### ISSUE TITLE
Social Network features

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1000]
As a user, I can "follow" an enterprise or "join" an enterprise. The OFN could then be used to send messages to customers, followers or members. This would open up a whole new world. The OFN would become a social network.

**Comment by RachL** [comment]
@mkllnk do you mind if we move this to discourse?

**Comment by Matt-Yorkley** [comment]
I remember discussing that at the Portugal gathering!

**Comment by mkllnk** [comment]
We discussed this a long time ago in Australia. We thought this feature may attract a lot of people. But at the moment I think we should focus on improving current features. I'm closing this. Feel free to open a topic on Discourse.
