### ISSUE TITLE
[Admin][Enterprise] Latitude and longitude fields are indicated as required but aren't required

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10008]
## Description
When you create an enterprise in the admin dashboard (admin/enterprises/new), as well as in an enterprise paramaters address (admin/enterprises/from-admin/edit#!#address_panel), latitude and longitude fields are indicated as required fields but aren't actually required. You can save without filling in these fields.

## Expected Behavior
If a field is not required, there should not be the red asterisk above it.

## Actual Behaviour
The latitude and longitude fields are indicated as required with the red asterisks, but aren't really required.

## Steps to Reproduce
1. Click "New enterprise" button in the dashboard (admin/enterprises/new)
2. Don't fill in the latitude and longitude fields
3. See that you can proceed
4. Go to Enterprise tab > Settings > Address
5. See that the fields are not filled

## Animated Gif/Screenshot
![Screen Shot 2022-11-16 at 20 21 42](https://user-images.githubusercontent.com/28386648/202280742-48393204-edc4-4e0f-a28b-206af7cf356d.png)

## Workaround
If you think lat and long required and don't want to type them manually, you can check the "Calculate latitude and longitude automatically from address?" box 

## Severity
bug-s4: it's annoying, but you can use it

**Comment by vviekk** [comment]
Please assign this to me
