### ISSUE TITLE
[Matomo] Track usage of "Shopping @ <shop>" button

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10000]
## Description

There are user reports pointing out that the "Shopping @ <shop>" button is not clear. To best assess how to improve this we would ideally track the usage of this button, and how often is it used.

![image](https://user-images.githubusercontent.com/49817236/187669679-6f05f2f0-c2f6-4325-8f81-c7629bd613b4.png)

**- As a:** Matomo user

**- I want to be able to do:** (specify the desired behavior)
(Link to others issues or resources to provide context > only if really necessary). -->

## Acceptance Criteria & Tests

1. When tracking is in place we should be able to  : 

- number of hits on the button, depending on the page the user is or comes from
- differenciate loggin or guest sessions

## Additional context

This came up [here](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1661776367331329?thread_ts=1661774901.651919&cid=CG7NJ966B).

**Comment by filipefurtad0** [comment]
Thanks @RachL , sound good - let's do that :+1: 

We've got some results on this:

![image](https://user-images.githubusercontent.com/49817236/202772663-22d2bb06-74ca-458b-85f6-fc34babdaa55.png)

But before closing the issue, I'd like to make sure it's actually working as intended. I've now clicked the `shopping @ button` on staging FR on the pages:
- details
- payment
- summary
- order confirmation
Let's see if this correctly appears on the results (only visible some hours later).

If all is good, I'd create the tag/trigger/goal in FR-prod, or any other instances. Let's see how it turns out :crossed_fingers:

**Comment by filipefurtad0** [comment]
Ok, this is now working as an `Event` - in FR production - see `Behavior` > `Events`:

![image](https://user-images.githubusercontent.com/49817236/207031699-ddb343b4-3c1e-48fd-9f94-f06769773772.png)

The two lines actually track the same behavior - it took over 24h for these lines to appear, after creating and deploying the tag/trigger. So I thought it was not working - although it was debugged in test mode - and ended up created a slightly different version of it.

As to the acceptance criteria:

>    - number of hits on the button, depending on the page the user is or comes from

In order to have info on the page, I think we would have to create different `Events`, in which the triggers are activated as an additional criteria, so we can establish a comparison.

Another option would be to use Goals instead of Events, and funnel out results.

>    - differenciate loggin or guest sessions

I'm not sure how we can differentiate logged in vs. guest, as we can't access the `segmented view`, as described here:
https://matomo.org/faq/reports/get-insights-and-improve-your-site-with-events-report/

So, given that we're working cookieless: How can we distinguish session types (guest, logged)?

**Comment by filipefurtad0** [comment]
These are not code changes and GH will not track these, I feel it's usefulf to document how we reached this result, for the `Events` above - left: web inspector underlining the `Element` in question; middle: the Trigger which is activated when clicking any Element with `class` containing `current-hub` - these are actually are two, the `shopping @` and the `Hub's name`, so we could even differentiate this if we would like; right: the tag referring the previous trigger.

![image](https://user-images.githubusercontent.com/49817236/207037341-1a243bbb-f4fe-4f33-be58-f93dd9b41e62.png)

**Comment by filipefurtad0** [comment]
In any case, I think we can answer [this question](https://github.com/openfoodfoundation/openfoodnetwork/issues/10000#issuecomment-1317028017) already:

> good start is to first understand whether or not the button is used

I'd say yes, the button **is** used:

![Screenshot from 2022-12-12 12-06-03](https://user-images.githubusercontent.com/49817236/207040923-9e7fb576-269b-4e43-8904-ced17156d0fc.png)

Perhaps a good idea to leave it in production for a week or so, and let it gather some data.
Shall we close this @RachL - and specify improvements on other, upcoming issues?

**Comment by RachL** [comment]
sounds good to me!

**Comment by filipefurtad0** [comment]
> we are not cookieless (huhu the sentence) we use cookies with no personal data

Right! Thanks for that :pray: 

> I thought that we could track loggedin people, I will have a look again

Maybe it is possible, I'll try to figure it out as well. Let's keep in touch on this.

**Comment by filipefurtad0** [comment]
With Custom Reports, it seems to be possible to get the URL of a given Event, when it is triggered:



Label | Visits
-- | --
coopcircuits.fr/ - 0 - Click shopping @ | 32
coopcircuits.fr/account - 0 - Click shopping @ | 16
coopcircuits.fr/shops - 0 - Click shopping @ | 13
coopcircuits.fr/<shpo_1>/shop - 0 - Click shopping @ | 10
coopcircuits.fr/<shop_2>/shop - 0 - Click shopping @ | 7
coopcircuits.fr/<shop_3>/shop - 0 - Click shopping @ | 4
coopcircuits.fr/cart - 0 - Click shopping @ | 4
coopcircuits.fr/<shop_4>/shop - 0 - Click shopping @ | 4
coopcircuits.fr/<shop_5>/shop - 0 - Click shopping @ | 4


</body>

</html>

These are just the first 10 entries, for December 2022, on FR-prod. The data would need some major **cleaning**... For example, we have several entries for the order confirmation page, but these don't show at the top 10, because each URL is unique. It would make sense to sum these up. #learningpython :snake:

It seems also to be used in the `/cart` and `/map` page. I'll send you the full output for via DM @RachL as it contains several shop names and other info which might be sensitive.

So I guess this would cover the first acceptance criteria. As to:

> 2. differenciate loggin or guest sessions

I don't know how to go around this yet, but should be possible.

**Comment by filipefurtad0** [comment]
Alright!! :tada: 

There's a better way to do this: we can add a filter for a given Event category:

![image](https://user-images.githubusercontent.com/49817236/211300627-64735ad3-a236-4333-8452-177364e05f1e.png)
