### ISSUE TITLE
[Open my shop] Missing enterprise type choice in the "open my shop" process

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10007]
## Description
When creating an enterprise from the “Open a shop” button (https://coopcircuits.fr/sell), you’re not asked what type of enterprise (profile, hub or shop) you want to choose. So you end up with an alert on the Enterprises list page, and your enterprise doesn't appear on the map.

## Expected Behavior
At some point in the enterprise creation process, you should be asked what type of enterprise you want to choose (profile, hub or shop).

## Actual Behaviour
The choice is not there.
(before, at the end of the process you landed on this following page with the choice, but I can't manage to find the way to see it anymore 🤔
![Screen Shot 2022-09-20 at 10 47 15](https://user-images.githubusercontent.com/28386648/202279144-1d7bf113-5b8f-479b-8f9f-bb57f8015fab.png)
)

## Steps to Reproduce
1. Login as a user who isn't an admin yet (no enterprises)
2. On an OFN website landpage (for instance https://staging.coopcircuits.fr/), click the "Open my shop" button in the main menu
3. Follow the steps
4. In the admin dashboard > Enterprises, see the red alert on your enterprise

## Animated Gif/Screenshot
![Screen Shot 2022-11-12 at 14 12 33](https://user-images.githubusercontent.com/28386648/202278399-edd9f6aa-0d24-4b3f-adb6-e0e7702f6d8f.png)

## Workaround
You can choose the package afterwards

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by RachL** [comment]
@audez "open my shop" is not an OFN feature it's a translation that was tweaked. In anyway, when I click on "join" I'm always directed to the `/register` page. If I complete the registration I'm always redirected at the end to the choice. So I can't reproduce this.
If there is indeed a button that does not redirect to the `/register` page, then we need to fix this in translation. 
Otherwise reopen if you are sure you can reproduce it on staging, perhaps I'm missing something.

**Comment by audez** [comment]
I reproduced it well:

https://user-images.githubusercontent.com/28386648/202320133-06751f55-7b67-4d69-831a-c0490c853e44.mp4

But i also reproduced with landing on the choice page as you said

Actually the following happens: 
- when you create a new enterprise from the /register page, in the end you have a button "Go to the dashboard" that brings you to the pack choice page (admin/enterprises/enterprise_name/welcome). But you can quit this page (by clicking on "Account" or "Logout" or simply closing the window, and never end the process. 
- If you do this, you'll have the alert on the Enterprises list page, and your enterprise doesn't appear on the map.
- And then if you create a new enterprise from the /register page, when clicking on "Go to the dashboard" in the end, that brings you to the homepage instead of the pack choice page. You're never asked anymore to choose the pack

i'll update this later :)

**Comment by RachL** [comment]
@audez 

> I reproduced it well:

Nope as you've used an email that already has enterprises. That case was never treated in the enterprise creation as the design assumed you would use the admin section to create the enterprise when you already have one. To see the choice of the pack you must use a fresh email with 0 enterprises.

> But you can quit this page (by clicking on "Account" or "Logout" or simply closing the window, and never end the process.

Two additional info

- Actually if it's the first ever enterprise of the email, on the first login in the admin section you'll have the choice of the pack.
- It's "normal" that you can quit the page. Previously the register process was designed to end here. But a lot of people didn't find how to find the admin section. So with a papercut we tweacked this page by adding a button to go to the admin side to see the choice of the pack (which, again, appears when it's your first registering).

Just to not be missunderstood: I'm not saying this is the perfect onboarding.Just that we can't fix this with a bug issue, we must either find papercuts that work with all cases or redesign our register process.

**Comment by audez** [comment]
thanks for the input, i've written a wishlist: https://github.com/openfoodfoundation/wishlist/issues/381
