### ISSUE TITLE
Introduce a "Filter results" button on the BOM page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10017]
## Description

**- As a:** enterprise user or super admin
**- On page:** `admin/orders/bulk_management`
**- I want to be able to do:** 

Currently each time you change a filter, the content of the page reloads. This can generate a lot of uneccessary request and is not consistent on what we have on the other pages.

The proposal is to mimic the behavior of the order list : 

Current BOM page : 

![image](https://user-images.githubusercontent.com/6525576/202483608-838743a5-9d9f-413b-a671-f0cf13b8481e.png)

What we want to do: 

![image](https://user-images.githubusercontent.com/6525576/202485056-bd705bcc-3cb9-4a15-b339-beab5f192a81.png)

For now, let's keep current behavior of showing the past week by default. We only change how we get results : we need to press the button instead of just using filters.

## Acceptance Criteria & Tests

1. Log in as enterprise manager
2. Go to BOM
3. See that you need to use the filter button to get different result than the past week
4.Check the clear filters button is still working

**Comment by jibees** [comment]
On the `/admin/orders`:
 - the orders are loaded on the first page load. Should we mimic the same behavior?
 - the date range selector is empty (select all the orders then). Should we mimic the same behavior?

Thanks!

**Comment by RachL** [comment]
@jibees 

> the orders are loaded on the first page load. Should we imitate the same behavior?

We can load first week like we do now yes.

so the date selector should be current week per default.
