### ISSUE TITLE
[Analytics - DE] Matomo Tracking code missing from page source code  

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10020]
## Description

Since recent changes, the Matomo tracking code seems not to be generated in the pages from the OFN-DE.

## Expected Behavior

Tracking code should be automatically generated and appended to the webpages source code.

## Actual Behaviour

Tracking code is absent from the source code.

## Steps to Reproduce

1. Visit `view-source:https://openfoodnetwork.de/`
2. Compare with `view-source:https://openfoodnetwork.org.au/`, for example.

## Animated Gif/Screenshot

-

## Workaround

-

## Severity

This would be an Analytics - S2

## Your Environment

* Version used: probably since v4.2.15
* Browser name and version: All
* Operating System and version (desktop or mobile): All

**Comment by RachL** [comment]
@filipefurtad0 I don't think it's a bug. I've just remembered that I've never set up the tag manager for small instances. As before we only needed the tag manager to follow some specific goals, I only set it up for 3-4 main instances. that was enough to get data.
