### ISSUE TITLE
Add Windows specific steps in Docker setup guide to run docker/build and docker/server scripts

### ISSUE THREAD

**Issue by vviekk** [openfoodfoundation/openfoodnetwork#10021]
### What we should change and why (this is tech debt)

Update the [Docker setup](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/docker/README.md) doc to include additional steps required for setting up dev env on windows with Docker.
These few steps will make the setup more uniform across devs as they all run the same script to set up instead of translating the bash commands from the scripts to run for their individual machine.

### Context

Slack Thread - https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1668593679216319
During dev env setup on a windows machine, I realized that there are some steps missing to set up Ubuntu WSL to be able to run the scripts that pull Docker images and build containers. 
One way is to try and look into the docker/build and docker/server scripts and create mapping commands to run on windows. This could be error prone and may result in inconsistencies across different machines.
To keep the setup consistent, its easier and safer to run the scripts in the repo for setup. To do that on windows, we have to add the following steps in the Docker guide:

- ----- After creating a local copy the repo from git----
- Install WSL ubuntu distribution by running `wsl --install Ubuntu` on Windows PowerShell or Command Prompt.
-  Install Windows Terminal from Microsoft Store or website.
- Spin up Ubuntu WSL on Windows terminal and finish the basic setup. For more details see [this](https://learn.microsoft.com/en-us/windows/wsl/install).
- In Windows Terminal settings, change the working directory of Ubuntu WSL to that of the repo. 
- Go to docker settings and enable WSL and Ubuntu. Details [here](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers).
- Spin up Ubuntu on Windows Terminal and go to the root of the repo.

- ---------Then continue on to running the docker/build and docker/server scripts ------

### Impact and timeline

Impact - Make the dev env setup easier for windows machine for all the new devs trying to work with docker.
timeline - Stand alone change, can be done whenever.

**Comment by heroinedor** [comment]
From my point of view, only modifying the documentation is not enough.
The scripts in the docker folder are meant to be used only on linux (mayb on macos ?), so they have to be duplicated with a Windows version to be useful for a developer working on Windows.
Can I take over this issue and make it more general like "make it easy to use OFN with docker on Windows" ?
