### ISSUE TITLE
Add Final Weight to Order Cycle Customer Totals report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#10036]
## Description

In the 'Bulk Order Management' page (BOM) you can change the weight of a sold product. Currently there is no way to see this information in the reports.

Let's add an additional column to the OC Customer Totals report on each line item that has a Final Weight for that line item.

In the case that the weight has not been changed in BOM this column should give the variant weight
In the case that the weight has been changed in BOM and qty = 1 this column should give the change weight
In the case that the weight has been changed in BOM and qty > 1 this column should give the sum of changed weights eg if 2x salad were 145g and 160g then the value should be 305g

## Acceptance Criteria & Tests

1. Add new column to the 'Order Cycle Customer Totals' report - 'Final Weight'
2. Column to be added to the end of each row.
3. Ensure that the 3 cases outlined above are all met. Test with qty of 1, 2 and something >2 at least.
4. These columns to be hidden by default in UI. API will return all data 'columns'.
5. All fields translatable
6. Unit test to cover this functionality.

**Comment by abdellani** [comment]
Hi @lin-d-hop 

For the third case, the weights' sum will be rendered in the summary row, right?

**Comment by lin-d-hop** [comment]
Hi @abdellani 
No incorrect.
The weight will _always_ be displayed in the line item row and _never_ in the summary row.

When the line item has a qty > 1 then there is the chance that the BOM has updated the weight to 2 different weights. Thus we will need to sum them to offer any information at all. So far all line items with qty>1 we will sum the weight of the line item.

Does that make more sense?

**Comment by abdellani** [comment]
@lin-d-hop 
Sorry, I'm still confused. Maybe I misunderstood the problem.

I have a product with two variants:
![image](https://user-images.githubusercontent.com/16113997/203993027-267bbf03-6fe9-4e34-936e-aca434997cdf.png)

I make an order of 1Kg with quantity=3
![image](https://user-images.githubusercontent.com/16113997/203994137-0154510b-5f9e-4645-a16e-2944940b38be.png)

The order will have only one line item:
![image](https://user-images.githubusercontent.com/16113997/203994407-4e2f4acb-4e89-48cf-8cbd-6857806c28ee.png)

I change the weight to 4000 (4Kg)
![image](https://user-images.githubusercontent.com/16113997/203994558-e9e72bc4-d6c2-4a8d-aef3-16bd25dea3f4.png)

The line item is updated now:
![image](https://user-images.githubusercontent.com/16113997/203994702-5ea4c021-ee75-401b-862f-9962b6fbaf72.png)

I don't see how 
- a line item can have more than one weight.
- an order has more than one line item referring to the same variant

According to what I understand, every line item refers to a unique variant. 

- If a new item is added to an existing order, and 
- that item refers to a variant that already exists in the order.
- This new item will be merged with the existing one.

![image](https://user-images.githubusercontent.com/16113997/203999144-c18342ba-c6f3-4ff5-b380-eeccdb4ea8b1.png)

the result
![image](https://user-images.githubusercontent.com/16113997/203998556-ef0fa8ac-9dd7-41f3-b6e0-2029a2d0eb25.png)

![image](https://user-images.githubusercontent.com/16113997/203999270-fa6753ee-cd58-4ee3-8809-b8256e154eac.png)

**Comment by lin-d-hop** [comment]
Hi @abdellani 

In Bulk Order Management you can change the line item of a weight after ordering:

![Screenshot from 2022-11-25 14-00-00](https://user-images.githubusercontent.com/8669848/204001654-c2548e42-8fac-4c59-87ad-56d8e381db8d.png)

This is to account for products like cheese from the round - when it is cut it might be a different weight to what was ordered.

I am not sure where this is stored in the DB but can dig that out if you get stuck.

Hope that helps :)

**Comment by RachL** [comment]
@lin-d-hop I think @abdellani found the correct field? So actually the user is already putting the final sum, there is no additional multiply by quantity to do?

**Comment by lin-d-hop** [comment]
Ah ok great. The user doesn't do this - seems OFN does this....
This might be something we need to look at more closely. BOM separates the items out and I have no idea how the logic to recombine and separate again works... :thinking: 

We need to test if this works with BOM - I don't know if the BOM data is stored elsewhere?

**Comment by RachL** [comment]
@lin-d-hop 


I think then the UI is confusing. Because it looks like asking for the total weight of the quantity (when you edit it°. I agree that wihtout doing anything the multiplication happens. But if you edit the weight, it looks like you need to enter full weight and not weight per item?

**Comment by RachL** [comment]
Actually, if we look at Mohamed's screenshot we have the answer: when he put 4000 in weight, he had 4000 in the line_item.final_weight_volume . So I guess we just want that value to appear in the report?

**Comment by lin-d-hop** [comment]
But the BOM puts a different row for each ordered item no?
I definitely tested this... so now I'm confused

**Comment by lin-d-hop** [comment]
Mohammed hasn't used BOM - just variant editing. So there's a missing step

**Comment by lin-d-hop** [comment]
Oh sorry, I see now he did. I missed that

**Comment by lin-d-hop** [comment]
Ok, ignore everything I said :)

Tis correct just to put final_weight_volume in the report....

I'll retest the thing with each line item getting a new line in BOM... I must have made a mistake there

**Comment by abdellani** [comment]
So, I'll just add the `final_weight_volume` to the report.
