### ISSUE TITLE
Add Variant SKU to Order Cycle Supplier Totals report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#10030]
## Description

As an enterprise user, I want to be able to access variant SKUs from the reports.
Let's add it to the Order Cycle Supplier Totals report

## Acceptance Criteria & Tests

1. Variant SKU added to the line item rows of Order Cycle Supplier Totals report
2. To be added to the end of each row.
3. These columns to be hidden by default in UI. API will return all data 'columns'.
4. All fields translatable
5. Unit test to cover this functionality.

**Comment by RachL** [comment]
@lin-d-hop actually I left this issue in review as the need is probably answered by https://github.com/openfoodfoundation/openfoodnetwork/pull/10023

So unless another instance needs it, there is no rush to add a column.

**Comment by lin-d-hop** [comment]
Another besides AU?

**Comment by RachL** [comment]
No FR: https://github.com/openfoodfoundation/wishlist/issues/314

**Comment by abdellani** [comment]
@lin-d-hop 
The new column will be rendered by default?
