### ISSUE TITLE
Add 'on hand' and 'on demand' to Products report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#10035]
## Description

As an enterprise user I would like a report that tells me what stock I have.

The following fields should be added to the Products & Inventory -> Products Report:
'On Hand' that displays the stock level
'On Demand' displays if the product can be ordered on demand from the supplier.

In the DB these fields are hard to find - they are in spree_stock_items.count_on_hand and (I think) spree_stock_items.backorderable

On hand and On demand are translated fields already used in Bulk Edit products and other places, so best to use the same translation for consistency.

Note that we will be IGNORING inventory overrides in this. This needs to be communicated to the user as a warning on the reports page. Let's use the same UI as in the Packing reports when we let users know that names might be hidden (as in the bottom of this screenshot)
![Screenshot from 2022-11-21 11-41-55](https://user-images.githubusercontent.com/8669848/203042888-fd6b5478-5f04-4d59-8597-54cf5f1134b5.png)

The warning should read:
> Note that stock levels reported are from supplier product lists only. If you are using Inventory to manage your stock quantities these values will be ignored in this report.

## Acceptance Criteria & Tests

1. Add two new columns to the 'All Products' report - 'On Hand' and 'On Demand'
2. Columns to be added to the end of each row.
3. Ensure that the translation is consistent with the Products pages.
4. Only use the product level quantities for this. Inventory overrides will be ignored.
5. A warning is displayed to the user to let them know that Inventory settings will be ignored.  
6. These columns to be hidden by default in UI. API will return all data 'columns'.
7. All fields translatable
8. Unit test to cover this functionality.

**Comment by abdellani** [comment]
Hi @lin-d-hop 

A variant has many `spree_stock_items`.

I can easily calculate the `on hand` by making the sum cross the stock_items
```ruby
on_hand : variant.stock_items.sum(&:count_on_hand) 
```

But for the `on_demand`, is it possible to have a variant with more than one `stock_item`, where each `stock_item` has a different value for `backorderable`? 
if yes, how can we decide to show "Yes" or "No" in the report?

**Comment by abdellani** [comment]
I have an answer now.
There's a one-to-one relationship between `variants` and the `stock items`.

**Comment by dacook** [comment]
Hi @abdellani , thanks for progressing on this. I'm still unsure about this logic, but have to admit I also don't know this area of the system yet.

> * There's a one-to-one relationship between variants and the stock items.

Actually, variant has one-to-many relationship with stock items: 
https://github.com/openfoodfoundation/openfoodnetwork/blob/f25fb19fe82487d92d5b7f5f1a871a4d6da435a3/app/models/spree/variant.rb#L29

I can see that each set of "stock items" exist in a "stock location", which isn't linked to an enterprise (in fact I can't even find it in the admin interface). So they represent different physical stock in different locations. I'm worried that by showing a value from just the first stock item record, we're not seeing the full picture and could mislead people.

**Comment by dacook** [comment]
So (continuing my comment from the PR), it looks that the 'On Demand' column should be referring to `variant.on_demand`, rather than the `spree_stock_items.backorderable` that Lynne suggested.
I have to admit I'm still a bit confused, so I could be wrong. @lin-d-hop are you able to comment?

**Comment by abdellani** [comment]
> > * There's a one-to-one relationship between variants and the stock items.
> 
> Actually, variant has one-to-many relationship with stock items:
> 
> https://github.com/openfoodfoundation/openfoodnetwork/blob/f25fb19fe82487d92d5b7f5f1a871a4d6da435a3/app/models/spree/variant.rb#L29
> 
> I can see that each set of "stock items" exist in a "stock location", which isn't linked to an enterprise (in fact I can't even find it in the admin interface). So they represent different physical stock in different locations. I'm worried that by showing a value from just the first stock item record, we're not seeing the full picture and could mislead people.


@dacook I noticed that too.
According to what I understood during the last meeting, some parts of the system (like this part) are overengineered. 
So it's true that a `variant` can have more than one `stock items`, but in reality, a variant is connected to only one stock item.

**Comment by dacook** [comment]
>  some parts of the system (like this part) are overengineered.

Thanks for letting me know, it's good to be aware of this.
Perhaps one day we should update the stock_items association to represent this truth.. but not today.

**Comment by lin-d-hop** [comment]
assume that I am wrong :)
