### ISSUE TITLE
StimulusReflex caching warning

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10048]
### What we should change and why (this is tech debt)

Were currently seeing this warning, when running the app/specs in the dev/test environment: 

Heads up! 🔥

👉 StimulusReflex requires caching to be enabled. Caching allows the session to be modified during ActionCable requests.

To enable caching in development, run:

  rails dev:cache

### Context

This came up here:
https://github.com/openfoodfoundation/openfoodnetwork/issues/7853#issuecomment-1306875605

**Comment by jibees** [comment]
This warning appears because we don't use cache in Dev: 

https://github.com/openfoodfoundation/openfoodnetwork/blob/a95bef141faf76fa9eda85d64d89c876c7aff8ba/config/environments/development.rb#L30

If we start the server by setting `DEV_CACHING` env. variable to `true`
```
DEV_CACHING=true bundle exec rails s -p 3000
``` 
it's ok ...

**Comment by jibees** [comment]
So, the next discussion is: should we activate caching in development mode?

I'm not sure which strategy we should use around making caching disabled by default. 
 - Pros
    - Development mode is closer that production logic, then it's easier to catch (caching) bugs.
  - Cons
    - If we want to debug some DB/model queries, then we probably need to deactivate caching. 


@openfoodfoundation/core-devs do you guys have any thoughts?


(https://github.com/stimulusreflex/stimulus_reflex/issues/258)

**Comment by abdellani** [comment]
@jibees 
I was checking the discussion. Does [this mean](https://github.com/stimulusreflex/stimulus_reflex/issues/258#issuecomment-693643107)  that if the cache is off,  the SR features will not be available?

**Comment by jibees** [comment]
I don't think so, because it actually works in dev. env. when caching is off ;)

**Comment by abdellani** [comment]
@jibees 
Yes, I confirm. The code from PR referred to in the last [comment](https://github.com/stimulusreflex/stimulus_reflex/issues/258#issuecomment-693643107) is updated.

They're just showing a [warning now](https://github.com/stimulusreflex/stimulus_reflex/blob/13c8d48fb385d9dffea909fc20709b0723ba81a3/lib/stimulus_reflex/utils/sanity_checker.rb#L38).

I vote for enabling the cache.

**Comment by binarygit** [comment]
I agree, we should enable caching
