### ISSUE TITLE
[Deprecation warning] Enumerating ActiveModel::Errors as a hash has been deprecated.

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/openfoodnetwork#10044]
### What we should change and why (this is tech debt)

```
DEPRECATION WARNING: Enumerating ActiveModel::Errors as a hash has been deprecated.
In Rails 6.1, `errors` is an array of Error objects,
therefore it should be accessed by a block with a single block
parameter like this:

person.errors.each do |error|
  attribute = error.attribute
  message = error.message
end

You are passing a block expecting two parameters,
so the old hash behavior is simulated. As this is deprecated,
this will result in an ArgumentError in Rails 7.0.
 (called from rescue in save_master at /home/runner/work/openfoodnetwork/openfoodnetwork/app/models/spree/product.rb:418)
```

### Impact and timeline

Preparation for Rails 7 upgrade

**Comment by anansilva** [comment]
Hi @sigmundpetersen, [ just opened a PR for this.](https://github.com/openfoodfoundation/openfoodnetwork/pull/10482) Could you add me as an assignee there, so that I can add reviewers? Thanks!

**Comment by anansilva** [comment]
Ups, can't seem to add reviewers but thank you!

**Comment by sigmundpetersen** [comment]
Don't worry, you don't have to add specific reviewers.
Our process is such that when a PR is in the Zenhub 'Code Review' column, it will be picked up by a reviewer automatically.

**Comment by anansilva** [comment]
Ah, didn't know about this, thanks for sharing!
