### ISSUE TITLE
Suggestions for usability when adding new products in Bulk Edit Products

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1006]
These suggestions came from Peter Richardson who has been the Stroudco website manager for 4 years and who also sells plants on Stroudco.....

"Another thought... apart from wishing that my producer name was filled in by default when adding a new product, it would be nice if the system had a default product category for each producer so that mine would have 'plants' pre-selected as a category when adding a new product.  I expect most producers only use one category. Maybe most products don't come and go as quickly as plants, but for me adding a new product needs to be as quick as possible.

Anyway, I thought that the process of adding products was fairly intuitive, apart from the 'on hand' and 'on demand' boxes which could do with re-labelling I think as 'number available' and 'unlimited quantity'.

Heroic work, changing to the new system. Nice to see it as a national/international effort.

Peter"

**Comment by lin-d-hop** [comment]
#gitcull2017
