### ISSUE TITLE
Product images not displayed on shopfront - iPhone 13 and 14 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10063]
## Description

Product images are not being displayed on iPhone models 13 and 14 (browsers Safari and Chrome), when the user visits the shopfront. It has been reported that images on the backoffice are not loading either. For reference see [this thread](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1669597806740019).  

## Expected Behavior

Product images should display both on shopfront and backoffice, for models later than iPhone 12.

## Actual Behaviour

Product images are not being displayed, for models later than iPhone 12.

## Steps to Reproduce

1. Log in to Browserstack and select Safari or Chrome on iPhone 13 on 14.
2. Visit https://openfoodnetwork.org.au/fat-beets-food-hub/shop#/shop
3. Notice images are not displaying
4. Switch browser to  iPhone 12. See the product images load

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/204247354-7da31e6d-3f6a-4928-b5a9-4b7145096a49.png)

![image](https://user-images.githubusercontent.com/49817236/204247366-6a0c61a9-1cc8-4837-8e17-609eccb69e85.png)

## Workaround

Using the app without images.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.2.2
* Browser name and version: browsers Safari and Chrome
* Operating System and version (desktop or mobile): mobile, iPhone models 13 and 14; Desktop Safari, version 15.5 on macOS Monterey version 12.4

**Comment by jibees** [comment]
Seems like images doesn't appears on Safari mac as well.

**Comment by abdellani** [comment]
I'm wondering if the problem is related to the image format or to some security restrictions on those devices.
Are the images downloaded and not rendered (or maybe rendered but not visible)? or they are not downloaded at all?
