### ISSUE TITLE
[Missing translation] Tax category 'None' can't be translated for edit product page

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10060]
## Description

The tax category 'None' can't be translated on the edit product page. It is translated on the create new product page though.

## Expected Behavior

'None' on the edit product page should be translated using the same string as on the create new product page.

## Actual Behaviour

'None' can't be translated on the edit product page.

## Steps to Reproduce

1. Select a language other than English.
2. Go to admin/products.
3. Select the edit icon of a product.
4. Look at the available values in the tax category dropdown.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/1790176/204150441-eda9110a-2b68-4202-bc4a-79e483db10c5.png)

## Workaround

None. 

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.2.23
* Browser name and version: Firefox 107
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by vviekk** [comment]
Hi, Please assign this to me :)

**Comment by vviekk** [comment]
@drummer83 Yes, I think I understand.
![image](https://user-images.githubusercontent.com/91144693/204839172-a3215d6d-3a0b-4696-b06a-610a92160937.png)
![image](https://user-images.githubusercontent.com/91144693/204839262-4ef0f640-ef82-453f-9b7f-b52f7972ec3e.png)

It shouldn't be the text 'None' in the first image. It should be the same are the second image (translated accordingly).
