### ISSUE TITLE
Open Street Map logo not showing on Groups map

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1007]
## Description
Open Street Map contributor "logo" not showing on group maps.

## Expected Behavior
As it is displayed on the "map" page
![screenshot from 2018-02-28 16-44-20](https://user-images.githubusercontent.com/8135376/36796958-1ab75c74-1ca7-11e8-82e5-63bb0ee6870d.png)
we should display the Open Street Map contributor logo on the group map.

## Actual Behavior
Open Stree Map contributors logo not displayd on group map:
![screenshot from 2018-02-28 16-45-03](https://user-images.githubusercontent.com/8135376/36796983-29e821e2-1ca7-11e8-9346-38bafbaed327.png)

## Steps to Reproduce
1. Go to "groups" menu, choose any group.
2. Look at the map, you don't see the OSM contributors logo.

## Severity
S3, not crucial but quite a few  users look at map page and it's important to pay attribution credits to OSM contributors for the tiles we use (and showing support to OSM that way, first step before we can go further!)

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by daniellemoorhead** [comment]
Will come back to this once changes to the groups design that come out of the Thrive work have been determined.

**Comment by sigmundpetersen** [comment]
This seems to have been fixed 🎉
