### ISSUE TITLE
Should product searches only search for whole words?

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1008]
If I search for "tea" on the Stroudco shop front, I also get steaks! And because coffees are also in the same category of "tea & coffee" I also get coffees.

Should searches only match whole words? 
Should whole categories be listed if they match a search phrase?

**Comment by OliverUK** [comment]
@lin-d-hop what's your view on this? I do get some very strange results.

**Comment by NickWeir63** [comment]
Shall we set this up on the global forum for discussion?

**Comment by OliverUK** [comment]
Good idea. I'll post something.

**Comment by lin-d-hop** [comment]
Product searching has improved since this was created. Needs more spec and inception to be useful on github
