### ISSUE TITLE
[BOM] All orders within the date range aren't displayed after switching OC to "All"

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10091]
## Description
On the Bulk Order Management (BOM) Page, when selecting an Order Cycle (OC) in the dropdown list, and then selecting "All" in the same dropdown list, only the orders corresponding to the date range of the previously selected OC are shown.  

## Steps to Reproduce
1.  Connect to a shop that has several OCs with orders
2. On the BOM page (admin/orders/bulk_management), see that all orders within the "Date range" field are displayed
4. Select an OC in the "Order Cycle" dropdown list, see that orders corresponding to the OC are shown 
5. Select "All" in the "Order Cycle" dropdown list. See that only orders corresponding to the previously selected OC date range are shown 

## Animated Gif/Screenshot

![dropdungbb](https://user-images.githubusercontent.com/28386648/205381605-4d1cb78d-22c8-4f24-a105-d6b1d07f4a64.gif)

### Original call: date range = november 25 to december 3 - OK
METHOD: GET
URL
https://staging.coopcircuits.fr/admin/bulk_line_items.json?q%5Border_completed_at_gteq%5D=2022-11-25T00:00:00%2B01:00&q%5Border_completed_at_lt%5D=2022-12-03..

### After selecting "OCDELAVEGA" Order cycle: date range = nov 28 to december 1  -OK
METHOD: GET
URL
https://staging.coopcircuits.fr/admin/bulk_line_items.json?q%5Border_completed_at_gteq%5D=2022-11-28T00:00:00%2B01:00&q%5Border_completed_at_lt%5D=2022-12-01...

### After selecting "All": date range = nov 28 to december 1  - KO
METHOD: GET
URL
https://staging.coopcircuits.fr/admin/bulk_line_items.json?q%5Border_completed_at_gteq%5D=2022-11-28T00:00:00%2B01:00&q%5Border_completed_at_lt%5D=2022-12-01...

## Workaround
Reload the page.

## Severity
bug-s3: a feature is broken but there is a workaround

## Possible Fix
When sending the _GET admin/bulk_line_items.json_ request, in the _order_completed_at_gt_ and _order_completed_at_lt_ parameters, send the dates of the "Date range" field instead of the dates of the previously selected OC.

**Comment by RachL** [comment]
We are going to remove the behavior of selecting dates when selecting OC here: https://github.com/openfoodfoundation/openfoodnetwork/issues/10242

that should fix it. We can reopen if not the case.
