### ISSUE TITLE
[Product import] 500 error when a product has "0" in the unit value field 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10101]
## Description
When importing a product file with "0" in the "units" column, a message "No error detected" is displayed to the user, but after clicking the "Save" button the import is stopped and an ugly error message appears on screen. 

## Expected Behavior
The import should be stopped when clicking the "Upload" button, with a proper error message, as "1 error prohibited this record from being saved: Unit value must be greater than 0."

## Actual Behavior
The import is allowed and the following request triggers a 500 Internal Server Error, leading to an ugly message being displayed to the user.

POST | https://staging.coopcircuits.fr/admin/product_import/save_data

## Steps to Reproduce
1. On import page (admin/product_import), import a csv file with "0" value in the "units" column. 
Test file: 
[RAHDK.csv](https://github.com/openfoodfoundation/openfoodnetwork/files/10155879/RAHDK.csv)
2. Click "upload" button, then "import" button, and see the message "No errors detected!", click Save

### After clicking the "Upload" button
![Screen Shot 2022-12-05 at 17 08 55](https://user-images.githubusercontent.com/28386648/205686992-ad51cb59-ed85-40c0-b02d-9515a67adb1f.png)

### After clicking the "Save" button
![Screen Shot 2022-12-05 at 17 09 11](https://user-images.githubusercontent.com/28386648/205687022-d6f9509f-9962-4588-86c1-60c32baf9f49.png)

## Workaround
Don't put 0.

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by vviekk** [comment]
@audez 
Hi,
I'm working on adding the checks for the import. Issue - #9978
This seems like a low hanging fruit for the changes I am making.

If for this issue, we only need invalidate '0' for `UNITS`, I can add that check with the others.
Please confirm if I can do this in the same PR.

**Comment by audez** [comment]
Hi @vviekk yes indeed! thanks a lot :)
