### ISSUE TITLE
Remove unresponsive 'save changes' button from 'bulk edit products'

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1010]
From: Peter Richardson
Sent: 18 May 2016 11:37
To: Nick Weir
Subject: bulk edit products screen - further feedback

Hi Nick,

I've just used the bulk edit products screen again.  There is a 'save changes' button at the top and another at the bottom - I only saw and used the one at the bottom before. The one at the top behaves usefully, telling you when it has saved changes - it's only the one at the bottom which is confusingly unresponsive - simplest just to get rid of this one.

Peter

**Comment by OliverUK** [comment]
I guess it's not so much that the button is unresponsive but the "saving" and "saved" notification only show at the top. Something one quickly gets used to.

**Comment by daniellemoorhead** [comment]
Hey @oeoeaio and @mkllnk how easy would it be to have the two save buttons on this page do the same thing? ie. having the "saving" and "saved" notifications displaying at the top and the bottom?

**Comment by mkllnk** [comment]
@oeoeaio You probably know this one better. But I think that it would be quite easy to display the notification next to the button. Something between 1 and 3 hours.

**Comment by stveep** [comment]
Maybe I'm missing something, but on the admin/products/bulk_edit page I only see one save button (on the save bar at the bottom of the screen) - it only appears when a change has been made, and responds correctly with "Saving..." and "Saved" messages. So everything looks fine to me. I'm wondering if @bingxie 's other work on the save bars has fixed this since the issue was opened?

**Comment by daniellemoorhead** [comment]
@bingxie and @oeoeaio and @mkllnk are you able to shed some light for @stveep?

**Comment by bingxie** [comment]
Yes, now we have the same save bar on serval pages includes the bulk edit products page. And it acts like @stveep said. So I think we can close this issue.

**Comment by daniellemoorhead** [comment]
Great, thanks @bingxie. @stveep sorry for the confusion :)
