### ISSUE TITLE
[Reports] In "Order Cycle Customer Totals", incorrect sorting when lastname first letter isn't capitalized

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10117]
## Description
In the "Order Cycle Customer Totals" report, customers who don't have a capital letter for their last name will appear in the end of the list, instead of appearing in alphabetical order.

## Expected Behavior
Names should be sorted alphabetically whether the first letter is capitalized or not.

## Actual Behaviour
Names with lowercase first letter will appear after names with capitalized letters. If there are several names with lowercase first letter, they will be sorted alphabetically between them, but always appear after the capitalized ones. 

## Steps to Reproduce
1. Pass 4 orders with different names, of which 2 having a lowercase first letter for the last name (for instance "Dont Worry", "Chamois xaxa", "bou yaka" and "Ave Zebu")
2. In the "Order Cycle Customer Totals" report (admin/reports/orders_and_fulfillment), see that the lowercases ones appear in the end of the list ("Chamois xaxa" and "bou yaka" will appear after "Ave Zebu") 

## Animated Gif/Screenshot
![Screen Shot 2022-12-07 at 21 59 47](https://user-images.githubusercontent.com/28386648/206297594-6086a846-85da-4a1b-9787-4149268bc370.png)

## Workaround
The producer who raised the issue re-classify the names in Excel.

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by lin-d-hop** [comment]
@audez Sorry maybe I am being daft....
These are sorted by last name right?
So ogive before poustik makes sense?

I must be missing something.... :thinking:

**Comment by sigmundpetersen** [comment]
> So ogive before poustik makes sense?

But both of them should come before Yoo and Zoo, no?

**Comment by lin-d-hop** [comment]
Ah, yep, thanks Sigmund. I'll blame jetlag for not seeing that :joy:
