### ISSUE TITLE
Change OC page colors

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10125]
## Description
**- As a:** enteprise and super admin using feature toggle
**- On page:** `/admin/order_cycles` and sub pages
**- I want to be able to do:** 

- [x] Base the work on previous PR 

- [x] Fix table : 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/d5b23ad7-bfe7-44ba-9d1a-3757972bd9cd)

- [x] Turn "clear all" as secondary button

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/5ee04f4c-82e6-4952-92a4-3b326a69754a)

- [x] if not fixed by previous PR, placeholder need a darker grey: 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/32d70671-f24a-4db4-92ef-ca289ccab902)

- [ ]  Change columns selector to introduce same component than in reports

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/895d4939-a059-48ff-8d2f-406fa6c1fda2)

- [x] Green yellow and grey need to cover whole line

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/3910ad42-ecae-4cd9-8a2d-c60ae9ea690f)

- [x] Use white on blue when selected and white on grey when not? 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/f0afd20f-47a7-4cab-96b0-3bd4d6867bd1)

same as in but maybe we can use darker grey in both cases : 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/76586e43-aac3-418b-b2fb-019c2159d4b3)

- [x] Fix tag color

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/49c5c00a-1687-430d-b04f-4aa52f7f3eed)

- [x]  Use correct `#017a9a` blue

![image](https://user-images.githubusercontent.com/6525576/206479408-af8478cf-a66c-423a-aff5-9dca4a3a9d59.png)

## Acceptance Criteria & Tests

1. check the task are done
2. check old colors stay active without feature toggle

**Comment by jibees** [comment]
>Green yellow and grey need to cover whole line

I don't think it's necessary/wanted because the design _specifies_ that action icon buttons are _outside_ the `<table />`:
<img width="1312" alt="Capture d’écran 2022-12-08 à 16 35 12" src="https://user-images.githubusercontent.com/296452/206488364-25ba6fbd-32a4-4aea-9300-8bd245f07171.png">

**Comment by RachL** [comment]
@jibees I think that if we follow BUU icons will be changed at some point by an action dropdown : 

![image](https://user-images.githubusercontent.com/6525576/206489098-30f407bb-d258-4a78-bc37-2d3ae8410f84.png)


I didn't want to introduce this action dropdown yet to not introduce too many changes at the same time. Also I think it's better to introduce such a dropdown when it's always possible to do these action in bulk. Introducing without bulk, means more clicks...

So... long story short: I think the table should still be above the icons? Like we did for orders : 

![image](https://user-images.githubusercontent.com/6525576/206489890-8a282a30-12ca-421d-b9df-a62bdfb2e5f0.png)

I'm ok if the colors stop before, although it's a bit weird visually we can live with it for now.

**Comment by jibees** [comment]
I think your absolutely right + I'd name that columns with 'Actions' label.

I was confused because it's not what I've done in `/admin/orders/R1234`:

![Uploading Capture d’écran 2022-12-08 à 16.41.43.png…]()

**Comment by jibees** [comment]
Proposal:

<img width="980" alt="Capture d’écran 2022-12-08 à 16 44 41" src="https://user-images.githubusercontent.com/296452/206491409-0466dd2f-fdb8-444d-acf4-05633e4c9a9e.png">

**Comment by RachL** [comment]
> because it's not what I've done in /admin/orders/R1234:

ah my bad then! i agree with colum title and we need to change again in edit orders page sorrrry

Ok for the progress proposal

**Comment by jibees** [comment]
> ah my bad then! i agree with colum title and we need to change again in edit orders page sorrrry

No worries. It was a bit painful ; probably needs a PR for it (tooooo manyyyy PRSsssssss ; i'm lost)

**Comment by jibees** [comment]
> Good thing split checkout is going to be design ready soon

![giphy](https://user-images.githubusercontent.com/296452/206493439-78df8030-53f5-4580-8474-ce936dd0ed26.gif)

**Comment by jibees** [comment]
>  Change columns selector to introduce same component than in reports

It's not that easy, and this is not what I've done in `/admin/orders`. Shouldn't we create an issue/PR for that specific case?

**Comment by RachL** [comment]
@jibees there is no column selectors in `/admin/orders` - what are you refering to?

**Comment by jibees** [comment]
> @jibees there is no column selectors in /admin/orders - what are you refering to?

Right sorry. I was refering to this component: 
<img width="361" alt="Capture d’écran 2022-12-09 à 09 58 49" src="https://user-images.githubusercontent.com/296452/206664204-a03c09f9-1c22-494c-aa17-0b29d4591836.png">
which use the same classes

**Comment by RachL** [comment]
the column component is also on BOM and customer pages... perhaps using one of these issues then to handle it?

**Comment by jibees** [comment]
> perhaps using one of these issues then to handle it?

My point is to say that, to my point of view, this is a bit outside of the scope of the work for v2.
