### ISSUE TITLE
Follow up UK disk space usage

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#10132]
### What we should change and why (this is tech debt)
There was an issue causing the disk usage to keep growing on the UK server. Specifically, the postgres write-ahead logs never got cleaned up, until (presumably) the server restarted.

So we need to check if disk usage has continued to grow in this manner, and if so, fix Postgres to clean up the folder properly.

### Context

https://github.com/openfoodfoundation/openfoodnetwork/issues/10107
https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1670174312119459

When checked, the folder was 35gb:
```
sudo du -sh /var/lib/postgresql/9.5/main/pg_xlog
35G 	/var/lib/postgresql/9.5/main/pg_xlog
```

Now it is only 80mb:
```
81M	/var/lib/postgresql/9.5/main/pg_xlog
```

![Screen Shot 2022-12-09 at 8 34 36 pm](https://user-images.githubusercontent.com/4188088/206671108-67f657c0-0bcf-4f97-a87e-a22230a8409e.png)

### Impact and timeline
There's heaps of room on the server, so this may not become a problem for a long time. 
But if something is broken, it should be fixed pro-actively.

**Comment by dacook** [comment]
I suggest we check again in 1 month, so have set myself a reminder.

**Comment by mkllnk** [comment]
If the Metabase synchronisation is broken then we need to remove the replication slot:

* https://github.com/openfoodfoundation/openfoodnetwork/issues/9240#issuecomment-1162509356

**Comment by jibees** [comment]
As far as I know, metabase is disabled on every servers.

**Comment by dacook** [comment]
As per Maikel's comment, au-prod is disabled, and I can see it is also disabled on fr-prod:
```
openfoodnetwork=#  select * from pg_replication_slots;
(0 rows)
```

But it is enabled on uk-prod, and I'm not sure how to turn it off: 
```
openfoodnetwork=# select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid |    database     | active | active_pid | xmin | catalog_xmin | restart_lsn
-----------+----------+-----------+--------+-----------------+--------+------------+------+--------------+-------------
 debezium  | wal2json | logical   |  19600 | openfoodnetwork | t      |       8887 |      |     52567412 | 6E/2DD4FB0
(1 row)

openfoodnetwork=# select pg_drop_replication_slot('debezium');
ERROR:  replication slot "debezium" is already active for PID 8887
```

@mkllnk are you able to advise?

**Comment by dacook** [comment]
In terms of disk usage, I think it's no longer causing growth anyway, so I think this issue can otherwise be closed.
```
ofn-admin@production18:~$ sudo du -sh /var/lib/postgresql/9.5/main/pg_xlog
81M	/var/lib/postgresql/9.5/main/pg_xlog
```

**Comment by mkllnk** [comment]
That looks like the replication is still active and therefore it's not causing issues. We can leave it then and close this.

**Comment by RachL** [comment]
@mkllnk but metabase for UK is unsuable from the UI in metabase (last orders in April). Perhaps we should still stop this replication?

**Comment by mkllnk** [comment]
Yes, it's just draining memory and processing time on the prod server at the moment. We should probably do it when we get the whole n8n and Metabase thing standardised.

**Comment by dacook** [comment]
If it's draining memory and processing time on prod, then wouldn't it be worth de-activating it now?

I found a way to [force de-activate](https://stackoverflow.com/a/62878718/421243) it from the prod server. Is that ok with you @maikel?
```sql
select pg_drop_replication_slot('rep_slot');
    ERROR:  replication slot "rep_slot" is active for PID 162564
select pg_terminate_backend(162564); select pg_drop_replication_slot('rep_slot');
```

Ideally we'd stop the subscribing process (on the metabase server?), but it sounds like we haven't decided what to do with that so I wouldn't bother taking time to figure that out.

**Comment by dacook** [comment]
Ok, yes if it's unknown risk let's not make any further changes.
