### ISSUE TITLE
Shopfront won't load on iPad

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1013]
One of our Stroudco shoppers can't open the OFN shopfront on her iPad.  She is using Safari and says that it keeps trying to load but failing.  Do you need more information from her?

**Comment by pmackay** [comment]
It would be useful to know what version of iPad and what software version (go to Settings > General > About and note Version value).

My iPad often crashes and reloads large web pages these days. Pretty sure the Stroudco shop front will classify as a large web page...

If my recent PR re analytics can be merged, we can start to track them for the site and see how many people are using iPads, etc...

**Comment by NickWeir63** [comment]
Thanks @pmackay .   I asked those questions and got this response:
**iPad is 5 years old don't know what version

Software Version 8.4.1**

**Comment by pmackay** [comment]
Its quite an old device, so need to decide if this is important to solve. I suspect with the approach of loading the whole store on 1 page it will not be possible to reliably get it working on all old devices like this.

**Comment by pmackay** [comment]
Loaded slowly but OK on an iPad mini (2012 model) with iOS 9.3.1.

**Comment by pmackay** [comment]
@NickWeir63 is this ok to close for now?

**Comment by NickWeir63** [comment]
I think we were going to leave it open for the Aussies to put in their test results on other iPads so that we have a record of what works and what doesnt before we close it.  I will make a note to close it in a few days if that is OK

**Comment by oeoeaio** [comment]
Hi all,

At present we haven't got thorough testing on a wide array of devices as a part of our pipeline. I realise this would be ideal but at present its a matter of not really having the resources, which I'm sure you can appreciate.

The shopfront was very thoroughly tested on lots of devices at the time that is was built, and it is my understanding that it was working on all but the oldest devices, and in all browsers except IE 8 and down. Primary issue with old devices was memory if mine serves me correctly.

**Comment by daniellemoorhead** [comment]
@NickWeir63 let me know if Rob's response above is enough information for you to deal with responding to the shopper. I would assume that the older iPad she has doesn't have enough memory left to download all the products into the shop, if as Rob says memory was the issue they encountered when testing version 1.0 responsive design last May. Suggestions would be for her to try and free up some memory and see if that fixes the problem, and if it doesn't then to do as you suggested and use the main computer again.

**Comment by NickWeir63** [comment]
Thanks everyone.   I have sent the email below to the shopper and will close this now.

From: Nick Weir [mailto:nick@nickweir.co.uk] 
Sent: 27 May 2016 16:21
To: 'Caroline Denny'
Cc: manager@stroudco.org.uk
Subject: RE: Using Open Food Network on your iPad

Dear Caroline

The developers have looked into what is happening here and have tracked down a similar iPad to yours to use for testing.  Basically the features of Open Food Network use a high level of processing capacity which some of the older iPads are not able to provide.  Following your feedback they tested the system again using a modern iPad and it works fine, they then tested it on a 4 year-old iPad and it worked slowly but adequately.

So the only way we could make it work on your iPad would be to disable some of the more advanced functionality – which would be a shame after we have spent 3 years learning from the drawbacks of the old Stroudco software and finding ways to improve the system for the shoppers and for the Stroudco manager.

Another suggestion from the development team is that because the issue is to do with lack of memory, if you are able to free up more memory on your iPad (by closing down other applications) this may free up enough resources to run OFN on your iPad.

I am very sorry if we can't get the new shopfront to work on your iPad.  I hope you can find other ways to get to the Stroudco shop.

Thanks again for your feedback and for supporting Stroudco 

All the best
Nick

**Comment by NickWeir63** [comment]
One of our potential users (Good Food Oxford) has found that she can't open the Stroudco shopfront on her Samsung S4.  She is hoping to use OFN in a poor area of Oxford where people will be using older hardware and is concerned about the high requirements of OFN.  Her email is sk@syfi.freeserve.co.uk

**Comment by NickWeir63** [comment]
A Stroudco shopper has told us that when she opens the shopfront on her tablet (2 years old running Windows 10) it freezes (no error message and nothing happens even after a long wait)

**Comment by Rocksj** [comment]
Two customers trying to use iPad's this week couldn't place their orders. They are using iPads which are less than 2 years old and have 12gb memory. The operating systems are both version 9.3.2. They described it as:
We couldn't logon after we complied our order. When we pressed Login or checkout they went from dark to light red but nothing happened. So we couldn't complete the order.

**Comment by oeoeaio** [comment]
Hi @Rocksj, this sounds like a separate issue, but one which sounds very similar to an issue that some of my customers have reported. I have never been able to replicate it however. Do you have a good enough relationship with these customers to ask them if they could attempt to replicate the problem? Would be great to get some screenshots, and an error log of some sort from the device if possible...

**Comment by Rocksj** [comment]
Its one of our Directors and his wife, they have matching iPads, so I have asked the question!

**Comment by Rocksj** [comment]
Screenshots and comments from our Director:
The first is the screen after I press on my basket.
The second is the one I get when I press Login.Nothing happens but the red colour changes.
The third screen is the one I get if I try to do it again but login as a guest.The box changes to grey but nothing happens.

![img_0380](https://cloud.githubusercontent.com/assets/15102362/16381002/378690a2-3c72-11e6-9a06-9681b95677ca.png)
![img_0381](https://cloud.githubusercontent.com/assets/15102362/16381003/3a3a4d70-3c72-11e6-9ce8-95f888488f32.png)
![img_0382](https://cloud.githubusercontent.com/assets/15102362/16381005/3e10f354-3c72-11e6-81ad-368d234b0fce.png)

**Comment by lin-d-hop** [comment]
The experience doing a shop on my phone is clunky and couldn't complete a checkout. I agree with our director that the roll out in the UK will be limited if we can't keep up with competitors in the mobile space. Would be good to discuss in management and dev meetings this week...?
