### ISSUE TITLE
Split checkout design changes part 1

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10146]
## Description
**- As a:** shopper with split checkout activated
**- On page:** checkout process
**- I want to be able to do:** 

- [x] Stop underlining the step title before the step occurred: if there is no link, there shouldn't be any underlining

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/5a15d1ab-e279-4ca4-a1ec-846ab60fbe77)

- [x] Stop underlining bold title:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/6a820794-b2e1-42ed-8dcd-93494cc3800d)

- [x]  Use two columns for fields. 
<img width="642" alt="Capture d’écran 2022-12-13 à 12 22 08" src="https://user-images.githubusercontent.com/296452/207304881-e20768b1-f697-4993-bc27-d7251fc91c60.png">

- [x]  for all filelds, remove title and keep only placeholder

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/acca5b64-c9f5-43fb-ad2f-77f8b73d12f9)

- [x] Instead of "your details", a contact details start the process (first name and name are moved to "billing address"): 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/de4686a0-a44e-4123-bdf8-be29123807e3)

Apart from this billing address remains unchanged

- [x] When selecting a **shipping or payment** method, let's put the description _under_ the radio button that is selected and not _under_ the full list of shipping method

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/3283351d-cf66-47f9-813a-c62465028d6f)

- [x] Grey button can be interpreted as disabled, let's move them to white background with red text and border

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/48c8327c-7ee7-4693-9699-b4c21b73c713)

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/e9e79cc3-d803-41ee-b880-a872c46b30b7)

- [x] Price of shipping method and payment method are harmonized: italic+bold+bracket

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/78ac667b-b9a1-4e93-8b83-94ef2abdde70)

## Acceptance Criteria & Tests

1. Enable split checkout
2. Check the items above have changed

**Comment by jibees** [comment]
Sorry, but I deep dive into `label` vs. `placeholder` and seems like it's a bad idea (in term of accessibility) to use `placeholder` rather than `placeholder`. 

for example: https://www.nngroup.com/articles/form-design-placeholders/

Will make all the others modifications required by this PR, and will try to made a proposal for this `label`. I was wondering why we wanted to remove those labels? Which issue(s) we want to solve?

**Comment by RachL** [comment]
@jibees yes I had the same opinion, but we have talked about this issue in product circle but concluded it was ok because all fields are small. If you start typing your first name and you forgot it was the first name you were asked.... that's probably a rare case? But I agree that if one day we merge all address field into one for example this would be harmful.
This was introduced to fixed 2 things: redundancy of information & height of the full page.

**Comment by jibees** [comment]
Just a proposal:

<img width="652" alt="Capture d’écran 2022-12-13 à 12 34 18" src="https://user-images.githubusercontent.com/296452/207307353-f439f08d-66b9-4a8a-a07b-eca4df0cd643.png">

**Comment by RachL** [comment]
hmmm not convinced :D - I would prefer to leave it has is if we want to keep labels. @kirstenalarsen or @lin-d-hop can you check this with Jess tomorrow? My timezone will not overlap with hers as I've global meetings when Jess starts her day.

**Comment by kirstenalarsen** [comment]
I am a fan of removing the labels. I think we have to balance the accessibility of remembering what you're typing with the accessibility of scrolling a long way on this form with lots of fields. If others feel strongly about this, I'm open to pushing it with the existing labels (outside boxes) and seeing how it feels with all the other changes / improvements in place. And then it is just a small issue to remove the labels if it still feels overwhelming / long?

**Comment by Jesszahra** [comment]
Can we just do something like Shopify does? We don't have the capacity to user test this but I think Shopify must have data on checkouts so it can't be impacting accessibility too badly. From memory, Shopify has had this checkout style for a few years. Once user starts typing title goes to top of the box (but still inside).
 
<img width="312" alt="Screen Shot 2022-12-14 at 5 08 26 pm" src="https://user-images.githubusercontent.com/107977095/207503618-33e47753-781b-4667-8a4d-466d024e318c.png">

**Comment by jibees** [comment]
<img width="608" alt="Capture d’écran 2022-12-15 à 15 13 24" src="https://user-images.githubusercontent.com/296452/207883368-82a8523f-cada-4ae7-b8bb-74bd4f8dc08e.png">

**Comment by kirstenalarsen** [comment]
Beautiful @jibees !
