### ISSUE TITLE
UK staging down

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1015]
i get grumpy cat when I go to https://staging.openfoodnetwork.org.uk/

**Comment by pmackay** [comment]
I can see `ActiveRecord::RecordNotUnique (PG::Error: ERROR:  duplicate key value violates unique constraint "sessions_pkey"
DETAIL:  Key (id)=(52585) already exists.` in the log.

@lin-d-hop have you updated anything recently?

**Comment by lin-d-hop** [comment]
I'm getting through fine. Is it still down for you @NickWeir63?

**Comment by NickWeir63** [comment]
all fine now thanks
