### ISSUE TITLE
[staging-FR] Images and Stripe configuration is broken

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10163]
## Description

Images and Stripe configuration is broken on Staging-FR after provisioning in the context of https://github.com/openfoodfoundation/ofn-install/pull/849

## Expected Behavior

Images and Stripe should work as before.

## Actual Behaviour

Images and Stripe are broken.

## Steps to Reproduce

1. Visit https://staging.coopcircuits.fr/ -> notice images are missing
2. Checkout from a shop with Stripe enabled -> notice it is not possible

**Comment by RachL** [comment]
i think this one can be closed
