### ISSUE TITLE
Add parallel_tests gem

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10164]
### What we should change and why (this is tech debt)

Add https://github.com/grosser/parallel_tests gem -> a first attempt was made here https://github.com/openfoodfoundation/openfoodnetwork/pull/9838.

We've paused this effort because we've introduce knapsack in the meantime.

### Context

https://github.com/openfoodfoundation/openfoodnetwork/pull/9838

### Impact and timeline

A faster build.

**Comment by mkllnk** [comment]
Shall we close this? I think that one way to parallelise is enough.

**Comment by filipefurtad0** [comment]
Agree! Closing.
