### ISSUE TITLE
Multi-supplier OC: non-coordinator suppliers see info on other suppliers

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10173]
## Description

A supplier, which is not coordinating the OC, can see from other suppliers, in the:

` 3. Outgoing Products`
-> here the exchanges from other suppliers are visible
and

`4. Checkout Options`
-> Payment and Shipping methods are visible

This enables the possibility to click around and make apparent changes, which are not persistent - but which are, in itself, an inconsistent behavior of these pages.

## Expected Behavior

Non-coordinator suppliers should only see info on order-cycles (exchanges, payment- and shipping methods) related to them.

## Actual Behaviour

Non-coordinator suppliers are able to see and click (de-/select) info on order-cycles (exchanges, payment- and shipping methods) not related to them.

## Steps to Reproduce

1. Browser session 1 - OC Coordinator: As a hub, set up an order cycle with more than one supplier - see the doc below to set the permissions accordingly

2. Browser session 2 - OC Supplier: go through the different sections 1. to 4. and compare the results with the document below. -> notice that you are able to see information not related to your account.

2.a) . On the ` 3. Outgoing Products` click the trash-bin for the exchange of a supplier other than the one you're managing, with your account. Notice that the exchange line disappears -> this should only be possible for the OC coordinator. (this change is not persistent, though - point 4, below)

2.b) On the `4. Checkout Options` notice you're able to de-select shipment-/payment methods from other suppliers. Save your changes. (also here, the change is not persistent - point 4, below)

4. Browser session 1 - OC Coordinator: Notice that all changes introduced by the Supplier are not persistent - this is a good, and should be kept this way.

## Animated Gif/Screenshot

Details here:
https://docs.google.com/document/d/1j-CyrJfF3pEIQCqKHjhtztyNsrzo6xF149YAPLYLWOQ/edit

## Workaround

None?

## Severity

I guess an bug-s2, but since changes are not persistent I'd say an S3.

## Your Environment

* Version used: Spotted on 4.2.26 but pre-existent.
* Browser name and version: Firefox 109
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by audez** [comment]
Hi! thanks for this, we have one user that reported the issue in FR prod.

**Comment by vviekk** [comment]
Hi @filipefurtad0 , 
just wanted to confirm: the logged in user should only be able to see information related to them, correct?
* Or is it see all but only can edit their own?

**Comment by RachL** [comment]
@vviekk best is to go with only be able to see information related to them. Not the others. Let us know if you still have some time to work on this one, and many thanks for all your contributions so far ❤️

**Comment by jibees** [comment]
Hi @vviekk 
Hope you're doing well ;) I'll unassigned you, and move this issue to another state. If you still intend to work on it, will re-assign you!

**Comment by abdellani** [comment]
Hi @filipefurtad0 

* I was not able to reproduce the part related to `OUTGOING PRODUCTS` ( I think that I already [fixed it](https://github.com/openfoodfoundation/openfoodnetwork/issues/10462).)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/44b5ed02-0f1a-4f09-9db8-00768af050e8)

* I can confirm the second part of the issue

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/ac407281-745d-47a4-8d62-83d0e411d769)

**Comment by filipefurtad0** [comment]
> I was not able to reproduce the part related to OUTGOING PRODUCTS

Thanks for picking this up and feedback @abdellani. I cannot reproduce it either, for the case in which supplier 1 and 2 (added to a OC coordinated by an enterprise 3) are unrelated (meaning, no permissions are given between suppliers 1 and 2).

In the example I've pointed out, the case is slightly different:
- enterprise 1 is added as a supplier
- supplier 2 is added as a supplier (supplier 2 has granted permissions to add to an OC to enterprise 1, due to some other OC) -> I'm sorry, I've noticed this is missing from my notes above :exclamation::exclamation::exclamation: but this is needed to reproduce the issue
- enterprise 3 coordinates the OC

In this case:
- supplier 2 does not see enterprise 1, but
- enterprise 1 sees supplier 2 -> this is the point which could be addressed... (because enterprise 1 has received permissions from supplier 2, but I think these should be valid _only if enterprise 1 coordinates_ the OC, but this is the role from enterprise 3)
- enterprise 3 sees all

This is really a bit complicated :sweat_smile: Hope it makes sense. 

Would it be helpful if I write a spec for this?

**Comment by abdellani** [comment]
@filipefurtad0 

I tried to add the following condition: 
if **supplier A** has 'add_to_order_cycle' permission on another **supplier B**
**supplier A** should not see the exchange of **supplier B**, except if **supplier A** is a coordinator.

but the following spec failed
`rspec ./spec/system/admin/order_cycles/simple_spec.rb:476`

In this case, the **supplier** has  'add_to_order_cycle' permission on one of the distributors.

I think in this case, we should authorize the supplier to list incoming exchanges. What do you think?

------------------

Now, I believe that we have a problem with `managed_participating_producers` and `managed_participating_hubs`.

`managed_participating_producers` loads every producer regardless if the producer participated in that order cycle as a producer or as a hub. The same thing applies to `managed_participating_hubs`. 

@Matt-Yorkley  what do you think? 

https://github.com/openfoodfoundation/openfoodnetwork/blob/5ec872c6fdcdd54abb05351ee92e4fb8af81089a/lib/open_food_network/order_cycle_permissions.rb#L261-L278

**Comment by filipefurtad0** [comment]
> if supplier A has 'add_to_order_cycle' permission on another supplier B

> I think in this case, we should authorize the supplier to list incoming exchanges. What do you think?

I see your point - thanks for that. It's great we have that spec in place.

However, one thought:

I think this case is slightly different than the one described on the issue: on the spec, one enterprise is acting as distributor for that OC (`Enterprise 1`), while the other acts as a supplier (`Managed supplier`). I can imagine it is useful for distributors to "see" where products are coming from (the incoming exchange).

However, it should not be able to make changes to the incoming exchange, we can still see, that the check-boxes `1G` and `See all 5 variants` - although changes are not saved:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/9deab015-0ea3-4bfe-8c6c-819de7480f84)

Anyway: I see you have a PR for the `checkout options` section, which is great and surely an improvement. We should perhaps keep the visibility in the exchanges as it currently is (this should keep `/simple_spec.rb` green) and not spend much more time on this issue (I'm not sure it will bring that much benefit, all things considered).

**Comment by Matt-Yorkley** [comment]
> 3. Outgoing Products -> here the exchanges from other suppliers are visible

@filipefurtad0 I've just been trying this out and I can't replicate the problem. Using:

- A distributor enterprise that's the coordinator of the OC
- Two different suppliers that are added to the OC with the correct permissions and they are not distributors in the OC
- Logging in as a user who only manages one of the supplier enterprises and not the coordinator.
- The user can only see the entries for their own enterprise in incoming and outgoing :heavy_check_mark: 
- The user can't see the the other suppliers products or change anything :heavy_check_mark: 

Seems like it's working?

I can replicate the second issue (checkout options)

**Comment by abdellani** [comment]
> Anyway: I see you have a PR for the `checkout options` section, which is great and surely an improvement. We should perhaps keep the visibility in the exchanges as it currently is (this should keep `/simple_spec.rb` green) and not spend much more time on this issue (I'm not sure it will bring that much benefit, all things considered).

Ok @filipefurtad0 , I'll limit my PR to the checkout option. I'll just add new specs.



> * Two different suppliers that are added to the OC with the correct permissions and they are not distributors in the OC
> * Logging in as a user who _only_ manages one of the supplier enterprises and not the coordinator.
> * The user can only see the entries for their own supplier enterprise in incoming and outgoing heavy_check_mark
> * The user can't see the the other supplier's exchanges or products or change anything for the other supplier heavy_check_mark
> 
> Seems like it's working?
> 

@Matt-Yorkley I also failed when I tried to replicate the issue on this first time. 
Suppose we have suppliers A & B. I needed to grant 'add_to_order_cycle' permission to A  on B, then I logged in as A.
