### ISSUE TITLE
Allow bold / italic / underligning in product short description too

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10211]
## Description
**- As a:** shopper
**- On page:** `/shop
**- I want to be able to do:** If the product description is written in bold italic or perhaps underlined we need to see it in the short version of the description too.

Currently, the short description stays regular. Example: 

![image](https://user-images.githubusercontent.com/6525576/209843163-48fa2566-9f95-4474-a849-54d87a5ff955.png)

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/26144ad9-0e4b-4427-9ca3-e9242e9fd170)

## Acceptance Criteria & Tests

1. Add a product description with bold, italic or underlined text at the beginning
2. See bold italic and underline is correctly shown in the short description in the shopfront

**Comment by RachL** [comment]
@jibees do you think a link could be shown as well?

**Comment by jibees** [comment]
> @jibees do you think a link could be shown as well?

IMHO, this will be a side-effect when we'll modify the way we display it by not escaping HTML. Bold, italic, underline and links will be displayed.

**Comment by RachL** [comment]
Alright, let's go for it then :+1:

**Comment by jibees** [comment]
Possible fix:

```diff
diff --git a/app/views/shop/products/_summary.html.haml b/app/views/shop/products/_summary.html.haml
index c87d26ff46..c99eabaa4e 100644
--- a/app/views/shop/products/_summary.html.haml
+++ b/app/views/shop/products/_summary.html.haml
@@ -9,7 +9,7 @@
     %h3
       %a{"ng-click" => "triggerProductModal()", href: 'javascript:void(0)'}
         %span{"ng-bind" => "::product.name"}
-    %p.product-description{ng: {bind: "::product.description", click: "triggerProductModal()", show: "product.description.length"}}
+    %p.product-description{ng: {"bind-html": "::product.description_html", click: "triggerProductModal()", show: "product.description_html.length"}}
     .product-producer
       = t :products_from
       %span
```

**Comment by mgrigoriev8109** [comment]
I'd love to have a go at this.

**Comment by jibees** [comment]
Sure @mgrigoriev8109 !
I'll assign yourself!
