### ISSUE TITLE
[Split Checkout] Error 422 on step '2 - Payment' - Update highlighted fields

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10228]
## Description

Looks related to #9056, but seems to be introduced by the recent design changes https://github.com/openfoodfoundation/openfoodnetwork/pull/10154.

For customers with saved cards, the first attempt to proceed to the `/summary` page displays an error 422 and prevents the user from proceeding.

## Expected Behavior

If a card is pre-selected, no other action should be necessary on the /payment page -> proceeding to /summary should be possible when clicking `Next - Order summary`.

## Actual Behaviour

If a card is pre-selected, the user needs to click on `Next - Order summary` to proceed to the next step; the first attempt displays an error.

## Steps to Reproduce

-> enable Split checkout

As a customer:
1. Save a card (card type is irrelevant - x-4242 or x-3155 are fine); occurs also with more than one saved card
2. Visit a shop with Stripe payments
3. Add items to your cart and proceed to checkout
4. Add your details on the `/details` page and visit step 2.
5. On the `/payment` page your saved card should be pre-selected.
6. Click on `Next - Order summary` -> Notice the flash error.
8. Click `Next - Order summary` a second time -> you should be able to proceed to the `/summary` page as usual

## Animated Gif/Screenshot

Below staging-UK (**new design**, master) vs staging-AU (old design, some other build, previous to the design changes):

![image](https://user-images.githubusercontent.com/49817236/210411651-dbbce143-87ad-49c0-8eb6-016f42e1da48.png)

After staging master on staging-AU:

![image](https://user-images.githubusercontent.com/49817236/210414270-0281be8a-cc2e-4950-ab45-0b9b4fabbb48.png)

Notice the new design, and the error appearing on both servers.

## Workaround

Click a second time on `Next - Order summary`

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: Seems introduced by #10154; tested on v4.2.28
* Browser name and version: Firefox 109 and Chrome 108
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment]
oh I see now I didn't do the correct steps, thanks @filipefurtad0 !

@jibees is this something you can look into? I think we need to fix this before the roll-out.

**Comment by filipefurtad0** [comment]
> oh I see now I didn't do the correct steps, thanks @filipefurtad0 !

No worries @RachL - I was not very explicit before on the steps to reproduce, sorry for that :pray: 

> Looks related to https://github.com/openfoodfoundation/openfoodnetwork/issues/9056, but seems to be introduced by the recent design changes https://github.com/openfoodfoundation/openfoodnetwork/pull/10154.

Please note @jibees I'm not _sure_ this is introduced by the design changes. However staging-AU had #9804 staged in it (no bug is observed), which is previous from the merge of #10154 (bug is observed).

**Comment by jibees** [comment]
I don't see any reason on why it could be introduced by design changes, but we can always be surprised!

**Comment by jibees** [comment]
It seems to be a (bad) combination between `@hotwired/turbo` and the stripe iframe. 
Looks like a great workaround was posted here, in the meantime:
https://github.com/hotwired/turbo/issues/270#issuecomment-1068130327

Will submit a PR, let see how it works!
