### ISSUE TITLE
Improve basic page request speed

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#1023]
Testing with siege, any page makes these requests:

```
0.45 secs:   23358 bytes ==> GET  /
0.06 secs:    7748 bytes ==> GET  /assets/ofn-logo-footer.png
0.06 secs:   14355 bytes ==> GET  /assets/logo-white-notext.png
0.07 secs:   21141 bytes ==> GET  /system/content_configurations/logo_mobile_svgs//original/ofn_logo_uk1-300x68.png?2015
0.08 secs:   21141 bytes ==> GET  /system/content_configurations/logo_mobiles//original/ofn_logo_uk1-300x68.png?2015
0.06 secs:    9621 bytes ==> GET  /system/content_configurations/logos//original/ofn-uk-colorx2.png?2015
0.39 secs: 1301196 bytes ==> GET  /assets/darkswarm/all-c1c09af8a88c0143845fd1615485e6cf.js
0.17 secs:  373000 bytes ==> GET  /assets/darkswarm/all-01e2a7634cd8da22060edd46387c0595.css
0.15 secs:   79781 bytes ==> GET  /maps/api/js?libraries=places,geometry
0.11 secs:    2203 bytes ==> GET  /css?family=Roboto:400,300italic,400italic,300,700,700italic%7COswald:300,400,700
```

Obviously after that there is typically Angular API calls. Couple of quick thoughts:
- Could the loading of Google Maps JS be configured only to occur on the maps page?
- Does the footer need two OFN logos? 
- Could the `og:graph` image be made the same as the page logo? Currently its much larger which is not ideal anyway.
- Is there anything that could be done to reduce the main JS file size?

**Comment by daniellemoorhead** [comment]
@oeoeaio @mkllnk @bingxie @RohanM any thoughts on the above?

**Comment by mkllnk** [comment]
>    Could the loading of Google Maps JS be configured only to occur on the maps page?

Yes. That would be good. That would be /map and also on groups pages.

>    Does the footer need two OFN logos?

Do you mean /assets/logo-white-notext.png? Ideally, that would be an SVG stored in the icon font. What do you think?

>    Could the og:graph image be made the same as the page logo? Currently its much larger which is not ideal anyway.

There was no page logo by default in the past. Now there is, so we could use that one.

>    Is there anything that could be done to reduce the main JS file size?

Maybe look for old unused code. But it is pre-compiled already. I don't think there is much we can do. More and more of the application moves into Angular which means growing JS code and more to do for clients.

**Comment by pmackay** [comment]
>SVG stored in the icon font. 
@mkllnk what is defined in the icon font already? How do you configure it?

**Comment by mkllnk** [comment]
Well, there are a lot of symbols like the little farmer truck and the warning sign and so on. The font was compiled by Laura who left the project last year. She used icomoon.io to generate the fonts. We have the file you need to upload to icomoon to edit the current font.
https://gist.github.com/mkllnk/5acd096b7d0da97830012068db7f9b56

If you would just upload a font file, it doesn't know about little adjustments of the symbol positions. We haven't changed the font since Laura left.

**Comment by pmackay** [comment]
Here is a Lighthouse report run on homepage of OFN UK. Current score = 42/100.

[Lighthouse report- https---openfoodnetwork.org.uk-.pdf.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/682582/Lighthouse.report-.https---openfoodnetwork.org.uk-.pdf.pdf)

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/optimisations-suggestions/1176
