### ISSUE TITLE
[Sysadmin] UK staging down

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10253]
## Description

UK staging is down, apparently since [last provisioning](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1672896299782009).

## Expected Behavior

Visiting `https://staging.openfoodnetwork.org.uk/` renders the OFN website (status 200)

## Actual Behaviour

Visiting `https://staging.openfoodnetwork.org.uk/` gives us the snail (status 520, Bad Gateway)

## Steps to Reproduce

1. Stage master and visit `https://staging.openfoodnetwork.org.uk/` -> notice the snail and the error 520, Bad Gateway

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/211513472-09bce127-5588-433a-b325-230a29c96470.png)

**Comment by dacook** [comment]
Ok I finally found a helpful error message on the server: 

```
Jan 11 06:12:51 staging puma[12612]: NameError: undefined local variable or method `nakayoshi_fork` ...
```

This was updated recently. I'll look into that tomorrow.

**Comment by jibees** [comment]
This gem is supposed is to be removed since: https://github.com/openfoodfoundation/ofn-install/pull/855 
Will try to provision `uk-staging`

**Comment by jibees** [comment]
After provisioning, uk staging is up.


_For the record, I had an error:_

```
TASK [Datadog.datadog : Install ubuntu apt-key server] *************************************************************************************************************************************************************
fatal: [staging.openfoodnetwork.org.uk]: FAILED! => {"after": ["40976EAF437D05B5", "251BEFF479164387", "3B4FE6ACC0B21F32", "D94AA3F0EFE21092", "46181433FBB75451", "ABF5BD827BD9BF62", "8C47BE8E75BCA694", "93C4A3FD7BB9C367", "1F5EB010C5341279", "EB9B1D8886F44E2A", "670540C841468433", "28A1C275F9F8725B", "D27D666CD88E42B4", "AB6B7FCB60D31954", "D7F87B2966EB736F", "1655A0AB68576280", "6C5CDECAAA01DA2C", "CC59E6B43FA6E3CA", "8B1DA6120C2BF624", "DA3A94F6B33723BC", "7FCC7D46ACCC4CF8"], "attempts": 5, "before": ["40976EAF437D05B5", "251BEFF479164387", "3B4FE6ACC0B21F32", "D94AA3F0EFE21092", "46181433FBB75451", "ABF5BD827BD9BF62", "8C47BE8E75BCA694", "93C4A3FD7BB9C367", "1F5EB010C5341279", "EB9B1D8886F44E2A", "670540C841468433", "28A1C275F9F8725B", "D27D666CD88E42B4", "AB6B7FCB60D31954", "D7F87B2966EB736F", "1655A0AB68576280", "6C5CDECAAA01DA2C", "CC59E6B43FA6E3CA", "8B1DA6120C2BF624", "DA3A94F6B33723BC", "7FCC7D46ACCC4CF8"], "changed": true, "fp": "D3A80E30382E94DE", "id": "A2923DFF56EDA6E76E55E492D3A80E30382E94DE", "key_id": "A2923DFF56EDA6E76E55E492D3A80E30382E94DE", "msg": "apt-key did not return an error, but failed to add the key (check that the id is correct and *not* a subkey)", "short_id": "382E94DE"}
```
