### ISSUE TITLE
[Split checkout] Responsiveness is broken on iphone

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10250]
## Description

Not reproducing on android devices, but according to browserstack this is how split checkout looks like on iphone 14 with chrome: 

![image](https://user-images.githubusercontent.com/6525576/211305882-6de2af7b-6ff5-4358-b424-07f063eba682.png)

![image](https://user-images.githubusercontent.com/6525576/211306005-df525216-2233-4ce4-b6ef-187909d4b8e1.png)

![image](https://user-images.githubusercontent.com/6525576/211306084-dac19833-68a3-4bf1-84bc-364258f4a527.png)

On Android 12 - same browser, everything is clean and centered:

![image](https://user-images.githubusercontent.com/6525576/211306554-577e43ca-e54c-4675-a76d-3f98bf1d6109.png)

## Steps to Reproduce

1. Login with browserstack and check split checkout with iphone

## Workaround

Scroll horizontally or maybe it's possible to  reduce zoom?

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: master
* Browser name and version: Chrome 105

**Comment by jibees** [comment]
What I've found...

By default the view seems ok:
<img width="598" alt="Capture d’écran 2023-01-16 à 14 33 24" src="https://user-images.githubusercontent.com/296452/212690397-1acc495d-f52b-4453-b148-ffccb02bf814.png">

We I click on an input, the system zoom and then a horizontal scrollbar appears:
<img width="593" alt="Capture d’écran 2023-01-16 à 14 33 54" src="https://user-images.githubusercontent.com/296452/212690484-6b2dcbaa-c68c-4cc5-bf62-093c40017149.png">

When I finish to fill the input, yes, the zoom is still here:
<img width="599" alt="Capture d’écran 2023-01-16 à 14 34 35" src="https://user-images.githubusercontent.com/296452/212690595-6fb3e6c8-7639-48bf-9ee5-36355ab7db1a.png">

But I can de-zoom actually, and then I'm back on step1.


Is that what you've found, or the zoom was by default with that horizontal scroll bar and we can't de-zoom ?


(tested on iPhone 14 Pro v16.0)

**Comment by RachL** [comment]
@jibees I tested with a user that was already registered. So yes the zoom was by default with that horizontal scrollbar. I guess it's because all the field were pre-filled.

**Comment by jibees** [comment]
I've tested with a registered user, and when I go to `/checkout/details`, the default zoom is correctly handled:

<img width="566" alt="Capture d’écran 2023-01-16 à 14 51 55" src="https://user-images.githubusercontent.com/296452/212693840-3b64e311-c7b0-487e-8f50-3923b94b1821.png">


Have you tested to dezoom, and did it work?

**Comment by RachL** [comment]
@jibees you mean below 100%?

**Comment by jibees** [comment]
> @jibees you mean below 100%?

Nop, I mean like it should be ie. my previous screenshot. Maybe for one particular reason, your zoom is _by default_ to 110%, and I'm wondering if you could change it by dezooming manually.

**Comment by RachL** [comment]
I can de-zoom, but I have the focus problem at 100%. So if I go below yes it works.

**Comment by jibees** [comment]
I've submitted a PR, and deployed onto fr-staging
I'd be happy if you could tell my if it solves anything ;) Thanks!!

**Comment by RachL** [comment]
@jibees it looks like it yes! Only one weird thing: first time I landed on the cart page, I had an horizontal scroll. Then I proceeded to checkout and from then going back to the cart page didn't show an horizontal scroll. Maybe a cache issue?

**Comment by jibees** [comment]
> Maybe a cache issue?

Could be ...
