### ISSUE TITLE
Configurable 'From' Address for email communication from Enterprises

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1025]
Currently sends from instance address, which is not very useful for the producers replying or the instance coordination.

Enabling emails to be sent 'from' a different email address needs to be instance configurable as some instances may be using SMTP servers that overwrite the 'from' address.
- Add checkbox in Mail Methods panel in super admin configuration enabling Enterprise communication to be sent from the enterprise email address.
- Update the from address of appropriate emails to use hub 'from' address when this config is set.

**Comment by lin-d-hop** [comment]
Hi @RohanM @stveep 

Just a quick one...
 
We are getting some people replying to the OC notification emails to hello@open.....uk
Looking into this although the 'reply to' email is set to the coordinators email the 'from' email is still the instance.
```
mail(to: @producer.email,
           from: from_address,
           subject: subject,
           reply_to: @coordinator.email,
           cc: @coordinator.email)
```
It seems not all mail clients respect the 'reply_to' and use the 'from' instead.

I was just wondering if there was a reason it was implemented this way? Would you be happy if I just changed the 'from' to the coordinator as well?

Cheers!

**Comment by daniellemoorhead** [comment]
@oeoeaio any thoughts on this?

**Comment by daniellemoorhead** [comment]
Hey @kirstenalarsen are you able to shed some light on the above? Can @lin-d-hop change the from address to be the coordinator as well?

**Comment by oeoeaio** [comment]
I don't have any particular concerns with this change. Sounds good to me?

**Comment by lin-d-hop** [comment]
Hi @stveep 
Thanks for agreeing to look at this when you get the chance.

Fundamentally this change is quite simple. PR #1044 worked fine for our servers.
We just need to add in a UI step in Super Admin -> Configuration -> Mail Methods to allow this to be a feature that is turned on or off at instance level. This is because some instances will be using SMTP servers that override all outgoing emails to the same email address, rendering this feature useless.

I'll communicate via Slack on deployment process to make this easier to test.

Cheers :-)

**Comment by lin-d-hop** [comment]
Closing as this issue blew up in scope and practicalities
