### ISSUE TITLE
Order cycle report OC filter not working

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1026]
Reported by @OliverUK 
"I chose the "4th June" order cycle and assumed the report would give me data for the entire order cycle but it was in fact only part of the data because the "start" date at the top was still on 1st June (to which it seems to have defaulted). So I got data for the OC I chose but only for orders from 1st June onwards. I set the date back to 1st May and tried again and this time I got the data I expected.

I think choosing a OC should overwrite the date settings."

**Comment by lin-d-hop** [comment]
Hi @OliverUK 
On looking into this I understand your meaning. I now feel that I opened this as a bug incorrectly.
I think it might be an important function to be able to search for orders of specific dates within the order cycle. Introducing the functionality as you describe would also create confusion. It makes sense in a Stroudco setting but not for many other ways of using OFN.

- Perhaps we need some kind of user feedback that informs the user that only part of the OC is being searched?
- The date range is specified so as to stop a huge amount of data loading when the page is opened. Perhaps moving the date back to the start of the month before, instead of the first day of the current month?

Neither of these sound overly intuitive to me. 
Closing as I don't think this is actually an issue.

**Comment by OliverUK** [comment]
Fair enough, it may well be working as intended but I agree it would be good to make users more aware of it. When you choose an order cycle, it shows you the date range of that cycle. It seems to me natural for users to assume this overrides the start date further up. 

Defaulting the start date to the first day of the previous month would make it much less likely, in my opinion, for there to be mistakes. Maybe this is also a fairly simple solution to implement?

**Comment by OliverUK** [comment]
I feel this still needs addressing. Maybe @lin-d-hop  could reopen this issue, even if not labelled as a bug, while I go and do all my weekly paperwork a second time? :(

**Comment by Matt-Yorkley** [comment]
@lin-d-hop do you have a clear idea of what additional functionality would be needed to address this? Also I'm finding it tricky to match up order cycles to producers and hubs for reports testing as there's too many options as a superuser.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley We're not tackling reporting issues at the moment as we are considering a total refactor. Please look at issues in pipeline 'Dev Ready' from milestone 'UK Current'.

**Comment by lin-d-hop** [comment]
#gitcull2017
Issue is not described clearly enough to be worked on and is very low priority.

**Comment by myriamboure** [comment]
Duplicate as https://github.com/openfoodfoundation/openfoodnetwork/issues/1972 and icebox item created here (might be solved with report optimization first feature candidate) https://community.openfoodnetwork.org/t/improve-oc-reports-ux-to-avoid-annoying-mistake-causing-wrong-deliveries/1160
