### ISSUE TITLE
sitemap.xml is empty

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#1027]
ComfortableMexicanSofa is generating a `sitemap.xml` but its empty (presumably because in UK, CMS is not being used for anything, is it being used in Aus?).

It would be beneficial for SEO if OFN had a sitemap that contained links to all the basic pages and shops.

@oeoeaio @mkllnk have you considered this before? 

cc @lin-d-hop

**Comment by mkllnk** [comment]
No. I never came across that.

**Comment by daniellemoorhead** [comment]
We'll chat about this during the week when we're in the office @pmackay and let you know.

**Comment by pmackay** [comment]
@mkllnk what do you think about disabling the CMS sitemap generation and adding a controller to create one? I could look at that if you agree.

**Comment by mkllnk** [comment]
Sounds good. @RohanM would know if the CMS is used at all. Maybe to store some content of the site. But we should have our own sitemap. That would be great.

**Comment by daniellemoorhead** [comment]
@RohanM any thoughts on @pmackay's suggestion above of disabling the CMS-generated sitemap and adding a controller to create one?

**Comment by daniellemoorhead** [comment]
@RohanM checking in - thoughts on this one?

**Comment by RohanM** [comment]
I've recently removed CMS, since we haven't been using it for a long time. So now there should be no `sitemap.xml` at all. @pmackay, would you be interested in doing a PR to provide a sitemap?
