### ISSUE TITLE
Fee calculators: Remove the currency input field

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10272]
## Description
**- As a:** enterprise or super admin
**- On pages :** `/admin/enterprise_fees?enterprise_id=XXXX` for all calculators

`/admin/shipping_methods/new` + edition page

`/admin/payment_methods/new` + edition page

**- I want to be able to do:** not seeing the currency field anymore. By default, it should use the currency of the instance.

## Acceptance Criteria & Tests

1. Login
2. Create or edit shipping issues with fees (all calculators) must still work
3. Create or edit payment issues with fees (all calculators) must still work
4. Create or edit enterprise fees (all calculators) must still work

**Comment by dacook** [comment]
Hiding the currency works, but from what I can see I think it creates tech debt and is not a papercut. Maybe I'm not seeing the full picture but this is what I can see so far:

Calculator are classes that can be used for enterprise fees, shipping methods or payment methods. They have 'preferences', and some calculators have a currency preference (eg Flat Rate). 

It's possible that some fees/methods have been created that have a different currency set. 
**Does the currency do anything?**

1. If not, why don't we remove the currency preference from the calculators entirely?
2. If we need to keep the currency on the calculators, we could remove the stored preferences, and refer directly to the system default. In this case it's important to note that any fees/methods with a different currency would suddenly be using the system default.

Does this make sense, and does anyone agree with either option (@jibees or @drummer83)?

**Comment by lin-d-hop** [comment]
The desired solution is to hide the unwanted UX from the user. and autofill with the instance currency Yes it creates tech debt to remove this functionality but it improves the user experience so perhaps we can use Danni's phrase and 'put lipstick on the pig'?

If any calculator has a different currency set it should be ignored to use the isntance default.

@dacook Can we remove the currency from calculators entirely within the scope of a papercut?

**Comment by dacook** [comment]
Apologies, I thought I had responded earlier!

Thanks for confirming, so the currency does nothing on calculators and can be removed. 

We have a quick change to simply hide it for now. Perhaps we can call that step 1. Unfortunately it adds complexity (rather than taking it away), but we could ship it with the goal to clean up later.

But... It's probably not that much effort to remove the currency entirely.. actually why don't I just try it and see.
..Ok I have an alternate PR :)

**Comment by RachL** [comment]
@filipefurtad0 I think that https://github.com/openfoodfoundation/openfoodnetwork/pull/10333 will close this issue completely?

**Comment by filipefurtad0** [comment]
Not introduced here as these PRs are not yet in production, but perhaps good to document: we've observed this bugsnag error which seems related to currencies in shipping method calculators:

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/63da7254a81c370008605893?event_id=63da725400ad2e7b61620000&i=sk&m=nw

**Comment by dacook** [comment]
Strange. But I think it should no longer happen after this new PR anyway 🤞

**Comment by dacook** [comment]
The main part was merged on 25th Jan: hiding the currency input field.

The cleanup is a bit more complicated, so I've moved to a new tech debt issue: #10521
