### ISSUE TITLE
Add red asterisk to mandatory fields in business detail

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10271]
## Description
**- As a:** enterprise admin or superadmin
**- On page:** `/admin/enterprises/ENTERPRISE#!#business_details_panel`
**- I want to be able to do:** 

See a red asterisk next to the title of the mandatory fields:
    Company Legal Name
    Legal Address
    City / Postcode
    Country / State
    Legal Phone

![image](https://user-images.githubusercontent.com/6525576/212362976-1fa48d2d-c8db-4766-a846-e0e707f98f93.png)

## Acceptance Criteria & Tests

1. Login
2. See the red asterisk
3. Check the mandatory fields still work

**Comment by filipefurtad0** [comment]
Hey @RachL ,

Should we include ABN / ACN fields in this group of mandatory fields? Currently, these are not, even if any of the business details are filled in, and the user has `Charges GST?` set to `true`:

![image](https://user-images.githubusercontent.com/49817236/214577363-de220e88-a1ec-4b9c-92f4-abc28fb50780.png)

What do you think?

**Comment by RachL** [comment]
@filipefurtad0 I've noticed this as well. I concluded that if no one asked for this until now, maybe there are country where you can be charge with taxes without having a company number 🤷‍♀️ But maybe I did a shortcut and we should ask instance managers.
