### ISSUE TITLE
OFN CAN outgoing platform emails not being sent 

### ISSUE THREAD

**Issue by karlafalk** [openfoodfoundation/openfoodnetwork#10306]
## Description
OFN Canada's outgoing platform email account [orders@openfoodnetwork.ca] is not sending out platform emails.  We think this is an issue with authentication of our email credentials and need to be addressed at the system admin level.   The email itself (orders@openfoodnetwork.ca) is working and we are able to send & receive emails from it.

We had an issue with the gmail account 5 days ago when it was shut down do to 'suspected spamming', but once we had the email account reactivated, emails didn't not automatically resume being sent, so we had to have the authentication details reset in the server.  Once they were reset the platform emails resumed sending, but then stopped again (~1 day later), and have not been outgoing since Jan. 19th.  This time the cause is different, as this not due to a google suspension -- we logged into the orders@ email account and are able to send and receive emails manually. A history of the issue can be found in this [slack thread.](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1674060957688379)

## Expected Behavior
When an order is placed an order confirmation email should be sent to the customer and the enterprise account through our orders@openfoodnetwork.ca gmail account.

## Actual Behaviour
No confirmation emails are being sent.

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

**Comment by dacook** [comment]
For some reason the old login details got reverted on the serve.r I've manually updated these again and will investigate why it got changed.

![Uploading Screen Shot 2023-01-19 at 12.19.56 pm.png…]()

**Comment by dacook** [comment]
This was due to a problem I have in ofn-install, I've raised here: https://github.com/openfoodfoundation/ofn-install/issues/861
I don't know why yet, but it's easy to work around so I'll make sure I don't use that method again!
