### ISSUE TITLE
Wrong user fees on Enterprise bulk edit page

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1032]
On UK Production - When logged in as an admin, and using the Enterprise bulk edit page, if you click on the drop downs in the 'Package' column it gives the monthly user fees as 1% of monthly fees. This needs updating to 2%? 
![1 sales figures](https://cloud.githubusercontent.com/assets/19837861/15929962/2fdea44e-2e48-11e6-95e6-6a6a11349293.png)

**Comment by lin-d-hop** [comment]
Hi Mags,

This is a super admin task (though it should not have been incorrect). You can fix it yourself in Admin - Configuration - Business Model - Percentage of Turnover.

**Comment by MagsHall** [comment]
That's set correctly to 2% already I'm afraid!

**Comment by lin-d-hop** [comment]
Yep. I fixed it. Fixed in the profile too. Was just letting yo uknow for future that this wasnt a bug for github.

![ofnmags](https://cloud.githubusercontent.com/assets/8669848/15930935/4fa3450a-2e4d-11e6-9766-c5b400891ec6.png)
