### ISSUE TITLE
Cancelled orders are included in 'Notify producer' process

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1034]
I created and then immediately cancelled these two orders...
![screenshot 2016-06-12 20 33 59](https://cloud.githubusercontent.com/assets/10517702/15993406/1a6c99c6-30dd-11e6-86e8-0717f8cd9ecc.png)
......but they were then included in the automatic orders to producers that went out the following day...

From: hello@openfoodnetwork.org.uk [mailto:hello@openfoodnetwork.org.uk] 
Sent: 09 June 2016 07:34
To: jackierowanly@yahoo.co.uk
Cc: manager@stroudco.org.uk
Subject: [Open Food Network UK] Order cycle report for Jackie Rowanly & Co

	 
OPEN FOOD NETWORK UK 
	
	Dear Jackie Rowanly & Co, 
We now have all the consumer orders for the next food drop. 
Here is a summary of the orders for your products: 
SKU 	Supplier 	Product 	Quantity 	Price 	Subtotal 	Included tax 
jb 	Jackie Rowanly & Co 	Jostaberry Bushes - 1pot 	4 	£2.92 	£11.68 	£0.00 
	Jackie Rowanly & Co 	Redcurrant bushes - 1 pot 	2 	£2.92 	£5.84 	£0.00 
					£17.52 	£0.00 
Please confirm that you have got this email. Please send me an invoice for this amount so that we can send you payment. If you need to phone me on the day, please use the number below. 
Thanks and best wishes, 
Stroudco Food Hub 

Stroud Valleys School 
Stroud 
GL5 2HP 
0845 330 6340 
manager@stroudco.org.uk 

	
	Terms of service | Open Food Network UK

**Comment by stveep** [comment]
Are we running 1.8.1 on UK now? I thought I fixed this when Sara raised a similar issue a few weeks ago, and the fix should be in 1.8.1.

https://github.com/openfoodfoundation/openfoodnetwork/issues/1009
https://github.com/openfoodfoundation/openfoodnetwork/pull/1011

**Comment by lin-d-hop** [comment]
Not yet, issues with deployment after moving the hosting. Deploying asap, staging deployed so can text on there?

**Comment by NickWeir63** [comment]
I went to staging and found that all the order cycles had been wiped (not a big problem - I have recreated a test cycle but it does mean that we are still losing data on a deploy)
I created and then cancelled an order then pressed 'Notify producers' and the producer did not receive an email.  So closing this now
Thanks @stveep (sorry i forgot that you were working on this)
