### ISSUE TITLE
do not display empty categories

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1036]
The stroudco shopfront is displaying 28 product categories (taxons)..........
![screenshot 2016-06-14 14 16 45](https://cloud.githubusercontent.com/assets/10517702/16044479/8011aebe-323c-11e6-8a17-17d256fda2cd.png)
.......... even though most of them are not being used by Stroudco.
Please can we only display categories that this shopfront is actually using so that shoppers do not click on a category with nothing in it

**Comment by OliverUK** [comment]
@NickWeir63 
You can likely close this as I've discovered the categories weren't truly empty. When I tried with "Vinegars" it did go once empty.
