### ISSUE TITLE
Field description in not updated when Import is done

### ISSUE THREAD

**Issue by Trementinaire** [openfoodfoundation/openfoodnetwork#10374]
## Description
When I update info products with import option, all fields are updated except for the Description field

## Expected Behavior
Description field should be updated

## Actual Behaviour
Remains olf info in the Description field

## Steps to Reproduce
1. Acces to import
2. Load correct CSV
3. No errors detected
4. Check products and Description is not updated

## Animated Gif/Screenshot
CSV uploaded
![imatge](https://user-images.githubusercontent.com/124343506/216579091-e230a73f-e97f-4afc-8be8-994f82653750.png)
Description field not uploaded
![imatge](https://user-images.githubusercontent.com/124343506/216579329-29a4d15c-7bb9-4571-85d2-b21c72695dda.png)

## Workaround
Modify manually

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: I don't know
* Browser name and version: Firefox and Chrome 
* Operating System and version (desktop or mobile): Windows

**Comment by sigmundpetersen** [comment]
From the [user guide](https://guide.openfoodnetwork.org/basic-features/products-1/product-and-inventory-import#prepare-the-csv-file-for-import-1), this is expected. Along with other fields like `variant_unit_name`, `tax_category` and `shipping_category`.

If you want to suggest changes, you can add an issue to our [wishlist](https://github.com/openfoodfoundation/wishlist) repo. Thanks
