### ISSUE TITLE
[BUU] Listing products raises error if image URL is missing

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#10377]
## Error in OpenFoodNetwork Aus

**ActionView::Template::Error** in **admin/products#index**
Nil location provided. Can't build URI.

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/63e0998dabba4f00082d8a0f?event_id=63e0998d00ad1a49d5560000&i=gh&m=ci)

## Stacktrace

    app/components/product_component/product_component.html.haml:5 - block in call
    app/components/product_component/product_component.html.haml:2 - each
    app/components/product_component/product_component.html.haml:2 - call
    app/components/products_table_component/products_table_component.html.haml:18 - block in call
    app/components/products_table_component/products_table_component.html.haml:1 - call
    app/views/admin/products/index.html.haml:8 - _app_views_admin_products_index_html_haml__1371898613196803321_1084120
    lib/session_cookie_upgrader.rb:19 - call

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/63e0998dabba4f00082d8a0f?event_id=63e0998d00ad1a49d5560000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by isidzukuri** [comment]
folder `app/components/product_component`does not exists. And i could not find anything similar enough. Looks like code was refactored and stacktrace is outdated now. 

But if the same exception still raise in in other places possible solution is here https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/admin/products_v3/_table.html.haml#L57

```ruby
image_tag product.image&.url(:mini) || Spree::Image.default_image_url(:mini)
```

**Comment by mariocarabotta** [comment]
based on @isidzukuri's comment and chat with @dacook , we're closing this as not planned.

**Comment by mariocarabotta** [comment]
based on @isidzukuri's comment and chat with @dacook , we're closing this as not planned.
