### ISSUE TITLE
[Split checkout] Change content fo the en.yml file to help translators and remove some error messages

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10384]
## Description
**- As a:** shopper using split checkout
**- On page:** `/checkout/details`
**- I want to be able to do:** 

If I forget to fill a mandatory field, I need to see an error message that matches the names of the field.

Currently we have this message:

> Saving failed, please update the highlighted fields. Bill address address1 can't be blank, Bill address city can't be blank, Bill address phone can't be blank, Bill address firstname can't be blank, Bill address lastname can't be blank, Bill address zipcode can't be blank, First name and name can't be blank, City can't be blank, Phone number can't be blank, First name can't be blank, Last name can't be blank, Code postal can't be blank, Customer E-Mail can't be blank, Customer E-Mail is invalid, and Shipping method Select a shipping method

It should be (I've changed order and names of fields + removed First name and name and Bill address phone):

> Saving failed, please update the highlighted fields. Customer E-Mail can't be blank, Customer E-Mail is invalid, Customer phone can't be blank, Bill address first name can't be blank, Bill address last name can't be blank, Bill address (Street + House Number) can't be blank, Bill address city can't be blank, Bill address zipcode can't be blank,Bill address City can't be blank

> 
![image](https://user-images.githubusercontent.com/6525576/217044523-fbdf5322-39e0-42ee-9812-869484ce3c22.png)

+ We need to apply the rules chosen for billing address to shipping address

## Acceptance Criteria & Tests

1. Turn on split checkout
2. Check the error messages are matching fields title for all mandatory fields

**Comment by jibees** [comment]
Todo: 

- [ ] Change the order of the error message:
    - [ ] Customer Email and Customer Phone at the begining
- [ ] Remove `First name` and `Last name`
- [ ] Replace `Bill address phone` and `Phone number` by `Customer phone`
- [ ] Replace `Bill address address1` by `Bill address (Street + House Number)`


From: 
```
Bill address address1 can't be blank, Bill address city can't be blank, Bill address phone can't be blank, Billing address first name can't be blank, Bill address lastname can't be blank, Bill address zipcode can't be blank, Shipping address line 1 can't be blank, Shipping address suburb 1 can't be blank, Phone number can't be blank, First name can't be blank, Last name can't be blank, Shipping address postcode can't be blank, Customer E-Mail can't be blank, Customer E-Mail is invalid, and Shipping method Select a shipping method
```

To:
```
Saving failed, please update the highlighted fields. Customer E-Mail can't be blank, Customer E-Mail is invalid, Customer phone can't be blank, Bill address first name can't be blank, Bill address last name can't be blank, Bill address (Street + House Number) can't be blank, Bill address city can't be blank, Bill address zipcode can't be blank,Bill address City can't be blank
```
