### ISSUE TITLE
Columns incorrectly aligned in order cycle customer totals report

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1038]
![image](https://cloud.githubusercontent.com/assets/10843056/16065139/226b3ef6-32eb-11e6-9069-ef97a695d0bd.png)

**Comment by sstead** [comment]
Can we prioritise fixing this bug? This report is the most comprehensive of them all so it's important that it's working.

**Comment by daniellemoorhead** [comment]
Have got this on @bingxie's to-do list @sstead, he'll no doubt be in touch to chat to you about it :)
