### ISSUE TITLE
[current master, not in prod] Missing pagination from orders page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10390]
## Description

Merging #10375 broke the build as the branch was behind a recently introduced spec https://github.com/openfoodfoundation/openfoodnetwork/pull/10344: It fixes BOM page, but removes the pagination info, from the orders page.

## Expected Behavior

Orders page should have pagination information.

## Actual Behaviour

Pagination information is missing from the orders page.

## Steps to Reproduce

1. Visit /orders. Notice the `x Results found Viewing y to z results` info is missing.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/217314240-ba36928b-2ee7-4f86-86e8-6be32397f373.png)

## Workaround

-

## Severity

an S2 but not in prod.

## Your Environment

* Version used: current master -> https://github.com/openfoodfoundation/openfoodnetwork/commit/0f203a474cb79316b88182d89fe038898f5217cb

**Comment by RachL** [comment]
We are doomed with this work 🙈

**Comment by jibees** [comment]
A bit ;)
Thanks to @filipefurtad0 to create new automatic spec and spotted that before releasing!

**Comment by filipefurtad0** [comment]
> new automatic spec and spotted that before releasing!

A very fortunate accident... I've missed this on manual testing... again :grimacing:

**Comment by RachL** [comment]
Hey at least we improve automated tests :)
