### ISSUE TITLE
translation issue in reset password email

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1039]
![image](https://cloud.githubusercontent.com/assets/8135376/16072676/76eeaa48-32e2-11e6-99fc-dce31dfc7d91.png)

**Comment by myriamboure** [comment]
@blancnic do you know how to solve that? I tried again today and the problem is still there. If not can you ping the relevant persons? Thanks!

**Comment by myriamboure** [comment]
Also issue in object of automatic emails (here: welcoming email) 
![screenshot from 2016-09-05 12-41-31](https://cloud.githubusercontent.com/assets/8135376/18245565/374232ce-7366-11e6-9a44-7bb4422d72f5.png)

**Comment by myriamboure** [comment]
@sigmundpetersen do you have the same issue in Norway? I'm wondering if it's an internationalisation issue or only the French config.

**Comment by sigmundpetersen** [comment]
You mean the "translation missing" issue? These are keys not added to the yml files for translation yet (thus not added to Transifex). For Norway I translate all these "translation missing" manually in the yml file on the instance server.

So here fr.enterprise_mailer.welcome.subject will be the key

fr:
  enterprise_mailer:
    welcome:
      subject:

**Comment by jum-s** [comment]
Reproducing the bug on my locale machine, I found out that the translation of `t('enterprise_mailer.welcome.subject')` is effective, as wee can see on this mail log : 

    #<Mail::Message:136950770, Multipart: false, Headers: <Date: Mon, 28 Nov 2016 21:22:04 +0100>, <From: test@example.com>, <To: jums@dev4dev.eu>, <Message-ID: <583c91ec9200c_26664a0099817371@lordon.mail>>, **<Subject: MauriceBidochon Inc. est maintenant sur Spree Demo Site>**, <Mime-Version: 1.0>, <Content-Type: text/html>, <Content-Transfer-Encoding: quoted-printable>

I haven't check the reset password translation but I will dig on that soon

**Comment by jum-s** [comment]
About the reset password translation (which might be another issue than my last comment topic), I havent seen any translation of this reset password email in `config/locale` translation files. My intuition would be that the english text in the mail is the default devise setup.

I havent find any 'overwriting' devise controller relating to `send_reset_password_instructions` method which is a devise function implemented in `/app/controllers/user_passwords_controller.rb"
One solution could be to overwrite this devise default method by adding a new one called `reset_password_instructions` in `app/mailers/enterprises_mailer.rb` that would do the translation

**Comment by myriamboure** [comment]
Great that you can work on this @jum-s :-)
I just reproduced the translation mission in entreprise registration validation, I went at the bottom of the page and clicked on "inscription producteurs", I followed all the steps and received that email.
![screenshot from 2016-11-29 09-17-04](https://cloud.githubusercontent.com/assets/8135376/20701675/a2d9ec34-b614-11e6-9d07-8ec07f5f4052.png)

About the reset password message, it would be awesome if it could be translated in Transifex so that every instance can then translate the content of the message, I guess we all have the same issue ;-)
If you have doubts on how to connect with Transifex you can ask Maikel, or maybe Emilien (in France) will know as well, he worked on translations during the Berlin Hackaton.

**Comment by myriamboure** [comment]
@pacodelaluna do you think the work you have done on translations solve that "reset password" email translation issue?

**Comment by mkllnk** [comment]
Now translatable via #1548.
