### ISSUE TITLE
Error when no shipping info has been selected in split checkout

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#10402]
## Description
When using the split checkout feature toggle,
On the first step, if you don't select any shipping options and click next, an unhandled error occurs.

The error is: https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/63e444615e34f60008a82b2b?event_id=63e4446100ad28aa1f5f0000&i=sk&m=nw

## Expected Behavior
I assume this is required, so I think there should be a validation error to say so.

## Actual Behaviour
🐌 

## Steps to Reproduce
* Split checkout
1. Add to cart
2. Click checkout
3. Enter address details, but don't select shipping method
4. Click next.

## Animated Gif/Screenshot
![Screen Shot 2023-02-09 at 12 12 49 pm](https://user-images.githubusercontent.com/4188088/217689355-9b3404cb-d556-46ae-af5a-f359f3c03431.png)
![Screen Shot 2023-02-09 at 12 13 03 pm](https://user-images.githubusercontent.com/4188088/217689361-8b092359-a55d-4508-912c-97c41a34bb0b.png)

## Workaround
Select a shipping method before clicking next.

## Severity
Not sure how to classify for a feature toggle.

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): macOS

**Comment by dacook** [comment]
FYI @jibees

**Comment by RachL** [comment]
That's weird because I can't reproduce it in staging FR... what's the difference between the two? 

![image](https://user-images.githubusercontent.com/6525576/217764233-677fa07f-b0ee-4ac3-a985-d16c3484650c.png)

**Comment by filipefurtad0** [comment]
So @dacook has reproduced this in [staging-UK](https://user-images.githubusercontent.com/4188088/217688877-6722c838-d72e-46e8-82af-4df27caae09f.mov) and staging-AU (above).

I've checked a random account in staging-UK and cannot observe it -> I get the expected behavior (same as you've posted above @RachL ).

So there must be a data combination which triggers this. I'll look into the bugsnag, see if I can reproduce it consistently.

**Comment by filipefurtad0** [comment]
Ok, I've reproduced it in staging-UK now: the error is triggered for **first time customers** only.

I guess if the shipping address (or any required information in Details) is missing, the app should not 'try' to update the customer:

`app/services/default_address_updater.rb:18`
`customer.save`

Right?

My steps to reproduce were:
- creating a new OFN account
- login (I've tried this with a guest account, but could not trigger it)
- visit an open shop and add items to cart
- fill all personal and billing details; leave shipping details empty
- click `Next - Payment Method`

**Comment by RachL** [comment]
![ ](https://media.giphy.com/media/CI6hQq7NgmCqI/giphy.gif)


Nice catch !!! this makes it an s2 for the roll-out I think! Upgrading the severity

**Comment by jibees** [comment]
Actually pretty easy to text:

`spec/system/consumer/split_checkout_spec.rb#287`:

```ruby
    context "when no selecting a shipping method" do
      before do
        fill_out_details
        fill_out_billing_address
      end

      it "does not throw an error" do
        click_button "Next - Payment method"
        expect(page).to have_content "Please select a shipping method"
      end
    end
```
