### ISSUE TITLE
Producer/Supplier fees added to an OC are not displaying in the shop

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#10401]
## Description
Producers who are suppliers to hubs are able to add an enterprise fee (created in the producer's enterprise profile) to their products being sold by a hub.  This fee is different from a hub coordinator's fee.   A hub coordinator can add an enterprise fee to an order cycle on the 'General Settings' page of the OC setup -  and this fee will apply to ALL products coming into that OC.   But in addition to,   or instead of the coordinator fee -   it has always been possible for a producer/supplier enterprise fee to be added to an OC.  When a producer/supplier enterprise fee is added (on the incoming page of the OC),  this fee applies to that producer's products only.

After this week's release,  it does not seem possible to add a producer/supplier enterprise fee to an OC.  (Unless missing something very obvious.)

## Expected Behavior
A coordinator of an OC should be able to add a producer/supplier enterprise fee to the OC in the 'incoming' section.

## Actual Behaviour
The order cycle can be setup,  and the fee added to the OC -  but it does not show in the shop price description,  and the fee is not calculated upon purchase.

## Steps to Reproduce
1. Set up an OC with at least 1 supplier
2. Set up a fee for that supplier in the supplier's profile
(I tested with a per item fee - but haven't tested yet with other fee types)
3. Open the shop - and see that the fee does not display in the product price in the shop.

## Workaround
I don't know any other way to add a supplier fee to an OC.

fee created in producer/supplier's profile:
![demo supplier enterprise fee set](https://user-images.githubusercontent.com/13171778/217681925-89f4ae32-8356-4e7f-aed7-5b765551629a.png)

fee entered into the incoming section of the hub's OC
![demo supplier enterprise fee added to oc incoming](https://user-images.githubusercontent.com/13171778/217681935-57fff70f-04ac-482f-abf7-0477864fc1d7.png)

Fee is not calculating on the price or showing in the shop
![store - supplier fee not showing in price breakdown](https://user-images.githubusercontent.com/13171778/217682158-76fbd35a-5ec3-40fb-8aab-99eb63b5f398.png)

No fee  calculated on an order placed in the shop
![order confirmation - no fee and no tax on fee](https://user-images.githubusercontent.com/13171778/217681953-1c7846cc-d867-48e5-830a-0745645434f1.png)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by tschumilas** [comment]
I think I see my mistake....

**Comment by tschumilas** [comment]
sorry - double checked,  and I don't see if I made a mistake.   I just checked some order cycles with supplier/producer fees added that were set up before the last update and those fees are showing in the shop fine.   So I think this happened with last release.

An s1?  if there is no workaround?

**Comment by filipefurtad0** [comment]
For supplier A and  OC Coordinator / Distributor B:

Setting enterprise fees in the following way
![image](https://user-images.githubusercontent.com/49817236/217787830-ba6421eb-3dde-4440-bcfb-a64fbd7a11a0.png)

Adding the supplier fee to the OC:

![image](https://user-images.githubusercontent.com/49817236/217791084-5477e402-bf9e-4b4d-bdf5-f34667b7fd92.png)

Shows it in the shopfront:

![image](https://user-images.githubusercontent.com/49817236/217791217-e8577b15-4cd9-4e56-bfea-29512d8e25ab.png)

Appears on the order edit page after checking out:

![image](https://user-images.githubusercontent.com/49817236/217791651-d013b787-284a-467d-be50-0bc3d9536375.png)

**Comment by filipefurtad0** [comment]
However, if the the distributor adds it's own enterprise fee, in the OC outgoing exchange:

![image](https://user-images.githubusercontent.com/49817236/217794206-b834ed7d-2389-4e0d-b533-0f0e99dad52e.png)

then it all looks like this:

Shopfront - notice only the distributor fee (OUTGOING) appears, but it includes the variant:

![image](https://user-images.githubusercontent.com/49817236/217793315-ac4d38b5-f584-4d22-8cde-73586ab9e8c2.png)

But it **includes** both percentages, applied over the product - 10% `incoming` + 10% `outgoing`. This can be seen in the order edit page:

![image](https://user-images.githubusercontent.com/49817236/217793988-589d3e14-f2ef-434c-a293-84ef82cb33ab.png)

**Comment by RachL** [comment]
@filipefurtad0 before pinging everyone I did a test on my own - but now I realized I I've tested a different scenario than yours and Theresa: I assumed the hub didn't have access to the producer profile. So I've added a **hub fee** in the incoming section on a particular producer. And it did not show up in the shopfront. 
Real life use case of this is if a hub needs to handle logisitics for a particular producer, they will want to add their own fee on top of the producer, not a producer fee.

Maybe there is a problem with fees and it works sometimes because the hub has permissions on the producer?

**Comment by sigmundpetersen** [comment]
Filipe I guess your last scenario is #9751 ?

**Comment by filipefurtad0** [comment]
Thank you @sigmundpetersen - that's really good to know, so, no regression here :pray: 

> Real life use case of this is if a hub needs to handle logisitics for a particular producer, they will want to add their own fee on top of the producer, not a producer fee.

@RachL, great clarification. If I understand correctly, you mean:
- adding an enterprise fee (from the distributor - Kimchi Hub below)
- on the incoming section
- on the supplier exchange? 

Like this:

**Incoming section**
![image](https://user-images.githubusercontent.com/49817236/217797087-2bd1f89d-be8f-4955-8356-44a8fdf9772f.png)

And keeping the **Outgoing section** with no additional fees:
![image](https://user-images.githubusercontent.com/49817236/217797861-0b0961ad-0259-4e4f-b020-636fd5fbc634.png)

In this case, I can still see the fee appearing in the shopfront:
![image](https://user-images.githubusercontent.com/49817236/217798028-c717bdf3-a6b5-4cb4-98f2-c6094c955538.png)

**Comment by RachL** [comment]
oh boy this is a tricky one. I can't reproduce anymore as well.

However I noticed that when I came back to my test, the fee was not showing up anymore in the OC.

Instead of it being a problem with the fees, could it be a problem with the saving of the OC?

@tschumilas can you still see the fees in the incoming section when you go edit the OC?

**Comment by tschumilas** [comment]
If I go to edit the OC  -  yes,  I see the producer fee show up in incoming where i placed it.     Further -   in both incoming and outgoing I am able to add (I see in the dropdowns)  all the possible producer and hub fees as set up in their respective profiles.   So - I see all the options.

BUT -  in my example above -  the producer and hub enterprises are owned by the same user.   

And the fee type (in case it matters)  is flat rate (item).  

I can do more testing of scenerios today if its helpful -  let me know if there are particular configurations to look into....  We know this just happened yesterday with the latest release.  A shop i set up just the day before is displaying fees fine.

**Comment by tschumilas** [comment]
And if its helpful --   I went into a hub that was setup -   with a producer fee in incoming,  and no coordinator fee at all -  set up before the latest release -   and the fees are calculating properly, displayed properly.   I placed an order,  and fees and taxes are all calcualted fine on my order.

**Comment by filipefurtad0** [comment]
Thank you for those details Theresa. So I guess this means that we have an identical setup in production (one before, the other one after the release), and in one case all works, the other one does not. Do I understand this right?

Can you spot any differences on how the fees are set? For example:
- which tax categories are set on the enterprise fees? Or are they rather pointing `Inherit from product`? (and, if so, what is the tax category of the product?)
- which calculators are used?
  (sorry, many questions!)

I'll make some more tests and drop a line if I can reproduce it.

**Comment by tschumilas** [comment]
Strange thing - works now.
 Here's what I did:

originally - fee type was 'flat rate (item)',  entered as producer fee - incoming -  **tax on fee was 'taxable'** ,   tax on my test product was 'taxable'   -  that is the set up for my first issue report above -  fees did not calculate in the shop.

I checked that just an hour ago -  and fees were not calculating in the shop

Just now -  I tried changing the tax category for the fee  to '**inherit from product**'

And -  voila - the fee was calculated in the shop.

I changed the tax category for the fee **back to 'taxable'** and -  the fee is calculated and showing in the shop.


I'm just going to purchase and see if the taxes on product and taxes on fee are calculating correctly...

**Comment by tschumilas** [comment]
Yes -  fee is calculating in the shop,   and taxes on the product and on the fee are calculating on my order.

What on earth?

**Comment by tschumilas** [comment]
I am no longer able to replicate this.  I've tried different tax categories for the fee  -  and the producer fee, entered in incoming,  is now consistently displaying in the shop price.      But - I reallyl can't see what my error was in my original report.  I double and triple checked the fee setup and the OC before I reported and after I reported.

**Comment by RachL** [comment]
The fact that I've experienced something similar makes me think we have something fishy here but we haven't nailed the way to reproduce it yet. 
I propose we keep a close eye on it in the coming days: keep fees in all our tests / use of the platform. And in the meantime we close here? We reopen when we have a new case of course.

**Comment by tschumilas** [comment]
ok (Incidently -  the reason I even found this issue was because I was setting up a new OC to test the newly released producer tax report. It seems to me that taxes on producer enterprise fees are not showing in the report. (so taxes are underreported to the hub coordinator in that report)  I just want to test that for different types of fee calculators -  and will open an issue.    It could be that we did not think producer enterprise taxes on fees ought to be in this report ---  and then we just need to think about what report they ought to be in.....)  Closing the current issue now.
