### ISSUE TITLE
Update link and emails in enterprise sign up emails

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1041]
In 'Welcome to Open Food Network UK' email (first email when you make an account) there is still one reference to the AUS email address in the body of the text 

![sign up email - still got aus address](https://cloud.githubusercontent.com/assets/19837861/16076848/5bf09804-32ed-11e6-85cb-912565f0691f.png)

In welcome email for new enterprises ('xx is now on Open Food Network UK') the 'join the community' link takes you to the International discourse - needs to be updated to UK site
![wrong link to discourse page](https://cloud.githubusercontent.com/assets/19837861/16076915/a3d081fc-32ed-11e6-89bd-007129bd9dc6.png)

Is it perhaps also worth adding the support email in here? Something like 'If you still can't find the help you need, get in touch with our support team directly at support@openfoodnetwork.org.uk'

**Comment by lin-d-hop** [comment]
@mkllnk @daniellemoorhead @sstead 
Regarding Mags' 2nd point above, I'm wondering the best way to make the 'Join the Community' link the right one.
Currently the instance discourse URL is stored as an env var. However my feeling is that actually just linking the to instance discourse is not what many will want.
Some instances will wish to point to the global, i assume. And some their own forum.
I'm thinking this would be best set up as a config in super admin. What do y'all think?

**Comment by daniellemoorhead** [comment]
Sounds like the right move tome @lin-d-hop :)

**Comment by lin-d-hop** [comment]
PR #1090

**Comment by lin-d-hop** [comment]
@MagsHall can you test this is now fixed please?
