### ISSUE TITLE
[Vouchers] Implement bare minimum backoffice

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#10431]
## Description

The bare minimum backend implements the initial logic to create a voucher. These vouchers will be vastly simplified from the [final designs](https://www.figma.com/file/ZOe1Xmz4kg9wnHw1XFu389/Voucher-Back-office?node-id=47%3A301)

Two backoffice pages in Enterprise Settings:
1. Add Voucher Page
User can include a Voucher code - typed
No option to 'generate code'
Voucher type limited to 'flat amount'
Amount limited to $10
Expires and date not included - vouchers are infinite by default
Leave off 'voucher purpose' (later we can default to food equity)
Leave off 'Label'

2. List Vouchers Page
Leave off all filters
Include 'add new' button
Include table with cols 'Voucher Code', 'Rate'. All else dropped.
No delete yet.

At time of writing there was still some debate/exploration of how the data model will work - will we use the existing calculators and adjustments functionality? Will this fit in with tax implications? The plan is make as few implementation decisions as possible about this while we check in with AU accountant. Please document any assumptions that are made along the way.

## Acceptance Criteria & Tests

1. Simplified BE implementation as described above
2. We won't have a checkout version to test this yet, so we can just test the creation of Vouchers are created in data model and thus  list page as expected
3. Translations as standard
4. Unit tests as standard

**Comment by rioug** [comment]
Review comment from @dacook 
> Something to consider in the future steps will be what characters are allowed in the code. For example, a space or any word separators probably should be excluded.
> This makes it easier to copy/paste a code when double-clicking to select the code. For example try double-clicking on this: FREE:TOMATOES! 

It's something we should address, but maybe at a later stage ?
