### ISSUE TITLE
Discounts and Vouchers at Checkout

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#10430]
:information_source: Please track development and code review under the project **`##10430 Vouchers - Aus Pt 2 (UK)`**.

## What is the problem we are solving 

As an enterprise I can enable vouchers to be applied at checkout
As a shopper I can use a voucher at checkout

## Link to the "Product Development - Backlog" item in Discourse

[FE Design](https://www.figma.com/file/5Ax3XD6NsptPmb2a8sJcR6/Voucher-checkout-front-end?node-id=1419%3A71)
[BE Design](https://www.figma.com/file/ZOe1Xmz4kg9wnHw1XFu389/Voucher-Back-office?node-id=47%3A301)
[Discourse](https://community.openfoodnetwork.org/t/vouchers-discounts-credits-v1-designs/2752)

**Comment by RachL** [comment]
2 issues will be left: [activating the toggle everywher](https://github.com/openfoodfoundation/openfoodnetwork/issues/11827)e + removing the toggle. But i'm closing to make dev ready a bit more clear on what's left to do.
