### ISSUE TITLE
Shop front not loading

### ISSUE THREAD

**Issue by Rocksj** [openfoodfoundation/openfoodnetwork#1047]
Two customers reporting problems with the shopfront loading due an unresponsive script as below:

![ofn script message](https://cloud.githubusercontent.com/assets/15102362/16204272/059698fa-3716-11e6-8c7d-205810086265.jpg)
AND
![screen shot 2016-06-21 at 08 58 20](https://cloud.githubusercontent.com/assets/15102362/16222155/84a0e0a6-378e-11e6-9371-fa90e9f25a40.png)
In the second instance the first product also failed to load. The first was on a PC, the second on a Mac

**Comment by OliverUK** [comment]
I used to get these all the time. It was just a matter of clicking continue and giving it more time.
I've not had any recently thought.

**Comment by lin-d-hop** [comment]
@Rocksj Can you confirm this is still an issue. v1.8.3 deployed with some speed enhancements.

**Comment by Rocksj** [comment]
Afraid so @lin-d-hop 
![screen shot 2016-08-01 at 11 57 00](https://cloud.githubusercontent.com/assets/15102362/17292114/b92ccc06-57df-11e6-8ebd-9dfbb1fff6a8.png)

**Comment by Rocksj** [comment]
And 3 customers who we know of complaining this week that the system is slow, crashing and they are not ordering because of this. We have managed to put through one manually but this is clearly still an issue.

**Comment by Rocksj** [comment]
Both PCs, one on a Windows laptop (unknown spec) but about 2 years old. Another was from a works PC, pretty new fangled sparkly workplace, the third unknown. I'll try to find out more if that would be helpful? Is there a standard list of questions to ask?

**Comment by lin-d-hop** [comment]
Yeah finding out the device (mobile, laptop etc), OS and version (windows 7, ubuntu 12.04), browser (chrome, IE), age, internet connection (3G, wifi) can be helpful. But clearly we have a real problem that needs to be unpicked as fast as possible!

**Comment by OliverUK** [comment]
As it used to happen to me, would it help to know about my computer?
![screen shot 2016-08-03 at 13 44 09](https://cloud.githubusercontent.com/assets/17590921/17365909/76534a7a-5980-11e6-9feb-f51d02db1ea1.png)

**Comment by lin-d-hop** [comment]
How did it stop happening? @OliverUK

**Comment by OliverUK** [comment]
I'm afraid I don't know. It's still slow but the Unresponsive Script pop-up doesn't come up anymore.

**Comment by oeoeaio** [comment]
@Rocksj @lin-d-hop @OliverUK 

We are trying to release an update today as v1.8.4 that may help with this. It's around improving shopfront performance (esp. initial load and subsequent searching/filtering) mainly in response to @OliverUK's post on [discourse](http://community.openfoodnetwork.org/t/what-s-new-v-1-8-3-160720/636/2).
