### ISSUE TITLE
[Background reports] Internal server errors 500 (snail) on report generation

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10483]
## Description

This is addressing the final bits of #10413.
There were still internal server errors 500 in some cases which should be fixed before releasing background reports to production.

Note for testers: Maybe worth testing every single report as admin and super admin again before final release to production.

## Expected Behavior

There should be no internal server errors.

## Actual Behaviour

There were internal server errors on the following reports (all as super admin only):
- Payments by type (with and without date restriction)
- Order Cycle Supplier Totals (without date restrictions)

## Steps to Reproduce

1. As super admin go to staging UK
2. Try to access the mentioned reports above

## Animated Gif/Screenshot

| Report type | Background reports activated | **admin** user (**w/o** date restriction) | **admin** user (**with** date restriction) | **super admin** user (**w/o** date restriction) | **super admin** user (**with** date restriction) | 
| - | - | - | - | - | - |
| Orders And Distributors | yes | not tested | not tested | :x: Timeout 504 | :heavy_check_mark: |
| Bulk Co-op Supplier Report | yes | not tested | not tested | :x: Timeout 504 | :heavy_check_mark: |
| Payments By Type | yes | not tested | not tested | :x: Internal Server Error 500 (21:41) | :x: Internal Server Error 500 (21:44) |
| Order Cycle Supplier Totals | yes | not tested | not tested | :x: Internal Server Error (21:48) | :heavy_check_mark: |
| Mailing List | yes | not tested | not tested | :heavy_check_mark: | n.a. |
| All products | yes | not tested | not tested | :x: Timeout 504 | n.a. |
| Users & Enterprises | yes | not tested | not tested | :heavy_check_mark: | n.a. |
| Enterprise Fee Summary | yes | not tested | not tested | :heavy_check_mark: | :heavy_check_mark: |
| Payment Methods Report | yes | not tested | not tested | :x: Timeout 504 | :heavy_check_mark: |
| Tax Types | yes | not tested | not tested | :x: Timeout 504 | :heavy_check_mark: |
| Xero Summary | yes | not tested | not tested | :x: Timeout 504 | :heavy_check_mark: |
| Pack By Customer | yes | not tested | not tested | :x: Timeout 504 | :heavy_check_mark: |
| Revenues By Hub | yes | not tested | not tested | :heavy_check_mark: | :heavy_check_mark:  |

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by drummer83** [comment]
Hi @mkllnk and @Matt-Yorkley,

Here are my results of checking the background reports again. I did this on staging UK server.

## General findings
- After staging master or after restarting Sidekiq, the sidekiq process consumes one CPU with ~100 % for ~ 30 minutes.
- After 30 minutes the CPU load drops to ~0 %, unless reports are requested.
- Time needed for report generation varies extremely. I have seen the Order And Distributors w/o date restriction as slow as 4:58 mins. and as fast as < 5 seconds. This may depend on what else the process is doing (causing the CPU load being 100 % even without a requested report).
- Sometimes reports will never show results. At some point (observed between 2 and 25 minutes) the CPU load of the sidekiq process drops to ~0 % without the report being finished. I assume that the report generation was cancelled at this point for whatever reason.
- The first impression was that the reports are generated much faster without the background feature being enabled, but this may be misleading due to the CPU usage. If usage is ~0 % performance might be very similar for background reports on and off.

Here are some notes of three dedicated reports which I have tested. 

| Report type | Background reports activated | **admin** user (**w/o** date restriction) | **admin** user (last 30 days) | **super admin** user (**w/o** date restriction) | **super admin** user (**with** date restriction) | 
| - | - | - | - | - | - |
| Orders And Distributors | yes | :heavy_check_mark: (< 5 s to 4:58 min.) | :heavy_check_mark: (0:21 min.) | :x: No results, no email after > 25 minutes | :heavy_check_mark: (1:47 min.) |
| Payments By Type | yes | :heavy_check_mark: (0:24 min.) | :heavy_check_mark: (0:09 min.) | :heavy_check_mark: ( 0:44, 0:27 min.) | :heavy_check_mark: (< 5 s) |
| Order Cycle Supplier Totals | yes | :heavy_check_mark: (0:10 min.) | :heavy_check_mark: (< 5 s) | :question: 1. No results, no email after > 9 min. 2. Results after 1:55 min. | :heavy_check_mark: (0:11 min.) |

| Report type | Background reports activated | **admin** user (**w/o** date restriction) | **admin** user (last 30 days) | **super admin** user (**w/o** date restriction) | **super admin** user (**with** date restriction) | 
| - | - | - | - | - | - |
| Orders And Distributors | no | :heavy_check_mark: (< 5 s) | :heavy_check_mark: (< 5 s) | :x: Error 504 Timeout (120 s) | :heavy_check_mark: (< 5 s) |
| Payments By Type | no | :heavy_check_mark: (< 5 s) | :heavy_check_mark: (< 5 s) | :heavy_check_mark: (0:26 min.) | :heavy_check_mark: (< 5 s) |
| Order Cycle Supplier Totals | no | :heavy_check_mark: (< 5 s) | :heavy_check_mark: (< 5 s) | :heavy_check_mark: (1:55 min.) | :heavy_check_mark: (< 5 s) |

## Next steps
I think we should
- Try to find out why CPU usage is ~100 % for 30 minutes after deployment/restarting Sidekiq.
- Try to find out why sometimes the report generation is cancelled without providing results.

What do you think?

I'm personally not convinced that this is ready for roll out because I can't tell how severe the issues above will be in production.

**Comment by mkllnk** [comment]
Thanks a lot for testing this thoroughly, Konrad. I think that slower reports will be a trade-off for a faster and not-crashing frontend. We can't run big reports within the request without risking the server crashing or slowing other users down. But I noticed a couple of things that we can do to improve the speed:

- [ ] Disable retries for reports. If a report fails, it's currently run again and again. That's especially bad if a report crashes after a long time computing.
- [ ] Provide error feedback to the user when a report fails.
- [ ] Store report files on the local disk. That is faster than uploading to AWS and storage space should be limited because the files are deleted after a week anyway.

We also discussed another task before rolling this out:

- [ ] Monitor server memory, ideally per process, to observe effects of background reports. #10997

I think I should create issues for the above and we should this back on the agenda at the next delivery circle meeting. Do you agree?

Oh, and last but not least, do you think this issue here, labelled "[Background reports] Internal server errors 500 (snail) on report generation" can be closed? Your test looks like there are no regressions except slower responses and one intermittent failure.

**Comment by drummer83** [comment]
Yes, @mkllnk, we can close this one here and I agree to discussing this in Delivery Meeting again.
Your proposed improvements sound great. Would be cool if you could create the issues for those. 
Thanks!

**Comment by mkllnk** [comment]
I created issues.
