### ISSUE TITLE
[Background reports toggle] background_reports breaks PDF and XLSX file download 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10492]
## Description

Please note:
Users should not be experiencing this, as the toggle should not be activated in prod.

Concerns all reports: Downloaded PDF and XLSX files are empty EDIT: if `background_reports` is enabled.

~~This is a regression, it was working till recently, [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/10256) for example.~~

## Expected Behavior

Downloaded PDF and XLSX files should contain the same results as those resulting from the query.

## Actual Behaviour

Downloaded PDF and XLSX files are empty.

## Steps to Reproduce

- enable `background_reports`

1. Visit `/admin/reports/sales_tax` or any other report.
2. Generate results by choosing the appropriate search parameters
3. Download the results as PDF of XLSX
4. Notice the empty files

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/221873235-be665634-5726-4494-aeee-06e996f78fc7.png)

## Workaround

Download a csv and open it as XLSX or convert it to pdf. Use the "print results" button 

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.2.36 Chilli-lime Cricket
* Browser name and version: Firefox 110
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by jibees** [comment]
Whooops. That's a regression indeed. Will take a look.

**Comment by filipefurtad0** [comment]
Thanks - I'll work on #10478  to go support it.

**Comment by jibees** [comment]
Locally it works on `master` and `v4.2.36`. So I suspect something around background generation (it did not take to much time on my machine)

**Comment by filipefurtad0** [comment]
Yep - that's it, also on staging:
- with `background_reports` enabled -> no pdf xlsx generation
- with `background_reports` disabled -> all as before
Great finding @jibees !

**Comment by jibees** [comment]
Ok, so, I've tested PDF export on `admin/reports/sales_tax` with `background_reports` feature toggle activated on version:
 - `master`: ❌, file is downloaded but not valid
 - `v4.3.36`: ❌, file is downloaded but not valid
 - `v4.2.35`: ❌, file is downloaded but not valid
 - `v4.2.34`: ❌, file is downloaded but not valid
 - `v4.2.33`: ❌, but for a different reason (file is not dowloaded at all):
```
15:17:29 rails.1   | [wicked_pdf]: ["/Users/jibees/.rbenv/versions/3.0.3/bin/wkhtmltopdf", "--page-size", "A4", "file:////var/folders/hg/xfh7y34d6fjbgp3356n98d3r0000gn/T/wicked_pdf20230228-13030-qea8ny.html", "/var/folders/hg/xfh7y34d6fjbgp3356n98d3r0000gn/T/wicked_pdf_generated_file20230228-13030-4yhnhn.pdf"]
15:17:31 rails.1   | Not notifying due to an invalid api_key
15:17:31 rails.1   | /Users/jibees/dev/openfoodnetwork/app/jobs/report_job.rb:22:in `write': "\\xFE" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
15:17:31 rails.1   |    from /Users/jibees/dev/openfoodnetwork/app/jobs/report_job.rb:22:in `write'
15:17:31 rails.1   |    from /Users/jibees/dev/openfoodnetwork/app/jobs/report_job.rb:8:in `perform'
15:17:31 rails.1   |    from /Users/jibees/dev/openfoodnetwork/app/services/job_processor.rb:14:in `block (2 levels) in perform_forked'
.....
15:19:40 rails.1   | WARNING: V8 isolate was forked, it can not be disposed and memory will not be reclaimed till the Ruby process exits.
15:19:40 rails.1   | It is VERY likely your process will hang.
15:19:40 rails.1   | If you wish to use v8 in forked environment please ensure the platform is initialized with:
15:19:40 rails.1   | MiniRacer::Platform.set_flags! :single_threaded
``` 
 - `v4.2.32`: ❌, same as `v4.2.33`
 - `v4.2.31`: ❌, same as `v4.2.32`
 -  `v4.2.30`: code wasn't present.
 
 
 So, I must admit I'm a bit confused. As far as I know, it doesn't work on my machine.

**Comment by jibees** [comment]
> PS: In that case, I'm not sure it is really a regression; I've removed the label. In any case, I think we need test coverge on downloading files on reports.

I agree and I agree. ☝️

**Comment by jibees** [comment]
@filipefurtad0 I've open a small PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/10493

I'd be happy if you could confirm (I mean, before code reviewing it) if this solves the original issue. At least, works on my machine, but I'm not that confident.
