### ISSUE TITLE
Allow report summaries in JSON (API) output

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#10508]
## What is the problem we are solving 
For an integration, we require report summary lines in JSON format.

## Success factors = expected outcome 
Report summary lines (eg totals) can be found in report output from the v0 reports API, and differentiated from the other raw data.

## Useful information for inception
Example desired output. The 'summary' line should be optional and disabled by default to avoid causing issues with current integrations.
```
[{
    "data": [{
        "producer": "Fenech Farm",
        "product": "Pastured Free Range Eggs",
        "variant": "700g eggs (1 dozen 700g)",
        "quantity": 25,
        "total_units": "25.0",
        "curr_cost_per_unit": "8.0",
        "total_cost": "200.0",
        "sku": "",
        "producer_charges_sales_tax?": false,
        "product_tax_category": null
    }, {
        "report_row_type": "summary",
        "total": 234
    }]
}]
```

It seems better to separate data and summaries in the JSON structure, but this is not possible at this point, because the report framework only supports tabular output.

## Link to the "Product Development - Backlog" item in Discourse
n/a

**Comment by jibees** [comment]
Just wondering the use case of this one. 

To my understanding (I might be wrong...) summary row are more here for presentational concerns: it has all its place if we display as it in browser. Requesting reports via API and having some json is more about data (the json is rarely printed like this): what about managing the presentational aspects (the summary row then) _after_ retrieving all data and inside the client (that request the API)? 
Is the role of the API to manage summary row?

**Comment by lin-d-hop** [comment]
This is a quick and dirty fix and thanks for @dacook for the work on it! We agree this solution is not perfect, but I think for quick v0 hack to make this data available, it is a fair solution :) 

@jibees the use case is that there is data in the summary rows in some reports that can't be accessed in any other way via the API. eg Delivery notes.
