### ISSUE TITLE
[Products] Column 'Display as' can't be hidden in the table

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10500]
## Description

Every column in the product list can be shown or hidden using the 'columns' dropdown menu - except for 'display as'. This column is not listed in the dropdown. This applies to the old as well as the new columns dropdown menu (see screenshots).

## Expected Behavior

All the columns should be available for hiding and showing.

## Actual Behaviour

Column 'display as' is missing in the dropdown menu.

## Steps to Reproduce

1. Open the product list /admin/products.
2. Look at the columns dropdown menu.

## Animated Gif/Screenshot

Old dropdown:
![image](https://user-images.githubusercontent.com/1790176/222248939-c8a2567d-ee70-4468-a4ad-42bd2f307e48.png)

New dropdown:
![image](https://user-images.githubusercontent.com/1790176/222251858-0b3e74bc-434c-4af2-a4a9-98d6f824fae5.png)

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: v4.2.36
* Browser name and version: Firefox 110.0.1 (64-bit)
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by vviekk** [comment]
Seems like `Display as` is mapped to the same check box as  `Unit` .

![image](https://user-images.githubusercontent.com/91144693/223666382-7c5c4159-6a06-4a4b-bab6-bf0a3a07ecc1.png)

![image](https://user-images.githubusercontent.com/91144693/223666012-df9967ec-d3d0-4937-b8fb-1988b3b210cb.png)

**Comment by drummer83** [comment]
Ahhh, thanks @vviekk! That's a great finding. 
So the question is if we really need or want it that way. It caused some confusion to me obviously. Also I see no compelling reason to link the two. Even when looking at variants instead of products:

![image](https://user-images.githubusercontent.com/1790176/223706954-cc44b626-62b0-406b-88b2-3ff788769748.png)

Let's hear what @openfoodfoundation/train-drivers-product-owners think about this.

My proposal would be
A: to list both columns independently in the dropdown. And if there are reasons to keep the link we could maybe 
B: add the 'display as' in the name of the columns dropdown:
![image](https://user-images.githubusercontent.com/1790176/223707436-6b1a5206-0ca8-4c32-b297-2e94d6903ab3.png)

**Comment by vviekk** [comment]
Also Just another side note: (perhaps this was deliberately omitted)
We don't have the translate key for 'display_as' as we have for other columns like here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/62d0ce290a53ba616e9894a14c30e32de0f616a7/app/components/products_table_component.rb#L7-L22


There are no keys: 
* `admin.products_page.columns_selector.display_as`
* `admin.products_page.columns.display_as`

https://github.com/openfoodfoundation/openfoodnetwork/blob/62d0ce290a53ba616e9894a14c30e32de0f616a7/config/locales/en.yml#L489-L513

But there are other keys like ` admin.products.index.display_as`.

**Comment by RachL** [comment]
I think this issue will be closed with the new design as "display as" won't be a separate column anymore, closing!
