### ISSUE TITLE
[Split checkout] Bug preventing users from ordering 'Checkout is not possible due to absence of shipping options' 

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#10553]
## Description

UK users on split checkout roll-out report being unable to checkout due to shipping methods not being displayed. The shopfronts reported all had multiple active & valid shipping methods (and had them selected on order cycles where shopfront was a producer hub with complex order cycle options).

Shopfronts for which users reported issues: 

- [Producer](https://openfoodnetwork.org.uk/sole-of-discretion/shop#/shop) [id: 200275] 
- [Producer hub](https://openfoodnetwork.org.uk/tamar-valley-food-hubs/shop) [id: 160]
- [Producer hub](https://openfoodnetwork.org.uk/inmybackyard/shop#/shop) [id: 201505]

Example affected order id: R881774504
**This user has a saved billing and shipping address.**

## Expected Behavior

On screen one ('your details') of the split checkout process, user should see available shipping methods for their selected order cycle and be able to select and save a  method to proceed to next screen.

## Actual Behaviour

User is not shown any shipping methods and is therefore prevented from completing checkout as orders cannot be placed without a shipping method. An error banner 'Checkout is not possible due to absence of shipping options. Please contact the shop owner' is displayed when the next button is clicked.

## Steps to Reproduce

I have not been able to reproduce this bug myself yet. Split checkout feature was turned on for 33% of users, and was flagged by a handful of users from larger enterprises. Nevertheless:
1. Access openfoodnetwork.org.uk as user with split checkout feature turned on
2. Go to one of confirmed affected hubs (see above), add item to basket, click checkout
3. On the first page of the split checkout journey, see that shipping methods are not listed and error is triggered when 'next' button is pressed.

## Animated Gif/Screenshot

User screenshots:
![image001](https://user-images.githubusercontent.com/100226210/224708936-aa6ed95f-190d-4a36-b59e-2ace7f5e042b.jpg)
![Screenshot_20230311_180425_com android chrome](https://user-images.githubusercontent.com/100226210/224708963-7a0efeb7-b2f6-4a92-9f1a-8198d19ebc2b.jpg)
![Screenshot_20230312_192936_Chrome](https://user-images.githubusercontent.com/100226210/224708980-7aa6c743-a542-4cce-8f22-3b12840205bd.jpg)

## Workaround

Turn off split checkout for all UK users

## Your Environment

* Version used: Split checkout feature toggle
* Browser name and version: Various browsers 
* Operating System and version (desktop or mobile): Mobile & desktop

**Comment by BethanOFN** [comment]
Closing this issue as resolved - split checkout only displays shipping methods with a **matching** category (e.g. refrigerated if order contains refrigerated items), whereas legacy doesn't filter shipping methods. Hubs have not needed to set their shipping categories to match their products before, so many orders are failing when going through split checkout and encountering the filtered shipping methods for the first time. Workaround: have to edit shipping methods to check _all relevant shipping categories_, i.e. if a shipping method works for refrigerated and frozen products, then default, refrigerated and frozen must be checked.

**Comment by audez** [comment]
Same in FR [https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1678879419904139](url)
