### ISSUE TITLE
Remove OFN header / banner in order confirmation emails

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#10556]

**Comment by lin-d-hop** [comment]
Clearly the issue would benefit from more spec. But the designs are in other issues right? If it feels clear to you @jibees I don't see a problem in you picking it up.

**Comment by jibees** [comment]
It feels clear to me: once the user has activate its `Hide OFN navigation` preference, we should hide OFN header/banner in order confirmation emails (as we do for shops, cart, checkout, ... pages).

**Comment by kirstenalarsen** [comment]
I think this is great - thanks @jibees ! In initial discussions we had considered just doing it for everyone (not limiting to white label), but I think it is good to introduce it like this and then if people want it more broadly we could take it out of the 'switch'. thanks!
