### ISSUE TITLE
SO - Create an order cycle schedule

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1055]
**As a shop owner I want to create an order cycle schedule**

Go into admin section. 
Go to the orders section.
Click on the "Add Schedule" button.
Result: the add schedule screen modal displays.

Then:
- Add the name of the schedule
- Select the order cycles to go in the schedule (spike how hard it would be to use a jquery picker to add order cycles from one column to another).
- If you hit the cancel button and you confirm you want to cancel then it doesn't save it and closes the modal.
- If you hit the create button then the schedule is added to the database and the modal closes and the name of the schedule appears in the schedule column against all the selected order cycles.

See #1059 for an idea of the interface
- [x] Create Schedule model (1.5 hrs)
- [x] Add Schedules to Order Cycles interface (2 hrs)
- [x] Build modal for adding/editing Schedules (4 hrs)

**Comment by sstead** [comment]
All looks good. Can create, edit, add/remove OCs to the schedule by dragging, cancel, see in columns.
![image](https://cloud.githubusercontent.com/assets/10843056/20735770/60430508-b6f6-11e6-9737-b3c55816335c.png)

**Comment by sstead** [comment]
1 Problem- the Available column only lists OC that are currently dispalyed in the OC table. This includes past, present and future/draft OCs. If they are older and have been archived (hidden), I can't select them. But if I click 'show 30 more days' to reveal them, then I can see them in the Available column. The questions is, which OCs should show in the Avaialble column? All? I do like that they're listed in the same way as they appear in the table (chronologically). I noticed that if I drag a OC back from the selected column I can place it anywhere in the list- order is not enforced, the user can rearrange- is this a good thing? Or is it logical to keep the chronological order consistent?

**Comment by sstead** [comment]
Can we make it more obvious that you need to have the schedule column showing if you're using schedules? Maybe by default if you have any schedules, you it gets saved as a default visible column?
![image](https://cloud.githubusercontent.com/assets/10843056/20736473/dbcd06de-b6fa-11e6-8254-f4da66e3b0b6.png)

**Comment by sstead** [comment]
I can currently add order cycles with different coordinators to the same schedule- this is not correct I don't think.

**Comment by sstead** [comment]
Fixed:
- I can currently add order cycles with different coordinators to the same schedule.
- When subs is enabled the schedule column is added by default to the OC interface page
