### ISSUE TITLE
Allow 'hide' of OFN main navigation

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#10557]
Please use Clockify Project - #10555 Basic ‘White Label’ Feature Set for Shopfronts

[#10555 Basic ‘White Label’ Feature Set for Shopfronts](https://app.clockify.me/projects/641042313549b70568b019dd/edit)

## Description
** As an enterprise
** In page Enterprise Settings
** I want to be able to do:
- Click on new tab for White Label
- Add White Label tab to enterprise settings.
- Add option to hide OFN navigation.

This should hide OFN navigation when on the shop page, cart, during checkout and order confirmation when the order’s distributor has this option on.

## Acceptance Criteria & Tests
1. Login to admin as a shop / hub user
2. Go to Enterprise Settings
3. There should be a new Tab called White Label
4. When I go into it I have an option to 'Hide OFN Navigation'
5. I select and save

Now my shop, view/edit cart, checkout and order confirmation page should have plain white top of page, not showing OFN navigation menu (i.e. No Shops, Map, Producers, Learn etc) - as per '1.' in image below 

![image](https://user-images.githubusercontent.com/2911176/224957813-61e3a603-eee7-4abb-8053-661d9bfa4e75.png)

**Comment by jibees** [comment]
Should we show the navigation on checkout page if the preference is activated (as well on shop and cart page)?

**Comment by jibees** [comment]
> during checkout and order confirmation

Sorry, I didn't read this part ;)
