### ISSUE TITLE
Allow 'hide' of Groups tab in Shop Navigation

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#10560]
Please use Clockify Project - #10555  Basic ‘White Label’ Feature Set for Shopfronts

## Description
** As an enterprise
** In page Enterprise Settings, tab White Label
** I want to be able to do:
- hide the 'Groups' tab if it appears (i.e. if the enterprise is in a Group)
NB. This perhaps should be decoupled from the other settings i.e. Enterprises should be able to just do this without also using the 'hide main nav' and 'custom logo'

## Acceptance Criteria & Tests
1. Login to OFN as an enterprise 
2. Make sure the Enterprise is in a Group
3. Check the Shop page and see that Groups tab appears
4. Go to Enterprise Settings / White Label
5. Select 'Hide Groups Tab' (possible tooltip - Groups tab is activated when the Enterprise is in a Group. This will override this and hide it.) 
7. Reload Shop page and see that Groups tab is not there 

<img width="984" alt="image" src="https://user-images.githubusercontent.com/2911176/225795005-2d4eeddf-6cce-44f9-aec1-fc6a3f59b22b.png">

**Comment by kirstenalarsen** [comment]
@jibees re. my comment above about "perhaps should be decoupled from the other settings i.e. Enterprises should be able to just do this without also using the 'hide main nav' and 'custom logo'" . . I think that might actually make sense i.e. in the White Label tab we actually end up with a couple of different checkboxes, that operate independently, rather than nesting all the things behind one?

So 'Hide Groups tab' is a separate checkbox / function from 'Hide OFN Navigation'

**Comment by jibees** [comment]
Yes, this is exactly what I've done here: https://github.com/openfoodfoundation/openfoodnetwork/pull/10750
