### ISSUE TITLE
SO - Filter order cycles by schedule or by date range

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1056]
**As a shop owner I want to filter order cycles by schedule**

This story includes the addition of the schedules column on the order cycles table, and then the ability to filter the list by schedule. Can only show one schedule's order cycles at a time, won't be able to filter by multiple schedules.

This also includes changing the page to Angular.

![img_0567](https://cloud.githubusercontent.com/assets/2067859/16257370/7adef6ee-389b-11e6-8e90-c6dc44bb3a88.JPG)
- [x] Change page to angular (12 hrs)
- [x] Add shop filters to the page (6 hrs)
- [x] Add schedule filters to the page (3 hrs)

**Comment by daniellemoorhead** [comment]
This story includes the addition of the schedules column on the order cycles table, and then the ability to filter the list by date range or by schedule. Can only show one schedule's order cycles at a time, won't be able to filter by multiple schedules.

This also includes changing the page to Angular.

**Comment by daniellemoorhead** [comment]
@oeoeaio can you please add the photo of the page mockup you did for this (whiteboard image).

**Comment by sstead** [comment]
Yes - is angular
Yes - can filter by shop
Yes - can filter by schedule
Together the filters are "AND" filters (only show results meeting both criteria)
The results of the filter also hide old OCs, with the option of revealing them.

**Comment by sstead** [comment]
Done
