### ISSUE TITLE
SO - Select multiple order cycles and add them to a schedule

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1057]
**As a shop owner I want to select multiple order cycles and add them to a schedule**
- [ ] Add select boxes next to each order cycle (1 hr)
- [ ] Build function to add pop up a modal with schedule selection (3 hrs)
- [ ] Add actions dropdown, with "Add to schedule" (1 hr)

**Comment by daniellemoorhead** [comment]
Add them to an existing schedule, not create a new schedule at the same time?

**Comment by oeoeaio** [comment]
I don't think we need this, so I'm closing now. If it comes out of user testing that this is a requirement, then we can open this one up again.
