### ISSUE TITLE
SO - Edit or delete an order cycle schedule

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1059]
**As a shop owner I want to edit or delete an order cycle schedule**

Go to the order cycles screen.
Click on the Schedule name in the table (if it's not visible then you filter/search for it).
Result: the schedule modal displays in edit mode (same as the add schedule modal).

**EDIT**
- User can edit the name and the order cycles within the schedule, and then click on update (changed label).
- Schedule is updated in database.

**DELETE**
- User can also delete the schedule by clicking on the delete button.
- If no standing orders are in place for the schedule then it is deleted once the user confirms the action.
- If there are standing orders in place for the schedule then an error message displays saying you can't delete this because there are standing orders attached. The user then hits OK.

![img_0565](https://cloud.githubusercontent.com/assets/2067859/16256969/ded80468-3898-11e6-9736-fb53c803601c.JPG)

**Comment by nanoharsha** [comment]
@daniellemoorhead @oeoeaio does the above issue and work being done to fix it, also address the below issue #768  raised by @myriamboure .

Cheers.

**Comment by myriamboure** [comment]
I don't think so @nanoharsha I answered in the other thread :-) I was talking about any order cycle, here is a specific feature for standing orders. The other issue was that if you create a test order cycle and just go on it on the front end and add an item to your basket to test, the system create an uncomplete order with the status "cart", and then you can't delete the order cycle... I think it's different.

**Comment by sstead** [comment]
Search for schedule not yet working...
![image](https://cloud.githubusercontent.com/assets/10843056/20735910/6327e5a8-b6f7-11e6-9b3f-59a1bf1b8856.png)

**Comment by sstead** [comment]
Yes - can change name and this saves in all places
Yes - Can delete if no standing orders, after clicking confirm
Delete - If has associated standing order can't delete. When you try to delete I get a 'are you sure' message box. If you click yes, nothing happens and the Schedule hasn't been deleted.

**Comment by sstead** [comment]
This is outstanding, all else is working.
Delete - If has associated standing order can't delete. When you try to delete I get a 'are you sure' message box. If you click yes, nothing happens and the Schedule hasn't been deleted. Would be good to get a dialogue message saying 'sorry you can't delete this schedule because it has associated standing orders'.

**Comment by sstead** [comment]
This has been fixed, there's clear messaging saying that you can't delete a schedule with subs assigned to it.

![image](https://user-images.githubusercontent.com/10843056/42672574-23575c04-86aa-11e8-9374-b455e7f47ae5.png)
