### ISSUE TITLE
Deployment failed on `master`

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#10593]
_Originally posted by @jibees in https://github.com/openfoodfoundation/openfoodnetwork/issues/10568#issuecomment-1477801447_

Context: 
 - Deployment of `master`: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/fr-staging/deploys/969
  - Passed! ✅ 
  - But I got a 500 on page `/`:
<img width="1072" alt="Capture d’écran 2023-03-21 à 14 11 49" src="https://user-images.githubusercontent.com/296452/226616338-1e4aa696-d310-4508-ac49-22f85e865076.png">

 - I checked bugsnag: https://app.bugsnag.com/open-food-france/coopcircuits/errors/6419ac4014b1a40009d5c567
```
gems/webpacker-5.4.4/lib/webpacker/manifest.rb:79:in `handle_missing_entry': Webpacker can't find logo-white-notext.png in /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-03-21-130502/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
 (ActionView::Template::Error)
    from gems/webpacker-5.4.4/lib/webpacker/manifest.rb:49:in `lookup!'
    from gems/webpacker-5.4.4/lib/webpacker/helper.rb:193:in `rescue in resolve_path_to_image'
    from gems/webpacker-5.4.4/lib/webpacker/helper.rb:189:in `resolve_path_to_image'
    from config/initializers/webpack.rb:6:in `image_pack_path'
    from app/views/home/_tagline.html.haml:5:in `_app_views_home__tagline_html_haml__2572215756437575251_120080'
```

 - Logged on server, directory `packs` doesn't exist under `/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-03-21-130502/public`
 ```
ls: cannot access '/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-03-21-130502/public/packs': No such file or directory
```
 - Sounds like same as: https://github.com/rails/webpacker/issues/1759 and/or https://github.com/rails/webpacker/issues/1212

**Comment by dacook** [comment]
I don't really understand why this was necessary. It sounds like this issue you mentioned: https://github.com/rails/webpacker/issues/1212, but that refers to a change made a long time ago in webpacker v3.

Another possible cause is that the yarn installation on staging servers was changed on 15th May (https://github.com/openfoodfoundation/ofn-install/issues/865#issuecomment-1469260022). Yarn is now installed with Nodenv, and might have been a slightly different version.

In any case, I'm confused. I'd like to see dev-related dependencies moved out of production if they're not necessary.
But I'm glad you fixed it for now 👍
