### ISSUE TITLE
Missing translation: edit shipping category

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10596]
## Description

The page header on on the `/admin/shipping_categories/<shipping_category_id>/edit` is not translatable.

## Expected Behavior

Page should be fully translatable.

## Actual Behaviour

Page header is not translated

## Steps to Reproduce

1. Login as superadmin
2. Select a language other than EN
3. Visit `/admin/shipping_categories/<shipping_category_id>/edit` or edit an existing shipping category
4. See the missing translation

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/d3cc46cd-8e07-4b78-be6f-c30434afe045)

## Workaround

See the message in EN.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: Release - v4.2.39
* Browser name and version: Firefox 110
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

The file `/app/views/spree/admin/shipping_categories/edit.html.haml` considers translation, but the entry is missing on the en.yml file: adding `editing_shipping_category: "Editing Shipping Category"` to line 3770 should fix this.

**Comment by jibees** [comment]
OFN an i18n: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-(i18n)

**Comment by emiliecm** [comment]
I am working on this bug, and have successfully fixed it on my local copy. Any suggestion for how to create a unit test? I am not super familiar with i18n.
