### ISSUE TITLE
SO - Set up a standing order for a customer

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1060]
**As a shop owner I want to set up a standing order for a customer**

Go into admin section. 
Go to the orders section.
Click on the "Standing Orders" tab.
Result: Display the new standing orders page

Then:
- Click on the Add Standing Order button
- Fill in the following details: Customer; Schedule; Shipping Method; Payment Method.
- Select the schedule, set the duration (ongoing or an end date), and select the first order cycle in the standing order.

Then on same screen:
- Select products for the standing order: Choose from the variant drop down, select quantity and then hit the "Add" button.
- User can delete a product from the list using the delete button.
- Indicative calculated total price displays as products are added to the standing order
- User can click on the "?" button to understand why it's indicative.

Then to finish:
- Click cancel button and confirm action if you don't want to save it.
- Click create button to save it, which creates all the orders for that customer for each order cycle included in the standing order (bulk generation tool).
- User is taken back to the standing orders page, the new order is displayed within the list (somewhere).

**Comment by sstead** [comment]
Yes - there's a new SO tab, with +Create New SO button
Yes- I can add customer (dropdown of all customers on my list), I can select a schedule from those available, i can select paymnet/shipping method from list of coordinator's.
Yes - I can select dates
No - I can't select the first OC.
Address - No autofill from customer list. No 'same as billing' checkbox
Navigation buttons - no BACK button from the Review and Save screen- although i suppose we don't really need it, as you can edit anything there, but why not allow both?
![image](https://cloud.githubusercontent.com/assets/10843056/20738241/dcd818f6-b705-11e6-8266-a353de6387a5.png)
![image](https://cloud.githubusercontent.com/assets/10843056/20738246/e1ac8588-b705-11e6-8f85-c08a403bee95.png)

**Comment by sstead** [comment]
I could search for and add the watermelon item to the SO. But it wouldn't save. This may be because it's not in any of the outgoing sections of the schedule's OCs.
![image](https://cloud.githubusercontent.com/assets/10843056/20738372/b6370008-b706-11e6-9275-264a0593b4ee.png)

**Comment by sstead** [comment]
Enterprise can't make a SO without first making Schedule - make clearer.

![image](https://cloud.githubusercontent.com/assets/10843056/20738715/31750592-b709-11e6-90e7-c822d3dad9cf.png)

**Comment by sstead** [comment]
The majority of this is fixed/done. There's still some confusion in regards to which products can/can't be added to a sub, but that's covered here - https://github.com/openfoodfoundation/openfoodnetwork/issues/2243
