### ISSUE TITLE
SO - View all my standing orders

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1061]
**As a shop owner I want to view all my standing orders**

Go into admin section. 
Go to the orders section.
Click on the "Standing Orders" tab.
Result: Display the new standing orders page

Then:
- Filter by customer or by schedule (and possibly by item, but may be a bit tricky, we'll see).
- [x] Create Standing Order model (1 hr)
- [x] Build basic version of interface (11 hr)

**Comment by sstead** [comment]
Yes- page exists and you can filter by coordinator.
Yes- Is angular - with save column defaults.
Still some things to be done...
![image](https://cloud.githubusercontent.com/assets/10843056/20738348/89571226-b706-11e6-99f0-4093e6cb53e6.png)

**Comment by sstead** [comment]
![image](https://cloud.githubusercontent.com/assets/10843056/21171016/49650ebc-c21d-11e6-9c37-57b6acac773c.png)

**Comment by sstead** [comment]
![image](https://cloud.githubusercontent.com/assets/10843056/21171511/99b9aa64-c220-11e6-9da2-d6373cca61a1.png)

**Comment by sstead** [comment]
- Pricing are now showing in the Item column (fixed). They also calculate correctly.
- The 'closing in X days' message is now counting the correct number of days. (fixed)

Bugs:

Translations:
![image](https://user-images.githubusercontent.com/10843056/33110624-3cea8958-cf9d-11e7-82a7-dd9092e1df91.png)

This is outstanding:
![image](https://user-images.githubusercontent.com/10843056/33110641-5eb581b4-cf9d-11e7-9978-cc9130da432a.png)
