### ISSUE TITLE
Hide users with no completed orders from a hub's customers list

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10624]
## Description
**- As a:** enterprise user
**- On page:** `/admin/customers`
**- I want to be able to do:** Not see users who never completed an order at my shop /// At least one order must be completed to end up on the hub's customer's list.

## Acceptance Criteria & Tests

_Scenario 1 : As guest user_

1. Place an order for the first time at a shop
2. As a shop owner check the previous guest email is visible in the customer's list
3. Now with a different guest user, retry checkout but stop at step 2 or step 3 (it's important you fill step 1 and get to step 2)
4. As a shop owner check this new guest user is not listed as customer

_Scenario 2 : As a user with an account_

Same scenario than a guest user. Make sure it's the first time this user account is used for this shop (otherwise it will already be listed as a customer)

_Scenario 3 : cases of completed orders_

Check guest checkout and users with accounts are correctly added to the customer's list if they have completed at least 1 order.

_Scenario 4_ API

Check the API is handling the customer list in the same way.

**Comment by jibees** [comment]
Question arise when starting working on it... 

It appears that you can add customer to you shop via button `New Customer` on page `/admin/customers`:
<img width="761" alt="Capture d’écran 2023-04-04 à 11 46 15" src="https://user-images.githubusercontent.com/296452/229754981-252482d9-e995-41b6-880b-09270f29b41d.png">

By definition, this new customer does not have any (completed) order, and then can't be seen in this interface after creating it. 

What do you think?

**Comment by RachL** [comment]
@jibees nice spot! Then I guess we can't hide on the UI, we need to prevent adding automaticaly to the customer list people who never completed an order (was the case on legacy checkout). What do you think?

**Comment by RachL** [comment]
@jibees yes that's it

**Comment by jibees** [comment]
⚠️ Please, note that customer manually added via interface with only incomplete order should also be retrieved (ie. we cannot simply remove customer with only incomplete order)

**Comment by jibees** [comment]
I unassigned myself since I didn't find a valid solution.

**Comment by abdellani** [comment]
> Scenario 4 API

@RachL 

We have three endpoints that return the customers:
1. /admin/customers.json
2. /api/v0/customers
3. /api/v1/customers 

The first one is the endpoint used by the UI.

Do we need to change that behavior everywhere?

**Comment by jibees** [comment]
> Do we need to change that behavior everywhere?

As already discussed with @RachL , I'd say: yes!

**Comment by abdellani** [comment]
>Yes because, on legacy checkout no customer were created before the user click on "Place order now" button (after filling its information). Now we have 3 steps, we create a customer just after step 1 (which has an order in state cart).

This is not the case when the user uses 'login as a guest'.
In this case, we'll not have a new customer record. The order will be created without an associated `customer`. 

 
>Now we should retrieve:
>customer with complete order
>customer added manually via interface
>but not the customer with incomplete order

I couldn't find any attribute that tells explicitly if the customer was created manually from the dashboard or not.
Is this that correct?


I noticed the following things:
1. when a new customer is created manually from the admin dashboard, the `user_id` will be `nil`.
2. when a logged-in user (I tried an admin and a hub) creates an order from a shop front, the new customer will be created with `user_id = logged-in user.id`

I guess that it's correct to say that every customer created manually from the dashboard will have user_id = nil
but I'm not sure if it's safe to assume the opposite =>

Every customer with user_id = nil is a customer created manually 

Anyone can confirm?


-----
Potential  bug (to verify)

Steps to reproduce
1. go to the admin dashboard -> order -> new order
2. select distributor and order cycle
3. click on next
4. select a customer, C1 for example
5. Notice that the email and the addresses will be loaded
6. completed the missing data
7. click on update
8. Select another customer: C2 for example
9. Notice that the email and the addresses will be updated
10. click on update
11. The email and the addresses will be updated, but the customer id will not be replaced! the order will always refer to C1 on the database.
![image](https://user-images.githubusercontent.com/16113997/232677400-85402ed2-1321-47b4-b7d6-1c1e7c56ebe5.png)

**Comment by RachL** [comment]
> This is not the case when the user uses 'login as a guest'. 
In this case, we'll not have a new customer record. The order will be created without an associated customer.

@abdellani you are refering to legacy checkout? FYI I've tested this and when the user checkout as guest it does end up in the customer list of a shop on the UI. I think we should keep this behavior.

**Comment by abdellani** [comment]
> @abdellani you are refering to legacy checkout? 

No, I'm using the split checkout.

>FYI I've tested this and when the user checkout as guest it does end up in the customer list of a shop on the UI. I think we should keep this behavior.

I double-checked now. Yes, you're right.
I don't know what I missed on the last test (maybe I used the same email + name?).

**Comment by abdellani** [comment]
> Also, I don't know if it helps but maybe the way the issue is described leads to a certain solution but we can think of workarounds. The issue says "hide" but another way around instead of hiding is changing how we create the customer in the first place. It happens in step 1 currently because we need to save the details.

If I didn't miss anything, there's no difference between customers created manually and the others.
I'll need to check the code 

>  Perhaps we can save the details with another method, that avoids creating a customer at this stage and leave customer creation/update at order completion only? @abdellani

I'll check this option and comment later.

**Comment by filipefurtad0** [comment]
> Potential bug (to verify)

This is verified, indeed - that's a great catch @abdellani. I'm not very clear on the consequences, but I'll open an issue - I don't see a workaround, so I'd say it is an S2. 

BO orders take the first chosen customer, and the admin can neither notice nor correct this. We can see below, that the `email` in the order does not match the associated `customer_id`:

```

openfoodnetwork=> select email, customer_id from spree_orders where number = 'R228047701';
             email             | customer_id 
-------------------------------+-------------
 filipefurtado+treec@gmail.com |        8180
(1 row)

openfoodnetwork=> select email,id from customers where id = 8180;
              email              |  id  
---------------------------------+------
 filipefurtado+almondc@gmail.com | 8180
```

**Comment by filipefurtad0** [comment]
My two cents:

> Please, note that customer manually added via interface with only incomplete order should also be retrieved (ie. we cannot simply remove customer with only incomplete order

I agree: creating backoffice orders is a scenario in which we wish to retrieve the customers via 

> Perhaps we can save the details with another method, that avoids creating a customer at this stage and leave customer creation/update at order completion only?

It looks to me that this would be the ideal solution.

PS: Not entirely related, but perhaps good to keep in mind - In addition to `customers` we also have `shipments` being created before order completion on split-checkout. This is described [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/9168).

**Comment by RachL** [comment]
> we also have shipments being created before order completion on split-checkout

AFAIK this does not appear in the UI right? Does it appear on the API and does it contain personal data? If not, we can live with it I think.

**Comment by abdellani** [comment]
For the customer created manually, I think that the easiest solution is to add a flag on the customer model. 

For the existing record, I don't think that there is a possible way to distinguish between the customers created manually from the others (please correct me if I'm wrong).

**Comment by lin-d-hop** [comment]
Hi folks,
Let's just move forward with this.

For migrating old customers:
- If they have an order mark that they've ordered.
- If they don't have an order mark as manually created

For all new customers we can mark them correctly.

The longer this is outstanding with split checkout in place the worse the data corruption will be so let's just go for it.
