### ISSUE TITLE
SO - Store and edit a customer's preferred address

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1062]
**As a shop owner I want to store and edit a customer's preferred address**

### Issue 1: Frontend

The logic for auto-loading an address for an order is in CheckoutController#before_address.

Currently this logic is checking the current_user for for a bill_address and ship_address, however since we don't actually have an interface for assigning these, they are always nil. 

What happens instead is that the logic uses the current_order's email and OpenFoodNetwork::LastUsedAddress to find the address on the most recent order associated with that particular email. This is really supposed to be a fallback option, but instead is our only approach to loading address for existing customers.

It would be good to make this configurable by the customer both within the checkout (checkbox: "Save this as my default address") and in the account section.

### Issue 2: Back end

a) Some Enterprise users (Food Connect comes to mind) have expressed a desire to have more control over customer information from the backend, this includes updating account details such as name, contact number and delivery address details. 

b) we need some way of pulling up an appropriate address for customers as part of Standing Orders, and this will allow shops to set up an address for customers where one is known without the customer necessarily having to place an order first.

##### New fields on Customer

- [x] Add new optional fields to customer: bill_address_id and ship_address_id

- [x] Add a new field to customer: name (this is designed to be used in the backend)

##### Admin Customers Index
- [x] Add a new column for name, which is editable in situ

- [x] Add a new column for each address (bill, ship)
- [x] Column displays the start of the address, limited to ~15 characters
- [x] When the address is clicked, it can be edited in a modal (6h)

**Comment by bingxie** [comment]
- [ ] add bill_address_id and ship_address_id index and foreign key

**Comment by bingxie** [comment]
I moved those uncheck taskes to two separated issues #1130 and #1131 
I wanted to make it more easier to review and test.

**Comment by sstead** [comment]
![image](https://cloud.githubusercontent.com/assets/10843056/17916182/4bd3613e-69f4-11e6-8553-ab98b2545e28.png)

**Comment by sstead** [comment]
Regarding create an order... this is working well! yay!... a few nice to haves...
- It would be great if you could search for customers by their billing name, currently you can only search by email. People often have emails like bigapple65@gmail.com, so searching by email isn't always straightforward for the hub.
- Regarding the loading of customer details... Can we make it such that by default, the 'use billing address' box is selected, UNLESS the customer has different default shipping details to their billing details. If they have no default shipping address saved, we can also assume they want to 'use billing address'.
![image](https://cloud.githubusercontent.com/assets/10843056/19294283/c215cd5c-9076-11e6-92ee-ac81a9744b33.png)
