### ISSUE TITLE
[Deprecation] TimeWithZone#to_s(:short) is deprecated

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10625]
### What we should change and why (this is tech debt)

`DEPRECATION WARNING: TimeWithZone#to_s(:short) is deprecated. Please use TimeWithZone#to_fs(:short) instead. (called from block in report_order_cycle_options at <home>/openfoodnetwork/app/helpers/reports_helper.rb:6)`

### Context

I believe this was introduced after upgrading to Rails 7; noticed while working on #10507

**Comment by mkllnk** [comment]
Yes, there are a few deprecations in Rails 7. If we want to make sure that we don't have any deprecations left then we should set this value to `:raise`:

https://github.com/openfoodfoundation/openfoodnetwork/blob/6cfb86e578853561acd7d501bdb29dbe5e249f91/config/environments/test.rb#L50-L51

I should have done that before the upgrade to see if we had old deprecations before. :wink: 

Even better, in another project I added this code to list all current deprecations:

```rb
  ActiveSupport::Deprecation.behavior = ->(message, callstack, deprecation_horizon, gem_name) do
    allowed_warnings = []
    unless allowed_warnings.any? { |pattern| message.match(pattern) }
      ActiveSupport::Deprecation::DEFAULT_BEHAVIORS[:raise].call(message, callstack, deprecation_horizon, gem_name)
    end
  end
```

We would need to add our warnings to `allowed_warnings` and then they can then be removed one by one.
