### ISSUE TITLE
SO - Cancel a customer's standing order

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1063]
**As a shop owner I want to cancel a customer's standing order**

Go into admin section. 
Go to the orders section.
Click on the "Standing Orders" tab.
Result: Display the new standing orders page

Then:
- User clicks on the standing order to be cancelled.
- Modal displays that details what will happen if the user proceeds with the cancellation: all future orders for this standing orders will be cancelled and cannot be retrieved. You'll need to set this up again.

Then:
- Modal has 3 options to proceed: Cancel the cancellation; Pause the standing order instead; Cancel the order.
- If the user selects to cancel the cancellation, the modal disappears.
- If the user selects pause, the pause function kicks in (delivered in a separate issue), the modal disappears and a success message is displayed on top of the standing orders page. A pause icon displays against the standing order.
- If the user selects to cancel the order, the standing order is marked as cancelled in the database and all of the future orders in the standing order are deleted. Modal disappears and a success message is displayed on top of the standing orders page and the standing order is no longer in the list.
- [x] Add "cancelled_at" field to Standing Order model (2 hrs)
- [x] Add cancel action for Standing Orders (2 hrs)
- [x] Build cancel button and confirmation modal (3 hrs)
- [x] Link modal button with appropriate actions (1 hr)

**Comment by sstead** [comment]
Looks good... see sequence below...
![image](https://cloud.githubusercontent.com/assets/10843056/21166743/8b7f4fd2-c1fb-11e6-8a76-ead04cc91c9c.png)
![image](https://cloud.githubusercontent.com/assets/10843056/21166751/930bf9ee-c1fb-11e6-8d10-a5487b48ce69.png)
![image](https://cloud.githubusercontent.com/assets/10843056/21166754/9a878e86-c1fb-11e6-8f19-a69c2037456a.png)

**Comment by daniellemoorhead** [comment]
Remaining to do for this to be considered done:

Tell the user what is going to happen when they cancel a standing order where there's an open order cycle. That means that they have an order currently open, which means that they standing order alongside of the standing order, is going to be cancelled and removed.

**Comment by sstead** [comment]
Done- messaging to the user about repercussions of cancelling are clear.
![image](https://cloud.githubusercontent.com/assets/10843056/24275848/ab0a5a98-1086-11e7-8eae-aee317aabb57.png)

**Comment by sstead** [comment]
This looks complete.
