### ISSUE TITLE
SO - Pause a standing order

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1064]
**As a shop owner I want to pause a standing order**
- [x] Add "paused_at" field to Standing Order model (2 hrs)
- [x] Create action to "pause" a Standing Order (2 hrs)
- [x] Add pause button to interface (2 hrs)
- [x] Link up pause action to button, with appropriate messaging (2 hrs)

**Comment by sstead** [comment]
All looks good, see screenshots of sequence... 

![image](https://cloud.githubusercontent.com/assets/10843056/21165815/e1418af8-c1f5-11e6-8865-1a7511a4ca1a.png)

![image](https://cloud.githubusercontent.com/assets/10843056/21165837/00b47d64-c1f6-11e6-8793-3255701447a9.png)

![image](https://cloud.githubusercontent.com/assets/10843056/21165845/0b66b010-c1f6-11e6-8291-adff8f079c47.png)

![image](https://cloud.githubusercontent.com/assets/10843056/21165860/10d5f164-c1f6-11e6-878c-84235eb8084b.png)

Potential improvement- have a 'pause until' date so the admin can set and forget.

**Comment by daniellemoorhead** [comment]
Remaining work to be done:

Same as in #1063 - just need to add a message about how the current order will be cancelled and removed.

**Comment by sstead** [comment]
Same as in #1063 - just need to add a message about how the current order will be cancelled and removed...

This has been done... the user has two options a) keep current open order b) pause current order
![image](https://user-images.githubusercontent.com/10843056/33111637-41212cc4-cfa3-11e7-8bca-62cd21e6f0b9.png)

**Comment by sstead** [comment]
My testing shows that at the moment, if someone resumes a customers's subscription in the middle of an open OC they DO get an order for that OC.
