### ISSUE TITLE
SO - Edit a standing order

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1065]
**As a shop owner I want to edit a standing order**

All edits will be done from the standing order index page, with some pop out modals.

Can't edit the schedule or customer name.
Shipping, payment can be edited, this will be 2 new column in the table, with dropdown and select.
Can edit the start and end dates.
(column show/hide will be customisable)

Products - will be a new column (17 products) with a modal that pops out if you click.
Add product, Remove product, Change quantity
Has the product been modified from the initial standing order (item added, removed, or quantity changed) within an order? If so, the admin will need to manually decide what change to make to that order. For example if the initial standing order had 1 loaf of bread, but for one week in the future this was raised to 12 loaves. I'm now trying to change the standing order to be 3 loaves each week. The system will not decide if 3 or 12 is the correct quantity for the changed week, that decision needs to be made manually. The same goes for if the loaf was removed from a week's order.
- See modal image "cannot resolve order #R74813568

Orders will be a column, with editing modal
Table of Order Cycles, with items column.
Cancel button - orders go grey
An edit button takes you to the existing edit order interface.
- [x] Logic and action to update standing order products (and alert if there is a conflict) (6 hrs)
- [ ] Products Modal (6 hrs)
- [ ] Orders Modal (6 hrs)
- [ ] Editable form elements (shipping/payment methods, dates) (6 hrs)

**Comment by sstead** [comment]
Can edit items in the SO interface, but not other things. This works well, can add, change qty or remove items.
![image](https://cloud.githubusercontent.com/assets/10843056/20738909/bd3ebbd0-b70a-11e6-9f7e-d9dd67d52529.png)

Clicking the Edit Button opens a full edit page. Different to description above. Occurs on a new page, not a modal....
Yes - the customer name and schedule can't be edited.
Yes- can edit dates
Yes- can edit addresses
Can change products - limited testing as yet. Change to qty ok.

**Comment by sstead** [comment]
Bug relating to which items can and cannot be added to a SO...
![image](https://cloud.githubusercontent.com/assets/10843056/21171194/47b3a2ee-c21e-11e6-97a2-4b79ef65e24a.png)

**Comment by sstead** [comment]
This issue is mostly done, see this issue which covers the confusion around which items can/cannot be added to a sub https://github.com/openfoodfoundation/openfoodnetwork/issues/2243
