### ISSUE TITLE
Repeated customer entries on Customer reports

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10663]
## Description

Relates to https://github.com/openfoodfoundation/wishlist/issues/396#issuecomment-1497190767
A customer appears multiple times (probably according to each placed order?) on the customer reports.

## Expected Behavior

A customer should appear a single time on the customer reports.

## Actual Behaviour

A customer appears multiple times (probably according to each placed order?) on the customer reports.

## Steps to Reproduce

1. As a hub or superadmin, visit `admin/reports`
2. Generate both customer reports
3. Noticed there are several repeated entries, for the same customer

## Animated Gif/Screenshot

Mailing List Report
![image](https://user-images.githubusercontent.com/49817236/230066433-53792671-9030-4594-8662-6bd85d53e044.png)

Addresses Report
![image](https://user-images.githubusercontent.com/49817236/230063724-b5153ab8-b738-465c-a2b3-735524737262.png)

## Workaround

Filter out the repeated results when downloading as xlsx.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.3.0
* Browser name and version: Firefox 110
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by abdellani** [comment]
From what I can see, every order will have one row on the report.
If one customer makes three orders, he'll be listed three times.
I'll handle every report on a separate PR.

**Comment by drummer83** [comment]
Only partially fixed by #10665.
