### ISSUE TITLE
Release v4.3.2

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10671]
## Preparation on Thursday

- [x] Merge pull requests in the [Ready To Go] column
- [x] Include translations: `tx pull --force`
- [x] [Draft new release]. Look at previous [releases] for inspiration.
- [x] Notify [#instance-managers] of user-facing changes.

## Testing

- [x] [Find build] of the release commit and copy it below.
- [x] Move this issue to Test Ready.
- [x] Notify `@testers` in [#testing].
- [x] Test build: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/4323

## Finish on Tuesday

- [x] Publish and notify [#global-community] (this is automatically posted with a plugin)
- [x] Deploy the new release to all managed instances.
  <details><summary>Command line instructions</summary>
  <pre>
  cd ofn-install
  git pull
  ansible-playbook --limit all-prod --extra-vars "git_version=vx.y.z" playbooks/deploy.yml
  </pre>
  </details>
- [x] Notify [#instance-managers]:
  > @instance_managers The new release has been deployed.
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Ready To Go]: #zenhub
[Transifex pull request]: https://github.com/openfoodfoundation/openfoodnetwork/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+head%3Atransifex
[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A
[releases]: https://github.com/openfoodfoundation/openfoodnetwork/releases
[#instance-managers]: https://app.slack.com/client/T02G54U79/CG7NJ966B
[#testing]: https://openfoodnetwork.slack.com/app_redirect?channel=C02TZ6X00
[Find build]: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master
[#global-community]: https://app.slack.com/client/T02G54U79/C59ADD8F2

**Comment by filipefurtad0** [comment]
So [this issue - the red test case - is reproducible](https://github.com/openfoodfoundation/openfoodnetwork/pull/10640#issuecomment-1500059822) on this release as well, each time we use card x-3220 on subscriptions:

![image](https://user-images.githubusercontent.com/49817236/230616005-fec11a1d-b329-4c52-b908-645fe1b0bdb6.png)

Other cards like x-4242 or x-3184 don't trigger this error, so this looks like it is related to the 3DS2-authentication. In any case, this seems like it is generating a 404 error.

I'll open an issue, but I would not say it is a release blocker, we see now - I think - because:
- we monitor 404 errors
- Stripe has included this card in the[ list of test cards](https://stripe.com/docs/testing#three-ds-cards) (at least, I've only seen it now)

Issue coming up.

**Comment by RachL** [comment]
@filipefurtad0 I don't see anything related to stripe in this release. If it was introduced it was in another one so it's probably related to a previous release?

**Comment by filipefurtad0** [comment]
Agree, I don't think it was introduced here - but was checked now on this release/current master.

**Comment by RachL** [comment]
this is ready to go! https://docs.google.com/document/d/1DbVJNN2zvH_Mxq9LcZ2PHcu_NKRISqGsgbTWO0CDjXY/edit#

I've spotted something regarding Ts&cs and posted in #testing  It's not a release blocker (and probably already in production)
