### ISSUE TITLE
Order Cycle Coordinator can "clone" into an existing order cycle

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1067]
### Overview

Order Cycles can currently be "cloned", which creates a brand new OC with identical settings.

The proposed Standing Orders model requires that Order Cycles exist into the future, as far as the shop owner wants customers to be allowed to place/cancel and ultimately edit their future orders. 

In light of this, the capability to copy the list of products, fees and tags from between two existing order cycles becomes desirable.

### Tasks

 - [ ] Add a "Copy settings from..." button to the Order Cycles edit interface (potentially in the "Advanced Settings" section?), accessible only to coordinators
 - [ ] When this button is clicked, the user is asked to select an order cycle to copy settings from, and on confirmation runs a "copy" action to duplicate all properties duplicated by the "clone" action

**Comment by oeoeaio** [comment]
Duplicate of #1052

**Comment by daniellemoorhead** [comment]
@stveep this issue was closed and not worked on because it was a duplicate. So you're the only person to have worked on it.
