### ISSUE TITLE
[BUU] As an enterprise user, I want to know if I have products in my catalogue

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#10679]
## Context
This is the first issue that uses the new tech stack and new styling and components. We are going to set up the foundations of the new redesigned page, creating the first few elements (title, button, text for content), and assessing page loading. 
Since this issue covers error states as well, but there is a redesign of the illustrations in progress, we'll just include some placeholder content and [update once the imagery is ready](https://github.com/openfoodfoundation/openfoodnetwork/issues/10680).
We are not going to build the table itself in this card, but just the loading, empty and error states, and a placeholder state telling the user that they have products.

## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** know if I have products in my catalogue
**- So that:** I can decide if I need to create or import new ones or not

## Acceptance Criteria & Tests

**Scenario 1: Loading the page for the first time**
Given that I am logged in
When I land to `/admin/products`
Then the page starts loading my catalogue
And I see a loading indicator

Note: we will first build a version of the table loading that includes a simple loading indicator. Once we know more about how loading data is going to behave, we might potentially upgrade this to something more advanced.

Mockup > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?node-id=7%3A218&t=VkGk4jMtqb93Kksj-1

**Scenario 2: Successful loading with products**
Given that I have products in my catalogue
And I am in `/admin/products`
And the page is loading my catalogue
When the catalogue loads successfully
Then I see a message telling me that I have products in my catalogue

Mockup > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?node-id=7%3A631&t=VkGk4jMtqb93Kksj-1

**Scenario 3: Creating a new product from catalogue with products**
Given that I have products in my catalogue
And I am in `/admin/products`
And the page has loaded my catalogue successfully
When I click on the button to create a new product
Then I go to `/admin/products/new`

Note: this button should be shown only if I have products in my catalogue, not for empty and error states.

**Scenario 4: Successful loading without products**
Given that I don't have products
And I am in `/admin/products`
And the page is loading my catalogue
When the page loads my catalogue successfully
Then I see a message telling me that I don't have products in my catalogue

Mockup > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?node-id=7%3A227&t=VkGk4jMtqb93Kksj-1

**Scenario 5: Creating a new product from catalogue without products**
Given that I don't have products in my catalogue
And I am in `/admin/products`
And the page has loaded my (empty) catalogue successfully
When I click on the button to create a new product
Then I go to `/admin/products/new`

**Scenario 6: Importing products from catalogue without products**
Given that I don't have products in my catalogue
And I am in `/admin/products`
And the page has loaded my (empty) catalogue successfully
When I click on the button to import products
Then I go to `/admin/product_import`

**Scenario 7: Failed loading - no network**
Given that I don't have network connection
And I am in `/admin/products`
And the page is trying to load my catalogue
When the page stops trying to load my catalogue
Then I see a message telling me that I don't have network connection

Note: this scenario might be needed in case we have the ability to refresh the table without fully reloading the page. this scenario might not be necessary if we just go with full page load and no network browser behaviour.

Mockup > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?node-id=7%3A235&t=VkGk4jMtqb93Kksj-1

**Scenario 8: No network - refresh**
Given that I am in `/admin/products`
And the page has failed to load due to no network connection
When I click on the button to refresh
Then the page reloads my catalogue
And I see a loading indicator

Note: same as previous scenario.

**Scenario 9: Failed loading - catch'all**
Given that something is not working properly in the background
And I am in `/admin/products`
And the page is trying to load my catalogue
When the page stops trying to load my catalogue
Then I see a message informing me that something is not working.

Mockup > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?node-id=7%3A242&t=VkGk4jMtqb93Kksj-1

**Scenario 10: Catch'all - refresh**
Given that I am in `/admin/products`
And the page has failed to load my catalogue due to something not working properly in the background
When I click on the button to refresh
Then the page reloads
And I see a loading indicator

## Design specs

The whole set of screens is available here
https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?node-id=7%3A183&t=VkGk4jMtqb93Kksj-1

**New components and styles**

| Component | Example |
| --- | --- |
| Page title - H1 | ![Screenshot 2023-04-11 at 5 13 21 pm](https://user-images.githubusercontent.com/6696729/231098421-c7b162b9-b548-49b5-9b28-eb7d5d2d07e4.png) |
| Body text - regular | ![Screenshot 2023-04-11 at 5 14 32 pm](https://user-images.githubusercontent.com/6696729/231099078-7d79d8e3-163d-49c9-bde9-c025285ad810.png)
| Body text - semibold | ![Screenshot 2023-04-11 at 5 16 51 pm](https://user-images.githubusercontent.com/6696729/231099311-afe7abf4-5778-4ecd-afd5-330f57c8a991.png) |
| Primary button with left icon | ![Screenshot 2023-04-11 at 5 14 39 pm](https://user-images.githubusercontent.com/6696729/231099449-07b921bc-6f54-4102-bfe5-628cac5cedc5.png) |
| Secondary button with left icon | ![Screenshot 2023-04-11 at 5 14 53 pm](https://user-images.githubusercontent.com/6696729/231099528-7ed09ac9-5a19-468b-95e5-63fed125bc8d.png) |
| Page header - title only | ![Screenshot 2023-04-11 at 5 05 29 pm](https://user-images.githubusercontent.com/6696729/231096580-188a6ba6-3a8d-4760-a840-687014f19dd1.png) |
| Page header - with primary action  | ![Screenshot 2023-04-11 at 5 06 10 pm](https://user-images.githubusercontent.com/6696729/231096759-61d13c79-a03b-446a-8755-d971cc17761e.png) |
| Spinning loading indicator with message | ![Screenshot 2023-04-11 at 5 14 19 pm](https://user-images.githubusercontent.com/6696729/231099728-20438ab1-840d-4a5f-bcd9-2cffae70fc3b.png) |

**Comment by jibees** [comment]
Some screenshots:

![2023-06-13 17 49 50](https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/cd990662-ef3d-4dc3-a152-04f84bcf3cc4)
<img width="1420" alt="Capture d’écran 2023-06-13 à 17 48 10" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/b02dfea9-ea5d-4eaa-92c7-83cd58671405">

<img width="1516" alt="Capture d’écran 2023-06-13 à 17 50 53" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/de074bde-9e8b-4e04-95cf-8911106096a2">
<img width="1884" alt="Capture d’écran 2023-06-13 à 17 51 02" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/de8dd4e2-73ac-4e1e-a692-16fbc5f6551f">

**Comment by mariocarabotta** [comment]
@jibees a few questions:

1. have you created new button styles for this issue? If yes, I will give you a few notes for tweaks. Ideally we would start introducing new standardised button styles now (and keep track of them in the design system wiki). 
2. which icons library are you using? In figma I have used material icons, but I'm not particularly attached to it. I must say the ones that are in the current admin are not my favourite. They look bulky, but maybe it's just a sizing thing
3. which loading component are you using? I think it looks good in the screenshots, I just want to add it to the design system wiki for reference

Thank you, good work!

**Comment by jibees** [comment]
1.
> have you created new button styles for this issue?

Nop!

> Ideally we would start introducing new standardised button styles now (and keep track of them in the design system wiki).

Let's create it if needed!

2.
> which icons library are you using?

We use FontAwesome 3.2.1 as reading `app/webpacker/css/admin/plugins/font-awesome.scss`

3.
> which loading component are you using?

I created one, defined in `app/webpacker/css/admin_v3/components/spinner.scss`
