### ISSUE TITLE
Standing Orders: Restricting products available to use in standing orders

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1068]
How do we restrict which products are available to add to SOs ?
- Could only allow products available in all OCs for the given schedule to be added?
- Could have a specific list of products that are available to add to SOs?
  - Per schedule?
  - Per shop?

**Comment by sstead** [comment]
Rob suggests we just remove any restriction on which items can be added to a sub. See https://github.com/openfoodfoundation/openfoodnetwork/issues/2243
