### ISSUE TITLE
Property badges on profiles and filtering.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1069]
Testing notes for @RohanM 

**For a Producer:**
- Their full profile (viewed on the map) shows their Producer AND Product properties.
- Their producer listing mini profile shows their Producer AND Product Properties.
The above is true if the producer is a profile only, or a shopfront.  It's also true if they don't have any products added. (THIS SEEMS GOOD AND LOGICAL TO ME)

If the producer has a producer shopfront...
- The mini profile in shop listing does NOT show their properties (see suggestion below for hubs).
- The badges displayed in the actual shop only relate to the Product Properties that are active in the order cycle.  (THIS IS GOOD)

![image](https://cloud.githubusercontent.com/assets/10843056/16324793/0bebb806-39fb-11e6-9ab2-9a3f394fdb37.png)

**For Hubs**
- Their full profile (viewed on the map) doesn't show their Properties or Categories. (THIS COULD BE ADDED.
- Their shop listing mini profile shows their Categories, but NOT their PROPERTIES. (PROPERTIES SHOULD BE ADDED). The categories showing for them are all products available to them, not those that are active in their currently open order cycle(s)- I would suggest that an open shop shouldn't have badges for their whole product range, instead just for items that are in their current order cycle. Otherwise you think they have meat or organic items, but their shop doesn't have them this week :(. When the shop is closed you could list all. The same could be said for Properties.

![image](https://cloud.githubusercontent.com/assets/10843056/16324790/02ad87c4-39fb-11e6-9a23-fc7181d0a9d3.png)

**Groups Page**
It's functioning the same as above, and below for filters.

**Filters**
The filters on the Producer Directory and Shop Directory don't include properties.
![image](https://cloud.githubusercontent.com/assets/10843056/16324794/1264db2c-39fb-11e6-9fc0-5ffb79568ebd.png)

**Comment by RohanM** [comment]
After talking with @serenityhill, we've decided these issues aren't blockers. Branch pushed.
