### ISSUE TITLE
BO orders: changing customer does not update customer_id

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10717]
## Description

Spotted [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/10624#issuecomment-1512453770).

When creating a BO order, selecting an existing customer associates a `customer_id` with the order being created.

If this is done a second time, then, the email and addresses will be updated (as seen in the UI) but the `customer_id` will not be updated.

This creates a mismatch between the email/addresses and the `customer_id`.

## Expected Behavior

Edit: When creating an order in the BO, a second customer selection should update the `customer_id` on the `order`.

## Actual Behaviour

Edit: When creating an order in the BO, a second customer selection does not updated the `customer_id` on the `order`.

## Steps to Reproduce

1 go to the admin dashboard -> order -> new order
2. select distributor and order cycle
3. click on next
4. select a customer, C1 for example
5. Notice that the email and the addresses will be loaded
6. completed the missing data
7. click on update
8. Select another customer: C2 for example
9. Notice that the email and the addresses will be updated
10. click on update
11. The email and the addresses will be updated, but the customer id will not be replaced! the order will always refer to C1 on the database.

## Animated Gif/Screenshot

For the order below:

![image](https://user-images.githubusercontent.com/49817236/232807954-0397a31b-45fe-45bb-930b-17611f18140e.png)

```

openfoodnetwork=> select email, customer_id from spree_orders where number = 'R228047701';
             email             | customer_id 
-------------------------------+-------------
 filipefurtado+treec@gmail.com |        8180
(1 row)

openfoodnetwork=> select email,id from customers where id = 8180;
              email              |  id  
---------------------------------+------
 filipefurtado+almondc@gmail.com | 8180
```

## Severity

I'm not fully aware of all the impact this may have, but I can imagine inconsistencies in reporting.

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.3.3
* Browser name and version: Firefox 111
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by sigmundpetersen** [comment]
Maybe I'm reading this wrong, but isn't the Expected and Acutal Behaviour switched here? 🙂

**Comment by jibees** [comment]
> Maybe I'm reading this wrong, but isn't the Expected and Acutal Behaviour switched here? 🙂

I agree. 
@filipefurtad0 I suppose that you agree too?

**Comment by filipefurtad0** [comment]
Yes :100: @sigmundpetersen @jibees
Thanks for spotting that - now edited :slightly_smiling_face:
