### ISSUE TITLE
Property filters on producers pages

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1072]
Customers can filter enterprises by the properties of the products they produce.

This affects pages:

- Producers
- Groups (producers tab)

**Comment by RohanM** [comment]
The branch `filter-by-producer-properties` allows filtering of producers by the product properties or producer properties. The filtering should take effect on the producers page and also the groups "Our Producers" tab. The filters should resize to fit the space correctly when the browser window is resized.

**Comment by sstead** [comment]
@RohanM properties aren't showing in the filter.
![image](https://cloud.githubusercontent.com/assets/10843056/17236137/2c1dda5a-558a-11e6-8311-c140de0edab4.png)

**Comment by RohanM** [comment]
Looks like the producers was being cached, so we weren't getting the property info. I did `Rails.cache.clear` and it looks good now. We might need to do this on production when it ships.

**Comment by sstead** [comment]
Yay looks good Rohan!
- Catches enterprise with only product properties
- Catches enterprise with only enterprise properties (and no products/or with products)
- Catches both
- Removes deleted properties
- Works on profile only, shop, farmer hub.
- Works in groups too
- Is applied 'and' with the products filter
