### ISSUE TITLE
[Brakeman] Parameter value used in file name. 

### ISSUE THREAD

**Issue by rioug** [openfoodfoundation/openfoodnetwork#10736]
### What we should change and why (this is tech debt)
This is security issue,  Brakeman reported a File Access error : https://brakemanscanner.org/docs/warning_types/file_access/ in this PR #10714 
Problematic code : 
https://github.com/openfoodfoundation/openfoodnetwork/blob/fbc619d29fcca28a8ecd648d6a9fa4bb42eabd6d/app/controllers/admin/product_import_controller.rb#L40-L46
and most likely this one as well : 
https://github.com/openfoodfoundation/openfoodnetwork/blob/fbc619d29fcca28a8ecd648d6a9fa4bb42eabd6d/app/controllers/admin/product_import_controller.rb#L16-L18

We should validate the `filepath` before passing it to the `ProductImport::ProductImporter`

### Context
This showed up in this PR #10714

**Comment by abdellani** [comment]
I check the code.
We're using absolut paths
![image](https://user-images.githubusercontent.com/16113997/234241026-6289e9b6-8369-47e5-9e07-fcf955799efa.png)

Maybe we can use Pathname to get the real path, then check if the path starts with `/tmp` ?
```ruby
Pathname.new("/tmp/../../etc/passwd").realpath
=> #<Pathname:/etc/passwd>
```

**Comment by mkllnk** [comment]
That's a good idea. We should probably match as closely as we can, e.g. `^/tmp/product_imort-[0-9a-z.]*/import\.csv$$`.

But also: why does the browser know the whole path? can we just use an identifier and construct the path ourselves?
