### ISSUE TITLE
Admin, Add unregistered users modal: Some HTML is rendered as plain text instead of being 

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#10743]
## Description
As an admin, if you submit the form contained in the `Add unregistered users` modal, some HTML are rendered as plein text instead of being parsed as HTML by the browser. Then the form cannot be submit. 

<img width="722" alt="Capture d’écran 2023-04-25 à 08 51 36" src="https://user-images.githubusercontent.com/296452/234196942-57da13e9-2f46-4078-b467-49e4f078f697.png">

## Expected Behavior
You should not see the HTML once the form has been submit.

## Actual Behaviour
You can see the HTML once the form has been submit.

## Steps to Reproduce

1. As an admin, go to `/admin/enterprises/ENTERPRISE_SLUG/edit#/users_panel`
2. Click on `Add an unregistered user` bouton, modal opens
3. In the modal, submit the form
4. You should see html `data-reflex='submit-InviteManager#invite'>` in plain text in the top of the modal

## Workaround
The first time feature works, so workaround is something about ignoring this string.
Then, you should reload the page.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
Maybe worth checking once npm/gem packages on both cable_ready/stimulus_reflex when they will be ready in 5.0.0 and 3.5.0 respectively.

**Comment by abdellani** [comment]
When I click on `submit` nothing happens on the UI (tested under chrome/ubuntu):
![image](https://user-images.githubusercontent.com/16113997/234251252-d726bcb2-9ee0-4824-be78-7da11985360d.png)
I tried to upgrade cable_ready gem from "5.0.0.rc2" to "5.0.0"
but it looks like the problem is on  `stimulus_reflex` npm which depends on `rc-2`
```yml
stimulus_reflex@3.5.0-rc2:
  version "3.5.0-rc2"
  resolved "https://registry.yarnpkg.com/stimulus_reflex/-/stimulus_reflex-3.5.0-rc2.tgz#94ffa16d6c96220909ac18da74ebc73e718d2978"
  integrity sha512-vDF1TN9Ts2HlAjvVUV9gpv75zo+nZvVFLMKWPUFzjY6DK8VJEQMEYoZB36TQePlf1z6emw7YBVEPPSV+GGguPw==
  dependencies:
    "@hotwired/stimulus" "^3"
    "@rails/actioncable" "^6 || ^7"
    cable_ready "5.0.0-rc2"
```
