### ISSUE TITLE
Clicking on product image in checkout takes me to the homepage

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1075]
![image](https://cloud.githubusercontent.com/assets/10843056/16508167/c3129d2e-3f73-11e6-8fb4-69a51d803365.png)

Product images are clickable. I'd expect the product details window to open, but instead it takes me to the homepage.

**Comment by sineadfenton** [comment]
Hey @sstead 

Just wondering on this one (sorry know its old). But are you referring products essentially having their own URLs?

We've had a request in from a user about products having the own URLs so when you share a product directly for marketing purposes but I could see this tying into this too where clicking on the image would open a new window or iframe with the product and not the homepage?

S

**Comment by sstead** [comment]
Hi @sineadfenton, I suppose most immediately we just need to remove the confusing homepage redirect. Either by making the image not clickable (this might be easiest), or by having it open the product modal that you see in the shop (e.g. below). 
![image](https://user-images.githubusercontent.com/10843056/31258705-ea21e728-aa8c-11e7-9514-c156fa472d4f.png)

Giving products their own URL would be a next step. I haven't heard requests for this in Australia, but I can see how it would be helpful for marketing. If we did have unique product URLs, for sure it would make sense that clicking on the product image would open that URL in a new tab.

**Comment by sineadfenton** [comment]
Hey @sstead agreed, think focusing on the redirect in the first instance is a good first step.

I'll open up a discussion on Discourse around the unique URLs and have that discussion separately so as to keep things on topic here!

S

**Comment by daniellemoorhead** [comment]
Hey @sstead can this be closed? #1923 is merged and you created #1925 to cover off the rest? If it's done then please close this, else let us know what is remaining to be done.

**Comment by daniellemoorhead** [comment]
Closed as this is done.
