### ISSUE TITLE
[background_reports] ActionView::Template::Error in admin/reports#show

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#10758]
## Error in OpenFoodNetwork UK

**ActionView::Template::Error** in **admin/reports#show**
incompatible character encodings: UTF-8 and ASCII-8BIT

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6449f315fc11140008a25de1?event_id=6449f44e00bbc5144bf80000&i=gh&m=ci)

## Stacktrace

    app/views/admin/reports/show.html.haml:25 - _app_views_admin_reports_show_html_haml___687673448943673400_229320
    app/controllers/admin/reports_controller.rb:43 - show_report
    app/controllers/admin/reports_controller.rb:28 - show
    lib/session_cookie_upgrader.rb:19 - call

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6449f315fc11140008a25de1?event_id=6449f44e00bbc5144bf80000&i=gh&m=ci)

*Created by David Cook via Bugsnag*

**Comment by dacook** [comment]
Discovered here: https://github.com/openfoodfoundation/openfoodnetwork/issues/10757#issuecomment-1524682012

**Comment by dacook** [comment]
FYI @mkllnk I discovered this issue which made on screen reports unusable on UK prod when background_reports is enabled.

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**ActionView::Template::Error** in **admin/reports#show**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/6449557e99817e0008c84da3?event_id=644a7f7800bc6041be5b0000&i=gh&m=li)

**Comment by mkllnk** [comment]
Just noting that this has been observed on uk-prod and au-staging, both of which run Ubuntu 16.

**Comment by mkllnk** [comment]
I put a `pry` in the view where we render the table. Without background reports, the string is UTF-8. But with background reports:

```
@table.encoding
=> #<Encoding:ASCII-8BIT>
```

That doesn't raise an error in development though. So why does it raise an error on some servers and not others?

**Comment by mkllnk** [comment]
I inserted the UTF-8 ✓ character into a customer name to appear in the report and that works. So still not sure how to reproduce.

**Comment by mkllnk** [comment]
I manually tested this patch on staging and it works but I don't know how to write a spec for it:
```diff
diff --git a/app/views/admin/reports/show.html.haml b/app/views/admin/reports/show.html.haml
index c0f4562..49ebd8a 100644
--- a/app/views/admin/reports/show.html.haml
+++ b/app/views/admin/reports/show.html.haml
@@ -22,4 +22,4 @@
     %button.btn-print.icon-print{ onclick: "window.print()"}= t(:report_print)
 
 = t(@error, link: link_to(t(".report_link_label"), @error_url)) if @error
-= @table
+= @table.force_encoding("UTF-8")
```

**Comment by dacook** [comment]
Strange, but I'm glad you were able to prove the fix. As you say, it could be due to other external factors, so maybe it's not worth trying to narrow down the exact problem, and just add a comment to explain why the fix is there. Hopefully, it won't be relevant in the future after eventually upgrading Ubuntu..
The main thing is that it works :)

**Comment by mkllnk** [comment]
I finally have a clue. When you concatenate two strings, one UTF-8 and one ASCII-8BIT, the result becomes ASCII-8BIT. But if the UTF-8 string has special characters then it can't convert to ASCII and raises an error. So I guess that, depending on the instance, the page has a UTF-8 character somewhere else on the page.
