### ISSUE TITLE
Standing Orders - Reporting

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1076]
Are there reporting requirements/changes?

**Comment by daniellemoorhead** [comment]
Need to confirm whether or not this is needed during the tweak fortnight @oeoeaio

**Comment by lin-d-hop** [comment]
#gitcull2017
@daniellemoorhead @oeoeaio Please reopen if you need this issue but... it's pretty... empty.
