### ISSUE TITLE
Require belongs_to associations by default

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#10778]
### What we should change and why (this is tech debt)

Rails changed the default behaviour of the `belongs_to` association type in Rails 5.0. In old Rails presence on those relationships is not validated. Most of the times they need to be present though and we have a lot of `validate :x, presence: true` in our code. But we can now adopt the new Rails default which lots of new contributors expect.

### Context

* https://github.com/openfoodfoundation/openfoodnetwork/pull/10761#discussion_r1181982952
* https://edgeguides.rubyonrails.org/configuring.html#default-values-for-target-version-5-0

https://github.com/openfoodfoundation/openfoodnetwork/blob/482d438ec93f91bcc4f6aafa307fdfa2cffeb4d9/config/application.rb#L229

**Comment by lin-d-hop** [comment]
@mkllnk is this actively in play or can be move from In Dev for now?

**Comment by mkllnk** [comment]
In play. My tech-debt task when I need a break. It will probably stick around for a while.
