### ISSUE TITLE
Improve Order Cycle Clone Performance

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/openfoodnetwork#10777]
## Description
When large order cycles (e.g. with complex product descriptions and 3000+ products) are cloned, the default timeout is exceeded and that results in a slug 

## Expected Behavior
The order cycle should clone.

## Actual Behaviour
The slug shows up. This happens in multiple instances.

## Steps to Reproduce
Same steps as in https://github.com/openfoodfoundation/ofn-install/issues/871

**Comment by drummer83** [comment]
This was closed in #10832.
