### ISSUE TITLE
SO - Polling of order cycle open and close times

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1077]
Set up a chron job to poll order cycles every minute and trigger notifications for new opened cycles (#1078) or finalising orders in closed cycles (#1080).

**Comment by mkllnk** [comment]
- [ ] add process state to order cycle model (3h)
- [ ] write job to be executed periodically (6h)
- [ ] write cron job to create a delayed job (1h)
- [ ] setup cron job with ofn-install (4h)

**Comment by sstead** [comment]
From my understanding this is done. The system 'sees' when an OC in a schedule opens/closes and triggers appropriate actions.
