### ISSUE TITLE
Can't proceed to checkout if order total is equal to 0 (blocked at details step)

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#10787]
## Description
When a shop displays products at zero euros and a customer wants to shop products at zero euros from this shop, the tool loops on step 1 of spit checkout.

## Expected Behavior
Client should be able to shop products at zero euros

## Actual Behaviour
>Shop displays products at zero euros
>Customer add products at zero euros to his cart
> Customer selects "Checkout"
> Customer is stuck on the 1st step "1-Your details"

## How to test

1. As a shop manager, create a shop that sells a 0 product 
2. As a customer, add this product to cart
3. Proceed to checkout
4. On details step, fill the form
5. Submit
6. See that you're redirected to the details page.

I've create a shop, can be easily reproduced: https://staging.coopcircuits.fr/free-products-shop/shop

## Workaround
No free products on a shop

## Severity
S3
It's a real bug, but it concerns a rare use of the platform, so I would say S3

**Comment by jibees** [comment]
It's probably related to the order state, that is not able to be set to `payment` if there is only product at 0 and one is then redirected to details step when trying to proceed to payment step.

**Comment by jibees** [comment]
Note that this could probably happen if product is not equal to 0 but if you have paid products + vouchers (or negative fees) so that it brings the order total to 0.

**Comment by filipefurtad0** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/pull/11135 fixes this :tada: closing!

Please note that orders with `total = 0` will appear on the payments report like so:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/050afaba-9acb-42c4-bee8-8c7148beea13)

I think the `none` string is not translated, but I'm not even sure we should have this line on the report. Happy for feedback on this - discussion [here](https://openfoodnetwork.slack.com/archives/C04KJ61B63B/p1689164848517999).
