### ISSUE TITLE
Transition from legacy -> split checkout blocks order completion

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10790]
## Description

If a session is on legacy checkout and split checkout is enabled, then the customer will not be able to complete the order.

**Bugsnag**
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/63eeb3b31e601a000bde99a5?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging

**Bugsnag JS**
https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/645121280ee4280008dde93f?event_id=6451212700bc9ca9af670000&i=sk&m=nw

## Expected Behavior

Clicking "Place order now" should re-direct the customer to `/checkout/details`

## Actual Behaviour

A general error message is displayed; the customer cannot checkout.

## Steps to Reproduce

1. Disable split checkout
2. Begin checkout with a customer: stop at the checkout screen (/checkout)
3. Enable split checkout
4. Without refreshing the page, complete checkout (click Place order)
5. See the error.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/235703203-6748aa10-2ff9-40d8-a2bc-5830e254db68.png)

## Workaround

Refresh the page;

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.3.5
* Browser name and version: 112
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by filipefurtad0** [comment]
Not sure on the severity... as all instances are now on split-checkout. The bug may still occur if there are any open sessions on legacy checkout.

**Comment by RachL** [comment]
Legacy checkout has been removed, closing :tada:
