### ISSUE TITLE
Missing validation of user email address

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#10808]
## Error in OpenFoodNetwork Aus

**Net::SMTPFatalError** in **ActionMailer::MailDeliveryJob@default**
555 5.5.2 Syntax error. a80-20020a0dd853000000b0054c0dd7b376sm21641ywe.9 - gsmtp

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64544e2308cebe0009e0c732?event_id=645461da00bcd98a12030000&i=gh&m=ci)

## Stacktrace

    gems/net-smtp-0.3.3/lib/net/smtp.rb:1076 - check_response

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64544e2308cebe0009e0c732?event_id=645461da00bcd98a12030000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by mkllnk** [comment]
A user was created by inviting a manager to an enterprise. Somehow the email address had two backslashes `\\` at the end of the correct address. This was not caught by our validations and sending welcome emails failed.

**Comment by jibees** [comment]
We do have a test for invalid email, but seems like email address with two backslashes at the end is _valid_

https://github.com/openfoodfoundation/openfoodnetwork/blob/ec4c7b79bf04f76bad83f978618e3b1b27f419ac/spec/system/admin/enterprises_spec.rb#L570-L590

**Comment by mkllnk** [comment]
It was difficult to find where the validation happens. Our model uses Devise to validate:

https://github.com/openfoodfoundation/openfoodnetwork/blob/ad033e8d44631446c9e5117af6e35034badf4b46/app/models/spree/user.rb#L9-L10

Devise's validation just tests for an `@` though. It doesn't really check the validity:
```rb
  # Email regex used to validate email formats. It simply asserts that
  # one (and only one) @ exists in the given string. This is mainly
  # to give user feedback and not to assert the e-mail validity.
  config.email_regexp = /\A[^@\s]+@[^@\s]+\z/
```
https://github.com/heartcombo/devise/blob/4b72064bfcf076478c5c87818b9536b203f6584f/lib/generators/templates/devise.rb#L183-L186

When a user then becomes a customer, we have an additional validation:

https://github.com/openfoodfoundation/openfoodnetwork/blob/ad033e8d44631446c9e5117af6e35034badf4b46/app/models/customer.rb#L34

That gem is actually quite sophisticated and can test that the given domain is actually present and configured to receive email. This would catch typos, even when the result is a valid domain. We would need to update our test data though:

```rb
ValidEmail2::Address.new("me@example.com").valid_mx?
=> false
```

I suggest we add this validation to the user model and skip the customer email validation when a user is present. We still need to verify the email for guest checkouts though.

One challenge is that we have invalid emails in the database and we need some kind of migration to fix them or delete them. Otherwise the records will be invalid and logging in, for example can fail once we have a validation in place.

This missing validation explains some customer support requests...
