### ISSUE TITLE
Create order - can't select Paypal as payment method

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1081]
If I try to select paypal as a payment method when I'm creating an order from the back end, I get the 'grumpy cat/evil snail'.

![image](https://cloud.githubusercontent.com/assets/10843056/16512028/37ff79b0-3f9a-11e6-82f1-68167becdf0a.png)
- This may be because my Paypal account is not setup correctly? I'm unable to check whether this is also problematic for enterprise with properly functioning Paypals.
- It sort of makes sense that admin would be unable to select Paypal as a payment method, because this usually requires the user to login and pay on the spot. Alternatively, we'd need to send the customer a link saying 'pay now with Paypal'.

**Comment by sstead** [comment]
There is now a warning message, which is good.
![image](https://user-images.githubusercontent.com/10843056/28701704-50e7339c-739b-11e7-8f2b-893eefbcc63e.png)

**Comment by sstead** [comment]
The warning message is an improvement. But even better would be to remove/disable selection of Paypal as a payment method. Because people who haven't seen the warning can still get the Snail page- best to prevent this.

**Comment by lin-d-hop** [comment]
Paypal can be selected for orders created in backoffice now :-)
