### ISSUE TITLE
Develop the Ruby Connector that OFN will use to connect to the DFC

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#10828]
:information_source: **This is a funded feature.** Please use the Clockify project with the following name when working on this, including review and test: `#10828 DFC Ruby Connector`

## Description

Maxime has begun work on a Ruby Connector to the DFC. The connector automates the task of creating Ruby objects based on the DFC data model. Currently it can create objects and export to JSON-LD, OFN are going to enhance this work to also include functionality to Import from JSON-LD to Ruby objects.

Complexity in this step arises as not all objects in the graph must be populated, some may just be referenced as in:

`    {
      "@id": "entreprise/entrepriseId",
      "@type": "dfc-b:Entreprise",
      "dfc-b:VATnumber": "",
      "dfc-b:affiliates": [
        "person/personId"
      ],
      
      "dfc-b:defines": [
        "customerCategory/customerCategoryId1",
        "customerCategory/customerCategoryId2"
      ],
      "dfc-b:supplies": [
        "suppliedProduct/item1",
        "suppliedProduct/item2"
      ],
      "dfc-b:manages": [
        "catalogItem/catalogItemId1",
        "catalogItem/catalogItemId2"
      ]
    },`

the `customerCategoryId1` & `customerCategoryId2` nodes may not be included in the graph, so the Connector will need to utilise Lazy loading to create placeholders for those objects (including URI) and fetch additional data from that endpoint if required.

## Acceptance Criteria & Tests

1. Enhance the DFC Ruby connector  to automatically generate Ruby objects from an import of JSON-LD in approved DFC format,
2. The Connector must still be able to generate DFC valid JSON-LD output via Export.
3. The Connector must be able to parse incoming DFC valid JSON-LD via Import.
4. All JSON-LD generated or read should conform to [v1.8 of the DFC Standard](https://datafoodconsortium.gitbook.io/dfc-standard-documentation/appendixes/practical-examples/version-1.8)
5. The Import should handle referenced nodes by creating placeholder objects & using lazy loading.
6. If a referenced node is not present in the graph, a placeholder object should be created with the valid URI to the referenced object
7. The unpopulated placeholder can be later populated by retrieving the object details from the supplied URI
8. There is an assumption for Updates that all amended data is included in the graph - there is no requirement to populate referenced nodes that are not included for an Update.

**Comment by lin-d-hop** [comment]
@RaggedStaff Can you add links to any more details about this work. This is a really under specced issue right now. :pray: Thanks!

**Comment by RaggedStaff** [comment]
There's [a discussion on Import, lazy loading, pulling references in Slack](https://openfoodnetwork.slack.com/archives/C024VS581SA/p1681893891253899)
The Ruby Codegen portion of the Connector is [here](https://github.com/datafoodconsortium/connector-codegen-ruby)

This portion of the code falls within the `static` folder. 

This work is to incorporate Import functionality into the connector... to allow the parsing of incoming JSON-LD from another DFC platform and loading into DFC model objects created by the Connector.

Similar functionality has been implemented in the [Typescript Connector](https://github.com/datafoodconsortium/connector-codegen-typescript).

Complexity arises as not all objects will be fully populated.. some may just be links (including URI ID), these will need to be fetched as required by the application (lazy loading)

**Comment by lin-d-hop** [comment]
Hiya @mkllnk @RaggedStaff 
Is it purely capacity that is blocking this piece from being wrapped up currently? Or is there something external blocking this?
Thanks!

**Comment by mkllnk** [comment]
> Is it purely capacity that is blocking this piece from being wrapped up currently? Or is there something external blocking this?

There was a lot of delay because of Maxime's rewrite of the connector code generator. I think that we're finally unblocked though. I'm about to test the latest code again.

**Comment by RachL** [comment]
@mkllnk do we still need this issue?

**Comment by mkllnk** [comment]
> do we still need this issue?

Yes, the import functionality is not complete yet, just patched in OFN at the moment.

**Comment by mkllnk** [comment]
Currently just waiting for a review and merge:

* https://github.com/datafoodconsortium/connector-codegen/pull/12

We do have the code in OFN though and are using it already. Just waiting for upstream.
