### ISSUE TITLE
On small width screen, the cart element is missplaced

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#10835]
## Description
An image is better: 
<img width="568" alt="Capture d’écran 2023-05-12 à 09 19 36" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/296ec23b-641d-4f53-9426-aa79a7a99a53">

_Originally posted by @drummer83 in https://github.com/openfoodfoundation/openfoodnetwork/issues/10830#issuecomment-1544754115_

## Expected Behavior
Thi
<img width="593" alt="Capture d’écran 2023-05-12 à 09 19 45" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/4052f0f2-3156-4d14-8438-e24840acd107">

## Steps to Reproduce

1. Go to `/` with a small width device
2. See that the Cart element is missplaced

**Comment by filipefurtad0** [comment]
It does not affect all browsers, though:

Desktop (**Ubuntu 22.04**):
- left Chrome Version 113.0.5672.63 (Official Build) (64-bit) **- bug is not observed**
- right Firefox 113

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/b4b6943c-f1cc-41db-8d96-0e7c53dde695)

Mobile (**iPhone 13**)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/5a216538-0c37-4176-b16f-73df2ec34e16)

**Comment by drummer83** [comment]
@filipefurtad0 What happens if you reduce the screen size on Chrome? I assume it will show the bug as well.

**Comment by filipefurtad0** [comment]
> What happens if you reduce the screen size on Chrome?

Yes, had to reduce it more - spotted now.
