### ISSUE TITLE
v4.3.7 Seaweed Salad

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10830]
## Preparation on Thursday

- [x] Merge pull requests in the [Ready To Go] column
- [x] Include translations: `tx pull --force`
- [x] [Draft new release]. Look at previous [releases] for inspiration.
- [x] Notify [#instance-managers] of user-facing changes.

## Testing

- [x] [Find build] of the release commit and copy it below.
- [x] Move this issue to Test Ready.
- [x] Notify `@testers` in [#testing].
- [x] Test build: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/4419
- [x] Build including regression fix: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/4421

## Finish on Tuesday

- [x] Publish and notify [#global-community] (this is automatically posted with a plugin)
- [x] Deploy the new release to all managed instances.
  <details><summary>Command line instructions</summary>
  <pre>
  cd ofn-install
  git pull
  ansible-playbook --limit all-prod --extra-vars "git_version=vx.y.z" playbooks/deploy.yml
  </pre>
  </details>
- [x] Notify [#instance-managers]:
  > @instance_managers The new release has been deployed.
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Ready To Go]: #zenhub
[Transifex pull request]: https://github.com/openfoodfoundation/openfoodnetwork/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+head%3Atransifex
[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A
[releases]: https://github.com/openfoodfoundation/openfoodnetwork/releases
[#instance-managers]: https://app.slack.com/client/T02G54U79/CG7NJ966B
[#testing]: https://openfoodnetwork.slack.com/app_redirect?channel=C02TZ6X00
[Find build]: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master
[#global-community]: https://app.slack.com/client/T02G54U79/C59ADD8F2

**Comment by drummer83** [comment]
Hi @filipefurtad0 and @openfoodfoundation/core-devs,

I found an issue with this release on small screens (mobile). The 'cart' button is displayed in the wrong position as soon as the main navigation turns into the burger menu. Considering the large portion of mobile users I tend to seeing this as a release blocker. What do you think?

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/39163a76-6014-4d78-b307-d1190eef8266)

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/db6d746d-281d-42e0-8e18-40419dc60537

The rest is ok in this release, see testing notes here: https://docs.google.com/document/d/1IyXbALQXn11CKXym_3Hr7K7iUegqvBJe43DuN-iOCW0/edit#

**Comment by mkllnk** [comment]
Ouch. This is tricky. The release fixes an s2 bug. Is this bug as important? Difficult to say. The s2-bug affects enterprise managers but this visual regression looks really bad. :thinking: 

I agree with you, this should block the release. Affecting far more users and being a clear regression.

**Comment by sigmundpetersen** [comment]
Have we also confirmed this bug is not in master? If it is it should not block the release.

**Comment by filipefurtad0** [comment]
Agree with all the above.

It seems to affect users throughout the whole checkout, and to have been introduced with this release (left, prod-UK; right, staging-UK):

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/a2a1c106-7017-4604-9c7a-97c2a6d27a7f)

**Comment by jibees** [comment]
> Have we also confirmed this bug is not in production? If it is this should not block the release.

As far as I know, no, this bug is not in production: 

<img width="578" alt="Capture d’écran 2023-05-12 à 09 17 16" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/e70433ff-32ca-4238-8602-ad4c9efdf449">

So I will open an issue, that should be in the release: https://github.com/openfoodfoundation/openfoodnetwork/issues/10835

**Comment by filipefurtad0** [comment]
> The rest is ok in this release, see testing notes here: https://docs.google.com/document/d/1IyXbALQXn11CKXym_3Hr7K7iUegqvBJe43DuN-iOCW0/edit#

Given the tests on the release are ok, and https://github.com/openfoodfoundation/openfoodnetwork/issues/10835 is now closed (the PR only touches the UI). In any case, I've re-staged in another server and had a quick sanity test around the checkout UI (around the pages - shop, details, payment, summary, cart): all looks good to me.

I think we're safe to move this to Ready to Go. Do you agree @drummer83?

**Comment by drummer83** [comment]
Yes, I agree. Thanks, @filipefurtad0!

**Comment by jibees** [comment]
@filipefurtad0 did you change the target commit on the draft release? Any PR/commits merged (expect the one that solve the small width screens issue, https://github.com/openfoodfoundation/openfoodnetwork/issues/10835) during that time? If any commits, we probably should re-test the release.

**Comment by filipefurtad0** [comment]
> Any PR/commits merged (expect the one that solve the small width screens issue, https://github.com/openfoodfoundation/openfoodnetwork/issues/10835) during that time?

Yes, but only a spec - 93c0a064032e414ed947ce96fd974535272a17f3

I've staged the new build on staging-FR and did some quick checks, but yeah - I guess it can't hurt to have the full release test :ok_hand:

**Comment by filipefurtad0** [comment]
Re-tested the release, looking good :rocket: 
https://docs.google.com/document/d/1h4ZhZ6v25KBDq5o4DLbphB2kEtKnU111CYckDbA_nNM/edit#
