### ISSUE TITLE
SO - Display products bought in an order cycle in the shop cart dropdown

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1083]

**Comment by mkllnk** [comment]
Some estimates:

- [ ] Modify the cart view (2h)
- [ ] Load additional data (3h)
- [ ] Review and testing (2h)

**Comment by mkllnk** [comment]
@sstead Can you give some feedback about the layout of this? It could look like this:
![screenshot from 2016-07-22 16 15 31](https://cloud.githubusercontent.com/assets/3524483/17048253/dcbc6894-5027-11e6-9ce8-bcd592aff181.png)

**Comment by sstead** [comment]
How does it feel when the orders are both longer? I suppose it would scroll? The 'already ordered' section doesn't need a 'checkout now' button- will people be able to edit a past order as well? Otherwise it's good. Will there be a whole page view as well?..sometimes I shop without using the mini cart feature, and it would be good to see my already placed ordered in a full screen too.

**Comment by mkllnk** [comment]
> How does it feel when the orders are both longer? I suppose it would scroll?

Yes, it would scroll.

> The 'already ordered' section doesn't need a 'checkout now' button

These two buttons where already there. Originally, it was at the bottom. Then we placed a second one at the top in case the cart is very long. Now, the bottom one looks like it belongs to the ordered products. Should we just show the top buttons?

> will people be able to edit a past order as well?

Yes. But that comes later.

> Will there be a whole page view as well?

Yes. But that comes later.

Is the total of the previously ordered stuff confusing? We could hide that.

**Comment by sstead** [comment]
Looks good... 
![image](https://cloud.githubusercontent.com/assets/10843056/20824235/fd3ba932-b8ae-11e6-9c10-19dd6b2f4286.png)
- Scrolls well when long
- Scrolls on mobile (quick test)

**Comment by sstead** [comment]
Looks good. 
As already noted, cancelled orders are lingering. They also linger in the cart dropdown.

**Comment by sstead** [comment]
Canceled orders no longer lingering in the cart dropdown.
