### ISSUE TITLE
SO - Display products bought in an order cycle in the edit cart page

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1084]

**Comment by mkllnk** [comment]
Some estimates:

- [ ] Modify the edit cart view (1h)
- [ ] Load additional data (2h)
- [ ] Review and testing (1h)

**Comment by sstead** [comment]
Yes- is displaying, and only for order cycles where previous orders exist...
![image](https://cloud.githubusercontent.com/assets/10843056/20824661/9b4dfb68-b8b2-11e6-9e07-73b19349c3a8.png)

Yes- this message is clear and the link works, taking them to the edit cart page. One little improvement would be to take the customer to the page halfway scrolled down, in case they don't see it below their current order.
![image](https://cloud.githubusercontent.com/assets/10843056/20824686/c9cad006-b8b2-11e6-854c-fad97ac3d214.png)
