### ISSUE TITLE
SO - Improvements for when bought products are removed from an order on edit cart page

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1085]

**Comment by mkllnk** [comment]
- [ ] Update user interface (3h)
- [ ] Add feature to controller (3h)

**Comment by sstead** [comment]
Testing notes and images...
![image](https://cloud.githubusercontent.com/assets/10843056/18112047/ee8fa8f6-6f67-11e6-9cb7-4cf90b42be9b.png)

![image](https://cloud.githubusercontent.com/assets/10843056/18112065/1555824e-6f68-11e6-9744-4912461451c1.png)


![image](https://cloud.githubusercontent.com/assets/10843056/18112059/04ae26da-6f68-11e6-8c91-5be1b03f71e2.png)

![image](https://cloud.githubusercontent.com/assets/10843056/18112068/1c3cebc4-6f68-11e6-8913-9737e7bc94f5.png)

![image](https://cloud.githubusercontent.com/assets/10843056/18112074/29791fb0-6f68-11e6-9903-5ab75bc30f8a.png)

![image](https://cloud.githubusercontent.com/assets/10843056/18112077/2db9e3b6-6f68-11e6-9fa0-bd48d6b4444a.png)

![image](https://cloud.githubusercontent.com/assets/10843056/18112079/319e4b48-6f68-11e6-9147-31830a06cb57.png)

![image](https://cloud.githubusercontent.com/assets/10843056/18112085/3e84dbba-6f68-11e6-986e-a44ee64801ac.png)

![image](https://cloud.githubusercontent.com/assets/10843056/18112088/43750a0a-6f68-11e6-8209-1de36a5cd04f.png)

![image](https://cloud.githubusercontent.com/assets/10843056/18112210/3c1f80ea-6f69-11e6-8ad3-a04bd7ef80a6.png)

**Comment by sstead** [comment]
Looks good. 
The suggested improvements above are still outstanding, but the basic functionality is there.

**Comment by mkllnk** [comment]
Okay. Just summarising the suggestions that have not been done yet:

- Combine line items of the same product #1166.
- Edit quantity bought line items. The problem with this is that it is not clear at which point you actually commit to buy stuff. Say, you increase the number by one, you still need to go through some kind of checkout to confirm this change. We don't have a non-confusing solution for that.
- Soft delete and safe. For example: You click on delete. The row is crossed out and a save button appears. You need to press save to really delete the product. Let's keep this in mind when we get more feedback on this.
- Shipping fees are not changed. That's a problem. Is there any case in which the shipping fee should not be re-calculated?
- Confirmation about changed orders. Tricky. When should we email people? We could email for each item, but that would be annoying. If there would be the save button (see above), we could email on saving. That sounds good.

**Comment by myriamboure** [comment]
I opened that issue to cover the bug hidden in the testing comments here: https://github.com/openfoodfoundation/openfoodnetwork/issues/2906, not directly connected to recurring order feature.
I will retest and open a new issue for the shipping fee if that requires it, else let's wait for a case to happen...
Apart from that all the rest seems ok, so I'm closing that issue now.
