### ISSUE TITLE
[Vouchers] Order total in /cart page not updated

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10855]
## Description

If a voucher has been added (Step 2) and the customer checks the cart (visiting the `/cart` page) then the voucher parcel will appear deducting the order total. However, the order total itself, remains unchanged.

## Expected Behavior

The order total should be updated on the `/cart` page, when a voucher has been added to the order.

## Actual Behaviour

The order total is not updated on the `/cart` page, when a voucher has been added to the order.

## Steps to Reproduce

For all voucher issues: per-requisites are:
- As super admin - enable the vouchers feature toggle
- Having a hub with at least one voucher created
- The hub should have an open shop

1. As a customer, on the shopfront, add items to the cart. Edit your cart. (pic below, **point 1**)
2. Begin checkout, and stop on step 2 (/payment), add a voucher to the order. Edit your cart. (pic below, **point 2**) -> notice the existing parcels, but see the order total was not updated :x: 
3. Proceed to `/summary`. Notice the existing parcels, and see that order total was updated :heavy_check_mark: 

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/8799a02e-8227-4343-9d1f-2e01a20fd054)

## Workaround

The workaround is checking this in the summary page.

**Comment by rioug** [comment]
Will be fixed by #11003

**Comment by filipefurtad0** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/pull/11135 fixes this :tada: closing!
