### ISSUE TITLE
SO - Allow for editing orders and cart in the shop cart dropdown

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1086]

**Comment by mkllnk** [comment]
- [ ] Update user interface (3h)

**Comment by mkllnk** [comment]
We had this idea in the beginning, but it is not needed for a minimum viable product. Currently, you can't edit your cart in the dropdown, only on the cart page. So we don't need to introduce that for standing orders.

I also just talked to Rob and this needs a bit more thought, maybe a UX designer. If we enable editing in the dropdown, we have effectively two carts with the same features, which is confusing and more work in the future. We could develop the dropdown to be a fully featured cart and then remove the actual cart page. That means that the cart is always available on all pages. But there are open questions. It could get confusing if we introduce multiple carts for multiple shops. Or if people have a very small screen (mobile). We also have to make sure that it doesn't slow down the site.

**Comment by daniellemoorhead** [comment]
Not required
