### ISSUE TITLE
[Vouchers] Disabled 'Apply' button is blocking the voucher usage

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10866]
## Description

If a voucher code is entered but not yet applied and no payment method is selected when clicking 'next', then the 'apply' button remains disabled. It feels like you can't apply a voucher anymore. You have to change the value in the voucher code field before it can be applied.

## Expected Behavior

If there is a code entered in the voucher code input field, the 'Apply' button should be enabled, also after failing to go to the next step due to a missing payment method selection.

## Actual Behaviour

If a voucher code is entered but not yet applied and no payment method is selected when clicking 'next', then the 'apply' button remains disabled. It feels like you can't apply a voucher anymore. You have to change the value in the voucher code field before it can be applied.

## Steps to Reproduce

1. Proceed to checkout of an enterprise with vouchers.
2. On step 2 of the checkout enter a voucher code, but don't click 'Apply' yet.
3. Don't select a payment method.
4. Click 'Next - Order summary', an error message is displayed.
5. Observe that the voucher code is still there, but the 'Apply' button is disabled.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/6af46ddc-87d7-4fe7-bfc8-441acc683d7b

## Workaround

Change the voucher code.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Keep the voucher code and enable the 'Apply' button'.

**Comment by rioug** [comment]
Will be fixed by #11003
