### ISSUE TITLE
[Vouchers] No red highlighting of voucher code when code can't be found

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10869]
## Description

When a voucher code is entered which can't be found there is an error message asking to update the highlighted fields. But the voucher code input field is not highlighted in this case.

## Expected Behavior

The voucher code field should be highlighted (in red, see other examples).

## Actual Behaviour

There is the error message, but no highlighting.

## Steps to Reproduce

1. Proceed to checkout at an enterprise which has vouchers.
2. On step 2 type an invalid voucher code.
3. Look at the error message and the voucher code input field.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/4bd3cb29-6443-4901-8344-5d20b3d06802)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by rioug** [comment]
will be fixed by  #11003
