### ISSUE TITLE
Can't register a product price with a dot

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#10873]
## Description
Impossible to register a product price with a dot. 
If the price of the entered product is 5.5 euros, the price of the registered product will be 55 euros.

## Steps to Reproduce

1. As a shop manager, create a product and include a price with dot
2. Save the product
3. Consult the product price

## Workaround
Use a comma

## Severity
S3

**Comment by Cecilia-Hn** [comment]
My apologies, this is not a bug, this is related to the fact that we had, in France, unchecked the location options to compensate for the impossibility of using minus criteria -> https://github.com/openfoodfoundation/openfoodnetwork/pull/10838

**Comment by sigmundpetersen** [comment]
Maybe we can close the issue then?
Or do you still want to keep it open?

**Comment by Cecilia-Hn** [comment]
Yes :)
