### ISSUE TITLE
[Vouchers] UX and design improvements of page 'Vouchers'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10871]
## What is the need / problem?
The design should be similar to the 'Payment methods' or 'Shipping methods' pages because they all have the same purpose. Unified design increases usability and improves the experienced overall quality of the software.

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Instance Managers

## Potential solutions that will solve the problem
'Add new' button is currently above the table --> Comparing to Payment/Shipping methods: Name it 'Create new voucher +' and place it below the table.

Here is a mockup:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/92ee2f0a-d89d-4d55-a88c-142595d170e4)

Current design:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/26250112-cf5d-4b18-b593-7c65f3129285)

## Additional context
https://github.com/openfoodfoundation/openfoodnetwork/pull/10761#issuecomment-1554767636

**Comment by lin-d-hop** [comment]
See https://github.com/openfoodfoundation/openfoodnetwork/issues/10870#issuecomment-1586810378

Closing this issue so we can implement the actual designs with the BUU work.

Thanks for the detailed eye @drummer83
