### ISSUE TITLE
[Vouchers] UX and design improvements of page 'New voucher'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10870]
## What is the need / problem?
The design should be similar to the 'New payment method' or 'New shipping method' pages because they all have the same purpose. Unified design increases usability and improves the experienced overall quality of the software.

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Instance Managers

## Potential solutions that will solve the problem
1. Use header design from Payment/Shipping methods: 'New Voucher' & button 'Back to voucher list'
2. Use footer design from Payment/Shipping methods: Include the 'Cancel' and 'Create' buttons in the footer of the page
3. Default value should be $ 0.00 (instead of $ 0.0 which is untypical for money amounts).
4. Use a single-line input instead of a multi-line text field (separate issue #10868)

Here is a mockup:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/b7cd7440-c793-41a6-a06c-1fc529ac4052)

Current design:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/6b8284ca-412e-4d5f-95f7-f6aed34c5c04)

## Additional context
https://github.com/openfoodfoundation/openfoodnetwork/pull/10761#issuecomment-1554767636

**Comment by lin-d-hop** [comment]
Thanks for the detailed eye suggesting these @drummer83 

The voucher phase 1 work is out of budget so we have to pause on this work for now.

From @rioug on slack
_The design was done with the "new backoffice design" , which wasn't ready at the time when I started working on voucher. So I just used the current colours but try to stay as closed as possible to the given design ( at least in term of where the button and input field  are ) . As far as I can see, the UX improvement would bring the voucher pages more in line with the existing backoffice pages. So I'd say we should wait for the Backoffice UI uplift before addressing these._

Out of interest, when the QA was happening on this work was there a process to check against the designs? Of course in this case it wouldn't have helped. But for future work I'm hoping that part of the QA for new features is checking them against designs. Maybe that already happens. If not maybe one for a testers meeting? :)
