### ISSUE TITLE
SO - Process standing orders when a new order cycle opens

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1087]

**Comment by mkllnk** [comment]
Estimates:

Model data structure for scheduled orders (4h)
Create data migrations (3h)
Update user interface (2h)

**Comment by daniellemoorhead** [comment]
Needs to include error handling for products in the standing order that are not in stock.

**Comment by daniellemoorhead** [comment]
This issue can't be done until #1077 is completed.

**Comment by sstead** [comment]
From my understanding this is done. When an OC in a schedule opens, it triggers all subscriptions to that schedule to have an order created.
