### ISSUE TITLE
[BUU] Pagination for product list

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#10877]
## Context
This issue enhances the display of the product list table #10694.

## Out of scope
- truncate pagination links #10878 

## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** move between pages in my catalogue
**- So that:** I can load my products quickly and navigate between them

## Acceptance Criteria & Tests

**Scenario 1: Less than 25 products**
Given I have less than 25 products in my catalogue
And I am in `/admin/products`
And the page is loading my catalogue
When my catalogue has been loaded successfully
Then I don't see any pagination

**Scenario 2: More than 25 products**
Given I have more than 25 products in my catalogue
And I am in `/admin/products`
And the page is loading my catalogue
When my catalogue has been loaded successfully
Then I see the pagination

**Scenario 3: Clicking a page link**
Given I have more than 25 products in my catalogue
And I am in `/admin/products`
When I click on a page number
Then the table loads the products for the page I have clicked on

**Scenario 4: Disabled previous button**
Given I have more than 25 products in my catalogue
And I am in `/admin/products`
And the page is loading the first 25 products in my catalogue
When my catalogue has been loaded successfully
Then the button to go to the previous page is disabled 

**Scenario 5: Disabled next button**
Given I have more than 25 products in my catalogue
And I am in `/admin/products`
And the page is loading the last 25 (or less) products in my catalogue
When my catalogue has been loaded successfully
Then the button to go to the next page is disabled

**Scenario 6: Next button**
Given I have more than 25 products in my catalogue
And I am in `/admin/products`
And I am not in the last page of the catalogue
When I click on the next button in pagination
Then the catalogue loads the following 25 products in the list

**Scenario 7: Previous button**
Given I have more than 25 products in my catalogue
And I am in `/admin/products`
And I am not in the first page of the catalogue
When I click on the previous button in pagination
Then the catalogue loads the previous 25 products in the list

## Design specs
The screen for specs is here
https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?type=design&node-id=119-734

**New components and styles**

| Component | Example |
| --- | --- |
| Square action button | <img width="589" alt="Screenshot 2023-05-29 at 3 17 22 pm" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/7b3dc4da-359c-45c4-9019-4fc851cdd14c"> |

**Comment by mariocarabotta** [comment]
@jibees FYI the shadow is the same as the top menu one, if you want to reuse it as a mixin.
also on hover to be the same as active (mojo background and white label)

**Comment by jibees** [comment]
<img width="1377" alt="Capture d’écran 2023-06-21 à 11 50 47" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/2c4b6c0a-81df-4f03-bf04-1f33443817c1">

Available on PR/branch: https://github.com/openfoodfoundation/openfoodnetwork/pull/11007

**Comment by jibees** [comment]
I'm not sure either. Probably arrow should be much more light, and cursor should not be pointer but default.
