### ISSUE TITLE
SO - Notify customer when the order cycle has ended and their scheduled order is checked out

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1088]

**Comment by mkllnk** [comment]
- [ ] Model order cycle events (4h)
- [ ] Setup timed scripts (4h)
- [ ] Add setup scripts to ofn-install (4h)
- [ ] Create mailer with mail text (4h)

**Comment by sstead** [comment]
Yes, this is done, customers get an email at the close of the OC
