### ISSUE TITLE
[Checkout] Metrics: 99% of users "exit" on the `/details` step

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10881]
## Description

Sort of a duplicate of [this issue](https://github.com/openfoodfoundation/Analytics/issues/3). Bringing this over to this repo as a bug as discussed in delivery circle today.

Maybe related to https://github.com/openfoodfoundation/openfoodnetwork/issues/11599.

To a large extent, we're currently we're only able to track users on split-checkout till the `/details` step; after this, we observer exits to the order confirmation page.

For some reason, both customer support and myself are able to trigger the goal, and leave tracks through all the pages

## Expected Behavior

We expect to see this in the goals/funnels for UK-prod:

`/details` -> `/payment` -> `/summary` -> `/order_confirmation_page_URL` (GOAL trigger)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/dd8c1af4-00ac-4f53-9095-dc8f2663066d)

## Actual Behaviour

`/details` -> `/order_confirmation_page_URL` (no GOAL trigger)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/e95d568a-9ac9-4603-8def-82ee3ddda66f)

## Steps to Reproduce

1. Log into https://openfoodnetwork.innocraft.cloud/
2. Visit the UK-prod dashboard (site=2)
3. Check the goal and funnel from `SC_complete_order_w_funnel_URL`
4. Visit UK-prod site and checkout
5. Were you able to trigger a conversion with your visit? (you might need to wait 24hrs) If yes, then why? If no, then why?
6. Notice the current metrics: 99% of users exit from `/details` to order confirmation

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/c33c1eb3-f12e-4b39-a8e3-42244a3f7409)

## Your Environment

* Version used: v4.3.9
* Browser name and version: Not clear
* Operating System and version (desktop or mobile): Not clear

## Possible Fix

No idea: just using this space to post the latest data from the month of May (till today):

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/a973befc-01cf-46b7-a65d-aa475d4e7999)

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley , I've assigned you as we've chatted today - please do let me know if you need more context or any other info to tackle this.

**Comment by drummer83** [comment]
Now that #11599 has been closed we could consider looking at this again.
Would that make sense at the moment, @filipefurtad0 and @openfoodfoundation/train-drivers-product-owners?

**Comment by sigmundpetersen** [comment]
@filipefurtad0 what do you think of @drummer83 's comment above?
Or can this be closed here and followed up in https://github.com/openfoodfoundation/Analytics/issues/3 ?

**Comment by filipefurtad0** [comment]
Thanks for the reminder @sigmundpetersen . I think we can close here, as it does not seem to depend on our code, but on how Matomo is setup.

I recall checking this at the time, after we had the right page titles, but still could not observe user visits as separate events.

I think now might be a good time to revisit all this though, as we have a breaking change in Matomo.

Either way, I think it makes sense to track this issue on the Analytics repo. Closing.
(please feel free to reopen, should anyone disagree)
