### ISSUE TITLE
[staging-AU] Server down, no free space

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10917]
### What we should change and why (this is tech debt)

We need to clean up staging-AU. Staging/provisioning fails with:
`The error was: IOError: [Errno 28] No space left on device`

### Context

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/676
https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1685603143799249

### Impact and timeline

Testing.

**Comment by dacook** [comment]
I cleaned up some space: 
```
1.4G	/tmp/v8-compile-cache-1001
sudo rm -rf /tmp/v8-compile-cache-1001/

6.2G	/home/openfoodnetwork/apps/openfoodnetwork/releases-old
sudo rm -rf /home/openfoodnetwork/apps/openfoodnetwork/releases-old/* # oops I forgot that the current release is also under here!!

Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G   12G  7.7G  61% /
```

But accidentally deleted the current release, which causes deployments to fail.

**Comment by mkllnk** [comment]
We restarted the server, provisioned, deployed. Seems to work again. :heavy_check_mark:
