### ISSUE TITLE
Unit value not correctly displayed in /cart, /summary, order confirmation page & email

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10927]
## Description

Related and possibly same root cause as https://github.com/openfoodfoundation/openfoodnetwork/issues/9974

A `1 mL` variant will be displayed as `0 mL` in several places in the app, even after it was edited to display items, or another `variant_unit`, other than `volume`.

## Expected Behavior

A `1 mL` variant will be displayed as `1 mL` in:
- checkout `/summary` page
- `/cart` page
- order confirmation page
- order confirmation email

## Actual Behaviour

A `1 mL` variant will be displayed as `0 mL` in:
- checkout `/summary` page
- `/cart` page
- order confirmation page
- order confirmation email

## Steps to Reproduce

As a hub

1. Create a new product; 
2. Set mL as `Unit size`
3. Set 1 as `Value`
4. Add it to an open order cycle

As a customer

1. visit the shopfront and checkout with that item
2. Notice:
- checkout `/summary` page
- `/cart` page
- order confirmation email

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/7fbaf7e8-e2c3-4c85-88e3-f243ad74ec3b)

## Workaround

- correctly displayed in the shopfront -> `/<shop_name>/shop#/shop`
- correctly displayed in reports like packing reports by product -> `/admin/reports/packing/product`

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.3.11 (not introduced here)
* Browser name and version: Firedox 113
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

Not a possible fix, rather additional info - helpful to reproduce in a spec perhaps:

- from `spree_products`

```
  id   |   name    | description |        available_on        | deleted_at | permalink | meta_keywords | tax_category_id | shipping_category_id |         created_at         |         updated_at         | supplier_id | group_buy | group_buy_unit_size | variant_unit | variant_unit_scale | variant_unit_name | notes | primary_taxon_id | inherits_properties 
-------+-----------+-------------+----------------------------+------------+-----------+---------------+-----------------+----------------------+----------------------------+----------------------------+-------------+-----------+---------------------+--------------+--------------------+-------------------+-------+------------------+---------------------
 23707 | magic tea | \r         +| 2023-06-02 09:07:54.634159 |            | magic-tea |               |              14 |                    6 | 2023-06-02 09:07:54.710449 | 2023-06-02 09:07:54.795025 |        1852 |           |                     | volume       |              0.001 |                   |       |               64 | t
       |           | \r         +|                            |            |           |               |                 |                      |                            |                            |             |           |                     |              |                    |                   |       |                  | 
       |           |             |                            |            |           |               |                 |                      |                            |                            |             |           |                     |              |                    |                   |       |                  | 
(1 row)

```

- from `spree_variants`

```
  id   | sku | weight | height | width | depth | deleted_at | is_master | product_id | position | cost_currency | unit_value | unit_description | display_name | display_as | import_date | variant_unit | unit_presentation 
-------+-----+--------+--------+-------+-------+------------+-----------+------------+----------+---------------+------------+------------------+--------------+------------+-------------+--------------+-------------------
 63269 |     |   0.00 |        |       |       |            | f         |      23707 |        2 | CAD           |      0.001 |                  |              |            |             | volume       | 1mL
 63268 |     |   0.00 |        |       |       |            | t         |      23707 |        1 | CAD           |      0.001 |                  |              |            |             | volume       | 1mL
(2 rows)



```

**Comment by filipefurtad0** [comment]
I've taken the liberty to assign this one as S2 - I'd argue it's confusing as a user to receive confirmation emails with incorrect variant information. What do you think @openfoodfoundation/train-drivers-product-owners?

**Comment by jibees** [comment]
Discussion topic around severity: https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1685699285350599

**Comment by Matt-Yorkley** [comment]
It has a unit value of `0.001`, is it a rounding issue where that value is displayed?

**Comment by filipefurtad0** [comment]
> It has a unit value of 0.001, is it a rounding issue where that value is displayed?

Yup, seems to be the case - indeed, double from https://github.com/openfoodfoundation/openfoodnetwork/issues/9974.
Closing here, thanks!
