### ISSUE TITLE
Map suggests address but cannot locate it on the map

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1093]
![image](https://cloud.githubusercontent.com/assets/10843056/16675049/067a022c-4501-11e6-9b60-6d0068c13923.png)

@kirstenalarsen

**Comment by myriamboure** [comment]
Retested and this seems to be fixed, so closing: https://www.useloom.com/share/61f20c6d6b2b47309272fe72d4dd5d2d
Feel free to reopen if the bug still happens in Aus or elsewhere @sstead .
