### ISSUE TITLE
[White Label] Custom tab without a title; impossible to disable the custom tab

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10931]
## Description

Follow-up from #10875.

It's possible to create a custom tab, without a title. This makes the custom tab invisible to users.

It's also not possible to disable the custom tab, even if the checkbox is disabled.

## Expected Behavior

It should not be possible to create a custom tab, without a title.
(or, a title should be mandatory, when creating a white label custom tab.)

## Actual Behaviour

It is possible to create a custom tab, without a title.
(a title is not  mandatory, when creating a white label custom tab.)

## Steps to Reproduce

As a hub

1. Visit the White label section
2. Check the checkbox: `Create custom tab in shopfront`
3. Leave the section `Title for custom tab` empty
4. Add some content to the `Content for custom tab` section
5. Click `Update`
6. Notice the Checkbox selected on point 2; it is disabled, but the empty custom section appears anyway

As a customer

1. visit the shop
2. Notice the empty (custom) section; click on it
3. Notice the custom content will be displayed

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/319f7daa-8a4b-4c80-91ac-b117f07cb0bc)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/bb877c6f-7ef0-47c5-b667-16e7b8171726)

## Workaround

None, the user can't disable the tab. 

## Your Environment

* Version used: v4.3.11
* Browser name and version:  Firefox 113
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by aaronhirtenstein** [comment]
Flower Grower Collective just came up against this issue where the custom tab title had been enabled and was too long so when the user tried to save another setting on the account, it got an error message saying "Custom tab title is too long (maximum is 20 characters). 
The user didn't know where this field was and we spent ~20 minutes looking for it. In the end, I searched github and found this issue and was able to disable the custom tab (unclear what it's for so decided we don't need it). 
A simple fix for this would be to add the name of the tab where the field is located in the error message. Possible?
