### ISSUE TITLE
no ssl certificate on noticeboard.openfoodnetwork.org.au

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1094]
I think that's what this is . . 

I logged in at ofn first, and then hit the notices link 
![image](https://cloud.githubusercontent.com/assets/2911176/16675090/43297752-4501-11e6-96c8-55b21f500268.png)

**Comment by kirstenalarsen** [comment]
@daniellemoorhead - need to check w you how I should be using github e.g. how i should be labelling this etc. For now I have just flagged as Australia so I can keep track of it as being connected to 'aus re-launch' but happy to do something else if necessary

**Comment by mkllnk** [comment]
@kirstenalarsen Please test again and close the issue if it all works. :-)

This issue is not code related and shouldn't go into the release notes.
