### ISSUE TITLE
Missing translation: invalid URL

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10957]
## Description

Follow-up from #10922: this PR introduced a validation on custom URLs. Invalid URLs trigger a visible missing translation error message.

## Expected Behavior

An invalid URL validation should trigger a translatable message.

## Actual Behaviour

An invalid URL validation ~~should~~ does not trigger a translatable message. (edited)

## Steps to Reproduce

1. Add a custom image, on the White label section of an enterprise dashboard
2. Add an invalid URL to that image
3. Click Update.
4. See the missing translation error

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/a8e78eb2-b454-4389-8c43-a3c02c20621e)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.3.11
* Browser name and version: Firefox 113
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.

**Comment by filipefurtad0** [comment]
Hi @tarunsamanta2k20 :wave: 
I've assigned you to the issue.
Thanks!

**Comment by lin-d-hop** [comment]
Hi @tarunsamanta2k20 
How are you getting on with this issue? Let us know if you need some help :)

**Comment by tarunsamanta2k20** [comment]
@lin-d-hop Expected Behavior and actual behavior are the same.

**Comment by filipefurtad0** [comment]
> Expected Behavior and actual behavior are the same.

@tarunsamanta2k20 Thanks - now edited, hope the scope is clear now ;-)
Still up for working on the issue?

**Comment by tarunsamanta2k20** [comment]
> > Expected Behavior and actual behavior are the same.
> 
> @tarunsamanta2k20 Thanks - now edited, hope the scope is clear now ;-) Still up for working on the issue?

So, your actual behavior should UI doesn't display any errors even if the URL is invalid.

**Comment by filipefurtad0** [comment]
> So, your actual behavior is that UI doesn't display any errors even if the URL is invalid.

Hum, no: we do see a message - as shown on the picture - but the message is not translatable to other locales.

**Comment by jibees** [comment]
Hi @tarunsamanta2k20 👋 

After some weeks, I'll assign you from this issue, in order that another can tackle this one. Thanks! 😊
