### ISSUE TITLE
Error when rendering Order Cycle Supplier Totals Report

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10950]
## Description

Since v4.3.11 we have several occurrences on Bugsnag when rendering Order Cycle Supplier Totals Report. Some seem user-facing (US):

https://app.bugsnag.com/yaycode/openfoodnetwork-usa/errors/647f528712e81a000885d850?event_id=647f528700be0bc8d94e0000&i=sk&m=nw

Others don't, and rather look sidekiq related (FR), which I guess occur with the asynchronous rendering and email sent per email:

https://app.bugsnag.com/open-food-france/coopcircuits/errors/647f72568f1f900008ec0692?event_id=647f78d100be04a9f09b0000&i=sk&m=fq

In all cases the offending line is the same:

https://github.com/openfoodfoundation/openfoodnetwork/blob/1c9a09d88dc5379f698ee3df746447b5dca7cffc/app/services/variant_units/variant_and_line_item_naming.rb#L38

This has been introduced on this PR #10812.

## Expected Behavior

User should be able to render Order Cycle Supplier Totals Report.

## Actual Behaviour

User can't render Order Cycle Supplier Totals Report.

## Steps to Reproduce

Can't reproduce it for now. There is something about the products/variants which prevent rendering of the report.

## Animated Gif/Screenshot

?

## Workaround

?

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.3.11
* Browser name and version: ?
* Operating System and version (desktop or mobile): ?

**Comment by filipefurtad0** [comment]
This is related as well:

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/647c8b82ded5750008fb49dd?event_id=6480574600be0984acff0000&i=sk&m=nw

**Comment by sigmundpetersen** [comment]
Marked as S2 until proved otherwise

**Comment by abdellani** [comment]
A good issue to tackle after a long pause with reports : )

**Comment by jibees** [comment]
Seems like we do have an important client that suffering from this issue and needs report for tomorrow. Do you think of any workaround I can do?

**Comment by jibees** [comment]
Sorry, I confused two issues... It's not that one!
