### ISSUE TITLE
[Orders page] Uncaught Error: Missing target element "tooltip" for "tooltip" controller - missing Ship order Icon

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10956]
## Description

Capturing a payment triggers the error:

```
          Ferrum::JavaScriptError:
            Error: Missing target element "tooltip" for "tooltip" controller
                at extended.get (http://127.0.0.1:43907/packs-test/js/admin-b37e4fa00b2104ec0263.js:49200:15)
                at _this.showTooltip (http://127.0.0.1:43907/packs-test/js/admin-b37e4fa00b2104ec0263.js:3946:13)

```

This makes specs fail and hides the ship order icon, which was previously visible

## Expected Behavior

Tooltip for the ~~edit~~ shipping orders icon should be visible for as before.

## Actual Behaviour

Tooltip for the ~~edit~~ orders icon is not visible.

## Steps to Reproduce

1. As a hub, visit the /orders page; open the console.
2. Mouse-hover on the pencil icon. Notice the missing tooltip.
3. Capture a payment -> this should trigger the error on the console

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/d5b2e91c-b06c-447b-abdb-977d79c91083)

## Workaround

None, I guess.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.3.11
* Browser name and version: Firefox 113
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by jibees** [comment]
Hi @filipefurtad0 ! 
Did you manage to replicate this issue? I can't find any way to reproduce it. 

I will push a PR to add the tooltip for Edit button, but I wasn't able to see that particular error.

**Comment by filipefurtad0** [comment]
Hey @jibees ,
I could reproduce it with a spec (#10971). Interesting that you can't observe it. Maybe this is browser dependent?

**Comment by filipefurtad0** [comment]
Ok, I can reproduce it on the spec, by clicking the capture payment icon:

`find(".icon-capture").click`

If I do so, I get one of two errors:
```
Error: Error: Missing target element "tooltip" for "tooltip" controller
    at extended.get (http://127.0.0.1:43083/packs-test/js/admin-851201efbab0711ebeb5.js:28852:15)

```

Or the one below, if I add a `sleep(1)` after the click:

```
          Ferrum::JavaScriptError:
            Error: Missing target element "tooltip" for "tooltip" controller
                at extended.get (http://127.0.0.1:35879/packs-test/js/admin-851201efbab0711ebeb5.js:28852:15)
                at _this.hideTooltip (http://127.0.0.1:35879/packs-test/js/admin-851201efbab0711ebeb5.js:3886:13)

```
Do you think this should be added to the spec @jibees ? I was not able to assert on this content.

**Comment by filipefurtad0** [comment]
This is strange...
I'm observing this issue again:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/c8cc8078-a335-406f-8216-479b552c9d08)

We even see the missing shipping icon.
This was fine while testing... I'll need to re-open it :confused:

**Comment by filipefurtad0** [comment]
Steps to reproduce are basically the same as above:

Capturing the payment triggers:
```

          Ferrum::JavaScriptError:
            Error: Missing target element "tooltip" for "tooltip" controller
                at extended.get (http://127.0.0.1:43907/packs-test/js/admin-b37e4fa00b2104ec0263.js:49200:15)
                at _this.hideTooltip (http://127.0.0.1:43907/packs-test/js/admin-b37e4fa00b2104ec0263.js:3950:13)
```

After this, the shipping icon is missing... (added to the description).
