### ISSUE TITLE
[White label] Remember custom tab activation after error message

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10975]
## Description

If the custom tab can't be created due to a blank title, then the app should remember to show the custom tab setting as active, so the user can add the required title.

## Expected Behavior

After the error message the user visits the white label settings and the custom tab setting is still activated.

## Actual Behaviour

After the error message the user visits the white label settings and the custom tab setting is deactivated.

## Steps to Reproduce

1. Try to create a custom tab without title (or delete the existing title).
2. Click update.
3. See the error and return to the white label settings.
4. Check the checkbox for the custom tab.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/bf6b6792-4ed2-4fb5-b38e-c3cdb7a942cd

## Workaround

Activate the checkbox first to correct the error then.

## Severity
Not yet in production.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
As far as I know, it's not related to white label, but the whole settings page has the same behavior.

**Comment by drummer83** [comment]
Sorry, @jibees, maybe I was not clear.
I know that we have the issue of always being redirected to the 'Primary Details' in the enterprise settings. I think there is an issue for this already. 
Here I mean that the checkbox setting for 'Create custom tab in shopfront' is forgotten after the error. 
1. Activate the .
2. Leave the title empty (or delete the existing title).
3. Click update.
4. See the error message and the redirection to the 'Primary details' page (this a known issue).
5. Return to the white label settings.
6. See that the 'Create custom tab in shopfront' checkbox is now deactivated (even though it was activated before clicking 'Update').

Do you know what I mean? It's really confusing usability. 
    Check the checkbox for the custom tab.

**Comment by jibees** [comment]
Ok, I understood. Sorry for the confusion!
