### ISSUE TITLE
[Subscription order] Payment processing fails

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10973]
## Description

Bugsnags point to the code introduced in this PR:

Payment processing is failing when the order cycle closes. Subscription confirmation emails should arrive.

- This Bugsnag was triggered in master/staging-AU, upon closing of an order cycle:
https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64830a49ce03a0000856bf2a?filters[event.since]=30d&filters[error.status]=open

- This Bugsnag was triggered by testing in master/staging-UK, following the [test procedure](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Testing-Subscriptions):
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/64834ac1357cad00088b0b77?event_id=64834ac100be3ce87c500000&i=sk&m=nw

~~The code points to PR #10940.~~

## Expected Behavior

Payment processing should be successful. Subscription confirmation emails should arrive.

## Actual Behaviour

Payment processing is not successful on subscription orders. Subscription confirmation emails do not arrive.

## Steps to Reproduce

1. As a customer, set up a 3DS or 3DS2 card for a shop
2. As a hub, set up a subscription for that customer, using Stripe as a payment method
3. [Test subscriptions with the procedure](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Testing-Subscriptions)

## Animated Gif/Screenshot

-

## Workaround

-

## Severity

Not in production, would be at least an S2 regression

## Your Environment

* Version used: current master and v4.3.12 (not in prod yet)
* Browser name and version: Not relevant
* Operating System and version (desktop or mobile): Reproduced in staging-UK

**Comment by Matt-Yorkley** [comment]
Hmmm deep in the middle of that stack trace is:
```
Caused By: NameError · uninitialized constant Spree::LocalizedNumber
```

**Comment by Matt-Yorkley** [comment]
I think the quick fix for this (without going into any deep explorations of what seems to be an esoteric class-loading issue) is to just slap one of these at the top the `Spree::Payment` class:
```ruby
require "spree/localized_number"
```

**Comment by filipefurtad0** [comment]
Hey thanks @Matt-Yorkley.

Hum. Indeed, I've staged the PR pointing to a commit before PR https://github.com/openfoodfoundation/openfoodnetwork/pull/10940 to double check this, and the bug still occurs... I'll remove references to #10940 for now as this seems misleading.

> is to just slap one of these at the top the Spree::Payment class

That sounds like an uncontroversial change :-)

**Comment by filipefurtad0** [comment]
Anyway, after staging [#10936](https://github.com/openfoodfoundation/openfoodnetwork/commit/7974e1eaa6ac14c92e948b8424d949c0e3dc2cc8) / https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/4484 subscription job works again.

So it actually looks like the offending commit was https://github.com/openfoodfoundation/openfoodnetwork/commit/7974e1eaa6ac14c92e948b8424d949c0e3dc2cc8 / PR #10936...

**Comment by Matt-Yorkley** [comment]
Hmmmm... but that commit doesn't change anything related to either subscriptions or loading the `LocalizedNumber` module? I'd expect it to maybe come (indirectly) from recent changes in two different PRs that modified which classes do or don't declare `require "spree/localized_number"`...

Anyway, it's fixed :+1:
