### ISSUE TITLE
Missing tab title for 'OIDC settings' 

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10982]
## Description

OIDC is an abbreviation and should be written with capital letters. ~~In admin style v3 it is currently displayed with just a capital O.~~

## Expected Behavior

Use 'OIDC settings' in the navigation.

## Actual Behaviour

It's 'Oidc_settings'.

## Steps to Reproduce

1. Activate admin_style_v3 feature toggle.
2. Select 'Enterprises' from the primary navigation.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/255d4775-755f-4686-a7ab-c8e53fee158d)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
<img width="432" alt="Capture d’écran 2023-06-12 à 09 14 15" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/f1b2cfe3-8fa3-4373-b1bd-3aa0c1813672">

Actually this is not exactly related to admin_style_v3 (but maybe it's even worth). The key is not translated. 
Will open a PR.
