### ISSUE TITLE
funny wrapping on description text on groups page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1099]
![image](https://cloud.githubusercontent.com/assets/2911176/16975164/33187536-4e87-11e6-9b54-59c2c603c665.png)

**Comment by RachL** [comment]
@kirstenalarsen do you remember what you've meant by this issue?

**Comment by kirstenalarsen** [comment]
I think I just meant the the text could be taking up more horizontal space and therefore less vertical - seemed like it was wrapping unnecessarily early?

**Comment by lin-d-hop** [comment]
We're not going to act on this! #gitcull
