### ISSUE TITLE
[BUU] See variants for my products

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11005]
## Context
In this story we are building on top of https://github.com/openfoodfoundation/openfoodnetwork/issues/10694 to display the variants for each product in the table.

## Out of scope
- edit variants
- add new variants

## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** see the variants in my catalogue
**- So that:** I can review what I am selling and its stock levels

## Acceptance Criteria & Tests

**Scenario 1: Seeing variants - single enterprise**
Given I have one enterprise only
And I have products in my catalogue
And I am in `/admin/products`
And the page is loading my catalogue
When my catalogue has been loaded successfully
Then I see the list of my products ordered by name
And within each product I can see its variants

## Columns and fields to be displayed

Note 1: these are in display order, and include the ones that are product specific. The only new column to be added for now is Price.

Note 2: available on and import date don't need to be displayed, as per https://github.com/openfoodfoundation/openfoodnetwork/issues/10694

| Column | Display for single enterprise| Display for multiple enterprises | Mandatory | Display style & format |
| --- | --- | --- | --- | --- |
| Name | Yes | Yes | Yes | Semibold, left aligned |
| SKU | Yes | Yes | No | Regular, right aligned |
| Unit type - **EXCLUDE ITEM LABEL** | Yes | Yes | Yes | Regular, right aligned |
| **Price** | Yes | Yes | Yes | Regular, right aligned |
| On hand - DISPLAY ON DEMAND IF ALL VARIANTS ARE ON DEMAND | Yes | Yes | Yes | Regular, right aligned |
| Producer | NO | Yes | Yes | Regular, left aligned |
| Category | Yes | Yes | Yes | Regular, left aligned |
| Tax category | Yes | Yes | No | Regular, left aligned |
| Inherits properties - **DISPLAY AS YES / NO** | Yes | Yes | Yes | Regular, left aligned |
| ~~Available on~~ | ~~Yes~~ | ~~Yes~~ | ~~Yes~~ | ~~Regular, right aligned, YYYY-MM-DD~~ |
| ~~TBD - Import date~~ | ~~Yes~~ | ~~Yes~~ | ~~No~~ | ~~Regular, right aligned, YYYY-MM-DD~~ |

## Design specs

The screen for specs is here
https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?type=design&node-id=267%3A832&t=hO5rg4YoMVz0lMCY-1

**New components and styles**
More info on tables is available here https://github.com/openfoodfoundation/openfoodnetwork/wiki/Design-system.

| Component | Example |
| --- | --- |
| Table row with condensed height | ![Screenshot 2023-06-14 at 11 39 37](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/67254f9b-a023-4a29-8610-539d0b904835)
|

**Comment by dacook** [comment]
Work in progress. The drop shadow will require further thought to accomplish.
![Screen Shot 2023-06-16 at 5 02 56 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/25c831aa-cda7-43c7-ab7e-f514767b284d)


I notice that some of the columns for variants are repeats of the product (they cannot be different to the product as far as I know):
* supplier
* category
* inherits properties

Perhaps this will change in the product refactor though; I don't know.

**Comment by dacook** [comment]
> Producer	Display for single enterprise    NO 

For the hiding of the producer column, I think we should leave this until we get to the UI for hiding/showing columns. 
I can foresee a small issue when saving user preferences, if the user filters to only one producer, the column hides, the column preferences are saved, then later they are veiwing multiple producer but the column stays hidden as per the preference.

**Comment by dacook** [comment]
Hi @mariocarabotta, I implemented the unit name to appear on the product line like "Weight (kg)", but noticed that variants of the same product can have different scales (g vs kg). 
![Screen Shot 2023-06-22 at 2 27 40 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/f80fad62-beec-48ef-b61a-a205e7443b86)


So I moved the unit to the variant rows like this:

![Screen Shot 2023-06-22 at 2 25 00 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/4da2e960-3c2c-42a8-84af-eb30fc3ea8bb)


Now I can see the word "Items" repeating, which I can see you were intending to avoid.

I think we can differentiate between measurements (weight/volume) and "item"-based labelling. So measurements can show as per the first screenshot above, and items can show as per the second.

**Comment by dacook** [comment]
PS here's some bigger screenshots showing the styling of the whole table:
![Screen Shot 2023-06-22 at 2 42 26 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/950f738a-c92a-48cd-a6db-6c789b61c607)
![Screen Shot 2023-06-22 at 2 42 38 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/94afd43b-357c-422b-8c7f-27e7fdbdc96a)

**Comment by dacook** [comment]
PS I think it will be possible to achieve proper dropshadows, by stepping away from the standard table layout and using another layout (eg think `<div>` instead of `<table>`). I wanted to avoid that in case of unforeseen problems, but I think it's probably ok.

**Comment by drummer83** [comment]
This looks nice! 😊

Just a comment I would have made during testing anyway: Can we please add a whitespace between numbers and units, like `12 kg`. To my knowledge it's an international standard.
I know we are not doing this in other places of the app, but we should move in this direction. 🙏

**Comment by dacook** [comment]
That's interesting, I hadn't thought of that, thanks! It would be good if we could find a reference to the standard. If it's a regional preference, it might be possible to internationalise this with a translation ...but maybe we don't want to complicate things..

**Comment by kirstenalarsen** [comment]
This looks great - exciting! A note on the units . . is there a thing aoubt special unit adjustment e.g. g - kg etc that would mean we need to display the actual unit on each variant? 

e.g. if I have a product set as 'kg' but I put the value in as 0.4 then it automatically turns this into 400g (see below). So I think we need to have the unit on each line? 

Sorry I didn't pick this up earlier
<img width="590" alt="image" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/2911176/3797b9fd-de7d-406f-b2b4-9f6adf11f3e7">

**Comment by kirstenalarsen** [comment]
Shit. this makes me realise that we also have this magical thing where we have the 'auto-generated' variant name, that the user can overwrite if it's not correct. This is how we have dealt with giving people the flexibility they need in unit types / descriptions etc. I think it is quite important. 

It is also important in the "Items" that we have the field where they get to name the item e.g. 'dozens' or 'boxes'

**Comment by drummer83** [comment]
> It would be good if we could find a reference to the standard. If it's a regional preference, it might be possible to internationalise this with a translation ...but maybe we don't want to complicate things.

The standard is the SI = Système International defined by the BIPM = Bureau International des Poids et Mesures. References can be found 
- in their official publication (chapter 5.4.3): https://www.bipm.org/documents/20126/41483022/SI-Brochure-9.pdf
- in Wikipedia: https://en.wikipedia.org/wiki/International_System_of_Units#General_rules
- at NIST (see no. 15): https://physics.nist.gov/cuu/Units/checklist.html

**Comment by dacook** [comment]
Thanks Konrad, it's amazing how much is specified! Given the international standard, it would make sense to use that. However I just checked my pantry and all food packets have no space between the  number and unit, so I think it's fair to say there would be a regional preference (and personally I think it looks better, and has the advantage of being easier to copy/paste without being separated). 
Is this a topic for the forum?

**Comment by dacook** [comment]
Kirsten you're right, we have many different ways to configure how this is displayed (and the code is incredibly complex already!). As we can see in the existing bulk product edit screen, some things are automatically generated and appear as placeholders in a field where we can overwrite them.

So, as a general rule I think we should refer to and copy the existing product screen, and as I write this I remember this is what Mario has already told me to do. I think I just mis-interpreted the design and carried myself off in the wrong direction. So all good, ignore me...

**Comment by drummer83** [comment]
> Given the international standard, it would make sense to use that. However I just checked my pantry and all food packets have no space between the number and unit, so I think it's fair to say there would be a regional preference (and personally I think it looks better, and has the advantage of being easier to copy/paste without being separated).
> Is this a topic for the forum?

I have just checked my pantry as well and here the space is being used. And my eye thinks it's nicer with the space - probably it depends on what your are used to. So, indeed it seems like a regional thing...
By 'forum' you mean Slack or Discourse? Sure, let's discuss and decide there.

**Comment by mariocarabotta** [comment]
thanks everyone for the feedback! I would suggest for these observations to be documented once we get to an agreement on how to display this type of data, used in many parts of the software.
Also, for @dacook , we might want to document somewhere which fields are coming straight from the backend as they are, and which ones are modified in the front end..it might be handy to know that down the track

**Comment by dacook** [comment]
I'm never quite sure how to progress feature suggestions, but this time I've created a new discourse topic: https://community.openfoodnetwork.org/t/display-weight-and-volume-units-with-space-as-per-international-standard/2832
