### ISSUE TITLE
spacing in producer / hubs lists on group page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1100]
lots of wasted space and long names not wrapping, looks funny  . . 

![image](https://cloud.githubusercontent.com/assets/2911176/16975262/f7b40be4-4e87-11e6-93d8-0ed61daf40e3.png)

**Comment by lin-d-hop** [comment]
UX redesign will need to be prioritised in discourse. #gitcull
