### ISSUE TITLE
accidentally scrolling map on group page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1101]
is it possible to make the mouse scroll move the page until you click on the map (or something?)

Currently you land on the page and scroll down past the banner, which lands you on the map and starts zooming, when what you're really trying to do is just get down to the map

![image](https://cloud.githubusercontent.com/assets/2911176/16975765/f579ae1a-4e8c-11e6-8332-21f5e174d831.png)

**Comment by lin-d-hop** [comment]
Map UX will need to be prioritised in discourse. #gitcull
