### ISSUE TITLE
[Flaky] Redis::CommandError: ERR Protocol error: too big inline request 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11021]
### What we should change and why (this is tech debt)

Merging the latest redis bump https://github.com/openfoodfoundation/openfoodnetwork/pull/10455 seems to have introduced flakyness in a number of specs, which fail with the same error:

```
      Failure/Error: raise Client::ERROR_MAPPING.fetch(event.class), event.message
     
     Redis::CommandError:
       ERR Protocol error: too big inline request
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/issues/11010#issuecomment-1592400646
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5276188680/jobs/9542574284
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5276188680/jobs/9542574284

**Comment by filipefurtad0** [comment]
Ok, I'll signal this one as an S2 for investigation, and so we don't keep track of it - and move it to Dev Ready.

**Comment by Matt-Yorkley** [comment]
There's an open issue for this in the redis gem repo (with the same error and backtrace), and the other person reporting it likewise says it's intermittent and quite rare and they can't reproduce it manually...

**Comment by filipefurtad0** [comment]
> other person reporting it likewise says it's intermittent and quite rare

Ok, not on our side, and rare - back to all the things :ok_hand:

**Comment by Matt-Yorkley** [comment]
I just pushed a branch and two tests randomly failed due to this error. I'm wondering if we should revert those changes for now?

**Comment by filipefurtad0** [comment]
@mkllnk just did that [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/11033), I think we can close this issue.
