### ISSUE TITLE
[White label, Trix] Bullets and numbers are not displayed in shopfront (custom tab)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11024]
## Description

Even if numbers or bullets are entered in the Trix editor for the content of the custom tab, these are not displayed in the shopfront.

## Expected Behavior

Numbers and bullets should be shown in the shopfront.

## Actual Behaviour

Numbers and bullets are not displayed in the shopfront.

## Steps to Reproduce

1. Activate the Custom Tab in the White Label settings.
2. Enter a title.
3. Use numbers and bullets in the content text field.
4. Click update.
5. Look at the custom tab in the shopfront.

## Animated Gif/Screenshot

Editor:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/e1c5a6b2-2dee-4a94-a993-d9206fb4aa67)

Shopfront:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/3c13dfff-fe6c-41a1-af01-7e015c2c7dc6)

## Workaround

Use whitespaces and write the numbers yourself or use the dash for bullets.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
I should have done this one with #11025 
Wait for it to be merged now.

**Comment by jibees** [comment]
Finally, as a small modification only necessary, #11282 will also close this one.
