### ISSUE TITLE
Enterprise E2E link management - tab in enterprise mgmt would make this a lot more obvious

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1103]
![image](https://cloud.githubusercontent.com/assets/2911176/16976367/97f100d6-4e91-11e6-82a2-3277c6ed7692.png)

**Comment by myriamboure** [comment]
Iceboxed https://community.openfoodnetwork.org/t/hubs-can-easily-navigate-back-office-and-manage-their-shopfront/1246
#gitcull2018
