### ISSUE TITLE
[Invoices] Bulk invoice printing is showing endless spinner (Bugsnag)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11046]
## Description

Follow up of #10532.

When printing invoices in bulk there is an endless spinner and the invoices are not printed.
Here is the related bugsnag: https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/648834087e655d000884c36e?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open&filters%5Bapp.release_stage%5D=staging

## Expected Behavior

Print invoices.
No Bugsnag.

## Actual Behaviour

No invoices.
Bugsnag.

## Steps to Reproduce

1. Select one or more orders in the orders list.
2. Select 'Print invoices' from the actions dropdown menu.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by abdellani** [comment]
This was expected because we didn't decide what should happen when this button is clicked.

Each order falls in one of the following cases:
1. The doesn't have any invoice yet. In this case, we can list the following sub-cases: 
a. the order completed/resumed
b. the order is not completed yet
c. the order is canceled

2. The order has at least one invoice. In this case, we have:
a. the order is not updated since the last invoice.
b. the order is updated since the last invoice, and the changes will require regenerating the latest invoice.
c. the order is updated since the last invoice, and the changes will require generating a new invoice.

**Comment by drummer83** [comment]
Ok, I see. In my opinion we should do the following:

Each order falls in one of the following cases:
1. The doesn't have any invoice yet. In this case, we can list the following sub-cases: 
a. the order completed/resumed :arrow_right: **create invoice and send it**
b. the order is not completed yet :arrow_right: **do nothing**
c. the order is canceled :arrow_right: **do nothing** (because current invoices are not displaying that the order was cancelled)

2. The order has at least one invoice. In this case, we have:
a. the order is not updated since the last invoice. :arrow_right: **send invoice**
b. the order is updated since the last invoice, and the changes will require regenerating the latest invoice. :arrow_right: **update invoice and send it**
c. the order is updated since the last invoice, and the changes will require generating a new invoice. :arrow_right: **create invoice and send it**

Once again I think that we should disable the checkbox for orders which are not complete because ALL bulk actions we are providing only make sense for completed orders (https://github.com/openfoodfoundation/wishlist/issues/261#issuecomment-1377933112).

I'm not sure about the 'resumed' state. Is this similar to 'completed' but for resumed orders? Or is it an intermediate state for resumed orders before they are going to completed? I believe the first option is the case.

**Comment by abdellani** [comment]
> Ok, I see. In my opinion we should do the following:
> 
> Each order falls in one of the following cases:
> 
> 1. The doesn't have any invoice yet. In this case, we can list the following sub-cases:
>    a. the order completed/resumed arrow_right **create invoice and send it**
>    b. the order is not completed yet arrow_right **do nothing**
>    c. the order is canceled arrow_right **do nothing** (because current invoices are not displaying that the order was cancelled)
> 2. The order has at least one invoice. In this case, we have:
>    a. the order is not updated since the last invoice. arrow_right **send invoice**
>    b. the order is updated since the last invoice, and the changes will require regenerating the latest invoice. arrow_right **update invoice and send it**
>    c. the order is updated since the last invoice, and the changes will require generating a new invoice. arrow_right **create invoice and send it**

:+1: 

> Once again I think that we should disable the checkbox for orders which are not complete because ALL bulk actions we are providing only make sense for completed orders ([openfoodfoundation/wishlist#261 (comment)](https://github.com/openfoodfoundation/wishlist/issues/261#issuecomment-1377933112)).

I agree :+1: 

> I'm not sure about the 'resumed' state. Is this similar to 'completed' but for resumed orders? Or is it an intermediate state for resumed orders before they are going to completed? I believe the first option is the case.

I also have the same opinion. Maybe @filipefurtad0  can confirm?
