### ISSUE TITLE
[Checkout, Mobile] No margin around buttons 'Login' and 'Checkout as guest'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11042]
## Description

When starting the checkout process as a non-logged-in customer on a mobile device (small screen), there is no margin displayed around the buttons 'Login' and 'Checkout as guest'. The design should be identical to the other buttons used during checkout.

## Expected Behavior

The design should be identical to the other buttons used during checkout, which means there should be a margin around the buttons.

## Actual Behaviour

There is no margin around the buttons.

## Steps to Reproduce

1. If you are logged in as a customer: log out.
2. Put items into your cart.
3. Click cart, then click checkout.
4. Look at the buttons 'Login' and 'Checkout as guest'.
5. Select Login.
6. Compare to the buttons 'Next - Payment method' and 'Back to Edit Basket'.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/41beaf4a-b715-4520-bb09-47cd7541a486

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by AbdelrahmanAbbas1** [comment]
I'd like to look into this issue

**Comment by drummer83** [comment]
Welcome, @AbdelrahmanAbbas1! I have assigned it to you.
Looking forward to your contributions! 😊

**Comment by AbdelrahmanAbbas1** [comment]
Sorry for the misconvenience but something came up and I can't look into
the issue

**Comment by drummer83** [comment]
Ok, no worries @AbdelrahmanAbbas1!
Let us know if you ever want to continue.
