### ISSUE TITLE
More detailed 'Shop Now' information in modals

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1105]
Enterprises may wish to share outlets/shops where customers can access their products, other than OFN shops. Their profiles don't have a dedicated place to do this currently, enterprises just have to write this information in their About Us text. Proposal is to have more diverse 'shop now' icons that capture retail shops, farm gate stalls, external online shops etc.

FULL DETAILS - http://community.openfoodnetwork.org/t/more-detailed-shop-now-information-in-modals/331/1

**Comment by RachL** [comment]
I moved this as a wishlist on Discourse. Closing here.
