### ISSUE TITLE
[Invoices] Time in the invoices list not set correctly

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11051]
## Description

Follow up of #10532.

The displayed time of the invoices in the invoice list always seems to be 12 a.m.

## Expected Behavior

The displayed time should be the time of invoice creation.

## Actual Behaviour

The displayed time is always 12 a.m.

## Steps to Reproduce

1. Create one or more invoices.
2. Look at the invoice list.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by abdellani** [comment]
That field is supposed to represent a date (without time).

**Comment by drummer83** [comment]
> That field is supposed to represent a date (without time).

Hmm, I agree to display the date only on the invoice. But I think as an enterprise manager I want to be able to see a time as well. Imagine I created an invoice and on the same day I need to change the order and create a new invoice. It can be helpful to know when those two invoices were created - especially if I need to track down a mistake in the order or on the invoice.

I assume the time information is there in the data base. So I'd vote for displaying it in the back office.

**Comment by abdellani** [comment]
> > That field is supposed to represent a date (without time).
> 
> Hmm, I agree to display the date only on the invoice. But I think as an enterprise manager I want to be able to see a time as well. Imagine I created an invoice and on the same day I need to change the order and create a new invoice. It can be helpful to know when those two invoices were created - especially if I need to track down a mistake in the order or on the invoice.
> 
> I assume the time information is there in the data base. So I'd vote for displaying it in the back office.

At this level, the database only stores the date without time  (the column's type is a `date`, not `datetime` ).

I'm not against the idea of showing time, but I remember that I read/heard a comment, during the early discussion of the feature, saying that we don't need to show time.
I tried to find that comment but I couldn't find it, and I don't even remember who is the owner of the comment :(

Anyway, we can easily do that by changing the column type. 
Waiting for the opinions of others.

**Comment by lin-d-hop** [comment]
My 2c.
Date only on the invoice.
In back office most important thing is displaying invoices in (reverse) order of creation. 
If adding the time in the back office takes zero effort, it's okay to include. But if it's difficult to include just displaying in order of creation is fine 

Let me know if that's not clear :)
