### ISSUE TITLE
[BUU] Change the number of products shown in my catalogue

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11054]
## Context
This issue enhances the display of the product list table #10694.

## Out of scope
- filter by producer or category #11057
- search for products https://github.com/openfoodfoundation/openfoodnetwork/issues/11056

## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** choose how many products to see
**- So that:** I can scan through as many products as I want

## Acceptance Criteria & Tests

**Scenario 1: 15 or less products - NICE TO HAVE**
Given that I am in `/admin/products`
And I have 15 or less products
When the page has loaded my products 
Then I see all of my products
And I don't see a picker to change how many products are displayed

**Scenario 2: More than 15**
Given that I am in `/admin/products`
And I have more than 15 products
When the page has loaded my products 
Then I see the first 15 products of my catalogue
And I see a picker to change how many products are displayed

**Scenario 3: Change n. of product to display**
Given I have more than 15 products
And the page has loaded my first 15 products
When I select a number different than 15 products to display
Then the table refreshes
And I see the number of products I have selected

Available options:
- 15 products (default)
- 50 products
- 100 products

**Scenario 4: Pagination**
Given I have selected a number of products to be displayed different from 15
And there are multiple pages of products available
When I move between pages of products
Then I always see the number of products that I have initially selected

**Scenario 5: Searching and filtering**
Given I have selected a number of products to be displayed different from 15
When I search for a product (and/or [filter](https://github.com/openfoodfoundation/openfoodnetwork/issues/11057))
Then I always see the number of products that I have initially selected

## Design specs
A prototype is available here > https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?page-id=373%3A2076&type=design&node-id=373-2077&viewport=625%2C637%2C0.62&t=1a6HPQf2tS4LA7rY-1&scaling=min-zoom&starting-point-node-id=373%3A2077&mode=design

Note: the re-loading behaviour is a concept work in progress for now - implementation might be different depending on what's more feasible.

Figma screens are available here > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?type=design&node-id=373%3A2076&mode=design&t=PlajwLujJOXIZIjx-1

**New components and styles**

| Component | Example |
| --- | --- |
| Regular simple dropdown closed | ![Screenshot 2023-07-12 at 14 53 12](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/84e10af2-791b-45b2-b116-08e7cc83c560) |
| Regular simple dropdown open - with current selection | ![Screenshot 2023-07-12 at 14 55 42](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/58a5df18-fd0b-4a79-9f02-a476a3b5712d)|

**Comment by jibees** [comment]
<img width="1376" alt="Capture d’écran 2023-07-03 à 11 22 12" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/5752c2e5-71ed-4ddf-b7ff-aecfcee26c73">
<img width="1380" alt="Capture d’écran 2023-07-03 à 11 22 20" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/cb4186a5-1d1d-432c-b4fd-8a6fc5048361">
<img width="1377" alt="Capture d’écran 2023-07-03 à 11 22 27" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/3d9e4dc9-3ff5-4cdf-a55a-ae725d275fd7">


Ready in https://github.com/openfoodfoundation/openfoodnetwork/pull/11007
