### ISSUE TITLE
[Invoices] Viewing an invoice with the instance's invoice setting set to alternative model leads to an error 500 (Bugsnag)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11050]
## Description

Follow up of #10532.

Trying to view/download an invoice on an instance with the invoice setting set to alternative model leads to an error 500.
Here is the Bugsnag: https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64883d4eb464420008d0d1ab?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open&filters%5Bapp.release_stage%5D=staging
Even if the new invoices are supposed to work for regular invoices only, there should be no error 500.

## Expected Behavior

Existing invoices should be viewable/downloadable independent of the invoice setting.
If the new invoices are available for standard invoices only, then instances with the alternative invoice model still need access to the legacy invoice functionality.

## Actual Behaviour

There is an error 500 if an invoice is downloaded/viewed on an instance with instance setting set to alternative model.

## Steps to Reproduce

1. As super admin set the invoice setting to alternative model.
2. Create an invoice on the invoice page.
3. Try to download/view it.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by abdellani** [comment]
Hi @drummer83 

I'm not familiar with the `alternative model`. 
I did a quick search on the repo and on the user guide but I didn't find anything.
Can you please explain?

**Comment by drummer83** [comment]
Hi @abdellani,

The invoice settings are explained in the OFN super admin guide, because it is a setting at instance level: https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ofn-platform-configuration/invoice-settings.

I think this will explain what it is about. If there are more questions, please reach out!

**Comment by abdellani** [comment]
Hi @drummer83 
I was not able to reproduce the issue.
I shared all the steps that I followed to reproduce the issue.
Can you please check if I missed something?
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/e5413583-25bf-44f0-b7a9-37b001bca918)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/d79af396-9c7d-4292-8970-c9ce033af0b7)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/d2a8f905-639c-45de-809b-2b06a421fe78)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/cda5be8c-89bb-4193-9c00-fa2b2da5a898)

**Comment by abdellani** [comment]
Oh, I was able to reproduce it now. In only happens, when there're tax rates on the order.
