### ISSUE TITLE
[BUU] Search for a product

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11056]
## Context
This issue enhances the display of the product list table #10694.

## Out of scope
- filter by producer or category #11057

## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** search for products in my catalogue
**- So that:** I can find the product I am looking for

## Acceptance Criteria & Tests

**Scenario 1: Active search field**
Given that I am in `/admin/products`
And the page has already loaded my products
When I select the search field
Then the search field becomes active
And I can type my text query in it

**Scenario 2: Trigger search**
Given I have typed my query in the search field
And the query is valid
When I trigger searching (keyboard enter or pressing the button)
Then the system searches for products containing that query
And the table is replaced by a loading indicator

**Notes to explore: pasting text, enabling emojis/special characters, what fields is the system searching in (only product title? variants titles? product description? etc..)**

**Scenario 3: No results**
Given I have triggered a search in my catalogue
And there are no products matching that query
When the system responds to my request
Then I see message telling me that there are no results for my search

**Scenario 4: Clear search on no results**
Given there are no results for my search
When I clear my search
Then I see my catalogue with all the products

**Scenario 5: Search with results**
Given I have triggered a search in my catalogue
And there are products matching that query
When the system responds to my request
Then I see the list of products that match that query

**Scenario 6: Search with results - multiple pages**
Given I have triggered a search in my catalogue
And there are more than 25 products matching that query
When the system responds to my request
Then I see the list of products that match that query
And pagination at the bottom of the list

**Scenario 7: Move to next page**
Given there are more than 25 products in my search results
When I click on the next page button in pagination
Then the catalogue loads the following 25 products in the list of search results for my query

## Design specs
A prototype is available here > https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?page-id=346%3A903&type=design&node-id=346-1000&viewport=657%2C461%2C0.16&t=gG17pR0ejGmiUT88-1&scaling=min-zoom&starting-point-node-id=346%3A1000&mode=design
Figma screens are available here > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?type=design&node-id=346%3A903&mode=design&t=W6f7NFDHptqN9Fh7-1

**New components and styles**

| Component | Example |
| --- | --- |
| Relaxed text field | ![Screenshot 2023-07-05 at 14 55 44](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/6f29d839-5521-444b-a7b8-9cd5f973016b) |
|Relaxed secondary button| ![Screenshot 2023-07-05 at 14 56 06](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/5f07c267-7601-44fe-859e-413f4426eaff)|
|Regular secondary button disruptive|![Screenshot 2023-07-05 at 14 56 14](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/1a1b511e-edba-41fb-a965-e8e1aff33706)|
|Relaxed secondary button disruptive| ![Screenshot 2023-07-05 at 14 56 22](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/ccf93a23-31c0-494a-9dde-27f11743ecbb)|

**Comment by jibees** [comment]
<img width="1416" alt="Capture d’écran 2023-07-03 à 11 20 43" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/ec7d72a2-6c37-4177-b294-d2fa446575b1">
<img width="1452" alt="Capture d’écran 2023-07-03 à 11 20 52" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/f5aea2bf-3ff9-40a1-b075-5286d3703cda">


Ready in https://github.com/openfoodfoundation/openfoodnetwork/pull/11007

**Comment by jibees** [comment]
<img width="1410" alt="Capture d’écran 2023-07-05 à 14 12 35" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/8f24f774-7add-4ec8-9572-576a089d194d">
<img width="1409" alt="Capture d’écran 2023-07-05 à 14 12 41" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/cbb8917d-e705-483e-93bf-4af6fe56d512">

"Clear search" button is ready!

**Comment by jibees** [comment]
I (for now) did not complete the "23 results for 'yogourt'", and "No products found for 'yoooogour'" since results/no results can be found/not found via many filters (not only searched term)

**Comment by mariocarabotta** [comment]
> I (for now) did not complete the "23 results for 'yogourt'", and "No products found for 'yoooogour'" since results/no results can be found/not found via many filters (not only searched term)

Created a separate issue to cover those scenarios - will pick it up after we implement the filters https://github.com/openfoodfoundation/openfoodnetwork/issues/11197
