### ISSUE TITLE
[Invoices] Invoice number not visible on the invoice

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11052]
## Description

Follow up of #10532.

The invoice number is not visible on the invoice.

## Expected Behavior

The invoice number should be visible in the header of the invoice.

## Actual Behaviour

It's not visible.

## Steps to Reproduce

1. Create an invoice.
2. Look at it.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by abdellani** [comment]
I just re-implemented the invoice template to support the invoice presenter (instead of the order model)

Where is it supposed to appear?

I suggest before the invoice's generation date
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/989df941-efbf-439f-8c7c-d75045b60a2f)

**Comment by drummer83** [comment]
Ok, first of all, let's wait for an answer [here in Slack](https://openfoodnetwork.slack.com/archives/C04MR8R7078/p1687703065474749) to see which invoice template(s) should be updated.

After that my question would be: 
- A: Will we still have the old order numbers R123456789 and the invoice number is additional information?

OR
- B: Will we only have the invoice number and order numbers won't be used anymore?

If A, we need to display BOTH information. I agree to your proposal on the standard invoice template. For the alternative template I would propose to add it above the invoice issue date as well and rename invoice number to order number (see image below).
If B, we can simply replace the current order number. 

Alternative invoice template with invoice number and order number displayed.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/7178a4d5-8472-4a13-a831-25fc368a23bc)

**Comment by lin-d-hop** [comment]
Hiya, I will do my best to answer, though this is the first I'm looking at this.

We do need both Order Number and Invoice Number on the invoice.

I like the display you have given @drummer83. That seems right to me.
I would like to do something similar on the standard invoice template - in fact I think the header of the alternate invoice template is just better. Something like:

```
### Tax Invoice
Issued On:
Order Number:
Invoice Number:
```
