### ISSUE TITLE
[BUU] Change unit number and unit display

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11061]
![Screenshot 2024-03-13 at 3 19 38 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/9e0ab96c-5f49-42aa-ba3d-008b1b01240a) | ![Screenshot 2024-03-13 at 3 22 06 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/0b3942eb-5ee1-41ce-b2fa-144edd712464)

- on click show overlay with numeric field pre-selected
- if display unit is empty, show placeholder as {number}{unit scale abbreviation}
- if item is selected in unit scale, show placeholder as {number} {item label}
- "display unit as" optional field
- if "display unit as" is filled, once clicking outside, display it in the column (rather than the numeric value)

🎨 Design prototype: [Units - Product List](https://www.figma.com/proto/ddL6h7H9It5ZmUuVYQxzAD/Product-List?page-id=874%3A30&type=design&node-id=874-2267&viewport=805%2C358%2C0.26&t=6jfW8boLyZ0pNeKn-1&scaling=min-zoom&starting-point-node-id=874%3A31)

**Comment by mariocarabotta** [comment]
estimate: 2 days

**Comment by dacook** [comment]
Estimate updated to 4 days.

I've done some more digging and discovered another feature in the current screen. I'll implement these technical requirements:

**When product weight/volume/items is selected** (variant_unit_with_scale):
1. Update hidden product fields variant_unit and variant_unit_scale based on dropdown selection (variant_unit_with_scale). See bulk_product_update_spec.js.coffee#L503
2. Variant **display_as** placeholder is updated by `OptionValueNamer` using onscreen variant/product data. See ofnDisplayAs

**When a variant unit value is updated** (unit_value_with_description):
1. Update hidden variant fields unit_value and unit_description from text field (unit_value_with_description). See bulk_product_update_spec.js.coffee#L564
