### ISSUE TITLE
'back to ofn aus' link logs me out of ofn

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1106]
When I am logged in on noticeboard and hit the 'back to ofn australia' link, it takes me to openfoodnetwork.org.au in same tab but has me logged out

![image](https://cloud.githubusercontent.com/assets/2911176/17048555/314f589c-502a-11e6-93f3-1eecabbfa5f2.png)

![image](https://cloud.githubusercontent.com/assets/2911176/17048560/3d469980-502a-11e6-87ed-4027ca7300d8.png)

If i open a new tab in same browser I am still logged in, so browser knows that I am logged in and must be be over-ridden somehow?

![image](https://cloud.githubusercontent.com/assets/2911176/17048578/5821b000-502a-11e6-9a99-1870feb80834.png)

any chance we can fix this by either
- fixing something in the link it's redirecting to in same tab
- just opening a new tab so that browser logged in state overrides?

@sstead @mkllnk - I am not at all across discussions, outstanding issues or testing of this stuff so apologies if I'm duplicating. I'm just going through process for launching this and picking up stuff that I think might trip people up. NOT scheduled for fix at this stage

**Comment by kirstenalarsen** [comment]
now that we have disconnected the logins, we should probably change the text to 'Take me to Open Food Network Australia' and make sure that it just picks up the login status of the browser . . so if they are already logged in then the new tab should log them in

**Comment by myriamboure** [comment]
@kirstenalarsen seems that this does not concern the Open Food Network platform, and given the end to end process we are putting in place this should not be managed in this GH repo (which is only about the common international platform, so local discourses not concerned). Could be in another repo for Aus website, or in a Trello task board, but not here ;-)

**Comment by myriamboure** [comment]
I don't delete it for now to let you see where you want to put it, just leave it in "all the things", please delete when you know how to manage that ;-)

**Comment by mkllnk** [comment]
This is actually a feature request for OFN. It would mean that OFN can accept logins from other websites. It's the Single-Sign-On feature for OFN.

**Comment by myriamboure** [comment]
Ok I opened a Wishlist item https://community.openfoodnetwork.org/t/single-sign-on/1173 for the single sign on, but it seems to me there might be another task for Aus team to just change the text to "take me to OFN Australia" meanwhile sso is up, no @mkllnk ? Ideally as I said those non OFN platform related things should be followed up somewhere else, don't know where, the instance should choose ;-) Can we close then or not? not sure...

**Comment by daniellemoorhead** [comment]
Closing this as it's not relevant for the global platform ATM. Note left in AU office so we don't forget it.
