### ISSUE TITLE
[BUU] Change stock levels including on demand

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11062]
## Context
This issue makes the On hand column interactive and introduces the On demand option.

## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** edit variant stock levels
**- So that:** I can sell amounts of produce that I actually have

## Acceptance Criteria & Tests

**Scenario 1: Expand dropdown**
Given that I am in `/admin/products`
And I have products in the list
When I click on the stock field for a variant
Then I see the option to change the number of variants and On demand
And the numeric field is active

**Scenario 2: Change stock number**
Given that the stock numeric field for a variant is active
When I change that value
Then I am warned that one product has been changed (as per #11059)

**Scenario 3: Click out**
Given that the stock numeric field for a variant is active
When I click outside of the dropdown
Then the dropdown closes
And any update is retained

**Scenario 4: Click out**
Given that the stock numeric field for a variant is active
When I click outside of the dropdown
Then the dropdown closes
And any update is retained

**Scenario 5: Select on demand**
Given that the stock numeric field for a variant is active
And on demand is not selected
When I select on demand
Then the numeric value is overruled

**Scenario 6: Deselect on demand**
Given that the stock numeric field for a variant is active
And on demand is selected
When I deselect on demand
Then the previous numeric value is again the actual stock level

Note: this applies also after saving. The numeric value is stored in the DB even when it's overwritten by on demand

**Scenario 7: Save**
Given that I have changed stock value
When I click save
Then the system tries to update stock level
And I see a loading screen

**Scenario 8: Remove stock level from product row**
Product rows should NOT display any data regarding stock.

## Design specs

Figma screens are available here > 
https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=708%3A5152&mode=design&t=iLLc5dirO5nzLB9j-1

Prototype here (open dropdown in first variant) > https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?page-id=708%3A5152&type=design&node-id=708-5153&viewport=278%2C123%2C0.33&t=HepYfjKLR82NcjTL-1&scaling=min-zoom&mode=design

**New components and styles**

| Component | Example |
| --- | --- |
| Disabled field (uses $porcelain | ![Screenshot 2023-09-19 at 11 18 24](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/773cbc3a-2067-4ac6-9324-67d8128ebdd2)|

**Comment by dacook** [comment]
Hi @mariocarabotta , I'm looking at getting started on this and reviewing the requirements. It all looks great and I can't think of any questions with the widget.  However:

> Scenario 8: Remove stock level from product row

I can see that currently, the variant stock level(s) are automatically summed up on the product row, so this would be losing a feature. Is that ok?
![Screen Shot 2023-11-10 at 1 38 11 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/c0c9c614-ca53-4f46-8cd0-bb48cc184bc4)

**Comment by mariocarabotta** [comment]
@RachL suggested to remove it [here](https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1695090255247689) :)
