### ISSUE TITLE
[BUU] Create a new variant inline

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11066]
## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** create a new variant quickly
**- So that:** I can expand my catalogue efficiently

## Acceptance Criteria & Tests

**Scenario 1: Show new row**
Given that I am in `/admin/products`
When my catalogue has loaded
Then I see a new row under the last variant of each product 

**Scenario 2: Hover**
Given that I am in `/admin/products`
When I hover over the new row
Then I see a button to create a new variant

**Scenario 3: Create variant**
Given that I am seeing the button to create to create a new variant
When I click it
Then a new empty variant is shown inline
And a message at the top stating that a product has been changed is shown

**Scenario 4: Discard new variant**
Given that I am creating a new variant inline
When I discard the changes for the product with the new variant
Then the page is refreshed
And I don't see the new variant row anymore

Note: saving and failure scenarios should follow existing behaviour as implemented in #11059 

## Design specs
A prototype is available here (first product on hover) > https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?page-id=1303%3A2&type=design&node-id=1303-385&viewport=586%2C222%2C0.36&t=GH5mMrXD3ZYqHbnN-1&scaling=min-zoom&mode=design

Figma screens are available here > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=1303%3A2&mode=design&t=OWtKOGWMhPX4i0q8-1

**New components and styles**
| Component | Example |
| --- | --- |
| Secondary button condensed | ![Screenshot 2024-01-16 at 10 14 49](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/7154fd8a-42ac-4532-bccb-4381d8318fcf) |

**Comment by dacook** [comment]
To consider: https://www.stimulus-components.com/docs/stimulus-rails-nested-form

**Comment by dacook** [comment]
### Estimate: 9hrs
1. Markup and style new button and form fields (1hr)
2. Creating new record with nested variant form (prove the concept with the current rails form) (2hrs)
   * with unit tests for success, failure etc
3. Set up template and Javascript to add new form on click (allow multiple).  (6hrs)
   * It will also need to record form 'dirty' state in BulkFormController, either:
      1. Adding the new row is considered dirty, even before filling
      2. Standard behaviour: each field is considered dirty when filled (defaultValue is ""). 
   *  Consider if [stimulus-rails-nested-form](https://www.stimulus-components.com/docs/stimulus-rails-nested-form) is appropriate, but given above requirement, perhaps just build into BulkFormController.
   * Ensuring child controls are initialised correctly (eg on_hand popout)
   * Including feature specs

#### Assumptions
* Agreed with Mario that either option "a" or "b" above is ok
* Assuming the new variant form is exactly the same as edit, except:
   * No actions menu (edit), space is left blank
 * No additional indication the row is "new"
 * No remove button for new rows (although I that would be pretty easy if needed)
 * Leaving all fields blank on a new row will result in it being ignored during save. This means if  you enter in details for a new variant, then accidentally click "new variant" again, it won't block you from saving the first.

**Comment by mariocarabotta** [comment]
>   * No actions menu (edit), space is left blank
All good
> * No additional indication the row is "new"
All good
> * No remove button for new rows (although I that would be pretty easy if needed)
Nice to have, let's do it later
> * Leaving all fields blank on a new row will result in it being ignored during save. This means if  you enter in details for a new variant, then accidentally click "new variant" again, it won't block you from saving the first. (alternatively we can add a remove button).
All good, as long as I can add multiple new variants in one go (click the button multiple times, as per current behaviour)

**Comment by mariocarabotta** [comment]
deleting the variant before being saved is worked on [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/12400)
