### ISSUE TITLE
[BUU] Delete a product or variant

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11068]
## Context
This issue builds on top of https://github.com/openfoodfoundation/openfoodnetwork/issues/11069, to allow to delete products and variants.

## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** delete products or variants
**- So that:** my catalogue is up to date

## Acceptance Criteria & Tests

**Scenario 1: Product - delete action**
Given that I am seeing products in my catalogue
When I select the actions available for a product
Then I see an option to edit and an option to delete

**Scenario 2: Product - start deleting**
Given that I am seeing the actions for a product
When I select the delete option
Then I see a dialog asking for confirmation

**Scenario 3: Product - keep product**
Given that I am seeing the delete confirmation dialog
When I select the option to keep the product
Then the dialog disappears
And the product remains in my catalogue

**Scenario 4: Product - confirm deleting**
Given that I am seeing the delete confirmation dialog
When I select the option to delete the product
Then the deleting process starts
And the dialog disappears
And I see a loading indicator

**Scenario 5: Product - delete successful**
Given that I have started the deleting process for a product
When the process is successful
Then my catalogue reloads
And I don't see that product anymore
And I see a success message

**Scenario 6: Deleting failed**
Note: not sure how to handle this failure. We can look into it during development.

**Scenario 7: Variant - actions not available**
Given that I am seeing products in my catalogue
And I have products with one variant only
The single variant for a product does not show any action

**Scenario 8: Variant - actions available**
Given that I am seeing products in my catalogue
And I have products with multiple variants
Then those variants have actions

**Scenario 9: Variant - delete action**
Given that I am seeing products with multiple variants in my catalogue
When I select the actions available for those variants
Then I see an option to delete

**Scenario 10: Variant - start deleting**
Given that I am seeing the actions for a variant
When I select the delete option
Then I see a dialog asking for confirmation

**Scenario 11: Variant - keep variant**
Given that I am seeing the delete confirmation dialog
When I select the option to keep the variant
Then the dialog disappears
And the variant remains in my catalogue

**Scenario 12: Variant - confirm deleting**
Given that I am seeing the delete confirmation dialog
When I select the option to delete the variant
Then the deleting process starts
And the dialog disappears
And I see a loading indicator

**Scenario 13: Variant - delete successful**
Given that I have started the deleting process for a variant
When the process is successful
Then my catalogue reloads
And I don't see that variant anymore
And I see a success message

**Scenario 14: Deleting failed**
Note: not sure how to handle this failure. We can look into it during development.

## Design specs

Figma screens are available here > 
https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=517%3A2906&mode=design&t=PzBG8cWoBQnyy30t-1

Prototype here (delete first product) > https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?page-id=517%3A2906&type=design&node-id=517-2920&viewport=606%2C258%2C0.08&t=olIZaV9DfNiQk84y-1&scaling=min-zoom&mode=design

| Component | Example |
| --- | --- |
|Confirmation dialog|![Screenshot 2023-08-02 at 10 21 56](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/5bb3b755-2746-473c-a3cb-88fe737bf5ae)|
|Primary disruptive button relaxed|![Screenshot 2023-08-02 at 10 22 30](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/4559d748-a5c5-4003-9e2b-dcfba5771aa6)|

**Comment by dacook** [comment]
This is adding a new item to the actions menu. It would be worth referring to similar recent PR https://github.com/openfoodfoundation/openfoodnetwork/pull/11785

For the confirmation popup, I expect we want to use `ConfirmModalComponent` (but I haven't checked closely).

Estimating: in terms of hours I'd think it wouldn't need more than a few.

**Comment by chahmedejaz** [comment]
Hey @mariocarabotta - I'd love work on this, can you please assign it to me? Thanks.

**Comment by chahmedejaz** [comment]
@mariocarabotta - Just to confirm, is the display of success and failure messages are being handled in https://github.com/openfoodfoundation/openfoodnetwork/issues/11517 for this issue as well?

**Comment by mariocarabotta** [comment]
> @mariocarabotta - Just to confirm, is the display of success and failure messages are being handled in #11517 for this issue as well?

Ideally yes. the problem is that that card is still in progress. @abdellani probably has quite a few things to work on, it might not be high on his list at the moment.
do you have any preference on how to deal with it? we can decouple those scenarios, or try to prioritise updating the messages first

**Comment by chahmedejaz** [comment]
- I read the card issue in detail and found that it will just create the success/failure message card that will be used to handle messages for the product's name, SKU, and price changes.
- After that issue is closed, I suggest creating separate issues for places in which we need to use that card for success or failure messages. i.e. for cloning and deleting products

- Unfortunately, we have to have that card so that we can have symmetry of success and failure messages throughout the app
- However, for the time being, we can just use the same old UI notifications for success or failure messages until that card is completed.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/b7c0c0e3-4b5d-41bc-bd40-dfc272aac8e7)


Please let me know what you think about it. Thanks.

**Comment by chahmedejaz** [comment]
**Update:**
- It's PR is ready for review now.
