### ISSUE TITLE
[BUU] See and update product images

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11065]
## Context
This issue introduces the ability to view and edit images in the product list.

## Description

**- As an:** enterprise user 
**- On page:** `/admin/products`
**- I want to be able to:** see and edit images
**- So that:** I can show the right pictures of my produce to customers

## Acceptance Criteria & Tests

**Scenario 1: Default images in list**
Given that I am in `/admin/products`
And I have products without an image
When my catalogue has loaded
Then I see the default illustration for products without an image

**Scenario 2: Start adding image**
Given that I am hovering on a product 
When I select to edit its image
Then I see a section with the current image at its full size (this could be either the default or a previously uploaded one)

**Scenario 3: Browsing for image**
Given that I am seeing the section where to edit the product image
When I select to upload an image
Then I see the default system upload window
And I can browse in my machine to find the image I want

**Scenario 4: Uploading image**
Given that I am browsing in my machine to find the image I want
When I select the image
Then my image starts to upload to my catalogue
And the default system window disappears
And the section where to edit the product image disappears
And I see a loading indicator

**Scenario 5: Successful image update**
Given that I am uploading a new product image
When the image is successfully uploaded
Then I see a success message
And I see the new image in my product catalogue

**Scenario 6: Error**
Given that I am uploading a new product image
When the image is not successfully uploaded
Then I see an error message describing what the issue is

@jibees can you please let me know which errors might happen? I'll design based on actual scenarios

## Design specs
A prototype is available here (upload image for product with default illustration, then click again to see the new image) > https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?page-id=401%3A4320&type=design&node-id=401-4321&viewport=1013%2C303%2C0.14&t=tiXXkkRZsKsVBWnk-1&scaling=min-zoom&mode=design

Figma screens are available here > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery?type=design&node-id=401%3A4320&mode=design&t=rR08tEUkunFiHPm9-1

**New components and styles**

| Component | Example |
| --- | --- |
| Image in table (40x40) | ![Screenshot 2023-07-14 at 14 29 50](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/b7ab689a-4634-4bdb-94e0-2f79a6df6354)|
| Edit image button |![Screenshot 2023-07-14 at 14 31 05](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/2c3a93f7-177e-4fd0-b66b-e1a9a416cf6c)|
|Overlay dialog with title| ![Screenshot 2023-07-14 at 14 31 21](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/a0f9f51e-1ddf-415c-aa52-f73f8bb6ed7e)|

**Comment by dacook** [comment]
Not sure if this was documented elsewhere, but we discussed using this icon: `icon-upload-alt` (https://fontawesome.com/v3/icon/upload-alt)

(we still used the old version of FontAwesome)

**Comment by dacook** [comment]
I think we can extend `ModalComponent` for this. I think everything needed for uploading images should be in place already.
Estimating: I'd think it wouldn't need more than a few, maybe up to a day to get right.

**Comment by dacook** [comment]
Hi @mariocarabotta , on my list of things to do, I still have these:
 * fix edit on corrupt stagin gdata? ([mentioned on thread](https://openfoodnetwork.slack.com/archives/C018S101R4J/p1706191417633999?thread_ts=1705531338.497929&cid=C018S101R4J))
  * part 6?: improve style of image popup ([mentioned by Rachel](https://github.com/openfoodfoundation/openfoodnetwork/pull/12048#issuecomment-1904370866)). Sorry it was too much to do first go.
  * part 5?: error messages. Happy with the current handling of these or would like to implement something else?

Would you like me to follow any of these up before moving on from this issue?

**Comment by mariocarabotta** [comment]
@dacook

- corrupt data: Rachel recently mentioned in slack to pause that
- image pop up style: very clear it's "a bit broken", so if it's an easy fix, I'd be good to update
- errors: haven't been able to trigger any errors to be honest, and i've tried :) 

I do have some feedback on the sequencing of showing loading indicators and success messages, but I don't think it's top priority for now. If that's ok, I'll leave it for a separate improvement issue for later?

**Comment by mariocarabotta** [comment]
> @dacook
> 
> * corrupt data: Rachel recently mentioned in slack to pause that investigation
> * image pop up style: very clear it's "a bit broken", so if it's an easy fix, I'd be good to update
> * errors: haven't been able to trigger any errors to be honest, and i've tried :)
> 
> I do have some feedback on the sequencing of showing loading indicators and success message when dealing with images, but I don't think it's top priority for now. If that's ok, I'll leave it for a separate improvement issue for later?

I was able to replicate the 500 (got the snail in the new version) but maybe AU staging doesn't have the latest PRs. I'll keep an eye out for that in the next few days.

**Comment by dacook** [comment]
👍  Thanks Mario. 
I'll improve the image popup today or early next week.
