### ISSUE TITLE
Need a manual hack for a front end translation...

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1107]
From the begining in theFrench instance, we have useda manual hack to display the translation on the "end date" of an order cycle. At each upgrade we needto do it again, so we would like to solve the issue more sustainably.
Any idea how we can display the translated string? @mkllnk or @sigmundpetersen maybe?

![pb_traductionfr](https://cloud.githubusercontent.com/assets/8135376/17096112/1e291fb6-5258-11e6-9bf1-99fdad3417af.png)

**Comment by myriamboure** [comment]
The problem doens't happen on our  staging server, so it's link to internationalisation configuration apparently, but we don't find yet the problem...

**Comment by mkllnk** [comment]
That translation is done by a plugin called `momentjs-rails`. Maybe check for differences in your application configuration `application.yml`. Or read the documentation of that plugin. There might be hints why it thinks it should display English.

**Comment by myriamboure** [comment]
Ping @gnollet :-)

**Comment by blancnic** [comment]
I think we need to add //= require moment/fr.js
https://github.com/derekprior/momentjs-rails

**Comment by blancnic** [comment]
@mkllnk : don't you thing we could include this in a configuration file or define a all.js.coffee by country? Actually, we have to modify the js file each time we upgrade....

**Comment by myriamboure** [comment]
Why is it working in staging then?
Is there the same issue in Norway @sigmundpetersen ? You only have a production instance, o you have to modify the js file each time you upgrade as well?

**Comment by mkllnk** [comment]
all.js.coffee has already locale specific data, the I18n object with translations. If we could load other locale-dependent js-libraries in a similar way, that would be good. I don't think we want to include every locale in every instance. The all.js file would become too big and would negatively impact the user experience.

**Comment by sigmundpetersen** [comment]
@myriamboure yes we have the same issue on the Norwegian instance

**Comment by gnollet** [comment]
Hi,
I add the line //= require moment/fr.js on all.js.coffee and rebuild the assets.

That's fix the issue but we must think to this on each time we want to update platform.

**Comment by mkllnk** [comment]
Are you deploying via `git push`?

You can put that into your deploy script `.git/hooks/post-receive` on the server. Something like:

```sh
echo '//= require moment/fr.js' >> "$CURRENT_PATH/app/assets/javascripts/darkswarm/all.js.coffee"
```

Just before the assets are rebuild. I'm not sure about the path. You need to check that. But it would do it automatically every time you deploy.

**Comment by gnollet** [comment]
@mkllnk I'm using ansible scripts
I will take a look on the script to see if I can insert this

Thanks

**Comment by mkllnk** [comment]
That git hook is installed by the Ansible scripts, but not executed. The approach above works only with git-push deploys. If you do Ansible, you will need an Ansible playbook that adds that line to your all.js file.

**Comment by enricostano** [comment]
We'll need this for spanish instance too. cc/ @sseerrggii

**Comment by myriamboure** [comment]
I think this is something I reported in some Slack comments with remaining translation issues @pacodelaluna but it doesn't seem so trivial... I assign you as it's about translation issues but feel free to comment if needed!

**Comment by myriamboure** [comment]
@jeronimo are the PR you are committing solving this as well ? Else @lin-d-hop does anyone work on it or should we see on our side with @pacodelaluna ?

**Comment by myriamboure** [comment]
@enricostano any idea how to solve this issue ? It's coming up again each time we do an upgrade, and it's a front end issue to even worse... @ltrls or @pacodelaluna if you have some minutes to find how to solve that it would be awesome :-) It's really annoying ! At the moment it's in english on the French production server...

**Comment by sigmundpetersen** [comment]
Same as this #1781 ?

**Comment by sauloperez** [comment]
Yes, it is. Removing that one to keep the discussion here.

**Comment by leandroalemao** [comment]
All,
Just opened a PR #1819 to try to fix this issue.
👍 😄 
Tks
Lenadro.

**Comment by myriamboure** [comment]
You are awesome @leandroalemao :-)

**Comment by sauloperez** [comment]
Already merged
