### ISSUE TITLE
StandardError in db:migrate: The specified key does not exist.

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#11070]
## Error in OpenFoodNetwork Aus

**StandardError** in **db:migrate**
An error has occurred, this and all later migrations canceled:

The specified key does not exist.

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/648f9e1f3b1f11000845955b?event_id=648f9e1f00be8bcc4b640000&i=gh&m=ci)

## Stacktrace

    db/migrate/20230504001141_public_images.rb:38 - block in set_objects_to_readable
    db/migrate/20230504001141_public_images.rb:38 - set_objects_to_readable
    db/migrate/20230504001141_public_images.rb:8 - up

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/648f9e1f3b1f11000845955b?event_id=648f9e1f00be8bcc4b640000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by mkllnk** [comment]
Weird, it says that an object doesn't exit which we just listed from the bucket. Maybe it got deleted while the migration was in process. I'm trying again to see if it's a temporary issue.

**Comment by RachL** [comment]
@mkllnk is this one still needed / and needed in dev-ready?

**Comment by mkllnk** [comment]
No, can be closed. Migrations ran a while ago and are not re-run.
