### ISSUE TITLE
[Edit Variant] Can't update values on the variant edit page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11085]
## Description

Edit: I'm not sure this is a regression. Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/7719

~~Seems to affect only~~ Reported on FR-prod.

When:
- localization is enabled
- commas are used as decimal separators
- a locale like FR or EN is used

Then:
Editing the variant on the variant edit page does not take effect, after saving changes.

Update: this seems to happen because an empty space is added by default to the Price field; without having introduced it explicitly, the user ends up Clicking update and sending this empty space in the form, which prevents saving changes.

## Expected Behavior

It should be possible to edit ~~variants~~ values variants, on the variant edit page.
Update: an empty space should not be added by default to the price field.

## Actual Behaviour

It's not possible to edit ~~variants~~ values, on the variant edit page.
Update: an empty space should added by default to the price field.

## Steps to Reproduce

As super admin:
Set the localization preferences as:
- localization is enabled
- commas are used as decimal separators

As a hub:

0. Log in and select a locale like FR or EN
1. On the products page, click the edit product icon
2. Click Variants
3. Click the edit icon, for a given variant -> you should be redirected to `admin/products/<product_name>/variants/<variant_id>/edit`
4. Change the price value; click Update -> see changes did not take effect

## Animated Gif/Screenshot

**FR-prod**

[See video](https://openfoodnetwork.slack.com/files/U0168TVQZJ4/F05D6N5QM7X/enregistrement_de_l___e__cran_2023-06-20_a___08.39.46.mov), taken from FR-prod, [Slack thread](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1687243525197879).

**staging-FR**

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/fece22c3-d46a-4996-bda3-5544ccb6f714)

## Workaround

Edit the variant in the products page.
Update: if you delete the (pretty much invisible) empty space, then saving changes works.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.3.12 (v13 not deployed yet)
* Browser name and version: I think Safari?
* Operating System and version (desktop or mobile): Mac OS?

**Comment by jibees** [comment]
It should be possible to setup a spec for this right?
As it's a S3 and not a regression, not sure if I should prioritize this. On the others hand, some fr customers seems to complain recently.

**Comment by jibees** [comment]
When you say:
> localization is enabled

You mean this, right?
<img width="404" alt="Capture d’écran 2023-06-20 à 14 42 20" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/72dab13c-9168-4521-9cb3-36f9f0913798">

**Comment by jibees** [comment]
Question
I've the following configuration locally:
<img width="389" alt="Capture d’écran 2023-06-20 à 14 50 28" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/64362c77-022f-4ce8-a3db-cb94cd13e678">
Which, to me, enters in conflict. I've checked the "International thousand/decimal separator" but I've also configured mine (`,` and ``) ... I don't know what is suppose to happen after that. Any thoughts?

**Comment by filipefurtad0** [comment]
> Which, to me, enters in conflict. I've checked the "International thousand/decimal separator" but I've also configured mine (, and ``) ... I don't know what is suppose to happen after that. Any thoughts?

Hey @jibees , I don't have a clear answer... In fact, I've had similar questions about this and opened [this issue in the past](https://github.com/openfoodfoundation/openfoodnetwork/issues/7719) to raise this question: "what do we expect here? ".
Looking back now, I think the formulation in that issue is not really correct: ticking the localization option does play a role. I've tried to capture the current behavior on the spec here https://github.com/openfoodfoundation/openfoodnetwork/pull/11086.

**Comment by kirstenalarsen** [comment]
I'm afraid I have nothing helpful to add here - these were added for european instances and I've never gone anywhere near them!

**Comment by jibees** [comment]
> However, I think the bug recently reported is really about submitting an empty space on the form. Also this, I've tried to capture this on the spec

Ok, I probably should concentrate on it. And we probably should update the issue description as well.

**Comment by filipefurtad0** [comment]
> And we probably should update the issue description as well.

Yes, indeed - I've updated this now @jibees, I hope it's more clear.

**Comment by lin-d-hop** [comment]
Hi @filipefurtad0 @jibees 
Just checking if you found a clear solution to this problem? Will 'not adding the space' resolve this or does this need some deeper investigations/design?

**Comment by jibees** [comment]
We have a PR that resolve the underlying issue (ie. extra white space), but actually, there is some misunderstanding around all those options that we have around internationalization. Not sure this issue (that will be closed once PR is merged) is the right one to deal with.

**Comment by filipefurtad0** [comment]
> We have a PR that resolve the underlying issue (ie. extra white space)

Agree; the issue deals with the bug of not being able to update values. I think this will be fixed with the PR :crossed_fingers: 

> there is some misunderstanding around all those options that we have around internationalization

Also agree, I'm not sure what this feature/option does.
