### ISSUE TITLE
no 'invite users' button in aus noticeboard?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1108]
When I'm in ofn global community I have option to invite users

![image](https://cloud.githubusercontent.com/assets/2911176/17161560/da0345be-53f1-11e6-9912-de7c74bbf1ac.png)

but in the noticeboard I don't . . @mkllnk do you know if there is a reason for this? Trying to work out the best way to get people through this process and encountering some issues [here](http://community.openfoodnetwork.org/t/new-user-coming-to-ofn-for-discussion-forums/644))

![image](https://cloud.githubusercontent.com/assets/2911176/17161570/f31fc388-53f1-11e6-9f6a-c969397ab797.png)

**Comment by mkllnk** [comment]
Yes, because you need an OFN account for the noticeboard. They are tight together. There is no signup for the noticeboard, only at OFN. So you can't invite people to the noticeboard. The OFN would need a feature to invite people to the OFN.

**Comment by kirstenalarsen** [comment]
hmmmm. ok. will rethink

**Comment by kirstenalarsen** [comment]
so if they are already members of ofn, we still can't send them the email with activation to complete the login on noticeboard . . they would still have to login, hit notices, hit login again and then go to their email to hit the activation link?

**Comment by mkllnk** [comment]
Only the people that don't have a verified email with OFN yet. Yes, the problem is that we don't verify email addresses of OFN accounts, but Discourse needs verified email addresses.

**Comment by lin-d-hop** [comment]
Aus noticeboard is now depricated!
