### ISSUE TITLE
Error 422 on /admin/products

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11095]
## Description

On current master [5ec872c](https://github.com/openfoodfoundation/openfoodnetwork/commit/5ec872c6fdcdd54abb05351ee92e4fb8af81089a) opening /admin/products shows an endless spinner. There in an error 422 and a Bugsnag triggered:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6492e4e12e9f220008c3c01e?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging

This is blocking the test of #11002 because I need to reproduce the tax issue in master before staging the solution and to do that I need access to the tax settings of the products.

## Expected Behavior

No error, no bugsnag.

## Actual Behaviour

Error 422 and Bugsnag.

## Steps to Reproduce

1. Open /admin/products

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/7404e067-26d5-4981-aaa5-e476cd97ccb6)

## Your Environment

* Version used: [5ec872c](https://github.com/openfoodfoundation/openfoodnetwork/commit/5ec872c6fdcdd54abb05351ee92e4fb8af81089a)
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
Maybe you can try with a shop manager, and not the super admin (to no fetch the whole list of product)

**Comment by drummer83** [comment]
This should only affect staging UK and should be solved as soon as #10939 has been merged.

**Comment by drummer83** [comment]
> Workaround: Maybe you can try with a shop manager, and not the super admin (to no fetch the whole list of product)

Tried that, but it's the same. I will use a different server - if I have time for it today.

**Comment by dacook** [comment]
This would be a result of https://github.com/openfoodfoundation/openfoodnetwork/pull/10939 being staged on that server.

It has also been staged on AU staging now, so it has the same problem..

**Comment by RachL** [comment]
I'm closing this as it is on the old product page and we won't ix this.

**Comment by dacook** [comment]
Looks like it was a data problem that we probably fixed now anyway.
