### ISSUE TITLE
Odd labels on login screen

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1110]
all the login screens (including 'forgot password' etc) have odd labels in the red boxes.  I know this has happened before - was it something to do with a new deploy?
thanks
N
![screenshot 2016-07-31 17 27 09](https://cloud.githubusercontent.com/assets/10517702/17277831/06cc6480-5745-11e6-9661-efb261db5fd4.png)

**Comment by lin-d-hop** [comment]
We seem to have lost some translations again. I'll fix this.

**Comment by Rocksj** [comment]
And on the account balances screen
![screen shot 2016-08-03 at 11 44 51](https://cloud.githubusercontent.com/assets/15102362/17363008/f3f1f456-596f-11e6-813b-a848d562088d.png)

**Comment by lin-d-hop** [comment]
This is a translation issue and I need to wait until a time that OFN can go unused to 20 mins to make the change. Will try for midnight tonight...

**Comment by Rocksj** [comment]
We will definitely be closed then! @lin-d-hop

**Comment by OliverUK** [comment]
Any news on those strange labels?
