### ISSUE TITLE
Make front page dropdown banner customisable by super-admin

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1112]
The front page dropdown has a range of potential uses and is not currently that friendly 

In Aus, we have an immediate alternative use that we are implementing - to point people to new resources and functions ('learn' and 'connect') - see more about this [here](http://community.openfoodnetwork.org/t/new-configurable-landing-page-for-ofn-sites-new-sub-landing-page-for-enterprise-users/627/3)

We are also changing the colour because we figure no one is reading it at the moment and we want to use it more as an 'alert' 

These changes are currently being implemented only for aus as they are still hard-coded. Connected to @RohanM 's issue about how we're separating these changes for now

There is a larger issue to actually make use of this banner customisable by super-admin rather than needing code change, so that it can readily be turned into '[donate](http://community.openfoodnetwork.org/t/add-a-donate-support-button-on-the-marketplace-site/613/8)' or 'read here' or whatever as needed

**Comment by lin-d-hop** [comment]
This has been done
