### ISSUE TITLE
Add Trix editor to Product Description Editor

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#11129]
## Description

Replace the existing angular WYSIWYG editor with the Trix editor.
Here https://openfoodnetwork.org.uk/admin/products/new
And here https://openfoodnetwork.org.uk/admin/products/[_product-name_]/edit

## Acceptance Criteria & Tests

1. Remove old angular WYSIWYG
2. Replace with the Trix editor for product description
3. Test `<hr>` and `<br>`. Plus bullet points, strikethrough, headings etc etc.

From: https://github.com/openfoodfoundation/wishlist/issues/427

**Comment by jibees** [comment]
As far as I know: no ; trixeditor doesn't allow to insert HTML content.

**Comment by RachL** [comment]
@jibees have you check the last comment of the issue? https://github.com/openfoodfoundation/wishlist/issues/63#issuecomment-1340641620

Also hr and br are html right?  :p

**Comment by jibees** [comment]
I think I don't understand sorry.
