### ISSUE TITLE
New, alternative invoice fails on rendering logo

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#11149]
## Error in OpenFoodNetwork UK

**ActionView::Template::Error** in **BulkInvoiceJob@default**
wrong number of arguments (given 0, expected 1)

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/649da007fc68d5000829f088?event_id=649da03800becd23cc5e0000&i=gh&m=ci)

## Stacktrace

    app/models/enterprise.rb:299 - logo_url
    app/views/spree/admin/orders/invoice4.html.haml:9 - _app_views_spree_admin_orders_invoice__html_haml__1057873861057224477_152240
    app/services/invoice_renderer.rb:10 - render_to_string
    app/jobs/bulk_invoice_job.rb:11 - block in perform
    app/jobs/bulk_invoice_job.rb:10 - each
    app/jobs/bulk_invoice_job.rb:10 - perform

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/649da007fc68d5000829f088?event_id=649da03800becd23cc5e0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### Steps to reproduce

* You need a distributor with logo.
* The distributor needs to activate displaying the logo on invoices.
* You need to activate the new invoices.
* The instance needs to have the alternative invoice template activated.
* Create a new invoice.

**Comment by abdellani** [comment]
From the logs, it looks like you were trying to run a bulk print.
I handled that problem on https://github.com/openfoodfoundation/openfoodnetwork/issues/11046 .

There is another potential problem with logos.
When we generate an invoice, we store the URL of the logo on the serialized order in the invoice. I suspect that active storage generates a temporary link that refers to the logo. if that's true, what will happen when the link expires?

**Comment by mkllnk** [comment]
> When we generate an invoice, we store the URL of the logo on the serialized order in the invoice. I suspect that active storage generates a temporary link that refers to the logo. if that's true, what will happen when the link expires?

You are right, that's a little bit tricky. There are two options here:

1. Store the blob id instead and generate the URL, or
2. Use a public URL without expiry.

I didn't check this in detail but I think that Matt also changed the permissions on logo files to make them public recently. That should enable us to create a URL without expiry. Otherwise we need to store blob ids instead of URLs.
