### ISSUE TITLE
Feature toggled home page changes - future strategy

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1115]
As part of #1114, we're adding feature toggles that customise some parts of the home page. This is not ideal - we'd like these things to be configurable instead. A future strategy might involve shifting control of these things into the `Configuration -> Content` page of the admin section.

There was also some discussion around changing the behaviour of the page alert bar (aka Uber dropdown) to model the pop-up dog on Trello:
- Message is configurable by admin
- Each message is shown to each user once only (cookie/login to track)

**Comment by lin-d-hop** [comment]
Much of this has been done!
