### ISSUE TITLE
Improve Customer - Addresses Report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#11155]
## Description

Please can we adjust the filter
- Add date filters like in Orders & Fulfilments reports 
- Change name of 'Distributor' filter to 'Hub'
- Remove the 'Supplier' filter

Please can we add the following columns to the end of the Customers - ~Mailing List~ Address report:
- Orders Count: number of orders for the customer, where filters are true
- Orders Total: total amount spent at the shop for the customer, where filters are true
- Last order: date of the last order, where filters are true.

Additionally can we rename this report to 'Customers'.

As a final step on this issue please remove the Mailing List report.

Clearly this is more than a papercut :( However since 4 instances chose this, let's just do it. 

## Acceptance Criteria & Tests

1. Three additional columns - Orders Count, Orders Total, Last Order
2. All new columns should display based on filters. In the case that only one order matches the filters, count=1, total=order total and last order = order date. In the case that no orders match the filters for the customer, that customer is not shown.
3. Date filters are added
4. Supplier filter removed
5. Distributor filter changed to Hub
6. Report renamed to Customers
7. Mailing List report removed
8. Specs updated and added
9. Translations on all fields.

**Comment by jibees** [comment]
@lin-d-hop 

> Add date filters like in Orders & Fulfilments reports
> Change name of 'Distributor' filter to 'Hub'
> Remove the 'Supplier' filter

Should we change the Customers/Mailing List as well ? They both use the same filters for now.

**Comment by NiftyGaloot** [comment]
Can we also add the zipcode or post code to the report?
