### ISSUE TITLE
Remove `new_products_page` feature and its associated page, components, ... 

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#11153]
### What we should change and why (this is tech debt)
We now use `admin_style_v3`

### Context
This came up in PR https://github.com/openfoodfoundation/openfoodnetwork/pull/11007#discussion_r1251547475

**Comment by sigmundpetersen** [comment]
@RachL @dacook is this still relevant?
Shall we close, or add to BUU2?

**Comment by RachL** [comment]
I thought we did remove it but indeed I can't find the related PR, so I guess it's still relevant? Maybe David knows more.

**Comment by dacook** [comment]
Yep, all done long ago:
- duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/11273
