### ISSUE TITLE
Admin, Orders: Actions dropdown is not well placed

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#11164]
## Description
<img width="1650" alt="Capture d’écran 2023-07-06 à 10 35 18" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/d759aa23-3a28-4386-9986-ac2833a7cfa3">

This propbably came up after [#11123](https://github.com/openfoodfoundation/openfoodnetwork/issues/11123)

I'd say this one is blocking the release drafting for today.

**Comment by jibees** [comment]
Back `In Dev`, seems we don't see any orders as well...

**Comment by dacook** [comment]
I've added the priority label and moved to the top of the column, because it's blocking the release.
