### ISSUE TITLE
[GH-Actions] Open issues with Deployments

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11168]
## Description

Currently we can deploy to staging-UK, by simply placing the tag on the PR :sparkles: 

Before we can confidently replace Semaphore, we need to address some open issues:

~~- deployments to not work for other staging servers other than UK. Attempts trigger an ssh error (see pic below)~~ Edit: fixed :+1: 
- we need to clarify what do we stage exactly, when we use GH-Actions: a merge PR? The last commit of the branch? Also [raised here](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1687130590822749?thread_ts=1686922649.068849&cid=C02TZ6X00).
- is it possible to stage different builds from master? Or only the latest master? Use case: staging the currently deployed version in production

**Comment by Matt-Yorkley** [comment]
@filipefurtad0 I think it should work on AU and FR staging now :+1:

**Comment by filipefurtad0** [comment]
Great, just tested it on two PRs for each server staging-AU/FR and can confirm it works. I've updated the issue :+1:

**Comment by jibees** [comment]
@Matt-Yorkley Is it possible for you to explain briefly what was the issue, and what you've done? Thanks! 🙏

**Comment by RachL** [comment]
@filipefurtad0 do we still need this issue?

**Comment by filipefurtad0** [comment]
Thanks @RachL . As to the questions raised:

> - we need to clarify what do we stage exactly, when we use GH-Actions: a merge PR? The last commit of the branch? Also [raised here](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1687130590822749?thread_ts=1686922649.068849&cid=C02TZ6X00).

We can stage commits, within a given branch :heavy_check_mark: 
I'm not entirely sure whether we stage merge commits (with master) or just the commit itself. From the devops notifications channel it looks like we stage commits?

> - is it possible to stage different builds from master? Or only the latest master? Use case: staging the currently deployed version in production

As above, we can choose the specific commit we want from master. We can check the required commit from the [commit list from master](https://github.com/openfoodfoundation/openfoodnetwork/commits/master/). :heavy_check_mark: 

So, I'd say we can close.
