### ISSUE TITLE
[Checkout, Step 3] Delivery details are showing bill address (instead of delivery address)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11171]
## Description

If bill address and delivery address are not identical for an order, then on step 3 of the checkout process the bill address is displayed. This is irritating because the header is reading 'delivery details' and 'delivery address'.
In a first step we should display the delivery address instead of the bill address, in a second step we could even display both (unless they are identical).

## Expected Behavior

Display delivery address on step 3 of checkout.

## Actual Behaviour

Bill address is displayed on step 3 of checkout.

## Steps to Reproduce

1. Put items in your cart and proceed to checkout.
2. On step 1 of checkout select a 'delivery' shipping method and type a different delivery address than the bill address.
3. Proceed to step 3 of checkout.
4. Look at the address displayed under 'delivery address'.

## Animated Gif/Screenshot

Different billing and shipping addresses:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/d922bb97-3b67-43fe-907e-711d5ae97435)

Billing address is displayed as shipping address:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/175aba81-2266-47e1-aa2b-01f922159753)

## Workaround

None? But s2 would be too critical, I think.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Step 1: Replace billing address with shipping/delivery address.
Step 2: Display both addresses, if not identical. 
Proposal: 
![ksnip_20230706-195715](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/af87e059-2ba9-4348-afa6-2f6b23638aad)

**Comment by RachL** [comment]
Maybe a quick fix here is just displaying the delivery address and remove the bill address.
We had a lot of design iteration on that part so for now I would stick to what was designed and only fix the data. @jibees is this one you can squease in your agenda when you have the time?

**Comment by jibees** [comment]
> @jibees is this one you can squease in your agenda when you have the time?

Sure.
