### ISSUE TITLE
Make "on demand" check box a default column in the bulk edit product table

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1118]
I have noticed in support with new users that they don't find intuitively how to say that the product is available on demand when they create products from the bulk edit page. (=click on "columns" and then "on-demand")
So some of them just put a false arbitrary quantity (see example below), but that pollute the base then and can be annoying if various hubs use the same supplier.
As "on-demand" is very often use for lots of products, I propose to make it visible as a default column on top of the existing ones.

![screenshot from 2016-08-03 12-36-51](https://cloud.githubusercontent.com/assets/8135376/17362848/5860913e-5977-11e6-936a-a5db66c8232a.png)

**Comment by myriamboure** [comment]
Any objection @sstead , what do you think about it, as you are in contact with users often in support?

**Comment by myriamboure** [comment]
@sstead is it ok if we do that? It is confusing for users in France not to have the "on demand" column by default, they don't understand and put a big amount instead :-o

**Comment by sstead** [comment]
Yes I think this is very logical!

**Comment by myriamboure** [comment]
Same, seems pretty easy for Claire @pacodelaluna ? On all the issues where I propose Claire I can put the label "ruby for newbies" or "angular for newbies" ... but I don't know which one to use... or we can assign Claire to the tasks we identify for her ? What do you think ?

**Comment by oeoeaio** [comment]
See [my comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/1817#issuecomment-328395075) on @ltrls's PR. I have reservations but happy to be overruled if others think the interface remains usable.
