### ISSUE TITLE
Deleting enterprise managers does not save

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1119]
On UK production, if you try and delete an enterprise manager from an enterprise for which you are the owner, it does not save unless you also update the owner or notifications email at the same time. Clicking on the delete icon next to the user will remove the name, but the 'update' button at the bottom does not turn red and allow you to save. If you leave the page and return the deleted user will still be there. Have tried this whilst logged in as super admin and the same thing happens. 

Not a priority as I have figured out the work around of deleting and retyping the notifications email to allow you to save it, but may come up when future users are changing their managers.

**Comment by lin-d-hop** [comment]
Suggest this might be a similar fix to @levents changes in #1199 ?

**Comment by lin-d-hop** [comment]
@levent will comment. Hopefully we can explore a more long term solution to the manual hook.

**Comment by Matt-Yorkley** [comment]
Very similar fix, as you say. The problem is that some of the elements in the enterprise management pages interact with the form data but are not form elements themselves, so they don't trigger the $dirty state on the form without being told to explicitly.

**Comment by OliverUK** [comment]
@lin-d-hop  can't find the pull request in buildkite

**Comment by lin-d-hop** [comment]
@Matt-Yorkley can you submit another PR uk/* so this builds automatically in buildkite. Thanks!

**Comment by Matt-Yorkley** [comment]
@lin-d-hop it's already got the uk prefix: #1333.

**Comment by lin-d-hop** [comment]
@OliverUK this is on buildkite now

**Comment by OliverUK** [comment]
@lin-d-hop  Also failed. Must be doing something wrong.

**Comment by lin-d-hop** [comment]
Try again in 10 mins, builds/tests are all still running. You can see this on the PR itself, if is says Some Checks Havent Completed then it wont deploy. If there is a yellow circle or red cross beside the commit hash it won't deploy. Needs a green tick at the bottom.

**Comment by OliverUK** [comment]
Testing notes:
I added one of my email addresses as manager to an enterprise on staging, saved and returned to the user screen to remove it again. When I click the bin icon next to the new manager, the email address disappears and the "save" button now appears on the bottom of the screen. I clicked save and returned to the user screen. The deleted manager email was gone as it should.
