### ISSUE TITLE
Update button is obscured by free trial message 

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1120]
When editing enterprises and sometimes when editing products, the update / close buttons are obscured by the free trail message at the bottom of the screen. I can't see any obvious way to turn off or close this message. 

![obscured update button](https://cloud.githubusercontent.com/assets/19837861/17371451/d218ba40-5997-11e6-9dce-0afe19d1b7e4.png)

**Comment by MagsHall** [comment]
We're getting new users reporting this same problem too now. Does anyone know a fix?

**Comment by NickWeir63** [comment]
@daniellemoorhead as Lynne is away for a week, please could you suggest anyone we could talk to about this?  Is there a quick fix?  Thanks

**Comment by MagsHall** [comment]
Nick, did you say you weren't getting the error on your browser? What are you using? I am getting it using Chrome on a PC. Reuben gets it on a Mac using Firefox.

**Comment by NickWeir63** [comment]
I realise it is only not a problem for me because I am not getting the free trial message
![screenshot 2016-08-22 15 54 08](https://cloud.githubusercontent.com/assets/10517702/17859297/ebb1d26e-6880-11e6-8f62-68c271d2aad2.png)

**Comment by daniellemoorhead** [comment]
@oeoeaio or @bingxie do you think you could pick this bug up and sort it out for the UK team? It's become a bit of a problem for them that needs resolving. Would be great to get this into 1.8.5 release on friday.

**Comment by bingxie** [comment]
Before we can fix it. I need know what the solution could be? Adding a close button on the free trial message?

**Comment by oeoeaio** [comment]
Hm, how do people feel about only showing the trial message on the dashboard? Then there would be no conflict....

**Comment by NickWeir63** [comment]
yes great idea.  thanks
it will be great if we can have it in this release
thanks

**Comment by sstead** [comment]
Testing notes:
Correct, banner shows only on dashboard page, for a user with 1 trial enterprise, if they have 2 enterprises the banner doesn't display.

**Comment by lin-d-hop** [comment]
@NickWeir63 @MagsHall I've just deployed this update to UK production.

**Comment by NickWeir63** [comment]
great thanks Lynne.  @MagsHall shall i leave it with you to tell Reuben / check it works for him?  if not i can do it.  thanks

**Comment by oeoeaio** [comment]
Hey @lin-d-hop, which update did you deploy? We have not released a fix for this issue yet....

**Comment by MagsHall** [comment]
I have emailed Reuben to check, but it has disappeared from the demo hub so looks like it's a fix!
