### ISSUE TITLE
Property badges and filters on shop pages

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1121]
#1072 added property filters to producers listings (producers page and groups producers tab). Add badge display to the shops page and the groups shops tab.

**Comment by daniellemoorhead** [comment]
Hey @RohanM is this done?

**Comment by sstead** [comment]
So the appearance of badges for a) properties and b)categories are behaving inconsistently (as described below). We need to merge the two behaviours to get the ideal setup....

Currently for an OPEN shop we see the following:
- category badges of all products that that shop can sell, not just those in the current OC (not ideal)
- property badges of only the properties of the items in the current order cycle (ideal)

Currently for a CLOSED shop we see the following:
- category badges of all products that that shop can sell (ideal)
- No property badges, because none are in a current OC (not ideal, we should see all properties or products that shop can sell)

If we fix the above to all be 'ideal' the filter will be more intuitive, especially if the user is viewing closed shops.

**Comment by sstead** [comment]
Looks good! Unrelated issue found - https://github.com/openfoodfoundation/openfoodnetwork/issues/1157

**Comment by RohanM** [comment]
When we deployed this feature, we had a performance regression. I'm looking into how to make it fast enough to re-launch the feature, and also putting in some performance smoke tests so we pick up this kind of problem sooner.

**Comment by sstead** [comment]
Regarding the shops page... 
Type filter not working:
![image](https://cloud.githubusercontent.com/assets/10843056/20121910/35f3cef2-a668-11e6-85d0-1bbf46d6f28f.png)
It is working in the groups shops page:
![image](https://cloud.githubusercontent.com/assets/10843056/20121973/96609194-a668-11e6-922d-f44c4c325721.png)

Other things (I'm not sure if related)
- A producers's taxons and properties aren't showing.. in the producer list and groups producer list:
![image](https://cloud.githubusercontent.com/assets/10843056/20122002/bf9655ee-a668-11e6-9b2e-fdb5f2961199.png)
Most were showing, just not for 'producer of fish'.

- Type filter not working on groups producer page (For many proudcers, not just the producer of meat.
):
![image](https://cloud.githubusercontent.com/assets/10843056/20122022/deaeb9b2-a668-11e6-821b-d86c5562e595.png)

**Comment by sstead** [comment]
This is probably a separate thing to fix? Would you agree that this makes more sense...
Shop Now link should only be red if that shop is currently stocking an item from the producer in their open OC. 
![image](https://cloud.githubusercontent.com/assets/10843056/20122116/75e62cac-a669-11e6-83e2-e497dc6304a2.png)

**Comment by sstead** [comment]
Note to self: Tested cacheing, and making sure that changes were getting captured...
All was well in regards to products and taxons and properties, and how they display in shops page, producer page and groups equivalent.
Open Shop
- New open OC YES
- New supplier - new items in shop YES
- Items removed from shop YES
- New properties to supplier YES
- New properties to item YES
- properties removed from supplier YES
Properties removed from item YES
- Product changes category YES
- Delete product NO

Closed Shop
- New open OC  
- New supplier - new items in shop 
- Items removed from shop YES
- New properties to supplier YES
- New properties to item  YES
- properties removed from supplier YES
Properties removed from item  YES
- Product changes category YES
- Delete product NO

Producer
- Items removed from shop YES
- New properties to supplier YES
- New properties to item  YES
- properties removed from supplier YES
- Properties removed from item  YES
- Product changes category YES
- Delete product - NO!

**Comment by sstead** [comment]
Testing that deleted products are removed from OC interface AND the shop and badges on profile. FIXED
Separate bugs:
- https://github.com/openfoodfoundation/openfoodnetwork/issues/1236 Filters seeing deleted products
- https://github.com/openfoodfoundation/openfoodnetwork/issues/1237 Shop Now showing even if no items in OC.
