### ISSUE TITLE
Load fewer enterprises into shops/producers pages and others

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1122]
Issue #1035 was about loading only needed enterprises into the shopfront. But there are more pages that still load all enterprises:
-     app/views/home/_hubs.html.haml the list of shops, this is a similar task, but could work very well, because we are showing only a few enterprises at the beginning
-     app/views/groups/index.html.haml listing all groups, this is only for searching certain groups
-     app/views/groups/show.html.haml showing a single group, this could be optimised similar to the current task
-     app/views/map/index.html.haml the map with all enterprises, well, we need all enterprises on here, maybe caching would be good
-     app/views/producers/index.html.haml the list of producers, this could be optimised similarly

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/optimisations-suggestions/1176
