### ISSUE TITLE
[Vouchers] Checkout blocked after removing items from cart (order total < 0)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11233]
## Description

The order total of a given order may become negative if, after having added a voucher, a line item quantity is reduced by editing the cart; if so, checkout is blocked for that cart.

## Expected Behavior

After reducing line item quantity order total should remain zero (after having added a voucher).

## Actual Behaviour

After reducing line item quantity order total may go to negative values (after having added a voucher).

## Steps to Reproduce

After enabling vouchers and setting up a hub to have a shopfront and a voucher of amount 10:

As a customer:
1. Add some line items to the cart -> set this up so that order is equal or lower than 10
2. Add a voucher -> order total should zero.
3. Visit the cart. 
4. Reduce the amount of line items
5. Notice the negative order total
6. Try to complete the order

## Animated Gif/Screenshot

Before editing the cart:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/3dfcf725-fb25-4ce5-9009-860436db26a0)

After editing the cart:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/25cd09a6-f5a9-4f38-8fe2-47257f94b914)

Trying to checkout (user stuck on `/details` step):

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/b5613065-f62d-4fb6-add4-266502246efb)

## Workaround

Can't reach /payment so can't remove voucher.

Workarounds:
- Emptying cart, and starting over
- Adding more items to the cart so that the order total > voucher amount

## Your Environment

* Version used: v4.4.2
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by kirstenalarsen** [comment]
Could we have an estimate on fixing this? I'm hoping it could be considered an AU papercut (even if slightly larger than papercut) - we really want to get vouchers into use! ping @rioug

**Comment by rioug** [comment]
This should be fixed by #11117 which is in test ready right now.
