### ISSUE TITLE
Homepage changes for Thrive

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1123]
Make some changes to the home page (on Australian instance only) - page alert, learn & connect panes, footer Join us section. Also adds sell page, linked to from footer.

**Comment by sstead** [comment]
Broken link at https://staging2.openfood.com.au/sell
![image](https://cloud.githubusercontent.com/assets/10843056/17428471/fa099462-5b2b-11e6-9c4a-81d44d006bfd.png)

**Comment by daniellemoorhead** [comment]
Hey @RohanM has this been completed now, can the issue be closed?
