### ISSUE TITLE
Images broken in forum?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1124]
perhaps something to do with the domain change @mkllnk ? 

![image](https://cloud.githubusercontent.com/assets/2911176/17454471/12e03cd0-5bda-11e6-8be2-c173a118ba9b.png)

**Comment by mkllnk** [comment]
Yes, I it's the domain change. I could fix that one just by clicking "edit" and then "save".

**Comment by kirstenalarsen** [comment]
great - I’ll go through and do the rest :)

**Comment by pmackay** [comment]
@kirstenalarsen is this fixed now?

**Comment by sigmundpetersen** [comment]
ping @kirstenalarsen 😄

**Comment by daniellemoorhead** [comment]
Am going to close this on behalf of @kirstenalarsen as it's super old and not a priority any longer and isn't relevant to the platform.
