### ISSUE TITLE
Clean up unused OFN Enterprise fields

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#11243]
During inception / analysis I am noting fields on the **_Enterprise_** table in OFN that I think are obsolete and unused (I don't even know where you could update them in the UI?). Noting here as potential papercut to remove
* Pickup Times
* Next Collection At
* Distributor Info

**Comment by kirstenalarsen** [comment]
@mkllnk searched the code and found
I searched the code:
pickup_times: unused.
next_collection_at: used as backup value if the order cycle doesn't have a pickup_time defined for a distributor.
distributor_info: unused.

So let's delete pickup_times and distributor_info only

**Comment by kirstenalarsen** [comment]
@rioug might as well just knock this off and get it out of the way

**Comment by mkllnk** [comment]
I just stumbled across this and thought I better clean it up.

**Comment by kirstenalarsen** [comment]
Thank you. Please ensure it is tracked against macdoch
