### ISSUE TITLE
[Invoices] Tab displayed regardless of order state

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11240]
## Description

When editing an order, the Invoices tab should only be displayed for orders with state `complete`, `resumed` or `cancelled`. However, we can see this is being displayed for other order states, too. This is mentioned in the acceptance criteria [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/10725).

12. Order status that is different than completed/canceled/resumed can't have an invoice tab.

## Expected Behavior

The Invoices tab should only be displayed for orders with state `complete,` `resumed` or `cancelled`.

## Actual Behaviour

The Invoices tab is appearing for all order, regardless of its state.

## Steps to Reproduce

As super admin
0. Enable invoices
1. Visit the `/orders` page and edit a complete order -> notice the Invoices tab - OK
2. Visit the `/orders` page again and edit an order in state `payment` -> notice the Invoices tab - not OK

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/9180d1c6-2d68-4e13-bd3a-1cf1fa3b30b8)

**Comment by drummer83** [comment]
Sure, @bouaik! I will assign it to you.
Looking forward to another contribution of yours! 😊
