### ISSUE TITLE
Create redirects for intuitive ofn aus learn and connect links

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1125]
the obvious urls to send people to are 
openfoodnetwork.org.au/connect and openfoodnetwork.org.au/learn . . but these currently give people 404s

Can we create redirects to the openfoodnetwork.org/au pages from these links so that we can use them?

@serenityhill to check in w @RohanM and @mkllnk as to whether one of you can do this before mon/tues

![image](https://cloud.githubusercontent.com/assets/2911176/17454505/c4255a9c-5bdb-11e6-98d4-eb26ac7b4443.png)

**Comment by mkllnk** [comment]
Yes. That is quite easy to do.

**Comment by kirstenalarsen** [comment]
awesome! any chance you could do today or tomorrow?

**Comment by mkllnk** [comment]
Okay, Deployed.

**Comment by kirstenalarsen** [comment]
thanks so much for this @mkllnk - you're awesome! really appreciate the quick response :)
