### ISSUE TITLE
check if I can restart community.openfoodnetwork.org.au upgrade

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1126]
i may have been running the upgrade when the domain was switched. This is my guess at why the upgrade seems to be frozen (see below)

Is it reasonable for me to assume that this upgrade is not actually running and is ok for me to restart the upgrade? @mkllnk [not urgent - will just leave version out of date until clarified]

![image](https://cloud.githubusercontent.com/assets/2911176/17454829/0e524f6a-5be8-11e6-86dd-53a3f45b581e.png)

![image](https://cloud.githubusercontent.com/assets/2911176/17454834/4a70bc8e-5be8-11e6-8a00-f6763e65869f.png)

![image](https://cloud.githubusercontent.com/assets/2911176/17454835/50cab1fc-5be8-11e6-8c57-158882a46c35.png)

**Comment by mkllnk** [comment]
I just tried an upgrade an it failed. I have to investigate that.

**Comment by mkllnk** [comment]
I upgraded manually with shell access.
