### ISSUE TITLE
[BUU] As a single producer, I should not be able to see the producer dropdown

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11274]
## Description
**- As a:** enterprise user
**- On page:** `admin_products_v3`
**- I want to be able to do:** I should not see the producers dropdown see scenario 1 and design here: https://github.com/openfoodfoundation/openfoodnetwork/issues/11057

## Acceptance Criteria & Tests

1. Login as an enterprise with only 1 producer
2. See that the producer dropdown is hidden
3. Multi-producers profile can still use the dropdown

**Make sure to test as sigle producer and hub profile with single producer enterprise**

**Comment by mariocarabotta** [comment]
just to double check with @RachL : do you think there's any value in showing the producer column for single producer enterprise?

if no, we would use the same logic for https://github.com/openfoodfoundation/openfoodnetwork/issues/11055 + hiding the column itself

**Comment by RachL** [comment]
@mariocarabotta I wonder about the case of a hub user who has access to only one producer, can it reassure them to leave it? I don't have a strong opinion, we van hide it if you think it's best

**Comment by mariocarabotta** [comment]
my rationale for hiding it would be to simplify the UI complexity for producers that are selling on the platform.

thinking about producer-shop signing up > entering their details > starting to create products.
I assume there's no value for them in having the producer filter and the producer column.

Is there a way to identify producer-shop accounts VS hub-shop accounts? maybe the logic would need to be more nuanced

**Comment by RachL** [comment]
we could identify, but maybe a bit too complex at this stage. Otherwise I guess there is also the option to hide the column by default with the column dropdown. But happy to move forward with completely hidden.

**Comment by mariocarabotta** [comment]
let's go with completely hidden for hubs and producer-hubs with only one producer.

I hope the scenario you mentioned (hub user with only one producer) is not super common, and it might be an initial stage as they build their suppliers base
