### ISSUE TITLE
Need help with this issue

### ISSUE THREAD

**Issue by kefayatullahkhadem** [openfoodfoundation/openfoodnetwork#11286]
ey everyone
i installed the ofn on WSL Ubuntu windows 11
and everything is finished here what i have the error
and also i can't run this command

@DESKTOP-DLE9R1G:~/openfoodnetwork$ bundle exec rake db:test:prepare
fatal: No names found, cannot describe anything.
@DESKTOP-DLE9R1G:~/openfoodnetwork$

and this is the log error

[log error.txt](https://github.com/openfoodfoundation/openfoodnetwork/files/12178205/log.error.txt)

**Comment by mkllnk** [comment]
This is a support request which is discussed on Slack.
