### ISSUE TITLE
How to add the translated messages in the notify producers email?

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1128]
Where/how can I translate the messages sent to the producers via the "notify producer" button...
![screenshot from 2016-08-10 17-36-29](https://cloud.githubusercontent.com/assets/8135376/17560114/1b13201c-5f21-11e6-8634-0eea63b452a9.png)

**Comment by myriamboure** [comment]
Do you have the same issue in Norway @sigmundpetersen ? Did you find where to do the translation?

**Comment by myriamboure** [comment]
Ping @blancnic if you have an idea...

**Comment by myriamboure** [comment]
Sorry, actually I remember I translated them in Transifex, but it seems they don't appear in the production instance, any idea @blancnic ? Do we need to wait for a next upgrade or can we just "call" the new translations?

**Comment by myriamboure** [comment]
when I look in Transifex, it seems not all the strings are translated in the message, like the "Here is a summary of the orders for your products" or "Orders summary"... so I'm not sure all the strings are translated...

**Comment by sigmundpetersen** [comment]
Hey @myriamboure ! I can find "Here is a summary of the orders for your products:" in Transifex. We deployed the transifex branch to get the latest translations on the platform.

**Comment by myriamboure** [comment]
It seems only part of the email is translated... 
![screenshot from 2017-05-16 19-56-22](https://cloud.githubusercontent.com/assets/8135376/26120761/216fe6fc-3a72-11e7-8e02-c793c547bcf0.png)
@pacodelaluna I add that to your translation-to-do-list, but no pressure!

**Comment by myriamboure** [comment]
@pacodelaluna we need to have the "notify email" translated and content added in the email... for a test with a local territory who is building a hub to help private restaurants buy directly to producers. After the test if the tool fits their need they will make a donation and/or pay for custom dev. But we do anyway need to translate the notify producers mail... Do you know how we can move forward on that ? Do you have time to work on that ? If you don't please ask Maikel or Rob ;-)

**Comment by myriamboure** [comment]
There needs to be at least some dates so that the producer can identify the order, and the place where it needs to be delivered. Can the "producer instruction" in incoming products be displayed in the mail ? In that case the hub manager can write delivery date and place there.

**Comment by myriamboure** [comment]
I don't know who solved that, it is almost ok, just missing two small translations, closing this issue and opening a specific one.
