### ISSUE TITLE
`MiniMagick::Error` on a product: can't access the product anymore (backoffice nor shopfront)

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#11298]
## Description
Concerned customer: https://coopcircuits.fr/paniers-libres/shop#/shop_panel
When clicking on category `Thés, Cafés`, the request `https://coopcircuits.fr/api/v0/order_cycles/21112/products.json?distributor=732&page=1&per_page=10&q%5Bname_or_meta_keywords_or_variants_display_as_or_variants_display_name_or_supplier_name_cont%5D=&q%5Bprimary_taxon_id_in_any%5D%5B%5D=12` breaks because: 
```
"`convert /tmp/ActiveStorage-17460-20230728-67522-uq4fx3.jpg[0] -auto-orient -resize 48x48^ -gravity Center -background rgba(255,255,255,0.0) -extent 48x48 /tmp/image_processing20230728-67522-pb92oo.jpg` failed with error:\nconvert-im6.q16: insufficient image data in file `/tmp/ActiveStorage-17460-20230728-67522-uq4fx3.jpg' @ error/jpeg.c/ReadJPEGImage/1117.\nconvert-im6.q16: no images defined `/tmp/image_processing20230728-67522-pb92oo.jpg' @ error/convert.c/ConvertImageCommand/3258.\n"
```

related bugsnag: https://app.bugsnag.com/open-food-france/coopcircuits/errors/64a56ee87275560008ed83ad?filters[event.since]=30d&filters[error.status]=open

What is annoying is that we can't change/remove image from concerned product-s, because it seems impossible to retrieve it (in backoffice)

## Expected Behavior
https://coopcircuits.fr/paniers-libres/shop#/shop_panel should work when retrieving all the products 

## Actual Behaviour
Can't access particular product-s, at least one under the "Thés, Cafés" category

## Steps to Reproduce

1. Access https://coopcircuits.fr/paniers-libres/shop#/shop_panel
2. Scroll until we get the 422 error in the console
3. or click on "Thés, Cafés" category
4.

## Workaround
For now, I don't see any workaround ; I would like to unassigned attachement/image to product that cause failing but I'm not sure how to handle it. 

## Severity
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround

**Comment by filipefurtad0** [comment]
This error has not been observed in staging... It seems to affect only FR-prod? Could it related to an instance setting?

On UK, we've had a surge of (other) MiniMagick errors, which have stopped occurring on June the 20th:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/d3a9d8a0-0c3c-4541-80d8-0023fe5c95b6)
