### ISSUE TITLE
[BUU] Display of tax category is not working properly

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11291]
## Description

According to https://github.com/openfoodfoundation/openfoodnetwork/issues/11161 When tax category is "none" the display should be blank.

On Staging FR no matter the tax category the display stays at TVA 5,5%

## Steps to Reproduce

1. Log in as enterprise
2. Create a product with a tax category none
3. See the display is not blank
4. Try another tax category: see the display is not changing

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/d751096d-88e3-4cbd-bc4e-c56df616f1ac)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/9f8f13c5-2d99-4ac7-82c8-e9b72c50c94b)

**Comment by jibees** [comment]
Closing here thanks to https://github.com/openfoodfoundation/openfoodnetwork/pull/11156
