### ISSUE TITLE
SO - Customer can set default addresses during checkout

### ISSUE THREAD

**Issue by bingxie** [openfoodfoundation/openfoodnetwork#1130]
Add a checkbox to the billing and shipping address sections of the checkout page, allowing the customer to set the given address as their default (2h)

When auto-creating a new Customer when an order is placed, auto-assign "name" field using the full name of the billing address given. (1h)

The enterprise user can search/filter the customers(which belongs to current enterprises) and it will auto-complete the address form if the customer has the addresses.

Add a confirm when deleting a customer.

**Comment by daniellemoorhead** [comment]
Hey @bingxie can you let me know if you think you'll get this to Sally for testing this week? We're going to release milestone 1.8.5 on Friday so if it won't be ready by then I'll put it into [v1.8.6](https://github.com/openfoodfoundation/openfoodnetwork/milestone/39).

Cheers!

**Comment by bingxie** [comment]
I will create a PR for review today, then need someone to review it on Friday, I won't work on this Friday, so I think maybe we can put it into v1.8.6

**Comment by daniellemoorhead** [comment]
@sstead can you confirm that this has been added to the user guide? It went through in 1.8.6 but there weren't release notes from you as far as I can see and so I wanted to confirm before I closed this.

**Comment by sstead** [comment]
Hey @daniellemoorhead , yep it was in the [release notes](http://community.openfoodnetwork.org/t/what-s-new-v-1-8-6-162810/720) and covered in the [user guide](https://openfoodnetwork.org/user-guide/advanced-features/customer-accounts-and-tagging/).
