### ISSUE TITLE
[Vouchers] Error 500 (snail) when accessing /admin/enterprises/ENTERPRISE-NAME/edit (staging AU)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11319]
## Description

I had the voucher feature toggle deactivated on staging AU and staged and tested some PRs. Then I activated the toggle again and wanted to test around vouchers. But I get an error 500 whenever I try to access /admin/enterprises/enterprise-name/edit for an enterprise which has vouchers set up.

Here is the Bugsnag: https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64ca2c328383730008cf63e2?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging

## Expected Behavior

There should be no error 500.

## Actual Behaviour

There is an error 500.

## Steps to Reproduce

1. On staging AU as super admin try to access https://staging.openfoodnetwork.org.au/admin/enterprises/konrad-testhub-staging-au/edit

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by mkllnk** [comment]
This is a staging bug only. It comes from changing the database for vouchers and then deploying other code which doesn't have the newest vouchers code.

**Comment by drummer83** [comment]
So can we close or how do we handle this?

**Comment by mkllnk** [comment]
Does it work again when staging the vouchers PR? Then it will resolve itself once that PR is merged.

Generally, we don't have a process to deal with breaking database migrations on staging. The best approach would be to restore a database backup after staging a pull request with migrations. But that would need some work on our deploy process.

**Comment by drummer83** [comment]
> Does it work again when staging the vouchers PR? Then it will resolve itself once that PR is merged.

Yes, it does (PR #10821). The problem is that before merging #10821 we need to test and merge #11117 - which is not possible due to this error 500.

I will try to test #11117 on a different server (UK) for now - no action needs to be taken.

**Comment by abdellani** [comment]
Hi
is this issue still happening?

**Comment by abdellani** [comment]
@RachL 
Since #10821 is merged, I don't see a reason to have that problem.
Maybe the PR that you're testing needs to be rebased on the master branch.

Please let me know.

**Comment by RachL** [comment]
Ok indeed - I think I've staged the release successfully and this is fixed, closing :tada:
