### ISSUE TITLE
[Order Cycles] Incoming exchange accepts supplier fees with order-based calculators

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11326]
## Description

In the scope of #11013, we've discussed the case of OC coordinators adding supplier fees, which are applied over the order.
While we've mentioned this might be an edge case, it would be good to:
- query production DBs to assess how often this is the case (incoming exchanges with supplier fees which are order based-calculators)
- prevent OC incoming exchanges from adding supplier fees with order-based calculators
- maybe finally, migrate existing fees, or contact users? Unsure about how to deal with the existing cases.

A PR to close this issue would focus on filtering the options on the incoming exchange, to display only line-item based calculators.

## Expected Behavior

Incoming exchanges only display supplier fees with line-item-based calculators

## Actual Behaviour

Incoming exchanges accepts supplier fees, with all calculator types (line item and order based)

## Steps to Reproduce

Create a coordinator and a supplier enterprise; having granted the required permissions:

0. As the supplier, create an enterprise fee, with a calculator which operates at the order level, for example, `flat-rate per order`.
1. As a coordinator, create an order cycle
2. In the incoming exchange, add the previously mentioned supplier
3. Notice you can add the supplier order-based calculator fee

## Animated Gif/Screenshot

-

## Workaround

Incoming exchange: Add line-items calculators instead; leave your order based calculators for the outgoing exchage

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.4.5
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by abdulazizali77** [comment]
@RachL @sigmundpetersen id like to work on this 
Just to clarify in this screenshot below, we only want to display PerItem Enterprise Fees correct? 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/23547158/db2c3a8f-efe5-460f-8de9-99a7fe8ce346)

**Comment by RachL** [comment]
This is my understanding as well, but pinging @filipefurtad0 in case there is something I'm missing :+1:

**Comment by filipefurtad0** [comment]
> we only want to display PerItem Enterprise Fees correct?

Yes, that's it @abdulazizali77 :-)

In OFN, we have different calculator types, some have effect over the order, some apply fees over line items. 

In the scope of this issue, the only allowed fee calculator should be:

- Flat Rate (per item)
- Weight (per Kg/Lb)
- Flat percent (which actually acts at the line item level, as discussed [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/10348#issuecomment-1451812701))

The other calculators should not be allowed, on step `2. Incoming products`:

- Flat rate (per order)
- Flexible rate
- Price sack
