### ISSUE TITLE
Add required fields to DFC Enterprise Connector

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#11331]
**_All Global work to be tracked in Clockify #11242 Discovery Endpoints - including testing, code review etc
Aus devs to track in #11242 Task within Macdoch Regen Discovery_**

## Description

Following [here](https://community.openfoodnetwork.org/t/discovery-endpoints-api-dfc/2847) we need to add attributes to the DFC Enterprise Connector so that we can use it as our main supported API endpoint for reading Enterprise information. The Connector itself is already implemented but it only has name and description so we need to add other fields.

So we need to map OFN Enterprise model to DFC Enterprise Ontology. This can be done in Column D [here](https://docs.google.com/spreadsheets/d/1dayTJJtCX63Jr-OS2KdwdQvNeOQLgqeXUOKdoiCDMaE/edit#gid=0_

Once that mapping is done, we need to add the attributes to the Connector.

## Acceptance Criteria & Tests
* Read Enterprises using DFC Connector as JSON file

## Progress

We partly implemented this but then got blocked by the DFC Connector not supporting all fields we need.

- [x] #11397
- [ ] https://github.com/datafoodconsortium/data-model-uml/issues/5
- [ ] Add missing enterprise contact details to DFC API

The following list is the latest from @mariocarabotta:

- [x] enterprise name
- [x] enterprise uid
- [x] short description
- [x] long description
- [x] logo
- [x] address (this is several different fields)
- [ ] fb link
- [ ] insta link
- [ ] website
- [ ] linkedin link
- [ ] twitter link
- [x] product list
- [ ] phone number
- [ ] email
- [ ] contact name

**Comment by mkllnk** [comment]
The latest ontology seems to include everything we need for this. But the Connector still needs updating.
https://github.com/datafoodconsortium/ontology/releases/tag/v1.9.0

**Comment by kirstenalarsen** [comment]
They are very close, pinged 3 Nov to see if they can get it done. We will check in on 9 Nov and make decision whether to keep waiting or to do OFN custom attributes

**Comment by kirstenalarsen** [comment]
Hopefully Maxim's changes will unblock this and we can then just make required changes to the OFN DFC Ruby Connector (testing / confirmation by Friday). 

@mkllnk is also going to take on release management of the DFC Ruby Connector. When working on DFC Ruby Connector directly, please use Clockify #10828 DFC Ruby Connector.

**Comment by mkllnk** [comment]
I'm now a Ruby DFC Connector maintainer. 😄 Most things are unblocked now. The enterprise logo is not included yet.

**Comment by mkllnk** [comment]
@rioug, I started work on this today. I'm just missing the contact name now but ran out of time:

* https://github.com/mkllnk/openfoodnetwork/pull/new/dfc-enterprise-fields

I'll continue tomorrow. Getting this into the next release would be awesome to populate Airtable with our first test enterprises.
