### ISSUE TITLE
Possible XSS vulnerability

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1133]
https://groups.google.com/forum/#!topic/ruby-security-ann/8B2iV2tPRSE

The Rails team just fixed `html_safe` which doesn't escape quotes in the version we use at the moment. @RohanM @oeoeaio Are you aware of any problem upgrading to Rails 3.2.22?

**Comment by pmackay** [comment]
@mkllnk presumably it would make sense to upgrade to the latest v3.2.22.5 release? Is there a special process for updating Rails? Is it a case of try it, run the tests and if all looks ok then it could be merged?

**Comment by mkllnk** [comment]
The last Rails upgrade was a year ago by Rohan: 46aee6f77c600d32c8760b6423cbedd683fe9cca

He had to change two more lines in the Gemfile, but I can't see any other changes related to that. So I guess yes, we just have to try it.

**Comment by lin-d-hop** [comment]
#spreeupgrade
