### ISSUE TITLE
Develop READ Enterprise Groups functionality on the API

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#11335]
**_All Global work to be tracked in Clockify #11242 Discovery Endpoints - including testing, code review etc
Aus devs to track in #11242 Task within Macdoch Regen Discovery_**

## Description

Following [here](https://community.openfoodnetwork.org/t/discovery-endpoints-api-dfc/2847) 

As an API user, I want to be able to read group information and enterprise/group relationships on the API. This will use both the 'Enterprises Groups Enterprises' table (which maps Enterprises to Groups) and the 'Enterprise Groups' table which has information on the Groups

I want to be able to:
* [ ] READ list and info of Groups (uses Enterprise Groups)
* [ ] provide a Group ID and get Enterprise IDs (uses Enterprise Groups Enterprises)
* [ ] provide an Enterprise ID and get Group/s it's in (uses Enterprise Groups Enterprises)
* [ ] provide Group ID and get details of that Group

## Inception notes
NB. As far as I know this does not exist in DFC ontology so we don't need to try and make it 'DFC Compliant' but I'm not sure what that means re. tech . . are we just creating a REST endpoint, or are we creating a DFC one that we then put to DFC but they may or may not include in the standard?

## Acceptance Criteria & Tests
* Read Group information and Enterprise/Group relationships via API

**Comment by kirstenalarsen** [comment]
Slack discussion [here](https://openfoodnetwork.slack.com/archives/C05L39KHX2A/p1691126218923729
)

**Comment by mkllnk** [comment]
DFC agreed to add a new association of Enterprise has many affiliated Enterprises. 

* https://github.com/datafoodconsortium/ontology/discussions/75#discussioncomment-6691148

I haven't seen any action on that decision yet, so I just followed up on Slack.
