### ISSUE TITLE
[Vouchers] 'No payment required' is not displayed after editing the cart

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11358]
## Description

Follow up of #11117.
After editing the cart (with order total < voucher amount before and after editing) the 'no payment required' is NOT displayed on step 2 of the checkout process. A payment method needs to be selected and then on step 3 the payment method and transaction fee are displayed even though the voucher covers the order total.

## Expected Behavior

If after editing the cart the order total is less than the voucher amount, then in step 2 of the checkout there should be the message 'no payment required' instead of the list of payment methods.

## Actual Behaviour

The message is not shown, but the list of payment methods is displayed instead.

## Steps to Reproduce

1. As enterprise user set up a shop with vouchers and a payment method with payment fee.
2. As customer put items in you cart with order total less than voucher amount.
3. Go to checkout and finish step 1.
4. In step 2 enter the voucher code and apply it. -> The message 'no payment required' should show up.
5. Continue to step 3.
6. Edit the cart by clicking 'Edit' next to Order details.
7. Increase or reduce the items but make sure that the order total is still less than the voucher amount.
8. Click checkout again.
9. Finish step 1.
10. Look at step 2: The voucher is still active, but also you must select a payment method.
11. Select a payment method with payment fee.
12. Continue to step 3.
13. Observe that the payment fee is listed and in the order summary and that it is named in the Payment Method area even though the voucher amount is enough to cover the full cost.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/9060e7f9-2f8d-4154-ad35-22fb30e78f52)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by abdellani** [comment]
Hi @drummer83 
I couldn't reproduce the bug. I selected an item that costs 25$ and my voucher's value is 100$
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/0f50b6e2-da98-49ca-a3f1-de319996464b)

When I applied the voucher, the message showed up and the payment methods disappeared (as expected in your description)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/c84fb60b-eaae-4710-be42-d0bee44dc6f3)

The summary looks good
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/0ccb7946-1d8a-42b9-8bf9-80b9e13c71bb)

I increased the quantity to 2, the cost becomes 50$.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/3d54f9cb-5473-4123-b78c-b75069853282)

The payment step page looks good
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/69d64b76-a4c0-4eaa-8e44-d98b53d4f6a8)

can you please check if I missed something?

**Comment by abdellani** [comment]
Here are some other tests that I did:

|test|1|
|-|-|
|voucher|100$|
|quantity|4 (total cost of items = 100$)|
|shipping method| free|
|payment method|they were not listed|
|message: "no payment required"|Yes, it was rendered|
|is the behaviour correct?|I think so|

|test|2|
|-|-|
|voucher|100$|
|quantity|4 (total cost of items = 100$)|
|shipping method| home delivery 2$ (this will make total = 102$)|
|payment method|they were  listed|
|message: "no payment required"|No|
|is the behaviour correct?|I think so|

**Comment by drummer83** [comment]
You are right, @abdellani! I also can't reproduce this issue anymore. It was probably fixed by one of the previous PRs already. :muscle: 
We can close this one here.

Unfortunately I can't play the video you have uploaded. Can you? Is it a problem on my side?
So, I can't really comment on the other problem you have found, sorry.

**Comment by sigmundpetersen** [comment]
> Unfortunately I can't play the video you have uploaded. Can you? Is it a problem on my side?

I think it's a problem in Firefox and that it works in Chrome.
Maybe recommended to use another screen capture tool?
@filipefurtad0 @drummer83 @RachL what's your preferred tool?

**Comment by drummer83** [comment]
Thanks @sigmundpetersen! I will try later.
I'm using Peek (on Ubuntu 22). It required some driver changes to make it work, if I remember correctly. If needed I can try to find and share it. Just let me know.

**Comment by drummer83** [comment]
> When I click on 'Next- Order Summary', I get the following error message in the console.
> Is this related to #8886 ?

Sorry, @abdellani, I can't reproduce this error. Can't tell if it could be related to #8886.
I'd propose you should open an issue if you think it is worth it.
And this one here can be closed because it's fixed already.

**Comment by filipefurtad0** [comment]
> I think it's a problem in Firefox and that it works in Chrome.

Thanks @sigmundpetersen - indeed I could see the video contents in Chrome. Maybe it's about the file format (mp4)?
