### ISSUE TITLE
broken link in new user intro email

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1135]
from ['updating Terms of Service'](http://community.openfoodnetwork.org/t/updating-the-terms-of-service/665/3)
When logged in as SuperAdmin go to Configuration > Content. Here you can insert your own 'Terms of Service URL'. However, I've just had a look on staging, and unfortunately this link doesn't also carry through to the email you have posted above. This link must need to be modified somewhere else. Lynne recently made a related change, which allows instances to set the contact email which is contained in outgoing emails, in their config>content- [G#1090](https://github.com/openfoodfoundation/openfoodnetwork/pull/1090).

**Comment by lin-d-hop** [comment]
PR #1170

**Comment by lin-d-hop** [comment]
Couple more things to consider to complete this issue:
1) Aus ToS is not useful to any other instance so having this as a default seem inappropriate.
2) When ToS field blank the default is not being picked up by ContentConfig. The link should possibly be hidden in this scenario.

**Comment by daniellemoorhead** [comment]
Given the PR has been merged @lin-d-hop do you want to close this issue or leave it open for the extra things you noted?

**Comment by lin-d-hop** [comment]
Closing issue. I doubt anyone will get around to this any time soon so lets wait for someone to pick up the above outstanding tidbits eh? :-)
