### ISSUE TITLE
[Vouchers, Reports] Taxes in reports are not correct, e.g. Sales Tax Totals By Order report

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11364]
## Description

The values in the Sales Tax Totals By Order report are not correct. Other reports may be affected as well.
  - Discounts on taxes should be reflected in the tax column (= original tax minus tax discount).
  - Total without tax needs to be updated accordingly.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/1a0918bb-6357-41ee-bb9b-a0eef5b99413)

## Expected Behavior

Values in reports must be correct.

## Actual Behaviour

Values in reports are not correct.

## Steps to Reproduce

1. Place an order with a voucher and taxes excluded from price.
2. Render the report.
3. Compare the numbers of the report to the numbers of the order in the back office.

## Animated Gif/Screenshot

See above.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by rioug** [comment]
I have a fix ready to go for "Sales Tax Totals By Order" report

I had a look "Sales Tax Totals By Producer" report as well, but if I understand correctly, this is a report from the producer point of view, so voucher discount don't apply here. And from what I could see it doesn't apply to the other reports either. 
But let me know if I missed something.

**Comment by drummer83** [comment]
Thanks, @rioug!
Let's move forward with this one and I will check the other reports when testing this one. 
Sounds good?

**Comment by rioug** [comment]
Sounds good :+1:
