### ISSUE TITLE
[Invoices] Print and send invoice per email per order are missing from action dropdown

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11368]
## Description
When activating the toggle, those 2 options are disappearing from the action dropdown on the edit order page: 

without toggle : 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/9294f2d1-215f-48d3-be35-1925254943f6)

toggle activated : 

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/5670d0d7-dbe9-4825-bc48-000f7d4a648c)

## Steps to Reproduce

1. Go see an order on the admin side
2. Check the action dropdown
3. Now activate the toggle and do the same steps

## Severity

bug-s3: a feature is broken but there is a workaround

**Comment by abdellani** [comment]
Hi @RachL 

I think this issue is already solved on [my previous PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/11345).
I tested locally and I didn't find an issue.

Can you please confirm?
