### ISSUE TITLE
[Vouchers] Negative order total (credit owed) after changing to a shipping method without fee

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11361]
## Description

Follow up of #11117.
When starting a checkout process with a voucher and with a shipping method with shipping fee and later switching to a shipping method without shipping fee the result can be a negative order total amount in the order confirmation and a credit owed in the back office.

## Expected Behavior

Changes in shipping fees must be reflected correctly and must not lead to a negative order total.

## Actual Behaviour

It is possible to have a negative order total.

## Steps to Reproduce

1. As enterprise user set up a shop with a voucher and two shipping methods (one with a shipping fee and one without).
2. As customer put items in your cart with an order total less than the voucher amount.
3. Proceed to checkout and select the shipping method with shipping fee in step 1. 
4. Continue to step 2 and finish it.
5. In step 3 select 'Edit' next to Delivery details.
6. Select the shipping method without shipping fee.
7. Continue to step 2 and select a payment method (if required).
8. Continue to step 3.
9. Look at the order summary with the negative order total.
10. Complete the order.
11. As enterprise user look at the order in the back office and see that there is a 'credit owed'.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/c5fc9ebc-f7f7-40ac-b2bc-5d20bd73c7ea

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by rioug** [comment]
I think a workaround would be to delete and re add the same voucher when coming back to step 2 after editing the shipping.

**Comment by rioug** [comment]
This should be fixed by #11677
