### ISSUE TITLE
[Variant->Edit] Help icon ('?') for unit price is too big

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11388]
## Description

At some point we must have changed the size of the help icon ('?') for unit price on the 'Edit variant' page. 
EDIT: It's the same on the 'Create new product' page /admin/products/new

## Expected Behavior

The full icon should be visible.

## Actual Behaviour

Only the top half of the icon is visible.

## Steps to Reproduce

1. Go to e.g. /admin/products/23717/variants/63286/edit on staging UK
or
2. Go to /admin/products/new

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/03316cdb-87e2-43d6-96fa-1c7a4074b8ce)

## Workaround

None.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.4.6
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by amartyaroy** [comment]
hi @drummer83 
can i work in this issue?
And can you provide me the entire path where I can find the issue in the website i am unable to get the product page

**Comment by jibees** [comment]
Hi @amartyaroy 👋 

I've assigned you ;)
Regarding the path, it's `/admin/products/[PRODUCT_ID]/variants/[VARIANT_ID]/edit`, ie.
 - Go to `/admin/products`
 - Edit a product by clicking on Edit icon on table row
 - Click on 'variants' link
 - Edit a variant by clicking on Edit icon on table row

**Comment by jibees** [comment]
Fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/11525
