### ISSUE TITLE
Can't enter units when setting up new product

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1138]
Unit box has no options on dropdown menu.  Also display as box shows {{ placeholder_text}}
I have flagged this as important because we have a new user (Locavore) trying to set up a shopfront.  I assigned it to @daniellemoorhead because Lynne is away this week and I dint want to wait until she is back to move it forward.  Sorry Danni!
![screenshot 2016-08-23 18 09 13](https://cloud.githubusercontent.com/assets/10517702/17901897/fecf49a8-695c-11e6-9b24-6646ac96501d.png)

**Comment by NickWeir63** [comment]
just letting @MagsHall know about this in case Locavore contact you

**Comment by lin-d-hop** [comment]
@NickWeir63 Can't replicate this. May well have been only a temporary issue while I fixed the broken translations? Can you confirm it's no longer an issue?

**Comment by NickWeir63** [comment]
Yes this is fixed now - thanks @lin-d-hop
