### ISSUE TITLE
Creating or editing Payment Gateways fails

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/openfoodnetwork#1140]
When trying to create a new payment gateway or edit an existing one we get the error page.
Does not happen with "Payment Methods", only "Payment Gateways".
Norway instance, v1.8.4.

Here's the log from Bugsnag:
ActionView::Template::Error - undefined method `association_class' for nil:NilClass
app/serializers/api/admin/payment_method_serializer.rb:5  tag_list	

app/helpers/admin/injection_helper.rb:115  admin_inject_json_ams

app/helpers/admin/injection_helper.rb:27    admin_inject_payment_method	

Caused By: NoMethodError·undefined method `association_class' for nil:NilClass
app/serializers/api/admin/payment_method_serializer.rb:5     tag_list	

app/helpers/admin/injection_helper.rb:115     admin_inject_json_ams	

app/helpers/admin/injection_helper.rb:27       admin_inject_payment_method

@oeoeaio , @mkllnk , @sstead can you verify if this happens in AUS or not?

**Comment by oeoeaio** [comment]
@sigmundpetersen yes, can confirm this is an issue. I have a fix, and will try to get it out tomorrow.
