### ISSUE TITLE
Some EnterpriseFees are missing an enterprise_id

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#11436]
## Error in OpenFoodNetwork Aus

**StandardError** in **db:migrate**
An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  column "enterprise_id" contains null values

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64e532660ea202000802f68e?event_id=64e5326600bec67a113c0000&i=gh&m=ci)

## Stacktrace

    db/migrate/20230616055032_require_enterprise_on_enterprise_fee.rb:5 - change

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64e532660ea202000802f68e?event_id=64e5326600bec67a113c0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by mkllnk** [comment]
Affected servers queried with:
```sql
SELECT "enterprise_fees"."id", "enterprise_fees"."deleted_at" FROM "enterprise_fees" WHERE "enterprise_fees"."enterprise_id" IS NULL
```

au-prod:
```
 id  |        deleted_at         
-----+---------------------------
 682 | 2021-07-13 08:32:41.38938
(1 row)
```

us-prod:
```
 id |         deleted_at         
----+----------------------------
 93 | 2021-11-01 16:50:45.922209
  3 | 2021-11-01 16:50:53.052925
(2 rows)
```

ie-prod:
```
 id | deleted_at 
----+------------
 13 | 
(1 row)
```

**Comment by mkllnk** [comment]
An EnterpriseFee can be referenced by:

* `CoordinatorFee#enterprise_fee`
* `ExchangeFee#enterprise_fee`
* `Spree::Adjustment#originator`
* `Spree::Calculator#calculable_type`

**Comment by mkllnk** [comment]
We can delete a a record with:

```rb
fee.destroy_without_paranoia
```

**Comment by mkllnk** [comment]
Applied to au-prod:
```
fee = EnterpriseFee.deleted.find(682)
#<EnterpriseFee:0x00007fad2559af40                                                     
 id: 682,                                                                              
 enterprise_id: nil,                                                                   
 fee_type: "packing",                                                                  
 name: "Sourcing and packing ",                                                        
 created_at: Thu, 01 Jul 2021 22:32:57.325784000 AEST +10:00,                          
 updated_at: Tue, 13 Jul 2021 18:32:41.389433000 AEST +10:00,                          
 tax_category_id: 2,                                                                   
 inherits_tax_category: false,                                                         
 deleted_at: Tue, 13 Jul 2021 18:32:41.389380000 AEST +10:00>                          

fee.really_destroy!
```

**Comment by dacook** [comment]
Perfect, I think it's a really good idea to go ahead and clean up, given the circumstances. 
For the case of US fee 93, it seems quite a safe thing to do. It might be interesting to check the status of enterprise 492 and if they're still active (if not, then we can be even more confident ;) )

**Comment by mkllnk** [comment]
> It might be interesting to check the status of enterprise 492 and if they're still active (if not, then we can be even more confident ;) )

Good idea. The enterprise record is visible on the platform but the last order cycle was in December 2020. So not active at the moment.

**Comment by mkllnk** [comment]
us-prod:

```
fee = EnterpriseFee.deleted.find(93)
fee.update!(enterprise_id: 492)
/home/openfoodnetwork/.gem/ruby/3.1.0/gems/activerecord-7.0.6/lib/active_record/validations.rb:80:in `raise_validation_error': Validation failed: Calculator can't be blank (ActiveRecord::RecordInvalid)

fee.update_columns(enterprise_id: 492)
=> true
```

It's still an invalid record because it doesn't have a calculator but I think that we can ignore that for now.

```
fee = EnterpriseFee.deleted.find(3)
fee.really_destroy!
```

Deployment successful.

**Comment by mkllnk** [comment]
ie-prod
```
fee = EnterpriseFee.find(13)
fee.destroy
fee.really_destroy!
```

Deploy successful.
