### ISSUE TITLE
Stripe: Stripe Connect setup

### ISSUE THREAD

**Issue by stveep** [openfoodfoundation/openfoodnetwork#1143]
- Setting up Stripe Connect
  - Add gems required: Stripe, Oauth/omniauth
  - DB: Add Stripe accounts table: stripe_user_id, stripe_publishable_key,
  - DB: Add Stripe account to Enterprise
  - Routes: Callback URI to associate connected account with enterprise
  - Model: Add method to Enterprise to add a Stripe account and store keys. Allow only one       Stripe account to be connected at once?
  - Model: Add method to Enterprise to get the Stripe credentials (passed to StripeJS or Stripe  ruby method to get a token and make charges via customer param).
  - Controller: Add action to associate Enterprise -> Stripe on callback
  - Stripe Connect connection error handling (on callback)
  - Stripe Connect webhook handling (?)
  - UI: Add a 'Connect to Stripe' button for each enterprise that the user co-ordinates
    - Can pass in various params (email etc.) to prefill the signup form. Good to include a      profile/website for Stripe to verify.
  - UI: Add instance Stripe account setup to config in super admin

Future:
- When a Customer makes a payment using the Stripe gateway:
  - Create a Stripe Customer on the _instance_ Stripe account (or should this be hub Stripe acct?) if it doesn't already exist (https://stripe.com/docs/connect/shared-customers)
  - This can then be used to make future charges to that Customer account.
  - Should we store this locally or retrieve as needed via Stripe API?
  - Should we have a way of creating a Customer independently of placing an order?
- What happens when...
  - A second co-ordinator of an enterprise tries to connect a new Stripe account?

**Comment by daniellemoorhead** [comment]
Ping @oeoeaio here's the issue where Steve's getting on with Stripe Connect stuff :)

**Comment by stveep** [comment]
Hey @oeoeaio I pushed what I have so far on setting up the Stripe Connect workflow:

https://github.com/stveep/openfoodnetwork/tree/stripe-connect

I still haven't figured out how to authorise the stripe_connect controller action with cancan, but you can work through it as super admin. I can send you the UK Stripe account API keys if you want to test it. I need to add specs and some more error handling and security stuff generally, but for now do you think this is the right place in the UI to set up the Connection, and the right controller/model structure to make the requests and store the details? I put everything in the AdminEnterprises controller but maybe it would be better off in the regular Enterprise one?

**Comment by lin-d-hop** [comment]
Hi @stveep! Hope you're good! Hows this coming along? Is there anything that you could use some answers on? Or you happy? Just checkin in :-)

**Comment by daniellemoorhead** [comment]
This work is considered done, @oeoeaio is now working on #1455 which is setting up Stripe Connect as a Spree payment gateway.

Testing will occur for this as part of #1455.

**Comment by lin-d-hop** [comment]
Passing this to team Aus while the final touches are put into standing orders.

**Comment by oeoeaio** [comment]
Closing as I am pretty sure all of this has been covered off. Let me know if you disagree @stveep.
