### ISSUE TITLE
Add per enterprise feature toggle

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#11445]
## Description

Currently Feature Toggles are limited to per user. This makes many things tricky to work with eg in vouchers you need to apply to the enterprise mangers to activate then also to any shoppers that would test it.

We still want to be able to activate by user for many cases. It was very helpful in early split checkout testing for example.
So this change would be an addition that we could also choose to activate per enterprise.

On Slack @mkllnk has said it would be half a day's work. Maikel please share any other relevant details that might help someone take on this issue.

## Acceptance Criteria & Tests

1. We have the option to enable a feature toggle per enterprise as well as per user
2. If enabled per enterprise all managers and shoppers of that enterprise should be able to access the feature
3. If enabled per user then only the specific users can access, as per now
4. Test different permutations of enabling per enterprise and per user to check that they interact as expected eg if turned on per enterprise and then turned off, it should still work for any users it is turned on for. This kind of edge case.

**Comment by RachL** [comment]
FYI split checkout was only per user as well, never per enterprise
