### ISSUE TITLE
[Invoices numbers] Invoices should have sequential numbers by enterprise

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11458]
## Description
**- As a:** enterprise user
**- On page:** invoices PDF and invoice tab on the edit order screen
**- I want to be able to do:** 

In Europe (and maybe elsewhere) invoices need to be sequential and sellers should get a dedicated series for their sequence.

Currently the invoice code generates a new number per order, we need to change to have a number by hub.

This number also needs to be unique, so the proposal is to use the enterprise ID as a prefix to the number. Sequence is linked to the invoice issue date, NOT the date the order was completed.

Example:

Shop A receives only 2 orders: 1 in June, 1 in November

Shop A enterprise ID is 242.

Let's say the hub manager generate invoices for November first this would give:

- November order invoice has number 242-1
- June order invoice has number 242-2

However, if these 2 orders would have been selected for invoice generation together, this would have given:

- June order invoice with number 242-1
- November order invoice with number 242-2

## Acceptance Criteria & Tests

1. Randomly select orders on various pages: run bulk printing invoices should create sequential numbers for this invoices starting with the enterprise ID
2. Repeat step 1 but selecting orders coming from 2 different enterprises: check the sequence is created per enterprise

Repeat these 2 tests with invoices generation through sending invoice per email and manual 1by1 generation on the edit order page.

This feature should be covered by automated testing :pray:

**Comment by abdellani** [comment]
Hi @RachL 

I have a few questions:

1. the enterprise part of the invoice number will be the distributor ID?
2. I was thinking about the following scenario:

Shop ID: 242
this has two orders: order 1 and order 2
1. The shop owner generates an invoice for order 1, the invoice number will be: `242-1`
2. The shop owner generates an invoice for order 2, the invoice number will be: `242-2`
3. The shop owner edits the quantity of any line item of order 1, (an update that will require generating a new invoice), in this case, the invoice number will be: `242-3`, right?

**Comment by RachL** [comment]
@abdellani 

> the enterprise part of the invoice number will be the distributor ID

Good question! It's the ID we can find on `/admin/enterprises/enterprise-name/edit`


>  The shop owner generates an invoice for order 1, the invoice number will be: 242-1
    The shop owner generates an invoice for order 2, the invoice number will be: 242-2
    The shop owner edits the quantity of any line item of order 1, (an update that will require generating a new invoice), in this case, the invoice number will be: 242-3, right?


Yes this is correct!
