### ISSUE TITLE
Deleted product still in shop front

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1145]
I deleted a product that I had on the food hub under my own supplier account. It's no longer shown in the product list and it's no longer shown in the order cycle but it's still in the shop front.

![screen shot 2016-09-03 at 14 46 19](https://cloud.githubusercontent.com/assets/17590921/18225214/85ea2cec-71e5-11e6-9f07-23b6b6ddb797.png)
![screen shot 2016-09-03 at 14 46 30](https://cloud.githubusercontent.com/assets/17590921/18225215/85ed9788-71e5-11e6-886a-ec3a81f46544.png)
![screen shot 2016-09-03 at 14 47 08](https://cloud.githubusercontent.com/assets/17590921/18225216/85ef330e-71e5-11e6-8382-a493b6e04018.png)

**Comment by OliverUK** [comment]
@lin-d-hop @NickWeir63

**Comment by OliverUK** [comment]
Trying to select the item in the shop leads to the basket continuously updating itself and other strange results.

![screen shot 2016-09-03 at 15 52 34](https://cloud.githubusercontent.com/assets/17590921/18225614/8c7942a6-71ee-11e6-8401-ba730ed62233.png)

**Comment by lin-d-hop** [comment]
Hi @OliverUK,
Seems the Cider is now not available on the StroudCo shopfront.
Perhaps this was just that the cache had not updated?
Are you still experiencing issues with this?

**Comment by OliverUK** [comment]
Agreed it's now gone but it must have been there for a day or so, otherwise I wouldn't have raised it here as a bug.
