### ISSUE TITLE
Delivery report broken

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1146]
It's no longer possible to select any delivery options in this report.

![screen shot 2016-09-02 at 09 27 04](https://cloud.githubusercontent.com/assets/17590921/18225232/e397faa4-71e5-11e6-8802-ef92b6174465.png)

**Comment by OliverUK** [comment]
@lin-d-hop @NickWeir63

**Comment by OliverUK** [comment]
Today it's working, @lin-d-hop

**Comment by lin-d-hop** [comment]
Hi @OliverUK Have you been able to replicate this issue? I can't replicate locally or on production.

**Comment by OliverUK** [comment]
@lin-d-hop 
Hi Lynne,
I've tried again just now and it's still working. Can't really say much more than what the screenshot shows, i.e. that no options came up. Happy to close this for now.

**Comment by lin-d-hop** [comment]
Really odd. If this does come up again please reopen and mark the exact time that the issue occurred so we can try and correlate with other system changes.
Thanks @OliverUK I'll close this for now.
