### ISSUE TITLE
new enterprise sign up screen shows 'state' box instead of 'county'

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1147]
![screenshot 2016-09-04 13 54 37](https://cloud.githubusercontent.com/assets/10517702/18231292/20114e0e-72ae-11e6-9d5d-b93c9fc0fba4.png)

**Comment by lin-d-hop** [comment]
This has now been fixed.

@NickWeir63 Would you close if happy?

**Comment by NickWeir63** [comment]
Thanks
