### ISSUE TITLE
Remove "split_" prefix from the codebase

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11480]
### What we should change and why (this is tech debt)

We've removed the legacy checkout; split checkout is fully enabled. We don't need the `split_` prefix anymore.

### Context

This came up while [splitting](https://github.com/openfoodfoundation/openfoodnetwork/pull/11479)... split checkout files :slightly_smiling_face: 

### Impact and timeline

Simplify code.

**Comment by drummer83** [comment]
Closed by #11889.
