### ISSUE TITLE
Not able to receive mail 

### ISSUE THREAD

**Issue by pavan137049** [openfoodfoundation/openfoodnetwork#1148]
Hi , 
I was successfully able to setup snipe it on Ubuntu 16.04 and able create user and login . But i am not getting user login credentials through mail .
After the setup i edited the Docker.env file with gmail smtp login details. 

please find the attached docker.env file .
# Docker Environment File
# Database Variables

MYSQL_ROOT_PASSWORD=XXXXXXX
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=XXXXXXX
# Email Variables

MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
MAIL_PORT_587_TCP_PORT=587
MAIL_ENV_FROM_ADDR=snipeit.num@gmail.com
MAIL_ENV_FROM_NAME=Snipe IT
MAIL_ENV_ENCRYPTION=tls
MAIL_ENV_USERNAME=snipeit.num@gmail.com
MAIL_ENV_PASSWORD=XXXXXXXX
# SNIPE-IT Variables

APP_ENV=production
APP_DEBUG=false
APP_KEY=Y5hJeC7x1i7OxhDrvrQPlB9KvCorvRdO
APP_URL=http://127.0.0.1:32782
APP_TIMEZONE=Asis/Kolkata
APP_LOCALE=en

**Comment by mkllnk** [comment]
I think you reported your issue in the wrong repository. This is about the Open Food Network. We have nothing to do with snipe-it or docker.
