### ISSUE TITLE
UK production not loading

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1149]
I get this screen when I go to the Stroudco shopfront.  Same when going to openfoodnetwork.org.uk
![screenshot 2016-09-07 10 55 22](https://cloud.githubusercontent.com/assets/10517702/18307788/c9153ef6-74e9-11e6-8d5f-c7efbf4cdc48.png)

**Comment by lin-d-hop** [comment]
@NickWeir63 probs not worth opening a github issue for total server failure... we get enough emails about it as it is.
