### ISSUE TITLE
[Trix] Unordered and ordered lists are not designed uniformly (different margin)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11491]
## Description

Product description can be edited using the Trix editor since #11140. But the ordered list has increased margins compared to the unordered list. They should look the same.

## Expected Behavior

Both listings should have the same design.

## Actual Behaviour

Ordered lists have a much larger margin than unordered lists.

## Steps to Reproduce

1. Edit a product description on page /admin/products/_ID_/edit.
2. Use ordered and unordered lists and shift some to higher levels (using the editor buttons).
3. Click update.
4. Look at the product description in the shop front.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/eb848062-cf1d-47a7-bc45-67d99ab0bc29)

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Mahkxai** [comment]
I'd like to work on this issue. Can I take it?

**Comment by dacook** [comment]
I'd suggest that the spacing between the bullet points is ideal, so the numeric list should match that.

**Comment by HillaryOkello** [comment]
Can I work on this?

**Comment by sigmundpetersen** [comment]
Sure thank you @HillaryOkello ! I'll assign you

**Comment by HillaryOkello** [comment]
I created a PR for this https://github.com/openfoodfoundation/openfoodnetwork/pull/11651

**Comment by sigmundpetersen** [comment]
Thank you @HillaryOkello !
It will be reviewed by our dev team, and if approved it will move on to testing before merge.
They will give you feedback if they have any 🙂

**Comment by HillaryOkello** [comment]
Thanks @sigmundpetersen 
I'll look for another issue I can help solve as I wait 😄
