### ISSUE TITLE
Variant units are not displayed in the shop when created by product import

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#11493]
## Description
When using the product import file -  if there are several variants for a product - the products appear fine in the product list.  However, in the shopfront,  only the units for the first variant in the list are displayed.   The units for the other variants are missing. (Calculations of cost per unit.. are correct.)   Further,  the units appear correct in the product list.   If I delete the non-displayed units in the product list,  and re-enter them manually -  then the units are correctly displayed in the shop.  So -  it seems its an issue with the import file.

## Expected Behavior
The units for all variants should be displayed in the shop -   and this should happen whether the product is created by product import or manually.

## Actual Behaviour
If there are multiple variants for a product,  only the units associated with the first variant listed in the shop are displayed.

## Steps to Reproduce
Create a product with several variants using the product import tool
1.Open a shop with these variants
2.See that only the first variant in the list is displaying units
3.Go to the product list in the app,  and delete and re-enter the units for the second variant in the list
4.Go back to the shop and see that the units now appear.

## Animated Gif/Screenshot
Import file

[Import file -  units not displaying for variants in shopfront.xlsx](https://github.com/openfoodfoundation/openfoodnetwork/files/12517977/Import.file.-.units.not.displaying.for.variants.in.shopfront.xlsx)

Products appear fine in the product list
![units appear fine in product list after import](https://github.com/openfoodfoundation/openfoodnetwork/assets/13171778/271ef5b8-91a8-4229-acfb-28a4c37b30d9)

Shopfront -  the variant units are only displayed for the first variant 
![units only show for the first variant in the shopfront](https://github.com/openfoodfoundation/openfoodnetwork/assets/13171778/9cc370cf-2876-4f5d-b44e-7786ddc7fa6f)

If I manually delete and re-enter the units in the product list,  the variant units display in the shopfront
![enter units manually in the product list,  and they display](https://github.com/openfoodfoundation/openfoodnetwork/assets/13171778/2dc6fe48-3c6c-4138-9117-1e1d5aa0c1bf)

## Workaround
Manually enter the units for all products 

## Severity
I guess this is an s3.
BUT -  for hubs and producers with over 300 products in their product list -  it is pretty time consuming to change the units manually after product import.
I'm also noting issue - 11492 -  which is a second  bug with the product import file.   Both these bugs have happened quite recently (although I can't give you a date).

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by filipefurtad0** [comment]
Hey @tschumilas ,

Both me and @drummer83 tried reproducing the bug you've described (with the file you've kindly provided :pray: ) but failed to do so: it seems now, units are displayed for all variants as expected in the shopfront, after after product import.

Could you please check again, that you are still observing this issue, on the current release? Many thanks for that in advance.

**Comment by filipefurtad0** [comment]
Thanks so much for your feedback @tschumilas ! :pray:
