### ISSUE TITLE
Add Foreign Keys to Database if Needed

### ISSUE THREAD

**Issue by macanudo527** [openfoodfoundation/openfoodnetwork#11507]
### What we should change and why (this is tech debt)
Check if models that have relationships in the rails code also have foreign keys in the database. If there was a potential to create orphaned records, create a script that checks for them in production databases. Create foreign keys where necessary to maintain data integrity.  

### Context
Originally brought up by @mkllnk in https://github.com/openfoodfoundation/openfoodnetwork/pull/11441#discussion_r1314464345

### Impact and timeline
Not a critical issue, but will help with resolving #11482 . This will also help us implement cascading deletes in the database, so that it doesn't have to be done by Rails directly.

**Comment by macanudo527** [comment]
@mkllnk I can write migrations to create the foreign keys. However, to fix invalid records in the existing database I found the gem [yeet_dba](https://github.com/kevincolemaninc/yeet_dba). It seems to do everything we are looking for out of the box. Do you want to try that on the production server? Or should it be a simpler script?

**Comment by mkllnk** [comment]
That's a nice gem. I would need the SQL queries though to execute on all production servers in a script. I don't want to manually use that gem on every server. And the automatic fix may not always be good for us. There are some assumptions and it would be better for us to review any invalid data on a case-by-case basis.

**Comment by macanudo527** [comment]
OK, here is a list of all the foreign keys that are missing and from what tables, excluding polymorphic relationships and including only models defined in `app/models`.
|                                  |                           |
|:--------------------------------:|:-------------------------:|
|     **Table to Be Added To**     |      **Foreign Key**      |
|        column_preferences        |        spree_users        |
|         inventory_items          |        enterprises        |
|         inventory_items          |      spree_variants       |
|     report_rendering_options     |        spree_users        |
|        spree_adjustments         |       spree_orders        |
|        spree_adjustments         |   spree_tax_categories    |
|        spree_credit_cards        |      payment_methods      |
|        spree_credit_cards        |           users           |
|         spree_line_items         |   spree_tax_categories    |
|      spree_payment_methods       |         providers         |
|         spree_shipments          |   spree_stock_locations   |
| spree_shipping_method_categories | spree_shipping_categories |
| spree_shipping_method_categories |  spree_shipping_methods   |
|      spree_shipping_methods      |   spree_tax_categories    |
|       spree_shipping_rates       |      spree_shipments      |
|       spree_shipping_rates       |  spree_shipping_methods   |
|       spree_state_changes        |           users           |
|        spree_stock_items         |   spree_stock_locations   |
|        spree_stock_items         |      spree_variants       |
|      spree_stock_locations       |      spree_countries      |
|      spree_stock_locations       |       spree_states        |
|      spree_stock_movements       |     spree_stock_items     |
|         stripe_accounts          |        enterprises        |
|            tag_rules             |        enterprises        |

There are 24 in total.

**Comment by macanudo527** [comment]
> That's a nice gem. I would need the SQL queries though to execute on all production servers in a script. 

Shouldn't I make migrations to add all the keys? 

> And the automatic fix may not always be good for us. There are some assumptions and it would be better for us to review any invalid data on a case-by-case basis.

What kind of report should I create? Would a simple count of orphaned records work initially?  Or an SQL for each of these, so that users can run it in a DB viewer and decide on what to do for each record?

**Comment by mkllnk** [comment]
> Shouldn't I make migrations to add all the keys?

Yes. I meant SQL queries to check for any orphan entries. For example:
```sql
select count(*) from tag_rules left join enterprises on tag_rules.enterprise_id = enterprises.id where enterprises.id is null
```

I can execute that on all our managed production servers with one command and see that this particular query returns zero for every database and therefore the migration will be successful. If I get results for any of the missing keys then we need to resolve that first.
