### ISSUE TITLE
Dropdown UI tweaks

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11518]
## Description

**- As a:** enterprise user or super admin
**- On page:** `/admin/products_v3` => this page is behind feature toggle `admin_style_v3`
**- I want to be able to do:** 

- [x] change font size to default (14px)
- [x] when picker is active, but nothing is selected/typed in, change placeholder text to search for <label> (if easy enough to implement)
- [x] when picker is active, but nothing is selected/typed in, change placeholder text color to #BABDBE ($silver-sand)
- [x] when picker is active, change border color to $orient
- [x] when picker is active, add shadow to list container (style added to [Colours guide](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Design-styleguide:-colors-and-shadows))
- [x] add a 4px border to the list (i know this might be painful with the scrollbar. if too complex, let's not worry about it
- [x] for producers and categories, in the list of options, include an All producers, All categories option
- [x] active and hover list items to have same style, see [this prototype](https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?page-id=373%3A2076&type=design&node-id=373-2077&viewport=238%2C463%2C0.23&t=dtlWH3LOdt8Sbqqp-1&scaling=min-zoom&starting-point-node-id=373%3A2077&mode=design) for example
- [x] related to previous, increase thickness of vertical line to 3px
- [x] increase height of each list option to 36px
- [x] add top and bottom margin of 4px to the list 
![Screenshot 2023-09-11 at 11 20 43](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/aff961ff-da3c-4bb2-b13c-54a4cd9461a5)
- [x] after a list item is selected, the field is still active, it should go back to default state (see screenshot below)
![Screenshot 2023-09-11 at 11 05 32](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/2b4f95b1-1469-4c17-b7b0-bb58599f6def)

#### Additional nice to have requirements
- Handle long content better. (either truncate with ellipsis, or allow field to stretch in height?)
- On all selects: change icon to U+F078 chevron_down
- Search row columns: search input can grow, so we don't have whitespace. dropdowns can sit closer to search button. search input and dropdowns should each have a min-width.

Figma screens are available here >
https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=378-3907&mode=design&t=hqimHkMq8OKx5CII-0

## Acceptance Criteria & Tests

1. Activate feature toggle
2. Log in as enterprise
3. On  `/admin/products_v3` the dropdowns should met the above criterias

Warning: if your user has access to only one producer, you won't see the producer dropdown

**Comment by dacook** [comment]
I think most of the styles for dropdown will be in here: `app/webpacker/css/admin_v3/components/dropdown.scss`

This is behind a feature toggle, which you can enable on your dev enironment easily using the instructions here: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Feature-toggles
IE: http://localhost:3000/admin/feature-toggle/features/admin_style_v3

**Comment by Hanaffi** [comment]
feel free to assign this to me too

**Comment by sigmundpetersen** [comment]
Thank you @Hanaffi .
Don't hesitate to ask if you have any quesions!

**Comment by dacook** [comment]
Hi @Hanaffi , just wondering if you've been able to make any progress on this? Let me know if you have any questions (or you can also ask technical questions in #dev in Slack)

**Comment by dacook** [comment]
As I haven't heard from Hanaffi, I'll give this a go.

**Comment by mariocarabotta** [comment]
nice to have: change icon to U+F078

![Screenshot 2023-12-05 at 13 55 49](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/af6a91a9-b4f1-4fca-a4ae-2126f4cee9d3)

**Comment by dacook** [comment]
> * active and hover list items to have same style, see [this prototype](https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?page-id=373%3A2076&type=design&node-id=373-2077&viewport=238%2C463%2C0.23&t=dtlWH3LOdt8Sbqqp-1&scaling=min-zoom&starting-point-node-id=373%3A2077&mode=design) for example

Hi @mariocarabotta , I noticed in the prototype, that when you hover over the list, the active (currently selected option) appears without the left-border and background. Just confirming that this is intentional and I should follow the prototype?

**Comment by dacook** [comment]
>  change font size to default (14px)

Also, confirming that all form inputs should be 14px? I've updated them across the board, including older dropdowns:

![Screen Shot 2023-12-05 at 5 23 58 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/21e8c473-262b-4930-aaf3-5e828f394f31)

![Screen Shot 2023-12-05 at 5 21 19 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/2615cd8a-fa61-4c7f-bcb7-7a63945d62f0)

**Comment by mariocarabotta** [comment]
> > * active and hover list items to have same style, see [this prototype](https://www.figma.com/proto/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?page-id=373%3A2076&type=design&node-id=373-2077&viewport=238%2C463%2C0.23&t=dtlWH3LOdt8Sbqqp-1&scaling=min-zoom&starting-point-node-id=373%3A2077&mode=design) for example
> 
> Hi @mariocarabotta , I noticed in the prototype, that when you hover over the list, the active (currently selected option) appears without the left-border and background. Just confirming that this is intentional and I should follow the prototype?

Let's keep this consistent and have the active WITH left border and background. thanks for picking it up, sometimes it takes ages to make these sort of things work in a prototype

**Comment by mariocarabotta** [comment]
> Also, confirming that all form inputs should be 14px?

yep let's do it

**Comment by dacook** [comment]
> add top and bottom margin of 4px to the list
> add a 4px border to the list (i know this might be painful with the scrollbar. if too complex, let's not worry about it

@mariocarabotta, I tried this and have two options:

**1.** ![Screen Shot 2023-12-12 at 3 35 43 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/7577800d-2003-4cc3-a034-6942657abf3b) **2.** ![Screen Shot 2023-12-12 at 3 34 54 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/170e1467-b833-4d48-b1ca-1c06a87ddf00)

With option one, the scrollbar stops at the 4px margin, and we see the rounded edges. With option two , the scrollbar extends all the way to the top/bottom, but it doesn't obey the rounded edges. Also the 3px teal line doesn't.

I think option 2 looks and feels the best, because you can barely notice the absence of rounded edges. What do you think?

**Comment by mariocarabotta** [comment]
trust you with option 2!
