### ISSUE TITLE
UK security certificate warning

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1151]
I'm still getting these warnings using Firefox:

![screen shot 2016-09-08 at 16 32 00](https://cloud.githubusercontent.com/assets/17590921/18356219/c597ae76-75e3-11e6-93e8-74f8905e9ff4.png)
![screen shot 2016-09-08 at 16 32 10](https://cloud.githubusercontent.com/assets/17590921/18356220/c59b643a-75e3-11e6-9e1d-1907247da3ca.png)

@pmackay @lin-d-hop

**Comment by lin-d-hop** [comment]
Have you tried F5 to refresh the page? I can't replicate with my Firefox.

**Comment by NickWeir63** [comment]
it is opening OK for me on firefox too.  @OliverUK did you say that Liz Terry was getting this message too?  If so is it OK with you if I contact her and see if we can track down why this is happening for some people and not others?  I could ask her which browser she is using, which version of Windows, what hardware.  @lin-d-hop  is there anything else I should check with her?

**Comment by lin-d-hop** [comment]
The message is about a physical thing that has now been fixed. I have no idea how SSL certs could be an error happening on some computers and not others... apart from refreshing browsers I have nothing else to suggest :-(

**Comment by OliverUK** [comment]
Thanks all for the quick responses.
I still get the warning after clearing the browser cache and clearing "offline content" and after restarting Firefox with add-ons disabled. 

Quite possible that it's a problem my end but I'm just concerned that whatever is causing it may also be happening for others. 

I copied the following from the browser window:

> https://openfoodnetwork.org.uk/shops#/

Peer's Certificate issuer is not recognized.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

Certificate chain:

-----BEGIN CERTIFICATE-----
MIIFDzCCA/egAwIBAgITBpsz4RiCOo0XKtn6zbD4bkVA+zANBgkqhkiG9w0BAQsF
ADCBrzELMAkGA1UEBhMCVVMxETAPBgNVBAgTCElsbGlub2lzMRAwDgYDVQQHEwdD
aGljYWdvMSEwHwYDVQQKExhUcnVzdHdhdmUgSG9sZGluZ3MsIEluYy4xNzA1BgNV
BAMTLlRydXN0d2F2ZSBEb21haW4gVmFsaWRhdGlvbiBTSEEyNTYgQ0EsIExldmVs
IDExHzAdBgkqhkiG9w0BCQEWEGNhQHRydXN0d2F2ZS5jb20wHhcNMTYwOTA3MDQ0
ODExWhcNMTcwOTA3MTA0ODExWjAlMSMwIQYDVQQDExp3d3cub3BlbmZvb2RuZXR3
b3JrLm9yZy51azCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALE22x1p
ntRrAt/lxH+9JzDUYTZcZqR+E9C1HUVxskSYcaTgIZgOPgVUw81HL2H0RfJb9Gb6
hw53m+tmVqigG9oU1hMOjRSCsyVflssfHG7sZF2BwagDj8khKrToXgHACIW+gntk
Zz8WWCuDSrjuohtRnNaAUN+tEgcQ8EYQCQLKI0PKWjBTISdx/n1IoiAS2mqar+BG
BUk4EAYuSTXkMb/ncExghM3FyWEM/8GBQjjLXBu7AFkHlwDMJy1y1GW3TzKkAJWN
qOuxDmcz5XNKxU739yW4ekzQzFCwjIwOMteeMrLxKUfNoZ1OQ5TG6EAQVHXrvJqU
UuSkuQ7n8frPcYcCAwEAAaOCAaswggGnMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/
BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBQPmcXN+KdtYAjY
Er1Wo8FbwdL8vjAfBgNVHSMEGDAWgBT0HOI6r7ak5Nnpnf7vHHelYz3viDBIBgNV
HSAEQTA/MD0GDysGAQQBge0YAwMDAwQFAzAqMCgGCCsGAQUFBwIBFhxodHRwczov
L3NzbC50cnVzdHdhdmUuY29tL0NBMD0GA1UdEQQ2MDSCGnd3dy5vcGVuZm9vZG5l
dHdvcmsub3JnLnVrghZvcGVuZm9vZG5ldHdvcmsub3JnLnVrMDYGA1UdHwQvMC0w
K6ApoCeGJWh0dHA6Ly9jcmwudHJ1c3R3YXZlLmNvbS9EVkNBMl9MMS5jcmwwcQYI
KwYBBQUHAQEEZTBjMCYGCCsGAQUFBzABhhpodHRwOi8vb2NzcC50cnVzdHdhdmUu
Y29tLzA5BggrBgEFBQcwAoYtaHR0cDovL3NzbC50cnVzdHdhdmUuY29tL2lzc3Vl
cnMvRFZDQTJfTDEuY3J0MA0GCSqGSIb3DQEBCwUAA4IBAQAAeUh3bPHD6P/slNAM
xzTql+yJ7x1L1ruep27P1cOGeRAwUCuyJh9cYZfD8sNXs88xdF6BtqFqpXyNyb4S
muKQBclvKOF2LHdcRyb6bpD8+oFPOlLwLX9chbdKHHkHuJDgP/M8TB+m0HPXMtaK
2V4Za95Nr4cxU5e1xbnHIopXWGysW3nGl8Ya7Wpq+n6K+988B7WK8kzUC7nYC82Y
TGX3MvSdOH3ZAOhvB7PQHZTkzEZ+6jOj5HZBp+7wjQoyOPQVEbvwx/afTELSJBor
70kiZxxCdw9Yusa39lFMY88FKrnfYSObaTvlKfBqdU7xxJRZdrUcMBCeZEZVQD+5
gd1+
-----END CERTIFICATE-----

**Comment by myriamboure** [comment]
We got the same problem in France, it regularly happens, especially with new computers/users, and with Firefox. @gnollet is working on it also, it might be the same issue, we also use LetsEncrypt certificates.

**Comment by gnollet** [comment]
I think there is missing some information on certificate.
Please have a look on this link
https://www.ssllabs.com/ssltest/analyze.html?d=openfoodnetwork.org.uk

You should include chain certificate on the config.

**Comment by RohanM** [comment]
Agreed. I had a look at the docs from the certificate issuer (Trustwave), and it says they provide a `chain.crt` file with the certificate. If you append this at the end of the certificate used by nginx and then reload nginx, the chain error should disappear in ssllabs.

I noticed one other small thing. When I visit openfoodnetwork.org.uk, I'm redirected to `https://openfoodnetwork.org.uk//` (note the double / on the end). Perhaps there's something in the nginx rewrite rule that could be tightened up?

**Comment by lin-d-hop** [comment]
ok @pmackay was aware of this and said he was going to fix it today. @pmackay can you confirm? this is high priority.
Thanks @RohanM and @gnollet!

**Comment by pmackay** [comment]
Updated this. @OliverUK could you see if it resolves your issue?

That SSLLabs site is seriously detailed! I think the chain.cer is now in place. We get a "B" though, other issues:

```
Forward Secrecy 	Weak key exchange   WEAK
Strict Transport Security (HSTS) 	Invalid   Server provided more than one HSTS header
Uses common DH primes 	Yes   Replace with custom DH parameters if possible (more info)
```
I dont yet know what those mean, but hopefully not urgent to fix....

**Comment by pmackay** [comment]
@myriamboure when you say it happens regularly, how often? Is it every time the Letsencrypt cert is updated? Or at different times?

**Comment by OliverUK** [comment]
@pmackay Yes, the warning has now gone!

**Comment by NickWeir63** [comment]
I just had this email from a Stroudco shopper who had previously been having this problem:
Hi Nick, 
It's all working fine now. I use a Samsung Note 8 tablet computer and use the Google Chrome app as my browser. 
Thanks for sorting it all out!
Liz x

On 8 Sep 2016 20:12, "Nick Weir" <nick@nickweir.co.uk> wrote:
Dear Liz
I hope you are well.
Oliver told me that you have been having problems opening the Stroudco shop website.  I am very sorry to hear this.
We have now made some changes to the website server and it seems to have solved the problem for almost everyone – except for Oliver when he uses the Firefox browser.  If you have time please could you let me know if the problem is persisting for you and if so:
-          Which browser are you using?
-          Which version of Windows?
-          What computer/mobile device?
With big apologies for the hassle and best wishes to you and Denise
Nick

**Comment by pmackay** [comment]
Is this ok to close then @lin-d-hop @NickWeir63 @OliverUK ?

**Comment by OliverUK** [comment]
From a UK perspective yes, @pmackay.

**Comment by NickWeir63** [comment]
Fine by me - thanks very much to all who sorted it
