### ISSUE TITLE
[BUU] Saving and success message tweaks

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11517]
This card builds on top of scenarios 7 and 8 of #11059 

**Saving overlay**

- [x] blocking the table interface (but users will still be able to refresh or move to a different screen)
- [x] loading should be always visible even if I have scrolled below the fold. see [this issue for more details on current behaviour](https://github.com/openfoodfoundation/openfoodnetwork/pull/11565#issuecomment-1746814011). Also note that this specific behaviour might be overlapping with sticky table header, and sticky "products have changes" container, described [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/11058)

Designs here > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=657%3A3131&mode=design&t=M5n7m73a4MSXR9jQ-1
![Screenshot 2023-09-11 at 10 23 18](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/e75ec9e9-a2ba-49cd-bd24-1c70dd1eac47)

Success message

- [x] temporary message docked at the bottom center of the page
- [x] can be dismissed by clicking the button
- [x] will dismiss automatically after 4 seconds
- [x] user can still interact with the screen interface

Designs here >> https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=658%3A3704&mode=design&t=M5n7m73a4MSXR9jQ-1
(Click ▶️ button at top-right to preview the workflow -- I had to log in for it to work)

![Screenshot 2023-09-11 at 10 34 10](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/a35becf2-8c78-456a-855b-471c9e9ec201)

**Comment by mariocarabotta** [comment]
The overlay spinner can just say "Loading" and be used across different contexts

**Comment by mariocarabotta** [comment]
when testing styles across different pages, please add any messages with the wrong style / type in the issue below and they will be updated separately 

https://github.com/openfoodfoundation/openfoodnetwork/issues/11884

**Comment by mariocarabotta** [comment]
when testing styles across different pages, please add any messages with the wrong style / type in the issue below and they will be updated separately 

https://github.com/openfoodfoundation/openfoodnetwork/issues/11884

**Comment by dacook** [comment]
Discussed with Mario; we don't need a specific "Saving" status, the current "Loading" message is sufficient and perhaps even preferable.
So all done!
