### ISSUE TITLE
Enlarged unit price tooltip image, on variant edit page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11524]
## Description

Maybe introduced by [angular removal](https://github.com/openfoodfoundation/openfoodnetwork/pull/10833) from the admin pages?

The tool-tip image found on the variant-edit page appears enlarged and with incorrect shape. Function is not affected: if we click on it, the box is still displayed, as usual. It just affects readability and usability.

## Expected Behavior

Tooltip should appear with the correct size and shape:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/27b75b45-8a6c-41dc-9ccd-a5e0735c3274)

## Actual Behaviour

The question mark / tooltip image appears enlarged and partially hidden. There are also errors in the console, not sure if related:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/eb30d6bd-2372-4ae5-ae50-a59eb8015559)

## Steps to Reproduce

1. Visit the variant-edit page for a given variant, /admin/products/<product_id>/variants/<variant_id>/edit`
2. Notice the poor readability on the unit price tooltip image

## Animated Gif/Screenshot

See Expected and current behavior.

## Workaround

-

## Severity

Only backoffice users impacted. Function not compromised. Regression. Proposing:
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: tested on v4.4.10, but around for a while now I think«
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by RachL** [comment]
Huhu this title sounded like spam in my mailbox.

@jibees I would not fix this on the old form. It has been like this for weeks now - let's focus on getting admin style v3 out and fix it there?

**Comment by jibees** [comment]
yep, but it's very ugly in the admin style v3 as well... And it makes me feel bad.

<img width="849" alt="Capture d’écran 2023-09-11 à 15 16 38" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/a546ba98-99d4-4ac6-8822-eb7a9dc7ee65">

**Comment by RachL** [comment]
@jibees yes my proposal was to fix it on admin v3 but only there.
