### ISSUE TITLE
[Invoices] New and unique template

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11538]
**To be done behind the feature toggle "invoices"**

## Description

**- As a:** enterprise user and super admin
**- On page:** invoices PDF
**- I want to be able to do:** see the new and unique invoice template

Full template: [newtemplate_v3.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTAvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1b5f66994f4397897b123cc340f11a32ffe5377c/newtemplate_v3.pdf)

Breakdown:

- [x] Title is always the same: TAX INVOICE - but needs to be translated via Transifex
- [ ] Top left corner:
![image](https://github.com/openfoodfoundation/wishlist/assets/6525576/fe5e8226-0560-4102-bd65-ca1807844e3c)

- This comes from `/admin/enterprises/ENTERPRISENAME/edit#/address_panel` and `/admin/enterprises/ENTERPRISENAME//edit#/contact_panel` UNLESS the enterprise has field `/admin/enterprises/ENTERPRISENAME//edit#/business_details_panel`

- ABN & ACN values come from `/admin/enterprises/ENTERPRISENAME//edit#/business_details_panel`

- Terms "ABN" and "ACN" need to be translated through transifex

- [ ] Next:

![image](https://github.com/openfoodfoundation/wishlist/assets/6525576/a6b693dd-360e-458c-aa4e-513e0ffa8a35)

- Titles need to be translated through transifex
For values: 
- invoice numbers are handled by https://github.com/openfoodfoundation/openfoodnetwork/issues/11458
- issue date is the date when the PDF was generated for the first time
- date of transaction is order completed_at date
- order number is order number :-)
- date of service is described by https://github.com/openfoodfoundation/wishlist/issues/58
- OC name comes from what the user has put in step 1 of the OC the order is linked to

- [ ] Top right: the logo can be uploaded in `/admin/enterprises/ENTERPRISENAME/edit#/images_panel` but is displayed or not displayed by a checkbox in `/admin/enterprises/ENTERPRISENAME//edit#/business_details_panel`

- [ ] Customer billing address comes from what the shopper has given during checkout

- [ ] Table content

- Column titles should be translated through transifex

- Item column contains product name and producer names. Unit price is shown between brackets has described in https://github.com/openfoodfoundation/openfoodnetwork/issues/11393

- Items columns contains also the name of the shipping method (here "home delivery" and the type (shipping or pickup). :warning: **even if there is no fee** then the line just display 0 in total last column

- Items columns contains also - like today - the voucher code and the names of each manual adjustment. 1 adjustment = 1 line

- Qty column is the quantity bought by the shopper

- Weight / VOL comes from final_weight in BOM

- Price per unit **excl. tax**  is Total price **excl. tax** / qty

- Total price **excl. tax** is qty * price per unit

- Tax rate is the tax rate linked. For shipping methods, the tax rate can be found at instance settings level

- Total incl. price is the total price on the order

- Bottom line totals need to show in that order: Total amount excl. tax / total tax amount per type of tax + amount of total tax / total amount tax included. **All total titles need to be translated through transifex**

- [x] This section of the template comes from both previous template and has not changed:

![image](https://github.com/openfoodfoundation/wishlist/assets/6525576/d9ec5328-3404-4724-b13e-b631d282e4bd)

- Order note is added by hub manager on the order detail page

- the text is added by hub manager in  `/admin/enterprises/ENTERPRISENAME//edit#/business_details_panel`

- [x] Terms of Sales behavior is described in https://github.com/openfoodfoundation/openfoodnetwork/issues/11355

## Acceptance Criteria & Tests

1. Turn on the toggle
2. Check fields and PDF appear as described above
3. Previously generated invoices have not changed
4. Check super admin settings to switch template are gone
5. Check you still can change order of product by supplier through `/admin/enterprises/ENTERPRISENAME//edit#/business_details_panel`
6. Check enterprise that are tax registered and enterprises that are not
5. Deactivate the toggle and check previous templates still work

**Comment by abdellani** [comment]
Hi @RachL 
I have a few questions:
1. what does `Date of Service` mean? 

2. The unit price (or price per unit) column is not rending the unit price of the line items, but the `price_with_adjustments`

price_with_adjustments = price + ((enterprise fees sum) / quantity )

Do we want to show the price or `price_with_adjustment` ?
In both cases, we'll exclude the tax (added or included)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/064a6ad8-3d50-42c1-9f24-956b73e06d9e)

3. do we want to hide the tax rate column when the tax of the order = 0 (this is the current behavior)?

**Comment by RachL** [comment]
Hi @abdellani thanks for all this :) Here are some answers:

1. date of service is the last issue I need to write up (the wishlist is here https://github.com/openfoodfoundation/wishlist/issues/58 but the rule is not simple and I'm trying to see if we can simplify it). I'm still working on it. Can we add the date later or do you prefer to have everything now?

2. If currently we use `price_with_adjustment` we should keep `price_with_adjustment` thanks for this info!

3. YES! Sorry I didn't know we did this (too many test cases!)

**Comment by abdellani** [comment]
>  Can we add the date later or do you prefer to have everything now?

No, take your time :) 


Thank you  @RachL
