### ISSUE TITLE
[Enterprise fees w/ Tax Report by Producer] Error 500 when orders have variants not included in the OC

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11530]
## Description

Follow-up from https://github.com/openfoodfoundation/openfoodnetwork/pull/11013.

An order with a given variant is placed; the admin later removes the variant from the respective order cycle. If the report is ran, and the placed order has an enterprise fee, then the user will experience an error 500.

UPDATE: Since #11657 there is no error 500 anymore, but an error message instead. However it should be possible to render the report and there should be no error.

Investigation: https://github.com/openfoodfoundation/openfoodnetwork/pull/11013#issuecomment-1683751014
Conclusion: https://github.com/openfoodfoundation/openfoodnetwork/pull/11013#issuecomment-1684038522

## Expected Behavior

Users do not experience an error 500 when generating the report, after variants from orders with enterprise fees were removed from the respective order cycle. 

## Actual Behaviour

Users currently experience an error 500 when generating the report, after variants from orders with enterprise fees were removed from the respective order cycle. 

## Steps to Reproduce

1. Create an order from an order cycle with supplier level enterprise fees
2. Edit the order cycle and remove the variant, from that order cycle.
3. Run the Enterprise fees w/ Tax Report by Producer report
4. See the error 500

## Workaround

-

## Severity

bug-s3: a feature is broken but there is a workaround
(there is no workaround, but this report has been marked as deprecated)

## Your Environment

* Version used: feature should be introduced on the upcoming v4.4.11
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**ActionView::Template::Error** in **ReportJob@default**](https://app.bugsnag.com/open-food-france/coopcircuits/errors/6529a85feedd3c0008fe92b6?event_id=6529aa8400c72550832e0000&i=gh&m=li)
