### ISSUE TITLE
[Enterprise fees w/ Tax Report by Producer] Remove deprecation styling from the reports page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11531]
## Description

After we close #11529 and #11530 we should in principle be in the state where we can remove the deprecation styling from the reports page, introduced [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/11013#issuecomment-1715109841).

## Expected Behavior

Link to the Enterprise fees w/ Tax Report by Producer should not appear as deprecated.

## Actual Behaviour

Link to the Enterprise fees w/ Tax Report by Producer appears as deprecated.

## Steps to Reproduce

1. Visit `/admin/reports`
2. Notice de deprecation styling on the Enterprise fees w/ Tax Report by Producer link.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/f28b04d5-138a-464a-9547-900c45053f87)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: feature should be introduced on the upcoming v4.4.11
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by dacook** [comment]
@filipefurtad0 , one of the dependent issues is still open. Is this still blocked?

- https://github.com/openfoodfoundation/openfoodnetwork/issues/11529

**Comment by sigmundpetersen** [comment]
This is unblocked, ref. https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1716400836719719

**Comment by filipefurtad0** [comment]
>  Is this still blocked?

No, not anymore. I've forgotten to assign myself and remove the label - thank you @sigmundpetersen. Apologies if this caused confusion @dacook .

The remaining issue #11529 is complex, so the idea is that it stays open for now (as per Slack thread pointed above).
