### ISSUE TITLE
Order Cycle Supplier Totals report shows incorrect producers

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1154]
I set up the report to show orders for just one producer and although the csv report that I downloaded from the report was accurate, the report on the screen showed all producers for that order cycle - not just the one producer I had selected.
Here is the screenshot showing incorrect producers.....
![screenshot 2016-09-15 10 49 44](https://cloud.githubusercontent.com/assets/10517702/18545786/89232656-7b32-11e6-9877-584b98a9455a.png)
....and here is the downloaded csv showing the one correct producer
![screenshot 2016-09-15 10 53 22](https://cloud.githubusercontent.com/assets/10517702/18545812/a69171d4-7b32-11e6-86d7-064068f0c5df.png)

**Comment by OliverUK** [comment]
Have you tried clicking Search again with the CSV box NOT ticked. I seem to remember that with the box ticked, it doesn't necessarily update what's on the screen.

**Comment by NickWeir63** [comment]
Yes you are right - thanks Oliver.  If I uncheck the download CSV box then it does refresh the screen accurately.  So this is now a very low pirority bug - but it would be nice if the screen reflected what is being downloaded to the csv

**Comment by Matt-Yorkley** [comment]
So if CSV checkbox is selected the search button downloads the CSV, but if not it updates the search. Would it be clearer if there were two separate buttons instead, one for search and one for download?

**Comment by myriamboure** [comment]
This seems to be working fine now, so closing that issue
![capture du 2018-08-31 21-10-28](https://user-images.githubusercontent.com/8135376/44931559-589ec300-ad62-11e8-82b4-9fd4b4acfc3c.png)
