### ISSUE TITLE
[OFN BE] Shopfront does not fully load products

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11559]
## Description

There is a shop in which products are not fully loaded; error `"object must respond to #price and #quantity"` is triggered:
https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/65049aef2ae59a00087d7087?filters[error.status]=open&filters[event.since]=30d&event_id=6508172100c58c4da2900000

## Expected Behavior

Products should load.

## Actual Behaviour

Full product list not loading (endless spinner)

## Steps to Reproduce

1. Hard to reproduce, as the product seems to have been removed or gone out of stock in the meantime

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/ee9740f1-6bb2-4185-9c0e-01dc7572ed6c)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.4.10
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by jibees** [comment]
I guess this is related to https://github.com/openfoodfoundation/openfoodnetwork/issues/11521 ?

**Comment by filipefurtad0** [comment]
> I guess this is related to https://github.com/openfoodfoundation/openfoodnetwork/issues/11521 ?

Nice catch @jibees . I could not access the Bugsnag error for FR prod, so I'm not 100% sure they're the same, but looks likely.

**Comment by jibees** [comment]
Yeah, I could not access  either (I should have copy/paste it), but I'm 99% sure that was the same error message.

**Comment by filipefurtad0** [comment]
Great - let's close this one then :ok_hand:
