### ISSUE TITLE
Delivery report - Customer Delivery address incorrect

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1155]
@MagsHall @lin-d-hop 

When a customer puts in a separate delivery address for his current order, this doesn't seem to come through in the report. I can't screenshot it without compromising personal data but I'll email you the information shortly. Have opened this issue to keep track and for easy commenting. 

Thanks 
Oliver

**Comment by lin-d-hop** [comment]
@rhodri While you are making changes to the delivery report would you take a look at this as well?

**Comment by lin-d-hop** [comment]
PR #1177

**Comment by lin-d-hop** [comment]
Merged. Thanks crew!
