### ISSUE TITLE
Alphabetical sorting in reports confused by capitals

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1156]
OFN reports sort alphabetically by surname unless a customer's name is spelled all in capitals or alternatively (out of laziness) they omitted to capitalise the first letter. 
In the example below, MU was put before Mi thanks to the difference in capitalisation.

![screen shot 2016-09-15 at 14 25 50](https://cloud.githubusercontent.com/assets/17590921/18551558/d8244f8c-7b50-11e6-8ae9-f4fc78080b67.png)

At the very end of the list we find one customer whose name starts with M but comes after W, again thanks to the capitalisation.

![screen shot 2016-09-15 at 14 29 54](https://cloud.githubusercontent.com/assets/17590921/18551607/08c36b32-7b51-11e6-8847-17b89f6c91c6.png)

I'd be happy to adjust the spelling but OFN doesn't seem to have anywhere to display (and edit) customer's details. I know there is a customer section but all the data apart from email addresses is blank.

**Comment by lin-d-hop** [comment]
Hi @rhodri 
Am I right in thinking you were going to take a look at this one?
I like your thinking that as this spans a number of reports it will help you get your head around reporting a bit before we look at overhauling.
Nice one!

**Comment by Matt-Yorkley** [comment]
Maybe customers' names could be set to be capitalised uniformly on save as well, so the data is more uniform in the future?

**Comment by YanhanLyu** [comment]
Hi, I'm working on this ticket and want to check how to reproduce the issue. I looked in to the customer model but didn't find a field called surname. Thanks!

**Comment by myriamboure** [comment]
Hi @YanhanLyu ! Welcome here ! Great that you want to tackle that issue :)
I'm not a dev but this might help you:
I'm a new customer making an order in a shop, I fill in the fields in checkout
![capture du 2019-01-17 12-30-07](https://user-images.githubusercontent.com/8135376/51316110-0b429a00-1a54-11e9-9eac-a712d30165d0.png)
When order is made, as a hub manager I see the new customer in the list, but as you see first name and family name are "aggregated"
![capture du 2019-01-17 12-31-46](https://user-images.githubusercontent.com/8135376/51316148-1b5a7980-1a54-11e9-8d44-3e1f2ea1165b.png)
In reports, in some reports like the one shared by @OliverUK first name and family name are separated, but in some other they are aggregated like in the 4th order report "total OC by customer".
I don't know about the data model but devs will answer.
Wouldn't it be better to always keep first and family name separate in the back office and reports ? It would enable people to sort either by family name, or first name, the exports... I had this feedback  already from some user. I'm not saying this should be done here (would be another issue) but in the solution for this problem we can have that in mind maybe if that influence any decision.

**Comment by YanhanLyu** [comment]
@myriamboure Thanks a lot for clarification! My problem is that I do not know how to reproduce @OliverUK 's example. If the first name and last name in @OliverUK 's example come from the customer model, then I could modify the customer model only, but I'm not sure if they come from somewhere else(like the first and last name stored in billing address).  Thanks again @myriamboure !

**Comment by daniellemoorhead** [comment]
@OliverUK or @lin-d-hop or @NickWeir63  are you able to help @YanhanLyu with his questions on how to replicate the issue?

**Comment by OliverUK** [comment]
I don't really understand the question. If it's about where the report takes its data from, then I don't know. But I'd be interested to know for a start why some information of customers in the customers screen is populated and some isn't. For some, the names and addresses are filled in and for others they are not, regardless of how recently they ordered. Yet when they do order, all their details are shown in the order and emails.

**Comment by lin-d-hop** [comment]
Hi @YanhanLyu 
Your question does not seem to be about replicating the issue, but about the OFN data model. I can help on both fronts.

1) Firstly it would be great to confirm you can replicate the issue. On your local dev environment can you use the UI to complete 2 orders using surnames that are known to cause issues in this bug report. Try creating orders with surnames Misu and MUMU and check the issue remains as described.

2) Having confirmed this you'll have the data in your DB to track down the issue. You might like to check in the report code itself which details are being used for the name. The model storing the name will be found in spree_address and could be billing_address or shipping_address. It would be great to confirm this for the reports you are working on.

Crucially, you won't need to touch the models for this (as you suggested above). Instead you need to adjust the sorting algorithm. I don't know whether it would be best to capitalise all surnames or sort ignoring case... probably the latter.

@OliverUK In your description of this issue you don't say which reports this affects. This means that we can't create acceptance criteria for this issue. Please would you specify the reports for which this is an issue such that @YanhanLyu and testers can confirm they are fixed.

**Comment by OliverUK** [comment]
Certainly @lin-d-hop  @YanhanLyu the report is Pack by Customer

**Comment by daniellemoorhead** [comment]
Hey @YanhanLyu 👋 

It's been almost a month since any activity on this issue, so I'm going to move it back into the `Bug backlog` column. Feel free to move it back to `In Dev` if you start working on it again.

Cheers 😄

**Comment by dnie12** [comment]
Hello, 
@richardc2117 and I were working on this ticket and were able to reproduce this issue for Packing Reports. We found a solution to this issue, but we noticed that the images above correspond for Packing Reports and have not deeply investigated other report types.
