### ISSUE TITLE
[OFN BE, fr_BE.yml] Error 500 on shops visible only to registered customers

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11560]
## Description

On OFN BE only - if:
- the shop has the `Visible to registered customers only option` enabled
- the customer has the selected locale `fr_BE`
- the customer visits the shopfrom without being logged in

then:
- the customer will see an error 500.

Bugsnag:
https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/62c4e09cc5c6d90009de96f2?filters[error.status]=open&filters[event.since]=30d&pivot_tab=event

## Expected Behavior

The message indicating that the user should log in, should appear.

## Actual Behaviour

The user will see an error 500.

## Steps to Reproduce

1. As admin: enable the preference `Visible to registered customers only option`
2. As the customer, on a guest session
3. Select the fr_BE locale
4. Visit the shopfront from that shop

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/dd5010bd-cda6-4723-bd5f-2c64c2d8d882)

## Workaround

Use a different locale

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.10
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

The key in `fr.yml`:
`require_login_link_html: "Si vous êtes déjà autorisé à accéder à la boutique, %{login} pour continuer."`

The same key in `fr_BE.yml`:
`require_login_link_html: "Si vous êtes déjà un client approuvé, %{login} ou %{signup} pour continuer."`

Removing `ou %{signup}` from the BE key should fix this issue.

**Comment by drummer83** [comment]
@filipefurtad0 Should this one be closed as well or should it go back to In Dev?
