### ISSUE TITLE
[BOM] Allow to search with Lastname Firstname order and with a comma

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11585]
Follow up on https://github.com/openfoodfoundation/openfoodnetwork/issues/10570

## Description

**- As a:** (enterprise user, super admin, user...)
**- On page:** `/admin/orders/bulk_management`
**- I want to be able to do:** some user copy/paste what they see on the page in the search. Yet the search returns no result if there is a comma. 

Also, searching with last name first gives no result yet. We want to add those 2 cases to this search.

## Acceptance Criteria & Tests

1. Log in as admin of a hub with some complete orders and visit `/admin/orders/bulk_management`
2. On the search field, copy paste the first name + last name of a customer as it appears on BOM (with comma)
3. Click "Filter Results"
4. See it's working
5. Now switch your search and put last name first: it should work as well

**Comment by OsamaNabih** [comment]
Hey there, I'm trying to work on this, a draft of the work can be found here https://github.com/openfoodfoundation/openfoodnetwork/issues/11585
It's still a work in progress in the spec, I just wanted to get quick feedback.
Does this direction make sense to you?

**Comment by dacook** [comment]
This is available to pick up for work. The abandoned PR #11587 may serve as a helpful guide or starting point.

**Comment by bmd08a1** [comment]
Hi, I would love to help on this.
