### ISSUE TITLE
SO - Allow for bought products to be removed from an order on order page

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1158]
Testing of #1085 revealed that it is more logical to remove items from the order page.
- [ ] Design order page to be editable (4h)
- [ ] Add delete delete buttons for items (3h)
- [ ] Review and testing (2h)

**Comment by daniellemoorhead** [comment]
@oeoeaio can you discuss this one with @sstead because it was her suggestion to do this. Can you both decide on the best way forward with this, and if it's required for version 1. Ta!

**Comment by daniellemoorhead** [comment]
Order page to be overhauled, refer to #1390 for new user flows/designs where this work may pop up again.
