### ISSUE TITLE
Change page title on checkout pages

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11599]
## Description
**- As a:** guest shopper or loggedin shopper
**- On page:** checkout process
**- I want to be able to do:** 

Checkout pages have the same title: `Checkout - Open Food Network` 

This should be change as: 

URL ending with `/checkout/details` -> should have page title `Checkout Details - Open Food Network`
URL ending with `/checkout/payment` -> should have page title `Checkout Payment - Open Food Network`
URL ending with `/checkout/summary` -> should have page title `Checkout Summary - Open Food Network`

## Acceptance Criteria & Tests

Test the checkout process (all 3 steps) and their titles with a guest checkout and a loggedin checkout.

## Additional context
[Here](https://github.com/openfoodfoundation/Analytics/issues/3#issuecomment-1503696044) and 
[Here] https://github.com/openfoodfoundation/Analytics/issues/3#issuecomment-1505058928

**Comment by aisayo** [comment]
Hello, I would like to work on this

**Comment by sigmundpetersen** [comment]
Yes, thank you @aisayo . I'll assign you

**Comment by arunguleria** [comment]
Hello @RachL , I would like to work on this .
