### ISSUE TITLE
Email confirmation | Prevent guest checkout using registered email addresses

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1159]
**Who:** Any user who has signed up on the OFN
**Trigger:** They attempt to checkout as a guest instead of logging in.
**Goal:** To force a user to login if they try to checkout as a guest with an email that is already a registered (confirmed, or not). This can prevent identity theft, duplicate orders and typos.

Note: This issue is connected to #1587 and #1617, where users who sign up/login via the checkout process must confirm their email addresses. Also, this issue will resolve #907.

-------
**Registered user attempts guest checkout**

1. The user is at the checkout page and types in the already registered email:

![image](https://cloud.githubusercontent.com/assets/10843056/26713796/ba6734fe-47b1-11e7-8362-6812bafa16cc.png)

2. When they go to click next the login modal appears over the page, saying the email address for a registered user so they need to log in or use a different email address. The email address typed into the field is displayed in the login email input field.
![image](https://user-images.githubusercontent.com/10843056/27940505-5d214c3a-630e-11e7-8628-b10fc911d3a4.png)

a) The user successfully logs in with the original email. The modal closes and they continue with checkout. 

b) The user closes the modal. They remain on the 'Your Details' section of the checkout. If they click Next, the same login modal opens again. If they change the email to a non-registered email, they can checkout as a guest.

**Comment by daniellemoorhead** [comment]
#nicetohave

**Comment by daniellemoorhead** [comment]
We need to consider this issue in the broader context of the best approach to having all users register (and then how to deal with this retrospectively with existing users).

**Comment by Matt-Yorkley** [comment]
I have a branch for this now awaiting #1768. I've added the check to both the "Next" button in the details section and the final submit button.

Registered but unconfirmed users will also see an additional "please confirm your email" type message if they subsequently try to log in after being prompted.
