### ISSUE TITLE
Close the login modal after sign-up and display message on home page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11597]
## Description
**- As a:** new user
**- On page:** home page
**- I want to be able to do:** 

currently if you sign up on the website, a message will be display to tell you an email was sent to you for confirmation; as this message appears within the modal, password managers like lastpass, bitwarden etc dont save the password as they require the login modal to close for this.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/5f6a01e9-8b47-4b36-87e3-34a8398649c9)

The purpose here is then to display the message on the home page instead of the modal.

Error messages should be kept within the modal.

## Acceptance Criteria & Tests

1. Register on the website
2. Check the modal closes when clicking on "sign up now" and the user is redirected to the home page
3. The message explaining the confirmation email appears on a home page flash banner
4. Errors message like non matching passwords, wrong email... should be kept within the modal

**Comment by chinmaym07** [comment]
Hi @RachL 
Can I contribute to this ?

**Comment by RachL** [comment]
Hi @chinmaym07 yes of course! Welcome here :-) don't hesitate if you need help!!

**Comment by RachL** [comment]
Hello @chinmaym07 just checking in: are you still working on this?

**Comment by Thekote** [comment]
Hey @RachL can I take this one?

**Comment by RachL** [comment]
hi @Thekote yes please! don't hesitate to ping us on slack if you get stuck :)

**Comment by RachL** [comment]
Hello @Thekote I hope this message fins you well. I'm only checkin in here: are you still working on this issue?

**Comment by kellyzhangg** [comment]
Is this still valid to be worked on? Thanks!

**Comment by RachL** [comment]
Hello @kellyzhangg and welcome! Yes this is still valid. Don't hesitate to reach us if you have any question!

**Comment by kellyzhangg** [comment]
Sounds good! I'm not sure about the scope of this issue based on previous attempts adding more complexity than expected but if you want to assign this to me for now, that would be great! Thanks :)

**Comment by RachL** [comment]
Hi @kellyzhangg I see Sigmund has assigned you already, awesome :) Don't worry about previous contribution: we are indeed not looking at something more complex, a simple solution is perfect :) Many thanks in advance!

**Comment by sigmundpetersen** [comment]
Hey @kellyzhangg hope you are fine 🙂 
Are you still interested in working on this issue?
