### ISSUE TITLE
UK prod header links redirecting to AU instance 

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#11596]
## Description

Some UK users have reported that the UK main site header links redirect to the AU instance, rather than the UK about site. This means the users cannot access the UK about site. The users also see a different version of the UK main site (i.e. the header links are titled differently, see below for screenshots).

## Expected Behavior

All UK users should see the current release with header links directing to the UK about site.

## Actual Behaviour

Header link text is outdated, and links incorrectly direct to AU instance.

## Steps to Reproduce

I have been unable to reproduce this as it appears to be a caching issue.

## Animated Gif/Screenshot

Screengrab provided by user:
[Screen recording 2023-09-28 15.07.37.webm](https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/fa9077f2-18db-4d91-9812-e040912b9aa1)

Screenshot of issue showing outdated header links:
<img width="1233" alt="Screenshot 2023-09-29 at 11 22 30" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/79b2c341-1d8c-4578-b470-a9f044f02162">

Screenshot showing current, correct header links (notice different text):
<img width="1440" alt="Screenshot 2023-09-29 at 11 26 26" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/bc357697-163b-4367-ac11-8dbc66d04497">

## Workaround

Clearing browser cache resolved the issue for the affected users.

## Severity

bug-s3 - for competent computer users clearing browser cache is manageable, however for less confident users this requires support time to talk them through it. It's likely affecting more users than have contacted us 

## Your Environment

* Version used: UK prod
* Browser name and version: google chrome version 114.0.5735.119 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Google chromebook

**Comment by RachL** [comment]
@BethanOFN is this issue still happening?

**Comment by RachL** [comment]
@BethanOFN I'm going to close this issue for now as we can't replicate but please reopen if you still can or have users reporting this

**Comment by BethanOFN** [comment]
@RachL Sorry Rachel missed your previous comment!! Haven't had any users report since so fine with it being closed
