### ISSUE TITLE
[BUU, BOM] Pagination options displayed overlapping the line items table

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11608]
## Description

On the new BOM - Bulk Order Management page (following the BUU - Backoffice UI Uplift work), the pagination options are appearing in the incorrect area: these overlap the line items table.

## Expected Behavior

Pagination options in the BOM page should appear in the bottom of the page below the listed line items. See `/admin/orders` under admin_style_v3 toggle for correct design

![image](https://github.com/openfoodfoundation/wishlist/assets/6525576/454ae5fb-5221-4a8d-b2da-62178c4ccd9f)

## Actual Behaviour

Pagination options in the BOM page appear overlapping the line items table.

## Steps to Reproduce

Logged in as superadmin, enable the BUU feature:
1. Visit `admin/feature-toggle/features/admin_style_v3`
2. Select Fully Enable

As a Hub admin or Superadmin:
3. Visit the orders page - `admin/bulk_management`
4. Notice the hovering pagination options, on top of the line item table.

## Animated Gif/Screenshot

1) new design - to be fixed

![image](https://github.com/openfoodfoundation/wishlist/assets/49817236/da7232a7-13a6-47d7-9329-cee7060b68d0)

2) Correct placement of the pagination options:

![image](https://github.com/openfoodfoundation/wishlist/assets/6525576/5766a968-3c92-4bc8-8aa8-241d9d6a6fdd)

## Workaround

None needed, in principle the page works, but it's quite a distraction and compromises readibility.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.4.13
* Browser name and version: tested for Firefox 117
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by dacook** [comment]
Good idea to use the new pagination component. I'm not 100% sure if it's easy to drop in, but worth a try.
For reference, the partial for this bulk Orders page is here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/spree/admin/orders/_table.html.haml#L27-L28

The _new_ pagination component can be seen in use here: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/admin/products_v3/_content.html.haml#L14-L15

**Comment by dacook** [comment]
Estimating: I'm not actually sure how we use the _Estimate_ field for OFN, but in terms of hours I'd think it wouldn't need more than a few.

**Comment by sigmundpetersen** [comment]
Hey @Robert-Kramar 👋 Hope you are well
Do you still want to work on this issue or should we un-assign?
