### ISSUE TITLE
Show pop-in alert when clicking 'ship' button from Orders screen

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11602]
## Description
**- As a:** enterprise admin
**- On page:** `admin/orders?q[s]=completed_at+desc`
**- I want to be able to do:** 

We see fairly regular occurrences of confused customers who have been sent 'order shipped/pick-up notification' emails for old orders. This happens because the enterprises are trying to 'tidy up' their orders list: an order which has been paid for, and not marked as shipped, appears as 'READY' in the shipment column. An order marked as shipped will appear as 'SHIPPED'. Enterprises don't often realise that clicking this button sends a confirmation of shipment/pick-up email to the customer

We want to introduce a modal allowing to disable the email to be sent

for design check : https://github.com/openfoodfoundation/openfoodnetwork/wiki/Design-styleguide%3A-links-and-buttons and https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=517-2906&mode=design

and the current modal we have for cancelling orders (where you can disable the checkbox to send the email) :

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/1c168c34-131b-4673-8c31-e5cb730deff1)

Content of the modal : 

This will marked the order as Shipped
- [ ] Send email confirmation to customer

2 buttons : cancel & ok

## Acceptance Criteria & Tests

1. Go to admin/orders
2. Ship an order and check the modal is working
3. go to edit an order and use the ship button there : 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/b15ad8d3-cb2a-4d20-a874-c6df0ca8b566)

Behavior should be the same

**Comment by NickIkenma** [comment]
Is this design suitable?
The modal:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/68649866/3f271929-42df-4906-b43b-fb17dd3aa7df)

The checkbox component:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/68649866/f7caf963-749e-40ac-85f0-ae3255c9ebe6)

Link to design:
https://www.figma.com/file/QMLtSme5zWp5UOunWOEZgB/Order-Cycle?type=design&node-id=9%3A6&mode=design&t=3hezHWn5hkPdqJn0-1

**Comment by RachL** [comment]
@NickIkenma yes awesome! re a recent discussion you had with Mario, I'm curious about the position of the "ok" button: is it better here to have cancel as primary action?

**Comment by mariocarabotta** [comment]
updated designs here

https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=1222-2&mode=design&t=FNv0oULr9uhjP9Pv-0

these can be considered final for implementation
