### ISSUE TITLE
Display a warning message when changing the date range of an OC with linked orders

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11613]
## Description
**- As a:** enterprise user or super admin
**- On page:** `/admin/order_cycles`
**- I want to be able to do:** 

To create a new order cycle (OC), some users change the date range of an old one instead of duplicating it first.
This has hard consequences: producers bringing too much food on the delivery day and a big mess with orders.

When changing the date range of an OC **which has linked orders**, display a popup, for instance: "Orders are linked to this order cycle. If you wish to create a new order cycle, it is recommended to duplicate the order cycle first and then change the dates."

With two buttons as:
"Proceed anyway" -- "Cancel"

Proceed anyway => the saving process goes according to what the user has selected (saving and staying on the form, or saving and going back to the list)

Cancel should move the user back to the list (where the duplicate button is visible)

Here's the mock-up for guidance:
![image](https://github.com/openfoodfoundation/wishlist/assets/68649866/fa715024-31eb-4f9a-bf0e-2ff74ec311d4)

Here's the Figma link to the design:
https://www.figma.com/file/8iCdevuefE4hRIbGyBhWHX/Nicholas-Pushes?type=design&node-id=1%3A3&mode=design&t=seDLvGHNaCuVMQLs-1

Many thanks to @NickIkenma for the design!!

## Acceptance Criteria & Tests

1. Log in as an enterprise
2. Edit a currently active or past OC (make sure the OC has orders linked)
3. See the message
4. Create an OC (past, current or future) see that you can edit it without seeing the warning
5. Test you can cancel and be redirected to the OC list or proceed according to your saving button choice (staying on the form or be redirected to the list

Repeat as super admin.

This needs to be covered by an automated test.

**Comment by RachL** [comment]
@openfoodfoundation/core-devs is this one a `good-first-issue` ?

**Comment by dacook** [comment]
It looks like we do have a "modal" component to build from, so yes I think it is. 
For reference, the ConfirmModalComponent is used on the admin orders page [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/spree/admin/orders/index.html.haml).

**Comment by aisayo** [comment]
Hi, is this available to take?

**Comment by sigmundpetersen** [comment]
Hi @aisayo sure, thank you! 🙂 Don't hesitate to ask if you need any help!

**Comment by dacook** [comment]
Sorry I didn't point this out before, but this design has been with the colours for the new "admin_v3" style.
This has been implemented behind a "feature toggle", which you can enable on your dev environment easily using the instructions here: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Feature-toggles
IE: http://localhost:3000/admin/feature-toggle/features/admin_style_v3

It looks like we don't need to worry about the colours in this issue, it's more about adding a bold title, and positioning of the buttons. It's ok that the position of buttons on existing ConfirmModalComponents are updated too. Example:
![Screen Shot 2023-10-10 at 5 47 04 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/47ff07c3-6d48-4ff2-953c-fc0aee159f7a)

So I expect the style changes would go here:  `app/components/confirm_modal_component/confirm_modal_component.scss`. 

Sorry if you already figured all this out, I just thought I'd mention in case it helps.

**Comment by wandji20** [comment]
Hi
I would take this one.

**Comment by wandji20** [comment]
Hi
I have an open [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/12653) for this one
