### ISSUE TITLE
[BUU, Orders page] Left align all table content

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11610]
## Description

On the new orders page (BUU - Backoffice UI Uplift), the table content on the orders table is centered, which creates sort of a mismatch with column titles

## Expected Behavior

Table header should have the same text orientation as table contents - all should be left aligned

## Actual Behaviour

Table header does not have the same text orientation as table contents - it's currently oriented to the left, while the table contents have centered orientation.

## Steps to Reproduce

Logged in as superadmin, enable the BUU feature:
1. Visit `admin/feature-toggle/features/admin_style_v3`
2. Select Fully Enable

As a Hub admin or Superadmin:
3. Visit the orders page - `admin/orders`
4. Notice the mismatch on the table header vs table contents orientation

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/wishlist/assets/49817236/038ea019-6061-435d-993b-78eb5f3193e2)

## Workaround

None needed.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.4.13
* Browser name and version: tested for Firefox 117
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by lauriejefferson** [comment]
I would like to work on this issue.

**Comment by sigmundpetersen** [comment]
Yeah sure @lauriejefferson , thank you! 🙂 I'll assign you
