### ISSUE TITLE
[Reports] Customers report doesn't keep the date range selection

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11612]
## Description

This is very similar to [#10392](https://github.com/openfoodfoundation/openfoodnetwork/issues/10392).

When running a report and selecting a date range, this date range is usually kept after creating the report. This is convenient, if you want to make small changes to your settings and run the report again. However the customers report doesn't keep the date range. Instead the start and end date are empty after running the report.

Note: When refreshing or leaving the page and coming back, the date range should be cleared again.

## Expected Behavior

The date range should be kept after running the report.

## Actual Behaviour

The date range is empty after running the report and needs to be entered again.

## Steps to Reproduce

1. Open the customers report.
2. Select a date range.
3. Run the report.
4. Observe the date range.

## Animated Gif/Screenshot

This example is from the Enterprise Fees Summary report, but the principle is the same:
![Peek 2023-02-07 19-24](https://user-images.githubusercontent.com/1790176/217376324-01411781-c62a-45d8-a818-1965dff5a347.gif)

## Workaround

Enter the date again.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by yasirazgar** [comment]
@drummer83 @RachL I would like to work on this.

**Comment by drummer83** [comment]
Hi @yasirazgar,
Sure, I have assigned you! Thank you for your contribution! Don't hesitate to get in touch with us in case you encounter any problems.
Maybe it's worth looking at other reports how this is solved there.
Thanks again!

**Comment by yasirazgar** [comment]
@drummer83 Fixed it in this [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/11732)

**Comment by drummer83** [comment]
Thank you, @yasirazgar!
Your PR is now in Code Review and we will let you know if changes are required!
Thanks again! 😊
