### ISSUE TITLE
[Invoices] When a paid order with invoice gets a partial refund, generate a new invoice

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11614]
## Description

**- As a:** enterprise user
**- On page:** `/admin/orders/RXXXXX/edit` 
**- I want to be able to do:** 

 When a paid order gets partially refunded AND there was a first invoice was issued before refunding then we need to generate a new invoice

Design of the new invoice needs 2 things: **a line referring to the refund** + **previous invoice number** the credit invoice applies on/ When removing an item, ideally we are canceling a line that was previously invoice, example:

[new_withpartialrefund.pdf](https://github.com/openfoodfoundation/wishlist/files/12386419/new_withpartialrefund.pdf)

## Acceptance Criteria & Tests

1. Activate invoice toggle
2. Go to a paid order and generate an invoice
3. Remove an item through BOM or add a negative payment or add a manual negative adjustment
4. See the generate / update button is activated again in invoice tab
5. Clicking it generates the new invoice and cancel the previous one

Repeat on both invoice template.

**Comment by abdellani** [comment]
Hi @RachL 
I think this is the current behavior
Can you please double-check? 
https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/45baf405-0077-4974-837b-17cfa97f9d28

**Comment by RachL** [comment]
@abdellani ah yes indeed! We just need https://github.com/openfoodfoundation/openfoodnetwork/issues/11459

sorry too many issues :see_no_evil:
