### ISSUE TITLE
It misses several translations in the supplier profile for locale instance  not English

### ISSUE THREAD

**Issue by blancnic** [openfoodfoundation/openfoodnetwork#1162]
When you have a supplier profile in the french instance for example, you have some strings in english:

When you register as a supplier:

![ofn2](https://cloud.githubusercontent.com/assets/16450598/18633550/234c7f64-7e7d-11e6-9066-35ab8408c512.PNG)

![ofn1](https://cloud.githubusercontent.com/assets/16450598/18633480/ca4e5090-7e7c-11e6-9026-f6d351756f99.PNG)

![supplier1](https://cloud.githubusercontent.com/assets/16450598/18588686/cb2c0612-7c27-11e6-9f39-f3adf39c504f.JPG)

When you connect to your profile 
    home page => all 

![supplier2](https://cloud.githubusercontent.com/assets/16450598/18588698/e141ba8c-7c27-11e6-9e36-5fcc1400d801.JPG)

```
producer profile => 
```

![supplier3](https://cloud.githubusercontent.com/assets/16450598/18588715/ee5609b2-7c27-11e6-90d7-bd2893be68e5.JPG)

```
    When you update your informations in your supplier profile: 
        Primary details => 
```

![supplier4](https://cloud.githubusercontent.com/assets/16450598/18588730/fd1627ac-7c27-11e6-9900-cfa26de7d31b.JPG)

```
        Users=> 
```

![supplier5](https://cloud.githubusercontent.com/assets/16450598/18588740/01681180-7c28-11e6-9318-566a4cda1ce8.JPG)

```
        Address=> 
```

![supplier6](https://cloud.githubusercontent.com/assets/16450598/18588742/042a4b7c-7c28-11e6-861c-5358c9910ae1.JPG)

```
        Contact=> 
```

![supplier7](https://cloud.githubusercontent.com/assets/16450598/18588745/070d4f38-7c28-11e6-84f9-bda3a8460c77.JPG)

```
        About=> 
```

![supplier8](https://cloud.githubusercontent.com/assets/16450598/18588748/0952923a-7c28-11e6-8610-be295692cf03.JPG)

```
        Business_details=> 
```

![supplier9](https://cloud.githubusercontent.com/assets/16450598/18588750/0be16d3c-7c28-11e6-8848-aee7d7df98c6.JPG)

```
        Image=> 
```

![supplier10](https://cloud.githubusercontent.com/assets/16450598/18588751/0e90f494-7c28-11e6-9277-8a3c6eead3d5.JPG)

```
        Properties=> 
```

![supplier11](https://cloud.githubusercontent.com/assets/16450598/18588755/117a1ee2-7c28-11e6-9fda-97f0ca097675.JPG)

```
        Enterprise_fee=> 
```

![supplier12](https://cloud.githubusercontent.com/assets/16450598/18588760/16885d04-7c28-11e6-9928-94a62e50fb7f.JPG)

```
When you add and manage your products: 
    home page => 
        empty list product => 
```

![supplier15](https://cloud.githubusercontent.com/assets/16450598/18588785/3af28264-7c28-11e6-8255-9f6993ee2b82.JPG)

```
        with products=> 
```

![supplier17](https://cloud.githubusercontent.com/assets/16450598/18588796/42a28fcc-7c28-11e6-8c9d-c6039af7390f.JPG)

```
    add a new product =>
```

![supplier16_1](https://cloud.githubusercontent.com/assets/16450598/18588801/465db6f0-7c28-11e6-8422-d5e0bc30022f.JPG)
![supplier16_2](https://cloud.githubusercontent.com/assets/16450598/18588803/47a3cef0-7c28-11e6-93c7-a6c5ee607948.JPG)

```
Enterprise list => 
```

![supplier14](https://cloud.githubusercontent.com/assets/16450598/18588809/4e5922b8-7c28-11e6-9334-0441cce73740.JPG)
![supplier13](https://cloud.githubusercontent.com/assets/16450598/18588813/50a96578-7c28-11e6-8ec8-0f6581417581.JPG)

**Comment by myriamboure** [comment]
Will recheck and reopen separate issues for what's remaining.
