### ISSUE TITLE
Deploy to staging is broken

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#11644]
## Description

```
Run ssh ofn-deploy@staging.openfoodnetwork.org.au -o LogLevel=ERROR "pull-request-11634 ."
  ssh ofn-deploy@staging.openfoodnetwork.org.au -o LogLevel=ERROR "pull-request-11634 ."
  shell: /usr/bin/bash -e {0}
Deploying pull-request-116[3](https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6465296941/job/17551248040?pr=11634#step:4:3)[4](https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6465296941/job/17551248040?pr=11634#step:4:5)
Already up-to-date.
Warning: : Could not match supplied host pattern, ignoring: au-staging
ERROR! Specified hosts and/or --limit does not match any hosts
Error: Process completed with exit code 1.
```
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6465296941/job/17551248040?pr=11634

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by dacook** [comment]
I expect this is because of this change that was merged today: https://github.com/openfoodfoundation/ofn-install/pull/901

But I can't work out where the problem is yet. I've looked at https://github.com/openfoodfoundation/openfoodnetwork/blob/master/.github/workflows/stage.yml and it is based on the full domain name (eg staging.openfoodnetwork.org.au), which is configured as the label description: https://github.com/openfoodfoundation/openfoodnetwork/labels?q=pr-staged

So I don't know why it broke.. will try looking again in the morning if no-body else fixes it first.

**Comment by dacook** [comment]
I guess this script is relying on the fact that the host_id was the same as the hosts group ID. 
I'll revert the change and see if that fixes it.

**Comment by mkllnk** [comment]
Each staging server has it's deploy command hardcoded in `/home/ofn-deploy/deploy`. That file was created by ofn-install: `roles/semaphore_deployment/templates/deploy.j2`

We just needed to run another playbook: `playbooks/setup_semaphore_deployment.yml`

**Comment by dacook** [comment]
Ah ha, thanks for investigating. I think I skipped over that, assuming it was no longer used. How about we rename to something like `remote_deployment`? Just confirming if you're working on this?

**Comment by mkllnk** [comment]
Yes, I just opened a new PR.
