### ISSUE TITLE
[BUU, Products page] Pagination options displayed overlapping the products table

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11642]
## Description

Related to #11608.
On the bulk edit products page the pagination options are appearing in the incorrect area: these overlap the products table.

## Expected Behavior

Pagination options in the bulk edit products should appear in the bottom of the page below the listed products/variants. See `/admin/orders` under admin_style_v3 toggle for correct design

## Actual Behaviour

Pagination options in the bulk edit products page appear overlapping the line items table.

## Steps to Reproduce

Logged in as superadmin, enable the BUU feature:
1. Visit `admin/feature-toggle/features/admin_style_v3`
2. Select Fully Enable

As a Hub admin or Superadmin:
3. Visit the products page - `/admin/products`
4. Notice the hovering pagination options, on top of the products table.

## Animated Gif/Screenshot

1) bulk edit products page - to be fixed

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/f0d2c01f-fc0d-4224-a270-ec7a5e44378f)

2) Correct placement of the pagination options:

![image](https://github.com/openfoodfoundation/wishlist/assets/6525576/5766a968-3c92-4bc8-8aa8-241d9d6a6fdd)

## Workaround

-

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.4.15
* Browser name and version: tested for Firefox 117
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by Robert-Kramar** [comment]
can you assign me this issue ?

**Comment by sigmundpetersen** [comment]
Hi @Robert-Kramar sure, thank you! 🙂 Please don't hesitate to ask if you need any help

**Comment by filipefurtad0** [comment]
Hey @Robert-Kramar @sigmundpetersen ,

We'll have to close this issue, sorry for that (we'll need to work on the `/products_v3` page and not on `/products`, which will not be updated anymore).

@Robert-Kramar Would you be willing to work on https://github.com/openfoodfoundation/openfoodnetwork/issues/11608 instead? If so, I'll assign you to it.

Thanks!

**Comment by Robert-Kramar** [comment]
Yes sure, can you assign me https://github.com/openfoodfoundation/openfoodnetwork/issues/11608 issue :) thanks
