### ISSUE TITLE
Products_v3: URL state management broken

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#11640]
## Expected Behavior
When you apply a search term, producer filter, category filter, or pagination, the page state changes (different products are shown).
To reflect this, the URL in the addressbar should be updated. Also there should be a new item added in browser history, allowing you to go back/forward.

Items such as this should appear on the end of the URL: _page&_per_page , _search_term, _producer_id, _category_id.

## Actual Behaviour
But the feature only seems to work in dev mode. On staging and prod, the following error appears:
![Screen Shot 2023-10-10 at 3 38 00 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/3cfc8e5c-815a-4024-aff8-13494c873462)

## Steps to Reproduce
1. Go to /admin/products with admin_style_v3 toggle ON
2. Select a filter or page number
3. The right products are shown. But the URL doesn't include filter/pagination parameters.
4. Back.
5. It takes you too far back.

## Workaround
Make sure you remember what filters/pages you used. Don't click Back.

## Your Environment
 * au-staging
 * au-prod

## Possible Fix
https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1695915680526909?thread_ts=1695879707.687969&cid=C01CXQNJ1J6

**Comment by dacook** [comment]
I had to troubleshoot this on au-staging.

I don't think `OFN_URL` ever existed. It results in domain-less url which is consistent with the error message:
```
irb(main):001:0> Openfoodnetwork::Application.config.action_cable
=> {:mount_path=>"/cable", :precompile_assets=>true, :url=>"/cable", :allowed_request_origins=>[/http:\/\/\/*/, /https:\/\/\/*/]}
```

I tried changing the action_cable config to use `ENV['SITE_URL']`:

```diff
+  config.action_cable.url = "#{ENV['SITE_URL']}/cable"
+  config.action_cable.allowed_request_origins = [/http:\/\/#{ENV['SITE_URL']}\/*/, /https:\/\/#{ENV['SITE_URL']}\/*/]
```

Looks promising:
```
irb(main):001:0> Openfoodnetwork::Application.config.action_cable
=> {:mount_path=>"/cable", :precompile_assets=>true, :url=>"staging.openfoodnetwork.org.au/cable", :allowed_request_origins=>[/http:\/\/staging.openfoodnetwork.org.au\/*/, /https:\/\/staging.openfoodnetwork.org.au\/*/]}
```

But this resulted in something like:
```
WebSocket connection to 'wss://staging.openfoodnetwork.org.au/admin/products_v3/staging.openfoodnetwork.org.au/cable' failed:
```

I tried commenting out the `config.action_cable.url ` line entirely, but that takes us back to the original error:
```
DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://rails/admin/products_v3?_page=1&_per_page=15&_producer_id=1772' ...
```


So there's something not configured right still...

**Comment by dacook** [comment]
This was hard to debug on dev. I tried to boot up rails in staging mode, and got stuck here:

```
# config/environments/staging.rb:
  # config.force_ssl = true

OFN_REDIS_URL=redis://localhost:6379/3 SECRET_TOKEN=blah SITE_URL=localhost:3000 RAILS_ENV=staging rails s
```

Loading a page generates internal_server_error but I can't see what the error was.

**Comment by dacook** [comment]
The problem remains: when you choose a pagination option (and presumably a filter), the page is submitted with a GET request with params, but the params seem to get lost on the second submit.

The most notable problem is that it is not possible to get past page 1, when you have chosen a different page size (see video and description here: https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1720786387419379)
We can see that the parameter values get lost on subsequent requests: (`page` and `per_page` values get blank)
![Screenshot 2024-07-15 at 9 56 26 am](https://github.com/user-attachments/assets/a1b845d3-9c66-4b4b-b729-f8820c3a32e6)

**Comment by dacook** [comment]
The search/filter/pagination logic is shared with the orders screen, see:
`app/views/admin/shared/_stimulus_pagination.html.haml`
`search_controller.js`

**Comment by chahmedejaz** [comment]
Yes, @dacook - Both screens are using the same controllers and have the broken URL as well. 
I was thinking of building the URL with query params and updating the window location to that URL via JS. Its benefit is that the URL will be used to go back and forth as well.
For example, when the per_page items are selected, like 100. Then Stimulus action should build the URL `products_url?_page=1&_per_page=20` and then we change the window location to `products_url?_page=1&_per_page=20`

```javascript
window.location.href = 'http://localhost:3000/admin/products?page=&per_page=&%5Bq%5D%5Bs%5D=name+asc&search_term=&producer_id=3&category_id=';
```
We would be writing the logic to create the URL with the required query params.
what do you think about it? Thanks

**Comment by chahmedejaz** [comment]
> The problem remains: when you choose a pagination option (and presumably a filter), the page is submitted with a GET request with params, but the params seem to get lost on the second submit.
> 
> The most notable problem is that it is not possible to get past page 1, when you have chosen a different page size (see video and description here: https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1720786387419379) We can see that the parameter values get lost on subsequent requests: (`page` and `per_page` values get blank) ![Screenshot 2024-07-15 at 9 56 26 am](https://private-user-images.githubusercontent.com/4188088/348577618-a1b845d3-9c66-4b4b-b729-f8820c3a32e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjA2ODksIm5iZiI6MTcyMTEyMDM4OSwicGF0aCI6Ii80MTg4MDg4LzM0ODU3NzYxOC1hMWI4NDVkMy05YzY2LTRiNGItYjcyOS1mODgyMGMzYTMyZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDg1OTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBkOWY0MDY1NWI4ZWJlYmQxZDQ0NWM3MzFjZjJmNDVjZTRjOTE0NjdhMjVmM2YyZjhhYTAxOWY5YzAxZGRlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RnzSOsY_DFCTaKodsH5XXxWAqFmXNSGexR4GB-nQo78)

Yes, I also noticed that. Let me check this and get back to you, my hunch is that turbo might be doing something here

**Comment by chahmedejaz** [comment]
The PR is ready for review. Thanks.
