### ISSUE TITLE
[Vouchers] The note regarding order total less than voucher amount shouldn't be displayed for percentage vouchers

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11666]
## Description

The note 'Note: if your order total is less than your voucher you may not be able to spend the remaining value.' displayed at step 2 of checkout shouldn't be displayed for percentage vouchers because in this case it can't happen.

![image](https://github.com/openfoodfoundation/wishlist/assets/1790176/a2c0b99e-9ab4-40e2-8081-f8bdd772b4d2)

## Steps to Reproduce

1. As an enterprise manager, Set up a percentage voucher on a shop (make sure the feature toggle "vouchers" is activated"
2. As a shopper, apply that voucher to step 2 of the checkout process - notice the message is not displayed
3. Retest with a non percentage voucher and check the message is showing up

Let's add an automated test for this

## Severity

bug-s4: it's annoying, but you can use it

**Comment by drummer83** [comment]
Of course, and welcome, @prateek0411999!
Looking forward to your contribution!
And don't hesitate to ping us if you get stuck.

**Comment by prateek0411999** [comment]
Hi @drummer83, I've raised a pull request for the same (https://github.com/openfoodfoundation/openfoodnetwork/pull/11694)

Let me know if any change is required in this

**Comment by drummer83** [comment]
Thank you, @prateek0411999!
Your pull request will now be reviewed by our developers and then tested. We will let you know!
Thanks again!

**Comment by rioug** [comment]
Hey @drummer83 , as far as I can see the problem you are describing shouldn't be happening right now. I have not been able to reproduce it, could you check again ? and if you manage to reproduce it, could you provide more detailed step to reproduce ? 

I have a feeling this might have been an issue at some point, but it got resolved as part of another bug fix.

**Comment by prateek0411999** [comment]
Hi @rioug, For me this was actually happening that's why i raised the MR for the same.

**Comment by prateek0411999** [comment]
Hey @rioug, As per my observation this issue is still persisted, i was able to reproduce the same and that's why i've raised the MR.

**Comment by filipefurtad0** [comment]
Agree, this one is not clear how to reproduce... Below a percentage voucher is added, but no warning is displayed. This is before staging the associated PR:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/15309d22-fb4a-4f7f-ba57-fbbf36ef97a8)

Also the pic in the description displays a flat amount voucher. Any ideas?

**Comment by prateek0411999** [comment]
Hi @filipefurtad0, yes I was about point that the same.

**Comment by filipefurtad0** [comment]
Thanks @prateek0411999 - your spec documented it nicely :pray:
