### ISSUE TITLE
When cloning an OC, clone tags as well

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11667]
## Description
**- As a:** enterprise user
**- On page:** `/admin/order_cycles`
**- I want to be able to do:** when duplicating an order cycle with tags, I want these tags to appear on the duplicated order cycle

## Acceptance Criteria & Tests

1. Go to `/admin/order_cycles`
2. Make sure you have an order cycle (OC) with tags attached to it
3. Duplicate it
4. See the tags are present in the duplicated version as well
5. Check this works on the 2 types of OC (single producer and multi-producers)
6. Add automated tests for this

**Comment by chahmedejaz** [comment]
Hey @RachL - I'd love to work on this issue, can you please assign it to me? Thanks :)

**Comment by RachL** [comment]
hey @chahmedejaz yes of course, welcome! Don't hesitate if you need any help :)

**Comment by chahmedejaz** [comment]
Hey @RachL - 

- I spiked on this issue and it's a bug, not a feature.
- This functionality is implemented but broken.
- Please assign the label accordingly

Thanks
