### ISSUE TITLE
New shopfront user welcome email points to international discourse...

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1167]
...instead of UK forum
![screenshot 2016-09-23 09 35 19](https://cloud.githubusercontent.com/assets/10517702/18779510/3334e5e6-8171-11e6-9227-a640994f1898.png)

**Comment by lin-d-hop** [comment]
The URL reset in superadmin so this is fixed for now. I assume this issue arose on the last deployment. @MagsHall Can I assign this to you to retest after the next deployment? If this happens every deployment there will be a bug to find.

**Comment by lin-d-hop** [comment]
Closing at this was related to the fix in the last deploy.
