### ISSUE TITLE
Payment Fee adjustment after order completion 

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1168]
When you adjust the price or quantity of something on an order and the customer has paid by paypal the paypal transaction fee also changes which also makes their balance incorrect e.g. customer order is £52.33 and the transaction fee is £1.98, once their order is adjusted to £51.96 to reflect a change in price the transaction fee changes to £1.75. The Food Hub has already incurred the paypal charge but the customer has the benefit of the reduction in the transaction fee.

Potentially this issue may be relevant to all percentage based adjustments?

**Comment by daniellemoorhead** [comment]
@mkllnk and @RohanM any thoughts on this?

**Comment by mkllnk** [comment]
Yes, it's relevant for all adjustments and difficult to solve. If you click the 'update and recalculate fees' button, it will adjust all fees. That is very useful for fees related to packaging or posting. Even if the invoice will be paid later, the fees should be adjusted. But in the case of payment fees that incurred already, it's not what we want.

Maybe we need a way to mark fees as fixed? We would need to change payment methods to mark the right fee on successful payment. The update method of the order would need to ignore these.

Alternatively, a bit easier, we could offer two buttons. One the updates the fees and one that doesn't update the fees. So people can adjust the fees themselves if they wanted to.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Paypal Adjustment Fee](https://trello.com/c/zu9sNXMz/23-paypal-adjustment-fee)

**Comment by lbwright22** [comment]
Testing this 28th Oct 2019:

1) open order cycle with 10% transaction fee for Paypal payments and 2% enterprise fee for items bought.
2) as a customer buy 3 items at £1 each. Pay by Paypal: £3.36 (£3 + £0.30 payment fee + £0.06 enterprise fee)
3) edit order to reduce number of items purchased to 1. Select update and recalculate.  Customer charged £1.32 and refunded £2.04.  No refund to customer of payment fee, only refund for items and enterprise fee on the items.

I think this might be resolved @lin-d-hop ?  The enterprise will be charged by Paypal for each transaction based on the original transaction I imagine?  I certainly doubt Paypal will reduce the amount if the order is less.  Hence keeping the payment fee at it's original level will help the hub cover costs.

**Comment by lin-d-hop** [comment]
#git-cull
