### ISSUE TITLE
[Admin->Orders] Include tax on fees in the line item adjustment table

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#11680]
## Description
**- As a:** enterprise user
**- On page:** `/admin/orders/XXXX/edit`
**- I want to be able to do:**

On the Admin/orders page,  a hub manager should be able to see all the costs on an order,  and the details on this page should add up to the order total 

At present,  taxes on fees (when applicable) are not included in the line item adjustment table on the admin/orders page -  and users cannot understand why they cannot arrive at the order total from the information presented to them on this page.  This prompts a request from most new users telling us that their orders are calculating incorrectly.

## Example
This shop has a 20% enterprise fee on all products.
This fee is set to 'taxable' (but same result if it is set to 'inherit from product'
They sell a taxable product - candles ($10)
I purchase 1 candle and the costs should be:
Product - $10
Tax on product (13% x $10) = $1.30
Fee on product (20% x %10) = $2.00
Fee on product tax (13% x $2.00) = $0.26
Order total is $13.56,   Including tax of $1.56

See below that the confirmation at checkout to the customer is correct,  and the invoice is correct...
But see that the hub manager is confused because they do not arrive at the order total if they add up the product + line items on the admin/orders page.
![Checkout-Open-Food-Network](https://github.com/openfoodfoundation/wishlist/assets/13171778/bf36627e-b70a-4fa8-b6c9-2dc2670230de)
![Orders-OFN-Administration (1)](https://github.com/openfoodfoundation/wishlist/assets/13171778/5e84ec29-3211-4dd5-983b-b98bbaed2867)

## Acceptance Criteria & Tests

1. reproduce example above and check the admin order edit page is displaying the fees in the adjustment section
2. Add an automated test to cover this

**Comment by abdulazizali77** [comment]
@dacook please assign to me, id like to work on this

**Comment by RachL** [comment]
Hello @abdulazizali77 I hope this message finds you well; I'm only checking in, no pressure: are you still working on this issue?

**Comment by abdulazizali77** [comment]
@RachL sorry for delay ill put a PR next week!
