### ISSUE TITLE
Release v4.4.16 Green Coffee Beans

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11693]
## 1. Preparation on Thursday

- [x] Merge pull requests in the [Ready To Go] column
- [x] Include translations
  <details><summary>Command line instructions:</summary>
    <pre>
    <code>
    git checkout master
    git pull upstream master
    tx pull --force
    git commit -a -m "Update all locales with the latest Transifex translations"
    git push upstream master
    </code>
    </pre>
  </details>
- [x] Create a tag:
    - `script/tag_release` will auto increment patch version, otherwise
    - `git push upstream HEAD:refs/tags/vX.Y.Z`
- [x] [Draft new release]. Look at previous [releases] for inspiration.
    - Select new release tag
    - _Generate release notes_ and check to ensure all items are arranged in the right category.
- [x] Notify [#instance-managers] of user-facing :eyes:, API :warning: and experimental :construction: changes.

## 2. Testing

- [x] Move this issue to Test Ready.
- [x] Notify `@testers` in [#testing].
- [x] Test build: [Deploy to Staging] with release tag.

## 3. Finish on Tuesday

- [x] Publish and notify [#global-community] (this is automatically posted with a plugin)
- [x] Deploy the new release to all managed instances.
  <details><summary>Command line instructions</summary>
  <pre>
  cd ofn-install
  git pull
  ansible-playbook --limit all-prod --extra-vars "git_version=vX.Y.Z" playbooks/deploy.yml
  </pre>
  </details>
- [x] Notify [#instance-managers]:
  > @instance_managers The new release has been deployed.
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Ready To Go]: #zenhub
[Transifex pull request]: https://github.com/openfoodfoundation/openfoodnetwork/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+head%3Atransifex
[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A
[releases]: https://github.com/openfoodfoundation/openfoodnetwork/releases
[#instance-managers]: https://app.slack.com/client/T02G54U79/CG7NJ966B
[#testing]: https://openfoodnetwork.slack.com/app_redirect?channel=C02TZ6X00
[Deploy to Staging]: https://github.com/openfoodfoundation/openfoodnetwork/actions/workflows/stage.yml
[#global-community]: https://app.slack.com/client/T02G54U79/C59ADD8F2

**Comment by RachL** [comment]
@filipefurtad0 apart from the failed staging on FR server, this is good to go!

https://docs.google.com/document/d/1UaPTEw8CVFJLpFFKDRftciroXU66rXFSkrWAywM9Rqc/edit


Maybe we should find out why deployment has failed for staging FR though?

**Comment by filipefurtad0** [comment]
Great, thanks @RachL .

Agree, would be a good idea to check why it has happened, so we can safely deploy to production.

Indeed, from the staging [action link you've shared](https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6587711536), we can see this error message:

```

deploy_branch
The following actions uses node12 which is deprecated and will be forced to run on node16: lannonbr/repo-permission-check-action@2.0.2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

Which is a bit weird, as staging-FR has node v17.9.1 installed...

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/7d68b3d8-2e00-4743-8327-a1b425e1fb7f)

**Comment by filipefurtad0** [comment]
Ok, I've re-staged the 4.4.16 tagged build but observed no issues... I've removed the `blocked` label. Looks like we're good to ship this one @openfoodfoundation/core-devs ?

**Comment by filipefurtad0** [comment]
This is a bit weird. The successful deploy notifications arrived timely (and almost simultaneously for both staging servers), but looking at GH-Actions reveals the deployment job not really to have finished...

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/860fd807-e448-4d4c-a9f0-b510588564a0)

**Comment by dacook** [comment]
I took a look at the deployments and found:
* The notice about Node is just a warning, which I think is related to third-party action(s). We might need to upgrade these.
* Some of the deployments hung after the "clear transient data" step. The next step is "precompile assets" which often takes a few minutes. 

So I'm not sure that there's anything wrong with the release itself. Maybe this is an intermittent problem that gets worse when GH Actions is busy (like our flaky specs), but I don't know..

**Comment by dacook** [comment]
I've opened up a new issue for these warnings.  I'll go ahead and deploy the release.
