### ISSUE TITLE
UPDATE Enterprise in Group via DFC Endpoint Enterprise Groups

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#11707]
**_All Global work to be tracked in Clockify #11242 Discovery Endpoints - including testing, code review etc
Aus devs to track in #11242 Task within Macdoch Regen Discovery_**

## Description
* As a Discovery site administrator I am using Groups to organise my API calls. I am managing Enterprises in different groups to control which ones appear on a page. 
* As a Group owner, I want to be able to manage my Group members externally. 

* I use the new [READ Enterprise Groups endpoint ](https://app.zenhub.com/workspaces/dev-pipe-54b840c6a249c8781446d4b2/issues/gh/openfoodfoundation/openfoodnetwork/11508) to see and manage my Enterprise Groups externally and I want to be able to update OFN Enterprise Groups on the API 
 
I want to be able to: [~~why are my checkboxes not working?~~]
- [ ] as User with API key that includes Group Owner for the Group/s 
- [ ] provide a Group ID and Enterprise ID to add Enterprise to that Group
- [ ] provide a Group ID and Enterprise ID to remove an Enterprise from that Group
- [ ] get confirmation that this has worked 

maybe .. 
- [ ] ?? provide Group ID/s and Enterprise IDs/ to add or remove one or more enterprises to one or more Groups i.e. not just 1-to-1 - estimate please on how much harder this makes it?

## Acceptance Criteria & Tests
1.  Create or select an enterprise and a Group on OFN 
2. Ensure the Enterprise is NOT in that Group
3. Use API key of Group owner
4. Send request to add Enterprise to Group
5. Check OFN - is enterprise now in Group?
6. Send request to remove Enterprise from Group
7. Check OFN - is enterprise now removed from Group?

**Comment by kirstenalarsen** [comment]
@rioug could you estimate please

**Comment by gracejam** [comment]
Minimum scope: 


as User with API key that includes Group Owner for the Group/s

I want to be able to:

-[ ] provide a Group ID and Enterprise ID to add Enterprise to that Group

-[ ] provide a Group ID and Enterprise ID to remove an Enterprise from that Group

**Comment by mkllnk** [comment]
I'm actually not sure how to do this the proper DFC way, so I asked Maxime how this could be possible. We may need to list all group members which are still there instead of referring to the removed one.

**Comment by mkllnk** [comment]
Maxime confirmed that there's no DFC way to delete this relationship on its own. You need to update the group listing all enterprises that should be in the group (without the deleted enterprise). We could add our own custom action for this though. It's very easy and not offending any other standard to have some additional behaviour.

Technically, we can implement:

```
DELETE http://test.host/api/dfc/enterprise_groups/:group_id/affiliatedBy/:enterprise_id
```

Estimate: 1 day
