### ISSUE TITLE
Get Product image on DFC Product Connector

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#11712]
**_All Global work to be tracked in Clockify #11242 Discovery Endpoints - including testing, code review etc
Aus devs to track in #11242 Task within Macdoch Regen Discovery_**

## Description

As an external directory with API access for Producers/Enterprises that have given permission, I want to use OFN DFC Product Connector to populate my Product directory and I want to be able to use OFN imagery. 

[] As an authorised API User, I want to access a Product image on the DFC Product Connector

### Considerations
* This issue is related to #11331
* This issue may be related to / blocked by #9060 Product Refactor ie. if the product image is going to move we should perhaps do that first? @mkllnk @dacook interested in your thoughts on this? We will need it active by end Dec . .
* Should we have switch to include images? otherwise this is potentially heavy? OR will this just return a url where image can be accessed?? 

## Acceptance Criteria and Tests
1.  Use API key for Enterprise User, get Product (Variant?) ID from OFN
2.  Request Product information for an Product using Product ID
3.  Access and use image file

**Comment by kirstenalarsen** [comment]
can I have an estimate please @rioug , I think this one definitely needs to be in discussion with @mkllnk and possibly @dacook re. #9069

**Comment by kirstenalarsen** [comment]
can I have an estimate please @rioug , I think this one definitely needs to be in discussion with @mkllnk and possibly @dacook re. #9069

**Comment by dacook** [comment]
Regarding #9069, this doesn't mention on touching images, so I don't think would be related. 

From what I can see in the admin interface, it looks like we currently support a single image per product, and no additional images for variants (although I see lots of code for variant images.. I guess no longer used?). As I understand it, our goal is to make "products" the smallest unit (replacing variants), so at a high level I don't think that would change how we implement this issue.

Regarding how to access the images, I think a URL sounds like the most robust option. It means the initial response isn't delayed  by large images, and the image can be downloaded as a separate process. The discovery portal can then either simply use the original image URL on the page (super easy to implement), or download a copy of the image to store it.

**Comment by kirstenalarsen** [comment]
We don't think is realistic to get this into DFC ontology in timely way, so for this one we will just do OFN Custom Attribute (est. 0.5 day)
