### ISSUE TITLE
Enterprise User controls data sharing

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#11718]
**_All Global work to be tracked in Clockify #11242 Discovery Endpoints - including testing, code review etc
Aus devs to track in #11242 Task within Macdoch Regen Discovery_**

## Description

As an Enterprise User on OFN, I can see a new tab in my Enterprise Settings called "Connected Apps". There I can control when my data is shared with other services / platforms. I can also remove this permission.

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/3524483/383a6243-7d98-45e1-b418-cfe09b9ecd08)

### Design files
Prototype > https://www.figma.com/proto/zkyllJnljTZGc0LuhPmW9Y/Enterprises?page-id=0%3A1&type=design&node-id=16-2&viewport=167%2C-161%2C0.42&t=DAhVFGv2wsDR3u1j-1&scaling=min-zoom&starting-point-node-id=16%3A2&show-proto-sidebar=1
Asset files > https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=1073%3A2&mode=design&t=W9ltPUsP0VpDID9s-1

### Icons
Icon for menu: U-F12E puzzle piece
Toggle off: U-F057 cross circle
Toggle on: U-F058 tick circle

I do this on a new tab in my Enterprise Settings called "Connected Apps" 

Considerations:
~~* When I 'turn on' data sharing, I understand what I'm allowing (content of html block)~~
~~* Proposal that the app can be added and text customised using html block in superadmin~~
~~* The switch creates a flag (where) that can then be referenced (later in API calls?)~~
~~* NB. No actual data control here - it is just an interface for collecting user preference, and then everything is actioned manually based on this~~
~~* Beginnings of discussion about more ambitious design requirements. This is small first step (est. 1 day dev)~~

Once we are clearer on scope this may be broken into smaller issues

This will be developed behind a feature flag, in the new admin style, It might look different and out place but it's an experimental feature so we are happy with it.
Initial scope : 
- [ ] create data model to store "Connected App", (see : https://github.com/openfoodfoundation/openfoodnetwork/issues/11718#issuecomment-1807372213 ) Discovery Endpoints app will be hardcoded for now
- [ ] create screen for enterprise user to enable data sharing ( no way to disable for now ), design needed
- [ ] create webhook to trigger N8N workflow (sends enterprise id and API key), expect to get a link back to be displayed on screen above when available

Next step: 
 * add a way for enterprise user to disable data sharing:
   * make data private ?
   * delete data ? (via N8N workflow to delete data via a webhook )
* Add some instance configuration for Instance manager to enable/disable "Connected App"
* managing "Connected App"
  * First step, have some sort of configuration to add/remove "Connected App"
  * Improvement, create a super admin interface to manage "Connected App", to consider what happen when app is deleted/updated :
     * what happen to enterprise data ? 
     * notify enterprise of changes ?

## Acceptance Criteria (e.g.)
~~1. A Super admin user, go to Configuration, add a Connnected App - name, html block, link to T&Cs, checkbox to accept T&Cs. Save~~
~~2. As an Enterprise User, go to Settings, see tab Connected Apps, option for the App just created by super-admin~~
~~3. Hit the switch to turn that connection on~~
~~4. NB. As Enterprise User this actually does nothing that I can check!~~
~~5. Turn it on again~~
~~6. ?? Super-admin can edit? Delete? What are data implications of this? If I edit the text about what they are permitting after they have hit the switch?~~

Enterprise User

 1. As an Enterprise User, go to Settings, see tab Connected Apps, 
 2. See option for the Regenrative Producer Portal with blurb describing what the user is agreeing to
 3. Hit the button to enable data sharing, see some sort of loading indication  (ie: spinner)
 4. After a while, see a link to MiniExtension

Super Admin User
 1. As an Admin use go to Enterprise
 2. Choose an Enterprise, see tab Connected Apps
 3. See option for the Regenrative Producer Portal with blurb describing what the user is agreeing to
 3. Hit the button to enable data sharing, see some sort of loading indication  (ie: spinner)
 4. After a while, see a link to MiniExtension

**Comment by kirstenalarsen** [comment]
## Description

As an Enterprise User on OFN, I can control when my data is shared with other services / platforms. I can also remove this permission

I do this on a new tab in my Enterprise Settings called "Connected Apps" (see [design](https://www.figma.com/proto/xrhXNAuoP2Px0VceIqQcxy/Prototypes?page-id=459%3A2&type=design&node-id=459-3&viewport=500%2C407%2C0.78&t=EtXPurGPIPFGlUHE-1&scaling=min-zoom&starting-point-node-id=459%3A3))

**Comment by kirstenalarsen** [comment]
@mkllnk @mariocarabotta to brainstorm current required implementation, with a view to scope limiting if needed to keep small / manageable. @rioug likely to do

**Comment by mkllnk** [comment]
@kirstenalarsen I had a chat with Mario about the requirements yesterday and I think that this is a bit more work.

1. When the user activates the app, we need to trigger a workflow that copies enterprise data from OFN to Airtable. That trigger can be a simple webhook within OFN and the copying is implemented in n8n.
2. OFN will need to know the link of the form to update the Airtable data and add some fields. There are several options to implement this:
  * The n8n workflow returns that link to the OFN webhook. This means that we'll have a special webhook for connected apps.
  * Or we need an API endpoint to write the URL to the enterprise settings.
  * Or we use a generic link to an n8n workflow which looks up the link in Airtable and then redirects there. I don't actually know if Airtable can redirect the user.

One complication in this flow is that there's a delay between creating the Airtable row and the miniextensions link being available. So we need a background job or n8n workflow polling that row from time to time to retrieve the link and then copying it to OFN somehow. The delay is a few seconds.

@rioug It would be great to get your opinion on this.

**Comment by kirstenalarsen** [comment]
I would like to hear @rioug opinion too - the best option is not clear to me. On the face of it I like the idea of having a webhook for connected apps, perhaps that is something that will be useful also to future connected apps as well

I think the delay is ok as long as there is a nice little notice / spinner or something that explains

**Comment by rioug** [comment]
I am not sure what the miniextension link is for ? For now I just assume that we need to record it in OFN against an enterprise.

> The n8n workflow returns that link to the OFN webhook. This means that we'll have a special webhook for connected apps.

If I understand correctly this might take a while to run as we wait for the link to become available ? I am wondering if that could create performance issue with long running queries ?

> Or we need an API endpoint to write the URL to the enterprise settings.

I am assuming N8N will use the API once the link is available ?

> Or we use a generic link to an n8n workflow which looks up the link in Airtable and then redirects there. I don't actually know if Airtable can redirect the user.

We can potentially get into a situation where someone/something tries to use the link when the miniextension link is not available yet, we would need to cover said scenario.

My preference would go to option 2, it keeps the complexity out of OFN, but it means the waiting/polling will live in N8N. I don't know anything about it, so I don't know if that's potentially an issue or not ? would it be better to have that kind of thing in a background job ?

**Comment by mkllnk** [comment]
> I am not sure what the miniextension link is for ?

It links to a form where you can edit the Airtable data. That's like the "admin UI" for enterprises to choose which products to display and which certifications they have.

> If I understand correctly this might take a while to run as we wait for the link to become available ? I am wondering if that could create performance issue with long running queries ?

Yes. Grace is working on an n8n workflow that hopefully returns the link but it could take 10 seconds, maybe? So I'm thinking that we should run it in the background and use cable_ready to let the user know when it's done.

> I am assuming N8N will use the API once the link is available ?

That's the question. A webhook is typically delivered in a background job and this one could just receive the link and store it in our database. The second option adds a whole new API endpoint which I'm not keen on. But it would keep the webhook system a bit simpler by not needing this special webhook that stores a return value.

Here's an idea: an OFN integration app consists of:

- name
- description_html also containing the terms of service
- activation_url
- activation_data only present when active
- activated_html

When you activate the app, it triggers a webhook. The return value of the webhook is JSON that's stored as `activation_data`. The HTML parts can be stored in the I18n locale to be translatable. The activation_data is passed to `activated_html` as variables to display edit link. But other apps could have multiple links, images, whatever. That's a way to keep it general for other apps. I would keep the activation_url hardcoded for now. So the code contains the list of apps to connect and translations for name and description.

**Comment by rioug** [comment]
Thanks for the clarification, looks like getting the link from N8N via webhook is the way to go. 

The data model looks like a good starting point.

**Comment by kirstenalarsen** [comment]
I am not following this adequately - would be great to see a preferred option and associated estimate once you are aligned @mkllnk @rioug , or for discussion. I am cautiously watching scope / estimate creep from initial 1 day, while understanding that this is a critical piece that we need!

**Comment by mkllnk** [comment]
Initial estimate was assuming more capabilities of MiniExtensions. I think that this part will be at least 2 days now.

**Comment by rioug** [comment]
preferred option is : 
* The n8n workflow returns that link to the OFN webhook. This means that we'll have a special webhook for connected apps.
Estimate :
* 1 day for Super Admin /Enterprise User interface  (Assuming we only allow adding connected app from Super Admin)
* 1 - 1.5 days to implement webhook  that triggers N8N workflow to copy OFN data to airtable 

I added 0.5 day mostly because I am not familiar with our webhook implementation.

**Comment by mkllnk** [comment]
David and I talked through this again and we realised that we forgot to include the disabling logic. When the integration is switched off, we need to trigger another webhook to remove the enterprise data the integration (in this case n8n removing it from Airtable). That would probably add another half day to one day.

**Comment by rioug** [comment]
@kirstenalarsen @mkllnk I updated the description, let me know if I missed anything

**Comment by kirstenalarsen** [comment]
looks good @rioug - thanks :)

**Comment by lin-d-hop** [comment]
I'm actually really excited about this feature. Feels like OFN growing up a little bit :)

**Comment by mkllnk** [comment]
Great. I just added that the webhook needs to send the enterprise id and API key as auth token to the activation endpoint. Giving the auth token is the technical permission to copy data from the API. If an app fails to stop using user data, the user can revoke the auth token (change the OFN API key) to break the connection. This should satisfy the data sovereignty part for now without any public endpoints.

**Comment by mariocarabotta** [comment]
final copy
**BEFORE ACCEPTING**
<img width="830" alt="Screenshot 2023-12-19 at 14 58 02" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/fd3e38a5-e111-4150-9d0c-d42cad60f50b">

Button label: Allow data sharing
Paragraph: Eligible producers can showcase their regenerative credentials, farming practices and more through a profile listing. Simplifying how buyers can find regenerative produce and connect with producers of interest.
Link label: Learn more about Discover Regenerative

**AFTER ACCEPTING**
<img width="776" alt="Screenshot 2023-12-19 at 15 01 37" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/0e6c6a11-93f0-40ad-b88d-9f2c8546352f">
Banner paragraph: Your Open Food Network account is connected to Discover Regenerative. Add or update information on your Discover Regenerative listing here.
Button label: Manage listing
