### ISSUE TITLE
Shopfront sections (about, producers...) not collapsing 

### ISSUE THREAD

**Issue by denisegauvin** [openfoodfoundation/openfoodnetwork#1171]
## Description
As a user when I am on any shopfront, if I click on "about" or "producers" or "contact" or "groups" tab within the shopfront, the content expant, but when I click on the small arrow to collapse it, it doesn't work.
![shop_sections](https://cloud.githubusercontent.com/assets/22385230/18822587/f03b6e5a-83f4-11e6-8019-81a7daa82d3d.png)

## Expected Behavior
When I click on the "collapse" arrow it collapses and I don't see the content anymore.

## Actual Behavior
It doesn't collapse.
On mobile, where a section contains a lot of content, the user must scroll past all of the section content to reach the products

## Steps to Reproduce
1. Go to any shopfront (for instance https://www.openfoodfrance.org/hub-demo-open-food-france/shop)
2. Click on any of the inner tabs.

## Severity
S3, this is pretty annoying when navigating a shopfront and affecting many users.

## Your Environment
PC, French production (all productions), Chrome

## Possible Fix
When in the product edit page, if I hit cancel, i should be directed to Bulk Product Edit page.

**Comment by sstead** [comment]
Update. This issue is a problem associated with the Angular Foundations gem. To fix you must rewrite the whole tab. Not a quick fix.
