### ISSUE TITLE
Products with 'mL' unit displaying as 'dL' on shopfront

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#11724]
## Description

Newly created products created with unit=mL are showing in backoffice as millilitre. On the shopfront, they are incorrectly showing as dL/decilitre. Older products previously created as mL are still showing mL correctly.

## Expected Behavior

Products on shopfront should display the unit selected in backoffice

## Actual Behaviour

New products with mL are converted to dL units

## Steps to Reproduce

1. Create a **new** product with millilitre unit size
2. Add product to open order cycle
3. See product converted to decilitre units on shopfront
4. See pre-existing products on shopfront correctly displaying mL

## Animated Gif/Screenshot

Backoffice:
![Screenshot 2023-10-26 at 16 09 25](https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/925583d5-a375-4125-9e60-4128d254a488)

Shopfront:
![Screenshot 2023-10-26 at 16 09 31](https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/4897d521-cd34-46c9-b170-539a1cab8a63)

Unit dropdown also does not even list decilitre as an option:
![Screenshot 2023-10-26 at 16 15 24](https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/91ae908c-da8a-4f20-9c96-b43e64852b21)

## Workaround

No workaround - decilitre does not appear in superadmin config to deselect:
![Screenshot 2023-10-26 at 16 00 49](https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/8ad0acf1-3a69-4383-989e-65437d3856ea)

## Severity

Raising as an S2 because decilitre is an unknown unit size to majority of people and this is customer facing

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

See message from @mkllnk in [slack](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1698099327301509?thread_ts=1698037613.112019&cid=CG7NJ966B)

**Comment by abdellani** [comment]
The bug appeared after this [commit](https://github.com/openfoodfoundation/openfoodnetwork/commit/50f7177a38ea1602d487aa11f6ce8aab02622ec3)
As it's mentioned in the possible fix, it's trying to load the biggest unit.

One workaround will be to fill the `display as` field during product creation( screenshots below).
The value that's loaded automatically (as a placeholder) on that field is showing a wrong value.

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/9f778935-d8bd-4b1a-b054-15e9da947656)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/9c42e06c-5365-4a63-86e6-62e9609278d6)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/96d8e521-6a7f-42a9-b2b9-4cd049464624)

I didn't know about the  `Available unit feature`, but It seems that `VariantAndLineItemNaming` and `WeightsAndMeasures` are not taking into account that configuration.

We need to
* update AVAILABLE UNITS list
* fix the code responsible for updating the placeholder of the `Display as` field
* update WeightsAndMeasures or VariantAndLineItemNaming to avoid units that are not selected
