### ISSUE TITLE
Enterprise User actively consents to change of ToS

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#11720]
**_All Global work to be tracked in Clockify #11242 Discovery Endpoints - including testing, code review etc
Aus devs to track in #11242 Task within Macdoch Regen Discovery_**

## Description
* As instance managers / global community that cares about user rights and data sovereignty we want to make sure that our users understand and actively consent to changes to Terms of Service. We currently email our Users when we change ToS, but this is reliant on staffing etc, and people probably don't read it 
* As an Enterprise User, I want to know if something has changed in Terms of Service and agree to it before I keep using the Platform

Proposed Solution:
* We need:
  * One new attribute in the user record: terms_of_service_accepted_at datetime. 1 hour
  * On every page load we would check: user logged in? and latest terms accepted? 1 hour
  * If not then display a banner where you need to accept the terms for the banner to disappear. 4 hours
  * @mkllnk I wonder if the banner needs a text field, updated with new ToS, that briefly summarises substance of changes. How much time would that add?
  * When you accept terms, also update the user record. 1 hour
  * Thanks @RachL - if they don't accept after some time period we need to stop them using platform? How would we do that? 

That's a day. So not papercut but small feature.

## Acceptance Criteria
1. As super-admin, go to config and upload new ToS
2. As enterprise user login to platform
3. See notification, click it, it goes away
4. Logout, login again, check it hasn't come back

**Comment by kirstenalarsen** [comment]
**_All Global work to be tracked in Clockify #11242 Discovery Endpoints - including testing, code review etc
Aus devs to track in #11242 Task within Macdoch Regen Discovery_**

## Description
* As instance managers / global community that cares about user rights and data sovereignty we want to make sure that our users understand and actively consent to changes to Terms of Service. 
* As an Enterprise User, I want to know if something has changed in Terms of Service and agree to it before I keep using the Platform

Proposed Solution:
* Currently we check ToS at checkout and store that information in the customer record. When a new visitor comes, they don't have a customer record but we don't need to show this either.  Hm, I think you are aiming for enterprise users, right? They may actually never order but store data.
* We need:
  * One new attribute in the user record: terms_of_service_accepted_at datetime. 1 hour
  * On every page load we would check: user logged in? and latest terms accepted? 1 hour
  * If not then display a banner where you need to accept the terms for the banner to disappear. 4 hours
  * When you accept terms during checkout, also update the user record. 1 hour

That's a day. So not papercut but small feature.

**Comment by kirstenalarsen** [comment]
@mkllnk could you look with fresh eyes and check the estimate on this one?

**Comment by RachL** [comment]
@kirstenalarsen I think you want to speak about enterprise TOS only here. You can remove the customer part. Enterprise agree to TOS during registration. We store the date when we update the file as super admin, but we need to email our enterprises. So I guess what you want here is an automated email? And perhaps blocking the user as long as they don't accept?

**Comment by RachL** [comment]
yeah sorry I should have written "automated notification" 👍

**Comment by mkllnk** [comment]
@kirstenalarsen 

> I wonder if the banner needs a text field, updated with new ToS, that briefly summarises substance of changes. How much time would that add?

What about adding that summary in the ToS file itself? Otherwise we could do it through Transifex very easily. Adding a text field to the ToS file record may be another 3 hours.

> if they don't accept after some time period we need to stop them using platform? How would we do that?

Most platforms say that you have to stop using the platform or otherwise you agree to the terms. They are displayed on every page. Ignoring that banner needs to be seen as de-facto accepting it.

**Comment by kirstenalarsen** [comment]
Yep good, we can put the Summary in ToS. and Yes happy with that approach. Let's get it done and improve if needed

**Comment by rioug** [comment]
Here is an example of the banner : 
![tos_banner](https://github.com/openfoodfoundation/openfoodnetwork/assets/40413322/5914843e-2837-4f51-99cc-374321174b9a)

It should be annoying enough that users should want to close it :smiley:  
@kirstenalarsen (or anyone) let me know if you want any design changes.

**Comment by mkllnk** [comment]
Shall we add a link to the new terms?

**Comment by kirstenalarsen** [comment]
yes please add lijnk to terms. I'm just going to check design with @mariocarabotta

**Comment by mariocarabotta** [comment]
we have a banner component that @dacook has already built that could serve this purpose maybe?



![Image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/732b9fee-505d-44a5-aa96-fd1a7c4d17f6)

**Comment by kirstenalarsen** [comment]
Can that just be used in non-stimulus page?

**Comment by dacook** [comment]
Yep, It's mostly just HTML and CSS. I've not created a full component for it yet, but it should be very easy to re-use. Code is here:

* https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/admin/products_v3/_table.html.haml#L7-L17
* https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/webpacker/css/admin_v3/shared/forms.scss#L260-L279

We could consider creating a component to cover both these cases, it would be a good chance to try it out.

**Comment by mkllnk** [comment]
> we have a banner component

The banner doesn't have the functionality to accept the terms and then disappear. It would always show for everyone.

**Comment by rioug** [comment]
I am not sure how I feel about mixing BUU components in existing backoffice pages, is this something we already do ? 
The banner seems quite specific to the bulk update page, but it should be easy enough to reuse the HTML/CSS if we want to go down this path.

**Comment by dacook** [comment]
We've created a whole new design for the admin backoffice, which can be enabled by the `admin_style_v3` feature toggle. We intend to release this design in the not too distant future.
So I assume that Mario's design is for when the feature toggle is enabled. We'll need to add some styles in the design because it's currently unstyled (sorry I didn't think to mention this earlier):
![Screen Shot 2023-11-16 at 11 45 32 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/60804763-8f62-4555-82c8-8d89c90fd597)

**Comment by rioug** [comment]
No worries, I'll take care of it. And I'll update the wording to match Mario's design

**Comment by rioug** [comment]
I added some styling for the `admin_style_v3`

![v3_bannerUntitled](https://github.com/openfoodfoundation/openfoodnetwork/assets/40413322/3dde2afc-cf7c-4034-9913-2a93f58e7d68)

**Comment by rioug** [comment]
@kirstenalarsen @RachL 
Two questions that came up in code review : 
* there is an instance configuration called  "Enterprises must accept Terms of Service". If it's disabled, should we be showing the banner ? I'd say no but I just want to double check.
* Currently we don't record when an Enterprise user has accepted the ToS, they click a checkbox on registration so we can assume the agreed to the ToS at the time of registration. Once we deploy this change, the banner will show for everyone unless we assume everyone has already accepted the ToS. Two way we can do this : 
  * Record they accepted the ToS at the time of deploy
  * As mentioned above, assume they accepted the ToS when registering, so record they accepted the ToS when they registered (ie when the user was created). The potential "issue" here is the ToS might have been updated since then, so they will see the banner (but maybe that's what we want) .

**Comment by mkllnk** [comment]
When we updated the term, we also sent an email to everyone. So we can assume that everyone agreed to the current terms. Therefore I would use the deploy time.

**Comment by RachL** [comment]
@mkllnk when yuou say "we also sent an email to everyone" - you mean as instance managers using a dedicated software, not the OFN platform on its own - correct? I haven't found in this issue anything about an automated email but I want to be sure.

Technically we should be fin with the time of deploy. When working on ToS we asked instance manager to keep a record of their ToS changes and dates, in case of an audit. 

re 

>  "Enterprises must accept Terms of Service". If it's disabled, should we be showing the banner ?

Indeed, no :-)

**Comment by mkllnk** [comment]
> when you say "we also sent an email to everyone" - you mean as instance managers using a dedicated software, not the OFN platform on its own - correct?

That's correct. I probably can't assume that for all instances but the Australian team has been doing that. And in this case I would put the responsibility on the instances and just use the deploy date, as you agree as well.

**Comment by mariocarabotta** [comment]
adding myself as a tester for the visual

**Comment by kirstenalarsen** [comment]
Are we blocked here or awaiting a response from me?

**Comment by dacook** [comment]
No I think it's all good, Gaetan's almost finished the dev for the new design, then we can review and test. I think we decided:


**If "Enterprises must accept Terms of Service" is checked:** 
* assume all users have accepted the latest ToS, and don't show the banner until next time it's updated.

**If not checked:**
* Never show the banner

![](https://user-images.githubusercontent.com/4188088/283301479-9d2d6116-9f87-4628-9c38-90cdc4f49c3f.png)

**Comment by kirstenalarsen** [comment]
Great thanks :)
