### ISSUE TITLE
[BUU] Retain cloned product in list once it's successfully created

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11737]
This continues the work on Scenario 3 in #11067

**Scenario 1: Cloning successful**
Given that I have started the cloning process for a product
When the process is successful
Then my catalogue reloads
**And I see the new clone under the original product**
And the new clone's name is `COPY OF [original product name]`

Note: this is reflecting current behaviour, after refreshing the page manually then the overarching sorting takes precedence again.

**Comment by dacook** [comment]
This is now included within https://github.com/openfoodfoundation/openfoodnetwork/issues/11987
