### ISSUE TITLE
[Invoices] Change the display of the shipping method name

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11760]
## Description

**- As a:** enterprise user with invoices toggle ON
**- On page:** on PDF invoices
**- I want to be able to do:** (

currently in the "item" column we display 

**Shipping** (Type: `Shipping method name`). the proposal is to display: 

`Shipping method category`: `Shipping method name`

the shipping method category is defined by the user when creating a shipping method and can be Delivery or Pick up 

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/252d6d8e-7a8d-4a0a-a2eb-4155252fea01)

## Acceptance Criteria & Tests

1. Turn on invoices toggle
2. Check the display of the shipping method on the invoice for both pickup and delivery

**Comment by abdellani** [comment]
Hi @RachL,
Thank you for the screenshot, this is helpful.
