### ISSUE TITLE
[Vouchers] [Reports] Include vouchers in report: Enterprise Fees With Tax Report By Order

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11768]
**_ALL dev, code review, product and testing etc should use the Clockify code attached to this Epic https://github.com/openfoodfoundation/openfoodnetwork/issues/11922 - Citi OFN Vouchers Upgrade_**

## Description

When vouchers are applied in orders, then reports must display the discounted values of products, enterprise fees, and their corresponding taxes. 
Until now, many reports still show the numbers without taking vouchers into account.
The numbers have to be updated foll all tax scenarios:
- no taxes apply,
- taxes are included in price,
- taxes are added on top of price.

## Expected Behavior

These are the correct values for orders with tax incl. in price (including the voucher discount):
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/5e7f957c-757b-4404-897e-6a11e76c61d5)

## Actual Behaviour

Incorrect values (10 % voucher not considered)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/db7209a6-c6a7-4e88-b300-042405507824)

## Steps to Reproduce

1. Set up an enterprise with vouchers and taxes.
2. Place three orders (without tax, with tax incl. in price and with added tax).
3. Run the report.
4. Check the numbers (compare to order details and adjustments in back office).

## Animated Gif/Screenshot

See above.

## Workaround

None.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by chahmedejaz** [comment]
Hey @drummer83 - I'm working on this one. Please assign it to me. Thanks.

**Comment by drummer83** [comment]
Thanks, @chahmedejaz!
Did you manage to reproduce the issue? I have just seen that Rachel pinged me on this, sorry...
https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1702916511237929

**Comment by chahmedejaz** [comment]
> Thanks, @chahmedejaz! Did you manage to reproduce the issue? I have just seen that Rachel pinged me on this, sorry... https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1702916511237929

No problem @drummer83. 
I tried but I wasn't able to apply tax to the products during order checkout. I'm not sure what I'm missing. :/
I'm digging into the super admin manual to see what might be wrong, in the mean time, can you help on this?
I'll share the loom to better give you the idea of what I'm doing.

**Comment by drummer83** [comment]
@chahmedejaz 
You need to:
1. As admin: Set the enterprise to pay taxes:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/50c4dc5f-8e31-4a53-b673-cc29d48d9c06)
2. As super admin set up a zone including the whole country (if not available already):
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/69583f8e-65f4-4fa8-ad77-527851ee992c)
3. As super admin: Set up a tax category:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/e36da897-9b66-4501-b4cd-505b003f3136)
4. As super admin: Set up a tax rate that uses the tax category defined before AND the whole country zone defined before:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/85b0b1c6-09e5-4939-8ddc-34dca4d9b64c)
5. As admin: Apply the tax category to the product:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/7f75f1f5-e430-4f4a-b387-cbe97d81ffbb)
6. As customer: Buy that product.

This should be it. I hope I didn't forget anything.
Let me know...

**Comment by chahmedejaz** [comment]
Oh, I was missing the first step to enable sales tax for the enterprise. Thank you so much @drummer83 👍

**Comment by chahmedejaz** [comment]
**Update:**
- This has been fixed. The PR is ready for review now. Thanks.

**Comment by drummer83** [comment]
Hi @chahmedejaz,
I have tested this on staging AU today. It's looking good, but there is one thing I don't understand.
For orders with tax incl. in price there are somehow additional 0.08 $ displayed in the report. However, it doesn't show up in the summary row.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/df640904-0c4b-4569-a2de-9b91cba44b3a)

To calculate the numbers (maybe I'm wrong):
- the enterprise fee is 10 $ incl. tax
- the voucher is a 10 % voucher
- tax: 10 $ = 9.09 $ fee + 0.91 $ tax
- voucher: 10 % = 0.91 $ fee discount + 0.09 $ tax discount
- total: 9 $ = 8.18 $ fee + 0.82 $ tax

Can you find out where those additional 8 ct. in the report are coming from? I don't think it's correct. But maybe you can convince me that it is. :wink: 

I will move this back to In Dev so you can check this is more detail.

Here are the order details:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/c7f28cfe-5b0f-4a00-b720-834f553e72cf)

Thanks!
