### ISSUE TITLE
Contact tab not opening when shopfront requires login

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1180]
Clicking the contact hyperlink should open the shop's contact details tab. I think the URL of the link should be https://staging2.openfood.com.au/producer-of-honey/shop#/contact instead of https://staging2.openfood.com.au/producer-of-honey/shop##contact

![image](https://cloud.githubusercontent.com/assets/10843056/19175198/72b15258-8c80-11e6-9a8c-01fcff501aaa.png)

**Comment by lin-d-hop** [comment]
This has just been picked up by a UK user too.

**Comment by lin-d-hop** [comment]
Looking at this as it has been raised by a new user. PR #1188

**Comment by lin-d-hop** [comment]
#1210 is updated PR for this issue.
