### ISSUE TITLE
/shops page takes ages to load

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1181]
The page loads in all information about all enterprises in the system, which makes it now incredibly slow. Need to work out how to get this page to load faster

Avenues of exploration:
- load less data, e.g. only open hubs/shops, their producers and their producers' hubs
- change the way data loads
- other?

@bingxie is going to have a go at estimating this, so could @oeoeaio and @mkllnk please put in any notes about where to look / thoughts on what to do here

**Comment by mkllnk** [comment]
Initially, that page listed all shops. Now, it displays only open shops in the beginning. I think it would be good to load only the open shops first. The buttons to display closed shops or profiles can then load the additional shops. The shop-front pages already deal with later loading of enterprises into a big list of enterprises. That should make it easier.

**Comment by daniellemoorhead** [comment]
@kirstenalarsen is this still something you'd like on the Aus current backlog?

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/optimisations-suggestions/1176
