### ISSUE TITLE
Activate voucher feature toggle by default

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11827]
## Description
**- As a:** enterprise user
**- On page:** `/admin/enterprises/release-farm/edit#/vouchers_panel`
**- I want to be able to do:** 

I should see the voucher menu 

## Acceptance Criteria & Tests

1. Log in as enterprise user
2.  See you can use vouchers

1. Log in as super admin
2. See voucher feature toggle is "fully enabled"

**Comment by chahmedejaz** [comment]
I'm working on it.
