### ISSUE TITLE
Priceless product registration

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#11862]
## Description
As an admin
On page : /admin/products/new
I can register a product without a price by registering the product via the button "create and add another"
 

https://github.com/openfoodfoundation/openfoodnetwork/assets/67476305/f23afe1c-b507-42ba-925d-452f2118eb97

## Expected Behavior

The product should not be able to be registered without a price. 
The effect of a product without a price is a shop that loads indefinitely [11512](https://github.com/openfoodfoundation/openfoodnetwork/issues/11521)

## Severity
S2

**Comment by abdellani** [comment]
@Cecilia-Hn 
This is also happening when I click on create.

https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/81605aea-1bc6-49a3-8900-b51fab0e3f5b

**Comment by abdellani** [comment]
Another issue:
variant editing page has a similar issue.

https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/0ae5f6ad-94b2-429d-9286-fbfc7a44f069
