### ISSUE TITLE
[Bulk invoice printing] Bulk invoice order printing hangs

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11871]
## Description

If at least one order among all selected orders for printing is not in state `complete` (i.e. `completed_at` attribute is empty) then bulk printing will hang, with no feedback to the user. According to Bugsnag occurred several times in UK and FR.

Bugsnag here:
https://app.bugsnag.com/open-food-france/coopcircuits/errors/65645b3283f0e700079eb15e?event_id=656769cf00cdb5d91f9f0000&i=sk&m=nw

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/b122623f-57c4-4934-b73c-bcd6c7e26ffc)

## Expected Behavior

Hum. Needs a decision... Maybe the checkbox should be deactivated for orders which are not in state `complete`? Or which have no `completed_at` date?

## Actual Behaviour

The checkbox for incomplete orders is activated and the order can be selected for bulk printing; this renders a hanging modal with no info to the user.

## Steps to Reproduce

1. Log-in as admin from a hub with incomplete orders (for example in `payment` or address `state`)
2. Un-tick the option show only complete orders. Hit the search button.
3. Tick the checkbox for several orders
4. From the dropdown, select the option `bulk print invoices`
5. See the eternal spinner

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/66ef0179-06ed-4736-a084-eba03f82b727)

## Workaround

Manually select only complete resumed or cancelled orders.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.21
* Browser name and version: Firefox 119
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by RachL** [comment]
> Hum. Needs a decision... Maybe the checkbox should be deactivated for orders which are not in state complete? Or which have no completed_at date?

yep we talked about this in papercut meeting through https://github.com/openfoodfoundation/wishlist/issues/261 but couldn't find something. Needs a bit of brainstorm, maybe with @mariocarabotta
