### ISSUE TITLE
Remove voucher feature toggle

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11870]
## Description
**- As a:** super admin
**- On page:** `/admin/feature-toggle/features`
**- I want to be able to do:** see the voucher feature toggle does not exist anymore : vouchers are part of the OFN code base :tada:

## Acceptance Criteria & Tests

1. Log in as enterprise
2. See vouchers are working (you can create / deactivate them)
3. Log in as superadmin
4. See the vouchers feature toggle is gone

**Comment by RachL** [comment]
It can sound premature given we have just fully activated it on all instance, but I guess by the time we get to this issue we would have catch any big fish - but maybe I'm over optimist :)

**Comment by mkllnk** [comment]
This seemed easy and now I'm facing totally unrelated spec failures that seem to be only a problem in our test environment. :disappointed: I'll try again in the next year.

* https://github.com/mkllnk/openfoodnetwork/actions/runs/7296450980/job/19884295930
