### ISSUE TITLE
Update success / notice / error messages with the correct status

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11884]
to be mapped first. below an example of a message that should be success and not notice.
more info https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1701325935851049

![Screenshot 2023-12-01 at 13 49 38](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/1c09dff8-86ec-4cc7-87de-9c9adc86be70)

<img width="1327" alt="Screenshot 2023-12-19 at 13 23 26" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/26f5083f-fba7-4498-aa4b-a7c9e897941f">

the above happens also when updating a customer details

**Comment by RachL** [comment]
@mariocarabotta will you have time to design something here or shall we skip this one as part of the first release?

**Comment by mariocarabotta** [comment]
skip. There's no real design involved, it's more about mapping messages that have the wrong status. The order cycle creation has been fixed already.

**Comment by mariocarabotta** [comment]
archiving this for now.
doing upfront mapping of everything now feels like a daunting task. I would suggest to just raise individual issues when we find messages that are broken or styled in a way that affects folks using the admin.
