### ISSUE TITLE
UK tab from openfoodnetwork.org/hubs/#im-ready doesn't work

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1189]
when i click on UNITED KINGDOM nothing happens
![screenshot 2016-10-20 12 41 10](https://cloud.githubusercontent.com/assets/10517702/19558481/ad3c54b2-96c2-11e6-97c7-1f4f3fcd135a.png)

**Comment by lin-d-hop** [comment]
@NickWeir63 Labels please... or we'll never find this issue again :-)

**Comment by sstead** [comment]
![image](https://cloud.githubusercontent.com/assets/10843056/19713103/ed95d44a-9b8e-11e6-8d24-59f294b91f60.png)
Fixed
