### ISSUE TITLE
Consolidate various 'toggle' javascripts (Stimulus controllers)

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#11928]
### What we should change and why (this is tech debt)
We have multiple controllers that perform a 'toggle' function, that shows and hides a certain element. I noticed this and created what I hope is a good generic interface that could cover most/all of these cases: 69f160ff955802a70c983ebf5e823bd78d877b6e

So I propose that we attempt to remove each of these controllers in favour of that one:
* https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/webpacker/controllers/toggle_button_disabled_controller.js
* https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/webpacker/controllers/toggle_controller.js
* https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/webpacker/controllers/remote_toggle_controller.js

Maybe also:
* https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/webpacker/controllers/dropdown_controller.js

_**Update**_: It would be worth considering for each case if JS is needed at all, or if native browser functionality can be used (eg `<details><summary>`)

### Impact and timeline
This should make it easier to maintain, having less code and people can become familiar with using one method, rather than creating different ones to do the same thing.

**Comment by cyrillefr** [comment]
Hello @dacook,

May I work on this issue ?

**Comment by dacook** [comment]
Yes, please! I have assigned you. I'd suggest trying one of these at a time, and evaluate if it's a good change or not.
