### ISSUE TITLE
[Vouchers] Add vouchers to OC customer total report

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11923]
**_ALL dev, code review, product and testing etc should use the Clockify code 11922_**

## Description
**- As a:** enterprise user or super admin
**- On page:** `/admin/reports/orders_and_fulfillment/order_cycle_customer_totals`
**- I want to be able to do:**

When displaying summary row, I want to see 2 new columns: vouchers amount and voucher label

## Acceptance Criteria & Tests

1. Run `/admin/reports/orders_and_fulfillment/order_cycle_customer_totals`
2. By default, columns "vouchers amount" and "voucher label" would not be displayed
3. When displayed, see they show the correct data for orders with vouchers on total line
4. If summary/total row are not displayed, but the column is selected, then the behavior should be the same as the behavor we have currently under the "comments" column: the column show up empty (not the best behavior, but it's out of scope to improve this here)

**Comment by chahmedejaz** [comment]
Hey @RachL - I'm working on this. Can you please assign it to me. Thanks.

**Comment by chahmedejaz** [comment]
Hey @RachL - I've implemented the functionality and here's how it's looking rn:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/1c5957b7-67ce-4890-8dd5-b4a6591b2dbb)

Please validate this and let me know if I'm missing something. Thanks.

**Comment by chahmedejaz** [comment]
**Update:**
- The fix is ready for review now.
