### ISSUE TITLE
Adding Unsubscribe link to the bottom of all emails

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1193]
In the UK we are intermittently finding that batch emails are being picked up by spambots and resulting in specific mails being blocked to the recipient. This relates to us using a shared IP mailserver, so Aus likely isn't experiencing this. But we should be able to prevent it all the same. Fortunately it is only affecting hub managers at the moment. And at the moment our hub managers are a core part of the project. But this problem will increase in severity the more users we have.

A number of potential fixes are possible but none are guarantees, so I'm picking all the low hanging fruit first.

Adding an unsubscribe link to the bottom of all emails can help prevent spambots from blocking the mail. I envisage this can be a reply_to with Unsubscribe in the subject line. It won't actually be functional, as this transactional mail NEEDS to be sent by the system. But it might fool spambots. In the future if we find people are attempting to unsubscribe to these mails we can explore better mail settings. This is more of a sticking plaster.

@daniellemoorhead @oeoeaio @mkllnk Are you happy for this to be added for these reasons?

**Comment by mkllnk** [comment]
Hi Lynne, this is really interesting. Which mail provider do you use? And which emails are you talking about?

It does not seem right to me to add an unsubscribe link that does not work. First, our users could be confused about this fake feature. And second, I'm just imagining all these spammers using the same technique which will render it useless. It would be interesting to try though. So if you really wanted to go for it, I would suggest a link to a static page that tells the user:

- why they got the email
- how to not get the email (stop using OFN, only way to unsubscribe)

We could also mention that the reason for this link are anti-spam bots, but I think that's risky and doesn't help. Don't spread this dangerous idea. ;-)

**Comment by lin-d-hop** [comment]
We're using SendGrid. The ones that get blocked are the CCs to hub managers, and not all of them, mostly when they are sent in a big batch.

It's not our fault were not getting these transactional emails, but similarly given it is a rather specific set of emails that are not getting through there must be things that are within our power to enable.

I'm basically plucking things out of this document in the hope that we can reduce the regularity that our emails are being picked up as spam:
https://sendgrid.com/docs/Classroom/Deliver/Delivery_Introduction/email_deliverability_101.html 

Other ways around this are:
- Switch to google smtp but be restricted to all emails being sent from a single email and lose future whitelabelling capabilities
- Run our own mailserver... but when things go wrong the world will explode.
- Pay for a dedicated IP on this mailserver... but the cost is BIG.

I'm out of other ideas so picking low hanging deliverability fruit. Mmmmm deliverability fruit :-)

**Comment by mkllnk** [comment]
That's a good document. You probably went through a lot already. Here are some of my thoughts:

- Are there any emails people don't interact with? Should we give managers the option which notifications to receive and which not to receive?
- We can do the unsubscribe link if we point it to somewhere useful.
- Do we have "Open Food Netowork" in the subject?
- Can you tell the hub managers to add the sender to the address book?
- Have you looked at http://isnotspam.com/ and http://www.mail-tester.com/ ?

**Comment by OliverUK** [comment]
@mkllnk 

- I really want all the email the system sends, both to consumers and to producers. It makes my life much easier and conversely more difficult when they don't arrive.

- Email subjects looks something like this "Open Food Network UK Order Confirmation #R634118202"

- Will it make any difference if I add the OFN email to my address book? I don't think the filtering out happens anywhere that my email client settings can reach. They are never in any spam folder and I even have the following set in the webhosting control panel.
![screen shot 2016-11-01 at 07 58 55](https://cloud.githubusercontent.com/assets/17590921/19882942/2b648bb2-a009-11e6-9bc4-57d78867885b.png)

**Comment by lin-d-hop** [comment]
SendGrid say yes, add to address book. It helps with spam algorithms. I was under the impression you did this months ago.

⁣

Sent from BlueMail

​

**Comment by OliverUK** [comment]
![screen shot 2016-11-01 at 09 04 01](https://cloud.githubusercontent.com/assets/17590921/19884564/3311d24e-a012-11e6-896c-cab21d400810.png)

Indeed but neither that nor telling my webhost to allow everything from OFN has made any difference.

**Comment by OliverUK** [comment]
Incidentally, as I'm also currently helping with keeping an eye on OFN support requests in the UK, I can tell that not even the copies to support@openfoodnetwork.org.uk all arrive in Mags gmail account. I understand this support@ address is not a mailbox itself but simply forwards to the gmail account. 

Either the notification email copies don't even make it to an email address on the same domain (!) or they get lost in the process of being forwarded to the gmail account. None of the ones I'm missing are in the gmail spam folder.

**Comment by mkllnk** [comment]
> Will it make any difference if I add the OFN email to my address book? I don't think the filtering out happens anywhere that my email client settings can reach.

That depends on the configuration of your email client. If your email client syncs the address book with your email hoster, it can help. If your email client keeps the address book offline, it can't help. If you have a webmail interface, it could help to login there and add the sender addresses to the address book.

I have not heard of any of these problems before. I thought that your use of Sendgrid would be smarter than our use of a simple Gmail account. But maybe Gmail is better when it comes to deliverability. Worth an experiment? Non-profits can apply for free Google accounts with all the apps including Gmail for your own domain.

**Comment by lin-d-hop** [comment]
My understanding is that Gmail smpt will overwrite any 'from' address with your 'from' address. I imagine this is how gmail maintain super high deliverability. This is great in the standard use case. But this actively stops us from whitelabelling OFN emails, which so many of our users/potential users want.

**Comment by lin-d-hop** [comment]
Digging into the depths of our mailserver I have found we can add an unsubscribe from there. In the longer term it might be advantageous to add this from internal to OFN as it would enable us to reference the actual enterprise sending the email. But for now I will close this while I see if it improves deliverability.
