### ISSUE TITLE
Sales_tax report adaptation for French instance

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1194]
For France, our users need this report for their accounting / VAT declarations and payments.
But we need in the report for each order to have the total tax for each VAT rate, so total tax 5,5%, total tax 10%, total tax 20%. and then the total tax aggregation those figures.
So that the hub users can transmit this document to their accountant.

**Comment by myriamboure** [comment]
Description of what we want here: https://docs.google.com/document/d/1GhFu8138IDXvs-7vhUBOdhm-2BsZyjTIqh-rC8eeog0/edit?usp=sharing

**Comment by myriamboure** [comment]
Should we change the sales-tax report for everyone that way? Or should do a separate one "sales-tax per VAT rate"? Ping @NickWeir63 or @lin-d-hop tell me what you think, @oeoeaio @sstead I think this report could replace the current one, tell me if that sounds ok or if we do a seperate one.

**Comment by NickWeir63** [comment]
Myriam's google doc proposal looks fine to me thanks.  as long as we can download it as a csv like all the other reports we can always pull out the separate rates if necessary

**Comment by sstead** [comment]
Hi @myriamboure, I'd double check before removing the 'tax on delivery' and 'tax on fees' columns. I assume they were put there for a reason (perhaps a user requested this breakdown, although I'm not sure who, UK maybe?), and at a minimum, this breakdown makes it easy to see where the tax has accumulated from and verify that it's correct. In regards to the process of first selecting your hub and then having tax options become available- this is different to the behavior of most reports. It sounds intuitive, but consistency is also good? I think for Aus users, with only 1 tax zone, this proposed change won't impact them very much (assuming tax on delivery/tax on fees columns remain), so it would be ok to change the existing report. Just my thoughts.

**Comment by NickWeir63** [comment]
good point Sally.  i cant remember why VAT on fees is currently separated out but @myriamboure would it be OK to leave it separated out and hubs that want to add them back in can do that after the csv is downloaded?

**Comment by myriamboure** [comment]
Actually the issue is that with the job we are doing on VAT internationalization, there can be dozens of different tax rates, so that's why I propose to select first the hub, and that the table display according to the VAT categories/rates used by the hub.

I understand your point on tax on delivery and tax on fees... I guess in all countries the principle of VAT declaration is to tell the state what amount has been collected for each tax category... separating VAT on some products or services will actually make the job harder as the hub manager will have to add them manually to the good tax rate. We have to choose between two logics: either tax on products / delivery  fee whatever the rate (the current choice, but not adapted if you want a breakdown by rate for your VAT delcarations) or tax by rate (which is what hub needs for their VAT declarations to the authorities).
 
So what I propose is more the contrary, have by default a report by tax rate, and give the possibility for hubs who would need some breakdown by type of sales to get it. Maybe it can actually be a button allowing to switch one view or the other?

I modified the document by adding a selection "VAT by rates" or "breakdown by products / delivery / fees" (which keep the current report), so basically we keep the current report and add a second version that a hub can select "VAT by rates"...

Would it be ok that way?

**Comment by NickWeir63** [comment]
sounds good to me thanks

**Comment by sstead** [comment]
Yes I think that is good, as long as making a second report doesn't add to much extra dev time for you. The two reports can be selectable like the Payments reports (below)
![image](https://cloud.githubusercontent.com/assets/10843056/20740741/c294dec0-b719-11e6-9662-205b4d2872e0.png)
