### ISSUE TITLE
Set up code coverage metrics

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11948]
### What we should change and why (this is tech debt)

Set up code coverage metrics.

One approach would be to set up SimpleCov. But the results from this gem are not correct. This would need:
- to consider Knapsack queue mode - https://docs.knapsackpro.com/ruby/simplecov/
- appropriate configuration so we get numbers we can rely on 

### Context

https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1702589824233819?thread_ts=1658137192.453269&cid=C02TZ6X00

### Impact and timeline

Set up testing metrics is useful to understand how the project is evolving on this front.

**Comment by johansenja** [comment]
Do you mind if I have a try at this?
