### ISSUE TITLE
When on Product, Inventory or Users pages, menu is not highlighted correctly

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11952]
There are inconsistencies in how the menu is highlighted when pages under the Products and Users sections are loaded. This makes it a bit hard, especially for product list, to get context of where you are in the software. It also makes it a bit harder to distinguish the menu itself.

The correct way (primary and secondary menu highlighted) is happening for properties and import: 
<img width="526" alt="Screenshot 2023-12-19 at 11 41 58" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/f874310c-3be6-4cdd-bfa2-adc2821d9051">

Inventory is only highlighting the secondary menu item:
<img width="475" alt="Screenshot 2023-12-19 at 11 40 50" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/3f798cd3-285a-420a-8712-2fed7f8129c0">

Similarly, Roles is only highlighting the secondary menu item and not the primary (Users)
<img width="1206" alt="Screenshot 2023-12-19 at 15 08 41" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/a7ae90a7-ea33-4566-9c8d-afe9d1d39179">

Products is not highlighting anything:
<img width="642" alt="Screenshot 2023-12-19 at 11 40 03" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/40b35c46-8abf-45a8-ab2f-b8ef873075a4">

**Comment by drummer83** [comment]
The 'Roles' page (super admin) is also affected.

**Comment by bouaik** [comment]
I'd like to look into this issue

**Comment by sigmundpetersen** [comment]
Thank you @bouaik , I've assigned you 👍
