### ISSUE TITLE
Invoice adaptation for French instance

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1195]
How can I translate and adapt the invoice format that you can print from the order?
We need to make a French version (I guess every instance will need its own version)

I also need to be able to see the different VAT rate on the invoice.
Even without changing anything in the current set up (VAT is included in prices, so included in shop front, and detail "including xxx VAT" in the confirmation) we would like in the appearance of the invoice and order confirmation to have one aggregating line **for each VAT rate** (2,1%, 5,5%, 10%, 20%). And if no VAT for this rate, the line doesn't appear (ideally).

**Comment by myriamboure** [comment]
Ping @mkllnk or @oeoeaio any idea where /how to translate and adapt the invoice?

**Comment by oeoeaio** [comment]
Hi @myriamboure,

Translation of invoices will need to be added in the same way as any other pages on the site, at the moment it looks like some elements of it are hard-coded so there will be a little bit of initial work (perhaps an hour or so) to add the translated elements. Any developer familiar with rails should be able to do this, so if you have someone there who is willing to add translations to the template, feel free to get them to change `app/views/spree/admin/orders/invoice.html.haml` and submit a pull request and we'll merge it ASAP.

With regard to displaying the different tax rates - this is a little more complicated, and I will need to investigate further before I can give you a good idea of how much work this is. Am I right in understanding that this is the same as point 3 in your comment [here](http://community.openfoodnetwork.org/t/outstanding-tax-requirements-jan-2016/487/17?u=oeoeaio)? If so, I will quote on it as part of the outstanding tax requirements work. 

Hope that helps!

**Comment by myriamboure** [comment]
Thank you @oeoeaio and you're right, this is the point 3, but an urgent point for one of our user and that can be done first, before the whole job on tax refund is done, I guess (I hope). As we have a workaround for the moment by including VAT in prices (tax rate set up as "VAT included in price), so display in shopfront, so we "just" need, in the calculation of the VAT, to isolate the aggregation around each VAT rate and display each aggregation seperately. This is the most urgent for our user and we need to find a way to manage that (and also adapt the sales_tax report accordingly), we have a small budget for that from our user, but maybe that sounds better to raise a bucket on co-budget to do the whole tax job at once... 

Thanks for the translation guidance :-)

**Comment by myriamboure** [comment]
Ok, so given the evolution of discussion on tax overhaul, where is what I propose to answer the French need:

- we aggregate the amount for each "tax category"
Example in France here are the categories:
![screenshot from 2016-11-21 12-45-46](https://cloud.githubusercontent.com/assets/8135376/20481733/f8b1d8ce-afe8-11e6-886c-94f6510209d7.png)

- For the moment all VAT rates (one VAT rate per tax category) are set up as "VAT included in price" so I guess there is a "variable" that calculates the amount of tax for each given product ordered, so we need to add all those variables corresponding to the same tax category and display the sum

- Display the aggregated amount at the end of the invoice with one line per tax category, and name is name of tax category, with one "blank line" with a translatable term to introduce the tax breakdown (in French: "dont"):

**Example:** 
Total commande 150€ [this is th line with the total amount of the order]
Dont:
TVA 20% : 2,30€
TVA 5% : 7,80€

- If amount is 0, not display (so that we don't diplay 0 for the tax category "VAT not applicable")

**Comment by myriamboure** [comment]
Modèle of invoice for France here: https://docs.google.com/document/d/1OwMq_7asHvFZ6-WRNKWdkmCl-SV6xs2hu6tucizqgCA/edit?usp=sharing
I am waiting for some feedback to make sure it's ok.
We will need to add the possibility for a hub to configurate some aspects of the invoice (like the payment conditions, or some comment field where they can put some compulsory sentence depending on their status) but I guess we can do that in a second stage.

**Comment by myriamboure** [comment]
The idea would be to have an invoice translatable/adaptable by the instance and add possibility for a hub to customize some parts of the invoice (like the payment conditions offered to the client, or some general text. Let's see if we manage to do that in the budget allowed or not ;-)

**Comment by myriamboure** [comment]
See discussion here also, we need to know that before starting coding I guess? https://community.openfoodnetwork.org/t/invoice-internationalisation/753
