### ISSUE TITLE
New customers checking out as guest - hub address saves as default delivery address

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1196]
An Improvement picked up while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/1142

There is an inconsistency with saving the hub's address as the customer's default shipping address for customers who select a 'pick up' shipping option.... We need to ask if this is what we want in the field? and how is this helpful? Appologies for the long winded explanation below:
![image](https://cloud.githubusercontent.com/assets/10843056/19293429/d188b454-906f-11e6-8f60-7b0071a0f22a.png)
- I checked out as guest with this new email, for a person who has never been on the OFN before.
- When checking out as a guest there are no 'save this as my default' checkboxes
- At checkout this person selected a 'pickup' shipping method, so no shipping address was entered
- You can see above which details were saved in the enterprises Customer list. A default billing address has been saved. And the hub's address has been saved as the default shipping address.
- When this person checked out as a guest a second time, with different details (name, shipping/billing details), none of the originally saved details were overriden.
- When this customer signed up, checked out as a logged in user and then clicked the delivery shipping method, their shipping address auto-filled with the hub's address (below).
  ![image](https://cloud.githubusercontent.com/assets/10843056/19293486/8a440548-9070-11e6-85a9-a3235d0e67ad.png)

My suggestions:
- It's not always correct to say that when a hub has a 'pickup' shipping method that the address is the hubs address. Pick up may be from multiple pickup points such as schools and markets.
- As seen above, for a new customers shopping as a guest, if they select a pick up shipping method, the hub's address is saved in their shipping address field. However, for a logged in customer, when they are checking out, they can't select 'save as my default shipping address' when they choose a pick up shipping method. So it's not clear whether we want 'pick up' shipping addresses saved as the 'shipping address' or not....
- I would suggest that when a customer select's 'pick up' as their shipping method, that no address is saved in their 'shipping address'. The whole idea of these default addresses is to save time at checkout. If you're a customer who uses a 'pick up' shipping method, it doesn't take much time to click on the pickup point you want.  I don't think we need defaults saved for this. Plus, saving the hub's address as the shipping method doesn't mean your pickup shipping method is automatically selected in checkout at this point. If this is what we want, the system could remember which pick up shipping method this customer prefers, and save this in the shipping address field... something like 'prefers pick up'. This would require a checkbox at checkout saying 'save this as my default shipping method'.
- Under this new 'save as default' feature, pre-exisitng customers on an enterprise's list have NO default shipping/billing address. If they checkout and don't click 'save as default' then these fields remain blank. ONLY when they checkout and click the 'save as default' button will something be saved to the field. GIVEN THIS, I think it's logical that a new cusotmers who checks out as a guest, should have nothing saved in their 'default shipping and billing' columns. All that should be saved is the email they used and their name (although I have concerns with this name field, as noted above).
- Bing says this behaviour occured before the 1142 work was done.

**Comment by sstead** [comment]
Note the same thing occurs if Admin creates an order for a new customer and checks them out as a guest.

**Comment by lin-d-hop** [comment]
The workflow has changed since this issue was created. No longer relevant #gitcull
