### ISSUE TITLE
Incorrect mapping of flash messages on enterprise fees page

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11975]
#### What? Why?
Part of https://github.com/openfoodfoundation/openfoodnetwork/issues/11884.
Similar to https://github.com/openfoodfoundation/openfoodnetwork/issues/11885.

Updating an enterprise fee shows a notice/error styled message instead of a confirmation:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/d67fee1e-4422-43f0-8d3d-86ce5ece45a7)

#### What should we test?
Test on the old design, or if https://github.com/openfoodfoundation/openfoodnetwork/pull/11874 has been merged, you can check the new `admin_style_v3` design.
The success messages now appear as a success, not a 'notice'. (Green in the old design, black in the new)

* Order cycle update
* Order cycle create

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

**Comment by bouaik** [comment]
Can i take this issue ?

**Comment by drummer83** [comment]
Sure, thank you so much!
