### ISSUE TITLE
If customer has different shipping and billing default addresses don't make them unclick 'same as billing' in checkout

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1197]
A nice to have improvement...picked up while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/1142

![image](https://cloud.githubusercontent.com/assets/10843056/19293694/2fbab552-9072-11e6-9d23-527cf682bc1e.png)

**Comment by myriamboure** [comment]
I propose to  pick it up while we are solving https://github.com/openfoodfoundation/openfoodnetwork/issues/928 as it's connected, I include that in the scope.

**Comment by myriamboure** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/checkout-customization-adapt-fields-required-to-the-hub-model-and-customer-type/1163

@sstead I put that in the whishlist post on customizable checkout, I propose you to move that into icebox when we move forward in our roadmap, but it seems it is not in the priorities for now.
