### ISSUE TITLE
[Staging servers] Snail (error 504, timeout) when accessing the page /admin/enterprise_roles

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11976]
## Description

The page /admin/enterprise_roles can only be accessed by super admins. 
However, there is a timeout error 504 after 120 s when loading the page - probably due to too many roles to be displayed.

## Expected Behavior

The page should load quickly.

## Actual Behaviour

There is a timeout error 504 after 120 s.

## Steps to Reproduce

1. Log in as super admin.
2. Visit /admin/enterprise_roles.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/369f9e5c-0be2-42b0-a86c-4ad81126ead4)

## Workaround

None?

## Severity
bug-s2: a non-critical feature is broken, no workaround
OR
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Use pagination like on /admin/users?

**Comment by bmd08a1** [comment]
Hi, let me work on this

**Comment by drummer83** [comment]
Thank you! 🙏🏻
Looking forward to your contribution!
