### ISSUE TITLE
[BUU] Terms of Service (ToS) can't be accepted or read when additional notification is displayed

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11971]
## Description

Follow up of #11795.

It's not possible to accept or read the ToS if the additional warning about active order cycle without payment/shipping methods is active. It seems like the latter is lying over the ToS-banner and all clicks are directed to it. After dismissing the warning, ToS can be accepted.

## Expected Behavior

- The button 'Accept Terms of Service' must always be clickable when displayed.
- The link 'read ToS' must always be clickable when displayed.

## Actual Behaviour

- The button 'Accept Terms of Service' is not clickable when displayed together with the 'active order cycle but no shipping/payment method' notification.
- The link 'read ToS' is not clickable when displayed together with the 'active order cycle but no shipping/payment method' notification.

## Steps to Reproduce

1. Set up your enterprise to show the additional warning regarding shipping/payment methods as described in this comment: https://github.com/openfoodfoundation/wishlist/issues/493#issuecomment-1864429610
2. As super admin make sure the setting for enterprises to accept ToS is active: 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/8b5a6c63-6d23-414d-8889-dabfee222fff)
3. As super admin upload a new ToS file:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/6d6f4982-6c49-4464-94a2-cc4eb69d7edc)
4. As enterprise user visit any page in the /admin area.
5. Try to accept or read the ToS - it's not possible.
6. Dismiss the other warning.
7. Try to accept or read the ToS again - it's now possible.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/0eabb4a4-0411-4aa9-b0d8-418c42185c8d)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by chahmedejaz** [comment]
Its fix has been published. It's ready for review now. Thanks.
