### ISSUE TITLE
About us box needs widening for email address

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1200]
The box splits the email address so that simon@woodchestervalleyvineyard.co.uk shows as
**mon@woodchestervalleyvineyard.co.uk** above
**si**
see below
![screenshot 2016-10-27 14 30 09](https://cloud.githubusercontent.com/assets/10517702/19769364/07769e70-9c53-11e6-9053-96b4b7c62739.png)

**Comment by pmackay** [comment]
I just tried editing this in the browser and set `word-wrap: normal` instead of `break-word`. It then doesnt break the address:

![screen shot 2016-11-21 at 19 58 35](https://cloud.githubusercontent.com/assets/115115/20498404/ff25c4cc-b024-11e6-89ef-894fb1a475eb.png)

Would be great to get @oeoeaio's view on whether that's a CSS change that could be made?

**Comment by Matt-Yorkley** [comment]
@pmackay looks pretty straight forward. A minor CSS change like that shouldn't be a problem.

**Comment by KeirOsborn** [comment]
I've just submitted a PR for this. All I did was remove the word-wrap class from enterprise.email_address and enterprise.website in app/assets/javascripts/templates/partials/contact.html.haml. Obviously the default value of word-wrap is: "normal" so it just goes back to that without us having to alter any stylesheets.

**Comment by lin-d-hop** [comment]
PR #1368

**Comment by lin-d-hop** [comment]
@OliverUK this is ready for testing now :-)

**Comment by OliverUK** [comment]
I've tested this and the email address no longer splits. I reduced the screen size until the view switches to the mobile version and I also had a look from my mobile and couldn't replicated the the issue, so it looks fixed to me. :)

**Comment by daniellemoorhead** [comment]
@mkllnk to stage on Aus and @sstead to give the OK for 1.8.9 release next week.

**Comment by sstead** [comment]
I've tested this for a ridiculously long email address 'simonbeach@woodchestervalleyvineyardery.com.au'
Below is how it displays on the full profile, viewed from the map... The screenshot shows display on mobile, and on desktop windows of various sizes. 
![image](https://cloud.githubusercontent.com/assets/10843056/24432394/a63dbee8-146d-11e7-884e-5fca456ae8b8.png)
The new behaviour is to cut off the end of the address if it's too long. I'd be surprised if an email was ever so long that it had to be cut (approx 39 characters), so I think this is fine. For the real email 'simon@woodchestervalleyvineyard.co.uk', it was only just trimmed in the smaller desktop view, and was fine on mobile...
![image](https://cloud.githubusercontent.com/assets/10843056/24432429/f3661cec-146d-11e7-8ff9-0080c9a6ed16.png)

FYI, on the producers page, and in the groups 'our producers' tab, the short profile view is still wrapping long emails. See below for examples on mobile and desktop...
![image](https://cloud.githubusercontent.com/assets/10843056/24432542/b9fb299c-146e-11e7-925e-6c0bbcb14f0c.png)
![image](https://cloud.githubusercontent.com/assets/10843056/24432548/c54b0fd8-146e-11e7-8058-97c0c6fb3ad5.png)
Perhaps this could be addressed in a new issue?
