### ISSUE TITLE
Products with zero value in weight/volume field jam the BOM page

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1202]
## Description
In "bulk order management", if I set up a weight/volume to 0, the system doesn't manage to update the price to 0 (inconsistency) and when I try save, it save "fields in red contains error" (it's in orange, not red ;-)). Also I modified another field properly (but weight to 1000g instead of 2000) and this second field was also in orange (confusing as we think there is a mistake). 

## Expected Behavior
Three options:
**1- either if I try to type 0, price modify accordingly to 0, and when I click off the field a pop-in error message appear "You can't have items with zero quantity. Please delete the item if you want to cancel this product."**
2- either if I try to type 0, price modify accordingly to 0, and I can save without problem, the order appear with a 0 value and price on the product. IMO that is "polluting information" and shouldn't happen, so I don't support that solution.
3- either if I try to type 0, price modify accordingly to 0, I can modify other fields, nothing happens when I click off BUT when I save the error message display "fields in red contain errors" and only the 0 one field is in red. IMO it is not clear enough as we don't say the reason of the error, so I think we need a pop-in, and UX would be better if done when I click off, so I can't possible save a quantity with 0.

My preference goes to 1, do you agree @sstead @enricostano ? If yes I will clean up that introduction post to make it very clear.

## Actual Behavior
See Description above.

## Steps to Reproduce
1. Go to "orders", sub menu "bulk order management". Make sure with button "column" that the columns weight/volume and price are displayed.
2. Try to reduce the quantity to 0 for one product. Change it for another one. See what happens with prices.
3.Try to save, see what happen. Fix the 0 quantity by putting some number, try to save again. That should work.

## Animated Gif/Screenshot
https://www.useloom.com/share/e7cc5956b8c04a88a18ce11c75b9582b

Previous images from Sally:
![image](https://cloud.githubusercontent.com/assets/10843056/19795112/8fc7e924-9d24-11e6-9aa6-e2d30956b078.png)

In products, I am allowed to edit an item and give it a weight/volume value of zero...
![image](https://cloud.githubusercontent.com/assets/10843056/19795150/f0ad9248-9d24-11e6-8c57-14927c05ec01.png)

## Severity
S4, as I guess not so many user want to put a product with a 0 quantity. Bug was identified by Sally but not reported by a user.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by NickWeir63** [comment]
One of our UK potential users is a food bank which distributes food that supermarkets are throwing out.  In many cases they want to give the food away and then just ask for a donation at the end as part of the check out process.  Would it be possible to allow products to be set up with a price of 0.001 so that it rounds to zero and allows products to be given away?

**Comment by sstead** [comment]
yes, possible to have a $0.00 product 
Perhaps create  new issue for 'ask for donation at checkout' 
![image](https://cloud.githubusercontent.com/assets/10843056/20415400/0c4fb072-ad8c-11e6-8d1c-55baefcb1206.png)

**Comment by Matt-Yorkley** [comment]
I'll take a look at this now. I would think that a product should be able to have no weight/volume, but I'll have a look through the spec files to see if they suggest otherwise.

**Comment by Matt-Yorkley** [comment]
I'm looking at the BOM interface now, and it allows the user to alter the weight/volume:

![screenshot from 2016-11-27 18-53-27](https://cloud.githubusercontent.com/assets/9029026/20650955/08545a2e-b4d3-11e6-855b-303091cd6f23.png)
![screenshot from 2016-11-27 18-53-31](https://cloud.githubusercontent.com/assets/9029026/20650956/08568e7a-b4d3-11e6-90a7-67424da61324.png)

I'm logged in as a superuser, not sure if that makes a difference. Changing the weight/volume changes the price of the order as well, so if a product with weight 2 is set to 1, it becomes half the price. This doesn't really make sense as the product in the example is a bottle of juice...

**Comment by Matt-Yorkley** [comment]
I'm not even sure that weight/volume column is providing any useful information, as the number is normally tied to a type (weight/volume/items), a unit scale (ie 0.001) which acts as a modifier, and a unit name that explains the unit. The value only makes sense after it's processed with the other values, and is a bit meaningless out of context.

**Comment by sstead** [comment]
Hi @Matt-Yorkley , the ability to edit the weight/volume field of products is an important functionality for people selling things like legs of lamb, or watermelons. They might sell it at an approximate weight of 3kg, but then after they've boxed up the specific order, they can update it to the actual weight of 3.2kg and recalculate the price accordingly. The issue here is more relating to why the system gets all jammed up if a product has a weight/volume of zero, and if people should be able to make 0kg products? If it's something like tickets to an event/workshop, they can list the product as an item (no problem). What other need is there for 0kg/0L products?

**Comment by lin-d-hop** [comment]
No comments since 2016. Closing
#gitcull2021
