### ISSUE TITLE
Replace stubs on ./spec/lib/stripe/account_connector_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12034]
### What we should change and why (this is tech debt)

Same as for other specs on the epic, we can replace the stubs in this file and provide real responses to the code, to test it.

Some useful documentation:
https://datatracker.ietf.org/doc/html/rfc6749#section-1.2
https://stripe.com/docs/stripe-apps/api-authentication/oauth#install-app

A sequence diagram (WIP):

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/3804c7a6-7a8f-4fc7-b215-f07370699bba)
```

title OFN / Stripe OAuth2 Flow

entryspacing 1.1


participant Client (OFN)


participant Resource Owner (User)

participant Authorization Server (Stripe OAuth)

participant Resource Server (Stripe Account)

note over Client (OFN): Initiates access request

Client (OFN)->Resource Owner (User): requests validation for access request
Resource Owner (User)-->Client (OFN): validates the application’s access request\n        (authenticates and authorizes)
Client (OFN)->Authorization Server (Stripe OAuth): authorization grant (redirect URI)
note over Authorization Server (Stripe OAuth): validates authorization
Authorization Server (Stripe OAuth)-->Client (OFN): token
Client (OFN)->Resource Server (Stripe Account): sends token
Resource Server (Stripe Account)-->Client (OFN): returns requested data
```

### Context

Part of #11890

**Comment by filipefurtad0** [comment]
Yes sure @cyrillefr ,
Thanks - I've unassigned myself and assigned you.

**Comment by filipefurtad0** [comment]
Hey @cyrillefr ,

Thanks for looking into this.

Unfortunately, I also cannot answer... I've spent quite some time looking at this one, but also could not understand where to retrieve the a (test?) token, or how to proceed.

>  there is a mock below, with a code param.

It's a good catch indeed that the mock contains a `body:` param, which I guess would point out to a system spec. Recently, we've aimed at implementing a solution to set up a proxy and intercept browser calls to external websites (like Stripe) and record these with VCR [*], but we were unable to resolve a port conflict, within the setup. So, I also don't know how we could test this, if a system spec is needed.

[*] If you are interested in knowing more about this effort, you can check [this (closed PR)](https://github.com/openfoodfoundation/openfoodnetwork/issues/8957) and this [discussion on Slack](https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1708964774372149).

**Comment by filipefurtad0** [comment]
> Unfortunately, I also cannot answer...

Maybe a good idea to ping a @openfoodfoundation/developers for their thoughts on this one.

**Comment by mkllnk** [comment]
That spec file has only one `stub_request` call in there to receive a token. If you can observe a valid real authorisation request then you can supply the params and record that one with VCR. After the recording, the token may not be valid any more and re-recording is not easily possible but we would have a valid real recording to execute the test. And a comment can explain how you observe the token to supply to the spec. That's probably the minimal implementation here.

I'm not sure in which circumstances OAuth gets called with deauthorize but one limitation of VCR is that we can't record and replay incoming requests. So if Stripe is calling a callback endoint on our side then we can't record that with VCR. It's better to use mocks there. Stripe can't call your local dev machine anyway.

**Comment by filipefurtad0** [comment]
Thanks @mkllnk @cyrillefr ,

This is helpful, I think we're almost there. I've tried following your leads together with the documentation here - https://docs.stripe.com/connect/oauth-standard-accounts.

So, I think the flow would be (and as @cyrillefr already pointed out):
1) getting an `authorization_code`
2) exchanging it for a `token` with something like:

```
response = Stripe::OAuth.token({
  grant_type: 'authorization_code',
  code: 'ac_123456789',
})
```

3) then replace the stubs on the test case `"but the user doesn't manage own or manage the corresponding enterprise"` and deauthorize the account, with something like:

```
Stripe::OAuth.deauthorize({
    client_id: 'ca_xyz...,
    stripe_user_id: 'acct_xyz...,
})
```

4) Finally, assert that we get the expected error `CanCan::AccessDenied` error with `connector.create_account `.

> If you can observe a valid real authorisation request then you can supply the params and record that one with VCR

Now, point 2) fails, of course, because `code: 'ac_123456789'` is not a valid authorization code. I'm not entirelly sure how to get it. It seems to me, we would need to record the response from the GET request:
`
GET https://connect.stripe.com/oauth/authorize
`

with params as described [here](https://docs.stripe.com/connect/oauth-reference#get-authorize-request).

I have not been able to make this request work, but I think this would be the way forward.

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 , @mkllnk ,

I think the important part is to get the (first) code (the ac_xxx).
From what I remember from my various attempts:
- one must connect to the web page of Stripe (https://connect.stripe.com/oauth/authorize) available in the ctrl
- click the test mode -> there will be a redirection and the url will then have the parameter code in it
- with the value of code, you can then go on.

Which means, you can only do this in a system spec, because you will need Capybara/Selenium.
I have tried to look what was happening after clicking the "test mode" button, but haven't found anything. It is hidden, and even if we find it, it is not meant to be public and so subject to change.
That is why I think the need for Capybara/Selenium, but I do not know if it can integrate with VCR.

**Comment by filipefurtad0** [comment]
> one must connect to the web page of Stripe (https://connect.stripe.com/oauth/authorize) available in the ctrl

Could we not record the GET request from this URL, instead of using a system spec?

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

I don't know if it possible. If you open the dev web tools, you can look at the requests, but since there is a redirection after you click the `test mode` button, you cannot see anything as the request panel is re-initialized each time a page is loaded.
I have looked a bit, and there are some Firefox add-ons that could do the job, but I am not sure if it does the job. To me, it is a bit of a hack. so I did not get any further.
It would be cool if we could get this url, but the fact it is hidden is maybe due to security reasons.
Every search I have done implied at one moment to click a button.
I am testing right now a way to see what the url is.
I will post a comment when finished.

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

there is an interesting way. 
Here, it tells you how to log the Firefox console: https://help.mypurecloud.com/articles/gather-firefox-console-log/

So, if you enter in the url https://connect.stripe.com/oauth/authorize?                                      state=the_state&scope=read_write&client_id=ca_The_client_id_test_we_use&response_type=code

You will be able to see 2 interresting calls
- a POST to connect.stripe.com/ajax ... to create a test mode
- a GET to t.stripe.com/?domain=connect.stripe.com&page=oauth...with a lots of parameters
The GET seems very complicated with a lot of ids .... I don't know if we can replicate.
There is a code parameter to be returned, I think this is the one, but there are a lot of others parameters as well.

**Comment by filipefurtad0** [comment]
Hi @cyrillefr ,

Thanks for your investigation.

Instead of using a system spec, I've tried running the HTTP request suggested here:

`https://connect.stripe.com/oauth/authorize?response_type=code&client_id=<our_client_id>&scope=read_write`

On the PR, we can see that VCR indeed captures the reply... But I don't know how we can go from there to get the actual authorization code, which is what we get when we hit "Skip this form on the UI":

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/eada1b9c-2ca4-4ab7-a583-9f062265d037)

Then, the return URL looks like something like this:
`http://localhost:3000/stripe/callback?scope=read_write&code=ac_****`

> So if Stripe is calling a callback endoint on our side then we can't record that with VCR. It's better to use mocks there. Stripe can't call your local dev machine anyway.

So maybe we can't really go further on this one...

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

I think this is hidden. But since this is about security, this is a good reason :)
I think also we cannot go further here.

**Comment by filipefurtad0** [comment]
Thanks so much again @cyrillefr :pray: 
Closing the PR and this issue.
