### ISSUE TITLE
[Stripe] Customer charged twice

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12046]
## Description

From this [thread](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1705338677323449?thread_ts=1704895279.120209&cid=CG7NJ966B).

A customer was charged twice, but OFN shows only one successful payment.

This happened on FR but Bugsnag only keeps data from the last 30 days. So not too much additional info available.

## Expected Behavior

Customers should only be charged once for they're payments.

## Actual Behaviour

A customer was charged twice, but OFN shows only one successful payment.

## Steps to Reproduce

We don't know...

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/197f0daf-ce2f-4779-bd45-9625e65d4b44)

## Workaround

No workaround

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: the payements report to Nov 9, 2023 which means the issue has been present at least since v4.4.18 Calamari (Nov 6, 2023)
* Browser name and version: -
* Operating System and version (desktop or mobile): -

**Comment by RachL** [comment]
Given we have no way to reproduce, can we really do something about it?

**Comment by filipefurtad0** [comment]
> Given we have no way to reproduce, can we really do something about it?

I don't know how to proceed on this one. Perhaps others have ideas on what could be causing it?

**Comment by RachL** [comment]
@filipefurtad0 I've checked on stripe, and we have the same info than on OFN. Looks to me the shopper tried 3 times. the third was successful and that's the one the hub refunded.

I doubt the customer was charged twice. But I've asked on slack. In the meantime I would close this and reopen when we know more. At least it's documented as you say

**Comment by filipefurtad0** [comment]
Agree - and as per delivery circle - we don't have enough info to act on it (this happened two months ago, and is only reported now); having it here makes it easier to search for, should it happen again in the future.

**Comment by RachL** [comment]
Stripe info:

# First attempt - failed 3D secure

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/dfb00605-0978-4966-805e-ff145abc2430)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/c79c2d3d-3579-484d-9c30-e1741a316138)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/71dd463e-e51a-46e8-aa36-7ba1585e8cab)

# Second attempt - failed 3D secure with a different card

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/c9cf3c7b-1810-4f59-b7f6-fa9e9e078ac4)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/235980e4-ae2d-4fdf-a461-b83c1e417f47)

# Third attempt successful then refunded by hub - same card than second attempt

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/6285af13-4737-47ed-8883-f2014e260e28)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/3b81cc90-35f8-4cd4-8ee0-1e6213520b9d)

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/456b546e-4078-4e54-a16e-18ebc67b7164)
