### ISSUE TITLE
Visual indication of stock levels in order cycle setup.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1204]
Use case: Theresa from Canada has a hub with multiple outgoing distributors and independent suppilers. The suppliers can update their stock availability and mark unavailable products with 'on hand = 0'. The coordinator populates the incoming section of the order cycle. The distributors can then login and select which items they'd like to stock it their outgoing shops. The problem for the coordinator is that they only want the outgoing distributors to see items which are available, so they need to be careful to only add items with 'on hand > 0' to incoming. Currently there's no way to see which items have zero on hand. So the coordinator needs to cross check with the producers's list. 

If out of stock items were visually indicated, this process would be easy. 
* This is a quick and easier fix- you could also fix this problem by giving each item an 'unavailable' checkbox, rather than relying on 'on hand' as a proxy.

Further use cases: I'm running an OC and want to see which items are getting low on stock, or have stocked out. Visual indicators in the OC is a quicker way to check that consulting product lists.

Potentail visual indicators:
- Greyed out (out of stock)
- Transparent orange (nearly out of stock), transparent red (out of stock)
- Corner flag
- Banner over item
* The enterprise could choose what stock level to highlight items orange at.

![image](https://cloud.githubusercontent.com/assets/10843056/20043922/f0af77d2-a4e7-11e6-9f7f-4acbe5259c3b.png)

**Comment by lin-d-hop** [comment]
This will not be not be actioned from here. OC UX redesign #gitcull
