### ISSUE TITLE
Require a product to be added to cart, before other products can be added (add ons)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1205]
Make it so that I cannot add certain items to my cart unless I have another certain product in my cart already. 

This is a request from a user selling bulk meat boxes, with the option of 'add on' items. She doesn't want customers just buying the add ons alone. 

This is low priority, a nice to have feature.

**Comment by lin-d-hop** [comment]
This is a huge feature that requires inception and prioritisation #gitcull
