### ISSUE TITLE
[Invoices] Several tax rates are showing up on the invoice for the same product

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12067]
## Description
For some products, several tax rates are displayed on the invoice while only one is applied / can be applied.

Maybe linked / same error as in https://github.com/openfoodfoundation/openfoodnetwork/issues/12066

## Expected Behavior

We need to show only the tax rate that is used for this product

## Actual Behaviour
All tax rates are showing up

## Steps to Reproduce
Not sure yet how to end up in this situation, but on UK staging with invoices toggle ON, you can reproduce on this order for example: 

https://staging.openfoodnetwork.org.uk/admin/orders/R858337342/invoices

https://staging.openfoodnetwork.org.uk/admin/orders/R858337342/print?invoice_id=53

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/a78bb13c-19b1-4f69-acd5-caa3cd52eeaa)

## Severity

bug-s3: a feature is broken but there is a workaround

**Comment by abdellani** [comment]
Hi @RachL 

I disabled the invoice flag and printed the invoice with the alternative model flag enabled.
I get the same results: 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/72975729-4cbb-4f88-9374-1f06a72567af)
Does this mean that this model also has an issue?

**Comment by RachL** [comment]
I don't think we need fixing on current invoices I think, only on the new template.

**Comment by abdellani** [comment]
@RachL 

Here are the steps to reproduce the bug:

1. create a tax category (TG)
2. create multiple tax rates that belong to TG: TR1, TR2, TR3
3. create an order in a way that only one of the tax rates should apply to the line items (for example TR1) (TR2 & TR3 should not apply)
4. notice that all the tax rates will be listed in the invoice.

**Comment by RachL** [comment]
YAY this is fixed! Good one @abdellani :muscle:

I will ask Theresa to do a final test in prod. Merging!

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/cbdaae18-7dc4-4dda-9c2b-b4cd42f40b91)
