### ISSUE TITLE
[Order details] Actions dropdown opens automatically after shipping the order

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12063]
### Action dropdown opens automatically
After marking an order as shipped via the button on the edit order page or via the actions dropdown, the actions dropdown is opened automatically even though the mouse is positioned somewhere else on the screen. 

## Expected Behavior

The actions drop down should not be opened automatically.

## Actual Behaviour

The actions dropdown opens automatically.

## Steps to Reproduce

1. Place an order and capture the payment on the /orders page.
2. Go to the order details page (/admin/orders/<order_number>/edit).
3. Use the button or the actions dropdown to mark the order as shipped.
4. See that the actions dropdown opens automatically after confirming the shipment confirmation dialog.

## Animated Gif/Screenshot

Here is an example (sorry, the mouse is invisible):

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/6bf3aee0-cdbc-4323-a86a-dde23233820b

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by cyrillefr** [comment]
Hello @drummer83 , 

May I work on this issue ?

**Comment by drummer83** [comment]
Sure!
Thank you! 🙏🏻
