### ISSUE TITLE
[Reports] Sales Tax Totals by Producer report shows all tax rates of a tax category and incorrect results

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12066]
## Description

This was observed when testing [#11543](https://github.com/openfoodfoundation/openfoodnetwork/pull/11543).

If an order is placed involving a product which has a tax category that consists of multiple tax rates, then the Sales Tax Totals by Producer report will display one line for each and every tax rate of that category - even if that tax rate has never been applied in any orders. The additional lines also have Total excl. tax and Total incl. tax values listed but they should all be zero, because no orders used these tax rates.
The report gives the impression that the summary rows are incorrect - but in fact the summary rows are correct and the lines above are incorrect.

## Expected Behavior

Only tax rates which have been applied in any orders within the filter criteria should be shown and considered. If it is not possible to hide the unused tax rates, then at least the Total excl. tax and Total incl. tax values must be zero.

## Actual Behaviour

Tax rates which have not been applied to any orders are listed in the report and they even have Total excl. tax and Total incl. tax values entered.

## Steps to Reproduce

1. As super admin set up at least two tax rates for the same tax category.
2. Apply the tax category to a product.
3. Place an order including this product.
4. Run the Sales Tax Totals by Producer report.
5. See that the report lists both tax rates and values for Total excl. tax and Total incl. tax even for the tax rate which has never been used.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/8aa52335-fd35-4d30-9dd2-5be321ca0006)

## Workaround

None.

## Severity
bug-s2 or bug-s5

## Your Environment

* Version used: staged #11543 
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by cyrillefr** [comment]
Hello @drummer83 , 

May I work on this issue ?

I have found a `Listing Tax Categories` (/admin/tax_categories) page.
Is there some doc for settings taxes ( I read a bit the user guide but cannot find taxes related information).
Or the above page is intuitive enough to sex taxes and tax categories ?

**Comment by drummer83** [comment]
Sure! Thanks for having a look at this, @cyrillefr!

Tax settings are set for the instance and that's why they are explained in the super-admin guide. Here is a link: https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ofn-platform-configuration/taxes-and-tax-zones
The only thing that regular admins (enterprise users) do, is to add tax categories to products, fees and shipping methods.

In case you are overwhelmed reading about the tax setup - don't worry. I think everyone feels like this in the beginning - at least I did. In case you get stuck somewhere or need an additional explanation, don't hesitate to reach out!

Thanks again!

**Comment by cyrillefr** [comment]
Hello @drummer83 ,

I have written , I have reproduced the test case and modified the code to compute the `Total excl. tax ($)` column only by taking into account the proper tax_rate ( and so in your example, there would a line of 0s in the second line).

But I tried to look at the spec to add a test, and so I run the line `rspec spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb:83`. Which my new code passes also.

See the capture: 
![rspec_sales_tax_2](https://github.com/openfoodfoundation/openfoodnetwork/assets/5203082/08021fe7-aacd-49ee-b4d4-db43ad2dd92b)

The spec is about one order(one line item) and 2 tax rates. But there is 100, 100 and a total of 100 in the `Total excl. tax ($)` column.
I expected to see some "real" total column. Is there an issue there ? Or may be the total is not some real total ?
Also, there is the same kind of problem in the last column.

**Comment by drummer83** [comment]
Hi @cyrillefr,

I'm not sure I understand your question.

It looks really weird, but I think it's correct. It's strange because there are two taxes applied.
Product without tax costs 100. That's true for both tax rates.
Tax 1 adds 1,50.
Tax 2 adds 2,50.
So the overall total is 104.
