### ISSUE TITLE
Create a printable receipt and enable printing for POS

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1207]
http://community.openfoodnetwork.org/t/print-a-receipt-in-a-pos-use-of-ofn/719

**Comment by myriamboure** [comment]
Proposal of modelisation of receipt: https://docs.google.com/document/d/1oE5unhTI2gG8X467Vl3iR9y4VeUJLo_tyuiB_XSa1co/edit?usp=sharing

**Comment by NickWeir63** [comment]
looks good to me

**Comment by myriamboure** [comment]
Sorry I wrote that in French, I will translate to English!

**Comment by myriamboure** [comment]
I guess we will need to add a "print receipt" button in the "action" list for an order.

**Comment by myriamboure** [comment]
@oeoeaio is what @ltrls propose ok for you? We need to push the commit quickly as the shop is opening in 3 weeks!!!

**Comment by oeoeaio** [comment]
Hey @myriam and @ltrls, sounds promising! I will try and find some time this weekend to have a more detailed look.

**Comment by oeoeaio** [comment]
Hey @ltrls. @RohanM and I have been discussing this and we think it would be best to create a separate repo for the client binaries for now. Seeing as we are not using git LFS for anything else, it seems like a lot of overhead to add to the project for just this feature. How do you feel about storing the libraries in a GitHub repo?
