### ISSUE TITLE
Enable testing OFN offline

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1209]
If you try to use the OFN locally without being connected to the internet, the Javascript fails, because it can't find some Google objects. It breaks the whole site. It also means, if Google where to go offline, the production OFN servers would break. It would be really good to cut that dependency.

**Comment by pmackay** [comment]
Can you outline here what the specific dependencies are?

**Comment by mkllnk** [comment]
`app/assets/javascripts/darkswarm/all.js.coffee` contains:
```
#= require angular-google-maps.min.js
```
That fails if the Google servers are not available.

`app/assets/javascripts/darkswarm/darkswarm.js.coffee` has `google-maps` as dependency and therefore fails if it is not loaded, e.g. if you would comment out the line above.

`app/assets/javascripts/darkswarm/services/enterprises.js.coffee` depends on `Geo` which depends on the above as well.

I'm not sure what the Angular paradigm is for this. I guess it would be great if the google-maps module would be fault tolerant. And maybe newer versions are.

**Comment by pmackay** [comment]
There are also several uses of Gmap in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/darkswarm/directives/map_osm_tiles.js.coffee. Seems a bit odd though given its for configuring OSM tiles.

**Comment by lin-d-hop** [comment]
Let's just assume devs will be working with internet... #gitcull
