### ISSUE TITLE
[Invoices] Include taxes on enterprise fees per line item on invoice

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12106]
## Description

This is a leftover from #12047.

## Expected Behavior

Taxes on enterprise fees per item should be included in the numbers shown for each item on the new invoice template.

## Actual Behaviour

Taxes on enterprise fees per item are not included in the numbers shown for each item on the new invoice template. The overall calculation and totals are correct though.

## Steps to Reproduce

1. Activate the feature toggle for 'invoices'.
2. Set up an enterprise fee with per item calculator and taxes (incl. or excl. from price).
3. Set up a product with taxes (same tax category as above).
4. Set up an order cycle with that product and add the enterprise fee to incoming or outgoing exchanges.
5. Place an order.
6. In the back office look at the order and print the invoice.
7. Check the numbers.
8. Repeat for the other tax type (incl. or excl. from price respectively).

## Animated Gif/Screenshot

Tax ecxl. from price:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/0615afe6-20d8-4631-847f-ad093b1d5fde)

Tax incl. in price:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/1391207f-893f-4e23-812d-7a79f43713bf)

## Workaround

None.

## Severity
Behind feature toggle:
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
awesome, thank so much @drummer83 !

**Comment by sigmundpetersen** [comment]
Sure, thanks @chahmedejaz ! 👍 
I'll assign you

**Comment by RachL** [comment]
Hello @chahmedejaz ! I hope this message finds you well. Are you still working on this issue? (no rush just checking in :) )

**Comment by chahmedejaz** [comment]
Hey @RachL - Really sorry this issue somehow skipped my mind😅.
Let me wrap this up as soon as possible. Thanks for the reminder. ✨

**Comment by chahmedejaz** [comment]
Hey @drummer83 - I'm trying to reproduce this however, I think it's working fine for me 😅. Can you please validate the screenshots and guide me what am I doing wrong here? Thanks.

**For excluded tax:**
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/6f408d64-d42e-4664-8537-b7c28ebc4786)
**Respective Order page:**
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/183a4dcb-4dfd-4f86-9188-c7cc5ea01454)


**For included tax:**
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/b7da4272-c652-4aed-96ee-d864427e6bc5)


**Respective Order page:**
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/13d649d1-3652-4aa4-bbbd-ba51ff06ebc6)

**Comment by drummer83** [comment]
Thanks @chahmedejaz,
At first sight this really seems solved.
Could you try the same on a staging server? Then I could investigate there as well.

**Comment by chahmedejaz** [comment]
> Could you try the same on a staging server? Then I could investigate there as well.

@drummer83 - The staging enterprise user I have, doesn't have taxes on products. Moreover, it doesn't have access to _Configuration_ tab. :(

**Comment by chahmedejaz** [comment]
@drummer83 - Here's the result. I think seems right 😅 

**Order page:**
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/49a295ea-ecfa-4a37-a42d-1f770ca804c8)

**For Invoice (Tax excluded)**
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/71e65c0c-f3be-40a3-85f0-1d7ad15e8026)

**Comment by drummer83** [comment]
Thanks @chahmedejaz,
Yes, I can confirm that this seems to be solved already. Closing.
Thanks for looking into it anyways! 🙏
