### ISSUE TITLE
A user (hub manager or buyer) should be able to delete his account from OFN

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1212]
As a user I can delete myself my account (as I can close my account on any platform). For legal reasons and archive needs passed transaction stay registered, but I shouldn't be anymore in the "users" list.

**Comment by sigmundpetersen** [comment]
Part of wishlist https://community.openfoodnetwork.org/t/users-and-admins-can-delete-accounts-entreprises-customers-order-cycles-groups/1149

Closing
