### ISSUE TITLE
[DFC Orders] DFC Import of products

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#12139]
**Funded Feature. Please track ALL ASSOCIATED WORK under the associated tracking code: #11678 DFC Orders**

## Description

Get product list from DFC producer store and let the user decide which ones to import.

* Confirm valid OIDC tokens are present or refresh. See #11947.
* Catalog URL is hardcoded in the first iteration. (ask @RaggedStaff)
* The producer catalog is fetched from the DFC URI and the list of products is displayed on the screen.
* Each product has an import button to import that product into OFN. Technically, the form can contain the whole JSON and post it do the OFN DFC API to do the work.
* Already imported products have a disabled import button.
* The import stores the `@id` attribute of the product on the other platform to record the link and remember that it was imported. See #11946.

**Comment by RaggedStaff** [comment]
The endpoint URI's for the test domain are:

**Producer App:** 
https://food-data-collaboration-produc-fe870152f634.herokuapp.com/api/products
https://food-data-collaboration-produc-fe870152f634.herokuapp.com/api/hub-users

**Comment by mkllnk** [comment]
@RaggedStaff, will the product catalog include all information in one graph or do we have to query more?

The OFN catalog_items endpoint has everything included because that's what the DFC Prototype needed. I don't have functionality to resolve resources yet and time is precious.

Also, can the first iteration just import all products and then the OFN shop decides which ones they want to display in the shop? Much easier then implementing the UX to list and import products one by one.

**Comment by RaggedStaff** [comment]
@mkllnk That's fine for 1st iteration. 

Just a small clarifying question: are we importing all the products against each hub? Is there a way to only import a Producers products once & for each hub to link to them? I'm thinking that sounds hard but curious how hard? 🤨

**Comment by mkllnk** [comment]
> are we importing all the products against each hub?

Yes, at the moment we do.

> Is there a way to only import a Producers products once & for each hub to link to them? 

Yes, that would be quite easy. We just need to check if we have the semantic id stored already.
