### ISSUE TITLE
Uploading a logo fails when registering an enterprise

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1214]
https://docs.google.com/document/d/1xnsu9_iC2YoQbWrpMGfR0R9rtZTjazMVEONAxqAYYWU/edit
https://docs.google.com/document/d/1CCjENJ-oVw8ka_SBSfQ1qC6cE0J3CyCQDH57zbf9vlA/edit

When I try to upload a logo, I see a JS error message:

`JS error: TypeError: headers is not a function`

Replicated on https://openfoodnetwork.org.au

**Comment by daniellemoorhead** [comment]
@lin-d-hop is this is something worth of the UK Current backlog?

**Comment by lin-d-hop** [comment]
@daniellemoorhead I see this has been put into v1.8.7
Happy to ask @Matt-Yorkley to take a look if that's useful?

**Comment by daniellemoorhead** [comment]
Sounds like a plan @lin-d-hop @Matt-Yorkley

**Comment by Matt-Yorkley** [comment]
I'll have a look at these issues soon. I noticed this upload issue today as well, also that not all countries in the enterprise registration form have states, and if there's no states to select in step 2, the form can't be submitted properly in step 4...

**Comment by Matt-Yorkley** [comment]
@daniellemoorhead do you know if the image preview was working before?

**Comment by Matt-Yorkley** [comment]
Did a bit of JS debugging, the issue seems to be with the **angular-file-upload-rails** gem not processing the API response headers properly. We currently use v1.1.0 which is quite old. Upgrading to v1.1.6 fixes the error message and displays the preview images properly while uploading.

**Comment by daniellemoorhead** [comment]
I don't know, sorry @Matt-Yorkley however @sstead may be able to help. Sally, was image preview working before?

**Comment by Matt-Yorkley** [comment]
No worries, it's resolved already.

**Comment by OliverUK** [comment]
Happy to test this @lin-d-hop  but can't find in buildkite.
