### ISSUE TITLE
[BUU] Improve Product Search Keywords

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12145]
### What we should change and why (this is tech debt)

We have a test for this feature in which we assert only if the data is saved on the respective fields. We should improve it by testing the search feature on the products page, making sure it finds products according to the added search keywords.

Relevant spec:
https://github.com/openfoodfoundation/openfoodnetwork/blob/78a1726bdc3bf61194a9e68c112865da2df3c5b6/spec/system/admin/products_spec.rb#L494

### Context

This came up here:
https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1707424388711889

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

May I work on this issue ?
