### ISSUE TITLE
Extra content on new payment method error page

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1215]
When creating a payment method for enterprise, I didn’t select the hub initially to which the payment method was being created.
When I click on create without selecting the Hub, the page refreshes with an error message and prompts to “Atleast one hub must be selected”, but after a few seconds, there is an extra sub page loaded below this page, with the header , openfoodnetwork logo and all the header content and showing the existing payment methods.
I have seen such behavior sometimes in the regular setup too, but yeah could replicate it here.
Not sure if its as per requirement, but the header appearing twice doesn’t sound right !! 
I tried the same with updating the payment method, and found no issue !! 

Source:
https://docs.google.com/document/d/1AL1ZchxAkBHmOO1w_gZA56lSegwXt9OYwPJlOLutMvQ/edit

![ofn-payment-methods-error-loading-below](https://cloud.githubusercontent.com/assets/154210/20413457/42e50e80-ad81-11e6-93c7-2c551a4eaa9e.png)

**Comment by daniellemoorhead** [comment]
@lin-d-hop is this is something worth of the UK Current backlog?

**Comment by myriamboure** [comment]
Just retested and this is still happening.

**Comment by RachL** [comment]
If needed, the test I did is described over there: https://github.com/openfoodfoundation/openfoodnetwork/issues/3225

**Comment by RachL** [comment]
this is now fixed 🎉
