### ISSUE TITLE
UX confusing when adding/removing enterprise managers

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1216]
I log in as an enterprise user, and I edit my enterprise and go to the "Users" tab. I enter the email address of a user I wish to add as a manager.

When I do so, the "Update" button is shown as active. But I haven't actually made a change to the form. I have to click the "+" button before the user will be added. **I expect the "Update" button to stay greyed out until I hit "+"**.

![screenshot from 2018-03-09 15-06-36](https://user-images.githubusercontent.com/8135376/37211215-822c7410-23ab-11e8-89ae-ee6d45a9f861.png)

**Comment by janfabry** [comment]
The delete part was covered in 9284dd9. I think the change required is mostly in Angular code, so "angular for newbies" might be a better label?

**Comment by Matt-Yorkley** [comment]
I have a branch for fixing this which I thought was working, but it now seems to consistently work ~50% of the time. :cry:

**Comment by Matt-Yorkley** [comment]
Fixed! Seems like a weird angular race condition where $setDirty() was being triggered at the same time by multiple sources.  

@myriamboure do you want to test this one? #2143

**Comment by myriamboure** [comment]
Is this fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/2196 @mkllnk ? @Matt-Yorkley ? If yes it seems Maikel have fixed the issue introduced by precedent PR, am I right? So we can close this one?

**Comment by myriamboure** [comment]
Nop, sorry, I understand now, 2196 only reverted the changes introduced by 2143 so you need to create a new PR @Matt-Yorkley to solve it again without the bug ;-)
