### ISSUE TITLE
[DFC Orders] Create/update order when order is placed within OFN

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#12178]
**Funded Feature. Please track ALL ASSOCIATED WORK under the associated tracking code: #11678 DFC Orders**

## Description

1. When customer places an order with a Hub that reduces On Hand for a DFC Product below 0: 
2. Check if we have a _held_ order with the Producer for the current SalesSession. 
3. If so, update quantities as required. 
4. If not, create new _held_ Order for any/all DFC products requiring replenishment.

## Acceptance Criteria

- [ ] When a customer order is placed (checkout completed) for a DFC Product that has sufficient On Hand, no DFC Order updates are processed
- [ ] When the first customer order, within an OrderCycle, is placed that reduces OnHand (for a DFC Product) below [<0], a draft Order is **created** on the Producer platform, with a FulfillementState of _held_
- [ ] When subsequent customer orders, within an OrderCycle, are placed that reduce OnHand (for any DFC Product) below [<0], the draft Order is **updated** on the Producer platform (keeping  FulfillementState = _held_)

**Comment by RaggedStaff** [comment]
@mkllnk - had a stab at updating this, let me know if it tallies with your understanding ?

**Comment by mkllnk** [comment]
My current work in progress:

* https://github.com/openfoodfoundation/openfoodnetwork/compare/master...mkllnk:openfoodnetwork:dfc-order

**Comment by mkllnk** [comment]
@RaggedStaff, my latest blocker is the orders endpoint responding with an error 500 when posting a new order. I don't know if it's a bug or just missing parameters. I'm sending `POST https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders`:

```json
{
    "@context": "https://www.datafoodconsortium.org",
    "@graph": [
        {
            "@type": "dfc-b:Order",
            "dfc-b:orderNumber": "",
            "dfc-b:date": "",
            "dfc-b:hasPart": {
                "@type": "dfc-b:OrderLine",
                "dfc-b:description": "",
                "dfc-b:quantity": 3,
                "dfc-b:concerns": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466238259/Offer"
            },
            "dfc-b:orderedBy": "http://test.host/api/dfc/enterprises/384"
        },
        {
            "@type": "dfc-b:OrderLine",
            "dfc-b:description": "",
            "dfc-b:quantity": 3,
            "dfc-b:concerns": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466238259/Offer"
        }
    ]
}
```

Comparing that to the [spec by Garethe](https://app.swaggerhub.com/apis-docs/RAGGEDSTAFF23/dfc-sample_api/v1.12.1#/Orders/post_api_dfc_Enterprises__enterprise_id__Orders), I have some questions. There are a lot more fields which I thought were not needed here. But which ones are mandatory?

* "dfc-b:belongsTo":  We don't have a sales session, right?
* "dfc-b:orderNumber": The order number should be generated by the endpoint, right?
* "dfc-b:hasOrderStatus": Is _draft_ the default or do I need to include this?
* "dfc-b:hasFulfilmentStatus": Mandatory?
* "dfc-b:hasPaymentState": I would assume this to be filled in by the endpoint.
* "dfc-b:hasPaymentMethod": I don't know any published payment methods. Is there a magical value here or can I omit?
* "dfc-b:discount": Surely not used here.
* "dfc-b:OrderedBy": Required? Person identified on the OFN? Or do I need to know the id of the person on the Shopify side?
* "dfc-b:soldBy": Required? Same, can I use the OFN id?
* "dfc-b:selects": Do I need to know a shipping method?
* "dfc-b:uses": Same question.
* "dfc-b:hasPart": When posting an order, I don't set my own price, do I?

**Comment by RaggedStaff** [comment]
**From a DFC Standard/ontology perspective, almost everything is optional.** That said, Shopify will require some data to build an Order. Have you tried Orders.GET to see what it looks like coming back ? 
 
I think you need to send 
```
         "dfc-b:orderNumber": "#",
```
To indicate a null id.

You do need to include the states: 
```
         "dfc-b:hasOrderStatus: Draft ,
         "dfc-b:hasFulfilmentStatus: Unfulfilled ,
         "dfc-b:hasPaymentStatus: Unpaid ,
```
Are the defaults, I think. @ajluker or @dupreesi can confirm what they expect/accept.

> "dfc-b:hasPaymentMethod": I don't know any published payment methods. Is there a magical value here or can I omit?

Not enumerated within DFC, I think you can ommit this.

> "dfc-b:discount": Surely not used here.

No, not required for this UC. May be applied by the creating platform.

> "dfc-b:OrderedBy": Required? Person identified on the OFN? Or do I need to know the id of the person on the Shopify side?

This is the URI (Id) of the Agent placing the Order... in this case the Shopify customer. I'm expecting the receiving platform to handle that, using data from the OIDC credentials (& any linked account).

> "dfc-b:soldBy": Required? Same, can I use the OFN id?

Not required, or even relevant for this UC.

> "dfc-b:selects": Do I need to know a shipping method?

Nope. That  should be set later (probably  within the Shopify UI)

> "dfc-b:uses": Same question.

I don't think PickUpOptions are valid for this pilot, but same story - 

> "dfc-b:hasPart": When posting an order, I don't set my own price, do I?

In this instance - `hasPart` indicates a relationship to an `OrderLine` object, which contains a link to `Offer`, not `Price`, there was an error in the ontology & the swagger spec needs updating. You will need to include at least 1 `OrderLine` object - as Shopify will not allow the creation of an order without a line item. You can will need to include: 

* `dfc-b:concerns:` - to provide the Shopify `SuppliedProduct` URI for the product 
* `dfc-b:hasQuantity:` - to confirm the amount of items being ordered (e.g. 1 Case, 3 kg etc) - you can pull the `hasUnit` value from `SuppliedProduct:hasQuantity` (they mostly seem to be "dfc-m:Kilogram" for the test products).

**Comment by dupreesi** [comment]
Hi @RaggedStaff @mkllnk as promised here are some logs when a Hub sends Shopify Orders to the Producer. I hope it helps, if you are still having issues I'd suggest we try an debug on a call. 

- As soon as the first OrderLine gets ordered via the Hub, we send a POST (example 1) which then creates a Draft Order on the Producer's Shopify.
- For any additionally incoming Hub orders, we send PUT requests to the endpoint using the OrderId (examples 2,3). 
- When a SalesSession finishes the Draft Order Status gets updated (example 4)

**1. CREATE ORDER (POST https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders)**

Example request body for creating a DraftOrder ordering 5 cases of Apple Syrup from the producer (test-hodmedod). 

```
{
  "@context": "https://www.datafoodconsortium.org",
  "@graph": [
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/1",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466402099"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/#",
      "@type": "dfc-b:Order",
      "dfc-b:hasOrderStatus": {
        "@id": "dfc-v:Held"
      },
      "dfc-b:hasPart": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/#/OrderLines/1"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/#/OrderLines/1",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/1"
      },
      "dfc-b:quantity": "5"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SalesSession/#",
      "@type": "dfc-b:SaleSession",
      "dfc-b:beginDate": "Tue Aug 20 2024 08:02:23 GMT+0000 (Coordinated Universal Time)",
      "dfc-b:endDate": "Tue Aug 27 2024 08:02:23 GMT+0000 (Coordinated Universal Time)"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466402099",
      "@type": "dfc-b:SuppliedProduct"
    }
  ]
}
```
This post request created Draft 50: 

<img width="609" alt="Bildschirmfoto 2024-08-20 um 10 04 29" src="https://github.com/user-attachments/assets/33210156-8e81-4d49-b0ea-7788a2fb5892">
<img width="628" alt="Bildschirmfoto 2024-08-20 um 10 04 38" src="https://github.com/user-attachments/assets/71daa079-de02-4707-b0aa-2f147959dcfa">


**2. UPDATE ORDER (PUT https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083)**

Example request body to update the existing Draft 50 (OrderId 1173026636083) with updated line items (10 cases of Barley Flakes). Note that for updating an existing DraftOrder, all of the existing  + updated line items need to be sent. 
Once Shopify has created / updated a Draft Order, OrderLinesIds get created. When new OrderLines are being sent (that aren't part of the existing order), we can use an indexed Id, e.g. OrderLines.length + 1.

```
{
  "@context": "https://www.datafoodconsortium.org",
  "@graph": [
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/1",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466402099"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/2",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466565939"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083",
      "@type": "dfc-b:Order",
      "dfc-b:hasOrderStatus": {
        "@id": "dfc-v:Held"
      },
      "dfc-b:hasPart": [
        {
          "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/93"
        },
        {
          "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/2"
        }
      ]
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/2",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/2"
      },
      "dfc-b:quantity": "10"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/93",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/1"
      },
      "dfc-b:quantity": "5"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466402099",
      "@type": "dfc-b:SuppliedProduct"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466565939",
      "@type": "dfc-b:SuppliedProduct"
    }
  ]
}
```
Updated Draft Order:
<img width="629" alt="Bildschirmfoto 2024-08-20 um 10 12 13" src="https://github.com/user-attachments/assets/dc07b38a-489a-4a11-a9f4-6107a3e12f2a">


**3. Ordering 7 cases of Baked British Beans (another PUT to https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083)**

Same principle as above - exiting + updated order lines are needed for Shopify to update the draft order.
```
{
  "@context": "https://www.datafoodconsortium.org",
  "@graph": [
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/1",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466402099"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/2",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466565939"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/3",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466500403"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083",
      "@type": "dfc-b:Order",
      "dfc-b:hasOrderStatus": {
        "@id": "dfc-v:Held"
      },
      "dfc-b:hasPart": [
        {
          "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/93"
        },
        {
          "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/95"
        },
        {
          "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/3"
        }
      ]
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/3",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/3"
      },
      "dfc-b:quantity": "7"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/93",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/1"
      },
      "dfc-b:quantity": "5"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/95",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/2"
      },
      "dfc-b:quantity": "10"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466402099",
      "@type": "dfc-b:SuppliedProduct"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466500403",
      "@type": "dfc-b:SuppliedProduct"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466565939",
      "@type": "dfc-b:SuppliedProduct"
    }
  ]
}
```


**4. Completing the Draft Order (Also PUT to https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083)**

To complete the draft order the order status has to be updated using this request body:

```
{
  "@context": "https://www.datafoodconsortium.org",
  "@graph": [
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/1",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466402099"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/2",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466565939"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/3",
      "@type": "dfc-b:Offer",
      "dfc-b:offeredItem": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466500403"
      }
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083",
      "@type": "dfc-b:Order",
      "dfc-b:hasOrderStatus": {
        "@id": "dfc-v:Complete"
      },
      "dfc-b:hasPart": [
        {
          "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/93"
        },
        {
          "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/95"
        },
        {
          "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/98"
        }
      ]
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/93",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/1"
      },
      "dfc-b:quantity": "5"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/95",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/2"
      },
      "dfc-b:quantity": "10"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083/OrderLines/98",
      "@type": "dfc-b:OrderLine",
      "dfc-b:concerns": {
        "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/3"
      },
      "dfc-b:quantity": "7"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466402099",
      "@type": "dfc-b:SuppliedProduct"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466500403",
      "@type": "dfc-b:SuppliedProduct"
    },
    {
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466565939",
      "@type": "dfc-b:SuppliedProduct"
    }
  ]
}
```

Result: 

<img width="626" alt="Bildschirmfoto 2024-08-20 um 10 34 25" src="https://github.com/user-attachments/assets/c7adb1b6-fc46-4527-8ea0-0f9220c32eb5">

**Comment by dupreesi** [comment]
So in summary:
1. get all supplied products that are available via the producer endpoint
2. create a new order using one or more supplied products including their required Offers / OrderLines / SalesSession
3. Get the OrderId of the created Order
4. test the PUT endpoint to update the Order by its Id

**Comment by mkllnk** [comment]
I tried to follow your example as closely as possible and finally created an order. :tada: 

Here are a few things I noticed:

* The value of `dfc-b:offeredItem` is expressed as string on our side but as object on your side. That verb is actually not mentioned in the official context. So I wondered if the connector may not know to interpret this as object. But this turned out to be all good.
* The OrderLine was anonymous in our data but has an id in your example. I just pasted your id in and it worked! So I guess we have to enumerate the line item ids.
* The SaleSession is not connected to anything. Why does the connector need it then? How shall we set the dates going forward?

**Comment by dupreesi** [comment]
Hey @mkllnk, I'm pleased to hear that it has worked! 
Regarding your first two remarks, I think it'd be best to check with @RaggedStaff as we're not in charge of refactoring code within the connector repository (we're only calling its functions to create the graph). 
Regarding the SalesSession - this is only used to send across the dates for the stock to be reserved until (end-date). 
We are also storing these dates in our database and there is an automation in place that automatically finishes a SalesSession and opens an new one based on the end date. Additionally, the hub user has the option to manually create or finish a SalesSession if needed. 
Once a SalesSession ends, the draft order is being completed and can be fulfilled. 
Regarding formatting the dates: do you think you could stick to the provided example format? 
```
"Tue Aug 27 2024 08:02:23 GMT+0000 (Coordinated Universal Time)"
```

**Comment by mkllnk** [comment]
> Once a SalesSession ends, the draft order is being completed and can be fulfilled.

Does that happen automatically or do we need to finalise the order by updating the status?

> Regarding formatting the dates: do you think you could stick to the provided example format?

That's serialised by the connector. It's a standard JSON encoding for dates.

**Comment by mkllnk** [comment]
> Regarding formatting the dates: do you think you could stick to the provided example format?

Follow up: the standard JSON format raised a server error again. I tried a few different formats and found:

* The timezone has to be GMT+0000 or UTC.
* Working: `"Thu Aug 22 2024 05:40:38 UTC"`

**Comment by dupreesi** [comment]
> > Once a SalesSession ends, the draft order is being completed and can be fulfilled.
> 
> Does that happen automatically or do we need to finalise the order by updating the status?

At the moment there is not automation for external connections in place (only within the two Shopify Apps).
So to end a SalesSession (Draft)Order you need to manually send a PUT with an updated order status (example 4).
```
{
      "@id": "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1173026636083",
      "@type": "dfc-b:Order",
      "dfc-b:hasOrderStatus": {
        "@id": "dfc-v:Complete"
      }
```

Great that the dates are working. Thanks for checking!

**Comment by RaggedStaff** [comment]
@dupreesi - I think we will need to standardise date formats (to ISO) at some point. I'll create an issue for that on the backlog.

**Comment by mkllnk** [comment]
@dupreesi, I have trouble updating an existing order. I tried a lot of different things but can't get it to work. And now suddenly the server is responding error 500 when listing orders. Something is broken again.


Anyway, here's the body of the PUT update request I tried:

```json
{
   "@context" : "https://www.datafoodconsortium.org",
   "@graph" : [
      {
         "@id" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1175203184947",
         "@type" : "dfc-b:Order",
         "dfc-b:date" : "",
         "dfc-b:hasOrderStatus" : "dfc-v:Held",
         "dfc-b:hasPart" : [
            "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1175203184947/orderLines/117",
            "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1175203184947/orderLines/2"
         ],
         "dfc-b:orderNumber" : ""
      },
      {
         "@id" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1175203184947/orderLines/117",
         "@type" : "dfc-b:OrderLine",
         "dfc-b:concerns" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/44519466467635",
         "dfc-b:description" : "",
         "dfc-b:hasPrice" : {
            "@type" : "dfc-b:Price",
            "dfc-b:VATrate" : 0,
            "dfc-b:hasUnit" : "dfc-m:PoundSterling",
            "dfc-b:value" : "2.09"
         },
         "dfc-b:quantity" : "3"
      },
      {
         "@id" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Orders/1175203184947/orderLines/2",
         "@type" : "dfc-b:OrderLine",
         "dfc-b:concerns" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466467635/Offer",
         "dfc-b:description" : "",
         "dfc-b:quantity" : 3
      },
      {
         "@id" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/44519466467635",
         "@type" : "dfc-b:Offer",
         "dfc-b:offeredItem" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466467635",
         "dfc-b:stockLimitation" : 0
      },
      {
         "@id" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466467635/Offer",
         "@type" : "dfc-b:Offer",
         "dfc-b:hasPrice" : {
            "@type" : "dfc-b:Price",
            "dfc-b:VATrate" : "0",
            "dfc-b:hasUnit" : "dfc-m:Euro",
            "dfc-b:value" : "2.09"
         },
         "dfc-b:offeredItem" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466467635",
         "dfc-b:stockLimitation" : 0
      },
      {
         "@id" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466467635",
         "@type" : "dfc-b:SuppliedProduct",
         "dfc-b:alcoholPercentage" : 0,
         "dfc-b:description" : "",
         "dfc-b:lifetime" : "",
         "dfc-b:name" : "",
         "dfc-b:totalTheoreticalStock" : 0,
         "dfc-b:usageOrStorageCondition" : ""
      },
      {
         "@id" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466467635",
         "@type" : "dfc-b:SuppliedProduct",
         "dfc-b:alcoholPercentage" : 0,
         "dfc-b:description" : "<table width=\"100%\">\n<tbody>\n<tr style=\"border: 0px;\">\n<td bgcolor=\"#d6fbed\" style=\"color: #000000; border: 0px;\"><strong>They're back!</strong></td>\n</tr>\n</tbody>\n</table>\n<p><strong>Think baked beans are British? They are now! We use only British-grown fava beans - Britain's original bean, grown here since the Iron Age. Our Baked British Beans are deliciously different, with large meaty fava beans in a tasty tomato sauce.</strong></p>\n<p><strong><a title=\"What are fava beans? Aren't they just broad beans?\" href=\"/blogs/news/what-are-fava-beans-are-they-just-broad-beans\" data-mce-fragment=\"1\" data-mce-href=\"/blogs/news/what-are-fava-beans-are-they-just-broad-beans\">What are fava beans? Find out here...</a></strong></p>\n<!-- split --><h3>Complete Product Details</h3><p>Our Baked British Beans are cooked and ready to eat, hot or cold. They're good served on toast but also delicious added to stews, curries or casseroles. Or even in a pie.</p>\n<h5 class=\"product-detail-title\">Cooking instructions</h5>\n<p><strong>Cooking on the Hob</strong><br>Empty contents into saucepan. Heat gently for 4-5 minutes while stirring. For best flavour do not boil or overcook. Do not reheat.</p>\n<p><strong>Microwave Cooking</strong><br>Empty contents into a non-metallic bowl and cover. Heat for 2 to 3 minutes, stirring halfway. Check the food is hot, stir well and serve. Do not reheat.</p>\n<h5 class=\"product-detail-title\">To Store</h5>\n<p>Store in a cool, dry place. Once opened, transfer contents to a non-metallic container, cover refrigerate and use with 2 days.</p>\n<h5 class=\"product-detail-title\">Ingredients</h5>\n<p>Fava Beans (Broad Beans) (42%), Water, Tomato Puree, Sugar, Modified Maize Starch, Salt, Herbs &amp; Spices, Concentrated Lemon Juice</p>\n<h5 class=\"product-detail-title\">Allergy information</h5>\n<p>No Allergens</p>\n<table width=\"100%\">\n<tbody>\n<tr>\n<td><strong>Typical values</strong></td>\n<td><strong>Per 100g</strong></td>\n</tr>\n<tr>\n<td>Energy</td>\n<td>292kJ (69kcal)</td>\n</tr>\n<tr>\n<td>Fat</td>\n<td>0.4g</td>\n</tr>\n<tr>\n<td>of which saturates</td>\n<td>0.1g</td>\n</tr>\n<tr>\n<td>Carbohydrate</td>\n<td>10.1g</td>\n</tr>\n<tr>\n<td>of which sugars</td>\n<td>4.6g</td>\n</tr>\n<tr>\n<td>Fibre</td>\n<td>5g</td>\n</tr>\n<tr>\n<td>Protein</td>\n<td>4g</td>\n</tr>\n<tr>\n<td>Salt</td>\n<td>0.6g</td>\n</tr>\n</tbody>\n</table><h5 class=\"product-detail-title\">More</h5>\n<p>Delicious, nutritious and good for the soil, fava beans are a variety of broad bean, Vicia faba, left to ripen and dry before harvest. They’re also known as field beans, horse beans, Windsor beans or ful.</p>\n<p>Suitable for vegans and vegetarians</p>\n",
         "dfc-b:hasQuantity" : {
            "@type" : "dfc-b:QuantitativeValue",
            "dfc-b:hasUnit" : "dfc-m:Kilogram",
            "dfc-b:value" : "0.4"
         },
         "dfc-b:image" : "https://cdn.shopify.com/s/files/1/0731/8483/7939/products/Pack-Can-Baked-Beans-1800x6_983x656_513758e6-2616-4687-a8b2-ba6dde864923.jpg?v=1677760778",
         "dfc-b:lifetime" : "",
         "dfc-b:name" : "Baked British Beans - Retail can, 400g (can)",
         "dfc-b:referencedBy" : "https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466467635/CatalogItem",
         "dfc-b:totalTheoreticalStock" : 0,
         "dfc-b:usageOrStorageCondition" : ""
      }
   ]
}
```

Can you spot what's wrong?

**Comment by mkllnk** [comment]
Thank you for explaining that. My code didn't see that the existing line item was for the same product. And the reason is that I was comparing by Offer. But your API uses different ids for offers in different endpoints.

SuppliedProducts contains:
```
https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts/44519466467635/Offer
```

Orders contains:
```
https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/Offers/44519466467635
```

So when placing a new order, I use the id from the supplied products, of course. But then when I retrieve the order again, I get a different id. I'll try to solve this by matching by product instead. But be aware that this means that we are now limited to single a single offer per product. Maybe no problem in your scenario but we are trying to implement code that will work with other DFC APIs as well.

@RaggedStaff, this should probably go in your list for the next iteration.

**Comment by mkllnk** [comment]
I successfully added quantity to an existing order! :tada:

**Comment by mkllnk** [comment]
@ajluker, does your API support deleting orders? I sent a delete request to the order id but got a 400 error back.

I just thought it would be nice to clean up my test data automatically in my tests.

**Comment by mkllnk** [comment]
:heavy_check_mark: Complete an open order.

So the most important API interactions are working.

Question: How do you distinguish between orders from different platforms? The API doesn't expose anything to determine if I placed that order or if someone else did it. The client field is empty.
