### ISSUE TITLE
Add product image upload UX

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1217]
I login to the admin, go to bulk product management and then click "New product". I select a product image to upload. Above the form is what looks like an image preview. When I select an image, this preview remains on the placeholder image. I expect it to change to the uploaded image.

Would we prefer to remove the preview or make the preview update when we select an image? Perhaps we could reuse the image upload widget in the enterprise registration form?

**Comment by daniellemoorhead** [comment]
Hey @RohanM does the image upload widget in the enterprise registration form include a preview? And is it easy enough to add it to the admin interface?

**Comment by myriamboure** [comment]
Iceboxed https://community.openfoodnetwork.org/t/hubs-can-easily-navigate-back-office-and-manage-their-shopfront/1246
#gitcull2018
