### ISSUE TITLE
Remove order cycle admin debug information

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1218]
In every environment other than staging, we see debugging information under an order cycle. This is no longer useful, so remove it entirely.

![ofn-oc-debug](https://cloud.githubusercontent.com/assets/154210/20413682/64edb616-ad82-11e6-99e7-248d5a93b2a9.png)

**Comment by daniellemoorhead** [comment]
Hey @RohanM do you think this would be something that a newbie could do pretty easily?
