### ISSUE TITLE
Add angular cloaking to admin edit enterprise

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1219]
While the edit enterprise interface is loading, we see the angular template before it is rendered. Use `ng-cloak` to hide this until it's ready to display. There are sections to cloak in the menu bar and also the body (see screenshot).

![ofn-edit-enterprise-cloaking-needed](https://cloud.githubusercontent.com/assets/154210/20413732/b2ee5898-ad82-11e6-8ba3-9b1fcd84d39c.png)

**Comment by nikobozi** [comment]
Hello, new contributer here! I tried to reproduce this, but it looks to me like this is not an issue anymore, can this be closed then?

**Comment by daniellemoorhead** [comment]
@sauloperez @luisramos0 @HugsDaniel @kristinalim @myriamboure @RachL can one of you check whether this is actually still an issue, and close it if it isn't? 🙂

**Comment by jonleighton** [comment]
I've checked this and agree with the conclusion that it is no longer a problem. `ng-cloak` is in the source for the page. (it's in `app/views/admin/enterprises/_ng_form.html`) I think this can be closed.

**Comment by luisramos0** [comment]
awesome, thanks @jonleighton
