### ISSUE TITLE
Create option to ask for donation at checkout

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1220]
building on the discussion at [G#1202](https://github.com/openfoodfoundation/openfoodnetwork/issues/1202#issuecomment-261425029) it would be good to have this option for not-for-profit hubs which need voluntary support.  Also for food banks who are giving away the food but want to give 'shoppers' the option to make a voluntary donation

**Comment by arthur-koenig** [comment]
We are very interested in this feature in France ! @NickWeir63 The donation field could be configured by the hub's admin, with options such as min and max, and adding engaging text. I guess it's just an extra field that could be transferred via the payment API ?

**Comment by lin-d-hop** [comment]
#gitcull2017 
Moving from github to wishlist
https://community.openfoodnetwork.org/t/voluntary-donation-at-checkout/1147
