### ISSUE TITLE
Remove default social Spree preferences

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#1221]
There are several default social media and other preferences in 

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/content_configuration.rb

Can I suggest they would be better removed? A useful default is one that doesnt need changing. In this case most of those should be changed depending on the domain or country the OFN install is for.

I raise this because it was confusing with a test UK install that Aus values were set. Simpler would have been to see blanks, more obvious they must be set manually.

Happy to do a PR if others agree. @mkllnk @oeoeaio thoughts?

**Comment by NickWeir63** [comment]
From a UK admin perspective I agree it would be better to have blanks than Aus links

**Comment by mkllnk** [comment]
I guess the idea behind that was backwards compatibility. The Australian values were hard-coded at first. So if we remove the default values, we should add a migration that sets the Australian values if no value is present yet to avoid loosing the Australian configuration. That would have been the better way to start with. I think it's a great idea to fix it.

**Comment by pmackay** [comment]
@mkllnk I'm a but puzzled by this, how would setting the Aus values in a migration be different to having default values? If migrations are run on a new install isnt the outcome the same? I'm probably missing something...

**Comment by mkllnk** [comment]
I wouldn't run all migrations for a new install. I would just run `rake db:setup` which is loading the schema and inserting seed data. We could also do a migration that sets the default values only for a certain locale. What do you think?

**Comment by lin-d-hop** [comment]
No longer relevant.
