### ISSUE TITLE
Improve display of group buy in shopfront

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1222]
A user has pointed out how unintuitive the group buy display in the shop front in. For someone who's never used the tool before, there are multiple ways they could interpret its functionality. For the example below, the user was unsure whether the 1kg meant the max that could be purchased (it's actually the unit size).

Ways to improve:
- Include an info, or what's this? box with an explanation of the tool
- Include the total bulk unit size for the customer's knowledge
- Show how close the group is to reaching the bulk unit size
- Remove the 'bulk' icon from group buy products - she didn't know what this meant. Some products which are bulk (5kg almonds) but didn't have the group buy tool, don't have the bulk icon, which is confusing.
- Change 'min and max' text to 'prefered' and 'upper limit'.. or something else.

![image](https://cloud.githubusercontent.com/assets/10843056/20467326/6caae6b8-afd9-11e6-9ca5-8f310551d8ed.png)

**Comment by myriamboure** [comment]
Add this to "improve placing order UX" icebox as one of the feature candidate: https://community.openfoodnetwork.org/t/customer-easily-go-through-the-whole-placing-order-process/1245
So closing for now.
