### ISSUE TITLE
Make 'choose when you want your order' customisable

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1223]
A user has requested the ability to customise the 'choose when you want your order' flag, for shops with multiple active order cycles.

This phrase doesn't suit all uses of multiple order cycles.

Below is a screenshot of the user's request/case
![image](https://cloud.githubusercontent.com/assets/10843056/20467402/14a38630-afdb-11e6-8820-7c4ae32bbd54.png)

**Comment by myriamboure** [comment]
I think this is not adaptable either to all cases... I think the best option would be to let the hub determine the phrasing, if that could be set up in the hub, as he set up the default close shop message, he could also set up this message?

**Comment by NickWeir63** [comment]
i like Myriam's suggestion to make it customisable.  I have a UK user who wants to use OFN for his veg box scheme  He has 2 delivery rounds on different days of the week to different areas so he would want to write 'delivery around Axminster on a Tuesday' or 'delivery around Crediton on a Friday'

**Comment by sstead** [comment]
Yes customisable is the way to go. The image above is just one use case- they're a farmer's market with a different OC for each location.

**Comment by lin-d-hop** [comment]
Transifex does this on Instance level. 
I don't think we care enough :-)
