### ISSUE TITLE
Data sharing button not triggering N8N

### ISSUE THREAD

**Issue by amidaOFN** [openfoodfoundation/openfoodnetwork#12231]
The 'Allow Data Sharing' button on the platform is no longer triggering the N8N workflow to create a mini-extensions link/new Airtable record. 

The user view is that the button remains 'spinning' on 'loading' without creating the button to 'Manage Listing' via the miniextensions form. 

There is no attempted execution in N8N history when this happens. 

Amida has replicated by clicking the data sharing button as a manager for the enterprise, not from superadmin account.

There are currently 2 enterprises waiting to receive their miniextensions link - this will become urgent as new enterprises want to access their profile listing.

**Comment by mkllnk** [comment]
The culprit was an expired Airtable access token. This has been resolved.
