### ISSUE TITLE
View producer certifications

### ISSUE THREAD

**Issue by JbPasquier** [openfoodfoundation/openfoodnetwork#12237]
![Image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/f6dbecd9-36d4-43dc-aa62-68e524f8848d)

Kirsten has added a certification to Pukawidgee, has been confirmed, so there is now test data

**Comment by JbPasquier** [comment]
I missed this one. Now that I have a clearer idea on what is a Supporting Evidence, what is an Assurance and what is a Certification, I can see an issue with this.

We can't mix content with different properties in the same display. This is a framework limitation based on the specification. You can see it like trying to put a plane in a cardboard box made for trains.

We should have handled this one beforehand the implementation. It was unclear to us that those two things where related.

How can we implement that now?

- Quick one, we could have a third entrypoint on a producer, with the mixed content merged in.
- Or, cleanest one would be to merge certification and supporting evidence while keeping their separate @type. But that'll require *a lot* of work to re-do the component with this new behaviour.
- Or, easiest one would be to split it in two on the display. You'll always have supporting evidence on top then certifications on the bottom.
- Or, maybe certifications aren't plane, maybe they're trains too?

It's still unclear to me what's the relation between a certification and a supporting evidence. Shouldn't a Certification be a Supporting Evidence with an ofn:Classification - ofn:label of Certification?
Could this work?

**Comment by JbPasquier** [comment]
Done with the custom implementation.

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/14278890/989e2467-7b76-4555-bd79-969284717a4e)

**Comment by kirstenalarsen** [comment]
Looks like you've been doing wonderful things @JbPasquier , that I don't quite understand, but thank you! 

This is close: missing Source field, link to download doc and 'read more'

![Image](https://github.com/openfoodfoundation/openfoodnetwork/assets/2911176/bbe25411-bc6b-454c-ba71-bb9af0e2d6b6)

NB. Source is now working for the other evidence (yay) - spacing a bit funny?


![Image](https://github.com/openfoodfoundation/openfoodnetwork/assets/2911176/5e4c65f7-4d9b-4ea9-89a9-631f9e8379e5)

**Comment by JbPasquier** [comment]
I'm fixing the missing source for certification.

@mkllnk Can you point me which fields I should add?

I'm currently displaying:
- ofn:Creation_date
- ofn:Title
- ofn:Classification - ofn:label
- ofn:Certification_status
- ofn:Expiry_date
- ofn:Certification_ID
- ofn:service_provider_label
- ofn:service_provider_uri
- ofn:Description
- ofn:Documentation_permissions

Am I missing some others?

**Comment by kirstenalarsen** [comment]
@mkllnk and @mariocarabotta are going to check the data for these fields @JbPasquier 

Once this is done, can we also apply this logic to how the Supporting Evidence filter works on the Producer list? This would clean up the problems we are having in a range of other issues

**Comment by JbPasquier** [comment]
> Supporting Evidence filter works on the Producer list?

No, the way I implemented it here works because there is really only a small amount of data. It's just one producer's data.
If this custom implementation were to filter the entire list of producers, it would take a really long time to filter anything.

The main issue here is the complexity of the data: filtering many certifications within many supporting evidence within many producers (within many products on the other list), combined with an 'and/or' filter.

Maybe we can think of some data adaptation. @mkllnk would it be complex for you to pre-calculate all of this and add three fields directly on a producer/products with all its relevant `Supporting Evidence`, `Assurance Partners` and `Certifications` filters? The same way you did `ofn:Produce_category`?

**Comment by kirstenalarsen** [comment]
ah ok, we'll chat here and get back to you

**Comment by kirstenalarsen** [comment]
OK, this one is CLOSED
