### ISSUE TITLE
Embed Blox in Wordpress

### ISSUE THREAD

**Issue by JbPasquier** [openfoodfoundation/openfoodnetwork#12238]
See ours live at https://regenerative.org.au/test/

Wordpress intergration: [Slack discussion here](https://openfoodnetwork.slack.com/archives/C063G64AFTP/p1709226467943049
)
@JbPasquier deployed an internal wordpress to test different behaviours, good news, no issue encountered ( https://ofn-rpp-wp.startinblox.com/ ), I've written some integration guidelines there: https://git.startinblox.com/components/ofn-rpp/-/blob/master/INTEGRATION.md

@mkllnk questions:
I have a question about the rewrite rule:
RewriteRule ^my-page/.+$ /my-page/ [L]
How does it work when we have the component on the home page? Can we check for a path like ^regenerative-produce-portal-.+$?

maikel
:deciduous_tree:  [5 days ago](https://openfoodnetwork.slack.com/archives/C063G64AFTP/p1709266461749899?thread_ts=1709226467.943049&cid=C063G64AFTP)
I copied the component to this page: https://regenerative.org.au/test/
It mostly worked fine but the rewrite rule doesn't seem to work. I put this at the top of the .htaccess file above the Wordpress config:
RewriteEngine On
RewriteBase /
RewriteRule ^test/.+$ /test/ [L]
(edited)

![Image](https://github.com/openfoodfoundation/openfoodnetwork/assets/2911176/b5aa35fb-a032-440d-9138-a8e7476ea78f)

**Comment by JbPasquier** [comment]
I'm trying some workaround to see if they could fit your WP.

I have an unsatisfying one, remove our lines from the `.htaccess` then replace your WP permalink setting with something like `/%postname%/.+.`

This way, it'll avoid 404, but when you reach a producer details directly or refresh the page it's always redirected to the producers list.

It could work as an imperfect workaround while we find a better solution.

Implemented on our WP as example.

**Comment by mkllnk** [comment]
I see. So sharing a link to a producer redirects to the components start page instead of the producer. That's better than the 404 we got before but, as you say, unsatisfying. The issue is with the internal routing of Wordpress, I believe. Maybe it would need a special plugin to route certain requests to a page while preserving the path.

**Comment by JbPasquier** [comment]
Exact.

Alex pointed me to the [WP_Rewrite](https://developer.wordpress.org/reference/classes/wp_rewrite/) class of Wordpress, that would allow these kind of rewrite from your theme files.

It should look like something like that:
```php
  $wp_rewrite->rules = array('^some_path/.+$' => $wp_rewrite->index . '?pagename=some-path') + $wp_rewrite->rules;
```
But I haven't been able to test it.

The only difference with the htaccess approach is that it also set up the Wordpress query class which may be needed on your WP to allow a proper rewrite?

**Comment by mkllnk** [comment]
By the way, our current test page is https://regenerative.org.au/test/. But when it's going live, we want to move that to the home page.

**Comment by JbPasquier** [comment]
In that case, the Alex's way should work better, but you will have to add the prefix to the rewrite rule to avoid conflict with your other pages.

On the component integration, you can remove the `route-prefix="test"` and it'll handle the root path by itself.

**Comment by kirstenalarsen** [comment]
This is good! Only thing we need to do is move it to the right page for launch

**Comment by mkllnk** [comment]
@kirstenalarsen Is this now considered done?

**Comment by kirstenalarsen** [comment]
yep I reckon
