### ISSUE TITLE
Openstreetmap loaded via http breaking https

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1226]
All map pages load from http://tile.openstreetmap.org/. That connection is not encrypted and compromises the security on all pages with a map.

**Comment by pmackay** [comment]
This could be fixed by changing

`'http://tile.openstreetmap.org/'`

to

`'https://c.tile.openstreetmap.org/'`

(you have to use one of the a/b/c sub-domains for `https` to work correctly)
