### ISSUE TITLE
[DFC Orders] Update staging FR and UK data

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12270]
## Description
**- As a:** tester / OFN team member
**- On page:** staging UK and FR
**- I want to be able to do:** I want to see recent anonymized data on both staging server, in order to fetch the taxonomies maching that was done in prod.

(I think) this is the task we use to put prod data to stagings: https://github.com/openfoodfoundation/openfoodnetwork/blob/29dad44f9fd181d4cdd7ff109b40f9c8d0985d77/lib/tasks/data/truncate_data.rake#L4

## Acceptance Criteria & Tests

1. DFC's taxon URI are available in both staging
2. Production data is present although all emails are anonymized

- This will close https://github.com/openfoodfoundation/openfoodnetwork/issues/12375

**Comment by dacook** [comment]
I'm sure it's written somewhere, but just confirming that these would be refreshed from their respective prod servers:
* uk_prod -> uk_staging
* fr_prod -> fr_staging

**Comment by dacook** [comment]
uk_staging is in progress, but I hit a snag and wasn't able to complete it this week.

I know what to do next, and will document it for next time. Remaining <30min for uk_staging.
I think fr_staging would only take <1hr now that I know what to do.

**Comment by mkllnk** [comment]
Hm, I think that uk-staging had Canadian data but I'm not sure. And I don't know if it matters.

**Comment by RachL** [comment]
> I think that uk-staging had Canadian data 

Yes indeed, but we've talked about in testing circle and concluded we did not need CA data anymore. I think it was used to have an instance with tax excluded from price. 

Moreover @RaggedStaff wants to have UK data on staging to be able to test DFC related stuff. So back to :gb:

**Comment by dacook** [comment]
I'm having a frustrating problem with the uk_staging server and am unable to fix it. 
I'm sad to say it might not be worth spending more time on, and instead work on upgrading the server.

**Comment by dacook** [comment]
UK Staging is up! https://staging.openfoodnetwork.org.uk/

More notes about access: https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1723705437065689

I've removed the no-staging label as I believe it's now usable again 🎉

**Comment by dacook** [comment]
I've added notes to the wiki for next time:
https://github.com/openfoodfoundation/ofn-install/wiki/Refreshing-a-staging-server

**Comment by dacook** [comment]
fr_staging is updated!
https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1725852798586159
