### ISSUE TITLE
Update button not enabled after deleting a manager in Enterprise Settings

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1227]
The delete will not save until I've clicked the update button. As a work around, user must change something else to make the button clickable.

![image](https://cloud.githubusercontent.com/assets/10843056/20545648/692e3a58-b164-11e6-80be-7bede27e93c7.png)

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley do you think this would be a good newbie issue?

**Comment by daniellemoorhead** [comment]
@sstead is this still a bug?

**Comment by sstead** [comment]
No seems fixed :D
