### ISSUE TITLE
Allow to turn the feature toggle on for all new users

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12282]
## Description
**- As a:** enterprise user newly created
**- On page:** /admin
**- I want to be able to do:** see `admin_v3_style` as default behavior

To do so, we need to be able to add this group of users to the feature toggle.

**new users = created after July 3rd.**

## Acceptance Criteria & Tests

1. Turn on feature toggle for new users
2. Create an new enterprise
3. See the new admin is here by default
4. Check old enterprise have not changed
5. Check disabling this group of actors brings back the old designs.

## Dependencies
This can be done once we've implemented all [BUU1](https://github.com/openfoodfoundation/openfoodnetwork/milestone/64) features, plus
* https://github.com/openfoodfoundation/openfoodnetwork/pull/11645

**Comment by mkllnk** [comment]
@RachL, from which date on do you want to count new users? Were you imagining the date of deployment? Or the time the feature is toggled on?

The easiest implementation would be to create a Flipper group which would select all users created after a certain date. That would allow you to enable or disable the feature for the entire group at any time, and still enable for individual users as well.

**Comment by RachL** [comment]
@mkllnk I assumed each instance could toggle it on or off when they want so yes the flipper group sounds perfect! But we need to define a date and I guess it will be hard coded in the group. So this is block until we know when the first milestone will be done :+1:

**Comment by dacook** [comment]
I'm not familiar with Flipper groups, but am estimating it won't take more than **1 day**.

**Comment by dacook** [comment]
@RachL I've added a dependencies title in the description above, please let me know if this is not correct.

**Comment by RachL** [comment]
@dacook I don't know. This is mainly blocked because we need to choose a date, after which we consider people are new to the system. To be able to choose this date, we need to understand when the milestone will be ready. In my mind, we would be able to work on this issue in parallel of finishing the test: both could go on the release at the same time.
