### ISSUE TITLE
Clone DB from UK-prod, into staging-UK

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12283]
### What we should change and why (this is tech debt)

We need to clone and anonymize personal data from the UK-prod DB, into staging-UK.

### Context

This came up here:
https://community.openfoodnetwork.org/t/testers-catch-up-6th-march-2024/2939

### Impact and timeline

 This should enable us to test the DFC-orders feature.

**Comment by RachL** [comment]
@filipefurtad0 we will do it as part of the DFC orders project, so we have https://github.com/openfoodfoundation/openfoodnetwork/issues/12270 to cover this already (and yes I took the liberty to add staging FR as well, so we can easily test moving product from one staging to the other using DFC :muscle:

**Comment by filipefurtad0** [comment]
Ah I've missed that issue - thank you @RachL :pray:
