### ISSUE TITLE
Ability to create a negative price product to accomodate returns/refunds

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#1229]
Some food hubs offer refunds for returned packaging,  or refillable containers (milk bottles for example) that have a deposit on them when purchased. It would be useful OFN could credit a subsequent order with a returned package/bottle.  If the platform would accept a negative price value,  then a hub could enter a product as -  returned milk bottle,   and a price as a negative  ($-2.00).

**Comment by lin-d-hop** [comment]
this is a feature and requires inception and prioritisation. #gitcull
