### ISSUE TITLE
[Missing translation] Return authorizarion: status

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12295]
## Description

Spotted in the scope of https://github.com/openfoodfoundation/openfoodnetwork/pull/11958.

There is a missing translation in the return authorizations section.

## Expected Behavior

Status should be a translatable string.

## Actual Behaviour

Status is always displayed in English.

## Steps to Reproduce

1. For a given shipped order, create a return authorization.
2. Change to a locale other than EN.
3. Notice the missing translation on Status.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/e17ea600-a719-472d-b5a0-e9557a2c54b9)

## Workaround

-

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.34
* Browser name and version: Firefox 123
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

The relevant file should be:
`./app/views/spree/admin/return_authorizations/edit.html.haml`

**Comment by arunguleria** [comment]
Hello @sigmundpetersen,  I would like to work on this

**Comment by sigmundpetersen** [comment]
Sure thank you @arunguleria !
Don't hesitate to ask if there's anything

**Comment by kellyzhangg** [comment]
Is this issue closed? The pull requests seems to solve the issue if I'm not mistaken

**Comment by dacook** [comment]
You're right, the PR is just awaiting a manual test to confirm. Sorry the status was out of date, I've updated it to indicate it's in progress.
