### ISSUE TITLE
[BUU] Wrong tax category display

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12294]
## Description

Found by Konrad (see [slack thread](https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1706706326967479)) when a variant has tax category set to "none", the new product list shows the default category for this variant instead of "none".

## Steps to Reproduce

1. Go see "release farm" products on staging FR
2. See the variant "test" of the product "copy of Frys"
3. The tax category of the variant is set to "none" but the new display shows the TVA 5,5% rate (which is the default rate in staging Fr's config)

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/d1714563-163b-4e28-a39a-2a4e36a11730)

OLD version:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/2ca9abd3-281c-4193-a5c7-b6f6e295da18)

NEW version:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/f54f0438-4ef9-42fa-8e47-2e8193e90401)

## Workaround
No workaround. 

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by chahmedejaz** [comment]
Hey @RachL - I did a spike on this one and here are my findings on it:
- It works as expected when the app has no default tax category i.e. no tax category has default checked
- The issue gets reproduced only when there's a default category present.

I'd like to work on this one, can you please assign it to me? Thanks

**Comment by chahmedejaz** [comment]
**Update:**
The PR is ready for review now.
