### ISSUE TITLE
Rubocop Rails/HelperInstanceVariable

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/openfoodnetwork#12314]
Part of https://github.com/openfoodfoundation/openfoodnetwork/issues/11482

https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/HelperInstanceVariable

**Comment by chahmedejaz** [comment]
Hi @sigmundpetersen - I'd love to work on this one, can you please assign it to me? Thanks.

**Comment by chahmedejaz** [comment]
**Update:**
Development work is complete for this issue. PR is ready for review now. Thanks.
