### ISSUE TITLE
Limit product searching to strings that start with the search term

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1233]
Currently if a customer is searching products the might search for 'tea'. Results of this search include the word 'steak'. This is rather odd.

More commonly, a search would return matches that start with the search string.

As a customer I search for products.
If I search for 'tea'
- Loose Leaf Tea should return
- Teaberry should return
- Steak should not return

If the search string is equal to a word in a taxon/product/producer that product matches.
If the search string appears at the start of a word in a taxon/product/producer that product matches.
If the search string appears within a word in a taxon/product/producer, but not at the start, that product does not match.

We do not need to match case in searches.

![teasearch](https://cloud.githubusercontent.com/assets/8669848/20606891/ffa6b412-b26b-11e6-988f-506cf4880364.png)

**Comment by Matt-Yorkley** [comment]
Not sure there's an easy way to do this without adding huge amounts of overhead with each search. You'd have to be running string functions on every product name in the database for each search in order to achieve this. Unless there's another way?

Also, searching for "cake" would not find "teacake". Hyphenated names would miss too, like "baked" would not find "home-baked".

**Comment by Matt-Yorkley** [comment]
![screenshot from 2016-11-27 22-58-10](https://cloud.githubusercontent.com/assets/9029026/20652662/36022470-b4f5-11e6-912d-639ed80a0fa9.png)

Think of the Papple Juice!

**Comment by lin-d-hop** [comment]
Personally I think even with these cases the search would be improved by not taking any part string. It should reduce search overload too. There must be libraries for this. 
@Matt-Yorkley could you investigate and propose a solution?

**Comment by lin-d-hop** [comment]
Rhodri to investigate a possible solution and feedback

**Comment by lin-d-hop** [comment]
@rhodri @stveep I think it'll be useful, Steve, if you maybe just pair with Rhodri to show him how you'd go about unpicking where to look for this and how to go about it. It's a Darkswarm out there :-)

**Comment by rhodri** [comment]
😽

**Comment by lin-d-hop** [comment]
This is now available again if anyone is willing to pick up where Rhodri left off?

**Comment by OliverUK** [comment]
@lin-d-hop 
Mixed results testing this. 
Searching for "tea" now no longer returns Steak. Various searches for product titles returned no surprises. For example Sauerkraut in a jar is returned for searching of "jar" and "Sauer" but not kraut. While in this particular case it would be ok if it did, it's not a problem that it doesn't.

But presumably searching should still work for variants too?
In the examples screenshotted below, thighs, fillet and rump don't return any result while steak returns the Beef listing (as it should).
Rolled, shoulder and tudor return the pork listing but belly doesn't.
Neither Dijon nor Wholegrain return the Mustard.
![screen shot 2017-05-19 at 14 06 37](https://cloud.githubusercontent.com/assets/17590921/26249230/9e7e1ae2-3c9d-11e7-8f15-09b47bc86e55.png)
![screen shot 2017-05-19 at 14 06 54](https://cloud.githubusercontent.com/assets/17590921/26249231/9e8264d0-3c9d-11e7-8aee-047b7f231bd9.png)
![screen shot 2017-05-19 at 14 15 13](https://cloud.githubusercontent.com/assets/17590921/26249237/a2ba7f24-3c9d-11e7-9301-ede45cc44f2a.png)

**Comment by mkllnk** [comment]
@OliverUK Thank you for your thorough testing. Unfortunately, the review of #1545 didn't pick up on the variant issue you reported. We now have randomly failing tests probably depending on the random order of variants in the database:

- `spec/features/consumer/shopping/shopping_spec.rb:217`

I will look into it and see if I can come up with a better solution.

**Comment by mkllnk** [comment]
It turned out that the issue was caused in another part of the code where variant names were collected as one word "WholegrainDijon". The word "Dijon" was not found. I think I fixed it as part of #1609.

Please close this issue if everything is resolved.

**Comment by OliverUK** [comment]
@lin-d-hop do you want this re-tested? Not sure what I'd have to deploy though. Also what I see in Buildkite has changed and none of the builds look familiar now.

**Comment by lin-d-hop** [comment]
Thanks @OliverUK. Since 1069 has been merged I say we leave this. When it gets onto production we can look then and open a new issue for anything further.
Brrraaaaap thanks @mkllnk
