### ISSUE TITLE
[BUU] [Infinite loader] - Remove Stimulus Reflex from Products Page

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#12331]
In some circumstances, the new bulk edit products screen will fail to load products, leaving an infinite loader, and a poor user wondering if anything was still happening.
- Split from #11752 because these issues have different impacts and will be solved separately

**Action Items:**
Remove SR From:
- [x] Product screen loading, filtering and saving (https://github.com/openfoodfoundation/openfoodnetwork/pull/12328)
- [x] Product delete action (https://github.com/openfoodfoundation/openfoodnetwork/issues/12398)
- [ ] #12551

## Steps to reproduce
This was last replicated on fr_prod, at approx 9:30am AEST: https://github.com/openfoodfoundation/openfoodnetwork/issues/11752#issuecomment-2024144334
Sometimes it works fine, but maybe if the server is busier, it doesn't.

![Image](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/e0eeef0a-4ea9-4806-aa28-f7383c6ce740)

**Comment by RachL** [comment]
Reopenning because we need to finish removing SR and then do a prod test.

**Comment by RachL** [comment]
lowering to s2 as this is behind a feature toggle

**Comment by chahmedejaz** [comment]
Updated the Description to include the remaining action items from https://github.com/openfoodfoundation/openfoodnetwork/pull/12328

I'm assigning this to myself to work on the remaining items.

**Comment by dacook** [comment]
Thanks @chahmedejaz. 
For the **Delete** action, @anansilva has already been looking at an overlapping issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/11987

That would include replacing SR with Turbo, which is actually a pretty big task. We could consider breaking it up, but I suspect it will be necessary to work through it one part at a time anyway. Maybe we can discuss that in Slack.
I think it's ok for this but to wait for that to be done. 

For **Edit Image**, it's not actually triggering this issue (it doesn't use SR for reloading the products), so we can  handle that separately. I do think we should create an issue for it, so will go ahead and create that now.

**Comment by chahmedejaz** [comment]
Thanks @dacook for the the heads-up.
I'll discuss with Ana on this before moving any further with this one. :)

**Comment by dacook** [comment]
Thanks for being proactive on this one Ahmed! I've created a separate issue for edit.

**Comment by dacook** [comment]
Groan, we missed one more little use of StimulusReflex, I've added a new issue to the list at the top.

I'm not sure if this is still an `s2` or `BUU1` issue though, I think we can de-prioritise and consider as `tech debt` instead.

In any case, it's probably a quick fix so I won't spend too much time deliberating it. I've not added any labels to the new sub-issue yet.

**Comment by RachL** [comment]
I'm closing this issue: let's keep subissue only. If subissues are a blocker we can raise them as s2, or re-open here if we really have a lot of them and need grouping 👍 .
