### ISSUE TITLE
[Invoices] Bulk printing of invoices not reflecting sort applied in Orders screen

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#12340]
## Description

A user contacted support as they use the Bulk Actions - Print Invoices tool as packing slips for their orders. Since Tuesday 4th April, the user noticed an issue with the generated PDF where sorting applied to Orders was not being reflected in the PDF file. The user usually sorts the Orders page by name alphabetically, then clicks Print Invoices, and the generated PDF is also sorted alphabetically. Since Tuesday, the generated PDF is sorted differently (see Possible Fix below). The user is a hub which had 88 orders over 130 pages in their latest order cycle, so sorting the printed PDF manually is not practical.

## Expected Behavior

Generated PDFs should reflect sorting applied on the Orders screen, in the same way that filters (e.g. order cycle/name) are reflected in the generated PDF.

## Actual Behaviour

Generated PDF is sorted in one way, irrespective of sorting applied on Orders screen. Sorting by date or name does not change the generated PDF.

## Steps to Reproduce

1. User selects enterprise (ID: 202005), order cycle (id: 215923) sorts the Orders screen by clicking a column heading e.g. name column
<img width="800" alt="Screenshot 2024-04-04 at 15 58 22" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/309d828b-c6d1-4867-aab2-bf83601a04fd">
2. User sets view to '100 per page' to include all orders in outputted PDF.
3. User clicks 'select all' checkbox, then bulk actions, print invoices. 
4. Generated PDF is sorted by name alphabetically. 

## Animated Gif/Screenshot

First order in list when sorted alphabetically:
<img width="800" alt="Screenshot 2024-04-04 at 15 58 22" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/309d828b-c6d1-4867-aab2-bf83601a04fd">

First order in generated PDF:
<img width="842" alt="Screenshot 2024-04-04 at 16 20 53" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/a4242195-738c-41d9-9356-dc494118af48">

## Workaround

I've tried adding dummy company name/legal address into enterprise settings, which didn't work.
I've also tested with other enterprises and seen the same issue, as well as using the date range filter vs. the order cycle filter.
I've also tested on new admin and seen the same issue.
Same issue when viewing 15 per page.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

The sorting of orders in the PDF appears to be via the id field within spree_orders. Running this query on UK prod:
`select * from spree_orders where distributor_id=202005 and order_cycle_id=215923 and state='complete' order by id asc`
Returns the orders in the same order they appear in the PDF.
PDF:
<img width="400" alt="Screenshot 2024-04-04 at 16 20 53" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/8b4cd05d-db9c-4cec-9737-3de53abcf4db">
SQL query:
<img width="600" alt="Screenshot 2024-04-04 at 16 48 49" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/632b2bb7-1efd-479a-a11f-f43897b603e0">

**Comment by mkllnk** [comment]
I used Filipe's automated spec and did a `git bisect`. I found 6e9089ad4792c16e0a33f0ec0ab9179c8f659e9e breaking this feature. That was in release https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v4.4.35 deployed two weeks ago, 25 March 2024.
