### ISSUE TITLE
'inherit properties from enterprise' tickbox lost in product edit

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1235]
![image](https://cloud.githubusercontent.com/assets/10843056/20614703/f0919b44-b325-11e6-879d-9914f61b426a.png)

**Comment by myriamboure** [comment]
Just checked on french production and they are here:
![screenshot from 2018-03-20 11-45-17](https://user-images.githubusercontent.com/8135376/37650107-408dedfe-2c34-11e8-81cb-cbf5938d1c5b.png)
Also checked on Aus staging and still here:
![screenshot from 2018-03-20 11-46-38](https://user-images.githubusercontent.com/8135376/37650161-66459268-2c34-11e8-9fe0-581980ae7288.png)
So closing.
