### ISSUE TITLE
Remove unused Discourse SSO integration

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#12355]
### What we should change and why (this is tech debt)
There is some code for linking up with a discourse instance. But it is:
> eight years old. I think it was used with the Fair Food Forum which is now not used anymore. So we can take it out.

See `lib/discourse/single_sign_on.rb` and any other related files, environment variables etc. There are mentions in:
* openfoodnetwork
* ofn-install
* [ofn-install/wiki/Discourse-integration](https://github.com/openfoodfoundation/ofn-install/wiki/Discourse-integration)

### Context
Discussed in [#delivery-circle](https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1712708679583339)

**Comment by isidzukuri** [comment]
@dacook please take a look https://github.com/openfoodfoundation/openfoodnetwork/pull/12496
