### ISSUE TITLE
Shops filter by type/category is seeing deleted products

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1236]
This 'meat and fish' filter suggested that Producer of Vegetable stocked meat and fish. The shop didn't have any meat and fish in the current order cycle. It was seeing a past product which has since been deleted which was meat/fish.
The badges on the profile are correctly reflecting items in the current OC
![image](https://cloud.githubusercontent.com/assets/10843056/20615360/3cd55be2-b32d-11e6-9c66-4dbdae887aca.png)
@RohanM

**Comment by RohanM** [comment]
See `Spree::Taxon.supplied_taxons`. This doesn't filter out deleted products, so we see taxons for them.

**Comment by daniellemoorhead** [comment]
Is this still happening @sstead?

**Comment by sstead** [comment]
No this doesn't seem to be happening anymore.

**Comment by sauloperez** [comment]
should be close the issue then @sstead ?

**Comment by sstead** [comment]
I'm not 100% certain the issue has fixed itself, but yes I'll close it.
