### ISSUE TITLE
Mirror return or line break in shipping / payment method description

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12365]
## Description

When setting up a shipping or payment method description, users are allowed to return to line or add line breaks in the admin side.

However this is not done is the shopfront where everything is only separated with a space. If description are long this can be quite ugly.

## Steps to Reproduce

1. Add shipping method description with line breaks / return
2. Checkout and observe the same description in shopfront

## Animated Gif/Screenshot

Backoffice:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/b5a1c216-83c5-48b8-925f-29fb0ef0a12f)

Shopfront:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/2c6a5026-c3e9-40b3-b551-780bcb2013ca)

## Workaround

Some users are adding pipes or /// to separate their sentences.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.38
* Browser name and version: Firefox and chrome
* Operating System and version (desktop or mobile): both

**Comment by MrBowmanXD** [comment]
Tried using html_safe and raw in the shipping method description (checkout/_details.html.haml: line 98) but it doesn't work so my assumption is that the shipping method description is edited without the line breaks and return. Will delve deep into the code in order to know how the shipping method description is being saved.

**Comment by MrBowmanXD** [comment]
The simple format method resolves the issue. Don't know if it introduces errors or possibility of malicious code  being introduced.
