### ISSUE TITLE
Shop For link showing on producer profile even if no items are stocked in the shop

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1237]
The Shop For links at the bottom of producer profiles should only be active if the shop has the producer's items in their current open order cycle.
Below is an example - no citrus items are in the shop's current OCs, they just have E2Es to allow them to be added to the shop.
![image](https://cloud.githubusercontent.com/assets/10843056/20615395/a720f056-b32d-11e6-8530-45caa09939ca.png)

**Comment by lin-d-hop** [comment]
It's been years since we've cared. #gitcull
