### ISSUE TITLE
Remove "ready for" info from shipping method description area at checkout

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12395]
## Description
**- As a:** shopper
**- On page:** `checkout/details`
**- I want to be able to do:** sometimes, some shipping method are not available very day. It can raise a conflict with the content the shop manager puts in the "ready for" field.
Therefore, we should remove the display of the field in the shipping method description. It shall remain :

- at the top of the checkout pages
- on the dropdown of the shop
- on order confirmation
- on email confirmation

This is the area where we want to remove it:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/a8e0f951-1ad0-4022-bf29-552a655a0844)

## Acceptance Criteria & Tests

1. Set up a "ready for" information (=> delivery details at step 3 of the order cycle)
2. See it shows up in the top right blue corner of the shopfront
3. See it shows up on the top of the checkout process
4. See order confirmation and email confirmation still have the info
5. However, shipping method description in checkout/details does not have the info anymore

**Comment by MrBowmanXD** [comment]
Hello, i commented the code related to the distributor address panel, that makes the desired result but i receive two email confirmations, is it normal?

**Comment by RachL** [comment]
Hi @MrBowmanXD can you open a PR with your change? It might be easier for the team to give you a feedback this way :)

**Comment by MrBowmanXD** [comment]
Have to check again, but a email confirmation with the name inserted on the form and a email confirmation with blank name were sent. Tomorrow will try to reproduce this problem or check if it remains.

**Comment by MrBowmanXD** [comment]
Now i understand the two emails. One is for the buyer the other for the shop owner. With that out of the way we can probably submit the pull request but i don't know if this feature that i commented, will be necessary for the future that's why i commented it and not delete.

**Comment by sigmundpetersen** [comment]
Thank you @MrBowmanXD .
This PR is now ready for code review, let's wait for our devs to review it 👍

**Comment by MrBowmanXD** [comment]
Will change the code in order to remove only the "ready for" section as noted by the reviewer.

**Comment by MrBowmanXD** [comment]
Just made the commit with the changes necessary.

**Comment by MrBowmanXD** [comment]
Indentation issues prevent from commits to pass the checks, will research this issue in order to see how to solve this problem.
