### ISSUE TITLE
[BUU] Can't save changes on staging-AU

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12403]
## Description

Since recently I can't save changes on the /admin/products page with admin_v3 toggle enabled. I get redirected to /unauthorized. Here is the error message from the browser console:

```
GET
https://staging.openfoodnetwork.org.au/unauthorized
[HTTP/2 401  196ms]

	
GET
	
scheme
	https
host
	staging.openfoodnetwork.org.au
filename
	/unauthorized
Address
	65.99.217.140:443
Status
	401
Version
	HTTP/2
Transferred
	18.71 kB (17.08 kB size)
Referrer Policy
	strict-origin-when-cross-origin
Request Priority
	Highest
DNS Resolution
	System

    	
    cache-control
    	no-store
    content-security-policy
    	default-src 'self' https:; font-src 'self' https: data: fonts.gstatic.com; img-src 'self' https: data: *.s3.amazonaws.com; object-src 'none'; frame-ancestors 'none'; script-src 'self' https: 'unsafe-inline' 'unsafe-eval' *.stripe.com openfoodnetwork.innocraft.cloud maps.googleapis.com maps.gstatic.com d2wy8f7a9ursnm.cloudfront.net; style-src 'self' https: 'unsafe-inline' fonts.googleapis.com cdnjs.cloudflare.com; connect-src 'self' https: https://staging.openfoodnetwork.org.au wss://staging.openfoodnetwork.org.au
    content-type
    	text/html; charset=utf-8
    date
    	Fri, 19 Apr 2024 12:25:21 GMT
    expires
    	Fri, 01 Jan 1990 00:00:00 GMT
    link
    	</packs/css/darkswarm-9775c18d.css>; rel=preload; as=style; nopush,</packs/js/application-c989ee9fb1b3acd181cd.js>; rel=preload; as=script; nopush,</assets/darkswarm/all-53e644a1fb5beee24c7d006b08b70d84afa4619ec5d6b05bd2adb983bb019afa.js>; rel=preload; as=script; nopush,</assets/web/all-1da1cc6fe6a50c600a4552a2cc1a45297623e3d517b0e95219ed51cd7f798342.js>; rel=preload; as=script; nopush
    pragma
    	no-cache
    referrer-policy
    	strict-origin-when-cross-origin
    server
    	nginx
    set-cookie
    	XSRF-TOKEN=vgKo2i_98Mic1crBmVtqx7aa99oUqJ6rvHdwlSVNYxy9A_F1-OcfHiD7ibkWEcg6mmWXHlvi7jwrDHi8KBlZ_g; path=/; SameSite=Lax; secure
    strict-transport-security
    	max-age=63072000; includeSubDomains
    x-content-type-options
    	nosniff
    x-content-type-options
    	nosniff
    x-download-options
    	noopen
    X-Firefox-Spdy
    	h2
    x-permitted-cross-domain-policies
    	none
    x-request-id
    	1919917d-eac1-45df-828c-176b95eea085
    x-runtime
    	0.053590
    x-xss-protection
    	1; mode=block
    x-xss-protection
    	1; mode=block
    	
    Accept
    	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-GB,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	_pk_id.3.32b3=3a6411dd196058de.1712920606.; __stripe_mid=e0acd1c5-aef0-4723-9363-d3a3c531883abc99f5; cookies_consent=cookies_consent; XSRF-TOKEN=j7XVOvq5-gr3oPuQlGEY_q1vv21F5m11iB8vw3ipQP-MtIyVLaMV3EuOuOgbK7oDgZDfqQqsHeIfZCfqdf16HQ; _ofn_session_id=bac583c1a8000f393f0caef219f197c4; _pk_ses.3.32b3=1; __stripe_sid=77833aa9-3752-4989-8303-273b4634a6822a82a7
    Host
    	staging.openfoodnetwork.org.au
    Referer
    	https://staging.openfoodnetwork.org.au/admin/products?_page=1&_per_page=15
    Sec-Fetch-Dest
    	document
    Sec-Fetch-Mode
    	navigate
    Sec-Fetch-Site
    	same-origin
    Sec-Fetch-User
    	?1
    TE
    	trailers
    Upgrade-Insecure-Requests
    	1
    User-Agent
    	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
```

## Expected Behavior

Changes should be saved.

## Actual Behaviour

Changes are not changed and I get redirected to /unauthorized.

## Steps to Reproduce

1. Activate the Admin_v3 toggle.
2. Go to /admin/products page.
3. Make some changes.
4. Click 'Save changes'.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/fa4c169b-246a-4c89-9205-171d4ef6e0e5)

## Workaround

Make changes on the product details page.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: current master
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by dacook** [comment]
I just created a new producer user, and experienced the same problem (on master branch):
![Screenshot 2024-04-22 at 4 32 17 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/8f36f179-d61c-43f8-8e56-c3247b2d4e82)


I'm pretty confident this was introduced by https://github.com/openfoodfoundation/openfoodnetwork/pull/12361. We didn't test with a non-admin user, and clearly need to add feature specs for that!

**Comment by dacook** [comment]
"Content missing" is due to this JS error message:
https://app.bugsnag.com/yaycode/open-food-network-js-australia/errors/6626041ebf35c10008e42421
(https://openfoodnetwork.slack.com/archives/G010VN35QU9/p1713767460266119)

I wonder if we can also catch that general error and provide a more helpful response (even if it is only a 🐌 )

**Comment by dacook** [comment]
This issue has been linked to an error in Bugsnag
[**Error** in **/admin/products**](https://app.bugsnag.com/yaycode/open-food-network-js-australia/errors/6626041ebf35c10008e42421?event_id=6626043a00e6f42188430000&i=gh&m=li)
