### ISSUE TITLE
Several missing translations since release v4.4.41

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12429]
## Description

Introduced on [v4.4.41](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1714590425614379).

1)
We're seeing a missing JS translation in production:

`remaining_in_stock: "Only %{quantity} left"`

2)
Edit:

we're also seeing that

`spree.admin.orders.index.selected`

is missing.

3)

`admin.order_cycles.status.open`

## Expected Behavior

Remaining stock in the shopfront should be translated.

## Actual Behaviour

Remaining stock in the shopfront is not translated.

## Steps to Reproduce

This seems to be reproducible for non-default locales, like `en_US.yml`, or `en_AU.yml`; it does not seem to occur for `en.yml`, or `fr.yml`.

1) 

As admin:
1. Visit the Dashboard and the Shop preferences tab: enable the "Display remaining stock in shopfront if low on-hand" 
2. For a given product on the order cycle, set the on hand stock to 2 units.

As a customer:
3. Visit the shopfron set-up in the previous steps
4. Notice the missing translation

2)

As admin:
1. Visit the orders page. Notice the missing translation next to the actions menu.

3)

As admin:
1. Visit the orders page.
2. Create an order
3. Click the dropdown to select an order cycle; notice the missing translation

## Animated Gif/Screenshot

1) 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/bcc640d0-6945-4d45-91fb-ada3a8a54bdf)

2)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/5a29f3bb-a5fe-479c-aa07-1929abab9a6f)

3) 

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/0882ef73-0f96-4ab5-8317-e090a491a262)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.41
* Browser name and version: Firefox 125.0.3
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by RachL** [comment]
As this is shopfront facing, I'm bumping it as s2 :+1:

**Comment by filipefurtad0** [comment]
I've edited the title because initially I was convinced this was related to these Bugsnag errors, happening at least since [6 Apr on CA](https://app.bugsnag.com/yaycode/open-food-network-js-canada/errors/610c674e0f0fba0007e087b5?filters[error.status]=open&filters[event.since]=30d&event_id=6612531000e2853509a80000), [5 Apr on UK](https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/610aa4b4b0545300075f714b?filters[event.since]=30d&filters[error.status]=open&filters[search]=moment&event_id=6610329800e28d31dfcf0000).

These point to moment.js and the locales as well... However, staging the latest versions showed that this bug is occurring only since v4.4.41.

**Comment by sigmundpetersen** [comment]
These keys are untranslated for en_AU and en_US.

Maybe #12392 did something with the language fallback solution?

**Comment by mkllnk** [comment]
I remember now that the JS part of translations loads only the "available locales", not all locales to save on the JS bundle size. So without the source in there, it can't find the fallback translations.

**Comment by mkllnk** [comment]
I confirmed on au-staging that it's fixed through the revert.
