### ISSUE TITLE
Need to make Connected Apps 'Learn More about Discover Regnerative' translatable

### ISSUE THREAD

**Issue by karlafalk** [openfoodfoundation/openfoodnetwork#12426]
## What is the problem we are solving 
Need to make text and link for the section 'Learn More about Discover Regenerative' in Connected Apps translatable.  This text or url doesn't seem to be in Transifex and able to be translated currently.  
<img width="850" alt="Screenshot 2024-05-01 at 6 56 11 AM" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/88801240/5904d409-a791-4baa-bb1b-8b29e0db95b3">

## Success factors = expected outcome 
This text and the linked url is able to be translated in Transifex.

## Useful information for inception
Related to [Waterloo Food Commons (CA) - OFN Changes #12411 ](https://github.com/openfoodfoundation/openfoodnetwork/issues/12411 )

**Comment by mkllnk** [comment]
This is already translatable. The key constains `connected_apps.description_html`.

**Comment by RachL** [comment]
Then I'm closing this issue, feel free to re-open @karlafalk if there is anything that need to change. Btw for these small issues don't hesitate to use the bug template or the user story template, that are less generic than the epic template.
