### ISSUE TITLE
Get Canadian team into Github

### ISSUE THREAD

**Issue by David-OFN-CA** [openfoodfoundation/openfoodnetwork#12436]

**Comment by David-OFN-CA** [comment]
@mkllnk has successfully added Kalra and I to the openfoodfoundation repo and to this project - thank you! 

But we still need to add the following folks to to the openfoodfoundation repo as well: 
- Rebecca (https://github.com/RebeccaOFN) 
- and Anthony (https://github.com/acsikos) 

Once that's done, I can add them to this project and close the issue. 

Alternatively you could just upgrade my status on the repo, and I can take care of adding Anthony and Karla to the repo and the project - either option works for me, just let me know

Cheers all.

**Comment by RachL** [comment]
@David-OFN-CA you are now an admin and I've added Rebecca and Anthony as well; at least they should have received an invite.

**Comment by David-OFN-CA** [comment]
thanks @RachL - appreciate it!

**Comment by David-OFN-CA** [comment]
Hi @RachL - just following up on this, as I've run into one little issue that I've been unable to resolve, and I'm wondering if you have any ideas on what's up?:

- Both @RebeccaOFN and @karlafalk received and accepted their invites to open food foundation repo 
- I've been able to assign @RebeccaOFN to this project, but when I search for Karla, I'm unable to find her - any idea what the issue here might be?

NB: The last person I need to add is Anthony, and I'm just touching base with him to confirm that he received and accepted your invitation - will update when I know more

**Comment by David-OFN-CA** [comment]
@RachL I've been able to assign Anthony to the project as well, but not @karlafalk, for some reason I can't figure out, so can't close the issue

**Comment by mkllnk** [comment]
In the project settings I can see that Karla as write access directly and admin access through the team:

* https://github.com/orgs/openfoodfoundation/projects/16/settings/access

**Comment by RachL** [comment]
I think that just mean she can edit the project, not that she can be assigned to issues. I honestly don't understand github's logic on assignment. I've invited Karla to the issue reporters team, but she needs to accept the invite.

**Comment by sigmundpetersen** [comment]
As long as she is an org member it should be possible to assign her to issues (https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#about-issue-and-pull-request-assignees)

But she wouldn't necessary show in the assignee dropdown.
Did you try to search for her in the assignee box? I don't have access to assign people to the `sib-discovery-components` so I can't check. But it looks like this on `openfoodnetwork `repo issues
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1451633/d4c4023a-d6a6-4639-932e-770181b8fc8d)

**Comment by RachL** [comment]
> Did you try to search for her in the assignee box?

Yes I couldn't find her... maybe she was not a member of the org? @mkllnk what method did you use to add her?

**Comment by mkllnk** [comment]
Okay, Karla wasn't added to any repository yet, only to the organisation and the project. I added the team to the sib-components repository and now you can select her for issues.

**Comment by kirstenalarsen** [comment]
omg it's so confusing!! Thanks everyone for working it out!

**Comment by David-OFN-CA** [comment]
thanks all!
