### ISSUE TITLE
Customisable pop up message for shops

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1244]
A user has requested....

"Just wondering if theres a possibility of adding a pop up or disclaimer that says something about photos can be viewed on a web version / not mobile version?"

This could be useful in a number of difference scenarios. This particular shop already had a novel in their 'shopfront message' so a pop up window could be another place for more pressing messages. In this case, the user didn't think customers would know that they could see product photos by clicking the expando icon in their mobile.

**Comment by lin-d-hop** [comment]
#gitcull2017
Closing as this is a feature, and not clearly specified. Sounds more like mobile UX.
I'm not even sure what to put in the wishlist because the problem and the solution don't seem closely aligned.
@sstead If this is still wanted maybe spec in the wishlist discourse category?
