### ISSUE TITLE
Connected App is connecting twice

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#12471]
:information_source: _Please use project **Discover Regenerative (Macdoch pt 2): 3. Open Source Tech Evolution** to track work on this issue._

## Description

Some people manage to click the button to connect the Discover Regenerative app twice. It then creates two Connected App records and triggers two webhooks which can create two entries in the portal database.

I think that this happens when the server is busy or the connection is slow. The button is turned into a disabled "Loading" button with a delay and that delay can be longer when the server is busy, allowing for multiple clicks.

We should disable the button after clicking straight away.

## Expected Behavior

You can click the button only once.

## Actual Behaviour

You can click the button multiple times. The slower the server responds, the more often you can click it.

## Steps to Reproduce

1. Turn on feature for connected apps.
2. Go to enterprise settings and connected apps.
3. Click on the connect button many times as fast as possible.
4. Check the webhook executions in n8n.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

* Add JS to disable button.
* Replace StimulusReflex with Turbo.

**Comment by kirstenalarsen** [comment]
@mkllnk please connect clockify code to this issue

**Comment by mkllnk** [comment]
Okay, tracking under Discover Regenerative (Macdoch pt 2): 3. Open Source Tech Evolution.
