### ISSUE TITLE
[staging-FR] Can't stage master/PRs

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12485]
## Description

Staging via GH actions is not working, after several attempts (master/PRs):
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/9098187531/job/25007805965

**Comment by sigmundpetersen** [comment]
Same out-of-memory error as in https://github.com/openfoodfoundation/openfoodnetwork/pull/12449#issuecomment-2107035249

Would a restart of the server help?

**Comment by filipefurtad0** [comment]
I'll try that out! I should have rights to restart puma

**Comment by filipefurtad0** [comment]
It's looking good!! :tada: 
Thanks so much for that @sigmundpetersen :gem:
