### ISSUE TITLE
UX Improvements discovered 2016

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1251]

**Comment by sauloperez** [comment]
@sstead I think several of this issues can be picked by newcomers for the Hacktoberfest, right? Let me know which ones are ready or assign them the "Hacktoberfest" label yourself.

**Comment by sstead** [comment]
I've added the below to Hacktoberfest :)
https://github.com/openfoodfoundation/openfoodnetwork/issues/1252
https://github.com/openfoodfoundation/openfoodnetwork/issues/1274
https://github.com/openfoodfoundation/openfoodnetwork/issues/1279
https://github.com/openfoodfoundation/openfoodnetwork/issues/1282
https://github.com/openfoodfoundation/openfoodnetwork/issues/1273
https://github.com/openfoodfoundation/openfoodnetwork/issues/1314
https://github.com/openfoodfoundation/openfoodnetwork/issues/1311
https://github.com/openfoodfoundation/openfoodnetwork/issues/1290

**Comment by sigmundpetersen** [comment]
This epic is just a collection of issues with no further info.
I'm moving the remaining issues out as standalone issues and closing this.
