### ISSUE TITLE
[BUU] Uploading corrupt product images fails silently

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12513]
## Description

Uploading a corrupt image has no visible effect on the UI. This can give the impression that the change was sucessful, when in fact, nothing changes. An error can be seen in the console.

## Expected Behavior

An error message should be displayed to the user. Below, an image from legacy BO, as an example:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/33c3b2fa-4a25-4865-bd1e-96db39ce2294)

## Actual Behaviour

Nothing happens, no visible warning appears to the user (an error in the console can be seen)

## Steps to Reproduce

1. Edit a valid image (for example, on the text editor, delete some lines, and hit save)
2. With `admin_products_3` feature enabled, open the console and try uploading the corrupt file.
3. Notice no error appears to the user. An error is seen in the console.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/a833f161-8a90-4332-893f-19f3275a2a30)

## Workaround

None needed.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

See https://github.com/openfoodfoundation/openfoodnetwork/issues/12513#issuecomment-2132465419

**Comment by MrBowmanXD** [comment]
So the solution is to add an message to the user?

**Comment by filipefurtad0** [comment]
> So the solution is to add a message to the user?

From a user perspective, yes. The user should be warned that updating an image was not successful.

In addition to that, I think the console error should not occur; I might be wrong, but to me it indicates we're not handling this exception gracefully. I'd think a response status of 422 would be appropriate (but again, not sure).

**Comment by dacook** [comment]
Thanks for looking at this. It is related to the last PR (https://github.com/openfoodfoundation/openfoodnetwork/pull/12504) which introduced a Turbo Stream format.

Here we can see that the `turbo_stream` format was added for the success, but not the error or exception cases (sorry):
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/spree/admin/images_controller.rb#L49-L66

So we need to add it there too. I think the ideal solution would be to render the `edit.turbo_stream` view, and update it to include the error message. That way, the dialog would show with the error message.
Alternatively, we can probably just let the `update` view show, which will automatically show the error message in a flash popup.

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

May I work on this issue ?

**Comment by sigmundpetersen** [comment]
Sure thank you @cyrillefr 👍
