### ISSUE TITLE
Update and recalculate fees button not working for payment fees after order adjusted in backoffice

### ISSUE THREAD

**Issue by karlafalk** [openfoodfoundation/openfoodnetwork#12512]
## Description
The order total is not being updated with Payment fees that are % based after adding to an order in the backoffice, even after clicking the 'Update and recalculate fees' button.   

## Expected Behavior
Customer makes and order and choose a payment option with a % fee.  A transaction fee is added to the order. In the backend a product is added to the order, order total changes, 'update and recalcuate fees' button is clicked.  It would be expected that this would result in the transaction fee increasing to reflect the new order total.   

## Actual Behaviour
'Update and recalcuate fees' button is clicked, and the transaction fee is not changed. Thus the order total does not correctly reflect the payment fees that should be attached to the order.  

## Steps to Reproduce
1. Create a payment fee with a % fee.
2. Create a customer order selecting that payment fee.
3. Add a product to that order in the backend.
4. Click the 'Update and recalculate fees' button.
5. Note that the transaction fee doesn't not change to reflect the payment fees that should be charged on the increased order total.

## Animated Gif/Screenshot
<img width="1310" alt="Screenshot 2024-05-22 at 6 19 08 AM" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/88801240/5f8c4a57-4ad2-4895-a671-40e7e4ccb4ea">

https://github.com/openfoodfoundation/openfoodnetwork/assets/88801240/e13aeaaa-8483-41c6-8012-24e3541d4b11

## Workaround
Need to manually add an adjustment to the order to reflect the missing payment fees.  Many hub/shop managers may not notice the issue and thus fees would be getting charged incorrectly.  

## Severity
bug-s3: a feature is broken but there is a workaround

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used: openfoodnetwork.ca
* Browser name and version: Firefox 126.0 (64-bit)
* Operating System and version (desktop or mobile): Mac 13.6.6 (22G630) desktop

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 , @RachL , @sigmundpetersen , (Sorry, I don't know who to ping here :) )

I have reproduced this issue locally. I don't know if anyone else needs to check.
If it is fine, may I work on this issue ?

**Comment by sigmundpetersen** [comment]
Sure, go ahead @cyrillefr 🎉 Thanks
Your pinging was correct btw 🙂
