### ISSUE TITLE
Enterprise manager cannot edit  'about' details  - bounced to user login screen

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#12533]
## Description
As an enterprise manager,  if I try to edit the 'about' details for the enterprise I manage,   and hit 'update',  I am bounced to a user login screen.

This does not happen for the enterprise OWNER,  who is able to edit about details as expected.

## Expected Behavior
Enterprise manager should be able to do everything the owner can do,  except create new managers.  So the enterprise manager should be able to edit the 'about' settings  

## Actual Behaviour
When the manager hits 'update' to save their edits,  they are bounced to the user login screen.  (BUt they are already logged in)

## Steps to Reproduce
Log in as an enterprise manager
Try to update the 'about' content in enterprise settings
Hit 'update'
See that you are bounced to a user login page.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/13171778/769e6022-bfca-419c-9db1-f980e3c25d30

## Workaround
Enterprise owner can edit this content

## Severity
s2

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment
OFN Canada,   but OFN USA has also reported this

* Version used:
Chrome - latest
Windows 11 - desktop

**Comment by dacook** [comment]
Confirmed in my dev environment:
* ✅ super admin: can save any enterprise details
* ✅ owner: can save any enterprise details
* ❌ manager: can view, but can't save any details
* ❌ manager of enterprise with permissions to edit profile: can view, but can't save any details
*  ✅ manager of other enterprise: can't view or edit, unauthorised.

**Comment by mkllnk** [comment]
I did a manual bisect of the last release and found that my pull request broke it:

* #12481

**Comment by mkllnk** [comment]
Looking at the network request, the embedded form in the form contains an authenticity token. The form submission contains both tokens and the second one from the connected apps panel is used. This is probably raising the unauthorized error in Rails because the token doesn't match.

**Comment by karlafalk** [comment]
I had another user report similar issues today, just now in Canada.  I haven't had time to look into it yet, but when she was trying to download the product csv template she kept getting redirected to the login screen (when she was already logged in) and was getting an 'unauthorized' error.
