### ISSUE TITLE
Allow dedicated user to access an anonymized orders endpoint

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12543]
**Funded feature code is #12543 [DFC] Anonymized orders endpoint**

## Context

A research project is starting in France on evolution of prices in short food systems and comparison with prices in supermarket.

Most of FR's big short food chain platforms (the Food Assembly, Cagette, Socleo...) are participating

People carying out this research need to access CoopCircuits's orders data. As Socleo is giving access to their data through their DFC API, researchers are asking CoopCircuits to deliver their data in the same format so that they can work on their research more easily.

## Data

Researchers need for a given period and [a list of product names](https://nextcloud.coopcircuits.fr/index.php/s/dARjZkY3Fg56Mg2):

- enterprise (producers) postal code
- enterprise (distributor) postal code
- variant unit name
- unit type
- units
- price
- quantity sold

Especially, they should not be able to find the producer name / full address through the data we give them.

## Evolution needed on OFN side

- [x] #12544
- [ ] Only enterprise which have agreed to share their data will have their orders data available on this endpoint: we need users to be able to opt-out: https://github.com/openfoodfoundation/openfoodnetwork/issues/12550
- [ ] Allow one special user to access this endpoint (added in first issue)

## Additional info

Regarding the 3rd task Socleo is planning to ask researchers to register on Les Communs and ask for a token each time they want to query a platform, using their email address.
They've followed this process https://www.keycloak.org/docs/latest/securing_apps/#_resource_owner_password_credentials_flow and have already done the client part on Les Communs (which is common to both our platforms if I understood correctly).

the following query database can show an example of the data needed (but with producer names):

> select spree_products.name as product_name, spree_variants.display_name as unit_name, spree_products.variant_unit, spree_variants.unit_value as unit_value,  spree_variants.unit_presentation,
SUM(quantity) as total_quantity, price, enterprise1.name as distributor_name, 
distributors.zipcode as distributor_postcode, enterprise2.name as producer_name, producers.zipcode as producer_postcode 
from spree_line_items
  join spree_orders 
    on spree_line_items.order_id=spree_orders.id
   join spree_variants 
    on variant_id=spree_variants.id
    join spree_products
    on spree_variants.product_id=spree_products.id
 join enterprises as enterprise1
    on spree_orders.distributor_id=enterprise1.id
  join spree_addresses as distributors
    on enterprise1.address_id=distributors.id
  join enterprises as enterprise2   
on spree_products.supplier_id=enterprise2.id
   join spree_addresses as producers
  on enterprise2.address_id=producers.id 
where state='complete'
and spree_orders.completed_at>='2023-12-01'
and spree_orders.completed_at<'2024-01-01'
and LOWER(spree_products.name) IN (SELECT lower(name) from spree_products where lower(name) LIKE '%abricot%' OR
LOWER(spree_products.name) LIKE '%asperge%' OR
LOWER(spree_products.name) LIKE '%aubergine%' OR
LOWER(spree_products.name) LIKE '%banane%' OR
LOWER(spree_products.name) LIKE '%boeuf%' OR
LOWER(spree_products.name) LIKE '%bœuf%' OR
LOWER(spree_products.name) LIKE '%carotte%' 
group by spree_products.name , spree_variants.display_name , spree_variants.unit_value,  spree_variants.unit_presentation,
spree_products.variant_unit, price, enterprise1.name, enterprise2.name, distributors.zipcode, producers.zipcode
order by distributor_name, product_name

## Implementation notes

This is a temporary feature which will probably be removed at the end of the research project. So we can take some shortcuts.

* Create a new controller `engines/dfc_provider`, maybe called `AnonymousOrdersController`.
* We can re-use some of the DFC authentification but instead of looking up a user, we will trust the given email address.
* The email address can be authorized against our feature toggles. For example `Flipper.enable(:inrae, "jo@inrae.org")`. Then we can create a model class to work with Flipper: `InraeUser = Struct.new(:flipper_id)` and pass that on to check if the email is allowed to access this endpoint. This implements point 3 above.
* Enterprises need to be able to opt out as well. I think that we should add a new model for this, `ResearchParticipation`. It belongs to Enterprise and has a simple boolean value `participating`. If the entry is absent, we count that as `true`. So it's an opt out. We need a button somewhere to opt out, triggering `enterprise.research_participation.update(participating: false)`.
* Create `OrderBuilder` similar to https://github.com/mkllnk/openfoodnetwork/blob/b11221a235e419f1438e5c1045044cb1c8330428/engines/dfc_provider/app/services/order_builder.rb.

**Comment by RachL** [comment]
@mkllnk I'm working on the issue for the connected apps page. Instead of a config in ofn-install, would it be easier to create a checkbox/seeting in the super admin "configurations" menu?
I don't know if it's easier, but we could even allow super admin to activate / deactivate the connected apps panel with a checkbox instead of the feature toggle (as features toggles should remain temporary).

**Comment by mkllnk** [comment]
> Instead of a config in ofn-install, would it be easier to create a checkbox/seeting in the super admin "configurations" menu?

Creating checkboxes is not easier to start with but will be easier to maintain in the long term. I reckon that we should add a new super admin menu for this where you can activate each app individually. So the code needs a list of apps.

**Comment by RachL** [comment]
@RaggedStaff I don't think we will do the same than Socleo. See sub issues:
- https://github.com/openfoodfoundation/openfoodnetwork/issues/12544 where we use flipper to add the email that can access
- https://github.com/openfoodfoundation/openfoodnetwork/issues/12550 where we use the connected apps page for producers to opt-out

**Comment by dacook** [comment]
I think the _Implementation Notes_ are out of date, now that we are using the Connected Apps feature.

Regarding opt-in/opt-out: I think the decision was to make it opt-in, but make a one-time migration to enable it for all users as needed. This has the disadvantage that new enterprises will not be opted in. It seems to make the most sense for connected apps.

Hmm but I am wondering about making it opt-out. It is anonymised data after all.
So when the instance manager enables it, it's immediately enabled by default. Then we exclude any enterprises that have opted out. I think that would work, as long as the instance setting is clearly labelled so that instance managers are aware of what they're doing. 

So unless I'm missing anything, I think it's no easier either way, so we should choose what's best for this project (opt-out).

**Comment by RachL** [comment]
> So unless I'm missing anything, I think it's no easier either way, so we should choose what's best for this project (opt-out).

@dacook apologize perhaps I mixed the two words, but it would be best to do **opt-in by default** and let users have the ability to opt-out on the connected apps page. We have emailed enterprise (and can do so for the new ones as well) and only 12 of them wants to opt-out. So it's easier for me to opt them out before giving access to researchers, rather than having to opt-in all the others...

> I think the Implementation Notes are out of date, now that we are using the Connected Apps feature.

It looks (with my limited knowledge) that they are ok, it's only that we are using the connected apps page to give the ability to opt-out?

**Comment by dacook** [comment]
No worries, thanks for confirming Rachel

**Comment by dacook** [comment]
Hi @RachL , I got confused here and misunderstood again 😞. I wish I realised yesterday so that we could discuss it!

So I've formatted my previous comments with numbers  to clarify the options. I implemented option 1, but now I see you wanted option 2! I could re-implement it to option 2, or keep option 1 and use a simple script to enable all enterprises (but this won't enable new enterprises). So I'd like to clarify:

Should new enterprises be enabled when they join? If so, we should use option 2. If not, we can stick with option 1.

**Comment by RachL** [comment]
@dacook let's move on with option 1. If at least all current enterprises can be opted-in, that's already good, and we will handle new enterprises with a different process. Thanks 🙏

**Comment by dacook** [comment]
Thanks for confirming, sorry about that..

**Comment by RachL** [comment]
Closing and I will open new issues if INRAE has some feedback.
