### ISSUE TITLE
[BUU] Errors when creating variants

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12553]
## Description

When creating a variant the user has the option to choose between `On hand` and `On demand`. Currently, even if the user sets the variant to be `On demand`, the UI requires a input on the `On hand` field.

## Expected Behavior

If a variant is set to be `On demand`, then it should not be necessary type a value on the `On hand` field, to save changes.

## Actual Behaviour

Even though a variant is set to be `On demand`, the UI requires an `On hand` value, in order to save changes.

## Steps to Reproduce

1. Enable feature toggle admin_style_v3
2. On the /products page, create a variant; set it to have an On demand value.
3. Hit Save changes.
4. Notice changes are not saved and the On hand field is underlined 

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/7f8b678c-0cfe-49ee-b2fb-2eb7c982fe6a)

## Workaround

Typing a random value on the `On hand` field.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.4.49
* Browser name and version: Firefox 126.0.2
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by dacook** [comment]
Hi @filipefurtad0 , the error in the screenshot for the Price field.
I tried replicating on master, and interestingly got a slightly different problem:

1. Enable feature toggle admin_style_v3
2. On the /products page, choose 'New variant'; set it to have an On demand value. (do not change any other values)
3. Hit Save changes.
4. Notice changes are not saved, the **Unit** field has an error ("can't be blank"), and the **On hand** field has reverted to 0 (not 'on demand').
![Screenshot 2024-06-06 at 9 30 52 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/7bece81a-d9e4-470b-8c2d-bdb1032d285e)

Can you provide any more details how you had the error on the price field?

----
I was aware of this problem with the unit field: the unit field is blank by default (1), but when you open the popout (2), it contains a `1`. It's not until you change that value that the change is registered and saved.

1. ![Screenshot 2024-06-06 at 9 33 48 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/9ac77ce5-901e-4701-9fab-7e6090df0d54)

2. ![Screenshot 2024-06-06 at 9 33 58 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/4f880af0-e799-4983-97ed-5ff2623d2038)

**Comment by dacook** [comment]
So in summary (from what I can see so far), it appears to be three problems with creating new variants:
1. Unit field is out of sync with the popout
2. Price field validation error? (I thought it always defaulted to `0.00`)
3. 'On demand' selection is lost when error on saving new variant

**Comment by RachL** [comment]
I've removed the `good-first-issue` label while we investigate, but FYI that price field error was the one I had in https://github.com/openfoodfoundation/openfoodnetwork/issues/11633 
=> the error appeared on a product I was NOT editing. So perhaps @filipefurtad0 edited a on-hand value, saved and got the price error on another product, hence this issue.
Now how to reproduce this... 💩

**Comment by filipefurtad0** [comment]
I can't reproduce this either now @RachL, sorry. I'm not sure what changed, or whether I just bumped on what you describe @dacook, i.e., in the case that something is left blank, the choice regarding stock is not kept:

> Notice changes are not saved, the Unit field has an error ("can't be blank"), and the On hand field has reverted to 0 (not 'on demand').

Therefore, I agree with your summary:

- Unit field is out of sync with the popout -> indeed. For a 1 kg product, the default value appearing on the dropdown is 0.001, with an empty Display as field:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/a76987c4-2d34-4f91-a60c-6857820a506f)

- Price field validation error? (I thought it always defaulted to 0.00) -> I think price is mandatory, and can never be left blank. I think it is ok to get an error, when left blank.
 
- 'On demand' selection is lost when error on saving new variant -> fully agree, this is reproducible

**Comment by filipefurtad0** [comment]
To avoid confusion, maybe it is best to close this issue, and open two issues for points 1) and 3) above? And also for point 2) as well of course, if you feel this is inconsistent behavior (to have Price as a mandatory field).

Looking at https://github.com/openfoodfoundation/openfoodnetwork/issues/11633 it does seem similar... Although I was not editing a variant, but rather creating a new one. Maybe there is a combination here I'm missing...

**Comment by filipefurtad0** [comment]
Ok, created the two issues (mentioned above). I think we can close here.
