### ISSUE TITLE
[BUU] Remove SR from clear search button

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#12551]
On the new Bulk Edit Products screen (`/admin/products` with [feature toggle](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Feature-toggles) `admin_style_v3`):
We want to remove the StimulusReflex action from the "Clear Search" button that appears when there are no search results.

- See https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/admin/products_v3/_no_products.html.haml#L3
- Also remove now-unused [ProductsReflex](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/reflexes/products_reflex.rb) 

This is the last task which allows us to 
- Close https://github.com/openfoodfoundation/openfoodnetwork/issues/12331

![Screenshot 2024-06-05 at 9 27 29 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/01ba56f4-4532-4f7a-8613-efb2ab7b6fb1)

**Comment by dacook** [comment]
I think it will be pretty easy to change the link to load with the turbo-frame instead.

**Comment by RachL** [comment]
@sigmundpetersen not sure we want to fix this one as a priority after BUU release, that's why I've left it outside of the milestone.

@dacook can this one be a good first issue?

**Comment by dacook** [comment]
Yes, it's a small, clearly defined task, and would be a good intro to our use of Turbo .

**Comment by wandji20** [comment]
Can I take this one?
