### ISSUE TITLE
[BUU] Unit field is out of sync with the popout

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12570]
## Description

Follow-up from #12553.

Unit field is out of sync with the popout and does not allow saving changes, even though there is a default value displayed to the user.

## Expected Behavior

The Unit value field should reflect the actual unit value of a variant; this value should be displayed as the pre-defined value, and it should not need to be changed, to be able to save changes.

## Actual Behaviour

The Unit value field does not reflect the actual unit value of a variant; another value is displayed as the pre-defined value, but saving changes is not possible.

## Steps to Reproduce

1. Choose a product which has a unit of Weight (kg) -> 1.
2. Create a new variant on this product by clicking the + sign.
3. Fill in all fields but do not change the Unit field
4. Check which value is pre-defined on the Unit pop-out - in this case it should be 0.001, which is not correct. Should be 1. Click Save changes
5. Notice you get an error: although 0.001 is pre-filled, this value is not considered by the UI. 

## Animated Gif/Screenshot

When creating a new Weight (1 kg) variant:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/a484ca61-c9a8-4832-b33e-4d2082fa6cc7)

The pre-filled value is 0.001; Clicking Save changes:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/72c22669-0dcf-48fd-8649-3a0f1fe69103)

## Workaround

Explicitly type the value you wish for the Unit field.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.50
* Browser name and version: Firefox 126
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by chahmedejaz** [comment]
**Update:**
- It has been fixed and the draft has been submitted.
- However, I think let's wait for the product clone PR to be merged because these changes might create conflict.
- PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/12565 
- So, I'll publish the PR once the above is merged. Thanks.
