### ISSUE TITLE
Reports Overhaul: Add in missing columns for line items

### ISSUE THREAD

**Issue by rhodri** [openfoodfoundation/openfoodnetwork#1257]
As part of rewriting the initial Orders and Fulfilment > Order Cycle Customer Totals report

Reintroduce the line-item columns (i.e. those that are not just defined for the customer totals rows) that Rob has not included in his prototype, namely:
- Order Hub
- Customer Email
- Customer Phone
- Product Producer
- Line Item Paid?
- Line Item Shipping
- Line Item Delivery?
- Line Item Shipping Address
- Product SKU
- Line Item Order Cycle
- Line Item Payment Method
- Line Item Billing Address

### Technical notes:
1. On the frontend, columns need to be added to the `columnDefs` array in the `gridOptions` found in `/app/assets/javascripts/admin/reports/services/orders_and_fulfillments_report.js.coffee`. This also includes how totals are calculated when rows are grouped.
2. The requisite JSON data needs to be retrieved from the DB and made available in `/app/controllers/spree/admin/reports_controller_decorator.rb#orders_and_fulfillment`
3. This will also involve editing serializers present in `/app/serializers/api/admin/reports/variant_serializer.rb`

**Comment by rhodri** [comment]
This could be an opportune time to ask whether some fields defined on line item should actually be moved into the order. Fields like paid?, shipping, delivery?, order cycle, payment method, billing address  seem to be the same for every item in an order... is there ever a situation where an order contains line items with different billing addresses or order cycles?

**Comment by kirstenalarsen** [comment]
@oeoeaio - any thoughts on the question above?

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-reports-potential-integration/1143
