### ISSUE TITLE
Reports Overhaul: Add in missing totals columns

### ISSUE THREAD

**Issue by rhodri** [openfoodfoundation/openfoodnetwork#1258]
As part of rewriting the initial Orders and Fulfilment > Order Cycle Customer Totals report

Reintroduce the totals columns (i.e. those that are just defined for the customer totals rows) that Rob has not included in his prototype, namely:
- Order Admin + Handling Fees
- Order Shipping Fees
- Order Payment Fees
- Order Total

### Challenges
We are attempting to represent multiple different data structures within the confines of a table with only one header row. This means that certain rows have no meaning for line items (like payment processor fee), and other rows have no meaning for the aggregated customer totals (like product name). So because of the limitations of tables, it looks we will have to supply the above order-level redundantly with each line item and *hide* this information.

### Technical notes
1. On the frontend, columns need to be added to the `columnDefs` array in the `gridOptions` found in `/app/assets/javascripts/admin/reports/services/orders_and_fulfillments_report.js.coffee`.
    - The above also includes how totals are calculated when rows are grouped. You can set a `customTreeAggregationFn` for a column which will be given access to the entire row object, as described in the [UI Grid documentation](http://ui-grid.info/docs/#/api/ui.grid.treeBase.api:ColumnDef#properties_customtreeaggregationfn).
    - If we need to supply order-level data in each line item, we can change how each cell is formatted by using the `cellTemplate` property for a column. There is a relevant example in the [UI Grid Guide](http://ui-grid.info/docs/#/tutorial/320_complex_grouping).
3. The requisite JSON data needs to be retrieved from the DB and made available in `/app/controllers/spree/admin/reports_controller_decorator.rb#orders_and_fulfillment`
4. This will also involve editing serializers present in `/app/serializers/api/admin/reports/variant_serializer.rb`

**Comment by kirstenalarsen** [comment]
@oeoeaio

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-reports-potential-integration/1143
