### ISSUE TITLE
Reports Overhaul: Show and hide columns

### ISSUE THREAD

**Issue by rhodri** [openfoodfoundation/openfoodnetwork#1259]
As part of rewriting the initial Orders and Fulfilment > Order Cycle Customer Totals report

Enable the ability to show and hide columns.

### Technical notes
1. Actually enabling this functionality is easy! Just set `enableGridMenu` to true in the `gridOptions` object in `/app/assets/javascripts/admin/reports/services/orders_and_fulfillments_report.js.coffee`. Here is the section of the [UI Grid guide](http://ui-grid.info/docs/#/tutorial/121_grid_menu).
2. For some reason @oeoeaio doesn't like this UI (is that right?) so customising it can be done by creating our own custom UI and toggling the relevant `visible` attribute in our `columnDefs`. See this [section of the UI Grid](http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns) guide for an example.

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-reports-potential-integration/1143
