### ISSUE TITLE
Reports Overhaul: Add PDF export capability

### ISSUE THREAD

**Issue by rhodri** [openfoodfoundation/openfoodnetwork#1260]
As part of rewriting the initial Orders and Fulfilment > Order Cycle Customer Totals report

Enable the ability to export to PDF.

### Technical notes
1. We will need to include [`pdfmake`](http://pdfmake.org) in the page, and since we don't have a frontend build system to speak of this will either need to be included on all pages, or somehow injected into the `<head>` from the reporting template.
2. Gaining access to the PDF export functionality is easy, it's part of the grid menu! See #1259 for instructions on how to enable this
3. We can customise PDF export format! Have a look at this [section of the UI Grid guide](http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex)

**Comment by rhodri** [comment]
One issue with UI Grid's built-in export functionality is that the totals rows are not exported as part of the CSV – will they be included in the PDF? Can we use the custom export functionality to add these rows in if need be?

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-reports-potential-integration/1143
