### ISSUE TITLE
Reports Overhaul: Investigate sorting behaviour

### ISSUE THREAD

**Issue by rhodri** [openfoodfoundation/openfoodnetwork#1261]
As part of rewriting the initial Orders and Fulfilment > Order Cycle Customer Totals report

Sorting seems a little borked, especially with the grouping schema that we have. UI Grid lets us redefine its internal sorting functionality, as well as hooking in to use our own external sorting code.

Experiment with making case invariant sorting the default, and if that doesn't help, then investigate what kind of arguments are passed to the sorting function to see what is going on. 

### Technical notes
1. UI grid guides on [in-grid sorting](http://ui-grid.info/docs/#/tutorial/102_sorting) and [external sorting](http://ui-grid.info/docs/#/tutorial/307_external_sorting) can be found via those links.

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-reports-potential-integration/1143
