### ISSUE TITLE
Reports Overhaul: Filtering for each column

### ISSUE THREAD

**Issue by rhodri** [openfoodfoundation/openfoodnetwork#1262]
As part of rewriting the initial Orders and Fulfilment > Order Cycle Customer Totals report

Text filtering is provided by default by UI Grid but we also have the option of introducing custom filtering UI and logic.

One obvious issue is that dropdowns would have to be populated manually, they cannot be filled automatically with options extracted from the data by UI grid. So to avoid excessive data duplication we would have to write routines to extract this data ourselves.

### Technical notes
1. Basic guide on adding text filtering can be found in the [UI grid guide](http://ui-grid.info/docs/#/tutorial/103_filtering)
2. Custom filtering is demonstrated [here](http://ui-grid.info/docs/#/tutorial/306_custom_filters)
3. Hooking into the grid and using custom external filtering routines is detailed [here](http://ui-grid.info/docs/#/tutorial/308_external_filtering)

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-reports-potential-integration/1143
