### ISSUE TITLE
[BUU] Activate admin_style_v3 for dev, test and new servers

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#12627]
When the new Backoffice UI Uplift design (`admin_style_v3`) is the primary design, we need ensure we are using it while developing new changes:

* dev environments
* tests (local and CI)
* ~~staging~~ (these can be managed manually for now)
* new servers

**Steps:**

1. Prepare tests
   * [x] https://github.com/openfoodfoundation/openfoodnetwork/pull/11645
   * [x] https://github.com/openfoodfoundation/openfoodnetwork/pull/12649
   * [ ] spec/system/admin/product_import_spec.rb:100:213:679:720 - https://github.com/openfoodfoundation/openfoodnetwork/pull/12668
   * [x] spec/system/admin/products_spec.rb:283 - https://github.com/openfoodfoundation/openfoodnetwork/pull/12652
   * [x] spec/system/admin/subscriptions/smoke_tests_spec.rb:240 - https://github.com/openfoodfoundation/openfoodnetwork/pull/12652
   * Consider improving specs as per [review comments](https://github.com/openfoodfoundation/openfoodnetwork/pull/11645#pullrequestreview-2152471490)
- [ ] Make `admin_style_v3` [active by default](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/feature_toggle.rb)
   - This will enable for dev, test and new servers (any environment that doesn't already have a saved setting for `admin_style_v3`)
   - So we can remove the `Flipper.enable` in `base_spec_helper`

**Comment by dacook** [comment]
Once https://github.com/openfoodfoundation/openfoodnetwork/pull/11645 is complete, we should be able to simply make `admin_style_v3` `ACTIVE_BY_DEFAULT` in `feature_toggle.rb`

**Comment by filipefurtad0** [comment]
As per delivery circle, I've assigned myself to this issue @dacook .

**Comment by dacook** [comment]
https://community.openfoodnetwork.org/t/backoffice-ui-product-list-uplift-rollout/2921/33
>On July 16th we will release the new admin by default to all super admin and make this the default environment for dev and testers.

This won't all be included in the release next Tuesday 16th, but hopefully we will have it merged in master.

**Comment by RachL** [comment]
Yes I was getting a bit too optimistic sorry :)

**Comment by dacook** [comment]
> [ ] Make `admin_style_v3` [active by default](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/feature_toggle.rb)

@filipefurtad0 I tested this out on my dev environment to see how it works.

1. Delete existing feature toggle for `admin_style_v3` (Actually I deleted all just for fun)
   ![Screenshot 2024-07-16 at 10 50 15 am](https://github.com/user-attachments/assets/1b6ed3f7-36aa-4cd1-9e6b-44cd796b23c7)
2. Copy (not move) admin_style_v3 from CURRENT_FEATURES to ACTIVE_BY_DEFAULT in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/feature_toggle.rb
3. Restart server. The feature is present and enabled: ![Screenshot 2024-07-16 at 10 53 25 am](https://github.com/user-attachments/assets/05c682a4-ec07-4a6f-a05b-faea63e409fe)
4. Disabled or partially enable the feature (similar to current prod servers): ![Screenshot 2024-07-16 at 10 54 34 am](https://github.com/user-attachments/assets/d0e66114-31a9-4f48-95b9-71d9ea6b862a)
5. Restart the server. No change was made to the feature toggles.

**Comment by filipefurtad0** [comment]
>  I tested this out on my dev environment to see how it works.

Ok, I see. So, if:
- the feature does not exist, it will create and enable it
- the feature exists, it does nothing

I've staged the current PR to have a quick test on the current behavior, and [added some testing notes](https://github.com/openfoodfoundation/openfoodnetwork/pull/12668#issue-2406192509) on this regard - (it's looking good!)
