### ISSUE TITLE
[BUU] Insert cloned products below the original product

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12623]
## Description

When cloning a product in the product list, the clone is inserted *above* the original product.
It is more intuitive to insert it *below*.

## Expected Behavior

Insert the cloned product below the original.

## Actual Behaviour

The cloned product is inserted above the original.

## Steps to Reproduce

1. Activate the feature toggle 'admin_style_v3'.
2. Go to the page `/admin/products`.
3. Clone a product.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/574486fe-d0b8-4857-ba6d-ca40dd08728c)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by zsoltiNagy** [comment]
I propose a simple solution for this issue: change `new_product.name = "COPY OF #{product.name}"` to `new_product.name = "#{product.name} [CLONE]"` and update all corresponding references in tests and comments. This new naming convention better aligns with the action name (Clone). Additionally, adding a selectable "[CLONED]" search field could further enhance the user experience. If you approve of this approach, I would like to implement it as my first issue on this repo 😊

**Comment by RachL** [comment]
@zsoltiNagy Hello and welcome here! Thank you for your proposal :hugs:  Can you perhaps clarify how this renaming would affect the position of the product in the list?

To give you a bit of context: we have completely rebuilt the product page under the `admin_style_v3 `toggle. As we are releasing this new style to current users, we want them to have the least number of changes in how the UI worked before. Hence, we want to keep the cloning product to appear below the original product - as it does when the toggle is OFF.

I'm afraid we don't want to change the naming convention right now for the same reasons. Maybe in a later stage, but during the release process I don't think it's a good move. 
Don't hesitate if this is not clear and/or you need help finding a new issue!

**Comment by zsoltiNagy** [comment]
Hi @RachL ! :) If we follow this idea, every cloned product should appear immediately after the product it originated from. According to the corresponding table, we currently order the products by name by default. Simply copying the original name and adding a [CLONE] flag to the cloned version would maintain the original order and place the newly cloned product right after its origin.
 have already made a pull request for this change and left a comment regarding the potential need to apply the same change to order cycle cloning: [#12669 ](https://github.com/openfoodfoundation/openfoodnetwork/pull/12669#issuecomment-2227998105)

**Comment by dacook** [comment]
Thanks, this is a logical way to solve the problem broadly, but as Rachel has mentioned, we're not ready to change the name format right now. (although it makes sense and we would like to do that in the future).

The cloned product is actually controlled with a special Turbo Stream action here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/admin/products_v3/clone.turbo_stream.haml#L13
It might be as simple as updating that one line.

**Comment by zsoltiNagy** [comment]
Both of you are totally right :) I haven't seen this file before because I initially made the mistake of branching from origin instead of upstream; the former was forked a couple of months/weeks ago. This is way simpler than I thought! I followed your guide and made a [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/12675).
