### ISSUE TITLE
Voucher code field at checkout only allows one character

### ISSUE THREAD

**Issue by amidaOFN** [openfoodfoundation/openfoodnetwork#12632]
## Description
At checkout when entering a voucher code the user can only type one character at a time. After each character they need to re-click in the space to type another character, and repeat until the code is completely entered. This will no doubt be a nuisance to customers.

## Expected Behavior
Voucher code field should accept the full voucher code without needing to reclick into the field.

## Actual Behaviour
Voucher field requires the user to reclick into the field after each character. 

## Steps to Reproduce
1.  Go to checkout with a cart of items
2.  Attempt to enter a voucher code

## Workaround
Some users can use discounts via enterprise fees however this does not work for all use cases of vouchers

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
Chrome Version 126.0.6478.127 on laptop

**Comment by chahmedejaz** [comment]
The fix is ready for review. Thanks
