### ISSUE TITLE
Reports Overhaul: Generate and share columnDefs across reports

### ISSUE THREAD

**Issue by rhodri** [openfoodfoundation/openfoodnetwork#1263]
Maintaining a list of columnDefs for each report will create an awful lot of code duplication.

Columns will almost certainly be rendered the same across different reports, so let's have the ability to:
- generate a columnDef from a few options: field name, data type, filtering style, etc
- map field name to a generated column def

This would be one step towards allowing dynamic specification of the contents of a report. This can be done either in JS, or server side.

**Comment by kirstenalarsen** [comment]
Hi @rhodri - just having a quick look through these and pinging @oeoeaio on a couple where his input might be useful :)

**Comment by lin-d-hop** [comment]
#gitcull2017
https://github.com/openfoodfoundation/openfoodnetwork/issues/1264
