### ISSUE TITLE
[inventory] Producer column is empty in review page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12642]
## Description

Following https://github.com/openfoodfoundation/openfoodnetwork/pull/12562 inventory review screen is not showing the producer of a variant

## Steps to Reproduce

1. Go to `/admin/inventory`
2. Select a shop and make sure not all of the shop products are already in inventory
3. You should see a banner saying you can add products and you can "review now"
4. See the producer column in empty

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/c1d299f0-355b-4f49-9613-9a6834f48845)

## Workaround

i'm guessing it's verry rare to have 2 producers with the exact same variant name/units/etc but it can happen. So no real workaround (except adding and then hiding), but this is not s2 material

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: master from 3rd July
* Browser name and version: Firefox and chrome
* Operating System and version (desktop or mobile): desktop

## Possible Fix

display variant producers name? If it's the same producer, only display it once.

**Comment by cyrillefr** [comment]
Hello @RachL ,

May I work on this issue ?

**Comment by RachL** [comment]
HI @cyrillefr yes you are very welcome to! Many thanks :)
