### ISSUE TITLE
Reports Overhaul: Add ability to switch between Orders and Fulfillment reports

### ISSUE THREAD

**Issue by rhodri** [openfoodfoundation/openfoodnetwork#1264]
Generalising the overhaul for the Order Cycle Customer Totals report to the other sub-types of the Orders and Fulfillment report.

This will involve:
1. providing JSON endpoints for the other report types – will this just be the same data?
2. providing different columnDefs for each report 
3. increasing sophistication of grouping – it is possible to group by multiple levels in UI grid, as evidenced [in this example](http://ui-grid.info/docs/#/tutorial/320_complex_grouping).
4. an XHR to the server for data, then refreshing the grid with this data and new column defs

**Comment by kirstenalarsen** [comment]
question here about the overarching 'report selector' functionality that we don't want to loose e.g. setting dates, selecting order cycle, choosing hub / proudcer etc. If / when rebuilding would we potentially move some of this to a higher level e.g. choose order cycle at top level and then easily pull up different reports having made that selection once? Would require some more design input, but just putting it out there - @oeoeaio @sstead

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-reports-potential-integration/1143
