### ISSUE TITLE
[BUU] Activate admin_style_v3 for all super admins

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12651]
⚠ Please use clockify code https://github.com/openfoodfoundation/openfoodnetwork/issues/7198 Back Office Uplift (Product) while reviewing or working on this task.

## Description

**- As a:** super admin
**- On page:** all admin pages
**- I want to be able to do:** see the new style as default view

The flipper group "admin" is already there, we just need to activate it by default on `admin_style_v3` feature toggle

## Acceptance Criteria & Tests

1. Before staging he PR check super admins dont' see the new admin by default
2. After staging the PR, check all super admins see it, they can remove the "admin" group but then no super admin can see the new UI unless there are in another group who has access
3. Check this does not affect other users

**Comment by dacook** [comment]
https://community.openfoodnetwork.org/t/backoffice-ui-product-list-uplift-rollout/2921/33
>On July 16th we will release the new admin by default to all super admin and make this the default environment for dev and testers.

I will aim to have this in the next release, deployed next Tues 16th.
