### ISSUE TITLE
[Inventory] Products missing from Inventory

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#12679]
## Description

User raised that certain products were missing from their inventory - they were not showing in Hidden, New or Inventory products. 

## Expected Behavior

If an enterprise is using the inventory, all products should appear in one of: Hidden, New or Inventory lists.

## Actual Behaviour

Not all products are displayed. 

## Steps to Reproduce

1. See product in Products list:
<img width="1293" alt="Screenshot 2024-07-16 at 15 29 46" src="https://github.com/user-attachments/assets/1b9f98b0-2a41-44e1-ae55-5dfc4378cc0b">

2. Go to inventory for Cambridge Food Hub (id: 201177)
3. Search for 'Grapes, White (seeded) - Spain (organic)' (product id: 303049) or 'Apricots, Spain (organic)' (product id:360652)
4. Observe that no matching product is found in either Inventory, Hidden or New 

## Animated Gif/Screenshot

![Missing apricots 1](https://github.com/user-attachments/assets/694b34b3-3146-45f9-813d-68c0aa68e684)

## Workaround

No workaround - customers unable to use inventory fully. 

## Severity

bug-s2 for us, bug-s1 for the user (they are unable to manage their full inventory, which they need to manage products)

## Your Environment

* Version used: Both old UI and new UI
* Browser name and version: UK Prod
* Operating System and version (desktop or mobile):

**Comment by rioug** [comment]
I think that's an issue with how the inventory page is designed. On this page, product are loaded in the background, so if you happen to search for a product that hasn't been loaded yet you won't find it. That can be a problem for shops with lots of products (or a super admin user).  I am fairly confident if the customer were to stay on the inventory page, the product will eventually show up. 

There is also this issue with the ordering and duplicate data : https://github.com/openfoodfoundation/openfoodnetwork/issues/12670 , so it's possible the loading of product is slowed down by the duplicate data, or even the latest product refactor changes. For know I am going to fix #12670 and we'll see if it addresses the issue.

**Comment by BethanOFN** [comment]
@rioug Slow loading was my first thought - however I tried it with one of my other test accounts (not super admin, just a couple of hubs) and left it to load for over an hour and still nothing. I don't think it's related to loading speed

**Comment by rioug** [comment]
That's good to know. Let's see if the product sorting fix the issue first, and I'll revisit this issue if it doesn't

**Comment by rioug** [comment]
@BethanOFN the fix for https://github.com/openfoodfoundation/openfoodnetwork/issues/12670 has been released today, could you check if you are still missing products ?

**Comment by BethanOFN** [comment]
@rioug user has confirmed all back to normal 🎉  thank you!

**Comment by RachL** [comment]
oh yeah!

![ ](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXo1dWxxeWM1bzB0cW80cnc2d3MzZ3gzdTNwdXBmeW42eDBrc2RyMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/wAxlCmeX1ri1y/giphy.gif)

closing 🥳
