### ISSUE TITLE
[BUU] error 500 on admin/products

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12682]
## Description

Noticed on the HU instance for superadmin and on FR for a new user (who subscribe to the platform on the 16th): switching OFF BUU is removing the problem. 

See https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1721196187473149

## Steps to Reproduce

🤷 

## Severity

bug-s2: a non-critical feature is broken, no workaround

**Comment by chahmedejaz** [comment]
That's strange because as per the shared stack trace, it seems to be caused by this line of code:
https://github.com/openfoodfoundation/openfoodnetwork/blob/23fc77351ef5be5f4e7a2115c3081fe7b26dccf5/app/services/weights_and_measures.rb#L28-L29

And for the above to throw the shared error, we have to pass `significant: true`, otherwise it doesn't throw the error 😅 
![image](https://github.com/user-attachments/assets/0f3823c1-90f7-49ba-8ede-a533887bbd8f)

I think it would help if we had some Bugsnag screenshots showing the full stack-tace. Moreover, it might be due to the data issue on staging, which is weirder 😅 .

FYI: It's being reproduced on the https://staging.openfoodnetwork.org.au/ . I remember when I staged my PR on it, it was working fine. Now all of a sudden it's throwing the 500 error. Do we have any Bugsnag loggings for this one? It might help. Thanks.

**Comment by dacook** [comment]
## FR
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1721140244370209
```
ActionView::Template::Error: undefined method `[]' for nil:NilClass
   scales[product_scale.to_f]['system']
                             ^^^^^^^^^^
Location
app/services/weights_and_measures.rb:20 - system
```
## HU
https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1721196187473149
```
F, [2024-07-16 07:23:13 #14433] FATAL -- :
ActionView::Template::Error (undefined method `>' for nil:NilClass
          if options[:significant] && options[:precision] > 0
                                                          ^):
    10: %td.col-unit_scale.field.naked_inputs{ 'data-controller': 'toggle-control', 'data-toggle-control-match-value': 'items' }
    11:   = f.hidden_field :variant_unit
    12:   = f.hidden_field :variant_unit_scale
    13:   = f.select :variant_unit_with_scale,
    14:       options_for_select(WeightsAndMeasures.variant_unit_options, product.variant_unit_with_scale),
    15:       {},
    16:       class: "fullwidth no-input",
app/services/weights_and_measures.rb:28:in `block (2 levels) in variant_unit_options'
app/services/weights_and_measures.rb:26:in `each'
app/services/weights_and_measures.rb:26:in `filter_map'
app/services/weights_and_measures.rb:26:in `block in variant_unit_options'
app/services/weights_and_measures.rb:25:in `each'
app/services/weights_and_measures.rb:25:in `flat_map'
app/services/weights_and_measures.rb:25:in `variant_unit_options'
app/views/admin/products_v3/_product_row.html.haml:13
app/views/admin/products_v3/_product_variant_row.html.haml:7
app/views/admin/products_v3/_product_variant_row.html.haml:1
app/views/admin/products_v3/_table.html.haml:66
app/views/admin/products_v3/_table.html.haml:65:in `each_with_index'
app/views/admin/products_v3/_table.html.haml:65
app/views/admin/products_v3/_table.html.haml:1
app/views/admin/products_v3/_content.html.haml:18
app/views/admin/products_v3/index.html.haml:15
app/controllers/admin/products_v3_controller.rb:13:in `index'
I, [2024-07-16 07:23:13 #14433]  INFO -- : Processing by ErrorsController#internal_server_error as HTML
```

**Comment by dacook** [comment]
Thanks for looking into this Ahmed. I've granted you access to BugSnag, however we don't have it set up for Hungary (yet.. but we should..).

> And for the above to throw the shared error, we have to pass `significant: true`, otherwise it doesn't throw the error 😅

Yes, you're right. It appears to be crashing at [this line](https://github.com/rails/rails/blob/55c4adeb36eff229972eecbb53723c1b80393091/activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb#L16), yet I can't see any reason why `options[:significant]` would be true, because it is not defined anywhere in our case. 
We could try [forcing it to false](https://github.com/openfoodfoundation/openfoodnetwork/pull/12683), but I can't replicate the issue so have no idea if it will help or not.

**Comment by dacook** [comment]
For the **FR** error, I investigated and found it was caused by corrupted data. I was able to fix this and have raised a PR.

**Comment by dacook** [comment]
I have logged in to **hu_prod** and tested with a new user with one single new product, and the error continues.  (If no products, there's no error).
So I securely copied the data from hu_prod to my dev environment (without images). I cannot replicate the error on any products at all, it all works fine!

So it's some weird environment thing? I can't see any issues with the environment:
```
openfoodnetwork@ofn-hungary-1:~/apps/openfoodnetwork/current$ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]

openfoodnetwork@ofn-hungary-1:~/apps/openfoodnetwork/current$ bundle check
The Gemfile's dependencies are satisfied

openfoodnetwork@ofn-hungary-1:~/apps/openfoodnetwork/current$ git status
HEAD detached at v4.5.1
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	typechange: config/database.yml
	typechange: db/default/spree/states.yml
	modified:   db/schema.rb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.env.production
	log/sidekiq.log-20240716
	log/sidekiq.log-20240717
```
I'm not sure how to proceed at this point.

**Comment by chahmedejaz** [comment]
> Thanks for looking into this Ahmed. I've granted you access to BugSnag, however we don't have it set up for Hungary (yet.. but we should..).
> 
> > And for the above to throw the shared error, we have to pass `significant: true`, otherwise it doesn't throw the error 😅
> 
> Yes, you're right. It appears to be crashing at [this line](https://github.com/rails/rails/blob/55c4adeb36eff229972eecbb53723c1b80393091/activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb#L16), yet I can't see any reason why `options[:significant]` would be true, because it is not defined anywhere in our case. We could try [forcing it to false](https://github.com/openfoodfoundation/openfoodnetwork/pull/12683), but I can't replicate the issue so have no idea if it will help or not.

Thanks for the invite, David.
I think it's worth trying this as I believe our supplied options should be prioritized.

**Comment by dacook** [comment]
Error tracked in BugSnag here: https://app.bugsnag.com/yaycode/openfoodnetwork-hungary/errors/669dbcd95c37ca2809b396cf

**Comment by dacook** [comment]
Not fixed 😞 

![Screenshot 2024-07-23 at 12 23 26 pm](https://github.com/user-attachments/assets/611c4678-0ebe-40e9-b182-a7ff546d3cde)

**Comment by rioug** [comment]
I'll have another look, I am wondering if it's an active support bug related to locale

**Comment by rioug** [comment]
Same error, but different file. The fix we released worked but it uncovered another bug ...
I managed to reproduce the error locally, it's indeed a locale issue :
```
irb(main):001> I18n.locale
=> :en_AU
irb(main):003> ActiveSupport::NumberHelper.number_to_rounded(0.001, precision: nil)
=> "0.001"
```
With `:hu` locale : 
```
irb(main):001> ActiveSupport::NumberHelper.number_to_rounded(0.001, precision: nil)
/home/gaetan/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-7.0.8/lib/active_support/number_helper/rounding_helper.rb:38:in `absolute_precision': undefined method `>' for nil:NilClass (NoMethodError)

          if options[:significant] && options[:precision] > 0
                                                          ^
irb(main):002> I18n.locale
=> :hu
```
I'll apply the same fix for the new bug.

**Comment by rioug** [comment]
I thought this possibly was an ActiveSupport bug, but I can't quite reproduce it outside of our set up :confused: , anyway we have a work around so I won't spend more time looking into this.

**Comment by dacook** [comment]
That's great, thanks so much!
