### ISSUE TITLE
Image upload error

### ISSUE THREAD

**Issue by pragai** [openfoodfoundation/openfoodnetwork#12685]
## Description
It happened while I uploaded a new product image. It happens occasionally. Not sure if S3 related, because we have other issues with showing product images as well.

I, [2024-07-18 14:04:49 #26011]  INFO -- : Completed 500 Internal Server Error in 84ms (ActiveRecord: 14.2ms | Allocations: 20090)
F, [2024-07-18 14:04:49 #26011] FATAL -- :
ActionView::Template::Error (uninitialized constant Spree::Image::MiniMagick
    rescue ActiveStorage::Error, MiniMagick::Error, ActionView::Template::Error => e
                                 ^^^^^^^^^^
Did you mean?  MiniMime):
    30:         %td.no-border
    31:           %span.handle
    32:         %td
    33:           = link_to image_tag(image.url(:mini)), image.url(:product)
    34:         %td= options_text_for(image)
    35:         %td= image.alt
    36:         %td.actions
app/models/spree/image.rb:36:in `rescue in url'
app/models/spree/image.rb:32:in `url'
app/views/spree/admin/images/index.html.haml:33
[4:07](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1721311675051649)

## Expected Behavior
Upload image w/o 500 error.

## Actual Behaviour
Image upload 

## Steps to Reproduce
-
- 
- 
1. go to products list
2.edit a product
3.upload image.

## Workaround
When the same image is uploaded it succeeds second time.,

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version: Firefox 128

* Operating System and version (desktop or mobile):
Ubuntu

## Possible Fix
Maybe issues with S3 connection handling?

**Comment by filipefurtad0** [comment]
Hey @pragai ,

Do you know if this error occurs on the new products UI? Or did you rather observe it on the old products screen?

This could be helpful in narrowing down the error. Thanks for your help!

**Comment by sigmundpetersen** [comment]
@mkllnk I guess this one is also closed by #12754 ?
