### ISSUE TITLE
[BUU] ActionView::Template::Error in admin/products_v3#index

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#12705]
## Error in OpenFoodNetwork Aus

**ActionView::Template::Error** in **admin/products_v3#index**
undefined method `/' for nil:NilClass

      scaled_unit_value = variant.unit_value / (variant.product.variant_unit_scale || 1)
                                             ^

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/669f38efa03983296406328b?event_id=66a07ff900efd698a1b20000&i=gh&m=ci)

## Stacktrace

    app/helpers/admin/products_helper.rb:21 - unit_value_with_description
    app/views/admin/products_v3/_variant_row.html.haml:20 - _app_views_admin_products_v___variant_row_html_haml__1827959112950086768_9292720
    app/views/admin/products_v3/_product_variant_row.html.haml:12 - block (3 levels) in _app_views_admin_products_v___product_variant_row_html_haml___4491341818290561796_9292540
    app/views/admin/products_v3/_product_variant_row.html.haml:10 - block (2 levels) in _app_views_admin_products_v___product_variant_row_html_haml___4491341818290561796_9292540
    app/views/admin/products_v3/_product_variant_row.html.haml:9 - each_with_index
    app/views/admin/products_v3/_product_variant_row.html.haml:9 - block in _app_views_admin_products_v___product_variant_row_html_haml___4491341818290561796_9292540
    app/views/admin/products_v3/_product_variant_row.html.haml:1 - _app_views_admin_products_v___product_variant_row_html_haml___4491341818290561796_9292540
    app/views/admin/products_v3/_table.html.haml:66 - block (2 levels) in _app_views_admin_products_v___table_html_haml___4011096604980307158_9291660
    app/views/admin/products_v3/_table.html.haml:65 - each_with_index
    app/views/admin/products_v3/_table.html.haml:65 - block in _app_views_admin_products_v___table_html_haml___4011096604980307158_9291660
    app/views/admin/products_v3/_table.html.haml:1 - _app_views_admin_products_v___table_html_haml___4011096604980307158_9291660
    app/views/admin/products_v3/_content.html.haml:18 - _app_views_admin_products_v___content_html_haml__4235413950232638027_9291280
    app/views/admin/products_v3/index.html.haml:15 - _app_views_admin_products_v__index_html_haml__3030162839370015489_9291040
    app/controllers/admin/products_v3_controller.rb:13 - index

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/669f38efa03983296406328b?event_id=66a07ff900efd698a1b20000&i=gh&m=ci)

*Created by Admin OFF via Bugsnag*

This helper assumes `variant.unit_value` is not nil, but there is nothing enforcing this rule if the `variant_unit` is items. The BUU product screen will populate `unit_value` with 1, so it shouldn't be an issue for new product, but it breaks for older product.
https://github.com/openfoodfoundation/openfoodnetwork/blob/dfea0cd805c555b84dce163f9ed83842a5b5b992/app/helpers/admin/products_helper.rb#L20-L28

## Workaround
Disable "admin_style_v3"  for the affected user 

## Technical workaround
Update variant where `unit_value: nil` and set it to 1 for the affected user.

## Severity#

bug-s3: a feature is broken but there is a workaround

**Comment by chahmedejaz** [comment]
Did a spike on this, previously it was:
https://github.com/openfoodfoundation/openfoodnetwork/blame/6d6f8735e3eff94f53a142538e158116331175cd/app/views/admin/products_v3/_variant_row.html.haml#L22

It had the default value of 1 in the calculation. I'm not sure how I missed it in the refactor 😕 

Fixing it now.
