### ISSUE TITLE
Problem with brave browser

### ISSUE THREAD

**Issue by ligi** [openfoodfoundation/openfoodnetwork#12706]
I am having problems opening this site in the [Brave browser](https://brave.com/) - it looks like this:

![image](https://github.com/user-attachments/assets/e4bfb826-3356-4185-984f-953e7ad0268e)

it works fine with FireFox. 
the initial cookie dialog is not shown (also tried in private mode) - and so could not use the site as everything is "greyed" out.
For now I can use the "workaround" to use FF - but other users might drop off after the initial "dam -  this site is not working" and are not so hungry to try with other browsers.
Maybe these error messages help get to the bottom of the problem:
![image](https://github.com/user-attachments/assets/a46d74a9-beac-4d5f-bcf3-4ab5be895f43)

**Comment by RachL** [comment]
@konrad as detailed [here](https://github.com/openfoodfoundation/wishlist/issues/1), you can deactivate the cookie banner, which would avoid this problem.

**Comment by drummer83** [comment]
Hi @ligi, can you try again?

**Comment by ligi** [comment]
yes - works now - thanks!
