### ISSUE TITLE
[BUU] review performance

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#12718]

**Comment by dacook** [comment]
Tests for first page of 15 products for super admin: https://staging.openfoodnetwork.org.au/admin/products

### 0. old angular screen (products_old)
This also uses tomselect

HTTP response: 1s, 40.9kb, 29 kb
HTTP response 2 (json): 532ms, 262b
![Screenshot 2024-07-31 at 1 49 32 pm](https://github.com/user-attachments/assets/cde7924b-35f5-4171-bbd7-71707cc5cd7d)

### 1. current (master)
HTTP response: 3.03s, 45.3kb
![Screenshot 2024-07-31 at 1 37 26 pm](https://github.com/user-attachments/assets/d43674fe-abb2-44c6-b5a0-2ab51bbc11a2)

### 2. no tom-select for variant producers or categories
HTTP response: 3.02s, 40.9kb
![Screenshot 2024-07-31 at 1 43 48 pm](https://github.com/user-attachments/assets/b5597924-08f0-4743-ab31-7d1cd40a728b) ![Screenshot 2024-07-31 at 1 55 11 pm](https://github.com/user-attachments/assets/6ff486ba-40ff-4d9c-9a27-b7fd2604efae)
Caveat: the producer filter was still a tomselect drdopdown.

While watching it load, it appears to pause when loading each producer dropdown. hmm let's try without loading them

### 3. no producers
HTTP response: 846ms, 14.3kb
![Screenshot 2024-07-31 at 1 58 12 pm](https://github.com/user-attachments/assets/a4538591-ce61-4b99-894f-5de96c88072c)

Wow, ok so loading producers makes a big difference, even native dropdowns?! (

(Also, an unrelated note, but it takes a few minutes for Chrome to process the performance profile on my machine, which I thought was pretty beefy!)

**Comment by dacook** [comment]
I used a super admin because it provides the largest data set to test with. 

But this may not be very relevant for an enterprise user, who only has a few producers anyway. Hmm, need to test an enterprise user too.

**Comment by rioug** [comment]
Nice ! sounds like some caching around producer could help ?

**Comment by dacook** [comment]
I had a  go at analysing real-world data after the BUU rollout started, but couldn't [find any conclusive data yet](https://openfoodnetwork.slack.com/archives/C014V9TCWH5/p1722905191667689).

As discussed in [#delivery-circle](https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1722512504029619?thread_ts=1722402447.906469&cid=C01T75H6G0Z), there are many hubs that have over 20 producers (some as many as 150). I've not verified the impact of these, but I think it won't hurt to try and optimise this.
