### ISSUE TITLE
[Checkout] Change colour of 'complete order' button to match rest of the UI

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#12716]
## Description

We have reports of users globally who arrive to collect orders or are awaiting deliveries of orders they haven't actually placed. Investigations have shown that each time this happens, the user has arrived at the 'checkout' screen, but has failed to click the button to complete their order. Transifex changes have been made to the text as some users indicated the 'complete order' text suggested their order was already completed, however another sticking point is likely that the colour of the 'complete order' button is green. From a UX perspective, green is associated with 'completed' or 'done' and is indeed used on completed stages of the checkout process:
<img width="1179" alt="Screenshot 2024-07-30 at 10 31 56" src="https://github.com/user-attachments/assets/234e4326-edcc-454c-b155-7260a601ef79">
This conflict between all other actionable buttons on the platform using OFN orange/#F26F52, together with the association of green=done (reinforced by previous completed stages of the checkout marked in green) is therefore likely contributing to incomplete checkouts.

## Expected Behavior

Actionable buttons/the complete order button should be visually consistent with others across the platform, i.e. using #F26F52

## Actual Behaviour

The complete order button is shown in 'completed green'/#0B8C61 

## Possible Fix

Amend colour of button to OFN orange/#F26F52 in line with rest of the UI and other 'incomplete' elements

<img width="1198" alt="Screenshot 2024-07-30 at 10 36 55" src="https://github.com/user-attachments/assets/fb5e43ba-0f00-405c-b23f-6424aba41159">

**Comment by chahmedejaz** [comment]
Hi @jeevikasirwani - Thanks for your interest in this issue, and sorry for the delay. 
Anyhow, I believe the reported issue is caused by these lines:
https://github.com/openfoodfoundation/openfoodnetwork/blob/8716b75d3d8570be5506cb43bfec3ac1208de365/app/webpacker/css/darkswarm/split-checkout.scss#L343-L356

Please let us know if you would like to work on this one or face any issue. Thanks.
