### ISSUE TITLE
[BUU] Show per page not working after searching

### ISSUE THREAD

**Issue by rioug** [openfoodfoundation/openfoodnetwork#12712]
## Description

On the bulk edit page, after searching for something changing the the "Show x per page" dropdown doesn't work. The product list reload but the new filter is not applied.  

## Expected Behavior

After performing a search, when selecting "50 per page" it should show 50 products on the page.

## Actual Behaviour

After performing a search, when selecting "50 per page" it shows the default 15 products on the page.

## Steps to Reproduce

As an admin in the backoffice:
1. Open Bulk edit page
2. Enter a search term, make sure you have more than 50 results
3. Select Show 50 per page, products will load again but it will still show 15 products per page

## Animated Gif/Screenshot

After a search :
![Screenshot Capture - 2024-07-29 - 10-32-49](https://github.com/user-attachments/assets/3b1c5cae-01df-4036-9b20-e2b843942550)

After selecting 100 per page
![after_filter](https://github.com/user-attachments/assets/d24a3099-670a-48f7-a891-ad1e93cc1549)

## Workaround

Refreshing the page (via refresh button or ctrl + R) should reload the page the correct filter applied 
## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.5.2
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Linux desktop

**Comment by chahmedejaz** [comment]
Hi @rioug - I believe this has been fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/12678. Can you please validate this in the latest master? Thanks

**Comment by rioug** [comment]
Thanks @chahmedejaz , I just had another look on master and as far as I can tell this is now fixed. Closing
