### ISSUE TITLE
'Connect' and 'Learn' links in banner can't show hover colour on mobile

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1272]
It's difficult to tell that they're links going to different parts of the site ^ this can be fixed as part of the 'Register Now' issue - https://github.com/openfoodfoundation/openfoodnetwork/issues/1271
Devices: Mobile/Tablet
Where: Page Banner
![image](https://cloud.githubusercontent.com/assets/10843056/20949308/c5508b16-bc6c-11e6-8e54-0623b1e959bd.png)

**Comment by lin-d-hop** [comment]
Not in the mobile epic so assuming this has been superseded in new designs
