### ISSUE TITLE
NoMethodError in Admin::ProductsV3#index - Only when using the hu.yml locale

### ISSUE THREAD

**Issue by zsoltiNagy** [openfoodfoundation/openfoodnetwork#12739]
## Description
When using the hu.yml locale and the admin_style_v3 is fully enabled the Products page (admin/products) throws the following error:
`<pre style="font-size: 11px; white-space: pre-wrap; color: rgb(236, 236, 236); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 34, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code>undefined method `&gt;' for nil:NilClass

          if options[:significant] &amp;&amp; options[:precision] &gt; 0
                                                          ^</code></pre><div class="source " id="frame-source-0-11" style="border: 1px solid rgb(85, 85, 85); background: rgb(51, 51, 51); max-width: 978px; color: rgb(236, 236, 236); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#22</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background: rgb(68, 68, 68);">
20 21 22 23 24 25 | def unit_value_with_description(variant)       scaled_unit_value = variant.unit_value / (variant.product.variant_unit_scale \|\| 1)       precised_unit_value = number_with_precision(         scaled_unit_value,         precision: nil,         strip_insignificant_zeros: true
-- | --

</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(236, 236, 236); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 34, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Trace of template inclusion: #&lt;ActionView::Template app/views/admin/products_v3/_product_variant_row.html.haml locals=["category_options", "form", "producer_options", "product", "product_index", "tax_category_options"]&gt;, #&lt;ActionView::Template app/views/admin/products_v3/_table.html.haml locals=["category_options", "producer_options", "products", "tax_category_options"]&gt;, #&lt;ActionView::Template app/views/admin/products_v3/_content.html.haml locals=["category_id", "category_options", "flashes", "pagy", "producer_id", "producer_options", "products", "search_term", "tax_category_options"]&gt;, #&lt;ActionView::Template app/views/admin/products_v3/index.html.haml locals=["categories", "flash", "producers", "tax_category_options"]&gt;</p><br class="Apple-interchange-newline">`

If I switch the language to es or en_AU the same page works flawlessly. The same behavior can be reproduced on locale and also the live site with the mentioned configuration. 

## Expected Behavior
The app should render the page as with other locales.

## Actual Behaviour
See description.

## Steps to Reproduce
1. Add the hu language to the AVAILABLE_LOCALES in .env
2. Make sure v3_admin_style is enabled (/admin/feature-toggle/features)
3. Login, go to administration/products
4. Use rake tmp:cache:clear when making changes to the translation files.

## Animated Gif/Screenshot
<img width="2560" alt="Screenshot 2024-08-06 at 22 33 14" src="https://github.com/user-attachments/assets/3df28ce3-e574-4355-951d-b936bd5445b9">

## Workaround
The app works as intended if we switch off v3_admin_style for every user.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
Both locale and production.

* Version used: [v4.5.4 Orange roll](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v4.5.4)

## Possible Fix
Probably a configuration issue.

**Comment by chahmedejaz** [comment]
Hi @zsoltiNagy - Can you please try it in the latest master? I remember this has been fixed and your code seems to be missing it. (_Seems like it from code in the attached error screenshot_). Thanks

**Comment by zsoltiNagy** [comment]
@chahmedejaz Right, I pulled the latest master and retested. The underlying code changed, though the issue seems to be the same. Is the related fix released yet? If so, than I think this is a different issue, since the same behaviour is reproducible on our current production as well. Its using [v4.5.4 Orange roll](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v4.5.4).

**Comment by chahmedejaz** [comment]
Let me take a look, I thought it should have been fixed. Thanks for bringing it to light.

**Comment by chahmedejaz** [comment]
Did a spike on this @zsoltiNagy, the error shown above is fixed in the latest master. However, the [fix](https://github.com/openfoodfoundation/openfoodnetwork/pull/12700) needs to be implemented for all the other places having similar issues as well.
I'm working on implementing it, thanks.

**Comment by zsoltiNagy** [comment]
Thank you for this fix @chahmedejaz ! This was a real headache for our team, now it works as intended:
<img width="1278" alt="Screenshot 2024-08-09 at 14 47 15" src="https://github.com/user-attachments/assets/9626c200-4828-4056-bf69-25cefc8b645c">
