### ISSUE TITLE
'Close' button on banner doesn't persist (page refresh reloads banner)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1273]
Recommendation: Close should persist for session
Device: All
Page banner:
![image](https://cloud.githubusercontent.com/assets/10843056/20949433/604c5320-bc6d-11e6-9088-bea20597687c.png)

**Comment by pmackay** [comment]
How long should this persist for? It would need some kind of cookie setting I guess.

**Comment by sstead** [comment]
On the Aus instance the banner has different content, but the issue still remains in that it will reappear after being closed and after a page refresh. Other instances have the same grey /register banner which also still has this issue.

**Comment by RachL** [comment]
I'm closing this as letting the banner re-appear is actually wanted in some cases. If we want to tackle this we will need another type of issue with more detail / spec work.
