### ISSUE TITLE
[Admin] UX improvements for creation of new products

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12744]
## Description

While testing #12671 several minor issues were found. They are collected here to be addressed in one or more separate PRs.

## Expected Behavior

See table below.

## Actual Behaviour

By 'error' in below table we mean that the field is left blank or filled with invalid content when clicking 'Create'.

| Field | Expected | Actual |
| - | - | - |
| Supplier | Red color of field's label 'Supplier' on error | No red color of field's label on error :x: |
| Unit size | Red border on error | No red border on error :x: |
| Unit name (if variant unit == item) | Unit name is kept after error messages | Unit name is not kept after error messages :x: |
| Unit name (if variant unit == item) | Red color of label, border and 'can't be blank' text on error | No red highlighting at all on error :x: |
| Value (if variant unit != item) | Red border on error | No red border on error :x: |
| Product category | Red border on error | No red border on error :x: |
| Shipping category | Selection is kept after error message | Selection is not kept after error message :x: |
| Image | Uploaded image is kept on error (see #9297) | Uploaded image is not kept on error :x: |

## Further ideas for improvement
  - Use same 'can't be blank' string for supplier and product category as for e.g. product name.
  - Unify the three different types of drop down menus:
    - Modern design wth pre-filled 'Select a supplier'
    - Modern design without pre-filled information (completely empty)
    - Legacy design (smaller line heights, no highlighting on hover)

## Steps to Reproduce

1. As enterprise user visit /admin/products/new.
2. Fill in invalid data or leave required fields empty according to the table above.

## Animated Gif/Screenshot

Here is an example, not showing all of the mentioned above:
![image](https://github.com/user-attachments/assets/d6ae8b5d-e921-420c-b1f4-b6451002e85d)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by wandji20** [comment]
I have an open [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/12749) for this one

Note
The last point (Keeping uploaded in image on error) was not handled :disappointed:
