### ISSUE TITLE
Increase the padding between the logo and Open Source content - will make the link click targets easier to hit on mobile

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1275]
Where: Footer
Device: Mobile/Tablet
![image](https://cloud.githubusercontent.com/assets/10843056/20949611/5aca0c48-bc6e-11e6-8627-b008db9039b6.png)

**Comment by erose357** [comment]
Hi! @Aram-Anderson and I are new contributors were hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by daniellemoorhead** [comment]
Hi @erose357 and @Aram-Anderson, welcome to the Open Food Network! Great to have you both onboard and contributing 🎉
