### ISSUE TITLE
Remove bugherd from australian staging servers

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1276]
Why is this happening? Why is bugherd still on staging? Can't we just remove bugherd?
Device: Mobile/tablet
Where: Feedback
![image](https://cloud.githubusercontent.com/assets/10843056/20949682/dba7f334-bc6e-11e6-9c70-56af7f19adbe.png)

**Comment by daniellemoorhead** [comment]
@maikel any chance you could remove bugherd from our australian staging servers? Worried that people will notice/use/comment on the feedback link when they're testing standing orders.

**Comment by mkllnk** [comment]
@sstead: You can remove Bugherd by removing the Bugherd API key as admin.

admin -> Configuration: Remove "Bugherd Api Key" and click "Update".

I just did that on staging2. To make it permanent, the thing that is in staging2 has to be pushed to production. Staging1 doesn't have a Bugherd Api Key at the moment.
