### ISSUE TITLE
Bulk Coop supplier report broken

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#12768]
The Bulk Coop supplier report wasn't updated when we moved supplier to the variant, most likely because there is no specs covering it.

## Error in Coopcircuits

**ActionView::Template::Error** in **ReportJob@default**
undefined method `supplier' for #<Spree::Product id: 71028, name: "1) Panier de la semaine", description: "<div>Panier composé avec les légumes de saison, 5 ...", deleted_at: nil, meta_keywords: "panier de légumes ; lannion; légumes bio", tax_category_id: nil, shipping_category_id: nil, created_at: "2024-05-02 10:42:25.150969000 +0200", updated_at: "2024-05-02 16:04:34.067208000 +0200", group_buy: nil, group_buy_unit_size: nil, variant_unit: "items", variant_unit_scale: nil, variant_unit_name: "panier de légumes", notes: "", primary_taxon_id: nil, inherits_properties: true, sku: "">
Did you mean?  supplier_id

[View on Bugsnag](https://app.bugsnag.com/open-food-france/coopcircuits/errors/66bb00fe9bebc34ea382134e?event_id=66bb010200f67f6527650000&i=gh&m=ci)

## Stacktrace

    lib/reporting/reports/bulk_coop/supplier_report.rb:48 - variant_product_supplier_name
    lib/reporting/report_row_builder.rb:22 - block in build_row
    lib/reporting/report_row_builder.rb:20 - transform_values
    lib/reporting/report_row_builder.rb:20 - build_row
    lib/reporting/report_rows_builder.rb:44 - block in computed_data
    lib/reporting/report_rows_builder.rb:43 - map
    lib/reporting/report_rows_builder.rb:43 - computed_data
    lib/reporting/report_rows_builder.rb:15 - grouped_data
    lib/reporting/report_template.rb:12 - grouped_data
    app/views/admin/reports/_table.html.haml:9 - _app_views_admin_reports__table_html_haml__821384436403953597_140680
    lib/reporting/report_renderer.rb:56 - to_html
    lib/reporting/report_renderer.rb:52 - public_send
    lib/reporting/report_renderer.rb:52 - render_as
    lib/reporting/report_template.rb:8 - render_as
    app/jobs/report_job.rb:16 - perform

[View full stacktrace](https://app.bugsnag.com/open-food-france/coopcircuits/errors/66bb00fe9bebc34ea382134e?event_id=66bb010200f67f6527650000&i=gh&m=ci)

*Created by Coopcircuits Admin via Bugsnag*

**Comment by filipefurtad0** [comment]
> most likely because there is no specs covering it.

...indeed this was the case, see #12785.
