### ISSUE TITLE
Display Unit As field is not displaying on invoice

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#12777]
## Description

Users often have variants sold in different units -  like  by the 'bunch'  and by the 'bucket'.  Before the product refactor,  users would list the most typical unit name (ie - 'bunch') and then use the 'display as' feature to employ a different display unit name -  like 'bucket'.  
Now with product refactoring,   this 'display unit as'  field still exists,  and it shows correctly in the shop,  and on the customer's order, and in reports.  However,  'display unit as'  content is not displaying on the invoice.  The invoice shows the 'variant unit name' assigned to that grouping of products.

## Expected Behavior
If a user is able to enter conent into a 'display unit as' field on their edit product page,  and if shoppers can order this product based on this info,  then the 'display as' content should appear on the invoice.

## Actual Behaviour
Info entered in the 'display as' area for a variant does not display on the invoice. 

## Steps to Reproduce

1. edit a product and add info into the 'display unit as' field that is different from the 'unit scale' 
2. place that product in a shop and order the product
3. see that the info entered in the 'display unit as' field is correctly displayed on the order.  It is also correctly displayed in the order cycle reports and in the packing reports
4.see that the 'display unit as' field information is not correctly displayed on the invoice.  Instead,  the invoice has the 'unit scale' information displayed (but the price is correct)

## Animated Gif/Screenshot
Example is 'Cosmos - Afternoon White' -  see the display unit as field is entered to be '1 bucket'
![display unit as field entered with 'bucket'](https://github.com/user-attachments/assets/43d63aae-d9f7-4ec0-8544-308fb4d2caff)

Item appears correct on the order:
![display as info correctly displayed on the order](https://github.com/user-attachments/assets/274ceb0e-f435-4c03-822b-c6701a176466)

Item is also correct on the order cycle reports,  and the packing reports

Item is incorrect on the invoice
![invoice-R422104140 pdf (2) Copy conv 1](https://github.com/user-attachments/assets/ab3a6649-7db3-4b66-b52d-73d58953dcf9)

## Workaround
variant would need to be re-entered as a new product,  with a different unit name/scale,   removed from the order,  and re-entered in the back office.   Its fine for new products,  but for exising products, this isn't a viable workaround

## Severity
s2?

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix
I think this may be a product refactor bug

**Comment by drummer83** [comment]
Thank you for this one! 🙏🏻 
I've just had this being reported to be incorrect in the orders and distributors report as well!

**Comment by chahmedejaz** [comment]
Let me look into it and other reports as well. Thanks
