### ISSUE TITLE
As an admin, I can preview how products will appear in the store

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12770]
**When working on this use clokify code # 12476 - Flower farms**

## Description
**- As a:** admin or super admin
**- On page:** `/admin/products`
**- I want to be able to do:** 

Access a new menu allowing individual preview of products.

 There are a few elements relying on the order cycle or AngularJS which we may need to leave out to save time here:

-  Hide the pie chart.
-  Disable the add-button.
-  Don't open product or producer modal.
-  Use only producer price.

**if a person updates a product but doesn't save it, they will see the version that was saved before**.

## Design links

https://www.figma.com/proto/ddL6h7H9It5ZmUuVYQxzAD/Product-List?page-id=1083%3A2&node-id=1083-2672&viewport=418%2C519%2C0.07&t=cxHmDB4r34gl7q0V-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1083%3A2672

https://www.figma.com/proto/ddL6h7H9It5ZmUuVYQxzAD/Product-List?page-id=1083%3A2&node-id=1138-368&viewport=287%2C154%2C0.14&t=EUUeqCZtE37WPgTM-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1138%3A368&show-proto-sidebar=1

## Acceptance criteria and tests

The following scenario must be tested as single producer, producer hubs and hub profile. A quick look at super admin might be useful too.

1. Log in 
2. On `admin/products` you should now have a new menu "preview" in the product action buttons: 
![image](https://github.com/user-attachments/assets/65784f4c-b460-4af3-8f34-e190a69364d2)

3. Clicking on preview opens a new modal allowing to see the product as it would appear in shop (apart from the prices that are showing producer prices)

![image](https://github.com/user-attachments/assets/ce4be08e-a5a3-4a09-ad86-95b510b1ea79)

4. The tab product details allows to see the product description:

![image](https://github.com/user-attachments/assets/9c77f9c9-7847-4d74-a1e1-860342c074c6)

5. Check that updating the product + saving is showing up on the preview and that the add to cart button is disabled

6. Check the preview is also available from the edit product page (next to the update button)

![image](https://github.com/user-attachments/assets/d482d174-7600-412d-a1b4-45af8915fd8e)

**Comment by rioug** [comment]
@RachL The remaining stock is displayed by default as there is no way to check the shop settings when in the backoffice
