### ISSUE TITLE
[CI] Can't record several artifacts on same node group

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12791]
### What we should change and why (this is tech debt)

If more than one spec fails within the same node group (for example, both failing specs are in `system_admin`) but on separate nodes (ex: `14, 11` and `14, 3`), then there is a naming conflict on artifact generation.
Likely to have been introduced with https://github.com/openfoodfoundation/openfoodnetwork/issues/12757.

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/10461826863/job/28970944267?pr=12790

**Comment by chahmedejaz** [comment]
Hi @filipefurtad0 - Can you please validate it in the latest master, as this should have been fixed in [this issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/12783). Thanks.

**Comment by filipefurtad0** [comment]
Thanks for the heads up @chahmedejaz :zap: 

I'll open a PR with different failing specs and report back.

**Comment by filipefurtad0** [comment]
Looks great!!

I've broken the build in this PR:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/10475057320/job/29010847500?pr=12795

From which several artifacts were produced:

![image](https://github.com/user-attachments/assets/82ac2b22-602e-46e1-92a0-e5019d9e48f6)

![image](https://github.com/user-attachments/assets/d0af572d-bc2b-46c4-a3dd-4750d94eafb7)

![image](https://github.com/user-attachments/assets/a70e73c8-0431-4454-8395-61e3702eb2ee)

Each artifact containing the screenshots for every failing test case.

Awesome :muscle:
