### ISSUE TITLE
Welcome email to rephrase

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1279]
Welcome email references 'Send Feedback' interaction - a feature available on the staging sites but not in production. This message is still appearing in production's Welcome emails.
Recommendation: Remove this line from the welcome email, because the Send Feedback feature doesn't exist.
Device: All 
Where: Welcome email
![image](https://cloud.githubusercontent.com/assets/10843056/20949800/9b7b5d90-bc6f-11e6-9009-98d4afd689ac.png)

**Comment by sstead** [comment]
Update: Yes bugherd has been removed so we no longer have a 'send feedback' button. Let's rephrase the email:

Existing text: "We welcome all your questions and feedback; you can use the Send Feedback button on the site or email us at hello@openfoodnetwork.org.au"

Update text to read: "We welcome all your questions and feedback; you can email us at hello@openfoodnetwork.org.au" <--- note that this email will be different for each instance.

**Comment by myriamboure** [comment]
@sstead I think it's better in such cases to directly modify the main thread, as it is not valid anymore so we don't care about the precedent situation here. Let's try to do that whenever we can to avoid people spend time reading useless things ;-)

**Comment by luisramos0** [comment]
this can be done in transifex now for en_au here:
https://www.transifex.com/open-food-foundation/open-food-network/translate/#en_AU/enyml/63684022?q=key%3Aemail_signup_help_html
