### ISSUE TITLE
[BUU] Table width is not responsive to the amount of selected columns

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12809]
## Expected Behavior

Table width should be responsive to the amount of selected columns, i.e, less columns selected => wider display for the kept columns.  A gray area should not appear.

## Actual Behaviour

Table width is not responsive to the amount of selected columns, i.e, removing columns does not change the width of the kept columns. A gray area appears.

## Steps to Reproduce

1. As a (hub) admin visit the /products page
2. On the Columns dropdown, de-select some columns
3. Notice the gray space appearing on the right side of the table, and this does not influence the table contents.

## Animated Gif/Screenshot

![image](https://github.com/user-attachments/assets/f8521e67-c58f-4763-ac85-9b980cc8478b)

## Workaround

No workaround (If one is removing columns to make elements more readable).

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.6.1
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by chahmedejaz** [comment]
This issue is reproduced only when either **Producer** or **On Hand** columns is hidden.
