### ISSUE TITLE
Editing products with mL as units leads to inconsistent behavior with Hungarian locale 

### ISSUE THREAD

**Issue by zsoltiNagy** [openfoodfoundation/openfoodnetwork#12815]
## Description
I encountered an issue when changing the unit scale in the admin/products section. This action causes inconsistent behavior when using the Hungarian (hun) locale. The bug is problematic because it affects the accuracy of product information displayed to users in this locale, leading to potential confusion or errors in interpreting product data. I was trying to ensure that product units are correctly scaled and displayed according to local preferences, but the inconsistency prevents achieving this objective effectively.

## Expected Behavior
Changing unit scales with ease.

## Actual Behaviour
When changing unit scales, the modified product banner gets stuck and displays inconsistent results. Additionally, the units change in an inconsistent manner.

## Steps to Reproduce
1. admin_style_v3 feature is enabled at /admin/feature-toggle/features
2. locale is set to hungarian (Magyar)
3. navigate to /admin/products
4. try to change any products Unit scale, e.g. from ml to mg

## Animated Gif/Screenshot
![image](https://github.com/user-attachments/assets/9f06c198-85cc-4337-89c9-a292b496061e)
)

## Workaround
Switching admin_style_v3 off

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by zsoltiNagy** [comment]
@RachL I'll try best to give you a detailed answer!

->If you change from ml to mg, what do you get as an inconsistent unit?
If we edit a product with a milliliter (ml) packaging, after saving it, a message appears indicating that there is a change and we should save again. If we save again, it converts the product from ml to grams (g) and divides its weight by a thousand. For example, instead of 500 ml, it becomes 0.5 g.

->Can you translate what the error message means?
The error message means 1 product modified.

->Do you have this behavior on all products? All enterprises?
So far where it was tested this bug occured. Though only when the admin_style_v3 feature was turned on.

->Previously, if the error message would not go away it was often because there was a corrupted product.
Yes, this behavior creates corrupted products. The save notification banner stays visible indefinitely and displays incorrect information, such as indicating changes for multiple products when only one has been modified, even if there are no cloned instances present.

**Comment by filipefurtad0** [comment]
Hey @zsoltiNagy ,

Thanks for reporting! I'm trying to reproduce the issue.

> try to change any products Unit scale, e.g. from ml to mg

You're trying to change units from mL to mg, so changing from 500 mL you'd like to get 500 mg - do I understand correctly?

The picture you share displays the `unit (g)` as selected option. So maybe the `mg` option is not available for selection. Which makes me wonder whether this option is set under Configuration / General settings tab (accessible only as superadmin):

![image](https://github.com/user-attachments/assets/6eab7702-dded-4de4-b410-31b8059f3f9b)

I've tested changing units **without** the `mg` option selected (as above) for both the legacy and new design and we do get different behavior. I've created three weight products (500 mL) and changed the unit to g, on different sessions (one legacy products page, and the other one - the new products page). The results are different indeed:

![image](https://github.com/user-attachments/assets/f188925f-9b3e-4a6b-adcc-52305758719d)

We can see that there is a different logic working and that variants have different `unit_values`:

```
 weight | unit_value | unit_description | display_name | display_as | variant_unit | unit_presentation 
--------+------------+------------------+--------------+------------+--------------+-------------------
   0.00 |        0.5 |                  |              |            | weight       | 0.5g
   0.50 |        500 |                  |              |            | weight       | 500g
   0.00 |        0.5 |                  |              |            | volume       | 500mL
(3 rows)
```

The third row displays an unchanged 500 mL product / variant. I could not get strange or inconsistent behavior on saving the changes, or noticed corrupt products.

> For example, instead of 500 ml, it becomes 0.5 g.

I could only reproduce this for the legacy products page; for the new products page, I got 500 g (as shown on the pics).

Can you comment on these findings and share your configuration? Many thanks again for your help @zsoltiNagy.

**Comment by zsoltiNagy** [comment]
@filipefurtad0 Thanks for the quick reply and the questions. This morning, I had the opportunity to test this issue more thorougly using the hungarian locale. Here is the configuration I use on my local instance:

<img width="392" alt="Screenshot 2024-08-27 at 05 47 24" src="https://github.com/user-attachments/assets/70c1d095-95b1-4e35-a1ce-bba8fb63c35f">

I realized there are two -probably connected- issues working in tandem, hence the inconsistent behavior that we noticed. 
The first is an issue with changing the Unit Scale:
-> The product has a Volume (mL) Unit Scale with 500ml Unit originally 
<img width="1370" alt="Screenshot 2024-08-27 at 05 57 22" src="https://github.com/user-attachments/assets/933f1c23-3ee7-4e78-90ed-cc0ca2a14668">

-> I change it to Weight(mg)
<img width="1359" alt="Screenshot 2024-08-27 at 05 58 04" src="https://github.com/user-attachments/assets/eec9e4eb-3233-4534-a77b-926a9727dbb8">
-> The Unit is multiplied by 1000
<img width="1353" alt="Screenshot 2024-08-27 at 06 01 04" src="https://github.com/user-attachments/assets/b08d9e90-a5c0-4827-a8fd-a712d6ca4c6e">

In itself its not a big problem, though combined with the second it can lead to some confusion.
**So, the second, probably the main issue**:
-> I want to change the Unit for a Product with mL Unit Scale
<img width="1377" alt="Screenshot 2024-08-27 at 06 03 24" src="https://github.com/user-attachments/assets/230c9d9c-9efa-4c3c-9863-fc9538d440de">
<img width="1359" alt="Screenshot 2024-08-27 at 06 04 15" src="https://github.com/user-attachments/assets/a318ade4-23ec-4ae7-b5c0-e07854188e78">
-> After clicking on saving the changes ("Változások mentése")the Unit Scale changes to Weight (mg) ("Súly (mg)")
<img width="1366" alt="Screenshot 2024-08-27 at 06 05 00" src="https://github.com/user-attachments/assets/4c9be770-14c8-489f-9959-80f3fb50cd6d">
-> The unit is changed to the correct amount:
<img width="1359" alt="Screenshot 2024-08-27 at 06 06 03" src="https://github.com/user-attachments/assets/10384183-eea5-4c08-9bd6-4a675a90eed1">
-> The banner on top is stuck and unresponsive, and now if I click on Save changes/"Változtatások mentése" once again, the black banner on the bottom of the screen shows that the changes were saved and the Unit changes to mg.
<img width="1382" alt="Screenshot 2024-08-27 at 06 06 48" src="https://github.com/user-attachments/assets/3bad249f-7afb-466c-b83e-531b4705a360">
-> If I have multiple products using "Volume (mL)"/"Űrtartalom (mL)" and I change only ones Unit value, the same Unit Scale change occurs for both and the banner indicates two product change:
<img width="1268" alt="Screenshot 2024-08-27 at 06 38 06" src="https://github.com/user-attachments/assets/364012b4-1d6b-4ffb-af7e-6683df340e3c">
-> Also the stucked banner is permanent and unresponsive, even after changing the locale to English and navigating back to the Products page:
<img width="1280" alt="Screenshot 2024-08-27 at 06 39 00" src="https://github.com/user-attachments/assets/a2c63aee-cb65-4396-be15-7b84c511098a">
-> The only workaround to get rid of the banner is deleting the affected products. 

Sorry if the issue description was confusing at first and once again thanks for the quick replies! :)

**Comment by zsoltiNagy** [comment]
Unit Scale/"Mértékegység skála", Unit/"Mértékegység"

**Comment by filipefurtad0** [comment]
Hi @zsoltiNagy ,

Thanks for your detailed description. I am not able to test this in a staging server with the HU locale, we'd need to provision it with this setting.

Given this, I was unable to reproduce the issue:
- changing unit scale from 500 mL to 500 mg works well, we get the expected result
- changing unit from 500 mL to 100 mL also works without any issues

I think I could test this in a local environment with the `hu` locale, I'd need to check how to set the default locales there, not sure how. I'll get back to you once I find something new.

**Comment by chahmedejaz** [comment]
Hi everyone, I looked into this issue however, I'm not able to reproduce it even with hu locale in the local environment.
The only error I encountered was a 500 error which resulted in updating the product AUD Price (from the previous locale) values to HUF values.
However, I believe the Hungarian prices on the instances would have been in HUF values already so it shouldn't be an issue there. Even if we did, we would have it logged in the Bugsnag which is not the case. Anyhow, I'm investigating further on the code level. Thanks

@filipefurtad0 Please make the following changes in your env files to have the Hungarian config locale working.:
- Replace following with ` AVAILABLE_LOCALES="en_AU,es,hu" `
https://github.com/openfoodfoundation/openfoodnetwork/blob/e2423ad6126009790dec5fff0c4aa7be3a070895/.env#L16
- Replace following with ` CURRENCY="HUF" `
https://github.com/openfoodfoundation/openfoodnetwork/blob/e2423ad6126009790dec5fff0c4aa7be3a070895/.env#L22
- Replace following with ` LOCALE="hu"`
https://github.com/openfoodfoundation/openfoodnetwork/blob/e2423ad6126009790dec5fff0c4aa7be3a070895/.env.development#L11

**Comment by chahmedejaz** [comment]
@zsoltiNagy - Just a thought:
> -> After clicking on saving the changes ("Változások mentése")the Unit Scale changes to Weight (mg) ("Súly (mg)")
> -> The unit is changed to the correct amount:

Do you get the success black banner message below for the first attempt?

**Comment by filipefurtad0** [comment]
Thanks for your help @chahmedejaz , I had forgotten to change `openfoodnetwork/.env` as well :raised_hands: 

This now worked and I can see the bug:

![image](https://github.com/user-attachments/assets/89c08ef8-b925-41c8-aadc-d712d41bb16f)
 
Changing units from 500 to 100 changes the unit scale, from mL to g. But actually it seems, that any change - for example, editing the product name - leads to this as well:

![image](https://github.com/user-attachments/assets/b5e5ef2e-d1ab-4140-90b1-55d1f21317f8)

It seems this occurs only with units mL. Any change made from a any other unit to mL or on a product/variant which has mL as a unit type will trigger a 422 error on the console. Here is a server log for such a change:
```

Unpermitted parameters: :authenticity_token, :page, :per_page, :search_term, :producer_id, :category_id, :products, :commit. Context: { controller: Admin::ProductsV3Controller, action: bulk_update, request: #<ActionDispatch::Request:0x0000747ab00c5108>, params: {"authenticity_token"=>"G4-SJ05o4l-UdW69RWSzzGGM8IT3rruIu5qvpqEWsoBFfatCLRl8275F1r19Din8PIwji6ULOpX9Imh16n_zFg", "page"=>"1", "per_page"=>"15", "search_term"=>"", "producer_id"=>"", "category_id"=>"", "products"=>{"0"=>{"id"=>"1", "name"=>"products", "sku"=>"", "variant_unit"=>"volume_0,001", "variant_unit_scale"=>"", "variant_unit_with_scale"=>"volume_0,001", "variant_unit_name"=>"", "variants_attributes"=>{"0"=>{"id"=>"2", "display_name"=>"", "sku"=>"", "unit_value"=>"100", "unit_description"=>"", "unit_value_with_description"=>"100", "display_as"=>"", "price"=>"0", "on_hand"=>"0", "on_demand"=>"0", "supplier_id"=>"1", "primary_taxon_id"=>"1", "tax_category_id"=>"1"}}}, "1"=>{"id"=>"2", "name"=>"Tomate Gloriette", "sku"=>"", "variant_unit"=>"weight", "variant_unit_scale"=>"1.0", "variant_unit_with_scale"=>"weight_1", "variant_unit_name"=>"", "variants_attributes"=>{"0"=>{"id"=>"3", "display_name"=>"", "sku"=>"", "unit_value"=>"500.0", "unit_description"=>"", "unit_value_with_description"=>"500", "display_as"=>"", "price"=>"0", "on_demand"=>"1", "supplier_id"=>"1", "primary_taxon_id"=>"1", "tax_category_id"=>"1"}}}}, "commit"=>"Változások mentése", "controller"=>"admin/products_v3", "action"=>"bulk_update"} }
Unpermitted parameter: :unit_value_with_description. Context: { controller: Admin::ProductsV3Controller, action: bulk_update, request: #<ActionDispatch::Request:0x0000747ab00c5108>, params: {"authenticity_token"=>"G4-SJ05o4l-UdW69RWSzzGGM8IT3rruIu5qvpqEWsoBFfatCLRl8275F1r19Din8PIwji6ULOpX9Imh16n_zFg", "page"=>"1", "per_page"=>"15", "search_term"=>"", "producer_id"=>"", "category_id"=>"", "products"=>{"0"=>{"id"=>"1", "name"=>"products", "sku"=>"", "variant_unit"=>"volume_0,001", "variant_unit_scale"=>"", "variant_unit_with_scale"=>"volume_0,001", "variant_unit_name"=>"", "variants_attributes"=>{"0"=>{"id"=>"2", "display_name"=>"", "sku"=>"", "unit_value"=>"100", "unit_description"=>"", "unit_value_with_description"=>"100", "display_as"=>"", "price"=>"0", "on_hand"=>"0", "on_demand"=>"0", "supplier_id"=>"1", "primary_taxon_id"=>"1", "tax_category_id"=>"1"}}}, "1"=>{"id"=>"2", "name"=>"Tomate Gloriette", "sku"=>"", "variant_unit"=>"weight", "variant_unit_scale"=>"1.0", "variant_unit_with_scale"=>"weight_1", "variant_unit_name"=>"", "variants_attributes"=>{"0"=>{"id"=>"3", "display_name"=>"", "sku"=>"", "unit_value"=>"500.0", "unit_description"=>"", "unit_value_with_description"=>"500", "display_as"=>"", "price"=>"0", "on_demand"=>"1", "supplier_id"=>"1", "primary_taxon_id"=>"1", "tax_category_id"=>"1"}}}}, "commit"=>"Változások mentése", "controller"=>"admin/products_v3", "action"=>"bulk_update"} }
Unpermitted parameter: :unit_value_with_description. Context: { controller: Admin::ProductsV3Controller, action: bulk_update, request: #<ActionDispatch::Request:0x0000747ab00c5108>, params: {"authenticity_token"=>"G4-SJ05o4l-UdW69RWSzzGGM8IT3rruIu5qvpqEWsoBFfatCLRl8275F1r19Din8PIwji6ULOpX9Imh16n_zFg", "page"=>"1", "per_page"=>"15", "search_term"=>"", "producer_id"=>"", "category_id"=>"", "products"=>{"0"=>{"id"=>"1", "name"=>"products", "sku"=>"", "variant_unit"=>"volume_0,001", "variant_unit_scale"=>"", "variant_unit_with_scale"=>"volume_0,001", "variant_unit_name"=>"", "variants_attributes"=>{"0"=>{"id"=>"2", "display_name"=>"", "sku"=>"", "unit_value"=>"100", "unit_description"=>"", "unit_value_with_description"=>"100", "display_as"=>"", "price"=>"0", "on_hand"=>"0", "on_demand"=>"0", "supplier_id"=>"1", "primary_taxon_id"=>"1", "tax_category_id"=>"1"}}}, "1"=>{"id"=>"2", "name"=>"Tomate Gloriette", "sku"=>"", "variant_unit"=>"weight", "variant_unit_scale"=>"1.0", "variant_unit_with_scale"=>"weight_1", "variant_unit_name"=>"", "variants_attributes"=>{"0"=>{"id"=>"3", "display_name"=>"", "sku"=>"", "unit_value"=>"500.0", "unit_description"=>"", "unit_value_with_description"=>"500", "display_as"=>"", "price"=>"0", "on_demand"=>"1", "supplier_id"=>"1", "primary_taxon_id"=>"1", "tax_category_id"=>"1"}}}}, "commit"=>"Változások mentése", "controller"=>"admin/products_v3", "action"=>"bulk_update"} }
Unpermitted parameters: :authenticity_token, :page, :per_page, :search_term, :producer_id, :category_id, :commit. Context: { controller: Admin::ProductsV3Controller, action: bulk_update, request: #<ActionDispatch::Request:0x0000747ab00c5108>, params: {"authenticity_token"=>"G4-SJ05o4l-UdW69RWSzzGGM8IT3rruIu5qvpqEWsoBFfatCLRl8275F1r19Din8PIwji6ULOpX9Imh16n_zFg", "page"=>"1", "per_page"=>"15", "search_term"=>"", "producer_id"=>"", "category_id"=>"", "products"=>{"0"=>{"id"=>"1", "name"=>"products", "sku"=>"", "variant_unit"=>"volume_0,001", "variant_unit_scale"=>"", "variant_unit_with_scale"=>"volume_0,001", "variant_unit_name"=>"", "variants_attributes"=>{"0"=>{"id"=>"2", "display_name"=>"", "sku"=>"", "unit_value"=>"100", "unit_description"=>"", "unit_value_with_description"=>"100", "display_as"=>"", "price"=>"0", "on_hand"=>"0", "on_demand"=>"0", "supplier_id"=>"1", "primary_taxon_id"=>"1", "tax_category_id"=>"1"}}}, "1"=>{"id"=>"2", "name"=>"Tomate Gloriette", "sku"=>"", "variant_unit"=>"weight", "variant_unit_scale"=>"1.0", "variant_unit_with_scale"=>"weight_1", "variant_unit_name"=>"", "variants_attributes"=>{"0"=>{"id"=>"3", "display_name"=>"", "sku"=>"", "unit_value"=>"500.0", "unit_description"=>"", "unit_value_with_description"=>"500", "display_as"=>"", "price"=>"0", "on_demand"=>"1", "supplier_id"=>"1", "primary_taxon_id"=>"1", "tax_category_id"=>"1"}}}}, "commit"=>"Változások mentése", "controller"=>"admin/products_v3", "action"=>"bulk_update"} }
```

**Comment by chahmedejaz** [comment]
Thanks @filipefurtad0, @zsoltiNagy  - I've also reproduced the issue, seems like I was also missing a step. Working on its fix. Thanks

**Comment by RachL** [comment]
Well done for finding this! I guess this makes it more of an s2? But anyway I see you're on it Ahmed, so probably the severity doesn't change anything at this stage :)

**Comment by chahmedejaz** [comment]
Sounds good Rachel. It's only the issue with Hungarian locale, I've found the root cause for this one and will propose the solutions in a while. Thanks

**Comment by chahmedejaz** [comment]
The fix is ready for review. 
@openfoodfoundation/core-devs would love to hear your thoughts on the fix. As it's creating buggy data on the Hungarian instance, Please let me know if you think of the otherwise solution so that we can fix it before re-drafting the release. Thanks.
