### ISSUE TITLE
User details page content has lost left/right padding

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1283]
Device: Mobile 
Where: User details
![image](https://cloud.githubusercontent.com/assets/10843056/20950361/61453b24-bc73-11e6-95f0-1aebf646e91d.png)

**Comment by pmackay** [comment]
How much padding would you expect? There is a small gutter I think. Otherwise fullwidth seems appropriate for mobile?

**Comment by sstead** [comment]
I think the padding looks ok now...
![image](https://user-images.githubusercontent.com/10843056/46838992-89652400-ce07-11e8-8cae-59da89bedc3d.png)
