### ISSUE TITLE
[Citi OFN Vouchers] As a shopper I can use a voucher created with VINE

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12859]
**_⚠️ When working on this use the Clockify code: Citi Food Vouchers: #1A. https://github.com/openfoodfoundation/openfoodnetwork/issues/11922 Citi OFN Voucher - VINE Integration ⚠️_**
## Description
**- As a:** a shopper
**- On page:** payment method step at checkout
**- I want to be able to do:**  

A voucher issued through VINE should work the same as an OFN voucher for the shopper experience:

- they can add the code at payment step
- they can see the discount is applied during checkout process

For the hub: all reports handling vouchers are updated accordingly.

the system should first check the OFN vouchers database before the VINE one.

## Acceptance Criteria & Tests

1. Check both guest shoppers and shoppers with an account and a VINE voucher
2. Check also guest shoppers and shopper with an account, but with an OFN voucher
3. Check what happens when the voucher has expired
4.  For enterprise users, reports should be accurate

## Estimations 
For context this is the current voucher "life cycle" :
When a customer enter a voucher code : 
- Check voucher exist in OFN
- Create order adjustment linked to voucher
- update adjustment with the correct amount and tax portion if necessary and update order totals and states  
- after payment details are entered, update adjustment and order totals and states
- voucher adjustment will be closed when the order is finalised, ie: this is when the voucher is considered "redeemed"
 
VINE voucher "life cycle" :
- Check if voucher exist in VINE :  https://vine-staging.openfoodnetwork.org.au/api-documentation#app-endpoints-POSTapi-v1-voucher-validation type: "voucher_code", value: "short_voucher_code" 
- Create a VINE voucher in OFN, based on data retrieved from VINE API, obfuscate voucher code (ie, keep only last 3 digit visible), will need to store voucher_id and voucher_set_id.
- Create order adjustment linked to voucher
- Update adjustment with the correct amount and tax portion if necessary and update order totals and states  
- After payment details are entered, update adjustment and order totals and states
- When order is finalised:
  -  Redeem VINE voucher the amount stored in voucher adjustment ( don't forget tax ) : https://vine-staging.openfoodnetwork.org.au/api-documentation#app-endpoints-POSTapi-v1-voucher-redemptions , use voucher_id and voucher_set_id stored against the voucher
  - Close the voucher adjustment on success
  - Handle redeeming error, display feedback to the user, potentially redirect to payment step so they can try a different voucher ?

### Assumption: 
- functionality to sign request with a JWT token already exist

### Tasks:
 - Check if VINE voucher exists and create voucher in OFN, update voucher model to add voucher_id, voucher_set_id : **0.5 -1 days**
 - VINE voucher redeeming and handle potential errors : **1.5 days** (high estimate, our checkout logic is complicated)  

Total : 2 -2.5 days , add 20% to cover unforeseen issue
**Estimation total: 2.4 - 3 days**

**Comment by rioug** [comment]
@RachL a few questions :
- I am not sure we ended up on an answer regarding diplaying VINE voucher on the voucher admin page. I am hiding them from now as they are going to be managed in VINE
- Do we need to tell the user if their VINE voucher is invalid ? currently I just return a generic error.

**Comment by RachL** [comment]
@rioug I'm still unsure how it will look like but I remember Kirsten saying the list of vouchers could end up being pretty long. If so, that would be a strong argument for not listing them on OFN

> Do we need to tell the user if their VINE voucher is invalid ? Currently I just return a generic error.

Do you mean on the checkout page? In this case I think a generic message is enough, the shopper does not need to know the type of voucher.

**Comment by rioug** [comment]
> > Do we need to tell the user if their VINE voucher is invalid ? Currently I just return a generic error.
> 
> Do you mean on the checkout page? In this case I think a generic message is enough, the shopper does not need to know the type of voucher.

I meant when adding a voucher to the order, the VINE Api can return an "Invalid voucher" error, ie: it has established the voucher exist in VINE but it's invalid for some reason. I am wondering if we should tell the customer so they can potentially tell whoever gave them the voucher that there is an issue.

**Comment by rioug** [comment]
I spent 49.59 hours on this
49.59 / 7.5 => 6.6 days
That's more than double the estimate, some of this time was spent setting User/Voucher in VINE, and there was a couple of scenarios that I missed in my estimate. On top of this, I always underestimate how long it takes to write the test notes for the PR.

**Comment by rioug** [comment]
New requirement :
- a voucher to be able to be redeemed by multiple merchants

**Comment by rioug** [comment]
@RachL 
Error shown to the customer :
On the checkout page when completing an order, when when redeeming a voucher fails we show an error if : 
- there was an error with the API (ie not available)
- The redemption failed

Redeeming a voucher can fail for multiple reasons, from the VINE Api:https://github.com/openfoodfoundation/vine/blob/1ec4970b94c3550880e7c3067bf8baf9da62b290/app/Http/Controllers/Api/V1/ApiVoucherRedemptionsController.php#L64-L93
The errors will be written in our log files, so we can use that if we need to investigate issues.
That said, do we want to show more specific errors to the customer ?  I don't think we would be sharing information that could lead to someone abusing the VINE Api.
