### ISSUE TITLE
Learn & Connect Main Navigation -Logo in main nav takes the User back to openfoodnetwork.org 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1285]
Logo in main nav takes the User back to openfoodnetwork.org (not .au) which is a jarring experience given that I came from the AU site.
Device: All
Where: Connect/Learn
![image](https://cloud.githubusercontent.com/assets/10843056/20950472/079cc3c0-bc74-11e6-8094-35e6f63c8061.png)

**Comment by sstead** [comment]
This is an Australia only issue, so might not be hacktoberfest suitable?

**Comment by myriamboure** [comment]
@kirstenalarsen can confirm but I removed the Hacktoberfest logo and I think we can close the issue as not related to this repo but to an external website. You can close if we are right.

**Comment by daniellemoorhead** [comment]
Closing issue, not relevant to global
