### ISSUE TITLE
[Citi Vouchers] Add VINE connected app

### ISSUE THREAD

**Issue by rioug** [openfoodfoundation/openfoodnetwork#12855]
_**:warning: When working on this use the Clockify code:  Citi Food Vouchers: #1A. #11922 Citi OFN Voucher - VINE Integration :warning:**_ 

## Description

See https://docs.google.com/presentation/d/1PcYNqh_2YNJ0GIaI7DDQPdKsLe5OFL5zlPl1v1ZMHmw/edit#slide=id.g279a7e25fac_0_0 for requirements

### Assumptions:
* The api key is provided by VINE
* A successful request to VINE api is enough to considered VINE connected app to be connected. 

### Tasks:
* Create new connected app and update admin screen, including an input for API key  **0.5 day** 
* Create "connect" action :  **1.25 day**
  * Generate a JWT token to sign request to VINE 
  * Try to connect to VINE with the given API key, store API key in the database on success
  * if error, provide feedback to the user, and allow to enter an new APi key

Total : 1.75 days , add 20% to cover unforeseen issue 
**Estimation total: 2.1 days**

## Acceptance Criteria & Tests

1.
2. 
3. 
4.

**Comment by mkllnk** [comment]
On the tasks:

* I don't think we need a background job to connect the app.
* We need an input field for the API key (called PAT = Personal Access Token here) which is new. The other apps don't have that.
* The controller needs to forward params like the PAT to the specific ConnectedApp class.
* It can then store that in the database and be connected instantly, assuming that the PAT will work.
* We could try the PAT first and tell the user if it's wrong. That's a nice-to-have though. I wouldn't do that in the background though because instant feedback to the user is more useful here.

**Comment by rioug** [comment]
> * It can then store that in the database and be connected instantly, assuming that the PAT will work.
> 
> * We could try the PAT first and tell the user if it's wrong. That's a nice-to-have though. I wouldn't do that in the background though because instant feedback to the user is more useful here.
> 

I am bit sceptical on not checking the PAT when turning on the connected app. It would make tracking down a wrong PAT harder, as we will probably realised the PAT is wrong when a customer tries to redeem a voucher for the first time, plus it would lead to a bad UX.

It should be pretty quick to check the PAT directly against the API and provide the ability to re enter the PAT if doesn't work. Agreed on not doing that in the background.  

@maikel What do you think ?

**Comment by mkllnk** [comment]
Yes, I'm happy for that, too. Definitely better UX.

**Comment by kirstenalarsen** [comment]
just commenting that I belatedly saw @RachL suggestion about possibly doing this on the voucher page and I quite liked. Perhaps one for delivery circle tonight

**Comment by rioug** [comment]
Updated the estimate with more details on this is going to work, based on Maikel's feedback

**Comment by rioug** [comment]
@rachel

I missed that we need store a secret linked with the API key in the database (the secret is used to sign request to VINE API). For added security we'll need to encrypt the data.

Estimation on the added work: 
- update screen and model to handle the secret **0.5.days**
- add encryption, includes generating encryption keys for all server and add it to `ofn-secret` **1 day**

Total : **1.5days**

Currently I spent 17h15 hours on this, which is slightly over the estimated 15h45 (2.1 days at 7.5h per day)
