### ISSUE TITLE
[Admin] Products Page does not scroll to the top when navigating between pages

### ISSUE THREAD

**Issue by zsoltiNagy** [openfoodfoundation/openfoodnetwork#12863]
## Description
When navigating between pages, the page does not automatically scroll back to the top. The user remains at the same scroll position, which may lead to confusion or a less seamless experience. Please update the functionality so that the page scrolls to the top upon navigation.

## Steps to Reproduce
1. Navigate to /admin/products
2. Clone a product for 15 times
3. Use pagination at the bottom of the page

## Animated Gif/Screenshot
<img width="1401" alt="Screenshot 2024-09-16 at 09 52 25 1" src="https://github.com/user-attachments/assets/02b3d2dc-7635-4425-92ed-5a3891273287">
<img width="1379" alt="Screenshot 2024-09-16 at 09 52 54" src="https://github.com/user-attachments/assets/d5cab9b6-b062-4279-b089-ebb72326efb5">

## Severity
bug-s4: it's annoying, but you can use it

**Comment by bouaik** [comment]
Can i take this issue ?

**Comment by filipefurtad0** [comment]
Sure @bouaik ,
Thanks! I've assigned you to the issue. Please let us know if you have any questions.
