### ISSUE TITLE
News page is empty

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1286]
Page is empty. On mobile/tablet this looks like an error. As a User I tried to use the dropdown to go to 'News' again, to be shown the same empty page :(

Device: All
Where: News

![image](https://cloud.githubusercontent.com/assets/10843056/20950595/b9ebf370-bc74-11e6-98b0-7431878fcb14.png)

**Comment by sstead** [comment]
I've removed the News link from Configuration > Content. It can be reinstated if News is added.
![image](https://cloud.githubusercontent.com/assets/10843056/20950685/47295854-bc75-11e6-9cc9-8f8022d72d28.png)

**Comment by sstead** [comment]
I deleted News from the "top nav" menu in Appearance > Menus
![image](https://cloud.githubusercontent.com/assets/10843056/21830395/81839794-d7f0-11e6-8329-486de82e96c7.png)

**Comment by daniellemoorhead** [comment]
Closing this issue as it's for the Wordpress site and not the OFN platform. Will consider the need for a news section on the global site at the point where we redesign it (a future desired piece of work).
