### ISSUE TITLE
News Dropdown Expanded

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1287]
This must be the wordpress navigation - everything looks different, even has different sections and groupings - confusing
Where: openfoodnetwork.org/news
Devices: All

![image](https://cloud.githubusercontent.com/assets/10843056/20950764/b69988ee-bc75-11e6-9923-79e4d45ddad0.png)

**Comment by sstead** [comment]
I can't see what this one is about? The horizontal menu becomes vertical quite smoothly and accurately? What's the problem?
![image](https://cloud.githubusercontent.com/assets/10843056/20950879/7f677740-bc76-11e6-9109-180e096bfe25.png)

**Comment by sstead** [comment]
I think the issue here is the users were/are being sent between local instances and the global instance (where the About Us pages are and the user guide/news pages were). The menus are different between the 2. I'm not sure what the solution is to this.

**Comment by myriamboure** [comment]
I think we can close that issue as this is not related to the OFN repository, it is about informational wordpress websites. The more broader problematic would be about integration between the OFN app and local info websites. The current solution to do "as if" they were the same website doesn't work but we will iterate later on. If you disagree reopen.
