### ISSUE TITLE
[Product preview] Prices on previewed products have '$' currency regardless of instance

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#12891]
**Please use clockify code #12476 Flower Farms**

## Description

Following the release of #12848 , product price in product preview is showing with '$' as the currency. This value doesn't appear to be from transifex but instead hard coded

## Expected Behavior

Product prices should show the currency defined at instance level (e.g. £ for UK, $ for US, CAN, AUS, € for FR etc)

## Actual Behaviour

Product prices in product preview show $ value regardless of instance

## Steps to Reproduce

1. Go to Products screen on UK Prod
2. Click preview on an existing product
3. Observe price value shown with $ symbol

## Animated Gif/Screenshot

Product preview on UK prod:
<img width="1000" alt="Screenshot 2024-10-07 at 11 22 57" src="https://github.com/user-attachments/assets/90807bfa-17e5-41c6-a710-d4e598251cba">

## Your Environment

UK Prod

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Reference currencyConfig currency symbol

**Comment by RachL** [comment]
hum that sounds like something we should have included in the first scope. @rioug I'm not sure who will pick up this one, do you see anything that might be worth sharing from the tech side?

**Comment by rioug** [comment]
Product preview uses `number_to_currency` helper https://apidock.com/rails/ActionView/Helpers/NumberHelper/number_to_currency. So will need to either pass the correct parameter to the helper or look into using `Spree::Money` or `Spree::Variant#price_in`. It should be a quick fix.
