### ISSUE TITLE
Release v4.6.11 Mee Goreng

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#12892]
## 1. Drafting on Friday

- [x] Merge pull requests in the [Ready To Go] column
  - [x] Depends on #12908 
- [x] Include translations: `script/release/update_locales`
    - You need the [Transifex Client] installed on your local dev environement to run the script.
- [x] Increment version number: `git push upstream HEAD:refs/tags/vX.Y.Z`
    - Major: if server changes are required (eg. provision with ofn-install)
    - Minor: larger change that is irreversible (eg. migration deleting data)
    - Patch: all others. Shortcut: `script/release/tag`
- [x] [Draft new release]. Look at previous [releases] for inspiration.
    - Select new release tag
    - _Generate release notes_ and check to ensure all items are arranged in the right category.
- [x] Notify [#instance-managers] of user-facing :eyes:, API :warning: and experimental :construction: changes.

## 2. Testing

- [x] Move this issue to Test Ready.
- [x] Notify `@testers` in [#testing].
- [x] Test build: [Deploy to Staging] with release tag.
- [x] Notify a deployer to deploy it

## 3. Deployment at beginning of week

- [x] Publish and notify [#global-community] (this is automatically posted with a plugin)
- [x] Deploy the new release to all managed instances.
  <details><summary>Command line instructions</summary>
  <pre>
  cd ofn-install
  git pull
  ansible-playbook --limit all_prod --extra-vars "git_version=vX.Y.Z" playbooks/deploy.yml
  </pre>
  </details>
- [x] Notify [#instance-managers]:
  > @instance_managers The new release has been deployed.
- [x] [Create issue] for next release and confirm with next release drafter in [#delivery-circle].

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Ready To Go]: https://github.com/orgs/openfoodfoundation/projects/8?filterQuery=status%3A%22Ready+to+go+%F0%9F%9A%80%22
[Transifex pull request]: https://github.com/openfoodfoundation/openfoodnetwork/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+head%3Atransifex
[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A
[releases]: https://github.com/openfoodfoundation/openfoodnetwork/releases
[#instance-managers]: https://app.slack.com/client/T02G54U79/CG7NJ966B
[#testing]: https://openfoodnetwork.slack.com/app_redirect?channel=C02TZ6X00
[Deploy to Staging]: https://github.com/openfoodfoundation/openfoodnetwork/actions/workflows/stage.yml
[#global-community]: https://app.slack.com/client/T02G54U79/C59ADD8F2
[Create issue]: https://github.com/openfoodfoundation/openfoodnetwork/issues/new?assignees=&labels=&projects=&template=release.md&title=Release
[#delivery-circle]: https://openfoodnetwork.slack.com/archives/C01T75H6G0Z
[Transifex Client]: https://developers.transifex.com/docs/cli

**Comment by drummer83** [comment]
Hi @dacook and @rioug,
Thanks for preparing the release. I know it was my turn, but I got distracted and a bit scared due to the potential bug. Glad it was only a configuration problem.

I've tested the release and couldn't find any problems. Testing notes are here, but nothing mentioned: https://docs.google.com/document/d/1kAeHBeCqhKYt51A_GS8_982BP0IEmJzTM48Gwz2KRmw/edit?tab=t.0

This one is ready to go! :rocket: 
Thanks again!
