### ISSUE TITLE
Estimate work needed to allow producer to edit their products on hubs' orders

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12893]
⚠️ **Please use clockify code #12476 Flower Farms**

## Description

In order to handle https://github.com/openfoodfoundation/wishlist/issues/172

**- As a:** producer without shops, but supplying other existing hubs 
**- On page:** `/admin/orders`
**- I want to be able to do:** see the orders containing my products in `admin/orders` and be able to edit them : add my products only, edit the quantity of my products only, delete my products only. Ideally the other products are hidden.

Hubs need to have the ability to allow producers to do that.

⚠ if the hub does not allow the producer to do see customer names, customer names must be hidden here as well (we can hide the whole tab perhaps?)

## Acceptance Criteria & Tests

The spike results need to give a clear solution in terms of tech solution. And an estimate of the amount of work needed. **No development should be started at this stage.**

**Comment by chahmedejaz** [comment]
Hi @RachL - Did a spike on this one, it's a 1±0.5 day effort for all the following tasks:
- Add enterprise permission 
- Add the ability to view orders containing my products
- Add the ability to add, edit, or delete my products from the order
- Hide all kinds of customer information from the orders

I have the following questions:
- What about other tabs? Do we need to hide them as well? 
![image](https://github.com/user-attachments/assets/602e6c11-4815-4137-bdf6-f42d0eea9d1c)

- For the part:
> ⚠ if the hub does not allow the producer to do see customer names, customer names must be hidden here as well (we can hide the whole tab perhaps?)
- Do the hubs have that ability? Or is it part of this?

Thanks

**Comment by RachL** [comment]
@chahmedejaz yes the hub has the ability here: `/admin/enterprises/release-farm/edit#/shop_preferences_panel`

![image](https://github.com/user-attachments/assets/76d0c3b2-963d-4ad6-8970-bc302bf4c261)

So when working on the enterprise permissions, we should reuse that setting to check if producer are allowed or not.

for the tab, I'm adding this to the agenda of tomorrow's product circle and let you know right away.

**Comment by chahmedejaz** [comment]
Sure, thanks Rachel

**Comment by RachL** [comment]
Thanks @mkllnk @chahmedejaz 

> Which line items should be displayed? Only from that supplier or all items?

What's the easiest? Note that in the case where we display all items, we should block the ability for the supplier to edit item they don't own.

> Hide order total? Fees? Adjustments?

I would leave them in first interation and we can see later if this is a problem.

I can do the screenshot after check with product circle :+1:

**Comment by chahmedejaz** [comment]
Thanks so much @mkllnk for the insights.

> What's the easiest? Note that in the case where we display all items, we should block the ability for the supplier to edit item they don't own.

@RachL - I think showing all the items would be easiest, that way we just need to put checks on the action buttons along with some authorization checks. What do you think @mkllnk?

**Comment by RachL** [comment]
@chahmedejaz @mkllnk 

FYI @tschumilas  will double check with her users to understand if it is a problem that producers are seeing what shoppers have ordered from other producers.

Once we have the info we can see how we progress with this. A couple of additional info that came out during our talk today: 

- we should add a setting that hub can turn on to allow producers to edit their items on orders (not all users will be happy about it)
- it would be nice if the `/admin/orders` page only shows to the producer, orders which contains their products
- another use case which can be solve here is the case where the producer has to give the final weight to the hub. Here they could do it themselves, but we would have to handle access to the BOM page as well

**Comment by mkllnk** [comment]
David and I had differing opinions here. David thinks that it's easier to show all items and disable the ones you can't edit. In this case, you have the whole picture of the order and a displayed order total makes sense.

I, on the other hand, thought that it would be easier to display only the items that can be edited. Then we don't need a version of the view with disabled items. And in case of many items, the supplier has the _shortlist_ of the items they are controlling without distraction. Any order total needs to be hidden to not confuse.

I reckon that we let @tschumilas decide on this one. Technically, it's not a big difference.

**Comment by tschumilas** [comment]
So I've chatted with a group of producers.  There are producers who don't want other suppliers in the same shop to see their prices,  or to know how much product they are supplying to specific buyers.   So,  I think it would be best to display (on the order)  only those items that can be edited (that is -  only the items owned by the producer doing the editing). 

One question -  about a producer ADDING items to an order.  Will they sell all the OC products in the 'select a variant' drop down, 
 or just their own?   That dropdown doesn't have pricing info -  so it wouldn't matter if a producer saw other producer's products.  BUT I'm wondering if we are opening up to user errors here.   For example -  I'm a producer in a shop with 20 other producers.  We all sell a given product.   Its easy to accidently add a different producer's product to the order.    (I've done it as a hub manager many many times)  I think its out of scope here?    But just raising  the issue - ideally a producer with this new permission to edit a hub's order,  would only be able to add their OWN products to the order.

**Comment by chahmedejaz** [comment]
@RachL - After considering the details, it would take 2-3 days of effort to implement this feature. Thanks.

**Comment by RachL** [comment]
Creating a proper issue here: https://github.com/openfoodfoundation/openfoodnetwork/issues/13031 Closing here
