### ISSUE TITLE
When all shops are closed, Users are presented with a confusing message when landing on /shops

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1290]
Device: Mobile/Tablet
Where: Shops
Recommendation: Message should read all shops are closed (rather than an incomplete 0 results sentence) or consider another way to encourage browsing of closed shops.
![image](https://cloud.githubusercontent.com/assets/10843056/20951434/c8af74f4-bc79-11e6-88e5-75ac0661882e.png)

**Comment by sstead** [comment]
This issue has been improved slightly since it was created:
![image](https://user-images.githubusercontent.com/10843056/46840084-1199f800-ce0d-11e8-8dd8-fdf63186c656.png)

- The message no longer reads "no results found for (blank)." Instead the search term has been added.

However the messaging could still be improved:
- The sentence "Did you mean? (text the user searched for)" doesn't help. I would expect a 'did you mean' helper to suggest similar sounding places to aid in the case of a typo. As it currently works this sentence is useless. There's another issue for this https://github.com/openfoodfoundation/openfoodnetwork/issues/1382
- We could suggest 'try another search or browse the [map](https://openfoodnetwork.org.au/map)'

**Comment by myriamboure** [comment]
Closing for https://github.com/openfoodfoundation/openfoodnetwork/issues/1382
