### ISSUE TITLE
Taxes (incl. in price) on shipping fees are being subtracted from order total

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12908]
## Description

I'm raising this as an s1 because I believe we have it in current master, but not yet in production. However, we shouldn't release anything until this is fixed.

When creating an order which includes a shipping fee with taxes (incl. in price), then the taxes on the shipping fee are subtracted from the order total - they should be included and not change the order total.

## Expected Behavior

Taxes on shipping fees included in price should not change - especially not reduce - the order total. The tax should appear as positive in the order adjustments.

## Actual Behaviour

Taxes on shipping fees included in price are reducing the order total. The tax appears as negative in the order adjustments.

## Steps to Reproduce

1. Create a shipping method with a shipping fee which has tax included in price.
2. Place an order using that shipping method.
3. Observe that the order total is reduced by the tax amount.
4. Observe that the tax is shown as negative in the order adjustments..

## Animated Gif/Screenshot

The cart/order summary:
![image](https://github.com/user-attachments/assets/8df65757-8dc5-4137-8607-9b0b6c8d6251)

The order confirmation:
![image](https://github.com/user-attachments/assets/13c62ba4-9091-4768-b018-dc0fef69bd84)

The adjustments:
![image](https://github.com/user-attachments/assets/8298012b-4596-4e6a-ba65-21b610e169d8)

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by rioug** [comment]
I couldn't reproduce the issue locally. So I had a look at your order on staging and it looks like a configuration issue.
The shipment's tax adjustment as the label "Refund Aus-GST-incl.price 10.0% (Included in price)", this is consistent with an negative tax adjustment.

The snippet below tells us that the tax rate adjustment is considered a refund if the order's zone doesn't match the Tax rate's zone or the order's zone is not included in the default's tax zone:
https://github.com/openfoodfoundation/openfoodnetwork/blob/7211b0d64aba415700016c71c4177ab00ef30b1c/app/models/spree/tax_rate.rb#L103-L118

The tax rate linked to the shipment: 
```ruby
<Spree::TaxRate:0x00007f471ccada68
 id: 24,                   
 amount: 0.1e0,            
 zone_id: 7,               
 tax_category_id: 1,       
 created_at: Thu, 29 Sep 2022 01:16:23.399569000 AEST +10:00,
 updated_at: Thu, 29 Sep 2022 01:16:44.397820000 AEST +10:00,
 included_in_price: true,  
 name: "Aus-GST-incl.price",
 show_rate_in_label: true, 
 deleted_at: nil> 
```
and associated zone : 
``` ruby
#<Spree::Zone:0x00007f471c66f4a8                                   
 id: 7,                                                            
 name: "Australia",                                                
 description: "",                                                  
 created_at: Thu, 15 Sep 2022 14:31:18.627800000 AEST +10:00,      
 updated_at: Thu, 15 Sep 2022 14:31:18.627800000 AEST +10:00,      
 default_tax: true,                                                
 zone_members_count: 0>
```
The zone associated with the order : 
```ruby
#<Spree::Zone:0x00007f471c774308                                         
 id: 3,                                                                  
 name: "New South Wales",                                                
 description: "New South Wales",                                         
 created_at: Wed, 11 Jul 2012 19:17:11.067050000 AEST +10:00,            
 updated_at: Sat, 07 May 2022 01:38:16.269514000 AEST +10:00,            
 default_tax: false,                                                     
 zone_members_count: 1> 
 ```
New South Wales is in Australia, but the code doesn't seem to support this kind of association.

**Comment by rioug** [comment]
@openfoodfoundation/testers could one of you confirm it's good now ?

**Comment by rioug** [comment]
I found this interesting comment about the "refund" code path : 
https://github.com/openfoodfoundation/openfoodnetwork/pull/6565/commits/a328a9bc1b1f902cc09f88201dbe1d89f84d44b4#r566535431

@openfoodfoundation/developers I am wondering if we should raise an error if we reach that code ? It shouldn't happen in production according to the comment and it would prevent issue like this one.

**Comment by drummer83** [comment]
Okay, thanks for the investigation @rioug!

I can reproduce this, but also Australia must be set as "Default Tax Zone". I have no clue if all this makes sense, but it seems it hasn't been changed recently. 

Closing here.
