### ISSUE TITLE
Order closing dropdown, when access zooms the mobile page however when a date is selected does not remove page zoom

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1291]
Recommendation: This seems to be a persistent issue with mobile and dropdown/field/select actions
Devices: Mobile/Tablet
Where: Shopfront
![image](https://cloud.githubusercontent.com/assets/10843056/20951469/feb0857a-bc79-11e6-9614-22eaf9bda0d1.png)

**Comment by jeronimo** [comment]
I might misunderstood the issue but in Android 6.0.1 with Chrome 56.0.x behaviour looks fine. 
![screenshot_20170327-114543](https://cloud.githubusercontent.com/assets/88912/24352969/917e7712-12e3-11e7-831b-402bfd465907.png)
Unless the zoom-in was executed manually by user. In that case it is normal behaviour not to zoom out automatically after selecting dropdown's option.

**Comment by jeronimo** [comment]
I could find only this dropdown in the front-end
