### ISSUE TITLE
Release v5.0.0 Grünkohl

### ISSUE THREAD

**Issue by rioug** [openfoodfoundation/openfoodnetwork#12920]
## 1. Preparation on Thursday

- [x] Merge pull requests in the [Ready To Go] column
- [x] Include translations: `script/release/update_locales`
    - You need the [Transifex Client] installed on your local dev environement to run the script.
- [x] Increment version number: `git push upstream HEAD:refs/tags/vX.Y.Z`
    - Major: if server changes are required (eg. provision with ofn-install)
    - Minor: larger change that is irreversible (eg. migration deleting data)
    - Patch: all others. Shortcut: `script/release/tag`
- [x] [Draft new release]. Look at previous [releases] for inspiration.
    - Select new release tag
    - _Generate release notes_ and check to ensure all items are arranged in the right category.
- [x] Notify [#instance-managers] of user-facing :eyes:, API :warning: and experimental :construction: changes.

## 2. Testing

- [x] Move this issue to Test Ready.
- [x] Notify `@testers` in [#testing].
- [x] Test build: [Deploy to Staging] with release tag.

## 3. Finish on Tuesday

- [x] Publish and notify [#global-community] (this is automatically posted with a plugin)
- [x] Deploy the new release to all managed instances.
  <details><summary>Command line instructions</summary>
  <pre>
  cd ofn-install
  git pull
  ansible-playbook --limit all_prod --extra-vars "git_version=vX.Y.Z" playbooks/deploy.yml
  </pre>
  </details>
- [x] Notify [#instance-managers]:
  > @instance_managers The new release has been deployed.
- [x] [Create issue] for next release and confirm with next release manager in [#core-devs].

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Ready To Go]: https://github.com/orgs/openfoodfoundation/projects/8?filterQuery=status%3A%22Ready+to+go+%F0%9F%9A%80%22
[Transifex pull request]: https://github.com/openfoodfoundation/openfoodnetwork/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+head%3Atransifex
[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A
[releases]: https://github.com/openfoodfoundation/openfoodnetwork/releases
[#instance-managers]: https://app.slack.com/client/T02G54U79/CG7NJ966B
[#testing]: https://openfoodnetwork.slack.com/app_redirect?channel=C02TZ6X00
[Deploy to Staging]: https://github.com/openfoodfoundation/openfoodnetwork/actions/workflows/stage.yml
[#global-community]: https://app.slack.com/client/T02G54U79/C59ADD8F2
[Create issue]: https://github.com/openfoodfoundation/openfoodnetwork/issues/new?assignees=&labels=&projects=&template=release.md&title=Release
[#core-devs]: https://openfoodnetwork.slack.com/archives/GK2T38QPJ
[Transifex Client]: https://developers.transifex.com/docs/cli

**Comment by mkllnk** [comment]
I created another tag in between again. You'll need to adjust the release note generation to the last official release tag v4.6.11.

**Comment by filipefurtad0** [comment]
Hey @rioug ,

I've tested the release, and the usual test cases show no issues, all good here:
https://docs.google.com/document/d/1IkUr7Fcipzr5oCggC7c03nzcqS3rG9XZdTKCx5Z-zZQ/edit?tab=t.0

However, I thought I'd have a look in the products page, given we're rolling out a big chunk. Unfortunately, it can be seen, that after staging this PR, new products/variants (1, pic below) retain the attributed unit scale but previously created products/variants (2, pic below) are left without a unit scale. Interestingly, it appears ok in the shopfrot:

![image](https://github.com/user-attachments/assets/d13b16c1-9605-4fbb-a6aa-3aae73d1a094)

I've checked the DB and it looks like the issue is not only on the UI, `variant_unit_scale` is NULL for variant 2):

For variant 1):
```

openfoodnetwork=> select variant_unit, variant_unit_scale, unit_value from spree_variants where id = 158192;
 variant_unit | variant_unit_scale | unit_value 
--------------+--------------------+------------
 weight       |               1000 |      22000
```

For variant 2)

```
openfoodnetwork=> select variant_unit, variant_unit_scale, unit_value from spree_variants where id = 158187;
 variant_unit | variant_unit_scale | unit_value 
--------------+--------------------+------------
 weight       |                    |       1000
(1 row)

```

I don't know why, but this was (and is, as of now) not observed in staging-AU, where the PR [#12787](https://github.com/openfoodfoundation/openfoodnetwork/pull/12787) was tested:

![image](https://github.com/user-attachments/assets/c977fef7-edfe-4b95-8281-4610b32f0765)

I'm afraid this release might be removing unit scale from all variants, so I'd mark it as blocked, for now. I'm a bit puzzled by this, I'd expect this to have been seen in staging-AU, before.

Happy for your thoughts on this.

**Comment by filipefurtad0** [comment]
After deleting the migrations with:
```

bundle exec rails db:migrate:down VERSION=20240819045115
bundle exec rails db:migrate:down VERSION=20240618013850
```

and re-staging the PR, we get the following result:

Variant 1) (from the pic in the previous comment) now has an empty `variant_unit_scale`:
```

openfoodnetwork=> select variant_unit, variant_unit_scale, unit_value from spree_variants where id = 158192;
 variant_unit | variant_unit_scale | unit_value 
--------------+--------------------+------------
 weight       |                    |      22000
(1 row)
```

Variant 2) now has the correct information an empty `variant_unit_scale`:

```
openfoodnetwork=> select variant_unit, variant_unit_scale, unit_value from spree_variants where id = 158187;
 variant_unit | variant_unit_scale | unit_value 
--------------+--------------------+------------
 weight       |               1000 |       1000
(1 row)
```

With an empty (mandatory) value, no changes can be made to the page. I think this might render the page unusable.

So, I'm not sure we're good here. Can you confirm @rioug @RachL ?

**Comment by rioug** [comment]
I think the database was a bit out of sync, probably because the PR was staged on the server but the migration were never reverted before this release was staged.

I reverted the migration using :
```
bundle exec rails db:migrate:down VERSION=20240819045115
bundle exec rails db:migrate:down VERSION=20240618013850
```
I then staged the current release and set up some test data : 
![Before_staging](https://github.com/user-attachments/assets/23a153f5-7f44-4e2b-8225-f45b49db71f3)

After staging v5.0.0 I can see the unit scale are correct :
![varian_unit_after](https://github.com/user-attachments/assets/298d4d97-de22-4831-ba0a-51443023ebd9)
