### ISSUE TITLE
Shop closed information in mobile is difficult to read in Mobile being right aligned

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1293]
Recommendation: Left align for Mobile/Tablet
Device: Mobile/tablet
Where: Shopfront
![image](https://cloud.githubusercontent.com/assets/10843056/20951666/34e19e44-bc7b-11e6-85af-98589dcb9993.png)

**Comment by OliverUK** [comment]
@lin-d-hop  I can't find mobile_closed in buildkite. I tried the merged uk/convert-sass-to-scss which deployed to staging ok but doesn't seem to have any effect on the orientation of the closed shop message shown on mobile devices.

**Comment by pmackay** [comment]
@OliverUK uk/convert-sass-to-scss has no functional effect - it is purely file format conversions to make SCSS files more consistent.

**Comment by OliverUK** [comment]
Thanks @pmackay I sort of expected that but as I don't quite understand the technical side and as the two were "merged" I thought I try.

**Comment by lin-d-hop** [comment]
@OliverUK try now

**Comment by OliverUK** [comment]
@lin-d-hop 
![screen shot 2017-01-25 at 17 03 16](https://cloud.githubusercontent.com/assets/17590921/22300702/34487d10-e320-11e6-9977-e51bece939bd.png)

**Comment by OliverUK** [comment]
This now deployed ok and below shows how closed shops now display on my mobile. 
![screenshot_20170201-171719](https://cloud.githubusercontent.com/assets/17590921/22517904/9d015cfa-e8a2-11e6-9a6f-c663f0e66f4b.png)
![screenshot_20170201-171754](https://cloud.githubusercontent.com/assets/17590921/22517905/9d08d3f4-e8a2-11e6-99c4-f9a60b24b5cf.png)

Text is now left aligned.

**Comment by sstead** [comment]
Tested on Nokia in IE and iPhone in Chrome. All good, left aligning correctly.
