### ISSUE TITLE
Text in 'next order closing' dropdown cuts off if too long

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1294]
Recommendation: Needs to wrap. Ideally a message like this shouldn't be an option in a dropdown.
Device: Mobile/Tablet
Where: Shopfront
![image](https://cloud.githubusercontent.com/assets/10843056/20951712/7fe4f292-bc7b-11e6-9e9f-6005425f45a8.png)

**Comment by Matt-Yorkley** [comment]
There's a few things with this issue. Firstly, that field is supposed to be a short, descriptive name for when the delivery will be made. It should result in something like "**Ready for:** Monday 23rd", not "**Ready for:** PLEASE BRING BACK YOUR GLASS BOTTLES AND DON'T FORGET TO SIGN UP TO OUR NEWSLETTER". So maybe that needs to be made more clear in the backend.

I notice there's a field for adding a description alongside the title in the backend, but there doesn't seem to be anywhere in the frontend where the description in this field actually gets displayed to the user. Maybe that's why people are resorting to putting more text in the title.

![screenshot from 2016-12-19 11-56-03](https://cloud.githubusercontent.com/assets/9029026/21312177/ad61cfcc-c5e2-11e6-801a-f8e488008060.png)

I think maybe the best option would be to limit the number of characters that can go into the title, and make sure the description is shown in the frontend when selected.

![screenshot from 2016-12-19 11-55-50](https://cloud.githubusercontent.com/assets/9029026/21312575/c218d102-c5e4-11e6-931a-66fa7db20f39.png)

Also some help tooltips added alongside the two fields in the backend might be useful.

**Comment by lin-d-hop** [comment]
That all sounds great @Matt-Yorkley.
How do you propose the description be displayed in the front end? Happy for you to design that.
Note in the tooltip it would be worth pointing out that these is a message field within Edit Enterprise -> Shop Preferences -> Shopfront Message.

**Comment by pmackay** [comment]
Is there even a need to implement wrapping (original issue point)? If the guidelines or restrictions about entering content in backend fixed this "empty bottles" message it would not be a problem..

**Comment by Matt-Yorkley** [comment]
I'm thinking it won't be necessary, no. Current proposal: 

- set a maximum length on the field of around 35 characters
- make sure the additional field for notes actually gets displayed in the frontend.

**Comment by sstead** [comment]
@matt the 'pick-up instructions' field was initially designed to not show at the front end. The idea was that you could include relatively private information in this field that will only be shown to customers who have checked out. An example- if you run a coop and allow customers to pick up orders from someone's back porch, you might only include the address of the house in this field, rather than on the profile. I'm not sure how widely used this feature is, but that's its background.

**Comment by Matt-Yorkley** [comment]
@sstead Ah, that makes sense now. I've searched the code and it doesn't get shown anywhere, which is partly why I felt like putting it to use. Do you think it should be only shown at the late stage of the checkout?

**Comment by sstead** [comment]
Had a chat to Rob and we think for now we should leave it as is. Keep in mind, enterprises can use the shipping methods description to tell customers about the pick up instructions. They can also use the 'shopfront message' to communicate additional instructions/details. The only other functionality that would be useful is the ability to have an order cycle specific message. This would be handy, but re-purposing this field may not be the answer because a) the transition would be messy, as many of the Aus user's messages weren't written to be displayed in the shopfront b) we need to be careful of cluttering the shopfront with messages so this needs some planning and c) there is a broader need to overhaul OC setup and this would be better addressed then. In the meantime, perhaps we could change the prompt 'pick-up instructions' to 'message to customers', or include 'what's this' pop up with an explanation, so users are aware of where the field is displayed.

**Comment by lin-d-hop** [comment]
@sstead When you say 'leave it like it is' I assume you refer to not displaying the additional text in the shopfront.
In order the resolve the UX issue we would still need to set a limit to the original field to 35 characters. Is this ok with you to go ahead with?

@Matt-Yorkley I think it is ok for UK users that currently use this field for additional information to move this info to the secondary field that is displayed at a later stage.

**Comment by sstead** [comment]
Yes, suggesting we leave the 'pick up instructions' field as is. The 'ready for' field above would be better limited to 35 characters.
________________________________

**Comment by sstead** [comment]
**Things that work:**
- In a hub order cycle I can write a maximum of 35 characters in the field.
- Those 35 characters fit well in in the mobile and desktop view.

**Things that still need to be done:**
- The tip text seems incomplete (see below)
![image](https://cloud.githubusercontent.com/assets/10843056/24438284/08773c50-1492-11e7-9264-3ab15e7c20eb.png)
Suggested text for tips:
Ready for: "When will orders placed in this OC be ready for the customer? (35 character limit)"
Customer instructions: "These instructions will only be shown to customers after they complete an order, in their order confirmation"

- There is also 'ready for' and 'customer instructions' fields in Producer only OCs (see below). These 'simple' OCs need 1) tips 2) the 35 character limit. Currently i can type excess of 35 characters in these OCs and get the wrapping issue.
![image](https://cloud.githubusercontent.com/assets/10843056/24438301/28e97732-1492-11e7-8a40-63b45ffc4b49.png)

**Comment by Matt-Yorkley** [comment]
@sstead I've fixed the tooltips and added them to the simple OC form and set the max length on the 'ready for' field.

**Comment by sstead** [comment]
Good to go - the producer only order cycles include the fix now, and the tooltip text is complete.

**Comment by mkllnk** [comment]
Fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/1532.
