### ISSUE TITLE
Price % breakdown pie graph not showing on mobile

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1297]
Device: Mobile/Tablet
Page: Shopfront

![image](https://cloud.githubusercontent.com/assets/10843056/20951894/c1a2ad18-bc7c-11e6-80ea-dc2e501e3bea.png)

Suggestion: Could you house it inside the expander.... 
![image](https://cloud.githubusercontent.com/assets/10843056/20951929/f508465e-bc7c-11e6-966e-9c069b3f3771.png)

**Comment by myriamboure** [comment]
Closing for most recent and templated https://github.com/openfoodfoundation/openfoodnetwork/issues/2102 (duplicate)
