### ISSUE TITLE
Order cancel error 

### ISSUE THREAD

**Issue by pragai** [openfoodfoundation/openfoodnetwork#12982]
## Description
![Screenshot 2024-11-18 at 19 05 51](https://github.com/user-attachments/assets/dd637551-0258-4795-b902-d482c7fe7f97)

On the Order List secreen selecting a list of orders and chosing action to cancel these orders freezes the app.
Also the attached error appears in the console.

## Expected Behavior
User is able to cancel orders from list.

## Actual Behaviour
Order cancel freezes the app.

## Steps to Reproduce
It maybe only an issue on the Hungarian instance.

Open Orders List.
Select some items.
Choose Cancel Orders action.

## Workaround
None

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
Hi @pragai flatpickr is the tool we use for the calendar. I remember there was something you needed to change on the translation in your case. Did you change it again recently or no link?

**Comment by pragai** [comment]
Could you recall what to change in the translation? If I recall correctly we did that, but I cannot find anything related to flatpickr now.

**Comment by chahmedejaz** [comment]
Hi @pragai - I did a spike on this issue in hu locale, when I 'confirm' the order cancelation, it cancels the order in the background but does not close the confirmation modal. Please review this screencast:

https://github.com/user-attachments/assets/d3858d88-2cd3-4f4c-8e05-af672bdf886b

Can you please validate? Thanks
