### ISSUE TITLE
[DFC Orders] Retail Variant Pricing

### ISSUE THREAD

**Issue by RaggedStaff** [openfoodfoundation/openfoodnetwork#12988]
#### :information_source: Funded Feature. Please track ALL ASSOCIATED WORK under the associated tracking code `#11678 DFC Orders`

When we import Transformed Products, we need to ensure the price of the retail variant reflects the actual cost price (Wholesale Product Price / Case Quantity ), not the RRP (Retail Product Price) as currently happens.

1. For mapped Products (where we will order a multiple pack/case, we need to adjust the price.
2. In the future, on an import screen it would be useful to display both prices & allow adjustment/selection from the importing user.

sample Screenshot from Shopify Hub app attached: 
![Image](https://github.com/user-attachments/assets/cc7af69b-5ce4-4a0e-81fc-9b24ddc9cddc)

**Comment by RaggedStaff** [comment]
@mkllnk does this make sense? Do you need any more detail from me to estimate?

**Comment by mkllnk** [comment]
> does this make sense? Do you need any more detail from me to estimate?

It makes sense. Just to explain the logic a bit better based on our phone conversation:

* The user imports products [manually](https://github.com/openfoodfoundation/openfoodnetwork/issues/12139) or the product price gets [updated when an order cycle opens](https://github.com/openfoodfoundation/openfoodnetwork/issues/12986).
* If not product mappings are present, we use the retail price of the retail variant as we do at the moment.
* If product mappings are present (transformations) then a retail variant's price is calculated from the wholesale variant price.
* Example: 1 can of retail beans are packed in a wholesale slab of 12 cans of beans. The slab costs $24 and the calculated price for the retail variant is then `24 / 12 = 2`.
* The distributor still adds their own fees within OFN to achieve their desired retail price.

This logic may not work for others using the import feature in the future. Then the user would need to define an import strategy. I could imagine this to be in the OIDC settings page but we don't have to worry about that yet.

Estimate: 2 days.
