### ISSUE TITLE
Remove page zoom when User clicks into field to update item #

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1298]
Remove page zoom when User clicks into field to update item # - this was they can see the total price of the item update as they change the item #
Device: Mobile/Tablet
Where: Shopfront
![image](https://cloud.githubusercontent.com/assets/10843056/20952011/764f748a-bc7d-11e6-9ae6-97dd191f36c1.png)

**Comment by pmackay** [comment]
Can you clarify what you mean by "page zoom"?

**Comment by lin-d-hop** [comment]
When you click in the box the page zooms to massive. A browser feature when filling in a text box. Does that help @pmackay?

**Comment by pmackay** [comment]
Yes, I know what that means, just didnt initially connect with description.

**Comment by sstead** [comment]
Note: This issue may get cleaned up in the mobile improvements which are currently underway.

**Comment by myriamboure** [comment]
@kirstenalarsen this is definitely impacted by mobile UX overhaul so I'll close it now, no need to have someone working on this anymore as UX is gonna change pretty much on that area. Reopen if you disagree.
