### ISSUE TITLE
Order cycle mail reports to producers display different data in html and txt versions

### ISSUE THREAD

**Issue by nicolasVr** [openfoodfoundation/openfoodnetwork#12993]
## Description
At the end of an order cycle the producers cans receive by mail a report of their orders. This mail contains a plain text and a html versions.
Both display the total order the producer has to deliver, but only the html shows the order by customer.

I acknowledged this issue because a hub complained that he missed an information he received before. Actually he probably changed email reader or settings.

## Expected Behavior
Both text and html versions should display all informations.

## Actual Behaviour
Here is an example retrieved from an email :
### Plain text version :
Cher(ère) La Ferme des p&#39;tits cllos,

Vous trouverez ci-dessous les informations pour le cycle de vente prévu pour :

- Du Cllos à la Fourchette (Ferme des Margannes le 22/11)

Orders summary

Les produits et quantités à livrer :

 - La Ferme des p'tits cllos - Crème crue - 20 cl (QTY: 2) @ 3,30 € = 6,60 €
 - La Ferme des p'tits cllos - Lait cru de vache  - 1L (QTY: 1) @ 1,65 € = 1,65 €
 - La Ferme des p'tits cllos - Yaourt au lait de vache - 125g (QTY: 8) @ 0,60 € = 4,80 €

Total: 13,05 €

Merci et belle fin de journée!,
Du Cllos à la Fourchette
1501 avenue de la Banque à Genêts, Cherbourg-en-Cotentin, 50470
0662833336
nicolas@lesgoulues.fr

### html version : 
_CoopCircuits

CoopCircuits

Cher(ère) La Ferme des p'tits cllos,

Vous trouverez ci-dessous les informations pour le cycle de vente prévu pour :
•  Du Cllos à la Fourchette (Ferme des Margannes le 22/11)

Les produits et quantités à livrer :
Référence Produit Produit Quantité Prix Sous-total Inclut TVA
Crème crue - 20 cl 2 3,30 € 6,60 € 0,34 €
Lait cru de vache - 1L 1 1,65 € 1,65 € 0,09 €
Yaourt au lait de vache - 125g 8 0,60 € 4,80 € 0,26 €
13,05 € 0,69 €

Détail par client·e :
Référence Produit Produit Quantité Prénom Nom de famille
Crème crue - 20 cl 1 Anne XXX
Yaourt au lait de vache - 125g 4 Régine ZZZ
Crème crue - 20 cl 1 Jourdainne AAAA
Lait cru de vache - 1L 1 Jourdainne AAAA
Yaourt au lait de vache - 125g 4 Jourdainne AAAAA

Merci et belle fin de journée! ,

Du Cllos à la Fourchette

1501 avenue de la Banque à Genêts
Cherbourg-en-Cotentin
50470

0662833336

nicolas@lesgoulues.fr

Conditions Générales d'Utilisation et de vente de CoopCircuits | CoopCircuits

## other point regarding mails
All mails sent by OFN-FR contain in the html headers _-- If you delete this meta tag, Half Life 3 will never be released. --_
Funny, but maybe not necessary ?

## Workaround
use html version...

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
French OFN instance

**Comment by RachL** [comment]
@openfoodfoundation/developers any hints at what may have caused this? FYI this was reported by users: https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1726668578218679 (but I suspect it has been here longer than september)

**Comment by nicolasVr** [comment]
It seems that more informations were added in html version of the email 3 years ago, but plain text version was not modified accordingly : https://github.com/openfoodfoundation/openfoodnetwork/blame/7a2a6fab21cbf869c928fddb178d73b21485776c/app/views/producer_mailer/order_cycle_report.html.haml

**Comment by nicolasVr** [comment]
"The Half Life 3" stuff was introduced 10 years ago : https://github.com/openfoodfoundation/openfoodnetwork/blame/7a2a6fab21cbf869c928fddb178d73b21485776c/app/views/layouts/mailer.html.haml#L4
I think it can be removed now !

**Comment by chahmedejaz** [comment]
Hi @RachL, @nicolasVr - The customer information was also added in the text version in future commits however, there was a conditional check to display the information which was never true in the case of the text version. It's a quick fix, and raising the PR now. Thanks.

**Comment by chahmedejaz** [comment]
@nicolasVr, @RachL - We are missing the **Included Tax** for the line item in the text version. Do we have any format/template to display this tax in the text version of the report? Other than that, the missing customer information issue is fixed as shown in the screencast below. Thanks.


https://github.com/user-attachments/assets/4184b2c8-603f-44f9-9a05-b9ecd3258f56

**Comment by RachL** [comment]
@chahmedejaz how about adding it in brackets after the total, something like: 

= $30.00 ($0.91 tax incl.)

**Comment by chahmedejaz** [comment]
Thanks @RachL - This has been incorporated and here's the demo:

[Screencast from 12-02-2024 06:50:09 PM.webm](https://github.com/user-attachments/assets/1d8a23d1-9063-4aea-8fad-d2fb5bd7395e)

The PR is ready for review now. Thanks.
