### ISSUE TITLE
Add customer code to notify producer emails when enabled

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#13007]
⚠️ **Please use clockify code #12476 Flower Farms**

## Context

Flower hubs are primarily wholesale hubs to businesses (versus consumers).
And, suppliers to these hubs pack the orders and label with the customer name before delivering to the hub.
Most suppliers use the automated email notification to pack orders since its an email and they can forward it easily to their team/helpers, and since they seldom have wifi access (for an OFN report) in their packing sheds.

At present, the customer name is added to the automated 'notify producer' emails when this option is enabled by the hub.
However, the business name (aka 'customer code' in the customer list) is not on these emails.

## Description
**- As a:** producer
**- On page:** "notify producer" email. email title is Order cycle report for [name of the producer)
**- I want to be able to do:** 

if the hub has enabled me to see customer names, I should receive an email that also shows the customer code as last column

![-Open-Food-Network-Canada-Order-cycle-report-for-Garden-Party-gardenpartyflowerfarm-gmail-com-Gmail-11-26-2024_01_32_PM](https://github.com/user-attachments/assets/3caec08e-f2e8-4859-a7fd-0d77e2c71715)

## Acceptance Criteria & Tests

1. Login with a hub that has customer names enabled at `admin/enterprises/speedy-uk-farm/edit#/shop_preferences_panel`
2. Click the "notify producer" button of the order cycle
3. Check the customer code appears in a column after last name
4. If nos customer code is showing up, the column should not appear
5. If the hub has customer names disabled, no name and no code should appear in the email

**Comment by tschumilas** [comment]
Its just criminal that you were on this so fast @chahmedejaz !!@!@!  Good to remember that sometimes the little things matter the most to our users.

**Comment by RachL** [comment]
@tschumilas FYI I'm usually getting the smallest issues ready first so if you think you have other don't hesitate to list them before our call on monday :)

**Comment by chahmedejaz** [comment]
>  Its just criminal that you were on this so fast @chahmedejaz !!@!@! Good to remember that sometimes the little things matter the most to our users.

😄😄

**Comment by chahmedejaz** [comment]
Hi @RachL - This feature has been implemented, however, we have an existing bug due to which customer details are not displayed in the text report in this notification mail.

The above bug is being fixed [here ](https://github.com/openfoodfoundation/openfoodnetwork/issues/12993)and feedback is needed on [this comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/12993#issuecomment-2499184256) so that we could get that bug fixed in master and we could test this feature in the text report of email as well. Thanks

**Comment by chahmedejaz** [comment]
@RachL, @tschumilas - Here's the current implementation:

https://github.com/user-attachments/assets/0f6dff3a-18d7-41a1-9e51-8241d63bc427

Please let me know what you think about it.

**Comment by tschumilas** [comment]
Looks good to me!

**Comment by RachL** [comment]
Same :) Thanks @chahmedejaz

**Comment by chahmedejaz** [comment]
**Update:**
- Development work for this issue is complete
- PR is raised however it depends upon the merge of the following fix in the text report before it'd be ready for review:
- https://github.com/openfoodfoundation/openfoodnetwork/pull/12996

Thanks.

**Comment by chahmedejaz** [comment]
**Update:**
- As the dependent issue is fixed, the PR for this issue is rebased and ready for review. Thanks
