### ISSUE TITLE
If cart has many items, user forced to scroll back to top of page to close cart

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1300]
When a User has created a shopping cart with many items, they're forced to scroll back to the top of the page to close it and continue shopping
Recommendation: Shopping cart dropdown should close/collapse if the User clicks outside of the dropdown
Device: Mobile/Tablet
Where: Cart dropdown
![image](https://cloud.githubusercontent.com/assets/10843056/20952093/09605032-bc7e-11e6-8043-233a299c4cbd.png)

**Comment by Matt-Yorkley** [comment]
This applies to desktop view as well, it's really annoying!

**Comment by lin-d-hop** [comment]
Duplicate #543 

Definitely a good one to pick up @podoglyph

**Comment by myriamboure** [comment]
Merged into https://github.com/openfoodfoundation/openfoodnetwork/issues/1255 so closing this one
