### ISSUE TITLE
[Orders Page] - Pagination is not working

### ISSUE THREAD

**Issue by chahmedejaz** [openfoodfoundation/openfoodnetwork#13002]
## Description

Reported here: https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1732694195740329?thread_ts=1732694195.740329&cid=CG7NJ966B

## Expected Behavior

- We should be able to navigate to different pages on the Orders Page.

## Actual Behaviour

- Pagination is not working and gives error

## Steps to Reproduce

1. Go to the Orders page
2. Navigate to the different page i.e. page#2
3. Nothing happens

## Workaround

- No workaround from the UI
## Severity

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
I agree with the s1 : it does prevent to print invoices e.g.

**Comment by dacook** [comment]
Deployed to all prod servers.

It's interesting to note an error that appeared after deployment, but it's only occurred once so I'm not sure it's worth following up at this stage: https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1732748611191179
