### ISSUE TITLE
Add 'tax category' to the All Products report

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#13008]
⚠️ **Please use clockify code #12476 Flower Farms**

## Context

When creating new variants at present, the 'default' tax category of 'none' is populated. If the supplier does not catch this, then no tax is charged for this product when the variant is purchased.

The hub only discovers this much later, when doing monthly tax reconcilliations - and so this means they have to go back to the customer and re-invoice them for the tax. Its very time consuming.

IF the hub had a quick way to check the tax category of all supplier's products before the shop opens, then they could fix the item in the supplier's product list (or as the supplier to do so).

Adding the 'tax category' to the 'all products' report would give the hubs this info quickly.

## Description
**- As a:** enterprise
**- On page:** `/admin/reports/products_and_inventory/all_products`
**- I want to be able to do:** 

This report should display a new column "tax category". this columns should be added as the last column of the report and should show the variant tax category

## Acceptance Criteria & Tests

1. Login as enterprise and go to `/admin/reports/products_and_inventory/all_products`
2. Check the "tax category" is available as a column
3. The column is not selected by default (to avoid messing with integration some users might have)

**Comment by RachL** [comment]
@chahmedejaz one more :)

**Comment by chahmedejaz** [comment]
Sure, Rachel :)

**Comment by chahmedejaz** [comment]
**Update:**
- The PR is ready for review
