### ISSUE TITLE
- OR - is wrapping in mobile in checkout

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1302]
- OR - is wrapping in mobile (tested on 375px wide phone, may have additional wrapping issues with a 320px wide phone)
Devices: Mobile/tablet
Where: Checkout as guest
Recommendation: Lose the dashes?

![image](https://cloud.githubusercontent.com/assets/10843056/20952858/841dede8-bc83-11e6-8912-509286de7d4d.png)

**Comment by lin-d-hop** [comment]
@OliverUK Can you test by looking on mobile device as well as PC.

**Comment by OliverUK** [comment]
@lin-d-hop 
Deployed to staging and tested. Created test OC and accessed front end on 
- firefox on Mac
- Android phone with 720 x 1280 - 294 ppi screen

Resulting screens shown below. 

![screen shot 2016-12-19 at 13 55 10](https://cloud.githubusercontent.com/assets/17590921/21315283/53c16a5c-c5f3-11e6-8d70-33486d62ab18.png)
![screenshot_20161219-135307](https://cloud.githubusercontent.com/assets/17590921/21315282/53befde4-c5f3-11e6-8bf8-3c37bb79a2a9.png)
