### ISSUE TITLE
If a user has provided city and state, it would be nice for the postcode to auto-fill

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1303]
Device: All
Where: Checkout
Recommendation: Set up address validation, link to address services
![image](https://cloud.githubusercontent.com/assets/10843056/20952909/d6d36eaa-bc83-11e6-9c4e-17c1c55d0b93.png)

**Comment by pmackay** [comment]
In what way would it auto-fill?

**Comment by sstead** [comment]
Sorry @pmackay can't answer that. All of these Dec 7th issues were things picked up by Yuko that I put into Github, perhaps ask her if she has a suggestion.

**Comment by lin-d-hop** [comment]
This is not something that would work internationally and thus not worth exploring further. In Aus half a state is a single postcode. In UK a postcode is one side of one street. #gitcull
