### ISSUE TITLE
Order summary should be placed above 'place order now' button to encourage final review by user.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1304]
Where: Checkout
Device: Mobile/Tablet
![image](https://cloud.githubusercontent.com/assets/10843056/20952928/feea273a-bc83-11e6-807a-ddc09a676a59.png)

**Comment by pmackay** [comment]
I'm a bit concerned about just moving the whole order summary as-is above the Place order button. It has the Back to cart button which is larger. 

What about moving the Back to cart button to be on the left on the same line as the Place order button? And align Place order to the right? (for all layouts, not just mobile) That would:

* Mean the Place order button is aligned with all the Next buttons in each form section, which seems more consistent.
* The final button layout would follow this [wizard UX recommendation](http://ui-patterns.com/patterns/Wizard).

@sstead @lin-d-hop thoughts?

**Comment by lin-d-hop** [comment]
Hi @pmackay Yep that was what I was envisaging. With both buttons appearing below the Order Summary.
Thanks for clarifying.

**Comment by myriamboure** [comment]
Has this been covered by mobile UX overhaul work @kirstenalarsen ? I'm not sure, it doesn't seem mobile wheckout has already  been worked on, so shall we keep this one and try to find someone to do it by highliting this to hacktoberfest contributors?

**Comment by Erioldoesdesign** [comment]
I don't think this is covered by mobile UX work so far but I disagree with having 50/50 buttons next to each other. Mobile is better if you stack buttons for accessibility and reducing error.

So:

[ Place order]

[< Back to Cart ]

leave at least 50px gap between two buttons so people don't accidentally hit one when they mean the other.

**Comment by RachL** [comment]
I'm closing this one because I think this will be covered and better spec in the checkout split.
