### ISSUE TITLE
Grey property tags on producer profile map modals are clickable, but do nothing

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1306]
Device: All
Where: Shops, profiles, map profile modals,
Recommendation: Make not clickable.

![image](https://cloud.githubusercontent.com/assets/10843056/20953200/ccb66a92-bc85-11e6-852f-7f7739447d2f.png)

**Comment by sauloperez** [comment]
Just to let you know, we have a slack team and a dev channel where people working on the codebase chat with each other. It's a great place to get some help as you start working on stuff. Let me know if you'd like us to send through an invitation to join. We also have community message boards where things get discussed [here](https://community.openfoodnetwork.org/).

**Comment by letakeane** [comment]
@sauloperez Thank you so much! I'd love to be added to the team/channel. Looking forward to diving deeper into an open source project!

**Comment by kirstenalarsen** [comment]
hey Leta - can you send your email to hello@openfoodnetwork.org and we’ll add you to slack :)

**Comment by sstead** [comment]
Thanks Leta!

**Testing notes**
- The map profile buttons no longer look clickable (correct)
- Filter buttons are still clickable (correct)
- However, the property and category badges in product description modals, within shops are still clickable when they shouldn't be. See below.
![image](https://user-images.githubusercontent.com/10843056/28607201-155480a6-721e-11e7-8c6a-66f3830c7ced.png)

**Comment by myriamboure** [comment]
Iceboxed here: https://community.openfoodnetwork.org/t/upload-and-display-product-quality-certificates/1145
#gitcull2018
