### ISSUE TITLE
Duplicate property tags on producer profiles map modal

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1307]
Devices: All
Where: Map, profile - Production
This producer doesn't have 2 grass fed properties applied, nor does it have the property applied to products and the producer.
![image](https://cloud.githubusercontent.com/assets/10843056/20953299/96ba0a42-bc86-11e6-84c2-4e9c241c6236.png)
![image](https://cloud.githubusercontent.com/assets/10843056/20953325/d600f18e-bc86-11e6-88c0-7d12e04149c0.png)
![image](https://cloud.githubusercontent.com/assets/10843056/20953410/822a537e-bc87-11e6-956b-c5f0a4c80c13.png)

**Comment by jennPeavler** [comment]
Hi there.  I am a first time contributor and I was hoping to fix this issue.  I am unable to recreate the duplication.  Is this still an issue?  If so ,can you please elaborate on how to re-create it.

Thanks for the feedback.  Hopefully I can resolve the issue!

**Comment by enricostano** [comment]
hi @jennPeavler !

@sstead could you please provide steps to reproduce this issue? Thanks!

**Comment by sstead** [comment]
Welcome @jennPeavler! I've had a look and I can't see this issue occurring anymore, nor can I recreate it. I hope you can find another issue to tackle :)

**Comment by daniellemoorhead** [comment]
Hey @jennPeavler @lauraturk you'll find some issues we thought were good for newbies to the codebase here:

Angular: https://github.com/openfoodfoundation/openfoodnetwork/labels/angular%20for%20newbies
Ruby: https://github.com/openfoodfoundation/openfoodnetwork/labels/rubies%20for%20newbies

**Comment by jennPeavler** [comment]
Thanks Danni M.  I'm going to try and tackle one now!
