### ISSUE TITLE
From the UK staging site, the registration country default is set to Afghanistan.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1308]
Device: All
Where: Register
![image](https://cloud.githubusercontent.com/assets/10843056/20953456/f7d8242a-bc87-11e6-8dd5-f7481e9e9660.png)

**Comment by myriamboure** [comment]
Is there a way to set up the registration default country? We have the same issue also in France, I didn't see neither in Github nor community forum.

**Comment by daniellemoorhead** [comment]
I think this issue is also linked to #218?

@lin-d-hop is this still an issue for the UK? Maybe one for the UK dev team to pick up?

**Comment by Matt-Yorkley** [comment]
This is covered in #1330.

**Comment by Matt-Yorkley** [comment]
Closed by #1609
