### ISSUE TITLE
State field is missing on UK staging

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1309]
State field is missing. Updated country to Aus, still missing. Field appeared after I tried to Submit the form and the form errors were presented.
Device: All
Where: Register - UK staging
![image](https://cloud.githubusercontent.com/assets/10843056/20953530/82fa76c0-bc88-11e6-9a52-5a5e97368b47.png)

**Comment by lin-d-hop** [comment]
Fixed now.
