### ISSUE TITLE
Reduce padding at top of page (above heading) to maximise screen height

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1311]
Devices: Mobile/Tablet
Where: Producers
![image](https://cloud.githubusercontent.com/assets/10843056/20953607/0ac7e916-bc89-11e6-961b-24075de2a027.png)

**Comment by lauraturk** [comment]
Afternoon! I’m a first-time contributor and was hoping to help out with this issue. If there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by daniellemoorhead** [comment]
@mkllnk or @enricostano or @Matt-Yorkley could one of you help out @lauraturk with setting up and getting onboard with the OFN codebase?

@lauraturk welcome! It's at a crappy time of the early morning for you but we have a regular dev catchup this Thursday (which makes it 5:30pm Melbourne time and 8:30am UK time). You're very welcome to join us if you're still awake! Also, have you joined our slack team yet?

**Comment by Matt-Yorkley** [comment]
Hi @lauraturk, I don't think anyone's working on this at the moment. If you want to set up a full dev environment there's guides for different OS's in our wiki: https://github.com/openfoodfoundation/openfoodnetwork/wiki

**Comment by lauraturk** [comment]
@Matt-Yorkley and @daniellemoorhead thanks! I'm all set up according to the wiki and Contributing doc. Great documentation, thanks!

There's a small cadre of us diving into our first contributions to open source for a school project. You'll see us popping up the next couple of days to hopefully help with some of the easier things!

**Comment by kirstenalarsen** [comment]
Hey Laura, welcome and if you send your email to hello@openfoodnetwork.org I’ll add you to Slack. Perhaps send me the emails of all the students so i can do it in one go?

**Comment by sstead** [comment]
The padding has been reduced since Yuko first picked up this issue. 
![image](https://user-images.githubusercontent.com/10843056/46839692-e0202d00-ce0a-11e8-963e-324b9b164682.png)
I'm no designer, so I'll leave this for someone else to decide whether the padding could be further improved.

**Comment by myriamboure** [comment]
@kirstenalarsen same here, I'm closing that issue as will definitely be impacted by mobile UX overhaul given Yuko new designs. Reopen if you disagree.
