### ISSUE TITLE
Why do the UK filters not have icons like AU?

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1312]
Devices: Mobile/Tablet
Where: Producers -UK
![image](https://cloud.githubusercontent.com/assets/10843056/20953647/39fa4242-bc89-11e6-81b0-a92fbe7df9f3.png)

- [x] @lin-d-hop to review all existing icons and see if any additional ones could be added to OFN UK
- [ ] @pmackay to document where to get icons and how to configure.

**Comment by lin-d-hop** [comment]
@sstead do you know where we could grab the image files for these label images?

**Comment by pmackay** [comment]
I've fixed the CORS config on S3 and uploaded images for all the taxon terms that match the image set I found on the OFN folder on Dropbox (/OFN DESIGN/HISTORICAL/design-ux/icon-font/design/taxon). 

@lin-d-hop could you please check and see if any other icons could be used on any other taxon terms? I think some additional icons could be useful personally.

**Comment by lin-d-hop** [comment]
Thanks for fixing this @pmackay Happy to update the icons.

**Comment by lin-d-hop** [comment]
All UK taxons now have icons.

**Comment by pmackay** [comment]
@lin-d-hop where are all the icons now stored, that you've used? I'd like to add a note to the deploy docs so this is a documented step for any instance.

**Comment by lin-d-hop** [comment]
@pmackay right now on gdrive. They aren't polished, in fact that are super amateur. Link to the others and ill make sure these are in the same place.

**Comment by pmackay** [comment]
I've added a small note here:

https://github.com/openfoodfoundation/ofn-install/wiki/Administration#taxonomies

**Comment by pmackay** [comment]
Have also added note here https://github.com/openfoodfoundation/ofn-install/wiki/File-storage#cors-configuration about CORS config.
