### ISSUE TITLE
Filter 'properties' are cut off

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1313]
Devices: Mobile/tablet
Where: Producers
Recommendation: Need to wrap. Side note: Is the term 'properties' language specific to the industry? I immediately thought of real estate :)
![image](https://cloud.githubusercontent.com/assets/10843056/20953695/76ee8dac-bc89-11e6-97ce-62a7625b344f.png)

**Comment by lin-d-hop** [comment]
Tested and it now appears correctly (ie as per main site) via android and chrome mobile tool.
Closing. Reopen if spotted again.
