### ISSUE TITLE
Clear filters on Producers page is currently located at the bottom of the expanded filters set. 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1314]
Where: Producers
Devices: Mobile/Tablet
Recommendation: Needs to be made available when the filters are collapsed.
![image](https://cloud.githubusercontent.com/assets/10843056/20953757/d2e0308e-bc89-11e6-91ab-4a718cb58a62.png)
![image](https://cloud.githubusercontent.com/assets/10843056/20953767/dd66fa9c-bc89-11e6-80f2-2130d0a47f8a.png)

**Comment by myriamboure** [comment]
Shall we cover this in a bigger UX overhaul project @kirstenalarsen ? After the first part of the work has been done on shops things will have changed on filter looks so I guess we will have to adjust on other page to have some consistency in the app. Do you agree? If yes shall we close this one for now? Or at least remove hacktoberfest if there is a risk that this work will not be used for long...

**Comment by kirstenalarsen** [comment]
hmmm - i don't really know what this is, but don't think it's clear that the producer listing will be included in quick wins (much as i would like it to be). If it's an easy fix just do it?

**Comment by RachL** [comment]
Closing here. Not sure which solution is wanted. We can reopen when we know / want to work on that page.
