### ISSUE TITLE
If there are no filters for a search term, don't show empty filter headings (eg. filter by property)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1315]
If there are no filters for a search term, don't show empty filter headings (eg. filter by property in image below)
Devices: Mobile/tablet
Where: Producers
![image](https://cloud.githubusercontent.com/assets/10843056/20953792/02d4df7e-bc8a-11e6-93b0-f7d75bb70aa5.png)

**Comment by myriamboure** [comment]
Iceboxed https://community.openfoodnetwork.org/t/customers-easily-go-through-the-whole-placing-order-process-on-mobile/1244 will work on it when we open the mobile UX topic
#gitcull2018
