### ISSUE TITLE
Reports Overhaul

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1316]

**Comment by Matt-Yorkley** [comment]
@rhodri Are you working on the UI Grid integration already? Am I right in thinking the current plan is to implement UI Grid (which includes re-creating a lot of the current functionality) and then add these improvements on top of that implementation? I'm also wondering if you think the 8 issues in this epic should be done in a certain order, or have a rough plan?

Maybe we can set up a uk testing branch for collaborating on this.

**Comment by lin-d-hop** [comment]
Closing this one. We are going to tackle with a totally different strategy, picking off the low hanging fruit and refactoring the existing first. Great outcome of the Aus week.
We'll capture things here:
https://community.openfoodnetwork.org/t/improve-reports-potential-integration/1143
#gitcull2017
