### ISSUE TITLE
LoadError in lib/open_food_network/integrity_checker.rb:1

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1321]
## Error in OpenFoodNetwork

**LoadError** in **lib/open_food_network/integrity_checker.rb:1**
cannot load such file -- rspec/rails

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5848a3be3cd47b100056b9a9)

## Stacktrace

    lib/open_food_network/integrity_checker.rb:1 - <top (required)>
    script/rails:6 - require
    script/rails:6 - <main>

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5848a3be3cd47b100056b9a9)

**Comment by mkllnk** [comment]
@RohanM Is that something you wrote? That has been happening on production for a month now.

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=584aa90274d81d110017ea78)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5853e68ef970de1100e84907)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=585a7e06eba2b21000e0ed52)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58762d4b64358d1100548964)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=587819a74a7e0611002818b2)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5878d046d1a9241100b3d4ee)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=587f67bced371d11007f8a98)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58815437334a8c1100e5667d)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5888a22c5615ff1100064a8f)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5891dc94253eff110041bd91)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=589a60a46724791100d8b52f)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=589b1704320fcc100008c612)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=589dba099eb6111100ce6b61)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58ad8bdce634951100cc5393)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58b02f971304af130016b7b2)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58c93c1be2045a1100973f5e)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58c9d682c99f2212009e5645)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58cbdf1c685e761800f8b3ca)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58dbb11c7247761700ddf47c)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58de5417077f3e17008998c8)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58e4f9aab048a61b008bd056)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58ee34292c4584001b3f005c&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58f76ea83cc2520019c97482&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=58fa11a8d465610018d0fa41&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5901faa63d57670018465fb2&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5909e3a6e892a6001ae36c3d&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=590c86a9d2f20600183d84ba&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5914fbc574c57c0018022e8e&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5915c12780cbbc0018bd2455&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=591c58a8745f4200185a2c94&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=591efba94a940d0019581bae&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=591f87bdad66a40018a7368c&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59259328cce45c0018834387&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=592ecda84a74e10018deb361&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=593170a949f2b40018bd22d9&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5941cea3bd3c130018a95fd9&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=594c5a9bc9226000185cb2ff&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5954439456bee300183d2b4d&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=596ff2fdb537470018a2d118&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=597295fe3ef9a2001a5c2554&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59792d76fddc460018235a24&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=597bd075befc46001c13ffdd&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=598267eea17ab4001a264ef4&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=598e45628c9d35001c2dd98a&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5994dcde9007e600189fb83d&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59977fdb0a73e70018bf9bc5&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59c452b9f2ecb5001a5e0eb6&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59c5a436cc3492001804caac&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59c6f5b5843812001cda0083&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59cc3bb25129e6001804a19f&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59d819294041030018b5d8ee&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59e00222df4d170018762398&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59e153a2e56367001a4149cc&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59e3f69efd2b4400186a4a59&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59e7eb1cb4ecf4001d8f2734&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59ea8e199a2b9c001856c916&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59f125965b6730001bd60e74&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=59fa600f0558e2001841aa36&i=gh&m=ra)

**Comment by sauloperez** [comment]
Can we please close this integration? To me it doesn't make sense to report failures of a particular instance.

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5a063d85029796001a8a3721&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5a0cd4ff65f988001a62af6a&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5a1760f743a0e5001aeaf171&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5a1df872a3b6e60019b3450f&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**LoadError** in **lib/open_food_network/integrity_checker.rb:1**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/581bd0c61aeffcbdf8e17197?event_id=5a21ecef069299001990b878&i=gh&m=ra)
