### ISSUE TITLE
Standing Orders - Tweaks & Fixes

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1323]
Everything in here is to be worked on during the two weeks of iterative changes to the new standing orders functionality.

**Comment by daniellemoorhead** [comment]
Hey @sigmundpetersen these subscriptions epics are really old potentially not even valid anymore and shouldn't this is why they weren't in the product feature backlog. They're all under the v1 epic, so they won't get lost 😃

**Comment by sigmundpetersen** [comment]
Yeah that's fine @daniellemoorhead I just followed the pattern of Spree Upgrade epic. These epics were in the Subs project, I moved them from there. Not having them in any project makes them harder to follow. Subs is not released yet and these eipcs have issues still open. I guess they should be reviewed, close the ones that are in fact done and move ones for Subs v2 elsewhere 😄

**Comment by daniellemoorhead** [comment]
Yep, they definitely need to be reviewed. Tis hard because it morphed into
something much bigger and is mostly in Rob's head. Sally and I are slowly
going through it all, trying to get a handle on it.
