### ISSUE TITLE
when change country while changing address, states doesn't refresh

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1341]
I changed some addresses for producers on the French instance now that we have imported the Spanish states, but when changing the address, I select first "Spain", then I expect the states to update but they don't, I have to "save", I get an error message but at the same time now the good states are available. So it's just not at all user friendy, would be great if states could dynamically refresh when I change country in the address.
![screenshot from 2016-12-18 08-29-01](https://cloud.githubusercontent.com/assets/8135376/21292389/94335ae6-c503-11e6-91d3-524e0bcb1f32.png)

Ping @NickWeir63 you will have the same issue when you have the Welsh addresses.

**Comment by myriamboure** [comment]
Nothing urgent of course, and normally if you import first the addresses users would naturally select their country first so it should not be too much of a problem...

**Comment by sigmundpetersen** [comment]
We're also trying to add Swedish addresses on the Norwegian instance and get the same error. Interested in finding out if this is a bug or what w should do to fix it on the server.

**Comment by myriamboure** [comment]
@sigmundpetersen that shouldn't prevent you to add swedish addresses on the server though, we managed to import them in France, if you have question ask Paco on Slack, he just did it :-)

**Comment by myriamboure** [comment]
Closing as we reopened a new issue for the same case... https://github.com/openfoodfoundation/openfoodnetwork/issues/1538
