### ISSUE TITLE
Blank delivery times

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1344]
Under order cycles there's a field to set when the delivery will be ready.

![screenshot from 2016-12-19 11-27-17](https://cloud.githubusercontent.com/assets/9029026/21311362/b6b40878-c5de-11e6-85a0-849fca459dd9.png)

If this is left blank it leaves an empty option in the dropdown in the frontend:

![screenshot from 2016-12-19 11-27-29](https://cloud.githubusercontent.com/assets/9029026/21311379/cfecac3c-c5de-11e6-934f-fef9dc189541.png)

It might be a good idea to make this field required on the backend. If there's multiple entries for pickup times, and some are blank it ends up with some named selections and some blank in the same dropdown, which is really confusing.

**Comment by lin-d-hop** [comment]
Yep, go for it @Matt-Yorkley

**Comment by Matt-Yorkley** [comment]
This is a bit more complicated than I thought, as there isn't a good implementation for validating fields with the ajax requests from the update button on the save bar. A few other things need to be validated on the admin page before save, and it's currently not handled very well. I'll have a look when I get time.

**Comment by daniellemoorhead** [comment]
Have moved this into 1.8.10 as it won't be ready for release today. See @sstead's testing notes for next steps.
