### ISSUE TITLE
Specs use $ for currency

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1346]
When running specs on a non-AUS setup, various tests fail as they are looking for values with "$" as the currency symbol. This isn't a big deal, but it does slow down the dev process when there are lots of errors.

2 possible solutions: internationalise all the tests (seems a bit unnecessary), or set some config options that explicitly set the default currency symbol to "$" before tests are run (easy option). 

Not a critical issue, but it would streamline things for non-AUS devs.

**Comment by lin-d-hop** [comment]
Yeah wavy hands. Would be nice to internationalise this!

**Comment by Matt-Yorkley** [comment]
@lin-d-hop Do you think it would be preferable to have all tests run using localised currency settings? I haven't had a proper look, but it might be an epic faff and could make a lot of specs more messy and complex than they need to be. Setting the default currency to $ whilst the tests run and just having a single test that checks currency functionality might be a lot cleaner...?

Either way it'll make life easier when it's sorted :)

**Comment by lin-d-hop** [comment]
@Matt-Yorkley My vote is setting default currency for simplicity. 
@stveep @sigmundpetersen any thoughts to the contrary?

**Comment by sigmundpetersen** [comment]
No obejctions :)

**Comment by stveep** [comment]
Agree - `I guess in config/environments/test.rb`

**Comment by myriamboure** [comment]
@Matt-Yorkley can I just close this one? Or do you want me to open an icebox item so that we can prioritize later ? If I understand well the focus is to make development easier by improving tests speed and efficiency right?

**Comment by myriamboure** [comment]
In objective to improve efficiency in developing / reviewing / testing / staging, I have created an icebox "developers don't waste precious time while developing" https://community.openfoodnetwork.org/t/developers-dont-waste-precious-time-while-developing/1273 and attach this in it, so closing it for now, we can reopen when we prioritize.

**Comment by lin-d-hop** [comment]
Reclosing. #gitcull
