### ISSUE TITLE
Clear cache when loading baseline data on staging

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1351]
When we load the baseline data on staging (which happens before each deploy), we change the database but don't touch the cache. This leaves the cached data inconsistent with the database, and introduces some confusing defects into the system that have nothing to do with the staged code.

To solve this, run `Rails.cache.clear` after the baseline data has been loaded.

**Comment by daniellemoorhead** [comment]
@oeoeaio @mkllnk and @RohanM what should we do about this in terms of the processes we use to deploy to staging? Only staging?

**Comment by mkllnk** [comment]
It's just a minor code change. Maybe I can look into it when looking at production deploy as well.

**Comment by myriamboure** [comment]
@sauloperez shall this go into sys admin standardization epic?

**Comment by sauloperez** [comment]
Yes, AFAIK this is still true

**Comment by Matt-Yorkley** [comment]
We have various bugs on bugsnag for UK prod related to caches not being valid, or objects missing when caches are loaded. It would be great if a simple Rails.cache.clear on deploy would fix that!

**Comment by sauloperez** [comment]
Now that I read again, I'm not so sure that is a solution @Matt-Yorkley clearing the cache is meant for staging environments where you load a bunch of new data and the cache is no longer up-to-date.

Cache errors in production should be fixed by revising the cache invalidation strategy. Could you please create issues for those problems you mention? I'm afraid our cache is not working as it should...

**Comment by Matt-Yorkley** [comment]
Hmm... I can't see the error now in Bugsnag. I'll post it up next time I see it.

**Comment by RachL** [comment]
@sauloperez are we doing this currenlty? Is this still needed if not?

**Comment by mkllnk** [comment]
Hm, I think most staging servers don't reset the database at the moment. But that is something we want to do again. And that case, yes, I think this will be needed.
