### ISSUE TITLE
Timing out...UK server

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1360]
One customer has been in touch saying she can't submit an order.
If I try and enter it for her I get the slug error page.
I also tried adding a new product just now and got another slug. 

Something is going badly wrong today!

@lin-d-hop @MagsHall @NickWeir63

**Comment by OliverUK** [comment]
Tried also from the front end on her behalf using guest checkout. The screen goes to 
![screen shot 2017-01-04 at 13 20 57](https://cloud.githubusercontent.com/assets/17590921/21643574/e6a8c646-d280-11e6-9ead-4638c7271376.png)

and then returns to the checkout page.

**Comment by OliverUK** [comment]
I've been able to submit the order now in 4 parts!

I kept taking things out of the basket and retrying until the order submitted. Eventually I had submitted all but one item but when I tried that last one on its own, that too went through. Therefore I can't say that any one particular product caused the issues not was it a certain number of items or value.

**Comment by lin-d-hop** [comment]
⁣ok, I deployed to prod yesterday, latest release. Clearly causing problems. Will revert asap.
Thanks oliver

**Comment by OliverUK** [comment]
Thanks @lin-d-hop 
Several orders have come through since earlier but just had a phone call from another member who can't order and I guess there may be more who haven't said. 
This is how the failed orders look in the orders list:

<img width="570" alt="screen shot 2017-01-04 at 21 08 59" src="https://cloud.githubusercontent.com/assets/17590921/21659335/26c5ba40-d2c2-11e6-951e-943bd01f3c05.png">
