### ISSUE TITLE
Avoid ActionController::RoutingError being triggered for 404 requests

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#1362]
The OFN UK log is full of `ActionController::RoutingError` exception traces because there are lots of spam crawlers calling odd URLs. Lets avoid this by adding 

`match '*path', via: :all, to: 'pages#error_404'`

to the end of `routes.rb` and a controller:

```
class PagesController < ApplicationController
  def error_404
    render status: 404
  end
end
```

**Comment by lin-d-hop** [comment]
This doesn't seem to be creating any major issues. CLosing.
