### ISSUE TITLE
Make selection of a group for display clearer

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#1364]
Currently a checkbox labelled "ON FRONT PAGE ?" must be ticked to show a group on `/groups` page. This could be more descriptive/clearer if it said something like "Display on Groups page". It feels confusing currently as it suggests the group will appear on the homepage (front).

**Comment by lin-d-hop** [comment]
This can be changed in en-GB: admin_entreprise_groups_on_front_page
Hence doesn't need an issue.
