### ISSUE TITLE
Remove /test directory?

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#1365]
There is one performance `BrowsingTest` that gets the homepage, but it isnt called in Travis. Most directories are empty. Is the `/test` dir needed?

@mkllnk thoughts?

**Comment by lin-d-hop** [comment]
@pmackay Can you ask this quesiton via slack instead? Then open an issue if it really is an issue?

**Comment by mkllnk** [comment]
This is not used at all. I would get rid of it. @pmackay Are you happy to create a PR?

**Comment by pmackay** [comment]
Now removed. Closing.
