### ISSUE TITLE
If I delete owner as a manager, the owner can no longer edit the enterprise

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1371]
If I own a profile, I'm automatically made a manager of the profile. As the owner, i can add and remove managers. 

As the owner, if I add another manager and remove myself as a manager (but remain the owner) I'm no longer able to edit that profile. I get the 'unauthorised' message. I can't see it in my enterprise list. If I enter the link e.g "https://staging2.openfood.com.au/admin/enterprises/NAME/edit" I am told I'm not authorised. I can't create OCs for that enterprise or see it in my admin. It's like I have no permission to it.

The new manager can see the profile in their account, but they cannot edit the users. The manager can see that the owner is still the owner... but that owner has lost all access to the enterprise they own...
![image](https://cloud.githubusercontent.com/assets/10843056/21834893/c9b31dde-d80c-11e6-8b9d-37797ccc8572.png)

Suggested solution:
- Don't allow delete of owner from the manager list.
OR
- Allow for deleting of owner from manager list, but treat owner the same as the manager (except for the additional power that comes with being owner, e.g. being able to add/remove managers and change notification email).

**Comment by myriamboure** [comment]
This has been covered by the work done by Matt on email confirmation, the issue should be solved now.
