### ISSUE TITLE
Private shop issue: require login not displaying well to user

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1376]
![screenshot from 2017-01-12 14-45-36](https://cloud.githubusercontent.com/assets/8135376/21892344/a99f9f8e-d8d6-11e6-8302-e88445036c69.png)

**Comment by myriamboure** [comment]
I wanted to ping Pacodelaluna but he doesn't seem to be in the team, also he submitted a pull request already (and will definitely submit more I hope!) Is it possible to add him @mkllnk ? Thanks ;-)

**Comment by myriamboure** [comment]
@pacodelaluna this is for you maybe? Easy? sorry @mkllnk  for the wrong request,  it was before you added him I guess, should have checked ;-)

**Comment by myriamboure** [comment]
I can't assign Pacodelaluna on this issue, is it a permission issue @mkllnk ?

**Comment by mkllnk** [comment]
This is a translation issue. Translators have to know that they must not translate things within `%{...}`. They are variables that get replaced, in this case by links. Should that be mentioned in https://community.openfoodnetwork.org/t/localisation-ofn-in-your-language/397 ? Or do we need a separate translator guide?

**Comment by myriamboure** [comment]
@pacodelaluna the first user needing that is going to test the platform this week, do you undertand this translation issue? Can you answer Maikel here on what you think we should do?

**Comment by pacodelaluna** [comment]
@myriamboure Yes, it is related to the translation, not to the code, let's discuss this on Slack.
