### ISSUE TITLE
 Private shop issue: if I login to a private show with a non-recognized email > BOOM

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1377]
Following this: https://github.com/openfoodfoundation/openfoodnetwork/issues/1376

So as requested, I login, if I use an email in the hub customer list the shopfront appear, works as expected.
If I use another email, valid account on ofn, I got the system error screen... I would have expected an error message saying something like "The email you tried to connect with is not in the members list of the foodhub, please connect with your member email. Not member? Contact the hub [link to contact]"

**Comment by myriamboure** [comment]
Same @pacodelaluna connected to the other one... let me know if you think it's easy or not.

**Comment by pacodelaluna** [comment]
@myriamboure Can you provide me a screenshot of this ? Let's discuss this on Slack.

**Comment by myriamboure** [comment]
@pacodelaluna clic on the shop page on "collectif court circuit la barre de monts", then clic on "login" (you have to use the upper login as the button in the page doesn't work), and try to login with a non super admin account (I use my account myriam@ouishare.net), as this account is not in the "buyers" list of the collectif court circuit entreprise, it is not recognize, but instead of  having an error message, it just crashes:
![screenshot from 2017-03-07 10-33-54](https://cloud.githubusercontent.com/assets/8135376/23650206/97d9b5ee-0321-11e7-99f0-cdae65eda1c8.png)

**Comment by myriamboure** [comment]
I re-tested and this is working properly, so closing.
