### ISSUE TITLE
Shop search always returns 'did you mean?'

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1382]
## Description
When I search for a place it always reads 'did you mean?', even if I spelled it correctly. Usually if you say 'did you mean', there will be a list of locations that are similar to what I typed. Just a bit confusing/not quite right. We need to change the wording so that it is more logical.

## Current behavior
When search show result:
![image](https://cloud.githubusercontent.com/assets/10843056/21914363/f2adfd78-d986-11e6-9da5-70d56254984d.png)
When search doesn't show result:
![46840084-1199f800-ce0d-11e8-8dd8-fdf63186c656](https://user-images.githubusercontent.com/8135376/46981639-8ef98d00-d0d9-11e8-8488-137fc61ec04f.png)

## Expected behavior
- Change "Did you mean?" to 'Results for [search text]' so if there is a result it is correctly displayed below...
- and if there is no result it says "Sorry, no results found for [search text]. Try another search or browse the map" (so we need to change a bit the sentence as today it is "Sorry, no results found for [search text]. Try another search." and add the url under "map" so that it redirects to the map)

**Comment by myriamboure** [comment]
@sstead I reformatted the issue so that it is clear for a dev what to do. If you disagree please tell or modify directly. We need to give precise indications to devs ;-) I closed the other issue.

**Comment by ZiyangGao1028** [comment]
Hi there, I'm a new dev and I would like to pick it up as a first issue!  -Ziyang

**Comment by luisramos0** [comment]
this is transifex work now.
here:
https://www.transifex.com/open-food-foundation/open-food-network/translate/#en_AU/enyml/63684045?q=key%3Ahubs_matches
and here
https://www.transifex.com/open-food-foundation/open-food-network/translate/#en_AU/enyml/63684058?q=key%3Asearch_no_results_html
