### ISSUE TITLE
Change 'enterprise relationships' to 'enterprise permissions'

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1384]
I suggest we replace "relationships" with "permissions", which is a more accurate description of the tool. Explaining E2Es is quite tricky already. Removing one more confusing word from the mix would help. 

![image](https://cloud.githubusercontent.com/assets/10843056/21916902/a5669dd4-d997-11e6-8344-b2537de6288f.png)

**Comment by myriamboure** [comment]
Adding "good first issue" label. For those who pick it up, change string "enterprise relationships" to "enterprise permissions" (this string is already connected to transifex as already translated by other instances so it's only about modifying original en version)

**Comment by farmermel** [comment]
Hi there! New contributors here (@OphDub @JorgeEdPerezGa @j25bender), moving on from issue 1806, hoping to help out with this issue. We noticed nobody was assigned to it, but if there's already a solution in progress we're happy to try helping out elsewhere. Thanks!

**Comment by sstead** [comment]
Thanks @farmermel , all yours!

**Comment by farmermel** [comment]
Hello again! My fellow contributors and I have made some headway but no longer have the time for this issue. 
In the file: `/app/views/admin/shared/_enterprises_sub_menu.html.haml`
We took this code:
`= content_for :sub_menu do
  %ul#sub_nav.inline-menu{"data-hook" => "admin_enterprise_sub_tabs"}
    = tab :enterprises, url: main_app.admin_enterprises_path
    = tab :enterprise_relationships, url: main_app.admin_enterprise_relationships_path`

and changed the last line to:
    `= tab :enterprise_permissions, url: main_app.admin_enterprise_relationships_path`

After this change the app looks like:
<img width="1155" alt="screen shot 2018-04-04 at 6 33 48 pm" src="https://user-images.githubusercontent.com/28467250/38341899-32eeba60-3838-11e8-8e3b-7b6950c0d65c.png">

We hope this helps the next person to pick up this issue!

**Comment by myriamboure** [comment]
Ok, thanks @farmermel and feel free to come back whenever you want :-) Cheers!

**Comment by kristinalim** [comment]
Hello! :-) I will be looking into this issue. Thanks for the tip, @farmermel!
