### ISSUE TITLE
SO - front end user flows design

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1390]
To fix the experience currently implemented in editing orders, and to prepare for the next stage of standing orders, we need user flows/interaction designs developed for the following tasks:

- [ ] A user edits their current order (within the current order cycle)
- [ ] A user sets up a standing order
- [ ] A user manages a future order (cancelling or possibly modifying within a particular order cycle)
- [ ] A user manages their standing order  (cancelling or bulk order editing)
- [ ] A user pauses their standing order for a set period of time

**Comment by yukoosawa** [comment]
### User edits their current order (within current order cycle)

HIGH LEVEL USER FLOWS:
- [OFN SO Edit User Flows 20170212.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/770032/OFN.SO.Edit.User.Flows.20170212.pdf)

SCOPE (TBC):
- Homepage (logged in)
-- Alert User that an SO within current OC is editable
-- Provide link to Edit Cart page
- Edit Cart page (https://github.com/openfoodfoundation/openfoodnetwork/issues/1084)
-- *Waiting to test current build of this feature in Staging1*
-- User can add/delete/modify SO items to current order
-- User can cancel current SO order
-- [TBC] User can update delivery/pickup location for current order
-- [TBC] User can update payment type for current order
-- User can add non-recurring items to order
- My Orders page
-- User can access current open SOs
-- User can access future/upcoming SOs [Future]
-- User can access fulfilled orders (which may include SO items)
- Email announcing SO is open for editing
-- Provide link to Edit Cart page

OUT OF SCOPE:
- Shopping Cart dropdown (https://github.com/openfoodfoundation/openfoodnetwork/issues/1086)

ASSUMPTIONS:
- User has previously setup a SO with Shop
- Shop has allowed customer SOs to be editable
- User has SOs only with the one Shop (likely use case)

**Comment by myriamboure** [comment]
Edit cart flow has been described precisely here https://github.com/openfoodfoundation/openfoodnetwork/issues/1461 and we gonna review it carefully, the other things in this issue will have to go through solution design and priorization process before going back to github, so I'm closing that issue now.
