### ISSUE TITLE
Standing orders - restrict payment methods available for standing orders

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1391]

**Comment by oeoeaio** [comment]
Probably not worth doing until #1466 and #1080 are done

**Comment by sigmundpetersen** [comment]
Could this also be unblocked if #1080 is @daniellemoorhead ? #chainreaction

**Comment by sigmundpetersen** [comment]
Ping @sstead here as well ☝️

**Comment by sstead** [comment]
Yes, this is done. When creating or editing a SO you only see Stripe or cash payment methods.

**Comment by daniellemoorhead** [comment]
@sigmundpetersen #chainreaction 😆 

![Alt Text](http://www.gifbin.com/bin/032014/1396280184_chain_reaction_of_150_mousetraps.gif)
