### ISSUE TITLE
Deleting a Order Cycle should not delete Schedules

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1397]
Expected: You can delete a schedule by clicking on the delete button

Actual: The button deleted both the Schedule and the Order Cycle. If this is the expected behaviour User should be warned that both will be deleted. [Update] Delete from within the SO modal deletes the schedule. I clicked the delete/rubbish bin icon next to the OC/Schedule row in list which appeared to delete both.

*Issue spotted by Yuko

**Comment by oeoeaio** [comment]
Schedules weren't actually being deleted, they were just being orphaned. I fixed this by preventing OC from being deleted if it is linked to a schedule. Once the link to the schedule has been removed, the user is free to delete the OC.

**Comment by sstead** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/10843056/24182924/1d4b2354-0f19-11e7-924e-93fe53dc433d.png)

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018
