### ISSUE TITLE
In Create New OC, the schedule field should have a dropdown arrow and hint text

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1398]
Expected: Go to create an order cycle. There should be a new field called schedules.

Actual: New field is a dropdown select, should be displayed as such with a down arrow and 'please select' as hint text.

![image](https://cloud.githubusercontent.com/assets/10843056/22269999/e02174fa-e2e1-11e6-9f7c-c00ce2eee767.png)

*Issue spotted by Yuko

**Comment by oeoeaio** [comment]
This component uses Select2, and as far as I can see, the convention is only to use a dropdown arrow if the component is not a multi-select (ie. multiple items can be selected).

I have added a placeholder: "Please select..." to give a prompt, but I think I will leave it there for now.

**Comment by sstead** [comment]
Done 
![image](https://cloud.githubusercontent.com/assets/10843056/24183148/a567953c-0f1a-11e7-8f41-cf6378cca5fd.png)

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018
