### ISSUE TITLE
Separate multiple schedules in OC table with a comma

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1399]
Expected: On the OC admin page, in the schedule column, any schedules selected in the add OC interface should be listed next to the OC.

Improvement: Multiple schedules listed beside OCs need to be comma separated. They are difficult to distinguish from each other as links.

![image](https://cloud.githubusercontent.com/assets/10843056/22270157/6fc456ae-e2e2-11e6-9c8b-e76dd457411c.png)

*Issue spotted by Yuko

**Comment by sstead** [comment]
Done 
![image](https://cloud.githubusercontent.com/assets/10843056/24183049/bfa5107e-0f19-11e7-8243-c9e59aea79a2.png)

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018
