### ISSUE TITLE
When creating a standing order for a customer, there is a typo in 'postcode' field

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1400]
Expected: I can select payment and shipping methods that are active

Improvement: When entering address, there's a typo in the postcode field.

![image](https://cloud.githubusercontent.com/assets/10843056/22270254/daf37310-e2e2-11e6-9215-a708aa001e2f.png)

*Issue spotted by Yuko

**Comment by sstead** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/10843056/24183473/ae9296a0-0f1c-11e7-8cc1-91393316af65.png)

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018
