### ISSUE TITLE
Disallow creation of standing orders with 0 products in them

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1402]
Expected: You can search for and select which items will be in this SO and in what QTYs.

Actual: I was able to save a new SO with 0 items in it.

*Issue spotted by Yuko

**Comment by daniellemoorhead** [comment]
Error happens when you hit save so the disallowing actually does happen, but need to look at doing this error earlier in the flow.

**Comment by sstead** [comment]
Done - in both the Add Products and Review & Save stages, i can't proceed unless there are products in the SO
![image](https://cloud.githubusercontent.com/assets/10843056/24183525/0949f64c-0f1d-11e7-807b-730e9ac7bfbd.png)
![image](https://cloud.githubusercontent.com/assets/10843056/24183547/2f064d18-0f1d-11e7-9029-f68b1c42e529.png)

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018

**Comment by sstead** [comment]
Duplicated here https://github.com/openfoodfoundation/openfoodnetwork/issues/2462
