### ISSUE TITLE
Subnavigation within admin is inconsistent

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1404]
Green sub-navigation in 'Orders' section disappears for Standing Orders. Not all the same filters apply and perhaps the QuickSearch is enough? 

![image](https://cloud.githubusercontent.com/assets/10843056/22277070/ad67d722-e30c-11e6-9850-dfbef06f8c54.png)

![image](https://cloud.githubusercontent.com/assets/10843056/22277077/b43723aa-e30c-11e6-8615-844154ec7e48.png)

*Issue spotted by Yuko

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018
