### ISSUE TITLE
Make possible to edit Standing Order start and edit dates in dropdown

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1406]
Expected: Start and end dates can be edited in dropdown. 
                     
Actual: I could only edit Shipping and Payment by clicking the SO edit button on the RH side – instruction implies it would happen by dropdown

*Issue spotted by Yuko

**Comment by oeoeaio** [comment]
I think I would like to put this on hold for now, pending some user testing and thinking about the best interface for altering the date limits on a standing order...
