### ISSUE TITLE
Clarify if cancellng standing order, or just one order

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1408]
Expected: The order will remain on your standing order list, in the state 'cancelled'

I had some confusion between cancelling a SO and cancelling an Order as both can be done from the page.
Also when an order is cancelled in this view, the button now shows 'Resume Order' when hovered over - however clicking it doesn’t do anything…

![image](https://cloud.githubusercontent.com/assets/10843056/22277331/c5da94f0-e30e-11e6-9ac7-301e9513154e.png)

*Issue spotted by Yuko

**Comment by daniellemoorhead** [comment]
@oeoeaio can you clarify if this needs to be done and add an estimate if so. If not put in leftovers epic.

**Comment by sstead** [comment]
Individual orders can now be cancelled, and resumed. This was tested going from the state of pending to cancelled to pending again.
![image](https://cloud.githubusercontent.com/assets/10843056/24183864/ee3b41c4-0f1e-11e7-8513-51f079660b26.png)
 I need to further test what happens if you go from In Cart to cancelled and is then resumed again.

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018
