### ISSUE TITLE
Improve order cancellation email (to Customer)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1409]
Recommendation: Should include the shop/hub/producer name, list of items in the cancelled order and a contact point if they want to follow up.

![image](https://cloud.githubusercontent.com/assets/10843056/22277373/0ec79e88-e30f-11e6-9e1f-8ce0cdcdeeb1.png)

*Issue spotted by Yuko

**Comment by sstead** [comment]
Update - Cancelation emails are still this ugly.

**Comment by sigmundpetersen** [comment]
@daniellemoorhead is this really a part of a Subs epic?

**Comment by daniellemoorhead** [comment]
probably not @sigmundpetersen but I'll ley @sstead answer that :)

**Comment by myriamboure** [comment]
Closing as reopened a new issue specifying a bit more the case https://github.com/openfoodfoundation/openfoodnetwork/issues/2910
