### ISSUE TITLE
Items removed from Standing Order for unknown reason

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1410]
Expected: When an order cycle opens, the system is triggered to create an order for this standing order, and the shop admin can now see it in their 'Listing Orders' page. It will be in the state 'complete' and any items in the standing order that ARE NOT in the order cycle will have been removed.

Feedback: The order was created however on the Customer side, one item was removed (no inventory) but the other was also removed (inventory on demand). 
*Issue spotted by Yuko

**Comment by oeoeaio** [comment]
Note to self, this is covered by #1078, and recognition of stock from inventory still seems to be an issue. Testing notes there.

**Comment by sstead** [comment]
I haven't seen this so closing for now.
