### ISSUE TITLE
SO should show as 'in cart' until finalised

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1411]
Expected: When an order cycle opens, the system is triggered to create an order for this standing order, and the shop admin can now see it in their 'Listing Orders' page. It will be in the state 'complete' and any items in the standing order that ARE NOT in the order cycle will have been removed.

Also shouldn’t the SO status be ‘Cart’ until the OC closes? Allowing the Customer to amend their SO if needed?

*Issue spotted by Yuko

**Comment by sstead** [comment]
Done - open SOs show as 'Cart'
![image](https://cloud.githubusercontent.com/assets/10843056/24273925/3d0a8f7a-1079-11e7-9f33-93183a6aed26.png)

**Comment by sstead** [comment]
This is not done yet

**Comment by myriamboure** [comment]
Closing as replaced by https://github.com/openfoodfoundation/openfoodnetwork/issues/2879
