### ISSUE TITLE
Standing order caused on hand level to go to -1

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1412]
Inventory for item (Enoki mushrooms) = 0. When the OC opened, SO was completed (inc. sending email to Customer) and inventory was set to -1

![image](https://cloud.githubusercontent.com/assets/10843056/22277533/719a1fee-e310-11e6-8504-19b6612ba4d6.png)

*Issue spotted by Yuko

**Comment by oeoeaio** [comment]
Can't seem to replicate this one. Not sure if I've inadvertently fixed it somewhere else, or if I am not doing the right thing to replicate...

**Comment by oeoeaio** [comment]
Ping @yukoosawa. I know it's a long shot - but if you can remember steps to reproduce that would be super helpful...

**Comment by yukoosawa** [comment]
@oeoeaio Sorry I missed your ping! From memory (and it's a bit hazy) I had set the shop inventory to 0 for Enoki mushrooms and then put in an SO for 2... When the OC opened I received the confirmation email but noticed inventory was now -1.

I was definitely testing this before the additional tickets for amending an order + receiving an email if my order COULD NOT be fulfilled were pushed to staging.

It's very possible it is no longer an issue :)

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018

**Comment by sstead** [comment]
I'm closing this as I can't reproduce it anymore
