### ISSUE TITLE
Treatment of standing order with zero items included - fees still charged

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1414]
If a Customer has a SO setup with no items/products - they are still sent an order confirmation email.

My test scenario was the following:

Shop/Producer
1. Create SO for customer with 1 item
2. Pickup fee for SO is cash $10 (which I understand for pickup would likely not be a real charge - I just happened to create it this way)
3. In SO list page I delete item from customer SO (now = 0)
4. New OC opens (which the SO is attached to) and email is sent

Customer
1. Receive order confirmation email
2. I am being charged $10 for pickup with no items

Issue: Looks like if there is a delivery fee associated with the SO, the Customer is being charged even if 0 items will be delivered.

![image](https://cloud.githubusercontent.com/assets/10843056/22278007/36407b74-e314-11e6-9e97-cdc25c5ed2bd.png)

*Issue spotted by Yuko

**Comment by yukoosawa** [comment]
@daniellemoorhead @oeoeaio Adding another display gremlin to this ticket. If an SO item is unavailable due to 0 inventory - it displays in the 'edit cart' page (https://github.com/openfoodfoundation/openfoodnetwork/issues/1084) with the option to delete.

It would be helpful to the user/customer if they were presented with a message similar to the SO/OC open email: Unfortunately, not all products that you requested were available. The original quantities that you requested appear crossed-out below.

![staging1 ofn edit cart 0 standing order items](https://cloud.githubusercontent.com/assets/19785399/23108812/bb2098c6-f6e0-11e6-82f1-2ffbd602a386.png)

**Comment by sstead** [comment]
This is the email confirmation received by a customer whose SO items are not available (on hand = 0)
Fixed - Shipping fees aren't lingering.
Bug - The enterprise fee ($10/order) has remained in the order.
Suggestion - change the subject. The word confirmation sounds like it all went according to plan.
![image](https://cloud.githubusercontent.com/assets/10843056/24184208/e82f142a-0f20-11e7-8033-335e4a495756.png)

Regarding Edit Cart - it wasn't included in this Staging episode, so I haven't yet tested if on hand = 0 items show there.

**Comment by sstead** [comment]
This is somewhat related...
![image](https://cloud.githubusercontent.com/assets/10843056/24274783/a5980932-107e-11e7-963f-fc952307235e.png)

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018

**Comment by sstead** [comment]
Checking which issues are still outstanding

**Testing Notes**
Outstanding
- The only thing outstanding is that currently shop managers can save a subscription with zero in it. They're prevented from saving a sub with no items in it, but they can save a sub with an item at 0 QTY. We should prevent this. 

Fixed
- Orders with no stock, or insufficient stock are correctly calculating fees and the email chain going to customers is logial.

https://docs.google.com/document/d/1-wY8SwWVOTy1gAQnC49Gbiud6puAJFtL8wKtwH1LVpQ/edit#heading=h.b7iqn1rqo5bu

**Comment by sstead** [comment]
Here's the outstanding issue - https://github.com/openfoodfoundation/openfoodnetwork/issues/2462
