### ISSUE TITLE
Map does not work in Explorer

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1416]
On UK production there are no enterprises showing up on the Map when viewing on Internet Explorer 11. It also freezes when you try to zoom in. 

It is working fine in Chrome and Firefox.

**Comment by Duende13** [comment]
http://stackoverflow.com/questions/27261346/custom-svg-markers-wont-display-in-ie-11

with IE11 and svg images two required bits seem to be scaledSize and optimized.

**Comment by daniellemoorhead** [comment]
Hi @Duende13 when looking for advice on GH probably worth @mentioning people so they know to look at it. There are so many issues on here :)

@oeoeaio and @mkllnk and @RohanM any issues with what Suzanna has outlined above?

**Comment by myriamboure** [comment]
Put s3 in severity as doesn't affect "most users" but probably a few of them. Discovery though is a non-critical feature (but important) that is not working for some users, so could be s2 @lin-d-hop what do you think?

**Comment by RachL** [comment]
I'm closing this one #cleanup. Let's reopen if we still have IE11 users / decide it is a browser we want to support.
