### ISSUE TITLE
Photo needs fixing on UK production in Explorer

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1418]
The photograph on the [hubs case study page](https://openfoodnetwork.org.uk/shops/signup
) is not displaying correctly when viewed in Internet Explorer 11. 

Displayed in Internet Explorer
![image](https://cloud.githubusercontent.com/assets/19837861/22298040/0675f6a0-e317-11e6-96eb-9c3f1b47e208.png)

Displayed in Chrome
![image](https://cloud.githubusercontent.com/assets/19837861/22298067/217c4940-e317-11e6-8d48-956f48b709ca.png)

**Comment by sineadfenton** [comment]
Hey All,

Have done some testing on this in IE11 and it is still an issue where the picture continues to render incorrectly.

It seems like this might be a wider issue given the comments in #1475. Do we think this is something that one of the newer developers can look into?

Cheers,

Sinead

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Photo Display](https://trello.com/c/kiI8xLSh/41-photo-display)

**Comment by daniellemoorhead** [comment]
@sineadfenton is this still a problem? If so it needs to be triaged with the new bug severity rating system we're using (https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity). Ta 😄

**Comment by lin-d-hop** [comment]
My feeling is this is not a global issue. Still an issue for UK but a minor one. Moving to UK trello
