### ISSUE TITLE
Localise business details on UK Production

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1419]
New enterprises are still being asked to enter ABN / ACN numbers when setting up. These need changing - 

ABN to Company Number
ACN to Charity Number

These appear at step 4 in the registration process, and on the Business Details tab in the Enterprises page in Admin.

**Comment by lin-d-hop** [comment]
@OliverUK I'd like to train you to make these changes.... Do you have time Friday?

**Comment by lin-d-hop** [comment]
Solved with #1423
