### ISSUE TITLE
"To order" and "On Demand" labels - only use one or the other or use "unlimited"

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1421]
Lynne to show Oliver how this is changed

**Comment by OliverUK** [comment]
@MagsHall @NickWeir63 
Lynne has just shown me how to make these sort of translation changes. Are you ok if I change the above and call them **unlimited**? As a user this terms for me explains better what the tick box does.

Here are the places where, as far as I know, these labels appear.
![screen shot 2017-01-27 at 15 37 33](https://cloud.githubusercontent.com/assets/17590921/22376615/a45b1040-e4a6-11e6-9d56-3636acdccdfb.png)

![screen shot 2017-01-27 at 15 38 36](https://cloud.githubusercontent.com/assets/17590921/22376637/b5d31156-e4a6-11e6-8346-472b190bca5d.png)

![screen shot 2017-01-27 at 15 39 30](https://cloud.githubusercontent.com/assets/17590921/22376663/d1b76ffc-e4a6-11e6-9ce6-8e47166bd563.png)

![screen shot 2017-01-27 at 15 40 01](https://cloud.githubusercontent.com/assets/17590921/22376689/ee020a28-e4a6-11e6-8b8a-f64c82f62443.png)

**Comment by MagsHall** [comment]
Yes, 'Unlimited' makes much more sense to me too! Go for it.

**Comment by NickWeir63** [comment]
Fine by me too.  Thanks for doing it

**Comment by OliverUK** [comment]
![screen shot 2017-02-01 at 17 30 59](https://cloud.githubusercontent.com/assets/17590921/22518410/63951e5a-e8a4-11e6-94d8-63dae0c0f580.png)
![screen shot 2017-02-01 at 17 31 28](https://cloud.githubusercontent.com/assets/17590921/22518411/639b3736-e8a4-11e6-8b06-d13b0f1264a5.png)
![screen shot 2017-02-01 at 17 31 46](https://cloud.githubusercontent.com/assets/17590921/22518412/639d6f9c-e8a4-11e6-91ce-19c2c45b3ea5.png)
