### ISSUE TITLE
ABN and ACN Make no sense in UK

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1423]
Can we change to Company Number and Charity Number please?
ABN = Company Number
ACN = Charity Number

**Comment by pmackay** [comment]
Are these actually useful or important things for us to capture in the UK?
Or should their visibility be configurable based on locale, and just hidden
for non-AU countries?

**Comment by lin-d-hop** [comment]
They are non-conpulsory fields. I don't think its worth the dev time right now. Do u think its important?

**Comment by pmackay** [comment]
I dont think its that important. Just a shame from UX PoV to ask for stuff
we dont need. But its a decent hack to remove the acroyms that make no
sense in UK :)

**Comment by NickWeir63** [comment]
One of the new Anglesey producers complained that they confused her.  Is it a lot of work to hide them for the UK instance?

**Comment by lin-d-hop** [comment]
@nick surely she wont be confused if we go with the changes oliver has already made⁣?

**Comment by NickWeir63** [comment]
No - good point - that should solve it
