### ISSUE TITLE
[aus production] Excon::Errors::SocketError in db2fog:clean

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1429]
## Error in OpenFoodNetwork

**Excon::Errors::SocketError** in **db2fog:clean**
end of file reached (EOFError)

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=5892a4f8e3d3821100c722ba)

## Stacktrace

    /home/ubuntu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/openssl/buffering.rb:182 - sysread_nonblock

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=5892a4f8e3d3821100c722ba)

**Comment by mkllnk** [comment]
This error happens only every few weeks, but it made me aware that the database cleaning is not working properly. Trying to run it manually, tries to delete old backups and fails silently.

```sh
RAILS_ENV=production bundle exec rake db2fog:clean
```
```
[fog][WARNING] fog: the specified s3 bucket name(db-backup_ofn_production) is not a valid dns name, which will negatively impact performance.  For details see: http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html
^Crake aborted!
Interrupt: 
[..]
Excon::Errors::NotFound: Expected(200) <=> Actual(404 Not Found)
excon.error.response
  :body          => ""
  :headers       => {
    "Content-Type"      => "application/xml"
    "Date"              => "Thu, 02 Feb 2017 05:36:33 GMT"
    "Server"            => "AmazonS3"
    "Transfer-Encoding" => "chunked"
    "x-amz-id-2"        => "4s...Mn9D0="
    "x-amz-request-id"  => "FAD...902"
  }
  :local_address => "10.244.3.155"
  :local_port    => 57188
  :reason_phrase => "Not Found"
  :remote_ip     => "52.216.81.51"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
```

It fails to delete files in a subfolder like `pre-20140710/dump-openfoodweb_production-201312171601.sql.gz`. Since there are a lot of files, each execution of `db2fog:clean` runs for hours and tries to delete the same files over and over again. These long runs make it more likely that an IO error happens as reported by Bugsnag. The causing failure to delete files is not reported by Bugsnag.

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::SocketError** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=58a26fda186bd9110028e586)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::Timeout** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=58acfbfa8917d41100c1c478)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::SocketError** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=58afa004e4815811002f280e)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::Timeout** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=58cb4fe436f4cb1200d5b0a0)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::Timeout** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=58cf49ac47fdb017009bba41)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::InternalServerError** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=58db20e40079a91700e708f9)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::InternalServerError** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=590d442af04d2b00189fa651&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::Timeout** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=593e08881a8e9b00188df59e&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::InternalServerError** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=594740ad1a25070018759c3c&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::Timeout** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=5965969e631f870018cab349&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::InternalServerError** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=5983e33bf1823d0017351bb1&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::Timeout** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=59950855d501eb001969d2da&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Excon::Errors::Timeout** in **db2fog:clean**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/584f61491aeffcbdf8e3a547?event_id=5997ac5cc049c6001790f449&i=gh&m=ra)

**Comment by RachL** [comment]
hello @mkllnk is this problem still happening?

**Comment by mkllnk** [comment]
No, closing this.
