### ISSUE TITLE
Add Roo gem

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1430]
Find here: https://github.com/roo-rb/roo

Adds the ability to read in csv and other spreadsheet formats into Rails.

**Comment by pmackay** [comment]
For what purpose? Shouldnt this be part of a feature story?

**Comment by lin-d-hop** [comment]
Patience there cowboy. I'm making an epic as we speak.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley You need to add the Gemfile.lock for the deployment server.

_remote: You are trying to install in deployment mode after changing your Gemfile. Run `bundle install` elsewhere and add the updated Gemfile.lock to version control._

**Comment by Matt-Yorkley** [comment]
Included in main feature.
