### ISSUE TITLE
Update Products report to ensure all fields for import are included

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1434]
Products report can also be used as a base file for import.
Therefore all fields that can be updated in import should be included in this export file.
The report does not need to be limited to these fields, all existing fields are also fine.

Fields:
- Supplier*
- Product name*
- Product description
- Variant dame
- Price*
- Stock level
- Product categories*
- Unit type (eg grams)*
- Unit value (eg 400)*
- Display as (eg 400g)
- Shipping category
- Image path
- Tax category
- Available date
- SKU
- Group buy
- Bulk unit size
- Properties

(*) denotes required field in product import. Not relevant to this report though.

**Comment by myriamboure** [comment]
This will need to be thought better in iteration iteration 2, as the header in reports are translatable, and not in the import spreadsheet. So for now we leave that in a sandbox and we'll see.

**Comment by myriamboure** [comment]
@lin-d-hop now that we have the csv templates downloadable, users can easily export their data if the want through a report and just match with the template. Do you think there is a case that show the need for reports to be used as a based for product import?
If I export, change a whole column, and then reimport I can do that as well by matching with csv, no? Shall we wait for the need to appear before investigating more on that side for iteration 2 of product import? Tell me what you think. IMO it's not necessary and I would close and wait for the need to emerge.

**Comment by myriamboure** [comment]
@lin-d-hop following comment above I'm closing this issue as I think we don't need it anymore. If you disagree just raise your voice :-)
