### ISSUE TITLE
Update Inventory report to ensure all fields for import are included

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1435]
Inventory report can also be used as a base file for import.
Therefore all fields that can be updated in import should be included in this export file.
The report does not need to be limited to these fields, all existing fields are also fine.

Fields
- Supplier*
- Product name*
- Prices
- In stock?
- On demand?
- Tags
- Hide?

**Comment by myriamboure** [comment]
This will need to be thought better in iteration iteration 2, as the header in reports are translatable, and not in the import spreadsheet. So for now we leave that in a sandbox and we'll see.

**Comment by myriamboure** [comment]
Same question here @lin-d-hop if you agree with me please close those two issues directly ;-)

**Comment by myriamboure** [comment]
@lin-d-hop following comment above I'm closing this issue as I think we don't need it anymore. If you disagree just raise your voice :-)
