### ISSUE TITLE
Product Import v1

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1444]
Epic to capture implementation of product import functionality.

Full phase 1 specification captured here: 
https://docs.google.com/document/d/1PB4OBpnhvINPXr4F2qfmUcjl8Ug3nyVh-6v7UokBNiI/edit#

Upon completion users will be able to import products and inventory from a data file for any enterprise they have appropriate permissions. Users will be able to create or update products/inventory from multiple suppliers within a single file, and to multiple inventories on a single import. Fresh imports can be viewed via an overview before import, then edited via Bulk Product Edit page or Inventory page after import. Users can use a range of default values on imports. Clear error messages will be communicated to users. 

Within the scope of this epic, improved image upload functionality will be added to Bulk Product Edit page.

IMPORTANT - Be sure to merge features as they are implemented. This feature should not be enabled in menus until completed. However it can be implemented and accessible via URL such that features can be continuously merged as we go.

Project board to follow the pipeline for that epic: https://github.com/openfoodfoundation/openfoodnetwork/projects/20

**Comment by Matt-Yorkley** [comment]
Very handy Railscast on implementing CSV import with Roo gem: http://railscasts.com/episodes/396-importing-csv-and-excel

**Comment by Matt-Yorkley** [comment]
Weight/volume based fields:

**unit_value** (_int_, example: 500)
**unit_description** (_str_, examples: "g", "kg", "T", "mL", "L")
**variant_unit** (_enum_, "weight"|"volume"|"items")
**variant_unit_scale** (_float_, examples: 0.001 for millimetres. Required if variant_unit = "weight" or "volume")
**display_as** (_str_, example: "500g". Used if variant_unit = "weight" or "volume". Usually null, unless necessary)
**variant_unit_name** (_str_, example: "large bunch". Required if variant_unit = "items")

Example **variant_unit_scale** values: 

grams (g) = 1
kilograms (kg) = 1000
tonnes (T) = 1000000
millilitres (mL) = 0.001
litres (L) = 1
kilolitres = 1000
litres = 1

As far as I can tell, the **unit_description** gets worked out based on **variant_unit_scale** and can be left empty...? And **display_as** can be left empty as well, by default it becomes the calculated **unit_value** multiplied by **unit_scale** plus the **unit_description** string, ie "500g", but it can be overridden if desired.

**Comment by Matt-Yorkley** [comment]
Creating a new product from a hash where all the weight/volume values are not empty but also are not valid numbers (eg "?") and then calling product.valid? returns **true**... and only returns **false** if the values are empty :(

**Comment by Matt-Yorkley** [comment]
Note: enterprise names are case sensitive, so the **supplier** field on any spreadsheets will need to be case sensitive.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bulk Upload/Download](https://trello.com/c/u2NMz4Se/33-bulk-upload-download)

**Comment by myriamboure** [comment]
I worked  on the new flows after discussion in Barcelona, here they are, need to review the stories now.

**Comment by kirstenalarsen** [comment]
Hi - any chance of a brief summary of Barcelona discussion and implications? Where are we at with this - when can we have it!? Do we have a way to move through the clash with Spree Upgrade?

**Comment by myriamboure** [comment]
Is there really a clash with Spree upgrade @Matt-Yorkley ? @kirstenalarsen we listed all the remaining things to be done with Matt and it is his priority one. We are simplifying a lot the first release as there was far too much in it and many UX issues. You will see all in the slides I shared above.

**Comment by daniellemoorhead** [comment]
Hey @myriamboure @Matt-Yorkley I'm sitting with @sstead and she's super excited about the possibility that product import v1 is almost done!

Are we correct in our assumption that only #2490, #2459, #2458, and #2481 are left in terms of functionality and then all that's left is the user guide #2454? Or are #2161 and #2162 also required?

**Comment by myriamboure** [comment]
I need to check with @Matt-Yorkley on the two things in the backlog yes. Will ping him ;-) But we are getting closer yes!

**Comment by RachL** [comment]
I've left the remaining issues (out of the re-definition of the scope) in tech debt backlog only for now. Closing this epic!
