### ISSUE TITLE
When manager add an order in back office, inventory prices not taken into account

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1446]
A hub manager is using the inventory option for BtoB shop, he uses it to set up different prices for business clients.
After he had closed the order cycle, he receives an email of a client who is late but would like to pass an order. He goes into the back office, "orders", "add new" to capture the order of the client and send him a confirmation. BUT ... the prices that appears are not the one of the inventory, and the wrong prices appear in the order and in the order confirmation that he sends to his client.

I told him as a work around to reopen the OC, pass the order and close it, but that's not ideal, take more time, and when the shop is open it can be confusing if there is another OC at the same time and people connect to buy, they would see both, etc.

Example with the product "pamplemousse":
![screenshot from 2017-02-08 09-33-42](https://cloud.githubusercontent.com/assets/8135376/22729792/870b1494-ede4-11e6-9dc3-25fd9ccaf70b.png)

In inventory:
![screenshot from 2017-02-08 09-54-40](https://cloud.githubusercontent.com/assets/8135376/22729817/a3a1fcee-ede4-11e6-951c-7862f605ff2a.png)

**Comment by myriamboure** [comment]
Did anyone have the same issue @sstead on your side? @lin-d-hop ?

**Comment by sstead** [comment]
@myriamboure  yes this is happening on Aus Production. This is quite an urgent bug, @lin-d-hop can anyone in the UK take a look?

**Comment by lin-d-hop** [comment]
@stveep or @Matt-Yorkley - Do either of you have a moment to look at this? Would be a useful contribution to the global core, though not affecting UK while we aren't making use of inventories much.

**Comment by sstead** [comment]
Potentially related...
This order was put through the front end. The price calculated was correct, but on viewing the completed order the $2 displayed in the 'price' column (for the two grapefruit items) is the Product price,, whereas it should show the Inventory price. The total for this order is correct, it's just the display in this column that is incorrect.
![image](https://cloud.githubusercontent.com/assets/10843056/23289540/7f1104d0-fa9e-11e6-9240-be3e078ccaff.png)

**Comment by sstead** [comment]
The Inventory price is showing correctly now.

There is an issue with On Hand values not reading from Inventory though.
![image](https://cloud.githubusercontent.com/assets/10843056/26238843/26d95044-3cbe-11e7-867a-43edde21dec2.png)

Also, the manager creating an order can add 'hidden' products, when they shouldn't really be able to.

**Comment by oeoeaio** [comment]
Ok, this is an existing issue, I am going to push #1575/ #1527 through anyway. I'll pick this stock stuff up as a separate issue.
