### ISSUE TITLE
CSA/buying group: enable to see the list of buyers for an OC

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1447]
Specs are being discussed here: https://community.openfoodnetwork.org/t/csa-buying-group-enable-to-see-the-list-of-buyers-for-an-oc/804

**Comment by RachL** [comment]
Reading the discourse post, I think this is now enabled in reports. If I'm mistaken, anyway this is a discussion that must be held in discourse now. So I'm closing this.
