### ISSUE TITLE
Error message gives superadmin address instead of OFN address

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1449]
On UK production, If I try to create a hub using a name that is already claimed, I get an error message telling me to contact spree@example.com. This is the super admin login, but I don't think the email goes anywhere. 

Can we change this to hello@openfoodnetwork.org.uk? Or would it be simpler to change the superadmin address to hello@... ? 

![error message spree email](https://cloud.githubusercontent.com/assets/19837861/22785305/a3984824-eecb-11e6-9b30-40dae9a1d331.png)

**Comment by lin-d-hop** [comment]
@MagsHall This error is saying the current owner of the enterprise is spree@example.com.
I don't think we have to worry about this error. The only enterprises that spree@example.com owns are test enterprises and I'm assuming you're creating another test enterprise.

**Comment by MagsHall** [comment]
oh aye, I didn't read the message properly there! You're right. Scrap this.
