### ISSUE TITLE
Missing GB translations breaking enterprise form

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1450]
This issue just showed up today, I havn't seen it before. Various fields in enterprise form are broken due to missing GB translations (in UK development environment). When editing an existing enterprise, a number of the fields get wiped by this bug, which means you can't save properly.

![screenshot from 2017-02-10 12-34-01](https://cloud.githubusercontent.com/assets/9029026/22827014/837e3662-ef8d-11e6-8ba4-59fb2a02e692.png)

**Comment by Matt-Yorkley** [comment]
![screenshot from 2017-02-10 12-39-26](https://cloud.githubusercontent.com/assets/9029026/22827121/18a4cdbe-ef8e-11e6-801f-e0884f84faec.png)

**Comment by Matt-Yorkley** [comment]
![screenshot from 2017-02-10 12-49-06](https://cloud.githubusercontent.com/assets/9029026/22827384/87672fb6-ef8f-11e6-9d5d-df3f651690e8.png)
![screenshot from 2017-02-10 12-49-46](https://cloud.githubusercontent.com/assets/9029026/22827386/8b892eaa-ef8f-11e6-99d0-8b582852c7d2.png)

**Comment by Matt-Yorkley** [comment]
This might effect other countries as well?

**Comment by lin-d-hop** [comment]
@mkllnk  88dea0f doesn't seem to have been picked up by Transifex. I thought there was a webhook to pick up when en.yml changes.... or was that more of a hope?
I don't have any permissions in Transifex so all I can see if that en-GB.yml looks totally up to date, which it isn't :-)

**Comment by mkllnk** [comment]
@lin-d-hop Sorry, I probably forgot to update the transifex branch. We should really automate this. I just didn't have time. I now pushed master there, which is not ideal either, but that should contain all new stuff. Transifex should pick it up within one day. It retrieves the source file straight from Github.

**Comment by lin-d-hop** [comment]
@mkllnk Automating the transifex process (both picking up changes to en.yml in transifex and committing changes to locale files back to github) would be a really useful feature to add to the multilingual work. Do you have an idea of how long it would take? If not... let's talk estimates of estimates :-)

**Comment by mkllnk** [comment]
The implementation just a few hours. Between 2 and 5 I would guess. More interesting is the process. It could be annoying if Transifex would trigger a new commit to master. For example while we have something in staging, we don't want any new commits. Otherwise we have to merge and stage again.

- Step 1: Discuss the current manual process and possible automation on Discourse.
- Step 2: Implement it.

**Comment by lin-d-hop** [comment]
Thanks @mkllnk I'll get that discussion going then :+1:

**Comment by lin-d-hop** [comment]
Here it is:
https://community.openfoodnetwork.org/t/improving-the-transifex-process/831

Closing this issue as something more appropriate will come out of the discussion
