### ISSUE TITLE
Improve products UI

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1452]
There are a number of fields relating to products that can currently be edited manually in the **edit product** UI that are actually quite complex in how they relate to each other. 

This complexity is handled really well in the **create product** UI by providing a dropdown that maps things like "kg" to "1000" and "mL" to "0.001" for the `variant_unit_scale` field. There are similar (related) issues with how the `display_as`, `variant_unit_name`, and `unit_value` fields are used conditionally or used in calculations for values.

Currently users can edit these values directly, which I think can break things in some circumstances, or produce confusing results in others.

As most of the functionality is already present in the create product form it should be fairly straightforward to include it in the edit product forms.

![screenshot from 2017-02-13 15-17-01](https://cloud.githubusercontent.com/assets/9029026/22889442/1677b3a6-f201-11e6-9109-3a02042d7293.png)

Values for 250ml item:

![screenshot from 2017-02-13 15-27-27](https://cloud.githubusercontent.com/assets/9029026/22889448/1aecdf7e-f201-11e6-9623-63c6e4e83fc8.png)
![screenshot from 2017-02-13 15-29-53](https://cloud.githubusercontent.com/assets/9029026/22889563/7e5c9d10-f201-11e6-8693-06b93c81d116.png)

**Comment by Matt-Yorkley** [comment]
This ties in to #1444 as well: we should probably do something similar with how these same fields are represented in uploaded Product Import files and how they can be converted into the correct values from "human readable" values.

**Comment by OliverUK** [comment]
I have tested this and it looks great. Back office UX makes so much more sense now. I've played with the settings and haven't found any major bugs and it all displays ok in the front. 

The only thing I've found where it can get confusing (and break) is where the unit is "item".
In the variant edit screen the unit description field is left blank. As long as I don't touch it and only use BEP to change things, it's fine. But if I type something into it, I get the buggy results below. I don't know if it would make sense to disable the field in this case?

![screen shot 2017-04-12 at 17 47 28](https://cloud.githubusercontent.com/assets/17590921/24969414/a787ef44-1fa8-11e7-8dc4-acee6f2595f7.png)
![screen shot 2017-04-12 at 17 47 41](https://cloud.githubusercontent.com/assets/17590921/24969413/a785ca7a-1fa8-11e7-923f-c53a0ece98bb.png)
![screen shot 2017-04-12 at 17 48 17](https://cloud.githubusercontent.com/assets/17590921/24969415/a788dd46-1fa8-11e7-8408-b0d24fee0368.png)

**Comment by OliverUK** [comment]
I'm not sure I'd let this hold up deployment and I'm not sure how many people even use the variant edit screen.

**Comment by Matt-Yorkley** [comment]
Ah, thanks @OliverUK. Yes, I think unit description should only apply to "volume" or "weight" items. I've just pushed a quick update, if you want to check it.

**Comment by OliverUK** [comment]
Hi @Matt-Yorkley  
Would it make sense to remove unit description also from other kinds of units? It's still there in weight(g) for example and if I enter anything, the listing produces the same as above, only this time it would say "300g test". I can see there may be rare cases where you would want something added like this (e.g. 300g pack) but it may be more likely people write a g or "grams" in it, making the result "300g g" etc.

**Comment by Matt-Yorkley** [comment]
@OliverUK I think it'd be good to keep it in. It's somewhat useful for specifying "1kg sack" or "250g steak" etc. 

Maybe it needs a placeholder description that gives an example, so people don't end up writing "grams"...

**Comment by Matt-Yorkley** [comment]
@OliverUK Okay, I've added a placeholder to the field.

**Comment by OliverUK** [comment]
@Matt-Yorkley does it need testing again, do you reckon?

**Comment by Matt-Yorkley** [comment]
I think it's fine. 
![screenshot from 2017-04-14 17-38-54](https://cloud.githubusercontent.com/assets/9029026/25049336/4e98436a-2139-11e7-90bb-e5c0d211ce10.png)

**Comment by sstead** [comment]
I saw one very edge case where things got glitchy... it occurs when switching between KG products and ITEM products. The unit description text can linger.

![image](https://cloud.githubusercontent.com/assets/10843056/26390410/ceadc3a4-40a1-11e7-98c8-d053df4cd747.png)

![image](https://cloud.githubusercontent.com/assets/10843056/26390413/d24658f0-40a1-11e7-98eb-2faa82490bee.png)

**Comment by daniellemoorhead** [comment]
@oeoeaio does the bug Sally found above need to be fixed? The PR has been merged...does this mean it's been fixed already? If so, can we close this issue?

**Comment by oeoeaio** [comment]
Sorry @daniellemoorhead I had a comment typed but I didn't post it. I will create new issues for item + description, and unused product fields. Closing this issue now.
