### ISSUE TITLE
Customer bug occurs when user sign up is duplicated

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1457]
Locavore have a closed shop on UK production which is only open to their existing veg box customers. They are creating new users themselves from Admin, adding them to their customer list, then emailing details to their customers with a default password. 

However, one of their new users did not follow the instructions and signed up as a user from the OFN home page using the same email address but creating her own password. This went through without an alert saying the password was incorrect or the email was already used, but she could not access the locavore shop. 

There was still only one user registered for this address, and the user had been correctly added to the locavore customer list - see screenshots below. We tried re-setting the user's password to the default one Locavore had set, but the shop still was not visible. I am not able to delete either the user or the customer from Locavore's list - the latter returns an error saying the customer has orders associated with it, which it does not as the customer cannot access the shop! 

![susan mcnaughton issue](https://cloud.githubusercontent.com/assets/19837861/23062917/c1edac62-f4ff-11e6-961e-78dc4295786c.png)

Locavore have created another account for the user with a different email address for now, and I will encourage shops to get users to create their own accounts rather than enterprises adding them from Admin, but it seems the ability to create users from both ends is causing a bug in the system which might create further problems in the future.

**Comment by myriamboure** [comment]
This is covered by https://github.com/openfoodfoundation/openfoodnetwork/issues/1493 and https://github.com/openfoodfoundation/openfoodnetwork/issues/1494 so closing as duplicates. Should be fixed soon, part one is almost there.
