### ISSUE TITLE
Bulk Edit data loading

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1463]
The Bulk Edit products page has some performance issues that don't scale well. Currently all the data from all products is loaded into the page via angular so the products can be searched and filtered. This needs to be revamped and streamlined.

**Comment by Matt-Yorkley** [comment]
@rob just a made a quick issue for this, so that it's visible. I'm quite interested in having a go at it, but maybe it's best left to someone with more experience?

**Comment by oeoeaio** [comment]
I'm happy to leave up to you guys in the UK to schedule in as you see fit. Happy to assist and code review as required. The index page that I am most happy with to date is probably the OrderCycles index page (in the `standing-orders` branch), so perhaps that is a good place to look for inspiration if you're talking about a complete rewrite of the fetch/update logic...

Anyway, let me know if/how I can help...

**Comment by lin-d-hop** [comment]
Great! @Matt-Yorkley this is a lower priority than data import but something we can def talk about scheduling in...

**Comment by lin-d-hop** [comment]
This is being looked at in the Performance epic. No value added by this issue
