### ISSUE TITLE
Stripe: allow logged in customers to store the credit card details they enter at the checkout for later use

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1466]
The StripeConnect gateway I have set up is pretty much the StripeGateway copied from the latest version of Spree, and I have then added a few bits to configure it for use with Connect. 

As it currently stands, I have it working with Stripe tokens requested via Stripe.json the checkout page, which are then used by the StripeConnect gateway to make charge requests on behalf of connected stripe account (shops).

The next phase is to get it to store credit card details for later use. Firstly from the checkout (this issue), and later by explicitly entering card details in a separate form: #1456.

### Storing card details

Most of the data model components required for this to work already exist in Spree, we just need to do a little bit of tweaking to get them to play together properly.

The StripeConnect gateway is already creating instances of `Spree::CreditCard`, and storing card info against these. The problem is that the process of storing the information is a bit broken. For starters, the `Spree::Payment#create_payment_profile` is not really set up for storing cards that are represented by a token (`source.gateway_payment_profile_id`), as is requires `source.number` be present before calling `payment_method.create_profile`. Assuming we override this the main remaining problem is configuring the StripeConnect gateway to conform to Stripes fairly strict process for doing what we want to do: store card details against a customer on the platform's stripe account, and then charge the same card on behalf of a connect account (shop).

In the case where a customer is entering and wanting to store credit card details for the first time, this means we have a fairly complicated process, as we need to ping Stripe in four separate requests:

1. Submit the card details using Stripe.js from the checkout page, get a token back.
2. From `Spree::Gateway::StripeConnect#create_profile`: use the token to store the previously submitted card against a new Stripe customer, get a Stripe `customer_id` and `card_id` back. These are stored against the existing Spree::CreditCard model as `gateway_customer_profile_id` and `gateway_payment_profile_id` respectively. 
3. Request a NEW token, which can be used to make a new charge. We can't reuse the existing token because is has already been 'used', pass this 'new' token needs to be returned from `Spree::Gateway::StripeConnect#options_for_purchase_or_auth`.
4. Submit a charge request on behalf of a connected Stripe Account (ie. that belonging to the enterprise user).

NOTE: If we were not charging on behalf of a connected account, we could just submit a charge request using the customer_id and card_id received in step 2, without doing step 3, but that is not what we are doing.

In the case that we are using an *existing* credit card stored in a Spree::CreditCard object with a `gateway_customer_profile_id` and a `gateway_payment_profile_id`, we should just be able to do steps 3 and 4 to make a charge...

### Loading stored cards

Unfortunately our version of Spree is a little behind the times: instances of the Spree::CreditCard model have no user_id attached. I guess they were just for record keeping at the current point. In version 2.3, the ability to reuse credit cards was introduced, by linking each one to a user (customer). Existing CreditCard instances could then be pulled up and used to create new charges without re-entering card info.

Commit here: https://github.com/spree/spree/commit/d470b31798f37e82645bad0d6938fdd4655e3164

If we can do more or less the same thing, we should be able to coax Spree to show existing credit cards for a given OFN user in the checkout, which will enabled us to just submit a source_id and type with the checkout form: `source_attributes: { id: [card_id], type: 'Spree::CreditCard'}` (untested, but something like that), thus bypassing Stripe.js

**Comment by oeoeaio** [comment]
How do you feel about tackling this @stveep?

I've pushed a spike here: https://github.com/oeoeaio/openfoodnetwork/tree/stripe-connect-spike

See the last commit.

**Comment by stveep** [comment]
Yep I can have a go at this

**Comment by stveep** [comment]
I pulled in the credit card model from future Stripe and added a drop-down to show and choose previous cards (see PR against your spike). I guess we should add a "New Card" default option to the menu, and disable the other card input fields if a saved card is selected - let me know if you have any strong feelings about the UI!

I'm not sure exactly what to do next...I guess we need to go down a different route where the `source_attributes` are set depending on whether this is a new card or a re-use of an existing one - in which case we feed in to your step 3 above?

**Comment by oeoeaio** [comment]
Thanks! Looking good. Comments on PR :)

**Comment by daniellemoorhead** [comment]
What's the PR number for this @oeoeaio? It doesn't seem to be connected to this issue, or referenced. Is it all in #1468?

**Comment by sauloperez** [comment]
@oeoeaio can you turn that detailed description of the design into a wiki doc or something alike? it's essential to have it available for future reference as we work on the payment gateway.

**Comment by oeoeaio** [comment]
@sauloperez Yep! Added a new issue to the [Stripe Connect](https://github.com/openfoodfoundation/openfoodnetwork/projects/3) project: #1733
