### ISSUE TITLE
Rephrase error message in create new product

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1467]
A user said they found this error message confusing... The term 'variant' is not very meaningful to users, so perhaps we should not use it in customer facing messages.
![image](https://cloud.githubusercontent.com/assets/10843056/23281903/20bba582-fa73-11e6-9f84-64052beb0dc5.png)

**Comment by luisramos0** [comment]
this is not a transifex job in en_AU, the string "variant unit name" is not translatable. "variant unit" is also not translatable btw.
