### ISSUE TITLE
Remove separate Enterprise Terms of Service link from config

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1470]
@Matt-Yorkley @lin-d-hop 

Following on conversation from #1211

Just use the existing terms of service link in "Footer Links" config for registration ToS

**Comment by daniellemoorhead** [comment]
Moved this one to v1.8.9 milestone, not sure where it's at (currently in backlog, not ready in time for release).

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley we'd like to put this into 1.8.9 next week, reckon you can do what you need to do to get it ready for that? Otherwise we can drop it into 1.8.10.

**Comment by Matt-Yorkley** [comment]
@daniellemoorhead Okay, it's on my to-do list.

**Comment by Matt-Yorkley** [comment]
@daniellemoorhead Done.
