### ISSUE TITLE
Formatting on Groups Page

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1471]
On the groups page producers with long names drop onto a new line while to bulk of the table has little content.
Can we readjust the column widths such that more space is given to the enterprise names?

![groupsnewline](https://cloud.githubusercontent.com/assets/8669848/23453303/c6e48ace-fe5f-11e6-80cf-54dd4841e55b.png)

**Comment by OliverUK** [comment]
@lin-d-hop I can't find a build to test

**Comment by sstead** [comment]
Looks all good in groups and main directories
![image](https://cloud.githubusercontent.com/assets/10843056/26714735/381ef2d4-47b6-11e7-929b-6522e313658d.png)

**Comment by lin-d-hop** [comment]
Merged. Closing :-)
