### ISSUE TITLE
Can't highlight text in map search field - moves map instead

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1472]
so if I want to highlight text to delete / replace I can't do it, and need to manually backspace - annoying

![image](https://cloud.githubusercontent.com/assets/2911176/23472011/855e58be-feff-11e6-82ae-c9b4e89c82f2.png)

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/discovery/1177
