### ISSUE TITLE
Report Filtering - minor feature broken

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1473]
![screen shot 2017-03-03 at 09 17 27](https://cloud.githubusercontent.com/assets/17590921/23545282/a0a94482-fff2-11e6-838e-b46fcb0c0a64.png)

The calendar buttons no longer work on this screen. It's possible to type in dates but it won't accept dashes so you have to leave them in and only change numbers. Not a big deal but very confusing initially.

**Comment by myriamboure** [comment]
They don't work either on the order cycle page anymore.

**Comment by myriamboure** [comment]
It seems that you can click on the calendar icon when the field is empty, but it fill it in with an undefined date:
![screenshot from 2017-06-21 11-07-19](https://user-images.githubusercontent.com/8135376/27376487-9c20ffbe-5672-11e7-8724-7443e88f6793.png)
This happens in reports and in order cycle bulk page
![screenshot from 2017-06-21 11-12-09](https://user-images.githubusercontent.com/8135376/27376497-a9408fc0-5672-11e7-8412-a202f6fa632a.png)

This is annoying some users in France, adding priority on it.

**Comment by myriamboure** [comment]
@lin-d-hop is this going to be solve with the UI-grid work ? Do you know when it should be ready ? So that I can discuss with the user who is annoyed by that and check if it's ok for him to wait.

**Comment by sigmundpetersen** [comment]
@myriamboure the ui-grid report is on the June milestone but there seems to be quite some work left on the PR https://github.com/openfoodfoundation/openfoodnetwork/pull/1547 (linked to epic https://github.com/openfoodfoundation/openfoodnetwork/issues/1316) 

@daniellemoorhead do you have any more info on the progress of this?

**Comment by lin-d-hop** [comment]
There is also UX work that needs to be done for the first release of UI-grid reports.

It won't make the June release. I'm working for July.

**Comment by daniellemoorhead** [comment]
Moved relevant issues/PRs to the July release, definitely not in June. Will be doing an audit of the june milestone in the next week so that all can see what will get through.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Order Cycle Customer Totals](https://trello.com/c/zYgi70s3/44-order-cycle-customer-totals)

**Comment by lin-d-hop** [comment]
To update on UI-grids, I am working on having different developers look at this but it's a complex piece of work and our budgets are getting tight. If anyone else can contribute on cobudget it will really help us continue with confidence :-)

**Comment by myriamboure** [comment]
I understand @lin-d-hop I think OFFrance will more likely commit more to Spree upgrade and other big pieces of work that makes our work just hard now (email confim, deletion, internationalisation...), before contributing or launching other big new features. But I keep that in mind, we also do want more flexibility in reports of course. There is a big issue on our side on performance on the reports pages, as an admin I don't even manage to open the order cycle customer page, I got the snail every time (a hub user who has many hubs and transactions has the same issue...). I don't know if UI grid solve that but that is even prioritary for me.

**Comment by RachL** [comment]
I re-tested this and I don't this any issue. So closing it. Please do re-open it if I'm wrong!
