### ISSUE TITLE
W3 Validator giving loads of errors in https://openfoodnetwork.org.uk/shops/signup

### ISSUE THREAD

**Issue by Duende13** [openfoodfoundation/openfoodnetwork#1475]
I was having a look into the issue with ie11  and images going crazy ( #1418 ) and someone point it out that there were too many problems to be sure what was causing the real problem, like end tags div seen but not open elements, attributes not allowed,  etc

The whole list of errors:

http://validator.w3.org/nu/?doc=https%3A%2F%2Fopenfoodnetwork.org.uk%2Fshops%2Fsignup

I found an easy work-around for the problem but just for the record and for the future, it will be good to have a look into these errors.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Photo Display](https://trello.com/c/kiI8xLSh/41-photo-display)

**Comment by lin-d-hop** [comment]
#gitcull
