### ISSUE TITLE
Software release updates can be done by the Super admin through the instance UI

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1480]
Would be so great if Super admins could implement release updates to local instances via their admin interface, kind of like what Word Press do.

![screen shot 2017-03-10 at 1 36 04 pm](https://cloud.githubusercontent.com/assets/10949052/23780608/fda8601a-059b-11e7-8fb2-7e029db04b61.png)

![screen shot 2017-03-10 at 1 36 13 pm](https://cloud.githubusercontent.com/assets/10949052/23780616/0b24a6d6-059c-11e7-9d9a-4c7bade1f611.png)

**Comment by RachL** [comment]
woooow the super cool feature request :D @daniellemoorhead do you agree we should move this to discourse? Not sure if we need to reopen this soon as I don't see it been picked-up as a priority before quite some time. So I'm closing and we should open it in discourse when the need is up again. Feel free to reopen if you disagree :)
