### ISSUE TITLE
Typo in Aus production on /welcome producer page

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1482]
Typo in Aus production on /welcome producer page
![image](https://cloud.githubusercontent.com/assets/10843056/23929040/59e916e2-0977-11e7-997b-3a56d73e0d03.png)

**Comment by jennPeavler** [comment]
Hi there - I was hoping to help fix this issue, it looks like a good bug for a first-time contributor! I noticed this translated string `production_description_text2` doesn't exist in any of the translation files. Curious if anyone knows if we could just delete this text block from the template file (link the file word to the line in the template file)? Any strings that don't exist in the translation files automatically default to the key of the translation (e.g. if you take out `production_description_text` all of the description blocks will display 'Production Description Text') Not sure if this is behavior that could be easily altered or not.
https://github.com/svenfuchs/i18n

Something like this might work:
https://stackoverflow.com/questions/12353416/rails-i18n-check-if-translation-exists

The second solution is likely more robust (don't render the element at all if the translation doesn't exist) and they may already have something in the repo that does the:

ruby
def i18n_set? key
  I18n.t key, :raise => true rescue false
end

Thank you for your assistance.  Hopefully I can fix this issue!

**Comment by enricostano** [comment]
Hi @jennPeavler and welcome to the OFN community!

I'm not sure if this issue is related to https://github.com/openfoodfoundation/openfoodnetwork/issues/1541 and https://github.com/openfoodfoundation/openfoodnetwork/pull/1622

**Comment by daniellemoorhead** [comment]
@mkllnk or @oeoeaio any thoughts on above?

**Comment by oeoeaio** [comment]
Hi @jennPeavler, thanks for looking into this! Unfortunately I believe this issue has just been fixed by #1622.

Interesting idea about preventing translations from appearing at all when no translation key is found. @enricostano @mkllnk any thoughts about whether this is good practice?

**Comment by oeoeaio** [comment]
This is fixed on Aus Production, so closing now.

**Comment by mkllnk** [comment]
Interesting thought. I would definitely keep them in dev and staging environments to make it easier to spot mistakes. Even on production it sometimes happens that missing keys are not noticed, because the key says the same as the translation would. So not displaying it at all would be a downside then. Difficult question. I would leave it for now.

**Comment by mkllnk** [comment]
There was another suggestion of using the i18n-tasks gem to find missing or unused keys: https://github.com/openfoodfoundation/openfoodnetwork/issues/738 I would prioritise working on that over changing the display of missing keys.

**Comment by enricostano** [comment]
Yeah that kind of tool would be nice to explore.
