### ISSUE TITLE
Switch SSL certificate to LetsEncrypt for openfoodnetwork.org.au

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1483]
The SSL certificate on openfoodnetwork.org.au is due to expire in ~6 weeks (3rd May 2017). Switch to using LetsEncrypt to handle auto-renewal.

**Comment by daniellemoorhead** [comment]
@RohanM @kirstenalarsen @mkllnk is it worth adding this to our immediate backlog, given we're likely to be otherwise occupied in May?

**Comment by mkllnk** [comment]
I just did it.
