### ISSUE TITLE
New page for "editing" a complete order

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1488]
Create a new page, where customers can view & make changes to completed order in an open order cycle (where this has been allowed by the shop). This will be heavily based on the cart page, but needs to be a separate view, because loading an order into the cart will erase the contents of the cart if this means switching OCs...

As a customer with a completed order in an open order cycle, I can navigate to a page where:
- [x] I can remove products from the completed order
- [x] I can adjust the quantities of products ordered
- [x] I can completely cancel the order
- [x] I can press a button to save the changes I have made
- [x] If my cart is empty, I can press a button to navigate to the shop, where I can add more products to my cart
- [x] If my cart is not empty, I can press a button to navigate back to my cart

**Comment by sstead** [comment]
Some early bugs spotted...
**Something funny with the date:**
Regarding order ending 634... I just placed this order, it's April 19th, but in transaction history the order shows as occurring on May 19th. The time is correct, 11:12
![image](https://cloud.githubusercontent.com/assets/10843056/25159339/8da87e00-24f2-11e7-92ba-73f3dccdcf69.png)

**Shipping and Payment method fees not showing when editing order**
![image](https://cloud.githubusercontent.com/assets/10843056/25159400/e9452e66-24f2-11e7-95ff-731e76be7ef4.png)

**Comment by oeoeaio** [comment]
Should be fixed:
- Added a 'changes allowed until' alert on the order editing page
- Prevented user from removing the last item of an order, suggests that they cancel the order when they do this. I though this was safer than just cancelling it.
- Changes to quantities on a completed order should now draw from inventory correctly (this was an existing issue in the admin section, which should also be fixed now).
- Changes to quantities on a completed order should now update shipping and transaction fees (this was an existing issue in the admin section, which should also be fixed now)
- 'Back to Cart' and 'Back to Store' buttons are hidden if the cart is set up for a different shop
- Month weirdness with dates showing one month in advance
- Show shipping and transaction fees in the edit form

Still working on:
- Asking for confirmation before cancelling an order

Things I didn't do:
- Show cancelled order in the transaction history (can we make this a separate issue?)
- Prevent the user from leaving the (might have another look at this if I get a chance)

**Comment by sstead** [comment]
Should be fixed:
- Added a 'changes allowed until' alert on the order editing page (YES)
- Prevented user from removing the last item of an order, suggests that they cancel the order when they do this. I though this was safer than just cancelling it. (YES)
- Changes to quantities on a completed order should now draw from inventory correctly (this was an existing issue in the admin section, which should also be fixed now). (NO - Changes to quantities are updating in the correct place, but if the order is cancelled the stock goes back against the product, not to the inventory)
- Changes to quantities on a completed order should now update shipping and transaction fees (this was an existing issue in the admin section, which should also be fixed now) (YES for shipping, yet to test others)
- 'Back to Cart' and 'Back to Store' buttons are hidden if the cart is set up for a different shop
- Month weirdness with dates showing one month in advance (YES)
- Show shipping and transaction fees in the edit form

**Comment by sstead** [comment]
These are now fixed:
- Changes to quantities on a completed order should now draw from inventory correctly (this was an existing issue in the admin section, which should also be fixed now). (YES)
- Changes to quantities on a completed order should now update shipping and transaction fees (this was an existing issue in the admin section, which should also be fixed now) (YES)
