### ISSUE TITLE
Add a new "open orders" section to the account page

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1489]
This section will allow customers to navigate to the new page for editing completed but open orders as per #1488.

As a customer with a completed order in an open order cycle, a can navigate to my account page where:
- [x] I can see any completed orders for any open OCs in a separate section
- [x] I can view details of the orders such as: when the OC closes, the number of items, the shipping and payment methods, and the order and payment totals
- [x] I can click through to "edit" the order where this is allowed by the shop
- [x] I can cancel the order directly from the account page view

Other improvements:
- [x] Implement hash navigation for the accordion elements on the page, so that the user can be taken directly to a particular section within the page?

**Comment by sstead** [comment]
YES- I can see any completed orders for any open OCs in a separate section
This works correctly. Only showing if Edit Orders is allowed.

YES- I can view details of the orders such as: when the OC closes, the number of items, the shipping and payment methods, and the order and payment totals
Date of order is currently incorrect by 1 month, as noted in #1488 

YES - I can click through to "edit" the order where this is allowed by the shop.

YES -  I can cancel the order directly from the account page view.
As noted in #1488, should there be a confirmation before the order is cancelled?

**Comment by sstead** [comment]
Fixed:
"As noted in #1488, should there be a confirmation before the order is cancelled?" - there is an 'are you sure'
Date of order is no longer incorrect.
