### ISSUE TITLE
Alerting customers to the presence of existing auto-generated orders in the current OC

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1490]
As a customer with an existing standing-order-generated order:

- [x] I am alerted to its presence (using a flash notice) when I navigate to the shop page of the enterprise with which it was placed
- [x] I can dismiss the flash notice (do we remember this, and for how long?)

Where more than one such order exists:
- [x] The flash provides a link to my account page, where I can see all my completed orders, as per #1489

Where only one such order exists:
- [x] The flash provides a link direct to the edit order page, as per #1488

**Comment by sstead** [comment]
ISSUE - This also has the date issue (it says May 26 when it should say April 26).
![image](https://cloud.githubusercontent.com/assets/10843056/25163413/8a3fae3a-250d-11e7-8280-fbec575b7b27.png)

**Comment by oeoeaio** [comment]
Should be fixed: 
- Wrong date issue
- Banner showing cancelled items
- Showing time available to alter orders when more than one

I think these things are ok for now:
- Dismissing banner

**Comment by sstead** [comment]
Should be fixed: 
- Wrong date issue (YES)
- Banner showing cancelled items (YES)
- Showing time available to alter orders when more than one (YES)

I think these things are ok for now:
- Dismissing banner
