### ISSUE TITLE
No saving option after deleting tag

### ISSUE THREAD

**Issue by arthur-koenig** [openfoodfoundation/openfoodnetwork#1497]
After deleting a tag (whether it's for a customer, an order cycle or other...) the "save" or "update" button appears at the bottom of the page, but is not clickable. 
After deleting a tag, a user should be able to save changes.
Today, the workaround is not ideal : the user must re-type something in the tag box and delete what he just typed. Only then will he be able to save changes. 
![screen shot 2017-03-23 at 4 38 20 pm](https://cloud.githubusercontent.com/assets/17574782/24256278/0aa81cf0-0fe8-11e7-8838-65c5721647a9.png)

![screen shot 2017-03-23 at 4 41 11 pm](https://cloud.githubusercontent.com/assets/17574782/24256286/1273d82a-0fe8-11e7-9a0d-7a42cd117c65.png)

**Comment by RachL** [comment]
This is working now 🎉 Closing
