### ISSUE TITLE
Disturbing error message if I want to print a receipt and have no printer set up

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1499]
On the "action" menu in the order page, if I clic on "print receipt" (if printing receipt toggle is activated for the instance), and if I have not set up any thermal printer, I have the snales BOOM image.
Would  be better to have a kind pop-in saying "You don't have any printer set up, please set up a printer before you can print a receipt" with a "close" button.

**Comment by myriamboure** [comment]
Same for "choose printer ticket" by the way... it needs QZ to be installed, but would be great to have a kind error message saying that and redirecting to the user guide (still in my to-do to right that page) instead of just the BOOM page...

**Comment by myriamboure** [comment]
Here is the message I get now
![screenshot from 2017-05-16 19-29-59](https://cloud.githubusercontent.com/assets/8135376/26119712/73b6176e-3a6e-11e7-8220-fff91cc3f813.png)

A bit better than the snale, but would be better to have a message saying "You need to install QZ on your computer to be able to print a receipt with a thermal printer. Please see _here_ how to do that." with a link to the user guide page explaining that (which is not yet written, on my todo to make it happen)

**Comment by lin-d-hop** [comment]
#gitcull
Is this more a Translation missing issue?
