### ISSUE TITLE
When creating a product clicking 'On Demand' does not update stock level

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1504]
This seems to be an intermittent problem.

Sometimes when I set a product stock level to 'On Demand' the stock level stays at 0 and the product then fails to appear in the shop front. This is only when creating a product.

I have experienced this myself today and I know that many people experience this as it is a common support complaint.

**Comment by Matt-Yorkley** [comment]
@lin-d-hop Just been trying to replicate this, but haven't managed it so far. I tried creating various different products using volume, weight, and items as the unit type in case that made a difference... 

Any more info to go on?

**Comment by Matt-Yorkley** [comment]
Having stock zero is fine for on demand products though, right? Just did 6 test products and they were all created successfully...

**Comment by lin-d-hop** [comment]
'On demand' should mean that they then appear in the shopfront as stock level is irrelevant.
The issue is that when created with 'on demand' they then don't appear in shopfront as the stock level is zero. The 'on demand' should cancel out zero stock.

**Comment by Matt-Yorkley** [comment]
@lin-d-hop Ahh... so they do appear in the backend, but they don't show up in shops? I'll take another look.

**Comment by Matt-Yorkley** [comment]
Just had another go at replicating this, and new products with `on_demand` all appeared in the shopfront...

**Comment by myriamboure** [comment]
I tried to reproduce but didn't manage, and never had this issue... can you reproduce it ? Never had this issue and we have lots of users with lots of "on demand" products...

Else @lin-d-hop I propose to close this in favor of https://github.com/openfoodfoundation/openfoodnetwork/issues/698, which should cover it (and if relevant switch to s2, but else we can also choose to pick up some annoying s3 and prioritize them if we have no s2). Please reopen if you disagree.
