### ISSUE TITLE
Rights to choose thermal printers refused to non super admin user

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1510]
When testing on the French staging to print thermal ticket after we did the upgrade of the last release, their is a right issue that prevent the user to choose a printer in order to print the receipt.
@ltrls has found the issue (something new he has discovered on OFN, he is going through his learning curve !!! Say you love it Pierre, hein? ;-)) so we are going to test his new branch on our staging and make sure everything is ok, and pull the fix before tomorrow.
Ping @daniellemoorhead for info.

**Comment by daniellemoorhead** [comment]
Hi @myriamboure hoping as you create these issues you can fill in the meta on the right hand side of the screen? ie. Assignees, where it is in the pipeline, any labels (suggest 'france', and 'aus review' when you want us to look at something) and priority. With all the issues and PRs coming in at the moment it will make it easier for me to triage and figure out AU team priorities each week. Thanks! 😄

**Comment by daniellemoorhead** [comment]
PS. @ltrls can you please assign yourself to isses/PRs that you're working on? I can't assign you as I don't think you've accepted the invitation to join the repo. Thanks!
