### ISSUE TITLE
Deselecting shipping or payment methods in Manage enterprise list doesn't work

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1517]
I'm Managing my shop enterprise that has shipping and payment methods already setup. I unclick the tickbox next to a shipping/payment method in the 'enable' column to turn 'off' the shipping method. I click save. I get the banner saying that my enterprise has been updated, but in Shipping/Payment methods I still see the method I just deactivated is still active. If I want to deactivate it I need to 'edit shipping/payment method' and remove the enterprise there- which is difficult because if the method is only applied to one enterprise, you can't save the method with no enterprise selected. Thus you'd need to delete the method.

![image](https://cloud.githubusercontent.com/assets/10843056/24535063/8fba887a-161d-11e7-98e2-212fe8256144.png)

The opposite works fine - If I'm selecting to enable a shipping/payment method that is currently deactivated.

**Comment by yasirazgar** [comment]
Looking into it

**Comment by sauloperez** [comment]
Great @yasirazgar ! keep 'em coming!

**Comment by myriamboure** [comment]
I'm closing this for now as after investigations from various devs we will need a whole project/new feature to solve this. Kept track of this original issue and this connected PR in the icebox item: https://community.openfoodnetwork.org/t/hubs-manages-without-friction-shipping-and-payment-methods-and-can-grant-permissions-on-them/1269

**Comment by yasirazgar** [comment]
@myriamboure @sauloperez I think we can merge this pr https://github.com/openfoodfoundation/openfoodnetwork/pull/1979 for this issue and resolve it. 
Though its related to, https://github.com/openfoodfoundation/openfoodnetwork/issues/2023, it fixes uses case mentioned in this issue. 
What do you guys think?

**Comment by myriamboure** [comment]
@yasirazgar if I read again on the PR (too long discussion there!) Maikel in one of the latest comments said "I resolved the issue with the missing menu items. But Sally discovered another bug. If you actually uncheck a method now, it doesn't just deactivate the method, but it completely disappears unless other enterprises are using the same method. Only super-admin can bring that method back. I think we need to address that issue first." So this is very annoying and prevent us to merge #1979 as yes it's fixing the pure described case but introducing another bug which is even more annoying, which is that the method disappear if you manage to uncheck it... so we can't merge it unfortunately :-( I'm so sorry! Does any of the other issues I proposed you can fit you? By the way are you on our Slack? https://openfoodnetwork.slack.com Maybe it would be great if you wanted to join our Slack, if you want to get a bit more involved...

**Comment by yasirazgar** [comment]
ok @myriamboure, I am not in openfoodnetwork slack yet, can you please invite me, my email:  yasirazgar@gmail.com.

**Comment by myriamboure** [comment]
Invitation sent @yasirazgar looking forward to see you there!
