### ISSUE TITLE
Allowing customers to view already ordered items for the same OC in the cart

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1523]
And navigate to a page where they can edit such orders if this is allowed.

**Comment by sstead** [comment]
This is what it looks like in the dropdown, the edit cart page and checkout...
![image](https://cloud.githubusercontent.com/assets/10843056/25163138/66fb728a-250b-11e7-937b-5dc7f58d8209.png)

ISSUE- this is capturing cancelled orders
![image](https://cloud.githubusercontent.com/assets/10843056/25163160/93c0395e-250b-11e7-8927-8c217014234b.png)

**Comment by oeoeaio** [comment]
All of this should be fixed now.

**Comment by sstead** [comment]
Just checking these things are fixed...
- ISSUE- this is capturing cancelled orders (YES)
- ISSUE - there's an inconsistency in how items are counted. This is minor but would be nice to be consistent. (YES)

Not done, and probably not a priority...
- Suggestion for the Order Confirmation Page...regarding turning the Save button to grey if someone's just checked out.

**Comment by oeoeaio** [comment]
@sstead, the save button should be disabled and slightly faded out when no changes have been made (ie. when an order has just been confirmed or after the order is saved). Is this not happening?

Should look like this before:
![screen shot 2017-05-10 at 12 11 37 pm](https://cloud.githubusercontent.com/assets/2067859/25880305/f84e4bbc-3579-11e7-9ce4-91f4ec7a595a.png)

And like this when there are changes that need to be saved:
![screen shot 2017-05-10 at 12 13 02 pm](https://cloud.githubusercontent.com/assets/2067859/25880327/1a519f70-357a-11e7-9698-95871680fe15.png)

**Comment by sstead** [comment]
@oeoeaio Yes sorry it's done

**Comment by sstead** [comment]
Done
