### ISSUE TITLE
Supplying producer can view Reports tab, but gets Snail Page (something went wrong)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1526]
On Aus production, if I'm logged in as a producer who only sells through a hub (I don't manage the hub, just supply to it), when I'm in my dashboard I can see the Reports tab, but when I click on it I get the Snail Page.

![image](https://cloud.githubusercontent.com/assets/10843056/24784804/5f4b688c-1b98-11e7-94ed-4939c67c4a6c.png)

**Suggested fixes...**

**Easy suggested fix:**
- If a user has no permission to view any reports, then don't show the Reports tab in the menu.

**Harder (but better) suggested fix:**
- There are some reports that this user would find very useful. Perhaps we can have a reports tab that is filtered to show very limited data to such a user.

Two reports I know would be useful to some people... 

The producer should be able to download a Order Cycle Customer Totals Report - but showing only the lines which relate to them. This is helpful in cases where the hub wants the supplier to bring products pre-packed by customer, ready to be put in customer boxes. Of course, there would be other cases where the hub doesn't need the supplier to know which customers ordered their products. I'm not sure what privacy protocol would be?

Another one that would be useful... order cycle supplier totals, showing just the totals for the one supplier (not identified by customer). This would allow supplying producers to login and view their cumulative orders for each product during the order cycle. We've had a few hubs who have had to email producers manually to give them such an update, or click the 'notify producers' button in OC which is not ideal.

Note- producers who are profile only can also see and click the reports menu item (and they get the snail). For these users, who aren't supplying hubs, the Reports tab should just be removed entirely

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suppling Producer Report Error Page](https://trello.com/c/8MFa84xs/70-suppling-producer-report-error-page)

**Comment by oeoeaio** [comment]
Technical explanation of what is going wrong in #1734
