### ISSUE TITLE
Inconsistency issue in test environment

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1533]
Hi,

with @Em-AK we discovered that if a dependency (`spree` gem for instance) changes some [default configuration](https://github.com/openfoodfoundation/spree/commit/c594d6111b0c7e4fafe03b548748049bf5a7b28a) we still get the old value since is cached in `tmp/cache/paralleltests` directory. As a result we were getting different results for some test in Travis CI and our local environment.

This was introduced by https://github.com/openfoodfoundation/openfoodnetwork/commit/bc11140a40762a69a68dbde4617c9ca1c9097575

In our case it took 3 days and 2 people to nail the issue and detect a somewhat brittle solution: running `bundle exec rake tmp:clear`.

@RohanM @oeoeaio @Matt-Yorkley do you have any idea on how to make this more robust?

EDIT: steps to reproduce:

 - running `./spec/controllers/spree/api/products_controller_spec.rb:38` in `master`
 - switch to `spree-upgrade-4` from https://github.com/Em-AK/openfoodnetwork
 - run `bundle install`
 - run the same spec again

You can go back and forth from the 2 branches and it will break the caching in `test` environment.

**Comment by enricostano** [comment]
Just wanted to add that you can also run `rm -rf tmp/cache/paralleltests/* && bundle exec rspec` as a workaround....

**Comment by sauloperez** [comment]
To me something that leaves left overs behind which can affect other test executions sounds pretty bad. We need to either investigate that parallalel test thing in-depth or find another solution.

**Comment by enricostano** [comment]
It's not only related to parallel test IMHO

**Comment by enricostano** [comment]
Moved to icebox: https://community.openfoodnetwork.org/t/enforce-consistency-between-ci-development-and-test-environments/1159

**Comment by lin-d-hop** [comment]
This has an ice box. Why did it get reopened here?

**Comment by sigmundpetersen** [comment]
Yeah I wonder if we treated these tech wishlist items differently than product wishlist. But I agree to close and only use Discourse wishlists for these as well.
