### ISSUE TITLE
Name the profile editing space 'Enterprise Settings'

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1535]
When talking to users or writing in the User Guide, I find it difficult to refer to the 'profile editing section' or 'profile managing area'. This place (see below), doesn't really have a short sweet location name. Users often aren't clear on where this place is, and I think a clearer name would help with this.

![image](https://cloud.githubusercontent.com/assets/10843056/25157810/ecba4a24-24e6-11e7-8481-1049241de860.png)

We've decided that **"Enterprise Settings"** is the preferred name.

@oeoeaio @kirstenalarsen @anyone else

If we agree to rename this place, here's the changed that would need to be made:

![image](https://cloud.githubusercontent.com/assets/10843056/25157910/b570eed2-24e7-11e7-8a0d-59b72adead27.png)
Note: choose "Settings"

![image](https://cloud.githubusercontent.com/assets/10843056/25157913/ba80d680-24e7-11e7-8922-b8120046125a.png)
Note: choose "Settings:"

**Comment by oeoeaio** [comment]
Cool, I'm happy with either of those suggestions. I guess this job is basically just setting up translations that allow the buttons and the title to be set. @daniellemoorhead should we lock down a spec for this and stick it in `rubiesfornewbies`?

**Comment by sstead** [comment]
We're overhauling the user guide and it'd be great to start using new terminology.

**Comment by daniellemoorhead** [comment]
@myriamboure @enricostano @sauloperez @lin-d-hop @NickWeir63 @sigmundpetersen what do you think of this idea?

**Comment by sauloperez** [comment]
Being picky, I lean towards "settings". It feels to me like a more appropriate term and aligned with most of the SASS out there.

**Comment by sigmundpetersen** [comment]
"Enterprise Settings"?

**Comment by myriamboure** [comment]
Good idea anyway, I don't really care about "settings" or "configuration" as we are going to translate it anyway ;-) But I hear more often "entreprise settings"

**Comment by daniellemoorhead** [comment]
@sstead based on the feedback did you want to make a decision?

**Comment by sstead** [comment]
Ok cool, "Enterprise Settings" is fine

**Comment by kristinalim** [comment]
The enterprise index page for admins has a different set of action links:

![20180720132627-admin-enterprise-index-links](https://user-images.githubusercontent.com/2243/42984733-a150a4dc-8c20-11e8-94ab-d4801d846ba1.png)

I think these small, related changes should be done as well:

1. **Also rename the "Edit Profile" link to "Settings".** This leads to the same "Settings" page as the one for enterprise users. This way, the admin also clicks a "Settings" link to go to the "Settings: Sample Enterprise" page.
2. **Add divider above "Payment Methods".** The links "Payment Methods", "Shipping Methods", and "Enterprise Fees" lead to tabs within the "Settings" page.

Are you okay with above?

**Comment by kirstenalarsen** [comment]
@kristinalim I'm ok with the above - @myriamboure @sstead ??

**Comment by sstead** [comment]
Yes looks good thanks

**Comment by myriamboure** [comment]
Yep looks good awesome @kristinalim ! Go for it!

**Comment by daniellemoorhead** [comment]
Hey again @kristinalim can you also assign yourself to any issues you pick up? Do you have the right permissions to do this?

**Comment by kristinalim** [comment]
@daniellemoorhead Thanks for assigning me to the issue! :-) I don't have permissions to do that myself, because I'm not yet a certified contributor yet as far as I understand.
