### ISSUE TITLE
Issue in "change pack" option 2 not displaying

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1541]
Open 2 description is the same as option 1 and a text "producer description text 2" appears. On v 1.8.9 deployed on the French staging.
![screenshot from 2017-04-20 15-03-24](https://cloud.githubusercontent.com/assets/8135376/25232188/bf69ca1e-25da-11e7-8a50-fb720392516a.png)

@pacodelaluna is it connected to something you have done with translatability or not?
@sstead do you have the same issue in Australia ? So that we know if it's connected to the translation process...

**Comment by sstead** [comment]
Hey @myriamboure , yes, we are also having this issue...
![image](https://cloud.githubusercontent.com/assets/10843056/25259975/a75207b8-268c-11e7-9635-d6c4a836fa4e.png)

**Comment by myriamboure** [comment]
@pacodelaluna do you think that's something Claire could work on? Is it easy enough for her to start ?

**Comment by myriamboure** [comment]
@sstead @clairezed is fixing that, it was a bad key, can you confirm what text need to display here in the producer shop ?
There are two possible text in Transifex:
> sell_description_text
Sell your products directly to customers through your very own Open Food Network shopfront.
or 
> sell_description_text2
A Producer Shop is for your produce only, if you want to sell produce grown/produced off site, select 'Producer Hub'.

Shall we put both one after the other so that both display ? It sounds logical to us... thanks for confirming !

**Comment by sstead** [comment]
Yes, I believe initially both these sentences were displayed, and the user guide screenshot confirms this....
![image](https://user-images.githubusercontent.com/10843056/26859284-067812d4-4b7a-11e7-9165-0a57b4d880a5.png)
Thanks :)

**Comment by myriamboure** [comment]
Awesome, I think you can push your PR @clairezed :-)

**Comment by myriamboure** [comment]
@clairezed I think your PR was ready on that, am I right ? Sally answered and it confirmed what we had worked out last week. Let me know if any question ;-)

**Comment by enricostano** [comment]
> a text "producer description text 2" appears

This is because the i18n key `producer_description_text2` does not exists. I added more insights in the related PR.

**Comment by daniellemoorhead** [comment]
@myriamboure and @clairezed the PR for this issue was merged so feel free to close this one :-)
