### ISSUE TITLE
Firefox insufficient stock available alert message loop in /cart page

### ISSUE THREAD

**Issue by jeronimo** [openfoodfoundation/openfoodnetwork#1543]
In `/cart` "Edit your cart" page when clicking `up` on `input type="number"` on Firefox and when the "insufficient stock available" message dialog pops up - it gets into loop and can't get rid off it until page reload.

<img width="582" alt="screen shot 2017-04-20 at 14 38 25" src="https://cloud.githubusercontent.com/assets/88912/25233628/618599e4-25d7-11e7-9def-94e1d543f924.png">
In this particular case it is visible that quantity goes down to 6 automatically and gets back to 7.

OSX. Firefox 52.0.2.

It should go down to 6 as it does in Chrome browser.

**Comment by mllocs** [comment]
Looks that this is not happening anymore in Firefox 53

![](http://g.recordit.co/T8Yfz5SB2y.gif)

**Comment by daniellemoorhead** [comment]
@jeronimo can you check if you still get the same problem, and if resolved close this issue?

**Comment by RachL** [comment]
@daniellemoorhead I've checked as well and didn't see the problem anymore. I'm closing this and if the problem happens again we can reopen ;)
