### ISSUE TITLE
Update text on Australia's welcome emails - translations

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1553]
This is the first email you get when registering...
![image](https://cloud.githubusercontent.com/assets/10843056/25647029/cae7ec3c-3001-11e7-947c-11ed8515023b.png)

Can we remove the 'Feedback button' part?

**Comment by sstead** [comment]
This is the second email. I think it's ok...
![image](https://cloud.githubusercontent.com/assets/10843056/25647050/f94f5420-3001-11e7-9b57-03bb4247e687.png)

**Comment by sstead** [comment]
This is the email you get after confirming you email...
![image](https://cloud.githubusercontent.com/assets/10843056/25647058/0d091172-3002-11e7-97cd-c21361972efc.png)

Suggested rephrase of text.... (italics is a link or customised text)

Welcome, _Dani_!
Thank you for confirming your email address. _Danielle's Farm_ is now part of _Staging 2_! 
You can manage your account by logging into the _Admin Panel_ or by clicking the cog in the top right hand side of the _homepage_, and selecting Administration.

Support (in blue heading)
Checkout the _OFN User Guide_ for FAQs and setup guides to help you get up and running. If you have any questions, or need assistance please email us at _hello@openfoodnetwork.org_.

Fair Food Forum (in blue heading)
We'd like to invite you to _join the Fair Food Forum_. This online discussion forum is a place where individuals involved in the fair food sector can connect with others, provide peer to peer support and ask questions. There's a wealth of knowledge out there, so check it out!

Learn (in blue heading)
OFN has also compiled a _Learn library_ of resources for the fair food movement. The resources span many of the common issues facing community food enterprises such as finance, marketing, managing volunteers and logistics.

Cheers,
_Staging 2 Team_

**Comment by sstead** [comment]
Password reset email...
Can we add our email 'hello@' so that people don't reply to admin@openfoodweb with their questions...
![image](https://cloud.githubusercontent.com/assets/10843056/25647118/83dd6c6c-3002-11e7-8051-297682ac7f04.png)

**Comment by lin-d-hop** [comment]
Aus is now on Transifex :tada:
