### ISSUE TITLE
Report improvements - Enterprise fee when >1 fee, and tax breakdown by product

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1554]
Two simple report additions that would be helpful

a) If a shop has enterprise fees on >1 enterprise, there's no report that splits out what enterprise fees were gathered by each party. E.g. The hub takes 10% and the delivery service takes 5%. The reports only give a total enterprise fee value. We need to have a line for each fee going to each party.

b) The OC customer totals report doesn't have the tax setting of each product. An Australian user needed to know which items in a hub OC carried GST, and which supplier supplied them. The only way to get this info was a combination of the Xero report (has the tax status) and the OC customer totals (has the producer).

**Comment by tschumilas** [comment]
Having a fees report is something high on Canada's priority list.  Several hubs here are using complex transport arrangements,  and right now have to calculate fees by hand.  How can I help to make this happen? @lin-d-hop  @myriamboure   - do you have any need to isolate fees in your instances?

**Comment by daniellemoorhead** [comment]
@oeoeaio @lin-d-hop @jeronimo is this something we can/should add to the UI grid further work we're doing?

**Comment by kirstenalarsen** [comment]
Fees report is underway - #2673 

No idea how important the request to add tax category in customer totals report is, but I suspect it is something that will need to be solved via https://community.openfoodnetwork.org/t/provide-a-more-flexible-reporting-functionality-with-rich-data-access/1197/7

@sstead - can you make sure that is recorded in the aus feature list and just ping me to let me know who and if you think still relevant so I can follow up with them when we have a solution?

Closing this issue.
