### ISSUE TITLE
Complete Placeholder Creation

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1560]
There remain approximately 83 files that require language string placeholders.

Can these all be replaced and the original translation added to en.yml.

Time Estimate: 8hrs

**Comment by jeronimo** [comment]
There is an issue with Spree Core as it loads model decorators before translations are loaded so validations fail to find translations. There is a fix (https://github.com/spree/spree/pull/7469/files) for Spree 3.0 so it might be solved only after that. 

This happens in situations like `validates :distributors, presence: { message: I18n.t(:spree_distributors_error) }` where translation goes into `Proc`. Temporary solution is to create validator classes or to move validations into methods.

**Comment by daniellemoorhead** [comment]
@lin-d-hop @jeronimo the PR for this issue has been merged so feel free to close this :-)
