### ISSUE TITLE
Replace Open/Closed Icons

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1561]
The "open" and "closed" icons still need to be replaced.
We need to discuss and decide which icons to use.
And we need to replace these icons in the current symbol font.

From @mkllnk via Slack:
Icons are in a font. And we would like an icon that does not contain text. Maybe a first step would be to replace the icon just with a text label. The internationalisation discussion contains a lot of ideas for a symbol that's easy to understand for everyone: https://community.openfoodnetwork.org/t/internationalisation-project-notes/312/59 pp

Hardcode the language set is a viable first option. It can be an improvement later to have an interface for that.

Time Estimate: 6hrs

**Comment by daniellemoorhead** [comment]
Are visual design aspects such as icons worthy of having some @yukoosawa time on?

**Comment by mkllnk** [comment]
That's an excellent idea. We all just came up with ideas, but don't know what the best solution is. If Yuko could come up with a nice design element that uses text separate from a logo that would be great.

**Comment by lin-d-hop** [comment]
Note from Maikel on slack (for posterity):
These symbols are in the custom ofn font created with icomoon.io. The source file is here: https://gist.github.com/mkllnk/5acd096b7d0da97830012068db7f9b56

**Comment by daniellemoorhead** [comment]
Please see remaining work to be done for this issue on PR #1937. @Matt-Yorkley or @sstead it might be worth listing these things out on here so that it's easier to figure it out (unless you're going to quickly do them and send through a new PR Matt, in that case don't worry about it :) )

**Comment by daniellemoorhead** [comment]
Closing this issue as a) the PR has been merged, and b) it's been a while since I added my comment above and so I assume that there's nothing left to do as there was no action.
