### ISSUE TITLE
Map not behaving right on Groups page

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1567]
I have just created a new group for Preston Area Food Hubs but on the map on their page it is showing one of their producers as located in the Atlantic ocean - https://openfoodnetwork.org.uk/groups/preston-area-food-hubs#/map

Their address is entered correctly in their enterprise profile (Langroyd Organics, BD23 3LR) but they don't seem to be showing up at all on the main map.

**Comment by NickWeir63** [comment]
The same happened with 'B Bees' when i tried to add them to the 'Good Food Oxford' group.  I ended up taking them out of the group

**Comment by daniellemoorhead** [comment]
Hey there, this is a duplicate of #1383 so closing this one and will add your detail to it @MagsHall.
