### ISSUE TITLE
Development environment - undefined method `tag_list'

### ISSUE THREAD

**Issue by jeronimo** [openfoodfoundation/openfoodnetwork#1571]
Sometimes I get error `undefined method `tag_list' for #<Spree::Variant:0x007fc2c65bedf8>`
<img width="732" alt="screen shot 2017-05-12 at 15 25 27" src="https://cloud.githubusercontent.com/assets/88912/26002353/47c08e4a-3727-11e7-8ad1-10b5352d1268.png">

Adding `acts_as_taggable` into Spree::Variant decorator seemed to help. Will make pull request later if no one is against it.

**Comment by daniellemoorhead** [comment]
@enricostano? @Em-AK? @RohanM?

**Comment by enricostano** [comment]
I've not been able to reproduce it.

**Comment by myriamboure** [comment]
I propose to close this one as Enrico was not able to reproduce and we just closed the associated PR for the same reason. Will reopen if appear again.
