### ISSUE TITLE
On-hand restrictions for items added via admin section

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1578]
Stock does not seem be restricted for items created in an admin section, where the variant has an inventory override.

![26d95044-3cbe-11e7-867a-43edde21dec2](https://cloud.githubusercontent.com/assets/2067859/26269667/863de6f0-3d39-11e7-9e71-f9a506e994c6.png)

**Comment by lin-d-hop** [comment]
Stock levels are now working for items added in back office.
