### ISSUE TITLE
Bug on prices displayed when in same OC distributors using inventory are mixed with distributors who don't

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1580]
A big French supply 10 buying groups and 1 physical shop. He organizes the sales through 2 order cycles: week 1 he delivers half of the buying groups, week 2 he delivers the other half +  the shop.
Every buying group and the shop have specific "hubs", each one have its own page to order with their specific list of members and are "private shops".
The hub "wholesales" (used by the shop to order) manages an inventory as the prices are overridden.

In the OC week 2, there is a bug on the front end for the hub "wholesales", the prices displayed are not the inventory price.

It seems that an OC cannot handle both hubs that manage inventories and hubs that don't, am I right ?
This is a bug for me that we need to solve, the price displayed should be the inventory price of the hub if the hub runs an inventory.

@sstead can you confirm that this is a general bug and not only me who have missed a specific set up ? Thanks ;-)

**Comment by kirstenalarsen** [comment]
hi @myriam - check that each shop has the read from inventory switch turned on? I think it’s in shop preferences

**Comment by myriamboure** [comment]
That's the issue @kirstenalarsen , the "read from inventory" option is not in the entreprise set up, but in the OC "advanced options"... so you have to turn it on for the whole OC... I checked in "shop preference" and all the enterprise set up options and didn't find it. Is it me who don't find it ? Was it there and it disappeared ?

**Comment by sstead** [comment]
Hi @myriamboure I'm not certain that I understand exactly how your shop is configured and what problem you are experiencing, but I've had a play around and couldn't seem to replicate it.

From what I understand, you want to have a single order cycle, with multiple distributors, and for some of these distributors to set prices in inventory, while some distributors don't use inventory.

From what I can see this is possible...Example below...

![image](https://cloud.githubusercontent.com/assets/10843056/26613293/6c5c2df6-45fd-11e7-85cf-3150367947d9.png)
These two shops are both stocking Citrus items. One shop 'inherits' all prices from the Products, and the other has Inventory 'overrides' on price. 
![image](https://cloud.githubusercontent.com/assets/10843056/26613579/dcc87094-45fe-11e7-9ab9-92c17453dae3.png)

The result is that in the shops I can see that one is charging Inventory prices, the other is charging Product prices.
![image](https://cloud.githubusercontent.com/assets/10843056/26613359/abe67a58-45fd-11e7-94c8-1741e7787d60.png)
What settings are in place to allow this?
- The Producer has permitted 'permission to add to Inventory' to both distributors. One has overridden prices, the other has not.
- Both enterprises are set to allow New products. This doesn't impact on price overrides, just whether or not new products need to be approved.
![image](https://cloud.githubusercontent.com/assets/10843056/26613637/12e98834-45ff-11e7-9924-ea32a4428cc1.png)

Note: the Advanced Setting in Inventory does no control overrides on price and stock level. This setting only restricts WHICH items will show in the incoming section. Price overrides depend on each distributor's Inventory list.
![image](https://cloud.githubusercontent.com/assets/10843056/26613393/eb70b9e0-45fd-11e7-9a6b-4e61b59852e0.png)
If the above is activated, the INCOMING stock will be restricted to ONLY those items which are in the coordinator's inventory. Any HIDDEN items won't show. And if the coordinator's Inventory setting is set to 'hide NEW products' they will also NOT show. 
![image](https://cloud.githubusercontent.com/assets/10843056/26613461/32706fb6-45fe-11e7-81b0-546d25c38716.png)
So, this setting doesn't impact overries, it only impacts whether or not the product will be available in the Incoming section. Price overrides will depend on each Enterprise's Inventory list. 

Does this help? Or is there a bug I'm not seeing?

**Comment by myriamboure** [comment]
Thanks a lot @sstead I'll do the same set up. This is not super intuitive as for the hub manager, the distributors who don't modify the price don't have to use inventory, so they wouldn't have thought to use the inventory. Maybe that's a case to add to the user guide somewhere ? Or Discourse ? But thanks anyway, I think it will solve my issue :-) I close the issue.
