### ISSUE TITLE
Unit description not cleared when switching between kg and items

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1582]
Picked up in #1452. When switching variant_unit between `weight` products and `items`, the unit description text on variants lingers. It should to be removed.

![issue1](https://cloud.githubusercontent.com/assets/2067859/26476359/87be673a-4201-11e7-840a-684a1f4bb883.png)
![issue2](https://cloud.githubusercontent.com/assets/2067859/26476360/891be5b2-4201-11e7-89c9-c86a87713539.png)

## Severity
S3, not affecting so many users I guess and there is a workaround.

**Comment by RachL** [comment]
I just tested this and it is still true.

![image](https://user-images.githubusercontent.com/6525576/54764511-3edaa580-4bf8-11e9-8143-c5add2db1c6d.png)
