### ISSUE TITLE
Stock control malfunctioning when inventory on hand > product on hand value.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1584]
This issue arrises for products which have On Hand quantities overridden in Inventory AND the inventory stock level is greater than the product stock level. What happens is... when the shopper switches between Edit Cart and the Shopfront changing their order QTY for the product, the system doesn't save QTY changes if they change from a value within the Product On Hand allowable range TO a value above the Product On Hand allowable range, but below the Inventory on hand allowable range.

It's interesting because it's not like the product is not adhering to the Inventory stock level at all, because if I try to order more than the Inventory On Hand value I'm told that there's limited stock. This is correct. It's just not saving some changes, and not giving any warning.

Example below. Sorry in advance for how unpleasant it will be to get your head around this...

Here's the product causing the issue:
![image](https://cloud.githubusercontent.com/assets/10843056/26483703/b458bc5c-4231-11e7-822e-6c3253f0ec16.png)

Here's the steps to follow to see the error:
Arrive in shop, and order the following:
•	Button 10
•	Shitake 10
Edit Cart
Both show QTY 10 (CORRECT)
Continue shopping and change...
•	Button 3
•	Shitake 3
Edit Cart
Both show QTY 3 (CORRECT)
Continue shopping and change...
•	Button 10 
•	Shitake 10
Edit Cart
Button 3 (HASN'T SAVED)
Shitake 10 (CORRECT)
Continue shopping and change...
•	Button 5
•	Shitake 5
Edit Cart
Button 5 (CORRECT)
Shitake 5 (CORRECT)
Continue shopping and change...
•	Button 7
•	Shitake 7
Edit Cart
Button 5 (HASN'T SAVED)
Shitake 7 (CORRECT)

**Comment by enricostano** [comment]
@myriamboure could you please check this again? Thanks!

**Comment by myriamboure** [comment]
Quantity on hand disappear in next version of Spree so let's see after Spree upgrade where we are at about that.

**Comment by luisramos0** [comment]
Removing the reference to #2109 and moving it to epic #2584 (all the issues blocked by the spree upgrade).

**Comment by luisramos0** [comment]
I have tested this carefully in both v1 and v2, I cant replicate. I dont think it's related to stock levels or catalog vs inventory. I think this must have a been a problem with moving between shop list page and cart page... I tried clicking quickly in the buttons but didnt get any weird behaviour.
What do you think we should do with this?
I am closing it as I dont see what else we can do about it. Feel free to re-open.

**Comment by luisramos0** [comment]
I forgot to mention: I tested this with both overriding own catalog (get my own product to inventory and overriding it) or some other enterprise catalog.
