### ISSUE TITLE
Email confirmation | User sign up (modal)

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1586]
**Who:** Any user wanting to register on the OFN.
**How they access the sign up process:** via the sign up tab which is accessible via the 'Login' link in the top banner (opens login modal).

-------
**Step 1(a): User signs up**
The new user accesses the sign up tab and submits their email and password.
After submitting the modal will display this text:

![image](https://user-images.githubusercontent.com/10843056/26961273-e36d5cf6-4d20-11e7-91bb-0ca064f9b538.png)

And the following conditions are in place:
-  User remains logged out (new functionality). 
-  They can close the modal and display the original page underneath (existing functionality).
-  The green success banner does not show (existing functionality).

**Step 1(b): User resends confirmation email**
If the user needs the confirmation email to be resent, and clicks on the link in the model (screenshot above), this triggers:
1. The same confirm email to be sent.
2. A message to display below the 'resend email confirmation' saying 'We've resent the confirmation to email address, check your inbox'.

![image](https://user-images.githubusercontent.com/10843056/27938824-f18dc91c-6303-11e7-9970-21143b5d8f5d.png)

-------
**Step 2: System requests email confirmation**
The completion of step 1 will trigger the system to do 2 things:
1. System creates a user record, flagged as unconfirmed.
2. System sends a confirmation email to the user that includes a unique confirm link for that user.

![image](https://user-images.githubusercontent.com/10843056/27938845-19f80f02-6304-11e7-9a82-bf05f5196bf9.png)

-------
**Step 3: User confirms email**
The user clicking on the confirmation link in the email will trigger the following:
1. System flags the user record as confirmed.
2. System sends the user a 'Welcome' email.

![image](https://user-images.githubusercontent.com/10843056/26961185-4cfe0dec-4d20-11e7-825d-7b41c593c0c0.png)

3. Browser window opens and displays the page that they were on when they signed up, with the login tab open with a 'thanks for confirming message' displayed in the login tab. We need to think about the possibility that somebody tries to abuse this feature for unwanted redirects.

![image](https://user-images.githubusercontent.com/10843056/26961028-fe143c0c-4d1e-11e7-9ac4-324073856634.png)

-------
**Step 4: User logs in**
Successful login from this screen will then close the modal and allow the user to continue browsing (existing functionality).

-------

EXCEPTIONS

- If the user attempts to login without clicking on the confirmation link in the email, they will not be able to login and will be directed to confirm (https://github.com/openfoodfoundation/openfoodnetwork/issues/1616)

- If the user tries to create an account using an email that is already signed up on OFN the existing functionality will apply: 
![image](https://cloud.githubusercontent.com/assets/10843056/26711793/4cee6132-47a6-11e7-8c5b-79338acbe771.png)

- If the user is a previous guest checkout, their customer record will be connected (https://github.com/openfoodfoundation/openfoodnetwork/issues/1592).

**Comment by daniellemoorhead** [comment]
There are two outstanding questions in terms of the scope of this work:

- [ ] How to deal with unconfirmed users if they attempt to place an order through the checkout.
- [ ] In the scenario where a user has already put things into their cart prior to sign up, is it possible to have them come back to the website and have these items still in their cart? i.e. end up back at the point in the website they were at when they clicked to sign up and opened the modal?

**Comment by myriamboure** [comment]
@daniellemoorhead I can't see because of a strange light on the picture, but for you the user is logged in when he submits the form and see the green success banner ? I would suggest to avoid that and only log the user when he has clicked the validation link, as this is the desired behaviour we want to implement, we want all new sign up to force email confirmation... is it technically possible to have existing unconfirmed email who are able to login without confirming their email and not enabling log in until the email is validated for all new users ?

**Comment by myriamboure** [comment]
As you wrote for entreprise sign up : "There is the need for a new page telling the user to go to their inbox and click on the confirmation link they receive in an email from OFN."

**Comment by myriamboure** [comment]
- [ ] 1- When sign-up form submitted, email confirmation sent to user + display green “check validation link in mailbox” pop-in/banner
- [ ] 2- Slightly change content for existing email confirmation as not associated anomyre with entreprise creation (see below)
- [ ] 3- When user clicks on validation link, open home page in new tab + send welcome email

Email confirmation proposal: 
Hello !
Your have created an account on [name of the instance - ex: Open Food France]. To complete the account creation, you need to confirm your email by clicking on the link below.
Confirm this email address >> [with hyperlink for validation] 
Cheers,
The [OFN] team

**Comment by myriamboure** [comment]
@daniellemoorhead See https://github.com/openfoodfoundation/openfoodnetwork/issues/1591 for outstanding question 1.

**Comment by daniellemoorhead** [comment]
Success message on modal when user has clicked on confirm link still not done. Is this in another PR?
