### ISSUE TITLE
Email confirmation | User sign up (customer-only shop)

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1588]
**Who:** Any user wanting to access a customer-only shop.
**How they access the sign up process:** the user navigates to the customer-only shopfront and sees this message, and clicks on 'register':

![image](https://user-images.githubusercontent.com/10843056/26864353-000b7b86-4b9b-11e7-8261-76270ca966b4.png)

-------
**Step 1(a): User signs up**
The new user accesses the sign up tab and submits their email and password.
After submitting the modal will display this text:

![image](https://user-images.githubusercontent.com/10843056/27939273-0497fc3c-6307-11e7-82e1-c5de05eaaaf1.png)

And the following conditions are in place:
-  User remains logged out (new functionality). 
-  They can close the modal and display the original page underneath (existing functionality).
-  The green success banner does not show (existing functionality).

**Step 1(b): User resends confirmation email**
If the user needs the confirmation email to be resent, and clicks on the link in the model (screenshot above), this triggers:
1. The same confirm email to be sent.
2. A message to display below the 'resend email confirmation' saying 'We've resent the confirmation to email address, check your inbox'.

![image](https://user-images.githubusercontent.com/10843056/27939289-1aaf1640-6307-11e7-9c8d-14a53794aed0.png)

-------
**Step 2: System requests email confirmation**
The completion of step 1 will trigger the system to do 2 things:
1. System creates a user record, flagged as unconfirmed.
2. System sends a confirmation email to the user that includes a unique confirm link for that user.

![image](https://user-images.githubusercontent.com/10843056/26962724-a3ea18de-4d2b-11e7-87e4-04aed11f24fb.png)

-------
**Step 3: User confirms email**
The user clicking on the confirmation link in the email will trigger the following:
1. System flags the user record as confirmed.
2. System sends the user a 'Welcome' email (same generic email as #1585)

![image](https://user-images.githubusercontent.com/10843056/26962642-eb93c3b6-4d2a-11e7-9468-02464e3ada40.png)

3. Browser window opens and displays the homepage (_Question: can we instead display the page that they were on when they signed up?_) with the login tab open with a 'thanks for confirming message' displayed in the login tab. 

![image](https://user-images.githubusercontent.com/10843056/27939233-c3ddc50a-6306-11e7-9a87-96adac740acf.png)

Once logged in, they system will check if they are on the shop's customer list, and either take them to the shop, or show them the 'contact the shop to be given access' message (this is existing functionality).

-------
**Step 4: User logs in**
Successful login from this screen will then trigger the system to check if they are on the shop's customer list, and either take them to the shop if they are, or show them the 'contact the shop to be given access' message (existing functionality).

-------
EXCEPTIONS

- If the user attempts to login without clicking on the confirmation link in the email, they will not be able to login and will be directed to confirm (https://github.com/openfoodfoundation/openfoodnetwork/issues/1616)

- If the user tries to create an account using an email that is already signed up on OFN the existing functionality will apply: 
![image](https://cloud.githubusercontent.com/assets/10843056/26711793/4cee6132-47a6-11e7-8c5b-79338acbe771.png)

- If the user is a previous guest checkout, their customer record will be connected (https://github.com/openfoodfoundation/openfoodnetwork/issues/1592).

-------
FUTURE IMPROVEMENT TO PROCESS 

It's pretty obvious that the process of getting access to a customer-only shop is a poor user experience. Rather than extending the scope of this issue to include it a separate issue has been created that makes the getting rejected from a customer-only shop less confusing and sad (#1613).

**Comment by myriamboure** [comment]
![img_7905](https://cloud.githubusercontent.com/assets/8135376/26556602/bfb0c0b0-449b-11e7-884f-7f668c6394f8.JPG)

As you can see by the above flow, the change to user sign up process when invited by a customer-only shop, is that users don't need anymore to have an account before they can be (efficientlyl) added to the customer list. When a user tries to access the private shopfront, he has to login or sign-up (following process in #1586 ), and the validated email is matched with the customer list.

Ideally we want to make sure that the user signs up with the same email address that the one in the customer list. I suggest here that we consider it's the role of the hub to remind the user in the notification email with wich email address he is supposed to register.

When signing up, the user sees a page telling her to go to her inbox and click on the confirmation link they receive in an email from OFN. It would be great if there would be a means of getting back to the targetted OFN shopfront page would be awesome... Else at least the OFN home page...

This will solve #1493

**Comment by myriamboure** [comment]
I see two things to develop :
- [ ] 1- Adding a new customer create a new guest account > If email recognized no new account is created
- [ ] 2- When an unconfirmed user connects to a customer-only shop, email confirmation sent to user + message “you need to validate your email to access the shop”

**Comment by myriamboure** [comment]
I retested the whole process and it is all good so I close this issue (https://docs.google.com/document/d/1UXwLF0o4TdQ8SyqoJdp1l70TuNby8ZhZvq12z27C4No/edit?usp=sharing)
