### ISSUE TITLE
Email confirmation | Resending confirmation emails

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1590]

**Comment by myriamboure** [comment]
Do we need a specific Github issue for that ? I listed in every issue when re-send of confirmation email are triggered, but I can try to sum it up here. There are for me only 2 cases where an unconfirmed user needs the confirmation email to be re-sent:
- when he tries to create an entreprise https://github.com/openfoodfoundation/openfoodnetwork/issues/1585
- when he tries to access a customer-only shop https://github.com/openfoodfoundation/openfoodnetwork/issues/1588
- if a user want to access his guest orders history https://github.com/openfoodfoundation/openfoodnetwork/issues/1592

**Comment by daniellemoorhead** [comment]
I created this as a separate thing because it's good practice to break stories down to be as small as possible. I figured that the resend email flow was separate to the inclusion of email verification and so worthy if a separate story/stories. Good agile/lean practice is small batch - small stories, small releases, etc. :)

**Comment by daniellemoorhead** [comment]
Not needed anymore, have created individual issues for each login point (#1615, #1616, #1617, #1618, #1619)
