### ISSUE TITLE
Email confirmation | Linking a registered user to their existing guest checkout orders

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1592]
**Who:** All users on the OFN
**Trigger:** User confirms their email address
**Goal:** To ensure that the enterprise can see the full order history for one email address (user), but protect the previous owner of the email address.

For epic #946, where any user at all has clicked on the 'confirm email address' link in the confirmation email they receive, the system must:
- Check if the email address is associated with any guest checkout orders.
- Where there have been previous guest checkout orders, the associated guest customer record must be linked to the newly registered user.
- The guest order history does not show in the registered user's order history.
- The enterprise can see the linkage between the guest orders and the subsequent registered user orders in their customer list.

Background on the design decision: Enterprises want to see the full order history of a customer. It doesn't matter if the customer was registered or not. It would also be very convenient to show all previous orders to the user. The problem is that we don't know which orders were really performed by the same person. We can't rely on the email address, because:

- People misspell email addresses.
- People change email addresses and email addresses change owners.
- People invent email addresses for guest checkouts that actually exist.

So if we would show all guest orders with the same email address to the newly registered customer, they may see orders that don't belong to them. That breaches the privacy of the person that ordered as guest.

-------
SPIKE
- How easy is this to implement? Will it work out of the box as @oeoeaio says?

**Comment by myriamboure** [comment]
In #917, Maikel suggests that it would be great to keep track of guest orders. Today when a guest becomes a user the previous orders are not shown in the “user account”. We propose to make them available in the user account once guest becomes user.

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley @mkllnk is this functionality part of the work you have done for email confirm?

**Comment by mkllnk** [comment]
No, not part of it. But the confirmation is needed for this.

**Comment by myriamboure** [comment]
@daniellemoorhead there is something I don't understand here, when you say

> To ensure that the enterprise can see the full order history for one email address (user), but protect the previous owner of the email address.

I understand your design proposal but sightly disagree. I see your arguments to say that a guest user -
- might have misspelt the email address used
- or might have used an email, then close his mailbox and then someone else might have open the same email address (I'm not sure that's authorized by email providers though so not sure about that argument)
- a customer might have used a random email and then it happens that the real people using that email creates an account

**BUT here are my objections:**
- If a guest user uses an email that happens to exist (point 3) the real user would have received an order confirmation email and would have write to us saying "I never ordered, how did you get my email, etc." So for me this can't happen, or if it does it woud be a mistake and we would treat it as a mistake.
- If a guest user misspelt her email (point 1) and this misspelt address happens to be a real one and the real user creates an account, we are in the same case as just described. Else there is no issue, she just didn't receive her previous order confirmations, and she wouldn't see when registering the orders made through that error email.
- Point 2 I think is impossibe, I checked and gmail for instance doesn't authorize to create an email address already used by someone else before even if this user has closed it (https://support.google.com/mail/answer/56256?hl=en&visit_id=1-636625089850149575-3195862716&rd=1) so this case for me can't happen.

So for me: "The guest order history does not show in the registered user's order history."  > I disagree, as a new registered user I want to see in my account the past orders I made with that same email address when I was still a guest and had no account.

**So I would simplify that story and just say that:**
- the previous guest records are associated with the new register user
- so manager see all info attached to user
- user see all info in his account

Do you agree @daniellemoorhead ?

**Comment by mkllnk** [comment]
Maybe I can answer some of these questions.

> used an email, then close his mailbox and then someone else might have open the same email address (I'm not sure that's authorized by email providers though so not sure about that argument)

This is possible. Some email providers make the address available straight after deletion, most block it for a few months and some providers (Gmail) block it forever.

> the real user would have received an order confirmation email and would have write to us saying "I never ordered, how did you get my email, etc."

If I received an email like that, I would suspect some kind of scam. Maybe I would mark it as spam, but I wouldn't react to it, because that is how the bad guys get you.

I agree that the cases in which we don't want to associate the data are very rare. But they can happen and we would be doing the wrong thing in these cases. These issues have been real for bigger companies with more customers and therefore more email addresses. For me, this comes down to basic security measures. When you order as a guest, there is no authentication and all data is untrusted. We can display that to the manager for their information, but it's not right to display it to customers.

**Comment by myriamboure** [comment]
Ok I get your points @mkllnk 
Then my question is: can we just consider that all the records from before the account is created remain as guest and are not connected to the new account at all? Is it really a problem for the hub manager if she doesn't see the records associated to that customer? I mean the problems you mention on the user side will be the same on the hub manager side, if the email was used by someone esle the hub manager will see a wrong record associated to a customer.
**SO my proposal is: we don't associate any guest record to new accounts.** And we close this issue :-)
The hub manager will still see the past orders but they will not be associated with the account of the new user. I don't think it's really a problem, if the hub manager filter orders with the email she will see all the orders anyway, so why would she need to have the guest orders formally associated with the customer?

**Comment by oeoeaio** [comment]
I think you're both on the right path, in that we should not associate guest `orders` with new or existing `user` accounts. These should probably remain disconnected as far as the user is concerned.

**Comment by daniellemoorhead** [comment]
@myriamboure, hello 👋 

First thing I would say is I'm not the best point of reference for questioning functionality designed for email confirm. Firstly because it's been a VERY long time since I wrote all this up, and secondly because you guys know the system much better than I do 😁 

So I think go with what @mkllnk and @oeoeaio have confirmed with you. 

The only question I have is about the impact of this on the customer list for the enterprise - will the same email address show up twice, and thus be duplicated if the enterprise emails their customers? And even if this does happen, does it matter? And can enterprises even email their entire customer list?

**Comment by daniellemoorhead** [comment]
And finally, I wonder what Shopify does? Can you guest checkout with their software, and if you then register does it keep the history of your guest checkouts?

**Comment by myriamboure** [comment]
> The only question I have is about the impact of this on the customer list for the enterprise - will the same email address show up twice, and thus be duplicated if the enterprise emails their customers? And even if this does happen, does it matter? And can enterprises even email their entire customer list?

For the enterprise, what will happen is that for one give email, the hub will see that:
![screenshot from 2018-05-25 14-11-09](https://user-images.githubusercontent.com/8135376/40543643-8b2fefae-6025-11e8-85ed-37cc4b8d08a6.png)
Which I agree is not so good... Can't we technically "deactivate"/"archive" the old email (so that it doesn't appear in the  cutomer list and the hub only see the account now that it is created?) But then in case the email is a mistake (one of the three cases above) we would archive an entry that is valid?

Actually I think the only solution to really solve that problem would be to force users to create themselves an account in order to be able to shop :-o 

Probably that's why all websites went in that direction.
Do we want to do that?
Else we need to decide:
- either to accept the risk of reconciliation errors (low) and merge guest records into new user account
- either to accept that there is this strange duplicate in the hub manager "customer" view... 

@sstead what do you think? and @sauloperez ? @lin-d-hop

**Comment by Matt-Yorkley** [comment]
So it looks like the final decision is to not associate old guest orders with newly registered customers. The minor outstanding issue is that there will be duplicate entries in an enterprise's customer list for the registered and non-registered orders for the same email address. 

A simple solution to that might be just to add a `guest` label in the UI next to the guest record, so it's clear to enterprise users why the email address is in there twice?

**Comment by myriamboure** [comment]
I like your idea @Matt-Yorkley ! @mkllnk @oeoeaio is that fine with you? Could be good for now to do that and we will see in the future if we need to go further. I opened a brand new issue to keep this conversation aside and avoid the mess of it, here it is: https://github.com/openfoodfoundation/openfoodnetwork/issues/2338 I assigned it to you Matt I hope it's ok, let's just wait for confirmation from Maikel and Rob and then let's do it :-)

**Comment by mkllnk** [comment]
Yes, I had the same idea. The guest label is also useful in general. And then it's clear that they are two different identities.

**Comment by myriamboure** [comment]
Ok so I'm closing this now that we agreed on a solution for now captured here https://github.com/openfoodfoundation/openfoodnetwork/issues/2338 :-)
