### ISSUE TITLE
Enterprise owner adds a manager who is not yet an OFN user via the manager field (as what happened before with notification field)

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1593]
**Who:** Enterprise Owner wanting to assign an Enterprise Manager who isn't a registered user on OFN yet.
**How they access the sign up process:** Entreprise Owner type their email address in "add manager" field and add them. That triggers a validation email to the unrecognized email and launch sign up process for this new user.

-------
**Step 1(a): Enterprise Owner signs up the user to be Enterprise Manager**
The Enterprise Owner accesses the "managers - add a manager" field in /admin and submits that user's email address.
(today it's only possible to select confirmed user. We want to let the possibility to type an unrecognized email and add it as a manager)

After submitting, a 'pending verification' message displays in the interface below the managers list:

![image](https://user-images.githubusercontent.com/10843056/26964668-fdac29e8-4d35-11e7-93ab-36cf9cdbbf0b.png)

And the following conditions are in place:
-  The new manager is added on the list of managers but appear as "email validation pending" 
-  The 'pending verification' message continues to display until the user confirms (existing functionality).

**Step 1(b): Enterprise Owner resends confirmation email to user**
If the Enterprise Owner needs to resend the confirmation email, and therefore clicks on the 'resend'  on the link in the interface (screenshot above), this triggers:
1. The same confirm email to be sent.
2. Success indicator: a green banner with "a confirmation email has been sent" is display in a green success banner on top of page (remains on the same page)
![screenshot from 2018-03-09 14-56-24](https://user-images.githubusercontent.com/8135376/37210768-2d60e962-23aa-11e8-9217-3ff09b1fe5ea.png)

-------
**Step 2: System requests email confirmation**
The completion of step 1 will trigger the system to do 2 things:
1. System creates a user record, flagged as unconfirmed.
2. System sends a confirmation email to the new user that includes a unique confirm link for that user.

![image](https://user-images.githubusercontent.com/10843056/26964856-b92e149c-4d36-11e7-81ad-6908773e6f8d.png)

-------
**Step 3: User confirms email**
The user clicking on the confirmation link in the email will trigger the following:
1. System flags the user record as confirmed.
2. System sets the user as the Manager of the Enterprise.
3. System sends the user a 'Welcome' email (unique for this user)

![image](https://user-images.githubusercontent.com/10843056/26964971-3214c09a-4d37-11e7-8122-3b5a3080c7bb.png)

4. Browser window opens and displays the page with "email successfully confirmed" and with modal open where they set a password, and once the password is set directs them to /admin (existing functionality).

**Comment by sstead** [comment]
I think this field should function as the current 'notifications' field functions. E.g. I add a new user's email in the manager field, a text box reads 'email confirmation awaiting verifiication -resend confirmation' until the new user confirms their email, at which point they're added as a user, they set up a password and are added as manager of that enterprise.

**Comment by sstead** [comment]
**Current functionality in regards to Enterprises Adding managers**
- If I want to add a user to the Manager field, in the dropdown menu I'll only see Users who are related to my existing enterprises (other user who I manage/own enterprises with). I won't see all users called James in the system if I start typing 'james..' etc. BUT if I type the exact, full email of a user (can be enterprise user, or shopper user), then I can select them and add them as a manager.
- They'll be added as a manager, without any need to verify, and they get no email notification that this has happened.
- So, as an owner, I've just added a unverified shopper user as a manager of my enterprise. I can then make them the owner of that enterprise, and remove myself as owner/manager. This can happen without that user needing to verify, and again they get no notification that this has happened. This is a way that an enterprise can have owners who are not verified. However, if that user then changes the notification email to the non-verified email, THEN the email verificaiton email will be sent to them.
![image](https://user-images.githubusercontent.com/10843056/26865281-4a4e2334-4b9f-11e7-986d-735f555f2759.png)

**Comment by daniellemoorhead** [comment]
>This is a way that an enterprise can have owners who are not verified. However, if that user then changes the notification email to the non-verified email, THEN the email verification email will be sent to them.

@sstead I don't quite understand what you mean by this. Let's talk about it this week!

**Comment by daniellemoorhead** [comment]
@myriamboure we've removed this from the initial scope for email confirmation because it's not actually about email confirmation so much as improving the way it currently functions. Feel free to have your team do this work separately if it's something you really want to fix. :)

**Comment by myriamboure** [comment]
Just to sum up for @ltrls as it was not clear to me reading the whole thing above: we want to be able to add a new manager without using the notification field hack, ie we want to be able if I type a user address in the "add manager" field, if the address is not recognized as a validated user, a validation link is send to that user (as it is done today when we use notification field). Let's talk directly if needs be Pierre :-) Don't know if you need to wait for the other email verification work to be complete before you work on that !

**Comment by Matt-Yorkley** [comment]
@myriamboure There's some changes to these fields and the way users will be added as managers coming in the first 2 email confirmation PRs. I think it would be a good idea to wait for those to be merged.

**Comment by myriamboure** [comment]
Sure @Matt-Yorkley ! Let's wait, and if that makes sense to include that in the initial scope please go ahead, we want anyway this to be done asap, so feel free to pick it up if you do connected things.

**Comment by Matt-Yorkley** [comment]
@myriamboure I'm going to add this to the email confirmation scope as you suggested, if that's ok? It will fit nicely with the changes to how enterprise managers are added.

**Comment by myriamboure** [comment]
Sure, go ahead @Matt-Yorkley this is a critical priority for us the quicker fixed the better. Please take a look at what I suggested here : https://community.openfoodnetwork.org/t/inviting-hub-members-via-email/989/17?u=myriamboure I suggest that when you add a manager it is automatically added in the customer list of the hub as well. If it doesn't have to be done in the same issue we can add this later also ;-)

**Comment by myriamboure** [comment]
Update: This is not possible anymore with first part of email confirm merged to add an unconfirmed user using the "notification" field hack, so I suggest we implement this new feature in the "manager" field directly now and don't use "notification" for that. So only confirmed users can be add in notification field, but we can add a new manager from "manager" field. I'm updating the story description to reflect that. Then we can discuss if we want this to be possible in both "manager" and "notification" but I suggest we say that you need to be a manager to be able to be assigned to receive notification.

**Comment by myriamboure** [comment]
@Matt-Yorkley it would be great to prioritize that work as next on email confirm as users are having trouble as now they can't use the "notification" hack anymore (cf conversation with @lin-d-hop) I have reviewed the initial description and amended it to make sure it's all specified and clear, if you have any question please ask. So to be clear we want people to be able to add someone as a manager who is not yet on OFN directly from the "add a manager" field. Thanks :-)

**Comment by myriamboure** [comment]
@Matt-Yorkley can you please make sure that this UX detail is taken into account when you work on it? I think it is connected to this. https://github.com/openfoodfoundation/openfoodnetwork/issues/1216
> The "update" button should be activated only when the "+" button has been hit and new manager appears on the list
