### ISSUE TITLE
Change forum link in Aus welcome email to fairfoodforum.org.au

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1594]
it currently goes to global ofn forum, which will be much less relevant to sign-up users. The sooner we can do this the better :)

@sstead @daniellemoorhead

**Comment by daniellemoorhead** [comment]
I think you're meaning the URL needs to be changed @kirstenalarsen, rather than setting up a redirect?

@oeoeaio can you please do this as part of your PR day this week?

**Comment by kirstenalarsen** [comment]
yeah nothing complex, it's just not been updated since the aus forum existed!!

**Comment by sstead** [comment]
related issue also encompassing wider improvements to the welcome emails - https://github.com/openfoodfoundation/openfoodnetwork/issues/1553

**Comment by daniellemoorhead** [comment]
Wonder whether we could have @mkllnk do this next week? There are way too many things on @oeoeaio's plate this week.

**Comment by mkllnk** [comment]
Thanks to contributions by the community, changing the URL was as easy as going to Admin -> Configuration -> Content and change "Community Forum Url". Well, almost. The email sender doesn't notice the change until the next deploy. I did it manually:

```sh
RAILS_ENV=production ./script/delayed_job -i 0 stop
```

Mails should contain the right link now (sent by the production server). Can anyone confirm that? @sstead?

**Comment by daniellemoorhead** [comment]
Sally is away next week, maybe Jen can check? Or Kirsten?

**Comment by enricostano** [comment]
Would be nice to have this kind of configuration in per-instance seed data.

**Comment by daniellemoorhead** [comment]
@kirstenalarsen with sally away this week did you want to test it?

@enricostano worth creating a new issue for the extension of this to per-instance seed data?

**Comment by sstead** [comment]
Thanks @mkllnk, the email on production is now correct. 
![image](https://user-images.githubusercontent.com/10843056/28446348-8cd29ed4-6e0d-11e7-8603-4c2b5d5af88d.png)
