### ISSUE TITLE
Embeddable Shopfronts via iframes

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1597]

**Comment by lin-d-hop** [comment]
Hi @daniellemoorhead 

PR #1557 covers this whole epic.

UK have tested the embedded shopfront quite rigorously:
- Host site must be on OFN instance embed allowed list
- Host site must be hosted over SSL
- Embed page does not allow any linking to other parts of OFN shopfront
- Embed page allows search, modals, login, logout, basket, checkout.

@jeronimo and @enricostano have both contributed to code reviews with loads of useful insights (thanks!)

Sooo, over the Aus for final test, review and merge. UK have an unfortunate circumstance of having to roll this out fast, with the aim of pleasing the user it was developed for. Do you think it would at all be possible for someone to have a look this week?

**Comment by lin-d-hop** [comment]
In terms of testing, it's a little tricky to test the functionality as you need to embed in an SSL served site. 

However, potentially we could merge this pre-'functionality test' as long as the security features are working correctly eg can't embed until the host url is whitelisted in superadmin. 

UK plan to write up some usage notes for the user guide so that we can update the user guide before  official release.

**Comment by daniellemoorhead** [comment]
@lin-d-hop we have a dilemma in that we only have @oeoeaio in the office this week, Maikel is still on holiday. He is dedicating one day this week to PRs, and the other 2 to Stripe and Standing Orders. So my question to you is: what's more important in terms of this week for Rob to focus on - getting through the backlog of random PRs that are building up; getting stripe and standing orders closer to done; or reviewing and pushing embeddable shopfronts. Ping me on slack if you want to chat further about this.

**Comment by lin-d-hop** [comment]
Embeddable shopfronts has now been merged and coming soon to an instance near you :-D
