### ISSUE TITLE
Handling Language Defaults and Cookies

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1598]
- [ ] - The first time a user visits, use the default language of the instance. If I go to ofn.fr, I expect it to be in French.
- [ ] - If a user is not logged in and chooses a language, store it in an independent cookie (not session).
- [ ] - If a user is logged in, store it in the database as user preference and also update the cookie.
- [ ] - If someone logs out, the language persists because of the cookie.
- [ ] - If someone then logs in with another account, the locale of that account is loaded (and persists).
- [ ] - If a logged out user selects a language (cookie) and then sign up we should automatically store the info in the cookie in the DB

**Comment by lin-d-hop** [comment]
@jeronimo Can you take a look at this list when you get the chance please?

**Comment by jeronimo** [comment]
@lin-d-hop, All of this had been done with https://github.com/openfoodfoundation/openfoodnetwork/pull/1572
except `The first time a user visits, use the default language of the instance. If I go to ofn.fr, I expect it to be in French.` as default language (in this example - `fr`) is set in `application.yml` which covers that case.

**Comment by lin-d-hop** [comment]
Awesome @jeronimo! Just checking for completeness. That's great :-)

**Comment by daniellemoorhead** [comment]
Have handed over review of #1572 to @mkllnk now that he's back :)

**Comment by daniellemoorhead** [comment]
@ltrls would be great if you could tick the checkboxes in the description that have been done in PR #1572 so that we know what's left before this can be closed. Same for you @Matt-Yorkley once your #1793 has gone through.

**Comment by daniellemoorhead** [comment]
@lin-d-hop I've moved this issue back into the "All The Things" column on the xenhub board. It's still in the Multilingual project so easy enough to find. Will leave you to figure out if there's anything left on the checklist still to be done.

**Comment by lin-d-hop** [comment]
Closing as completed (new bugs/features to go in new issues)
