### ISSUE TITLE
Email Confirmation Send Failures

### ISSUE THREAD

**Issue by jmjcle** [openfoodfoundation/openfoodnetwork#1600]
I'm running in to an issue in the current build (development environment) with user email confirmations.  Hoping to get some guidance in troubleshooting.

Initial user email confirmations never go out and upon issuing a re-send from the Enterprise -> Users page, I get two banners at the top of the screen.  One says that the confirmation email was sent.  The other warns about a missing translation.  Something to do with devise and enterprise.send_instructions but I can't read the entire error as it's obscured by the false success message.  I'm using the default en locale.

When using a local sendmail server in the Spree Mail Methods config, I see no connection or relay attempts in the server logs.  Same when using an external SMTP service.  

![ofn-translation-missing](https://cloud.githubusercontent.com/assets/29126449/26689340/549c8c30-46c3-11e7-90cb-9c67f5a89c7f.png)

**Comment by daniellemoorhead** [comment]
@mkllnk or @myriamboure, any thoughts on why this would be happening?

**Comment by myriamboure** [comment]
it definitely seems to technical to me, seems to be connected to mail server issue, but more a tech bug apparently ;-) I let @mkllnk answer :-)

**Comment by mkllnk** [comment]
There are two issues here. One is that there are some translations missing. That might happen if you have a locale other than just `en`. If you use `en` and still have missing translations, please open a new issue.

Your main issue is sending the emails. You said that you are in development environment. Does that mean you are running this on your own local computer? Usually, no emails are sent in development environment. But I will try to explain how email sending works.

- The application creates a task (Delayed::Job) to send an email.
- During development that task just stays in the database, nothing happens.
- If you start a separate program called Delayed::Job, it will check the database for tasks.
- In production and staging, it uses the email method defined in the admin section for that particular environment to send the email.
- In development, it uses the Letter Opener tool to display the email in your browser.

So you need to run `./script/delayed_job` to see the emails. If you run the application on a remote server in development mode, you are out of luck. You won't see any emails. You should switch to staging environment then.

We could avoid this confusion by bypassing Delayed::Job in development mode. But that means that we may not pick up bugs that only appear when using Delayed::Job. Or maybe this part is missing in the readme file?

**Comment by jmjcle** [comment]
That helps a lot, mkllnk.  Thank you!  I am using just en and I can totally live with a missing translation as long as the underlying email function works.  I did not realize that I shouldn't expect emails to send in dev.  I'll move in to staging or production and look at Delayed::Job.  I might have seen some error logs around that.

**Comment by Matt-Yorkley** [comment]
Closing this for now, feel free to reopen. If I understand correctly it was related to emails not sending via delayed_job in development environment, which is expected.
