### ISSUE TITLE
UK production - logo needs resizing

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1602]
![screenshot from 2017-06-05 20-25-43](https://cloud.githubusercontent.com/assets/9029026/26799398/669ba228-4a2d-11e7-8e54-cf3ac67c3a19.png)
![screenshot from 2017-06-05 20-25-45](https://cloud.githubusercontent.com/assets/9029026/26799399/66b5a402-4a2d-11e7-845e-ca24371ad312.png)

The logo image scaling is based on width instead of height, and AU production has an extra wide logo image. Looks messy on UK production because our image isn't exactly the same width...

**Comment by daniellemoorhead** [comment]
Merged, closing issue.
