### ISSUE TITLE
UK production - Ugly product image thumbnails

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1603]
For some reason product thumbnails on AU production seem to get sized and cropped into nice little squares that fit properly in the image placeholders, but on UK production they don't and it looks really messy. 

AU production:

![screenshot from 2017-06-05 20-38-01](https://cloud.githubusercontent.com/assets/9029026/26800407/18e63c74-4a31-11e7-8006-a9d67d4f43aa.png)

UK production:

![screenshot from 2017-06-05 20-34-29](https://cloud.githubusercontent.com/assets/9029026/26800417/24a2bdf8-4a31-11e7-9fbc-ef6419fada0f.png)

Might be something to do with the Amazon hosting settings...?

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sizing of Images on Shopfronts](https://trello.com/c/FACSxZu1/67-sizing-of-images-on-shopfronts)

**Comment by mkllnk** [comment]
@sstead Do you have an idea what could be the cause?

**Comment by sstead** [comment]
No sorry, I'm not sure what could cause this

**Comment by sineadfenton** [comment]
Are we able to compare sections of the code for each platform to see what the discrepancies might be ?

**Comment by lin-d-hop** [comment]
@sineadfenton the code is the same. We all deploy from the same repo. Likely issue is server settings. Or possibly gem configuration if images are resized on upload...

**Comment by myriamboure** [comment]
@augnustin @ltrls can one of you investigate on that ? This would answer our "resize" need, the problem is also happening in France, same as UK... any idea @mkllnk or @oeoeaio where that can come from ?

**Comment by oeoeaio** [comment]
Are we actually sure that some kind of cropping is taking place? There has been a lot of hand-holding to get producers and shops set up on aus production. So perhaps the fact that the images seem to look better is just a reflection of this support? The only way that I have found to get product images for the Baw Baw Food Hub to display in the way that I want them is to crop them manually before I upload them. This is always going to result in a better image than an algorithm can come up with. Perhaps we just need a suggestion that images are squares, somewhere in the image upload form?

**Comment by myriamboure** [comment]
Yes, I was wondering about that @oeoeaio so I looked at various shops in Aus production and all products' pictures seemed nice so I supposed it was cropped, but as you say maybe it was just manual support ;-)
So I'll be happy to let @augnustin or @ltrls propose something that could work to either crop the image (like a "frame" where you see your image through and can move your image and then clic on "crop" when you are happy) and/or resize and/or compress (cf https://github.com/openfoodfoundation/openfoodnetwork/issues/795). We can see then from the possibilities what we choose (to solve our issue but also save our energy as we have lots of other priorities so let's just solve the urgent UX need but not do more ;-)).

**Comment by Matt-Yorkley** [comment]
Is it Paperclip that creates the thumbnails, or S3? Maybe there's some simple Paperclip settings that could be tweaked.

**Comment by mkllnk** [comment]
> Is it Paperclip that creates the thumbnails, or S3?

Paperclip has the capability of creating thumbnails. S3 is just a storage option and doesn't change the stored files, I believe.

**Comment by sauloperez** [comment]
> Paperclip has the capability of creating thumbnails. S3 is just a storage option and doesn't change the stored files, I believe.

I can confirm

**Comment by myriamboure** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-product-images-display-in-shop/1162
