### ISSUE TITLE
Variant Ordering - Confusing results

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1604]
Variants are currently ordered seemingly randomly when displayed to the user:
![variants1](https://cloud.githubusercontent.com/assets/8669848/26829121/211f5e1c-4abc-11e7-8780-fc8531cee935.png)
![variants2](https://cloud.githubusercontent.com/assets/8669848/26829122/2167852a-4abc-11e7-94a8-45da15665f05.png)

When displaying variants to the user could they be displayed ordered as follows:
- First: Alphabetically eg Gala, Regal Prince, Spartan
- Second: Ascending unit_value eg 250g, 500g, 1kg 

So we'd expect the apples in the example above to come out as:
1) Gala UK 500g
2) Gala UK 1kg
3) Regal Prince UK 500g
4) Regal Prince UK 1kg
5) Spartan UK 500g
6) Spartan UK 1kg

**Comment by OliverUK** [comment]
This is becoming rather important for us in terms of how variants are ordered on purchase orders. You can end up with a very long order email to a supplier where, in the above example, the apricots 500g appear towards the top and apricots 250g way down and it's up to the supplier to find them, add them up and make sure they've not missed anything. It's illogical and hugely error-prone. So it's not just an aesthetical issue.

**Comment by lin-d-hop** [comment]
@oliver, ready for testing on staging. Can you take a look? Will need deploying.

⁣Sent from BlueMail ​

**Comment by lin-d-hop** [comment]
@duende13 I suspect your fix won't affect the order email, so this will be and additional task.

⁣Sent from BlueMail ​

**Comment by lin-d-hop** [comment]
@oliver would you open a new issue detailing the issue in the notification email and assign to Susana? Thanks everyone.

⁣Sent from BlueMail ​

**Comment by OliverUK** [comment]
OK @lin-d-hop, will do. I'm on holiday and only meant to be doing some Stroudco work, so can't do testing until week commencing 17th. Otherwise I'll get into trouble. ;)

**Comment by lin-d-hop** [comment]
No probs, I'm on holiday too :-)

⁣Sent from BlueMail ​

**Comment by daniellemoorhead** [comment]
Linking the new issue for email notification to this issue for easy finding: #1663

**Comment by OliverUK** [comment]
@lin-d-hop  I've had a look now and as far as I can see, the new ordering works well in the shopfront.

**Comment by Duende13** [comment]
Hi @sauloperez, just a note. This issue is not RoR, it was Angular related and it's already been solved (PR #1652) The one that mentions @OliverUK it's RoR and I'm working on it  (#1663)

**Comment by daniellemoorhead** [comment]
Hey @Duende13 now that #1652 has been merged feel free to close this issue 😄

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ordering of Variants and Shipping Methods](https://trello.com/c/l9oQNVZa/52-ordering-of-variants-and-shipping-methods)
