### ISSUE TITLE
Enterprise fees UX

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1606]
Awkward UX on the Enterprise Fees page:

- The name field can't be read as it is too small. 
- The value input field on the far right doesn't appear when adding a new fee until the fee has been saved and the page reloads (has to be saved twice).

![screenshot from 2017-06-06 14-07-06](https://cloud.githubusercontent.com/assets/9029026/26830845/16891ef6-4ac2-11e7-824d-62ba013022fa.png)

**Comment by lin-d-hop** [comment]
#gitcull
