### ISSUE TITLE
Spee logo on UK staging/production

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1607]
Not very good for branding with our enterprise users. Also most of them have probably never heard of Spree. I'm pretty sure it shows the OFN logo on AUS production?

![screenshot from 2017-06-06 14-13-37](https://cloud.githubusercontent.com/assets/9029026/26830999/bac21158-4ac2-11e7-82b9-ef7160e10742.png)

**Comment by kirstenalarsen** [comment]
confirming that yes aus production shows a logo, albeit a very old one and should be updated! If this were made into a super-admin configurable field that could be good, but perhaps that’s over-complicating things

**Comment by sineadfenton** [comment]
Hey @Matt-Yorkley,

Is there a particular size for the logo that's needed? We can send one across and maybe get this updated, would certainly help from a UX perspective - I was confused when I initially started using the system by this as it hadn't been mentioned. Best to save confusion where we can

Cheers,

Sinead

**Comment by enricostano** [comment]
> super-admin configurable field

I would prefer a system variable somewhere defined deplyoing the app (Ansible scripts, etc)

**Comment by Matt-Yorkley** [comment]
I think this has been sorted now on UK production. Possibly by @lin-d-hop...

**Comment by enricostano** [comment]
Can we have more details about it please? This is something more instances will need to customize.

**Comment by lin-d-hop** [comment]
Basically I hacked it, like usual ;-)

1) I took the name of the file the logo was being loaded from via the webbrower. In our case:
/assets/admin/bg/spree_50-2a06eed2050bf730806d31c080c2a008.png

2) I replaced the image to our logo on the server. In our case this was located at:
/apps/openfoodnetwork/current/public/assets/admin/bg/spree_50-2a06eed2050bf730806d31c080c2a008.png

Hope that's useful and sorry that it was a hack. In my defense, I was merely following the advice here:
http://guides.spreecommerce.org/developer/asset.html

**Comment by myriamboure** [comment]
Agree with you @rbarreca and I guess that's the kind of "small tweaks" that @daniellemoorhead and @kirstenalarsen has been talking about lately, not really new features that deserve an icebox. Maybe a new type of labels and we decide to put some small tweaks regularly as a side of bigger features? So we would have the curation team to curate bugs / tech debt / features / small tweaks... Then we need to carefully describe a small tweak as the threshold with feature can be subtle... OR we can have in features "big" and "small" and small are one story, no epic, and big are more than one story... TBD
