### ISSUE TITLE
When SuperAdmin creates a user they should not set their password

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1612]
This is bad practice...
- Instead the new user should get an email confirmation link, and when they click that link they should be prompted to set a password.
- The SuperAdmin user should not be able to see, change or reset the user's password. If they need to reset their password they can do it themselves.

This image shows the SuperAdmin view of creating a new user:
![image](https://user-images.githubusercontent.com/10843056/26957045-a0661b52-4d05-11e7-92bc-e4997b75246b.png)

**Comment by Matt-Yorkley** [comment]
Is this the same as #1589 ?

**Comment by sauloperez** [comment]
It would be worth taking a look at the spree release notes to see if this got ever fixed

**Comment by myriamboure** [comment]
No @Matt-Yorkley it is precised in #1589 "Note: we know that setting a password for a user is bad, and we've created #1612 to change this functionality so that the user sets it themselves." I'll sum up in the other issue what is exactly missing and @ you. If you want to have a look at spree release to check if this one have been fixed that would be great :-)

**Comment by sauloperez** [comment]
The only trace I found in Spree is that in the commit `8fb746c12` the `Spree::Admin::UsersController` has been moved to the api engine and apparently it just returns JSON.

However, when accessing this URL in the app there's an ajax request to `/admin/users/new` that returns the whole HTML markup, including the password confirm field. I haven't found how we manage to return that and whether it's Spree or OFN (I bet it's us)

**Comment by myriamboure** [comment]
I know this is not totally in scope but do we want to include that in email confirmation link? As in term of stories it's on the same UX "user creation" flow, so as we are reviewing it with email confirm... maybe good to do it at the same time? What do you think @enricostano @sauloperez @Matt-Yorkley 

Also I have a question: **why is it such a bad practice?** I mean admins won't touch it, and anyway admins don't see the password and in case of any big issue, that might be useful for an admin to be able to change the user password and do tests on their account, or... I don't know, just wondering why it's bad and we need to change that.

**Comment by mkllnk** [comment]
> why is it such a bad practice?

Setting a password as admin always comes with the problem how to communicate that password to the user. In most cases it's sent via email which is not a secure medium. The password is likely to end up on several computers (the sender, the mail servers, the receiver, backups) and is stored in plain text.

The admin can set a temporary password that has to be changed by the user, but most users don't do it.

**Comment by myriamboure** [comment]
I don't know how to label that, it's not a new feature reallly neither bug but more security issue, so I used tech debt so that we don't forget to tackle it soon... or should we icebox in "future proof the tech platform" thing?

**Comment by myriamboure** [comment]
Ok then closing for now, I opened an icebox item https://community.openfoodnetwork.org/t/prevent-possibility-of-password-fraud-when-super-admin-creates-a-user-account/1362
