### ISSUE TITLE
Email Confirmation | Map confirmed enterprise addresses to the user

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1614]
**Who:** Any enterprise owner who has confirmed their email address.
**Trigger:** No trigger, this is done proactively by us
**Goal:** To ensure that any user who has verified their email address via the enterprise creation process doesn't have to do it again as part of #946.

For epic #946, a one off event needs to be run where any user who has registered one or more enterprises (and therefore already verified their email address via this process) has this confirmation attached to the user, rather than the enterprise.

-------
SPIKE / TO BE DETERMINED

- Does the user always use the same email address for each new enterprise they create? Or is it possible that they have used/verified different email addresses? (@sstead here, yes, I think they always use the same email).

- @sstead here... It is possible for a 'verified' profile to be owned by a user who has never verified their email address, thus we may incorrectly verify some users who are have not confirmed their emails. How does this occur? If the original creator of a profile transfers ownership to a customer user (someone who has no other enterprise profiles). They can do this without the new owner needing to verify (the profile is already seen as verified). However, note that if the original owner puts the new customer user owner as the 'notification' email, the system recognises that that is a 'new user' and sends them a confirmation. So it seems the system can tell the difference between those owners who are verified and those owners who are not. I think that if we mark all owners of verified enterprise profiles as being verified users, some (very few) of these non-verified owners will be incorrectly verified. Unless we can double check (as the notifications field does) if they have actually confirmed their email before.

-------
SOLUTION THOUGHTS

This task depends on two other tasks:

- Change the user model to have confirmable email addresses (see #1668)
- Current enterprise email verification updates the user model as well

We can then safely create a database migration that verifies user email addresses that have been verified as enterprise addresses.

**Comment by Matt-Yorkley** [comment]
I'm pretty sure this is now covered by a migration query in #1690.

**Comment by myriamboure** [comment]
Yes closing as this has been covered:
- "user always use the same email address for each new enterprise they create" > if they want to use another address they will log out and create another user for the other enterprises, current impementation is good
- not possible in current implementation to make owner an unconfirmed user
- as Matt said migration seems to have covered the case of previous unconfirmed owner. If we hear any error reported we will treat them as issues
Closing this then :-)
