### ISSUE TITLE
Email confirmation | Unconfirmed new enterprise user login 

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1615]
**Who:** Enterprise users who have signed up to OFN but have not yet confirmed their email address.
**How they access the login process:** via the 'Register' link on the homepage and on the dropdown the displays at the top of the screen when you first arrive.

Note: this story is directly connected to #1585.

-------
**Step 1(a): User logs in**
The unconfirmed user accesses the login tab on /register and submits their email and password.

After submitting, the modal will display this text:

![image](https://user-images.githubusercontent.com/10843056/27939684-e0d2801c-6309-11e7-84f1-9a25e859f87e.png)
--> Instead of the orange and green messages here, instead use the same style as what displays when the user submits their details on the sign up page, with an option to resend the confirmation email.

And the following conditions are in place:
-  User remains logged out (new functionality). 
-  Closing the modal takes them to the homepage (existing functionality).

**Step 1(b): User resends confirmation email**
If the user needs the confirmation email to be resent, and clicks on the link in the model (screenshot above), this triggers:
1. The same confirm email to be sent as in #1585.
2. A message displays above the 'resend email confirmation' saying 'We resent the email, check your inbox'.

![image](https://user-images.githubusercontent.com/10843056/27939696-ee3dd382-6309-11e7-88c0-6b00913fc5d4.png)

-------
Once the user has initiated resending the confirmation email, the subsequent steps 2-5 are exactly the same as what occurs in #1585.

**Comment by myriamboure** [comment]
This has been covered in email confirm merge https://github.com/openfoodfoundation/openfoodnetwork/pull/1720
