### ISSUE TITLE
Email confirmation | Unconfirmed new user login (modal)

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1616]
**Who:** Any users who have signed up to OFN but have not yet confirmed their email address.
**How they access the login process:** via the login tab which is accessible via the 'Login' link in the top banner (opens login modal).

Note: this story is directly connected to #1586.

-------
**Step 1(a): User logs in**
The unconfirmed user accesses the login tab and submits their email and password.

After submitting, the modal will display this text:
![image](https://user-images.githubusercontent.com/10843056/27939895-fa087112-630a-11e7-8547-a8f2b89f5150.png)

And the following conditions are in place:
-  User remains logged out (new functionality). 
-  They can close the modal and display the original page underneath (existing functionality).

**Step 1(b): User resends confirmation email**
If the user needs the confirmation email to be resent, and clicks on the link in the model (screenshot above), this triggers:
1. The same confirm email to be sent as in #1586.
2. A message displays below the 'resend email confirmation' saying 'We've resent the confirmation to email address, check your inbox'.
![image](https://user-images.githubusercontent.com/10843056/27939906-06ac4970-630b-11e7-9f9b-5ebf0822ff14.png)

-------
Once the user has initiated resending the confirmation email, the subsequent steps 2-4 are exactly the same as what occurs in #1586.

**Comment by myriamboure** [comment]
Covered in merge #1720
