### ISSUE TITLE
Email confirmation | Unconfirmed new user login (checkout)

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1617]
**Who:** Any users who have signed up to OFN but have not yet confirmed their email address.
**How they access the login process:** by clicking 'login' at the following points in their journey on the site:
- From a shopfront (once they've added items to their cart)
- From the edit cart page
- From the 'log in or guest checkout?' page
- From any page on the OFN, if they have items in their cart (homepage, a groups page, a /sell page, etc).

Note: this story is directly connected to #1587.

-------
**Step 1(a): User logs in**
The unconfirmed user accesses the login tab and submits their email and password.

After submitting, the modal will display this text:
![image](https://user-images.githubusercontent.com/10843056/27940070-e1495276-630b-11e7-9764-a1e782b03fcb.png)

And the following conditions are in place:
-  User remains logged out (new functionality). 
-  They can close the modal and display the original page underneath (existing functionality).

**Step 1(b): User resends confirmation email**
If the user needs the confirmation email to be resent, and clicks on the link in the model (screenshot above), this triggers:
1. The same confirm email to be sent as in #1587.
2. A message displays below the 'resend email confirmation' saying 'We resent the email, check your inbox'.
![image](https://user-images.githubusercontent.com/10843056/27940108-2ccfd968-630c-11e7-9230-71f39a880c44.png)

-------
Once the user has initiated resending the confirmation email, the subsequent steps 2-4 are exactly the same as what occurs in #1587.

**Comment by myriamboure** [comment]
Included in #1720 (just retested quickly in case to reassure me and all good ;-))
