### ISSUE TITLE
Email confirmation | Unconfirmed new user login (customer-only shop)

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1618]
**Who:** Any users who have signed up to OFN but have not yet confirmed their email address.
**How they access the login process:** the user navigates to the customer-only shopfront and sees this message, and clicks on 'register':

![image](https://user-images.githubusercontent.com/10843056/26864353-000b7b86-4b9b-11e7-8261-76270ca966b4.png)

Note: this story is directly connected to #1588.

-------
**Step 1(a): User logs in**
The unconfirmed user accesses the login tab and submits their email and password.

After submitting, the modal will display this text:

![image](https://user-images.githubusercontent.com/10843056/27940271-08ba7bfe-630d-11e7-8553-2ebabf4864d2.png)

And the following conditions are in place:
-  User remains logged out (new functionality). 
-  They can close the modal and display the original page underneath (existing functionality).

**Step 1(b): User resends confirmation email**
If the user needs the confirmation email to be resent, and clicks on the link in the model (screenshot above), this triggers:
1. The same confirm email to be sent as in #1588.
2. A message displays below the 'resend email confirmation' saying 'We've resent the confirmation to email address, check your inbox'.
![image](https://user-images.githubusercontent.com/10843056/27940276-12ec75a0-630d-11e7-857d-627962f13514.png)

-------
Once the user has initiated resending the confirmation email, the subsequent steps 2-4 are exactly the same as what occurs in #1588.

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley is this part of the functionality you've built for Email confirm?

**Comment by myriamboure** [comment]
I retested that story as well as the "register" one and it's all good, so I'm closing it (https://docs.google.com/document/d/1UXwLF0o4TdQ8SyqoJdp1l70TuNby8ZhZvq12z27C4No/edit?usp=sharing - I have retested all that at the end, didn't do all the captures but all work really good).
