### ISSUE TITLE
Address.state can't be blank when creating a new Enterprise

### ISSUE THREAD

**Issue by mllocs** [openfoodfoundation/openfoodnetwork#1620]
Hello everyone 👋  

I just did the setup of the Rails project in my maching and my first step was to register a new user, which would be a new producer (called Enterprise internally). I'm struggling entering a valid address during the registration process. I guess that not all the countries have state but that check might not work properly. 

If I select a country without states I would expect the validators to also skip that verification. I'm missing something? I'm always getting the error "Address.state can't be blank", even with countries without state. 

Thanks.

![](https://www.dropbox.com/s/abqf26d7hui1g3z/Screenshot%202017-06-10%2014.13.46.png?dl=1)
![](https://www.dropbox.com/s/hkahrx3fr8sitjz/Screenshot%202017-06-10%2014.14.03.png?dl=1)

**Comment by enricostano** [comment]
Maybe related to https://github.com/openfoodfoundation/openfoodnetwork/issues/1309 ?

**Comment by mllocs** [comment]
@enricostano I can see the States dropdown if the country has States. My problem is the validation. Countries without states should allow Address.state to be blank. BTW, this is my local environment, I cloned the `master` branch yesterday. 😄

**Comment by mllocs** [comment]
Same issue as here https://github.com/openfoodfoundation/openfoodnetwork/issues/1330
