### ISSUE TITLE
Bug on customer account display

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1623]
URL : https://www.openfoodfrance.org/account#/#hub-demo-open-food-france
![screenshot from 2017-06-16 14-20-53](https://user-images.githubusercontent.com/8135376/27226487-9bb90070-529f-11e7-8ea4-63449928d1b3.png)
Any idea why we have that @pacodelaluna ?

**Comment by myriamboure** [comment]
The "NaN" € instead of the total amount on the top right

**Comment by myriamboure** [comment]
That's strange also, the calculation are wrong on the amount owed...

**Comment by myriamboure** [comment]
![screenshot from 2017-06-27 18-41-15](https://user-images.githubusercontent.com/8135376/27599198-3f8bae84-5b68-11e7-940b-c1ad5c14aabe.png)

**Comment by myriamboure** [comment]
![screenshot from 2017-06-27 18-41-15](https://user-images.githubusercontent.com/8135376/27599261-7e3ef1c2-5b68-11e7-80d1-cbf231ab2000.png)
I have the impression that's a rounding display on column "amount", as when I click on the order it's the right amount.
Do you have the same issue @sigmundpetersen and @sstead ?

**Comment by enricostano** [comment]
`NaN` is a great JS classic :trollface:

**Comment by myriamboure** [comment]
@ltrls awesome if you can look at that, I can't assign you yet but I can mention you at least ;-)

**Comment by myriamboure** [comment]
Seems to be connected also to https://github.com/openfoodfoundation/openfoodnetwork/issues/853
