### ISSUE TITLE
Shipping Method Ordering - Confusing Results

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1626]
Shipping methods are currently ordered seemingly randomly when displayed to the user.

![shippingmethodordering](https://user-images.githubusercontent.com/8669848/27281668-a3bed2da-54e4-11e7-977c-cb23eeff09f0.png)

When displaying variants to the user could they be displayed ordered alphabetically.

So we'd expect the example above to come out as:
1) Collect between 12-1 pm Saturday (free)
2) Collect LATER than 1pm Saturday (free)
3) Home delivery - 1 mile (£2.00)
4) Home delivery - 1, 2 or 3 miles - orders over £25 (£2.00)
5) Home delivery - 2 miles (£3.50)
6) Home delivery - 3 miles (£5.00)

Looking at this list it is not the perfect ordering, but I think once it is alphabetically ordered hub managers will have more power to manipulate the display and we can come up with work arounds :-)

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ordering of Variants and Shipping Methods](https://trello.com/c/l9oQNVZa/52-ordering-of-variants-and-shipping-methods)

**Comment by OliverUK** [comment]
![screen shot 2017-09-05 at 16 57 49](https://user-images.githubusercontent.com/17590921/30070512-94f42480-925b-11e7-979e-5b8bbabaae5a.png)

Shipping methods now sort as expected on staging after deploy.

**Comment by daniellemoorhead** [comment]
Will hold off on closing this till the merged code has been released onto Aus production with the next thing we merge. Ping @oeoeaio and @mkllnk to take not that this will be going through with whatever the next thing is that you push to production.

**Comment by oeoeaio** [comment]
@daniellemoorhead do you think this can be closed?

**Comment by sigmundpetersen** [comment]
@oeoeaio seems this PR #1795 is connected and not merged yet?

**Comment by daniellemoorhead** [comment]
Closing this now as #1795 has been merged.
