### ISSUE TITLE
Update SASS Gem

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1628]
OFN CSS seems to load a huge amount of repetitive and redundant data.
![1](https://user-images.githubusercontent.com/8669848/27332347-672b1ba0-55b9-11e7-92ba-e3d628b93add.png)
![2](https://user-images.githubusercontent.com/8669848/27332350-67d3f8ec-55b9-11e7-95a8-e08f8c8db0dc.png)
![3](https://user-images.githubusercontent.com/8669848/27332352-6905a08a-55b9-11e7-9ab5-10ab93155ea1.png)

It seems users of sass have reported issues of redundant CSS in older versions of SASS, like that which we are using.
@Matt-Yorkley suggests that we are using an old version due to some dependancies that we've now been able to update. 

Soooo would be great to explore updating SASS to the most recent version.

**Comment by Matt-Yorkley** [comment]
Another thing I'm not sure about is the inclusion of 2 large CSS files instead of one. We seem to have the regular compiled CSS file, and a second one called `all_split2.css`. This file seems to be including all the darkswarm styles a second time?

**Comment by daniellemoorhead** [comment]
@oeoeaio anything you can add to this in terms of history of why there's 2 large CSS files and upgrading?

**Comment by oeoeaio** [comment]
@Matt-Yorkley looking at the original commit b540f645c3: looks like an attempt to overcome an issue with IE having a maximum file length? Not sure if this is still working or required...

**Comment by Matt-Yorkley** [comment]
I thought that maybe SASS could handle removing duplicates whilst compiling, but it looks like we'd need a separate CSS optimizer/purger. I've been looking at whether this relates directly to other discussions like #1393 on css-linting with codeclimate, but I think that's a separate issue. 

This strange IE hack probably won't be needed if we can properly reduce the vast amounts of duplication of CSS rules. As an example if you click right click a link and inspect the CSS you can see the rule to set the font color on links is duplicated roughly 30 times across both files.

I'll take a look at CSS optimizers...

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/optimisations-suggestions/1176
