### ISSUE TITLE
Returned inventory is added to the Product On Hand value incorrectly

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1631]
When products are managed in Inventory...

When a customer orders the product, the stock is subtracted from the Invenotry On Hand value. But if the order is cancelled or the item returned, the stock returns to the Product On Hand value.

This is incorrect, it should continue to treat that item as Inventory, not a Product.

**Comment by enricostano** [comment]
@sauloperez this is something we could check: if and how it will change with the new inventory implementation in Spree 2.0

**Comment by kirstenalarsen** [comment]
this makes me wonder if we should maintain a ‘pre-spree-upgrade’ version operating on a staging server somewhere, to make it really easy for people testing to check back whether something is a bug or behaviour introduced by spree upgrade. It can sometimes be challenging (even for the super-human @sstead) to remember the detail of exactly how everything is meant to work / worked before!

**Comment by enricostano** [comment]
> ‘pre-spree-upgrade’ version operating on a staging server

That would be awesome @kirstenalarsen

**Comment by daniellemoorhead** [comment]
The two staging servers in Aus get used fairly frequently @kirstenalarsen, whether it's for demos or for rob and maikel's stuff - reckon we should spin up another temporary staging server specifically for Spree upgrade?

**Comment by enricostano** [comment]
This is blocked by Spree upgrade

**Comment by luisramos0** [comment]
Removing the reference to #2109 and moving it to epic #2584 (all the issues blocked by the spree upgrade).

**Comment by luisramos0** [comment]
v2 comes with this one fixed 🎉 
I have tested in v1 and it is broken, I tested in v2 and it works.
You can have a look at staging AUS.

Testing notes:   #wannabetester
https://docs.google.com/document/d/1KU5WBhU6GKPuG35VeoOrec5gti7ICVAD5w3nQVjpQWY/edit

I have additionally verified that resuming the order takes the inventory back again from the right place.
Closing the issue.
