### ISSUE TITLE
Malfunctions with the OC advanced settings - restricting variants to coordinator's inventory

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1632]
Under the settings below, products which are in the coordinator's New Products list should be available in the Incoming section of an order cycle. This is according to the initial description of the feature in the user guide.

![image](https://user-images.githubusercontent.com/10843056/27371235-542d083e-56a3-11e7-9106-4b50f4497a48.png)

![image](https://user-images.githubusercontent.com/10843056/27371245-5eec61d4-56a3-11e7-8a8a-ad6330aa943f.png)

**Comment by sstead** [comment]
**Further issues with the OC advanced Settings**

I found while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2413 that the setting wasn't working...
In the example pictured below the products should be restricted to the coordinator's inventory, which is correctly 2 variants. But when I save the OC I see that the OC has 7 variants, and when I go to the shop the variants aren't being restricted to the coordinator's inventory.

https://github.com/openfoodfoundation/openfoodnetwork/pull/2413

**Comment by kirstenalarsen** [comment]
I have been investigating (learning Inventory) today and I think these are both ok
