### ISSUE TITLE
On the /welcome screen there is no image

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1648]
This issue has been found by @sstead while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/1524, more info [here](https://community.openfoodnetwork.org/t/spree-testing-june-2017/976).

![](https://community.openfoodnetwork.org/uploads/default/optimized/1X/4cdb71084af479f3f50c87455cbeab53f3e07ccc_1_690x465.png)

**Comment by enricostano** [comment]
While running the app locally I see the Spree logo in that route:

![2017-06-29-162138_1366x768_scrot](https://user-images.githubusercontent.com/748971/27692469-1222e554-5ce7-11e7-9df3-727178de38a8.png)

But I see that your staging instance is using a different logo, the broken image title suggest something that starts with `Ofn...`. Could be that some custom asset has not been loaded while deploying?

cc/ @oeoeaio @RohanM

**Comment by enricostano** [comment]
ping @oeoeaio @RohanM

**Comment by enricostano** [comment]
@sstead could you please test this again? Thanks!

It is deployed at https://staging1.openfood.com.au

cc/ @sigmundpetersen @OliverUK @oeoeaio

**Comment by sstead** [comment]
The image did not load again. But it's probably just because the images aren't present- not a Spree related issue.
![image](https://user-images.githubusercontent.com/10843056/28446487-5b0fc8b2-6e0e-11e7-80c6-5320e92be172.png)

**Comment by sstead** [comment]
Related to this page....
![image](https://user-images.githubusercontent.com/10843056/28446668-98561d56-6e0f-11e7-97dd-125437e43817.png)

**Comment by enricostano** [comment]
>The image did not load again. But it's probably just because the images aren't present- not a Spree related issue.

Yeah, I'm pretty sure it's not Spree related. It seems to be related to https://github.com/openfoodfoundation/openfoodnetwork/issues/1607 ping @oeoeaio 

> Producer Description Text2

Yep, https://github.com/openfoodfoundation/openfoodnetwork/pull/1622 got merged 8 hrs ago. We're good here.

**Comment by enricostano** [comment]
@sstead @oeoeaio I think we can close this issue, right?

**Comment by oeoeaio** [comment]
I think this should be configurable from super admin (?), so we should be able test if it is a genuine issue or not fairly easily...

**Comment by enricostano** [comment]
I've been able to set the footer image from configuration section with super admin user. Let's close this issue.

![2017-08-03-195530_1366x768_scrot](https://user-images.githubusercontent.com/748971/28935835-0eca0ed6-7886-11e7-8d4b-3240c706d8be.png)

**Comment by sstead** [comment]
Rob had a look into it and the image on /welcome is not set in SuperAdmin configuration. It's hard coded. We're not sure why the image displays correctly on Production, but not on Staging1 and Staging2. It's not likely to be Spree related. 

And I can confirm the text at /welcome is fixed- instead of the incorrect 'producer description Text2'
