### ISSUE TITLE
Add store name beside pin location icon.

### ISSUE THREAD

**Issue by renziver** [openfoodfoundation/openfoodnetwork#1649]
<img width="538" alt="screen shot 2017-06-30 at 10 17 21 am" src="https://user-images.githubusercontent.com/13497174/27718314-d5f62522-5d7d-11e7-98b9-feac0195fb9c.png">
can we have something like this on the map so that it would be easier to identify the name of the store and save time on clicking the icon just to know the store name?

<img width="1136" alt="screen shot 2017-06-30 at 10 16 22 am" src="https://user-images.githubusercontent.com/13497174/27718315-d5f84d8e-5d7d-11e7-995b-fa0f19c23b38.png">

**Comment by daniellemoorhead** [comment]
We'd really love to bring the whole map experience better for users. Ping @kirstenalarsen, maybe something that'd be covered within the search and directory stuff we've been talking about?

**Comment by kirstenalarsen** [comment]
yes i think so - this is a great idea (would it be challenging with translations?) could you tag it ‘directory’ then I’ll pick it up while speccing, which might (hopefully) happen soon :)

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/discovery/1177
