### ISSUE TITLE
Wrong color combination in red error banner

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1657]
The text of the red banner cannot be read due lack of constrast between text and background colors.

The text color for the `.error` class has been changed in https://github.com/openfoodfoundation/openfoodnetwork/commit/564c1a36503c9eb7cb90905035918c07137ddf35#diff-7c2eeac4e6608877bb981b056037f74bR32

To reproduce the issue I tried to create an Order Cycle while no Enterprise could create one. The text says: *None of your enterprises have permission to coordinate an order cycle*

But I guess this affects every error banner in the `admin` section.

![2017-07-04-142058_1366x768_scrot](https://user-images.githubusercontent.com/748971/27829921-48ea0c30-60c4-11e7-9198-76cdb221ddfc.png)

cc/ @oeoeaio

**Comment by oeoeaio** [comment]
Yeah, I fixed this in https://github.com/oeoeaio/openfoodnetwork/commit/688b28ad8778b2e640bbea9b28d01bfd22f7f4c0 

Just have to wait for standing orders for the fix, or we can cherry-pick it I suppose...

**Comment by enricostano** [comment]
I think would be nice to have a separate PR to bring it into next release IMHO

**Comment by oeoeaio** [comment]
@enricostano #1746

**Comment by enricostano** [comment]
Thanks @oeoeaio !
