### ISSUE TITLE
Variants are ordered illogically (not ordered at all) on purchase order emails

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1663]
There doesn't seem to be any logic behind how variants are ordered on emails sent to suppliers. 
You can end up with a very long order email to a supplier where, for example, Apricots 500g appears towards the top and Apricots 250g way down and it's up to the supplier to find them, add them up and make sure they've not missed anything.

**Comment by sauloperez** [comment]
I guess this is again just a matter of applying alphabetic order, in this case in the underlying database query

**Comment by OliverUK** [comment]
Ordering seems to work well now in the linked issue 1604 on UK staging. Could the same be applied to the order emails? Sort alphabetically first and the by qty in ascending order?

**Comment by Duende13** [comment]
I'm working on that @OliverUK :)

**Comment by Duende13** [comment]
@OliverUK , @lin-d-hop , just one question, does it make sense that this order can be seen into the confirmation screen at the end of the check out? The summary of the order screen. It can be applied to both, email and confirmation screen. Is it ok for you? I'm almost there just I have to add some tests and I'll be done :)

**Comment by OliverUK** [comment]
Hi Susana, 
You are saying that the customer orders will also be ordered in the same way as the orders to the suppliers? I can see no problem with this.

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ordering of Variants and Shipping Methods](https://trello.com/c/l9oQNVZa/52-ordering-of-variants-and-shipping-methods)

**Comment by lin-d-hop** [comment]
@Duende13 
This has now been deployed to UK production but seems to not be working.
Ping @OliverUK to provide more details....

**Comment by OliverUK** [comment]
OK so here is an example of this mornings notify producer emails as copied to me:

![screen shot 2017-10-12 at 10 48 40](https://user-images.githubusercontent.com/17590921/31490175-fbb40c2a-af3a-11e7-97fa-b22c2b24ccd7.png)

**Comment by OliverUK** [comment]
@Duende13 any news on what the problem can be?

**Comment by Duende13** [comment]
Hi @OliverUK ,
I was having a look into that and I realised that the changes that I made were not merged into the current master branch. @lin-d-hop and I will look into that and we'll fix it. Thank you for your understanding :)

**Comment by Duende13** [comment]
Hi @OliverUK ,
a new PR has done for this issue but it includes just the order of variants by name and unit value in confirmation email and screen for clients, not producers. When these changes are merged, it will be really easy to apply to producer emails too.

**Comment by myriamboure** [comment]
@lin-d-hop I saw you closed the associated PR, do you want to move this forward or should we just open a wishlist item for that and close the issue? It's nice to have but maybe not a priority, is it?

**Comment by myriamboure** [comment]
Sorry @lin-d-hop forget my precedent message, didn't see the new PR.

**Comment by OliverUK** [comment]
@Duende13 @lin-d-hop 
Regarding producer emails, seeing that dev work has gone into it, it's a shame we aren't seeing the benefits. Is there anything I can do to move this forward? I opened this issue with producer emails in mind and from what you say we now have a partial fix which does the job for consumer emails? Can we now transfer this to producer emails too?

**Comment by lin-d-hop** [comment]
Hi Olievr, if you look at the PR you will see this is back to Susana after testing the recent changes. Susana is not yet back since Christmas holidays. Thanks for your patience.
