### ISSUE TITLE
Incorrect invoice dates

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1672]
Orders show wrong date in UI. The order here says "03 August" when the date is actually 03-07-2017...? This happens on all orders.

Orders page:
![screenshot from 2017-07-11 13-25-13](https://user-images.githubusercontent.com/9029026/28068403-451ecd2e-663d-11e7-9544-832129255a0c.png)

Order:
![screenshot from 2017-07-11 13-25-06](https://user-images.githubusercontent.com/9029026/28068402-451dfbec-663d-11e7-9db3-780db45785af.png)

**Comment by oeoeaio** [comment]
Is the date being formatted using `:long`? (Sorry on phone, can't check myself). I had a weird issue that looked like this when `:long` was used. Never worked out what was going on but using an explicit format fixed it.

**Comment by Matt-Yorkley** [comment]
@oeoeaio yeah it looks like it's using a method called `pretty_time` which is using `format: :long`.

**Comment by Matt-Yorkley** [comment]
Wow this is really weird... using explicit date formatting the short version `%b` gives me `Aug`, but the long version `%B` gives me `September`. They should be the same month!

**Comment by oeoeaio** [comment]
Yep definitely something odd happening...could you document the steps you took to reproduce if that's easy? I'd like to have a deeper look and see if I can work out what is going on..

**Comment by Matt-Yorkley** [comment]
Ah, I've found the answer: https://github.com/spree/spree/pull/2427 It looks like this might will be fixed in the Spree upgrade...

**Comment by RachL** [comment]
@Matt-Yorkley @lin-d-hop is this fixed now?

**Comment by RachL** [comment]
I'm guessing it is. So closing. Feel free to reopen if not.
