### ISSUE TITLE
UK Invoice wording and localisation

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1674]
Invoices currently say "GST" in the UK, instead of "VAT".

Invoices are titled "Tax Invoice", but should probably just be "Invoice". 

Date format is shown as "YYYY-MM-DD" instead of "DD-MM-YYYY".

![screenshot from 2017-07-11 13-41-23](https://user-images.githubusercontent.com/9029026/28068761-cf8a1116-663e-11e7-8e1c-af076fcba81f.png)
![screenshot from 2017-07-11 13-41-29](https://user-images.githubusercontent.com/9029026/28068762-cf9491e0-663e-11e7-892f-42393ea92b39.png)

**Comment by myriamboure** [comment]
@Matt-Yorkley You should check the other invoice format we have done in France, it might  answer your need... see in admin "user alternative invoice" thing ;-)

**Comment by sineadfenton** [comment]
Hey all,

We've had a couple more requests on translating GST into VAT for the UK. I just wanted to follow up in relation to the #1684 ticket and if this was that was currently being actioned?

(excuse my ignorance! just can't quite work it out and it would be good to feedback to the community) 

cheers,

S

**Comment by Matt-Yorkley** [comment]
@sineadfenton it should be going through soon.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GST/VAT Invoice for Shoppers](https://trello.com/c/YWiVRIah/47-gst-vat-invoice-for-shoppers)

**Comment by lin-d-hop** [comment]
Merged so closing
