### ISSUE TITLE
Wording of "capture" for payments

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1676]
"Capture" is a slightly jargony word for marking orders as paid, and has caused some confusion.

Suggestion to change the wording to "Mark as paid".

![screenshot from 2017-07-11 14-27-50](https://user-images.githubusercontent.com/9029026/28070557-3c76ab4e-6645-11e7-8539-c1c3965b553f.png)

**Comment by daniellemoorhead** [comment]
Hey @Matt-Yorkley would this be an #angularfornewbies type piece of work?

**Comment by daniellemoorhead** [comment]
Hey @Matt-Yorkley the PR #1687 was merged in July, ok to close this issue?
