### ISSUE TITLE
Company number for invoices

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1677]
Currently when trying to send invoices, users are told they have to set a company number and invoices don't send. The number referred to is the ABN, but ABNs are Australian Business Numbers and this isn't clear in the message. In the UI for enterprises, there are fields for ABN and ACN. For UK we probably just need one for "Company Number".

![screenshot from 2017-07-11 14-50-51](https://user-images.githubusercontent.com/9029026/28072407-c9d18068-664a-11e7-97fb-311605f21d37.png)
![screenshot from 2017-07-11 14-50-55](https://user-images.githubusercontent.com/9029026/28072406-c9ce3da4-664a-11e7-8336-b4799fa6e01f.png)
![screenshot from 2017-07-11 15-06-09](https://user-images.githubusercontent.com/9029026/28072408-c9d4b102-664a-11e7-8f46-da9230291ee4.png)

**Comment by Matt-Yorkley** [comment]
@lin-d-hop Can I change the translation for "ABN" to "Company Number" for the UK? What should we do with "ACN"?

**Comment by lin-d-hop** [comment]
Sure

⁣Sent from BlueMail ​

**Comment by NickWeir63** [comment]
maybe ACN could be "Charity Number"?

**Comment by daniellemoorhead** [comment]
Closing this issue as the PR #1686 has been merged. @Matt-Yorkley feel free to reopen if this isn't correct.
