### ISSUE TITLE
Missing translation sending invoices

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1678]
![screenshot from 2017-07-11 15-12-20](https://user-images.githubusercontent.com/9029026/28072700-b5d31b7a-664b-11e7-8605-4ea18754a62b.png)

**Comment by Matt-Yorkley** [comment]
@lin-d-hop I thought UK production defaulted to EN translation keys when GB keys were missing? Has this changed?

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley this PR attached to this has been closed but this is still sitting with a Code Review status. Is there further work going on, or should we push this issue back to the backlog to be worked on later?

**Comment by Matt-Yorkley** [comment]
This was fixed during the previous Spree upgrade work.
