### ISSUE TITLE
Datepickers not working

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1679]
- Datepicker widgets have missing icons when viewing individual Order Cycles.

![screenshot from 2017-07-11 15-27-00](https://user-images.githubusercontent.com/9029026/28073678-66c3066e-664e-11e7-84f0-966f0d96ea79.png)

- Datepicker icons on the main Order Cycles page sometimes don't work when clicked?

![screenshot from 2017-07-11 15-26-43](https://user-images.githubusercontent.com/9029026/28073598-2104b7da-664e-11e7-81da-fcf1810c1272.png)

**Comment by Matt-Yorkley** [comment]
Datepicker buttons not working intermittently was a UK localisation issue where saved dates displayed as yyyy-mm-dd but new dates used yyyy/mm/dd format (only on UK) which caused parsing issues and javascript errors, and no datepicker popup.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Datepickers Not Working](https://trello.com/c/jJrOJHRo/65-datepickers-not-working)
