### ISSUE TITLE
Multiple formats for AJAX requests

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1691]
While working on step 6 of the Spree upgrade (https://github.com/openfoodfoundation/openfoodnetwork/pull/1524) I found out that we make 2 different kinds of AJAX requests while dealing with the same resources.

A clear case is both `#update` and `#destroy` actions in [LineItemsControllerDecorator](https://github.com/coopdevs/openfoodnetwork/blob/69053bf744bd2d8bfeab67843538088a90840fd0/app/controllers/spree/admin/line_items_controller_decorator.rb#L35). This is the `#destroy` action:
```ruby
  # TODO: simplify this, 3 formats per action is too much:
  #       we need `js` format for admin/orders/edit (jquery-rails gem)
  #       we need `json` format for admin/orders/bulk_management (angular)
  #       we don't know if `html` format is needed
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { render_order_form }
      format.js { render nothing: true, status: 204 } # No Content
      format.json { render nothing: true, status: 204 } # No Content
    end
  end
```
As already showed in the documentation of the action we use the same action for different things. I would leave the `HTML` vs `AJAX` issue for now since the broken consistency between different AJAX calls seems more urgent to tackle to me.

We basically do 2 completely different requests to destroy or update a `LineItem` from JS. At least 2 basic headers are different.

I suggest to investigate how we can have only one way to make AJAX requests.

Related PR https://github.com/Em-AK/openfoodnetwork/pull/10

**Comment by enricostano** [comment]
cc/ @oeoeaio @RohanM @mllocs

**Comment by oeoeaio** [comment]
I vote json. Agree that we need to review this. Add it to the tech debt pile. 🙂

**Comment by enricostano** [comment]
Moved to icebox: https://community.openfoodnetwork.org/t/clean-up-endpoint-responses-formats/1158

**Comment by luisramos0** [comment]
this problem is still valid and we also have #4284 for the content of the put and post requests...

**Comment by mkllnk** [comment]
This issue will be resolved by our API work.
