### ISSUE TITLE
Authorization Failure when accessing payment methods in Edit/Create Order

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1693]
This issue has been found by @sstead while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/1524, more info [here](https://community.openfoodnetwork.org/t/spree-testing-june-2017/976).

Once placed an order from the backend (admin) she tried to edit the order and access the **Payments** tab but she got an **Authorization failure** error like showed in the bottom of the following picture:

![](https://community.openfoodnetwork.org/uploads/default/optimized/1X/f8e0323ac9e24397a965a8e98e38597d0e523bb4_1_690x415.png)

**Comment by enricostano** [comment]
@sstead I've not being able to reproduce this error. Would you please try again once we deploy step 6 on some server?

Thanks!

**Comment by enricostano** [comment]
@sstead could you please test this again? Thanks!

It is deployed at https://staging1.openfood.com.au

cc/ @sigmundpetersen @OliverUK

**Comment by enricostano** [comment]
@sstead @sigmundpetersen could you please test this again? Thanks!

**Comment by sstead** [comment]
Yes @enricostano , this Authorisation Failure is still occurring for me. It is still occuring for New Orders and Editing Orders.

**Comment by sauloperez** [comment]
This seems to be related to https://github.com/Em-AK/openfoodnetwork/pull/15

**Comment by enricostano** [comment]
@sstead this should be fixed now in staging1. Could you please test it again? Thanks!

**Comment by enricostano** [comment]
Thanks @sstead!
