### ISSUE TITLE
Marking an order as 'captured' or paid. GET UNAUTHORISED MESSAGE

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1694]
This issue has been found by @sstead while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/1524, more info [here](https://community.openfoodnetwork.org/t/spree-testing-june-2017/976).

Once placed an order from the backend (admin) she tried to **mark the order as captured** but she got an **Authorization failure** error like showed in the upper part of the following picture:

![](https://community.openfoodnetwork.org/uploads/default/optimized/1X/f8e0323ac9e24397a965a8e98e38597d0e523bb4_1_690x415.png)

**Comment by enricostano** [comment]
@sstead I've not being able to reproduce this error. Would you please try again once we deploy step 6 on some server?

Thanks!

**Comment by enricostano** [comment]
@sstead could you please test this again? Thanks!

It is deployed at https://staging1.openfood.com.au

cc/ @sigmundpetersen @OliverUK

**Comment by sstead** [comment]
I'm still getting this error... 

Would it help for you to login as my user to see the error @enricostano ? My login is sally+2@openfoodnetwork.org.au, I'll slack the pw

**Comment by enricostano** [comment]
The request is:
```
POST https://staging1.openfood.com.au/admin/orders/R483615334/payments/1018/fire?e=capture
```
and the response is a redirect to `https://staging1.openfood.com.au/unauthorized`

**Comment by enricostano** [comment]
It seems a problem in loading order 😞

**Comment by enricostano** [comment]
https://github.com/Em-AK/openfoodnetwork/pull/15 should fix this issue

**Comment by sstead** [comment]
Yes, this is now fixed

**Comment by enricostano** [comment]
Go go go! Thanks!
