### ISSUE TITLE
Paypal and Pinpayments does not work

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1695]
This issue has been found by @sstead while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/1524, more info [here](https://community.openfoodnetwork.org/t/spree-testing-june-2017/976).

> I wasn't able to get Paypal or Pinpayments to work. Maybe my fault, maybe a bug? I used the accounts that we use for testing- it could be that I set them up wrong, but I did double check?? Error messages below. You can test for yourself in Toowoomba Food Hub.

![](https://community.openfoodnetwork.org/uploads/default/original/1X/e8772cd298e547a4cd7e77422dbacad902477508.png)

**Comment by enricostano** [comment]
@sstead @kirstenalarsen @oeoeaio I'm not sure how to test this in local. Should we wait to test it again once we have step 6 deployed again somewhere? Thanks!

**Comment by oeoeaio** [comment]
There must be a way to test this locally... Are there test cards that you can use with PayPal? @sstead did we have a PayPal account that we can use for testing?

**Comment by sstead** [comment]
Yes @oeoeaio , there are Eaterprise accounts for both Pin Payments and Paypal that I use to test. I can confirm that this Paypal account is working on Staging2. The Pinpayments account is setup on staging2, but not working on currently (same error message as above).

**Comment by enricostano** [comment]
@sstead @oeoeaio I guess that in Staging2 there is something else deployed, not step 6. Right? We need to test this with step 6.

Of course it should work first with `master` 😂

**Comment by kirstenalarsen** [comment]
correct. step 6 is currently deployed nowhere i think

**Comment by enricostano** [comment]
@sstead could you please test this again? Thanks!

It is deployed at https://staging1.openfood.com.au

cc/ @sigmundpetersen @OliverUK

**Comment by sstead** [comment]
Yes, i finally got Paypal and PinPayments to work!

Note to self: 
Pinpayments won't process if amount is too low. $1.10 works. 
Paypal: if Solution is 'Sole' then the Landing Page must be 'Billing'. If the solution is 'Mark' then Landing Page must be 'Login'.

**Comment by enricostano** [comment]
Cool, thanks @sstead !!!
