### ISSUE TITLE
Email - flaky password confirmation on signup

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1696]
Reference: https://github.com/openfoodfoundation/openfoodnetwork/pull/1697

Steps to replicate this bug:

- Go to Login modal -> Sign Up tab.
- Add an email and password.
- Leave "Confirm password" field blank.
- Click "Sign Up".
- Sign up is completed successfully without confirming password... 😞 

If an incorrect password is typed into the field, the validation works correctly and doesn't allow sign up when the button is clicked, and displays a message. If the text in the field is then deleted so that it is blank, the validation continues to work and shows the correct warning message.

So it seems if the field is left untouched it gets ignored completely, but after it's been touched it works correctly.

![screenshot from 2017-07-15 14-06-59](https://user-images.githubusercontent.com/9029026/28239576-23518eca-6967-11e7-84f2-7e259628b5e3.png)
![screenshot from 2017-07-15 14-07-07](https://user-images.githubusercontent.com/9029026/28239575-235181b4-6967-11e7-8857-8838a7f654c2.png)

**Comment by sauloperez** [comment]
I just encountered this. I think we should raise the priority of this bug. It's not only a bit flaky in terms of UX but also gives a bad image of how we deal with security.

**Comment by daniellemoorhead** [comment]
@sauloperez this should be fixed as part of the work @Matt-Yorkley and @ltrls are doing implementing email confirmation functionality.

**Comment by Matt-Yorkley** [comment]
Actually @daniellemoorhead I think this one is ok to go through as a standalone bugfix. It's a small amount of code and it's not really tied up with the other email branches.

**Comment by daniellemoorhead** [comment]
PR merged so closing issue
