### ISSUE TITLE
Cannot add product properties

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1699]
Clicking on the `ADD PRODUCT PROPERTIES` button nothing happen.

![add](https://user-images.githubusercontent.com/748971/28267329-f6d02386-6af9-11e7-829a-a6cb3440216f.png)

After clicking on the button the following error shows up in the console:

```
TypeError: el.attr(...) is undefined
```

**Comment by enricostano** [comment]
I'm still not sure if this is a regression related to the step 6 of Spree upgrade or it's broken in `master` too.

Maybe @mllocs or someone else could help trying to reproduce it in `master` branch.

**Comment by enricostano** [comment]
Ouch I was using a different user, who doesn't own the enterprise... we should not even show that buttons IMHO

**Comment by oeoeaio** [comment]
Out of interest @enricostano, how did you even get to that page if your user doesn't manage the producer of "Fuji Apples"?
