### ISSUE TITLE
Alternate backgrounds to product list not retained when deleting items from order

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1710]
Another issue I spotted while testing spree upgrade...
![image](https://user-images.githubusercontent.com/10843056/28447633-4ff1368a-6e15-11e7-89d0-98fc696311e2.png)

**Comment by sauloperez** [comment]
@oeoeaio @RohanM do you have any idea how is this implemented? I know we're using [Rails' cycle helper](http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-cycle) but I can't manage to find how we update the `class` on the `tr` dom element once a row is deleted. Do we do it from angular or from some hidden jQuery snippet?

**Comment by oeoeaio** [comment]
Hey @sauloperez, this is all vanilla Spree behaviour. I'm not sure what is happening with Spree step 6, but the version we are using seems to handle to removal of the row and update of the row classes from `core/app/assets/javascripts/admin/admin.js.erb`.

**Comment by sauloperez** [comment]
Good to know. Now I know where to investigate. Thanks!

**Comment by sauloperez** [comment]
We can't manage to find how our current version of Spree implements this behaviour. Given that it's not big deal we prefer to focus our efforts on more prioritary bugs. That is something that will surely be fixed in Spree 2.0.

Maybe you @morantron can take a look with your frontend wizardry skills?

**Comment by sauloperez** [comment]
This is deployed already in https://staging1.openfood.com.au. Can you test again, please?

**Comment by sstead** [comment]
Yes, this is fixed.

**Comment by sauloperez** [comment]
thanks a lot for the testing @sstead !
