### ISSUE TITLE
new Open All Adjustments and Close All Adjustments buttons

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1712]
These buttons came up during Spree upgrade testing. I haven't noticed them before, and they are not on Production. They give the Snail Page, so perhaps it's better if they are not there.

It shows both when creating an order, and when editing an order.

![image](https://user-images.githubusercontent.com/10843056/28451267-987e3bb8-6e2f-11e7-85f0-1d917f611c22.png)

**Comment by sauloperez** [comment]
As per my investigation on Spree, these two buttons where introduced in https://github.com/spree/spree/commit/43a3cca49. For the reasonable solution would be fixing the links to avoid the snale page (if possible) and so we avoid diverging from Spree in the middle of the upgrade. 

The more we diverge from Spree the more effort the upgrade requires.

**Comment by sauloperez** [comment]
Solved in https://github.com/Em-AK/openfoodnetwork/pull/14

**Comment by sauloperez** [comment]
The fix is already in the step 6 main branch. We will ping you @sstead once the branch is deployed again in staging.

**Comment by sauloperez** [comment]
This is deployed in staging1. Can we test it again @sstead ?

**Comment by sstead** [comment]
@sauloperez when I click on the Open All/Close All I get Authorisation Failure. I can add a new adjustment with no problem. Could this be related to the Authorisation Failure as part of https://github.com/openfoodfoundation/openfoodnetwork/issues/1693?
![image](https://user-images.githubusercontent.com/10843056/28950155-ed633220-7904-11e7-8db8-0e46e4c43b64.png)

**Comment by sauloperez** [comment]
Definitely related to https://github.com/openfoodfoundation/openfoodnetwork/issues/1693

**Comment by enricostano** [comment]
Nope, it seems related to something else

**Comment by sstead** [comment]
I just tested 1693 and it is fixed. But this error remains.

**Comment by sauloperez** [comment]
Yep @sstead, and thanks again for testing :tada: !

The plan is now to remove the feature completely as it seems it's not fully implemented until Spree 2.0. Better to have all of it than trying to fix something unfinished. We will let you know when you can test again.

**Comment by sauloperez** [comment]
This is deployed already in https://staging1.openfood.com.au. Can you test again, please?

**Comment by sstead** [comment]
Yes, these buttons are removed, which fixes the problem.

**Comment by sauloperez** [comment]
thanks a lot @sstead !
