### ISSUE TITLE
NoMethodError canceling an order from admin

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1715]
### Context
This issue has been found testing Spree upgrade step 6 https://github.com/openfoodfoundation/openfoodnetwork/pull/1524

### Steps to reproduce
 1. create an enterprise as **producer SHOP**
 2. create an order with a customer
 3. log in as the enterprise owner and go to `/admin/orders`
 4. edit the order, clic on **Actions** dropdown and select **Cancel Order**

### Screenshots
![2017-07-21-144522_1366x768_scrot](https://user-images.githubusercontent.com/748971/28463931-3e98b97c-6e23-11e7-9fdf-0c1212ba10ad.png)

**Comment by enricostano** [comment]
Could be related to https://github.com/openfoodfoundation/openfoodnetwork/pull/1524/commits/27f08fe0db2a510245193459f12733698a80abfb

**Comment by sauloperez** [comment]
Yep, this is due to a missing `Spree::MailMethod`. I suggest we add it to the seed data at least temporally until we reach Spree 2.0 with the step 7.

Check out my commit.

**Comment by sauloperez** [comment]
solved by https://github.com/Em-AK/openfoodnetwork/pull/13
