### ISSUE TITLE
Remove authorize_admin override

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1716]
### Context
In [Spree::Admin::BaseController#authorize_admin](https://github.com/openfoodfoundation/openfoodnetwork/blob/155a2574bb514b2aba4b2a23eddb9a1e68ec5b93/app/controllers/spree/admin/base_controller_decorator.rb#L18) we override the method since the old Spree version used to return `Object` when a model doesn't exist.

This override is not needed anymore since https://github.com/spree/spree/commit/46b91eec6b3bce5e0ff46da813183225104f0257

Our code:
```ruby
  # Override Spree method
  # It's a shame Spree doesn't just let CanCan handle this in it's own way
  def authorize_admin
    if respond_to?(:model_class, true) && model_class
      record = model_class
    else
      # this line changed to allow specificity for each non-resource controller (to be consistent with "authorize_resource :class => false", see https://github.com/ryanb/cancan/blob/60cf6a67ef59c0c9b63bc27ea0101125c4193ea6/lib/cancan/controller_resource.rb#L146)
      record = self.class.to_s.sub("Controller", "").underscore.split('/').last.singularize.to_sym
    end
    authorize! :admin, record
    authorize! action, record
  end
```

New Spree 2.0 code:
```ruby
  def authorize_admin
    if respond_to?(:model_class, true) && model_class
      record = model_class
    else
      record = controller_name.to_sym
    end
    authorize! :admin, record
    authorize! action, record
  end
```

### What needs to be done
Once we get Spree 2.0 we can remove our override and test that everything is OK.

**Comment by sauloperez** [comment]
Good catch @enricostano !

**Comment by luisramos0** [comment]
@kristinalim could you have a look at this one please?
I dont think I understand this commit: https://github.com/openfoodfoundation/openfoodnetwork/commit/01d4b8fb1037facf0cc0f0c3d245a3cd34241422

Is your commit above needed or can we still drop the override as initially suggested?

**Comment by luisramos0** [comment]
@kristinalim please ignore, I just realized this can only be done after the specific commit is in our spree version and this commit is _not_ in our spree 2-0-4. This can only be done after the spree upgrade.

**Comment by luisramos0** [comment]
Removing the reference to #2109, it's already in epic #2584 (all the issues blocked by the spree upgrade).

**Comment by lin-d-hop** [comment]
CLosing as it doesn't seem to be causing problems and we don't seem to be getting to it:)
