### ISSUE TITLE
Tag rules not working on UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1717]
I have set up a variant tag rule called 'trade' on the new shopfront for Purely Pickled Eggs and the rule is not working (the variant should be invisible by default and it is visible).  @OliverUK has tested a similar rule on the Stroudco shopfront and is having the same problem.
![image](https://user-images.githubusercontent.com/10517702/28471234-5f6deda0-6e34-11e7-909f-8a6a9c301c59.png)

**Comment by lin-d-hop** [comment]
Duplicate of #1664. Closing.
