### ISSUE TITLE
The 'show profiles' filter in the Shops directory is not working

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1718]
Expected functionality: By default the Shops page only shows shops that have a currently open order cycle. Profile-only hubs don't show unless the user clicks 'show profiles'. On Aus production this isn't happening, clicking the checkbox does nothing.

![image](https://user-images.githubusercontent.com/10843056/28487690-9cc8ee8e-6ed9-11e7-809d-5db0fc5e60c9.png)

**Comment by daniellemoorhead** [comment]
@kirstenalarsen this is a pretty bad experience for our users. Should we get it up the to do list and paid for out of AU funds?

**Comment by kirstenalarsen** [comment]
do we have a milestone or project or something that is ‘aus priorities’? If so, can we put it there and discuss whether there are any ‘aussie funds’ w serenity next week?
