### ISSUE TITLE
Typo in the shopfront, on properties filter buttons

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1721]
Typo in the shopfront, on properties filter buttons. 

![image](https://user-images.githubusercontent.com/10843056/28599452-07ba771e-71ee-11e7-972f-62d52260ee4a.png)

**Comment by sauloperez** [comment]
[This](https://github.com/openfoodfoundation/openfoodnetwork/commit/ef488133e#diff-ac406701b25523fd6e29778c25d99962R8) seems to be the culprit commit. Hope this makes it easier to fix.

**Comment by daniellemoorhead** [comment]
Fixed so closing.
