### ISSUE TITLE
Misalignment on Account page

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1722]
There is misalignment of text on the Account page, depending on whether the shop has a logo or not. Can we fix this so that the balance always aligns to the right?

![image](https://user-images.githubusercontent.com/10843056/28600714-1de1776e-71f7-11e7-9bd3-90da90089fbb.png)

**Comment by jdiejim** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by sstead** [comment]
All yours @jdiejim !

**Comment by daniellemoorhead** [comment]
Hi @jdiejim, good to have you onboard!

Not sure if you've been invited to our slack team by anyone on here (or if you've come through to the repository via chatting to someone about getting involved), but if you need an invite send an email to hello@openfoodnetwork.org and @sstead can set you up. Cheers 😄
