### ISSUE TITLE
[Stripe] Upgrade API to latest version

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1726]
### Overview
While we have been developing the Stripe integration, there have been updates to the API. We should assess what these are and then upgrade to the version of the API we are using to the latest version. This may require making changes to the codebase, but it may not.

UPDATE: The version we have been testing with on staging is `2017-05-25` and there has only been one minor update to the API since then ([2017-06-05](https://stripe.com/docs/upgrades?since=2017-05-25#2017-06-05)), so perhaps this is a non-issue.

### Tasks
- [x] Bump API version to latest on staging before next round of testing, to verify that everything is working

**Comment by luisramos0** [comment]
this was duplicated in #4640 
I'll close this issue and keep the most recent #4640 so that we keep the most recent info.
