### ISSUE TITLE
Can we simplify setup of Paypal by providing dropdown options or hiding fields and setting defaults

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1730]
Paypal is fiddly to setup and there's lots of room for human error.
Suggestions below:

![image](https://user-images.githubusercontent.com/10843056/28608245-f10ccd7a-7222-11e7-9441-b50d043b29b9.png)

**Comment by lin-d-hop** [comment]
All very good ideas from Sally. As enterprises only have to do this once the pain we allieviate is pretty small. Most users figure it out with the great user guide. #gitcull
