### ISSUE TITLE
[Stripe] Document charge process in GitHub wiki

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1733]
### Overview
The technical approach used to integrate Stripe into the OFN needs to be documented for posterity, so that other developers can understand what the hell is going on. Good starting point in #1466

### Tasks
- [x] Add a document to the GitHub wiki detailing the approach used to integrate Stripe into the OFN

**Comment by RachL** [comment]
@luisramos0 @lin-d-hop something we need to do as part of Stripe SCA? Or something we just want to close?

**Comment by luisramos0** [comment]
It's a good issue! I think it's worth doing it now that I still remember what is going on. I can spend 1/2 hours writing a tech doc. It will be very useful for anyone taking over work on our stripe integration. I wish I had one when I started.

**Comment by andrewpbrett** [comment]
I added [this page](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Stripe) to the wiki. @sauloperez could you read it over and close this issue if you feel it's sufficient? If you want to make edits directly feel free.

**Comment by sauloperez** [comment]
That looks great @andrewpbrett :+1:
