### ISSUE TITLE
Reports index is attempting set the description on sales tax reports which aren't loaded

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1734]
### Problem
Reports are loaded into the index page based on which ones the user has permission to view. Permissions are determined by the types of enterprise that a user manages, and are determined in `ability_decorator.rb`. At the moment, users who manage producer enterprises only (and no shops) do not have permission to view the sales tax reports, so they are not loaded.

The issue is that on we're trying to [set a description on for the sales tax reports](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/spree/admin/reports_controller_decorator.rb#L36) anyway, resulting in the request failing with a `NoMethodError`.

From Bugsnag:
![screen shot 2017-07-27 at 5 52 01 pm](https://user-images.githubusercontent.com/2067859/28660121-2369e974-72f5-11e7-879b-2dd523b6cb14.png)

### Solution
I guess we either just allow producers to see the sales tax reports, or we check that each report exists before adding a description to it. @sstead can you think of any particular reason why producers shouldn't be able to see sales tax reports? They seem to have access to pretty much ever other kind of report...

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**NoMethodError** in **spree/admin/reports#index**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/597966437d1fd70019261fc1?event_id=597966437d1fd70019261fc0&i=gh&m=li)

**Comment by sstead** [comment]
Is this related to this? - https://github.com/openfoodfoundation/openfoodnetwork/issues/1526

**Comment by oeoeaio** [comment]
Yep! Same issue. Closing now.
