### ISSUE TITLE
When i use 'print invoice' for a long order it has display errors on second page

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1738]
If an order is long enough to cover 2 pages the 'print invoice' invoice has display issues. This occurs for both invoice types.

![image](https://user-images.githubusercontent.com/10843056/28700435-1fd0629a-7393-11e7-9d59-2c7399fae232.png)

![image](https://user-images.githubusercontent.com/10843056/28700448-2f22ae7e-7393-11e7-9657-16211fa8a429.png)

*Steps to reproduce*

* Create an order with at least 35 items.
* Go to admin / orders / edit order: choose "print invoice" from the actions dropdown.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Invoices & Second Page](https://trello.com/c/jYZOFZNa/83-invoices-second-page)

**Comment by sstead** [comment]
@daniellemoorhead we've had a user in Australia request that this is fixed, how can we speed it along? Should we shift it to Aus Current? Or @sineadfenton any chance you guys can tackle it soonish?

**Comment by daniellemoorhead** [comment]
@kirstenalarsen are we able to get @mkllnk to fix this bug for AU?

**Comment by kirstenalarsen** [comment]
sure . .

**Comment by daniellemoorhead** [comment]
@mkllnk can you also add this to your list :)

**Comment by sstead** [comment]
@mkllnk josh from Synchronicity farm has asked about this a couple of times. Any way to speed it up?
