### ISSUE TITLE
If instance doesn't have thermal printing activated hide additional invoice options from enterprises

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1740]
It's my understanding that these fields in enterprise business details are only used in the thermally printed invoices.

![image](https://user-images.githubusercontent.com/10843056/28705267-616d15b2-73b2-11e7-9568-a91ea88bfc61.png)

If the instance has not got thermal printing activated, can the above fields be hidden? Otherwise people write things here and then wonder why they don't show anywhere.

![image](https://user-images.githubusercontent.com/10843056/28705304-7e4d3a9a-73b2-11e7-982e-6924aef25443.png)

**Comment by RachL** [comment]
The plan will be soon to remove completely this feature. Closing.
