### ISSUE TITLE
Simplify the Product Edit Screen

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1741]
Based on [this discussion...](https://community.openfoodnetwork.org/t/edit-product-page-ux-improvements/977)

Could we make adjustments to the Edit Product page such that the initial edit page looks like this:

![productdetails-new](https://user-images.githubusercontent.com/8669848/28715270-09589f36-738f-11e7-84f9-86836fadf998.png)

With a number of fields removed and the SEO and Bulk Buy Options moved to separate tabs:

![productdetails-bulkbuy](https://user-images.githubusercontent.com/8669848/28715275-0cf3a46a-738f-11e7-813a-50e5e785b53a.png)
![productdetails-seo](https://user-images.githubusercontent.com/8669848/28715276-0fd5fdf4-738f-11e7-82c6-30d6cd17fff3.png)

**Comment by sstead** [comment]
I've had another user get confused in the Edit Product area. Specifically she was trying to add variants... see image below with suggestion for how to improve...
![image](https://user-images.githubusercontent.com/10843056/28954486-0b03f29c-7923-11e7-9273-11a46b0ca775.png)

**Comment by Duende13** [comment]
Hi @sstead  and @lin-d-hop ,
Sally's changes are just related with Edit/New Variant Screen not Edit Product Screen, could we just create a new issue? Thank you!

**Comment by daniellemoorhead** [comment]
Sally is away @Duende13 so I created it for her - #1805

**Comment by lin-d-hop** [comment]
@sstead @oeoeaio could we queue this one for testing tomorrow.
Either this or multilingual will be on UK staging if that saves some time :-)

**Comment by daniellemoorhead** [comment]
@Duende13 @lin-d-hop which PR is this linked to? I couldn't find it referenced on this issue.

**Comment by oeoeaio** [comment]
@daniellemoorhead #1823, it went through on Friday

**Comment by daniellemoorhead** [comment]
Closing this one @lin-d-hop, reopen if this isn't correct.
