### ISSUE TITLE
Producer description missing text on profile selection  OFN UK

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#1743]
When a new enterprise is setting up they're asked to select what profile they want.

The second profile "Producer Shop" still uses a translation. Can the below (if it can..) be deleted and inline with the others which just use p.description in that area

<span class="translation_missing" title="translation missing: en-GB.admin.enterprises.change_type_form.producer_description_text2">Producer Description Text2</span>

![image](https://user-images.githubusercontent.com/28807449/28744392-bbfe44e2-7457-11e7-8091-501f165edc02.png)

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Producer Translation Text](https://trello.com/c/jnvIXmZG/71-producer-translation-text)

**Comment by sineadfenton** [comment]
@NickWeir63 just as a thought, the second box should say something different right? It says the same as the first, but perhaps 
"Add your own products and sell through the Open Food Network"

(Might explain my confusion earlier over on Slack)

**Comment by enricostano** [comment]
This should be fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/1622

**Comment by daniellemoorhead** [comment]
#1622 was merged 21 days ago (and part of the July dot point release) and this issue was created 13 days ago. 

@sineadfenton are you guys on the latest version yet?

If you are and this is still occurring then #1622 doesn't fix it. If you aren't then I would suggest getting the updated version onto production and then test if it's still a problem :)

**Comment by sineadfenton** [comment]
All good on this one
![image](https://user-images.githubusercontent.com/28807449/29248569-05a786c8-8013-11e7-9835-4ee689b3b0c8.png)
