### ISSUE TITLE
Standing Orders + Stripe: Ensure that payment totals for standing orders are correct before processing payment

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1751]
### Overview
Standing Orders are 'placed' when an order cycle opens, but the customer is not charged until the order cycle closes. In the interim, they are able to make changes to the contents of their order. We need to add some logic to `StandingOrderPlacementJob` to ensure that the payment total for the order is up to date.

### Tasks
- [x] Update the payment total for each Standing Order in `StandingOrderPlacementJob`. This means that orders changed by the customer after the order cycle is opened should still have payments for the final order total.
- [x] Make 100% sure there is a payment to process before we attempt to charge the card as per #1752

**Comment by daniellemoorhead** [comment]
done, merged.
