### ISSUE TITLE
Embedded shops require third-party cookies

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1754]
Some browsers deny third-party cookies. And security or privacy aware people change their browser setting to block third-party cookies as well. Embedded shops need third-party cookies to work. There is a work-around to open a new window setting a cookie. I found the following configuration still broken:

* Firefox ESR 52.2.0 with third-party cookies set to "From visited" or "Never"

The Allow Cookies button opens and closes a window, but the banner still shows up and loading of products doesn't work.

The only idea I have to solve this is to give people more options of how they can get around it.

* Link to a tutorial how to allow cookies.
* Visit the shop on the open food network.

Any other ideas?

@Matt-Yorkley 

![screenshot from 2017-08-04 11 29 17](https://user-images.githubusercontent.com/3524483/28950552-3415079a-7908-11e7-941b-ba2d1efe0282.png)

**Comment by Matt-Yorkley** [comment]
Okay, maybe it needs some adjustment. This workaround fixes the issue for the default Safari and iOS cookie blocking policies, but if a user has adjusted their settings manually to block third party cookies entirely they will need to manually enable them again or whitelist the site.

I think in this case where third party cookies are fully blocked, getting the user to visit the site wouldn't change anything. Perhaps we could just add a little more to the description? Something like:

"Click the button below to allow cookies for this site. If the issue persists you may need to adjust your browser settings for third party cookies."

**Comment by mkllnk** [comment]
Yes, it was just my browser setting that needed to be changed manually. Can we detect if the user tried to solve the problem already? I would add the option to go to the OFN then. A not embedded shop is better than a broken shop.

**Comment by Matt-Yorkley** [comment]
Unfortunately I think we can't detect if they tried to solve it already, as if they have the cookies fully blocked we can't save anything between page loads with sessions or cookies, so it will always appear to be the first attempt. Unless there's another solution?

**Comment by mkllnk** [comment]
After cookies have been enabled, we need to reload the shop page, right? If we append a URL parameter to indicate that we tried to set a cookie already, then we know that it failed.

**Comment by lin-d-hop** [comment]
Embedded shopfronts is not an officially supported feature. Depricated. #gitcull
