### ISSUE TITLE
Navigation around Enterprise Settings and Shipping/Payment methods

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1756]
Navigation around the Enterprise Settings is not always intuitive. This is one of the first places a user goes, so we should make it less confusing.

Use case: If I'm in Edit Enterprise > Contact details and I make some changes and click update, the page reloads, but I'm back on Primary Details. I would expect to be taken to the contact details page refreshed.

Use case: I'm setting up shipping and payment methods. I navigate to the New shipping method page, via my enterprise settings. When I'm done I'm redirected to a list page of my shipping methods, not back to the enterprise edit page (on the shipping method tab) as I'd expect. Same for payment methods. This is confusing, and I'm not sure where these three screens are or how they interconnect.

![image](https://user-images.githubusercontent.com/10843056/28954875-8eb7dd40-7925-11e7-8a6a-dafee090c66c.png)

**Comment by adamgunther1** [comment]
Hi there! First-time contributors and we're hoping to help out with this issue as an assignment for school. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by NickWeir63** [comment]
Hi @adamgunther1 welcome to OFN !  If you let me have your email address I will join you up to our Slack channel to help with communication.  My email is nick@openfoodnetwork.org.uk  This issue is not ladbelled as 'Rubies for Newbies' but I will ask @lin-d-hop to let you know if it is suitable for a first-time contribution.  

Thanks very much for getting involved.  Hope to meet you soon.

**Comment by adamgunther1** [comment]
Thank you, please let me know. Three of us are working on the issue and do have solid experience developing full stack rails apps and have been working with Ruby for close to a year.

**Comment by sauloperez** [comment]
Welcome @adamgunther1! Always happy to see new contributors! Your experience will come in handy.

**Comment by adamgunther1** [comment]
Hi, due to the timeframe for our assignment, this issue will require a lot of back and forth on UI/UX decisions, so we are going to offer to contribute on another issue. Thanks for the warm welcome!

**Comment by NickWeir63** [comment]
Thanks @adamgunther1 you might like to look at the issues labelled 'rubies for newbies' unless anyone @daniellemoorhead ? can suggest a quick issue for you to look at.  Thanks again

**Comment by audez** [comment]
Can i create a specific issue "[Admin] Don't jump to primary details after saving a change in Enterprise settings"?
I think with this and adding the shipment methods to the [Improve admin UX (journey) when managing payment methods #3728](https://github.com/openfoodfoundation/openfoodnetwork/issues/3728), we could close this one

**Comment by audez** [comment]
I close this one as it is covered by:
- #9753 for the refresh in Enterprise parameters
- #3728 &  #9754 for navigation issues in shipping and payment methods
