### ISSUE TITLE
Confusing UX on Delete Properties

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1759]
Update by Myriam 21.05.2018 to clarify what needs to be done.

## Description
While editing the product, there is an option to view 'PRODUCT PROPERTIES' This then shows any properties that have been assigned to the product. To delete a property you MUST click on the bin icon to the right of the product. Clicking the 'x' beside the property name does not result in a permanent removal of the property.

## Expected Behavior
This page would be much more clear and consistent with the rest of OFN if we simply stop the X appearing next to the property name. (See image, there is no X)
![tothis](https://user-images.githubusercontent.com/8669848/30022703-4d8ef37e-9164-11e7-9d8e-c4f90ab7759f.png)
The extra click for 'Update' is still obviously a UX sub-optimality however the user is warned before leaving the page if they haven't clicked save which is a big improvement to the current situation.

## Actual Behavior
See image, there is a confusing X
![thispart](https://user-images.githubusercontent.com/8669848/30022690-4187d96a-9164-11e7-91a4-fce80b84ac20.png)

## Steps to Reproduce
1. Go to "products", select one product and click "edit" then go to tab "product properties"
2. Try deleting a property using the X and/or the bin

## Context
Was reported by uk user https://community.openfoodnetwork.org.uk/t/deleting-product-properties/194

## Severity
S4

## Your Environment
PC, Retested on French production, Chrome

## Possible Fix
Remove the "X" on property label

**Comment by Matt-Yorkley** [comment]
@NickWeir63 It seems to work fine as long as you press the update button after adding or deleting properties.

**Comment by sineadfenton** [comment]
Hey @Matt-Yorkley,

We've just had a chat about this and all okay in terms of functionality, it's a UX issue.

"To remove a property we need to click the bin icon which is way over to the right of the property and that clicking the X does not make a permanent change" - users have been finding this quite confusing.

I believe @NickWeir63 will add some notes here to outline how this may work better - https://community.openfoodnetwork.org/t/user-guide-testing-feedback/217/25

![image 2](https://user-images.githubusercontent.com/28807449/29159866-00212a96-7da8-11e7-9d9d-0bf35135a62b.png)

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Product properties not deleting successfully](https://trello.com/c/B0ZE8H5t/77-product-properties-not-deleting-successfully)

**Comment by NickWeir63** [comment]
@Matt-Yorkley sorry to waste your time on this.  I have put [some notes up here](https://community.openfoodnetwork.org.uk/t/deleting-product-properties/194) to help other users who are confused by this.  In the long term it would be good if the bin icon could be moved to the left (between the 'name' box and the 'description' box (which is rarely used so looks like a blank space)) so that the bin icon appears next to the property rather than over on the right next to the menu list.

**Comment by lin-d-hop** [comment]
Solution Proposal

This page would be much more clear and consistent with the rest of OFN if we simply stop the X appearing next to the property name.

Let's update this:
![thispart](https://user-images.githubusercontent.com/8669848/30022690-4187d96a-9164-11e7-91a4-fce80b84ac20.png)

To this:
![tothis](https://user-images.githubusercontent.com/8669848/30022703-4d8ef37e-9164-11e7-9d8e-c4f90ab7759f.png)

The extra click for 'Update' is still obviously a UX sub-optimality however the user is warned before leaving the page if they haven't clicked save which is a big improvement to the current situation.

**Comment by lin-d-hop** [comment]
If not picked up by a newbie this fits in nicely with the work you are doing @Duende13

**Comment by sigmundpetersen** [comment]
In support of the suggestion :)

**Comment by myriamboure** [comment]
Ok I cleaned up this issue, it is ready to be picked. Maybe @rtrunkhill you would be up for that new issue now that you start to see how OFN works ;-) ?

**Comment by Matt-Yorkley** [comment]
I was going to try to help out @rtrunkhill with this dropdwon issue, but in UK production and my latest local version of master this page seems to be broken, so I'm not sure how to help. Maybe that's another issue!

**Comment by Matt-Yorkley** [comment]
For reference @rtrunkhill as per your quest for the missing views, this page is originally generated by the Spree gem, but we have some overrides for these views using Deface. The files in question can be found under `/app/overrides/spree/admin/product_properties/`.

**Comment by myriamboure** [comment]
I think @Matt-Yorkley you are connected as an admin that's why you see what you see and the properties are not proposed to you ;-) Connect as a regular user.

**Comment by Matt-Yorkley** [comment]
I still get this:

![screenshot from 2018-05-31 15-12-55](https://user-images.githubusercontent.com/9029026/40787326-3c882992-64e5-11e8-9814-54d4b64455f1.png)

...which doesn't look right. The delete buttons are missing and the actions heading on the table is gone.

**Comment by Matt-Yorkley** [comment]
Also, whenever I try to save using the update button I get bounced out of admin to the home page. My console shows a 302 redirect happens just before going to the home page, because the browser is incorrectly being sent to `/products/product-name` (which doesn't exist) instead of `/admin/products/product-name` after saving... :frowning_face: 

@myriamboure can you do a quick check to see if you get the same on OFN France? I'll open a separate issue for this if so.

**Comment by Matt-Yorkley** [comment]
I restarted my local rails server and now I can't replicate that issue either :see_no_evil: Maybe it's ok.

**Comment by myriamboure** [comment]
I don't understand your last comment @Matt-Yorkley I can replicate the error, if I click on the small x on the property label I have the impression it is deleted but when I save it is not, it reappears... what do you mean by "maybe it is ok"?

**Comment by Matt-Yorkley** [comment]
Sorry, I meant the second bug I encountered yesterday where it redirected to the home page after saving. It's not doing that now.

**Comment by anushreddy** [comment]
can i take a look at it?

**Comment by lin-d-hop** [comment]
Feel free to take a look and ask questions on Slack, Anush :-)

**Comment by HugsDaniel** [comment]
Anyone tackling this one at the moment ?
