### ISSUE TITLE
Missing translations in all.js

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1761]
@lin-d-hop encountered a broken sign-up form on the UK production server. It seems related to some missing translations in the compiled `all.js` file. We see the same on the Australian production server, but our sign-up form is working. From the file:
```
<span class=\"translation_missing\" title=\"translation missing: en-GB.spree.firstname\">Firstname</span>
```

There are eight `translation missing` errors in that file.

The visible errors on the UK production servers come from missing translations within Javascript.

    [missing "en.welcome_to_ofn" translation]

These are generated by i18n-js which is looking for `en` translations while the `en-GB` locale is included in the all.js asset file.

This could be related to the new i18n-js gem introduced in #1564, but it could also be a configuration issue on the UK server.

**Comment by daniellemoorhead** [comment]
Ping @lin-d-hop @Matt-Yorkley @sineadfenton

**Comment by lin-d-hop** [comment]
Thanks for looking into this @mkllnk. Personally I am still stumped. So is @Matt-Yorkley.

Since this is affecting no other servers I think UK configuration is not playing nice with the new i18n-js gem. Definitely not solved by rebuilding assets, clearing cache etc.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley also tried some things on UK staging in this PR
https://github.com/openfoodfoundation/openfoodnetwork/pull/1757

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Translation Text](https://trello.com/c/mJnXNtVt/82-translation-text)

**Comment by jeronimo** [comment]
Ok. So the problem is that registration page uses different layout which does not include 
<img width="466" alt="screen shot 2017-08-12 at 10 05 37" src="https://user-images.githubusercontent.com/88912/29239459-1710fa74-7f47-11e7-938c-0b7a19e2423b.png">
partial `_i18n_script.html.haml`

It exists in `darkswarm` and `admin`
<img width="421" alt="screen shot 2017-08-12 at 10 06 41" src="https://user-images.githubusercontent.com/88912/29239446-d499e5fc-7f46-11e7-98d9-de70dc330c9f.png">

But not the one that is used in registration.
<img width="924" alt="screen shot 2017-08-12 at 10 12 26" src="https://user-images.githubusercontent.com/88912/29239444-c4dc1216-7f46-11e7-9a29-1f69b68e5c16.png">

Quick fix: deploy server with `default_locale: en`. 
Normal fix: Add i18n-js related code to Spree generated layouts.

**Comment by lin-d-hop** [comment]
Officially fixed by @jeronimo 
#1765

Just for clarity:
#1764 is a patch for v1.8.13.
#1765 is on current master

Since no one else is experiencing the problem is is probably on to just make sure #1765 is merged before the next release.

Thanks everyone for putting the time in to fix this. This has been stressing me out for a week!

**Comment by mkllnk** [comment]
Great. That fix for the registration got merged. But there are still missing translations in the `all.js` file. There have been no reports to visible issues yet, but it is something that should be fixed. So I'm not closing this yet.

**Comment by daniellemoorhead** [comment]
Closed this as PR merged.

**Comment by daniellemoorhead** [comment]
@mkllnk I assume this can't be closed yet due to the remaining translations not being done yet? If this is the case can you please change the milestone to September? Thanks.

**Comment by mkllnk** [comment]
True, this still needs fixing, but at least all visible issues are fixed.

**Comment by daniellemoorhead** [comment]
REMAINING TO BE DONE FOR THIS ISSUE:
>...there are still missing translations in the all.js file. There have been no reports to visible issues yet, but it is something that should be fixed.

**Comment by myriamboure** [comment]
Just to  be sure it is connected, there are now a lot of pages with js.something.something untranslated things, is that related to that issue ? Should I open different issues for each page concerned ? 
![screenshot from 2017-09-05 19-54-01](https://user-images.githubusercontent.com/8135376/30075102-1a35f822-9274-11e7-8816-3f410ba69a01.png)
(I only see that when connecting with a non admin account btw)
![screenshot from 2017-09-05 19-57-36](https://user-images.githubusercontent.com/8135376/30075292-d3ad292e-9274-11e7-8c0e-8ec65362d83f.png) (see js.saving at the bottom)
![illustration3](https://user-images.githubusercontent.com/8135376/30075307-e5db72fe-9274-11e7-9b07-ec4b3103162a.jpeg)
Is UK still working on this ? Else I think @ltrls might have some time for that.

**Comment by sigmundpetersen** [comment]
Those strings are translated in Scandinavia and I can see them in Transifex. I also see that French is fully translated. Did you deploy the latest release from the transifex branch?

**Comment by myriamboure** [comment]
I guess you are connected with an admin account, I also see them translated with an admin account. Try with a regular user account and let me know if they are translated ?

**Comment by daniellemoorhead** [comment]
@sigmundpetersen did you check what @myriamboure suggested above?

I'd like to triage this issue, and either move it back into the backlog or ensure that it's being worked on and therefore worthy of sitting in the Code Review column.

Next steps for this?

**Comment by myriamboure** [comment]
@daniellemoorhead this was fixed and has nothing to do with this PR I think so I deleted the posts. Don't need to have a look @sigmundpetersen it's all good :-) Still we need to know how to move that forward. Should we close this and open a better specified bug issue? It seems this one was open for something specific to uk that were fixed. If there is no visible error, do we need to keep it open? Or wait for the need to be here to fix it? @mkllnk

**Comment by mkllnk** [comment]
I think we should open a new issue with low priority for the remaining missing translations and close this one.

**Comment by myriamboure** [comment]
I guess a dev who have access to the code should do it @mkllnk right? Cause as a user I have no idea what those missing translations refer to. Can you do it quickly? Else point someone else who can ;-)

**Comment by mkllnk** [comment]
I had another look and couldn't find any missing translations in the sign-up form. I'll close this one and we can open a new issue if we come across it.
