### ISSUE TITLE
Final test against re-provisioned AUS staging

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1769]
In https://github.com/openfoodfoundation/openfoodnetwork/issues/1711 we found out that the AUS staging server is out of date compared to the latest `ofn-istall` scripts. This was causing a subtle issue that took us quite a while to understand.

After AUS staging has been provisioned again with latest `ofn-install` scripts we would like to test step 6 using a snapshot of AUS production data. We already did something similar with a snapshot from UK production DB locally and it went OK.

After this last check we should be ready to go and merge https://github.com/openfoodfoundation/openfoodnetwork/pull/1524 into `master` 🎉 

cc/ @kirstenalarsen @mkllnk @oeoeaio @RohanM @sauloperez

**Comment by daniellemoorhead** [comment]
Hey @enricostano given we've pushed to aus production do we need this issue anymore? Can it be closed?

**Comment by enricostano** [comment]
🎉
