### ISSUE TITLE
Property and category badges appear clickable in product description modals in shops

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1770]
The property and category badges in product description modals, within shops appear clickable even when there's no description attached. The property badge should be clickable IF there's a product description attached (Correct behaviour is that when the mouse hovers over the badge the description pops up). The category badge should never be clickable. See below.
![image](https://user-images.githubusercontent.com/10843056/29444387-97a3bfb6-8422-11e7-9374-5f142fa36e6c.png)

**Comment by myriamboure** [comment]
The only issue I see is that there is no way to see the producer properties if you don't click on this "product description field". In https://github.com/openfoodfoundation/openfoodnetwork/issues/1546 I explain that we need to make it possible for the customer to see the products certificates (if they are organic for example the producer can publish the certification to prove it) so instead I would suggest to leave it like that but if no description have been added to the product, add a template text like : _"No description for the product"_
Else if we want to hide the product description button if no description is set up we need to rethink a bit the shopfront ux and, for instance, put the label somewhere on the product line, maybe below the Farmer name with small buttons (that will be clickable to show the certificate document if uploaded).
What do you think @sstead ?

**Comment by myriamboure** [comment]
Closing in favor of https://github.com/openfoodfoundation/openfoodnetwork/issues/1546 that seems to cover it.

**Comment by myriamboure** [comment]
If you disagree @sstead feel free to reopen, 1546 have been captured in an icebox item :-)
