### ISSUE TITLE
New missing translations

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1772]
When testing on French staging before upgrade, I noticed that there are still a lot of untranslated things, but just reporting here some new annoying:

In https://staging.openfoodfrance.fr/admin/enterprise_relationships

![screenshot from 2017-08-19 20-09-35](https://user-images.githubusercontent.com/8135376/29489169-b4831214-851a-11e7-93b5-8311d903bd0f.png)

Can you take care of that @pacodelaluna ?

**Comment by myriamboure** [comment]
I add also this one in inventory:
https://staging.openfoodfrance.fr/admin/inventory

![screenshot from 2017-08-19 20-15-57](https://user-images.githubusercontent.com/8135376/29489188-4f7e9914-851b-11e7-8c33-b957d68dbf3d.png)

**Comment by myriamboure** [comment]
Can it be linked to https://github.com/openfoodfoundation/openfoodnetwork/pull/1735 ? I don't think so, just mentionning it in case...

Oups I just realized there were lots of new strings in Transifex, I guess that will solve this issue :-o I'll do those translation tomorrow @pacodelaluna so we can test if that work, sorry, I should have checked first, still a bit disconnected, week-end work :-p

**Comment by enricostano** [comment]
Related https://github.com/openfoodfoundation/openfoodnetwork/pull/1771
