### ISSUE TITLE
Desindex unvisible shops in google search

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1773]
When I search by the name an entreprise that has an unvisible shop in Google, it appears as first link... if they are unvisible, this is because they don't want to be search... can we desindex the unvisible shops in Google/other search tools ?

**Comment by myriamboure** [comment]
@ltrls is it something that is specific to each instance or is it needed to discuss and reach a consent by the community ? It sounds to me like more instance based...
I discussed with the invisible hubs and they all don't want to appear in google searches, so we need to move forward.
One question : if they are desindexed through OFN but embed their shopfront in their own website, I guess as the url will be different that won't have any impact, they can stay indexed from their own website ?
Ping @daniellemoorhead how have you done in Australia ? And @lin-d-hop in UK ?

**Comment by sauloperez** [comment]
This is the way to do so https://support.google.com/webmasters/answer/93710?hl=en

**Comment by daniellemoorhead** [comment]
I think @oeoeaio and @mkllnk can probably tell you better than I what the AU team have done @myriamboure...or maybe @kirstenalarsen?

**Comment by mkllnk** [comment]
That should be a very easy code change to include the mentioned meta tag.

**Comment by myriamboure** [comment]
@pacodelaluna do you have time to work on that in the coming days ? We just tested with @RachL and the french staging server is also still visible on google when you type "staging open food france"... I can create another issue but if you work on that one maybe you can desindex staging at the same time ? Please let me know if you can't work on it, I will try to see with @ltrls find someone else to do it as we really need to move forward... I know you are super busy at the moment, so just let me know ;-)
