### ISSUE TITLE
Missing translations in order cycle page

### ISSUE THREAD

**Issue by sseerrggii** [openfoodfoundation/openfoodnetwork#1778]
![2017-08-29-133521_1920x1080_scrot](https://user-images.githubusercontent.com/2297137/29819086-67e86830-8cbf-11e7-97c6-8a6833c6bb3f.png)

**Comment by sauloperez** [comment]
The `selected` copy in the `productos` column is also missing

**Comment by sauloperez** [comment]
Solved in #1789
