### ISSUE TITLE
Missing translations in register enterprise

### ISSUE THREAD

**Issue by sseerrggii** [openfoodfoundation/openfoodnetwork#1779]
![contact0](https://user-images.githubusercontent.com/2297137/29819639-c86c66fa-8cc1-11e7-8a0e-9153eb7dc9fa.png)
![contact](https://user-images.githubusercontent.com/2297137/29819641-ca926808-8cc1-11e7-9873-ba82ce5fc954.png)
![contact2](https://user-images.githubusercontent.com/2297137/29819642-cca03a80-8cc1-11e7-94b5-6a167240ba19.png)

**Comment by sauloperez** [comment]
Might be related to https://github.com/openfoodfoundation/openfoodnetwork/pull/1763

**Comment by sauloperez** [comment]
It is very likely that solution will be the same as in https://github.com/openfoodfoundation/openfoodnetwork/pull/1789

**Comment by sauloperez** [comment]
`Back` and `Continue` are already translated in `config/locales/es.yml`. It must be that we translated them after the version we have deployed in alpha.katuma.org

**Comment by saimonmoore** [comment]
I'm taking over this.

**Comment by sauloperez** [comment]
Solved by https://github.com/openfoodfoundation/openfoodnetwork/pull/1820
