### ISSUE TITLE
Missing translations in account view

### ISSUE THREAD

**Issue by sseerrggii** [openfoodfoundation/openfoodnetwork#1780]
![2017-08-29-135753_1920x1080_scrot](https://user-images.githubusercontent.com/2297137/29819779-7198239a-8cc2-11e7-93e7-221d30ca33c7.png)

**Comment by sauloperez** [comment]
It is very likely that solution will be the same as in https://github.com/openfoodfoundation/openfoodnetwork/pull/1789

**Comment by saimonmoore** [comment]
Working on this.

**Comment by saimonmoore** [comment]
There are spanish copies in transifex already. Waiting for them to reach our repo.

**Comment by sauloperez** [comment]
@sseerrggii we will need to keep an eye on it. We should get this translations in next release.
