### ISSUE TITLE
Missing translations in new product page

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1784]
![new_product](https://user-images.githubusercontent.com/762088/29876243-8113150c-8d9c-11e7-98bf-c974151fe0ea.jpg)

**Comment by sauloperez** [comment]
It is very likely that solution will be the same as in https://github.com/openfoodfoundation/openfoodnetwork/pull/1789

**Comment by leandroalemao** [comment]
@sauloperez I'm picking this issue up as my first contribution, I mean having a go.. 😄 👍 Tks

**Comment by leandroalemao** [comment]
Hi @sauloperez I've just opened a new PR https://github.com/openfoodfoundation/openfoodnetwork/pull/1792.
I hope all good. 😄 👍 
Always glad to help
Tks.
Leandro.

**Comment by sauloperez** [comment]
Done in https://github.com/openfoodfoundation/openfoodnetwork/pull/1792. Thanks again @leandroalemao !
