### ISSUE TITLE
Modifying the product master price from the edit product page does not update the price shown in the shop page

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1788]
### What? Why?

When editing the master price of a product from the edit product page (see below), although the change is successfully saved the price shown in the shop isn't updated. See gif below.

![price_not_updated](https://user-images.githubusercontent.com/762088/29916905-8285140e-8e40-11e7-8744-97bbc230961d.gif)

To actually update the price listed in the shop, I need to go update the price in the variant:

![edit_variant](https://user-images.githubusercontent.com/762088/29916990-c49cbd06-8e40-11e7-805a-5cfdfd9292b0.gif)

To me this looks like a UX/UI bug. It is very counter intuitive for products for which the enterprise admin didn't add any variant. Her expectations is that updating the price from edit product page will update the price shown in the shop. **This is particularly relevant when onboarding new users to OFN as they are not aware of variants yet. Their products don't have variants.**

### What does vanilla Spree do?

As of Spree 2.0 (the version we aim for with upgrade's step 7), as opposed to OFN, when a product is created no variant shows up in the variants page. Then, when the master price in the edit product page is updated the one shown in the shop page is updated as well.

When new variants are added the product's master price is shown in the shop index page, while in the product details page only variant prices are listed, and compared to the master one. See screenshots below:

![shop_index](https://user-images.githubusercontent.com/762088/29917500-795fd8d0-8e42-11e7-9ff5-18b2799e393d.png)
![product_page](https://user-images.githubusercontent.com/762088/29917511-7cd979b2-8e42-11e7-93e6-2098e080999e.png)

You can check this out in our Spree demo site https://ancient-anchorage-61613.herokuapp.com/

username: `spree@example.com`
password: `spree123`

**Comment by sauloperez** [comment]
You can read the reason for this behaviour in https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1504139427000114

**Comment by sauloperez** [comment]
The last time checked this it didn't look like a 5min fix. It is related to the `master` variant and I don't think this ever worked so regardless of the actual solution we go for it might require a significant amount of backend work.

**Comment by luisramos0** [comment]
great analysis work!

**Comment by RachL** [comment]
FYI read in #2979 

> yeah, @myriamboure agreed as well. lets do it.
and we close #1788

So I'm closing this.
