### ISSUE TITLE
Submit login form on enter

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1790]
## What?

When hitting enter once the login form is filed in, the form is not submitting as opposite to the user's expectations. The sign up form next to it, however, it does submit the form on enter.

![login_form](https://user-images.githubusercontent.com/762088/29925720-875319a6-8e61-11e7-8167-4f530f08c897.png)

The login form should be submitted when pressing enter as well.

**Comment by yasirazgar** [comment]
looking into it

**Comment by sauloperez** [comment]
Awesome and thanks a lot @yasirazgar !

**Comment by yasirazgar** [comment]
@sauloperez, I checked this on mac, the login form is getting submitted on hitting enter, please let me know if I am missing something/

**Comment by sauloperez** [comment]
Perhaps it was simply slow :thinking:

**Comment by sauloperez** [comment]
Sorry my bad :sweat: I see it working in my localhost now. Sorry for the inconvenience. If you still want to contribute you can take https://github.com/openfoodfoundation/openfoodnetwork/issues/1799 or any of the ![good firt issues](https://github.com/openfoodfoundation/openfoodnetwork/labels/good%20first%20issue)
