### ISSUE TITLE
Bug in confirmation email from "notification" field

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1796]
A user want to add a producer as a manager so that the producer can add his products himself. He is not a user yet as the hub has set up his profile for him.
We use for the moment a workaround which is to type the email in the "notification" field to trigger a confirmation email to be sent so that the producer can be added as a manager. As suggested by @sstead .
There is a bug, I click on the link and I'm redirected to the OFN BUT I get an error message "unauthorized".
![screenshot from 2017-09-05 12-09-00](https://user-images.githubusercontent.com/8135376/30056919-f9849b0e-9234-11e7-9219-e32b9be359ad.png)

Can this be fixed quickly ? Who could fix that ? @Matt-Yorkley @ltrls is it connected to the work you have done on email confirmation ?

**Comment by daniellemoorhead** [comment]
@myriamboure I wouldn't see this as part of the email confirm work that @Matt-Yorkley and @ltrls are doing as none of it is live yet.

**Comment by daniellemoorhead** [comment]
The workaround for this is to have the manager sign up as a user of the OFN, which then makes it easy for the enterprise to assign them as the manager. At least this isn't completely blocked, the workaround is annoying but is there.

Suggestion would be, perhaps get @ltrls to work on #1593, rather than spend money on fixing the hack? By the time the bug is found and then fixed it may be easier just to have Pierre build the proper functionality....

**Comment by myriamboure** [comment]
No, actually this workaround doesn't work @daniellemoorhead as you need the user to be verified so that it appears in the available managers'list, and today, the only way is to create an entreprise, so it would mean the producer would have to sign up and create a new entreprise, and then will be able to be added as a manager to his first entreprise (created by the hub) so it would create a duplicate :-o

BUT the good news is that I tested again this morning an it seems to work again... I guess we have to wait for users validations to be functional for @ltrls to work on https://github.com/openfoodfoundation/openfoodnetwork/issues/1593 ? I'll check with him, but I agree with you anyway, closing this issue now.
