### ISSUE TITLE
Missing translations in the "nofify producers" email

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1798]
![illustration2](https://user-images.githubusercontent.com/8135376/30073687-ffda8c9a-926e-11e7-8928-d2cf4dd108f7.jpeg)

**Comment by ltrls** [comment]
The email subject is translated in my development environment, I can't see why it wouldn't work in production oO

**Comment by myriamboure** [comment]
I have re-tested and it's still the same for me... where can the issue come from ? Any idea @sauloperez or @enricostano do you have the same issue in Spain ?

**Comment by myriamboure** [comment]
Did you manage to understand the issue @ltrls ?

**Comment by myriamboure** [comment]
Seems like the key is in transifex since last May but it's not working...
![screenshot from 2017-10-04 17-23-28](https://user-images.githubusercontent.com/8135376/31184129-d9a1b7f8-a928-11e7-87b3-fe545aee7cac.png)

**Comment by myriamboure** [comment]
Title fixed with the upgrade on French production.
