### ISSUE TITLE
Missing translations in the "new shipping method" page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1799]
![illustration](https://user-images.githubusercontent.com/8135376/30076322-c3bbeaf6-9278-11e7-81d3-12896385ff1d.jpeg)

**Comment by myriamboure** [comment]
Hi @sauloperez I created a few more missing translation issues following your model should I add them to the September milestone as well ? Please do it if that seems reasonable to you ;-)

**Comment by daniellemoorhead** [comment]
Hey, if you're adding things to the september release then just the PRs, not the issues. Thanks :)

**Comment by sauloperez** [comment]
Being done in #1799

**Comment by g33kyshivam** [comment]
Hey @sauloperez . I would like to work on this issue !

**Comment by sauloperez** [comment]
Hi @g33kyshivam! Unfortunately @yasirazgar already worked on it in #1799 but you can check out https://github.com/openfoodfoundation/openfoodnetwork/labels/good%20first%20issue. There's plenty of work you can help with

**Comment by sauloperez** [comment]
DOne in #1921
