### ISSUE TITLE
Missing translations in "new product" page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1801]
comment : on the page title, the problem is probably not a translation one, just that the title remains the same as when you are on the main "products" page, but it should be different like "new product" so I guess you need to create a new string and add it somewhere ?

![illustration3](https://user-images.githubusercontent.com/8135376/30078406-56471176-927d-11e7-9c76-f295dc3fbea7.jpeg)

**Comment by sigmundpetersen** [comment]
#1784 duplicate?

**Comment by myriamboure** [comment]
Thanks @sigmundpetersen ! Seems there are 2 things that were not pointed in the previous issue : the page title and the image selection, as the other one is closed, I leave this one open, if you want to finish this off @leandroalemao that would be awesome :-) Nice to e-meet you btw !

**Comment by sauloperez** [comment]
I believe the image selection depends on the language setting of your machine as it is an operative-system-level UI element.

**Comment by myriamboure** [comment]
Ok I don't manage to test, not Ubuntu savy enough, but I'll try that tonight with my boyfriend :-o Still the title key needs to be added ;-)

**Comment by myriamboure** [comment]
@RachL Maybe you can test if you have a French language based system ? Do you see the image upload thing in French ? Thanks ;-)

**Comment by sauloperez** [comment]
> Still the title key needs to be added ;-)

yep, I'll take a look

**Comment by RachL** [comment]
@myriamboure yes it is in french ! 
![image](https://user-images.githubusercontent.com/6525576/30116077-d8a65768-931c-11e7-8509-3cb6f302f479.png)

However, the button "new product" does not work on the latest version of Firefox. I had to login on chrome to see this. Do you know if there is already an issue open for that ?

**Comment by myriamboure** [comment]
I don't think so @RachL but you can check by typing in the search bock on the issues page... and then please feel free to open your first OFN Github issue :-) Is it 55.0.2 ? It have this version and it seems to work on my computer.

**Comment by sauloperez** [comment]
Solved in https://github.com/openfoodfoundation/openfoodnetwork/pull/1814 @myriamboure

**Comment by leandroalemao** [comment]
Hi @sauloperez @myriamboure @enricostano @sigmundpetersen I've just opened the PR #1815 to fix the missing translations on edit products page.
I hope all good.
Tks
Leandro

**Comment by myriamboure** [comment]
Ok, we are happy to test when it's deployed somewhere if needed ;-)

**Comment by enricostano** [comment]
Closing this issue as solved by https://github.com/openfoodfoundation/openfoodnetwork/pull/1815

Many thanks @leandroalemao 🎉

**Comment by sauloperez** [comment]
Sorry @enricostano there was a misunderstanding here. Most of this issues was solved by @leandroalemao in https://github.com/openfoodfoundation/openfoodnetwork/pull/1792 but @myriamboure pointed out that we were missing the page title. This is still waiting for review in https://github.com/openfoodfoundation/openfoodnetwork/pull/1814

Meanwhile, @leandroalemao started working on the "edit product" page in #1815 which had its own issue https://github.com/openfoodfoundation/openfoodnetwork/issues/1785.

Let's wait for #1814 to close this. It's the last piece to have the "new product" page 100% translated.

**Comment by mkllnk** [comment]
#1814 has been merged.
