### ISSUE TITLE
Missing translations in main "products" page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1802]
comment : on the page title, it seems the key is missing in transifex, so it seems like an automatic translation from spree but which is not at all meaningful.
comment 2 : on the column header "nom" ("name") it looks like it is translated but I wanted to change the translation in transifex by "product/variant" to clarify following users feedbacks, and I realize there is also no key for that header, so I guess it was also an automatic translation from Spree...
![illustration](https://user-images.githubusercontent.com/8135376/30079102-58ebab42-927f-11e7-9cf5-3c1833ff94ef.jpeg)

**Comment by ltrls** [comment]
The title should appear in Transifex, if you can look for it by key it is: `spree.admin.products.bulk_edit.header.title`

**Comment by myriamboure** [comment]
Thanks, and yes the title is translating ok, I guess it was just a transifex branch not update on our server ;-)
