### ISSUE TITLE
Missing translations : calendar

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1803]
## Description
In order cycle page (but I guess it can happen in other calendar pages), the calendar needs to be translatable
![illustration](https://user-images.githubusercontent.com/8135376/30079271-f22e5b7e-927f-11e7-960d-05a81fef31be.jpeg)

## Step to reproduce
1. Log in as enterprise user or super admin
2. Go to the order cycles menu
3. Create a new order cycle or edit a current one
4. See the calendar dropdown
5. This dropdown also appears in the "reports" menu

## Severity
bug-s4: it's annoying, but you can use it

**Comment by luisramos0** [comment]
There are two types of calendars: datepickers where user can select a date (in the orders management page for example) and datetime pickers where user can select a datetime (in OC list and OC edit pages for example). This issue referes to datetimepickers.

I managed to translate date pickers in #3893 but I cant fix the datetimepickers...

I think the fix to translate datetime pickers will be similar to the datepickers, but I have not managed to find the trick...
For datetime pickers we may need to add the localization files of the plugin (something I didnt have to do to fix the datepickers).

Also, I have created #3894 to remove duplicated code around these pickers... we have 5 implementations of calendars in the code...

**Comment by rmklaus12** [comment]
This is a bugger, isn't it? Had a go at this, with experienced help, but no luck so far. I did dig up the syntax `.datetimepicker.setLocale('de');`, of which I tried multiple iterations with no luck. Will keep it assigned to me, as I want to keep working on it.

**Comment by luisramos0** [comment]
:muscle: it's hard, good luck!
The code is here /home/luisramos/dev/ofn/vendor/assets/javascripts/jquery-ui-timepicker-addon.js
No .setLocale there, just .regional.

see localization tab here:
https://trentrichardson.com/examples/timepicker/

it says we have to add our own translations!
So the solution could be to do:
```

$.datepicker.regional['ru'] = {
	**closeText: t('js.timepicker.closeText'),
	prevText: t('js.timepicker.prevText'),
   etc... for all of these:**
	nextText: 'След>',
	currentText: 'Сегодня',
	monthNames: ['Январь','Февраль','Март','Апрель','Май','Июнь',
	'Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
	monthNamesShort: ['Янв','Фев','Мар','Апр','Май','Июн',
	'Июл','Авг','Сен','Окт','Ноя','Дек'],
	dayNames: ['воскресенье','понедельник','вторник','среда','четверг','пятница','суббота'],
	dayNamesShort: ['вск','пнд','втр','срд','чтв','птн','сбт'],
	dayNamesMin: ['Вс','Пн','Вт','Ср','Чт','Пт','Сб'],
	weekHeader: 'Не',
	dateFormat: 'dd.mm.yy',
	firstDay: 1,
	isRTL: false,
	showMonthAfterYear: false,
	yearSuffix: ''
};
$.datepicker.setDefaults($.datepicker.regional['ru']);

```
I am not sure how to get the current locale in JS but that should be easy, even if we have to inject it from ther server side (I can show you how to do this if the rest works :+1:)

**Comment by RachL** [comment]
@luisramos0 @rmklaus12 wouldn't it be easier to use another tool that just fetch the language of the browser to display the calendar in the correct language? Another calendar could really improve our UX, and I think @Matt-Yorkley noticed a couple.

**Comment by luisramos0** [comment]
I think using another datetimepicker is a lot more work than this issue Rachel.
We shouldnt use the "language of the browser", we need to use the user locale.

**Comment by RachL** [comment]
hey @rmklaus12 how are you doing? As there hasn't been movement here since more than a month, I'm assuming you have no time anymore to work on it and will un-assign you. Please re-assign yourself if I'm wrong and you still want to work on it! Thank you :)

**Comment by rmklaus12** [comment]
Hey @RachL! So sorry, yes, happy to have this unassigned. I hope to still jump on some of the smaller translations issues, but I have started a full-time job (yay) that is taking most of my bandwidth ;-)
