### ISSUE TITLE
Add "tooltips" on main bulk edit product page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1804]
To improve the ux, after some users suggested it (after I explained them how to proceed as they didn't find alone), I propose to add some "tooltips" ("infobulles" in french, not sure about the translation) as it is done here on the "order" page to edit order or capture payments:
![illustration](https://user-images.githubusercontent.com/8135376/30079842-dec6a5da-9281-11e7-9a50-788ad30d5066.jpeg)

on the bulk edit page here:
![illustration3](https://user-images.githubusercontent.com/8135376/30079959-4e9d9c4c-9282-11e7-8812-9c33f82fb5b6.jpeg)

and of course the tooltip text needs to be translatable but that's obvious now ;-)

**Comment by myriamboure** [comment]
I guess there will be no objection if we add those tooltips ? @enricostano @sauloperez @sstead @lin-d-hop if any objection please voice it now !

**Comment by sauloperez** [comment]
No problem of course

**Comment by daniellemoorhead** [comment]
Hey @myriamboure the PR for this #1858 has not yet been merged. Are you sure you want to close this issue? Should it be reopened until the PR is merged?

**Comment by myriamboure** [comment]
Sorry, yep, I closed it too quickly ;-)
