### ISSUE TITLE
Non-clickable logo and shopname on shopping page

### ISSUE THREAD

**Issue by simoneluijckx** [openfoodfoundation/openfoodnetwork#1806]
A = action | P = problem | S = solution
**A:** I'm 'shopping' in customer mode and want to go back to the homepage of the shop
**P:** Logo and shopname are not-clickable
![image](https://user-images.githubusercontent.com/31434588/30100070-f4bac52a-932a-11e7-9e65-c49512634189.png)
**S:** perhaps the shopname and logo could be made clickable and lead to the same page as the 'about Simone's Sweet Shop' links to. Since I think people are used to clicking on picture and name, and then it will lead to something at least.

**Comment by daniellemoorhead** [comment]
I'm loving the fact that you're adding these to the repo @simoneluijckx - keep it up! They're so handy to have :)

**Comment by farmermel** [comment]
Hi there! First time contributors here (@ophdub @jorgeedperezga @j25bender) hoping to help out with this issue. We noticed nobody was assigned to it, but if there’s already a solution in progress we're happy to try helping out elsewhere. Thanks!

**Comment by sauloperez** [comment]
Hi @farmermel ! welcome to Open Food Network! feel free to pick it. You can also take a look at any of the [good first issues](https://github.com/openfoodfoundation/openfoodnetwork/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or the [severity 4](https://github.com/openfoodfoundation/openfoodnetwork/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug-s4) and [severity 3](https://github.com/openfoodfoundation/openfoodnetwork/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug-s3) bugs.

**Comment by Matt-Yorkley** [comment]
As a shopping / sales point: do we want links on an enterprise's shop page to be taking users away from their shop?

**Comment by myriamboure** [comment]
To be honest @farmermel I'm not sure about this issue, we are cleaning up a lot of issues and this one has not really been specified and needs to be discussed in term of UX. May I suggest you pick up 423 or 1538 or 1171 or 1384 for instance which are better specified ? Thanks a lot for your contribution and feel free to join our Slack https://openfoodnetwork.slack.com there is a  #dev channel there if needs be :-)

**Comment by farmermel** [comment]
Thanks for the update! We will find a different issue to tackle.

**Comment by lin-d-hop** [comment]
#gitcull
