### ISSUE TITLE
At checkout, button only shows 'Edit your cart'

### ISSUE THREAD

**Issue by simoneluijckx** [openfoodfoundation/openfoodnetwork#1808]
A: action | P: problem | S: solution

A: ordered 10 loafs: want to check out immediately
P: I can only click 'edit your cart', but I don't want to edit anything. It seemed to me as if I couldn't check out...
![image](https://user-images.githubusercontent.com/31434588/30100553-9b7e5678-932c-11e7-825a-47bd99deddef.png)
S: is it better if the button says 'check out' or is it then confusing if people would want to edit their cart? Or 2 buttons: 'check out' and 'edit cart'

**Comment by sauloperez** [comment]
I also feel the same. It's confusing when you just want to check out

**Comment by myriamboure** [comment]
Agree, maybe two button "see cart" and "checkout" ? a bit the same as what you have in top right corner but that lots of people don't see ;-)

**Comment by kirstenalarsen** [comment]
or one button “cart” - fairly standard next step in a checkout process?

**Comment by sauloperez** [comment]
Yep, let's check what is the standard. We're not inventing anything here.

**Comment by sauloperez** [comment]
![amazon](https://user-images.githubusercontent.com/762088/30107471-21084354-92ff-11e7-8b6b-2d8756e4d22e.png)
Fairly known marketplace does that :point_up:

**Comment by simoneluijckx** [comment]
Those 2 buttons look the best to me! Just one click and you go directly to what you wanna do.

**Comment by myriamboure** [comment]
Agree !

**Comment by kirstenalarsen** [comment]
needs to be put into a standard feature request template to be incorporated as papercut. Will pass the < 0.5 day test if that happens and is renominated

**Comment by RachL** [comment]
This button does not exist anymore. Closing.
