### ISSUE TITLE
Click buttons not visible when creating profile on OFN

### ISSUE THREAD

**Issue by simoneluijckx** [openfoodfoundation/openfoodnetwork#1810]
A: action | P: problem | S: solution

A: register on OFN as a hub/shop/etc.
P: I get an 'agree with the terms' window, but I can't see where to continue. You apparently have to scroll down to see that button.
![image](https://user-images.githubusercontent.com/31434588/30101359-5f614bf2-932f-11e7-9b0a-fef8515b61ba.png)
P: same happens when you need to tell if you're a producer yes / no. Have to scroll down for button to continue, but is not obvious. 
![image](https://user-images.githubusercontent.com/31434588/30101370-6ba452b0-932f-11e7-9674-65dd60ff8d9b.png)
S: make the buttons directly visible. --> easy and fast to click, no confusion/irritation for the user

**Comment by myriamboure** [comment]
100% agree :-)

**Comment by sauloperez** [comment]
sort of duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/1766

**Comment by daniellemoorhead** [comment]
Duplicate of #1766

**Comment by RachL** [comment]
@daniellemoorhead hey I didn't know you could mark things as duplicate! Does this mean this issue will be closed when #1766 is closed?

**Comment by daniellemoorhead** [comment]
Not sure @RachL. We should test that!

**Comment by sigmundpetersen** [comment]
So #3791 was merged and it didn't close this automatically, so we have now tested that 😊 Closing manually
