### ISSUE TITLE
Instagram link not working #ux #aus

### ISSUE THREAD

**Issue by simoneluijckx** [openfoodfoundation/openfoodnetwork#1811]
Action: clicking on Instagram icon on bottom window
Problem: leads to error page - link is not updated
![image](https://user-images.githubusercontent.com/31434588/30107150-42c241a6-9341-11e7-8c21-d00173d400e6.png)
Solution: update link to: https://www.instagram.com/openfoodnetworkaus/
Q: this is however on the general website (so for global users, it will lead to the aus account)
Idea: general Instagram account showing what's happening global, promoting the # use of #OFN #openfoodnetwork  ?

**Comment by daniellemoorhead** [comment]
Hey @oeoeaio or @mkllnk or @sstead or @kirstenalarsen do you know whether this is part of the config for the super admin, to change this, or is it hard coded?

**Comment by daniellemoorhead** [comment]
Hey @simoneluijckx is this on the global website? Can you add a link please? If it's for the wordpress site then we can fix that outside of the OFN codebase (and therefore it doesn't need to be a github issue so much as a message in the AU team slack channel).

**Comment by daniellemoorhead** [comment]
PS. That idea of a global instagram is lovely, but who would look after it? Maybe worth bringing up as an idea at the next global OFN hangout, next tuesday. You should come along to this and pitch the idea!

**Comment by simoneluijckx** [comment]
@daniellemoorhead this is the link: 
https://openfoodnetwork.org/ 
So the global OFN website. On the AUS website we don't have a link to Instagram, allthough we do have an AUS OFN instagram ;) 

And I saw this message too late to pitch at the global hangout :( I actually do have an idea ready ;)

**Comment by sstead** [comment]
Good spotting Simone! I've updated the link to the Aus instagram, but we can always change it if a global instagram evolves... I sense you have some ideas brewing :P
Here's where to change the link in Wordpress...
![image](https://user-images.githubusercontent.com/10843056/30462120-de1ae434-9a06-11e7-8029-62e0faf8198f.png)

**Comment by oeoeaio** [comment]
Yay! Thanks @sstead 👏
