### ISSUE TITLE
Customer signup email confirmation outdated

### ISSUE THREAD

**Issue by simoneluijckx** [openfoodfoundation/openfoodnetwork#1812]
Action: signing up as a customer
Problem: email is good, but the 'connect with us' links look a bit outdated and doesn't have the same style as on the website
![image](https://user-images.githubusercontent.com/31434588/30107573-83e9f3a8-9342-11e7-8369-73528d9c3c2a.png)
Solution: update and add Instagram and newsletter sign-up
![image](https://user-images.githubusercontent.com/31434588/30107788-27ffb428-9343-11e7-839e-858c17176cc8.png)
Q: is LinkedIn a medium that we want to use to connect with customers / shops? Is it still active?

**Comment by lin-d-hop** [comment]
Duplicate
