### ISSUE TITLE
Remove redundant enteprise registration I18n keys once new keys translated

### ISSUE THREAD

**Issue by saimonmoore** [openfoodfoundation/openfoodnetwork#1821]
See related PR here: After 7.0 release, should be able to translate the new keys created by https://github.com/openfoodfoundation/openfoodnetwork/pull/1820 and remove these redundant keys:

https://github.com/openfoodfoundation/openfoodnetwork/pull/1820/files#diff-37c9b835927e3c363588f172de9bb6faR1366

**Comment by sauloperez** [comment]
Do you mean the next release by `7.0 release`?

**Comment by saimonmoore** [comment]
Yes. The next release (I thought it was 7.0 because of this: https://github.com/openfoodfoundation/openfoodnetwork/milestone/58 which I saw Enrica added to the PR)

**Comment by saimonmoore** [comment]
lol :bear: :blonde_woman:

**Comment by saimonmoore** [comment]
Enrica don't hold any hard feelings...only soft ones :laughing:

**Comment by RachL** [comment]
@sauloperez were those keys removed?

**Comment by sauloperez** [comment]
Yep, @luisramos0 did in https://github.com/openfoodfoundation/openfoodnetwork/commit/ee8fe4b6b407356a9647692a0733c263bda2ccaf#diff-37c9b835927e3c363588f172de9bb6fa

**Comment by luisramos0** [comment]
yeah, this can be closed.
