### ISSUE TITLE
ActiveRecord::RecordInvalid in spree/admin/orders#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1826]
## Error in OpenFoodNetwork

**ActiveRecord::RecordInvalid** in **spree/admin/orders#update**
Validation failed: State is invalid

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/59b9ab57bf20b40018c56d0d?event_id=59b9abdd93bd8700171ce04b&i=gh&m=ci)

## Stacktrace

    app/models/spree/adjustment_decorator.rb:26 - set_absolute_included_tax!
    app/models/spree/adjustment_decorator.rb:22 - set_included_tax!
    app/models/spree/shipment_decorator.rb:7 - ensure_correct_adjustment_with_included_tax
    app/models/spree/order_decorator.rb:34 - block (3 levels) in <top (required)>

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/59b9ab57bf20b40018c56d0d?event_id=59b9abdd93bd8700171ce04b&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by mkllnk** [comment]
@oeoeaio @enricostano This is new on Aus production since yesterday, happened four times so far, same user. Could this be connected to to the Spree upgrade?

**Comment by oeoeaio** [comment]
@mkllnk Yep, I think so. I'm investigating now.
