### ISSUE TITLE
Appears that two adjustments are deleted when you delete just one.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1828]
It appears that 2 lines of adjustments are deleted after you first delete a single adjustment. This could confuse a user, and make them worry that more adjustments have been deleted than they intended.

![image](https://user-images.githubusercontent.com/10843056/30412906-4e719164-995e-11e7-8304-2781994ece05.png)

**Comment by myriamboure** [comment]
I'm not able to reproduce this error. I tried in different circumstances, so I'm closing it for now and we will reopen if it show up again.
