### ISSUE TITLE
Translation missing for 'product category cannot be blank' error, in new product.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1829]
@mkllnk could you please appropriately tag and direct this translation error, I'm not certain who works on translation related bugs.

![image](https://user-images.githubusercontent.com/10843056/30413000-f4e572cc-995e-11e7-9fab-4f98b3af96ad.png)

**Comment by daniellemoorhead** [comment]
@enricostano apparently this has happened as a result of the spree step 6 upgrade.

**Comment by mkllnk** [comment]
I'm taking this on because it's blocking one of my pull requests: https://github.com/openfoodfoundation/openfoodnetwork/pull/3006

**Comment by mkllnk** [comment]
This is actually not as easy as it looks. In `application.yml` we load all decorators early and the product decorator is loaded before the I18n module is initialised. I will look into two options:

- Loading I18n earlier to prevent similar bugs.
- Remove the message declaration and use the default ActiveRecord key for the translation.
