### ISSUE TITLE
Phone number not showing in Contact tab in shopfronts

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1832]
The contact phone number for an enterprise is not showing in the Contact tab in shopfronts. The contact number is showing on profiles in the directory and map however.

This feels like a possible task for a newbie - i'm not sure if it's angular or rubies though....

![image](https://user-images.githubusercontent.com/10843056/30460601-265fd382-99fb-11e7-81d0-3b3d452865c8.png)

**Comment by Mcents** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by Mcents** [comment]
Hi again! I noticed that the phone attribute on Enterprise is nil for most Enterprises. But the alternative_phone attribute on the spree_addresses tables does contain a number. Would you like the alternative_phone attribute used here? Thanks!

**Comment by sauloperez** [comment]
We should use the field that @sstead points out in the screenshot. That is the one enterprises fill form `/admin`
