### ISSUE TITLE
Quickbooks integration

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1833]
Quickbooks is a commonly used accounting package in Australia. OFN already has an integration with Xero that allows users to import their customer's invoices into the accounting package. This makes it easier for them to track whether invoices are paid or not in their accounting system. It would be great to offer something similar to users who use Quickbooks.

Quickbooks doesn't allow for direct import of CSV files. Instead their software works on the import of IIF files, which are .txt format. Could we generate a report which provides a IIF file of customer invoices for import into Quickbooks?

This page has templates which we could adapt our report from. https://community.intuit.com/articles/1501233

**Comment by RachL** [comment]
This is a feature request, I'm closing it has it is currently possible through Zapier. The rest must be discussed by opening a special thread in discourse.
