### ISSUE TITLE
Snail fails when trying to edit payments on orders 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1838]
Cannot add payment (fails when trying to update)
![image](https://user-images.githubusercontent.com/2911176/30531349-097161b2-9c91-11e7-87e4-d41841aaeb40.png)

Cannot open payment info from payments page
![image](https://user-images.githubusercontent.com/2911176/30531338-f74467c8-9c90-11e7-9b1b-f739e29567b8.png)

These are paypal payments originally, so not sure if connected to #1074 and #1837

**Comment by daniellemoorhead** [comment]
@kirstenalarsen do you want this focused on by the AU team? If so best put it into the Australian current project :)

**Comment by kirstenalarsen** [comment]
not necessarily, was just logging the bug, no idea how urgent it is in the
bigger scheme of things

**Comment by myriamboure** [comment]
@kirstenalarsen I tried to reproduce that bug but I don't have enough information about the context, the steps: did you pass an order from admin and when reaching payment stage don't manage to go forward? Was it an order passed by a customer online that you want to modify? Did you pass the order manually with option credit/debit card, finalized, and then wanted to change for Cash but couldn't? Please, provide more information if possible, else I suggest we close that and wait until it happens again.

**Comment by kirstenalarsen** [comment]
No idea. Close it :)
