### ISSUE TITLE
How to change the url for localization strategy ?

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1843]
![screenshot from 2017-09-20 10-56-03](https://user-images.githubusercontent.com/8135376/30635324-568a6b9e-9df2-11e7-9ffc-c57c47cab5a0.png)

See the url here is "https://www.openfoodfrance.org/sell", how can each instance change those to adapt it to local SEO strategies ? Like in France we would like to rethink all the url names so that we use relevant keywords and an understandable url (if someone share it for ex)

**Comment by sauloperez** [comment]
I'd first say what is the problem you're trying to solve?

**Comment by myriamboure** [comment]
I want the url to improve the SEO of the Open Food France website.
I also suspect it is reassuring for French users to see url text in French. But the main objective is SEO, put some relevant keywords in URL.
It's not super strategic if I share an url with a user of this given page where they can fin the various possible entreprises they can create to share with them a link with "sell" written on it...
@RachL did we have other arguments ?

**Comment by RachL** [comment]
@myriamboure Indeed URL with keywords could be very helpful in terms of SEO. I'm not an expert so I might be wrong, but I'm afraid it would imply a lot of work to personnalize URL per instances. Plus - if I'm not mistaken - if all instances use the same URL it stills improve the website's SEO, doesn't it ? 
That being said, maybe it would be great to have a written process on how to create an SEO friendly URL for each new page ? I don't know if it has be done already. It would prevent from having a URL like "sell". What do you think ?

**Comment by myriamboure** [comment]
Ok so for the French speakers I found two interesting posts [here](https://www.growthhacking.fr/t/url-en-francais-sur-notre-site-en-anglais/3575/2) and [here](https://yellowdolphins.com/2011/12/rediger-des-url-indexables-lisibles-et-seo-friendly/).
It doesn't seem to be so important in terms of SEO, but it is a good practice in terms of user experience from my understanding.
I'll invite Coralie in that discussion, who pointed that and might have some other arguments.

**Comment by sauloperez** [comment]
I understand having a clear an concise URLs helps a lot for SEO and UX but translating the URLs sounds like a huuuuge headache. Furthermore, I can't see the benefit.

In any case, URLs it's nothing we can change now. It'd break all links out there: email notifcations, orders and links shared anywhere. It's something to keep in mind for new features though.
