### ISSUE TITLE
"entreprise relationship" tab still not translated.

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1844]
Reference to PR https://github.com/openfoodfoundation/openfoodnetwork/pull/1771

In release note 1.8.14 the tab is supposed to be translated, we deployed it and it's not. No new string in transifex either but there was one existing already (maybe it's the same, not sure).
Not working either in Spain so it seems like a bug.

**Comment by enricostano** [comment]
More than a bug it seems that the `en.yml` key has not been imported in Transifex.

cc/ @mkllnk @sseerrggii

**Comment by mkllnk** [comment]
I'm sorry, the transifex branch was not updated after the last release. All I did now is `git push origin v1.8.14:transifex`. Within the next 24h Transifex will download `en.yml` from the transifex branch. The new text will then be available for translation. 100% translated languages will be committed to the transifex branch automatically. We really need to automated this more...

**Comment by enricostano** [comment]
> We really need to automated this more...

Yes please 🙏 @mkllnk let's talk one day to understand how we can tackle this one 💪

**Comment by daniellemoorhead** [comment]
In the meantime do we need to enforce in Australia that any release we do we MUST also update the transifex branch? Can it be something that we put in big letters on a wall somewhere in the australia office and that we remind each other each time we do a release?

(1. do we know which changes made it into the release? 2. are release notes done? 3. has transifex branch been updated)

**Comment by myriamboure** [comment]
Just tested, the tab is now translated :-)

**Comment by enricostano** [comment]
@myriamboure do you think this Transifex automatization is something that OF France could dedicate time to? It's pretty urgent IMHO and I guess @mkllnk will be pleased to get help there. What do you think?

**Comment by myriamboure** [comment]
Yes, I'm sure Augustin will be happy to work on that :-) I can't @ him yet (not in the Github team, waiting to be added ;-)) but I invite him here.

**Comment by myriamboure** [comment]
I mean on transifex automation discussion ;-)

**Comment by sauloperez** [comment]
That would be awesom! this process is way to slow for our current needs.
