### ISSUE TITLE
One tooltip is off the page on OC edit page

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1848]
Updated by Myriam 21.05.2018

## Description
One tooltip on order cycle edit page / "advance settings" can't be seen

## Expected Behavior
Tooltip can be read properly

## Actual Behavior
Tooltip can't be seen (Myriam just retested in 13inch screen for instance, so "regular" screen)
![image](https://user-images.githubusercontent.com/10843056/30726477-611a37a4-9f8e-11e7-8f8c-2181ca980282.png)

## Steps to Reproduce
1. You need to have one order cycle created already, then click on "edit" 
2. Click on "advance settings" button below the main menu
3. On this advance setting zone there is a tooltip below "choose products from", this tooltip is on one line only an can't be read properly.

## Context
Retesting to clean and specify old issues.

## Severity
S5

## Your Environment
PC, Aus production (+ French production), Chrome

## Possible Fix
Display tooltip on two lines?

**Comment by Ecksi** [comment]
Hi there! 

We are first-time contributors and we're hoping to help out with this issue. We noticed that nobody was assigned to it, but if there’s already a solution in progress we are happy to try helping out elsewhere.

Thanks!

**Comment by myriamboure** [comment]
Hey @Ecksi welcome here! You are most welcome to work on this, no one is working on it at the moment :-) Check the wiki, you'll find everything about how to commit a great PR, etc. Thanks in advance for your contributions!

**Comment by myriamboure** [comment]
This is free for someone to take!

**Comment by jonleighton** [comment]
It looks like @tonyr729 has proposed a fix for this in https://github.com/Ecksi/openfoodnetwork/pull/1, but it has been merged into a separate fork of the code. Perhaps it can simply be pulled in?
