### ISSUE TITLE
Broken tooltips in simple, producer-shop order cycle

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1849]
## Description
In **producer shop** order cycles 2 tooltips have lost their content.

## Actual Behavior
For the 2 tooltips below the content is not shown:
![image](https://user-images.githubusercontent.com/10843056/30726506-8fb3c8be-9f8e-11e7-9cf5-683235f47438.png)

## Expected Behavior
Here's what the content should be... (the image comes from a non-producer shop order cycle, where the given tooltips have their content)
![image](https://user-images.githubusercontent.com/10843056/30726574-11d9a688-9f8f-11e7-8cc3-87fb6157e659.png)

## Steps to Reproduce
1. Connect as a manager of a "producer shop" type of entreprise
2. Go to order cycle and create a new one
3. You will see given the images or the video below, the 2 given tooltips don't have any content

## Animated Gif/Screenshot
https://www.useloom.com/share/e0cd9704183547f0a86ef5825d80320f

## Context
?

## Severity
5 

## Your Environment
* Version used: 1.10.1
* Browser name and version: Chrome 53.0.2785.116 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix

**Comment by HugsDaniel** [comment]
Hi, I took a look and was unable to reproduce this issue. The tooltips seem to be working correctly for me, could you check once more ?

**Comment by myriamboure** [comment]
Hi @HugsDaniel ! I just reproduced the bug, it's still there: https://www.useloom.com/share/e0cd9704183547f0a86ef5825d80320f

To reproduce, make sure you use an entreprise profile that is a producer shop only, otherwise you can't reproduce it. And you have to create an order cycle, the "permanent demo" one is not working the same way apparently.

**Comment by enricostano** [comment]
@myriamboure @sstead  could we please add specific steps on how to reproduce this issue? Thanks!

**Comment by myriamboure** [comment]
Done @enricostano sorry I'm still on holidays, trying to keep up but doing the bare minimum :-p

**Comment by sauloperez** [comment]
Do yourself a favour and shut the pc down @myriam :sweat_smile:
