### ISSUE TITLE
Save button not activated when I remove a customer's tag

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1850]
In the screenshot below, I've just deleted a tag from a customer, yet the save button isn't clickable.

![image](https://user-images.githubusercontent.com/10843056/30726601-3356e3f2-9f8f-11e7-99b4-c54c4dc3d916.png)

**Comment by sauloperez** [comment]
Shouldn't we add the `bug` label to all these?

**Comment by JF-Lalonde** [comment]
Hi, I'm looking through the issues to see where I can help. I'd love to try to fix this if no one else is working on it, otherwise I can help out elsewhere!

**Comment by sstead** [comment]
Hey @JF-Lalonde, welcome. No one is working on this issue, so go for it! If you'd like to be added to the OFN dev slack channel, send me your email to hello@openfoodnetwork.org and I'll add you.

**Comment by JF-Lalonde** [comment]
@sstead I'm unable to reproduce this in development. I've tried creating customers for each shop and was able to delete any and all tags on each customer. Each time the save button worked.
Please let me know if there was more context to this situation than I am seeing.

Also, I noticed while I was adding/deleting labels that there was a bug with the pop-under notification. I created issue #1950 to deal with this.

**Comment by sstead** [comment]
Thanks @JF-Lalonde , 
I've just checked on [Aus production](https://openfoodnetwork.org.au) and [Staging1 ](https://staging1.openfood.com.au)and the bug is still happening for me... Nothing particularly specific about the context... it seems to happen for existing customers and new customers. I'm using Chrome 'Version 61.0.3163.100 (Official Build) (64-bit)'
![image](https://user-images.githubusercontent.com/10843056/32520972-f0d0d3c0-c465-11e7-90c4-d9a5549d4104.png)

**Comment by JF-Lalonde** [comment]
@sstead Thank you for the information. Unfortunately I'm unable to get to the root of this. If anyone else has a chance to work on this that would be great. In the meantime I'll look for other issues to help with!
