### ISSUE TITLE
Missing translations in enterprise edit page

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1852]
The left-hand sidebar in the enterprise edit page is missing all translations.

![users](https://user-images.githubusercontent.com/762088/30736988-30cb4c36-9f85-11e7-84ae-b17eb758d338.png)

**Comment by yasirazgar** [comment]
I checked this, text for menu items are not hardcoded, all are using translations only, I believe its in the following file `app/assets/javascripts/admin/enterprises/controllers/side_menu_controller.js.coffee`

**Comment by sauloperez** [comment]
This must be related to what you have been investigating these days @saimonmoore . In development I have the `LOCALE` (See https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/application.yml.example#L11) set to `es` and the left-hand sidebar it's all in English.

In production, it does work.

![es](https://user-images.githubusercontent.com/762088/31825148-825de4ae-b5b1-11e7-81eb-a7d7afc9d120.png)

**Comment by yasirazgar** [comment]
ok will look into it.

**Comment by sauloperez** [comment]
Thanks again @yasirazgar

**Comment by sauloperez** [comment]
Any update on this @yasirazgar?

**Comment by yasirazgar** [comment]
Sorry @sauloperez will complete it by this weekend.

**Comment by sauloperez** [comment]
Oh great! no rush though. Don't hesitate to tell us if you can't and we'll let someone else pick it up. We, people, have a life as well :laughing:

**Comment by yasirazgar** [comment]
@sauloperez, the translations are showing up correctly, I also checked the #1915 the fix was applied  commonly, so that if translation for any language is not available it fallbacks to en, as the pr is also merged the issue should be fixed. 
Can you please take and let me know if I am missing something.
Thank you!

**Comment by myriamboure** [comment]
@sauloperez do you still have the issue ? From my understanding if the problem is still there it's only in dev environment, please feel free to rate that as a bug then ;-)

**Comment by sauloperez** [comment]
Confirmed. It was something related to my dev env. Now the translations in master are properly loaded. Thanks @yasirazgar !
