### ISSUE TITLE
Expand all link should show a pointer cursor on hover

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1854]
The "EXPANDIR TODOS" red link shows a text cursor on hover which makes it impossible to guess that it is actually a link. It should change to a pointer cursor instead.
 
![captura de pantalla 2017-09-22 a les 16 37 56](https://user-images.githubusercontent.com/762088/30749741-9d87514c-9fb4-11e7-8d4b-5a47b76ca630.png)

**Comment by myriamboure** [comment]
Duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/1117 which is in the "dev ready" OFFrance project board, I thought @ltrls could work on it when he has solved the remaining issues on the ongoing PR ;)

**Comment by sauloperez** [comment]
Oops, sorry, I tend to forget about finding the issue first 😅 . Closing then.
