### ISSUE TITLE
Allow customers to update their card details from the /account page

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1863]
### Overview
At the moment, customers can add cards to their account from the checkout or from their `/account` page. It would be good to allow customers to update their card details, in addition to just adding a card. This is not on the critical path to release, so is a nice to have for now.

### Approach
I am pretty sure that we can use Stripe Elements to handle this, so it shouldn't been too difficult to build. We will just need the implement an Rails #update action for credit cards. More info about implementation from the Stripe side here: https://stripe.com/docs/recipes/updating-customer-cards

**Comment by MiguelSilva1997** [comment]
Hi there! Me and @liambarstad are first-time contributors and we were hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress we are happy to try helping out elsewhere. Thanks!

**Comment by enricostano** [comment]
@MiguelSilva1997 hi and welcome!

Is there a specific reason why you would like to start with this issue? I ask so since there are other issues that are more critical and/or better specified to start with. This one still has to go through the product management pipe and get specified.

What about one from the following lists?
 - https://github.com/openfoodfoundation/openfoodnetwork/issues?q=is%3Aissue+is%3Aopen+label%3Abug-s2
 - https://github.com/openfoodfoundation/openfoodnetwork/labels/good%20first%20issue

Feel free to ping me for more info, we also have a Slack channel if you want to join!

**Comment by liambarstad** [comment]
We also noticed that credit card information is being saved in the database. I am unsure if this was a design decision or not, but it is possible to only save the an encrypted UID on the card object and query stripe for all card and customer details. We would be happy to implement the ability to update via stripe but are finding it exceedingly difficult to find the relevant classes and are unfamiliar with HAML. What functionality is already implemented? and where should we add our work?

**Comment by enricostano** [comment]
Hi @liambarstad !

is there any issue open for the credit card problem you are mentioning? If not please feel free to open a new one.

cc/ @oeoeaio

**Comment by oeoeaio** [comment]
Hi @liambarstad, thanks for your interest in this issue.

There are quite a few parts to this so it is probably not an ideal first issue, but I am happy to provide a bit of guidance if you would like to continue working on it.

Are you at all familiar with [AngularJS](https://angularjs.org/) and/or [Coffeescript](http://coffeescript.org/)? Solving this issue will require an understanding of both. I imagine that the majority of the work you will need to do will be in an angular service called CreditCard (`app/assets/javascripts/darkswarm/services/credit_card.js.coffee`). 

The CreditCard service accepts basic card information received from Stripe and submits it to our servers via AJAX so that it can be stored. At the moment it is really only set up to submit new card information, it doesn't handle update actions, so you will probably need to refactor it to allow it to handle both actions.

On the rails side, you will need to add a new #update action to the `CreditCardsController` (`app/controllers/spree/credit_cards_controller.rb`) and wire it up.

The last step will be to alter the interface so that your new update action can be used by customers. Do you have an idea about how you will design this interface? It would be great if you could upload  sketch to illustrate your thinking.

It terms of the storage of card information in the database, we are only storing the expiry, type and last four digits of the card, the full card number and CCV never hit our servers. While it is possible to retrieve expiry, type and last_four information from Stripe using only the UID, storing it in our database makes it much faster to display card information in forms, etc because we don't have to request the information from Stripe every time we want it. Does that answer your question?

Let me know if there's anything else I can help with.

**Comment by oeoeaio** [comment]
In terms of where to add your work, I would suggest reading our [CONTRIBUTING.md](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/CONTRIBUTING.md). It will talk you through how to fork the repo and set up your local git environment so that you can submit changes to your fork and then open a pull request against the main repository.

**Comment by lin-d-hop** [comment]
A user can add and delete a card meaning there is a valid workaround.
Many merchants require users to remove and add cards totally so this is not really an inconvenience to the user.
This is annoying no one.
Closing
