### ISSUE TITLE
Enable hub manager to decide if she wants to receive a notification email or not

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1865]
Today there is no way for a hub manager to deactivate the notification emails.
The solution is, from their mailbox to set up a filter that send to trash or to a specific mailbox the confirmation emails.
Most of the hub in France do that, they are fed up with receiving an email each time an order is passed...
But we received a feedback from a user saying that emails have a carbon footprint so it would be better just to enable a hub to desactivate notification.

I tried to delete the email in the "notification" field but it doesn't work, the system today requires a notification email.

To do:
- either add a checkbox "Don't send me notifications"
- either enable to empty the notification field

I don't know if that would have other implications.

**Comment by RachL** [comment]
Two things here:
- it is probably best to move it to discourse
- recently I had a hub who did a mistake and the only way to fix this was thanks to the confirmation emails. So I'm afraid this is something we want to keep for now. Once we have a proper edit trail, this can be reconsider. 

Closing.
