### ISSUE TITLE
Deletions in OFN

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1880]
Today users feel pretty painful not to be able to delete any customer, any order cycle (as ong as someone has opened the shopfront page), any entreprise (when they make mistakes), any order (when they do tests).
This epic is implementing the ability to delete accounts, entreprises, users, customers, order cycles, orders,   and products.

See reference discussion (still ongoing) : https://community.openfoodnetwork.org/t/what-to-implement-in-terms-of-users-enterprises-removal/1046/2

Update: most important (prioroty) here are
- Enable a user to delete his account
- Enable a hub to delete a customer from their customer list (unable to use private shop)

**Comment by myriamboure** [comment]
@enricostano @sauloperez do you know if Spree upgrade will have an impact on any of those issues ? This seems like a fundamental think to get done, can it be done in parallel of Spree upgrade ?

**Comment by enricostano** [comment]
I don't think Spree upgrade will bring anything in this direction since every project that uses Spree will adopt a different take on the problem. We need to finish to discuss it first and then talk about implementation IMHO.

**Comment by myriamboure** [comment]
Sure sure @enricostano I just wanted to understand the project management process, but will change whatever is needed given the result of the Discourse discussion ;)

**Comment by myriamboure** [comment]
Closing the epic as an icebox item is opened in community: https://community.openfoodnetwork.org/t/users-and-admins-can-delete-accounts-entreprises-customers-order-cycles-groups/1149
