### ISSUE TITLE
Bug in orders filter by dates

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1883]
Use case: as a hub manager I want to filter the orders from certain dates ranges.
The calendar displays properly, I can choose a start date but then it displays wrongly : aa-09-jj
If I select an "end date" the "start dates" disappears and the end dates also displays wrongly.

![screenshot from 2017-09-27 22-01-12](https://user-images.githubusercontent.com/8135376/30934937-6d15199e-a3cf-11e7-97c3-5f56b8cd63fc.png)

**Comment by sigmundpetersen** [comment]
I was looking into the same thing recently @myriamboure and I think it's related to the translation key spree.date_picker.js_format added to Transifex. I don't think this should be translated. I will try putting it back to yy-mm-dd and see. You may try in parallel :)

**Comment by myriamboure** [comment]
@ltrls can you check that quickly ?

**Comment by sauloperez** [comment]
I also experienced this odd behaviour of the "aa" in the order cycle list.

![order_cycle_list](https://user-images.githubusercontent.com/762088/31782944-e26b62b4-b4fc-11e7-92a7-573188c5b188.png)

Does anybody know whether we have any other issue related to this? Just to keep things organized.

**Comment by myriamboure** [comment]
@ltrls has apparently found the solution randomly while working on some other things ;) he will tell us soon.

**Comment by ltrls** [comment]
might or might not be it, but in `en.yml` the key that seems to be used for formatting the date is written this way: `format: ! '%Y-%m-%d'`. In other local files the exclamation mark is not there (it could be Transifex's fault). it seems that the percent sign has special meaning in yaml and that the exclamation means to ignore that. I haven't tried to put it back yet but I guess it's worth a try :)

**Comment by sigmundpetersen** [comment]
@ltrls @myriamboure FYI there are 2 date picker keys in en.yml, spree.date_picker.js_format: yy-mm-dd and spree.date_picker.format: %Y-%M-%D

'Untranslating' yy-mm-dd fixed it ion Scandinavian instance

**Comment by sauloperez** [comment]
I checked and `js_format` is also the one used in the orders list

**Comment by myriamboure** [comment]
This issue is fixed thanks to #1924 solution found by @sauloperez so closing this issue.
