### ISSUE TITLE
Order "order cycle" list from most recent to oldest in "orders" filtering

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1884]
We just got a feedback from a user (who actually is becoming kind of a very active tester apparently ;-)):
she got lost in trying to filter the orders by "order cycle" as she has many and they were proposed in a random order, whereas in other places on the platform they are ordered from most recent to oldest, so it's easier to search.

To do: display order cycles from most recent to oldest in "order cycle" filter field in "orders" page.

In reports for instance:
![screenshot from 2017-09-27 22-22-38](https://user-images.githubusercontent.com/8135376/30936022-cc7f52fc-a3d2-11e7-8169-6ac63065fb7a.png)

Currently in orders page:
![screenshot from 2017-09-27 22-22-52](https://user-images.githubusercontent.com/8135376/30936026-d2f07526-a3d2-11e7-9908-75205ce148d8.png)

**Comment by thedanielvogelsang** [comment]
Hi there team! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by lin-d-hop** [comment]
Hi @thedanielvogelsang! Welcome! That would be fantastic!
If you have any questions feel free to ask here or in the #dev channel of our [Slack group](https://openfoodnetwork.slack.com). 

For this issue just stick to fixing the OC ordering in the Orders page.
@myriamboure if you notice any other places the ordering of OCs is confusing please open a new issue (and add good first issue label).

**Comment by myriamboure** [comment]
Awesome ! Ok @lin-d-hop I try to stick to the rule one issue = one PR now so small and separate issues ;-)

**Comment by NickWeir63** [comment]
Hi @thedanielvogelsang - thanks for your help.  I would like to invite you to join the OFN dev update mumble at 8.30amGMT tomorrow (Thursday).  Joining details and a timezone converter are in [the agenda here](https://docs.google.com/spreadsheets/d/164AIN1zow3OhvGJfPE5GWnPYmZNFGgznF4ThQPJV_To/edit#gid=40650955) (you are welcome to add notes to the agenda).  Hope to see you there.  Nick
