### ISSUE TITLE
Allow producer to see customers names if hub agrees

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1887]
As a producer, I want to see what has been ordered to prepare each individual client basket for the delivery in the food hub.
When I go in "report", "order cycle total by customer", i see that:
![masque](https://user-images.githubusercontent.com/8135376/31017700-b5e4effe-a529-11e7-990a-7a8c160c4278.png)

The producer doesn't know who he is supposed to deliver which basket :-(

**My proposal is:**
1- Add a checkbox on hub menu, in "Shop preferences" :"Allow suppliers to see customers names and contacts details in their customers reports" Y/N
2- This remove the anonymisation of the customer list in the producers "order cycle customer total" report.

I guess this is something that will be most needed also in the buying group features... I suspect Spree is built like that because in a competitive commercial world, a shop will consider as his asset his customer list, and won't share them with their supplier as they would be afraid that they sell direct to them... but in our case it will be different, especially in buying groups models.

**Comment by myriamboure** [comment]
@enricostano @sauloperez @kirstenalarsen @lin-d-hop @sstead @daniellemoorhead any objection if we do that ?

**Comment by sstead** [comment]
This sounds like a useful change to me, no objections.
________________________________

**Comment by enricostano** [comment]
In our experience here suppliers don't care about customers details, they just want to know how many Kg of potatos that hub will need for the next week. But I can imagine other scenarios of course.

What I suggest is to work at reports level, for instance having a report without customers info and another with that info.

In any case this doesn't seem a Spree related thing, the current behaviour seems 100% on OFN side to me.

**Comment by myriamboure** [comment]
Icebox item opened here https://community.openfoodnetwork.org/t/hubs-suppliers-can-prepare-the-invidual-orders-for-the-hubs-customers/1151
