### ISSUE TITLE
When a producer adds a product, he can't add it to a shopfront he supplies

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1888]
In my producer account, I create a new product. I want to add it to the order cycle of the buying group I supply. I go in order cycle, I select normally the new product in "Incoming", BUT in "outgoing", I can't select it ! The product is available, I see it but I can't check the checkbox.

![screenshot from 2017-09-29 15-41-59](https://user-images.githubusercontent.com/8135376/31018526-c711a788-a52c-11e7-8d44-7ee4a7f871ac.png)

I suspect this is not really a bug, I guess it's on purpose, as maybe the hub want to control which products are distributed in his shopfront.
SO I suggest to allow the hub to also tell if he allow or not the producers to add products to the shopfront or not.

- In hub menu, "shopfront preferences", "Allow producers to add/withdraw products in the shopfront" Y/N
- Then this "unlock" the possibility for the producer to check/uncheck boxes in the OC

**Comment by myriamboure** [comment]
@sstead @lin-d-hop @sigmundpetersen @enricostano any objection to that ? It sounds like a small thing that is annoying one of our user in France. If it's quick to fix we would like to fix it :-)

**Comment by enricostano** [comment]
@myriamboure I think we need some investigation explaining the current behaviour, both in the code and at product level.

**Comment by sauloperez** [comment]
Yep, we already a task on Katuma to investigate this behaviour that we don't understand either.

**Comment by myriamboure** [comment]
Ok so following Rob's comment I checked and yes I didn't have the permission "hub authorize producer to add to order cycle" so I gave that permission and this has solved the problem, no problem then, closing the issue.
