### ISSUE TITLE
Bug in "order cycles" filter on customer admin reports

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1889]
## Description
As a producer, I can't filter my sales by order cycle for the hubs I provide, so I can't get easily the information on what I'm suppose to deliver to a hub for a given order cycle.

## Expected Behavior
As a producer, when I generate a report, I should be able to filter the results by order cycle for all the order cycle I am a supplier for.

## Actual Behavior
As a producer, when I generate a report, I can only filter the results by order cycle for the order cycle I created.

## Steps to Reproduce
1- Connect to admin section with a **producer** account, make sure you create at least one product for the producer.
2- In another brower, connect with a hub account that has the permission to add to order cycle the producer's products (permissions/entreprise relationships, in entreprise menu), and open an order cycle with the producer's products.
3- With the producer account, go to "reports", "order cycle reports", and select for instance "order cycle total by producer".
4- Try to filter by order cycle, the hub's order cycle doesn't appear and can't be selected.

## Animated Gif/Screenshot

1- By default, I see the total quantity ordered for my products from the start date automatically selected, this seems to work ok.
![screenshot from 2017-09-29 15-55-40](https://user-images.githubusercontent.com/8135376/31019345-afed4424-a52f-11e7-930e-425e309c9bfa.png)

2- If I select a specific hub "hub demo open food france" here, I see the total corresponding to this hub this seems to work ok as well
![screenshot from 2017-09-29 15-56-00](https://user-images.githubusercontent.com/8135376/31019348-b17739d0-a52f-11e7-98a2-af3b5d5a4c52.png)

3- **BUT** If I try to select an order cycle to filter a bit more, I am proposed only the producer shop OC, I can't see the hub OC, so I can't filter by hub OC. We need to fix that so that the producer can filter by order cycle to know in real time what in needs to prepare for a given distribution so that he can anticipate a bit before the order cycle is closed.
![screenshot from 2017-09-29 15-56-07](https://user-images.githubusercontent.com/8135376/31019378-cbb7f046-a52f-11e7-95b2-cc1ff603577e.png)

## Context
Various producers complained when trying to get the information about what they were supposed to deliver to the hub they are supplying (a buying group in this case).

## Severity
I put s2 as there is no workaround and it's pretty annoying, it's already hard for many producers to manage themselves their sales... let's not make it harder.

## Your Environment
* Version used: 1.10.1
* Browser name and version: Chrome 53.0.2785.116 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Comment
If I select a hub first, only the OC connected to that hub should be proposed.
If I select an OC first, I shouldn't be able then to add a filter on the hub.
This is to avoid conflicts.

**Comment by myriamboure** [comment]
To do:
- [ ] For "producer rights" users, propose in the order cycle filter not only the producer hub 's OC, but also the hubs' OC he is a supplier for.
This is a clear bug to me so we gonna move forward to fix it, annoying at least two users who reported that to us.

I propose to treat separately the calendar thing, maybe @augnustin you had some idea to add that in some locals so that all the calendars use a local format, etc. Let's put the calendar thing in another discussion ;-)

**Comment by myriamboure** [comment]
On this issue we are limiting the scope to:
- as a producer, in my admin "report" section, I am proposed in the OC filter all the OC for which my products are listed in.

So we are conscious that there might be a conflict if I select a hub, and then an OC that is not connected to that hub (no result) or if I select an OC, and then a hub that has is not connected to that OC. We will address that in a [specific issue and PR](https://github.com/openfoodfoundation/openfoodnetwork/issues/1968) after this one. #1issue1pr #agile

**Comment by myriamboure** [comment]
I hit again the issue while doing support to a producer who only sells through hubs and doesn't manager to filter the orders reports as he can't use the order cycle filter (OC of the hub not showing) and sometimes he makes mistakes when sorting only with the dates... 
The workaround of sorting only with the dates is not working as multiples OC are run in parallel by the hub so there is no workaround really... so putting S2.

**Comment by daniellemoorhead** [comment]
@myriamboure given it looks like an easy fix did you want to see if someone can pick this up and fix it for you?

**Comment by myriamboure** [comment]
Yep @daniellemoorhead I proposed @HugsDaniel to work on it, as he seems to be rocking all the first PRs :-)

**Comment by sauloperez** [comment]
I did some investigation to understand why order cycles are not shown for producers, so I will post my findings here.
