### ISSUE TITLE
Orders which had a failed payment attempt during checkout should not remain in 'failed' state

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1902]
This is occurring when an checkout is attempted, but fails with Stripe, and then a successful checkout is achieved with a manual payment option (cash). The state is still showing as failed, which is not accurate.

![image](https://user-images.githubusercontent.com/10843056/31530403-f05e756c-b02b-11e7-97fa-05d31e621f01.png)

**Comment by daniellemoorhead** [comment]
@oeoeaio will this need to be done as part of the Stripe initial work?

**Comment by oeoeaio** [comment]
Possibly yeah. I'll investigate more on Wednesday.
