### ISSUE TITLE
"update" send snail fail page on OC page if no OC listed

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1907]
## Description
 A user wanted to create a new OC, but quickly clicked on "update" as he didn't read the button and that that was the one to create an OC. This crashes the system (snail page). 

## Expected Behavior
 If no OC and I click on "update", display a pop-in message or banner "no order cycle to update".

## Actual Behavior
 If no OC and I click on "update", snail page appear (crashes).

## Steps to Reproduce
1. With a hub entreprise with no OC, go to order cycle and click on "update"

## Animated Gif/Screenshot
![update](https://user-images.githubusercontent.com/8135376/31608147-89d95988-b26f-11e7-8682-857c4a3f6460.jpeg)

## Context
While doing support to a new user and seeing him navigate. He wanted to create an order cycle, so on OC menu, he didn't read carefully and quickly clicked on the "update" button.

## Severity
S4, not so many people I guess have this behavior, but the result is disturbing for a user.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by RachL** [comment]
@myriamboure I have the feeling the OC page has change a lot since then. So I'm closing this as I don't see an update button anymore when no OC exists. If I missunderstood feel free to reopen it. Thanks.
