### ISSUE TITLE
Language testing: clicking Cog -> 'my account' redirects to English instead of French.

### ISSUE THREAD

**Issue by simoneluijckx** [openfoodfoundation/openfoodnetwork#1908]
## New issue  from testings on: [Uk/language frontend  ##1793](https://github.com/openfoodfoundation/openfoodnetwork/pull/1793#issuecomment-336972911) 

Clicking on 'compte' (my account) leads me to the EN account page:
The headers are all in English again, before they were in French
![image](https://user-images.githubusercontent.com/31434588/31630004-fce339a8-b300-11e7-9ccd-a6551f85503b.png)

![image](https://user-images.githubusercontent.com/31434588/31630012-059f8a56-b301-11e7-8dbf-12b853d0fc3b.png)

This is the linkname of this page: https://staging2.openfood.com.au/account#/orders
-->when using the back buttons of the browser works: After the previous steps I clicked back, leads me back to the FR page.

**Comment by simoneluijckx** [comment]
@lin-d-hop here it is, can't get to add a label though. Perhaps I don't have the rights to do it?

**Comment by myriamboure** [comment]
Yes, I noticed that when testing on the latest version, I saw the new tabs but everything is in English. Wondering about "credit cards" in the test above, are we storing any credit card information ?

**Comment by lin-d-hop** [comment]
Never storing credit card info. Stripe does this.

⁣Sent from BlueMail ​

**Comment by Matt-Yorkley** [comment]
This is fixed in PR #1793 with this commit: https://github.com/openfoodfoundation/openfoodnetwork/pull/1793/commits/f03c2153a2ab46939271463de7a216b8872ca040
