### ISSUE TITLE
Toggling of a Store's page drop-downs will not 'un-toggle'

### ISSUE THREAD

**Issue by jbexx** [openfoodfoundation/openfoodnetwork#1911]
When viewing a store's page, clicking on the ‘about’, ‘producers’, ‘contact’, or ‘groups’ link will expand that section. You can then click on the other sections to switch the content, but there is no way to completely un-toggle these sections.

![pasted image at 2017_10_16 04_46 pm](https://user-images.githubusercontent.com/23174736/31699943-3e6ec054-b383-11e7-8c17-6836d7ec23ab.png)

As a user, this feels like a toggle-able control, but the un-toggle piece is missing.

**Comment by sauloperez** [comment]
Agree! I experienced the same

**Comment by myriamboure** [comment]
This is now fixed, you can check on any shop on Australian website which has the latest version https://www.openfoodnetwork.org.au/bawbawfoodhub/shop#/
