### ISSUE TITLE
Clicking on the 'Show More' link within the expanded shop widget collapses the widget unexpectedly.

### ISSUE THREAD

**Issue by EndlessHypnosis** [openfoodfoundation/openfoodnetwork#1913]
When clicking on the ‘Show more’ link, the list does indeed expand, but the detail widget also collapses. So the user must re-open the details to view the expanded list. This appears to be due to clicking anywhere within the widget closing it. It may also be prudent to apply the fix for this to the store name…which also closes/opens the detail widget before redirecting.

![image](https://user-images.githubusercontent.com/26394305/31736095-fe6b8112-b400-11e7-9f64-1483084042cb.png)

## Severity
S3 as it's a pretty obvious front end UX issue so might affect quite a few customers trying to look for shops, and the current behavior is pretty disturbing for a customer.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by sigmundpetersen** [comment]
@daniellemoorhead I reclon we could :) please correct if this is ruby not angular
