### ISSUE TITLE
Setting order cycle date from list persists wrong date

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1924]
## What

The date persisted in the order cycle doesn't match the one selected in the order cycle when doing so from the order cycles list. See the gif below:

![](http://g.recordit.co/eKNsQfwYS0.gif)

## Steps to reproduce

1. Go to order cycles
2. Modify a date of one of the available cycles through the datepicker
3. Click on the update button at the bottom of the page

Once reloaded the displayed date it's not the one we selected.

## Acceptance Criteria

As an admin I want to see the actual date that I selected in the order cycle datepicker.

**Comment by kirstenalarsen** [comment]
wow, video bug reporting - I love it!

**Comment by sigmundpetersen** [comment]
what tool are you using for recording @sauloperez ? 😄 #META

**Comment by sauloperez** [comment]
I have to admit I was on my good ol' mac 😅  using [Recordit](http://recordit.co/), but NORMALLY I use [Peek](https://github.com/phw/peek) in my daily day Ubuntu

**Comment by sauloperez** [comment]
The issue turned out to be due to a wrong translation of the key `js_format`. The date picker does not understand `aa` as year (año in Spanish). Changing it from `aa-mm-dd` to `yy-mm-dd`.

By quickly checking the locales I believe you will experience the same problem @myriamboure @ltrls and @sigmundpetersen. You have to stick to the English syntax (y, m, d).

**Comment by sigmundpetersen** [comment]
> Changing it from aa-mm-dd to yy-mm-dd.

This worked on Scandinavian instance @sauloperez @myriamboure

**Comment by myriamboure** [comment]
@sauloperez @sigmundpetersen do we need to commit any PR or is it something we are supposed to do on our local server configuration ? Sorry non tech ;-)

**Comment by sauloperez** [comment]
It's just a translation that you need to change in Transifex. Look for https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/fr.yml#L2079

**Comment by sigmundpetersen** [comment]
@sauloperez do you think these keys should be removed from en.yml as translation of them breaks functionality? 😄 

There are 2 date picker keys `spree.date_picker.js_format: yy-mm-dd` and `spree.date_picker.format: %Y-%M-%D`

**Comment by sauloperez** [comment]
I wouldn't remove them as it seems to be the mechanism to localize the date format. For instance in Spain the standard is `dd-mm-yyyy`. Perhaps is worth adding a comment to note the special syntax cocumented in http://api.jqueryui.com/datepicker/#option-dateFormat

**Comment by myriamboure** [comment]
Standard in France is also dd-mm-yyyy :-)

**Comment by myriamboure** [comment]
That works in France ! Should we close that issue then @sauloperez ?

**Comment by daniellemoorhead** [comment]
@lin-d-hop @sineadfenton @NickWeir63 is this relevant for the UK instance?

**Comment by sineadfenton** [comment]
@daniellemoorhead No from testing now and work on order cycles last week I cant say this cropped up for me, so we look grand on this end.

**Comment by daniellemoorhead** [comment]
Thanks @sineadfenton then I imagine it would be ok to close this @sauloperez @myriamboure 😄
