### ISSUE TITLE
Change package screen text

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1926]
We've had feedback that users get confused between terms like profile, type, and package. For the sake of using consistent terminology can we change the text below...

![image](https://user-images.githubusercontent.com/10843056/31980035-9cfd715c-b995-11e7-89c7-8770852935e1.png)

**Comment by MasonHolland** [comment]
I can tackle this!

**Comment by jenPlusPlus** [comment]
Hi there! We are first-time contributors and were hoping to help out with this issue. We noticed that this issue hasn't been closed and the repo we cloned still contains the incorrect text. We've submitted a pull request [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/1992) for review. Let us know if you need any additional information. Thanks!

**Comment by enricostano** [comment]
Welcome @jenPlusPlus ! Thanks for your help!

**Comment by mttwlkr** [comment]
Hi. @stevenleelawson, @kc2693 and I are developers who are new to open-source. We noticed this [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/1992) has been closed without resolution due to probable merge-conflicts. We have read this PR, are aware of the Transifex issue and would like to help. Thanks.

**Comment by myriamboure** [comment]
Hi @mttwlkr @stevenleelawson @Kc2693 ! Welcome here! Awesome that you want to contribute and help on the OFN project :-) Yes that will be a pleasure if you want to start with this small translation issue to get a first glance at the code base. Have a look also at the wiki where you will find lots of useful information about how to make a great PR, find info on internationalization, etc. Like https://github.com/openfoodfoundation/openfoodnetwork/wiki/i18n. If you want 2 or 3 other simple issues like this one I will be happy to give you some issue numbers :-) Just let me know!
