### ISSUE TITLE
New variant form persists wrong weight

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1932]
## What

When creating a new variant it is not possible to set a fraction of the product's weight. Neither `0.5`, nor `0,5` nor `500` show the right value in the variants list. See gif below:

![variant_bugs](https://user-images.githubusercontent.com/762088/32168553-68db8ffe-bd6d-11e7-8203-70783f52b1ae.gif)

When editing however, typing `0.5` does show up as `500g` in the variants list.

First, we need to fix the weird label copy and then, fix the input field so that it works like the edit form.

## Acceptance criteria

As an admin, when I navigate to the new variant form, I see `PESO (kg)` rather than `PESO ({{UNITNAME(1000.0, 'WEIGHT')}})`.

Also, when I create a new variant with weight `0.5` it shows as up as `500g` in the variants list.

**Comment by Matt-Yorkley** [comment]
It's working for edit variant but not new variant. Looks like it's calling this method in https://github.com/openfoodfoundation/openfoodnetwork/blob/8b560e6cee23800d5cd9b163c185638065ba3384/app/assets/javascripts/admin/products/controllers/variant_units_controller.js.coffee but it's not rendering the result...

**Comment by Matt-Yorkley** [comment]
I think it might be because the edit variant form is shown after a page reload, but the new variant form is being injected into the DOM via an asynchronous get request.

**Comment by Matt-Yorkley** [comment]
@sauloperez I made some changes to the variant edit forms in #1531. The new form uses angular to work with different weight calculations but it looks like the new variant form isn't executing any of the angular methods attached to it.

**Comment by sauloperez** [comment]
>  the add variant form isn't executing any of the angular methods attached to it.

This is all I have found the whole morning. And it seems to be exactly this:

> I think it might be because the edit variant form is shown after a page reload, but the new variant form is being injected into the DOM via an asynchronous get request.

I'm not familiar enough with angular to find out why. I suspect something like https://stackoverflow.com/questions/33195110/load-ngcontroller-after-ngapp-is-loaded-by-ajax might be related. I guess we need to dig deeper on how the other overriden forms work and why don't use `$compile`.

Any help you could provide is veeeery welcome @Matt-Yorkley !

**Comment by sauloperez** [comment]
By the way, I take this.
