### ISSUE TITLE
Deleting a variant removes also the next one

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1933]
## What

When deleting a variant from the variants list, it removes the one I clicked on but also the next one. When refreshing the page though, only the one I clicked on was actually removed. See gif below:

![deleting_variants](https://user-images.githubusercontent.com/762088/32169030-12725768-bd6f-11e7-9891-d2174e34ba81.gif)

Needles to say that although the next variant it's not actually deleted from the DB this bug is scary for the user.

## Acceptance Criteria

As an admin, when I remove one variant by clicking on the trash icon it removes only its row from the UI.

**Comment by sauloperez** [comment]
Fixed in: https://github.com/openfoodfoundation/spree/pull/3

**Comment by sauloperez** [comment]
cc @oeoeaio @mkllnk I need your approvals on that PR guys

**Comment by enricostano** [comment]
@sauloperez https://github.com/openfoodfoundation/spree/pull/3 got merged, we can integrate that in OFN now 👏
