### ISSUE TITLE
Using Meta Keywords to Improve Search

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1936]
The Problem: Currently the Product search box allows searching in the Category, Product Title and Variant Name. This is important as descriptions often contain a lot of additional text we don't want to search for. However, this means that products can end up with long names if we want to be able to search for them but don't want to create a specific category for the product. An example from the UK is craft items like Greeting Cards.

Proposed Solution: To use the SEO fields in the Edit Product screen to do this. I would propose that we use the 'Meta Keyword' field. Thus terms that appear in the 'Meta Keyword' field will be searchable in the Product Search and thus be displayed to the user at that point.

Some fields will need to be renamed for UX:
Tab Name SEO could become 'Search'
'Meta Keyword' could become 'Product Search Keywords'
'Meta Description' could become 'SEO Keywords'.

Fixing the SEO keywords is outside the scope of this issue.
It would be useful to have a tooltip to explain what this is doing.

![image](https://user-images.githubusercontent.com/8669848/32219214-5a8fbe6c-be25-11e7-9201-28a93d84db3b.png)

Discussion: https://community.openfoodnetwork.org/t/enabling-meta-keywords-to-help-with-product-search/1102

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Meta Descriptions and Keywords](https://trello.com/c/0fPdtlER/103-meta-descriptions-and-keywords)

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/discovery/1177

**Comment by myriamboure** [comment]
It seems we have a PR ready to test for this one so reopening it.
