### ISSUE TITLE
As a hub manager, I want to get OC Shipping Method Totals by Supplier

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1946]
**The problem:**
Today if I manage a hub with 2 pick-up points = 2 shipping options offered at checkout, I can't get totals fo each shipping method per producer, so as a hub manager I can't organize well the logistics.
Reports only propose agregated data per "distributor" (= hub entreprise).

For each supplier, I want to see the agregated data per shipping method.

**The solution:**
In the "orders & fulfillments" reports section, create a new report:
- OC Shipping Method Totals by Supplier
 
I guess it's not so complicated, a dev can just copy-paste those two reports and change the source for the "distributor" columns to a "delivery option", right ? Any difficulty expected ?

**Source discussion:**
https://community.openfoodnetwork.org/t/need-reports-filters-by-shipping-method-suggestions-welcome/1111

**Acceptance criteria:**
I can display data and download csv file for this new report. The columns are the same as for the report "OC Distributor Totals by Supplier" but the column "Shipping method" has replaced the column "Distributor" and the totals are well agregated.

**Comment by sauloperez** [comment]
> a dev can just copy-paste those two reports and change the source for the "distributor" columns to a "delivery option", right?

Not really, we're not supposed to copy and paste code :cold_sweat: it makes it a lot harder to maintain. However IMO reports ended up being a bit of a nightmare with lots of duplication, very hard to read for devs and with poor performance.

Try to reuse as much as you can, although we know /reports needs a major effort to mitigate all those problems.

**Comment by myriamboure** [comment]
Hum... I understand, I guess we'll discuss that as well in Aus, but for now I need to find a way to get agregated data per shipping method and I don't see another option than a report (for now...) but I agree with you about poor performance, as an admin I'm unable to charge some reports because here are too much data... hard to give support :-(

**Comment by sauloperez** [comment]
Sure, I understand the way to get that data is through a report, but I just raised the flag. Of course, we need to discuss about that in Aus among other things :+1:

**Comment by myriamboure** [comment]
Pause in this until we have clarified if we can create that new concept of "delivery place" in the data model, in this case the report will be done based on this new concept which makes much more sens than filtering by shipping method I think.

**Comment by myriamboure** [comment]
Icebox item here https://community.openfoodnetwork.org/t/enable-products-dispatch-per-distribution-location/1155
