### ISSUE TITLE
Remove duplicate datepicker directive

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1947]
## What
The datepicker directive is defined in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/directives/date_picker.js.coffee and https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/index_utils/directives/datepicker.js.coffee. However with a quick git grep I only see it used in `bulk_management`. 

We should stick to one or the other because they are exact copies. I lean towards the first one as it seems a bit more generic and there is a `datetime_picker.js.coffee` file next to it.

**Comment by JF-Lalonde** [comment]
I'm happy to remove the duplicated file and make sure all tests are still passing. I would love to make a Pull request, but I don't have permission to push my branch up to make the PR...

**Comment by sauloperez** [comment]
Hi @JF-Lalonde that would be awesome! Did you create your own fork? Take a look at https://github.com/openfoodfoundation/openfoodnetwork/blob/master/CONTRIBUTING.md

Make sure you find all the uses of said directive. Feel free to ask any question here or in the #dev channel of our Slack chat: https://openfoodnetwork.slack.com/

**Comment by JF-Lalonde** [comment]
@sauloperez Sorry, I realized I didn't fork the repo before checking out a branch! I'll go ahead and fix that, then I'll submit a PR

**Comment by myriamboure** [comment]
Solved by #1951 which has just been merged.
