### ISSUE TITLE
Changes in pop-under on admin dashboard do not increment

### ISSUE THREAD

**Issue by JF-Lalonde** [openfoodfoundation/openfoodnetwork#1950]
On the admin dashboard, if you create a new customer and start making changes a pop-under notification appears with the message "You have made 1 unsaved changes".
- This message should change depending on the amount of unsaved changes (e.g. "You have made 2/3/4 unsaved changes")
- This message should say "change" instead of "changes" when only 1 change has been made.

<img width="1066" alt="screen shot 2017-11-07 at 1 05 32 pm" src="https://user-images.githubusercontent.com/26772297/32515152-6d6e2036-c3bc-11e7-99df-eaa5ca277ed5.png">

**Comment by lin-d-hop** [comment]
I would like to suggest that we always just say:
"You have unsaved changes".

Why:
It doesn't matter how many there are
Getting a consistently accurate count is likely more effort than it is worth.
