### ISSUE TITLE
Add rubocop-rspec

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1959]
## What?

Now that we finally got to RSpec 3, it's time to add https://github.com/backus/rubocop-rspec to our Rubocop to enforce a style guide also for our test suite. This will also make the transition to RSpec 3's syntax and additions easier.

**Comment by daniellemoorhead** [comment]
@sauloperez does this also need testing or does the pr-no-test label apply?

**Comment by sauloperez** [comment]
Moved to https://community.openfoodnetwork.org/t/agree-on-and-enforce-a-style-guide-for-tests/1154
