### ISSUE TITLE
Remove old aliases prior to i18n-js

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1961]
## What?

The old aliases that we had before `i18n-js` was introduced, present in [app/assets/javascripts/darkswarm/i18n.translate.js.coffee](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/darkswarm/i18n.translate.js.coffee), should be removed after everything is moved to `i18n-js`.

Unfortunately, we are not there yet. This is what happens to the `admin/products/bulk_edit` page without these aliases:

![bulk_edit](https://user-images.githubusercontent.com/762088/32834108-9c85d026-ca01-11e7-9d3d-584719adec77.png)

**Comment by myriamboure** [comment]
@sauloperez is it clear enough for a newby coming to OFN? I'm not tech so not undertanding clearly what needs to be done and it was before we use the new issue template ;-) Adding tech debt as it doesn't seem like a bug but something linked to some depedency upgrade. Feel free to add any emergency label as well.

**Comment by sauloperez** [comment]
Honestly I don't remember exactly what I meant so let's close it until we need it again.
