### ISSUE TITLE
'Resend' email button from Admin dashboard for easy triggering

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1963]
Would be really good to be able to resend email confirmations from the Dashboard . . 

![image](https://user-images.githubusercontent.com/2911176/32863012-233f4b68-caae-11e7-9f73-64e9c3ff6b5c.png)

and maybe even confirm them for cases when the email has stuffed up and we don't want to mess people around. But I'm sure that was discussed in email confirmation work @myriamboure @daniellemoorhead @sstead

**Comment by daniellemoorhead** [comment]
>But I'm sure that was discussed in email confirmation work @myriamboure @daniellemoorhead @sstead

We didn't discuss the dashboard, or email stuff ups initially @kirstenalarsen. Maybe @RachL and @myriamboure have incorporated this since?

**Comment by sstead** [comment]
@kirstenalarsen in future it will be the user that must be confirmed, not the enterprise. Therefore these messages will no longer show. The user will not be able to see the backend until they confirm their email... I wonder if SuperAdmin needs a feed saying which users are yet to confirm? Probably not, because each user can resend their confirmation link themselves when they try to login (pre confirmation).

**Comment by kirstenalarsen** [comment]
ah cool

I think it would be good for superadmin to have that - maybe not on dashboard - but definitely useful to have lists of people to follow up with and see why they got stuck. Just working on conversion stuff for CERES, and seems like this info on people who tried to sign up but failed would be very useful!!

**Comment by sauloperez** [comment]
IMHO getting this insights it's the responsibility of a business analytics tool such as Chartio or Metabase. 

Now we might be asking ourselves about abandoned signups but in a week might be something else, so not affordable to have it in `/admin`. It might chanhe too often.

**Comment by lin-d-hop** [comment]
This needs a wishlist.

Most people workaround it via an email client and there are many ways to resend within the app.

#gitcull21
