### ISSUE TITLE
Update 'contributing' guidelines w advice on creating issues?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1964]
I just created an issue at #1963 

and as this is my first in a very long time I have no idea where to put it, if / how to label it etc. I clicked contributing guidelines but nothing there. Perhaps a couple of sentences that tell me if i need to label it or anything @daniellemoorhead ?

**Comment by lin-d-hop** [comment]
Discussions on this one have led to #1996 :-)
