### ISSUE TITLE
Taxonomies / Product Categories broken 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1965]
I discovered this in Aus production the other day but hadn't got to creating issue yet - we can no longer edit or add product categories (was trying to add a new one for 'fibre')

![image](https://user-images.githubusercontent.com/2911176/32863307-1e4c1ffe-caaf-11e7-9106-9bc4d60a76c1.png)

This is not a major problem for existing instances, but it is a MAJOR problem for new instances as without product categories I suspect we can't create products e.g. USA

![image](https://user-images.githubusercontent.com/2911176/32863256-f7ee5354-caae-11e7-8286-acabb8b0a4b6.png)

I have a suspicion that this could be Spree Upgrade related, as we have no idea how long since it broke but was obviously (apparently?) ok when India was set up?
@sauloperez @oeoeaio @enricostano

**Comment by kirstenalarsen** [comment]
NB. re. setup of US instance - we can create products using the 'head' category of 'Products' . . so we can move ahead without this being fixed, but with no ability to have the next level of vegetables meat etc . . so quite urgent

**Comment by kirstenalarsen** [comment]
@sauloperez any chance you can have a look at this as I have a suspicion that spree upgrade may have been involved?

**Comment by sauloperez** [comment]
Sure

**Comment by sauloperez** [comment]
Although the UX it's a bit broken with that strange message, I can still create taxons. Can you confirm @kirstenalarsen ? 

![taxonomy](https://user-images.githubusercontent.com/762088/33474947-d003aa0e-d67c-11e7-9114-7648f211f0c6.gif)

Still working in https://github.com/openfoodfoundation/openfoodnetwork/pull/1984

**Comment by kirstenalarsen** [comment]
can still create the top level which is the 'taxonomy' e.g. products but can't create the next level e.g. vegetables. I don't know how closely tied our concept of 'product category' is to a spree taxon called Products . . which is what we've always had in aus production?

**Comment by sauloperez** [comment]
ok, I didn't check taxonomies before so I'm kind of discovering it. I'll take another look next week then.
