### ISSUE TITLE
Improve invalid number format treatment and UX on inventory page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1971]
**Problem description:**
On inventory page, if I fill in a number that has not a number format (ex: 2,50,50 or 2.50,2 or 2.50. or...) and try saving, the amount is saved with the invalid format and I get no error message. So if I don't pay attention, I don't realize that the amount I tried to enter is false.

![testing notes 1](https://user-images.githubusercontent.com/8135376/33020315-2efcf68c-cdfe-11e7-8f84-9637c715f3c5.jpg)

**Acceptance criteria:**
When I fill in a number that has not a number format and try saving:
- the system prevent saving
- the wrong amount I filled in is still there and appears in red 
- I see an error message "xxx. has an invalid format. Please enter a number."

**Comment by sauloperez** [comment]
See my comment https://github.com/openfoodfoundation/openfoodnetwork/issues/1970#issuecomment-348405112 which is also related to this.

**Comment by sauloperez** [comment]
We need to check first whether the backend returns already a validation error for that particular item so we can display it. If that's the case, it should be easy.

**Comment by sauloperez** [comment]
@kirstenalarsen mention that might related to EU number format. UK and AU haven't heard of this issue.

**Comment by kirstenalarsen** [comment]
have confirmed that this also happens in Aus. If I put a comma in the number or an extra full stop, it just doesn't save and doesn't give me any warning / notification of the problem
