### ISSUE TITLE
Default start date in reports should be 1st day of M-1 month

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1972]
**Problem:**
I got twice this feedback from 2 users in less than a month who have been in a serious mess as when doing the exports, they selected their OC but didn't pay attention to the "start date". Their OC was between two months, so they had missed in all their orders all the orders that were passed on the month before... which caused them serious troubles for the distribution :-o

![screenshot from 2017-11-21 10-43-12](https://user-images.githubusercontent.com/8135376/33065510-5e3d171e-cea9-11e7-8697-be6e40cc7240.png)

**Solution proposed:**
Change the start date by default to the 1st day of the month before.
I know that would be more data to charge by default, that would decrease even more the performances... any other idea how to solve that issue ?
Else I would propose to move forward with that.

@sstead @lin-d-hop any suggestion ? Did you solve that issue differently ?

**Comment by sstead** [comment]
I don't think we've encountered this problem is Aus. 
I don't see any problem with changing the default start date, except when super-admin accesses the reports- so much data might make the page crash. But maybe it will be ok.

**Comment by daniellemoorhead** [comment]
>I don't see any problem with changing the default start date, except when super-admin accesses the reports- so much data might make the page crash.

Is this likely to be the case @myriamboure? Perhaps it something to focus on during testing when this gets built?

**Comment by myriamboure** [comment]
@daniellemoorhead I'll show you in Aus, as an admin I can't already access any "order reports" anymore, it makes the system crash all the time... so for me it won't change anything as I can't access them anyway. Perf issues :-( I agree with @sstead that it won't make the situation better for admin... but it would avoid annoying mistakes for users... don't really know what to do. Let's discuss this case when we talk about perf in Aus ;)

**Comment by sauloperez** [comment]
what if we don't provide a default start date at all? The change you propose @myriamboure will make it work for some particular cases but not for others. If there's no default the user has to consciously choose a start date, so no mistakes there.

**Comment by myriamboure** [comment]
Yes but @sauloperez I guess then by default all infos will be charged and it will overload the app and the snale will appear ... The idea of the default start date is to limit the number of info charges no ? If not then I definitely agree with you Pau, no start day !

**Comment by sauloperez** [comment]
I was assuming that if the user does not provide a start/end date it would fail, but that might have other consequences in terms of UX.

**Comment by myriamboure** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/improve-oc-reports-ux-to-avoid-annoying-mistake-causing-wrong-deliveries/1160
