### ISSUE TITLE
Variant Overrides need to be marked with permission_revoked_at after an enterprise relationship is destroyed

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1976]
At the moment, there is an `after_save` callback on EnterpriseRelationship which sets the `permission_revoked_at` property of any variant overrides affected by that relationship. This works fine when revoking or reinstating Add to Inventory permission (aka `create_variant_overrides`), but it doesn't work when destroying the relationship completely. We need to add an after_destroy callback to ensure the same things happens there.

**Comment by cbordei** [comment]
I see this was added a bit after this issue was created: https://github.com/cbordei/openfoodnetwork/commit/9079437284aab3b83895b8c5625dca0189b00118 and it seems like it does what is asked here (although it does it with `before` not `after`)

**Comment by lin-d-hop** [comment]
Closing since we'll be working on removing variant overrides soon.
