### ISSUE TITLE
When an OC is tagged as invisible, the shop can show as open in the directory, but it looks closed to a visitor

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1980]
If a shop has OCs marked as invisible by default, but has on open OC that's visible to tagged customers, the shop will show as open on the Shop's directory. If a untagged visitor visits the shop however, it will look closed. This can be confusing. 

I'd suggest that there's a message such as 'this shop is only visible to certain customers, please contact the shop to gain access'. Or alternatively if the only OC that's open is one that's tagged, the shop should not show as open in the directly.

![image](https://user-images.githubusercontent.com/10843056/33406668-1a3c4a06-d5c2-11e7-8ade-e7e2c0ad6150.png)

**Comment by RachL** [comment]
I tested the above scenario and I had the message, so I guess this has been done since.

![image](https://user-images.githubusercontent.com/6525576/55338437-057c2280-54a1-11e9-9eaf-cdf78ac9aec2.png)
