### ISSUE TITLE
CI scripts fail with Postgres >= 9.2

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1993]
Postgresql [renamed](https://www.postgresql.org/message-id/E1T6wSQ-0005kN-LD%40wrigleys.postgresql.org) the `procpid` column which is used by our CI scripts in `script/ci/includes.sh`:

```sh
function drop_and_recreate_database {
    # Adapted from: http://stackoverflow.com/questions/12924466/capistrano-with-postgresql-error-database-is-being-accessed-by-other-users
    DB=$1
    shift
    psql postgres $@ <<EOF
REVOKE CONNECT ON DATABASE $DB FROM public;
ALTER DATABASE $DB CONNECTION LIMIT 0;
SELECT pg_terminate_backend(procpid)
FROM pg_stat_activity
WHERE procpid <> pg_backend_pid()
AND datname='$DB';
DROP DATABASE $DB;
CREATE DATABASE $DB;
EOF
}
```

On servers with newer Postgresql, we need to rename `procpid` to `pid`. I'm not sure how we do this in a backwards compatible way, since we have several servers with different Postgresql version.

As a workaround, I added this to our deploy script:
```sh
# WARNING: dirty
# Patch ci script for Postgresql 9.2 and newer.
sed -i 's/procpid/pid/g' script/ci/includes.sh
```

**Comment by sauloperez** [comment]
Can you open an issue in ofn-install for this?

**Comment by mkllnk** [comment]
Thanks Pau. I have created https://github.com/openfoodfoundation/ofn-install/issues/101. I would still keep this, because the failing CI script is in the openfoodnetwork repository.

**Comment by sauloperez** [comment]
Thanks @mkllnk!
