### ISSUE TITLE
'Choose OC' rectangle stays over the cogwheel menu display

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1995]
## Description
Cog meny is hidden by OC tag inviting to choose an OC when multiple OC.

## Expected Behavior
Cog menu is visible even if I click on it before choosing an OC.

## Actual Behavior
Cog menu is hidden below the OC choice tag.

## Steps to Reproduce
1 - Open a shopfront page that have at least 2 OC open
2 - Try to click on the cog menu

## Animated Gif/Screenshot
https://www.useloom.com/share/915cf5b18122441fb68ec11619e74ee7

## Context
Was reported by a hub manager who is a great debugger ;-)

## Severity
S5. The probability that a user want to use the cog before choosing an OC when multiple OC is very low.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
Display the crog meny on top (as it will always be an action you perform after the OC choices are proposed so sounds more logical on a UX prospective)

**Comment by RachL** [comment]
This is now fixed 🎉
