### ISSUE TITLE
Amount refresh real time not working on bulk edit product

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1997]
When I tested before https://github.com/openfoodfoundation/openfoodnetwork/pull/1831 was merged on staging it was working, but I know @ltrls and @oeoeaio have done things because of code climate afterward before merging, so I guess it broke the refresh real time.
We can leave with it, but it's annoying in term of ux.
Severity 4.

https://www.useloom.com/share/b9086f6d09004a53be35fb32eda7375c

Note: It is working as expected in inventory, only bulk product page is concerned.
But it takes a lot of time to save... I don't know if it's normal, you will see in the video.

**Comment by myriamboure** [comment]
For info, the real time refreshing is working on the French staging but not in production. Strange.

**Comment by RachL** [comment]
It took me a while to understand this one. From what I understand this is working now. We can reopen if needed.
