### ISSUE TITLE
Translations missing in "order management" pages

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2001]
## Description
Hub managers don't all understand English, and are confused when they see English strings (here only in back office so doesn't affect customers)

## Expected Behavior
All text is translated in local language

## Actual Behavior
Some strings are not translated

## Steps to Reproduce
1. In menu "orders", clic on the "edit" button of any order. On all sub-page here, in the horizontal sub-menu bar, "back to order list" not translated, green zone title on the right "order information" also, and "date completed"
2. Same page look at "poduct name/reference" ("select variant" untranslated) and click on the list ("please enter 3 or more characters" not translated) + in the table "shipping" not translated + botton button "update and recalculate fees" not translated
5. Then click on "adjustments", in the table, first column, "date/time" not translated and when shipping fees, "shipping" not translated.
6. Then click on "payments", in the table the two first column headers are not translated (date/time, amount)
7. Then click on "delivery", in the table the status is not translated ("pending" for instance)

## Gif or screenshot
![screenshot from 2017-12-20 12-34-01](https://user-images.githubusercontent.com/8135376/34187083-bbea0dcc-e583-11e7-9823-e0027f2919c2.png)
![screenshot from 2017-12-20 12-38-29](https://user-images.githubusercontent.com/8135376/34187087-bf50f17e-e583-11e7-8723-e255dd96d471.png)
![screenshot from 2017-12-20 12-38-45](https://user-images.githubusercontent.com/8135376/34187092-c6082168-e583-11e7-8c0c-28613fb9e2eb.png)
![screenshot from 2017-12-20 12-39-10](https://user-images.githubusercontent.com/8135376/34187094-c90a80fe-e583-11e7-83b6-54970d419d2a.png)

## Severity
4

## Your Environment
*Version used: 1.10.1
*Browser name and version: Chrome 53.0.2785.116 (64-bit)
*Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by mjal** [comment]
I just sent a PR but other mentioned texts come from spree codebase: Back to product list, Order information, Date completed, Date/Time, Amount and Pending.
There is probably not much we can do before the spree upgrade. (Maybe they could work by bumping our spree-i18n version)

I think that the last one ("Please enter 3 characters") comes from select2 (the select box library).
It's the same for "None" in #1999, I'll take a look at these two later

**Comment by sauloperez** [comment]
Are these copies you mention translated in spree-i18n? If so, which version?

**Comment by mjal** [comment]
I think it was progressively moved from spree/core/config/locales to spree-i18n so it depends on the text right now
The french translations for this came in spree-i18n v2.2 but I think that they are already available in spanish and other locales for the version we use
