### ISSUE TITLE
Flat percent calculator in shipping/payment method only applies to products total (excl. ent. fee)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2003]
## Expected Behavior
When "flat percent" calculator is chosen, the % is supposed to be calculated on the total amount charged in the order ([see user guide to check](https://openfoodnetwork.org/user-guide/producer-set-up-guide/shipping-methods/)), which is logical.

## Actual Behavior
The % is not calculated on the total amount charged in the order, but on the products total cost, excluding any entreprise fee that was added by the hub.

## Steps to Reproduce
1. In "entreprise"  menu, select an entreprise and go in "shipping method"
2. Chose calculator "flat percent" and save
3. In the corresponding shopfront, make an order.
4. Go in "orders", open your order, you will see the detail amount for shipping fee = % x products price

## Gif
![screenshot from 2017-12-20 15-25-08](https://user-images.githubusercontent.com/8135376/34191822-13cd4fbc-e59e-11e7-8ac2-39bb990af173.png)
![untitled presentation](https://user-images.githubusercontent.com/8135376/34191792-eb1aa29a-e59d-11e7-95b7-04f80c7cce43.jpg)

## Context
I was tackling the calculator translations issue and did some test, and realized it was not working as supposed to do.

## Severity
3

Potentially affecting all users using payment or shipping method fee, but there is a workaround, which is to set up a higher % on the shipping and payment fee to include the entreprise fee in them so that the calculated amount is good. I don't know if it's many users or not, could be severity 2 if very few users use that.

## Your Environment
* Version used: 1.10.1
* Browser name and version: Chrome 53.0.2785.116 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by luisramos0** [comment]
This looks like a feature to me: "include enterprise fees in shipping fees calculations". 

This calculator comes from Spree and computes on the "items total" (it's how it's called FlatPercentItemTotal) and does not include any adjustments.

Anyway, in terms of implementation, it is probably better to leave FlatPercentItemTotal and create a new calculator FlatPercentIncludingEnterpriseFees...
it will be something like this but will need to look up existing enterprise fees:
https://github.com/openfoodfoundation/openfoodnetwork/blob/187fbd788be9c7f283047ef9ae72fc6715d61ce3/app/models/spree/calculator/flat_percent_item_total_decorator.rb#L11

**Comment by drummer83** [comment]
Hope I got his right...
According to a recent discussion on Slack, this behaviour is ok for shipping and enterprise fees, but payment fees should be calculated incl. all other fees and taxes - because this is what the payment service will actually do.
[https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1600324879222800](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1600324879222800)

**Comment by RachL** [comment]
@drummer83 are you sure for the taxes? Hubs can be refunded of the VAT for Stripe or Paypal for example. So it would be weird to make the customer pay for it?

**Comment by drummer83** [comment]
You're probably right, @RachL. So glad my wife is doing our tax declaration... :-)

**Comment by lin-d-hop** [comment]
@audez just created a new one for this and we moved it to wishlist. Closing.

**Comment by audez** [comment]
oops i .. duplicated again!!! 
ty @lin-d-hop
