### ISSUE TITLE
[Spree Upgrade] Remove use of Order#shipping_method_id from ShippingMethodsControllerDecorator

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2010]
`app/controllers/spree/admin/shipping_methods_controller_decorator.rb` references the column `shipping_method_id` from the `spree_orders` table and this won't be longer available in Spree 2.0.

The work has already been started in: https://github.com/openfoodfoundation/openfoodnetwork/pull/1659

Initially we thought of making shipping_methods soft deletable, but currently, the easier approach seems to just keep the existing method and disallow deleting shipping_methods that are being used in orders.

**Comment by luisramos0** [comment]
we can also use this commit:
[b353d7a](https://github.com/openfoodfoundation/openfoodnetwork/pull/1651/commits/b353d7a8a5e2e7268130ee866efa6eb2f1919f85)

**Comment by luisramos0** [comment]
@sauloperez instead of going through all the trouble of making shipping_methods deletable (#1659) why dont we keep the current functionality of just blocking the deletion of shipping_methods that have already been used? Would that not be much easier/faster? (and allow us to focus on more important matters)
Thanks!
(I will mark this issue as blocked until this question is clarified)

**Comment by sauloperez** [comment]
Well, it does seem like refactoring that `#do_not_destroy_referenced_shipping_methods` to use the db schema will be much easier than implementing soft deletes. Is that what you mean?

**Comment by luisramos0** [comment]
Yes, just make that do_not_destroy refuse to delete shipping_methods that are already used.
If you agree, I'll go ahead with that.

**Comment by sauloperez** [comment]
Ype, seems reasonable.

**Comment by luisramos0** [comment]
ok, the simple solution is done and working.
I really wanted to leave it with a auto test covering it but I cant make it work for some reason. Help on #2728 needed...
