### ISSUE TITLE
[Spree Upgrade] Decide how we will implement Spree's new StockLocations/StockItems

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#2017]
After we've understood the data migration documented in #2012, we need to decide how to interact with Spree's new stock management system. This involves making a decision about how much of the new functionality we expose to OFN users in our initial cut.

One option that was discussed was to completely hide the functionality and simply use a single 'default' `StockLocation` for the entire platform, and have one `StockItem` for each variant. This should allow us to migrate across with minimal additional work, though some customisation/adapter logic may be required.

**Comment by luisramos0** [comment]
I am closing this spike. This is done. The approach is exactly what Rob suggests above:
"use a single 'default' StockLocation for the entire platform, and have one StockItem for each variant. This should allow us to migrate across with minimal additional work, though some customisation/adapter logic may be required."
