### ISSUE TITLE
[Spree Upgrade] Stock Management

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#2018]
Spree 2.0.0 introduces a much more sophisticated model for managing stock levels. Rather than a simple `on_hand` count for each variant, stock is modelled by `StockItems`, which can be held at multiple `StockLocations`.

We need to develop an approach to integrating this more sophisticated model into the OFN.

**Comment by sauloperez** [comment]
https://github.com/spree/spree/commit/2c48bfbaad98b8af35a5e95ba268a057c6973b47 is the migration we're talking about.

**Comment by sauloperez** [comment]
See the discussion :point_right: https://github.com/openfoodfoundation/openfoodnetwork/issues/2012#issuecomment-374969502

**Comment by luisramos0** [comment]
closing, wow!!!
