### ISSUE TITLE
[Spree 2 Upgrade] Fix references to MailMethod in specs

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2020]
## What

We need to get rid of the creation of `Spree::MailMethod` in all specs and use `Spree::Config[:mails_from]` instead. 

So in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/controllers/spree/orders_controller_spec.rb#L401 we would turn:

```ruby
Spree::MailMethod.create!(
  environment: Rails.env,
  preferred_mails_from: 'spree@example.com'
)
```

into:

```ruby
Spree::Config[:mails_from] = "spree@example.com"
```

**Comment by sauloperez** [comment]
This is not yet doable as it depends on https://github.com/spree/spree/pull/2643/files#diff-a428b7a87ba7179c65fcb97529aa2452R10 from Spree. Until we don't reach that point our efforts are pointless.

**Comment by luisramos0** [comment]
I just looked at spree 2 branch and I believe we do have this already and this is now doable and it is not blocked.

**Comment by luisramos0** [comment]
Specs referencing MailMethod in spree 2-0-4-stable branch:
spec/controllers/admin/subscriptions_controller_spec.rb
spec/controllers/spree/admin/orders_controller_spec.rb
spec/controllers/spree/orders_controller_spec.rb
spec/controllers/user_passwords_controller_spec.rb
spec/features/consumer/shopping/orders_spec.rb
spec/jobs/subscription_confirm_job_spec.rb
spec/mailers/enterprise_mailer_spec.rb
spec/mailers/producer_mailer_spec.rb
spec/mailers/user_mailer_spec.rb
spec/models/order_cycle_spec.rb
spec/models/spree/order_spec.rb
spec/services/create_mail_method_spec.rb
