### ISSUE TITLE
Uncheck shipping/payment method make the method disappear when only user

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2023]
## Description
When a shipping/payment method only apply to one entreprise, if that entreprise wants to unapply that method, the method disappear from the entreprise menu and he can't put it back if needs be.

## Expected Behavior
In the entreprise menu, if I uncheck "applied?" checkbox, the method should just appear as unapplied, but still be there.

## Actual Behavior
If you actually uncheck a method now, it doesn't just deactivate the method, but it completely disappears unless other enterprises are using the same method. Only super-admin can bring that method back.

## Steps to Reproduce
1. In the entreprise menu click on "shipping method". 
2. Ensure you have two methods created, and both are used only by your entreprise.
3. Uncheck the "apply?" checkox for one of them. And save.
4. The method has disappeared.

## Animated Gif/Screenshot
https://www.useloom.com/share/121339b8217a48f2ba02e481aa85c675

## Context
We noticed that issue when working on this other bug https://github.com/openfoodfoundation/openfoodnetwork/pull/1979#issuecomment-353486384

## Severity
3 (you can ask a super admin to restore the method, or create it again)

## Your Environment
* Version used: 1.10.1
* Browser name and version: Chrome 53.0.2785.116 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by yasirazgar** [comment]
@myriamboure, I checked both shipping and payment methods its working correctly, the unchecked item is not getting disappeared.

![2023](https://user-images.githubusercontent.com/7279519/34463433-c4ccdd46-ee81-11e7-8229-c40971ccbb4e.gif)

**Comment by myriamboure** [comment]
@yasirazgar did you check that the shipping/payment method were used ONLY by the entreprise you made the test with? Else you won't be able to reproduce the bug... if the method is used by another entreprise it doesn't disappear if unchecked.

**Comment by yasirazgar** [comment]
Yes, I made sure that shipping/payment method were used only the Enterprise which I tested. Ok

**Comment by yasirazgar** [comment]
@myriamboure, please take a look at the below screen shot for the payment methods.
![2023 - payment methods](https://user-images.githubusercontent.com/7279519/34509247-d29372da-f06d-11e7-93c2-7173ec9f5376.png)

**Comment by myriamboure** [comment]
@yasirazgar your entreprise user, does it have admin rights? I bet that's why you can't reproduce the bug (I see "configuration" in the menu that you can't see if you are not an admin ;-)). Your entreprise shouldn't have admin rights. I used an entreprise user who has a producer shop.
If you want the clear detailed explanation on how it works I recommend you to read Sally's comment [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/1979#issuecomment-353486384).
For the payment method there seem to be two different issues that Sally reported originally, but the one that I reported here is the same as for shipping method.

**Comment by yasirazgar** [comment]
Oops! sorry, let me take a closer look at it, will get back to you if I have any questions.

**Comment by yasirazgar** [comment]
@myriamboure, I was able to reproduce the issue on logging in as manager like you said, i have fixed the issue in this PR,
https://github.com/openfoodfoundation/openfoodnetwork/pull/2039
Please take a look.

**Comment by myriamboure** [comment]
Awesome @yasirazgar thanks a lot ! I think Pau gave you some feedback on the code side first, I'm not a developer myself but I'll be happy to test as soon as it's ready :-)

**Comment by myriamboure** [comment]
This is blocked at the moment as we need to review some things in our data model about how shipping/payment methods are associated to enterprises and permissions rules that apply to them. This is iceboxed https://community.openfoodnetwork.org/t/hubs-manages-without-friction-shipping-and-payment-methods-and-can-grant-permissions-on-them/1269 and we will be able to work on this bug only when we decide to prioritize this.

**Comment by myriamboure** [comment]
Closing as iceboxed
