### ISSUE TITLE
Tag rules are not working for show/hide payment method

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#2044]
While I can successfully show and hide variants now, having recently tried for the first time to show or hide payment methods at checkout, I found this not to be working. 

I wanted to make the payment option "invoice" available to existing customers only and force new customers to pay by card via stripe. 
The tagged payment method (invoice) can be hidden but it will be hidden from everyone, including those customers who should see it. 

Here is what I've done on UK production for Stroudco Food Hub. 
1) Set up rules as below:
![fireshot capture 012 - enterprises - ofn administration_ - https___openfoodnetwork org uk_adm](https://user-images.githubusercontent.com/17590921/34939060-6e58d3c2-f9e2-11e7-85b2-2b80f410917e.png)

2) Tag the payment method and customers
![screen shot 2018-01-15 at 10 47 27](https://user-images.githubusercontent.com/17590921/34938826-90e23f6a-f9e1-11e7-8f9d-990dfb0ae330.png)
![screen shot 2018-01-15 at 10 35 11](https://user-images.githubusercontent.com/17590921/34938831-95a16a30-f9e1-11e7-89ee-caabd6878dcc.png)

3) Log in using a different browser and try and check out using the payment method "invoice"
![screen shot 2018-01-15 at 10 36 30](https://user-images.githubusercontent.com/17590921/34938941-ff937636-f9e1-11e7-9c57-39ee9e3b5b87.png)
![screen shot 2018-01-15 at 10 37 02](https://user-images.githubusercontent.com/17590921/34938950-07410f06-f9e2-11e7-8de6-e38eb0d6bef9.png)

The payment method is hidden from me even though I'm tagged as someone who should see it.

**Comment by lin-d-hop** [comment]
Hi @OliverUK, just sent you a slack msg. Did you see the template when you set up the issue? Do you think in future you could stick closely to this template? Thanks!

**Comment by NickWeir63** [comment]
Hi @OliverUK I just had a quick look at this again and notice that there is no default tag rule set up for this - see top screenshot below.  Please can you try setting up a default rule to say that for payment methods tagged invoice the payment method is not visible.  Also I notice that the new invoice tag rule is duplicated.  it is probably worth removing it from the full member rule - see top of the second screenshot

![screenshot 2018-01-15 11 32 03](https://user-images.githubusercontent.com/10517702/34940734-9c93e8c0-f9e8-11e7-9783-ec295242f030.png)

![screenshot 2018-01-15 11 36 25](https://user-images.githubusercontent.com/10517702/34940759-ba1f420e-f9e8-11e7-827d-0b915acd5145.png)

**Comment by lin-d-hop** [comment]
Thanks for raising this via our support process @OliverUK! If you don't mind I'm going to close this issue while we run through the options from @NickWeir63 to keep it off the developer radar. We can reopen using the bug template if this doesn't solve the issue. Cheers!
