### ISSUE TITLE
Draft a new release

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2046]
There are quite a lot of merged PRs already and there are fixes needed.

**Comment by sauloperez** [comment]
Working on it!

**Comment by sauloperez** [comment]
Fun fact. We managed to release an issue from 2015 https://github.com/openfoodfoundation/openfoodnetwork/pull/498 :tada: :trollface:

**Comment by sauloperez** [comment]
Done in: https://github.com/openfoodfoundation/openfoodnetwork/releases

**Comment by daniellemoorhead** [comment]
Can we close this now @sauloperez ?
