### ISSUE TITLE
Security issue discourages to access a shop on mobile when clicking directly on the shop link

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2050]
## Description
On Android mobiles, when a customer clink on a shop link from his mobile browers, he get a security alert message and is discouraged to access the shop.

## Expected Behavior
When he clicks on the link the shopfront page opens.

## Actual Behavior
When he clicks on the link, he gets the security alert message and is not encourage to access the site.
BUT if he goes on www.openfoodfrance.org and from the "shops" page, find his shop and click from here, there is no issue.

## Steps to Reproduce
1. Send yourself an email with the link of a shopfront.
2. With an Android mobile, open this link directly from your mail manager.
3. You will get the error message.

## Animated Gif/Screenshot
![screenshot_2017-09-13-00-26-45](https://user-images.githubusercontent.com/8135376/35221355-b7db0ed2-ffde-11e7-984d-8ec21b80ed7d.png)
(It's in Spanish as we got this screenshot from a Spanish user selling to French customers)

## Context
The customer just hit that issue when he clicks on a shopfront link from an Android mobile...

## Severity
It discourages cusomters to access the shop on their mobile fom the link that hubs send them. The bug has been reported by at least 3 hubs on France who had messages from their customers. There are workarounds (like buy from a computer or find the shop from the OFN site on your mobile - doesn't work for invisible shops though) but it's very annoying for the customer and he doesn't know those workaround, so the bug is reported again and again by new customers... I put s3 though at it doesn't prevent to access the shop  but discourage a lot to do it, so might worth s2...

## Your Environment
* Version used: 1.10.1
* Browser name and version:  Chrome 50.0.2661.89
* Operating System and version (desktop or mobile): Android version 5.1
(the  bug has also been reported by someone using the default Samsung Internet browser)

## Possible Fix
Could that come from the SSL certificate?

**Comment by sauloperez** [comment]
It looks like it expired

**Comment by myriamboure** [comment]
No it doesn't @sauloperez , it's only on this specific case that it doesn't work...

**Comment by myriamboure** [comment]
Can it come from an issue with the SSL certificate configuration?

**Comment by sauloperez** [comment]
> Can it come from an issue with the SSL certificate configuration?

That must be it then, but I have no idea how that works.

**Comment by enricostano** [comment]
Would be great to have the full error from the browser

**Comment by HugsDaniel** [comment]
Have you checked with OVH ? They may have been flagged for another app.

**Comment by myriamboure** [comment]
I'm checking with the two users who reported that, for one it seems it is working now, I see the other one tomorrow... maybe it was random circumstances, like when we had issues with our ssl certificates...

**Comment by myriamboure** [comment]
Ok I got back to the three users who reported that bug to ask them to try again, and it seems to work now, so must have been a temporary issue linked  to our ssl certificate, closing the issue.
