### ISSUE TITLE
script/setup fails with psql: FATAL:  database does not exist

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2052]
## Description
The `script/setup` fails when checking `psql`. On my machine, where I have all set up and just want to regenerate my database's seed and install any missing dependencies, I get:

```shell
➜  openfoodnetwork (master) script/setup
The Gemfile's dependencies are satisfied
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
psql: FATAL:  database "pau" does not exist
psql: FATAL:  database "pau" does not exist
```

This might be related to what `colinf` mentioned in the Slack dev channel: https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1516315543000547

## Expected Behavior
The script should work without failures.

## Actual Behavior
It fails when checking information through `psql`.

## Steps to Reproduce

1. Setup the environment manually, including the test database, seed data, etc.
2. Run `script/setup`

## Context
I was just trying to put my machine up to date to run the rails server in development.

## Severity
Severity 3

## Your Environment
* Version used: sha 6d9cc7e29 from the master branch
* Browser name and version: Does not apply
* Operating System and version (desktop or mobile): Ubuntu 16.04.3 LTS

**Comment by HugsDaniel** [comment]
It seems that the package manager fails to create a database named $user. I ran `createdb` in terminal to create a db for login user. It doesn't fail anymore, however I get...
```
open_food_network_dev already exists
open_food_network_test already exists
-- create_table("account_invoices", {:force=>true})
rake aborted!
ActiveRecord::StatementInvalid: PG::Error: ERROR:  cannot drop table account_invoices because other objects depend on it
DETAIL:  constraint billable_periods_account_invoice_id_fk on table billable_periods depends on table account_invoices
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: DROP TABLE "account_invoices"
/home/hugs/code/HugsDaniel/openfoodnetwork/db/schema.rb:16:in `block in <top (required)>'
/home/hugs/code/HugsDaniel/openfoodnetwork/db/schema.rb:14:in `<top (required)>'
/home/hugs/.rbenv/versions/2.1.5/bin/bundle:23:in `load'
/home/hugs/.rbenv/versions/2.1.5/bin/bundle:23:in `<main>'
PG::Error: ERROR:  cannot drop table account_invoices because other objects depend on it
DETAIL:  constraint billable_periods_account_invoice_id_fk on table billable_periods depends on table account_invoices
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
/home/hugs/code/HugsDaniel/openfoodnetwork/db/schema.rb:16:in `block in <top (required)>'
/home/hugs/code/HugsDaniel/openfoodnetwork/db/schema.rb:14:in `<top (required)>'
/home/hugs/.rbenv/versions/2.1.5/bin/bundle:23:in `load'
/home/hugs/.rbenv/versions/2.1.5/bin/bundle:23:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```
... coming from `bundle exec rake db:setup db:test:prepare`

**Comment by sauloperez** [comment]
I believe we shouldn't have to create a role for the login user in Postgres. There has to be an easier way. 

> ERROR:  cannot drop table account_invoices because other objects depend on it

Is telling you that there are other connections to the OFN database, perhaps the rails server.
