### ISSUE TITLE
States are not displayed in modify address pop-in and prevent saving

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2057]
## Description
When I want to modify a customer address, I am asked to select a state, but the states list is not proposed so I can't select any state, and i I try so save, an error mesage is displayed and I can't save the address.

## Expected Behavior
In the  modify address pop-in, the states corresponding to the country selected are proposed in the list, so I can select the relevant one.

## Actual Behavior
No states list is proposed.

## Steps to Reproduce
1. Go to "customers", select a shop, the customer lists dispay. You have the possibility to modify the shipping and billing address for a customer.
2. Click on one of those addresses to modify it.
3. You see the states list, there is no list, try to save, you see the error message.

## Animated Gif/Screenshot
https://www.useloom.com/share/146773f9e8e64d02a6b8c50421fb069e

## Context
A hub manager is dealing with quite a lot of old people who doesn't manage to order themselves, so he does it for them. He tried to set up their address so that he doesn't have to re-write them each time, but he can't do it.

## Severity
3 (not a major feature, not a lot of users concerned, but a bit annoying...)

## Your Environment
* Version used: 1.10.1
* Browser name and version: Chrome 53.0.2785.116 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by mjal** [comment]
We only have Australian states in database now
I have a [pull request](https://github.com/openfoodfoundation/openfoodnetwork/compare/master...mjal:2057states-are-not-displayed-in-modify-address-pop-in-and-prevent-saving) ready for this one but it only covers French states. If we do it this way, we may also add states for other countries.
Spree uses [carmen](https://github.com/carmen-ruby/carmen) since 2.4, so a spree upgrade will also solve this issue.
Should I submit the pull request anyway ?

**Comment by sauloperez** [comment]
I understood your PR @mjal the fix is simply the addition of `parseInt`, right? In that case, that would be enough as each OFN instance have (or should at this point...) have their own states in their DB already. Am I right @myriamboure ?

**Comment by mjal** [comment]
The country states are on the seeds, maybe every instance have the same data at this point.
There was a bug, I added `parseInt` and `, true` as a fix because the id comparison wasn't strict. France with id "13" was strangely matched with another country with id "132"

**Comment by sauloperez** [comment]
yes, the seed data it's a mess we're currently working on... just open your PR and let's merge that fix :ok_hand:

**Comment by myriamboure** [comment]
> So the issue is about the UI and not about the data. Am I right @myriamboure ?
I guess so @sauloperez we do have states locally in our DB that shows in entreprise registration, etc. They just don't show in this pop-in and are blocking saving.

**Comment by sauloperez** [comment]
Agreed then.
