### ISSUE TITLE
Do not enqueue OrderCycleNotificationJob if there are no orders

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2062]
## Description
When going through https://github.com/openfoodfoundation/openfoodnetwork/pull/2058 we found out that we enqueue an `OrderCycleNotificationJob` regardless of the number of the orders in the order cycle. You would agree with me, that if there are none, there's no point in sending any email.

However, we do currently check that but too late; just before we're about to build and send the email from the background job. Check: https://github.com/openfoodfoundation/openfoodnetwork/pull/2058#discussion_r164449761

## What to do?
We should move that `if has_orders?(order_cycle, producer)` from https://github.com/coopdevs/openfoodnetwork/blob/c860ffc176918e8c856a44f6aa5c9cafe503ea21/app/mailers/producer_mailer.rb#L15-L21 to https://github.com/coopdevs/openfoodnetwork/blob/master/app/controllers/admin/order_cycles_controller.rb#L92

**Comment by lin-d-hop** [comment]
This isn't causing any problems. A quality thing, sure, but its oooold now.
