### ISSUE TITLE
Overlapping text along with moving icons within /admin

### ISSUE THREAD

**Issue by Cache123** [openfoodfoundation/openfoodnetwork#2064]
On the admin dashboard, if you view on a narrower screen width, "My Enterprises" and text from class "translation_missing" overlap.

![screen shot 2018-02-01 at 2 38 15 pm](https://user-images.githubusercontent.com/28741948/35705098-ba2a4d2e-075e-11e8-9e6c-8b30f0b1d0a5.png)

**Comment by daniellemoorhead** [comment]
Hey @Cache123 thanks for adding this issue. A question - where you on a small screen device for this?

**Comment by Cache123** [comment]
Hey @daniellemoorhead we were using our 13" laptops but were playing around for responsiveness with smaller screen sizes and noticed this.

**Comment by daniellemoorhead** [comment]
Unfortunately @Cache123 the backend admin section isn't built for small screens. It's one of a long list of improvements we'd like to make to the platform, but it hasn't been the most important thing to focus on (yet).

**Comment by Cache123** [comment]
@daniellemoorhead That's totally understandable :) Love your site and the mission you're accomplishing. Hope to be able to contribute in the near future! Thanks for the feedback.

**Comment by daniellemoorhead** [comment]
Looking forward to having you onboard @Cache123 !

**Comment by sauloperez** [comment]
@Cache123 welcome! Feel yourself at home! There's plenty of stuff you can contribute on. Pick up anything you like and don't hesitate to ask us whatever you want.

**Comment by RachL** [comment]
I didn't managed to reproduce this one. Closing.
