### ISSUE TITLE
Provide new seed data in load_sample_data

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2072]
## Description

The current [dev:load_sample_data](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/tasks/dev.rake#L6) adds quite a lot of records but not very useful when testing. AFAIK the `Enterprise 2` is the one that allows you placing an order right away, without having to add any payment or delivery method manually first.

We need enough sample data so that a tester can start testing the established test cases with the app after running the `dev:load_sample_data` rake task.

## Expected Behavior

After a branch is deployed in the desired environment, a developer can log into the machine and execute `db:reset` to erase the existing data in the DB, populate it with the seed data Spree provides, and then, execute `dev:load_sample_data`.

This provides all the data specified in: https://docs.google.com/document/d/1_va0Aw2yJ5BRe-HtuBT-OC8HNHIui0gvQ0uElWjDVs0/edit?usp=sharing

## Actual Behavior
The aforementioned rake task now populates the DB with the data that is not relevant for testing.

## Context

https://community.openfoodnetwork.org/t/seed-data-development-provisioning-deployment/910

## Severity

S-3. It's impacting the testing process a great deal and thus affecting our velocity.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Rewriting https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/tasks/dev.rake#L6

**Comment by myriamboure** [comment]
Is there any connexion with https://github.com/openfoodfoundation/openfoodnetwork/issues/220 ? If the other issue is outdated, please close it @sauloperez

**Comment by myriamboure** [comment]
If it's a wishlist to go further on seeds thing improvement after fixing bugs then tell me and I'll open a wishlist.

**Comment by sauloperez** [comment]
closed.

**Comment by sauloperez** [comment]
I'd like to review the attached socument again and provide more precise requirements if needed.

**Comment by mkllnk** [comment]
I commented on this on Discourse: https://community.openfoodnetwork.org/t/seed-data-development-provisioning-deployment/910/3
