### ISSUE TITLE
Subscriptions v1

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#2077]
[Updated by Myriam 22.10.2018]

## Original description of the problem this feature is solving
https://community.openfoodnetwork.org/t/a-hub-manager-can-setup-an-automatic-standing-order-for-a-registered-customer/1462

## Description of the feature
Big overview of how it works:
- hub manager can set up the recurring order, pause or cancel. If start date is before OC end date, order is made for the OC. If end date is before OC end date, no order is made for the OC.
- when OC starts, customer receives an email saying an order has been made on her behalf (can amend, if hub authorize it)
- when OC closes, customer receives an email saying the order has been confirmed and can’t be modified anymore

## Story map
Most user stories have been realized now, and after an end to end check, we are just listing in this epic now the last remaining bugs and big UX issues so that we can consider the feature as done.

You can get a view of all the remainin issues and bugs via the github project for this: https://github.com/openfoodfoundation/openfoodnetwork/projects/15

**Comment by enricostano** [comment]
@daniellemoorhead @oeoeaio any task to deal with translations before we go live with subscriptions?

**Comment by sstead** [comment]
Testing Feedback @oeoeaio 

issues found:
- Email issues when a subscription has items in it that are not in the OC
- There's no information about the shipping method in the email confirmations going to subscribers who pay with Stripe
- Emails to the shop owner are sometimes not sent
- Email not sent when an edited subscription order is first actiated
- Messaging isn't that clear when the manager starts or un-pauses a subscription mid way through open OC

https://docs.google.com/document/d/1GB9j6ks0FPVBu_pnqgOCuH9jUbjBzFBy5UhAfURT8Hs/edit?usp=sharing

**Comment by oeoeaio** [comment]
@enricostano I assume we just treat translations for this feature in the same way as we treat other translations. Is there any particular reason that this is a special case?

**Comment by enricostano** [comment]
> @enricostano I assume we just treat translations for this feature in the same way as we treat other translations. Is there any particular reason that this is a special case?

You're right, right now we have that strategy. I'm only wondering if all the instances are aware of the coming changes and that maybe they want to wait to deploy the release that will include this feature so they can translate the new keys first and then deploy the next (really near) release.

Ignore me, I'm just trying to understand if that rule is OK for all the cases or we need to be careful in some case. :sweat_smile:

**Comment by daniellemoorhead** [comment]
I hear you @enricostano and I think this is an opportunity for us to mature as a software development group to ensure that what we build is considered in the context of implementation. It makes me happy that this feature is currently hiding behind a toggle, I'm of the belief that this is good practice for any new feature we decide to build.

And perhaps we need to include consideration within our product development process about how to launch? We've done that with Subs (see the slack channel for that detail), but perhaps having it within the process will be of benefit in terms of consistency?

**Comment by myriamboure** [comment]
I'm closing this epic in the cleaning process I'm doing and will open a new one with the remaining things for standing order / subs feature to be consider as done.

**Comment by myriamboure** [comment]
I'm reopening it so we can keep track of all the past thing and not loose connexion. I'm just adding to the epic the last issues in the board project. Ideally I should have created a last sub epic, but now that there are no more sub epic it's ok to attach them directly I guess.

**Comment by luisramos0** [comment]
From what I understood we will consider subs v1 ready when the issues in the "subs backlog" column are closed.
I'd close this epic when that point is reached.

That means we can remove all the issues from this epic that are in both "Tech debt backlog" and "Bug Backlog". They become normal issues in the backlog.
@RachL do you agree?

**Comment by RachL** [comment]
> From what I understood we will consider subs v1 ready when the issues in the "subs backlog" column are closed.
I'd close this epic when that point is reached.

Yup that was my plan

>@RachL do you agree?

Yes!

**Comment by luisramos0** [comment]
ok, I have finished the dev of the last issue.
I removed the ones in Bug Backlog from this epic.
This is in Code Review :tada:

**Comment by kristinalim** [comment]
The last PR for this epic has been merged! :tada: :fireworks: :champagne: :smiley: Closing this epic now.
