### ISSUE TITLE
When long list of products unfolded, if modify lower product, "save" banner hide the line I'm modifying

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2081]
## Description
When I modify a list of products in "bulk edit" page, when products are all displayed, if I work on the last one of the list I can't see what I'm doing / writing as the lower "save" banner hide the line I'm modifying... if I "close" it the page is recharged so I loose what I was modifying.

## Expected Behavior
When I modify the lower line the "save" banner appear but below the line I'm modifying and I can still see my changes.

## Actual Behavior
When I modify the lower line the "save" banner appear on the line I'm modifying and I can't see my changes.

## Steps to Reproduce
1. You need to be logged in with an account that allow you to modify a products list
2. Go to "products" menu and click on "display all" (red writting at the left of the table) on the "bulk edit product" page
3. Try to modify the very last product, you will see that you can't do it properly.

## Animated Gif/Screenshot
https://www.useloom.com/share/c1c77ad61d7f404f97e14ce914b9d428

## Context
A hub manager wanted to update the products list of one of their suppliers.

## Severity
3 (basic feature that is not working properly - but there is a workaround which is to click on "edit product" on the right of the product)

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
Maybe just set up a fixed "blank" space at the end of any product list or even any "product" menu page maybe, of the high of the banner?

**Comment by myriamboure** [comment]
I'm proposing to move to S2 as I had again a feedback from a user, it seems they don't easily use the workaround and they are pretty annoyed by this little thing. I guess it's a very little think to modify, to you agree @enricostano ? If you agree I'll put directly in "delivery backlog" so that it can be taken by someone.

**Comment by sauloperez** [comment]
I'm not that sure another user complaining is reason enough to raise the severity, considering the number of users affected.

I just say this because I feel like we're turning lots of bugs to the same severity and that doesn't do us any favor. We risk the bug priorities becoming useless and so not helping in allocating our very limited resources, which was its purpose.

**Comment by myriamboure** [comment]
I would have been happy to discuss @sauloperez but @HugsDaniel was too quick ;-) Sorry about that, I didn't raise the severity just because one more complain but because I thought people where just not finding the workaround and stayed blocked... but I agree that it's arguable.
