### ISSUE TITLE
Doc how to manage Skylight

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2082]
## Description
Now that we introduced Skylight in https://github.com/openfoodfoundation/openfoodnetwork/pull/2070 as our Application Performance Monitoring service we need to document in the wiki how to create a new app in Skylight for every OFN instance that wants to use it, how to manage it, how to provision, how to enable it in staging, etc.

Then we'll need to update:
https://github.com/openfoodfoundation/openfoodnetwork/blob/183621f90b5ebbc42195bae2c9934beb63f900fd/config/application.rb#L30 to point to this wiki page instead.

**Comment by RachL** [comment]
hi @sauloperez I remember François telling me that Skylight had become quite expensive for France and that we have moved now to other tools. If this is true, can this issue be closed then?

**Comment by sauloperez** [comment]
It'd be good to understand why you had the need to pay. We haven't moved to other tools though it's just that there's is a misunderstanding about what Datadog and Skylight do. So it is still worth documenting.

**Comment by Matt-Yorkley** [comment]
You have to apply for an Open source account with them then it's free, right?

**Comment by sauloperez** [comment]
Yep
