### ISSUE TITLE
Customers authorise the use of credit cards by shops

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#2085]
## Overview
As part of the subscriptions feature, we want shops to be able to repeatedly charge customers for their orders using a stored credit card. At present, there is no mechanism by which customers can grant permission for this to happen. 

## Expected outcome 
Customers must be able to explicitly grant and revoke permission for shops to use their stored credit cards. At the bare minimum this will require a new UI element in the front-end accounts page, and a new field on `Customer` to indicate permission to charge cards.

**Comment by myriamboure** [comment]
@oeoeaio @daniellemoorhead just a process question, shouldn't we have created an epic for this with one issue per story, and then would have one PR per story? I have linked the 3 PRs to that story but probably would be "cleaner" to use epic next time I guess ;-) Do you agree Danni agile process master?

**Comment by daniellemoorhead** [comment]
@myriamboure yes, it would. However we haven't been following the "new way" with the subs stuff, it's been @oeoeaio getting all the things to done so we can get it done.

Future work on subs will be broken down in the way you describe :)

**Comment by oeoeaio** [comment]
Sorry @myriamboure, I thought it was only going to be one PR, but then it exploded into three!
