### ISSUE TITLE
If a user has items in cart and hub remove them from OC, he can still proceed to checkout and buy them

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2091]
## Description
A user can buy items that were removed/deleted from an order cycle if they had those products in their cart before retrieval.

## Expected Behavior
If at checkout time some products I have in my cart have become unavailable because removed from the OC by the manager, I should not be able to checkout and be sent back to my cart with an error message on the given item saying they became unavailable and prompting me to modify my cart.

## Actual Behavior
If at checkout time some products I have in my cart have become unavailable because retrieved from the OC by the manager, I am still able to buy them.

## Steps to Reproduce
1. In browser A, user A put in his cart x quantity of item y. He is ready to checkout but has not yet clicked on the last step of the checkout.
2. At that precise moment, the shop manager modify this very same order cycle and remove the given item OR producer from the order cycle, and save the change.
3. After that, user 1 click on the last step of his checkout and manage to proceed and buy the product.

## Animated Gif/Screenshot
https://www.useloom.com/share/4dcbfb6a0025435ea4014a0780921050

## Context
We reported while working on #1491 as part of the job for new feature #1031 persistent cart.

## Severity
s3 or s2 (to be discussed, putting s3 for now)

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
An attempt was made on #1767 but was not complete.

**Comment by mkllnk** [comment]
@myriamboure What do you mean by "retrieved"? Do you mean deleted?

**Comment by myriamboure** [comment]
Sorry @mkllnk forget about it I got confused;-) It has nothing to do it was about if you delete (yes!) a product or customer in an OC, was persisting in shop, so different problem ;-)

**Comment by myriamboure** [comment]
@mkllnk yes that's what I meant :-)

**Comment by myriamboure** [comment]
changes de termes to avoid confusion, thanks @mkllnk :-)

**Comment by sauloperez** [comment]
It might not be a good idea to work on this until we reach a stable point with Spree 2.0. It's the area of Spree we overrode the most and there might be 🐉 🐉

**Comment by sigmundpetersen** [comment]
Is this really a part of Spree Upgrade or is it just blocked by it?

**Comment by luisramos0** [comment]
This is blocked by spree upgrade but it is not part of it. This will be looked at after the upgrade. I have removed the spree2 epic from this issue.

**Comment by luisramos0** [comment]
Removing the reference to #2109 and moving it to epic #2584 (all the issues blocked by the spree upgrade).
