### ISSUE TITLE
Disable `should` syntax in specs

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2097]
## What? Why?

We are still using the very old RSpec should syntax. Chances are that this syntax won’t work in upcoming versions of RSpec and that may prevent us from upgrading RSpec in the future.

The problem is that we waste valuable time and energy reviewing the syntax used in a PR when this is better done by machines. We would be better off focusing on architecture and implementation.

This stems from https://github.com/openfoodfoundation/openfoodnetwork/pull/2084, which is a good example of this.

## Proposed solution

This needs to be disabled with RSpec itself. See https://relishapp.com/rspec/rspec-expectations/docs/syntax-configuration#disable-should-syntax.

## Dependencies

We tried doing it in https://github.com/openfoodfoundation/openfoodnetwork/pull/2180 but as explained in https://github.com/openfoodfoundation/openfoodnetwork/pull/2180#issuecomment-376897246, it can't be done until we reach Spree 3.0.

**Comment by sauloperez** [comment]
After opening https://github.com/rubocop-rspec/rubocop-rspec/issues/587, I have a more clear view of this. Rubocop-rspec does not have a cop to disallow the use of `should`. This has to be done through the RSpec configuration.

The problem with that is that all specs using `should` would fail. So we need to convert all of them to `expect` syntax before that.

**Comment by luisramos0** [comment]
#3837 migrates rspec syntax of:
- [X] validators
- [X] helpers
- [X] jobs
- [x] mailers
- [X] models
- [X] serializers
- [X] support
- [x] requests
- [x] services (171 tests)
- [x] lib (500+ tests)

there are still these to migrate as part of this issue:
- [ ] controllers (574 tests)
- [ ] features/admin (313 tests)
- [ ] features/consume (173 tests)

**Comment by luisramos0** [comment]
#3846 continues this.
but still some specs under spec/features to be converted: spec/features/consumer/cookies_spec.rb spec/features/consumer/shopping/shopping_spec.rb spec/features/consumer/shopping/embedded_groups_spec.rb spec/features/consumer/shopping/variant_overrides_spec.rb spec/features/consumer/shopping/embedded_shopfronts_spec.rb spec/features/consumer/shopping/cart_spec.rb spec/features/consumer/shopping/products_spec.rb spec/features/consumer/shopping/checkout_auth_spec.rb spec/features/consumer/shopping/orders_spec.rb spec/features/consumer/producers_spec.rb spec/features/consumer/authentication_spec.rb spec/features/consumer/shops_spec.rb spec/features/consumer/confirm_invitation_spec.rb spec/features/consumer/sitemap_spec.rb spec/features/consumer/account/cards_spec.rb spec/features/consumer/account_spec.rb spec/features/consumer/account/settings_spec.rb spec/features/consumer/registration_spec.rb spec/features/consumer/footer_links_spec.rb spec/features/consumer/groups_spec.rb spec/features/consumer/shopping/checkout_spec.rb

**Comment by luisramos0** [comment]
🎉
