### ISSUE TITLE
On tablet, checkout issues (to retest)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2103]
## Description
During check out, the box that shows the order has text rather than number totals under shipping, transaction fee and total. Doesn’t let check out as guest. 
(was reported here https://github.com/openfoodfoundation/openfoodnetwork/issues/1092 but looking for a tablet to retest and see if still problems, will open separate issues if needs be)

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot
![bug1](https://user-images.githubusercontent.com/8135376/36777019-28fa931c-1c68-11e8-9d49-accc36c7d26b.png)

## Severity
Could be S3 or even S2 if prevent from ordering as guest, but let's check.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by myriamboure** [comment]
@sstead or @RachL does any of you have access to a tablet? Can you test if there is still an issue on tablet with checkout "text instead of numbers" and "checkout as guest"? And if there is an issue please update the initial post. Thanks!

**Comment by RachL** [comment]
@myriamboure @sstead sorry I do not have my tablet anymore. Mobile should work as well isn't it ? If so, I can do some test on my side.

**Comment by myriamboure** [comment]
Hum... the previous person who reported that had seen that issue on tablet but not mobile (strange) so I would say why not, let's retest on mobile and if checkout as guest and amounts summary are all good, let's close this. We can reopen an issue if other problems later, this was an old bug that was reported, probably before many things changed... so go for it @RachL

**Comment by sstead** [comment]
I don't have access to a tablet. I had a quick test on my phone and didn't see the issue.

**Comment by myriamboure** [comment]
Ok let's close and we'll reopen if we see other issues later.
