### ISSUE TITLE
Users can't access openfoodfrance from Samsung tablet (mobile maybe also)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2104]
## Description
I tested with my mother Samsung tablet Galaxy Tab 2 10.1.
I try to access https://www.openfoodfrance.org, got the security alert message and I can't proceed, no way to go over this message. Same if I type directly https://www.openfoodfrance.org/hub-demo-open-food-france/shop.
On the tablet set up I disable "warning messages if security issue" (but users shouldn't have to do it, not a good practice at all!!!), and still, when I try to access the shop, products don't get loaded... I waited for 5 min. Tried to use filters, didn't work. Tried to login, no change.
I'm not able to access the products list and shop, even if manage (not trivial) to passe security alter.

## Expected Behavior
I can access the shopfront

## Actual Behavior
I can't on Samsung Galaxy Tab 2 internet browser.

## Steps to Reproduce
See above description.

## Animated Gif/Screenshot
Security altert, can't go forward:
![img_8630](https://user-images.githubusercontent.com/8135376/36816748-132489fe-1cdf-11e8-9397-9926b0336e29.JPG)

Try to click on "display certificat":
![img_8631](https://user-images.githubusercontent.com/8135376/36816762-1b72c684-1cdf-11e8-92d4-463df7839f9c.JPG)

Then click on "display  info page" from there:
![img_8632](https://user-images.githubusercontent.com/8135376/36816768-1f2de4e8-1cdf-11e8-8722-025ab331e0eb.JPG)

Changing security parameter from the tablet:
![img_8633](https://user-images.githubusercontent.com/8135376/36816771-21ff2aa6-1cdf-11e8-81ca-4f518fa8aa80.JPG)

Then able to connect but unable to load products:
https://drive.google.com/open?id=1vUlTLQJHMAJ2kP259_7sCnJmrdy89oWr

## Context
I tried to retest an old bug. I had received also sporadic feedbacks from hub telling me some users have issues with Samsung tablets and phone (couldn't yet reproduce on phone but suspect problems might be the same)

## Severity
S1, some users don't manage to access the website.

## Your Environment
* Version used: 1.10.1
* Browser name and version: Samsung Internet (for Samsung Galaxy Tab 2 10.1, seems to be Android browser but I can't find the version)
* Operating System and version (desktop or mobile): Android 4.0 (Ice Cream Sandwich)
(https://en.wikipedia.org/wiki/Samsung_Galaxy_Tab_2_10.1 or http://www.samsung.com/fr/consumer/mobile-devices/tablets/others/GT-P5100ZWAXEF/)

## Possible Fix
?

**Comment by myriamboure** [comment]
I suspect older version of Android internet browser (from 2012-2013) are causing those issues. With recent Samsung phones I didn't see that issue. But there are still quite a lot of people who have a 5-6 year old phone... so I think we should support those versions of Android browsers.

**Comment by daniellemoorhead** [comment]
Hi @myriamboure, this leads to the question of how many old versions of tablets/phones/browser versions we should be supporting (the bigger the list, the more effort required). An android tablet from 2012 that hasn't updated the operating system or browser version to me is not something that we should be supporting anymore. As much as it pains me to say that, trying to support the myriad of different versions of Android that each device provider has set up on their phones/tablets is really really hard to do. iOS was easier, it was constrained within the Apple ecosystem. But supporting Android is a nightmare.

Even Google only supports to a certain level: https://www.forbes.com/sites/ewanspence/2017/02/20/google-kills-android-gingerbread/

Can I suggest that we determine as a global group which device software versions we will support as a minimum, that way there will be a line drawn in the sand for us on when something is a high severity...and when it is unsupported. We unfortunately can't support all the things 😢 

I also wonder whether a severity 1 rating is correct when this issue is hitting such a tiny tiny percentage of our total user base?

**Comment by myriamboure** [comment]
I understand @daniellemoorhead I'm a bit torn because I hate planned obscolescence and want to applause those who keep their devices for a long time! But I also undertand the reality and cost of this, so then it's important that we define until which version we support and display that somewhere in our website (where should it be? In footer? but not really visible... in the confirmation email people receive when they register! Something at the end like: Be aware that if you use an old version of a browser you might not be able to use the site... ) SO  propose to add a task in "global communication / in single cohesive unit?" about better communicating about the service we offer (this could be part of it and would avoid people thinking the site is not working...) in Milanote, add it to the roadmap priority list and create an icebox for that (even if not pure dev thing but will need some devs I think to analyse what is reasonable). What do you think @daniellemoorhead about that plan?

**Comment by Matt-Yorkley** [comment]
It looks like an SSL certificate issue with google fonts, maybe they've changed something? Maybe our google font links need updating in some way?

**Comment by daniellemoorhead** [comment]
>What do you think @daniellemoorhead about that plan?

I don't think this has anything to do with single cohesive unit, but it's a clarification in what we do/don't support. If it was to fit anywhere it'd be the make what we have great stream. Happy for you to add it!

FYI There's a feature that can be implemented that recognises when a user is coming in on an unsupported browser (not sure about device) and alerts them to the fact. Not that we need to do this, but this is what we did on other projects I've worked on as a way to kill Internet Explorer 6 DEAD 😈 

Usually supported browsers goes on the help/support pages of a website. The place people go to when something goes wrong.

**Comment by daniellemoorhead** [comment]
>Maybe our google font links need updating in some way?

Easy thing to check @Matt-Yorkley?

**Comment by myriamboure** [comment]
Ok Iceboxed this here @daniellemoorhead : https://community.openfoodnetwork.org/t/clearly-communicate-about-which-browser-we-support/1249, whatever this is a bug linked to google font we will need at some point to communicate clearly with our users on which browsers we support. Let's see Matt's feedback on the google font thing and see what we do with that issue.

**Comment by myriamboure** [comment]
I'm closing this for now as no more request from users, and no recent feedback from users... it was an old device anyway, let's see if other cases show up.
