### ISSUE TITLE
Spree Upgrade to 2.0.4

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#2109]
Hey @enricostano @sauloperez I've created this single placeholder for the Spree Upgrade sub work to go under. I'm assuming that all the spree work you do (as outlined in #2018, #1957 and #2011) will all need to be released as a "feature" together, so I've put those three epics under this one and we can use this one within the feature backlog.

If this isn't correct and you can actually release each of these epics as separate pieces then let me know and I'll get rid of this epic and put it back to the way it was 😄 

If this is correct then you'll have responsibility for adding detail in here about the work to be done, which can be a high level reference for anyone trying to understand what you're doing. So feel free to delete what I've written here and add that detail. 

💪 🤘

**Comment by sauloperez** [comment]
:ok_hand:

**Comment by luisramos0** [comment]
Update title to reflect a more specific scope. From this discussion it's pretty clear we are going live with 2.0.4 before continuing upgrading to 2.0.8 or 2.1.0: https://community.openfoodnetwork.org/t/spree-upgrade-go-live-on-v2-0-4-or-move-further-to-2-1-0/1534/2

**Comment by sigmundpetersen** [comment]
I think we can close this Epic now @luisramos0 ?!!? 🎉 💪 🕺

**Comment by luisramos0** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
  🎉 🎉 🎉 🎉 🎉 🎉 ahahaha, can you believe it?  🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by enricostano** [comment]
![](https://media0.giphy.com/media/1Bd8arYi1NXBFjTMpl/giphy.gif?cid=790b76115cd2a2f8714f685855ce1acf&rid=giphy.gif)
