### ISSUE TITLE
On producer modal, "shop X products at" is gone

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2112]
## Description
On the producer modal, there are links at the bottom but there is not anymore any indication of what those links are.

## Expected Behavior
An intro line, as it was before "shop for X products at"
![bugnew](https://user-images.githubusercontent.com/8135376/36949129-843fa6ac-1fe4-11e8-96bb-05633ba52412.png)

## Actual Behavior
No intro line, directly the shops url
![screenshot from 2018-03-04 19-40-58](https://user-images.githubusercontent.com/8135376/36949138-92d4d232-1fe4-11e8-836b-fbf47c792982.png)

## Steps to Reproduce
1. Go on map and click on a producer icon, or from a shop below product name.

## Context
Was retesting old issues.

## Severity
S3, a bit annoying in term of UX and no UX workaround really... and affect everyone.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
Restore the line.

**Comment by wrycoder** [comment]
Sorry for the long delay on this. Now that I have started to investigate, I'm having trouble reproducing the problem in my tests. (The string "SHOP FOR [X] PRODUCTS" is successfully found in the page.) Is there more to the user story here?

**Comment by myriamboure** [comment]
@wrycoder I just retested on French production and the string is still not displayed, so I don't understand why you can't reproduce... That might be one clue: the string appear correctly ("shop now" or "change shopfront for") for hub type enterprises (the red icons on the map) BUT the string "shop for x products" which applies for non-hub producer type enterprises is not displayed. Does it help?
