### ISSUE TITLE
Product Filters Icons don't appear on French instance

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2130]
## Description
Both on computer and mobile, we don't have any icon for product categories (whereas they do in Aus and Uk and...)

## Expected Behavior
Show Icons

## Actual Behavior
Icons not shown

## Steps to Reproduce
1. Click on a shop dropdown, or within a shop you see filters don't have the small nice icons.

## Animated Gif/Screenshot
**In France:**
![screenshot from 2018-03-10 21-19-08](https://user-images.githubusercontent.com/8135376/37246425-f0c02a0e-24a8-11e8-9f98-622e552d25c6.png)
![screenshot from 2018-03-10 21-19-28](https://user-images.githubusercontent.com/8135376/37246430-f9214d40-24a8-11e8-88c5-3425689981f8.png)

**In UK:**
![screenshot from 2018-03-10 21-20-16](https://user-images.githubusercontent.com/8135376/37246432-fe4dd86a-24a8-11e8-854f-48b86bc7e98f.png)
![screenshot from 2018-03-10 21-20-32](https://user-images.githubusercontent.com/8135376/37246434-028fa8d6-24a9-11e8-8fe2-84612f66d3f9.png)

## Context
Wanted to see how to make the shop nicer and saw that diference, which can be a small start :-)

## Severity
S4 (we've been living with it for ages... but would be great to fix as would improve a bit UX)

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
Decribed in https://github.com/openfoodfoundation/openfoodnetwork/issues/1312 (UK had the same issue earlier) > I asked on Slack to get the images for the icons so that we can do the same.

**Comment by myriamboure** [comment]
Assigning you @pacodelaluna as when we will have the images you will have to put them somewhere on our server (see #1312 they explained how to do it). I'll let you know when we got them.

Note to self: update this page (https://github.com/openfoodfoundation/ofn-install/wiki/Administration#taxonomies) when we have put the icons on Google Drive OR share Dropbox link to access directly the images.

**Comment by myriamboure** [comment]
@pacodelaluna the icons are here: https://drive.google.com/open?id=17mXE54QUxk-8TrHOOJSkuJFkIJpDd6J1 so if you look at the other issue I mentioned you should see how to add the icons :-) Thanks!

**Comment by enricostano** [comment]
We started this repo https://github.com/coopdevs/ofn-taxonomy some time ago, at some point we should treat taxonomies with the same strategy we use with states.... one day... :sweat_smile:

**Comment by myriamboure** [comment]
It seems Canada is having the same issue as France, categories icons are not showing on the shopfronts or search. Can someone add them on the French and Canadian servers as explained in #1312 ? @pacodelaluna ? Anyone ? If it's like 15 min and solve a problem for 2 instances it would worth it :muscle:

**Comment by sauloperez** [comment]
We don't have them either in Katuma. I'm not sure fixing them manually is the best solution here given that fact that we're adding more OFN instances. It might fix it for now but the problem will come back again soon.

**Comment by RachL** [comment]
I'm closing this one as we are leaning to remove those icons completely.
