### ISSUE TITLE
Undefined method `has_spree_role?` for nil:NilClass

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2132]
## Description
Some days ago we got notified in Bugnsnag of the error below:

![error1](https://user-images.githubusercontent.com/762088/37276716-dd42145c-25e2-11e8-8071-90df4df1b371.png)

We just realized that the Bugsnag free plan keeps the data just for 7 days so we got no other details besides the screenshot above.

## Expected Behavior
The app should either show the order cycles or redirect to the login in case of an unauthenticated requested.

## Actual Behavior
The order cycles page fails rendering the snail page (very likely)

## Steps to Reproduce
Unknown

## Animated Gif/Screenshot
None

## Context
This was notified by Bugsnag

## Severity
Severity 3. There's no workaround that I know of but it just happens from time to time to individual users.

## Your Environment

* Version used: v1.11
* Browser name and version: Unknown
* Operating System and version (desktop or mobile): Unknown

## Possible Fix

We need to check why an empty user is received in the line below:

https://github.com/openfoodfoundation/openfoodnetwork/blob/afda5cc04ee972cb30b3bc0bc655a5b7818b8ab2/app/models/order_cycle.rb#L61

which comes from:

https://github.com/openfoodfoundation/openfoodnetwork/blob/afda5cc04ee972cb30b3bc0bc655a5b7818b8ab2/app/controllers/admin/order_cycles_controller.rb#L119

Could it just be an authenticated request not properly redirected to the login?

**Comment by enricostano** [comment]
Guest customers?

**Comment by sauloperez** [comment]
Well, yes, not logged in users

**Comment by myriamboure** [comment]
I'm not sure I understand the issue... but I'm looking for 2-3 issues that we can delegate to some devs who have some free time (occasional) can we put that in @sauloperez ?

**Comment by sauloperez** [comment]
Yes, @myriamboure. Someone should take a look

**Comment by myriamboure** [comment]
@sauloperez is this still an issue or did the work we did on disabling guest orders for users had an impact on it? Luis could work on that if you think the problem is still there.

**Comment by sauloperez** [comment]
Let me check when is the last time we saw this.

**Comment by frank-west-iii** [comment]
@sauloperez and @myriamboure, this is the same error here: https://github.com/openfoodfoundation/openfoodnetwork/issues/2271

This would be "solved" by the PR on that issue.

**Comment by myriamboure** [comment]
This is a bit too tech to me I let @sauloperez answer that question ;-)

**Comment by myriamboure** [comment]
@sauloperez now that https://github.com/openfoodfoundation/openfoodnetwork/issues/2271 has been merged, is this issue fixed? Can we close it?

**Comment by sauloperez** [comment]
yep
