### ISSUE TITLE
Edit Customer address form is too zoomed in to see Save button

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2139]
## Description
When a shop owner goes to edit or add an address to a customer the form is zoomed in too far - I cannot see the Update button. Using the page's scroll bar doesn't help, instead I need to zoom out in my browser to 90% to see the button. Users shouldn't need to zoom in and out to use the page.

## Expected Behavior
Ideally the whole form will fit in the browser at 100%, otherwise the form needs its own scroll bar.

## Actual Behavior
The update button is out of sight at the bottom of the page.

## Steps to Reproduce
1. Go to admin/customers
2. Have your browser at 100% zoom
3. Edit a customer's address

## Animated Gif/Screenshot
Note you cannot see the Update button at the bottom of the form.
![image](https://user-images.githubusercontent.com/10843056/37378124-f8e461c4-2781-11e8-8754-5380b3e0c4a5.png)

## Severity
3-4 

## Your Environment
PC, Chrome.

**Comment by Erioldoesdesign** [comment]
This doesn't seem to happen on my machine which is a mac 2012 using latest OS and Chrome versions

<img width="1280" alt="Screenshot 2020-11-04 at 22 43 35" src="https://user-images.githubusercontent.com/11681324/98175835-421ac600-1eef-11eb-8237-8a5091545659.png">

<img width="1280" alt="Screenshot 2020-11-04 at 22 42 01" src="https://user-images.githubusercontent.com/11681324/98175827-3fb86c00-1eef-11eb-9c4c-5f20129b9633.png">

**Comment by RachL** [comment]
Indeed, even on my tiny screen: closing!
