### ISSUE TITLE
Automatically configure mail from seed data

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2141]
## Description

It's the thing we spend most of our time (and our mood...) on when deploying to staging and when setting up a new instance. Hence, having that done automatically from `db:seed` would be a huge gain.

It's just about doing what is done from the UI on `/admin/mail_methods/new` but without human intervention, which hopefully will also remove the human error.

To do that, we need to provide the domain and the API key as env var and then use that data to populate the spree config as Spree does internally when executing that controller action.

**Comment by sauloperez** [comment]
@curation_team I haven't found any epic for this seed data epic or the new sys admin standardization. Let me know how you want to proceed so we don't loose track of it. Keep in mind that this is a feature and not a bug.

**Comment by myriamboure** [comment]
I think if you open that issue on OFN-install (isn't it better to put it there? It's about install, deployment, etc.  no?) you have an epic there on sys admin standardization @sauloperez 
I would vote to proceed on this one in the sys amin standardization priority epic as it seems it would save us sooooo much time in all the staging deployment we do all the time. I see @pacodelaluna fighting so much with it, I don't know how many hours he has spent on it already... Do you agree @enricostano @kirstenalarsen @oeoeaio ?

**Comment by enricostano** [comment]
Nope, this is a change in OFN. Not `ofn-install`. In any case the epic can be "sys amin standardization"

**Comment by sauloperez** [comment]
Agree. Let's create a copy of that epic that we have in ofn-install. This way we can match the things we do regarding this topic.

**Comment by myriamboure** [comment]
@sauloperez @enricostano I created the epic please put in it all what's related to sys admin standardization and feel free to amend my description if it's not accurate.

**Comment by myriamboure** [comment]
@sauloperez @enricostano I put the epic in "inception" in project "product development backlog" so that you can identify all the stories=issues needed to be worked on. Also as we said we would prioritize this epic in Q1 so please put in delivery backlog (zen hub pipeline) any issue that is in this epic after you've done the inception ;-) I guess you tech people are doing the inception alone on that and don't need PO view.
