### ISSUE TITLE
Sys admin standardization

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2142]
## Description
We lose a lot of time in staging deployment or setting up new instances because of unstandardized or undocumented process, things that are just broken, monitoring issues, delayed job issues, email not sent issues, etc.

## Feature candidate
- disconnect staging deployment from Australia
- update seeds data
- automatically configure mail from seeds data
- ...

## Metrics
Staging deployment is smooth and easy for all sys admins and enable support to one another.

## Icebox item
Discourse discussion on global sys admin process (sorry no formal icebox item opened for this one it was just an obvious priority)

**Comment by sigmundpetersen** [comment]
Guess you mean https://github.com/openfoodfoundation/ofn-install/issues/172

**Comment by sauloperez** [comment]
Oops, yes. I thought I was on ofn-install. That remaining issue belongs there.

**Comment by myriamboure** [comment]
Closing it, I moved the last issue to the new epic, thanks Pau.
