### ISSUE TITLE
Upgrade Webmock

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2144]
## Description

The [Webmock](https://github.com/bblimke/webmock) test gem requires an upgrade. While we're at 1.8, the latest version is 3.3.

We know from https://github.com/openfoodfoundation/openfoodnetwork/pull/2136 that upgrading to 2.0 already caused some specs to fail. Some unstubbed request in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/requests/checkout/stripe_connect_spec.rb arouse.

## Possible Fix
Let's go straight to 3.3 and make the required changes. Only if these were way too much and took us too much time would I consider aiming for 2.0 first.

**Comment by sigmundpetersen** [comment]
Fixed by #2572. Correct me if I'm wrong.

**Comment by sauloperez** [comment]
Yep, thanks for the heads-up
