### ISSUE TITLE
Upgrade Poltergeist

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2145]
## Description

The [Poltergeist](https://github.com/teampoltergeist/poltergeist) test gem requires an upgrade. While we're at 1.16, the latest version is 1.17

We know from https://github.com/openfoodfoundation/openfoodnetwork/pull/2136 that upgrade caused a spec to fail. If I'm not mistaken the expected markup wasn't present on a page but we still need to check.

## Expectation
We want `poltergeist` to its latest version now that it's just a small change.

**Comment by sigmundpetersen** [comment]
FIxed by #2606. Correct me if I'm wrong.

**Comment by sauloperez** [comment]
Yep, thanks for the heads-up
