### ISSUE TITLE
Upgrade DatabaseCleaner

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2146]
## Description

The [DatabaseCleaner](https://github.com/DatabaseCleaner/database_cleaner) test gem requires an upgrade. While we're at 0.7.1, the latest version is 1.6.2 😱 

We know from https://github.com/openfoodfoundation/openfoodnetwork/pull/2136 that upgrade cause many specs to 💥 . It will require an in-depth investigation of its configuration settings and changes on our side.

## Possible Fix
A gradual upgrade, one minor version at a time, might be of help here, but it will take us some time one way or another. It's time to pay the tech debt, including lots of interests 😞

**Comment by sigmundpetersen** [comment]
Removed in #3106. Can this be closed? @sauloperez @luisramos0 @mkllnk

**Comment by luisramos0** [comment]
#3106 is closed, not merged.

**Comment by sigmundpetersen** [comment]
Ah, good thing I asked 🙂

**Comment by luisramos0** [comment]
the rails 4 upgrade brought 1.7.0, we can still upgrade to latest, see #5716
