### ISSUE TITLE
Broken asset precompile in master branch

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#2147]
## Description
Running asset precompile task is broken: https://gist.github.com/enricostano/ee9657165bd7cd08d5ef6788277568f9

## Expected Behavior
Should build assets without errors.

## Actual Behavior
https://gist.github.com/enricostano/ee9657165bd7cd08d5ef6788277568f9

## Steps to Reproduce
1. Run the `assets:precompile:primary` task

## Context
I was trying to deploy `master` branch to our staging.

## Severity
This is an emergency, we cannot release a new version with this error in place.

## Your Environment
* Version used: `master`

## Possible Fix
Not sure yet.

**Comment by enricostano** [comment]
OK, it seems that `moment.js` requirement has been added by https://github.com/openfoodfoundation/openfoodnetwork/commit/f6af5098b0897d3fb6cb0926f0c5d8e6eb51bc0a in https://github.com/openfoodfoundation/openfoodnetwork/pull/2068

I also see that `moment.js` was added by https://github.com/openfoodfoundation/openfoodnetwork/pull/1819/files

cc/ @oeoeaio @leandroalemao

**Comment by enricostano** [comment]
Mh, it seems that the JS libraries installed with a ruby gem are noit being picked.

**Comment by enricostano** [comment]
Emergency resolved, the real issue is that precompiling assets takes so long that the deploy process loose connection and get unresponsive. :(

**Comment by sauloperez** [comment]
oops, it takes long but this never happened to me. Looks like the "bundle" might be getting too big

**Comment by sigmundpetersen** [comment]
Yes this happened to Norway as well (on every deploy). It used up all RAM 😑 So I restarted the server before a deploy to make it work 😊 I have upgraded the server recently with double RAM and haven't tried a deploy after.

**Comment by sauloperez** [comment]
Let us know the result @sigmundpetersen !

I just deployed master to our staging and this is what ansible returns... 

```
Thursday 15 March 2018  17:52:00 +0100 (0:00:00.042)       0:24:15.119
```

**Comment by mkllnk** [comment]
Every merge we do in Aus goes through our staging server first. We had no trouble deploying and I just staged something new based on master which staged successfully as well.

This is not a complete test though, because we keep the cache of previous compilations. So if the compilation fails on something that doesn't need compiling on staging, then we don't notice.
