### ISSUE TITLE
Subs: update OC closing date in subs. dashboard when changes occur

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2156]
## Description
I created an OC with French time so was already closed in Australia, then changed to fit to Aus time, but in the subscription dashboard the OC still appears as "closed x hours ago" AND there is a translation missing to fix.

## Expected Behavior
"closed" is translated + if the OC close date is changed the info in subs. dashboard should also be updated.

## Actual Behavior
"closed" translation is missing + the OC close date doesn't update if there is a change in the OC close date.

## Steps to Reproduce
1. In "orders", "subscriptions", you see the dashboard of the existing subscriptions.
2. Unfold one of them, check which OC is there and which end date is displayed.
3. In "order cycle "find the corresponding OC and change close dates. Save.
4. Go back to subs. dashboard: you see the close date has not been update.
5. Then go back to the OC and put a past date as closing date.
6. Create a new subscription  on this OC. In the subs dashboard you see the "closed" translation missing.

## Animated Gif/Screenshot
![screenshot from 2018-03-20 09-20-48](https://user-images.githubusercontent.com/8135376/37643176-039246ca-2c20-11e8-9eb5-ac51b32844ea.png)

## Context
I was testing subscriptions for the first time and got stuck when filling in the date...

## Severity
NA, new feature being developped.

## Your Environment
- Version used: 1.11
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
- translate "closed"
AND
- make sure closing date is updated in subs dashboard

**Comment by myriamboure** [comment]
@oeoeaio put this in the project backlog, it is pretty confusing for users so I suggest we include that in the first subs. scope. What do you think?

**Comment by oeoeaio** [comment]
Translation should been fixed already by #2088, which should be included in v1.12.

I don't know how the other issue with OC closed dates failing to 'update' could possibly happen, it should be reading from the exact same field. I will add it to my list of things to look at.

**Comment by sstead** [comment]
I think this is still happening inconsistently, i'll leave the issue open for now.

**Comment by myriamboure** [comment]
Closing this issue as captured more clearly here https://github.com/openfoodfoundation/openfoodnetwork/issues/2878
