### ISSUE TITLE
Subs: strange conflict make OC appear as "close date not set" in subs dashboard

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2157]
## Description
I created a second OC at the exact time where the first one was opening. I don't know if a conflict happened but in subs. dashboard the new OC appears with no OC name and just "Close date not set" which is pretty confusing.

## Expected Behavior
The OC in subs dashboard is displayed with proper name and close date.

## Actual Behavior
In some strange cases the OC is displayed only with "Close date not set" in subs dashboard.

## Steps to Reproduce
1. A First OC with subscriptions for a given user we supposed to start at 6:45
2. Exactly at 6:45 I click on "save" for a second OC with the same schedule on it.
3. When looking at subs dashboad the subs for OC1 are created, but not yet for OC2 I have to wait a bit... and finally they appear but with OC displayed as "close date not set"

## Animated Gif/Screenshot
OC2 still as pending:
![screenshot from 2018-03-20 09-26-32](https://user-images.githubusercontent.com/8135376/37643469-f091c89c-2c20-11e8-8c9e-347b1664f589.png)

And a few minutes later:
![screenshot from 2018-03-20 09-27-11](https://user-images.githubusercontent.com/8135376/37643476-f54b0664-2c20-11e8-9a6a-53714146ac89.png)

## Context
I was testing subscriptions for the first time and got stuck when filling in the date...

## Severity
NA, new feature being developped.

## Your Environment
- Version used: 1.11
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by sstead** [comment]
Just making a note that I haven't seen this, perhaps it's something we can close in future if no one else encounters it.

**Comment by myriamboure** [comment]
I'm closing this one as covered by two separate issues more clearly described: https://github.com/openfoodfoundation/openfoodnetwork/issues/2877 and https://github.com/openfoodfoundation/openfoodnetwork/issues/2878
