### ISSUE TITLE
[Subs] Send only one order conf. email to customer for shops that don't allow modifications

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2158]
## Description
I think there is a UX issue with subscriptions for shops who are set up to "don't allow order modification". As a user I receive a confirmation email when the OC opens saying that an order has been made for me. And another one that looks like a duplicate when the OC closes... These two emails make sense if you give the possibility to the customer to modify the order, but not if you don't.

## Expected Behavior
- either we say only shops who allow order modification can create a subscription
- either we only send one confirmation email to the user then the OC opens (or closes), just as if he was making his order himself in a shop that doesn't allow to modify the order afterwards.

## Steps to Reproduce
1. For a shop that is set to "don't allow order modification" (in shop preferences, enterprise menu)
2. Create an order cycle, a schedule linked to that order cycle, and a subscription for any given user.
3. With the customer account, wait for the OC to open: you receive a fist email that tells you an order has been made for you (no possibility to modify, nothing just info).
4. Wait for the OC to close: you receive a second email that tells you that an order has been made for you (looks very much like the first one, only one word changed but it's very confusing and can look like a duplicate.

## Context
I was testing subscriptions for the first time and got stuck when filling in the date...

## Severity
NA, new feature being developped.

## Your Environment
- Version used: 1.11
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
- either don't allow to create subscription for hubs set up do "don't allow changes" (don't think we should do that as basket schemes models might want subs but don't allow modification...)
- either if subs on a "don't allow changes" hub only send one order confirmation email when OC starts (or finishes) (preferably)

**Comment by oeoeaio** [comment]
Hi @myriamboure, the emails are actually sent for different reasons, and while they may look similar they have different content. 
The first email notifies the user that:
1) an order cycle has opened and reminds them what they have subscribed for
2) whether all of their requested items are available 
3) that they can edit/cancel the order (if applicable)

The second email 
1) confirms that payment has been processed (or not if processing failed)
2) that the order has been finalised

I think there is scope for allow user to set preferences about which of these emails they receive, but I am reluctant to not send them by default, even if they do look a bit similar. What do you think?

**Comment by myriamboure** [comment]
Happy to retest again the UX part when we have released the "beta v0" on subs. As a user I was a bit disappointed so that means to me that there is some UX issue. But I'm happy to give it a fresh look after the first release. What is currently happening is ok for beta v0 so I let that in backlog in the project (or we can put it to some "on hold" column if better) for now and we can review later.

**Comment by myriamboure** [comment]
I'm closing this for now as not prioritary, UX is ok to start with, will see with user feedbacks.
