### ISSUE TITLE
Old Tech things to sort out

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2159]
## Description
Just creating an epic to put all the old "tech things that I can't understand" together so that someone with tech knowledge can review and decide what to do with them (icebox / backlog if quick tech debt, etc.)
@enricostano I propose we go through them in our next "issue review" session :-)

**Comment by RachL** [comment]
All issues were closed except 2 tech debt. Removed them so we can close this epic.
