### ISSUE TITLE
[Spree 2 Upgrade] Refactor CreateMailMethod to work on Spree 2.0

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2164]
## Description
We need to refactor the `CreateMailMethod` class for it to work on Spree 2.0, which completely removed `Spree::MailMethod`. When that service was introduced in https://github.com/openfoodfoundation/openfoodnetwork/pull/2148, we were still in Spree 1.3 (sort of...) and so we relied on `Spree::MailMethod`.

## Possible Fix
This service has to write the settings directly to `Spree::Config`. See https://github.com/spree/spree/pull/2643 for reference.

**Comment by elf-pavlik** [comment]
I think this caused issue I mentioned in https://github.com/openfoodfoundation/ofn-install/pull/134#issuecomment-374809707

**Comment by sauloperez** [comment]
This is just a reminder that will have to deal with this once we get to Spree 2.0. So far, the `CreateMailMethod` works as expected, at least when I used it.

**Comment by luisramos0** [comment]
I dont think this is blocked anymore.

**Comment by luisramos0** [comment]
Closed by #2590
