### ISSUE TITLE
Translation issue in success banner after confirming email

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2167]
## Description
When a new user click on confirmation link, he is redirected to login modal but the success message is badly translated, it seems like it's a wrong/missing translation key. The message is "Your account has been confirmed, you are now connected" whereas it should be "Thanks for confirming your email! You can now log in".
The string in transifex is "Thanks for confirming your email! You can now log in" but what is displayed in French is not the translation written in Transifex.

## Expected Behavior
Accurate translated message should be displayed.

## Actual Behavior
Some other message that is not in Transifex appears (don't know where it comes from)

## Steps to Reproduce
See images

## Animated Gif/Screenshot
After cliking on confirmation link the message in French is "Votre compte a été confirmé. Vous êtes maintenant connecté(e)" (equivalent to "Your account has been confirmed, you are now connected")
![screenshot from 2018-03-22 19-18-08](https://user-images.githubusercontent.com/8135376/37790672-8075333a-2e07-11e8-89df-f95746df61e9.png)

In Transifex if I search in "translation text" the text I see in French it doesn't exist. Super strange.
Here is the key that should be used in that translation but is not:
![screenshot from 2018-03-22 19-32-53](https://user-images.githubusercontent.com/8135376/37790936-2bf8eda0-2e08-11e8-8e1b-1ca3de3da803.png)

## Context
I hit that when I clicked from the "private shopfront" page, when I hit the page saying it is reserved to members and register from here.

## Severity
s3

## Your Environment
- Version used: French staging with branch PR2160
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
fix translation key

**Comment by myriamboure** [comment]
@Matt-Yorkley I assigned that to you so that you can check seems there is an issue with translation key for confirmation email success banner.

**Comment by myriamboure** [comment]
Or there is something bugging with Transifex with the recent things done by @mkllnk and @sauloperez on that end... the translation I see in this success banner is not in transifex, strange.

**Comment by mkllnk** [comment]
I just had a quick look at the French locale and the text for `devise.confirmations.confirmed` is missing. But in Transifex it's translated and if I download the version from Transifex, the correct version is in there.

@myriamboure Could it be that you first translated everything to 100% (e.g. machine translation) and then improved the translations? At the moment, we have an issue that only first 100% translated event triggers the translations to be copied to Github. All changes afterwards don't make it into the code until there are new translations available.

**Comment by mkllnk** [comment]
I jumped ahead since I was already looking at it and created a new pull request: https://github.com/openfoodfoundation/openfoodnetwork/pull/2168

I think we need to talk about the Transifex integration again. There should be a better solution.

**Comment by myriamboure** [comment]
I don't remember @mkllnk but if that happened, if I did translate differently the string before and then changed it happened weeks or months ago, and I guess we did update transifex a couple of times since then (there were new translations available that have been merged since then so should have updated the ones I modified if I did modify them?). Anyway I agree with you that the translation process is not really smooth/straightfoward at the moment.

**Comment by myriamboure** [comment]
Ok so apparently fix has been merged, but need to wait next release to test if that is fixed, so when v1.14 will be deployed. Assigning myself on it then.

**Comment by myriamboure** [comment]
I retested on French staging with master branch something after release 1.15 and it is fixed so closing now.
