### ISSUE TITLE
Update email content for manager invitation sign-up

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2171]
## Description
Continuing remaining work from https://github.com/openfoodfoundation/openfoodnetwork/pull/2138#issuecomment-375650719

When an unregistered user is invited as a manager, he receives 2 messages at the same time:
- an account validation message (link to click on to validate email)
- a "you have been invited by Enterprise X to join as manager" email.
The content of the second email is a bit disturbing so propose is to change a bit the English original text:
1- Clarify that the validation email might already have been received and that can't access profile until they validate
2- There is a redundant message : you can contact instance manager (not sure it's something we want also so I won't put that anyway) ad just below "you can review FAQ if you have any question or join the forum to ask your question" > let direct the users to the forum instead of bothering instance managers.

## Expected Behavior
Email content:
You have been invited to manage [Enterprise] on [instance].
**You should have received or will soon receive an email with a confirmation link. You won’t be able to access [enterprise]'s profile until you have confirmed your email.**
**Not sure why you have received this email? Please contact [enterprise contact email] for more information.**
Si tiene dificultades, revise nuestras preguntas frecuentes, navegue el foro o haga una entrada de con tema de 'Soporte' y ¡alguien le ayudará! 

## Actual Behavior
Email content:
You have been invited to manage [Enterprise] on [instance].
**You will receive an email shortly to confirm your registration.
Not sure why you have received this email? Please contact [enterprise contact email] for more information, or you can contact [instance] at [instance email].**
Si tiene dificultades, revise nuestras preguntas frecuentes, navegue el foro o haga una entrada de con tema de 'Soporte' y ¡alguien le ayudará! 

## Steps to Reproduce
1.From any enterprise menu, "users" "add an unregistered user"
2. Check emails you receive as the new user.

## Context
Noticed that while testing PR2138 so we merged that PR but this is remains to be done.

## Severity
s3 not blocking but a bit not user friendly.

## Your Environment
- Version used: branch PR2138 deployed on Katuma staging
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
Change en corresponding entries.

**Comment by myriamboure** [comment]
@sstead @daniellemoorhead @lin-d-hop I'm not native English so if you disagree with my proposed amended content for english email please propose something else :-)

**Comment by sstead** [comment]
I made some little edits to the content and am happy with it, thanks Myriam.

**Comment by myriamboure** [comment]
Cool :-) @Matt-Yorkley can you amend the English text content for the English part of the message then? Thanks:-)
