### ISSUE TITLE
"Price sack" enterprise fee is not working (not being calculated at all)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2173]
## Description
If you set up an enterprise fee using "price sack" calculator, calculations are note happening at all and no fee is charged.
**Example 1:**
![screenshot from 2018-03-23 16-45-32](https://user-images.githubusercontent.com/8135376/37839060-d4aee092-2eb9-11e8-920e-828b81bea700.png)
![screenshot from 2018-03-23 16-45-47](https://user-images.githubusercontent.com/8135376/37839064-d75d710a-2eb9-11e8-81d9-90727b79892d.png)

**Example 2:**
![screenshot from 2018-03-23 16-45-58](https://user-images.githubusercontent.com/8135376/37839076-dbe77acc-2eb9-11e8-9307-9aa86e26a5fc.png)
![screenshot from 2018-03-23 16-46-16](https://user-images.githubusercontent.com/8135376/37839087-df0652e6-2eb9-11e8-83a8-11f649a527b0.png)

## Expected Behavior
Fee should be calculated and displayed in "admin & handling" section.
Formula is:
- if order amount < min amount then cost = normal amount
- if order amount > or = min amount then cost = discount amount

## Actual Behavior
Fee is not calculated and displayed.

## Steps to Reproduce
1. Set up a enterprise fee with "price sack" calculator
2. Create an OC and apply that fee in outgoing
3. Make an order

## Context
I hit that while testing PR2079

## Severity
s3 (there is no workaround but no one complained so I guess no one is using it? Don't know... if it is used it would be s2, not sure so putting 2)

## Your Environment
- Version used: branch PR2079 deployed on UK staging
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
Make sure calculation happens and fees are displayed correctly in cart and checkout.

**Comment by HugsDaniel** [comment]
@myriamboure `order amount` is the quantity of variants ordered or the price ?

**Comment by myriamboure** [comment]
@HugsDaniel I mean with "order amount" the price for the total order.
You can check here it's well explained: https://openfoodnetwork.org/user-guide/producer-set-up-guide/enterprise-fees/

One thing I'm not sure though reading that again... if there are two enterprise fees in the OC like "percent" and "price sack", is price sack calculated on the total price for the products BEFORE or AFTER "percent" fee is taken?
I would say logically that all fees should apply to base product cost (with no other fee applied), but just wanted to precise that in case someone disagree.
