### ISSUE TITLE
Temporary fix to Spree mistranslations

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2187]
## Description

This is a reminder that PR #2178 is a temporary fix to an issue coming from Spree I18n translations. Later upgrades from Spree and Spree I18n may solve the issue, so the fixes may have to be removed.

**Comment by luisramos0** [comment]
Removing the reference to #2109 and moving it to epic #2584 (all the issues blocked by the spree upgrade).

**Comment by sigmundpetersen** [comment]
Is this really linked to #2178 or is it rather #2176?

**Comment by RachL** [comment]
@openfoodfoundation/core-devs do we still need this issue?

**Comment by mkllnk** [comment]
No, we don't actually need any fix here.
