### ISSUE TITLE
Enterprise model: combine ABN and ACN field

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#219]
Enterprises have an ABN or ACN and not both, right?

So we could use only one input field for it and parse the input to distinguish.
- An ABN has 11 digits. The first two are a checksum for the remaining 9. The algorithm is public: http://www.ato.gov.au/Business/Australian-business-number/In-detail/Introduction/Format-of-the-ABN/
- An ACN has 9 digits. It is the predecessor of the ABN. The last digit is a checksum similar to the ABN checksum: http://www.asic.gov.au/asic/asic.nsf/byheadline/Australian+Company+Number+%28ACN%29+Check+Digit?opendocument

**Comment by lin-d-hop** [comment]
Bascially, no one has cared about this for years. #gitcull
