### ISSUE TITLE
Old OC's with no/conflictual dates makes OC's index crash and prevent users from accessing their OCs

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2193]
EDIT: all the description below was in fact connected to conflictual dates. Under resolution in PR2119.
We found a workaround wich is to change dates in database so s3 is ok.

## Description
A user who was running regular order cycles on OFN changed the permalink (url name) of his shop.
After doing that, when he clicks on "order cycle' he can't access anymore any of his order cycles and he sees the new "subscription" layout which other users don't see yet... 
I did another experience: I added another user I manage as a manager of the given hub.
When I log in with that manager in the order cycle list I see the subscription layout but when I try to display his shop OC's nothing happens. If I delete that manager and connect again with that manager account I see again old order cycle full list.
Even worse, even as super admin I can't access anymore this hub's OC...
Creating a new order cycle doesn't change anything, when it is created I can't find it again anywhere even as super admin.

## Expected Behavior
A hub manager can access his past and present order cycles to be able to manage and duplicate them.

## Actual Behavior
When permalink is changed hub can't access anymore his OC.

## Steps to Reproduce
1. As a hub manager change the permalink of the shop (url)
2. Then click on order cycles and see.

## Animated Gif/Screenshot
https://www.useloom.com/share/98c232fd3cf748c8b3009af0756a0dc1 

## Context
The concerned user contacted me yesterday and is super annoyed as he can't manage and see anymore his order cycles.

## Severity
S2. I don't see any workaround, trying to find a way to help that user but have not found yet... Even worse is that even as super admin I can't access anymore this hub's OC... 

## Your Environment
- Version used: v1.12
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
It seems like a conflict connected to the new layout of order cycle page with subscription feature, seems that when shop change names the shop's OC can't be found anymore. Am I right @oeoeaio ?

**Comment by myriamboure** [comment]
@sauloperez @sauloperez I don't know if you had a look at subs but if you are around today and can have a look would be awesome... I'm a bit powerless for that user, apart asking him to create a new enterprise from scratch.

**Comment by daniellemoorhead** [comment]
@myriamboure given the solution discussed on Slack around order cycle dates can this issue now be closed?

**Comment by myriamboure** [comment]
closing as problem solved thanks to Rob :-)

**Comment by myriamboure** [comment]
Oups, actually bug is still here as there is still a little thing to fix in the PR that solves it. Not linked to permaling thought so reopening but changing title.

**Comment by myriamboure** [comment]
closed via https://github.com/openfoodfoundation/openfoodnetwork/pull/2119
