### ISSUE TITLE
Invite button not clickable when Inviting new Manager

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2197]
## Description
When I use the Invite Manager field in Aus production, the box opens, I type the email of the manager I want to invite, but when I click the Invite button nothing happens. It works for super-admin users.

## Expected Behavior
The invite button should become clickable after I enter an email, and after I click it I should see a success/error message.

## Steps to Reproduce

1. Log in as enterprise user (not super admin).
1. Go to the Users tab of a profile you own. 
2. Click the invite manager button and enter an email, click Invite.

## Animated Gif/Screenshot
https://www.useloom.com/share/28d04bfcb06641079936c2f41790cb4c

## Context
I can't add managers.

## Severity
S3

## Your Environment
PC, Chrome.

## Possible fix

The POST request to invite a manager causes a 403 forbidden response. We probably need to tweak authorisations. See `app/models/spree/ability_decorator.rb`. This never worked. The issue was already there in the original feature introduced in 82457d2b632923118ac4aed171272a628ff3ed83.

**Comment by myriamboure** [comment]
As this is part of epic on user email verification (we included the manager invite in it) I suggest we fix that bug properly as part of the epic job. I tested with super-admin users so didn't see that bug while testing, sorry about that (learing). @Matt-Yorkley can you work on it in the coming days?

**Comment by myriamboure** [comment]
@Matt-Yorkley this is pretty important I think and users I waiting for this in part of email confirm thing. Can you fix that quickly please? As a reminder Maikel had reverted your branch so you need to resubmit with the fix. Thank :)

**Comment by sauloperez** [comment]
Amazing `possible fix` :clap::clap:
