### ISSUE TITLE
[Spree 2 Upgrade] Update base_mailer_decorator.rb

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2198]
## Description
Once in Spree 2.0 the API to get the mail settings changes. This needs to be reflected in [app/mailers/spree/base_mailer_decorator.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/mailers/spree/base_mailer_decorator.rb)

See the explanation in: https://github.com/openfoodfoundation/openfoodnetwork/pull/2166

**Comment by luisramos0** [comment]
I dont think this is blocked anymore.

**Comment by luisramos0** [comment]
I may be missing something, but it looks like PR #2589 is all we need here.

**Comment by mkllnk** [comment]
Pull requests for the 2-0-stable branch don't close the associated issues (they would get closed when merged into master). So we have to do that manually.

**Comment by luisramos0** [comment]
I think it was just because PR 2589 was not "connected" to this issue. No?

**Comment by mkllnk** [comment]
Maybe. We have two things here: One is Github detecting text like `closes #100` to auto-closing the issue when the PR is merged into master. The other thing is Zenhub moving issues and PRs together. So if we connect things, it should still work.
