### ISSUE TITLE
Seed info from YAML file; also use YAML for loading sample data?

### ISSUE THREAD

**Issue by weedySeaDragon** [openfoodfoundation/openfoodnetwork#220]
I'd like to have the ability to seed info from a YAML file(s) (or some other text file(s) that can be created/edited by non-programmers).  The YAML files could then be populated as needed by different installations. Specifically, the "suburbs" could be populated differently for AUS, UK, and US installations. (Also, right now the data in suburb_seeds.rb is coupled to the specific database (postgres) syntax.  The data shouldn't be shaped by the database used.) 
This would mean revising some of db/seeds.rb and db/suburb_seeds.rb

Likewise, I'd also like to have the sample data loaded from YAML files.  This would provide greater flexibility (for development as well as testing).  This would mean revising dev.rake.  (I'd likely have it call other methods that would probably live in files in lib/open_food_network.)

I can do the work, then do a pull request.

Thoughts?

**Comment by sauloperez** [comment]
We have bigger problems than this and flexibility adding seed data is not one of them so far.
