### ISSUE TITLE
Can't scroll to see in modals (profiles, longer product descriptions)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2201]
## Description
Users can write long descriptions for products - there is no character limit on the text field. In the shop, if the description is too long, the customer can't scroll down in the product modal the read the full description.

Also, when testing groups I noticed you also can't scroll to see long profiles on maps/groups.

## Expected Behavior
I should be able to scroll down to read full description. Or the user should be limited in how long of a description they write.

## Steps to Reproduce
1. Put a long product description into the text field (>1000 characters)
2. View it in this shop - you'll notice you can't scroll

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/10843056/38537548-a9700984-3cd2-11e8-98cd-b757a16ea692.png)

here's a view of a profile in a group page. I can't see a scroll bar and using pgup or pgdn just scrolls on the map underneath, not the modal.
https://www.useloom.com/share/c5c8fde155224f09a93b065074c1e876

## Context
A user complained about this after writing a long product description.

## Severity
s4

## Your Environment
- Chrome 
PC

## Possible Fix
Either allow for scrolling in the product modal, or limit the characters allowed in a product description so it fits.

**Comment by jdg006** [comment]
I'd be happy to try and take this issue on. Let me know which fix you would rather (the limit on characters or the ability to scroll) and i'll get right to it.

**Comment by myriamboure** [comment]
Hi @jdg006 and welcome in the OFN community! Great that you want to help on that :-) I'm not tech but on a UX prospective I would rather choose the ability to scroll if description is too long. Also for mobile responsiveness that seems like the best option to me. If anyone disagree please tell :)

**Comment by sauloperez** [comment]
Looks like the easiest to implement as well.

**Comment by myriamboure** [comment]
Please @kristinalim go on, as we didn't get any answer from @jdg006 since April so it's awesome if you can take it :-)
