### ISSUE TITLE
Time on datepickers on ordercycles not working and sporadically changing

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#2202]
Time functionality on the datepickers in the order cycle pages are not rendering correctly and change upon clicks

## Description
Selecting time on the "datepickers" function on the order cycle page do not work. As you click on a date the time changes automatically. If you try to enter a time using the keyboard when clicking on the hour or minute box, it does not pull through what you tyope

## Expected Behavior
When you click on the time you should either see numbers to enter the time, or be able to type in numbers manually using the keyboard.

## Actual Behavior
When you click on different dates you'll see in the video that the time starts to change automatically following no clear pattern. 
When I try to click on the hour/minute box to type numbers in, any typing is not pulled through into the boxes

## Steps to Reproduce
1. go to order cycles and select a test cycle to use
2. click on a datepicker
3. select a date
4. then click on hour
5. select a date again
6. see the time change
7. click on the hour box, try enter text - it doesn't pull through

## Animated Gif/Screenshot
http://recordit.co/keWUlXWCyr

## Context
Users

## Severity
High (add up from Myriam: I  suggest to put S3 on it there is a workaround, it's affecting lots of users but they can manually type the right time in the field)

## Your Environment
* Version used: 
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): desktop, windows 10
 (user raised was on Firefox and Chromium on Linux)

## Possible Fix
Allow users to at least type a time and stop the time changing when selecting dates.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Time Pickers not working on date picker order cycle page](https://trello.com/c/7JOaifgn/174-time-pickers-not-working-on-date-picker-order-cycle-page)

**Comment by pacodelaluna** [comment]
I am working on this ticket. I can see 2 options:
1. To update the current lib and to use selects for time selection (instead of sliders which are broken due to Jquery UI issue)
2. To integrate a new datetimepicker lib such as [https://flatpickr.js.org/](https://flatpickr.js.org/)

First one can be done in minutes, second one in hours.

**Comment by sauloperez** [comment]
I'd go with 1 for now. There might be dragons in there so I'd be conservative.

**Comment by pacodelaluna** [comment]
About this first option, the date time picker will look like this then:
![screen shot 2019-02-11 at 18 18 44](https://user-images.githubusercontent.com/27745/52580903-a0ee0100-2e29-11e9-927c-ddd27fd7348e.png)

**Comment by sauloperez** [comment]
Looks way better!
