### ISSUE TITLE
Spree's new order lock feature

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2206]
## Description
While digging deeper on the Spree 2.0 changes and trying to boot the app we found out that https://github.com/spree/spree/commit/45eabed81 introduced a `lock` option on [#current_order](https://github.com/spree/spree/commit/45eabed81#diff-4c76cfd37035d99f52b5a54bbeef4eaaR16) and [#load_order](https://github.com/spree/spree/commit/45eabed81#diff-10992068b70df9a93b07ec08575d29a6R93), which apparently might allow having an order at a time to avoid conflicts between orders.

This `lock` option uses the Rails `lock` method. See details in https://apidock.com/rails/v3.2.13/ActiveRecord/Locking/Pessimistic. https://stackoverflow.com/a/13070147 might also be relevant to the topic.

We need to spend some time to understand if that is something we need to aware of or we can simply forget about it.

**Comment by mkllnk** [comment]
### Impact of the locking feature

First of all: https://github.com/spree/spree/commit/45eabed81 is not part of 2-0-4-stable. We don't need to deal with this now. But I looked into it anyway.

Pessimistic locking of an order is optional and not used by default. All our calls to `current_order` won't use locking and we retain our old behaviour. That part is good.

Spree uses the lock at several points. The introducing commit has these:

- `Spree::Api::CheckoutsController` loads `@order` with a lock on `next`, `advance` and `update`. We don't use this controller.
- `Spree::Api::OrdersController` loads `@order` with a lock on `update`. We don't use this controller.
- `Spree::CheckoutController` loads `@order` with a lock. The method to do that changes names from `load_order` to `load_order_with_lock`. *We override this method and need to change it!*
- `Spree::OrdersController` loads `@order` with a lock on update. This is in use without modification.

There may be more usage in later commits, but without a target branch, I can't search for these usages.

### Understanding the locking feature

Locking is usally done within a transaction. Fictional example from the documentation:
```rb
Account.transaction do
  # select * from accounts where name = 'shugo' limit 1 for update
  shugo = Account.where("name = 'shugo'").lock(true).first
  yuko = Account.where("name = 'yuko'").lock(true).first
  shugo.balance -= 100
  shugo.save!
  yuko.balance += 100
  yuko.save!
end
```

If another process would run this at the same time, Postgres lets the second process wait at the select statement until the first process is done. That sounds really cool.

However, the Spree code doesn't use a transaction explicitly. So within a controller, we basically do:

```rb
def update
  @order = Spree::Order.lock(lock).find_by!(number: params[:id])
  @order.update_attributes(order_params)
end
```

I think that the lock is obtained on the default transaction, the current database connection. I don't know when that connection is closed and the lock is released. I tested with two processes that I can modify the cart from both. So the lock must be released at the end of the request, but I can't see any hint of that in the log file.

Anyway, I think that pessimistic locking is useful in the actions Spree is using it in. I'm not sure if their implementation works as desired, but it doesn't seem to do any harm. I've read a few articles that recommend using transactions and locks only in model classes, not in controllers. So I think we can mostly ignore Spree's change for now. We do need to change our CheckoutController though to override the renamed method.

**Comment by myriamboure** [comment]
Wooooo, it means we will be able to lock orders when the transaction is made! This make so much sense, that is something we need so much, great to see Spree is going in that direction. Just some context: the idea is that an order will be editabe until a delivery note (meaning products has been deivered so original order can't be modified anymore) or an invoice (meaning transactions officially happened) is created. I don't know the tech part but the business logic should be this IMO and from what we discussed yesterday.

**Comment by mkllnk** [comment]
Sorry Myriam, that's not what this is about. This locking is on database level and lasts only for milliseconds. If you are clicking very fast or you have multiple tabs open and try to order in both of them at the same time, this new locking should prevent any inconsistent data resulting from this.
