### ISSUE TITLE
Enterprise managers can access the page of the report they want to generate

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2210]
## What is the problem we are solving 
Some enterprise users, when clicking on “reports” and then clicking on a specific report they would like to access, don’t even manage to reach the given report page as they experience a timeout (too many data loaded).
This is because all data are loaded with some default filtering options (like start date = first day of the month) but for some users even with those pre-defined filters that makes too many data so they experience timeout.

## Success factors = expected outcome 
Enterprise users when clicking on "reports" then clicking on a given report can access the page of this given report.  

## Metric
People who are on a broadband network can click on any report from "report" menu and access the given report page without experiencing timeout.

## Useful information for inception
**Actual behavior:** Enterprise users when clicking on "reports" then clicking on a given report are redirected to report page but by default there is some pre-defined filters and the system automatically tries to load the corresponding data. As a consequence, some users who have many data even with those default filtering options experience timeout and so the page doesn't even open.

## Link to the "Icebox" item in Discourse
https://community.openfoodnetwork.org/t/make-sure-all-enterprise-managers-can-access-reports-filtering-menu/1282

## First feature candidate to be implemented
"remove default filtering and don't load the report before filtering options are set"
WARNING: this will not solved the performance issue experienced by users who try to generate a report with one year data for instance. Should only solve first bit: they manage to go on the given report page.

**Comment by myriamboure** [comment]
@mkllnk this epic is for you :-) There are two stories, and we suggested that @RachL has a quick UX work on it (should be little things, but  like for instance display a message inviting the user to use filters, and telling that if long period might take more time to load... things like that) before you take the stories and implement them. @RachL can you plan that in the coming days?

**Comment by myriamboure** [comment]
Ok so it seems that epic is now done as al the three issues in it have been done! @daniellemoorhead in our processes are we supposed now to have the last master staged to retest the whole feature and review if the original problem have been solved before we can consider the feature as done? Or as long as all the issues in the epic are done we just consider it as done?

**Comment by daniellemoorhead** [comment]
>in our processes are we supposed now to have the last master staged to retest the whole feature and review if the original problem have been solved before we can consider the feature as done? Or as long as all the issues in the epic are done we just consider it as done?

@myriamboure have we achieved this?

![screen shot 2018-06-22 at 1 40 39 pm](https://user-images.githubusercontent.com/10949052/41756835-e87b2b9e-7621-11e8-9f2e-f4dac8bb8b31.png)

If yes, then we can safely say we have achieved what we set out to do and we can consider this done 😄

**Comment by myriamboure** [comment]
I need to wait for the new release to be done so that I can test and see if we achieved the expected outcome and metrics @daniellemoorhead I can't tell before I can test for real ;-)

**Comment by sauloperez** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v1.16.0 is already live. You just need to deploy it in the french instance.

**Comment by myriamboure** [comment]
We can now access the pages of all reports, so the scope of that epic is done, we can close. Reports are still not working and bugging a lot but we will need to prioritize some report overhaul later on to tackle it.
