### ISSUE TITLE
Reports: Don't load any data

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2211]
## Description
**- As a:** enterprise manager

**- On page:** /admin/reports when clicking on any link from that page
![screenshot from 2018-04-12 19-35-30](https://user-images.githubusercontent.com/8135376/38693949-b68cd540-3e88-11e8-8779-c2ef3ff83b8a.png)

**- I want to be able to do:** access the page with no data loaded (pre-defined existing filters options are still there)

## Acceptance criteria
1- When the user click on any of the links from the /admin/reports, the page opens with the filter and instead of the data a message is shown saying "Please select filters in order to access your data".
![untitled presentation](https://user-images.githubusercontent.com/8135376/38925992-792067c6-4301-11e8-8773-39616dacd528.jpg)

2- Once the user applies filters and click on "search", the page reloads, but does not open a new window (it is already the case).

**Comment by myriamboure** [comment]
@RachL do you think you can work on UX for this in priority so that @mkllnk can start implementing it?

**Comment by RachL** [comment]
@myriamboure @mkllnk I think for the UX here 3 points are relevant : 

1. When the user click on any of the links from the /admin/reports, the page opens with the filter and instead of the data a message is shown saying "Please select filters in order to access your data".
2. If the filters selected require a large amount of data that would prevent the page to be loaded, a message should appear asking the user to select less filter (e.g. : select a less large time range)
3. Once the user applies filters, the page reloads, but does not open a new window (I think it is already the case)

For number 2, I guess we need a cap of number of data a user can ask at once.

What do you think ?

**Comment by sauloperez** [comment]
suggestion 2 is very hard to implement as there's no deterministic way to know how large the amount of data is to prevent the page to be loaded. I don't know any way to weight how much data the DB will process.

I agree with you on setting a totally arbitrary threshold which we think is reasonable for both the user and the current performance of all instances today (if that is what you meant).

https://johnnunemaker.com/database-performance-simplified/ is an awesome must-read article on this topic, particularly the `Limit Everything` section, which involves UX a bit.

**Comment by RachL** [comment]
@sauloperez yes that what I meant, I don't think we will be able to fix a good threshold other than arbitrary for the moment. But at least it should prevent the user from having an indefinite loader. Thx for the link !

**Comment by myriamboure** [comment]
Agree with your suggestion @RachL !
Although I would suggest to open a new issue for point 2 because we need to investigate and test given current peformance what limit is reasonable and list them to be able to implement them, like for instance:
- if you ask more than one month data you are required to change dates so that it's no more than one month
- if you ask more than one OC at a time same.
- etc.
So we can have only in this issue "don't load any data" which includes the message displayed in stead invite users to apply filters to load data.
Do you agree? If yes please create a third issue for this epic and we can treat it separatly.

**Comment by myriamboure** [comment]
@RachL I added the mockups based on your suggestion. Left aside the data cap for the moment, I let you create another issue and link it to the epic. @mkllnk I put that story in dev ready for you to pick-up :-)

**Comment by RachL** [comment]
@myriamboure thx ! Sorry about that I thought I had uploaded my mockup. Dunno what happened...
