### ISSUE TITLE
[Spree Upgrade] Checkout

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2216]
## Description

We have a number of customizations on top of Spree's checkout process to implement the collapsed customer-facing checkout. See:

https://github.com/openfoodfoundation/openfoodnetwork/blob/514ad5d898d0ba8c2e8a877e20f930fdbf418aa0/app/models/spree/order_decorator.rb#L29-L46

It's very likely that we'll have to touch the checkout while working on the [other Spree 2.0 epics](https://github.com/openfoodfoundation/openfoodnetwork/issues/2109), but it deserves an investigation on its own and perhaps the changes on the checkout will block some of those other issues.

**Comment by sigmundpetersen** [comment]
Can we close? 🎉 @luisramos0 @sauloperez Or are there more stuff to be put into this Epic?

**Comment by luisramos0** [comment]
yeah, as #2520 was moved to non-core, I think we can close this.
Checkout is working fine on v2 and the checkout shipping method id is handled in #2683 (part of the multi shipment epic).
