### ISSUE TITLE
Spree 2.0 Upgrade: Boot the app 

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2217]
## Description

The further we go with the spree upgrade the more issues we find that can't be solved by being compatible with the `master` branch. We need to continue the development in a different branch so that we can work on both, OFN's development and the Spree upgrade, independently.

We already created said branch as https://github.com/openfoodfoundation/openfoodnetwork/tree/2-0-stable and so all PRs related to the upgrade must be merged into it. Some day, when we're finally done will merge `2-0-stable` into `master`.

## What needs to be done?

To make that branch run on Spree 2.0 we need to:

* Update OFN's dependencies so that they are compatible with Spree 2.0.
* Fix any failures due to Spree changes required for Rails to start successfully.

**Comment by sauloperez** [comment]
```
$ b rails s
=> Booting Unicorn
=> Rails 3.2.21 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[SKYLIGHT] [1.6.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
(eval):1: warning: encountered \r in middle of line, treated as a mere space
listening on addr=0.0.0.0:3000 fd=16
worker=0 spawning...
master process ready
worker=0 spawned pid=9588
worker=0 ready
```

We just need #2284 to be merged!

![](https://media.giphy.com/media/d3MKSNzLtyTHE6OY/giphy.gif)

**Comment by kirstenalarsen** [comment]
omg really?! this is exciting . .

**Comment by sauloperez** [comment]
Yes it is! Things are slowly moving forward!

**Comment by sauloperez** [comment]
Done!

```
➜  openfoodnetwork 2-0-stable ✗ brs
=> Booting Unicorn
=> Rails 3.2.21 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[SKYLIGHT] [1.6.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
(eval):1: warning: encountered \r in middle of line, treated as a mere space
listening on addr=0.0.0.0:3000 fd=16
worker=0 spawning...
master process ready
worker=0 spawned pid=12582
worker=0 ready
```

![](https://media.giphy.com/media/mp1JYId8n0t3y/giphy.gif)

**Comment by kirstenalarsen** [comment]
your gifs have just made us all laugh a lot. and YAYAY!!
