### ISSUE TITLE
Investigate current customizations on Spree's checkout

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2218]
## Description

Before thinking about implementing our checkout onto Spree 2.0 we first need to have a clear picture of all the customizations we did there and where are they in the codebase.

Once we have that clear understanding we'll be able to foresee how these customizations impact the upgrade

## Expectations

We should carefully document these findings as a wiki page so that we don't miss it.

**Comment by sauloperez** [comment]
who should work on this @enricostano ?

**Comment by enricostano** [comment]
@mkllnk @Matt-Yorkley perhaps? Any volunteer? I'm sure also @oeoeaio has some insight nobody else knows :smiley:

**Comment by oeoeaio** [comment]
As far as I know the majority of the customisation we have done is in CheckoutController#update (we actually created our own CheckoutController which inherits from Spree::CheckoutController, I'm not sure why we did that). We have hacked the Spree::Order model A LOT, and I'm sure some of that has an influence on the checkout, but don't think we've altered the actual state machine all that much if at all.

**Comment by enricostano** [comment]
Probably good outcomes of this task would be:
 - documentation of all the possible states an order must go through
 - documentation of all the "callbacks"(?) we call transitioning from one state to another

**Comment by sauloperez** [comment]
What I can tell is that we overrode the checkout flow as shown below to add couple things on top:

https://github.com/openfoodfoundation/openfoodnetwork/blob/3fc49d59354f1c4fe6452c6cc445469d198fb7a4/app/models/spree/order_decorator.rb#L29-L46

**Comment by mkllnk** [comment]
Okay, I will put my findings in this post first, using it as a wiki and then moving that to the wiki when ready.

#### WIP

Nothing to see yet. ;-)

**Comment by sauloperez** [comment]
Wow @mkllnk that's more than I expected! can you please add a wiki page and reference it from https://github.com/openfoodfoundation/openfoodnetwork/wiki/Spree-Upgrade-Themes ? that sounds like a good place to have, agree?

**Comment by mkllnk** [comment]
@sauloperez I created individual pages for the upgrade themes to keep it a bit tidier. I think we need to create a task list from all this, possibly convert it into an epic.

**Comment by sauloperez** [comment]
Yep, I think this deserves some sort of inception to then fit small isolated issues into https://github.com/openfoodfoundation/openfoodnetwork/issues/2216

**Comment by luisramos0** [comment]
I guess this investigation is complete, right @mkllnk ? Can we close this issue?

**Comment by mkllnk** [comment]
Yes, I think we can close it.

I still have a not about creating an issue for `payment_attributes`, but looking at the code now, I can't see any reason for that. Was that the thing that we thought `payment_attributes` was removed, but they removed only a duplicate. It's still there and works the same as before.
