### ISSUE TITLE
[Spree Upgrade][Paypal] Investigate better_spree_paypal_express's spree-upgrade-intermediate branch

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2225]
## Description

We need to investigate what the branch mentioned below implements:

https://github.com/openfoodfoundation/openfoodnetwork/blob/1abfe2ab8c57a614635edf48c48270e430ef6afd/Gemfile#L18-L21

and see what's the impact on the Spree upgrade.

**Comment by sauloperez** [comment]
This issue does not prevent us from booting the app so assigning it to the main epic instead.

**Comment by HugsDaniel** [comment]
I'm taking this one.

**Comment by daniellemoorhead** [comment]
Heya @HugsDaniel this has been sitting in Dev for a couple of weeks now with now movement. Is it still in progress, or shall we move it back to Dev Ready till you're able to continue work?

#tidyingupthedeliverytrain

![cleanup](https://user-images.githubusercontent.com/10949052/40818173-31c62964-6599-11e8-9fe1-3d50e37c3ee1.gif)

**Comment by HugsDaniel** [comment]
Hey ! Sorry I have a little trouble understanding what it does exactly, but I'm on it.

**Comment by HugsDaniel** [comment]
So I compared `openfoodfoundation/better_spree_paypal_express@spree-upgrade-intermediate` with `spree-contrib/better_spree_paypal_express@master`.

It appears that a lot of commits fix issues from `spree-contrib` and update dependencies (`paypal-sdk-merchant`, `spree_core`...).
Most of the commits though just add customizations to `spree-contrib/better_spree_paypal_express`, such as password type, support for pg and sqlite3, adding page preferences, redirections, language support and refactor of JS functions... It doesn't seem that it has been submitted to spree-contrib.

These fixes and customizations don't seem to be implemented in latest version of `spree-contrib/better_spree_paypal_express`.

Most of the commits come from [@radar](https://github.com/radar) and the last ones from @mkllnk and @RohanM. Want to add something ? @sauloperez any thoughts ?

**Comment by sauloperez** [comment]
So, looks like it's become a gem of our own and will ever hardly go back to the one from spree_contrib. Am I right? If so, I would just fork and publish it as a regular ruby gem of our own and apply the same best practices we agreed on in the [upgrade catch-up](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Team-catch-ups--%F0%9F%92%AC#notes--agreement) (CI, code review, etc.).

What about changes related to Spree 2.0.4? Are there any that we should take into account?

**Comment by HugsDaniel** [comment]
@sauloperez do you want it published as a gem ? Wouldn't it be more consistent to try to get rid of the fork as we do with Spree ?

`spree-contrib/better_spree_paypal_express` uses `spree_core v2.0.3` btw, seems pretty close to what we want to achieve.

**Comment by sauloperez** [comment]
> Wouldn't it be more consistent to try to get rid of the fork as we do with Spree ?

That's what I dream of but, is it feasible?

> spree-contrib/better_spree_paypal_express uses spree_core v2.0.3 btw, seems pretty close to what we want to achieve.

We're using 2.0.4 so it shouldn't be a problem, so the question is what to do with our patches.

**Comment by HugsDaniel** [comment]
Maybe submit them to spree-contrib ? How quick do you think they can merge them, is they're willing to do it ? We could use our fork as a gem until they do, and they switch to spree-contrib's.

**Comment by sauloperez** [comment]
> Maybe submit them to spree-contrib?

yes, we should

> How quick do you think they can merge them, if they're willing to do it ?

We need to check their activity in the repo to tell

> We could use our fork as a gem until they do, and then switch to spree-contrib's.

If they are willing to accept the PR I wouldn't reach for a gem. I would reach for that just if they don't accept any more PRs or release new versions.

**Comment by sigmundpetersen** [comment]
Any conclusion on this one @sauloperez @HugsDaniel @mkllnk ?

**Comment by luisramos0** [comment]
Looks like no conclusion has been achieved here yet.

I have moved this to spree's upgrade non-core epic. In terms of spree upgrade, there will be an issue "fix paypal integration" that can be the result of this spike.

I think there are two different topic here:
1 - make what we have work with spree 2-0-4
2 - the future of this dependency
I think we should clearly separate these two things.

**Comment by mkllnk** [comment]
I've done this investigation when doing https://github.com/openfoodfoundation/openfoodnetwork/pull/3380. We have only two commits on top of Spree code

- Pass customer email and phone number to PayPal (Rohan)
- Change type of password from string to password (Maikel)

They are tiny code changes that have not been sent to upstream, but could be useful there as well. I think we should open pull requests.

This investigation is done, closing.

**Comment by sauloperez** [comment]
Awesome @mkllnk that's the best solution, which we should have done in the first place.
