### ISSUE TITLE
Build a prototype to validate the new data model

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2227]
## Description
**- As a:** enterprise manager

**- On page:** in an external prototype based on the data model resulted from inception session

**- I want to be able to do:** create my own version of a given product and keep traceability of product origin in my shopfront.

## Acceptance criteria
- In the prototype whatever the version of product I create (split, aggregate, etc.) I am able to create it and keep traceability of origin)

**Comment by myriamboure** [comment]
Not sure who will work on it so just putting you three on this "prototype" thing and you can see how you want to split the work? In term of priority with Spree upgrade, how do we want to handle this? Do you need that understanding for Spree upgrade? Else I guess this should come after Spree upgrade, or should be assigned to someone not working on Spree upgrade if we want to paralelize.

**Comment by sauloperez** [comment]
To me, this should come after Spree upgrade. I don't think we have the resources to work on these two things at the same time plus butfixing and current feature development.

**Comment by sigmundpetersen** [comment]
> butfixing 

Hope everything is going well with this @sauloperez . A nice weekend to you 👋 :bowtie:

**Comment by sigmundpetersen** [comment]
This is handled through Discourse for now
