### ISSUE TITLE
Enable products chain traceability

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2228]
## What is the problem we are solving 
- Mary and Shannon need to be able to make and sell their own version of Fred’s product, without loosing the product origin information
- Fred needs to be able to deny that he supplies a given product to a given hub (if he didn’t create the product himself)
- Mary and Shannon need to be able to create Fred’s products on his behalf in order to sell their own version of it in their shop
- The model needs to enable stocks to be updated consistently along the chain
Today our data model is not adapted to cover those cases. 

## Success factors = expected outcome 
- Mary and Shannon can create and sell their own version of Fred's product (whether or not Fred is managing his catalog on OFN) without friction and reflect the information of the product origin in their shop.
- Fred can deny a false product origin.

## Metric
All the cases we could think about of "derivated products" created by Agents can be created on OFN and transparency on traceability/origin is ensured in the shopfront.

## Useful information for inception
Here are the results from the first inception session: https://community.openfoodnetwork.org/t/modalization-session-product-chain-data-model/1285

## Link to the "Icebox" item in Discourse
https://community.openfoodnetwork.org/t/enable-product-chain-tracking-hubs-variants-creation/1152

## First feature candidate to be implemented
The first feature candidate is to build a prototype to test the new data model that will allow all the above and enable that product chain traceability. Other stories will follow.

**Comment by myriamboure** [comment]
I think the first issue is there and somehow ready to be taken so I guess we can leave it in feature backlog... not sure we will prioritize as it seems other things will go first, but it is in the column.

**Comment by lin-d-hop** [comment]
Feels ambitious that this is a github epic ;-)
#gitcull
