### ISSUE TITLE
Integrate Coveralls to show code coverage

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#223]
https://coveralls.io/ - be good to add a badge to README

**Comment by sigmundpetersen** [comment]
Hey @luisramos0 @sauloperez is this outdated? Are we using SimpleCov for this?

**Comment by sauloperez** [comment]
We're using SimpleCov for development but as I mentioned in #2889 we could use CodeClimate to check it on all PRs. I think we can close this one and have #2889 only.

**Comment by sigmundpetersen** [comment]
Closing in favour of potential use of CodeClimate.
