### ISSUE TITLE
Investigate consequences of Spree using Decorators gem

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2234]
## Description

I just found out that Spree switched to [decorators gem](https://github.com/parndt/decorators) in [cd471bffa](https://github.com/spree/spree/commit/cd471bffa). We need to understand what consequences this has for OFN. Does this change the way our decorators should be implemented? If so, how?

EDIT [c31e3ce24](https://github.com/spree/spree/commit/c31e3ce24) later reverts these changes but we still need to investigate.

**Comment by sauloperez** [comment]
This issue does not prevent us from booting the app so assigning it to the main epic instead until we find a better home for it.

**Comment by HugsDaniel** [comment]
The main difference introduced with https://github.com/spree/spree/commit/cd471bffa  is the subdirectory convention. With this decorators gem, all the decorators must follow this naming convention :
`app/decorators/<at least one subdirectory>/something_decorator.rb`.
For example, it would be something like :
`app/decorators/controllers/pages_controller_decorator.rb`.

It changes the way we implement ours, as decorators are named as following :
`app/<subdirectory>/spree/something_decorator.rb`
For example, for checkout controller we have : 
`app/controllers/spree/checkout_controller_decorator.rb`

I believe with the decorators gem we would have to do something like : 
`app/decorators/controllers/spree/checkout_controller_decorator.rb`

**Comment by sauloperez** [comment]
We can close it or is there something else you want to check?

**Comment by sauloperez** [comment]
Apparently, this change never got merged back :point_right: https://github.com/spree/spree/pull/2414#issuecomment-20656808

**Comment by mkllnk** [comment]
Okay, I just looked into this myself to get familiar with the issues. Since the commit is reverted within our version of Spree already (2.0.4), it doesn't have any effect to our code. And as you said, they never merged it later on, so we don't need to worry about it at all. I think we can close this.

**Comment by sauloperez** [comment]
thanks @mkllnk
