### ISSUE TITLE
Update redirect URL when resending email confirmation

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#2237]
## Description

When sending email confirmations, the page the user is on gets stored so they can be redirected to the page they came from after clicking the validation link. This does not get updated when a confirmation email is re-sent.

## Expected Behavior

Resending email confirmations should update the return URL.

## Actual Behaviour

The return URL stays the same as it was when the user initially signed up.

## Steps to Reproduce
1. Sign up and receive confirmation email
2. Click resend email from a different page

## Context

Clicking validation links form re-sent confirmation emails.

**Comment by Matt-Yorkley** [comment]
@myriamboure After working on #2186 I realised I had to solve it at the same time as this issue, so they are both covered now in PR #2238.

**Comment by myriamboure** [comment]
Ok, cool, so @Matt-Yorkley is the modification you did in #2186 also working for other cases when users click on "resend confirmation" link? Does it redirect them to later page in all cases or just the reset password case? Thanks for the precision.
Ideally we would like to try to have one PR = one issue, but let's move forward and keep that in mind for next time ;-)

**Comment by Matt-Yorkley** [comment]
There's 2 places with the reset password message, and they should both now redirect to the latest page.
