### ISSUE TITLE
Integrate CodeClimate to check code quality

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#224]
http://docs.codeclimate.com/

Tools like this and Coveralls, as well as the Travis build, would be very useful if more people are starting to contribute to the project.

**Comment by mkllnk** [comment]
Since Codeclimate is enforcing styles on pull requests, I found it quite useful to install rubocop locally. I looked for an integration via a `pre-commit` hook, but I'm not really happy with it. There is overcommit which takes over your whole git hook logic. And by default, it warns you about some old offences as well, not only in changed lines. I looked around and couldn't find a script that ignores old offences.

Just as a dirty workaround, I wrote a little script that enforces only that the number of offences is not increasing. https://gist.github.com/mkllnk/3ee2886439c893fd57fe

It still needs two seconds to run when you commit. But that's better than three and a half seconds needed by overcommit and better than looking at Codeclimate and amending my last commit.

**Comment by pmackay** [comment]
I’m not sure what you mean by overcommit? Do you have a link that explains a bit more?

Good idea just checking old files. The recommendation is that when editing files we should be fixing issues in them, even if not related to the current dev task - what do you think about that?

**Comment by mkllnk** [comment]
https://github.com/brigade/overcommit

> The recommendation is that when editing files we should be fixing issues in them, even if not related to the current dev task - what do you think about that?

I think it depends on how many issues there are and how much of the file you change. Reviewing a pull request should stay simple without too much noise from fixing unrelated issues. I try to weigh up between readability of code, readability of the commits and fixing issues. And sometimes you try to fix something and accidentally break it, even if it's just a typo or you thought that you could simplify something.
So, if it's a large file with a lot of issues, I sometimes just fix the issues within the touched methods.

Do you think we should always fix all issues? The pre-commit hook for that would be a lot simpler. :-)

**Comment by pmackay** [comment]
I do agree with you. But then Thoughtbot suggest, dont [fix all the issues separately](https://github.com/thoughtbot/guides#guides) and see last [FAQ here](https://houndci.com/faq):

> Don't rewrite existing code to follow this guide.

But if we dont do that, and we dont fix unrelated issues in files we're changing, I struggle to see how issues get fixed! Agree it would be awesome to get to something more like 0 errors. 

I wondered about stripping down the number of issues that are reported against and then fixing the high level errors/warnings. Open to ideas though.

**Comment by mkllnk** [comment]
It depends on the severity of the issue as well. For example, when I activated Codeclimate for my fork of openfoodnetwork, it reported that the version of nokogiri we were using has a vulnerability. That is something to act on straight away.
If I need to understand confusing code to solve my task, I may rewrite that code after I understood it. When someone else will come back to that file, it will hopefully be easier to understand.
Codeclimate lists five hotspots, files that are rated with F. I think it would be worth addressing these issues without any other reason.

In total, we are doing quite well. 3.76 out of 4, that's a good rating. And if there are readability issues in files we rarely look at, it doesn't matter. The files we touch frequently, will get fixed over time. That's important.

**Comment by pmackay** [comment]
Is it worth:

* a separate issue for fixing the F rated stuff?
* adding some docs in wiki about use of CC, including a link to your Gist?

**Comment by mkllnk** [comment]
> a separate issue for fixing the F rated stuff?

Yes, you can do that from CC, I think. There is a Create Issue button.

> adding some docs in wiki about use of CC, including a link to your Gist?

Contributing.md would be a good place. I would recommend to install rubocop, take the pre-commit.sample hook and add the gist content at the bottom.
