### ISSUE TITLE
[Subscriptions] If I have no future OCs in a schedule, I can't edit subscriptions due to product unavailable error

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2243]
## Description
Subscriptions have been designed with a control in place which restricts which products can be added to a subscription. The way this works currently is that you can _only_ add a product to a subscription _if_ that product is sitting in a current or future OC that is within the schedule that the subscription is applied to.

If I try to edit or create a susbcription when there are no future OCs setup, I can't really add any products to a subscripton and I get error messages. 

The logic of this control was initially designed in the case that customers were creating their subs. It would prevent them from adding rare items to their subs, and maximise the chances that items in their sub would be available.  

However, currently customers cannot setup subs. Shops setup sub, so the shop manager has the power to say 'no I won't create a subscription for peaches because they won't be in season for the next 10 months'. Thus this control is more of a pain than an asset. Also we have in place great messaging for situations where an item in a sub is not in stock. The customer is told 'sorry some items in your sub are not avaialble'  

## Expected Behavior
As a shop I want full control over which items go in subs. I expect that if I have the power to put a product in my OCs, I have permission to put them in a sub. I don't anticipate that I need future OCs before I can add items to subs. 

## Actual Behavior
I can't make any changes to a subscription or create one because I don't have future OCs setup.

## Steps to Reproduce
1. Create a valid subscription (with a schedule, OC and products that are available)
2. Run that OC, and have the subscription triggered, then close the OC.
3. Now, when there is no upcoming OCs for the schedule try to edit a subscription that's subscribed to the schedule. I found that i couldn't change things. You'll also find if you try to create a sub that you can't because no items are available.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/10843056/39105983-37276ba4-46fc-11e8-94e8-03d8e961ae9a.png)

## Context
A shop may have monthly subscriptions. Thus they may have a period between OCs where there is no future OC for the subscription. During this time they'll encounter this error if they try to change any subscription details (dates, shipping/payment methods, customer address etc).

## Severity
s3

##suggested fix
Allow subscriptions to contain any products which the shop is able to put in their OC. Remove restrictions currently in place.

## Your Environment
Chrome, PC, Staging1

**Comment by daniellemoorhead** [comment]
Make it a warning @oeoeaio and then test this when it's out for use.

**Comment by sstead** [comment]
Just checked and this is still oustanding

**Comment by sstead** [comment]
@oeoeaio as just discussed, lets either put a warning in place, or just have no restriction on which items can be added to a sub (anything that can be stocked in their shop can be put in a sub).

**Comment by daniellemoorhead** [comment]
@kristinalim we're going to add this final issue to the subscription beta functionality. @sstead is right now rewriting it to be clearer in terms of what needs to be built (which is the removing the restriction @oeoeaio put in place). Have a chat to @sstead or @mkllnk if it isn't clear what needs to be done 😃

**Comment by daniellemoorhead** [comment]
@kristinalim just one more note - if you think this is going to take more than a 2-3 of hours to get to code review then can you let me know?

**Comment by kristinalim** [comment]
I think I have sufficient understanding of how subscriptions work now to get that in quickly enough. Is this the most urgent task for me right now?

**Comment by kristinalim** [comment]
By the way, yes, I'm thinking around 3 hours for removing the restriction and changing it to warn the user instead.

**Comment by daniellemoorhead** [comment]
>Is this the most urgent task for me right now?

I think it's the most important next thing you pick up, but less than anything you already have in the pipe and are working on right now.

**Comment by daniellemoorhead** [comment]
Hey @kristinalim 👋 
This has been sitting in the In Dev column with no progress since late September. I'm assuming you're not working on it at the moment so I feel like we should close the PR and move this issue back to Dev Ready.

@myriamboure do you agree? Is this something that is a bigger priority than the other work @kristinalim has on her plate at the moment?

**Comment by myriamboure** [comment]
It is the most annoying issue in subscription, but @kristinalim is working on another S2 issue which is more prioritary.... so let's queue it. We need to find some dev to work on subs anyway as there are around 10 remaining issues to fix before release (which I saw you did already in Aus ;-)) So if we close I would leave the issue pretty high in the dev ready column.
