### ISSUE TITLE
Delete old sessions from the database

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2247]
We are storing session data in the database, but never delete them. Our database fills up with useless session data.

## Description

We use https://github.com/rails/activerecord-session_store which is part of the Rails 3 core.

## Expected Behavior

Sessions older than a month should get deleted.

## Actual Behavior

Session data persists forever even if the user's browser doesn't have the session id any more.

## Steps to Reproduce

1. Log into a long running instance database.
2. Run: `select updated_at from sessions limit 5;`
3. Observe dates that are years old.

```
openfoodnetwork=> select updated_at from sessions limit 5;
         updated_at         
----------------------------
 2015-06-11 02:48:17.72724
 2015-06-11 02:48:18.089722
 2015-06-11 02:48:22.233834
 2015-06-11 02:48:22.443063
 2015-06-11 02:48:26.397765
(5 rows)
```

## Context

I was just about to implement the session store in another project and came across `rake db:sessions:trim`. That rake task is not included in our version of Rails and we never clean up sessions.

## Possible Fix

Check how https://github.com/rails/activerecord-session_store implements the session trimming. Maybe it's just including the gem and adding a task to our cron schedule.

**Comment by enricostano** [comment]
One day we should probably investigate if switching to an in-memory DB for sessions (Redis, etc) would be a good approach for us.

In any case we can check right now how this is affecting Postgres performance due to both accesses and size of the table.

**Comment by mkllnk** [comment]
Yeah, one day. But for now I'm very reluctant to add more complexity to our setup.

How do you check the affect on performance? Benchmark a query, delete all old entries and benchmark again?

**Comment by enricostano** [comment]
You can ask Postgresql and @sauloperez :joy:

**Comment by sauloperez** [comment]
Setup Skylight and monitoring infrastructure and then we can speak again :trollface: .

Jokes aside, my bet is that this will hardly be a problem for our DBs any time soon. As long as we have an index for the appropriate column/s and we don't end up with 100M rows in a month the reads will still be fast enough.

**Comment by mkllnk** [comment]
> @mkllnk what's the problem you're experiencing? Disk space? DB performance?

Nothing I could measure. I just thought it's a possible optimisation, nothing urgent.

**Comment by luisramos0** [comment]
s5 should be in all the things right @sigmundpetersen ?

**Comment by luisramos0** [comment]
keeping this as tech debt only.

**Comment by mkllnk** [comment]
I just looked at this. Our current backup file (sql.gz) is 480 MB. The same without the sessions table is 107 MB. So we are wasting a lot of space, bandwidth and CPU power when creating backups. I'm not sure about the performance though.

**Comment by luisramos0** [comment]
this is related to #3608
