### ISSUE TITLE
App Bootstrap and configuration: Figure out strategy and tools

### ISSUE THREAD

**Issue by weedySeaDragon** [openfoodfoundation/openfoodnetwork#225]
**General Goals?**
1st version: use configuration files 
Later version: be interactive (good for user that is new and/or less technical)

**How to/ Implementation**
- look at how Spree boostraps and loads configuration
- Figaro and any other gems/strategies

When things are decided, make a note in the GitHub wiki for now: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Configuration
- This info may ultimately be moved to the Open Food Foundation website

**Comment by lin-d-hop** [comment]
#gitcull.... no one has cared for years!
