### ISSUE TITLE
Missing interpolation argument :instance

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2250]
## Description
Katuma's Bugsnag reported an error yesterday when I tried the new invite manager feature for our buying group. This seems to be affecting Katuma and the German instance only cc @kirstenalarsen .

Bugsnag's stacktrace:
![screenshot from 2018-04-26 15-36-20](https://user-images.githubusercontent.com/762088/39309150-99c39fcc-4967-11e8-8eeb-850e56639f82.png)

## Expected Behavior
The app sends the invitation email successfully

## Actual Behavior
The app fails with 

```ruby
ActionView::Template::Errorapp/views/enterprise_mailer/manager_invitation.html.haml:9
missing interpolation argument :instance in "¿No está seguro de por qué ha recibido este correo electrónico? Por favor, póngase en contacto con %{owner_email} para obtener más información, o puede ponerse en contacto con %{instance} en %{instance_email}." ({:owner_email=>"xxxx@xxxx.xxx"} given)
```

## Steps to Reproduce

1. Head over to the users section of the enterprise settings
2. Click on "Add an unregistered user"
3. Introduce an email
4. Click on "Invite"

This just caused an error that will be displayed in the Rails log.

## Context
I just wanted to invite a new user to admin our buying group so that she could check reports.

## Severity
This is a severiy 3 as we can work around this by asking the user to create her user first and then asociating her to the enterprise. This is what we used to do so far.

## Your Environment
* Version used: v1.14
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu

## Possible Fix

While the `en` copy changed in https://github.com/openfoodfoundation/openfoodnetwork/commit/101269a4873c2a82f82df72c0c7e25fd4d15f50e removing `:instance` to

https://github.com/openfoodfoundation/openfoodnetwork/blob/6ae1780180adc8bfa1a8d01b8f76cbdb3d610100/config/locales/en.yml#L1353

Some translations still reference the `:instance` and `:intance_email` variables as shown below

```
config/locales/de_DE.yml
1199:    mistakenly_sent: "Nicht sicher, warum Sie diese E-Mail erhalten haben? Bitte kontaktieren Sie %{owner_email} für weitere Informationen, oder kontaktieren Sie %{instance} unter %{instance_email}."

config/locales/en.yml
1353:    mistakenly_sent: "Not sure why you have received this email? Please contact %{owner_email} for more information."

config/locales/es.yml
1198:    mistakenly_sent: "¿No está seguro de por qué ha recibido este correo electrónico? Por favor, póngase en contacto con %{owner_email} para obtener más información, o puede ponerse en contacto con %{instance} en %{instance_email}."

config/locales/fr.yml
1198:    mistakenly_sent: "Vous ne savez pas pourquoi vous recevez cet email? Veuillez contacter %{owner_email} pour toute question."
```

We just need to update the translations in Transifex and fetch them.

**Comment by myriamboure** [comment]
@Matt-Yorkley can you take this one maybe?

**Comment by myriamboure** [comment]
Ok so let's close and we will reopen if we see another issue. Thanks @sauloperez :-)
