### ISSUE TITLE
URI::InvalidURIError in enterprises#relatives

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2251]
## Description
Katuma's Bugsnag reported the following error 4 days ago.

![screenshot from 2018-04-26 15-52-39](https://user-images.githubusercontent.com/762088/39310106-df11b80a-4969-11e8-9879-15558d09a72a.png)

## Expected Behavior
`enterprises#relatives` shouldn't fail, I guess

## Actual Behavior
The app fails with the mentioned error when issuing the following request: 

```
curl --request GET \
  --header 'X-Csrf-Token: OLie+WlEahxpXGW5i+yTRNgVR+ONVsZkgE/dzFHNNXQ=' \
  --header 'Accept-Encoding: gzip, deflate' \
  --header 'Cookie: [FILTERED]' \
  --header 'Accept: application/json, text/javascript, */*' \
  --header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/537.86.7' \
  --header 'Referer: https://alpha.katuma.org/shops#/?query=grup%20de%20consum%20la%20panarra&show_closed=1#grup-de-consum-la-panarra' \
  --header 'Accept-Language: ca-es' \
  --header 'X-Requested-With: XMLHttpRequest' \
  'https://alpha.katuma.org/enterprises/12/relatives.json'
```

## Steps to Reproduce

Check the CURL above.

## Severity
The reach of this bug is still unknown but in any case it's not a critical feature, so severity 3.

## Your Environment
* Version used: v1.14
* Browser name and version: Possibly Firefox
* Operating System and version (desktop or mobile): Mac OS X 10.9.5

**Comment by luisramos0** [comment]
I dont think this should be at the top of the bug backlog. Maybe not even S3.
This is probably related to the producers of a shop and so the impact is probably that the producers are not loaded completely/correctly in some situations.

![Screenshot 2019-05-31 at 15 32 23](https://user-images.githubusercontent.com/1640378/58712863-5339dc00-83b9-11e9-9bf9-bc1a1f4dfc53.png)

I'd move this to the bug backlog, maybe move to s4.

**Comment by RachL** [comment]
This error did not occurred in the last year if I'm not mistaken. closing for now.
