### ISSUE TITLE
Error facing new users who've been invited to manager an enterprise - 'password reset token has expired'

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2254]
## Description
New users who have been invited to help manage an account (via the new Add New User as a Manager button) are redirected to a 'set your password' page when they confirm their email. This is correct functionality (the users have never set a password), but unfortunately when the new user types in a password and saves it they get the 'password reset token has expired' error message. The good thing is that the user has confirmed their account, so they'll be able to ask for a 'reset password' email (PR2238 prevents unconfirmed users from resetting passwords), however it's still confusing for new users- they have to work out where to go to resent a confirmation link.

This bug was found while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2220

## Expected Behavior
When the new user is take to the page where they create a password they should be able to set a password and then be logged in.

## Actual Behavior
The page won't let them set a password and they can't login. They need to navigate theselves to reset password in order to create a password.

## Steps to Reproduce
1. Login with an enterprise owner. 
2. Go to Enterprise Setting > Users and 'Add and unregistered user'
3. Next go to the email of the invited manager, and click the confirmation link.
4. You'll be redirected to a page to create a pw. Enter a valid pw. click save.- error appears

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/10843056/39344215-6ae6bc58-4a24-11e8-8979-79081150594d.png)

## Context
We've just released this new mechanism for inviting new managers - but it has a fairly confusing bug in it, that all users of the feature will run into.

## Severity
s2

## Your Environment
* Chrome and Firefox
* PC, laptop

## Possible Fix
Make the 'create password' form work without errors.

**Comment by daniellemoorhead** [comment]
@enricostano how does the bug triage process work will @myriamboure is away? I think this is a priority to fix, above most other things.

**Comment by myriamboure** [comment]
@sauloperez @mkllnk can https://github.com/openfoodfoundation/openfoodnetwork/issues/2250 be connected to that issue? They seems to happen at exactly the same behavior point.

**Comment by sauloperez** [comment]
I don't think so @myriamboure . #2250 is just related to a translation.

**Comment by daniellemoorhead** [comment]
>@daniellemoorhead this is in delivery backlog so first dev available should take it, and it seems Maikel did already :-)

@myriamboure I wasn't sure if bugs were being triaged by you and @enricostano to make sure the severity set was correct. I remember talk of a weekly catch up to do this...but wasn't sure whether it was still happening :)

**Comment by myriamboure** [comment]
Not really weekly, it's more if there is a need... but if peopel can autonomously manager that on the flow that's the best, we will jump if we disagree I guess ;-)
