### ISSUE TITLE
How does UI customization overlap with i18n re: using different wording? (within a main language)

### ISSUE THREAD

**Issue by weedySeaDragon** [openfoodfoundation/openfoodnetwork#226]
What are the guidelines for using i18n to customize the presentation for a specific OFN installation?  (Or is it too early to spend any time figuring that out?)

i18n can be used to change the specific wording that is presented to a user in the UI, reports, etc. Should that be discouraged?  Are there specific times when that causes problems in the system now?  Could it cause problems in the future?  Does it really matter?
 - someone should probably do some googling & researching to see what issues others have hit when using i18n as  a way to do minor UX tweaking.  (conference presentations, blogs, etc.) 
    - it is acceptable practice?
    - what are the problems that can arise?
    - what happens when the system further grows, evolves, matures?  Does it create brittleness or does it create a reasonable path forward

(This may need to be defined and scoped out as a feature, which happens in  the OFN Trello feature boards.   Contact OFN folks for info on that. )

**Comment by pmackay** [comment]
Am going to close as recently new CMS functionality is being implemented that allows much of the UI to be customised without resorting to i18n.
