### ISSUE TITLE
ActiveMerchant fails to connect to servers with new TLS certificates

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2265]
The Pin Payments gateway just stopped working, because the server got new TLS/SSL certificates. The new certificates are issued with a root cert that is not in the ActiveMerchant bundle.

## Expected Behavior
All payment gateways are working.

## Actual Behavior
Pin Payments stopped working. If any other services renew their certificates that are not supported, the same happens to other gateways as well.

## Steps to Reproduce

1. `bundle exec rails console`
2. `ActiveMerchant::Connection.new("https://test-api.pin.net.au").request(:get, nil)`

Bad response:
```
ActiveMerchant::ConnectionError: The SSL connection to the remote server could not be established
```
Good response:
```
=> #<Net::HTTPNotFound 404 Not Found readbody=true>
```

## Context

We got notified by Pin Payments about their server updates and tested if payments still go through.

## Severity

I'll give it an s3, because it only affects Australia at the moment and I have a manual patch. But it's not a lasting solution.

## Possible Fix

Hot fix on the server:
```sh
curl -fsS https://raw.githubusercontent.com/activemerchant/active_merchant/7ebdc250a7f802d64731f826135b5b8ff86c663d/lib/certs/cacert.pem > "$(bundle show activemerchant | head -n 1)/lib/certs/cacert.pem"
```

Long term fixes:

- Create own branch of ActiveMerchant and patch it (sorry I ran out of time today).
- Get the Spree upgrade done and upgrade ActiveMerchant to the latest version.

**Comment by sauloperez** [comment]
Is it something we can upgrade in parallel or does our Spree version specify an old version of it?
