### ISSUE TITLE
Login modal shows after checkout for users who have previously tried to checkout as a guest as registered user.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2277]
## Description
This bug was found while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2073. If a user tries to checkout as a guest with a registered users's email, then that user gets told 'you can't do that' and they then use another email to checkout as a guest, when they see the order confirmation screen, the login modal pops up. 

## Expected Behavior
The login modal shouldn't pop up.

## Actual Behavior
A login modal pops up over the order confirmation page.

## Steps to Reproduce
1. Checkout as a guest in any shop
2. Try to use the email of a registered user - you'll be told you can't do that, you must either login, or remain a guest but use another email. Close the login modal with the error message.
3. Use a different un-registered email. 
4. checkout- on the confirmation page you'll see the login modal pop up unneccessarily. 

## Animated Gif/Screenshot
See the modal at the end of this video... https://www.useloom.com/share/4d1180870f06415b83ec80c68c6dd99b

## Context
It's a very minor bug, a user would probably just close the modal.

## Severity
S5

## Your Environment
PC, chrome, Aus production

## Possible Fix
Stop the modal opening.

**Comment by myriamboure** [comment]
@Matt-Yorkley as you have worked on this issue it might be quicker for you to have a look and fix it. Can you take this one? Still part of email confirm work as was introduced by it, but last small bits!
