### ISSUE TITLE
Unreadable welcome text (image missing)

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2278]
The enterprise welcome screen where you choose your package (enterprise subscription) is missing the background image which makes the text invisible.

## Expected Behavior

![image](https://user-images.githubusercontent.com/10843056/31980035-9cfd715c-b995-11e7-89c7-8770852935e1.png)

## Actual Behavior

![screenshot from 2018-05-11 14-37-59](https://user-images.githubusercontent.com/3524483/39906945-f43971b2-5528-11e8-9f5b-2faafd2bbcbb.png)

## Steps to Reproduce

1. Log in as enterprise user
2. Edit an enterprise
3. Change the last part of the URL from `edit` to `welcome` and hit enter
4. Alternatively, you can sign up as a new enterprise. That's how people usually see it.

## Context

Sally was testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2269, but couldn't see the changed text.

## Severity

It's affecting every new enterprise user. The interface is usable, but they may not understand everything. => s4

## Your Environment

Tested locally, on staging and production.

## Possible Fix

We can define a dark background colour for the case that the image isn't there. Additionally, we could restore the image to it's supposed position at `/assets/home/tagline-bg.jpg`. I found the image on our old server.

![tagline-bg](https://user-images.githubusercontent.com/3524483/39907109-e9f348a8-5529-11e8-80ed-824df03d52c2.jpg)

**Comment by robotscissors** [comment]
I would be happy to take a stab at this. May I have this issue?

**Comment by mkllnk** [comment]
You are very welcome to work on this issue. :-)

**Comment by myriamboure** [comment]
Welcome @robotscissors! Seems you are new here right? If you have any question feel free to ask and check [the wiki](https://github.com/openfoodfoundation/openfoodnetwork/wiki) to see a bit how we work, what we expect in PRs, etc. ;-) How did you find us btw?

**Comment by robotscissors** [comment]
I found you on codetriage.com! Thank you for the tips too.
