### ISSUE TITLE
Embed Gitbooks user guide into global website

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2279]
## Description
We've created a new version of the User Guide in Gitbooks as opposed to Wordpress. This was triggered by the global community's need for instance specific guides, and for multiple languages. The new Gitbook guide has been created and is now ready to be used. It needs to be embedded into the global website before the link can be shared with users. The old guide is not being maintained very well, so we need to embed the new one soon.

**- As a:** Instance manager, i need to be able to direct users to an up to date user guide.

**- On page:** To date the guide has been located here http://openfoodnetwork.org/user-guide/. To save redirecting people, the proposal is that we embed the gitbooks guide there as well. 

**- I want to be able to do:**  Have 1 guide that's up to date, located in the right place.

## Acceptance Criteria
The Gitbooks guide should be embedded into the global website, preferably here - http://openfoodnetwork.org/user-guide/

**Further details about the task**
- See slack channel #userguide for information about how to login to the Gitbooks version of the guide.
- Here's the Gitbookd instructions for embedding -https://docs.gitbook.com/content-editing/customization#custom-domain
- You'll need access to the openfoodnetwork.org domain hoster i think- if so ask me and I'll get you the code etc. It's hosted with GoDaddy, admin@openfoodfoundation.org, customer number 64954248
- You may need access to Wordpress as well - let me know if you need this.

Question: What do we do with the old user guide material? Will users be frustrated that the version of the guide that they are used to will no longer be there? I've spoken to Dani and we think that because the new guide has search functionality it's ok to replace the old guide entirely. - However Nick has mentioned that UK has spread some documents that have specific user guide links in them- thus we may need to add some sort of banner to all the old pages saying 'our guide has moved' - is there a quick way to do this (maybe add a note onto the menu- which is on all pages)? Otherwise I/someone can do it manually.

**Comment by mkllnk** [comment]
We could embed the guide at https://openfoodnetwork.org/user-guide/, but that would slow it down (our server would need to become a proxy for Gitbook). Technically, it's much better to have it at https://guide.openfoodnetwork.org/ and install proper redirects. That's what I've done now. We can add more redirects in the Wordpress admin panel to help people find the right pages.
