### ISSUE TITLE
From Product Edit if I cancel I'm taken to unfamiliar Listing Products page.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2297]
## Description
I was introducing a new user the the products page, and showed them the edit product area. We clicked cancel from the product edit page and were redirected to the 'Listing Products' page. This page is otherwise inaccessible, and it can disorientate the user. They expect that cancelling will take them to where they were before (Bulk product Edit).

## Expected Behavior
If I click cancel from Edit Product, i should be redirected to 'Bulk Product Edit' - the page I was on before going to edit the produt. 

## Actual Behavior
I'm redirected to Listing Products which is an unfamiliar view, and as far as I know, it's not intended to be used as part of OFN. It's a Spree remnant. 

## Steps to Reproduce
1. Login with an enterprise that has products
2. Click on edit a product
3. Then click cancel - you'll be redirected to Listing Products page.

## Animated Gif/Screenshot
https://www.useloom.com/share/5651af4a95814b7f8c1785795d19bade

## Context
It makes the website harder to navigate and it feels buggy to be taken to a phantom page.

## Severity
S4

## Your Environment
PC, Aus production, Chrome

## Possible Fix
When in the product edit page, if I hit cancel, i should be directed to Bulk Product Edit page.

**Comment by frank-west-iii** [comment]
There are 2 possible solutions to this, but would like to know which one would be best to implement:

Option 1:
```
Spree::Core::Engine.routes.prepend do
  get '/admin/products' => 'admin/products#bulk_edit'
```
Cons: Url mismatch may cause confusion in future debugging sessions with customers

Option 2:
```
Spree::Core::Engine.routes.prepend do
  get '/admin/products', to: redirect('/admin/products/bulk_edit', status: 301)
```
Pro: Urls will be the same regardless of how you get to bulk edit


Either way we can also look at removing several locations in the code where we use spree/deface to override the url for certain actions.

Deface could not be used here because the "Cancel" button is in a shared view and would affect every "Cancel" button.

**Comment by myriamboure** [comment]
@mkllnk @sauloperez what do you think is the best option?

**Comment by sauloperez** [comment]
Touching the URLs seems indeed confusing. If that cancel shared view was ours, would it make sense to add a URL argument to it so that we can provide the one for bulk_edit in this case?

**Comment by frank-west-iii** [comment]
@sauloperez, I don't believe it is ours. It is a spree shared view. Although I am not extremely familiar with Spree it seems like a URL arg may not be feasible. Thoughts?

https://github.com/openfoodfoundation/spree/blob/step-6a/backend/app/views/spree/admin/shared/_edit_resource_links.html.erb

I think a permanent redirect would be the most straightforward case as it would very explicit in debugging as the redirect would show up in the logs.

**Comment by sauloperez** [comment]
> I think a permanent redirect would be the most straightforward case as it would very explicit in debugging as the redirect would show up in the logs.

You convinced me there :+1:

**Comment by mkllnk** [comment]
Yes, I agree that the redirect is a good solution for this particular problem. Going forward, I'm wondering if we should place our bulk product edit exactly in the same spot as Spree's product editing has been. We wouldn't need the redirect any more, because we are replacing Spree's view instead of adding another one.

**Comment by mkllnk** [comment]
No, it doesn't. But we use the bulk edit view instead of Spree's product list, right?

**Comment by frank-west-iii** [comment]
@mkllnk, was the idea here to rename bulk product edit to index essentially overriding Spree's index action in this location? 
https://github.com/openfoodfoundation/openfoodnetwork/blob/9d57beb33f89b694dd50e5ce281dd3a80ebe5310/app/controllers/spree/admin/products_controller_decorator.rb

**Comment by mkllnk** [comment]
Yes, that was my idea. Thank you for putting it in clearer words. What do you think about that?

**Comment by frank-west-iii** [comment]
I can take a stab at that to see what that would look like in an overall change.

Are we worried about renaming routes and users getting 404s if they bookmarked the old route? It's probably not a huge problem but thought I would ask just in case.

**Comment by sauloperez** [comment]
Well, I personally try to keep routes for that exact same reason but I don't see it as a big problem here either.

**Comment by mkllnk** [comment]
We haven't been caring about routes much. It would be a nice practice to respond with a permanent redirect for old routes when we make a change.
