### ISSUE TITLE
Email confirm - guiding sentence missing in registration process

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2303]
## Description
At the step where the entreprise has been created and the message "your entreprise has been added to the OFN" appears, the small guiding sentence "“If you exit the wizard at any stage, you can continue to create your profile by going to the admin interface” has disappeared and needs to be added.

## Expected Behavior
The small guiding sentence is here.
![screenshot from 2018-05-21 15-08-48](https://user-images.githubusercontent.com/8135376/40309186-ea5707da-5d08-11e8-88db-5b8f59673a01.png)

## Actual Behavior
It is not
![screenshot from 2018-05-21 15-09-44](https://user-images.githubusercontent.com/8135376/40309217-061be954-5d09-11e8-94c7-a2f6bccc04f8.png)

## Steps to Reproduce
1. create an entreprise from the registration wizard

## Context
I was reviewing story #1585

## Severity
s5

**Comment by luisramos0** [comment]
Hi Myriam, the message was never that one, right?

From git I believe the message was "If you exit this wizard at any stage, you need to click the confirmation link in the email you have received. This will take you to your admin interface where you can continue setting up your profile."

This was added Oct 1st 2015 by Maikel and then removed by Matt-Yorkley on Feb 6th 2018.
The removal was related to "Remove mention of confirmation email from enterprise creation wizard".

So, now we want to put back the message you mention above (this one does not mention the confirmation email like the previous version). I'll assume this is correct and go ahead, let me know if you see any problem here.

Thanks, Luis

**Comment by luisramos0** [comment]
Hi @rob @mkllnk, the PR #2336 fixed this specific issue and tested the move of translations in the en.yml without the need for new translations.
@mkllnk confirmed that "moving the other 8 was recognised by Transifex and it updates the translations automatically without a human needing to translate it again."
This was done only for step TYPE in the registration process.
So I think it's ok to have the PR closed and also this issue. Shall we open a new issue to move all the other registration steps to this new structure? Can you please confirm and I can open the issue.
Thanks!

**Comment by mkllnk** [comment]
Yes, please. It would be great to clean up the translation file. Otherwise people just go with the flow and add to the mess.

**Comment by luisramos0** [comment]
ok @mkllnk, done.
