### ISSUE TITLE
"Invite new manager" email not translated

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2306]
## Description
As a hub manager I invite a new manager who is not yet on OFN. That triggers an email to the contact email address, but this email is in English and not translated.

## Expected Behavior
The email received is in local language.

## Actual Behavior
The email received is in English

## Steps to Reproduce
1. As a hub manager go to enterprise settings, "managers" tab
2. Click on "Invite a manager/add a new user"
3. Enter the email address of the person you want to invite (who is not yet on OFN)
4. Check the mailbox for that email address and see

## Animated Gif/Screenshot
![screenshot from 2018-05-22 05-15-51](https://user-images.githubusercontent.com/8135376/40340478-64ab669a-5d7f-11e8-9aca-86be8e347b3e.png)

## Context
I was doing some test on email confirm end to end

## Severity
S3

## Your Environment
* Version used: master branch between v1.15 and v1.15.1 depoyed on French staging
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): desktop Ubuntu

## Possible Fix
Make translation possible.

**Comment by myriamboure** [comment]
@Matt-Yorkley @HugsDaniel can one of you assign to this one maybe?

**Comment by Matt-Yorkley** [comment]
The translation keys are there, is this maybe a Transifex issue?

**Comment by myriamboure** [comment]
Hum... @mkllnk did something in the last days, I will check with next deploy... those transifex issues are annoying, would be great to understand the core issue and try to fix it.

**Comment by myriamboure** [comment]
I checks on French production with the last upgrade and it's all displaying well. Closing then.
