### ISSUE TITLE
Translations missing in "orders" page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2308]
## Description
When filtering orders the "no order founds" result isn't transated
![namhpcfbljehhfgp](https://user-images.githubusercontent.com/8135376/40341984-770f1ee0-5d88-11e8-9612-01ccfca33e67.png)

**Comment by luisramos0** [comment]
Let's see if it's a "good first PR" for a "good first issue" :-)
