### ISSUE TITLE
Translations missing in "order edit" page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2309]
## Description
"Shipping" remains untranslated.
> in "order details" section
![screenshot from 2018-05-22 06-20-56](https://user-images.githubusercontent.com/8135376/40342061-de01f1ae-5d88-11e8-90d2-3af2875948b5.png)
> in "adjustments" section
![screenshot from 2018-05-22 06-25-39](https://user-images.githubusercontent.com/8135376/40342133-1f572340-5d89-11e8-95a3-97a76c71d531.png)

**Comment by luisramos0** [comment]
Hi Myriam, I can't replicate. I tried a few different things but it's showing "Expédition:". You are on fr, right?

<img width="693" alt="screen shot 2018-05-23 at 12 33 56" src="https://user-images.githubusercontent.com/1640378/40422024-d2ea5a7e-5e85-11e8-8259-11df35f7b7ca.png">

Was that "Shipping" manually entered?

**Comment by myriamboure** [comment]
Yes, this one seems fixed now so closing.
