### ISSUE TITLE
Product Import: imported product counts not displaying

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2312]
## Description
After saving the new product info from csv file, the last step show the "results" and tell how many products have been saved successfully. This count is not working.

## Expected Behavior
Count should work.

## Actual Behavior
Count is not working.

## Steps to Reproduce
1. Go to hidden https://staging.openfoodnetwork.org.uk/admin/product_import and follow the steps until you reach the "results" page (after saving products).

## Animated Gif/Screenshot
![screenshot from 2018-05-22 16-53-31](https://user-images.githubusercontent.com/8135376/40370716-26ad75b0-5de1-11e8-86ed-481ada98225e.png)

## Context
Listing product Import issues after first big PR

## Your Environment
* Version used: branch #1492 on UK staging
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
Make sure count works ;-)

**Comment by Matt-Yorkley** [comment]
This is another Transifex issue, the translation doesn't contain `{%num}` anymore, but some of the translations have not been updated...

**Comment by myriamboure** [comment]
:+1: :point_up: @mkllnk

**Comment by Matt-Yorkley** [comment]
This has been fixed now via Transifex updates. :+1:
