### ISSUE TITLE
Product Import: "reset absent products" is not working

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2313]
## Description
I upload a csv with 2 products only from producer "Sole of Discretion".
I click "reset absent products" when selecting import options. I get the warning message
![screenshot from 2018-05-22 17-14-45](https://user-images.githubusercontent.com/8135376/40371842-a9baa836-5de3-11e8-9a93-37de38d788e4.png) 
so logically all other products from that producer apart those 2 products in the file should be reset to zero stock.

## Expected Behavior
If "reset absent products" is checked, stock info for all absent products from the same producer should be set to 0.

## Actual Behavior
Nothing happens, products that are not in the csv remains untouched

## Steps to Reproduce
1. Go to hidden https://staging.openfoodnetwork.org.uk/admin/product_import
2. Import a csv file and click "reset absent products" option on import options
3. Go till the end an check products in the producer products listing

## Animated Gif/Screenshot
https://www.useloom.com/share/5360a4632a624878bef98f9efe9bcef9

## Context
Listing product Import issues after first big PR

## Your Environment
* Version used: branch #1492 on UK staging
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by RachL** [comment]
This is resolved in https://github.com/openfoodfoundation/openfoodnetwork/pull/2474

See testing notes in there for more info :) So I'm closing this one.
