### ISSUE TITLE
Product Import: confusing UX when "viewing products" at the end of the process

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2314]
## Description
When I reach the last step of the import, products are saved and want to "view products". I am redirected to product listing page with only the updated products shown. But as a user now that I am on that product listing page I want to check all the products for a given producer, so I select a product in the filters. Nothing happens. I have to clear filters and then use them again for the filter to be unllocked and enable me to filter again.

## Expected Behavior
When I am viewing the updated products on products listing, if I use filters they apply and replace the view of updated products.

## Actual Behavior
When I am viewing the updated products on products listing, if I use filters they are ignored, nothing happens, and I have to "clear filters" to be able to use the filters again.

## Steps to Reproduce
1. Go to hidden https://staging.openfoodnetwork.org.uk/admin/product_import and import and save some products 
2. On the result page, click on "view products"
3. Try to fitler on a producer > nothing happens, you still view the upload results
4. Clear filters, then filter on producer again > it works

## Animated Gif/Screenshot
https://www.useloom.com/share/e3e374eb8a414953a6513e84f683b2de

## Context
Listing product Import issues after first big PR

## Your Environment
* Version used: branch #1492 on UK staging
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
Make sure that once on product listing page, if filter is applied, it works

**Comment by RachL** [comment]
@myriamboure another way might be to redirect to the product page and on this page create two new filters pre-checked : last update & created date (by default they would show the products updated or created during the last week, and the user would be able to change the period). Thus, we don't make another page like now, we use the the same page but with new filters. And I think the filters might work directly then.

**Comment by myriamboure** [comment]
That's a good idea @RachL !
Would that be on option technically @Matt-Yorkley ?
I think we need a broader reflexion on UX (see https://github.com/openfoodfoundation/openfoodnetwork/issues/2325 and https://github.com/openfoodfoundation/openfoodnetwork/issues/2329 as well to understand the general UX issues)

**Comment by myriamboure** [comment]
I think that's what @lin-d-hop meant in https://github.com/openfoodfoundation/openfoodnetwork/issues/1431 and https://github.com/openfoodfoundation/openfoodnetwork/issues/1432 so I guess we are on the same page here.

**Comment by Matt-Yorkley** [comment]
It's because the Import Date filter is set. If you change it, it will show more products.

**Comment by myriamboure** [comment]
Oh ok sorry @Matt-Yorkley I didn't get it ;-) See suggestion from @RachL above to create two fields  "last update & created date".
For users who don't use this import feature it's strange to have a field name "import date", so as a minimum I would rename "Last update" (considering that creation is an update somehow). I don't see right now a use case where we would need also the creation date, do you have one in mind @RachL ? Else I suggest we just rename the filter in that case and don't add another one for now, until the need appears.

**Comment by RachL** [comment]
@myriamboure creation date was for me usefull in order to show the last product created. But maybe these products will appear as well when the user selects last update. Which is fine by me

**Comment by myriamboure** [comment]
Question @Matt-Yorkley : this "import date" button, does it capture all updates dates on products? or only if import feature is used? Do you see that filter added on the main bulk product filters? I guess yes...
So I guess it neets some functionnal modification as today this filter only take into account dates when an import is made, not when an update is made on a given product?
So my suggestion is not only to rename the filter "last update" but also a bit the behavior: add it in the main filters on "bulk products" page + capture dates when updates were made, even if not through imports. What do you think @Matt-Yorkley ?

**Comment by myriamboure** [comment]
For now proposal is to hide the button: https://github.com/openfoodfoundation/openfoodnetwork/issues/2365 until we know what to do otherwise it will be visible in production.

**Comment by RachL** [comment]
@myriamboure In real life you won't do a manual product creation as the same time as an import. Then, the last products visible on the page will only be imported products if you do an import. So they are on top, which I think is clear enough. But maybe I did not understand what you've meant and then let's talk yes :)

**Comment by myriamboure** [comment]
Closing this as we reached to an agreement that we would ask first to choose where they want to import (see https://github.com/openfoodfoundation/openfoodnetwork/issues/2452)
