### ISSUE TITLE
Product Import: add possibility to choose “on demand” for “set stock level” in import options

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2315]
## Description
A user who imports products via csv might want to set up all items or "empty" items (using the import option "set stock level") to "on demand". It is not possible today. It can only be done today within the csv file (column on_demand, 1 if yes, 0 if no).

## Expected Behavior
If I click on "set stock level" in import options I should be able to choose "on demand" instead of having to choose a fix quantity

## Actual Behavior
Same for "set stock level" in import options

## Steps to Reproduce
1. Go to hidden https://staging.openfoodnetwork.org.uk/admin/product_import
2. Upload a csv and select "set stock level", "overwrite all" or "overwrite if empty" (doesn't matter)
3. You can only select a fix amount, no "on demand"

## Animated Gif/Screenshot
![screenshot from 2018-05-22 17-31-38](https://user-images.githubusercontent.com/8135376/40373912-39bc331a-5de8-11e8-8361-d153a15e1d9a.png)

## Context
Listing product Import issues after first big PR

## Your Environment
* Version used: branch #1492 on UK staging
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
On the import options, add a checkbox "on demand?" at the right of the quantity selection and if it is checked the quantity field should be greyed and not possible to fill in anymore
![untitled presentation](https://user-images.githubusercontent.com/8135376/40374255-fe90025c-5de8-11e8-8f15-64eb2b123282.jpg)

**Comment by Matt-Yorkley** [comment]
I think for setting it from csv, the column should be called `on_demand`, and the value should be `1` for yes, and blank or `0` for no.

**Comment by Matt-Yorkley** [comment]
I'll take a look at adding an extra import option for it.

**Comment by myriamboure** [comment]
Yes sorry @Matt-Yorkley it works within the csv, I changed the first description line to reflect it, it's just on the import options that you can't set it up to on_demand.

**Comment by oeoeaio** [comment]
I'm not going to get a chance to look at this before I go away tomorrow night, so un-assigning myself for now.

**Comment by myriamboure** [comment]
Closing it for now as we are removing the default setup possibilities for the first iteration, it is creating too much confusion and not adding so much value.
