### ISSUE TITLE
Product Import: rename import options labels

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2319]
## Description
The current labels mention "default" like "set default stock level", "set default tax category". This term like "default stock level" is already used in inventory to talk about the default stock you set for when you "reset stock to default" so I'm afraid users might get confused with same terminology. I suggest to just remove the "default" word in the 4 import options.

## Expected Behavior
"set stock level"
"set tax category"
"set shipping category"
"set available date"

## Actual Behavior
"default" is added.

## Steps to Reproduce
1. Go to hidden https://staging.openfoodnetwork.org.uk/admin/product_import
2. Upload a file and see option proposed.

## Animated Gif/Screenshot
![untitled presentation 1](https://user-images.githubusercontent.com/8135376/40426368-2f7533f8-5e9b-11e8-8b1b-b4e97ebc4c8f.jpg)

## Context
Listing product Import issues after first big PR

## Your Environment
* Version used: branch #1492 on UK staging
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by myriamboure** [comment]
I'm not sure about this one @RachL what do you think?

**Comment by RachL** [comment]
@myriamboure it was confusing for me as well when I've tested. So I agree on this one. Plus the term does not help the user (even if we would not be using it somewhere else), so let's not use it.

**Comment by myriamboure** [comment]
We are removing that step from the product import feature as confusing and really not practical in term of UX, we added the two key things we wanted to keep on the first page (where to import + what do we do with products that are not in the spreadsheet). We will iterate then given users feedback.
