### ISSUE TITLE
Product Import: override in "set tax category" doesn't work

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2321]
## Description
I import a csv with products to update (the problem doesn't happen for new products created) and select import option "set tax category", "override all" (or "override if empty", doesn't matter) and I choose "reduced rate". I proceed till the end and view products, i check and shipping category is not set to "reduced rate".

## Expected Behavior
If I override tax category info for the products I import, it should work also for existing products (not only new products).

## Actual Behavior
It doesn't work for already existing products

## Steps to Reproduce
1. Go to hidden https://staging.openfoodnetwork.org.uk/admin/product_import
2. Choose a csv and choose as import options "set tax category", "override all" and "reduced rate"
3. Go till the end and see

## Animated Gif/Screenshot
![screenshot from 2018-05-23 15-53-01](https://user-images.githubusercontent.com/8135376/40428829-77d0f4ec-5ea1-11e8-9496-079342bd2ad9.png)
- For new product blueberries it works:
![screenshot from 2018-05-23 15-53-15](https://user-images.githubusercontent.com/8135376/40428834-7aa32fbe-5ea1-11e8-98ec-fe17d0bb504c.png)
- For existing products pinapple it doesn't:
![screenshot from 2018-05-23 15-53-29](https://user-images.githubusercontent.com/8135376/40428837-7cd6acd4-5ea1-11e8-838c-324e7d08fca4.png)

## Context
Listing product Import issues after first big PR

## Your Environment
* Version used: branch #1492 on UK staging
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by Matt-Yorkley** [comment]
Some fields can't be updated for existing products but can be set for new products. I think it's in the original brief. Maybe that's something that needs to be clarified in the user guide.

**Comment by myriamboure** [comment]
Hum... I don't understand the story behind that then. For me the "risk" is the same than for setting up stock level for all products or "empty field" products in the csv. Why couldn't the user do that for tax category? 
I think it's pretty confusing to have exactly the same UX but not the same resut depending on the import option. I don't think just explaining it in the user guide is a solution here.
I checked the original brief https://docs.google.com/document/d/1PB4OBpnhvINPXr4F2qfmUcjl8Ug3nyVh-6v7UokBNiI/edit# but could't find any info about thath. @lin-d-hop do you know why we wouldn't allow users to set default tax and shipping categories to all / empty products in the csv if the products exists already in the system?
If there is no need to set default values, or if it's too risky and users wi make mistakes, then I would just delete the import option and just force users to fill in their column. If there is a need I woud allow for both new and existing products.
I would vote for having the same behavior than others and just make it possible to update exsiting products info.

**Comment by myriamboure** [comment]
Closing for https://github.com/openfoodfoundation/openfoodnetwork/issues/2460
