### ISSUE TITLE
Product Import: csv with both products list and inventory updates for various enterprises is not saved

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2325]
## Description
I import a csv with update on two product lists and on two inventories. One of the product is added at the same time to product list and inventory.
![screenshot from 2018-05-23 21-18-09](https://user-images.githubusercontent.com/8135376/40446412-712e0066-5ecf-11e8-85e2-036b05f037c3.png)

## Expected Behavior
All products are imported correctly.

## Actual Behavior
Two errors:
- the new product added at the same time in product list and inventory is liste as an error for the inventory entry. It seems it's not possible to add a product to an inventory if the product is not already in the system
![screenshot from 2018-05-23 21-04-52](https://user-images.githubusercontent.com/8135376/40446397-62a9eb54-5ecf-11e8-8103-968fb076fdd8.png)

- the info doesn't manage to get saved, progression bar is not moving.
![screenshot from 2018-05-23 21-11-38](https://user-images.githubusercontent.com/8135376/40446404-66b7d210-5ecf-11e8-86da-d95da8dac946.png)
I tried to delete the line for the error inventory entry, and it doesn't change anything, saving doesn't work.

## Steps to Reproduce
1. Go to hidden https://staging.openfoodnetwork.org.uk/admin/product_import
2. Upload a csv following the model in the description
3. Set up the two "inventory" enterprise to "inventory" on import options
4. Proceed, the file is uploaded.
5. See error, but still proceed
6. Save doesn't work

## Animated Gif/Screenshot
https://www.useloom.com/share/1fe2bbb8d1944502857fe9e9112acd4a

## Context
Listing product Import issues after first big PR

## Your Environment
* Version used: branch #1492 on UK staging
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by RachL** [comment]
@myriamboure what strikes me is that the user works on a file to put for each line if it's an inventory or a product import. And then when he/she arrives on OFN, we ask me again for each entreprise if it has to be imported into products or inventory. The job is done twice.

I would suggest that the user make two csv file : one for inventory and another one for products (thus the "supplier" column has the same meaning inside one file). And we ask him if he is uploading a file for products or inventory **before** he/she uploads the file.
The "import into" line in the import options for each enterprise could then be deleted.

What do you think ? ping @sstead @kirstenalarsen

**Comment by myriamboure** [comment]
Yes, actually I agree 100% and I will open right now a new issue to propose that instead and that could close this one. What's more, when you go till the end you have the button "biew products" if you imported in products listings, OR "view inventory" if you imported in inventories, but you can't view both at the same time, so there is a flow somehow in the end to end process if we let people put in the same file both products listings and inventory lines. I think it simplifies the UX. Let's see what other people think :-)

**Comment by myriamboure** [comment]
Else if we believe users need to be able to do both at once we need to review UX for the end of the process and maybe not propose to "view products" or "view inventory"... opinions welcome.

**Comment by myriamboure** [comment]
I gave a try to another possible UX: https://github.com/openfoodfoundation/openfoodnetwork/issues/2329 please let me know what you think.
For me we have two options:
- either we review the UX for the start of the process as proposed in #2329
- either we change the end of the process, after saving, and just display a success page but don't propose the user to "view products" or "view inventory" (which would also simplify a lot the process I think as UX is tricky and not really satisfying on that part today)
- or we do both
@sstead @kirstenalarsen @lin-d-hop @Matt-Yorkley please share your views on that :-)

**Comment by sstead** [comment]
I don't feel immersed enough in Product Import to give good advice on this one.. From looking at what you describe in #2329 it sounds user-friendly enough. It just requires that you go through the upload process twice if you need to update both Products and Inventory? If you're doing this, it looks like you already have a column in the csv indicating whether the row applies in products or inventory, so it should be easy for the user to filter the spreadsheet and create 2 CSVs - one for products, one for inventory? Do I understand this correctly? The questions is whether it's acceptable to ask some users to do 2 uploads if they need to? I imagine for most users it won't be a problem, but there might be some cases where users resent the extra step (if they're regularly updating both products and inventory).

I'm not sure about that second dot point. Maybe it's ok that the user chooses where they want to be redirected to- products of inventory.

**Comment by myriamboure** [comment]
Yes basically we have two options:
- we allow to import to product listings and inventory in one single file. 
Pros: you can do all in one file / one import
Cons: if you have many enterprises in that file, you need for each one of the enterprise to precise if you want to import to product list or inventory, it's pretty annoying + the csv is a bit confusing as "supplier" and "producer" have close meanings and I'm not sure users will understand the difference to build the spreadsheet correctly.
- we separate product listing and inventory import as two different processes. 
Pros: you don't have to specify for each enterprise if import is in product listing or inventory so if many enterprises it's easier + less error probably I guess with the confusing about "supplier" and "producer" columns use 
Cons: if need to do two imports.

UX about last step is still unclear to me.

I think we would need:
- to talk with some users who have explicitly expressed a need for that to test the options (@kirstenalarsen @lin-d-hop I think you know users who need that)
- and maybe have some UX expert view at some point...

**Comment by RachL** [comment]
@myriamboure if we choose to keep only one file, I suggest that the file should have one more column, with the content "inventory" or "product". It would be quicker than clicking one by one after import. Of course there is the remaining issue of the supplier column but at least the task of choosing between inventory and product wouldn't be done twice.

**Comment by myriamboure** [comment]
Very good point @RachL, good idea :-)

**Comment by Matt-Yorkley** [comment]
I hadn't thought about this case before, but yes, a product being imported into inventory has to relate to an existing product in order to be saved properly. If we're trying to add the product record and add it to inventories at the same time it won't really be possible...

**Comment by Matt-Yorkley** [comment]
On second thoughts, I can probably work out a solution for this.

**Comment by kirstenalarsen** [comment]
my 2c, influenced by ofn over many years . . we try to accommodate too many options for too many people and end up making features too confusing for anyone to use

So I would vote to separate the processes 

Most people, and certainly more basic users don’t need to understand what inventory is. This may change as inventory becomes more the way of doing things, in which case most people won’t need to know about updating underlying products

But I think is really good for them to make that choice before they hit the button - which one am i doing?

And if they’re not running inventory on any of their enterprises perhaps they shouldn’t even have the option

**Comment by myriamboure** [comment]
Great, I like that. @lin-d-hop you worked on the first spec for this feature, what do you think about that?

**Comment by myriamboure** [comment]
Closing as we are changing the UX and this won't be a problem anymore
