### ISSUE TITLE
Link to Skylight dashboard for each instance

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#2327]
#### Overview

I have been in contact with Skylight regarding the registration of the Australian OFN instance as an open source user. I was contacted by Vaidehi, who said this:

>Right now, on the Open Food Network repo README, there is a performance monitoring badge that links back to the Barcelona OFN app. Since there will now be two different OFN app instances, we'll need a way to allow your contributors to see your individual, separate performance data dashboards, depending on whether they're viewing the Barcelona OFN app, or the Australia OFN app.

>The way that we've dealt with this for other apps is by including a dynamic link that points to the specific Skylight dashboard URL in a visible enough place so that your contributors can find it. 

Basically what I propose to do in order to fulfil this requirement is to add an env variable which will be used to conditionally show a link to the relevant instance's Skylight dashboard in the footer show in the front-end views.

I am working on a PR now, which I will submit soon, but just wanted to record this issue as context for the PR.

**Comment by sauloperez** [comment]
Regarding the badge in the README, I thought we could have the Australian one as it's the one with the highest traffic.
