### ISSUE TITLE
Seeding suburbs: Looking up state by name creates bad data (ex: 'WA')

### ISSUE THREAD

**Issue by weedySeaDragon** [openfoodfoundation/openfoodnetwork#233]
When seeding suburbs, the new suburbs get the reference to a state in the spree_states table. But currently, the state is looked up just using the state abbreviation.  Using just the state abbreviation does not guarantee that the correct state will be found. 
After seeding, there are two entries in the spree_states table with the same abbreviation: Both Western Australia in Australia, and Washington State in the United States have the abbreviation "**WA**".

Because <code>suburb_seeds.rb</code> just looks up "WA" and since Spree seeds the states from the United States before the states from Australia are added, any suburbs in Western Australia end up with a reference to Washington state, USA (the first "WA" found).  Specifically, the following suburbs get a reference to Washington State, USA: GIBSON DESERT NORTH, GIBSON DESERT SOUTH, NGAANYATJARRA-GILES.
 *(Perhaps they're just tired of being parched and have decided to relocate to the delightfully damp western part of Washington State (WA), USA.)*

When seeding suburbs, the states used should be limited to a specific country. (Perhaps a scope could be defined.)

(This could be addressed as part of issue #220 )

To reproduce:
1. Drop any existing db, then create, load, and seed a database (<code>rake db:drop, db:setup</code>)
 - during seeding, Spree will load countries and states (US). 
 - OFN db/seeds.rb will  then load Australian. states, then will seed the suburbs

The code is in  \db\suburb_seeds.rb :
```
module SuburbSeeder
	def self.seed_suburbs
		state_id_act = Spree::State.where(abbr: "ACT").first.id
		state_id_nsw = Spree::State.where(abbr: "NSW").first.id
		state_id_nt = Spree::State.where(abbr: "NT").first.id
		state_id_qld = Spree::State.where(abbr: "QLD").first.id
		state_id_sa = Spree::State.where(abbr: "SA").first.id
		state_id_tas = Spree::State.where(abbr: "Tas").first.id
		state_id_vic = Spree::State.where(abbr: "Vic").first.id
		state_id_wa = Spree::State.where(abbr: "WA").first.id
```

**Comment by pmackay** [comment]
Closing as suburb import no longer supported.
