### ISSUE TITLE
Missing translations in the frontoffice > shops list > filter by delivery (fr and pt)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2334]
(this is the first issue I raise, please correct me if I am doing something wrong. I have searched the backlog and couldn't find this issue there)

## Description
See screenshot and "delivery" filter in live French instance 

## Expected Behavior
Should be translated in appropriate language

## Actual Behavior
Delivery/Pickup is always shown

## Steps to Reproduce
go to https://www.openfoodfrance.org/shops#/
Click "Filtrer par"
And see text in English under "Filtrer par Livraison"

## Animated Gif/Screenshot
<img width="1198" alt="screen shot 2018-05-25 at 23 34 12" src="https://user-images.githubusercontent.com/1640378/40568817-c832b2ca-6074-11e8-850b-4a1a27d80ed8.png">

## Context
I am reviewing ofn's translation to Portuguese.

## Severity
4

## Your Environment
* Version used: LATEST as of 25/05/2018
* Browser name and version: chrome
* Operating System and version (desktop or mobile): macos

## Possible Fix
I will create a PR to fix this shortly.

**Comment by myriamboure** [comment]
Awesome @luisramos0 you got it! Good to get used to the template :-) For translations missing sometimes we shorten it a bit as it's pretty obvious, but good habit to use the template, thanks!
