### ISSUE TITLE
Intermittent invalid certificates message on some recent Samsung phones

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2344]
## Description
Almost every week I get reports from users who tell they can't access the shop on their Samsung mobile because they get the "certificat unvalid issue".
I'm trying to get more info from users to understand why it's not working on certain Samsung mobiles... but it's pretty common, it happens every week. Users get worried when they see that, especially for hubs where they are supposed to pay with credit cards.
As you can see the cerificate expires on 10th June and we are 29th May so it is valid.
It must be something with the version of the Android browser? Or some parameters?

We know the present case is with a **Samsung Galaxy A8 from 2018, with Android 7.1.1 Nougat (probably with the Samsung Experience 8.5 UX on top if I check the model characteristics on the web). Browser is Google Chrome.

![33769795_2091038477847934_2500277183725961216_n](https://user-images.githubusercontent.com/8135376/40660401-327bd51a-6351-11e8-8a3d-2734cd491d6b.jpg)
![33720436_2091032307848551_7290310563773546496_n](https://user-images.githubusercontent.com/8135376/40660404-34ddcf3e-6351-11e8-8b95-b4cf5d276232.jpg)

## Expected Behavior
They can access the site from their Samsung mobile

## Actual Behavior
They can't on some recent  mobiles for un unknown reason

## Severity
S3 there is a workaround which is to go on the computer, but users get anxious.

**Comment by kirstenalarsen** [comment]
This seems more like bug affecting immediate users than wishlist to me?

**Comment by RachL** [comment]
hey @myriamboure any updates on this one? I've received nothing related in customer support.

**Comment by RachL** [comment]
We talked again with the user and the person who experienced it is not around anymore. So we're closing this and if it happens again we can reopen.
