### ISSUE TITLE
Enterprise tabs in shopfront display on two lines

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2347]
https://github.com/openfoodfoundation/openfoodnetwork/pull/2331 made the shopfront tabs display in two lines. I accidentally merged that before it was tested.
## Expected Behavior

The tabs are on one line.

![screenshot from 2018-05-30 16-39-03](https://user-images.githubusercontent.com/3524483/40703283-0236d512-6428-11e8-941d-743bb0361a03.png)

## Actual Behavior

The tabs are on two lines.

## Steps to Reproduce

1. Go to any shopfront.

## Animated Gif/Screenshot

![screenshot from 2018-05-30 07-34-56](https://user-images.githubusercontent.com/8135376/40700914-021de7c4-63dc-11e8-8c4a-f6990c0badf7.png)

## Severity

s4 every customer is affected, but it's only a layout issue.

**Comment by oeoeaio** [comment]
I'm working on this now
