### ISSUE TITLE
Add guiding message in "report" section to prevent users panicking when they see no data.

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2356]
## Description
Now that we have removed default loading of data and default filtering, users can be disturbed (panicking even) when the first thing they see is "no data". When working on UX with Rachel we thought it would be good to add a little reassuring message:
![image2](https://user-images.githubusercontent.com/8135376/40926149-cc965962-681b-11e8-93f6-ebe9c001a766.jpg)

## Expected Behavior
The reassuring and guiding message is displayed.

## Actual Behavior
It is not.

## Steps to Reproduce
1. Click on reports and see

**Comment by RachL** [comment]
@myriamboure I completely agree, same opinion as before :)

**Comment by sstead** [comment]
I think this would be nice to have if it's an easy job, I can imagine users getting confused.
