### ISSUE TITLE
Spree 2.0: JS libs not found or not defined

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2359]
## Description

when loading the app's `/` path the libs jquery-ui, I18n and angular can't be found. As a consequence, when clicking on log in no dropdown shows up. The chrome console reports the following errors:

```
all.js:1 Uncaught Error: Sprockets::FileNotFound: couldn't find file 'jquery-ui'
  (in /Users/pau/dev/openfoodnetwork/app/assets/javascripts/darkswarm/all.js.coffee:3)
    at all.js:1
(anonymous) @ all.js:1
(index):21 Uncaught ReferenceError: I18n is not defined
    at (index):21
(anonymous) @ (index):21
(index):87 Uncaught ReferenceError: angular is not defined
    at (index):87
(anonymous) @ (index):87
(index):90 Uncaught ReferenceError: angular is not defined
    at (index):90
(anonymous) @ (index):90
(index):93 Uncaught ReferenceError: angular is not defined
    at (index):93
(anonymous) @ (index):93
(index):96 Uncaught ReferenceError: angular is not defined
    at (index):96
(anonymous) @ (index):96
(index):99 Uncaught ReferenceError: angular is not defined
    at (index):99
(anonymous) @ (index):99
(index):102 Uncaught ReferenceError: angular is not defined
    at (index):102
(anonymous) @ (index):102
(index):105 Uncaught ReferenceError: angular is not defined
    at (index):105
```

## Expected Behavior
When clicking on log in a dropdown should appear.

## Actual Behavior
No dropdown appears.

## Possible Fix

The error related to jquery has to do with the fact that we are now using `jquery-rails (3.0.0)` and `jquery-ui-rails (4.0.5)`, while on `master` we use `jquery-rails (2.2.2)` only. 

In any case, all this is related to the asset pipeline.

**Comment by sauloperez** [comment]
We're still missing I18n and angular

**Comment by HugsDaniel** [comment]
I don't have the error in the console, and I18n and Angular seem to be working fine on my machine on 2-0-stable. @sauloperez did you manage to reproduce the error after my patch ?

**Comment by sauloperez** [comment]
I haven't tried `2-0-stable` lately. If you say it's ok let's close it. We can open it if it happens again.
