### ISSUE TITLE
In OC interface the 'Clear All' button (to clear OC search terms or filters) does nothing

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2362]
## Description
There's a button the OC interface which does nothing- this isn't good for users- can confuse them.

## Expected Behavior
If I'm searching or filtering in the OC interface and i click 'clear all' then my search terms and filters should be removed. 

## Actual Behavior
Nothing happens when you click 'clear all' 

## Steps to Reproduce
1. Login with an enterprise which has OCs
2. Search or filter within the OC listing page.
3. Click 'clear all' - this should clear the filters but it does nothing

## Animated Gif/Screenshot
https://www.useloom.com/share/6e6d2d4512fc4a9799cebbef7b5b9fa3?focus_title=1&muted=1

## Severity
s4

## Your Environment
Aus production
Chrome 
PC

## Possible Fix
Either make the button work, or remove it.

**Comment by adam-conway** [comment]
Hi there 👋. First time contributor here and I think I can get this button working! It doesn't look like anybody is currently assigned to it but if it's already being worked on, please let me know.

**Comment by myriamboure** [comment]
Welcome @adam-conway ! Awesome, go for it, thanks a lot! :+1:

**Comment by myriamboure** [comment]
This is free for someone else to take :-)

**Comment by sigmundpetersen** [comment]
Hi @nikobozi please go ahead! 🙂
