### ISSUE TITLE
Embedded shops aren't working when you go to checkout

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2382]
## Description
I'm able to embed my shop into my own website. However, when i try to place an order in the embedded shop I can't get to the 'edit my cart' or 'checkout' pages. 

## Expected Behavior
I should be able to checkout in the embedded shop

## Actual Behavior
I see a blank screen when i try to checkout in an embedded shop. 

## Steps to Reproduce
1. Go to an embedded shop. here's an example - https://openfoodnetwork.org/user-guide/advanced-features/demo-embedded-shop/
2. Put an item in your cart
3. Click edit your cart or checkout
4. You'll see a blank screen- unable to checkout.

## Animated Gif/Screenshot
https://www.useloom.com/share/77734df7480e41f19708df787942bfcc

## Context
I'm trying to have a functional embedded shop. 

## Severity
S2

## Your Environment
* Version used: 1.16
* Browser name and version: Chrome, PC.

**Comment by kirstenalarsen** [comment]
@myriamboure @Matt-Yorkley @sauloperez we found this when I was again turning my head to what / how bad is the embedded shop mobile situation (i.e. could it be quick fix or we actually need major direction change) . . which is what happened last time I tried to do this e.g. it's not working on mobile because it's not working on desktop! It looks like Black Mountain only closed 2 days ago so surely you would have heard if this was preventing checkouts @Matt-Yorkley ?

**Comment by myriamboure** [comment]
Hum... we have a user who has embedded the shopfront but didn't report any bug either... do you use v1.15.2 in Aus? Or the last master?

**Comment by kirstenalarsen** [comment]
apparently we upgrade to latest master a couple of times a week so i’d say latest master

**Comment by myriamboure** [comment]
So maybe that appeared with something we merged recentely... no idea what it can be, we cannot test embed shopfronts every time we test something...

**Comment by kirstenalarsen** [comment]
maybe we need some more automated testing on embedded shopfronts? or if it’s a known sensitivity point it’s not a bad idea to just check it once a week or so or before a release?

**Comment by Matt-Yorkley** [comment]
I havn't had any reports recently, but I'm not sure when we deployed the last changes with embedded shopfronts. I'm looking into it now...

**Comment by lin-d-hop** [comment]
Uk has had intermittent reports of this. Maybe 3 reports since last deploy. But for each user it was consistent. So likely a specific browser/os/version? Uk is on 1.15.2
