### ISSUE TITLE
When capturing an order from backoffice, if I forget to choose a payment method, I get the snail

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2393]
## Description
As a hub manager when capturing an order from backoffice, if I forget to choose a payment method I get the snail.

## Expected Behavior
If I forget an error message is displayed saying I need to choose a payment method.

## Actual Behavior
Proceed and get the snail failure page.

## Steps to Reproduce
1. Make an order from back office and don't check any payment method

## Animated Gif/Screenshot
https://www.useloom.com/share/4a730b3788bc4f908e510e7648dfd098

## Context
Was testing #2368 

## Severity
S4

## Your Environment
* Version used: branch #2368 on UK staging.
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): desktop

## Possible Fix
Display error message and prevent to go further until a payment method is choosen.

**Comment by lin-d-hop** [comment]
No longer an issue quite in this way. the reality is kind of worse....
Closing #gitcull2021
