### ISSUE TITLE
Have a single feature toggles implementation

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2395]
## Description

Now that we merged https://github.com/openfoodfoundation/openfoodnetwork/pull/2369, we need to combine our two implementations of feature toggles. The one in [app/models/feature_flags.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/feature_flags.rb) with the existing one in [lib/open_food_network/feature_toggle.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/feature_toggle.rb)

**Comment by mkllnk** [comment]
This has changed a bit. We don't have FeatureFlags any more but Flipper is our new source of truth. PR is on its way.
