### ISSUE TITLE
Bulk invoice printing

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2396]
## Original description of the problem this feature is solving
https://community.openfoodnetwork.org/t/enable-quicker-packing-and-invoicing/1412

## Description of the feature including mockups
Hub manage will be able, from orders page, to apply existing filters, select orders on which bulk action will apply, and choose single bulk action "print invoices" to generate in a new tab a PDF to print all corresponding invoices.

This means we are introducing an "actions" button on order page + a new button to change the number of results per page, and we are angularising the page and adding checkbox selector.

Complete mockups are available here:
https://drive.google.com/drive/folders/18RVpnnZgDGYwR6HXOtOhUiG73RtYNmGV?ogsrc=32

Some screenshots:
![image](https://user-images.githubusercontent.com/6525576/45103588-899b4100-b130-11e8-91ff-9ffc2aa06ba9.png)

![image](https://user-images.githubusercontent.com/6525576/45103627-a0da2e80-b130-11e8-9d8c-c2bc777c0980.png)

![image](https://user-images.githubusercontent.com/6525576/43719347-c26a682c-998d-11e8-8840-6e8d5394bdc4.png)

## Story map
_(especially useful until the related issues I created under this epic)_

 1.  Recreate the Spree view without deface overrides #2525
 2.  Angularise the current Orders page (without adding new features). #2526
 3.  Add the "results per page" dropdown and show feedback for results found / results shown. #2527 
 4. Add checkboxes, bulk actions dropdown, and the print invoices bulk action #2510 

## Inception documentation sources
Some discussion happened in issue #2510  on inception so important to check there to understand some of the inception decisions.

**Comment by myriamboure** [comment]
@luisramos0 today we cannot capture delilvery. I know... but we'll reach there step by step. We clarified things after our call this morning and @RachL is opening the epics and issues asap, everything should clarify then ;-) Rachel I let you explain the plan to Luis ;-)

**Comment by RachL** [comment]
So I've updated a bit the list of stories. The idea is to say the order page is the page where we can do bulk actions.
So we would have printing options AND emails options. As I guess we will do separated issue for that, we can say we start with a first release of email and do printing later for example ? @luisramos0 @myriamboure

**Comment by luisramos0** [comment]
I'd start with the most useful to users. I'd guess printing is the most useful.

**Comment by myriamboure** [comment]
Yep cool. Wondering if we need to implement the "send via email" now, or maybe we can keep it for further iterations? Same for delivery notes. If we can generate delivery notes and invoices are based on delivery notes I guess being able to print by batch invoices is enough for now. Let's stick to the priority need and not go further... So @RachL I would limit the scope for now to "print invoices".

**Comment by myriamboure** [comment]
It seems this epic will have only one issue then, it's a bit strange but if it's simple I guess it's ok like that... if you had multiple stories @RachL I would have splitted in multiples issues attached to that epic.

**Comment by RachL** [comment]
@myriamboure why not create all the issue we've spoken of (email, bulk printing...) under this epic and just move the bulk invoice printing issue in the pipe ASAP ? Does an entire epic have to be prioritize to make it through the pipeline ?

**Comment by myriamboure** [comment]
Well actually we have not prioritized the need of introducing bulk actions further than bulk invoice printing so I would only create one issue about filtering and having the action button with only "print invoices" as an option (as we said it was the easiest wait to answer the need to start with). We don't want issues to stand long in Github without a priorization work being done. We only create epics for needs that have been prioritized @RachL. I had originally created that epic but when talking to Kirsten and Sally I think we need to close it (we can reopen later one if this need become a priority) and open a new one with the following the need "hub managers can have easily access to customer based individual packing sheets to quickly prepare the baskets". That's for that need that Aus need bulk invoice printing, people using invoices as packing lists (we were doing that as well when we were running a food hub so I get the point). Among the possible feature candidates we quickly did a brainstorming and said that quick fix would do the job with little efforts. Do you understand the point?

**Comment by Matt-Yorkley** [comment]
I think we should consider that there are probably a lot of bulk actions that would greatly improve the orders UI, so when we implement the bulk action for printing invoices we should do it in a way that will make it easy to add more bulk actions later. 

Has there been an inception session on this, or is there one scheduled?

**Comment by Matt-Yorkley** [comment]
@RachL didn't you have some mockups with checkboxes on each row, and a "select all" checkbox? I think that's a good solution.

**Comment by RachL** [comment]
@Matt-Yorkley Yes that was the original idea, I would also be in favor of checkboxes rather than filters, but I can't remember why in Barcelona we've removed this idea... 
And yes this involves bulkactions in general and how we make bulk actions. I would like a little discussion/inception as I've understood that the topic was not taken in Barcelona at the end. 

@myriamboure if I understand your comments, I should delete this epic?

**Comment by myriamboure** [comment]
Actually @Matt-Yorkley we had a quick inception and wanted to build a quick fix so try to find the solution with minimum work and maximum value added, and adding the checkboxes seemed like a big job. I think we are ok about the feature candidate "enable bulk invoice printing", so if we feel there is a need for another proper inception session to discuss the different ways to implement it on both tech and UX side, I guess we should reschedule a quick time slot, and share the 2-3 options we discussed with @luisramos0 @kirstenalarsen @sstead @RachL. Until know probably we were not enough "transparent" about the inception sessions we were doing, and it was a bit unorganized probably, but we can set up a date and invite all those interested to decide on how we implement the feature. I'm not sure who will be the tech owner on this as @luisramos0 will be moving more to spree upgrade, right?

**Comment by myriamboure** [comment]
Ok so given your input @RachL I think we need to set up an inception session for that. And we should prepare on both tech and UX about how we see that working and different options. Yes I would say that the need is different from the one I orginally identified, and the various solutions I mentioned here are not adapted anymore, it's a different need.

**Comment by Matt-Yorkley** [comment]
That sounds good. I think we need to add an extra filter for the orders page so the user can choose the number of results displayed per page. Currently the page loads about 20 records, and it's not possible to show any more. 

The number of different filters there is already completely crazy, so I was thinking we could show a few of them initially on the page, and put the rest in an "advanced filter options type tab" which the user can choose to show/hide. A bit like on the Order Cycle edit page, where the "advanced settings" tab comes down when you click it. What do you think?

**Comment by myriamboure** [comment]
Yes, cool, but if we have a session when we discuss together synchronously we should invite others who may want to join (open invitation). Else (and anyway) we should share the result of our proposal with the rest of the community to ask feedback/consent, as I did for cookies. For new features it's important to let some space for people to react and consent to avoid having to change it all afterward...

**Comment by Matt-Yorkley** [comment]
Of course! Lets discuss ideas and get some consensus. 

We can look at examples from popular platforms as well on how to handle these UX issues. 

![ui-bulk](https://user-images.githubusercontent.com/9029026/43328410-d2c51c60-91b5-11e8-8b72-3656fe993271.png)

**Comment by RachL** [comment]
@daniellemoorhead You've changed the title of the epic, but actually we wanted to do a larger epic surounding bulk actions... so I guess the title and the content are not correct. Not sure what's best. Delete this epic for now and focus on the issues we've created or do a specific epic for BIP....

**Comment by daniellemoorhead** [comment]
>actually we wanted to do a larger epic surrounding bulk actions

...and yet what was approved by the product curation team was printing only.

Given the scope has changed do we need to take this back to make sure everyone is ok that this is bigger (it is, as a result, yes?) than what was originally added as a feature on the roadmap.

This is another good example for our process discussions @RachL @myriamboure of scope creep/change from what was approved by the product curation team (PCT)...but this change hasn't been reflected back onto the roadmap as different. I have a feeling it's because it wasn't brainstormed from a problem to a need in the first place (it was proposed as bulk printing, a solution, right from the start) and so maybe this won't be a thing that happens moving forward. I'm just not sure how to keep track of decisions like this, if the PCT isn't included when there's such a big scope change...

So, what do we do from here?

**Comment by myriamboure** [comment]
The scope has not changed. I first wrote that epic in line with my understanding of the need (because we were writting epic as needs) which was to enable hub managers to invoice quickly. There were various possible solution to brainstorm. But after discussing with Kirsten and Sally we understood the need was to efficiently pack, and the easiest solution was today to print invoices and use them as packing sheets and them put them in the basket so invoice is then sent as well.

So we have done the need brainstorming @daniellemoorhead but @RachL I think you need rewrite the icebox associated to it or check if we properly clarified the need we identified, the solutions we brainstormed, and why we choose bulk invoice printing as the easiest solution that would add the more value.

So please, let's redo properly the documentation of the work we went through to avoid more confusion... if you don't remember @RachL tell me and we can do it together. SO it's just a documentation issue, but we are clear and aligned!

**Comment by RachL** [comment]
@myriamboure is this the correct icebox : https://community.openfoodnetwork.org/t/make-invoicing-operations-smooth-and-easy-for-hub-managers-and-customers/1200

As now everything is correctly documented on the issue #2510 do we still need the epic ? (it will mostly be a copy / paste)

**Comment by myriamboure** [comment]
@RachL I edited the epic thread and took the content you put in the new issue which was supposed to be the epic ;-) So I'm closing the other one in favor of this one, but there are some important advice on it, especially from Yuko, that we need to take here:
- as there is only one bulk action she recommends to not have a dropdown menu but a direct CTA, like "Print invoices"
- and she recommends that the color of the button changes as soon as one order is selected so that the CTA becomes active and obvious
- she also [recommends on slack ](https://openfoodnetwork.slack.com/archives/CC5CW0AJW/p1535605307000100)regarding @kirstenalarsen comment on left/right side for the button to leave it as you did in your mockups for now and wait for more data.

I think that deserves some precision in the main thread description @RachL, i leave that to you now :-)

**Comment by myriamboure** [comment]
I think you need to clean the screenshots in the main thread @RachL some are the old version with action button above the filter (i think we decided that right?) I would keep only the second one, but wanted to check with you ;-)

**Comment by RachL** [comment]
@myriamboure the mockups and screenshot are up-to-date except for Yuko's comment on action button (which I fully agree on). Where did you saw that something else was decided?
As soon as this is clear I will update with Yuko's comment and then we are good.

Thanks for re-odering stuff, tbh the original epic went too far, so that's why I felt more confident discussing on the last issue to be made as it is easier to start from what we want at the end :)

**Comment by myriamboure** [comment]
@RachL your first mockup show the action button on the top, the second below. So we need to decide to be able to kickoff the implementation.
After our quick discussion on the phone, and taking into account community feedback, here is what we propose the community:
- **We choose the second mockup (on the top message): so the one with action button below the filters, on the right.** Yuko supported button on the right. You're right @kirstenalarsen that on bulk product management, inventory and reports, some action button are below the filters on the left. But a good UX practice is to have the action button on the same position on the page, like all CTA on the right. So we propose to implement that here, and we can then try to get specific data to see if that's fluid for users ;-)
- **Rachel is going to update the mockups with the following small adjustments**:
1- **Replace "Action + dropdown" by "Print invoices" button** as Yuko suggested (we will put a dropdown when we have more actions)
2- **Make the button change color when a first order is selected** to make it clear it's activated and you can click on it.
Is it fine with you @kirstenalarsen ? Or do you want to argue more to keep action button below filters on the left?

**Comment by kirstenalarsen** [comment]
go for it. I agree with Yuko that we should just get on with it and then get feedback later to refine

**Comment by myriamboure** [comment]
ping @RachL we have everything then top adapt the mockups and kickoff!

**Comment by RachL** [comment]
@myriamboure and all: 1. was already made actually, but the screenshots were wrong so I've updated everything again and added 2.

Moving this to dev ready 🎉

**Comment by RachL** [comment]
@Matt-Yorkley tell me when you are ready to pick up, we can make a quit chat to kick-off the dev

**Comment by daniellemoorhead** [comment]
@myriamboure @RachL I would suggest your feature kick off should include more than just @Matt-Yorkley. @sstead is likely to be testing this, and who will be @Matt-Yorkley's back up who can be helping with this work and also taking the lead on code reviews? Perhaps Hugo or Kristina? You'll need to get at least two devs across this so that they can hit the ground running and organise themselves to deliver things :)

**Comment by daniellemoorhead** [comment]
Also, is this our opportunity to try and get some high level estimates so we can attempt to have an understanding of when it might be done?

**Comment by myriamboure** [comment]
We identified a remaining bug when testing the release, so reopen the epic.
