### ISSUE TITLE
Placing orders as superadmin - Customers do not appear in customer list

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#2397]
## Description
When logged in as a superadmin and placing an order on behalf of an enterprise that is placing an order on behalf of a customer, the customer search dropdown does not fetch results for all customers because it is filtered by enterprise permissions, and superadmins don't automatically get those permissions on all enterprises without manually adding them as managers of the enterprise in question.

The feature seems to be working correctly for regular enterprise users when searching customers of enterprises they own.

## Expected Behavior
Results are returned for all customers of the enterprise.

## Actual Behavior
No results are returned.

## Steps to Reproduce
1. Log in as superadmin
2. Create a new order for an enterprise
3. Proceed through steps until adding a customer
4. Customer search dropdown does not return results from all customer lists

## Animated Gif/Screenshot
![screenshot from 2018-06-20 16-13-11](https://user-images.githubusercontent.com/9029026/41667540-21003b36-74a5-11e8-8fb3-a85cb2aa3a73.png)

## Context
Part of bug report in #2354

## Severity
s4. Orders can still be placed in this way, the customer email just needs to be typed in manually instead of being fetched in the search.

## Your Environment
See #2354 

## Possible Fix
Change permissions/scopes for superadmin users using customer search.

**Comment by lin-d-hop** [comment]
No comments since 2018.
Advise not to create orders as superadmin in any case
Closing
#gitcull2021
