### ISSUE TITLE
[Cookies] Implement delete "remember me" cookie when user logs out

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2400]
## Description
Today if a user has checked "remember me" when logging in, the cookie cannot be actively disabled, even if it is an optional cookie. With GDPR we need to change that and give a way for users to disable it. 

- As a: registered user

- I want to be able to do: disable "remember me" cookie.

## Acceptance criteria
If registered user has logged in checking the "remember me" checkbox, remember me cookie is set (current behavior)
If registered user then logs out, remember me cookie is unset (to implement).

**Comment by luisramos0** [comment]
From my simple test right now, this is already the current behaviour. When user logins and checks "remember me", a cookie is set. When user logs out, that cookie is deleted.
In Chrome Dev Tools on tab Application, you can see the cookies that are set to test this.

**Comment by myriamboure** [comment]
@luisramos0 in this comment https://github.com/openfoodfoundation/openfoodnetwork/issues/2240#issuecomment-395612296 @mkllnk said he didn't see any action that would delete the remember me cookie before the 12 days automatic deletion period. So if your test found other results, can you confirm @mkllnk the behavior identified by Luis? In that case you can just close that issue :-)

**Comment by mkllnk** [comment]
I just tested this again in Firefox and get the same result as @luisramos0. The cookie is deleted on logout. Great! Easiest issue ever. :-)
