### ISSUE TITLE
[Cookies] Create cookie policy page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2401]
## Description
Today users are not informed about which cookies are set on their browsers and for what. With GDPR we need to inform them.

- As a: visitor/user

- I want to be able to: understand which cookies are set on my computer and for what (later one: I want to be able to customize and disable optional cookies > see other stories)

## Acceptance criteria
- Create the cookie policy page, content is here: https://docs.google.com/document/d/1sWqXeDZBerXP263w1NWSpsgCuBGCZf35368VKlgPdq0/edit#
- The cookie policy page is always applicable to all instances. 
- Must be translatable. 
-  If instance config is "Matomo" then Matomo cookie section is visible and Google Analytics cookies section is not / if instance config is "GA" then GA section displays and matomo section doesn't 
- The url in "set-by" column vary depending on instance url when entity setting up cookie is instance.
- The cookies policy page is a modal page like the login modal here and accessible through a similar URL, for example /policies/cookies
- It needs to be readable on mobile as well.

See slide 5 https://docs.google.com/presentation/d/1uMWiW6lQhqexAe_uFmjp5QNAM1zLfnIe1bF3-_Nb5xo/edit?ts=5b2be17d#slide=id.g3841ad4459_0_19

**Comment by luisramos0** [comment]
"Analytics cookies section only displays if instance has configured connexion to google analytics in configuration."
Can we skip this for now? This work will be trashed as we move to piwik. Can we just show the analytics cookies info in all instances (even if it's not being used). It feels like a waste of time to implement something that will change soon.

**Comment by myriamboure** [comment]
@luisramos0 as far as France is concerned I would feel pretty uncomfortable to put in our cookie policy that we use analytics cookies as we don't... so let's see what other devs think about Matomo and from than plan if we have some dynamic display depending on instance configuration. We might need to wait to be in Barcelona to decide that though... as Barcelona devs are on holidays and I know they have some opinion on that.

**Comment by luisramos0** [comment]
Marked as blocked, it's dev complete but we will wait for next week (gathering) to make a decision about analytics.

**Comment by myriamboure** [comment]
Hey @luisramos0 ! Do you agree with the new content page with the decision we took to use Saas version of Matomo to start with ? https://docs.google.com/document/d/1sWqXeDZBerXP263w1NWSpsgCuBGCZf35368VKlgPdq0/edit# I was not sure about which matomo cookies we would use and what they are for, so please update the text if that makes sense! I'm going through the issues to see what is gonna change now.

**Comment by luisramos0** [comment]
Screenshot of the new cookies policy page:
<img width="1234" alt="screen shot 2018-07-20 at 17 32 28" src="https://user-images.githubusercontent.com/1640378/43014090-f1b219de-8c42-11e8-8f09-88f5396862e0.png">

**Comment by daniellemoorhead** [comment]
Given this was delivered by #2411 can this issue be closed @luisramos0?

**Comment by daniellemoorhead** [comment]
Actually, I see from the (long) conversation on #2411 that you're waiting for @myriamboure to return and wrap up all the issues associated with that PR. So pretend I didn't write that previous comment 😉 

![Alt Text](http://memecrunch.com/meme/BF8DP/nothing-to-see-here/image.gif)

**Comment by luisramos0** [comment]
ahaha. some  serious gif action here :-)
