### ISSUE TITLE
[cookies] Add footer link to access the cookie policy page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2402]
## Description
Today users are not informed about which cookies are set on their browsers and for what. With GDPR we need to inform them. So now that the cookie policy page is created we need to give users access to it.

- As a: visitor/user

- I want to be able to: understand which cookies are set on my computer and for what (later one: I want to be able to customize and disable optional cookies > see other stories)

## Acceptance criteria
- In footer on all app pages I can access the cookie policy via a dedicated link.
- When click on link, opens page in same tab. User can just click on any menu again to access other sections.

See slide 4 https://docs.google.com/presentation/d/1uMWiW6lQhqexAe_uFmjp5QNAM1zLfnIe1bF3-_Nb5xo/edit?ts=5b2be17d#slide=id.g3c59fe849e_0_6

**Comment by luisramos0** [comment]
Marked as blocked, it's dev complete but we will wait for next week (gathering) to make a decision about analytics.
