### ISSUE TITLE
[Cookies] Add privacy policy URL and display in footer

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2406]
## Description
Today users are not informed about the privacy policy whose cookie policy is a part of. With GDPR we need to inform them. So we need to allow access to privacy policy as well as cookie policy.

As a: visitor/user

I want to be able to: understand the privacy policy of OFN more generally, into which cookie policy happens.

## Acceptance criteria

- Add in configuration panel the possibility to link a “privacy policy” PDF setup at instance level (optional)
- Add in the footer link to access the privacy policy (if not url set up for the instance it should not appear)

See slide 4 and 10 https://docs.google.com/presentation/d/1uMWiW6lQhqexAe_uFmjp5QNAM1zLfnIe1bF3-_Nb5xo/edit?ts=5b2be17d#slide=id.g3c59fe849e_0_6

**Comment by luisramos0** [comment]
Hi @myriamboure 
I was looking at the configuration page, theres a entry for "TOS required", section "ENTERPRISE TERMS OF SERVICE". Shall we merge this one entry with cookies toggle and privacy URL and call the section "Legal Settings"? It would simplify the screen a little bit.

I suggest:
- Rename Section "ENTERPRISE TERMS OF SERVICE" to "LEGAL SETTINGS"
- Add in this section to the existing "ENTERPRISES MUST ACCEPT TERMS OF SERVICE", "Cookies Toogle" and "Private URL" field.

**Comment by luisramos0** [comment]
I've just found the "terms of service URL" field in the content configuration page...
We should either move the "privacy URL" to the content configuration page or move the "terms of service URL" to the global configuration page. You guys choose? :-)

**Comment by myriamboure** [comment]
I like what you are proposing @luisramos0 ! Let's go for it put it under "legal settings"
Good idea to bring the terms of services URL to legal settings as well I would say (IMO), I propose to put that under "general configuration" page for now, maybe if it starts to get busier that we can move some part in new sub menu but we start to have quite a lot already so let's keep it in general settings for now.

**Comment by luisramos0** [comment]
This is the current legal settings screen:
<img width="384" alt="screen shot 2018-06-29 at 14 25 56" src="https://user-images.githubusercontent.com/1640378/42094665-64ce7ca6-7ba8-11e8-8c69-663955a4421a.png">

**Comment by luisramos0** [comment]
Latest view on the screen with flexible analytics parts on the policy page. The checkboxes will show/hide the Analytics parts on the policy page:

<img width="374" alt="screen shot 2018-07-27 at 10 38 52" src="https://user-images.githubusercontent.com/1640378/43313927-52b37c00-9189-11e8-8b87-f7458ee4d6da.png">

<img width="744" alt="screen shot 2018-07-27 at 10 38 21" src="https://user-images.githubusercontent.com/1640378/43313913-4906791e-9189-11e8-8961-137329947811.png">

<img width="740" alt="screen shot 2018-07-27 at 10 38 27" src="https://user-images.githubusercontent.com/1640378/43313932-5651c3a8-9189-11e8-85ec-dfcac8d1b89f.png">
