### ISSUE TITLE
[Cookies] Build coookie banner and add a toggle to power it on-off

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2407]
## Description
Today users are not informed about the cookies set up on their computer and don't give their consent. With GDPR we need to inform them and request their consent. The content of the cookie policy page and set up options is still pending as we need some more info to decide but we can move forward with implementing the consent banner (it can remain toggled off until the feature is ready to be released).

As a: visitor/user

I want to be able to: be notified that cookies are used and be requested my consent, and check cookie policy if I want to understand.

## Acceptance criteria

- A banner is displayed on desktop and mobile with following text, link to cookie policy, and button to "accept cookies"
![screenshot from 2018-06-26 12-50-46](https://user-images.githubusercontent.com/8135376/41907135-3e521548-7940-11e8-95f1-29cc83b1a694.png)
![screenshot from 2018-06-26 12-50-32](https://user-images.githubusercontent.com/8135376/41907139-4162e56e-7940-11e8-81f8-3d383c8f6c10.png)

- This banner is by default toggled off but can be toggled on from admin > configuration (See slide 10 https://docs.google.com/presentation/d/1uMWiW6lQhqexAe_uFmjp5QNAM1zLfnIe1bF3-_Nb5xo/edit?ts=5b2be17d#slide=id.g3c59fe849e_0_6). Updated: Even if the banner is toggled off the cookies policy link on the footer of the website should still be shown.

- Technically all essential cookies are set up as soon as user either click on "accept cookies" or start navigating on the website (so if clicks on any other menu).

NOTE: Analytics cookies are out of scope for now. Missing informations to decide on them still.

**Comment by myriamboure** [comment]
I put a little bit more text @luisramos0 so that users are incited to click on "accept cookies" and know that if they don't click on "accept" but navigate they do consent. All clear? @RachL does it looks good to you as well?

**Comment by RachL** [comment]
@myriamboure perfect !

**Comment by luisramos0** [comment]
This is what I have so far:
<img width="1075" alt="screen shot 2018-06-27 at 17 26 38" src="https://user-images.githubusercontent.com/1640378/41986849-5116841c-7a2f-11e8-86d9-911331139b3f.png">
and
<img width="266" alt="screen shot 2018-06-27 at 17 34 36" src="https://user-images.githubusercontent.com/1640378/41987210-6459830c-7a30-11e8-9124-eb759fd8f885.png">

**Comment by myriamboure** [comment]
Looks good @luisramos0 ! :-)
