### ISSUE TITLE
Enable instances to add menus in the main header (with redirects)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2410]
## Description
Given conversation in Slack https://openfoodnetwork.slack.com/archives/C0DNLAZC7/p1529691706000289 there is a lazy consent to do a proper implementation of "adding more menu headers with redirects" feature to avoid a hack more and more instance are doing.

## Expected Behavior
Instance can add more menus headers in the top menu of an OFN website menu

## Actual Behavior
Hack done for example in UK (but also Aus): See here for the code changes commit in the UK
https://github.com/openfoodfoundation/openfoodnetwork/commit/90d5a04368e229fc849a386b91d3284dd893702d
And then you need to create config/initializers/feature_toggle.rb and add the appropriate code to enable it. UK example is: 

require 'open_food_network/feature_toggle'

module OpenFoodNetwork
 FeatureToggle.class_eval do
   private

   def self.features
     {order_cycles: true,
      about_blog_homepage: true}
   end
 end
end

## Context
Now France is willing to do the same so again the hack need is happening, as it's a quick fix we propose to do it properly.

## Possible Fix
Add some backoffice fields that, if you fill in with URL, you get the menu on your instance.

UPDATE Luis 8/8/2018:
The feature implemented includes 7 new translation pairs (title and url) for each menu entry and then a checkbox on the Content configuration to enable/disable these menu entries. The mobile menu icons can also be defined in the content configuration (see screenshots below).

What needs to be tested:
- we need to set a few variation son the translations files and then activate/deactivate different menu entries and see if both large menu and mobile menu work properly with different type of links.

**Comment by lin-d-hop** [comment]
Please note that the existing implementations are:
UK: About, Blog, Support
Aus: Connect, Learn (they have taken About off)

This will need to work for both existing implementations.

**Comment by luisramos0** [comment]
I think the best solution here is to let each menu entry be enabled/disabled and include a URL field for the ones that can have custom URLs.
Note: the URL config fields themselves cannot be used to toggle menu because "about" and "groups", for example, are used in the footer as well. For these ones, a URL is always necessary but the entry is in the menu only for some instances.
So, this would be my suggestion for the screen :

<img width="600" alt="screen shot 2018-06-29 at 22 39 31" src="https://user-images.githubusercontent.com/1640378/42116008-5d740008-7bed-11e8-9178-bf4f4df55f08.png">

AU config would be:
<img width="603" alt="screen shot 2018-06-29 at 22 44 49" src="https://user-images.githubusercontent.com/1640378/42116307-91c3b352-7bee-11e8-9705-b089408994ba.png">

UK config would be:
<img width="604" alt="screen shot 2018-06-29 at 22 45 47" src="https://user-images.githubusercontent.com/1640378/42116321-9e2ae1f6-7bee-11e8-8a44-7d6a066c4551.png">

Generic config would be:
<img width="602" alt="screen shot 2018-06-29 at 22 46 26" src="https://user-images.githubusercontent.com/1640378/42116337-b0c8c152-7bee-11e8-9fbd-4c92125b798f.png">

FR config would be:
<img width="609" alt="screen shot 2018-06-29 at 22 47 31" src="https://user-images.githubusercontent.com/1640378/42116344-bdd65ab2-7bee-11e8-9072-25932aaa8a6a.png">

I am happy to do something completely different, just let me know. This is all very easy to implement. Rails+Spree at it's best really.

**Comment by myriamboure** [comment]
@mkllnk @lin-d-hop what do you think about it? What I like with that solution is that the menu headers can be translated through Transifex as well so multilingual would work. It might not answer our later needs but it does the job for now. Don't you think? Can @luisramos0 move forward with that solution? Else do you have another idea?

**Comment by Matt-Yorkley** [comment]
We nned to set both the url and the link text, which is 2 fields, right? Hmmm... I'm not sure how well that would work with multilingual instances. If an instances has three languages, how would this UI work? Or do we just have a Transifex key for each link title? What if a different link was needed per language and per instance?

**Comment by lin-d-hop** [comment]
@luisramos0 @myriamboure I think that this system will also be hacked such that people can call the menu headers whatever they like in Transifex. So I wonder why specify 'About' 'Learn' 'Connect' 'Blog' 'Support' etc at all? Why not just put a maximum number of fields that users could assign whatever Label and URL they want?
Eg Repeat the following field options 7 times
Menu Label:
URL: 

My main concern with this solution is that a user could add EVERY field and that would have rendering consequences. 

@Matt-Yorkley The case in which a user wants the link to link for a different URL for a different language has yet to arise. Sounds like you are over-engineering at this point to me.

**Comment by myriamboure** [comment]
@lin-d-hop I thought about it but then realized with this proposal we cannot translate the menu header, which is a problem if multilingual is enabled in your instance (not talking about the url translation...). That's why I thought Luis solution was an easy fix for our current need. Just taking the existing tabs used with their English translation, so that we can then translate them in Transifex and change the url behind them in configuration... An instance will never enable all the tabs as the app would look horrible... the instance manager will quickly realize they shouldn't do that... just looking for quick fix easy to implement. @mkllnk what do you think?

**Comment by Matt-Yorkley** [comment]
From experience I can say you'd be absolutely amazed by how horrible people will make a site look in order to squeeze random things they want into a menu.

**Comment by myriamboure** [comment]
Ok, I can hear that. So does anyone has another quick fix solution that enable us to not loose the translatability of the header menus?

**Comment by Matt-Yorkley** [comment]
I didn't mean to slow things down with my interjections, just bouncing some ideas around. UK is very keen for a solution to this, even if its a basic one.

**Comment by lin-d-hop** [comment]
I think we can think of a way to do this while being able to translate.
We could have 7 holders and label them as such:
Menu 1: [MenuTitle1]
URL Input: 
Enable Checkbox:

Menu 2: [MenuTitle2]
URL Input:
Enable Checkbox:

So the [MenuTitle]s are not input fields, but in-app text which acts as a holder and can then be translated in the input file. In the en.yml file we would see:
menuTitle1: Shop
menuTitle2: Maps
menuTitle3: Producers
menuTitle4: Connect
menuTitle5: Learn

Sorry to not make mocks. I hope that makes sense.

**Comment by mkllnk** [comment]
Another quick fix idea: You can place localised views on the server to load different content: http://guides.rubyonrails.org/i18n.html#localized-views
There are four views affected though:

```sh
git grep label_connect -- app/views/
#app/views/home/_connect.html.haml:      %h2= t :label_connect
#app/views/shared/_connect_learn_call.html.haml:      = link_to t(:label_connect), "https://openfoodnetwork.org/au/connect/", target: '_blank'
#app/views/shared/menu/_large_menu.html.haml:              = t 'label_connect'
#app/views/shared/menu/_mobile_menu.html.haml:            = t 'label_connect'
```

The real solution will be multilingual phase 2: make database fields translatable.

**Comment by luisramos0** [comment]
Hey, thanks for the feedback!
@mkllnk I didnt know about localized views. Interesting. I am not sure I want to go that way just for this fix....
@lin-d-hop thanks for your proposal! The only advantage of my solution is that it forces people to keep the menu similar across instances.

None of the options solves the problem of translatable URLs: I just realized the translatable menus is a problem for Portugal. For example, Katuma's portuguese version cannot just point to katuma.org in Catalan as it is right now...

What if we put the URLs on the en.yml file as well @lin-d-hop ?
In the backoffice you would just enable/disable them.

We could have 7 holders and label them as such:
[MenuTitle1]: [MenuURL1]
Enable Checkbox:
[MenuTitle2]: [MenuURL2]
Enable Checkbox:
etc.

In the en.yml file we would see:
menuTitle1: Shop
menuURL1: /shops
menuTitle2: Maps
menuURL2: /maps
menuTitle3: About
menuURL3: /about_EN.html
etc

**Comment by myriamboure** [comment]
I'm not tech but that sounds cool @luisramos0 ! Would solve the redirections multilingual issues! What do you think @mkllnk @lin-d-hop @Matt-Yorkley ?

**Comment by Matt-Yorkley** [comment]
Actually there's another issue, but maybe it's one for `ofn-install`. If each menu item has a checkbox to activate we'll have to set some defaults for which ones are checked, and also have a way for instances to set their (non-default) preferences for each one...

**Comment by mkllnk** [comment]
It's not great, but pragmatic. I wish we had time for a better solution.

**Comment by luisramos0** [comment]
@Matt-Yorkley I am not sure I understand the problem you mention. I can just set the defaults in the code. After the install (which happens once for each instance), all a instance manager has to do is to go to the backoffice and set the menu they want with the checkboxes. Right?

**Comment by sauloperez** [comment]
I agree with @mkllnk. I feel like in the rush to fix this individual problem, we're increasing a lot the complexity of the UI for something that looks more like low-level configuration to me. It looks to me as if we were implementing WordPress: everything can be controlled by the UI and that's not the most maintainable approach.

I hope one day we can sit and go through the pros and cons and find better solutions.

**Comment by luisramos0** [comment]
I am not sure I understand your point @sauloperez.
I feel the solution is kind of simple and gives the users quite a lot of flexibility to configure their menu.

>> It feels like we were implementing WordPress
I think that is good! The website will be an CMS one day. It should be configurable by users/managers as much as possible.

**Comment by myriamboure** [comment]
Ok so let's move forward? It seems there is kind of a lazy (not 100% happy but still) consent? if there is still any objection please raise your voice, else let's do it!

**Comment by luisramos0** [comment]
thanks @myriamboure I think there is consent and we can move forward (I may have some time for this today) but I would like to understand what @sauloperez and @mkllnk are not happy about. If I understand maybe I can make it more aligned with what they think.

**Comment by Matt-Yorkley** [comment]
I don't think we're "building Wordpress" here, we're cleaning up an issue that has resulted in 3 different instances using custom hacks to control their navigation links in a disorganised way (that currently  complicates deployments). 

There's some complexity with multilingual and different links per language, and I think we're handling that with some fairly reasonable config options.

@luisramos0 I just meant that after this feature is in place and the config options are there, we could create a corresponding part in ofn-install so that instances can set up their chosen menu configuration by defining a couple of variables in their config files instead of logging in and clicking the options manually.

**Comment by luisramos0** [comment]
ok, done.

In the en.yml file:
<img width="398" alt="screen shot 2018-08-08 at 22 34 42" src="https://user-images.githubusercontent.com/1640378/43865790-78544468-9b5b-11e8-9e16-b4008a5aa961.png">

In the Backoffice:
<img width="576" alt="screen shot 2018-08-08 at 22 34 55" src="https://user-images.githubusercontent.com/1640378/43865798-831dab14-9b5b-11e8-9953-33649d401a66.png">

In the Frontoffice large menu:
<img width="811" alt="screen shot 2018-08-08 at 22 35 39" src="https://user-images.githubusercontent.com/1640378/43865824-9fb00628-9b5b-11e8-8a08-c1ed3c77be03.png">

In the Frontoffice mobile menu:
<img width="384" alt="screen shot 2018-08-08 at 22 35 59" src="https://user-images.githubusercontent.com/1640378/43865879-c512f114-9b5b-11e8-826d-820fdb059b09.png">

I decided to add the mobile menu icons to the content config, I couldn't find another better/easier/faster solution for this.

I took anone little decision, let me know if you want to change: on the mobile menu, we list the available locales if there is more than one (only applicable to KATUMA today as far as I see). These languages were listed _between_ the basic menu (shops/map/producers) and the extended "feature toggled" menus. To make my life easier and the code simpler, I moved these locales to the end of all (max 7) menu entries.

Ready for code review. Let me know if you have any questions.

**Comment by daniellemoorhead** [comment]
@myriamboure @luisramos0 there was an oversight in this issue - the footer displays the top navigation links as well

![screen shot 2018-08-31 at 1 26 25 pm](https://user-images.githubusercontent.com/10949052/44891252-a21aee00-ad21-11e8-9adb-d4da8743963f.png)

The footer menu is hard coded I think. So what you have in the top menu won't reflect in the footer. Not a big issue, but worth noting just in case you want to create an issue (bug?) for this gap.

**Comment by myriamboure** [comment]
@daniellemoorhead The links behind them and related translations remain valid, am I right @luisramos0 ? I'm not sure we need to have again another same navigation in footer and header, what's the point? Shall we just remove completely the header-menu-duplicate from the footer? @RachL what is your UX thought on it? @kirstenalarsen @sstead what was the point for that decision originally? In Aus do you have a different header and footer already? I think it is the case with the hack you were doing. So I see two options:
- leave as is, so even if header menu change, leave those as footer
- remove them
Thoughts?

**Comment by luisramos0** [comment]
Yes, the footer remains the same, it was not adapting to the menu with the previous feature toggle and now it is not adapting.
The links will always work as /shops /map /producers /groups are static. And the footer_about_url is still there on the backoffice to be configured.

**Comment by myriamboure** [comment]
It's good for me that it remains as is, was already the case, and not a priority to tackle.
