### ISSUE TITLE
Translation missing in order cycle page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#2414]
## Description
Some translations are missing here :
![image](https://user-images.githubusercontent.com/6525576/42028742-704627c2-7acd-11e8-88f4-c4fa36488178.png)

## Steps to Reproduce
Go to order cycle page : /admin/order_cycles

## Context
A French user reported it. 

## Severity
S4

## Your Environment
* Version used: v1.15.2

**Comment by daniellemoorhead** [comment]
Hey @RachL @myriamboure @HugsDaniel who looks after these kind of translation problems that are found in France? Is there a process to ensure that translation issues are quickly fixed? This seems pretty important for non-english speaking countries using the platform...

**Comment by myriamboure** [comment]
@daniellemoorhead as discussed this morning we need some process, but for now we use them as good first issues to onboard new contributors, that helps them understand the Transifex logic and internationalization issues.

**Comment by kristinalim** [comment]
Noting here that this has been addressed in #2659, #2661, #2671 It so happens that the nature of the translation issues are different, so although simple, I separated the PRs in case some might get merged quicker than the others.
