### ISSUE TITLE
[Stripe] Improve the user experience of CVC and Date Field

### ISSUE THREAD

**Issue by wmortada** [openfoodfoundation/openfoodnetwork#2418]
The user experience for the Stripe payment form could be improved.

## Description
The Stripe payment form prompts users to input 'CVC' but doesn't explain what CVC is.  I don't think this is a good user experience and may confuse people who are unfamiliar with making payment online.

It also prompts users to input 'MM / YY' but doesn't explain that this is the expiry date for the card.  I think most people will be able to guess that this expects the expiry date but this isn't explicit and again could be confusing for people who are unfamiliar with making online payments.

I imagine that the majority of customers won't have an issue with this.  However, I think that OFN should try to be as inclusive and accessible as possible.  A minor change here could make a big difference to the usability of this form.

## Expected Behavior
The Stripe payment form should explain what CVC means.  It should also explain that it expects the expiry date in the field marked 'MM / YY'.

## Actual Behavior
The Stripe payment form prompts the user to input the following information:

- Card Number
- MM / YY
- CVC

It doesn't provide any clarification that it expects the card expiry date in the second field or explain what CVC means.

## Steps to Reproduce
1. Select an item from a shop
2. Go to checkout
3. Select to pay by credit or debit card (via Stripe)

## Screenshot
![screenshot-2018-6-29 checkout](https://user-images.githubusercontent.com/13518928/42090440-63de4eac-7b99-11e8-80a9-00c3cfa9a968.png)

## Context
This bug affects any shop that offers Stripe as a payment method.

## Severity
S4 - May prevent some users from completing checkout.

## Your Environment
* Version used: Current UK version
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu Linux desktop

## Possible Fix
A possible solution to this would be to provide some help text that explains what 'MM / YY' and 'CVC' mean.  

For example:

- MM / YY = card expiry date
- CVC = Card Verification Code - for most cards this is the final three digits on the back of your card (on American Express cards, it is usually a four digit code on the front)

**Comment by myriamboure** [comment]
And I would suggest as well we separate the fieds (what @luisramos0 started as a first attempt) as we encountered some not so user friendy effect when typing the card number in IOS figured were overlapping with MM/YY.
 Also with different fields it is easiers to add tolltips after each field separately.

**Comment by lin-d-hop** [comment]
Closing as users are not reporting this problem.
