### ISSUE TITLE
The customer's view of an order 'in credit' isn't clear or consistent

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2423]
## Description
Found while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2273 .
As a customer who has an order with payment state 'in credit' (e.g. I paid $40, but one item was then removed from my order, so I've now overpaid by $10), the view on the /account tabs don't make sense.

## Expected Behavior
If I have an order with credit I should be able to see this. 

## Actual Behavior
If I have an order with credit, in certain places on the /account page I'm told the order is not paid, which is not the case. In fact the order is overpaid.

## Steps to Reproduce
1. Place an order as a customer
2. As the shop manager mark that order as paid. 
3. Then as the shop manager remove an item from that order to reduce the total value. This will put the order into a 'credit' state.
4. View the /account page as the customer and look at the order in the 'orders' tab and look at the order confirmation page. You'll see the order marked as not paid. Then go to the /account 'transaction history' tab and see how the credit is correctly recorded here.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/10843056/42207788-1d857496-7eee-11e8-8858-ddd9a354fb54.png)

## Context
If /account is to be useful it needs to accurately and consistently reflect the payment state of orders.

## Severity
S3

## Your Environment
PC, Chrome, staging1.openfood.com.au

## Possible Fix
On the orders page and the confirmation email either mark the payment state as 'Paid' , or 'In credit'- either of these options is more accurate than 'not paid'.

**Comment by lin-d-hop** [comment]
This is being incepted and prioritised here:
https://community.openfoodnetwork.org/t/enable-customers-to-pay-partially-or-fully-with-their-credits/1211
