### ISSUE TITLE
[Cookies] Document technical choices in wiki

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2427]
Create some documentation around the matomo config we are doing right now. In the wiki probably best place (to check).

**Comment by luisramos0** [comment]
Hi @myriamboure I am sorry but I cant recall what was this issue for.
Is this related to creating documentation around best practices like this?https://github.com/openfoodfoundation/openfoodnetwork/wiki/Code,-the-way-we-do-things

**Comment by myriamboure** [comment]
@luisramos0 from my understanding it was to check if there needs to be any wiki update linked to the new feature, so you will for instance add a page on Matomo configuration maybe for new instances who join the OFN and want to get their data analysis? Also I think from the discussion we had with @Matt-Yorkley for product import he was talking about adding some class documentation comments...  I have another issue to do the same on user guide and superadmin handbooks which are more "product oriented", so yours is more about tech documentation. @mkllnk if you see more precisely what documentation should be added on the tech side please let us know.

**Comment by luisramos0** [comment]
ok!
thanks for reminding me that I should create some documentation around the matomo config we are doing right now! I'll add that to my todo list re matomo config issue.

**Comment by mkllnk** [comment]
On the ofn-install project we often add a checklist of wiki changes to each pull request. That is very helpful. Maybe we should add that to our pull request template.

**Comment by mkllnk** [comment]
Okay, I updated the issue and pull request templates.

**Comment by daniellemoorhead** [comment]
@myriamboure @luisramos0 can we close this issue? Did you already do this documentation Luis?

**Comment by myriamboure** [comment]
I don't think so @daniellemoorhead this remain to be done from my understanding.

**Comment by luisramos0** [comment]
Here's the wiki page:
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Matomo-Integration

I think this is enough. What do you think?

Moving issue to test ready.

**Comment by mkllnk** [comment]
I thought the issue was more about why you did certain implementation decisions. But I'm happy with it. Should there be something in the user guide?

**Comment by luisramos0** [comment]
Yeah, this is more of a user guide, isnt it?
I dont think we need any technical documentation here. It's all rather straight forward.

**Comment by myriamboure** [comment]
I guess what you wrote @luisramos0 yes is more for a super-admin handbook, how to setup matomo in OFN, and how to configurate it to get usefull data (which I have not yet understood, will be next step I guess!). So it's more on my task when all the other last bits of implementation are done. I too the content of your suggestion Luis as a base. So if no need for more technical implementation documentation for next devs to understand what was done, we can close that. I let you judge on that, I'm not reading the tech documentations ;-)

**Comment by daniellemoorhead** [comment]
>So if no need for more technical implementation documentation for next devs to understand what was done, we can close that. I let you judge on that, I'm not reading the tech documentations ;-)

Given the above comment by @myriamboure can this be closed @luisramos0?

**Comment by luisramos0** [comment]
yes, I think we can close, I dont think there's much tech details I can add here.
