### ISSUE TITLE
[Cookies] Document feature use in super admin handbook gitbook

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2428]
As an instance super admin, I can easily set up and use Matomo, and get valuable data to drive the solution design and decisions.

Acceptance criteria: the process to setup and use properly matomo is documented on the super admin handbook: https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/

**Comment by daniellemoorhead** [comment]
Hey @myriamboure I'm not sure what this is for? I assume the template isn't filled in because it's not a code change and more an implementation task?

**Comment by myriamboure** [comment]
Yes @daniellemoorhead just opened an issue so that we don't forget to do it before considering the feature as done... So it's basically just a reminder, but this will be one of the last task we will work on in the epic I guess.

**Comment by myriamboure** [comment]
@RachL as soon as we have done the upgrade in France and you are setting up Matomo for the French instance, can you document step by step what you do in the super admin handbook https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ with some beautifyl screenshots ? It would be good especially to give some recommendation and agree on good practices about how we set it up to have comparable data from every instances... thank youuuuu! <:)

**Comment by myriamboure** [comment]
It is great @RachL awesome ! I have just changed the first sentence to explain a bit why we chose Matomo. Else I didn't change anything, it's perfect for me ! Let's close that issue then and consider this feature as fulllly done ! :smiley:
