### ISSUE TITLE
Fix spacing around page of edit account when error message returned

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2429]
## Description
In account / account settings, if user puts in an invalid email then when the page returns (with error message) the margins are lost

## Expected Behavior
Margins as per Account settings
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/7bf38e7f-5274-472b-8035-90dfe3a763e5)

## Actual Behavior
margins disappeared

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/0f00d453-d37a-4b00-9d20-35bc1f4f7929)

## Steps to Reproduce
login, go to account, account settings
change email to something invalid e.g. remove .com or '@'
hit enter

## Your Environment

Mac chrome, android chrome

**Comment by myriamboure** [comment]
Which severity is that bug @kirstenalarsen ? I put s4 as front end but not super annoying... change it if you disagree.

**Comment by kirstenalarsen** [comment]
even lower - was first one i did when working through mobile ux issues, before deciding that putting them back in gh not best approach. will post update on where i have got to shortly

**Comment by haseleyi** [comment]
Note: To reproduce, I needed a window that wasn't maximized
