### ISSUE TITLE
Make OC name field editable from OC index

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2430]
When a user comes along to create a series of OCs to set up their subscription schedule, they need to basically replicate the same thing over and over again, but with different dates and OC name.

A tiny change would make this infinitely easier - **make the name editable from the OC Index / overview page.** Then I can set up one, hit clone as many times as I like, and update the names and open / close times without having to open / edit each order cycle itself (very time consuming) 

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/b23a1b9c-c8c2-4869-b792-0141579ebdae)

See also #2463 #2439 for related issues 

I think that this, combined with #2439 is a more elegant and simple solution than #1052 as it means user doesn't need to open each order cycle

**Comment by kirstenalarsen** [comment]
also just realised that cloning doesn't keep the schedule - annoying. Can that be editable from Index page too?

**Comment by myriamboure** [comment]
I would say that cloning should keep the schedule this is what you expect as a user, so this is a remaining bug for me. Not preventing release but will need to be fixed.
The feature you propose is not related to subscription, but more generally to make OC creation by duplicate easier. I agree if would improve enterprise manager UX and if not hard would vote to do it now.

**Comment by myriamboure** [comment]
Those are two seperate issues, can you separate them @kirstenalarsen so we don't get confused in working on them?

**Comment by kirstenalarsen** [comment]
Cloning to include schedule now in https://github.com/openfoodfoundation/openfoodnetwork/issues/2439

**Comment by myriamboure** [comment]
@kirstenalarsen I don't think this should be part of release plan of subscription. This should be part of another "unmet need" which would be "make order cycle duplication easier for hub managers". I would suggest we take it out of subscription epic, it is another focus point IMO and subscription doesn't need that to be fully released. I took the liberty to rename ;-)
