### ISSUE TITLE
[Spree 2 Upgrade] Refactor Order#shipping_method in checkout flow

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2432]
## Description

The customization we added in the payment step of the checkout flow relies on `Order#shipping_method` which is gone in Spree 2.0. Therefore, this logic needs to be refactored to work on that Spree version.

https://github.com/openfoodfoundation/openfoodnetwork/blob/09534b41e9a806daf91c5633d0b03e009e297b30/app/models/spree/order_decorator.rb#L33-L42

**Comment by sauloperez** [comment]
We need to check the status of this issue now that we got https://github.com/openfoodfoundation/openfoodnetwork/pull/2431

**Comment by luisramos0** [comment]
I am going to close this issue as the main problem in its description (the checkout workflow) is superbly fixed with the beautiful (and simple!) #2431 
I have created #2683 which will handle the rest of the problem. I'll describe my understanding of what needs to be done in #2683
