### ISSUE TITLE
Spree Upgrade - Remove dependency to Dash in Spree

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2434]
## Description
Dash has been removed from Spree in 2.0
See what we are using it for and remove dependency.

See spec/features/admin/Overview_spec:116 with_dash_configured

Interesting reference: https://www.quora.com/What-happened-to-Jirafe-analytics

## Expected Behavior
Pass the referenced test.

## Actual Behavior
Test fails.

## Steps to Reproduce
Run build.

## Your Environment
spree branch

## Possible Fix
Maybe remove it. Is it necessary?

**Comment by luisramos0** [comment]
is this issue now closed with the closed PR?

**Comment by daniellemoorhead** [comment]
Closing this as PR #2488 is merged. @HugsDaniel feel free to reopen this if all the work isn't yet done.
