### ISSUE TITLE
[Spree Upgrade] Spree 2.0 removes on_demand property from  Product and Variant

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#2435]
## Description

`on_demand` is removed from Product and Variant in these 2 PRs for Spree 2.0:

https://github.com/spree/spree/commit/40665ab244277138801ee278f663fd2f6da7da22#diff-c1dfa6db7daf5dcbf0bf6caad4024294
https://github.com/spree/spree/commit/14a398cd3625a1ef7173c1661d7013d51ea92446#diff-c1dfa6db7daf5dcbf0bf6caad4024294

There are 81 mentions of `on_demand` throughout our app folder. 

I think our users regularly use this option for product stock. 

## Expected Behavior

Products can be set to `on_demand`.

## Actual Behavior

It's gone in 2.0!

## Animated Gif/Screenshot

![shrug-gif](https://media.giphy.com/media/13NUOwOLq0NJug/200w_d.gif) 

## Context

Spree Upgrade.

**Comment by Matt-Yorkley** [comment]
This will need a bit of a spike, but after some discussions there was a mention of a solution where we allow backorders on items. This will probably need to include looking at our current use of the `allow_backorders` config setting and the previous issues relating to it. I can't remember if it is just a large number of specs that depend on it being turned off, or whether or not some of our customisations make it unusable.

https://github.com/openfoodfoundation/openfoodnetwork/search?q=allow+backorders&type=Issues

**Comment by Matt-Yorkley** [comment]
Thanks @daniellemoorhead, this was just here to document it as a reminder. Yes it can be filed under "all the Spree upgrade things". I think it will be covered in the new plans to keep the existing API in terms of models/methods.

**Comment by luisramos0** [comment]
Useful conversation: https://github.com/spree/spree/commit/1ca45b826934d345c0e39dfebe9a707f649ea2ab
From what I have seen, it has not come back since then.
From this conversation here looks like we need to use backorders instead:
https://groups.google.com/forum/#!topic/spree-user/kUHJljlN2hQ

**Comment by myriamboure** [comment]
I don't really care about the use of backlorders in replacement of on_demand, but what I care for is the UX, as most users actually do check the box "on demand" on product as they don't manage stock levels within OFN.
My concern is that today backorder is setup at instance level, whereas every hub, for every product, should be able to decide if their customer can order more than stocked / order as much as they want without specified stock info. So the "allow backorder" info should be at product level. Is it the case?

**Comment by myriamboure** [comment]
Ok that sounds pretty good actually, pretty aligned with the work we have done on product chain model as well. I summed up how it works, change, and potential solution here https://community.openfoodnetwork.org/t/what-to-do-with-backorders-and-on-demand-after-spree-got-rid-of-on-demand/1445 let me know if that is logical and if we see other options.

**Comment by sauloperez** [comment]
For the record, Ux-wise when user sets product to `on_demand`, product master variant sets its stock item backordable to true #headache

**Comment by luisramos0** [comment]
Currently "undefined method `allow_backorders" is the most common error in our 2-0-stable build, so it looks like this epic is the top priority in the Spree Upgrade ;-)

**Comment by luisramos0** [comment]
This has been addressed. Closing the issue.
We will review this in detail when we get to manual testing v2. Very soon :-D
