### ISSUE TITLE
Subscriptions: cloning OC's should copy schedule

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2439]
## Description

Enterprise users need to set up lots of basically identical order cycles in a schedule before they can start using subscriptions.

The current clone feature (available from the Order Cycle index page) does not clone key information - most importantly the schedule itself which is left blank

This means that the user must open each order cycle to set the schedule - infuriating. This combined with [G2430](https://github.com/openfoodfoundation/openfoodnetwork/issues/2430) makes this initial essential step very annoying and likely off-putting

## Expected Behavior

When an Order Cycle is cloned from the Order Cycle index page, the schedule information should be copied

## Actual Behavior

The schedule information is left blank

## Steps to Reproduce
1. Go to Order Cycles
2. Select an Order Cycle that is in a Schedule (or put one in one - which will require creating a schedule)
3. Clone it - using button on the right of the of
![image](https://user-images.githubusercontent.com/2911176/42366953-e1049524-8145-11e8-92bf-e047a8f34a06.png)
4. notice that cloned OC has no schedule

## Severity
I'm putting this as severity 3. In conjunction with #2530 it makes OC creation for setting up a schedule very very painful and likely off-putting to early adopters

## NB - Relationship to previously reported issue #1052 
I think this is a better and simpler solution and so #1052 should be closed
My (light) investigations suggest that products fees and tags are being correctly captured in cloning so it is just the schedule that needs to be included

**Comment by ssciolist** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by ssciolist** [comment]
Unfortunately, I’ve had to drop this issue from my to-do list. Sorry about that, and hopefully someone else will be able to pick this up!

**Comment by oeoeaio** [comment]
Ah! Just saw this. Not copying the schedule was not an oversight or a mistake. I did that deliberately to avoid order cycles being mapped onto a bunch of subscriptions unintentionally because the user did not pay attention to which schedule applied. I agree that there is an issue with UX, but I think the proposed solution of such copying across the schedule is not that great either.

**Comment by kirstenalarsen** [comment]
ok, point taken @oeoeaio. I will close this issue and make change to the User Guide that advises people to clone all the order cycles first and then open up the scheduler and add them to the Schedule - rather than opening the order cycle to change the schedule.
