### ISSUE TITLE
Bulk Order Management: Sorting is not working

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#2440]
Front-end sorting in the "Bulk Order Management" page is not working.

## Description

This is of the same nature as the bug described in #589.

## Expected Behavior

Clicking the header for a sortable column such as "Order No.", "Name", and "Order Date" should sort the line items accordingly. Clicking the header again should sort the line items in reverse order.

## Actual Behavior

Nothing happens.

## Steps to Reproduce

Before doing the following, there should already be a few recently completed orders in your database.

1. Go to the "Bulk Order Management" page.
2. Click on the column header "Name". The line items should be sorted by customer name.
3. Click on the column header "Name" again. The line items should be sorted by customer name in reverse order.

## Severity

4

## Possible Fix

This should be fixed in the same way as #589.

@oeoeaio describes an effective solution [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/589#issuecomment-288942315).

**Comment by RachL** [comment]
@sauloperez the workaround is to apply filters so my guess is S4
