### ISSUE TITLE
Spree Upgrade - `Validation failed: Card has expired`

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2449]
## Description
Spree's `:credit_card` factory (see `spree/core/lib/spree/testing_support/factories/credit_card_factory.rb`) creates a card with past expiration date (12/2013), making all tests using  `create(:payment)` fail (see `spec/models/spree/order_spec.rb:401` for example).

## Expected Behavior
Pass the referenced tests.

## Actual Behavior
Tests fail.

## Steps to Reproduce
Run build.
See Job#2 task 81 and 110 to 113 for examples.

## Your Environment
Spree 2-0-stable branch

## Possible Fix
Override params for credit card factory to put valid date.

**Comment by sauloperez** [comment]
I believe this gets fixed by https://github.com/openfoodfoundation/spree/pull/7. The failure is due to Spree's factories and so it needs to be fixed in our fork.

**Comment by sauloperez** [comment]
Since this is addressed in https://github.com/openfoodfoundation/spree/pull/7 which is another repo, I can't connect both in Zenhub :sob:.

**Comment by HugsDaniel** [comment]
Do you want me to open an issue on openfoodfoundation/spree ?

**Comment by sauloperez** [comment]
Not needed now but we will next time.
