### ISSUE TITLE
[Spree 2 Upgrade] undefined method `on_hand' for Spee::Variant

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2450]
## Description
Spree's `on_hand` column in variants is gone in v2.0, making all tests using `variant.on_hand` or `variant` factory with `on_hand` parameter fail.

## Expected Behavior
Pass the referenced tests.

## Actual Behavior
Tests fail.

## Steps to Reproduce
Run build.
See Job#2 task 178 for `variant.on_hand` example and tasks 119 to 125 for variant factory with `on_hand` param examples.

See : https://gist.github.com/HugsDaniel/c3b4853671144fde788e7d680a256790

## Your Environment
Spree 2-0-stable branch

**Comment by sauloperez** [comment]
I think it would be worth sharing the tests output with a gist or at least link to the Semaphore CI job where you got the failures from to make it easy for someone to pick up the issue.

**Comment by luisramos0** [comment]
I believe @mkllnk is working on #2575 which will help with this one.
