### ISSUE TITLE
Duplicate alerts when removing enterprise properties

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2453]
When trying to remove a property from a producer, an alert pops up saying that there are unsaved changes. When confirm the dialog, the same pops up again.

## Description

When editing enterprise properties, the remove button triggers an alert box. That box says that there are unsaved changes even though I haven't changed anything. This box pops up twice.

## Expected Behavior

You click on the trash icon and the "Update" button becomes active. You can then save your changes with the Update button.

## Actual Behavior

An alert box pops up twice.

## Steps to Reproduce

1. Log in as admin.
2. Go to enterprises.
3. Edit an enterprise that is a supplier/produce (sells none).
4. Click on Properties.
5. Click on the trash icon.

## Animated Gif/Screenshot

![screenshot from 2018-07-12 10-49-49](https://user-images.githubusercontent.com/3524483/42606646-271f7134-85c2-11e8-9824-ee0a1f251915.png)

## Context

I'm working on running our automated tests with Chrome. While our old test browser didn't care about alerts, Chrome does and I noticed that I need to confirm two modals to make the test pass.

Different issue on the same page: https://github.com/openfoodfoundation/openfoodnetwork/issues/1759

## Severity

s4, affects admins, but you can just click OK twice.

## Possible Fix

Fix the logic detecting form changes.

**Comment by myriamboure** [comment]
I think we need to discuss about the UX for deletion. I find it a bit dangerous to have only the update button when you delete something, I would love some UX perspective on it. For changing an existing info update button is ok but deletion would be different IMO. @RachL

**Comment by daniellemoorhead** [comment]
Changing this to s5 - it's annoying...but in no way stopping anything.

**Comment by lin-d-hop** [comment]
@binarygit I'm wondering with the Angular work you are doing on this area of the app if this is still an issue?

**Comment by binarygit** [comment]
Nopes not an issue now. Right now, you click the trash icon, and when it prompts you about unsaved changes you can just click `ok` once and it goes away. So, not an issue anymore.
