### ISSUE TITLE
Create product import page in master user guide

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2454]
## Description
When the feature is ready to be release, we need to add the user guide page in gitbook so that users can learn about the feature.
I propose that when we do that we also announce on Slack so that each instance manager can look at it and organize training of support team on the new feature, and communication about it.

## Acceptance criteria
- I have prepared a [user guide page](https://docs.google.com/document/d/1QDtKQe64enO5ZLnht9PxQ8bOlaMHCueJBMWSyW4zCng/edit)  which is still under construction.

**Comment by myriamboure** [comment]
This has been started and almost finished but wait for the templates to be ready to adapt the user guide. So back in the backlog for now.

**Comment by myriamboure** [comment]
@sstead @RachL now that the template issue have been merged and the release should happen in the next hours, we should (Sally you probably already have) the latest version of the templates so we can update the user guide. The last bit which is to make the product import button visible is in code review, so let's get prepared ! There are still 2 bugs in the dev ready column of the board project, for one of them we wait for the release to test, but we will check before merging the last PR showing the button that everything is working ok. @RachL as soon as we upgrade you will have the necessary info for French user guide. @sauloperez if you work on the Katuma user guide this info might be useful for you too.

**Comment by sstead** [comment]
Hey, I've had another go at updating the user guide today. I'm only up to product import/update. Will hopefully get a chance to do Inventory next week. Also where should I put observations regarding things that could be fixed/improved as I test and write the guide?

**Comment by myriamboure** [comment]
@sstead hopefully @Matt-Yorkley can find some time to finish that soon... about what can be improved, you can open some wishlist if you want (if you put all your idea in one wishlist put it as "needs curation" and we can then break it in things that we can prioritize, or open one wishlist per idea). We want to release first with what is now, when the bugs are fixed of course...

**Comment by RachL** [comment]
A first english version has been published and is now getting reviewed / used. So I'm closing this issue as I will follow this up on the user guide slack channel.
