### ISSUE TITLE
Product import: delete default options page and bring back some filter in previous page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2460]
## Description

We don't need anymore the default option page set up as we are simplifying the first release (were UX issues).

## Acceptance criteria
![capture du 2018-07-12 15-57-57](https://user-images.githubusercontent.com/8135376/42637817-67062cdc-85ec-11e8-9637-4e3d9a47e023.png)

- The "default options" page is not there anymore (were very confusing and not UX friendly at all when you have many enterprises) 
- The PO landing page **still propose the option to "reset absent products**". The use case is that a big wholesaler whose product catalog changes want to automatically set the stock to 0 for products which might have disappeared from the catalog.
- **When I click on "upload" from PO landing page, I am not redirected to the previous default option setup page, I directly see the progress bar of the upload**.

## Test cases
- We need to make sure that reset absent products work, until now it was not working but Matt seems to say it should work, so let's retest: https://github.com/openfoodfoundation/openfoodnetwork/issues/2313

**Comment by Matt-Yorkley** [comment]
Closed via #2474

**Comment by Matt-Yorkley** [comment]
Closed via #2474
