### ISSUE TITLE
Cloning an OC sets Schedule to 'none' which is not editable from OC overview screen

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2463]
Trying to get OC rapid creation more workable . . following from #2430 and #2439

When an OC is cloned, the schedule is set to 'none'

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/f3e409f6-87c9-4a07-a3f0-87bf39469215)

This 'None' is NOT clickable to pull up the Schedule / OC selector, so the User does need to go into the OC to select the Schedule. Annoying.

## Expected Behavior
Complete #2439
and
make Schedule = 'None' also clickable to bring up the Schedule Updater 

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/52e510d1-186b-4669-912c-e5a486f323f8)

## Actual Behavior
A user needs to go into the OC to set Schedule every time they create / clone a new OC. Once they have set it once, they can open the Schedule Updater by clicking on the Schedule name from the OC Overview screen

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a3d47ae7-e2fe-4f29-9a50-6f147b05e82f)

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/be058900-1762-4dd5-bd77-a4d76fb146b9)

**Comment by anon0mys** [comment]
Hi @kirstenalarsen, I am a new dev and am interested in contributing! I noticed that this issue was referenced in a PR for another issue, but I am not sure if that PR fixes the issue. Do you still need someone to work on this? Thanks!

**Comment by oeoeaio** [comment]
@kirstenalarsen I'm not sure this is needed? I can see two cases where an OC does not belong to a schedule and so has 'None' in the schedules column:

1. The schedule that you want to add the unassigned OC to already exists. In this case, there must be other order cycles assigned to it, as you cannot have an empty schedule. Therefore, you can just click on another reference to it elsewhere in the page, and then add the unassigned OC to that schedule.
2. The schedule that you want to add the unassigned OC to does not already exist. In this case, you should just create a new schedule at the top right of the screen and add the unassigned OC to it.

The screen that comes up when you click on a schedule name is an edit form for a particular schedule. If we add the ability to click 'None', what would you like to see? We can't show the normal screen that is shown because we have not specified a schedule to render a form for...

**Comment by oeoeaio** [comment]
As I have said in a couple of different places, I think we just need a dedicated schedules index. Attempting to squeeze them into the order cycles index was a nice idea, but I think it's going to be tricky to get the UX to the point that we are happy with it.

**Comment by myriamboure** [comment]
Ok so from what I understand I guess we can close that issue for now (@kirstenalarsen you closed the other one so I hope that's fine with you, reopen if that's not!) and ask @RachL to have a look at a UX improvement about the subscription flow regarding schedules management especially? And make some proposal based on Rob's suggestion? But that can be planned for iteration 2, subscription works as expected for release one so let's just explain in user guide and it's fine if it's not all super user friendly for now, agile releasing ;-) Also in this UX work on schedule we might also integrate further reflexion regarding what CSA needs to use this feature (the "contracts" notion kind of). What do you think @RachL ? You have quite a lot on your plat maybe, tell us if you can add that one or not. I added that [here](https://app.cardboardit.com/maps/guests/ab9ea64b14ff4efd418b6a5dfb5a89c2dd4060e075328dccdfb20874974c8882) for now, will check on Discourse post but I find discussion threads hard to read the list of things we want to do for release 2 compared to the things we want to fix for release one to work properly :-o

**Comment by myriamboure** [comment]
Or if we want to have Yuko work on the subscription UX that's another idea. I think we first need to do a bit more of inception about CSA needs though as some things in the current logic will probably change a bit.

**Comment by myriamboure** [comment]
@anon0mys do you want me to point you to some other issue that you could work on? Be welcome to our community! Your contributions are most welcome :-)

**Comment by RachL** [comment]
@myriamboure I can have a look starting the end of next week. However, I need to dive into subscriptions as I didn't tested it properly. Can you point me to the original spec ? Also is first release already released ?

**Comment by anon0mys** [comment]
@myriamboure I would definitely like to contribute! This is my first open source project, so maybe something that is good for a new developer?

**Comment by myriamboure** [comment]
Awesome @anon0mys ! Here are some issues that are bugs pretty prioritory (S3), and labeled as good first issues:
- https://github.com/openfoodfoundation/openfoodnetwork/issues/1361
- https://github.com/openfoodfoundation/openfoodnetwork/issues/2375
- https://github.com/openfoodfoundation/openfoodnetwork/issues/2112
- https://github.com/openfoodfoundation/openfoodnetwork/issues/2300
Please check on the wiki the internationalisation / transifex sections to make sure you understand how to address them properly, two of the issues above are translations related ones ;-)
