### ISSUE TITLE
Subscriptions: make Pickup/Delivery details  field editable from OC index

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2464]
following on from #2430, #2439 and #2463

When a User is rapidly creating multiple OCs for their schedule, the only field that they are now likely to need to open each OC for is the Pick-Up / delivery details field - where they (most likely) communicate the pick-up/delivery date to customers

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/23b394ed-62af-455e-a2e2-021e2709f96c)

If this could also be available in the OC Index screen - likely as an optional column - then they would be able to do all these in one go, or at least easily without having to open each order cycle

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/b918b02d-068d-4883-8cb3-cd7989a75529)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by myriamboure** [comment]
I'm not sure @kirstenalarsen about this one, as this depends on the number of outgoing ditributors you have in the OC, you need to set this up those for each distributor. If you have more than one (80% of cases in France for instance) that becomes impossible to manage from OC index.

**Comment by kirstenalarsen** [comment]
ah cool - yes good point. let’s leave this one then. i’ll close it
