### ISSUE TITLE
Missing translation - enterprise viewing customers subscription

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2465]
I'm not sure how we deal with missing translations? Is there something I can do to fix this? @mkllnk @myriamboure 
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/f52fd72d-7482-4c95-a7d5-383b6c990c75)

as an Enterprise, go to Orders, Subscriptions and open up a Customers 'Orders' tab

![image](https://user-images.githubusercontent.com/2911176/42674523-6e8e8572-86b3-11e8-8a8b-4a5ac7295dd9.png)

I have made it S2 because it may not prevent people doing things - or it may - I'm not sure what information is meant to be conveyed here so I don't really know how serious it is?

**Comment by myriamboure** [comment]
@mkllnk is it a missing entry in en.yml file? If yes it should be pretty quick to fix... but we still need to ask someone to do it :-)

**Comment by kirstenalarsen** [comment]
we’ve got write permission @myriam - perhaps we should just learn to do it :)
