### ISSUE TITLE
registration process - move translation keys into new structure

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2484]
## Description
To avoid having all translation keys at the root of the en.yml file. A new structure for translation keys was created for step TYPE of the registration process and lazy look up was used as much as possible.
The TYPE step was changed as part of issue #2303 where we confirmed that if translation keys are moved from root to a new place, if we keep the key text, transifex will pick up the translations and translators will not have to translate everything again.

The goal is to make the en.yml file organized with a minimum number of entries at the root level.

## Testing
No change in behaviour, no change in transifex. This is just a refactor of the registration process translation keys.
Afterwards, we should test the registration process and make sure all existing translations are picked up automatically by transifex.

**Comment by myriamboure** [comment]
Ok I added some priority on this as it seems it's introducing some mess we don't want to keep in. @luisramos0 as you started the job and it works if you manage to fit it in between other things that would be cool ;-)

**Comment by luisramos0** [comment]
ok, but I want to get into the spree upgrade first :-D
Somewhere in August...

**Comment by luisramos0** [comment]
I have added the tag good-first-issue. This can be tackled in several PRs (we can start by migrating a few more keys each time).

**Comment by luisramos0** [comment]
In July I said "I want to get into the spree upgrade first" 🤣 

I'm doing this one now before I clean up translations in v2.
