### ISSUE TITLE
Unfilled checkout panels default to Open in Mobile

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2485]
## Expected Behavior
When a Customer goes to the Checkout, any panels that require information to be filled in will default to open so that it is obvious that they have to enter information.

If the Customer is already logged in or logs in, and has shopped previously, this will most likely be the Shipping and Payment panels

If they are a new Shopper it will also be the Details and Billing Info panels

## Actual Behavior
panels are closed and require Customer to click on 'expand', which is in small text and on the right hand side of the screen. So people get stuck

![image](https://user-images.githubusercontent.com/2911176/42942213-87ffef7a-8ba2-11e8-9f93-c048941b74dd.png)

## Steps to Reproduce
1. Go to Checkout on Mobile
2. See that some panels are closed and you need to click small link to open them - not obvious
3.
4.

**Comment by kirstenalarsen** [comment]
See #2830 for additional information. Please apply this behaviour to both desktop and mobile

**Comment by RachL** [comment]
Closing via #3047
