### ISSUE TITLE
Remove New Relic

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2486]
Several admins voiced that they don't like New Relic being in our code. A poll on Slack showed that nobody is using it any more:
https://openfoodnetwork.slack.com/archives/C0DNLAZC7/p1531802988000065

## Description

Removing New Relic make our dependencies smaller and avoids some confusing log output of the application. Skylight is the new New Relic.

## Expected Behavior

New Relic is not there.

## Actual Behavior

New Relic is installed with the bundle, it is present in log output and there are some unused configuration files.

## Steps to Reproduce

1. Gemfile.lock contains newrelic

## Severity

Tech debt s4.

**Comment by sauloperez** [comment]
![](https://media.giphy.com/media/3o7btXkbsV26U95Uly/giphy-downsized.gif)
