### ISSUE TITLE
Selected LOCALE is not maintained with navigation

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2491]
## Description
If you add a product to the cart on the Portuguese site, it switches to Spanish as you visit the cart.

- go to shop in Portuguese https://alpha.katuma.org/quinta-de-silvares-vizela/shop?locale=pt
- select an order cycle
- add a quantity
- click Edit Cart "Editar carrinho"
- the destination page is a page in spanish

## Expected Behavior
Should keep user language: portuguese in this example.

## Actual Behavior
Switches to Spanish.

## Steps to Reproduce
See description above.

## Context
Portugese version of Katuma not usable like this.

## Severity
S4

## Your Environment
* Version used: katuma live
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): OSX

**Comment by sauloperez** [comment]
Assuming we already have the means to persist the user's language preference, it would just be a matter of persisting it also when the user starts the checkout process. How does this sound?
