### ISSUE TITLE
Inventory show "loading" instead of products

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2502]
When switching shops in the inventory as super admin, there is a Javascript error that stops the products from showing properly.

This problem seems to be only with certain enterprise permissions, currently on https://staging1.openfood.com.au/admin/inventory.

More info: https://github.com/openfoodfoundation/openfoodnetwork/pull/2389#issuecomment-404737942

## Expected Behavior

The loading message disappears and products are shown.

## Actual Behavior

The loading message stays. There are Javascript errors.

## Steps to Reproduce

1. Got to https://staging1.openfood.com.au/admin/inventory.
2. Log in as super admin.
3. Switch between shops.
4. Observe the Javascript console of your browser.

## Animated Gif/Screenshot

https://www.useloom.com/share/c2cda401be9747ee830e735e1b0d9dfa

## Context

Sally found this while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2389.

## Severity

s4, only super admin is affected.

## Possible Fix

@luisramos0 suggested this patch:
```diff
diff --git a/app/assets/javascripts/admin/variant_overrides/filters/hub_permissions_filter.js.coffee b/app/assets/javascripts/admin/variant_overrides/filters/hub_permissions_filter.js.coffee
index 39b5e7783..928b236c8 100644
--- a/app/assets/javascripts/admin/variant_overrides/filters/hub_permissions_filter.js.coffee
+++ b/app/assets/javascripts/admin/variant_overrides/filters/hub_permissions_filter.js.coffee
@@ -1,4 +1,4 @@
 angular.module("admin.variantOverrides").filter "hubPermissions", ($filter) ->
   return (products, hubPermissions, hub_id) ->
     return [] if !hub_id
-    return $filter('filter')(products, ((product) -> hubPermissions[hub_id].indexOf(product.producer_id) > -1), true)
+    return $filter('filter')(products, ((product) -> hubPermissions[hub_id] && hubPermissions[hub_id].indexOf(product.producer_id) > -1), true)
```

**Comment by luisramos0** [comment]
I think this is happening on 2-0-stable with sample data... I am not sure why.

Going through it, an even easier fix:
```diff
--- a/app/assets/javascripts/admin/variant_overrides/filters/hub_permissions_filter.js.coffee
+++ b/app/assets/javascripts/admin/variant_overrides/filters/hub_permissions_filter.js.coffee
@@ -1,4 +1,5 @@
 angular.module("admin.variantOverrides").filter "hubPermissions", ($filter) ->
   return (products, hubPermissions, hub_id) ->
     return [] if !hub_id
+    return [] if !hubPermissions[hub_id]
     return $filter('filter')(products, ((product) -> hubPermissions[hub_id].indexOf(product.producer_id) > -1), true)

```
