### ISSUE TITLE
Subs: Prevent Enterprise from creating subscription for Customer that isn't a User

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2508]
## Description
An Enterprise can create a Customer without creating a User. 
This means that they can then create a Subscription for a Customer that is not a User.
This means that when that subscription is turned into an order, the Customer receives an email telling them their order has been created and gives them a link to edit their order.
When they hit that link they get an 'unauthorised' page. If they then sign up (creating a User) and log in, the subscription connected with the Customer is not connected with their User, so they still can't access it.
 
This situation of creating orders / future proxy orders for a non-user / unconfirmed user is undermining the logic of the email confirmation work. While we still allow for guest users, it does not make sense to do so for a subscription. 

Allowing the Enterprise to instigate User creation from Admin (e.g. when creating a Customer) could be a longer term solution to this, but would require full inception and is not part of Subscription V1

In the meantime we can prevent the Enterprise from creating an invalid subscription by only allowing creation of Subscriptions for existing / confirmed users

## Expected Behavior
Only confirmed Users can have Subscriptions created. Therefore when they receive order confirmation / amendment emails, they will be able to login and access those orders (pending #2506). 

## Actual Behaviour
New Customers that don't have confirmed Users can have subscriptions created. This causes multiple problems, including undermining email confirmation, sending them information that they cannot act upon, and failing to connect their subscription with their User even after it is created. 

## Steps to Reproduce
1. Create a new Customer from admin/customers  - use a 'virgin' email that doesn't already have a User in OFN
2. Create a Subscription for that Customer
3. Click on the 'update order' link in order confirmation
4. See 'unauthorised' screen
. . you can further explore implications
5. If you then sign up and create a User, and click the link you will still get unauthorised, as the order is not connected with your new user

## Context
Testing Subscriptions as a person new to it, got completely tangled. Potentially very off-putting to Subscription beta testers

## Severity
s3 - with sufficient user guide, assuming people read it, enterprises can ensure that Subscriptions for Customers with no User are not created. And/or, they can delete and recreate Subs once the Customer has created a User. But it is very easy to make this mistake and the implications (delete and recreate Sub, or losing an irritated customer) are reasonably large

## Possible Fix
When an Enterprise is  creating a Subscription, only Customers that are confirmed users are valid to be added to the Subscription

Customers that are not valid should be greyed out in the Customer dropdown
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/d6d100fd-ad35-4088-adc8-923c79d5d1a8)

**Comment by myriamboure** [comment]
I think we need to investigate different ways to solve that issue.
- **Option 1:** a hub manager can't create a subscription for a customer that is not a user (what you propose above). I wouldn't vote for that option as it make life of the hub manager harder as they need to explain the user how to create an account and make sure they do it. We experienced that for private shop feature, it is pretty hard.
- **Option 2:** a hub manager can add a customer in their customer list and create a subscription for that customer. At that point the system triggers an email to be sent to the customer if they are not recognized as a user, with a validation link saying something like "{HUB X] has set up a subscription for you, hopefully upon your request! For the subscription to be active, you need to validate your account + validation link". So technically we need to have "pending" subscriptions that will be activated only when the user has clicked on validation link.
- **Option 3:** a hub manager can add a customer in their customer list and create a subscription for that customer. The subscription is valid as it is and the customer receives a message telling that this order is going to be made (a guest order here). IF the hub has authorized the customer to modify the order, when the user clicks on the link it is taken to a screen a bit similar to the one when you try to enter a private shop and you have not yet registered, with a message like "To access your order, you need to login. No account yet? Register." and then just like private shop, the system matches the addresses and create the account and associate the subscription to that account.
- **Other option?**

I would vote either for option 2 or 3. For me option 2 makes more sense as a subscription in itself is a contract so forcing registered account for a subscription (know user identity) makes sense to me.

**Comment by myriamboure** [comment]
So @sstead proposal here https://github.com/openfoodfoundation/openfoodnetwork/issues/2506 corresponds to option 2. If we all agree that's what we want to do I suggest we close that issue and keep the other one, but specify it a bit more clearly, especially what message exactly get sent when and what it triggers on system side at which moment. This is definitely a bug for release one of subs to work, so we need to fix it. Meanwhile I put the other issue in "analysis and design" in the bug management board so that we know when it can go to dev ready.

**Comment by kirstenalarsen** [comment]
hmmm. My issue here is with the line between bugs / issues preventing release of v1 and extension of the feature set. I am conscious of the tendency to scope-creep and never be able to tick the box on v1. 

I think that option 2 would be the preferred one because i think that having a Subscription created in the system SHOULD require a User to be created. It doesn’t make sense to use a ‘guest’ for something that is a recurring contract. To create the subscription as a contract requires at minimum confirmation of an email surely

But to implement 2 requires creation of some new actions and interfaces, incepting the flow etc, and working out a ‘pending’ subscription - which to my understanding is a new ‘state’ that is not currently supported in the already quite complex subscriptions mechanism

I don’t see it happening anytime soon and I want to release v1. Hence my preference for Option 1 now. I agree it makes life harder for Hub Manager than 2 or 3, but right now, for people who really really want to use subscriptions, it’s much better than the mess that occurs if you create a subscription for an unverified customer OR relying on Customers to tell you when they have signed up

. . although . . I have just realised that there is still a missing link because you still need customers to do this so you can add them to your customer list. Which means that we either need to
a) have something in the Add Customer interface that tells you if your are trying to add someone who is not a user
b) fix / clean-up the problem about linking a Subscription - and any orders - created for a guest with a User that is created AFTER the Customer and Subscription? If we viewed that as a BUG and fixed that, then might the whole problem would actually go away?  

If we did INSTEAD
- #2511 ensure that any Order or Subscription for a Customer was linked with the User for that email, regardless of WHEN the subscription and order were created
- AND made #2506 a prompt to login OR sign-up . . 
then the problem might be solved . . 
we could leave the current (not ideal) state as is where subscriptions and orders can exist for unconfirmed customers, but if they want to view or make changes to it they need to sign-up / login?

I have created a new issue for #2511 to investigate how doable that is, and added comment in #2506

**Comment by kirstenalarsen** [comment]
ok. So #2511 isn't doable and this is not agreed as the best solution now. A super-duper simple quick-fix solution can be achieved with #2506 and #2534. 

Closing this issue and referenced for consideration in Subs v2 via [Subscriptions improvements](https://community.openfoodnetwork.org/t/subscriptions-improvements/1349/15)
