### ISSUE TITLE
PinPayments aren't working when applied in the backoffice (Edit/New)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2514]
## Description
PinPayments is working in the front end - I can place a $2 order in a shop. (note this is a minimum spend for PinPayments)

In the backend I should be able to apply a Pin Payment charge to an order, either by editing an existing order, or if I manually create an order. 

Here's the field I'm refering to:
![image](https://user-images.githubusercontent.com/10843056/43618117-02534dd6-970a-11e8-843e-375fcb84ff1a.png)

## Expected Behavior
The PinPayment field in the backend should work.

## Actual Behavior
It doesn't work- I can enter card info, but when I click update, there's no payment processed or saved against the order.

## Steps to Reproduce
1. On Aus production you can go to https://openfoodnetwork.org.au/demo-hub/shop to see a shop with a working Pin account. This is a real account, if you use it you'll be charged.
2. Go to the backed for that shop and create a new order
3. Make an order worth $2 e.g. 20 x 10c apricots. 
4. Get to the payment area and select PinPayments
5. Enter a legit credit card and click update. 
6. You'll see an updated payment screen with nothing in it. There's no sign that the payment was done. If you click continue you'll see the order wasn't created. 

You'll see similar issues if you try to apply a Pin payment to an existing order with balance due.

## Animated Gif/Screenshot
Can't do due to credit card details.

## Context
Found while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2420 

## Severity
s3

## Your Environment
PC, Chrome, staging1 and Aus production

**Comment by RachL** [comment]
Closing as PinPayments are now removed.
