### ISSUE TITLE
[Bulk invoice printing] Recreate the Spree view without deface overrides

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#2525]
## Description

Part 1 of the Bulk Invoice Printing epic.

As a small issue in preparation for the Bulk Invoice Printing epic, we need to recreate our own views for the admin Orders page. This means taking the Spree view, applying anything from the deface overrides we have previously created, adding them together into new view file and deleting the old overrides.

## Acceptance criteria

A new view should be created for the Orders page in the backend. Visually it should be the same as before.

**Comment by Matt-Yorkley** [comment]
@myriamboure shall we move this issue and #2526 to "dev ready"?

**Comment by RachL** [comment]
@Matt-Yorkley yes I just did :)

**Comment by daniellemoorhead** [comment]
Woahhhhh little donkey! 

Have you officially kicked off this feature yet? I do believe that kick off should precede putting things into dev ready...yes?

**Comment by Matt-Yorkley** [comment]
@daniellemoorhead we've officially kicked off now :)

![](https://media.giphy.com/media/I3N5kit04iStO/giphy.gif)

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley 

![](https://media1.tenor.com/images/3376fe1615eaca2b3ef0e1ea251c1204/tenor.gif?itemid=11084136)
