### ISSUE TITLE
[Spree Build] Selenium::WebDriver unable to obtain stable firefox connection

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2531]
## Description

With recent versions of Firefox and the version of Selenium WebDriver that is used in Spree `2-0-4-stable` , Selenium is unable to establish a stable connection with Firefox, so tests using Selenium don't run.

`Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds`

## Expected Behavior

SeleniumWebdriver runs with recent versions of Firefox so that the suite can run.

## Actual Behavior

`Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds`, which means that all tests using Selenium don't run at all.

## Steps to Reproduce

In our Spree fork : 

1. `git checkout 2-0-4-stable`
2. `bash build.sh`

## Animated Gif/Screenshot

![screenshot from 2018-08-09 10-33-03](https://user-images.githubusercontent.com/28786869/43887620-acda4200-9bbf-11e8-8acc-e14ec5491bbf.png)

## Context

This affects our Spree build and prevents us from having a running test suite on branch `2-0-4-stable`.

## Your Environment

* Version used: Spree `2-0-4-stable`
* Browser name and version: Firefox 61
* Operating System and version (desktop or mobile): Ubuntu 16.04

## Possible Fix

Update our version of Selenium in the Gemfile and install the correct drivers to have compatibility with recent versions of Firefox.

**Comment by HugsDaniel** [comment]
As @mkllnk suggested in https://github.com/openfoodfoundation/spree/pull/11#issuecomment-412391890, we use FF31 instead of FF61 to avoid having to use a fix.

**Comment by mkllnk** [comment]
I do have that error with FF 52.9, but not with FF 33.
