### ISSUE TITLE
[Spree Build] Selenium::WebDriver element is not clickable

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2532]
## Description

Blocked by #2531 

When running Spree's test suite for `backend`, an error occurs with Selenium with the following message : 
`Element <button class="foo"> is not clickable at point (...) because another element <div id="select2-drop-mask" class="select2-drop-mask"> obscures it`.

This comes from the select2 dropdown used by Spree for selection in form fields containing a collection of elements (such as country, state...).

## Expected Behavior
The element should be clickable and the tests should continue running.

## Actual Behavior
The element is not clickable because the select2 dropdown obscures it, making the test fail.

## Steps to Reproduce

On our Spree fork : 

1. `cd backend`
2. `bundle install`
3. `bundle exec rspec spec`

## Animated Gif/Screenshot
This is an example of the error we get : 
![screenshot from 2018-08-09 12-23-26](https://user-images.githubusercontent.com/28786869/43893582-bc588484-9bcf-11e8-80cb-d3c32d27181e.png)

## Context
This affects our Spree build and prevents us from having a passing test suite on branch 2-0-4-stable.

## Your Environment

* Version used: Spree `2-0-4-stable`
* Browser name and version: Firefox 61
* Operating System and version (desktop or mobile): Ubuntu 16.04

## Possible Fix
It seems that the error occurs when the test have a `fill` statement in a form and that the string passed doesn't match anything in the collection within the select2 dropdown, making it stay instead of close. When Selenium tries to click a button elsewhere on the page, the presence of dropdown prevents it from doing so. 
Passing the `fill` a string matching the collection should fix it.

**Comment by luisramos0** [comment]
hey @HugsDaniel , PR #12 on spree fixed this right? can be closed?
I dont see this error on my local.

**Comment by HugsDaniel** [comment]
@luisramos0 yes it is ! I close it now
