### ISSUE TITLE
[Spree Build] Unexpected ActiveRecord::StatementInvalid

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2537]
## Description
Blocked by #2531 

When running test `core/spec/models/spree/product_spec.rb:226`, it fails with ` expected ActiveRecord::RecordNotUnique, got #<ActiveRecord::StatementInvalid: SQLite3::ConstraintException: UNIQUE constraint failed`. 

RSpec is expecting a `RecordNotUnique` error and gets a `StatementInvalid` error instead. We do have the `SQLite3 UNIQUE` constraint error met though, but not with the expected ActiveRecord error.

## Expected Behavior

`ActiveRecord::RecordNotUnique` should be raised.

## Actual Behavior

`ActiveRecord::StatementInvalid` is raised, which is the superclass for all database execution errors (https://api.rubyonrails.org/). It matches the tested behavior but not as expected.

## Steps to Reproduce

1. `cd core`
2. `bundle exec rspec spec/models/spree/product_spec.rb:226`

## Animated Gif/Screenshot

![screenshot from 2018-08-10 13-03-16](https://user-images.githubusercontent.com/28786869/43955204-6ddbbecc-9c9f-11e8-9b7b-1c1857b8e8e8.png)

## Context

This affects our Spree build and prevents us from having a passing test suite on branch 2-0-4-stable.

## Your Environment

* Version used: Spree `2-0-4-stable`
* Browser name and version: Firefox 61
* Operating System and version (desktop or mobile): Ubuntu 16.04

## Possible Fix

Use something like `raise_error(ActiveRecord::StatementInvalid, /SQLite3::ConstraintException/)` to fit the unique constraint expected.

**Comment by sigmundpetersen** [comment]
#canweclose ? https://github.com/openfoodfoundation/spree/pull/14

**Comment by HugsDaniel** [comment]
Yes ! I close it now
