### ISSUE TITLE
Welcome email can be localized to region

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#254]
Here's the content:

```
Hello,

Welcome to Australia's Open Food Network! Your login email is pauljmackay@gmail.com

You can go online and start shopping through food hubs and local producers you like at http://openfoodnetwork.org.au

We welcome all your questions and feedback; you can use the Send Feedback button on the site or email us at hello@openfoodnetwork.org

Thanks for getting on board and we look forward to introducing you to many more great farmers, food hubs and food!

Cheers,
Kirsten Larsen and the OFN Team
```

I'm happy to tackle this but have some questions:

* Could it just say "Welcome to Open Food Network!" ?
* Can URL be inserted using a variable? (I can look into this)
* Does it need to have different emails for different countries, for feedback?

**Comment by pmackay** [comment]
@RohanM would appreciate if you could check if anything else needs doing with this, after last merge.

**Comment by RohanM** [comment]
@pmackay , I'm not quite sure what you'd like me to check here?

**Comment by pmackay** [comment]
@RohanM are you happy for this issue to be closed now?
