### ISSUE TITLE
Error when creating new Enterprise fee

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#2545]
## Description

When trying to add a new enterprise fee I am not taken to the Create Enterprise fee page and instead am only given the option to Update an Enterprise Fee. When I try to update for an enterprise that does not currently have an enterprise fee I get a 500 error on bulk_update

## Expected Behavior

1. Enterprise -> Enterprise Fees
2. Click Create New Enterprise Fee
3. Taken to the page that let's me create an Enterprise fee.
4. Successfully create enterprise fee.

## Actual Behavior
1. Enterprise -> Enterprise Fees
2. Click Create New Enterprise Fee
3. Taken to the bulk edit enterprise fee page
4. 500 error when trying to update any enterprise fee.

## Context
This bug is blocking set up of new enterprises, including Food Assemblies in the UK.

## Severity

bug-s1: enterprise sign up is BROKEN

## Your Environment

* Version used: ~v1.17~, now v1.18.0
* Browser name and version: Tried in Chrome and IE
* Operating System and version (desktop or mobile): Linux and Windows

**Comment by luisramos0** [comment]
Hi Lynne, I tried to replicate locally. It doesnt look like a generic problem as it's working on my local.
Do you want to give me access to some enterprise in UK live so I can have a look?

Another thing that always helps with server side errors like this 500 is the dev tools log.
When the error occurs (this is useful when any error occurs on the browser actually), could you please open the dev tools console and see what error is in there? just replicate the error and press Ctrl+Shift+J (cmd+alt+J on mac).
Thanks,
Luís

**Comment by mkllnk** [comment]
I tried this as super-admin. There are a lot of enterprise fees so that the page takes a while to load. When trying to update, the server takes a while and I then get a 502 Bad Gateway error. That means that nginx is not waiting long enough for the application (or the application is too slow). I'm not sure if it's the same with an enterprise user.

**Comment by mkllnk** [comment]
I just checked the version on the server. It's v1.18.0, not v1.17.0 as reported by @lin-d-hop.

**Comment by mkllnk** [comment]
There are two ways to get to enterprise fees. Number one through an enterprise:

- *Enterprises*
- Click on an enterprise
- Click on *Enterprise fees*
- Click on *Create one now* or *Manage*
- All enterprise fees visible to you are displayed in a form

Or straight from the enterprise list:

- *Enterprises*
- Each enterprise row has a link *Enterprise fees*, click it.
- You see only the fees for that enterprise.
- Updating still takes too long on the UK server.

**Comment by mkllnk** [comment]
The nginx timeout was 30 seconds and the unicorn timeout was 30 seconds. I increased both to 120 seconds and I can now create and update fees. Updating takes 50 seconds. So I would demote this issue to be an S2 (or even S3?) as increasing the timeout is a workaround.

Things to do:

- Change UK config in ofn-install for increased timeout.
- (I'm not sure if ofn-install allows setting this timeout everywhere, maybe improve ofn-install.)
- Analyse the performance of updating enterprise fees. Do we have Skylight data on this?
- Make that update faster and scale well.

**Comment by daniellemoorhead** [comment]
@lin-d-hop to progress this further we need you to chime back in. 

I've put it into the blocked column for now - once you respond to the questions @mkllnk has above we can move it forward for resolution.

**Comment by mkllnk** [comment]
The operation that takes a lot of time is `EnterpriseFeeSet.new({}).save`. It loads all fees (fast) and then saves every single one. Somehow that's really fast on Aus production, but quite slow on UK production (150 fees). I compared some tables it joins with and couldn't see a big difference between the databases (variants, exchange_variants). Anyway, loading all fees and saving all of them is not the best approach.

**Comment by daniellemoorhead** [comment]
So what next @mkllnk?

**Comment by mkllnk** [comment]
I opened pull requests for the minor stuff. The one remaining thing is to tweak the class `EnterpriseFeeSet` so be more efficient. I'm happy for someone else to take that on. It's almost the weekend for me. But I could look into it next week (further delaying Spree upgrade) if everybody is busy. Actually, I think @kristinalim would be very good at this.

**Comment by daniellemoorhead** [comment]
@kristinalim if you want to add it to your list then that would be great.

@mkllnk get back to the spree upgrade young man, there's no time to lose! 😉

**Comment by lin-d-hop** [comment]
Thanks all for the swift input!

Some things to note:
1) When this issue was create UK was on 1.17. @Matt-Yorkley updated to 1.18 last night.
2) When I was managing servers all timeouts were set ridiculously high to 360 seconds. 
@Matt-Yorkley When you reprovisioned would timeouts have been reset to default levels? That makes sense and stupidly I didn't clock that now that my head is  out of server management. Sorry all!
3) All testing was done with enterprise users.

@Matt-Yorkley could you take a look and make sure all the timeouts (I remember updating 3 in the past, read and response in nginx and the one maikel has updated in unicorn) have been increased?

Thanks @mkllnk for tinkering for us. And thanks all for jumping on it so quickly!

**Comment by lin-d-hop** [comment]
Note also as an Enterprise user there is only one way to access Enterprise fees. The second way Maikel mentioned above is not relevant for an Enterprise user.

Agree this issue lower priority. Apologies again for my oversight that UK timeouts were reset when the server was reprovisioned and I stepped away from managing. I should have clocked that.

**Comment by daniellemoorhead** [comment]
#2550 is merged so closing this.

@mkllnk a few of these haven't been closed when you've merged them...is GH broken?

**Comment by mkllnk** [comment]
The pull request didn't solve the whole issue as the issue was a bit more general. So it wasn't set to close this one. But if @lin-d-hop is happy with the outcome, this is solved. :-)

**Comment by daniellemoorhead** [comment]
@lin-d-hop I've reopened this issue - can you please let us know if you're happy with the outcome and re-close this if you are :-)

**Comment by myriamboure** [comment]
@lin-d-hop can we close that issue? Don't understand if it still remains as is, or needs a new issue with different scoping of issue open, or just closed. Thanks!

**Comment by daniellemoorhead** [comment]
Let's just close it for now, @lin-d-hop can reopen or create a new one when she's out of exam mode and has the brain space 🤓
