### ISSUE TITLE
[Subscriptions] When unpausing a subscription, tell the shop owner whether an order will be created

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2549]
[updated by Myriam 22.10.2018]

## Description
As a shop manager I want to make sure I don't create automatic orders for "subscribed customers" that would be inappropriate.

If I have a customer with a paused subscription, and I have an open OC in the schedule that the customer is subscribed to, if I unpause their subscription I am asked 'are you sure?' but I'm not given any info about if an automatic order will be created straight away for an open OC or not.

## Possible fix
a) tell the shop manager - 'if you have an open OC in this subscription's schedule currently, an order will be created for this customer, are you sure?'
b) (this is a slightly more complicated option) give the shop manager the option - 'you're unpausing a subscription while there's an open OC, would you like to generate an order for this customer in this OC? Or do you want to avoid creating an order for this OC?'

Myriam vote for option a. simpler and efficient enough. Easy fix. @sstead @RachL @kirstenalarsen do you agree?

**Comment by kristinalim** [comment]
Estimated time: 0.5 hours after #2909 is addressed

Related to #2909
