### ISSUE TITLE
The void credit button doesn't work

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2552]
## Description
As a shop manager, if I have credited an amount to the customer via stripe there is a new line added to the ‘Payments’ section of the order (when editing an order). Next to the new line is a Cross icon with ‘void’ - As a user I would assume that this undos the refund I just gave. I click the void button and get a nonsense error message.

Found while testing #2273 ,
test notes https://docs.google.com/document/d/10lqelt6b0AEF6nhFSj0FII8ks8K3rv4beWZtcBfV_8M/edit#
![image](https://user-images.githubusercontent.com/10843056/44252044-2196c080-a23e-11e8-98f6-b03d2abfc556.png)

## Expected Behavior
I suggest we either remove the void button or have the error message read ‘you cannot void a credit payment’.

## Steps to Reproduce
1. Create an order and pay with Stripe
2. As shop manager reduce the items in the order so it goes into credit
3. Refund the credit
4. try to void the refund.

## Severity
s4

## Your Environment
PC, Chrome, Aus prodcution, v1.18.0

**Comment by hmesander** [comment]
I think I would like to try to solve this, but I wasn't sure if someone was already working on it. Is it ok if I pick this issue up?

**Comment by kirstenalarsen** [comment]
I think this is now working. Very old issue so closing
