### ISSUE TITLE
Intermittently failing cookies spec

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2553]
## Description

A spec recently introduced in #2411 seems to be unreliable. I've seen this error a few times now:

```
  1) Cookies banner in the homepage does not show after cookies are accepted
     Failure/Error: expect(page).to_not have_css("button", :text => accept_cookies_button_text, :visible => true)
       expected not to find visible css "button" with text "Accept Cookies", found 1 match: "Accept Cookies"
     # ./spec/features/consumer/cookies_spec.rb:86:in `expect_not_visible_cookies_banner'
     # ./spec/features/consumer/cookies_spec.rb:13:in `block (4 levels) in <top (required)>'
```

 Example: https://travis-ci.org/mkllnk/openfoodnetwork/jobs/417116813

## Expected Behavior

Automated test always pass.

## Actual Behavior

The mentioned spec fails from time to time.

## Steps to Reproduce

1. `bundle exec rspec ./spec/features/consumer/cookies_spec.rb:11`

## Context

Testing other pull requests often results in failed tests and I need to restart the build.

## Severity

tech-debt, but quite high

## Possible Fix

I'm wondering if the accept button is clicked before the action is associated to it.

**Comment by Matt-Yorkley** [comment]
I noticed this once yesterday. I've found in the past that if any sort of CSS animations/transitions are used on a UI element, capybara sometimes has trouble tracking it. This can sometimes be fixed vy adding or removing extra `expect` conditions at relevant points in the test, for example to expect something to be non-visible, then expect it to be visible immediately after.

**Comment by Matt-Yorkley** [comment]
Speaking of tech debt with tests, how far did the transition from poltergeist to headless chrome get?

**Comment by mkllnk** [comment]
Good question: https://github.com/mkllnk/openfoodnetwork/commits/headless-chrome

I can't remember how many tests are still failing. I think there is not much left, but the remaining specs are tricky to fix. Are you volunteering to take over? On one hand it's not the biggest priority, but on the other hand it will just become more and more difficult to resolve merge conflicts over time. That branch touches a lot of files. We should finish it or partly merge it soon.

**Comment by luisramos0** [comment]
Is there an issue for headless chrome? we should have one.
Agree Maikel, I'd merge what is done asap and leave the rest for later.

**Comment by mkllnk** [comment]
Yes: https://github.com/openfoodfoundation/openfoodnetwork/issues/2469

We can't merge all commits, because the browsers behave differently. Not all new code will work with the old PhandomJS.
