### ISSUE TITLE
Suggestion: Use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [openfoodfoundation/openfoodnetwork#2558]
Would you be up for automatically creating Dependency update PRs? I built [Dependabot](https://dependabot.com) to do that and it's free for open source.

I think it would save you a bit of time and help keep Open Food Network up-to-date, but I also have an ulterior motive for asking: I'm keen to get more open source apps using it so I can use the data on the CI runs for dependency updates to find bugs in new releases and point the maintainers to the failing CI run as a reproduction step.

Having well-tested open-source apps like Open Food Network use it should enable it to do awesome things, like automatically test release candidates of Rails and report back on any breakages, etc.

What do you reckon?

**Comment by daniellemoorhead** [comment]
@mkllnk @luisramos0 @sauloperez @Matt-Yorkley will leave you to respond to @greysteil re his suggestion.

**Comment by mkllnk** [comment]
It sounds like a cool project, but I'm not sure if our code is ready for it. We have some really old dependencies that won't be easy to upgrade. We also have a lot of dependencies.

@greysteil 

- How many pull requests would Dependabot create for our repository initially?
- Do you have an estimate of how many pull requests it would create per week?

We can give it a try, but it doesn't solve the bigger problem that we need to update *our* code to deal with newer dependencies. Actually updating is a one liner. And Github warns us about dependencies with security issues already.

**Comment by greysteil** [comment]
Thanks @mkllnk!

I rate limit the number of PRs it creates per run to 5, and to a maximum of 10 open PRs.

In this case, since you'd be doing me a favour as well, how about I do the initial work to get things up-to-date? Some gems are obviously tricker than others (Rails...) but a bunch should be pretty straightforward.

**Comment by mkllnk** [comment]
That's a nice offer. I just installed Dependabot for this repository. Let's see which magic it does.

**Comment by greysteil** [comment]
Awesome - I'll watch this repo and pitch in where I can. Looks like the first 3 PRs don't need any code changes at all. 🙂

**Comment by luisramos0** [comment]
Thanks a lot @greysteil 
I have reviewed the open PRs.
Although there's some good test coverage in place, for each of these PRs I think we should answer  the question (to someone who knows why we use the dependency): "what could this possibly break in the app?"

**Comment by kristinalim** [comment]
@greysteil Thought to mention that I find Dependabot really cool! It's easy to fall behind on dependency upgrades, and it's nice that it nudges projects to make little steps. The changelog snippet and commit summary are really handy too. :+1:

**Comment by mkllnk** [comment]
Yes, I'm quite impressed how well it is designed and how well it communicates. :-)

**Comment by greysteil** [comment]
Really pleased you're finding it useful. :-)
