### ISSUE TITLE
Spree related issues

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2584]
This epic groups all changes that can only happen after OFN is upgraded to work with spree 2-0-4.

**Comment by sigmundpetersen** [comment]
Hey @luisramos0 we keep epics in All the things and follow them on a higher level in https://github.com/openfoodfoundation/openfoodnetwork/projects/19

**Comment by luisramos0** [comment]
Now that spree is gone I dont think this epic makes sense. I am removing the two remaining issues, they become normal tech debt issues.
