### ISSUE TITLE
[Spree 2 Upgrade] remove dependency to MailMethod in db/seeds.rb

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2586]
## Description
Spree 2 does not have MailMethod any more, we need to adapt the existing calls. See epic #1957 for more details.

In db/seeds.rb this needs to be changed:

def create_mail_method
  Spree::MailMethod.destroy_all
  CreateMailMethod.new(
    environment: Rails.env,
    ...

## Expected Behavior
No dependency to MailMethod.

## Your Environment
Spree 2.0.4-stable branch.

**Comment by mkllnk** [comment]
Is this done?

**Comment by luisramos0** [comment]
this will be closed when #2590 is merged.

**Comment by sauloperez** [comment]
Closed by #2590
