### ISSUE TITLE
Make it possible to customize the link to user guide per instances

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#2593]
## Description
Link to user guide in admin mode is hard-wired at the moment. This issue is here to make changes to the code in order to allow each instance to have their own link.
![image](https://user-images.githubusercontent.com/6525576/44676848-abac0980-aa34-11e8-8428-2199fe467ef1.png)

## Acceptance criteria
In configuration > general settings, a field should be made available to add an external link. 
Only super admins can change this link.
For managers, when clicking on the user guide button, the user guide should open in a new page (same behaviour as now).
Example of user guide link in French: https://ofnuserguidefr.gitbook.io/guide-utilisateur-open-food-france

**Comment by daniellemoorhead** [comment]
This makes complete sense to do, but I wonder if it is a #goodfirstissue @RachL? Or is it a little more tricky for a newbie? @mkllnk what do you think?

**Comment by mkllnk** [comment]
It's a good first issue for people with experience with the ambition to work more on the OFN. It may be too much for a one-time contributor. I guess it will require to change around 4 files. It's touching the user interface, translations and storing value via Spree in the database.
