### ISSUE TITLE
[Cookie] Improve cookie policy page visualisation on mobile

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2600]
## Description
On mobile, the  table inside cookie policy modal page is unreadable. 
Modal is not horizontally scrollable so just can't be read.

## Expected Behavior
User can read cookie policy from modal.

## Actual Behavior
She can't.
![img_9439](https://user-images.githubusercontent.com/8135376/44707002-a89c3200-aaa3-11e8-9946-ba3a9d7dedb5.PNG)

## Steps to Reproduce
1. Go to home page and footer in aus production
2. From mobile, click on "cookie policy", scroll, you see the unreadable table

## Context
Part of cookie epic.

## Severity
S4

## Possible Fix
Table should be a paragraph for each cookie.
Myriam suggestion:
![capture du 2018-08-28 09-28-53](https://user-images.githubusercontent.com/8135376/44707449-d46be780-aaa4-11e8-897c-d272bb460a29.png)

About modal page vs new tab, for now we don't touch we will see with final review if navigation is ok as is. Keep a note here in case:
Luis "The modal is not taking up all screen height. I can make it full height, it's very easy to do it, I just need to test the other modals: registration and sign up. I am not sure how a normal page will make it better in terms of ux apart from making it full screen."

**Comment by myriamboure** [comment]
@RachL what do you think about my suggestion in term of UX for the cookie policy page display? Also @luisramos0 I guess then we would change the page for both mobile and desktop the same way, right?  But i think it's acceptable on desktop as well, correct me if I'm wrong.

**Comment by myriamboure** [comment]
Ok closing as I intergated that in this other issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/2601

**Comment by luisramos0** [comment]
yes, sounds good @myriamboure we change both desktop and mobile and we do it as part of #2601. Thanks!
