### ISSUE TITLE
[Cookies] Update text of cookie policy page (WIP)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2601]
## Description
Cookie policy page needs to be updated to make it readable on mobile (multi columns tables needs to be removed) + some light corrections on text.

## Expected Behavior
Content is https://docs.google.com/document/d/1RWvlXFzgpPtkhWhrm2OoWThHKwY87bu8e2l8-sPHa4w/edit?usp=sharing

## Actual Behavior
Content is slightly different and tables are not readable
![img_9439](https://user-images.githubusercontent.com/8135376/44712814-f029ba80-aab1-11e8-874a-0d825535094f.PNG)

## Steps to Reproduce
From footer click on cookie policy page.

## Context
In cookie epic.

## Severity
S4

## Possible Fix
See update cookie policy page content, I have update the tables to put the info on just one column, see example:
![capture du 2018-08-28 11-03-50](https://user-images.githubusercontent.com/8135376/44712865-13ed0080-aab2-11e8-873c-e189e04d26bd.png)

**Comment by luisramos0** [comment]
I'll try both "single column table" and "no table, just header and text", it may look better. I'll share screen shots here so we can decide.
