### ISSUE TITLE
[Product Import] Make product import submenu visible for all users + beta sentence

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2603]
## Description
Today only superadmins can see the submenu. This task is about adding it for all the users.

We want also to add a sentence at the beginning of the page saying "This feature is still in beta: you may experience some errors while using it. Please don't hesitate to contact us at [Insert email]. "

**Comment by sigmundpetersen** [comment]
Is it correct to say that this is blocked by #3845 and #3843 ? @lin-d-hop @RachL

**Comment by RachL** [comment]
@sigmundpetersen I actually don't think so. As we want to add a beta sentence and the contact of the super admin, I think we need to push this one forward. Other bugs will come up for sure, but at least we would have more data to play with.

**Comment by Matt-Yorkley** [comment]
Are we happy with the final wording of: 

"This feature is still in beta: you may experience some errors while using it. Please don't hesitate to contact us at [Insert email]."

And do we have an easy way to insert an instance-specific support email address for each instance?

**Comment by RachL** [comment]
@Matt-Yorkley both the sentence and the email can be handled by each instance in transifex Am I right?

**Comment by Matt-Yorkley** [comment]
OK. I've just put it as `...contact support` in the base translation, instances can change it to `...contact us at support@whatever.com` as they choose.
