### ISSUE TITLE
Translation missing on main menu

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#2617]
## Description
The "more" dropdown is not translated :
![image](https://user-images.githubusercontent.com/6525576/44862622-62013000-ac7b-11e8-8269-8f86fd0e5362.png)

## Steps to Reproduce
Log in as an admin, and check main menu in an non-english instance.

## Severity
S4

## Your Environment
* Version used: v1.18

**Comment by RachL** [comment]
I'm reopening this as it seems again untranslated in v2 :sob:

**Comment by djtrack16** [comment]
to log in as an admin, is that a special/particular username/pwd?

**Comment by mkllnk** [comment]
It's a permission to access all configuration options. It can be given to any username.
