### ISSUE TITLE
Packing Report Per Producer: Products listed for each customer

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#264]
Similar to OrderCycleSupplierTotals report, however this just displays total orders for each supplier.

For the StroudCo migration additional breakdown per customer is required to support the packing process.

Sort this list by Hub then producer, then product, then frozen/chilled, then customer ID (from predecessor system)

Fields:
Hub, Producer, Customer Name, ID, Product, Varient, Qty, Frozen/Chilled

**Comment by lin-d-hop** [comment]
PR #566 awaiting feedback on this one...

**Comment by NickWeir63** [comment]
Assuming that Aus Staging 2 has the latest version of this report I re-tested these packing reports.  It seems the same problem in happening.  I produced a report by supplier and a report by customer for the same period.  The report by supplier should show:
![image](https://cloud.githubusercontent.com/assets/10517702/9278910/db1a7560-42ab-11e5-9cc7-663758d3c915.png)
but it actually shows:
![image](https://cloud.githubusercontent.com/assets/10517702/9278924/ef23aa22-42ab-11e5-9fd7-26af16a2e88e.png)
@lin-d-hop it might be that your fix to this bug haven't got through to staging 2 yet.  But if you want me to send you the downloaded CSVs on this let me know.

**Comment by RohanM** [comment]
Hi @NickWeir63,

Staging2 currently has a different branch in it, so @lin-d-hop's work won't be showing at the moment.

**Comment by NickWeir63** [comment]
Sorry @lin-d-hop but it looks like the same problem is still happening.  I will email you a CSV showing my downloaded customer report and the supplier reports side by side.  The yellow highlighted bits (copied below) show that most of the Jess's Ladies products on the supplier report are allocated to the customer 'Hello Again' when actually most of them should be allocated to the customer 'Carol Mathews'
Let me know if you want me to do more testing
![screenshot 2015-10-07 09 46 17](https://cloud.githubusercontent.com/assets/10517702/10332913/63d436d8-6cd8-11e5-9857-3888ac542f21.png)
![screenshot 2015-10-07 09 46 37](https://cloud.githubusercontent.com/assets/10517702/10332919/70274f24-6cd8-11e5-88c1-cb972b9e3315.png)

**Comment by lin-d-hop** [comment]
@Nick, to avoid unnecessary tasks in the future please will you check if PR #674 has been merged before testing. If it is closed it will have been merged. Open means not yet merged. Thank you!!

**Comment by lin-d-hop** [comment]
Merged. Over to Nick for testing.

**Comment by NickWeir63** [comment]
tested and working perfectly - massive thanks to @lin-d-hop

**Comment by NickWeir63** [comment]
Just tested this on UK production and it works perfectly there too
Thanks Lynne
