### ISSUE TITLE
Translation missing on customer account

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#2646]
## Description
As a customer, the "Authorised shops" is not translated in credit card profile:
![image](https://user-images.githubusercontent.com/6525576/45120598-e7468200-b15e-11e8-92f7-1055bb21be74.png)

Same on the tooltip for authorised shops:
![image](https://user-images.githubusercontent.com/6525576/45120882-bca8f900-b15f-11e8-9900-96c82e40f328.png)

## Steps to Reproduce
On a non-english instance, log in as a customer, go to your profile and select the credit card tab.

## Severity
S4

## Your Environment
* Version used: v1.18

**Comment by sigmundpetersen** [comment]
@kristinalim says this should already be fixed (description in #2659). I don't know which PR it was fixed in. @RachL should we close this or do you want to stage and test to confirm? We can stage master to whatever staging server to test.

**Comment by RachL** [comment]
@sigmundpetersen thank you for pointing that out :) I'm closing for now and will reoppened it if necessary!
