### ISSUE TITLE
Packing Report Per Consumer: Include chilled/frozen items

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#265]
Report to needs to sort by hub then by customer, then alphabetically by product.

Report will be similar to OrderCycleBy Customer Report only requiring a subset of these fields:
Hub, Customer Names, PredecessorReferenceID, Product, Varient, Qty, Chilled/Frozen

Note #315 is a prerequistite for this issue.
Note #267 requires Frozen/Chilled Items to be recorded also.

**Comment by lin-d-hop** [comment]
@kirstenalarsen says that this report is often requested by other Hubs around the place as well so there is scope to do something nice and clever to make it work for everyone?

@kirstenalarsen are you currently tracking these requests on a wiki somewhere? Or how shall we capture the range of requests? Perhaps makes some notes here and we can have a chat at some point? The UK dev team won't have time for this one for a little bit so we have some scoping time :-)

**Comment by lin-d-hop** [comment]
@kirstenalarsen bump on the question above. Are there specific fields requested by others? In the short term I was just thinking of a simple implementation (no angular reports yet).

**Comment by kirstenalarsen** [comment]
Going to be doing some work summarising outstanding report stuff tomorrow so will bump back then - will be a 'wish list' page on discourse . .it's all coming together. Once is clear scope of works then moves into backlog :) yay

**Comment by kirstenalarsen** [comment]
okelly dokey. have copied paul's spec comments across to here - http://community.openfoodnetwork.org/t/uk-reports-todo/131 and pinged Lisa from food connect as she's the one I was thinking of

Have separated out the ones you've done (now in category 'Testing') from the ones you're still doing (now in category 'Doing') on the wiki - so you can improve testing notes / docs as you see fit.

**Comment by lin-d-hop** [comment]
PR #566 awaiting feedback on this one...

**Comment by NickWeir63** [comment]
I tested this on Aus staging 2 by setting up a 'July' order cycle for Stroudco and putting 2 orders through it.  Both orders included the 500ml yogurt from Jessies Ladies.  The supplier report (attached) correctly shows each order separately – 13 for Carol Mathews and 2 for Nick Test1.  However the customer report (attached) shows 15 for Nick Test1 and none for Carol.
![supplier packing report - yogurt glitch](https://cloud.githubusercontent.com/assets/10517702/8661692/533b80c0-29b1-11e5-9021-84cb1e71b043.png)
![customer packing report - yogurt glitch](https://cloud.githubusercontent.com/assets/10517702/8661698/5c2a12a0-29b1-11e5-82bc-73b9aa1a7086.png)

**Comment by lin-d-hop** [comment]
Merged. Over to Nick for testing.

**Comment by NickWeir63** [comment]
tested and working perfectly - thanks for all your work @lin-d-hop

**Comment by NickWeir63** [comment]
Just tested this on UK production and it works perfectly there too
Thanks Lynne
