### ISSUE TITLE
ActionView::Template::Error in spree/admin/payments#new

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2655]
## Error in OpenFoodNetwork

**ActionView::Template::Error** in **spree/admin/payments#new**
undefined method `amount' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5b63943e6f4a970017120327?event_id=5b91d2db002e1709057a0000&i=gh&m=ci)

## Stacktrace

    app/models/spree/calculator/flat_percent_item_total_decorator.rb:10 - map
    app/models/spree/calculator/flat_percent_item_total_decorator.rb:10 - compute
    app/serializers/api/payment_method_serializer.rb:6 - price
    app/helpers/admin/injection_helper.rb:128 - admin_inject_json_ams_array
    app/views/spree/admin/payments/_form.html.erb:2 - _68f38d8d3853ce3de2471e009762bf0d

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5b63943e6f4a970017120327?event_id=5b91d2db002e1709057a0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by mkllnk** [comment]
An enterprise in Australia can't create payments via the admin interface. The above error is raised when visiting https://openfoodnetwork.org.au/admin/orders/R513858701/payments/new. Somehow it seems possible that `Spree::Order.line_items` returns `[nil]` (at least one `nil` in an array).

This doesn't affect all enterprises. We haven't found out yet which circumstances trigger this.

**Comment by mkllnk** [comment]
My investigation so far: The root cause is that the `current_order` is not passed to the calculators. A buggy implementation then thinks that `nil` is a line item and tries to call `amount`. There are several things to fix here:

- Write a test that exposes this bug.
- Run git bisect to find which commit broke it. Probably Stripe work as it moved some of this code around.
- Get rid of `app/models/spree/calculator_decorator.rb`. It contains only one method `line_items_for` which is buggy. A better home for that method would be a service or lib class.
- Use that new method in `OpenFoodNetwork::Calculator::Weight` which has its own (currently better) implementation.
- Pass on `current_order` as option in `app/views/spree/admin/payments/_form.html.erb:2`.

Bonus points:

- Load the payment method data via the API in a JSON request instead of using ams.

The quick fix is:
```diff
diff --git a/app/views/spree/admin/payments/_form.html.erb b/app/views/spree/admin/payments/_form.html.erb
index e46b2febc..e075d1288 100644
--- a/app/views/spree/admin/payments/_form.html.erb
+++ b/app/views/spree/admin/payments/_form.html.erb
@@ -1,5 +1,5 @@
 <%= admin_inject_json "admin.payments", "currentOrderNumber", @order.number %>
-<%= admin_inject_json_ams_array "admin.payments", "paymentMethods", @payment_methods, Api::PaymentMethodSerializer %>
+<%= admin_inject_json_ams_array "admin.payments", "paymentMethods", @payment_methods, Api::PaymentMethodSerializer, current_order: @order %>
 
 <div data-hook="admin_payment_form_fields" class="row">
   <div class="alpha three columns">
```

**Comment by mkllnk** [comment]
8c6b8d5e84a796bd1b4171ff5393336f65c02b32 is the first bad commit for this particular bug. Before that commit, the bug was only in Stripe payments.

**Comment by sauloperez** [comment]
Could you work on it? Do you need any help?

**Comment by mkllnk** [comment]
Yes, I ran out of time, but created the pull request now.
