### ISSUE TITLE
Outstanding Payment Report for Order Cycle: Ability to sort by delivery type

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#266]

**Comment by lin-d-hop** [comment]
This report now shows a user balance as of #316 

Still missing legacy system ids.... referred to in issue #315

**Comment by kirstenalarsen** [comment]
Hi . . just looking at this, the order cycle selector should filter to only include OCs where the User is owner/manager of a participating Hub, OR User manages a Hub that has given P-OC to the Coordinator of that Order Cycle (i.e. the Hub is added to someone else's OC). See the filter against OC in other reports, I am working on actually documenting the logic to update with the new permissions.

![image](https://cloud.githubusercontent.com/assets/2911176/6103003/05109b34-b093-11e4-9966-33f7debd3f9c.png)

**Comment by lin-d-hop** [comment]
Hi @kirstenalarsen, from somewhat sunny Gympie :-)
Just to confirm, is this definitely the only report this doesn't work correctly on? I use the exact same method as the Customer and Products & Inventory reports.

If so I'm happy to dig deeper but initial investigations left me a little confused...

Thanks!

**Comment by lin-d-hop** [comment]
Now completed in PR #392 

Hopefully :-)

**Comment by lin-d-hop** [comment]
Closing as merged
