### ISSUE TITLE
[Spree Upgrade] Fix issues related to shipments in adjustment_spec

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2665]
Quite a few erros related to shipments in spec/models/spree/adjustment_spec.rb

**Comment by luisramos0** [comment]
First step done in #2670 .

There is more work to be done, we still need to make the tests related to shipping fees pass.

**Comment by luisramos0** [comment]
This issue will be closed when #2811, #2812 and #2816 are merged.

**Comment by daniellemoorhead** [comment]
>This issue will be closed when #2811, #2812 and #2816 are merged.

Does the issue still need to sit in the code review column until these are merged? Or can it be unattached from the others and reattached to one of these?

**Comment by luisramos0** [comment]
I think we can leave the issue connections as they are.
This is currently in code review and will be closed after all the 3 PRs are merged. I can do that manually hopefully next week after Maikels review.
