### ISSUE TITLE
Delivery Report for Order Cycle: Include outstanding balance & chilledItems

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#267]

**Comment by lin-d-hop** [comment]
This report has been added in #316 

Still needs to handle the chilled and frozen items... that's the next step

**Comment by lin-d-hop** [comment]
This is now completed in PR #392 

Awaiting feedback and merge hopefully...

**Comment by lin-d-hop** [comment]
Closing as merged
