### ISSUE TITLE
Enterprise Fee Summary Report

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2673]
## What is the problem we are solving
Hubs cannot access information about fees and how much they have contributed to totals, as there is no report that reveals them. This is significantly undermining/ limiting the use of the fee functionality. Hubs are not making more use of the flexible fees in OFN e.g. fundraising, calculate food transport costs, levy extra charges on distant products, etc. OFN allows for these things, but without the ability to total different fees in a report, it is too time consuming to calculate these totals ‘by hand’ using customer orders. 

## Success factors = expected outcome
Hubs can easily access information about how much money has been collected from customers by each fee type and fee owner. More example of specific use cases (Hubs with specific fee info requirement) see https://community.openfoodnetwork.org/t/report-that-isolates-various-enterprise-fees/1361/15

## Metric
Hubs can use sophisticated fee structures because the information about them is easily accessible

## Useful information for/from inception

The Report should have its own section on admin/reports called Fee Summary Report.

It will have a wide range of filters. See mockup in https://github.com/openfoodfoundation/openfoodnetwork/issues/2672

This google spreadsheet shows what the report should display and the order in which it should do so - 'THIS By Customer' sheet in this google sheet  https://docs.google.com/spreadsheets/d/1pnJwHgBo2sokdcwNoLquYlVh8ICUcx6X4J2ZAMnRyio/edit#gid=474722894

## Link to the "Icebox" item in Discourse
https://community.openfoodnetwork.org/t/report-that-isolates-various-enterprise-fees/1361

## First feature candidate to be implemented
Create report that generates information as per the 'THIS By Customer' sheet in this google sheet  https://docs.google.com/spreadsheets/d/1pnJwHgBo2sokdcwNoLquYlVh8ICUcx6X4J2ZAMnRyio/edit#gid=474722894

**Comment by RachL** [comment]
@kirstenalarsen about the two issues in "all the things". Are those easy/small enough that we label them "improvement" or should we migrate them to discourse?

**Comment by kirstenalarsen** [comment]
I am going to say they are likely small, improvements . . Likely it would be able to be used more with these two things, but seems silly to do without demand. So I'd say they can be labelled improvements. How do improvements ever get done?

**Comment by RachL** [comment]
@kirstenalarsen the same way as s3 bugs, unless it is an easy issue then we can also label it "good-first-issue".

**Comment by sigmundpetersen** [comment]
#2657 and #3465 labelled and moved to Bug backlog. Should we remove the remaining issues and close this epic then?

**Comment by sigmundpetersen** [comment]
Okay I removed the remaining open issues from the Epic and closed
