### ISSUE TITLE
Define best practice for a local dev environment

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#268]
We have a slightly confusing state for setting up dev environments:

* ofn_deployment can be used to create a local OFN install, but its no use for development because it doesnt use a local copy of openfoodnetwork on the host machine.
* This https://github.com/openfoodfoundation/openfoodnetwork/pull/246 offers a separate script but is not merged and only works on Linux.

I'd like to work out what best route to take. Currently this would hold up Aidan.

Would it make sense to use ofn_deployment modified to just provision and do some other steps, but not install the openfoodnetwork project?

**Comment by elf-pavlik** [comment]
@Em-AK wrote easy step by step instructions here which worked out well for everyone participating in Berlin hackweek
* https://wcs-2015.hackpad.com/Install-process-Open-Food-Network-gEYPuM8pQtQ

**Comment by pmackay** [comment]
How do these differ from the instructions in the OFN README? Could they be merged or something? 

A small plea to keep OFN docs to Discourse or Github, otherwise it creates more places to look. :)

**Comment by Em-AK** [comment]
Yes I will diff it with the README and do the update if needed.

**Comment by pmackay** [comment]
@Em-AK were you able to compare the docs? Does anything from your notes need folding back into the OFN docs?

**Comment by pmackay** [comment]
Added some notes to README. Otherwise pretty much most of key content from hackpad doc covered.
