### ISSUE TITLE
[Spree Upgrade] Handle shipping_method_id in checkout

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2683]
We need to look at both
- app/assets/javascripts/darkswarm/controllers/checkout/checkout_controller.js.coffee
- app/assets/javascripts/darkswarm/services/checkout.js.coffee
and 
- app/views/checkout/_shipping.html.haml

and review/replace shipping_method_id usage.

For reference, other files that may need review/changes:
- app/controllers/checkout_controller.rb
- spec/requests/checkout/failed_checkout_spec.rb
- spec/requests/checkout/stripe_connect_spec.rb
- spec/javascripts/unit/darkswarm/services/checkout_spec.js.coffee
- spec/controllers/checkout_controller_spec.rb

See [this commit](https://github.com/openfoodfoundation/openfoodnetwork/pull/1651/commits/05aeb03839ca02942d0e68894316f94f113a0e16) for line numbers.

**Comment by sauloperez** [comment]
I agree with your plan. I don't really understand what you mean by

> With this I think we will be able to drop the order.shipping_method_id column (which is a non-sense column in the multi shipments world anyway, not totally nonsense in OFN2 because we force 1 order to have 1 shipment).

We'll be able to remove the column in OFN2 or not?

**Comment by luisramos0** [comment]
yes, we will drop the column.

I was just re-iterating the difference between spree v2 model and ofn v2 model. the column is non-sense in spree 2 because 1 order - n shipments. BUT, although we WILL drop it, the column would still make sense in ofn v2 because in ofn v2   1 order - 1 shipment. Sorry, I could have committed that, it just creates unnecessary complexity.

**Comment by luisramos0** [comment]
I think this will take me a bit of time to get finished so I'll wait for @mkllnk feedback before I start the work to be sure we are all aligned.

**Comment by luisramos0** [comment]
fixed in #2216
