### ISSUE TITLE
[Spree Upgrade][Models] Fix order_spec and orders_controller spec tests with shipment fees and taxes (3 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2685]
Originated from #2009.
We have to find what's broken in the shipping fees calculation and fix them in spec/models/spree/order_spec.rb. It may be a code change, it may just be adapting tests.

Acc Criteria: order_spec tests passing.

**Comment by HugsDaniel** [comment]
@luisramos0 are you on this one ? If not I can take it

**Comment by luisramos0** [comment]
I am not on this one because it is a tricky one :-) I don't recommend it, but you are welcome!!!

The on_demand issue (https://github.com/openfoodfoundation/openfoodnetwork/issues/2435) could be a good one for you (but it's not simple).

**Comment by luisramos0** [comment]
I am adding one orders_controller spec broken test to this issue as it will require the same solution as seen in PR #2864 
The current issue is that the solution in #2864 is not acceptable.

These are the 2 errors in order_spec :
```
 13) Spree::Order a completed order with shipping and transaction fees removing line_items updates shipping and transaction fees
      Failure/Error: expect(order.adjustment_total).to eq expected_fees - shipping_fee - payment_fee
      
        expected: 8
             got: 13.0 (#<BigDecimal:7f385bdedb78,'0.13E2',9(18)>)
      
        (compared using ==)
      # ./spec/models/spree/order_spec.rb:685:in `block (4 levels) in <top (required)>'

  14) Spree::Order a completed order with shipping and transaction fees changing the shipping method to one without fees updates shipping fees
      Failure/Error: expect(order.shipment.adjustment.included_tax).to eq 0
      
        expected: 0
             got: 1.2 (#<BigDecimal:7f385bb91208,'0.12E1',18(27)>)
      
        (compared using ==)
      # ./spec/models/spree/order_spec.rb:721:in `block (4 levels) in <top (required)>'

```


and this is the error in orders_controller spec:

```
33) Spree::OrdersController removing items from a completed order with shipping and transaction fees updates the fees
      Failure/Error: expect(order.shipment.adjustment.included_tax).to eq 1.2
      
        expected: 1.2
             got: 0.0 (#<BigDecimal:7f7df5ed0858,'0.0',9(18)>)
      
        (compared using ==)
      # ./spec/controllers/spree/orders_controller_spec.rb:191:in `block (4 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
3 month later and I still don't know what to do here 😭 
Maybe someone else wants to look at #2864 and find a better solution.

**Comment by sauloperez** [comment]
I can take a look

**Comment by luisramos0** [comment]
should be ready to close BUT I see spec/controllers/spree/orders_controller_spec.rb:219 broken in 2-0-stable build... this should be green after 3366, right @sauloperez ?

**Comment by sigmundpetersen** [comment]
seems this is a new spec fail that appeared after the original one was fixed?
