### ISSUE TITLE
VAT Support: Add tax_category dropdown to New Product form

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#269]
In the UK certain categories of products are VAT exempt and others not, for instance you pay 20% VAT on sales of fruit juice but 0% on vegetables. Tax rates reference: https://en.wikipedia.org/wiki/Value_Added_Tax_%28United_Kingdom%29#Rates

Confirmed the VAT stuff can all be done within the current spree settings. Custom tax zones (ie. UK_VAT) by country can be entered and different tax rates for different product categories set up per tax zone.

The one issue is that product category (ie. vegetables) and tax category (ie. also vegetables) are seperate fields, and the tax category dropdown is not currently displayed on the add new product page (you have to manually edit the product afterwards and scroll down past a large list of settings to find it). 

Also, in order to have multiple tax levels for different product categories you need to set one of them (20% or 0% in this instance) as the default. This could cause issues if our non-computer-savvy producers forget to select the right thing when adding a new product, so maybe some simple validation on the add product page that checks if they've properly picked a valid option and gives a clear flash message otherwise would sort it.

Spree tax reference: http://guides.spreecommerce.com/developer/taxation.html

**Comment by pmackay** [comment]
@RohanM is this completely done and could be closed? 

cc @lin-d-hop

**Comment by lin-d-hop** [comment]
This is done according to Discourse and my quick investigations. Testing done in #273
