### ISSUE TITLE
VAT Support: Add optional column to Product list to display tax_category for each product

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#270]
The product page already has a dropdown option to view different fields related to the products, would be nice to be able to scroll through the list and see if the tax_categories are set properly on the products.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley did you conclude this isn't really necessary?

Closing at this stage. Can be reopened if deemed necessary later.
