### ISSUE TITLE
Update icon colours

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2703]
Change icons in OFN Header to orange, including Hamburger. Text stays black e.g.

![image](https://user-images.githubusercontent.com/2911176/45486267-cfde4900-b79d-11e8-91cc-7b7919329519.png)

Google slide 19 - https://docs.google.com/presentation/d/10I8-3mRjxnPUXtEk04X3UERVPEPvqPjrEdF37_1KpmE/edit#slide=id.g40ea76c80f_0_65
Zeplin: https://zpl.io/agNJxxQ

**Comment by mllocs** [comment]
I noticed that #2704 and #2706 are quite related with this one, I'll probably tackle the three of them at once 😄

**Comment by daniellemoorhead** [comment]
Hey @mllocs how are you doing this this? Any progress? 

Just checking in, last update was 22 days ago so if you've been too busy I'll move this one back to dev ready till you're ready to pick it up again. Or if you're slowly working on it then that's great. Would like an update though, just so we know 😄

**Comment by daniellemoorhead** [comment]
I'm (sadly) moving this and #2704 and PR #3252 back into Dev ready as @mllocs is on holiday for a month and no one else is available to finish it.

Ping @kirstenalarsen as an FYI

**Comment by luisramos0** [comment]
hello, can I get access to the zeplin project?

**Comment by RachL** [comment]
@luisramos0 I have just invited you. Tell me if it has worked.

**Comment by luisramos0** [comment]
yes, it worked, thanks!

**Comment by lin-d-hop** [comment]
Love this!
Everything looks great.
My only note is that when google auto translates a page this changes the header. I don’t think this is an issue for us :-)

https://docs.google.com/document/d/1qGe_W4LaOj_lFYDtJpH3gg_-XAjXYqCGhwfl1S4YzQQ/edit#
