### ISSUE TITLE
Update cart icon and panel

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2704]
Change element from
![image](https://user-images.githubusercontent.com/2911176/45486376-3499a380-b79e-11e8-93b3-76a36322a5ba.png)

to 
![image](https://user-images.githubusercontent.com/2911176/45486339-10d65d80-b79e-11e8-8ba8-e40308a09b1b.png)

Google slides 5 & 12

**Comment by Matt-Yorkley** [comment]
Closing, as I'm pretty sure this change is already in `master`. Feel free to reopen if I've misunderstood.
