### ISSUE TITLE
[mobile ux] Restyle Empty Cart display

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2706]
## In a feature branch or master?
No feature branch required, all changes contained in this one story 🎉 

## Description

As a shop
When a shopper opens their empty shopping cart on my shop
I want a way to send them to my shop tab so they start shopping

## Acceptance and Testing
**HOW IT WORKS NOW**
![Screen Shot 2020-02-07 at 3 38 59 pm](https://user-images.githubusercontent.com/10949052/74001517-0da9c600-49c0-11ea-86e0-a2ff8f3304cf.png)

**HOW IT SHOULD WORK**
mobile
![image](https://user-images.githubusercontent.com/2911176/45668785-5f4e7800-bb61-11e8-881e-8c8158aafef7.png)

tablet
![Screen Shot 2020-02-07 at 3 40 05 pm](https://user-images.githubusercontent.com/10949052/74001561-3467fc80-49c0-11ea-9420-98d5c32f0b8c.png)

desktop
![Screen Shot 2020-02-07 at 3 40 19 pm](https://user-images.githubusercontent.com/10949052/74001563-3631c000-49c0-11ea-8efa-1e7711937d90.png)

- [ ] copy stating the cart is empty displays on mobile/table/desktop
- [ ] on mobile there is a call to action button that says "take me shopping!"
- [ ] If the user has a previous shopfront in a cookie, it takes them to that shop
- [ ] If the user does not have a previous shopfront cookie, it takes them to /shops
- [ ] Button copy can be set at instance level (ie. transifex)

Zeplin: https://zpl.io/aBN0Q4L

**Comment by eelcodevlieger** [comment]
That's a much cleaner design.

An empty cart currently shows two rows of button, presumably the top and bottom of the empty line item list.

As an interim solution we could hide the bottom buttons if the cart is empty. The 'Checkout now' button is also not functional on an empty cart.

![image](https://user-images.githubusercontent.com/44651943/56922513-424b3180-6ac0-11e9-830f-e99dc7321f6b.png)

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley the "Take me shopping!" button on mobile isn't on the PR. I'm going to create a testing doc and test the rest but I already know this is missing.

Do you want to create a new PR for it attached to this one, or add it to the other one? It's ok for it not to be in a branch and merged separately.

**Comment by daniellemoorhead** [comment]
Also, I assume that all the copy for this epic is in transifex, correct?

**Comment by daniellemoorhead** [comment]
@yukoosawa with the take me shopping button should it display if the user opens the cart from a shop, as it does when they're on a non-shop page? That's how the button works now (ie if on a shopfront do not display), making sure that's the interaction you designed?

**Comment by yukoosawa** [comment]
@daniellemoorhead I'm ok to leave it as is on AU Staging -- but the intention was to have the 'take me shopping' button persist in the View Cart.

If the user HAS NOT visited OFN before / cleared cookies / viewing in private browser mode:
- From the Home, Shop List, Map, and Producer List pages, the 'Take me shopping' button should take the user to the Shop List page.

If the user HAS visited OFN before / last visited shop saved in cookies / viewing in private browser mode within the same session:
- From the Home, Shop List, Map, and Producer List pages, the 'Take me shopping' button should take the user to the last visited shop.

Currently the 'Take me shopping' button is missing from the View Cart when accessed from the Shop page. This could be one of the ways we're shortcutting users to their last visited shop in Mobile (see slack discussion from today). Although in the current Covid-19 world, is the assumption that customers only want to shop from the same previous shop still true???

As for the empty View Cart on an individual Shop page -- here it's fine to leave off -- although I had assumed we would leave it on for consistency and use it as another 'close' button.

**Comment by daniellemoorhead** [comment]
>Currently the 'Take me shopping' button is missing from the View Cart when accessed from the Shop page.

@Matt-Yorkley I checked this in an icognito window on staging and it doesn't show up on /shops right now. I'll add this to the list of things to be fixed.

![Screen Shot 2020-06-16 at 5 21 22 pm](https://user-images.githubusercontent.com/10949052/84743851-d98d8400-aff5-11ea-903b-1581129ccb26.png)
