### ISSUE TITLE
VAT Support: Add VAT information to sales reports

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#271]
Ability to see how much sales tax applies to each order, and display this in reports.

**Comment by RohanM** [comment]
@Matt-Yorkley, I've taken your branch and done some work to clean it up. The current work in progress is at https://github.com/openfoodfoundation/openfoodnetwork/compare/Matt-Yorkley-reports_vat?expand=1 . You can see my commits on 8th Jan.

There is still some work outstanding. We need to tell Spree to charge the customers with the specified shipping tax rate, which its not doing as of yet. Also, in the report, I'm not confident that the figures are being pulled from the correct place. At the moment, the shipping_tax_rate is being pulled from the config variable, but we really want to report on what was charged at the time the order was placed.

All in all, it's coming together. I'll see if I can get it sorted and merged tomorrow.

**Comment by Matt-Yorkley** [comment]
I was working on the assumption that shipping tax would be included in the shipping cost... 

Would another config option to explicitly have it included or not included be better?

**Comment by Matt-Yorkley** [comment]
My earlier comment above (22 Nov) is related to the question of if it's necessary to record more details on sales about what tax was charged at the time, as opposed to calculating it from the config variables. It needed the database to be altered though, so I wanted to get feedback first...

**Comment by RohanM** [comment]
Aah, gotcha. With the tax included in the shipping cost, things are simpler. However, I'm a bit uncertain about the calculations in the report. They seem to be for the case where tax is not included in the price and you want to add it on, eg.

```ruby
# Sales tax
totals[:sales_tax] += line_item.amount * tax_rate

# Shipping tax
shipping_cost * Spree::Config[:shipping_tax_rate]
```

To work out how much tax is included in a price, wouldn't it be something like this?

```ruby
# Sales tax
totals[:sales_tax] += tax_rate * line_item.amount / (1 + tax_rate)

# Shipping tax
tax_rate * shipping_cost / (1 + Spree::Config[:shipping_tax_rate])
```

**Comment by RohanM** [comment]
As to whether to have a config option to record whether tax is included on shipping or not, we could do that by using the TaxRate model, which already has that option. However, since tax is included for both UK and Aus, we don't need to build the functionality for adding tax yet.

**Comment by RohanM** [comment]
I agree with your November comment that it would be good to record the tax charged on items. In most cases, Spree already does this through the Adjustments system: https://guides.spreecommerce.com/developer/adjustments.html. This doesn't cover tax on shipping yet though, as far as I can see. I'll have a look and see if I can work out a way of doing that.

**Comment by Matt-Yorkley** [comment]
You're right about the calculations being for added tax instead of inclusive. I've got a feeling the adjustments weren't recording inclusive tax data last time I looked, but I could be wrong. Also not recording shipping tax, as you mentioned.

**Comment by RohanM** [comment]
I had a look and adjustments seem to record inclusive tax data, but the adjustments are recorded against the line items, not against the order. They're accessible via `Order#price_adjustments`.

I've updated the branch to use the correct calculations. And I'll see if there's a way to include shipping in price adjustments, if that turns out to be the right way to do it.

**Comment by RohanM** [comment]
I've just pushed a few bits and pieces. The report now pulls the per-item sales tax from the adjustments, so it's reporting on the tax charged at invoice time **for the items**. I looked into doing this for shipping tax as well, and it's quite tricky with our version of spree. I'm leaving it for the moment and looking at two other tasks:

- Displaying the tax on shipping in the checkout
- Charging tax on fees. At the moment it's not charged, and I think it should be charged on all order-wide fees and on fees for items that attract tax. Does this sound right to you?

**Comment by RohanM** [comment]
I'm heading away for a couple of weeks. I've written up the current state of play (what we need) on a wiki page: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Sales-Tax

**Comment by Matt-Yorkley** [comment]
Hmm... I'm not sure about tax rates on different services. There's a list of all goods and services for VAT here: https://www.gov.uk/rates-of-vat-on-different-goods-and-services but I couldn't find anything useful on additional services like packing or admin, which aren't listed (that page seems to be the definitive list of what is and isn't taxed, and at what rate). Shipping is definitely 20%. 

This page seems to indicate that secondary services like admin don't have VAT applied as long as they are itemised/invoiced as being distinct from the goods being sold: http://www.ukbusinessforums.co.uk/threads/vat-on-admin-fees.207201/

**Comment by lin-d-hop** [comment]
The sales tax report looks like it's doing what this says on the tin.

@NickWeir63 can you confirm that this is the data needed for StroudCo and that it is working as expected.

**Comment by NickWeir63** [comment]
@lin-d-hop gave me a very helpful training session yesterday - big thanks Lynne and we got our heads around how this all works.   It is fantastic - even bigger thanks to @RohanM and @Matt-Yorkley for all your work on this.  We are very grateful.  So far all the tests I have run today have worked out perfectly and the report gives us what Stroudco needs for its VAT return.  
THANK YOU!
Shall I close this issue now?

**Comment by lin-d-hop** [comment]
Nice one @NickWeir63. If you're satisfied that this works as we need it, with multiple tax codes and some fees being taxed, some not, then I say we close.

@RohanM We saw yesterday how tangly tax is. Well done on all your work on this and massive thanks!
