### ISSUE TITLE
Shopfront search (mobile)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2712]
Sequence of actions is best seen in slides under Iteration 4 (currently 14-21) - https://docs.google.com/presentation/d/10I8-3mRjxnPUXtEk04X3UERVPEPvqPjrEdF37_1KpmE/edit#slide=id.g41f0a2d615_0_8

![image](https://user-images.githubusercontent.com/2911176/46519930-8aed9400-c8bd-11e8-8662-2169480f67f7.png)

Zeplin design: https://zpl.io/25rBPXe
Hover / press states:  https://zpl.io/VQE63pW

Notes:
Search field hint text reduced to accommodate 320px (small) devices
On field focus device keyboard is presented
In mobile no explicit ‘search’ button - device keyboard should show the correct ‘search’ button
In iOS/Safari this is typically a blue ‘go’ or ‘search’ button
In Android/Chrome this is typically a ‘magnifying glass’ icon
In mobile, once the user starts typing a search term, ‘x’ icon appears in field to allow for easy clearing of the text typed in field.
Zeplin components: https://zpl.io/VknQPmZ

NB. On scroll search/filter bar stays sticky

**Comment by daniellemoorhead** [comment]
@yukoosawa and @kirstenalarsen I saw something new in this issue today that I hadn't realised was in scope:

>NB. On scroll search/filter bar stays sticky

This isn't evident in Zeplin so I hadn't included it in scope. 

Can you please explain how it's supposed to work? The search bar is already in the middle of the screen, it doesn't leave a whole lot of room to scroll through products. The main nav is already persistent, so how do you see the search bar working with this and the shop header/order cycle section?
<img width="237" alt="Screen Shot 2019-12-18 at 5 23 32 pm" src="https://user-images.githubusercontent.com/10949052/71061007-24e7e680-21bb-11ea-82e5-16670bcf5ecb.png">

More information please! 

![](https://media3.giphy.com/media/zuazhWMxfLp9m/giphy.gif)

**Comment by yukoosawa** [comment]
Will preface this comment by saying the following interaction pattern is a nice-to-have :)

### **Proposed behaviour**
As the user scrolls down the page in mobile/tablet/smaller viewports
- The main nav is sticky
- The shop header + OC selector scrolls away
- The search/filter bar scrolls up until it is positioned directly below the main nav and then stays sticky
As the user scrolls back up and reaches the top of the page
- The shop header + OC selector reappear correctly positioned

### **Why**
Currently shopfronts don't use any pagination, but instead lazy load products as you scroll down. For shops with a long list of products, getting back to the top of the page to search/filter to find the thing you want in the long list is a pain on smaller devices.

### **How**
**Option 1:** Use CSS3's position:sticky with the top positioned specified to accommodate the main nav - https://developer.mozilla.org/en-US/docs/Web/CSS/position). Browser support for this is: 

![image](https://user-images.githubusercontent.com/19785399/71869739-27b26900-30e1-11ea-8bfb-ae07bddb20a9.png)


**Option 2:** Use JS solution like this - https://codepen.io/eagleeyejack/pen/eomOqo

### **What will it look like**
![Mobile: Shop - Sticky Search](https://user-images.githubusercontent.com/19785399/71869671-e3bf6400-30e0-11ea-8d1f-c3f87ffd2d10.png)

**Comment by daniellemoorhead** [comment]
Closed as replaced by stories within epic #4601
