### ISSUE TITLE
Check responsiveness of all elements

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2714]
Responsive grid layouts provided in slides 
https://docs.google.com/presentation/d/10I8-3mRjxnPUXtEk04X3UERVPEPvqPjrEdF37_1KpmE/edit#slide=id.g40ea76c80f_0_18

![image](https://user-images.githubusercontent.com/2911176/46519285-0f8ae300-c8bb-11e8-91d4-18cb9b656140.png)

**Comment by daniellemoorhead** [comment]
Separate card not required, this will be needed as the base for all work done redoing mobile. Closing.
