### ISSUE TITLE
[mobile ux] Sticky footer element on Cart dropdown

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2718]
## In a feature branch or master?
View cart feature branch 

## Description
**- As a:** shopper
**- On page:** main nav cart view
**- I want to be able to do:** scroll through the items in my cart while still seeing the edit cart and check out buttons

## Acceptance Criteria & Tests

- [ ] Edit cart and Checkout buttons stick to bottom of screen
- [ ] Product list scrolls when the list is longer than the screen height.
- [ ] Page/body scroll disabled when the cart is open + scrollable -- to ensure users can't accidentally scroll the background content.

Mobile
<img width="242" alt="Screen Shot 2020-01-22 at 4 27 42 pm" src="https://user-images.githubusercontent.com/10949052/72868071-0d10fe80-3d35-11ea-8599-5ab60c90c938.png">

Tablet
<img width="477" alt="Screen Shot 2020-01-22 at 4 28 07 pm" src="https://user-images.githubusercontent.com/10949052/72868069-0bdfd180-3d35-11ea-8054-692e7ab599b4.png">

Desktop
<img width="787" alt="Screen Shot 2020-01-22 at 4 28 26 pm" src="https://user-images.githubusercontent.com/10949052/72868067-0aaea480-3d35-11ea-8691-dd2f4d0555b7.png">

Zeplin: https://zpl.io/bAEMxv8

**Comment by daniellemoorhead** [comment]
@yukoosawa there's no scroll bar design on these screenshots for when product list is longer than screen height. Should there be? Or no scroll bar present?

**Comment by yukoosawa** [comment]
@daniellemoorhead Scrollbar visibility should be dictated by a user's setup/preference -- usually specified at the OS/browser level -- not by the application.

As long as the cart content is scrollable if taller than the viewport, then the right scrollbars will appear based on individual preference/device/touchscreen vs mouse driven/browser.

I would recommend however disabling the page/body scroll when the cart is open + scrollable -- to ensure users can't accidentally scroll the background content.

**Comment by daniellemoorhead** [comment]
Passed testing in #5480
