### ISSUE TITLE
[subscriptions] bug when trying to create a subscription if no current or future OC has the schedule associated

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2740]
## Description
A hub manager has created a schedule, associated to a first OC, and has created subscriptions.
The OC has closed and the next one has not yet been set up. 
Then she wants to create a new subscription > she gets an error message saying "product X is not available for the selected schedule". This is very confusing, as the user has followed the user guide, created a schedule, a first OC using that schedule... but it doesn't work, she can't add a new subscription !
![capture du 2018-09-17 23-46-33](https://user-images.githubusercontent.com/8135376/45652123-ec4af000-bad3-11e8-98ec-dffe3ceacf52.png)

## Expected Behavior
Hub manager manages to create a subscription after having created a schedule and a first associated OC.

## Actual Behavior
IF there is no active or planned OC using that schedule, the creation of a new subscription display confusing error message "product X is not available for the selected schedule" and can't proceed.

## Steps to Reproduce
1. For a given hub, enable subscription (done by super admin), then create a schedule
2. Associate it with one OC.
3. Add a subscription for product X > it works
4. OC closes.
5. Add a subscription for product X > it doesn't work

## Context
Reported by a French user beta-testing subscription (or more accurately "standing orders" ;-)) feature.

## Severity
S3 - there is a workaround which is to make sure you have an active or planned OC using that schedule to set up a new subscription. Which is doable, need to be added to all user guides though.

## Your Environment
* Version used: v1.18 on French instance (not sure which version it is in Canada) so it's not linked to the last v1.19 release.
* Browser name and version: Firefox Quantum 62.0
* Operating System and version (desktop or mobile): Ubuntu 18.04.1 LTS

## Possible Fix
- Easy fix: if you click on "new subscription" and there is no active or planned OC using that schedule, display straight away error message saying "subscription can only be created on active schedules, and no current or planned OC is using that schedule. Add one before creating a subscription"
OR
- More user friendly: make it possible to create a subscription even if no current or future OC uses the schedule. Maybe it's enough technically that past OC have used it?

**Comment by myriamboure** [comment]
@sstead @daniellemoorhead @kirstenalarsen I let you prioritize that one among other bugs reported from actual use of standing orders feature. I think it's quite annoying and really not well explained. I suggested a quick fix, not ideal but can make the deal for now. If you agree add it to dev ready. I added it to both subs and bug management project board, not sure when a feature is released, even in beta, if it should still be on project board... for me when released, should be treated as bugs simply.

**Comment by kristinalim** [comment]
@myriamboure This is identical to #2243 which I already addressed in PR #2733. (Although the PR is not yet ready for code review - moving it as soon as I can get it to have a green Semaphore build. There has been an unrelated intermittent failure which the PR has not yet been able to get past.)

Feel free to reopen in case I misunderstood and this is not a duplicate. :slightly_smiling_face:

**Comment by myriamboure** [comment]
Cool, thanks @kristinalim ! I think you are right, the other issue was about editing subs but same same for creating new ones ;-)
