### ISSUE TITLE
Possibility of skipping records when filtering "Orders and Distributors" report by time

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#2748]
Basic user flow when filtering the report can result to records being skipped.

It's likely this affects other reports.

## Description

When selecting a time through the picker, the user ends up with timestamps like `2018-09-17 00:00:00 +1000` (`HH:MM:SS` of `00:00:00`). The report then finds records completed between start time and time, _exclusive_ - the boundaries are not included.

Let's say I generate order reports weekly. If I don't know about this quirk, I would just set the dates to:

* `2018-09-10 00:00:00 +1000` and `2018-09-17 00:00:00 +1000` for last week
* `2018-09-17 00:00:00 +1000` and `2018-09-18 00:00:00 +1000` for this week

If there is an order completed exactly on `2018-09-17 00:00:00 +1000`, this record would not be included in either report. This is an edge case, but possible.

## Expected Behavior

1. **Option 1:** End time should use `23:59:59` as default.
2. **Option 2:** Include start time (greater than or equal to) and exclude end time (less than) in the results.
3. **Option 3:** Add a hint in the report filters that makes this clear.

For Option 1, we would need to verify that the DBMS does not store milliseconds, or else this solution would not include `23:59:59.010`.

## Steps to Reproduce

As distributor enterprise owner:

1. Go to "Reports" > "Orders and Distributors".
2. Copy the "Order Date" of a sample order.
3. Set the order date as the end time. Select any close enough start time, and click "Search". Notice that the order is not included.
5. Set the order date as the start time. Select any close enough end time, and click "Search". Notice that the order is not included.

## Context

I'm working on the Enterprise Fee Summary Report.

## Severity

bug-s3: a feature is broken but there is a workaround

**Comment by kirstenalarsen** [comment]
@kristinalim this is ringing a bell for me and I have a feeling that this has been picked up somewhere else before - have you / could you search github and discourse to see where it is mentioned and if there is previous discussion on whether or how to fix it?

also checking with the human font of all knowledge - @myriamboure do you know if/where previous discussion of this is?

**Comment by kristinalim** [comment]
@kirstenalarsen I had done a proper search only in Github. I did so in the forum just now too. Nothing that caught my attention talks about the same.

**Comment by myriamboure** [comment]
Interesting @kristinalim this is well spotted ! I would exclude option 3 as even if edge case, we can't say that if an order is made at a certain hour it's not taken into account... Or maybe if we tell it then we need to tell to set up end time at 23:59:59 BUT this is not possible, or pretty hard to do with current time setup, it works by 15 min if I change it automatically change back by 15 min periods. 

@kirstenalarsen from my knowledge (which is not comprehensive ;-)) this has not been covered by any other issue, I was not aware of that behavior. Not prioritary as the likelyhood is very unprobable, but still, this is to fix somehow.

Option 1 or 2, both would work IMO so I would say let's choose the easy one. I guess it is the same for order cycle setup btw, not only reports. If an order is made and an OC finish at 00:00:00 and the other starts 00:00:00, on which OC is made the order?

**Comment by lin-d-hop** [comment]
Perhaps this should be within the acceptance criteria for the upcoming reports work... Will link in.
And closing :trollface: #gitcull2021
