### ISSUE TITLE
Show console error and failed HTTP requests in issues

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2758]
## Description

Some bugs do not provide enough context to be discussed properly and having error messages can provide great insight.

Having a screenshot of the browser console and the HTTP responses can help us a great deal.

## Expected Behavior

Ask for the browser's console error messages and the responses of the HTTP failed requests in the Github issue template.

## Context

This stems from https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1537445733000100

**Comment by lin-d-hop** [comment]
We're much better at providing clear issues now. Closing #gitcull
