### ISSUE TITLE
Cannot Duplicate Order Cycle

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#2764]
## Description

Occasional reports of Order Cycle duplication giving a 422 error:
The change you wanted was rejected. Maybe you tried to change something you don't have access to.
An error that is still a cat!

## Expected Behavior

When the duplicate OC button is clicked a duplicate of the OC should appear with all the variants.

## Actual Behavior

When the duplicate OC button is clicked the 422 grumpy cat error page displays. when reloading the page the OC has been duplicated but the OC has no variants.

Error in bugsnag is:
```
ActiveRecord::RecordInvalidadmin/order_cycles#clone
Validation failed: Variants unit value can't be blank
```
(Sorry that I haven't posted a full stack trace screenshot. Printscreen button stops working sometimes since I upgraded to latest ubuntu. Fixes when I restart so I'll post then.)

## Steps to Reproduce

Reproducing consistently with Grimshaw Community Food Hub on UK production
1. Go to Order Cycles on UK prod
2. Find the Grimshaw Community Food Hub OC (there is only one)
3. Click the Duplicate Button
4. Stare at the cat

## Animated Gif/Screenshot

Coming soon...

## Context

The user is just keeping the same OC and updating the closing dates. So they do have a work around.

Though internationally reports of problems opening and cloning OCs have been common recently. 

## Severity

* Version used: tested on v1.20. Was also happening on v1.18.
* Browser name and version: multiple
* Operating System and version (desktop or mobile): Desktop multiple

**Comment by kirstenalarsen** [comment]
there were some changes to oc cloning recently - #2439 and #2463 - could it be related to those? @kristinalim ?

**Comment by NickWeir63** [comment]
![image](https://user-images.githubusercontent.com/10517702/45948243-12e6ba80-bfef-11e8-9d03-f70d72b4a237.png)

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error when cloning order cycles](https://trello.com/c/LwZdBkPc/223-error-when-cloning-order-cycles)

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [problem creating an order cycle](https://trello.com/c/ai3A5sSr/238-problem-creating-an-order-cycle)

**Comment by kristinalim** [comment]
Thanks for that very useful info from the Bugsnag notification, @lin-d-hop.

I am still working on #2764 which is bug-s2, but this is most likely related. I was able to successfully set up an invalid variant through the web UI alone, which should not be possible and has big potential to mess up other code.

@lin-d-hop Do any of the variants which were not automatically copied into the new OC happen to have a non-numeric unit value?

**Comment by kristinalim** [comment]
I was able to confirm that #2776 is related to this issue, or at least is one way to replicate this issue.

To replicate, as enterprise manager:

1. Create a new product with "Items" as unit size.
2. Go to the "Bulk Edit Products" page.
3. Add a new variant for the product. Set unit to a non-numeric value, e.g. "1 med".
4. Create an OC with the variant in a incoming exchange. (Probably same behaviour if outgoing exchange.)
5. Clone the OC. The variant is correctly copied into the new OC.
6. Change the name of this new OC, for less confusion later.
7. Back in the "Bulk Edit Products" page, change the product "Unit" to weight and save. At this point, as explained in #2776, the variant is already considered invalid by the application.
8. Try to clone the OC again. The OC does not have the new variant, and the error with similar Bugsnag details in issue description is triggered.

**Comment by lin-d-hop** [comment]
@sineadfenton this should now be fixed on uk prod with the patch this morning. Could you test if this can now be closed?

**Comment by sauloperez** [comment]
I wonder if we should really check (or persist) the variant when duplicating the OC. To me, the state of the variants should not affect OCs in any way.

**Comment by sineadfenton** [comment]
This has come up again unfortunately, it's with an enterprise Grimshaw Community Centre on UK production in particular - no other enterprises are giving us the issue.
http://recordit.co/jtiNwnRcDM
When we refresh the order cycle has infact been created.

Oddly for them though is that we can't seem to create an order cycle from scratch at all - I'll create a new issue for this. We haven't been able to spot anything different through our investigations, but maybe if we can figure out whats different about this enterprise it can help us

**Comment by myriamboure** [comment]
@sineadfenton is this error of OC duplication still happening ? I'm trying to review the s3 bugs and see which ones we should prioritize. If this happens again it's probably a high priority. If it does, and only for this hub, it would be good to know what specificities this hub has, like if they use subs or not, etc. And maybe we should open a new issue if it's different from the one in the main thread (it seems a patch we fixing it some time ago) to avoid confusion and clarify the new and persistent bug. Thanks !

**Comment by myriamboure** [comment]
@sineadfenton any news on this one ? It's on top of the list, so if the bug is still there we can add it to the dev ready column in 5th bug position to be taken, there is a free spot ;-) Else let's close it, we can always reopen if it reappears for some reason later. Thanks !

**Comment by sineadfenton** [comment]
Sorry team - we are all good on this (tested again) and I'll close this now.
