### ISSUE TITLE
Create a single re-usable instance of the loading spinner

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#2772]
## Description

Following comments in #2692, this is a small issue to refactor our multiple instances of the loading spinner throughout the codebase into one re-usable view and CSS block using BEM.

**Comment by daniellemoorhead** [comment]
Would this be a good first issue @Matt-Yorkley?

**Comment by Matt-Yorkley** [comment]
Yes, it should be fairly simple. I'll unassign myself for now if you have someone else in mind.
