### ISSUE TITLE
Impossible to load products after filtering

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2773]
## Description
As a super admin, on both UK and FR instances, it's suuuuuper slow to filter products to just display products of a certain producer for instance.
As a reminder, this has been changed as previously there was a message even worse saying "no products" while it was charging (and no indication it was charging) but the solution implemented is not working either.

## Expected Behavior
When the list is charging I have a message telling the list is charging, and the list charges in a reasonable amount of time (<1 min ?)

## Actual Behavior
After 2-3 minutes nothing is charged, and I have no message telling me the list is charging.

## Steps to Reproduce
1. Login as super admin in an instance with lots of data (France or UK for sure)
2. Go to products, and apply a filter on a producer. See

## Animated Gif/Screenshot
From UK production:
https://www.useloom.com/share/1b25b88dba0744cbbac2b45505f1a2d1
You will see in the video, I wait, but have no message, at all, and even after some minutes, still no products, and no message nothing.

From French production:
https://www.useloom.com/share/62c5b2d1324c4d6286b2a4f4efb69fb8

## Context
This has been reported by @RachL and myself doing support to user and having difficulties in doing that support because of that, and also doing testing. We don't know how hard users are affected yet, we had no feedback so we guess it is still acceptable, but as super-admins it's pretty hard to help users if we can't access the products list...

## Severity
S3 as we can use another email address and add ourselves as manager of the hub to give support. It's not a nice workaround, but that's what I have done lately to overcome the problem...

## Your Environment

* Version used: v1.18 on french instance and v1.20 on UK instance
* Browser name and version: both on Chrome and Firefox, same results
* Operating System and version (desktop or mobile): Ubuntu 1.18

## Possible Fix
We need to improve loading performance, or introduce pagination when filters are applied, or... whatever that can improve loading performance first, and then add the "loading" message.

**Comment by RachL** [comment]
@myriamboure wouldn't it be quicker to release a loader first and work on performance after? I mean, I don't care if loading products *after filtering* takes time, as long as I know the system is actually loading... which I don't at the moment.

By the way are you ok if I had the filtering part in the title here? Because I haven't had any issue without filtering.

**Comment by myriamboure** [comment]
As you want @RachL just do it :-) For me loading time needs to be worked on first as it seems it crashes before the server manages to load all products if we look at the console and network tool... but we will see when some dev work on it what makes sense to do first. I have no objection with reversing the tasks ;-)

**Comment by sauloperez** [comment]
Do we have Skylight set up for FR? I guess not but it'd give us the details we need here. We do for UK already

**Comment by Matt-Yorkley** [comment]
The way we load products on that page is super inefficient. For an admin user we end up loading every product in the database into the DOM, and the filtering doesn't fully work until its all finished... :grimacing:

**Comment by Matt-Yorkley** [comment]
So as UK and FR increase in size, the page becomes less and less usable.

**Comment by sauloperez** [comment]
We're talking about Bulk Edit Products page here, right?

**Comment by luisramos0** [comment]
I am closing this as the bulk product page is now paginated ❤️
