### ISSUE TITLE
Able to end up with an invalid variant through web UI

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#2776]
Through the web UI alone, it is possible to end up with an invalid variant. This has big potential to mess up related code.

## Description

We normally presume `variant.save` and `variant.update_attributes` would succeed if we do not make changes the record that would make it invalid. When we have an already invalid variant, even if we don't change it and then attempt to save it, it would fail.

I haven't done more investigation on the consequences. I'm still just documenting at this point.

## Expected Behavior

It should not be possible to end up with an invalid variant in the database.

## Actual Behavior

I can create an invalid variant in the web UI by performing a series of actions.

## Steps to Reproduce

As enterprise manager:

1. Create a new product with "Items" as unit size.
2. Go to the "Bulk Edit Products" page.
3. Add a new variant for the product. Set unit to a non-numeric value, e.g. ~"1 med"~ "med".
4. Save the changes
5. Change the product "Unit" to weight, and save.

The variant at this point fails validation.

## Context

Some possibly related issues:

* #2769 
* #2764
* #2774 
* #2739 

## Severity

S2

**Comment by sauloperez** [comment]
This is going to be harder... there's not a single unit test for the `ProductSet` class, the one responsible for this... :clap:
