### ISSUE TITLE
[Spree Upgrade] Fix pending specs in Order Syncer and Proxy Order (Subscriptions)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2788]
order_syncer_spec is broken with 9 broken specs.
These specs were made pending but need to be fixed at some point.

Move all specs in proxy_order_spec to pending (order syncer and proxy order are specific to subscriptions).

See #2789 and #2902 and #3071

**Comment by daniellemoorhead** [comment]
If this is blocked and can't be worked on (and thus not `In Dev`) should it be moved back into the Spree Upgrade backlog until it's unblocked? Ping @kristinalim 😄

**Comment by kristinalim** [comment]
Fixing just the parts of the blocker issue #2696 that fix this one. I moved #2696 to In Dev as well.

And reversed the other dependency relationship, so this one blocks #3410.

Sorry!
