### ISSUE TITLE
Producer does not appear in inventory

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#2799]
## Description
If I go to the inventory for Stroudco and try and filter for Producer:Wharf Farm, it no longer comes up. They also don't come up if I leave Producer unfiltered and search for their produce. This happens for me logged in as me and it happens when I log in as super admin but it seems to work fine for Nick.

## Expected Behavior
Inventory screen loads produce for Wharf Farm

## Actual Behavior
Screen displays " No matching products found in your inventory "

## Animated Gif/Screenshot
http://recordit.co/k6dAumaPgP

## Context
We use the inventory to reset how much a producer has available each week. 

## Your Environment
Firefox 62.0.2 on Mac 10.12.6

**Comment by OliverUK** [comment]
With the fix of #2769 this too seems to be working again now. @myriamboure should I close?

**Comment by myriamboure** [comment]
Thanks @OliverUK we will close when we have tested and merged the patch to master, leave it open for now, I have added that issue number to the patch to know we have to close it when tested.

**Comment by sigmundpetersen** [comment]
I guess we can close this now that #2769 is tested and merged @myriamboure ?
