### ISSUE TITLE
An API is available for 3rd party interactions

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#280]
Providing a full documented API is a long term goal, to support interactions from other websites and mobile apps. 
## Review

There are a number of questions I have about the current state of APIs and use of JSON:
- Is the intent to move everything to AMS instead of RABL?
- Could the use of the `representation` module that uses `.rep` files also get replaced by AMS?
- Why do read-only operations on the `/api` need a product key? Could the key only be needed for write operations?
- Would it be possible to define a full API accessible via an `/api` endpoint and use that instead of routes ending with `.json`? Seems quite mixed currently. What implications would this have?

**Comment by wvengen** [comment]
wrt AMS: is the performance really that bad to to use something else than Spree here? In https://github.com/spree/spree/issues/5971#issuecomment-86541811 some people ponder whether Spree should migrate.

**Comment by pmackay** [comment]
>to to use something else than Spree here?

Can you expand on what you mean by this?

**Comment by wvengen** [comment]
Spree is [using RABL](https://github.com/spree/spree/blob/master/api/app/views/spree/api/v1/products/index.v1.rabl). As a (new) developer I would expect some similarity in approaches between Spree and OFN.

**Comment by pmackay** [comment]
@RohanM might need to chip in. This is an old issue and I started some work on harmonising but didnt get far. Things might have changed anyway since then. I figured it was good to be consistent within the OFN codebase (which was a mix) irrespective of what Spree uses.

**Comment by wvengen** [comment]
:+1: for harmonising within OFN. I might start working on API stuff, so it would be useful for me to know which approach fits best for us.

**Comment by wvengen** [comment]
Related: #287

**Comment by wvengen** [comment]
I discovered the many other AMS files, and can see it makes sense to use that. Especially with Rails 5 preferring AMS as well. Currently I'm experimenting with rendering RABL from within AMS, so that we can use the same JSON format for addresses and images, for example, within our own objects (like an enterprise) - without having to copy that in AMS.

**Comment by lin-d-hop** [comment]
Moved to Discourse wishlist #gitcull2017
https://community.openfoodnetwork.org/t/road-map-for-ofns-api
