### ISSUE TITLE
[Spree Upgrade][Reports] Do not use count_on_hand in lettuce_share_report_spec.rb (1 broken spec)

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2805]
## Description

LettueShareReport `only available items` spec updates the variant's `count_on_hand` column in its setup. This column is now gone. See below:

https://github.com/openfoodfoundation/openfoodnetwork/blob/f0183cd17ec23fd52b637379f5859f0c2a574141/spec/lib/open_food_network/lettuce_share_report_spec.rb#L50-L54

## Possible Fix

Use the attribute accessor instead of directly updating the DB column in line 51. This will go through our `VariantStock` concern, as already happens with the various variants created in the setup phase.

**Comment by luisramos0** [comment]
This report spec was moved to xdescribe as it was broken here: #3019
This issue should remove this xdescribe.
