### ISSUE TITLE
[Multi language] Make OFN multi language work

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2808]
EPIC to represent issues related to the usage of multi language instances of OFN. Currently we only have katuma with more than one language activated in production.

**Comment by luisramos0** [comment]
currently just this blocking issue #2491 but Sara also reported an issue in the backoffice related to being unable to translate product categories, I'll have a look at some point.

**Comment by sauloperez** [comment]
I'd like to investigate if we pick the browser's configured locale the firs time. It seems that the `Accept-Language` HTTP serves this purpose. Source: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages

Does it sound good to add it in this epic?

**Comment by luisramos0** [comment]
Yes @sauloperez , I think that's a new issue on this epic. Although it is not a blocking bug, it's more like a feature.

**Comment by myriamboure** [comment]
@luisramos0 can I close that epic ? There is still one issue about some remaining untranslated emails, I kept the issue in the bug backlog. There are other things that have not been done for a local instance to be fully multi-lingual but it is a new feature to prioritize, the first level of feature was about making non data things translatable https://community.openfoodnetwork.org/t/multilingual-instances-enable-users-of-a-single-language-to-see-all-info-in-their-own-language/1447.

**Comment by luisramos0** [comment]
Yes, agree @myriamboure thanks for the heads up. I am closing this epic now.
For me, it's was really about getting the basics for katuma's adoption in Portugal. Job done ;-)

In terms of the remaining work, imo I think we shouldn't consider it a bug, multi-language is a feature and this epic was the first step. Making the other emails multi-language is the continuation of the feature.
