### ISSUE TITLE
Breaking OFN down in domains

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2809]
Continuing the work done in #2521 by moving code to engines/domains.
Discourse conversation started [here](https://community.openfoodnetwork.org/t/breaking-ofn-down-into-domains/1377) and ended up in some agreemnts on the wiki [here](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Tech-Doc:-How-OFN-is-organized-in-Domains-using-Rails-Engines).

**Comment by lin-d-hop** [comment]
Closing as this is no longer an agreed priority. Still might bea  good idea
