### ISSUE TITLE
Update the language_name: key for IT locale file

### ISSUE THREAD

**Issue by pacodelaluna** [openfoodfoundation/openfoodnetwork#2819]
The language_name key should provide the name of the language itself.
I can see that in IT locale file, it is set as 'Inglese' when I think it should be 'Italiano', https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/it.yml#L2.
Tell me if any issue.

**Comment by myriamboure** [comment]
I'm wondering if that issue shouldn't be in the OFN-install repo? We hit that issue when implementing multilingual switching French - Italiano on the French instance, apparently @pacodelaluna had to do some manual hack on production. @sauloperez @luisramos0 @Matt-Yorkley do you see what the issue can be that we need to fix?

**Comment by sigmundpetersen** [comment]
Couldn't this just be changed in Transifex?

**Comment by myriamboure** [comment]
Oh yes, thanks @luisramos0 I didn't tell the italian translator about paying attention to that specific translation... anyway, I changed it @pacodelaluna so if we push again the italian translation from transifex into OFN and redo the process "Italiano" should automatically be there now. But we need to wait for next release to check that as we need to integrate translations into master to verify it solved the issue. But it should do.

**Comment by pacodelaluna** [comment]
Of course it could be fixed into Transiflex, but after it needs to be merged into the master branch, that's why I created the ticket here.
Still not solved by the way.

**Comment by luisramos0** [comment]
oh, I see you meant to create the issue to correct the translation in transifex and then merge it. I am not sure we create issues for that kind of translation issue. I will reopen so we can track this specific one.

**Comment by luisramos0** [comment]
I dont think FR was updated on the last releasse. I think we need to update the transifex process. A manual update/PR of all languages in every release is probably the best/easiest process.

**Comment by sigmundpetersen** [comment]
Ping @mkllnk for feedback on the transifex process and the way forward on this specific issue

**Comment by mkllnk** [comment]
I agree. Manually pulling all translations when releasing fits our current process much better. The automatic Transifex integration hasn't been working well for us.

**Comment by pacodelaluna** [comment]
@mkllnk Ok, it is an option yes, and both options (merge one and direct pull one) can help to have better results. We could even add a recipe on ofn-install to proceed this automatically.

**Comment by sigmundpetersen** [comment]
Can we close this now @mkllnk as the manual Transifex process is written down?
Should we also create an issue in ofn-install repo what @pacodelaluna suggests, to pull latest translations with ansible on every deploy?

**Comment by mkllnk** [comment]
Yes, I think we can close it now.

And yes, a new issue would be good. I would make it a separate playbook to start with, because by pulling the translations the deploy is not deterministic any more. The result depends on Transifex instead of the code. And if we automate it, we should only do it when we deploy master. Otherwise we will have a mismatch between the code and the translations.
