### ISSUE TITLE
Update CI's badge

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2822]
## Description
We didn't update the README's CI badge when switched to Semaphore CI and so it still points to the last CI run we did in Travis. That is 3 months ago.

## Expected Behavior
The README's CI badge needs to point to the latest CI execution on `master` so that we can know the status of our test suite.

**Comment by sauloperez** [comment]
[![Build Status](https://semaphoreci.com/api/v1/openfoodfoundation/openfoodnetwork-2/branches/master/badge.svg)](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2)

Is the appropriate snippet according to https://semaphoreci.com/docs/how-to-get-build-badge.html.

**Comment by 73VW** [comment]
I'll do it!
