### ISSUE TITLE
Product upload attempt leads to snail . .

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2827]
## Description
Trying to use product uploader on german instance openfoodnetwork.de

Selected csv file and hit upload
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/be564626-514c-472b-8f01-219be97697f7)

## Expected Behavior
Should progress through Product Upload and tell me if there is something wrong with my file and if so what it is

## Actual Behavior
Snail appears, console output also shown below
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/009bed03-a367-4f01-bd07-241db636c785)

## Steps to Reproduce
Have attached the file I am trying to upload . .
Try and upload it in openfoodnetwork.de

## Severity
S1-2
It is arguably a 'non-critical' feature, but for lead user we are working with in Germany it is a critical feature . . so I'm saying S1

## Your Environment
Mac Chrome Desktop

## Possible Fix
I think this instance is running an older version, but this version was working when I tested it on Aus. Maybe worth upgrading to latest release before investigating more closely. Issue for that is [here](https://github.com/openfoodfoundation/ofn-install/issues/249)

It is possible (?) that this is related to the issue creating order cycles also currently on this instance? https://github.com/openfoodfoundation/ofn-install/issues/254 - likely similar to https://github.com/openfoodfoundation/openfoodnetwork/issues/2676

**Comment by myriamboure** [comment]
You are hacking the bug labels @kirstenalarsen this can be s2 as blocking use of major feature with no workaround but not preventing to use the app ;-)

**Comment by kirstenalarsen** [comment]
File needs to be saved to UTF-8.csv FROM a file with german language setting in order to handle the accents. See new issue https://github.com/openfoodfoundation/openfoodnetwork/issues/2836. Closing this.
