### ISSUE TITLE
Embedded UX requests

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2828]

**Comment by daniellemoorhead** [comment]
Hey @kirstenalarsen is this _really_ related to Mobile Quick Wins which relates to shopping on a mobile? Or is it an extension of the embedded shops work that's sneaking in? Can you add a description on here so we understand how it relates?

**Comment by sigmundpetersen** [comment]
Underlying issues closed and no further description so closing this.
