### ISSUE TITLE
Data or formatting issues in German email order confirmations

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2834]
## Description
Order confirmation email has some strange fields - looks like it's not collecting some data or something? Could be translation related?

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/da917a8e-33e5-42f4-9bcd-0c2879a8ece4)

## Expected Behavior
It should include the customer name rather than "%[name]"

and shouldn't end with "strong>!"

## Steps to Reproduce
1. go to openfoodnetwork.de
2. place an order 
3. look at email confirmation

## Severity
s4 - doesn't affect use but will affect every user and is a bad look for launching instance

**Comment by kirstenalarsen** [comment]
could this be connected to multilingual?

**Comment by myriamboure** [comment]
it might be a translation issue in German, I don't have access to German in transifex but it % needs to clicked on, not typed, check in Transifex if translation is good @kirstenalarsen

**Comment by mkllnk** [comment]
The name thing got fixed 24 hours ago (curly brackets instead of `[`). It's in the master branch now, waiting for deployment to the German server.

**Comment by kirstenalarsen** [comment]
thanks @mkllnk - should I have known that somehow? just still finding my way into all the continuously improving processes?

**Comment by mkllnk** [comment]
I updated the German instance to latest master and it solved this problem.
![screenshot from 2018-12-07 14-54-08](https://user-images.githubusercontent.com/3524483/49626901-0c81af80-fa30-11e8-9b98-7953d6d080e3.png)
