### ISSUE TITLE
Content Guidance to make mobile sing!!

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2835]
In designing new mobile interface @yukoosawa observed many painful things, often caused by the amount of flexibility we give our users in naming things (see below)

We thought that perhaps publishing a "Top Tips to make your Shop awesome on Mobile" guide when we release the new design could help people with this . . and then gradually we could guide with tooltips and eventually length restrictions on fields .. 

This card is to remind us to think about this when releasing.

We currently give shops/hubs almost infinite flexibility regarding content length (names, variants, weights etc) and when OFN was a desktop first application this was not an issue. However now that we’re optimising for mobile also, this introduces a lot of issues when it comes to the design, and the content variability is compromising the mobile experience. Applying some restrictions (aka best practice guidelines) to ensure content consistency will be of benefit for ongoing Mobile UX design efforts.

The current implementation of variants is atypical of a shop/ecomm site, and particularly for food sites. The use of variants to list product flavours (ie. museli, jams & preserves, body products) where lists can exceed 10 items introduces a number of ux issues in mobile:
* Product + variant list can’t be viewed in a single mobile view (however collapsing isn’t an option as this hides so many product variants from the user).
* Keyword search for a product can’t take the use to the specific matched variant.

**Comment by daniellemoorhead** [comment]
Have added a link to this card in the overarching shopping improvements epic. Closing it for now as there is nothing specific to build, but a review will be done at the end of the work to determine an approach, and anything non-dev related will go into ATAP.
