### ISSUE TITLE
Change contact details in welcome email

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2839]
@kirstenalarsen commented on [Fri Oct 05 2018](https://github.com/openfoodfoundation/ofn-install/issues/252)

![image](https://user-images.githubusercontent.com/2911176/46508189-a46feb00-c87f-11e8-89cb-709ba1534b21.png)

Kirsten to confirm new details
Remove linkedin
Check Odi and others: will there be Facebook / Twitter?
Contact email . .

**Comment by YanhanLyu** [comment]
Hi, I'm happy to take this issue!

**Comment by sigmundpetersen** [comment]
Yeah I wonder if @kirstenalarsen should confirm on this one, as it is part of an instance specific epic.

**Comment by myriamboure** [comment]
In France it's the French contact email at the end of emails, why comes that in Germany it's not the local German main contact email? Isn't it a super admin configuration ? In "content" at the bottom of the page there is "email" field...
About removing linkedin, we don't use it in France but we need to check with others, no @kirstenalarsen before removing it?

**Comment by mkllnk** [comment]
@kirstenalarsen This is done as super-admin at https://openfoodnetwork.de/admin/content/edit. I removed most of the links. I didn't change the email though, because I don't know what it should be. Is there hello@openfoodnetwork.de?

**Comment by luisramos0** [comment]
Is this tech debt? needs the label if it is.
or we can move it to "all the things" column

**Comment by sigmundpetersen** [comment]
This is more a configuration task in back office. I would move it

**Comment by daniellemoorhead** [comment]
@kirstenalarsen can you review what @mkllnk says above in terms of how to configure this - it doesn't require any dev work by the sounds of it so this issue can be closed.

**Comment by daniellemoorhead** [comment]
Have moved out of tech debt to all the things as it's doesn't fit into any of the pipe columns.

**Comment by lin-d-hop** [comment]
This is config. Not a github issue. #gitcull
