### ISSUE TITLE
When user changes their mail from "my account", no confirmation is sent + disturbing UX

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2840]
## Description

As a user I try to change my email address...
1- the UX is bad, when I click on "proceed" I am redirected violently to login modal
2- When I login again I see a message saying the new email will apply when it is validated, but I never receive any validation email on the new mailbox... **UPDATE: I receive the email but not on the new email, on the old one!!! So I can't validate the new email obviously.**

## Expected Behavior
1- when i click on "proceed" I get a success message saying a validation email was sent to the new address, and that I'll be able to connect with this new address once validated.
2- I should receive a validation message on that new address.

## Steps to Reproduce
1. With any user, go to "my account" and "account info" (last tab)
2. Change the email, type your password, and validate.
3. Check the new malbox: nothing
4. Check the old mailbox: you see validation email

## Animated Gif/Screenshot

https://www.useloom.com/share/fdda1736be3e47cfbdecdf24c6edc3fc

## Context

I was trying to do support to a user who wanted to change their email.

## Severity
bug-s3: a feature is broken but there is a workaround = keep using the old email...

## Your Environment

* Version used: v1.18
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu 18

**Comment by myriamboure** [comment]
WARNING: this is REALLY ANNOYING I think it can break some logic we have implemented:
As user with validated email user@gmail.com, in "my account" I change the email to new-user@gmail.com.
The confirmation email is sent to "user@gmail.com", and if I click on validation link, I can then connect with "new-user@gmail.com" as a validated user BUT the new email is NOT validated.
I continue the experiment and change again the mail to "new-new-user@gmail.com", NOW I received a confirmation link on "new-user@gmail.com".
THE LOGIC IS BROKEN AND PRETTY DANGEROUS AS IT MEANS WE CAN HAVE UNVALIDATED USERS TREATED AS VALIDATED USERS. I don't know what it can break but sounds bad...
https://www.useloom.com/share/e6823992c58947b4b3f941f5911161ad

**Comment by myriamboure** [comment]
Ok I'm sorry but this seems REALLY bad to me, shall I put s2? @Matt-Yorkley tell me what you think, you know pretty well what can be the implication I think.

**Comment by Matt-Yorkley** [comment]
I'll take a look at this today, I think it will be a quick one.

**Comment by Matt-Yorkley** [comment]
@myriamboure On the account details page you can add a new email address or change your password. If it's just an email change you don't need the password change as well. Maybe it's not very clear. The user gets logged out only if the change password fields have been used.

I'll take a look at making sure the email goes to the correct address.

**Comment by Matt-Yorkley** [comment]
I'll make a separate issue for the forced logout when updating user password.

**Comment by RachL** [comment]
@myriamboure is this really a bug or a feature that has been forgotten during email validation project?

**Comment by Matt-Yorkley** [comment]
I think there was some Spree code that was overriding some of Devise's user confirmation code, and it was only handling confirmations of new users but not confirmations for email changes on existing users. Anyway, it should be fixed by the PR above :+1:
