### ISSUE TITLE
Filtering on the Orders page does not filter and subsequent pages are not updated when scrolled through - UK Productions

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#2843]
## Description

Users are trying to filter through orders and are unable to do so adequately. 

- You enter a filter criteria and it does not filter correctly - i.e. I enter an email address and several others all come come up instead of the one I have searched for

- When I click next page, I'm presented with different data in terms of order status, but the same email addresses as the first page

## Expected Behavior

Users should be able to filter through the pages and use the filter functionality to filter the information they want

## Steps to Reproduce

1. Go to orders
2. Search for sara@tamarvalleyfoodhubs.org.uk
3. Add the distributor as Tamar Valley Food Hub
4. See that the data is not only Sara's email but a range of users 
5. Go to the next page - you'll see that only the data in the email column is the same whereas the status does change

## Animated Gif/Screenshot

This is page 1 when I filter using only Sara's email
![image](https://user-images.githubusercontent.com/28807449/46612684-3179a500-cb09-11e8-85ac-b0e7f42486dc.png)

This is page 2
![image](https://user-images.githubusercontent.com/28807449/46612746-59690880-cb09-11e8-8aaf-98f0ed8c5304.png)

## Context

Users cannot reconcille their orders to their customers - this has been reported by 3 users in the UK

## Your Environment

* Version used:
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10

## Possible Fix

The filtering works as intended and the pages change when you go through them

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Customer Order Issues](https://trello.com/c/N4J6bhpd/257-customer-order-issues)

**Comment by lin-d-hop** [comment]
Note that UK deployed a patch on the weekend to fix BEP issues. 
@Matt-Yorkley with this S1 if there is no quick fix then please revert!

**Comment by Matt-Yorkley** [comment]
I've reverted UK prod now, so the issue is temporarily fixed. This only affects UK at the moment.
