### ISSUE TITLE
Remove parallel_tests gem

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2852]
## Description

`parallel_tests` gem was introduced by Rohan in 2015 before we used knapsack to parallelise spec runs. So we can remove it completely. See db47c01784df955cff00560f3c4b5454467025dd 2b3689fd933f99349f5284c61fc51ff1e875fb34 for details.

Stems from https://github.com/openfoodfoundation/openfoodnetwork/pull/2832

**Comment by CoryWritesCode** [comment]
Has anyone picked this up yet for hacktoberfest?

**Comment by sigmundpetersen** [comment]
Yes @CoryWritesCode this is now in Code Review with #2853 

The best way to find another issue is to install the Zenhub extension and pick one in the 'Dev Ready' column here https://github.com/openfoodfoundation/openfoodnetwork/labels/Hacktoberfest#boards?labels=hacktoberfest&activeFilters=labels&repos=6257856

**Comment by sigmundpetersen** [comment]
BTW thanks a lot for your interest and welcome to Open Food Network. If you have any questions you can ask in our `dev` channel on [Slack](https://openfoodnetwork.org/slack-invite)
