### ISSUE TITLE
Strange category duplication in product filter

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2854]
## Description
When trying to filter a product by category, one category is duplicated 11 times.

## Expected Behavior
Each category is proposed just once.

## Steps to Reproduce
1. As a hub manager go to products: https://openfoodnetwork.ca/admin/products
2. Try to filter with category.

## Animated Gif/Screenshot
On French staging while testing 2831
![capture du 2018-10-09 11-17-09](https://user-images.githubusercontent.com/8135376/46659561-73f8bb80-cbb5-11e8-8484-69caba52ee4f.png)

On canadian production instance with v1.20
![capture du 2018-10-09 11-17-23](https://user-images.githubusercontent.com/8135376/46659595-8541c800-cbb5-11e8-8a6b-f83d3d10a8b0.png)

## Context
Discovered while testing 2831 

## Severity
S4 as apprently it is not preventing filtering...

**Comment by nikobozi** [comment]
The collection is apparently delivered that way from the backend `app/controllers/spree/admin/products_controller_decorator.rb`, they have the same name but different ids:
![screenshot_products](https://user-images.githubusercontent.com/23106612/46685079-dd4bef00-cbf4-11e8-94e3-550fc14b38ac.png)

**Comment by myriamboure** [comment]
Hum... this is strange as categories are defined at instance level so there should be only one id for a category. How can that be possible? @Matt-Yorkley @kristinalim @mkllnk or others, any idea?

**Comment by RachL** [comment]
This is fixed now :)
