### ISSUE TITLE
Some translations are back to English on French instance... transifex process bugging

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2857]
## Description
Some translations, solved months ago, are back to English after the upgrade to v1.21 on French instance.
We had experienced that before on other random translations (remember @mkllnk the image of "choose a package" shared on Slack in the fr-new-prod channel https://openfoodnetwork.slack.com/files/U04HYLZHB/FCLRYD8MU/image.png)
Users have reported that, they are disturbed and worried it affects front end at some point.

It is hard to understand, it seems randomly after an upgrade, some things are back to English, and some things that were back to English precedently are back to French (like the image above on registration process, now is back to French)

## Expected Behavior
Translated strings remain translated in app.

## Actual Behavior
They randomly disappear after some upgrade.

## Steps to Reproduce
1. Today noticed on "order" page https://www.openfoodfrance.org/admin/orders?q%5Bs%5D=completed_at+desc: "new order" and "listing orders", "capture" are back to Ensligh ...
![image](https://user-images.githubusercontent.com/8135376/46759290-5586e300-cccf-11e8-92f1-3f732f57d55d.png)
2. Might be some other places but we have not yet noticed them.

## Context
Reported by a user.

## Severity
S3, but if at some point starts to touch front end will become s2, so it would be great to understand and avoid that to happen again.

**Comment by Matt-Yorkley** [comment]
The namespacing of keys have been changed when the view was remade, so they are better organised, e.g. from `listing_orders` to `spree.admin.orders.index.listing_orders`.

**Comment by myriamboure** [comment]
Ok, but French was already translated 100% and no new string has appeared, so why don't they appear then? I thought if we are translated 100% translation are pulled. But does it happen if you modify a string? Or just if there are new strings translated and reach 100%?

**Comment by myriamboure** [comment]
@mkllnk if the transifex process has been updated, shall we just check at next release if fixed and then close that issue?

**Comment by myriamboure** [comment]
I leave that in test ready so we don't forge to test.

**Comment by sauloperez** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v1.22.0 is now live so we should be able check this @myriamboure once it is deployed to FR.

**Comment by RachL** [comment]
with 1.22 all translation are back to normal :) So I'm closing this one!
