### ISSUE TITLE
NoMethodError in spree/admin/orders#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2860]
There can be an error when updating shipping methods when updating an order as admin. This happened twice on Australian production.

## Error in OpenFoodNetwork

**NoMethodError** in **spree/admin/orders#update**
undefined method `finalized?' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5bbecb7e53a566001b5e61ec?event_id=5bbecd970030515178600000&i=gh&m=ci)

## Stacktrace

    app/models/spree/order_decorator.rb:410 - update_adjustment!
    app/models/spree/order_decorator.rb:168 - block in update_shipping_fees!
    app/models/spree/order_decorator.rb:166 - update_shipping_fees!

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5bbecb7e53a566001b5e61ec?event_id=5bbecd970030515178600000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by Matt-Yorkley** [comment]
I think there may be issues around orders created manually by an admin not always being in the right state or having the correct related objects in place. Maybe we need more specs for those manual creation cases.

**Comment by RachL** [comment]
@mkllnk is this one related to this old one: https://github.com/openfoodfoundation/openfoodnetwork/issues/762
If yes, shalle we close #762 ?

**Comment by mkllnk** [comment]
No, they are two different issues.
