### ISSUE TITLE
Register link on checkout page leads to broken page

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2873]
## Description

The registration call at the bottom of the page sometimes leads to the wrong URL. It should go to `/registration`, but from the checkout page it goes to `/signup` which is Spree's path for registrations. Since we are not using Spree's signup, the page is broken and shows the snail.

## Expected Behavior

On every page the "Register here" call leads to `/register`.

## Actual Behavior

On some pages (checkout) the register call leads to `/signup`.

## Steps to Reproduce

1. Visit a shop.
2. Add a product to the cart.
3. Go to the checkout and scroll down.
4. Click on "Register here".

## Animated Gif/Screenshot

![screenshot from 2018-10-16 18-09-12](https://user-images.githubusercontent.com/3524483/46998572-a767b700-d16e-11e8-8135-015dfc660b93.png)

## Context

Bugsnag reported the broken page. See below.

## Severity

S3 as every instance is affected (I believe) and it can prevent customers from ordering. The workaround is to go to another page and then click on the link. Another workaround is to click on login and then select the register tab.

## Your Environment

* Version used: f8bccda6abe1c859e2506a3265178d818d1a1d5d

## Possible Fix

I'm not sure why the link doesn't render deterministically. But I noticed that there are Spree routes with the same names.
```
# rake routes
                registration GET  /register(.:format)              registration#index
           registration_auth GET  /register/auth(.:format)         registration#authenticate
                      signup GET  /signup(.:format)                spree/user_registrations#new
                registration POST /signup(.:format)                spree/user_registrations#create
       checkout_registration GET  /checkout/registration(.:format) spree/checkout#registration
update_checkout_registration PUT  /checkout/registration(.:format) spree/checkout#update_registration
```

Maybe there is a way to deactivate the unused Spree routes? Otherwise we can use our own helper to refer to the right path.

## Bugsnag error: ActionView::Template::Error in spree/user_registrations#new

**ActionView::Template::Error** in **spree/user_registrations#new**
store/all.css isn't precompiled

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5bc556570aae8f001943d029?event_id=5bc585ce0030994927d00000&i=gh&m=ci)

## Stacktrace

    gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:142 - digest_for

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5bc556570aae8f001943d029?event_id=5bc585ce0030994927d00000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by Jefferson-Faseler** [comment]
I would love to tackle this bug.
Plan A - Remove the route from Spree
Plan B - The quickest/safest fix I can think of would be to send this route to the correct action on the line below where Spree routes are mounted. Without looking at the relative code it seems this anchor tag href is dynamically generated (I'm guessing based off the behavior of the bug). So my thought would be that if there is any other place it is unexpectedly piped into the views, it would at least not explode again trying to go to `/signup`.

Are there any objections to the approach in plan-B? And is this the place to ask/discuss feature questions or is there a better place?

**Comment by mkllnk** [comment]
That quick fix would definitely help. What would be your way of pointing the route into the right direction?

One option would be to edit `config/initializers/rack_rewrite.rb` to redirect the browser.

**Comment by Jefferson-Faseler** [comment]
That could definitely do it. I was thinking adding the following to line 128 the last line of the `routes.draw` block. Rails will define it top down and issue resolved. Only downside would be a slight organizational issue since it would put that line far away from it's alias route.

```
  get "/signup", to: "registration#index", as: :signup
```

**Comment by Jefferson-Faseler** [comment]
Hmmm. Spree seems to be pretty greedy about it's routes. My above suggestion does not actually work as easily as I thought. Possible Rails 3 difference from Rails 4 (what I'm used to)?

```
$ rake routes | grep regist

registration GET    /register(.:format)            registration#index
...
removed by me
...
signup GET    /signup(.:format)                      registration#index
...
...
signup GET      /signup(.:format)                    spree/user_registrations#new
```

The route remains. I don't how Rails would handle this, maybe in our favor, but it seems kind of race-conditiony.

**Comment by mkllnk** [comment]
Thank you for working that out. It may be a bug in our Rails version or the way Spree is loading routes. What's your best suggestion now?

**Comment by Jefferson-Faseler** [comment]
I need to look at Spree more closely (from a quick glance there aren't really any options it expects to be passed in), and the Rails 3 routing logic (I read something about the path helper pointing to the inverse of the path Rack chooses when there are duplicate routes. Which makes me suspect this a Rails oversight, but that is only speculation from me).

If this needs to be an urgent fix maybe there is a way to use a before action to redirect for this case, which would be pretty ugly from some implementation perspectives.

We could also spell out each Spree route rather than mount what the engine generates. That may solve some other unknown routing issues like this.

I can spend some time on it tomorrow, NYC Eastern timezone, not sure if the urgency of this is high enough someone fixes it in the meantime. It's a little annoying it isn't an easy routing fix.

It's just hard to tell which `/signup` paths are related to this. It's sprinkled everywhere in the codebase and there are two valid`/signup` paths nested in other routes.

**Comment by mkllnk** [comment]
It's not that urgent. Would rack-rewrite be a solution?

**Comment by Jefferson-Faseler** [comment]
Yeah, that is probably the best solution. Sorry, I had forgotten you proposed that!

**Comment by mkllnk** [comment]
Thank you for looking into all the other options though. That was exactly what I was hoping for, proper research for a better option before implementing the the second best. :+1: :medal_sports:

**Comment by Jefferson-Faseler** [comment]
Started prepping to write feature specs against this and found #3174 

Is this the same issue? If so, I will find something else to do?

**Comment by RachL** [comment]
Hi @Jefferson-Faseler good call. I wasn't able to reproduce the error. But I will let @mkllnk answer as he opened this issue. PR #3174 started to fix a similar problem noticed from the user account and not from checkout. But it seems to me that the solution has fixed it at both places. But let's see if Maikel confirms this.

**Comment by Jefferson-Faseler** [comment]
@RachL Thanks for getting back to me. Would have been a headscratcher if I had synced locally with upstream and then tried to de-bug! Do you think we should still add feature specs then? Or even implement @mkllnk 's idea so it doesn't pop up again/keep happening in a fringe place of the app we haven't noticed yet? I'm new to the codebase and your processes still.

**Comment by mkllnk** [comment]
Excellent @Jefferson-Faseler, this is the same issue. Sorry for not realising that earlier. PR #3174 is one solution to the problem, but not ideal. It's probably better than my idea to use rack-rewrite.

I still think that a feature spec would be helpful. Otherwise this may break again. It also enables us to test for a better solution. For example, when we upgrade to Rails 4, we can revert #3174 and see if your spec still passes.

It's probably best to assume that this issue is a bug in Rails 3. Thanks a lot for your research.

**Comment by daniellemoorhead** [comment]
Hey @Jefferson-Faseler, so over to you now to right the feature specs for this. We are most excited at the fact that this will be coming 🎉 

Cheers!

**Comment by daniellemoorhead** [comment]
Also, the team think you're great, and would love to see you contributing more to the repo 🤗

**Comment by daniellemoorhead** [comment]
Hiya @Jefferson-Faseler, given the lack of reply we're gonna assume you're busy and pop this issue back into the `Dev Ready` column to be picked up at a later date.

Would be great to see you back in the repo sometime soon, if your time frees up and you'd like to contribute again 😃
