### ISSUE TITLE
[Subscriptions] Missing translation on "subscription" pages

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2874]
## Description

In this issue I collect all the untranslated strings on the subscription section. I thought all those translations could be handled in just one PR to avoid multiple staging. If you prefer to break it per page I can do it.

## Steps to Reproduce

UPDATED BY @RachL on June the 4th 2019

1. On https://staging.openfoodfrance.org/admin/subscriptions page:

- [x] The search placeholder:
![image](https://user-images.githubusercontent.com/6525576/58883611-0fa7e080-86df-11e9-9f66-d376e101e280.png)

On tab "items"
- [x] button: save, saving and saved
![capture du 2018-10-16 21-23-07](https://user-images.githubusercontent.com/8135376/47041667-b3ad3d80-d189-11e8-9f2b-77f5670d47a1.png)

- [x] status bar at the bottom: saving... and saved
 
![Screenshot 2019-06-04 at 20 31 12](https://user-images.githubusercontent.com/1640378/58908229-e9e30180-8707-11e9-911a-6289e0d323cf.png)

- [x] Tooltips are not translate (none of the three, "edit", "pause" and "cancel", "unpause" (when paused). I just captured one here:
![capture du 2018-10-16 21-27-35](https://user-images.githubusercontent.com/8135376/47041946-54036200-d18a-11e8-8ee4-274c24fab0cb.png)

2. On editing a subscription: https://staging.openfoodfrance.org/admin/subscriptions/2/edit

- [x] review
![image](https://user-images.githubusercontent.com/6525576/58883826-7deca300-86df-11e9-9009-d92819db137c.png)

On editing address field: 
- [x] suburb

![image](https://user-images.githubusercontent.com/6525576/58883901-a1afe900-86df-11e9-9dba-45e053457d42.png)

3. On new subscription setup
- [x] Page 1:
![capture du 2018-10-16 21-34-16](https://user-images.githubusercontent.com/8135376/47042317-400c3000-d18b-11e8-92f8-4e58f542e88b.png)
- [x] Page 4:
![capture du 2018-10-16 21-36-04](https://user-images.githubusercontent.com/8135376/47042415-82ce0800-d18b-11e8-9598-657d64f4ce35.png)

## Context

Reviewing the remaining things to be done to consider standing order v1 as done.

## Severity
S3, but not so relevant here as included in standing order project anyway

**Comment by kristinalim** [comment]
Estimated time: 2 hours

**Comment by luisramos0** [comment]
this issue was created in v1, in v2 the work required may be different, probably less missing translations.

**Comment by RachL** [comment]
@luisramos0 good point. I will do a check on this

**Comment by RachL** [comment]
This issue is now updated.

**Comment by luisramos0** [comment]
I have added one item to the list: save/saving in the bottom bar on the tab "items"
there are 8 points in the list now.

**Comment by RachL** [comment]
@luisramos0 nice! good catch!

**Comment by RachL** [comment]
Ready to roll!

![image](https://user-images.githubusercontent.com/6525576/59454376-2ef6ea00-8e12-11e9-8fd2-b22c22e8a424.png)

![image](https://user-images.githubusercontent.com/6525576/59454409-433ae700-8e12-11e9-8eb4-2d4571e72f9b.png)

![image](https://user-images.githubusercontent.com/6525576/59454451-69608700-8e12-11e9-814f-ee05bf0fa708.png)

![image](https://user-images.githubusercontent.com/6525576/59454479-78473980-8e12-11e9-9578-c0b362145869.png)

![image](https://user-images.githubusercontent.com/6525576/59454508-89904600-8e12-11e9-8a42-f432f5a8c7f7.png)
