### ISSUE TITLE
[Subscriptions] Currency internationalization issue on subs

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2875]
## Description

Currency symbol is $ on subscription pages, whatever the local currency setup.

## Expected Behavior

Currency adapt to local currency setup.

## Steps to Reproduce

1. On all screens of the subscription concerned (setup process when adding products and reviewing, "items" and "orders" tabs) you can see $ even on the French instance setup to €
![capture du 2018-10-16 21-41-36](https://user-images.githubusercontent.com/8135376/47042858-92018580-d18c-11e8-9fea-bfcd4448a109.png)

## Context

Reviewing the remaining things to be done to consider standing order v1 as done.

## Severity
S3, but not so relevant here as included in standing order project anyway

**Comment by kristinalim** [comment]
Estimated time: 0.5 hours
