### ISSUE TITLE
[Spree Upgrade] Fix Orders list page - remove show_only_unfulfilled_orders

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2898]
Filter to show_only_unfulfilled_orders was dropped in Spree2 [here](https://github.com/spree/spree/commit/2d8cd38e704b765345e75a5ea61aaf79a399af92#diff-a49b505b614b2659d9eae6c90d79f698R67). We should do the same in OFN.

This is currently breaking 12 tests in the 2-0 build with the following error:
```
ActionView::Template::Error:
        undefined method `inventory_units_shipment_id_null' for #<Ransack::Search:0x00560611c0d420>
      # ./app/views/spree/admin/orders/_filters.html.haml:35:in `block in _763a1cda9a9c777b576637ebc1247599'

```

Acceptance criteria:
No broken tests with this error.

**Comment by HugsDaniel** [comment]
I stumbled upon this while fixing the edit page, should we just remove it from the filters ? No replacement for now ?

**Comment by HugsDaniel** [comment]
This https://github.com/spree/spree/blob/3c46d141c5cb2bedced63596178a0a79df3f0c9e/backend/app/controllers/spree/admin/orders_controller.rb#L22 stays in 2.0 stable and after, it's in our code base as well:
 https://github.com/openfoodfoundation/openfoodnetwork/blob/32632addfb064c27c9cf15274348c3187c3e6431/app/controllers/spree/admin/orders_controller_decorator.rb#L39
But it seems useless without the field in the view right ? Should we remove it ?
