### ISSUE TITLE
It's difficult to directly link to a food hub, producer, etc

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfoundation/openfoodnetwork#290]
Because of the way the URLs are structured, its very hard to link to a producer, hub, etc if you want to share that with other people.

This makes it a lot harder to share; or to show other people.

![image](https://cloud.githubusercontent.com/assets/365751/5009757/bbb080c6-6aba-11e4-94d4-9732a13ee055.png)

**Comment by kirstenalarsen** [comment]
NB. working on this now and should be through next week.

**Comment by kirstenalarsen** [comment]
done. see documentation at http://community.openfoodnetwork.org/t/direct-link-to-my-shopfront-permalink/43
