### ISSUE TITLE
Can't login anymore on mobile (hamburger menu too long and closing when scroll)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2907]
## Description
I try to login on mobile, open the hamburger menu on the left, but the list is long now that we have more menus on the French production, so I try to scroll with my finger to reach the "se connecter" (=login) menu, but when I scroll the menu closes ! 

## Expected Behavior
I manage to access the login menu on mobile

## Actual Behavior
I don't

## Steps to Reproduce
1. With a mobile (I did with Iphone SE) go to www.openfoodfrance.org and click on the hamburger menu on the top left corner.
2. Try to scroll to reach "se connecter" which is the last menu entry not visible if you don't scroll
3. See the result

## Context
I was doing some testing.

## Severity
S2, I have no way if I want to do a quick intervention on my hub to login on mobile.

## Your Environment
* Version used: V1.21 on French production, iPhone SE
* Browser name and version: Safari
* Operating System and version (desktop or mobile): Iphone OS

## Possible Fix
- Enable scrolling on hamburger menu?

**Comment by kristinalim** [comment]
I am able to reproduce this behaviour in an actual mobile browser, and not in mobile browser emulation through Developer Tools in Chrome.

Collapse or reset of the hamburger menu seems to be triggered by the window resize browser event. Scrolling down the browser window in mobile browsers auto-hides the address bar, which resizes the browser area and then triggers a window resize event.

I am still looking into where exactly this happens though.

**Comment by RachL** [comment]
@myriamboure @kristinalim I am NOT able to reproduce the bug on Firefox and Chrome on Android. So I guess this is link to iOS devices? Which I'm not able to test during my tests... So I really need to ping you Myriam each time I'm testing on Mobile, that's the lesson I take...

**Comment by kristinalim** [comment]
@RachL I am able to reproduce this in Chrome on Android, actually, so this is not just for iOS:

* Browser: Chrome on Android (version 69.0.3497.100)
* Orientation: Landscape

Noting that this version allows the address bar to slide up and disappear when scrolling down the page, which I think is related. That could be a difference between our Chrome versions.
