### ISSUE TITLE
Improve order cancellation email

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2910]
## Description
If when I cancel an order as a customer, or if a hub manager do it from backoffice, as a customer I receive an email but there are some important info missing:
-  if the order is cancelled, we should add a sentence "if you didn't want to cancel that order, please contact [hub contact email]"
- there is no indication if the order was paid if I will be refunded, or other.

## Expected Behavior
The email I receive is clear, I understand what I have cancelled (content of the order) and I know what action to do if I made a mistake. I know what happens with my payments.

**Template proposal:**
![order cancellation](https://user-images.githubusercontent.com/8135376/51735378-955bb580-2087-11e9-8d62-b5086909eb35.jpg)

With the last sentence we can have 2 options (depending if order has been paid or not):
- "Your order was unpaid so no refund has been made"
- "Your order was paid so Superhub has refunded the full amount"
- And later when we have credits: "Your order was paid so your account has been credited"

## Actual Behavior
![Capture du 2019-05-21 11-50-58](https://user-images.githubusercontent.com/8135376/58086346-be67ff00-7bbe-11e9-92e9-778a230b6d3d.png)

Some info are missing (see above)

## Steps to Reproduce
1. In an OC with a hub that allows to modify order until order closes, make an order.
2. Then go to modify the order and click on "cancel order"
3. Check your mailbox.

## Your Environment

* Version used: V2.1 on Katuma staging
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Ubuntu 18

**Comment by kirstenalarsen** [comment]
I think you're hacking the bug system @myriamboure . . is this a bug or a desired enhancement?

**Comment by RachL** [comment]
@myriamboure shouldn't it be 3 separate issues? Plus I'm not sure they are qualified as bugs...

**Comment by myriamboure** [comment]
I am not sure either but what is clearly a bug to me is the display of enterprise fees details to customers. The rest is not a bug but probably it should be treated at once if someone review this order candellation email, so I was not sure @RachL We could separate in three issues but we should ask a dev first if it's easier to do it all at once or not.

**Comment by sigmundpetersen** [comment]
Just convert this issue to a sub-epic, create 3 new issues and put bug label on the one with the fees?

**Comment by myriamboure** [comment]
Yes, could be solution, let me see with the dev who will work on it what is better, if we need a more refine story map on it or not. It is part of the remaining subs things to do for release so it's not so important to know if it's a bug or not, it will be done anyway before we release.

**Comment by myriamboure** [comment]
@kristinalim @lin-d-hop @RachL  can I have a review of my proposal for the cancellation email template ? cf last post. I need to clarify that as part of subs remaining stories. Thanks !

**Comment by lin-d-hop** [comment]
Nice work Myriam!
The template looks great. From the top here are my English suggestions:

"If you have changed your mind or don't wish to cancel this order please contact [hub manager email]"
_I think you can remove the line_ "Here are the details of what you ordered:" 
"Your order was unpaid so no refund has been made"
"Your order was paid so Superhub has refunded the full amount"
"Your order was paid so your account has been credited"

**Comment by myriamboure** [comment]
@lin-d-hop about deleting the line "Here are the details of what you ordered:" see:
- order confirmation email
![capture du 2019-01-24 19-47-06](https://user-images.githubusercontent.com/8135376/51701282-6c98d900-2011-11e9-96c6-677595e45197.png)
- in subs, notification email saying was unable to place the order
![capture du 2019-01-24 19-46-00](https://user-images.githubusercontent.com/8135376/51701291-715d8d00-2011-11e9-92ac-d6f171f5f49d.png)

So for consistency I would keep it in that model too... but if other agree I'm happy to remove it, I agree with you that it might not be necessary.

Happy about the other phrasing changes. I will update now the main post with the latest version.

**Comment by lin-d-hop** [comment]
Great!
Note that even though I suggest removing the line, I made a small update to the text for more native english (though your English is near perfect ;-)): "Here are the details of what you ordered:"

**Comment by myriamboure** [comment]
Fixed, thanks @lin-d-hop :-) So if no one else raise a voice I will consider we have a consent around that order cancellation template :-)

**Comment by luisramos0** [comment]
Removing from the subs v1 epic as it's not part of the scope.

**Comment by luchiago** [comment]
Hi, can I work on this?

**Comment by sigmundpetersen** [comment]
Yes, you can pick up this one as well 👍
