### ISSUE TITLE
[Subscriptions] Make subs radio button visible for shop managers so that they can activate it :-)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2915]
## Description
This will be the last issue to work on when all the other bugs are fixed :-)
Today only super admin can see the radio button and activate it for a hub. When we are ready to release we will make this radio button visible to all hub managers !

![capture du 2018-10-23 16-16-39](https://user-images.githubusercontent.com/8135376/47366993-10a37900-d6df-11e8-96ed-12006c1f4e42.png)

**Comment by lin-d-hop** [comment]
It would be great if this was not made available for all users unless super admin allows.
UK have incorporated this into our pricing model and if users can turn on without paying it would not be ideal for us.

**Comment by luisramos0** [comment]
@lin-d-hop can you please clarify? I think it will be a bit more complicated.

your request seems to be to add a new checkbox somewhere on the global configuration to activate this activate button for managers? where would that option be? general config after "embedded shopfront settings" for example?

**Comment by luisramos0** [comment]
or do you want the checkbox to be for each enterprise?
so, super admin would have to activate for a given enterprise and then the enterprise could activate it or not? I am confused :-)

**Comment by lin-d-hop** [comment]
To be honest we spoke about this at the global gathering and I'm not sure the extra faff is worth it. I can't imagine any user will actually start using this feature to a significant degree and somehow go under the radar on user fees. Perhaps it is better to wait until there is a significant revenue implication for not having it.

In other words... ignore my comment above :-)

**Comment by luisramos0** [comment]
ok, thanks, I'll enable this to all managers.
