### ISSUE TITLE
Location markers not moving with changes to addresses - UK Production

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#2917]
## Description

When changing the address of an enterprise within spree, the changes pull through however the location markers do not change

## Expected Behavior

You change the address and the location marker changes too

## Actual Behavior

You can change the details of the enterprise in spree, but the location marker remains in the same location as the previous place, even though the details have been updated.
For instance with Audacious Veg, the initial marker is in Hainault, thus the prefix on the page when i open my shop states "Hainault, hain"

I go in and change the address, taking away hainault and adding Plaistow instead and moving the location to central london. You can see part of the address changes, but the marker is in the incorrect place.

## Steps to Reproduce

1. Go to an enterprise, look at its location on the map and then change it in spree
2. Go to the map, refresh, view the location of the enterprise. It's in the same place, but the details have changed (it'll state the new town, but not actually put it there.

Audacious Veg can be viewed as an incorrect example. The location marker is in Hainault (north east london), but the address is in East London.

## Animated Gif/Screenshot

The old address
![image](https://user-images.githubusercontent.com/28807449/47384652-c67ebf80-d6ff-11e8-87af-7930ede72ef5.png)

The new address
![image](https://user-images.githubusercontent.com/28807449/47384593-9f27f280-d6ff-11e8-8859-c5de82c9c495.png)

Where it should be
****
![image](https://user-images.githubusercontent.com/28807449/47384433-13ae6180-d6ff-11e8-9ab9-8f2785df8d82.png)

Where is still remains
![image](https://user-images.githubusercontent.com/28807449/47384460-245ed780-d6ff-11e8-90a3-db047ed5a655.png)

Details of the change are there - the town says plaistow, but the icon is incorrect
![image](https://user-images.githubusercontent.com/28807449/47384720-f6c65e00-d6ff-11e8-84f2-aef157cf131f.png)

## Context

This is affecting a Food Assembly due to go live this week.

## Your Environment

* Version used:
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Desktop

## Possible Fix

Markers should change when the address is changed

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Producer icon not displaying in correct place on map](https://trello.com/c/OcuKCv5W/268-producer-icon-not-displaying-in-correct-place-on-map)

**Comment by RachL** [comment]
Hello @sineadfenton if I'm not mistaken, this has been tackled by https://github.com/openfoodfoundation/openfoodnetwork/issues/2765 . Next release on UK production should have the fix, but best is to check with @Matt-Yorkley

**Comment by RachL** [comment]
So I'm closing this, feel free to reopen if you think I was wrong!

**Comment by sineadfenton** [comment]
Cheers @RachL totally missed that, thanks. I;; close this
