### ISSUE TITLE
Impossible to change producer behind a product

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2925]
## Description
A user in France made a mistake, she has two enterprises (as she wants to offer her catalog at two different prices for individuals and pro and this option was the easiest for her as we can't have pricing tables). She created a long list of products. Then instead of recreating / duplicating each product to then assign them to the second producer, she directly assigned them to the second producer, so she basically changed the ownership of the products to the second enterprise, while she had also a test OC open :see_no_evil: 
I explained her she had to do the reverse operation and then we will create another catalog for the second enterprise by duplicating the products (waiting for the bug to be fixed), but when she tried to do the revers operation, she got an error. I investigated, fixed some variants unit issues, saving works well on quantities and prices, unlike in issue #2919. She probably did different wrong actions, on variants, etc so it might have messed up data somehow... but I can't tell :-(

I tried to really wait for the product page to be loaded, then change producer name, save and don't switch tab, just wait. Got error 500:
![capture du 2018-10-25 14-55-17](https://user-images.githubusercontent.com/8135376/47502166-63a83800-d867-11e8-8166-b7b3ae77c69e.png)

Then I tried as @mkllnk suggested in the issue 2919 to to edit the product and try to change the producer there, but I also got an error, here error 502 with the snail:
![capture du 2018-10-25 14-58-01](https://user-images.githubusercontent.com/8135376/47502228-8d615f00-d867-11e8-96db-f2ee9aef3766.png)

In both cases, if I refresh the page, data is not saved.

Si basically I am stuck. There is no really workaround, appart recreate manually all the products, which she spent 2 hours to do so I don't want to ask her that again. Do you have some clue? Else I guess I will have to recreate all the products one by one on the first enterprise, but we need anyway to fix the bug.

## Expected Behavior

Hub manager can change producer owner of a product (given she is owning both enterprises)

## Actual Behavior

She can't.

## Steps to Reproduce

i don't really know how to reproduce as it seems to be a mix of data mismanagement, so if devs have some clue reading the dev console please share them !

1. On french prod go to products, filter for EARL Sandra et matthieu gibert.
2. On any product, try to change the owner for Ferme de Sandra et matthieu gibert and see the error.

## Context

User reported it and is stuck.

## Severity
I would say S2 as I don't think recreating the product list is a valid workaround? I mean it could be for a single product...

## Your Environment

* Version used: V1.21
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu 18

**Comment by myriamboure** [comment]
Happy to discuss the severity of course... it will take me 2 hours to recreate the products, so maybe that's much less time than a dev would spend to solve it and we prefer to opt for that option for now... but I wait for some analysis and we can decide.

**Comment by kirstenalarsen** [comment]
there are obviously some robustness issues in this area, but if it's going to take 2 hours to recreate the products I'd be leaning towards saying that might be the most efficient action 'global team' wise - there are so many bugs and things floating around that if there is a way to avoid a dev spending time investigating this that would be preferable @myriamboure ?

**Comment by daniellemoorhead** [comment]
I agree with @kirstenalarsen. As much as it's not the best use of your time @myriamboure I think Spree upgrade needs to take priority over this, especially when there have been so many S2 bugs of late. Should we move this back to being an s3 given there's a workaround?

**Comment by luisramos0** [comment]
lets have a look at the logs. maybe it's an easy one.

@myriamboure can you give my user access to that enterprise?

**Comment by myriamboure** [comment]
Ok we have organized with @RachL she is manuelle recreating the products for now so I switch this to S3. @luisramos0 if you have more emergencies this is a bit less urgent then.

**Comment by luisramos0** [comment]
ok, I had a look and it's not straight forward.
Here's what I have seen:
the request to save the data is apparently successful on the server but the page sees a 502 (not 500 as you are seeing). 502 is probably related to some timeout.
Here are the logs for reference. I'll leave it for now.
```

Started POST "/admin/products/bulk_update" for 83.223.250.110 at 2018-10-26 15:35:35 +0200
Processing by Spree::Admin::ProductsController#bulk_update as HTML
  Parameters: {"products"=>[{"id"=>3452, "supplier_id"=>648}, {"id"=>3453, "supplier_id"=>648}], "filters"=>nil, "product"=>{}}
  Rendered json/_injection_ams.html.haml (12.2ms)
  Rendered shared/components/_enterprise_search.html.haml (1.4ms)
  Rendered shared/components/_filter_controls.html.haml (0.6ms)
  Rendered shared/components/_filter_box.html.haml (0.5ms)
  Rendered producers/_filters.html.haml (2.3ms)
  Rendered producers/_skinny.html.haml (0.6ms)
  Rendered producers/_fat.html.haml (1.2ms)
  Rendered shared/components/_enterprise_no_results.html.haml (0.6ms)
  Rendered shared/_register_call.html.haml (0.9ms)
  Rendered shared/_footer.html.haml (6.8ms)
  Rendered producers/index.html.haml within layouts/darkswarm (10528.6ms)
  Rendered layouts/_i18n_script.html.haml (0.9ms)
  Rendered layouts/_bugherd_script.html.haml (0.7ms)
  Rendered layouts/_matomo_tag.html.haml (1.2ms)
  Rendered shared/_ie_warning.html.haml (1.0ms)
  Rendered json/_injection_ams.html.haml (0.5ms)
  Rendered json/_current_user.rabl (1.1ms)
  Rendered json/_injection.html.haml (1.8ms)
  Rendered json/_flash.rabl (0.7ms)
  Rendered json/_injection.html.haml (1.3ms)
  Rendered json/_injection_ams.html.haml (0.8ms)
  Rendered json/_injection_ams.html.haml (0.6ms)
  Rendered json/_injection_ams.html.haml (0.5ms)
  Rendered json/_injection_ams.html.haml (0.5ms)
  Rendered shared/_signed_out.html.haml (0.5ms)
  Rendered shared/menu/_cart.html.haml (1.5ms)
  Rendered shared/menu/_large_menu.html.haml (6.5ms)
  Rendered shared/menu/_cart.html.haml (1.4ms)
  Rendered shared/_signed_out.html.haml (0.5ms)
  Rendered shared/menu/_mobile_menu.html.haml (12.5ms)
  Rendered shared/menu/_menu.html.haml (19.7ms)
  Rendered /home/openfoodnetwork/.gem/ruby/2.1.0/bundler/gems/spree-69db1c090f37/frontend/app/views/spree/shared/_google_analytics.html.erb (1.1ms)
  Rendered layouts/darkswarm.html.haml (10629.4ms)
Completed 200 OK in 10632.8ms (Views: 5805.5ms | ActiveRecord: 4824.9ms)
```

**Comment by myriamboure** [comment]
We tested again and it seems that the problem is not here anymore. So closing the issue, we will reopen if necessary.
