### ISSUE TITLE
Australia is added as a country within migration scripts

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#293]
Previous comment added https://github.com/openfoodfoundation/openfoodnetwork/commit/c35112a40c793ad68bcd10a48a6c9afddbc73d4b#commitcomment-7074187.

This causes a bug stopping the billing address being filled out during checkout, because the `:default_country_id` does not match `12`, which is assumed elsewhere.

It also causes problems with #236.

**Comment by pmackay** [comment]
I've suggested in #441 that it would be preferable to use the 2 letter ISO code, rather than the name. Would that have any negative issues on these changes?

**Comment by mkllnk** [comment]
Your pull request #454 looks good. Are there any other open issues relating to this one ore can we close this issue?

**Comment by pmackay** [comment]
Not that I can think of...
