### ISSUE TITLE
[Spree Upgrade] Fix Weight calculator

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2931]
In Spree 2, what gets sent to the calculator is a Package and the weight calculator needs to calculate based on that type of object.

**Comment by luisramos0** [comment]
reopening, this issue represents the problem in the 2-0 branch. we need to merge #3072 to 2-0-stable and verify that it does fix the 3 broken specs.

**Comment by luisramos0** [comment]
connected this to the merge PR #3311, the PR does close this issue and this issue can be closed when the PR 3311 is merged into 2-0-stable.

**Comment by sigmundpetersen** [comment]
Close issue?

**Comment by luisramos0** [comment]
ah, yes, thanks for the heads up!
I verified, the tests are all green on the 2-0 build.
