### ISSUE TITLE
[Spree Upgrade] [Broken Test] Fix action orders.show, gone in spree 2 

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2937]
Orders show is gone in Spree 2 since:
https://github.com/spree/spree/commit/4e54ceda35397fe81399c8ca4e951e123d1a63f3

All occurrences of admin_order_path will fail. Maybe they need to be fixed, or we just redirect to edit.

the two only remaining occurrences are:
- order_serializer.show_path - we need to investigate if we can remove order_serializer method show_path.  Where is it really used? Otherwise it will be a redirect to edit.
- ordersHelper.order_links(order). Where are these links used?

**Comment by Matt-Yorkley** [comment]
We've discussed previously the idea that orders will become non-editable at some point in the delivery process... so I think reimplementing Orders#show is the way to go.
