### ISSUE TITLE
Product import not working on French instance with simple file

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2951]
## Description

A new user has some excel files to populate to create their catalog in OFN. I did try to do the first import for them, and it is not working, and no error displays.

## Expected Behavior

I can upload a list of product with product import feature.

## Actual Behavior

I can't.

## Steps to Reproduce

1. On french instance, go to https://www.openfoodfrance.org/admin/product_import
2. Try to import a simple file like https://drive.google.com/open?id=1JKDfEcb-VhSL_wqEhXZl2nFoWkFKhIcF of course make sure the producer already exists
3. See the error, the file can't be uploaded, and no error message is displayed

## Animated Gif/Screenshot

![capture du 2018-10-25 22-17-13](https://user-images.githubusercontent.com/8135376/47638047-cba79880-db5d-11e8-96c9-0dca132f9a94.png)

## Context

A new promising user on OFFrance want to upload their producer catalog.

## Severity
S3 - S2, you can still create manually products, but for hundreds of products it becomes complicated. Here I put S3 for now, we start with only one list that if it doesn't work we can fill in manually, it's only around 30 products...

**Comment by Matt-Yorkley** [comment]
I think this is the same issue as #2836. Files have to be saved with UTF-8 encoding, but Excel sometimes defaults to other encodings. See my comment here: https://github.com/openfoodfoundation/openfoodnetwork/issues/2836#issuecomment-436257578

**Comment by myriamboure** [comment]
Unfortunately it's not that @Matt-Yorkley I'll show you tomorrow :-( And no error message is displayed...

**Comment by Matt-Yorkley** [comment]
I've investigated a bit further, and there was an uncaught product validation error related to missing tax category. The reason this has only shown up on French production is because you have this set on the instance:

![screenshot from 2018-11-18 20-31-40](https://user-images.githubusercontent.com/9029026/48677750-5bdf6900-eb71-11e8-8b83-3647d665cfbf.png)
 
I guess nobody else has this set. So this means on French production, the tax category has to be specified for each product being uploaded. I'll make a quick PR now to give user feedback in this case.

**Comment by myriamboure** [comment]
Great investigations @Matt-Yorkley !!!
I'll test in a couple of days, but if it's a super admin setup, if the PR is take a bit of time, we can just specify in super admin handbook and uncheck this on French production instance... it's not so important actually, I don't know why we have this setup. If I had known that could be that I would have just unchecked I think and not even open an issue. So if it's 10 min let's display the error message but else, let's not dedicate more time on it, you found a solution already :-)

**Comment by Matt-Yorkley** [comment]
I've already made a PR to give basic feedback in this case. :+1:
