### ISSUE TITLE
[Spree Upgrade][Phase 2] Fix non-core features

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2953]
Non core features have been commented out in the build and will need to be fixed when the core functionality is ready to go.
These features are:
- reports
- subscriptions
- product import
- bulk invoices
- account invoices
- paypal integration

**Comment by luisramos0** [comment]
for reference, I validated paypal integration is working in v2, I did a basic setup and managed to pay an order through a paypal sandbox account.

**Comment by sauloperez** [comment]
Is this sandbox setup documented somewhere in the wiki? It'd be great to have it up to date as we did with Stripe recently.

**Comment by luisramos0** [comment]
I put some details here: https://docs.google.com/document/d/15EdXKb4B3BS8gekD6_9PDdPTZsjUCAVS2011zRf55lM/edit#
