### ISSUE TITLE
[Flaky Spec] Fix unreliable bulk_order_management_spec.rb feature spec

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2962]
## Description

I found this error while passing CI on https://github.com/openfoodfoundation/openfoodnetwork/pull/2958. You can check the CI build on https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-2958/builds/2

It's totally unrelated to that PR's change so it's likely an unreliable test that needs to be fixed.
 
```
1) 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using action buttons using edit buttons shows an edit button for line_items, which takes the user to the standard edit page for the order
     Got 1 failure and 1 other error:

     1.1) Failure/Error: expect(URI.parse(current_url).path).to eq "/admin/orders/#{o1.number}/edit"
          
            expected: "/admin/orders/R722674705/edit"
                 got: "/admin/orders//edit"
          
            (compared using ==)
          # ./spec/features/admin/bulk_order_management_spec.rb:625:in `block (5 levels) in <top (required)>'

     1.2) Failure/Error: @app.call(env)
          
          ActiveRecord::RecordNotFound:
            Couldn't find Spree::Order with number = edit
          # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
          # ------------------
          # --- Caused by: ---
          # Capybara::CapybaraError:
          #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
          #   ./spec/spec_helper.rb:92:in `block (2 levels) in <top (required)>'

Finished in 18 minutes 29 seconds (files took 36.69 seconds to load)
855 examples, 1 failure, 5 pending

Failed examples:

rspec ./spec/features/admin/bulk_order_management_spec.rb:605 # 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using action buttons using edit buttons shows an edit button for line_items, which takes the user to the standard edit page for the order
```

## Expected Behavior

This test should always pass.

## Actual Behavior

I don't have data to claim it failed before, but I bet it did.

**Comment by sauloperez** [comment]
Would you agree on considering this a bug? it's a part of our codebase that is misfunctioning, aka. bug. We got to do something with the unreliability of our test suite...

**Comment by luisramos0** [comment]
I dont think it's a bug. It's high priority tech debt.
A bug is pushed by users/biz. This is something we devs really want to fix now but may not have time = tech debt.

**Comment by Matt-Yorkley** [comment]
Looks like there's an order without an order number, which is not possible. Could be another classic angular issue with the check happening before the data has fully finished loading. Is it failing consistently or occasionally?

**Comment by luisramos0** [comment]
oh, I jus saw the column in zenhub "tech debt backlog" awesome. devs need to find a spacetime to prioritize this. thanks @myriamboure

**Comment by daniellemoorhead** [comment]
Managing tech debt be like

![](https://media.giphy.com/media/sXOj0wtpyELdu/giphy.gif)

😆

**Comment by kirstenalarsen** [comment]
oh my god. this should also be in our communications somewhere! "Want to know why that bug isn't fixed yet? see below"
