### ISSUE TITLE
The checkbox and delete function, and trash button in BOM doesn't work

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2965]
## Description
There's checkboxed in the BOM page. You should be able to select products and then use the action>delete selected function to delete those lines from orders. Instead when I click delete I'm asked 'are you sure', i click yes, then the items disappear from the list. But if i reload the page the items return, and the items also remain on the order.

The trash icon itself has the same behaviour - looks like it's deleted the item but it hasn't really

## Expected Behavior
When I delete something from the list it should be removed from the orders.

## Actual Behavior
It appears the item is deleted but it has not actually been delete.

## Steps to Reproduce
1. Go to BOM and see items ordered
2. click the select box next to an item
3. Go to actions - delete selected, and click yes when asked 'are you sure'
4. See that hte item is removed from the list
5. Now reload the page and see the item has returned. Also see item still on order.

## Context
I found this while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2912 . The real life scenario is that I have received 10 orders for milk but my milk delivery did not come. I want to delete milk from all 10 orders that asked for milk and BOM is a place to do this quickly. If I use this tool I might think milk was deleted from orders, but in fact the milk is still in customer ordrers

## Severity
S3 - you can work around this issue, but it's a bit of a trap because you think it has worked when it has not.

## Your Environment
PC, AUs production. chrome.

## Possible Fix
Make it a true delete.

**Comment by myriamboure** [comment]
@sstead I invite you to judge if that s3 is somehow prioritory compared to others and place in the "bug backlog" column compared to the other S3 bugs regarding the level of priority you perceive... let's start some collaborative priorization work on this bug  backlog :-) Cheers!

**Comment by RachL** [comment]
I just tested this and it works (katuma staging and France production). I'm closing this. Let's reopen if we see it happens again.
