### ISSUE TITLE
Duplicates show in Orders list

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2966]
## Description
Sometimes I see duplicate errors in the Orders list..

This error has been reported by a users of ours too

## Steps to Reproduce
Here is a video showing the steps which lead up to the error … 
https://www.useloom.com/share/35983a9e90b84c13b7ae1a79315066ad

## Context
Just confusing

## Severity
s4

## Your Environment
PC, Aus rpoduction, chrome

**Comment by RachL** [comment]
Not sure how to reproduce...closing it. We can reopen if needed.
