### ISSUE TITLE
[Spree Upgrade][BackOffice] Fix deleting enterprise fee behaviour (1 broken test)

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2987]
## Description

In `spec/features/admin/enterprise_fees_spec.rb:122`, when deleting an enterprise fee that is referenced by a product, a banner should show up and the deletion should fail. 

In browser, we can see that it's not the case : the enterprise fee disappears with no banner, and when reloading the page it's still here.

This is the last failing spec of Job#1 o/

## Expected Behavior

`spec/features/admin/enterprise_fees_spec.rb:122` spec should pass

## Actual Behavior

The spec fails.

## Steps to Reproduce

1. On 2-0-stable, go to Enterprises, Enterprise fees
2. Try to delete one that is referenced by a product (in Product Distributions)
3. It should disappear, and show up once you reload the page

## Possible Fix

It seems to be a problem of views, maybe Angular, because the fee is indeed NOT deleted, but the view acts as if it was.

It could be related to Jquery, in master the request is made in JS : 
![screenshot from 2018-11-07 21-19-01](https://user-images.githubusercontent.com/28786869/48158438-c9b6a580-e2d2-11e8-91c1-d12d6635b4f7.png)
and in 2-0-stable it's made in HTML : 
![screenshot from 2018-11-07 21-17-51](https://user-images.githubusercontent.com/28786869/48158452-d4713a80-e2d2-11e8-8080-e2898d9791cf.png)

This is supposed to be made in AJAX right ? Jquery was bumped from 2.0 to 3.0, maybe it's somewhere over there.

**Comment by RachL** [comment]
Closing as PR #3011 is going to be merged.

**Comment by luisramos0** [comment]
This issue is for the 2-0 branch @RachL 
We need to wait for master to be merged into 2-0 and check that the test is now passing in the build:

```
 26) 
    As an administrator
    I want to manage enterprise fees
 deleting a shipping method referenced by a product distribution
      Failure/Error: expect(page).to have_content "That enterprise fee cannot be deleted as it is referenced by a product distribution: #{p.id} - #{p.name}."
        expected to find text "That enterprise fee cannot be deleted as it is referenced by a product distribution: 188 - Product #183 - 3929." in "Logged In As : aditya@weissnat.ca Account Logout Store DASHBOARD ORDERS PRODUCTS REPORTS CONFIGURATION USERS ORDER CYCLES GROUPS ENTERPRISES CUSTOMERS Enterprise Fees ENTERPRISE FEE TYPE NAME TAX CATEGORY CALCULATOR CALCULATOR VALUES"
      # ./spec/features/admin/enterprise_fees_spec.rb:122:in `block (2 levels) in <top (required)>'

```

**Comment by sigmundpetersen** [comment]
@luisramos0 I couldn't find the failed spec in latest 2.0 build so I guess we can close?

**Comment by luisramos0** [comment]
yes, I checked yesterday but I forgot to the close the issue. thanks for the heads up!

well done @HugsDaniel for fixing this with a good approach!
