### ISSUE TITLE
[Spree Upgrade] Fix products_and_inventory_report pending spec (1 broken spec)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3021]
Fix spec spec/lib/open_food_network/products_and_inventory_report_spec.rb
moved to xdescribe in #3019

Job 4 - 1 x spec/lib/open_food_network/products_and_inventory_report_spec.rb:105
```
2) OpenFoodNetwork::ProductsAndInventoryReport As an enterprise user Filtering variants should filter deleted products
     Failure/Error: subject.filter(Spree::Variant.scoped).should match_array [product1.master, product1.variants.first]
     
       expected collection contained:  [#<Spree::Variant id: 2329, sku: "ABC", weight: #<BigDecimal:7f13b76be780,'0.1E-2',9(36)>, height: ni..."AUD", unit_value: 1.0, unit_description: "", display_name: nil, display_as: nil, import_date: nil>]
       actual collection contained:    [#<Spree::Variant id: 2329, sku: "ABC", weight: #<BigDecimal:7f13b76b3c40,'0.0',9(18)>, height: nil, ..."AUD", unit_value: 1.0, unit_description: "", display_name: nil, display_as: nil, import_date: nil>]
       the extra elements were:        [#<Spree::Variant id: 2331, sku: "ABC", weight: #<BigDecimal:7f13b76aaeb0,'0.0',9(18)>, height: nil, ..."AUD", unit_value: 1.0, unit_description: "", display_name: nil, display_as: nil, import_date: nil>]
     # ./spec/lib/open_food_network/products_and_inventory_report_spec.rb:109:in `block (4 levels) in <module:OpenFoodNetwork>'
```

this test
```
        it "should filter deleted products" do
          product1 = create(:simple_product, supplier: supplier)
          product2 = create(:simple_product, supplier: supplier)
          product2.delete
          subject.filter(Spree::Variant.scoped).should match_array [product1.master, product1.variants.first]
        end
```

product2.delete is not removing product2's variants from the scope as expected.

**Comment by mkllnk** [comment]
From the Changelog:
> Calling #destroy on any PaymentMethod, Product, TaxCategory, TaxRate or Variant object will now no longer delete that object. Instead, the `deleted_at` attribute on that object will be set to the current time. Attempting to find that object again using something such as `Spree::Product.find(1)` will fail because there is now a default scope to only find *non*-deleted records on these models. To remove this scope, use `Spree::Product.unscoped.find(1)`.

Our current usage of `destroy` is probably no problem. But we need to look for `delete` and other calls that were removed from the following models:

- [ ] PaymentMethod
- [ ] Product
- [ ] TaxCategory
- [ ] TaxRate
- [ ] Variant

**Comment by luisramos0** [comment]
we need to wait for the next merge from master to 2-0 and then see that the spec is green.

**Comment by luisramos0** [comment]
I have confirmed that this spec is fixed.
