### ISSUE TITLE
[Spree Upgrade][BackOffice] Fix redirection issue in admin products controller (2 broken tests)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3031]
Fix spec/controllers/spree/admin/products_controller_spec.rb

```
 18) Spree::Admin::ProductsController creating a new product redirects to products when the user hits 'create'
      Failure/Error: response.should redirect_to spree.admin_products_path
        Expected response to be a <:redirect>, but was <200>
      # ./spec/controllers/spree/admin/products_controller_spec.rb:96:in `block (3 levels) in <top (required)>'

  19) Spree::Admin::ProductsController creating a new product redirects to new when the user hits 'add_another'
      Failure/Error: response.should redirect_to "/admin/products/new"
        Expected response to be a <:redirect>, but was <200>
      # ./spec/controllers/spree/admin/products_controller_spec.rb:116:in `block (3 levels) in <top (required)>'
```

This should be a simple fix after #2982 is fixed.

**Comment by luisramos0** [comment]
Looking at this with the branch in #2982, I cant figure this one out...
The redirects are working correctly, but for some reason the 302 response is not showing up on the test. It does show on dev tools _ network when testing manually.
@sauloperez do you want to have a look at this one? Could be a quick one for you.

**Comment by daniellemoorhead** [comment]
Hey @sauloperez now that #3206 is merged can this be closed, or will further work be done on it and therefore it should be back to the In Dev column?

#toottoot

**Comment by luisramos0** [comment]
It's fixed.
