### ISSUE TITLE
[Defacepocalypse] Convert products/new/replace_form.html.haml.deface to an OFN view

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3050]
## Description

We need to refactor [app/overrides/spree/admin/products/new/replace_form.html.haml.deface](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/overrides/spree/admin/products/new/replace_form.html.haml.deface) in `master` to have the same behavior but using an OFN view. 

To do that we need to:

1. Bring Spree's [backend/app/views/spree/admin/products/new.html.erb](https://github.com/openfoodfoundation/spree/blob/step-6a/backend/app/views/spree/admin/products/new.html.erb) into this repo.
2. Apply OFN's [app/overrides/spree/admin/products/new/replace_form.html.haml.deface](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/overrides/spree/admin/products/new/replace_form.html.haml.deface) on top
3. Ensure all other overrides still work, which should be the ones in [app/overrides/spree/admin/products/_form](https://github.com/openfoodfoundation/openfoodnetwork/tree/master/app/overrides/spree/admin/products/_form)
3. Remove [app/overrides/spree/admin/products/new/replace_form.html.haml.deface](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/overrides/spree/admin/products/new/replace_form.html.haml.deface)

**Comment by HugsDaniel** [comment]
Should I do this in master ?

**Comment by sauloperez** [comment]
Yes, please.
