### ISSUE TITLE
[Domains] Move Orders model and controller to Order Management engine

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3052]
It was discussed in the Porto gathering that this would be the best next step for the evolution of OFN into Domains.
Creating a Domain of a core component of OFN is really what we need to be assured this separation into domains will not cause to much trouble and still delivery its value of breaking OFN business logic into smaller less complex parts.
The chosen domain was the BackOffice Order management (maybe we can call it Order Fulfilment, a very common name for this component in other retail systems). In this issue we should create the new BackOffice domain and move the Spree::Order object decorator, its controller and also the back office order management pages. We can either move a big part of this scope or maybe start we some of the parts, like the Order Edit page.

This work as being discussed in https://community.openfoodnetwork.org/t/breaking-ofn-down-into-domains/1377
It has been documented in https://github.com/openfoodfoundation/openfoodnetwork/wiki/Tech-Doc:-How-OFN-is-organized-in-Domains-using-Rails-Engines
And it has been started in https://github.com/openfoodfoundation/openfoodnetwork/pull/2521

**Comment by luisramos0** [comment]
We already have a OrderManagement engine with some reports code. This issue now represents the move of the Orders model and controller to the engine.

**Comment by lin-d-hop** [comment]
CLosing as this is no longer an agreed forthcoming priority.... still might be a good idea :)
