### ISSUE TITLE
Maps API not working

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3056]
## Description

Map markers are not working on the new Belgian instance at: https://openfoodnetwork.be 
The API key has been provisioned correctly, and the Maps Javascript API is receiving requests. There are no requests going to the Geolocation API though, and new enterprises do not appear on the map.

![screenshot from 2018-11-10 16-11-53](https://user-images.githubusercontent.com/9029026/48570649-ba4fe180-e8fc-11e8-9da7-38d6d100bc1f.png)

## Expected Behavior

Map should be working and showing enterprises.

## Actual Behavior

No enterprises are shown.

## Steps to Reproduce

1. Create an enterprise on https://openfoodnetwork.be 
2. Go to /map page

## Severity

bug-s2: a non-critical feature is broken, no workaround

**Comment by Matt-Yorkley** [comment]
For background: the Google account is set up and has billing attached. The API key has no restrictions.

**Comment by Matt-Yorkley** [comment]
I'm not getting any errors in Bugsnag, or in the logs.

**Comment by sauloperez** [comment]
wasn't the Geocoding API the one we use? Does it need to be enabled manually from the Google account?

**Comment by Matt-Yorkley** [comment]
Ah, that screenshot was old. Here's a recent one: 
![screenshot from 2018-11-15 18-05-51](https://user-images.githubusercontent.com/9029026/48572383-419f5400-e901-11e8-9f96-62e595dde98e.png)

**Comment by sauloperez** [comment]
that's very weird... did you provision and deploy the latest version of both repos?

**Comment by Matt-Yorkley** [comment]
Yes. I'll try updating again.

**Comment by Matt-Yorkley** [comment]
I redeployed (the same release) and it seems to be fixed. Maybe it was the unicorn/nginx restart that did it? I can't believe the answer was "turn it off and on again"... :unamused:
