### ISSUE TITLE
UX: Make all map icons green

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#3060]
## Description

This is a small UX issue, that is a quick win and was agreed in conversations on Slack. Great first issue for new devs!

The OFN map is confusing for users. Map icons are green and red, though the meaning of these colours is not well communicated and generally not well understood even by OFN core contributors. The assumption by new users is that Red icons mean closed and Green mean open. This makes it look like OFN is full of closed shops, which does not look good.

There are ongoing discussions about completely designing the OFN map, which is a much bigger task requiring a lot of design. This issue is a quick win to reduce the confusion.

This issue involves simply changing the colour of all map icons such that all map icons are green, to use the existing green colour for all icons.

## Expected Behavior

All icons on the map appear Green.

## Actual Behavior

Some map icons appear in Red while others appear in Green.

## Steps to Reproduce

1. Look at the map
2. See the green and red icons
3. Be confused about their meaning :-)

## Animated Gif/Screenshot

![embed](https://user-images.githubusercontent.com/8669848/48618021-f2eccb00-e98f-11e8-920d-fa28d7aff649.png)

## Context

Many new users to OFN ask why the map icons are two different colours and ask why so many shops on OFN are closed. They ask what is wrong with the software if there are a lot of users that don't use the platform. And they ask why their own shops appear closed when they are open. This is an annoying question for administrators and onboarders to have to answer all the time.

## Severity
bug-s4: it's annoying, but you can use it

## Possible Fix

Update all map icons to use the green colour such that no map icons appear in Red.

**Comment by myriamboure** [comment]
@lin-d-hop this is not a bug but a new feature, can you please put that in a wishlist? You can straight away vote on it, if you do the discovery/inception, list potential solutions, and propose a feature candidate it can go quickly through potentially. There are some discussions around mapping improvement and I think there might be some other options we want to discuss. We want to stop opening issues for new feature in GH, remember ? ;-) #withmuchofloveofcourse

**Comment by lin-d-hop** [comment]
I can do that but I feel like being such a tiny fix that is a 'Good First Issue' it makes more sense to just open an issue for it.
I do think that it's good to just open 'Good First Issues' because then we have a lot available for dabbling devs to take a look at and tick off. I feel like we'll be wasting all of our time to bother putting something so simple in the Community pipeline.
Closing.....

**Comment by lin-d-hop** [comment]
https://community.openfoodnetwork.org/t/ux-make-make-icons-green/1505
