### ISSUE TITLE
Repeated translation in Order Confirmation Screen and Email

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#3063]
On both the customer screen after ordering and in the email sent to customers, the 'Ready for collection' string appears twice. First time it is followed by the 'Ready for message' and the second time by 'Pick up message'.
The second string needs to be independent of the first so they can be translated separately in Transifex.

## Description
 More details of the bug can be found on the user forum :
https://community.openfoodnetwork.org.uk/t/bug-in-order-confirmation-email/376

In Transifex the two strings are numbers 1131 and 1205. I think there should be 4 strings (2 for each of the email and the confirmation screen).

Maikel from #dev channel on Slack identified:
The only way to tell which string is used where is by looking into the code. Our source locale is `en.yml`: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/en.yml
There you can find the translation key that is used in the code. One string is called `order_pickup_time` and the other one is called `email_shipping_collection_time`. The latter is used in two places in `app/views/spree/order_mailer/_shipping.html.haml`. The other one is used once in `app/views/spree/shared/_order_details.html.haml`.

You need to change the code in `app/views/spree/order_mailer/_shipping.html.haml` which accidentally uses the same translation twice. The second time it should use a different text. It's probably a copy&paste error.

## Expected Behavior
1st label on left of order confirmation screen should read 'Ready for collection' followed by user inputted 'ready for message' 

2nd label on left of order confirmation screen should read 'Collection Instructions' followed by user inputted 'pick up message' 

Same for order confirmation email

## Actual Behavior
1st label on left of order confirmation screen reads 'Ready for collection' followed by user inputted 'ready for message' 

2nd label on left of order confirmation screen reads 'Ready for Collection' followed by user inputted 'pick up message' 

Same for order confirmation email

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/45104035/48637327-52b19900-e9c5-11e8-85c6-54efeb903b83.png)
 
## Context
 OFN user spotted the error and thought it was confusing to the customer

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment
OFN user reported the 'bug'. Unsure of environment.  Assume it occurs in all environments 

## Possible Fix
 The only way to tell which string is used where is by looking into the code. Our source locale is `en.yml`: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/en.yml
There you can find the translation key that is used in the code. One string is called `order_pickup_time` and the other one is called `email_shipping_collection_time`. The latter is used in two places in `app/views/spree/order_mailer/_shipping.html.haml`. The other one is used once in `app/views/spree/shared/_order_details.html.haml`.

You need to change the code in `app/views/spree/order_mailer/_shipping.html.haml` which accidentally uses the same translation twice. The second time it should use a different text. It's probably a copy&paste error.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug in order confirmation email](https://trello.com/c/qyWkIKZ5/301-bug-in-order-confirmation-email)

**Comment by luisramos0** [comment]
s4 should be "all the things" right @sigmundpetersen ?
