### ISSUE TITLE
Wrong display in order page after using filters

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3064]
## Description
This was reporter by an Australian user. I remember @sstead mentioned it in another issue, but I cannot find the issue anymore. At the time we did not manage to reproduced it. But now I think I've found how.

## Steps to Reproduce:
1. On order page /admin/orders?q[s]=completed_at+desc check "show unfulfilled orders only", then click on "filter orders"
2. On the same page, uncheck unfulfilled orders, and filter again
3. Now check “show complete orders only”. The page will show several times the last order :
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/2c1e290a-67da-4397-b8eb-3926ebd8ee05)

## Severity
bug-s4: it's annoying, but you can use it

If you reload completely the page the display is again correct. However I don't know how many users will think about reloading their page...

## Your Environment

* Version used: v1.22
* Browser name and version: Firefow 63
* Operating System and version (desktop or mobile): Ubuntu 18 LTS

## Possible Fix
No idea :-)

**Comment by Matt-Yorkley** [comment]
I've investigated this a bit further and found the checkbox for "show unfulfilled orders only" seems to respond to 3 states rather than 2: `true`, `false`, and `nil` give 3 different responses. Apparently this is the theme of the week!

**Comment by Matt-Yorkley** [comment]
I'd say it's s3 as in some cases I think it might stop users being able to see/edit all of their orders?
