### ISSUE TITLE
Inventory page says "on demand" in scenario where variant is not on demand for shop

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#3068]
Inventory page says "on demand" in scenario where variant is not on demand for shop.

## Description

With the following settings:

* Producer - On Demand: `true`, Count on Hand: 10
* Variant Override - On demand: false, Count on Hand: blank

The effective stock level is the producer's count on hand of 10. But the Inventory page still says that stock is "On Demand".

## Expected Behavior

PENDING

## Actual Behavior

PENDING

## Steps to Reproduce

Signed in as producer:

1. Create a product.
2. Set the variant to have 0 count on hand, and save.
3. Set the variant to be "on demand", and save. (Step 3 should no longer be relevant after this, but it is. A different issue will be created for this bug, but meanwhile we want to take advantage of it for testing.)
4. Grant distributor permission "to add to order cycle" and "to add products to inventory".

Signed in as the distributor:

1. Add a payment method and a shipping method to the distributor.
2. In "Inventory Settings", enable this: "New products must be added to my inventory before they can be put into my shopfront".
2. Add the variant to the inventory:
    a. Go to Products > Inventory.
    b. Click "Review Now" to see the list of products that can be added.
    c. Click "Add" for the variant.
3. Create an ongoing order cycle, and include the variant.
4. With `true` "on demand" - Using: VO setting of "on demand" (true)
    a. Go to Products > Inventory.
    b. Tick the "on demand" checkbox, and save. The "on hand" status says "On demand".
    e. The variant appears in the shop.
5. With `false` "on demand" - Using: VO setting of "on demand" (false), supplier setting of "count on hand" (0)
    a. Go to Products > Inventory.
    b. Untick the "on demand" checkbox, and save. The "on hand" status still says "On demand", but this is not the case.
    e. The variant does not appear in the shop.

## Context

Related to #3058.

## Severity

bug-s2

## Possible Fix

PENDING

**Comment by myriamboure** [comment]
I think the fix for this bug had been merged, if I'm mistaken @kristinalim please reopen.
