### ISSUE TITLE
Boot Angular automatically in orders#new view

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#3083]
### What we should change and why (this is tech debt)

Following the [conversation](https://github.com/openfoodfoundation/openfoodnetwork/pull/3053#discussion_r233864476) in #3053, in `app/views/spree/admin/products/new.html.haml ` Angular is booted manually at the bottom of the file.

We should figure out a way to boot it automatically, either with `content_for` or `ng-app`.

**Comment by RachL** [comment]
Closing as we are steeping away from Angular.
