### ISSUE TITLE
Skylight warning [E0001] Spans were closed out of order

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3101]
## Description

Skylight spits out a warning in `log/skylight.log` with the following contents:

```
[SKYLIGHT] [1.6.1] [E0001] Spans were closed out of order.
To debug this issue set `SKYLIGHT_ENABLE_TRACE_LOGS=true` in your environment. (Beware, it is quite noisy!)
This request will not be tracked. Please contact support@skylight.io for more information.
```

This might lead to loss of data, affecting the accuracy of the data we see when checking Skylight's graphs.

Check https://www.skylight.io/support/troubleshooting#e0001-spans-were-closed-out-of-order-and-invalid-span-nesting for details.

## Expected Behavior

There should be no warnings in `log/skylight.log`

## Actual Behavior

Skylight constantly outputs the message showed above.

## Steps to Reproduce

I checked this in UK, FR and Katuma's production. Just log into the machine and check it running:

```
$ tail -f log/skylight.log
```

**Comment by sauloperez** [comment]
Wow! the ruby agent is now at v3.1.1! https://github.com/skylightio/skylight-ruby/releases

**Comment by sauloperez** [comment]
Should be fixed with the release v1.23.1

**Comment by Matt-Yorkley** [comment]
Can we close this now then @sauloperez ?

**Comment by sauloperez** [comment]
Let me check

**Comment by sauloperez** [comment]
Nope :sob: I just check on Katuma's production and navigating through the app outputs

```
[SKYLIGHT] [1.7.1] [E0001] Spans were closed out of order.
To debug this issue set `SKYLIGHT_ENABLE_TRACE_LOGS=true` in your environment. (Beware, it is quite noisy!)

This request will not be tracked. Please contact support@skylight.io for more information.
```
