### ISSUE TITLE
[Spree Upgrade] Spree 2 has moved all tabs translations from en to en.spree.admin.tab

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3119]
In the backoffice, the main menu "Products" and the tabs "Products" and "Inventory" must be translatable. Spree 2 has moved tabs to spree.admin.tab, see here: https://github.com/spree/spree/commit/4c82bfdf489e63768b84020f37d7db197565ac30

This will fix:
- the first test in #3112 (Products - Inventory)
- this issue #3073 (Enterprises - Permissions)

But this issue should fix all tabs in the backoffice. Not just these two issues above.

See "Add missing Spree translations" here to understand what Spree.t does https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-(i18n)#development

Extra: we may use the opportunity to de-deface the product_sub_menu into a normal submenu under views/admin/shared or views/spree/admin/shared

**Comment by luisramos0** [comment]
@HugsDaniel I think the de-deface of product_sub_menu should be done in master.
The rest is 2-0-stable specific.

**Comment by daniellemoorhead** [comment]
OK team, it's been 18 days since any change on this issue. 

@HugsDaniel @luisramos0 @mkllnk does it need to stay in the in dev column or should it move back to Dev Ready till you pick it up again?

#toomanythingsinthepipe
#toottoot

**Comment by luisramos0** [comment]
up to @HugsDaniel to see if he is doing this one soon or not

**Comment by HugsDaniel** [comment]
I think we can put it back to Dev Ready, I have other things to do before.
