### ISSUE TITLE
Error when editing products from product list page

### ISSUE THREAD

**Issue by guidamt** [openfoodfoundation/openfoodnetwork#3120]
## Description

When editing and saving "unit" column on the products page, the following message appears when you choose "item" unit but don't fill the box: _not saved._ _There was an error saving unsupported data: 400_. Instead, by doing the same editing procedure from the product details page, the error message is: _variant unit name can't be blank_ which is much more understandable to users.

## Expected Behavior

The error message that appears when leaving unit box empty in "Unit" column from products list on "Poducts page" should be the same as the one that appears by editing products from "product details page".

## Actual Behavior

If you edit an existing product on product list and change any unit to "item" but leave empty unit box the error message is not clear to users: _not saved_There was an error saving unsupported data_.

## Steps to Reproduce

1. Sign as a producer. 
2. Go to products > products page.
3. Edit one product of the list expanding the details on product page.
4. Change Unit column from any unit to item.
5. Leave empty the box below (type of item).
6. Save the changes you edited.

## Context

Editing some product details from diferent products from the same producer (like "display as", "value", or "price").

## Severity

bug-s4

## Your Environment

* Version used: v1.24.0 
* Browser name and version: Firefox 63.0.3
* Operating System and version (desktop or mobile): Windows 7

**Comment by luisramos0** [comment]
this is an easy one, I'll take it as a break from SCA work :-D
