### ISSUE TITLE
[Spree Upgrade][FrontOffice] Fix Upgrade build - FrontOffice

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3123]
Issues in the frontoffice that break the spree upgrade build.

**Comment by sigmundpetersen** [comment]
All epic issues closed. Can we close the epic then? 🎉 @luisramos0 @sauloperez

**Comment by luisramos0** [comment]
ehehe, nice, yes.

There's just the weight calculation fix missing (#3072) that doesnt have an issue right now, but we can close the epic!!! :tada:
