### ISSUE TITLE
Order cycle pages are not always displayed with JSON data injected

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#314]
@RohanM any idea why this might be?

**Comment by RohanM** [comment]
I have a bunch of clarifying questions:

- By order cycle pages, do you mean the admin new/edit order cycle page?
- Could you attach a screenshot?
- Are there any javascript errors when this happens?
- Or are there any network issues, ie. scripts failing to load?

**Comment by lin-d-hop** [comment]
Closing, can reopen if continues to be an issue.
