### ISSUE TITLE
Report OC customer totals leading to an error 502

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3148]
## Description
One of our hubs is trying to download its data in order to prepare its orders. Once the user hits search, the page loads until it shows the snail.
The manager trying to do that is managing 15 hubs. So I thought that he was trying to load to much data. So I did some tests with only one shop, but the result is the same.

## Steps to Reproduce
1. With French production data, go to reports URL https://www.openfoodfrance.org/admin/reports/orders_and_fulfillment?report_type=order_cycle_customer_totals
2. Dates : From December the 3rd to December the 9th
3. Hubs : Suteau Biosol Admin
4. Order cycle : sem 49 envoi 13 du 3.12 (6 Nov _ 27 nov)
5. Report : OC customer totals
6. Download by csv : Yes

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/49143117-a17efd00-f2fa-11e8-8aab-b7c48f211f84.png)

## Context
Reported by a French user that runs 15 shops.## Severity
bug-s2: a non-critical feature is broken, no workaround
I'm putting s2 so far as I assume we can maybe manually extract the data before fixing the bug. If not, I'm afraid this is s1...

Note: if we extract data manually, the hub needs data from 2 OC which name start with sem 49 envoi 13

## Your Environment
* Version used: v1.23
* Browser name and version: Firefox v. 63
* Operating System and version (desktop or mobile): Ubuntu 18 LTS

**Comment by luisramos0** [comment]
@RachL now that the request timeout on the server has been changed and the urgency is lower. I think we should close this one as a duplicate of #1539

**Comment by RachL** [comment]
@luisramos0 yes you are right, and yes thanks @sigmundpetersen you are like a OFN repo librarian to me :)

![](https://media.giphy.com/media/xjxmO85AEXRHPLiDW3/giphy.gif)

**Comment by sigmundpetersen** [comment]
I've always dreamt of being one 📚

**Comment by luisramos0** [comment]
the fix to this problem: https://github.com/openfoodfoundation/ofn-install/pull/290
