### ISSUE TITLE
Customers notes are truncating across different orders

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#3149]
## Description

Customers placing notes with their orders seem to sporadically been appearing in other customers orders. 

## Expected Behavior

Notes made by a customer should only show on their own orders

## Actual Behavior

There have been two peculairties here which we are tryig to pin down

1. Oliver who uses firefox and safari on a mac, see customers notes replicated on the incorrect orders.
I however on windows, chrome and firefox see the comments matching up to the correct orders. 

2. When you change the page, order notes from the first page are showing up on the second page - as seen in the video. This affects all users regardless of their browser/OS

If it's better to split these I can do so, but as we get different results as we replicate the issues I've gone for putting our observations down.

## Steps to Reproduce

Difference in views
Orders R136242427 and R074566242

Page truncation
1. Go to orders and filter by stroudco
2. Look at the order notes for R383184313  on page 1, it states they are away
3. Look at the order notes for the second customer on page 2 R864052464 - it copies the one outlined above

http://recordit.co/nzMXru6bEr

## Animated Gif/Screenshot

First issue where we see different things:

What oliver sees -  firefox, safari, mac
![r136242427 order - olivers](https://user-images.githubusercontent.com/28807449/49151803-e316a480-f308-11e8-95c1-5ed3df260c8d.PNG)
![r074566242 - orders - olivers](https://user-images.githubusercontent.com/28807449/49151804-e316a480-f308-11e8-8242-1f4a10ddc58f.PNG)

What I see - chrome, firefox, windows
![r074566242 - orders](https://user-images.githubusercontent.com/28807449/49151692-93d07400-f308-11e8-981e-4201c442206d.PNG)
![r136242427 order](https://user-images.githubusercontent.com/28807449/49151696-959a3780-f308-11e8-8f00-c71b2b5239b6.PNG)

Second issue where there is a truncation
http://recordit.co/nzMXru6bEr

## Context

Difficult to know which information is correct on first glance and this could result in orders being dealt with incorrectly.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by myriamboure** [comment]
@sineadfenton don't hesitate to place the S3 bugs you open in the pipeline "bug backlog" and try to judge where they are in order of priority. We are trying a distributed way of prioritizing bugs... the curation team will use that backlog to push in the dev pipeline the most prioritary ones :-)

**Comment by lbwright22** [comment]
I have just tested this on UK demo hub by adding a really really long note to the order.
The note appeared on the correct order only and didn't straddle over to the previous order.
Hence i am closing the card as this does not appear to be an issue with V2 software.

**Comment by lbwright22** [comment]
Re-opening the issue as I didn't do sufficient testing - apologies.

Still occurring:
A) note against order R136242427 is replicated against order R074566242 (there should be a different note against the second order than the first)
More than one instance of this observed today for StroudCo orders Nov 2018. Relates to to 'Actual Behaviour' (2) in original description (when changing page the content of the notes transfer across if the customer on the next page also has a note against their order)

B) tested with a different food hub (OFN demo UK hub). 
a) Made 15 orders and added notes 'note 1' to 'note 15'.
b) Order one (with note 'note 1') is on page 2 (top of the table) and order 15 (with note 'note 15') is on page 1 (top of entry of the table) when viewing orders.
c) Note against order 1 displays as 'Note 15'. ie incorrect
d) note on email sent to customer (myself) is correct.

Hence issue is not resolved.
