### ISSUE TITLE
Remove unused `payment_enterprise` from order cycle exchanges

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3155]
## Description

Products are sold through order cycles. Order cycles have incoming and outgoing exchanges. Incoming exchanges define which products are coming into the order cycle to be sold. There is one incoming exchange for each supplier. Outgoing exchanges define which distributors are selling which products from this order cycle.

![img_0735](https://user-images.githubusercontent.com/3524483/49199471-17af5c80-f3ec-11e8-8ee2-e787d4b51a31.JPG)

The ActiveRecord model `Exchange` has an association to enterprises called `payment_enterprise`. The database column is called `payment_enterprise_id`. I can't find any use of this property in the code base and think that we can get rid of it.

## Expected Behavior

The application contains only necessary code.

## Actual Behavior

The application contains more code than necessary which confuses people and generates more work when changing code.

## Steps to Reproduce

1. Find all references: `git grep payment_enterprise`

## Context

I'm working on #2072, creating seed data for testing. The unused code made it more difficult for me to understand it. Completing my task takes a bit more time.

## Severity

tech-debt

## Possible Fix

- Remove all references from the code (except old migrations).
- Create a migration to remove the column.

## First time contributors

You are very welcome to work on this issue. Please have a look at our contribution guide. The wiki page about migrations can also help you with this task.

- https://github.com/openfoodfoundation/openfoodnetwork/blob/master/CONTRIBUTING.md
- https://github.com/openfoodfoundation/openfoodnetwork/wiki/Database-migrations

**Comment by amers185** [comment]
If somebody has not worked on this issue. I would like to work on it. I am a novice so if you could give me some directions, I would appreciate it.

**Comment by mkllnk** [comment]
Welcome @amers185. We would appreciate your work very much.

The first step is setting up your dev environment: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/GETTING_STARTED.md
You can then play with the app and work on this issue. Please have a look at https://github.com/openfoodfoundation/openfoodnetwork/blob/master/CONTRIBUTING.md for commit and pull request guidelines.

**Comment by mkllnk** [comment]
For this issue you will need to change the database. If you are new to Ruby on Rails, the database migration guide will tell you everything about it: https://guides.rubyonrails.org/active_record_migrations.html

**Comment by amers185** [comment]
@mkllnk I wanted to confirm if nobody is working on this issue?

**Comment by mkllnk** [comment]
That's right. Nobody is working on this at the moment. Go ahead. :-)

**Comment by amers185** [comment]
On a high-level, the solution to this problem is tantamount to removing an attribute in our db model and reloading the data? Would that be a correct assessment? Would something like this: https://stackoverflow.com/questions/8391750/delete-attribute-form-model-in-ruby-on-rails do the trick? @mkllnk thank you for your help.

**Comment by sauloperez** [comment]
yes, that it's it @amers185. That will remove the column from the database table when the migration is executed (we do it automatically at deploy time).

**Comment by sauloperez** [comment]
@amers185 beware! @m-budryte and @hughbric solved it already.
