### ISSUE TITLE
Wording in Reports Section

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#3159]
When accessing all reports, OFN users must click the blue button 'Search'.  In some cases this is appropriate as you can select subsets of data to look at.
For other instances (such as when downloading 'addresses') 'Go' or 'Download' would be more appropriate.
Currently the same string is used in each location in the reports section of the user dashboard and in other locations.

To download or view addresses in the reports section of the user dashboard, the user must select the blue button labeled 'SEARCH'.  This is counter-intuitive as there is no 'searchable' data in this section of the reports.  'GO' or 'Download' would be more appropriate.
The same is true for reports in the 'Products and Inventory' section.

The string 'Search' is used in multiple locations in the code and so can not be isolated. This was identified by a member of the #dev team @luisramos0 

but that string is in en.yml as “search” without context here https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/en.yml#L2080 (edited)
it’s used in quite a few places… not just reports.
like orders and users search

## Expected Behavior

The string next to search boxes in the orders and users section should be independent of that used in the reports section.  That would enable one to be 'Search' and the other to be 'Go' or 'Download'.

OFN users wishing to download or look at their customers' addresses would be able to do so then by selecting the blue button labeled 'Go' (the string at the bottom of the page can be translated to 'Select filters and click on GO to download your data')

## Actual Behavior

The blue button in the 'Customers' and 'Products & Inventory' sections of reports states 'SEARCH'.

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![screenshot1](https://user-images.githubusercontent.com/45104035/49304114-506e3500-f4c3-11e8-8832-5cb51b808665.png)

## Context

Issue raised by OFN user in UK.

## Severity

bug-s4

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Labelling of Reports](https://trello.com/c/JMbRV1kL/58-labelling-of-reports)
