### ISSUE TITLE
update inventory upload template

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3160]
## Description
Some fields are still missing in the inventory  upload template (product  import feature)
- variant_unit_name (to be confirmed)
- sku
- on_demand

@Matt-Yorkley can you confirm variant_unit_name I have some doubts about the first one, is variant_unit_name needed if I want to update a price or stock for a product that is set up as "item" ? Or is it enough to have the unit type in the inventory template to identify the product ? I wrote in the comment in the template issue that I thought it was needed but you didn't answer.

## Expected Behavior
User can download accurate info to prepare inventory import.

## Actual Behavior
They can't.

## Steps to Reproduce
Go to https://www.openfoodfrance.org/admin/product_import an download inventory upload template, you will see those fields are not it, but you can update sku and on_demand, so they should be in the template.

## Severity
S3

## Context
Spotted by Sally https://github.com/openfoodfoundation/openfoodnetwork/issues/3116

**Comment by Matt-Yorkley** [comment]
`variant_unit_name` shouldn't be relevant. I've included these template changes in PR #3233
