### ISSUE TITLE
"back" and "continue" buttons untranslated at image step of registration modal (front end)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3161]
![capture du 2018-12-02 00-09-02](https://user-images.githubusercontent.com/8135376/49333844-96f88800-f5c6-11e8-8c90-c14b2667d5ab.png)

**Comment by RachL** [comment]
@myriamboure "continue" as well isn't it ?

**Comment by myriamboure** [comment]
True @RachL I updated the title ;)
