### ISSUE TITLE
Limit the available order cycles to select from for tagged shoppers

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#3170]
## Description

An order cycle has been tagged for specific customers for a shopfront that uses registered only access.
Most shoppers will only have one order cycle that they can choose from, however these shoppers still have to click the order cycle selection box and choose the only available order cycle.

## Expected Behavior

Users should only see the available cycles

## Actual Behavior

Users see an initial empty box and have to click down to the select the one available option

## Steps to Reproduce

1. Create an order cycle
2. Tag customer and then tag the order cycle so only one should be visible
3. Go to the shop front

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/28807449/49448071-f8d80e00-f7cf-11e8-840f-cf791e81bb30.png)

## Context

Users may think that there is no order cycle available for them - a particular issue for new users

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by pacodelaluna** [comment]
My guess is that we should avoid blank values in this select box. Investigating.

**Comment by pacodelaluna** [comment]
Ok, it is more complex than this, elements are hidden inside the select, need to dig this up.

**Comment by kirstenalarsen** [comment]
We have just had this raised by a user. I think the correct behaviour would be that if there is only one Order Cycle available to that user it should be selected by default. This is how it works when there is only one order cycle at all, and as far as this Customer is concerned there IS only one, so they shouldn't have to choose.

**Comment by kirstenalarsen** [comment]
It might be worth considering this alongside the changes to this element that are part of the mobile re-design - worth implementing together or after? see item #2 https://community.openfoodnetwork.org/t/mobile-shopping-ux-improvements-an-overview/1859  ping @daniellemoorhead @mkllnk @Matt-Yorkley

**Comment by luisramos0** [comment]
A variation on this problem is that if the customer is not tagged and goes to the shop, the message is correct but the OC selector appears and the select box is empty...
![image](https://user-images.githubusercontent.com/1640378/74945287-63826300-53ef-11ea-8804-1fbb73f0904e.png)

**Comment by luisramos0** [comment]
you need to understand tagging of customers and ocs to replicate this issue :-)
this is the tag rules I have to get this working:
![image](https://user-images.githubusercontent.com/1640378/74947817-55cedc80-53f3-11ea-8ea9-47e1281bf74d.png)
additionally, I have an OC tagged no_u and an OC tagged xpto as well as a customer tagged xpto

**Comment by luisramos0** [comment]
ah, took me over an hour of debugging to find this little bug!!!

The list of OCs to display is defined in [BaseController#set_order_cycles](https://github.com/openfoodfoundation/openfoodnetwork/blob/93fda02e43e581200794005109aed6d32d6f24da/app/controllers/base_controller.rb#L26), here tag rules are applied so the list of OCs is always correct BUT, when loading the shop page, the logic to reset the order cycle in [EnterprisesControlles#reset_order_cycle](https://github.com/openfoodfoundation/openfoodnetwork/blob/93fda02e43e581200794005109aed6d32d6f24da/app/controllers/enterprises_controller.rb#L93) is not applying tag rules and SO it is seeing multiple OCs when in fact (after tag rules) there is only one SO, it is not selecting the one OC that passes tag rules application.
SO, we need to add tag rules applicator to this EnterprisesController, hopefully reusing code from what's in BaseController.

**Comment by daniellemoorhead** [comment]
...and therefore not a bug to be solved with the mobile shopping work because if the single OC displayed then it wouldn't be a problem with the existing way the OC selector works. Correct @luisramos0?

**Comment by daniellemoorhead** [comment]
PS. Awesome detective work finding the problem!

![](https://media.giphy.com/media/NS7gPxeumewkWDOIxi/giphy.gif)

**Comment by luisramos0** [comment]
correct, not related to the mobile ux work.
