### ISSUE TITLE
[Spree Upgrade] Verify all points where scope_to_variant is used

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3172]
There are quite a few places where variants are scoped to become variant_overrides.
Now that the basic adaptation of VariantOverrides to spree 2 (#2559 and then #3232) is done, we need to verify each of these uses and make sure they are working as expected.
We must validate that scoping is working properly not just for count_on_hand and on_demand but also price, default_stock, resettable, sku and lastly, permissions.

I think this can be done later in the upgrade as it's not breaking any tests.

This is the list of references:

```ruby
- 1
/Users/luisramos/dev/ofn/openfoodnetwork/app/controllers/spree/admin/line_items_controller_decorator.rb:
    7    def create
    8      variant = Spree::Variant.find(params[:line_item][:variant_id])
    9:     OpenFoodNetwork::ScopeVariantToHub.new(@order.distributor).scope(variant)
   10  
   11      @line_item = @order.add_variant(variant, params[:line_item][:quantity].to_i)

- 2
/Users/luisramos/dev/ofn/openfoodnetwork/app/models/order_cycle.rb:
  259      # The Spree::Order.complete scope only checks for completed_at date, does not ensure state is "complete"
  260      orders = Spree::Order.complete.where(state: "complete", user_id: user, distributor_id: distributor, order_cycle_id: self)
  261:     scoper = OpenFoodNetwork::ScopeVariantToHub.new(distributor)
  262      items = Spree::LineItem.joins(:order).merge(orders)
  263      items.each { |li| scoper.scope(li.variant) }

- 3
/Users/luisramos/dev/ofn/openfoodnetwork/app/models/spree/line_item_decorator.rb:
  137    def scoper
  138  	  return @scoper unless @scoper.nil?
  139: 	  @scoper = OpenFoodNetwork::ScopeVariantToHub.new(order.distributor)
  140    end
  141  

- 4
/Users/luisramos/dev/ofn/openfoodnetwork/app/services/cart_service.rb:
   41      max_quantity = max_quantity.to_i if max_quantity
   42      variant = Spree::Variant.find(variant_id)
   43:     OpenFoodNetwork::ScopeVariantToHub.new(@distributor).scope(variant)
   44  
   45      return unless quantity > 0 && valid_variant?(variant)

- 5
/Users/luisramos/dev/ofn/openfoodnetwork/lib/open_food_network/products_renderer.rb:
   59        # look up the stock as overridden by VariantOverrides, and the scope method is not affected
   60        # by them.
   61:       scoper = OpenFoodNetwork::ScopeVariantToHub.new(@distributor)
   62        Spree::Variant.
   63          for_distribution(@order_cycle, @distributor).

- 6
/Users/luisramos/dev/ofn/openfoodnetwork/lib/open_food_network/scope_product_to_hub.rb:
   17      module ScopeProductToHub
   18        def variants_distributed_by(order_cycle, distributor)
   19:         super.each { |v| ScopeVariantToHub.new(@hub, @variant_overrides).scope(v) }
   20        end
   21      end

- 7
/Users/luisramos/dev/ofn/openfoodnetwork/lib/open_food_network/scope_variants_for_search.rb:
   45        distributor = Enterprise.find params[:distributor_id]
   46        @variants = @variants.in_distributor(distributor)
   47:       scoper = OpenFoodNetwork::ScopeVariantToHub.new(distributor)
   48        # Perform scoping after all filtering is done.
   49        # Filtering could be a problem on scoped variants.

- 8
/Users/luisramos/dev/ofn/openfoodnetwork/lib/spree/core/controller_helpers/order_decorator.rb:
    6  
    7      if order
    8:       scoper = OpenFoodNetwork::ScopeVariantToHub.new(order.distributor)
    9        order.line_items.each do |li|
   10          scoper.scope(li.variant)
```

**Comment by sauloperez** [comment]
Should we create an issue to cover them with unit tests?

**Comment by luisramos0** [comment]
Yeah, I would. IMO even my last PR adapting variant overrides should have had more tests as well but without zeus it's so painful... I am stuck because I really need zeus and I have tried many different things already without success...
is there a valid alternative to zeus?

**Comment by luisramos0** [comment]
HURRAY!!!! I did try to use spring at some point but couldnt make it work, now I gave it a more serious try and it's working!!!!
because we are on rails 3.2 we need to use spring 1.1.3 with spring-commands-rspec

~/dev/ofn/openfoodnetwork (2-0-stable) $ time bin/rspec spec/models/order_cycle_spec.rb:154
**real	0m20.779s**

~/dev/ofn/openfoodnetwork (2-0-stable) $ time bin/rspec spec/models/order_cycle_spec.rb:154
**real	0m3.672s**

thanks a lot for the pointer @sauloperez

**Comment by luisramos0** [comment]
Each of the points above will have to be validated:

- [X] 1. app/controllers/spree/admin/line_items_controller_decorator.rb:
This controller has been deleted because it is no longer used. It's replacement Spree::Api::ShipmentsController has been tested and verified already.

- [ ] 2. app/models/order_cycle.rb:
     - only used in items_bought_by_user 

- [ ] 3. app/models/spree/line_item_decorator.rb:
   - scoping when doing cap_quantity_at_stock, sufficient_stock? and update_inventory_with_scoping

- [X] 4. app/services/cart_service.rb:
This has been verified, scoping happens just before attempt_cart_add.

- [ ] 5. lib/open_food_network/products_renderer.rb:
Scoping happens in load_products and in all_variants_for_shop

- [ ] 6. lib/open_food_network/scope_product_to_hub.rb:
This needs to be reviewed.

- [ ] 7. lib/open_food_network/scope_variants_for_search.rb:
This needs to be reviewed.

- [ ] 8. lib/spree/core/controller_helpers/order_decorator.rb:
We should have tests covering this one. Needs to be verified.

**Comment by luisramos0** [comment]
As part of this review I have also reviewed other VO fields: price, sku, stock reset bulk action in inventory page (resettable and default_stock fields), inventory_items.visible (adding and hiding items from inventory) and also clearing up override data with the checkbox of the column “inherits?”.
It all seems to be working fine and covered with tests.

**Comment by mkllnk** [comment]
Great work Luis! It looks very thorough and I can't think of any other case that needs to be covered. User testing will reveal if we found everything.
