### ISSUE TITLE
Integrate Bugsnag's JS library

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3184]
## Description

While we do have Bugsnag to track errors on the backend, we don't have any visibility over the errors that happen on the client side.

We should integrate the Bugsnag's JS library to achieve it. They even have an [Angular integration guide](https://docs.bugsnag.com/platforms/javascript/angular/). But don't get too excited; chances are that our version is far too old compared to that guide and things might not work.

**Comment by mkllnk** [comment]
We use the JS integration in the Fair Food project. This simple snippet in the layout does the trick:
```erb
<% if Rails.env.staging? || Rails.env.production? %>
  <script
    src="//d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js"
    data-apikey="4b....aaad">
  </script>
<% end %>
```

**Comment by acmh** [comment]
Hi @mkllnk, can I make a PR for this issue?

**Comment by mkllnk** [comment]
Sure. The API key is probably best configured in `application.yml`.
