### ISSUE TITLE
Localise text in Registration process

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#319]
e.g. 
- are you ok with the way suburb / state / postcode work in ofn.org.uk/register
- email confirmation email has hello@openfoodnetwork.org as contact email with any problems, probably should be dev.ofnuk or wherever you're going to handle customer service from

**Comment by Em-AK** [comment]
Is anyone working on this ?
We are dealing with localisation during the EU hackweek, we can also deal with this issue.

**Comment by lin-d-hop** [comment]
Closing as the registration process all looks good and international now
