### ISSUE TITLE
ActiveRecord::StatementInvalid in admin/order_cycles#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3192]
## Description

Entering pick up instructions that exceed 255 characters leads to a server error.

**ActiveRecord::StatementInvalid** in **admin/order_cycles#update**
PG::StringDataRightTruncation: ERROR:  value too long for type character varying(255)
: UPDATE "exchanges" SET "pickup_instructions" = 'Pick up options are:                                                                                                                                                                  - Theatre Royal courtyard (#30 Hargraves St) in Castlemaine between 5pm and 6pm on a Wednesday                  - Drop into the Harcourt Organic Farming Co-op shop (phew mouthful!) in Harcourt Weds or Friday 10am-4pm.', "updated_at" = '2018-12-07 00:23:13.552177' WHERE "exchanges"."id" = 66943

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5c09bd711a398a001e24458e?event_id=5c09bd710031f6a7ff2a0000&i=gh&m=ci)

    gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5c09bd711a398a001e24458e?event_id=5c09bd710031f6a7ff2a0000&i=gh&m=ci)

## Expected Behavior

It should not be possible to enter instructions that exceed the character limit of the database. Updating the order cycle should always succeed.

## Actual Behavior

A server error is possible.

## Steps to Reproduce

1. Edit an order cycle.
2. Change the pick up instructions to a long text.
3. Try to save the changes.

## Animated Gif/Screenshot

Not recorded yet.

## Context

One of our Australian users experienced this and it got reported through Bugsnag.

## Severity

S4 It's annoying when saving fails, but most people can figure out to use a shorter description.

## Your Environment

* Version used: 1052d982550f0b7ac601b399f032291383ddad26

## Possible Fix

Limit the text field to the limit of the database field. Maybe evaluate if the limit of the database field should be increased. How would it look like with longer instructions?

**Comment by sauloperez** [comment]
![](https://media.giphy.com/media/14aUO0Mf7dWDXW/giphy.gif)

**Comment by daniellemoorhead** [comment]
Sad...but LOL @sauloperez

**Comment by jgman** [comment]
I would like to work on this as my first issue.

**Comment by sigmundpetersen** [comment]
Yes @jgman please go ahead! 🙂 Welcome, and please ask if you need any assistance 👍

**Comment by sauloperez** [comment]
Hi @jgman ! Also, don't hesitate to ask on the dev channel of [our Slack team](https://openfoodnetwork.org/slack-invite).
