### ISSUE TITLE
Seeding process: Stop asking for input!

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#3202]
## Description
During the process of seeding the database, I'm asked for an email address and password for the admin user.

## Expected Behavior
When I seed the database in an app, I expect the script to proceed without my input.

## Actual Behavior
Although there is a default email address and password, the script can't go on until I confirm them.  I HATE babysitting processes.  I just want to finish these basic tasks and move on.

## Severity
bug-s4: it's annoying, but you can use it

## Possible Fix
Just change the script to use the default admin email address and password WITHOUT demanding input.

**Comment by sauloperez** [comment]
I know it can be improved but have you tried using the [yes](https://en.m.wikipedia.org/wiki/Yes_(Unix)) command?

**Comment by mkllnk** [comment]
This behaviour came from spree_auth_devise and the solution was to set an environment variable:

```sh
export AUTO_ACCEPT="true"
#export ADMIN_EMAIL="spree@example.com"
#export ADMIN_PASSWORD="spree123"
```

Anyway, we removed spree_auth_devise in https://github.com/openfoodfoundation/openfoodnetwork/pull/3700. We are not creating a user anymore and this is not happening. I will close this issue.
