### ISSUE TITLE
Broken stock levels on product list page when product added and removed quickly from basket

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3222]
## Description
I am pretty sure there is a bug in this commit/line:
https://github.com/openfoodfoundation/openfoodnetwork/commit/a26266159cefcdc55c2e1bff7d5498a9d88c069d#diff-0e4d2deb3b86720d428f95f51c0c19dfR65
This is calculating stock_levels (on_hand) for variants that are listed in the request but are not present in the order (prior to this code is executed, the method li_stock_levels fetches stock levels for variants present in the order). The problem is that variants coming from the order are scoped in the cart service (are transformed into overrides) but this Spree::Variant.find call does not scope variants, so the on_hand value sent is the variants one when it should be the override on_hand value if a override exists.

I am not too sure about this logic but looking at the commit this code was added to fix a problem with multiple requests where frontend code requests stocklevels for a specific list of variants but when the server executes, the variants are not in the order any more (probably due to another request removing them). We should keep the logic but fix the bug.

## Expected Behavior
In some cases on the product list when adding and removing quantities, stock levels reported will be the variants values even if buying from a hub with inventory.

## Actual Behavior
Inventory (variant overrides) stock levels are reported instead.

## Steps to Reproduce
I didn't replicate this and probably better just to get this covered in specs. I believe manual verification will be difficult.

## Context
Detected while fixing Spree Upgrade build.

## Severity
bug-s5: we can live with it, only a few users impacted

## Possible Fix
So, a few things need to be done here:
1. create spec to validate the bug exists
2. fix the bug by scoping the variant before calling on_hand
3. refactor code! the method names at least need to be improved (the current best way to understand what's going on is to read the tests [here](https://github.com/openfoodfoundation/openfoodnetwork/commit/a26266159cefcdc55c2e1bff7d5498a9d88c069d#diff-cc6b7d88d7ef9e9a51819e616293808fR98))

The fix to the bug will be something like this:
```
      variant = Spree::Variant.find(variant_id)
      cartService.scoper.scope(variant)
      stock_levels[variant_id] = { quantity: 0, max_quantity: 0, on_hand: variant.on_hand }
```

I found this issue because this is where #3118 is breaking in the v2 branch. This is only seen in v2 variant overrides specs because order.add_variant is not working for the spec in #3118. To be investigated as part of #3118

**Comment by luisramos0** [comment]
I am closing this issue as I cant replicate it.
there are 3 possibilities:
- This is dead code that is never reached (so there would be no bug, just broken dead code)
- could be some concurrency case that reaches this code. that would mean we have a bug.
- I am missing something

**Comment by luisramos0** [comment]
I am reopening this issue because we got a bugsnag alert from the VariantsStockLevels one in #3230 
So we have the proof this is not dead code: https://github.com/openfoodfoundation/openfoodnetwork/blob/75abd4586e4d346ac91f580e7a8a6cd221572f66/app/services/variants_stock_levels.rb#L12

So, the code above is not dead and it contains a bug.
There are two things we need to do here:
- remove the bugsnag alert from VariantsStockLevels
- make it Scope variants before returning stock levels so that the bug is fixed

**Comment by luisramos0** [comment]
it's still an s5 as we have only seen one bugsnag alert for it.

**Comment by luisramos0** [comment]
this alert as come up a few times now, moving to s4

**Comment by luisramos0** [comment]
revisiting this bug...
This is still up to date and we do get these bugsnag alerts once in a while.

The task is to add scoping here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/services/variants_stock_levels.rb#L13
and remove the bugnag notification.

**Comment by RachL** [comment]
I'm upgrading this one to s3, it might be linked to quite a few problems cart problems in France such as https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1583920428008700

**Comment by luisramos0** [comment]
I guess you forgot to update the label. :-)

**Comment by luisramos0** [comment]
yeah, I think this should be prioritized. It's something specific we can do to improve the situation in a very important area of the app where there are issues being experienced by users.

**Comment by RachL** [comment]
@luisramos0 thanks for the label! That's what happening when you get a phone call just after commenting....
