### ISSUE TITLE
Duplicated header when forgetting to select hubs in Payment config

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3225]
## Description
As a super admin, when you add a new payment method, if you forget to select the hub, the error is displayed in a page where there contents of the main page are added in the middle.

## Expected Behavior
We should have the same page as before when clicking on "create", but with the error message. No added content.

## Actual Behavior
![image](https://user-images.githubusercontent.com/6525576/50147014-6480a780-02b5-11e9-851c-19d449dc28bc.png)

## Steps to Reproduce
1. Log in as super admin
2. Go to Admin > Configurations > Payment Method
3. Click on "add a new payment method"
4. Fill in everything except the hub in the right menu
5. Click on Create

## Context
Found while testing #3156

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: v1.23.1
* Browser name and version: Firefox 64
* Operating System and version (desktop or mobile): Windows 10

**Comment by sauloperez** [comment]
Does this happen for regular admins too? I guess so...

**Comment by sigmundpetersen** [comment]
Yes I just replicated with Enterprise Admin

**Comment by sigmundpetersen** [comment]
Related to #1215 ? Duplicate?

**Comment by RachL** [comment]
I didn't saw your comment back then @sigmundpetersen sorry. You are right. I'm closing this, and will but a link in 1215 if we need something from here.
