### ISSUE TITLE
Assess and maybe replace blockenspiel gem

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3231]
## Description

Our dependencies need to be kept up to date. Since that is work, we only want to keep dependencies that save lots of work in other ways. A discussion in https://github.com/openfoodfoundation/openfoodnetwork/pull/3211 opened the question if we need the gem blockenspiel. We need to assess its use and decide if we want to keep it.

## Severity

Low tech debt.

## Possible Fix

Two possible options:

- Replace the current logic using blockenspiel and remove the gem.
- Write a guide how to use blockenspiel efficiently in our code base.

**Comment by luisramos0** [comment]
nice issue title 😂
