### ISSUE TITLE
[Spree Upgrade] Verify all points where scope_to_variant is used (non-core features)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3237]
After verifying scoping for core features in #3172, we need to do the same for non-core features.

This is the list of references:

```ruby
- 1
/Users/luisramos/dev/ofn/openfoodnetwork/app/services/order_factory.rb:
   77  
   78    def scoper
   79:     @scoper ||= OpenFoodNetwork::ScopeVariantToHub.new(shop)
   80    end
   81  end

- 2
/Users/luisramos/dev/ofn/openfoodnetwork/app/services/subscription_estimator.rb:
   43  
   44    def scoper
   45:     OpenFoodNetwork::ScopeVariantToHub.new(shop)
   46    end
   47  

- 3
/Users/luisramos/dev/ofn/openfoodnetwork/lib/open_food_network/products_and_inventory_report_base.rb:
   60        if params[:distributor_id].to_i > 0
   61          distributor = Enterprise.find params[:distributor_id]
   62:         scoper = OpenFoodNetwork::ScopeVariantToHub.new(distributor)
   63          variants.in_distributor(distributor).each { |v| scoper.scope(v) }
   64        else
```

**Comment by mkllnk** [comment]
- [x] `app/services/order_factory.rb`: The code looks good and is tested in `spec/services/order_factory_spec.rb:117` with a price override.
- [x] `app/services/subscription_estimator.rb`:The code looks good and is tested in `spec/services/subscription_estimator_spec.rb:57` with a price override.
- [x] `lib/open_food_network/products_and_inventory_report_base.rb`: The report only scopes variants when a distributor is selected. I covered this case in #3654. It may be unexpected for single-enterprise users but I haven't seen any feature request for this. Changing it is out of scope. :stuck_out_tongue_winking_eye:

**Comment by luisramos0** [comment]
awesome @mkllnk

**Comment by luisramos0** [comment]
I am not sure why zenhub didnt move this to code review automatically with the connect PR...
