### ISSUE TITLE
Shopfront top to include banner image for more prominent branding

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#324]
![image](https://cloud.githubusercontent.com/assets/2911176/5832374/5e596716-a198-11e4-957e-462dd059010f.png)

**Comment by myriamboure** [comment]
Listed in shopping UX icebox https://community.openfoodnetwork.org/t/customer-easily-go-through-the-whole-placing-order-process/1245 #gitcull2018
