### ISSUE TITLE
Rename rake tasks namespace to ofn

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3248]
## Description

As agreed in https://community.openfoodnetwork.org/t/rake-task-naming/1531, we want to rename OFN's rake tasks namespace to `ofn` instead of the long `openfoodnetwork`.

**Comment by Jefferson-Faseler** [comment]
I would like to tackle this quick win if I can. I'm new to ZenHub and could not figure out how to assign this to myself. Possibly because I only have read permissions?

**Comment by sigmundpetersen** [comment]
Hey @Jefferson-Faseler and welcome! Would be awsome if you would like to try fixing this issue. Yes you are right, it's not possible to assign because of permissions. But just go ahead and submit your PR and we will connect it to this issue.
