### ISSUE TITLE
Display_name not available on the variants create/edit page

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3249]
## Description
As a farmer
When I create a variant for my product
I need to set the display name of the variant as it will be shown on the shopfront
Currently I can only do that on the bulk product edit page

This is very confusing for the user who is creating variants using the variants tab...

Additionally, and to add to the user confusion, the unit display_as value is also only available on the bulk product edit page.

## Expected Behavior
I can set the variant's display_name and unit's display_as fields of a variant when I edit a variant.

## Actual Behavior
These fields are missing from the page (see third screenshot):
<img width="880" alt="screenshot 2018-12-27 at 14 59 34" src="https://user-images.githubusercontent.com/1640378/50484978-2b4de300-09eb-11e9-86f2-2fee4d91c2cf.png">

<img width="893" alt="screenshot 2018-12-27 at 14 59 49" src="https://user-images.githubusercontent.com/1640378/50484682-ba59fb80-09e9-11e9-97d2-1dfd93ae4071.png">

<img width="879" alt="screenshot 2018-12-27 at 14 59 58" src="https://user-images.githubusercontent.com/1640378/50484676-b0d09380-09e9-11e9-9118-1a0505fdca92.png">

## Steps to Reproduce
Go to bulk product edit page and click on the edit button of any variant

## Context
I found this in a user demo in Portugal and then I realised it can be easily fixed as part of the spree upgrade.

## Severity
I'd say bug-s3, it's totally broken UX on a very basic feature: I believe every single user will see this.

## Possible Fix
The missing fields are OFN specific fields. We need to de-deface the view and add these fields to it.
This is discussed in this thread: https://community.openfoodnetwork.org/t/product-option-types-vs-product-variant-unit-fields/1535/3
This is related to spree upgrade issue: #3091 and I believe we should fix this one together with it.

**Comment by myriamboure** [comment]
I see you put that bug in dev ready @luisramos0 but we have a priorization process for bugs. IMO it should stay in "all the things" as for the moment we prioritize s3 bugs in the bug backlog. We don't have much space to make s3 bugs through the pipe though... but in any case we shouldn't put bugs randomly in dev ready. Do you agree ? If yes I let you put it pack to all the things for now, or at the end of the  bug backlog as it's s4. If you think it deserve s3 (its confusing in your description) we need to order compared to other s3 bugs.

**Comment by luisramos0** [comment]
I am sorry, I got really confused with the priority of this one because I dont have enough context about all the S3 things.
So, I leave my opinion and I will let you correct it, ok? I think this is S3. It's ridiculously bad UX on a core feature like creating variants :-(
We can still keep it on "All the things" for prioritization compared to other s3s, right?

**Comment by myriamboure** [comment]
Yes, let's do that, I'll add it to the bug backlog but not at the top of the list ;-) No worries of course I have lots of doubts all the time, still learning and building on the fly !
