### ISSUE TITLE
Allow enterprises to show/hide contact information (visibility control)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#326]
Control which contact info appears where / address privacy e.g. 
- display options for contact name; phone number; address; email 
- Enterprises can set 'non-contactable' option e.g. only via Food Hubs
- respect in Contact tab and Modals
- option to exclude from or blur on map
- check order conf email

Maybe wait until front E2E and member structure in place, so don't have to redo

**Comment by myriamboure** [comment]
Closing, you don't have to put any email and phone number to display on shopfront, so privacy model seems ok
#gitcull2018
