### ISSUE TITLE
[Enterprise Fee Summary] Rows using order-based calculators not providing OC exchange data

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#3283]
Rows using order-based calculators are not providing OC exchange data.

## Description

@kirstenalarsen provided this sample screenshot of a report where some columns are blank where there should be a value:

![enterprise_fee_summary-blank_exchange_information](https://user-images.githubusercontent.com/2243/50725218-4a5c1b80-1135-11e9-845d-9149f2997285.png)

I finally learned that this happens when `Spree::Adjustment#source` is a `Spree::Order` instance. Currently, the report only supports adjustments where this is `Spree::LineItem`.

## Expected Behavior

Rows for exchange enterprise fees that use order-based calculators should have "Fee Calc on Transfer Through" values.

## Actual Behavior

Rows for exchange enterprise fees that use order-based calculators do not have "Fee Calc on Transfer Through" values.

## Steps to Reproduce

1. Set up an OC with different enterprises for producer, coordinator, and distributor.
2. Set up an incoming and outgoing exchange for a variant with stock.
3. Add one enterprise fee each for the producer, coordinator, and distributor to the incoming exchange and also to the outgoing exchange.
4. Create and complete an order for the variant.
5. Check the Enterprise Fee Summary. For the 6 rows marked "Incoming" / "Outgoing", "Fee Calc on Transfer Through" is blank.

## Context

This came up when testing in staging.

## Severity

bug-s2: a non-critical feature is broken, no workaround

Although this feature has not yet been launched.

## Possible Fix

Add support for calculators that would result to saving `Spree::Order` for `Spree::Adjustment#source`.

**Comment by kristinalim** [comment]
To get "Fee Calc on Transfer Through" for enterprise fees added to **OC exchanges**, in effect what we do currently is:

1. Identify the line item for which  the adjustment was created.
2. Get the variant for the line item.
3. See whether the adjustment was for an incoming or an outgoing exchange. This is cached in the adjustment metadata.
4. Knowing the variant and whether incoming/outgoing, we find the related OC exchange.
5. We get the name of the **sender** for this exchange.

Order-based calculators such as "Flat Rate (per order)" can also be used by an enterprise fee that is added to an exchange. But it turns out that order adjustments created using these calculators are no longer associated with the line item but with the order, so with the data we save, we cannot identify the variant and consequently also the exchange and the sender.

This was the reason for the blank "Fee Calc on Transfer Through" cells in the screenshot.

@kirstenalarsen For these order-based calculators added to exchanges, should "Fee Calc on Transfer Through" be "All" or should it be the sender in the exchange?

* If the former, this would be simple.
* If the latter, we would need to cache more data in adjustments. And for some existing data, there is a chance we will no longer be able to identify the correct exchange.

**Comment by kirstenalarsen** [comment]
HI @kristinalim - I don't have time to drop myself deeply into this this week but don't want to hold it up. At first glance my thought would be that it should be the 'receiver' rather than the 'sender' of the exchange - is that what you mean by 'all'? As in these fees are placed on the whole order as through the shop/hub so would need to be all items in the order which would be from multiple senders? So I think that's good news and means it's the simple option?

**Comment by kristinalim** [comment]
Hmm, that seems more useful... And yes, using the "receiver" of the exchange is simpler, @kirstenalarsen.

So then:

1. Fee added to an incoming exchange - Column is name of coordinator
2. Fee added to an outgoing exchange - Column is name of distributor
3. Fee added as "coordinator fee" not tied to an exchange but to OC - Column is name of distributor?

> At first glance my thought would be that it should be the 'receiver' rather than the 'sender' of the exchange - is that what you mean by 'all'? As in these fees are placed on the whole order as through the shop/hub so would need to be all items in the order which would be from multiple senders?

That's what's confusing me right now. This sample report in the specification includes a value of "All": https://github.com/openfoodfoundation/openfoodnetwork/issues/2616#issue-355438315 How is this column intended to be used? If 1, 2, and 3 above seem okay, then we can go with that definition of the column.

**Comment by kirstenalarsen** [comment]
1. no I don't think that's quite right - I think it should map to the incoming or outgoing in the report and also to how the fee is actually calculated 

So if the fee is on incoming it should be the Producer . . so I think the 'per order' fee in this case would be per customer for that producer.

2. YES If it is on outgoing, then it is on the whole order as everything is going through the Hub

3. Yes I think so - will be calculated on all items in the order according to the distributor of the order 

Ah ha - but the coordinator fee 'total' will be counted on all items in all orders through ALL DISTRIBUTORs in the OC - that's where the all comes from . . does that work?

**Comment by kristinalim** [comment]
@kirstenalarsen Is my proposal for Scenario 1B workable for now?

1. Fee added to an incoming exchange
    - If fee is computed against just the line item - Column is name of producer
    - If fee is computed against the entire order, so there can be multiple line items which can be under different producers - For now, can we have "Entire Orders through DISTRIBUTOR_NAME"? Because of the way we store calculations for these types of calculators, for some OC configs, there is no way to accurately tell (for existing orders) from which exchange the fee applied, so we can't accurately know the producer name. If there was a way to tell, we don't split the values per line item either, so splitting by producer is complicated and can result in $$ discrepancies.
2. Fee added to an outgoing exchange - Column is name of distributor
3. Fee added as "coordinator fee" not tied to an exchange but to OC - Column is "All"

**Comment by kristinalim** [comment]
@kirstenalarsen No need to read through my previous comment above. Here's a summary of implementation changes, which I did for now in PR #3283.

**Type 1:** For rows marked Incoming/Outgoing that have line item -based calculators:

1. "Fee Calc on Transfer Through" is producer name for incoming, and distributor name for outgoing.
2. For tax category:
    a. If the enterprise fee itself has a tax category, this is used.
    b. If the enterprise fee inherits the product's tax category, this is the tax category of the product.
    c. If the enterprise fee has no tax category, this is blank.

**Type 2:** For rows marked Incoming/Outgoing that have order-based calculators:

1. "Fee Calc on Transfer Through" is "Entire Orders through DISTRIBUTOR_NAME".
2. For tax category:
    a. If the enterprise fee itself has a tax category, this is used.
    b. If the enterprise fee inherits the product's tax category, this is "Various".
    c. If the enterprise fee has no tax category, this is blank.

**Type 3:** For rows marked "Coordinator":

1. "Fee Calc on Transfer Through" is "All".
2. For tax category (same as in Type 2).

If this is okay for v1, I'll move the PR to Code Review. Then I can work on more complicated changes for Type 2 if needed.
