### ISSUE TITLE
[Spree Upgrade] Data Migration

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3285]
As discussed here: https://community.openfoodnetwork.org/t/staging-ofn-v2/1527/5
We need to make sure:
1- the db:migrate from v1 to v2 works correctly
2- the db seed works correctly
3- all v1 data in current live instances is migrated to the v2 data model

## What to test
I install v2 on a live instance running v1 and I get the db in the correct v2 state while the data in the DB has been adapted correctly to v2. We should cover different data tests we need to run for the migration. What are the changes in the data model that we need to adapt/migrate?

**Comment by luisramos0** [comment]
@sauloperez I think you are more clear than I am about what needs to be done here. Can you help write up/clarify what exactly we need to do and test as pat of this task? Thanks!

**Comment by luisramos0** [comment]
To validate the data migrations, we need to load live data into staging, run the migrations and check the result is good.
Discussion here: https://community.openfoodnetwork.org/t/testing-ofn-v2/1545/5

We will need to check all v1 historical data is stored in an appropriate manner in the v2 data model, order adjustments, order shipping_methods, enterprise shipping methods and payment methods. What else will we need to test in terms of data?

**Comment by sauloperez** [comment]
I wouldn't harm to investigate the actual data migration Spree did on existing data, to check things are fine, like from on_hand attributes from their old to their new location, etc.

Then the actual check will be to generate data, migrate it and then use it again. If the data migrations were right we should see no errors.

**Comment by luisramos0** [comment]
I have quite a few things todo but I think this is the highest priority right now.

Tomorrow I'll take a backup for UK live and load it into uk staging. After that I plan to run the v2 migrations and look at the data. At that point we will have a staging server with live like data running in v2. I'll report back here.

**Comment by luisramos0** [comment]
I have spent quite a lot of time on this one...
- We now have a way to sanitize and truncate live data to be used for testing  #3579 
- 2 existing migrations were fixed #3591
- 2 new migrations added (picked up from future spree versions and adapted) #3602

I am currently testing locally with live data. I'll create issues as I find them.

**Comment by sauloperez** [comment]
Are we done with this epic?

**Comment by luisramos0** [comment]
there's 3591 above to be merged.

and I think @kristinalim question on #3591 is very important and we should investigate a little better:
"Do we have a system for validating a certain v1 instance will not lose any data when migrating?"

**Comment by kristinalim** [comment]
I think the plan of @RachL to compare reports in v1 and after migration to v2 is great for checking if we've lost data. We can bring one production DB to staging, anonymize the data but do not truncate it, and then we can test if generated reports in v1 and in v2 get the same number of rows and column totals. We could even compare them with `diff` because AFAIK we expect the reports to be identical.

Do you agree that this is worth doing?

Meanwhile, I've been reviewing the DB migration scripts too and will be submitting a PR with minor fixes.

**Comment by kristinalim** [comment]
I created only PR #3680, which I don't even think matters because `Spree::ShippingRate` does not have model validations nor relevant `unique` table indices.

I also noticed that `Spree::ShippingMethod#shipping_category` does not get preserved when running the v2 migrations. But there are no (undeleted) shipping methods with shipping category in `AU`, `FR`, and `UK`:

```ruby
Spree::ShippingMethod.where("shipping_category_id IS NOT NULL").count
# => 0
```

**Comment by luisramos0** [comment]
Nice, it's great that you are reviewing the migrations as well!
ah, yes, re Spree::ShippingMethod#shipping_category I have noticed that and verified that as well but forgot to mention here :-) I think we will be fine with that.

Yes, comparing reports is a good way to go. @RachL is already doing it with truncated data (it's truncated to the last 3 months). This bug was detected that way: #3677
The reports have a filter for dates so it should be fine with this data set and the system is very very slow already with truncate data... we can give it a try with the full data set later and see if the reports work.

**Comment by luisramos0** [comment]
@RachL @kristinalim I have loaded katuma live data to staging.katuma.org
I anonymized the data but did not truncate it, it would be good to compare staging data with live data now. there will be differences as we have already seen in reports for example.

**Comment by luisramos0** [comment]
I am closing this now. I dont think we need more validations of the data migration process.
