### ISSUE TITLE
[i18n] Missing string and wrong automatic translation on orders page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3288]
On /admin/orders page, the filter "first name begins with" is not in transifex and cannot be translated.
In French the translation is so wrong we are a bit ashamed... "begins", translated "commence" in French is currently written "commmance"... 

We need the string in transifex to be able to fix that.

English:
![untitled presentation](https://user-images.githubusercontent.com/8135376/50768934-8d77d500-1282-11e9-9693-82a385b4fab5.jpg)

French:
![untitled presentation 1](https://user-images.githubusercontent.com/8135376/50768941-923c8900-1282-11e9-8876-356cf1355519.jpg)

**Comment by myriamboure** [comment]
@HugsDaniel are you still our internationalization issues master, can you quickly fix this one which is pretty annoying and make us look pretty unprofessional ?

**Comment by sigmundpetersen** [comment]
Hey @myriamboure what's the added value of the [i18n] prefix? Should we just re-introduce the `i18n` label?
