### ISSUE TITLE
[i18n] translation missing "insert url"

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3292]
## Description

On entreprise settings / shop preferences

![public php](https://user-images.githubusercontent.com/8135376/50835456-0a747e80-1357-11e9-9c6b-62a7276544b2.png)

## Steps to Reproduce
1. Log in as enterprise user or superadmin
2. Go to enterprise > Settings
3. Go to shop preferences
4. Try to add an URL you will see that "insert url" is not translated

## Severity
bug-s4: it's annoying, but you can use it

**Comment by kevinchristianson** [comment]
I looked into where this string could be coming from and found it in the file vendor/assets/javascripts/textAngular.min.js as a hard-coded string along with many other hard-coded strings. I believe this is a generated file, however, so changing it there would not actually solve the issue. The string doesn't seem to appear anywhere else in the OFN project though and I didn't see it in Spree either. I know @haseleyi worked on an issue where a translation bug was coming from one of the gems OFN uses, so maybe that could be the case here as well. Any ideas for where else to look or how to continue?

**Comment by jazzdragon** [comment]
I'm snagging this one

**Comment by daniellemoorhead** [comment]
I moved it into the In Dev column for you @jazzdragon. Welcome to the team! If you need any help jump onto the Slack #dev channel and if you mention @devs you'll be able to notify the dev team about the question.

Cheers 🎉

**Comment by jazzdragon** [comment]
Thought I made progress, but not sure this is actually possible to do with dynamic translating. See https://github.com/textAngular/textAngular/issues/821

This is as far as I got, in case someone has an idea of how to help me solve this, or want to take over: https://github.com/openfoodfoundation/openfoodnetwork/pull/3758/files
