### ISSUE TITLE
When duplicating a product, image is not shown in the duplicate product straight away, needs refresh

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3298]
## Description
When I duplicate a product with an image, the copy is created but the image seems not to be duplicated as it is not displayed:
![capture du 2019-01-09 09-42-59](https://user-images.githubusercontent.com/8135376/50887719-3abe2a80-13f4-11e9-9ab9-b8c335823a62.png)

But when I refresh the page, I realize the images have actually been copied correctly:
![capture du 2019-01-09 09-46-02](https://user-images.githubusercontent.com/8135376/50887747-4d386400-13f4-11e9-992c-03c3de3dc17c.png)

Also sometimes if many data for the user account, the duplication takes time, it is confusing we have the impression it is not working.

## Expected Behavior
When I duplicate a product with an image, the new line shows straight away the image.
During the duplication time, a loader is displayed.

## Actual Behavior
It doesn't.

## Steps to Reproduce
1. Go to products, duplicate a product with an image, you see the new line has no image.
2. Refresh, and see the image has appeared.

## Context
Remaining bug after fixing #2756 

## Severity
I would say S3, the feature is not broken, but the UX is very broken, it is very confusing for the user.

## Your Environment

* Version used: v1.24
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu 18.1

**Comment by RachL** [comment]
@myriamboure can we take the opportunity in this issue to add a loader when clicking on duplicate? I find it confusing to click on duplicate and then not know that something is happening...

**Comment by myriamboure** [comment]
I added that in the description but I'm wondering if those two things shouldn't be two separate issues ? I think it should.

**Comment by RachL** [comment]
Let's maybe see with a dev. Because if we remove the refresh IMO we need a loader

**Comment by RachL** [comment]
This is working now 🎉  Closing
