### ISSUE TITLE
If a User creates an Enterprise, full permission E2E links are created between the new Producer and any Hubs MANAGED by that User

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#330]
May need to think about this more . . do we want auto E2E link creation to be restricted to Enterprise Owners only for now, perhaps . .

http://community.openfoodnetwork.org/t/auto-creation-of-e2e-links-when-creating-new-enterprises/33?u=openfoodnetwork

**Comment by myriamboure** [comment]
I propose to close as too old and all that is going to be reviewed in new product chain thinking. Permissions working ok for now also. #gitcull2018
