### ISSUE TITLE
If I try to create a new Enterprise Fee but forget to fill the 'Fee Type' field, I get snail page.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#3307]
## Description
When I try to make a new enterprise fee, if I forget to select a 'fee type' I get the snail page. This is unpleasant for users. Could we please put a red error box around the field, or an error message (please select a fee type) instead?

## Expected Behavior
I would prefer an error message telling me what to fix.

## Actual Behavior
The user gets a snail page which doesn't tell them what they did wrong.

## Steps to Reproduce
1. Go to the Enterprise Fee page 
2. Enter details for a new fee, but leave the Fee Type field blank
3. See error

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/10843056/51008686-e1dfc500-15a0-11e9-9029-ec3ddeb44a75.png)

## Context
I'm trying to setup fees.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
Aus staging, PC, Chrome.

**Comment by kirstenalarsen** [comment]
@sauloperez agrees is papercut - hurrah! lack of validation, it's in

**Comment by sauloperez** [comment]
This is again a lack of a validation
