### ISSUE TITLE
When User (owner) creates new Hub, existing Producers should GIVE E2E links to that Hub

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#331]
unless Super-Admin? to discuss

**Comment by kirstenalarsen** [comment]
this one still not done . . am going to push anyway, but need to sort this one next week and then we're done on these auto-creates.

See full notes here - http://community.openfoodnetwork.org/t/what-e2e-links-do-new-enterprises-have/33/3

**Comment by kirstenalarsen** [comment]
as admin@off, I own OFN independent hub

[CORRECT] from admin
- I create enterprise, not a producer
- creates as type 'any'
- creates E2E link from producers

[NOT QUITE] from /register
- creates as any (Hubbit)
- creates E2E link with other hubs
- does NOT create E2E link from existing producers

**Comment by RohanM** [comment]
With this issue from /register, I'm a bit confused as there's no option to create as `sells=any` (ie. as a hub). So not sure how this situation could arise?

**Comment by RohanM** [comment]
New spec: If you're logged in, and you own a hub, and you create an enterprise that's not producer, then that enterprise is created as sells any.

**Comment by kirstenalarsen** [comment]
for some reason this is not working in production. pretty sure we tested and pushed it last week, but when creating new buying group for SEFhub it's not working.

logged in as southeastfoodhub@gmail.com, which 'owns' lots of hubs
![image](https://cloud.githubusercontent.com/assets/2911176/6892189/a5ccdc5e-d70d-11e4-88a1-6f31de9bee24.png)

create new enterprise, not producer and is NOT a hub


therefore producer links to this new enterprise also not created :(

**Comment by kirstenalarsen** [comment]
nb. this relates to these commits, which don't seem to have taken effect

![image](https://cloud.githubusercontent.com/assets/2911176/6892219/01088258-d70e-11e4-9dfc-3b444721ea2f.png)

**Comment by kirstenalarsen** [comment]
updated spec - should create only P-OC NOT all permissions
