### ISSUE TITLE
, and . problem is back on enterprise fees

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3335]
## Description
In countries using , as a separator for decimals, when I setup a "per kg" enterprise fee, and fill in with "5,50" for instance, when I save it is transformed to "5.00".
This was fixed by Pierre last year, I did tested that specifically I remember, so probably was reintroduced by refactor ? (@mkllnk maybe it will ring a bell)

## Expected Behavior
User can enter indifferently , or . for decimals separator, it will work

## Actual Behavior
It doesn't.

## Steps to Reproduce
1. Go to enterprise fee.
2. Create/update a fee with per kg basis with , as decimal separator.
3. Save, you see the decimals are not taken into account.

## Animated Gif/Screenshot
Before clicking save
![capture du 2019-01-16 13-06-57](https://user-images.githubusercontent.com/8135376/51248414-51362a00-1990-11e9-8a0c-ee20a3da23ed.png)
After clicking save
![capture du 2019-01-16 13-07-25](https://user-images.githubusercontent.com/8135376/51248417-52ffed80-1990-11e9-9560-d9dad1b04e78.png)

## Context
Found the bug while doing support to big italian hub setting hub some pilot on OFN.

## Severity
S3, there is a workaround which is to enter a . as a separator but people don't think about it and think it's broken in most european countries.

## Possible Fix
Check the refactor done by Maikel some time ago if there is a clue there ? It was working before as far as I remember.

**Comment by mkllnk** [comment]
Myriam is referring to issue #853 closed by pull request #1831. That pull request is treating each fee individually. It overlooked the Weight calculator. Other fees like Flat Rate per order seems fine:

Before update:
![Screenshot from 2019-03-18 17-08-59](https://user-images.githubusercontent.com/3524483/54510227-967ed400-49a0-11e9-84aa-693666112d84.png)

After update:
![Screenshot from 2019-03-18 17-09-15](https://user-images.githubusercontent.com/3524483/54510239-9d0d4b80-49a0-11e9-9d97-4367ff77d032.png)

But I can reproduce the bug with Weight per kg.
