### ISSUE TITLE
moment().add(period, number) is deprecated

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3348]
## Description

In https://github.com/openfoodfoundation/openfoodnetwork/pull/3344 we started seeing the new deprecation warning

```
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
```

You can see it in the 1st job build in https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-3344/builds/3.

## Expected Behavior

We need to change the calls the moment's `add()` to follow the new signature. Let's not forget to read that guide first.

**Comment by leandroalemao** [comment]
Hi folks,
I've just opened a PR to fix this https://github.com/openfoodfoundation/openfoodnetwork/pull/3386.
I hope it's all good.
Tks
Leandro.

**Comment by sauloperez** [comment]
Hi @leandroalemao ! happy to see you back!

**Comment by leandroalemao** [comment]
Tks @sauloperez ! You know.. busy life here as usual 👍 😄
