### ISSUE TITLE
Improve unreliable specs - Use timecop for time comparison in specs

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3369]
## Description
A quick fix to spec/models/proxy_order_spec.rb was put in place in #3354
the correct solution for this and all occurrences of this issue is to use timecop.freeze

## Expected Behavior
Spec is reliable and precise.

## Actual Behavior
Spec is not precise, assertion is too generic (2 seconds).

## Possible Fix
Use [timecop](https://github.com/travisjeffery/timecop).

**Comment by lin-d-hop** [comment]
CLosing as @filipefurtad0 is doing great work on this
