### ISSUE TITLE
Extract #with_open_adjustments out of OrdersController

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3376]
## Description

In https://github.com/openfoodfoundation/openfoodnetwork/pull/3366 we purposefully left an already grown `#with_open-adjustments` method in OrdersController but with the commitment to extract it.

Doing so will make it possible to reduce the complexity of that method by extracting others from it while doing the same with an already fat controller. Note, however, that we might need to extract other business logic out of `OrdersController#update` into a service object.

## Expected Outcome

`#with_open_adjustments` does not pollute the OrdersController with more responsibilities, more than it already has.

**Comment by Matt-Yorkley** [comment]
Closing; `#with_open_adjustments` was deleted a couple of months back :+1:
