### ISSUE TITLE
Common vs Country specific instances

### ISSUE THREAD

**Issue by Oliverks** [openfoodfoundation/openfoodnetwork#338]
Hei all!

I am part of this new initiative in Oslo, Norway, to mount a local food coop. Myriam has contacted some of you in the past weeks.
I am in the process of exploring the repo and trying to get it running and a few (probably naive) questions pop up.
First one: currently OFN is used in Australia and the UK running it seems (please confirm) two different instances. Why not using one global instance? As a reason I can think of country specific customizations, different legal requirements, etc. But not sure why this would imply local instances.

Of course the question is not neutral, using one common instance would allow us to be ready even quicker without the need for local admin and such - but contributing by paying a monthly fee.

Thanks!

**Comment by kirstenalarsen** [comment]
Hi!

Yes OFN in Australia and in the UK are currently running on two different instances. Our current intention is that different regions and countries would have separate instances for 3 reasons:
1) technical - so we don't currently need to deal with country specific customisations, taxes, currencies and languages within the same app (one step at a time :)
2) resilience - we think it's important that local food systems are not reliant on people or software running somewhere far far away and out of control. We're still a pretty small outfit with lots of good will contributions etc - we don't want the whole world going down if something goes wrong with a production deploy
3) philosophical / political - we think that local ownership and control of local food systems is a critical counter-balance to centralising corporate industrial ag - we want to protect against centralisation of control of our food systems, including protecting you against us :)

All of that said . . we are increasingly realising that the set-up and deployment, at the same time as organising local governance etc, is quite a big barrier for people - and we too would like for you to be ready quickly. Also, as we saw in the UK, actually having something up and running really helps to mobilise people to get involved, build on it, and be able to think about the organisation etc. We are looking at introducing an option where we could potentially do the install and perhaps maintain / upgrade for you (and others like you), maybe with monthly fee which would get you going more quickly and let you focus on getting everything else in order. something like how discourse do (https://payments.discourse.org/buy/ - although it would cost more than $100). Would you / your group perhaps be interested in something like that? 

Kirsten

**Comment by Oliverks** [comment]
I understand your points and I agree, But as you say, having a shared instance would significantly lower the effort to start a coop and would be such a boost at the beginning to mobilize people. Not to mention the potential economy of scale, both in time and money.

So, yes we would definitely be interested to discuss this. I will just see who on our side should take part and will get back to you.

/Olivier

**Comment by pmackay** [comment]
Would it be ok to close this and move discussion (if needed) to http://community.openfoodnetwork.org/?

**Comment by Oliverks** [comment]
Hei Pauk,
Perfectly ok to close the discussion. No need on my side to move it.
/Olivier
