### ISSUE TITLE
Do not include unused application.css and application.js when precompiling assets

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#3395]
Do not include unused `application.css` and `application.js` when precompiling assets.

## Description

We are also precompiling `application.css` and `application.js` (Rails defaults), which AFAIK we do not use anywhere.

The current situation is not ideal:

1. Both `application.css` and `application.js` require the entire CSS and JS trees, which means asset precompilation is taking more time than it should.
2. Even when everything seems fine in development and when running specs, deployment to staging or production could fail. See sample [recent deployment](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/uk-staging/deploys/52) to staging UK which had this error when precompiling assets:

```
rake aborted!
Sass::SyntaxError: Undefined variable: "$warning-red".
  (in /mnt/code/projects/openfoodnetwork/openfoodnetwork/src/app/assets/stylesheets/admin/pages/subscription_form.css.scss)
/mnt/code/projects/openfoodnetwork/openfoodnetwork/src/app/assets/stylesheets/admin/pages/subscription_form.css.scss:3
Tasks: TOP => assets:precompile:all
(See full trace by running task with --trace)
** [Bugsnag] No API key configured, couldn't notify
rake aborted!
Command failed with status (1): [/home/klim/.rbenv/versions/2.1.5/bin/ruby ...]
/home/klim/.rbenv/versions/2.1.5/bin/bundle:23:in `load'
/home/klim/.rbenv/versions/2.1.5/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

I see two options:

1. Exclude both files from asset precompilation. There are no constants for the default values of `config.assets.precompile` however, so we might end up changing this in a way that is not upgrade-safe: https://github.com/rails/rails/blob/v3.2.22.5/railties/lib/rails/application/configuration.rb#L48
2. Clear `application.css` and `application.js`. Let Sprockets continue to compile these, but they will be blank files.

## Steps to Reproduce

For developers:

1. In an SCSS partial imported by `admin/all.css` which does not import `admin/variables` directly, use a variable declared in `admin/variables`.
2. Loading the admin page should still compile the CSS successfully.
3. Running `bundle exec rake assets:precompile` would fail.

## Context

For #2733, pages were loading successfully in development, and automated tests were passing. However, deployment to staging failed.

**Comment by mkllnk** [comment]
I just looked at this because I'm changing some styles for mobile. It looks like I can just remove those manifest files and everything keeps working. Compile time reduces on my machine from 40s to 24s.

**Comment by Matt-Yorkley** [comment]
I read the other day that those files are used in emails more commonly than on the site itself... that might be something to double-check.

**Comment by mkllnk** [comment]
Ah, good thinking! I just checked and our mailer layout references a custom manifest. But I should definitely include that in the testing steps. :bowing_woman:
