### ISSUE TITLE
Remove "visible: true" from have_selector in feature specs

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#3398]
Remove `visible: true` from `have_selector` in feature specs

## Description

The following confirms that our config and version already make `have_selector` look only at visible selectors:

```
     Failure/Error: expect(page).to have_selector "table.managers" #, visible: true
       expected to find **visible** css "table.managers" but there were no matches. Also found "", which matched the selector but not all filters.
     # ./spec/features/admin/enterprise_roles_spec.rb:121:in `block (5 levels) in <top (required)>'
     # -e:1:in `<main>'
```

## Expected Behavior

No user-observable changes expected.

## Actual Behavior

No user-observable changes expected.

## Steps to Reproduce

In a feature test, assert this for a hidden element:

```ruby
expect(page).to have_selector(custom_selector)
```

Expect the test to fail.

## Context

I was looking into addressing #3381.

**Comment by RachL** [comment]
@filipefurtad0 where you aware of this one? do you think we need to keep it or is it outdated?

**Comment by filipefurtad0** [comment]
Hey @RachL , thanks for the heads up on this one - I was not aware.

I've had a quick look and we do use this option in several places in our specs. It seems not to be outdated. I'll assign myself and remove this option and see if we still have a green build.
