### ISSUE TITLE
Remove obsolete soft-delete action

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3405]
## Description

Spree 2 changed the implementation of soft-deleting products. Calling `destroy` is now soft-deleting. That means that we don't need our own `soft_delete` action on the products controller decorator any more: https://github.com/openfoodfoundation/openfoodnetwork/pull/3394/files/b1fde225f3cdf64dee1d6634e0060ec2f913968d#diff-21992ae590a608944725dafc108beb2c

**Comment by luisramos0** [comment]
remove tag [[Spree Upgrade]] so we keep it for mandatory issues in v2.

**Comment by luisramos0** [comment]
This was closed by #4578
