### ISSUE TITLE
Credit card name should be able to be different from Checkout name 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#341]
Auto-populate from Customer name, but overridable

**Comment by myriamboure** [comment]
??? @kirstenalarsen I don't understand this issue, is it still valid? Can you explain if yes so that I can link to the relevant icebox item?

**Comment by kirstenalarsen** [comment]
is very old and no idea if is still a problem - just couldn't use a credit card in different name from the customer name on the order. was used for merchant gateway setup (embedded credit card) which I think hardly anyone (if at all) is using at the moment. so fine to shut it i reckon
