### ISSUE TITLE
Replace Spree calculators with our own

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3413]
## Description

We override almost all code in Spree decorators. We also had trouble with inheritance in the past. And since Spree 2 we define our own list of calculators, but still point to Spree classes.

It would simplify our code and make it more robust to create our own calculator classes within the OFN namespace. They can live in `lib` as they are not application specific and could move into their own gem in the future.

Spree makes it really simple to define our own list of used calculators. See #3400.

**Comment by luisramos0** [comment]
Removing [Spree Upgrade] so we keep the tag only for mandatory issues for v2.

**Comment by luisramos0** [comment]
this was done as part of https://github.com/openfoodfoundation/openfoodnetwork/issues/5687 and #5883
