### ISSUE TITLE
Import validation panel gives incorrect information -  column names in the wrong places

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#3414]
## Description

When doing a product import I used the product import template 

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/8379b46d-f061-4d56-842f-278933962f0f)

to create an import file that looks like this

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/77811dc9-9dc8-40f2-8ba2-9bc98ad55097)

The import validation then looks like this . . 
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a1cae950-f9cd-421b-bb64-e5588ad8f5f6)

It tells me everything is fine, but the column names are all wrong. 
* The Producer does not appear
* Producer column contains SKU
* SKU column contains Product name
etc

The data are imported correctly then but the display is very confusing and users feels they can't do the import and it's bugging.

## Expected Behavior
The column names should match the data in the columns / the column names from the import file

## Actual Behavior
The column names in the import validation display are all muddled up, even if data are then imported correctly.

## Steps to Reproduce
1. Go to admin/product_import 
2. Download the product import template file
3. Set up some products to import, following instructions in user guide - https://guide.openfoodnetwork.org/advanced-features/products/product-and-inventory-import#1-import-new-products
4. Save your file as csv
5. Go back to product import
6. Select 'Product List', choose file, select your file
7. Select import 
8. View product validation

## Animated Gif/Screenshot
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a1cae950-f9cd-421b-bb64-e5588ad8f5f6)

## Context
Was extremely confusing when I was trying to upload products

## Severity
s3 - non-critical feature and you can still do the import. However if you are a person doing this for the first time and don't know this it would likely put you off using it. Also I am imagining that if you have an actually incorrect file this is going to give you very unhelpful feedback to fix it

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment
Chrome, Mac OS

**Comment by kirstenalarsen** [comment]
the plot thickens. While doing this bug report I retested with the file above and now it looks ok
![image](https://user-images.githubusercontent.com/2911176/52030899-fabf1300-256d-11e9-8739-69c939c68fe4.png)
although still not showing the Producer column

But then i tested with the bigger file (med) and it is having the same problem
![image](https://user-images.githubusercontent.com/2911176/52030855-cf3c2880-256d-11e9-909c-cee2f93ed461.png)

**Comment by myriamboure** [comment]
Thank you @kirstenalarsen :-) Following conversation on delivery train I removed the bug tag as the feature is not yet release, I added it in the project and epic and I'll retest now. We will see if it blocks releasing or not, if it doesn't we will release and will tag this as a bug so it can be fixed among other bugs, else we will ensure it is fixed before we release.

**Comment by myriamboure** [comment]
@kirstenalarsen question : if you still continue and import the products, are the information saved correctly, the name in the fiels "name", attached to the good producer, etc ? When you check the catalog ?
I understand it is VERY confusing for the user and needs to be fixed, but I want to understand if the data import still happens consistently even if display of information is wrong. Thanks :-)

**Comment by myriamboure** [comment]
I think it is blocking the release as it introduce a pretty annoying confusion when doing the import, so this is attached to the epic which is among top priority, so should be fixed quickly.

**Comment by myriamboure** [comment]
I found the answer in Slack, data are imported correctly, all good @kirstenalarsen :-)

**Comment by myriamboure** [comment]
"ok it almost seems random!! works on some files, some columns appear / disappear" from Kirsten on Slack. If it's random, then I suggest we don't block release of the feature and keep it in bug backlog, and see if it reappears, fix it following usual priority process.

**Comment by Matt-Yorkley** [comment]
I think this is related to #3448

**Comment by RachL** [comment]
@kirstenalarsen @myriamboure as I did not find the exact files, I wasn't able to reproduce so I'm guessing Matt's solution works as well for this problem. This issue will be close when the PR will be merged, but do not hesitate to test again with the exact same file after the release. And re-open if necessary :)
