### ISSUE TITLE
[Product import] Saving error when on_demand is empty

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3419]
## Description
Seen while testing #3387 : when testing what happened with empty on_demand cells for 2 lines on a second batch, I had an error at the saving stage, which prevented the 2 products to be imported.

## Expected Behavior
Any errors should be revealed before the actual import, not after.

## Steps to Reproduce
1. Use the file described here with producers matching your environment: https://docs.google.com/document/d/1muvvMKkA0dfUxNS75VxavsFudFXorVcojbLCrZW6Msc/edit# (Apparently github prevent me from uploading a .csv to the issue, too bad)
2. Click on import
3. Observe results

## Your Environment

* Version used: 1.25
* Browser name and version: Firefox 64
* Operating System and version (desktop or mobile): Ubuntu 18.10

**Comment by Matt-Yorkley** [comment]
@RachL Can you send me the file on Slack so I can reproduce it? Thanks.

**Comment by RachL** [comment]
@Matt-Yorkley done!

**Comment by daniellemoorhead** [comment]
@RachL @Matt-Yorkley this has also been sitting here for over 3 weeks with no change. Is it being worked on or back into the backlog?

#toottoot

**Comment by Matt-Yorkley** [comment]
I've just done some initial tests with this, and it is saving correctly when `on_demand` is set to `0`, `1`, or blank. I'll investigate a bit more...

**Comment by Matt-Yorkley** [comment]
@RachL I've confirmed in both automatic and manual testing that empty `on_demand` values are not a problem when importing.

If I look at the CSV file you used for the test it looks like there are some issues with the content and the file itself.

Extra commas in the column headers:
![Screenshot-2019-03-27-17-37:17](https://user-images.githubusercontent.com/9029026/55099175-2f0b0780-50b7-11e9-92ac-ce7b1dcff37b.png)
And lots of blank columns:
![Screenshot-2019-03-27-17-37:36](https://user-images.githubusercontent.com/9029026/55099179-2fa39e00-50b7-11e9-8c3b-ec947b3f4871.png)
Error values embedded in the CSV file itself (I think this is a Microsoft Excel thing):
![Screenshot-2019-03-27-17-38:00](https://user-images.githubusercontent.com/9029026/55099180-2fa39e00-50b7-11e9-8005-90b3f78920cd.png)

Also, there's no `unit_type` column in the file?

**Comment by Matt-Yorkley** [comment]
Test file:
![Screenshot-2019-03-27-17-44:27](https://user-images.githubusercontent.com/9029026/55099674-0d5e5000-50b8-11e9-88f1-ee97ea35deb8.png)

Results after (successful) import:
![Screenshot-2019-03-27-17-44:12](https://user-images.githubusercontent.com/9029026/55099694-15b68b00-50b8-11e9-9988-f13c7593736b.png)

**Comment by RachL** [comment]
@Matt-Yorkley yes this was opened before we made the recent changes, so I'm closing this ;)
