### ISSUE TITLE
[Product import] Parallel imports override each other

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3423]
## Description

I think that we have a problem if several people try to use the product import within the same second. The file name contains a timestamp including seconds, but no other random part or incremental number. So if two people uploaded a CSV file in the same second, it would create a big mess.

```rb
    def save_uploaded_file(upload)
      filename = 'import' + Time.zone.now.strftime('%d-%m-%Y-%H-%M-%S')
      extension = '.' + upload.original_filename.split('.').last
      directory = 'tmp/product_import'
      Dir.mkdir(directory) unless File.exist?(directory)
      File.open(Rails.root.join(directory, filename + extension), 'wb') do |f|
        f.write(upload.read)
        f.path
      end
    end
```

## Expected Behavior

Many people can use the product upload and it never fails.

## Actual Behavior

It would try to write the same file. This could either fail or write data from two people into one file. Best case it's just invalid. Worst case a person is importing data from another person.

## Steps to Reproduce

1. Open two different windows and try to upload two different sets of products with the same second.

## Context

I was just looking through product import code for the Spree upgrade.

## Severity

I would say s3, because in some cases it's broken. The workaround is to upload when nobody else is uploading.

## Possible Fix

Use Ruby's `Dir::Tmpname` for a safe and unique place to upload a file.

**Comment by myriamboure** [comment]
I think this is not blocking the release of the feature as the probability of the import being launched at the same second is very low, isn't it ? Is it ok if I disconnect from the feature epic and we prioritize and fix it as any regular bug @mkllnk ? Or do you think we need to fix before releasing ?

**Comment by mkllnk** [comment]
Yes, it's unlikely, unless people double-click on the button and upload twice. Anyway, Matt has a pull request already. It's a simple solution. :-D
