### ISSUE TITLE
orders_and_distributors report is missing shipment method

### ISSUE THREAD

**Issue by berteh** [openfoodfoundation/openfoodnetwork#3446]
## Description
The orders_and_distributors report contains the details of the order, but not the related selected shipment method. When the distributor has multiple "pick-up"-type shipment methods, this missing information is crucial in managing the orders using this report.

## Expected Behavior
see shipment method in report table (and csv export)

## Actual Behavior
shipment method is missing

## Steps to Reproduce
1. create 2 shipment method of "pick-up" type, in different locations, for a single distributor
2. create 2 orders, with same products, each with a different "pick-up" point
3. create report, where you cannot distinguish the logistics details between the 2 orders

## Context
More efficient logistics to group orders grouped by pick-up location for shipment.

## Severity
bug-s4: it's annoying, but you can use it when combining with customers report and praying the user did not pick a different pickup location for this order... which is a dangerous bet.

## Your Environment
* Version used: .be instance
* Browser name and version: chrome 71.0
* Operating System and version (desktop or mobile): Win8 desktop

**Comment by SDBowen** [comment]
Hello :wave: 

I would like to help on this issue. I think I have it tackled and will create a PR shortly.

**Comment by berteh** [comment]
cool, thanks !
