### ISSUE TITLE
Add deployed version link to github issue template

### ISSUE THREAD

**Issue by berteh** [openfoodfoundation/openfoodnetwork#3453]
OFN version is asked in bug report (github template), but this info is not available to non admins, and will likely never be per https://community.openfoodnetwork.org/t/display-software-version/1170/7

## Possible Fix

Please add the following url to the GitHub issue report template in section "environment", to enable the user to find his/her version number:
https://github.com/openfoodfoundation/ofn-install/wiki/Current-deployment-status

**Comment by sigmundpetersen** [comment]
@daniellemoorhead anything you could do?

**Comment by daniellemoorhead** [comment]
It's done already, OFN version is one of the things in the versions section of the template. closing.
