### ISSUE TITLE
I18n: Producer Sign up asks specifically for ABN (Australian Business Number)

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#348]
Producer sign up should either request international company number equivalent or allow international options.

**Comment by pmackay** [comment]
Should check if #219 can be addressed also.

**Comment by elf-pavlik** [comment]
Any updates on this issue?

**Comment by pmackay** [comment]
@elf-pavlik what extra information do you need? I think a short term fix would be to hide that number if not AU.

**Comment by myriamboure** [comment]
@lin-d-hop, @mkllnk  and others, I checked with the new internationalisation, in the producer sign up, it seems that the field "ABN" and "ACN" are translated by what we have written in transifex (so can choose what to ask), BUT "charge GST" is not translated, and it's written "say-yes" or "say-no" near the button.
See illustration in Norway here, without yet the translation applied:
![chargegst-no](https://cloud.githubusercontent.com/assets/8135376/12194735/62e056d6-b5f2-11e5-824b-36fb5bebcd4a.png)

And in France, with the translation applied:
![chargegst](https://cloud.githubusercontent.com/assets/8135376/12194730/59e5af90-b5f2-11e5-90ad-02739182fc57.png)

**Comment by mkllnk** [comment]
Okay, I identified the problem. The translation for `say_yes` is not in the OFN. It is in Spree. The spree_i18n project contains all translations, but `say_yes` is missing in the French translation file of Spree. There are three possible solutions:

* Upgrade to a newer version of spree and spree_i18n.
* Patching spree_i18n.
* Including `say_yes` in our own language file.

I think that the last solution is the easiest and best. I will fix that in our master branch.

**Comment by myriamboure** [comment]
Thank you @mkllnk :-)

**Comment by mkllnk** [comment]
@lin-d-hop Can this issue be closed now? I think you can customise the business number via your en-GB locale.

**Comment by lin-d-hop** [comment]
Thanks @mkllnk, star! All looks good. Closing.
