### ISSUE TITLE
When crediting an order the transaction fee is applied when it shouldn't

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#3490]
## Expected Behavior
I have an order which was paid in full with Stripe. Then I removed an item from the order, putting the order in Credit. I tried to refund this credit using the Credit button. I found that when the credit was applied, the transaction fee that the shop has on Stripe payments was applied to the credit. 

I would not expect a payment method transaction fee to be applied to a credit event.

## Actual Behaviour
The credit event incurred the transaction fee.

## Steps to Reproduce
1. Place an order in a shop and pay with Stripe- where stripe has a payment method fee associated (e.g $5)
2. Go to Orders in the backend and take one item from the order, putting it into credit
3. Go to edit the order and go to payments. Click the credit button.
4. See that the credit was applied but the transaction fee was also applied.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/10843056/52763133-aa1bdf80-306e-11e9-9153-832326290fd4.png)

## Workaround

The new workaround for this bug is to stop doing partial refunds through OFN or if the partial refund is done through OFN do a negative adjustments and refund through stripe :face_with_head_bandage: 

## Context
I'm trying to do a partial refund from the backend.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
Product, Aus, Chrome, PC, Desktop

## Possible Fix
Credit event should not carry fee.

**Comment by sauloperez** [comment]
This one is looking at us @luisramos0 :trollface: I wish we could wait until fixing it in v2 but I'm afraid it'll still take some time...

**Comment by luisramos0** [comment]
well, not really, I think we have to ask:
- is this a fundamental feature in ofn and how much is it used today? most probably it's not used and it has been broken for a while
- will this fix in master work in v2 and thus, there will be no rework when merging to v2? I think the answer is no, we would have to fix in master and then think again about it in v2 with all the changes in adjustments/shipments
So, I'd only fix this one only in v2 if no one disagrees.

**Comment by sauloperez** [comment]
That's exactly what I meant. We need to know if it can wait for a single v2-fix or not

**Comment by kirstenalarsen** [comment]
@daniellemoorhead just clearing issues and found this - think is related to your local produce ladies question?

**Comment by kirstenalarsen** [comment]
not sure if we actually need to act on this or not

**Comment by daniellemoorhead** [comment]
> @daniellemoorhead just clearing issues and found this - think is related to your local produce ladies question?

@kirstenalarsen no, this is different. They were not happy about having to take the hit on the original stripe fee. The stripe website says that they don't charge fees on refunds so it would be worth checking if this is actually an issue anymore, maybe they changed their policy.

https://stripe.com/docs/refunds
![Screen Shot 2020-04-15 at 5 08 26 pm](https://user-images.githubusercontent.com/10949052/79308345-c437a300-7f3b-11ea-9ad8-11e483906458.png)

**Comment by luisramos0** [comment]
This can probably be investigated together with https://github.com/openfoodfoundation/openfoodnetwork/issues/5258
Maybe this is not a problem with stripe-sca, feeling optimist :blush:

**Comment by sigmundpetersen** [comment]
So we move this back to All the things?

**Comment by luisramos0** [comment]
@lin-d-hop can you make the call if this is part of the scope or not.

**Comment by lin-d-hop** [comment]
Although this is a long term annoyance it is nothing related to Stripe and definitely related to all payment method fees. 

It was optimistic that it was ever thought it might be in scope for Stripe SCA. Definitely out of scope. I wish I'd noticed a dozen comments ago to save all the investigation time ;-)

**Comment by RachL** [comment]
Ok I'm confirming this one is still happening and is really annoying now that we cannot delete adjustments anymore. Next round of s3 this is FR choice for sure.
I'm surprise no user was bothered by this sooner!

**Comment by lin-d-hop** [comment]
Hi @apricot12 I see you picked this up a month ago. How's it going? Have you been getting the help you need to figure it out?

**Comment by apricot12** [comment]
> Hi @apricot12 I see you picked this up a month ago. How's it going? Have you been getting the help you need to figure it out?

Well, it's 90% there but it needs ironing out. I almost pushed out a PR before I realized I was leaving out some possible scenarios.

**Comment by lin-d-hop** [comment]
Cool! ✨
If you can start to feel brave to talk about specifics as you learn I think it will help other devs learn the nuances of the app too. OFN is hard so talking/writing about the mistakes means that fewer people have to repeat and relearn them. 🙂
