### ISSUE TITLE
Investigate removal of spinjs-rails gem

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3491]
### What we should change and why (this is tech debt)

Our Gemfile contains spinjs-rails and we include the code in our front-end theme called Darkswarm. But we think that it's unused. This task includes:

- Find pages with the current spinner and verify they are working.
- Remove the gem from the Gemfile and `app/assets/javascripts/darkswarm/all.js.coffee`.
- Verify that the spinner is still working.

### Context

Dependabot prompted to update the gem version in https://github.com/openfoodfoundation/openfoodnetwork/pull/3460 which made us think about its use.

### Impact and timeline

 Keeping this gem dependency means regular reviews of updates of this gem. It should be removed as soon as possible. The task should only take a couple of hours.

**Comment by sauloperez** [comment]
Thanks @mkllnk!
