### ISSUE TITLE
Upgrade sass gem

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3501]
### What we should change and why (this is tech debt)

Depandabot tried to update our sass gem but the deployment to staging failed. In order to keep our dependencies up-to-date we need to find out why this failed and enable us to upgrade.

### Context

Failed PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/3458

### Impact and timeline

This can be done as soon as possible. But it should be done before the next Rails upgrade which is probably due after the current Spree upgrade.

**Comment by sigmundpetersen** [comment]
This was upgraded in #5158
