### ISSUE TITLE
Comply to rubocop styles

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3502]
### What we should change and why (this is tech debt)

Code Climate seems to be more relaxed than our Rubocop rules and we have several style violations. We need to either fix them or re-generate the rubocop todo list. It's probably the best to do both: fix the recent and obvious violations and defer the ones that are less important.

### Context

Code Climate complained about https://github.com/openfoodfoundation/openfoodnetwork/pull/3451. Usually I would change the pull request before merging, but there are pre-existing issues and I didn't want to block the pipeline.

### Impact and timeline

Within the next days or weeks while we still remember the recent code changes that violated our code style.

**Comment by luisramos0** [comment]
@mkllnk the rubocop todo list has been rebuilt recently. I wonder if this issue is still valid.

**Comment by mkllnk** [comment]
Ah, yes, almost done. I actually just stumbled across some violations fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/3935. I'll associate that PR with this issue.

**Comment by mkllnk** [comment]
Closed via #3935.
