### ISSUE TITLE
Orders and fulfillment report doesn't display price currency

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3510]
## Description

Orders and fulfillment report doesn't display price currency and that makes it hard to read. It would be much easier to spot the price columns if they had the currency next to them, otherwise, it's not easy to understand what those decimal numbers are about at a first glance.

## Expected Behavior

CURR. COST PER UNIT and TOTAL COST columns should display the price currency

## Actual Behaviour

There's no currency now

## Steps to Reproduce

1. Navigate to orders and fulfillment report
2. Pick order cycle supplier totals report type
3. Generate the report for a particular order cycle

## Context

I was trying to get this week's orders to one of the providers of our food hub

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v1.26.1
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using: Katuma

## Possible Fix

It turns out that [app/views/spree/admin/reports/_table.html.haml](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/spree/admin/reports/_table.html.haml) prints the cell values straight from [lib/open_food_network/orders_and_fulfillments_report.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/orders_and_fulfillments_report.rb) and no currency is taken into account. The value we pass to the view should have it appended, possibly by extracting a presenter object.

**Comment by sigmundpetersen** [comment]
Smells more like a feature request than a bug? Other opinions @RachL @lin-d-hop ?

**Comment by RachL** [comment]
@sigmundpetersen yes this to me is a feature request indeed. We are in front of something that was not designed according to a need, not something that is not working properly. I'm afraid we have to close it and move it to discourse where it could be prioritize over (or not) any work on the API enabling us to do all the report we want but with another tool. Except is this can be a good first issue (but still a feature request). Do you agree @sauloperez ?

**Comment by sauloperez** [comment]
It feels on the edge to be but yes, I understand. I was trying to cheat as this can be done quite quickly however having to wait for a full-fledged API to see the € there is exactly what I wanted to avoid. By the time we finish that I'm sure I won't care about that report at all. I accept what collectively decide anway :+1:

**Comment by RachL** [comment]
I agree @sauloperez but then on Discourse you can vote to prioritize this over the API work. The problem here is that this is not the only thing we would like to change on reports. So if we do this one, we would do others as well... and end up with a very big thing :/

**Comment by sauloperez** [comment]
Closing in favor of https://community.openfoodnetwork.org/t/orders-and-fulfillment-reports-display-price-currency/1578
