### ISSUE TITLE
Delete Spree::Core::ControllerHelpers::Order.class_eval.current_order_with_scoped_variants

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3515]
### What we should change and why (this is tech debt)
In v2, if we remove the following override:
[Spree::Core::ControllerHelpers::Order.class_eval.current_order_with_scoped_variants](https://github.com/openfoodfoundation/openfoodnetwork/blob/f0a6f5ae3ca56f39c5ba96fd63ee95b6af951fad/lib/spree/core/controller_helpers/order_decorator.rb#L4)
the build remains green.
Scoping variants every time we fetch current_order is quite expensive and may not be necessary at all.

### Impact and timeline
This has a performance impact and, also, scoping variants should be an explicit concern of current_order users.

### Possible Implementation
To delete this override safely we need to verify all uses of current_order and make sure they do the scoping correctly on their own.
A green build without this scoping means all tested scenarios don't need this but there could be untested scenarios.

So, for every use of current_order we need to see if the scoping is 1. required and 2. present.
For example, we know that in cart_controller current_order is being used but variant scoping is done correctly. So, no need to change.
But for example, is enterprises_controller.enough_stock? scoping variants correctly or is it dependend on current_order_with_scoped_variants?

Additionally, current_order is a spree method so we need to make sure all spree code that OFN uses and that uses current_order is also scoping variants if necessary.

Having raised all these concerns: because the build is green there's a strong indication that nothing needs to be done and the method can be removed!

## Expected Behavior
current_order does not need to handle variant scoping.

## Actual Behavior
current_order is problaby needed to handle variant scope although these scenarios are not covered by tests.

**Comment by mkllnk** [comment]
This was done in:

* 20f610fbee4f6a9e22bb77e3baa7fc6cb684a628
