### ISSUE TITLE
[Spree upgrade][Flaky spec] `spec/features/admin/customers_spec.rb:184`

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3520]
### What we should change and why (this is tech debt)

Pull requests for our Spree upgrade branch `2-0-stable` regularly fail `spec/features/admin/customers_spec.rb:184`. The unreliable spec feedback costs time.

### Context

https://github.com/openfoodfoundation/openfoodnetwork/pull/3394
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-3394/builds/6

### Impact and timeline

This is not as important as flaky specs on the master branch but the sooner we fix it the faster we can deliver the Spree upgrade.

**Comment by mkllnk** [comment]
The customers spec failed four times in the last ten builds:

- https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-0-stable/builds/226
- https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-0-stable/builds/224
- https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-0-stable/builds/223
- https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-0-stable/builds/220

```
rspec ./spec/features/admin/customers_spec.rb:210

  1) Customers as an enterprise user using the customers index updating a customer addresses creates a new shipping address
     Failure/Error: expect(page).to have_link 'New Address1'
       expected to find visible link "New Address1" but there were no matches
     # ./spec/features/admin/customers_spec.rb:228:in `block (5 levels) in <top (required)>'

  1) Customers as an enterprise user using the customers index updating a customer addresses creates a new shipping address
     Failure/Error: expect(page).to have_link 'New Address1'
       expected to find visible link "New Address1" but there were no matches
     # ./spec/features/admin/customers_spec.rb:228:in `block (5 levels) in <top (required)>'

  1) Customers as an enterprise user using the customers index updating a customer addresses creates a new shipping address
     Failure/Error: expect(ship_address.firstname).to eq 'First'
     
       expected: "First"
            got: "Firstt"
     
       (compared using ==)
     # ./spec/features/admin/customers_spec.rb:232:in `block (5 levels) in <top (required)>'


  2) Customers as an enterprise user using the customers index updating a customer addresses creates a new shipping address
     Failure/Error: expect(ship_address.firstname).to eq 'First'
     
       expected: "First"
            got: "First2345678"
     
       (compared using ==)
     # ./spec/features/admin/customers_spec.rb:232:in `block (5 levels) in <top (required)>'
```
```
rspec ./spec/features/admin/customers_spec.rb:184

  1) Customers as an enterprise user using the customers index updating a customer addresses updates the existing billing address
     Failure/Error: expect(page).to have_link 'New Address1'
       expected to find visible link "New Address1" but there were no matches
     # ./spec/features/admin/customers_spec.rb:201:in `block (5 levels) in <top (required)>'
```

**Comment by mkllnk** [comment]
I can reproduce it locally when running `cat /dev/urandom > /dev/null` in a separate console. The problem is the data entry. The address form doesn't get filled in properly.
```rb
          fill_in 'firstname', with: "First"
          fill_in 'lastname', with: "Last"
          fill_in 'address1', with: "New Address1"
          fill_in 'phone', with: "12345678"
          fill_in 'city', with: "Melbourne"
          fill_in 'zipcode', with: "3000"

          select2_select 'Australia', from: 'country_id'
          select2_select 'Victoria', from: 'state_id'
```

Result on the screen:
![capybara-201903181539054860299769](https://user-images.githubusercontent.com/3524483/54507187-56195900-4994-11e9-8482-699994b462bf.png)

**Comment by mkllnk** [comment]
It seems to be a [known bug](https://github.com/teamcapybara/capybara/issues/1890), a race condition caused by Bootstrap's fading in of the modal and the driver's sendKeys method returning too early. Here are some different solutions to that. Which one is your favourite? Or do you have other ideas?

### Assertions in the spec to wait for the input
```diff
diff --cc spec/features/admin/customers_spec.rb
index 7a2650d93,7a2650d93..7217521b0
--- a/spec/features/admin/customers_spec.rb
+++ b/spec/features/admin/customers_spec.rb
@@@ -213,12 -213,12 +213,12 @@@ feature 'Customers' d
            first('#ship-address-link').click
            expect(page).to have_content 'Edit Shipping Address'
  
--          fill_in 'firstname', with: "First"
--          fill_in 'lastname', with: "Last"
--          fill_in 'address1', with: "New Address1"
--          fill_in 'phone', with: "12345678"
--          fill_in 'city', with: "Melbourne"
--          fill_in 'zipcode', with: "3000"
++          fill_in_and_verify 'firstname', with: "First"
++          fill_in_and_verify 'lastname', with: "Last"
++          fill_in_and_verify 'address1', with: "New Address1"
++          fill_in_and_verify 'phone', with: "12345678"
++          fill_in_and_verify 'city', with: "Melbourne"
++          fill_in_and_verify 'zipcode', with: "3000"
  
            select2_select 'Australia', from: 'country_id'
            select2_select 'Victoria', from: 'state_id'
@@@ -235,6 -235,6 +235,11 @@@
            expect(ship_address.phone).to eq '12345678'
            expect(ship_address.city).to eq 'Melbourne'
          end
++
++        def fill_in_and_verify(name, opts)
++          fill_in name, opts
++          expect(page).to have_field name, opts
++        end
        end
  
        describe "creating a new customer" do
```

### Wait for the modal before doing anything

```diff
--- a/spec/features/admin/customers_spec.rb
+++ b/spec/features/admin/customers_spec.rb
@@ -210,7 +210,7 @@ feature 'Customers' do
         it 'creates a new shipping address' do
           expect(page).to have_content 'SHIPPING ADDRESS'
 
-          first('#ship-address-link').click
+          open_modal('#ship-address-link')
           expect(page).to have_content 'Edit Shipping Address'
 
           fill_in 'firstname', with: "First"
@@ -235,6 +235,13 @@ feature 'Customers' do
           expect(ship_address.phone).to eq '12345678'
           expect(ship_address.city).to eq 'Melbourne'
         end
+
+        def open_modal(selector)
+          first(selector).click
+          # Wait for the fade-in animation to finish.
+          # Otherwise `fill_in` may not work properly.
+          sleep 0.4
+        end
       end
 
       describe "creating a new customer" do
```

### Disable the fading effect

This could be done for specs only. Disabling animations speeds up specs but also means that we test a version of the app that is different. If we accidentally had an animation that took 300 minutes we would only be able to notice that in specs if we keep animations enabled.

```diff
--- a/app/assets/javascripts/admin/utils/services/dialog_defaults.js.coffee
+++ b/app/assets/javascripts/admin/utils/services/dialog_defaults.js.coffee
@@ -1,5 +1,4 @@
 angular.module("admin.utils").factory "DialogDefaults", ($window) ->
-  show: { effect: "fade", duration: 400 }
   hide: { effect: "fade", duration: 300 }
   autoOpen: false
   resizable: false
```

**Comment by luisramos0** [comment]
amazing detective work Maikel!! 👏 
I prefer "Assertions in the spec to wait for the input" :+1:

**Comment by kristinalim** [comment]
**Re: Assertions in the spec to wait for the input**

I don't like this approach because each of the field manipulations have to be aware that "this field is in a modal". Would we need to do this for all form components that are in modals, or just fix specs as soon as they fail?

**Re: Wait for the modal before doing anything**

I prefer this approach, but separating the click from the wait. For example: `expect(page).to have_modal`. This will allow us to test different responses to clicking a button. For example, for one scenario there is a modal, but for another there is none.

@mkllnk Does waiting for the modal to be `visible: true` not work?

**Comment by mkllnk** [comment]
> Does waiting for the modal to be `visible: true` not work?

There is an assertion already: `expect(page).to have_content 'Edit Shipping Address'`. That should default to `visible: true`. I guess the problem is that elements are already seen as visible when they are more than 50% visible.

I think I will go with your suggestion to keep the wait in a different method. It's the least invasive way of solving this problem. I don't like that we need to know the animation time (400 ms) there. But waiting for inputs needs the knowledge of being in a modal and disabling animations needs the knowledge of the way animations can be disabled (CSS and JS).
