### ISSUE TITLE
[Product import] On_hand can currently not be left blank

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3523]
## Description
Since changes made in inventory, these new rules have been introduce to PI:
>    1. If blank - Read as "Use producer stock settings", so "on_hand" should be blank.
    2. If "true", "TRUE", or "1" - Read as on demand of "Yes", so "on_hand" should be blank.
    3. If "false", "FALSE", or "0" - Read as on demand of "No", so "on_hand" is required.

However on the product side, a product cannot be created or updated with a blank on_hand column. If you set on_demand to 1, you need to set on_hand to 0.

## Steps to Reproduce
1. Log in as a super admin
2. Go to /admin/product_import
3. Try to upload a file while leaving on_demand to 1 and on_hand to 0 (you should see the below error message)

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/53094586-d7f39f00-351a-11e9-8b24-1861cb78256d.png)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v1.26.1
* Browser name and version: Firefox 64
* Operating System and version (desktop or mobile): Ubuntu 18.10

## Possible Fix
Allow on_hand to be blank

**Comment by daniellemoorhead** [comment]
OK team, this has been sitting here for over 3 weeks with no change. 

@Matt-Yorkley are you still working on it or does it get moved back to the backlog? Ping @RachL who also may have the knowledge to answer this.

#toottoot
