### ISSUE TITLE
Remove Product Distributions

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3525]
### What we should change and why (this is tech debt)
Product Distributions is a dead feature and should be removed from OFN.

### Context
From a slack conversation [here](https://openfoodnetwork.slack.com/archives/C59ADD8F2/p1546958052045600)

### Impact and timeline
Removing this will reduce code complexity and thus OFN's cost of maintenance.

**Comment by luisramos0** [comment]
@mkllnk I just realized you used product distributions in the sample data PR here: https://github.com/openfoodfoundation/openfoodnetwork/pull/3209/files#diff-6b925f809b3a412c614a3e69e37d6a78R89

Can you share what you know about product distributions? Is this a working feature? is it not replaced by OCs?

**Comment by mkllnk** [comment]
I only included it to make the data valid. It's annoying code without any benefit. :-) I would love to see it :fire:.

**Comment by luisramos0** [comment]
I found this comment from Rob, 2 years ago:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6c83f67b86c1f14b003a057b299536909d8c8f1e/app/models/enterprise.rb#L139

I guess that's now :-)

**Comment by luisramos0** [comment]
Another amazing line of code:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6c83f67b86c1f14b003a057b299536909d8c8f1e/spec/models/spree/order_spec.rb#L463

**Comment by sauloperez** [comment]
>  set_feature_toggle :order_cycles, false 

lol, it's clearly time to :fire:
