### ISSUE TITLE
[Spree upgrade] Impossible to duplicate/clone a product

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3530]
## Description
As a super admin or a producer, I'm not able to duplicate a product.

Note that all the products I have tested had images.

## Steps to Reproduce
1. Go to https://staging.openfoodfrance.org/
2. Login as super admin
3. Choose "Producer of pommes"
4. Try to duplicate a product
5. Nothing happens

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/53187991-a6ef9900-3604-11e9-92ef-624dd7232076.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: ??
* Browser name and version: Firefox 64 and Chromium 73
* Operating System and version (desktop or mobile): Windows 10

**Comment by luisramos0** [comment]
I only tried this after fixing #3529 
I can clone a product now even with a new enterprise. So, most probably the same cause as #3529 
please let me know if it is working now @RachL 
thanks

**Comment by RachL** [comment]
@luisramos0 yes it is!
