### ISSUE TITLE
[Subscriptions] Proxy orders show OC is closed when it isn't

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3544]
## Description

When viewing a subscription's proxy_order, it shows the order cycle as **closed** when it's actually **open**. It also shows an error message relating to the close time:

![screenshot-2019-02-25-13-49 39](https://user-images.githubusercontent.com/9029026/53342322-9a6d8800-3905-11e9-87f7-4998db0316e3.png)

I'm not sure if this also affects the placement of orders via proxy_orders, but I suspect it might.

## Expected Behavior

It should list the order's OC as open when it is open. 

## Actual Behaviour

It incorrectly shows the OC is closed.

## Steps to Reproduce

1. Create a subscription
2. View the order in the subscription
3. It displays: "closed Invalid date"

## Context

Testing subs.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: master
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Debian 10

## Possible Fix

Greping for the "Invalid date" error message shows it originates in the the js datepicker component...

**Comment by luisramos0** [comment]
see comment [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/3545#issuecomment-499562211)

**Comment by luisramos0** [comment]
Dear testers, @Matt-Yorkley says on slack maybe we should close these issues. Do you want to try to replicate?

**Comment by RachL** [comment]
@luisramos0 @Matt-Yorkley I can reproduce this in Staging FR:

![image](https://user-images.githubusercontent.com/6525576/60045101-43659d00-96c4-11e9-8794-6e04731ff0ed.png)

So back to the subs column.

**Comment by luisramos0** [comment]
ok, thanks for testing it. I'll give it a try again.

**Comment by luisramos0** [comment]
@RachL I feel a bit dumb here, I cant replicate this in fr staging. I have played with "Mary's Online Shop" but cant see this error... I tried with OC with and without end date...

**Comment by RachL** [comment]
@luisramos0 Many I've misunderstood Matt's issue, but I still see something weird on the orders. I've just logged in as super admin. The 3 first subscription for Mary's don't have orders yet. the others are showing these info:

![image](https://user-images.githubusercontent.com/6525576/60523414-f187cd00-9cea-11e9-9914-d690d7d446dc.png)

**Comment by luisramos0** [comment]
ah, nice, I see something different!

https://staging.openfoodfrance.org/admin/subscriptions

logged in as spree@example.com  
![Screenshot 2019-07-02 at 20 14 25](https://user-images.githubusercontent.com/1640378/60540050-1e95a900-9d06-11e9-8ade-45397de8af29.png)

what user are you logged in as?

**Comment by RachL** [comment]
@luisramos0 what the.... ? :rofl: I logged in as spree@example.com as well. I have "closed invalid date" on all Subs for Mary's who have an order...
I'm using Firefox 67. Can this be a cache issue?

**Comment by luisramos0** [comment]
good catch, I can see the problem in firefox as well. it works on chrome but not on firefox.
I'll have a look.

**Comment by luisramos0** [comment]
same server, same subscription:
chrome:
![Screenshot 2019-07-12 at 11 35 12](https://user-images.githubusercontent.com/1640378/61122246-289f7080-a499-11e9-92dd-ff36c8916fd0.png)

firefox:
![Screenshot 2019-07-12 at 11 35 19](https://user-images.githubusercontent.com/1640378/61122254-2d642480-a499-11e9-93c0-3da43b870c96.png)

**Comment by luisramos0** [comment]
in firefox, moment is not able to parse the oc close date "2019-08-06 09:01:31 +1000", it returns "invalid date" here: https://github.com/openfoodfoundation/openfoodnetwork/blob/bdeb56bfaf8e42dfb05d4617ce7df46267fcf47a/app/assets/javascripts/admin/subscriptions/controllers/orders_panel_controller.js.coffee#L18

**Comment by luisramos0** [comment]
the fix is to provie a date format, something already done in another side of our code:
https://github.com/openfoodfoundation/openfoodnetwork/blob/bdeb56bfaf8e42dfb05d4617ce7df46267fcf47a/app/assets/javascripts/admin/order_cycles/directives/change-warning.js.coffee#L13
