### ISSUE TITLE
[Subscriptions] Can't create subscription with ends_at date

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3545]
## Description

If I create a subscription with the `ends_at` date set it doesn't create a proxy_order. If I leave `ends_at` blank it does create a proxy_order.

The end date for the OC is 7 months from now. No combination of `ends_at` dates will create a proxy order.

Am I missing something?

## Expected Behavior

A proxy order is created.

## Actual Behaviour

No orders are created.

## Steps to Reproduce

1. Create a subscription with ends_at set
2. No proxy order is created

## Animated Gif/Screenshot

![screenshot-2019-02-25-14-15 29](https://user-images.githubusercontent.com/9029026/53343254-d6a1e800-3907-11e9-9e7b-5e145e8c2692.png)

## Context

Testing subs.

**Comment by Matt-Yorkley** [comment]
Possibly related to errors in dates when subs are saved, noted here: #3544

**Comment by luisramos0** [comment]
@Matt-Yorkley I cant replicate this issue neither #3544... they work fine for me locally. Maybe something specific about the OC you are using?
Can you try again?
or @RachL are you able to replicate these two issues?

**Comment by luisramos0** [comment]
Dear testers, @Matt-Yorkley says on slack maybe we should close these issues. Do you want to try to replicate?

**Comment by RachL** [comment]
@Matt-Yorkley I can reproduce your screenshot only if I create a subs linked to a shop with no OC currently open, which is a correct behaviour.

So I'm closing this but feel free to reopen if you manage to reproduce it.

![image](https://user-images.githubusercontent.com/6525576/60045519-5e84dc80-96c5-11e9-85c3-890a3307fc4d.png)
