### ISSUE TITLE
Monitor downtime of production servers

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3549]
Several instances report slow servers and downtime. #3493
We need to measure what our real downtime is to evaluate the current impact.

- [x] Australia
- [x] France
- [x] UK

**Comment by mkllnk** [comment]
Okay, monitoring is set up through Wormly. Now we just need to wait and collect data.

**Comment by luisramos0** [comment]
great stuff @mkllnk

**Comment by mkllnk** [comment]
The first couple of days data:
![screenshot from 2019-02-28 09-09-17](https://user-images.githubusercontent.com/3524483/53526534-99706c80-3b38-11e9-96c6-d6f6704aacc0.png)
![screenshot from 2019-02-28 09-08-49](https://user-images.githubusercontent.com/3524483/53526537-9d03f380-3b38-11e9-9571-9883424e414c.png)
