### ISSUE TITLE
[Spree upgrade] Add stripe to staging FR

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3553]
## Description
- **As a:** super admin
- **On page:**  /admin/stripe_connect_settings/edit
- **I want to be able to do:** See API info and be able to enable enterprise stripe accounts.

The API keys can be found on OFN France stipe account. Account details are charged in bitwarden **but please use the test data info not the production info.**

## Acceptance Criteria
1. As a super admin I can see the API details here : /admin/stripe_connect_settings/edit
2. I can tick the checkbox
3. If I go on an enterprise profile, I have the blue button "stripe connect" in the paiment methods (enterprise settings).

**Comment by sauloperez** [comment]
I did find all the keys and updated the secrets file but I'm not sure ofn-install's provision works there and I can't find the way to restart the unicorn.

**Comment by sauloperez** [comment]
This is blocked until we figure out how to provision to FR staging or we fix https://github.com/openfoodfoundation/ofn-install/issues/270

**Comment by sauloperez** [comment]
I manually modified `config/application.yml` in https://staging.openfoodfrance.org with the details I got from OFF's Stripe account. I tested the described acceptance criteria but check it out yourself @RachL to ensure we are on the same page.

I'll update the [Stripe's wiki page](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Setting-up-Stripe-on-an-OFN-instance) meanwhile.

**Comment by RachL** [comment]
@sauloperez did you manage to connect an enterprise? When I try to do it the callback URL shows https://staging.openfoodfrance.fr/ instead of https://staging.openfoodfrance.org

**Comment by RachL** [comment]
@sauloperez but yes I forgot this in my acceptance criteria 🤦‍♂️

**Comment by sauloperez** [comment]
I haven't. Let me check.

Btw, check out https://github.com/openfoodfoundation/openfoodnetwork/wiki/Setting-up-Stripe-on-an-OFN-instance. I hope it's more clear now.

**Comment by sauloperez** [comment]
Fixed! both the webhook and callback were pointing to openfoodfrance.fr instead of openfoodfrance.org.

**Comment by RachL** [comment]
This is working!!! Thank you @sauloperez 

![ ](https://media.giphy.com/media/3ov9jEKWFGKZVYsxPy/giphy.gif)

**Comment by RachL** [comment]
Reopening shortly this one because we need to do again step 5 of https://github.com/openfoodfoundation/openfoodnetwork/wiki/Setting-up-Stripe-on-an-OFN-instance on FR staging.
