### ISSUE TITLE
[Spree upgrade] Unable to sign up

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3561]
## Description
I can't sign up as a new user.

## Steps to Reproduce
1. Go to https://staging.openfoodfrance.org/#/login or even https://staging.openfoodfrance.org/register/auth#/signup?after_login=%2Fregister
2. Try to sign up
3. You get an error message saying you need to check your email address (I've tried around 5-6 emails addresses, and same result)

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/53488172-d16ea580-3a8d-11e9-89f5-822ccead2c4e.png)

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: ?
* Browser name and version: Firefox 64
* Operating System and version (desktop or mobile): Windows 10

**Comment by sauloperez** [comment]
Can you check again? according to @luisramos0 it is fixed.

**Comment by RachL** [comment]
Yes it is! Thx guys 🎉
