### ISSUE TITLE
[Spree Upgrade] Investigate "can't modify frozen Hash" error

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3564]
## Description

An error popped up while @RachL was testing the checkout in v2 Katuma's staging. Although she didn't see any error Bugsnag got the following one

![screenshot from 2019-02-28 16-53-48](https://user-images.githubusercontent.com/762088/53579377-bb3e1380-3b79-11e9-8abd-1438d5ef4851.png)

We need to investigate what it is. If this happened so easily in staging it could as well happen in production.

It's important to note that it involves adjustments, something we touched quite a lot recently.

**Comment by sauloperez** [comment]
@RachL do you remember the steps to reproduce by any chance?

**Comment by RachL** [comment]
@sauloperez I tried to reproduced it but didn't managed to so far. I was testing stripe, so I was doing multiple checkout, with various Stripe testing card and configurations (wrong dates, empty CVC...)

**Comment by sauloperez** [comment]
The only information I can provide is that that message shows up when trying to modify a destroyed record by means of a writer method. How this can be achieved here? no idea, so I think it's better to close this one until we find it again and know the steps to reproduce. If it still happens we'll encounter it soon.

**Comment by mkllnk** [comment]
I checked Australian staging Bugsnag and it's not there.

**Comment by sauloperez** [comment]
Ok, so closing
