### ISSUE TITLE
[OFN Belgium] Error 500 when trying to log in as super admin or manager to /admin

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3567]
## Description
When you log in as a super admin or a manager you are redirected to the /admin URL that gives you an error 500.

Workaround is to go to another admin URL, example https://openfoodnetwork.be/admin/orders?q%5Bs%5D=completed_at+desc and then navigate from there

## Steps to Reproduce
1. Log in as super admin (log in charged in Bitwarden)
2. Go to /admin
3. Get our friend the snail

## Animated Gif/Screenshot
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/df134ec8-8029-4ba2-b900-59c03b2488fa)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 1.26.1 ?
* Browser name and version: Firefox 64
* Operating System and version (desktop or mobile): Ubuntu 18.10

**Comment by luisramos0** [comment]
nice, I have access to the server.
it's a problem with translations
error:
```
Completed 500 Internal Server Error in 67.0ms (ActiveRecord: 0.7ms)
** [Bugsnag] Notifying https://notify.bugsnag.com of I18n::InvalidPluralizationData

ActionView::Template::Error (translation data {:zero=>"Vous n'avez aucun produit actif.", :one=>"U heeft één aktieve product"} can not be used with :count => 54):
    12:     - if @product_count > 0
    13:       %div.seven.columns.alpha.list-item
    14:         %span.six.columns.alpha
    15:           = t(".active_products", count: @product_count )
    16:         %span.one.column.omega
    17:           %span.icon-ok-sign
    18:       %a.seven.columns.alpha.button.bottom.blue{ href: "#{admin_products_path}" }
  app/views/spree/admin/overview/_products.html.haml:15:in `_50199b7ec9c33cd7615935c00963d948'
  app/views/spree/admin/overview/multi_enterprise_dashboard.html.haml:16:in `_f12bb44d95a02c92877279a21220f2f4'
  app/controllers/spree/admin/overview_controller_decorator.rb:12:in `index'
```

this is relatesd to this PR:
3378

my guess is that the plural translation is missing:
overview.products.active_products.other

is the language you are in 100% translated in transifex?

**Comment by RachL** [comment]
@luisramos0 I believe it was fr_BE but how can I be sure. I have the error when switching to English too btw.

I see on transifex that currently no languages are 100% translated, but I'm wondering if I have the right account (login with github).

**Comment by luisramos0** [comment]
ok, I havent tested but I am pretty sure this is the cause of this issue.
en.yml:
<img width="413" alt="screenshot 2019-03-02 at 15 33 08" src="https://user-images.githubusercontent.com/1640378/53684058-92945600-3d00-11e9-967e-0606a4c72953.png">

fr_BE.yml:
<img width="379" alt="screenshot 2019-03-02 at 15 32 58" src="https://user-images.githubusercontent.com/1640378/53684057-8e683880-3d00-11e9-90d3-0803ec62c8f4.png">

the entry overview.products.active_products.other needs to be translated in transifex and the problem will be solved.

**Comment by RachL** [comment]
As this won't be tested before the deployment of the release, I'm adding the blocked label.

**Comment by RachL** [comment]
Hey @luisramos0 a quick question: how come a missing translation leads to an error 500? I mean, usually we see the translation key, it's ugly but it works. Otherwise I have the feeling we really need to communicate more carefully to translators that a new release is coming.

**Comment by luisramos0** [comment]
It looks like it's from these special pluralization translations: #3378
Maybe @mkllnk will know better.

**Comment by mkllnk** [comment]
Uh, that is weird. Missing translations will usually not cause an exception. Maybe it's different here with the count value. I didn't know that. I just tested this after I removed the `other` translation from a key:

```
> I18n.t('bla')
=> "translation missing: en.bla"

I18n.t('orders_bought_items_notice')
=> {:one=>"An additional item is already confirmed for this order cycle"}

> I18n.t('orders_bought_items_notice', count: 1)
=> "An additional item is already confirmed for this order cycle"

> I18n.t('orders_bought_items_notice', count: 0)
I18n::InvalidPluralizationData: translation data {:one=>"An additional item is already confirmed for this order cycle"} can not be used with :count => 0
```

Lesson: Never use pluralisation without the `other` key. How can we prevent this? The I18n gem has an open issue for this: https://github.com/ruby-i18n/i18n/issues/123. It's included in the next milestone. We can wait for that and upgrade or we can use one of the workarounds mentioned in that issue.

Since we have a lot of tech debt, I'm leaning towards waiting but I'm almost sure to feel regret at some point when this happens again. We just have to deal with it.

**Comment by luisramos0** [comment]
Nice investigation Maikel!

So, we currently have 2 mandatory translations in en.yml, if they are missed by the translator, the system will be broken.
- overview.products.active_products.other
- overview.order_cycles.you_have_active.other

Yeah, maybe not the most urgent issue but I'd revert the change to the "manual" approach to pluralization.

**Comment by RachL** [comment]
Theo has confirmed this is working, so I'm closing this!
