### ISSUE TITLE
Add data migration tool functionality for update and delete

### ISSUE THREAD

**Issue by aidandunsdon** [openfoodfoundation/openfoodnetwork#357]
Splitting story #274 task into 2 sub tasks. 
Sub task 1. Migration of Stroudco database in single extract, transform, load.  Is implemented as an independent tool and does not require changes to application via pull request merge etc. Doesn’t require Rails db migration as no migration ids are required.  

Sub Task 2. Add data migration tool functionality for update and delete. Required if running in old Stroudco and new OFN instance in parallel. Requires migration ids and therefore changes to application db structure with rails db migrate, pull request, merge etc.

**Comment by lin-d-hop** [comment]
Closing as we will now be dealing with this in issues stemming from:
http://community.openfoodnetwork.org/t/bulk-import-of-product-inventory/667/7
