### ISSUE TITLE
[Spree upgrade] Can't ship an order made from a new account

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3574]
## Description
I'm able to ship previous orders. However when I'm creating a new account, I can capture payment but not ship the order. Is this the way spree v1 works? 

If so I'm ok with it because the ship feature was always weird, but then I guess we need to remove it in v1 as well?

## Steps to Reproduce
1. Go to https://staging.openfoodfrance.org/admin/orders?q%5Bs%5D=completed_at+desc
2. Try to capture a payment from an order at the  Winery District Food Hub.
3. After capturing, you should see the ship icon.
4. Do the same on Rachel deete account test hub.
5. After capture, the ship account does not show up

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/53738753-58f25500-3e90-11e9-848c-c4b3a5dcadc4.png)

## Severity
bug-s3

## Your Environment

* Version used: ??
* Browser name and version: Firefox 64
* Operating System and version (desktop or mobile): Ubuntu 18.10

**Comment by luisramos0** [comment]
I am afraid I cant replicate this in AU staging now :-(
There's some specific about that enterprise you call "new account" or about the order you place. I think we should try to understand what was making the "ship" action fail.

I'd bet it's related to something in the shipping method used..

**Comment by RachL** [comment]
@luisramos0 Can't replicate it on AU staging has well, so closing this. We will reopen if it happens again.
