### ISSUE TITLE
[Spree Upgrade] Clear all button translation does not fit

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3577]
## Description

As show in the screenshot, the Clear all button has a 100px fixed width which causes translations not to fit.

![screenshot from 2019-03-05 11-47-23](https://user-images.githubusercontent.com/762088/53818921-354f0d80-3f69-11e9-937d-0c0cc9d73f02.png)

It turns out that this doesn't not happen in v1, although the button has also a fixed width of 100px.

![screenshot from 2019-03-05 17-05-58](https://user-images.githubusercontent.com/762088/53818927-3849fe00-3f69-11e9-9783-2c417228a7fd.png)

## Expected Behavior

The button should not have a fixed width and rather adapt to the text.

## Actual Behaviour

It currently cuts the translation's text.

## Steps to Reproduce

1. Navigate to `/admin/order_cycles`

## Context

I was using the v2 version of the app in Catalan and I found it.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: 72e9c1d00
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by luisramos0** [comment]
on the OC page we have space left for the long translation, but on the inventory page there's no space left :-( what do we do? #fix-width-layout
![Screenshot 2019-03-24 at 21 04 37](https://user-images.githubusercontent.com/1640378/54885838-8a9b8200-4e78-11e9-9252-f3cbf891fbb3.png)

![Screenshot 2019-03-24 at 21 04 17](https://user-images.githubusercontent.com/1640378/54885837-8a02eb80-4e78-11e9-8c03-8c2053fe93d1.png)


what if you change the translation for just esborrar?

**Comment by sauloperez** [comment]
That could be a solution, yep
