### ISSUE TITLE
[Spree Upgrade] Disable stock transfers

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3578]
## Description

Spree v2 ships with stock transfers but since long agreed, we won't expose new features to OFN. Besides, as OFN has a single stock location, this feature is useless for us.

It looks like

![screenshot from 2019-03-05 11-31-36](https://user-images.githubusercontent.com/762088/53819375-1c932780-3f6a-11e9-8536-97898daa7441.png)

## Acceptance Criteria

It shouldn't be possible to see these page and any links to it (there is at least one in the settings side menu) at all.

**Comment by sigmundpetersen** [comment]
Fixed already in #3548?

**Comment by luisramos0** [comment]
yes, I connected 3548 to this one.
