### ISSUE TITLE
Hub logos are removed during deploy update

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#358]
Reported by Fife team after UK production server updated recently. See attached for where logos disappeared.
![broken logo back end screenshot](https://cloud.githubusercontent.com/assets/115115/5967262/4dd51892-a803-11e4-9e1b-bab68031f7b6.png)
![broken logo screenshot](https://cloud.githubusercontent.com/assets/115115/5967261/4dd26d4a-a803-11e4-9b1a-3fb812ca2a5c.png)

**Comment by lin-d-hop** [comment]
Is this still an issue? Didn't happen to enterprises on recent production deployment.
Closing.
