### ISSUE TITLE
Voiding payment does not remove transaction fee

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#3584]
Voiding either captured or uncaptured payment does not remove transaction fee.

## Description

I'm not sure if the payment method is relevant, but this was observed by @RachL for cash and myself for cheque. 

## Expected Behavior

When you void an existing payment and add another payment, you should only have the transaction fee for the payment that wasn't voided.

## Actual Behavior

When you void an existing payment and add another payment, you end up with two transaction fees.

## Steps to Reproduce

For below, create a cheque or cash payment method for the distributor. Take note of the expected calculation rate.

**As enterprise manager:**

Voiding payment that has been captured:

1. Create an order selecting the payment method earlier.
2. Complete the order without capturing payment. Check that the transaction fee is correct.
3. Capture payment. Check that the transaction fee is still correct.
4. Void the payment.
5. Add another payment. Notice in "Order Details" that there are now two transaction fees charged.

Voiding payment that was not captured:

1. Create another order.
2. Complete the order without capturing payment.
3. Mark the uncaptured payment void.
4. Add another payment to the order. Notice in "Order Details" that there are now two transaction fees charged.

## Context

Discovered by @RachL (and confirmed by myself) while testing #3563.

## Severity

bug-s3: a feature is broken but there is a workaround

You can set the transaction fee to $0.

**Comment by luisramos0** [comment]
This will be related to https://github.com/openfoodfoundation/openfoodnetwork/pull/3559
I'd bet the transaction fee adjustment is being voided as well as the payment but recalculated/re-added afterwards in order.update_payment_fees
