### ISSUE TITLE
Release v1.28.0 Completo

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3587]
## Description
This issue is here to track the evolution of release 1.28

## Draft

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/transifex/builds/12

**Comment by sigmundpetersen** [comment]
Nice! Why did we use the transifex branch and not master this time?

**Comment by RachL** [comment]
No idea :)

I found a weird display in one the reports. I tested the report on UK staging and it is shown correctly.
The display is weird for manager. For super admin I even have this:

![image](https://user-images.githubusercontent.com/6525576/53971362-13868f80-40fd-11e9-9c04-36d1eaea9965.png)

 I will stage the release on UK staging to see if the problem is linked to seed data.

Testing notes: https://docs.google.com/document/d/127Wl4ptD6A27teYVZqwCeBuJ_LdxNGPW2N1bIFoWd5k/edit#

**Comment by RachL** [comment]
All good on UK staging (well I get the snail in super admin because time out, but at least it is working for managers. So my guess is that it is linked to the data and not the code):

![image](https://user-images.githubusercontent.com/6525576/53972283-c6a3b880-40fe-11e9-883f-739bb5afd8ab.png)

**Comment by sauloperez** [comment]
🙈 I know what that is in Katuma staging but I won't take without a lawyer :troll:.

Jokes aside, that is the separate report app we hacked for Katuma... Looking forward to :fire: it.

**Comment by sauloperez** [comment]
:warning: **this release will need a ofn-install provisioning before being deployed**

**Comment by sauloperez** [comment]
We were wondering with @sigmundpetersen why was a provisioning needed. It must be the Bugsnag initializer stated in the release notes:

> Bring into the app the Bugsnag initializer used in ofn-install. It won't be symlinked at deploy time anymore. #3554 (Connected to ofn-install change: openfoodfoundation/ofn-install#329)
