### ISSUE TITLE
Cannot delete enterprises 

### ISSUE THREAD

**Issue by FiferMags** [openfoodfoundation/openfoodnetwork#359]
Error message returned when you try to delete an enterprise, both when logged in as a user and super-admin
![enterprise delete error](https://cloud.githubusercontent.com/assets/10771369/5974296/72482856-a86a-11e4-8974-6a9dce1c7185.jpg)

**Comment by kirstenalarsen** [comment]
perfect @FiferMags :)

**Comment by kirstenalarsen** [comment]
This is a core problem e.g. it's not just UK server or something the UK team should handle. Have tagged it Core and added to our backlog.

**Comment by myriamboure** [comment]
I experienced the same problem trying to clean up all the fake test accounts we have created for Norway... would be great to be able to clean it up :-)

**Comment by lin-d-hop** [comment]
Captured in OFN Delete project
