### ISSUE TITLE
[Product import] Impossible to upload a file with some tax category on OFN Canada

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3597]
## Description
Two problems here, let's see if we need to split the issue:
1. Some tax category cannot be found, even if it is correctly copy pasted
The tax-category  HST (Newfoundland and Labrador) does not work for example, but the tax category Zero-rated does. Could this be linked to space or special characters?

2. Impossible to upload a file without a tax category
I've tried the same file (just a different producer/category) on both OFN Canada and OFN France, and an unstranlated error shows up in OFN Canada, blocking the import.

## Steps to Reproduce
1. Go to https://openfoodnetwork.ca/admin/product_import
2. Try to upload one of these files: 
https://drive.google.com/drive/u/0/folders/1qRTfKAOKUglqxeQyLxVpKo67-6h8U8x2

## Animated Gif/Screenshot
OFN Canada (no tax column):

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/af4e6876-4a1b-4aa4-8761-a3ee4d4f056c)

OFN France (no tax column):

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/c8199ce1-44c2-4f50-bb5a-5cbb0a96116c)

OFN Canada with tax error:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/632ce605-c661-4231-8c22-9e73690f7976)

OFN Canada with no tax error:

![image](https://user-images.githubusercontent.com/6525576/54205320-6afa7600-44d6-11e9-9cb6-9a7cf512bc99.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: 1.28
* Browser name and version: Firefox 64
* Operating System and version (desktop or mobile): Windows 10

**Comment by Matt-Yorkley** [comment]
The second part "Impossible to upload a file without a tax category" is down to instance configuration: some instances require that all products have a tax category, and some don't.

**Comment by sineadfenton** [comment]
This is also an issue in the UK now - it seems so after the latest UK release?

![image](https://user-images.githubusercontent.com/28807449/57938695-96c41e80-78c0-11e9-9693-c796bf34006e.png)

**Comment by tschumilas** [comment]
This issue can be closed -   @RachL discovered that this is because the importer isn't recognizing brackets in the tax category field.  She created a new issue for this.  (We took brackets out of the tax category names on OFN_CAN and this field uploads fine now.)
