### ISSUE TITLE
[Spree Upgrade] Fix shipments.stock_location_id migration issue

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3600]
## Description
After migrating to v2, shipment.stock_location_id become null.

## Expected Behavior
After migrating v1 data to v2, we dont see any shipment.stock_location_id nulls.

## Actual Behaviour
shipment.stock_location_id is null for all shipments after migration.

## Steps to Reproduce
Fetch live data in v1 model, run db:migrate, inspect db.

## Possible Fix
Because we only have one stock location, we can make all existing shipments get the default stock location.
To do that we need to bring spree/spree@219e09b from spree v2.1.0

What's the best way to include it? Shall we simply copy the migration code to our branch as a new migration in OFN?

**Comment by mkllnk** [comment]
Yes, I think we should copy it. That's what we did with all the other migrations, right?
