### ISSUE TITLE
Unable to Save Changes in Inventory - "Use Producer Stock Settings"

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#3603]
## Description

A user has reported that they are unable to make changes to inventory. Specifically they have reported that they are unable to makes changes to 'Enable Stock Reset'. However when I went to have a play with this user and specific product I found that I could not save any changes with the error "Count on hand must be blank because using producer stock settings". I get this error when I try to change "Use Producer Stock Settings" to a different value too.

## Expected Behaviour

I should be able to make changes in inventory items.

## Actual Behaviour

I can't change the Inventory items stock settings for any inventory item. I have tested this for inventory items that have 'Unlimited?' field set to "Yes", "No" and "Use Producer Stock Settings". I seem to just not be able to update inventory stock levels now.

Console shows 400 error.
Logs give a 400 Bad request error.

## Steps to Reproduce

1. Go to Inventory (on UK production)
2. Try to update any field. I tried on many fields for 3 different enterprises.
3. See the error "Count on hand must be blank because using producer stock settings"

## Animated Gif/Screenshot

http://recordit.co/A5PnGqzL5b

## Context

This is making Inventory impossible to use for Hubs that rely on the 'Reset Stock' functionality. And in fact for anyone that wants to update inventory away from 

## Severity

I think s2 - Inventory is a non-critical but very close to critical feature!

## Your Environment

* Version used: v1.28
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubnutu 18.04
* OFN Platform instance: UK

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can't enable Stock Reset - Stroudco](https://trello.com/c/UYVnphM3/402-cant-enable-stock-reset-stroudco)

**Comment by luisramos0** [comment]
I just checked the UK live DB state:
"On demand Variant Overrides can't have count_on_hand" - **correct**, zero results for:
select * from variant_overrides where on_demand = 't' and count_on_hand is not null;

"On_demand false variant overrides must have count_on_hand" - **incorrect**, 2 results for:
select * from variant_overrides where on_demand = 'f' and count_on_hand is null;

"Use producer settings variant overrides can't have count_on_hand" - **incorrect**, 7 records for:
select * from variant_overrides vo where vo.on_demand is null and vo.count_on_hand is not null;

There are 4 enterprises in the uk live with this problem. It's not related to the variants in teh recording, it's mostly a problem with olive oil variants...

I have checked both FR and AUS live, these queries all return no results. Which is correct.

In v1.28 we have #3505. Could be the cause of the problem although I dont understand how, yet..
The quick workaround will be to clean up the data manually but ideally, first, we find out how the data came to this broken state.

**Comment by kristinalim** [comment]
I also don't see how #3505 could cause the invalid data.

The DB migration script which updated VO "On Demand" and "On Hand" settings to follow the new validation rules tracked the changes it made in a CSV file. In the UK server, this CSV file is: `/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2018-12-27-104734/reports/SimplifyVariantOverrideStockSettings/changed_variant_overrides.csv`. Seeing in this file that, out of these 9 invalid VOs in the DB, only 1 (supposedly) was updated by the migration script.

Also, none of these VOs have an `import_date`, which should mean that these were not created/updated to invalid values through CSV import.

**Comment by lin-d-hop** [comment]
I have updated the culprit inventory items and am now able to save inventory again.
Thanks all for the detective work!
I will close this and see if it comes up again - in which case we need to understand how these VOs are becoming corrupted in the first place.

**Comment by kristinalim** [comment]
@lin-d-hop Did there happen to be a deployment issue in UK that needed to be fixed at some point since December 27 (date of CSV file)? If yes, it's possible this was a deployment issue.

This sequence of events could result to invalid VOs:

1. Code is updated on December 27, and the migration script is run on the server. At this point, all existing VOs pass the new validation rules. But the app server did not restart, so the new validation rules are not yet enforced.
2. Users are still able to save VOs that do not pass the new validation rules.
3. App server is restarted successfully, and the invalid VOs are now correctly considered invalid.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley can you comment on the above?
That might well have happened @kristinalim Thanks!

**Comment by luisramos0** [comment]
@lin-d-hop have you mentioned somewhere on slack this has happened again?
I checked the UK live DB now and its fine.
