### ISSUE TITLE
[Spree Upgrade] Order edit page is not filtering shipping methods by the order distributor

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3607]
## Description
When editing an order we can see the full list of shipping methods in the system.

## Expected Behavior
We should see only shipping methods of the order's distributor.

## Actual Behaviour
We see the full list of shipping methods in the system.

## Steps to Reproduce
Open any order, edit shipping method and check the list.

## Animated Gif/Screenshot
Example from my local instance with sanitized AUS live data (I see 500+ shipping methods for any order)
![Screenshot 2019-03-15 at 12 40 50](https://user-images.githubusercontent.com/1640378/54431917-97ed9980-471f-11e9-8a3b-ab303e1f1418.png)

## Context
Found while testing #3527

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

**Comment by luisramos0** [comment]
This issue is fixed by a PR in spree: https://github.com/openfoodfoundation/spree/pull/39

**Comment by RachL** [comment]
thx @luisramos0 ! I wanted to open this but didn't have time since yesterday, sorry !

**Comment by luisramos0** [comment]
it's ok, I opened it because I created the PR for it.
can you open the email one?

**Comment by sauloperez** [comment]
I might have been too fast in merging https://github.com/openfoodfoundation/spree/pull/39 but this should be solved as soon as we pull that new commit in OFN's Gemfile.lock.

**Comment by luisramos0** [comment]
thanks. I think we are good, I'll create a new PR to bring spree39 to ofn. That PR can be manually tested and will close this issue.
