### ISSUE TITLE
Clean up useless data from live DBs to improve db backups speed and potentially app performance

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3608]
### What we should change and why (this is tech debt)
We will soon have tasks to sanitize and truncate data from production  #3579 This is useful to fetch data from live environments into testing environments.

Now we should create a new task for a different purpose: to reduce the live DB size by deleting data that is not needed.
Maybe it can be called ofn:data:clean_up

There are at least 3 good candidates to be deleted or truncated (keep only latest entries):
- spree_state_changes
- spree_log_entries
- sessions

This requires further investigation about what exactly are these tables and if they can really be deleted.

**Deleting all the data in these 3 tables in the AUS live database reduces the ZIP database size from 485MB to 67MB!**

### Context
this was found as part of Spree 2 data migrations.
This issue can include #2247 but it's not specific to sessions.

### Impact and timeline
This will make backups run faster and take a lot less space.
And it can improve app performance: #3099

**Comment by sauloperez** [comment]
I think this requires more than a rake task and fits more in ofn-install than here. In the past I investigated https://www.percona.com/doc/percona-toolkit/LATEST/pt-archiver.html for instance but never go to use it in production.

**Comment by luisramos0** [comment]
-  more than a rake task
there are many things you can do in this space, the scope here would be to simply delete unnecessary entries. 

- fits more in ofn-install than here
could be, I am not sure, I could easily see a job running that runs the tasks regularly (for example, delete sessions older than 1 month), that would be better in the app code, right?

- pt-archiver.html
the scope of this issue is not about archiving data, it's really just the simple case of deleting data that is not necessary for the operation

**Comment by mkllnk** [comment]
To break it down by table:

Aus production

- full backup: 480 MB
- without sessions: 107 MB
- without log entries: 106 MB
- without state changes: 70 MB

So I think sessions is a big one. Then let's look at state changes. Log entries is not really worth it but we can delete it while we are at it.

None of this really affects the performance of the app directly, I think. It's only the backup generation (which can affect the performance of the app).

**Comment by sauloperez** [comment]
Given these numbers it would be more about disk-space savings, right? No idea if that is currently a problem. Worth checking to be sure.

**Comment by mkllnk** [comment]
For me it's more about processing times. Creating or downloading backups in half the time is great.

**Comment by sauloperez** [comment]
Current numbers in FR production

![Screenshot from 2020-02-14 15-08-46](https://user-images.githubusercontent.com/762088/74538200-fa58a680-4f3b-11ea-8ab7-d0a6b7086236.png)

**Comment by Matt-Yorkley** [comment]
Some of our databases are reaching ~2.5 million records in the sessions table. We maintain 2 indexes on that table, plus we have to query it on every pageload or endpoint. We even hit it when serving an asset like an image for some reason. :see_no_evil:

**Comment by mkllnk** [comment]
> We even hit it when serving an asset like an image for some reason.

What? Did you test that in production or development? I can understand development because it needs the asset pipeline but nginx should handle this in production.

I just requested https://staging.openfoodnetwork.org.au/system/content_configurations/logos//original/OFN_Aus.png?2020 and the unicorn logs don't show any request while nginx logs show it. I think this is okay.

#### Sessions

The session issue is described in #2247.

#### Spree state changes

This is purely for logging, like we are introducing more and more subscription logging, Spree has state change logging. It can be helpful when investigating bugs but I doubt we need data older than a year. We also have backups for old data.

**Comment by sauloperez** [comment]
> It can be helpful when investigating bugs but I doubt we need data older than a year

to be honest, I don't think we even need more than a month.

**Comment by Matt-Yorkley** [comment]
>  we are introducing more and more subscription logging, Spree has state change logging

Yeah, I'm just wondering if this has ever been used in the entire history of OFN? 7 million records that have never been used for anything... :see_no_evil:

**Comment by Matt-Yorkley** [comment]
Just a heads up the database backup task that runs every 4 hours seems to be negatively impacting performance at least on French Prod, and I assume on others. CPU and and disk latency spikes, lasting around 5 minutes... I think even some fairl conservative pruning of these monster tables would be a big improvement here.

**Comment by Matt-Yorkley** [comment]
Can we just make a nice rake task and run it via `schedule.rb`?

**Comment by mkllnk** [comment]
Yes, I would delete all state changes older than a year.

**Comment by sauloperez** [comment]
> Can we just make a nice rake task and run it via schedule.rb?

What I had in mind was to extract https://github.com/openfoodfoundation/openfoodnetwork/blob/fabddbd1c0ce0c7ef1cb1507109c7258d7740851/lib/tasks/data/truncate_data.rb#L50-L54, and run it every N months. It's a 5min task and it would possibly fix the burden of the backups

**Comment by Matt-Yorkley** [comment]
Yep, that sounds awesome. Once a month?

**Comment by mkllnk** [comment]
Looks great. I would use longer periods though. Maybe keep data for 2 years? We can always reduce those periods later. Better safe than sorry.

**Comment by sauloperez** [comment]
I've never found myself in a situation where I needed any state change or log entry older than a couple of months. On the other hand, old sessions are not needed at all either but let's start with something and then we'll see if we need to tweak the time-window.

**Comment by Matt-Yorkley** [comment]
Has this been tested? https://github.com/openfoodfoundation/openfoodnetwork/blob/fabddbd1c0ce0c7ef1cb1507109c7258d7740851/lib/tasks/data/truncate_data.rb#L50-L54

When I experiment with this in the console, `Session` is an uninitialized constant. I think it needs a direct SQL query, and we should probably be querying by `updated_at` instead of `created_at`, right?

**Comment by sauloperez** [comment]
yep might be safer but I wonder if they are really updated or just created

**Comment by mkllnk** [comment]
>> We should probably be finding old sessions by updated_at instead of created_at, right?
> I wonder if they are really updated or just created

We are changing session variables regularly (session_id, flash messages). It updates the session record in the database every time.
