### ISSUE TITLE
[Spree Upgrade] Shipment confirmation email is not sent

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3616]
## Description
After shipping an order, you don't get an email saying shipment has begun.

## Steps to Reproduce
1. Create an order with a user account you can check the mailbox with and with shipping options. Pay by cash.
2. Log in as a manager of the shop you just did the order from
3. Capture payment. You should now see the "highway" icon (see screenshot below)
4. No email will be sent to the inbox

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/54542035-5701b900-499b-11e9-9ae1-c6313bcb1ac2.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: Au v2 staging
* Browser name and version: Firefox 65
* Operating System and version (desktop or mobile): Ubuntu 18.10

**Comment by luisramos0** [comment]
I will get to this one at some point.

**Comment by luisramos0** [comment]
@RachL I cant replicate this. I get the email on my user email in staging AU:
![Screenshot 2019-03-23 at 13 25 41](https://user-images.githubusercontent.com/1640378/54866699-57b99700-4d6f-11e9-950d-0b2960bb264c.png)

In your screenshot the user email is spree@example.com...
am I missing something?
Thanks!

**Comment by luisramos0** [comment]
I used this issue to test most emails in v2 in staging AU as is
https://github.com/openfoodfoundation/openfoodnetwork/wiki/emails
I tested cases 1, 2, 3, 4i, 5i, 7 and 10i 
I have not detected any issues 💪

**Comment by RachL** [comment]
@luisramos0 the screenshot was not link to my test, I just wanted to add an image to help visualize the icon I was speaking about. But yes I just re-tried and could not replicate, so I'm closing this one.
