### ISSUE TITLE
Set up Delayed Job alarms for AU staging

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3621]
## Description

To better explain issues like https://github.com/openfoodfoundation/openfoodnetwork/issues/3391 it's important to know if Delayed Job is up or not. Not only for devs but this is also helpful for testers. Currently, v2 is running in AU staging.

We just need to add just another host with the current alarms system we have in place for AU production and share credentials in Bitwarden so others can check when issues arise.

**Comment by sauloperez** [comment]
Do you think you could do it @mkllnk ?

**Comment by mkllnk** [comment]
Sure. I can set up some monitoring and connect it to Slack. But for testers, the best way to check is the API: https://staging.openfoodnetwork.org.au/api/status/job_queue

**Comment by sauloperez** [comment]
> Not only for devs but this is also helpful for testers.

We also need to get notified when it goes down so we prevent possible failures testers might not notice. Just as we do for production. Also, all alarm 3rd-party services (from what I know of HappyApps) give you details about each incident.

**Comment by mkllnk** [comment]
Okay, I created my own Happy Apps account and added a check for the Australian staging server. Notifications should go to Slack.

I didn't see a global Happy Apps account. @sauloperez Is that something we still need to do? Then we can put that in Bitwarden and we have all the checks together.

**Comment by sauloperez** [comment]
We opened Happy Apps accounts for each instance. So far, the only globals accounts are Datadog and Bitwarden.

I just shared Katuma's credentials and added a Katuma's collection as we did with France. I think UK it's the only missing one here @Matt-Yorkley

**Comment by mkllnk** [comment]
Ah, okay, I added the credentials for my account. @sauloperez Happy to close this?

**Comment by sauloperez** [comment]
Yes, thanks a lot @mkllnk ! We can create a card to add alarms for other stagings when we need to.
