### ISSUE TITLE
Add Delayed Job Web 

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3622]
## Description

We need to make it easier to check the behavior of Delayed Job in a given server and perform basic operations like retries or deletion of jobs.

A good way to do so is by setting up [Delayed Job Web](https://github.com/ejschmitt/delayed_job_web). This will be particularly useful for stagings where we try and mess up with things.

I raised the topic [ages ago](https://community.openfoodnetwork.org/t/delayed-job-monitoring/1099/2) but it never got into the priorities.

Check out https://community.openfoodnetwork.org/t/delayed-job-monitoring/1099/2 for a description of this web UI features.

Something to take into account is the authentication. Not everyone can have access to that UI meant for the core team.

**Comment by sauloperez** [comment]
If you want to check it live for Katuma, you can check it in https://app.katuma.org/admin/reports/order_cycle_management/delayed_job/overview. I did a massive hack back then to have it at least for us.

**Comment by mkllnk** [comment]
That is still a great idea. Do you think we should create a standalone app for this or integrate it within OFN?

**Comment by sauloperez** [comment]
> Do you think we should create a standalone app for this

No way. That would add an extra maintenance cost we can't afford IMO. If you want to check it, we have it live for Katuma in https://app.katuma.org/admin/reports/order_cycle_management/delayed_job/overview
