### ISSUE TITLE
Do not refresh cache when deleting OC

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3626]
### What we should change and why (this is tech debt)

When deleting an order cycle that was just created instead of simply expiring the cache key we do enqueue a `RefreshProductsCacheJob`. That is a bit odd since there is no order cycle to fetch its products from.

The first thing we need to understand is where this refresh is triggered from. So far the refreshes are caused by an `after_save` callback and according to the [Rails guides](https://guides.rubyonrails.org/v3.2/active_record_validations_callbacks.html), the `after_save` callbacks are not called on destroy.

Then, as per the investigation above, we need to confirm if it is true that **we process the background job that refreshes the cache within the lifespan of the transaction**. If that was the case it could potentially be the source cause of many hard-to-spot bugs.

### Context

This stems from the thorough investigation needed by https://github.com/openfoodfoundation/openfoodnetwork/issues/3391

### Impact and timeline

Both products cache and background jobs are a crucial part of our system and they need full understanding and ownership.

**Comment by sigmundpetersen** [comment]
Is all cahce gone? Can we close this @sauloperez ?

**Comment by sauloperez** [comment]
Yep. This is not relevant anymore.
