### ISSUE TITLE
Release v 1.29 Durian

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3630]
Semaphore link: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/562

**Comment by RachL** [comment]
I've seen something I'm not sure I saw before: you can add in a sub a product that has been deleted before.

Will add a special issue for this as I could reproduced it in production as well. So this is not blocking the release.

https://docs.google.com/document/d/12W_Bx6AVS5q-jEo3Bz-96g6YUcl0fnuc8to6h9xt2_Q/edit#

**Comment by lin-d-hop** [comment]
This is not new to this release. We are experiencing this on UK production.
Is the product in Inventory? I'm still trying to work out the nature of the issue with the user in UK.
You can't actually add the product to the Sub - but you have the choice of the product.

**Comment by RachL** [comment]
@lin-d-hop the product was not in inventory in my case. have to run to a meeting, but will create the issue in a couple of hours.

**Comment by RachL** [comment]
@lin-d-hop in my case, I could add the product to the sub. I've opened an issue here: https://github.com/openfoodfoundation/openfoodnetwork/issues/3635 don't hesitate to add examples, I didn't do further tests so far.
