### ISSUE TITLE
[Subscriptions] Deleted products appear in dropdown

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3635]
## Description
When you create a new subs you can see deleted products in the product selection.

## Steps to Reproduce
This is the exact steps I made. I need to test other scenarios as well:

1. Create a product. Put it in an open OC
2. Duplicate the product. 
3. Delete the duplicate
4. Add the product to a subs. In the dropdown you will see both the product and the duplicate you have deleted.
5. You can actually save the subscription with this deleted product with no errors. Nothing will happen further has you cannot add it to an OC.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/54758815-2e70fd80-4bed-11e9-8b37-df18de5a1eae.png)

![image](https://user-images.githubusercontent.com/6525576/54759735-fc609b00-4bee-11e9-8bd6-52a16ebeea28.png)

![image](https://user-images.githubusercontent.com/6525576/54759695-e652da80-4bee-11e9-898d-af7cae0c68f8.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: 1.29
* Browser name and version: Firfoex 65
* Operating System and version (desktop or mobile): Windows 10
* OFN Platform instance where you discovered the bug, and which version of the software they are using: Katuma staging.

**Comment by luisramos0** [comment]
I cant replicate this problem @RachL 

I see different problem: I add a product to a subscription, I delete the product and the subscriptions list page stops working.

**Comment by RachL** [comment]
@luisramos0 you are right. Specific to v1 then. However I didn't manage to reproduce your error. Can you open a specific issue for this one. Meanwhile I'm closing this.

**Comment by luisramos0** [comment]
new issue here: https://github.com/openfoodfoundation/openfoodnetwork/issues/3948

**Comment by luisramos0** [comment]
new issue here: https://github.com/openfoodfoundation/openfoodnetwork/issues/3948
