### ISSUE TITLE
[i18n] "cancelled" for payment status is badly automatically translated by spree

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3642]
## Description
On order / edit an order / payments, the status "cancelled" (when a payment is cancelled) is badly automatically translated by Spree in French, by "empty" ("vide" in French). The string is not in transifex so I can't do anything.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/8135376/54837480-cd1d5d00-4cc6-11e9-9302-7d6592376f72.png)
(in the red rectangle is the bad translation)

## Context
Reported by a user who got confused.

## Severity
S3

**Comment by luisramos0** [comment]
I think this has been fixed in v2. moving to test ready to be tested.

**Comment by RachL** [comment]
Indeed! 

![image](https://user-images.githubusercontent.com/6525576/58793438-6685bb00-85f6-11e9-98f4-d88ad1a8932c.png)


Closing
