### ISSUE TITLE
Tax category translation missing

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/openfoodnetwork#3645]
Translation for en_validation_msg_tax is missing. This is my first issue and I would love guidance if there is something different I should be doing.

## Description
When the instance had the "tax category required" box ticked and the user chose "no tax category", she got the error message "Tax category translation missing: en_validation_msg_tax" instead of something like "tax category required" or something like that.

## Expected Behavior
The error message should say something like "you must specify a tax category"

## Actual Behavior
The user is not able to save the update but they don't have information about why

## Steps to Reproduce

1. Superadmin configures instance to require a tax category
2. User edits a product choosing "no tax category"
3. User can not edit product, gets error message about untranslated error message

## Animated Gif/Screenshot
![ErrorOFNBulkBuyOption](https://user-images.githubusercontent.com/37803238/54866465-3a65d800-4d31-11e9-86ff-6fd633c3bd46.png)

## Context
It's confusing to the users and made a misconfiguration harder to identify. If an instance really did want to require a tax category for every product, users would be affected every time they tried to select the "no tax category" choice. In a perfect world, "no tax category" would not be an option if "tax category required" was selected.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
Just vanilla Chrome browser

## Possible Fix
Locate variable and provide a translation for this case?

**Comment by RachL** [comment]
@lauriewayne There are labels that you can use for bugs, and you can add it to the bug backlog as well, but other than that it was perfect :) I just did both so you don't need to do them again ;)

**Comment by amers185** [comment]
If this issue has not be taken, I am interested in working on it.

**Comment by RachL** [comment]
Go ahead @amers185 ! Thank you :)

**Comment by amers185** [comment]
@RachL I am still quite new to rails routing and I was wondering if you could direct me to where the bug is located in the code base? I appreciate it.

**Comment by daniellemoorhead** [comment]
@mkllnk @luisramos0 @sauloperez @Matt-Yorkley @kristinalim able to help @amers185?

**Comment by mkllnk** [comment]
Hi @amers185. Great to see you supporting us. I just looked for the code and found that it was fixed a few weeks ago when working on a very similar issue: https://github.com/openfoodfoundation/openfoodnetwork/pull/3585

No wonder you couldn't find the code. I will close this issue. Maybe you would like to have a look at #3509? You will need to edit several files there. One is `app/views/spree/order_mailer/_signoff.html.haml`.

**Comment by amers185** [comment]
@mkllnk Thank you. I was going a little crazy trying to find the correct file so its good to know :P I looked at #3509 and I will start working on that. In the issue description, the steps to reproduce are missing. Further, is there a general strategy I can use to navigate the directory? Lasty, I am a little confused about superadmin and what role it plays? Thank you.
