### ISSUE TITLE
[Product Import] Upload fails with special characters

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3657]
## Description

Uploading a CSV file with invalid UTF-8 characters fails without good user feedback. The user sees a snail page.

## Expected Behavior

The import either filters invalid characters or warns about them.

## Actual Behaviour

The import shows a snail page. The log shows:
```
Started POST "/admin/product_import" for 124.149.174.246 at 2019-03-26 18:12:47 -0400
Processing by Admin::ProductImportController#import as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"t0HqmDGiA2EMIC+f17IvMwWf/VQS4/b4lGLP6Pd5Ckw=", "settings"=>{"import_into"=>"product_list", "reset_all_absent"=>""}, "file"=>#<ActionDispatch::Http::UploadedFile:0x007f64e8ac1c10 @original_filename="product_list_template - floralora flowers part 1 to row 102.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"product_list_template - floralora flowers part 1 to row 102.csv\"\r\nContent-Type: text/csv\r\n", @tempfile=#<Tempfile:/tmp/RackMultipart20190326-23874-ncyq4a>>, "commit"=>"Upload"}
Completed 500 Internal Server Error in 28.8ms (ActiveRecord: 10.1ms)
Notifying https://notify.bugsnag.com of ArgumentError

ArgumentError (invalid byte sequence in UTF-8):
  app/services/upload_sanitizer.rb:16:in `gsub'
  app/services/upload_sanitizer.rb:16:in `strip_bom_character'
  app/services/upload_sanitizer.rb:10:in `call'
  app/controllers/admin/product_import_controller.rb:85:in `block in save_uploaded_file'
  app/controllers/admin/product_import_controller.rb:84:in `open'
  app/controllers/admin/product_import_controller.rb:84:in `save_uploaded_file'
  app/controllers/admin/product_import_controller.rb:14:in `import'
```

## Steps to Reproduce

1. Download [products-with-invalid-characters.csv.txt](https://github.com/openfoodfoundation/openfoodnetwork/files/3010693/products-with-invalid-characters.csv.txt) and change the filename ending from `.txt` to `.csv`.
1. Go to admin, products, import.
2. Upload the CSV file

## Context

Theresa tried to upload new products.

## Severity

S3. The upload feature is broken but fixing the encoding of the CSV file is a valid workaround.
https://csvimproved.com/support/questions-and-answers/916-save-a-csv-file-as-utf-8

## Your Environment

* Version used: v1.29.0 at https://openfoodnetwork.ca/admin/product_import

**Comment by sauloperez** [comment]
This is exactly what happened in Katuma 3 days ago

![Screenshot from 2019-05-23 12-12-48](https://user-images.githubusercontent.com/762088/58245708-b1c9df00-7d55-11e9-9c46-137c5a69dc35.png)

https://app.bugsnag.com/katuma/katuma/errors/5ce1784d9b9a8a0018307b97?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=30d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Bapp.release_stage%5D%5B%5D%5Bvalue%5D=production&filters%5Bapp.release_stage%5D%5B%5D%5Btype%5D=eq&event_id=5ce17a3c0039f28ef0190000
