### ISSUE TITLE
Shipping fee "per kg" are not updated when real weight is captured

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3661]
## Description
As a manager I have created a product "cheese (kg)" with a variant 1kg and a variant 0.5kg (500g).
When my customers order, they can then choose if they want 3kg, 1,5kg, etc.
The customer will pay a transport fee which is per kg based.

When the pieces of cheese are received, there is always a gap between ordered and delivered, as you can't be precise when you cut a piece of cheese ! 
So the manager when giving the cheese to the customer adjust the real weight in BOM. The price is automatically adjusted.

BUT the shipping fee which is per kg based is not...
Even if I try to go into the order and click on "update and recalculate fees", nothing changes.

## Expected Behavior
If there is a per kg shipping fee, if the weight of the order is changed, the fee should change accordingly.

## Actual Behaviour
It doesn't.

## Steps to Reproduce
1. Make sure you have a product "per kg" and a shipipng method fee "per kg"
2. Order that product.
3. In BOM page, change the weight, see the price changing, and save.
4. Go to the order, you see the shipping fee is unchanged. You can try to update and recalculate fee, nothing change.

## Animated Gif/Screenshot
Product for the test:
![Capture du 2019-03-27 15-13-32](https://user-images.githubusercontent.com/8135376/55083831-6f14bf00-50a4-11e9-8acc-18522210374c.png)
Order with 10ct shipping fee per kg
![Capture du 2019-03-27 15-14-09](https://user-images.githubusercontent.com/8135376/55083853-7a67ea80-50a4-11e9-9ebc-cf6cd9ccbca3.png)
In BOM before changing volume:
![Capture du 2019-03-27 15-14-54](https://user-images.githubusercontent.com/8135376/55083868-818ef880-50a4-11e9-9850-620c6778b577.png)
After:
![Capture du 2019-03-27 15-15-11](https://user-images.githubusercontent.com/8135376/55083887-8bb0f700-50a4-11e9-94fa-97a172c464e1.png)
Unchanged shipping fee:
![Capture du 2019-03-27 15-15-59](https://user-images.githubusercontent.com/8135376/55083913-966b8c00-50a4-11e9-9aaf-893d7157ae7d.png)

## Context
Reported by a user.

## Severity
The workaround is to capture a manual adjustment for every single order, which isn't an acceptable workaround. Only one user is concerned in France for now so I think it's reasonable to keep the severity to s3 and see with that user how they can handle...

## Your Environment

* Version used: 1.29
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu 18
* OFN Platform instance where you discovered the bug, and which version of the software they are using. French production

## Possible fix
Calculate on g based and not kg based the fee ?

**Comment by luisramos0** [comment]
it's broken in v2 as well: https://staging.openfoodnetwork.org.au/admin/orders/R474428075/edit
yeah, it's a border line s2, I'd keep it s3 if possible mostly because I dont think the fix will be easy... a good candidate to be fixed in v2 only.
