### ISSUE TITLE
Open links should appear before closed links in modal

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#367]
![image](https://cloud.githubusercontent.com/assets/2911176/6032739/9b008faa-ac60-11e4-8b0b-f38384b3319a.png)

This is a system-wide issue (on producers page, too). Angular developer job. Assign to Raf or Rob.

**Comment by myriamboure** [comment]
Seems to be done, but "shop for blabla products at" seems to be gone, will report as a bug.
![screenshot from 2018-03-04 19-40-58](https://user-images.githubusercontent.com/8135376/36949107-2f9975b0-1fe4-11e8-97ab-d5c886a32d23.png)
