### ISSUE TITLE
Spree_Prices rows being duplicated after migration

### ISSUE THREAD

**Issue by aidandunsdon** [openfoodfoundation/openfoodnetwork#370]
Hi  @RohanM   @kirstenalarsen  

We have managed to migrate 626 users, 135 enterprises, 1,900 products and variants and associated taxons from Stroudco to OFN and these seem to appear as expected in the admin UI. However there is an issue with the migration of the product prices. For each variant, our data migration tool populates the Spree_prices table with an amount derived from the Stroudco database and references it to the relevant variant_id in OFN. However, it seems that when the edit product form is opened in the Spree admin UI, a new master price (i.e. a row in spree_prices) is being automatically generated by Spree for each migrated variant even though one is already present. This means we end up with two master prices for each variant, one with the correct migrated value and one with a blank value. It is this blank one that is being picked up by the UI. Do you know if there is any way around this?

**Comment by aidandunsdon** [comment]
@RohanM   Is it OK to assign you this question? - not sure of the project  protocol on this! Sorry if it is not the usual thing - let me know thanks Aidan

**Comment by RohanM** [comment]
Hi @aidandunsdon,

My first guess would be that the site currency isn't matching the currency that prices are imported with (ie. `price.currency`). The site currency is found in `Spree::Config.currency` and can be modified by changing that variable (which is stored in the database).

If that doesn't solve the problem, it would be easier for me to help if I had a copy of the database after migration that's exhibiting the problem. If that happens, could you email me a database dump?

**Comment by aidandunsdon** [comment]
Hi @RohanM @kirstenalarsen That seems to solve the problem - thanks!
