### ISSUE TITLE
[Spree 2.1] Upgrade to Spree 2-1-0

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3704]
The initial analysis/estimation is in #3565, this epic will contain all tasks and subepics for the upgrade to 2-1-0 much like #2109 for spree 2-0-4.

#### Relation to Rails 4 Upgrade
Spree 2-1-0 runs on Rails 4.0.0 and this epic should include all work related to the upgrade of OFN to rails 4 as well.

#### Relation to Ruby 2.2 Upgrade
#2891 is the issue that represents the work to upgrade OFN to Ruby 2.2 (although some rails upgrade discussion happened there). OFN 2.0.0 runs on ruby 2.1.5 and spree 2-1-0 will run on ruby 2.1.5 as well, so 2891 is not directly connected to this epic should remain open.

#### The upgrade branch
The [2-1-stable branch]([ofn/2-1-stable](https://github.com/openfoodfoundation/openfoodnetwork/compare/2-0-stable...2-1-stable?expand=1)) is based on spree 2.1. There are some temporary fixes on it right now so that we can see the specs running.

**Comment by Matt-Yorkley** [comment]
Looks like the `2.1` stable branch of the `better_spree_paypal_express` gem requires `spree_core` `2.1.1` instead of `2.1.0`...

**Comment by luisramos0** [comment]
that is correct, I think the rule is that x-y-stable branches represent version x.y.z whwere z is the last/max stable version. so I'd expect 2-1-stable better_spree_paypal_express to depend on spree versions as high as possible, possibility the latest 2-1-X version

**Comment by mkllnk** [comment]
I'm trying to upgrade Ceres Fair Food to Rails 4 and ran into an incompatibility between Rails 4.x and Ruby 2.3. The newer Ruby version introduced a new method and which breaks a `respond_to` call in Rails.  https://github.com/rails/rails/commit/a98475c2df8ab7d7d353cb29bb3f201c4c7eb9d1

I'm trying to solve this by "patching" Ruby in an initializer:
```rb
# Ruby 2.3 introduces the method Hash#to_proc.
# Unfortunately, Rails 4 assumes that hashes don't respond to that method.
# https://github.com/rails/rails/commit/a98475c2df8ab7d7d353cb29bb3f201c4c7eb9d1
# Rails 5 is patched.
Hash.send(:remove_method, :to_proc)
```

The other option would be to patch Rails.

**Comment by luisramos0** [comment]
great finding Maikel!
are you sure we will bump into that as well? if no, let's wait until we have that problem, otherwise, let's get have a PR :heart:

**Comment by mkllnk** [comment]
I don't know if we will bump into it. I just wanted to share it here just in case. The error message will be: `ArgumentError: wrong number of arguments (given 0, expected 1)`

**Comment by luisramos0** [comment]
great, thanks!

**Comment by luisramos0** [comment]
Moving to ready to go as we will be merging the branch to master soon.

**Comment by RachL** [comment]
@luisramos0 I see there are two issues still attached here and not merged yet. Do we need to keep track of them in the epic? If so I would moved it back to test ready. Otherwise we can close it an follow the issues as part of the general workflow now that everything is in master?

**Comment by luisramos0** [comment]
yeah, we can keep them in this epic but I am closing the epic now anyway. It's master now so any issue with be a normal issue.
