### ISSUE TITLE
Free Trial message on website

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#371]
We agreed to put the following message up at the top on the homepage.  (This is part of a bigger wordpress editing job that Mags has agreed to take on - see Word doc "Proposed changes to OFN UK website home page text")
Anyway here is the wording for the top of the homepage:

> Until July 2015 several UK food hubs and producers are using this Open Food Network (OFN) software on a free trial basis.  We are also setting up a co-operative structure which will coordinate the development of OFN in the UK.  This cooperative will be funded by contributions from OFN users like you.  If you would like to help set up this co-op please contact hello@openfoodnetwork.org.uk

**Comment by kirstenalarsen** [comment]
Hi Nick, are you abel to add labels (so add the label 'uk' to your issues) or you don't have enough permission to do that?

**Comment by NickWeir63** [comment]
Hi Kirsten, i dont think i have permission - but that is because i cant see an option to add labels - where should i see that option?

**Comment by kirstenalarsen** [comment]
on the right hand side by the comment?

**Comment by NickWeir63** [comment]
yes i can see there that you have added the UK label but there are no options for me to add more labels.  who do i need to ask to get permission?

**Comment by kirstenalarsen** [comment]
i think it will be a @rohanm or @oeoeaio thing, but let me have a quick look and see if i can do it . .

**Comment by NickWeir63** [comment]
thanks - i will be off line for a few hours now

**Comment by kirstenalarsen** [comment]
ok, I can't do it . . but looks like @pmackay is an owner, and I think he's 'active' right now - Paul are you able to either
a) add Nick, Fifemags and Alexis (not sure if she's already signed up on github nick?) to the Developers group
OR
b) create a Testers group and add them to that
. . so they can label issues and assign themselves (or others) to them?

**Comment by kirstenalarsen** [comment]
no worries. taking to github like duck to water :)

**Comment by pmackay** [comment]
I've sent invites to @NickWeir63 and @FiferMags. 

@kirstenalarsen pop a photo on your profile, helps to match people :)

**Comment by kirstenalarsen** [comment]
done

**Comment by NickWeir63** [comment]
Paul - please can you give Mags the login details so that she can update the UK website with this message.  thanks N

**Comment by pmackay** [comment]
@kirstenalarsen @RohanM About the homepage, @NickWeir63 has suggested inserting a message above the list of hubs. Would it be ok if I insert another partial for highlight messages that could be configured by locale? Or do you have any other suggestions? Have you discussed how custom site messages such as this could be handled easily by one site in a way that doesnt affect other installations?

**Comment by kirstenalarsen** [comment]
We had a quick discussion about this this week, fine if you want to do a banner / flash message that appears at the top of the hub list page (and user can close) - like happens on the shop. Would that work?

**Comment by NickWeir63** [comment]
This sounds ideal - thanks.  Can we do it now?

**Comment by pmackay** [comment]
@kirstenalarsen do you mean something similar to the shopfront (open/closed) messages? If so, I cannot see anything like that for the overall site. Is there any place where sitewide messages can be stored? If not, where would they go in the admin preferences? 

There is a CMS admin tab under Configuration, but is the CMS not being used?

**Comment by RohanM** [comment]
@kirstenalarsen Could you attach a screenshot of the banner/flash message that you mentioned as appearing on the shop? I'm not sure which one you mean.

@pmackay That's correct, the CMS is not currently in use. Your idea of configuring that message by locale sounds good to me for the moment. It'd be great to have something like a CMS for some of these site messages, but I think we'd want to spend a bit more time designing that kind of feature - not suitable if you need something up quickly.

**Comment by summerscope** [comment]
hi @NickWeir63 @pmackay sorry for being late to the party on this issue. please see my feedback on paul's pull request here: https://github.com/openfoodfoundation/openfoodnetwork/pull/494 and let me know your feedback :)

**Comment by pmackay** [comment]
I'm not sure how important @NickWeir63 felt this messaging was for the site. Its taken longer to put together cos I'm on and off the work. 

I dont mind waiting for the wider design work to finish, but @RohanM didnt mention this when we discussed how to do this technically - when did your work start @summerscope? Would have been handy to know earlier and save the time/cost of doing it, given very limited resources available to us :)

**Comment by NickWeir63** [comment]
Thanks @summerscope - yes we can wait.  I am happy to skype on this but would probably be out of my depth - maybe best for me to leave it to @pmackay but let me know if i can contribute at all
