### ISSUE TITLE
[Subscriptions][Stock] You can create a subs with a product that has not enough stock

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3713]
## Description
Nothing prevents a producer today to create a subscription with more item than his product has in stock.

At least you should see a message, and the confirmation email towards the consumer should mention it. Otherwise you end up with a negative stock level.

## Steps to Reproduce
1. I've set up an order cycle with a product that has a stock level of 45
2. I've set up a subscription for 50 items of this product.
3. The buyer received a notification and a confirmation email confirming the order of 50 item
4. The producer ended up with a negative stock level.

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/30f950fd-760c-4140-babf-b5e138ef3749)

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/40fd465f-1121-4a6b-89a9-69020363141c)

## Severity
bug-s4: it's annoying, but you can use it

=> I'm guessing most people use subs with "on demand" settings

## Your Environment
* Version used: v1.30
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Ubuntu 18.10
* OFN Platform instance where you discovered the bug, and which version of the software they are using. Katuma staging

**Comment by luisramos0** [comment]
S4: another candidate to be moved to bug backlog @RachL ?

**Comment by RachL** [comment]
@luisramos0 I would love some feedback from others on this ping @lin-d-hop @kristinalim  . If most people put their product to on demand, I guess this is s4. However if people do set stock levels, I believe we have an s3 / almost an s2. 
In a regular order, we prevent people from ordering more than the producer has in stock. I don't understand why this would not be a problem with a sub. My guess is that hub and producer will think that the stock is manage the same across the two type of orders, thus they won't pause a sub or update stock levels. As a result, in some cases they might end up with an order they cannot fulfill.

**Comment by luisramos0** [comment]
yeah, I think I have changed my mind. This is S3 and needs to be fixed now. I'll have a look at this one and 2505 and 2507 this week.

**Comment by luisramos0** [comment]
hey @RachL I cant replicate this one.

I have a product with 5 in stock.
I create the subscription with 10 items. When I create the subscription maybe the user should be warned that the stock is not enough not even for a single order (that could be a low priority bug).
but when the real orders I generated for the customers, I get the correct emails: there are two OCs in the subscription so I get one email saying insufficient stock (5 only) and another saying out of stock.

Are we doing something different?

**Comment by luisramos0** [comment]
is it ok if I move these bugs to test ready for validation @RachL ? or should we keep the conversation in  Dev Ready column (as you prefer).

**Comment by luisramos0** [comment]
what I have written above about this issue is still valid but I just realized that the "low priority bug" I mention above is a variation of #2505: if the orders are not created yet, nothing happens with the stock levels (this is the low priority bug I mention above), but, if the orders in the subscription are already created and the insufficient stock or out of stock product is added to the subscription, the product is added to the orders without stock verification, this case is #2505

**Comment by RachL** [comment]
Yes you are right, I cannot reproduce it either. Just tested on Katuma's staging with Garlic:

![image](https://user-images.githubusercontent.com/6525576/59102336-0d869180-892c-11e9-8979-03a7fa945ad9.png)

> is it ok if I move these bugs to test ready for validation @RachL ? or should we keep the conversation in Dev Ready column (as you prefer).

Yes that's the clearest way to do it, thank you!

Closing this!
