### ISSUE TITLE
[Spree Upgrade] Inventory cannot update price

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#3715]
## Description

Tamar Valley Food Hub (TVFH) has permission to add Berio Mill to their inventory. When I open TVFH inventory I see the list for Berio Mill correctly. However when I try to update the price I get the following error:
"I couldn't get authorisation to save those changes, so they remain unsaved."

## Expected Behavior

The changes to the price in inventory should save correctly and then should follow through to a change in price in the shopfront - as they currently do in v1.

## Actual Behaviour

Error and no price update.

## Steps to Reproduce

1. Open Inventory for TVFH on FR staging
2. Update a price eg Cornish Ale Mustard for Berio Mill
3. See the error "I couldn't get authorisation to save those changes, so they remain unsaved."
4. Price is unchanged in the shopfront

## Animated Gif/Screenshot

Sorry the gif is so sloooooooow

![inventory](https://user-images.githubusercontent.com/8669848/55811959-f2410680-5ae1-11e9-9506-04a15e820621.gif)

## Severity

S2
## Your Environment

* Version used:
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu Desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using. V2 on FR staging

**Comment by lin-d-hop** [comment]
In fact this is all Inventory changes for this pair (TVFH and Berrio Mill). More gif:
![inventory2](https://user-images.githubusercontent.com/8669848/55812239-87dc9600-5ae2-11e9-85d8-f273eb3f1d93.gif)

I'll do more testing with other ERs

**Comment by luisramos0** [comment]
the inventory page validates the full inventory on any change, so if there's one single variant broken, the page will be completely broken... it's unfortunate for the user but it's good to catch all bugs in the page...

this is a case of spoiled "Sponge Cake" :-) It's a deleted variant that is being shown in the inventory.

I'll create a PR...

**Comment by luisramos0** [comment]
The deleted variant was not shown in the inventory but when the inventory data was being saved, the authorization procedure was checking this deleted variant and failed. Fixed in #3747

**Comment by sauloperez** [comment]
Good work @luisramos0 !
