### ISSUE TITLE
Reduce / remove Supplier list in Order Cycles summary screen

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#373]
The Order Cycles summary page is getting out of control now that we have Order cycles with many suppliers. Need to remove or reduce it to make this table simpler and more vertically compact.

Could reduce by making it a pop-up / hover list on mouse-click, rather than displaying all?

![image](https://cloud.githubusercontent.com/assets/2911176/6076086/50e25c9a-ae32-11e4-9e8b-0d4346e0947f.png)

**Comment by victornava** [comment]
Done https://github.com/openfoodfoundation/openfoodnetwork/pull/414

**Comment by victornava** [comment]
Ignore the comment above. It is related to something else.
