### ISSUE TITLE
Missing translation when trying to remove a fee from an OC

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3732]
## Description
When you add a fee to an OC, the "remove" link is not translated.

## Steps to Reproduce
1. Log in as a producer or a hub or a super admin
2. Go to /admin/order_cycles
3. Create on order cycle and add fees to it
4. You will the the "remove" link

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/55971505-e724dc80-5c81-11e9-890e-01c5dce84ec0.png)

## Severity
bug-s3: a feature is broken but there is a workaround

* Version used: v1.29
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop Ubuntu 18.10

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Failing Subs](https://trello.com/c/eBNWazqb/426-failing-subs)
