### ISSUE TITLE
Admin logo

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3733]
## Description

The logo in the admin area is set to the Spree logo by default. Some instances have manually hacked this to show the OFN logo instead of Spree, and it's much better! 

There's a Spree::Config preference called: `Spree::Config[:admin_interface_logo]` which has a default value of `admin/bg/spree_50.png`. We can set it by default to the OFN logo, and we could optionally allow instances to set or upload a custom logo.

## Expected Behavior

Effective branding!

## Actual Behavior

Promoting Spree instead of OFN?

## Steps to Reproduce

You can take a look at the admin area on UK production and French production to compare. Alternatively if you'd like to hack _your_ instance's admin logo, the process looks like this (if you have SSH access):

1. `sudo su openfoodnetwork`
2. `cd /home/openfoodnetwork/apps/openfoodnetwork/current`
3. `bash -lc "bundle exec rails c"`
4. `Spree::Config[:admin_interface_logo] = 'ofn-logo.png'`

I'm not sure how the routing works for this exactly, but the above will use the logo found under: `app/assets/images/ofn-logo.png`.

## Animated Gif/Screenshot

![Screenshot-2019-04-11-19-01:53.png](https://images.zenhubusercontent.com/58278b61e40e5714b1702bca/a8671cab-efd8-4eca-b4df-9d070bf67840)

## Severity

s5?

## Possible Fix

There's lots of options. We could just set in an initializer, or make a fancy custom image upload thing in the content config UI like we have with other custom logos.

**Comment by lin-d-hop** [comment]
Let's decide on the right approach and spec if clearly for the dev hack!

**Comment by Matt-Yorkley** [comment]
Just throwing it out there as a potential idea :+1:

**Comment by lin-d-hop** [comment]
Tis a great potential idea! Spec spec spec :-D

**Comment by Matt-Yorkley** [comment]
I outlined 2 rough options for implementation: 

I think the **first option** is probably a single line of code in an initializer, so not exactly an interesting challenge but maybe a quick win. Or maybe quick wins are good if we have competing teams trying to score points?

The **second option** involves replicating the logo upload UI we created for the frontend logo and hero banner, and doing either of these: 

- applying the path of the uploaded file to the corresponding Spree::Config setting, which would probably require an override in `app/models/spree/app_configuration_decorator.rb`, OR:
- de-defacing the admin layout and using a new preference added in `app/models/content_configuration.rb`. This would be a much nicer task if we de-defaced the admin layout view before the devhack, and is probably the better choice.

**Comment by sauloperez** [comment]
> de-defacing the admin layout and using a new preference added in app/models/content_configuration.rb. This would be a much nicer task if we de-defaced the admin layout view before the devhack, and is probably the better choice.

Is this going to happen though? I feel like we have lots of open fronts.
