### ISSUE TITLE
[v2] Not authorized to access reports

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3735]
## Description
I've created a producer profile, but I'm not authorized to access the report menu.

With super admin, no problem.

## Steps to Reproduce
1. Create a new profile
2. Setup an OC with a product
3. Make an order
4. Go to reports to see data, you will be redirected to the home page with an authorization failure

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/55995502-f1ac9980-5cb4-11e9-9c4b-8128531a6ce9.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Windows 10

**Comment by luisramos0** [comment]
@RachL I cant replicate this locally or in stg FR. 
can you pls add more details? Maybe tell me the user so I can check the DD?
is it reports or is it a specific report?

**Comment by RachL** [comment]
@luisramos0 I can't replicate as well.... it happened twice for me with a fresh producer account. Closing this and I will reopen it if we can replicate.

**Comment by luisramos0** [comment]
:-( there's probably a bug here...
