### ISSUE TITLE
Update user guide for v2

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3739]
## Description

The release of version 2.0.0 will need some updates of the user guide. Let's collect them here.

- [ ] Shipping category is now mandatory
- [ ] Removing shipping fees
  > If you delete a shipping fee and look at the order details again, the shipping fee will re-appear. You can use this behaviour if you want to re-calculate the shipping fee. If you don't want to charge a shipping fee you can set the amount of the shipping fee to `0`.

This issue has been split from #3598.

**Comment by sigmundpetersen** [comment]
Hey @RachL should we put this somewhere else so we don't forget it?

**Comment by RachL** [comment]
@sigmundpetersen I'm actually closing it. This is not a task for me but for Louise who will lead the english user guide version. It is recorded in the ATAP tasks.
