### ISSUE TITLE
Scrolling w. modals on small screens (smaller than 640px)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#374]
Launching modal causes background page to scroll to top (so you loose whichever hub you had expanded to click on a modal)

**Comment by kirstenalarsen** [comment]
@sstead could you check and confirm whether this is still a problem? If not, close :)

**Comment by sstead** [comment]
If my window is tiny, then yes, this is still a problem.
![image](https://cloud.githubusercontent.com/assets/10843056/10091047/9af6c60c-6379-11e5-88cf-32539373ee99.png)

**Comment by myriamboure** [comment]
Re-tested and this is not an issue anymore https://www.useloom.com/share/4e3744debfee4ff4b0f51ad0a081d08a so closing.
