### ISSUE TITLE
Create a Github Deployments API integration

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3740]
### Description

We could integrate our deployments with the Github Deployments API. This would give us a nice view of the deployment status of our servers inside the Github UI, and would show the deployment status clearly at the bottom of each PR:
![Screenshot-2019-04-11-18-03:22.png](https://images.zenhubusercontent.com/58278b61e40e5714b1702bca/3c41d517-aa11-44c8-9f9a-5d265726ae65)

### Expected Behavior

Deployment statuses are reported to the Github Deployments API, shown in PRs and listed in the deployments page: https://github.com/openfoodfoundation/openfoodnetwork/deployments

### Context

Planning potential mini-projects for the UK Devhack.

### Plan

- Check out the docs for the Deployments API: https://developer.github.com/v3/repos/deployments/
- Test some simple API calls to update the status of different servers, probably using `curl`, and make sure it works correctly
- Add the API call into an Ansible task in `ofn-install`, to be triggered after a deployment is completed

**Comment by georgethoppil** [comment]
@Matt-Yorkley this looks like a fun ticket. Is this something I can look into as well?

**Comment by Matt-Yorkley** [comment]
Sure! I think it'll need a dev with admin access to set up a bot-user on the repo with a restricted key that has access to modifying the deployments notifications through the API (and nothing else), with an access token that can be used programmatically. I'm a bit hazy on the details; I posted this in 2019, that was like 30 years ago... :sweat_smile:

**Comment by georgethoppil** [comment]
@Matt-Yorkley awesome thanks :) 

1) Don't we have the [ofn-deployments](https://github.com/ofn-deployments) user that we can use for this?

2) Forked `ofn-install` and I installed all the pre-requirements on the readme page.  I am trying to install the vm using vagrant and I am able to `vagrant up` but errors out on `ansible-playbook site.yml --limit vagrant`. Any ideas on this?

```
ERROR! the role 'geerlingguy.security' was not found in /Users/georgethoppil/Desktop/ofn-install/playbooks/roles:/Users/georgethoppil/Desktop/ofn-install/community:/Users/georgethoppil/Desktop/ofn-install/roles:/Users/georgethoppil/Desktop/ofn-install/playbooks

The error appears to be in '/Users/georgethoppil/Desktop/ofn-install/playbooks/provision.yml': line 33, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
    - role: geerlingguy.security
      ^ here
```

**Comment by RachL** [comment]
@openfoodfoundation/core-devs do we still need this one?

**Comment by mkllnk** [comment]
No. Could be cool but we have another way of staging now. Closing.
