### ISSUE TITLE
Error 500 trying to create a product on staging FR

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3754]
## Description
As super admin or admin, creating a new product leads to an error 500

EDIT: After adding payment and shipping methods to "Rachel's v2 farm" it went ok. so I guess this is not s1. But I guess a producer should be able to create products without it, right? Or at least getting a clean error message? I will leave "Rachel's producer untouched so we can reproduce this"

## Steps to Reproduce
1. Login as superadmin on https://staging.openfoodfrance.org/
2. Try to create a product with the producer "Rachel v2 farm" or "Rachel's producer"
3. Fill in all the fields including a tax category different from "none"

## Animated Gif/Screenshot
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/4c3400c6-866a-4e98-85f8-2bca9668c303)

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
* Version used: v2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop Unbuntu 18.10
* OFN Platform instance where you discovered the bug, and which version of the software they are using. Staging FR

**Comment by luisramos0** [comment]
@RachL I cant replicate this one.
I could create a product in "Rachel's producer".

can you try again and share a screenshot of the details of the product before creating. Must be some field in the product form...

**Comment by luisramos0** [comment]
assigning S3 as it looks like it's related to some field on the product create page. we can move to s2 when we find out what it is exactly.

**Comment by RachL** [comment]
@luisramos0 couldn't replicate myself either, so closing this

**Comment by luisramos0** [comment]
ok, thanks!
