### ISSUE TITLE
Why /map is so slow?

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#3756]
## Description
I'm filing this using the bug template, not sure if you consider performance stuff as a bug or something else. Sorry if it's the wrong place and sorry if there is any other issue/pr addressing this.

Basically I'm wondering why `/map` is so slow to load:
https://openfoodnetwork.org.uk/map 52294 ms
https://app.katuma.org/map 19677 ms

Any insight?

## Expected Behavior
Be faster? :grimacing: :sweat_smile: 

## Actual Behaviour
Sloooow.

## Steps to Reproduce
Visit `/map` on any OFN instance.

## Animated Gif/Screenshot
![](https://media3.giphy.com/media/lJnAXeJO8tE7E37mxq/giphy.gif?cid=790b76115cc2dbd141746f644d6db532&rid=giphy.gif)

## Context
:grimacing: 

## Severity
I'm not sure, feel free to change it.

## Your Environment

* Version used:
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Arch Linux desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using: I tried on Katuma and UK

## Possible Fix
:sunglasses:

**Comment by Matt-Yorkley** [comment]
Bumping this to an S3 because it's really bad...

**Comment by sauloperez** [comment]
All I can tell is that we load all enterprises to be displayed on the map and that it is indeed inefficient.

**Comment by luisramos0** [comment]
from @RachL testing notes on #3801 "Map is as fast as lightning!!!"
great stuff really from @Matt-Yorkley 👏
