### ISSUE TITLE
Error 404 from missing CSS file

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3759]
## Description

One of our CSS files is not set up correctly, and is reported as missing and generating errors:

![Screenshot-2019-04-28-17-49:06](https://user-images.githubusercontent.com/9029026/56867527-09d32700-69de-11e9-9fe3-c56628b8a9e3.png)

## Expected Behavior

CSS files should load without errors. 

## Actual Behaviour

See above.

## Possible Fix

Fix some of the CSS added here: https://github.com/openfoodfoundation/openfoodnetwork/commit/e1953c279b3176c9836f51e4c0991441cd409ae9#diff-dd9c0e35ddeedf7f7af04fc80c055d9d

**Comment by sauloperez** [comment]
This seems to keep happening @Matt-Yorkley . It was deployed yesterday at 12:48PM CEST but I still see it in the logs

![Screenshot from 2019-08-06 10-31-39](https://user-images.githubusercontent.com/762088/62524230-87a49b00-b835-11e9-8953-02ecf48b650d.png)

**Comment by Matt-Yorkley** [comment]
Just had a look through the logs for UK prod. I see the error around a hundred of times per day last week, until yesterday around the time `v2.2.2` was deployed, with the last one being at `Aug 05, 2019 at 11:37:10.000` None since then.

**Comment by sauloperez** [comment]
No logs found regarding this so fixed!
