### ISSUE TITLE
Change hub notification message on the front page has a type 'remove any items in you cart' - needs to be 'your cart'

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#376]
Warning message triggered when you have items in your cart and you change Hubs, has typo . .

![image](https://cloud.githubusercontent.com/assets/2911176/6076588/a4e0c32a-ae39-11e4-98ca-7be718d378e7.png)

**Comment by livcg** [comment]
I believe the fix has been merged and looks correct on staging:
![screen shot 2015-03-06 at 12 24 32 pm](https://cloud.githubusercontent.com/assets/6513927/6518579/ec6e6d82-c3fb-11e4-985d-a27aae53d9db.png)  I'll reassign this to Kirsten for now.
