### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3760]
Editing @Matt-Yorkley's original epic with the outcomes of the performance session at #gathering19

Performance is a feature.

This feature has taken a high priority agreed at #gathering19

Success Criteria for Performance:
- Pages will load in under 5 seconds. 3-5 is acceptable.
- OFN supports unlimited enterprises with 10,000 products. 

Priority pages (in order of decreasing priority)
- /maps - Merged
- /shops - Awaiting PR merge and release
- /producer - Awaiting PR merge and release
- /groups - Awaiting PR merge and release
- /admin/ edit order cycles - Spike
- /enterprise/shop - Dev ready
- /reports/orders+fulfillment - Dev ready
- /super-admin/enterprises
- /super-admin/order-cycles
- /bom - Spike
- /admin/products
- /admin/enterprises - only a problem for hubs with large numbers of producers
- /checkout

**Comment by RachL** [comment]
@Matt-Yorkley thanks! There already was an epic but the title was not clear. So I've put all the issues of the previous one in yours and left only the epic in the bugbacklog. Ping @daniellemoorhead I know you wanted to have a look on those issues as well and grouping them. Does this make any sense?

**Comment by Matt-Yorkley** [comment]
Great! Yeah I think that makes more sense. The old epic #3493 was more like a bug report. It's already s2 for France, and I've added UK to the title of the issue, because it's an s2 for us as well. 

With the new monitoring we've added in the last week we can quite safely say the performance issues with the above pages are the cause of the downtimes, so now we have a clearer idea on how to proceed.

**Comment by RachL** [comment]
@Matt-Yorkley yes the new monitoring looks great! It is only provisioned in UK for now right?

**Comment by Matt-Yorkley** [comment]
![coming-soon](https://media.giphy.com/media/3o72FkiKGMGauydfyg/giphy.gif)

**Comment by sauloperez** [comment]
IMO we should also consider creating a specific performance backlog because lots of unrelated issues and epics will start soon popping up, as suggested by @luisramos0

**Comment by luisramos0** [comment]
Awesome, in the gathering we should scope this so that we know what we want to address in the short term and what is not essential. Performance is as infinite topic and we will only be able to address a few things in the short term.

**Comment by Matt-Yorkley** [comment]
I did some investigation on what it would take to fix `/shops`, `/producers`, and `/groups`. As per luis's suggestion, we can move the shopfront search to an API endpoint and make it much nicer. The main blocker there is the geocoding where we show shops near a geographic location. I this is currently done on the client-side via javascript libraries. If we migrate the searching to the server-side we would also need to implement the geocoding features in Rails instead of javascript.

On the plus side I think there may be some alternate ways we can get some quick wins in drastically improving `/groups`, and substantially improve `/shops` and `/producers` without doing the longer-term idea of a search and filter rewrite.

**Comment by lin-d-hop** [comment]
I am closing this Epic.
We've done amazing performance work and the system has coped over COVID. Future performance work can be re-incepted. We can dig this out then :-)

**Comment by luisramos0** [comment]
:+1: this was a true "epic", well done team!
