### ISSUE TITLE
Can't use S3 only for backups without using it for image storage too

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3766]
## Description

When I provisioned Katuma with the latest `ofn-install` and v1.30.0 few errors related to Paperclip starting popping up such as

![Screenshot from 2019-04-30 21-39-21](https://user-images.githubusercontent.com/762088/56988489-742bc900-6b90-11e9-84ed-9dc0f9253a95.png)

The actual problem here is that katuma does not use S3 as image storage, only as backup storage. 

I tried disabling `use amazon s3 for images` from `/admin/image_settings/edit` with no success. Still the following line

https://github.com/openfoodfoundation/openfoodnetwork/blob/88cbf5bd36ab5b633ffc3f76efb41822072146b9/config/initializers/spree.rb#L28

will always get evaluated taking precedence over the UI.

## Expected Behavior

Images should be stored in the server and not in S3. Specifically, `Spree::Image.attachment_definitions[:attachment][:storage]` should return `nil` from a rails console in production. See https://github.com/openfoodfoundation/spree/blob/step-6a/backend/app/controllers/spree/admin/image_settings_controller.rb#L55 for details.

## Actual Behaviour

Paperclip is configured with S3 storage thus all image URLs are resolved assuming so and fail due to missing configuration options.

## Steps to Reproduce

1. tail -f log/delayed_job
2. enqueue a `ProductsCacheIntegrityCheckerJob` with valid settings like distributor_id: 93,
order_cycle_id: 505
3. The log will show a message like 

```
Job ProductsCacheIntegrityCheckerJob (id=323401) FAILED (6 prior attempts) with ArgumentError: missing required :bucket option
```

## Context

We never enabled backups in Katuma until now.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: v1.30.0, ofn-install `master`
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using. 

## Possible Fix

#3764

**Comment by sauloperez** [comment]
I managed to get over it by simply modifying the initializer to set `config.use_s3 = false` and then restarting both unicorn and delayed job but I'll share a patch ASAP.

**Comment by sigmundpetersen** [comment]
Hey @sauloperez isn't this related and fixed by #3764 ?
Just checking we are not doing double work :)

**Comment by sauloperez** [comment]
Oh thanks! Yes, I do think so. I'll link both.

**Comment by sauloperez** [comment]
Retried all remaining (17) failed jobs and all seems stable now.
