### ISSUE TITLE
Shopfront corrects but doesn't notify when Orders exceed the 'on hand' quantity (confusing).

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#377]
In the shop, if I try to buy 5 of an item, and there is only 2 'On Hand', it won't let me increase the number past 2. (maybe there should be an alert telling the customer why the number can't be increased... 'only 2 remaining')

If you try to increase the number in 'edit cart' section, you'll be able to increase the number, but once you click 'update' you get this message.... not a very user friendly message (something like, "Product X only has 2 units remaining in stock", would be better)

As you can see in the image above, it doesn't automatically reduce the order to the On Hand max (in this case 2), but it remains at the exceeding amount, calculating the cost based on that too. Maybe this should be the same as in the store (can't increase number, with alert telling them why).

**Comment by sstead** [comment]
Sorry, can't insert image for some reason.

**Comment by RohanM** [comment]
Additionally, when a customer is purchasing the last of the stock of an item, they get an "insufficient stock available" message against the line item, even though there is enough stock to fulfil their order.

**Comment by RohanM** [comment]
Fixed with #828
