### ISSUE TITLE
Missing translation on shopfront / insufficient stock

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3772]
## Description
When a product has less stock than the buyer ask for, a modal displays with a message. This message is not translated.

## Steps to Reproduce
1. Go for example on https://www.openfoodfrance.org/hub-demo-open-food-france/shop
2. Put 10000 on the first product as a quantity
3. See message

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/57070876-0e972400-6cd9-11e9-9768-980dda0c7dfb.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v1.30
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Both

**Comment by luisramos0** [comment]
this has been fixed in v2.
moving to test ready to be verified by a tester.

**Comment by RachL** [comment]
Yes it is!

![image](https://user-images.githubusercontent.com/6525576/58793623-cda36f80-85f6-11e9-82d9-fa7f845eb7b7.png)


Closing
