### ISSUE TITLE
Missing Catalan translation for order cycle closing date

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3773]
## Description

I noticed that it is only Catalan the only one missing the translation for the `enterprises_next_closing` translation key in https://app.katuma.org. For unknown reasons, we are not using the https://github.com/derekprior/momentjs-rails/blob/master/vendor/assets/javascripts/moment/ca.js locale file.

It seems that the Catalan has been available since 2012 and our `Gemfile.lock` specifies the latest version so there must be something preventing moment from picking the right locale file.

## Expected Behavior

A shops page should show "Tancament de la comanda següent en X dies".

## Actual Behaviour

It shows "Tancament de la comanda següent in 3 days" instead

## Steps to Reproduce

1. navigate to https://app.katuma.org/shops#/
2. Click on a shop's name

If no shop is currently open, you can open an order cycle on staging/development environment and navigate to its shop.

## Animated Gif/Screenshot

![Screenshot from 2019-05-02 14-51-58](https://user-images.githubusercontent.com/762088/57076403-e106a680-6ce9-11e9-9a18-017849b4f5d1.png)

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v1.30.0
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu
* OFN Platform instance where you discovered the bug, and which version of the software they are using. 

## Possible Fix

We first need to determine why momentjs is not picking the `ca` locale.

**Comment by RachL** [comment]
hey @sauloperez we can close this one now right? Thanks to https://github.com/openfoodfoundation/openfoodnetwork/pull/5554

**Comment by sauloperez** [comment]
Yes! Fixed!
