### ISSUE TITLE
Release v1.31.0 Bananas

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3775]
release draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-aa6c18f3ecf379330d0d

this is staged in uk staging: https://staging.openfoodnetwork.org.uk

**Comment by RachL** [comment]
@luisramos0 I found 2 things that are quite important and maybe linked to the release:
1. I was unable to link a stripe account to a new enterprise. Couldn't find a previous test account with stripe on it, so did not test on existing account.
2. Image upload to product dose not work.

Testing notes : https://docs.google.com/document/d/1CvKT7StHuroZaIYaaSj8Ex_a1KfQ5rDTTeNITxaRZFs/edit#

**Comment by luisramos0** [comment]
1. it will be related to the stripe config on the server
2. it will be related to the s3 config on the server

@Matt-Yorkley would be able to have a look?

**Comment by Matt-Yorkley** [comment]
Images are now working, it was unrelated to the release. I think the Stripe issue is similar, it needs reconfiguring on UK Staging.

**Comment by luisramos0** [comment]
agreed with @RachL to unstage v1.31 from uk staging so we can test #3717 
we can revert uk staging or other staging server to v1 to test stripe in v1.31

**Comment by RachL** [comment]
Tested strip on Fr staging:
- I created a new enterprise and managed to connect the stripe account
- I opened an order cycle, and managed to pay on order through stripe

Uploading images however is not working anymore on Staging Fr. Maybe this is just a staging problem?

**Comment by sauloperez** [comment]
@RachL approved it in https://openfoodnetwork.slack.com/archives/C4NDJT3FY/p1557133092126200 so I'm proceeding with the final publication and deploy to Katuma staging. It is needed to get everything ready to deploy v2.0 tomorrow.

**Comment by sauloperez** [comment]
## Deployment

- [ ] AU
- [ ] DE
- [ ] BE
- [ ] FR
- [ ] ES
- [ ] NO
- [ ] UK
- [ ] CA
- [ ] US

**Comment by RachL** [comment]
US and Norway are the last ones. US is schedule for tomorrow. For Norway ping @sigmundpetersen . I guess it is safe to close this now.

**Comment by sigmundpetersen** [comment]
No active hubs on Norway atm, so either way it's not critical. We have to figure out if a deployment on a non-ofn-install breaks Bugsnag (same discussion as [last release](https://github.com/openfoodfoundation/openfoodnetwork/issues/3691))
