### ISSUE TITLE
Make all map icons green

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3777]
## Description
Many new users to OFN ask why the map icons are two different colours and ask why so many shops on OFN are closed. They ask what is wrong with the software if there are a lot of users that don’t use the platform. And they ask why their own shops appear closed when they are open. This is an annoying question for administrators and onboarders to have to answer all the time.

The current colors are based on this diagram:
![image](https://user-images.githubusercontent.com/6525576/57096548-dcf07e00-6d15-11e9-882b-992fb57dbc75.png)

**- As a:** non logged in user (or any logged in user - so anyone basically)
**- On page:** /map
**- I want to be able to do:** see all icons in green

## Acceptance criteria

Visiting /map I should only see green icons. No more white or red.

**Comment by eelcodevlieger** [comment]
One issue is that there is currently no green Hub icon. I have created this asset by editing the red Hub icon.

**Comment by eelcodevlieger** [comment]
![image](https://user-images.githubusercontent.com/44651943/57181382-d0d9fd00-6e8a-11e9-81e9-22c861869f12.png)
