### ISSUE TITLE
As a User w. Hub, when I create a Producer 'sells' attribute should be 'none' (currently 'any') 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#378]
Note, as a User w. Hub, when I create a Hub should be 'any' (is correct)

**Comment by RohanM** [comment]
We tried creating a Producer from the Admin page and also from the public registration page but couldn't reproduce the problem.  From the Admin page, the 'sells' attribute was set to 'none'.  From the public registration page, it was set to 'unspecified'.

**Comment by kirstenalarsen** [comment]
what were you logged in as? I think the problem is when you are an Enterprise User that has a Hub . . if you're in as admin perhaps it doesn't happen?
