### ISSUE TITLE
Embedded shopfront doesn't load products on mobile

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3780]
## Description

When loading an embedded shopfront on mobile for the first time, you need to activate cookies. But when clicking the button to activate cookies, a blank screen appears.

The new tab is opened to set a cookie. But after setting the cookie the page should close and trigger a reload of the shop page. Users can to this as a workaround:

* Close the blank page tab.
* Reload the embedded shop page.

## Expected Behavior

The button to activate cookies should reload the page and show the product list.

## Actual Behaviour

A blank page appears.

## Steps to Reproduce

1. Go to an embedded shopfront with a smart phone. Use a private window if you have been there before.
2. Tap the button *Allow Cookies*.
3. Observe the blank page.

## Animated Gif/Screenshot

...

## Context

An Australian shop regularly receives feedback from customers not seeing the product list.
https://www.tfgardens.com.au/order-fruit-online/

## Severity

s3, affecting mobile users, there is a workaround

## Your Environment

* Version used: v1.29.0
* Browser name and version: Safari and Firefox
* Operating System and version (desktop or mobile): iPhone X
* Australian production: https://www.tfgardens.com.au/order-fruit-online/

**Comment by mkllnk** [comment]
We did get reports that the products are sometimes not loading on laptops either. Any details to help to reproduce this are very welcome.

**Comment by kirstenalarsen** [comment]
I have accepted that embedded shopfront is dead. Closing
