### ISSUE TITLE
Can't create or edit an order cycle on German instance

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#3792]
## Description
On the German instance

## Expected Behavior
When I go to create or edit an Order Cycle, the view should open, enable me to type in the 'name' box 

![image](https://user-images.githubusercontent.com/2911176/57190186-1403a100-6f5b-11e9-922a-638f56bdd564.png)

## Actual Behaviour
The view loads but I can't type in the Name field 

and my lists of Suppliers and Distributors are empty so I can't add any.

![image](https://user-images.githubusercontent.com/2911176/57190214-5d53f080-6f5b-11e9-973a-04fa930d464e.png)

I am set to 'any' and I have shipping and payment methods set up. There is a producer with lots of products (DorV-online) and I have permissions to add to order cycle and inventory.

When I use Browser tools I see this error
![image](https://user-images.githubusercontent.com/2911176/57190294-fb47bb00-6f5b-11e9-9601-ace8c9b4f73b.png)

then a bit later on reload I am seeing this
![image](https://user-images.githubusercontent.com/2911176/57190265-c63b6880-6f5b-11e9-917e-7d85cc2b97e4.png)

I have just created a completely new Enterprise and tried with this in case some kind of weird data problem, but same thing happens

## Steps to Reproduce

1. Go to german instance
2. Try to create or edit and order cycle

## Animated Gif/Screenshot
http://recordit.co/yI0PcvsTty

## Context
Germany meant to be launching tomorrow (Monday 6 May)

## Severity
S1 - Order cycle is a critical function. I can't find a workaround
-->

## Your Environment
Chrome MACOS
Tried Firefox as well, same problem

**Comment by kirstenalarsen** [comment]
From Julia just now - 
![image](https://user-images.githubusercontent.com/2911176/57190624-88404380-6f5f-11e9-89c1-2c723fc04e8a.png)

**Comment by mkllnk** [comment]
I just looked at this and it seems to be a performance problem. There are several things that need to be loaded and it just took one minute for me to load. Then I could edit everything.

**Comment by kirstenalarsen** [comment]
hmmm - yes I just came to similar conclusion - as I noticed the 'loading ... ' thing in the bottom. But mine is still loading - way more than a minute. 

and now the loading thing has disappeared and I have these errors
![image](https://user-images.githubusercontent.com/2911176/57190665-4a8fea80-6f60-11e9-8223-b28b6a5f36a1.png)

Is this a similar problem to the product uploader? as in it just can't cope with the number or products now being pulled into the order cycle @mkllnk ?

**Comment by kirstenalarsen** [comment]
yup. once I removed the producer DorV-online (with its thousands of products) the order cycle loaded in a flash. So we understand the problem. But I don't know how we're going to get the order cycle open for tomorrow . .

**Comment by mkllnk** [comment]
I noticed the 404 errors. I'm not sure why they are there but they don't seem to be important. The 504 means a timeout after a minute or two. Since several people are now trying to do these really slow things and we have huge timeouts, it just piles up, I think.

**Comment by kirstenalarsen** [comment]
have you got it open now? Can you just create the order cycle with the info that Julia just posted in Slack . . I'm assuming just all products in and out

![image](https://user-images.githubusercontent.com/2911176/57190729-41534d80-6f61-11e9-9fd1-7d5e7293a6c9.png)

**Comment by mkllnk** [comment]
I managed to load the form without errors. So it's possible. I'm not sure if it matters that I'm logged in as super admin. Maybe you will need several tries to load the form but you should leave two minutes between tries. Otherwise you are just contributing to the problem.

Okay, I'll try to create it.

**Comment by kirstenalarsen** [comment]
I'm trying to add products to the OC and getting errors :( products aren't loading when I open the panel. Page appears to have 'finished' loading, as much as it's planning to do so!

![image](https://user-images.githubusercontent.com/2911176/57192041-88e0d600-6f6f-11e9-97db-7c0e2fe36d32.png)

**Comment by kristinalim** [comment]
The error is most likely because the page doesn't have the data the page needs, because it failed fetching that data in the HTTP 504 above.

I'm also taking a look.

**Comment by kristinalim** [comment]
This is when loading the edit OC page, for an _almost_ bare database and OC:

![20190505182602-newrelic_order_cycle_edit_page](https://user-images.githubusercontent.com/2243/57192465-6a74dd80-6f63-11e9-91c1-3a0371aaa003.png)

It is a lot, and probably so much higher if the OC has thousands of exchanges and possible products to add.

**Comment by mkllnk** [comment]
The unicorn timeout is 120 but the connection is timing out after 60. That is an nginx setting. We set `keepalive_timout` but there are more:

- `proxy_read_timeout`
- `proxy_send_timeout`
- ...

Setting them could be a quick fix here.

**Comment by mkllnk** [comment]
Okay, I just did that and it helped. The products loaded in 80 seconds and I have the OC edit form. Now I tried to add all the 6687 products and it took 78 seconds to complete. :heavy_check_mark:

**Comment by mkllnk** [comment]
After creating the order cycle had 6687 incoming and outgoing products I was not able to edit the order cycle any more. I upscaled the server to 8 CPUs and 32 GB memory and increased the timeout to six minutes. Still no luck.

Germany will try it with fewer products for now. I'm not sure about the current bug priority. We don't have a specification about the amount of products that can be in an order cycle. So it doesn't seem right to have this as S1 but for Germany it is. It is a critical feature and there is not workaround.

**Comment by mkllnk** [comment]
After discussing this on Slack I took the bug label off. Supporting more than 1000 products is seen as a new feature that needs some more inception like how to browse that amount of products.

**Comment by lin-d-hop** [comment]
Closing as this is now being handled by the admin/order_cycles Epic: #4131
