### ISSUE TITLE
Add placeholder in variant edit page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3793]
As suggested by @CathyPearce while testing #3788

## Description
**- As a:** manager or super admin
**- On page:** Variant edit page /admin/products/PRODUCTNAME/variants
**- I want to be able to do:** 
Add placeholders on Display name and Display as fields. The idea is to have the same behavior than in product bulk edit page where we add as placeholder the value of the main product.

This will help the manager to know which variant they are editing.

## Acceptance Criteria
1. Log in as an admin
2. The behavior on the bulk product page should not change, meaning, when adding variants you can see placeholders with the value from the main product. Example :
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/ea7df213-1a0d-473c-a1d9-5ff94025e0e0)
3. When using the variant edit page, the current behaviour is with no placeholder :
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/7e465b0e-0fca-46fe-8680-2ee3f8165e65)
and we would like to have a placeholder in (in this example) the display as field :
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/8c2d4b78-bc1d-4140-bfa9-4f867912e7fd)
4. If nothing is written in the display name, we should see a placeholder as well

**Comment by JacksonBates** [comment]
@RachL would it be poor etiquette for me to work on this? It's not my 'first issue' in the project, but I'm still ramping up on the tech stack ofn uses so I'm looking for low hanging fruit at the moment.

I'm mindful of not wanting to take away opportunities from others passing through, though...

**Comment by sigmundpetersen** [comment]
Please go ahead @JacksonBates , thank you! 
Really, there are more than enough `good first issue`'s around for everyone to pick up 🙂

**Comment by JacksonBates** [comment]
Thanks @sigmundpetersen :+1:

**Comment by sigmundpetersen** [comment]
@JacksonBates will you be working on this or should we put it back to the backlog?

**Comment by JacksonBates** [comment]
@sigmundpetersen yes, I'm on it - just been going through the process of getting a new job so been unable to pick it up. All clear now so I can continue :)

**Comment by sigmundpetersen** [comment]
Okay that's great thanks! :)

**Comment by daniellemoorhead** [comment]
Hey @JacksonBates did you negotiate well, got the new job all sorted? Reckon you'll have time to pick this up?

**Comment by sigmundpetersen** [comment]
OK moving to backlog. Please shout if you would like to pick it up again @JacksonBates 👍

**Comment by JacksonBates** [comment]
Ok. I'm boning up on AngularJS to figure out the best approach - I'll let you know once I've got it clearer

**Comment by sauloperez** [comment]
Hi @JacksonBates did you get any further on this? Is there something we can help you with?

**Comment by JacksonBates** [comment]
Hi @sauloperez, I've had to stop picking up AngularJS for now - my new job has me diving into Laravel and I only have headspace for one new tech at a time :)

**Comment by sauloperez** [comment]
Fair enough @JacksonBates . Then is ready for anyone else to pick it up.
