### ISSUE TITLE
Release v2.0.0 Beta Carotene

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3796]
Release draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-e669e99e73ab566b101c

**Comment by RachL** [comment]
Testing notes and recap:

https://docs.google.com/document/d/1sct7zLcpZShKIaSgIvfwf-M6eoQtz6VZD9p64LvfByk/edit#

- Images on product cannot be uploaded > seems a config issue, so did not opened anything
- Bulk product edit page putting every variant created to on demand: https://github.com/openfoodfoundation/openfoodnetwork/issues/3803
- Product cannot be duplicated again if previous duplicate as been deleted https://github.com/openfoodfoundation/openfoodnetwork/issues/3808
- Stock problems https://github.com/openfoodfoundation/openfoodnetwork/issues/3804
- Report issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/3805 
- Edge case trying to delete a shipped order through BOM: https://github.com/openfoodfoundation/openfoodnetwork/issues/3807

**Comment by luisramos0** [comment]
nice @RachL 

fyi, there's this issue as well https://github.com/openfoodfoundation/openfoodnetwork/issues/3692

**Comment by sauloperez** [comment]
This is the list of remaining issues and their status:

* #3803: closed
* #3807: It is an s4 so not critical
* #3808: It is an s3, a bit more annoying but still not critical

Therefore, we can publish and deploy v2.0.0 to Katuma as planned.

**Comment by sauloperez** [comment]
Deployed to Katuma and working! 

![](https://media.giphy.com/media/9A5dffWW9jJoOeMVLT/giphy.gif)

**Comment by luisramos0** [comment]
this is not in katuma staging any longer.
