### ISSUE TITLE
Order Cycle updates to work with P-OC permissions

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#380]
###Order Cycle Updates to work with P-OC Permissions
 - As a Enterprise that has granted P-OC to another Enterprise, I should be able to
- see Order Cycles my Enterprises are in on my OC summary page, even though I don't run them
- see but not Edit the Coordinator
- remove my products from them (add products? not yet)
- add my fees to my participating Enterprises (e.g. where I am outgoing or incoming)
- I can only reopen OC, change name etc if I own / manage the Coordinator

see also http://community.openfoodnetwork.org/t/order-cycle-fixes-improvements/45

**Comment by oeoeaio** [comment]
Following discussion with @lin-d-hop and @kirstenalarsen, implementation will be that producers who have granted P-OC to another enterprise will be able to add and remove any of their own products to order cycles in which they have been placed. Additionally, the coordinator will be able to set a boolean on each outgoing exchange on the order cycle, which specifies whether the hub will accept changes to the makeup of its exchange by a producer.

**Comment by kirstenalarsen** [comment]
working through detailed spec and testing at http://community.openfoodnetwork.org/t/upgrading-order-cycle-functionality-to-read-from-p-oc/137/2, this issue is superseded by that work.
