### ISSUE TITLE
UK Header Logo size too large on mobile

### ISSUE THREAD

**Issue by CathyPearce** [openfoodfoundation/openfoodnetwork#3800]
## Description
**- As a:** User (in particular) on Mobile
**- On page:** Any screen e.g. landing page, or shopfront page
**- I want to be able to do:** The OFN logo is larger than the top header, it should be shrunk to fit (same as e.g. France or Spain.  
At the moment, this doesn't matter as the header scrolls with the page.  But PR#3786 is making the header stickly and at that point, the logo comes below the header and obscures any writing behind

UK header now:
![image.png](https://images.zenhubusercontent.com/5c5daad43547567638dbb356/fa636632-7d21-484b-b52b-83116a9e0578)

FR/ES Header:
![image.png](https://images.zenhubusercontent.com/5c5daad43547567638dbb356/c522b40c-a787-428f-8c60-df69df7ca7ac)

## Acceptance Criteria
For Mobile, a small logo will display which fits in the header will be used

**Comment by daniellemoorhead** [comment]
Closed, no longer occurring
