### ISSUE TITLE
If insufficient stock on editing cart, quantity shown becomes incorrect

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3804]
## Description
I've tried editing a cart and reaching product's max stock level. I received a correct message warning me that I couldn't go further. However after I pressed "ok" on the message" the quantity ordered went down to 0 on the UI. But actually it has still well kept the 7 units I was trying to buy. Updating the cart leads to an error 500.

## Steps to Reproduce
1. Go to https://staging.katuma.org/carrot-release/shop
2. Order 7 quantity of "Wine with stock at 7"
3. On the cart, try to add one quantity. A message pops up saying there is only one left.
4. Press "ok"
5. On your cart copy of wine is now showing with 0 quantity
6. Try to raise the number and get again the warning saying there is no stock left (so the 7 quantity is still somewhere but not shown through the UI
7. Try the update button and get an error 500

The workaround is to go back to the shop where the 7 quantity is showing correctly and go back to the cart

## Animated Gif/Screenshot
Cart with 7 on quantity:
![image](https://user-images.githubusercontent.com/6525576/57219603-e2d9ae00-6ff8-11e9-947f-1b434ffbcae9.png)
Rasing to 8 gives this correct message:
![image](https://user-images.githubusercontent.com/6525576/57219630-f6851480-6ff8-11e9-956b-bd34de5dafb5.png)
After pressing ok:
![image](https://user-images.githubusercontent.com/6525576/57219643-06045d80-6ff9-11e9-9af2-ade57d4befd9.png)
when raising again:
![image](https://user-images.githubusercontent.com/6525576/57219675-1a485a80-6ff9-11e9-80e4-0725ef01d016.png)

Trying the update button:
![image](https://user-images.githubusercontent.com/6525576/57219739-5a0f4200-6ff9-11e9-8cd5-69d9c88ead40.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): desktop

**Comment by RachL** [comment]
Closing as I did not managed to replicate :'(

**Comment by RachL** [comment]
@luisramos0 I think I'm managing to reproduce this in Katuma staging currently. Can you confirm?
Steps:

Add 2 beef in the cart on Maryse'shop https://staging.katuma.org/maryse-s-private-shop/shop
On the edit cart page try to change the number (even decreasing it). 
A message will pop up with insufficient stock and quantity drops down to 0.
The update button leads to a 500 error.

**Comment by RachL** [comment]
Managed to reproduced it as well with Eggs in https://staging.openfoodnetwork.org.uk/banana-release/shop 
The max amount is 3.

**Comment by luisramos0** [comment]
ah, I dont understand how I missed this one on my first verification! it's pretty obvious now that I look at the code :-)
I can replicate. you just need a variant on_demand with hidden on_hand value of zero or negative.

It's a simple PR, I'll create it tomorrow.
