### ISSUE TITLE
Deleting a shipped order through BOM leads to an uneditable order

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3807]
## Description
I guess this is an edge case, but it happened to me by mistake, so I guess it can happen to other people by mistake as well?

## Steps to Reproduce
1. Logged in as rachel.arnould+carrots@gmail.com on Katuma staging
2. I went to BOM /admin/orders/bulk_management and filtered on wine 1L
3. I deleted one of the order for wine 1L. Unfortunately I deleted the wrong one : I deleted the one that was already shipped.
4. It has put the amount of the order to 0 which is correct, however the order cannot be edited anymore through the order page. /admin/orders/R877312310/edit give an error 500

**What should happened** : I should be able to access the order edit page without any error.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/57223111-3a7e1680-7005-11e9-8d1b-c44efa1c84f4.png)

![image](https://user-images.githubusercontent.com/6525576/57223084-2afecd80-7005-11e9-8457-0b16e7d8112e.png)

## Severity
bug-s4: it's annoying, but you can use it

Edge case ?

## Your Environment
* Version used: v2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): desktop Ubuntu 19.10

**Comment by lin-d-hop** [comment]
Upgraded to s3 but unfortunately not a papercut.

**Comment by kirstenalarsen** [comment]
@RachL could you update this to describe exactly what you think SHOULD happen and then pop it into 'welcome new developers' project? Thanks

**Comment by RachL** [comment]
Ok done

**Comment by filipefurtad0** [comment]
Hey @RachL ,

I just observed this bug. Also, if a customer attempts to view a deleted order from BOM he will see get snail/error 500 as well. Clicking in View (pic below):

from /account#/orders/
![image](https://user-images.githubusercontent.com/49817236/82810801-44302180-9e87-11ea-9679-7719e6699863.png)

This makes it a bit more severe, but perhaps not S2?

**Comment by RachL** [comment]
Should be fixed by https://github.com/openfoodfoundation/openfoodnetwork/issues/7768

Closing.
