### ISSUE TITLE
When deleting a product duplicate, a product cannot be duplicated again

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3808]
## Description
I deleted a product that I previously created through the duplication icon. After that I could not duplicate the original product anymore. Others were ok.

## Steps to Reproduce
1. Log in as a super admin or producer
2. Duplicate a product
3. Delete the duplicate
4. Try to duplicate the same product again. Nothing happens. Browser shows a 422 error

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/57223854-c1cc8980-7007-11e9-954a-414fc903c908.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2
* Browser name and version: FIrefox 66
* Operating System and version (desktop or mobile): desktop Ubuntu 19.10

**Comment by filipefurtad0** [comment]
I could not reproduce this issue anymore @RachL . Maybe #6617 fixed this?

**Comment by RachL** [comment]
YAY couldn't reproduce as well, closing 🎉
