### ISSUE TITLE
DB tuning - indexes

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3819]
### What we should change and why (this is tech debt)
There must be more opportunities like #3818 
We could spend some time finding what db indexes would benefit the perfomance of the app.

### Context
This came up in PR #3818 

### Impact and timeline
Improve app performance

**Comment by mkllnk** [comment]
This issue is almost five years old. Instead of looking for indexes to optimise it's better to identify bad performance and then see how we can improve it.
