### ISSUE TITLE
RuntimeError in app/jobs/products_cache_integrity_checker_job.rb:6

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3830]
## Error in Katuma

**RuntimeError** in **app/jobs/products_cache_integrity_checker_job.rb:6**
Products JSON differs from cached version for distributor: 93, order cycle: 469

[View on Bugsnag](https://app.bugsnag.com/katuma/katuma/errors/5c864dfee822db0019f45a62?event_id=5cd3d0a00039c766cb880000&i=gh&m=ci)

## Stacktrace

    app/jobs/products_cache_integrity_checker_job.rb:6 - perform
    script/delayed_job:5 - <main>

[View full stacktrace](https://app.bugsnag.com/katuma/katuma/errors/5c864dfee822db0019f45a62?event_id=5cd3d0a00039c766cb880000&i=gh&m=ci)

*Created by Katuma via Bugsnag*

## Description

Since v2.0.0 this error that used to happen sporadically now happens more often. This results in surpassing the 250 events/day free quota we have in Katuma. I did see an exceptional increase of these errors while we used v2.0.0 in staging but it wasn't clear whether the issue was limited to staging or not.

This background job checks whether for a given (distributor, order_cycle) pair the cache is stale or not, meaning that the JSON response stored in the cache is not equal to the actual and latest JSON response. This means that we're missing at least a scenario where the cache should be refreshed.

Also, because we enqueue as many of these jobs as cacheable exchanges (exchanges whose order cycle has at least opening or closing date and is not closed yet) and every hour, the flood of recurrent bugsnag notifications is considerable.

## Expected Behavior

The products cache should always be kept up to date by refreshing it when any of the entities involved in a shopfront is updated.

## Actual Behaviour

The products cache is not kept in sync with the actual data updates.

## Steps to Reproduce

TBD

## Context

This has been introduced by v2.0.0.

## Severity

Still not clear. We need to find out if changing the order cycle or any other attribute refreshes the cache. In the meantime, the shopfront won't reflect its actual state.

## Your Environment

* Version used: v2.0.0
* OFN Platform instance where you discovered the bug, and which version of the software they are using: Katuma

## Possible Fix

There must be some new model or attribute added in v2 and involved in a shopfront that doesn't trigger a cache refresh while it should.

A way to know the difference would be to fix the Bugsnag notification so that it could display it. This now fails. We pass `diff: checker.diff.to_s(:text)` as a second argument of the `Bugsnag.notify` call but it should be included in the exception message instead.

Additionally, as explained in https://github.com/openfoodfoundation/openfoodnetwork/wiki/Products-cache#development, there is a settings page to debug cache's staleness but it currently crashes in Katuma. The `log/production.log` shows how the app simply dies:

```
Started GET "/admin/cache_settings/edit" for 109.69.11.78 at 2019-05-09 21:14:48 +0000
Processing by Admin::CacheSettingsController#edit as HTML
Creating scope :accessible_by. Overwriting existing method OrderCycle.accessible_by.
Connecting to database specified by database.yml
[SKYLIGHT] [1.7.2] Skylight agent enabled
Creating scope :deleted. Overwriting existing method Spree::Variant.deleted.
Creating scope :available. Overwriting existing method Spree::PaymentMethod.available.
Creating scope :accessible_by. Overwriting existing method OrderCycle.accessible_by.
```

The root cause of this, as usual, is because we fetch all `Exchange.cacheable` and compute the diff between the cache and the actual shopfront for each of them.

**Comment by RachL** [comment]
@sauloperez is this issue automatically created by bugsnag? Is this an s1 or s2? I'm asking because you moved it to dev ready but I'm not sure I understand why. Thx ;)

**Comment by sauloperez** [comment]
because I had to stop and continue now, sorry

**Comment by sauloperez** [comment]
Now that #3839 got merged, we know this has to do with v2's change on the db/schema.rb.

![Screenshot from 2019-05-10 14-37-19](https://user-images.githubusercontent.com/762088/57837850-e53fc300-77c3-11e9-940c-c86830070af1.png)

Obviously, database migrations don't refresh the cache :see_no_evil: . We need to document then that deploying v2 requires refreshing all the cached products as explained in https://github.com/openfoodfoundation/openfoodnetwork/wiki/Products-cache#refreshing-the-entire-cache.

However, we spotted other diffs in Bugsnag reporting a difference on the `on_demand` and `on_hand` attributes having the cache entry a v2 schema already. Specifically, we saw few entries with a diff like follows

```
-        "on_hand": 0,
+        "on_hand": -1,
```

That's definitely a separate problem that must be related to new models/actions missing a cache refresh call.

I suggest we close this issue as it fixes most of the errors reported in Bugsnag and create a new one the next time we encounter the second problem. Since I refreshed the cache yesterday night, there have been no new errors (it is a pretty quiet day on the week though).

![Screenshot from 2019-05-16 10-25-24](https://user-images.githubusercontent.com/762088/57838508-1ff62b00-77c5-11e9-8484-a474577e28e4.png)

**Comment by sauloperez** [comment]
This keeps happening a lot. Only In the last two days Katuma had several occurrences, one of them being https://app.bugsnag.com/katuma/katuma/errors/5cd56e35de067d0018fdea09?event_id=5d3310cb004b11d35ac90000&i=em&m=fq&filters[app.release_stage][0][value]=production&filters[app.release_stage][0][type]=eq. It's hard to quantify though because a wrong shop gets reported many times.

I haven't checked again but I guess the actual behavior is still what we described in #3862

**Comment by mkllnk** [comment]
Now that France is on v2, it happens there as well. It's the same problem with stock changes on on-demand products:

```diff
"variants": [
       {
         "id": 2378,
         "is_master": false,
         "on_hand": 0,
         "name_to_display": "boîte de 6",
         "unit_to_display": "1 boite",
         "unit_value": 1.0,
         "options_text": "1 boite",
         "on_demand": true,
         "price": "2.4",
         "fees": {
         },
         "price_with_fees": "2.4",
         "product_name": "oeufs",
         "tag_list": [
 
         ]
       },
       {
         "id": 2379,
         "is_master": false,
-        "on_hand": 0,
+        "on_hand": -3,
         "name_to_display": "boîte de 12",
         "unit_to_display": "1 boîte",
         "unit_value": 1.0,
         "options_text": "1 boîte",
         "on_demand": true,
         "price": "4.8",
         "fees": {
         },
         "price_with_fees": "4.8",
         "product_name": "oeufs",
         "tag_list": [
 
         ]
       }
     ]
```

**Comment by sauloperez** [comment]
Yep, I was about to share the same. There's clearly an increase. I don't even remember seeing cache errors in FR so far.

**Comment by mkllnk** [comment]
And it makes sense. In v1, on-demand variants always had a stock of `0` and didn't need updating when sold. But now the stock changes. And even though it's not important for the shop at all, the integrity checker sees the difference in stock.

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**RuntimeError** in **app/jobs/products_cache_integrity_checker_job.rb:11**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d1f11a5518e0d0018ffe521?event_id=5d4a1548004c8f9acf750000&i=gh&m=li)

**Comment by sigmundpetersen** [comment]
Is cache gone? Can we close?

**Comment by Matt-Yorkley** [comment]
The cache doesn't exist! :tada:
