### ISSUE TITLE
[Flaky spec] spec/models/product_importer_spec.rb:270

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3831]
### What we should change and why (this is tech debt)

Our master build just failed because of a flaky spec. I ran it locally and it passed.
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/611

### Context

The build was triggered by a locale update which is completely unrelated to the failing spec.

### Impact and timeline

Please give more examples here if you encounter this spec failing.

**Comment by mkllnk** [comment]
The line of this test moved: `spec/models/product_importer_spec.rb:272`

The problem is that we create two products with the display name "Small Bag". One with potatoes and one with chives. Then we validate that a Small Bag is potatoes but sometimes the database returns the chives.

@Matt-Yorkley This should be very easy to fix but I'm not sure about the intent of the spec. Should we change the display name or should they be the same?

**Comment by Matt-Yorkley** [comment]
Ok, this is a super quick fix and it pops up often, I'll fix it now.
