### ISSUE TITLE
Unable to distinguish between link and regular text in WYSIWYG editor

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#3832]
## Description

In the WYSIWYG editor in the admin section, you cannot distinguish between a link and regular text unless the cursor is hovered over the link.

Examples of where you can see this are in the editor for enterprise "About Us" content and, after #3799, in the editor for product description.

## Expected Behavior

The user should be able to immediately tell in the WYSIWYG editor if the text is a link or not.

## Actual Behavior

An inserted link looks like regular text unless the cursor is hovered over the link.

## Steps to Reproduce

1. Go to the settings page for an enterprise. Open the "About" tab.
2. Insert a link in the WYSIWYG editor for "About Us". Notice that the link looks like regular text.
3. Hover over the link. Notice that you can now tell that it is a link.
4. Save the changes.
5. Go back to the list of enterprises.
6. Go to the settings page for the enterprise again. Open the "About" tab.
7. Notice that the link still looks like regular text.
8. Hover over the link. Notice that you can tell again that it is a link.

## Animated Gif/Screenshot

![20190509174700-wysiwyg-editor-link](https://user-images.githubusercontent.com/2243/57444454-c355b600-7282-11e9-9be1-e856723eda76.gif)

## Context

Discovered this while reviewing #3799 

## Severity

bug-s4: it's annoying, but you can use it

## Possible Fix

Can show links in the same color they appear on hover

**Comment by agustinariq** [comment]
Hello! I worked on this issue in https://github.com/openfoodfoundation/openfoodnetwork/pull/4354
