### ISSUE TITLE
Uploading Variants Causes Errors in V2 Product Import

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#3844]
## Description

When uploading files that contain different variants that need to be grouped together the importer seems to crash - there is no error message but the loading page never changes.

The difference here is that a file has 2 entries that need to be updated and then create 13 more - could the issue be that the importer cannot do this?

## Expected Behavior

Should upload as per usual

## Actual Behaviour

An 'invisible' error

When I refresh and attempt to reupload the data some of the data has gone in, and others haven't. There was no error indicated when I first imported the file during the initial checks

It looks like it stops after the 3rd entry where the data changes from unit type, ot variant unit type “bar”

## Steps to Reproduce

1. https://docs.google.com/spreadsheets/d/1-n5PyoOqloRXWdw-DUGMoy0AWs5KeeQWKITnMIbDyyg/edit#gid=788111594
2. Upload the above file
3. Import and see that the file never actually goes in, the page starts to load but never changes
4. Reupload the file to see that some have infact been uploaded

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/28807449/57527664-277e8580-7328-11e9-9864-afb48ceb63fe.png)

![image](https://user-images.githubusercontent.com/28807449/57527709-4e3cbc00-7328-11e9-98f3-5197c2da620c.png)

 GET https://staging.openfoodfrance.org/assets/admin/custom.css net::ERR_ABORTED 404
all-8e381660fc94b253a53474fe56c7de90.js:547 SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at fromJson (all-8e381660fc94b253a53474fe56c7de90.js:543)
    at defaultHttpResponseTransform (all-8e381660fc94b253a53474fe56c7de90.js:546)
    at all-8e381660fc94b253a53474fe56c7de90.js:546
    at forEach (all-8e381660fc94b253a53474fe56c7de90.js:543)
    at transformData (all-8e381660fc94b253a53474fe56c7de90.js:546)
    at transformResponse (all-8e381660fc94b253a53474fe56c7de90.js:546)
    at processQueue (all-8e381660fc94b253a53474fe56c7de90.js:547)
    at all-8e381660fc94b253a53474fe56c7de90.js:547
    at Scope.$eval (all-8e381660fc94b253a53474fe56c7de90.js:547)
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:547
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:546
processQueue @ all-8e381660fc94b253a53474fe56c7de90.js:547
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:547
$eval @ all-8e381660fc94b253a53474fe56c7de90.js:547
$digest @ all-8e381660fc94b253a53474fe56c7de90.js:547
$apply @ all-8e381660fc94b253a53474fe56c7de90.js:547
done @ all-8e381660fc94b253a53474fe56c7de90.js:546
completeRequest @ all-8e381660fc94b253a53474fe56c7de90.js:546
requestLoaded @ all-8e381660fc94b253a53474fe56c7de90.js:546
load (async)
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:546
sendReq @ all-8e381660fc94b253a53474fe56c7de90.js:546
chain @ all-8e381660fc94b253a53474fe56c7de90.js:546
processQueue @ all-8e381660fc94b253a53474fe56c7de90.js:547
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:547
$eval @ all-8e381660fc94b253a53474fe56c7de90.js:547
$digest @ all-8e381660fc94b253a53474fe56c7de90.js:547
$apply @ all-8e381660fc94b253a53474fe56c7de90.js:547
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:551
dispatch @ all-8e381660fc94b253a53474fe56c7de90.js:26
elemData.handle @ all-8e381660fc94b253a53474fe56c7de90.js:26
all-8e381660fc94b253a53474fe56c7de90.js:699 undefined
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:699
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:546
processQueue @ all-8e381660fc94b253a53474fe56c7de90.js:547
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:547
$eval @ all-8e381660fc94b253a53474fe56c7de90.js:547
$digest @ all-8e381660fc94b253a53474fe56c7de90.js:547
$apply @ all-8e381660fc94b253a53474fe56c7de90.js:547
done @ all-8e381660fc94b253a53474fe56c7de90.js:546
completeRequest @ all-8e381660fc94b253a53474fe56c7de90.js:546
requestLoaded @ all-8e381660fc94b253a53474fe56c7de90.js:546
load (async)
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:546
sendReq @ all-8e381660fc94b253a53474fe56c7de90.js:546
chain @ all-8e381660fc94b253a53474fe56c7de90.js:546
processQueue @ all-8e381660fc94b253a53474fe56c7de90.js:547
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:547
$eval @ all-8e381660fc94b253a53474fe56c7de90.js:547
$digest @ all-8e381660fc94b253a53474fe56c7de90.js:547
$apply @ all-8e381660fc94b253a53474fe56c7de90.js:547
(anonymous) @ all-8e381660fc94b253a53474fe56c7de90.js:551
dispatch @ all-8e381660fc94b253a53474fe56c7de90.js:26
elemData.handle @ all-8e381660fc94b253a53474fe56c7de90.js:26

## Context

We will likely receive upload files from specific clients that require us to carry out updates on data whilst also creating new product

## Your Environment

* Version used: v2 french staging
* Browser name and version: 
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by mkllnk** [comment]
I can reproduce this on French staging. There is the following error message sent back by the server:

```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "permalink_idx_unique"
DETAIL:  Key (permalink)=(natural-lavender-soap) already exists.
: INSERT INTO "spree_products" ("available_on", "created_at", "deleted_at", "description", "group_buy", "group_buy_unit_size", "inherits_properties", "meta_description", "meta_keywords", "name", "notes", "permalink", "primary_taxon_id", "shipping_category_id", "supplier_id", "tax_category_id", "updated_at", "variant_unit", "variant_unit_name", "variant_unit_scale") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20) RETURNING "id"
```

**Comment by mkllnk** [comment]
The problem seems to be a conflict on permalinks. Permalinks need to be unique. There is already a products with the permalink `natural-lavender-soap` but it is deleted. So I guess that there is at least one flaw in this code:

https://github.com/openfoodfoundation/openfoodnetwork/blob/568e3003ba43c713ac4fb5a57fddfbca086f7b98/lib/open_food_network/permalink_generator.rb#L18-L21

1. `id` is `nil` for a new product. And in SQL `id != NULL` is always false. That means that we probably never detect permalink conflicts when creating products.
2. Without explicitly querying with the `deleted` scope, we only get undeleted products. So we don't detect conflicts with deleted products.

I still need to verify this in unit tests.

**Comment by mkllnk** [comment]
Digging into this I can verify that there is a conflict with the permalinks of deleted products. Unfortunately, our code is not the only one dealing with permalinks. Spree tried to do that as well: https://github.com/openfoodfoundation/spree/blob/master/core/lib/spree/core/permalinks.rb

It's horrifying because they are injecting their permalink code into ActiveRecord. At some point they realised though that it would be better to replace their implementation with [Friendly Id](https://github.com/norman/friendly_id). That gem seems a bit bloated for our needs but we may go there one day. We will also get there by upgrading to Spree 2.3.0.
