### ISSUE TITLE
SQL Injection Vulnerability in users_and_enterprises_report

### ISSUE THREAD

**Issue by Drumstickx** [openfoodfoundation/openfoodnetwork#3855]
## Description
The admin interface contains a SQL injection vulnerability on the user and enterprises report page.
The `enterprise_id_in[]` and `users_id_in[]` parameters in requests issued to the respective endpoint are not properly sanitized.
This allows the execution of arbitrary SQL queries (e.g., dropping a table as shown below).

## Steps to Reproduce
1. Setup a new postgresql database (to prevent data loss) as described in `GETTINGS_STARTED.md`
2. Run openfoodnetwork with the new database (`bundle exec rails server`)
3. Visit the users and enterprises report section in the admin web interface at `http://0.0.0.0:3000/admin/reports/users_and_enterprises` in a browser (log in with the default credentials)
4. Extract the value of the cookie header and the authenticity token parameter as follows:
	- 4.1. Open the network tab of the developer console of your browser
	- 4.2. Issue a POST request by searching for any enterprise (e.g., `Mary's Online Shop`) using the form on the `http://0.0.0.0:3000/admin/reports/users_and_enterprises` site
	- 4.3. Inspect the issued request in the developer console and extract the cookie header value (e.g. `_session_id=27f5b5fbd88863d5afc0e445eed189b2`) and the authenticity token value (e.g., `gYhFyg4ud5kf77svOXGQd6ZnMJqFiEeBBVC49tb21iY=`)
5. Craft a malicious request with the values extracted in 4., (e.g. using the [Advanced Rest Client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo)) by injecting a malicious SQL query via the `enterprise_id_in[]` parameter (works the same way for `user_id_in[]`)
    - Example for a malicious parameter value: `3)%3B DROP TABLE sessions%3B SELECT enterprises.id, enterprises.created_at FROM enterprises WHERE enterprises.id IN(3`
	- I attached two screenshots of an example request configuration with the Advanced Rest Client as well as an export of this request that can be imported in the Advanced Rest Client and used for reproduction (cookie header and authenticity token have to be updated with values of a current session)
6. Send the request issued in 5. to delete the sessions database

## Severity
Vulnerability

## Your Environment
* Version used: v2.0.1 / master branch as of 59d4e3d9e2192524d807b8dbc4271b427adea1ac
* Browser name and version: Chromium Version 74.0.3729.157
* Operating System and version (desktop or mobile): Arch Linux

## Possible Fix
Sanitize user input in SQL queries. See the attached PR for a rewritten version of the two database queries with proper sanitation.

## Attachments
![ARC1](https://user-images.githubusercontent.com/9080610/57984899-a4180f00-7a60-11e9-9b5e-64667731d7ab.png)
![ARC2](https://user-images.githubusercontent.com/9080610/57984900-a4180f00-7a60-11e9-88a7-c08667b9fb79.png)

[arc-data-export-19-5-2019.txt](https://github.com/openfoodfoundation/openfoodnetwork/files/3195292/arc-data-export-19-5-2019.txt)
(note: the export is in .json format but I renamed it to .txt as .json attachments are not allowed)

**Comment by kristinalim** [comment]
Hello, @Drumstickx! Thank you very much for reporting this and for submitting a PR. I've alerted the other core dev contributors about this.

I confirm that this is a problem.

The "Users & Enterprises" report is only available to superadmins so this is less critical, but we should still address this ASAP. :+1:

You might have checked this already too... I searched the code for other places where we call `ActiveRecord::Base.connection.execute` with a string into which we insert an unsanitized browser-submitted parameter. Fortunately, there doesn't seem to be anywhere else where this is a problem. (I only searched for keyword `execute`.)

**Comment by Matt-Yorkley** [comment]
Thanks @Drumstickx. How did you come across our project? 

On our production servers users don't have access to that page, but its worth looking at. We've got a security audit coming up soon, but most of the team is away in France this week.

**Comment by Drumstickx** [comment]
I am currently taking a look at vulnerabilities in open source software as part of an university assignment.
While looking for SQL injections, I searched for `.execute` and `.exec_query` and found the reported SQL injection(s).

Regarding your upcoming audit: the [brakeman](https://github.com/presidentbeef/brakeman) static analysis tool might prove helpful in finding potential vulnerabilities and could also be integrated in the CI.

**Comment by luisramos0** [comment]
thank you @Drumstickx great work!
