### ISSUE TITLE
Top 5 s3 bugs (NEW)

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3857]
We agreed we would manage s3 bugs by group of 5, bits by bits. This epic is here to group them.

**Comment by luisramos0** [comment]
I am working on 3 of these issues.

I'd say #2774 is to hard to fix now and #2251 is not so important, and suggest we select other 2 S3 bugs, for example: #3660 and #764

what do you think @RachL ?

**Comment by RachL** [comment]
@luisramos0 great! I did the changes

**Comment by luisramos0** [comment]
@RachL 
So #3660 is definitely going to take a little time and #3928 is already in code review. I think you suggested we move 3660 out of this epic and move 3928 to close the scope of this epic?

**Comment by RachL** [comment]
@luisramos0 yes. Or we just reuse this epic for each batch of 5 bugs we will deal with (and navigate it between the bug backlog and the dev ready column). I was thinking maybe it would help us to have our notes on each bugs we leave for later. But maybe we can comment on the issues directly and open / close TOP 5 epics as we go.

Either way is fine by me.

**Comment by luisramos0** [comment]
I prefer "comment on the issues directly and open / close TOP 5 epics as we go"
additionally I think we can open "top 5" epics only if we really mean to prioritize like that, otherwise we can go back to the normal moving of the top 3 bugs into the dev ready without epic.

**Comment by luisramos0** [comment]
can we close this and open a new top 5 s3 bugs epic? it's a bit confusing in terms of scope.
there are 2 open issues right now here, I assume we will have 5 at some point?

**Comment by sigmundpetersen** [comment]
Yes I think we agreed to do that, no? I don't know  why this wasn't done. There are 10 total issues attached to this epic so this was just expanded from the last round. Let's close, find 3 more s3's in addition to the 2 open ones here and put at the bottom of Dev ready?

**Comment by RachL** [comment]
@luisramos0 @sigmundpetersen it was done like this at a delivery train, I don't remember by whom but we started 5 new s3 bugs in here. So total 10 (2x top 5). I didn't have the courage to ask for a complete new epic that's why I rename this one with "new".

I would prefer that we leave it like this and the next time we are able to fit a new top 5 s3 bugs in dev ready we open a new epic. If we do it now it would be wrong in terms of what has been prioritized. 

It is correct that we only have 2 s3 bugs left to do. Am I making any sense? :D

**Comment by sigmundpetersen** [comment]
Yes you make sense :) I concur, let's make a new one at the next crossroads 👍

**Comment by luisramos0** [comment]
ok, we keep these 2.
I have no clue what were the first 5 and the second round 3 already closed.. did we really add those 3 and close them afterwards, I dont remember coming back to this epic after working on the first 5...

**Comment by sigmundpetersen** [comment]
It's all in the Zenhub history further up. Danielle added 5 new issues on Aug 6, 3 of them have been taken on by Matt and Kristina and closed 🙂

**Comment by luisramos0** [comment]
now I am curious, where do you see that "Danielle added 5 new issues on Aug 6"?

**Comment by sigmundpetersen** [comment]
![Untitled](https://user-images.githubusercontent.com/1451633/64413619-1e14e800-d092-11e9-8faa-23a7f18257af.png)

**Comment by luisramos0** [comment]
ah nice, I missed that line, thanks!

**Comment by luisramos0** [comment]
🎉
