### ISSUE TITLE
As a super-admin, I can hide invoices for an instance

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3859]
## Description
**- As a:** super admin
**- On page:** /admin/general_settings/edit
**- I want to be able to do:** Be able to switch on and off my user access to invoices. As the invoice management is currently not compliant with France accountability law, this will help instance like France to turn off the use of this feature.

By default, the config must be at ON.

## Acceptance Criteria
*Scenario 1*
1. Logged in as a super admin, I can turn OFF the invoices
2. Logged in as a super admin or an enterprise manager - On `/admin/orders?q[s]=completed_at+desc` I cannot see the bulk invoice printing button anymore
3. Logged in as a super admin or an enterprise manager - On `/admin/orders/ORDERNUMBER/edit` I cannot see the send invoice and print invoice button in the action dropdown

*Scenario 2*
1.Logged in as a super admin, I can see that by default invoices are turned ON
2. Logged in as a super admin or an enterprise manager, the bulk invoice button is working as usual on `/admin/orders?q[s]=completed_at+desc`
3. Logged in as a super admin or an enterprise manager - On `/admin/orders/ORDERNUMBER/edit` I can see the send invoice and print invoice button in the action dropdown, and they are working as usual

**Comment by luisramos0** [comment]
I assume this setting will be in Configuration > Invoice Settings (admin/invoice_settings/edit)?

this is currently the page:
<img width="746" alt="Screenshot 2019-06-18 at 15 51 13" src="https://user-images.githubusercontent.com/1640378/59694677-ef991680-91e0-11e9-80fe-cfb7ec07c332.png">

I'll label this new checkbox as "Enable Invoices?", ok?

**Comment by RachL** [comment]
@luisramos0 fine by me :)
