### ISSUE TITLE
Product stays in the product lists even when out of stock

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3862]
## Description

Whenever a new order is placed and stock is updated the cache is not updated resulting on wrong stock displayed in the shopfront. Since the products cache is only used in the shopfront, all other parts of the app are not affected; they'll display correct stock level.

## Expected Behavior

The shopfront does not display products that are out of stock.

## Actual Behaviour

When you add an out of stock product into the cart, a modal pop ups telling it ran out of stock and then the product greys out forbidding you to purchase it.

## Steps to Reproduce

1. Disable on demand and add some stock to a variant
2. Place an order consuming all the stock available
3. Then, check the updated stock in the variant from the backoffice
4. Try placing a new order adding that same product

## Context

https://github.com/openfoodfoundation/openfoodnetwork/issues/3830#issuecomment-492970792

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v2.0.1
* OFN Platform instance where you discovered the bug: Katuma

## Possible Fix

Add the necessary cache refreshing logic for the new stock item model.

**Comment by sauloperez** [comment]
Note to myself. We need to investigate if the following method needs updating:

https://github.com/openfoodfoundation/openfoodnetwork/blob/4afa0cdca1b66d42f32506f1d62d9fc54b15d33c/app/models/spree/variant_decorator.rb#L121-L136
