### ISSUE TITLE
Unit Type is not correctly imported in Product Import v2

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#3877]
## Description

A file is uploaded and the variants contain different unit types, i.e. kg, g and and item (multipacks such as "g x 4 bags" which would then append to be 125_g x 4 bags_)

The product import review pages indicate the data will be imported as is in the csv files. However when you review the data, some datas unit types have changed. It looks like instead of maintaining the csv files input, it updates them all to use the same unit type. 

The might be the correct way, however in v1, we could do it as initially stated, and the main issue if this is how it is meant to be is you are initially told in the review page it will do something different to what the end result is, and it is then difficult to review the end result in BEP

## Expected Behavior

The importer should notify any changes.

## Actual Behaviour

Some data points change, whereas others dont, so it's really hard to see what the actual issue is that causes a change, especially when working with large data sets

## Steps to Reproduce

1. Upload - https://docs.google.com/spreadsheets/d/1DCHBuiBitkgjiAVR5jUG4Pz-E2UgGYDl0VgTyje2KTs/edit#gid=796587646
2. Note the import screen and all data points are fine
3. Upload
4.Check through the data and not that some have changed their formats when it comes to the unit type - S015Z | Alfalfa   Seeds - is an example

## Animated Gif/Screenshot

File going in:
![File going in](https://user-images.githubusercontent.com/28807449/58462889-b3ffb500-812a-11e9-800d-bdff04c57371.PNG)
what goes in:
![What ends up going in](https://user-images.githubusercontent.com/28807449/58462914-c11ca400-812a-11e9-9846-d91d998c4db9.PNG)

line 63 is an example of something that hasnt gone in correctly
https://docs.google.com/spreadsheets/d/1DCHBuiBitkgjiAVR5jUG4Pz-E2UgGYDl0VgTyje2KTs/edit#gid=796587646

## Context

We have large clients using a multipack format and need a way of accommodating this and being clear on what the tool can and cant do.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by luisramos0** [comment]
according to @lin-d-hop 3908 is not closing this.

**Comment by luisramos0** [comment]
sorry, my mistake with 3843
