### ISSUE TITLE
[v2] Cannot checkout if a product shipping category is not in any of the shipping methods

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3879]
## Description
Shipping categories are now mandatory on products and shipping methods.

But you can create a product with a shipping category that was not selected in the shipping methods you have created. When this happens, the hub manager does not see his mistake, but his buyers won't be able to checkout that product. 

## Steps to Reproduce
1. Log is as an instance manager.
2. Check that you shipping methods are all missing one shipping category
3. Create a product with that particular shipping category
4. Put this product in an open OC and try to checkout that product
5. At the last step of checkout, the payment will show a spinner, but nothing else happens. You cannot go further (error 500)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop 

## Possible Fix
Several options:
A - Make checkout succeed whatever the shipping categories selected or not selected
B - When creating a shipping method make all the categories and zones selected by default
C - When creating a product, show in the shipping categories dropdown only the shipping categories selected in the shipping methods.

**Comment by kristinalim** [comment]
**Another option:** How about adding packing categories that are separate from shipping categories? It seems like a simpler and more appropriate solution IMO. Spree's definition of shipping category does not seem to match how it is currently being used in UK.

We can migrate existing shipping categories into packing categories, add to where in v1 they appear in reports / pages, and also support in product import. Then we can keep existing v2 shipping method and category behaviour.

So shops would be left with only 1 shipping category - the "default" shipping category - until they decide to change this.

**Comment by luisramos0** [comment]
@kristinalim I dont think we need to introduce a new concept for this, there's a quick fix.

this is not as bad as I thought.
on step 2 to reproduce
"Check that you shipping methods are all missing one shipping category"

it really matters that you uncheck the products shipping category from ALL shipping methods of the hub, if one of the shipping methods contains the shipping category of the product, that shipping method will be selected automatically on checkout and checkout will not fail.
so, the workaround, if the checkout is really broken bcause of this is to add the products shipping category to ONE of the shipping methods.
An example: user buys a frozen item (product shipping category = frozen), if no shipping method of the hub supports frozen items (shipping method category = frozen), the checkout will fail (this is the bug). If there's one shipping method that supports frozen items, when user checks out a frozen item, that shipping method will be selected automatically, even if user selects another shipping method.

anyway, I have a quick fix for this bug (option A above) that will disable shipping category verification on checkout and will let user buy frozen products even if the shipping method doesnt have that shipping category. I'll create a PR in a sec.

**Comment by kristinalim** [comment]
@luisramos0 I checked your solution in #3884 and agree that it is indeed simpler. I'm happy with that.
