### ISSUE TITLE
Cannot save variant overrides as Hub user (either as Owner/Mgr or with E2E perm)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#389]
![image](https://cloud.githubusercontent.com/assets/2911176/6281348/c8892594-b913-11e4-9371-592fea8d4b20.png)

**Comment by RohanM** [comment]
Fixed in e96b109.

**Comment by kirstenalarsen** [comment]
We need to update http://community.openfoodnetwork.org/t/variant-overrides-hub-can-override-stock-level-and-price-on-a-variant/31 to make sure we have clear and correct spec for how this works. From what I can see we have some problems:

Is working when I am the owner of the Hub and the Producer.

Fails if I am the manager (not owner) of the Hub and Producer
e.g.
![image](https://cloud.githubusercontent.com/assets/2911176/6681581/ff29b638-ccbc-11e4-8e05-edd51e28a1f4.png)

![image](https://cloud.githubusercontent.com/assets/2911176/6681576/e9cea7ee-ccbc-11e4-8508-10905bf9af27.png)

Fails when I am Owner or Manager of the Hub and have P-VO from the producer
![image](https://cloud.githubusercontent.com/assets/2911176/6681496/a67c4cfe-ccbb-11e4-9a0f-91b44e5f36b7.png)

Fails when I am the manager of the Producer [whether I do or don't have P-VO from the Hub, but should I need this?]

Think it may be reading off P-OC rather than P-VO . . which means it's bringing up some variants it shouldn't e.g. if I am manager of Producer 2 and Hub 1, and P2 has given H1 P-OC, VO:
- I get drop-down options for Hubs 1, 2, 3 [Correct, I am manager of H1, and P2 has given P-VO to all 3 of these]
- and Independent [incorrect? I am not manager, Independent has not given P-VO to Hub1; and P2 has not given P-VO to Independent], but Independent HAS given P-OC to Hub1
- when I select Hub 2 [I am not manager, but P2 has given P-VO]
 - I see P1, P2, P3 . . 
 - Hub2 has given Hub1 P-OC, so it may be checking my user H1, and then using P-OC to determine the list I see? 

![image](https://cloud.githubusercontent.com/assets/2911176/6681691/0b5a7422-ccbf-11e4-823c-86e1ea5deba3.png)

**Comment by RohanM** [comment]
This mysteriously seems to be fixed in staging.

**Comment by kirstenalarsen** [comment]
now ok when I am
- manager (not owner) of the Hub and Producer
- Owner or Manager of the Hub and have P-VO from the producer

the issues about who sees what are still a bit unclear. I cannot no longer select from Hubs that my Producers have given P-OC to . . but am separating this out into a different issue. So closing this
