### ISSUE TITLE
'Users' should be lower down the panels - perhaps at the bottom?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#390]
![image](https://cloud.githubusercontent.com/assets/2911176/6282500/8fbb4168-b92a-11e4-9b8a-a5a6d5e32f7a.png)

**Comment by OliverUK** [comment]
Tested in Safari on Mac and Users now appears on the bottom of the menu. Clicking on it works and their is probably not much else to say. Same result whether I go through the Enterprises menu or the dashboard.

![screen shot 2016-12-14 at 14 05 41](https://cloud.githubusercontent.com/assets/17590921/21185035/fab6f598-c206-11e6-89af-5624f26ef724.png)

**Comment by sstead** [comment]
This one isn't going to make it into release 1.8.7

**Comment by sstead** [comment]
Some minor menu display inconsistencies, but this appears to already be happening on production...
