### ISSUE TITLE
Sorts product per alphabetical order 

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3909]
## Description
**- As a:** Enterprise user or super admin user
**- On page:** /admin/products
**- I want to be able to do:** See products per alphabetical order.

This user feedback came from Guillaume, see: https://community.openfoodnetwork.org/t/some-potential-ofn-improvements-from-a-small-normandy-producer/1663

## Acceptance Criteria
This issue can be closed if the following tests can be done:

*Scenario 1*
1. Log in as an enterprise user
2. Go to /admin/products
3. The list of product shall appear in alphabetical order with filter or without filters.

*Scenario 2*
1. Log in as a super admin
2. Go to /admin/products
3. The list of product shall appear in alphabetical order with filter or without filters.

**Comment by anushreddy** [comment]
is anyone working on this? i would like to start with this if no one is working

**Comment by RachL** [comment]
@anushreddy unfortunately yes @luisramos0 has started to work on this here: https://github.com/openfoodfoundation/openfoodnetwork/pull/3911 Maybe it is easier for you to pick up something else?

**Comment by luisramos0** [comment]
@anushreddy you are welcome to continue what I did, see #3911 
this is now an interesting javascript promises challenge in this method to ensure the pages are parsed in order here: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/index_utils/services/paged_fetcher.js.coffee

something like this change is needed now:
https://github.com/openfoodfoundation/openfoodnetwork/pull/3911/commits/5e72048608352e335e8737df9f4c02710567b7d4

I am not planning to pick this up, but if you are up for some js/promises fun, this is your issue ;-)

**Comment by luisramos0** [comment]
I remove good-first-issue as it's quite a tricky JS challenge.

**Comment by luisramos0** [comment]
now that the results are paginated on the server side, I think this is a simple change on the server code to sort the results. to be confirmed... I am adding the good first issue back anyway.

**Comment by pacodelaluna** [comment]
Taking a look at it, will push a PR asap.
