### ISSUE TITLE
Add red * on all the mandatory fields when creating a new OC

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3910]
## Description
**- As a:** enterprise user or super admin
**- On page:** /admin/order_cycles/new

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/eb2fd70c-e5f2-4db6-8f0a-bf92d8d178e5)

**- I want to be able to do:** Be able to see more clearly which fields are mandatory to fill in.

The current mandatory fields are:
- Name
- Ready for

The proposal is to add a red * besides each field name. This is what is being done on product creation:

![image](https://user-images.githubusercontent.com/6525576/59190594-66993400-8b7d-11e9-9dec-a36395b408f3.png)

This feedback came out of https://community.openfoodnetwork.org/t/some-potential-ofn-improvements-from-a-small-normandy-producer/1663/2

It will help us to show more easily that the "ready for" field is mandatory.

## Acceptance Criteria
This issue can be closed if the following tests can be done:

*Scenario 1*

1. Log in as an enterprise user
2. Go to /admin/order_cycles/new
3. You can see red * on all the mandatory fields. When they are all filled up, the update button is enhanced (current behaviour)

*Scenario 2*

1. Log in as a super admin
2. Go to /admin/order_cycles/new
3. You can see red * on all the mandatory fields. When they are all filled up, the update button is enhanced (current behaviour)

**Comment by abhishek-iitj** [comment]
@RachL would like to work on this one. 
Should I proceed?

**Comment by luisramos0** [comment]
Hi @abhishek-iitj you are welcome! please go ahead, let us know if you have any issues with this.

**Comment by RachL** [comment]
Welcome in our community @abhishek-iitj ! :) Looking forward to your contribution

**Comment by daningenthron** [comment]
Hi @RachL, if this issue is back open for Hacktoberfest, I can take a look at it? I'll plan on setting up the asterisks the same way as on the product page, and adding your suggested tests, unless there are any other considerations

**Comment by RachL** [comment]
Hi @daningenthron ! Sure go for it :) 💪

**Comment by daningenthron** [comment]
Hi @RachL can you verify that 'Orders open at' and 'Orders close' should be mandatory? I see instances in the code where OCs are undated or partially dated, where one or more of these fields have null values.

**Comment by RachL** [comment]
Hi @daningenthron my bad indeed those fields are not mandatory yet. Let's focus here only on those who are. I will update the issue.

**Comment by daningenthron** [comment]
Got it - thanks for clarifying!
