### ISSUE TITLE
Unable to create new product (snail) with Value field empty

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3912]
## Description
User cant create product.

![Screenshot 2019-06-10 at 13 11 51](https://user-images.githubusercontent.com/1640378/59194625-8af70f80-8b81-11e9-8f18-aab2b98b39a6.png)

I am still talking to the user to confirm this is her problem but I did find a bug.

## Steps to Reproduce
When creating a product with unit type items, user fills in all required fields except the unit value field which is mandatory.

## Actual Behaviour
After submitting the form, the user should see the same page with a standard form error saying "unit value field cant be blank".

![Screenshot 2019-06-10 at 13 11 58](https://user-images.githubusercontent.com/1640378/59194626-8af70f80-8b81-11e9-8ad5-7fb0b13f5f7c.png)

## Expected Behavior
After submitting the form, user sees snail page.

## Context
First real bug coming from Portuguese users.

## Severity
bug-s3
the workaround is to call support that will call developers that will look at the logs and will tell support "unit value field is mandatory" that will tell the user "unit value field is mandatory" :-D

## Your Environment
* Version used: Katuma OFN v2.0.2
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): osx 10.14

## Possible Fix
the bug is in this line:
https://github.com/openfoodfoundation/openfoodnetwork/blob/568e3003ba43c713ac4fb5a57fddfbca086f7b98/app/controllers/spree/admin/products_controller_decorator.rb#L142

for some reason product.valid? is returning true but product.errors is not empty:
![Screenshot 2019-06-10 at 13 05 24](https://user-images.githubusercontent.com/1640378/59194929-8717bd00-8b82-11e9-8321-2d1499ac7195.png)

Probably related to the fact that this field unit_description is a delegate in the product model:
`delegate_belongs_to :master, :unit_value, :unit_description`

The fix is to either use product.errors instead of product.valid? here or change something in the model to get product.errors and product.valid? consistent again.

**Comment by luisramos0** [comment]
Just replicated this one in katuma live, v2.5.0

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**RuntimeError** in **spree/admin/products#create**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5db4208c2ab8f4001989c256?event_id=5e816edf00595296c5f60000&i=gh&m=li)
