### ISSUE TITLE
ActiveRecord::StatementInvalid in cart#populate

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3913]
## Description

It looks like adding an item to the cart can fail in rare circumtances. We had more than 8000 events in Bugsnag but it affected only 23 users, mostly in one shop and because of one specific item. The Winter Squash in https://openfoodnetwork.org.au/north-arm-farms/shop.

I can't re-produce it now. But we may need to add some data sanitation to avoid this problem in the future.

## Severity

S3.

## Error in OpenFoodNetwork

**ActiveRecord::StatementInvalid** in **cart#populate**
PG::NumericValueOutOfRange: ERROR:  numeric field overflow
DETAIL:  A field with precision 10, scale 2 must round to an absolute value less than 10^8.
: INSERT INTO "spree_line_items" ("created_at", "currency", "distribution_fee", "final_weight_volume", "max_quantity", "order_id", "price", "quantity", "updated_at", "variant_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5cea270a24cd6a00198343c3?event_id=5cfe27ac004205ebe0580000&i=gh&m=ci)

## Stacktrace

    app/models/spree/order_decorator.rb:161 - add_variant
    app/services/cart_service.rb:47 - cart_add
    app/services/cart_service.rb:41 - attempt_cart_add
    app/services/cart_service.rb:28 - block in attempt_cart_add_variants
    app/services/cart_service.rb:26 - each
    app/services/cart_service.rb:26 - attempt_cart_add_variants
    app/services/cart_service.rb:19 - block in populate
    app/services/cart_service.rb:17 - populate
    app/controllers/cart_controller.rb:14 - block in populate
    app/models/spree/adjustment_decorator.rb:47 - without_callbacks
    app/controllers/cart_controller.rb:11 - populate

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5cea270a24cd6a00198343c3?event_id=5cfe27ac004205ebe0580000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by luisramos0** [comment]
I cant find this error in the AUS bugsnag, is it still there?

**Comment by mkllnk** [comment]
It looks like our data retention of 90 days let this expire. It didn't happen again. I'll close it for now.
