### ISSUE TITLE
Release v2.1.0 Rapid Rasberry

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3920]
- [x] Draft
- [ ] ~~Try to sneak #3836 in...~~
- [x] Test the release
- [x] Deploy to v2 servers

**Comment by RachL** [comment]
@Matt-Yorkley I saw two issues but I think there are related to staging :

- I didn't manage to get a pin on the map whatever the address I've put in.
- Product images couldn't be uploaded

what do you think? Complete notes: https://docs.google.com/document/d/1bb-WDXMUPoItFAVvmK9YrApuLMl1mYZF-2yIFpsO5g4/edit#

On a side note, when I was reviewing the PR, I've learn that now you can edit the home banner. Nice stuff 😎 If this wasn't the main way to get enterprise register, I would have more fun with it (special greetings, shops discovery/special sales...)

![image](https://user-images.githubusercontent.com/6525576/59383336-fc8cb480-8d5f-11e9-83bc-ee7f83b4257a.png)

**Comment by sauloperez** [comment]
lol @RachL . How do you change that :astonished: ?

**Comment by RachL** [comment]
@sauloperez this info will cost you a LOT my friend 😁

**Comment by Matt-Yorkley** [comment]
Update: I've deployed this on UK staging, and image upload and map markers are working.

**Comment by RachL** [comment]
Moving this to ready to go! Wondering what happened to the French staging though...

**Comment by RachL** [comment]
Closing as the deployment was done
