### ISSUE TITLE
ActiveRecord::RecordNotUnique in checkout#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3924]
## Description

The checkout fails with this error. It can happen after the payment which means that the payment will disappear (database rollback). That can cause duplicate charges and happened to an Australian enterprise. It happened in all four reported cases in https://github.com/openfoodfoundation/openfoodnetwork/issues/3925.

This error affected more enterprises though. In those cases we were lucky though and the order was paid by bank transfer instead of credit card.

It first happened 5th May 2019 and was raised 5 times since then (today 13 June 2019).

## Error in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **checkout#update**
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "spree_shipments_pkey"
DETAIL:  Key (id)=(36089) already exists.
: INSERT INTO "spree_shipments" ("address_id", "cost", "created_at", "id", "number", "order_id", "shipped_at", "shipping_method_id", "state", "tracking", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5cce713175df8a001a341c4f?event_id=5cf4a18a003f0fe818910000&i=gh&m=ci)

## Stacktrace

    app/models/spree/order_decorator.rb:175 - block in update_shipping_fees!
    app/models/spree/order_decorator.rb:172 - update_shipping_fees!
    app/controllers/checkout_controller.rb:134 - advance_order_state
    app/controllers/checkout_controller.rb:33 - update

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5cce713175df8a001a341c4f?event_id=5cf4a18a003f0fe818910000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by mkllnk** [comment]
This error is raised when trying to update shipping fees. Saving the shipment tries to create a new record. That indicates that it wasn't created properly in the first case.

https://github.com/openfoodfoundation/openfoodnetwork/blob/080689ccfa6197f32cef6b25dc86c5e68dfd7619/app/models/spree/order_decorator.rb#L35
https://github.com/openfoodfoundation/openfoodnetwork/blob/080689ccfa6197f32cef6b25dc86c5e68dfd7619/app/models/spree/order_decorator.rb#L162-L171

As the comment indicates, it would be good to move this code. It would make more sense to me if the shipments were updated before the payment is processed, not after. But it's actually difficult to tell when this code is called: on each save of a completed order. And there is an explicit call when a line item is destroyed.

**Comment by mkllnk** [comment]
I looked into the checkout flow in more detail.

* The checkout controller is basically calling `order.next` and the order is transitioning from `payment` to `complete`.
* Before that transition, `process_payments!` is called and creates the payment.
* After that transition, `finalize!` is called.
  - `created_at` is touched which triggers after save hooks.
  - All adjustments are closed.
  - All shipments are updated and finalized. (We did that already through after_save before, the after_save hook doesn't make sense in this scenario.)
  - The order is saved. (Triggering after_save again.)
  - Order update hooks are called but I don't know if we have any here. I couldn't find any, maybe in gems.
  - The order confirmation is sent.

That confirms for me that we should get rid of the after_save hooks to update fees on the order. They are inefficient and can fail (at the wrong time).

But I still don't know why we get duplicate shipment ids.

**Comment by luisramos0** [comment]
Nice Maikel.
We are talking about the core of our callback hell here... I have tried to descend into it during the v2 upgrade and delete this update_shipping_fees method, I had to return back to real world with a very broken build and a damaged brain trying to understand how checkout flow and adjustments play together with the callbacks.

I'd just move to v2 asap where we have a db constraint to force 1 shipment per order...

**Comment by luisramos0** [comment]
For reference, I found this tech debt issue related to update_shipping_fees: https://github.com/openfoodfoundation/openfoodnetwork/issues/3375

**Comment by mkllnk** [comment]
I deployed #3968 to Aus production which rescues this exception. So I'm closing this for now. Everything else should be handled in #3925.
