### ISSUE TITLE
Failure to update cloned order cycle

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#3937]
## Description
Failed to update order cycle message when trying to edit the date, product mix,  or suppliers in a cloned order cycle.   Further,  after this failure,  the original/source order cycle experiences the same problem. 

## Expected Behavior
Cloning should result in an autonomous new order cycle that can be edited and modified

## Actual Behaviour
edits to date, product mix,  supplier list in a cloned order cycle with over 1600 products cannot be saved.    And - after attempting these changes the source order cycle - which had been working fine,  also failed to update

## Steps to Reproduce

1.create an order cycle (the problem one above had 1600 products)
2.clone this source order cycle.
3. open the clone and try to change the date,  add/delete suppliers -  failure to update?
4.return to the source OC -  try to add/delete suppleirs -  failure to update?

## Context
OC have to be created from new each week -  with 1600 products,  complex fees,  tagging for different buyer groups...  this is very time consuming.  

## Severity
Suggesting S2 .

## Your Environment

* Version used:
* Browser name and version: latest chrome
* Operating System and version (desktop or mobile): windows 10 
* OFN Platform instance where you discovered the bug, and which version of the software they are using.   first happened when using version 1,   continues after upgrade to 2.1

**Comment by sauloperez** [comment]
We probably didn't mean to close this one. I didn't know the magic comments worked even from a commit.
