### ISSUE TITLE
Staging1 refers to images of staging2

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#394]
For example: https://staging1.openfood.com.au/groups/11 has two images uploaded by users. They are stored on a could server, but on in the directory of staging2:

```
https://s3.amazonaws.com/ofn_staging_2/public/images/enterprise_groups/promo_images/11/original/banner_-_mildura.png?1403518974
https://s3.amazonaws.com/ofn_staging_2/public/images/enterprise_groups/logos/11/original/BLANK_Regional_Brand.png?1403517441
```

**Comment by daniellemoorhead** [comment]
@mkllnk is this still a problem? If so is it low priority?

**Comment by mkllnk** [comment]
Yes, it is still a problem. And yes, it is low priority at the moment. It would become important if someone would like to test a lot of image stuff on staging1 (deleting/uploading).

**Comment by sauloperez** [comment]
This seems to be the same issue as https://github.com/openfoodfoundation/openfoodnetwork/issues/1337

**Comment by sigmundpetersen** [comment]
@mkllnk are there still 2 staging servers for AU? Is this still an issue?

**Comment by mkllnk** [comment]
Well spotted @sigmundpetersen! We have only one staging server now and it's set up correctly. This can be closed, after 4 years of hard work. ;-)
