### ISSUE TITLE
Admin menu bar looks funny, sometimes

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#395]
Depending on browser and window size the menu bar in the admin backend is displayed with offset menu items. The menu is generated by Spree code. The element sizes are probably calculated at the wrong point of time and not general enough.

In order to reproduce: Open the admin interface with Chrome on a large screen.

This problem occurred when the new 'Groups' menu item made the menu a bit crowded.

**Comment by lin-d-hop** [comment]
#gitcull2017
Not enough info to work on this and likely outdated. 
If we need this let's reopen with a clear description (screenshots etc) as this is likely a good first issue.
