### ISSUE TITLE
When deleting a product, orders and fulfillment report shows a 500 error

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3956]
## Description

When I delete a product purchased in an order, I cannot use the orders and fulfillment report anymore.

## Expected Behavior

Even long after a product has been deleted, I should be able to check the order and fulfillments report.

## Actual Behaviour

After an order is placed and then one of its products is deleted, when check the report crashes with the message `undefined method 'name' for nil:NilClass`.

## Steps to Reproduce

1. Place an order
2. Delete one of the products in said order
3. Go check any of the order and fulfillment reports
4. :boom: 

BE's Bugsnag error https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/5d068ad9bd21c60019ca7d36?event_id=5d068ad90041ec272ba70000&i=sk&m=nw

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v2.1.0

## Possible Fix

This is tightly related to https://github.com/openfoodfoundation/openfoodnetwork/issues/3903 and the solution will be similar to https://github.com/openfoodfoundation/spree/pull/41

**Comment by sauloperez** [comment]
I've been thinking about the soft-deletion of products and variants. This bug will be in many other areas of the app, including all other reports. We could remove that `default_scope` to always include deleted rows but then the situation is not any better; we would allow users to place orders with deleted products or use deleted payment methods, for instance :see_no_evil: .

Another option that came to my mind is going back to the previous behavior and forbid deletion of products (isn't that what we had?) so no need to handle soft-deleted products. Then we could perhaps list all the areas affected by this soft-delete. It doesn't sound easy though. There might be soft-deleted products already in our DBs that need to be dealt with.

Or simply accept the fact and spot all places where we should soft-deleted models and fix them one by one. Even if we stick to this, it's worth having the discussion and being aware of it.

**Comment by sauloperez** [comment]
![](https://media.giphy.com/media/AL1yzYEYuPKPC/giphy.gif)

**Comment by luisramos0** [comment]
I think we need to keep delete product and soft deletion is a really important feature for the future.
So, I'd say we need to handle it case by case.
