### ISSUE TITLE
Errors in variant price and missing variant in shop order cycle (producer ID 200275: Sole of Discretion)

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#3961]
## Description

Producer Sole of Discretion noticed that the price of their Lemon Sole (variant 300g Fillet, product ID 203407, variant id 210784) is displaying as £8.78 to the customer whereas price entered by the producer is £8.00. The other variant of this product (2 x whole) displays the correct price to the customer.  
In addition, there are two variants of the product 'megrim' - 300g and 800g. Only the 800g variant is displaying to the customer in their order cycles.
The issues are occuring in the Sole of Discretion order cycles for their OFN shop front.  The shop has no enterprise fees. Both variants of the megrim product are selected on the order cycles.
No other issues found.

## Expected Behavior

-The Lemon Sole Variant 300g fillets should display the price of £8.00 to the customer
-The Megrim should have two variants available to purchase- 800g whole and 300g fillets

## Actual Behaviour

- The 300g fillet variant of lemon sole displays at a price of £8.78 to the customer
- Only the 800g whole variant displays to the customer for the megrim.

## Steps to Reproduce

1. Checked enterprise fees for order cycle and the producer shop
2. Checked relevant variants are selected in the order cycles
3. @lin-d-hop refreshed cache
4. Added new variants to both these products which displayed to customer correctly.

## Context

Incorrect prices displayed to customers and missing products. Disruptive to producer as it means that effectively they are missing out on sales of two of their products.
Order cycles set up which include these products and variants long into the future and so time consuming to add new variants to replaced the corrupted ones not displaying correctly.

## Severity

Not sure s-4? 

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sole of Discretion questions](https://trello.com/c/7OW7buKu/462-sole-of-discretion-questions)

**Comment by lin-d-hop** [comment]
This is a critical feature broken with no workaround.... Which is how we describe S1s.

Personally I think S1 is a bit drastic. I also think that this is likely something small and keep preparing myself for the cringe of shame when a developer tells me the trivial error. Deep breaths. No shame. We're a team... etc.

I am putting S2 on this until we know the cause. If it can affect multiple shopfronts then it is definitely an S2. If it is contained to one shopfront then we can try working around it as this producer does not sell high volumes.

Ping @lbwright22

**Comment by luisramos0** [comment]
Hello, I dont have more time and I'll only be back on Monday but looking at the app I am 100% sure this is a cache problem because 8.78 is in the cache and the price on the db is 8.00.

in the console I see:
- Spree::Variant.find_by_id(210784).price.to_s
8.00

So, this is a cache problem in v1. In v2 we are better prepared to debug and understand these problems with cache.

One test I'd do is to update the price of the variant to 8.01 lets say and verify what happens to the price in the the shopfront. Maybe there's an error on the update process of this variant's price...

**Comment by lbwright22** [comment]
I wondered if there was any update on this and/or how it could be fixed. The user has noticed errors in other products:
Only one variant of fish pie mix and megrim showing
Products not displaying (cause unknown): Monk fillets, Cod, Cuttlefish, Crab meat white, haddock, ling, Loch D. Salmon, Glenarm Organic Salmon, Squid.
I wonder if this could be due to an error in the variant stock level in cache for these products. Products show correctly on order cycle for Mercia hub, just not the Sole of Discretion Shop front itself.

**Comment by lbwright22** [comment]
User has noticed more errors:
Mackerel-fillets 300g variant not showing 
Plaice - fillets price displaying as £5.00 when it should be £5.20

Again I have added new variants which display correctly so that the producer can continue to trade but the ones with errors in them are still in their product list (and used by other order cycles)

**Comment by lbwright22** [comment]
OFN in UK has been updated from v1 to v2 and there is no evidence to show (yet) that this issue will arise in v2. Hence I am closing card
