### ISSUE TITLE
New header displaying badly in Spanish, Catalan & Portuguese

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3967]
## Description
When testing the new header on Katuma, I noticed it is displaying badly for certain language. Basically all language except Italian.

## Steps to Reproduce
1. Go to Katuma's staging
2. Go to a shop
3. Switch between italian and something else

## Animated Gif/Screenshot
Italian:
![image](https://user-images.githubusercontent.com/6525576/59847956-467b2900-9364-11e9-97b1-3025002858af.png)

Catalan:

![image](https://user-images.githubusercontent.com/6525576/59847988-5eeb4380-9364-11e9-95c7-965018485823.png)

## Your Environment

* Version used: v2.1
* Browser name and version: Firefox 67
* Operating System and version (desktop or mobile): Desktop Windows 10

**Comment by luisramos0** [comment]
this should block 2.2.0 release. changing to bug-s2. feel free to change.
