### ISSUE TITLE
Error 500 when trying to empty my cart when shopping at Mary's

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3969]
## Description
I've noticed while testing #3804 that trying to empty your cart on Mary's Online Shop thanks to the little "bin" icon would result in an error 500.

With Maryse or Fred/Fredo/Freddy, couldn't replicate the issue. The page reloads and redirects back to the shop when hitting that icon.

What is making Mary's shop special is that matter?

## Steps to Reproduce

1. Go to a staging server and add item to your cart from Mary's Shop
2. On the /cart URL hit the little bin icon
3. See an error 500

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/60037732-a6e6cf00-96b2-11e9-8172-9a10e2f2a17c.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v2.1
* Browser name and version: Firefox 67
* Operating System and version (desktop or mobile): Ubuntu 19.10

**Comment by Matt-Yorkley** [comment]
The error is:
```ruby
NoMethodError (undefined method `order' for nil:NilClass):
  app/models/spree/calculator_decorator.rb:12:in `line_items_for'
  app/models/calculator/flat_percent_per_item.rb:23:in `compute'
  app/controllers/spree/orders_controller_decorator.rb:148:in `with_open_adjustments'
  app/controllers/spree/orders_controller_decorator.rb:47:in `update'

```

**Comment by Matt-Yorkley** [comment]
The error is at line 12, which was recently changed from this:
```ruby
elsif object.respond_to? :order
        object.order.line_items
```
to this: 
```ruby
elsif object.order.present?
        object.order.line_items
```
