### ISSUE TITLE
Show a friendly message when trying to upload an image in a format different than .png or .jpg

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3975]
## Description
If you upload an image on a product, or create a product with an .svg image for example, the image won't be displayed. Only .png or .jpg are allowed, but the user does not know it.

## Steps to Reproduce
1. Go to `admin/products`
2. Create a product with a .svg image or edit a product image with a .svg file
3. See the display problem

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/60182837-5643b300-9825-11e9-87ff-701d7d519323.png)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v2.1
* Browser name and version: Firefox 67
* Operating System and version (desktop or mobile): Ubuntu 19.10

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**ActiveStorage::IntegrityError** in **active_storage/representations/redirect#show**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/626bc542ec604700086798f6?event_id=62a6033c0094fd2fe1e60000&i=gh&m=li)

**Comment by mkllnk** [comment]
This issue has been unlinked from an error in Bugsnag
[**ActiveStorage::IntegrityError** in **active_storage/representations/redirect#show**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/626bc542ec604700086798f6?event_id=62a6033c0094fd2fe1e60000&i=gh&m=ul)
