### ISSUE TITLE
French prod timeout issue: cannot add enterprise fees

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3978]
## Description
Reported by users. When trying to add a fee, the snail appears with a 504 timeout on https://www.openfoodfrance.org/admin/enterprise_fees/bulk_update

## Steps to Reproduce
1. Log in as the Demo hub (ask me for access) on french prod
2. Go to `/admin/enterprise_fees?enterprise_id=212`
3. Try to add a fee and click "update"
4. See our friend the snail https://www.openfoodfrance.org/admin/enterprise_fees/bulk_update

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/60193455-fefb0e00-9837-11e9-9af8-11e853978487.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v1.31
* Browser name and version: Firefox 67
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
you dont need to add a new fee to replicate, just go to the page and click update.

these are the logs:
```
Started POST "/admin/enterprise_fees/bulk_update" for 78.130.4.9 at 2019-06-26 21:54:01 +0200
Processing by Admin::EnterpriseFeesController#bulk_update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"CAr5EKnBs7t953Fqc6OAvsVA8fbS8e4b9WI2TfuCed8=", "enterprise_id"=>"212", "enterprise_fee_set"=>{"collection_attributes"=>{"0"=>{"id"=>"37", "enterprise_id"=>"212", "fee_type"=>"admin", "name"=>"Marge pour opérations", "tax_category_id"=>"", "inherits_tax_category"=>"true", "calculator_type"=>"Calculator::FlatPercentPerItem", "calculator_attributes"=>{"preferred_flat_percent"=>"15.0", "id"=>"177"}}, "1"=>{"id"=>"73", "enterprise_id"=>"212", "fee_type"=>"admin", "name"=>"Test3", "tax_category_id"=>"", "inherits_tax_category"=>"true", "calculator_type"=>"Spree::Calculator::PriceSack", "calculator_attributes"=>{"preferred_minimal_amount"=>"10.0", "preferred_normal_amount"=>"2.0", "preferred_discount_amount"=>"1.0", "preferred_currency"=>"EUR", "id"=>"424"}}, "2"=>{"id"=>"72", "enterprise_id"=>"212", "fee_type"=>"admin", "name"=>"Test weight", "tax_category_id"=>"", "inherits_tax_category"=>"true", "calculator_type"=>"Calculator::Weight", "calculator_attributes"=>{"preferred_per_kg"=>"5.0", "id"=>"600"}}, "3"=>{"id"=>"", "enterprise_id"=>"212", "fee_type"=>"? object:null ?", "name"=>"", "tax_category_id"=>"", "inherits_tax_category"=>"false", "calculator_type"=>""}, "4"=>{"id"=>"", "enterprise_id"=>"212", "fee_type"=>"? object:null ?", "name"=>"", "tax_category_id"=>"", "inherits_tax_category"=>"false", "calculator_type"=>""}, "5"=>{"id"=>"", "enterprise_id"=>"212", "fee_type"=>"? object:null ?", "name"=>"", "tax_category_id"=>"", "inherits_tax_category"=>"false", "calculator_type"=>""}}}, "commit"=>"Mettre à jour"}
```

**Comment by luisramos0** [comment]
it's a timeout at 1min:
![Screenshot 2019-06-26 at 20 55 37](https://user-images.githubusercontent.com/1640378/60210439-c9185280-9854-11e9-9306-d808bd1ddd11.png)

**Comment by luisramos0** [comment]
the bad workaround is to:
- create the fee
- submit the form
- see the snail
- go back to the list and see that **the new fee is there**
- if necessary (to update the value of the fee for example):
- update the fee
- submit the form
- see the snail
- go back to the list and see the fee is as desired

**Comment by RachL** [comment]
@luisramos0 yes indeed this workaround is working for my demo hub, but not for one of the users who reported it. Could it be that it takes longer sometimes (the timeour occurs before the process creates the fees?)

**Comment by luisramos0** [comment]
yes, could be Rachel.

**Comment by mkllnk** [comment]
The French server config sets a timeout of 2 minutes but nginx has a default of 1 minute. The nginx config was fixed in a recent ofn-install update. I re-provisioned the server to give it the full 2 minutes. The request still times out after 2 minutes.

Next actions:

- [ ] increase timeout to 5 minutes and see if that helps
- [ ] measure the performance locally
- [ ] test v2 locally and check for performance changes
- [ ] refactor code to optimise performance

**Comment by mkllnk** [comment]
### Performance

37% of the execution time is in SQL queries. Around 15,000 queries are performed and most of them are duplicates. They look like this:

```sql
SELECT "spree_variants".id FROM "spree_variants"
 INNER JOIN "exchange_variants" ON "spree_variants"."id" = "exchange_variants"."variant_id"
 WHERE "exchange_variants"."exchange_id" = 19866 AND ("spree_variants".deleted_at IS NULL); 
```

The only variable in here is the exchange id and it's the same for most of the queries. In most of them I've seen two different ids. There is potentially a huge saving here by caching the value. Here the code triggering it:

```
app/models/exchange.rb:94:in `to_h'
app/models/exchange.rb:102:in `eql?'
lib/open_food_network/products_cache.rb:121:in `uniq'
lib/open_food_network/products_cache.rb:121:in `refresh_incoming_exchanges'
lib/open_food_network/products_cache.rb:133:in `refresh_supplier_fee'
lib/open_food_network/products_cache.rb:85:in `enterprise_fee_changed'
app/models/enterprise_fee.rb:64:in `refresh_products_cache'
app/models/model_set.rb:43:in `each'
app/models/model_set.rb:43:in `all?'
app/models/model_set.rb:43:in `save'
app/controllers/admin/enterprise_fees_controller.rb:31:in `bulk_update'
```

**Comment by mkllnk** [comment]
If you call `exchange.variants` it queries the variants and builds ActiveRecord objects. If you call it again, those objects are cached and no further query is needed.

But if you call `exchange.variant_ids` it queries the database everytime. We spend a lot of time querying here. So I tried to switch from `variant_ids` to `variants.map(&:id)` to leverage the caching but the result was much worse. It doesn't involve the database much but Ruby is really busy building objects and comparing them and uses a lot of memory for that.
