### ISSUE TITLE
url/login should go to homepage with login panel open 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#398]
currently goes to old login page, which is confusing

![image](https://cloud.githubusercontent.com/assets/2911176/6460407/21d2b586-c1eb-11e4-8915-7fcebcefb312.png)

**Comment by Jayzz55** [comment]
Hi, just submitted a Pull Request for a fix to this. but found out that Victor has also submitted a fix for this. great job @victornava ! :)

**Comment by victornava** [comment]
This is done. Needs to be merged.

**Comment by sstead** [comment]
I recon this is all good @kirstenalarsen
