### ISSUE TITLE
Display enterprise ID in profile

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3990]
## Description
**- As a:** Super admin (but if too complex all admins)
**- On page:** `/admin/enterprises/ENTERPRISENAME/edit#/primary_details`
**- I want to be able to do:** see the ID of this enterprise

We will be using Zapier a lot, so either we create zaps to have this ID, or we just add it to the enterprise profile.

The ID would only be shown in the PRIMARY DETAIL page, just above the name and would not be editable.

![image](https://user-images.githubusercontent.com/6525576/60523873-cfdb1580-9ceb-11e9-9ab0-284f1c7facbf.png)

## Acceptance Criteria
1. Logged in as an admin I'm able to see the enterprise ID on `admin/enterprises/ENTERPRISENAME/edit#/primary_details`
2. I can't edit this ID.

**Comment by RachL** [comment]
@luisramos0 @Matt-Yorkley @lin-d-hop @kristinalim @mkllnk 

I created this after a discussion with @pacodelaluna whom I always ask to fetch me enterprise ID since we started playing with Zapier.

François would like to tackle this as it his - according to him - super easy. Does anyone objects? 

It would be done as a volunteer contribution but does mean that it will involve some code review, so I don't want it to be a pipe hack :)

Otherwise I will create myself a Zap to do it, the only downside is that all instance have to do it on their side.

**Comment by luisramos0** [comment]
hey @RachL there are many easy ways to get the ID with dev tools, for example, on the product list, right click over any producer name and inspect html:
![Screenshot 2019-07-02 at 20 18 24](https://user-images.githubusercontent.com/1640378/60540285-b3000b80-9d06-11e9-8066-70a34067a772.png)

that value in the html is the enterprise ID.

Also, another way is to use the API:
https://staging.openfoodfrance.org/api/enterprises/managed

**Comment by pacodelaluna** [comment]
@luisramos0 It is easy but not straight-forward if you are not used to it. My idea was just to add it as a disabled field (`OFN ID`) on Enterprise form, `Primary Details` section, before the title. And only for Admin users.

**Comment by mkllnk** [comment]
I would put it under the URL as an additional line. It's super easy and I think the review will be easy as well.

**Comment by RachL** [comment]
@luisramos0 interesting! for hubs, is there another page I can use with dev tools? In production, what do I need to display the API content?

**Comment by luisramos0** [comment]
yes, inventory, inspect the "select shop" select box and the select element contains all the ids as well.

you need to be logged in in production with a user that manages the enterprise.
