### ISSUE TITLE
[mobile ux] Display bug on cart button

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3991]
## In a feature branch or master?
View cart feature branch 

## Description

There's a display bug in `master` at the moment. It's caused by a semi-hidden element that apparently hasn't worked for a while, because of a typo. It's only visible on the medium and small screens.

Here's the current cart button:

![broken_cart](https://user-images.githubusercontent.com/9029026/60526329-0ca50d80-9ce8-11e9-8bbe-949d24a9b9fa.png)

If I fix the missing element (the current shop button) it then looks like this:

![fixed_but_bad](https://user-images.githubusercontent.com/9029026/60526359-2181a100-9ce8-11e9-9bde-42074288b9ef.png)

It's not well styled. 

So the question is: do we want to fix it or remove it?

**Comment by Matt-Yorkley** [comment]
I've fixed the visual bug in #3992, but I've left the non-visible current shop button alone for now.

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley I haven't seen this bug in my travels, can you tell me a) if it's still a problem, and b) whether you fixed it in the PR?

**Comment by daniellemoorhead** [comment]
>@Matt-Yorkley I haven't seen this bug in my travels, can you tell me a) if it's still a problem, and b) whether you fixed it in the PR?

@Matt-Yorkley?

![](https://media.giphy.com/media/MkxZKy77sWoEw/giphy.gif)

**Comment by Matt-Yorkley** [comment]
Fixed :+1:
