### ISSUE TITLE
Duplicate production data to staging server for UK and FR

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3998]
## Description
As discussed in the delivery train meeting, the idea is to install production data on UK and FR staging (for both UK and FR production data).

For France the accounts to keep are :

myriam.boure[at]gmail.com
rachel.arnould[at]gmail.com

For Aus, please keep admin@openfoodweb.org, kirsten@openfoodnetwork.org.au, emily@openfoodnetwork.org.au and maikel@openfoodnetwork.org.au

**Comment by luisramos0** [comment]
@RachL I am planning to do this tomorrow.
you list FR and UK but then list accounts for FR and AU.
I just want to double check: I should go for the 3 of them: stagings UK, FR and AUS all receive their respective live data. right?

**Comment by RachL** [comment]
@luisramos0 yes I think Kirsten added Aus info. I'm pinging @lin-d-hop so if she add UK info yes you can do all 3. Otherwise we will just do AU and FR for now and do UK later on :)

**Comment by lin-d-hop** [comment]
For UK please keep:
spree@example.com
lynne[at]openfoodnetwork.org.uk
nick[at]nickweir.co.uk
sara[at]tamarvalleyfoodhubs.org.uk

**Comment by luisramos0** [comment]
ok, all 3 servers are reset with live truncated and anonymized data, everyone should be able to login with their live credentials in the respective staging server.

**Comment by luisramos0** [comment]
I then tried to update all servers to v2.2.0 and got into trouble... will update asap.

**Comment by luisramos0** [comment]
ok, all servers are working now.

Emails are working in FR staging.
I dont know why the production mail methods dont work in AUS and UK. They must be adapted for the emails to work in AU and UK staging.

**Comment by RachL** [comment]
@luisramos0 how is it working for map data? https://staging.openfoodfrance.org/map I don't see anything there

**Comment by luisramos0** [comment]
tbh I have no clue. the settings were copied from live but probably it's not working for some reason.
I have spent quite a lot of time doing this already. I am not sure I should spend more time getting these instances perfect. what do you think?

**Comment by RachL** [comment]
Staging FR can still not upload images, but this was pre-existent. This can be close for the FR part. @kirstenalarsen et @lin-d-hop can you confirm for AU et UK?

**Comment by RachL** [comment]
Ok actually let's maybe open specific issues for each problem on staging server. I'm closing this, thank you @luisramos0 !
