### ISSUE TITLE
Orders stuck in 'Payment' state - what has happened to these customers?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4003]
## Description
While investigating #3925 I was exploring 'uncompleted orders' and particularly those that are stuck in 'Payment' state. This could be related to case 
c) Customer's payment failed but customer was not notified (so order was presumed successful)

@mkllnk commented in Slack that payment state means that the payment has failed e.g. invalid credit card, but orders should be put back into cart state .. so if this is not happening, what is happening to these users / orders - are they just disappearing?
[image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/80c5d6d4-2b49-45e1-b7d9-e4daab43fd32)

I am sad to report that there are quite a few - on Aus production 175 in total. While some of these go back a long way, some of them are more recent and in current active hubs. From a quick look through some, it seems that all are connected to credit cards. Recent ones Stripe, older ones paypal.

When I follow through into the order and then into the payment I see that it is in state 'checkout'
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/b0c7064d-fff9-4007-8ebe-5ac4eee24359)

## Expected Behavior
- We shouldn't have orders stuck in Payment state - if the Payment fails the Order should be in Cart and the payment showing as failed
- If a Customer's credit card fails, they should be notified
- [Then what - I'm not sure! TBD] Notify customers to contact Hub with updated credit card details? Update their details? 

## Actual Behavior
I haven't yet managed to replicate this - will work on it. Currently hypothesis that it is a failed credit card

## Steps to Reproduce
To see the problem: 
1. go to orders, untick 'show only completed orders' and select State 'Payment' . . 
working on it
2. and/or go to a recent order cycle and just see all of them 

Replication not yet managed
1.
2.
3.
4.

## Context
It has scared me. Trying to work out problems with duplicating and missing payments and finding all these floating around 

There is also #4004 which I'm still trying to work out if it is a problem

## Severity
I think this will become either S1 or S2 . . putting S2 until we're clearer on what it is

Taking credit card payments and getting customer orders is a critical feature. Notifying customers to 
bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround

## Your Environment
MacOS

## Possible Fix
Handling failed credit card payments?

**Comment by kirstenalarsen** [comment]
Just checked with a card I have blocked at my bank and I get this error
http://recordit.co/vAYUoFC51j
![image](https://user-images.githubusercontent.com/2911176/60640662-8580a280-9e6b-11e9-841a-4d7aa05c6f02.png)

**Comment by kirstenalarsen** [comment]
Here's one that's paypal not Stripe
![image](https://user-images.githubusercontent.com/2911176/60640768-15265100-9e6c-11e9-8d61-6b9178109889.png)

**Comment by mkllnk** [comment]
This is probably linked to an error we have seen in Bugsnag a few times: https://github.com/openfoodfoundation/openfoodnetwork/issues/4005

**Comment by luisramos0** [comment]
yeah, it's the state machine not working for some reason after a failed payment but the user will see an error at checkout.
so it doesnt mean it's a serious problem, right? the payment fails, the checkout errors out because the state machine fails, the user sees an error and the order stays in payment state.
we need to understand why the state machine fails to move back to cart but I wouldnt assume that an order in "payment state" is an s1 or s2. it's just the wrong workflow state for a failed order.
does this make sense @kirstenalarsen ?

**Comment by luisramos0** [comment]
moving to S3 just to keep it more realistic according to my understanding.
please feel free to update back to S2 when you get back to this one @kirstenalarsen

**Comment by luisramos0** [comment]
for working on #4005 and fixing it in #4252, I'd make 4252 close this one as well based on the following explanation: currently, all failed payments (stripe of credit card) of pickup orders (ship address not required) will be stuck in payment state. These issue is just those orders: something went wrong with the payment and without ship address the restart order workflow (move it to cart) failed with bugsnag reported above and in #4005

Does this make sense?

I dont have super powers in AUS live but we can have a look at some of these orders above and check if the ship method is delivery of not.

**Comment by luisramos0** [comment]
Moving to code review together with #4005 and #4252.

**Comment by luisramos0** [comment]
Based on the work done in #4252 if the payment fails we are now notifying the user in more cases and showing a lot less snails :tada: (the snail was always showing in payments failed for pick up orders) and in these we are able to reset the order back to cart state because these pick up orders now have a shipping address (the distributor address).

with this, I don't think we are fixing all cases where order gets stuck in payment state, but definitely most of them.
Shall we leave this open and check in the future or close it?

**Comment by RachL** [comment]
@luisramos0 I feel we can close this and re-open if needed.

**Comment by sigmundpetersen** [comment]
I agree, let's open a fresh one on next report

**Comment by luisramos0** [comment]
:+1:
