### ISSUE TITLE
[Performance] admin edit order cycles queries

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4006]
### What we should change and why (this is tech debt)

Part 1 of the N+1 issues with Admin Order Cycles. See spike here: https://github.com/openfoodfoundation/openfoodnetwork/issues/3858

**Pain point:** `/admin/enterprises/for_order_cycle.json`

The `app/serializers/api/admin/for_order_cycle/supplied_product_serializer.rb` calls these methods on every variant the enterprise owner has access to:

```
lib/open_food_network/variant_and_line_item_naming.rb:13:in `options_text'
lib/open_food_network/variant_and_line_item_naming.rb:42:in `unit_to_display'
lib/open_food_network/variant_and_line_item_naming.rb:30:in `full_name'
app/serializers/api/admin/for_order_cycle/supplied_product_serializer.rb:22:in `block in variants'
app/serializers/api/admin/for_order_cycle/supplied_product_serializer.rb:22:in `variants'
app/controllers/admin/enterprises_controller.rb:100:in `block (2 levels) in for_order_cycle'
app/controllers/admin/enterprises_controller.rb:98:in `for_order_cycle'

SELECT "spree_option_values".* FROM "spree_option_values" INNER JOIN "spree_option_types" ON "spree_option_types"."id" = "spree_option_values"."option_type_id" INNER JOIN "spree_option_values_variants" ON "spree_option_values"."id" = "spree_option_values_variants"."option_value_id" WHERE "spree_option_values_variants"."variant_id" = 203369 ORDER BY spree_option_types.position asc; 
```

It's fetching `variant.fullname` via the join tables: `spree_option_values_variants` and `spree_option_types` in `variant_and_line_item_naming.rb`. I attempted to add some simple preloading for these values before the serialization takes place, but it didn't seem to work for some reason...

### Context

This is related to the `admin edit order cycles` spike: https://github.com/openfoodfoundation/openfoodnetwork/issues/3858

**Comment by luisramos0** [comment]
this is not obvious because there's lots of logic inside variant_and_line_item_naming#full_name
and on top of that there's the visible_for scope.

**Comment by Matt-Yorkley** [comment]
See comment here for more details: https://github.com/openfoodfoundation/openfoodnetwork/pull/4426#issuecomment-549271566
