### ISSUE TITLE
Make OFN independent of Spree

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4013]
### What we should change and why (this is tech debt)
As discussed in [this thread](https://community.openfoodnetwork.org/t/bye-bye-spree-or-spree-v2-1-and-beyond/1598) we agree OFN will gradually move away from depending on Spree: basically due to our heavily customised spree code that makes spree upgrades very painful, we stopped taking the benefit of re-using the third party. And not having our code split between spree code and customization will make our code a lot cleaner.

We started by removing the dependency to spree frontend in #3676 
The next steps will be to remove spree_aut_devise (#4014) and spree_api (#4054).
After that spree_backend will not be a big challenge because we already customize most of the code. (#4050) 
Finally removing spree_core will be the biggest challenge.

### Context
See community thread linked above.

### Impact and timeline
This is a major step in OFN architecture as it will open many doors for simplification.
Apart from spree_core, this will not be a difficult task to execute.

**Comment by RachL** [comment]
This can now be closed 🎉
