### ISSUE TITLE
An order can be set to repeat by the customer

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#402]

**Comment by pmackay** [comment]
@RohanM @oeoeaio could you please add some thoughts on a implementation strategy for this one? 

thanks!

**Comment by NickWeir63** [comment]
would it help to know how the stroudco developer set up the stroudco repeat order code?

**Comment by lin-d-hop** [comment]
We had a long chat about this today. It is a big piece of work to have the functionality we need to make it practical. There is a desire to have a smaller version that allows a product to be repeated, but I think this is too specific to be useful to our use cases. 

I've moved this into backlog to reflect the current state of play. Even Stroudco aren't using this functionality at the moment after having it developed... so are we happy for this to be a backlog issue for us as well?

The discussions on this will be captured here:
http://community.openfoodnetwork.org/t/standing-repeating-orders/82

**Comment by pmackay** [comment]
@lin-d-hop was #403 closed because there isnt a logical way to separate these things? For this story to be complete, that both repeats and holidays are required?

**Comment by lin-d-hop** [comment]
The spec for this is captured here: http://community.openfoodnetwork.org/t/standing-repeating-orders/82

Thus the functionality of #403 is captured in this issue.

This story is yet to be separated into tasks. When it is the tasks will be very different from the combo of #402 and #403 so this separation does not make for a useful or logical split.

**Comment by lin-d-hop** [comment]
Closing as this is now being handled in the Standing Orders epic!
