### ISSUE TITLE
Out of stock 'on hand' items are showing in the shopfront (V2)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4021]
## Description

Following #4018, I have an 'on hand' item with a negative stock level
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a8927886-5d39-4ab3-9d6b-8396043220e4)

This item is showing in the shop
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/e5ea2d8b-bf12-41a5-a981-2fa6c14e961d)

When I try to add it to my cart I see this error message
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/c2dfa69d-09ed-4206-afe4-1524c67b8bf9)

and then the stock is shown on the shop page as if it is in my order
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/d9637aa3-c306-4243-aab4-bb08219e38b2)

I can place the order and it is correct i.e. doesn't put -1 cheese in my order or reduce what I pay
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/74313ea8-699a-4788-8dcf-a7464907cca4)

Cheese stock is still at -1 and my order in backend is correct
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/0b2df2ce-b545-47a4-96b4-e7e35a3e60ed)

Report is not showing item in my order at zero (just checking this one for @tschumilas)  showing fees
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/b7adb847-bb54-4394-857d-f02d3700777a)

## Expected Behavior
If an item is NOT set to on demand, and is out of stock (which includes both 0 and negative numbers) it should NOT show in shop 

## Actual Behavior
It appears in the shop and doesn't display out of stock message until customer tries to add to cart. Then shows as negative item in shop

## Steps to Reproduce
Hmmmm . . as above . .
However, I just attempted to reproduce this from a standing start i.e. without following the duplicate order set-up of #4018 and the shop seems to be ok - as in -ve stock items that I just set in the Bulk Products page are behaving correctly and not showing in the shop. I have also manually switched those from on-demand to on-hand etc . . could I have set something that was previously vague?

## Context
Trying to work out #4018 and discovered this

## Severity
s3 I think, even s4? - this shouldn't happen and will confuse users, but should only happen in rare cases following the duplicate order problem, and doesn't affect the checkout process or the order

## Your Environment
MacOS

**Comment by mkllnk** [comment]
Closing in favour of #4020. ;-)
