### ISSUE TITLE
Release v2.2 Lupin

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4023]
Release draft:
https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-bc26cd8c27f728c5b31c

Testing notes:

https://docs.google.com/document/d/1ND4AegbImmFgRKuBRiIDy-nDWrIMBk_gqagGio-fERY/edit#heading=h.4ctypvfojpgm

**Comment by RachL** [comment]
@luisramos0 I'm waiting for my OC to end in order to see if subs emails are working and I haven't had a look at the content of the release itself yet just a large sanity check.

Stripe field for credit card is not editable and 3 reports are failing. Could this be linked to a particular PR?

I need to go right now, but I can open issues later.

**Comment by luisramos0** [comment]
Testing depends on the test data you are using. I dont think we are testing with the sample data.
I undeleted all products from the DB in katuma stg and the packing report started working, so definitely related to deleted products. 
We only fixed orders and fulfillments report in this release #3964
Do we know if other reports work in production if there were deleted products in the system?

**Comment by RachL** [comment]
@luisramos0  my production access is messed up on katuma (because of deleted products). can you check as super admin? Or maybe @sauloperez ?

**Comment by RachL** [comment]
Alright so stripe is working thanks @mkllnk ! For the reports #4016 is open.

And I couldn't reproduce the bug on bulk invoice printing. This is ready to go!

**Comment by luisramos0** [comment]
I have published the release :tada:
with that bug this is not going to make the big instances, so I removed the excitement part from the release notes :-)

**Comment by luisramos0** [comment]
thanks @RachL!!!!

**Comment by mkllnk** [comment]
Well done, @luisramos0 and @RachL. This release is great for current v2 instances. The rest just has to wait a bit longer. @RachL I'm not sure what that means for the France roll-out schedule.

**Comment by RachL** [comment]
@mkllnk I will test everything  today and Monday. If everything passes I guess we still can keep the 23rd, otherwise (especially if we see something big coming up from Theresa's investigations) we need to postponed. I have no idea what it means in terms of dev availability. Do you plan any holidays after? @luisramos0 you are off in August right?

**Comment by mkllnk** [comment]
Maybe I will take a long weekend towards the end of August. But that's nothing that would be in conflict with the rollout.

**Comment by luisramos0** [comment]
I am off two weeks in August week of the 5th and the 19th.
