### ISSUE TITLE
Add grey line in main header

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4034]
## Description
Yuko's header design was showing a grey line at the bottom of the main header.

Very useful when you scroll on a white background.

## Expected Behavior

![image](https://user-images.githubusercontent.com/6525576/61134637-52b85900-a4c0-11e9-9db7-2fd4e82a230d.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/6525576/61134283-978fc000-a4bf-11e9-9a95-5c1d9851e28b.png)

## Steps to Reproduce

Just scroll on any page on a instance on v2.2 and onwards

## Your Environment
* Version used: v2.2
* Browser name and version: Any
* Operating System and version (desktop or mobile): Any

**Comment by Matt-Yorkley** [comment]
Whilst we're making issues for small tweaks, I noticed the nav bar was scaled down recently but the logo was not, it should have a `max-height` of 44px (according to Zeplin):

![max-height](https://user-images.githubusercontent.com/9029026/61139370-1c2f0e00-a4c1-11e9-9b1c-86b2f1e2de67.png)
