### ISSUE TITLE
Managers are not able to delete line items from orders anymore

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4038]
## Description
Hub managers should be able to delete line items from orders in the order edit page. This was possible in v1, and it is not in v2 anymore.

## Steps to Reproduce
1. Login with rachel.arnould[at]openfoodfrance.org on French production (v1.31)
2. Go to `/admin/orders/R854846648/edit` you will see this:
![image](https://user-images.githubusercontent.com/6525576/61207453-6c8eb180-a6f5-11e9-9336-a614398ec673.png)

3. Login with the same account on French staging (v2.2)
4. Go to `/admin/orders/R854846648/edit` you will see this:
![image](https://user-images.githubusercontent.com/6525576/61207508-90ea8e00-a6f5-11e9-8c74-104882e2f9c4.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: see above
* Browser name and version: Firefox 67 desktop on Ubuntu 19.10

**Comment by luisramos0** [comment]
this is a Spree 2.0 bug fixed in Spree 2.4: https://github.com/spree/spree/pull/5624

**Comment by luisramos0** [comment]
@RachL @tschumilas there is a problem in the way we are showing the line items in the order edit page right? is there an issue for it? #4043 is the perfect moment to fix it.

**Comment by tschumilas** [comment]
On the order edit page,  the variants all appear as the primary product.  Below -  how my hollyhocks are entered (different colours are different variants),   and how the order shows.  The invoice shows correctly.
![how the variants are entered](https://user-images.githubusercontent.com/13171778/61236026-001bae80-a705-11e9-804e-f168baaf5c17.jpg)
![variants appear as primary product](https://user-images.githubusercontent.com/13171778/61236032-06118f80-a705-11e9-9b18-bf66cfc7443b.jpg)

**Comment by luisramos0** [comment]
thanks, I'll fix that as well, very easy.

**Comment by luisramos0** [comment]
ok, variant names change done in the PR :+1:
