### ISSUE TITLE
Shop product list pagination

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4042]
### Task
- Add pagination to the shop products list, so that only a small number of products display initially in the shop and the user interacts with the page to display more.

- **STILL TO BE DETERMINED:** What is the best design for implementing this? Do we make it an auto-magical display of the next part of the list when they scroll to the bottom? Or traditional 1-2-3-4-etc page buttons and/or next-previous buttons? Or just a load more button? And what happens if they go away and then come back to the page, do we take that user back to the first part of the list, or can we remember where they were?

### Acceptance Criteria
As a user
When I first go to a shop
Then I will see a truncated list of products
And ...?

### Screenshots
coming once solution design completed.

**Comment by Matt-Yorkley** [comment]
I think #4040 and #4041 will have to be done at the same time as this, they can't be separated.
