### ISSUE TITLE
Release v2.2.1 Duhat

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4046]
Release draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-77c936d81fb1c5a609b6

**Comment by RachL** [comment]
@kristinalim I add 3 issues while testing:

1. I can't upload an image on a product but that's okay, it worked on katuma staging so this is a staging FR issue
2. Paying with paypal puts orders into a wrong shipment state, but I think like Luis that it is an s3 not blocking the release. Will open an issue for this one.
3. While wanting to test the inventory I've noticed that I can't access to the demo shop anymore (I could before staging the release), I get an error 500:

https://staging.openfoodfrance.org/hub-demo-open-food-france/shop

![image](https://user-images.githubusercontent.com/6525576/61375728-e4004480-a89f-11e9-9ac9-61f163c38aee.png)

I've the same error on Katuma's staging if I try to access the multishop OC on Mary's Online Shop. The error that was trigered was this one: https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1563366891000400 

Any clue @sauloperez @luisramos0 @kristinalim ?

Full testing notes: https://docs.google.com/document/d/1PthwBN5sLIO50uzLCi_FW4IREhnW-I3_7T9exO6i-cY/edit

**Comment by RachL** [comment]
If I understand clearly the errors I'm seeing are already pre-existing. So I'm moving this to ready to go.

**Comment by kristinalim** [comment]
Thank you, @RachL! :slightly_smiling_face:

I've published the release: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v2.2.1

**Comment by sauloperez** [comment]
The agreement was that the release manager in charge needs to at least coordinate the deployment of all servers :warning: so according to https://github.com/openfoodfoundation/ofn-install/wiki/Current-deployment-status, that's at least DE, BE, ES and CA.

I can do it myself since I'll deploy with https://github.com/openfoodfoundation/ofn-install/pull/471 on Katuma tomorrow what do you say @kristinalim ?

**Comment by kristinalim** [comment]
@sauloperez I was actually planning to deploy today, but still need to follow the discussion in https://github.com/openfoodfoundation/ofn-install/pull/471 for implications and extra steps. It would indeed be safer if you do this @sauloperez - please do.

**Comment by sauloperez** [comment]
If you prefer I can go with CA later this week (I hope tomorrow) while you deal with the other v2 instances.

**Comment by kristinalim** [comment]
@sauloperez I've deployed to Belgium and Germany. Germany also does not use S3 and is affected by https://github.com/openfoodfoundation/ofn-install/pull/471, but it is fine now.

I'll handle Canada too if that's okay - it should be similar to Germany.

**Comment by kristinalim** [comment]
FYI, this has already been deployed to all of ES (done by @sauloperez), DE, BE, and CA. https://github.com/openfoodfoundation/ofn-install/wiki/Current-deployment-status

**Comment by luisramos0** [comment]
amazing!!!
