### ISSUE TITLE
Producers can choose when they trade

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#405]

**Comment by pmackay** [comment]
@NickWeir63 can you clarify what this means? Is it whether they are included in an order cycle? Or which days they can trade within a cycle?

**Comment by NickWeir63** [comment]
it is whether they are included in an order cycle or not

**Comment by lin-d-hop** [comment]
Particularly that producers can opt in or opt out of an order cycle for a hub. Possibly this functionality already exists?

**Comment by pmackay** [comment]
@kirstenalarsen can you comment on whether any of this feature is already available?

**Comment by kirstenalarsen** [comment]
will do when @oeoeaio has finished the card he is working on. Producers will not be able to add themselves to OC for now (Coordinator keeps control of that) but they will see the Order Cycles they're in and be able to remove themselves from it

**Comment by lin-d-hop** [comment]
Hi @oeoeaio @kirstenalarsen 
Just wondering how this has progressed (and if we need to find any time for it)? Will you update this issue to keep us in the loop?
Cheers dears :-)

**Comment by lin-d-hop** [comment]
Confirmed with @kirstenalarsen that producers can now update both products and their whole self for an order cycle.

Closing :-)
