### ISSUE TITLE
Make OFN independent of spree_backend

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4050]
### What we should change and why (this is tech debt)
Most of spree_backend code is overriden in OFN thus creating a mess between OFN code on top of spree code. By removing spree_backend and moving what's needed to OFN, working with our code base becomes a LOT easier.

Before we do this we need to finish de-deface all spree_backend views as part of #2807, this is very close to completion now :tada:

After this is done, we can move the views and controllers that are not in OFN yet:
- 8 in the config space:
  - - [X] countries, states and zones #4290
  - - [X] general settings, image_settings and mail methods #4289
  - - [X] tax_categories, tax_rates and tax_settings #4292
  - - [X] taxonomies and taxons #4291
  - - [X] shipping_methods and shipping_categories #4269
  - - [X] payment_methods (merge controllers) #4371
- 5 in the product space:
  - - [X] images (copy controller and views to OFN) #4372
  - - [x] option_types and option_values (copy controllers and views to OFN) moved in #4389 but removed in #4397
  - - [x]  prototypes - the prototypes feature is not used since 2013 #4395
  - - [x] product_properties and properties - (copy properties views and the controllers) #4449
- 1 in the orders space:
  - - [x] return_authorizations (copy views and controller) #4450
- and 1 for user searches:
  - - [x] search (merge controller and get rid of rabl view, is this really used in the users admin page?) #4511

These are the 9 views we dont need to copy because we dont use them in OFN: banners, promotion_actions, promotion_rules, promotions, stock_items, stock_locations, stock_movements, stock_transfers, trackers (we should remove GA support).

We have 10 controller decorators that need to be merged with the original controllers (all code in original controller that is not needed should not be copied):
  - - [x] adjustments_controller_decorator.rb #4515
  - - [x] base_controller_decorator.rb #4512
  - - [x] orders_controller_decorator.rb #4513
  - - [x] customer_details_controller_decorator.rb #4513
  - - [x] overview_controller_decorator.rb #4514
  - - [x] payments_controller_decorator.rb #4509
  - - [x] products_controller_decorator.rb #4508
  - - [x] variants_controller_decorator.rb #4508
  - - [x] reports_controller_decorator.rb #4507
  - - [x] resource_controller_decorator.rb #4510
  - - [x] search_controller_decorator.rb #4511

And we have 3 controllers that are not decorated in OFN but may be needed, or maybe not:
  - - [x] line_items_controller.rb (not needed)
  - - [x] stock_items_controller.rb (not needed)
  - - [x] inventory_units_controller.rb (not needed)

Spree views in spree/admin/shared that may be needed:
  - - [x] _destroy.js.erb #4588
  - - [x] _new_resource_links.html.erb  #4588
  - - [x] _translations.html.erb  #4588
  - - [x] _address_form.html.erb #4513
  - - [x] _update_order_state.js #4513
  - - [x] _calculator_fields.html.erb #4585
  - - [x] _address.html.erb (not needed)
  - - [x] _alert.html.erb (not needed)
  - - [x] _order_details.html.erb (not needed)
  - - [x] _report_criteria.html.erb (not needed)
  - - [x] _show_resource_links.html.erb (not needed)

The trickiest part of this task (but also one of the best!) will probably be the clean up of the JS code under /assets as we should only copy what is needed. I reckon not much will be copied. This will be tricky because this is not angular code.

Other things that need to be copied: CSS, helpers and routes.

### Impact and timeline
There are a few hundreds of lines of code that need to be moved around but just imagine how much better the OFN codebase will look after this, not a single controller_decorator!!!!

**Comment by RachL** [comment]
@luisramos0 I've just realized you won't be there at next delivery train meeting. Before going on holiday can you just drop a line here explaining why this is in dev-ready? To my knowledge we didn't prioritize this one, but maybe I'm wrong.

**Comment by luisramos0** [comment]
This is normal tech debt backlog, every dev has some time to continuously do tech debt issues and they come to dev ready as we select them. I did spree_auth_devise and now I will do this in my tech debt time (last few weeks, on my toggle, it shows as 15% of my time).

This is different from the "api clean up" work in dev ready which (although marked as tech debt) is prioritized work.

I pointed Hugo to this one because I thought it would be a great restart or him, and it was because he already did this in the past. The action now could be to point Hugo somewhere more into the actually backlog priorities.

**Comment by RachL** [comment]
Ah thanks for explaining! I didn't know that all the dev were doing this. I will add this to the agenda of Tuesday, just to be sure how we are handling tech debt. I guess if it was unclear for me it might have been unclear for other people.

**Comment by RachL** [comment]
@luisramos0 ah :-) so you confirmed my suspiscion : #4595 is needed to close the work on spree_backend then?

**Comment by luisramos0** [comment]
yes, that's why I included it inside this epic. Sorry, I only see now you moved it to test ready. I thought I did it, otherwise I'd have clarified.

I only need #4511 and #4620 tested/merged. Then I will prepare #4617 and #4621 to get all this finished 💪
