### ISSUE TITLE
User sign up process not working

### ISSUE THREAD

**Issue by CliffordNetwork** [openfoodfoundation/openfoodnetwork#4052]
Hi,

Our user log in process doesn't appear to work. When you enter new user detials and hit Sign up now it does nothing, no reponse at all. 

In the logs i seee this though: 

Started POST "/user/spree_user" for 85.255.233.25 at 2019-07-16 12:28:50 +0000
Processing by UserRegistrationsController#create as JSON
  Parameters: {"spree_user"=>{"remember_me"=>0, "email"=>"jim.j.clifford@domain.com", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "return_url"=>"https://redes.smartfarmer.pt/#/login", "user_registration"=>{"spree_user"=>{"remember_me"=>0, "email"=>"jim.j.clifford@icloud.com", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "return_url"=>"https://redes.smartfarmer.pt/#/login"}}
  Rendered shared/mailers/_signoff.html.haml (4.2ms)
  Rendered shared/mailers/_social_and_contact.html.haml (8.0ms)
  Rendered spree/user_mailer/confirmation_instructions.html.haml within layouts/mailer (23.9ms)
  Rendered layouts/mailer.html.haml (38.2ms)
  Rendered spree/user_mailer/confirmation_instructions.text.erb (2.6ms)

This is a log in attempt to see if it actually set it up but just didn't render the pages...

Started POST "/user/spree_user" for 85.255.233.25 at 2019-07-16 12:29:06 +0000
Processing by UserRegistrationsController#create as JSON
  Parameters: {"spree_user"=>{"remember_me"=>0, "email"=>"jim.j.clifford@domain.com", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "return_url"=>"https://redes.smartfarmer.pt/#/login", "user_registration"=>{"spree_user"=>{"remember_me"=>0, "email"=>"jim.j.clifford@icloud.com", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "return_url"=>"https://redes.smartfarmer.pt/#/login"}}
Completed 401 Unauthorized in 32.4ms (Views: 0.5ms | ActiveRecord: 4.9ms)

Any help would be greatly appreciated.

**Comment by luisramos0** [comment]
Hi @AngelHeadedHipsters thanks for reporting the issue.

As mentioned [here](https://github.com/openfoodfoundation/ofn-install/issues/392#issuecomment-483175143) before we continue with this support process someone from your organisation needs to sign the OFN pledge: https://community.openfoodnetwork.org/t/ofn-community-pledge-v1-0-1-june-2017/948

ping @montejunto
Let us know if you need anything else from our side to do that ❤️

**Comment by sigmundpetersen** [comment]
Is this good now @montejunto?

**Comment by montejunto** [comment]
yes this is ok now @sigmundpetersen , all tests taken in consideration it seemed it was internal server problems related to firewall and closed ports.

**Comment by sigmundpetersen** [comment]
Great thanks!
