### ISSUE TITLE
Delete a product that is sold in an OC and all buyers with this item in their cart will see an error 500

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4053]
## Description
As a manager, if I delete a product that is sold in an OC, all buyers with this item in their cart will see an error 500 when trying to reach the website.

## Steps to Reproduce
1. As buyer, add a variant in your cart
2. In a private windows, connect as a manager and delete that product while leaving the OC open
3. Try to reach the website as a buyer again (ANY page) and you will see an error 500, 

## Animated Gif/Screenshot
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/ffae204a-96d7-4ea3-a3b1-9a2f66f6d6b6)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop Ubuntu 19.10

**Comment by mkllnk** [comment]
This corresponds to the following error in Bugsnag:

```
bundler/gems/spree-46d6f8f5fd43/core/app/models/spree/price.rb:29:in `check_price': Price must belong to a variant (ActionView::Template::Error)
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:407:in `_run__821922957767654710__validate__695418356367962835__callbacks'
...
    from bundler/gems/spree-46d6f8f5fd43/core/lib/spree/core/delegate_belongs_to.rb:42:in `block (2 levels) in delegate_belongs_to'
    from lib/open_food_network/scope_variant_to_hub.rb:16:in `price'
    from app/serializers/api/variant_serializer.rb:6:in `price'
    from (eval):11:in `_fast_attributes'
    from gems/active_model_serializers-0.8.4/lib/active_model/serializer.rb:456:in `attributes'
...
```

The name of the error can change. I also saw a `RuntimeError`. You can search for `Price must belong to a variant` in Bugsnag to find these errors.

I couldn't find this error in Katuma production nor in Canada production. But we don't know if this would happen on the current v1 instances after the upgrade.

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**ActionView::Template::Error** in **spree/home#unauthorized**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d5f3078254edb00195cfa4a?event_id=5d5f363b004db75298640000&i=gh&m=li)

**Comment by mkllnk** [comment]
@RachL, what was your workaround? This just happened to Emily. She solved it by closing the affected order cycle which clears out the cart. Another option could be to find the cart (order in state 'cart') as another manager and remove all line items.

**Comment by Matt-Yorkley** [comment]
I just encountered this in development whilst trying to replicate a different issue. It's really nasty.

**Comment by mkllnk** [comment]
I vote for upgrading this to s2: A hub manager can trigger this bug without knowing and suddenly it has s1 impact: everything is broken for some users.

**Comment by sigmundpetersen** [comment]
@RachL is this the same as #3907 ?

**Comment by RachL** [comment]
@sigmundpetersen not sure. In 3907 I didn't have an error 500 but maybe the bug has evolved since then? Maybe worth to check both at the same time.

**Comment by lin-d-hop** [comment]
I think this is related to #3907 

I think this should be upgraded to S2.

This is causing more issues than the one's reported already. A few details in #3907 but I'll create an issue too.

I think the solution to this needs some real inception.... it is not a quick fix. It is pretty fundamental about how we handle deletes and relates to Network Feature, Delivery Note, Invoicing....
