### ISSUE TITLE
[API] Fix api/product endpoint, most calls are not including the supplier attribute in the response

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4056]
## Description
The product api endpoint is not consistently returning the supplier of the product.

## Expected Behavior
supplier should always be returned.

## Actual Behaviour
supplier is not returned.

## Steps to Reproduce
The spec spree/Api/products_controller_spec is verifying what attributes are returned in each case, these lists of attributes need to be reviewed. supplier is the main missing attribute.

**Comment by Matt-Yorkley** [comment]
Is this another soft-deleted variants issue?

**Comment by luisramos0** [comment]
No, I forgot to mention context
This comes from removing spree_api #4054 and merging spree api code with existing OFN api code (/api/products) and verifying the inconsistencies... supplier is just an example #mess
