### ISSUE TITLE
Subs page not displaying if a line item in an order was deleted

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4062]
## Description

In French production, we cannot reach the demo hub subscription page: there is an infinite spinner. A line item with no variant is causing this.

## Steps to Reproduce
1. Log in as rachel.arnould[at]openfoodfrance.org or super admin
2. Try to reach `/admin/subscriptions` for the Hub demo Open Food France
3. The spinner shows up but never ends

## Animated Gif/Screenshot
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/3edf9052-1e64-4b4f-a686-814cba7b5aca)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used:v.2.2.1
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Ubuntu 18

## Possible Fix

 
The underlying issue is a line item with a missing variant. It probably got deleted at some point.

```
app/serializers/api/admin/subscription_line_item_serializer.rb:8:in `description': undefined method `product' for nil:NilClass (NoMethodError)
```
https://app.bugsnag.com/open-food-france/open-food-france-prod/errors/5d36638487f0ee0018332a37

A simple check for `nil` can fix the serializer. But we also need to find out how this can happen. We should either prevent the deletion of a variant that is still in use or update all subscriptions or make line items aware of deleted variants.

This is a duplicate of #3948.

**Comment by Matt-Yorkley** [comment]
I have a feeling this could be fixed already...

**Comment by luisramos0** [comment]
still broken...

replicate:
- create subs with product
- delete product
- broken subs page

exception:
```
NoMethodError (undefined method `product' for nil:NilClass):
  app/serializers/api/admin/subscription_line_item_serializer.rb:8:in `description'
  app/controllers/spree/admin/base_controller_decorator.rb:89:in `render_as_json'
  app/controllers/admin/subscriptions_controller.rb:26:in `block (2 levels) in index'
  app/controllers/admin/subscriptions_controller.rb:15:in `index'
```

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Subscription tab not loading](https://trello.com/c/Xs0toHs0/560-subscription-tab-not-loading)
