### ISSUE TITLE
[API clean up] API exemplar

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4070]
### What we should change and why (this is tech debt)
To build a consistent API we need a well documented guie to create API endpoints and a good exemplar where the best practice is described and used.
We should probably take [one existing API endpoint](https://app.swaggerhub.com/apis/luisramos0/the-open_food_network/0.1), change it to the agreed best practice and document it on the wiki.
One particularly important dimension here is the pagination solution.

### Context
This is part of the API clean effort.

**Comment by luisramos0** [comment]
There's an initial version of this issue here:
https://github.com/openfoodfoundation/openfoodnetwork/wiki/API-documentation#how-to-build-a-new-api-endpoint-with-examples

**Comment by kristinalim** [comment]
I am happy with the documentation. Very good work, @luisramos0! :heavy_check_mark: 

@sauloperez @Matt-Yorkley Second approval? This is an issue, so tagging you in the comment.

**Comment by Matt-Yorkley** [comment]
Yes, I'm happy with the docs. :heavy_check_mark:
