### ISSUE TITLE
Do not load all pages in Bulk Edit Products

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4076]
### What we should change and why (this is tech debt)

Currently, the Bulk Edit Products page loads all pages regardless of how much you scroll. You might want to see only the first one. This adds a totally unnecessary load on the server.

[services/bulk_products.js.coffee](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/services/bulk_products.js.coffee) uses [PagedFetcher](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/index_utils/services/paged_fetcher.js.coffee) to load them async.

### Context

This stems from https://github.com/openfoodfoundation/ofn-install/issues/477#issuecomment-514677459

### Impact and timeline

This should cut the negative impact on performance this page has which seems to be causing serious downtime.

**Comment by sauloperez** [comment]
anyone familiar with this code and why it was designed that way? @mkllnk @luisramos0 @Matt-Yorkley @kristinalim ?

**Comment by Matt-Yorkley** [comment]
I'll take this one, if nobody minds. I'm thinking we just implement a simpler pagination, like in the new orders page.

**Comment by luisramos0** [comment]
I know pageFetcher, I think I made it use promises at some point, last time I looked at it I found this problem: https://github.com/openfoodfoundation/openfoodnetwork/pull/3911#issuecomment-501810292
Maybe #3911 can be part of this issue (it's just "sort entries alphabetically").

Anyway, this is for fetching all pages which is what we need to stop doing here :-)

**Comment by luisramos0** [comment]
I think we have discussed this somewhere else, but anyway: this is a brilliant opportunity to make this page use the API (api/products) and get some nice pagination in the API as an API exemplar :-) #4070
For example, move this in api/products from bulk_products to index (I dont think index is being used)

**Comment by luisramos0** [comment]
fyi spree/api/products_controller_decorator will be in spree/api/products_controller after [this](https://github.com/openfoodfoundation/openfoodnetwork/pull/4055/files#diff-98a94f4b19fb11b62cc959a2f9f50259).

**Comment by mkllnk** [comment]
I think the PageFetcher was written to get around timeouts, have a quicker response but still keep the full functionality. Moving the searching to the backend and using pagination is a better idea though. Happy for you to go ahead.
