### ISSUE TITLE
[Spike] Analyze impact of /api/products/bulk_products on DB

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4077]
### What we should change and why (this is tech debt)

We need to know what are the queries this request generates and see what impact they have on DB in terms of response time. Then, we can check how these can be optimized.

### Context

This stems from https://github.com/openfoodfoundation/ofn-install/issues/477.

### Impact and timeline

This should cut the negative impact on performance this page has which seems to be causing serious downtime.

**Comment by luisramos0** [comment]
I am not sure we need to do this work. When a super admin loads the products update page, there are dozens?hundreds? of requests to the server for each page... I think we just need to do #4076

**Comment by sauloperez** [comment]
Copying a relevant request log from https://github.com/openfoodfoundation/ofn-install/issues/477#issuecomment-514121571

```
Started GET "/api/products/bulk_products?page=29;per_page=20;" for 82.132.212.49 at 2019-07-22 15:56:04 +0000
(...)
Completed 200 OK in 64479.5ms (Views: 34634.5ms | ActiveRecord: 29843.7ms)
```
Notice the **ActiveRecord: 29843.7ms** we can hardly handle something like this unless we at least take a look. That is why I added spike to this issue.

**Comment by Matt-Yorkley** [comment]
I'm doing the pagination now (it's nearly ready for review). I think the queries are still pretty bad even when they're smaller, so I think it's worth seeing if there's any quick wins (like simple N+1s we can strip out) to improve it.

**Comment by luisramos0** [comment]
ok, agreed!

**Comment by Matt-Yorkley** [comment]
```ruby
def spike
   if quick_wins_available?
      fix_it_now!
   else
      redirect_to_dev_ready_column
   end
end
```
:smile:

**Comment by sauloperez** [comment]
I created https://github.com/openfoodfoundation/openfoodnetwork/pull/4092 while investigating this.

**Comment by sauloperez** [comment]
Here's the outcome of the investigation. Basically, wherever I look I see N+1 which makes it harder to prioritize... but these are what look to the relevant things:

### All Api::Admin::ProductSerializer's attributes trigger a query

None of the many attributes and associations of the `Api::Admin::ProductSerializer`, including variants and the atttributes and associations of their `Api::Admin::VariantSerializer`, are eager loaded. Nested N+1? M*(N+1) :boom:?

### Mem-expensive enterprises query in /admin/products

Copied straight from the log

```
Rendered spree/admin/products/index/_header.html.haml (63.5ms)
  Enterprise Load (2.0ms)  SELECT "enterprises".* FROM "enterprises" WHERE "enterprises"."is_primary_producer" = 't' ORDER BY name
```
Might it be triggered by index/_header.html.haml ?

What stands out from the query plan below is that sorting by name takes 1071Kb (UK server)

```
openfoodnetwork=> explain analyze SELECT "enterprises".* FROM "enterprises" WHERE "enterprises"."is_primary_producer" = 't' ORDER BY name;
                                                      QUERY PLAN
----------------------------------------------------------------------------------------------------------------------
 Sort  (cost=270.13..273.36 rows=1291 width=1639) (actual time=5.708..5.961 rows=1291 loops=1)
   Sort Key: name
   Sort Method: quicksort  Memory: 1071kB
   ->  Seq Scan on enterprises  (cost=0.00..203.42 rows=1291 width=1639) (actual time=0.023..1.945 rows=1291 loops=1)
         Filter: is_primary_producer
         Rows Removed by Filter: 151
 Planning time: 17.614 ms
 Execution time: 6.206 ms
```

In any case, this broad query could be even more dangerous as the number of enterprises grows. We better fix it soon.

**Comment by mkllnk** [comment]
Yes, individual issues for each of the things you found.

**Comment by sauloperez** [comment]
Issues created. Feel free to question their severity.
