### ISSUE TITLE
Stop referencing /admin/custom.css

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4080]
### What we should change and why (this is tech debt)

From different views of the app we refer to `/admin/custom.css` which does not exist anymore. This cause lots pointless requests which waste resources and add noise in the logs. If we are fine without that CSS file, we could just remove all references to it.

### Context

This came up while checking UK's nginx logs. All requests to this file end up with a 404 as Nginx can't file the file.

![Screenshot from 2019-07-25 15-14-19](https://user-images.githubusercontent.com/762088/61877468-5c45b600-aeef-11e9-83d0-15b75a6c1cdd.png)

### Impact and timeline

It'd be great to reduce this pointless noise in the logs as well not waste system resources

**Comment by Matt-Yorkley** [comment]
There's already an issue for this from a month ago :wink: #3759
