### ISSUE TITLE
Add grey line below nav bar on mobile as well

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4082]
## Description

In https://github.com/openfoodfoundation/openfoodnetwork/pull/4048 we added a grey line under the nav bar to respect the design Yuko has made.

While testing #3786 with @daniellemoorhead we saw that is was not applied to mobile.

So in this issue we are bringing this grey line to mobile AND we need to change the grey colour on both desktop and mobile to the same grey used in the rest of the navbar (which is lighter than the grey used currently for the bottom of the navbar on desltop). See comment here: https://github.com/openfoodfoundation/openfoodnetwork/pull/4048#issuecomment-512915564

## Acceptance Criteria
1. As a visitor I can see the grey line below the navbar on :
- Latest iOS device with both Chrome and Safari latest version
- At least on Android device with both Firefox and Chrome
2. Desktop version is working as well, especially on IE
3. The bottom grey line matches the vertical ones like here:

![image](https://user-images.githubusercontent.com/6525576/61948803-26650800-afa9-11e9-8b79-b33d7d4d6286.png)

**Comment by luisramos0** [comment]
did #4123 close this?

**Comment by Matt-Yorkley** [comment]
Closed by #4123
