### ISSUE TITLE
Missing translations / misleading automatic translations from Spree on orders pages

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4090]
## Description

With v2 new badly automatic translations from Spree have appeared on the orders section, and there are also missing translation that (re)appeared... I'm pretty sure some of those were translated before the upgrade. We need to enable translation of those strings through transifex to be able to translate them properly.

## Animated Gif/Screenshot

1.
![Untitled presentation](https://user-images.githubusercontent.com/8135376/62050414-7a722580-b211-11e9-89e0-67bc127226a7.jpg)
2. On the edit order page:
![Untitled presentation(1)](https://user-images.githubusercontent.com/8135376/62050424-7e9e4300-b211-11e9-9eaf-1daf41080f03.jpg)
3.
![Untitled presentation(2)](https://user-images.githubusercontent.com/8135376/62050437-8231ca00-b211-11e9-8f26-9924f4ec2ba7.jpg)
4.
![Untitled presentation(3)](https://user-images.githubusercontent.com/8135376/62050443-85c55100-b211-11e9-8021-6afcb648a7f4.jpg)
5.
![Untitled presentation(4)](https://user-images.githubusercontent.com/8135376/62050452-88c04180-b211-11e9-9f2a-e847bc239d61.jpg)
6.
![Untitled presentation(5)](https://user-images.githubusercontent.com/8135376/62050460-8cec5f00-b211-11e9-8804-5b8835a212be.jpg)

## Context

User reports on OFFrance for part of those missing translations. We added some we noticed ourselves.

## Severity
What is the severity for translations, S3 ? 

## Your Environment

* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu
* OFN Platform instance where you discovered the bug, and which version of the software they are using : France on v2.2.1

**Comment by luisramos0** [comment]
1. js.admin.orders.shipment_states.backorder = "réapprovisionnement"
2.
- backordered (same as on_hand in point 3 below) - missing translation in app/views/spree/admin/orders/_shipment_manifest.html.haml
- rupture de stock - missing translation in app/views/spree/admin/shared/_order_tabs.html.haml that gets the automatic spree translation
3. ship - missing translation in app/views/spree/admin/orders/_shipment.html.haml
4. missing translation in app/views/spree/admin/adjustments/index.html.haml
5. missing translations related to #4079, maybe @HugsDaniel can fix this one as part of 4079
6. missing translations in views that are still in spree
