### ISSUE TITLE
Mem-expensive and broad enterprises query in /admin/products

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4098]
### What we should change and why (this is tech debt)

Copied straight from the log

```sql
Rendered spree/admin/products/index/_header.html.haml (63.5ms)
  Enterprise Load (2.0ms)  SELECT "enterprises".* FROM "enterprises" WHERE "enterprises"."is_primary_producer" = 't' ORDER BY name
```
Might it be triggered by index/_header.html.haml ?

What stands out from the query plan below is that sorting by name takes 1071Kb (UK server). **Is the sorting really needed?**

```sql
openfoodnetwork=> explain analyze SELECT "enterprises".* FROM "enterprises" WHERE "enterprises"."is_primary_producer" = 't' ORDER BY name;
																		QUERY PLAN
----------------------------------------------------------------------------------------------------------------------
 Sort  (cost=270.13..273.36 rows=1291 width=1639) (actual time=5.708..5.961 rows=1291 loops=1)
	Sort Key: name
	Sort Method: quicksort  Memory: 1071kB
	->  Seq Scan on enterprises  (cost=0.00..203.42 rows=1291 width=1639) (actual time=0.023..1.945 rows=1291 loops=1)
			Filter: is_primary_producer
			Rows Removed by Filter: 151
 Planning time: 17.614 ms
 Execution time: 6.206 ms
```

It also quite slow because it has a very broad WHERE constraint. It's not as bad as https://github.com/openfoodfoundation/openfoodnetwork/issues/4095 but it's rather similar.

So, **can we get rid of that sorting?** and **can we reconsider this query given its bad performance**?

### Context

This comes from the investigations done in https://github.com/openfoodfoundation/openfoodnetwork/issues/4077

This query is generated by the `/api/products/bulk_products` endpoint.

### Impact and timeline

This query is quite mem-intensive but also 

It'd great to check whether it causes PostgreSQL to write to temporary files, which can be checked with Datadog's `temp_bytes` metric and its graph. Disk usage slows down the queries.

![Screenshot from 2019-07-30 16-10-44](https://user-images.githubusercontent.com/762088/62136543-9d213e80-b2e4-11e9-82b1-60692b3a34bf.png)

**Comment by lin-d-hop** [comment]
This page currently loads in a reasonable time even in super admin.
Closing.
