### ISSUE TITLE
Tag field oversized in Edge, Chrome and Chromium

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4099]
## Description
When adding or editing a new payment method or a new shipping method, the tag field is oversized when using browsers like Edge or Chrome. Firefox displays it in a smaller way that is enough for what the field is supposed to do.

## Steps to Reproduce
1. Got to `/admin/payment_methods/new`with browserstack and switch browsers
2. Observe the difference in the tag field

## Animated Gif/Screenshot
In Firefox:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/53b20967-d295-4bcb-b8ba-6ce802001e22)

In chrome/Edge:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/f457e3f3-ea78-4584-ab23-e7f55ff554e3)

## Severity
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it

I'm hesitating between both of these severity

## Your Environment

* Version used: v2.2.1
* Browser name and version: See issue
* Operating System and version (desktop or mobile): Desktop Windows and Ubuntu

## Possible Fix
Display Firefox's style

**Comment by RachL** [comment]
@luisramos0 @Matt-Yorkley is this something we can tag as a good first issue?

**Comment by luisramos0** [comment]
this is in master but it is not live. so, it's a bug in the coming v2.2.2.

**Comment by luisramos0** [comment]
I dont understand why this is happening but maybe a good first issue for a css hacker...

the fix may be to add a new css rule on top of the tags-input library custom css.
tags-input .host { height: 44px }

but I dont understand why this 100% height is taking 900pixels now...

**Comment by andresgutgon** [comment]
Not happening in an updated version of Chrome
![image](https://user-images.githubusercontent.com/49499/92325242-4f2f4c00-f049-11ea-86dc-6c85af2884a4.png)


![image](https://user-images.githubusercontent.com/49499/92325265-6d954780-f049-11ea-9786-c8c3e7716216.png)

**Comment by RachL** [comment]
aaah I love issues fixing themselves on their own :) thanks for the check @andresgutgon and good to have you here! 

I'm closing
