### ISSUE TITLE
Print SKU in order confirmation email

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4102]
## What is the problem we are solving 
For Hub owners that use the SKU for packing, and want to pack as orders arrive via email (i.e. when they see the email confirmations), they need to see the SKU

At the moment the order confirmation email doesn't show SKU
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/1a5d273b-d3f7-4bb3-b10f-ab2136195e15)

However the invoice printing from admin does. The proposal is to amend the order confirmation email to include the SKU in the same location as it displays on the invoice

## Success factors = expected outcome 
SKUs appear on the order confirmation email when they are included in the product. The order confirmation appears as now if the product/variant doesn't have SKU

**Comment by RachL** [comment]
@kirstenalarsen hello Kirsten, FYI you can also use the story template when creating an issue like this :) The story template as a important paragraph: the acceptance criteria. I like to write the tests directly here so testers no exactly what they have to look at. Am I right to believe that this test would answer the need:

_Scenario 1_: 
1. As a manager, add a product with an SKU to an open OC
2. As a buyer, checkout that product along with another one with no SKU
3. The order confirmation email the buyer receives is mentioning the SKU for the product with an SKU, for the second one, nothing is mentioned
4. The order confirmation received by the Hub is mentioning SKU as well, same format

_Scenario 2_:

Repeat all scenario 1 but with a subscription order, not a manual checkout.


Also @kirstenalarsen can you share a screenshot or mockups of where the SKU should be put? Also do we write something before like "SKU: XXXXX" or just the number?

**Comment by Matt-Yorkley** [comment]
There's already a table with columns so maybe just "SKU" at the top? For the "some with SKUs / some without SKUs" issue, maybe a placeholder like "-" would be good?

```
Item       SKU      Qty      Price
-------------------------------------
Chop       CHP1      2       $4.00
Cutlet      -        1       $1.00
```
