### ISSUE TITLE
Missing translations on new delivery method setup page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4109]
## Description

URL: `/admin/shipping_methods/new`

![Capture du 2019-07-31 22-15-16](https://user-images.githubusercontent.com/8135376/62244903-b14a6600-b3e0-11e9-964c-b83cc831379b.png)

Also, when I change the calculator type, a little sentence appear below, that is untranslated :
![Capture du 2019-07-31 22-39-23](https://user-images.githubusercontent.com/8135376/62246579-34b98680-b3e4-11e9-8d46-b4da7e3d8c55.png)

**Comment by myriamboure** [comment]
@RachL is it normal that the "hubs" list is now down the page and not on the right column of the page ? Just wondering... seems difficult when there is a long list of enterprises...

**Comment by myriamboure** [comment]
For information, before:
![Capture du 2019-07-31 22-17-13](https://user-images.githubusercontent.com/8135376/62245058-fbcbe280-b3e0-11e9-82ef-597a1d703327.png)

**Comment by RachL** [comment]
@myriamboure I know it sucks, but remember missing translations can be done by new developers. Can you stick to the template and add at least the URL and the user? Otherwise it might be difficult for them to take these issues.

**Comment by RachL** [comment]
For the list of hubs, yes it is like this with spree v2
