### ISSUE TITLE
Translation missing on paiement method menu page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4110]
## Description

URL: `/admin/enterprises/SHOPNAME/edit#/payment_methods`

![Capture du 2019-07-31 22-44-35](https://user-images.githubusercontent.com/8135376/62246873-db058c00-b3e4-11e9-8565-9912482e5b52.png)

**Comment by daningenthron** [comment]
Hello! This appears to be due to a typo causing a mismatch between the Transifex source file and the payment methods HAML:

`= t('.no_method_yet')` vs. `not_method_yet: You don't have any payment methods yet.`

I'd be happy to make the change to the English and translation yml files.

**Comment by RachL** [comment]
Hi @daningenthron and welcome to the community!

No one is working on this issue currently, feel free to do so! If you have any question don't hesitate to join us [on Slack](https://openfoodnetwork.org/slack-invite), and ask for help in the #dev channel

Also, if you haven't seen yet, here is the wiki page on how we are handling translations: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

**Comment by daningenthron** [comment]
Thanks! Just getting a 404 on the Slack invite - should I use a different link?

**Comment by sigmundpetersen** [comment]
Try this @daningenthron https://join.slack.com/t/openfoodnetwork/shared_invite/enQtMzU2Mjk5MDc2MjA5LTM4ZTAzZjIwNzIxMmU5ODFiNWY1MTU2ZWUyNzQwNjdjNTY0N2VhY2UwOGU4ZmVjNzYyZDU2NjY3NzZkZmQwYjk
