### ISSUE TITLE
Release v2.2.2 Pop

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4117]
Release draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-4b2f1aacd5863ddef665
Build: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/761

PRs: https://github.com/openfoodfoundation/openfoodnetwork/pulls?utf8=✓&q=is%3Apr+merged%3A>2019-07-19T20%3A26%3A00%2B02%3A00+sort%3Aupdated-desc+base%3Amaster

**Comment by RachL** [comment]
@sauloperez I've found two bugs while testing :

- https://github.com/openfoodfoundation/openfoodnetwork/issues/4122 but already in production
- https://github.com/openfoodfoundation/openfoodnetwork/issues/4121 I don't think it is a blocker.

Full release notes: https://docs.google.com/document/d/1xvcWzzngdkG-DiEGEOYVkldzMiG8ch70ql2vJU7D8TA/edit#

**Comment by sauloperez** [comment]
Ok, then I'll go on with the release :+1: Thanks @RachL !

**Comment by sauloperez** [comment]
Published: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v2.2.2

I'll deal with the deployment on Monday.

**Comment by sauloperez** [comment]
Deployed to all instances except AU as listed in https://github.com/openfoodfoundation/ofn-install/wiki/Current-deployment-status
