### ISSUE TITLE
Add tests for "Footer and External Links" dynamic content

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4118]
### What we should change and why (this is tech debt)

Automate the tests mentioned in https://github.com/openfoodfoundation/openfoodnetwork/pull/3389#issuecomment-457794935 as feature specs or view specs so that next time @RachL does waste precious time doing something that a computer would do faster and more reliably.  

### Context

This came up in https://github.com/openfoodfoundation/openfoodnetwork/pull/4093#issuecomment-516369849

### Impact and timeline

It should be pretty straightforward to add and it'd improve our confidence when updating Redcarpet.

**Comment by luisramos0** [comment]
as I mentioned on Filipe's PR, this is already being auto tested here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/25a8c44c2273d0704563ef35c7bf30f919e90365/spec/features/admin/content_spec.rb#L18

**Comment by luisramos0** [comment]
I missed the detail that the test should validate special characters which iss done in Filipe's PR.
I recomemded Filiep to just move content_spec to /configuration and add the special characters validation to that existing spec :+1:
