### ISSUE TITLE
When an inventory override stock level to ondemand, the producer stock on hand is reduced as well

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4122]
## Description

As part of the release testing I gave Marys'online shop the permissions to sell Pop release's products.

Pop release had choco pops on demand and Limonade on hand (0 left).

I left choco pops as "use producer settings" on Mary's inventory and I switch Limonade "on demand" in Mary's inventory. I noticed two things:

1. Mary does not see that Choco pops are "on demand", she only sees the stock level. Which is confusing.
2. If a shoper takes 34 limonade, the producer stock gets diminished, but it shouldn't

## Steps to Reproduce
1. As a producer, create a product with a on hand stock number
2. Give permission to a shop to add to inventory and to OC
3. As the shop; override the on hand product to "on demand"
4. As a buyer, checkout the product on the hub shop with a quantity higher than the on hand level you've set as a producer
5. Check the producer stock level: it now shows a negative quantity. 

## Animated Gif/Screenshot

Mary's inventory before checkout:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/7f17125e-0163-42be-bab3-75cab11d80a3)

Pop's release stock after checkout on Mary's shop not on Pop release's shop:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/16c6bf01-b182-47f8-b9b3-282c05a1eab0)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.2.2 (release testing)
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
I was tempted to say it's S2, but now I dont think it is. I think S3 is fine because the producer stock setting is on_demand so the stock level (that in v2 is now updated even if in on_demand) should not be seen...
I'd say that if producer setting enabled and producer has it as on_demand, we should hide the stock level in the inventory page.
And also we should stop updating the producer stock.

The S2 or S1 would be if the producer setting was on_hand and the stock was reduced. If that is not the case, this is an S3.

Makes sense?

**Comment by luisramos0** [comment]
can you clarify steps to reproduce please? point 4. what product is it? choco pops or lemonade?

**Comment by RachL** [comment]
@luisramos0 point 4 is lemonade. So yes your sentence is correct : the producer setting is on_hand and the producer stock is updated on a sale of the override

**Comment by RachL** [comment]
I've updated the issue.

**Comment by luisramos0** [comment]
ok, in that case this must be an S2 Rachel.

**Comment by luisramos0** [comment]
I dont understand how this is happening, I am sure we have an automated test covering this case... must be a bug in the code and the test...

**Comment by RachL** [comment]
In my routing I don't always check the producer stock level, only that the override is correct. This is how I've missed it it my last release testing I think... Lesson learned...

**Comment by luisramos0** [comment]
I am afraid I will not have time to fix this one before I go on holidays.

**Comment by Matt-Yorkley** [comment]
I've had a quick look at the specs, it looks like there's missing coverage. 

I added the following test, and it fails at line 156. The variant's stock is reduced.

https://github.com/openfoodfoundation/openfoodnetwork/blob/9ff26c170b14d19b362b081cf5c72b904d052fe4/spec/features/consumer/shopping/variant_overrides_spec.rb#L151-L158

**Comment by Matt-Yorkley** [comment]
So this is in production, has no workaround and affects a critical feature. I'd say S1 and immediate hotfix.

**Comment by Matt-Yorkley** [comment]
So at some point, variant stock is being decremented, and I think the variant.on_demand is being called when the variant is unscoped. So the override's value does not come into play.

**Comment by mkllnk** [comment]
Interesting bug. I actually think that we didn't specify this before. One of the v2 changes is that sock is now reduced for on-demand variants as well. If we made that number more visible, people could track how much stock they have to backorder.

If we take that as the desired behaviour then we need to track stock on the variant override even though it's on-demand. That would revert some of @kristinalim's work on enforcing our v1 rules on variant overrides.

I think we need to discuss what the "right" behaviour is and how we want to go forward. That's probably a first inception on The Network feature.
