### ISSUE TITLE
Admin can't create Stripe payments

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4134]
## Description

When an enterprise user tries to create a payment for an order and selects a Stripe payment method, the input fields for the credit card details don't appear.

## Expected Behavior

There can be several payment methods to choose from. Once a Stripe payment method is selected, a new input field should appear:
![Screenshot from 2019-08-07 15-29-35](https://user-images.githubusercontent.com/3524483/62597116-493bd880-b928-11e9-9836-8ce3d26ac85d.png)

## Actual Behaviour

You can select a Stripe payment method. The cardholder name input appears but not the credit card number input.
![Screenshot from 2019-08-07 14-14-12](https://user-images.githubusercontent.com/3524483/62597152-6a9cc480-b928-11e9-9e2c-ef4621bd5055.png)

## Steps to Reproduce

1. You need an enterprise connected to Stripe, a Stripe payment method and an unpaid order.
2. Edit the order.
3. Click on payments.
4. Click on the "+ NEW PAYMENT" button.
5. Select the Stripe payment method.

## Context

An Australian user reported this. It's slowing down their order processing a lot. The workaround is to open an order cycle and create the order as a guest.

## Severity

Rating as S2 because it's between S1 and S3. A critical feature is broken but there is a workaround. I'm not sure for how long the user accepts the workaround though and if this needs to be changed.

Reference:

- bug-s1: a critical feature is broken: checkout, payments, signup, login
- bug-s2: a non-critical feature is broken, no workaround
- bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v2.2.2
* Australian production. Also replicated on Australian staging and in dev mode.

## Possible Fix

I don't know. The Angular directive `stripe-elements` is there and the StripeJS code is loaded. But somehow it doesn't replace the directive.

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**StateMachine::InvalidTransition** in **spree/admin/payments#create**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d4a4224cbece7001943b173?event_id=5d4a4224004ca20acfb70000&i=gh&m=li)

**Comment by mkllnk** [comment]
I found the issue. There are deface files to make Stripe working but they are not working since the upgrade. De-defacing solves this issue.

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**ActionView::Template::Error** in **spree/admin/payments#show**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d4a4ce887be02001e977b79?event_id=5d4a4ce8004caa93852a0000&i=gh&m=li)

**Comment by lin-d-hop** [comment]
@HugsDaniel @mkllnk Is this therefore ready for testing with the above PR? :point_up:

**Comment by sigmundpetersen** [comment]
yeah just some missing translations then it's good
