### ISSUE TITLE
Product Stock levels not updating for Producer Shop

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#4143]
## Description

This bug was reported for v1 #3961 but closed until we had evidence that it would also occur in v2.
Producer Sole of Discretion has found numerous errors in either the price or stock level of their products (or one variant of a product) over the last few months.
Errors encountered since switch to v2 are with the 600g whole mackerel variant. Stock level is set to zero but product remains in producer shop for customer to purchase.
Past errors included variant prices not displaying correctly in the producer shop front and variants being missing from shop front even though they were in stock (indicating that stock level not being updated from zero).

## Expected Behavior

Stock level and prices for variants set by producer should be reflected in shop front. Stock level of frozen whole mackerel set to zero and so this variant should not appear to the customer.

## Actual Behaviour

Stock level of frozen whole mackerel set to zero but variant appears still on producer shop front.

## Steps to Reproduce

1. increase stock level from 0 to 2, save changes: frozen whole mackerel appears on shop front
2. decrease stock level from 2 to 0, save changes, refresh page: frozen whole mackerel appears on shop front
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/45104035/62791817-d9635480-bac5-11e9-8e7d-b5e798c9aeb7.png)
![image](https://user-images.githubusercontent.com/45104035/62791822-df593580-bac5-11e9-8ea0-7ae5155b1526.png)

## Context

Producer unable to remove seasonal items from stock.

## Severity

bug-s2

Strictly a bug-s1 as it is a critical feature (item in stock which can not be removed) but there is a manual fix in that if the item is removed from the order cycle it disappears from the shop front.

Could crop up in other shop fronts.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using. 

Chrome
Windows 10

## Possible Fix

Suggestion from previous bug that it was related to Cache.

**Comment by sigmundpetersen** [comment]
Could this be the same as #4020 ?

**Comment by lbwright22** [comment]
hi @sigmundpetersen not sure. Looks very closely related to issue #4020 but changing stock level as admin manually doesn't work in this case. You have to remove the item from the order cycle totally.
Error occurs in producer's shop front (producer shop not hub) but does not occur to the same product when listed on the hub shop front of another enterprise (Mercia)

**Comment by luisramos0** [comment]
I think this is the same as #4020, our cache system is broken for some cases and we need to review it. I agree this is an S2 or even S1. I think this will be experienced by more users as we go...

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sole of Discretion: products not updating](https://trello.com/c/Ik1vr0UG/510-sole-of-discretion-products-not-updating)

**Comment by luisramos0** [comment]
ok, I can replicate the problem in #4020 and believe it's the same as this issue.
Let's track the fix in #4020 and keep this one open until the fix is in uk live. We can close this one when we know the problem is fixed in uk live, ok?

**Comment by luisramos0** [comment]
ok, now that #4020 is closed, we need to release a version with the fix (next release), deploy it to UK and then verify if this problem here is also solved. I am not sure what's the right pipe state for it until it can be tested...

**Comment by sigmundpetersen** [comment]
Blocked (by next release) in Test Ready?

**Comment by RachL** [comment]
@lin-d-hop @lbwright22 now that the new release has been deployed, can you check if this bug is still occurring?

**Comment by lbwright22** [comment]
@RachL I have got about half way through testing all of Sole of Discretion products and there are at least 3 variants for which the stock levels are not updating still:
Dressed Crab when stock level is zero it still appears in shop front
same for Herring fillets and Gurnard fillet. There may be more products for which this is happening too but since i have found three errors so far I won't go through all the rest of the products one by one as they have lots! 
@lin-d-hop

**Comment by RachL** [comment]
Thanks a lot @lbwright22 ! I'm putting this back to dev ready then

**Comment by Matt-Yorkley** [comment]
I think this is probably closed by #4162, which was deployed two days ago. It should stop the issue recurring in the future, but might not fix the current cases. I'll do some more investigating...

**Comment by Matt-Yorkley** [comment]
It looks like all the products in the shopfront all have at least 1 stock...

**Comment by Matt-Yorkley** [comment]
Closing for now, feel free to reopen.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley 
@lbwright22 tested this after the deployment. That's why @RachL moved it back to dev ready.

**Comment by lin-d-hop** [comment]
@lbwright22 Do you think there is a chance that the product cache just hadn't updated? Changing the stock level to 0 should trigger a cache update meaning that it should display quickly, let's say within a couple of minutes. 

@Matt-Yorkley's comment about the "Products all having at least 1 stock"..... does that suggest a fix to you @lbwright22 ? 

Perhaps you could add some more detail based on testing again....?

**Comment by lbwright22** [comment]
Sole of Discretion:
1) open order cycle named 'testing' . Add all products to this.
2) Herring fillet stock level = 0 therefore should NOT appear in shop front. 
BUT *****Herring fillet appears in shop front under order cycle 'testing'****
3) increase stock level of herring fillet to = 1; save and refresh.
-> Herring fillet appears in shop front (it should do)
4) decrease stock level of herring fillet to = 0, save and refresh shop front.
BUT *****Herring fillet appears in shop front under order cycle 'testing'****
I can also add these products to my basket with no problem

Hence the error is still there.  User wants it such that if stock level= 0 the item doesn't appear in the shop front (as is the case with most items).
The other day I found there to be errors with at least 3 products (herring fillet, gurnard fillet and dressed crab) but I didn't test them all and so likely to be more.

Ping @Matt-Yorkley @lin-d-hop @RachL

**Comment by RachL** [comment]
Back to dev ready then...

**Comment by sauloperez** [comment]
Any more insights on this @Matt-Yorkley ? Should I resume it?

**Comment by luisramos0** [comment]
hello @lbwright22 
I had a look at this one again in uk live and I think I see what's the problem.

These products are overrided in the inventory: the user has added their own products to their inventory page and has overridden the stock levels.
![Screenshot 2019-09-16 at 13 03 27](https://user-images.githubusercontent.com/1640378/64956791-54691900-d883-11e9-97dd-03141e456c9b.png)

The stock config in the inventory for unlimited? is NO and therefore in this case, the stock levels in the bulk product edit page are ignored and the inventory stock levels are used instead. I changed the stock in the inventory page of herring fillet to 0 and the product disappears from the shopfront.

I know there were cache problems before in this shop and I think #4240 will improve the situation for cache problems but would my explanation above clear all "problematic" cases for this shop now? can you check? if so maybe we should close this issue.

**Comment by luisramos0** [comment]
Moving to test ready until confirmation. Please feel free to move back to dev ready if problem is not solved/clarified.

**Comment by lbwright22** [comment]
Yes, this issue seems to be fixed. The products which did not update their stock level were all those found to be over-ridden in the producer inventory.

Testing a random selection of products shows they update correctly.
Thank you for sorting this @luisramos0 @RachL and all

**Comment by luisramos0** [comment]
ah, great stuff! thanks for confirming Louise
