### ISSUE TITLE
Contaminated login?  Particular user can not save to inventory.

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4145]
## Description

I wonder if this relates to the 'flower mobius loop bug' - 4138,   and/or the bug related to inability to manage permissions - 4139.     My login -  tchumilas at rogers.com -  is owner and manager for multiple enterprises.  These enterprises are the ones involved in issue 4138.   That issue appears to be fixed -  I can now save changes in my product lists.  BUT -  I can still not save changes (overrides) to inventories for ANY enterprises with that login.  Contaminated login?

## Expected Behavior

Any user,  with a farm shop,  or hub enterprise should be able to set up an inventory and save overrides to their own products.  (They should be able to save to inventory other's products for which they have permission also -  but here,  I'm ONLY referring to an enterprise putting their own products into inventory)

## Actual Behaviour

One particular user -  and only that user it seems -  cannot save overrides of the OWN products to inventory.  Error is: I couldn't get authorisation to save those changes, so they remain unsaved.   At first I thought it was just related to the enterprises involved in the loop issue - 4138,  but I created a new enterprise  -  no permissions,  no products in any OC,  and still can't save to inventory.   BUT,  if I add a different login as a manager to this new enterprise (or to any of the enterprises involved in 4138,   I am able to save overrides in inventory.  So the problem is only with enterprises where tschumilas at rogers.com is the manager -  both existing and bran new enterprises.    . I can't reproduce it with any other login -  so I don't think anyone will be able to reproduce.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by luisramos0** [comment]
the inventory page breaks if there is a single broken override, I'd say it's related to one specific override that the enterprise can see in the inventory page.

**Comment by tschumilas** [comment]
So -  I should be able to see something that tells me there is a broken override?    And a broken override for one enterprise,  will mean that user is unable to manage inventories for other enterprises they manage -  even if those other enterprises are not selling to/from the affected inventory?   So - just trying to understand this -  it means a user's different enterprises are not really autonomous. ??

**Comment by luisramos0** [comment]
--- I should be able to see something that tells me there is a broken override?
no, a dev needs to investigate the code, there is some issue with permissions.
for devs: the way we fetch VOs and validate their permissions [on READ](https://github.com/openfoodfoundation/openfoodnetwork/blob/b4ffd4dcc2916573fd43e3bfabad85131a110dc7/app/controllers/spree/api/products_controller_decorator.rb#L23) is very separated from the way we validate VOs and their permissions [on WRITE](https://github.com/openfoodfoundation/openfoodnetwork/blob/b4ffd4dcc2916573fd43e3bfabad85131a110dc7/app/controllers/admin/variant_overrides_controller.rb#L76).

--- it means a user's different enterprises are not really autonomous. ??
not in this page, all variants of all enterprises the user can override will be fetched and updated at the same time in this page.

**Comment by luisramos0** [comment]
only one user affected so I am guessing severity S3 , feel free to change!

**Comment by tschumilas** [comment]
Its fine to make this s3 -   I have a workaround now -  added another login/user as manager and that manager login can save to inventory.   (I have no idea why that works - but it works.)

**Comment by luisramos0** [comment]
ok, moved to the bug backlog, only s1 and s2s get direct access to dev ready

**Comment by tschumilas** [comment]
I have abandoned this problem login,  so this is no longer an active bug as far as I know.
