### ISSUE TITLE
Release v2.2.3 Sea lettuce

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4150]
Release Draft:
https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-40d6b4cdbbaa2b78d759

Build:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/791

List of PRs:
https://github.com/openfoodfoundation/openfoodnetwork/pulls?utf8=%E2%9C%93&q=is%3Apr+merged%3A%3E2019-08-02T00%3A00%3A00%2B02%3A00+sort%3Aupdated-desc+base%3Amaster+

**Comment by lin-d-hop** [comment]
Alright - here are my testing notes:

https://docs.google.com/document/d/1hSx9JrvpIUME0-VkfSMyo4TINkvIu5kRQYBp0Nbe74g/edit#

All looks good. A couple of known issues relating to order flow, enterprises appearing on the map in FR staging and images on FR staging. Other than that everything seems to be working as we'd expect.

Big up respect to @RachL .... release testing is a big job!

**Comment by luisramos0** [comment]
released :+1:
thanks Lynne!
