### ISSUE TITLE
Cannot ship orders with variants on_demand

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4158]
## Description
Manager cannot ship an order if the order contains variants that are on_demand. Variants on_demand will appear in the order as "quantity x backordered" (instead of "quantity x on_hand"), the shipment state will show pending instead of ready and the ship button (both in the order list and in the order page) will not appear. See images [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/4112#issuecomment-521584878).

## Expected Behavior
You can ship an order with on_demand variants.

## Actual Behaviour
You cannot ship orders with on_demand variants.

## Steps to Reproduce
1. place an order with a variant that is on_demand
2. try to ship the order

## Context
Detected in #4112 

## Severity
bug-s3
I dont think this is a critical feature.
The (not so good) workaround is to temporarily change the variant in the order to on_hand, ship the order and then move the variant back to on_demand.

## Your Environment
* Version used: staging katuma 2.2.2
* Browser name and version: chrome latest
* Operating System and version (desktop or mobile): mac desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using. 2.2.2

## Possible Fixes

- Remove backordered logic from the shipment state method [here](https://github.com/openfoodfoundation/spree/blob/8a8585a43cd04d1a50dc65227f337a91b18d66d5/core/app/models/spree/shipment.rb#L207).

- The items are marked as "backordered" when their stock is negative, and that sets the order to "backordered" state, which blocks is from being shipped. If we don't reduce stock of on_demand items below zero, it should be fixed.

**Comment by Matt-Yorkley** [comment]
Orders with on_demand items can't be shipped, and the workaround is not at all obvious... I think this should be an S2.

**Comment by Matt-Yorkley** [comment]
Closing this bug report in favour of issue #4217
