### ISSUE TITLE
Enterprise fee tax selection needs option for 'none'

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#416]
Enterprise fee enables setting tax (correct), but doesn't give an option for not attaching the tax to the fee

![image](https://cloud.githubusercontent.com/assets/2911176/6633059/3710dbf0-c996-11e4-83de-83351169fd77.png)

should be like the product tax dropdown . . 
![image](https://cloud.githubusercontent.com/assets/2911176/6633065/4e2322a8-c996-11e4-9653-cb0b4e1c1cce.png)

**Comment by kirstenalarsen** [comment]
similar issue to https://github.com/openfoodfoundation/openfoodnetwork/issues/426

**Comment by kirstenalarsen** [comment]
I'm not entirely clear whether it is now calculating tax on all the fees or not, but as it's defaulting them all to gst it probably is, so can't deploy like this

**Comment by RohanM** [comment]
Fixed, will come with next push.
