### ISSUE TITLE
Lettuceshare report no longer selecting by order cycle

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4160]
## Description

Our biggest user in Aus has a specific report the 'Lettuceshare Report' that they use for providing info in a form to their network of buyers groups. It has stopped working with V2 . . 

"we create the Order Cycles for the next week and then use Lettuce Share to create a Wholesale Availability File for Customers to see the wholesale availability for the week ahead. Our co-op bulk buyers groups upload the csv file that is created to upload into their Lettuce share ordering systems for members.  This File that we create each week is essentially our price list and availability list for the Week so its really important that it is accurate and up to date. 
**This week the report is not reflecting the the current order cycle at all. It appears to have listed all the products and variants in the  Food Connect OFN system.**

I've attached the file created on Tuesday night this week after following this process: products_and_inventory_20190815 . An example that you will see is Kiwifruit is listed - it is not available and it is not showing as available in our order cycle when you search for Kiwi fruit. So the order cycles are correct but the file created through the lettuce share report completely is wrong.  It appears something has changed since the update that is affecting this report.

## Expected Behavior
The report should only include products / variants in the selected order cycle

## Actual Behavior
It is including all products / variants of the Distributor

## Steps to Reproduce

1. In OFN, select “Reports” from the top menu bar
2. Select “lettuceshare” - this will take about 30 seconds to load up
3. In order to ensure you are getting the correct information, the following filters must be set before downloading the report: [NB. Happy to give access to aus prod server if needed]
    * Distributor: Food Connect Wholesale 
    * Order Cycle: Master relevant to the week (eg. 3419 Master)
4. Check the box “DOWNLOAD AS CSV”, and click ‘Search’ which will start downloading the file to your computer.

## Context
Key user in Aus - this is extremely important to them as this report was built specifically to meet a critical need for them. But I understand that it likely matters to no one else :(

## Severity
s2 - non-critical, no workaround
OR
s3 - because of small number of users impacted (1)

## Possible Fix
Introduced with V2

**Comment by kirstenalarsen** [comment]
NB. Pending dev insights on whether this is a quick fix or not - I am going to have a look at whether there is a zapier way to meet the need that this report was built for. This is a v2 regression, but given very tight resources at the moment it might be better to move away from maintaining a report that is only used by one user. @mkllnk welcome any thoughts

**Comment by luisramos0** [comment]
This report is quite a simple one, this bug should be easy to fix.

**Comment by kirstenalarsen** [comment]
ok, given that the required endpoint is not yet in the API (thanks @luisramos0 ) AND that this looks quite easy to fix, I will leave this as s2 and really appreciate quick fix! Thanks

**Comment by mkllnk** [comment]
I found the cause. The distributor filter is overriding the order cycle filter. In more detail:

The LettuceShareReport is calling `variants` on ProductsAndInventoryReportBase. That one is taking all variants visible to the user and then filters it by supplier, order cycle, distributor and stock:
```rb
    def filter(variants)
      filter_on_hand filter_to_distributor filter_to_order_cycle filter_to_supplier variants
    end
```

Unfortunately the order cycle filter and the distributor filter both filter by `variant.id` and the latter is overriding the former. The resulting code is pretty much this:

```rb
        order_cycle = OrderCycle.find params[:order_cycle_id]
        distributor = Enterprise.find params[:distributor_id]

        variants.
          where(id: order_cycle.variants).
          where(id: ExchangeVariant.select(:variant_id).
                          joins(:exchange).
                         where('exchanges.incoming = ? AND exchanges.receiver_id = ?', false, distributor))
```

In some cases it can be a workaround to not filter by distributor.

**Comment by mkllnk** [comment]
This bug got introduced by v2.
