### ISSUE TITLE
Selection of Shipping Category should be identified as required with a red asterisk in product creation

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4165]
## Description

With V2 the User is now required to select a Shipping Category when creating a product. However the field is not highlighted with a red asterisk so there is no way for them to know that. This is a meaningless field to them so they are unlikely to do it without being told

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/5c8cb4bb-3f2e-4db2-a715-e5ab42b01e56)

If they have not selected a Shipping Category, then they see this message below and the Unit Size and Value fields are cleared. So they then select a meaningless Shipping Category field (say Default) and get error message that they don't have units

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/b4bcd6c4-753f-4da4-9205-8fb6cfaf3c76) 

ARGHGGHG - could we make life more painful for a new user if we tried ;) ?

## Expected Behavior

The Shipping Category field should EITHER
- have a red asterisk to denote the need to select a value OR
- just default to Default so they don't have to think about it

## Actual Behavior
as above

## Steps to Reproduce

1. Create new product
2. Fill out all required fields but DON'T select a Shipping Category
3. Voila

## Animated Gif/Screenshot
http://recordit.co/z4DUokFeGH

## Severity

bug-s4: it's annoying, but you can use it

**Comment by RachL** [comment]
Hi @daningenthron yes, you can go with switching the default to default! Thank you so much!
