### ISSUE TITLE
Create Shipping Method should auto-select Default Shipping Category

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4166]
## Description
Similar to #4165, V2 has introduced requirement of Shipping Category in creation of a Shipping Method. 

This is meaningless to users, as are the Shipping Categories, so could we please just select Default by default so they don't have to think about it?

## Expected Behavior
Shipping Category automatically set to Default

## Actual Behaviour
Shipping method fails to save because Customer hasn't selected Shipping Method. There is an error message

## Steps to Reproduce

1. Create Shipping Method
2. Don't select Shipping Category
3. Try to Save
4.

![image](https://user-images.githubusercontent.com/2911176/63240897-0b7a7080-c295-11e9-86b5-d6c8915431d6.png)

## Context
Just annoying

## Severity

bug-s4: it's annoying, but you can use it

**Comment by luisramos0** [comment]
this has been discussed somewhere else, I cant remember where. @RachL and @lin-d-hop were both involved, I cant remember the decision of that discussion.

**Comment by RachL** [comment]
I don't think this is a bug, more a UX discussion. If indeed none of our users care about this we should have a selection by default. I'm labeling it "improvement".

So far, no users have send feedback in France on this. Let's use this issue to track feedback we might receive and make a decision later on. I'm not sure we have enough info to do it currently.

**Comment by lin-d-hop** [comment]
I think simply having the compulsory field - red star will be enough. I think it would be good to begin to encourage users to really use the shipping category.

**Comment by luisramos0** [comment]
what do you guys think about making both ship method creation and product creation pages look up the "Default" shipping category and select it by default?
From my code review here: https://github.com/openfoodfoundation/openfoodnetwork/pull/4262#pullrequestreview-288542802

**Comment by RachL** [comment]
@luisramos0 yes I'm ok with that.

I'm sorry @lin-d-hop but when dan asked about it I've only read the issue description and not the comments below, so I've told him that he could go with having "default" selected by default.
And I agree with you Luis, the idea is to select "default" not the first shipping category which is available.

**Comment by kirstenalarsen** [comment]
This seems to be done! yippee, closing :)
