### ISSUE TITLE
Upgrade stripe gem to latest compatible version that supports the Payment Intents and Setup Intents API

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4169]
### What we should change and why (this is tech debt)

- Required for #4170 

Upgrade stripe gem to latest compatible version that supports the Payment Intents and Setup Intents APIs.

Support for `SetupIntents` was [added in `stripe` 4.21.0](https://github.com/stripe/stripe-ruby/blob/master/CHANGELOG.md#4210---2019-06-28).

### Context

We need to upgrade to a version of the `stripe` gem that supports Stripe's Payment Intents and Setup Intents API. This is in preparation for updating our integration for SCA compliance, especially for off-session payments that happen for subscriptions.

Read more:

* [Planning your SCA Migration](https://stripe.com/docs/strong-customer-authentication/migration)
* [Saving card details without a payment](https://stripe.com/docs/payments/cards/saving-cards#saving-card-without-payment)

### Impact and timeline

This should be done ASAP as prerequisite for sub-issues in the epic for SCA compliance, which is currently tagged S1.

**Comment by sigmundpetersen** [comment]
I think this is already in Test Ready with #4152 ?

**Comment by kristinalim** [comment]
Thank you, @sigmundpetersen! :slightly_smiling_face: You are right. I updated the PR description to close this one once merged.
