### ISSUE TITLE
Strange bug on , and . on product quantity setup

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4171]
## Description

For some producers (strangely), when setting up the quantity of a variant, if I use , instead of . the platform says it is saved but it is not (on chrome and firefox). This has been reproduced with the producer "Le moulin des copains" on French production (see Loom video below).

With another producer (Terravie on French production) I tried to reproduce but I couldn't, I types 0,5 and it properly saved... but I saw another issue when the Terravie user was sharing his screen: when he filled in "0,5" when saving it changed to 0 ,5 (added a space) which disturbed the display of the product. He was on internet explorer... (I tested with the same product as he did... so on his computer it was adding a space, on mine nothing, was working.)

## Expected Behavior

In countries where we use , as separator for decimal, users should be able to setup quantities with ,

## Actual Behaviour

They can't

## Steps to Reproduce

1. Go to product page, click on "expand all" and on any variant, modify the quantity for "0,5"
2. Save... a cross finger that you are on a producer case that enable you to reproduce the bug !

## Animated Gif/Screenshot

https://www.loom.com/share/a9e03e5b1d4849e6814fefb6fa3817a7

## Context

I saw that when doing live support on skype screen sharing with a user.

## Severity
bug-s3: a feature is broken but there is a workaround which is to put a . it is not intuitive for French or Belgium or Catalan users but it works

## Your Environment

* Version used: v2.2.3 I think (not 100% sure, could be 2.2.2)
* Browser name and version: tested on Firefox and Chrome
* Operating System and version (desktop or mobile): Ubuntu
* OFN Platform instance where you discovered the bug: French production

**Comment by RachL** [comment]
I could never reproduce this one. Closing.
