### ISSUE TITLE
Customer should see updated terms of off-session charging through Stripe

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4175]
## Description

Part of #4170

This issue is for reviewing how we present the terms of Stripe off-screen charging to customers.

**- As a:** customer
**- On page:** `/checkout`, `/account#/cards`
**- I want to be able to do:** See terms of Stripe off-screen charging

## Acceptance Criteria

The customer should see sufficient information about the terms of off-session charging. See [here](https://stripe.com/docs/payments/cards/reusing-cards#mandates) for more information.

**Comment by andrewpbrett** [comment]
Update link on mandates: https://stripe.com/docs/strong-customer-authentication/faqs#mandates

**Comment by andrewpbrett** [comment]
This is what that above commit looks like:
<img width="587" alt="Screen Shot 2020-12-03 at 6 40 16 AM" src="https://user-images.githubusercontent.com/35588/101042887-815e2600-3532-11eb-8a96-6b3e63b82cd5.png">

Based on the advice from Stripe around mandates, I pulled the text out of the infobox (that the customer would have to click on to read) and added some language that Stripe suggests. It's kind of wall-of-text-y now though. Not sure if we want to pause to get design feedback or wait on that until later given that we need to get this rolled out.
