### ISSUE TITLE
Order cycles date / time widget - the time control is confusing, broken or just badly designed?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#418]
Fix (or explain) time widget in OC setup
![image](https://cloud.githubusercontent.com/assets/2911176/6634362/5bd2ef7c-c9ab-11e4-8b75-0fa76c5c3488.png)

**Comment by sstead** [comment]
A user could not be confident that their desired closing time/date had been saved... suggested improvements....
1) restore image
2) save the time in the widget and the text field
3) change the +1100 to AEST
4) put a progress bar for the time (hours/mins)

![image](https://cloud.githubusercontent.com/assets/10843056/20732431/cad9c69a-b6e2-11e6-9118-f8686eedefd2.png)

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley do you think this would make a good first issue for newbies?

**Comment by Matt-Yorkley** [comment]
Sure, looks simple enough.

**Comment by sauloperez** [comment]
Just to clarify and expand the acceptance criteria for this issue:

- [ ] Restore the datepicker button in both open an close input fields
- [ ] Display the stored time when reopening the datepicker
- [ ] Show the local time according to the user locale without showing any time offset
- [ ] Show slider to select time in the datepicker

This sticks to items listed above and makes them work for other instances Agree @sstead, @daniellemoorhead?

**Comment by myriamboure** [comment]
Yeahhhh ! Thanks @sauloperez  I had also some comments from users who didn't understand the "+2:00" that was confusing... i'm not sure peoplel would understand the "ECT" or "AEST" time zone mention so I would just suggest "use the locale" but don't mention any international time stuff.

**Comment by sstead** [comment]
I'm not sure how the 'locale' time works. In Australia there are a few time zones, so unless the system knows which time zone the users is in, it would be good to say AEST as the reference point (this zone covers most of Australia, then people in other zones can calculate the difference). I suspect Canada, USA etc would be similar.

**Comment by daniellemoorhead** [comment]
![image](https://user-images.githubusercontent.com/10949052/31976163-85c72988-b981-11e7-8449-7fa31f4ebf17.png)

We have the joy of many timezones on our very big island @sauloperez.

So when you say show the user time according to user locale does that mean you would be using the user's computer/phone time setting?

**Comment by sauloperez** [comment]
> So when you say show the user time according to user locale does that mean you would be using the user's computer/phone time setting?

That's the idea. Although I'm pretty sure many devs hate AUS time zones mess :trollface:, that would still work. Everyone would see the time according to his timezone.

**Comment by daniellemoorhead** [comment]
>Although I'm pretty sure many devs hate AUS time zones mess

It's painful for non-devs too, just in terms of remembering when you speak to people in different timezones in the same country!! But I rather this than the Chinese model where they have a single timezone and it can be pitch black but is supposedly 9am!!

>Everyone would see the time according to his timezone.

So @sstead rather than needing to do the calculation our users would see the date/time based on where they are. Will this work ok? Any scenarios where it won't work?

**Comment by kirstenalarsen** [comment]
could they just pick a timezone in their setup? apologies if this has already been discussed, i’m just scanning and read last message

**Comment by sauloperez** [comment]
Well, we should offer the possibility (perhaps as a later iteration to keep things fast) but I'd pick the timezone offset from the browser.

> Any scenarios where it won't work?

I can't think of any :thinking:

**Comment by sstead** [comment]
"So rather than needing to do the calculation our users would see the date/time based on where they are. Will this work ok? Any scenarios where it won't work?" - Yes this seems good to me, but can we also show what time zone they have? The only possible point of confusion is that if the time zone isn't specified anywhere, the user will not be certain whether the timezone is set to their browser, or if it's set to eastern time by default. Some users may need to test this to confirm. Whereas if we could indicate the time zone there'd be no ambiguity.

**Comment by sauloperez** [comment]
Well, I'm not sure there's any value on showing that if it's not editable (I don't know whether spree allows it). Users assume datetimes are in local time. Just think about all the services you use, google's for instance.

**Comment by myriamboure** [comment]
Removing goodfirstissue label as it seems we need a clear inception process to decide what we do. So closing this issue for now, iceboxed it in: https://community.openfoodnetwork.org/t/hubs-can-easily-navigate-back-office-and-manage-their-shopfront/1246 and we will reopen when we decide to prioritize the hub manager UX and this will probably be one of the stories we will then put in it.
#gitcull2018
