### ISSUE TITLE
Add a default date range for Delivery Report

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#4184]
## Description

Since many shops and hubs have been trading for a significant time frame now the delivery report is large and is not downloading- the web page is timing out.  Unlike some of the other reports there is no default date range (say of a week or month) set for this report. This would prevent the need to download all the data for a hub.

## Expected Behavior

Delivery Report should download data for the last month or week only.

## Actual Behaviour

The default setting for downloading a delivery report is to access all the data generated by hub sales since it set up on OFN.

## Steps to Reproduce

1. Reports -> order cycle management -> delivery report
2. No default date range selected.
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/45104035/63505586-b1afbb80-c4cb-11e9-9ce2-14a7b47d25b3.png)

## Context

The delivery report is utilized weekly by many hubs to get orders packed and shipped to customers who purchased items.  Often it fails to download due to the excessive amount of data it is attempting to download at once.

## Severity

s-3 there is a workaround (payment methods report and then change to download delivery report) but it is annoying and large hubs are finding it difficult to operate without this function working as it should do.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by lin-d-hop** [comment]
Hi @jasonk357,
Thanks for this fix.
I wonder if we can make a small improvement to it.
As the date range sets to 'End Date' as Today at 1am this creates issues for users.
When they run the report all orders that were placed today are missed from the report.
Could we update to set the date range to Tomorrow at 1am?

I understand that this could also be a new issue. If Devs require it then fine. However since it is a small fix as part of the Good First Issue I'm hoping that I can just reopen.....

**Comment by luisramos0** [comment]
wherever you are, at 1am you should be sleeping not running OFN reports! serious risk of falling a sleep 😆

**Comment by luisramos0** [comment]
lol, I think I didnt understand the problem, anyway, it was a good joke :-)

**Comment by lin-d-hop** [comment]
@jasonk357 Will you have the chance to look at this?
If not I think we need to prioritise another way. 
Probably it is simple enough that I can do it....

**Comment by kirstenalarsen** [comment]
Hi, just dealing with a customer confused about missing customers this morning, and when I remove the dates completely all is fine. Just wondering why we didn't go with the 'just load nothing until they set filters' approach on this report? It seems the inconsistency is confusing? any thoughts

**Comment by kirstenalarsen** [comment]
but whichever way, I heartily agree that defaults need to include all of current day. This is 2nd confused user wondering why some customers are missing

**Comment by lin-d-hop** [comment]
Because this report is slow and was timing out. The fix to limit data loaded is useful, but there was an error in implementation that wasn't picked up in testing.

**Comment by kirstenalarsen** [comment]
yep cool. just noting that the way we fixed this in say Order Cycle - Customer Totals was to load NOTHING until filters were set, so is really clear to user that they need to set the filters as they want them. So is just a bit potentially confusing for users that some reports require all desired filters to be set, and some require some to be cleared / checked. Not a biggie, just noting inconsistency

![image](https://user-images.githubusercontent.com/2911176/66872604-141bc880-eff2-11e9-85d2-82e24c9e01e4.png)

**Comment by lin-d-hop** [comment]
Yes. Agreed. Another case of fixing something that's broken rather than refactoring the whole report or reports section. 'Cos agile is how we roll.

Perhaps a wishlist item about unifying reports UX would be a better place to have this discussion?

**Comment by RachL** [comment]
@lin-d-hop @kirstenalarsen I have one of our early user commenting on this addition of a default date range: basically they are telling me that this _was_ a feature on the order and fulfillment report at the beginning and that it was removed because too many users were making mistakes. They are now confused to see it back. Do you remember something like this? 😩
