### ISSUE TITLE
Add 'Customer Notes' field to Orders Index page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#419]
Where a Customer has written a note during Checkout, the Shop / Hub can only see this in the report or emails. Would be very useful to have it appear in order index page BUT it is sometimes quite long

Add a field called 'Notes' before the total, that just has 'view' or a pop-up icon of some sort . . and then works like the "What's This?" fields elsewhere in the site e.g. pops up a little message box, containing the Customer's notes

![image](https://cloud.githubusercontent.com/assets/2911176/6634377/ad4fec92-c9ab-11e4-8dbe-ca68c22ca661.png)

![image](https://cloud.githubusercontent.com/assets/2911176/6634405/1b4508cc-c9ac-11e4-9c0a-ee172e6aae74.png)

**Comment by kirstenalarsen** [comment]
Scheduled, included in http://community.openfoodnetwork.org/t/fixes-to-single-order-edit-and-order-index-page/170

**Comment by mkllnk** [comment]
Ready in branch single-order-patches.

As discussed earlier today, the note hint is displayed under the order number instead of taking up an own column.
