### ISSUE TITLE
Translation missing "add a new card" in front end / my account / credit cards

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4190]
![Capture du 2019-08-27 10-51-04](https://user-images.githubusercontent.com/8135376/63756453-af2cd780-c8b8-11e9-8d6e-f9afffd93031.png)

Discovered on French instance v2.2.3 while update user guide.

**Comment by RachL** [comment]
@myriamboure if you put it as a good first issue, can you please stick to the template? I'm sorry. I know it is long but at least you need to detail the step you do to get to this page, otherwise a new dev will not be able to pick this one up.

**Comment by daningenthron** [comment]
Hi, I can go ahead and grab this if no one is on it yet?

**Comment by sigmundpetersen** [comment]
Go ahead @daningenthron 🙂 Thanks!

**Comment by sauloperez** [comment]
Hi @daningenthron! Welcome!
Very happy to have your help with it.

If you have any questions setting up the dev env, with Github, etc. feel free to ask on the dev channel of [our Slack team](https://join.slack.com/t/openfoodnetwork/shared_invite/enQtMzU2Mjk5MDc2MjA5LTM4ZTAzZjIwNzIxMmU5ODFiNWY1MTU2ZWUyNzQwNjdjNTY0N2VhY2UwOGU4ZmVjNzYyZDU2NjY3NzZkZmQwYjk).
