### ISSUE TITLE
Release v2.3.0 Aloe Vera

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4191]
Release draft:

https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-aed950c1fce3b12aa462

Ongoing testing notes: https://docs.google.com/document/d/1A7PDecifh-9IXONUpgdBz5ZDl_4GwCE1Ohi4_YY0nfc/edit#

**Comment by lin-d-hop** [comment]
Note we tested with #4157 (we did release testing on this PR branch).

So this release includes #4157

**Comment by mkllnk** [comment]
Great! Done! :muscle:
