### ISSUE TITLE
French hub manager can't access anymore some specific front end shops... strange thing

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4192]
## Description

François (manager of Micromarché, La Grande Barge, various hubs in France) can't access anymore the front end page of 2 of his shops when he is connected with this user or this one.
- https://www.openfoodfrance.org/epicerie/shop
- https://www.openfoodfrance.org/boutiqueenligne/shop
Strangely, no problem with his other shops, and he can also access them when he is not connected as a user with one of those two accounts (with francois[at)ledebutdesharicots.fr or micromarche[at]ecosnantes.org.)
No issue of accessing the backoffice, all good on backoffice, only those two shopfronts when he is connected with one of the two user accounts...

![download](https://user-images.githubusercontent.com/8135376/63787561-567b3000-c8f4-11e9-83c7-35508c4dfd62.jpeg)

He needs to access those shops on an everyday basis as he uses them to manage the sales in his physical shop... so it's quite urgent to find the problem.

UPDATE : this user created a new enterprise and recreated the OC under this new enterprise and it solved the problem. He has done that several time in the past, so apparently it seems that the enterprises under those shopfront and/or the associated users starts to have too much data associated, so when he starts fresh with a new enterprise he can again access the things... apparently this was a workaround that worked again here. 

## Steps to Reproduce

1. Hard to reproduce, didn't manage... maybe if we connect with his user account but we need to change his password, I can ask him if we really need but maybe the network info will already give a clue of the problem.

## Context

Reported by the user

## Severity
Switching from s2 to s3 as the user found a workaround to recreate (for the 5th or 6th time again...) a new shop to somehow "lighter" the dataset associated to the enterprise and it seems if worked, but the problem still persist.

**Comment by RachL** [comment]
@myriamboure have you tried to add yourself as a manager?

**Comment by myriamboure** [comment]
Don't knopw how to prioritize, maybe it is link to some performance work ?

**Comment by myriamboure** [comment]
I didn't try @RachL I probably should have. I had no difficulty to access when NOT a manager though... so yes that might be a clue...

**Comment by luisramos0** [comment]
we should analyse this issue, there's an error 500, not 502/504, so it's not obviously a performance/timeout  problem... I think it's a good time to raise this issue to s2, or move it to top 5 s3s or maybe just include it in the performance epic for analaysis.

**Comment by RachL** [comment]
This issue is not reported by the user anymore. Closing
