### ISSUE TITLE
`bundle exec` error during deploy

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4193]
## Description

_Written by Maikel. Matt's the author because his account is connected to Bugsnag._

While deploying v2.3.0 the following error was raised. From the timing I can tell that it was probably during unicorn restart but definitely before notifying Datadog. It seems like the current working directory has been moved or deleted. The error happened on every deployed instance. This issue may be about ofn-install instead of openfoodnetwork.

All services seem to be restarted though and I didn't observe any negative effects.

## Error in OpenFoodNetwork UK

**Errno::ENOENT** in **/home/openfoodnetwork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:71**
No such file or directory - getcwd

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5d65df2b58cd94001b4e20dc?event_id=5d65df2b004dc0b8d7190000&i=gh&m=ci)

## Stacktrace

    /home/openfoodnetwork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:71 - getwd

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5d65df2b58cd94001b4e20dc?event_id=5d65df2b004dc0b8d7190000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by sauloperez** [comment]
this is very weird. It's what happens when the current directory is an old `current`. Did someone manage to reproduce?

**Comment by Matt-Yorkley** [comment]
I've seen this a couple of times during deployment. Hopefully this will be fixed by https://github.com/openfoodfoundation/ofn-install/pull/595
