### ISSUE TITLE
Emails not landing in Inbox

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4194]
## Description

The number of reports of emails not arriving in inboxes is increasing. We need to take another look at our Sendgrid and DNS to improve inbox landing.

DNS and Sendgrid details in Bitwarden

## Expected Behavior

All OFN emails arrive in inbox

## Actual Behaviour

Many successfully send according to Sendgrid, but fail to land in inboxes. However the emails do not appear in the spambox of users either.

## Context

Many suppliers miss there orders as supplier notifications do not arrive. Forgot password emails are also regularly affected.

## Severity

bug-S2 - We've asked users to improve things on their end and the problem persists.

## Possible Fix

Change your record from:
v=spf1 include:_spf.google.com ~all
to:
v=spf1 include:_spf.google.com include:sendgrid.net ~all
https://sendgrid.com/docs/glossary/spf/#already-have-an-spf-record-for-your-domain

**Comment by Matt-Yorkley** [comment]
Done :+1:

**Comment by lin-d-hop** [comment]
Reopening this as this week we've had a high number of reports of missing emails.
Specifically Order Confirmation Emails

**Comment by Matt-Yorkley** [comment]
I updated the SPF records to include Sendgrid, as suggested in the Sendgrid docs. Does anyone else have any ideas for how to improve email delivery rates?

**Comment by luisramos0** [comment]
you can leave sendgrid for a better provider?
I worked with authsmtp.com in the past.
there's mandrill and others: https://www.codeinwp.com/blog/best-smtp-providers/

**Comment by luisramos0** [comment]
in terms of OFN we can give a try to https://litmus.com/ to improve email quality.

**Comment by luisramos0** [comment]
one thing we should maybe consider is to never use production email providers for staging servers. emails sent by staging servers are less likely to be opened and clicked and thus will influence negatively overall reputation.

**Comment by lin-d-hop** [comment]
That is a good thing to know and remember... And probably not something we've done.

**Comment by lin-d-hop** [comment]
There is much I don't understand...

- Other instances also use Sendgrid yes? But no one else seems to have such dramas with email deliverability.

- What are other instances using as their mail client?

- Maybe the staging server issue is actually an important part of this..... Is that a difference with UK to other servers? #onthetodolist

**Comment by luisramos0** [comment]
Email deliverability is a complex business and one of the dimensions is location. The rules in the UK are different and different SMTP services performance differently in different countries.
Also, it's not just the sender you need to consider but the recipients. What email domain are most of your users?

**Comment by lin-d-hop** [comment]
We've been asking the enterprises for a while and the results are a mix of the free ones - yahoo, gmail and live are all causing problems. We consistently ask them to follow a set of steps on their side though I have no idea how often they actually pass our advice on to shoppers.

**Comment by luisramos0** [comment]
do you have deliverability stats in sedngrid? # of opens, # of clicks, # of unsubs, # of spam reports, etc?

**Comment by lin-d-hop** [comment]
Yeah. Every time someone reports I check and sendgrid reports 'delivered'. Meaning that it is blocked on the client end right? But people are checking their spam and not finding them.

**Comment by lin-d-hop** [comment]
We don't pay for sendgrid so only have 3 days worth of history

**Comment by luisramos0** [comment]
wait, sendgrid reports delivered and users dont see it? really? that's very strange!
I thought we were talking about the case where user finds email in spam, these are very different cases.

**Comment by lin-d-hop** [comment]
No. The specific case is that Sendgrid reports delivered and according to the enterprise managers the users check spam and it is definitely not there. This is happening a lot. Every time I check (when I get the specific user's email address within 3 days) this is the case. 

I've spoken to Sendgrid and they've done a lot to get us whitelisted. The problem seems to be beyond the control of Sendgrid.

**Comment by lin-d-hop** [comment]
Please do ask more questions... apologies for not being more clear. I'm not overly familiar with the jargon in emailland.

**Comment by lin-d-hop** [comment]
Hi @luisramos0 You sound pretty knowledgeable on email delivery. Any other thoughts on this?

**Comment by luisramos0** [comment]
My actions here would be to change provider and get a specific report from a user.
Do reporting users know the difference between spam and social tabs for example? Have they been trained to look up the email in the right folders?

**Comment by lin-d-hop** [comment]
@luisramos0 I've been working on this for months. Yes they do. I wrote a whole forum post about it (though our forum is currently down so I can't share that until I fix the forum #backlog).

I specifically put a lot of effort in to enterprises to be 100% sure that users are definitely not receiving their emails. Sometimes this happens to a hub manager so I can talk to them directly. I have delayed making on issue on this for month because I've really really really tried every possible thing to know that it's not just user error.

Maybe we do need to change providers :-(

**Comment by lin-d-hop** [comment]
Closing as I guess this is back to me to work on.

**Comment by luisramos0** [comment]
it would be good to see an example with some screenshots. maybe you can share a screenshot of sendgrid console where you see the email being delivered.

**Comment by lin-d-hop** [comment]
Ping @luisramos0 As we only have sendgrid data for 3 days I can't do that specifically. But here, in detail, is my process.

1) User reports that someone didn't get their email.

2) I send a standard reply that says I need the email address and the specific email so I can look into it. Also please check spam filters and here are links to improve email deliverability for live, yahoo and gmail. We have a post that explains this in detail on our forum. Includes info on why deliverability is so hard to try and encourage patience eg 90% of emails are spam.

3) 50% of the time I get the email address within 3 days.

4) I go to sendgrid and find the specific email. I see this screen:
![Screenshot from 2019-10-01 12-29-48](https://user-images.githubusercontent.com/8669848/65958727-04c04b00-e448-11e9-878a-6928c23817fb.png)

5) I send an email back to the user explaining that according to our systems the user definitely got the email and so the problem is likely with their mail clients eg Outlook and further links to steps.

6) Usually I don't hear back. But I do hear from the same shop managers every week with 1-3 emails that are missing. Sometimes this means lost revenue as producers don't deliver. Other times it is missing password resets so people don't order. 

We've been in this dance for about 6 months and there is only so long I can keep repeating the same information to them without it being patronising.

**Comment by lin-d-hop** [comment]
We do send a copy of every email to hello@openfoodnetwork.org.uk. I wonder if this might be having an impact. These emails are NEVER opened.

**Comment by luisramos0** [comment]
ok, that's very useful information!

your example is a ac.uk email, that could be related to the mail server at that particular school...

but I think I found the main problem, it's the dns records for openfoodnetwork.org.uk
I used mxtoolbox for this.
no dmarc or spf:
https://mxtoolbox.com/domain/openfoodnetwork.org.uk/

it's even blacklisted in one service, I checked it, BACKSCATTERER but the IP is not there...

anyway, spf and dmarc need to be fixed.
where is this mail domain registered mail.vhdns.net? some dns config needs to be made there. 

Lets re-open this issue at least to fix this spf and dmarc DNS entries, AUS, FR and UK at least have this problem.
For example https://mxtoolbox.com/domain/openfoodfrance.org/
https://mxtoolbox.com/domain/openfoodnetwork.org.au/

**Comment by luisramos0** [comment]
"These emails are NEVER opened."
It depends what mail server we are using to manage this address. if this is a gmail account it could have an impact on gmail deliverability as gmail will see these no-opens and use it for their overall stats for this domain.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley Can you take care of this?

@luisramos0 Thanks again for the detective-ing! :heart:

**Comment by lin-d-hop** [comment]
UK DNS with Vidahost - details are in bitwarden. However Matt has done quite a bit of this in the past so I think he'll be quickest.

**Comment by kristinalim** [comment]
@lin-d-hop Emails of OFN UK use G Suite, right?

There is a low limit for sending through SMTP:

> The maximum number of unique recipients allowed per user per 24-hour period is approximately 130 times the number of user licenses in your G Suite account.

https://support.google.com/a/answer/2956491#sendinglimitsforrelay

Could this be the issue? Do you see bounce emails in the inbox of the sender email account?

**Comment by lin-d-hop** [comment]
@kristinalim We use Sendgrid. So I dont think this is related.

**Comment by kristinalim** [comment]
Yes. Thank you, @lin-d-hop. I got confused from seeing Google in the SPF record and then my general lack of understanding about SMTP relay. :joy:

**Comment by Matt-Yorkley** [comment]
Ok, it turns out the format for SPF records was changed slightly at some point, and the guides I looked at recommended the old version, which is now deprecated. I've updated it and the mx record checker now shows the SPF record correctly.

I'm looking at DKIM and DMARC now.

**Comment by Matt-Yorkley** [comment]
Ok, we've got SPF, DKIM, and DMARC. I've set some monitoring as well so I'll be notified if there's any issues with bounces due to DMARC issues.

**Comment by luisramos0** [comment]
I'd keep this issue for all OFN domains, au and fr are still broken:
For example https://mxtoolbox.com/domain/openfoodfrance.org/
https://mxtoolbox.com/domain/openfoodnetwork.org.au/

**Comment by luisramos0** [comment]
lets do this for the other servers.

**Comment by luisramos0** [comment]
Let's do this.
@Matt-Yorkley it's probably a good idea to have a little guide how to do this in the DNS register.
We can then ask all instance managers to share their dns register credentials so that a dev can do the work of setting appropriate dns records for dmarc and spf.
Apart from FR and AUS I see canada is also not setting dmarc and spf.
And... Katuma.org is also blacklisted by Spamhaus DBL

**Comment by Matt-Yorkley** [comment]
SPF is fairly straightforward, but DMARC is a bit more complicated. I think these configurations could be very different on each instance, depending on their email setup.

**Comment by Matt-Yorkley** [comment]
Update (copied from Slack):
```
I've just had to revert our DMARC settings after reviewing some of the debug information, as we were getting DMARC failures, which is not good. Basically it's not straightforward at all, and will need more analysis and maybe restructuring how we handle emails.

We're getting failures from `about.openfoodnetwork.org.uk` for example, and I'm not sure how easy it is to customise our mail settings there, with the Docker/Discourse setup, and possible failures from forwarded emails on gmail accounts used for support.
```

**Comment by kirstenalarsen** [comment]
This is happening in Aus

**Comment by luisramos0** [comment]
ok, lets look at all the problems we have here:
checked:
https://mxtoolbox.com/domain/openfoodfrance.org
https://mxtoolbox.com/domain/openfoodnetwork.org
https://mxtoolbox.com/domain/openfoodnetwork.org.au
https://mxtoolbox.com/domain/openfoodnetwork.org.uk
https://mxtoolbox.com/domain/katuma.org
https://mxtoolbox.com/domain/openfoodnetwork.net
https://mxtoolbox.com/domain/openfoodnetwork.ca
https://mxtoolbox.com/domain/openfoodnetwork.be
https://mxtoolbox.com/domain/openfoodnetwork.de

- [ ] ERROR - blacklist Blacklisted by BACKSCATTERER - UK
- [ ] ERROR - blacklist Blacklisted by Spamhaus DBL (mx1.filterantispam.com ) - KA
- [ ] ERROR - dmarc DNS Record not found - FR, ORG, AU, KA, US, CA, BE, DE
- [ ] ERROR - spf DNS Record not found - BE
- [ ] ERROR - mx No DMARC Record found - FR, ORG, AU, KA, US, CA, BE, DE
- [ ] ERROR - smtp mx1.filterantispam.com | Failed To Connect - KA
- [ ] WARN - spf No SPF Record found - AU, US, CA, DE
- [ ] WARN - dns SOA Refresh Value is outside of the recommended range and SOA Expire Value out of recommended range - FR, ORG, AU, UK, KA, US, CA, BE, DE
- [ ] WARN dns SOA Serial Number Format is Invalid - UK
- [ ] WARN - mx DMARC Quarantine/Reject policy not enabled - FR, ORG, AU, UK, KA, US, CA, BE, DE
- [ ] WARN - spf Too many included lookups (14) - FR 
 - [ ] WARN - smtp DNS Reverse DNS does not match SMTP Banner - ORG, AU, US, CA, BE, DE
- [ ] WARN - smtp Reverse DNS Resolution FAILED! This is a problem - AU, US, CA, DE
- [ ] WARN - smtp | mail.vhdns.net | Warning - Does not support TLS. - UK

SPF is needed for dmarc so we should start with fixing the SPF issues.
I'll look at a specific case FR and see what can be done.

**Comment by luisramos0** [comment]
Regarding SPF records.
Email providers per domain right now:
gmail - AU, CA
sendgrid - BE, DE, FR, UK, US
mandrill - KA

AU, US, CA, DE and BE are missing SPF records.
So, for the gmail ones AU, CA according to [this](https://support.google.com/a/answer/33786?hl=en) we need to add something like: v=spf1 include:_spf.google.com ~all.
For the sendgrid ones US, DE and BE, according to [this](https://sendgrid.com/docs/glossary/spf/) we need to add something like this: v=spf1 include:sendgrid.net ~all

**Comment by luisramos0** [comment]
@Matt-Yorkley re your dmarc errors above, did you see in dmarc there's a DMARC Policy that you can set to none (p=none), basically you can  setup dmarc but let the providers know you dont want it enforced. With this setup we can see reports and gradually fix the problems. When we think all is fixed, we can change the policy to p=quarantine or p=reject

**Comment by luisramos0** [comment]
@Matt-Yorkley "We're also getting what looks like failures from related to gmail accounts used for support."
Yes, after you setup dkim you need to make the webmail app use dkim to send emails outs.
This is how you [do it in gmail](https://support.google.com/a/answer/180504).

I just realized that sendgrid does this for us automatically, [this](https://sendgrid.com/docs/ui/account-and-settings/how-to-set-up-domain-authentication/#using-automated-security) is done correctly in FR.

**Comment by luisramos0** [comment]
We are now getting dmarc reports for FR in admin@openfoodfrance.org
We have errors coming from emails sent from @forums.openfoodfrance.org
Maybe we need

@Matt-Yorkley can we change the dmarc uk email from your email to some admin account so other people can have access? Is this the same type of error you are getting for about.openfoodnetwork.org.uk?

I think the solution is to add these domains to the spf record and make the discourse mail config use dkim.

**Comment by Matt-Yorkley** [comment]
> did you see in dmarc there's a DMARC Policy that you can set to none (p=none), basically you can setup dmarc but let the providers know you dont want it enforced. With this setup we can see reports and gradually fix the problems. When we think all is fixed, we can change the policy to p=quarantine or p=reject

Yes, and we have error reports. I think it won't be easy to fix. I'm not sure how to configure DKIM our discourse, because it's in a Docker container.

**Comment by luisramos0** [comment]
I got access to AUS godaddy account now, thanks Kirsten!

In https://dcc.godaddy.com/manage/OPENFOODNETWORK.ORG.AU/dns
I added the google SPF entry:
![Screenshot 2019-11-07 at 11 06 35](https://user-images.githubusercontent.com/1640378/68384174-f3f1ac00-014e-11ea-8293-787b971d0e68.png)

SPF record for openfoodnetwork.org looks good with google (and madrill?).

Added dmarc records for both openfoodnetwork.org and openfoodnetwork.org.au

I needed these reports to be sent to a shared inbox that I had access so I used the newly created mailbox: tech at openfoodfoundation in the dmarc records above.
For the dmarc reports to be received in a different domain that the domain they refer to they need these entries in the destination domain, in this case I added this to the openfoodfoundation.org dns:
![Screenshot 2019-11-07 at 11 21 32](https://user-images.githubusercontent.com/1640378/68385124-00770400-0151-11ea-8a53-768321ff7425.png)

This fixes the dmarc errors in .org and .org.au
Now we need look at these dmarc reports and fix the problems in there (usually dkim issues).

**Comment by luisramos0** [comment]
In the gsuite console for openfoodnetwork.org I started authentication of emails:
![Screenshot 2019-11-07 at 11 51 03](https://user-images.githubusercontent.com/1640378/68386877-f0612380-0154-11ea-8715-9207cdb54990.png)

This was already activated for openfoodnetwork.org.au

**Comment by luisramos0** [comment]
I have checked dmarc reports on openfoodnetwork.org and openfoodnetwork.org.au and both have dkim problems. I am not sure what else needs to be done in google config. It needs to be investigated.

**Comment by daniellemoorhead** [comment]
@luisramos0 it looks like you're working on this but it's assigned to @Matt-Yorkley, do you need to change it to you?

**Comment by luisramos0** [comment]
Hi @daniellemoorhead yeah, I added myself, I left Matt as Matt is looking for the UK part of this.

**Comment by luisramos0** [comment]
ok, to replace this already long issue I have created the epic #4491 with 5 issues so far.
