### ISSUE TITLE
All OC are showing an invalid date as a closing date

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4195]
## Description
All OC on all shops / instances are showing "invalid date" as a closing date.

## Steps to Reproduce

Go to any open shop e.g. https://www.openfoodfrance.org/pas-une-boulangerie/shop
https://openfoodnetwork.org.uk/locavoregrocery/shop

## Animated Gif/Screenshot
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/0e030fdb-00d2-4a91-8ab2-27ae3118b863)

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
* Version used: v2.3
* Browser name and version: Firefox 68
* Operating System and version (desktop or mobile): Desktop

**Comment by kristinalim** [comment]
This looks like a browser issue. I can reproduce this in Firefox `68.0.2`, but not in the following:

* Chromium - `Version 72.0.3626.109 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)`
* Google Chrome - `Version 75.0.3770.100 (Official Build) (64-bit)`
