### ISSUE TITLE
Warning message if enterprise user leaves enterprise management without update / save

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#420]
An enterprise user can make changes within any tab of their enterprise management screen, and switch between tabs. Those changes are saved when they hit the update button (at the bottom)

There is no warning if the User selects 'back to Enterprise list' or clicks elsewhere (e.g. top menu) and has not saved changes.

![image](https://cloud.githubusercontent.com/assets/2911176/6649720/008a3c88-ca46-11e4-93ff-083b2cfc67f8.png)

TODO
- create warning message if User clicks link to leave the page and there are unsaved changes in any tab. Generic / standard warning e.g. "You have unsaved changes, do you want to leave this page or stay"

**Comment by elf-pavlik** [comment]
possibly one could reuse

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/enterprises/controllers/enterprise_controller.js.coffee#L11-L19

**Comment by OliverUK** [comment]
@lin-d-hop @sstead 

I've tested this separately from the enterprise switcher test in a separate issue but I think it's in the same piece of code??

It worked for me once after deploying to staging but after the first time, further testing does not normally produce a warning message even if unsaved changes are present. 

I logged out and logged back in again and tried again.
If I get a warning message and then choose Stay on Page and then save, I can make another change attempt and still get the warning message and so then it works.

If I choose to leave the page without saving, this seems to break the warning message and I don't get any more warnings from then on. This seems to happen even if I'm editing a different enterprise with the exception of the new switcher drop-down, which seems to produce warning messages ok in any case.

I tested this in Safari using spree@example.com.

I also noticed that creating a tag rule throws up a superfluous warning.

![screen shot 2016-12-13 at 15 22 11](https://cloud.githubusercontent.com/assets/17590921/21145969/0df09408-c148-11e6-80a7-e9744a0ce527.png)
![screen shot 2016-12-13 at 15 22 20](https://cloud.githubusercontent.com/assets/17590921/21145970/0dfb2134-c148-11e6-9647-9644e8ba85cc.png)

**Comment by lin-d-hop** [comment]
@Matt-Yorkley Could you look at @OliverUKs testing notes above?

**Comment by Matt-Yorkley** [comment]
@OliverUK Updated and ready for testing.

**Comment by OliverUK** [comment]
Might have to remind me what I need to deploy for re-testing. I tried the latest uk/switcher build but it failed.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley Merge conflicts?

**Comment by Matt-Yorkley** [comment]
I think there's a seperate branch made by mkllnk with some changes, but it also needs some further adjustments. I'll sort it soon.

**Comment by lin-d-hop** [comment]
Thanks @matt-yorkley :-)
