### ISSUE TITLE
'Back' from Edit Order removes filters on Orders page

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4207]
## Description

A small UX improvement such that a browsers Back buttons maintain filtering.

## Expected Behavior

1. A user filters the orders on the Orders page to find a specific set of orders.
2. They then click Edit Order to make some changes to it.
3. They save this then hit 'Back' or the button 'Back to Orders List'.
4. They're taken back to the Orders page and all of their filters are still in place meaning that I'm still shown the same set of Products as before I navigated away.

## Actual Behaviour

1. .... As above
2. .....
3. ....
4. They're taken back to the Products page but their filters have gone. They need to reload the filters, which takes time. If I'm editing dozens of orders (and I can't do it in  the BOM) I quickly get annoyed!

## Steps to Reproduce

See above.

## Context

When I have a number of changes to make to multiple orders I get quite annoyed. For large hubs this becomes unwieldy quite quickly as there are often sizeable changes to make and I can't make them on the Orders or BOM pages.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: 2.3.1
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Linux
* OFN Platform instance where you discovered the bug, and which version of the software they are using. UK

**Comment by kirstenalarsen** [comment]
in the short term we could handle this with similar interim fix as we applied to the products - just default to opening the order in a new tab - would you have an objection to that as a simple short-term papercut @lin-d-hop ?

**Comment by NickMoignard** [comment]
Yeah, I am interested in this issue.
Let me work on this

**Comment by rioug** [comment]
I'll look at this as well, should be just a matter of adapting what I did for #4206

**Comment by sigmundpetersen** [comment]
Thank you @rioug 🎉

**Comment by rioug** [comment]
Unfortunately I am going to have a lot less free time, so I am going to leave this one to someone else.

As mentioned above, you can look at #4206 and use a similar solution.

**Comment by sauloperez** [comment]
I was talking a look at https://github.com/openfoodfoundation/openfoodnetwork/pull/5722 and I'm not sure this would fit into half a day. Maybe but there's quite a lot of code involved.
