### ISSUE TITLE
Fix rubocop issues in taxons_controller

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4209]
### What we should change and why (this is tech debt)
Rubocop issues in app/controllers/api/taxons_controller.rb should be solved.

### Context
The file was moved as part of #4104 so existing rubocop issues were flagged by codeclimate.

### Impact and timeline
We should aim to get no rubocop issues in ofn.

**Comment by macanudo527** [comment]
I think this is resolved:
```
~/workspace/ofn$ bundle exec rubocop app/controllers/api/v0/taxons_controller.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

Note that the actual file is located at app/controllers/api/v0/taxons_controller.rb

**Comment by dacook** [comment]
Good question. Perhaps it got fixed previously and this never got closed (I can only find one small error in the git history).
🤷 

The admin controller has five completely different violations, so I think we should work through them one by one via #6055.

So this is done 🎉
