### ISSUE TITLE
Create drop-down for easier switching between Enterprises for management

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#421]
The Enterprise Index page shows a User all the Enterprises that they manage

![image](https://cloud.githubusercontent.com/assets/2911176/6649729/43658ff8-ca46-11e4-82a3-70f95a983e43.png)

Selecting an Enterprise Profile takes you into the Enterprise Management page
![image](https://cloud.githubusercontent.com/assets/2911176/6649682/21be96ac-ca45-11e4-8433-1b6af7457d0d.png)

To switch between management of different enterprises, the User currently needs to reload the Enterprise Index page, either by clicking on the top menu, or using the 'back to Enterprises list' button. This is annoying - would be much better to be able to change between enterprises directly  

TO DO
- Create a Dropdown selector next to the 'back to Enterprises list' that shows the names of the Enterprises that the User manages (on the right)
- Selecting the Enterprise name takes User directly into the Enterprise management page of that Enterprise
- warning if unsaved changes before going to new page (see https://github.com/openfoodfoundation/openfoodnetwork/issues/420)

**Comment by Matt-Yorkley** [comment]
@kirstenalarsen I'm working on this enterprise switcher dropdown. Do you have a preference for the layout?

Option A:

![screenshot from 2016-11-26 15-40-17](https://cloud.githubusercontent.com/assets/9029026/20641445/ad7d74a2-b3ef-11e6-9f8c-64f6aefc2340.png)

Option B:

![screenshot from 2016-11-26 15-43-08](https://cloud.githubusercontent.com/assets/9029026/20641446/ad9f87d6-b3ef-11e6-8d08-a9047377f336.png)

**Comment by kirstenalarsen** [comment]
Not a strong one, maybe slight inclination to b . . @sstead?

**Comment by sstead** [comment]
Looks great! Yes I agree, B is more similar to existing appearance.
________________________________

**Comment by lin-d-hop** [comment]
Note this PR also fixes #420 so no need to redeploy @OliverUK

**Comment by OliverUK** [comment]
@lin-d-hop 
I have tested this using the super admin login. The drop-down appears when editing an enterprise. I successfully switched between enterprises and mad changes to some and saved them, all without noticing anything untoward.

Please note, Lynne, I've only tested this in super admin. It seems I have to register my normal user account anew every day on staging and today I was once again unable to confirm the account (no confirmation email).

**Comment by OliverUK** [comment]
I have also tried a variety of changes before trying to navigate away and in each case I was warned that I had unsaved changes.

**Comment by lin-d-hop** [comment]
Thanks @OliverUK. Ill make some changes so the mailserver updates persist then we can try again with different user accounts.

**Comment by lin-d-hop** [comment]
@OliverUK You should be able to deploy and test this now...?

**Comment by OliverUK** [comment]
I thought this was all done @lin-d-hop . Did you mean a different issue?

**Comment by lin-d-hop** [comment]
From Oliver: _Please note, Lynne, I've only tested this in super admin. It seems I have to register my normal user account anew every day on staging and today I was once again unable to confirm the account (no confirmation email)._

Would you be able to test outside of superadmin please @OliverUK?

**Comment by OliverUK** [comment]
@lin-d-hop rebuilt, redeployed and retested using my normal login - great that I now can!

Noticed no difference to the website's behaviour between the different logins. All looks to be working fine.

I also get this warning message now, which is good to have but as far as I can tell incorrect. Not part of this issue though. 

![screen shot 2017-01-10 at 16 22 37](https://cloud.githubusercontent.com/assets/17590921/21814472/5814f640-d751-11e6-8d81-53fb3cfd3bbd.png)

**Comment by lin-d-hop** [comment]
@OliverUK Payment methods are inactive as this is a prod DB copy on staging and I need to do another production deploy to save DB updates. So you will see this message until i do that.

Thanks, tested and ready for @sstead

**Comment by sstead** [comment]
@Matt-yorkley The dropdown looks good. However the dropdown list should include all enterprise that the users can edit. This includes ones they own, ones they manage and ones that have granted the user's enterprises E2E permission to edit their profile. When testing 2 profiles were missing from my dropdown- these were the ones I have been granted E2E permission to edit the profile of.
![image](https://cloud.githubusercontent.com/assets/10843056/21835087/60380ef8-d80e-11e6-986f-76d7ae709424.png)

**Comment by Matt-Yorkley** [comment]
@sstead The enterprises enabled through E2E should be included now.
