### ISSUE TITLE
A shop producer tab is showing hubs as well

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4218]
## Description
A shop frontend has a tab where buyers can see all the producers profile the shop owner is working with.

However this tab also shows hubs associated with the shop owner (thanks to permissions) including the shop owner himselft, even if he is a hub and not a producer.

## Expected Behavior
See only producer profile.

## Steps to Reproduce
1. Go to a shop and producer tab e.g. https://staging.katuma.org/mary-s-online-shop/shop#/producers
2. As you can see Mary's online shop is listed as a producer so as Maryse Private shop. But both are hubs

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/64183997-0dcef400-ce6b-11e9-8120-65d5bd687a5c.png)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v2.3
* Browser name and version: Firefox 68
* Operating System and version (desktop or mobile): Both

**Comment by sauloperez** [comment]
It seems to me that this was a regression introduced in https://github.com/openfoodfoundation/openfoodnetwork/commit/785595a951#diff-cb3a83c18bf551093003a6565c2da425R54.

**Comment by tschumilas** [comment]
This is only a S4 I realize -  but its proving quite annoying to a lot of hubs with both Aus @emilyjeanrogers and OFN-CAN having hubs raise the issue.    Is this a potential papercut? @sauloperez @luisramos0 @sigmundpetersen ?  (not sure who to pink for a size assessment)

**Comment by luisramos0** [comment]
Hello, quickly looking at that commit Pau linked, it does look like a regression.
I think this is papercut sized, should be easy to review the queries and get the correct enterprises on the list :+1:

**Comment by emilyjeanrogers** [comment]
[Tasmanian Produce Collective ](url) have complained about this in Aus. All of the hubs are appearing in their OWN listing of Producers - even though none of these Hubs are primary producers.

**Comment by Erioldoesdesign** [comment]
Agreed with removing hubs from this tab for papercut sized issue.

Quick question, are there any cases where a hub would would with other hubs and would want them displayed? under two separate headings under the producer tab like 'Producers' and 'Hubs' (or whatever labels we want 'Growers' 'Partner hubs' etc.)

**Comment by andrewpbrett** [comment]
I believe this is fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/7015 if I've understood the issue correctly. I've moved that PR to code review.
