### ISSUE TITLE
Incomplete removal of 'owner' role when user roles deleted 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#422]
When super-admin deletes User role that maps to owner of Enterprise (from User/Roles - https://openfoodnetwork.org.au/admin/enterprise_roles page), it is not completely removed

e.g. for enterprise Richie & Rosie, all user roles have been deleted

![image](https://cloud.githubusercontent.com/assets/2911176/6650077/148ba228-ca53-11e4-87af-f3dfefc794fc.png)

and the Enterprise index page no longer shows that user as the owner
![image](https://cloud.githubusercontent.com/assets/2911176/6650075/f4ecd9a0-ca52-11e4-9efe-2119e3b85ec3.png)

but if you go into the Enterprise it is still there 
![image](https://cloud.githubusercontent.com/assets/2911176/6650079/3eb9c3a4-ca53-11e4-906d-e7ce16d81f98.png)
and still appears on Reports/Users & Enterprises
![image](https://cloud.githubusercontent.com/assets/2911176/6650084/675224b4-ca53-11e4-8288-0df55b189009.png)

TO DO
- make the User/Roles page have an indicator when role is owner
- when the owner role is deleted from the User / Roles page, remove it completely
- if there is another manager, set it to that
- if there is not another manager, set the owner to site admin
- warning when removing owner, notification of whether is setting to site admin or another manager

**Comment by lin-d-hop** [comment]
#gitcull2017
Closing as captured in the Deletions Epic.
