### ISSUE TITLE
Buyer cannot access completed orders

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4220]
## Description
This is tricky because I'm not able to reproduce this bug, but at the same time I have no evidence so far that the user did something wrong.

Set up:
- This is a new hub starting their first OC opened since Monday
- 3 buyers have pass orders
- None of them can see their order in their profile _yet_ they do have confirmation email that the order was successful and the admin order page is showing these orders as completed
- I know one of them is using Edge as a browser

What I've done so far to Sherlocked this one:

1. Tested on our demo hub with an old account - went fine
2. Tested on our de mo hub but with a fresh new buyer account - went fine
3. Went on the shop of this user https://www.openfoodfrance.org/nantes-chantenay/shop did an order with another fresh new buyer account - no problemo :face_with_head_bandage: I could even cancel the order
4. Logued in with browserstack to see if the page had a display pb with IE, but it does not look like it...

## Steps to Reproduce

???

## Animated Gif/Screenshot
Example of an affected order: #R845786132

Confirmation email:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/226f3e84-58bf-4f3d-b113-fe4083a84f3e)

Admin:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/103f8a3d-165b-4f4b-8030-5e50101c1efe)

User:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/1dcd40a1-2d7c-4426-b368-28bd9ee204c4)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.3
* Browser name and version: Edge
* Operating System and version (desktop or mobile): Desktop

**Comment by sauloperez** [comment]
Could you share order, oc, enterprise, user, etc ids?

**Comment by RachL** [comment]
Enterprise and order are in the description: #R845786132 and enterprise https://www.openfoodfrance.org/nantes-chantenay/shop 
ID is 961
However for the user I would prefer give the personal email per slack if it is ok @sauloperez

**Comment by RachL** [comment]
Closng as we are unable to reproduce.
