### ISSUE TITLE
No Products Showing for Enterprise in Superadmin

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#4221]
## Description

When logged in as SuperAdmin, I accessed Bulk Edit Products for a Producer Shop enterprise. There were no products listed but there are 28 products associated with this Producer. When logged in as Superadmin I accessed Order Cycles for the Producer and could see all the products in a past Order Cycle. When I added myself as a Manager of this Producer I could view all products in Bulk Edit Products. 

Replicated multiple times over multiple days and waited 2 minutes each time (in case page load was just slow). This was not a speed issue as I was able to load Products for other enterprises with 100+ products in 1 - 2 seconds. 

## Expected Behavior

Products should load

## Actual Behaviour

Products do not load.

## Steps to Reproduce

1. Log in as Superadmin
2. Access Products Bulk Edit 
3. Select Producer: Ninety Mile Biodynamics Lamb and bulk Beef
4. No Products load
5. Access Order Cycles
6. Select Enterprise: Ninety Mile Biodynamics Lamb and bulk Beef
7. Select edit for past Order Cycle
8. Products included in Order Cycle

## Context
I was investigating a question about product images for the customer and wanted to view their products using Superadmin. 

## Severity
This has only been replicated for one Superadmin user, attempting to access products for one Enterprise. Minimal impact, but worth investigating to understand the trigger. 

bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used:

Version used: v2.2.2
OFN Platform instance: OFN Australia

**Comment by RachL** [comment]
@emilyjeanrogers are you able to reproduce this issue now that the page is paginated for super admin?

**Comment by emilyjeanrogers** [comment]
@Rachl No I can't.  I've just checked and it looks like the issue is resolved. I can now view all the products in Superadmin for this customer, using Bulk Edit.
