### ISSUE TITLE
NoMethodErrorspree/paypal#express

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4233]
This is a more specific and technical version of #4222 and may not be the cause of it. So opening a new issue. Severity should be the same as 4222 imo.

### Error in OpenFoodNetwork

link to bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d6ea59aa104a600184d9e67?filters[event.since][0]=30d&filters[error.status][0]=fixed

![Screenshot 2019-09-06 at 09 18 26](https://user-images.githubusercontent.com/1640378/64412454-4d722780-d087-11e9-9e62-4b0616dcae31.png)

### Possible fix
To fix the paypal express error (the checkout would fail, it's just the recovery so that user does not see the snail if paypal payment fails, user should be redirected to checkout page) we need to re-add this route:
get '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**NoMethodError** in **spree/paypal#express**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d6ea59aa104a600184d9e67?event_id=5d71ccd4004f30f03d9e0000&i=gh&m=li)
