### ISSUE TITLE
cart page shouldn't show 'admin & handling' if it is zero

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#424]
![image](https://cloud.githubusercontent.com/assets/2911176/6650693/423151e8-ca74-11e4-939b-947bdddca4a9.png)

**Comment by jtruong2** [comment]
Hi I'm new to open source contributing. I saw no one is assigned. I'd like to tackle this issue.

**Comment by myriamboure** [comment]
Hi @jtruong2 ! Welcome! That would be fantastic!
If you have any questions feel free to ask here or in the #dev channel of our [Slack](https://openfoodnetwork.slack.com/) group :-)
If needs be take a look at https://github.com/openfoodfoundation/openfoodnetwork/blob/master/CONTRIBUTING.md as well.
Cheers !

**Comment by jtruong2** [comment]
@myriamboure I fixed the issue and wrote a test that if there are no adjustments, then hide the row. I'm trying to write another test that shows that it does show the row if there are adjustments but I can' figure out how to create an order that has eligible adjustments in the spec.

**Comment by jtruong2** [comment]
I can put in a PR if anyone would like to have a look.

**Comment by sauloperez** [comment]
Yes, @jtruong2, better to have discussions about the specifics of the code in a PR :+1:

**Comment by myriamboure** [comment]
@jtruong2 I don't have dev skills but as @sauloperez suggested I am sure devs will help you through with the tests on the PR :)

**Comment by jtruong2** [comment]
@sauloperez Great! I will put a PR in shortly

**Comment by mjal** [comment]
Hi @jtruong2 
I think that we need to add the entreprise_fee to the order_cycle for it to work
You can have a look at a way to do it in [this branch based on your work](https://github.com/mjal/openfoodnetwork/blob/424cart-page-shouldnt-show-admin-handling-if-it-is-zero/spec/features/consumer/shopping/cart_spec.rb) :)

**Comment by myriamboure** [comment]
@mjal Please feel free to continue the work started by @jtruong2 as he said in the PR #1955 that he wouldn't be able to finish the work and wanted to free it for someone else to tackle it. So please reopen the PR if you want to continue on it, or submit a new one with your branch if you have found how to fix the issue :-)
