### ISSUE TITLE
Inventory is limitted to the first 100 products

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4243]
## Description

The inventory page shows 10 products to start with. There is a button to display more. But it's showing only up to 100 products. An inventory with more than 100 products can't be managed.

## Expected Behavior

Then inventory shows 10 products and a button to load x more. x is the total number of products in the inventory minus the 10 products already shown. For example, the button will says "Show All (149 more)" more and after clicking on it, the total 159 products are shown and the buttons disappear.

Please note: the previous behaviour did show "Show All (90 more)" for a short time during page load. But more products were loaded in the background and that number increased to the full amount.

## Actual Behaviour

The inventory shows 10 products and a button to load 90 more. After clicking the button, 100 products are shown.

## Steps to Reproduce

1. Create or use an enterprise with inventory, for example a farm shop.
2. Add more than 100 products to the inventory.
3. Load the inventory page: `/admin/inventory`
4. Observe the button at the bottom.

## Animated Gif/Screenshot

Shown first and currently it doesn't change:
![Screenshot from 2019-09-08 16-27-14](https://user-images.githubusercontent.com/3524483/64484458-b6a79580-d255-11e9-91da-ec585b65cc27.png)

Shown in v1.3.1 when all products were loaded:
![Screenshot from 2019-09-08 16-26-22](https://user-images.githubusercontent.com/3524483/64484465-bc9d7680-d255-11e9-940d-6cd5bf4bd031.png)

## Context

The Australian farmer New Life Farm reported this issue. They use the inventory every week and this week they saw the issue. I verified that the last release introduced this bug.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround

I'm not sure if the inventory is a critical feature. But for people using it, they may not be able to manage their stock to successfully open an order cycle. Not being able to sell produce, seems to be an s1.

A possible workaround is to not use the inventory. But this may need a lot of effort and I don't know how well it works and how to best transition.

## Your Environment

* Version used: v1.4.1 au-prod

## Possible Fix

I changed the number of products loaded in one go from 100 to 200 to help our farmer straight away. app/assets/javascripts/admin/variant_overrides/controllers/variant_overrides_controller.js.coffee

But that doesn't really solve the problem. I guess, we have to apply the new Bulk Products Edit pagination logic to the inventory as well.

**Comment by luisramos0** [comment]
if S1 it's goes directly to the top of dev ready (I put it there now), even if s2 still goes to dev ready but below the other S2s.

**Comment by Matt-Yorkley** [comment]
We set a default pagination max value of 100 in an initializer recently. Maybe we can override it for Variant Overrides.

**Comment by Matt-Yorkley** [comment]
Although it should only affect explicitly paginated queries. I can't see where we do that for Variant Overrides.

**Comment by Matt-Yorkley** [comment]
It also highlight that we';re not actually using pagination on the inventory page, just loading everything at once and the show more button is actually unhiding results instead of fetching them.

**Comment by tschumilas** [comment]
Today,  I am unable (as super admin,  or as regular hub manager) to manage my inventory.  (I think I'm the only user on OFN-CAN who uses inventory,  so I can't say if any other user has this issue)  Its not quite the pagination issue described here -    I definately have over 100 products in inventory -   and I can't get any of them to show up (no inventory products,  no hidden products and no new products).     None of them show.     (Garden Party Flower Farm).   I can't find a work a round either. I can't open a shop drawing on the product list -  because the shop keeps showing the unmanged inventory.   I need to open my shop tonight,   so only thing I can think of is to create another enterprise hub  -  with no inventory -  and supply it with Garden Party Flower Farm products.  I'll do that for now -  unless anyone else has a work a round.

**Comment by mkllnk** [comment]
I wrote a spec and `git bisect` is telling me that commit f6d0de1454006b51706117fe8a001da63414b528 in #4081 broke it. It's the change in the ProductsController. The same code is used by the inventory which can't find the total number of pages now. This patch solves the issue but is not the best solution:
```diff
diff --git a/app/controllers/api/products_controller.rb b/app/controllers/api/products_controller.rb
index 6a90cdf95..5cdb9a1bd 100644
--- a/app/controllers/api/products_controller.rb
+++ b/app/controllers/api/products_controller.rb
@@ -127,6 +127,7 @@ module Api
 
       render text: {
         products: serializer,
+        pages: products.num_pages,
         pagination: pagination_data(products)
       }.to_json
     end
```
