### ISSUE TITLE
The products page can fail to display products when using pages

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4248]
## Description

The products page displays 15 products by default. You can click through more pages of products. If you are on the last page (or one of the later ones) and then increase the number of products to display per page then no products are shown.

For example, there are 150 products, 15 products are displayed per page and there are 10 pages. You can go to page 10 and then you choose to display 100 products per page. With this setting, there are only 2 pages and our current page 10 doesn't have any products.

The problem is that there is no button to change the setting because the UI assumes that there are no products at all.

## Expected Behavior

When increasing the number of products to be shown per page, I still want to see the products I was looking at. It would also satisfy to show the last page with products if the current page has no products.

As a minimal requirement, it needs to show buttons to go back to pages with products.

## Actual Behaviour

It tells me that there are no products and I need to click on Products in the menu again to go back.

## Steps to Reproduce

1. Have at least 30 products.
2. Go to products and choose the last page.
3. Increase the number of products shown per page.

## Animated Gif/Screenshot

![Peek 2019-09-09 15-46](https://user-images.githubusercontent.com/3524483/64506098-a658ee80-d319-11e9-8e68-4f74d21790ac.gif)

## Context

Just testing the new pagination.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v2.4.1

**Comment by mariocarabotta** [comment]
this is not happening anymore in the new UI
