### ISSUE TITLE
Tax selector in 'add product' doesn't give me an option for 'none'

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#426]
![image](https://cloud.githubusercontent.com/assets/2911176/6681344/06f5e58e-ccb9-11e4-8ba0-f159c3e916cb.png)

once i go in to edit the product, the dropdown does give me this option. 

As the tax is calculating and appearing on checkout etc, this will mean that the default is to be charging tax on a whole lot of items that people aren't expecting it to (e.g. any new product created, if they don't manually go and change it back in the full product edit interface)

![image](https://cloud.githubusercontent.com/assets/2911176/6681365/71df5060-ccb9-11e4-87fe-da77d49b158f.png)

**Comment by kirstenalarsen** [comment]
see also https://github.com/openfoodfoundation/openfoodnetwork/issues/416

**Comment by RohanM** [comment]
I've allowed selecting 'None' for tax category on products, with the exception that if products require a tax category (see 'Tax Settings'), then a choice must be made.
