### ISSUE TITLE
Order confirmation screen should have Contact info panel open by default

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#427]
so that it is clear to the Customer who they should contact with any changes or additional requests

![image](https://cloud.githubusercontent.com/assets/2911176/6682110/00d7f800-ccc7-11e4-8ef3-102b2e16c4ab.png)

**Comment by livcg** [comment]
Should the Contact panel be open by default only right after an order is placed?  Or anytime a show order page is displayed?

What's the best way to achieve this?  I see that the Contact panel is displayed when the URL has the format https://staging2.openfood.com.au/orders/R603575485##contact and the panel is activated by Angular.  Is there some spree magic that I should use to modify the resulting URL after a purchase or should I add some JS to activate the tab after the HTML loads?

**Comment by myriamboure** [comment]
Captured in icebox: https://community.openfoodnetwork.org/t/customer-easily-go-through-the-whole-placing-order-process/1245 #gitcull2018
