### ISSUE TITLE
In new enterprise email, community forum link send to global forum for all instances...

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4273]
## Description
After an entreprise is registered on OFN, the owner receive an email with link to user guide, admin panel, and forum.
The forum link apparently redirect to community.openfoodnetwork.org, there is no way in configuration to fill in the local forum url, and so to link it inside the translation key "email_community_html "

## Expected Behavior
Forum link in local instance redirect to local forum

## Actual Behaviour
It doesn't

## Steps to Reproduce
1. Create an enterprise in local instance
2. Click on the forum link in the email received

## Animated Gif/Screenshot
![Capture du 2019-09-18 22-47-24](https://user-images.githubusercontent.com/8135376/65184857-af0e9a80-da66-11e9-9cf9-c15164f7272f.png)

## Context
Noticed that when working on all the registration wordings to try to solve registration confusion...

## Severity
S3, no really direct workaround, but for now the forums are not so much used...

## Your Environment

* Version used: 2.4.1
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu
* OFN Platform instance where you discovered the bug : French

## Possible Fix
I guess, add in the configuration space a field to fill in the local forum url, and then fix the translation key to use it ?

**Comment by myriamboure** [comment]
@RachL I added that to missing translations even if not only missing translation, I mentioned the translation issue in another issue, this is about the redirection link, but it's an internationalization issue... so would put it in the same "basket" of translations...

**Comment by RachL** [comment]
@lin-d-hop I believe this is a feature request (instances being able to specify link to their own forum). Shall I open a potential papercut?

**Comment by RachL** [comment]
Actually.... this is already working!! 🎉
