### ISSUE TITLE
Release v2.5.0

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4274]
Draft is here: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-1a2a6c095252cf45a112
Target commit is here: https://github.com/openfoodfoundation/openfoodnetwork/commit/3535c4d564d0d44f7961a25a9f98f531f2c870e0
Build to deploy is here: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/862

- [x] Draft
- [x] Test
- [x] Publish
- [x] Deploy

**Comment by RachL** [comment]
This is ready to go ! https://docs.google.com/document/d/1lsewB9hohQTsEDrSA2mF_f0Ni1eIH58dIdAFZcb58j4/edit#

I thought there was a problem with shipping orders paid through stripe and paypal. But actually it was just a bit slow. Maybe some checks need to happen before the ship button can be activated?

**Comment by kristinalim** [comment]
I wish to deploy this on Monday, because this release includes some critical changes and we don't want to be stuck with a high severity bug over the weekend.
