### ISSUE TITLE
A translation has disappeared in new product creation and create confusion in user's mind

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4276]
## Description
The field to put the nb of units have lost the previous translation with Spree upgrade.
On French production :
- before (from image in user guide) :
![Capture du 2019-09-19 15-18-40.png](https://images.zenhubusercontent.com/5549b4964f7a08fbb7f2b552/437abc38-ccab-4e87-b8dc-dbaac7159b41)
- now (current production)
![Capture du 2019-09-19 15-19-43.png](https://images.zenhubusercontent.com/5549b4964f7a08fbb7f2b552/adcd54d3-bffb-459f-b281-c32f90d10849)

I was doing support to a user who had put the price in this field, because "montant" (new automatic translation from spree I guess) means more like price in French... where we expect nb of units. It is pretty confusing and induces users mistakes.

This string needs to be translatable again so we can put the right translation.

## Severity
bug-s3

## Your Environment

* Version used: 2.4.1
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu

**Comment by luisramos0** [comment]
This could have been fixed in transifex here:
https://www.transifex.com/open-food-foundation/open-food-network/translate/#fr/enyml/80855260?q=key%3A%22value%22

But better add a page specific translation key for this "value". New PR.
