### ISSUE TITLE
new Enterprises have button for Admin Dashboard at completion of sign-up

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4277]
## Description

As a new user signing up as an enterprise, I go through the Registration wizard. When I have completed the registration I see this panel

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/c9a56f7e-391c-446e-a076-e1fc36bc6372)

If I close the box or hit the button I go to the home page. In order to continue setting up my profile or shop (including select package, make visible) I need to go to openfoodnetwork.org.au/admin - which requires me to go to the Profile menu item, and select Administration. There is no prompt to do so. It is weird and confusing

As instance managers we think a significant number of enterprise sign-ups are getting lost and never making it into the Dashboard.

![image](https://user-images.githubusercontent.com/2911176/73997927-04b2f780-49b4-11ea-9322-daf2690630d4.png)

I want to be able to 
* complete the front-end registration and be taken directly to the next step of enterprise sign-up, which is package selection at openfoodnetwork.org.au/admin/enterprises/my-enterprise/welcome

There are (currently) two options for how this could most easily be resolved
 
On this modal at the final step of the registration can we please:

1. Change the URL on the button to go directly to https://openfoodnetwork.org.au/admin (will be package selection screen if they haven't selected one) (and text on the button to "Go to Enterprise Dashboard")

NB. Noting that everyone can adjust text on this page via translations we haven't focused on rewording it

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/dbcfc199-bffb-4565-a130-a21d941400ec) 

## Acceptance Criteria and Tests

1. New user can create an Enterprise using the front-end wizard
2. It is clear at the end of the wizard that they need to go to the Dashboard to finish setting up and activate their Enterprise
3. It is extremely obvious that they do so . .

**Comment by sauloperez** [comment]
> Or possibly even do away with the panel all together and just take them straight to https://openfoodnetwork.org.au/admin/enterprises/zapier-rules-ok/welcome

I'd go with that.

**Comment by kirstenalarsen** [comment]
Needs to be on correct template and agreed solution

**Comment by RachL** [comment]
Thank you @kirstenalarsen for filing this! We changed all our translation in France but it is indeed still not helping people to understand how to end up on the admin panel from the home tab.

I agree there is no need for the home button, but I disagree we should move them directly to the admin side. Indeed this is the only part of the process they can do later: at this stage only their registration is taken into account. So I would keep it and just change the button URL and name. I don't think it matters where the button links to at the admin side: if you don't choose a package, you will always have the package selection I believe. So either /enterprises or /dashboard are fine by me.

So my vote goes for Option 1.
