### ISSUE TITLE
[API clean up] Move soft_delete to destroy in both api/products and api/variants

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4278]
### What we should change and why (this is tech debt)
The actions soft_delete and destroy are duplicated. We dont have hard_deletes any longer so we need to move soft_delete to destroy and remove destroy from both api/products and api/variants.

DELETE api/product/21/soft_delete should be converted to DELETE api/product/21
This endpoint is used in app/assets/javascripts/admin/bulk_product_update.js.coffee
API doc in swagger needs to be updated afterwards.

### Context
This came up from the API documentation work #3001 

### Impact and timeline
This is kind of urgent as the duplicated actions dont have similar implementations...

**Comment by kshlyk** [comment]
@luisramos0, do you mind if I fixed it?

**Comment by luisramos0** [comment]
yes, pls go ahead, let me know if you have any questions!
we need to keep the code under soft_delete and move it to destroy.

**Comment by kshlyk** [comment]
@luisramos0, almost done. Are there an external API consumers which can be affected by removing `soft_delete` method?

**Comment by luisramos0** [comment]
great! no, no external clients.
these are used internally by the bulk products edit page: /admin/products
when you delete products and variants.

here (I think you just need to delete the /soft_delete part of the url):
https://github.com/openfoodfoundation/openfoodnetwork/blob/0f588dbe0bf5ac6611341d95496f2fbae5a42cbb/app/assets/javascripts/admin/bulk_product_update.js.coffee#L141

and then the unit test for that js code:
spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee

you can run js unit tests with karma:
bundle exec rake karma:start

**Comment by kshlyk** [comment]
OK. Thank you. I've already found that js. Btw, I think we should consider implementing versioning in our API. It will become vital if we decide to develop OFN mobile apps. As far as I see API has no version now.
