### ISSUE TITLE
If I include a Hub profile in a Group, the Hubs tab fails

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#428]
possibly needs to include the 'show profiles' logic from front page . . default to include them

![image](https://cloud.githubusercontent.com/assets/2911176/6682342/880172c6-cccb-11e4-82fb-a8ef3318c594.png)

**Comment by kirstenalarsen** [comment]
test data kirsten.larsen as group manager and hubbedy hub

**Comment by mkllnk** [comment]
Done in branch groups-pages.

**Comment by mkllnk** [comment]
I was wondering if we should display profiles by default?
