### ISSUE TITLE
[API clean up] Remove .json from api/customers endpoint

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4283]
### What we should change and why (this is tech debt)
Current API is:
GET ​/customers.json

PUT ​/customers​/{customer_id}.json

We need to remove .json from the URL so that these are coherent with the rest of the API.

This should be a very simple task although the OFN client code needs to be updated.

### Context
This came up from the API documentation work #3001

### Impact and timeline
This is a simple change that will make the customers API consistent with the rest of the API.

**Comment by RachL** [comment]
@openfoodfoundation/developers do we still need this one in the context of API V1?

**Comment by mkllnk** [comment]
No, lets not touch the old API for a cleanup tasks.
