### ISSUE TITLE
New enterprise creation (from admin) needs red asterisks to signify required fields

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#429]
against name; email; address; suburb / postcode

![image](https://cloud.githubusercontent.com/assets/2911176/6682398/4ecfcfe2-cccc-11e4-8de8-2dba7ba32bba.png)

**Comment by livcg** [comment]
The form has the new field Owner which seems to be required, so I'll add an asterisk to its label also.

**Comment by myriamboure** [comment]
this is done so closing
![screenshot from 2018-03-04 19-52-32](https://user-images.githubusercontent.com/8135376/36949220-9d84ee32-1fe5-11e8-84f5-c9239a8f9d2a.png)
