### ISSUE TITLE
Error on orders page -  string translation?

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4302]
## Description

The order page is showing an error in the quantity field since the latest release.
![huron orders error](https://user-images.githubusercontent.com/13171778/65437501-e926c600-ddf1-11e9-9a4b-1b0f43482302.jpg)

## Expected Behavior

the field should report the quantity ordered

## Actual Behaviour

field has error as shown

## Steps to Reproduce

1.place an order 
2.open the order to edit,  see the error
3.
4.

## Context

NOTE -  I'm seeing this order in a hub I'm just setting up.  Its a food bank,  so the prices of the products are $0.    Is it possible that a 0 priced product is causing this error?    Or as the error suggests is this a missing translation string?

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using. 

Happening with the new 2.5.0  deployment today.

**Comment by luisramos0** [comment]
ok, I can replicate the issue...
it’s a space in the shipment state
 “on_hand” vs “on hand”

I have added the missing translation key in the PR.
