### ISSUE TITLE
Missing translation in shipment and payment state

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4304]
## Description

When a user ships an order, the translation is set to "none" because the translation for shipment state is missing
`= t(@order.shipment_state, scope: :shipment_states, default: [:missing, "none"])`

## Steps to Reproduce
1. Go to `/orders?q[s]=completed_at+desc`
2. Ship an order if none is shipped yet
3. Go to the edit order page

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/65441215-4fc7d600-de2a-11e9-947d-59fd56bd02da.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.5
* Browser name and version: Freifox 69
* Operating System and version (desktop or mobile): Both

**Comment by AndreiUngur** [comment]
Hi :wave: 
I have tackled this issue here: https://github.com/openfoodfoundation/openfoodnetwork/pull/4361 by using the relevant translations under `spree.(payment|shipment)_states`.

**Comment by RachL** [comment]
Hi @AndreiUngur welcome here and thank you so much for your contribution 😍 !

**Comment by AndreiUngur** [comment]
Sorry about that -- I'll have to let someone else tackle this one !

**Comment by chaserx** [comment]
I can take this.
