### ISSUE TITLE
Cannot select shipping method when creating an order as admin 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4307]
## Description

When creating an order as admin, the process no longer includes a step to select shipping method (apparently it used to, I don't know how to check this).

## Actual Behavior
I go to create an order. Select Distributor and Order Cycle

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/2432666c-453e-4e54-a27f-467b90d402ed) 

Add a product. Hit 'update and recalculate fees'

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/be34e682-f3a0-4fb6-ad41-5dfa111e8f12)

Select a Customer, hit update
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/7b8c3696-7a9e-444b-bcb2-09f28942ac81)

I then have no continue button, so I go to Adjustments. 

I have TWO shipping methods available to my shop and this order cycle (no tags etc). However the order has automatically given me a $0 shipping adjustment, rather than an option to choose. 

If I place the order through the shop, this section looks like this

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/2f71ff53-b185-4845-8661-e00a7ff2d188)

So to get the delivery shipping fee of $10 I have to edit this adjustment

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/7208bf35-084b-44d3-8184-246063cae017)

then I hit continue. which brings me here

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/3e311638-ced0-4e20-a611-4574ffe2a1d1)

PREVIOUSLY (prior to most recent release - I think), I could then hit continue HOWEVER now if I hit continue, it just takes me back to the Orders page and it has lost all information from my order

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/9eee0eaa-d562-46a0-aa4d-5a3aaa2e3e41)

I can try to get around this by NOT clicking continue the 2nd time and just selecting payments
[noting that if I look back at the order details, the shipping adjustment now has the correct $10 - bringing order total to $160]

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a688d887-fa1d-4951-b1ea-c11218030157)

Righto, so here I am capturing a $160 cash payment. 
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/432ba4c6-645c-4d68-a4db-e6579d503f10)

Which somehow then leaves me with a balance due of $150? It only captured the $10 adjustment?

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/792c4635-7320-4bf2-8412-781f49292bc6)

But still gives me the $160 as the amount I have remaining to capture 

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/c970a42f-f253-481e-8d6c-5c0b568210a3)

So I capture that, but now the system tells me I owe the customer $10. He went on to explain to me the steps he had to take to try and clean up that $10, and that he can't see in his reports which orders are pick-up or delivery anymore? 

But I was too irritated to take that information in. 

## Steps to Reproduce

As above

## Context
User trying to create orders from admin, when they have different costs associated with different shipping methods

## Severity

I am not sure how to assess severity of this. I don't know if the ability to set a shipping method while creating an order from admin is considered a critical or non-critical feature. Without reference to a v1, I am also unclear how much of this is v2 regression and how much is from latest release etc

I'm going to say s2-3. For this user, it is extremely painful - the workaround is pretty unworkable (I couldn't even follow it). OFN is meant to be saving people time not continually making it worse! 

## Possible Fix
I think perhaps the user guide hasn't been updated so we have a record of how it worked in V1. certainly it seems like corroborating evidence that there used to be a step where shipping method was selected 

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/8ba9a043-8eb9-406f-86ff-926d089b9b78)
https://guide.openfoodnetwork.org/advanced-features/orders/create-orders-manually

I would suggest we just restore this step if at all possible?

**Comment by sigmundpetersen** [comment]
This looks much the same as #4128 . They should be looked at together

**Comment by luisramos0** [comment]
hello, to select the shipping method you need to define customer details and then go back to order details where the shipping methods are available for selection.

**Comment by RachL** [comment]
Yes @luisramos0 is right @kirstenalarsen the workflow is pretty bad now, but this is the workaround you can give to the user. So I guess this is not an s2. But #4128 is on top of the pile. So we should get them done in the next round of s3 bugs.
Are you ok with this?

**Comment by kirstenalarsen** [comment]
yes, great. closing :)
