### ISSUE TITLE
Eager-load obvious associations used in OrdersAndFulfillmentsReport

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4308]
### What we should change and why (this is tech debt)

* Supplier Totals - variant, product, supplier
* Supplier Totals by Distributor - order, variant, product
* Distributor Totals by Supplier - order, variant, product
* Customer Totals - order, bill address, variant, product - **Added:** shipment

We are adding _n_ queries for **each line item** involved in the report. Eager-loading, we can significantly reduce the number of queries and the response time.

Query example:

![20190924152204-eager_load_order_and_distributor](https://user-images.githubusercontent.com/2243/65491402-8e6c9780-dee1-11e9-90b1-4b35f94585b4.png)

Stack trace:

![20190924153908-eager_load_order_stack_trace](https://user-images.githubusercontent.com/2243/65491461-a9d7a280-dee1-11e9-9b9b-3e0e8ed0b72c.png)

### Context

This was created in relation to the spike #4130 for the Orders and Fulfillments report.

### Impact and timeline

This is expected to significantly reduce the response time.

**Comment by sauloperez** [comment]
We should stop seeing traces like https://app.datadoghq.com/apm/trace/4523883766251097946?colorBy=service&env=production&graphType=flamegraph&routing_hint=1569838147022&shouldShowLegend=true&sort=time&spanID=3279947065713045773 in Datadog.
