### ISSUE TITLE
N+1 for shipment, selected shipping rate, and shipping method in Customer Totals report

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4314]
### What we should change and why (this is tech debt)

This is related to #4310. Any work for this should be coordinated with #4213 

The shipment, shipping rate, and shipping method records should be fetched in batch. At the moment, there are 2 queries (aside from query to be removed in #4310) for each non-group row in the Customer Totals report.

### Context

This was created in relation to the spike #4130 for the Orders and Fulfillments report.

### Impact and timeline

This is expected to have some effect on the response time, and it will significantly reduce the number of SQL queries.

**Comment by Matt-Yorkley** [comment]
Orders and Fulfilment reports are the worst thing performance-wise, and Customer Totals is by far the worst of it's 4 sub-reports. 

Can we keep this and #4313 open and move them to the backlog? I think closing them and forgetting is a bad idea.
