### ISSUE TITLE
Pre-fill Orders and Fulfillments report date filters with start and end dates

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4315]
### What we should change and why (this is tech debt)

Mistakenly running the report for all-time when the user needs data only for a shorter period would unnecessarily hog the Unicorn worker for _n_ more seconds/minutes. This small UI change is a small effort that could avoid that.

Pre-fill the start and end date fields with reasonable values, to encourage the user to set the period they need so they don't generate a report for all-time unless they actually need that.

### Context

This was created in relation to the spike #4130 for the Orders and Fulfillments report.

### Impact and timeline

This would reduce unnecessary spikes in response time, and improve user experience too.

**Comment by kristinalim** [comment]
@lin-d-hop I saw that you suggested a change in date range in #4184. Do you know what a reasonable date range for the Orders and Fulfillment report is? The PR for this, PR #4327, uses:

* Beginning of day, 1 year ago
* Beginning of day, today

**Comment by lin-d-hop** [comment]
Beginning of day 1 month ago is fine.
However beginning of day today is not. This means that if I place an order at 10am as an admin (as an addition or correction) then run the report at 2pm to do my deliveries the order I created is not there (unless I change the date range). Previous behaviour was that today's orders are in the reoprt. So I would suggest:

- Start Date - Beginning of day 1 month ago.
- End date - Midnight tonight or beginning of day tomorrow. I would suggest this date is **slightly in the future** to avoid missing recent orders made by admins.

**Comment by kristinalim** [comment]
@sauloperez This is the thread where @lin-d-hop recommended to change it from 1 month ago (from my previous value of 1 year ago).

@lin-d-hop For context, @sauloperez prefers to be more conservative:

> I'd be conservative and limit it to 1 week only. I haven't checked the numbers but a month can surely cause :boom: in many cases which would lead to a poor experience for the user.

What do both of you think?

**Comment by kristinalim** [comment]
@lin-d-hop @sauloperez Then, would 2 weeks perhaps be better?

**Comment by lin-d-hop** [comment]
Is one month too long? To me this is perfect.

**Comment by sauloperez** [comment]
let's iterate then and see but we should find a proper way to track nb. of crashes vs total requests. Would you mind setting that up in Datadog @kristinalim ? I can lend you a hand.

**Comment by kristinalim** [comment]
@sauloperez Is this what you had in mind? :slightly_smiling_face: 

* Chart 1: Total Requests vs HTTP 502 (Bad Gateway) + HTTP 504 (Gateway Timeout)
* Chart 2: Max Response Time vs Mean Response Time vs Median Response Time

![20191016202725-orders_and_fulfillment_report_monitoring](https://user-images.githubusercontent.com/2243/66919188-722cc800-f053-11e9-9f97-0d571b477c07.png)

I like it already! If you're happy with that, I will clone for the shopfront and the edit OC problem endpoints.

**Comment by kristinalim** [comment]
That is in the "Production - Rails Action Monitoring" Datadog dashboard, BTW.

**Comment by sauloperez** [comment]
Awesome! you rock :metal: @kristinalim ! Let's keep an eye on it once we ship the filters change :+1:
