### ISSUE TITLE
Add DB index for order state

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4317]
### What we should change and why (this is tech debt)

This is not yet included in any index, even composite ones. Needs to be investigated if this will help.

We filter for order state in multiple reports.

### Context

This was created in relation to the spike #4130 for the Orders and Fulfillments report.

### Impact and timeline

This is expected to have minor or significant impact on different reports.

**Comment by sauloperez** [comment]
I'm not entirely sure about that. For an index to be effective needs to have a large cardinality effectively splitting the column values into many buckets thus making it lightning fast to fetch them. This is not the case if we compare state vs an id of some sort.

Besides, I doubt we query the order state alone so it'd be much cost-effective to index by whatever other columns we might be querying. But even so, appending the order state in such index might not have a noticeable impact.

**Comment by Matt-Yorkley** [comment]
I've had a look at this, and used some searching in Datadog traces. I think adding an index on state will not bring much benefit, and obviously will have a cost.

**Comment by Matt-Yorkley** [comment]
Search results for traces with `spree_orders.state`:

![order_state](https://user-images.githubusercontent.com/9029026/68077261-9957f900-fdb8-11e9-8761-b93ccf0e1ac3.png)

**Comment by Matt-Yorkley** [comment]
Can we close this?

**Comment by sauloperez** [comment]
What do you think about my comment above? I think that's what's going to bring noticeable improvement but I haven't EXPLAIN ANALYZEd anything yet. Definitely, `state` alone won't do anything.

**Comment by Matt-Yorkley** [comment]
We already have a compound index on the orders table with `completed_at` as the first item in the index. 

I looked through Datadog to try to find places where `state` was used, and where an index for `completed_at, state` would be useful, but I couldn't really find anything to support that.

**Comment by sauloperez** [comment]
If there's an index with `completed_at` there's no low-hanging-fruit here. I would just close this.
