### ISSUE TITLE
Add DB index for order_cycle_id and distributor_id in orders table

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4318]
### What we should change and why (this is tech debt)

These are not yet included in any index, even composite ones.

There are queries like these in `Permissions#visible_orders`, which is alarming if you have thousands or millions of order records:

![20190925171943-query_permissions](https://user-images.githubusercontent.com/2243/65587663-cdb9e780-dfb8-11e9-83f5-e5c6d8aca91b.png)

### Context

This was created in relation to the spike #4130 for the Orders and Fulfillments report.

### Impact and timeline

This is expected to have minor or significant impact on different actions, not just reports, especially when the user is a superadmin.

**Comment by sauloperez** [comment]
Where did that `SELECT "order_cycles.id" FROM "order_cycles"` query come from :cold_sweat: it's really concerning...

**Comment by sauloperez** [comment]
As part of this issue, I would also investigate whether these two queries can be combined in a join so we can leverage the composite index you propose @kristinalim . I bet we can fetch both the orders that match the distributors but also the ones that match the order cycles in a single shot.

**Comment by Matt-Yorkley** [comment]
Looking in Datadog and our schema, I think we might benefit from a `supplier_id` index on the `spree_products` table as well. It seems to be used a lot (with high latency), and it's missing.

**Comment by sauloperez** [comment]
If you can prove that with data :+1: As a rule of thumb though, IMO it's best if we find composite indexes that can be used in multiple scenarios but also bring further perf. improvements, at the expense of RAM + disk of course.
