### ISSUE TITLE
Eager-load associations for Variant#options_text used in Orders and Fulfillment report

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4319]
### What we should change and why (this is tech debt)

I separated this from #4308, because I started looking into this before and it wasn't simple.

We are using `options_text` is used for `Spree::Variant#full_name` used in different parts of the code.

### Context

This was created in relation to the spike #4130 for the Orders and Fulfillments report.

### Impact and timeline

This is expected to have observable impact on the Orders and Fulfillment report. The same strategy could be used in other parts of the code that call `Spree::Variant#full_name` for multiple variants, such as AFAIK the edit OC page.

**Comment by lin-d-hop** [comment]
closing as not completing in this round of performance improvements
