### ISSUE TITLE
Add fields to variant drop-down when adding variants to existing order

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#432]
When a User is adding variants to an existing order (via Orders, edit Order)

they need more information than is currently available about the variant.
1. Include Producer / Supplier name
2. Include variant label (where different from the product / variant name)
3. [advanced - can split into different issue if necessary] check whether this is checking against variant overrides 

![image](https://cloud.githubusercontent.com/assets/2911176/6683291/652bba24-ccd8-11e4-82b8-0b719c4ea317.png)

**Comment by kirstenalarsen** [comment]
scheduled, is part of http://community.openfoodnetwork.org/t/single-order-management-wishlist/85

**Comment by mkllnk** [comment]
Ready in branch single-order-patches.
