### ISSUE TITLE
Subscription that uses weight calculator cannot be saved or unpaused

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4322]
## Description

Unpausing a subscription that uses a weight calculator does not succeed https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5d8b408fb208330019de81bc

## Steps to Reproduce

Picking one shop:
1. Enable subscriptions for the shop. Go to the Settings page for the enterprise, and enabling Shop Preferences > Subscriptions.
2. Create a weight-based shipping fee for the shop. Go to Enterprises > Shipping Methods for the enterprise, and add a shipping method that uses weight calculator. Set the shipping fee after creating the shipping method, e.g. 5.
3. Update one product in the shop to use volume, e.g. 3L.
4. Edit one variant in Step 3 and set a weight, e.g. 2.2kg.
5. Create a new subscription that uses the shipping method, and add the variant. This works. :heavy_check_mark: 
6. Wait for the orders under the subscription in Subscriptions to no longer show "Pending". :heavy_check_mark: 
6. Try to edit the subscription date. It is not saved but there is no warning. :warning: 
7. Try to pause the subscription. It works. :heavy_check_mark: 
8. Try to unpause the subscription. It does not work. :warning: 

## Context

See error on Bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5d8b408fb208330019de81bc?event_id=5d8b408f0050355630460000&i=sk&m=nw

## Severity

bug-s3: a feature is broken but there is a workaround

**Comment by luisramos0** [comment]
question from @RachL on slack: what is the workaround?

**Comment by lin-d-hop** [comment]
Is this specifically linked to the Weight Calculator?
I have a subscription that does not use the Weight Calculator that does not unpause.

Is the workaround to remove and recreate the subscription?

**Comment by luisramos0** [comment]
yes, this is specific to Weight Calculator

**Comment by luisramos0** [comment]
better create another issue maybe there's another bugsnag entry for your problem.

**Comment by sauloperez** [comment]
OMG... I was right now writing an issue about this :see_no_evil:

**Comment by sauloperez** [comment]
IMO this particular bug should be prioritized so that we cover this case with our automated test suite as explained in https://github.com/openfoodfoundation/openfoodnetwork/issues/4322#issuecomment-546385505 while fixing the bug. Then, we'll have subs fully automated and testers won't need to take it into account in release testing. I'm sure @lin-d-hop @RachL and @filipefurtad0 we'll appreciate it.

**Comment by RachL** [comment]
@sauloperez FYI aside from this one, there is another bug on subs that will need an automated test as well and that is in dev ready: https://github.com/openfoodfoundation/openfoodnetwork/issues/4410

**Comment by sauloperez** [comment]
Ouch, thanks for the heads-up

**Comment by luisramos0** [comment]
closed by #4539
