### ISSUE TITLE
Manager and super admin not able to select outgoing products for a particular shop

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4329]
## Description

"Au local" is a hub enterprise on French production. ID : 922 

They manage directly all there producers.

When they create an order cycle, then cannot select outgoing products.

All products are on demand.

All permissions seem in place...

## Steps to Reproduce

1. Log in as a manager of Au local (ID 922 )
2. Try to create an OC with outgoing products

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/0f2ceb42-b546-478f-a5db-5936ee3ea52f)

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
* Version used: 2.5
* Browser name and version: Firefox 69
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
![Screenshot 2019-09-26 at 16 57 27](https://user-images.githubusercontent.com/1640378/65704609-bfce9a00-e07e-11e9-92a3-5523d499cde0.png)

Enterprise is configured to only sell from Inventory, because no inventory exists, no products can be added to outgoing exchanges.

**Comment by RachL** [comment]
thank you <3 I feeeel soooo duuuuummmmm
