### ISSUE TITLE
Release 2.5.1

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4337]
Draft is here: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-5d1d3181d278e91de9c0

Target commit is here: https://github.com/openfoodfoundation/openfoodnetwork/commit/d162e8c0872ac40d050fd3201b7983ccc5f49e5b

Build to deploy is here: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/879

- [x] Draft
- [x] Test
- [x] Release
- [x] Deploy

**Comment by lin-d-hop** [comment]
Alright team. Thanks for all of your awesomeness!
Tested and all clear:
https://docs.google.com/document/d/1j1fzbMokjBlgVl_d2i_5U5MtEZTyjr0AkRZpzEFJNTE/edit#
