### ISSUE TITLE
Product list: enable action button to be opened in a new tab

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4338]
## Description
Currently you cannot open the edit product button in a new tab.

This means that when you have to update several products (for example updating the tax category), you need to open the edit page and go back to the full list of products before you can select another product to edit. 
If you had used filters, all filters are removed when reloading the page. While we are not tackling this behavior in this issue, it means it is difficult to see which product you have already edited vs. which product you didn't.
When opening all of them in several new tabs, you can more easily manage them.

## Steps to Reproduce
1. Go to `/admin/products`
2. Filter the results for one particular producer
3. Try to edit a product using the following icon: 
![image](https://user-images.githubusercontent.com/6525576/65898644-50281a00-e3b2-11e9-9657-d41445c5fb34.png)
4. See that you cannot open the target page in a new tab
5. Open the edit page, then go back to `/admin/products`. Notice all your filter are lost (which is let's say for now a correct behavior)

## Your Environment
* Version used: v2.5
* Browser name and version: All browser and version
* Operating System and version (desktop or mobile): Desktop

**Comment by JacksonBates** [comment]
Hi - new to this project.

I've got the dev environment set up and replicated the issue - I'd like to have a crack at the fix.

**Comment by RachL** [comment]
Hi @JacksonBates and welcome! I see you already have proposed a PR, nice :) If you have any particular question, don't hesitate to join the community on our [Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/enQtMzU2Mjk5MDc2MjA5LTM4ZTAzZjIwNzIxMmU5ODFiNWY1MTU2ZWUyNzQwNjdjNTY0N2VhY2UwOGU4ZmVjNzYyZDU2NjY3NzZkZmQwYjk)

**Comment by JacksonBates** [comment]
Thanks @RachL, that slack link doesn't work for me I'm afraid - it claims to be no longer active.

**Comment by sigmundpetersen** [comment]
Hey @JacksonBates try [this](https://join.slack.com/t/openfoodnetwork/shared_invite/enQtNzY3NDEwNzM2MDM0LWFmNGRhNDUwYzNmNWNkYmFkMzgxNDg1OTg1ODNjNWY4Y2FhNDIwNmE4ZWI0OThiMGNmZjFkODczNGZiYTJmNWI)

**Comment by JacksonBates** [comment]
Thanks @sigmundpetersen, that worked
