### ISSUE TITLE
Angularising Single Order Index Page

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#435]
Revamp the single order index page to use angular...

**Comment by kirstenalarsen** [comment]
see discussion at http://community.openfoodnetwork.org/t/generating-invoices-from-ofn/108

**Comment by lin-d-hop** [comment]
YAY @oeoeaio is back!!

Looking forward to working on this but have felt totally stuck without @oeoeaio's input. Whoooop!

**Comment by kirstenalarsen** [comment]
hope @oeoeaio is as excited to be back as we all are to have him - you should see the day he’s had but I think he’s going to join us for Skype tonight so perhaps he can tell you himself ;)

**Comment by NickWeir63** [comment]
In our skype call today @kirstenalarsen asked me to move this to the v1.4 milestone and she is "putting it on a card"

**Comment by lin-d-hop** [comment]
#gitcull2017
