### ISSUE TITLE
release v2.5.2 Bear

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4357]
draft:
https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-24dd7384f989c05355ca

target commit:
https://github.com/openfoodfoundation/openfoodnetwork/commit/5077b0e625542cbbec3ee85ffb4b7503912fe98e

build:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/905

- [x] - draft
- [x] - test
- [x] - publish
- [x] - deploy

**Comment by RachL** [comment]
@luisramos0 I believe this is the first time we have a non-eatable release name :D

Anyway, everything looks good for new enterprises, but when I've tried to shop at [Mary's hub on Katuma](https://staging.katuma.org/mary-s-online-shop/shop), I hit the snail with this particular error: https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1570553452060700 Wasn't this fixed previously? I can't find the issue again in the bug backlog.

Testing notes: https://docs.google.com/document/d/1lQiDlmSUMqF7Z4DTNoP12psjrDBBA_mm1mmpUMbO_zM/edit#

**Comment by luisramos0** [comment]
staging katuma DB looks like a mine field for product deletions :-), most products are deleted...
what account did you use Rachel so I can check the products in the cart.

**Comment by luisramos0** [comment]
I think this PR should have solved that as the problem comes from fetching a nil price of a variant:
https://github.com/openfoodfoundation/openfoodnetwork/pull/4242/files

There are no deleted prices for non deleted variants in the DB.
`select spree_variants.deleted_at, spree_prices.deleted_at from spree_variants left outer join spree_prices on (spree_prices.variant_id = spree_variants.id) where spree_variants.deleted_at is null;`

**Comment by RachL** [comment]
@luisramos0 spree@example.com but you will now get a direct snail when loggin in with this account.

I should have staged 4242 on Katuma :(

**Comment by RachL** [comment]
@luisramos0 I've created a new issue to tackle this problem:

https://github.com/openfoodfoundation/openfoodnetwork/issues/4369

I suspect this already in production, so I guess we can move forward with the release.

**Comment by luisramos0** [comment]
ok, lets do it.

**Comment by luisramos0** [comment]
released now, to be deployed tomorrow.
