### ISSUE TITLE
Groups page not showing when hubs are open, and producers are missing from fat view

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#437]
![image](https://cloud.githubusercontent.com/assets/2911176/6745088/1a0b250e-cf06-11e4-88f4-c312888a1753.png)

**Comment by mkllnk** [comment]
These two problems were caused by missing data on the page.

I've updated the group-pages branch which now waits to be tested at some point. :-)
