### ISSUE TITLE
Don't reload Orders page after payment is captured

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4377]
## Description
- As an enterprise user
- On page Orders (https://openfoodnetwork.org.au/admin/orders)
- I want to be able to quickly capture payment on multiple orders, including where I have selected them according to filters  
see discussion at https://community.openfoodnetwork.org/t/enable-quick-capture-of-payments-for-a-batch-of-orders/1478/9

## Acceptance Criteria & Tests

Enterprise user should be able to set filters on the orders page to select a group of orders, and then 'capture payments' on these without losing their filter selection and being returned to home orders page each time

Create multiple orders with cash payments i.e. order is complete but not paid. Orders that are complete but not paid have a small tick at the right hand side which allows the payment to be captured

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/65300e2d-95d2-4e13-8551-687f5e49d81b)

Set filters to select the orders you are looking for e.g. all orders from a particular user, order cycle or distributor etc

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/ce412702-338f-4e05-b427-e35c7fa8d098)

Hit capture payment button on the first order
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/9b0c2a8f-2158-4a60-83c3-9971ea8cda98)

Page SHOULD NOT reload to Orders page with no filters selected. 

The capture payment action should take place while keeping the same selection of filters on the page. So the page should then look like this

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/43cd1548-d778-48e9-81ae-bb5de03ad2c3)

[This should NOT happen]
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/de778df8-5d58-4622-b094-13518793fd72)

**Comment by kirstenalarsen** [comment]
NB. If implementation of this proves problematic / tricky, the other option is to use the checkboxes to select multiple orders, and change 'Print Invoices' to an Actions dropdown, with two options: 'Print Invoices' and 'Capture Payments'

**Comment by Matt-Yorkley** [comment]
I'm taking a look at this now. The logic and UX is identical for both the `capture` and `ship` buttons. I think it makes sense to update both at the same time here.

**Comment by Matt-Yorkley** [comment]
Ok, this is going to need some UX work as well. Currently when we refresh the page we can give feedback via the green/red flash messages in the header. If we move to asynchronous requests, we'll need to introduce a new way of delivering success/error feedback on this page.

@RachL ?

**Comment by RachL** [comment]
@Matt-Yorkley when you capture a payment the button changes to a ship button, so it should give users a hint. But maybe we can play more with the button? Turn it green or red if there is an error?
Although I'm not sure we see the button currently in case of an error...we just have no button at all...
Can a message be displayed even though we don't reload the page?

**Comment by Matt-Yorkley** [comment]
I don't think we can reuse the message in the header. I'll take a look tomorrow.

In most cases it should save correctly. I don't think an error will be common. I'm thinking of trying a small spinning icon next to the button (floating to the right) when loading, then a small green tick or red cross that fades after a couple of seconds..?
