### ISSUE TITLE
Email problem in FR prod

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4382]
## Description

I have a user that didn't receive his confirmation email.

Lynne suggested the good idea to put an email in copy of the email sent, in order for me to find this particular confirmation email and forward it to the user.

This ended up with email problems:

```Unhandled error```
```Net::SMTPFatalError: 550 Unauthenticated senders not allowed```
```Location```
```app/controllers/user_confirmations_controller.rb:13 - create```

Sigmund suggested DJ should maybe be restarted?

## Steps to Reproduce
Here are all the steps I did:
1. Loged in as super admin
2. Went to `/admin/mail_method` There is a field that says "send a copy of all email to". There I've put my email. Saved. 
3. Got back to the user profile and tried to resend the confirmation email. Failed. 
4. Removed my email, retried, failed again.

## Severity
bug-s2: a non-critical feature is broken, no workaround

* Version used: v2.5.2
* Browser name and version: Firefox 69
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
have you tried to set the correct sendgrid credentials when you change something in the form? maybe you need to always enter the credentials when updating this form.

**Comment by sigmundpetersen** [comment]
A password/username update also requires restarting Delayed_Job https://github.com/openfoodfoundation/ofn-install/wiki/Sending-emails-from-OFN#configuring-a-mail-method-automatically

**Comment by luisramos0** [comment]
ok, plan:
- set the credentials correctly on the form and save.
- see if this solves problem  🤞 
- if not, restart delayed_job
- see if this solves problem  🤞
- if not, rethink :-)

**Comment by RachL** [comment]
@luisramos0 So I've just retried with the password and now I could send the email. I'm waiting to see if I received the email in copy.

Shall we open something to add a message on this page? It's really not obvious that you need to delete the password and copy/paste it again....

**Comment by RachL** [comment]
Got the email, closing! Thank you all!!!

![](https://media.giphy.com/media/3krrjoL0vHRaWqwU3k/giphy.gif)

**Comment by luisramos0** [comment]
ehehe, nice.
yes, we should create an issue for that "be able to update mail method without touching password field"
