### ISSUE TITLE
Product shows but unavailable to purchase in Hub Shop front

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#4383]
## Description

Cocoa Nibs and Dried Mango supplied to Cambridge Food Hub by Storimarket are both in stock in the Cambridge Food Hub inventory, both added to the order cycle (in coming and outgoing parts) and both appear on their shop front without their variants visible nor the option which allows a customer to add the items to their baskets.

## Expected Behavior

Products are in stock and so customer should be able to add to basket. Products not in stock should not appear at all on shop front.

## Actual Behaviour

Products are in stock. They appear on the shop front but there is no option which allows the customer to purchase them.

## Steps to Reproduce

1. Checked product inventory
2. Checked Order cycle
3. Checked tags and tag rules
4. 

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/45104035/67111743-8dbbde00-f1cd-11e9-8247-c1c03072e816.png)
![image](https://user-images.githubusercontent.com/45104035/67111760-96acaf80-f1cd-11e9-95e0-6bdbf31cdeef.png)
![image](https://user-images.githubusercontent.com/45104035/67111834-c22f9a00-f1cd-11e9-8420-57ca55fdd817.png)

## Severity

Labeling this as S1 as Food hub can't function without its products being available for customers to purchase.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Discourse: Products not showing up on shopfront](https://trello.com/c/rryl9Cbn/585-discourse-products-not-showing-up-on-shopfront)

**Comment by lbwright22** [comment]
work around sorted by changing stock level of items to fixed numbers and then changing the inventory settings to inherit stock levels from producer rather than override.

**Comment by lin-d-hop** [comment]
Workaround drop issues to s3 (unfortunately).... and fingers crossed this disappears when the product cache is out :-)

**Comment by lbwright22** [comment]
Post release of 2.6.1 this issue has been resolved.

Put user settings back to unlimited supply from producer with hub having override on stock levels in their inventory.
Products and variants display correctly in shop front.

Closing issue.
