### ISSUE TITLE
Sample data should include Orders

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4388]
### What we should change and why (this is tech debt)
We should add orders to sample data so that a freshly loaded dev/test environment already includes some orders that can be used for testing.

### Context
The questions was raised here:
https://github.com/openfoodfoundation/openfoodnetwork/issues/4378
and is related to this thread:
https://community.openfoodnetwork.org/t/seed-data-development-provisioning-deployment/910/24

btw, the names of the sample enterprises can be changed according to what was agreed in the thread.

### Impact and timeline
This is a super easy task and will make our sample data a lot better.

### Possible implementation
We need to create OrderFactory under lib/tasks/sample_data and link it in lib/tasks/sample_data.rake

**Comment by daningenthron** [comment]
Hi @luisramos0, I'd like to give this a shot. What sort of states would you like represented, maybe based on the core Spree factories? Any of the cases set up at spec/factories/order_factory.rb?

**Comment by luisramos0** [comment]
Hello @daningenthron great!
I recommend we start simple with a few orders:
- incomplete order (cart)
- completed order with pending payment
- completed order with captured payment
- completed order with a delivery ship method
- completed order with a collect ship method
- completed order with some form of adjustments

@RachL does this make sense? what do you think? please let us know how would you want to see this done.

**Comment by RachL** [comment]
Yes it does make sense and I guess it is a good way to start, we can always improve it after?

**Comment by jeduardo824** [comment]
I will check this next week!
