### ISSUE TITLE
Missing translation on the date range selector, in Orders and Fulfillment

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#4412]
## Description

Missing translation:
"END" in not translated in the date range selector, in Orders and Fulfillment (pic below).

## Expected Behavior
It should appear translated to the chosen user language.

## Actual Behaviour
END is shown, regardless of the choice of language.

## Steps to Reproduce

1. Login as an Enterprise/Hub.
2. Select a language other then English
3. Go to admin/reports/orders_and_fulfillment
4. The date range selector should show END, for the upper date limit.

## Animated Gif/Screenshot
![Screenshot at 2019-10-29 10-39-58.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/73ebbab5-3c57-45f0-9b93-a4aac9f9167f)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v2.6.0
* Browser name and version: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 18.04 Desktop

**Comment by RachL** [comment]
Awesome @filipefurtad0 ! I've just unassigned you because you won't be working on this ;)

**Comment by filipefurtad0** [comment]
Ahh true :-) Just testing, later on perhaps!

**Comment by gkpacker** [comment]
Can i take this one?

**Comment by gkpacker** [comment]
Tried to run the setup here, but I have problems with libv8 on my mac, so i can't take it, sorry
