### ISSUE TITLE
Partial PayPal refunds unsupported by platform but option button present

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#4416]
## Description

Hub or shop amends a customers order to remove an item that is not in stock. Customer has paid using PayPal. Hence they are owed credit.
User (hub or shop manager) goes to credit owed screen. Blue button 'Refund' is available.
Selecting the blue button brings up 'Authorization failure' screen.
PayPal partial refunds are not supported by the platform (only Stripe partial refunds are automated).
Hence the blue button 'refund' is misleading to hub and shop managers and implies functionality which doesn't exist.

## Expected Behavior

If PayPal partial refunds are not possible on the platform then the blue 'refund' button should not be visible for the Paypal credit owing screen.

## Actual Behaviour

On PayPal credit owing screen there is an option for 'refund' which is not supported.

## Steps to Reproduce

As description

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/45104035/67844902-772f5400-faf6-11e9-8c6e-4b17c07dc072.png)
![image](https://user-images.githubusercontent.com/45104035/67844931-82827f80-faf6-11e9-814d-22b802d095b4.png)

## Severity

S5
## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Paper cut candidate.

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Paypal partial refund - The Tree](https://trello.com/c/30Ccygua/593-paypal-partial-refund-the-tree)

**Comment by kirstenalarsen** [comment]
I am pretty sure this used to work. I don't know how others feel, but I think a small investigation into how hard to get it working again might be worthwhile? I don't think we are at the point where we're 'stopping' integration with paypal, and it might not be a huge fix? Would be keen for anyone picking up this issue to actually see if it might be fixable - obviously makes it a harder issue

NB. Stripe refunds and partial refunds work

**Comment by Erioldoesdesign** [comment]
Would love to see if as Kirsten says above, there is a way to get paypal refunds working.

If not and this papercut to remove the button goes ahead, I would extend the scope by a small amount and offer some text in the UI to guide the enterprise-user in how they can proceed to refund. Which I assume, is contact the customer via email and arrange a manual refund of some kind (either via paypal or bank transfer or whatever) but giving that 'next step' is good UX if we remove the refund button.

**Comment by Matt-Yorkley** [comment]
I think hiding the refund button if it's a Paypal payment would be good to begin with, then maybe move investigations around the feasibility of Paypal refunds to a separate issue.
