### ISSUE TITLE
Release v2.6.1 Melon

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4420]
Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-c316d4f819329855c019

Target commit: 61c581ae52910ea337d17e200f8f641a1ec99c9b

Build: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/955

- [x] - Draft
- [x] - Test
- [x] - Publish
- [ ] - Deploy

**Comment by filipefurtad0** [comment]
Hi @kristinalim,

I think the release is good to go :tada:  test notes below.
https://docs.google.com/document/d/1aU2uowI4_aTHhahotqZhFh0-V1dD54uOpJxC7j50QGI/edit#

Not too sure how much testing would still be necessary. To me, the less obvious features are still Subscriptions and Inventory but I feel I have tested the basic features.

**Comment by RachL** [comment]
Hey @filipefurtad0 don't worry about inventory, it is already well covered by automated tests.

Concerning subs I had a go at testing them with Stripe and aside the know issue around editing, this is working correctly :tada: 

We can chat on Slack on how to test with Stripe but the key is that the user linked to the sub needs to have a saved credit card that allows the hub to charge. This is done in the user profile:

![image](https://user-images.githubusercontent.com/6525576/68151842-c33d2700-ff42-11e9-83ad-cfdcb4d17540.png)

Saving a card is linked to stripe. This is why it has failed in UK staging for you I guess.
Anyway congrats on you first release test!!

![Alt](https://media.giphy.com/media/g9582DNuQppxC/giphy.gif)

**Comment by filipefurtad0** [comment]
Hi @RachL,

I'll give Subs a try then, previously adding a card to the user - that makes sense :-)

I got a bit concerned about this not working on staging-UK, since adding a credit card is perhaps an important feature. So, good to know it's just a staging issue and that it works fine on FR, too.

Thank you, it was my pleasure! :-D :tada:

**Comment by kristinalim** [comment]
Thank you very much, @filipefurtad0 and @RachL! :grinning: :heart: Publishing this now!

**Comment by RachL** [comment]
Thank you Kristina !! Matt has deployed, so I'm closing
