### ISSUE TITLE
Add supplier_id index to spree_products table

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4424]
### What we should change and why (this is tech debt)

We're missing a `supplier_id` index on the `spree_products` table. This index is commonly used and will result in sequential scans. It's a foreign key, and has high cardinality.

### Context

Looking into potential useful indexes for performance.

Example traces:

https://app.datadoghq.com/apm/resource/rails-postgres/postgres.query/3e58832d71271611?end=1572733957676&env=production&index=apm-search&paused=false&start=1570141957676
https://app.datadoghq.com/apm/resource/rails-postgres/postgres.query/79a87739d97ae77f?end=1572729769909&env=production&index=apm-search&paused=false&start=1570137769909
https://app.datadoghq.com/apm/resource/rails-postgres/postgres.query/8478cbff71034945?end=1572729762684&env=production&index=apm-search&paused=false&start=1570137762684

**Comment by luisramos0** [comment]
Moving this to tech debt backlog to remove the performance column in the pipe. This is probably the top priority in terms of performance issues right now. This would have a very good impact I am sure.
