### ISSUE TITLE
Default selection of Hub/Shop on creation of payment / shipping method when there is only one option

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4428]
## What is the problem we are solving 
When creating a payment or shipping method, you have to select which hub/hubs that method should be attached to

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/82aaf785-3327-4436-86ed-b77051f32d6c)

It is extremely easy to miss and then the user gets lots of red

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/042fa037-ade8-4d66-96ec-979623dce162)

## Success factors = expected outcome 
If there is only one option for selection of Hub / Shop, that should be selected by default, then they don't have to think about it

**Comment by RachL** [comment]
Oh yes pleaaase!!! Can this be a good first issue? ping @openfoodfoundation/developers

**Comment by cyrillefr** [comment]
Hello, I would like to work on this one.

**Comment by luisramos0** [comment]
Great, welcome Cyrille! Join us on slack!

this is at:
- app/views/spree/admin/payment_methods/edit.html.haml
- app/views/spree/admin/shipping_methods/edit.html.haml

both use:
app/views/spree/admin/shared/_hubs_sidebar.html.haml
