### ISSUE TITLE
'Enter' key activates search on Products (and Orders?) page 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4437]
## What is the problem we are solving 

When repeatedly using search box to find and deal with products in Products page, it is really irritating to have to actually hit 'filter results' before anything happens. It would be great if hitting enter, which I (and I suspect many others) do instinctively, activated the search.

Pretty standard to type something in a search box and have 'enter' then do the search?

I suspect there are issues with consistency of UX across the admin back-end, but I wonder if this is one small thing that might be good?

## Success factors = expected outcome 
when I type something in the search box on the Products page, I can hit 'enter' and the search runs
when I type something in a search box on the Orders page, I can hit 'enter' and the search runs

**Comment by RachL** [comment]
@kirstenalarsen can you use the story template rather than the feature template when you create something like this? When it is small it is sometimes also something we can tag as good first issue. So it is important to have key elements such as the user type, URL, maybe even screenshots?

**Comment by kirstenalarsen** [comment]
Can we extend this to do the same thing on the Orders page and still be a papercut? @luisramos0 @sauloperez @mkllnk

**Comment by mkllnk** [comment]
Yes, I believe that this is papercut size.

**Comment by rmklaus12** [comment]
Looking for my first contribution and would like more info on this as I cannot recreate the issue (nor find a specific Products page) on the live site.

**Comment by luisramos0** [comment]
Hi @rmklaus12 you need to setup your local environment and load sample data
bundle exec rake ofn:sample_data

Start the server:
bundle exec rails s

After this you can go to 0.0.0.0:3000/admin/products where you will see the page.

**Comment by kirstenalarsen** [comment]
Hi @rmklaus12 - these pages are in the admin interface, so you will need to create yourself an enterprise to see them. Please don't do so on the production server - either on your local environment or a staging server (i.e. staging.openfoodnetwork.org.au) login and /register to create an enterprise. Then you can to to the admin dashboard openfoodnetwork.org.au/admin and you will be able to see the products and orders pages. Probably worth setting up a shop with a few producers and orders so you have some data to play with (and understand a bit more about what's going on). User guide here - https://guide.openfoodnetwork.org/quick-start-guides/producer-shop-quick-setup-guide

Alternatively create a login on staging and I'll give you access to an existing test hub

Devs is there a better way than this to get useful test data? This was quite a 'non-dev' response! @luisramos0 @Matt-Yorkley @pacodelaluna @filipefurtad0

**Comment by kirstenalarsen** [comment]
ha @luisramos0 was providing a much more sensible dev response while i was typing :)

ignore me

**Comment by rmklaus12** [comment]
All good! I did get the sample data and can access it, but I’m not able to
create an enterprise. The alert says that fields are blank which is not the
case. So far I’ve drilled down and the error is occurring in the api
enterprise controller#create method. Not too surprising there, will do more
digging over the
weekend.

I appreciate your response as well Kirsten :)

**Comment by luisramos0** [comment]
Please share error details here or in #dev so we can help.

If you sample data you dont need to create an enterprise to fix this issue, do you know that? sample data comes with 4 enterprises.

**Comment by kirstenalarsen** [comment]
Hi @rmklaus12 - how are you going with this?

**Comment by rmklaus12** [comment]
Hi @kirstenalarsen. I did not dig into this as much as I'd hoped. My local environment is up and running and I've picked up another issue to work on. I can look into this again this week.

**Comment by rmklaus12** [comment]
@kirstenalarsen - well not sure what changed, but I was able to create an enterprise locally. So, all good!

**Comment by kirstenalarsen** [comment]
hi @rmklaus12 can you confirm that you are not working on this and someone else can pick it up? Thanks :)

**Comment by rmklaus12** [comment]
I am not :)
