### ISSUE TITLE
Release v2.6.2 Magrana

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4438]
Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-da2219c01a49458f1225

Target commit: https://github.com/openfoodfoundation/openfoodnetwork/commit/a6ba9563558c13c65677ef0d0008bca9bfb36b8c

Build: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/965

- [x] Draft
- [x] Test
- [x] Publish
- [x] Deploy

**Comment by RachL** [comment]
I'm almost done, only stripe missing 

https://docs.google.com/document/d/1Sz5LernQSG4G7W5uHpBTaN15wQekbRUwUuc0Z0L9Psc/edit#

**Comment by RachL** [comment]
OK so paying with stripe still works, but I still didn't find a way to connect a fake stripe account like we did with yours @sauloperez. I don't seem to find how to give fake bank account info.
I suggest we don't block the release because of that. And figure something out for the next one.

**Comment by sauloperez** [comment]
I'm still a bit lost about what you mention. Has something changed on Stripe suddenly for our release testing not to work or is it simply something we don't do often?

**Comment by RachL** [comment]
@sauloperez we did it each time so far. As we had your account. What has changed is that we can't share it anymore. Like I said the only problem is to manage to create another test account. By the way, which bank account is yours linked with?

**Comment by filipefurtad0** [comment]
Hey @RachL and @sauloperez,

I guess Stripe didn't enjoy my portuguese IP-address, and asked for a two-step authentication for me to proceed to the account settings. Perhaps this was optional, but I must have missed it - but I have a hunch this is now required.

In anycase and according to the link below, it should be possible to remove the two-step authentication, but only by contacting them directly. After removal perhaps we can share the account again.

https://support.stripe.com/questions/two-step-authentication-requirement
**Disabling Two-Step Authentication**
If you are having trouble with two-step authentication, you can request that your account have the requirement removed by contacting Stripe Support.

**Comment by sauloperez** [comment]
That sounds like the way to go @filipefurtad0 . I'll ask them to do so as the owner of the account.

**Comment by sauloperez** [comment]
All good so far!
