### ISSUE TITLE
Reports are timing out on French production

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4439]
## Description

A few users have reported this: for the month of October they cannot download data for their hub.

Most of them do this in the evening: last user reported this yesterday at 9:30pm.

This is _not_ due to the last release, because all the cases that I have, are trying to reach reports only once a month.

## Steps to Reproduce

Here are the prod data we can use for one user in particular : 

when trying to replicate now, the time out might not be reached and the pages loads with 1.79min

1. Log in as super admin
2. Go to Orders & fulfillment reports
3. Select the month of october for the following hub: `Collectif Court Circuit - dépôt de la Barre de Monts` (or any hub starting by "collectif court circuit)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v2.6.1
* Browser name and version: Firefox 69
* Operating System and version (desktop or mobile): Desktop

## Possible Fix
Increase FR time out

**Comment by RachL** [comment]
This was not provision in FR prod yet, is this correct?

**Comment by sauloperez** [comment]
Yes, it was Nov 12th at noon :point_right: https://app.datadoghq.com/event/event?id=5189133656004272199

**Comment by RachL** [comment]
@sauloperez my comment was 17 days ago ;) 
We didn't provision until the release deployment, which means that during 5 days this hub couldn't reach their report.
Luckily I could do it during the night and send them their report.
I didn't say anything at that time because I thought it is something that will require time from the team, and thought I had to wait until the release. But now that I see that we do it quite regularly for UK I regret not pushing for an early provisioning - it killed a bit my schedule :(
Maybe we should define a rule for it? It would be great for instances without a dev to know what they can ask for.

**Comment by sauloperez** [comment]
definitely, you should have pushed. Provisioning is something we do before deployment but just as a convention and because ofn-install has no release process whatsoever. We need to do something about it as things like this issue depend on it.
