### ISSUE TITLE
Option for producer to set 'Organic' flag against organic products

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#445]
I am very sorry that this has only just come up.  i don't know how we missed it earlier but several Stroudco shoppers and the Stroudco management group feel that we need to keep the Stroudco system of producers being able to flag products which are certified organic.
We don't need to be able to filter on this (although that would be nice in the future) but we do need shoppers to be able to see which products are organic without having to search on the word 'organic' in the product description.
@lin-d-hop and @pmackay is this a big job?
Very sorry
Nick

**Comment by kirstenalarsen** [comment]
I've got some bad news and some good news @NickWeir63  . . . the bad news is that this is a much bigger job than it sounds. the good news is that it's well underway and should be in staging by next week 

see notes here - http://community.openfoodnetwork.org/t/properties-of-enterprises-and-product-variants-e-g-organic-certified/50  

there are a couple of annoying little tasks to do with enterprises setting them up that haven't managed to get scheduled here yet, so very open to @pmackay or @lin-d-hop putting their hand up for those. Can tell you more if anyone has capacity

FYI - you can keep an eye on what we're working on by going to . . http://community.openfoodnetwork.org/c/development/doing

**Comment by NickWeir63** [comment]
the good news far outweighs the bad - thank you
