### ISSUE TITLE
Release v2.6.3 Dióspiro

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4465]
Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-10dc3bd3d246b50e8999

Target commit: https://github.com/openfoodfoundation/openfoodnetwork/commit/8546e11ffcc31d428a3655d08457d22769693fd2

Build: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/998

- [x] Draft
- [x] Test
- [x] Publish
- [x] Deploy

**Comment by lin-d-hop** [comment]
Release testing notes here:
https://docs.google.com/document/d/1IyyW9s1DYL3Zip4jEs_nZjq_uJ_5FgbvBetHwX9M4WA/edit#

This is good to go with the patch.
Thanks for all the fast paced work on the fix so we are still getting this out today :-)

**Comment by luisramos0** [comment]
deployed everywhere 🎉
