### ISSUE TITLE
[Release Blocker] Incorrect Shipping Method in OC Customer Totals Report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4468]
## Description

Introduced in 2.6.3.

The Order Cycle Customer Totals report is not showing the correct shipping method. Instead is it showing the first available shipping method no matter which one was selected for the order.

@luisramos0 identified the bug here:
https://github.com/openfoodfoundation/openfoodnetwork/pull/4426#discussion_r346749067
Thanks Luis!

Personally as this is our most heavily used report I think this bug blocks the release. Open to others disagreeing.

## Expected Behavior

Order cycle Customer Totals report displays the shipping method that was selected on the order.

## Actual Behaviour

Order cycle Customer Totals report always displays the same shipping method, the first available one.

## Steps to Reproduce

1. Complete an order where you had a choice of multiple shipping methods and you did not choose the first one
2. View the order in the OC Customer Totals report.
3. The incorrect shipping method is displayed. Fees are correct

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 2.6.3
* Browser name and version: 
* Operating System and version (desktop or mobile):

## Possible Fix

See the discussion following this comment:
https://github.com/openfoodfoundation/openfoodnetwork/pull/4426#discussion_r346749067

**Comment by Matt-Yorkley** [comment]
Okay, I'll take a look at this, starting with some specs that cover selecting a non-first shipping method at checkout, which are obviously missing.

**Comment by luisramos0** [comment]
:+1: I wonder if we should just revert/merge/release immediately and then get the a better fix for the next release. It's your call.
It would be good to publish the release today and release tomorrow.
