### ISSUE TITLE
Contact link in private shop message broken

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4472]
## Description

When a guest (not logged in) visits a private shop, a little message tells them to login. It also contains a contact link but clicking on it doesn't do anything.

## Expected Behavior

Clicking on the contact link should open the Contact tab on the same page.

## Actual Behaviour

Nothing happens.

## Steps to Reproduce

1. Open a member-only shop front.
2. Visit the shop front as a guest (in a private window).
3. Click on "contact" in the notification.

## Animated Gif/Screenshot

<img width="1912" alt="Window_and_Harcourt_Organic_Farming_Co-op__HOFCoop__-_Open_Food_Network" src="https://user-images.githubusercontent.com/3524483/69096938-955ef300-0aa9-11ea-9da5-8e11593805d1.png">

## Workaround

Click on the Contact tab instead.

## Severity

bug-s3: a feature is broken but there is a workaround

You could argue that this is a s4 bug because people can still use the platform. But if they want to click the contact link, they are stuck and need help. It's likely that they don't know the workaround and may not be able to use the platform.

## Your Environment

* Version used: v2.6.2
* Browser name and version: Firefox on Linux and Chrome on MacOS

**Comment by RachL** [comment]
This is working now 🎉 Closing
