### ISSUE TITLE
Invoices are showing shipping address instead of billing address

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4473]
## Description
Invoices are showing shipping address instead of billing address.

The label is invoice_billing_address and then the field picked up is the ship_address 
https://github.com/openfoodfoundation/openfoodnetwork/blob/9c8c71bd0877a2ffbf3dc68fc75a0049ffa68c78/app/views/spree/admin/orders/invoice2.html.haml#L45

## Steps to Reproduce
1. Go to `/admin/orders?q[s]=completed_at+desc`
2. Select an order and generate a PDF invoice
3. Compare the address on the invoice and the address mentioned in customer detail menu at `/admin/orders/ORDERNUMBER/customer`
4. See that the invoice is not mentioning billing address as it should.

## Workaround
None I can recall except looking at the order customer details?

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: 2.6.2
* Browser name and version: Firefox 70
* Operating System and version (desktop or mobile): Desktop

**Comment by kshlyk** [comment]
Hello @RachL. I can fix the bug, but I'm not sure which is wrong: **label** or **value**? Could you please have a look at generated invoice and dispel my doubts.

**Comment by RachL** [comment]
Hi @kshlyk and welcome :-) The invoice should show the billing address. So the label is correct, but the value is wrong.
Let me know if this isn't clear

**Comment by kshlyk** [comment]
It's clear, thank you. I'm fixing it
