### ISSUE TITLE
Improve Email Deliverability

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4491]
## Description
This epic represents the effort to improve email deliverability across OFN's domains.

This epic originates from #4194 and particularly [this comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/4194#issuecomment-547375382) with a list of errors and warnings detected using mxtoolbox.

These are the domains considered for this epic:
- ORG - https://mxtoolbox.com/domain/openfoodnetwork.org
- FR - https://mxtoolbox.com/domain/openfoodfrance.org
- AU - https://mxtoolbox.com/domain/openfoodnetwork.org.au
- UK - https://mxtoolbox.com/domain/openfoodnetwork.org.uk
- KA - https://mxtoolbox.com/domain/katuma.org
- US - https://mxtoolbox.com/domain/openfoodnetwork.net
- CA - https://mxtoolbox.com/domain/openfoodnetwork.ca
- BE - https://mxtoolbox.com/domain/openfoodnetwork.be
- DE - https://mxtoolbox.com/domain/openfoodnetwork.de

The emails providers used right now for these domains are:
- gmail - AU, ORG, CA
- sendgrid - BE, DE, FR, UK, US
- mandrill - KA

## Acceptance Criteria
One possible definition of the acceptance criteria for this epic is: "there are no errors and no major warnings in mxtoolbox for any of our domains".

We can at some point define what are the warnings in mxtoolbox that we consider "major warnings" and what are the warnings we can live with.

**Comment by luisramos0** [comment]
status of each issue:
- #4492 this probably involves switching email providers in the uk or ignore and close the issue.
- #4493 pending confirmation from @sauloperez to remove dns entry
- #4494 pending access to CA and BE dns registers
- #4495 pending question to @RachL about vtiger lookups that could be removed from the spf record
- #4496 this is the most laborious one where we need to analyse dmarc records and fix the problems (like emails being sent from the forums tool without dkim :-/)
- #4497 I have just asked Maikel if he could give this one a try
- #4498 I dont have access to uk dns register (there's a 2fa wall) - probably something for @Matt-Yorkley to have a look
- #4499 pending access to CA dns register

**Comment by luisramos0** [comment]
ok, as discussed before, I dont think this is ALL S2 level. All these things help avoiding emails sent to spam folders but I believe the s2 issue in UK comes from #4492 and possibly (this one could also be a false alarm) #4498 

As part of this effort I think we should finish #4494, #4493, #4498 and discuss #4492 
#4496 is important but can take a while to get sorted as we need to go through all the emails sent by each domain... I am tagging it S3 so we can leave it for later.

If everyone agrees, 4495 and 4496 will remain open in "All the things" and we try to close the others. 4493, is with @sauloperez  and 4492, 4494, 4498 are for @Matt-Yorkley (or someone with access to uk dns).

**Comment by luisramos0** [comment]
thanks @Matt-Yorkley for fixing #4494 and #4498 
Only the blacklisted issue remaining then: Katuma #4493 and UK #4492.

**Comment by Matt-Yorkley** [comment]
Note: UK is looking better now, and I've updated the DMARC policy from `none` to `quarantine`, which should help with deliverability.

**Comment by luisramos0** [comment]
@Matt-Yorkley from what I read it's recommended to have impecable dmarc reports for some time before moving to quarantine... I wouldnt move so fast to quanrantine because emails will be marked as spam if not correctly configured.
