### ISSUE TITLE
[Email Deliverability] Spam filter used for katuma.org emails is blacklisted on Spamhaus DBL

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4493]
## Description
![Screenshot 2019-11-25 at 15 35 31](https://user-images.githubusercontent.com/1640378/69554174-4a594a00-0f99-11ea-85ae-3d2f81e39715.png)

I think the best solution here is to stop using this spam filter: filterantispam.com
To do this I think we just need to remove a DNS entry where this filter is configured.

**Comment by luisramos0** [comment]
ping @sauloperez I leave it up to you to remove the dns config because I am not sure why/who added it originally.

**Comment by sauloperez** [comment]
Yes, I let this to us. Thanks for taking care of it!

**Comment by sauloperez** [comment]
Done. I remove those two mx entries after the DNS provider's tech support confirmed they were old antispam filters they no longer use.

The score at https://mxtoolbox.com/domain/katuma.org/ immediately improved. We only have `No DMARC Record found` reported now.

**Comment by luisramos0** [comment]
great, thanks!!!
dmarc! I missed katuma in https://github.com/openfoodfoundation/openfoodnetwork/issues/4494 reopened it.
