### ISSUE TITLE
[Email Deliverability] Most recent instances (.BE, .DE, .CA and .NET) have no DMARC and SPF records

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4494]
## Description
![Screenshot 2019-11-25 at 15 43 26](https://user-images.githubusercontent.com/1640378/69554885-5b568b00-0f9a-11ea-82e1-cead2640fcbf.png)

We need to add DMARC and SPF records for these 4 domains.

Re dmarc record:
- mxtoolbox can generate dmarc records

Re the spf record:
- For the gmail ones AU, CA according to [this](https://support.google.com/a/answer/33786?hl=en) we need to add something like: v=spf1 include:_spf.google.com ~all.
- For the sendgrid ones US, DE and BE, according to [this](https://sendgrid.com/docs/glossary/spf/) we need to add something like this: v=spf1 include:sendgrid.net ~all

**Comment by luisramos0** [comment]
I have added spf and dmarc records for DE and US (these are on the same godaddy account as AUS)

we are now missing BE and CA

**Comment by luisramos0** [comment]
ok, CA is done.

Only BE missing.

**Comment by Matt-Yorkley** [comment]
I've just had a look and BE isn't on the UK's hosting account. I'm not sure where their DNS record are kept...

**Comment by luisramos0** [comment]
from whois I see it's on https://www.dnsbelgium.be
ping @RachL maybe Theo will have the credentials?

**Comment by RachL** [comment]
@luisramos0 @Matt-Yorkley Theo says he has no idea and apparently nobody else in Oxfam was involved... ?

**Comment by sigmundpetersen** [comment]
I think BE is hosted on OVH at least, but maybe that's not what you're looking for.

**Comment by Matt-Yorkley** [comment]
Maybe it's in their OVH account then... I'll take another look

**Comment by luisramos0** [comment]
more info here:
https://www.dnsbelgium.be/en/whois/info/openfoodnetwork.be/details
it points to https://www.123-reg.co.uk/
and it also points to heg.com which mentions godaddy...

**Comment by Matt-Yorkley** [comment]
Yeah it looks like it's with 123-reg.co.uk

**Comment by Matt-Yorkley** [comment]
I've added the credentials to Bitwarden and I'll have a look at SPF records now.

**Comment by Matt-Yorkley** [comment]
BE now has a valid SPF record :+1:

**Comment by Matt-Yorkley** [comment]
BE now has a DMARC record as well, with reports going to the tech@ address (along with UK reports) :+1:

**Comment by luisramos0** [comment]
looks good here https://mxtoolbox.com/Pro/domain/openfoodnetwork.be//#/
thanks Matt!
closing this, we can now track the dmarc reports and the errors in #4496

**Comment by luisramos0** [comment]
reopening, I missed Katuma.
https://mxtoolbox.com/Pro/domain/katuma.org/#/
@sauloperez do you want to give me access or do you want to add it yourself?

**Comment by sauloperez** [comment]
Done! no more errors for katuma.org

**Comment by luisramos0** [comment]
thanks!!!!

**Comment by sauloperez** [comment]
thanks for dealing with the issue so efficiently just telling me what to do. Much appreciated :trollface:
