### ISSUE TITLE
[Email Deliverability] spf Too many included lookups for FR domain

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4495]
## Description
spf Too many included lookups

![Screenshot 2019-11-25 at 15 53 16](https://user-images.githubusercontent.com/1640378/69556454-a07bbc80-0f9c-11ea-98b1-b58e426fd31c.png)

We need to make the spf record more simple.

The existing SPF record contains vtiger domains and that makes the list too long. @RachL do we still use vtiger to send emails from @openfoodfrance.org?

**Comment by luisramos0** [comment]
this is a warning on mxtoolbox but google mxchecker considers this an error:
https://toolbox.googleapps.com/apps/checkmx/check?domain=openfoodfrance.org&dkim_selector=

**Comment by RachL** [comment]
@luisramos0 thanks for the reminder, I totally missed this question. 

Vtiger is our CRM and support tool. So we are sending emails with it in two different manner :

1. We use it to send email like a regular email box. The main advantage is that the email is store with the contact profile, easy for any team member to check what has been said previously. 
However we could stop doing it: there is other ways we can archive our emails.

2. Our support tool: when people write at support [at] openfoodfrance.org it creates a ticket / issue in Vtiger. This sends an automated email to them to confirm the ticket has been created. Then any response by the support team will generate an email to the user. The user answer per email most of the time. 

This second manner is working really good with our user and help us to organize incoming emails depending on severity. We could imagine transition to another support tool but I guess we will have the same problems?

**Comment by luisramos0** [comment]
This is the SPF record for FR: 
`include:mx.ovh.com include:ca.vtiger.email include:vtigermails.com ?all`

This is a problem with the vtiger setup, on their side, they are giving us two domains to be added to spf and these 2 domains go (DNS) around a lot creating this problem:

this is the spf record of ca.vtiger.email...

<img width="1107" alt="Screenshot 2019-12-05 at 15 13 51" src="https://user-images.githubusercontent.com/1640378/70247818-eb9e8800-1771-11ea-82eb-55787ed4df11.png">

and this is the full depth of their spf hierarchy: click [here](https://www.dmarcanalyzer.com/spf/checker/?dmarcdns%5Btype%5D=spf&dmarcdns%5Bdomain%5D=openfoodfrance.org&g-recaptcha-response=03AOLTBLS6xtJoBpS_ALBIq5W71qsYz7ptyoVNGwKcsD9NT-0zzaxtA6G7VMk8ZZhHCmV4KKxUhaYS6KDLkQqhpPOlFcc_jGfGtCTdZkAziZj1mBnGTeurqEZk2QIdY5301czDFXXFwQBEi_INaPHT5YCYks_MtHhmkJQdgHHMFiTdKUVLRSZRiCu64jkQd0JxPBvaUUTcdzxBQ6kk8aT2REHSQ3pjzcrmg33W0whobQDrguBI_FaPEGKvipvdEl4QpyCSLhqxVa9M_uppBhd-NestuHSBXDjnOTTCWujZgj3ujRt2sHQxd0q0_67b4yoCjwEdaBapNIr5qGxL4FZcN_5uAwrAbQjGODVYjpsQw-GitN0P1X8Js-jcDdLwbXZJTkbpgEtIa4488LzqJNF9_Zq7vw8veFx9fR-_MVpbfbTo7WYFV_Shcy1KzJAo_EIH1YQF1GbCYcqPWOtlMOcBPMODuRKLFqMG7hQIGgChOQN3Ui2iBlaNtG51-LY1lnT4NbSwqtD9cjhg
) and run the report

it's insane..

the OVH one also has a problem with the use of PTR:
"You shouldn't use PTR lookups as they are deprecated"
Although I dont think this is the problem here.

SO, the only way out of this I can think of is to separate the domain of the emails sent by vtiger from the other ones. For example, making emails to and from vtiger go from/to info@crm.openfoodfrance.org

To be clear, this problem impacts negatively the email reputation of the domain @openfoodfrance.org

**Comment by pacodelaluna** [comment]
Ok, didn't know about this issue, I will take a deeper look at this config, I just copied/pasted some configuration from VTiger and OVH, I will try to understand it a bit more.

**Comment by luisramos0** [comment]
hello @pacodelaluna  your config is correct, you did what they ask you to do. the problem is on their side.

**Comment by RachL** [comment]
@luisramos0 @pacodelaluna shall I contact them to see if they can do something? We are paying the Vtiger service so generally their support gives a quick answer.
Or is it a case where we should consider another tool?

**Comment by luisramos0** [comment]
ah, good point, lets contact them, yes!
the question is really just: we are getting "too many spf lookups" error when including your spf records, how can we fix this problem?

**Comment by RachL** [comment]
Okay. Email sent!

**Comment by RachL** [comment]
@luisramos0 @pacodelaluna here is Vtiger's answer:

> Thank you for reaching out. On reviewing I noticed that you have used the SPF record of Email Campaign server which is no more need as Email Campaign relays on CANME to authenticate emails.
Please do remove the "include:ca.vtiger.email"(ref) from SPF record.

**Comment by luisramos0** [comment]
that is nice, I did it and it fixes the problem.
Maybe we can ask them to update their guide: https://www.vtiger.com/docs/email-authentication

I am closing the issue.
If their advise is not correct and they send emails from ca.vtiger.email, we will see the errors in the dmarc reports: #4496

**Comment by RachL** [comment]
Great, thanks!

**Comment by pacodelaluna** [comment]
Good catch, sorry, I couldn't deal with this lately.
