### ISSUE TITLE
DMARC reports should have no errors

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4496]
## Description
After we setup dmarc dns records for our domains we receive DMARC reports. These reports list errors for all emails sent, we should fix these errors.

We need to list the existing reported errors for each domain here. For example, in org.uk the emails sent from the forum are not authenticated with dkim.

After all these problems are fixed we can enable the DMARC policy in the dmarc record (currently disabled) to Quarantine. That will make this warning go:
![Screenshot 2019-11-25 at 16 03 55](https://user-images.githubusercontent.com/1640378/69556738-344d8880-0f9d-11ea-9cb7-e8383e3978b8.png)

I am not sure we really need to enable the policy but we sure need to fix the errors that come on the dmarc report. 

One of the tools that can be used to do this is to send an email to ping@tools.mxtoolbox.com from our domain and see the report in mxtoolbox.

**Comment by luisramos0** [comment]
We have a number of reports already being sent, particularly to tech@openfoodfoundation.org
I have just looked at some reports for openfoodnetwork.org.au and found some errors in report from google.com (report ID 2355158623373711237):
A - this IP 202.78.197.197 (ip-78-197-197.dtp.net.id) sent 2 emails on behlaf of openfoodnetwork.org.au and both dkim and spf failed.
B - this IP 188.65.118.154 (freemail.footholds.net) sent 1 email on behlaf of openfoodnetwork.org.au where spf failed (basically because this IP is not in our dns record)
C - this IP 79.170.44.47 (mail47.extendcp.co.uk) sent 1 email on behlaf of openfoodnetwork.org.au where spf failed (basically because this IP is not in our spf record)

A report from the previous day for ofn.org.au includes errors for 3 more emails for case B above and 6 more emails for case C above.

Another report from mail.ru includes one email from 198.2.175.43 (mail43.suw151.rsgsv.net) that fails both spf and dkim.

From other reports I think it looks like enterprises are using mailchimp to send emails to their customers and using the domain "openfoodnetwork.org.au". This is what I see in one report:
```
		<identifiers>
			<envelope_to>terrewahfarm.com.au</envelope_to>
			<envelope_from>mail43.suw151.rsgsv.net</envelope_from>
			<header_from>openfoodnetwork.org.au</header_from>
		</identifiers>
```

**Comment by Matt-Yorkley** [comment]
We have a lot of failures like this for UK. I'm not sure how to interpret them all. Mails from the app (via Sendgrid) are all fine. The failures are a mix of odd domains and apparently Google mail server IPs... I'm not sure if some of them are valid mails sent by us or not.

**Comment by luisramos0** [comment]
I think they are all valid emails, I dont think anyone is sending emails on behalf of OFN.
I think the failures will all have an explanation, one example are individual accounts like your email on openfoodnetwork.org.uk, do you have correct dkim config when you send emails from that account? that will appear on the dmarc report.
Long term we should aim to clean this up because every email sent without authentication will hurt the reputation of the domain.

**Comment by Matt-Yorkley** [comment]
I've only just added an email for myself. All the emails using `@openfoodnetwork.org.uk` just forward incoming mails to personal email accounts. In theory, when anyone from the UK team replies to one of those emails it should be from a personal email, and shouldn't directly use the `openfoodnetwork.org.uk` domain in the from-address.

**Comment by lin-d-hop** [comment]
Not true @Matt-Yorkley 
We have set gmail smtp servers to send mail from the same address. This was originally a plan for free email accounts but now obviously a very costly solution.
Time to stop using forwarding and gmail smtp to manage our mail.

**Comment by Matt-Yorkley** [comment]
I think some mail clients allow you to modify the form address to respond "as" another email. So we need to figure out if anyone in the UK team is doing this., or if some gmail accounts are trying to do it automatically?

The other remaining bits to investigate are: emails on our Discourse site at `https://community.openfoodnetwork.org.uk/` for password reset, signup, etc, (these don't have DKIM/SPF, and i don't know how to modify the Docker image for it) and taking a careful look at our Mailchimp newsletter to make sure it's passing DKIM.

**Comment by lin-d-hop** [comment]
Yes everyone in the UK team is doing this :laughing: :woman_facepalming:

**Comment by Matt-Yorkley** [comment]
Aha! I missed your first message. Yeah, that gmail SMTP hack is totally blocking our deliverability.

**Comment by lin-d-hop** [comment]
Yep. I see that now. Let's fix it. Give me a plan please :pray:

**Comment by lin-d-hop** [comment]
I have no resolved the SMTP hack our our email deliverability seems to have gotten worse.
Any ideas? @Matt-Yorkley

**Comment by luisramos0** [comment]
just to clarify: the recent subs issue is not related to this.

**Comment by lin-d-hop** [comment]
Closing as instances have got proper email set ups now for their team emails.
