### ISSUE TITLE
[Email Deliverability] ORG.AU - mixed up DNS records

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4497]
## Description
This needs to be looked at:
![Screenshot 2019-11-25 at 16 24 40](https://user-images.githubusercontent.com/1640378/69558450-277e6400-0fa0-11ea-9dd5-646b682654ec.png)

**Comment by luisramos0** [comment]
Apparently there's a mail server running on the AUS prod2 server:
telnet openfoodnetwork.org.au 25
Trying 43.239.97.171...
Connected to openfoodnetwork.org.au.
Escape character is '^]'.
220 prod2.openfoodnetwork.org.au ESMTP Postfix (Ubuntu)

this is flagged by google mx checker as a problem.

@mkllnk is this some specific thing on the au server or is this a generic ofn-install issue?

**Comment by mkllnk** [comment]
I was not aware of that! Maybe the cloud image came with the mail server installed, or it's the dependency of something else, maybe installing Wordpress as apt package could have triggered that?

I don't think that ofn-install has anything to do with it. We do run our Wordpress website on that server and it sends out emails when you create a new user or reset the password. The server should only listen to localhost though. Are you happy to look into that or should I take over here?

**Comment by luisramos0** [comment]
Thanks @mkllnk I am unfamiliar with wordpress setup and I dont know how to fix that problem. maybe faster if you try to fix it?

**Comment by mkllnk** [comment]
Postfix was automatically installed by mailutils. Mailutils was manually installed. I guess that it came with the cloud image of Rimu hosting.

Postfix is actually used by our Wordpress installation to send emails. Deliveribility hasn't been an issue yet. We are only sending to OFN-AU staff members when creating a new account or resetting a password.

The server was not authenticating emails from outside. I now changed the postfix config to only listen to the localhost network interface. Port 25 is closed from the outside.

@luisramos0 Does this complete the task? I guess we can't do anything about Gmail server banners.

**Comment by luisramos0** [comment]
yes, problem fixed 👌 
![Screenshot 2019-12-05 at 09 52 07](https://user-images.githubusercontent.com/1640378/70224294-f131a900-1744-11ea-8d16-2add67a5d7c2.png)

thanks Maikel!
