### ISSUE TITLE
[Email Deliverability] org.uk spf record is invalid

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4498]
## Description
According to google mx checker, org.uk spf record is invalid.

![Screenshot 2019-11-25 at 16 33 37](https://user-images.githubusercontent.com/1640378/69559172-5a752780-0fa1-11ea-9500-e90c61c72997.png)

https://toolbox.googleapps.com/apps/checkmx/check?domain=openfoodnetwork.org.uk&dkim_selector=

**Comment by luisramos0** [comment]
ping @Matt-Yorkley

**Comment by Matt-Yorkley** [comment]
Fixed :+1:

**Comment by luisramos0** [comment]
thanks Matt :+1:
