### ISSUE TITLE
[Email Deliverability] DKIM is not setup for 

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4499]
## Description
According to google mx checker DKIM keys are not setup for the following domains: US, FR, UK, BE, DE, KA and CA
At least the ones using gsuite (CA) should have this problem sorted.

![Screenshot 2019-11-25 at 16 34 53](https://user-images.githubusercontent.com/1640378/69559348-b17afc80-0fa1-11ea-9bbd-5de29a32a681.png)

**Comment by luisramos0** [comment]
@tschumilas do you know where the DNS is registered for CA? can you share access in bitwarden or slack? thanks!

**Comment by tschumilas** [comment]
openfoodnetwork.ca  is registered with https://www.10dollar.ca/
But I don't know how to access bitwarden -  looks like it is an app for firefox?  is that right?  Or is there another way I access it?

**Comment by luisramos0** [comment]
bitwarden is a password manager, you can use the website or the browser plugin.
first you would need to create an account: https://bitwarden.com/

I've also pinged you on slack if you just want to send me the password to 10dollar.ca

**Comment by luisramos0** [comment]
I have access to the CA dns register, I fixed #4494 for BE :+1: 
to fix this one, DKIM, I also need access to the gsuite console to follow this guide (I pinged Therese on slack now to sort out this access): https://support.google.com/a/answer/174126

**Comment by luisramos0** [comment]
ok, done, thanks @tschumilas 
I am closing this issue. All other DKIM problems will show up in the dmarc reports. there's an issue for that #4496
