### ISSUE TITLE
Fix the CI build

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4500]
### What we should change and why (this is tech debt)

The CI build is currently failing a crazy lot which slows us down and brings down our confidence on the tests.

### Context

The only explanation that we found is that the recent upgrade to Ruby 2.2.10 made some of the already flaky tests totally unreliable.

### Impact and timeline

This is totally affecting our delivery pipe and needs to be fixed ASAP.

**Comment by sigmundpetersen** [comment]
Maybe #3369 can be considered as part of this work? Improving spec reliability using timwcop

**Comment by Matt-Yorkley** [comment]
I'm wondering if now is a good time to try out `CircleCI`? All these flaky specs pass locally and only fail in Semaphore, which is running Ubuntu 14. We might get a faster build, too...

**Comment by luisramos0** [comment]
:tada:

**Comment by sauloperez** [comment]
If I'm not mistaken https://github.com/openfoodfoundation/openfoodnetwork/pull/4756 was the last missing piece.

**Comment by luisramos0** [comment]
there are few more but they dont break so often, embbeded_shopfront_spec for example.
this was a good team effort!
