### ISSUE TITLE
New OC bottom page buttons do not fit well with long text

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4503]
## Description

When translating the button in French for example, the text is longer, leaving the buttons to display like this:

French:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/f8b723d1-36a1-4e50-9024-a47c539775d7)

Spanish:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/54929695-6cb4-4f03-85a5-d4cf4e528fa1)

Instead of:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/6312c51d-488a-4b02-b89b-2ae5f7f938e3)

## Steps to Reproduce

Make sure to check a non English instance.

1. Go to `/admin/order_cycles/`
2. Create or edit an OC
3. See bottom buttons

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v2.6.4
* Browser name and version: Firefox 70
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
for reference, this is similar to https://github.com/openfoodfoundation/openfoodnetwork/pull/3648/files
