### ISSUE TITLE
Release v2.6.5 Coriander

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4517]
Steps: 

- [x] Include translations
- [x] Draft:
 https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-57280c729f3a29eddb19
- [x] Test:
 https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1029
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

**Comment by RachL** [comment]
Alright this is ready to go! 🎉 

Testing notes: https://docs.google.com/document/d/1M71ImDsv1kTYuC2_Lno3pn2OWAQvmrWGAoIw-pIoFLo/edit#
