### ISSUE TITLE
Tamar Valley Food Hub - Pack By Supplier report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4521]
## Description

The Pack By Supplier report is a crucial report for the functioning of this food hub. It has long been a report that they've struggled with, timing out and the like. It's the main reason that the UK has a 6 min timeout.

This week the report is not running at all. They have tried running the report for 1 day's data at a time and that has not worked. 

The error is a timeout slug.

## Expected Behavior

Report runs

## Actual Behaviour

Slug

## Steps to Reproduce

1. Go to reports and click Pack By Supplier on OFN UK
2. Use for enterprise "Tamar Valley Food Hub" (id 160) - for order cycle "TVFH 20191129" (id 203812)
3. Wait 6 mins and see the slug
4.

## Severity

s1 - This is stopping the hub from doing their deliveries this week. This is our biggest hub and currently all is lost.

## Your Environment

* Version used: UK Prod
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

10min timeout?

**Comment by kristinalim** [comment]
Noting these stats in the server right now:

```
Tasks: 168 total,   3 running, 165 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.0 us,  0.6 sy,  0.0 ni, 91.2 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem :  8174824 total,  2923388 free,  4089480 used,  1161956 buff/cache
KiB Swap:  2097144 total,  1502736 free,   594408 used.  3634292 avail Mem
```

There is ~2.9 GB free RAM right now, but at some point there probably was a memory spike that caused processes to use swap. The server is still using 0.6 GB of swap in use right now.

**Comment by luisramos0** [comment]
I am looking at the data, the OC has 48 exchanges and 2134 variants, the previous OCs had 45 exchanges and around 2000 variants.
The number of orders is also a little higher with 188 against 165 and 184 before.
So, the data volume looks similar but slightly higher.
I am not sure such a small difference could cause the report to reach the timeout...

**Comment by kristinalim** [comment]
Okay, so I managed to [find a command](https://www.cyberciti.biz/faq/linux-which-process-is-using-swap/) for listing processes using swap, and it does seem that a reboot would be the easiest way if it is safe:
 
```
openfoodnetwork@production18:~/apps/openfoodnetwork/current$ for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | sort -k 2 -n -r
memcached 167336 kB
bundle 124572 kB
ruby 109372 kB
agent 42788 kB
fail2ban-server 11244 kB
bundle 7060 kB
bundle 4084 kB
bundle 3804 kB
bundle 3700 kB
postgres 3216 kB
systemd-journal 2308 kB
postgres 2196 kB
accounts-daemon 1960 kB
trace-agent 1580 kB
postgres 1536 kB
postgres 1536 kB
postgres 1504 kB
postgres 1468 kB
postgres 1456 kB
postgres 1456 kB
do-agent 1404 kB
rsyslogd 1236 kB
nginx 1180 kB
postgres 1096 kB
postgres 1088 kB
postgres 1084 kB
postgres 1084 kB
postgres 1084 kB
postgres 1084 kB
postgres 1080 kB
[etc]
```

**Comment by kristinalim** [comment]
@luisramos0 Given the numbers here and our hesitation to reboot the server, I think we can try:

1. Restarting memcached to handle the `memcached` task
2. Deploying, to handle `bundle`, `ruby`

**Comment by luisramos0** [comment]
ah, yeah, lets do that!
and you can run the command aboe again after restarting things.

**Comment by kristinalim** [comment]
I've restarted memcached:

```
ofn-admin@production18:~$ ps aux | grep memcached
memcache 11782  0.0  0.0 642820  5272 ?        Ssl  Oct22  28:54 /usr/bin/memcached -m 128 -p 11211 -u memcache -l 127.0.0.1 -t 6 -I 4M
ofn-adm+ 30126  0.0  0.0  14228   992 pts/5    S+   15:45   0:00 grep --color=auto memcached
ofn-admin@production18:~$ sudo /etc/init.d/memcached restart
[ ok ] Restarting memcached (via systemctl): memcached.service.
ofn-admin@production18:~$ ps aux | grep memcached
memcache 30194  0.1  0.1 223308 15100 ?        Ssl  15:45   0:00 /usr/bin/memcached -m 128 -p 11211 -u memcache -l 127.0.0.1 -t 6 -I 4M
ofn-adm+ 30235  0.0  0.0  14228   916 pts/5    S+   15:46   0:00 grep --color=auto memcached
```

**Comment by Matt-Yorkley** [comment]
CPU is spiking near 100%...

**Comment by kristinalim** [comment]
Thanks for suggesting to just reload Unicorn, @Matt-Yorkley :

```
openfoodnetwork@production18:~/apps/openfoodnetwork/shared$ cat pids/unicorn.pid 
9676
openfoodnetwork@production18:~/apps/openfoodnetwork/shared$ ps aux | grep unicorn
openfoo+  1463  2.4  8.5 2058288 698996 ?      Sl   14:00   2:41 unicorn worker[0] -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
openfoo+  1473  3.9  7.7 1985092 636964 ?      Sl   14:01   4:24 unicorn worker[2] -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
openfoo+  9676  0.0  1.0 569160 84088 ?        Sl   Nov26   0:43 unicorn master -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
openfoo+ 10920  3.2 10.5 2287448 866200 ?      Sl   12:29   6:39 unicorn worker[3] -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
openfoo+ 26347  4.5  7.1 1283032 584176 ?      Sl   15:33   0:51 unicorn worker[1] -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
openfoo+ 32360  0.0  0.0  14228  1056 pts/3    S+   15:52   0:00 grep --color=auto unicorn
openfoodnetwork@production18:~/apps/openfoodnetwork/shared$ kill -s USR2 9676
```

**Comment by kristinalim** [comment]
I also restarted `delayed_job` which was one of those using swap (formerly 100+MB):

```
ofn-admin@production18:~$ for file in /proc/*/status ; do awk '/VmSwap|Name|^Pid/{printf $2 " " $3 " " $4 }END{ print ""}' $file; done | grep ruby
ruby  32412  0 kB 
ruby  32526  0 kB 
ruby  32528  0 kB 
ruby  32531  0 kB 
ruby  5016  62280 kB 
ruby  8376  0 kB 
ofn-admin@production18:~$ ps aux | grep 5016
openfoo+  5016  0.2  4.4 900296 361568 ?       Sl   Nov26   8:06 delayed_job
ofn-admin@production18:~$ sudo systemctl restart delayed_job_openfoodnetwork.service
ofn-admin@production18:~$ ps aux | grep delayed_job
openfoo+ 19623  1.9  2.5 568244 208572 ?       Sl   16:38   0:00 delayed_job
```

**Comment by kristinalim** [comment]
I also restarted Unicorn because the old workers weren't getting killed after the reload:

```
sudo systemctl restart unicorn_openfoodnetwork.service
```

**Comment by kristinalim** [comment]
Another thing I noticed BTW is that part of the datadog agent is running on swap as well. I don't know if it is intrusive or just reads logs - if the former, can be a bottleneck too...

@Matt-Yorkley Do you happen to know if it is safe to restart without restarting all the processes that use it?

**Comment by kristinalim** [comment]
This is `agent` in the list of processes above, using only 42 MB of swap. Noting here also for documentation.

**Comment by luisramos0** [comment]
I was looking at the code and found that this report and orders_and_fulfillments_report use Permissions.visible_orders and basically puts all the orders the user can see in a IN clause :face_with_head_bandage: :coffin:  (Reports::LineItems#search_orders)

**Comment by luisramos0** [comment]
we changed the timeout on the server to 12mins
@RachL just confirmed the report works for one day in 7mins

have we ever considered data archiving in OFN? Archiving orders from previous years would avoid this problem. The problem will get bigger as the user gets more orders in the system.

**Comment by lin-d-hop** [comment]
Archiving would be a great part of a the performance strategy.

**Comment by lin-d-hop** [comment]
Trying to run again today I cannot get the final day of orders in this order cycle to load in the report.
Nov26 (9:30am) - Nov27(9:30am)

**Comment by luisramos0** [comment]
From the back of this issue i am working on improving performance of the report by improving one of the permissions queries "visible_orders":
https://github.com/openfoodfoundation/openfoodnetwork/pull/4523

I dont think this will be enough, there will probably be other things we need to do to get this report to run in "a few minutes".

I agree running a report in a background job is a good approach but this hub only has 38k orders in the system and under 200 orders in this OC. This report shouldnt take over 10minutes to compute...

**Comment by Matt-Yorkley** [comment]
From Datadog it looks like there's some big N+1 issues with loading properties. I can have a go at it tomorrow

**Comment by luisramos0** [comment]
do you mean this?
![Screenshot 2019-11-29 at 15 48 30](https://user-images.githubusercontent.com/1640378/69879596-bc929d00-12bf-11ea-8b51-71faa0e56fd9.png)

how do you know this is from the report?

**Comment by luisramos0** [comment]
@Matt-Yorkley tested your PR locally with live data where the report is taking 8 minutes to load.
This has indeed reduced the number of queries from 321 to 101 but the report is taking the same time to load. 8 mins :-(
I think the problem is in Report::LineItems#list
I'm trying to re-write it.

**Comment by Matt-Yorkley** [comment]
Maybe its something with that specific data? The page load took less than half the time for me locally...

**Comment by Matt-Yorkley** [comment]
8 minutes is insane...

**Comment by Matt-Yorkley** [comment]
Are you using data from UK prod for that specific enterprise? From Lynne's comments it seems like the data around the 25th was especially bad. I wonder if there's something more there?

**Comment by luisramos0** [comment]
I am running my tests with live uk data and running the report for the same OC dates.
The 25th loads ok in under 2 minutes. If I run the 25th and the 26th it gets to 8 minutes.
Just rerun it now, your PR doesnt improve the situation. It took a few seconds more actually in this last run... :-(
I think it's related to hidden line items, I'll debug now.

@Matt-Yorkley  I have made some refactorings (like converting Report::LineItems to a class). If you make any major changes to the report please do it on top of my PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/4523

**Comment by luisramos0** [comment]
I couldnt believe these results so I run the report again in master and with your PR. 8mins both.

**Comment by luisramos0** [comment]
The report that takes 8mins, if I comment out line_items_with_hidden_details the same report takes 30secs :-O
"30secs fix" in lib/open_food_network/reports/line_items.rb:
<img width="610" alt="Screenshot 2019-11-29 at 22 22 39" src="https://user-images.githubusercontent.com/1640378/69891745-c4b9ff00-12f6-11ea-9c0a-94320410c3dc.png">

So, the problem is isolated 👍 

Now we need to fix it.

**Comment by luisramos0** [comment]
my first clue is that we are abusing IN clauses all over the app, sometimes the IN clause has a sql query which is ok, but I see many times we have lists of IDs computed previously in a separate query. That isn't as fast as a join or a inner query AND it has limits:
https://stackoverflow.com/questions/1009706/postgresql-max-number-of-parameters-in-in-clause

**Comment by luisramos0** [comment]
ok, I think this last commit in this PR fixes the problem: https://github.com/openfoodfoundation/openfoodnetwork/pull/4523/commits/d7fa7909d7a865b8fea2cfa8a8ef5000ba612af2
Basically instead of searching for line items that are hidden (NOT IN clause) we search for the editable line items (MERGE) and iterate on the negative (the line items that are not editable, thus hidden :-)).

The code needs to be validated and tested further. But the report runs in 77secs instead of 8mins now on my local for 25th and 26th together.

I have a busy weekend, I will only come back to this Monday morning. If anyone has time to validate this and push it forward for testing that would be great. This is still an unresolved S1 (we better get this fixes live before next Thursday).
