### ISSUE TITLE
Release v2.6.6 Turnip

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4528]
Steps: 

- [x] Include translations
- [x] Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-c942482f3ea7356a59b1
- [ ] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1036
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

**Comment by lin-d-hop** [comment]
@luisramos0 the build is failing :-( tried rebuilding and same error.

**Comment by lin-d-hop** [comment]
Worked on the third try. On to the testaporium.

**Comment by lin-d-hop** [comment]
Testing notes here:
https://docs.google.com/document/d/1cpYPhiRBztilW7MSSobuTouHf8aODrc0W1EFZ20DCZw/edit#

I had a few issues on reports but I think this is corrupt data. @RachL is going to take a deeper look as I have to run now. Thanks Rachel! I owe you a testing tag :-)

**Comment by RachL** [comment]
The reports are working good with staging FR data. Let's see now on UK with the prod data.

**Comment by RachL** [comment]
With prod data, they were time out issue, so this is ready to go and be tested on UK live.
