### ISSUE TITLE
[mobile ux] Reduce prominence of 'select OC' when Customer can't use it

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#4529]
## Description
When a shop is set to 'private' i.e. only registered customers can place orders, it still shows the order cycle selector. If there is more than one order cycle available, it shows the big red 'choose when you want your order' message. The selector doesn't work as the shop isn't active for this customer. It is unnecessarily confusing!

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/fe559dc8-ffe8-41b3-9ef1-045fff3b3caa)

## Expected Behavior
* If a shop is private and the user on the page is not a Customer
* Definitely - the red 'choose when you want your order' box should NOT appear
* Maybe - the OC selector should just be hidden / not appear

## Actual Behaviour
The OC selector looks like you can use it, and there is a big red message box telling you you should, even though you can't

## Steps to Reproduce
* Create a private shop (using shop preferences) 
* Go to shopfront as a user that is not registered as a customer

## Workaround
Send instructions to customers via email or other channel to try and reduce confusion

## Severity
S4

## Your Environment
Mac, Chrome

**Comment by RachL** [comment]
@kirstenalarsen the problem with having the selector once tags are in place is already documented here: https://github.com/openfoodfoundation/openfoodnetwork/issues/3170

The problem you mention with private shops sounds different. Can you change the description to focus on this problem only?

**Comment by RachL** [comment]
But I wonder if you don't have tag in place, because I cannot reproduce it on the private shops we have :/

**Comment by kirstenalarsen** [comment]
Just updating this with screenshot of how it looks in new mobile setup, this shop has two order cycles but is set to private shop 

![image](https://user-images.githubusercontent.com/2911176/78295972-ac920f00-7578-11ea-830a-91a17772ea5b.png)

The selector box isn't active at all, can't click on it or anything, so I guess the ideal would be that it just doesn't appear at all?

**Comment by RachL** [comment]
@kirstenalarsen yes I also think best would be that it does not appear at all.

**Comment by kirstenalarsen** [comment]
Just adding a bit of extra information in case this were picked up by new dev - a 'private shop' is one that has the Enterprise Shop Preference 'Publicly Visible Shop' set to 'visible to registered customers only'

![image](https://user-images.githubusercontent.com/2911176/78561942-e2c2dd80-785b-11ea-979a-51c862594ac1.png)

e.g. https://openfoodnetwork.org.au/admin/enterprises/warrenbayne-farm-collective/edit#/shop_preferences

**Comment by luisramos0** [comment]
this is inside an epic in dev ready, can I pick this up?
