### ISSUE TITLE
Clicking on cart in header nav takes me to checkout, not to edit cart page

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4532]
## Expected Behavior
When I click on the cart icon in the header nav it will take me to the edit cart page

## Actual Behaviour
When I click on the cart icon in the header nav it takes me the first screen of the checkout process and I need to hit the 'back to cart' button to actually see the cart.

## Workaround
Click on the 'back to cart' button. 

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

## Your Environment
n/a this is agnostic to all environments

## Possible Fix
Change the link so it goes to /cart

--> Ruby work

**Comment by Matt-Yorkley** [comment]
Is this just on Mobile?
