### ISSUE TITLE
Hide the groups link in shop menu if not in a group

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4533]
## Description
**- As a:** shopper
**- On page:** a shop
**- I want to be able to do:** not see the groups link if the shop isn't in a group, because I'll open that link, see nothing there, and be annoyed by it.

## Acceptance Criteria & Tests
- [ ] When the shop is part of a group, I will see the groups menu item. When I click on this I will see an expanded section with the group/s listed.
- [ ] When the shop is not part of a group, I will not see the groups menu item.

1. Go to a shop that is in a group
2. Check that the group menu item displays
3. Check that on-click of that menu item the section expands and the group/s are listed there.
4. Go to a shop that is not in a group
5. Check that the group menu item does not display

--> Ruby work

**Comment by jeduardo824** [comment]
I can work on this one

**Comment by sigmundpetersen** [comment]
Hey @jeduardo824! Yes, thank you please go ahead 🙂

**Comment by mkllnk** [comment]
Hey @jeduardo824, how are you going?

The tabs are rendered in `app/views/shopping_shared/_tabs.html.haml`. They call a helper called `shop_tabs` which lists the tabs. That's probably the code you want to change. It's in the file `app/helpers/shop_helper.rb`.

`current_distributor.groups.present?` tells you if the enterprise has any groups. When there are no groups, it will probably look better to adjust the columns `cols` to 6, 3, 3. Have a play and see how it looks.

Bonus points: the best approach is to write a test first. Head to `spec/helpers/shop_helper_spec.rb` and add a `describe "shop_tabs" do` block. It should have at least two test cases, one with group and one without. :wink: 

Happy hacking! :smile:

**Comment by jeduardo824** [comment]
@mkllnk Thanks! It was very clarifying. I will open a PR by the end of the week. Great tip about the cols!

**Comment by jeduardo824** [comment]
Hey guys! Sorry for taking so much time to accomplish this. @mkllnk I need your opinion about the `cols.`

This is the result of using `6 3 3`:
 
![Screen Shot 2020-01-05 at 23 08 32](https://user-images.githubusercontent.com/27960597/71790750-ca4ee700-3010-11ea-9730-18ab82d4f3eb.png)

And this is the result of using `4 4 4`:
![Screen Shot 2020-01-05 at 23 10 27](https://user-images.githubusercontent.com/27960597/71790757-e05ca780-3010-11ea-9d68-b5024859b818.png)

I prefer `4 4 4`. And you?
