### ISSUE TITLE
[mobile ux] Change phone keyboard enter key to say "Search" or show magnifying glass

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4534]
## In a feature branch or master?
This can be merged directly to master 🎉 

## Description
**- As a:** shopper
**- On page:** search on a shop using a mobile or tablet device
**- I want:** the button that currently says "done" to say "Search" so that it reflects the action I am undertaking

Note: < input type="search" >

## Acceptance Criteria & Tests
- [ ] When on any mobile or tablet device using the product search function I will see "Search" or magnifying glass icon display on the enter button. 

1. Go to a shop
2. Click into the search bar
3. Look at the keyboard, the enter button on iOS/Safari should say "Search" and on Android/Chrome should show a magnifying glass icon

**Comment by rmklaus12** [comment]
I'm going to take #5104 , but happy to get assigned this one as well.

**Comment by sigmundpetersen** [comment]
Thank you!

**Comment by rmklaus12** [comment]
Can someone point me in the right direction for this code? I've done very little mobile development and while I'm getting to know the codebase by digging around, I don't want to waste too much time. Thank you!

**Comment by daniellemoorhead** [comment]
http://mobileinputtypes.com/

**Comment by rmklaus12** [comment]
The input type is set as search but still not working properly. In researching, there may be a related issue with Angular, so I'm still working on this. It appears to not be as straightforward as I/we had hoped

<img width="769" alt="Screen Shot 2020-05-01 at 11 06 14 am" src="https://user-images.githubusercontent.com/30268789/80772983-d9e3d400-8b9b-11ea-9385-3d6bc0912eb2.png">

**Comment by rmklaus12** [comment]
Testing with Browserstack shows iOS does not have same results as expected by the input types on http://mobileinputtypes.com/, which is fairly old I'm guessing. Android seems to work beautifully with most of the data types, specifically the search, email, phone and password. 
If anyone has any insights on iOS, meanwhile I'll keep at it.

**Comment by daniellemoorhead** [comment]
maybe input type="search" rather than input id="search" @rmklaus12 ?

**Comment by rmklaus12** [comment]
Thanks @daniellemoorhead, I actually just found the solution! 
`input inputmode="search"` 
It creates 'go' on the button instead of search, but it changes it. Input type alone does not work and all documentation is old, so seems Apple has changed that. I wish that link you shared had a date on it! His date example does show 2012 though. 
I'm testing on Browserstack and will then push the PR. 'inputmode' is only supported by newer browsers, so I'm going to leave the type field in there as well, as both work.

**Comment by daniellemoorhead** [comment]
You're wonderful @rmklaus12 😄

**Comment by rmklaus12** [comment]
Well...we shall see! It seems to be very browser/device dependent. Older iPhone models still show 'return' and the key on Android changes as well (magnifying glass or old school return symbol). So, my next question was going to be how important is this to work on as many devices as possible?

**Comment by daniellemoorhead** [comment]
I think what you've done is enough @rmklaus12, send it over for code review!

I looked up gifs for 'pass it on', saw this, has nothing to do with what you're about to do (pass it on to code review) but it made me LOL so here it is:

![](https://gif-finder.com/wp-content/uploads/2018/03/Boop-Pass-it-on.gif?v=2)

**Comment by rmklaus12** [comment]
I love it!! Happy to pass it on. I can't stop trying different things! I gotta...
![image](https://user-images.githubusercontent.com/30268789/80788141-a15bee80-8bcb-11ea-83d3-6eb68fb4f0b6.png)
