### ISSUE TITLE
[mobile ux] Field focus on iPhones change the zoom level of a page and user needs to resize it

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4535]
## In a feature branch or master?
This can be merged directly to master 🎉 

## Expected Behavior
When I do a search of shop products on an iPhone, the browser does not zoom in and resize so that the page no longer fits the screen.

## Actual Behaviour
When I do a search of shop products on an iPhone, the browser zooms in and resizes the page, which means when I click out of the search bar I then need to resize the page back to original in order to continue browsing. This is really annoying!

## Steps to Reproduce
1. Go to a shop on an iPhone (any browser)
2. Click on the search bar
3. See the page zoom in
4. Click out of the search bar, the page remains at the incorrect zoom level.

## Animated Gif/Screenshot
https://airtable.com/tblPoizwAxVfccvOz/viwIhkyM0Fc83qbts/recafWYVSJtNntiZE

## Workaround
Resize the page to fit the screen

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

## Your Environment
* Version used: n/a
* Browser name and version: Firefox and Safari, latest versions
* Operating System and version (desktop or mobile): Checked on iPhone 6s and X

## Possible Fix

There are several solutions at https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone. The simplest would be to increase the font size to at least 16px to prevent zooming.

## Here's a video of the wacky!!!
Courtesy of Yuko :P
(Had to zip the video as github says NO to videos!)
[OFN-20200108-mobile-search-field-resize.mov.zip](https://github.com/openfoodfoundation/openfoodnetwork/files/4038531/OFN-20200108-mobile-search-field-resize.mov.zip)

--> CSS

**Comment by daniellemoorhead** [comment]
@mkllnk if you fix this one there's benefit to CFF as well - it happens on their search bar too.

**Comment by luisramos0** [comment]
Nice, I can replicate this on my wonderful iphone 4 :-)
I'll try to fix it.

**Comment by luisramos0** [comment]
The font size was 14, so changing to 16 makes it look good. And it fixes the problem (at least on my iphone 4). Done #5261.

**Comment by mkllnk** [comment]
Hurray! This one will make @daniellemoorhead very happy. :tada:

![](https://media.giphy.com/media/iY08sb8H9mQG4/giphy.gif)
