### ISSUE TITLE
[mobile ux] Click anywhere to close the price breakdown info box

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4536]
## In a feature branch or master?
Product listing feature branch 

## Description
**- As a:** shopper
**- On page:** the products list of a shop
**- I want to:** click anywhere to close the price breakdown info box if I've opened one.

## Acceptance Criteria & Tests
- [ ] The price breakdown info box will shut if you click anywhere on the page.

1. Go to a shop on desktop
2. Click on a pie icon next to any product and display the info box
3. Click anywhere on the page outside of the displayed price breakdown info box
4. Info box will disappear.

--> JS

**Comment by daniellemoorhead** [comment]
@mkllnk do you think this could be a good first issue?

**Comment by mkllnk** [comment]
No. It may be easy but it may not. I have no idea how to solve it without taking a closer look at the code.

**Comment by daniellemoorhead** [comment]
Closing this as the remaining tweaks required will be part of another story.
