### ISSUE TITLE
French prod: not all product are loading on a shopfront

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4537]
## Description
A shopfront is not loading entirely. This user has embedded shopfronts on his website. The other shopfronts are working fine.

## Steps to Reproduce

1. Go visit https://www.openfoodfrance.org/micromarche-villeenbois/shop
2. Only the first products will appear

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
* Version used: v.2.6.5
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Both

**Comment by RachL** [comment]
We might need to dump the prod data somewhere: they won't reopen the shop before tomorrow

**Comment by luisramos0** [comment]
From slack:
```
error in console: “Use ‘track by’ expression to specify” (edited) 
it’s related to repeated products.
“id”:366,“name”:“Céréales”,“permalink”:“pates-de-bles-tendres-vrac1-1-26-27”
we had an issue related to this
it’s a new problem even with the fix from last time, the same product id is appearing twice: Duplicate key: 366
pls try to remove this product from the OC
Done it seems to be resolve indeed: now i can scroll up to Yoghurt.
```

This needs to be investigated. Not an S1 for sure, lets keep it S2 as this may happen to other shops and it's a very critical feature?

**Comment by RachL** [comment]
ok for s2. But the shops needs to be able to sell the product with id 366.

**Comment by luisramos0** [comment]
before we get someone to investigate (maybe me tomorrow morning) I'd try to clone the product, add it to OC and see if it still happens? #workaround

**Comment by luisramos0** [comment]
also, slightly change the name of the product or of its variants may help #workaround

**Comment by RachL** [comment]
@luisramos0 duplicating or chaging variant name does not work. however changing product name is working: I've changed `Céréales` to `Céréales_`

**Comment by mkllnk** [comment]
Good investigation. There is another product called "Céréales" and two products with the same name raise this error in Angular code:
```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: product in Products.products track by product.id, Duplicate key: 1454, Duplicate value: {"id":1454,"name":"Céréales","permalink":"pates-de-bles-tendres-vrac1-1-43-44-47-48-51","meta_keywords":"","group_buy":false,"notes":"","description":"","description_html":"","properties_with_values":[{"id":1,"name":"Label BIO AB","value":""}],"price":1.45,"variants":[{"id":3852,...
```

I'm not sure why Luis' output didn't specify the actual error name.

**Comment by mkllnk** [comment]
Confirmed: We just order by product name. When two products have the same name, the order in which they are returned from the database is undefined. In this case the two products with the same name have been retrieved in different orders for the first and the second page. And the pagination then lead to loading the same product twice. This patch fixes it:

```diff
diff --git a/app/services/products_renderer.rb b/app/services/products_renderer.rb
index ca9c72826..bfa7f4eaa 100644
--- a/app/services/products_renderer.rb
+++ b/app/services/products_renderer.rb
@@ -66,7 +66,7 @@ class ProductsRenderer
         .split(",").map { |id| "spree_products.primary_taxon_id=#{id} DESC" }
         .join(", ") + ", spree_products.name ASC, spree_products.id ASC"
     else
-      "spree_products.name ASC"
+      "spree_products.name ASC, spree_products.id"
     end
   end
 ```

I don't know how to write a test for this because I can't create test data that is reliably returning the "wrong" order when the order is undefined. I guess I just have to patch it without automated test.

**Comment by luisramos0** [comment]
ah, awesome @mkllnk
