### ISSUE TITLE
Timeout on Orders and Fulfilment Report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4547]
## Description

This report is timing out in UK and Australia.... detail

## Expected Behavior

Report loads in 3-4 minutes

## Actual Behaviour

Timeout at 12 minutes in UK

## Steps to Reproduce

1. UK Timeout:
Customer Totals Report
A user with only access to one enterprise - lynnedavis[at]gmail[dot]com
Tamar Valley Food Hub
Dates: 2019-11-29 to 2019-12-05
OC: TVFH20191206

## Workaround

To run the report 1 or 2 days at a time.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 2.6.6
* Browser name and version: Chrome Firefox
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
First thing I notice is that you have permissions on Tamar Valley Apple Co-op which is a producer, not a distributor. That means that the algorithm to hide customer details is having to work a lot.

**Comment by luisramos0** [comment]
I wonder if you have changed permissions of your user meanwhile, with the co-op enterprise, as a producer, I can run the report:
![Screenshot 2019-12-10 at 10 26 08](https://user-images.githubusercontent.com/1640378/70521683-8a8eff80-1b37-11ea-8fd5-647d445fe024.png)

**Comment by luisramos0** [comment]
I assumed this is wrong and I am now testing with a user with access to the Hub account.

From 2019-11-29+00:00 to 2019-12-03+00:00 the report runs in 2.4 mins.

But for the full date range it times out after 2.8 mins...
I read above "Timeout at 12 minutes in UK" - do you see 12mins in the network tab of your browser?

**Comment by luisramos0** [comment]
the full dates are taking 6.28mins locally. I will now try to understand where it is taking all this time.
