### ISSUE TITLE
Permalink to shops on UK Staging

### ISSUE THREAD

**Issue by aidandunsdon** [openfoodfoundation/openfoodnetwork#455]
Hi @RohanM   @NickWeir63  @pmackay  - Permalinks on UK staging  don't seem to be working as they did on development server.  Could this be related to problems @pmackay was having with installation and permalink field in database at https://github.com/openfoodfoundation/openfoodnetwork/issues/440 
see screen grab
![screengrab](https://cloud.githubusercontent.com/assets/9034769/6898128/139e529e-d6f0-11e4-9298-0f6cb7ae3bf7.png)

**Comment by aidandunsdon** [comment]
Actually this could be a problem at my end. Its now not working on the dev environment having worked with the previous version. I need to do some more tests... so leave it with me for now.cheers

**Comment by pmackay** [comment]
@aidandunsdon it looks like permalinks on staging are not quite what OFN would generate - Stroudco is `https://staging.openfoodnetwork.org.uk/Enterprise_27/shop` whereas I would have thought it should be something like `/stroudco/shop`.

Also the homepage shouldnt be showing all the producers, only the ones that are hubs.

**Comment by aidandunsdon** [comment]
@pmackay Sussed it now - closing issue cheers

**Comment by pmackay** [comment]
What was the issue?

**Comment by aidandunsdon** [comment]
There were mandatory fields missing in the source data,

**Comment by pmackay** [comment]
@aidandunsdon I notice the URL is still saying `Enterprise_27` - are you able to get it to say `stroudco`?

**Comment by aidandunsdon** [comment]
Refresh your browser - its working here now
