### ISSUE TITLE
AWS FR credentials in Bitwarden don't work

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4552]
## Description

The credentials for FR's AWS account don't work. As a result, we can't check if backups are properly ending up in the S3 bucket.

We need to update them with the right values.

**Comment by sauloperez** [comment]
ping @RachL @pacodelaluna

**Comment by pacodelaluna** [comment]
Checking this out.

**Comment by sauloperez** [comment]
I can confirm it's fixed! I can now see the backups.
