### ISSUE TITLE
Text formatting for 'about' groups 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#456]
can we get the same text editor functionality as for the enterprises?

from
![image](https://cloud.githubusercontent.com/assets/2911176/6915503/4eb1960c-d7e0-11e4-81ab-f887ea58836f.png)

to
![image](https://cloud.githubusercontent.com/assets/2911176/6915508/5a8a235e-d7e0-11e4-94f5-5d1206ca6a9e.png)

**Comment by mkllnk** [comment]
Yes, it's in the group-pages branch now.
