### ISSUE TITLE
Release v2.6.7 Rice

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4562]
Steps: 

- [x] Include translations
- [x] Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-09ca96d2e639a53e10aa
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1059
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

**Comment by filipefurtad0** [comment]
Hi @kristinalim :-)

I believe the release is good to go, testing notes below:
https://docs.google.com/document/d/1QYvso8wN5IDBS-fBw4Wg1mzu6-85tIyff9oK8LYlWHs/edit#

Moving to Ready to Go!

**Comment by kristinalim** [comment]
For reference, this is the Bugsnag error for the bug that @filipefurtad0 encountered:

https://app.bugsnag.com/katuma/katuma/errors/5df1473a4baf8d00191e7451?event_id=5df74f7c0054d6f52e4c0000

This is the related discussion on Slack:

https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1576491768009500
