### ISSUE TITLE
[mobile ux] Move shop content to tabs with URLs

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4568]
## Description

**- As a:** enterprise
**- On page:** shopfront
**- I want to be able to do:** have my shop content on separate tabs that I can link to directly

## Acceptance Criteria & Tests
**HOW IT LOOKS NOW**
Mobile
![Screen Shot 2019-12-13 at 3.11.26 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/daf0f4f0-78f5-45d9-ab4e-387d70adcbd9)
Tablet
<img width="739" alt="Screen Shot 2019-12-13 at 3 40 22 pm" src="https://user-images.githubusercontent.com/10949052/70769774-f59e3780-1dbe-11ea-98ca-3dbb593a3099.png">
Desktop
<img width="1222" alt="Screen Shot 2019-12-13 at 3 40 34 pm" src="https://user-images.githubusercontent.com/10949052/70769792-03ec5380-1dbf-11ea-80b6-469575a5223a.png">

1. Check that clicking on a tab link loads a new page with its own URL.
1. Check that the groups tab only shows if the shop is part of a group.
4. Check that the home tab only shows when the shop has a shopfront message.
5. Check that when there is no shopfront message, the default tab to open is shop.
6. Check that when there is a shopfront message, the default tab to open is home.
7. Check that the underline displays on the tab that is open, for every tab.

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

--> rails

**Comment by Matt-Yorkley** [comment]
Ok, so we already have linkable tabs. So I guess the main issue here is moving the actual product list (currently shown below every tab) to it's own `Shop` tab.

**Comment by daniellemoorhead** [comment]
>Ok, so we already have linkable tabs. So I guess the main issue here is moving the actual product list (currently shown below every tab) to it's own Shop tab.

And also move the shopfront message to the home tab. I'll test this to see how it's implemented.

@Matt-Yorkley we don't want this change to go into a release until the styling changes have been done to the content in these tabs - what's the best way of having this happen? Ping @mkllnk
