### ISSUE TITLE
[mobile ux] Style the 'About' tab

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4569]
## Description

**- As a:** enterprise
**- On page:** About tab in shopfront
**- I want to be able to do:** have my content look like the new design

## Acceptance Criteria & Tests

**HOW IT LOOKS NOW**
Mobile
![Screen Shot 2019-12-13 at 3.19.32 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/1e80b49b-2df9-4db5-87c1-13665cbb0e67)
Tablet
![Screen Shot 2019-12-13 at 3.21.17 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/716fea91-a1d4-4a4a-8601-355a0ef8cf18)
Desktop
![Screen Shot 2019-12-13 at 3.21.33 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/6f4540c5-753c-4880-ac6f-b50915b57a11)

**HOW IT NEEDS TO LOOK**
**_Mobile_**
- Full width image

![Mobile: Shopfront - About@1x](https://user-images.githubusercontent.com/19785399/72490119-3afdbc80-37e4-11ea-9c69-2a25ff3257b9.png)

**_Tablet_**
- Full width image

![Tablet: Shopfront - About](https://user-images.githubusercontent.com/19785399/72490211-95971880-37e4-11ea-98a1-a6a02a26524b.png)

**_Desktop_**
- Width of image to fit content area, centre-aligned
- 1200 x 260 will be wide enough for the space

![Desktop: Shopfront - About](https://user-images.githubusercontent.com/19785399/72490114-36390880-37e4-11ea-8ec7-ab666761b6ba.png)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

--> CSS

**Comment by daniellemoorhead** [comment]
@ybo can you please provide design input for tablet and desktop: is the preference to have the about image span the width on tablet and desktop? Current version leaves the image left aligned and in a smaller section, what should we do in the new version?

And @mkllnk if Yuko says to span the width will this cause issues / complexity in making sure images that are uploaded to a specific size don't pixelate? It looks like we ask for images that are 1200 x 260, is 1200 the span of the desktop width?

**Comment by mkllnk** [comment]
It adds complexity but shouldn't be too hard. When a large image is uploaded, stretch it across. And smaller images just stay small, but may centred?

**Comment by Matt-Yorkley** [comment]
This tab has been updated in #4655 

![about_tab](https://user-images.githubusercontent.com/9029026/71982402-a95edf80-3224-11ea-9f3a-564b0583773f.png)


...


Some other restyling of the navigation and theme has been added in #4690. Let me know if it needs anything else.

**Comment by daniellemoorhead** [comment]
Tested on UK staging, looks good:

<img width="1257" alt="Screen Shot 2020-01-22 at 5 02 56 pm" src="https://user-images.githubusercontent.com/10949052/72869384-2d42bc80-3d39-11ea-89fa-70a597158003.png">

<img width="753" alt="Screen Shot 2020-01-22 at 5 03 07 pm" src="https://user-images.githubusercontent.com/10949052/72869379-2b78f900-3d39-11ea-9729-0fcc261659a6.png">

<img width="478" alt="Screen Shot 2020-01-22 at 5 03 15 pm" src="https://user-images.githubusercontent.com/10949052/72869386-2e73e980-3d39-11ea-90ae-f7838207d661.png">
