### ISSUE TITLE
[mobile ux] Style the 'Producer' tab

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4570]
## Description

**- As a:** enterprise
**- On page:** Producers tab in shopfront
**- I want to be able to do:** have my content look like the new design

## Acceptance Criteria & Tests

**HOW IT LOOKS NOW**
Mobile
![Screen Shot 2019-12-13 at 3.46.09 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/bab0f94b-cb49-4797-8cdd-56d4e1511d28)
Tablet
![Screen Shot 2019-12-13 at 3.46.28 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/b5d7377c-2c03-4b80-9507-fe504499ba87)
Desktop
<img width="696" alt="Screen Shot 2019-12-13 at 3 46 44 pm" src="https://user-images.githubusercontent.com/10949052/70770104-2f237280-1dc0-11ea-9ad2-6d408d8d3ead.png">

**HOW IT NEEDS TO LOOK**
Mobile
<img width="235" alt="Screen Shot 2019-12-13 at 3 50 43 pm" src="https://user-images.githubusercontent.com/10949052/70770140-57ab6c80-1dc0-11ea-807e-9a2743c89ffc.png">

Tablet
- Same as current version, 2 rows
Desktop
- Same as current version, 3 rows

**NOTE: PLEASE KEEP THE TRACTORS AS THE BULLET IMAGE. THEY SHOULD BE SVG FORMAT SO SETTING THE COLOUR SHOULD MAKE THEM THE REQUIRED ORANGE.**

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

--> CSS

**Comment by daniellemoorhead** [comment]
@ybo we're sort of partial to the tractor bullet point, but you've used a boring dot point for the new look. Could we maybe keep the tractors? 🙏 Or are you anti-tractor and plain jane dot is the direction?

**Comment by ybo** [comment]
Hey I think you tagged the wrong user :)

**Comment by daniellemoorhead** [comment]
@mkllnk spoke to @yukoosawa today and it turns out that the tractor bullet points should be easy to set up, no work from her required. The colour of them should be set within the CSS (they're SVG files apparently).

**Comment by daniellemoorhead** [comment]
Closing this, will follow the required changes in #4764 and in test doc https://docs.google.com/document/d/1WpJmNwuYUC3V4rqf7MQEWCmh723q9FI41YnU4F9mX1Y/edit?usp=sharing
