### ISSUE TITLE
Units showing as 'none' on all pending or ready orders; showing as 'shipped' on all shipped orders

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4582]
## Description
The units on the order editing page are showing as 'none' on all new and all previous orders for 'pending' and 'ready' orders.  The units are showing as 'shipped' on all 'shipped' orders (versus showing the units.  This is happening for products entered as item or products entered by weight. 
 It is happening for new orders and ALL previous orders.  I've tested, and it is occuring on OFN-CAN and on OFN-US.  Might this be related to !https://github.com/openfoodfoundation/openfoodnetwork/issues/4581  as they started at the same time (first noticed Dec 14)

## Expected Behavior
the units should show on the orders to facilitate editing

## Actual Behaviour
units are showing as 'none'.  This is happening for all products and all new and old orders.  The item quantity CAN be edited and re-calcuation works fine.   The units are showing correctly in all reports and on the invoice.  

## Steps to Reproduce

1. go into OFN-CAN as super admin
2. go into the orders editing tab
3. see that order units are all 'none'
4.

## Animated Gif/Screenshot
![edit order screen does not show units](https://user-images.githubusercontent.com/13171778/70850972-18cbf400-1e5e-11ea-9947-94cb2e2fdd9c.jpg)

## Workaround
look to the variant description to know what the units are

## Severity
s2
(orders can still be edited)

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
hello Therese, thanks for raising the issue!
I think this is a bug introduced here: https://github.com/openfoodfoundation/openfoodnetwork/pull/4385

Although this is ugly, users can preform all actions in the app. I think this is an S3.

**Comment by tschumilas** [comment]
Hmmm - wonder why I never saw it before on the orders page -  the bug was reported back in October, I and other users here have edited many orders without seeing this.   Oh -  maybe its to do with just picking up translations in transifex.  Damn.  so I"ve made it s3 -  but its going in my paperclip priorities.

**Comment by kirstenalarsen** [comment]
wow i never noticed this, annoying!! putting on my list to consider for votes too

**Comment by RachL** [comment]
Ok I'm selecting this as FR's vote (it's more annoying than #7627 because visible during demos).

@openfoodfoundation/train-drivers-product-owners do you agree that "none" should not only be replaced by unit, but a combo of unit value and unit type?

If too complex I'm wondering if we shouldn't consider just removing the "x none/shipped".
