### ISSUE TITLE
Many warnings in master build 

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4589]
### What we should change and why (this is tech debt)
Since #4559 we have lots of these warnings in the build
`2019-12-16 03:00:26 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::UnhandledError is deprecated. Use Selenium::WebDriver::Error::UnknownError (ensure the driver supports W3C WebDriver specification) instead.`

That is the fact, I also _think_ the build is more unstable and is flaky specs are more flaky - maybe this is good as it will force us to fix the flaky specs.

### Context
I was looking for errors in a specific build and found the unrelated warnings.

### Impact and timeline
We need to fix the flaky specs OR revert 4559

**Comment by luisramos0** [comment]
I put this inside 4500 as I think it is closely related.

**Comment by luisramos0** [comment]
some quick analysis, here says updating capybara would solve the problem.
https://stackoverflow.com/questions/55810432/deprecation-warnings-after-switching-to-the-webdrivers-gem

updating capybara from 2.15 t

**Comment by luisramos0** [comment]
I can upgrade capybara to 2.18 :+1: but it doesnt solve the problem. I'll create the PR anyway.
I am now trying to upgrade webdrivers. I see Matt has suggested this already in 4559 :-)

**Comment by luisramos0** [comment]
ok, upgrading capybara and webdrivers done https://github.com/openfoodfoundation/openfoodnetwork/pull/4590

this issue (the warnings) remain.

**Comment by Matt-Yorkley** [comment]
So if we get to Spree 2.1 / Rails 4 we can upgrade these gems and improve Selenium/Capybara?

**Comment by luisramos0** [comment]
I am not sure what version of nokogiri spree 2.1 is on. if we get to nokogiri 1.8 we can get to capybara 3. I am not sure what's new in capybara 3, but it must be better: https://github.com/teamcapybara/capybara/blob/master/UPGRADING.md

**Comment by Matt-Yorkley** [comment]
I did some testing earlier and it seemed like our version of `devise` was the only thing holding us back on `nokogiri`...

**Comment by luisramos0** [comment]
ah, yeah, I was looking for what's holding us on to nokogiri, that 's great to know!
we dont have spree_auth_devise AND spree itself does not depend on devise! so we can try to upgrade devise directly!!!

we can try to move this forward directly:
gem 'devise', '~> 2.2.5'

**Comment by luisramos0** [comment]
spree_auth_devise 2-1-stable depends on:
s.add_dependency 'devise', '~> 3.2.2'

**Comment by Matt-Yorkley** [comment]
My mistake, it's `deface`, not `devise`...

**Comment by luisramos0** [comment]
ah, ok, what I say above about devise still applies. we can upgrade it :-)
I think we can get rid of deface in spree, we dont use in ofn and in spree it is used mainly for spree_auth_devise which we dont use. there's one deface for spree_api but we dont use it :-)
so, I think we could try to remove the deface dependency from spree in this next upgrade and upgrade nokogiri from there.

**Comment by Matt-Yorkley** [comment]
Fixed.
