### ISSUE TITLE
Payment Methods Table in Dashboard does not display in Plain Language

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#4592]
## Description
Table showing Payment Methods in Dashboard includes non-intuitive language that would not make sense to a customer. eg. Spree::PaymentMethod::Check, Environment: Production 

## Expected Behaviour
Table fields should display information in plain language

## Actual Behaviour
Log in as an Enterprise
Access Dashboard
Select Payment Methods 
Click on Manage Payment Methods button

## Animated Gif/Screenshot

![Screen Shot 2019-12-12 at 4 50 01 PM](https://user-images.githubusercontent.com/47620442/70954191-4021fb80-20c0-11ea-9977-88e02f094b62.png)

## Workaround
Table is still visible, but much of the information is meaningless to a customer

## Severity
S4

## Your Environment

Australian Instance

**Comment by kirstenalarsen** [comment]
Needs what plain language terms specified to be useful to incoming developer? or do you think this is self-explanatory @lin-d-hop?

**Comment by jeduardo824** [comment]
I will fix that!

**Comment by emilyjeanrogers** [comment]
I dropped the ball on following this one through as it was being worked on - and as per @kirstenalarsen 's suggestion should have specified it more clearly.  

The Provider Column now contains meaningful information. However the Environment Column is still 'tech' oriented. ie. the words *Environment* and *Production* are not meaningful to a Customer (or they do have meaning, but not the meaning we understand in terms of software development). 

I wonder does this column even need to be displayed to customers?

**Comment by luisramos0** [comment]
good point, that field is not shown in the edit form, only to super admins.
But it will show to managers on the list view.
For reference to a dev doing it, it's a simple change, something like this code change:
![image](https://user-images.githubusercontent.com/1640378/87487338-4ae04700-c635-11ea-9186-7e4376144d6f.png)

**Comment by luisramos0** [comment]
Hi @emilyjeanrogers the original request of this issue was resolved. I think we should open a new issue to remove the environment column. I think this should remain closed.

**Comment by emilyjeanrogers** [comment]
@luisramos0 the original request included removing the non-intuitive language, and specifically referenced this example:

Table showing Payment Methods in Dashboard includes non-intuitive language that would not make sense to a customer. eg. Spree::PaymentMethod::Check, **Environment: Production**

I guess it depends on processes etc - happy to open a new issue if that keeps it clean?

**Comment by luisramos0** [comment]
ah, sorry, I missed it. If it was mentioned in issue we should keep this open :+1:

The issue could have been more specific like include the decision to remove the environment column for non-super admins. Anyway, that's what we are asking for now :-)

### Expected Behaviour

The column Environment should only be displayed to super admins, not enterprise managers.

**Comment by luisramos0** [comment]
I am moving this back to all the things.
@jeduardo824 is this something you would like to pick up? Otherwise we can unassign you so other devs can pick it up :+1:

**Comment by jeduardo824** [comment]
I can work on that. I did not notice that I should have hidden the environment section. @luisramos0

**Comment by luisramos0** [comment]
awesome, thanks @jeduardo824 !

**Comment by emilyjeanrogers** [comment]
Thanks @jeduardo824

And yes agreed @luisramos0 I should have been a lot more precise in my specification of the issue! Lesson learned :-)
