### ISSUE TITLE
Reset password fails when logged in user clicks on confirm email (add Unregistered User to Manage Enterprise)

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#4593]
## Description
When an Enterprise adds an Unregistered user to manage their account, an email is sent to confirm the new user's email address. 

If the same desktop is used to confirm the email address... and If the user doesn't log out from all active windows before confirming the email, the user will not see the reset Password page and will be redirected to the home page, with previously logged in user account. 

If the user then logs out, and tries to go back to the email and click on the confirm email link, the email has already been confirmed and customer will see a login page. But the 'new' customer has not yet set a password. They can't login. They can't reset their password.

At this point a Superadmin needs to reset their password.

## Expected Behaviour
When a user clicks on the confirm password link in a new customer email, the system should recognise if they are already logged in as an existing user and manage the process accordingly.

## Actual Behaviour
The system requires the customer to know that they should be logged out before clicking on a confirm password link in a new customer email. The system does not offer a back up option to set a password if the link is clicked on while logged in as an existing customer. 

RESEST PASSWORD PAGE FOR NON-LOGGED IN USER WHEN CLICK ON CONFIRM EMAIL:
https://openfoodnetwork.org.au/user/spree_user/password/edit?reset_password_token=61FnraprWsu2YJ1q4WsL

REDIRECTED WHEN LOGGED IN USER CLICKS ON CONFIRM EMAIL 
https://openfoodnetwork.org.au/#/login

## Steps to Reproduce

1. Access Dashboard as Logged in Enterprise
2. Go to Users
3. Click button to Add an Unregistered User
4. Enter an email address not current set up on OFN
**FAIL:**
5. Do not log out
6. Open confirmation email and click on Confirm Email address
7. It is not possible to set a password
8. It is not possible to go back and log out and repeat steps 6. 7. and 8.
**SUCCESS:**
Complete steps 1. - 4.
5. Log out of all OFN windows first
6. Open confirmation email and click on Confirm Email address
7. Confirm Password.
8. Successfully logged in as New User.

## Workaround
There is a work around (log out first) but Enterprises are not aware of it.

## Severity
s5 

This mostly impacts OFN Admins or logged in Superadmins, when setting up enterprise accounts on behalf of a customer, or setting up test or investigation accounts.

## Your Environment
Australian Instance

**Comment by RachL** [comment]
I'm not sure this is something that needs to be changed 🤔  @lin-d-hop what do you think?

**Comment by lin-d-hop** [comment]
I agree that there is an issue here but I don't think it is so problematic that we will ever allocate resources. In almost all cases the OFN handling of sessions creates a surprisingly (for us) smooth user experience.
@emilyjeanrogers Did a user report this or is it something that annoyed you? If it was just you that noticed it then I would suggest we close this issue in protection of our sanity and mental health ;-)

**Comment by emilyjeanrogers** [comment]
@lin-d-hop This is only raised by me as it's something that impacts me every time I investigate a customer issue - but it's unlikely to impact a Customer directly. I agree it could be closed, even though i would love it to be addressed! 

At the heart of the issue is the fact that I have to add myself as a manager of an enterprise in order to view the OFN experience the way they view it. A more robust, long term solution might be to make it possible for a Superadmin to "View As" a specified Enterprise. 

Meanwhile I'll close this!
