### ISSUE TITLE
[mobile ux] 5. Product list

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4597]
## What is the problem we are solving 
Currently the list of products on the shop looks like an homage to mid 20th century brutalist soviet architecture. There is nothing about the product view that screams "BUY ME!" It's more of a "you must read and use your own imagination to fill in the gaps and work hard till you die" kinda deal.

Problems with this: 
- Photos sell products. And yet, photos hidden behind a click.
- Product details are in a modal. Modals are frowned upon on mobile. They also offer no way to allow for direct linking to a product in the shop.
- You have to type in the quantity you want, no easy, single click way to add the product to the cart.

## Success factors = expected outcome 
- [ ] Products have as much detail about them shown on the listing itself. 
- [ ] Increased cart size on mobile due to photo / product attractiveness. (can we measure this @RachL?)

## In/out of scope for phase 1
Out: individual product pages; In: maintaining current modal for individual product pages.

Out: direct linking to products; In: direct link to shop product list.

## Design Overview
**MOBILE**
![Mobile: Shop - Product List](https://user-images.githubusercontent.com/19785399/72670027-868fb080-3a06-11ea-9912-419911a2de09.png)

![Mobile: Shop - Product Variants](https://user-images.githubusercontent.com/19785399/72628817-1c4f1100-391d-11ea-9456-08e09508d97f.png)

**TABLET**
![Tablet: Shop - Product List](https://user-images.githubusercontent.com/19785399/72670030-93140900-3a06-11ea-86a2-34721c26aef2.png)

**DESKTOP**
![Desktop: Shop - Filters](https://user-images.githubusercontent.com/19785399/72496399-6d64e500-37f7-11ea-9d93-ff9c412cfdc5.png)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

**Comment by Matt-Yorkley** [comment]
The UI on this page came up in discussions today. We have to display price per kilo / price per litre next to products, for most countries (it's a compliance issue)...

**Comment by yukoosawa** [comment]
@Matt-Yorkley can you point me to a place where I can read up about the compliance requirements in more detail?

**Comment by RachL** [comment]
@yukoosawa some official info here: https://ec.europa.eu/info/law/law-topic/consumers/consumer-contract-law/price-indication-directive_en in most ecommerce website it is refered to as "price per unit".

**Comment by yukoosawa** [comment]
@RachL @Matt-Yorkley Can you also provide a more precise description of why the new design is in your mind not doing the right thing?

**Comment by Matt-Yorkley** [comment]
@yukoosawa I was just mentioning it here as I think we'll need to add this "price per unit" thing  somewhere here, and we don't want to mess up the nice design :sweat_smile:

**Comment by Erioldoesdesign** [comment]
@jaycmb @RachL I added this to our section on challenges and consideration in our doc on unit prices: https://www.notion.so/openfoodnetwork/Consumer-Price-Comparison-2642469713954191af8e82e308ca71ec
