### ISSUE TITLE
[mobile ux] Add products to the cart redesign

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4598]
## In a feature branch or master?
Product listing feature branch 

## Description
**- As a:** shopper
**- On page:** the product list in a shop
**- I want to be able to do:** quickly add or remove products in my cart

## Acceptance Criteria & Tests
- [ ] Standard product listing

**HOW IT LOOKS NOW**
<img width="122" alt="Screen Shot 2019-12-18 at 2 30 47 pm" src="https://user-images.githubusercontent.com/10949052/71053671-4e951380-21a3-11ea-8df9-d33c6090ec1a.png">
<img width="148" alt="Screen Shot 2019-12-18 at 2 31 06 pm" src="https://user-images.githubusercontent.com/10949052/71053652-3ae9ad00-21a3-11ea-8469-77b133e77c64.png">

**HOW IT NEEDS TO LOOK**
<img width="77" alt="Screen Shot 2019-12-18 at 2 31 40 pm" src="https://user-images.githubusercontent.com/10949052/71053679-58b71200-21a3-11ea-812c-ef8bf44cb5d7.png">
<img width="77" alt="Screen Shot 2019-12-18 at 2 31 46 pm" src="https://user-images.githubusercontent.com/10949052/71053683-5a80d580-21a3-11ea-9ded-e405fe4d9fe3.png">

- [ ] Group buy min/max product listing

**HOW IT LOOKS NOW**
On mobile:
![Screen Shot 2020-05-26 at 5 26 52 pm](https://user-images.githubusercontent.com/10949052/82872245-1d9ce400-9f76-11ea-8330-2d59bdcf162d.png)

On desktop:
![Screen Shot 2020-05-26 at 5 26 25 pm](https://user-images.githubusercontent.com/10949052/82872251-1f66a780-9f76-11ea-8bd2-2183d173e767.png)

**HOW IT NEEDS TO LOOK**
On mobile:
![OFN Shop Product List Bulk Order 20200518](https://user-images.githubusercontent.com/10949052/82873350-b849f280-9f77-11ea-912d-b3b75e3170b3.png)

![OFN Shop Product List Bulk Order Modal 20200518](https://user-images.githubusercontent.com/10949052/82871850-8768be00-9f75-11ea-8e05-603418392fa0.png)

On desktop:
![Desktop OFN Shop Product List Bulk Order 20200518](https://user-images.githubusercontent.com/10949052/82872091-e595a100-9f75-11ea-84ef-52a99b6e16ff.png)

![OFN Desktop Shop Product List Bulk Order Modal 20200518](https://user-images.githubusercontent.com/10949052/82871860-89cb1800-9f75-11ea-808b-23ea04ecc550.png)

------
### Testing notes
**Test single products**

ADD A PRODUCT TO CART
1. View product list on a shop
2. Click the add button on a product
3. That product should be added to the cart with a quantity of 1; the cart icon at top of page should show a '1'; the 'add' button should change to be a plus/minus buttons; '1 in cart' copy should display under buttons.

INCREASE QUANTITY IN CART FOR A PRODUCT
1. Click the '+' button on a product
2. The cart should now have 2 of that product; the cart icon at the top of the page should show a '2'; '2 in cart' copy should display under buttons.

That product should be added to the cart with a quantity of 1; the cart icon at top of page should show a '1'; the 'add' button should change to be a plus/minus buttons; '1 in cart' copy should display under buttons.

DECREASE QUANTITY IN CART FOR A PRODUCT
1. Click the '-' button on a product
2. The cart should now have 1 of that product; the cart icon at the top of the page should show a '1'; '1 in cart' copy should display under buttons.

**Test bulk products**
ADD A BULK PRODUCT TO CART
1. View product list on a shop
2. Click the add button on a product
3. Bulk product add modal displays
4. Click add 1 for min and 2 for max
5. That product should be added to the cart with a quantity of min 1 and max 2; the cart icon at top of page should show a '1'; the min and max numbers should display (as per screenshot) and 'in cart' copy should display under buttons.

INCREASE QUANTITY IN CART FOR A BULK PRODUCT
1. Click on the min/max numbers
2. Bulk product add modal displays
3. Click add 2 for min and 3 for max
4. That product should have a cart quantity of 2, and the min and max numbers should have changed to be 2/3.

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

**Comment by daniellemoorhead** [comment]
@mkllnk I've added the bulk products details to this story so you can go ahead and build it 🎉 

If you need better versions of the bulk products designs then @yukoosawa can sort those out for you.

I'd like to test this design with some shoppers/shops before we put it live, so as soon as I've tested the branch I'll be talking to a few users to make sure the design is 👌

**Comment by mkllnk** [comment]
Translations for "Add" to consider for the button sizes:

```
Ajouter
Ekle
Добавить
```

**Comment by daniellemoorhead** [comment]
@mkllnk how can we test those? Is there a way to understand what that will do to the layout prior to testing it other than @yukoosawa adding these into the design file?

**Comment by mkllnk** [comment]
We don't have a convenient way to test this on staging. I could create a special testing branch with these language bits added but I need to remove those language changes before merging it again.

**Comment by mkllnk** [comment]
@daniellemoorhead I tested one of the longest words `Aggiungi` and found that I needed to make the button 6px wider for a perfect fit. That should be fine. If people use longer translations, the add-button will just become a bit wider while the +/- buttons stay the same.

**Comment by daniellemoorhead** [comment]
awesome, thanks @mkllnk 😄

**Comment by mkllnk** [comment]
@daniellemoorhead @yukoosawa I looked at the design and the logic affecting the bulk quantity fields. The design shows a maximum quantity of `-` which means that it's not set. I find that confusing because it looks very similar to the button to reduce quantity.

Logically, it also makes sense to set the max quantity to at least what the min quantity is. When you want six apples, you imply that you want a maximum of six apples. So my current design increases the max quantity with the minimum quantity (unless the max is higher). It also reduces the min quantity with the max quantity (if you reduce the max quantity below the min quantity). This will be easier to understand when you actually play with it. I think that it makes much more sense than before and aids the understanding of the fields.

![Peek 2020-06-11 10-13](https://user-images.githubusercontent.com/3524483/84330976-3f2fd980-abcc-11ea-847a-63608910f308.gif)

**Comment by daniellemoorhead** [comment]
Cool @mkllnk 😎 

Let's get it through to testing and have a play with it!

**Comment by daniellemoorhead** [comment]
Any thoughts on when you'll have this in the branch and ready for testing @mkllnk?

**Comment by mkllnk** [comment]
My aim was to get it ready today. The implementation is done but the specs need adjusting and they fail seemingly unrelated... I have no clue why yet.

**Comment by mkllnk** [comment]
Remaining issue are documented in https://docs.google.com/document/d/1WZZSuMCLHiZ_UY_nLJZ8MI-HGadTQmVty7zXeS7H6VE

**Comment by daniellemoorhead** [comment]
Closing this card as all remaining work to be done is part of #6080
