### ISSUE TITLE
[mobile ux] Restyle product listings

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4599]
## In a feature branch or master?
Product listing feature branch 

## Description
**- As a:** enterprise
**- On page:** product listings on a shop
**- I want to be able to do:** the design to match the rest of my shop

## Acceptance Criteria & Tests
Key changes / call outs:
- [x] No more red, grey, black colour palette.
- [x] Photos now display on mobile
- [x] Product title wraps (same as current version)
- [x] Producer name truncates
- [x] Weight/size wraps
- [x] Price breakdown "pie" displays on mobile
- [x] Listing content layout change
- [x] Removal of category icon
- [x] Display product properties under description
- [x] Display truncated product description, 'more' link to open product detail modal
- [x] Clicking on product name or image also opens product detail modal
- [x] Removal of per-product sub-total display on mobile
- [x] Categories design has less padding without affecting the categories design in the filter section.

**HOW IT LOOKS NOW**
Mobile
<img width="479" alt="Screen Shot 2019-12-18 at 2 37 04 pm" src="https://user-images.githubusercontent.com/10949052/71053909-3245a680-21a4-11ea-8bc5-637a726f0ecb.png">
<img width="472" alt="Screen Shot 2019-12-18 at 2 38 33 pm" src="https://user-images.githubusercontent.com/10949052/71053915-383b8780-21a4-11ea-8200-0fc8818bcd07.png">

Tablet
<img width="621" alt="Screen Shot 2019-12-18 at 2 37 50 pm" src="https://user-images.githubusercontent.com/10949052/71053946-4c7f8480-21a4-11ea-8408-a335e6c4559e.png">
<img width="619" alt="Screen Shot 2019-12-18 at 2 38 09 pm" src="https://user-images.githubusercontent.com/10949052/71053950-50130b80-21a4-11ea-9b36-4cf3976af09c.png">

Desktop
<img width="948" alt="Screen Shot 2019-12-18 at 2 39 04 pm" src="https://user-images.githubusercontent.com/10949052/71053965-628d4500-21a4-11ea-9baf-b411c5d231eb.png">
<img width="942" alt="Screen Shot 2019-12-18 at 2 38 49 pm" src="https://user-images.githubusercontent.com/10949052/71053968-64570880-21a4-11ea-8f7b-fb8674889078.png">

**HOW IT NEEDS TO LOOK**
**_Mobile_**

![Mobile: Shop - Product List](https://user-images.githubusercontent.com/19785399/72670064-f4d47300-3a06-11ea-962e-a9d89950e99e.png)

**_Tablet_**

![Tablet: Shop - Product List](https://user-images.githubusercontent.com/19785399/72670062-ee45fb80-3a06-11ea-80b6-2c8d8b463e3b.png)

**_Desktop_**

![Desktop: Shop - Filters](https://user-images.githubusercontent.com/19785399/72496424-82417880-37f7-11ea-8329-c63513bb434c.png)

**_Max Characters_**

![Mobile: Shop - Max Characters](https://user-images.githubusercontent.com/19785399/72670055-e0907600-3a06-11ea-974f-7f618739831f.png)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

--> CSS + JS

**Comment by yukoosawa** [comment]
### **UPDATED DESIGN NOTES**

Product properties are now included
- Reduce size of product property here so they fit better in available space. But do not reduce the size of the product property elsewhere... they need to be appropriately sized for tap/clicking elsewhere.

Product description with more/less link
- Use 'more' link to expand description
- Use 'Show less' to collapse description
- Note: descriptions can include multiple paragraphs

_Short_
https://openfoodnetwork.org.au/prom-coast-food-co-op/shop
Mountain Oat Rye
> A tasty, longkeeping rye sourdough with lots of rolled biodynamic oats, a little olive oil, and sweetened with a little organic honey. Toasts well.

_Medium_
https://openfoodnetwork.org.au/synchronicity-farm/shop
BOX - Family Premium Large - Includes 2 Dozen Eggs + Extra of all items)
> Our Premium Box Includes 2 Dozen Eggs and more of all items in the box. When we pack a Seasonal Family Box each week, we make sure that there is an awesome selection of the freshest produce available at the time of harvest. As an example, the box contains: Kale, Salad Mix, Spinach, Avocado, Apples, Watermelon, Leek, Carrots with leaves, Zucchini, Cucumber, Corn, Sweet Potato, Sebago Potatoes, Red and Gold Onions, Eggs, Chilli, Bay Leaves, Garlic, Turmeric, Oregano, Parsley, Nasturtium Flowers.

_Long w/ paragraphs_
https://openfoodnetwork.org.au/elmore-compost-and-organics/shop
Pelletised Green Organic Compost
> Our pelletised compost is produced by pressing high grade compost through an extrusion process, resulting in a concentrated format. This innovative, convenient and concentrated format is ideal for all types of applications from the home gardener's potted plants to the broadacre farm's air seeder.

> Among the benefits of the pelletised format are convenient storage - takes up less space in your shed; fast & easy application - simply sprinkle a few pellets on your lawn, pot plant or around the fruit orchard; slower to release due to its increased density; efficient composting - when applied in the correct quantities; increased resistance to wind - doesn't blow around on a gusty day; cost effective freight and packaging - less bulk; handy weight & size - easier on your back; dust supressent - healthier for you; less mess - no dirt under your fingernails!

> Elmore's Organic Pelletised Compost will vastly improve your soil health naturally, acting as a condensed format soil conditioner.

Max character considerations
- Product title: wrap
- Producer name: truncate with ellipsis
- Weight/size: wrap

### **UPDATED IMAGES**

Mobile - Product listings
![Mobile: Shop - Product List](https://user-images.githubusercontent.com/19785399/71865635-693b1800-30d1-11ea-8b9c-82e41da3da39.png)

Mobile - Product listings expanded
![Mobile: Shop - Description Less](https://user-images.githubusercontent.com/19785399/71867066-9e963480-30d6-11ea-8a29-6906efed12bf.png)

Mobile - Max character examples
![Mobile: Shop - Max Characters](https://user-images.githubusercontent.com/19785399/71867125-dac99500-30d6-11ea-9769-6404d4afd161.png)

@daniellemoorhead A couple of things we should discuss
- The product name is orange to show it's clickable... but now they're not clickable...
- The producer name is blue to show it's clickable... are you wanting to remove these modals too?

**Comment by mkllnk** [comment]
@daniellemoorhead The designs don't show active elements like links. We have two links in this design:

1. The product name: orange-500
2. The producer name: teal-500

Should I select a lighter colour when hovering over the link? Maybe orange-400 and teal-400?

Hm, I just saw that @Matt-Yorkley decided to use darker colours for links in the producers tab. It would be consistent to go with that but I like lighter more. What does @yukoosawa say?

I'm assuming that I should remove all other active colours like when hovering over variants. It's only important for desktop anyway because mobiles don't have a mouse to hover.

**Comment by yukoosawa** [comment]
@mkllnk Great points! Although the 400/lighter colour looks nicer - accessibility guidelines would recommend darker (600/darker). I can provide colour specs for this if needed.

Can we also add a text-decoration: underline; so the visual indicator is not reliant on the colour change alone.

And YES to removing the variant hover! If it isn't clickable then no hover needed!

**Comment by mkllnk** [comment]
@yukoosawa There is no teal-600 defined in Zeplin. Can you add that for the hover/active colour?

**Comment by yukoosawa** [comment]
@mkllnk Teal 600: #007A9A

**Comment by mkllnk** [comment]
@yukoosawa Is there a design for our bulk buy option somewhere? I couldn't find it.

Bulk buy is when people can select two quantities per product. The first is what you want and the second is what you are willing to take to make a big bulk buy order work.

![Screenshot from 2020-04-09 14-24-27](https://user-images.githubusercontent.com/3524483/78857893-1bd29c00-7a6e-11ea-8d3d-e09f1cf1374f.png)

**Comment by yukoosawa** [comment]
@daniellemoorhead @mkllnk Is it a bug in staging that the bulk ordering min/max fields aren't reflected in the cart dropdown + edit cart page? Or is it intentional?

**Comment by mkllnk** [comment]
@yukoosawa I think that was never implemented. People are buying only the minimum quantity and that's what they are invoiced for to start with. If the coordinator needs to spread more bulk item and adds to peoples orders according to their "max" value, that's handled after checkout and after the order cycle closed.

**Comment by yukoosawa** [comment]
@mkllnk Thanks for clarifiying! Is it also safe to assume that within a single shopfront, there can be both 'bulk' and non-bulk' items listed? I feel like the orange 'add' button for non-bulk + the min/max fields for bulk items -- makes it a little unclear that the min/max fields need a number input to 'add to cart'... Plus the change in interaction for +/- becomes confusing when there are two ways to change the value... Will keep working on a solution

**Comment by mkllnk** [comment]
@yukoosawa 

Yes, both is possible in the same shopfront. And you can't put a max value in if you haven't added a min value. That's a technical restriction at the moment so it would be nice if the design could support it but for now we can assume that people need to add the product first and then they can choose to set a higher value.

So we could keep the Add button. And we could keep the plus/minus buttons. And in addition to the plus/minus buttons we could have a second set of plus/minus buttons for extra quantity?

For example, instead of saying that you want 2 but are able to take 3, you could add 2 and mark +1 extra.

**Comment by mkllnk** [comment]
@daniellemoorhead @yukoosawa I would like to request a little change in the design to make it technically simpler. It's quite complex to evaluate if the product description fits into the line or not because it depends on the exact screen size. And it can change if people resize the window. It's easy to show an ellipsis at the end when it overflows and it's very easy to make a click on the description always open the modal. But displaying a separate link only when it overflows is difficult.

My version opens the product model when clicking on any product description:
![Screenshot from 2020-04-21 15-02-41](https://user-images.githubusercontent.com/3524483/79827286-48c56e00-83e1-11ea-884c-0ed1d7481201.png)

Is that okay?

**Comment by mkllnk** [comment]
@yukoosawa What do you think about the animation when hovering over a product image?

Image in the middle is hovered:
![Screenshot from 2020-04-21 16-44-34](https://user-images.githubusercontent.com/3524483/79833904-816c4400-83ef-11ea-881f-e8743350ae6a.png)

That's still the old brick red and I find it quite ugly in general. Since the hovering has no use on mobile and the desktop version still has the pointer cursor, I would like to get rid of it.

**Comment by yukoosawa** [comment]
> @daniellemoorhead @yukoosawa I would like to request a little change in the design to make it technically simpler. It's quite complex to evaluate if the product description fits into the line or not because it depends on the exact screen size. And it can change if people resize the window. It's easy to show an ellipsis at the end when it overflows and it's very easy to make a click on the description always open the modal. But displaying a separate link only when it overflows is difficult.
> 

@mkllnk Yes I'm ok with this. It's hard to tell from the screenshot (and not all the UI updates are in as yet) but as long as the user can still easily click/tap on the Producer link and the Price Breakdown icon (so hit / mobile tappable areas are maintained) then I'm fine with the product modal being triggered from the description.

Thank you for following up!

**Comment by yukoosawa** [comment]
> @yukoosawa What do you think about the animation when hovering over a product image? 
> That's still the old brick red and I find it quite ugly in general. Since the hovering has no use on mobile and the desktop version still has the pointer cursor, I would like to get rid of it.

@mkllnk Yes agree we can remove the brick-red overlay! I'm also thinking we should remove the icon too. Without the coloured overlay on hover it will be difficult to read over the image -- and I think that style of icon to enlarge is a little dated now :)

**Comment by yukoosawa** [comment]
@mkllnk A few more questions about bulk ordering!
- Is bulk (min/max) applied at a product level? Or can individual variants associated with a product be bulk or regular?
- Is bulk 'max' specified by the shop/hub? Can it be?

**Comment by daniellemoorhead** [comment]
@yukoosawa the min/max is applied at a product level, when you create the product there is an option of "group buy options" and you set the bulk unit size.

<img width="744" alt="Screen Shot 2020-04-27 at 8 39 03 pm" src="https://user-images.githubusercontent.com/10949052/80363161-280c8500-88c7-11ea-99f1-07dc31437b8c.png">

[As the guide says](https://guide.openfoodnetwork.org/basic-features/products-1/group-buy-for-bulk-ordering), you set the total units required for the bulk purchase like so:
<img width="604" alt="Screen Shot 2020-04-27 at 8 40 45 pm" src="https://user-images.githubusercontent.com/10949052/80363328-6c982080-88c7-11ea-936e-fa8e29d94440.png">

There's no max, the shop just adjusts everyone's orders to reach the total units required. You can read more in the guide about that.

**Comment by daniellemoorhead** [comment]
Oh, and:

>@daniellemoorhead I updated the PR and fixed all the easy stuff. Just a note on the active property labels: In production, these properties have descriptions and they pop up as a tooltip when you hover or tap on mobile. That's why they are active. But even without tooltip, they appeared active which I now fixed. I removed the darker border on hover completely but the pointer cursor is still displayed if there is a tooltip. I reckon that the tooltip is quite important to explain what chemical-free or organic really mean.

This is a fine solution, we're pretty sure anecdotally that hardly anyone uses the description field, so this solution works fine 😄
