### ISSUE TITLE
'add distributor' menu is showing all hubs I manage, not filtering by P-OC of Coordinator

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#460]
![image](https://cloud.githubusercontent.com/assets/2911176/6933839/ea9df668-d877-11e4-8a24-7b583344701e.png)

**Comment by kirstenalarsen** [comment]
sally - can you check if you can recreate this in a new order cycle, if new order cycle is correct can close this issue

**Comment by sstead** [comment]
Looks fine, I'll close this issue. I checked, and when I made a new order cycle, I could only select distributors who had P-OC with the coordinator, not a distributor that the coordinator managed (without P-OC).
