### ISSUE TITLE
[mobile ux] 6. Search and filter products in shop

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4601]
## What is the problem we are solving 
The filter design solution is very clunky, displays badly, and doesn't allow for sub-categories or more complex filter hierarchies. Search is fine, but if we don't change the way it looks / interacts inline with the rest of the design it will look strange.

## Success factors = expected outcome 
- [ ] Filters will be handled in a way that allows for their future expansion.
- [ ] Section will fit in with the new design

## Design overview
**_Mobile_**
![Mobile: Shop - Filters](https://user-images.githubusercontent.com/19785399/72494561-3a6c2280-37f2-11ea-9cb7-9ea5eb0b8f10.png)

**_Tablet_**
![Tablet: Shop - Filters](https://user-images.githubusercontent.com/19785399/72494531-258f8f00-37f2-11ea-8989-1670ff78f2f1.png)

**_Desktop_**
![Desktop: Shop - Filters](https://user-images.githubusercontent.com/19785399/72494603-6a1b2a80-37f2-11ea-94b9-6a00f0894810.png)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

**Comment by daniellemoorhead** [comment]
Hey @Matt-Yorkley the epic never moves out of the In Dev column, only the stories. Once all the stories are through to done we move the epic to closed. So I've put this back in the in dev column again.

![](https://66.media.tumblr.com/ebf7018b54ea636973b6acb2f9c7883d/eeb993b946a11230-57/s500x750/d550163eb2f4e6d74e75753099239100b66184e5.gif)

**Comment by daniellemoorhead** [comment]
Testing notes for this: https://docs.google.com/document/d/1MjZ2zvcuilWnvrxXJkWkrvMjuB5cyMO1EXHqtPH1LYk/edit?usp=sharing

**Comment by Matt-Yorkley** [comment]
Are we good to close this epic now @daniellemoorhead ?

**Comment by daniellemoorhead** [comment]
No @Matt-Yorkley as that issue with the iOS keyboard is still open and needing to be fixed.

**Comment by daniellemoorhead** [comment]
You're welcome to remove yourself from the epic, I'm going to see if I can find some help from devs I work with on the other job.

**Comment by daniellemoorhead** [comment]
@yukoosawa did you want to do a design sweep on the search and filters changes? You'd had a good look at them when we tested the branch, so I am thinking probs not, but putting it out there in case you did want to 😄

**Comment by yukoosawa** [comment]
@daniellemoorhead If the sweep can wait until the weekend then I'll do another pass (:zany_face:) but if you need to get it into prod asap then best not to wait for me!

**Comment by daniellemoorhead** [comment]
It's already on production after we tested the branch so it's easy for you
to test it because the changes are live :)

**Comment by daniellemoorhead** [comment]
I'm going to call this epic done, as it was thoroughly tested by Yuko during development and I'm confident the design is good enough for now.
