### ISSUE TITLE
[mobile ux] Clear button in search field

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4602]
## In a feature branch or master?
Search & Filter feature branch 

## Description
**- As a:** shopper
**- On page:** shop product search
**- I want to be able to do:** clear the search field with minimal clicks

## Acceptance Criteria & Tests

Currently:
- To clear the search on mobile you have to click into the search field and then delete the search term yourself (either highlight the whole thing and hit delete, or hit delete per character)

Desired behaviour:
- [ ] When you click in the search field the search copy is highlighted and a clear button appears.
- [ ] Click on the icon and the copy clears
- [ ] User can use the browser select / select all / etc functionality if they choose to click on the text to edit, rather than using the clear button.
- [ ] Remove the awkward field resizing that currently happens in production (see attached screen recording below).
- [ ] Fine to use icon in OFN font/SVGs if easier
![Screen Shot 2020-01-08 at 10 50 23 PM](https://user-images.githubusercontent.com/19785399/72037374-e69a9000-326b-11ea-898d-4ed72be00be1.png)

Example provided by Danni:
![IMG_CA8DA07AEC28-1](https://user-images.githubusercontent.com/10949052/71058732-e9e2b480-21b4-11ea-9272-0e7b7b5646f9.jpeg)

### **HOW IT SHOULD LOOK**
![Mobile: Shop - Search Clear Field@1x](https://user-images.githubusercontent.com/19785399/72494900-51f7db00-37f3-11ea-8712-28c5e3d0c14e.png)

**Comment by yukoosawa** [comment]
@daniellemoorhead Adding an updated design here (and in Zeplin).

As part of this ticket, can we remove the awkward field resizing that currently happens in production (see attached screen recording below).

And yes you can use any icon, even this one that should be included in the OFN font/SVGs:
![Screen Shot 2020-01-08 at 10 50 23 PM](https://user-images.githubusercontent.com/19785399/72037374-e69a9000-326b-11ea-898d-4ed72be00be1.png)

### **HOW IT SHOULD LOOK**
![Mobile: Shop - Search Clear Field@1x](https://user-images.githubusercontent.com/19785399/72036848-19dc1f80-326a-11ea-80f7-ba25595cb6ab.png)

### **FIELD RESIZING WACKINESS**
(Had to zip the video as github says NO to videos!)
[OFN-20200108-mobile-search-field-resize.mov.zip](https://github.com/openfoodfoundation/openfoodnetwork/files/4038531/OFN-20200108-mobile-search-field-resize.mov.zip)

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley this doesn't work on iPhones....I couldn't get the recording I did on my phone to embed on here or the testing notes so I zipped it and added it here. You can see the following things in this:

- [ ] the zoom issue explained in #4604 
- [ ] when I enter the search term and hit search, the keyboard doesn't disappear by itself.
- [ ] the placement of the x is not in the actual search box
- [ ] when I click back into the search field, and then hit the x the term clears but the focus is no longer on the search field. If I'm clicking in the field and then hit the x then I'm expecting to change the search term.

[RPReplay_Final1588335979.MP4.zip](https://github.com/openfoodfoundation/openfoodnetwork/files/4564130/RPReplay_Final1588335979.MP4.zip)

**Comment by Matt-Yorkley** [comment]
> some weird UX problem that only applies to iPhones

![](https://media.giphy.com/media/Fjr6v88OPk7U4/giphy.gif)

I'll see what I can do... :sweat_smile:

**Comment by Matt-Yorkley** [comment]
P.S @daniellemoorhead is that screen capture from the feature branch? It looks like there's some bits missing (the search box placeholder text was definitely changed, but it's unchanged there...?)
