### ISSUE TITLE
[mobile ux] Restyle search + filter section on shop tab

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4604]
## In a feature branch or master?
Search & Filter feature branch 

## Description
**- As a:** enterprise
**- On page:** my shopfront
**- I want to be able to do:** have a design for search and filter that matches the rest of the new design

## Acceptance Criteria & Tests
**HOW IT LOOKS NOW**
Mobile
<img width="476" alt="Screen Shot 2019-12-18 at 4 19 31 pm" src="https://user-images.githubusercontent.com/10949052/71059988-6cb93e80-21b8-11ea-9983-f20e65014b3c.png">
Tablet
<img width="728" alt="Screen Shot 2019-12-18 at 4 20 05 pm" src="https://user-images.githubusercontent.com/10949052/71059994-6fb42f00-21b8-11ea-824d-70b48d3a4048.png">
Desktop
<img width="949" alt="Screen Shot 2019-12-18 at 4 20 30 pm" src="https://user-images.githubusercontent.com/10949052/71059996-70e55c00-21b8-11ea-9d20-7a3629bf84d9.png">

**HOW IT SHOULD LOOK**
Mobile
<img width="229" alt="Screen Shot 2019-12-18 at 4 16 47 pm" src="https://user-images.githubusercontent.com/10949052/71060043-8c506700-21b8-11ea-99e6-b01484eee4bf.png">
Tablet
<img width="468" alt="Screen Shot 2019-12-18 at 4 17 34 pm" src="https://user-images.githubusercontent.com/10949052/71060048-8fe3ee00-21b8-11ea-8d5f-bc92393666cb.png">
Desktop
<img width="778" alt="Screen Shot 2019-12-18 at 4 17 58 pm" src="https://user-images.githubusercontent.com/10949052/71060095-b570f780-21b8-11ea-9ce9-d84856b84f61.png">

- [ ] Search field hint text reduced to accommodate 320px (small) devices.
- [ ] On hover (desktop) state is darker grey (see states in Zeplin).

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

--> CSS

**Comment by daniellemoorhead** [comment]
Hey @Matt-Yorkley this one and #4603 are in code review, but you've merged the PR into the branch. Where shall we put these 2 issues, shall they move to test ready and I'll start testing the branch?

**Comment by Matt-Yorkley** [comment]
I think once these other 2 PRs are reviewed and merged we can test the whole branch together.

**Comment by sigmundpetersen** [comment]
So we can close this and #4603 then?

**Comment by daniellemoorhead** [comment]
@yukoosawa what does this mean? I looked in zeplin but couldn't see what you meant:

>- [ ] On hover (desktop) state is darker grey (see states in Zeplin).

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley this isn't working on iPhones:

>- [ ]  Search field hint text reduced to accommodate 320px (small) devices.

You can see it by using browserstack, was the same on both the iPhone 8/safari and my 6s / Chrome.

**Comment by daniellemoorhead** [comment]
Also, the search bar on iPhones is doing the same bad zoom action that it used to do before @luisramos0 fixed it in #4535. This'll need to be fixed again.

**Comment by Matt-Yorkley** [comment]
I think I fucked up a merge conflict there during a rebase :see_no_evil: 

I'll take a look and get it fixed :+1:
