### ISSUE TITLE
[mobile ux] Restyle zero search results page

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4605]
## In a feature branch or master?
Search & Filter feature branch 

## Description
**- As a:** enterprise
**- On page:** my shopfront search
**- I want to be able to do:** have the no results page match the new design of the rest of the shopfront

## In/out of scope for phase 1
Out: Specifying total number of results for a search query
Out: Providing a 'Did you mean...' for common typos/misspellings
Out: Providing a related browse category suggestion like 'Dairy'

## Acceptance Criteria & Tests

Key changes / call outs
- [ ] Present a prominent no results message
- [ ] Present a prominent way to clear the search results (@yukoosawa keep in mind #4602 alongside of this)

**HOW IT LOOKS NOW**
Mobile
<img width="477" alt="Screen Shot 2019-12-18 at 5 10 36 pm" src="https://user-images.githubusercontent.com/10949052/71060374-68415580-21b9-11ea-8c44-ff86dd31d7ac.png">

Tablet
<img width="705" alt="Screen Shot 2019-12-18 at 5 10 18 pm" src="https://user-images.githubusercontent.com/10949052/71060379-6a0b1900-21b9-11ea-8a89-e0824b46b335.png">

Desktop
<img width="944" alt="Screen Shot 2019-12-18 at 5 10 05 pm" src="https://user-images.githubusercontent.com/10949052/71060369-67102880-21b9-11ea-9ebd-435d52df1da7.png">

**HOW IT SHOULD LOOK**
**_Mobile_**

![Mobile: Shop - 0 Results@1x](https://user-images.githubusercontent.com/19785399/72495905-04c93880-37f6-11ea-81a1-47807f2260a6.png)

**_Tablet_**

![Tablet: Shop - 0 Results](https://user-images.githubusercontent.com/19785399/72495912-098dec80-37f6-11ea-8584-131f525247d0.png)

**_Desktop_**

![Desktop: Shop - 0 Results](https://user-images.githubusercontent.com/19785399/72669174-b639bb00-39fc-11ea-889c-734914b1b041.png)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

Acceptance criteria:
- [ ] Restyled to look like screenshot
- [ ] Clear search function takes user back to full list of products

**Comment by yukoosawa** [comment]
@daniellemoorhead Adding an updated design here (and in Zeplin).

Assuming smart suggestions are out of scope, such as:
- Providing a 'Did you mean...' for common typos/misspellings
- Providing a browse category like 'Dairy'

### **HOW IT SHOULD LOOK**
Mobile
![Mobile: Shop - 0 Results@1x](https://user-images.githubusercontent.com/19785399/72037554-a982cd80-326c-11ea-8aad-8d2217c8e07d.png)

Tablet
![Tablet: Shop - 0 Results](https://user-images.githubusercontent.com/19785399/72038149-7c371f00-326e-11ea-837c-509a21950825.png)

Desktop
![Desktop: Shop - 0 Results](https://user-images.githubusercontent.com/19785399/72038163-8527f080-326e-11ea-8370-591b78cb9a75.png)

**Comment by daniellemoorhead** [comment]
This is good to go, so closing

**Comment by daniellemoorhead** [comment]
Seems @yukoosawa was a little tougher on all the things than I was - see testing notes for changes required.

https://docs.google.com/document/d/1MjZ2zvcuilWnvrxXJkWkrvMjuB5cyMO1EXHqtPH1LYk/edit?usp=sharing
