### ISSUE TITLE
[mobile ux] Style shop menu bar

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4612]
## Description

**- As a:** enterprise
**- On page:** shopfront
**- I want to be able to do:** see the shop menu bar in the new design

## Acceptance Criteria & Tests
**HOW IT LOOKS NOW**
Mobile
![Screen Shot 2019-12-13 at 3.11.26 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/daf0f4f0-78f5-45d9-ab4e-387d70adcbd9)
Tablet
<img width="739" alt="Screen Shot 2019-12-13 at 3 40 22 pm" src="https://user-images.githubusercontent.com/10949052/70769774-f59e3780-1dbe-11ea-98ca-3dbb593a3099.png">
Desktop
<img width="1222" alt="Screen Shot 2019-12-13 at 3 40 34 pm" src="https://user-images.githubusercontent.com/10949052/70769792-03ec5380-1dbf-11ea-80b6-469575a5223a.png">

**HOW IT SHOULD LOOK**
Mobile
![Screen Shot 2019-12-13 at 2.51.11 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/e5d1f8bc-b14c-457a-807c-bc61521e8efd)

Tablet
<img width="634" alt="Screen Shot 2019-12-13 at 3 26 31 pm" src="https://user-images.githubusercontent.com/10949052/70769698-ad7f1500-1dbe-11ea-94e5-08867655a487.png">

Desktop
<img width="784" alt="Screen Shot 2019-12-13 at 3 27 04 pm" src="https://user-images.githubusercontent.com/10949052/70769743-d30c1e80-1dbe-11ea-9d25-c432dd672308.png">

1. Open a shop on a range of mobile devices (tip: use browserstack)
2. Check that the tabs are laid out the same as the screenshot above.
3. Check that the groups tab only shows if the shop is part of a group.
4. Check that the home tab only shows when the shop has a shopfront message.
5. Check that when there is no shopfront message, the default tab to open is shop.
6. Check that when there is a shopfront message, the default tab to open is home.
7. Check that the underline displays on the tab that is open, for every tab.

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

--> CSS

**Comment by daniellemoorhead** [comment]
Closing this, will follow the required changes in #4764 and in test doc https://docs.google.com/document/d/1WpJmNwuYUC3V4rqf7MQEWCmh723q9FI41YnU4F9mX1Y/edit?usp=sharing
