### ISSUE TITLE
as a Hub in someone else's OC - can't see exchanges I need to see

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#463]
as Kirsten@eaterprises, I manage Ben's Coop

3 producers have given me P-OC
![image](https://cloud.githubusercontent.com/assets/2911176/6936848/13cc6ec8-d8a2-11e4-9da3-c3c9e8e27a29.png)

and my mate Bill, at Bill's coop has added me to OC (Bill's view, via kirsten.larsen76)

![image](https://cloud.githubusercontent.com/assets/2911176/6936844/068a1d82-d8a2-11e4-9dac-05cb504f8717.png)

but when I go and look at it, I can't see the incoming exchanges from Producers where I have P-OC, or the Products already in my existing exchange

![image](https://cloud.githubusercontent.com/assets/2911176/6936866/75080972-d8a2-11e4-841d-f30751650aaf.png)

**Comment by sstead** [comment]
Yep, I experienced same thing.

**Comment by kirstenalarsen** [comment]
outgoing exchanges now correct. but I think I shouldn't be able to edit the incoming ones . . because if I remove a product from the incoming exchange then it removes it from the whole OC

![image](https://cloud.githubusercontent.com/assets/2911176/7056341/4266e4f6-de8e-11e4-82ff-8cd8b68ba473.png)
