### ISSUE TITLE
Release 2.6.8

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4636]
Steps: 

- [x] Include translations
- [x] Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-8c1e07e7b700eb3c1d97
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1080
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

**Comment by RachL** [comment]
Nothing here that does not already exist in production I believe this is ready to go :-) https://docs.google.com/document/d/1RAVODjNyM4hDqIEURj5WMnSR-LWCfMScXmG090mh2lE/edit#
