### ISSUE TITLE
Cannot add manager to Stroudco enterprise

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#464]
After @aidandunsdon uploaded imported database into UK staging, @NickWeir63 wanted access to Stroudco. I tried entering "nick" and his full email in the "Add a manager" dropdown on the Enterprise > Users tab, but it just showed "searching" icon and did not find any user.

**Comment by aidandunsdon** [comment]
@pmackay That's because there's no user nick - manager is same as old system i.e info@stroudco.org.uk . There is also a user for carol and matillda  @NickWeir63 can these queries go through me during this initial testing to save time thanks

**Comment by pmackay** [comment]
OK. However we added a new account for Nick, so what is required for a new
user to be able to see it?
