### ISSUE TITLE
[Spree 2.1] Adapt PaypalExpress gem

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4645]
The paypal gem is currently disabled, and can't be installed with bundler. The `2-1-stable` branch explicitly requires `spree_core ~> 2.1.1`, but we are using `2.1.0`.

See: https://github.com/openfoodfoundation/better_spree_paypal_express/blob/76e113d61cb1a24645f9b0975a472f03cd0fc2a7/spree_paypal_express.gemspec#L26

A large number of the remaining failing tests are related to this.

**Comment by luisramos0** [comment]
Some quickfixes are in the branch, they need to be reverted/fixed:
      - file spec/controllers/spree/paypal_controller_spec.rb deleted
      - file app/controllers/spree/paypal_controller_decorator.rb  deleted
      - the import spree_paypal_express is commented in app/assets/javascripts/admin/all.js
      - the gem spree_paypal_express is commented in the Gemfile

**Comment by luisramos0** [comment]
spree 2.1.1 was released 2 days after spree 2.1.0 and just gemfile differences, so we may just move to 2.1.1 immediately.
https://github.com/spree/spree/compare/v2.1.0...v2.1.1

I'll give it a try.

**Comment by luisramos0** [comment]
At the same time looks like paypal gem 2-0-stable and 2-1-stable are exactly the same, so first, I'll try to run everything with the existing paypal 2-0-stable gem.

**Comment by luisramos0** [comment]
note for the future, this is exactly what we did:
"patched better_spree_paypal_express 2-1-stable to point to spree 2.1.0 instead of 2.1.1"

**Comment by Matt-Yorkley** [comment]
In more detail:

- Copied `2-1-stable` (contains upstream changes for Spree 2.1) to new `2-1-0-stable` branch
- Cherry-picked two OFN commits from previous `2-0-stable` branch
- Changed restriction in gemspec from `spree_core ~> 2.1.1` to `spree_core ~> 2.1.0`
