### ISSUE TITLE
Editing Basket Result in 500 Error (Slug)

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4662]
## Description

From the Edit Basket page I have the opportunity to edit the quantity of (and remove) items within my basket.

This functionality works however the user experiences a 500 error (slug) on attempt. When you press back you are returned to the basket with the correctly updated contents.

## Expected Behavior

The item qty should be updated without the user experiencing an error

## Actual Behaviour

When I press Update I see the slug.
When I press the Rubbish Bin (Delete item) I see the slug.

## Steps to Reproduce

1. Create a basket
2. Go to Edit Basket
3. Change the Qty of items or remove an item from the basket
4. Suffer the slug
5. Press Back in the browser and see that the update has actually happened

## Workaround

The above describes the workaround. However this workaround is unacceptable as this is a customer facing page.

## Severity

bug-s3: a feature is broken but there is a workaround
I would say that this is s3 due to the fact that it is customer facing.

## Your Environment

* Version used: 2.6.8 UK
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu

## Possible Fix

Whatever it is, start by reproducing the failure in any existing (or new) feature spec. We thought they had this case covered.

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Map and deleting items from basket](https://trello.com/c/hamvC8Sx/613-map-and-deleting-items-from-basket)

**Comment by RachL** [comment]
I stop testing these two during release testing because I thought it was covered by automated tests... :-( ping @sauloperez 

I wonder if we shouldn't treat this as an s2. Slug for customers is really bad...

**Comment by luisramos0** [comment]
I dont think this is generic. must be something specific to the product or OC you are using for the test. can you add details about OC, product and fees?

**Comment by lin-d-hop** [comment]
Are you sure it's not generic? This has been reported multiple times and I've always been able to replicate with any basket..... I've just been slow to create the issue :woman_facepalming:

**Comment by sauloperez** [comment]
I thought it was covered yes. There might be a tiny difference on the steps. Did someone find a bugsnag notification we attach here? That would help a lot identify the root cause.

In any case, we must fix the automated test when fixing this. Adding it in the description.

**Comment by lin-d-hop** [comment]
Probably a duplicate of: 
https://github.com/openfoodfoundation/openfoodnetwork/issues/4581

**Comment by luisramos0** [comment]
hmm.. if it's a duplicate it will never happen again.

I cant replicate this in master locally now. I can edit the cart normally.

I am not sure what we should do with this issue.

**Comment by lin-d-hop** [comment]
I'm just going to close it :trollface:
