### ISSUE TITLE
Style the 'Home' tab

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4670]
## Description
**- As a:** enterprise
**- On page:** home tab on my shopfront
**- I want to be able to do:** have my content look like the new design

## Acceptance Criteria & Tests

Key changes / call outs
- [ ] Remove green/coloured background and border
- [ ] All other text styling to remain as is, as customers currently use a wysiwyg to make these oh-so-pretty!

**HOW IT LOOKS NOW**
<img width="1263" alt="green-box1" src="https://user-images.githubusercontent.com/10949052/72229361-22ce4780-3602-11ea-9d73-3e9a1afaac7f.png">
<img width="1264" alt="green-box4" src="https://user-images.githubusercontent.com/10949052/72229363-24980b00-3602-11ea-87f5-7c7a033925f0.png">
![green-box3](https://user-images.githubusercontent.com/10949052/72229365-2661ce80-3602-11ea-8d5c-94da1b9b8a08.png)
<img width="1263" alt="green-box2" src="https://user-images.githubusercontent.com/10949052/72229367-2792fb80-3602-11ea-8f71-c3a0c6524174.png">
<img width="1264" alt="green-box5" src="https://user-images.githubusercontent.com/10949052/72229369-295cbf00-3602-11ea-9db5-17846db6e159.png">

**HOW IT NEEDS TO LOOK**
**_Mobile_**

![Mobile: Shopfront - Home 5 tabs](https://user-images.githubusercontent.com/19785399/72492383-faee0800-37ea-11ea-9e09-b4cae44f6e05.png)

**_Tablet_**

![Tablet: Shop - Home](https://user-images.githubusercontent.com/19785399/72670213-16cef500-3a09-11ea-9034-af252dcc5a9f.png)

**_Desktop_**

![Desktop: Shopfront - Home](https://user-images.githubusercontent.com/19785399/72492609-d47c9c80-37eb-11ea-89cc-eda68035b1ae.png)

**Comment by Matt-Yorkley** [comment]
Closed by #4655
