### ISSUE TITLE
[mobile ux] Remove icons from categories

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4671]
## In a feature branch or master?
This can be merged directly to master 🎉 

## Description
**- As a:** instance manager
**- On page:** product categories
**- I want to be able to do:** have consistency with my categories and the way they display to users

## Acceptance Criteria & Tests
**Current behaviour**
Small icons display beside categories for _some_ instances
<img width="146" alt="Screen Shot 2020-01-13 at 12 47 52 pm" src="https://user-images.githubusercontent.com/10949052/72229466-f1a24700-3602-11ea-86a1-94431342e101.png">

**Changed behaviour**
Remove these icons so that there is consistency, no categories have them. 

Reason: as we add / remove / change categories we don't have icons to match them.

**Comment by daniellemoorhead** [comment]
I'm pretty sure all these are gone now. Is that correct @mkllnk and @Matt-Yorkley, they disappeared from the product list view and the filter view?

**Comment by mkllnk** [comment]
Yes, my pending pull request removes those items from the product listing.
