### ISSUE TITLE
Remove N+1 queries detected by Bullet

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4673]
### What we should change and why (this is tech debt)
We should add eager loading to avoid N+queries and remove unused eager loading.
Bullet was added to CI in #4475 and the output of it's run on 2020-01-14 is stored here:
https://gist.github.com/luisramos0/f044fd8e0f381c0793a995f7d373732e

There are a lot of entries but also a lot of repetition. Repeated entries are probably the best candidates to be addressed first.

For example this entry appears 51 times in the build:
```
Unused Eager Loading detected
  Spree::Order => [:adjustments]
  Remove from your finder: :includes => [:adjustments]
```

This other one appears 90 times in the file!
```
GET http://127.0.0.1:43198/enterprise-52/shop
Need Counter Cache
  Enterprise => [:shipping_methods]
N+1 Query detected
  Enterprise => [:shipping_methods]
  Add to your finder: :includes => [:shipping_methods]
N+1 Query method call stack
  /home/runner/openfoodnetwork/app/models/enterprise.rb:341:in `ready_for_checkout?'

```

If these entries come up many times in this log, it's because it is a code path crossed many times in the specs, and that probably means it is something that is executed a lot of times in production.

### Context
This came up in #4475 as part of the performance improvement epics recently addressed.

### Impact and timeline
This is not the top priority but it represents a really good and rather easy way to improve performance of the app in general. Defenetely something we should address at some point, for example, the next time we want to work on the app's overall performance.

**Comment by Matt-Yorkley** [comment]
If anyone picks this up again (we still have really basic N+1s all over the app) I found another nice option for usage. Add the bullet gem, then add this to `environments/development.rb`:
```ruby
config.after_initialize do
  # To use, start a rails server with: `ENABLE_BULLET=true rails s`
  if Rails.env.development? && ENV.fetch('ENABLE_BULLET', nil)
    Bullet.enable = true
    Bullet.rails_logger = true
    Bullet.alert = true # Display bullet results immediately in a Javascript alert
  end
end
```

**Comment by RachL** [comment]
I'm closing this epic as there are no issues attached.
