### ISSUE TITLE
[mobile ux] restyle product listing modal

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4684]
## In a feature branch or master?
This can be merged straight to master 🎉 

## Description

**- As a:** enterprise
**- On page:** product listing modal
**- I want to be able to do:** the design to match the rest of my shop

## Acceptance Criteria & Tests
Key changes / call outs
- [ ] Modals should present a clear 'outside area' where the user can tap/click to close the modal (see designs for mobile / tablet / desktop padding)
- [ ] As per current production, Producer Name **IS NOT** a clickable link so users don't let lost in a myriad of modals
- [ ] Remove product category
- [ ] Display product property(s) in the smaller size as per new shop product listing
- [ ] For modals which require scrolling (uncommon but possible, esp. on mobile) display a clear 'close' button at the bottom of the modal
- [ ] Modals should be centered in the viewport (currently in mobile they're squished to the top)
- [ ] Remove grey border around images

**TESTING**
_No text or images_
Basil
https://openfoodnetwork.org.au/somerset-heritage-produce/shop

_Variable height in images_
Spitfire Wholewheat Bread Flour
https://openfoodnetwork.org.au/woodstock-flour/shop

_Lots of text_
Pelletised Green Organic Compost
https://openfoodnetwork.org.au/elmore-compost-and-organics/shop

**HOW IT LOOKS NOW**
Mobile
![IMG_5731](https://user-images.githubusercontent.com/10949052/72573805-f9236200-391a-11ea-936b-84b2f8a57ac2.PNG)
Tablet
<img width="578" alt="Screen Shot 2020-01-17 at 11 18 28 am" src="https://user-images.githubusercontent.com/10949052/72573873-30920e80-391b-11ea-8307-4ed2e39e6ad9.png">

Desktop
<img width="818" alt="Screen Shot 2020-01-17 at 11 18 12 am" src="https://user-images.githubusercontent.com/10949052/72573875-32f46880-391b-11ea-96ea-cc9b873bcd79.png">

**HOW IT SHOULD LOOK**
**_Mobile_**
![Mobile: Product Detail Modal](https://user-images.githubusercontent.com/19785399/72585646-d5c9ca00-38bc-11ea-8a71-2c26671156f9.png)

_Scrollable Modal_
![Mobile: Product Detail Modal Scroll](https://user-images.githubusercontent.com/19785399/72585652-db271480-38bc-11ea-9104-df217865afbd.png)

**_Tablet_**
![Tablet: Shop - Product Detail Modal](https://user-images.githubusercontent.com/19785399/72585551-897e8a00-38bc-11ea-8ff8-a0921d0e2531.png)

_Increased amount of copy (atypical)_
![Tablet: Shop - Product Detail Modal Large](https://user-images.githubusercontent.com/19785399/72585558-8e433e00-38bc-11ea-8196-2dd9655d1b67.png)

**_Desktop_**
![Desktop: Product Detail Modal](https://user-images.githubusercontent.com/19785399/72585586-a915b280-38bc-11ea-9d7a-fcf635339c74.png)

_Increased amount of copy (atypical)_
![Desktop: Product Detail Modal Large](https://user-images.githubusercontent.com/19785399/72585605-b16ded80-38bc-11ea-9218-61dcb6a6ef19.png)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

**Comment by luisramos0** [comment]
Hello, in the description I see "Remove product category"
but in zeplin and in the images the categories are still there... I will assume KEEP.

**Comment by luisramos0** [comment]
This is how it's looking now:
![image](https://user-images.githubusercontent.com/1640378/79694570-ffeaa980-8268-11ea-9ffe-18902c1a62a5.png)

Is changing the close icon on the top right part of this issue? I am not sure how to change it... ofn-i_009-close

**Comment by yukoosawa** [comment]
@luisramos0 Yes your 'edit' thinking is correct! I believe the icon is currently part of an OFN font created before I joined :) Unsure as to who implemented it, and what it would take to change.

Can you add a screenshot of what it would look like with the current icon... Perhaps I can live with it :upside_down_face:

**Comment by luisramos0** [comment]
Hello @yukoosawa thanks for your feedback.

This is the current icon (I can improve the positioning):
![image](https://user-images.githubusercontent.com/1640378/79696397-66c19000-8274-11ea-877a-6b84a187e198.png)

**Comment by yukoosawa** [comment]
Hi @luisramos0!

If we could tweak the positioning (top) that would be great! Looking at the font/close icon in production now, am thinking we can tweak it as follows to get it closer:

background-color: rgba(0,0,0,0.5);
color: #fff
font-size: 1.5rem

![Screen Shot 2020-04-19 at 2 44 40 PM](https://user-images.githubusercontent.com/19785399/79696712-66150380-824c-11ea-86c4-61a2fdd44446.png)

And if you need a hover colour, we could update the background-color: to #0096ad. The X can stay white.

I should probably check where else that class is used... make sure I'm not suggesting something that will break stuff elsewhere :sweat_smile:

**Comment by luisramos0** [comment]
Nice, thanks @yukoosawa that css works!

I finished this PR and then went to test it and I realized I was changing all modals in the FrontOffice :blush: 
For example, the "outside area" around the modal on mobile, is that not something we want to have on all modals? The modals I am aware of are product (this issue), login, registration and cookies policy.
Login would move from 
![image](https://user-images.githubusercontent.com/1640378/80129840-8f58cb00-858f-11ea-9d23-5b53c5e0918d.png)
to
![image](https://user-images.githubusercontent.com/1640378/80129864-9a136000-858f-11ea-8bb6-572b35374cfb.png)

OR
sign up from
![image](https://user-images.githubusercontent.com/1640378/80130078-f4acbc00-858f-11ea-9d22-f3aee73118f2.png)

to
![image](https://user-images.githubusercontent.com/1640378/80130099-fb3b3380-858f-11ea-8f95-939ff93a7368.png)


the registration:
![image](https://user-images.githubusercontent.com/1640378/80130358-579e5300-8590-11ea-83eb-a0d013c39dca.png)

to
![image](https://user-images.githubusercontent.com/1640378/80130379-6258e800-8590-11ea-953a-a81ef9efae78.png)


this last one needs some extra padding I think.

Is this something we want to do now?
If we dont do this now I'll have to duplicate quite a few styles (old modals vs new modals).

**Comment by daniellemoorhead** [comment]
@luisramos0 I'm a bit confused, because you're "from" screenshots (which have orange buttons) look like the new version and your "to" screenshots (red buttons) look like the old version. Are they in the correct order?

**Comment by daniellemoorhead** [comment]
OK, I looked at my phone and I think the orange buttons are just confused the situation (when did they change?) and the difference is that currently the log in / sign up / register enterprise modals on mobile are flush with the edge of the screen, but in the new version there is a gap. Correct @luisramos0?

If this is correct, then I think the enterprise register form looks terrible (the placement of the blue-lined details header is sub-optimal) but the other modals look fine. 

Will leave @yukoosawa to confirm, but I think as long as we can fix the blue-lined header then I say go with the easier path in terms of dev work.

**Comment by luisramos0** [comment]
yes, correct. for some reason the buttons are orange on staging FR!
ok, as you seem open to it, I'll tweak these views a little and share results here.

**Comment by yukoosawa** [comment]
@luisramos0 cc: @daniellemoorhead Based on the screenshots included here (+ the tweaks already mentioned) I'm ok for the change to ripple out to FrontOffice.

OFN uses too many modals!! For sign up / login it provides some focus for the user, and what we're requesting from the user is short, sweet, and commonly understood. I'm not familiar with the enterprise side of the platform – but if that modal is presenting me a multiple step process which requires scrollbars then :confounded: We could always make the product/producer modals pages with unique URLS :stuck_out_tongue_winking_eye:

And yes I've just figured out I can include emojis so feel it's necessary to include them excessively with all my comments now :tada::smiling_imp::space_invader:

**Comment by daniellemoorhead** [comment]
Am taking the `feedback-needed` label, over to you @luisramos0 👍
