### ISSUE TITLE
[Release Blocker] 500 Error at Checkout

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4689]
## Description

500 error when I click checkout!

I opened a shop (Marsh Goods) with Collection and Delivery, Paypal, Stripe, Cash, two OCs
Added products (Insects, Weeds) to the cart.
When I click "checkout" I get a 500 error

This happens with both products, both OCs.
The other open shop (preexisting) goes to checkout fine.

There might be a mistake with my shopfront creation... But still I want a warning here!

## Expected Behaviour

Being able to perform the fundamental e-commerce function of a purchase

## Actual Behaviour

I can add things to cart but when I click checkout (both via Cart Button and the Cart Screen) I get a 500 error

## Steps to Reproduce

1. Go to Shop - Marsh Goods
2. Add items to cart - Insects, Weeds
3. Click Checkout
4. Death by Slug

## Severity

S2 as this is release testing.

## Your Environment

* Version used: v2.7 FR Staging
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Desktop Ubuntu

**Comment by luisramos0** [comment]
I dont have much time to investigate but form the logs it's a stripe method without enterprise selected (missing preferred_enterprise_id on the stripe payment method)

**Comment by lin-d-hop** [comment]
Ok well this is a bug on many fronts.
1) Even when I removed Stripe as a payment method the problem persists.
2) Everything is connected fine in the backend.

Could this be related to #4606? I used an existing Stripe account that is also connected to other account. Now connected to this account. Does the fix in some way assume that this payment method will not be connected to other enterprises?

**Comment by lin-d-hop** [comment]
@mkllnk I don't suppose you'll have a chance to look on your Monday? This will mean that I can wake up early and finish release testing on my Monday before 8am :-)

Or maybe someone else will get there before...

**Comment by luisramos0** [comment]
still stripe, the payment method cash is type stripe...

I fixed it now:
![Screenshot 2020-01-19 at 19 47 12](https://user-images.githubusercontent.com/1640378/72687338-cd5bd400-3af4-11ea-9efa-d48f49bdbf37.png)
![Screenshot 2020-01-19 at 19 48 32](https://user-images.githubusercontent.com/1640378/72687339-cdf46a80-3af4-11ea-9fe1-bc9b3a2395d1.png)
![Screenshot 2020-01-19 at 19 48 43](https://user-images.githubusercontent.com/1640378/72687340-ce8d0100-3af4-11ea-81ce-4c5cda133be1.png)

**Comment by lin-d-hop** [comment]
That is insanely boring and has really fucked up my schedule :woman_facepalming:

**Comment by lin-d-hop** [comment]
It was also really easy to do and I didn't spot it.
A error here would have saved me a lot...
But since no user has reported it I'm not going to bother opening an issue.

**Comment by luisramos0** [comment]
or lets change the subject and keep this one for it. It's an S4 + very annoying = S3 I think....

**Comment by lin-d-hop** [comment]
Papercut candidate? If adding an error would be easy.

**Comment by lin-d-hop** [comment]
Also, thank you @luisramos0 for pointing out the issue :-)

**Comment by luisramos0** [comment]
I didnt know we would/could put bugs into the papercuts pipe.
size wise this is ok for papercut, yes.

**Comment by lin-d-hop** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/issues/4713
