### ISSUE TITLE
Error when non-admin user accesses Stroudco shop

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#470]
This is shown in the UK staging log when accessing the Stroudco shop when logged in as Nick:

```
ActiveRecord::StatementInvalid (PG::Error: ERROR:  relation "spree_orders" does not exist at character 13
: INSERT INTO "spree_orders" ("adjustment_total", "bill_address_id", "cart_id", "completed_at", "created_at", "currency", "distributor_id", "email", "item_total", "last_ip_address", "number", "order_cycle_id", "payment_state", "payment_total", "ship_address_id", "shipment_state", "shipping_method_id", "special_instructions", "state", "total", "updated_at", "user_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22) RETURNING "id"):
  lib/spree/core/controller_helpers/order_decorator.rb:3:in `current_order_with_scoped_variants'
  app/controllers/enterprises_controller.rb:81:in `reset_order'
```

**Comment by NickWeir63** [comment]
good to skype with you just now.  here are the actions we agreed:  @pmackay will run another deployment to UK staging to see if this completes more cleanly this time and solves the login problems.    @aidandunsdon will look at the database structure and see if the error message above gives any clues as to the login problem.

**Comment by aidandunsdon** [comment]
@pmackay @NickWeir63 @RohanM  - I had quick look. It seems like when a user first logs in, an empty cart order is created in spree_orders. I am guessing that problem might be related to this getting out of sync during the migration though this is a hunch. Unfortunately, I am on leave now for a while but will make it a priority on my return.

**Comment by pmackay** [comment]
Think this was due to an inconsistent database state. Resolved now.

**Comment by aidandunsdon** [comment]
@pmackay Do you know how this was resolved? it seemed to be fixed when I returned from leave. - It seems to occur each time the database is migrated.
