### ISSUE TITLE
[mobile ux] Restyle view cart dropdown in main nav

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4704]
## In a feature branch or master?
View cart feature branch 

## Description
**- As a:** enterprise
**- On page:** main nav cart view
**- I want to be able to do:** have it look like the new design

## Acceptance Criteria & Tests

- [ ] Edit cart and Checkout buttons only at bottom of list, remove top buttons
- [ ] Product single item quantity removed (ie. quantity + total displayed, removed single unit price)
- [ ] Product list restyled
- [ ] Edit cart and Checkout section restyled

**HOW IT LOOKS NOW**
Mobile + Tablet - doesn't display
Desktop
<img width="534" alt="Screen Shot 2020-01-22 at 2 38 56 pm" src="https://user-images.githubusercontent.com/10949052/72863533-0e3a2f80-3d25-11ea-9bb4-2fe7d146d5ac.png">

**HOW IT SHOULD LOOK**
Desktop (only for now)
Note: the zeplin view includes an 'edit cart' button.
![image](https://user-images.githubusercontent.com/2911176/45721963-a5e9b400-bbed-11e8-8e50-989e0926d806.png)

**Comment by Matt-Yorkley** [comment]
@daniellemoorhead @yukoosawa 

I've got this epic mostly done, but there's a coupe of things that need some feedback.

- The "Take me shopping!" button in some of the mockups with an empty cart. Where is it supposed to take the user?
- The current cart has some functionality that isn't covered here: if the user has already placed an order in the selected OC and the OC is still open, the cart will show a list of products that are already ordered, under a subheading: "Already Ordered in this Order Cycle". They can then add more products to the cart, and see both lists. This isn't included in the Zepin designs.

**Comment by Matt-Yorkley** [comment]
Also: the animated CTA on the homepage really messes with the new cart layout. Can we move it to the bottom of the screen? I think it'll be really difficult to fix otherwise...

**CTA at the top:**

![CTA-top](https://user-images.githubusercontent.com/9029026/82730423-d3123200-9cff-11ea-9c0e-eaf6c6d64203.gif)

**CTA at the bottom:**

![CTA-bottom](https://user-images.githubusercontent.com/9029026/82730463-37cd8c80-9d00-11ea-9727-4d50a58fb92b.gif)

Also: the current UX for the CTA displaces the main navigation at exactly the moment the user wants to click links in it (and makes sure they can easily click a different link in the CTA). Maybe that was never a good idea to begin with?

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley the CTA banner is the only place where instances have an opportunity to promote something to their users. I really don't feel comfortable removing it from the site. In Australia we have a call to enterprises to register, and if we didn't have this then the link is wayyyyyy down the bottom of the page and not as easily accessible.

![Screen Shot 2020-05-26 at 4 32 10 pm](https://user-images.githubusercontent.com/10949052/82867640-9009c600-9f6e-11ea-9bbf-d1cb109f06ab.png)

Also, I feel like this is an edge case. If I'm going to look at my cart then I'm going to be in a shop most of the time. In the less likely event that I'm on the homepage and then click on the cart the likelihood of clicking on it before the banner displays is a super small likelihood, is what I'm thinking.

Regardless, what I'm curious about is how many users click on this banner. @RachL do you know if there's a way to check in Matomo? Probably not, right, because we don't have event tracking set up, but thought it worth asking. It would be good to let the data speak around that CTA banner, if there are significant enough clicks from there then we don't lose it but if no one is using it then it's a safer bet to remove it. (Ping @mbudm, would be good to include this in the metrics work you're doing if it ain't already set up).

If we need to keep it, I see there being 2 options:

1. You have the cart view align directly underneath the banner so that it doesn't display over the banner. I imagine this is difficult given you haven't managed to line it up that way and asked to remove the banner. Is there no way to have it display perpetually underneath the nav?

2. We could move the banner to below the main navigation (will need to see how this looks and if it has the same impact) and then the cart will display over the top of it. This version also removes the (rare) annoyance of the top nav moving just as you're about to click on something.

**Comment by daniellemoorhead** [comment]
> The current cart dropdown has some functionality that isn't covered here: if the user has already placed an order in the selected OC and the OC is still open, the cart will show a list of products that are already ordered, under a subheading: "Already Ordered in this Order Cycle". They can then add more products to the cart, and see both lists. This isn't included in the Zeplin designs.

@yukoosawa here's the user flow with this:

**1. You revisit a shop that has an open OC that you've already placed an order in:**

It shows you what you bought previously in the view cart dropdown
![Screen Shot 2020-05-26 at 4 59 43 pm](https://user-images.githubusercontent.com/10949052/82870185-e24ce600-9f72-11ea-96ad-35274e1897d7.png)

And a blue banner displays under the main nav
![Screen Shot 2020-05-26 at 5 02 33 pm](https://user-images.githubusercontent.com/10949052/82870238-f85aa680-9f72-11ea-8fd5-59beb15cb032.png)
![Screen Shot 2020-05-26 at 5 05 12 pm](https://user-images.githubusercontent.com/10949052/82870313-145e4800-9f73-11ea-9037-e289582ba999.png)

------
**2. You add more of the same product to the cart**

It shows the new products in your cart plus the ones already ordered below it.
![Screen Shot 2020-05-26 at 5 00 02 pm](https://user-images.githubusercontent.com/10949052/82870448-525b6c00-9f73-11ea-964a-b395f40c9f60.png)

------
**3. You buy them (note: this is a new order in the system)**
![Screen Shot 2020-05-26 at 5 01 36 pm](https://user-images.githubusercontent.com/10949052/82870531-7323c180-9f73-11ea-9807-1d5550f5b56a.png)

------
**4. You buy another lot of the same product (again, a new order)**
![Screen Shot 2020-05-26 at 5 06 42 pm](https://user-images.githubusercontent.com/10949052/82870605-98b0cb00-9f73-11ea-9443-73b9f652f07e.png)

------
**5. You buy a different range of products(another new order)**
![Screen Shot 2020-05-26 at 5 11 26 pm](https://user-images.githubusercontent.com/10949052/82870972-22f92f00-9f74-11ea-945a-3f49a098ed85.png)

------

So you can see, each time you order the items display as a list down the view cart screen. As noted above, on the orders page you can see they're all separate orders, even though they show up in your view cart screen without the detail around them being separate orders. I guess they infer this, but the fact that the products are repeated down the page for each subsequent purchase, even though they're the same product and in the shoppers mind they bought 8 packs of duck eggs, not 2 and 5 and 1 packs.

![Screen Shot 2020-05-26 at 5 18 54 pm](https://user-images.githubusercontent.com/10949052/82871482-fe518700-9f74-11ea-9762-7012dade5a65.png)

------

So, the constraint is that we can't change the functionality of how changes/additions to orders work, and therefore we just need to know how to display these additional products in the new look cart.

Fun fun :)

**Comment by Matt-Yorkley** [comment]
@daniellemoorhead 

> I really don't feel comfortable removing it from the site

Just to clarify: I'm not suggesting removing the CTA, just moving it to the bottom of the screen instead of the top. It's still be sticky and visible when the users scrolls:

![CTA-bottom](https://user-images.githubusercontent.com/9029026/82878561-ef9aae00-9f3b-11ea-8f97-0598656690eb.gif)

**Comment by daniellemoorhead** [comment]
Can you instead put it under the nav? Like the order success or the blue edit order banner?

**Comment by Matt-Yorkley** [comment]
Well that's another problem right there: we often display those other flash messages on the homepage, underneath the main navigation. It's not easy to make them pay nicely in the same space.

**Comment by daniellemoorhead** [comment]
![](https://i.imgur.com/1KnyV0d.gif)

So to make sure I understand correctly, there are other messages that will display on the homepage under the main nav, yes? Can you tell me what they are?

In terms of your idea, if we were to put it at the bottom of the screen what happens to it when the user scrolls down? Your video shows the cart opening, joy, but not what happens to the banner when you scroll the page down. Does it stay appended to the bottom of the screen? The thing about it being up the top is that it scrolls out of site as you scroll down...but if it's appended to the bottom of the screen does it stay there all the time till you close it? That worries me because at the moment the close is broken and it comes back the next time you visit. So, can you demo scroll with that version?

PS. I 100% agree that it's annoying having the top nav move when you're about to click something on it, and it would be good to resolve this. Whatever we decide, I'll have to run the change past the instance managers to make sure they're ok with it before we can proceed.

**Comment by Matt-Yorkley** [comment]
It stays where it is either way. It currently sticks to the top, but it would stick to the bottom instead.

CURRENT POSITION:

![CTA-top2](https://user-images.githubusercontent.com/9029026/82990630-c5f58b80-9ffc-11ea-8e2d-98053a5938ec.gif)

NEW POSITION:

![CTA-bottom2](https://user-images.githubusercontent.com/9029026/82990148-056fa800-9ffc-11ea-8fe8-b4cab5048658.gif)

**Comment by yukoosawa** [comment]
I'll take a look at this over the weekend. This behaviour in cart is super confusing for users who are shopping from shops that have OCs continuously open :slightly_frowning_face: And it will be worse on Mobile with the limited screen real estate. Regular ecomm shoppers will not understand why all this other stuff is being shown (but can't be actioned upon) in their current view cart. Do users even find this useful?

> The current cart dropdown has some functionality that isn't covered here: if the user has already placed an order in the selected OC and the OC is still open, the cart will show a list of products that are already ordered, under a subheading: "Already Ordered in this Order Cycle". They can then add more products to the cart, and see both lists. This isn't included in the Zeplin designs.
>

**Comment by daniellemoorhead** [comment]
> Regular ecomm shoppers will not understand why all this other stuff is being shown (but can't be actioned upon) in their current view cart. Do users even find this useful?

Completely agree @yukoosawa, wondering if we just direct them to the orders page from the view cart screen rather than displaying the items? Ceres allows for edits to orders, I'll have a look at how they do it, record it, and post it here.

**Comment by Matt-Yorkley** [comment]
So the decision is to cut it? That's the easiest option on my end...

**Comment by kirstenalarsen** [comment]
on the question of CTA thingo - I have no problem with it moving to bottom of screen. I think that would be much less annoying while also still there

**Comment by daniellemoorhead** [comment]
Wasn’t to cut it, was to move it to the bottom. See slack thread in mobile-UX For Lynne and Rachel 👍🏻 along with Kirsten 👍🏻 response here.

**Comment by Matt-Yorkley** [comment]
Sorry, I meant cut the other cart functionality of showing items from previous orders in the cart dropdown.

**Comment by daniellemoorhead** [comment]
Just spoke to @yukoosawa, we can't look at the example I did on AU staging cos it's busted to talk through it, but in theory we're ok for you to cut the previous orders section from the view cart dropdown. And I'll be creating a wishlist item around improving the edit order flow.

One thing though @Matt-Yorkley - are you able to tell me how many shops on our main sites (UK, FR, AU) allow shoppers to cancel/edit? Would be good to understand how frequently this is actually offered to shoppers, we think maybe not that often but would be great to have data to back this up. 🙏

**Comment by daniellemoorhead** [comment]
Passed testing via #5480
