### ISSUE TITLE
[mobile ux] Total items in cart and close menu on main nav dropdown cart view 

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4705]
## In a feature branch or master?
View cart feature branch 

## Description
**- As a:** shopper
**- On page:** main nav cart dropdown
**- I want to be able to do:** see how many items are in my cart and close the cart view

## Acceptance Criteria & Tests

- [ ] New menu added to cart drop down at that sticks to top of screen below cart icon
- [ ] New menu looks like design
- [ ] Total items in cart count in the menu
- [ ] Close function in the menu
- [ ] Clicking on the cart in the menu also closes the cart view

<img width="253" alt="Screen Shot 2020-01-22 at 4 35 00 pm" src="https://user-images.githubusercontent.com/10949052/72868452-2797a780-3d36-11ea-929e-e380b6096c93.png">

**Comment by daniellemoorhead** [comment]
@yukoosawa currently the main nav cart view is clickable to open/close the dropdown. Given you now have a 'close' option in the dropdown should this open/close interaction remain the same?

**Comment by yukoosawa** [comment]
@daniellemoorhead I would recommend keeping the current open/close interaction with the main nav cart -- this way we don't introduce any confusion with current users.

If we track both events and notice a significant preference for one over another, we could opt to remove one at a later stage.

**Comment by daniellemoorhead** [comment]
>- [ ]  New menu added to cart drop down at that sticks to top of screen below cart icon

@yukoosawa does this mean that the "7 items in cart" and close menu should stay stuck to the top under then main nav, is that correct?

**Comment by yukoosawa** [comment]
> > * [ ]   New menu added to cart drop down at that sticks to top of screen below cart icon
> 
> @yukoosawa does this mean that the "54 items in your cart" and close menu should stay stuck to the top under then main nav, is that correct?

Yes that's correct. On my iPhone 6S that should show approx 5 products before I have to scroll the list.

**Comment by daniellemoorhead** [comment]
Passed testing for #5480
