### ISSUE TITLE
Improve the "page not found" grumpy cat page

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#471]
Just that this page could use a bit more text to be friendly to the user. Also some basic OFN branding might be good.

Also what about an image like these below, instead of a cat? :-)

![apple](https://cloud.githubusercontent.com/assets/115115/6962215/48200df0-d92a-11e4-90bd-a00ad5e5544f.png)
![ugly_veg](https://cloud.githubusercontent.com/assets/115115/6962225/59b968c2-d92a-11e4-8106-defadfa1cc48.jpg)

**Comment by kirstenalarsen** [comment]
this was raised today but someone else and I agree it's annoying as is - the joke definitely wears off a lot if you're htting the grumpy cat and don't want to be!!

I like the images below :) assume they're not freely available though! very happy for you to work on / suggest some new error pages!

**Comment by omglett** [comment]
![nogrow_v1](https://cloud.githubusercontent.com/assets/13658293/9083513/c1b2c19a-3b62-11e5-961a-4c15932f3d15.jpg)

**Comment by lin-d-hop** [comment]
@kirstenalarsen @pmackay @NickWeir63 
@omglett has put this one together for us... any thoughts or feedback?
I guess we could update the text so something more relevant and embed it so navigation away from the grumpy slug is easier.

Sorry about the delayed reply @omglett ... summer is a busy time ;-)

**Comment by NickWeir63** [comment]
This looks great - thanks Tom

**Comment by kirstenalarsen** [comment]
wow - just sorting a bunch of stuff out in xero and I broke something - how polite and useful is this error page!! I think perhaps something along these lines, with a friendly illustration e.g. snail at the top followed by some actual suggestions about what to do would be great!

**Comment by pmackay** [comment]
@omglett any chance of editing the image you created so it is a thin banner image that could be at the top of the page, and then we could work on some text below similar to the Xero example @kirstenalarsen has suggested?

**Comment by pmackay** [comment]
Have posted http://community.openfoodnetwork.org/t/global-user-help-page/514 to get feedback on idea of a general help page that could be linked to from the site error page (500). This is to avoid having to customise those pages per install. However if anyone thinks a customisable 500 page is a better way to go please say.
