### ISSUE TITLE
Migration of Dean Forest Foodhub Data

### ISSUE THREAD

**Issue by aidandunsdon** [openfoodfoundation/openfoodnetwork#472]
Using the migration tool developed for Stroudco, migrate the Dean Forest customers, producers and  products to UK staging from current PHP MySQL platform. Assumption for this task is  that the db schema are the same for the 2 foodhubs given that they are derived from the same software package / platform.

**Comment by aidandunsdon** [comment]
Hi @lin-d-hop 
An issue that came up when migrating Stroudco data relates to the creation of enterprises in OFN which are mapped to suppliers in the existing database. An enterprise in OFN must have an associated user as an owner whereas in the existing Stroudco database, there were a small number of suppliers who do not have associated members.  To fix this @NickWeir63 created a new member for each supplier that lacked the associated record.  In the Dean Forest data there are also some suppliers who do not have associated members. These are the suppliers with the following ids 78,79,83,85,87,93,94,96,98,99,100,102,103,104,106,119,120,124 . Could you add these members and resend the dump  - Thanks

**Comment by NickWeir63** [comment]
@lin-d-hop when we did the Stroudco dump some of the producers who did not have an account were dummy producers who we had set up for test purposes.  if you have any dummy (or dead) producers who dont need migrating you could do what we did and ask @aidandunsdon to delete them from the database before migrating

**Comment by aidandunsdon** [comment]
@lin-d-hop the data is uploaded. It seems to work as logged in user but we need to sort #508.

**Comment by lin-d-hop** [comment]
Hi @aidandunsdon 
It looks to me that some enterprises have been entered with the same ID. When I use the enterprise page to go to specific enterprises clicking on 'Forest Meadow' takes me to 'Madgets Farm' as both have id 84. This seems like it might be a migration error to me. Would you take a look and confirm?
Thanks!

**Comment by NickWeir63** [comment]
This issue from Alexis may be linked......
From: alexisgreenwood99@gmail.com 
Sent: Sunday, April 26, 2015 2:07 PM
To: nick@nickweir.co.uk 
Subject: Fw: Producer data massaging - 2
 
I was going to massage Winstone’s icecream (so to speak).  I went to the data in the sheet and noticed an apparent anomaly.  Winstones’ product_supplier_id is 59 I think.  But there are rows for 60 and 61 also bearing Winstone’s name.  The product descriptions look anomalous though (more like wine than icecream in the case of 60).   If one goes back to the Supplier listings, there are no 60 and 61.  It goes from 59 – Winstones to 62 – Caroline Saturley.  Has something got out of kilter?
 
I will hold fire until I hear from you.  
 
Alexis.

**Comment by aidandunsdon** [comment]
Hi @lin-d-hop @NickWeir63  @getweaving  Looks like its the permalinks that got out of sync - the ids themselves are all unique and OK  - so the db doesn't complain. Can I correct and reload the database? It will go back to the state as of when I loaded the DF data - Is this a problem?   By the way this is a different issue to that identified by Alexis - she appears to be referring to the original MySQL Stroudco data.

**Comment by aidandunsdon** [comment]
@lin-d-hop @NickWeir63 @getweaving  Hi All - I have corrected the permalinks and Forest Meadow now goes to Forest meadow as expected. Hope everything is now OK.
