### ISSUE TITLE
Tooltip does not appear in Order Cycles page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#4731]
### Description

Tooltips appear on several occasions and serve as navigation and user experience helper.

This issue concerns those appearing on the small Copy | Clone | Delete Icons, next to a product or order cycle, in the respective pages.

### Expected Behaviour

Logged in as Admin, click on Order Cycles, in the main Menu. Provided there is an Order Cycle entry, three buttons should be visible. A tooltip should appear, when hovering the mouse cursor over it:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/97f70067-cd84-4ebf-8014-8bb80e367371)

### Actual Behaviour

The tooltip does not appear, in the Order Cycles page (/admin/order_cycles):

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/d742b3d2-170c-491a-8d59-ab2a19660ee8)

### Steps to Reproduce

- Log in as SuperAdmin.
- Click on the Order Cycles button (main menu).
- Create an Order Cycle - if none is displayed
- Hover the mouse over one of the three Copy | Clone | Delete Icons, next to the respective Order Cycle.

### Context

Editing Order Cycles.

### Severity
bug-s5

Impact is minimal. The customer will not know why the change was not possible and will not know how to resolve it. An appropriate error message will improve customer experience. The work around is to re-enter the products.

### Your Environment
Version used: v2.2.2
OFN Platform instance: Staging OFN Katuma

**Comment by tsara27** [comment]
Hello @filipefurtad0,

My name is Tsara and I am Rails developer. Can I help solving this bug?

**Comment by Matt-Yorkley** [comment]
@tsara27 Sure, go for it :+1:

**Comment by Matt-Yorkley** [comment]
Hey @tsara27 it looks like somebody already fixed it here: https://github.com/openfoodfoundation/openfoodnetwork/pull/4784

Feel free to pick up another issue though :smile:

**Comment by tsara27** [comment]
> Hey @tsara27 it looks like somebody already fixed it here: #4784
> 
> Feel free to pick up another issue though

No worries. :grinning: 
I will do.
