### ISSUE TITLE
Reports Balance Calculation does not match User Balance Calculation

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4732]
## Description

OFN has a very very basic ability to manage customer balances.

Shoppers can see their balance in Accounts -> Transactions.

Hub Managers can see customer balances in Reports -> Order Cycle Management -> Payment Methods reports.

The two places use different calculations to come to a customer balance. Shoppers see a sum or order balances while hub managers see a sum of order totals minus payments.

These two calculations should match. In the code the most common method used is the version the shoppers see. The Reports should use that method too.

## Expected Behavior

Shoppers and Hub Managers see a consistent balance. 

## Actual Behaviour

Shoppers and Hub Managers are seeing different balances

## Steps to Reproduce

1. Shop and make payments for a shopper.
2. Cancel a payment for the shopper in Edit Orders -> Payments
3. Go to Accounts -> Transactions and see one balance for the shopper
4. Go to Reports -> Order Cycle Management -> Payment Methods report and see a different balance for the shopper
5. Cringe at the difference.

## Workaround

Our current work around is to not use this feature!

## Severity

bug-s4: a feature is broken and there is no workaround. The feature is currently unused but in hot demand.

## Your Environment

* Version used: 2.7.1 UK
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu

**Comment by sigmundpetersen** [comment]
Hey @lin-d-hop why was this reopened and in which column should it be placed?

**Comment by lin-d-hop** [comment]
Reopened because it remained an issue.
It should be where it is... code review for the new PR.

**Comment by RachL** [comment]
@sauloperez should this one be part of the epic as well?

**Comment by lin-d-hop** [comment]
It should be solved by the epic for sure

**Comment by sauloperez** [comment]
oh yes, I moved it to dev ready so we keep track of it but it's better to link it to the epic.

**Comment by RachL** [comment]
@lin-d-hop I did a few tests, and I think @filipefurtad0 as well, and this looks fixed with new customer balances approach. The only thing left is the roll-out of the feature to all instances. I will document the roll-out plan in the epic and I'm closing here in the meantime, we can reopen if after the roll-out we still experience issues.
