### ISSUE TITLE
Release v2.7.2

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4736]
Steps: 

- [x] Include translations
- [x] Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-a37d2a3a04b703ef57ce
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1146
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

**Comment by RachL** [comment]
I believe this is ready to go!

Testing notes: https://docs.google.com/document/d/1vLJLTfhWTOW-cg1vX33azy4GfvHSYUZMXw1a_xS0Jqo/edit#heading=h.4ctypvfojpgm

**Comment by kristinalim** [comment]
Thank you, @RachL! :slightly_smiling_face:

**Comment by sauloperez** [comment]
It's already live
