### ISSUE TITLE
Spree no longer loading overridden countries.yml 

### ISSUE THREAD

**Issue by rafaqz** [openfoodfoundation/openfoodnetwork#475]
Spree seems to load its own countries.yml during Spree::Core::Engine.load_seed [(here)](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/db/seeds.rb) and ignores [ours](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/db/default/spree/countries.yml) which is an issue because deployment was overriding the file in our repo to limit country lists to a single specified country, and now country dropdowns always have the whole world. 

I imagine this happened during cleanup of superseded override methods? Just a guess, I don't have time to look into it.

**Comment by pmackay** [comment]
@rafaqz is this just an issue for new deployments? And do your seed changes on `ofn_deployment` relate to this?

**Comment by rafaqz** [comment]
Yes just first time deployment. I didn't fix it and didn't really do much relating to it in ofn_deploy, as that's not where the problem and I didn't have time to track it down in ofn. I'm guessing the override needs to be explicitly called somewhere and that the old directory structure overrides have been removed? it would be good to get a comment on this from @RohanM

**Comment by lin-d-hop** [comment]
Closing as fixed in OFN-install.
