### ISSUE TITLE
Make simple OC edit page list all products again (if more than 100 are available)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4754]
## Description
Simple OC edit page is listing a max of 100 products.
User cant create an OC with all products required.

## Expected Behavior
Can add more than 100 products to OC.

## Actual Behaviour
Can only add the first 100 products.

## Steps to Reproduce
Make more than 100 products available to be added to a simple OC. 
Create a new simple OC and try to add all products.

## Workaround
I dont think there's one. Maybe just convert type of enterprise and use the nonsimple OC edit pages.

## Severity
@mkllnk described this as an S1 in AUS.

Looks like an S2 with the workaround I describe above.
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
Found in AUS prod version 2.7.1.

## Possible Fix
We can develop pagination on these pages, that's #4743.
We can make the server endpoint return all products if no pagination is requested by the client, that's #4744

**Comment by mkllnk** [comment]
Issue solved. Tech-debt continued in #4755.
