### ISSUE TITLE
404 when trying to credit pin payment

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#476]
Place order and paid with credit card
edit order
shows (correctly) credit owed
![image](https://cloud.githubusercontent.com/assets/2911176/7017919/b3cdd3b4-dd41-11e4-9d00-000c55480f7c.png)

when I hit the reconcile tick thing, it shows 'credit' but then crashes (grumpy cat) - can we see if this is something smallish to make this work?
4:18pm, Tuesday 7 april, logged in as admin
order: R848245628

**Comment by kirstenalarsen** [comment]
also failed the first time I tried to put it through. I didn't change anything, just did it again and then it worked

**Comment by RohanM** [comment]
This looks like it might be the error:

https://bugsnag.com/yaycode/openfoodnetwork/errors/55237629cf825b739dc05928?event_id=552382f43c1c5c4f2ff0a2ba

**Comment by RohanM** [comment]
The Pin Payments gateway support refunds but not credits of arbitrary amounts, nor voiding transactions. So in theory, this situation would require a refund of the original amount ($240), then another charge for the new amount ($120). I'm not sure if Spree's interface supports refunds, so (without looking into it in detail) I suspect that might be a follow-up task: adding refund support and removing credit support for Pin payments.

**Comment by kirstenalarsen** [comment]
spree does support refunds, and it used to work . . but I am now finding that it doesn't anymore (even when has nothing to do with pin payments). I am getting grumpy cats trying to process refunds even on 'check' payment methods, so I have accounts stuck in credit when they shouldn't be . .

**Comment by kirstenalarsen** [comment]
see error logs from evening / night of 16 April
