### ISSUE TITLE
Anglicising the welcome email sent to new signups to OFN UK

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#477]
This screenshot shows the welcome email that comes to new signups from UK staging.  Please can:
1) 'You can start shopping online now at demo.spreecommerce.com' be changed to direct people to UK staging
2) '....you can use the Send Feedback button on the site or email us at hello@openfoodnetwork.org'  be changed to hello@openfoodnetwork.org.uk
3) 'Email us: 
hello@openfoodnetwork.org '
be changed to
hello@openfoodnetwork.org.uk

Thanks
Nick
![screenshot 2015-04-07 10 01 26](https://cloud.githubusercontent.com/assets/10517702/7019986/46e94d52-dd0d-11e4-8795-cbbad8ef1279.png)

**Comment by pmackay** [comment]
Given that #371 was not accepted for now, I'd propose @summerscope feed into this when the wider rebranding exercise has progressed, rather than taking it forward now.

**Comment by NickWeir63** [comment]
fine by me.  do we leave this issue open still?

**Comment by pmackay** [comment]
Yes, keep open til we can resolve it :)

**Comment by NickWeir63** [comment]
I will retest this when UK staging is able to send emails

**Comment by NickWeir63** [comment]
Looking good on staging with this message from hello@openfoodnetwork.org.uk:
Hello! 
Welcome to OFN UK Staging! 
 
Your login 
Your login email is nickweir23@gmail.com 
You can start shopping online now at staging.openfoodnetwork.org.uk 
 


Still need to test this on production once the email notifications are working again on prodcution
