### ISSUE TITLE
[mobile ux] Message and graphic on shop tab when shopper needs to select an order cycle

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4774]
## In a feature branch or master?
Order cycle section feature branch 

## Description

**- As a:** shopper
**- On page:** shop tab when they haven't selected an order cycle yet
**- I want to be able to do:** have an additional indicator on the shop where the products usually show that I have to do something before the products display

## Acceptance Criteria & Tests
Key changes / call outs:
- [x] OC module is highlighted in red
- [x] Dropdown selection is also red
- [x] Instruction is also represented to the user in body of page (this is to indicate to the user that the page isn't throwing an error by not displaying any products)
- [x] Body of page displays a light grey background colour + tiled background image (again to indicate the empty page is by design)

**HOW IT LOOKS NOW**

**_Mobile_**
Message is cut off in mobile :(

![IMG_0346](https://user-images.githubusercontent.com/19785399/74302502-be97c400-4d24-11ea-83e7-4d7a65664719.png)

**_Desktop_**
![screencapture-openfoodnetwork-org-au-harcourt-coop-shop-2020-02-07-22_42_23](https://user-images.githubusercontent.com/19785399/74078669-2b485100-49fb-11ea-8a6e-b733c9d86409.png)

**HOW IT SHOULD LOOK**
**_Mobile_**
![Mobile: Shopfront - OC Select Compulsory 01@1x](https://user-images.githubusercontent.com/19785399/74302966-4205e500-4d26-11ea-9169-08a87c23a2c0.png)

**_Desktop_**
![Desktop: Shop - OC Select Compulsory](https://user-images.githubusercontent.com/19785399/74302977-46320280-4d26-11ea-98cb-6ca17517c18e.png)

Design details are kept in our Zeplin account:
Mobile: https://zpl.io/bzez7e3
Desktop: https://zpl.io/aM03RgJ

**Comment by daniellemoorhead** [comment]
@mkllnk let's have a chat about this design implementation. @yukoosawa thinks that maybe it'll be difficult to have the background image displaying on a single tab, so let's talk it through and figure out what is the easiest solution.

Would be a conditional display, if no order cycle selected, display choose an OC message + background. If they then select an OC the background disappears, the products list appears, and the OC section turns blue. Yuko thinking maybe the background is a nice to have and a bit of a design overkill. Thoughts?

**Comment by mkllnk** [comment]
@daniellemoorhead Would you like another call about this?

Some thoughts:

- Background shouldn't be that hard to implement.
- The background is a good idea to take the eye off that part.
- Text on a textured background is a bit ugly, isn't it?
- We can give that message a background that is very similar to the pattern but plain, or do a 50% transparency to make the text more legible. And a little border to make it a tangible thing in the viewer's brain.
- I would still keep the background but alter the products section to have a white background. So when the products are loaded, you don't see the pattern until you get to the bottom where the OFN logo sticks out. The pattern would still be visible there.
- But I will go with Yuko's recommendation. Disabling the background shouldn't be hard either. I need to check the code.
- Aiming for the best and marking some things as nice-to-have would give me the flexibility to dismiss things that turn out too difficult during implementation.

**Comment by daniellemoorhead** [comment]
@mkllnk let's lock in a time next Wednesday to chat about this further. That's my next OFN day.

**Comment by daniellemoorhead** [comment]
@mkllnk I'm having a chat with @yukoosawa next week to discuss order cycle stuff. Specifically:

- What to do about order cycle closed personal message alongside of the shopfront closed version of the OC (where to put the personal message, how it fits against the OC section look and feel, how it fits with the Home tab vs Shop tab vs the known need in the future for OC specific shopfront messages. Big design thinking required which Yuko is in the process of doing).

- What to do about fitting the OC name into the drop-down field to ensure the characters fit on mobile/tablet.

We can cover your dot points above, but in the meantime I'll leave it to @yukoosawa to respond to any of these specifically, or to factor them into her thinking around the overall design of shopfront closed state vs when it's open.

**Comment by daniellemoorhead** [comment]
One thing I would say though, in terms of your thoughts above:

>Aiming for the best and marking some things as nice-to-have would give me the flexibility to dismiss things that turn out too difficult during implementation.

IMO it's better to agree on a path forward and set scope, not leave some things to be nice to haves. This card is low in terms of value, so to me we decide on the easiest implementation and stick to that. So, we'll lock down scope next week and then we can implement it easily enough :)

**Comment by mkllnk** [comment]
We can try that. "Ease" is often an unknown though.

**Comment by luisramos0** [comment]
This looks ok to me. What do you think?

![image](https://user-images.githubusercontent.com/1640378/80862029-f4847e80-8c69-11ea-98b9-084292ae4d46.png)

![image](https://user-images.githubusercontent.com/1640378/80862039-0e25c600-8c6a-11ea-82d5-37f1739deb3c.png)

![image](https://user-images.githubusercontent.com/1640378/80862045-1c73e200-8c6a-11ea-922d-afed2e42b0bf.png)

**Comment by daniellemoorhead** [comment]
@yukoosawa there's no background image on this version from @luisramos0 - this matches the closed shop version that is also grey. Are you happy for this version with no background, or do you think the graphic should be added?

**Comment by yukoosawa** [comment]
@daniellemoorhead I'm ok to leave out the background illustration. But I do have a few other OC UI tweaks which I would like to have instead... was hoping to list them when we do a QA pass for the OC Selector epic...

**Comment by daniellemoorhead** [comment]
@yukoosawa let's schedule that in for this week if possible so that we can get those changes in while @luisramos0 still has OC stuff in his sights.

**Comment by daniellemoorhead** [comment]
Tested, good to go.

Notes: https://docs.google.com/document/d/1wC42pMcgAAzqnVWBFW_Dm0MrTo5MOosZr_bBwjb56Wk/edit?usp=sharing

**Comment by daniellemoorhead** [comment]
Closing, PR will be merged later once a few fixes to another issue made.
