### ISSUE TITLE
[Spree 2.1] Fix email validation issues

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4775]
### What we should change and why (this is tech debt)

A temporary fix was added for broken email validations in `3-0-stable`, in this commit: https://github.com/openfoodfoundation/openfoodnetwork/pull/4641/commits/398223ffd778b429b99fe960a6fab30a9a33dd0e

Spree 2.1 has some new email validations on `Spree::Order`, and they were throwing fatal errors every time they run in the test suite, so have been disabled temporarily (with an ugly-looking hack). This needs to be re-examined and resolved properly.

Example failed spec (when validation is not removed):
```
ActiveRecord::RecordInvalid: Validation failed: Customer E-Mail is invalid

  0) CheckoutController building the order when completing the order sets the new order's token to the same as the old order
     Failure/Error: order.save!

     ActiveRecord::RecordInvalid:
       Validation failed: Customer E-Mail is invalid
     # ./spec/controllers/checkout_controller_spec.rb:133:in `block (4 levels) in <top (required)>'
```

**Comment by luisramos0** [comment]
removing the temp fix breaks 180 specs :-O
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-4825/builds/10

**Comment by luisramos0** [comment]
the easiest option seems to be the reintroduce the old validator and ignore the new one:
` validates :email, :presence => true, :format => /^([\w\.%\+\-']+)@([\w\-]+\.)+([\w]{2,})$/i, :if => :require_email`

due to our different scale I dont think we will be experiencing the reason for this new validator: https://github.com/spree/spree/issues/1238

any thoughts?

**Comment by Matt-Yorkley** [comment]
Agreed! I think the fancy new email address parser is not critical at all, and we can just skip it. :+1:
