### ISSUE TITLE
[mobile ux] Back/forward browser buttons don't work with shop tabs

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4810]
## In a feature branch or master?
This can be merged directly to master 🎉 

## Description
Back/forward on browser doesn't change the displayed tab, only the URL.

## Expected Behavior
When I have navigated across different tabs, and then I hit back or forward and the tab URL displays, the tab displayed should also change. 

## Actual Behaviour
The URL changes however the displayed tab does not.

## Steps to Reproduce

1. Navigate to a shop
2. Click through the tabs (notice how the URL changes for each tab, and each tab is displayed)
3. Click the browser back button (notice how the URL changes however the displayed tab does not)
4. Click the browser forward button (same as the back button)

## Animated Gif/Screenshot
![Screen Shot 2020-02-20 at 8.51.14 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/adc8ca98-dd48-4848-a026-bebd39c6aa4f)

## Workaround
Click on the tabs themselves

## Possible Fix
Make the tabs work with the browser back buttons

**Comment by daniellemoorhead** [comment]
Ping @Matt-Yorkley and @mkllnk - new bug to be fixed, and this is in production so the sooner the better :)

**Comment by mkllnk** [comment]
This is one of these "exploding" tasks. The current tabs code is very complex and doesn't consider the browser navigation. I tried to make the tabs listen to the back button but Angular doesn't update the tab, it only updates which tab link is highlighted. https://github.com/openfoodfoundation/openfoodnetwork/commit/e6fc1f31a3ca6e2efd0934b62806e08b93fa18b0

I reckon that this part needs some refactoring. We can either re-implement tabs based on the browser navigation or move to the original idea of making these tabs real pages. Real pages are very simple to implement but navigating between the tabs will be a lot slower. Rewriting the tabs code is more complex and will add more maintenance cost but it's the most efficient UX. I will try that and see how difficult it really is.

**Comment by daniellemoorhead** [comment]
@mkllnk can you let @JenRSmith know when this is ready to test please 🙏
