### ISSUE TITLE
[Spree 2.1] Fix assets precompilation

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4819]
## Description
There a few things we need to do to fix assets in rails 4, see here:
https://guides.rubyonrails.org/v4.0/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0-gemfile

We need to update application.rb, currently this is what we have:
  Bundler.require(*Rails.groups(:assets => %w(development test)))

We need to update ofn-install precompile because
https://guides.rubyonrails.org/v4.0/upgrading_ruby_on_rails.html#sprockets-rails
This is what we are doing now:
assets:precompile:primary and assets:precompile:all have been removed. Use assets:precompile instead.

## Acceptance Criteria & Tests
Assets are precompiled correctly on deploy.

**Comment by Matt-Yorkley** [comment]
Should be easy to add a check in the deployment playbook for Rails 4 and conditionally use the other command.

**Comment by Matt-Yorkley** [comment]
I thought the Bundler.require bit was already updated in the `3-0-stable` branch?

**Comment by luisramos0** [comment]
I removed the assets group from the gemfile but now the application.rb file needs to be updated here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/56bd866f178b6cc90917f82fdff63a202fe8f31c/config/application.rb#L8
