### ISSUE TITLE
Dashboard should show active OC's that I am participating in

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#482]
showing none
![image](https://cloud.githubusercontent.com/assets/2911176/7057326/e4eb33fe-de97-11e4-9a2c-0b7acf2a873d.png)

but i am participating in 
![image](https://cloud.githubusercontent.com/assets/2911176/7057348/08b51fe8-de98-11e4-9986-0108d89fb5d6.png)

**Comment by myriamboure** [comment]
I don't think this is still an issue, closing #gitcull2018
