### ISSUE TITLE
'&' symbol in enterprise name not showing correctly on backend

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4830]
## Description

In the backend of OFN-CAN  it seems that the ampersand symbol '&' in an enterprise name shows incorrectly in the list of OCs,  and in the inventory list.  For example:  the enterprise "A&E Fine Foods"  shows as "A&ampE; Fine Foods".  

## Expected Behavior
The '&' symbol should always show as the '&" symbol

## Actual Behaviour
Thee '&' symbol shows correctly in the shopname,  in reports,  in product screen,  in orders, etc.  But it does not show correctly in the admin - inventory page,   nor in the admin - order cycles pages.

## Steps to Reproduce
create an enterprise with an '&' in the enterprise name
go to create an inventory for that enterprise,  or create an OC for that enterprise -  and see how the name show

## Animated Gif/Screenshot
How the '&' shows to the public in the shopfront:

![screenshot-openfoodnetwork ca-2020 02](https://user-images.githubusercontent.com/13171778/75097219-1d0b4080-5576-11ea-8181-c5d1374f7dcf.png)

![OC list](https://user-images.githubusercontent.com/13171778/75097221-25fc1200-5576-11ea-87c9-9d7ff9826d11.png)
![inventory page](https://user-images.githubusercontent.com/13171778/75097224-2ac0c600-5576-11ea-83be-7436edc91da5.png)

## Your Environment
OFN-Canada,  using Google Chrome

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jeduardo824** [comment]
I can take a look.
