### ISSUE TITLE
Release 2.7.7

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4854]
Steps: 

- [x] Include translations
- [x] Draft new release: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-8698fa8bb72cb18211c1
- [x] Notify #instance-managers of user-facing changes. (None this week)
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1199 
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by lin-d-hop** [comment]
Release testing failed on product import.
Issue opened here: https://github.com/openfoodfoundation/openfoodnetwork/issues/4871

Everything else fine. Notes here:
https://docs.google.com/document/d/1YZVeuX88yUsobYEIrfHNsE-fvEhgkLvT9ivFOqh67Z4/edit#
