### ISSUE TITLE
Subscription Orders not Created

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4870]
## Description

This week Banc Organics experienced huge failures on the generation of orders from Subscriptions.

3 Subscriptions were created successfully: R204511658, R522328655, R642514522.
These align to the first 3 active subscriptions in their subscription list.
23 subscriptions then failed to have orders created for them.

@luisramos0 noticed a Bugsnag related to subscriptions and I can confirm that this was the OC in question - Banc Organics OC opened at 6pm on Feb 27th so this message is definitely related to this OC.
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1582826433008200

## Expected Behavior

All subs should open without error.

## Actual Behaviour

3 opened and 27 failed to open.

## Steps to Reproduce

I currently have no idea how to reproduce this. We have seen an issue in the past for THIS enterprise on subscriptions which resulted in an s2 issue (I suspected user error) followed by an issue to create logging in subscriptions so that we could debug issues more successfully in future:
https://github.com/openfoodfoundation/openfoodnetwork/issues/4462

## Animated Gif/Screenshot

The best way to understand this issue more closely will be to log into UK production and inspect Banc's subscriptions. 
Subscriptions for OC A5 are marked as 'Pending' for all but the first three relevant subscriptions. The successfully opened subscription orders are marked at 'Cart'.

![Screenshot from 2020-03-01 09-29-08](https://user-images.githubusercontent.com/8669848/75623127-282a2600-5b9f-11ea-833b-43e831f2b8b8.png)

Ignore that it says 'County' instead of 'State'. I think I've now fixed this in transifex :-)

## Workaround

The most urgent part of this issue is that we need a good workaround to ensure that Banc's subscription orders are opened this week. I'd like to chat this through with someone.
Currently I'm wondering if I should:
1) Cancel the open orders
2) Shift the open date of this OC to after now()
3) Check that subscriptions open correctly.

I think this will work but I wonder if there are any potential side effects... one is that the users will receive another email about their subscription this week.

## Severity

S1 - I am marking this as an S1 as subscriptions is an officially supported feature that opens orders and the orders did not open. Failure to create orders and thus take payments represents a critical feature being broken.

I'm not going to call anyone to work on this on a Sunday, however. 
Once we have successfully opened the orders for this week I will also be happy to downgrade to an S2.

## Your Environment

* Version used: 2.7.6 UK production

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Banc Subscriptions](https://trello.com/c/oeiaxHQF/684-banc-subscriptions)

**Comment by luisramos0** [comment]
The is OC 204060
This gives us the list of orders placed:
select * from proxy_orders where order_cycle_id = 204060;
Only 3 with order_id, the placement order job must have failed.

The [bugsnag error](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5e5803c0282bd000191898bb?event_id=5e5803c00056908952be0000&i=sk&m=nw) is related and shows that the process failed while authenticating with the email server. The process is not designed to continue if an error occurs while sending email.
I assume one of the 3 orders did not get an email sent to the user.
Anyway, for now, I think it's obvious what I need to do: remove the "placed_at" label from the other orders and run the process again. I'll report back.

**Comment by luisramos0** [comment]
To be clear: more logs would not help here.

**Comment by luisramos0** [comment]
I have updated 23 missing orders (35 subscriptions in total - 2 are canceled - 7 are paused - the 3 already placed = 23), the job has run now and it looks good.
The manager got this email: "A total of 23 subscriptions were marked for automatic processing.
Of these, 21 were processed successfully. Details of the issues encountered are provided below."
One issse was insuficccient stock and another was no stock.

Looks like the job failed because of a temporary problem with the email server. Rerunning it fixed the problem.
Looking at the ids of the 3 placed orders I'd say order R642514522 is missing an email to the user. We can resend the email on the admin orders page, right?

I'd say the problem is solved. I'll wait for confirmation.

Some ideas for a postmoterm:
- we can make the placement job a bit more resilient by maybe adding some delayed retries accessing the email server. We can also make it go through all orders even if there is a problem (like this one) placing one of the orders.
- the bugsnag alert was there on Thursday and I commented on it. We could have fixed this proactively :-( We do have the right tools in place :+1:

**Comment by lin-d-hop** [comment]
Thanks @luisramos0! This is great :-)
I guess at the time we didn't know that a failed email would have caused all orders to fail?
At least I didn't know that otherwise I would have acted then. I assume you didn't know it @luisramos0 or your comment might have done more than comment?
I feel like we _almost_ have the right tools in place. I would have liked a notification that the orders just didn't get placed.

On another note - UK have experienced a recent, dramatic increase in emails being flagged as spam (despite the work gone into updating mail servers). Is there a chance the failed emails could be related?

**Comment by luisramos0** [comment]
correct, I didnt know one failed order would fail the following orders.

A bugsnag error on a subs job must always be checked for now on.

I dont see how this could be related to deliverability. Maybe it just means the ESP is bad and you need to switch.

**Comment by lin-d-hop** [comment]
:woman_facepalming: I literally JUST switched all the UK emails over to a new provider recommended by the dev team. Please don't say that :sob:

**Comment by luisramos0** [comment]
ok, I didnt know that. are you sure you did the switch correctly? Maybe something is missing.

**Comment by lin-d-hop** [comment]
No. Last time I talked to you about it you suggested I look at the DMARC reports on the tech email account. This is why I put a message in dev asking how to interpret (though maybe I linked the wrong report). I'm trying but I feel like I'm swimming in the dark and don't feel very supported to do so.

**Comment by luisramos0** [comment]
this looks like a connectivity/authentication issue, not a deliverability issue seen in dmarc.

**Comment by lin-d-hop** [comment]
Yep. Understand. Deleting the above comments as they are unrelated to the issue at hand.

**Comment by lin-d-hop** [comment]
Another question @luisramos0
Am I correct in thinking that only 1/10 Bugsnag issues are posted into Slack? I remember there is something about them not all creating notifications. I recall @sigmundpetersen pointed this out in the past.

If this is the case are we confident that we'll get any notification on the failure of the subscriptions job?

We've had a lot of this kind of failure in the UK and France and the knowledge that an error on one subscription can cause all the subs in the job to fail seems like a pertinent insight to me. Can we act on this?

**Comment by luisramos0** [comment]
I marked the issue in bugsnag fixed, that way, if it happens again, we will get a notification for sure. We dont receive notifications for existing issues in bugsnag.

**Comment by RachL** [comment]
>  I remember there is something about them not all creating notifications. I recall @sigmundpetersen pointed this out in the past.

Bugsnag notifies only the 1st, 10th and so on.

**Comment by lin-d-hop** [comment]
Thanks both.
All makes sense.

What are the next steps.... ?

I like Luis' ideas above:
_we can make the placement job a bit more resilient by maybe adding some delayed retries accessing the email server. We can also make it go through all orders even if there is a problem (like this one) placing one of the orders._

In particular, I am still concerned that we do _NOT_ have all the right alerts in place to catch something like this in future. To me a simple step might be some specific notification if the subs job is killed part way through.

**Comment by luisramos0** [comment]
that's a good idea, specific bugsnag message :+1:

the bugsnag rules are not just 1, 10, etc. it's configured like this:
![image](https://user-images.githubusercontent.com/1640378/75692159-0911be00-5c9d-11ea-9448-1561a8019970.png)

**Comment by daniellemoorhead** [comment]
You ok to test this @lin-d-hop? Figure you understand subscriptions the most 😄

**Comment by lin-d-hop** [comment]
@luisramos0 @RachL 
I don't want to close this issue until we can have a clear strategy of knowing when it happens in the future. As a support person there is nothing worse than having an issue reappear that you 'fixed' simply because we didn't even make a warning/error/bugsnag last time. 

Options:
1) Specific bugsnag message when subs placement job fails mid process (this must flow through to slack)
2) Add delayed retries on the placement job
3) If one sub placement fails, don't kill the job. Post an error to bugsnag and continue placing subs. (Error must flow through to slack)

My preference would be 3. However if we can't prioritise that now but we can prioritise 1 then I vote 1.

I'm almost ready to deprecate it to UK users. 
Please can we prioritise small steps to make subs more supportable?

**Comment by RachL** [comment]
@luisramos0 @lin-d-hop I think we can add to dev ready the specific bugsnag message for sure. Can you create the issue @lin-d-hop ?

About the job, I agree 3 sounds good, can we have an idea of the size? I'm not saying we shouldn't do it, I would like more to understand "when". Thanks :)

**Comment by luisramos0** [comment]
yes, we can implement point 3, I am not sure it's the worth it just because the retries will fail in most cases: most errors will not be specific to the order.
I'd like a second opinion here @openfoodfoundation/core-devs

**Comment by sauloperez** [comment]
I think we do have the necessary monitoring in place, it is just about having the necessary alerting on top of it. 

### Monitoring and alerting

We currently have Datadog monitoring Delayed Job, like any other part of our infrastructure. We have it currently watching `
Resource subscriptionplacementjob has a high error rate on env:production` plus `Resource subscriptionplacementjob has an abnormal change in throughput on env:production`. This means we receive a message in the `devops-alerts` Slack channel with a graph when that happens, similar to https://openfoodnetwork.slack.com/archives/GLJQ2LASF/p1583409853000200.

The question to me is how can make this visible to an instance manager/devops team? It's clear that we do have the information but it doesn't serve its purpose. I acknowledge the fact that I can't attend all the alerts I see and as a result, I tend to pay little attention to things that do deserve it. It is probably both an excess of information but also not having the necessary (ops) resources our instances need.

The problem is that all this monitoring is only applied to FR and not the UK. We decided so to keep costs as low as possible. IMO in this particular case, possibly the costs in human hours trying to fix the issue and the impact on user satisfaction clearly outweigh the 35$/month this dedicated monitoring costs.

###

**Comment by luisramos0** [comment]
I am not sure I understand why you talk about datadog when we are talking about a case that already generates a bugsnag event. Can you clarify?

**Comment by sauloperez** [comment]
Still working on it, sorry

**Comment by sauloperez** [comment]
Now. I finished my comment. Hope its clear.

**Comment by lin-d-hop** [comment]
Thanks @sauloperez. It's hard to me to know if DD is the best solution here without understanding what the actual process is. All I want is to be alerted every time OFN fails to place subscriptions, so I can take action before I have angry users that have no orders.

I would like to progress this S1 and create a new issue. Unfortunately I don't understand your suggestion well enough to make an issue. I don't want to make you feel like a bottleneck on DD either. 

How to become unstuck on this?

**Comment by sauloperez** [comment]
IMO if you need to be notified and not miss any notification you better check the email account associated with Bugsnag. I created a label in Gmail so I don't miss them the ones for Katuma in the wealth of emails. The Slack channel gives visibility to the global team, while email notification are better suited for instance managers.

Other than that, I think the action item here is your number 3. Specifically to make the job handle this failure scenario and continue with the process plus

> Tune the various config settings listed in https://github.com/collectiveidea/delayed_job/#gory-details. Specifically, reschedule_at and max_attempts. I agree with @luisramos0 that most of the time retrying is pointless but it does help with temporary problems.

Then, we can have a debate around DD and the role it plays alongside Bugsnag. Sorry if it felt overwhelming :sweat_smile:

**Comment by lin-d-hop** [comment]
The specific problem here was the the error, that was noticed, said 'A Subs Email failed to send'. And we all happily went on with our days not realising that this failure actually meant that no Subs orders were placed.

I think the conversation on how we do alerts, while obviously important, is out of scope here.

I'm going to make an issue that a Bugsnag and clear error message is raised when the Subs Placement job is interrupted. The message should contain enough information that the instance manager can act.

**Comment by luisramos0** [comment]
cool :+1: 
the problem I see here is that those alerts will not be actionable by instance managers. We will be catching exceptions that we dont know about like the last one email server not available. So we wont know what to do until we look at the error ourselves. So, I think these alerts will always be for tech support/devs.

Anyway, lets do point 1 and 3.

**Comment by lin-d-hop** [comment]
If we have an alert that offers a little more detail about the Subs placement job that failed then instance managers can mitigate with users more effectively. We'll also be able to raise issues for devs.

So I'm hoping we can include a bit more info in the alerts :crossed_fingers: 

Off to create the issues. Will close this once they are open

**Comment by lin-d-hop** [comment]
Improve notifications on subs placement job failure: https://github.com/openfoodfoundation/openfoodnetwork/issues/4981

Continue Subs Placement job when a subs order creation fails:
https://github.com/openfoodfoundation/openfoodnetwork/issues/4983
