### ISSUE TITLE
[Spree 2.1] Fix Admin Orders page - spec/features/admin/orders_spec.rb:149 (1 broken spec)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4881]
There's a problem with this tricky spec in orders admin page related to updating customer details.

**Comment by Matt-Yorkley** [comment]
`save_and_open_screenshot` says:

![capybara-202003120007054068358958](https://user-images.githubusercontent.com/9029026/76472507-0da14980-63f6-11ea-86e0-3d70dae03e08.png)

**Comment by Matt-Yorkley** [comment]
Even before that we get this during the test: 

![capybara-202003121014482329770089](https://user-images.githubusercontent.com/9029026/76506069-d7da8000-644a-11ea-8910-db6e8a5015ec.png)

I think the workflow for adding a variant to an order in the admin UI is broken.
