### ISSUE TITLE
[Spree 2.1] App broken in staging

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4900]
I tried deploying a Rails 4 branch to staging, and it was totally broken. I think we need to adjust some of the configs for staging and production environments.

For example we have `config.eager_load = false` for staging and production, but I think this should be `true`.

The Rails log showed some odd-looking cache entries as well, so we might need to review the settings for `memcached`..?

**Comment by Matt-Yorkley** [comment]
Rails spits out this advice when eager_load is not set:
```
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true
```

**Comment by sauloperez** [comment]
can this be closed @Matt-Yorkley ?

**Comment by Matt-Yorkley** [comment]
There's a related PR that's not merged yet. We planned on re-checking this once the other spree upgrade bits are merged and we've debased. Let's leave it open for now

**Comment by luisramos0** [comment]
I staged 3-0-LATEST in uk staging and it0s definetly not broken, I didnt find a single problem in the app in my sanity check!!!

I am closing this issue, ok Matt?

what do you mean by "odd-looking cache entries"?

**Comment by Matt-Yorkley** [comment]
The cache thing turned out to be nothing :+1:
