### ISSUE TITLE
Password change request on UK staging

### ISSUE THREAD

**Issue by getweaving** [openfoodfoundation/openfoodnetwork#491]
I received this link in the password change request email:

http://demo.spreecommerce.com/user/spree_user/password/edit?reset_password_token=7-nz2USOaDGQ93Pf7loR

When I follow it, I'm in Spree being invited to set up a sandbox account.  This doesn't seem right.  I did it anyway, and retried OFN with the password created in Spree.  No luck.

**Comment by pmackay** [comment]
Fixed. Was General Settings > site url setting.
