### ISSUE TITLE
[Spree 2.1] Fix spree/admin/orders_controller_spec and spree/orders_controller_spec and admin/orders_helper_spec (3 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4915]
3 specs broken:
spec/controllers/spree/orders_controller_spec.rb:248
spec/controllers/spree/admin/orders_controller_spec.rb:21
spec/helpers/admin/orders_helper_spec.rb:19

######

Invalid adjustment is being rendered because it is still seen as eligible.
The invalid adjustment (zero amount) never receives a call to update! and so eligibility is not correctly set. In master the adjustment receives a update! call and the eligibility is set correctly before rendering.

```
  2) Spree::Admin::OrdersController#edit view shows only eligible adjustments
     Failure/Error: expect(response.body).to_not match adjustment.label
     
       expected "<!DOCTYPE html>\n<html lang='en'>\n<head data-hook='admin_inside_head'>\n<meta content='text/html; c...ee.api_key = \"4a1d50e99b0858a36bd25281e3e8339417295fa63d8eb013\";\n</script>\n\n</body>\n</html>\n" not to match "invalid adjustment"
       Diff:
       @@ -1,2 +1,469 @@
       -invalid adjustment
       +<!DOCTYPE html>
       +<html lang='en'>
```

**Comment by luisramos0** [comment]
this is maybe related to this broken spec where adjustments are also not updated when needed:
/spec/controllers/spree/orders_controller_spec.rb:248

**Comment by luisramos0** [comment]
adding spec/helpers/admin/orders_helper_spec.rb:19 here as it's failing just because eligibility is not automatically set now and adjustments that are not eligible are being retrieved in tests.

I'd expect a newly created adjustment that is not eligible (like amount = 0) to NOT Be listed in order.adjustments.eligible

```
      adjustment = create(:adjustment, adjustable: order, amount: 0, originator_type: "Spree::TaxRate")
       order.adjustments.eligible   --- here we see the adjustment (in rails 3 we were not seeing it)

```
One workaround is to call update! on the adjustment:
```
      adjustment = create(:adjustment, adjustable: order, amount: 0, originator_type: "Spree::TaxRate")
      adjustment.update!  - -this will call adjustment.set_eligibility
       order.adjustments.eligible   --- here we dont see the adjustment :+1:
```

Maybe this is a specs only problem and so this workaround above may be good enough?

**Comment by Matt-Yorkley** [comment]
Interesting... in `master`, `adjustment.update!` is indeed called; about 20 times (!) from `Spree::OrderUpdater#update_adjustments`.

In `3-0-latest`, `adjustment.update!` is called ~14 times, but from `Spree::OrderUpdater#update_shipping_adjustments`. The `#update_adjustments` method that was being called in `master` (and presumably setting the eligibility) has been removed from `Spree::OrderUpdater`.

The code comments on `Spree::Adjustment#update!` that describe how and when it is triggered are also different between the two spree versions.

**Comment by Matt-Yorkley** [comment]
```ruby
def who_is_calling_me?
   puts caller_locations(1,1)[0].label
end
```
:smile:

**Comment by luisramos0** [comment]
ok, I think I found the root cause, I am not sure what to do about this mess so I made a PR with the simplest possible fix #hack_on_top_of_mess:
https://github.com/openfoodfoundation/openfoodnetwork/pull/4916
