### ISSUE TITLE
Bump jquery-ui-rails from 4.0.5 to 6.0.1

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4917]
### What we should change and why (this is tech debt)
Upgrade this will bring latest code from jquery-ui
We need to tweak a few things to make it work.

### Context
From dependabot PR #4839

### Impact and timeline
Not the most important upgrade right now.

**Comment by RachL** [comment]
We want to remove this one: https://github.com/openfoodfoundation/openfoodnetwork/issues/6665

so closing
