### ISSUE TITLE
[Spree 2-1] Fix spec/controllers/line_items_controller_spec.rb:45 (1 broken spec)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4922]
Some routing issue where route is not seen if params are not provided, I tried adding json to params but it doesnt fix it, only adding an item id will make it work, which is not the test.
```

 14) LineItemsController destroying a line item on a completed order without a line item id fails and raises an error
      Failure/Error: delete :destroy
      
      ActionController::UrlGenerationError:
        No route matches {:action=>"destroy", :controller=>"line_items"}
      # ./spec/controllers/line_items_controller_spec.rb:46:in `block (5 levels) in <top (required)>'
```

**Comment by Matt-Yorkley** [comment]
We've seen this in other specs as well. Rails 4 does not regard these routes as valid unless they have an id. It handles `id: ""` correctly, but not if `id: nil`, or no id is passed at all.

**Comment by Matt-Yorkley** [comment]
My question is: do we even need this test? 

We're testing the case where the destroy action is being called on the line_items controller without passing an id. Is there even any real case where this would happen?

**Comment by luisramos0** [comment]
I think it's a valid edge case test, verify that if no id is provided it will return 404.
I see that id: "" fixes it :+1:
I think we should go with it:
-          delete :destroy
+          delete :destroy, { format: :json, id: "" }
