### ISSUE TITLE
Subs cannot be edited when they contain unavailable items

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4924]
## Description

If a user is running a subscription over a long period of time, items in the subscription will likely come and go from future order cycles. For example "as a shopper I want tomatoes every week they are in season".

Currently if a hub manager wants to edit a subscription that contains an item that is not available in a future order cycle they have to remove that item. If they forget to add it back in later, they lose the sales.

In our goals of encouraging seasonal eating and all the like, we need to work with the use case.

As instance managers you might be interested to note that I have updated the error message in UK production to let the user know the subscription was not saved. Previously this was not communicated to the user, though they did see an error message.

## Expected Behavior

If an item in a subscription is not available in any future order cycles the hub manager should still be able to edit the subscription.

## Actual Behaviour

Subscription changes should save for the user.

## Steps to Reproduce

1. Create a subscription with a few items
2. Remove one of the items from all future order cycles
3. Edit the subscription
4. See that it does not save

## Animated Gif/Screenshot

![Screenshot from 2020-03-05 11-27-16](https://user-images.githubusercontent.com/8669848/75977612-af93d400-5ed4-11ea-9d90-0da1608d14e6.png)
![Screenshot from 2020-03-05 11-27-53](https://user-images.githubusercontent.com/8669848/75977619-b3275b00-5ed4-11ea-97dd-6ba2d2c15ef2.png)

## Workaround

Remove the item that is unavailable. Make a note somewhere and try to remember to add it back in when it is in a future order cycle.

## Severity

bug-s3: a feature is broken but there is a workaround

I'd propose s3 over s4 because we have a user who is removing future sale items from subscriptions to enable with this workaround.

## Your Environment

* Version used: 2.7.7 uk
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
I'm closing this, let's reopen if we find the correct scenario!
