### ISSUE TITLE
Release v2.7.8  Striped Espargo

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4929]
Steps: 

- [x] Include translations
- [x] https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-14a4ca376a87a44def0a
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1218
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by filipefurtad0** [comment]
Hi @luisramos0,

This is good to go. All the notes here:
https://docs.google.com/document/d/15Ow4OTrjrEN5DzAwHEMUU6-GUFveF1A8qDwyrPpxjM0/edit#

As discussed on Slack, two issues were found, not related to the release. These will be added/checked for pre-existence. Briefly:
- Snail upon product creation, if an image path is selected. All works normally if no image is selected
- Using the button [+ New Variant] at the Variants menu causes no action (the spinner briefly appeaers), and a Bugnsnag error. A snail appears not visible to the user.
- On the same menu, [Show Deleted] button never shows results, although there were previously deleted variants.

Ready to go! :tada:

**Comment by luisramos0** [comment]
Nice, thanks Filipe!
I can see new issues #4961 and #4962 for the 2nd and 3rd point above.
What is the status of point 1, will you create an issue as well?

**Comment by sigmundpetersen** [comment]
#4959

**Comment by luisramos0** [comment]
ah, nice, thanks @sigmundpetersen

**Comment by filipefurtad0** [comment]
Thanks @sigmundpetersen and @luisramos0.
Would you agree these are all S3s?

**Comment by luisramos0** [comment]
I agree
