### ISSUE TITLE
As a shopper on UK staging when I press confirm, nothing happens the first time

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#493]
Both @getweaving and I have had this issue..... having completed a shopping basket and filled in all our collection and payment details - see attached screenshot 
![screenshot 2015-04-10 15 51 13](https://cloud.githubusercontent.com/assets/10517702/7090334/372d5806-df9a-11e4-93af-ff5cf41b55c5.png)
we press 'Place order now' (bottom left) and nothing happens.  When we press 'Place order now' for the second time the order is successfully submitted.

**Comment by pmackay** [comment]
@NickWeir63 is this still true after the site reset recently?

**Comment by NickWeir63** [comment]
yes it happened again just this morning

**Comment by kirstenalarsen** [comment]
@NickWeir63 @getweaving is this only on stroudco or do you have other test hubs that it's happening for? also is it only nick? logged in / guest user? user with enterprise permissions or not? any pattern in the items you have in cart? etc
Would be really good if you can work out and create exact conditions to replicate the error, then is much easier for people to work out what is going on

**Comment by RohanM** [comment]
Here are some things to look into when debugging this:

- Are any errors coming up in Bugsnag or the server logs?
- Are there any javascript errors?
- What's happening on the network? Are we seeing a request? Is there an error in the response?

**Comment by NickWeir63** [comment]
I will do more extensive testing early next week and see if I can spot any patterns.  thanks all

**Comment by NickWeir63** [comment]
OK i have tried lots of options as guest user, admin and superadmin on Stroudco and DFFH hubs and have not been able to recreate this bug.  Sorry!  Should we close this issue and then I will re-open if if we manage to recreate it in future.
@getweaving do you remember what products you were ordering when you got this problem?  I don't...
thanks all

**Comment by pmackay** [comment]
Thanks for testing again Nick. I would close for now if it cannot be
reproduced.
