### ISSUE TITLE
[Flaky spec] Fix features/admin/variant_overrides_specs currently commented out (2 specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4957]
spec/features/admin/variant_overrides_spec.rb:193
spec/features/admin/variant_overrides_spec.rb:210

This spec is not failing all the time #flaky

**Comment by mkllnk** [comment]
Another example:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-5314/builds/1

**Comment by luisramos0** [comment]
interesting. this issue was for the rails 4 branch, the fact that you are seeing it in rails 3 it probably means its not specific to the rails 4 branch :+1:

**Comment by luisramos0** [comment]
this breaks very regularly on the rails 4 branch.

**Comment by luisramos0** [comment]
I just double checked and the link Maikel shared above is not for the same spec. Maybe we need another issue for those.
I am moving this back to spree 2.1 context where this spec is still failing regularly but not always.
