### ISSUE TITLE
Specs in engines are not executed in CI!?

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4958]
### What we should change and why (this is tech debt)

There are some broken specs in ent fee summary report.
The CI build needs to run these tests so we see the broken specs, so too tasks here:
- add engine specs to semaphore jobs
- fix the broken specs

### Context
@kristinalim detected this in #4783

### Impact and timeline
This is as serious as a broken build, needs to be fixed immediately.

**Comment by Matt-Yorkley** [comment]
As far as I can tell from the documentation on Rails Engines, they're not supposed to be tested in this way. They're designed to act like stand-alone components and not be tested in the full context of the app that's including them.

Maybe we need to move those specs back into the main spec folder if we want to test the engines in this way..?

**Comment by Matt-Yorkley** [comment]
I had a go at adjusting the settings for knapsack / rspec to try to include our engines as well, but the results were a bit flaky.

**Comment by Matt-Yorkley** [comment]
Copying the spec files from the engines back into the main /spec directory works well...

**Comment by luisramos0** [comment]
:-( copying the specs back to the main app would be something to do only if we dont find any other solution. 
I thought @kristinalim had sorted this problem before when she created the orders engine.

One option I see would be to add extra commands on the build jobs for each engine. Maybe that's what Kristina did in the past?

**Comment by Matt-Yorkley** [comment]
Conclusion summary:

- Engines are designed for things like `devise` that can be included in any app, but are not dependent on a specific app context
- The specs inside an engine are supposed to be run in a separate CI build. There's a way to include a small/generic "dummy" app inside the engine's spec folder to see how it integrates with the including app, but that's _not_ what we're trying to do here
- If we want to test how an engine behaves with _our_ app, we need to put those specs in the main `/spec` folder

**Comment by kristinalim** [comment]
Hi @luisramos0 and @Matt-Yorkley! I added the Rake task namespace `ofn:specs:engines` and added a job for it before. I don't remember why it was temporarily removed, IIRC it was because it wasn't playing well with Knapsack.

**Comment by kristinalim** [comment]
With "job", I mean Semaphore or Travis job at that time.

**Comment by kristinalim** [comment]
This is the related issue: #3088

**Comment by luisramos0** [comment]
IMHO the specs in the engine are not supposed to run only against the code in the engines, that would be to hard to make the engines code completely independent of the app already.

For now we can run the engine specs from root folder just like
bundle exec rspec engines/web/spec

kanpsack supports this well here:
https://docs.knapsackpro.com/ruby/knapsack#how-can-i-run-tests-from-multiple-directories
I am trying this. Looks like what we need.

**Comment by luisramos0** [comment]
So, in master before any changes I see a green build with:
Job 1 - 367 examples, 0 failures
Job 2 - 739 examples, 0 failures, 3 pending
Job 3 - 1059 examples, 0 failures, 4 pending
Job 4 - 1081 examples, 0 failures, 2 pending

With the new setup very similar to what is recommended on the link above I see:
Job 1 - 381 examples, 0 failures
Job 2 - 754 examples, 0 failures, 3 pending
Job 3 - 1100 examples, 16 failures, 4 pending - FAILED with the 16 broken specs from order_management
Job 4 - 1090 examples, 0 failures, 2 pending

The master build runs 3246 specs and this new config runs 3314 specs. It's 68 more specs.
It should have been 79 more specs: 73 in order management plus 6 in web.

I can see the 79 engine specs run correctly, there are just 9 (79-68) specs from the main app that I need to find out why they didnt run...

**Comment by luisramos0** [comment]
PR #4989 fixes the task that runs the engines specs.

So, I'd say this issue is fixed. Can you please review and approve?

(meanwhile I leave the new config in semaphore, that means the build is broken with the order management specs, which is more real I think :+1:)

**Comment by luisramos0** [comment]
This issue is now solved with the semaphore config changes and #4989 :muscle:
