### ISSUE TITLE
Creating a Product: snail when Value* field left blank

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#4959]
## Description
When creating a new product in the backoffice, leaving the mandatory field Value* blank, generates an error 500 Snail, instead of triggering the warning usually displayed when other mandatory fields are left blank.

## Expected Behavior

A warning should appear, indicating that the field is mandatory (pic below). In the example below, only 5 errors are triggered. It would be expected that the Value* field appears on the mandatory field list, its input box underlined in red, with the red message below "can't be blank" , as for other mandatory fields:

![image](https://user-images.githubusercontent.com/49817236/81995349-f541eb00-9641-11ea-8acd-fd6cb0ae83a3.png)

## Actual Behavior
Error 500, instead of the error message and red markings described above.

## Steps to Reproduce

1. Go to /admin/products
2. Click on the [+ New Product] button
3. Fill out all the mandatory fields, except Value*
5. Click on [Create] -> the Snail should appear.

## Animated Gif/Screenshot
These settings originated error 500/Snail - the "1" in Value* is a placeholder (grayed out):
![image](https://user-images.githubusercontent.com/49817236/76248652-a76fc780-6239-11ea-92a9-931940a791e7.png)

The settings below do not break the page - not because of the upload of the picture (as initially thought :-) but rather because the Value field is not empty:
![image](https://user-images.githubusercontent.com/49817236/76248755-d9812980-6239-11ea-87e0-ff1b682eb72d.png)

## Workaround

Filling out the field is the only way to create the product.

## Severity
bug-s3: a feature is broken but there is a workaround - although it is happening quite a lot lately, and does show a Snail to the user...

## Your Environment

* Version used: v2.7.8 Striped Espargo
* Browser name and version: Chrome/Firefox
* Operating System and version (desktop or mobile): desktop

**Comment by luisramos0** [comment]
I think I had a quick at this one at the time when it was reported and I think I saw that this was the problem generating this error message:

https://app.bugsnag.com/open-food-france/open-food-france-prod/errors/5eba5cb7ccbc8300170db8c3?event_id=5ebd364c005b2b5cfaf40000&i=sk&m=fq
```

RuntimeError: You need to save the variant to create a stock item before you can set stock levels.
Location
app/models/concerns/variant_stock.rb:135 - raise_error_if_no_stock_item_available
```

**Comment by filipefurtad0** [comment]
Thanks @luisramos0,

I've just reproduced this, and it seems not to be related to picture upload at all, but rather when tries to create the product without filling the Value * field, as shown in the first picture above. Updating the description.

**Comment by luisramos0** [comment]
ah, awesome, you have nailed it :tada: 

For devs: this needs to be investigated when in dev but I found that an empty unit value field is not making the product invalid in the code, it just leaves the product without variants. And when the stock levels code runs in  products_controller#set_stock_levels, it picks up the master variant and it fails because there are no stock items. I think the fix to this issue will be:
- to make the empty unit_value field add something to @product.errors and make @product.valid? return false
- and probably also to make the set_stock_levels code raise a user friendly error message if there are no variants in the product (instead of using the master variant)

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**RuntimeError** in **spree/admin/products#create**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5ebdb2fd672f2b001880e05f?event_id=5eddedcc005b7bc6a7000000&i=gh&m=li)

**Comment by Erioldoesdesign** [comment]
Agreed on this error papercut. No design input really other than...

...from a UX pov, it doesn't surprise me that 'value' is left blank sometimes. It's a mysterious field especially for first time or new users. the 'e.g. 1' helps but value can mean so many different things from 'cost/price' to the 'integer/number' . I wonder if there is a better label for this field. Something for design & product to brainstorm!
