### ISSUE TITLE
Subscription Orders created with order total greater than sum of product prices ?!

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4960]
## Description

Following on from https://github.com/openfoodfoundation/openfoodnetwork/issues/4924 we have a new issue.

To work around the above issue I cancelled two subscriptions and recreated them. Now both of these subscriptions have created orders that are set to charge the shopper the value of the new subscription PLUS the value of the old subscription. The opened order contains only the correct subscription items but the total of the order is the sum of both the old subscription and the new subscription.

Effected orders:
R376360277
R751120551

I really want to avoid overcharging the shopper so I am creating this as an S1 for these specific orders. Once the problem is corrected we can downgrade to s3.

## Expected Behavior

The subscription order total should only include the value of the items in the order.

## Actual Behaviour

The subscription order total contains the value of the items in the order PLUS the value of previously cancelled subscription items.

## Steps to Reproduce

I think this might be related to the fact that I opened the new subscriptions before I cancelled the old subscriptions? Though that is just a guess. 

I am not sure if this will happen every time. I will look into it further but I didn't want to delay on opening the issue. This is what I did...

1. Create a subscription for a customer that already has an open subscription
2. Cancel the old subscription
3. Wait for the next scheduled OC to open
4. Check that the value of the order is greater than the sum of constituent products.

## Animated Gif/Screenshot

![Screenshot from 2020-03-09 18-55-28](https://user-images.githubusercontent.com/8669848/76247520-9625bb80-6237-11ea-8dd5-11749addd9b0.png)

## Workaround

*shrugs* I haven't found one

## Severity

I really want to avoid overcharging the shopper so I am creating this as an S1 for these specific orders. Once the immediate problem is corrected we can downgrade to s3.

## Your Environment

* Version used: UK 2.7.7
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by mkllnk** [comment]
I see the same in the admin panel. I looked at the order and can see that there are two line items for the same product. They have been created six minutes apart. The subscription code is run every 5 minutes and I'm wondering if the subscription has been processed twice.

**Comment by mkllnk** [comment]
I deleted the newer line item expecting the total to be corrected. The total is now correct showing £12.40 but the still existing line item is not showing at all.

**Comment by mkllnk** [comment]
I added the item again through the admin interface and it correctly found the old item and added one. So now we have a visible line item with quantity 2. But it also added a volunteer discount from the shipping methods. I guess that that's a mistake. It should have kept the shipping method `Pontyberem`.

I reduced the quantity to 1 and the item is still visible. I updated the shipping method back to Pontyberem and it now looks all good.
![Screenshot from 2020-03-10 10-44-24](https://user-images.githubusercontent.com/3524483/76266616-26a5df80-62bc-11ea-9ea2-ba140905aafe.png)

**Comment by mkllnk** [comment]
The second order **R751120551** is slightly different. I can see 6 items in the admin view but the order has 9 line items.
```
[#<Spree::LineItem id: 509587, order_id: 757543, variant_id: 226726, quantity: 1, price: #<BigDecimal:556a53c8cdd8,'0.167E2',18(18)>, created_at: "2020-03-05 18:02:05", updated_at: "2020-03-05 18:02:05", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c8fb28,'0.1E1',9(18)>, cost_price: nil, tax_category_id: 1>,
 #<Spree::LineItem id: 509588, order_id: 757543, variant_id: 214655, quantity: 1, price: #<BigDecimal:556a53c7f930,'0.175E1',18(18)>, created_at: "2020-03-05 18:02:06", updated_at: "2020-03-05 18:02:06", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c7e148,'0.5E3',9(18)>, cost_price: nil, tax_category_id: 1>,
 #<Spree::LineItem id: 509589, order_id: 757543, variant_id: 214735, quantity: 1, price: #<BigDecimal:556a53c7cf28,'0.125E1',18(18)>, created_at: "2020-03-05 18:02:06", updated_at: "2020-03-05 18:02:06", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c7edf0,'0.15E3',9(18)>, cost_price: nil, tax_category_id: 1>,
 #<Spree::LineItem id: 509652, order_id: 757543, variant_id: 226458, quantity: 1, price: #<BigDecimal:556a53c73a40,'0.22E1',18(18)>, created_at: "2020-03-06 11:51:06", updated_at: "2020-03-06 11:51:06", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c72640,'0.1E4',9(18)>, cost_price: nil, tax_category_id: 1>,
 #<Spree::LineItem id: 509653, order_id: 757543, variant_id: 214532, quantity: 1, price: #<BigDecimal:556a53c71ee8,'0.25E1',18(18)>, created_at: "2020-03-06 11:51:23", updated_at: "2020-03-06 11:51:23", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c704f8,'0.1E4',9(18)>, cost_price: nil, tax_category_id: 1>,
 #<Spree::LineItem id: 509654, order_id: 757543, variant_id: 214755, quantity: 1, price: #<BigDecimal:556a53c67e98,'0.19E1',18(18)>, created_at: "2020-03-06 11:51:40", updated_at: "2020-03-06 11:51:40", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c664a8,'0.25E3',9(18)>, cost_price: nil, tax_category_id: 1>,
 #<Spree::LineItem id: 509655, order_id: 757543, variant_id: 226458, quantity: 1, price: #<BigDecimal:556a53c65b70,'0.22E1',18(18)>, created_at: "2020-03-06 11:53:37", updated_at: "2020-03-06 11:53:37", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c64478,'0.1E4',9(18)>, cost_price: nil, tax_category_id: 1>,
 #<Spree::LineItem id: 509656, order_id: 757543, variant_id: 214532, quantity: 1, price: #<BigDecimal:556a53c5b968,'0.25E1',18(18)>, created_at: "2020-03-06 11:53:37", updated_at: "2020-03-06 11:53:37", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c5a068,'0.1E4',9(18)>, cost_price: nil, tax_category_id: 1>,
 #<Spree::LineItem id: 509657, order_id: 757543, variant_id: 214755, quantity: 1, price: #<BigDecimal:556a53c59a00,'0.19E1',18(18)>, created_at: "2020-03-06 11:53:38", updated_at: "2020-03-06 11:53:38", max_quantity: nil, currency: "GBP", distribution_fee: nil, final_weight_volume: #<BigDecimal:556a53c58880,'0.25E3',9(18)>, cost_price: nil, tax_category_id: 1>]
```

The first three line items were added the day before the last six were added. The last six items are two sets of the same three variants which got placed 2 minutes apart. So the second set of three are duplicates again and somehow not visible in the admin panel.

Since those two sets are less then five minutes apart and don't cross a five minute border, they were probably created by the same subscription placement job.

**Comment by mkllnk** [comment]
Now I noticed that when I worked on the first order the shipment number changed. The second order has one shipment which contains only six items in the manifest. Manifest items correspond to line items but don't link to them directly. The admin view of the order shows the manifest items which doesn't equal the actual line items of the order here.

Removing a line item from the order deletes the corresponding line in the manifest which explains why they disappear from the admin view even though there is still the duplicate line items for the same variant.

Deleting the duplicate items instead of destroying them leaves the manifest untouched. I did that and then pressed the button to recalculate fees. It now looks alright. I don't know what caused this in the first place though.

**Comment by sauloperez** [comment]
Time to check whether https://github.com/openfoodfoundation/openfoodnetwork/pull/4527 is useful.

**Comment by lin-d-hop** [comment]
Thanks for all of this @mkllnk!

The big question for me at this point is _will this happen next week?_

Do you have any insights on this?

**Comment by daniellemoorhead** [comment]
Hey @lin-d-hop, given this is now an S3 does it get put back into All the things column until it's prioritised to be done by an instance? Or is this needed to try and mitigate the same problem not happening next week?

**Comment by lin-d-hop** [comment]
Closing this as the problem is solved and its a bit of an edge case.
