### ISSUE TITLE
[+ New Variant] button -> Snail, instead of new Variant

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#4961]
## Description

Using the button [+ New Variant] at the Variants menu causes no action (the spinner briefly appears, see below), generating a Bugnsnag error. A snail does not appear to the user.

## Expected Behavior
One should be redirected to the link:
https://staging.katuma.org/admin/products/PRODUCTNAME/variants/new

## Actual Behavior
Nothing much. Just the spinner flashes quickly, but nothing else is visible to the user. An error is displayed in Bugsnag 

## Steps to Reproduce

1. Go to Products
2. Edit a variant -> https://staging.katuma.org/admin/products/PRODUCTNAME/variants
3. Press the [+ New Product] button

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/819cce10-79b2-4d7e-b67b-79d79e2cade9)

## Workaround
Alternatively one can create a new Variant under the Products menu:
https://staging.katuma.org/admin/products/

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v2.7.8 Striped Espargo
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): desktop

**Comment by luisramos0** [comment]
this is a regression from removing spree_backend for sure, so I had a quick look and found a quick fix :-)

**Comment by filipefurtad0** [comment]
This one is fixed by #4963, so I think I can close this issue now.
Closing.
