### ISSUE TITLE
Can't recreate deleted variants: [Show Deleted] button

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#4962]
## Description
The [Show Deleted] button never shows results, despite having previously deleted variants:
![image](https://user-images.githubusercontent.com/49817236/76267426-9f784d80-6262-11ea-9eaf-79067b29a525.png)

![image](https://user-images.githubusercontent.com/49817236/76267509-f716b900-6262-11ea-83c3-eb4244166d4d.png)

## Expected Behavior
The deleted variants should appear.

## Actual Behaviour
Always, an empty list (no results message) appears.

## Steps to Reproduce
1. Go to products menu
2. Create a product, and several variants
3. Delete some of the previously created variants
4. Go to https://staging.katuma.org/admin/products/PRODUCTNAME/variants
5. Press the [Show Deleted]

## Workaround
A possible workaround would be creating a product and/or variants again.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

Version used: v2.7.8 Striped Espargo
Browser name and version: Chrome
Operating System and version (desktop or mobile): desktop

**Comment by filipefurtad0** [comment]
Just like #4961, this one is fixed by #4963, so I think I can close it.
Closing.

**Comment by luisramos0** [comment]
@filipefurtad0 fyi when a PR is connected to an issue, when we merge the PR the issue is closed automatically :+1:
