### ISSUE TITLE
Missing translation key in admin product list

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4966]
## Description
Column "name" has a missing translation key

## Steps to Reproduce
1. Go to `/admin/products`

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/76326761-6b943b00-62e9-11ea-81d4-8ac153e10971.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.7.8
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Desktop

**Comment by rmklaus12** [comment]
I've had a poke at this and believe I fixed it? My first issue and it hasn't been assigned to me, but wanted to get a handle on the translations using this as my first issue test. Does it need to be assigned before I do a PR?

**Comment by RachL** [comment]
Hi @rmklaus12 just putting a comment on the issue is enough to start a PR :) Thank you! Once the PR is there it will be linked to this issue.
We use transifex for all translation related issues. I'm unclear how it translate to your local environment, but this page on the wiki should contain all info: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

Don't hesitate to ping us on slack if it is not the case!

**Comment by rmklaus12** [comment]
@RachL - I believe the code for the translation itself was fine, it was just missing the keys in the en.yml file, which is what I added. I have been reading up on the other bit, all the pieces are coming together :-) I look forward to any feedback to see if I did miss something! I will do the PRs for both now.
