### ISSUE TITLE
Order totals missing from Order Cycle Management reports

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4967]
## Description

Recent change updated the OCM reports to include the paid payment total.
However this breaks the current usage for UK users.
Hence, reverting.

## Expected Behavior

The field shows the amount for the payment method used.

## Actual Behaviour

Amount field shows the amount that has been paid.

## Steps to Reproduce

1. Reports - Order cycle management report - Payment Methods
2. View the Amount field

## Animated Gif/Screenshot

![image (1)](https://user-images.githubusercontent.com/8669848/76336510-055de700-62ee-11ea-8c43-d39525edb367.png)

## Severity

bug s4

## Your Environment

* Version used: v2.7.7
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Payment method reports](https://trello.com/c/3z3sLXgN/677-payment-method-reports)

**Comment by sigmundpetersen** [comment]
Given the more critical usage of these reports in AU as reported in #5004 I suggest we elevate this to an S2.

**Comment by lin-d-hop** [comment]
Just needs a code review... :-)
