### ISSUE TITLE
User profile tabs don't work with browser's back and forward buttons

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4971]
## Description

Similar to #4810 you can navigate through tabs on the profile page but the browser's navigation buttons "back" and "forward" don't work.

## Expected Behavior

Using the browsers back and forward buttons has an effect and takes me to previous pages.

## Actual Behaviour

Using the navigation buttons on the profile page changes the URL but changes nothing on the page. Only when you go back far enough to go away from the profile page you see an effect.

## Steps to Reproduce

1. Log in.
2. Go to your profile.
3. Click on "Account Settings".
3. Click on "Credit Cards".
4. Click on the browser's back button.
6. You would expect to be on the Account Settings tab but nothing happened.

## Animated Gif/Screenshot

![Screenshot from 2020-03-11 11-31-13](https://user-images.githubusercontent.com/3524483/76370699-dac26b80-638b-11ea-809f-da57ef9cd7b7.png)

## Workaround

Not use the buttons.

## Severity

bug-s4: it's annoying, but you can use it

This is also a papercut.

## Possible Fix

Fix it the same way as #4810.

**Comment by kirstenalarsen** [comment]
This is clear to me, happy to have included as a potential papercut

**Comment by rmklaus12** [comment]
I'd like to take this one as my first contribution, I am able to reproduce it myself.

**Comment by sigmundpetersen** [comment]
Yes, please go ahead @rmklaus12 and welcome to OFN! 🎉

**Comment by rmklaus12** [comment]
Thank you @sigmundpetersen!

**Comment by rmklaus12** [comment]
Thank you @sigmundpetersen!

**Comment by RachL** [comment]
hello @rmklaus12 are you still working on i? I'm asking in order to know if I should un-assigned you or not. Thanks :)

**Comment by rmklaus12** [comment]
@RachL - please unassign me. It was a bit more than I can do at the moment and Danielle has pointed me to some better issues. Thank you!

**Comment by RachL** [comment]
no problem!

**Comment by Erioldoesdesign** [comment]
No design needed on this one, all makes sense. Great thinking through the UX on these tabs :)
