### ISSUE TITLE
[Mobile ux] Edit orders cart on shopper's profile Orders page does not display on mobile

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4973]
## Expected Behavior
I should be able to edit my order from the orders page.

## Actual Behaviour
There is no edit order button. 

## Steps to Reproduce
1. Place an order in a shop that allows for editing orders
2. Go to the orders page on mobile
3. Edit link does not appear against order
4. Go to orders page on desktop
5. Edit link does appear against order

## Animated Gif/Screenshot
Mobile version
![Screen Shot 2020-03-11 at 12.08.41 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/eb029174-ab12-469f-8861-01c6fd3049a1)
Desktop version
![Screen Shot 2020-03-11 at 12.08.52 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/f0cbf26e-eaf1-44aa-99ff-77cfb0df860e)

## Workaround
Do it on desktop

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
Hello, this is not a bug, this is explicitly done on the code for a very good reason, the extra column doesnt fit the page.
Before:
![image](https://user-images.githubusercontent.com/1640378/81417160-ab896a00-9142-11ea-8dfa-81f738e4ea43.png)

After:
![image](https://user-images.githubusercontent.com/1640378/81417103-96144000-9142-11ea-87d7-3ef30c04856c.png)

The easiest way out of this is probably to replace the cancel button with the edit button. The order can be cancelled on the edit order page (where the edit link takes the user to).
![image](https://user-images.githubusercontent.com/1640378/81417446-1aff5980-9143-11ea-971d-f00bd71d72f4.png)

Do you see any problems with this or shall I go ahead?

**Comment by lin-d-hop** [comment]
Sounds good to me. I feel like this is familiar UX from other sites.

**Comment by daniellemoorhead** [comment]
Yep, sounds good Luis. Change it to edit.
