### ISSUE TITLE
Release v2.7.9 Bacallà a la llauna

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#4985]
Steps: 

- [x] Include translations
- [x] [Draft new release] :point_right: https://github.com/openfoodfoundation/openfoodnetwork/releases
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1234
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by RachL** [comment]
The release is ready to go :) Testing notes: https://docs.google.com/document/d/1FiVut0pnWv4pQbkq8uR8THZpeq3J_Smaz1NStEcaqyk/edit#

**Comment by sauloperez** [comment]
The regression we found demands a hotfix release. https://github.com/openfoodfoundation/openfoodnetwork/pull/5006 was manually done in AU, where it became a serious problem (read the description of the issue) but this must be deployed to all servers, especially AU or we risk ending up in the same state.
