### ISSUE TITLE
[Spree 2.1] Investigate order states?

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4986]
In Spree 2.1 order states are not as expected in some cases during the order edit workflow. This might need investigating to see if there are any other related issues.

Context: https://github.com/openfoodfoundation/openfoodnetwork/pull/4979#discussion_r391540220

**Comment by luisramos0** [comment]
I think I clarified this one in 4979 by identifying this was caused by #4775
