### ISSUE TITLE
SCA Snail 404 - with test card 4000008260003178 (insufficient funds)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5007]
## Description
Error 404 - Snail - has been observed to appear when attempting payment with the test card 
4000008260003178, a Stripe test card - please see https://stripe.com/docs/testing#regulatory-cards

## Expected Behavior
After successful authentication, the user should be directed to the shopping cart, with the error message "Your card has insufficient funds.", which should appear in a red warning (top left of the screen).

## Actual Behaviour
Error 404 Snail has been observed. At times, the expected behaviour occurred.

## Steps to Reproduce

- Add an item to your cart
- Choose Stripe SCA as payment method
- Attempt to perform the payment with the test card 4000008260003178.

## Workaround
Workaround would be to use a different card.

## Severity
bug-s3: a feature is broken but there is a workaround
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Your Environment
Katuma-staging
Ubuntu 18.04, Chrome.

**Comment by Matt-Yorkley** [comment]
Just an idea... is there some way we can add some tests that use the dummy stripe cards and make real calls to a stripe testing account as part of the CI build?

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley,
That's a great idea. I'll try to investigate this...
Thank you.

**Comment by Matt-Yorkley** [comment]
Cool! It was just an idea, not a direct response to the issue. How's the `rspec` going?

**Comment by filipefurtad0** [comment]
Going slowly, at the moment :-) But I'm keeping at it.
I am mostly gathering all aditional tests we could need and checking mostly how the existing ones work.
Testing (all) cards and the respective outcomes sounds great for CI, so I'm adding this to the "Automated Tests" pipe column - we have one now, actually since we last met hehe :-)

**Comment by luisramos0** [comment]
I cant replicate this problem locally or in staging FR. It works correctly every time..

**Comment by filipefurtad0** [comment]
It's now working in Katuma now as well, but I remember not being able to reproduce this all that often.
Should we keep the issue open as a reminder of this situation, or would be closing more appropriate?

**Comment by luisramos0** [comment]
In these cases we close the issues and re-open if they happen again.

**Comment by filipefurtad0** [comment]
Closing for now - but keeping an eye on this.
