### ISSUE TITLE
Snail 500 while using Paypal (possibly Stripe SCA related)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5008]
## Description
Attempting to perform a checkout payment with Paypal Express, in staging server with implemented Stripe SCA, resulted in a Snail 500, instead of redirection to Paypal authentication website, generating a Snail (visible to the user) and the bugsnag error, below:
https://app.bugsnag.com/katuma/katuma/errors/5e6e534fb84fb400174e9864?event_id=5e6e534f00582cc715870000&i=sk&m=nw

## Expected Behavior
Attempts to pay with Paypal should redirect the user to the Paypal-authentication site.

## Actual Behaviour
Snail - Error 500
Bugsnag: https://app.bugsnag.com/katuma/katuma/errors/5e6e534fb84fb400174e9864?event_id=5e6e534f00582cc715870000&i=sk&m=nw

## Steps to Reproduce
1. Add a product to cart and check-out
2. Choose Paypal Express paying method
3. Press "Place order now"

## Workaround
Workarounds include using a different payment method, or trying again with Paypal.

## Severity
There are workarounds, but it may potentially affect every user using Paypal.

bug-s4: it's annoying, but you can use it
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Your Environment

Ubuntu 18.04, Chrome.

## Possible Fix

So far, observed in Katuma and Australia-staging servers, after Stripe SCA / PR #4757 was deployed, although these should, in principle, not be related, since this PR introduces no code changes to Paypal payments.

**Comment by lin-d-hop** [comment]
Is this because the SCA payment methods were still active?

This is definitely more than an s4 if users will experience a snail at checkout... s2.

**Comment by RachL** [comment]
I don't understand what "under Stripe SCA" means. I've tested Paypal checkout during release testing and it was working. ping @lin-d-hop @filipefurtad0

**Comment by filipefurtad0** [comment]
Hey!

@lin-d-hop: I don't know if that is the reason, but should active SCA payment methods prevent Paypal Express from working?

@RachL: "under Stripe SCA" is perhaps not that clear... Thanks for pointig it out. I am changing this to perhaps to "possibly Stripe SCA related"? This bug was observed while testing a Stripe SCA PR - #4757. This only happened after this PR was deployed, allthough the Paypal code was not changed.

I just figured it was good to perhaps set context.

**Comment by RachL** [comment]
@filipefurtad0 @lin-d-hop 

If it does indeed break paypal, it's yes an s2 but more importantly a release blocker.  But now I'm reading also the comment that lead you to create this issue:

> UPDATE: I just re-staged in FR, and checked out using a newly set-up Paypal method, with "fresh" credentials -> all good. So I am guessing, there is/was something wrong on my test credentials, which sometimes - apparently not always - generates a Paypal-Snail. Anyway, all good from this side!

Can we stage master in staging FR and try to checkout on the Bacalla farm? This is the farm I've set up paypal with for the last release. If this is working, I would leave this as an s4.

**Comment by filipefurtad0** [comment]
Thanks @RachL,
I was about to re-stage the PR to double check - but it's merged already so, I'm moving on to stage master. I'll post back here in a moment.

**Comment by filipefurtad0** [comment]
Ok, it didn't break it:
- build #1247 of master was staged to fr-staging on Tuesday, Mar 17 2020 at 15:50
- Order #R840352458 was payed with Paypal.

Shall we keep S4, then? Since it was not yet observed in production. I'll wait for your feedback @RachL and @lin-d-hop. Thank you!

**Comment by RachL** [comment]
When we cannot reproduce something we saw only on a staging server I would be in favor of downgrading the severity. If it was me I'm not even sure I would have opened the issue, but I'm not an example. What do you think @lin-d-hop ?

**Comment by luisramos0** [comment]
Hello, I recommended creating the issue. The question is: can we reproduce this systematically in some staging server?

**Comment by filipefurtad0** [comment]
This issue is stale, closing.
