### ISSUE TITLE
Can't access edit order 'payments' tab if order has been cancelled (or resumed)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5018]
## Description
I cancelled an order. I expected there to be an automatic stripe refund (wishful thinking? did this ever used to exist?) but there wasn't. So I went in to edit the order and try and refund from the payments tab, as per user guide

## Expected Behavior
I should be able to edit an order, go to the payments tab and refund (or do other actions)

## Actual Behaviour

I can't access the 'Edit Order' payment tab. At first I thought it was just for cancelled orders, but then I resumed the order and I still can't access it.

I just keep getting told "Please fill in customer info" but as far as I can see it is all filled in
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/052f6994-31f7-4e04-bcec-11e55fb3ca0d)

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/7428208b-dc53-49e9-9982-cd2cd45f6f33)

It seems to be ok for other orders, so perhaps is something that is triggered by an order 'cancellation', but it then is impossible to refund the order if we can't access the payments tab.

So it seems that I can't cancel and refund an order? 

## Steps to Reproduce

1. Create an order and pay by Stripe
2. Cancel the order
3. Edit the order, select payments tab (intending to generate refund)
See error, and get stuck on customer details tab

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by tschumilas** [comment]
Thanks for posting this.  FYI -  I wonder if we created this when we deleted 'resumed' orders.  People might remember -  maybe a month or so ago -  I think we deleted them because we couldn't figure out why someone would resume an order.  Maybe this is why -  if an order is cancelled before payment is reconciled,  the user should be able to resume that order to process a refund.  (But - it makes me wonder,  why isn't a refund automatically processed when an order is cancelled?)

**Comment by tschumilas** [comment]
I'm not sure I agree this is s3.   If a user is trying to manage orders in OFN,  they need to be able to refund cancelled orders.  There is no workaround -  the user has to manually refund outside of OFN,  and then the customer's OFN account is inaccurate.   I'd vote for s2.

**Comment by lbwright22** [comment]
can this be classed as a potential papercut issue?

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX of the ship button and order states](https://trello.com/c/kauOVQHU/786-ux-of-the-ship-button-and-order-states)

**Comment by luisramos0** [comment]
Can you please clarify the details for "I can't access the 'Edit Order' payment tab." _before_ you resume the order? What exactly happens?
I dont understand why this is not an S2.

**Comment by lin-d-hop** [comment]
This is the way OFN has worked for as long as I remember.

The workaround is to log into Stripe and refund the order on the hubs behalf.

I'm not clear on the proposed fix:
1. To make reactivating an order work again?
2. To make the payments tab functional on cancelled orders?

**Comment by kirstenalarsen** [comment]
I think that the proposed fix is either:
2. make the payments tab functional on cancelled and resumed orders
OR 
3. automatically refund credit card payment when the order is cancelled

I would be happy with either. The second one is perhaps more complex - potentially leading to different behaviour in stripe vs other payment methods; and still needing a login to stripe to take the payment again if the order is cancelled by accident, so on balance I'd probably lean towards 2.

I don't think it's ok that a Hub cannot refund a cancelled order for themselves without asking an instance manager

**Comment by kirstenalarsen** [comment]
@luisramos0 i think the answer to your question is described above - you try to click on the Payments tab but it just keeps taking you to the Customer Details tab

**Comment by luisramos0** [comment]
ok :+1: thanks!
So we keep it S3 and agree the solution is option 2 :+1:

**Comment by RachL** [comment]
Aligned with option 2 as I think we have somewhere an issue to issue credit in bulk.

In the future, I think I would explore automatic refund if the customer was cancelling the order. But let's see with more user feedback if this is needed!

**Comment by emilyjeanrogers** [comment]
The new "Actions" menu also doesn't work for cancelled orders - nothing happens on click.

**Comment by luisramos0** [comment]
That will be a problem between html and angular related to linksDropdown. I dont think the solution will be related to the solution of the original issue here, maybe it should be on a separate issue?

**Comment by lbwright22** [comment]
Even if you manually refund an order as in the workaround above, it is not possible to change the payment status from 'Credit Owing' to 'Paid' or 0.  This is confusing.

Testing below to narrow down what is actually happening now #5270 is fixed.

1. Customer places and order and the payment is recorded.
![beforecancellation](https://user-images.githubusercontent.com/45104035/94004612-df34fb80-fd94-11ea-87c6-c347f979b8e3.jpg)
customer view:
![customerbeforecancellation](https://user-images.githubusercontent.com/45104035/94004727-0be91300-fd95-11ea-9ae6-530e6425fd40.jpg)

2. Order is cancelled. No refund issued prior to cancellation.
![aftercancellationlistingorders](https://user-images.githubusercontent.com/45104035/94004826-29b67800-fd95-11ea-836a-fe23a59ebb6d.jpg)
Under Customer Transaction history the transaction no longer appears even though no refund has been noted on the system:
![customeraftercancellation](https://user-images.githubusercontent.com/45104035/94004919-58cce980-fd95-11ea-945d-f7733a12dbf6.jpg)
In Payment Method Reports, the cancelled order does not contribute to the customer's balance even though it is noted under listing orders as 'credit owing'.

3. Removing items from the cancelled order does not change the payment status
![aftercancellationlistingorders-modified](https://user-images.githubusercontent.com/45104035/94005165-cc6ef680-fd95-11ea-9e6e-31832aa85263.jpg)

**Comment by andrewpbrett** [comment]
I was able to reproduce this issue and implemented the simpler of the two options ("make the payments tab functional on cancelled and resumed orders") in #6982. 

When I tested this, I can now access the Payments tab for a canceled order with a completed payment and void the payment. Is that a sufficient solution?

**Comment by RachL** [comment]
@andrewpbrett I think it's a good option 👍
