### ISSUE TITLE
Invoice displaying the enterprise address instead of the customer's address

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#5019]
## Expected Behaviour
The customer's address displays under their name on the invoice.

## Actual Behaviour
The enterprise's address displays instead, even though it's showing the correct name and email/phone number.

## Animated Gif/Screenshot
![Image from iOS (2)](https://user-images.githubusercontent.com/10949052/77040279-b90c5880-6a0b-11ea-81f4-40462be3f8b0.jpg)

## Workaround
Go into the application and find the customer address and write it on the invoice. But this is a shit workaround when you have A LOT of orders.

## Severity
I'm calling this a sev-2 as the workaround is pretty unacceptable and this is a core part of the fulfillment process.

bug-s1: a critical feature is broken: checkout, payments, signup, login
**bug-s2: a non-critical feature is broken, no workaround**
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by mkllnk** [comment]
There has been a recent change to that address (a couple of months ago maybe). Maybe we change only one invoice template. There are two. It's displaying the delivery address which seems to be the food hub in this case.

**Comment by mkllnk** [comment]
c5229dd763b46a9cbdb340e1eafefba888e0dd03 changed invoice template2 but not template1. This is a good-first-issue or papercut size.

**Comment by kirstenalarsen** [comment]
they have 5 shipping methods. all except one (nightingale) is currently set to pick-up. So i guess we need to agree whether this is an error or is how it should behave. I think the tricky thing is the difference between an invoice and a packing sheet. They are often used as packing sheets (hence use of shipping address), but as invoices probably should be billing address? @daniellemoorhead @RachL

**Comment by sigmundpetersen** [comment]
For reference, the recent change was in #4560 that fixed #4473. It was released with [v2.6.8](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v2.6.8)

**Comment by RachL** [comment]
Ah yes so actually, we did not change anything "recently" to this template, we only changed the French template which needed a billing address in January: https://github.com/openfoodfoundation/openfoodnetwork/pull/4560#issuecomment-569226598

So I doubt that this is a bug recently introduced. Unless they changed recently their shipping method from home delivery to pickup.

I don't know what is your legal requirement, but in terms of UX, a from => to field makes me understand that the "to" field requires a shipping address (either the customer if it is a home delivery, or the hub if it is a pick-up). Not a billing address. If you need a billing address I think it should be somewhere else in the invoice. Is it correct?
