### ISSUE TITLE
No subscriptions launched for a particular OC

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5021]
## Description
We have a hub with regular failure with subscriptions. I've never opened an issue because I can't find how to reproduce them.

This time I'm still not able to reproduce but it is the first time absolutely ALL their subscriptions did not created orders.

## Steps to Reproduce

1. Hub id: 189
2. OC id : 3084 https://www.openfoodfrance.org/admin/order_cycles/3084/edit 

I've checked stocked, rhythm... but can't find a reason...

## Severity
bug-s2 or s3 ?

## Your Environment

* Version used: v2.7.10
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Dekstop

**Comment by lin-d-hop** [comment]
I would suggest you upgrade this to s1 to at least get the subs created. I believe devs can rerun the Subs Placement Job.

If they can find an underlying cause while doing this, that would be more likely an S3...

**Comment by RachL** [comment]
@lin-d-hop  Good to know there is this option of rerunning them! The hub already placed them manually again, so we can't rerun them today I'm afraid...

**Comment by filipefurtad0** [comment]
This sub `https://staging.coopcircuits.fr/admin/subscriptions/15/edit` is corrupt, for some reason... Sometimes, this led to a failed SCA payments. Attempting to capture it, i.e., clicking the :heavy_check_mark: at /admin/orders?q[s]=completed_at+desc triggers bugsnag - no snail seen. I've checked the error and this seems to have been triggered a few times in production as well. This is related to subs failing... The order is placed, but the confirmation emails don't arrive.

I'm not so sure this is a StripeSCA issue: if you take all parameters (customer and card, payment method, product, schedule) and create a new subscription, then all works fine. But maybe looking at `subscriptions/15/` will provide some clues...

**Comment by lbwright22** [comment]
Another occurrence of this:

Hub: Helston Local Food Hub
Order Cycle named 'Feb 6th 2021' should have generated an order for a Subscription on 28th Jan.

Products are in stock and in the order cycle
Schedule is attached to order cycle
Subscription is displaying as:
![helstonsub](https://user-images.githubusercontent.com/45104035/106385183-cb467980-63c6-11eb-95ef-6d2c5a79cdce.jpg)
on 31st Jan

**Comment by lbwright22** [comment]
This happened again for the same Hub (Helston Local Food) with order cycle '13th Feb'.

After some investigation, there were two schedules with identical names for the same hub. The hub manager was assigning the 'wrong' schedule to the order cycle (unknowingly) and hence the schedule was not generating the order.  

Does there need to be a 'safety catch' to prevent two schedules with identical names from being created?

**Comment by sauloperez** [comment]
> Does there need to be a 'safety catch' to prevent two schedules with identical names from being created?

This does make sense in terms of UX, as the common `(2)` suffix operative systems append to filenames.

**Comment by lbwright22** [comment]
This happened just now for 
HUB: Helston Local Food
OC 207576

Subscription 364 did not generate when the OC opened. 
Looking at the subscription when the OC was open showed that the items in the cart were all in an active OC (ie. no red 'there are no open or upcoming order cycles....')
Under the Order table no pending orders.

Work around:
Pause the subscription
Re-activate the subscription

Order is generated (ID R364211045)

**Comment by lbwright22** [comment]
Same thing occurred for order R147425008 for Banc Organics OC 207438, subscription 130.

**Comment by lin-d-hop** [comment]
Glad we havent seen this for a while :sweat_smile:

**Comment by lin-d-hop** [comment]
@andrewpbrett Do you think the work you've done on subs has meant that this can be closed?

**Comment by andrewpbrett** [comment]
Yes, I think we can close this - the work Pau and I did to refactor the PlacementJob means that the code has changed pretty substantially since March 2020 (and since March 2021) and it's unlikely that the same thing that was causing these reports is still present. If we see something similar in the future I'd recommend a new issue.
