### ISSUE TITLE
7. [mobile ux] View cart from main nav

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#5024]
## What is the problem we are solving 
Currently the dropdown view cart functionality does not work on mobile, and is in the old design for desktop. Shoppers on mobile are taken directly to the edit cart screen and have no option to view what they've added to the cart from the dropdown in the same way that they can on desktop.

On desktop the design is not optimal, red buttons, terrible spacing, and too many repeating buttons.

![Screen Shot 2020-03-20 at 4.34.46 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/a6acedf7-f9b6-4a22-90b0-b65e24d623e4)

## Success factors = expected outcome 
- [ ] Shoppers on desktop will interact with their cart in the same way they can on desktop.
- [ ] The design of the shop cart will no longer be discordant.

## Design overview
mobile
![Screen Shot 2020-03-20 at 4.38.08 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/60d84519-265f-4f59-8797-8c7424ce4624)

![Screen Shot 2020-03-20 at 4.38.14 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/8f4d8298-5011-41f5-b48c-439ace901d47)

tablet
![Screen Shot 2020-03-20 at 4.38.35 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/2f62534e-c5ea-4d79-b3d4-0dea5050a297)

![Screen Shot 2020-03-20 at 4.38.44 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/173e5d1a-3599-4aea-ab4a-e1a23d1204de)

desktop
![Screen Shot 2020-03-20 at 4.38.53 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/7c0b0dba-44ef-46a6-85c7-d071b2c85c55)

![Screen Shot 2020-03-20 at 4.38.58 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/c8a86c7b-f8d1-481d-9871-edf28531b894)

**Comment by daniellemoorhead** [comment]
Hey @Matt-Yorkley this is the last epic to be done in the mobile shopping work. I think you did some previous work on this...maybe you'd like to finish what you started?

![](https://media.giphy.com/media/3orif75hTF6XTFLCec/giphy.gif)

**Comment by Matt-Yorkley** [comment]
Yeah, I can take this one. I think these cart bits won't clash with the other mobile PRs :tada:

**Comment by daniellemoorhead** [comment]
Time to do a design sweep @yukoosawa. At your leisure. On staging.

**Comment by RachL** [comment]
@daniellemoorhead it looks everything is done here. Can we close this epic?

**Comment by daniellemoorhead** [comment]
No, there will be a final design sweep by yuko.

**Comment by daniellemoorhead** [comment]
Ok, so all that's left in this epic to complete is bug #5916 - this can be closed once that bug is resolved.

**Comment by Matt-Yorkley** [comment]
I'm closing this epic, the work has been finished and in production for months and it doesn't need to be sat in dev-ready. There's a small attached issue (#5916) which is vaguely related but also goes beyond the scope of just this epic, and relates to modal and scrollbar behavior in general. That can stay open as a standalone mobile issue. 

As a I side note I don't think we actually can/will fix #5916...
