### ISSUE TITLE
When showing profiles in Group/Hubs, should be able to click on the name and pop up the profile modal

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#503]
just like on the Hub list page . .
![image](https://cloud.githubusercontent.com/assets/2911176/7193679/8c97d698-e4e7-11e4-8b84-3b2f34685ae8.png)

currently nothing happens

**Comment by mkllnk** [comment]
Pushed to group-pages, ready to be tested.

**Comment by kirstenalarsen** [comment]
still not staged?

**Comment by mkllnk** [comment]
Probably overlooked. I opened a pull request now #567.
