### ISSUE TITLE
Miscalculation of GST after changing cart contents

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#504]
The first time I filled my cart, the GST calculated correctly, but then I removed some products, and then the GST was incorrect. It didn't hold on to the original GST calculation, but calculated a new, incorrect number.

The issue corrected itself after checkout- the order conf page was correct. The order conf email did not mention GST.

![miscalculation](https://cloud.githubusercontent.com/assets/10843056/7197730/ca616846-e527-11e4-8aff-9cdc0c7a8ce5.png)

**Comment by kirstenalarsen** [comment]
Hi @sstead - I'm having trouble replicating this one. I think it's Coop with no P-OC, salmon should include GST but not trout. So GST in the order is $1.82 for one bit of salmon

When I change the salmon to two bits, and hit update, it seems to recalc correctly to me

![image](https://cloud.githubusercontent.com/assets/2911176/7289869/5ec2553c-e9b9-11e4-8912-0e8ad1d89fab.png)

and then i change back to one and recalcs again
![image](https://cloud.githubusercontent.com/assets/2911176/7289875/72f0cf3e-e9b9-11e4-8ffc-7e655c7caf32.png)

can you see if you can still create this problem?

**Comment by sstead** [comment]
Yeah, it's hard to replicate... but I can replicate it with one particular set of steps....
- Shop at Demo Hub, on staging2.
- Select one of each (6) items.... then hit edit cart.... and it shows correct GST
![image](https://cloud.githubusercontent.com/assets/10843056/7310493/5cad82be-ea70-11e4-8fba-e4266f38a7c2.png)
- Then set the item number to zero fall all products except the Salmon and Trout. Click update. After updating it's no longer accurate...
![image](https://cloud.githubusercontent.com/assets/10843056/7310503/90a215d0-ea70-11e4-9cf0-7da6e44974d0.png)
- Then go and checkout with just the 2 fish products... and it recalculates accurately again...
![image](https://cloud.githubusercontent.com/assets/10843056/7310506/b1bf1114-ea70-11e4-9aac-41630b571297.png)

* I've checked and there are no fees in this order cycle

**Comment by daniellemoorhead** [comment]
@oeoeaio will this be fixed as part of the work you're doing around tax?

**Comment by myriamboure** [comment]
I retested and this seems to be solved, seems the basket page update dynamically if you set up the quantity to zero. @sstead if you think there is still a problem feel free to reopen.
