### ISSUE TITLE
Brief downtimes on French prod

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5049]
All servers are experiencing record usage, and France specifically has had 2 small downtimes in the last 24h.

We need to investigate the data a bit to find the pain points and then maybe plan some follow-up firefighting...

As a side note, our lack of full monitoring across all servers is a big drawback at this point.

**Comment by Matt-Yorkley** [comment]
I did some quick investigation on this.

I can't see any glaring specific things that are obvious causes of the small downtimes, I think it's just high usage. There were one or two actions that maybe used slightly more memory at the relevant times (I won't mention them specifically) but they all appear to be totally normal usage.

One thing I did spot (near the top of the list) was some wildly inefficient queries going on in the `CheckoutController` that I'm pretty sure are totally unnecessary. We're querying mountains of product properties and producer properties data in the cart edit page, and I don't think we actually need it there at all (it's just a consequence of re-using fat serializers in places they shouldn't be re-used).

Also I think we it would be really valuable at this point to have a little crack at getting some quick wins via #4763

**Comment by lin-d-hop** [comment]
Yes please!

**Comment by Matt-Yorkley** [comment]
I rechecked the `CheckoutController` idea, and actually it seems like impact would be fairly minimal.

I'd still recommend we try #4673 though.

**Comment by luisramos0** [comment]
the number of visits today was not as big as last week... I see the access log in matomo and I cant find anything special there...
