### ISSUE TITLE
"Nouvelle variante" button has no visible effect

### ISSUE THREAD

**Issue by blarsy** [openfoodfoundation/openfoodnetwork#5053]
## Description
While trying to add a variant for one of my products, I clicked on "Nouvelle variante". There has been a brief appearance of the standard waiting wheel, but not effect on the UI whatsoever.
![image](https://user-images.githubusercontent.com/3703906/77350310-97c5a800-6d3c-11ea-8373-2d5caa773aa7.png)

## Expected Behavior
I expected clicking on the button to have the browser automatically navigate to the new variant screen.

## Actual Behaviour
Well, it doesn't ;-)

## Steps to Reproduce
1. Navigate to https://www.openfoodnetwork.be/admin/products/tomate-2/variants as "le comptoir fermier du Rosoir"
2. Click on the "Nouvelle variante" button

## Workaround
By sneaking around, I saw this in my browser console:
![image](https://user-images.githubusercontent.com/3703906/77350720-39e59000-6d3d-11ea-95c3-0daeed886621.png)

... and when I navigate directly to https://www.openfoodnetwork.be/admin/products/tomate-2/variants/new by tweaking the URL in the browser's address bar, the new variant screen appears.

## Severity
Well, for me, as a former web programmer, it's an bug-s4, but probably a bug-s2 for a mere mortal ;-)

## Your Environment
* Version used: The one live on the 23/03/2020 19:30 at openfoodnetwork.be
* Browser name and version: I use Brave 1.4.96, but I could reproduce using Chrome Version 80.0.3987.149 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): mobile Macbook pro with MacOS Catalina 10.15.3

**Comment by RachL** [comment]
@blarsy welcome and thank you so much for your contribution!! However I believe this is already solved in the new release that will be deployed to Belgium tomorrow: https://github.com/openfoodfoundation/openfoodnetwork/pull/4963

You should have the fix already in the master branch you are using in development. Can you confirm?
