### ISSUE TITLE
As a hub, I can give my suppliers access to my customers' name and firstname

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5054]
## Description
**- As a:** enterprise manager
**- On page:** `/admin/enterprises/NAME/edit#/shop_preferences`
**- I want to be able to do:** allow my producers to see my customers names and firstnames in the following reports:

- Orders and distributors (one column: Customer name)
- Bulk Co-op (one column: Customer name)
- Order Cycle Customer Totals (one column: Customer name)
- All Customers (**name and first names are two columns on these ones**!)
- Enterprise Fee
- All Order Cycle Management  (**name and first names are two columns on this one**!)
- All Sale Tax
- Xero invoices
- All packing reports  (**name and first names are two columns on these ones**!)

**All new content must be translatable (it's not an English word but I mean no translation key missing at the end!).**

## Acceptance Criteria & Tests

*Scenario 1: Shop preferences for the hub*
1. As a hub, I can go on `/admin/enterprises/NAME/edit#/shop_preferences`
2. And see this new radio button at the bottom of the page:
![image](https://user-images.githubusercontent.com/6525576/77352660-d01ab580-6d3f-11ea-981d-bc004bfa0d74.png)
3. By default the radio button is at NO
5. The _what's this_ tooltip displays the following tip: `Enable your suppliers to see your customers name and firstname in reports`.
4. If I switch it to YES. All Names and first names of my customer will be visible to **ALL** my suppliers. Emails and phone numbers will remain hidden (which means the word "hidden" is displayed or the column is empty).
5. I need to save at the bottom for my changes to be saved.
6. Once saved I see this green message at the top of my screen: `Enterprise "NAME" has been successfully updated!`

**Comment by RachL** [comment]
@sauloperez about the sentence that helps a suppliers to understand that the fields are hidden because the hub is not allowing them to have access to that info.

The ideal case would be to show the sentence only if there are hidden fields. So I wanted to place the sentence below the action button, but I've just noticed the page is not reloading if I download a spreadsheet. Can you confirm that?
In that case I need to put the sentence above the action button with a more general sense like `if names and firstnames are hidden, please contact your hub and ask him to update their shop preferences`.

Also here I have one issue covering the button for the hub AND the result for the producer. Do I need to split in 2?

**Comment by sauloperez** [comment]
Excellent work @RachL! :clap:

**Comment by sauloperez** [comment]
:hankey: I see that moving the button to the bottom makes it hard to reach it when the rendered table is too long.
