### ISSUE TITLE
Create a Matomo event for the new shop preference radio button

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5055]
## Description

Here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5054

We introduce a new button in the shop preference menu.

We don't know how many users will activate this and we have no way currently to do that.

The purpose here is to be able to have at the end a Matomo event that count the number of shop who enabled or disabled it.
What could be interesting as well is to store the date at which they have done the change. Not sure what's possible here

**Comment by mbudm** [comment]
Given @rachel’s recent discovery of the matomo usage figures ballooning do we want to gauge whether we can afford to expand matomo tracking to admin pages?

If so then this would be a process of:

- a PR to add the matomo embed script to a base admin template partial
- decide if we use the existing matomo settings to turn on tracking for admin
- assess any privacy/content issues that aren't covered with the current privacy policy

Then after that the actual act of adding the event in matomo tag manager is fairly trivial.
