### ISSUE TITLE
Error message on account creation, a 401 on https://www.openfoodnetwork.be/user/spree_user underlies

### ISSUE THREAD

**Issue by blarsy** [openfoodfoundation/openfoodnetwork#5057]
## Description
Friend of mine fails to create an account, could reproduce using one of my email address
This time I checked the issues, including the closed ones (I may have missed it though)

## Expected Behavior
Go past the first subscription screen, after validating email and password

## Actual Behaviour
This:
![image](https://user-images.githubusercontent.com/3703906/77363275-bd5dac00-6d52-11ea-8550-8e3c75086d6d.png)

## Steps to Reproduce
1. Went to https://www.openfoodnetwork.be/register
2. Used the email address in the screenshot (it is flooded with spam already, so I don't paste it here ;-) )
3. Used an auto-generated pwd: LFsfANyKbmGPV3DV

## Animated Gif/Screenshot
See "actual behavior" above

## Workaround
None found

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: The one live on the 23/03/2020 22:10 at openfoodnetwork.be
* Browser name and version: Brave 1.4.96
* Operating System and version (desktop or mobile): mobile Macbook pro with MacOS Catalina 10.15.3

**Comment by luisramos0** [comment]
Hi, thanks for reporting the problem. We are aware of this problem. Because of the increase in usage of the platform all over the world, some email accounts went past their limits and emails stopped being sent. The Belgium account has not been recovered/upgraded yet. I believe the failed emails will be sent when the account limit is increased.

**Comment by lin-d-hop** [comment]
I can confirm. OFN UK emails went down for the same reason and we experienced this.

**Comment by sigmundpetersen** [comment]
If this was due to email quotas and that has been resolved, I think we can close.
