### ISSUE TITLE
Snail adding new product if nothing entered in Value field

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5058]
## Description
When adding a new product, if the Value field is left blank, when clicking on the Create button, the snail will appear.

## Expected Behavior
An error message asking to enter an amount in the Value field

## Actual Behaviour
Snail

## Steps to Reproduce

1. Add New Product
2. Complete all required fields except Value
3. Click Create
4. Snail

## Severity

bug-s3: a feature is broken but there is a workaround

## Possible Fix
Error message visible to customer, instead of Snail

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**RuntimeError** in **spree/admin/products#create**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5db4208c2ab8f4001989c256?event_id=5e7939ac0058ea22988b0000&i=gh&m=li)

**Comment by luisramos0** [comment]
this is a dup of #3912

**Comment by mkllnk** [comment]
This issue has been unlinked from an error in Bugsnag
[**RuntimeError** in **spree/admin/products#create**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5db4208c2ab8f4001989c256?event_id=5e816edf00595296c5f60000&i=gh&m=ul)
