### ISSUE TITLE
Order Silently Failing

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5059]
## Description

I have another case of an order failing silently.
I have checked the payment methods and the shipping methods and none use the weight calculator so I think we can rule out #4695 

Hub: Tamar Valley Food Hub
OC:
Orders: (note all are in cart state. Only one to be placed)
R116675887
R782766733
R613036265
R443405243
Shipping: Plymouth, Saltash & Liskeard - DELIVERY to home or workplace
Payment: Paypal

## Expected Behavior

Checkout successful

## Actual Behaviour

Hangs on checkout and nothing happens.
No redirection to paypal screen.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: 2.8 UK
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5e3f69702cc7af001991c233?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[search][0][type]=eq&filters[search][0][value]=pilgrimrobert%40msn.com

**Comment by lin-d-hop** [comment]
Being unable to track it down this order was placed over the phone.

I suspect this was a combination of #4695 and potentially trying to reuse the same cart from yesterday leading to a broken cart state.

I'm closing. The user will try again next week and call if he has troubles.
