### ISSUE TITLE
Error 400 on checkout with Stripe SCA

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5061]
## Description

On French prod
Hub La p'tite coop ID 1053

Order https://www.openfoodfrance.org/admin/orders/R673875614/edit

The user was unable to pay by credit card. The red message appear "Payment failed. Please contact us to finish your order".

So they checkout by cash, no problem.

All shipping methods of that user are NOT using weight calculators.

## Steps to Reproduce
1. I've put the same product as order https://www.openfoodfrance.org/admin/orders/R673875614/edit
2. And indeed I cannot checkout by Stripe

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/77441433-b7ff7080-6de9-11ea-9c4e-b8bd5474b263.png)

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: v2.8
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
false alarm, right?

**Comment by RachL** [comment]
Ah yes, weird I thought I had posted here as well: wrong payment method, closing!
