### ISSUE TITLE
Notifications to enterprise users in /admin for release updates, downtime, and other announcements

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#5066]
## Description

**- As a:** OFN instance manager
**- On page:** /admin
**- I want to be able to do:** easily notify my enterprise users of changes to the software, or downtime, or any kind of announcement that I need to make to them.

## Proposed Solution

We can use [headwayapp](https://headwayapp.co/) to do this. I use it with my other job and it's a really simple way of providing updates without having to build the notification platform into the system.

Some screenshots of how we use it:

![Screen Shot 2020-03-25 at 1.54.11 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/4b8b3598-e2b9-400d-9ca9-4d64b1a3a238)

![Screen Shot 2020-03-25 at 1.54.22 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/971970d5-b121-4ed5-a5ad-5eb59b0e826d)

And users can view all the updates on a different domain (https://changes.covidence.org/)

Would be great to have this as an option for each instance to "turn on" and use to notify their users about all the things.

## Next steps

- [ ] Define how we could implement it on a per instance basis
- [ ] Agree to do it
- [ ] Implement it

**Comment by RachL** [comment]
@daniellemoorhead is headaway open source? I think this needs a bit of inception / discussion before we create the good GH issue. We can discuss here, but FYI I had this wishlist open as well: https://community.openfoodnetwork.org/t/add-notifications-for-the-admin/1608

**Comment by sauloperez** [comment]
I didn't know that little notifications dropdown was a separate service! I came across that one in Bugsnag earlier this bug and this same idea immediately crossed my mind. Users will definitely miss big updates such as mobile or Stripe. 

![Screenshot from 2020-03-25 09-24-21](https://user-images.githubusercontent.com/762088/77516925-846d2680-6e7b-11ea-9ffb-1d484ad543f8.png)

This definitely needs product discussing but while I don't think it's a papercut, it is indeed a prerequisite for mobile and possibly Stripe IMO.

@RachL I missed that wishlist item! I do think they are separate things even tough solutions seem related, due to the fact that our app is crying for asynchronous UI.

**Comment by luisramos0** [comment]
this is nice and it is not difficult but it's not a papercut.
a papercut is half day for a dev, max one day, right?

**Comment by sauloperez** [comment]
it might even fit into a papercut's time-frame but they do not tend to be new features, that's what I thought.

**Comment by RachL** [comment]
> it is indeed a prerequisite for mobile and possibly Stripe (and other big changes) IMO.

I think I disagree for it to be a prerequisite for those two ;) 

And I'm sorry to insist but we need to have a closer look if we use a 3-party: what are their privacy policy? do they use cookies for their service? How much will it cost us etc...

**Comment by sauloperez** [comment]
Sure, we must have this debate but in a community thread. I hope you can open a whislist item for it @daniellemoorhead

**Comment by lin-d-hop** [comment]
Rejected papercut as needs more product discussions

**Comment by kirstenalarsen** [comment]
suggest working this up with more detail in connected wishlist items e.g. https://community.openfoodnetwork.org/t/add-notifications-for-the-admin/1608 with a view to getting considered in product / inception process
