### ISSUE TITLE
Auto redirect from Home to Shop when Order Cycle is selected

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5072]
## What is the problem we are solving 
The new separation of Home and Shop pages creates an extra step for users - making one more click necessary to find the shop

When they have taken the action to select from multiple order cycles, and so have chosen an Order Cycle they should be taken to the Shop page so that they can start shopping

I land on home page

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/980d5348-963e-4b4c-a1ca-0b2cece111c8)

I select my order cycle

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a84fc0a2-159d-42cd-8c17-e5a1e47580c4)

and now I just want to put things in my cart, not think and have to find the Shop tab

## Success factors = expected outcome 
When user selects an order cycle from multiple available, they are automatically taken to the shop

**Comment by RachL** [comment]
This is an interesting case. If one day we move to a custom home message per OC, this wouldn't be the ideal workflow... It makes me wonder if the home message shouldn't be somewhere else actually 🤔

**Comment by luisramos0** [comment]
I think we could easily re-add the message on the shop page, maybe a different field like "shop message" vs "home message" than users could choose their preferred style. So all the users who think this separation between home and shop is not good (I am sure I am not alone on this one), they could disable the "home message" and use the "shop message".
This could be achieved on the enterprise settings page: add new message "shop message".

To have an OC specific message we would need to add that field to the OC edit page. Now that we have it broken in 3 steps, it would fit well in the first step "details": this is all papercut imo :+1:

**Comment by daniellemoorhead** [comment]
I don't disagree with @luisramos0 in terms of changing the interaction, and glad it's all papercuts, but would prefer to have a designer look at this as an end to end journey so that we make changes within the understanding of what the user is doing and what their likely flow is between tabs and the such. 

For now, I'm not convinced that we should do this....And will review the experience with @yukoosawa once this first round of mobile ux improvements is done and then we can put forward a recommendation / decide to do this, then.

**Comment by luisramos0** [comment]
yeah, it's not an obvious decision.
In my mind this is a major UX problem right now. I wonder if this is not important enough that we should have a call to collectively come up with a solution.

**Comment by daniellemoorhead** [comment]
Tis difficult to have a call when @yukoosawa is only available outside of NY biz hours and on weekends. I don't see it as a _major_ ux problem right now, but one that can be considered by @yukoosawa without needing a meeting IMO.

**Comment by daniellemoorhead** [comment]
@mbudm reckon this is something you could sort out for us? It's the thing we briefly saw today :)
