### ISSUE TITLE
[Mobile UX] Rendering on multiple order cycles selection

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5077]
## Description

When multiple order cycles are open to choose from the options in the drop down do not render well.
The non-selected options are white and impossible to read.

## Expected Behavior

I'd like to be able to see the options without hovering over them

## Actual Behaviour

I can't

## Steps to Reproduce

1. Go to an enterprise with multiple OCs
2. Select one
3. The go to change to a different one
4. The options in the drop down are hidden against the white background

## Animated Gif/Screenshot

![sod](https://user-images.githubusercontent.com/8669848/77568733-fddb3800-6ec0-11ea-8f03-ebf74a4406c6.gif)

## Workaround

It's usable
## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: 2.8
* Browser name and version: Chrome 79
* Operating System and version (desktop or mobile): Desktop

**Comment by daniellemoorhead** [comment]
@luisramos0 if you're sorting out the remaining OC stories this bug will need to be fixed. It's only on Windows, not mac, and it's only when you've already selected an OC as you see them when you haven't yet selected. @Matt-Yorkley might have an idea on why this is.

<img width="404" alt="Screen Shot 2020-05-01 at 11 24 18 pm" src="https://user-images.githubusercontent.com/10949052/80808556-2a424c80-8c03-11ea-8ce7-90a2351f9502.png">

**Comment by daniellemoorhead** [comment]
I didn't know this had been added @lin-d-hop - if you find any other lovely bugs can you let me know you're adding them pretty please 🙏

**Comment by luisramos0** [comment]
I cant replicate this on my end (Linux), that means it's not an obvious fix and it's an S4, are you sure you want to include this in the scope? scope creep?

**Comment by luisramos0** [comment]
Please ignore previous comment, I can replicate on browserstask Windows 10 Chrome 79 :+1:
Should be a simple CSS issue to fix.

**Comment by luisramos0** [comment]
this is how it looks now in windows 10 chrome 79 onbrowserstack:
![image](https://user-images.githubusercontent.com/1640378/80822100-e6831f00-8bd1-11ea-8687-94f397f74ef3.png)

**Comment by lin-d-hop** [comment]
BTW happens for me on Chrome linux (that's where I recorded the gif)

Happy this has been fixed  :-D

**Comment by luisramos0** [comment]
ah, really, do you mind testing the PR?

**Comment by daniellemoorhead** [comment]
I'll test it. I can see it happen via browserstack.

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Switching between multiple open OCs on the shopfront](https://trello.com/c/nBZ7J02p/1023-switching-between-multiple-open-ocs-on-the-shopfront)
