### ISSUE TITLE
Deploy OFN free from external data collection such as google.

### ISSUE THREAD

**Issue by albjeremias** [openfoodfoundation/openfoodnetwork#5078]
## What is the problem we are solving 

The problem is that after I deployed OFN with docker-compose, i went to look into the network requests and I was really disappointed to find out that there are requests to google and to stripe, both of them companies which survive from data mining/collection from users.

I also posted on the OFN forum hope you don't feel as spam, but in there i'm requesting instructions on how-to disable it, and here on please to don't set to default to track OFN users.
https://community.openfoodnetwork.org/t/i-need-help-on-configuring-ofn-without-external-data-collection/1889

## Success factors = expected outcome 

I expected that OFN by default does do any network request to external servers at least as default.
I known this is not a simple issue, but i believe its very important.

## Useful information for inception

docker-compose using v2.8.0

**Comment by Matt-Yorkley** [comment]
Is this something you'd like to work on, @albjeremias ?

It would be great to move away from Google maps services, we currently have various bits of functionality that depend on them for Geocoding, searching for local food enterprises by location, and the map display page. 

In terms of using Stripe, we take online payments in lots of countries internationally and the alternatives there are pretty limited. We won't be moving away from Stripe any time soon.

**Comment by albjeremias** [comment]
I could work on it.. im not savvy with ruby.. but with support i think i can tackle little bits of it! :) as of stripe, i guess its a matter of not being activated by default?

**Comment by cillian** [comment]
:wave:... I got Open Street Map working [here](https://github.com/cillian/openfoodnetwork/commit/87427e49c18d60fb7b2dfbd69d1655c6ecc98aa8). The search works a bit differently than usual but if that's not a problem I could open a pull request?

![ofn-open-street-map](https://user-images.githubusercontent.com/101088/81427419-b3e9a100-9152-11ea-98e6-c4274ccbbc42.gif)

![open-street-map-config](https://user-images.githubusercontent.com/101088/81427705-12af1a80-9153-11ea-95bc-80c1535572e6.png)

Although I haven't got tests working locally yet so I haven't checked if they are all passing.

**Comment by Matt-Yorkley** [comment]
Nice! Sure, open a pull request @cillian and we'll take a look.

**Comment by RachL** [comment]
Exciting!!! 😍

**Comment by luisramos0** [comment]
After amazing work from @cillian we have an alternative to gmaps that uses OSM for maps.
This issue represents the work left to beign the required feature-parity to OSM maps in OFN. Once we have the feature parity between gmaps and OSM no one will complain if we switch the default.
imo, we should make osn the default immediately, users would have to activate gmaps if they want.

In terms of Stripe, this is a very simple issue (and good for browser performance in instances that don't use stripe): we just need to not load the stripe script if the general stripe config is disable (which it is by default). This is a simple call to stripe_enabled? where the stripe script is loaded.

**Comment by luisramos0** [comment]
I have created https://github.com/openfoodfoundation/openfoodnetwork/pull/5918 to address the stripe part of this issue.

**Comment by luisramos0** [comment]
Now that #5918 is done and stripe is not there unless activated, I'd love to make OSM the default option on new installs. It's a very simple PR actually that would just invert the logic currently there to activate OSM and de-activate gmaps.

**Comment by albjeremias** [comment]
owao.. its beautiful open source! :) sorry i was not active on this issue, but its beautiful to see! :) thank you all.. you all look really amazing!

**Comment by RachL** [comment]
As we have https://github.com/openfoodfoundation/openfoodnetwork/issues/5542 to track down work on maps, I'm closing here.

**Comment by luisramos0** [comment]
Hi Rachel, I think they are different asks.
The other issue is about making OSM feature rich to replace google maps. Which is great.
This ask here is just to be able to run OFN without google. I'd say this is done when I install OFN by default and google is not active and I can use OSM to display the maps and get the basic geocoding features. The scope of this issue is smaller imo.
