### ISSUE TITLE
As a guest shopper UK staging goes to grumpy cat

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#508]
@aidandunsdon @pmackay If I go to UK staging and click on Stroudco without logging in, I get the grumpy cat

**Comment by aidandunsdon** [comment]
This seems the same as #470. This occurred when Stroudco was first migrated but was resolved while I was away. Was anything specific done or is it a matter of a server reset? @pmackay @NickWeir63

**Comment by pmackay** [comment]
@aidandunsdon did you download a new copy of the staging database before doing a new data migration? If not, it might be out of date again.

**Comment by aidandunsdon** [comment]
@pmackay yes I took a copy of the staging database before migrating Dean Forest

**Comment by NickWeir63** [comment]
just spoke to @pmackay and @aidandunsdon and paul restarted the server and this resolved the problem - thanks both :)
