### ISSUE TITLE
Broken user signup in OFN USA

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5081]
## Description

As discussed in https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1585184014021700?thread_ts=1585182044.021200&cid=CG7NJ966B emails in OFN US are still broken. Payment to SendGrid was done as of Mon, Mar 23, 1:24 AM Pacific (US) time but still, we see this error in Bugsnag

> Net::SMTPFatalError · 550 Unauthenticated senders not allowed

https://app.bugsnag.com/yaycode/openfoodnetwork-usa/errors/5e7875b08c7b0c0017630f38?filters%5Bevent.since%5D%5B%5D=2020-03-26T02%3A19%3A25.721Z&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Bapp.release_stage%5D%5B%5D%5Bvalue%5D=production&filters%5Bapp.release_stage%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.before%5D%5B%5D=2020-03-26T02%3A22%3A13.755Z&event_id=5e7c11a0005922d4527b0000

## Expected Behavior

The signup form should display a green message saying she got an email.

## Actual Behaviour

When filling up the signup form and clicking on "Sign up now" an error message with the text "Something went wrong while creating your account. Check your email address and try again." shows up.

## Steps to reproduce

Just sign up for a user account and you'll get 
![Screenshot from 2020-03-26 12-02-04](https://user-images.githubusercontent.com/762088/77639825-a4731780-6f59-11ea-94d2-407609d22d14.png)

## Workaround
None

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: v2.8.0

## Possible Fix

According to SendGrid (
https://d2w67tjf43xwdp.cloudfront.net/Classroom/Send/How_Emails_Are_Sent/unauthenticated_sender.html), 

> To fix this issue, you’ll want to make sure that you’ve configured your setup to connect to smtp.sendgrid.net using authentication, and that the credentials you’re using are the same credentials you use to login to the SendGrid.

**Comment by Matt-Yorkley** [comment]
I think they had payment issues the other day, but these were resolved... maybe something changed in the account during that time?

**Comment by sauloperez** [comment]
That's what I'm guessing. Did they create a new account and thus credentials are outdated?

**Comment by lin-d-hop** [comment]
100% sendgird payments :woman_facepalming: Third instance this week.

**Comment by luisramos0** [comment]
![image](https://user-images.githubusercontent.com/1640378/77663670-38061180-6f75-11ea-96eb-6e77da8b90fa.png)

**Comment by sauloperez** [comment]
Sorry, not closed yet. I need the secrets in `master`.

**Comment by sauloperez** [comment]
Ok, fixed. I was provisioning the server with no luck because the configuration settings set from the UI were taking precedence :see_no_evil: 

I had to change `SMTP AUTHENTICATION TYPE` to `Login` and update `SMTP USERNAME ` and `SMTP PASSWORD` accordingly.

**Comment by luisramos0** [comment]
I tried to register, I didnt get an email. reopening.

**Comment by sigmundpetersen** [comment]
Worked for me right now

**Comment by lauriewayne** [comment]
Looking at Sendgrip, the "please confirm" are showing up but not the "welcome to" or order confirmation emails. Shipment confirmations are also showing up in sendgrid

**Comment by lauriewayne** [comment]
https://openfoodnetwork.net/locavore-farms/shop#/shop is a good place to do a test order if you want (I recommend the fresh basil)

**Comment by lauriewayne** [comment]
ooh it looks promising @sauloperez?

**Comment by sauloperez** [comment]
Ok, restarting Delayed Job did the trick. Thanks for the heads up @sigmundpetersen . I forgot to restart it yesterday and that's why only the email that is not triggered from a background job went through.

**Comment by lauriewayne** [comment]
Thank you guys! As I recall, isn't there a way for me to check on Delayed Job? (not that I will ever need to, just curious)

**Comment by lauriewayne** [comment]
Yes @sauloperez I hope you enjoy your basil! :-)

**Comment by luisramos0** [comment]
ok, works for me now :+1:
closing, right?

**Comment by sauloperez** [comment]
You have a web UI that displays stats for Delayed Job at https://openfoodnetwork.net/admin/delayed_job/overview but still, you might need a dev to make sense of it. At least you can see the errors there.

**Comment by lauriewayne** [comment]
Thank you Pau!!!
