### ISSUE TITLE
Remove blue sentence in payment method setting

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5092]
## Description
Since the start of the work on SCA we have now a sentence that is displayed below the provider dropdown:
![image](https://user-images.githubusercontent.com/6525576/77781910-a8389400-7056-11ea-8f39-379650f8cb64.png)

We should remove it : it's a bit ugly and does not help at all.

## Steps to Reproduce
1. Go to `/admin/payment_methods/new`
2. Switch from cash to paypal or stripe
3. Boom

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.8
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Desktop

**Comment by jeduardo824** [comment]
I was trying to fix #5102, and I bumped on this (I know the issues are not correlated. I was just poking around, hahaha). Since it was easy to fix, I'm submitting a PR.

**Comment by luisramos0** [comment]
ah, this was a debugging left over from #4672 :see_no_evil:
