### ISSUE TITLE
Missing/wrong translation key in Order Cycle Management report

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5095]
## Description
The report is presenting an "amount" in euros.

In French "amount" can translate with "quantité" if you are looking for an amount of products, but translate to "montant" if you are looking for an amount in euros.

We need a separate translation key for that report column. People are getting confused.

## Steps to Reproduce
1. Go to `/admin/reports/order_cycle_management`
2. Check the column name "Amount"

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/77784030-2185b600-705a-11ea-8465-8cdff626fc7d.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.8
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Desktop

**Comment by rmklaus12** [comment]
Grabbing this one.

**Comment by rmklaus12** [comment]
Can I get some suggestions on how to test my local instance to see what my changes are doing?

**Comment by rmklaus12** [comment]
In the digging I've done, I feel I may be way off track or missing something :-) 
The report page, when translated to French is showing montant for the Euro amount
<img width="299" alt="Screen Shot 2020-05-07 at 2 18 00 pm" src="https://user-images.githubusercontent.com/30268789/81254626-02be0a80-906f-11ea-8ebb-4ef611264d8d.png">
However, I did find this in the fr.yml file, is this what needs to change to Montant? The confusion comes in as the report (for me at least) is showing Montant now...
<img width="602" alt="Screen Shot 2020-05-07 at 2 40 20 pm" src="https://user-images.githubusercontent.com/30268789/81255371-d0ada800-9070-11ea-959b-5301e67fe134.png">

**Comment by mkllnk** [comment]
This is confusing. The report prints a money amount:
https://github.com/openfoodfoundation/openfoodnetwork/blob/066f978c59643bcbd2e973e4b6d7a6caae184484/lib/open_food_network/order_cycle_management_report.rb#L80

And the header column uses a generic translation key:
https://github.com/openfoodfoundation/openfoodnetwork/blob/066f978c59643bcbd2e973e4b6d7a6caae184484/lib/open_food_network/order_cycle_management_report.rb#L24


Which is translated as quantity amount:
https://github.com/openfoodfoundation/openfoodnetwork/blob/066f978c59643bcbd2e973e4b6d7a6caae184484/config/locales/fr.yml#L2177

And that is what I see in staging:
![Screenshot from 2020-05-07 15-30-44](https://user-images.githubusercontent.com/3524483/81257898-c511af80-9077-11ea-98d7-ea8c6a00f52d.png)

And I see the same locally. So, I have no idea what's different in your setup, @rmklaus12.

In terms of solving this issue. The translation key is used in several reports:

```sh
# git grep -w report_header_amount -- lib
lib/open_food_network/order_cycle_management_report.rb:          I18n.t(:report_header_amount),
lib/open_food_network/order_cycle_management_report.rb:          I18n.t(:report_header_amount),
lib/open_food_network/orders_and_fulfillments_report/customer_totals_report.rb:         I18n.t(:report_header_amount),
lib/open_food_network/orders_and_fulfillments_report/default_report.rb:          I18n.t(:report_header_amount),
lib/open_food_network/orders_and_fulfillments_report/distributor_totals_by_supplier_report.rb:         I18n.t(:report_header_amount), I18n.t(:report_header_curr_cost_per_unit),
lib/open_food_network/orders_and_fulfillments_report/supplier_totals_by_distributor_report.rb:         I18n.t(:report_header_amount), I18n.t(:report_header_curr_cost_per_unit),
lib/open_food_network/orders_and_fulfillments_report/supplier_totals_report.rb:         I18n.t(:report_header_variant), I18n.t(:report_header_amount),
lib/open_food_network/products_and_inventory_report.rb:        I18n.t(:report_header_amount),
```

So we need to check all the uses before we change anything. If they are all money amounts, @RachL can just change it in Transifex. If some of them are money and some of them are quantity amounts, we have to introduce another translation key.

I was thinking about `report_header_quantity` but that one is already in use and translated as "Nb commandé". @RachL, can you clarify that meaning?

@rmklaus12 We don't change any language files other than `em.yml` in pull requests. They are all changed via Transifex. But you probably found the documentation on that.

**Comment by rmklaus12** [comment]
Thank you for this @mkllnk. I was not sure the best way to test to see what shows in French so I'm simply using Google Translate. Which gives me the following, which shows several differences between our table headings. What is the best way to go about this and is the fact that we get different results, ultimately an issue to look at?

<img width="1225" alt="Screen Shot 2020-05-07 at 3 50 40 pm" src="https://user-images.githubusercontent.com/30268789/81259183-c2648980-907a-11ea-851f-5942acb9439c.png">

**Comment by rmklaus12** [comment]
> I was thinking about report_header_quantity but that one is already in use and translated as "Nb commandé". @RachL, can you clarify that meaning?

I think this is a typo and should be "No commandé"

**Comment by RachL** [comment]
> So we need to check all the uses before we change anything. If they are all money amounts, @RachL can just change it in Transifex. If some of them are money and some of them are quantity amounts, we have to introduce another translation key.

Indeed, there is a mix. I wondered if we didn't change the translation in transifex because we saw that in customers / suppliers totals this was a quantity and not money ("montant"). But then it affected reports showing money as well (this issue). So yes I think we need two keys.
This could also explain that you have a different translation, as I think I'm editing in Transifex a file that is just for the French instance, correct @mkllnk ?

I wonder if the key isn't used as well when creating a product? Because we changed "amount" into "quantity" there as well.

> I was thinking about report_header_quantity but that one is already in use and translated as "Nb commandé". @RachL, can you clarify that meaning?

"Nb" is a short way of saying "nombre" which is kind of a synonym for quantity.

**Comment by rmklaus12** [comment]
Checked all files and there are no instances of `report_header_quantity`

**Comment by rmklaus12** [comment]
@RachL - can you please verify these keys are correct? We have two reports where `report_header_quantity` exists and it appears they are correct as they relate to an amount or number of a product. 

 - Order_and_distributor_report
		 - Quantity (number/amount of product) - OK
			 - `report_header_quantity`
<img width="600" alt="orders_and_distributors" src="https://user-images.githubusercontent.com/30268789/81381727-84399980-9150-11ea-8077-a0e7dbca0e7b.png">

 - Packing_report
	 - Quantity (amount of product)
		 - `report_header_quantity` - OK
<img width="600" alt="packing" src="https://user-images.githubusercontent.com/30268789/81381761-91568880-9150-11ea-9927-dfafdef36926.png">

In looking closer, now that I understand it all much, I am seeing inconsistencies in wording and formatting. I would imagine overall, this could cause translating issues? If anything it could be improved, for consistency sake. I myself like consistency in apps :-) @mkllnk asked me to look at all the reports and see what data is displayed, what the current label is, and what they should be. I have screenshots, but using them could make this comment into a book. I have only listed those fields that relate to amount or quantity

Reports using `report_header_amount`:

 - order_cycle_management
	 - Amount table heading
		 - Correct -> a currency field using `report_header_amount`
 
<img width="600" alt="order_cycle_management" src="https://user-images.githubusercontent.com/30268789/81381677-6ec46f80-9150-11ea-90e0-33f91ad0a102.png">

- customer_totals
	 - Amount table heading
		 - Incorrect -> a quantity field using `report_header_amount`
		 - Heading should be "Quantity" and code `report_header_quantity`
		 - All headings in this table that refer to currency are using the label with the $ currency symbol. The currency field is labeled 'Item ($)'. This should be changed to Amount
<img width="600" alt="customer_totals" src="https://user-images.githubusercontent.com/30268789/81381825-af23ed80-9150-11ea-8b73-b0a073990014.png">
 
- default_report
	 - Amount table heading
		 - Incorrect -> a quantity field using `report_header_amount`
		 - Heading should be "Quantity" and code `report_header_quantity`
<img width="600" alt="default_report" src="https://user-images.githubusercontent.com/30268789/81381849-bba84600-9150-11ea-9d07-e749166de9a1.png">

 - distributors_totals_by_supplier
	 - 	Amount table heading
		 - Incorrect -> a quantity field using `report_header_amount`
		 - Heading should be "Quantity" and code `report_header_quantity`
<img width="600" alt="distributors_totals_by_supplier" src="https://user-images.githubusercontent.com/30268789/81381888-ce227f80-9150-11ea-9315-c4a727ed2266.png">

- supplier_totals_by_distributor
	- 	Amount table heading
		 - Incorrect -> a quantity field using `report_header_amount`
		 - Heading should be "Quantity" and code `report_header_quantity`
<img width="600" alt="supplier_totals_by_distributor" src="https://user-images.githubusercontent.com/30268789/81381923-e0042280-9150-11ea-97ac-814049a98789.png">

 - supplier_totals
	 - 	Amount table heading
		 - Incorrect -> a quantity field using `report_header_amount`
		 - Heading should be "Quantity" and code `report_header_quantity`
<img width="600" alt="supplier_totals" src="https://user-images.githubusercontent.com/30268789/81381953-ebefe480-9150-11ea-8d32-604bd4b15fde.png">
 
- products_and_inventory
	 - Price table heading
		 - using `report_header_price` that displays the cost (or amount)
		 - label should be 'Amount' for consistency.
	 - Amount table heading
		 - using `report_header_amount`; however, on my local copy, there is no data for the amount field. 
<img width="600" alt="products_and_inventory" src="https://user-images.githubusercontent.com/30268789/81382003-00cc7800-9151-11ea-89d1-c3b44411bb43.png">
I did notice this in the code, could be why the amount field is blank??
<img width="572" alt="Screen Shot 2020-05-08 at 5 20 36 pm" src="https://user-images.githubusercontent.com/30268789/81382079-2194cd80-9151-11ea-81ad-3ae54e59a076.png">

Hope this isn't overkill! Really helped me get my head around these reports :-)

**Comment by rmklaus12** [comment]
Checking back in on this one @RachL. Want to make sure we're all on the same page before I make any changes. Thanks!

**Comment by RachL** [comment]
I'm so sorry @rmklaus12 I must have missed your previous message! Yes this is looking all good and clear, thanks! :+1:

**Comment by rmklaus12** [comment]
No worries! I will make the changes and Puuusssshhh :-)
