### ISSUE TITLE
Wrong behavior for the button "clear filters" in admin/products

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5096]
## Description
A bit of an edge case as it happens only on the specific following scenario:

## Steps to Reproduce
1. Go to `admin/products`
2. Type in the search the word "pptes"
3. The search will tell you Sorry, no results match ' pptes ' - which is correct
4. Then hit the red button "clear filters"
5. This will then show the message "No products yet. Why don't you add some?" But it should come back to `admin/products` which is the result without any filters.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/77784940-acb37b80-705b-11ea-8be8-d349c138a826.png)

## Workaround
Clic on "Filter results". But the first message is troubling

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.8
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment]
@lin-d-hop @sauloperez bug or papercut?

**Comment by sauloperez** [comment]
The boundary is not that clear but this feels to me like a bug. It might even take more time than a papercut.

**Comment by RachL** [comment]
Hello @chrishil1 !

>  should the quick search field clear out as well?

Yes it should :)
