### ISSUE TITLE
[Performance] Bulk Order Management

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5098]
## Description

For pretty much all UK users the BOM is currently unusable.

This is now an urgent issue for our users as suddenly they are receiving hundreds of orders for stock items that can't be delivered as they scrabble to keep systems up to date in the chaos.

Every time I run this page I get a different behaviour. It seems to depend on how quickly I get the filters set as to whether they are used. It also seems to depend on how much free memory I have (I have a SSD, users generally don't). And I wouldn't be surprised if server load impact this too.

I want to know if there are quick performance wins on the BOM. 

## Expected Behavior

BOM is useable for rural users with older laptops.

## Actual Behaviour

It is usable to me on a Saturday morning after a restart with no other browser tabs open.

## Steps to Reproduce

1. Go to BOM
2. Add filters. Try doing this in a hurry... and taking some thinking time
3. Try doing this on a browser that is using memory compared to a fresh browser
4. Hard to trust this page for doing hundreds of updates.

## Animated Gif/Screenshot

I've run the BOM a bunch of times in the past days....

![bom](https://user-images.githubusercontent.com/8669848/77819638-43bc1a00-70d4-11ea-88f4-cd9508a74ab3.gif)

![bom2](https://user-images.githubusercontent.com/8669848/77819640-4880ce00-70d4-11ea-8e5d-75706fd603ee.gif)

![bom3](https://user-images.githubusercontent.com/8669848/77819643-4d458200-70d4-11ea-8ea9-062ffdf5e734.gif)

![bom4](https://user-images.githubusercontent.com/8669848/77819646-50407280-70d4-11ea-81c8-7a298077048a.gif)

## Workaround

Keep trying until you make something happen and hopefully get to save your changes successfully.

## Severity

bug-s2: a non-critical feature is broken, no workaround

Due to the high load of orders and high volatility of producer stock levels not having this page means hours of order updates over a weekend. UK support team is offering to help one hub that is facing this.

## Your Environment

* Version used: 2.8
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Desktop Ubuntu

## Possible Fix

Pagination?
@Matt-Yorkley and @luisramos0 will both have ideas.

**Comment by luisramos0** [comment]
I dont understand why you say most users.
I only see 3 hubs with OCs with over 100 orders.

         204177 | Tamar Valley Food Hub                       |   318
         204188 | Locavore Grocery                            |   181
         204190 | Locavore Grocery                            |   168
         204143 | Locavore Grocery                            |   145
         204159 | Tamar Valley Food Hub                       |   127
         204055 | Kent Food Hubs - Folkestone                 |   121
         204204 | Kent Food Hubs - Folkestone                 |   103

**Comment by lin-d-hop** [comment]
Why is the cut off 100 orders?

The user that reported this had fewer than 100 orders this week and the page was unusable. 

Is 100 orders based on something quantitaive or assumption?

**Comment by luisramos0** [comment]
I was trying to decode your "pretty much all UK users the BOM is currently unusable." and "they are receiving hundreds of orders".
what user in what enterprise is having this issue? I see you are using an account with access to lots of enterprises. that will make things worse for sure.

Looks like you have not seen a timeout right? that would mean this is a javascript issue. big load on the browser. That means computer specs and browser, etc will have an impact.

**Comment by lin-d-hop** [comment]
The user that reported is Banc Organics - they run an box scheme selling only one producer.

Note from Matt:
 it makes 2 large request for every filter click, and the first one it made returned 2.24MB of compressed json

the second query loaded 11MB of compressed json.

@luisramos0 Thanks for your help trying to find workarounds. I've now managed to help the user sort this out this morning.
If you don't think this should be an s2 then feel free to downgrade. It was agreed S2 in slack yesterday so I made it so.

Thanks for all your effort "to decode" my issue.

**Comment by lin-d-hop** [comment]
Re Browser load - some notes from Matt:

 it makes 2 large request for every filter click, and the first one it made returned 2.24MB of compressed json
the second query loaded 11MB of compressed json.

**Comment by luisramos0** [comment]
ok, cool. I think performance is a feature and tagging bugs caused by an increase in the load on the system can be misleading. So, I dont think this is an S2 because I dont think this is a bug.
I think this is a performance issue that we all agree needs to be addressed now.

**Comment by luisramos0** [comment]
ping @lin-d-hop 
I'd say this one should be re-opened and left at Test Ready with prod-test so it can be re-verified after the release on Tuesday.
