### ISSUE TITLE
Snail page after authorizing OFN on my Stripe account. Visa/Mastercard still not available afterwards

### ISSUE THREAD

**Issue by blarsy** [openfoodfoundation/openfoodnetwork#5101]
## Description
I want to allow Visa/Mastercard payment. So I tried to connect my Stripe account to OFN.

## Expected Behavior
OFN and my Stripe account are linked, then the Visa/Mastercard payment option is available when customers are ordering on my OFN shop.

## Actual Behaviour
After authorizing via a navigation to connect.stripe.com, the OFN error page appears. The console shows 2 apparently identical HTTP request ending with a 500

## Steps to Reproduce
1. Log in to my account on openfoodnetwork.be named after "Le comptoir fermier du Rosoir"
2. In the payment methods admin page, hit the "Connect  Stripe" button 
![image](https://user-images.githubusercontent.com/3703906/77845196-15f6d400-71ad-11ea-9ad7-be62526535d0.png)
3. On the authorization page at Stripe, hit the "Connect my Stripe account" button
![image](https://user-images.githubusercontent.com/3703906/77845211-40489180-71ad-11ea-989d-9f1659b7a31a.png)
4. The error page appears
![image](https://user-images.githubusercontent.com/3703906/77845216-4fc7da80-71ad-11ea-9c4a-e254fa506d3b.png)
If ever useful for troubleshooting, both http 500 requests we see in the log try to go to https://openfoodnetwork.be/stripe/callbacks?state=eyJhbGciOiJIUzI1NiJ9.eyJlbnRlcnByaXNlX2lkIjoibGUtY29tcHRvaXItZmVybWllci1kdS1yb3NvaXIifQ.0FxnFouLt-yCozWzZ1e4XjH8s6-RotF0i8xMiVL46E4&scope=read_write&code=ac_GzwsHoQPf3wlUVxqrBGRg3nZDzVE3iT2

## Workaround
None found

## Severity
bug-s1

## Your Environment
* Version used: The one live on the 29/03/2020 10:50 local time at openfoodnetwork.be
* Browser name and version: Brave 1.4.96
* Operating System and version (desktop or mobile): mobile Macbook pro with MacOS Catalina 10.15.3

**Comment by lin-d-hop** [comment]
Hi @blarsy 
I just tested this and successfully connected my Stripe account in Belgium. So it is not impacting everyone.

Could you tell me which payment method you used?
1) Stripe
2) Stripe SCA
They are different and Stripe SCA is a new implementation.

Many thanks,
Lynne

**Comment by blarsy** [comment]
Thx for the reply.

I did not notice there were 2 ways connecting to Stripe.
![image](https://user-images.githubusercontent.com/3703906/77847778-eac9b000-71bf-11ea-8c32-039b2462d2a6.png)
![image](https://user-images.githubusercontent.com/3703906/77847802-07fe7e80-71c0-11ea-968a-c5be85ea4215.png)

Looks like it is Stripe (so, not "SCA").

**Comment by lin-d-hop** [comment]
Ok. Keep it as Stripe.
Are you able to record your screen as you try to connect to Stripe?

So far I can't evidence that this is a code issue as I can connect my Stripe account without issue.

It would be good to understand how wide spread this is on the BE instance. Are you in contact with Sophie or Theo?

**Comment by blarsy** [comment]
Here's a screen video record.
https://youtu.be/LVXvVd6bDoQ

I am in contact with Sophie & Théo, but I did not tell them about the present issue yet. I found out this morning, actually.

**Comment by lin-d-hop** [comment]
Thanks @blarsy 
As I cannot replicate this and no other instances are experiencing it around the world I do not think there is a software issue.
I've let Sophie and Theo know you are having trouble.
I'm going to close this issue. Sophie and Theo can reopen it once they confirm the issue.
Best wishes!

**Comment by Matt-Yorkley** [comment]
@lin-d-hop there's a relevant error in Bugnag...

**Comment by blarsy** [comment]
Hi @Matt-Yorkley 

Thx for the info. Does it mean someone is on it ?

Actually, a farmer colleague of mine mentioned this issue to me this morning (so there are at least 2 occurrences), and my former activity as a developer enabled me to provide the present Github issue.
