### ISSUE TITLE
My Account: make shop names links to open Shop

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5102]
## Description
- As a Customer
- on page https://openfoodnetwork.org.au/account#/orders
- I can easily navigate to My Shops (the ones I have ordered through

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/8d37b871-1d73-428a-afca-5a941e7265d6)

This way the My Account / Orders page can become a useful way to navigate to my 'favourite' shops, which otherwise I need to know the links for, or go through the Search. This is particularly useful for Hubs / Shops that are not visible as only accessible to members etc - it is too easy for them to navigate away and have no way of getting back

It would be good to do the same thing on the Transactions page, which is formatted a bit more nicely already
https://openfoodnetwork.org.au/account#/transactions

## Acceptance Criteria & Tests
From the Customer accounts pages Orders and Transactions, Customers can click on name of Shop/Hub and be taken to that Shop

**Comment by jeduardo824** [comment]
I'm working on this one.

**Comment by jeduardo824** [comment]
Hey, @kirstenalarsen I did not read the part about the Transactions page, sorry. Do you still want this on Transactions too? I can do this at the weekend. Thanks
