### ISSUE TITLE
Make frontoffice app work even if stripe and/or maps URLs are down or break with JS errors

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5109]
## Description
Originated in #5080

We need to make our app independent of stripe and maps. If there are problems with these URLs and/or scripts, the webapp needs to keep working.

## Acceptance Criteria & Tests
Stripe and maps are down, the webapp keeps working.
Stripe js code blows up with some JS error, the webapp keeps working.

**Comment by kirstenalarsen** [comment]
I'm making this S1 until someone can tell me that either
a) there is an easier way to get people alerted or able to login (notification on JS failure?)
b) the bugsnag thing (#5110) will be able to tell us who the user is so that we can contact them - which is unlikely as they can't login!

**Comment by luisramos0** [comment]
we need to see if 5110 will give us the identification of the user...

**Comment by Matt-Yorkley** [comment]
> unlikely as they can't login!

Yeah, that's unlikely.

**Comment by Matt-Yorkley** [comment]
I had a quick play around and found: 
- If I comment out the Stripe JS in the header, the site doesn't break
- If I comment out the **Google Maps JS** in the header, everything breaks.

We've got some initial feedback from the new JS logging as well, which mostly points the finger at our **Google Maps JS**.

Looking at the way methods from these two external scripts are actually called from within in our codebase we find:

- The external Stripe JS is generally used by code from the very well-written and up-to-date stripe gem
- The external **Google Maps JS** is generally used by... a bit of statically-included javascript that hasn't been updated in 6 years: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/vendor/assets/javascripts/angular-google-maps.min.js

And if I update this file to the latest version from that repo (plus a new dependency) then the site doesn't break if the initial maps JS fails to load. Looks like it was a flaw that was fixed years ago by the maintainer, we just didn't pick it up. :see_no_evil:

**Comment by luisramos0** [comment]
oh, that's an amazing discovery!
we just need to update the dependency!?

I am happy I created this issue a few minutes ago :heart: https://github.com/openfoodfoundation/openfoodnetwork/issues/5120

**Comment by Matt-Yorkley** [comment]
#5120 is an awesome idea! I find `npm` can be an absolute pain in the ass, maybe `yarn` is good?

I added a draft here that I think resolves the S1 for now: #5121

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX of the ship button and order states](https://trello.com/c/kauOVQHU/786-ux-of-the-ship-button-and-order-states)
