### ISSUE TITLE
Amazon signature version update breaks ofn

### ISSUE THREAD

**Issue by rafaqz** [openfoodfoundation/openfoodnetwork#511]
Amazon is changing its signature protocol, starting with newest servers but eventually all.

That means Frankfurt S3 wont work with openfoodnetwork as it's currently setup, and needs signature v4, whatever that means in practise.

http://stackoverflow.com/questions/27847888/aws-s3-in-rails-how-to-set-the-s3-signature-version-parameter

**Comment by rafaqz** [comment]
The actual error is:
`AWS::S3::Errors::InvalidRequest (The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.):`

**Comment by kirstenalarsen** [comment]
see #516, workaround by using US S3 for now. will keep this issue open for better resolution when possible
