### ISSUE TITLE
JS error logging to bugsnag

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5110]
## Description
If there are JS errors on the browser we need to be aware of.
For taht we should use bugsnag JS to generate alerts on bugssnag if something goes wrong in the browser.
Originated in #5080

See Maikel's comment here:
https://github.com/openfoodfoundation/openfoodnetwork/issues/5080#issuecomment-605776691

## Acceptance Criteria & Tests
A JS error happens on the browser and we get a bugsand alert informing us about the problem.

**Comment by sigmundpetersen** [comment]
Theres' also #3184 .
Don't know if they are duplicates but there's some relevant discussion we can build on.
