### ISSUE TITLE
Orders page Total could/ should display the 'outstanding total' or have a new column that does 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5114]
## Description

**- As an enterprise user (shop or hub), I sometimes have orders that are partially paid, or have a credit
**- On page Orders, I want to be able to see the actual amount owing or credited on an order, as well as the actual Order total
**- so for this order, it currently shows me Balance Due and the Order total

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/5a9e6118-b098-487f-a7ae-82f879e7b730)
 
and when I go into the payment I see that some of it is paid but $48 of it is not

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/837aeffd-4a02-4ebd-9453-4932b7764593)

It would be really really useful to have this information on the Orders page where I can see it without opening each Order - so that I know there is something else I need to chase up, and if I am reconciling payments against the bank account I actually know how much I am looking for

Suggested solution - show the amount outstanding in brackets after the link in Payment State, so
- Balance Due ($40.00) or
- Credit Owed ($40.00)

## Acceptance Criteria & Tests

1. Create an order and take payment with stripe
2. Add an item to the order (so that item is not paid for)
3. I can see the amount owing on the Orders page

I realise this is not yet a clear enough spec - @tschumilas @lin-d-hop @RachL thoughts on implementing as above?

**Comment by tschumilas** [comment]
Would be excellent to have this!

**Comment by kirstenalarsen** [comment]
ha. losing my mind. I totally created this issue twice!!
