### ISSUE TITLE
Release v2.8.2 Patch release with a single PR

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5115]
Steps: 

- [x] translations were not updated
- [x] https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-3101294ca300ed35b136
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/281
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

This is a minor change in the HTML code to add the bugsnag tag. We can probably just do a quick sanity check in the frontoffice and the backoffice.

**Comment by filipefurtad0** [comment]
Hi @luisramos0 ,

Clicked around, made a few purchases, while looking at front- and backoffice.
Nothing unusual. Good to go.

**Comment by luisramos0** [comment]
thanks Filipe!

**Comment by luisramos0** [comment]
thanks for testing this so quickly Filipe!
