### ISSUE TITLE
Payments using a Deleted Payment Method can't be viewed in Admin

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5118]
## Description
If a customer select a payment method to complete an order, and then that payment method is deleted, it is not possible to view the payment details in admin. There is a snail if the payment method is selected.

## Expected Behaviour
It should be possible to view the payment details for a payment method that was used in a transaction, even if it has since been deleted.

## Actual Behaviour
Snail

## Steps to Reproduce

1. Create Payment Method
2. Place Order using Payment Method
3. Delete Payment Method
4. Go to Orders and view the completed order
5. Select edit icon for the completed order
6. Select Payment in right navigation list
7. Select Payment Method
8. Snail

![Screen Shot 2020-04-01 at 10 50 01 AM](https://user-images.githubusercontent.com/47620442/78085553-05419a80-7407-11ea-9b2e-3a8f101f162c.png)

## Workaround
no workaround

## Severity

Unsure. It is broken, there is no workaround for the impacted enterprises. But it is an uncommon scenario.

**Comment by Matt-Yorkley** [comment]
I imagine it will be really important to fix this for the Stripe  SCA rollout... 

Thanks @emilyjeanrogers :heart:

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX of the ship button and order states](https://trello.com/c/kauOVQHU/786-ux-of-the-ship-button-and-order-states)

**Comment by Matt-Yorkley** [comment]
Dev note: Payment Methods are already soft-deleted so I think it should be fairly straightforward to allow them to be viewed in this case.
