### ISSUE TITLE
Use NPM or add YARN to manage JS packages

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5120]
### What we should change and why (this is tech debt)
It's 2020 and it's a bit ridiculous we have our JS dependencies on our codebase :see_no_evil: 
Using the Gemfile (like we do for angularjs-file-upload-rails for example) isnt the right approach because we depend on out of date or nonexistent rails wrappers for the JS dependencies.
The correct and simple solution is to use a JS package manager and integrate it into the asset pipeline.

There are two options here that I think are valid, use npm.
You can run
`npm install --save textangular`
and that is probably it as this will be available to be used in app/assets/javascripts/admin/all.js

But yarn is better than npm for a few reasons so we could start using yarn for this and get the dependencies through it.

This can then be used to include all the JS dependencies in our repo:
- app/assets/javascripts/shared
- app/assets/stylesheets/shared
- vendor/assets/javascripts/
- vendor/assets/stylesheets/
- Gemfile

### Context
This came up in quite a few PRs where we are upgrading dependencies directly in our repo:
- upgrading text angular in Feb 2018: https://github.com/openfoodfoundation/openfoodnetwork/pull/2060#issuecomment-364200533
- upgrade text angular in Feb 2020 - https://github.com/openfoodfoundation/openfoodnetwork/pull/4816#issuecomment-592457713

### Impact and timeline
This will be a very good clean up of our frontend code.

**Comment by sauloperez** [comment]
Rails made the shift from Sprockets to Webpack to manage assets some time ago. Anything we do should get us closer to that.

I guess you suggest exposing the npm packages where the Rails asset pipeline can pick them up. I'm afraid, however, that having a Rails version still uses Sprockets for the asset pipeline, moving away from it might end up in a dead-end or a very complex scenario where we can't leverage the Rails tooling.

Any way we choose, I'd give a very close look at how [Sharetribe](https://github.com/sharetribe/sharetribe/blob/master/app/assets/javascripts/application.js) dealt with it. They introduced React components before Rails supported it if I'm not mistaken.

**Comment by luisramos0** [comment]
webpack is a bundlder, it replaced asset pipeline.
both package managers npm and yarn play well with it. I dont think this will introduce a problem.
