### ISSUE TITLE
Cache home page counters for a day

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5123]
### What we should change and why (this is tech debt)

We need to cache the home page so that we reduce a bit the pressure on the instance, namely the DB. The counts of producers, shops, shoppers, and orders that we show at the bottom of the home page are the root cause of 2 of the 10 top queries where our servers spend the most time.

In the last week, we got reports of the app being slowed and these queries taking more than 2 seconds (hard to know if as a consequence or cause). We even got one at 3.15min :see_no_evil: 

It was agreed in the last delivery train that we'll cache those counters for a day. And we want to explore HTTP caching. It might be the best bang for the buck.

We must beware of https://github.com/openfoodfoundation/openfoodnetwork/blob/78170bc7098df3415a3e86766e41aaba9da10500/app/controllers/application_controller.rb#L131-L135.

### Context

Now, that information is far below the fold, it's very unlikely users check it, and if they do, the information doesn't need to be real-time accurate. With this steady increase on requests we are experiencing we need to make better use of the system resources before we get :fire: #scalability.

### Impact and timeline

Saving some requests on one of the most visited pages (it's among the top 5 of visited URLs), will already have a noticeable impact.

**Comment by RachL** [comment]
@sauloperez do we have the other top 10 queries listed somewhere?

**Comment by sauloperez** [comment]
Yep, in Datadog https://app.datadoghq.com/apm/service/rails-postgres/postgres.query?end=1585765141949&env=production&paused=false&start=1585160341949. You can see the list down below on that page. But watch out, executing them often doesn't mean we need to fix them.

**Comment by Matt-Yorkley** [comment]
I feel like investigating and resolving the `set_cache_headers` issue and assessing our HTML caching in general are two really big topics that might be outside of the scope for this issue? Also: HTML caching in general changes in Rails 4, so if we start playing with it here I think we will have to change it very soon :see_no_evil: 

Can we just add some simple cache entries for those 4 specific numbers and set them to expire after 24 hours?
