### ISSUE TITLE
OC 'Advanced Settings' Box should appear on all Tabs of the Order Cycle Interface

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5128]
## Description
As an Enterprise User, I want to easily access and modify whether my OC is drawing from all products or Inventory, at any point in my order cycle editing journey

When I create an Order Cycle there is initially no Advanced Settings box at the top

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/994027fe-0639-457b-af74-6ff62a2b68d4)

When I hit save, I am automatically progressed to the Incoming Products tab. The Advanced Settings box is not available on this tab . . however this is where I would like to make the choice between using Inventory or All Products

It would also be useful Outgoing Products tab, then I can easily check what the setting is - particularly useful if I'm wondering where products are or what is going on

So the proposal is that this option box appears in the blue bar on all tabs

This is part of a suite of suggested changes that should help with user confusion. See also #4804

## Acceptance Criteria & Tests

1. Create an Order Cycle
2. Once automatically progressed to Incoming Products, you have the option to modify the Inventory setting for this order cycle
3.  Once on the Outgoing Products, you can also access and change the Inventory setting if you want to

**Comment by tschumilas** [comment]
Nice one!

**Comment by RachL** [comment]
I'm not sure putting the switch in each steps is the way to go.... I wonder if it wouldn't confused people to have it on several steps :/

Why not leave it only in general settings?

**Comment by kirstenalarsen** [comment]
At the monent you don't see it. You create of and auto to incoming, so you never even see advanced settings unless you go back to it. I guess the other option would be to have it there from the outset, but I get that you can't save it until you have actually saved the oc. 

I think it is better to have it accessible in each tab so that it is really easy for people to see the implications of switching it. If not all, definitely at least incoming

**Comment by Erioldoesdesign** [comment]
I'm unsure how I enable the advanced settings on the 'Order cycles' section. Is it something I enable in settings of the enterprise first and then return to see it appear?

**Comment by kirstenalarsen** [comment]
It's very confusing currently - you don't see it until you have created the order cycle from the first tab. But when you hit create it takes you straight to the next tab, where it doesn't appear, so you have to know to go back to the first tab.

I do still think this is confusing, but as we're working to get rid of inventory through network I'm not sure that it's actually sensible to make it easier to use? Making me wonder if I should remove this suggestion . .

**Comment by Erioldoesdesign** [comment]
@kirstenalarsen I think it depends one:

1. How much time a dev would take to do this task
2. How quickly we're re-working/redesigning inventory

If answer is 1. less than a couple of days and 2. Not very soon then it's worth doing

**Comment by dnie12** [comment]
Hello @kirstenalarsen, 
@richardc2117 and I working on this task of adding the 'Advanced Settings' Box to the Incoming Products and Outgoing Products tabs when creating an order cycle. Currently after selecting a different option in the Advanced Settings button, it reloads to the General Settings Tab. We were wondering if you wanted that behavior to remain or if you wanted the page to reload on the current tab.

**Comment by kirstenalarsen** [comment]
HI @dnie12 and @richardc2117 - thanks for picking up this issue! I think it should reload on the current tab please. Thanks :)

**Comment by filipefurtad0** [comment]
Ok, we've got two PRs which were tested and fix this issue.

- #7390 fixes the issue but breaks the build (due to a missing translation); adds no tests.

- #7390 fixes the issue, accounts for internationalization and adds tests, but introduces an un-necessary confirmation modal, when "Save and reload page).

I'd propose to merge #7390 and open an issue to remove the modal, if needed.
