### ISSUE TITLE
Add 'inc. tax' to Customer totals report

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#513]
to totals row only (total tax on order)
![image](https://cloud.githubusercontent.com/assets/2911176/7289948/a499f19a-e9ba-11e4-8b76-d9ddc0222d7c.png)

**Comment by daniellemoorhead** [comment]
@oeoeaio perhaps reports are something else to consider in terms of making changes to tax?

**Comment by lin-d-hop** [comment]
Added to https://community.openfoodnetwork.org/t/outstanding-tax-requirements-jan-2016/487
#gitcull2017
