### ISSUE TITLE
No error message when product import's CSV is malformed

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5132]
## Description

A Bugsnag error notification related to a malformed CSV just came in: https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/5e85ed88fdafed00193f6108?event_id=5e85ed8800599ff16e1e0000&i=sk&m=nw

As this error is not handled by the app, the user won't see any notice and won't have visual clue about the broken format.

## Expected Behavior

The user should know the file is not a valid CSV.

## Actual Behaviour

The import fails without any visual indication to the user

## Steps to Reproduce

Import products from a file that has at least one unquoted field containing the characters \r or \n.

## Workaround

none

## Severity

bug-s4: it's annoying, but you can use it

## Possible Fix

This method

https://github.com/openfoodfoundation/openfoodnetwork/blob/fe8beb5448b8b7d91af2c03c805a130e020f9cd3/app/models/product_import/product_importer.rb#L226-L240

should handle CSV::MalformedCSVError errors as well.

**Comment by RachL** [comment]
@sauloperez can this be a good first issue?

**Comment by sauloperez** [comment]
definitely!

**Comment by rioug** [comment]
I am looking at this.

**Comment by rioug** [comment]
CSV file including a \r [product_list_malformed.zip](https://github.com/openfoodfoundation/openfoodnetwork/files/4743531/product_list_malformed.zip)
Added as a zip because github doesn't allow .csv file/

**Comment by sigmundpetersen** [comment]
Hey @rioug thanks, go ahead! 🙂
