### ISSUE TITLE
Bulk Invoice print garbled and only generating one per page?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5138]
## Description
I don't have any more info from the user yet but a report that the bulk invoice print isn't working 

they sent this image

![IMG_20200303_0001.jpg](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a921aa8b-b86b-43f6-a9ab-4e56bf60e9fe)

I have just run it myself and seems fine. I have asked them to try again and see if it works

## Expected Behavior
Bulk invoice generation should print all invoices in one file with no squiggle and random characters!

## Actual Behaviour
as shown above

## Steps to Reproduce
no info yet
1.
2.
3.
4.

## Severity
TBC

**Comment by lin-d-hop** [comment]
@kirstenalarsen Can you find out what PDF reader they are using to read the PDF?

This gets tested every release. The issue is specific to the user.

**Comment by RachL** [comment]
Closing as we haven't heard anything on this since.
