### ISSUE TITLE
[Bugsnag] No API key configured, couldn't notify

### ISSUE THREAD

**Issue by rafaqz** [openfoodfoundation/openfoodnetwork#514]
That's the error, and no notifications are being sent, but there is a bugsnag key at config/bugsnag.rb:

Bugsnag.configure do |config|
  config.api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  config.notify_release_stages = %w(production staging)
  config.use_ssl = true
end

Is that setup any different to what's being used on au production?

**Comment by elf-pavlik** [comment]
I asked about bugsnag on [deployment slack channel](https://openfoodnetwork.slack.com/messages/deployment-user-group/) and in answer received link to https://openfoodnetwork.slack.com/messages/deployment-user-group/

@rafaqz have you already resolved this issue?

**Comment by kirstenalarsen** [comment]
Raf isn't working on ofn anymore, reckon @mkllnk probably best chance for an answer on this . .

**Comment by mkllnk** [comment]
The problem was that the file `bugsnag.rb` belongs into the folder `config/initializers` instead of just `config`. Rohan and I found that mistake in the deploy scripts and fixed it there (openfoodfoundation/ofn_deployment@b1ac120223b46d7d25d9956b6344e0b5c0cd6ccc).
