### ISSUE TITLE
Throw more metal at UK & FR Production

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5140]
It's time for some more metal! :metal: :metal:

UK Production in the last month:

![Screenshot from 2020-04-03 11-10-08](https://user-images.githubusercontent.com/9029026/78348475-5cc83d80-75a2-11ea-81ca-c8c43c90328f.png)

CPU looks okay, but in the last fortnight memory is becoming really tight and swap is spiking hard, which will only compound our problems.

We need to announce some downtime (estimated at 25 minutes) and upgrade the DO droplet, following these steps:

- turn off the droplet
- take a **snapshot**
- "resize" the droplet to a bigger package
- turn it back on
- have a quick look and probably: manually restart the services for unicorn and delayed_job as they might not fare well during the shutdown process

https://www.digitalocean.com/docs/droplets/how-to/resize/
https://www.digitalocean.com/docs/images/snapshots/how-to/snapshot-droplets/

**Comment by sauloperez** [comment]
Bad news. OFF's plan in OVH doesn't allow us to upgrade the server :see_no_evil: We have to hold on for OFF, I'm afraid. @RachL is already checking alternative providers but I'm sure we can still check within OVH.

**Comment by sauloperez** [comment]
Steps done for UK

- [ ] Shutdown server manually
- [ ] Take a snapshot
- [ ] Resize droplet
- [ ] Power droplet back on
- [ ] Ensure services are started

**Comment by sauloperez** [comment]
There's a snapshot from 6 months ago. Is it from an old server migration @Matt-Yorkley ? We should delete it because we're paying for it.

**Comment by sauloperez** [comment]
We'll need to create another issue for FR and do it soon.
