### ISSUE TITLE
Release v2.9.0 Navratan Korma

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5141]
I'll go for a minor 2.9.0 instead of patch 2.8.3 because there are quite a few significatn fixes in this release :tada:

Steps: 

- [x] Include translations
- [x] Release Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-ce57bc7badb6b7180f67
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1299
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by RachL** [comment]
This is looking good! Lots of good stuff 😍 

ready to go! https://docs.google.com/document/d/1DMID-xCeT6EDbG_VpgG1nG6JfZCbAbDiVPUJFoxZRTk/edit#
