### ISSUE TITLE
Reduce performance impact of /shops

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5143]
### What we should change and why (this is tech debt)

We need to reduce the impact the `/shops` page is having on our servers load by reducing its response time with quick and easy optimizations. It's holding its position as the worst app endpoint in the last month.

### Context

With the increased demand and the scarcity of resources in FR and UK servers this page's response times are going nuts, and this causing the DB to be on :fire: as well.

Today, the percentile 95 reaches 15secs sometimes, like this [request](https://app.datadoghq.com/apm/trace/5148661426660309856?env=production&sort=time&colorBy=service&graphType=flamegraph&shouldShowLegend=true ). And it's getting worse.

![Screenshot from 2020-04-03 13-35-27](https://user-images.githubusercontent.com/762088/78356784-80928000-75b0-11ea-9f49-5bcec053ce93.png)
Count of requests taking more than 10s in the last 4h for UK and FR together.

Even the latency distribution is taking a very weird and far from good shape.

![Screenshot from 2020-04-03 13-42-28](https://user-images.githubusercontent.com/762088/78357045-0282a900-75b1-11ea-8e32-498d8ae601b1.png)

### Impact and timeline

Any improvement in this page will have a big impact on the server load. Doing more with the same resources it's a good way to scale-up the system, isn't it?

**Comment by sauloperez** [comment]
I tried an aggressive caching strategy using Rails [page caching](https://guides.rubyonrails.org/caching_with_rails.html#page-caching) but that won't work due to the dynamic nature of this page. Even if we go with other lower-level strategies dealing ourselves with cache invalidation, I'm afraid the complexity will be pretty big and it'll take time.

My personal conclusion is that we'll need to work pretty soon on refactoring /shops if we want to survive this :chart_with_upwards_trend: As per @matt-yorkley’s insights, there are no quick wins there unless we :fire: the tech-debt.

**Comment by Matt-Yorkley** [comment]
>  the percentile 95 reaches 15secs sometimes

It's worse than that... :grimacing: 

![Screenshot from 2020-04-03 18-50-20](https://user-images.githubusercontent.com/9029026/78385390-0c6dd180-75dc-11ea-96db-e6a8cb6a4189.png)

**Comment by sauloperez** [comment]
OH MY F***** GOD :see_no_evil:

**Comment by Matt-Yorkley** [comment]
We can have another look at the data on this when the new release is deployed.

**Comment by sauloperez** [comment]
This is sweet! :heart: 

![Screenshot from 2020-04-14 12-33-00](https://user-images.githubusercontent.com/762088/79215674-3466fb80-7e4c-11ea-876c-714911064a1e.png)
Data in the last two days

**Comment by daniellemoorhead** [comment]
Yay! Can we consider @sauloperez's stats update the equivalent of a #prod-test and this card can be closed now? Or is there a specific test to do?

**Comment by sauloperez** [comment]
Yep, we can close

> It's holding its position as the worst app endpoint in the last month.

It has fallen down to the 4th position :v: great job @Matt-Yorkley :clap:
