### ISSUE TITLE
Amazon S3 uses only US standard url to retreive images

### ISSUE THREAD

**Issue by rafaqz** [openfoodfoundation/openfoodnetwork#516]
There are a number of clunky fixes for this here:

https://github.com/spree/spree/issues/1840

If anyone has opinions on which to implement, let me know.

**Comment by kirstenalarsen** [comment]
from email from @rafaqz 

Options are:
- don't use s3 and keep images on the server (Rohan thinks that's bad and hard to change later)
- use s3 in US (other side of the atlantic for largest files? not a very good option, but maybe thats what we are doing in au anyway? 
- Fix the problem with one of the hacks in the spree issue i reference.
- Update spree so we don't get these ancient bugs :)

**Comment by kirstenalarsen** [comment]
option 2 works :)

**Comment by PascalPencil** [comment]
This works https://github.com/spree/spree/issues/7252#issuecomment-203803403
