### ISSUE TITLE
Enterprise User should be able to add any registered user on the system as a manager of Enterprise

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5164]
## Description

I am logged in as an Enterprise, with ownership permissions. I want to add a manager to my enterprise. They are already a user on the OFN system but not any of my enterprises

I try to do this, but it only lets me choose from users within my enterprises. I am pretty sure this is wrong?

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/1bf87f6d-cee2-4494-b0a0-4cb280f8b05c)

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/59d7ec62-86c1-4124-a53a-de2d347708d3)

I shouldn't need to 'invite an unregistered user' to add someone who IS registered on OFN. However if I try to add an unregistered user I get this message
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/6834d790-fe63-41a9-bb03-d0aec9a994e7)
 
In SUPERADMIN I can add the other user I want 
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/22fd3e9b-94be-4c77-980e-0ed05a61e908)

## Expected Behaviour

An owner of an Enterprise can add any registered user on the system as a manager of their enterprise

## Actual Behaviour
They can only add users that are owners or managers of their existing enterprises

## Steps to Reproduce

1. Be an owner of an enterprise
2. Go to Settings / Users
3. Try to add a user as manager that has no pre-existing relationship with this Enterprise 
4. That user will show as 'not found'

## Workaround
I think the only workaround is to ask superadmin to add the user to the first enterprise you need, and then you should have it available for the next ones

## Severity
S3 - I'm going S3 because we can get around it with super-admin. But it does clarify for me some of the issues we've been having with farmers market set-ups

The [user guide](https://guide.openfoodnetwork.org/basic-features/enterprise-profile/enterprise-settings#users) is currently misleading as it says you can add anyone who is on the system as a manager

## Your Environment
Mac. Safari

**Comment by RachL** [comment]
@kirstenalarsen this is working, I'm doing it all the time. But you need to type the entire email address, not just the beginning. And I think it is the correct behavior. Otherwise we would show the user all emails from the system. And that would be a privacy problem.

**Comment by kirstenalarsen** [comment]
i thought i did! but I see now that you are right - hurrah!! Thanks @RachL :)
