### ISSUE TITLE
Filtering by Shipping Method in Order Cycle Management Reports is broken

### ISSUE THREAD

**Issue by Ekow244** [openfoodfoundation/openfoodnetwork#5168]
## Description
Filtering by Shipping method is broken in the Order Cycle Management reports.
As Hubs are increasingly offering home delivery and working to improve their distribution systems this is presenting big challenges.... many hubs are sorting manually and this is taking a significant amount of time.

## Expected Behavior
In the Order Cycle Management reports page, I selected 'Collect in person' under Shipping methods and filtered my search results. 
I expected the results to only display "Collect in person" under Shipping method

## Actual Behaviour
The results displayed the various types of shipping methods I have in my account. It failed to filter the results by the shipping method I had specified.

![Screenshot from 2020-04-05 19-37-53](https://user-images.githubusercontent.com/41970974/78508285-0fe89080-7775-11ea-9f5b-b7d818e47dd0.png)

## Severity
bug s3

## Steps to Reproduce
Link: https://openfoodnetwork.org.uk/admin/reports/order_cycle_management
Account: daniel.ekow.baidoo@gmail.com

1. Navigate to the Order Cycle Management reports page in the admin panel
2. Select a shipping method you want to filter by
3. Click on search 
4. Verify if the search results display on the filter you selected in Shipping method

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Order Cycle Management - Reports Filter on Shipping Method](https://trello.com/c/gbK0UYIQ/815-order-cycle-management-reports-filter-on-shipping-method)

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Order Cycle Management - Reports Filter on Shipping Method](https://trello.com/c/gbK0UYIQ/815-order-cycle-management-reports-filter-on-shipping-method)

**Comment by RachL** [comment]
@lin-d-hop i've just tested this and it works for me. I'm closing but please reopen if I'm wrong.

**Comment by RachL** [comment]
Nevermind! My test was twisted. Actually it does filter by shipping method, but not by shipping method name: but by shipping method type.

I was testing on a hub that had only two shipping method, one per type 🤦
