### ISSUE TITLE
Support locales longer than 5 characters

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#5170]
## What is the problem we are solving

Locales such as `fil_PH` cannot be supported because `locale` in the `spree_users` table can only store up to 5 characters. There is an error when I switch to `fil_PH` as a logged in user.

Actually, if I check my `/usr/share/i18n/SUPPORTED`, 70+ of the 495 locales listed have 6 characters.

This is needed by Philippines. :grimacing: This is a blocker for our deployment, so I'll be making this small change to increase the max characters from 5 to 6.

## Success factors = expected outcome 

As logged in user, I can switch to `fil_PH`.

**Comment by mkllnk** [comment]
On my system there are exactly 70 locales with six characters and no locales with 7 characters:
```
cat /usr/share/i18n/SUPPORTED | egrep '^[A-Za-z_]{6}' | wc -l
70

cat /usr/share/i18n/SUPPORTED | egrep '^[A-Za-z_]{7}' | wc -l
0
```

:+1:

**Comment by lin-d-hop** [comment]
@kristinalim 
I'm not clear on how to test this one. Can you give some clues?
