### ISSUE TITLE
Shop can easily see Customer account totals on Customers page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5171]
## Description

- As a Shop or Hub
- On page: admin/customers
- I want to be able to see the total amount owed from or owing to my shop for each Customer
- This column could be present by default, or hidden by default in the columns drop down (shown below)
- It should be clear whether the amount is owing to the Shop, or the Customer has a credit (red for owing to the shop?)
 
This information is currently visible to the Customer in their [account transactions page](https://openfoodnetwork.org.au/account#/transactions) - I think the page just adds up the total credits and debits at each shop and displays it on this page

If the Shop manager could also see this amount easily it saves them pulling the Payments report anytime they are trying to work out the state of a customers account balance

(slight enhancement to ease our workaround account credits process :)
  
## Acceptance Criteria & Tests

1. View Customers list, see customer with account credit = $0
2. Create an order for that Customer with multiple items in a shop
3. Edit the order to remove an item, so now the Customer is owed money (they have an account credit)
4. Refresh Customers page - should now show a customer account credit amount 
5. Go to the Customer's order and add payment, -$XX to indicate processign a refund
6. Refresh Customer page - should now show new amount reflecting the refund

**Comment by kirstenalarsen** [comment]
nb. concern? question check performance implications?

**Comment by luisramos0** [comment]
size S I'd say.
related to #5173 and https://github.com/openfoodfoundation/openfoodnetwork/pull/5031/files

**Comment by dacook** [comment]
I'll take a look into this!

**Comment by dacook** [comment]
In progress, I think I'm going to need to learn a bit more to figure this one out.

**Comment by luisramos0** [comment]
hello David! Not an easy one if you starting with OFN!

I think you should create a service under app/services called CustomerBalance that takes a customer and does something like this:
https://github.com/openfoodfoundation/openfoodnetwork/pull/5031/files#diff-d92a88617a8371ec293fbd1c06389eb8R14

```
class CustomerBalance
    def initialize(customer)
       @customer = customer
    end

    def call
        payment_total - completed_order_total
    end

     private

    def payment_total
      payments.sum(&:amount)
    end

    # Lists all complete user payments including payments in incomplete or canceled orders
    def payments
      Spree::Payment.where(order_id: customer_orders, state: "completed")
    end

    def customer_orders
         Spree::Order.where(distributor_id: @customer.enterprise, email: @customer.email)
    end

    def completed_order_total
      completed_not_cancelled_orders.sum(&:total)
    end

    def completed_not_cancelled_orders
      customer_orders.complete.not_state(:canceled)
    end
```

NOTE: looking up orders by email (and not customer id or user id) includes orders completed before the user registered in OFN (guest orders).

This service will be useful at some point but for the customers page (this issue) you may need to load this data through an ActiveRecord query that loads this data for all customers at once, otherwise this service will generate a couple of queries per customer....

I hope this helps.

**Comment by dacook** [comment]
Thanks @luisramos0 , this is really detailed and helpful! You're right, not a good first issue, I forgot to look for the tag. I don't think I'm going to be able to progress it in the short term, so it might be best to unassign me in case someone else can pick it up.

**Comment by luisramos0** [comment]
Can I get some advise on the UI on how to represent the positive negative balance?
This is what we are doing in the orders list:
![image](https://user-images.githubusercontent.com/1640378/94949622-2039b800-04d9-11eb-84e1-88625937bfc4.png)

I think we should do something similar but should I get it exactly the same using "credit owned" and "balance due" tags like for orders?

**Comment by luisramos0** [comment]
On a related topic, in this issue I am just using the existing UserBalanceCalculator to get the customer balance but there seems to be some problems with it as we can see @lin-d-hop trying to fix it here: https://github.com/openfoodfoundation/openfoodnetwork/pull/5031

Shall I go into that as part of this issue?

**Comment by kirstenalarsen** [comment]
I found this hard when we did the order page and still find it hard! I think include the 'credit' and 'balance' because otherwise it is just confusing. 

I don't know about the calculator - if it is not working properly then probably (yes please) but aware of paper cut scope crewp

**Comment by lin-d-hop** [comment]
Agree re papercut scope creep...

Butttt..... The UserBalanceCalculator does have problems and having you look at this and your confidence that it is correct @luisramos0 would be a huge relief for me. I would love to have the confidence that this can be used widely through the platform.
Perhaps we can timebox it? If the investigations and fix take longer than 2-3 hours then it needs its own issue?

I would agree that our users will appreciate the 'Balance Due' and 'Credit Owed' text. Based on my knowledge of our users this will save a lot of support queries!

**Comment by luisramos0** [comment]
ok, thanks for you feedback :+1:

this is how it looks with the labels:
![image](https://user-images.githubusercontent.com/1640378/95979882-3cf8b880-0e14-11eb-8d45-46d1452994cb.png)

I am going to have a look at the calculation logic now.

**Comment by luisramos0** [comment]
ok, I gave a good look and improved the PR related to the calculation of the balance:
https://github.com/openfoodfoundation/openfoodnetwork/pull/5031#issuecomment-710240422

Anyway, this issue here and PR (add balance to customers pages) are related to it but 100% independent. We can move this issue and PR forward and let the balance calculation PR #5031 follow it's way independently (it needs product feedback that can take a while).

**Comment by Erioldoesdesign** [comment]
Sorry I cam into this late but just want to note, from a design on papercuts pov what is here:
![image](https://user-images.githubusercontent.com/11681324/97873780-04137b80-1d10-11eb-83c8-4a7d2540ac20.png)

is good for a first version within papercuts territory but in general, theres a lot of 'UI mixed messages' between this column and the transactions section described in #5031 e.g.
- Minus symbols being used on green text and regular grey text
- 'Credit owed' and 'balance due' being statements that can have multiple contexts per producer-user.
- Use of colours in transactions (not accessible for colour blindness/impairments
- No use of '+' plus symbols to indicate opposite of minus amounts.
- Orange traffic light circle being used without clear action on how to resolve (users get anxious and worried when they see orange/red and they like to know how to 'keep track' and follow up an action. Too many of these UI patterns can make a user consider other systems which don't 'tell them off' irrational I know but hey, that's humans 🤷 )

These can form some of the design thoughts for non-papercut improvements to these sections I'll add in our notion section until we have defined the inception/design pipeline process for these

**Comment by luisramos0** [comment]
that's awesome feedback @Erioldoesdesign i am looking forward improving those things!

**Comment by luisramos0** [comment]
regarding #5031 maybe useful to clarify that the page in there is for the customer, this one in this PR is for the manager. No user will see the two pages with the same data except for a manager buying in their own shop which is an edge case I think.
