### ISSUE TITLE
Error Connecting to Stripe - different login cookies for https://www.openfoodnetwork... and https://openfoodnetwork...

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5179]
## Description

An enterprise is getting a slug on connecting to Stripe.
Fortunately we have loads of information on this issue....

Here is the Bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5e7bade40a31b10018d4828e?filters[event.since][0]=30d&filters[error.status][0]=open&pivot_tab=event

## Expected Behavior

Stripe should connect successfully or give an error as to why not

## Actual Behaviour

We are seeing the Slug on the Stripe callback. Stripe is failing to connect

## Steps to Reproduce

Seems to be specific to edge cases - of which this user is one.

Additionally - since this was reported I have removed the user from being owner/manager of another account. I have asked the user to try again. I will confirm if this was the problem.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/8669848/78643047-91dad580-78ab-11ea-8f36-10923f404f09.png)
![image](https://user-images.githubusercontent.com/8669848/78643059-956e5c80-78ab-11ea-8c79-e044d989fd98.png)
![image](https://user-images.githubusercontent.com/8669848/78643071-9901e380-78ab-11ea-9b69-27034dd41ff8.png)
![image](https://user-images.githubusercontent.com/8669848/78643080-9bfcd400-78ab-11ea-81c0-6f0af82a9336.png)
![image](https://user-images.githubusercontent.com/8669848/78643091-9ef7c480-78ab-11ea-9916-1b699bfe89f8.png)
![image](https://user-images.githubusercontent.com/8669848/78643099-a28b4b80-78ab-11ea-8a38-a3ba2d034ba3.png)
![image](https://user-images.githubusercontent.com/8669848/78643113-a74fff80-78ab-11ea-997f-408822c95d20.png)
![image](https://user-images.githubusercontent.com/8669848/78643124-aa4af000-78ab-11ea-9dee-bf4674326d00.png)

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 2.9 UK
* Browser name and version: 
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
spree_current_user is nil on Stripe::CallbacksController

it's not permissions, it's something to do with the user session, it looks like they are not logged in on OFN when they come back..
I noticed the url where they land doesnt have the www, can you try to add the www to it and reload?

another approach: if you change the url where they land to just the domain like http://openfoodnetwork.org.uk does that work and is the user logged in in that homepage?

**Comment by lin-d-hop** [comment]
Why would this only impact this user? If that was the issue would we be seeing an issue with no one being able to connect Stripe?

**Comment by luisramos0** [comment]
yes, second option. **Could be** something browser specific.

**Comment by kristinalim** [comment]
> it looks like they are not logged in on OFN when they come back..
> I noticed the url where they land doesnt have the www, can you try to add the www to it and reload?

I think this is the problem. If they are logged in at `www`, they are not logged in automatically in non-`www`, which is correct behaviour.

@lin-d-hop Could you check if the first "Redirect URI" in Stripe does not have "www" in the domain name? If that's the case, then please ask the user to log in at the non-`www` website and connect to Stripe from there.

[From Stripe docs](https://stripe.com/docs/connect/oauth-reference): "If no redirect_uri is set, the first URI in the list is used." And we do not specify a redirect URI when generating the Stripe URL where we redirect the user.

(Ideally, we use only one domain name for each instance. Currently, both `www` and non-`www` work for many instances.)

**Comment by luisramos0** [comment]
:see_no_evil: I tested this, you are right @kristinalim 
test:
- login at openfoodnetwork.org.uk
- go to www.openfoodnetwork.org.uk and see you are not logged in :see_no_evil: 
same problem in OFN FR.

openfoodnetwork.org.uk should be an http(s) redirect to www.openfoodnetwork.org.uk

**Comment by lin-d-hop** [comment]
Ping @luisramos0 and @kristinalim 

The user did not do the www thing.

From user:
_It appears to be sorted.  I tried the same process on Chrome rather than Firefox and it went through OK.  I’m not sure it was the browser or something you have done in the meantime._

Two things changed:
1) they used a different browser
2) That I removed them as owner of another enterprise.

*shrugs*

**Comment by luisramos0** [comment]
it all depends on what url were they on chrome. i dont think this should closed. different sessions on www and nowww will create more problems. we need to fix it. id say this is an s3.

**Comment by luisramos0** [comment]
I am pretty sure we experienced this again in Brasil, user tries to connect to stripe but is on www.openfoodbrasil.com.br
stripe redirect is configured for openfoodbrasil.com.br, when user lands on OFN: openfoodbrasil.com.br
This is not the only reason we should make openfoodbrasil.com.br redirect to www.openfoodbrasil.com.br, I am pretty sure this is flagging duplicate content for SEO for example.
Etc...
I am re-opening this issue because the report is exactly this problem: in the description you can see how the start point is www and the snail is not on www.

I think this is an S3 and can be converted to an ofn-install issue at some point: make base domain redirect to www.openfood... now I wonder, is this not a simple DNS rules?

**Comment by luisramos0** [comment]
ofn-install#643 represents the changes that we need to do in ofn-install to fix this issue.

**Comment by Matt-Yorkley** [comment]
This issue is tracked in https://github.com/openfoodfoundation/ofn-install/issues/643
