### ISSUE TITLE
Cannot activate account via the verify email link

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#519]
![image](https://cloud.githubusercontent.com/assets/10843056/7310057/463ef334-ea69-11e4-82f0-1e9d712c2910.png)

I was in staging1, and created an account in the sign up process (sallystead@hotmail.com). Rowan then granted this account SuperAdmin status, from his SuperAdmin account. I then created an enterprise owned by my new SuperAdmin account. I received the 'verify your email' email, but when I clicked the link this was the error bar I saw. Consequently I can't verify this account and cannot create order cycles from it.

**Comment by sstead** [comment]
The email conf. directs me to Staging2... I think this is the problem 
![image](https://cloud.githubusercontent.com/assets/10843056/7310378/4bdfc926-ea6e-11e4-858c-3be1950d8320.png)

**Comment by elf-pavlik** [comment]
did someone possibly resolve this issue already?
