### ISSUE TITLE
Order sort by column header doesn't work

### ISSUE THREAD

**Issue by JenSheridan** [openfoodfoundation/openfoodnetwork#5190]
## Description
When you are in the Orders page of backend (e.g. https://openfoodnetwork.org.au/admin/orders ) each column header is hyperlinked, but clicking on them doesn't trigger any action. 

## Expected Behaviour
When you click a column header it should sort by that column. When you click again it should sort in the reverse order. e.g. clicking Shipment State should sort all 'Pending' to the top, clicking again should sort all 'Completed' to the top.

## Actual Behaviour
You click on the header and nothing happens. For some column headers an arrow appears pointing up or down, but this doesn't make anything happen.

## Steps to Reproduce
Go to Order page. Click a column header. Observe nothing happening 😀 

## Workaround
Workaround is to download CSV file and sort, but for some of these that's not a simple sort as the field you want to sort by (e.g. Shipment State) is applied just to order total but not all of the items in the order.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.0
* Browser name and version: Chrome Version 80.0.3987.149
* Operating System and version (desktop or mobile): Mac OSX El Capitan Desktop

**Comment by luisramos0** [comment]
it's an XS

**Comment by dacook** [comment]
I'll take this, pull request #5256 has been submitted.

**Comment by JenRSmith** [comment]
Tested and all working as required. Moved to Ready to Go. Testing notes here - https://docs.google.com/document/d/1FrzdO1lpDQsxOjoDhdx0PTU452wezekVq9vQvwIFaZ0/edit#
