### ISSUE TITLE
Missing jquery-ui image

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5201]
Possibly since some of our Spree asset changes a while back, we've been getting _tons_ of errors for this:

```
open() "/home/openfoodnetwork/apps/openfoodnetwork/current/public/assets/jquery-ui/ui-bg_flat_75_ffffff_40x100-bd8d4ac9eb16341c108b8ef81637c3f5.png" 
failed (2: No such file or directory)
```

It's some tiny jquery-ui image file that apparently isn't being loaded as expected now in the asset pipeline. The file is located in the `jquery-ui-rails` gem.

It's a very small thing, but the downsides to this are:

- we get vast amounts of error logs for this that are just noise, making it harder to find actual errors
- when it's not found (which is all the time) the server returns a whole HTML page worth of data in the response

#### Possible solutions:

- investigate and fix it so we return the image correctly
- remove it from the relevant CSS file (it looks like it might actually not be needed anyway)

**Comment by ckhung5** [comment]
Hi @Matt-Yorkley, I am doing this card as part of my code challenge. I not sure how to reproduce this error. May I get some help from you ?

**Comment by ckhung5** [comment]
It looks like we just need to upgrade the jquery-ui-rails gem to version 4.1.1 as there are changes to look for dependant assets. 

Here is the PR created:
https://github.com/jquery-ui-rails/jquery-ui-rails/pull/59

Here is the changing from OFN jquery-ui-rails version 4.0.0
https://github.com/jquery-ui-rails/jquery-ui-rails/blob/v4.0.0/vendor/assets/stylesheets/jquery.ui.theme.css.erb

Here is version 4.1.1 with changes:
https://github.com/jquery-ui-rails/jquery-ui-rails/blob/v4.1.1/app/assets/stylesheets/jquery.ui.theme.css.erb

**Comment by ckhung5** [comment]
After looking around, this ui-big-flat image is use in Admin page under order cycle tab. My local doesn't have any error without upgrading the gem to version 4.1.1.

**Comment by luisramos0** [comment]
I cannot replicate this locally and I get a 200 on the file:
![image](https://user-images.githubusercontent.com/1640378/82549325-ae2d8b80-9b54-11ea-97ab-6c9332e56074.png)

That means this is related to the assets pipeline in some way as the 404 error in staging is not on the file name exactly but on a file with a timestamp at the end:
![image](https://user-images.githubusercontent.com/1640378/82549412-cef5e100-9b54-11ea-8360-690b8c514df7.png)

I wonder if this timestamp is constant or generated? If it is constant I'd just add the image directly to out /images folder, this is the missing white image btw:
~~~
ui-bg_flat_75_ffffff_40x100
~~~
![ui-bg_flat_75_ffffff_40x100](https://user-images.githubusercontent.com/1640378/82549646-27c57980-9b55-11ea-81ab-be0873e9b9c8.png)
~~~

**Comment by dacook** [comment]
Hi @Matt-Yorkley , I've searched the AU Bugsnag and ruby logs (`zgrep "ui-bg_flat" shared/log/*`), but can't find any instance of this error. Are you able to comment if this is still an issue?
