### ISSUE TITLE
Release v2.9.2 Spinach Dahl

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5203]
Steps: 

- [X] Include translations
- [x] Draft https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-7390d3ba91d6146c8e73
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1321
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by lin-d-hop** [comment]
:boom:
Tested. Looks good. 

https://docs.google.com/document/d/1XruHkPTGmhC3Kkb6UR-wQdrHaBCdRh_ByITsZdVzXEQ/edit#

One small concern that I couldn't take a Stripe payment from the backoffice... though unlikely to be related to this release and not a normal part of release testing.
