### ISSUE TITLE
Missing translation key in inventory error message

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5204]
## Description

The error message states "count on hand" in English

## Steps to Reproduce
1. Go to `/admin/inventory`
2. Leave count on hand and on demand check box blank
3. Try to save
4. See error message

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/79002596-10a46c80-7b51-11ea-8726-b06398ff33aa.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.1
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Desktop

**Comment by rmklaus12** [comment]
@RachL - I am not seeing what I should be seeing? :-) I have no save option, so I'm not sure how to recreate that error message. 
<img width="600" alt="Screen Shot 2020-06-01 at 2 16 37 pm" src="https://user-images.githubusercontent.com/30268789/83375575-a6060380-a412-11ea-8218-54be61bb5bea.png">

**Comment by rmklaus12** [comment]
I was able to get a save button by switching around the On Demand dropbox, but still no error.

**Comment by RachL** [comment]
@rmklaus12 sorry I forgot one step: switch one of your lines to "no" in the on demand column, leave the count on hand blank and then try to save.

**Comment by rmklaus12** [comment]
Like this? Because it saves with no error for me :-( 
<img width="600" alt="Screen Shot 2020-06-01 at 4 56 04 pm" src="https://user-images.githubusercontent.com/30268789/83383627-e1133180-a428-11ea-8f36-80977bedfed6.png">
