### ISSUE TITLE
Money - refunds, account credits and invoicing (make-it-great)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5207]
This epic is to help organise a bunch of potential small changes that dramatically increase the handling of changes to orders and implications for payments i.e. refunds, credits and reissuing invoices

I recognise that some of this crosses into 'delivery note' territory, but am trying to include in here things that I see as 'quick wins' - getting as a big jump in the operation of this part of the system without a full feature design / re-design (while recognising that that is coming)

**Comment by lin-d-hop** [comment]
Remaining issues can be reassigned to other wishlist epics
