### ISSUE TITLE
Remove default 'closed order cycle' message when shop has filled in a Shopfront closed message

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5216]
## Description

- As an Enterprise User
- if I have filled in a message in my Shop Preferences 'Closed Shopfront' 
- the default line "Please wait until the next cycle opens (or contact us directly to see if we can accept any late orders)" should NOT appear My Closed Shopfront message makes this superfluous

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a0cfc029-53f3-445c-a782-19a0f136e9c5)

## Acceptance Criteria & Tests

1. If a Shop has not filled in the Shop Preferences 'Closed Shopfront' message their closed shopfront should include the line "Please wait until the next cycle opens (or contact us directly to see if we can accept any late orders)"
2. If a Shop HAS filled in their own Shop Preferences 'Closed Shopfront' message, the default line should NOT display as their own message replaces it

**Comment by tschumilas** [comment]
sorry -  accidently closed and re-opended this.   Seriously - I'm working so fast  and trying to multi task - don't leave me at these things!

**Comment by luisramos0** [comment]
like this?
![image](https://user-images.githubusercontent.com/1640378/79683388-bcb91800-8221-11ea-87fa-4c972e9984b4.png)

and

![image](https://user-images.githubusercontent.com/1640378/79683392-c3e02600-8221-11ea-9b82-477347f5e979.png)

and

![image](https://user-images.githubusercontent.com/1640378/79683426-fdb12c80-8221-11ea-9fe1-b3c66c2c1f3d.png)


and

![image](https://user-images.githubusercontent.com/1640378/79683489-61d3f080-8222-11ea-9c9c-4ba0fef9e05b.png)

**Comment by luisramos0** [comment]
I got this one done as part of #4772

**Comment by luisramos0** [comment]
ok, updated design according to #4573 and [this decision](https://github.com/openfoodfoundation/openfoodnetwork/issues/4573#issuecomment-616976123), so this becomes:
phone
![image](https://user-images.githubusercontent.com/1640378/79882777-02750c80-83eb-11ea-8ddc-0341dff95c34.png)

tablet:
![image](https://user-images.githubusercontent.com/1640378/79882800-0d2fa180-83eb-11ea-9f46-6cab21520e49.png)

desktop:
![image](https://user-images.githubusercontent.com/1640378/79882842-1c165400-83eb-11ea-86d4-69095c9153ee.png)

and

phone
![image](https://user-images.githubusercontent.com/1640378/79883074-60a1ef80-83eb-11ea-8aa7-d56c9c9681d2.png)

desktop
![image](https://user-images.githubusercontent.com/1640378/79883048-597ae180-83eb-11ea-98af-58867e62dc47.png)


Will now have the same content in Home as well as in Shop according to #4573 .

**Comment by daniellemoorhead** [comment]
Tested, good to go :-)

Testing notes: https://docs.google.com/document/d/1wC42pMcgAAzqnVWBFW_Dm0MrTo5MOosZr_bBwjb56Wk/edit?usp=sharing

**Comment by daniellemoorhead** [comment]
Closing, PR will be merged later once a few fixes to another issue made.
