### ISSUE TITLE
Paypal not set up correctly but transaction appears to be processed (incomplete)

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5225]
## Description
An enterprise (Goughs Range Olives) had not set PayPal up correctly as there was no PayPal pop up at the checkout. It is unclear why the PayPal pop did not appear. But I was able to select the Paypal Payment Method and complete the transaction. No payment was processed but the transaction went through, appearing as 'incomplete' in Admin.

## Expected Behavior
It should not be possible to process a payment with an incorrectly set up Payment Method. When trying to replicate this error, there was an error message when the Paypal method was not set up properly. This did not happen in the case where the error was observed

## Actual Behaviour
The transaction appeared to be completed by no payment was processed.

## Steps to Reproduce

Unable to reproduce. I created a Paypal payment method, didn't enter details from a Paypal account and saved it. I was able to select the payment method, but when trying to check out I saw an error message:

![Screen Shot 2020-04-14 at 11 14 03 AM](https://user-images.githubusercontent.com/47620442/79175516-468f6c80-7e41-11ea-8081-f2592edd80d8.png)

## Severity

S1 for the enterprise in question. No workaround at the moment.  
S2 possibly as this doesn't impact a lot of enterprises -but unsure how many or why.

## Your Environment

* Version used: Aus production
* Browser name and version: Chrome Version 80.0.3987.149

**Comment by kirstenalarsen** [comment]
This is S1. I don't know if the user has or hasn't set up paypal correctly - but I can't see anything wrong with it.

There is one payment method

![image](https://user-images.githubusercontent.com/2911176/79188609-d98cce80-7e62-11ea-8a7e-7aa2cb406e53.png)

which seems correctly set up to me (I think it is correct that the password doesn't appear)

![image](https://user-images.githubusercontent.com/2911176/79188637-ec9f9e80-7e62-11ea-9e6a-119e3a8fd235.png)
![image](https://user-images.githubusercontent.com/2911176/79188665-017c3200-7e63-11ea-8b49-ebd6931f6e7d.png)

In the shop I am given this option
![image](https://user-images.githubusercontent.com/2911176/79188689-15c02f00-7e63-11ea-84f8-46bf08686f15.png)

When I hit Place Order I get this error
![image](https://user-images.githubusercontent.com/2911176/79188721-2c668600-7e63-11ea-866c-96e4b927cb5a.png)

So it is now not letting the order go through but I don't know why

dev tools shows me this
![image](https://user-images.githubusercontent.com/2911176/79188765-515af900-7e63-11ea-96ed-56090f4d2f21.png)
![image](https://user-images.githubusercontent.com/2911176/79188787-6041ab80-7e63-11ea-82e5-87df6edc8aae.png)
![image](https://user-images.githubusercontent.com/2911176/79188807-6afc4080-7e63-11ea-9c8b-c97cadc4b6a1.png)

I am about to set up a different paypal account and see if I can replicate it

**Comment by kirstenalarsen** [comment]
OK, different paypal account works

and confirmed that if I make a mistake in EITHER the password or the signature I can replicate this error. So calling this user error and closing for now. Yay. Thanks @mkllnk  :)
