### ISSUE TITLE
Filters display broken on list pages - filters are currently disabled to hide this, need to fix

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#523]
![image](https://cloud.githubusercontent.com/assets/2911176/7315723/8651b80e-eab3-11e4-85e1-092d6cfc2f79.png)

and when you clear it, it looks like there's no data . . there is, you just have to scroll down a long way

![image](https://cloud.githubusercontent.com/assets/2911176/7315743/afad58ca-eab3-11e4-8c44-5f6a5ad17926.png)

**Comment by kirstenalarsen** [comment]
@oeoeaio - are these in the branch that you've asked @RohanM to review? or elsewhere?

**Comment by oeoeaio** [comment]
@kirstenalarsen yep, in that branch

**Comment by kirstenalarsen** [comment]
ok we're pushing it into staging - if it passes I'll have about 5 mins to check it and make call to push to production to be part of v1.0, can you keep an eye and maybe give it a quick once over on staging as well?
