### ISSUE TITLE
As a shopper UK staging is slow to load products when I first start shopping

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#524]
On UK staging I get the 'loading products' spinning circles for about 15 seconds when I first go to the shop see screenshot
![screenshot 2015-04-24 17 54 40](https://cloud.githubusercontent.com/assets/10517702/7324084/2abc90de-eaab-11e4-903d-105076ae2515.png)
.  @pmackay and @aidandunsdon are experiencing similar delays on their computers.  Is there any way to speed this up?  Thanks N
On UK staging there are now:
155 enterprises
2,884 products with the same number of variants
921 users
These figures don't include the Fife Diet records and other hubs currently on production

**Comment by NickWeir63** [comment]
We are steadily loading more Stroudco products into our order cycle - currently 402 variants and the loading speed is steadily going up - we are now up to 27 seconds.  Here is an email from @getweaving with a suggestion that might make a difference to the loading speed...?
" I was just looking at the OC page myself and noticed all those debugging messages coming up.  They were handy in a way – I could see the Winstones products listed at the end...but I would be inclined to ask one of the Devs to turn them off now.  Unless there’s some good reason for them being there.  They were also turned on on Staging 2 on that function I remember so there may be a reason."

**Comment by RohanM** [comment]
Hi Nick,

I have some time scheduled in the next week or two to work on the loading speed of the shopfront (ie. the "loading products" part). I'll also experiment with removing those debugging messages from the order cycles screen and see if that helps with the  loading time of that page.

**Comment by NickWeir63** [comment]
great 
thanks for all your work - it is very much appreciated over here

**Comment by lin-d-hop** [comment]
Closing as this is reported fixed... by super @RohanM

**Comment by NickWeir63** [comment]
Just had an update to UK staging and yes - this is so much better - all the Stroudco products load in less than one minute - thank you so much
