### ISSUE TITLE
Add https://www.polipay.co.nz/ as a payment option

### ISSUE THREAD

**Issue by roryfogerty** [openfoodfoundation/openfoodnetwork#5255]
## What is the problem we are solving 
https://community.openfoodnetwork.org/t/add-https-www-polipay-co-nz-as-a-payment-option/1912

## Success factors = expected outcome 
Can pay with Polipay. OFN-NZ = customer delight 

## Useful information for inception
https://www.polipay.co.nz/developers/
https://www.polipayments.com/Developer
https://www.polipayments.com/APIintro

## Link to the "Product Development - Backlog" item in Discourse

> NO idea what to write here, sorry

**Comment by luisramos0** [comment]
Hi Rory, was this prioritized? if it wasnt and because it's not a papercut, I believe it should be in discourse only, not in GH.

**Comment by RachL** [comment]
HI @roryfogerty yes Luis is right, we handle all feature request in Discourse under Software improvement > Wishlist: https://community.openfoodnetwork.org/c/software-impovement/wishlist-curation/76
Please have a look and add this suggestion there! Meanwhile I'm closing here.
