### ISSUE TITLE
Internationalise the Business Model within OFN

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#526]
A supplier has the option to change their business type within OFN (supplier, shop, hub etc).

When they display their options currently this displays the Australian business model. We'll need to update this to display our business model....

![supplierinfo](https://cloud.githubusercontent.com/assets/8669848/7332902/7b1cb3a6-eb50-11e4-9c4c-4135e8e94030.png)

**Comment by pmackay** [comment]
Is this the kind of thing that @summerscope is suggesting would move to a global site containing docs?

**Comment by lin-d-hop** [comment]
This is being looked at by @oeoeaio in super charged form.

See http://community.openfoodnetwork.org/t/enterprise-user-accounts/242 for updates on how this is progressing.

My thinking is that UK will just need to configure once this is in place... which, of course, is awesome.

**Comment by myriamboure** [comment]
Same need for us in Norway of course... and yes, configuring the business model and be able to adapt the text in each "package box" to explain it clearly it would be awesome :-)

**Comment by lin-d-hop** [comment]
@NickWeir63 @myriamboure This work has now been completed. You can find out how to use it here:
http://community.openfoodnetwork.org/t/configuration-content/307

@NickWeir63 I'm assigning this to you to see if you can test and check it meets our spec.

You'll see that there is a place in which we need to put in HTML. Don't worry, I won't ask you to write HTML. Just write plain text of what you'd like to see and let me know when you have. I can update to HTML if need be.

**Comment by NickWeir63** [comment]
This all looks great on staging2 - thanks @sstead but I am assuming that I need to make these changes on UK production?  When I go to UK production there is no 'content' option under configuration.  Is this because we are running v1.0 on UK production.  @sstead do we need to wait for an update before I enter the UK details?

**Comment by kirstenalarsen** [comment]
yup, you need an upgrade. will do as part of work over next couple of weeks :)

**Comment by myriamboure** [comment]
@lin-d-hop that seems to be all good :-) And thank you for the improvement on UX design to register a hub... it was pretty hard to find the "Aussie producer" button after the list of shops ;-)

**Comment by NickWeir63** [comment]
here is the text for UK production.  if you can show me how to make it into HTML i will do the rest
thanks
[OFN UK pricing table.docx](https://github.com/openfoodfoundation/openfoodnetwork/files/50668/OFN.UK.pricing.table.docx)

**Comment by lin-d-hop** [comment]
First part of this is done on staging. @NickWeir63 if you think this is ok perhaps copy across to UK production?
https://staging.openfoodnetwork.org.uk/producers/signup

There is still work to be done on this to my understanding:
http://community.openfoodnetwork.org/t/enterprise-index-rebuild/219/13

**Comment by NickWeir63** [comment]
Thanks @lin-d-hop that looks great
I have copied them over to production so we now have:
- pricing table
- case study
- detail
for producers and hubs
I think that is all we can do for now - do you think there is more still to do?

**Comment by lin-d-hop** [comment]
Still to do:
- Internationalise step in sign up process in image above. Just en-GB locale perhaps?
- Change text for free trial period for UK
- Update OFN invoicing to facilitate free if you turnover under £5k for UK
- Change to flat 2% to UK (for dev simplicity and increased turnover)

**Comment by lin-d-hop** [comment]
This should be wrapped up with #814 

Closing...
