### ISSUE TITLE
Testing Spree upgrade

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5260]
Testing plan is here:

https://docs.google.com/document/d/1N_wzCtvib_sLK-I8pwu-HoXaTsrE2xD7aVRojAz5O1g/edit#

PR used to stage it: https://github.com/openfoodfoundation/openfoodnetwork/pull/4825

**Comment by luisramos0** [comment]
Hello Rachel, did I mention this branch is not exactly the final one? This branch includes things from PRs that are still in transit  through the pipe (#4841, #4920 and #4993).
So, it's only good for initial testing.

**Comment by luisramos0** [comment]
I cant remember exactly when but the staged version in UK is now the official one 3-0-stable :+1:

**Comment by luisramos0** [comment]
I have manually activated FR language in uk staging so we can look for missing translations. It will be wiped out on the next deploy but we can keep the current version in there for a few days at least.

**Comment by sigmundpetersen** [comment]
I don't think the upgrade branch is staged on uk now, so removing label to avoid confusion.
Please re-add on next deploy @luisramos0 @filipefurtad0

**Comment by filipefurtad0** [comment]
Thank you for pointing this out @sigmundpetersen !

**Comment by luisramos0** [comment]
I have deployed the main upgrade branch again to uk staging.

**Comment by RachL** [comment]
Now that everything has been merged to master, I'm closing here. Specific issues will be open if needed 🎉 

Thanks a lot @filipefurtad0 !
