### ISSUE TITLE
Snail when tagging a customer with a tag  that has already been used

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5264]
## Error in OpenFoodNetwork UK

**ActsAsTaggableOn::DuplicateTagError** in **admin/customers#update**
'veg-box' has already been taken

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5e9c11eda883cd001769776c?event_id=5e9c11ed0059eeae30230000&i=gh&m=ci)

## Stacktrace

    app/controllers/spree/admin/resource_controller.rb:31 - update

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5e9c11eda883cd001769776c?event_id=5e9c11ed0059eeae30230000&i=gh&m=ci)

*Created by Admin OFF via Bugsnag*

**Comment by RachL** [comment]
No user reports on this since it has been opened. Closing.
