### ISSUE TITLE
Payment state of order paid for before cancellation

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5270]
## Description

When an order is cancelled the Payment State for an order that has been paid for shows as Paid. 
After the cancellation of a paid order the Payment State should reflect that the shopper requires a refund -> Credit Owing.

## Expected Behavior

1) customer places order
2) Payment is captured for the order
3) Order is cancelled and customer has not yet been refunded.  Order should appear in listings order table as figure 3 highlighted in red:
![orcancelledideal](https://user-images.githubusercontent.com/45104035/92407785-7d895600-f133-11ea-8178-bb85eceba705.jpg)
Figure 3

## Actual Behaviour

1) Customer places an order on the platform.
2) Payment for the order is captured. Order appears on listing orders page as shown highlighted in red below

![ordercomplete](https://user-images.githubusercontent.com/45104035/92407520-b5dc6480-f132-11ea-9340-9546e3fa0555.jpg)
Figure 1

3) Order is cancelled. At present order appears on listing orders page as shown highlighted in red below

![orcancellednow](https://user-images.githubusercontent.com/45104035/92407577-e15f4f00-f132-11ea-80a9-0541d90aed19.jpg)
Figure 2
Note: Payment state is green 'Paid'

The customer is owed money by the hub/shop as they have paid for their goods but will not receive them.  Expected behaviour is for the listings order table to reflect this.

## Steps to Reproduce

1. Create an order and ensure it is paid.
2. See that the Payment State displays as Paid
3. Cancel the order
4. See that the Payment State remains as Paid

## Severity

bug s5  potential paper cut
## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX of the ship button and order states](https://trello.com/c/kauOVQHU/786-ux-of-the-ship-button-and-order-states)

**Comment by andresgutgon** [comment]
Hi, I was reading issues with `good first issue` tag and I read all required info for this issue. This is what I saw
![image](https://user-images.githubusercontent.com/49499/92322994-53516e80-f035-11ea-859f-5b360d12ac25.png)


Imo this issue is too complex for being a first contribution :)

**Comment by lin-d-hop** [comment]
Hi @lbwright22 
Thanks for noticing this appears to be solved. Do you think you can add some screenshots that show the issue is resolved and then close it?

**Comment by lbwright22** [comment]
This issue is resolved.
Test: 
1. create an order. Record Payment.
2. Cancel order.
3. View status in listing orders : Payment state = credit owing
![5270closed2](https://user-images.githubusercontent.com/45104035/93997646-890f8a80-fd8b-11ea-869f-094a315b76cc.jpg)
4. view order Payment state = credit owing
![5270closed1](https://user-images.githubusercontent.com/45104035/93997719-9f1d4b00-fd8b-11ea-8f6f-307a5178b764.jpg)
