### ISSUE TITLE
Adding card information on receipt - ex.: Card ********4242 / 22.

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5272]
## What is the problem we are solving 

I feel it would be a good idea to include the last four digits and the year of validity of the card used to perform each payment, on the respective invoice (updated: receipt). I think this may be helpful both for customers and hubs/shops, as an additional method to verify and control which payment is related to which card and order.

## Success factors = expected outcome 

So, additional to the payment method and confirmation, one would see something like:

----------

Paying via: Stripe-Connect

Card ********4242 / 22.

**Comment by RachL** [comment]
@filipefurtad0 I don't think this is something we can do. Do you have examples of retailers doing that?

**Comment by lin-d-hop** [comment]
Every card receipt has this.
Ask for a receipt next time you pay for something by card.... interesting if FR don't do this...

**Comment by RachL** [comment]
@lin-d-hop a receip is different from an invoice.

**Comment by filipefurtad0** [comment]
Yes, I though this would be common practice throughout Europe - at least. It is indeed interesting that this is not the case with France, and perhaps reason enough not to implement this in OFN.

**Comment by lin-d-hop** [comment]
If we get to the point that we issue receipts at payment and invoices when goods are delivered with updated charges... then we should consider these details on the receipt.

Agree with @RachL. Let's close this. #biggerfish

**Comment by RachL** [comment]
This is interesting. It peaked my curiosity so I event went digging out my old Amazon accounts. No credit card info on my invoices, whether I ordered through Amazon UK or FR or US (I'm sooo ashamed of these old account and carbon footprint, anyway...).

Receipt in France do have credit card info. So it is definitely a receipt thing, not an invoice thing? 

If you want to use OFN invoices as receipts I think you can go forward as long as it is only the English template that is affected.
Indeed, POS is France is starting to be "legislated". The requirements that a POS software needs to match to be certified in France is not something we can match with OFN currently. This means also we will soon need to remove the "receip" printer we've built (ironically for us only).

**Comment by filipefurtad0** [comment]
>> @lin-d-hop a receip is different from an invoice

You are right @RachL - the title is misleading. I meant this as a feature for a receipt, an invoice which is settled for, or an order confirmation. So, the document which shows money is in. I've adjusted the title for clarity.

**Comment by RachL** [comment]
@filipefurtad0  I'm sorry again: do you have examples of platforms showing card numbers on order confirmation or invoices? If not I believe the title should only be receipts?

**Comment by filipefurtad0** [comment]
I don't have examples where cards are used on invoices, and that is not really my intention with this papercut suggestion - thus removing from the title.

Perhaps I am missing how to print a document which proves payments/orders/payment methods, which can be used for tax purposes, but does not use the word "invoice"?

Under /orders/#ordernumber/edit -> "Actions" one can find "Print Invoice" and not "receipt", as indicated on the guide:
https://guide.openfoodnetwork.org/basic-features/orders/thermally-printed-receipts#printing-receipts-in-ofn

So, this document changes from "not paid" to "paid", depending on the state of the order, but keeps the wording "Invoice".

![image](https://user-images.githubusercontent.com/49817236/79799239-0ef95680-8352-11ea-8a3f-a6ce31112a51.png)

**Comment by RachL** [comment]
This is the feature I was talking about that was made for France - and I believe France is the only place where you have users using it?  You need a special printer for it. In any case those are supposed to be receipts. I think invoice is not the right translation?
For better and more accurate tax follow up reports are best used for it.

**Comment by Erioldoesdesign** [comment]
I also checked in my amazon account and invoices don't have my last 4 digits but something they call 'order summary' and 'order details' has this in. Also physical stores that offer email receipts instead of paper ones at tills have my last 4 digits too.

I think the key thing here is, we think it might help customer and enterprises/hub managers, but in what ways do we think this helps and do we have to do it this way? If we need/want additional ways to verify a purchase, we can, if needed think of another way :)

**Comment by RachL** [comment]
In FR we are working on being able to be at a stage where we can remove the FR receipt feature OFN has at the moment. More info on this soon! Closing in the meantime.
