### ISSUE TITLE
Product item name not updating

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#5274]
## Description

I updated the item name, but it didn't change in the opened order cycle.
(NB I didn't captures it but it did the same for the price of another product, I had to delete the product and recreate it to get the good price)

![Capture du 2020-04-20 22-57-00](https://user-images.githubusercontent.com/8135376/79799435-bc706800-835a-11ea-9a99-b497d9a35195.png)
![Capture du 2020-04-20 22-57-22](https://user-images.githubusercontent.com/8135376/79799440-be3a2b80-835a-11ea-9201-644f2218c84d.png)

## Steps to Reproduce

Not sure how to reproduce, it doesn't seem to happen for every product, I just had problems for 2 products, one on price, the other on item name...

## Severity

S3, create a new product

## Your Environment

* Version used: Not sure, the last one on French instance ;-)
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu

**Comment by RachL** [comment]
@myriamboure what was the product you had a problem with the name? The one on the screenshot? When is it best for me to try and re-test it on your shop?

**Comment by myriamboure** [comment]
The item name always is for a product, never a variant as long as I remember @RachL 
So it applies to all variants of a product.
I have the case on many variants, still now you can check in the shop now the OC open only tonight it is open tuesday and wednesday all day.
The producer "Aurore de Provence" just told me now that he had changed name from sachet to bocal for one or two products and it didn't reflect on the shop, was still "sachet"... you can check tomorrow when the OC is open if you want or we can quickly open and close the OC if you want to check today :)

**Comment by myriamboure** [comment]
I basically have to "force" the display name on almost all products, I realized modifications I did last week never went through, even on the new OC I created today...

**Comment by RachL** [comment]
> The producer "Aurore de Provence" just told me now that he had changed name from sachet to bocal for one or two products and it didn't reflect on the shop, was still "sachet"...

@myriamboure ah ok so you are talking about the variant unit name. Not the product name. I've compared the product list and the shop for this producer and the info are correct now.

What do you mean by "force"?
