### ISSUE TITLE
Moving from superadmin to just admin on UK staging

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#528]
I want to set myself as a ‘user’ to get only admin access (I previously had superadmin access).  So I unclicked the ‘admin’ box on my nick@nickweir.co.uk login (password localfood1), 

![screenshot 2015-04-27 11 05 46](https://cloud.githubusercontent.com/assets/10517702/7365828/a265e0a8-ed8b-11e4-8d40-f41f0dcb4a67.png)

but this seems to have left this account as a standard shopper with no admin access….
Mags says: I've checked it out and you're right - you're on staging as a user but the side bar menu on the main page isn't giving you an admin option to access the back shop. This is a bug for the dev team

**Comment by kirstenalarsen** [comment]
not a bug. you just need to actually have permission to manage some enterprises, which if you've been operating as superadmin you currently won't. so someone who is super-admin will need to give you permission to manage (and probably own) stroudco. more info here http://community.openfoodnetwork.org/t/managing-users-including-enterprise-users/164

Best if you are the owner of stroudco, as this means magic things happen for you when you create new producers (depending on which version you're running . . so check w @pmackay )
http://community.openfoodnetwork.org/t/what-e2e-links-do-new-enterprises-have/33

**Comment by NickWeir63** [comment]
thanks Kirsten.  I will wait to hear from @pmackay then close this and let @FiferMags know this too

**Comment by aidandunsdon** [comment]
@NickWeir63 @kirstenalarsen @pmackay nick@nickweir.co.uk is already designated as owner of Stroudco and in Enterprise Relationships Stroudco is permitted to add to order cycle and manage the products of its producers.  What seems to have changed from when things were previously working is that Stroudco Foodhub is now designated as a primary producer (unlike Dean Forest hub which is not having this issue). Can you be a hub for others and a primary producer simultaneously? @NickWeir63 If you untick the Producer Role tickbox on the enterprise screen do you then get the access you need?

**Comment by pmackay** [comment]
@NickWeir63 have you resolved this one then?

**Comment by NickWeir63** [comment]
yes thanks this issue is resolved.  the only outstanding question I have on this is to do with Kirsten's point above about the version that we are running on UK staging.  The reason I am curious is because I am trying to do some testing on the new VAT functions and struggling to make it work, then I saw that the Aussies have only just deployed (5 days ago) the latest of Rohan's improvements to the VAT system..... and I wondered if we have these improvements on UK staging?

**Comment by pmackay** [comment]
We definitely dont have changes from just 5 days ago. We could try updating
staging to their latest release (0.8.1)?

**Comment by NickWeir63** [comment]
I dont want to put you to unnecessary work (given how much necessary work there is!).  Let me carry on struggling with it for a while and if it doesn't work I will try again after the next UK update
