### ISSUE TITLE
Tag display does not work for managers

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5282]
## Description

As a manager of a hub, if you tag someone else than yourself, the tag will not be displayed in the list of customers. However it is still working.

A bit disturbing for our users: they have no possibility to check if they have tagged the right person.

## Steps to Reproduce

1. On demo hub in French production (ID 212) I've tagged an OC as "prive". This means that all customers with the tag "vip" can see it and not the others.
2. My openfood account is vip - my gmail account is not
3. Connected as openfood I can see the OC, connected as gmail I cannot - so far so good
4. But as a manager of the hub I cannot see who is tagged with that tag (I've added it to Myriam and myself). The only customer I see with the tag "vip" is a customer that was tagged a few years ago.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/79893204-01040e00-8404-11ea-866a-9f36f49fd27e.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v2.9.4
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

**Comment by tschumilas** [comment]
Tags disappeared from customer lists this morning in 2 Canadian hubs.  All tags but one customer (no idea why that one).  Its not just appearance,  its also functional.  No customer whose tags disappeared is seeing any shops (they were tagged to OC).  I think this makes it an S1 - no?  There is no workaround -  shoppers cannot place orders.

**Comment by luisramos0** [comment]
This was most probably introduced with the performance improve of the customers page.
https://github.com/openfoodfoundation/openfoodnetwork/pull/5196/files
in V2.9.3
A revert to v2.9.2 will most probably fix the problem.
Because it is a problem with the customers page,
- option 1 is that it just breaks tags you change or add
- option 2 it messes tag data around... 
Based on the possibility of option 2 I'd recommend not using the customers page if you can. 

I'd strongly recommend a revert to v2.9.2 on all instances.

**Comment by tschumilas** [comment]
How would an enterprise avoid the customer's page?  Sorry - I"m just not clear on the workaround here?

**Comment by lauriewayne** [comment]
I think that is more a survival strategy until we can revert and less a workaround. Can we safely revert ASAP to minimize possible problems from users unknowingly using the customers page?

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tags not saving on Stroudco](https://trello.com/c/jirlLYB3/927-tags-not-saving-on-stroudco)
