### ISSUE TITLE
bug on UK staging after importing data while shopper had an open cart

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#529]
This is not urgent but will need sorting before we try to import data from another food hub while we are running OFN UK live with Stroudco, DFFH, etc

I had an cart with 2 Stroudco items which i had not submitted.  @aidandunsdon imported DFFH data then reset the system.  Then I couldn't login.  We think this is because there was some incompatibilty between the items in my cart and the new database.  When @aidandunsdon tried to 'empty cart' he got the grumpy cat error message.  we got round the problem by Aidan submitting my order to empty the cart.  then i could login successfully.

**Comment by lin-d-hop** [comment]
Closing on Aidens bequest.
