### ISSUE TITLE
Change PriceSack Minimal amount from Integer to Float

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5303]
## Description

'Price Sack' Shipping method does not consider non-integer figures as Minimal amount, which is used as boundary condition for applying the Normal or the Discount amount. This is related to issue #4654 and PR #4812

While non-integer figures are accepted in the settings of the shipping method, one observes incorrect calculation in on checkout, caused by the truncation of a non-integer Minimal amount. When this happens, the shipping costs are calculated considering the Discount amount in cases which the Normal amount should be considered instead.

## Expected Behavior

'Price Sack' Shipping method should display the correct costs. Minimal amount non-integer values should be considered when these are compared with the order amounts.

## Actual Behaviour

Minimal amount values get truncated, leading to incorrect shipping cost calculations.

## Steps to Reproduce

1. As admin, and set up a shipping method using Price Sack and these exemplary values:

- Minimal amount = 16.5
- Normal amount = 5.0
- Discount amount = 1.0

2. Go to the shopfront, and place an order of 16.
3. Choose the PriceSack shipping method.
4. Observe that the displayed shipping cost is 1.0, while it rather should be 5.0 (as 16 < 16.5)

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/893919dd-9ea7-4730-806d-e8ce2363672d)

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/bc3da353-e82d-4ad3-8cc6-479c1606f4c4)

## Workaround

Using integers for the Minimal amount works fine.

## Severity

S4 - has a workaround, and perhaps not many users are impacted.

## Your Environment

* Version used: v2.9.5 
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Ubuntu 18.04

**Comment by luchiago** [comment]
Hi @filipefurtad0. Can I work on this?

**Comment by filipefurtad0** [comment]
Hey @luchiago,
Sure, you are very welcome! :-)
