### ISSUE TITLE
Change Ready for message for Long term (continuously open) Order Cycles

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5305]
## Description

As a shopper I visit the home page of a hub/shop which has an order cycle which is open all the time.
In the blue order cycle notice box in the top right corner the text 'Next Order Cycle Closing in ....' is displayed.  This is confusing.  I might think I won't be able to collect my food for another year/month.
![withtext](https://user-images.githubusercontent.com/45104035/80464499-cdf4d980-8931-11ea-91fa-052fde41719d.jpg)

Proposed improvement
If order cycle end date is more than 3 months ahead of current date then the text 'Next Order Cycle closing in...' is not displayed.
![withouttext](https://user-images.githubusercontent.com/45104035/80464523-d64d1480-8931-11ea-9160-98fea82ebade.jpg)

## Acceptance Criteria & Tests

1. Set up an order cycle with end date more than 3 months in advance.
2. View shop page as a customer
3. The text 'New Order Cycle Closing in...' is not present  (see above mock up screen shots)
4.

**Comment by RachL** [comment]
hello @lbwright22 I believe that the one Kirsten has opened here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5216 Works as well in your case isn't it? I would favor it as it gives a solution that is broader than one particular use case.

**Comment by lin-d-hop** [comment]
@RachL These are different enhancements

@lbwright22 Rachels comment makes it clear the enhancement isn't yet clearly specified. I gave a few tips on Slack for improving it :smile:

**Comment by lbwright22** [comment]
@RachL and @lin-d-hop hope the description makes more sense now. Sorry for confusion

**Comment by Erioldoesdesign** [comment]
Okay after reading this adding in 'New Order Cycle Closing in...' text when it's missing is fine but I would suggest wording like 'This shop has not set up the next order cycle' or 'Pending next order cycle'

**Comment by Erioldoesdesign** [comment]
Okay so I misunderstood the acceptance criteria on this issue. I agree that when a shop has an order cycle that is more than 3 month in the future, removing the text 'New Order Cycle Closing in...' is good. No UX, no design but just flagging I struggled to understand what the issue was proposing.

The reason why I meddled and was commenting is that I see the order cycle selection as a critical part of the user path to purchase. Critical user paths are where UX, wording and etc. is super important.

**Comment by luisramos0** [comment]
Hello, initially I used 3 months exactly for the OC date test but if the OC closes in 2.6 months from now the message will still be "closing in 3 months". So I used 75 days as the measure in the code. This way the message will never be "closing in 3 months" but either empty or "closing in 2 months". Do you agree this is better or do you prefer to have exactly 3 months?

**Comment by Erioldoesdesign** [comment]
Just a note to say I've seen out on other sites, services that you can place orders for 16 weeks in advance which seems like a lot to me. I expect there are more 'regular' shopper out there where 2 months sounds like way in the future to be ordering goods but also that 4 months has been 'seen' out there. Therefore I would say the original 3 months splits the difference :) so 3 months from my pov but would love to hear Louise & support teams thoughts.

**Comment by luisramos0** [comment]
ok :+1: 
I am not sure I was clear, may I was, I'll clarify amyway:
The problem I tried to solve is that if the OC closes in 3 month exactly, for example from today, 21 Jan 2021. The label will show "closing in 3 month", same if the OC closes on the 15th Jan 2021, it will still say "closing in 3 months". Only if the OC closes on the 6th of Jan 2021, it will say "closing in 2 months". The label will only disappear if OC closes on the 22nd of January or afterwards.
What I did was to make the label disappear, for this example above, if OC closes after the 6th Jan 2021. I did this so that it will never show "closing in 3 months" but only "closing in 2 months" at a maximum.

**Comment by Erioldoesdesign** [comment]
Makes sense 👍

**Comment by Erioldoesdesign** [comment]
@Matt-Yorkley yup, but I'm not sure in what circumstances we have a blank space now given Luis's explanation. Either orders are open until 2 months re. "closing in 2 months" or they are closed. I don't think we have a blank space state in Luis's proposal?

**Comment by luisramos0** [comment]
My proposal is only about the time window when the message shows: I fixed it at max "closing in 2 months".
The original requirement is still there, after this time window is past (OCs closing in 4 months for example) we show it empty as per issue description above.

**Comment by luisramos0** [comment]
I am happy to change it and add some text for those cases of OCs closing in over 3 months, if you agree it's better, should be very easy :+1:

**Comment by Matt-Yorkley** [comment]
So with the proposed changes:
- closed order cycles will display the same as before
- open order cycles closing in less than 3 months will display the same as before
- open order cycles closing in 3 months or more will have the message removed and will have a blank space

**Example OC closing in less than 3 months:**

![Screenshot from 2020-10-31 17-54-50](https://user-images.githubusercontent.com/9029026/97786239-a1ed3600-1baa-11eb-95e7-78db8404e0ce.png)

**What the OC selector will show with these changes, if the OC is closing in more than 3 months:**

![Screenshot from 2020-10-30 10-10-03](https://user-images.githubusercontent.com/9029026/97786191-458a1680-1baa-11eb-9750-6ca218681090.png)

**What we could show instead, for OCs closing 3 or more months:**
![Screenshot from 2020-10-30 10-09-29](https://user-images.githubusercontent.com/9029026/97786204-5dfa3100-1baa-11eb-850d-db829523028e.png)

**Comment by Erioldoesdesign** [comment]
LGTM @Matt-Yorkley

**Comment by luisramos0** [comment]
ok, I can go back to the PR to do that.
@lbwright22 @RachL @lin-d-hop any concerns?

**Comment by lin-d-hop** [comment]
LGTM2

**Comment by RachL** [comment]
Looks great :)  Maybe just a comment that this will need a translation key for that new text. I apologize if this is obvious 🙈 , I just don't want to open missing translation issue anymore :)
