### ISSUE TITLE
Tax report is showing order.created_at instead of completed_at

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5306]
## Description

When looking at the report `/admin/reports/sales_tax` the date shown is `order.updated_at`, we need it to be set at `completed_at` which would then be the same date as shown in `/admin/orders?q[s]=completed_at+desc`. 

## Steps to Reproduce
1. Connected as a manager, check the dates of the report `/admin/reports/sales_tax`

2. See some of them are different from `/admin/orders?q[s]=completed_at+desc` for the same order number

## Animated Gif/Screenshot
Example in French production :

Order page:

![image](https://user-images.githubusercontent.com/6525576/80372479-e1e9fe00-8893-11ea-821f-c0951b5c4e26.png)

Tax report:

![image](https://user-images.githubusercontent.com/6525576/80372447-d5fe3c00-8893-11ea-833a-949f8833d939.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v2.9.5
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile):Desktop

**Comment by kirstenalarsen** [comment]
Disagree that this is s2. It has always been like this and no one noticed until now

**Comment by RachL** [comment]
@kirstenalarsen I don't kbow if you read the full discussion on slack but the reason for it to be tagged S2 was that there is no workaround (no other reports are showing the date) and that it was a really simple job to do (2min).
