### ISSUE TITLE
Error 422 (grumpy cat) on cloning an order cycle

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5307]
## Description

Hub 922 in Frend prod cannot clone some of its OC. These OC contains meat products that I suspects where changed from item to weight. 

## Steps to Reproduce
1. On French prod, try to clone this OC: https://www.openfoodfrance.org/admin/order_cycles/3570/clone
2. See grumpy cat

## Animated Gif/Screenshot
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/99660765-fb82-4454-8d4c-bbb6d8ea656b)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.4
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

**Comment by filipefurtad0** [comment]
I think this is a duplicate of #4216 and discussed in #6527 and #6737, which is being addressed in this week's release. Should we close this issue @RachL ?

**Comment by RachL** [comment]
Well we weren't sure if it was the same as #4216 but I didn't heard of this one, so I'm closing and I will reopen if needed :+1:

**Comment by filipefurtad0** [comment]
Yes, it's related but much less visible I guess, than the broken shopfront... let's keep it in mind :+1:
