### ISSUE TITLE
Product price doesn't not update in the OC

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#5310]
## Description

The veggy producer has changed the price of a poduct for the new OC. The product has the new price in product list, but in the OC it is still the old price strangely...
In front of me he changed another price, for potatoes, and that time the price updated correctly in the OC. But nothing to do with the first product... I asked him what happened when he did the changed, apparently he was updating many things on the page before saving. Maybe that will be a clue... I guess meanwhile I'll have to delete and recreate the product :-( I did that already in the last OC for one product on which I had the same issue.

## Expected Behavior

If I update the price of a product it does update in the OC.

## Actual Behaviour

It does not.

## Steps to Reproduce

I am not sure how to reproduce, as sometimes it does update, sometimes not. Sorry I have no time for such investigations at the moment :-(

## Animated Gif/Screenshot

Exemple on French production on "claytone de cuba" for producer "La ferme du Bouligat"
![Capture du 2020-04-27 21-44-20](https://user-images.githubusercontent.com/8135376/80414183-eb458b80-88d0-11ea-96b1-63601606fb4c.png)
Price is 1,5€
But on the OC:
![Capture du 2020-04-27 21-50-33](https://user-images.githubusercontent.com/8135376/80414835-ecc38380-88d1-11ea-9839-2cbfe34d4396.png)

## Severity

S3 I can delete and recreate the product but it's really annoying...

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by kirstenalarsen** [comment]
any possibility he has an override in Inventory? If it exists it will be used in his Shop regardless of any settings

**Comment by RachL** [comment]
As we have not enough info to reproduce this one, I'm closing. We can reopen if this happens again.
