### ISSUE TITLE
I open and close an OC, it still appears as visible WITH the shop closed message :-(

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#5311]
## Description

The images speaks by itself
![Capture du 2020-04-27 21-53-31](https://user-images.githubusercontent.com/8135376/80414599-93f3eb00-88d1-11ea-870a-7cfe1934c75e.png)

## Expected Behavior

When I close the OC the shop appears as closed.

## Actual Behaviour

The shop appears as closed AND the products are displayed as if it was opened

## Steps to Reproduce

1. I created an OC supposed to start tomorrow
2. To check if everything is ok I open it now, check, and rechange the open date to tomorrow
3. But now all the products are visible even if the shop appears as closed :-(

## Workaround

I didn't find any, I didn't check yet if people can order, I'll do that later today

## Severity

Could be S2 IMO if people can order, need to check so put S2 and S3 label until it's clear

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
@myriamboure are all your delivery and payment methods activated and no tags are involved? When I go to your shop currently I see it closed with no products.

**Comment by myriamboure** [comment]
Yes, all delivery and payment methods and delivery methods are activated and no tags are involved. I am managing other enterprises with that account, so no all payments and delivery methods I see are activated I guess though, but all that I created for that shop are activated.
Ok so if you see it closed with no products, it probably means only me as a manager can see it which is good, BUT I could make an order even if the OC is closed, which is still stranged... But then I guess at least it is s3...

**Comment by kirstenalarsen** [comment]
could this be a cache thing @Matt-Yorkley ? I know it's not meant to be on this page but suspiciously like the thing where info on order cycle open/closed may be delayed into the shops page by x seconds / minutes. Is it possible that there's a typo somewhere that is making it also delay update on the Shop page?

**Comment by Matt-Yorkley** [comment]
We haven't actually implemented _any_ of the potential caching proposals yet, so we'll have to wait just a little bit longer before we can immediately blame the cache when anything goes wrong :wink:

So in this case; the manager of the shop sees the product list as if the shop is open (when the shop is closed), but other users don't?

**Comment by RachL** [comment]
Yes that's what I understand as well @Matt-Yorkley 

@myriamboure we should pair next week when you are doing it so that we can get as much info as possible. You are the only one with the problem so far so we need as much info as we can before we can to be able to reproduce it.

**Comment by RachL** [comment]
Myriam closed her hub so we are not close to reproduce this soon. I'm closing and we can reopen the day we have more info.
