### ISSUE TITLE
Sort invoices in bulk invoice printing with completed_at desc order

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5321]
## Description
**- As a:** enterprise manager
**- On page:** `/admin/orders?q[s]=completed_at+desc` 
**- I want to be able to do:** 
Today when I select orders, the "print invoices" button does give me only the orders I have selected, however it does not keep the order I see in the order page.

If keeping the order is not possible (because too complex regarding filters etc), having them ordered by `completed_at` date would already be a big improvement!

## Acceptance Criteria & Tests

1. Log in as enterprise manager
2. Go to `/admin/orders?q[s]=completed_at+desc` 
3. Use the filters and sort the page in a specific way
4. Then select the orders and click the print button
5. Invoice within the PDF should have the same order as what the user sees on `/admin/orders?q[s]=completed_at+desc`

**Comment by pacodelaluna** [comment]
@RachL I can easily force the order to `completed_at DESC` but I can't make it dynamic easily, lacking some Angular knowledge to achieve this.

**Comment by RachL** [comment]
@pacodelaluna then let's go with the completed_at already, this will saves bugs hubs 3 or 4 hours a week already and I will open another issue to make it dynamic. That will be more the cherry on the cake :-) Thanks!

**Comment by pacodelaluna** [comment]
I will ask for a review then.
