### ISSUE TITLE
When tax is excluded from prices, tax is not separated by line items in the database

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#5331]
## Description
When tax is included in the price (throughout Europe & Aus), there's an adjustment in the database for each line item that equals the amount of the tax.   When tax is not included in the price (US & CAN) there's an adjustment in the database for the order in the amount of the tax. In these - tax excluded from price situations,  all of the tax amounts are summed for each order before they're put in the database.

For a simple farm shop,  selling a mix of taxable and non-taxable products this is not a major issue. When they run,  for example,  an Order Cycle Customer Totals report -  they can figure out the taxes on the order by subtraction.  (Total for the customer -  items+fees = taxes that were paid).   Or,  they can go through the invoices -  which list the taxes paid on the bottom.

However, for a hub shop,  selling products from suppliers with both taxable and non taxable products,  it is impossible  to get information to allow payouts to the suppliers,   and the suppliers themselves cannot get their tax information 'out' of OFN.

For example -  the Order Cycle Customer Totals report for a hub,  lists line by line each variant purchased,  from each supplier.  It gives the item cost (the supplier's price) and it gives the cost + fees (markups and other fees) for each variant.  But the tax per product is not available.  The tax is rolled into the customer's total for the WHOLE ORDER.  

You can figure out the total taxes paid on an order,  but there is no way to allocate these to individual suppliers with the data as it is currently provided. 

## Expected Behavior
A hub should be able to find the information in OFN to issue a correct payout (by whatever means - cheque, cash, bank transfer or automated splitting using Stripe) to their vendors.   And/or a supplier should be able to find information in OFN reports from which they can prepare their invoice to a hub. 
  Even if this isn't available in a report format,  it should be possible to do it with some scripting or other.  But this seems not to be possible either at the moment.  (I'll leave others to explain why not)

## Actual Behaviour
Line information on taxes is not available for instances where tax is exclusive of price.

Hubs like farmers' markets that take payments and issue payouts to vendors,  have decided they cannot use OFN,  and moved to other suppliers.

Other hubs have passed the problem to the suppliers who need to issue invoices weekly to the hubs. These suppliers can't get their information out of OFN either - so they keep parallel records.

## Steps to Reproduce

1. Use an instance where tax is excluded from price
2. Set up a hub with multiple suppliers selling taxable and non-taxable products.

3. Make an order
4. Try to find the amount of money owing to an individual supplier,  including the taxes they are owed.

## Workaround

If a hub's suppliers sell only non-taxable products its fine -  the OC customer or suppliers totals work.  If  a hub's suppliers sell only products taxable at the same tax rate -  its fine because we can calculate the taxes given the product prices.   These are the kinds of hubs we've had in OFN-CAN to date.  But now, we have farmers' markets setting up as hubs,  and their suppliers are selling a mix of taxable and non taxable items.   A hub would have to run an OC Customer's total report,  and manually go line by line,  across all orders,   identify if the variant is taxable and at what rate (from the supplier's product list),  calculate the line tax manually.   

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
I think the best next step here is to create a good example order in staging or prod so we can see exactly what is the actual behavior and what is expected behavior.

**Comment by tschumilas** [comment]
Example case:
Demo Hub,  sells products from 2 suppliers:   Demo Farm,   and Demo CSA
Each supplier sells 1 taxable and 1 non-taxable product.
The hub also added some flat fees -  so you can see these show up.  I didn't include an enterprise
fees bundled in the shop price just for easy math.  

I placed an order for all 4 products.  The shop and buyer are in Ontario -  tax rate on taxable products is 13%
The order admin screen is below -  shows  the 13% tax total on the order - calculates correctly.

I ran an order cycle customer totals report - below.
Shows the item subtotals and total  (that does NOT include tax)
Shows the fees totals.
Shows the order total.  By subtraction (order total - fees - item total) the user knows that the
order incurred $2.60 in taxes.  Which is correct.   But there is no way  for anyone (user or customer) to know WHICH items incurred tax .  This technically not legally compliant - but I can live with that short term.  The bigger issue is that the hub has to pay the right supplier the right amount of tax.  They have no way to know this,  short of reviewing each order against the supplier's product list.

![tax on orders - order admin screen](https://user-images.githubusercontent.com/13171778/80736075-a0e62980-8adf-11ea-9835-00222d879deb.png)
![order cycle customer totals report](https://user-images.githubusercontent.com/13171778/80736098-a774a100-8adf-11ea-9d8d-704c46810733.png)

**Comment by luisramos0** [comment]
ok, thanks, that's very clear!

The database supports this in the adjustments table the source of the adjustment can be the line item BUT in this case the source of these adjustments of $1.3 is the **order**... but in some other cases (I see lots of it in AU live db for example) the source of the adjustment is the **line item** (which would make it possible to get the data to a report) but maybe it's when the tax is included in the price... I dont know and this is where the we would need to enter investigate the mess...

**Comment by tschumilas** [comment]
Indeed -  this is the conclusion from Sean  @Fug1 at the start of this issue:  When tax is included in the price (throughout Europe & Aus), there's an adjustment in the database for each line item that equals the amount of the tax. When tax is not included in the price (US & CAN) there's an adjustment in the database for the order in the amount of the tax. In these - tax excluded from price situations, all of the tax amounts are summed for each order before they're put in the database.

**Comment by Fug1** [comment]
Yeah, you've got it exactly right @luisramos0. If tax is included in the price, there is an adjustment for the **line item** in the amount of the tax. When tax is not included in the price, tax is totaled for the order and stored as an adjustment for the **order**.

We can't realistically create a report that includes tax for each line item with the currently available information in the database.

It seems to me we need a change in the code so that it creates an adjustment in the database for the tax amount on each line item when tax is not included in the price. If we had that, we could create a report.

**Comment by luisramos0** [comment]
ok, we agree about the problem.

My problem is that I cant even think of a solution for this in the code. It's complicated and it will break things if we try to change it. I think this is the worse part of the ofn codebase...
The long term solution is to stop using spree and then gradually simply the existing code.
Maybe another dev will have a brilliant idea how to get something useful in the short term...

**Comment by kirstenalarsen** [comment]
@Matt-Yorkley @mkllnk @kristinalim @sauloperez any 'other Dev' feeling a eureka moment?

**Comment by kirstenalarsen** [comment]
@Fug1 @luisramos0 if the actual tax rate was just included in the line item in the API that would mean it can be calculated right? Even if the amount itself isn't in the database?

**Comment by Fug1** [comment]
I think it would be helpful to get the tax_category in the orders api output. It's in the spree_line_items table, but doesn't get included in the line item section in the orders api output.

But then you still have the problem of trying to figure out the tax_category of the enterprise fees. The fees show up in adjustments, and you need to figure out the tax_category by looking in the enterprise_fees table. If the tax_category for the fee is supposed to follow the product, you then need to match up the fee with the appropriate spree_line_item or product.

So I think it could be difficult to put it on the api.

And most importantly, without storing the tax information in the database at the time the order is created, you end up with potential discrepancies if the tax configuration on the system changes between the time the order is created and the time the report is pulled.

**Comment by RachL** [comment]
> My problem is that I cant even think of a solution for this in the code. It's complicated and it will break things if we try to change it. I think this is the worse part of the ofn codebase...

I wonder if the conclusion of this discussion in discourse wouldn't help? https://community.openfoodnetwork.org/t/co-budget-and-organization-around-the-tax-overhaul-dev/748/32?u=rachel

The price estimation at the end seems very low, I have no idea how accurate this was... this is 3 years old now... but it is even possible I think we should have a serious look at it.
I'm mentioning this as fyi in Europe tax is also excluded when the buyer is an enterprise... and many other weird cases this conversation in discourse describe.

**Comment by Erioldoesdesign** [comment]
I suspect this isn't a papercut based off just the developer time needed on this not even to start with unpicking the UX, UI and design problem statements...

**Comment by lin-d-hop** [comment]
There is no way this is a papercut :joy:

**Comment by sigmundpetersen** [comment]
So if it's still viewed as an enhancement and not buggy behaviour, this should move to Discourse.
If not we should change the label.

**Comment by kirstenalarsen** [comment]
Is it fair to say that this is getting handled in the adjustments refactor and I can close this issue? @Matt-Yorkley @tschumilas @lin-d-hop ?
