### ISSUE TITLE
After deleting a product I can't cancel an order containing that product

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5335]
## Description

Once a product has been soft-deleted it still appears in orders placed.

If I then want to cancel that order I cannot.

message = 'You need to save the variant to create a stock item before you can set stock levels.'

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5da4ec3ec076fc0019b57ad6?filters[event.since][0]=30d&filters[error.status][0]=open

## Expected Behavior

I want to be able to cancel orders that contain deleted products

## Actual Behaviour

I cannot cancel an order than contains a deleted product

## Steps to Reproduce

1. Create an order with a product
2. Delete the product
3. Cancel the order
4. Death by slug

## Workaround

Possibly by recreating the product and then cancelling the order? I haven't tested this.

## Severity

bug-s3: a feature is broken but there is a workaround of adding a negative adjustment.
I'm not sure if there is a workaround. This seems to mostly impact people making test orders on the system. This doesn't seem to impact people so often once they start trading.

## Your Environment

* Version used: UK 2.9.6
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Helston can't delete order](https://trello.com/c/QeZeUz6H/996-helston-cant-delete-order)

**Comment by RachL** [comment]
😱 and here I am deleting products for one of my users.... too late :'(

**Comment by Matt-Yorkley** [comment]
I wrote a spec related to this yesterday. When a variant is soft-deleted it's line item is hard-deleted...

**Comment by Matt-Yorkley** [comment]
Cancelling the order obviously tries to restock the deleted variant.

**Comment by Matt-Yorkley** [comment]
I don' think there's a workaround here, but it should be fairly simple to fix.

**Comment by luisramos0** [comment]
v3 brought soft deletion to stock items, I wonder if this one is solved...

**Comment by filipefurtad0** [comment]
For a newly created on_demand variant and after placing the order with it, it seems possible to and delete this variant (which is perhaps useful information to add to #5947). After deleting this variant, it's possible to reproduce this bug by attempting to delete the order:

![image](https://user-images.githubusercontent.com/49817236/92264157-b4fac700-eed5-11ea-9fa7-9bcd0dedd121.png)

Bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5f2ab6c5e81dc80018dea912?event_id=5f526da0005dec4b9a3f0000&i=sk&m=nw

**Comment by filipefurtad0** [comment]
> Cancelling the order obviously tries to restock the deleted variant.
That makes sense. Also, it's not possible to remove or refund those items, from the previously placed orders:

![image](https://user-images.githubusercontent.com/49817236/103761818-317ded80-500f-11eb-9c93-04451fc2e14c.png)

This was reported here:
https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1609931360401700?thread_ts=1609927942.401600&cid=CG7NJ966B

**Comment by cmittal791** [comment]
![localhost_3000_admin_orders_R445323256_fire_e=cancel](https://user-images.githubusercontent.com/81350194/112599707-4d3aa800-8e36-11eb-8733-1f1708ed2288.png)

**Comment by cmittal791** [comment]
I have fixed this on my local dev machine .. will be writing test, committing, and requesting pull ..

**Comment by filipefurtad0** [comment]
Thank you @cmittal791!
I'll assign you to this issue :+1:

**Comment by cmittal791** [comment]
Thanks!

**Comment by meronokbay** [comment]
I will pick up this one.

**Comment by filipefurtad0** [comment]
Thank you @meronokbay for picking this up!
I've assigned you to the issue. Please let us know if you have any questions.

**Comment by sigmundpetersen** [comment]
OK no worries @meronokbay . Thank you for your contributions so far, hope to see you back another time 💪

**Comment by RonellaG** [comment]
We have a producer (Enterprise 3452) that has deleted 2 products and now wants to cancel order R455001031 that contains them but cannot because of this bug.

As far as I can see there is no workaround for this. This producer sells seasonal products and this is likely to happen again for them.

For now I am going to suggest they make a negative adjustment for the value of the order and name the adjustment "Zeroing order as unable to cancel order for deleted products".

**Comment by georgethoppil** [comment]
I can take a look at this if no one else is

**Comment by sigmundpetersen** [comment]
Sure, go ahead @georgethoppil . Thank you 🎉 

There was a previous attempt at this in #7622 that you could take a look at if you want.
It was only missing additional specs I think.
