### ISSUE TITLE
Release 2.9.7 Coconut oil

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5346]
Steps: 

- [x] Include translations
- [x] https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-f9b0c414afabbbc401d4
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1373
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by luisramos0** [comment]
ping @RachL ready for testing ;-)

**Comment by RachL** [comment]
@luisramos0 sorry for taking so long I had a long play with payment methods :) But I haven't found anything blocking the release.

It is now ready to go !

I was singing this song all along: https://www.youtube.com/watch?v=fP01RNDDsPM

Coconut > Coco > Iko Iko... yeah don't search further :D

**Comment by luisramos0** [comment]
:rofl: that song is funny!
