### ISSUE TITLE
Cart Problems in Production

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5358]
We've now had a couple of downtime incidents caused by a cart bug, on multiple production servers.

If the `CartController#populate` endpoint (add-to-cart) returns an error code, the page will keep trying to post data to the cart endpoint again and again and again. Twice now we've had the add-to-cart endpoint return a `412` (we don't know why yet), and then it subsequently kept re-posting the data over and over, and this can cause serious problems.

More details in a thread from Friday 01 May in the (private) channel **#devops-notifications**

#### Proposed fix(es):

- [ ]  Investigate and fix whatever caused the initial `412`. #5361 
- [ ] Fix the problem of the add-to-cart code continually spamming the endpoint with lots of requests if an error is returned. Maybe just show an error to the user, and _not_ continually re-POST the data. #5371

**Comment by luisramos0** [comment]
I guess you meant bug-s1?
What downtime are you reffering to? The FR one a few weeks ago or something new?
