### ISSUE TITLE
Producer emails gives auth failure if not admin . .

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#536]
I am the coordinator of this order cycle and should be able to send emails

**Comment by pmackay** [comment]
@kirstenalarsen where can I find some info on how to check for permissions related to this?

**Comment by kirstenalarsen** [comment]
For this one I reckon safest way to start is just that owner or manager of
the coordinator has access. Can increase auth to others if needed later

**Comment by pmackay** [comment]
But is there a code pattern used elsewhere for checking permissions?

**Comment by kirstenalarsen** [comment]
I'd guess that you could look at the code for any admin page and see that.
Order cycles page itself should already have most of what you need e.g.
only the coordinator can change the dates. If its not obvious, its a
question for @rohanm or @oeoeaio

**Comment by RohanM** [comment]
@pmackay See `app/models/spree/ability.rb` `add_order_cycle_management_abilities`. There's also a corresponding spec in `spec/models/spree/ability_spec.rb`. This file controls access to admin actions. Adding the `notify_producers` action alongside `bulk_update`, `clone` and `destroy` looks like it might give you the correct logic.

**Comment by pmackay** [comment]
Closing based on @NickWeir63's testing today, but other issues still persist.
