### ISSUE TITLE
[Spree 2.1] Product Import: product saving shows frozen progress bar

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5363]
## Description

When importing products, the progress bar freezes upon product saving (see 2nd pic below). However, product import seems to be successful, as manually clicking Products and going to the product bulk edit page shows the complete list of newly imported products.

Also, it is worth noting, that only 1 HTTP request is visible, for validation (1st pic below) and saving (2nd pic below), which is not what is expected on the current test suite.

## Expected Behavior

After successful import, the user should be redirected to /admin/products. 

## Actual Behaviour

The page freezes (see 2nd pic below).

## Steps to Reproduce

1. Go to Product Import
2. Import a csv file - I've used this one:
producer,sku,name,display_name,category,description,units,unit_type,variant_unit_name,price,on_hand,available_on,on_demand,shipping_category,tax_category
Melon Farm,1,Apples_2,Apples_2,Fruit & Vegetables,,2,kg,,5,1,222,,Refrigeration,Zero rated
3. No errors should be detected. Click Save.
4. You should get the non-progressing saving bar (2nd pic)

## Animated Gif/Screenshot

validate_data - see HTTP requests
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/febd0ee8-167e-4bc7-96db-18c86fc0f401)

save_data - frozen progress bar
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/90d495ab-039c-4034-a076-e65b887ec677)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
ok, I see what's the problem.

The error can be seen on dev tools, on that resquest you show but on the response tab:
![image](https://user-images.githubusercontent.com/1640378/81791411-9aec4180-94fe-11ea-87be-1bf466426203.png)

It's a problem with duplicate product permalink apples-2.

On investigation I see that in master the code is smart enough to generate unique permalinks for the products, but the new version is not.
This problem can be avoided by importing a product that the permalink will not be repeated in the database (there are quite a lot of products in staging UK, I had used "Apples 40" in the name that generates the unique permalink apples-40).
This problem can be replicated (without relying on existing permalinks) by importing the same product to 2 different enterprises. The second import will fail with this error.

If we import "Apples 40" in master to 2 different enterprises, the permalink of the product in the second enterprise is "apples-40-41", this new version will try to save a duplicate permalink "apples-40" and fail.

The solution will be to see what has changed in the product permalink code in spree 2.1 and adapt OFN's PermalinkGenerator class.

**Comment by filipefurtad0** [comment]
Awesome @luisramos0,

I just imported a product with a unique name, and it works fine - no permalink issues.

Checking this and also related to doubles, I noticed that I try to update the stock, using the import function - uploading the same product, same variant name, to the same enterprise, just a different on_hand value results in this error:
![image](https://user-images.githubusercontent.com/49817236/81796919-fbcb4800-9505-11ea-9424-a91f8e5a3845.png)

A further clue in solving this issue, I hope.

Thanks for this update!

**Comment by luisramos0** [comment]
hmmm... yeah, I got to that error as well locally. I am not sure how they are related though :man_shrugging: BUT I deployed my fix to the variant_unit_name issue (it's a straight forward thing) and deployed the PR to staging UK and now I cant replicate the original error: permalink.

Can you try to replicate the original problem in staging UK now? There's PR #5420 in there now.

**Comment by filipefurtad0** [comment]
I can't seem replicate neither the permalink nor the variant_unit_name error. Both seem fixed :+1:

**Comment by luisramos0** [comment]
ah, nice, that means the extra variant_unit_name field was making the permalink logic break. I dont really understand how this could happen but I don't think it's worth investigating now. We can move forward. I'll move the PR to code review, thanks Filipe!

**Comment by filipefurtad0** [comment]
@lin-d-hop observed this issue again on release testing, on #6013 . It may relate to #5947 .

This is currently reproducible with the [file](https://docs.google.com/spreadsheets/d/1Y_zJwg_dW3InHhZBQH_Jkai7S1u-OvG6iJ3_x38gD6Y/edit?usp=sharing) Lynne provided points out to the previously reported error:

![image](https://user-images.githubusercontent.com/49817236/93066157-8917d800-f671-11ea-9f27-301747e7dff5.png)

**Comment by filipefurtad0** [comment]
Closing via #8876.
