### ISSUE TITLE
Adding a shipping method to an order as an admin should be VAT excl. 

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5368]
## Description

When adding a fixed fee to a shipping method, this fee is added Tax included.

Yet when selecting as an admin a shipping method with fees, the amount is showing fees + VAT, which is not correct

## Expected Behavior

Fees seen by the customer should be the same as those seen by the manager.

## Actual Behaviour

OFN shopfront:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/f4e59830-7256-468e-95d6-26fa6ab7d405)

OFN backoffice:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/f95953f2-2286-41dc-b651-1891d9d30d80)

## Steps to Reproduce

1. Create a shipping method with fees with a fixed amount
2. Make an order in front office, see the amount is correct
3. Make an order from the backoffice, see the amount is higher.

## Workaround

I guess the work around is to still select the shipping method and then add an adjustment removing the incorrect amount? Not sure if this doesn't screw the VAT report...

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.7
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

**Comment by JasmeetLuthra** [comment]
Hi Rachel. Is the issue still there? 
I tried reproducing the issue using the described steps but the shipping amount displayed is same in both front & back office.

**Comment by RachL** [comment]
hi @JasmeetLuthra yes the issue is still here but you need to assign a tax to your shipping method. It's something done here: https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ofn-platform-configuration/taxes-and-tax-zones#tax-settings

Let me know if this helps!

**Comment by JasmeetLuthra** [comment]
Thanks @RachL  I reproduced the issue after assigning tax. Can i start working on this?

**Comment by sigmundpetersen** [comment]
Yes you're welcome to start working on it and submit your PR on this! 👍 Thank you.
Please have a look at the [readme](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/README.md) and [getting started](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/GETTING_STARTED.md) sections if you haven't already!

**Comment by RachL** [comment]
yes! welcome on board @JasmeetLuthra :)

**Comment by luisramos0** [comment]
Hello @JasmeetLuthra  welcome to OFN, I recommend you look at good-first-issue label or the welcome new developers board.
I dont think this is a good first issue, actually I think this is a bad-first-issue :-) code related to taxes is tricky in OFN. Off course you can try!!! Good luck either way!

**Comment by JasmeetLuthra** [comment]
> Hello @JasmeetLuthra welcome to OFN, I recommend you look at good-first-issue label or the welcome new developers board.
> I dont think this is a good first issue, actually I think this is a bad-first-issue :-) code related to taxes is tricky in OFN. Off course you can try!!! Good luck either way!

Hello @luisramos0 ! Thank you for your insights . Yes, I am finding it quite hard to understand the taxation on shipping price. Whatever setting you do the price of shipment remains same . Even if I doesn't select "tax included in price" the shipment price remains same during the final checkout.  
If that's how it works , then changing the shipping_rate's  'display_price' to 'cost' in shipping partial  shows shipment price without any tax. But I don't know if that's how it should work so I didn't make any PR. 
Yes I think I should  move to good first issues first to have the better understanding of the codebase first. 
Thanks

**Comment by luisramos0** [comment]
you are welcome @JasmeetLuthra 
I think the change will be during checkout workflow on adjustment.rb where there is some logic to include/exclude taxes from adjustments, in this case, shipping fees.

**Comment by filipefurtad0** [comment]
Hey @RachL ,

I've observed this recently as well:

![Peek 2021-03-11 10-47](https://user-images.githubusercontent.com/49817236/110775738-2c2f6000-8257-11eb-9cbe-d0a5d6c1b184.gif)

In the example above, this shipping fee is displayed as 4,8 Eur but contributes to the order amount with as 4 Eur which is correct. So the extra 0,8 Eur do not add up to the order total.

In the example you report, do the 0,33€ add up to the order total?

**Comment by apricot12** [comment]
I still cant reproduce this, can you confirm this is still an issue? @RachL

**Comment by RachL** [comment]
@filipefurtad0 @apricot12 

Indeed this seemed to be fixed. Anyone know what this switch does? Couldn't find it in the user guide

![image](https://user-images.githubusercontent.com/6525576/159301940-d1a3ecd2-d239-4a33-8984-9683976dae39.png)
