### ISSUE TITLE
Broken shopfront in an edge case where OC is closed but products are fetched from database

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5369]
## Error in OpenFoodNetwork UK

**AbstractController::DoubleRenderError** in **api/order_cycles#products**
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5eb156ca1a8b83001807eff7?event_id=5eb156ca005b3525783d0000&i=gh&m=ci)

## Stacktrace

    app/controllers/api/base_controller.rb:74 - error_during_processing

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5eb156ca1a8b83001807eff7?event_id=5eb156ca005b3525783d0000&i=gh&m=ci)

*Created by Admin OFF via Bugsnag*

**Comment by luisramos0** [comment]
bug introduced in this release:
https://github.com/openfoodfoundation/openfoodnetwork/pull/5315/files#r420067156

We are not sure how edgy this case is: 1 user impacted in UK and 1 user in AUS. It's a very easy fix so I think we should get a release out to fix this.

**Comment by Matt-Yorkley** [comment]
I've investigated this a bit, and looked at the exact order cycle that was visited on UK Prod. It looks like it closed part-way through somebody shopping (they reached their order limit and manually shut the shop).

Looking at the code as well, I think this issue only affects closed order cycles, and the result of the error is just that we don't load any more products from the product list endpoint after it's closed.

So I think this is actually not an emergency, it basically will not really impact users. We can fix it for sure, but it's not the end of the world.

**Comment by Matt-Yorkley** [comment]
Is it a bug or a feature? :rofl:

**Comment by RachL** [comment]
So if I understand correctly: it's the case of customer adding stuff to their card and navigating through the products => But bim, the shop owner decide to close earlier... So the "fix" would make sure we gracefully re-direct the user to the shop close message if he tries to add a product to cart or something equivalent?

**Comment by Matt-Yorkley** [comment]
Yes, the hub closed the OC while someone was shopping, and they scrolled down through the products, and it did not load more products. 

I think we actually already redirect the user to the homepage with a "this order cycle has closed" message (it happened to me when I tried to check those affected order cycles). Maybe that happened as well, shortly after.

**Comment by luisramos0** [comment]
ok, great Matt, that makes sense.
I tagged S2 assuming this was a snail but you are right, this is only an ajax call that will fail. The user will not see it. The user will just not get an update of the list of products and sooner or later (probably by clicking somewhere), user is warned and redirected.
I am changing to S3.

**Comment by Matt-Yorkley** [comment]
Already fixed and in code review :+1:
