### ISSUE TITLE
Error loading UK staging on iPhone and iPad with iOS Safari 

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#538]
I just had this email from a Stroudco tester (Crockett) whose email is crockett@ebleyweb.co.uk

Sarah and I both tried to look at the link you sent but found the website doesn't work properly on iPhone or iPad. The page loads to start except for the list of foods - the loading circle animates for a while then a message saying "A problem occurred with this webpage so it was reloaded". After this repeating a few times the web browser replaces the rest of the website with a message that the website failed to load.

I tested the website on my android tablet (running androidOS 4.4.2), the website loads fine - so this issue seems to be iOS Safari browser specitic.

**Comment by pmackay** [comment]
Am reassigning this to @RohanM as he is looking at performance issues for the product loading. Good to have this testing feedback that can feed into that work.

**Comment by NickWeir63** [comment]
We were reviewing this issue as part of our UK dev update just now and wanting to check whether there was anything that we could do or if @kirstenalarsen @RohanM  or @oeoeaio could suggest?
Thanks

**Comment by kirstenalarsen** [comment]
nope nothing you can do, unless you want to join rohan in working on performance :) Might be worth checking aus prod now though as 1st tranche of performance stuff has gone through and would be cool if it had made a difference. I suspect it won't have though because it doesn't have the changes to product loading yet . .

**Comment by lin-d-hop** [comment]
Over to Nick to test once v1.0 is on UK staging

**Comment by NickWeir63** [comment]
We have now tested this and it is working fine - thanks very much.  There are still some issues with text being a bit small but I think we can move this to backlog and deal with the text size as a lower priority later.

**Comment by pmackay** [comment]
@NickWeir63 suggest close this and open a new issue about font sizes? That sounds like something @elf-pavlik and others could do during hackathon easily.

**Comment by NickWeir63** [comment]
Great - @elf-pavlik if this is possible for you to look at then my tester suggested that we also change the way OFN displays on iPhones so that it does not change format when you turn the iPhone on its side

**Comment by elf-pavlik** [comment]
Tomorrow we will know if someone will bring iPad / iPhone and would like to work on it

**Comment by pmackay** [comment]
@NickWeir63 could you check with the person who raised this if its still an issue? I just closed #248 after testing production on my iPad mini and it seemed fine.

**Comment by NickWeir63** [comment]
ok i will ask him

**Comment by NickWeir63** [comment]
Still no response from Crockett - sorry
I am happy to close this now
