### ISSUE TITLE
Currency name (руб.) incorrect displays on Russian locale

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5394]
## Description

In this path:
/admin/products/moloko/variants
"Price" show incorrect currency name, in codes (50.00 �,440;�,443;�,431;).
When interface language is selected as English, it's Ok.
But when interface language is selected as Russian, it's not Ok

## Expected Behavior

When interface language is selected as Russian, it should displays as "руб", like in English locale (pls see images below)

## Actual Behaviour

show codes "50.00 �,440;�,443;�,431;"
And In the Cart too

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

[Bad](https://drive.google.com/open?id=1DILUNotqRUh8edYqZ4dOSPMQlcyGrqdE)
[Good](https://drive.google.com/open?id=1pdf3vvWIZfxnhlKlSEgZUaejMoY2deTj)
[Add to Cart(Good)](https://drive.google.com/open?id=1_FS511aKasnwN--JGB535Hm7cOHWNqJH)
[Edit Cart(Bad)](https://drive.google.com/open?id=1AY_tCFsbZikgPkoiZxt1TFalqDHLlxNM)
## Your Environment

* Version used: OFN 2.9.6
* Browser name and version: Firefox 68.7.0esr
* Operating System and version (desktop or mobile):
openSUSE 15.1

**Comment by RachL** [comment]
@openfoodfoundation/core-devs can this be a good-first-issue?

**Comment by romale** [comment]
@RachL , this https://github.com/openfoodfoundation/openfoodnetwork/issues/5436#issuecomment-634755002 commands solves many issues with translations, and this issue too.
So I close it.

**Comment by romale** [comment]
No, it's not working in right way.
On OFN 3.2.9 this issue is still exist. Language file from transifex

**Comment by luisramos0** [comment]
The workaround could be to set a currency sign that does not contain special Russian characters?

**Comment by romale** [comment]
@luisramos0 , it looks like https://github.com/spree/spree/issues/2737 solves this problem

**Comment by romale** [comment]
Solved in v3.5.6
