### ISSUE TITLE
Add warning message to shipping and payment methods edit page

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5399]
## Description
There are two unresolved problems with shipping methods, with @RachL we agreed that it's a good short term solution to add a warning message to the edit ship methods page so that users are aware of some consequences of de-associating a shipping method from an/their enterprise.

The problems are that, de-activating a shipping method:
- and then editing a complete order that have not been shipped and is assigned to that shipping method, will automatically remove that shipping method from the order and assign another active shipping method #5367
- will make the shipping method disappear from the list of shipping methods (this one is applicable to payment methods as well) #4837

## Acceptance Criteria & Tests
Edit Ship method and see a clear warning message.

## Possible solution
Some points to be defined for this message:
- Location: I dont think it needs to be on the list of ship methods, the user cant do much in that page.
I'd add it to the edit page only, is that ok?
- Position: Would the text be on the top of the page or bottom of the page above the update button? Maybe top of the page is better?
- Style: Highlighted in red or just like this?
![image](https://user-images.githubusercontent.com/1640378/81548523-55e8d380-9375-11ea-960d-0ab947f6e82b.png)
- Text - What would be the exact text?

This was suggested by @RachL: "do not edit your shipping method with big changes (completely change the name, de-activate or remove fees) if you have orders with this shipping method that has not been shipped yet".
I'll give it a try:
"De-activating a shipping method from your enterprise can make the shipping method disappear from your list as you will not have permissions to edit it. Additionally, if you edit an order that have not been shipped but is assigned to that shipping method, the order shipping method will be automatically changed to an active shipping method. Alternatively, you can hide the shipping method from the checkout page by setting the option "Display on" to "back office only"

We can also add this message to payment methods, a more simple version:
"De-activating a payment method from your enterprise can make the payment method disappear from your list as you will not have permissions to edit it. Alternatively, you can hide the payment method from the checkout page by setting the option "Display on" to "back office only"

**Comment by RachL** [comment]
> Location: I dont think it needs to be on the list of ship methods, the user cant do much in that page.

Well they can de-activate a shipping method, which sucks if they have only one enterprise, but I'm fine to put it in the edit page for now.

> Position: Would the text be on the top of the page or bottom of the page above the update button? 

I think top we have more space?

> Style: Highlighted in red or just like this?

I don't think we have anything in red currently? So I guess we must go with your suggestion. I'm dreaming to get rid of that small blue font one day :)

**Comment by luisramos0** [comment]
I think I'll ignore this part of the message:
"   - if you edit an order that has not been shipped yet but is assigned to a de-activated shipping method, the order shipping method will be automatically replaced by an active shipping method. "

It's just too much text to put on the page :face_with_head_bandage:

**Comment by luisramos0** [comment]
![image](https://user-images.githubusercontent.com/1640378/81820854-06e39f80-9529-11ea-9907-641ba9900356.png)

![image](https://user-images.githubusercontent.com/1640378/81823755-8c1c8380-952c-11ea-99ff-018b6ada9bc9.png)

**Comment by luisramos0** [comment]
@RachL the PR is now in code review, let me know if you want me to change something!

**Comment by RachL** [comment]
@luisramos0 I think we are good. Though I remember @tschumilas mentioned that people were also sometimes editing name or fees, and this led to not ship orders to be wrong as well. But I guess we will be able to add it in translation :) So let's move forward!

**Comment by luisramos0** [comment]
yes, we could have added that case as well...
