### ISSUE TITLE
Fix-up shop/hub list navigation

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#540]
- add >> icon after name to indicate click will take you elsewhere
- when name >> is clicked, don't open up the 'fat view'
- deactivate link on right hand side
- add v icon to far right so is more obvious that clicking the bar will open up more info
- do we need a 'loading' spinner so that it's clear something is happening?  Or hope that the performance work going on will also help, as the shop page won't take so long to load

**Comment by rickginer** [comment]
Kirsten - I don't think we need a spinner personally - the browser spinner kicks in once you click the link, but let me know how it feels to you and we can always add one in.

Fix added to https://github.com/openfoodfoundation/openfoodnetwork/pull/553
