### ISSUE TITLE
Repeated entries in Orders and distributors Report 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5400]
## Description

Orders and distributors report at:

admin/reports/orders_and_distributors

shows more than the expected entries. For example, an order of 4 items shows up in 16 times in the table. If the number of items n in that order is 1, then all is good. So, for n > 1 then a n^n behaviour is observed (pic below).

It's worth noticing this was observed before the latest release v2.9.8, across different staging servers.

## Expected Behavior

The report should show one line per item in that order - right?

## Actual Behaviour

Items appear repeatedly in the report. 

## Steps to Reproduce

1. User - Place an order with n items
2. Admin - Check the report and observe that the number of lines in the table relate to the number of items in the order, in a exponential fashion, n^n, ex.: 4 items = 16 entries.

## Animated Gif/Screenshot

Order #R387418680:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/619164aa-e7b4-4dde-9be2-afbcd961fcb2)

Order R387418680 corresponds to order_id=1017:
![Screenshot_2020-05-11 Reports - OFN Administration.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/af66d26e-9e0c-46e0-b8a3-b9cd5b0d3a67)

## Severity

I am rating this an S3, but thoughts are welcome, as I am not sure on the real impact of this issue.

## Your Environment

* Version used: v2.9.8
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Desktop

## Possible Fix

Not really a fix, but related with update of specs for these reports:
Check and update test coverage of Orders and Distributors report #4746

**Comment by tschumilas** [comment]
This could be nothing related - but I'd feel bad if I didn't mention.  The large hub here that still can't run their OC_ Customer Totals report (even though our timeout has been re-set)  has also had problems with duplicate data entries showing up in the product lists of some of their suppliers.  We have not figured out where the duplicates came from -  but they seemed to show up sometime during the order cycle.  Everyone involved says they didn't do anything.  I've been doubting them - and assuming someone went in and duplicated products....    But - now this makes me wonder if this is linked.   Just thought I"d mention it.  Hub is BAileys Local Foods on OFN-CAN if it seems like anything worth looking at.

**Comment by emilyjeanrogers** [comment]
I was able to replicate this on a test Enterprise in Aus. Placed an order for 4 items and it appeared in the Orders & Distributors report 16 times.

**Comment by mkllnk** [comment]
I wrote an automated test for this and then tried to find when we introduced it. I went back as far as January and my test says the same thing: 2 line items result in 4 rows on the report. Are we sure this is new?

I will dig into the code now to find the logic doing this.

**Comment by mkllnk** [comment]
Okay, I think I found the change that made this fail: 13633e8bea3cf7b8720f9d8698f255a8d0f0ace2 was included in v2.7.0 deployed on January 21st.

Is it fair enough to downgrade this to s2 because it has been in production for nearly four months? If you know the pattern, you can also recognise the duplicates and remove them from the report manually. Is that a workaround?

I'm quite close to a solution though and would fix this regardless of the severity level.

**Comment by luisramos0** [comment]
downgraded to S2 based on the fact that is broken since January.
anyway, the fix is in, thanks @mkllnk :+1:
