### ISSUE TITLE
Translation of "Type in location" in /map not works

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5409]
## Description

I've translated "location_placeholder" attribute to russian, but no change on web interface

## Expected Behavior

"Введите местоположение ..."

## Actual Behaviour

"Type in a location..."

```
/home/openfoodnetwork/apps/openfoodnetwork/current# grep -R location_placeholder *|grep ru_RU.yml
config/locales/ru_RU.yml:  location_placeholder: "Введите местоположение 

```

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/81706732-dba17780-9478-11ea-9945-8ddf17734c97.png)

## Your Environment

* Version used: ofn 2.9.6
* Browser name and version: 68.7.0esr
* Operating System and version (desktop or mobile): Desktop openSUSE 15.1

**Comment by RachL** [comment]
@romale are you still experiencing the issue?

**Comment by romale** [comment]
No, thanks.
The solution here https://github.com/openfoodfoundation/openfoodnetwork/issues/5436#issuecomment-634755002
