### ISSUE TITLE
Shop / hub list - limit Producer's list so that it's not crazy . . 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#541]
When a Hub has lots of producers, the list in 'fat view' gets really long (see example below)

Use the x y z [+ 3] control to show that there are more but limit initial view to 6-8 (so 3-4 rows)

**Comment by rickginer** [comment]
Pull Request submitted https://github.com/openfoodfoundation/openfoodnetwork/pull/554

**Comment by sophiejackson1** [comment]
Seems that something has changed, there is now text saying '+ 35 more' and 'show less' but it hasn't reduced the length of the producers at all. See image: 
![screen shot 2015-05-14 at 4 45 25 pm](https://cloud.githubusercontent.com/assets/12440964/7627272/037406a2-fa59-11e4-9e0a-fc53bf8f4434.png)

**Comment by rickginer** [comment]
@sophiejackson1 That's not what it's supposed to look like! It doesn't look like the pull request has been merged yet so is this issue related to that @RohanM ?

**Comment by kirstenalarsen** [comment]
will follow up with @RohanM  - pretty sure he had merged it, otherwise the +35 more wouldn't be there at all

**Comment by RohanM** [comment]
I just had a look at it. I'm seeing it working on some hubs and not on others:

- When there are less than 7 hubs, I still see the more/less button with "-6 more" or similar.
- Inactive hubs display with the list expanded by default.

Could you have a look into those issues?

**Comment by rickginer** [comment]
@RohanM @kirstenalarsen my bad - I put the code somewhere that would only work for the Hub your were currently shopping at. Should be good now.
