### ISSUE TITLE
Katuma Server Upgrade

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5418]
Issue for tracking Katuma Server Upgrade. 

Currently scheduled for Saturday night.

### Pre-Migration

- [x] Buy a new server
- [x] Create a temporary subdomain and point it at the server
- [x] Set up some temporary configs for the new server (`hosts` entry, `host_vars`, etc)
- [x] Run the`setup` playbook on the new server
- [x] Use the new `letsencrypt_proxy` playbook on the current server, specifying the new server's IP
- [x] Run the`provision` playbook on the new server
- [x] Deploy the current release to the new server

### Migration

- [x] Set the current server in maintenance mode, with a nice custom message
- [x] Stop `unicorn` and `delayed_job` on the current server
- [x] Transfer the assets to the new server (includes all images, which are not hosted with S3)
- [x] Migrate the database to the new server with `db_transfer` playbook
- [x] Restart `delayed_job` and `unicorn` on the new server to ensure changes are picked up
- [x] Check everything is okay on the site
- [x] Run `transparent_proxy` playbook on the current server, pointing to the new one

### Post-Migration

- [x] Switch the domain name to point to the new server's IP
- [x] Leave some time for the DNS to propagate, then shut down the old server
- [x] Clean up the ofn-install inventory entries so only one remains, with the new IP address

### Optional Extras

- [x] Remove the temporary subdomain
- [x] Regenerate the certificate on the new server, with the temporary subdomain removed from the list

**Comment by Matt-Yorkley** [comment]
I'm doing a quick bit of hacking/prep for the migration on `fr-staging`, so marking it as in use...

**Comment by Matt-Yorkley** [comment]
@sauloperez un regal :point_up: :gift: :wink:

**Comment by sauloperez** [comment]
![](https://media.giphy.com/media/S9oNGC1E42VT2JRysv/giphy.gif)

**Comment by sauloperez** [comment]
The list looks good. I would go with the optional extras if it's not too late because these things become expensive tech debt quite soon.

**Comment by Matt-Yorkley** [comment]
> I would go with the optional extras

Cool, I added those at the end as a non-critical tidy-up.

**Comment by Matt-Yorkley** [comment]
Since I'm about to mess with the certbot validation mechanism on the current production server I did a quick check of your certificate's renewal date. 

42 days left, no passa nada.

**Comment by sauloperez** [comment]
![](https://media.giphy.com/media/KWhczKwjE3AuQBWWjc/giphy.gif)

**Comment by Matt-Yorkley** [comment]
Hot tip for the cleanup steps: if you want to recreate the certificate on the server with a different set of subdomains supplied in the configs, you can do this:

`ansible-playbook playbooks/provision.yml --limit es-prod -e "certbot_force_update=true" --tags certbot`

Make sure the DNS is updated and the entry for `es-prod` is pointing at the new server first :trollface: :

**Comment by sauloperez** [comment]
A fix we needed: https://github.com/openfoodfoundation/ofn-install/pull/615
and the cleanup: https://github.com/openfoodfoundation/ofn-install/pull/616

**Comment by Matt-Yorkley** [comment]
I think that was the smoothest and fastest server migration to date! We had to do a quick bugfix part way through, and Pau stopped during the downtime to open a PR, but next time will be faster and easier.

:heart_eyes: :rocket:

**Comment by sauloperez** [comment]
Something Eugeni spotted is that preferences (I guess all) weren't properly picked up. He saw emails were labeled as "Spree demo site". It turns out that although preferences in DB got successfully migrated, the Rails cache contained the seed data values from the initial server setup. I had to run the following to invalidate and refetch from DB.

```
irb(main):003:0> Spree::Preferences::Store.instance.clear_cache
```

We should document this somehow or even automate it @Matt-Yorkley .

**Comment by Matt-Yorkley** [comment]
We did a restart of unicorn and delayed job, right? Its weird they weren't picked up initially.

**Comment by sauloperez** [comment]
yes, very weird... I can't find an exact explanation.

**Comment by Matt-Yorkley** [comment]
> Spree::Preferences::Store.instance.clear_cache

That cache clearing seems like an important step, we should add it to the wiki page. Would a full `Rails.cache.clear` be a good idea?

**Comment by sauloperez** [comment]
Yesterday we shut down the old production server but we'll wait another week to finally remove the server and the DNS record. Just to have a fallback.

**Comment by sauloperez** [comment]
Eugeni just reported that Metabase now refuses connection. We didn't check that and I bet we didn't update the db_integration settings.

This is the message

![photo5938519163146449249](https://user-images.githubusercontent.com/762088/82888068-2a571300-9f49-11ea-9cb7-3e70e8c3e020.jpg)

**Comment by sauloperez** [comment]
We forgot to run the db_integrations playbook :see_no_evil:

**Comment by sauloperez** [comment]
Done :tada: !
