### ISSUE TITLE
Shop-front: alerts and validation 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#542]
- Shopfront lets me put incomplete integers in qty, and shows them on quick cart as valid. But then when I go to checkout, it just rounds down to highest complete integer (so if i put 0.5 it goes to zero). Can we change to integer in shopfront and notify customer that we are doing so
- The quantity field limits to the amount that is left in inventory. But it doesn't actually tell the user that - so I'm typing in 8 and getting 3 and I'm CONFUSED. Can i have a little warning or something? Also a problem if customers don't notice the automatic adjustment.
- Group buy: Disable max field until min field has a value

**Comment by sstead** [comment]
In regards to dot point 1, the system is basically just ignoring me when i hit the decimal. So if i type 1.5 I get 15. And if I type 8.5 I get 85. If my inventory is set at 10 and I type 1.5, I get 10. So there is still some potential for confusion.
In the Edit My Cart page, when you try to update the cart with a decimal in place you get this... This is good and could maybe be implemented in the shopfront in the future.

![image](https://cloud.githubusercontent.com/assets/10843056/9751491/e10e3082-56e8-11e5-89e0-703b645ded11.png)

In regards to dot point 2 - this hasn't been done yet.

In regards to dot point 3 - Yes, this has been done and is working. The max field is not editable until there is a min value. However, a Max value below the Min value is still allowed. 
![image](https://cloud.githubusercontent.com/assets/10843056/9751577/e194cb82-56e9-11e5-8c58-e00e506b59d2.png)
