### ISSUE TITLE
Sales tax report is showing amounts per types without adjustments

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5428]
## Description

No idea if this is a bug or a new feature, but this is preventing a user to do his official VAT declaration... :facepalm:

Indeed in France we have several VAT rates, let's keep it simple for understanding the issue: wine is at a 20% VAT rate and cheese at a 5,5% VAT rate. 

So an order can have products with different tax rates.... but also adjustments with different tax rates as well...

## Expected Behavior

I think we need to have for each tax type the amount with adjustments, so that the sum of all tax type equals the total tax amount.

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/e36467de-3c08-42af-8a01-84f20a62bcfc)

## Actual Behaviour

The 1,51 euros in the 5,5% tax type is the previous amount of tax on products _before_ a negative adjustment with a 5,5% tax has been added.

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/0bdc2a5b-fcd4-4adb-8dc8-ba2f21c39799)

## Steps to Reproduce

1. Take an order without adjustments and have a look at the `admin/reports/sale_tax` per type
2. Add an adjustment on this order with a tax type
2. Check `admin/reports/sale_tax` again
3. See the amount in the tax rate you have selected has not changes but the total tax amount reflects correctly the adjustment

## Workaround

No idea, I've been doing now the report manually for them, but I've been lucky they only had 5,5% VAT adjustments. In the future they will also have 20% VAT adjustments, and because of https://github.com/openfoodfoundation/openfoodnetwork/issues/5422 I'm not sure what tax rate they've used in adjustment... But I can't also find the adjustment tax value without looking through each order one by one... :boom:

## Severity

? 

## Your Environment

* Version used: v2.9.8
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Desktop

**Comment by pacodelaluna** [comment]
Ok, I was able to reproduce the issue locally, the Adjustment has to be negative actually for the issue to pop up. I will dig a bit more.
