### ISSUE TITLE
Improve map search and filter

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#544]
Currently the map only enables search by location (also only suburb, not street address). 

This is really annoying if you're looking for a particular farm or hub, or for a product category

Explore integration of auto-complete into the search bar, so that starting to type the name of an enterprise in the page will show you options for matching enterprises
- clicking on one of those options will zoom the map to near them (? and open modal . . pushing my luck?)
- q? the auto-complete will still show you options for matching addresses as well (yes please?)
- not selecting a suggested option will just send your query to the location search and google will do its best

Optional: similar for product categories . . so have the ability to type "fruit" and filter by enterprises that have "fruit"

Optional: enable search by street address as well

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/discovery/1177
