### ISSUE TITLE
Pointer on map does not reflect on address

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5442]
## Description

If i add address1 to enterprise, no pointer on map.
After insert coordinates to DB by hand, the pointer is shown on map. And, nothing changes on map after changing the address1. An addresses is correct and disacovered by google maps.
Also i was try to fill address2, nothing changes.

## Expected Behavior

After fill address1 of enterprise, pointer should be on map.

## Actual Behaviour

No pointer on map

## Steps to Reproduce

1. add or change address1 to/on enterprise
2. see map
3.
4.

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 2.9.8
* Browser name and version: Firefox 68.8.0esr
* Operating System and version (desktop or mobile): Desktop openSUSE 15.1

**Comment by luisramos0** [comment]
Hi! can you pls add more details about "After insert coordinates to DB by hand"
what exactly did you insert in the DB?
Thanks!

**Comment by romale** [comment]
Hi @luisramos0 ,
I do this:
`update spree_addresses set latitude='55.41030689999999', longitude='37.9024513' where id='3';`
I wrote about this in that thread https://openfoodnetwork.slack.com/archives/C0DNLAZC7/p1589045435218600

**Comment by romale** [comment]
From google console
![image](https://user-images.githubusercontent.com/928628/82142112-ae6f1380-9842-11ea-9bb5-a22616578681.png)

**Comment by luisramos0** [comment]
ok :+1: That means geocoding is not working for you.

I am not sure what's the problem.
This is the setup guide:
https://github.com/openfoodfoundation/ofn-install/wiki/Google-Maps

Could this be a problem with google geocoding not finding the specific address you are trying? can you try an address in another country that is working in another instance?

I'd go to another instance, create enterprise, add address and make sure it works, shows on the map. Then use that address on your instance and see if it works.

**Comment by romale** [comment]
I was change address to 100% valid on google maps and the result is same, no changes on map.
![image](https://user-images.githubusercontent.com/928628/82147325-a1105400-9857-11ea-947c-814f402fc791.png)
![image](https://user-images.githubusercontent.com/928628/82147743-7f639c80-9858-11ea-8918-bdcde2798af5.png)

On UK OFN
![image](https://user-images.githubusercontent.com/928628/82147814-07e23d00-9859-11ea-9504-abb23546267b.png)

>I'd go to another instance, create enterprise, add address and make sure it works, shows on the map. Then use that address on your instance and see if it works.

and after creating the enterprise, the OFN owner will not be able to delete it? :)

**Comment by romale** [comment]
@luisramos0 i was set google api restrictions to None and now address change is working!
Before i was this restrictions
![image](https://user-images.githubusercontent.com/928628/82148030-87bcd700-985a-11ea-9fe6-fec0930043bd.png)

Now address changed (but with some browser console errors)
![image](https://user-images.githubusercontent.com/928628/82148045-a622d280-985a-11ea-80f8-2f8cfc29ee1d.png)

**Comment by romale** [comment]
For future cases.
This google api restrictions does not work in this sequence for OFN URL "openfoodnetwork.ru"
```
*.openfoodnetwork.ru/*
openfoodnetwork.ru/*
```
But in this sequence is working
```
openfoodnetwork.ru/*
*.openfoodnetwork.ru/*
```

**Comment by romale** [comment]
@luisramos0 , thank you for your assistance!

**Comment by luisramos0** [comment]
I am sorry but I do not understand your previous comment, can you pls clarify if the problem is solved for you?
If the problem is solved can you try to explain what was the cause and solution?
Thanks!

**Comment by Matt-Yorkley** [comment]
Removing the Google API restrictions is needed. I think its in the wiki. It's solved now, right @romale?

**Comment by luisramos0** [comment]
ah, ok, on the wiki it says "no restrictions" is the default...

**Comment by romale** [comment]
> I am sorry but I do not understand your previous comment, can you pls clarify if the problem is solved for you?
> If the problem is solved can you try to explain what was the cause and solution?
> Thanks!

I'm sorry @luisramos0. Yes, this need solution description.

If i'm using HTTP Google API restrictions, so pointer on the map does not work. But if I use IP address Google API restrictions (and define OFN instance IP), all working fine.

**Comment by romale** [comment]
> Removing the Google API restrictions is needed. I think its in the wiki. It's solved now, right @romale?

it is impossible to leave in work without restrictions, only for the duration of testing. Otherwise, anyone will be able to use the API key and then you will be left without money in your google account

**Comment by luisramos0** [comment]
ok, that makes sense! but the wiki page is saying a different thing. I wonder what other instances have? "No restrictions"?

**Comment by romale** [comment]
> ok, that makes sense! but the wiki page is saying a different thing. I wonder what other instances have? "No restrictions"?

From OFN CANADA API key seems work fine in my instance :)

**Comment by romale** [comment]
Accordingly, anyone can use the api key until the money runs out on the account.

**Comment by luisramos0** [comment]
:-O

So I wonder if this still true?
"Unfortunately, the current restrictions model doesn't allow us to use the same key for Google Maps and geocoding. So we need to keep the key without restrictions."

**Comment by romale** [comment]
One key is used for the specified api in the Google console. It may be Maps and/or Geocoding. And in principle, you can use one api key for all ofn nodes. It depends on what community policy.
In my opinion, it is better to make restrictions for api. But maybe there is some secret meaning in "without restrictions", which is unknown to me.

**Comment by romale** [comment]
OFN UK also without api restrictions
