### ISSUE TITLE
Missing translation keys in Enterprise info

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5445]
## Description

I've translated all of them, but translation does not work

![image](https://user-images.githubusercontent.com/928628/82141688-43244200-9840-11ea-8ead-f17bc65b151c.png)

![image](https://user-images.githubusercontent.com/928628/82141702-4f100400-9840-11ea-8aca-834c9f7cd51b.png)

## Expected Behavior

Translation should work

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: 2.9.8
* Browser name and version: Firefox 68.8.0esr
* Operating System and version (desktop or mobile): Desktop openSUSE 15.1

**Comment by luisramos0** [comment]
Hi @romale, as you shared on the other issue, you are not following the standard translations process with transifex.
Anyway, if the keys are on the file you are probably having problems with unicorn or the assets. You can try to recompile assets on the server manually.
This is far from the recommended way to proceed so I wonder if we should close this issue or not.

Can you please upload your translations to transifex? That way they will be persisted for the future.

**Comment by romale** [comment]
Solved in https://github.com/openfoodfoundation/openfoodnetwork/issues/5436#issuecomment-634755002
