### ISSUE TITLE
[Spree 2.1] Stripe SCA - broken links on authentication page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5447]
## Description

The authentication page of Stripe SCA payment method leads to two broken links, by choosing Complete Authentication or Fail Authentication (below):

![image](https://user-images.githubusercontent.com/49817236/82161122-0aad5400-9892-11ea-9f84-93e4df78ad8c.png)

Both of these lead to:

![image](https://user-images.githubusercontent.com/49817236/82161152-3defe300-9892-11ea-8573-9c2bf3293a9f.png)

Choosing Complete Payment does not finish the order: no confirmation email, no amount arrives the hub.

## Expected Behavior

Payment should be sucessfull of fail, depending on choice

## Actual Behaviour

Broken link (second pic above).

## Steps to Reproduce

1. Set up the Stripe SCA payment method
2. As a user, attempt a payment with a 3D secure card, for example 4000002500003155
3. On the authentication page, choose Complete Authentication or Fail Authentication
4. Broken link.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: WIP 3-0-stable LATEST BUILD
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): desktop

**Comment by luisramos0** [comment]
Hey Filipe, I tested this on staging UK (with the new stripe setup using the UK live stripe account on test mode) and it is working correctly.
I think this was a problem with the stripe setup of the instance.
Can you please give it a try again? Thanks!
Old saved cards wont work because the stripe setup has changed. If you want to test saved cards you need to add them again

**Comment by filipefurtad0** [comment]
Awesome @luisramos0 ,
Stripe-SCA payments now work fine - The redirection works as expected after authentication.
I performed a brief sanity check on SCA functionality - Saving a card and paying with a saved SCA-card - all good now :tada:

**Comment by luisramos0** [comment]
cool, thanks Filipe!
