### ISSUE TITLE
Make multiple pick-up locations visible in the shop/hub list 'fat view'

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#545]
Many farms and hubs have multiple pick-up shipping methods, and it would be really useful for the user to be able to see these to inform their decision on where to shop

At the moment they can only see whether there is a pick-up and a delivery
![image](https://cloud.githubusercontent.com/assets/2911176/7515540/3d0f2124-f50b-11e4-91d1-7bb144dca6a2.png)

Show multiple pick-up shipping methods if they exist, using names provided - abridged if necessary? [We will have to go through a data clean as people are using these quite descriptively so some are long]
- could be using a [+ xx] control to show more
- delivery option goes at top if it exists

**Comment by lin-d-hop** [comment]
Nice to have but seems like we just don't care that much! #gitcull
