### ISSUE TITLE
Can the links to shops on the group page open into new tabs?

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#5454]
## Description
At present on a group page - see for example: https://openfoodnetwork.ca/groups/www-openfoodnetwork-ca-justfoodfarmstand#/producers,   each of the links to different farm shops opens in the same tab.   Is there a way to change the links so each opens in a new tab?

In OFN_CAN we have a number of farmers' markets set up as groups.  But,  because we don't have split payments,  each vendor is taking their own payment.   These users are wondering if we could help things along by having the links open in new tabs - that way when a shopper checks out from one market vendor,  they will still have the market group tab open  to go back to find the next vendor to shop from.

I know this isn't a bug - its an enhancement,  but I'm wondering if its a paper cut?  Anyone? 

## Expected Behavior
Operating as expected - just not great user experience.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by kirstenalarsen** [comment]
I have added this to the potential papercuts pile. I think it is clear enough from a product perspective (@lin-d-hop ) - @sauloperez could you check it re. tech and then we could put into 'next up' for @tschumilas to choose in next round?

**Comment by lin-d-hop** [comment]
I feel like this could have been more clearly described using the feature template. Can still be a papercut.

**Comment by jeduardo824** [comment]
@tschumilas Could you check the GIF in #5601 and let me know if this is what you are expecting?

**Comment by tschumilas** [comment]
I can't actually tell from the GIF.  What we were asking was - for example -  if I open Freddy's farm shop,   can I leave it as an open tab,  and go back to the producer list,   and open a second shop in a new tab.  So -  I would have 2 vendor shops (or more) open in my browzer in different tabs at the same time.   This would enable me to shop in 2 shops at once by going back and forth between tabs.  is that more clear?    (Sorry I didn't know how to slow the GIF down and it went too fast for me to see)  😉

**Comment by jeduardo824** [comment]
Yes, it is more clear, thanks.

![Screen Shot 2020-06-15 at 06 24 22](https://user-images.githubusercontent.com/27960597/84641182-1449cc00-aed1-11ea-9369-5552c7a86fe8.png)

Just to confirm: Do you want this behavior on the content inside the red square or the blue square? I can change both or just one.

**Comment by tschumilas** [comment]
The red square.

**Comment by jeduardo824** [comment]
@tschumilas I took the liberty to expand the behavior for the blue square too because I noticed that some producers have a lot of shops when the tab expands.

**Comment by luisramos0** [comment]
I am only seeing this issue now. I'm not sure this is a good product decision. Is everyone aware we do not support multi tab shopping, for example, shopping in 2 different shops at the same time? There are different scenarios where things can go wrong if this is done. Opening shop pages in separate tab will encourage this and generate trouble. Supporting shopping in multiple shops at the same time can be done but it's not a small task.

**Comment by tschumilas** [comment]
Thanks @luisramos0  -  I had just assumed that a buyer could buy from 2 shops at the same time if they were open in different tabs.  But I just tried -  and yes of course you are correct.   The buyer gets an error as soon as a product is selected in the second shop.   Damn it.   So - I guess we don't proceed with this issue at this time.     Boo hoo.     Sorry to everyone that I didn't realize this earlier.

**Comment by luisramos0** [comment]
Actually I got here from the v3.1.0 release notes:https://github.com/openfoodfoundation/openfoodnetwork/releases/latest
So this is already in production in some instances and will soon be on all instances.

**Comment by tschumilas** [comment]
Hmm --- so we might have some problems.  Although when I tried to order in 2 shops at once,  I did get an error that stopped me -  so that's good.   But instances might get asked about it from users.  Lets see what happens I guess.

**Comment by emilyjeanrogers** [comment]
@tschumilas I agree we might have some problems with this fix.  Especially in Aus as we are beginning to focus on using Groups to generate traffic to multiple producers ie. for Farmers Markets and Regional Hubs - and will be encouraging customers to use this Groups page to access multiple shops in a single shopping experience. 

I just tested this with two subsequent purchases in different shops, each opened in a new window. I didn't close Shop 1  after completing the purchase. The error message I got when attempting to checkout in Shop 2 didn't provide a way out / resolution, and sustained even after I had closed the Shop 1 window. I had to refresh the page before being able to checkout in Shop 2. 

Maybe this needs more thinking, and perhaps even we revert in the interim?

**Comment by tschumilas** [comment]
Is reverting an option?

**Comment by filipefurtad0** [comment]
Awesome that you spotted this @luisramos0 - I did not think of it while testing. Thank you @emilyjeanrogers as well, for verifying and reopening the issue.

I agree this encourages shopping and multiple tabs, so we may get several issues soon. Should this reversion/fix be prioritized and moved to Dev Ready? Maybe it would still make it to the patch being prepared for version v.3.1.0.

**Comment by luisramos0** [comment]
yes, reverting is an option. It's unfortunate because we took the time to develop it but yes, we can do it easily if you think that is the best approach. I think it is the best approach.

**Comment by luisramos0** [comment]
I created the PR that reverts this, it's in code review now:
https://github.com/openfoodfoundation/openfoodnetwork/pull/5770

**Comment by tschumilas** [comment]
I also feel bad that we wasted time -  so very sorry @filipefurtad0  -  I just simply didn't understand that we didn't support shopping in two different tabs.   Is all your work wasted?   If we create a wishlist item to enable shopping in 2 tabs at once,  would we be able to use what you've done?   What do people think about a wishlist item like this.  @emilyjeanrogers -  it seems like Aus is down the same path as Can with groups and markets.... -  would shopping in multiple stores be something your users would want too?

**Comment by lin-d-hop** [comment]
@tschumilas This needs to go to wishlist. The scale and scope of this work is unknown and pretty freakin huge.

**Comment by filipefurtad0** [comment]
Hey @tschumilas,

I just tested the PR and the developers work - which is @jeduardo824's, and not mine. But anyway, I do believe this is part of the process: to support each other in making better choices :+1:

**Comment by luisramos0** [comment]
yeah, agree with Filipe. It's not a big deal. The important bit is that we can look back and improve.
Let's revert. I think the revert should close this issue and leave things as they were before.

After that we can go to the wishlist item to make shopping in multiple shops at the same time possible. Getting multiple open carts for a given shopper to retain their contents as the shopper jumps between shops should be straight forward, a day or two of dev time. In itself a pretty nice feature I think. Getting it to work in paralllel browser windows is a little bit more complicated but not huge. Anyway, see you on discourse ;-)

**Comment by emilyjeanrogers** [comment]
> @emilyjeanrogers - it seems like Aus is down the same path as Can with groups and markets.... - would shopping in multiple stores be something your users would want too?

Yes I think it's something we would want to look deeper into - not sure of the optimal approach, but with more farmers markets and hubs coming online, being able to shop in multiple stores will become increasingly relevant. So yes - would be good to see a wishlist item explored.

**Comment by luisramos0** [comment]
the revert PR has now been merged so this change will be reverted in the next release.

**Comment by luisramos0** [comment]
fyi, this was reverted in prod just now (v3.2.3) in all globally managed instances.
