### ISSUE TITLE
Stock levels not taking the expected effect on /cart page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5455]
## Description

The stock levels for different products set incorrect limits in the cart page. When increasing the amount of a product with existing stock, the  modal for insufficient stock is triggered once the stock of one of the items' amounts is exceeded. This happens with inventory set take the settings from the producer. See pics/example below.

## Expected Behavior

It should be possible to increase the amount of a given stock item, if the number of items does not exceed the settings in the backoffice.

## Actual Behaviour

The adjustment of the number of items in the cart page is incorrectly limited - apparently the stock levels from other products are considered.

## Steps to Reproduce

1. Set stock values for two different products A and B, for example 20 an 100 stock levels, respectively
2. As a customer and while in the shopfront, insert the 20 units of each on the cart. Proceed to cart.
3. In the /cart page, try to increase the amount of items for product B.
4. The modal will appear, stating the level of 20 cannot be exceeded, while in fact still 80 items are left

Please see pictures of this example below.

## Animated Gif/Screenshot

Right side - admin page, Left side - customer

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/9eab1ea0-6233-4d84-aad2-69e46f20d882)

Inventory is set to take the settings from the producer:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/6dc6ec23-6229-4aa1-8a5c-57f706ef8b64)

## Workaround

The workaround is not to use the /cart page to introduce changes to the cart.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: PR for release  2.9.9
* Browser name and version: Firefox 2.9.9
* Operating System and version (desktop or mobile): Desktop

**Comment by Matt-Yorkley** [comment]
I've just been looking at some related code in another PR. I think this might be related to the angular $scope on the directive...

**Comment by mkllnk** [comment]
@filipefurtad0, @Matt-Yorkley said that this issue is not new. Can you re-produce this problem in production? In that case we don't need to delay the release.

**Comment by filipefurtad0** [comment]
Hi @mkllnk ,

Yes, I'm catching up now and it seems not be introduced by the release - which is good news! Also, that there is a fix for this already... Awesome :+1: 

No need to delay the release from my side - thanks Maikel!
