### ISSUE TITLE
Spike - easy way to do address validation?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#546]

**Comment by daniellemoorhead** [comment]
Will need to consider this from an international perspective. Moving it to the core backlog, maybe someone in another location would like to pick this up.

**Comment by myriamboure** [comment]
Any idea @elf-pavlik or @blancnic ? I'm not sure I understand the problem... any precision @daniellemoorhead ?

**Comment by sstead** [comment]
It's important that enterprise addresses are valid, and can be successfully plotted on the OFN maps. We have found that when addresses aren't valid (such as a typo in the street name), other strange things can happen, such as https://github.com/openfoodfoundation/openfoodnetwork/issues/1173

Dani has suggested that we find an API which validated addresses at the point of enterprises entering their address. Some validators may work in just 1 country- in which case we need to give each instance the chance to install their own API. Or there may the opportunity to find a single, global validator.

**Comment by myriamboure** [comment]
As we still use the google map database, it seems there is that in Google maps, no? Lots of times, you start typing your address, and the suggestion in Google map appear, and you can only clic on it, so you have to enter an address which is recognize by google maps (autocomplete)

**Comment by daniellemoorhead** [comment]
@lin-d-hop this was the address validation issue I spoke about in the dev chat. Not sure if it's worthy of focus by Levent, but tis a candidate :)

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/discovery/1177
