### ISSUE TITLE
Facebook picks random (rather than relevant) snippet when shopfront or group link is posted

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#547]
is there any way we can get it to include information that relates to the enterprise or group that it is linking to?

![image](https://cloud.githubusercontent.com/assets/2911176/7528713/f2072964-f56f-11e4-8100-3c9fabbe501f.png)

**Comment by pmackay** [comment]
@kirstenalarsen any chance of using a label for the hackathon possible issues, rather than another milestone? :)

**Comment by kirstenalarsen** [comment]
i’m not too fussed if you’d rather - zenhub makes life easy for me to organise them all one way or the other :)

**Comment by pmackay** [comment]
How about a `hack idea` label then? Happy to tweak...

**Comment by pmackay** [comment]
Also for anyone who looks at this, might be worth doing at the same time as #551 - could be related.

**Comment by kirstenalarsen** [comment]
maybe check w. @elf-pavlik first as not sure if he’s done / doing some other organising?

welcome back btw - nice to see you pop up :)

**Comment by elf-pavlik** [comment]
links helpful for fixing it
* http://ogp.me/
* https://developers.facebook.com/tools/debug/

**Comment by pmackay** [comment]
@elf-pavlik have you been looking at any other way of organising content for the hackathon? Any thoughts on labelling to filter across the milestones?

**Comment by ludivinecp** [comment]
I'm working on it !

**Comment by elf-pavlik** [comment]
possibly more useful resources
* railscast https://youtu.be/Vg8-fHiLlds
* https://github.com/lassebunk/metamagic
* https://github.com/kpumuk/meta-tags#open-graph

**Comment by mkllnk** [comment]
There are two different things discussed here.

#### Posting shop link on Facebook

That is a problem at the moment. The current shop link goes to the shops list and has a hash selector that is evaluated by Javascript to display the shop's modal. While that's fine for normal browsers, Facebook does something wrong and shows the modal of another shop.

#### Providing a Facebook share button on OFN

With open graph, it is possible to put something on the timeline of the user (after receiving permission to do so). In that case the app puts all relevant information for Facebook into meta tags and we have more control over the display. But to make this work, we need a single resource for a shop, not a list of shops with a modal.

Having a single resource for each shop solves the problem already. The additional share button is therefore a feature on top of solving the problem described of this issue, I think.

Does this make sense?

**Comment by lin-d-hop** [comment]
Closing #gitcull
