### ISSUE TITLE
Import Validation Overview had incorrect column headers

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5470]
## Description

When importing product details using the Product Import features, a file was uploaded and the Import Validation Overview appeared. There were no errors. The Import Validation Overview table showed the data to be imported. All of the column names were incorrect (ie. the column that included Weight was labelled Producer, the column that included Producer was labelled SKU, the column that included Product Category was labelled Shipping Category)

## Expected Behavior
The column headings should line up with the correct column!

## Actual Behaviour
When uploading this data file:

![Screen Shot 2020-05-20 at 4 51 47 PM](https://user-images.githubusercontent.com/47620442/82414343-3d399580-9aba-11ea-87c3-a0bddc08d611.png)

The following Import Validation Overview was displayed

![Screen Shot 2020-05-20 at 4 52 44 PM](https://user-images.githubusercontent.com/47620442/82414415-5f331800-9aba-11ea-800a-f70d328b2bd5.png)

The product import was completed successfully.

## Steps to Reproduce
Unable to reproduce so far. 

Of possible relevance: 
- The product import was for 4 new products for an existing Producer who already had some products. 
- One of the new product variants was the same as one of the Producer's existing products however it was imported as a new variant, as some details didn't match

## Workaround
This does not impact the ability to import products. When validating the import, a customer would be confused when trying to confirm if the product import details are correct, however if they ignore the misaligned column names, the import goes ahead successfully.

## Severity
S4

## Your Environment

* Browser name and version: Chrome Version 81.0.4044.138
* Operating System and version OS X El Capitan desktop

**Comment by RachL** [comment]
@emilyjeanrogers as this is something we have not been able to reproduce I'm going to close it. We can reopen if it happens again. Best would be then to upload the file used to be able to reproduce it.
