### ISSUE TITLE
Incorrect Enterprise Fees Associated with Incoming Products

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5472]
## Description

Enterprise A (hub) is co-ordinating an OC.  
Enterprises B and C supply the OC.
On the 'Incoming Products' section, enterprise fees associated with both enterprises B and C can be added but **not** enterprise fees set by enterprise A.
Order cycle co-ordinators should be able to set their own fees to suppliers in order cycles.

## Expected Behavior

Enterprise A (hub) is co-ordinating an OC.  
Enterprises B and C supply the OC.
Under 'Incoming Products' of an OC Enterprise A can set enterprise fees to enterprise B or C.  They should be able to add Enterprise fees that belong to Enterprise A.

## Actual Behaviour

Enterprise A (hub) is co-ordinating an OC.  
Enterprises B and C supply the OC.
Under 'Incoming products' of an OC, enterprise A can only apply enterprise fees set up by enterprises B and C to their products. Enteprise fees that belong to Enterprise A are not visible.

## Steps to Reproduce

1. Create an OC : coordinator = OFN UK Demo Hub
2. Add two suppliers to the incoming products section 
3. Try to add one of OFN UK Demo Hub's enterprise fees to these two suppliers- not possible
4.

## Animated Gif/Screenshot

![ocerror1](https://user-images.githubusercontent.com/45104035/82437626-a0620280-9a8f-11ea-880c-fd4d1d2cbf78.jpg)

## Severity

No workaround.
S3
Please advise 

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [adding enterprise fee to OC for Good Food Exeter](https://trello.com/c/5SVleRks/1076-adding-enterprise-fee-to-oc-for-good-food-exeter)

**Comment by tschumilas** [comment]
The coordinator of an OC already has the ability to CREATE and SELECT any fees needed by THEIR OWN enterprise  in an OC.   Specifically: Enterprise A (coordinator) can add a fee **they've** created in the general settings tab of the OC,   AND  Enterprise A  can add fees **created by any supplying enterprises** on the incoming page of the OC.      Is this issue about which fees can be added by whom to an OC?  Or is this issue about who can create fees?  I'm seeking clarity.

Use Case:   Enterprise A coordinates an OC.  Enterprise B supplies them and several other re-sellers.   Enterprise A sets an enterprise fee (a markup) that applies to all products in the OC they coordinate to reflect their own costs.  Enterprise A can apply this fee in the General Settings for the OC.  It will apply to all incoming products from all suppliers for ANY distributor shop attached to that OC.  
In this same OC,  Supplier Enterprise B incurs a transportation cost to bring goods to the aggregation point.  Supplier Enterprise B knows their costs,  so they create a unique transport fee for each hub they supply.   Enterprise B selects the correct fee for each hub they supply in the incoming section of the appropriate order cycles. 
Isn't this what we want?  
This is what we have now:
An OC coordinator can create and add  fees -  that apply to ALL products.
An OC coordinator can uniquely specify the price of ANY product (using inventory) (in case some produts have higher costs to re-sell than others for example)
A supplier to an order cycle (that they don't coordinate) can **create** a fee and apply it to **their own** products.
An OC coordinator **can apply** a fee to a given supplier's products.  

What we DON"T have:   No enterprise can create a fee to be applied to another enterprises products.   At present each enterprise has sovereignty over fees applied to its own products.

Don't we want this?
@lbwright22  @kirstenalarsen - wondering if this has been discussed re: network feature?

**Comment by Matt-Yorkley** [comment]
Hey @openfoodfoundation/train-drivers-product-owners I'm wondering if this issue needs a bit more clarity / scoping before it can easily be picked up by devs?

**Comment by RachL** [comment]
Outch. Indeed. I'm even wondering if this isn't a feature request that would need a bit of inception. Can a distributor raise the prices of a specific producer without their consent? @lin-d-hop @lbwright22 it's been a while since this one was open. How do you see this?

**Comment by lin-d-hop** [comment]
I have updated the issue. I believe this was actually a regression at one point.
An enterprise needs to be able to set their own fees on an order cycle eg 'I collect this producer from supplier A and add a 5% fee for that service'.

I'm not sure about your questions @tschumilas. I became confused when reading your comment so not sure what to reply.

**Comment by lin-d-hop** [comment]
@lbwright22 it would be helpful if you would confirm. The screenshot doesn't seem to confirm the issue to my understanding so if I'm not correct please do let me know.

**Comment by tschumilas** [comment]
If I collect produce from supplier A and want to add a $2 fee for that service.   The fee is MY fee as the hub.   As a hub I can currently create this fee,   and apply it to supplier A's product.  Can I  not?      My point above was that we need to be clear on whose fee it is  -  in this example,  the hub is not creating a fee on behalf of supplier A.   The hub is creating their own fee and applying it to select products they sell.  But it is a hub enterprise fee,  not supplier A's fee.

**Comment by lin-d-hop** [comment]
Thanks for the clarity @tschumilas 
It is the hubs fee and applied only to Supplier A.
My understanding of this issue is that this ability for a hub to create a fee and apply to only one supplier within the OC was disabled, and that this was a regression.

**Comment by RachL** [comment]
@lin-d-hop @tschumilas hello lovely ladies. I was reproducing the issue with @jibees this morning and I noticed that currently the systems allows the coordinator to add fees from supplier A to supplier B. 

It's not the scope of the issue but I wonder if this is a behavior we want to keep. In which case is this interesting?

So here in the dropdown I don't understand why I can select both producers:

![image](https://user-images.githubusercontent.com/6525576/127293573-988d3969-b9a5-4727-964f-2834d190ea5b.png)

**Comment by kirstenalarsen** [comment]
Because Supplier A may be doing something for Supplier B that they are charging for i.e. collecting and transporting, packing etc

This is the designed / conceptualised reason for fees working like this. In practice I have no idea whether anyone uses it at all

**Comment by RachL** [comment]
@kirstenalarsen ok thanks and the coordinator knows about it? Because in my test scenario there are no permissions between suppliers A and B.
