### ISSUE TITLE
Refund via paypal as an enterprise user

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#548]
## Description
If I go to an order that has been paid for with Paypal and I edit it, and go to Payments. If I then click on the payment method, I get taken to a screen where it looks like I can do a refund of that paypal payment. But if I click on refund I get an 'unauthorised' banner. 

The experience is slightly different for superadmin users... they can click on 'refund' and then they can enter in an amount to refund, but when they click save, nothing happens- the order is still marked as paid and complete.

## Expected Behavior
I would expect to see either:
- "sorry you can't process refunds here, go to paypal to do a refund"
- Or the refund functionality should work

## Steps to Reproduce
1. Place an order in a shop with Paypal payment method
2. Edit that order and go to Payments
3. Click the payment method and then click refund
4. If you're a regular users you'll see 'unauthorised', if you're a superadmin user you can enter an amount to refund but nothing happens.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/10843056/44250124-88b07700-a236-11e8-9f22-7fa66235559b.png)

If I'm a superadmin user I don't get the unauthorised screen, instead I see this... 
![image](https://user-images.githubusercontent.com/10843056/44250148-99f98380-a236-11e8-8e31-b171fc5b47b2.png)

## Context
a user could encounter this if they were trying to refund a Paypal payment from OFN.

## Severity
s3

## Your Environment
PC, Chrome, Aus production, 1.18.0

**Comment by myriamboure** [comment]
This needs to be retested.

**Comment by sstead** [comment]
This bug still exists...
![image](https://user-images.githubusercontent.com/10843056/44249564-c2cc4980-a233-11e8-8927-753c79f7fc76.png)

**Comment by lin-d-hop** [comment]
Now refunds through Paypal give a clear message that Refunds are not possible with Paypal.

To add this would be a new feature so closing this bug.
