### ISSUE TITLE
Switching between shops does not work correctly

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5496]
## Description

Switching between different shops does not work as expected: while logged in and shopping in shop A, clicking Shops in the main menu and choosing shop B from the shop list will first display again the shopfront of shop A (were customer was initially)... The address bar shows the address of shop B. See gif below.

## Expected Behavior

Switching shops by clicking on the main menu should work, and lead you to the shopfront you clicked on.

## Actual Behaviour

Clicking on another shop first showed the shopfront of the previous shop.

## Steps to Reproduce

Not always observable if in guest mode - Only occurs if logged in.

1. Log in (admin, customer...)
2. Click /shops in main menu
3. Choose an open shop A
4. Click again in /shops in main menu 
5. Choose another shop (other than the one you are), shop B
6. You should observe shop A again, while the address bar clearly shows the address of shop B...

## Animated Gif/Screenshot

![switching_between_shops](https://user-images.githubusercontent.com/49817236/82736674-7759a000-9d23-11ea-96df-9a37b2e57964.gif)

## Workaround

Refreshing the page solves this.

## Severity

While it is not always observable (only while logged in) and it does have a workaround (refreshing page) this is quite a critical feature - switching shops... it's a release blocker - S2.

## Your Environment

* Version used: Release draft 2.9.10
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
I just confirmed this is caused by #5440
this commit: https://github.com/openfoodfoundation/openfoodnetwork/pull/5440/commits/a438317d69c5787a94b8f745b01dc8b8c19cf3a7

Refactoring legacy code...
Look at the code review chat for this commit:
![image](https://user-images.githubusercontent.com/1640378/82844146-520d9300-9ed7-11ea-9373-58c69f2e643e.png)

I can work on this tomorrow morning.
