### ISSUE TITLE
Still missing variant labels

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#550]
![image](https://cloud.githubusercontent.com/assets/10843056/7531077/90498fc8-f597-11e4-92c6-413f63b6e162.png) this is in editing an order

![image](https://cloud.githubusercontent.com/assets/10843056/7531081/932b9268-f597-11e4-852b-90ad86841ecb.png)

![image](https://cloud.githubusercontent.com/assets/10843056/7531082/95590ba6-f597-11e4-81dd-c8f564e58b7f.png)

**Comment by sstead** [comment]
![image](https://cloud.githubusercontent.com/assets/10843056/7531151/b45b5774-f598-11e4-89a6-2c1eb18a9485.png)

**Comment by kirstenalarsen** [comment]
we think is kinda related to #673 which @oeoeaio is working on now, so if is easy to knock this off at the same time will do so
