### ISSUE TITLE
Missing translation key - Closed OC info

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5507]
## Description

The info appearing for closed OCs is missing from the translation key file en.yml:
"The order cycle you've selected has just closed. Please try again!"

## Steps to Reproduce

1. Customer - add items to the cart, and proceed to checkout
2. Admin - Close the OC from which the customer has the items from
3. Customer - While on checkout, click Shops/Boutiques (below):

![image](https://user-images.githubusercontent.com/49817236/82736031-635f6f80-9d1e-11ea-975e-0f0db11f8865.png)

**Comment by luchiago** [comment]
I would like to tackle this issue.

**Comment by luchiago** [comment]
hey @filipefurtad0, as admin I'm not able to close an OC while some customer has products on cart.

**Comment by filipefurtad0** [comment]
Hey @luchiago ,

What the exact difficulty you are encountering?

Deleting the OC should not be possible - indeed, the trash symbol disappears after there is an order. However, changing the date in Close into a past day should close the OC.

Hope this helps?

**Comment by luchiago** [comment]
Yeah, it helps, that is exactly what I was looking for. Thanks
