### ISSUE TITLE
Increasing the quantity of items in a shipped order is possible via BOM (triggers Bugsnag)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5509]
## Description

It's possible to increase the quantity beyond the Max. value under Bulk Order Management, for shipped orders - generating the error message "Fields with red borders contain errors." and triggering Bugsnag:

https://app.bugsnag.com/katuma/katuma/errors/5ecd23ca0573c100186ae8c8?event_id=5ecd23ca005b8d91543d0000&i=sk&m=nw

Unhandled error
NoMethodError: undefined method `stock_location' for nil:NilClass
Location
app/models/spree/line_item_decorator.rb:162 - update_inventory_with_scoping

It's also possible to decrease the quantity.

## Expected Behavior

While it should be possible to change the quantity of a paid order, that shouldn't necessarily be the case for a shipped order. Currently, this is the behaviour when editing under /orders/<order_number>/edit# - possible to edit after payment, but not after shipping.

An enhancement would be to have something like "Finalise Order" function, which would process refunds and makes the order uneditable. See also conversation in Slack:
https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1590506669497100?thread_ts=1590506147.497000&cid=CDLKH9MM0

## Actual Behaviour

Not only it is possible to change the quantities (generating errors) as it's possible to do so over the Max. value.
## Steps to Reproduce

1. Place an order, with valid payment and ship the order
2. Go to BOM and try to increase the quantity of an item in that order, beyond the Max. limit
3. Click Save Changes
4. Observe the error "Fields with red borders contain errors."

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e7d79cd3-a1a4-4e89-a7ad-abe390aba0d9)

![BOM_Peek 2020-05-26 15-15.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/598677d3-2782-4750-a36d-d6b886fa23b6)

## Workaround

Adding a New Return Authorization, to decrease the quantity of a shipped order would be a workaround.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v2.9.9
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Desktop

**Comment by filipefurtad0** [comment]
This also happens for Shipped & Returned Orders:

![Peek 2021-06-02 15-51](https://user-images.githubusercontent.com/49817236/120502764-9c630300-c3ba-11eb-8075-5927a154d52f.gif)

**Comment by Matt-Yorkley** [comment]
Outdated; we're removing he ability to edit shipped orders in BOM.
