### ISSUE TITLE
OFN logo doesn't appear when we share www.openfoodnetwork.no on social media

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#551]
![no-logo](https://cloud.githubusercontent.com/assets/8135376/7536983/4fc6e498-f595-11e4-878f-fb338f2570a9.jpg)

**Comment by myriamboure** [comment]
I'm just starting to report the issues I observe when they happen (and while we are going to start testing) without prioritizing, so this one for example is not at all a priority, just reporting it so that we don't forget it :-)

**Comment by elf-pavlik** [comment]
@myriamboure can we close this one in favor of #547 ? We have already put it in on a milestone for Berlin hackweek!

**Comment by myriamboure** [comment]
Sure @elf-pavlik, I close it now :-)
