### ISSUE TITLE
Shoppers that have already clicked Terms and Conditions can checkout without re-accepting

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5514]
## Description

As a shopper I only need to accept the Terms and Conditions on the first checkout from a shop. On every future checkout I just need to a link to them - the Terms and Conditions can be accepted by default.

## Acceptance Criteria & Tests

As a Shopper:
- The first time I checkout from a shop I need to accept the Terms and Conditions.
- The second time I checkout, if the Ts&Cs are the same then they are accepted by default
- If the Ts&Cs are changed then I must accept them again.

1. Add Ts&Cs to an Enterprise
2. Login and Checkout from their shopfront. You will have to accept the Ts&Cs to checkout
3. Create a new basket and checkout from this shopfront. The Ts&Cs should be accepted by default. This should also be true on a different order cycle for this Enterprise.
4. Now upload new Ts&Cs for this Enterprise in Enterprise Settings -> Business Details
5. Go back to the Checkout. You will now need to accept the Ts&Cs in order to checkout.

**Comment by RachL** [comment]
@luisramos0 @lin-d-hop I've just noticed that https://github.com/openfoodfoundation/openfoodnetwork/issues/5512 shows a sentence to the shopper without a checkbox. On Discourse we spoke about this checkbox too: was it removed for design purposes? 

As we are in the process or revising our Terms and conditions in FR I will ask our lawyer if we are allow to do that. Myriam and I had in mind that the action to check something was mandatory to save consent. But maybe we are wrong.

**Comment by luisramos0** [comment]
no no, the checkbox is just not in the first step, it's the 2nd step here: https://github.com/openfoodfoundation/openfoodnetwork/pull/5994

**Comment by RachL** [comment]
thanks @luisramos0 sorry about that 🙈 . I think the translation fooled me. I will comment on the issue!
