### ISSUE TITLE
Enterprise can easily update and view Terms and Conditions

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5515]
## Description

As a Hub I'll need to be informed that when I change the Terms and Conditions my users will need to reaccept them. I'll also need to know the date that I last updated the Terms and Conditions and be able to view the Terms and Conditions from the back office. All of this can be explained in a tool tip. EDIT: Not a tool tip, a modal!

![Screenshot from 2020-05-27 16-26-23](https://user-images.githubusercontent.com/8669848/83040270-fce89300-a036-11ea-9102-27db63e1a8ed.png)

## Acceptance Criteria & Tests

- In Enterprise Settings -> Business Details once I have uploaded Terms and Conditions I can see a link to my existing terms and conditions. If I click this link I should be able to see my Terms and Conditions in a new tab.
- Once I have uploaded my Ts&Cs I can see the date and time of the last upload.
- When I go to replace my existing Ts&Cs I will see an error message that reads as per the image above.

1. Go to Enterprise Settings -> Business Details and upload Ts&Cs
2. Now see a link to the uploaded Ts&Cs. This link text can be a truncated filename. This link should open in a new tab.
3. The date time for when the link was uploaded should be visible.
4. Now upload another document.
5. See the notification message (as per image above). Click Continue.
6. The link text will have changed to the new filename and the link will open the new file.
7. The datetime will reflect the new upload time.

**Comment by luisramos0** [comment]
What needs to be done here:
- [ ] In the backoffice, the T&Cs link should open in a new tab.
- [ ] In the backoffice, the date time for when the link was uploaded should be visible.
- [ ] When I go to replace my existing Ts&Cs I will see an error message that reads as per the image above.

@lin-d-hop re modals and tooltips:

in my head tooltips are the text that appears when you mouse over a label or link. That's what's requested in https://github.com/openfoodfoundation/openfoodnetwork/issues/5516 is this assumption correct?
I wonder if we should do something like tag rules:
![image](https://user-images.githubusercontent.com/1640378/94442310-b600da80-019b-11eb-85e1-6261ed999f85.png)

that shows:
![image](https://user-images.githubusercontent.com/1640378/94442336-bef1ac00-019b-11eb-8d29-a7ec71bc1ba4.png)





In this issue we are talking about a small modal with buttons, right?
Is there an existing modal in the app I should base the design?
Shall I use something like the modal for customer addresses?
![image](https://user-images.githubusercontent.com/1640378/94442155-8a7df000-019b-11eb-87d1-50e92bae09cb.png)

Also, the request is only for re-upload of T&Cs. On the first upload there is no message displayed to the user, correct?
I wonder if in case of the first upload we should also show a slightly different/simpler message like "all users will have to accept this on checkout...."

**Comment by lin-d-hop** [comment]
Hi Luis,
This all sounds great.

Yes to a modal - using the same design as tag rules. Perfect.

Regarding adding a modal when a user adds the Ts&Cs the first time - Yeah, I think this is a good idea. Good thinking.
