### ISSUE TITLE
Add a Tooltip to explain Terms and Conditions to Enterprises

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5516]
## Description

As a Hub I want to a tooltip to explain the Terms and Conditions option in Enterprise Settings -> Business Details.

The default text can read:
_Terms and Conditions are the contract between you, the seller and the shopper. If you upload a file here shoppers must accept your Terms and Conditions in order to complete checkout. For the shopper this will appear as a checkbox at checkout that must be checked in order to proceed with checkout. We highly recommend you upload Terms and Conditions in alignment with national legislation.

Shoppers will only be required to accept Terms and Conditions once. However if you change you Terms and Conditions shoppers will again be required to accept them before they can checkout._

### Acceptance

- In Enterprise Settings -> Business Details -> Terms and Conditions there is a tooltip that displays the text to explain to the Enterprise manager
- Translation keys are used

### Testing
1. See Terms and Conditions tooltip and appropriate text in Enterprise Settings -> Business Details 
2. Check in another language

**Comment by jroes** [comment]
Hi @lin-d-hop! I'm not seeing a Terms and Conditions option on the Business Details screen with the latest code in master, running via Docker.

Here's what I'm seeing:

<img width="963" alt="Screen Shot 2020-07-22 at 2 51 30 PM" src="https://user-images.githubusercontent.com/27847/88216481-27b42980-cc2b-11ea-83bb-62b28daf04e0.png">

Is it possible I'm looking in the wrong spot?

**Comment by RachL** [comment]
Hi @jroes and welcome here !

This issue cannot be done before https://github.com/openfoodfoundation/openfoodnetwork/issues/5512 that will add the terms and condition option.

If you are looking for independent issue, have a look at our `good-first-issues` or this board: https://github.com/openfoodfoundation/openfoodnetwork/projects/27

Don't hesitate if you have questions :)

**Comment by luisramos0** [comment]
Hi @jroes #5512 is now done in branch tcs so you can pick this issue now.
You just have to use branch tcs instead of master :+1:
