### ISSUE TITLE
Hubs can require Shoppers to accept their Terms and Conditions

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5517]
## What is the problem we are solving 

When shoppers place an order from an enterprise they are entering a legally binding contract with the enterprise under law in pretty much every country on the planet.

Hubs need to be able to specify the Terms and Conditions of this contract.

Shoppers need to demonstrate that they accept this legally binding contract.

This feature epic enables:
- Hubs to be able to upload a set of Terms and Conditions
- Shoppers to be able to view and accept Terms and Conditions at checkout
- Shoppers to only have to accept once. On future checkouts their acceptance is recorded as default.
- Hubs can change their Terms and Conditions
- On doing so Shoppers will again be asked to accept the new Terms and Conditions at checkout

## Success factors = expected outcome 

1. Hubs can upload Terms and Conditions
2. Shoppers must accept Terms and Conditions to checkout
3. Shoppers clicks are minimised - returning shoppers encounter no additional clicks after they have accepted Ts&Cs
4. Hubs can update Terms and Conditions forcing shoppers to accept the new Ts&Cs

## Link to the "Product Development - Backlog" item in Discourse

[Discourse Link](https://community.openfoodnetwork.org/t/hubs-can-ask-their-customers-to-validate-their-own-terms-and-conditions/1265)

Tech Lead: @sauloperez 
Product Lead: @lin-d-hop

**Comment by luisramos0** [comment]
This is all now in Code Review. As usual we leave the Epic in Dev Ready until all issues are merged and we think the job is done :+1:

**Comment by luisramos0** [comment]
@lin-d-hop I think this is ready to be closed now.

**Comment by lin-d-hop** [comment]
How very exciting!

Great work everyone!
