### ISSUE TITLE
Product images displaying in different places according to which variant they're assigned to

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#552]
This is a very minor issue, but I spent the time figuring out how images display according to which variant they're assigned to, so thought I'd capture this...

This issue: essentially, there's the potential for someone to add images to their variants and then get confused when no image displays in their shopfront... this is because no image has been assigned to 'all' variants.
- So the solution is either 1) if no image has been assigned to 'all' variants, BUT images have been assigned to 1 or more variants, one of these images should be pulled and displayed in the shopfront. Or 2) you could make it so that you must add an 'all' variant image, before you can add images to individual variants. or 3) just disable people being able to add individual variant images (they only show in the order summer page/ order conf. anyway as tiny thumbnails.

Here's how the system currently works...

When you add an image and assign it to 'all' variants, it will show in the shopfront, and also beside any variants in the edit your cart page (if they don't have unique images assigned to them).

![image](https://cloud.githubusercontent.com/assets/10843056/7547167/2ff272f4-f62b-11e4-9717-3fab4473ed45.png)

![image](https://cloud.githubusercontent.com/assets/10843056/7547164/2a246f1c-f62b-11e4-980e-a79ba208c92a.png)

If you THEN add images and assign them to individual variants, the "all" image will show in the shopfront, and the variant assigned image will show in the edit your cart

![image](https://cloud.githubusercontent.com/assets/10843056/7547163/242d5bdc-f62b-11e4-950d-9c1357d69cfe.png)

If you have added images to individual variants, but not to 'all' variants, then no image will show in the shopfront, only in the edit your cart.
If you have added an image to 'all' variants, but not to individual variants, the 'all' image will show in the shopfront and in the order summary.

**Comment by Matt-Yorkley** [comment]
@sstead So what's the desired behaviour for this? If a product image is missing then the first image from a product's variants should be shown in it's place?

**Comment by sstead** [comment]
Hey Matt, I think the explanation below covers the desired behaviour... it would prevent someone from adding variant images, and still not seeing an image in the shopfront...

"So the solution is either 1) if no image has been assigned to 'all' variants, BUT images have been assigned to 1 or more variants, one of these images should be pulled and displayed in the shopfront. Or 2) you could make it so that you must add an 'all' variant image, before you can add images to individual variants. or 3) just disable people being able to add individual variant images (they only show in the order summer page/ order conf. anyway as tiny thumbnails."

**Comment by myriamboure** [comment]
I would vote for either 2 or 3. Iceboxing it anyway here https://community.openfoodnetwork.org/t/improve-product-images-display-in-shop/1162 so closing for now will reopen when we decide to prioritize.
