### ISSUE TITLE
Admin configs don't always update when saved

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5522]
This problem has been around for a long time, but we just got another question in slack about why updating site logos in superadmin was not updating on the site.

We have various different configs that can be set as superadmin, but a lot of them require a unicorn restart. It's not clear to the user which ones will work and which ones won't. It also means the server can be left in a limbo state, where a config has changed but won't be applied until next deploy, which can cause havok.

### Possible solution

I think a lot of these configs are related to `Spree::Preferences` not updating correctly, as they are cached. We can possibly just call `Spree::Preferences::Store.instance.clear_cache` inside a callback somewhere when saving config changes...

**Comment by luisramos0** [comment]
nice, I dont think this is tech debt. This is a bug. I'd say bug S4.
