### ISSUE TITLE
[Spree 2.1] Stripe (Connect and SCA) payments not working in the backoffice

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5525]
## Description

Payments with Stripe are not working if the order is placed in the backoffice, for both Stripe SCA and Stripe Connect, with the simplest test card 4242424242424242.

These payment methods have been tested in the shopfront and work fine, only known issue so far is #5447.

## Expected Behavior

Payments in the BO should work for both Stripe-Connect and Stripe-SCA, with cards which do not require authentication.

## Actual Behaviour

The "Error Saving Payment" message is shown (below).

## Steps to Reproduce

1. Create a new order for a given customer. Make sure this customer/user allows charges on a credit card or add one, under the user's account, /account -> Credit Cards. Place a Check under Authorised Shops, for the respective shop.
2. Fill the necessary details, and proceed to Payment Methods
3. Select a Stripe payment method and add the respective credit card data, allowed by the user.
4. Press Update -> The error messages (below) should be displayed.

## Animated Gif/Screenshot

Stripe Connect:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/649eac11-3787-4957-a0a6-e7624af85523)

Stripe SCA:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/4ec1a912-b6a4-4ed2-bc98-e51e67e742d7)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 3-0-stable
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Ubuntu 18.04, Desktop

## Possible Fix

Related issues:
Stripe SCA Payments fail in the backoffice #5212
[StripeSCA] Fix card payments in the Backoffice #5233

**Comment by luisramos0** [comment]
It was totally broken in the upgrade branch, the attributes of the card were not permitted (something that needs to be done explicitly in rails 4). Done in #5597

**Comment by filipefurtad0** [comment]
Hi @luisramos0 ,

Tested the outcome of different cards for both stripe methods, when placing orders in the backoffice, checking whether:

i) confirmation email
ii) order amounts and
iii) entries in Stripe dashboard

match. This was done for cards where success is expected:

a) Visa 4242424242424242
b) international card 4000002460000001

And when failure is expected:

c) 3D Secure 4000002760003184 (only for Stripe SCA)
d) card_declined code - 4000000000000002
e) incorrect_cvc code - 4000000000000127

Summarizing:
- when card types a) and b) are used in the backoffice i) ii) and iii) always match - all good.
- card type c) fails as expected (only for Stripe SCA)
- failing card types d) and e) lead to the expected result with Stripe SCA payment method; with Stripe-Connect it breaks the payment page (this is known - https://github.com/openfoodfoundation/openfoodnetwork/pull/5233#issuecomment-619935320)

Ready to go :tada:
