### ISSUE TITLE
[Spree 2.1] Broken spec - EnterprisesController missing routes

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5533]
Errors:

```
  1) EnterprisesController as an enterprise owner creating an enterprise creates as sells=any when it is not a producer
     Failure/Error: spree_post :create, { enterprise: new_enterprise_params }
     
     AbstractController::ActionNotFound:
       The action 'create' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:33:in `block (4 levels) in <module:Api>'

  2) EnterprisesController as an enterprise owner creating an enterprise saves all user ids submitted
     Failure/Error:
       spree_post :create, {
         enterprise: new_enterprise_params.
           merge({ user_ids: [enterprise_owner.id, manager1.id, manager2.id] })
       }
     
     AbstractController::ActionNotFound:
       The action 'create' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:43:in `block (4 levels) in <module:Api>'

  3) EnterprisesController as an enterprise manager submitting a valid image I can update enterprise image
     Failure/Error: spree_post :update_image, logo: 'a logo', id: enterprise.id
     
     AbstractController::ActionNotFound:
       The action 'update_image' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:71:in `block (4 levels) in <module:Api>'

  4) EnterprisesController as an non-managing user submitting a valid image I can't update enterprise image
     Failure/Error: spree_post :update_image, logo: 'a logo', id: enterprise.id
     
     AbstractController::ActionNotFound:
       The action 'update_image' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:90:in `block (4 levels) in <module:Api>'
```

**Comment by Matt-Yorkley** [comment]
I think this is caused by this Devise user mappings issue: https://stackoverflow.com/a/4321055

**Comment by luisramos0** [comment]
This could be some mess up between spree routes and Ofn routes. shop and enterprise controllers are both ofn only routes, maybe devise (or the test) is only using/loading/seeing spree routes.

**Comment by luisramos0** [comment]
I tried playing with api_post instead of spree_post
I see that removing use_route: :spree from ControllerHacks#api_process
I get this one to fail with similar problems as this issue:
spec/controllers/api/variants_controller_spec.rb:72:
I still think this is related to routes and namespaces, api or spree...

Anyway, no luck yet.

**Comment by luisramos0** [comment]
After quite some hours trying to fix this I finally read the error message again:
The action 'create' could not be found for EnterprisesController
it doesn't say
The action 'create' could not be found for Api::EnterprisesController
:-)
It's looking at the wrong controller!
I think we can just set use_route: :api
I will try that now.

**Comment by luisramos0** [comment]
It's the most weird rspec thing, this is the only way rspec gets to select the correct Api::EnterprisesController, not ::EnterprisesController :man_shrugging: 
![image](https://user-images.githubusercontent.com/1640378/83554378-8f3fd980-a504-11ea-9e09-eb7f97373c70.png)
