### ISSUE TITLE
Tags on variants are not hiding/showing variants accordings to the rules set

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5534]
## Description
From https://github.com/openfoodfoundation/openfoodnetwork/issues/5529 I have erased all tag rules and started over.

Main story: the hub is selling its product with 3 prices (`part` = individual customers,  `grpm`= groups of customers, `pro` = professional customers).

Variants tagged `pro` are the cheapest and therefore should be available for professionals only. 

**Tag rule number 1 : make variants with `pro` tag invisible by default.**
I saved : shopfront with incognito mode is showing all 3 prices, yet pro tag should be invisible for anyone, no?

**Tag rule number 2 : Customers tagged  `grpm`**
I have added that customer tagged  `grpm` cannot see variants tagged `part` . All good, no impact on the shopfront when you are not loggedin. But this is expected here as it is not a default rule.

**Tag rule number 3: Customers tagged `pro`**
I have made `pro` customers allowed to see variants with tag `pro`. Saved all good and shopfront with incognito users are not being impacted. But this is expected here as it is not a default rule.

But then I have added 2 others rules for `pro` customers :
1. They are not able to see `grpm`variants
2. They are not able to see `part`variants

When adding both these rules, shopfront in incognito mode started to hide these variants as well...

## Steps to Reproduce

See above

## Animated Gif/Screenshot

What the shopfront must looklike when you are not logged in:

![image](https://user-images.githubusercontent.com/6525576/83331257-4504f100-a295-11ea-8547-cd74e73bc33e.png)

## Severity

bug-s3: a feature is broken but there is a workaround

The workaround is to create separate shops.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by filipefurtad0** [comment]
Hi @RachL ,

I tried to reproduce the findings above in v3 and v2.1 and found no difference between these. Please see the test-notes for all cases/settings here:
https://docs.google.com/document/d/1nOIzoMN6tu0-2YKpEPNb0QtseqXy3yCsMjBPKkKghUI/edit


In summary, I could not reproduce these two observations:

> I saved : shopfront with incognito mode is showing all 3 prices, yet pro tag should be invisible for anyone, no?
- I verified that the default rule applies also to guest customers (`pro` variant is hidden in guest mode)

> When adding both these rules, shopfront in incognito mode started to hide these variants as well...
- hiding `grpm` and `part` variants for the pro customer did not make these invisible to the guest/incognito customer.

It seems possible to fulfil the use-case. Perhaps we could compare settings? Am I missing any details?

**Comment by RachL** [comment]
@filipefurtad0 thank you!

I've requested access to your doc, you should have received an email :)

**Comment by filipefurtad0** [comment]
Oops, I forgot to move it to our folder after editing - it should be visible to everyone now. Thanks @RachL!

**Comment by filipefurtad0** [comment]
Hi @RachL ,

Thanks for granting me access to a production Demo Hub!

I went through the steps you described in this issue. Same as in the document above, I've set two different registered customers (Pro, and Reg) and checked the behaviour for guest customers as well (pics below, Pro, Reg, Guest).

- Tag rule 1 - hide PRO variant from everyone

![tag_1](https://user-images.githubusercontent.com/49817236/87030011-ea867b00-c1d8-11ea-8358-bb7985161b97.png)


- Tag rule 2 - hide PART variant from Reg-user

![tag_2](https://user-images.githubusercontent.com/49817236/87030014-eb1f1180-c1d8-11ea-8581-68313224faca.png)


- Tag rules 3:
i) show PRO variant to Pro-users
ii) hide PART/GRPM variants from Pro-users
iii) keep PART/GRPM variants visible to guest users

![tag_3](https://user-images.githubusercontent.com/49817236/87030015-ebb7a800-c1d8-11ea-812e-c48d696ee39f.png)


These are the final settings used to achieve this:

![image](https://user-images.githubusercontent.com/49817236/87029821-94b1d300-c1d8-11ea-84d6-b40ddf53558a.png)

![image](https://user-images.githubusercontent.com/49817236/87029854-a3988580-c1d8-11ea-9b1a-6b4f819a9a6e.png)

Default:
![image](https://user-images.githubusercontent.com/49817236/87029932-c165ea80-c1d8-11ea-8444-27af26d653d9.png)

Customer rules:
![image](https://user-images.githubusercontent.com/49817236/87029976-d5a9e780-c1d8-11ea-979d-3cb280ba1653.png)


I don't think order matters, but it helped me to do this subsequently, from:
i) creating tag rules
ii) setting them to the variants in the inventory
iii) setting them to the respective customers


This seems to work fine throughout production servers, in addition to staging-v3, and v2.1.

**Comment by RachL** [comment]
Closing, seems to work for everyone else :)
