### ISSUE TITLE
Deleting the last item from the confirmed order is allowed in /cart page (no warning) and easily leads to error 500

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5546]
## Description

While in the /cart page and placing orders in shops which have the option to edit confirmed orders for the same OC, the customer can remove all items from previously confirmed orders. This leads to an empty order and generates error 500 when attempting to viewing these (bug #5505).

This issue was first reported here https://github.com/openfoodfoundation/openfoodnetwork/pull/5480#discussion_r433421881

## Expected Behavior

While editing the cart, removing the last item from a previously confirmed order should not be allowed, and warning should be shown to the customer stating so.

This already happens if the order is viewed/edited in the /account#/orders/ page:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/0a8f6456-d6d9-4907-820b-aa3ca0a79b53)

## Actual Behaviour

In the /cart page the user can remove all items from a previously confirmed order. Attempting to view this empty order will generate error 500 (bug #5505).

## Steps to Reproduce

Admin:
1. Go to shop preferences an choose "Customers can change / cancel orders while order cycle is openallow shops to Go to a shop which allows" 

Customer:
2. Visit shop and place an order. Make sure you get the order confirmation.
3. Visit the shopfront again and, for the same OC, place an item in the cart, proceeding to /cart page
4. While in cart page, the previous order should be visible (pic below).
5. Now remove all items from the previously placed order.
6. Press Edit confirmed items.
7. Boom.

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/8b3b4dce-44ce-469d-95a6-0c447b25d3c1)

## Workaround

Cancelling the previously confirmed order.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 2.9.10 and 2.9.11
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Ubuntu 18.04 Desktop

## Possible Fix

Related with issue bug #5505.
Perhaps also related with issues #5253 and #5350.

**Comment by mprieger** [comment]
Hello! I'm a new developer and was interested in picking this up.

I was able to look into it a bit and identified the issue but wanted to clarify my approach.

From my understanding, the error handling for deleting an item from a confirmed order on the /orders page occurs server-side, in the Spree/Order controller. 

Conversely, there is no error handling for this action on the /cart page (hence this issue), but it acts a little differently. On deleting an item, a Darkswarm controller (EditBoughtOrder) function sends a delete request to the LineItem controller which removes the item server-side.

Is there a preference for handling this error on the frontend (EditBoughtOrder controller) vs. the backend (LineItem controller)?

**Comment by filipefurtad0** [comment]
This issue was partially addressed by #6528 and its severity downgraded.

The scenario in which we can still remove the last item (while on the cart page) is when there are more than one orders placed, for the current order cycle. In that case, the last item is still possible to remove:

![Peek 2021-03-04 11-33](https://user-images.githubusercontent.com/49817236/109959877-fd0d7180-7cdf-11eb-96e0-d122ff0b2d82.gif)

**Comment by guidoDutra** [comment]
Hello, I'd like to pick up this issue, could someone assign it to me? @sigmundpetersen
