### ISSUE TITLE
The reset password option still refers to www.openfoodnetwork.org.no and doesn't work

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#555]
See here the screenshot: https://drive.google.com/open?id=0B_HDFsX1e_2VeTkyS0VQUmpheHM&authuser=0

The domain for Norway is www.openfoodnetwork.no, but there has been some misunderstanding at the begining and it seems that the .org.no is still somewhere in the back office...

**Comment by rafaqz** [comment]
That was a typo :) one minute fix.

**Comment by pmackay** [comment]
@rafaqz what's the setting that defines where that URL is read from? Its an issue for #491 as well, which I need to look at....

**Comment by rafaqz** [comment]
I think those are different issues, this was just the admin no reply email
address that displays as the sender, and is set in the spree mailer setup.
But the password reset worked fine for me, but maybe it's not for others,
I'm not sure.

**Comment by myriamboure** [comment]
Thanks a lot, works fine!
