### ISSUE TITLE
Order Cycle Management Report Page doesn't load for superadmin

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5551]
## Description
When accessing the Reporting tab as a logged in Superadmin, the Order Cycle Management Report link fails to load the page. The Payment Method Report and Delivery Report links also fail.

## Expected Behavior
Reports Page for Order Cycle Management Reports should load

## Actual Behaviour
Snail when clicking link to open Order Cycle Management Reports, Payment Methods Report and Delivery Report

## Steps to Reproduce

1. Log in as Superadmin
2. Go to Reports
3. Click Order Cycle Management, Delivery Report or Payment Methods Report link
4. Snail

## Workaround
To investigate an issue or run a report for a particular enterprise it is possible to add yourself as a manager for that Enterprise,  then log in as that manager to run these reports.

## Severity
S5?

## Your Environment

Aus Instance, Chrome, desktop

**Comment by mkllnk** [comment]
https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5ece496e8be69a0017dd54aa

![Screenshot from 2020-06-03 15-03-50](https://user-images.githubusercontent.com/3524483/83597790-78a08d80-a5ab-11ea-85bf-ca961fad050c.png)

**Comment by emilyjeanrogers** [comment]
@mkllnk would the above bug be triggered even if a report wasn't specified? This scenario occurred just by clicking on the link to open the Order Cycle Management Report page. 

If there's a payment method missing, does that imply that a database check is happening before specifying which report to run?  

On Slack, @Matt-Yorkley said "I think there's some code that pulls orders the user has permission to edit when building some of the filtering options displayed in the form"

**Comment by lin-d-hop** [comment]
@emilyjeanrogers Yes this bug occurs before the page loads at all. There is a payment method missing from an order due to a data inconsistency created somewhere else in the platform that we have yet to track down.

**Comment by emilyjeanrogers** [comment]
It looks to me like this is no longer happening - I was able to successfully run Order Cycle Management Reports today while logged in as Superadmin. Not sure if/how it was fixed.. but will close this issue!
