### ISSUE TITLE
500 Error on Enterprise Fee Report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5553]
## Description

I'm not able to render the Enterprise Fee report at all.
I get a 500 error.
I even tried as a user with no orders to their name and 500 error.

## Expected Behavior

The Enterprise Fee report loads successfully

## Actual Behaviour

500 Error 

## Steps to Reproduce

1. Log in as any user (any tested so far)
2. Reports -> Enterprise Fee Summary
3. SLUG

## Workaround

None found

## Severity

Impacts all instances (at least FR and UK, so probably all)
S2

## Your Environment

* Version used: 2.9.11
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu Desktop

**Comment by lin-d-hop** [comment]
Reproduced in FR with this nice bugsnag:
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1591189396304800

**Comment by tschumilas** [comment]
Getting the slug on OFN Canada too when I try to access this.

**Comment by Matt-Yorkley** [comment]
Should be fixed now...

**Comment by RachL** [comment]
@Matt-Yorkley can you detail you fixed this without releasing something? In the meantime I'm closing this as it is working again :)

**Comment by luisramos0** [comment]
@Matt-Yorkley can you explain the solution?
I saw you deleted your comment in #5465
