### ISSUE TITLE
Missing translation key 'shipping_category'

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5558]
## Description

On "+New Product" section

![image](https://user-images.githubusercontent.com/928628/83769446-87a93d80-a688-11ea-8ca7-734584b1b129.png)

## Steps to Reproduce

1. Products
2. +New Product
3. 
4.

## Your Environment

* Version used: 2.9.10
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
hey @romale thanks for spotting this one!! Do you mind adding the steps to get to the product page in your description? Translation issues are often pick-up by new developers in the community. They often don't know the software at all. The more we can describe things, the bigger the chance someone will pick it up!

**Comment by romale** [comment]
Hi @RachL . Sure. Added
