### ISSUE TITLE
Change wording for organisation ID and VAT

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#556]
The wording is not adapted to Norway. We need just one field for "Orgnr" + "Charges MVA?" with yes and no buttons.
The VAT number is the organization number + MVA at the end. It's a number have to be in some documents. Should we have another box then if the answer to "Charges MVA" is yes, then ask the VAT  number? (which will be the org number + VAT) or can we generate it automatically if needed to avoid asking that to the user?

![orgnumber_vat](https://cloud.githubusercontent.com/assets/8135376/7569097/e90d7306-f806-11e4-84ae-8f704020b5da.jpg)

**Comment by myriamboure** [comment]
This will work for Norway, but if we want one instance for Scandinavia, we need to check how the ID for companies and the VAT works there. But let's be agile and see when someone from there want to use OFN!

**Comment by pmackay** [comment]
Might be worth reviewing recent VAT changes for UK too.

**Comment by elf-pavlik** [comment]
We could take a look at it during hackweek in Berlin. @myriamboure please feel free to move it to related milestone!

**Comment by myriamboure** [comment]
@elf-pavlik I'm not sure this is still a valid issue as I think it was just a translation issue that we fixed in Transifex... For Scandinavia even if we have different languages and just one instance, we can for each language use the good term for organization number and VAT, we'll see when the case happens if we need more than that. Just waiting for confirmation from @sigmundpetersen and Cynthia.

**Comment by sigmundpetersen** [comment]
I guess this is fixed yes with translation of the locale files. I think in the case we go for one Scandinavian instance we should have implemented language choice for the user in the front and back end.

**Comment by myriamboure** [comment]
Ok, I close the issue then.
