### ISSUE TITLE
Release v2.10.0 Shiitake

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5560]
Steps: 

- [x] Include translations
- [x] Release draft https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-51c2c1f91401636e8381
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1469
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by lin-d-hop** [comment]
Nothing out of the ordinary here :-)

https://docs.google.com/document/d/1Y6bJtTri4i2i_NRQ1WfrWavRBaxoaP_Uyg0RRf0v2NU/edit#

Good to go
