### ISSUE TITLE
[BO Orders] Orders with one line item not including enterprise fees

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5567]
## Description

EDIT: Applies only for orders with one line item.

When placing orders in the backoffice, prices per item do not include the enterprise fees set for the respective order cycle. This can lead to significant discrepancies between values obtained when orders are placed in the shopfront or in the backoffice (see pics below).

Update: this happens if one does not press the Update And Recalculate Fees button (bottom), but rather clicks into Customer Details, due to the displaying of the message "Cannot set shipping method until customer details are provided" just below the item list.

## Expected Behavior

It would be expected to automatically recalculate and update fees, when navigating to Customer Details, without having to press the button. This would make fees to take effect in both in the front- as well as in the backoffice.

## Actual Behaviour

If the user does not press Update And Recalculate Fees button (edit:) **or does not add further line items**, and clicks directly into Customer Details no enterprise fees are applied to items, when placing the order in the backoffice.

## Steps to Reproduce

It's best to disable VAT/GST for better comparison of the charged values.

Admin
1. In /admin/enterprise_fees set some enterprise fees (see ex. below). 
2. Add it to an order cycle. Make sure it applies to the products you have there (weight fees don't apply to items and vice-versa).

Customer:
3. Go to the shopfront and add some items to the cart, from the OC with the set enterprise fees
4. The fees should appear and be visible under the price breakdown. Note that not all fees appear show up here either: some appear only on checkout under Admin & Handling.
5. Place an order.

Admin:
6. Place the same order (same number of items of each product), with the same delivery and payment methods.
7. Compare the results

## Animated Gif/Screenshot

Set enterprise fees:
![image](https://user-images.githubusercontent.com/49817236/84038205-8c773580-a997-11ea-9a9e-aa0da5bb1c20.png)

Left: Backoffice, Right Shopfront
![image](https://user-images.githubusercontent.com/49817236/84036788-9e57d900-a995-11ea-9d78-d8185382afd0.png)

Backoffice and Shopfront order confirmations:

![image](https://user-images.githubusercontent.com/49817236/84037223-2e961e00-a996-11ea-9584-38bbfd469a4f.png)

## Workaround

Update and Recalculate Fees before introducing Customer Details and placing the order.

## Severity

downgraded to bug-s4

## Your Environment

* Version used: observed while testing the Spree Upgrade 2.1 branch, but also in release v2.10. - not yet confirmed in production
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Desktop Ubuntu 18.04

**Comment by filipefurtad0** [comment]
PR #7299 fixed this issue - closing.

**Comment by tschumilas** [comment]
I think that this bug only happens for the first item added to a back office order.  As soon as a second item is added (if if it is the first item a second time),  the enterprise fees (and taxes on enterprise fees)  are correctly added.   So - this is a bit different than the first issue.   (Also warrants more testing because this seems different than what was happening to me last week....)
