### ISSUE TITLE
[Spree Upgrade 2.1] Can't add shipment fee 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5568]
## Description

It's not possible to add a shipment fee, by editing the respective shipping method. Inserting values in the "Calculator" fields and pressing Update displays the message "Shipping Method "<shipmentmethod>" has been successfully updated!", but the changes don't take effect. See gif below.

## Expected Behavior

Changes should take effect, in introducing shipment fees.

## Actual Behaviour

The message is displayed but changes don't take effect.

## Steps to Reproduce

1. Go to https://staging.openfoodnetwork.org.uk/admin/shipping_methods/<shipment_number>/edit
2. Under Calculator choose a fee type and insert a value
3. Press Update -> the value is not saved.

## Animated Gif/Screenshot

![shippment_method_not_updated.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/556baa9b-dad6-409d-b0ab-106ca6680848)

## Severity

A critical feature - S2

## Your Environment

* Version used: UK 3-0 stable.
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Desktop Ubuntu 18.04

**Comment by luisramos0** [comment]
Thanks Filipe, this was the typical rails 4 strong params issue where some attributes needed to be permitted explicitly, done in #5570.
