### ISSUE TITLE
Missing translation in backoffice Payments

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5575]
## Description

When placing orders in the backoffice, and selecting Paypal under payments, the "No Payment Via Admin Backend" is not translated :

![image](https://user-images.githubusercontent.com/49817236/84174990-3974af80-aa77-11ea-9c82-e520ed983dd8.png)

## Steps to Reproduce

Log in as an admin, place an order in the backoffice and check the "Payments" section in an non-english instance.

## Severity

S4

## Your Environment

Version used: v2.10.0

**Comment by RachL** [comment]
thanks @filipefurtad0 ❤️ fyi all translation issues can be good first issues :) So I'm generally adding the label and adding them to the welcome new dev board.

**Comment by filipefurtad0** [comment]
Thanks @RachL! - I'll be sure to add that next time... :+1:

**Comment by rmklaus12** [comment]
I cannot seem to replicate this, by way of I cannot get to a spot where I can choose PayPal as a payment :-) I'm on my local, using the sample data, so have about 4 enterprises, but none have PayPal setup. If I try to add it as a payment method I get a Rails error. 
<img width="500" alt="Screen Shot 2020-06-19 at 4 44 03 pm" src="https://user-images.githubusercontent.com/30268789/85104654-4d28ce80-b24c-11ea-9702-c205cd84068e.png">

**Comment by filipefurtad0** [comment]
Hey @rmklaus12 ,

I haven't set that payment method locally, so I can't help you with that particular issue - but perhaps if can provide you credentials to a staging server, if you wish to observe the error. Would that help?

**Comment by rmklaus12** [comment]
@filipefurtad0 - that would be great! Thank you :-)
