### ISSUE TITLE
rake db:migrate fails 

### ISSUE THREAD

**Issue by umairpannu** [openfoodfoundation/openfoodnetwork#558]
rake aborted!
Value assigned to config.time_zone not recognized.Run "rake -D time" for a list of tasks for finding appropriate time zone names.
I am new in rails frame work need your guidance on this issue

**Comment by RohanM** [comment]
Hi @umairpannu! It's most likely that this error is happening because `config/application.yml` is missing. There's some instructions on setting it up in the README - see under Get it running -> Configure the site.

**Comment by pmackay** [comment]
Closing but @umairpannu please reply if there is still an issue.
