### ISSUE TITLE
[Checkout JS] Response data is null

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5583]
See epic for more context: https://github.com/openfoodfoundation/openfoodnetwork/issues/5402

### Errors where `response.data` is null

There's a number of JS checkout error cases where it looks like we've used this conditional on the response (in `#handle_checkout_error_response`): 
```javascript
if response.data.path
```
and we've hit this error: `TypeError: response.data is null `. 

There's also a very similar but separate set of errors, which are also triggered from within `#handle_checkout_error_response`:
```
TypeError: Cannot read property 'path' of null
```

Maybe we can adapt it to be a bit more defensive, eg:
```javascript
if response.data?.path?
```
and/or maybe we need to handle this case explicitly with a different error message.

**Comment by Matt-Yorkley** [comment]
Thinking about it, this issue might be caused by either of the other two issues in this epic, so maybe we should address those first and then see how it looks in prod...

**Comment by luisramos0** [comment]
I cant find this error on bugsnag but it's so easy to do that I think we should get this one in now. The else is a throw response so the error will pop up with more details :+1:
