### ISSUE TITLE
[Checkout JS] Stripe Elements

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5584]
See epic for more context: #5402

### Element not mounted

This checkout JS error appears various times in Bugsnag:
```
We could not retrieve data from the specified Element. Please make sure the Element you are attempting to use is still mounted.
```
The `Element` referred to here is actually a `Stripe Elements` object. Further reading: https://stackoverflow.com/questions/48391076/stripe-not-working-with-error-uncaught-in-promise-error-we-could-not-retriev

**Comment by luisramos0** [comment]
I can see this impacted 3 users in FR, 3 users in AU and 6 users in AUS. I wonder if this is an S2 or if we should wait a few more weeks and see if it happens often.
We could see if these users managed to place the orders in the end or if this really blocked them.

**Comment by luisramos0** [comment]
We agreed this should stay as an S2 on delivery train meeting.

Questions:
- how many users affected now since last check?
- did these users managed to checkout in some way after the error?
- does the problem go away with a page refresh?

**Comment by luisramos0** [comment]
This happened to 5 guest users in the UK in the last 3 weeks, 1 guest user in AUS, 1 in FR and none in CA.
I am not sure why these numbers are different from my previous analysis...

I am downgrading to S3 based on the very low number of users. Please feel free to disagree and move back to S2 (we may do that in some time if we see the number of occurrences going up). There's only one occurrence per IP/user so I think this is probably something that goes away as soon as the user retries or logins.

**Comment by RachL** [comment]
@jibees @Matt-Yorkley is this fixed by checkout-split?

**Comment by Matt-Yorkley** [comment]
I'm pretty sure this was fixed ages ago :smile:
