### ISSUE TITLE
[Checkout JS] Chrome security policies

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5585]
See epic for more context: #5402

### Chrome security policies

The bit that concerns me most with the dev-tools screenshot in the original issue (especially given that the reports seem to be related to Chrome) is this:

![chrome](https://user-images.githubusercontent.com/9029026/84359418-e448b300-abc8-11ea-849d-34b2f3a0e924.png)

Essentially Chrome is rolling out changes to cross-site cookie loading that will break OFN, and telling us the changes will be enforced in some upcoming version. There are a few security-labelling type things that are currently optional that we should implement sooner or later, both with cookies and with scripts. Essentially the code just needs to be explicit about declaring what external content should be regarded as safe, like "yes, allow scripts and cookies from stripe.com".

Relevant info here, specifically on the Chrome / Cookies issue: 
https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html
https://web.dev/samesite-cookies-explained/

All browsers are slowly moving in this direction, but it looks like Chrome is spearheading the move into breaking-changes territory.

**Comment by Matt-Yorkley** [comment]
Thinking about it, this issue might be caused by either of the other two issues in this epic, so maybe we should address those first and then see how it looks in prod...

**Comment by luisramos0** [comment]
This one is definitely an S2 and needs to be addressed now :+1:

**Comment by Matt-Yorkley** [comment]
So I contacted Stripe about this after reading their docs and various threads where people were experiencing the same issue, and it seems like Stripe's answer is that there isn't a problem. It looks like there's nothing we can do on our side. 

The issue is triggered from within `stripe-js`, but the code within that script already handles `SameSite` configuration for cookies. It looks like Stripe have been working on this for months, and there are potentially some minor issues remaining in some cases for users that have old cookies saved in their browsers. Clearing browser cookies manually in those cases may be the answer, but it looks like it's not something we can handle with code.

**Comment by Matt-Yorkley** [comment]
Closing for now...

**Comment by RachL** [comment]
thanks for dealing with this @Matt-Yorkley !
