### ISSUE TITLE
Release v2.10.1 Gazpacho

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5586]
Steps: 

- [x] Include translations
- [x] Release draft: https://github.com/openfoodfoundation/openfoodnetwork/releases
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1493
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by RachL** [comment]
Everything is looking good 🎉 https://docs.google.com/document/d/1Mw9PJUWP2_2AG9N5kx2Zsr6918H5glkyblf8R0yb_2c/edit#

**Comment by sauloperez** [comment]
Deployed to all instances!
