### ISSUE TITLE
Upgrade angular to latest minor release

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#559]
I've started this upgrade in the angular-1-2-26 branch. The latest version is actually 1.2.28, but the angularjs-rails gem doesn't include that release. Could you file an issue to ask them to provide that version? It seems that they have a process for doing so.

In the meantime, I imagine it'd be productive to work through the spec failures on the 1.2.26 branch. I've invited you into buildkite, and you can see the failing specs here: https://buildkite.com/open-food-foundation/open-food-network/builds?branch=angular-1-2-26 . Both the JS and the rspec tests have failures.

Let me know how you go, and if there are any backend things that you need a hand with.

**Comment by kirstenalarsen** [comment]
@RohanM is it correct to assume that this is not done or merged, so I remove it from v1.0 milestone?

**Comment by daniellemoorhead** [comment]
@RohanM was this upgrade completed? Can we close the issue now?

**Comment by pmackay** [comment]
@oeoeaio if you're updating Angular currently, would it resolve this?

**Comment by oeoeaio** [comment]
Yep, it's done. Went through in 1.8
