### ISSUE TITLE
[Rails 4.1] CSRF protection from remote <script> tags (22 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5606]
We have few errors in the build related to this change in rails 4.1:
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#csrf-protection-from-remote-script-tags

The build:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-5611/builds/8

**Comment by luchiago** [comment]
I would like to tackle this issue

**Comment by luisramos0** [comment]
this issue is not finished yet.

I think the fix in #5651 is good for controllers but I am not sure what the fix is when the problem occurs in a feature spec, for example:
spec/features/admin/enterprise_roles_spec.rb
and 
spec/features/admin/enterprise_spec.rb

**Comment by luchiago** [comment]
@luisramos0 I can check this out.

**Comment by luisramos0** [comment]
Hello @luchiago thank you!!!
I have updated the link to the latest build in the description above.

**Comment by Matt-Yorkley** [comment]
I think the remaining issues might require some tinkering with Angular. This change relates to blocking of requests executed in scripts, and CSRF protection usually entails passing a unique token with the request that can be checked on the backend.

Related reading: https://stackoverflow.com/questions/14734243/rails-csrf-protection-angular-js-protect-from-forgery-makes-me-to-log-out-on

**Comment by luisramos0** [comment]
interesting @Matt-Yorkley :+1:

**Comment by Matt-Yorkley** [comment]
This might be mostly (or entirely) fixed by #6022 already, but we won't know until we have more open PRs merged...

**Comment by luisramos0** [comment]
wait, I must have messed up the rebasing, that 6022 is not in the new branches...
let me see what happened there and add that commit to the rails-4-1 branch

**Comment by luisramos0** [comment]
here's latest build with 6022: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/rails-4-1-latest/builds/8

**Comment by luisramos0** [comment]
you are right! this is fixed :-O :tada:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/rails-4-1-latest/builds/9

there are 13 broken specs now none related to this. closing.
