### ISSUE TITLE
500 Error when creating a product with missing value

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5612]
## Description

There are a lot of required fields when creating a product.

For the most part OFN gives a good error message when a required field is blank. However when creating a product with Unit Size Items if the Value field is left blank the user sees the slug (500 error)

## Expected Behavior

When Unit Size = Items and Value is left null we should see an error message at the top of the screen explaining. 

The user sees this error message in other cases:
![Screenshot from 2020-06-15 16-37-23](https://user-images.githubusercontent.com/8669848/84677588-d6779280-af26-11ea-92ae-176becb09465.png)

## Actual Behaviour

In the case that Unit Size = Items and Value is left null the user experiences a 500 error.

## Steps to Reproduce

1. Go to create a new product
2. Enter Unit Size = Items and Value is left null 
3. Fill in all the other required fields
4. Press Create. See the Slug.

## Workaround

Fill in all the fields. It is just annoying and we have multiple support queries a week asking if Create Products is broken. This has blocked users for days.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: 2.10.1
* Browser name and version: Chrome and Firefox
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
@lin-d-hop is this a duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/4959 ? Sorry haven't had time to check in detail.

**Comment by lin-d-hop** [comment]
closing. duplicate :-)
