### ISSUE TITLE
[Spree Upgrade 2.1] Can't save changes made on Configuration > Zones > Type fields

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5620]
## Description

Saving changes takes no effect, when editing Type fields in Zones, under Configurations (superadmin), which prevents changing these settings.

## Expected Behavior

Pressing Update should make changes take effect.

## Actual Behaviour

Pressing update does not save changes.

## Steps to Reproduce

1. Log in as superadmin
2. Go to Configurations > Zones
3. Edit a Zone and attempt to make changes to the Type sections, for example, changing:
- "Country based" to "County based"
- Adding or removing countries or counties

4. Press Update
5. Verify that changes do not take effect

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/31517d4c-d243-4cb7-aa9e-4e4014227068)

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v3 stable
* Browser name and version: Firefox 75 
* Operating System and version (desktop or mobile): Ubuntu

## Possible Fix

This should be related to spree-upgrade as this issue is not observed on Katuma-staging (v2).

**Comment by Matt-Yorkley** [comment]
Probably related to strong params...
