### ISSUE TITLE
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary.

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5625]
### What we should change and why (this is tech debt)

The Rails 4 upgrade brought the following deprecation warning that likely prevent upcoming gem upgrades

```
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /usr/src/app/app/assets/stylesheets/darkswarm/variables.css.scss to /usr/src/app/app/assets/stylesheets/darkswar
m/variables.scss. (called from _app_views_layouts_darkswarm_html_haml___3990351141569700945_46957256630860 at /usr/src/app/app/views/layouts/darkswarm.html.haml:18)
(...)
``` 

You can see it just booting the app on your local machine.

### Context

This came up after the merge of https://github.com/openfoodfoundation/openfoodnetwork/pull/5158

### Impact and timeline

This, apart from slowing down the dev env and cluttering the output, it blocks future ugprades.

**Comment by Matt-Yorkley** [comment]
This makes specs incredibly noisy and should be very quick to fix, moving to top of tech-debt pile.
