### ISSUE TITLE
Not able to finish local setup on 

### ISSUE THREAD

**Issue by luchiago** [openfoodfoundation/openfoodnetwork#5629]
## Description

I tried to do the local setup of the project and I wasn't able to finish it because one seed file has a bug

## Expected Behavior

The expected behavior is being able to finish the setup of the project

## Actual Behaviour

I can't finish the setup

## Steps to Reproduce

1. Clone the repository to your machine
2. Follow the steps on GETTING_STARTED.md
3. Run `script/setup`
4. See the error

## Animated Gif/Screenshot

![error_ofn](https://user-images.githubusercontent.com/30028621/84892635-4e9f9e80-b074-11ea-8a99-3b36b761bca7.png)

## Workaround

Comment the line where the error occurs

## Severity

bug-s5

## Your Environment

* Version used: Master branch
* Browser name and version: Chromium | 83.0.4103.97
* Operating System and version (desktop or mobile): Manjaro 20.0.3 Lysia

## Possible Fix

Just change one line when an object is not found because of his name.

**Comment by luchiago** [comment]
If you guys consider as a real problem, I can send a PR fixing. It's easy to solve.

**Comment by jeduardo824** [comment]
Same here
