### ISSUE TITLE
v3 Rollout

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5637]
- [x] Deploy all servers (and notify #instance-managers)
  - [x] ES 2020-06-23 Tuesday
  - [x] DE 2020-06-24 Wednesday
  - [x] BE 2020-06-24 Wednesday
  - [x] AU 2020-07-14 Tuesday
  - [x] FR 2020-07-30 Thursday
  - [x] CA 2020-08-04 Tuesday
  - [x] UK 2020-08-04 Tuesday
  - [x] US 2020-08-06 Thursday

**Comment by Matt-Yorkley** [comment]
Added:
- Mobile Cart changes
- Display-only shops fix

Build and release notes updated.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

The release looks good to go - full test notes here:
https://docs.google.com/document/d/1pUjxsNdldyT7cq15soTjb5iPY-4csu-4BAsphP6uSoY/

Thanks for drafting and for all the help :tada: :heart:

**Comment by Matt-Yorkley** [comment]
I've updated this issue name and description as a generic placeholder for the v3 rollout
