### ISSUE TITLE
Rails 4 fingerprinted assets

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5643]
We still have some issues with non-fingerpritned assets being called from the codebase. Rails 4 basically does not do non-fingerprinted assets, at all.

More background here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5622#issuecomment-645891351

So basically it looks like we still have a bunch of places in the codebase where we are calling assets in a way that will not include the fingerprint, and we need to fix that.

**Comment by Matt-Yorkley** [comment]
It looks like this applies to fonts as well as images, and we'll need to check basically anything that's in the `/app/assets/*` directories.

**Comment by sauloperez** [comment]
I started with https://github.com/openfoodfoundation/openfoodnetwork/pull/5644

**Comment by filipefurtad0** [comment]
Hi - Just a brief feedback from my side: During testing of the release I haven't found anything major missing from the app.

**Comment by sauloperez** [comment]
@luisramos0 I think that all assets work so far due to the combination of ofn-install's (dangerous) symlink plus assets being placed in `public/` that @Matt-Yorkley described in the other issue. But it's a bit messy and makes all feel uneasy and lower our confidence so we better get as close to Rails default as we can.

**Comment by Matt-Yorkley** [comment]
> This is bug right? There will be images and icons missing from the app?

It's a worrying issue, but it shouldn't actually affect current OFN production servers at the moment, unless we start adding new assets or changing old ones. It's a bit complicated but we should probably fix it.

**Comment by Matt-Yorkley** [comment]
Basically the work that needs to be done will look a bit like [this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/5635), but for some of the other assets (like fonts and maybe some other images) that are still being generated with without fingerprints, as "non-digest assets" are now completely ignored by Rails.

**Comment by Matt-Yorkley** [comment]
As a side note, on any _new_ servers that are deployed, lots of assets will be broken for sure until we fix this.

**Comment by sauloperez** [comment]
It think it'll be fairly straightforward to find out which assets are processed with the `assets:precompile:nondigest` rake task in Rails 3.2. https://github.com/rails/rails/blob/e17e25cd23e8abd45b1706463dd57c90fa6dcb7c/actionpack/lib/sprockets/assets.rake#L33-L57 is the code responsible for doing so.

**Comment by luisramos0** [comment]
ok, makes sense. I think it's well labelled then: S3, regression, we should fix it now but will not block the release :+1:

**Comment by Matt-Yorkley** [comment]
Remaining bits:
- user-uploaded images (products, enterprise logos, etc) are not affected, they're handled by either Paperclip or S3 and will not require changes
- there are still a few images that need fixing, for things like the "no-image" image, eg the default image shown for a product when no product image has been uploaded yet
