### ISSUE TITLE
Logout during Subscription creation

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5648]
During release testing Filipe encountered a possible issue whilst creating a subscription: at the point of adding a product, got logged out unexpectedly and whilst logging back in, this error appeared in Bugsnag: 
```
NoMethodError: undefined method `empty?' for nil:NilClass
Location: app/services/permitted_attributes/subscription.rb:10 - call
```

After logging in again subscriptions seemed to work correctly, and the issue wasn't reproduced(?). 

We might need to adjust the logic a bit here:

https://github.com/openfoodfoundation/openfoodnetwork/blob/dd9d9e331677539783be44015867b08bb410314c/app/services/permitted_attributes/subscription.rb#L10

**Comment by luisramos0** [comment]
I am tagging this S2, it should block the roll out.
