### ISSUE TITLE
Variable weights - not saving (nothing happens when I hit Update)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#565]
error as shown below

![image](https://cloud.githubusercontent.com/assets/2911176/7646646/f33b91ae-fb09-11e4-84ae-2e8cea99377d.png)

this should have been deployed into staging2? @oeoeaio  any idea what's happening -  I think you said you had tried this and was working?

**Comment by lin-d-hop** [comment]
Hi @kirstenalarsen @oeoeaio 
Did you need me to look at this at all?
x

**Comment by kirstenalarsen** [comment]
this was me not understanding how variable weights was implemented. @oeoeaio then showed me and now is all good :)
