### ISSUE TITLE
User cant checkout - the app is not seeing the app settings stored in the DB

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5657]
## Description
Katuma is the first v3 deployment.
Originally a checkout problem:
User clicked 7 times on checkout but comunication with Stripe fails.
We found it through bugsnag:
https://app.bugsnag.com/katuma/katuma/errors/5ef1aba43cf9f70017838bec?filters[event.since][0]=30d&filters[error.status][0]=open

But now we see it's a config problem:
![image](https://user-images.githubusercontent.com/1640378/85398615-6c29a800-b54d-11ea-9284-bca54a641786.png)

![image](https://user-images.githubusercontent.com/1640378/85398463-2c62c080-b54d-11ea-923a-678954e5cfa1.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
This could have been caused by the config issue discussed on slack. The wrong stripe config will cause something like this. I am closing for now, we can reopen if it happens again.

**Comment by luisramos0** [comment]
I also confirmed locally that the user is not seeing a snail.
This is what the user is seeing:
![image](https://user-image:+1: ithubusercontent.com/1640378/85391113-ad1bbf80-b541-11ea-97f1-b93cc9236a2b.png)

:+1

**Comment by sauloperez** [comment]
Yes, I've seen other user errors in Bugsnag where this is displayed. You can see it in the Session tab :ok_hand: It's so good that we're improving these messages lately.
