### ISSUE TITLE
DEPRECATION WARNING: Calling #sum with a block is deprecated and will be removed in Rails 4.1

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5661]
### What we should change and why (this is tech debt)

The Rails 4 upgrade brought the following deprecation warning that prevents us from migrating to Rails 4.1

```
DEPRECATION WARNING: Calling #sum with a block is deprecated and will be removed in Rails 4.1. If you want to perform sum calculation over the array of elements, use `to_a.sum(&block)`. (called from total_on_hand at /home/runner/openfoodnetwork/app/models/spree/stock/quantifier.rb:18)
```

### Context

This came up after the merge of #5158

### Impact and timeline

This, apart from slowing down the dev env, CI and cluttering the output, it blocks future upgrades.

**Comment by luisramos0** [comment]
:+1: 
this is related or even a duplicate of #5609

**Comment by sauloperez** [comment]
I believe it exactly what you show in https://github.com/openfoodfoundation/openfoodnetwork/issues/5386#issuecomment-630877549's screenshot

**Comment by Matt-Yorkley** [comment]
I think this can be closed now :+1:

**Comment by luisramos0** [comment]
Yes :+1:
