### ISSUE TITLE
[v3] Checkout error with DB error

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5662]
## Description
This bugsnag error in katuma flag 2 users with problems on checkout.
A DB constraint problem related to created_at fields on addresses:
https://app.bugsnag.com/katuma/katuma/errors/5ef235fc2dfe230018a3c3b8?event_id=5ef235fc005b8b9aa0e10000&i=sk&m=nw

## Expected Behavior
Checkout should work.

## Actual Behaviour
User cant checkout.

## Steps to Reproduce
unknown

## Workaround
none

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
* Version used: v3.0.1
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix
There's something to do with null constraints on timestamps.
I notice the db/schema is changed on the server against git for a lot of tables, all diffs similar to this:
![image](https://user-images.githubusercontent.com/1640378/85439243-acf0e380-b584-11ea-96c7-979a0cb88187.png)

**Comment by luisramos0** [comment]
I created the PR with the results of db:migrate: https://github.com/openfoodfoundation/openfoodnetwork/pull/5663
but it's not enough, we need to find out why the values are not being populated.

A quick fix would be to remove these constraints. I am not sure how to do that.

**Comment by luisramos0** [comment]
I wonder if this could be related to this problem in v2 where the error is "Shipping address first name can't be blank, Shipping address last name can't be blank, Shipping address street can't be blank, Shipping address city can't be blank, Shipping address zipcode can't be blank, and Shipping address phone can't be blank (RuntimeError)"
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5eb17b15ad3e440017bff9a2?filters[event.since][0]=30d&filters[error.status][0]=open

**Comment by filipefurtad0** [comment]
Hi @luisramos0,
Is it possible to reproduce this in a local/staging environment?

**Comment by luisramos0** [comment]
good question: no, and I dont understand why :-(
