### ISSUE TITLE
Price Sack Shipping Method Calculator does not include Enterprise Fees

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5664]
Description
The Price Sack Shipping Method Calculator can be used to set a threshold above which a lower rate of delivery charge can be applied.  The threshold set in the admin back office is currently calculated as the customer total for products purchased only (no enterprise fees included).  
This is confusing to most users: they want to set the threshold for a customer to spend (product price + enterprise fee).

For example:
Price Sack Enterprise Fee: 
![pricesackone](https://user-images.githubusercontent.com/45104035/85442216-d52e1180-b587-11ea-831d-1a70a6d1a4f9.jpg)
Enterprise fee of 20% is applied to all products
![pricesackenterprisefee](https://user-images.githubusercontent.com/45104035/85442414-132b3580-b588-11ea-8af8-d243a298dd65.jpg)
![pricesackOC](https://user-images.githubusercontent.com/45104035/85442445-1aeada00-b588-11ea-8825-4fac010feee9.jpg)

Expected behaviour: 
Customer total is £20 or more, then the shipping fee is £0.  Customer total is less than £20 then shipping fee is £5.

Actual behaviour:
Customer total is £20.40 (£17.00 of products and £3.20 of enterprise fees). Customer pays shipping fee of £5 (unexpected)

![pricesackchargeincorrect](https://user-images.githubusercontent.com/45104035/85442750-6a310a80-b588-11ea-816a-d9b24cfc9127.jpg)

Steps to reproduce
1) set up shipping method with price sack calculator.  Set threshold between normal and discount amount as £20.
2) set up order cycles with different types of enterprise fee calculators applied.
3) add products to basket with value of £20 (inclusive of enterprise fee).
4) check out with price sack shipping method
5) observe whether discount or normal shipping fee is applied.

Potential Papercut
bug S3
good first issue

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Price Sack calc - Github issue needed](https://trello.com/c/5H8M3RYR/1178-price-sack-calc-github-issue-needed)

**Comment by luisramos0** [comment]
All calculators use line items (with their included tax) to make their calculations even if they are order level calculators (not per item calculators). I think this is a feature request. Is this request only for price sack or for all order level calculators? And: are we sure we want to make this change? Just asking.

This is definitely not a good first issue. Calculators are not easy ground.
This is not too difficult to do, changing each order level calculator to include fees is a papercut.

**Comment by lin-d-hop** [comment]
Ok, my mistake.

I thought product Enterprise Fees were included in order level enterprise fees.

Closing.

**Comment by tschumilas** [comment]
Just clarifying @luisramos0 :  If taxes are not included in prices (North America and elsewhere)  i believe all calculators are calculated on the pre-tax line amount.   So its only when taxes are included in prices that the calculation is made ontop of the tax .  I think.

**Comment by luisramos0** [comment]
correct!
