### ISSUE TITLE
Styling in main menu (Superadmin)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5671]
## Description

While testing translation PR #5589 I noticed the item "More" on the main menu is slightly misplaced. This appears only to affect  Superadmin in Language dashboard.

## Expected Behavior

Menu should look like this ("More" should appear translated, in production):
![image](https://user-images.githubusercontent.com/6525576/44862622-62013000-ac7b-11e8-8269-8f86fd0e5362.png)

## Actual Behaviour

![image](https://user-images.githubusercontent.com/49817236/85766710-3a603f00-b70f-11ea-8660-bc7a58bfcc7c.png)

## Steps to Reproduce

1. Log in as Superadmin and check how the main menu looks like in French language.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Worth checking how does it look like in production, with the due translation key.

**Comment by renanbona** [comment]
Can I take this issue?

**Comment by sigmundpetersen** [comment]
Yes, please go ahead 👍 
Welcome to Open Food Network!
Please ask if you have any questions and you are welcome to join us [on Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A)

**Comment by filipefurtad0** [comment]
Welcome @renanbona! :tada:

**Comment by RachL** [comment]
This is partially fixed now

![image](https://user-images.githubusercontent.com/6525576/89157224-72f40380-d56c-11ea-94d3-a7b2e8058790.png)
