### ISSUE TITLE
For OFN BE :translation problem, how to solve it? For "front office" texts

### ISSUE THREAD

**Issue by SophieDuponcheel** [openfoodfoundation/openfoodnetwork#5679]
## Description

For OFN Be: some words and data have not been translated and are still in English. These are data that depend on other data (e.g. time data - hour, month, year, etc.).
I guess the "distance_of_time" is a variable in the code which is translated through another library (not transifex), and this other library does not have support for fr_BE (yet). something in that direction.

Customers don't always understand and it's not very harmonious on the site. I've had a few complaints from shops.

## Expected Behavior

all the data should be translated into Fr (and dutch). This is the case for the site OFN France, or OFN Spain.

## Actual Behaviour

Some words  and data have not been translated. So we have 
"Le prochain cycle ouvrira dans **about 13 hours**. Le dernier cycle de vente s'est terminé il y a **about 1 hour**"
or "closing dans 15 heures" instead of "fermeture dans 15 heures".

## Steps to Reproduce

 https://www.openfoodnetwork.be/portouverte/shop 

1.Go to OFN Be
2.Select "comptoirs fermés" 
3.select one "comptoir fermé" and you'll se the bug.
4.

1. Go to OFN Be
2. Select "comptoir"
3. See a few shops soon to be closed: "closing dans 15 heures".

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/63047606/85853709-49003200-b7b3-11ea-9583-bdef29030015.png)

![image](https://user-images.githubusercontent.com/63047606/91408491-4027ed00-e844-11ea-813c-11a3d265a574.png)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
There is loads of information in this Slack convo that will be useful when someone picks this up:
https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1592388069220900

**Comment by luisramos0** [comment]
this was fixed for a number of languages here: https://github.com/openfoodfoundation/openfoodnetwork/pull/5807/files

I think the problem here is slightly different because the language is fr_BE and that "fr_BE" will not be available in momentjs, I think the solution is to make our code truncate the locale string and use just "fr" instead of "fr_BE" for momentJS translations. That will require some code, but it's probably a simple change.

**Comment by luisramos0** [comment]
I think this _could_ be a good first issue for a dev with some JS experience.

**Comment by SophieDuponcheel** [comment]
Ok great, thanks for that !!
So now it has to be in the hands of a developer? Is there anything I can do? to make sure it's not forgotten?

**Comment by sigmundpetersen** [comment]
I put it on the [Welcome New Developers](https://github.com/openfoodfoundation/openfoodnetwork/projects/27) board so it's more visible for potential volunteer contributors.

And you can add the 'BE' label to the issue and it will be picked up in the next round of S3 issues. You can read more about that process for instance managers here https://community.openfoodnetwork.org/t/prioritising-severity-3-bugs-to-be-fixed/1768

**Comment by luisramos0** [comment]
I just found out this problem in the closed shop page is not related to javascript and moment locales as I thought.
This specific issue is a server side problem with the function distance_of_time_in_words_to_now.

**Comment by drummer83** [comment]
Hey all,
just to let you know: I have just discovered that we have the same issue in Germany.
