### ISSUE TITLE
Variable weights improvements

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#568]
We have pushed through to production as is @lin-d-hop but in playing with it, @oeoeaio and I have a couple of suggested improvements. Think Rob is planning to do these . . 

1. Make weight and price take unit quantity into account so if there are 3 at 1kg, weight is 3000 and price corresponds to that (otherwise is really hard to see where you're actually at)
![image](https://cloud.githubusercontent.com/assets/2911176/7762278/53ae6690-0075-11e5-811a-55f0d934e26d.png)
- dynamically update if 'quantity' is changed?

2. Update the calculator at the top to read from weight / volume rather than quantity * weight
![image](https://cloud.githubusercontent.com/assets/2911176/7762303/c565b11c-0075-11e5-8205-9be11f8ab17b.png)

**Comment by kirstenalarsen** [comment]
Hi @lin-d-hop - it doesn't look like @oeoeaio is going to get to these before being away for a while - any chance / interest in you doing them?

**Comment by lin-d-hop** [comment]
hi @kirstenalarsen, sure I'll take a look at these enhancements :-)

**Comment by lin-d-hop** [comment]
PR in #644 :-)

**Comment by sstead** [comment]
Some notes from testing...
In relation to K's suggestions above.
1) Yes, the weight/volume field is showing the quanity x the unit weight/volume (as below)
![image](https://cloud.githubusercontent.com/assets/10843056/9676562/f5926f40-5310-11e5-8963-e0197d285d00.png)
2) Yes, price is automatically updating if you change the quantity or weight/volume values. The summary box at top is also calculating live.
3) No, the calculator seems to be looking at Quantity and Weight not the editable weight/volume field (as below).
![image](https://cloud.githubusercontent.com/assets/10843056/9676606/a47b562a-5311-11e5-92d5-82ede49b5e4f.png)

? I looked at a couple of reports, and it doesn't look like any changes have been made on that front yet.

**Comment by sstead** [comment]
The summary box at the top is not populating for products that are set as items (bunch, box, packet). This issue exists in production as well. I've githubed it...
![image](https://cloud.githubusercontent.com/assets/10843056/9676705/3d1d4d24-5313-11e5-8fb0-e5a7e3b7168f.png)

**Comment by sstead** [comment]
Suggestions to make feature easier to use:
The weight/volume field doesn't tell you what units the number is in. It would be great if, like in the summary box, the units are shown beside the number. Or could we have an info box that tells people. At the moment, mass units are shown in g, and volume units are shown in L. (this is a little inconsistent).

When you set the 'Group Buy Unit Size', when editing a product, there's not indication of what units to use... For mass, it's g, for volume it's L. But there's no way of knowing this- can we have an info box, or insert a greyed out grams/Litres in the box which disappears when you start typing?

**Comment by sstead** [comment]
When using the Group Buy function, I imagine it would be helpful if people got an alert if they raised a customer's order above their MAX quantity.
