### ISSUE TITLE
A missing order cycle in Katuma 

### ISSUE THREAD

**Issue by eugenichafer** [openfoodfoundation/openfoodnetwork#5681]
## Description

When a week after closing OC, people  that make accounting of this Hub did'nt find an OC. It was missing. They named his weekly OC with "Set." plus number of week. And "Set. 25" is gone on the list on OC
Instead, when you search orders by date, all Orders of this OC are in the system but no the OC

## Expected Behavior

To find OC 

## Actual Behaviour

OC is missing

## Steps to Reproduce

1. Enter Katuma 
2. Open Order Cicles of Ridorta. Grup de consum ecològic d'Horta
3. Set.25 OC is missing
4. Open Orders, then filter by date from 10/6/2020 to 15/6/2020 and you will find orders of this OC

## Animated Gif/Screenshot

<img width="1019" alt="Captura de Pantalla 2020-06-26 a les 18 44 43" src="https://user-images.githubusercontent.com/64070973/85884678-4d444380-b7e3-11ea-91d0-1e46f61615d5.png">
<img width="1022" alt="Captura de Pantalla 2020-06-26 a les 18 45 49" src="https://user-images.githubusercontent.com/64070973/85884682-4e757080-b7e3-11ea-9880-6671a17443ff.png">

## Severity
 bug-s4

## Your Environment

* Version used: V3.0.2.
* Browser name and version: Safari 13.1.1 (15609.2.9.1.2)
* Operating System and version (desktop or mobile): MacOs Catalina 10.15.5 (19F101)

**Comment by RachL** [comment]
@luisramos0 is it possibly related to v3?

**Comment by luisramos0** [comment]
The data looks good, there is no such oc in the system, the orders you are seeing are from OC Set 27 you can edit the order and see on the bottom of the page.

These are the OCs in the system for this enterprise:
![image](https://user-images.githubusercontent.com/1640378/85889111-bf685880-b7e2-11ea-918d-910f21ee2dfb.png)

Why do you think there should be one OC with that name? Any info we can use to investigate?

**Comment by eugenichafer** [comment]
You are right. Surely instead of duplicating Set. 25 OC to create the Set. 27 the cycle was modified without having duplicated it first. The first approach to the problem was to look at the order information for what OC it was, but how that information is at the bottom I didn’t notice. I apologize for wasting your time.

**Comment by luisramos0** [comment]
No problem @eugenichafer you are welcome!
