### ISSUE TITLE
Remove unchangable config settings from Configuration

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5695]
## Description
Image settings are not something that can be changed without the help of a dev: running commands on the server, moving images around, etc.
I think we can probably delete completely this page:
![image](https://user-images.githubusercontent.com/1640378/85957072-1e180880-b982-11ea-9b30-64b51953bf32.png)

The only part I have doubts are the paperclips styles, can this be changed? Will they have an impact anywhere on the app? Are these configs useful?

## Expected Behavior
No image settings in Configuration.

## Actual Behaviour
Image settings can be changed and images in the app will break.

## Steps to Reproduce
There are few cases:
- change attachments URL and see that all existing images are now gone.
- change use s3 for images and see that all images are now gone.

## Severity
I think this is the cause of S1 #5668
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
Seen in BE prod.

**Comment by luisramos0** [comment]
in the uk the paperclip styles have a # instead of a > in the name.
![image](https://user-images.githubusercontent.com/1640378/85957253-c67a9c80-b983-11ea-8dce-ee69b6dcc36c.png)

**Comment by Matt-Yorkley** [comment]
We can't currently set some of these values via provisioning, and there are different values across different servers...

I think the # and > characters are something to do with image sizing/scaling with Paperclip.

**Comment by luisramos0** [comment]
ok, do you think they are better as provisioning vars or configs in this page? do you know if these are just changeable?

**Comment by Matt-Yorkley** [comment]
I think it's best removed from the UI :+1:

**Comment by luisramos0** [comment]
:tada:
