### ISSUE TITLE
Bug: Shopping cart code displaying on smaller browser window size

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#570]
Action: I open https://openfoodnetwork.org.au/ in a smaller browser window (not full screen) on my macbook 13".

Expected: The site opens the same way it does when it is full screen, shopping cart does not display initially (see screenshot 1), once it's loaded behind the scenes it then displays.
![screen shot 2015-05-27 at 12 03 11 pm](https://cloud.githubusercontent.com/assets/10949052/7827240/6d1d07d4-0468-11e5-8825-e50849aec07a.png)

Actual: The cart displays strangely for a few seconds before the style kicks in and hides it (see screenshot 2).
![screen shot 2015-05-27 at 11 56 18 am](https://cloud.githubusercontent.com/assets/10949052/7827179/6eb5741a-0467-11e5-9c14-9a7d33c45332.png)

**Comment by kirstenalarsen** [comment]
Hi @daniellemoorhead - these are actually two different things, one of which I was just about to put in and allocate :) could you possibly split em?
