### ISSUE TITLE
Fav icon not visible in v3.x.x

### ISSUE THREAD

**Issue by satyasarathy** [openfoodfoundation/openfoodnetwork#5700]
## Description

Noticed that fav icon is not visible in versions 3.x.x. Confirmed against v3.0.0 and v3.0.2.
The fav icon in the mentioned path does not exists.
`<link href="/images/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">`

## Expected Behavior

Fav icon should appear.

## Actual Behaviour

No fav icon seen. 

## Steps to Reproduce

1. Open https://www.openfoodindia.org in chrome (also incognito)
2. Fav icon not appearing

## Your Environment

* Version used: v3.0.0 and v3.0.2
* Browser name and version: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS Catalina (10.15.4)

**Comment by Matt-Yorkley** [comment]
Part of this issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/5643

**Comment by sauloperez** [comment]
damn! that URL is missing the fingerprint so this is directly related to https://github.com/openfoodfoundation/openfoodnetwork/issues/5643. It's one of those images that need fixing. 

Thanks @satyasarathy !

**Comment by sauloperez** [comment]
lol @Matt-Yorkley

**Comment by Matt-Yorkley** [comment]
I think I might have already solved this in a PR somewhere...

**Comment by lin-d-hop** [comment]
Not fixed in Master.
Appeared in UK production on v3.2.1 today.

**Comment by RachL** [comment]
Yes on all prod now.
