### ISSUE TITLE
Require timestamps on all models that have them

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#5702]
### What we should change and why (this is tech debt)

- [ ] Replace all code that sets timestamps to `nil`.
- [ ] Change all timestamp columns to disallow null values.

### Context

Rails used to have mandatory timestamps by default (e.g. `created_at not null`). Rails 4 dropped the default value and we had some code crashing when it tried to set a timestamp to null. So we relaxed the timestamp requirement and made it optional. But since we don't know which other bugs that could introduce and Rails 5 defaults to enforcing timestamps again, we should fix our code and enforce timestamps again. The full discussion is on #5663.

### Impact and timeline

Since we don't know if the relaxed timestamps can cause other bugs, we should do this as soon as possible. Possible bugs could be:

- Orders are not displayed if they don't have a timestamp.
- Whole reports could be empty if an order without timestamps is involved.
- Certain pages could show a snail because they try to display a timestamp that doesn't exist.
- ...

**Comment by luisramos0** [comment]
:+1: that bugsnag error is not related. I think it's just someone bulk printing invoices selecting orders that are not completed. IT needs a separate issue.

Rails 5 default is different but we can keep timestamps optional in rails 5, it's not a blocker at all.

We can decide to keep timestamps optional. It's not like all things will not have timestamps from now on, just some.

I dont think it's an obvious decision.

**Comment by luisramos0** [comment]
I dont think this is a regression, a regression is a bug. Do we have specific proof that this is causing problems?

**Comment by mkllnk** [comment]
No, I don't have any proof that this is a problem at all. I just listed potential problems that can happen when those edge-case orders are present in the database.

I don't think a release test will find potential problems unless we erase some timestamps in the database. If all other code works correctly, everything will still have timestamps and all is good. We should set the currently missing timestamps though.

It's difficult, because this is not an issue in itself but it increases the risk of other issues.
