### ISSUE TITLE
Email domain gone back to demo.spreecommerce.com after deploying v3.0.2

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5704]
## Description
Emails with wrong domain in India and Brasil after deploying v3.0.2.

## Expected Behavior
Emails should be sent from the configured domain.

## Actual Behaviour
demo domain was used.

## Steps to Reproduce
Deploy v3 in a v2 server and send a test email.

## Workaround
Set the domain in mail settings again?

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
India and Brasil servers

* Version used: v3.0.2

## Possible Fix
This maybe related to #5668 and the new data format in table spree_preferences.

**Comment by satyasarathy** [comment]
@luisramos0 The logo also seems out of line.
![image](https://user-images.githubusercontent.com/3152144/86132530-a3c3c180-bb04-11ea-9fff-d95c782db64c.png)

Please note that this anomaly is also found in v2.10.1.

**Comment by sigmundpetersen** [comment]
Was the anomaly seen in 2.10.1 after reverting from 3.0.2 @satyasarathy ?

**Comment by satyasarathy** [comment]
@sigmundpetersen I first reverted to v3.0.0 and then to v2.10.1. I did not see this anomaly in 3.0.0.

**Comment by luisramos0** [comment]
I just registered in BR and the problem is solved. I am not sure what happened there.

@satyasarathy I think you should move back to v3.0.2 and we should work from there.

**Comment by satyasarathy** [comment]
@luisramos0 I just moved to v3.0.2 and yes the email part is resolved. But the fav icon (https://github.com/openfoodfoundation/openfoodnetwork/issues/5700) is still not visible.

**Comment by luisramos0** [comment]
ok, #5700 is not related to this issue here except the fact they are issues in the same version.

So, this issue is fixed in both Brasil and India BUT I dont know why it happened or what fixed it or if it is going to happen in other instances as they upgrade to v3. Looks like this will happen again to other instances as it happened in both IN and BR.

Let's try to describe what was done in India, did you just deploy the different version @satyasarathy ? (in this sequence 3.0.2, 3.0.0, 2.10.2 and then 3.0.2 again) Did you run any manual commands?

@rafaelbbraz can you add some details about what have you done in BR exactly?

**Comment by satyasarathy** [comment]
@luisramos0, India instance was originally on v2.9.10 (Chop Suey). Then it was upgraded to 3.0.2.
Yes, the sequence was 3.0.2, 3.0.0, 2.10.1 and finally 3.0.2. I only ran this deploy  command (changed the versions accordingly)
`ansible-playbook playbooks/deploy.yml --limit in-prod -e "git_version=v3.0.2" -vvvv`

**Comment by luisramos0** [comment]
great, that's useful, did you go to /admin/general_settings/edit and tried to change the data there?

**Comment by satyasarathy** [comment]
@luisramos0 the change was required only when moving between major versions.

**Comment by rafaelbbrazdmc** [comment]
My deploy was in a new server directly to 3.0.2 and after I move to 3.0.0 and the email was fixed!

**Comment by Matt-Yorkley** [comment]
The icons/logos issue is totally separate and is already fixed in other PRs (which should be in the next release) :+1:

I'm not sure about all the variables in play here; both of these servers were reset / reinstalled just before this bug appeared, right?

This appears to be related to https://github.com/openfoodfoundation/openfoodnetwork/pull/5660 and the marshalling/unmarshalling preferences issue. I'm concerned the switching back to previous releases might have had a negative impact here with the migrations.

**Comment by satyasarathy** [comment]
@Matt-Yorkley Is there any specific operation or validation steps that be performed to see for any negative impact.

**Comment by filipefurtad0** [comment]
Hello!

I checked for this issue in AU production server, right after deploying `v3.1.0` - it looks good:

![image](https://user-images.githubusercontent.com/49817236/87463510-6c2b3e00-c609-11ea-96d6-21e602d470ec.png)

**Comment by luisramos0** [comment]
nice, thanks Filipe.

I think we can close it now.
We can reopen if it comes back later in some server.
