### ISSUE TITLE
Bugsnag when printing of alternative-invoice of orders in cart state

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5708]
## Description

Bulk printing of orders in cart state generates errors 422 (seen in the console) and Bugsnag errors, across staging servers (both v3 and v2.1). The user sees an endless-spinner and several GET requests are sent.

In staging-ES:

![image](https://user-images.githubusercontent.com/49817236/86139994-4752a900-bae8-11ea-82e8-d650333cddd7.png)

https://app.bugsnag.com/katuma/katuma/errors/5ef35f60d643330019edb2c6?filters[event.since][0]=30d&filters[error.status][0]=open
```
ActionView::Template::ErrorBulkInvoiceService#start_pdf_job_without_delay
undefined method `to_date' for nil:NilClass Did you mean?  to_a18 seconds agoJun 30th, 14:40:35 UTC | staging |  -- | -- | --
```

In staging-AU

![image](https://user-images.githubusercontent.com/49817236/85574134-6952b400-b62e-11ea-8ea7-cfa303ed7366.png)

https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5ef367c30c9a67001715b9dc?event_id=5ef367c3005b7b5abac50000&i=sk&m=nw

```
ActionView::Template::ErrorBulkInvoiceService#start_pdf_job_without_delay
undefined method `full_address' for nil:NilClass
```

- Observed while testing - https://github.com/openfoodfoundation/openfoodnetwork/issues/5561#issuecomment-648855149
- Reproduced by @luisramos0 - see : https://openfoodnetwork.slack.com/archives/C015WAZHF7C/p1593503633228200?thread_ts=1593436667.217800&cid=C015WAZHF7C

## Expected Behavior

Hide the print invoice button when showing incomplete orders.

## Actual Behaviour

Send a bulk print job to cart state orders triggers (many) errors above and leaves the user with an endless spinner.

## Steps to Reproduce

1. Login as superadmin
2. Go to /orders and untick the "Only show complete orders" box
3. Press Filter Results
4. Select an order in the Cart state
5. Open the browser console and press Print Invoices

## Workaround

You need to press escape or F5 to exit the endless-spinner.

## Severity

This is probably an edge case, but generates a lot of errors...
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v2.1 and v3.
* Browser name and version: Firefox 77
* Operating System and version (desktop or mobile): Desktop/Ubuntu

**Comment by filipefurtad0** [comment]
This issue concerns the **alternative invoice** only - I've updated the title. Some additional notes:
- the 422 error is displayed even for `complete` orders when bulk-printing

However:
- attempting to print orders in `payment` or `cart` state from the **/orders** page does indeed trigger this error:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60db13a52c42e6000863225a?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=30d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Bapp.release_stage%5D%5B%5D%5Bvalue%5D=staging&filters%5Bapp.release_stage%5D%5B%5D%5Btype%5D=eq&event_id=611f7b86007f9c392a310000

and leaves the user with the endless spinner.

**Comment by sinansonmez** [comment]
Hello @filipefurtad0. 

I recreated this issue, please find the video below. However, as you can see below, the system actually created the invoices without any issue. 

I wanted to confirm the expected behavior: If an order in `payment` or `cart` status, the `Print Invoices` button should be disabled, right? If yes, I can start working on the solution. 

https://user-images.githubusercontent.com/37421564/133143254-09390658-534b-446d-9c4e-df5d621aac86.mov

**Comment by filipefurtad0** [comment]
Hey @sinansonmez ,
Thanks for that feedback.

Agree with your proposal as quick win, as this is the current behavior, when one tries to print each order, under `https://staging.openfoodnetwork.org.uk/admin/orders/<order_nr>/edit`, the Actions menu is disabled:

![image](https://user-images.githubusercontent.com/49817236/133251234-56899e45-e2ac-4017-bde3-bb9a24be5498.png)

This menu becomes enabled once an order is in state = `complete`. So I think the bulk order printing (done from `/orders`) should follow this behavior as well:
- only orders in state `complete` should display the checkbox to be selected for bulk invoice printing, in the orders table (updated Expected Behavior accordingly)

This should prevent the endless spinner from being displayed to the user.

**Comment by RachL** [comment]
Hello @sinansonmez ! I hope this message finds you well. Are you stil working on this one?

**Comment by sigmundpetersen** [comment]
@RachL I think the updated status is in the connected PR.
I wonder if there's actually a product decision needed to proceed 👍

**Comment by sinansonmez** [comment]
Hey, @RachL and @sigmundpetersen , I was waiting for a decision to proceed in [this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/8197#issuecomment-934643851)

**Comment by pedrocarmona** [comment]
Hey, I believe this card is no longer valid. The view logic has changed in https://github.com/openfoodfoundation/openfoodnetwork/pull/10833

**Comment by RachL** [comment]
Thanks @pedrocarmona ! Closing :)
