### ISSUE TITLE
reroute old urls that are 404ing from google e.g. /products

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#571]
probably just send them to home page - openfoodnetwork.org.au but if you want them mapped to specific pages can ask @daniellemoorhead to map for you, just need to let her know what the problematic ones are

**Comment by mkllnk** [comment]
@kirstenalarsen 


I'm not sure if we are talking about two different things here.

 1. The grumpy cat on /products: I have a patch for that and it would be good if someone let's me know if there are more problematic URLs. We will see it in Bugsnag if these errors occur.

 2. The redirect table @daniellmoorhead created for the new global website. #572 It contains the URLs of old pages like the old user manual that should be redirected to the new page as soon as it is in place. That is a separate issue we should work on when the global sites gets online. It might involve configuring several web servers that are completely independent from the OFN source code.

@daniellmoorhead: Do you have URLs on openfoodnetwork.org.au that should be redirected somewhere as well?

**Comment by daniellemoorhead** [comment]
I don't have those Maikel - I only looked at the openfoodnetwork.org. I can
have a look at .org.au next Friday if you'll have time to implement the
redirects on your last day?

**Comment by mkllnk** [comment]
This one is done. The redirects for the global website have do be done when we switch over to that.

**Comment by mkllnk** [comment]
Just noticed that this branch was forgotten: url-redirects
It can go into one of the next staging ones.
