### ISSUE TITLE
New global site - Permanent redirects required when it goes live

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#572]
Need to add a few redirects on the server for when the content at http://global.openfoodnetwork.org goes live and replaces the current content at http://openfoodnetwork.org. This will make sure that we don't have users coming through via out of date bookmarks / out of date indexed pages linked to in search engine results. No one likes a 404 to be their first view of OFN :)

REDIRECT 1. HOMEPAGE
Depending on what the decision is on the URL for the new site there may need to be a redirect set up for the homepage. 

i.e. if it remains as a sub domain 'global.openf...' or equivelant it will need a redirect, it won't if it replaces the domain level 'openf...'

REDIRECT 2. ABOUT PAGE
On old site - http://openfoodnetwork.org/about.html - to be redirected to new site homepage.

REDIRECT 3. GET INVOLVED PAGE
On the old site - http://openfoodnetwork.org/get-involved.html - to be redirected to the new volunteer page - http://global.openfoodnetwork.org/about/volunteer/

**Comment by mkllnk** [comment]
And there is other old content on openfoodfoundation.org as well.
There we have two options:

1. Edit the documents to include the new URL. For example a big yellow box: "This content is out of date. Please visit global.openfoodnetwork.org/..."

2. Implement redirects, for example:
http://openfoodfoundation.org/document/ofn-user-manual -> http://global.openfoodnetwork.org/platform/user-guide/

**Comment by RohanM** [comment]
I've made these two redirects (about.html and get-involved.html). Any others can be made easily from the backend - Settings -> EPS Redirects.
