### ISSUE TITLE
Remove space from "welcome_to" and "closing" Transifex keys in different languages

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5723]
## Description

PR #5707 introduced a change in the code which adds an space before welcome_to and closing keys. Before, this space was included in the Transifex files, after the translated text. This needs to be removed now to avoid a double space, from the keys:

- "closing"
- "welcome_to"

This was already done in #5707 for en.yml:

- closing: "Closing " -> closing: "Closing"
- welcome_to: "Welcome to " -> welcome_to: "Welcome to"

and now needs to be done for all languages which have an extra space after the translated text.

## Expected Behavior

- with the key set to:
`welcome_to: "Welcome to"`

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/857524c5-797e-4f43-ae14-6fd953c36931)

## Actual Behaviour

- with the key set to:
`welcome_to: "Welcome to "`

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/56698708-ef7a-4d1e-9883-bcaae344a771)

## Steps to Reproduce

The `welcome_to` key is visible in the subject of the confirmation Email:

1. Sign in on OFN
2. Click on "Confirm this email address" on the confirmation email
3. Log in for the first time
4. Check your mailbox again and look for the subject of the confirmation email

The `closing` key is visible in the shopfront (/shops):
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/d739b5e8-ef7e-4aa6-9659-d39b9ece4c9f)

## Severity

bug-s3: a feature is broken but there is a workaround

**Comment by luisramos0** [comment]
Thanks Filipe. The description is very good and useful to get the task done but I wonder if this is a valid issue in GH. The changes (remove the space) is something to be done in transifex only.

**Comment by filipefurtad0** [comment]
Thank you for your feedback on this @luisramos0 .

Indeed, this is not a valid GH issue. My intention was to make this visible to the community: perhaps a post on Slack mentioning this issue, would be more appropriate?

Closing.

**Comment by luisramos0** [comment]
yeah, I am not sure what's best approach, maybe slack :+1:

**Comment by RachL** [comment]
@luisramos0 @filipefurtad0 Transifex has triggered new keys for both, so I guess translators will translate them without space.
