### ISSUE TITLE
New global site - order hierarchy on page titles

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#574]
Page titles - suggest that you put the sequence in opposite order, and show the heirarchy in the title as well.

So have something like this:

Volunteer - About - Open Food Network
or 
Volunteer - Open Food Network

Rather than:

Open Food Network - Volunteer

Doing them opposite means that when you have more than one tab open you can see which is which rather than having all of them say the same thing. See what I mean:
![screen shot 2015-05-22 at 2 41 18 pm](https://cloud.githubusercontent.com/assets/10949052/7828248/619e05dc-0474-11e5-8b9d-4ee523b7860d.png)

**Comment by myriamboure** [comment]
@daniellemoorhead maybe when you rework on the global website with Jens you can also pay attention to that? :-)

**Comment by daniellemoorhead** [comment]
Closing as this has nothing to do with the OFN code base
