### ISSUE TITLE
The shopfront search doesn't find display names of variants

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#5757]
## Description

When a variant has a unique display name and you search for it in the shopfront, no products are shown.

## Expected Behavior

Products are found by a variant's display name

## Actual Behaviour

Display names are ignored by the search.

## Steps to Reproduce

1. Create a variant with a display name "Marmelade" but don't call anything else in the product like that.
2. Go to the shopfront and type "Marm"
3. No product is shown even though the product with "Marmelade" should show.

## Animated Gif/Screenshot

![Search](https://user-images.githubusercontent.com/3524483/87120573-17638c80-c2c4-11ea-988e-0c510ea2d9e8.gif)

## Workaround

Use the browser's search function.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.1.0

**Comment by mkllnk** [comment]
Bumping to s3 after a comment from Luis: https://github.com/openfoodfoundation/openfoodnetwork/pull/5756#pullrequestreview-446327114

**Comment by Matt-Yorkley** [comment]
Dev note: we should re-enable this [broken spec](https://github.com/openfoodfoundation/openfoodnetwork/issues/5756) while fixing this bug.
