### ISSUE TITLE
PinPayments not supported in OFN v3

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#5764]
## Description

Selecting a PinPayments payment method during checkout results in the error:
> That payment method is unsupported. Please choose another one.

Unfortunately, this enterprise doesn't have any other payment methods configured. We have 15 active payment methods used by 33 enterprises. 5 of those enterprises have only PinPayments configured. All other enterprises have at least on other payment method available.

Only one enterprise has active order cycles: `2876`

Enterprise ids with only PinPayments: `284, 648, 1899,  2220, 2876`

All affected enterprise ids:
```rb
Spree::PaymentMethod.where(type: "Spree::Gateway::Pin").where(active: true).joins(:distributors).uniq.pluck('enterprises.id')
# 56, 86, 95, 111, 112, 121, 123, 134, 140, 141, 189, 220, 259, 265, 283, 284, 319, 397, 502, 520, 524, 624, 648, 666, 738, 1899, 1959, 1960, 2028, 2137, 2141, 2220, 2876
```

## Expected Behavior

PinPayments works during checkout as before. It has been broken in the backend for a while (#2514)

## Actual Behaviour

The checkout fails and an error message is displayed at the top.

## Steps to Reproduce

1. Select a PinPayments payment method during checkout
2.
3.
4.

## Animated Gif/Screenshot

![Screenshot from 2020-07-15 10-31-48](https://user-images.githubusercontent.com/3524483/87489497-87885e80-c686-11ea-80a4-c44f90d6975e.png)

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: v3.1.0 on Australian production
* Browser name and version:
* Operating System and version (desktop or mobile):

## Bugsnag

**RuntimeError** in **checkout#update**
That payment method is unsupported. Please choose another one.

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5f0e3bf28137c100180b4e75?event_id=5f0e3d55005b85c5ac910000&i=gh&m=ci)

## Stacktrace

    app/controllers/checkout_controller.rb:242 - update_failed
    app/controllers/checkout_controller.rb:178 - checkout_workflow
    app/controllers/checkout_controller.rb:52 - update
    app/services/current_order_locker.rb:11 - block in around
    app/services/current_order_locker.rb:24 - block in lock_order_and_variants
    app/services/current_order_locker.rb:22 - lock_order_and_variants
    app/services/current_order_locker.rb:11 - around

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5f0e3bf28137c100180b4e75?event_id=5f0e3d55005b85c5ac910000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by luisramos0** [comment]
Hi Maikel, we have one failed payment, how do we know it's totally broken? Have you tested it?

**Comment by mkllnk** [comment]
Yes, I tested it. And there have been no successful orders in that shop today.

**Comment by mkllnk** [comment]
The ActiveMerchant version did not change during the upgrade. It stayed at 1.78.0. I tried a Visa card and the gateway supports that: https://github.com/activemerchant/active_merchant/blob/v1.78.0/lib/active_merchant/billing/gateways/pin.rb

**Comment by mkllnk** [comment]
I found that `Spree::CreditCard` is not supplying a brand like "visa" as it should do. And Spree verifies that:
https://github.com/openfoodfoundation/spree/blob/0b0c422369c82b6dd7e7cb627a24e3a9fca19a6c/core/app/models/spree/gateway.rb#L50

So the question is if Spree introduced this check or if they got rid of the brand.

**Comment by mkllnk** [comment]
I worked on a fix and tested it successfully. I'll open a PR soon. For Australia it would be great to deploy this before Sunday when our customer opens the next order cycle.
