### ISSUE TITLE
[mobile ux] Close cart dropdown doesn't slide off screen

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#5765]
## Expected Behavior
Cart should slide shut on desktop/tablet the same way it slides open - smooooooooooothly

![](https://media1.giphy.com/media/3oEdv83HXgTdrPfvPi/giphy.gif)

## Actual Behaviour
Cart closes without the slide effect, it just disappears, poof gone, no smooooooooth.

![](https://gifimage.net/wp-content/uploads/2018/05/slamming-door-gif-2.gif)

## Steps to Reproduce

1. Go to a shop on desktop
2. Open the cart (smooooooothly slides out from the side of screen)
3. Close the cart (eek, it's gone, no smooth)

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley I assume it's best for you to tweak this one given you did the original work?

**Comment by Matt-Yorkley** [comment]
Sure :+1: It's a pretty easy one.
