### ISSUE TITLE
Can't update Pin Payment API key

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5767]
## Description

Observed in both on staging-AU and in production-AU servers, after deploying v3.1.0:

- It's not possible to Pin Payment API key, while setting up this payment method (see gif below). This is a v3 regression and blocks testing PR #5766 and this payment method.

## Expected Behavior

Changes should take effect by inserting values in the API key field and pressing Update should displays the message "Payment Method has been successfully updated!".

## Actual Behaviour

Inserting values in the API key field and pressing Update displays the message "Payment Method has been successfully updated!", but the changes don't take effect. See gif below.

## Steps to Reproduce

1. Create a "Pin Payment" payment method
2. Insert an API key
3. Press Update
4. Verify that changes did not take effect

## Animated Gif/Screenshot

![cant_updat_api_key](https://user-images.githubusercontent.com/49817236/87538602-6169bb00-c694-11ea-9529-b0b4c9eac724.gif)

## Workaround

No workaround.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: v3.1.0
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop/GalliumOS

## Possible Fix

Related to #5766.
Possibly related to #5568 and the respective PR #5570.

**Comment by Matt-Yorkley** [comment]
Its probably a Strong Params issue. This payment method didn't really get tested during the upgrade.
