### ISSUE TITLE
Software version can be displayed in the UI or Admin interface

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#577]
It would be very helpful for testers if there was an obvious way to know what version of OFN was running when looking at web pages, rather than having to use git versions to work this out. 

Would best practice here be to add a `VERSION` file in the project root, that is updated on each major version update? 

@lin-d-hop any thoughts?

**Comment by Em-AK** [comment]
@emaestracci and @knopfler81 implemented this by relying on the last existing git tag.

**Comment by pmackay** [comment]
@Em-AK is there a commit for that?

**Comment by Em-AK** [comment]
Yes here for the moment: https://github.com/knopfler81/openfoodnetwork/commit/7aa1a3f892bd56237457436f7c83e96e3408a8b7

**Comment by Em-AK** [comment]
Update here https://github.com/WildCodeSchool/openfoodnetwork/pull/3

**Comment by pmackay** [comment]
@Em-AK what's needed to get the PR for this completed?

**Comment by bingxie** [comment]
I have used this gem(https://github.com/dtaniwaki/rack-dev-mark) to show different things for different envs. And it's very beautiful.

**Comment by bingxie** [comment]
![snip20160601_1](https://cloud.githubusercontent.com/assets/1144652/15695762/f8049c14-27ed-11e6-93db-fd03131d5a64.png)
![snip20160601_2](https://cloud.githubusercontent.com/assets/1144652/15695761/f803a16a-27ed-11e6-897f-933ba9b6cb56.png)

**Comment by daniellemoorhead** [comment]
Hey @bingxie have you put this into staging for @sstead to test?

**Comment by bingxie** [comment]
Need someone to review the PR, if there is no comments, @sstead can stage it and have a test. Thanks

**Comment by daniellemoorhead** [comment]
Work was done in #1021 but a new approach was discussed on that PR that isn't yet implemented. Would be good to have someone pick this up and implement the described approach:

>I really like the idea of using GitHub's webhooks to listen for release events and to then update the version number accordingly.

**Comment by sauloperez** [comment]
Can someone describe that other approach?

> I really like the idea of using GitHub's webhooks to listen for release events and to then update the version number accordingly.

To me it looks overly complex. What's wrong with having a VERSION file in each deploy and reading the number from it? I know it's not as cool as a webhook :trollface:

**Comment by mkllnk** [comment]
> What's wrong with having a VERSION file in each deploy and reading the number from it?

Do you mean that the deployment process generates that file, but it's not tracked by Git? Sounds simple and it would do the job. Only in Aus production we would never see the tagged version name, because we deploy before we release. Not a big deal for me.

**Comment by sauloperez** [comment]
exactly that @mkllnk. You get the tag and the sha from the git remote, for instance. @enricostano you're way more familiar with the deployment process than me. Does this sound good?

**Comment by oeoeaio** [comment]
> To me it looks overly complex.

Looking back at what we were proposing, I tend to agree. It would have been shiny, but maintaining webhooks to all servers wouldn't have been very pleasant.

If we are going to update the version as part of deployment it would be good to only have to implement that in one place. @maikel, in an ideal world would we use `ofn-install` for deployment, and encourage everyone else to do the same?

**Comment by maikel** [comment]
You probably mean someone else.

**Comment by mkllnk** [comment]
> To me it looks overly complex.
> maintaining webhooks to all servers wouldn't have been very pleasant.

I agree.

> it would be good to only have to implement that in one place.

Yes, I agree on that as well.

The whole Ansible vs Git deployment discussion is a bit bigger. I think we should do that at the forum, possible topic: "What would be the best way to deploy and update OFN?"

Just to solve this issue, we could write a little shell script that writes the currently checked out version to a file. We can call that script from the Git hook and the Ansible playbook. Hm, it's actually a one liner:

```sh
#!/bin/sh
git describe --tags > VERSION
```

What do you think?

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/display-software-version/1170

**Comment by RachL** [comment]
Reopen for the upcoming devhack

**Comment by lin-d-hop** [comment]
No one devhacked this and we have a workaround using Slack and Github Wiki. Bye bye. #gitcull

**Comment by drummer83** [comment]
Fixed by #11004.

**Comment by drummer83** [comment]
Fixed by #11004.
