### ISSUE TITLE
2 users cant checkout after v3 deployment in AUS - bugsnag UnhandledRejection/checkout

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5772]
## Description
I am a bit puzzled by these two users that did not manage to checkout in AUS in the last 24 hours...
https://app.bugsnag.com/yaycode/open-food-network-js-australia/errors/5e830917206643001787799f?filters[event.since][0]=30d&filters[error.status][0]=open&pivot_tab=event
This could be an S1/S2 in v3...  only 2 users, stripe payments. 3 retries for each of these 2 users, no success as far as I can see.
The 7th event on the list (3rd user) managed to checkout on a second attempt.

The problem is that this error UnhandledRejection/checkout was not happening in v2 after 2 of my javascritpt PRs improving checkout code... so, it's a new type of error where the server returns 404. I may be missing something.
 
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
@luisramos0 as we decided in delivery train I'm closing this one as there hasn't been any more report, and probably linked to #5785 . Please reopen if I've misunderstood.

**Comment by luisramos0** [comment]
yes, let's keep it closed. We can reopen if/when the bugsnag alert appears again.
