### ISSUE TITLE
Pin Payments fail for cards with expiry date on the present month (on first attempt)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5776]
## Description

"Pin Payments" fail if the card has an expiry date for the month in which the payment is being processed, i.e., the present month. The error "One or more parameters were missing or invalid" is shown, and checkout is not completed.

Retrying by clicking "Place order now" once more renders the payment successful. 

This was observed while testing PR #5766 , on different staging servers and immediately after deploy and restarting unicorn, as attempts to exclude possible "memory-effects" in the queuing of error messages. See also test notes: https://github.com/openfoodfoundation/openfoodnetwork/pull/5766#issuecomment-659059221

## Expected Behavior

Payment should be successful on first attempt, with cards valid til the end of the present month.

## Actual Behaviour

The error "One or more parameters were missing or invalid" is show and retrying is necessary to perform checkout.

## Steps to Reproduce

As admin:
1. Set up payment "Pin payments" payment method. See https://github.com/openfoodfoundation/openfoodnetwork/pull/5766#issue-449304378 for details.

As customer:
2. Go to the shopfront insert items in the cart and proceed to checkout
3. Choose a "Successful response" test card from https://pinpayments.com/developers/api-reference/test-cards
4. Make sure you insert a random security code is three-digit for Visa and Mastercard and four-digit for American Express
5. Select the "Expiry date" for the current month and year (July 2020, at time of writing)
6. Click "Place order now" and verify the error (see pic below)
7. Click "Place order now"  once again. Checkout should be successful.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/87691289-58571780-c782-11ea-8eab-b83affba71f2.png)

## Workaround

 Click "Place order now" a second time.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.1.0
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop/GalliumOS v3.1

## Possible Fix

Possibly related with v3 upgrade, but unsure - label was not added, for this reason.

**Comment by luisramos0** [comment]
Hi Filipe, this is pre-existing. We are considering not support PinPayments at some point, correct?
I'd say this is an S4.

**Comment by RachL** [comment]
> We are considering not support PinPayments at some point, correct?

I think this has not been validated yet :(

**Comment by filipefurtad0** [comment]
Thanks @luisramos0 and @RachL,

Indeed, the decision to discontinue supporting this feature hasn't yet been taken, but since the issue is per-existing and it should affect few users - agree with downgrading.

**Comment by RachL** [comment]
Pin Payments have been removed, closing.
