### ISSUE TITLE
Pin payments not working in backoffice orders

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5790]
## Description

Pin payments are not working when placing orders in the backoffice. Inserting valid or invalid payment credentials leads to the same result: no error is displayed, but the payment is not accepted.

## Expected Behavior

Providing:
- invalid card information should display the error message: "Error saving payment".
- valid card information should result in a successful payment.

## Actual Behaviour

No error is displayed. The user is redirected to the payments page of the order-edit section.

## Steps to Reproduce

1. Edit or create an order. Add items/customer information.
2. Add a new payment and choose Pin Payments.
3. Fill in some of the required fields with random, invalid card data (random charterers) and press Update (fail-case)
4. Fill in all of the required fields with valid card data (random charterers) and press Update (pass-case)
5. Verify that both 3. and 4. yield the same result.

## Animated Gif/Screenshot

![pin_payments_fail.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/030e8b2f-c89a-4b49-bfd4-7937a9745279)

![pin_payments_fail_2.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/a8157229-d660-4190-9906-c6c0b81269b1)

## Workaround

Using other payment methods.

## Severity

I guess this one belongs together with #5766 - maybe S2?

## Your Environment

* Version used: Firefox 78
* Browser name and version: v3.1.0
* Operating System and version (desktop or mobile): Desktop/Ubuntu 18.04

**Comment by RachL** [comment]
@filipefurtad0 I don't think we will be able to do it as an s2. Otherwise we would need to cover this for paypal as well. I'm not even sure this as worked before ping @kirstenalarsen

**Comment by filipefurtad0** [comment]
Thank you @RachL, I just removed the label and was about to write :+1

**Comment by mkllnk** [comment]
@filipefurtad0 This has been broken for a long time. This issue seems to be a duplicate of #2514.

**Comment by filipefurtad0** [comment]
Thanks @mkllnk - closing.
