### ISSUE TITLE
Enterprise logos not showing on Aus production

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5797]
## Description

Enterprise logos are showing broken image placeholder in Shop

On top of shop page
![image](https://user-images.githubusercontent.com/2911176/88048185-3997bd00-cb96-11ea-9126-8fd781320214.png)

In Producer profile in shop
![image](https://user-images.githubusercontent.com/2911176/88048222-4d432380-cb96-11ea-8bd2-11c5b6bbbfd7.png)

Profiles on map
![image](https://user-images.githubusercontent.com/2911176/88048277-621fb700-cb96-11ea-9928-45c3145e2148.png)

![image](https://user-images.githubusercontent.com/2911176/88048302-6fd53c80-cb96-11ea-9667-d3d6cc0a22ac.png)

It's not just the logo it's also the banner images

About tab in Shop
![image](https://user-images.githubusercontent.com/2911176/88048366-8a0f1a80-cb96-11ea-9630-21c340f1298f.png)

## Expected Behavior

Enterprise logos and banner images should display

## Actual Behaviour
Broken images displayed

## Steps to Reproduce
Go to Aus production - openfoodnetwork.org.au. Pick a shop or enterprise profile anywhere in the site!

## Severity
<!-- Assign a label and explain the impact.

S1 or S2?

**Comment by sauloperez** [comment]
I did a quick check and the favicon and hub pictures are missing but not the product images. While the latter are served successfully from S3, the hub pictures point to `/images/enterprises/logos/...`, a local filesystem path, and it should be S3 as well. I bet then, it has something to do with the issue we are having with preferences somehow and the config settings set from the admin UI.

**Comment by kirstenalarsen** [comment]
is it worth me fiddling with config settings? I suspect not . .

**Comment by luisramos0** [comment]
please do not change settings in the admin Kirsten, if you did it already let us know exactly what have you changed. thanks!

**Comment by sauloperez** [comment]
yes, changing settings UI makes these issues twice as hard to debug/fix :warning:

**Comment by kirstenalarsen** [comment]
nope i haven't. won't

**Comment by sauloperez** [comment]
It seems that the settings are ok as `Spree::Image.attachment_definitions[:attachment]` returns the expected values.

**Comment by sauloperez** [comment]
:see_no_evil: I just did a restart and [Remi's Patch](https://openfoodnetwork.org.au/remi-s-patch/shop) promo image is back

**Comment by kirstenalarsen** [comment]
yep :) closing

**Comment by kirstenalarsen** [comment]
was that a bit hasty @sauloperez ?

**Comment by luisramos0** [comment]
I forgot to mention that when I run the SQL to fix the spree_preferences calculators issue I also cleared the cache on the rails console and restarted unicorn. I am not sure how that could have caused this issue but its worth mentioning...

**Comment by sauloperez** [comment]
mmm I haven't found any trace of preferences while digging around but it's worth knowing. Thanks @luisramos0 :+1:

**Comment by sauloperez** [comment]
> was that a bit hasty @sauloperez ?

as long as the images you checked are back is fine
