### ISSUE TITLE
ActiveRecord::InvalidForeignKey in spree/orders#populate

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#580]
## Exception in OpenFoodNetwork

**ActiveRecord::InvalidForeignKey** in **spree/orders#populate**
PG::Error: ERROR:  insert or update on table &quot;adjustment_metadata&quot; violates foreign key constraint &quot;adjustment_metadata_adjustment_id_fk&quot;
DETAIL:  Key (adjustment_id)=(224018) is not present in table &quot;spree_adjustments&quot;.
: INSERT INTO &quot;adjustment_metadata&quot; (&quot;adjustment_id&quot;, &quot;enterprise_id&quot;, &quot;enterprise_role&quot;, &quot;fee_name&quot;, &quot;fee_type&quot;) VALUES ($1, $2, $3, $4, $5) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550949537c992b99eacf44ce?event_id=556ead903f6d8bce636b42b7)
## Stacktrace

```
lib/open_food_network/enterprise_fee_applicator.rb:6 - create_line_item_adjustment
lib/open_food_network/enterprise_fee_calculator.rb:32 - block in create_line_item_adjustments_for
lib/open_food_network/enterprise_fee_calculator.rb:31 - each
lib/open_food_network/enterprise_fee_calculator.rb:31 - create_line_item_adjustments_for
app/models/spree/order_decorator.rb:161 - block in update_distribution_charge!
app/models/spree/order_decorator.rb:159 - update_distribution_charge!
app/models/spree/order_decorator.rb:6 - block in &lt;top (required)&gt;
app/controllers/spree/orders_controller_decorator.rb:29 - populate
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550949537c992b99eacf44ce?event_id=556ead903f6d8bce636b42b7)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::InvalidForeignKey** in **spree/orders#populate**
PG::Error: ERROR:  insert or update on table &quot;adjustment_metadata&quot; violates foreign key constraint &quot;adjustment_metadata_adjustment_id_fk&quot;
DETAIL:  Key (adjustment_id)=(225242) is not present in table &quot;spree_adjustments&quot;.
: INSERT INTO &quot;adjustment_metadata&quot; (&quot;adjustment_id&quot;, &quot;enterprise_id&quot;, &quot;enterprise_role&quot;, &quot;fee_name&quot;, &quot;fee_type&quot;) VALUES ($1, $2, $3, $4, $5) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550949537c992b99eacf44ce?event_id=556fecc474645b276aa1f919)

## Stacktrace

    lib/open_food_network/enterprise_fee_applicator.rb:6 - create_line_item_adjustment
    lib/open_food_network/enterprise_fee_calculator.rb:32 - block in create_line_item_adjustments_for
    lib/open_food_network/enterprise_fee_calculator.rb:31 - each
    lib/open_food_network/enterprise_fee_calculator.rb:31 - create_line_item_adjustments_for
    app/models/spree/order_decorator.rb:164 - block in update_distribution_charge!
    app/models/spree/order_decorator.rb:162 - update_distribution_charge!
    app/models/spree/order_decorator.rb:6 - block in &lt;top (required)&gt;
    app/controllers/spree/orders_controller_decorator.rb:29 - populate

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550949537c992b99eacf44ce?event_id=556fecc474645b276aa1f919)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::InvalidForeignKey** in **spree/orders#populate**
PG::Error: ERROR:  insert or update on table &quot;adjustment_metadata&quot; violates foreign key constraint &quot;adjustment_metadata_adjustment_id_fk&quot;
DETAIL:  Key (adjustment_id)=(231689) is not present in table &quot;spree_adjustments&quot;.
: INSERT INTO &quot;adjustment_metadata&quot; (&quot;adjustment_id&quot;, &quot;enterprise_id&quot;, &quot;enterprise_role&quot;, &quot;fee_name&quot;, &quot;fee_type&quot;) VALUES ($1, $2, $3, $4, $5) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550949537c992b99eacf44ce?event_id=55766094a14d8e2633b9c2a4)

## Stacktrace

    lib/open_food_network/enterprise_fee_applicator.rb:6 - create_line_item_adjustment
    lib/open_food_network/enterprise_fee_calculator.rb:32 - block in create_line_item_adjustments_for
    lib/open_food_network/enterprise_fee_calculator.rb:31 - each
    lib/open_food_network/enterprise_fee_calculator.rb:31 - create_line_item_adjustments_for
    app/models/spree/order_decorator.rb:164 - block in update_distribution_charge!
    app/models/spree/order_decorator.rb:162 - update_distribution_charge!
    app/models/spree/order_decorator.rb:6 - block in &lt;top (required)&gt;
    app/controllers/spree/orders_controller_decorator.rb:29 - populate

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550949537c992b99eacf44ce?event_id=55766094a14d8e2633b9c2a4)

**Comment by RachL** [comment]
Hello @mkllnk is this an error that we still experience? Shall I put it in the bug backlog?

**Comment by mkllnk** [comment]
Not in the last three months.
