### ISSUE TITLE
Order Cycle advanced settings  cannot be changed

### ISSUE THREAD

**Issue by mbudm** [openfoodfoundation/openfoodnetwork#5802]
## Description
Discovered while attempting to recreate locally the issue in #5773 .

In a complex order cycle edit screen, the advanced settings allow you to select filters for all products or the coordinators inventory only. Changing this option and hitting the save and reload button doesn't actually succeed in changing this setting.

## Expected Behavior
The newly selected filter should be retained after saving and reloading

## Actual Behaviour
The existing filter is selected after save and reload

## Steps to Reproduce
- find or create a complex order cycle (with 1+ distributors?)
- edit the order cycle
- select advanced settings
- change the radio button (either way) between 'COORDINATOR'S INVENTORY ONLY' and 'ALL AVAILABLE PRODUCTS'
- click 'Save and Reload Page' button
- page reloads
- open advanced settings again and the option you selected has not saved

## Animated Gif/Screenshot
![5773regression](https://user-images.githubusercontent.com/2467577/88139339-dc057e00-cc32-11ea-8b7b-a58c7c2ca001.gif)

Alternate way: http://recordit.co/EsXA7GN1BY

## Workaround
Paraphrasing from @kirstenalarsen, if an enterprise clones an order cycle that is set to the right setting they should be able to have the new order cycle at that same setting

## Severity
s2 or s3 depending on the viability of the workaround

## Your Environment
Tested on AU staging, AU prod and locally

## Possible Fix
I've also rolled back to 3.1.1 and 3.1.0 and am still seeing the issue, which suggests it is caused by some setting in data. With my remaining time today I'm going to reset my db to test again.
EDIT: After resetting the local db (with local environment at [v3.1.0](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v3.1.0)) the issue was still present

**Comment by kirstenalarsen** [comment]
I'm not sure this is adequate workaround to make this S3 - for a new shop or Hub they cannot change the setting, so for them there is no workaround and they effectively can't use inventory. While it's not a critical feature it is a widely used one. I don't think we can leave this languishing in S3. Have updated to S2 - open to debate :)

**Comment by mbudm** [comment]
I just realised that the existing PR for #5773 includes a fix for this as well. Will leave this open for info, can be closed with that PR.

**Comment by luisramos0** [comment]
Yes, fixed by #5775
