### ISSUE TITLE
v3.1.3 patch release (single PR 5775 to fix issue 5773)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5805]
Steps: 

- [x] Draft release: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-bbe2829b0f57ed6dd0c9
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/v3-1-3/builds/2
- [x] Publish and deploy to AUS server

**Comment by filipefurtad0** [comment]
I've created Fibonacci Hub for release testing, and for testing the PR at hand.

From a previously created Producer (Fricando Farming - has two products with available stock), added the permissions to:

- add to order cycle
- add products to inventory

![image](https://user-images.githubusercontent.com/49817236/88217288-40860480-cc56-11ea-9a9a-0d22ea1d0740.png)

If the advanced setting is set, to only choose products from coordinators inventory, and no products are added to the inventory, no product can be set as "Outgoing":

![image](https://user-images.githubusercontent.com/49817236/88216926-b2aa1980-cc55-11ea-8783-3afe40059a8b.png)

If own products (such as, "product in inventory" - see below) and products from the producer which granted the above permissions are added to the inventory, then it becomes possible to add them to the OC.

- Inventory (visible)

![image](https://user-images.githubusercontent.com/49817236/88226037-6534a900-cc63-11ea-8991-f4ba4e8c4b7e.png)


- Inventory (hidden)

![image](https://user-images.githubusercontent.com/49817236/88226085-75e51f00-cc63-11ea-9134-fba0ea25eadb.png)


This results in only two products available to add to the OC:

![image](https://user-images.githubusercontent.com/49817236/88225599-abd5d380-cc62-11ea-851e-53e37616ecfa.png)


So, one of the products was added, but hidden - so it does not show up, as expected. The other two appear as expected in the shop-front.



Verified as well, that inventory settings (Dashboard) work as expected. Setting "New products must be added to my inventory" removes the possibility of adding "Product not in inventory" (below):

![image](https://user-images.githubusercontent.com/49817236/88220279-aa081200-cc5a-11ea-8c9b-920dfd48dbe4.png)

![image](https://user-images.githubusercontent.com/49817236/88225221-0cb0dc00-cc62-11ea-8baa-980a6f015fc0.png)






Two issues was found:

a) The PR solves the issue at hand, but the error is still visible, after changing package to Producer with Profile Only. Visiting order Order Cycles and choosing the previously open OC shows:

![image](https://user-images.githubusercontent.com/49817236/88227730-f1e06680-cc65-11ea-8c74-daf4d3de98a6.png)


Changing back to Producer Hub solves this.


b) the Order Cycle page of the producer used for these tests seems not to render properly (endless spinner):

![Peek 2020-07-22 21-57](https://user-images.githubusercontent.com/49817236/88228125-9498e500-cc66-11ea-93de-b3099bdfea65.gif)



Release testing notes:

https://docs.google.com/document/d/1aUgbUipkRKzQ6gtdJ2t4s7p3wPPgi9-BYIgLuX0GOug/edit#


Perhaps this release can be deployed, opening the respective issues, for a) and b)? Added the feedback-needed label.

**Comment by luisramos0** [comment]
Filipe, are you using the Producer profile to edit the OC? re a) I dont think a producer only profile will have access to advanced (3 steps) OCs, right? I think it will be an S4 issue to handle the case where advanced OCs are setup but the account is then downgraded to "producer only profile". As far as I understand the test case you have created, it doesnt look like a problem.

re b) can you open dev tools and share the network tab and any errors? If nothing special is seen there, could you share credentials to that user so I can have a look? is it staging UK or staging FR?

I dont think the PR could have caused b) and I think a) is an edge case so I'm going to deploy this release to AUS now.

Thanks for the testing!

**Comment by filipefurtad0** [comment]
Yes @luisramos0,

a) I also think with that package access should not be granted - that's the issue, I think - and an edge case as well so bug-s4 seems appropriate.

b) I don't think it was introduced by the PR, just noticed it by release testing. I'll add the pic below to an issue as well (Error 401):
![image](https://user-images.githubusercontent.com/49817236/88235374-a7b1b200-cc72-11ea-8829-0438557ef54e.png)

Thank you for your feedback.

**Comment by RachL** [comment]
@filipefurtad0 @luisramos0 b) reminds me a bit of: https://github.com/openfoodfoundation/openfoodnetwork/issues/4544 how many enterprise does your user have Filipe?

**Comment by filipefurtad0** [comment]
b) is from a profile-only producer, with products on one enterprise only. 
But, yes it does look similar with that issue. However, here error 401 is visible, which appearently does not occur - at least it's not visible in the pic you shared @RachL :
https://user-images.githubusercontent.com/6525576/70423086-1f78f680-1a6d-11ea-86c1-e0c8345582b3.png

**Comment by luisramos0** [comment]
if we can replicate b), I think it deserves an issue :+1:

**Comment by filipefurtad0** [comment]
Thanks @luisramos0 ,
This is being discussed under issue #5831 .
