### ISSUE TITLE
Unable to run Bulk Coop Report

### ISSUE THREAD

**Issue by chezaorchard** [openfoodfoundation/openfoodnetwork#5814]
## Description
When running Bulk Coop Report, long load time and then snail no grow system error page displayed. Report not generated.

![Screen Shot 2020-07-23 at 3 23 35 pm](https://user-images.githubusercontent.com/68367600/88257530-4553c280-cd01-11ea-83bb-c8527f55a076.png)

## Expected Behavior
When customer Terra Nadra (2864) normally run this report monthly, the report generates almost immediately.

## Actual Behaviour
Report not generating at all, snail system error page displayed.

## Steps to Reproduce
Can reproduce with multiple enterprises (1965, 119) and for a different/shorter date range (21/07 - 23/7).
 
1. Navigate to Bulk Coop Report
2. Enter date range (26/6 - today)
3. Click Generate Report
4. Waiting for openfoodnetwork.org.au displayed
5. Snail System Error page displayed after about 6 mins

## Workaround
No workaround

## Severity
S2 - no workaround, hub requires report

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used: Version 84.0.4147.89
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): desktop

**Comment by sauloperez** [comment]
@chezaorchard where those steps to reproduce done as superadmin or as manager of an affected hub? Superadmins get many more results than a hub manager and so numbers can't be compared.

**Comment by sauloperez** [comment]
I opened https://github.com/openfoodfoundation/openfoodnetwork/pull/5815 to mitigate this but there's no magic solution :man_shrugging: it will improve things a bit but that's all. Reports have a response time that grows linearly with the number of line items the hub has (more or less).

**Comment by RachL** [comment]
Yes if this happens as super admin, we cannot unfortunately spend time on it for now.  But good candidate to be taken into account for the report work ping @lin-d-hop

**Comment by Matt-Yorkley** [comment]
Probably a data issue with one of the orders / line_items / variants. It's only affecting this specific hub and this specific date range, right?

**Comment by sauloperez** [comment]
> Probably a data issue with one of the orders / line_items / variants. It's only affecting this specific hub and this specific date range, right?

It'd be great news if it was that.

**Comment by chezaorchard** [comment]
When I logged the bug I was able to replicate the error for multiple hubs, and for different date ranges, including a single day.

I've logged in as the affected enterprise to attempt and replicate it again just now and the report is slow to generate but it is running.

**Comment by luisramos0** [comment]
>>> When I logged the bug I was able to replicate the error for multiple hubs, and for different date ranges, including a single day.

Re "I was able to replicate the error for multiple hubs", did you 1) run the report as super admin for multiple enterprises and could see the error or 2) did you login as those enterprises and hit the problem?

1) is not an S2.
2) could be an S2.

**Comment by chezaorchard** [comment]
@luisramos0, I was logged in as super admin at the time - have taken on board your earlier comment re making sure I test logged in as actual enterprises - thank you! As above, the report seems to be running now for the affected enterprise. So, 1. is not an S2

**Comment by sauloperez** [comment]
It's still possible that there's an inconsistent line_item that makes the report crash but one that doesn't belong to this enterprise. However, if the enterprise manager can get the report again, I'd close the issue. We know performance is a major concern in reports and falls out of the scope of this issue IMO, although we improved noticeably already.

**Comment by RachL** [comment]
Yes let's close and reopen if we know a specific enterprise cannot reach the report again 👍
