### ISSUE TITLE
Stripe-SCA payment do not include ship/transaction fees (on a second payment attempt)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5816]
## Description

PR #5798 introduced changes to address the bug described in issue #5774. This relates to incorrect payment amounts processed by Stripe payments, after a first failed attempt, due to an invalid card. These incorrect payment amounts relate to transaction and shipment fees, set by the shop.

It was verified that this PR solves the issue for Stripe-Connect but that the issue persists with Stripe-SCA, namely it what concerns enterprise fees - which is the scope of the present issue.

## Expected Behavior

After a failed payment attempt, a successful payment should cover the total value of the order, including fees.

## Actual Behaviour

After a failed payment attempt, a successful payment does not cover the total value of the order: transaction fees remain marked as "Balance Due (€xx)".

## Steps to Reproduce

Admin
1. Set a transaction for Stripe-SCA and a shipment fee. Open an OC with these payment and shipment methods.

Customer
2. Insert items in the cart, from the above mentioned OC, proceeding to checkout.
3. Choose Stripe-SCA as payment method and Insert the invalid card 4000000000000069 (Charge is declined with an expired_card code)
4. Insert a valid test card (with or without 3D-authentication)
5. Check the total value of your order on the order confirmation

Admin
6. Compare the order total with:
i) Stripe Dashboard
ii) /orders page

Verify the values don't match with the order total. In i) and ii) it should be visible that:

Total order amount = charged amount + transaction fee

Depending on the card used, a failed payment may appear as well under:
iii) /admin/orders/Rxxxxxxxxxxx/payments

## Animated Gif/Screenshot

- Stripe Dashboard:

![image](https://user-images.githubusercontent.com/49817236/88279281-b5e7e880-ccdb-11ea-91ae-e7dd4f9357c9.png)

- /orders page (Admin):

![image](https://user-images.githubusercontent.com/49817236/88279317-c26c4100-ccdb-11ea-87df-117ccbc6ce45.png)

## Workaround

No workaround

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: Observed while testing PR #5798, which should integrate v3.2.0
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

Perhaps related to #5818 .

**Comment by luisramos0** [comment]
I cant replicate this locally with sample data and my stripe account.
I follow "Steps to Reproduce", I pay with card 424242424242 on the second attempt and I get the correct values.

![image](https://user-images.githubusercontent.com/1640378/88413131-91226c80-cdd2-11ea-955a-65a1da555dda.png)
![image](https://user-images.githubusercontent.com/1640378/88413148-97b0e400-cdd2-11ea-8c86-ccc371734289.png)
![image](https://user-images.githubusercontent.com/1640378/88413172-a0091f00-cdd2-11ea-8fa1-c7f48847ca67.png)

**Comment by luisramos0** [comment]
please ignore previous comment, I tested with StripeConnect...
It was the right start, I just forgot to try stripeSCA afterwards :face_with_head_bandage:

**Comment by luisramos0** [comment]
I can replicate this with sample data. I can also replicate it in v2, it's not a regression.
A PR is on it's way :+1:
