### ISSUE TITLE
Release v3.2.0 Feebonaci

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5823]
Steps: 

- [x] Include translations
- [x] [New v3.2.0 release draft](https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-60ad8bac5845e70063fc)
- [x] Notify #instance-managers of user-facing changes.
- [x] Please test this specific build: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1601
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by RachL** [comment]
Alright I've followed basic release testing + the tests done on #5780 . Everything looks good to go!

**Comment by RachL** [comment]
@luisramos0 are we keeping this one open because of the FR deployment tomorrow?

**Comment by luisramos0** [comment]
ah, no, I forgot to close this :+1: 

we have #5637 for the roll out.
