### ISSUE TITLE
Voiding an initial payment (i.e. a full refund) after partially refunding the order is not possible with Stripe-SCA

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5829]
## Description

Orders payed with both Stripe-Connect and Stripe-SCA allow to perform a partial refund of the order (after removing some items). However, after this partial refund, voiding the initial payment of the order is still possible in Stripe-Connect, but fails with Stripe-SCA.

## Expected Behavior

In both payment methods, voiding of the initial order payment should be possible, after a partial refund. This should be reflected on the Stripe-Dashboard:

Initial payment:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/9bfba9fa-b5e2-49a3-98bd-bbd73c50b116)

After partial refund:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/4d3c0f86-2bc5-43c5-9155-e9baa1f50908)

After voiding the initial payment:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/d214ae37-90db-4c3f-8c26-9b73756e8e6f)

## Actual Behaviour

Only with Stripe-Connect it is possible to void of the initial payment of the order, after a partial refund. With Stripe-SCA this operation yields the error "Refund amount (€xxx) is greater than unrefunded amount on charge (€xxx)

## Steps to Reproduce

Customer (or Admin, in the BO)
1. Place an order with several items, using Stripe-SCA as a payment method.

Admin
2. Edit the respective order, remove some items.
3. Go to Payments - there should be a given amount in credit owed.
4. Press "Credit" on the initial payment of the order. A second entry should appear under Payments.
5. Now, on the first (initial) payment, press the X (void payment). See the error.

## Animated Gif/Screenshot

After partial refund, and attempting to void the original payment:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/da4b2e46-6a30-49b9-b4e6-d89f86dec4d9)

## Workaround

Cancelling the order is maybe an option, but it does not provide the refund through Stripe.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.1.3
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

Observed while testing #5780 but apparently not related to this PR. Also appears independent of applying transaction fees.

**Comment by luisramos0** [comment]
I agree with S3 :+1:

**Comment by luisramos0** [comment]
I think this will be XS, a couple of hours.
