### ISSUE TITLE
RuntimeError in checkout#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#583]
## Exception in OpenFoodNetwork

**RuntimeError** in **checkout#update**
Phantom Fees

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556eecd5ea1b57dee73cf21e?event_id=556eecd51466b3d831a02c19)
## Stacktrace

```
app/controllers/checkout_controller.rb:64 - check_order_for_phantom_fees
app/controllers/checkout_controller.rb:19 - update
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556eecd5ea1b57dee73cf21e?event_id=556eecd51466b3d831a02c19)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**RuntimeError** in **checkout#update**
Phantom Fees

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556eecd5ea1b57dee73cf21e?event_id=55758c7d99e09c90326c0c33)

## Stacktrace

    app/controllers/checkout_controller.rb:64 - check_order_for_phantom_fees
    app/controllers/checkout_controller.rb:19 - update

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556eecd5ea1b57dee73cf21e?event_id=55758c7d99e09c90326c0c33)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**RuntimeError** in **checkout#update**
Phantom Fees

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556eecd5ea1b57dee73cf21e?event_id=5577bd288200b68933f60a5d)

## Stacktrace

    app/controllers/checkout_controller.rb:64 - check_order_for_phantom_fees
    app/controllers/checkout_controller.rb:19 - update

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556eecd5ea1b57dee73cf21e?event_id=5577bd288200b68933f60a5d)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**RuntimeError** in **checkout#update**
Phantom Fees

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556eecd5ea1b57dee73cf21e?event_id=557a035346d742a9311fbd03)

## Stacktrace

    app/controllers/checkout_controller.rb:64 - check_order_for_phantom_fees
    app/controllers/checkout_controller.rb:19 - update

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556eecd5ea1b57dee73cf21e?event_id=557a035346d742a9311fbd03)

**Comment by RachL** [comment]
@mkllnk same question here: is this something to treat as a bug or to close because we are not experiencing it anymore?

**Comment by mkllnk** [comment]
Not recently.
