### ISSUE TITLE
Orders not showing on customer order reports 

### ISSUE THREAD

**Issue by chezaorchard** [openfoodfoundation/openfoodnetwork#5835]
## Description
Some customer orders not displaying on report: Order Cycle Customer Totals, for Prom Coast Food Collective (1965)
Order numbers not appearing seem to be those affected by V3 bugs where shipping, payment or admin fees have dropped off an order.

## Expected Behavior
All customer orders for a given period should display in the Order Cycle Customer Totals report

## Actual Behaviour
Orders were missing from the Order Cycle Customer Totals report - discovered when reconciling against Stripe payment report for the same period.

## Steps to Reproduce

1. Logged in as Prom Coast Food Collective
2. Generated Order Cycle Customer Totals report for July
3. Matched totals in report to totals in stripe report
4. Notice line items that don't match - adjust in order to reconcile and realise rows are missing for some orders. Row exists on stripe payment report, row does not exist in Order Cycle Customer Total report

## Workaround
Orders are listed in listing orders screen and can be found by searching for the order number.

## Severity
<!-- Assign a label and explain the impact.

bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: Version 84.0.4147.89
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Desktop 

*Chez to test and make notes if this is the same case for other Enterprises and order numbers affected by 5774

**Comment by kirstenalarsen** [comment]
@chezaorchard are you sure this isn't a date thing or something? I have just tried about 15 orders from the tracking spreadsheet (including all the Prom Coast ones) and I am getting them all in the on screen result of the Order Cycle - Customer Totals report (as super-admin).

Can you give me an order number that is not appearing for you?

**Comment by chezaorchard** [comment]
@kirstenalarsen and @luisramos0 - order numbers that did not appear in the July Customer Totals report that I ran where the following:
R314228858
R038117225
R410335530
R706775248
R658448253
R223614724
R624646775

I feel like a crazy person - I've just run the report again twice (logged in as both the enterprise and super admin) and all those order numbers are there. No longer able to replicate this bug.

**Comment by luisramos0** [comment]
Hello @chezaorchard you are not crazy, it's just how computers work. They have their logic, we just don't get what is that logic sometimes. I mean, something must have changed between the exact parameters you run or maybe in the internals of system (could still be a bug of some sort).

I guess we should close this. We can reopen if it happens again?

**Comment by chezaorchard** [comment]
Sounds good @luisramos0 - I'll run for some other enterprises who were affected by other V3 bugs when I'm back on Thursday Aus time and post here if it happens again.

Just in case it's useful see my additional comment about R826807508 above - this was the only way I discovered this happening; because the order number didn't appear in my customer order I looked it up logged in as super admin and discovered the bug

**Comment by luisramos0** [comment]
ok, I will briefly check the other issue now :+1:
