### ISSUE TITLE
Date selector and Distributor ID filters don't work on Bulk Co-op report

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5837]
## Description

Date selector and Distributor ID filters currently don't work on Bulk Co-op report. Displayed results are the same, independently of choice of distributor or date.

## Expected Behavior

It should be possible to filter results on the Bulk Co-op report by date or distributor ID.

## Actual Behaviour

None of these filters work.
## Steps to Reproduce

Best observed as superadmin
1. Go to Reports and Bulk- Coop; choose any sub-report type.
2. Leave the date selector and Distributor ID fields blank, and press "Generate Report"
3. Set a date range and/or a Distributor ID
4. Press "Generate Report" and compare the query results those obtained in point 2 -> they should be identical.  

## Workaround

If the report does not break, the work around is to filter results manually, or in the CSV file

## Severity

Considering the workaround this would be an bug-s3. However, for some hubs, perhaps it is easy to generate a Error 504 - Gateway Timeout, which would just break the report; in these cases, this would be an bug-s2. So, I think maybe a prioritized bug-s3?

## Your Environment

* Version used: v3.1.3
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

Together with poor performance - which was already considerably improved with PR #5815 - this could an additional underlying cause to the bug reported in #5814.

Related to #4747 and to #5032.

Possible v3-regression.

**Comment by luisramos0** [comment]
Thanks Filipe for raising this.
I think this should be S2, must be a simple fix also.

**Comment by RachL** [comment]
@luisramos0 let's maybe wait after v3 roll out is over to see if we need to raise the priority? There is a workaround so I believe it's not an urgent bug for now. We will need to fix it, but we can leave this decision for later?

**Comment by luisramos0** [comment]
sure! I think this must be causing #5814 as well
