### ISSUE TITLE
Upgrade combine_pdf

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5838]
### What we should change and why (this is tech debt)
We can upgrade combine_pdf but it looks like some adaptation needs to be done.

### Context
Broken build here:
https://github.com/openfoodfoundation/openfoodnetwork/pull/5791

### Impact and timeline
Not a big priority.

**Comment by sigmundpetersen** [comment]
This is now on latest. Closing
