### ISSUE TITLE
NoMethodError in spree/user_sessions#create

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#584]
## Exception in OpenFoodNetwork

**NoMethodError** in **spree/user_sessions#create**
undefined method &#x60;completed?&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556efe2bea1b57dee73d0e76?event_id=556efe2b6300df92313e85b7)
## Stacktrace

```
lib/spree/core/controller_helpers/order_decorator.rb:26 - set_current_order
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556efe2bea1b57dee73d0e76?event_id=556efe2b6300df92313e85b7)

**Comment by RachL** [comment]
@mkllnk should we move this to bug backlog or close it?

**Comment by mkllnk** [comment]
This hasn't happened recently. Closing...
