### ISSUE TITLE
Last 40 products not displayed in Incoming Order Cycle

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5840]
## Description
When editing an Order Cycle, Incoming products only displays 151 products for Aus Enterprise New Life Farm. There are 191 products available to this order cycle, and the counter says they have been loaded,  however they are not shown and are not able to be added to the order cycle.

## Expected Behavior
All products available to the Order Cycle should be shown

## Actual Behaviour

The first 151 products are displayed. The counter says 191 of 191 Variants Loaded. But only 151 variants are displayed and there is no option to display more.

## Steps to Reproduce
- Log in as Manager of New Life Farm
- Order cycle: **MR C Thursday 30.07.20** /admin/order_cycles/6020/incoming
- Incoming Products, Expand All, Load All Variants
- Only 151 products shown - last product is Radish
- Additional 40 products are not shown

## Animated Gif/Screenshot
![screenshot - only can see up to 'radish young'](https://user-images.githubusercontent.com/47620442/88742000-59c21000-d184-11ea-9b68-368f1520f6dc.JPG)

## Workaround
No workaround

## Severity
S1 or S2?

Will tag as an S1 - at least until we know more.

**Comment by emilyjeanrogers** [comment]
This issue appears to be similar to previous issue experienced by the same Enterprise in Sep 2019:

https://github.com/openfoodfoundation/openfoodnetwork/issues/4243

**Comment by mkllnk** [comment]
This may be user error. They are seeing 151 products and 191 variants. The new way of counting is probably not familiar.

I let the computer count for me:
```js
$(".exchange-product").length
$(".exchange-product-variant").length
```

**Comment by emilyjeanrogers** [comment]
Agree - I think this user was expecting an error as they'd seen it in the past, and she wasn't familiar with the count of variants, rather than a count of products. May be a UX thing that could be clarified at some point.
