### ISSUE TITLE
Product image sizes in the shop page are not correct for all instances except AUS

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5849]
## Description
All instances except AUS have their image settings set to 100x100 for product small images, the size that is shown on the shop page. But the place holder is adapted for 112x112 images which is the config in AUS.

This is an example from Katuma but it's happening in all instances, all shops.
![image](https://user-images.githubusercontent.com/1640378/89022984-c8d16d00-d31a-11ea-92d7-2e3b6c3f86f3.png)

in France:
![image](https://user-images.githubusercontent.com/1640378/89023726-ed7a1480-d31b-11ea-9efb-5562c6ec4375.png)

The image has been resized to 100x100 and you can see a space between the right side of the image and the end of the placeholder.
In AUS, becausse the images are being resized to 112x112 this is not happening:
![image](https://user-images.githubusercontent.com/1640378/89023099-f0283a00-d31a-11ea-9849-f0d777883975.png)

## Expected Behavior
I think the easiest best way is to just remove the configuration and always use 112x112.

## Actual Behaviour
100x100 is used and it causes the issue.

## Workaround
None afaik.

## Severity
I am not sure. S3?
This is really just a broken config so maybe we can make it an enhancement.

## Your Environment
All prod servers except AUS.

* Version used: v3.2.0 and v2.10.1

## Possible Fix
I found this as I was moving the config from a page in admin to ofn-install. I am now thinking maybe this should not be configurable at all.
Anyway, if we agree we can change the configs to 112x112 everywherre, I think I can fix this as part of https://github.com/openfoodfoundation/ofn-install/pull/645/files

**Comment by lin-d-hop** [comment]
While like 40% of our shop traffic has NO images (mobile) I really can't care about 12px. 

That being said it would be great to standardise to the full size across all servers.

**Comment by RachL** [comment]
> While like 40% of our shop traffic has NO images (mobile) I really can't care about 12px.

@lin-d-hop Maikel is working on the final bits of that branch, so pictures on mobile will soon be a reality ;)

It could be good to trace why the change was made on AU, other than that, the space available is clearly 112x112, so I don't understand why we would stick to 100x100. So I'm ok with the change as well :)

**Comment by mkllnk** [comment]
I don't know but my guess is the the default is 100x100 and that we changed the configuration in Aus a long time ago when the design was made for 112x112. This knowledge was never passed on and so nobody else updated the image settings to fit the design. I didn't set up Germany but I could imagine that @kirstenalarsen copied image settings from Australia after someone noticed.

This is a good reason to standardise these settings. The openfoodnetwork project sounds like a better place for that configuration than ofn-install because the design is defined here.
