### ISSUE TITLE
"min" and "max" are not displayed completely in group buy products on shop front

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5854]
## Description

When a product has a group buy, the inscriptions "min" and "max" are not displayed completely

It happens on En and Ru interface language

## Expected Behavior

"min" and "max"

## Actual Behaviour

"m" and "ma"

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/89131969-76aa6a80-d519-11ea-8e9b-25160a3c21cb.png)

## Your Environment

* Version used: 3.2.0
* Browser name and version: 78.0.2esr
* Operating System and version (desktop or mobile): desktop (linux)

**Comment by romale** [comment]
Starting from Firefox 74.0 version this issue happens.
I've checked on FF versions that NO issue: 66.0.3 (linux), 69.0.3 (win), 70.0.1(win), 72.0.1(win), 73.0(win), 73.0.1(win)
With issue: 74.0(win), 74.0.1(win), 76.0.1(win), 78.0.2 (linux) (other versions i've not checked. Windows and linux)

**Comment by RachL** [comment]
@romale thanks for this issue. It should be covered by the work done currently in this PR by Maikel: https://github.com/openfoodfoundation/openfoodnetwork/issues/5968

So I'm closing here, and we can reopen if the release of this PR does not change anything 👍
