### ISSUE TITLE
Customers: Duplicate customer code doesn't save but doesn't tell me why, need message

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#587]
On Customer Accounts page admin/customers
![image](https://cloud.githubusercontent.com/assets/2911176/7976952/eb8860c8-0ac6-11e5-8a38-6fa13bad6fa6.png)

**Comment by oeoeaio** [comment]
This is particularly an issue when trying to remove a customer code, because this is saved as an empty string rather than null.
