### ISSUE TITLE
[Rails 4.1] Bump acts_as_list to 0.3.0 at least (1 broken spec)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5872]
### What we should change and why (this is tech debt)
We need 0.3.0 for rails 4.1 upgrade.
I wonder if 0.3.0 works with rails 4.0. We should try this in master first.
I think we will need to relax spree_core dependencies list first as done here https://github.com/openfoodfoundation/spree/pull/45

### Context
From rails 4.1 upgrade, broken spec related to enterprise_groups.

### Impact and timeline
rails 4.1. upgrade

**Comment by luisramos0** [comment]
I think this is only breaking one spec in the rails 4.1 build:
spec/features/admin/enterprise_groups_spec.rb:90

**Comment by Matt-Yorkley** [comment]
I just did a quick local test with https://github.com/openfoodfoundation/spree/pull/48 and we can bump to 0.3.0 easily and it seems to be fixed :+1:

**Comment by luisramos0** [comment]
nice, then this can easily be done after bye bye spree is merged :+1:
