### ISSUE TITLE
Stripe payment failed, order did not go through but charge went through to shopper's bank account

### ISSUE THREAD

**Issue by RonellaG** [openfoodfoundation/openfoodnetwork#5874]
## Description

I received an enquiry from a shopper about a charge going through when the order did not go through. It seems that she thought that she had successfully placed her order until she realised Remi's Patch (2444) had not received her order yesterday.

She then realised the payment from her bank account had been made but she never received an Order Confirmation email from our system.

I checked on our system and the order # R273565285 state is a red dot for “payment” and payment status is “failed”. So it is concerning that the payment went through anyway but her order did not. 

## Expected Behavior

Payment should have gone through and status should be "paid"
Order should have gone through to the producer.

## Actual Behaviour

Customer thought she had successfully placed an order. She provided the following details of her order:
Order details – vegetable items from Remi’s Patch, Open Food Networks
Order placed on Tuesday 04.08.20
Credit card payment $55.00
Check out procedure completed as Guest
Order was to be made Thursday 06.08.20 to The Commons"

But the order did not go through to the producer and she did not receive an order confirmation from our system.

Payment from her bank account was made by Stripe.

The order # R273565285 state in our system is a red dot for “payment” and payment status is “failed”. 

<img width="1036" alt="Screen Shot 2020-08-07 at 2 21 20 pm" src="https://user-images.githubusercontent.com/68315791/89611759-4f5cf000-d8c1-11ea-8cfa-92b21ab092d0.png">

<img width="993" alt="Screen Shot 2020-08-07 at 1 48 58 pm" src="https://user-images.githubusercontent.com/68315791/89611850-8e8b4100-d8c1-11ea-9259-701a2f34c3c8.png">

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by mkllnk** [comment]
Order R273565285 was placed 4th August at 18:18 Australian time. The payment failed and Bugsnag logged the error:
> Your card's security code is incorrect.

If that's true, the bank would be very stupid to make the transfer. So either this error is not correct or this is not the right order.

**Comment by mkllnk** [comment]
The user had 9 previous orders, all successful.

**Comment by mkllnk** [comment]
When an order fails, it should get reset to the cart state. But this order is in payment state which is an indicator of something gone wrong.

**Comment by kirstenalarsen** [comment]
![image](https://user-images.githubusercontent.com/2911176/89612889-4a4d7000-d8c4-11ea-9269-063a3990bdb7.png)

From what I can see in Stripe the payment was blocked with incorrect cvc

There is only one recorded transaction and it is this blocked one
![image](https://user-images.githubusercontent.com/2911176/89612962-7d8fff00-d8c4-11ea-892f-cfbc2ff5f0ec.png)

Interestingly when I click inside the transaction it has this message 
![image](https://user-images.githubusercontent.com/2911176/89613025-9a2c3700-d8c4-11ea-85b6-b68c706106b2.png)

@RonellaG it might be worth asking the customer to check that the payment has actually gone through and has not been returned to their account?

**Comment by RonellaG** [comment]
Customer sent another email recalling her experience of placing the order:

"Has there been a slight change to the cart? The way the items were listed in the cart, and how you edit the contents seemed slightly altered from when I last placed an order with Remi (which was a fortnight ago). I didn’t think much of it at the time, but I did edit the contents of my cart, then proceeded to checkout, and then pressed the button to confirm payment/order and the system seemed to freeze for a moment. My recollection is a bit fuzzy, I’m afraid. I’m pretty sure the system told me the purchase had been processed, and then I closed out of the website without thinking any more of it."

**Comment by RonellaG** [comment]
Customer sent another email with transaction details from her bank account.
 
"Miscellaneous debit

Description: V3915 04/08 REMIS PATCH +61432349928

Amount: $55.00

I checked and the last payment I made did not list a mobile phone number. I’ve checked and this is Remi’s mobile number."

**Comment by kirstenalarsen** [comment]
![image](https://user-images.githubusercontent.com/2911176/89651356-26f7e480-d907-11ea-8c3e-6f4ae00b144e.png)

**Comment by kirstenalarsen** [comment]
awaiting user confirmation that the amount definitely has not been returned to her account by Stripe

**Comment by emilyjeanrogers** [comment]
Customer has confirmed that her bank has now returned the amount to her account.
