### ISSUE TITLE
Patch Release 3.2.2

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5876]
Steps: 

- [x] Include translations
- [x] [Draft new release]
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/paypal-patch 
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [ ] Nudge next release manager

**Comment by Matt-Yorkley** [comment]
Ok folks, this patch release is `v3.2.1` plus two commits: one that updates the `Gemfile.lock` to use the new patched paypal gem version,  and one that adds the latest Transifex translations.

**Comment by RachL** [comment]
@Matt-Yorkley This is ready to go!! https://docs.google.com/document/d/17cOZT-dSJTypo5Ypjmxxupr6fZ4SjP75tlJag5nMfUA/edit#
