### ISSUE TITLE
Add tax amount per type of tax on invoices

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5881]
**A bit of context**: 

We have two big users in France (200-300 orders a week) that will start using a POS system in September. Their OFN use will strickly be for "pre-ordering" products (adjustments will be entirely managed on pick-up day with the POS app).

- Let's say Jane does an order on the OFN
- The hub prepares pickup day thanks to OFN
- During pickup time Jane can come pickup their product but also buy other products that some of the 30 producers are bringing extra for pickup day
- When Jane pickups up her order, **the hubs takes the order total on the OFN** (they use bulk invoice printing for that) and add new products but also any adjustments directly in the POS app
- Jane goes home with only one invoice (from the POS app) that gather their OFN pre-order and their final purchase at the location.

In order to do the step in bold _the hubs takes the order total on the OFN & add it to the POS app_ the hubs needs to know the total amount of the order, but also the VAT amount per type of VAT. Indeed otherwise they need to re-enter ALL pre-ordered products on the POS system. With these info they just need to enter the total amount and then they are free to do all adjustments necessary on top of that (removing or adding products etc).

## Description
**- As a:** enterprise user or super user
**- On page:** `/admin/orders?q[s]=completed_at+desc`
**- I want to be able to do:** See tax amount per type of tax on invoices

This means that instead of this:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/a982f179-bb0e-4bdc-bd14-40ffa181c503)

We need new lines (one per VAT type). With FR data it would look like this:

Total VAT: X €
Total VAT 5% : X €
Total VAT 20%: X €
Total VAT 10% : X €
Total VAT 2,1% : X €

Total excl. TAX : X €
Total incl. TAX: X €

**WARNING:** there are 2 invoices templates. For now let's just make changes to the one used in FR.

How each line is named can be base on the string we for the columns here: `/admin/reports/sales_tax`.

## Acceptance Criteria & Tests

*Scenario 1*

1. Login as a hub
2. Go to `/admin/orders?q[s]=completed_at+desc`
3. Select several invoices and hit "print invoices"
4. All invoices on the file should have the new format, with correct values (we can compare to the report)

*Scenario 2*

1. Login as a hub
2. Go to `/admin/orders?q[s]=completed_at+desc`
3. Edit an order
4. Go to action in the top left corner and press "print invoice"
5. The invoice should have the correct format

*Scenario 3*

Same as scenario 1 and 2, but connected as super admin.

**Comment by tschumilas** [comment]
Following this with interest to learn how well it works for this hub.  We have hubs that could learn from this in OFN-CAN.

**Comment by RachL** [comment]
Ok so this is closed by #5986 🎉
