### ISSUE TITLE
Migrate USA server to AWS an OFN AWS account

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5896]
### What we should change and why (this is tech debt)
USA server is in a AWS account that has been contributed / paid for by an Associate. There is increasing nervousness from USA instance manager about not having full control of the server. It need to be migrated to an OFN AWS account 

### Context
USA instance growing fast and insufficient visibility / control / ability to manage the server

### Impact and timeline
Couple of hours work

**Comment by luisramos0** [comment]
Hello, I dont think this should be in OFN project, this is ofn-install work.
I have created this issue some time ago:
https://github.com/openfoodfoundation/ofn-install/issues/646
Can we use 646 instead?

Is it now decided that we are going to stay on AWS? Initially, the plan was to move to another provider.

**Comment by RachL** [comment]
yes @luisramos0 I'm making the change right now :+1:
