### ISSUE TITLE
Can't delete Cloned Order Cycle

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5903]
## Description
Enterprise Willunga Farmers Market (2545) created a clone of an existing order cycle. They were then unable to delete that cloned order cycle. These cloned O/Cs were of the existing O/C called **2020 Week 21**

ERROR:
**An order cycle has been selected by a customer and cannot be deleted. To prevent customers from accessing it please close it instead.**

When logged in as a Manager of the Enterprise we were also unable to delete the cloned order cycle. We created an additional test clone and were unable to delete that either.

To remove the cloned order cycles from the Enterprise's view, we changed their end dates to January 2019. These two order cycles are now no longer visible in the Order Cycle list, and cannot be browsed for as they are more than 90 days ago (is this a bug in itself?). When using the search tool for the names of these order cycles (**COPY of 2020 Week 21**) there are no results. It's not clear if these order cycles still exist.

## Expected Behavior
The Order Cycle can be deleted

## Steps to Reproduce

1. Access Enterprise Willunga Farmers Market as Superadmin
2. Go to Order Cycles
3. Select clone for an existing order cycle
4. Attempt to delete the cloned order cycle

To remove the Order Cycle from view, change the end date to a date well in the past. This Order Cycle disappears and cannot be searched (but does it still exist??) 

## Severity
S3
 
The workaround is to change the end date of the order cycle, which makes it disappear (to somewhere???)

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RonellaG** [comment]
Screen shot of order cycle list view before I tried to replicate the action of duplicating the order cycle. "Copy of 2020 Week 21" was created by Willunga Farmers Market manager.

<img width="979" alt="Screen Shot 2020-08-12 at 4 36 02 pm" src="https://user-images.githubusercontent.com/68315791/90095523-401feb80-dd74-11ea-9a9b-732451a1ae6a.png">

Screen shot of order cycle list view after I duplicated the order cycle.

<img width="992" alt="Screen Shot 2020-08-12 at 4 43 14 pm" src="https://user-images.githubusercontent.com/68315791/90095601-7c534c00-dd74-11ea-8931-028b4f367c92.png">

Screen shot of notification in red when I tried to delete/remove the duplicated order cycle.

<img width="897" alt="Screen Shot 2020-08-12 at 5 02 46 pm" src="https://user-images.githubusercontent.com/68315791/90095623-9856ed80-dd74-11ea-9085-d51d89331383.png">
