### ISSUE TITLE
Customers: show selected Hub on Customers page and enable easy switch to different Hub

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#591]
Once I have selected Hub and is showing Customers, I can't actually see which Hub I selected - and have to reload base page to change hubs. 

![image](https://cloud.githubusercontent.com/assets/2911176/7977185/e237309a-0aca-11e5-96d7-4ef117e5a533.png)

Can we keep the Hub selector showing on the page and enable switching?

**Comment by bingxie** [comment]
@oeoeaio do you know why do we hide the dropdown on purpose at the moment?

**Comment by oeoeaio** [comment]
@bingxie I think it was maybe just to avoid writing the logic to handle updating the customer list. I think if the customer page used the same UI and logic as the Inventory (Variant Overrides) page, that would be good.
On Wed, Jun 15, 2016 at 11:34, Bing Xie <notifications@github.com> wrote:
@oeoeaio [https://github.com/oeoeaio] do you know why do we hide the dropdown on purpose at the moment?
