### ISSUE TITLE
Customers: amend Customer Totals report so that 'tags' displays any Customer tags, separated by commas

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#592]
![image](https://cloud.githubusercontent.com/assets/2911176/7977242/a5e337f0-0acb-11e5-8af6-77b395dd768a.png)

**Comment by kirstenalarsen** [comment]
@sstead Lisa at FC reckons this is right, but I'm not sure that anyone ever did it (suspicious) - can you check that if you put tags against customers in /admin/customers that they actually appear in this report, not just that there's a column there? 

If it's not working, please allocated to @mkllnk when he is back

**Comment by sstead** [comment]
My testing shows that 'customer codes' are included in the report (it looks at which customer was logged in, not what contact email address was given). Tags were not included in the report at all.

Here's the way I setup the codes and tags for these 2 customers:

![image](https://cloud.githubusercontent.com/assets/10843056/9319362/05122e48-4591-11e5-9d09-f7cb57e7408c.png)

Here's what the Order Cycle Customer Totals report gave me:

![image](https://cloud.githubusercontent.com/assets/10843056/9319419/a8680202-4591-11e5-86c2-c20aff311928.png)

...So @mkllnk , it looks like the tags need to be fixed so they carry into this report.

**Comment by sstead** [comment]
You can apply multiple customer codes...

![image](https://cloud.githubusercontent.com/assets/10843056/9319515/991ef1f6-4592-11e5-81bb-2e9743dc1a47.png)
