### ISSUE TITLE
ActiveRecord::InvalidForeignKey in admin/enterprises#destroy

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#593]
## Exception in OpenFoodNetwork

**ActiveRecord::InvalidForeignKey** in **admin/enterprises#destroy**
PG::Error: ERROR:  update or delete on table &quot;enterprises&quot; violates foreign key constraint &quot;enterprise_relationships_parent_id_fk&quot; on table &quot;enterprise_relationships&quot;
DETAIL:  Key (id)=(565) is still referenced from table &quot;enterprise_relationships&quot;.
: DELETE FROM &quot;enterprises&quot; WHERE &quot;enterprises&quot;.&quot;id&quot; = $1

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=556fc0e109d5f0f461a55b87)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:672 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=556fc0e109d5f0f461a55b87)

**Comment by mkllnk** [comment]
Deletion of enterprises is currently not supported.
Suggestions how to solve this are welcome.

**Comment by kirstenalarsen** [comment]
see http://community.openfoodnetwork.org/t/cant-delete-enterprises-shipping-methods-etc/47

**Comment by daniellemoorhead** [comment]
known issues, you can’t delete enterprises, non-urgent - #359 <#359>

**Comment by mkllnk** [comment]
In that case the UI should not allow to delete enterprises instead of displaying a severe error message.

**Comment by MikeiLL** [comment]
I have also come across this bug. Seems like it might be a small fix to either remove the "delete" link or to have the alert box that pops up explain that enterprises cannot currently be deleted. I have created a couple of Enterprises and am also unable to view or edit any information in the Edit page. There are no "owners" set on either of the Enterprises.

**Comment by romale** [comment]
Will this help?
https://stackoverflow.com/a/14182346

because this error with taxonomies deletion too

```
I, [2020-05-05 16:04:37#27767]  INFO -- : Started DELETE "/admin/taxonomies/1" for 127.0.0.1 at 2020-05-05 16:04:37 +0300
I, [2020-05-05 16:04:37#27767]  INFO -- : Processing by Spree::Admin::TaxonomiesController#destroy as HTML
I, [2020-05-05 16:04:37#27767]  INFO -- :   Parameters: {"authenticity_token"=>"oYQ6qnDWSKzo2LYH57loBIW2OXGzUvCfjeA06qz1PWo=", "id"=>"1"}
I, [2020-05-05 16:04:37#27767]  INFO -- : [paperclip] Scheduling attachments for deletion.
I, [2020-05-05 16:04:37#27767]  INFO -- : Completed 500 Internal Server Error in 73.9ms
F, [2020-05-05 16:04:37#27767] FATAL -- : 
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "spree_taxons" violates foreign key constraint "spree_products_primary_taxon_id_fk" on table "spree_products"
DETAIL:  Key (id)=(1) is still referenced from table "spree_products".
: DELETE FROM "spree_taxons" WHERE "spree_taxons"."id" = $1):
  app/controllers/spree/admin/resource_controller.rb:72:in `destroy'
```
