### ISSUE TITLE
Copy emails not arriving (field "Send Copy of All Mails To")

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5933]
## Description

Setting a valid address in the field "Send Copy of All Mails To" does not lead to the delivery of copy emails. So far, this was only verified in staging environments.

## Expected Behavior

The description clearly states "Sends a copy of all outgoing mails to this address. For multiple addresses, separate with commas." 

## Actual Behaviour

No copy emails are delivered, only the expected emails arrive (checked for: order confirmations, test-emails, delivery emails)

## Steps to Reproduce

1. Log in as superadmin
2. Go to Configuration > Mail Method Settings (/admin/mail_methods/edit)
3. Set up (a) valid email addresse(s) in the field "Send Copy of All Mails To"
4. Make sure you click update
5. Refresh the page, making sure changes were saved.
6. Trigger some Emails, like order confirmations, cancellations, deliveries.

## Workaround

Can't think of none, other than manually sending a copy, but I guess the recipient would have to do that... not sure this is a valid workaround.

Updated: as pointed out by @Matt-Yorkley CCing to the support could serve as a workaround. Downgrading to S3.

## Severity

Proposing bug-s3 till we have further info:
- v3-regression?
- is this occurring in production as well?

## Your Environment

- Version used: v3.2.3
- Browser name and version: Firefox 79
- Operating System and version (desktop or mobile): Desktop / Ubuntu 20.04

## Possible Fix

Maybe related to #5932.

**Comment by luisramos0** [comment]
I cannot reproduce this in au staging. It looks fine.
I used master to test it.

**Comment by filipefurtad0** [comment]
That's good news :+1: 
Also @lin-d-hop this to be ok in production.

In that case this is probably something related to my email settings/servers. I'll need to double check. Closing the issue for now.

**Comment by filipefurtad0** [comment]
Exactly, that's it @luisramos0,

This happened because:
i) I was manager of that hub in which the tests were performed and 
ii) I used a customer account I created myself

So, all emails addresses looked like
myemail1234+hub@gmail.com
myemail1234+customer@gmail.com
myemail1234+copyemail@gmail.com

Which all lands in the same account, and Gmail - as you mention Luis - handles this as the same email account, and does not seem to double these.

Thanks for the help testing and clarifying this!
