### ISSUE TITLE
Release v3.2.4 Wild Rice Chili

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5939]
Steps: 

- [x] Include translations
- [x] [release draft](https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-cc6314e2a2aa4c3dc73c) 
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1659
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by lin-d-hop** [comment]
Tested and good to go :)

https://docs.google.com/document/d/1Aigz0S4j8buN9SD0x7lXm7XXp14c9z4HMXlwdSwomGQ/edit#

**Comment by filipefurtad0** [comment]
Hey @lin-d-hop ,
I double-checked this draft as well on checkout issues, since it includes #5905 and found it not to introduce anything which could block the release - all good. It does however introduce a change, which relates to bug #5936 - further commenting on that issue.
