### ISSUE TITLE
Missing translation key en.spree.shipments_states.null

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5945]
## Description

Unfortunately I don't know how to fix it in the code.

## Expected Behavior

Shipping status in client profile -> Transactions should display 'Shipping status'  name

## Actual Behaviour

Exception code

## Steps to Reproduce

1. Client creates order (payment by cash)
2. Enterprise admin click on Capture (at right side of the order) in `/admin/orders`
2.1 Enterprise admin opens client order via Edit and delete product item
3. Client open `/account?locale=en#/transactions#my-enterprise4`
4. "Shipping status" displays `[missing "en.spree.shipments_states.null" translation]`

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/91062743-c15d6500-e635-11ea-846e-56c7e5684dc5.png)

## Your Environment

* Version used: 3.2.3
* Browser name and version: Firefox  78.1.0esr
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment]
thank you so much @romale for taking such a closer look to our translations! Don't hesitate to add the `good-first-issue` label when you create a translation issue: this label is followed by new developers who want to get involved :)

**Comment by romale** [comment]
ok @RachL :)

**Comment by lynnbright** [comment]
Hi @RachL,  I would love to help with this issue for hacktoberfest 😊

**Comment by RachL** [comment]
Hey @lynnbright ! Welcome 🎉 Please go ahead :) 

Have a look at the readme and getting started sections if you haven't already!

**Comment by lynnbright** [comment]
Hi @RachL,

I found out this issue has been solved by this [#6106 PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/6106).
I think this issue can be closed. :)

**Comment by RachL** [comment]
Alright, sorry for that thanks @lynnbright !
