### ISSUE TITLE
Can't Delete Products from Enterprise's Product list

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5947]
## Description
Aus Enterprise Grassroots Beef (975) has several products they wish to delete. In Edit Products, on select of the Trash Icon, the confirmation window appears 'Are you Sure?'. On select 'Yes' to confirm, nothing happens. The product doesn't delete. 

## Expected Behavior
A product can be deleted, or an error message is shown explaining why it can't be deleted.

## Actual Behaviour
Nothing happens - product is not deleted.

The products they want to delete have now been listed as variants of a single Soap product. See image below:

![Screen Shot 2020-08-25 at 2 23 24 PM](https://user-images.githubusercontent.com/47620442/91122978-05f10b00-e6df-11ea-9403-7279ddb7769c.png)

**Maybe related:**

The screen shot above was taken when logged in as Superadmin, and shows that the products that could not be deleted don't have images. This screen shot was taken in Chrome on a MacBook Pro. Tested on Safari as well - also no images.

@chezaorchard took the following screenshot at the same time, also logged in as Superadmin, also using Chrome browser, and the products DO have images. 

![Screen Shot 2020-08-25 at 1 53 04 pm](https://user-images.githubusercontent.com/47620442/91123439-39806500-e6e0-11ea-98b1-59b6dc98c944.png)

## Steps to Reproduce

1. Log in as Superadmin
2. Search for Enterprise Grassroots Beef
3. Use keyword search to find any of the Soap products that are not variants of a top level product (see image above)
4. Try to delete one of these products

## Workaround
The products can not be deleted. There is no workaround. The products can be ignored, but this is highly annoying to the customer.

## Severity
S2

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by emilyjeanrogers** [comment]
Maybe related to https://github.com/openfoodfoundation/openfoodnetwork/issues/5942

**Comment by seanbaker74** [comment]
I experienced this issue after upgrading my test system from 2.9.6 to 3.2.3. Certain products cannot be deleted through the UI, and no error message is provided. The server's production.log file does not provide any useful debugging information.

This issue appears to be related to the addition of the Spree::StockItem code (https://github.com/openfoodfoundation/openfoodnetwork/commit/0e711832fdff9f91ac2e70b9c1038d60cb1961e8)

In the rails console, if I run Spree::Product.destroy on a product that cannot be deleted, I get:
`ActiveRecord::ReadOnlyRecord: ActiveRecord::ReadOnlyRecord`

This issue was reported in Spree: https://github.com/spree/spree/issues/3723

In Spree, it looks like the fix was to remove stock_movements as a dependency to Spree::StockItem.destroy

**Fix:**
In stock_item.rb, change:
`has_many :stock_movements, dependent: :destroy`
to...
`has_many :stock_movements`

On my test system, if I make that change to stock_item.rb, I'm then able to delete those products in the UI.

**Comment by tschumilas** [comment]
Also noting this issue -  and the comment the recent move to V3 brought soft deletion to stock items -  could this have caused the problem of not being able to delete variants that have been ordered ?  https://github.com/openfoodfoundation/openfoodnetwork/issues/5335

**Comment by filipefurtad0** [comment]
I have reproduced this bug in a staging environment. It seems to play a role, whether the stock of the product/variant to be deleted is set to be on_hand or on_demand.

For two newly created products, product A with stock `on_hand` and product B with stock `on_demand`, and after adding them to an open OC, and placing two orders, each order containing either product A or product B, I've observed that:

- the product with stock set to `on_demand` can be deleted - cancelling the respective order reproduces bug #5335 
- the product with stock set to `on_hand` can't be deleted - Error 442 on the console (pic below) Setting this product to on_demand and trying to delete it does not seem to work either.

![image](https://user-images.githubusercontent.com/49817236/92268624-a236c100-eeda-11ea-8a61-de24ec98652c.png)

The image of that product seems broken, after attempting to delete the product, which seems to be causing error 404 on the console.

Hope this is useful to tackle the underlying issue.

**Comment by lin-d-hop** [comment]
On release testing just now I noticed that also Duplicate Product button is not working for some cases.

I am noting here because I have a hunch it is related.... but I don't have the time to investigate properly and create an issue right now.

**Comment by RachL** [comment]
@lin-d-hop we have this known issue here: https://github.com/openfoodfoundation/openfoodnetwork/issues/3808 is that what you have experienced?

**Comment by emilyjeanrogers** [comment]
I am adding further details to be absolutely sure that this issue includes being unable to delete Variants **as well as top level products** from an Enterprise's product list. A top level product can be moved by a Superadmin into a dummy enterprise, but a variant cannot.

Enterprise Grassroots Beef wants to delete a variant of the top level product Offal and Bones. The variant they want to delete is called Brisket Bones:

![Screen Shot 2020-11-04 at 2 37 06 PM](https://user-images.githubusercontent.com/47620442/98066622-ad42a900-1eab-11eb-9968-0e5115aa77da.png)


When I use the trash icon to try to delete the variant using Superadmin it appears to be working, but when you click OK the product just doesn't delete:
![Screen Shot 2020-11-04 at 2 37 22 PM](https://user-images.githubusercontent.com/47620442/98066642-b7fd3e00-1eab-11eb-9f95-abd1457d6018.png)

When I go into Variants and attempt to delete from in there, I get the snail:

![Screen Shot 2020-11-04 at 2 41 20 PM](https://user-images.githubusercontent.com/47620442/98066791-28a45a80-1eac-11eb-86c7-aa4d92164ed3.png)
![Screen Shot 2020-11-04 at 2 41 28 PM](https://user-images.githubusercontent.com/47620442/98066792-2a6e1e00-1eac-11eb-95aa-afa3dd1d1c12.png)


There is no workaround that I'm aware of for deleting a variant. A variant can't be moved to another enterprise. The only option is to set stock levels as zero so it will never appear in a shop - but it will always be there in their product list.

**Comment by tschumilas** [comment]
Just concuring with @emilyjeanrogers (and embarassed I didn't flag when I created the issue).   There is no way to move only one variant to another producer.  So  if a product has many variants -  support team has to assign all of them to a dummy enterprise,  and re-create the entire list of variants,  minus the one variant the producer needs deleted.    Speaking for alread over-burdened support teams -  surely we'd say that this workaround is not realistic,  and make this an s2.
