### ISSUE TITLE
Tagged Customer should not be charged tagged Shipping Method Fee

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5950]
## Description

Customers are being charged shipping method fees when they should not be based on tag rules. They are not shown the fee in their cart, but it appears in the order confirmation screen after paying and is charged to their Credit Card.

The Enterprise has been contacted by 2 customers who have been charged shipping method fees when they are tagged as members and should not be charged those fees. The fees were not displayed in their cart, but did appear in their order confirmation screen after paying, and in their order confirmation emails.

Replicated as a test customer, screen grabs below. See error message under Shipping Info in Shopping Cart.

## Expected Behavior
Shipping Method Fee should not be charged. 
If Shipping Method Fee is charged, it should appear in cart total.

## Actual Behaviour

Enterprise Willunga Farmers Market (2807)
A Shipping Method Fee of 10% is tagged **non-member**
Tag rule is set up that customers tagged **member** should not see shipping methods tagged **non-member**

EXAMPLE 1 - REAL CUSTOMER:

Customer for order R428222545 is tagged as **member**
Order Details on OFN and confirmation email to the customer both confirm that the total order is $137.44 and a $12.04 shipping fee was charged. 
Customer says the shipping fee did not appear in their cart total, but it did appear in their order confirmation email.

EXAMPLE 2 - OFN TEST TRANSACTION on same Enterprise

Customer for order R126884235 is tagged as **member**

**Cart total prior to Paying**
![Screen Shot 2020-08-27 at 10 58 14 AM](https://user-images.githubusercontent.com/47620442/91371921-ab2def80-e855-11ea-9728-83bd4dd3ddc1.png)

**Order Confirmation after Paying**
![Screen Shot 2020-08-27 at 11 01 06 AM](https://user-images.githubusercontent.com/47620442/91371952-b97c0b80-e855-11ea-8271-0f20d9172e6f.png)

## Steps to Reproduce
Unable to replicate using a test account. Customer tagged member did not see, and was not charged the tagged shipping method fee.

CAN Replicate by creating a test customer for Willunga Farmers Market, tagging customer as member, and carrying out a test transaction in the shop.

## Workaround
No workaround. Member customers are being charged a fee that is a) not supposed to be charged to them and b) not appearing in their cart prior to confirmation of payment.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by mkllnk** [comment]
I noticed that the enterprise has only one shipping method for customers tagged `non-member`. I would have thought that you need another (free) shipping method for members.

**Comment by mkllnk** [comment]
The problem is the missing shipping method for members. Creating a new shipping method tagged for members solves the problem. So this issue can be reframed as:

*A missing shipping method due to tags selects the wrong shipping method during checkout and charges wrong fees*

The system warns if you don't have a shipping method set up and doesn't show the shop as open (not ready for checkout). But this check seems to fail when there is a shipping method that can't be applied because of a tag rule.

**Comment by mkllnk** [comment]
I created the missing shipping method.

**Comment by kirstenalarsen** [comment]
Seems like this has been solved and should be closed? @mkllnk @RachL Please reopen if I have this wrong
