### ISSUE TITLE
Are the buttons in the Order/Edit out of order?

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5956]
## Description

In path '/admin/orders/R804637286/edit' and '/admin/orders/R804637286/adjustments'
In the screenshot of the user manuals, the order buttons are placed horizontally, and in my case somehow vertically, which in my opinion is not very nice. Is this a bug or a feature?

## Expected Behavior

horizontally buttons placed

## Actual Behaviour

vertically buttons placed

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/91438571-4209a480-e874-11ea-9d90-d04a0c9f908a.png)

![image](https://user-images.githubusercontent.com/928628/91438972-e986d700-e874-11ea-82f9-867cb4351c39.png)

## Your Environment

* Version used: 3.2.4
* Browser name and version: Firefox 78.1.0esr (linux)
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment]
@romale thank you for this issue! I accidentally created the same here: https://github.com/openfoodfoundation/openfoodnetwork/issues/6006 I've merged our two content over there so I'm closing here.
