### ISSUE TITLE
Strange default message showing in shop tab for open shop

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#5959]
## Description

For producer stores on OFN-CAN -  a default message is showing on their shop tab.  See picture below.  We've set up several test producer shops and it happens every time there are 2 order cycles created with the dropdown.  And,  the dropdown is in a red box,  not the teal box. 

## Expected Behavior

The two order cycles for a producer shop should behave the same as the two order cycles for a hub shop.  Teal box,  drop down,  and no message in the shop tab.  (The message in the home tab works fine.)

## Actual Behaviour

Strange message in shop tab.

## Steps to Reproduce

1. set up a producer - sells own -  enterprise
2.create 2 order cycles
3.see the message?
4.

## Animated Gif/Screenshot

![Screen Shot 2020-08-27 at 12 40 16 PM](https://user-images.githubusercontent.com/13171778/91471219-c142ac80-e863-11ea-8fc4-d5480086ea52.png)

## Workaround

No workaround that we know about.

## Your Environment

On desktop -  haven't looked on mobile yet.  

* Version used:
* Browser name and version:  Chrome - latest

* Operating System and version (desktop or mobile):
Desktop

**Comment by JessChen0** [comment]
Same issue on mobile and on firefox (desktop).   See mobile screenshot below.  The message occurs on the 2nd tab in "shop".

![Screenshot_20200827-130225](https://user-images.githubusercontent.com/57812482/91472996-45962f00-e866-11ea-869f-dc6cf69167f2.png)

**Comment by sigmundpetersen** [comment]
I don't know if this is the problem you are describing, but there seems to an error in Transifex in the shop message (key: shop.messages.select_oc.select_oc_html). There is some special formatting that should be kept from the original key that isn't.

**Comment by tschumilas** [comment]
I found the key and translated it properly -  thanks.   But how did this happen?  Will other instances be affected or should I close this issue?

**Comment by sigmundpetersen** [comment]
The original string contains HTML content (https://docs.transifex.com/translation/html-files). These should be preserved in the translated string but can be broken if one is not careful.

I saw that for the specific string in question the HTML was removed in the translated string. I don't know if this was intentional, I can help bring them back if you want.

**Comment by tschumilas** [comment]
Hmmm -  so -  I just did a 'regular' translation no HTML portion -  so I bet this isn't right.   Would you be able to help me fix this @sigmundpetersen ?

**Comment by luisramos0** [comment]
I confirm, it's a CA transifex problem. Translators should use the copy icon in transifex when there are special contents in the string to be translated and be careful to keep them.

Closing as we dont track these issues on GH. I wonder if there is something we can do to prevent these problems in the future.
