### ISSUE TITLE
Errno::ENOMEM in admin/enterprises#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#596]
## Exception in OpenFoodNetwork

**Errno::ENOMEM** in **admin/enterprises#update**
Cannot allocate memory - identify -format &#x27;%wx%h,%[exif:orientation]&#x27; &#x27;/tmp/9c4d696319116e01810498dcc3f5bef620150604-30298-1l5w4uy.PNG[0]&#x27; 2&gt;/dev/null

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=556ff9a674645b276aa22cfa)
## Stacktrace

```
gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:21 - call
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=556ff9a674645b276aa22cfa)

**Comment by mkllnk** [comment]
This looks like we have to limit the size of images people can upload. There are also handy JavaScript libraries that allow to scale images on client side.

@RohanM It looks like the server is using a lot of swap. Currently:
````
  System load:  0.85               Processes:           100
  Usage of /:   58.4% of 19.69GB   Users logged in:     0
  Memory usage: 70%                IP address for eth0: 10.240.79.12
  Swap usage:   75%
````
Do we need to upgrade our server?

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**Errno::ENOMEM** in **admin/enterprises#update**
Cannot allocate memory - identify -format &#x27;%wx%h,%[exif:orientation]&#x27; &#x27;/tmp/545c113d6ebbde700245e73ad4641c1520150605-7304-7g4s5s.PNG[0]&#x27; 2&gt;/dev/null

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=55711130682ebf1033a6b3fd)

## Stacktrace

    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:21 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=55711130682ebf1033a6b3fd)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**Errno::ENOMEM** in **spree/admin/images#create**
Cannot allocate memory - identify -format &#x27;%wx%h,%[exif:orientation]&#x27; &#x27;/tmp/c0fc7f75ea8d2698427cfe4bf0e29dde20150709-14859-16tzd4i.jpg[0]&#x27; 2&gt;/dev/null

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=559de14e8f1b59d82e376432)

## Stacktrace

    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:21 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=559de14e8f1b59d82e376432)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**Errno::ENOMEM** in **spree/admin/images#create**
Cannot allocate memory - identify -format &#x27;%wx%h,%[exif:orientation]&#x27; &#x27;/tmp/6b9b611799663da664ee7ed46862cc7d20150817-9503-oh0539.jpg[0]&#x27; 2&gt;/dev/null

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=55d18ec0135326f9348d76e5)

## Stacktrace

    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:21 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=55d18ec0135326f9348d76e5)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**Errno::ENOMEM** in **spree/admin/images#create**
Cannot allocate memory - identify -format &#x27;%wx%h,%[exif:orientation]&#x27; &#x27;/tmp/163a8bf3ef33acd994b5b3bd5d7776b320150824-21726-kyaqec.pdf[0]&#x27; 2&gt;/dev/null

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=55da8759c60ae3634f4d8803)

## Stacktrace

    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:32 - spawn
    gems/cocaine-0.5.7/lib/cocaine/command_line/runners/process_runner.rb:21 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/556ff860ea1b57dee73ea497?event_id=55da8759c60ae3634f4d8803)

**Comment by stveep** [comment]
@mkllnk @pmackay a build of one of my branches on UK staging had some similar errors, see log from @lin-d-hop here:

http://community.openfoodnetwork.org/t/customers-can-view-their-payments-and-balance/308/23

The issue seems to be with the order cycle factory, which involves an image as the original issue did here. Did you get to the bottom of it? Is our server just out of memory? These specs ran fine for me locally and in the Travis build.

**Comment by mkllnk** [comment]
Hi @stveep @pmackay @lin-d-hop 

Sorry, that is our fault. Since Travis is building very reliably and fast now, we deactivated testing on our Buildkite project. Without thinking about you still building on our CI server, we downscaled the server. It actually has not enough memory to run the tests any more.

Is it okay for you to rely on Travis for tests? You can still deploy through Buildkite.

Sorry for the confusion.

**Comment by lin-d-hop** [comment]
Thanks @mkllnk We'll use Travis for running tests now :-)

**Comment by RachL** [comment]
@mkllnk is this what you were mentioning here: https://github.com/openfoodfoundation/ofn-install/issues/355#issuecomment-477451058

Should we treat it as a bug or tech debt?

**Comment by mkllnk** [comment]
Yes, it's what I mentioned there. This hasn't happened recently though. Let's close it.
