### ISSUE TITLE
Release v3.2.5 Sobao

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5962]
Steps: 

- [x] Include translations
- [x] [Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1680
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by RachL** [comment]
@sauloperez it is looking good! I'm moving to ready to go :) https://docs.google.com/document/d/1Yf-JEzmE0FYNOsIXv7g7zJebN3UrLFTgtdHdLYHx8sk/edit#

**Comment by luisramos0** [comment]
done :heavy_check_mark:

**Comment by sauloperez** [comment]
ah ok. I was about to do it now.

**Comment by luisramos0** [comment]
oh, I am sorry, I thought I was meant to do this today. I think I mixed up with having to prepare the release on Thursday, sorry!
