### ISSUE TITLE
TypeError in gems/rack-1.4.5/lib/rack/request.rb:221

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#597]
## Exception in OpenFoodNetwork

**TypeError** in **gems/rack-1.4.5/lib/rack/request.rb:221**
can&#x27;t convert nil into Hash

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54c077ce99b2cdc8b88d48d6?event_id=556ffe321aa9463f452dcc96)
## Stacktrace

```
gems/rack-1.4.5/lib/rack/request.rb:221 - merge
gems/rack-1.4.5/lib/rack/request.rb:221 - params
bundler/gems/spree-afcc23e489eb/core/lib/spree/core/middleware/seo_assist.rb:12 - call
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54c077ce99b2cdc8b88d48d6?event_id=556ffe321aa9463f452dcc96)

**Comment by mkllnk** [comment]
This one is a really hard one to track down. The cause of this issue is not visible in the stack trace. See https://github.com/rack/rack/issues/430 for other people's experiences. It seems to be triggered by certain POST input data, for example image uploads. An upgrade of rack to 1.5.2 or higher could help. It might be related to #596.

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**TypeError** in **gems/rack-1.4.5/lib/rack/request.rb:221**
can&#x27;t convert nil into Hash

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54c077ce99b2cdc8b88d48d6?event_id=55711caa16542133405d32fa)

## Stacktrace

    gems/rack-1.4.5/lib/rack/request.rb:221 - merge
    gems/rack-1.4.5/lib/rack/request.rb:221 - params
    bundler/gems/spree-afcc23e489eb/core/lib/spree/core/middleware/seo_assist.rb:12 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54c077ce99b2cdc8b88d48d6?event_id=55711caa16542133405d32fa)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**TypeError** in **gems/rack-1.4.5/lib/rack/request.rb:221**
can&#x27;t convert nil into Hash

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54c077ce99b2cdc8b88d48d6?event_id=55bb2c1f5c4a41014f661d2d)

## Stacktrace

    gems/rack-1.4.5/lib/rack/request.rb:221 - merge
    gems/rack-1.4.5/lib/rack/request.rb:221 - params
    bundler/gems/spree-afcc23e489eb/core/lib/spree/core/middleware/seo_assist.rb:12 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54c077ce99b2cdc8b88d48d6?event_id=55bb2c1f5c4a41014f661d2d)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**TypeError** in **gems/rack-1.4.5/lib/rack/request.rb:221**
can&#x27;t convert nil into Hash

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54c077ce99b2cdc8b88d48d6?event_id=5629881639c3c7942ea6f247)

## Stacktrace

    gems/rack-1.4.5/lib/rack/request.rb:221 - merge
    gems/rack-1.4.5/lib/rack/request.rb:221 - params
    bundler/gems/spree-afcc23e489eb/core/lib/spree/core/middleware/seo_assist.rb:12 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54c077ce99b2cdc8b88d48d6?event_id=5629881639c3c7942ea6f247)

**Comment by RachL** [comment]
@mkllnk same here, sorry to tag you on all those issues again. There is no rush so look at them when you have the time ;)

**Comment by mkllnk** [comment]
It's easy to look them up. And I enjoy a clean out. I would feel much better with less than 100 issues open instead of 500.
