### ISSUE TITLE
After updating/mofication of a product (only) -->return to OFN home page and not to the dashboard or the updating's page

### ISSUE THREAD

**Issue by SophieDuponcheel** [openfoodfoundation/openfoodnetwork#5975]
## Description

When you update or modify a product in the dashboard, after its update, you return to the home page of the OFN site (and not to the page concerning the product in the dashboard).

It's very annoying because after that you have to go back to the dashboard, in the "product" tab, etc.

## Expected Behavior

you should find the product sheet in the dashboard, not go back to the home page of the platform.

## Actual Behaviour

We go back to the home page of the plateform.

## Steps to Reproduce

1. Go to product tab
2. Click on modify the product
3. Modify something (ex : product's name, price, etc.)
4. update/save the modification 
5. automatically we come back to the home page 

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/63047606/91859233-7b725380-ec6a-11ea-9d45-9662d21414c0.png)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
This will be fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/5722 as there will be no more new window.

**Comment by RachL** [comment]
Yes this is now fixed :tada:
