### ISSUE TITLE
REXML::ParseException in POST /orders/populate

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#598]
## Exception in OpenFoodNetwork

**REXML::ParseException** in **POST /orders/populate**
The document &quot;{&quot;variants&quot;:{&quot;750&quot;:{&quot;quantity&quot;:5,&quot;max_quantity&quot;:null},&quot;1646&quot;:{&quot;quantity&quot;:5,&quot;max_quantity&quot;:null},&quot;1739&quot;:{&quot;quantity&quot;:5,&quot;max_quantity&quot;:null},&quot;1968&quot;:{&quot;quantity&quot;:2,&quot;max_quantity&quot;:null},&quot;4136&quot;:{&quot;quantity&quot;:5,&quot;max_quantity&quot;:null},&quot;4144&quot;:{&quot;quantity&quot;:5,&quot;max_quantity&quot;:null},&quot;4148&quot;:{&quot;quantity&quot;:4,&quot;max_quantity&quot;:null},&quot;4150&quot;:{&quot;quantity&quot;:5,&quot;max_quantity&quot;:null},&quot;4154&quot;:{&quot;quantity&quot;:5,&quot;max_quantity&quot;:null},&quot;4787&quot;:{&quot;quantity&quot;:2,&quot;max_quantity&quot;:null},&quot;6552&quot;:{&quot;quantity&quot;:2,&quot;max_quantity&quot;:null}}}&quot; does not have a valid root

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550b5cafd4955826960202da?event_id=55767fda94b95c20047c54eb)
## Stacktrace

```
gems/activesupport-3.2.21/lib/active_support/xml_mini/rexml.rb:35 - parse
gems/activesupport-3.2.21/lib/active_support/xml_mini.rb:80 - parse
gems/activesupport-3.2.21/lib/active_support/core_ext/hash/conversions.rb:98 - from_xml
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550b5cafd4955826960202da?event_id=55767fda94b95c20047c54eb)

**Comment by mkllnk** [comment]
This bug prevents some iPad/iPhone users to place an order. The problem seems to be that the browser doesn't send `Content-Type: application/json` when sending an order as JSON.

**Comment by mkllnk** [comment]
Identified only three affected users in the last three months. Their user agents said they are:
```
iPhone  OS 8_1_2    Safari 600.1.4
iPad      OS 8_1_3    Safari 600.1.4
iPad      OS 8_3        Safari 600.1.4
```
That's all Safari on mobile iOS 8.

**Comment by RachL** [comment]
I don't believe we still support iOS 8. If we do or are still experiencing those errors, we can reopen this.
