### ISSUE TITLE
Missing translation key "shipping method" in Order->Edit

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5993]
## Description

When creating Order manually.

All keys with the phrase "shipping method" are translated, but in RU interface the same phrase "shipping method" (Order->Edit->Shipping/Edit) is shown not translated. Missing translation error is not shown. Then I added a counter to all phrases "shipping method" in en.yml, for example "shipping method1", "shipping method2", etc., but these phrases with numbers did not appear in the place circled in red either.

## Expected Behavior

"shipping method" should be tranlsated

## Actual Behaviour

Not translated

## Steps to Reproduce

1. Edit order /admin/orders/R815774803/edit#
2. Click on Edit (shipping method)
3. 
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/92267811-f301e600-eee9-11ea-8c32-c7f7c4b728e0.png)

## Your Environment

* Version used: 3.2.5
* Browser name and version: 78.1.0esr
* Operating System and version (desktop or mobile): Desktop (linux)

**Comment by tsara27** [comment]
Hello @romale and @RachL,

I am sure that I can solve this issue. Can you please assign this issue to me if no one take this issue?

Thanks!

**Comment by RachL** [comment]
@tsara27 here you go! Don't hesitate to ask if you have question :)

**Comment by tsara27** [comment]
Hello @romale,

I hope you are doing well! I have made pull request for this issue.
Please let me know if you have question. :slightly_smiling_face:

**Comment by romale** [comment]
> Hello @romale,
> 
> I hope you are doing well! I have made pull request for this issue.
> Please let me know if you have question. slightly_smiling_face

many thanks @tsara27 !
