### ISSUE TITLE
Intermittent errors with Amazon S3 images (staging-UK)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5999]
## Description

These errors have been observed in an intermittent way - they don't always occur:

- Adding new product with an image results error 500. Creating a product with no image works, so this seems to relate to images in S3 and possibly introduced by #5869 . Error relates to the [Bugsnag alert](
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5f3c11474cbbc5001823940e?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&event_id=5f563a53005e08be08e90000):

```
ArgumentErrorspree/admin/products #create
bucket_name may not be blank1 minute agoSep 7th, 14:49:07 GMT+1 | staging |  
-- | -- | --

```

- Images in Products are down, after page refresh. Refreshing a few more times brings the images back. Refreshing again breaks them.

This was observed on staging-UK. I could not reproduce on other staging servers (all busy as of writing). I am not sure this relates with the S3 settings in staging-UK.

I'm flagging this as it could be a release blocker.

## Expected Behavior

- It should be possible to add images with Amazon S3 enabled.
- Images should be displayed correctly in Products page

## Actual Behaviour

Intermittently:
- Error 500 is observed when attempting to add images with Amazon S3 enabled.
- Images should be displayed correctly in Products page

## Steps to Reproduce

Make sure Amazon S3 images is enabled.

- Error 500
1. Create a new product.
2. Fill out the necessary information
3. Add an image in a supported format (jpg, png,...)
4. Click on Create

- Images on Products page
1. Go to a profile/producer with images
2. Go to Products page
3. Hit refresh a couple of times

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/92366394-0204b600-f0ed-11ea-9ebb-7283684353ee.png)

![image](https://user-images.githubusercontent.com/49817236/92367733-b7843900-f0ee-11ea-919f-ab9b4621c91c.png)

After a pressing F5 a few times - no setting changes in between.

![image](https://user-images.githubusercontent.com/49817236/92367806-cf5bbd00-f0ee-11ea-89f8-345a8e69ba80.png)

Gif below shows Admin tab (left) and Customer (right), while pressing F5 repeatedly. See how images switch from being broke to being ok. This is only observed when Amazon S3 images are enabled:

![refreshin_images](https://user-images.githubusercontent.com/49817236/92383345-0ee1d380-f106-11ea-94ea-bfce67065450.gif)

Console:

![image](https://user-images.githubusercontent.com/49817236/92386053-ed371b00-f10a-11ea-9488-84dddc82c68f.png)

## Workaround

?

## Severity

Potentially an S2, but not unsure this happens outside staging-UK.

## Your Environment

* Version used: release draft v3.2.6, on staging-UK
* Browser name and version: Firefox 80 and Chrome 75 (on mobile)
* Operating System and version (desktop or mobile): Desktop, Ubuntu 20.04

**Comment by filipefurtad0** [comment]
This issue is reproducible on different staging servers, and points out to the configuration of S3:

![image](https://user-images.githubusercontent.com/49817236/92397235-668c3900-f11e-11ea-8aba-c64e5895a0d0.png)

In both staging-UK and -KAtuma, the field is left blank and seems to cause the errors. Where can we find the correct/complete settings for Amazon S3 for the respective staging servers?

**Comment by RachL** [comment]
This has been fixed, I'm closing.
