### ISSUE TITLE
Include en_US translations in install for USA instance

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/openfoodnetwork#6003]
In https://github.com/openfoodfoundation/ofn-install/blob/master/inventory/group_vars/us.yml the US server uses the generic en_yml instead of the us-specific. 

## Description
US-specific translations done in transifex (en_US) are not showing up in the US, which confuses Americans.

## Expected Behavior
Translated strings should appear in US interface 

## Actual Behaviour
Non-US idioms and terminology show up instead

## Workaround
US users put up with the awkward (to them) verbiage, but it causes them to not love OFN as much as they should, which impacts adoption rates, user retention, and donations.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
This happens in all environments

## Possible Fix
Integrate the en_US language file into new releases

**Comment by andrewpbrett** [comment]
Hi @lauriewayne, I created a pull request that (I hope) addresses this in the own-install repo.
