### ISSUE TITLE
BE Email deliverability problem

### ISSUE THREAD

**Issue by SophieDuponcheel** [openfoodfoundation/openfoodnetwork#6004]
## Description

Important problem for a producer/store on the OFN BE platform.
He does not receive the order confirmation mails and the customers do not receive the confirmation mails anymore. The orders are well confirmed on the platform. I tried an order on a counter that I manage, and I received the order confirmation as a buyer and as a seller. His adress is from hotmail.com, everything is correct, and he checked his spams and still nothing. 

I checked on SenGrid --> in "blocks" I can read for a lot of emails : 550 5.7.1 Service unavailable, Client host [******] blocked using Spamhaus. To request removal from this list see https://www.spamhaus.org/query/ip/167.89.100.175 (AS3130). [CO1NAM05FT003.eop-nam05.prod.protection.outlook.com]

The producer and the customer does'nt receive the order confirmation mails.

## Expected Behavior

The producer and the customer receive the order confirmation mails.

## Steps to Reproduce

1.
2.
3.
4.

## Severity
bug-s1

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
@SophieDuponcheel are you sure 100% of the customers are not receiving the emails and it's the only email with this problem?

In the global stats of sendgrid, how is your deliverability status?

**Comment by SophieDuponcheel** [comment]
The producer told me that he never received a confirmation email and neither do these customers. I asked to check for spam, and still nothing as email.

In the global stats 
![image](https://user-images.githubusercontent.com/63047606/92493492-de2c9780-f1f4-11ea-897a-fcbbe68743a0.png)

**Comment by Matt-Yorkley** [comment]
According to Spamhaus this outbound mail server (run by Sendgrid) has been automatically added to their block list because it's been used for phishing scams. I'm not sure there's anything we can do here other than complain to Sendgrid...

**Comment by Matt-Yorkley** [comment]
Looks like the Sendgrid login details have changed and not been updated in Bitwarden, so I can't log in and submit a support ticket...

**Comment by RachL** [comment]
thanks @Matt-Yorkley !

@SophieDuponcheel can you contact Sendgrid and let us know? I will close this issue in the meantime. Please re-open it if Sendgrid ask us to do anything on our side.

**Comment by SophieDuponcheel** [comment]
> 
> 
> thanks @Matt-Yorkley !
> 
> @SophieDuponcheel can you contact Sendgrid and let us know? I will close this issue in the meantime. Please re-open it if Sendgrid ask us to do anything on our side.

Ok I contact them right now. I'll tell you if you can do something. Thanks a lot
