### ISSUE TITLE
[Missing translation] Forgotten password email title not translated

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6007]
## Description

When using the forgotten password feature, emails title are sent in English and cannot be translated currently. This issue is created to solve this problem.

## Expected Behavior

The user should receive the email in the language they are suing on the platform

## Actual Behaviour

Everyone receives the email in English

## Steps to Reproduce
1. From the home page, got to 
2. Fill your email in the forgotten password tab
3. Check the email

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/92578974-e59f7f80-f28c-11ea-94f4-0336d51afa3e.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v3.2.6
* Browser name and version: All browsers
* Operating System and version (desktop or mobile): All devices

## Possible Fix

I'm pasting here a comment from @luisramos0 

> I am not sure what is the method but probably we just need to implement this password_change method on our user_mailer. Should be an easy one.

**Comment by RachL** [comment]
@sauloperez would designing the email be a FE task? I mean the email is a bit ugly with lots of space between the text and no logo / footer like the others

**Comment by luisramos0** [comment]
It's in rails, backend, haml.
btw, maybe we should redesign all the very-bad-looking emails at once? Is it just this one and the order shipped email, any other email without formatting?

**Comment by tsara27** [comment]
Hello @RachL 

I am interested to be one of contributor for OFN.
I am sure I can help you with this fix. Could you please assign me this issue?

Thanks!

**Comment by luisramos0** [comment]
:+1: good luck with it @tsara27 let us know if you have any issues.

we are using devise 3.5.10
https://github.com/heartcombo/devise/tree/v3.5.10

I am not exactly sure what needs to be done here, you can explore.
My initial attempt would be to customize this password_change method:
https://github.com/heartcombo/devise/blob/v3.5.10/app/mailers/devise/mailer.rb
here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/mailers/spree/user_mailer.rb

**Comment by tsara27** [comment]
>  good luck with it @tsara27 let us know if you have any issues.
> 
> we are using devise 3.5.10
> https://github.com/heartcombo/devise/tree/v3.5.10
> 
> I am not exactly sure what needs to be done here, you can explore.
> My initial attempt would be to customize this password_change method:
> https://github.com/heartcombo/devise/blob/v3.5.10/app/mailers/devise/mailer.rb
> here:
> https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/mailers/spree/user_mailer.rb

Thank you for your advice. :slightly_smiling_face:
