### ISSUE TITLE
ActiveRecord::StaleObjectError in checkout#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#602]
## Exception in OpenFoodNetwork

**ActiveRecord::StaleObjectError** in **checkout#update**
Attempted to update a stale object: Spree::Variant

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/554aa593ea1b57dee70ebe9c?event_id=557a3e5b0c5815e242920bc9)
## Stacktrace

```
lib/open_food_network/scope_variant_to_hub.rb:19 - decrement!
app/models/spree/inventory_unit_decorator.rb:11 - block in assign_opening_inventory
app/models/spree/inventory_unit_decorator.rb:7 - assign_opening_inventory
app/controllers/checkout_controller.rb:26 - update
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/554aa593ea1b57dee70ebe9c?event_id=557a3e5b0c5815e242920bc9)

**Comment by mkllnk** [comment]
This could make the cart freeze if you change the count of a line item. It happens roughly ones a week.

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::StaleObjectError** in **checkout#update**
Attempted to update a stale object: Spree::Variant

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/554aa593ea1b57dee70ebe9c?event_id=558ca94c20f1ee934e1d61c5)

## Stacktrace

    lib/open_food_network/scope_variant_to_hub.rb:19 - decrement!
    app/models/spree/inventory_unit_decorator.rb:11 - block in assign_opening_inventory
    app/models/spree/inventory_unit_decorator.rb:7 - assign_opening_inventory
    app/controllers/checkout_controller.rb:26 - update

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/554aa593ea1b57dee70ebe9c?event_id=558ca94c20f1ee934e1d61c5)

**Comment by RachL** [comment]
@mkllnk is this one still occurring?
