### ISSUE TITLE
[Rails 4.1] ActiveSupport::Concern::MultipleIncludedBlocks

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6023]
Since importing some Spree lib files we now get lots of instances of this error in the 4.1 build:

```
ActiveSupport::Concern::MultipleIncludedBlocks:
  Cannot define multiple 'included' blocks for a Concern
# ./lib/spree/core/controller_helpers/respond_with.rb:40:in `<module:RespondWith>'
# ./lib/spree/core/controller_helpers/respond_with.rb:37:in `<module:ControllerHelpers>'
# ./lib/spree/core/controller_helpers/respond_with.rb:36:in `<module:Core>'
# ./lib/spree/core/controller_helpers/respond_with.rb:35:in `<module:Spree>'
# ./lib/spree/core/controller_helpers/respond_with.rb:34:in `<top (required)>'
# ./app/controllers/base_controller.rb:1:in `<top (required)>'
...
```

It seems like the Spree version of the file `lib/spree/core/controller_helpers/respond_with.rb` is still being loaded from the spree gem, and our new imported version (ByeBye Spree) is being loaded as well, which is causing a conflict. Relevant PR here: https://github.com/openfoodfoundation/openfoodnetwork/pull/5677

Seems like it could be a class-loading issue with Rails 4.1 specifically? https://stackoverflow.com/questions/24244519/cannot-define-multiple-included-blocks-for-a-concern-activesupportconcern

**Comment by Matt-Yorkley** [comment]
Also applies to other imported controller helpers:
```
ActiveSupport::Concern::MultipleIncludedBlocks:
  Cannot define multiple 'included' blocks for a Concern
# ./lib/spree/core/controller_helpers/auth.rb:9:in `<module:Auth>'
# ./lib/spree/core/controller_helpers/auth.rb:6:in `<module:ControllerHelpers>'
# ./lib/spree/core/controller_helpers/auth.rb:5:in `<module:Core>'
# ./lib/spree/core/controller_helpers/auth.rb:4:in `<module:Spree>'
# ./lib/spree/core/controller_helpers/auth.rb:3:in `<top (required)>'
# ./app/controllers/spree/orders_controller.rb:2:in `<top (required)>'
```

**Comment by Matt-Yorkley** [comment]
Maybe this will be fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/5980 ?

**Comment by luisramos0** [comment]
Hmmm... I am now wondering if we should just make "bye bye spree" block rails 4.1 upgrade. Bye bye spree is really almost done.
I see very few issues in this build (all bye bye spree PRs merged together and running without spree_core): https://github.com/openfoodfoundation/openfoodnetwork/pull/5978 
We just have to push code review a bit more, there are 6 PRs in code review right now and there will be 2 more before the last one. 9 PRs in total: https://github.com/openfoodfoundation/openfoodnetwork/issues/4826

**Comment by andresgutgon** [comment]
I think I fixed this issue in this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6063/files#diff-433336d1449042e3e945048cf7c9c1d4L1 maybe can help
