### ISSUE TITLE
Error 500 on changing main logo or banner on FR prod

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6027]
## Description

Trying to change the logo on FR prod results on an error 500. Same if we try to upload the previous one.

## Steps to Reproduce
1. Go to `/admin/contents/edit`
2. Try to upload a main logo https://drive.google.com/drive/folders/1h-aMo7FYPAAgGDyC422XLaz7XUQE9oJB 
3. Save
4. See error 500

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/3dd6dc69-97c5-42e3-aed0-6ab7f2a86e98)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v3.2.5
* Browser name and version: All
* Operating System and version (desktop or mobile): both

**Comment by pacodelaluna** [comment]
It is related to some permissions on the FR prod server. Getting more info from Bugsnag: https://app.bugsnag.com/open-food-france/coopcircuits/errors/5f6050b663b8ef0018b28b5c?filters[event.since][0]=30d&filters[error.status][0]=open

**Comment by pacodelaluna** [comment]
![Screenshot from 2020-09-15 09-00-55](https://user-images.githubusercontent.com/27745/93176788-13277580-f732-11ea-9178-078178b2cd2a.png)

Ok, I will change manually the ownership of this folder to `openfoodnetwork:openfoodnetwork`, I guess it should do it.

**Comment by RachL** [comment]
Awesome this is working again! thanks @pacodelaluna !

**Comment by pacodelaluna** [comment]
`sudo chown -R openfoodnetwork:openfoodnetwork shared/system/content_configurations/` did the trick. I guess it was just an old configuration from the last server migration, and as we are not often changing much these images, we missed it.
