### ISSUE TITLE
How are E2Es effected by changing an enterprise's type or Producer/Non classification?

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#603]
Are E2E links still logical if we change an enterprise's type (profile, OWN, ANY) and Producer/Non-producer classification?

**Comment by sstead** [comment]
Upon quick investigation, it appears that automatic E2Es are only implemented at the point of enterprise creation. Editing their Producer/non-producer and OWN/ANY/NONE status after they've been created doesn't impact existing E2Es or add new ones.

**Comment by kirstenalarsen** [comment]
should it have any affect? do you think there is anything we need to do here or is ok?

**Comment by sstead** [comment]
I think it's good the way it is.
Automating E2Es can be handy, but if you don't know the automation rules, or if they automation rules are too complex, it's hard to work within them. At the moment they are JUST comprehensible for your average person (ie me :P )

If we were to make one change...
- We could make it so that an enterprise that goes from selling "ANY" to "OWN or NONE" loses all of its E2Es. 
- Then, if someone who owns many enterprises (as Lisa did once) accidentally creates a new ANY enterprise, and then heaps of unneccessary E2Es are created, by swithcing them back to NONE, all of these will be deleted. 
- But this would also carry the risk of removing someone's E2Es if they accidentally changed the status from ANY to NONE.

- I think a better solution is to have an E2E interface where multiple E2Es can be deleted/edited at the same time.

**Comment by kirstenalarsen** [comment]
yep I agree, so probably we leave as is for now and focus on improving the E2E interface
