### ISSUE TITLE
Enable Matomo tracking in Admin 

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#6031]
## Description

As an instance manager / super admin / product manager I would like to gather measurable insights on how enterprises use the Admin to better inform product decisions and improve the overall product experience for our enterprise customers.  

We would like to **extend Matomo tracking to Admin pages** to be able to
- get insights on enterprise user flows 
- measure the usage of existing features
- test the acceptance of new features (A/B, multivariate tests..)
- more general: to make product decisions based on data.

As discussed in product & design meeting and documented [here](https://community.openfoodnetwork.org/t/enable-matomo-to-measure-backoffice-and-actions/1554), we aim for a "simple" solution that will enable tracking of both front  office and back office per default once Matomo is setup for an instance.

The implementation of this issue should also enable solving #5055 

## Acceptance Criteria 

1. Enterprises can opt out of being tracked. (In the most simple solution they will see the same cookie banner as shoppers and by opting out they will switch off tracking both frontoffice and backoffice at same time)
2. In the Matomo UI we will have a way to easily differentiate views for Admin and Frontoffice data to separate Shoppers & Enterprises Analytics (2 separate views possible to avoid endless scrolling in the dropdown?)
3. We can track features and actions in Admin (adding events in matomo tag manager)

**Comment by luisramos0** [comment]
Hello @jaycmb maybe you want to put this issue inside the epic 5974?
![image](https://user-images.githubusercontent.com/1640378/93456787-1196b280-f8d6-11ea-823e-7f5e77662bbc.png)

**Comment by jaycmb** [comment]
@luisramos0 I thought I did but apparently not. Good catch, thanks :)

**Comment by jaycmb** [comment]
As commented in #6114, we would like to s**eparate Shopfront from Admin tracking**, in order to easily differentiate between admin user vs shopper user visits, actions etc.
Also when more events and funnels are defined, we would like to test product feature etc. might be better to manage with separate "websites" (as defined per Matomo) 

**How to do this?**

An option as discussed with @RachL would be to set up Admin-only Websites to test for some of the instances, like the first test "ADMIN | OFN UK", (Site ID 19) that track https://openfoodnetwork.org.uk/admin pages only

Unless there is another way, like having different projects around sub-domain /admin within one instance?).

Also: how can we exclude those Admin visits to be tracked in the OFN UK “normal” Shopfront?

**Comment by mbudm** [comment]
@jaycmb I see your points about separating the admin/shopper data. There are a few extra things to consider.

- We'll need to change the Matomo Settings screen to have separate config got the admin site
<img width="748" alt="Screen Shot 2020-10-29 at 10 33 45 am" src="https://user-images.githubusercontent.com/2467577/97507887-4cf6c780-19d2-11eb-8757-0b7892dd589b.png">
- This will necessitate 2 Matomo sites per instance (3 or 4 if the instance wants to test analytics on their staging instance). Does this have any ramifications for usability of Matomo or limits on numbers of Matomo `web sites'. I.e does this scale?
- What would also be good is to separate traffic in shops by excluding users who are in fact admins, as their behaviour is different to shoppers. I'm assuming here that shop owners go to their shop to check everything displays correctly. This can be achieved in a few ways.
  - With all data in one site you can create segments for customers/admins. customers are defined as never visiting a page in with `/admin/` in the URL, admins are defined as people. who have visited a page with `/admin/` in the URL. This will be possible with the forthcoming change.
  - add context to events using Matamo Tag Manager data layer. This is a code change where we surface data about the user and add it to events. We could add things like `isLoggedIn`, `isAdmin` or even some variables that help categorise them as shopper types (eg `hasNeverPurchased`). This data then allows for much more accurate segments. https://matomo.org/docs/tag-manager/#data-layer

**Comment by jaycmb** [comment]
> Does this have any ramifications for usability of Matomo or limits on numbers of Matomo `web sites'. 

Discussed that with Rachel, we do have a limit for number websites, i.e. with the current plan we could not have a separate Admin Website for each instance.
So the idea was to set this up for one or 2 instances only as a test case and see if it makes sense to possible switch to a another Matomo plan.

But your suggestion with creating segments sounds like a good workaround for this and we could keep all tracking per instance in one website and still separate user flows and visitor data between admin and shoppers.

**Comment by filipefurtad0** [comment]
Hi @jaycmb ,
I'm moving this issue back to All the Things for now :+1:

**Comment by RachL** [comment]
I'm closing this as it is working. If we want to change a specific thing we can open a new issue 👍 1:
