### ISSUE TITLE
Errors when deleting (and creating?) taxonomies

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6033]
## Description

While testing #5868 two BugsnagJS errors were triggered:

i) when creating a new taxon/child

https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/5f5f9c8d35c98900171659b8?event_id=5f5f9c8d005dfcffa4760000&i=sk&m=nw

Nothing visible to the user in this case, only BugsnagJS triggered. Could not reproduce this error.

ii.a) when attempting to delete a child-taxonomy which is is attributed to a product.

https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/5f5fa317f26a69001738bcf0?event_id=5f5fa317005e00fe89a20000&i=sk&m=nw

An the page freezes (endless spinner), error 422 is seen on the console (see pic below). This is reproducible, see steps to reproduce.

ii.b) when attempting to delete a main-taxonomy which is is attributed to a product.

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5f60cf8b37940e00177318ae?event_id=5f60cf8b005e05d971660000&i=sk&m=nw

## Expected Behavior

i) Creating taxonomies should not trigger errors on BugsnagJS

ii) It should not be possible to delete taxonomies when these are attributed to products, right? This is a mandatory field for products.
So, perhaps an improvement would be an informative message stating that the taxonomy X is attributed to product Y and cannot be deleted?

## Actual Behaviour

i) BugnsagJS was triggered, but nothing unusual is shown to the user. 

ii) Cannot delete a taxonomy (main or child) attributed to a product. Attempting to do so:
- for a child-taxonomy: screen freezes with error 422 (console) and BugsnagJS error - see ii.a) above. Refreshing the page shows the previously available taxonomies
- for a main taxonomy: snail/error 500 and Bugsnag error - see ii.b) above

## Steps to Reproduce

i) could not reproduce this error 

ii)

1. Log-in as superadmin. 
2. Go to /admin/taxonomies
3. Create a taxonomy and child taxonomies
4. Create new products with these taxonomies or add them to existing products.
5. Go back to /admin/taxonomies
6. Try to delete a child taxonomy - see error ii.a)
7. Try to delete a main taxonomy - see error ii.b)

## Animated Gif/Screenshot

Error ii.a)

![image](https://user-images.githubusercontent.com/49817236/93116481-37913c80-f6b5-11ea-9be2-c814b5c86c43.png)

Error ii.b)

![image](https://user-images.githubusercontent.com/49817236/93223690-3cfb8f00-f768-11ea-9ccf-418102956e01.png)

## Workaround

- Delete the product which has the taxonomy you want to delete. This is currently not always possible, due to #5947 
- If you can't delete the product then temporarily assign another taxonomy to that product.
Deleting should work after one of these steps. 

## Severity

bug-s4

## Your Environment

* Version used: v3.2.6
* Browser name and version: Firefox 80
* Operating System and version (desktop or mobile): Desktop/Ubuntu 20.04

## Possible Fix

Related to #6030, 5252 and #5947.

**Comment by filipefurtad0** [comment]
Scenario i) on this issue was addressed in PR #6343, so should be solved when Rails upgrade is complete :+1:

**Comment by drummer83** [comment]
Not sure if the issues described above are still reproducible. But still taxonomies cannot be deleted. There is no error message or freezing in the browser, but the taxonomy is back after opening the page again. 

https://user-images.githubusercontent.com/1790176/152075922-e9dda18e-cb0f-482e-8d28-8143a0f97d27.mp4

No product had the taxonomy used according to the filtered products list.
![grafik](https://user-images.githubusercontent.com/1790176/152075829-f765699e-ac3a-4653-8170-2b2742e08edb.png)

Also renaming a taxonomy seems to work at first sight, but it's not being saved permanently.
