### ISSUE TITLE
Docker-Compose Build command error-ing out with ruby-build

### ISSUE THREAD

**Issue by abdiclear** [openfoodfoundation/openfoodnetwork#6034]
## Description
I was trying to set up the app by following the Docker guide. I ran into an issue on step 9/15 of the docker file, what I believe to be the line that runs ruby-build's install.sh file.  The build stops as it returns a "ruby-build: definition not found: 2.3.7" error.

## Steps to Reproduce
What I did was:

1. Fork the repo
2. run docker-compose build

## Animated Gif/Screenshot
![issue1](https://user-images.githubusercontent.com/28714852/93272710-1ba89c00-f784-11ea-82e5-9f07befe4966.PNG)
![issue](https://user-images.githubusercontent.com/28714852/93272486-93c29200-f783-11ea-8566-3ae4810d019e.PNG)

## Severity
I'm not too sure what to rate it, maybe s3 or s4?

## Your Environment
I am on Windows 10 Pro.

## Possible Fix
I was thinking maybe something need to be modified within the Dockerfile.

**Comment by luisramos0** [comment]
Thanks for creating the issue!

I dont get that error "definition not found"

I get
Downloading ruby-2.3.7.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.7.tar.bz2
Installing ruby-2.3.7...


Something related to the ruby-build version you get?
You could try to modify these Dockerfile lines and try again:
RUN git clone --depth 1 --branch v1.1.2 https://github.com/rbenv/rbenv.git ${RBENV_ROOT} && \
    git clone --depth 1 --branch v20200520 https://github.com/rbenv/ruby-build.git ${RBENV_ROOT}/plugins/ruby-build && \

**Comment by abdiclear** [comment]
So after some searching and testing, it turns out there was some empty space in the .ruby-version (CR+LF). The empty space was getting read with the version number, so that's why it kept bugging out on me. Do we need this empty space after the version number?

**Comment by luisramos0** [comment]
That space is not in GH is it?
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/.ruby-version
Or do you mean the final empty line?

**Comment by luisramos0** [comment]
anyway, please create a PR with the fix that worked for you. we will accept it if it does break other peoples setup :+1: Thank you!

**Comment by abdiclear** [comment]
The final empty line sounds about right. It shows up on GitHub and my local text editors. I'll create a PR momentarily 👍.

**Comment by luisramos0** [comment]
this is now resolved, see #6047 for details.
