### ISSUE TITLE
Enterprise management page - status updating incompletely when change to Package.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#604]
![image](https://cloud.githubusercontent.com/assets/10843056/8124226/8b878f4a-111b-11e5-8931-5dd91ad6e224.png)
o

**Comment by daniellemoorhead** [comment]
@sstead is this still an issue?

**Comment by sstead** [comment]
Yes, still an issue

**Comment by myriamboure** [comment]
This seems to be fixed:
https://www.useloom.com/share/d218fc7cd04a46f1990c4b083bfa576b
So closing now, feel free to reopen @sstead if that's still an issue on your side.
