### ISSUE TITLE
/api/enterprises endpoint not working (snail)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#6040]
## Description

Our [swagger docs ](https://app.swaggerhub.com/apis/luisramos0/the-open_food_network/0.1#/enterprises/get_enterprises__enterprise_id__shopfront
) include an endpoint for enterprises/{enterprise_id}/shopfront

When I try to use it I get a snail
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/ecfb2594-e4f8-495b-b233-76d258df3d88)

This could be user error as I don't profess to know what I'm doing here - but I've tried a few others in the same way and they seem to work.

## Expected Behavior

The API should return information from the endpoint. NB. I am not attached to what exactly the endpoint returns as I was just exploring and haven't seen it - would like to! 

## Actual Behaviour

Snail

## Steps to Reproduce
1. Go to https://openfoodnetwork.org.au/api/enterprises/871/shopfront and put in an enterprise id of your choice
2. See snail

## Workaround
None that I know of

## Severity
Under discussion in Slack - it seems we are leaning to S2 as we are having increasing usage of our API and need to start viewing it as a critical feature
ping @luisramos0 @lin-d-hop @RachL 

## Your Environment
MAC OS Chrome, also doesn't work in firefox

**Comment by Matt-Yorkley** [comment]
@kirstenalarsen A quick look at the API code shows this route doesn't exist anymore, it looks like it was moved to: `/api/shops/<enterprise_id>`

**Comment by Matt-Yorkley** [comment]
This just requires a swagger documentation update. I don't think it's an S2, more like a papercut?

**Comment by luisramos0** [comment]
:+1: 
I think this is a bug. We need to keep api docs up to date and consider errors in api docs as bugs (the fix is a commit to the swagger doc in github).
Maybe not now but imo if API is a true first class citizen in OFN, this should be an S2 and fixed immediately.

**Comment by lin-d-hop** [comment]
I feel like this needs discussion. 
Is there anywhere in OFN that the documentation results in s2 issues? The OFN user guide is maintained outside of the global pipe. 

The API docs are v0.1 and under a personal account of Luis. My experience is that they are incomplete and lacking a lot of the detail required to be truly useful.

I agree the API should be a first class citizen, but I would suggest we have quite a bit of work to do before a documentation update is an S2.

**Comment by luisramos0** [comment]
I understand and dont disagree. I am afraid that if we dont start this now we will never start.
I think keeping API docs and API in sync is a fundamental requirement of the API. Therefore, a bug in docs and a bug in the API should be regarded as the same thing from the start.

**Comment by lin-d-hop** [comment]
I also 100% agree with you. But I have to be clear I am terrified about this.

I've spent the last 18 months working with the API. A lot of our endpoints are a mess. If we start officially supporting the hacky, messy endpoints now we are going to be locked into an API that serves no one. We're going to create a huge amount of additional inertia to change. Similarly, many endpoints are only partially documented. 

In my opinion, before the API becomes a first class supported feature we need to:
1)  have a kick off. 
2) decide which endpoints we are officially supporting.
3) document these endpoints in an official OFN account so we can avoid confusion with unsupported endpoints.
4) agree some decisions about how we prioritise API bugs.

I don't mind if you want to fix this documentation bug as an s2. 
Please please please, however, can we be a little more strategic about the bigger API picture? :pray:

**Comment by luisramos0** [comment]
ok, no problem.  I would not generalize "messy and hacky". We have an API that works. A good part of the OFN app is built on top of it! Some endpoints are ready to be used, some other need a good clean up and complete docs.

Let's follow your list! Can we start now?

**Comment by andrewpbrett** [comment]
I updated the [Swagger docs](https://app.swaggerhub.com/apis/Open-Food-Network/Open-Food-Network-API/0.2) that @kirstenalarsen [created](https://github.com/openfoodfoundation/openfoodnetwork/pull/6559#issuecomment-758332933), so I believe this can now be closed, since the old endpoint is no longer in the docs. 

I'm opening https://github.com/openfoodfoundation/openfoodnetwork/pull/6659 since it looks like Kirsten wasn't able to recreate the API on the OFN account with the old .yaml file.
