### ISSUE TITLE
Enterprise Index: Alignment of status icons

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#605]
![image](https://cloud.githubusercontent.com/assets/2911176/8124241/cfffa00e-111b-11e5-8c1b-af7206d7600a.png)

**Comment by myriamboure** [comment]
This seems fixed
![screenshot from 2018-02-28 22-36-20](https://user-images.githubusercontent.com/8135376/36814450-d6de2af6-1cd7-11e8-93e9-658ecd319eaa.png)
So closing.
