### ISSUE TITLE
Excessive deprecation messages

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6056]
We need to resolve the issues raised by the deprecation warnings.  The thousands of deprecation warnings that spam the test output make it much more difficult to read.  This bogs down the process of troubleshooting and debugging, which is already burdened by the lengthy test suite.

**Comment by lin-d-hop** [comment]
Hi @jhsu802701 
Thanks for submitting this issue to the community.
Did you see the issue templates?
As a community we will be unlikely to  work on this issue until it has a clear proposal for a tech solution, or is specified as a spike.
Perhaps you can ask these questions in the #dev channel in our Slack and see if people think it is worth creating issues with a clear and full specification?
