### ISSUE TITLE
Excessively long test process

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6057]
The test suite is excessively long.  SemaphoreCI takes over 20 minutes.  My local machine requires something like an hour.

Why must the test suite take so long?  Does the process of creating objects for the tests take excessively long?  If so, it would be better to create the objects just once and run many tests before destroying them.

**Comment by lin-d-hop** [comment]
Hi @jhsu802701 
Thanks for submitting this issue to the community.
Did you see the issue templates?
As a community we will be unlikely to  work on this issue until it has a clear proposal for a tech solution, or is specified as a spike.
Perhaps you can ask these questions in the #dev channel in our Slack and see if people think it is worth creating issues with a clear and full specification?
