### ISSUE TITLE
Errors at the end of the seeding process

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6058]
The database seeding process performs as expected until just before the end.  At the end of the seeding process, I'm getting the following screen output:
```
xprop:  unable to open display ''
xprop:  unable to open display ''
Couldn't find a suitable web browser!
Set the BROWSER environment variable to your desired browser.
Warning: program returned non-zero exit code #1
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'file:////usr/src/app/tmp/letter_opener/1600469773_1301756_9a4dc0d/rich.html'
```

**Comment by lin-d-hop** [comment]
Hi @jhsu802701 
Thanks for submitting this issue to the community.
Did you see the issue templates?
As a community we will be unlikely to  work on this issue until it has a clear proposal for a tech solution, or is specified as a spike.
Perhaps you can ask these questions in the #dev channel in our Slack and see if people think it is worth creating issues with a clear and full specification?
