### ISSUE TITLE
Bulk Order Management units

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6071]
## What is the problem we are solving 
As part of #5888 products can now have units of pounds and ounces. However, on the Bulk Order Management (BOM) interface, the weight column is in grams, so to adjust an order, a user would have to convert from pounds/ounces to grams. See discussion on #5888 for additional details and screenshots. 

## Success factors = expected outcome 
We could solve this a few different ways - it's not an easy problem! One solution would be to have the column just be weight and the units of the product indicated in each row, since now they might not be similar units (a shop can have some products in pounds and others in kg).

**Comment by RachL** [comment]
@jaycmb is this epic still something to do? If so I think we need to move it to inception backlog or equivalent so it can be broken into stories.

**Comment by jaycmb** [comment]
Yes, good point.
That should go into inception backlog because needs further investigation. 
I´ll close it here and reopen in inception pipe (as we do not have the connection to move across workspaces yet)

**Comment by RachL** [comment]
@jaycmb Github allows you to transfer an issue from one repo to another, no need for Zenhub ;) 

![image](https://user-images.githubusercontent.com/6525576/97731278-35ecce00-1ad5-11eb-928c-168dbacdde21.png)
