### ISSUE TITLE
Variant over-rides are not applied if original product has 'on demand' quantitiy

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#608]
Variant over-rides work for price and quantity (if on hand), but when the original product is 'on demand' it doesn't seem to work. See testing notes here... http://community.openfoodnetwork.org/t/june-19-testing-4-branches/244/2

**Comment by RohanM** [comment]
Fixed in branch vo-on-demand-stock-control, 040009013f161e6042986f1604102ab5e44f6517
