### ISSUE TITLE
Allow instances to choose what available units for products/variants

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6082]
## What is the problem we are solving 
With #5888 two new options (pounds and ounces) were introduced for product/variant units. The dropdown is now pretty big and could get bigger if we wanted to further support other units (many people in the US sell fruit by the pint or the quart), making it even more unwieldy to wade through a long list of options. 

This would allow shops to ignore units that they never use. 

Going further, we could also allow instances to choose the default available units for new shops on their instance (metric units only for most of the world, for example). 

## Success factors = expected outcome 
Happier admin users, easier product/variant creation

**Comment by andrewpbrett** [comment]
Migrated to https://community.openfoodnetwork.org/t/allow-enterprises-to-choose-what-available-units-for-products-variants/2060

**Comment by jaycmb** [comment]
As commented in #5888, for now the most simple solution for 

1. Allow user to hide / display options imperial vs metric or both when creating products

would be having a multi-select tick box with 
- Imperial
- Metric

(for use-cases like for example I as user in France, who won´t ever want to sell in oz just don´t want to have those imperial units in my unit size list)

Other issues, like 

2. Allow user to convert created products from one unit type to other, (i.e. a way that product units can be re-calculated automatically when for example producers expand the hubs or shops they are selling to and different units are needed)
3. Allow instances to choose the default available units for new shops on their instance (metric units only for most of the world, for example)

need some inception work and also feedback from users / customer support.
Pinging @RachL here

**Comment by andrewpbrett** [comment]
Reopening per conversation with Jana

**Comment by jaycmb** [comment]
As agreed in yesterday´s product curation meeting the 2 options were discussed to see if there is a simple solution to the concerns regarding compliance in EU and possible confusion of users

**1. Enterprise Level:** Allow enterprises to hide / display options imperial vs metric or both when creating products

**2. Instance Level:** Allow instances to choose the default available units for new shops on their instance (metric units could per default for most of the world)

Option 2) seemed to be simple and makes more sense as the Imperial Units are not of interest for most instances. Andy was willing to have a look into it :)
