### ISSUE TITLE
API error responses

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6096]
### What we should change and why (this is tech debt)

All our API endpoints return our full HTML error page (the infamous slug) when an error is encountered, including a 404. This is not the correct format for JSON endpoints, and also involves a much larger data transfer then necessary.

We should just return JSON with a standard error message. We probably want a separate message for a 404 and for other errors like a generic 422 or a 5xx.

### Context

Exploring API endpoints with the very nice [Insomnia](https://insomnia.rest/products/core) API testing client.

**Comment by Matt-Yorkley** [comment]
It also looks like we respond with a 404 in non-404 cases, like failure to authenticate? A clear message would be nicer.

**Comment by georgethoppil** [comment]
I can start taking a look at this
