### ISSUE TITLE
Modal behaviour when enterprise is both producer and hub 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#610]
- This should have 2 options - Jonai Farms (Melbourne) and Jonai Farms (Central Highlands) - where is Jonai Melbourne?  This is because when an Enterprise is both Producer and Hub the modal treats it as hub - therefore only shows the link to the Hub, and not the links to the Producer's other Hubs. I'm wondering if we should change the behaviour so that it treats it as producer instead - seems more useful . . TBC

![60dfb41480af5f1a](https://cloud.githubusercontent.com/assets/2911176/8344541/54978408-1b26-11e5-95f0-bb97b197d4ab.png)

**Comment by lin-d-hop** [comment]
This needs more spec to be useful. #gitcull
