### ISSUE TITLE
Add test coverage badge

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6100]
A test coverage badge should be added to the README.md file.  Only a collaborator can provide this.

The Semaphore CI tests show that the test coverage is only around 55%.  At the moment, trying to improve the test coverage is an agonizingly slow task.  Without the test coverage badge (and its link to the detailed test coverage results), the only way to see what code is covered or not covered is by running the entire test suite on our local machines.  This is a painful process because of the excessive time needed to run the entire test suite AND the thousands of deprecation messages in the screen output of the test suite.

**Comment by RachL** [comment]
This is done now :tada:
