### ISSUE TITLE
Actions Menu doesn't work for Cancelled orders

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#6101]
## Description

When clicking on options in the Actions menu in Orders, nothing happens. 

## Expected Behavior

Menu options are available to click. 

## Actual Behaviour

After an order has been cancelled, it is not possible to click on any items in the Actions menu. 

## Steps to Reproduce

1. Log in to an Enterprise
2. Edit an Order
3. Cancel the order
4. Attempt to use the Actions menu

This was originally noted as part of issue #5018 and @luisramos0 suggested raising it as a separate issue:

![Screen Shot 2020-09-29 at 12 51 56 PM](https://user-images.githubusercontent.com/47620442/94507274-b8723b80-0252-11eb-9860-831923c620ad.png)

bug-s3: a feature is broken but there is a workaround

**Comment by luisramos0** [comment]
Thanks @emilyjeanrogers for raising this issue!

**Comment by filipefurtad0** [comment]
PR #6982 brought this menu back to function - I think we can close it, after this PR is merged .
