### ISSUE TITLE
Enable setting variant SKU from Bulk Product edit page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#611]
currently only available for product

NB. Implementation to be considered pending http://community.openfoodnetwork.org/t/upgrade-variant-overrides-interface-for-independent-inventory-control-by-hubs/83 as functionality may be better handled in VO page, rather than BPE (quite likely that hubs have their own SKU systems?)

**Comment by myriamboure** [comment]
It seems it's possible to set up a SKU for variants in bulk edit products page, so closing
![screenshot from 2018-03-04 21-16-30](https://user-images.githubusercontent.com/8135376/36950101-62f9f7d8-1ff1-11e8-9622-95820d1de444.png)
