### ISSUE TITLE
Upgrade to Ruby 2.4

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6115]
### What we should change and why (this is tech debt)
We need to move forward with Ruby version so we can keep upgrading all other dependencies and also benefit from the so many improvements that come with latest Ruby versions, security and performance.

### Context
I think this was briefly discussed here:
https://github.com/openfoodfoundation/openfoodnetwork/pull/4518#issuecomment-559456990
We should probably try ruby 2.4 after we are on rails 4.1 https://github.com/openfoodfoundation/openfoodnetwork/issues/5386

### Impact and timeline
After rails 4.1 or maybe only after rails 4.2.

**Comment by tsara27** [comment]
Hello @luisramos0 

I have experience in upgrading Ruby application. Can I take this issue?

**Comment by luisramos0** [comment]
Hi @tsara27 welcome to OFN, join us on slack!
This upgrade can only be done after the upgrade to Rails 4.1.
I'd recommend you look for the label good-first-issue where we list issues that are good to start with the code base.

**Comment by tsara27** [comment]
I will do @luisramos0. Thanks!

**Comment by luisramos0** [comment]
ruby 2.4 brings support OpenSSL 1.1.0
I wonder if that will help with some local setup issues we have had with openssl...

**Comment by luisramos0** [comment]
not blocked any longer.
I think we can use 2.4.4 (semaphore upper 2.4 versions just like 2.3.8... "RC platform only").

**Comment by sauloperez** [comment]
We've been running on Ruby 2.4 for some weeks. So far, so good!
