### ISSUE TITLE
Invalid unit_value on product creation returns 500 instead of 422

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6117]
## Description
Entering a non-number for `unit_value` (appears as the "Value" text field) during product creation returns a 500 error instead of a more informative error message. We do have placeholder text in the field but this can often be missed or misinterpreted.

## Expected Behavior
Error message stating "Value must be a number" and a 422 server response.

## Actual Behaviour
Entering a non-number for unit_value during product creation returns a 500 error.

## Steps to Reproduce

1. https://openfoodnetwork.net/admin/products
2. Click on New Product
3. Enter valid product information except for the Value text field
4. Click Create
5. Death by slug

## Animated Gif/Screenshot
<img width="1047" alt="Screen Shot 2020-10-01 at 1 53 41 PM" src="https://user-images.githubusercontent.com/35588/94862215-86e1a780-03ed-11eb-8302-d8d57030b84b.png">

## Workaround
Reading the placeholder text, or just guessing at what went wrong. 

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
Safari

**Comment by RachL** [comment]
@andrewpbrett thanks :) When you add a good first issue, don't hesitate to add it to the welcome new dev board and add it to the correct column.Also, in this month of hacktoberfest, don't hesitate to use the hacktoberfest label 💪

**Comment by tsara27** [comment]
Hello @andrewpbrett 

I am sure I can help you solve this issue. Can you please assign this issue to me if no one take this issue?

Thanks!

**Comment by andrewpbrett** [comment]
#3912 and #4959 look very closely related and can probably be closed at the same time if we fix this one.

**Comment by tsara27** [comment]
Hello @andrewpbrett 

I will look into it.
