### ISSUE TITLE
Product description is cleared if there are errors in the product form

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6118]
## Description
This might be closer to feature request than bug... 

If I create a product, and type a really nice, long description with a lot of effort, but forget to do something else in the form (choose a Category for instance) and then I click Create, the form tells me about the error but wipes out all my wonderful work!

## Expected Behavior
The form should remember what I've entered in all the fields. 

## Actual Behaviour
The form remembers some fields (name, category, price) but not others (description, unit size, value, on hand)

## Steps to Reproduce

1. Go to https://openfoodnetwork.net/admin/products
2. Click New Product
3. Fill in description, unit size, value, on hand fields
4. Leave out one or more required fields
5. Click create

## Animated Gif/Screenshot
<img width="981" alt="Screen Shot 2020-10-01 at 2 12 17 PM" src="https://user-images.githubusercontent.com/35588/94864064-4899b780-03f0-11eb-8885-58d37695b288.png">

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment
Safari

**Comment by RachL** [comment]
@andrewpbrett @openfoodfoundation/core-devs can this be a `good-first-issue` ?

**Comment by luisramos0** [comment]
yes, for some one with Rails experience it should be easy to find out what's going on.

**Comment by andrewpbrett** [comment]
Yes! Sorry, forgot to tag issues on this one.
