### ISSUE TITLE
'Expand all' on BPE page only expands finite number of the top ones

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#612]
![image](https://cloud.githubusercontent.com/assets/2911176/8447301/a8c1991a-1ff9-11e5-9712-005099832cfb.png)

## Expected behaviour
When clicking on expand all, expand all. If lots of products do it only on the first page (if pagination) or display a message like "processing request" while they are expanding.

## Severity
S3 as there is a workaround. Pretty annoying in term of UX.

**Comment by lin-d-hop** [comment]
Pau's pagination work will mean that the flow of this issue will no longer be relevant. #gitcull
