### ISSUE TITLE
Backoffice orders: Endless spinner and error 500 after skipping OC selector 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6133]
## Description

Observed while testing #6039

Selecting a distributor and an order cycle from that distributor are the first steps to take, when placing backoffice orders. 

If the selection of the order cycle is skipped and the user clicks "Next" then the "Add Product" field is broken: attempting to search and choose from a product list from, by inserting characters in the, shows an endless spinner, error 500 on the console and  bugsnag is triggered.

See video below.

## Expected Behavior

Selecting an OC should be mandatory

## Actual Behaviour

The user is "allowed" to skip the choosing-OC step, which breaks the product search function: adding the first letters results in an endless spinner in the search field, error 500 in console and bugsnag error report:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5f33a1494da42b00178f81c4?event_id=5f5fa0c5005dfe3cef320000&i=sk&m=nw

## Steps to Reproduce

Log in as admin
1. Click "New Order"
2. Select a distributor; don't select an OC
3. Click "Next"
4. Try to select a product, by inserting the relevant first three letters/characters
5. See endless spinner/error 500/bugnsnag error

## Animated Gif/Screenshot

![error_not_selecting-OC](https://user-images.githubusercontent.com/49817236/95071596-d1bb3200-0701-11eb-9601-22ca4481d0d5.gif)

## Workaround

Selecting the OC, just below the "Add a product" section solves this.

## Severity

Proposing bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.2.8
* Browser name and version: Firefox 81
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by jibees** [comment]
<img width="847" alt="Capture d’écran 2023-04-17 à 15 48 21" src="https://user-images.githubusercontent.com/296452/232503598-e19e1f88-f1c1-4d91-bb9a-13af20b34ecc.png">

On this page, neither the distributor nor the order_cycle are required. Shouldn't we make them mandatory on that page?
I think it should solves the error we have on next step, but wondering if this is a good idea.
