### ISSUE TITLE
Release 3.2.10 Hardy Kiwi

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6149]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] Release draft: https://github.com/openfoodfoundation/openfoodnetwork/releases
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1771
- [ ] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by lin-d-hop** [comment]
Ready to Go:
https://docs.google.com/document/d/1UlxE2Cu9pz917oVL6aDmZNVf_zsj1grX-Bo4KGHjnag/edit#

Great work team!
