### ISSUE TITLE
Update the base Ubuntu Docker image from 18.04 to 20.04

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6152]
Ubuntu 18.04 is out of date because version 20.04 was released 6 months ago.

**Comment by jhsu802701** [comment]
An alternative path is to use a Ruby Docker image based on Debian Buster.

**Comment by ipalo** [comment]
Hi @jhsu802701, do you think this issue is eligible for the `Hacktoberfest`? 😄 
I've already worked on it, I can open a PR if you're ok with that!

**Comment by luisramos0** [comment]
Hello @ipalo we think it is. I added the label.
It needs to be Ubuntu, not debian, ok? :-)
