### ISSUE TITLE
"On hand" is not a mandatory field, when creating a product

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6159]
## Description

The "On Hand" field is not mandatory. The value zero is the default value and is assumed even if this no value is inserted.

## Expected Behavior

The behavior for the Price field (as below) is expected to be observed if the On hand field is left blank:

![image](https://user-images.githubusercontent.com/49817236/95357664-0c6ac900-08c0-11eb-9863-a5d39e9fb607.png)

## Actual Behaviour

It is not necessary to introduce a value on the "On Hand" field to create a product; when this is left blank then the value 0 is assumed (which is ok, zero is a valid value) but no error message/underlining of these missing fields is seen. 

## Steps to Reproduce

1. Log in as admin
2. Go to Products, and click +New Product
3. Fill in all the fields leaving "On Hand" empty: you'll need to delete the pre-filled zero (0).
4. Click "Create" -> creation is successful, and no warning is shown to the user.

## Animated Gif/Screenshot

See the pic under Expected Behavior showing the underlining and error message regarding the missing field. 

## Workaround

Adding/updating the price in the product list.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: introduced between v.3.2.9 and v.3.2.10
* Browser name and version: Firefox 81
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by RachL** [comment]
@filipefurtad0 we are not tagging regressions so far... For example https://github.com/openfoodfoundation/openfoodnetwork/issues/5947 is a regression as well.

We track them during major upgrade to be able to prioritize them. I'm not sure there is a need to do it more regularly, except maybe knowing where automated tests are not strong enough?

**Comment by filipefurtad0** [comment]
Thanks for the feedback here @RachL .
That's a good question - I'm not sure either. I figured it could be useful as it adds some context to the findings. Maybe we can chat about it on the Dev-train meeting? I'll remove the label and change the title.

**Comment by Tshamp7** [comment]
Hello! I saw this on codetriage and I'm interested in working on this if that's okay.

**Comment by filipefurtad0** [comment]
Hi @Tshamp7 ,
Welcome, please go ahead :tada: 
I've assigned you to this issue - please let us know if you have any questions.

**Comment by Tshamp7** [comment]
Thanks will do!

**Comment by RachL** [comment]
Hi @Tshamp7 ! I hope this message finds you well. Are you still planning to work on this? No pressure, I just want to make sure this is still something that is currently being worked on :)

**Comment by Tshamp7** [comment]
Hello! I was going to reach out to you guys, I had some stuff come up at
work I've been needing to work on and haven't had a chance. You can
unassign it from me.

Sorry about that!

**Comment by RachL** [comment]
No worries @Tshamp7 thanks for the quick answer :)

**Comment by filipefurtad0** [comment]
This seems reproducible in staging-UK, when the chosen language is English. When using the app in French, for example, and creating a new product:

![image](https://user-images.githubusercontent.com/49817236/99520087-965f8480-298a-11eb-8440-55e3fa8bd08f.png)

Clicking Create, leads to:

![image](https://user-images.githubusercontent.com/49817236/99519939-63b58c00-298a-11eb-9b93-6de19dab872b.png)

Which is the correct behavior. 

I've checked in Production in Katuma and Coopcircuits, and this is OK there as well, in different languages.

Also, I looked at Bugsnag: these errors in staging-UK appear grouped with **11 occurrences in production**, in UK, since the v3.4.1-beta was deployed:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fb380c47c7acc0018a558e1?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[app.release_stage][0][value]=production&filters[app.release_stage][0][type]=eq&pivot_tab=event

Should the severity be increased?

**Comment by filipefurtad0** [comment]
This seems only to affect instances/sessions using `en_GB` locale. It should be solved by adding the missing translation on Transifex. Ping @lin-d-hop .

See also discussion, for reference:
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1605692638182900

**Comment by filipefurtad0** [comment]
This translation was just pushed to the transifex branch :tada: 

![image](https://user-images.githubusercontent.com/49817236/99571357-186f9d80-29cb-11eb-98c5-ea72a740655f.png)

So no further action needed for now :+1:

**Comment by filipefurtad0** [comment]
"Price" seems to be a mandatory field in both staging and production again :+1: Removing the regression label.

![image](https://user-images.githubusercontent.com/49817236/100876648-950c7c80-349f-11eb-8d77-417a8d6d82ca.png)


"Display as" and "On hand" are marked by the (*) as mandatory fields but are not. This was the case before, so no regression here.

**Comment by ccozkan** [comment]
Hey :wave: , I would like to pick up this issue

**Comment by filipefurtad0** [comment]
Hi @ccozkan , welcome :tada: 
I've assigned you to the issue. Feel free to drop us a line if you have any questions :+1:

**Comment by ccozkan** [comment]
> Hi @ccozkan , welcome 
> I've assigned you to the issue. Feel free to drop us a line if you have any questions

Thanks @filipefurtad0 :smile: I've been busy so I had chance to look at and surf around to project recently.

I have couple of questions though :thinking: 

1. on hand validation

**Comment by Matt-Yorkley** [comment]
I have a feeling there might be some additional hidden complexity here, like if you select "weight", then certain fields are required, and if you select "items" then other fields are required...

**Comment by ccozkan** [comment]
Thanks @filipefurtad0 :smile: I've been busy so I had chance to look at and surf around to project recently. I have a question 
 though. :thinking:  I did not quite understand the role of with `Spree::StockItem`, `Spree::Variant`, and `VariantOverride`. Can you please explain them in one-or-two sentences?

**Comment by filipefurtad0** [comment]
Hey @ccozkan ,

I can add a very brief description sentences on what these concepts do in the app:

**Products/Variants** need to have a value for **stock items** set, from which the availability for a customer to purchase it depends on. For example, if a given variant (ex., eggs) has zero stock items, then it will be not available in the shopfront.

Hub managers and producers, can set the stock for the variants when they create a new variant or by editing an existing one, under the /admin/products page. However, the stock values set on this page can be _overiden_  by the settings in the **Inventory** page - /admin/inventory.

For details on this, see:
https://guide.openfoodnetwork.org/basic-features/products-1/product-variants
https://guide.openfoodnetwork.org/basic-features/products-1/inventory-tool#managing-your-inventory-products

I'm pointing out some files I think are relevant to understand how it works under the hood:
Spree::StockItem - /app/models/spree/stock_item.rb
Spree::Variant - /app/models/spree/variant.rb
VariantOverride - /app/models/variant_override.rb

Does this help? If you need some specific dev insight feel free to drop a line in the #dev channel on Slack.

I'm not sure this is a good first issue as there might be some other things happening - see @Matt-Yorkley 's comment above. If it gets to tricky feel free to look for issues with the `good first issue` label.

**Comment by filipefurtad0** [comment]
> like if you select "weight", then certain fields are required, and if you select "items" then other fields are required

I see that now @Matt-Yorkley : the "Display as" field is only mandatory if you choose Unit Size = Items. This is working, and I believe this is the expected behaviour. In the user guide for example this field is not set as mandatory ([see video](https://gblobscdn.gitbook.com/assets%2F-L9rgk4wEweX_zxXIzmW%2F-LxaFs3a0kjQKz2WBKCo%2F-LxaHw3uxEn-2891KxH5%2Fproductsadd.gif?alt=media&token=37875977-e7ac-4782-b656-31030876cefe)).

So maybe this is ok as is, and not a bug? In that case, I'd just add a spec to cover the case in which a items require "Display as"  #6447?

**Comment by Matt-Yorkley** [comment]
> the "Display as" field is only mandatory if you choose Unit Size = Items

Do you think the UX is clear enough on this, or could it be improved?

**Comment by filipefurtad0** [comment]
Yes, I think ideally the `*` should only appear, when the user chooses "Items". I guess it should not appear if user chooses any other unit (as in the user guide), as the "Display as" is not mandatory.

**Comment by filipefurtad0** [comment]
Some additional thoughts:

Currently, we can create a new product in two ways:
a) directly from the products page  by clicking "New Product" -> in this case, the user stays in the product page `/admin/products`
b) when editing a product, and clicking "New Product" -> in this case, the user is redirected to `/admin/products/new`

We have observed some differences in these pages and how these fields react, [for example here](https://github.com/openfoodfoundation/openfoodnetwork/issues/6304#issuecomment-723281676). So, it looks like we need to test them separately. That might mean need to add double specs for routes a) and b). At the moment, we test this manually still.

Maybe we should remove one of these paths? This would simplify the page, for example, removing the product creation path a), so that when the user clicks "New product" it gets redirected to path b).

The only loss in functionality would be to to be able to scroll down, while creating a new product. I'm not sure this is worth.

Would this make things simpler codewise and specwise?

**Comment by filipefurtad0** [comment]
As agreed [here](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1610487411277300), tech debt #6650 was opened to address the removal or product creation through path a), as described above.

**Comment by filipefurtad0** [comment]
Adjusted the name of the issue, as Display as is not mandatory and this is the expected behaviour. Opened issue #6159

**Comment by ccozkan** [comment]
Yes, sorry I've been busy, But I still want to work on it, I will try to tackle this issue this weekend:)

**Comment by ccozkan** [comment]
I have a suggestion about this issue :thinking: . Wouldn't just changing on_hand's `text_field` type to `number_field, min: 0` on the form, be a simpler solution to the issue?

**Comment by filipefurtad0** [comment]
Hey @ccozkan ,

This issue has gone through some changes, since it was opened. I've updated the description, to make it more clear. Right now, it's really only about informing the user, that the `on_hand` field is mandatory, with the red banner, as it happens for all other mandatory fields marked with the star sign `*`, as described in the Expected Behavior section.

However, those are interesting thoughts - but I'm not the best in the team to answer those questions. 

Maybe an approach would be to address the expected behavior, and then, in additional commits, add the changes you propose? This could then be discussed with the devs reviewing your PR.
