### ISSUE TITLE
User balances displayed on account screen

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#616]
Can we add the full transaction list to the user screen so that they can see their credit balance?

**Comment by lin-d-hop** [comment]
Exploring more in http://community.openfoodnetwork.org/t/customers-being-able-to-view-their-payments-and-balance-in-account/308

**Comment by lin-d-hop** [comment]
Hi @stveep,

The build on this branch is currently failing:
  1) Api::OrdersByDistributorSerializer serializes orders
     Failure/Error: expect(@serializer.to_json).to match "distributed_orders"
     NameError:
       undefined local variable or method `spree' for #<Api::OrderSerializer:0x007ff0d7611e60>
     # ./app/serializers/api/order_serializer.rb:31:in `path'
     # (eval):13:in `_fast_attributes'
     # ./spec/serializers/orders_by_distributor_serializer_spec.rb:19:in `block (2 levels) in <top (required)>'
  2) Api::OrdersByDistributorSerializer serializes the balance for each distributor
     Failure/Error: expect(@serializer.serializable_array[0].keys).to include :balance
     NameError:
       undefined local variable or method `spree' for #<Api::OrderSerializer:0x007ff0d77c38a8>
     # ./app/serializers/api/order_serializer.rb:31:in `path'
     # (eval):13:in `_fast_attributes'
     # ./spec/serializers/orders_by_distributor_serializer_spec.rb:23:in `block (2 levels) in <top (required)>'

It was passing a couple days ago... would you take a look when you can?

When it was passing I did deploy to staging and the changes looked really great. One comment on:
http://community.openfoodnetwork.org/t/customers-can-view-their-payments-and-balance/308/21

Thanks so much for this awesome work!!

**Comment by stveep** [comment]
This is the method causing the problem - to serialise the path to link to the order page, using the spree url helper:

app/serializers/api/order_serializer.rb

```{ruby}
class Api::OrderSerializer < ActiveModel::Serializer
  attributes :number, :completed_at, :total, :state, :shipment_state, :payment_state, :outstanding_balance, :payments, :path

  has_many :payments, serializer: Api::PaymentSerializer
...

  def path
    spree.order_url(object.number, only_path: true)
  end
end
```

The spec passes locally for me - is there any reason the helpers wouldn't be available when Travis runs the specs? Is there a better way to get the url into the frontend? Needs to go in an ng-repeat so can't render this on the server. @oeoeaio @mkllnk ?

**Comment by mkllnk** [comment]
The order of tests is different. Do you run that spec on its own? Do you run it with zeus? What happens if you run that spec on Travis on its own?

Somehow spree isn't loaded. But I don't know why. Maybe you need to require something. @oeoeaio ?

Providing the path during serialisation sounds reasonable to me.

**Comment by stveep** [comment]
OK I "fixed" it with:

```{ruby}
  def path
    Spree::Core::Engine.routes_url_helpers.order_url(object.number, only_path: true)
  end
```
Think it was something to do with zeus as you said. I had run the whole suite with zeus but it failed with the same error when run locally directly with rspec.

@lin-d-hop @pmackay could we please put the latest build on uk staging so I can see how it looks & performs?

**Comment by pmackay** [comment]
@stveep do you mean a particular branch that includes that change? 

If not, staging and prod have just been updated to commit just before v1.4 tag (slight annoyance with Buildkite not able to re-deploy same commit)

**Comment by stveep** [comment]
This is on the uk/account-balances branch - is it ok to deploy that? I don't really want to put it into master yet - I want to check how it looks with hub logos, localised currency and date formats etc., load speeds and also give @lin-d-hop and @NickWeir63 a chance to have a proper look at it.

https://github.com/openfoodfoundation/openfoodnetwork/commit/79808acd9f0d92847f5e8b606527ce43ae28805e

**Comment by lin-d-hop** [comment]
Aight @stveep that commit is now on staging.

Looking good too... will take a proper look once you are happy.

**Comment by NickWeir63** [comment]
Thanks @stveep this looks great.  the only minor request i have is to change the titles on the account screen.......
![screenshot 2016-02-03 09 46 08](https://cloud.githubusercontent.com/assets/10517702/12778800/c18d6a7e-ca5c-11e5-8592-5a71d822bb42.png)

....to read:
Transaction
Date & time
Payment state
Shipping state
Value
Balance

Otherwise seems to be working fine
Thank you
N

**Comment by NickWeir63** [comment]
...and one other minor point.  I think that the red £3.69 below should be a green -£1.29
thanks
![screenshot 2016-02-03 10 07 29](https://cloud.githubusercontent.com/assets/10517702/12779137/53394230-ca5e-11e5-9098-d6bacfeb2509.png)

**Comment by stveep** [comment]
OK I think this is just about ready. There are a couple of minor things that I couldn't figure out:

- Translation issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/827
- The scroll jumps to the wrong place when the orders table for a hub is open/closed - particularly noticeable when you close a hub with a large order list. I think because opening a big table changes the position of all the #anchors and I guess it goes to the old position. I can't figure out how to adjust any of this.
- Can't select text (on chrome) in the orders table (e.g. to copy). I have no idea why this is - something to do with active table?

I'll put a PR in now; let me know if you want me to make any changes. @oeoeaio @RohanM @mkllnk @daniellemoorhead

**Comment by stveep** [comment]
PR updated, the translation issue is now sorted out.

**Comment by daniellemoorhead** [comment]
Hey @stveep if we get the pull request #832 sorted before the deployment on Wednesday can we then add this feature to release 1.5? If so, @sstead will need to know so she can add it to the release notes. Cheers!

**Comment by stveep** [comment]
Yes happy for it to go in if you are! Suggested release notes:
"Account page now lists order and payment history organised by hub and shows any outstanding balance or credit with each hub."

**Comment by daniellemoorhead** [comment]
@stveep now that we've merged #832 can we close this issue? Or did you want to use this for the few tweaks still to come before it's considered completed?

**Comment by stveep** [comment]
Will use discourse for any further tweaks.

**Comment by daniellemoorhead** [comment]
@sstead see above comment from @stveep for suggested release notes comment :)
