### ISSUE TITLE
Bump karma version to latest possible

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6162]
### What we should change and why (this is tech debt)
We are using karma 0.13.22 released in 2015. Karma latest version is 5.2.3.

### Context
This was raised by dependabot alerts with security vulnerabilities on karma 0.13.22 dependencies.

### Impact and timeline
Karma is only a dev dependency so this is not a security vulnerability in prod. Anyway, this upgrade should be easy to do and will bring the benefits of later versions of karma :+1:

**Comment by sauloperez** [comment]
Latest karma is 6.0.1. See https://github.com/openfoodfoundation/openfoodnetwork/pull/6711.

**Comment by Matt-Yorkley** [comment]
`v0.x.x` -> `v6.x.x ` :open_mouth: 

Dependabot suddenly thinks we're a cutting-edge Rails app since we moved to Ruby 2.4.4 :trollface:

**Comment by Matt-Yorkley** [comment]
Closing; we've bumped it several times.

**Comment by luisramos0** [comment]
ah, yes, nice!
