### ISSUE TITLE
Ability to delete E2Es that have been granted TO my enterprise.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#619]
![image](https://cloud.githubusercontent.com/assets/10843056/8612165/753bb32e-270f-11e5-9b00-e4826c27c5d5.png)

## Update from Myriam
Retested march 2018 and still the issue:
https://www.useloom.com/share/65125d0faa674d90bdbe0dbd31dcc1f8

## Expected behavior:
The enterprise who was granted an E2E permission can delete that permission. So when I click on "delete" and "confirm" the relationship should be deleted.

## Severity
s4

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by daniellemoorhead** [comment]
@sstead still an issue?

**Comment by sstead** [comment]
Yep, still an issue

**Comment by lin-d-hop** [comment]
duplicate #7963 

#gitcull21
