### ISSUE TITLE
[mobile ux] Correct alignment on "ready for" field on Ipad

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6199]
## Description

On an iPad, the ready for field does not show up vertically centered.

A 1em/16px padding you be introduce above the dropdown.

## Steps to Reproduce
1. Go visit an open shop with an Ipad

## Animated Gif/Screenshot

Landscape

![image](https://user-images.githubusercontent.com/6525576/96258834-e8dd0800-0fbc-11eb-9f67-32221d82ea2c.png)

Portrait

![image](https://user-images.githubusercontent.com/6525576/96258861-f5616080-0fbc-11eb-968a-4b82c829d615.png)

## Workaround
None

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v3.2.10
* Browser name and version: Firefox, Chrome & Safari
* Operating System and version (desktop or mobile): Tablet

**Comment by RachL** [comment]
@luisramos0 @Matt-Yorkley I was supposed to open this issue out of https://github.com/openfoodfoundation/openfoodnetwork/issues/4572#issuecomment-704183647 but playing with it on staging FR where the latest release is I can't find a way to reproduce it. Was this fix like in the ages that took me to create this issue? :D

**Comment by RachL** [comment]
@luisramos0 @Matt-Yorkley forget my comment I know see that this is an iPad- specific issue !

**Comment by luisramos0** [comment]
yes, browser stack required :+1:

**Comment by luisramos0** [comment]
actually it's just ipad mini.
I dont see it on "ipad mini 2019" in browser stack, but this was replicated in an ipad mini 3 and an ipad mini 4.

**Comment by RachL** [comment]
I also managed to reproduce on Ipad 7 and the latest Ipad Pro.

**Comment by Erioldoesdesign** [comment]
Is this likely because ipad mini's media query breakpoints are unusual?

**Comment by jibees** [comment]
Hi,
I'm trying to reproduce this issue, but I can't do it.
Unfortunately, I do not have any (functional) iPad device at home, so my question is: 
_does this issue needs a real iPad device or you reproduced it from google chrome inspector or browserstack ?_

(btw, @filipefurtad0 did some test on iPhone device around this component : https://github.com/openfoodfoundation/openfoodnetwork/pull/6611#issuecomment-756409742)

**Comment by RachL** [comment]
@jibees I'm sending you the browserstack credential per Slack. We have a password manager but unfortunately we have reached our max number of persons on it, something we need to fix.
