### ISSUE TITLE
Error message when creating an order in BO

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6205]
## Description

When you create an order in back office, an error is displayed when you landing on the page to select products

## Expected Behavior
Error should be displayed only when getting to next steps without product, not landing on the page

## Actual Behaviour

Errors shows up when landing on the page

## Steps to Reproduce
1. Go on to `admin/orders?q[s]=completed_at+desc`
2. Click on "new order"
3. See the flash message when landing on the list of products

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/96287183-d1fcdc80-0fe1-11eb-8c38-42ca0ee869a7.png)

## Workaround
Just wait for the message to fade away

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v3.2.11
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Both

**Comment by Erioldoesdesign** [comment]
no design needed.

Had a look at the CSS and saw this weird div called 'flash error' that has changes state after a few seconds to display:none; and that's how it disappears.

![Screenshot 2020-11-03 at 14 38 30](https://user-images.githubusercontent.com/11681324/97998708-5b821c00-1de2-11eb-87d9-7ec9dcd36ceb.png)

**Comment by jibees** [comment]
for history, it has already been done: 38c25c412f5e09015d2f5a3c35b28a5a5a5320bb
