### ISSUE TITLE
Wordpress formatting tweaks to improve visual appeal of documentation

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#622]
4 requests :)

1) Can we make Heading 1 a bit smaller? It can look too large, especially for longer headings which use >1 line... e.g. http://openfoodnetwork.org/platform/user-guide/hubs-set-up-guide/create-or-connect-with-supplying-producers/

2) The tabs element in wordpress's visual composer needs formatting. Currently the fonts and colours don't match the rest of the site. Doesn't need anything fancy, just to look like rest of pages. Here's an example page using tabs- http://openfoodnetwork.org/platform/user-guide/advanced-features/enterprise-to-enterprise-permissions-e2es/

3) The accordion element in wordpress's visual composer also needs formating. Here is an example page using the accordion - http://openfoodnetwork.org/platform/user-guide/faqs/hub-faqs/

4) Can we change the colour of the scroll bar? Black on dark grey is very hard to see. I feel like I'm clicking blindly.

**Comment by sstead** [comment]
@kirstenalarsen could points 2 and 3 get slightly pipelined? Not life and death, but would be nice.

**Comment by kirstenalarsen** [comment]
pop it into milestone Aus - Next Up and we can consider in next sprint plan
