### ISSUE TITLE
Unable to remove Coordinator Fee from Order Cycle

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#6224]
## Description

Once an enterprise fee has been selected for 'Add Coordinator Fee' (page 1 of hub OC: General Settings), it can not be removed (it can be changed to a different enterprise fee though)

## Expected Behavior

1. Create Order Cycle and add Coordinator Fee to page 1 (General Settings)
![cfee1](https://user-images.githubusercontent.com/45104035/96574679-ade21980-12c7-11eb-8277-e69f3d608e08.jpg)
2. Complete the rest of the Order cycle set up and return to Order Cycle List
3. Edit Order Cycle
4. Remove Coordinator Fee and press save 
![cfee2](https://user-images.githubusercontent.com/45104035/96574802-d4a05000-12c7-11eb-9632-76603abf5432.jpg)
5. Return to Order Cycle List
6. Edit Order Cycle for 2nd time.
7. No Enterprise Fee is present on page 1 (General Settings) under the Coordinator Fee section.

## Actual Behaviour

1-5 as Expected Behaviour
6. Edit Order Cycle for 2nd time.
7. Enterprise Fee removed in step 4 is present.
![cfee1](https://user-images.githubusercontent.com/45104035/96575039-25b04400-12c8-11eb-8139-727c01343c24.jpg)

## Steps to Reproduce

1. Create Order Cycle with Coordinator Fee, return to Order Cycle list
2. Edit Order Cycle created in step 1
3. Remove Coordinator fee and press save. Return to Order Cycle list
4. Edit Order Cycle for a 2nd time and note that Coordinator fee removed in step 3 is reinstated.

## Workaround

Close the Order Cycle and open a new one without the associated fee.

## Severity

bug -s3
The work around is annoying as a lot of hubs will clone order cycles. If the OC which they clone has a coordinator fee but the one they wish to set up doesn't then they will have to spend extra time creating a new OC from scratch

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by tschumilas** [comment]
Echoing the point that the workaround is only really a workaround if the hub has realtively few suppliers.   Hubs here with 75 suppliers,  many with their own supplier fees,  will have a very time consuming task to set up new order cycles every week instead of cloning.  I understand its an s3 because there IS a workaround.   I'm just noting -  that sometimes the workaround isn't really practical.  Pleading for an s2.   Other thoughts?
