### ISSUE TITLE
Upgrade Active Merchant

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6225]
### What we should change and why (this is tech debt)
We can upgrade from v1.78 to v1.98 (Stripe payment intents) or v1.109 (stripe setup intents) or latest v1.113.

V1.109 would be useful in #4723

### Context
StripeSCA implementation needs new features to integrate with new Stripe API like payment intents and setup intents.

We do have a copied version from v1.98 in our repo that is being used by StripeSCA:
github.com/openfoodfoundation/openfoodnetwork/tree/master/lib/active_merchant/billing/gateways/stripe_payment_intents.rb
This should be deleted in favor of the code inside active merchant dependency.
There are some minor changes done to this file on our side we will need to handle in some way...
https://github.com/openfoodfoundation/openfoodnetwork/commit/6bb04f6cc6992ad40169ed22d4b19ca9909f4928#diff-19492101b546175aa3ca6a16ec7d0a610d0adae03cbaf130eff54092dec8e0fbR150

### Impact and timeline
Maybe done as part of StripeSCA.

**Comment by andrewpbrett** [comment]
`activemerchant (~> 1.109.0) was resolved to 1.109.0, which depends on ruby (>= 2.5)`

😭 😁
