### ISSUE TITLE
Missing translations on date picker (Orders pages - edit and bulk management)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6226]
## Description

Translation seems to be missing on the date picker, for both the Bulk order management and the Orders page. Observed while testing #5928.

## Expected Behavior

Different languages can be displayed on these date pickers, by choosing another languages other than English.

## Actual Behaviour

Only English is displayed on the date pickers in these pages, despite having selected other languages.

## Steps to Reproduce

1. Choose a language other than English ans log in as admin/hub manager
2. Visit `/admin/orders` or `/admin/orders/bulk_management`
3. Click on one of the date fields (see pics)
4. See missing translation

## Animated Gif/Screenshot

Bulk order management page:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/bb58201f-c1fa-4a8c-aa4e-25fe371aa323)

Orders page:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/b1b67768-9768-483c-bfb4-d66ad2859c47)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.2.11
* Browser name and version: Firefox 86 
* Operating System and version (desktop or mobile): Desktop/Ubuntu 20.04

**Comment by nikhilt99** [comment]
Hey, this is my first time working with this codebase. Me and my friend will work on this issue. Thanks :)

**Comment by ankis17** [comment]
> Hey, this is my first time working with this codebase. Me and my friend will work on this issue. Thanks :)

I'm the friend that will also work on this issue with Nikhil!

**Comment by sigmundpetersen** [comment]
Thank you @nikhilt99 and @ankis17, and welcome to OFN 🎉 
You can also connect to other devs on our [Slack #dev channel](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A) if you need any help.

**Comment by ankis17** [comment]
Hey - Nikhil and I were able to submit a pull request that may close this issue. It passes all the CI tests currently. Do we have to notify anyone to get the code that we modified reviewed?

**Comment by andrewpbrett** [comment]
Hi @ankis17 - this got stuck behind some high priority items in the Code Review queue, but I just left a review on it now.
