### ISSUE TITLE
Enterprise Relationships page- suggested changes to improve usability.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#623]
• Change 'everything' to 'select all' - people are more familiar with this concept.
• In the documentation I abbreviated the 4 different E2E permissions to... P-OC, P-VO, P-P, P-Profile.
Can we have the interface using the same abbreviations somewhere on this page? Or if we don't want to lock in these abbreviations, or if you have another idea for naming convention, speak up and I'll start using that instead.
- Kothagunda suggested that there should be checkboxes to select and delete relationships in bulk. This would be helpful for cleaning up after a shop closes in my experience.

• I think we need a link to the documentation on this page... perhaps also a table like this... dropping down from the top (could have show/hide option)... or the "What's this?" type help pop-ups we have on other pages.

![image](https://cloud.githubusercontent.com/assets/10843056/8664602/b4e851fc-2a1c-11e5-81b7-192321b6b614.png)

**Comment by myriamboure** [comment]
Another thing I would add to that is to enable to modify the E2E like just remove one permission. Today you have to delete it all ad recreate a new one, you cannot modify it.
Iceboxed here https://community.openfoodnetwork.org/t/hubs-can-easily-navigate-back-office-and-manage-their-shopfront/1246 in part of "hub manager UX improvement" 
#gitcull2018
