### ISSUE TITLE
Remove Pin Payments payment gateway

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6231]
### What we should change and why (this is tech debt)

As debated/decided [here](https://community.openfoodnetwork.org/t/product-curation-meeting-23-notes-20-october-2020/2099/2?u=rachel) the Pin Payments feature is to be removed from the OFN codebase.

### Context

This first came to light when rolling out v3, where it was spotted that only one AU-customer was using this payment method.

### Impact and timeline

This should simplify the codebase and the upgrade from Rails 4.0 -> 4.1

**Comment by mkllnk** [comment]
It's still used:
```
Spree::Payment.where(payment_method_id: Spree::PaymentMethod.where(type: "Spree::Gateway::Pin").select(:id)).maximum(:created_at)
=> 2020-11-11 06:29:59 UTC
```

It's used by The Bicycle Baker @kirstenalarsen :
```
Spree::Payment.where(payment_method_id: Spree::PaymentMethod.where(type: "Spree::Gateway::Pin").select(:id)).where("spree_payments.created_at > ?", 1.year.ago).includes(order: :distributor).map(&:order).map(&:distributor).uniq.map(&:name)
=> ["The Bicycle Baker"]
```

**Comment by luisramos0** [comment]
yes, ping @kirstenalarsen 
I raised that point here:
https://community.openfoodnetwork.org/t/product-curation-meeting-24-notes-20-october-2020/2099/3?u=luisramos0

**Comment by mkllnk** [comment]
The enterprise is moving towards another payment method. We asked them to do it within two weeks.
