### ISSUE TITLE
Resize product images on all servers

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#6236]
## Description

The new shopfront design will need larger images. On each production server, we will need to

1. change the style for small product images on `/admin/image_settings/edit` to `227x227#` and then
2. regenerate the small product images

```sh
cd ~/apps/openfoodnetwork/current/
screen bundle exec rails console production
$ Spree::Image.find_each { |image| image.attachment.reprocess!(:small) rescue nil } 
# Press keys to detach screen: ctrl a, d
```

Servers with regenerating in progress:

- [x] be-prod
- [x] es-prod
- [x] fr-prod
- [x] uk-prod
- [x] de-prod
- [x] ca-prod
- [x] us-prod
- [x] au-prod

## Acceptance Criteria & Tests

1. Go to a shopfront and find a product with an image.
2. Right-click on the image and select "View Image Info".
3. The image size needs to be 227x227 pixels.
4. Log into the console and find a recent image:

```rb
Spree::Image.order(:id).last.attachment.url(:small)
```

Servers with confirmed larger images:

- [x] be-prod
- [x] es-prod
- [x] fr-prod
- [x] uk-prod
- [x] de-prod
- [x] ca-prod
- [x] us-prod
- [x] au-prod

**Comment by mkllnk** [comment]
The last three servers are still processing images. Once that's done, someone has to check that it worked.

**Comment by Matt-Yorkley** [comment]
Looks good on all instances except Aus, where the images are still the old size (112x112). I can update them today.

Okay, so the if images required for the product listing are all recreated in advance, the only remaining issue is the discrepancy between the "forced-jpg" and "non-forced-jpg" configurations. I've just changed this on `de-prod`, so it now has the same config as the other instances and the relevant thumbnails have been recreated. See: https://github.com/openfoodfoundation/openfoodnetwork/pull/6223#issuecomment-714419873

So now if we just do a little more thumbnail-recreating on `au-prod` before the next release is deployed, nothing is blocked.

**Comment by Matt-Yorkley** [comment]
I'm updating a small subset of the thumbnails on `au-prod` now to make sure the resizing of `:small` thumbnails for existing `.jpg` images is complete. I couldn't see any related processes that are currently running with either `screen -ls` or `ps faux`.

**Comment by Matt-Yorkley** [comment]
Cool, that first bit is done. There's one more step to do, but I'll do it tomorrow during Aus nighttime :+1:

**Comment by Matt-Yorkley** [comment]
The last job is to remove the `:jpg` constraint on `:mini`, `:small` and `:large` thumbnails (in the UI), and run this:

```ruby
Spree::Image.where("attachment_file_name NOT LIKE '%.jpg'").find_each { |image| image.attachment.reprocess!(:mini, :small, :large) rescue nil }
```

**Comment by Matt-Yorkley** [comment]
Last job in progress now...

**Comment by Matt-Yorkley** [comment]
We now have a single standardised image config across all production servers :tada:
