### ISSUE TITLE
Staging-FR: Matomo tracking opt-out message showing incorrectly

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6239]
## Description

The Matomo tracking option seems not to be displayed incorrectly on staging-FR.

## Expected Behavior

This should be displayed on `#/policies/cookies`, in the Statistics Cookies - see for example staging-AU (https://staging.openfoodnetwork.org.au/#/policies/cookies).

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/5b44a837-ad58-4d1e-a6b1-965254e5ee05)

## Actual Behaviour

On staging-FR:

Chrome
![image](https://user-images.githubusercontent.com/49817236/96863487-dc462d00-145e-11eb-9e68-9b4f9cccf7f6.png)

Firefox
![image](https://user-images.githubusercontent.com/49817236/96863542-f122c080-145e-11eb-898c-8119fa683b6a.png)

## Steps to Reproduce

Currently only reproducible for staging-FR, as the staging server needs to be connected to Matomo for the message to be correctly displayed.

0. Check the settings on Matomo and the staging server, to make sure it's correctly connected and tracking is possible.
1. Login as superadmin on staging-FR
2. Go to Configuration
3. Enable all options on Legal Settings:

![image](https://user-images.githubusercontent.com/49817236/96863344-a739da80-145e-11eb-8cf8-9fdd899c5bfd.png)

4. visit `https://staging.coopcircuits.fr/#/policies/cookies`
5. See the error

## Severity

Affects staging servers only and testing:
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
@filipefurtad0 if the staging is not connected with Matomo, I think this is correct, no?

**Comment by filipefurtad0** [comment]
Yes, good point @RachL .
I think that's correct behavior for staging-UK and -ES. I'll update the issue above and remove those instances. Also, I'll add in "Steps to reproduce" that the staging server should be connected to Matomo, to verify this bug (as staging-FR currently is).

**Comment by filipefurtad0** [comment]
I had another look at this, while testing #7477 after re-connecting staging-FR with Matomo (tracking was lost since the Strasbourg fire). This is working correctly now, so we can close this issue:

![image](https://user-images.githubusercontent.com/49817236/117193515-da303400-adda-11eb-842a-9fdeb664a518.png)

To make this work the server needed to be re-connected to Matomo - it's working again:

![image](https://user-images.githubusercontent.com/49817236/117193667-0cda2c80-addb-11eb-9d69-3087fec399f5.png)

Re-enabling it was done by:

-  copying the Install code (found under Tag Manager > Install Code):

![image](https://user-images.githubusercontent.com/49817236/117194319-de108600-addb-11eb-9b73-a81c9051c37d.png)

And the site ID, as seen/set here:

![image](https://user-images.githubusercontent.com/49817236/117194677-48c1c180-addc-11eb-9345-f80b87386817.png)

![image](https://user-images.githubusercontent.com/49817236/117194941-9c340f80-addc-11eb-8f5a-b13d08dae078.png)


The Matomo settings (`/admin/matomo_settings/edit`, as superadmin):

![image](https://user-images.githubusercontent.com/49817236/117194241-c0dbb780-addb-11eb-90a1-d373ad476ed0.png)
