### ISSUE TITLE
Translation key missing -- 'no products in inventory'

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#6249]
## Description
On the order cycle page,  the message 'no products in inventory' appears if the supplier has not created products.  I don't think there is a key to translate this now.

It needs to be translated to 'no products'.  The reference to 'inventory'  is confusing and incorrect.   The message is meant to tell the order cycle coordinator that this supplier has not created products yet.   

## Expected Behavior
We should be able to translate the phrase  to 'no products'

## Actual Behaviour
'no products in inventory'  causes the order cycle coordinator to tell the supplier to create an inventory and put products there.  This is resulting in users creating inventory listings when they do not need to.

## Steps to Reproduce

1.create a hub with at least 1 supplier who has no products
2.visit the OC creation page -  see the message when you try to add this supplier
3.look in transifex for the string  -  I think its missing
4.

## Workaround

No workaround 

## Severity
s2

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by tschumilas** [comment]
Is this a possible papercut?  CAn I get an estimate please @kirstenalarsen @RachL @lin-d-hop @luisramos0 @filipefurtad0 ?  If it is,  I'd like it considered please.

**Comment by efgalvao** [comment]
This one is to add a key to the info "No Products" in all languages ?
Can I try this one ?

**Comment by RachL** [comment]
sure @efgalvao :) Thank you so much!
