### ISSUE TITLE
[mobile UX] Eur symbol displayed below the price of the item

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6252]
## Description

In the shopfront and when using a mobile device, the Eur currency symbol is displayed below the price of the item. This is observed only for:
• mobile devices
• items with prices in EUR
• prices with 4 digits

See pic below.

## Expected Behavior

Eur currently symbol should be displayed like this  - i.e., after the price:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/814a9833-d7de-46f4-a4b3-0c97a84e71db)

## Actual Behaviour

Eur currently symbol is displayed like this - i.e., below the price:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/35449d99-d31a-462a-ada2-c8262e94a228)

## Steps to Reproduce

1. Got to Browserstack and choose a mobile device (tested for Android/iPhone Firefox/Chrome/Safari).
2. Choose a shop with Eur currency and items with price which are at least 4 digits long 
3. Browse through the products and see the bug.

## Animated Gif/Screenshot

Below, left side - staging-UK - pound currency is correctly displayed. Compare with pic on the right side staging-ES, Eur currency below the price (red arrows):

![image](https://user-images.githubusercontent.com/49817236/97181479-3b73ac80-1793-11eb-8ce7-b78dfbf670b8.png)

## Workaround

Rotating your device 90°.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.3.0
* Browser name and version: Firefox 81 
* Operating System and version (desktop or mobile): Mobile Android

**Comment by RachL** [comment]
@filipefurtad0 do you know if the position of the currency symbol is tested automatically ? I forgot but for example I think this bug might not appear in pound for example as the currency symbol is located before the amount.

**Comment by filipefurtad0** [comment]
@RachL I don't know if this is tested automatically, I had a look at some specs and found nothing.

In any case, it should not appear in pound - this is what I wanted to show with the pic above... (left side, UK) Maybe I should add some text/green arrows to it, to make it more clear? I'll edit the description.

**Comment by RachL** [comment]
no sorry it's on me @filipefurtad0 on my phone github wasn't showing me the left image 🤦

**Comment by andrewpbrett** [comment]
I was able to reproduce this by just changing the configuration to show the currency symbol after the amount (without changing to Euro, that is). Fix is on the way.
