### ISSUE TITLE
"send test mail" results is hidden by other message

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#6259]
## Description

When some shop/enterprise configured in readonly mode (listing products only) the mail test results is hidden by message about "shipping and payment methods not enabled"

## Steps to Reproduce

1. switch enterprise to listing products only
2. click on "send test mail" in /admin/mail_methods/edit
3.
4.

## Animated Gif/Screenshot

![vokoscreenNG-2020-10-27_11-08-00 mkv](https://user-images.githubusercontent.com/928628/97276204-f1003780-1847-11eb-86d8-1fa34f17a6f9.gif)

## Your Environment

* Version used: 3.3.0
* Browser name and version: FF 78.4.0esr
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment]
This won't be an issue anymore with admin_style_v3 🎉
