### ISSUE TITLE
RU: Missing translation "Password Confirmation"

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#6262]
## Description

In path "/account#/settings"
But "password_confirmation" key is translated

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/97313925-36d4f400-1878-11eb-9fbb-a728a05328f2.png)

## Your Environment

* Version used: 3.3.0
* Browser name and version: FF 78
* Operating System and version (desktop or mobile): Desktop

**Comment by efgalvao** [comment]
I will try this one.
