### ISSUE TITLE
Clicking the current tab on the Account page hides that tab

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6265]
## Description
If you click on the current tab on the Account page (e.g. Credit Cards), the tab content disappears. Clicking again brings it back. 

## Expected Behavior
The tab content should remain visible.

## Actual Behaviour
The tab content disappears.

## Steps to Reproduce

1. Visit account page
2. See Orders visible
3. Click Orders
4. Content disappears

## Animated Gif/Screenshot
<img width="1430" alt="Screen Shot 2020-10-27 at 3 54 03 PM" src="https://user-images.githubusercontent.com/35588/97370624-a644e680-186c-11eb-9445-281260740187.png">

## Workaround
Clicking the tab again brings the content back.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
Safari on macOS Catalina

**Comment by KnifeHand** [comment]
It looks like the object for that page is set up like a toggle or a button.

**Comment by andrewpbrett** [comment]
Hi @KnifeHand I believe it's in `app/views/spree/users/show.html.haml` 👍
