### ISSUE TITLE
500 error while access /admin URL

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#6273]
## Description

Whel OFN interface in RU locale and user has more than one enterprise, then this user (enterprise manager) or super admin can't access /admin page because of 500 error. 
When OFN interface in EN locale, all Ok.

## Expected Behavior

/admin should opens

## Actual Behaviour

error 500

```
I, [2020-10-30 16:49:56#1906]  INFO -- : Started GET "/" for 127.0.0.1 at 2020-10-30 16:49:56 +0300
I, [2020-10-30 16:49:56#1906]  INFO -- : Processing by HomeController#index as */*
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/_register_call.html.haml (0.4ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/_page_alert.html.haml (2.1ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_alert.html.haml (3.1ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered home/_tagline.html.haml (0.9ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered home/_brandstory.html.haml (1.1ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered home/_system.html.haml (1.2ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered home/_cta.html.haml (0.3ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered home/_stats.html.haml (1.2ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/_register_call.html.haml (0.6ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/_footer.html.haml (14.3ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered home/index.html.haml within layouts/darkswarm (34.9ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/_ie_warning.html.haml (0.7ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_language_selector.html.haml (0.6ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_signed_out.html.haml (0.3ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_cart.html.haml (0.3ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_large_menu.html.haml (14.1ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_mobile_menu.html.haml (9.7ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_signed_out.html.haml (0.2ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_offcanvas_menu.html.haml (14.1ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_cart_sidebar.html.haml (2.0ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered shared/menu/_menu.html.haml (42.3ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered layouts/_bugsnag_js.html.haml (0.1ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered layouts/_i18n_script.html.haml (0.2ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered json/_injection_ams.html.haml (0.3ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered json/_injection_ams.html.haml (0.2ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered json/_injection_ams.html.haml (0.3ms)
I, [2020-10-30 16:49:56#1906]  INFO -- : Read fragment views/inject-all-taxons-1603736595 (0.5ms)
I, [2020-10-30 16:49:56#1906]  INFO -- : Read fragment views/inject-all-properties-1601978771 (0.4ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered json/_injection_ams.html.haml (0.2ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered json/_injection_ams.html.haml (0.1ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered layouts/_bugherd_script.html.haml (0.6ms)
I, [2020-10-30 16:49:56#1906]  INFO -- :   Rendered layouts/_matomo_tag.html.haml (2.5ms)
I, [2020-10-30 16:49:56#1906]  INFO -- : Completed 200 OK in 108ms (Views: 97.1ms | ActiveRecord: 5.7ms)
I, [2020-10-30 16:49:57#1906]  INFO -- : Started GET "/admin" for 127.0.0.1 at 2020-10-30 16:49:57 +0300
I, [2020-10-30 16:49:57#1906]  INFO -- : Processing by Spree::Admin::OverviewController#index as HTML
I, [2020-10-30 16:49:57#1906]  INFO -- :   Rendered admin/shared/_user_guide_link.html.haml (1.4ms)
I, [2020-10-30 16:49:57#1906]  INFO -- :   Rendered spree/admin/overview/_products.html.haml (4.8ms)
I, [2020-10-30 16:49:57#1906]  INFO -- :   Rendered spree/admin/overview/multi_enterprise_dashboard.html.haml within spree/layouts/admin (14.3ms)
I, [2020-10-30 16:49:57#1906]  INFO -- : Completed 500 Internal Server Error in 115ms
F, [2020-10-30 16:49:57#1906] FATAL -- : 
ActionView::Template::Error (translation data {:zero=>"У Вас нет активных товаров.", :one=>"У Вас один активный товар.", :other=>"У Вас %{count} активных товаров."} can not be used with :count => 3):
    12:     - if @product_count > 0
    13:       %div.seven.columns.alpha.list-item
    14:         %span.six.columns.alpha
    15:           = t(".active_products", count: @product_count )
    16:         %span.one.column.omega
    17:           %span.icon-ok-sign
    18:       %a.seven.columns.alpha.button.bottom.blue{ href: "#{admin_products_path}" }
  app/views/spree/admin/overview/_products.html.haml:15:in `_app_views_spree_admin_overview__products_html_haml___2357011212132846962_47459167848800'
  app/views/spree/admin/overview/multi_enterprise_dashboard.html.haml:16:in `_app_views_spree_admin_overview_multi_enterprise_dashboard_html_haml___2387861174485615688_47459168251800'
  app/controllers/spree/admin/overview_controller.rb:15:in `index'
```

## Steps to Reproduce

1. create for user two enterpises
2. open /admin
3.
4.

## Animated Gif/Screenshot

![vokoscreenNG-2020-10-30_17-05-30](https://user-images.githubusercontent.com/928628/97714547-60895780-1ad2-11eb-83e6-f0f14ffeb8f0.gif)

## Workaround

web server rewrite from /admin to /admin/enterprises ?

## Your Environment

* Version used:3.3.0
* Browser name and version: FF 78.4.0esr, Chromium 86.0.4240.111
* Operating System and version (desktop or mobile): Desktop, Opensuse 15.2

**Comment by romale** [comment]
this is a workaround to prevent the user from getting a 500 error. Instead of /admin, /admin/enterprises always opens

```
diff -u /etc/nginx/sites-available/ofn_443.conf.orig /etc/nginx/sites-available/ofn_443.conf
--- ofn_443.conf.orig   2020-10-20 13:07:48.000000000 +0300
+++ ofn_443.conf        2020-10-30 19:26:11.000000000 +0300
@@ -24,7 +24,8 @@
      if (-f /etc/nginx/maintenance.html) {
        return 503;
      }
-   
+
+     rewrite ^/admin$ /admin/enterprises permanent;
      gzip_proxied no-cache no-store private expired auth;
      proxy_http_version 1.1;
      proxy_set_header X-Real-IP $remote_addr;
```

**Comment by Matt-Yorkley** [comment]
I'm investigating this now. So far it seems like it only affects the Russian language and none of the others.

**Comment by Matt-Yorkley** [comment]
Okay it looks like the I18n gem might use different logic for Russian plurals: https://github.com/spree-contrib/spree_i18n/pull/88#issuecomment-6565948

I'll take a look and see if there's a nice way to resolve this...

**Comment by Matt-Yorkley** [comment]
Our current pluralisation generally has two forms, for "one" (1) and "other" (2+), eg: "1 bag", "6 bags". With Eastern Slavic languages there are four different forms here, which cover "one" (1), "few" (2-4), "many" (5-11), and then "other" (12+) and they each need separate translations. 

Is this correct @romale?

**Comment by Matt-Yorkley** [comment]
The error here is caused `rails-i18n` looking for keys for `:few` and `:many` in Russian when the given value is between 2 and 11, and the keys don't exist. I think for values that are either 1 or higher than 11, the error will not occur.

**Comment by Matt-Yorkley** [comment]
@romale the new keys have been merged, you should be able to set them in Transifex now, which should resolve the issue :+1:

**Comment by romale** [comment]
> Our current pluralisation generally has two forms, for "one" (1) and "other" (2+), eg: "1 bag", "6 bags". With Eastern Slavic languages there are four different forms here, which cover "one" (1), "few" (2-4), "many" (5-14), and then "other" (15+) and they each need separate translations.
> 
> Is this roughly correct, @romale?

In Russian, the singular (one, 1), the plural (1 <few <4) and also the plural (4 <many).
Other (none), is it possible '0' (zero)?
But, now a brain explosion:
1bag - 1коробкА (one)
20bags - 20коробОК (many)
21bags - 21коробкА (one)
22bags - 22коробкИ (few)
25bags - 25коробОК (many)
:)
I suggest leaving it as it is for now, the main thing is that it works :) Then we will work on the grammar (with the Russian community)

**Comment by romale** [comment]
> @romale the new keys have been merged, you should be able to set them in Transifex now, which should resolve the issue +1

ok, translated. Thank you @Matt-Yorkley !

**Comment by Matt-Yorkley** [comment]
> 1bag - 1коробкА (one)
20bags - 20коробОК (many)
21bags - 21коробкА (one)
22bags - 22коробкИ (few)
25bags - 25коробОК (many)

:exploding_head: 

The actual logic used in the `railsi18n` gem is here: https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/common_pluralizations/east_slavic.rb

I think it's covered already :+1:
