### ISSUE TITLE
[mobile ux] Markup visible in product descriptions on shopfront

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#6285]
## Description

Preview (first sentence/number of characters) of the product description is visible under product name on new shop front.
Any markup that has been used to format the product description is now displayed in the shopfront, unformulated in plain text. 
This is gibberish to the customer and confusing.

Product descriptions were not visible in the old shopfront so this was not previously an issue. 

## Expected Behavior

Code responsible for text formatting should be invisible.

## Actual Behaviour

Code for text formatting in product description is visible

## Steps to Reproduce

1. Create product. 
2. Write product description. Include a non-break-space and symbols in the first 40-50 characters.
3. Add product to order cycle
4. View product on shop front.

## Animated Gif/Screenshot

![ACMand](https://user-images.githubusercontent.com/45104035/97812971-f9f46d00-1c7c-11eb-9314-a787643af7ee.jpg)
![ACMandpop](https://user-images.githubusercontent.com/45104035/97812965-f8c34000-1c7c-11eb-941a-90ba7660531f.jpg)
![ACMpara](https://user-images.githubusercontent.com/45104035/97812967-f95bd680-1c7c-11eb-8bf3-abf651561000.jpg)
![ACMparapop](https://user-images.githubusercontent.com/45104035/97812968-f95bd680-1c7c-11eb-978d-4d76a130b0ff.jpg)
![ACMspace](https://user-images.githubusercontent.com/45104035/97812969-f9f46d00-1c7c-11eb-9b09-63ea974f4ef8.jpg)
![ACMspacepop](https://user-images.githubusercontent.com/45104035/97812970-f9f46d00-1c7c-11eb-8f31-269e2cff8042.jpg)

## Workaround

Re-write all product descriptions with symbols and formatting in the first line.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
Notes:
- I think some of this is down to the copy-paste behavior of different text editors
- We should be able to improve bits like `&amp;` and maybe adjust some of the content-stripping for things like `<!-- comments -->`
- We do need to be careful in general with parsing and displaying this content, for security reasons

**Comment by lbwright22** [comment]
Adding to this issue further concerns and irregularities with mark up appearing when it shouldn't in product descriptions. This is causing a lot of angst for UK users.

Copy and Paste Text into the Product Description field
1. Copy and paste (text and formatting): mark up appears when the user clicks 'update' to save their changes.
![proddescripcp](https://user-images.githubusercontent.com/45104035/100079302-64dc3280-2e3c-11eb-8b14-f4dcdd395801.gif)
2. Copy and paste (text and formatting), then highlight the inserted text, click on the remove formatting button on the editor: saved as in (1)
3. Remove text from product description or edit in another manner. DO NOT click update. Now copy and paste (text and formatting) text into the field. Highlight the pasted text. Click the 'remove formatting button'. Click update: random line breaks inserted.
![proddescripcpremoveformatingnoupdate](https://user-images.githubusercontent.com/45104035/100079722-ec29a600-2e3c-11eb-9ebe-891bca157749.gif)
4. Copy and paste (plain text only). Click update: no mark up appears.
![proddescripcpplaintext](https://user-images.githubusercontent.com/45104035/100079805-03689380-2e3d-11eb-86c2-5819c855aab6.gif)

**Comment by andrewpbrett** [comment]
@lbwright22 there's a partial fix going out on Tuesday with https://github.com/openfoodfoundation/openfoodnetwork/pull/6384. It doesn't address things like  and the general wonkiness however. Do you have a sense for the prevalence/priority of those issues? Is it worth making a separate issue for them?
