### ISSUE TITLE
Coordinator Enterprise Fee missing from products after editing order

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#6287]
## Description

Hub manager edits order in the back end to remove products which are out of stock.
After 'Update and recalculate enterprise fees' as well as the items removed from the basket (product price + fee), the enterprise fee for some other products is also removed.

Instance recorded so far: Bowhouse Link
Enterprise fee is added as 'coordinator fee'
order number R382744608
Bread removed from order (both loaves)
Enterprise fee also removed from the following products: Venison, Mallard, Partridge, Pheasant, Cinnamon Swirl, Pain au Chocolat, Croissant

## Expected Behavior

Edit an order in the back end and remove a product.
Update and recalculate fees.
Cost of product removed and its associated fee removed only from the customer's total

## Actual Behaviour

Edit an order in the back end and remove product
update and recalculate fees
Cost of product removed and enterprise fee associated with other products taken from customer's total.

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![BHOC](https://user-images.githubusercontent.com/45104035/97867113-2358db80-1d05-11eb-9685-1155c32d180e.jpg)
![BHorder1](https://user-images.githubusercontent.com/45104035/97867114-23f17200-1d05-11eb-9034-40bcd29f7748.png)
![BHorder1email](https://user-images.githubusercontent.com/45104035/97867116-248a0880-1d05-11eb-8725-3018d677ef14.png)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
Assigning a label of S2 while we investigate how wide spread this issue is.
If it impacts all enterprises and means that any item removed from an order renders the order total incorrect then this is a critical issue for order management.

If necessary we can workaround with adjustments, however this is unworkable across all orders and all enterprises. Hence S2.

**Comment by lbwright22** [comment]
I have tried the following to reproduce this error on the OFN UK demo hub but haven't been able to yet:

1. Set up an OC with coordinator enterprise fee (sales), flat percent. Add only products from hosting hub to OC. Order items, capture payment. Edit order by removing items. Update and recalculate fees-> results are consistent and enterprise fees on remaining items in the basket are correct.

2. Same as 1 but adding products from multiple producers and purchasing from range of producers before editing basket.  Results are consistent and enterprise fees on remaining items in basket are correct.

3. Same as 2 but change enterprise fee to admin fee (flat percent). Also only purchase from producers which are not the OC coordinator (same scenario as order R382744608). Results are consistent and enterprise fees on remaining items in basket are correct.

**Comment by tschumilas** [comment]
I've not been able to reproduce either.

**Comment by luisramos0** [comment]
what is the type of the enterprise fee?

**Comment by lin-d-hop** [comment]
Type: Admin
Calculator: Flat Percent

**Comment by lbwright22** [comment]
Checked all further orders which needed refunding for that enterprise and the producer.  No further problems encountered. As discussed with Lynne, since this was a one off and no one else has reported a similar occurrence, down graded to S3.
