### ISSUE TITLE
Apostrophe (') incorrectly displayed on Register page title (seen in French language)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6292]
## Description

The title of the register page is broken in French. This is caused by the incorrect display of the apostrophe (') character, which appears displayed as `&#39; `. 
This may be a general HTML encoding error, so the bug may affect other special characters and languages... other page titles as well? 

## Expected Behavior

The title of the /register page should render correctly, according to the Transifex translation:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e3001943-9bd7-45c0-93b8-e594ee6b4c62)

## Actual Behaviour

The title on the /render page is displaying the apostrophe character incorrectly (see pics below).

## Steps to Reproduce

1. Log in to any OFN server
2. Choose French language
3. Click on "Vous souhaitez proposer vos produits sur CoopCircuits ?   Démarrez ici " (gray banner, bottom of the hompage) or visit the /register
4. See the title of the page on the respective tab, or
5. Display the source page code of the /register page with `Ctrl + u`; look for the `<Title>` element

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/43d0cd5e-7ba7-4b56-9f5d-4fb2043de165)

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/64f387d0-bd52-4afd-ab17-331d3282ace1)

## Workaround

Using another language which does not this character on the title. Does this affect other special characters, as well?

## Severity

As a translation-related issue, I'm proposing:
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v.3.3.0
* Browser name and version: Firefox 81
* Operating System and version (desktop or mobile): Desktop, Ubuntu 20.04

**Comment by efgalvao** [comment]
Can I get this one ?

**Comment by RachL** [comment]
@efgalvao sure! Welcome :) If you need any help come and chat with us in the #dev channel on [our Slack](https://app.slack.com/client/T02G54U79) ;)

**Comment by efgalvao** [comment]
Thank you.
