### ISSUE TITLE
Improve documentation to set up production database + which repository to use?

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#630]
In the readme file, it's explained about how to install development and testing database, but how to install the production environment? We are installing the French version and are a bit fighting with the documentation... especially we had a question at the very begining: should we install the openfoodnetwork repository, or the ofn-deployment one? We started with the openfoodnetwork one... as we don't know about Ansible...

**Comment by pmackay** [comment]
I'm _starting_ to make better notes for this here http://community.openfoodnetwork.org/t/set-up-and-customisation-of-a-new-ofn/186. Could you feedback if it helps? If you're setting up a production environment on a server, ofn_deployment is the right thing to use.

**Comment by myriamboure** [comment]
I asked Sylvain, Christian and Gilles, who are doing the installation process in France, to look at it and see if that helps and give feedback. Thank you @pmackay :-)

**Comment by pmackay** [comment]
@myriamboure any feedback on whether this has improved now? Can we close?

**Comment by sigmundpetersen** [comment]
Remove from Norway Backlog milestone? Isn't this a global issue?

**Comment by pmackay** [comment]
@sigmundpetersen yes. Personally I think it would work better if there was just one backlog and labels were used for international or country specific interest. What do you think? Quite often the group implementing the issue isnt the same as the one who needs it anyway.

**Comment by sigmundpetersen** [comment]
Agreed, I think there should only be instance specific issues in the instance specific backlogs, like translations, regional customizations, business models etc. So usage and customization issues.

All functional and design related issues should be in Core Backlog, as we all upgrade our instances with the same releases don't we? (At least we should :) )

**Comment by myriamboure** [comment]
Yes you're right, sorry I see I have not answered that ping @pmackay :-)
@blancnic @marito59 do you think the documentation has improved on origina point mentionned in that issue? I remember we opened it when we was at Sylvain's place doing the very first installation... Can we close, or do you have any suggestion to share with @pmackay?

**Comment by marito59** [comment]
I have seen that the Wiki in Github has improved in content and structure and that's great. There is still a lot to discoverbut I think that the Github WIki is an helpful starting point.

**Comment by pmackay** [comment]
OK am going to close but please raise other docs issues if other specific things need improving.
