### ISSUE TITLE
New shop layout has header issues in desktop smaller window

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#6302]
## Description
When I loaded the new shop in a browser that is only half the width of my screen (very common, just happened to be how I had my browser sitting) it is quite a mess

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/0c75c5d4-a839-48d3-abbb-488f0a9319e3)

## Expected Behavior
It should switch decisively between desktop and ipad / smaller view - not sit in this 'in between' mess 

## Actual Behaviour
I start at wide desktop and gradually decrease screen width - goes from happy
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/57d750b3-23ae-4cba-9c27-9fded42df15f)

to abridged 'ready for field'
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/94ec290b-da10-4961-b0e5-20ccd951b914)

to header overlap chaos
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/0944f60d-9514-474c-8927-476b8986b08b)

to ipad / mobile

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/e9b0041a-f632-4093-9de2-74985a9061bb)

## Steps to Reproduce

1. Open a shop in desktop browser
2. Move the screen width

## Severity
S3? S2 - depends how prevalent it is?

## Your Environment
MAC OS, Safari - seems to switch much more quickly in Chrome and Firefox

**Comment by filipefurtad0** [comment]
This seems to happen for different desktop/browser combinations as well:

Browserstack - macOS sierra, high sierra, mojave / Safari versions
![image](https://user-images.githubusercontent.com/49817236/98097244-a7859d00-1e84-11eb-898f-e122d75bf3ca.png)

Browserstack - Windows 10 / Firefox
![image](https://user-images.githubusercontent.com/49817236/98097211-9b99db00-1e84-11eb-8bf2-280252f779a7.png)

Both Chrome/Firefox on Ubuntu
![image](https://user-images.githubusercontent.com/49817236/98097325-c5eb9880-1e84-11eb-9d77-640900b2c285.png)

**Comment by filipefurtad0** [comment]
The pics above only concern the header. I couldn't reproduce the piling up of the "ready for" field in the OC selector, even with a longer name. Which macOS / Safari versions were used in your pics @kirstenalarsen ?

**Comment by luisramos0** [comment]
The ready for issue is one of the outstanding issues in the Mobile epic:
https://github.com/openfoodfoundation/openfoodnetwork/issues/6196

I can't replicate on my ubuntu firefox...

Looks like you can easily replicate, I'd make this an S2. If a dev can replicate they will be able to fix it quickly.

**Comment by filipefurtad0** [comment]
Thanks Luis! Yes, it was quite straightforward to reproduce the header issue on my Ubuntu/Firefox. Bumping to S2. I'll move it to top DevReady as well.

As for the OC concerns:
I'm not sure what's reported here to be exactly the same as the issue #6196 . Above we see the text going _under_ the "Ready For" field, when the screen width is shrinked:

![image](https://user-images.githubusercontent.com/49817236/98152804-2e109d80-1eca-11eb-8a05-a8fdecf6fffc.png)

I can't seem reproduce this (this pic is a crop taken from description from Kirsten).

But I think this differs from Actual Behavior on issue #6196:
![image](https://user-images.githubusercontent.com/49817236/98152888-4bde0280-1eca-11eb-8240-e865526b0e5a.png)

which I can reproduce, with a longer "ready-for" text:
![image](https://user-images.githubusercontent.com/49817236/98153385-0241e780-1ecb-11eb-8d1e-0d070eb8fde4.png)

**Comment by sauloperez** [comment]
I can't manage to reproduce either in my Ubuntu FF 82.0.2

![Screenshot from 2020-11-06 13-54-13](https://user-images.githubusercontent.com/762088/98368394-916c0e00-2037-11eb-91f3-ff223b8f6e8a.png)

or in Browserstack with Windows Chrome 81

![Screenshot from 2020-11-06 13-56-17](https://user-images.githubusercontent.com/762088/98368563-dd1eb780-2037-11eb-9ef9-f92775c20880.png)


note I checked both Katuma's and AU's production.

**Comment by filipefurtad0** [comment]
Hey Pau,

I observed this in my system (same as yours) at these viewport widths (**see top-right corner**):

![overlapp_FR](https://user-images.githubusercontent.com/49817236/98374068-10f9dd00-2038-11eb-9b61-a8dc39ba6fa9.gif)

![overlapp_ES](https://user-images.githubusercontent.com/49817236/98374868-3509ee00-2039-11eb-8ad8-dfb651e55f3d.gif)


But, interestingly, I can't reproduce this now in staging-UK and -ES, which I used yesterday for testing... so, maybe there is a PR in master, fixing this and this will be gone as well, after deploy - next Tuesday?

**Comment by sauloperez** [comment]
ah I missed the scroll! got it.
