### ISSUE TITLE
Notify Producers Email includes Customer Names when Customer Names Report is checked.

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#6303]
EDITED TO ONLY FOCUS ON CUSTOMER NAMES
NEW ISSUE CREATED FOR NAME OF ORDER CYCLE 

## Description

This issue is discussed in Discourse [here](https://community.openfoodnetwork.org/t/notify-producers-email-to-include-customer-details/1311)

**As an Enterprise:** I want to give my Producers access to the information they need to aid with packing and administration of orders.  I currently do this by sending the Notify Producers Email which includes a list of Products that have been ordered. Many of my Producers use this email to pack by Customer and need Customer First Name & Last Name to pack the products ordered

As a result of https://github.com/openfoodfoundation/openfoodnetwork/pull/5769 I can now change my shop preferences so that Customer Names appear in the Reports that my Producers run on the platform. 

However, when i send the Notify Producers email to these same Producers, Customer Names are not included. Many of my producers don't run their own reports, and the only report they receive about Order Cycles is this Notify Producers Email. It is consistent and expected behaviour to include Customer Names in this email as well as in Reports.

 **The Notify Producers Email:** is generated and sent to all Producers in an Order Cycle when the Enterprise logs into the Edit Order Cycle page and selects the Notify Producers Button.

![Screen Shot 2020-11-04 at 3 33 17 PM](https://user-images.githubusercontent.com/47620442/98072599-7cb63b80-1eba-11eb-8e8d-830d8162b270.png)

**CURRENT BEHAVIOUR**

Currently, the Notify Producers email includes a a list of products summed by VARIANT. It looks like this:

![Screen Shot 2020-11-04 at 4 22 48 PM](https://user-images.githubusercontent.com/47620442/98072424-1b8e6800-1eba-11eb-8631-212e2cb78b46.png)

**DESIRED BEHAVIOUR**

The email should include Customer First and Last Names in the Notify Producers email when I have checked the box in Shop Preferences to show Customer Names in Reports.
![Screen Shot 2020-11-04 at 3 44 20 PM](https://user-images.githubusercontent.com/47620442/98070170-b7b57080-1eb4-11eb-985b-8aff58456d7e.png)
When the Customer Names in Reports button is checked by an Enterprise in Shop Preferences, the Notify Producers email should include an additional, second set of data.

Data set 1: (as per current) is a list of products, with totals summed by VARIANT as per the current email. 
Data set 2: (when button checked) is a list of products, with totals summed by CUSTOMER **and** including the Customer's First and Last Name. 

When the Customer Names in Reports button is NOT checked, the Notify Producers email would only include the following data set:

**Data set 1:**
Product / Variant Name
Quantity
Price
Subtotal
Included Tax

When the Customer Names in Reports button IS checked, the Notify Producers email would include the above data set **as well as** the  following data set:

**Data set 2**
Product / Variant Name
Quantity
First Name
Last Name

The layout of the two data sets would reflect this example provided by the UK  - except that it would not have the Customer’s Last Name xxxxxx out. 
 
![Screen Shot 2020-11-04 at 3 40 52 PM](https://user-images.githubusercontent.com/47620442/98069951-407fdc80-1eb4-11eb-8605-84300e13a53f.png)

## Acceptance Criteria & Tests

1.
2. 
3. 
4.

**Comment by lin-d-hop** [comment]
Hi @emilyjeanrogers 

I notice you've put two changes into this issue.

It is actually faster, easier and more reliable to just put one change in an issue. I know it sounds counterintuitive but when one PR means one change, means one thing to test, means one thing to roll back if things go wrong then the whole delivery process works better for everyone.

I say this so that you understand the logic for the future :-)

**Comment by emilyjeanrogers** [comment]
Ah yep OK thanks @lin-d-hop that does make sense. My logic was that having two things in a single issue felt sensible as they both involved adding content to the Notify Producers email. It felt like there'd be economies of scale to do them simultaneously - plus two birds / one stone! But I get why that could become complicated.

**Comment by sauloperez** [comment]
This seems larger than a Papercut because of the coding involved and potential pitfalls.

**Comment by kirstenalarsen** [comment]
Please make sure you include the link to where discussion inception happens on the issue @emilyjeanrogers just to speed things up when we're looking for history 
https://community.openfoodnetwork.org/t/notify-producers-email-to-include-customer-details/1311/39
also make sure is linked back the other way i.e. discourse includes link to github too

**Comment by emilyjeanrogers** [comment]
@sauloperez is it larger than a papercut because of the two tasks being together in the issue? Would either one of those tasks be papercut sized or are they both more complex?

**Comment by emilyjeanrogers** [comment]
> Please make sure you include the link to where discussion inception happens on the issue

Actually it was (or at least supposed to be) in the first sentence of the issue! But it looks like I didn't activate the link. Edited now so it's clickable.

**Comment by emilyjeanrogers** [comment]
I've edited this Issue to only focus on Customer Names. 
New Issue created for including Order Cycle Name - [Notify Producers Email Includes Name of Order Cycle](url)

**Comment by jaycmb** [comment]
Copied to Wishlist Repo, but kept in Welcome New Developers _Backend Hard_
