### ISSUE TITLE
Product edit: Cannot change Variant unit scale of an existing product

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6304]
## Description

After clicking the pencil to edit a previously created product the Variant unit scale dropdown appears empty, making it impossible to change units through this page.

This dropdown works fine, when creating a new product.

This works fine on bulk product edit.

## Expected Behavior

When editing a product, units should appear in the dropdown of Variant unit scale, and allow selection.

## Actual Behaviour

Variant unit scale dropdown appears empty, when editing a product.

## Steps to Reproduce

1. Click on the pencil to edit an existing product
2. Click on the dropdown just under Variant unit scale
3. The list should appear empty

## Animated Gif/Screenshot

![no_matches_found](https://user-images.githubusercontent.com/49817236/98111542-a5c5d480-1e98-11eb-8b6c-65f19e756e9d.gif)

## Workaround

Using Bulk Edit Products.

## Severity

Proposing this bug as s3?
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.3.1
* Browser name and version: Firefox 82
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

Maybe introduced by #6145 ? Adding the regression label as this was working till recently.
("recently" as in, it was working while testing PR #5978; stopped working after rebasing it)

**Comment by filipefurtad0** [comment]
@eugenichafer reported [earlier today](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1604686446399000), that there are issues with **product creation** as well, in Katuma (production). It seems, this depends on the customer path. I'm posting @andrewpbrett's "testing notes" on this issue :smile: 

If I go to the products page, and click new product, the units are there. But if I go from the products page to edit an individual product, no units show up. AND if I go from the edit product page and click on New Product from there, no units show

This was confirmed on the french production server, so the current workaround is to create new products from the products page `/admin/products`

**Comment by lin-d-hop** [comment]
This is being reported quite a lot in a number of different contexts.
I'm going to move up the code review queue.

**Comment by andrewpbrett** [comment]
I re-ran the tests and the PR is now green, just needs a second review. Is this possibly an s2? There is technically a workaround while creating a product, but for editing an existing product, the workaround is to delete it and recreate it... which feels like a pretty tedious workaround.

**Comment by Matt-Yorkley** [comment]
I encountered this in production yesterday, the dropdown was not working correctly in some cases.

**Comment by Matt-Yorkley** [comment]
To clarify; the dropdown was there, but depending on what option was selected, it would not show the selected option and would appear blank. It seemed to work for "items" but not for "weight"...?

**Comment by andrewpbrett** [comment]
I think this is a separate issue; previously, it was always blank, and not working across all production instances. At least on US production, I can click the edit pencil for a product and see the dropdown working correctly. @Matt-Yorkley was there a specific product on UK production that you were looking at where the dropdown was blank?

**Comment by andrewpbrett** [comment]
I investigated a bit more and I'm fairly confident this isn't the same issue. I'm going to re-close and say we should keep discussion on https://github.com/openfoodfoundation/openfoodnetwork/issues/6527
