### ISSUE TITLE
Reports: fix customer de-identification

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#631]
The Orders & Fulfilment / Customer Totals report has been amended to deal with permissions, so that if a User does not own or manage the Hub (but does own or manage the Producer), they can see the line items but the Customers' identifying details are empty

We need to update a bunch of older reports to carry this 'privacy' fix through, including
1. Orders and Distributors  
2. Bulk Co op Reports : Allocation, Customer Payments, Totals by Supplier, Packing Sheets
3. Packing Reports - both by Supplier and Customer  
4. Payment Reports

**Comment by RohanM** [comment]
@sstead Could you double check which of these reports actually have customer details and edit/remove above?

**Comment by sstead** [comment]
I went through all reports, and these are the ones that need customer details removed from the producer's view.

Orders and Distributors
This report shows the same for hubs and producers.
The fields in red are the Customer's details which should be blanked out to the producer.
![image](https://cloud.githubusercontent.com/assets/10843056/9080640/22e92608-3b99-11e5-8200-204c49b79be0.png)

Bulk Co-op
Totals by supplier- No customer info is displayed. Same view for producer and hub is fine.
Allocation- Shows allocation of product, assigned to customers, identified by name. The hub and producer see same report. Blank out customer name for the producer.
![image](https://cloud.githubusercontent.com/assets/10843056/9080651/4a0769b6-3b99-11e5-8214-8e17d33a93a4.png)
Packing Sheets- The hub and producer see same report. The customer is identified by name. Blank out customer name for producer.
![image](https://cloud.githubusercontent.com/assets/10843056/9080654/50a94d48-3b99-11e5-94cc-fe29c6ed565b.png)

Customer Payments- The hub and producer see same report. The customer is identified by name. Blank out customer name for producer.
![image](https://cloud.githubusercontent.com/assets/10843056/9080660/59c16fa0-3b99-11e5-939e-625eb4999053.png)


Pack by customer: 
- The hub and producer see the same thing. The customer first and last name should be blanked to the producer.
![image](https://cloud.githubusercontent.com/assets/10843056/9080667/6bac1972-3b99-11e5-91fe-4095d257d270.png)

Pack by Supplier:
- The hub and producer see the same thing. The customer first and last name should be blanked to the producer.
![image](https://cloud.githubusercontent.com/assets/10843056/9080672/70bf146e-3b99-11e5-8952-4a5520791494.png)

**Comment by lin-d-hop** [comment]
This looks like it was my additions that broke this. I am happy to take a look at this if you like, will try in the next couple days though tis my bday this weekend so more likely early next week.

**Comment by oeoeaio** [comment]
@sstead I've just pushed a fix for this through into staging, can you give it a test when you get a chance?

**Comment by sstead** [comment]
As a producer, supplying a hub... the only reports I can see which show the customer's name are the Sales Tax and two Xero reports. The rest are all showing 'HIDDEN' now :)

**Comment by sstead** [comment]
@oeoeaio Just testing the fix to this in staging2 now. The Sales Tax and Xero report are no longer visible to the producer who supplied a hub- they see no report. This is good from a customer privacy perspective. But just to be sure, the producer wouldn't need the GST report for their own GST reporting? And they wouldn't need the Xero report to invoice the hub? I guess this is not the purpose of these reports? In which case, all is good :)

**Comment by oeoeaio** [comment]
@sstead Yep, that pretty much sums up my understanding. Might just double check with @kirstenalarsen for sanity:

GST on an order sold through OFN should have no relevance for producers, and I don't think producers should have the ability to generate an Xero invoice reports for orders that were created through a separate hub that they happen to sell produce to.

**Comment by kirstenalarsen** [comment]
hmmm, I might need to think about this one a bit . . I think that’s right as in they don’t care whether the hub counted gst or not, all they care about is whether they’re charging gst or not . . but might there be a case where they’re using these reports to work our what they should be charging the hub/s and possibly putting info into their own systems for invoicing . . in which case the reports should generate according to the producer’s gst setup, not the hubs. I suspect that’s too much to deal with right now, so probably we need to just go with what you’ve done
