### ISSUE TITLE
Shoppers and Enterprises must confirm platform Terms of Service

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6316]
## What is the problem we are solving

To achieve basic legal compliance in line with UN Model Law and seemingly many countries domestic legislation, shoppers and enterprises must confirm agreement to the platform Terms of Service for buying and selling on the platform.

Currently within the OFN platform instances can upload their own Terms of Service. A link to these Terms of Service are included in the page footers and within transnational emails. When enterprises register they must confirm they agree to the Terms of Service at that point.

Currently within OFN if an instance updates their Terms of Service there is no way to confirm if enterprises have accepted these new Terms. The default assumption is that they do accept them (and this is often written into the Terms) however this assumption is no longer legally compliant. Similarly at no point do shoppers confirm their acceptance to the Terms of Service. If the Terms of Service change shoppers are not informed or asked to accept.

This epic will create legal compliance around Terms of Service that will minimise the risk of dispute based on the enterprise or shopper not being suitably informed of the changes in Terms of Service.

## Success factors = expected outcome

1. Shoppers will be asked to agree to Platform Terms of Service at checkout. This will have a super admin toggle.
2. After a shopper has agreed to Terms of Service we only ask them to recheck the box if one of hub or platform Terms have changed
[EDIT - Requirement 3 is removed for now]
3. When instances change their ToS the enterprise owner will be asked to agree to Terms of Service when they next log in.

**Comment by RachL** [comment]
This can be closed now 🎉
