### ISSUE TITLE
Enterprise User: should be able to add a new manager without creating a user first

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#632]
should be able to work the same as changing the contact email, e.g. I put the email in and it creates user, sends them an email to set password

**Comment by mkllnk** [comment]
@sstead Isn't this done already?

**Comment by sstead** [comment]
I think Kirsten is suggesting that if I want to add a new manager, I can just type an email in the manager field and that person will be sent a confirmation, once they confirm, they'll be the manager.  

Currently, if I want to add a manager, I need to put their email in the 'contact' field, this triggers them to get a confirmation, and if they confirm they're added as manager. I suppose this is less logical than typing a new manager into the manager field. If I try to type a new, unregistered email into the manager field, I get a dropdown of all registered users, but can't enter a new one.

**Comment by mkllnk** [comment]
Okay, this needs to be considered for #833 then.

**Comment by sstead** [comment]
This is done. You add the new manager as the notification email, this prompts a email conf to go to this person, when they confirm they're made manager.
