### ISSUE TITLE
Release 3.4.0 Bye bye Spree..ng Rolls

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6325]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] Draft: https://github.com/openfoodfoundation/openfoodnetwork/releases
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1883
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by RachL** [comment]
Alright I have found anything that seemed unusual :) 

So long Spree :) https://docs.google.com/document/d/1QIvjWbq3Dj_ikL42yGqWGlEythqjNrC4j96oCFbBFVo/edit#

@luisramos0 I think we have mentioned trying to label this one as beta as long as the roll-out is on?

Let me know if you need anything when communicating on this one. And congrats!!! It's ready to go 🎉

**Comment by filipefurtad0** [comment]
There is an issue here which seems introduced by this branch, which breaks the /users page after deployment - and can't seem to be "rolled-back" - see https://github.com/openfoodfoundation/openfoodnetwork/issues/6348

Adding blocked label, as discussed here:
 https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1604931234131900?thread_ts=1604928184.128300&cid=C02TZ6X00

**Comment by RachL** [comment]
I'm not sure I would block the release for that... It only affects super admin 🤔

**Comment by luisramos0** [comment]
I am keeping this issue open to map the rollout.
We have now deployed this version to FR.
We need to deploy to other instances, probably next week.

**Comment by mkllnk** [comment]
I'm closing because the deploys can now be discussed for the new release:  #6374
