### ISSUE TITLE
Shoppers must agree to Platform Terms of Service at checkout

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6327]
## Description

This issue builds on the work done in #5517 

Currently, if enabled, shoppers are asked to confirm Hub Terms and Conditions on checkout with a checkbox and a link to the document.

![Screenshot from 2020-11-06 07-47-12](https://user-images.githubusercontent.com/8669848/98339875-543a5880-2004-11eb-9492-d7966bd7a47b.png)
_When the box is not selected Checkout is 'greyed out'_
![Screenshot from 2020-11-06 07-47-18](https://user-images.githubusercontent.com/8669848/98339878-569cb280-2004-11eb-8531-dc3570d18c90.png)
_Shoppers can checkout when the box is selected_

### Super Admin configuration

The platform Terms of Service already exist within OFN. Super admin can save a Terms of Service document in [Admin-> Configuration-> General Settings-> Legal Settings](https://openfoodnetwork.org.uk/admin/general_settings/edit)
![Screenshot from 2020-11-06 07-57-04](https://user-images.githubusercontent.com/8669848/98340787-d0816b80-2005-11eb-83a9-1ccf4c30d6e2.png)

We now wish to extend this functionality to include a link to the Platform Terms of Service at checkout. 

This feature will have an instance level toggle. This toggle should appear after the _Enterprises must accept Terms of Service_ checkbox (as per the image above):
- [ ] Enterprises must accept Terms of Service
- [ ] Shoppers must accept Terms of Service

### Checkout Experience

At the point of checkout there are 4 possible variants of the checkout box that need to be supported.

1. When neither Enterprise nor Instance require the shopper to agree:
_No checkbox or text_

2. When the Hub requires the shopper to agree but the Instance does not:
_As now. Terms open in new tab._
- [ ] I agree to the seller's [Terms and Conditions](https://openfoodnetwork.org.uk/files/enterprises/terms_and_conditions/200211/sample_terms_conditions.pdf?1604408307)

3. When the Hub does not require Ts&Cs but the instance does:
_Terms open in new tab._
- [ ] I agree to the platform [Terms of Service](https://openfoodnetwork.org.uk/files/enterprises/terms_and_conditions/200211/sample_terms_conditions.pdf?1604408307)

4. When the Hub and the Instance both require the shopper to agree:
_Terms open in new tab_
- [ ] I agree to the seller's [Terms and Conditions](https://openfoodnetwork.org.uk/files/enterprises/terms_and_conditions/200211/sample_terms_conditions.pdf?1604408307) and the platform [Terms of Service](https://openfoodnetwork.org.uk/files/enterprises/terms_and_conditions/200211/sample_terms_conditions.pdf?1604408307)

## Acceptance Criteria & Tests

1. Instance managers must be able to enable and disable 'Shoppers must accept Terms of Service' checkbox via super admin
2. When enabled shoppers must check the checkbox to be able to checkout. If they do not the checkout button will be disabled.
3. The checkout flow must support the above 4 combinations of Terms of Service and Terms and Conditions requirements

**Comment by mkllnk** [comment]
Related work: #6000, #5912.
