### ISSUE TITLE
Shoppers that have already accepted Terms and Conditions AND Terms of Service can checkout without re-accepting

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6328]
## Description

As a shopper I only need to accept the enterprise Terms and Conditions and the platform Terms of Service on my first checkout or when one or these two documents change. If both documents are the same since last I checked out then I accept them by default. The checkbox will be ticked for me. I have the link to the both of the documents at checkout.

This issue is very similar to #5514 

## Acceptance Criteria & Tests

As a Shopper:

The first time I checkout from a shop I need to accept the Terms and Conditions (Ts&Cs) and the Terms of Service (ToS).
The second time I checkout, if the Ts&Cs and ToS are the same then they are accepted by default. The checkbox is ticked for me.
If the Ts&Cs OR ToS have changed then I must accept them again. The checkbox will be unticked by default and I must check before I will be allowed to checkout.

1. Add Ts&Cs to an Enterprise and ToS to the instance.
2. Login and Checkout from their shopfront. You will have to accept the Ts&Cs and ToS to checkout
3. Create a new basket and checkout from this shopfront. The Ts&Cs and ToS should be accepted by default. This should also be true on a different order cycle for this Enterprise.
4. Now upload new ToS for this Enterprise in SuperAdmin->Configuration->General Settings-> Legal Settings
5. Go back to the Checkout. You will now need to accept the ToS in order to checkout.

**Comment by RachL** [comment]
> The checkbox will be ticked for me. 

So FYI, the lawyer told us this was not legal either. Opt-in should be the constant rule. But I went and check all big ecommerce websites (Amazons & co) and no one ask customer to opt-in again once the opt-in has been made. However they all show a sentence that gives a reminder "Confirming shopping means you have agreed previously to blablabla".

This could be for 2 reasons:

1. They don't want to disturb shoppers with unnecessary clicks
2. They have a good legal department for any issues :)
3. Combination of 1 & 2

Nevertheless I feel this is still the right decision for us and we shouldn't ask for constant opt-in if nothing has changed. our current implementation is good I think. I just wanted to document this bit so everyone knows.

Regarding the issue I have 2 comments @lin-d-hop :

- Are we doing 2 checkbox or 1 checkbox and 2 links?
- If we can only put instance's ts&Cs as an appending doc to hubs ToS, we need to test that the shoppers is asked to opt-in to the instance doc even in the case where the hub has not set up their ToS

Also, in the instance guide we will need to advice instance to add a sentence in their Ts&Cs saying that they are not responsible for e.g. the quality of products sold by hubs. => this is mainly why shoppers do need to opt-in. Basically they need to sign a contract saying they have understood that the platform is not responsible for a set of activities that may impact them.
I will translate the sentence as soon as we have a final version in FR.

(Also by the way we are doing the same work for hubs' terms of sales, so we hope to be able to open source templates soon.)

**Comment by mkllnk** [comment]
For this part we need to know if the platform terms of service changed. That works well by recording a timestamp but we don't have that at the moment. We don't actually store the file within the platform. We just have a link to the terms.

@lin-d-hop @RachL From a product point of view, which of these two options would you prefer?

1. Upload the platform terms within OFN which updates the timestamp automatically. -OR-
2. Keep the link to the terms and have a separate date field that you can change manually so that customers have to agree again.

We also could build some ridiculous automation to download the link periodically and check for differences but I don't think it's worth it. Or we could only update the timestamp when you change the URL but then you have to make sure to always link to a new URL like `https://about.../platform-terms-2022-05-21`. But that also sounds more annoying than option 2 above. Other ideas?

**Comment by lin-d-hop** [comment]
Hi @mkllnk 
Let's go for Option 1 as this brings Platform Ts&Cs into consistency with Enterprise Ts&Cs.
Thanks very much for this work!

**Comment by lin-d-hop** [comment]
This will likely have implications for the roll out.

Do we need to:
a) Notify Instances managers to update their Ts&Cs? or
b) Can we somehow use the existing Ts&Cs where they exist and download/upload ourselves?

If we go for a) does this mean all enterprises will be asked to reconfirm Ts&Cs even though they haven't changed? This would make from an awkward roll out so if there is a clever way to do b) that would be excellent.

**Comment by mkllnk** [comment]
Great. I will add an option for admins to upload a terms of service file which will have a timestamp. I'll keep the old URL in the database as a backup in the transition but remove the admin UI part to update that field. So the only way to change the terms will be uploading a new file.

Customers then have to agree to the new terms only once.

If instances don't upload new platform terms but require customers to agree to them, we will keep the current behaviour of asking to confirm every time.
