### ISSUE TITLE
Duplicate Refunds created by user

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#6330]
## Description

Hub manager for UK enterprise (id 201386) refunds customer by Stripe SCA for missing products.  
Order number is: R281277012
Initial payment was made on 01/11/20 at 10:47 pm
Refund payment was made on 05/11/20 at 7:42 pm

Refund payment was processed twice.  Two payments to the customers credit/debit card of the same amount (£3.92) were recorded by both the OFN platform and Stripe at 7:42 pm on 05/11/20. Note that what is working well here is that all the transactions are recorded in OFN and in Stripe.

Lynne's hypothesis is that this is because the user double-clicks the refund button and the system just goes straight through to process twice.

Duplicate payments should be detected as being in error and not processed by the system.  

## Expected Behavior

User clicks to refund customer £3.92 via Stripe. The fact they have clicked is clear.
Customer is correctly refunded £3.92.

## Actual Behaviour

User clicks to refund customer £3.92 for missing products via Stripe.
Customer is actually refunded twice (ie two payments of £3.92 were made to the customer) with no warning to the enterprise.

## Steps to Reproduce

1. Create an order paid with Stripe then reduce a product quantity
2. Double click the Refund button to refund the difference
3. The refund goes through twice

## Animated Gif/Screenshot

![striperefundtimeline](https://user-images.githubusercontent.com/45104035/98354964-65da2b00-2019-11eb-820b-ac57cc9e4f7e.jpg)
![refundofn](https://user-images.githubusercontent.com/45104035/98354965-6672c180-2019-11eb-8af3-441f8b201c07.jpg)
## Workaround

User will have to request payment from customer which is undesirable and often not possible.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Some kind of 'Are you sure?' confirmation. Currently this is an ugly asset in OFN and at some point I would love us to better design our confirmations.

**Comment by lbwright22** [comment]
This has occurred again in the UK.
Enterprise: Slow Food Birmingham
Order No: R451762852
75p was refunded four times more than needed (ie refund was processed five times rather than once)
Date: 10th Oct 3:18pm

![stripesfbrefund](https://user-images.githubusercontent.com/45104035/99247686-32f51b80-27ff-11eb-8dbd-fe37da090239.jpg)
![sfbrefund](https://user-images.githubusercontent.com/45104035/99247687-338db200-27ff-11eb-8ef9-c1a953e1d9f6.jpg)

**Comment by lbwright22** [comment]
screen shot of this in action (ie evidence that double clicking really does result in double refunds!!)
![doubleclick refund](https://user-images.githubusercontent.com/45104035/104489822-fc057100-55c7-11eb-8d21-dce169200baf.gif)

**Comment by apricot12** [comment]
I've been attempting to find a way to recreate this in my dev environment for a while now, and it just doesnt happen. Proof below : 
![double-click](https://user-images.githubusercontent.com/65319144/121043142-fd7f4200-c7d1-11eb-9637-e3b7fcdd0f5f.gif)

I've tried double clicking and a single click as well.

**Comment by apricot12** [comment]
So I just tried to recreate this in the UK staging server and it is indeed present there : 
![image](https://user-images.githubusercontent.com/65319144/121057210-a92d8f80-c7dc-11eb-81f4-796517d7c639.png)
