### ISSUE TITLE
Change Sendgrid's authentication method

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6331]
## Description

Sendgrid is changing its authentification method on **December 9th!**

After that 2FA will be mandatory. Turning on 2FA breaks all emails :warning:

To fix, see https://sendgrid.com/docs/for-developers/sending-email/authentication/#basic-authentication

## Steps to Reproduce

-> "Click here to activate 2FA now!"
-> Click
-> All emails are broken

## Workaround
For now we can deactivate it but this option ends on December 9th.

## Severity

It's not a bug, but it's a high priority.

## Your Environment

* Version used: v3.3.2
* Browser name and version: All
* Operating System and version (desktop or mobile): All

**Comment by kirstenalarsen** [comment]
Please consider estimate of how hard to fix, who it affects and consideration of any other options? There are other email providers and if it were going to be days or weeks of work to fix then switching should perhaps be an option?

**Comment by Matt-Yorkley** [comment]
Changing providers would be a lot more work. Im not sure any instances affected by this would actually want to switch anyway?

**Comment by RachL** [comment]
@kirstenalarsen In France we started to use Mailjet for our newsletter and they do have a good SMTP service as well, which is probably the only one cheaper than Sendgrid. We've just set it up for the CSA network, however:

- the feature that helps support team to search for emails is less good
- setting up requires API authentication as well, so I'm not sure we would gain anything in switching.

All other email providers I've looked at are more expensive.

Which one are you using in AU?

**Comment by kirstenalarsen** [comment]
I think we still use gmail - is that right @mkllnk ?

**Comment by lin-d-hop** [comment]
In the UK we've just finished a whole bunch of work to get Sendgrid working well.....
For the first time in a long time it feels like UK emails are working well.

I'm not opposed to switching mail servers.... I'll just need to clear my diary for a week :face_with_head_bandage: :joy:

**Comment by Matt-Yorkley** [comment]
Done. It's in code review, we just need to merge and provision :+1:

**Comment by mkllnk** [comment]
> I think we still use gmail - is that right @mkllnk ?

Yes, that's right.

**Comment by RachL** [comment]
@Matt-Yorkley on which repo is the PR?

**Comment by sigmundpetersen** [comment]
I guess it's #6365 and https://github.com/openfoodfoundation/ofn-install/pull/668.
So this can be closed?
