### ISSUE TITLE
Bump paperclip from 3.4.2 to 4.3.7 (or 6.1.0)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6332]
### What we should change and why (this is tech debt)
We can upgrade paperclip to 4.3.7. Some work is needed for that.

### Context
https://github.com/openfoodfoundation/openfoodnetwork/pull/6318 and https://github.com/openfoodfoundation/openfoodnetwork/pull/6446

### Impact and timeline
I am not sure.

**Comment by sigmundpetersen** [comment]
This can be closed now that we have migrated to Active Storage 🚀
