### ISSUE TITLE
Bump money from 5.1.1 to 6.13.8

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6333]
### What we should change and why (this is tech debt)
We can bump money to v6 but we need to adapt some code.

### Context
https://github.com/openfoodfoundation/openfoodnetwork/pull/6320

### Impact and timeline
I am not sure.

**Comment by Matt-Yorkley** [comment]
Background: `Spree::Money` uses the money gem, and specifically calls `Money#parse` in some key places. This method was removed from the money gem in version `6.1.0` without replacement.

**Comment by Matt-Yorkley** [comment]
Done.
