### ISSUE TITLE
Where have the fees gone?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#634]
On staging2, in Bulk Foods Coop.

Order cycle has two fees, one coordinator (NBC  - 5% and one at outgoing Packing Flex). 
![image](https://cloud.githubusercontent.com/assets/2911176/8797308/def871a4-2fdd-11e5-9d80-13e0d14d65e4.png)

I've checked them both and they're set correctly
![image](https://cloud.githubusercontent.com/assets/2911176/8797204/3a6dd502-2fdd-11e5-8483-d36b5f1718d1.png)

But in the shopfront, there are no fees!
![image](https://cloud.githubusercontent.com/assets/2911176/8797171/0460212c-2fdd-11e5-86c1-01ea6ee71eab.png)

But if you go to edit cart, there they are
![image](https://cloud.githubusercontent.com/assets/2911176/8797253/95e6193a-2fdd-11e5-90d6-089e2f4f49b9.png)

@sstead can you check this and see if is user error (am i being a muppet?) or is perhaps connected to https://github.com/openfoodfoundation/openfoodnetwork/issues/615 suggesting a deeper problem?

**Comment by kirstenalarsen** [comment]
but wait, it gets weirder. so now I go back to the shopfront, and the items in my cart are now showing the correct fees, but items that I haven't put in my cart still haven't updated

![image](https://cloud.githubusercontent.com/assets/2911176/8797341/1bb23c56-2fde-11e5-9677-2fe03a44f58f.png)

**Comment by sstead** [comment]
Looks fixed to me! The coordinator fee is automatically incorporated into all product prices in the shopfront, from the get go. Then the packing fee is calculated and added on the next screen in the cart summary page.
