### ISSUE TITLE
Inaccuracies in Order Cycle Supplier totals

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#6344]
## Description

In order cycle reports (supplier totals, supplier totals by distributor and distributor totals by supplier) the 'total cost' figure does not balance for some products (ie total cost is not equal to quantity x unit cost).
This causes problems when hubs use reports to calculate payments to their suppliers.

Example:
hub: In my back yard, 
order cycle: IMBY weekly 2020/45
product: Celeriac from supplier Elbow Farm
![imbyceleraicproduct](https://user-images.githubusercontent.com/45104035/98533204-94a30c00-227a-11eb-8c02-c6852e271e80.jpg)

## Expected Behavior

11 people ordered Celeriac during the order cycle and the cost per unit is £2.00.
Total cost should be £22
No orders have been edited

## Actual Behaviour

Celeriac appears in order cycle supplier totals report with unit cost of £0.00.
Total cost is £20.

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

Order cycles suppliers report
![imby45suppliertotalsreport](https://user-images.githubusercontent.com/45104035/98533471-f06d9500-227a-11eb-8e66-7fd76ceaee98.jpg)
Order cycle customer totals report
![imby45customertotals](https://user-images.githubusercontent.com/45104035/98533498-f9f6fd00-227a-11eb-9c2f-739b07b3e59d.jpg)
Customer's order page
![imby45celeriacinorder](https://user-images.githubusercontent.com/45104035/98533527-011e0b00-227b-11eb-991f-0712219c532b.jpg)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment]
Investigated further by cross referencing supplier totals reports with customer totals reports for October for In My Back Yard.
Findings are consistent with known issues.  Supplier totals reports gives one 'current unit price' but the actual price of a product can vary over the time period of a report.
Hence quantity x current unit price only is equal to the supplier total IF the price of the product does not vary.
Example:
Green peppers from Elbow Farm in October, distributed through In My Back Yard:
3 were sold at 70 p per item
9 were sold at 80 p per item
Supplier's totals report states:
quantity = 12
Current unit price = £0.80
Supplier total = £9.30 (= 3*0.70 + 9*0.8)

**Comment by tschumilas** [comment]
Just seeing this @lbwright22  -  and was about to chime in with the conclusion you've reached.  When a price changes (ie a supplier changes the price of the product) -  the orders will appropriately have different prices for the item .  Orders will reflect the price in the store when the product was ordered.   We want this of course.

Reports take the selling price from the orders, put the unit price from the product list (or inventory override) at the time the report is run.  Can a dev confirm this?  

Implications for support   -  it would be really helpful if we put a little explanation in the instance management guide that describes where various bits of information in reports is coming from   (could a dev work with us on doing that maybe?)

Implications for users  -  if they change a price in an order cycle,  it applies to any future orders.  It does not automatically apply retrospectively to previous order cycle orders,  or to previous orders in the current order cycle.   If a user wants previous orders to reflect a new price (in the current order cycle or in previous order cycles) -  they need to delete and re-add the item (order management) and hit re-calculate. 

Can  any dev please confirm this?

**Comment by lin-d-hop** [comment]
I don't think we need a dev to confirm this. Both of your descriptions cover what is happening.

Closing this issue as everything is working as it should for now (albeit with annoying implications that support teams manage) and the reworking of the way product changes flow through this system is in various stages of inception, design and delivery.
