### ISSUE TITLE
Staging servers: ES, UK, FR - Error 500 on /admin/users (superadmin)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6348]
## Description

Superadmin users can't access /admin/users page - error 500 (snail). This was first observed while studying our API and going for the user keys but of course, prevents using the page and features in general.

Bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fa72d1eb3137f0017c978f2?event_id=5fa72d1e0062e352a0530000&i=sk&m=nw

Update: **Only** verified in staging environments:
- current master/release v3.4.0 

Staged back into the versions below, and the page still appeared broken:
- v3.3.1
- v3.2.11

## Expected Behavior

Superadmin users should be able to access `/admin/users`

## Actual Behaviour

Accessing `/admin/users` -> snail

## Steps to Reproduce

1. Log in as superadmin
2. Navigate to "Users", on main menu
3. You should see error 500 on page `/admin/users`

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/690c5f3f-3956-4f47-8142-bdf3e6cda81e)

## Workaround

Hum... depends on the actions, API keys can still be retrieved from the html source code, but other features...

## Severity

Not sure how critical this is, proposing
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: in staging environments, observed from v3.4.0 till v.3.2.11
* Browser name and version: Firefox 82
* Operating System and version (desktop or mobile): Desktop, Ubuntu 20.04

**Comment by RachL** [comment]
@filipefurtad0 I don't have the issue in production. Maybe a data problem in staging?

**Comment by filipefurtad0** [comment]
Thanks @RachL, yes that should be it - I'll try to figure out what's happening.

**Comment by Matt-Yorkley** [comment]
I can see this in Staging, and the error is:
```
I, [2020-11-09 13:28:07#12883]  INFO -- : Processing by Spree::Admin::UsersController#index as HTML
I, [2020-11-09 13:28:07#12883]  INFO -- :   Rendered spree/admin/users/index.html.haml within spree/layouts/admin (28.4ms)
I, [2020-11-09 13:28:07#12883]  INFO -- : Completed 500 Internal Server Error in 94ms
I, [2020-11-09 13:28:08#12883]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of ActionController::UrlGenerationError
F, [2020-11-09 13:28:08#12883] FATAL -- : 
ActionView::Template::Error (No route matches {:action=>"index", :controller=>"spree/admin/users", :page=>nil}):
    11:     <%= first_page_tag unless current_page.first? %>
    12:     <%= prev_page_tag unless current_page.first? %>
    13:     <% each_page do |page| -%>
    14:       <% if page.left_outer? || page.right_outer? || page.inside_window? -%>
    15:         <%= page_tag page %>
    16:       <% elsif !page.was_truncated? -%>
    17:         <%= gap_tag %>
  app/views/spree/admin/users/index.html.haml:29:in `_app_views_spree_admin_users_index_html_haml__3321076735980750937_47022401092460'
  lib/spree/responder.rb:24:in `to_html'
  lib/spree/core/controller_helpers/respond_with.rb:30:in `respond_with'
  app/controllers/spree/admin/users_controller.rb:14:in `index'
```
Line 29 referenced in the stacktrace is calling `#paginate` (Kaminari)...

**Comment by Matt-Yorkley** [comment]
So Kaminari is trying to do `paginate @users` in the admin/users view and encounters some kind of fatal error. It's not clear what's happening under the hood. The error indicates that a route can't be built (presumably whilst Kaminari is generating links for the different pages of users): `No route matches {:action=>"index", :controller=>"spree/admin/users", :page=>nil}`, but it could be that something is wrong with the user objects in `@users`.

**Comment by Matt-Yorkley** [comment]
This is reproducible in dev with `master`.

**Comment by Matt-Yorkley** [comment]
I manually staged the last release (`v3.3.1`) and the error is not there.

**Comment by Matt-Yorkley** [comment]
I rummaged around in the `spree_core` and `kaminari` gems looking to find some way that Spree might have been adding some Kaminari hacks (that we have now removed), but I couldn't find a single relevant bit of code. No decorators, custom Kaminari configuration, patches, related route changes or inclusions...

**Comment by Matt-Yorkley** [comment]
The error `No route matches {:action=>"index", :controller=>"spree/admin/users", :page=>nil}` is pretty strange, given that this is actually being called from the `index` action in the `spree/admin/users` controller in the first place (albeit in the view).
