### ISSUE TITLE
Switching between Weight and Item unit measures creates corrupt products

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6368]
## Description

When a user edits a product switching between weight and item unit measures, the change does not correctly save.
This results in corrupted products that cause cloning order cycles to fail. This has been seen intermittently but repeatedly in [#4216](https://github.com/openfoodfoundation/openfoodnetwork/issues/4216)

## Expected Behavior

Users should be able to update their products from items to weights units and back again and not suffer issues across the system due to corrupt product data.

## Actual Behaviour

If a user updates products from items to weights and/or vice versa order cycles containing that product cannot be cloned. The product becomes corrupted.

This is a screen shot of a DB query. All of these products should have been stored as items. Some (though I'm not sure exactly which) were shifted between items and weights.
![Screenshot from 2020-11-10 19-23-12.png](https://images.zenhubusercontent.com/5819aa67e40e5714b16f85fb/2e80db8a-8843-47e8-8931-54696a2eee0b)

## Steps to Reproduce

1. Create a product as 'items' unit type
2. Edit to save as 'weight'
3. Switch back to 'item'
4. Now try to clone an OC with this product in. CAT IN YOUR FACE!

## Workaround

I managed to fix this through the UI after I identified the products though it took a few attempts. I changed all products to Items on by one.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
This has created multiple S1s and it's still doing it, so might be worth taking a look at it...

**Comment by lin-d-hop** [comment]
Multiple, rare S1s that we can fix pretty easily because we can track down the cause.
But yes, we should fix this :-)

**Comment by RachL** [comment]
Could be linked with: https://github.com/openfoodfoundation/openfoodnetwork/issues/5234
