### ISSUE TITLE
Tests not passing in the Docker setup

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6370]
I have yet to get all the tests to pass in the Docker setup.  More details are in Issue #6228 .

**Comment by jhsu802701** [comment]
My first step is to set up this app in a virtual machine with a full GUI interface.  It's not as efficient as Docker, but it appears that all or most team members are relying on a Rails installation on their host systems.  Using a virtual machine puts me on the same page but won't affect my host system.  (I don't rely on a Rails installation on the host system.  Not being able to reset things willy-nilly is a deal-breaker.)

I'm using Vagrant to provision a VirtualBox virtual machine.  Then I save a snapshot then boot up the virtual machine without Vagrant.

**Comment by jhsu802701** [comment]
Ruby 2.3.7 relies on the libssl1.0-dev package, which is not available from Debian Buster.  This package requires Debian Stretch.

**Comment by jhsu802701** [comment]
I increased the Capybara.default_max_wait_time from 30 to 300 to avoid the timeout error.  I'm getting errors like the following:
```bash
     RuntimeError:
       Failed to execute:
       ["/bundles/bin/wkhtmltopdf", "--encoding", "UTF-8", "file:////tmp/wicked_pdf20201115-1-s6bv59.html", "/tmp/wicked_pdf_generated_file20201115-1-10zinb8.pdf"]
       Error: PDF could not be generated!
        Command Error: /bundles/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf:40:in `<top (required)>': Invalid platform, must be running on Ubuntu 14.04/16.04/18.04 CentOS 6/7, Debian 8/9, or intel-based macOS (missing binary: /bundles/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf_ubuntu_20.04_amd64). (RuntimeError)
       	from /bundles/bin/wkhtmltopdf:22:in `load'
       	from /bundles/bin/wkhtmltopdf:22:in `<main>'
```

**Comment by RachL** [comment]
I'm closing this issue since we've had a lot of upgrades. We can reopen new ones based on the latest issues.
