### ISSUE TITLE
Norway instance email config not working: enterprise conf emails not received

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#638]
Copying email from @myriamboure into github so @RohanM and I can tackle from two directions at same time:

It seems we have a problem with the sign up on the Norwegian instance (maybe a problem with the v1 installation? Or from before?

We have tested different things, and here is what happens:

- As an admin, I have created a new user "olivier.krener@gmail.com" (my boyfriend!), and I created an entreprise for him (Olivier test, with him as an owner). He never received any email, he checked in the spam also. Anyway, if he logs in with the password I put when I added him as a user, he can see the admin interface, and it seems he can manage his hub, but it is still written that he needs to confirm his email address...

![image](https://cloud.githubusercontent.com/assets/2911176/8976098/5abb9c82-36cb-11e5-9bbd-8276436a1096.png)

- We tried something else, with another account. I asked him to sign up directly from the platform. He did it with his email olivier.krener@capgemini.com, and when doing it, there is a green banner saying "you have successfully signed up" but the only thing he sees at that stage is "account". But he didn't receive either any email.

![image](https://cloud.githubusercontent.com/assets/2911176/8976103/647f7b26-36cb-11e5-8336-b35421c0d453.png)

And as an admin, I received no notification that he has signed up, so I have no idea that he has signed up and experimenting any difficulty.  
If I connect as an admin I see his account, but he has no rights

![image](https://cloud.githubusercontent.com/assets/2911176/8976112/713cdf8e-36cb-11e5-9944-78ce4b328ca8.png)

Normally, if I understand the new sign up process that were described here, he is supposed to receive some email that direct him to the right set up pages for his account, so that he can say if he wants to set up a hub, etc.

But it seems it's not working on the norwegian instance. What can we do? Is there something that has not been installed properly for our instance? Or does it come from somewhere else?

Kirsten, if you remember well, we had already problems when it was installed by Raf the first time, we received emails but the link in there was not working... (you helped us solving that but we just had to change the url when it was opening...) so it seems to be another problem.

Is it something easy to fix? I'm sorry to report that bug just before you are leaving for holidays, Cynthia just realized that yesterday when testing the hub she is building to pilote the platform here.

**Comment by kirstenalarsen** [comment]
@myriamboure - problem you have described sounds like it's to do with the email configuration. I've just put through an order and haven't received an email - do you agree that it is all (or no!) emails on the system, not just the enterprise address confirmation that is not working?

This is a different problem from the previous one. Two things we need to look into

1. @RohanM - could you check that delayed job is set-up correctly and doing whatever it should be doing? Or anything else at system level that might be interfering with emails?

2. @myriamboure - if Rohan tells us that 'delayed job' is ok, then we need to check some other stuff. But don't do steps below until you have confirmation from Rohan that the first thing is not the problem (don't want to waste time fixing anything that ain't broke :)

I have had a quick look and your mail method is configured as Raf set it up, and really nothing should have changed (see image below). 

![image](https://cloud.githubusercontent.com/assets/2911176/8976227/4ce7f798-36cd-11e5-963d-a66358e2f7db.png)

Did Raf send you account details for your mandrill account? If yes, perhaps try entering the password again . . . 

If you don't have it (in which case none of us have it), then I reckon you should reset your system email to one that you have control over. This would be a good idea anyway as people do sometimes respond to this email, and it's not a bad idea to be able to read those emails?

in case we get to this and you want to act on it while I'm away, then here is quick screen grab of our mail set-up on the aus server, pretty easy to emulate :)

![image](https://cloud.githubusercontent.com/assets/2911176/8976209/1fb86866-36cd-11e5-8375-392a52af1f44.png)

**Comment by kirstenalarsen** [comment]
NB. @myriamboure this is in aus milestone just so easy for rohan to keep track of it, as hoping to knock it off this week

**Comment by myriamboure** [comment]
Thank you @kirstenalarsen and @RohanM to help us with that ! I confirm it is all emails, I also just tried to make an order and didn't receive any email confirmation.
So I wait for @RohanM to confirm that everything is fine on his side and then I'll do what you said (I don't have the Mandrill account password, so I'll "copy" what you did for Australia).
I wondered if the "no-reply@openfoodnetwork.no" as sending address was ok, a we don't have settled this address with our domain provider, so I tried to change with "postmaster@openfoodnetwork.no" which is an address we have, and it didn't change anything, no more emails. So I put back no-reply@openfoodnetwork.no... I guess this is only "text" sent as sender...

**Comment by RohanM** [comment]
Hi @myriamboure. I had a look and Delayed Job was not properly configured nor running on the Norway server. I've set it up now, and all of the emails should have gone out now, and it should all be working. So as long as you're receiving emails now, no need to make any changes to the mail settings.

**Comment by myriamboure** [comment]
Thank you @RohanM ! I received a bunch of emails this morning :-) 
But there is one thing that still seems not working properly.
When I went on openfoodnetwork.no, as if I was discovering it, and I signed up because I wanted to create a hub or put my profile online as a producer, I receive this email:
![signup_mail](https://cloud.githubusercontent.com/assets/8135376/9002404/1034c32a-3764-11e5-8c83-eaadacfd4109.jpg)

And when I log in I still only see the "account option", I am not asked if I'm a producer and/or want to set up a hub, choose package, etc. We still receive the "old" email and not the process described here (http://community.openfoodnetwork.org/t/updated-text-and-links-in-registration-wizard-and-emails/206) which I found great :-) I see that it appears as "done" in the community page, but do we need any update for it to be operational?

**Comment by kirstenalarsen** [comment]
seems like you have signed-up but not actually gone into the enterprise registration, so you won't have actually triggered any of the other process. try going to /register (from front) when logged in as this user and you should be away? If is ok, can you close this issue please :)

**Comment by myriamboure** [comment]
Ok, yes... so I think there is something to improve in the UX here, as I have no idea that I have to scroll until the end of the hub list to see the button to register a hub. It should be in the login button for example, you could choose "sign up as a buyer" or "sign up as a hub"... 
Anyway, that is not a technical problem, so I'll close the issue and put that in the community forum :-) Thanks!
