### ISSUE TITLE
Google Chrome installation process for Ubuntu 

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6380]
### What we should change and why (this is tech debt)

In the wiki, one of the steps for installing Google Chrome in Ubuntu consists of:
```bash
sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
```
This command results in a permission denied error.  I was able to complete this manually, but I recall that there's a way to do this programatically with the tee command.

**Comment by sigmundpetersen** [comment]
Installing Chrome is removed from this wiki entry https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-Ubuntu

Closing
