### ISSUE TITLE
Cannot create new Enterprises

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#639]
On UK Staging, v1.0 code, when logged in with admin account. Just see the User Guide button in top right.

@kirstenalarsen could this be related to the point that the Enterprise UI generally doesnt seem to be updated?

**Comment by pmackay** [comment]
@RohanM are there any permissions changes related to the Admin account that might cause this one?

**Comment by kirstenalarsen** [comment]
i think it probably is updated - try logging in not as admin. We left the
old one there for admin as there are a couple of things difficult to do in
the new one (yet) like quickly make a whole lot of enterprises visible /
invisible :)

**Comment by kirstenalarsen** [comment]
@sstead has created an issue #646 for the missing new enterprise button, I can't replicate this so will look at it with her on Friday

**Comment by kirstenalarsen** [comment]
just need to make sure super-admin user has permission to create >1 (preferably very high number) of enterprises. See also https://github.com/openfoodfoundation/openfoodnetwork/issues/646. Closing this and you can open issue / task to make that default for super-admin if you want
