### ISSUE TITLE
Switch cancan to cancancan

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6403]
### What we should change and why (this is tech debt)

The `cancan` gem was abandoned a long time ago (~8 years?). We are at the highest version (1.6.10). It was also forked a long time ago and maintained separately in a new gem called `cancancan`. Version `1.6.10` of the `cancancan` gem is exactly the same, so we can jump to it now. This will mean that dependabot can start trying to bump it to newer versions.

### Context

Spree tidy up / upgrades, etc.

### Impact and timeline

.

**Comment by andrewpbrett** [comment]
Because we cancancan?

**Comment by arku** [comment]
> Version 1.6.10 of the cancancan gem is exactly the same, so we can jump to it now.

@Matt-Yorkley Do you mean [1.6.0](https://rubygems.org/gems/cancancan/versions/1.16.0)?

**Comment by Matt-Yorkley** [comment]
I think our version of cancan is 1.6.10 and there's a related branch in the  cancancan repo, but it looks like the first release is 1.7.0. We can try that.
