### ISSUE TITLE
No record of customer changing order

### ISSUE THREAD

**Issue by Renatacumming** [openfoodfoundation/openfoodnetwork#6404]
## Description
The customer has contacted the enterprise (enterprise number- 1585) because they have a credit owing on 3 orders in August and are asking for a refund. They have provided a screenshot showing the amount owed. 
There are three orders showing a credit in the enterprise order list but no record of what the credit is for or no record of any adjustments being made. 

The customer account matches the enterprise order list in the amount owed but the enterprise doesn't know what the refund is for. The enterprise believes the customer adjusted the order after paying via Stripe but there is no record of this in the order details. 

The enterprise as since changed their settings so that customers can no longer adjust orders after placing the order. 

## Expected Behaviour 
The enterprise should be able to see any adjustment made so as to manage orders and refund correctly

## Actual Behaviour
Screenshot from customer of account
![image](https://user-images.githubusercontent.com/74280572/99923683-f12e1d00-2d8a-11eb-89d1-9eb92327696f.png)

Screenshot of orders in enterprise order list
![99923721-1fabf800-2d8b-11eb-8574-95a31b259fe2](https://user-images.githubusercontent.com/35588/100266408-a0433380-2f06-11eb-8d67-ed5ebd1699d3.png)

Screenshot of order with larger credit owing
![image](https://user-images.githubusercontent.com/74280572/99923982-7403a780-2d8c-11eb-9260-aff4b798b0e2.png)

## Steps to Reproduce
Unsure how to reproduce
Possibly- open order cycle, place order and pay using Stripe, log back in and change order

1.
2.
3.
4.

## Workaround
Enterprise can provide a refund directly but has to trust the system without verifying why the credit is owed. 

## Severity
s2 ? 

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
There's an upcoming feature related to order history, but it's currently in the inception phase and not in dev-ready yet.

**Comment by andrewpbrett** [comment]
@Renatacumming I replaced the image in the issue description with one that blacks out the email and name of the customer 👍. 

Agree with @Matt-Yorkley - this does look like a bad bug, but will need some thought around a solution.

**Comment by chezaorchard** [comment]
Hi team, just checking where this is up to - do we need to provide anything further from the customer support side?

**Comment by Renatacumming** [comment]
Hi Team, just following Chez's comment above, wondering where this is at and if you need anything else from us to progress?

**Comment by andrewpbrett** [comment]
Sorry I missed your first comment @chezaorchard. I don't think there's anything else needed from the customer support side. The upcoming feature Matt is referring to is (I believe) [this one](https://app.zenhub.com/workspaces/product--inception-pipe-5f82e534db531f000f8c09ff/issues/openfoodfoundation/inception-pipe/11). If it's happened again since the original issue we could think about ways to patch something together quickly, but apart from that I think it's just waiting to get picked up and a solution designed.

**Comment by RachL** [comment]
I'm closing this bug report as we are not going to solve it as is. We will first develop a feature that allow us to get history of changes. Once we have this and we keep having changes that we cannot explain we will need to open a new bug report.
