### ISSUE TITLE
SemaphoreCI: Upgrade the Ubuntu version in use

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6406]
### What we should change and why (this is tech debt)
* The output of the command "cat /etc/os-release" in the SemaphoreCI build environment is:
```bash
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
* In other words, the current SemaphoreCI build environment uses an outdated version of Ubuntu whose support ended on April 30, 2019.  This version of Ubuntu is over six years and three LTS releases ago.
* The tests aren't passing in the current Docker setup (which uses Ubuntu 20.04).  I tried to move to Ubuntu 14.04, but some of the packages specified in the Dockerfile don't get installed because they weren't available in 14.04.  Successfully upgrading the Ubuntu version used in the SemaphoreCI environment would make it easier to fix the Docker setup.

**Comment by Matt-Yorkley** [comment]
Closing; we don't use Semaphore for CI now, and we don't use Ubuntu 14 in the build :+1:
