### ISSUE TITLE
[Rails 4.2] broken reports - server error 500

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6413]
## Description

Rendering the reports below generates an error 500. The reports only render, if a time range is chosen, from which no orders occurred, displaying an empty table.

- Orders and Fulfillments
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fbe868557217b001782dfda?event_id=5fbe86850064f3ff16330000&i=sk&m=nw

- Payments
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fbe850229bebe001a74dde6?event_id=5fbe85020064f58305ea0000&i=sk&m=nw

Maybe related to #6411?

## Expected Behavior

The reports should render correctly, with entries corresponding to orders/customers, etc.

## Actual Behaviour

These reports generate Error 500.
It only works as expected if there are no orders, on the chosen time frame (this can be tested by choosing future time range)

## Steps to Reproduce

1. As admin or superadmin, visit https://staging.openfoodnetwork.org.uk/admin/reports/orders_and_fulfillment
2. Click "Search"

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/100259060-af92a300-2f3f-11eb-8745-bbdefe2587af.png)

## Workaround

None.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: Rails 4.2
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by andrewpbrett** [comment]
I think this should be fixed as of b04a76e8bf4d9ac5339c4ff619cf669f89c44094, which is deployed to UK staging.

**Comment by filipefurtad0** [comment]
Yup,

I checked these reports, and they are fixed as well now - closing this issue :+1:
