### ISSUE TITLE
Shop link should close modal

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6415]
## Description
The link to a shop in the modal for a producer does not close the modal window. 

## Expected Behavior
Clicking the Shop for [Producer]'s products" link should take you to the place where you can shop for them. 

## Actual Behaviour
The modal does not close.

## Steps to Reproduce

1. Visit https://openfoodnetwork.net/brattleboro-winter-farmers-market/shop#/producers
2. Click on one of the producers
3. Click on the "Shop for X's products at" link
<img width="1010" alt="Screen Shot 2020-11-25 at 12 54 59 PM" src="https://user-images.githubusercontent.com/35588/100280679-6fbac400-2f1d-11eb-8bca-d314ecb9cbc8.png">
4. Nothing (apparently) happens

## Workaround
Go to the shop directly 

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
Safari, macOS Catalina

**Comment by RachL** [comment]
outch nice catch @andrewpbrett ! As it is shopfront facing I think everyone would have agreed to a higher severity. Anyway I see you already fixed it :D 

![ ](https://media.giphy.com/media/lRnUWhmllPI9a/giphy.gif)

**Comment by andrewpbrett** [comment]
It was actually @lauriewayne who noticed this :)

**Comment by lauriewayne** [comment]
That's our Andy!!!

**Comment by lauriewayne** [comment]
@andrewpbrett ideally it would close the modal **and** go to the "shop" tab. It currently goes to the "home" tab (underneath the modal).

**Comment by andrewpbrett** [comment]
@lauriewayne just updated to do just that 👍
