### ISSUE TITLE
Snail when creating enterprise fees, if Tax Category field is left blank

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6416]
## Description

The user sees the snail if attempts to create an enterprise fee, but leaves Tax Category field blank.

Bugsnag
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fbf9367d4efc80018dca481?event_id=5fbf936700658d8755bb0000&i=sk&m=nw

I thought this bug could be related to these settings, but it seems to occur independently of what is chosen here:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/b8b4bed0-8294-422f-96ef-b703515e4dfc)

And here (superadmin):

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e1280c0d-a72a-468e-8ff0-731f77724cc1)

## Expected Behavior

Currently (in master/production) it's possible to leave this info out, and still create the Fee.

## Actual Behaviour

It's not possible to create a fee leaving Tax Category blank.

## Steps to Reproduce

As admin
1. Go to https://staging.openfoodnetwork.org.uk/admin/enterprise_fees
2. Fill in Enterprise,	Fee Type, Name and Calculator 
3. Click Update
4. Boom.

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/f01fc3d4-90b1-4fe0-a172-5e29661845cf)

## Workaround

Select Tax Category from the dropdown, and try again.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: rails 4.2
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by Matt-Yorkley** [comment]
I didn't even realise this was possible to begin with. I think in UK we have a "no tax" tax category, but you still have to select one.

**Comment by lin-d-hop** [comment]
We need an error message rather than a slug :pray:

**Comment by Matt-Yorkley** [comment]
Note: the Bugnsag error is ` NameError - wrong constant name `...

**Comment by Matt-Yorkley** [comment]
I can't replicate this locally... I can always create the fee without error, regardless of other settings (I tried switching them all around). The error in Bugsnag looks a bit odd, I think this might be a data inconsistency issue related to a bug we've seen recently in master. I'll have to investigate a bit more....

**Comment by Matt-Yorkley** [comment]
Hmmm... I just created 6 enterprise fees in a row on UK Staging as well without setting the tax category field.

I did rebase the branch the other day, maybe it was fixed at that point?

**Comment by filipefurtad0** [comment]
Oh, you're right... This was easily reproduced before but it's gone now.
Thanks for checking Matt.

I think we can close this issue here.

**Not related** to the rails upgrade:
I think there is some inconsistency in the way the banner is displayed. For example, creating a fee but leaving empty mandatory fields like Enterprise or Name and clicking Update displays this banner (below) but no fee is created:

![image](https://user-images.githubusercontent.com/49817236/100641658-ab93c600-332f-11eb-9c76-dcd2f8c48e54.png)

This is a separate issue.
