### ISSUE TITLE
[Rails 4.2] Missing translations

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6419]
## Description

Found a couple of missing translations:

**1) Dashboard**

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/1c457075-8beb-4bd4-aff6-96cb6dbf0982)

**2) Tag Settings**

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/4caf65b4-6735-4dad-8c46-d9be6dba3de3)
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/6df247e5-b6e4-4990-924d-c066d78ccdd9)

**3) Customers -> Creating a new customer**

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/f2df4f9e-8ebc-436d-ac6e-05c9e959ef00)

**Comment by Matt-Yorkley** [comment]
Are these translations working in master now..?

**Comment by Matt-Yorkley** [comment]
Okay, I just rebased both the 4.1 and 4.2 branches, and it looks like this is fixed now. If you re-stage it, the trasnaltions should eb there.

**Comment by filipefurtad0** [comment]
Checked again after rebasing:

**1) Dashboard** - all good now

![image](https://user-images.githubusercontent.com/49817236/100462710-91a17b80-30c2-11eb-9fd7-46999f5b8c4b.png)

**2) Tag Settings** - those marked in red are pre-existing: In case there is none yet, I'll open an issue on this :+1: 

![image](https://user-images.githubusercontent.com/49817236/100462970-02e12e80-30c3-11eb-87fb-c8c084f18c29.png)

**3) Customers -> Creating a new customer**

![image](https://user-images.githubusercontent.com/49817236/100463062-2ad09200-30c3-11eb-9786-f0ca2aef7ac5.png)
