### ISSUE TITLE
Buildkite can be used for UK deployments

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#642]
* [ ] Edit CI scripts to handle pushing to different staging servers
* [ ] Test test -> deploy sequence on OFN UK Buildkite project
* [ ] Update ofn_deployment to setup post receive hook for git push to deploy.

**Comment by kirstenalarsen** [comment]
@RohanM and @mkllnk to do when rohan back on the 8th Oct
