### ISSUE TITLE
Try out RuboCop Autofixer

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6420]
### What we should change and why (this is tech debt)

Add https://github.com/marketplace/rubocop-auto-fixer to the repo. It will periodically make small PRs that fix minor Rubocop issues.

### Context

Manually applying Rubocop autocorrect...

### Impact and timeline

.

**Comment by luisramos0** [comment]
What exactly needs to be done here? It appears the app is already installed in our repo...

**Comment by mkllnk** [comment]
We had that Autofixer app installed for three years but it didn't do anything. The linked homepage can't be reached. I'm assuming that this app is dead. I removed it and I will close this issue.
