### ISSUE TITLE
v3.4.3 Codonyat

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#6429]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1927
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by RachL** [comment]
I think this is ready to go! https://docs.google.com/document/d/12zPCvOSK6aubV0EUJmGzsw_Wh9o7sZ9wwRvXX_WbZZ0/edit
