### ISSUE TITLE
On UK production - cannot add new product images

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#643]
Since the production and staging databases were merged some of the product images on the Stroudco shopfront display as a wierd image - see screenshot.  Other product images display correctly.  @aidandunsdon thought this might be to do with the way the images are referenced form the database.
![screenshot 2015-07-30 19 22 53](https://cloud.githubusercontent.com/assets/10517702/9034353/d3ce2eac-39c6-11e5-8b60-63be6b97bfd1.png)

**Comment by pmackay** [comment]
@NickWeir63 how much of an issue would it be for you to update the broken images on production once we copy the db there?

**Comment by NickWeir63** [comment]
Yes I can do this.  @aidandunsdon asked me to raise it as an issue because he thought he might be able to do an easy fix on it.  His holiday has been delayed by a week.  If he doesn't get to it before he goes away, then yes definitely I will reload the images onto production.

**Comment by pmackay** [comment]
If @aidandunston can do a quick fix that's great. In which case should I
wait to move the database from staging to production?

**Comment by NickWeir63** [comment]
i have just spoken to Aidan and he can't do a fix until later this week and he is not convinced that it is a database issue.  I have just checked that I can delete the weird images and upload the correct one and that all works, so @pmackay  please go ahead and move the database to production when you are ready and I will do the photo jib on production.  thanks

**Comment by pmackay** [comment]
@NickWeir63 production is now updated with staging db. However could you give a bit more detail about what you want to do on there now? There are some other changes I should do for images (related to where they get stored) that would be good to do first. However I may not be able to do that for about another week, as I'm away for part of this week and the weekend.

**Comment by NickWeir63** [comment]
Thanks @pmackay that is great.  I am happy to leave the photo job until later.  I want to activate all the Stroudco products into an order cycle, do the data massaging (adding in product quantities eg. 1kg, 75cl, etc) and getting shoppers to put in parallel orders whenever they put an order into the old Storudco software.  Is this OK? 

I also plan to tell Karen at Roots Fruits and Leaves that she can start using production again.  Is this OK?

thanks again - fantastic to have production up and running!

**Comment by pmackay** [comment]
There are a few other things that would be desirable to sort out ideally, if that's ok. @NickWeir63

**Comment by NickWeir63** [comment]
happy to help @pmackay - what 'other things' do you need me to sort out?

I notice that there are some random images appearing against some Stroudco products on production.  Is this something you are experimenting with?

**Comment by pmackay** [comment]
@NickWeir63 I've updated production with the settings to use Amazon for image storage. Would it make sense for you to setup a smaller set of products so we can see a list? And then could test adding an image to a product. With that settings change no images will be shown until new ones are added.

**Comment by NickWeir63** [comment]
Thanks @pmackay - I reduced the number of products to c450, reopened the order cycle and the shop loaded within 2 minutes (I will now do some testing to add back in products and see if we hit a limit at which the loading time goes through the roof).  The shop was already showing some photos but I did add a photo to a product that did not have one.  The new image showed up fine in the shop.  Can we now go ahead and load photos against all products on Produciton?
Thanks 
Nick

**Comment by pmackay** [comment]
It should be ok to load more images for production products.

**Comment by NickWeir63** [comment]
I just tried to add a photo to production - got as far as this screen but when I clicked update I got the grumpy cat
![screenshot 2015-09-13 16 10 33](https://cloud.githubusercontent.com/assets/10517702/9837299/5a726050-5a32-11e5-8d22-2c5e6f9e2736.png)

**Comment by NickWeir63** [comment]
The problem with loading images (above) does not happen on UK staging - I can load product photos fine on UK staging

**Comment by NickWeir63** [comment]
The same problem happens on UK production when I log in as admin on the Roots Fruits and Leaves shopfront - i get the grumpy cat when I try to upload an image

**Comment by mkllnk** [comment]
Hi! 

I just looked into the failure of uploading images. The problem was an inconsistent database. I guess, that happened when the two databases got merged. I don't know how that was done.

Anyway, I could fix the production database for this case and it should be possible to upload product images again. There might be more of these inconsistencies in the database.

Going back to the initial problem: missing images on the server. It looks like the images from the staging server were not transferred to the production server. So these are all missing and therefore look funny. I could transfer all images from staging to production, but I'm not sure if that is a good idea. It could happen that some if not all products will have wrong images associated. And it is likely that it causes orphan images on the production server.

So it would probably be better to upload the images again. Is that okay with you?

**Comment by pmackay** [comment]
I think it was agreed that it would be easier just to add images again than to try to transfer from staging.

**Comment by NickWeir63** [comment]
Yes we can start again with the images and upload them all to production.  However I am concerned about the inconsistencies in the database that @mkllnk has spotted and wonder if @aidandunsdon ca suggest what might have caused these.and what , if any ,other problems we might have in future as a result.....
Thanks all

**Comment by NickWeir63** [comment]
Yes I can upload images now - thanks @mkllnk  I will leave this issue open while I check with @aidandunsdon about database inconsistencies

**Comment by NickWeir63** [comment]
@mkllnk Could it be that these database inconsistencies are causing the slow loading speed (it takes about 2 minutes to load the shopfront products on UK production and this is with only about one third of the Stroudco products loaded into an order cycle - it is even slower when I load all 1000+ products).  Before we do much more work on the database, would it be worth testing the database by loading it into another server (staging2 ??) and seeing if the loading speed is as slow there?  Would this help us identify whether the problem is caused by the database or the server/deployment issues?
Thanks

**Comment by mkllnk** [comment]
I don't think so. I think that the code is not efficient enough to handle shops with hundreds or thousands of products. We have much smaller shops in Melbourne and still, the shopfront takes the most computation time. It is an issue we are aware of.

**Comment by pmackay** [comment]
Is there any plan to introduce paging? All products on one page is inherently not scalable.

**Comment by mkllnk** [comment]
Yes, it's on Rohan's plate at the moment, scheduled for this sprint.

**Comment by NickWeir63** [comment]
OK thanks I will close this now
