### ISSUE TITLE
GST not applying in production

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#645]
This producer is set to charge GST...
![image](https://cloud.githubusercontent.com/assets/10843056/9077040/ec4b5958-3b6c-11e5-8f05-9f9d45ec46ab.png)

And the product 'Lemons' is also set to include GST...
![image](https://cloud.githubusercontent.com/assets/10843056/9077063/28c827d0-3b6d-11e5-831a-08ab34edccec.png)

But in the shop and checkout there's no mention of GST
![image](https://cloud.githubusercontent.com/assets/10843056/9077065/3334e17c-3b6d-11e5-8f6f-8e88e62c0c26.png)
![image](https://cloud.githubusercontent.com/assets/10843056/9077066/34e6c210-3b6d-11e5-84f4-d147856f4543.png)

And the sales tax report isn't showing any GST charged either...
![image](https://cloud.githubusercontent.com/assets/10843056/9077105/9d8d1e18-3b6d-11e5-8bb6-a53ea9b3e796.png)

**Comment by RohanM** [comment]
I went into Demo Hub and "Charges GST?" was set to No. I set it to Yes and the tax appeared correctly.

**Comment by sstead** [comment]
face palm
