### ISSUE TITLE
Updating & recalculating Fees works but displays red banner (despite no error)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6459]
## Description

When editing an order, clicking Update & Recalculate fees displays a red banner on top of the screen - but without an error message. Nothing unusual is spotted on the console... So this seems harmless, but misleading to the user.

## Expected Behavior

No error -> no red banner.

## Actual Behaviour

A red banner is displayed when updating and recalculating fees.

## Steps to Reproduce

1. Log in as admin and go to /orders
2. Edit an order
3. Change the amount of a given line item
4. Click Update & Recalculate Fees

## Animated Gif/Screenshot

![red_banner](https://user-images.githubusercontent.com/49817236/101205803-144bad00-3666-11eb-9044-3c0e30df109d.gif)

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.4.4
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by RachL** [comment]
@lin-d-hop what do you think about this one. It's less worse than https://github.com/openfoodfoundation/openfoodnetwork/issues/6205 but I would a least raised it as s3.

**Comment by filipefurtad0** [comment]
Closed via #7450 :tada:
