### ISSUE TITLE
Missing '+ New Enterprise' button

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#646]
I'm logged in as a Super-Admin on Staging2 and can't see the +New Enterprise button.

![image](https://cloud.githubusercontent.com/assets/10843056/9128554/bd3640fe-3d0d-11e5-9906-645594c355c8.png)

**Comment by sstead** [comment]
As a non-super admin, with >1 Enterprise limit.... I can see the button. 

![image](https://cloud.githubusercontent.com/assets/10843056/9128575/395511b0-3d0e-11e5-9beb-0ce623440078.png)

**Comment by kirstenalarsen** [comment]
I have it (see below) so perhaps lets have a look friday when you're here @sstead 

![image](https://cloud.githubusercontent.com/assets/2911176/9347424/977a0c52-466c-11e5-8587-c016e01cb8fa.png)

**Comment by sstead** [comment]
It seems to me that in Staging 2, it's looking at your 'Enterprise Limit' even if you're set to SuperAdmin.

My SuperAdmin user account looked like this when I was unable to see the '+ New Enterprise' button.

![image](https://cloud.githubusercontent.com/assets/10843056/9398516/2fe909b4-47eb-11e5-8a9b-7ca40d63ef7e.png)

When I raised my Enterprise Limit to 2, the +New Enterprise button reappeared.

**Comment by sstead** [comment]
Ok, now I feel silly :S 
In production you also need to be both 'Admin' and have a Enterprise Limit set really high to see the '+ new enterprise' button. I thought being superadmin automatically let you own lots of enterprises, apparently not.
False alarm I think.

**Comment by pmackay** [comment]
@sstead @kirstenalarsen what is the Enterprise Limit? Why have a restriction for SuperAdmin at all?

**Comment by kirstenalarsen** [comment]
probably shouldn't be, you're welcome to fix it if you want - perhaps create a separate issue if you want to deal with it (now or later), I'm going to close this one for now
