### ISSUE TITLE
Bump acts-as-taggable-on from 4.0.0 to 5.0.0

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6460]
### What we should change and why (this is tech debt)
Bump it.

### Context
From dependabot, needs some adaptation:
https://github.com/openfoodfoundation/openfoodnetwork/pull/6458

### Impact and timeline
Not the most important thing I guess.

**Comment by RachL** [comment]
@openfoodfoundation/core-devs do we still need this issue?

**Comment by jibees** [comment]
Nop, because we're using `'~> 8.1'`
