### ISSUE TITLE
Bump angular-rails-templates from 0.3.0 to 1.1.0

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6473]
### What we should change and why (this is tech debt)
Bump version.

### Context
From here: https://github.com/openfoodfoundation/openfoodnetwork/pull/6451

### Impact and timeline
I am not sure.

**Comment by RachL** [comment]
@openfoodfoundation/core-devs do we want to keep this issue?

**Comment by jibees** [comment]
Nop, we are currently in `angular-rails-templates (1.2.0)` and it's managed by @dependabot-bot
