### ISSUE TITLE
confirmation emails not coming through to hub or shopper from UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#648]
When a shopper places an order they don't get email confirmation and neither does the hub admin.  I tried to add this to the previous github issue which was exactly the same issue we had last week (I think Rohan came up with a setting that resolved it)  but couldn't find the github issue- sorry.

**Comment by NickWeir63** [comment]
I am re-opening this as the email notification problem has restarted.  Sara Rock is trying to set up a trial shopfront on UK production and cannot get confirmation emails to send to her producers.  I think this was an issue that @pmackay solved for us before - please could one of the Aus team have a look at this as it is fairly urgent for Sara.  thanks

**Comment by kirstenalarsen** [comment]
Would be good to know how @pmackay solved it last time? Then we can
schedule a look at it this week

**Comment by mkllnk** [comment]
I had a look at it at the weekend. Delayed Job wasn't running, so I set it up. It's trying to send emails now, but the rendering of the emails still breaks. It can't find the root url of the site. I hope that Rohan has an idea tomorrow. Rob and I just looked at it again and don't understand how it is supposed to work.

**Comment by NickWeir63** [comment]
SOrted - thanks
