### ISSUE TITLE
Show unit price in Inventory

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#6496]
## Description

**- As an:** enterprise user
**- On page:** /admin/inventory
**- I want to be able to do:** See the price of a single unit when viewing my inventory products.

## Acceptance Criteria & Tests

The new form field needs to accurately reflect the unit price when the inventory price is updated. The field should also conform to the design spec specified in https://github.com/openfoodfoundation/openfoodnetwork/issues/6449#issue-756226197. 

Note that unit price should also be available in the columns dropdown.

1. Go to /admin/inventory
2. Change the price of an override

The changes need to be reflected in the unit price field at all times.

See https://github.com/openfoodfoundation/openfoodnetwork/issues/6494 's "tech considerations" for reference.

## Potential solution

This essentially means reusing the logic implemented for variants in #6494 for variant overrides.

**Comment by jaycmb** [comment]
Put on hold, as discussed in Delivery Circle.
Waiting until after product Uplift - 

> or not as inventory is to be phased out
