### ISSUE TITLE
Show unit price in Shopfront

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#6497]
## Description

**- As a:** user
**- On page:** <enterprise_name>/shop#/shop
**- I want to be able to do:** See the unit price of each of the variants of a product, including the bulk buy modal.

## Acceptance Criteria & Tests

The unit price should include any fees listed in the price breakdown. That is, all fees associated with a variant. See [app/assets/javascripts/templates/price_breakdown.html.haml](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/templates/price_breakdown.html.haml) and [Api::VariantSerializer#fees](https://github.com/openfoodfoundation/openfoodnetwork/blob/f2c37ef64d05bd797ea54fc72acd619ed6879d2a/app/serializers/api/variant_serializer.rb#L10-L13) for reference.

Check the design specs linked in https://github.com/openfoodfoundation/openfoodnetwork/issues/6449#issue-756226197. Watch out mobile!

1. Go to an enterprise's shopfront.
2. When the product is bought in bulk, click on "Add".

The unit price should correctly match the price displayed for the variant in both the variant and the bulk modal.

**Comment by jibees** [comment]
Reference: #6877

**Comment by jaycmb** [comment]
Has this not been done as the first issue of this epic (and been merged behind feature toggle)?

**Comment by jibees** [comment]
This issue was a sort of epic inside an epic, which wasn't a good idea (and it was mine I guess). 
I assume we can close this issue.

**Comment by sauloperez** [comment]
heads-up! we're missing the bulk modal to finish this

![Screenshot from 2021-04-15 08-44-58](https://user-images.githubusercontent.com/762088/114825907-14537a80-9dc7-11eb-8898-bc31ca06d0e3.png)

You need to enable group buy for the product from `/admin/products/<product_name>/group_buy_options`.

**Comment by jibees** [comment]
I juste created new issue: #7426 
Thanks for catching this @sauloperez !

**Comment by Erioldoesdesign** [comment]
So we would need the same sort of design for unit prices label next to the '$3.30' here?

**Comment by jibees** [comment]
@Erioldoesdesign I just added the Unit price next to the '$3.30'.
You can see here : #7428
Feel free to add your comments if it needs some re-design!!

**Comment by RachL** [comment]
I think this is safe to close now @jibees @jaycmb ?
