### ISSUE TITLE
Site crashes when I try to add product image

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#651]
The grumpy cat is appearing when I try to add product images.
This occurs both through the 'New Product' screen, and also when editing an existing product and trying to add an image.

- We've heard that it's happening for users (Farm Foodstore) and it's also occurring in SuperAdmin.
- Have tried JPG and PNG images- neither would upload.

There's no problem in staging2.

I added you @mkllnk  because this seems quite urgent - we have a few new enterprises who might be trying to add products in the next week. But of course, it's up to you when you want to look at this- not sure what else you have on your plate :)

**Comment by mkllnk** [comment]
Okay, according to the logs there has been a memory issue.
```
Errno::ENOMEMspree/admin/products#create
Cannot allocate memory - identify -format '%wx%h,%[exif:orientation]' '/tmp/6b9b611799663da664ee7ed46862cc7d20150817-9503-c7267e.jpg[0]' 2>/dev/null
app/models/spree/product_decorator.rb:15images_attributes=
```

One user got that four times in a row and probably gave up after that.

I just tested the production server with several images. At the moment, the server has around 300MB free memory. Uploading a 6.8MB photo reduces that to a 100MB. So if there are multiple users uploading images, it will definitely fail.

A good solution would be some JavaScript that resizes big images on client side. But somebody already worked on image uploads. @RohanM or @oeoeaio? It would be good to get some info about the current state of that task before starting from scratch.

In the mean time, we could just upgrade the server again. Current memory usage is 91%.

**Comment by kirstenalarsen** [comment]
Have upgraded memory to deal with this for now, has not reoccured since memory upgrade monday night. Would be good to come back and sort out the actual resizing of images at some point but closing this for now
