### ISSUE TITLE
Bump select2-rails from 3.4.9 to 4.0.13 (or ditch it)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6510]
### What we should change and why (this is tech debt)
We can upgrade jquery select2 to a latter version.

Upgrading select2-rails to v3.5 at least will allow us to remove the thor dependency from Gemfile in rails 6 and upgrade thor to v1.
But this upgrade will require some work as seen in #7553

Also noted by @Matt-Yorkley here, we could ditch this dependency: https://github.com/openfoodfoundation/openfoodnetwork/pull/7554/files#r628901503

### Context
https://github.com/openfoodfoundation/openfoodnetwork/pull/6505

### Impact and timeline
I dont think this is important right now.

**Comment by RachL** [comment]
@jibees do you confirm we are on the path to ditch it so we can close here?

**Comment by jibees** [comment]
Exactly. 
Viva `tom-select`!

![200w](https://user-images.githubusercontent.com/296452/191793056-010b6121-cdf7-4020-8ff1-1963959b57ed.gif)
