### ISSUE TITLE
Bump angularjs-rails from 1.5.5 to 1.8.0 

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6511]
### What we should change and why (this is tech debt)
We can upgrade to angularJS 1.8 although we are planning to move away from AngularJS.

### Context
Here https://github.com/openfoodfoundation/openfoodnetwork/pull/6501

### Impact and timeline
I am not sure this upgrade is worth the effort.

**Comment by RachL** [comment]
@openfoodfoundation/core-devs do we want to keep this issue?

**Comment by jibees** [comment]
Nop, we are currently in `angularjs-rails (1.8.0)` and it's managed by @dependabot-bot
