### ISSUE TITLE
Bump foundation-rails from 5.5.2.1 to 6.5.1.0

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6514]
### What we should change and why (this is tech debt)
We could try to make this upgrade.

### Context
Here: https://github.com/openfoodfoundation/openfoodnetwork/pull/6512

### Impact and timeline
I am not sure this is required as we are planning to move to a different stack.

**Comment by RachL** [comment]
@openfoodfoundation/core-devs do we still need this issue?

**Comment by jibees** [comment]
Closing, as we don't use `foundation-rails` anymore
