### ISSUE TITLE
Bump acts-as-taggable-on from 4.0.0 to 5.0.0

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6519]
### What we should change and why (this is tech debt)
we can upgrade acts-as-taggable-on to the latest version but it will require some work to fix some specs.

### Context
Here: https://github.com/openfoodfoundation/openfoodnetwork/pull/6513

### Impact and timeline
I dont think we need to worry about this now.

Release dates:
6.5.0 - November 07, 2019 (53.5 KB)
6.0.0 - June 18, 2018 (52.5 KB)
5.0.0 - May 21, 2017 (53 KB)
4.0.0 - August 01, 2016 (49 KB) 

v6 is for rails 5.

**Comment by sigmundpetersen** [comment]
Updated to latest in #7814 so we can close this
