### ISSUE TITLE
NoMethodError in spree/admin/reports#products_and_inventory

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#652]
## Exception in OpenFoodNetwork

**NoMethodError** in **spree/admin/reports#products_and_inventory**
undefined method &#x60;calculator&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/55d68b98ea1b57dee7f19ea9?event_id=55d69a9ff41b138f0a983497)
## Stacktrace

```
lib/open_food_network/lettuce_share_report.rb:45 - gst
lib/open_food_network/lettuce_share_report.rb:28 - block in table
lib/open_food_network/lettuce_share_report.rb:21 - table
app/controllers/spree/admin/reports_controller_decorator.rb:222 - products_and_inventory
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/55d68b98ea1b57dee7f19ea9?event_id=55d69a9ff41b138f0a983497)

**Comment by mkllnk** [comment]
This happened with a "None" tax category that had no tax rates. The quick fix is to remove that category that doesn't have a calculator. In the long term, the code should deal with that case. It seems to be a one liner.

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **spree/admin/reports#products_and_inventory**
undefined method &#x60;calculator&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/55d68b98ea1b57dee7f19ea9?event_id=55d6ad967697c07614da62fc)

## Stacktrace

    lib/open_food_network/lettuce_share_report.rb:45 - gst
    lib/open_food_network/lettuce_share_report.rb:28 - block in table
    lib/open_food_network/lettuce_share_report.rb:21 - table
    app/controllers/spree/admin/reports_controller_decorator.rb:222 - products_and_inventory

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/55d68b98ea1b57dee7f19ea9?event_id=55d6ad967697c07614da62fc)

**Comment by RachL** [comment]
@mkllnk do you think it is safe to close this one?
