### ISSUE TITLE
Error 500 when connecting Stripe accounts on OFN BE

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6521]
## Description

Okay you are going to hate me for this one because it does not happen to ALL users. Only some... 

## Steps to Reproduce

1. They click on the blue button connect with stripe on OFN
2. Then the little sign in link on the top right
3. They sign in on stripe
4. They are back to OFN where they need to click again on connect to finish linking both account. On click boom :snail: error 500
5. The stripe account is verified, all seems ok on this side.

Name of the enterprise: `ELS - Produits fairtrade (Oxfam MDM, Altromercato IT, Ethicable,...) et régionaux (BELVAS, Brasserie de la Lesse,...)`

We did a test together today, and I think this is the bugsnag linked to it: https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/5fb945ace364320017645d2e?filters[event.since][0]=30d&filters[error.status][0]=open

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/579af774-253e-4f77-9c85-57139d3d340f)

Console:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/158f7db0-f1ae-4033-86f3-3fc6ea8901ef)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v.3.4.4
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by andrewpbrett** [comment]
That bug report seems to indicate that `spree_current_user` is nil.... you're saying that it's only after they click on the button that the 500 happens? 

I looked at the git history and neither of those two files have changed recently (like in the last three years). So this is probably just an edge case we haven't encountered before and not a recent regression that might be happening to more people.

**Comment by andrewpbrett** [comment]
I looked at the screencast from @RachL and noticed that the person was signed into https://www.openfoodnetwork.be, but stripe was redirecting them to https://openfoodnetwork.be (no www). So for now we can probably change the stripe redirect, but this is a larger issue. 

Ah, yeah, looks like it's already been noted:
https://github.com/openfoodfoundation/openfoodnetwork/issues/5179
https://github.com/openfoodfoundation/ofn-install/issues/643
