### ISSUE TITLE
Report: refactor Lettuceshare report so more efficient (currently timing out as super-admin) 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#653]
https://openfoodnetwork.org.au/admin/reports/products_and_inventory?report_type=lettuce_share

**Comment by elf-pavlik** [comment]
does it relate to https://lettuceshare.org/ ?

**Comment by kirstenalarsen** [comment]
yes, this is the report that extracts info on product availability for
import into lettuceshare. I think it is working fine but this was a note I
made on implementation that it is pretty slow. This refactor not currently
scheduled by us . . will add to my list of things to check with the user
that commissioned this e.g. whether they're happy with it the way it is or
might want to upgrade it at some point

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/optimisations-suggestions/1176
