### ISSUE TITLE
Removal of app/controllers/spree/user_registrations_controller.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6531]
### What we should change and why (this is tech debt)

This is a followup of issue #6418

### Context

This came up in the code review of #6454, see https://github.com/openfoodfoundation/openfoodnetwork/issues/6454#issuecomment-742464086

**Comment by arku** [comment]
@luisramos0 I see `Spree::UserRegistrationsController` being used [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/user_registrations_controller.rb#L3).

Just to make sure, is it fine to inherit from `Devise::RegistrationsController` in `UserRegistrationsController`?

**Comment by Matt-Yorkley** [comment]
> is it fine to inherit from Devise::RegistrationsController in UserRegistrationsController?

Yes :+1:

**Comment by vsmay98** [comment]
Hello @filipefurtad0 
Can I work on this issue?

**Comment by jibees** [comment]
Hi @vsmay98 👋 
Sure, I'll assign you.
