### ISSUE TITLE
Missing Translation: Payment Method types

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6535]
## Description

Translation keys for the different payment method types are missing:
- Cash/EFT/etc (Payments for which automatic validation is not required)
- Paypay Express
- Stripe
- Stripe SCA
- Pinpayments
- Mastercard Internet Gateway Service (MIGS) <-- though I believe we are removing this one

While we are deprecating and removing Stripe (Stripe Connect) payment method it would be useful to be able to rename it. 

## Expected Behavior

These fields can all be translated.

## Actual Behaviour

They can't

## Steps to Reproduce

1. Go to create a new payment method
2. The payment method types are all hard coded in English

## Animated Gif/Screenshot

![Screenshot from 2020-12-15 10-44-05](https://user-images.githubusercontent.com/8669848/102205018-8623c200-3ec2-11eb-9516-16a3bdb1aa2a.png)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
@openfoodfoundation/core-devs is this one a good first issue?

**Comment by andrewpbrett** [comment]
@RachL Sure!

**Comment by PauloVilarinho** [comment]
I would like to take this issue!

**Comment by sauloperez** [comment]
all yours @PauloVilarinho
