### ISSUE TITLE
3D-Secure cards not charged when placing subscriptions with Stripe SCA payment method

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6543]
## Description

PR #6469 introduces changes on the setup and offline charging for subscriptions.

Before this PR, orders placed through subscriptions with Stripe SCA in combination with an authenticated 3D-Secure card (such as 4000002760003184) are not charged, and return the error - seen on the emails to the customer/hub:

`Invalid payment state`

After this PR, the customer can proceed to the authentication in  in the customer section `/account#/cards` of that card. However, placing the order results in an uncharged card, returning the error, via Email:

`Your card was declined. This transaction requires authentication. `

This introduces a regression, see discussion:
https://openfoodnetwork.slack.com/archives/CSCPHGVSS/p1608203766100600

## Expected Behavior

Stripe-SCA charges from 3D-auth cards should allow the placement of subscriptions.

## Actual Behaviour

Stripe-SCA charges from 3D-auth cards currently do not allow the placement of subscriptions.

## Steps to Reproduce

Customer
1. Add the 3D-secure card `4000002760003184` to the /account#/cards section.
2. Allow charges to a given hub
3. The authentication window should pop-up. Confirm authentication for that card.

Admin
1. Set up an OC, with a schedule - take note of the OC id number
2. Create a subscription for the customer above, setting the Stripe SCA as a payment method (optional: take note of the subscription id number)

Test the placement of the set subscription, following the procedure described:
- here https://github.com/openfoodfoundation/openfoodnetwork/wiki/Testing-Subscriptions (you'll need both OC and Subscription id nr.)
- or following #6291 - (you'll need the OC id nr.) a fix is underway for this, which reduces the waiting time, after the confirmation of the subscription (#6541)

## Your Environment

* Version used: this would be introduced in upcoming v3.4.5
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by andrewpbrett** [comment]
With the x-3184 card, this is expected behavior. That card always requires the extra SCA step, even if it's been set up for offline payments by the customer. 

If this is happening with the x-3155 card, it's an issue. That card should not require the extra SCA step for offline payments if the customer has set it up. 

See https://stripe.com/docs/testing

I think this should be closed, but will wait for test results to come back.

**Comment by filipefurtad0** [comment]
Thanks again for feedback on this @andrewpbrett .

> If this is happening with the x-3155 card, it's an issue. That card should not require the extra SCA step for offline payments if the customer has set it up.

Please see: https://github.com/openfoodfoundation/openfoodnetwork/pull/6533#issuecomment-747602420
