### ISSUE TITLE
Bulk Coop Reports: enable include 'group buy unit size' whenever field is !null, even if group buy is set to no

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#655]
Turning the Product 'group buy' to Yes causes two fields to appear in the shopfront, one for the amount people want and the other for max

The value in the Group Buy Unit Size field is used in a number of places, Bulk Order management and reports etc.

Currently the Bulk Coop reports do not include the Group Buy Unit Size field in the Unit size column) unless Group Buy is also set to on, which limits usefulness

Include the value in this column if there is anything in it, regardless of the group buy on or off

**Comment by sstead** [comment]
If I go to Reports and click this button....
![image](https://cloud.githubusercontent.com/assets/10843056/9750929/c303967e-56e1-11e5-9417-1692c60ae772.png)

... then the Group Buy Unit Sizes only show for products set to YES. (as seen below)...

![image](https://cloud.githubusercontent.com/assets/10843056/9750937/d9dee420-56e1-11e5-834e-4eb0924e9bbc.png)

.... but if I then select the report I want from the drop down menu..... (the same report which was already showing)... and click update.... it repopulates the table, with the correct Group Buy values (included products set to NO)

![image](https://cloud.githubusercontent.com/assets/10843056/9750954/218f1c86-56e2-11e5-9f6b-311b57a1c31c.png)

When I download them as a CSV, they're always correct.
