### ISSUE TITLE
Missing translation "Tags" and "Add a Tag" 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6550]
## Description

The translation key for "Tags" and "Add a Tag" are missing. I'm adding both to the same issue, as I think these go hand-in-hand - see steps to reproduce.

## Steps to Reproduce

This is seen on several pages.

1. Log in as Admin
2. Navigate to:
- /shipping_methods/new
- /payment_methods/new
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e4388590-84b7-4023-a4ef-86d58ee84b9b)

- Order Cycles - Outgoing:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/8403cce5-667b-4bc9-8e16-148dfb24240a)

- /customers
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/a2356823-4cf8-4460-ae97-1074566b4d12)

- /inventory
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/686e7556-2334-41b2-a8a7-1a64d5cbebe2)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.4.5
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by RachL** [comment]
this is now working 🎉
