### ISSUE TITLE
When uploading product images, icons are not scaled

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#6563]
## Description

In path, for example: /admin/products/iaitsa/images/1/edit
when upload product image in format 275x127 , then thumbnail viewed like in screenshot below

## Expected Behavior

Image scaled to right way

## Actual Behaviour

image croped

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

Uploaded source image:

![image](https://user-images.githubusercontent.com/928628/103158172-18ce3600-47cc-11eb-8e48-75be749c45d7.png)

Result image

![image](https://user-images.githubusercontent.com/928628/103158163-f0ded280-47cb-11eb-83f5-1bf8332393d6.png)

## Your Environment

* Version used: 3.4.5
* Browser name and version: Firefox 78.5.0esr 
* Operating System and version (desktop or mobile): Desktop

**Comment by PauloVilarinho** [comment]
I would like to take this issue

**Comment by PauloVilarinho** [comment]
This bug seems to be related to the paperclip gem configuration, so it is a simples fix

which of these results is the best way to scale the image? 

![Captura de tela de 2020-12-28 15-57-34](https://user-images.githubusercontent.com/33267902/103237210-aa9d8680-4925-11eb-8d8f-300812c3753f.png)

**Comment by andrewpbrett** [comment]
I’d definitely say the first one!

**Comment by PauloVilarinho** [comment]
This problem is happening on the store page too.

![Captura de tela de 2020-12-28 16-39-53](https://user-images.githubusercontent.com/33267902/103239195-92c90100-492b-11eb-9013-0b33022dffa2.jpg)

It is the same fix but for a different style, I'm adding that to my PR

**Comment by romale** [comment]
> This bug seems to be related to the paperclip gem configuration, so it is a simples fix
> 
> which of these results is the best way to scale the image?
> 
> ![Captura de tela de 2020-12-28 15-57-34](https://user-images.githubusercontent.com/33267902/103237337-0ec04a80-4926-11eb-94aa-89dd29dee013.jpg)
> 
> @romale @andrewpbrett

I'm agree with @andrewpbrett , first is the best way

**Comment by Matt-Yorkley** [comment]
I'd say this isn't a simple decision for a couple of reasons: it will change the look and layout of the shopfront, and also we would have to re-run a bunch of image resizing operations on all production servers, so it's not as simple as slapping the merge button...

**Comment by PauloVilarinho** [comment]
@Matt-Yorkley I think a good idea would be to enforce the size of the image using CSS.

enforcing the size would maintain the site layout preserving the changes to the image

The image resizing operations seems to be a problem since this change only applies to the new photo updates

**Comment by andrewpbrett** [comment]
> it will change the look and layout of the shopfront

Is that because the shopfront layout assumes square images? I wonder if there's a way to add letterboxing if the uploaded image isn't square.

I'm going to move this back to In Dev for now. Feel free to re-request review @PauloVilarinho

**Comment by mkllnk** [comment]
I believe that this has been solved with Active Storage.
