### ISSUE TITLE
Changing the currency in the UI breaks the instance (superadmin)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6568]
## Description

Changing the currency in the UI currently breaks an instance (if the server is not restarted): the shopfront does not load any products, see [Bugsnag error](https://app.bugsnag.com/katuma/katuma/errors/5fe9b9e14f9c5f0017f53a43?event_id=5fe9b9e100661c75fae90000&i=sk&m=nw).

## Expected Behavior

Changing the currency in the UI does not break the instance (if the server is not restarted). As discussed elsewhere, perhaps this option should be removed from the UI? Opening a tech-debt as well - see Possible Fix section.

## Actual Behaviour

A superadmin user can change the currency in the UI. This can easily break the instance. 

## Steps to Reproduce

As superadmin
1. Go to /admin/general_settings/edit
2. Change the selected currency to another one. Click Update.
3. Visit a shop from this instance, and see a broke shopfront (pic below).

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/103212464-bfb4ee00-4902-11eb-9b38-8efcb9c44c0e.png)

## Workaround

Contacting a sysadmin to restart the server.

## Severity

This surely does not happen often but high impact, bug-s4?

## Your Environment

* Version used: v.3.4.5
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): DesktopUbuntu 20.04

## Possible Fix

This issue can be closed by removing the ability for a user to change the currency in the UI, see tech-debt #6569.

**Comment by Matt-Yorkley** [comment]
Closed via #6575
