### ISSUE TITLE
Remove the ability for a superadmin to change the currency in the UI

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6569]
### What we should change and why (this is tech debt)

Proposing to remove the ability to change the currency in the UI, as doing so easily break the instance - if the server is not restarted, see bug #6568.

### Context

This came up in the context of [this discussion](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1604418560107000) and would close bug #6568

**Comment by PauloVilarinho** [comment]
I would like to work on this

**Comment by RachL** [comment]
@openfoodfoundation/core-devs if we remove it, how is a currency assigned to an instance?

**Comment by luisramos0** [comment]
It's defined in a config file through ofn install. I think this pr is a
good change.
