### ISSUE TITLE
[API Cleanup] Remove XML format

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6579]
### What we should change and why (this is tech debt)

We check for XML format in the requests coming in to API controllers [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/ec4d171993f9a5b2e1ac48a517f8c0806deed87d/app/controllers/api/base_controller.rb#L65-L73) but none of our API endpoints return XML...

:fire::fire::fire:

### Context

Came up during code review on https://github.com/openfoodfoundation/openfoodnetwork/pull/6577

**Comment by Matt-Yorkley** [comment]
Note: we should probably be setting the response's `content_type` to `application/json` _unconditionally_ here, if we're removing this conditional.

**Comment by PauloVilarinho** [comment]
So the main goal of this issue is to change the content-type to unconditionally be application/json  and to remove all the explicit content_types in all the controllers?

something like this 
```
    def set_content_type
      content_type = "application/json"
      headers["Content-Type"] = content_type
    end
```

and changing in every controller the response from this: 

```render status: :not_found, plain: {}.to_json, content_type: "application/json"```

to this style: 

```render status: :not_found, json: ''```

**Comment by Matt-Yorkley** [comment]
I think those controller responses are being handled elsewhere, so the scope for this issue is just changing the `set_content_type` method. It can be one line though, not two :+1:
```ruby
def set_content_type
  headers["Content-Type"] = "application/json"
end
```

**Comment by PauloVilarinho** [comment]
I closed the first one because I accidentally committed changes that I made for other PR
