### ISSUE TITLE
AbstractController::DoubleRenderError in spree/api/line_items#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#658]
## Exception in OpenFoodNetwork

**AbstractController::DoubleRenderError** in **spree/api/line_items#update**
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like &quot;redirect_to(...) and return&quot;.

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/557a2233ea1b57dee74f1979?event_id=55e276a13dc28b2a35508a20)
## Stacktrace

```
gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:15 - render
bundler/gems/spree-afcc23e489eb/api/app/controllers/spree/api/base_controller.rb:73 - error_during_processing
gems/activesupport-3.2.21/lib/active_support/rescuable.rb:80 - call
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/557a2233ea1b57dee74f1979?event_id=55e276a13dc28b2a35508a20)

**Comment by mkllnk** [comment]
This happened three times within the last month in production. Always the same user. It can mean that updating a line item in bulk order management doesn't save or hangs.

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**AbstractController::DoubleRenderError** in **spree/api/line_items#update**
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like &quot;redirect_to(...) and return&quot;.

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/557a2233ea1b57dee74f1979?event_id=5605bdd426d1b1e439c26e06)

## Stacktrace

    gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:15 - render
    bundler/gems/spree-afcc23e489eb/api/app/controllers/spree/api/base_controller.rb:73 - error_during_processing
    gems/activesupport-3.2.21/lib/active_support/rescuable.rb:80 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/557a2233ea1b57dee74f1979?event_id=5605bdd426d1b1e439c26e06)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**AbstractController::DoubleRenderError** in **spree/api/line_items#update**
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like &quot;redirect_to(...) and return&quot;.

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/557a2233ea1b57dee74f1979?event_id=56394b907e0967b40b5e1795)

## Stacktrace

    gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:15 - render
    bundler/gems/spree-afcc23e489eb/api/app/controllers/spree/api/base_controller.rb:73 - error_during_processing
    gems/activesupport-3.2.21/lib/active_support/rescuable.rb:80 - call

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/557a2233ea1b57dee74f1979?event_id=56394b907e0967b40b5e1795)

**Comment by RachL** [comment]
@mkllnk do you know if this error occurred again or if we can close this issue?
