### ISSUE TITLE
[API Cleanup] DRY pagination data

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6581]
### What we should change and why (this is tech debt)

We have a nice standardised format for rendering pagination data in our API endpoints (which was previously reviewed and agreed on), but we have several different copies of the same code for displaying that data, spread around all over the codebase. This needs to be dried up a bit so it's defined clearly in one place.

- https://github.com/openfoodfoundation/openfoodnetwork/blob/76def3a74feb71995b8102da1e07522c57ae1ba3/app/controllers/api/exchange_products_controller.rb#L92-L99
- https://github.com/openfoodfoundation/openfoodnetwork/blob/27586d072da92f22cce13f835722dbb846320d9c/app/controllers/admin/bulk_line_items_controller.rb#L94-L103
- https://github.com/openfoodfoundation/openfoodnetwork/blob/7408c45980b8452c8b0281f6a6318ac590615d89/app/controllers/api/products_controller.rb#L151-L158
- https://github.com/openfoodfoundation/openfoodnetwork/blob/ec4d171993f9a5b2e1ac48a517f8c0806deed87d/app/services/search_orders.rb#L11-L20

### Context

API review.

**Comment by PauloVilarinho** [comment]
the search orders service seems to do exactly what we need but it is set up to do it just for orders. I think a good solution would be to create a more generic service and replace this service with the generic one. @Matt-Yorkley, what you think about this idea?

**Comment by Matt-Yorkley** [comment]
Initially I thought it was only API controllers that needed it, so I thought putting this in the `Api::BaseController` might be sensible (as different API controllers can define different defaults for the number of results per page), but it's used in `Admin::BulkLineItemsController` as well. I'd consider putting it in a controller **concern**, and maybe including that concern in both the `Api::BaseController` and `Admin::BulkLineItemsController`.
