### ISSUE TITLE
UK production not opening

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#662]
i get this when i try to open UK production
![screenshot 2015-09-02 11 45 00](https://cloud.githubusercontent.com/assets/10517702/9629121/3587e788-5168-11e5-8bc8-387b703ea81e.png)
i wonder if @pmackay has taken it down because of the problems we have been having with it?  Will the Aussies be able to get to it to check what the problems are?
thanks
N

**Comment by lin-d-hop** [comment]
By 'it' do you mean the SSL certs?
 I notice in the emails we've got an overdue payment email pending. Not sure if we've paid for the new one but looks to me like we haven't uploaded it and hence the error. 

Should be a quick one, but just another task for @pmackays long list :-(

**Comment by pmackay** [comment]
Yeah I paid for the new certs on Monday but haven’t updated to servers yet.

**Comment by NickWeir63** [comment]
OK thanks - I will close this

**Comment by pmackay** [comment]
Ha, well its not fixed yet! :)

**Comment by NickWeir63** [comment]
Hi @pmackay 
I need to send in a report to Esmee Fairbairn in the next day or so, showing that OFN UK is set up - even if not fully running Storudco yet.  Please can you update the server with the new SSL certs so that we can fix the loading issue and make it look like OFN is set up.
Sorry to hassle you - I know you are busy
Thanks very much
Nick

**Comment by pmackay** [comment]
I am working on this. Will try to resolve tonight.

**Comment by pmackay** [comment]
Site now loads. Please say if you see any issues.

**Comment by NickWeir63** [comment]
great - thanks very much @pmackay
