### ISSUE TITLE
Snail when running Order Cycle Customer Totals Report

### ISSUE THREAD

**Issue by chezaorchard** [openfoodfoundation/openfoodnetwork#6623]
## Description
Aus customer Prom Coast Wholefoods Collective (1965) are getting a snail when running the Order Cycle Customer Totals Report. Snail is generated when including a date before October 4, 2020 in the range selected. The snail comes up when trying to run this report as both a Manager of Prom Coast and when logged in as Superadmin.

I have also tested for other Aus Hubs/Enterprises and found no problems - reports are running fine for dates before and after October 4, 2020.

## Expected Behavior
The report should run successfully for any date range

## Actual Behaviour
The report will not run, produces snail error, for any date range prior to October 4, 2020.

## Steps to Reproduce
1. Login as SuperAdmin OR as a manager of Enterprise 1965
2. Go to reports
3. Select Customer Totals
4. Choose date range beginning prior to October 4, 2020 

## Workaround
No workaround

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: MacOS Mojave 10.14.6
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Mac Desktop

Screenshots of error with dev tools logged in as manager & as super admin as they seem slightly different:

![Manager_PromCoast_customertotals_3Oct](https://user-images.githubusercontent.com/68367600/103861961-4d1dec80-5112-11eb-851f-e134d08bf399.jpg)
![SuperAdmin_PromCoast_CustomerTotals_3Oct](https://user-images.githubusercontent.com/68367600/103861969-50b17380-5112-11eb-949d-3b56bd2c7940.jpg)

**Comment by lin-d-hop** [comment]
CLosing as likely fixed with new reports work.
