### ISSUE TITLE
Emails down on staging-ES

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6637]
## Description

Emails not arriving and triggering Bugsnag error:
```
ActionView::Template::ErrorActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper
Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
```
https://app.bugsnag.com/katuma/katuma/errors/5ff091cd0d785c00198d1182?&event_id=5ffb3ce3006591c4b3750000

Tested:
Testmail, Intercept and Blind copy -> **working fine**
Signup, password recovery, order confirmation, pdf invoice -> **not working**

## Steps to Reproduce

1. Trigger signup, password recovery, order confirmation, pdf invoice emails
2. See bugsnag for the error 
## Your Environment

* Version used: spotted after v.3.4.5 - not sure if related

**Comment by Matt-Yorkley** [comment]
Are those emails working on other staging servers if master is staged?

**Comment by filipefurtad0** [comment]
I've tested emails in UK-staging, after the deployment of build #2033 (from Friday, Jan 08 2021 at 16:56). Emails were working fine here.

**Comment by Matt-Yorkley** [comment]
But what was deployed on `es-staging` when this bug was encountered?

**Comment by filipefurtad0** [comment]
It was first observed after this deploy:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/katuma-staging/deploys/499

And yesterday it still was broken, after staging this build:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/katuma-staging/deploys/505

**Comment by filipefurtad0** [comment]
No more staging-Katuma...
Closing.
