### ISSUE TITLE
Summary calculator box not populating in BOM for 'item' products 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#664]
![image](https://cloud.githubusercontent.com/assets/10843056/9676732/841aabd6-5313-11e5-8adf-d27d4a83c2d6.png)

![image](https://cloud.githubusercontent.com/assets/10843056/9676736/95508e98-5313-11e5-806c-5743d53121cb.png)

**Comment by RachL** [comment]
handled by: https://github.com/openfoodfoundation/openfoodnetwork/issues/8540
