### ISSUE TITLE
Metabase stopped syncing after Dec 31st for FR & AUS

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#6648]
## Description
 
Metabase stopped syncing for FR & AUS, latest data is from Dec 31st.
This affects all queries on data for 2021 and most of the KPIs on the Global Dashboards.

## Expected Behavior
Data should update automatically, so that  queries can be performed and dashboards provide correct information.

## Actual Behaviour

Data is only available until Dec31st which leads to errors or, worse: misleading information in queries and dashboard (in case of KPIs like "New Customers" or "Current Weeks Average Order Size"

## Steps to Reproduce

https://data.openfoodnetwork.org.uk/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo4NCwicXVlcnkiOnsic291cmNlLXRhYmxlIjo3MzEsIm9yZGVyLWJ5IjpbWyJkZXNjIixbImZpZWxkLWlkIiwxMjE3MV1dXX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0= 

1. Go to Metabase and open FR or AUS Database
2. Go to Dashboard, e.g.: https://data.openfoodnetwork.org.uk/dashboard/17?date_range=2021-01-01~2021-01-09
3. Or Go to Spree Orders and sort by Completed At, Descending.

## Animated Gif/Screenshot

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/39744592/104316943-20345580-54d5-11eb-9823-0b8432125903.png">

Order sorted by "Updated At" Descending

## Workaround
No Workaround

## Severity
bug-s2: a non-critical feature is broken, no workaround

**Comment by Matt-Yorkley** [comment]
France should be back now, and Aus will be back shortly. 

It would be nice to see what we can do to avoid these disruptions. I think there's a couple of things that can be updated to newer versions, which could potentially include some bugfixes or stability improvements. That would be worth checking out, and should be fairly simple.

**Comment by sauloperez** [comment]
For the record and to share the knowledge, can you explain what you did @Matt-Yorkley ?

**Comment by jaycmb** [comment]
+1 @sauloperez 

As mentioned in Product Curation, it would be great if @Matt-Yorkley  could 
1. explain what caused the syncing to stop, is it the same cause every time or different reasons?
2. explain what you did to fix it -> wondering if there is a way that I or anyone else from product could learn how to do so (#tech-support)

**Comment by RachL** [comment]
@Matt-Yorkley I'm sorry I'm reopening, it does seem the connection with FR is lost? 

![image](https://user-images.githubusercontent.com/6525576/104620828-b57b4980-568f-11eb-8164-d547d15b4656.png)

**Comment by Matt-Yorkley** [comment]
I was updating some bits earlier, it's back now. :+1:
