### ISSUE TITLE
ActiveRecord::RecordNotUnique in spree/admin/products#clone

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#665]
## Exception in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#clone**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(pumpkin-jap-slash-kent-4-8) already exists.
: INSERT INTO &quot;spree_products&quot; (&quot;available_on&quot;, &quot;count_on_hand&quot;, &quot;created_at&quot;, &quot;deleted_at&quot;, &quot;description&quot;, &quot;group_buy&quot;, &quot;group_buy_unit_size&quot;, &quot;inherits_properties&quot;, &quot;meta_description&quot;, &quot;meta_keywords&quot;, &quot;name&quot;, &quot;notes&quot;, &quot;on_demand&quot;, &quot;permalink&quot;, &quot;primary_taxon_id&quot;, &quot;shipping_category_id&quot;, &quot;supplier_id&quot;, &quot;tax_category_id&quot;, &quot;updated_at&quot;, &quot;variant_unit&quot;, &quot;variant_unit_name&quot;, &quot;variant_unit_scale&quot;) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=55ed003254daff913a6ec52d)
## Stacktrace

```
gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:661 - block in exec_query
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=55ed003254daff913a6ec52d)

**Comment by mkllnk** [comment]
This results in an error while duplicating a product. It just happened the first time after two months again.

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::InvalidForeignKey** in **spree/admin/shipping_categories#destroy**
PG::Error: ERROR:  update or delete on table &quot;spree_shipping_categories&quot; violates foreign key constraint &quot;spree_products_shipping_category_id_fk&quot; on table &quot;spree_products&quot;
DETAIL:  Key (id)=(2) is still referenced from table &quot;spree_products&quot;.
: DELETE FROM &quot;spree_shipping_categories&quot; WHERE &quot;spree_shipping_categories&quot;.&quot;id&quot; = $1

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5618594528d5b25c185dd4f8)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:672 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5618594528d5b25c185dd4f8)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#clone**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(medium-mixed-vegetable-and-fruit-box-2) already exists.
: INSERT INTO &quot;spree_products&quot; (&quot;available_on&quot;, &quot;count_on_hand&quot;, &quot;created_at&quot;, &quot;deleted_at&quot;, &quot;description&quot;, &quot;group_buy&quot;, &quot;group_buy_unit_size&quot;, &quot;inherits_properties&quot;, &quot;meta_description&quot;, &quot;meta_keywords&quot;, &quot;name&quot;, &quot;notes&quot;, &quot;on_demand&quot;, &quot;permalink&quot;, &quot;primary_taxon_id&quot;, &quot;shipping_category_id&quot;, &quot;supplier_id&quot;, &quot;tax_category_id&quot;, &quot;updated_at&quot;, &quot;variant_unit&quot;, &quot;variant_unit_name&quot;, &quot;variant_unit_scale&quot;) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5626f44b84f2a170702af9cd)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:661 - block in exec_query

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5626f44b84f2a170702af9cd)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#clone**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(bush-beans-3) already exists.
: INSERT INTO &quot;spree_products&quot; (&quot;available_on&quot;, &quot;count_on_hand&quot;, &quot;created_at&quot;, &quot;deleted_at&quot;, &quot;description&quot;, &quot;group_buy&quot;, &quot;group_buy_unit_size&quot;, &quot;inherits_properties&quot;, &quot;meta_description&quot;, &quot;meta_keywords&quot;, &quot;name&quot;, &quot;notes&quot;, &quot;on_demand&quot;, &quot;permalink&quot;, &quot;primary_taxon_id&quot;, &quot;shipping_category_id&quot;, &quot;supplier_id&quot;, &quot;tax_category_id&quot;, &quot;updated_at&quot;, &quot;variant_unit&quot;, &quot;variant_unit_name&quot;, &quot;variant_unit_scale&quot;) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=563050684c2b7e7b7926d0d5)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:661 - block in exec_query

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=563050684c2b7e7b7926d0d5)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#clone**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(pink-muesli-christmas-special-gf-1) already exists.
: INSERT INTO &quot;spree_products&quot; (&quot;available_on&quot;, &quot;count_on_hand&quot;, &quot;created_at&quot;, &quot;deleted_at&quot;, &quot;description&quot;, &quot;group_buy&quot;, &quot;group_buy_unit_size&quot;, &quot;inherits_properties&quot;, &quot;meta_description&quot;, &quot;meta_keywords&quot;, &quot;name&quot;, &quot;notes&quot;, &quot;on_demand&quot;, &quot;permalink&quot;, &quot;primary_taxon_id&quot;, &quot;shipping_category_id&quot;, &quot;supplier_id&quot;, &quot;tax_category_id&quot;, &quot;updated_at&quot;, &quot;variant_unit&quot;, &quot;variant_unit_name&quot;, &quot;variant_unit_scale&quot;) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=56397ec8ca7fef0b5b1e5e43)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:661 - block in exec_query

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=56397ec8ca7fef0b5b1e5e43)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#clone**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(broad-beans-7-8) already exists.
: INSERT INTO &quot;spree_products&quot; (&quot;available_on&quot;, &quot;count_on_hand&quot;, &quot;created_at&quot;, &quot;deleted_at&quot;, &quot;description&quot;, &quot;group_buy&quot;, &quot;group_buy_unit_size&quot;, &quot;inherits_properties&quot;, &quot;meta_description&quot;, &quot;meta_keywords&quot;, &quot;name&quot;, &quot;notes&quot;, &quot;on_demand&quot;, &quot;permalink&quot;, &quot;primary_taxon_id&quot;, &quot;shipping_category_id&quot;, &quot;supplier_id&quot;, &quot;tax_category_id&quot;, &quot;updated_at&quot;, &quot;variant_unit&quot;, &quot;variant_unit_name&quot;, &quot;variant_unit_scale&quot;) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=564403de28e58bed2d2359d9)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:661 - block in exec_query

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=564403de28e58bed2d2359d9)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::InvalidForeignKey** in **spree/admin/users#destroy**
PG::Error: ERROR:  update or delete on table &quot;spree_users&quot; violates foreign key constraint &quot;spree_orders_user_id_fk&quot; on table &quot;spree_orders&quot;
DETAIL:  Key (id)=(888) is still referenced from table &quot;spree_orders&quot;.
: DELETE FROM &quot;spree_users&quot; WHERE &quot;spree_users&quot;.&quot;id&quot; = $1

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=56456d85b4fe779711c3d4f5)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:672 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=56456d85b4fe779711c3d4f5)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#clone**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(sunflower-rye-porter-4) already exists.
: INSERT INTO &quot;spree_products&quot; (&quot;available_on&quot;, &quot;count_on_hand&quot;, &quot;created_at&quot;, &quot;deleted_at&quot;, &quot;description&quot;, &quot;group_buy&quot;, &quot;group_buy_unit_size&quot;, &quot;inherits_properties&quot;, &quot;meta_description&quot;, &quot;meta_keywords&quot;, &quot;name&quot;, &quot;notes&quot;, &quot;on_demand&quot;, &quot;permalink&quot;, &quot;primary_taxon_id&quot;, &quot;shipping_category_id&quot;, &quot;supplier_id&quot;, &quot;tax_category_id&quot;, &quot;updated_at&quot;, &quot;variant_unit&quot;, &quot;variant_unit_name&quot;, &quot;variant_unit_scale&quot;) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22) RETURNING &quot;id&quot;

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5653fda59e5621dd41ce06b0)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:661 - block in exec_query

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5653fda59e5621dd41ce06b0)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::InvalidForeignKey** in **spree/admin/users#destroy**
PG::Error: ERROR:  update or delete on table &quot;spree_users&quot; violates foreign key constraint &quot;spree_orders_user_id_fk&quot; on table &quot;spree_orders&quot;
DETAIL:  Key (id)=(3441) is still referenced from table &quot;spree_orders&quot;.
: DELETE FROM &quot;spree_users&quot; WHERE &quot;spree_users&quot;.&quot;id&quot; = $1

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5689e3d1f57a92164f2807ca)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - get_last_result
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176 - exec_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:672 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5689e3d1f57a92164f2807ca)

**Comment by daniellemoorhead** [comment]
@RohanM is this done? Can the issue be closed, or does it need to be moved into the Australian Backlog milestone?

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::InvalidForeignKey** in **spree/admin/users#destroy**](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=56cf8f217da36fb94f0e9120)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::InvalidForeignKey** in **spree/admin/users#destroy**](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=56d67666cf1028f623cc53f3)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::RecordNotUnique** in **spree/admin/products#clone**](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=56fb48aced383f5f77cb6d58)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::InvalidForeignKey** in **spree/admin/users#destroy**](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f104fc47e6d27c285bfb98?event_id=5710668c434db287359d9d77)
