### ISSUE TITLE
ActiveRecord::RecordNotUnique in spree/admin/products#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#666]
## Exception in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(lettuce-green-coral) already exists.
: UPDATE &quot;spree_products&quot; SET &quot;permalink&quot; = &#x27;lettuce-green-coral&#x27;, &quot;group_buy&quot; = &#x27;f&#x27;, &quot;available_on&quot; = &#x27;2015-09-06 14:00:00.000000&#x27;, &quot;meta_keywords&quot; = &#x27;&#x27;, &quot;meta_description&quot; = &#x27;&#x27;, &quot;notes&quot; = &#x27;&#x27;, &quot;updated_at&quot; = &#x27;2015-09-08 08:21:48.514929&#x27; WHERE &quot;spree_products&quot;.&quot;id&quot; = 3307

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=55ee9a8c269fec0f35d728d7)
## Stacktrace

```
gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=55ee9a8c269fec0f35d728d7)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(artichoke-globe) already exists.
: UPDATE &quot;spree_products&quot; SET &quot;name&quot; = &#x27;Artichoke- Globe&#x27;, &quot;permalink&quot; = &#x27;artichoke-globe&#x27;, &quot;variant_unit_name&quot; = &#x27;each&#x27;, &quot;group_buy&quot; = &#x27;t&#x27;, &quot;available_on&quot; = &#x27;2014-08-16 14:00:00.000000&#x27;, &quot;shipping_category_id&quot; = 3, &quot;meta_keywords&quot; = &#x27;&#x27;, &quot;meta_description&quot; = &#x27;&#x27;, &quot;notes&quot; = &#x27;The price will vary based on the size of the Artichokes. Pricing based on Min order 1 box of 16 Artichokes &#x27;, &quot;updated_at&quot; = &#x27;2015-09-12 06:19:58.722920&#x27; WHERE &quot;spree_products&quot;.&quot;id&quot; = 830

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=55f3c415114b56485a97755f)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=55f3c415114b56485a97755f)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **spree/admin/products#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;permalink_idx_unique&quot;
DETAIL:  Key (permalink)=(lemons) already exists.
: UPDATE &quot;spree_products&quot; SET &quot;permalink&quot; = &#x27;lemons&#x27;, &quot;available_on&quot; = &#x27;2015-04-15 14:00:00.000000&#x27;, &quot;updated_at&quot; = &#x27;2015-09-16 03:19:50.684025&#x27; WHERE &quot;spree_products&quot;.&quot;id&quot; = 2971

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=55f8dfd174f5f85f3c14c4e5)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=55f8dfd174f5f85f3c14c4e5)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **admin/customers#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;index_customers_on_enterprise_id_and_code&quot;
DETAIL:  Key (enterprise_id, code)=(153, ) already exists.
: UPDATE &quot;customers&quot; SET &quot;code&quot; = &#x27;&#x27;, &quot;updated_at&quot; = &#x27;2015-10-08 02:54:07.773786&#x27; WHERE &quot;customers&quot;.&quot;id&quot; = 2204

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=5615dab05a43e2ac64081ae0)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=5615dab05a43e2ac64081ae0)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **admin/customers#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;index_customers_on_enterprise_id_and_code&quot;
DETAIL:  Key (enterprise_id, code)=(153, ) already exists.
: UPDATE &quot;customers&quot; SET &quot;code&quot; = &#x27;&#x27;, &quot;updated_at&quot; = &#x27;2015-10-19 04:48:28.795144&#x27; WHERE &quot;customers&quot;.&quot;id&quot; = 688

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=562475f13a5d1d620566ce02)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=562475f13a5d1d620566ce02)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **admin/customers#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;index_customers_on_enterprise_id_and_code&quot;
DETAIL:  Key (enterprise_id, code)=(153, ) already exists.
: UPDATE &quot;customers&quot; SET &quot;code&quot; = &#x27;&#x27;, &quot;updated_at&quot; = &#x27;2015-10-22 04:18:27.806930&#x27; WHERE &quot;customers&quot;.&quot;id&quot; = 2421

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=56286364f04bc30656158175)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=56286364f04bc30656158175)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **admin/customers#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;index_customers_on_enterprise_id_and_code&quot;
DETAIL:  Key (enterprise_id, code)=(153, ) already exists.
: UPDATE &quot;customers&quot; SET &quot;code&quot; = &#x27;&#x27;, &quot;updated_at&quot; = &#x27;2015-11-03 00:26:10.297692&#x27; WHERE &quot;customers&quot;.&quot;id&quot; = 2204

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=5637fee5f87e398a2379c90f)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=5637fee5f87e398a2379c90f)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **admin/customers#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;index_customers_on_enterprise_id_and_code&quot;
DETAIL:  Key (enterprise_id, code)=(153, ) already exists.
: UPDATE &quot;customers&quot; SET &quot;code&quot; = &#x27;&#x27;, &quot;updated_at&quot; = &#x27;2015-11-04 01:54:59.970236&#x27; WHERE &quot;customers&quot;.&quot;id&quot; = 1269

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=56396535568422654d043238)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=56396535568422654d043238)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **admin/customers#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;index_customers_on_enterprise_id_and_code&quot;
DETAIL:  Key (enterprise_id, code)=(153, ) already exists.
: UPDATE &quot;customers&quot; SET &quot;code&quot; = &#x27;&#x27;, &quot;updated_at&quot; = &#x27;2015-11-12 02:37:48.285271&#x27; WHERE &quot;customers&quot;.&quot;id&quot; = 2485

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=5643fb343454639b12f1934a)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=5643fb343454639b12f1934a)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**ActiveRecord::RecordNotUnique** in **admin/customers#update**
PG::Error: ERROR:  duplicate key value violates unique constraint &quot;index_customers_on_enterprise_id_and_code&quot;
DETAIL:  Key (enterprise_id, code)=(153, ) already exists.
: UPDATE &quot;customers&quot; SET &quot;code&quot; = &#x27;&#x27;, &quot;updated_at&quot; = &#x27;2015-11-16 01:30:16.285051&#x27; WHERE &quot;customers&quot;.&quot;id&quot; = 1269

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=5649315c74f21de65f2e674b)

## Stacktrace

    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:671 - block in exec_delete

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/550f7020cf825b739dab87bb?event_id=5649315c74f21de65f2e674b)

**Comment by RachL** [comment]
@mkllnk do you feel this should be moved to the bug backlog?

**Comment by mkllnk** [comment]
No, I'll just close it.
