### ISSUE TITLE
Release v3.5.2 Sourdough

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6670]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Draft new release] https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v3.5.2
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2072
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Run the query for https://github.com/openfoodfoundation/openfoodnetwork/issues/6527 on core-instances and warn non core instances about it
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by filipefurtad0** [comment]
Since #6682 is now closed - thanks @Matt-Yorkley for the quick fix! - and #6534 still has some issues I guess we can move this to Test-ready and test the release. Please let me know if you feel otherwise - ping @andrewpbrett .

**Comment by filipefurtad0** [comment]
Please notice that I'm using the build `https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2072` to test the release, which includes @Matt-Yorkley fix of subs - PR #6684.

**Comment by filipefurtad0** [comment]
Good to go!! :tada: 
https://docs.google.com/document/d/1m5euhE27Mqh9AP56Qr870Sjjtp1cwumPLggCYrSsM0w/edit#
