### ISSUE TITLE
Subscription emails (placement and confirmation) not arriving in master

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6682]
## Description

Subscription placement and confirmation emails (usually sent to the Hub only) are not arriving. Orders and payments come through, correctly. Noticed while testing #6534, but not introduced by this PR, but rather sometime between the last release and current master. Maybe introduced by #6634? ping @Matt-Yorkley 

## Expected Behavior

Four emails should arrive, when successfully placing subscriptions, see:
 

## Actual Behaviour

Only order confirmation emails are arriving, 

## Steps to Reproduce

As a customer on /account#/cards:
1. Set up the card `4000003800000446 | This card requires authentication for one-time and other on-session payments`..
2. grant authorization to a given hub

As the Hub:
3. set up an OC to open at a future time, and the respective schedule
4. set stock, and the subscription details

On the server terminal, under ~/apps/openfoodnetwork/current$
5. Run `bundle exec rake ofn:subs:test:repeat_placement_job' -> this triggers:

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6001975bdd25d30017352930?event_id=6001975b00670c434b6f0000&i=sk&m=nw

6. Afterwards running `bundle exec rake ofn:subs:test:force_confirmation_job` -> this triggers:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60019a41417f170017e75e43?event_id=60019a4100661fe952000000&i=sk&m=nw

## Workaround

No workaround, the emails don't arrive to the Hub.

## Severity

I think this might be a release blocker?
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v3.5.1
* Browser name and version: Firefox 84
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by andrewpbrett** [comment]
It's puzzling to me that this is happening in master, so I'd like to figure out why; I was able to reproduce the issue locally and fix it with https://github.com/openfoodfoundation/openfoodnetwork/pull/6534/commits/9c75a232cd0c2bed85827bc55bcdc91001e30620 (@filipefurtad0 should confirm, however).

**Comment by Matt-Yorkley** [comment]
@andrewpbrett are we planning to get #6534 into this release? Or should we submit that commit to master?

**Comment by andrewpbrett** [comment]
I think there's a good chance it'll make it in. The emails thing was the only thing blocking it; @filipefurtad0 found another issue that needs feedback but I don't think it'd be a blocker.

**Comment by Matt-Yorkley** [comment]
I made a quick two-line-PR for master, it shouldn't conflict with the other PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/6684
