### ISSUE TITLE
Search in /shops not identifying all open/closed shopfronts by County (State)

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#6689]
## Description

Customer is looking for a OFN shopfront in Kent. 
Searching in /shops returns only those OFN enterprises (with shop fronts) in Kent with 'Kent' in the enterprise name.

## Expected Behavior

Customer visits /shops and searches for an enterprise with a shop front (open or closed) using county.
ie. they search using the keyword 'A' where 'A' = County (State) found in Enterprise address settings.

Search returns all shops/hubs within that county, irrespective of name.  (Search will also return all shops/hubs with the county in their name, even if their address is not within the county)
ie. Search returns all enterprises with shopfronts with Enterprise Settings -> Address County = A
AND all enterprises with Enterprise name contains the word 'A'

## Actual Behaviour

Customer visits /shops and searches for an enterprise with a shop front (open or closed) using county.
Search returns **some but not all** shops/hubs within that county, irrespective of name.  

## Steps to Reproduce

Scenario One: Kent
1. Visit /shops
2. Search 'Kent' 
3. View open and closed shop fronts. List includes Kent food hub Ashford, Kent Food hub Folkestone, Kent Food hubs Pantry, RESTOCK Kent, Kent Cider Co., Kent Food Hubs Whitstable, Kent Food Hubs Dover, Kent Sail Cargo, Kent Faversham, The Kent Seaweed Company
4. List does not include Goody Ales, Cocktail in a Bottle, Less Travelled Lamb, .... (and a number of other shop fronts which have an address of 'Kent' as the county but do not contain 'Kent' in the enterprise name.

Scenario Two: Cornwall
1. Visit /shops
2. Search 'Cornwall'
3. List includes Cusgarne Organic Farm Shop, Kehelland Trust Food Hub, Helston Local Food Hub
4. List does not include Tamar Valley Food Hubs (and others with 'Cornwall' as county).

Images taken at the same time (one after the other)
![cornwallone](https://user-images.githubusercontent.com/45104035/104906495-b0621700-597b-11eb-9f34-afb75a892290.jpg)
![cornwalltwo](https://user-images.githubusercontent.com/45104035/104906497-b0faad80-597b-11eb-8cfe-5f55fe51a1f9.jpg)

## Severity

S2 on advice of @RachL 

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

tested with Chrome and Edge

**Comment by RachL** [comment]
Heads up, as discussed in delivery train meeting, we are going to time box our work on this one: if it turns out this is something that was happening for quite some time and we just haven't seen it, it won't be tackled as an s2 for now as we have too much going on. Instead we would just document the error correctly so we know what we are dealing with.

**Comment by Matt-Yorkley** [comment]
I had a quick look. It's a bit jumbled and pretty difficult to debug. It obviously needs some work, but I agree it should be s3 for now.

**Comment by kirstenalarsen** [comment]
If this is an S3 and has no country label on it, it shouldn't be in S3 Bugs prioritised should it? It should be in all the things . . @RachL @lin-d-hop @jaycmb ? I'm moving it there for now :)
