### ISSUE TITLE
For group buy products, Max value not showing if I proceed through checkout then return to shopfront.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#669]
In production, if a product is group buy and I enter a Max and Min value.... then I go to the 'edit my cart' page, and then I return to the shopfront.... the Min value is still shown, but the Max value has isn't displayed.

If I don't enter in another Max value, my order still caries the original one. If I enter another Max value, it overrides the initial one.

**Comment by RohanM** [comment]
This was fixed in f3ae812, which is included in v1.2 release.

**Comment by RohanM** [comment]
Actually, the code in f3ae812 is a fix for a different bug. This issue is still outstanding.

**Comment by RohanM** [comment]
New fix in 037c524, preserve-max-quantity branch.

**Comment by myriamboure** [comment]
Awesome, thank you @RohanM :-)

**Comment by myriamboure** [comment]
@RohanM has it been merged already? We tested with the latest master branch and we are still losing the max values. Can you tell us when this should be merged? Thanks :-)

**Comment by sstead** [comment]
This is now in Aus production.
