### ISSUE TITLE
Calculating customer balance

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#6697]
## What is the problem we are solving 

This aims to solve the regression experienced in [v3.3.1](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v3.3.1). While we are at it, we also want to ensure balances are consistently calculated across various areas of the app.

This started in https://github.com/openfoodfoundation/openfoodnetwork/pull/6366.

## Success factors = expected outcome 

Hubs and individual users should be able to check balances in a reasonable time-span. We currently heard about hubs not being able to access /admin/customers because it takes forever to load.

We should greatly reduce p90 of the involved endpoints (some more than others).

**Comment by RachL** [comment]
From our chat with @sauloperez today here is the release / roll-out plan for this work:

- Next release (February 23rd): the last bit of dev work is released and activated for FR
- March 2nd : all instances get their toggl switch on. Meaning the new code is available everywhere and we can switch off easily if we've missed a bug.
- If no issues, we remove the toggle and the old code completely with the release scheduled for March 16th. It means 2 weeks to properly check balances. 

How does that sound @openfoodfoundation/train-drivers-product-owners

**Comment by jaycmb** [comment]
Sounds good to me!

**Comment by RachL** [comment]
As talked through in delivery circle this morning: we are closing this epic! The remaining PR is not linked to customer balances.

What @sauloperez  must be doing behind his screen:

![ ](https://media.giphy.com/media/zd9wcDX4H4z4I/giphy.gif)

Well done :)

**Comment by sauloperez** [comment]
Absolutely @RachL !
