### ISSUE TITLE
Switch from Unicorn to Puma

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6712]
### What we should change and why (this is tech debt)

We haven't made a solid decision on this yet, but it's an option we can investigate. Switching to Puma might give us a bit of a performance boost, and it seems like it's better integrated with Rails 5+. It's probably a good idea in the medium term.

### Context

Discussion in slack.

### Impact and timeline

.

**Comment by sauloperez** [comment]
My hypothesis: given how much slow IO there's in our app, having the app server processing requests while waiting for IO can have a positive impact. As it'll be able to process more concurrent requests I bet it'll lead to shorter request queuing at Nginx level, thus shorter response times.

**Comment by Matt-Yorkley** [comment]
I did a quick experiment with this. I think we can do it, but the transition would have to be managed really carefully (with changes in the both main repos) and might require a small bit of downtime.

**Comment by sauloperez** [comment]
Sure. It shouldn't be too much work. Only investigating what needs to be done to have zero-downtime deployments (I bet nothing too different). The rest will be quite similar.

Did you think about unicorn-killer? Looks like it should be avoided but there's a https://github.com/schneems/puma_worker_killer.

**Comment by Matt-Yorkley** [comment]
> puma-worker-killer

Yeah I think we might not need it.
