### ISSUE TITLE
Add SKU field to Inventory (On Hand) and All Products reports

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#672]
(FC) Currently none of the product related reports appear to include an SKU column. We were hoping to utilise product codes to join our many different systems together, but without a report that shows those codes, there's no reason to enter them all. Am i missing something, and if not, then here's my wishlist for the inclusion of SKU's in either the Inventory (On Hand) or the All Products reports. Will think more about which one is better soon.

**Comment by RachL** [comment]
SKU is present on all product reports except LettuceShare, so I'm closing this. If I missunderstood something feel free to re-open @kirstenalarsen (but I guess with the current process it would go under discourse).
