### ISSUE TITLE
Saving stock changes in inventory is failing

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6727]
## Description

In FR prod hub 1212 cannot save their changes in inventory. 

They are trying to change stock info for producer 1718 and producer 723.

For producer 1718, the product `Panier de légumes 10 € `needs to have a stock of 20.

For producer 723:
- the product `Boudin noir (17.50 €/Kg)` nees to have a stock of 20.
- the product `Côte dans l'échine (13,10 le kg) `needs to have a stock of 15.
- the product `Rôti dans l'échine` needs to have a stock of 4.

## Steps to Reproduce
1. Go to `/admin/inventory` for hub 1212
2. Try to update the above products - even one by one
3. See error message

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/105636717-e1ee4d00-5e69-11eb-8113-c7a50e15cfa7.png)

## Workaround
I've tried to change the permissions, so that the hub has "everything" of producer 1718, but it does not change anything. Same if I try as a super admin.

I did not change any permissions on producer 723

This hub cannot use the product catalog because another hub is selling those products through product catalog.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

I'm labeling it s1 because those products are sold by other hubs. So the hub is a bit stuck? 

## Your Environment

* Version used: v3.5.5
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment]
Might be linked to https://github.com/openfoodfoundation/openfoodnetwork/issues/6386

**Comment by RachL** [comment]
The hub has decided to delay it's opening to tomorrow (Monday 25th) 6:30pm. I hope spleeping on it will give me an idea... :sweat_smile:

**Comment by sauloperez** [comment]
This is the request that @RachL did using a manager she set up for this hub:

```curl
curl 'https://coopcircuits.fr/admin/variant_overrides/bulk_update' -H 'origin: https://coopcircuits.fr' -H 'accept-encoding: gzip, deflate, br' -H 'x-csrf-token: xxx' -H 'accept-language: en,fr-FR;q=0.9,fr;q=0.8,en-US;q=0.7' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3672.0 Safari/537.36' -H 'content-type: application/json;charset=UTF-8' -H 'accept: application/json, text/javascript, */*' -H 'referer: https://coopcircuits.fr/admin/inventory' -H 'authority: coopcircuits.fr' -H 'cookie: xxx' --data-binary '{"variant_overrides":[{"id":5301,"variant_id":28723,"hub_id":1212,"count_on_hand":"20"}]}' --compressed
```

following `Admin::VariantOverridesController#bulk_update`'s code, it's clear that the line that causes the response to be a 401 is https://github.com/openfoodfoundation/openfoodnetwork/blob/10a60b1f72318431fd0838c853ef5cc3bad4326d/app/controllers/admin/variant_overrides_controller.rb#L16, which very likely ends up checking https://github.com/openfoodfoundation/openfoodnetwork/blob/10a60b1f72318431fd0838c853ef5cc3bad4326d/app/models/spree/ability.rb#L199-L211.

A bit of debugging from the console made it clear that the supplier enterprises the hub can have variant overrides for doesn't match an overrides supplier. That is, the hub has `EnterpriseRelationships` with `[194, 202, 203, 204, 205, 207, 208, 209, 240, 387, 516, 723, 736, 887, 948, 1224, 1235, 1661, 1717, 1718, 1768, 1769, 1934, 1981, 1982, 2081, 2137, 2276, 2277, 2335]` but wanting to have variant override for a variant that is supplied by enterprise `1334`.

Checking in the DB

```sql
SELECT *
FROM enterprise_relationships
INNER JOIN "enterprise_relationship_permissions"
  ON "enterprise_relationship_permissions"."enterprise_relationship_id" = "enterprise_relationships"."id"
WHERE child_id = 1212
  ADN enterprise_relationship_permissions.name = 'create_variant_overrides';
  id  | parent_id | child_id |  id   | enterprise_relationship_id |           name           
------+-----------+----------+-------+----------------------------+--------------------------
 8504 |      2081 |     1212 | 16019 |                       8504 | create_variant_overrides
 8660 |      2137 |     1212 | 16317 |                       8660 | create_variant_overrides
 5563 |       240 |     1212 | 10249 |                       5563 | create_variant_overrides
 5564 |       387 |     1212 | 10251 |                       5564 | create_variant_overrides
 5565 |       203 |     1212 | 10253 |                       5565 | create_variant_overrides
 5566 |       209 |     1212 | 10255 |                       5566 | create_variant_overrides
 5567 |       516 |     1212 | 10257 |                       5567 | create_variant_overrides
 5568 |       204 |     1212 | 10259 |                       5568 | create_variant_overrides
 5569 |       202 |     1212 | 10261 |                       5569 | create_variant_overrides
 5570 |       205 |     1212 | 10263 |                       5570 | create_variant_overrides
 5572 |       723 |     1212 | 10267 |                       5572 | create_variant_overrides
 5574 |       194 |     1212 | 10271 |                       5574 | create_variant_overrides
 5577 |       208 |     1212 | 10277 |                       5577 | create_variant_overrides
 5579 |       736 |     1212 | 10281 |                       5579 | create_variant_overrides
 5580 |       887 |     1212 | 10283 |                       5580 | create_variant_overrides
 5583 |       948 |     1212 | 10289 |                       5583 | create_variant_overrides
 5584 |       207 |     1212 | 10291 |                       5584 | create_variant_overrides
 5619 |      1224 |     1212 | 10353 |                       5619 | create_variant_overrides
 5665 |      1235 |     1212 | 10435 |                       5665 | create_variant_overrides
 9342 |      2277 |     1212 | 17504 |                       9342 | create_variant_overrides
 9452 |      2276 |     1212 | 17718 |                       9452 | create_variant_overrides
 9567 |      2335 |     1212 | 17914 |                       9567 | create_variant_overrides
 9818 |      1718 |     1212 | 18269 |                       9818 | create_variant_overrides
 6940 |      1661 |     1212 | 13057 |                       6940 | create_variant_overrides
 6988 |      1717 |     1212 | 13175 |                       6988 | create_variant_overrides
 7062 |      1768 |     1212 | 13336 |                       7062 | create_variant_overrides
 7063 |      1769 |     1212 | 13338 |                       7063 | create_variant_overrides
 7621 |      1934 |     1212 | 14468 |                       7621 | create_variant_overrides
 7811 |      1981 |     1212 | 14864 |                       7811 | create_variant_overrides
 7812 |      1982 |     1212 | 14866 |                       7812 | create_variant_overrides
(30 rows)
```

We can confirm that hub 1212 doesn't have permission to `create_variant_overrides` with supplier 1334.

What makes it hard is that we do authorize every single override created by that hub even though we only update one and that one might be valid. It's like when a single inconsistent variant breaks an entire report.

**Comment by RachL** [comment]
1334 is a test enterprise of mine. I should not come in the mix? I was trying to update a variant for 1718. So permissions are correct for 1718...

**Comment by RachL** [comment]
Ok I understand now.

Because we can't delete product that have been ordered: https://github.com/openfoodfoundation/openfoodnetwork/issues/5942 (I didn't know this issue was closed... so I guess I'm going to re-open it....) 

I changed the owner of some products hub 1212 had access to - to my enterprise 1334.

So this is breaking inventory. I just added a permission from 1334 to 1212 and saving inventory works again. But the hub has again access to product they didn't want to see anymore... Even worse because I've used 1334 as a dumpster of product-to-be-deleted 😱 

@openfoodfoundation/train-drivers-product-owners So this issue is still relevant: the product that have changed owner, should not be checked in permissions. I'm unsure of the severity though. Any thoughts?

**Comment by sauloperez** [comment]
:see_no_evil: :see_no_evil: :see_no_evil:

**Comment by sauloperez** [comment]
We had an insightful call with @RachL and trying hard not to get lost in the various interrelated issues we have here, we concluded:

a) The inconsistency comes from the fact that the VO's underlying product changed its supplier to one the hub has no permissions with so that the hub is no longer authorized to read or update it.
b) We need to ONLY authorize the VOs updated in the UI and not all the hub's VOs as we do know. This will fix this issue in 99% of the cases. It'll just blow up when the VO belongs to a supplier the hub has no permissions. And that's useful already as we'll know that's the actual VO that is inconsistent and needs fixing. It'll then become a 5min task whereas, we spend 1h finding it among all the others.
c) To fix the underlying data inconsistency issue, we need to deal with any VOs that may be associated with a product when changing that product's supplier. We agreed that ideally, we should still show those in /admin/inventory but somehow greyed out and noting that it's no longer available. That probably requires efforts that soon become wasted due to the network feature. A quicker solution is to simply remove these stale VOs as they aren't valid anymore.

So, I'll start with b) and we'll create an issue for c) and discuss it with the rest of the product team.

**Comment by Matt-Yorkley** [comment]
Great investigation :clap:

> the VO's underlying product changed its supplier to one the hub has no permissions with

:see_no_evil:

**Comment by sauloperez** [comment]
I bet there are many cases likes this one across the entire app...
