### ISSUE TITLE
As an enterprise manager, I can use a date range picker

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#6730]
## Description

**- As a:** Enterprise user and super admin

**- On page:** 
 - `/admin/reports` on each reports filters
 - `/admin/orders?q[s]=completed_at+desc` in start / end date filters
 - `/admin/orders/bulk_management` in start / end date filters
 - `/admin/subscriptions/` when creating or editing a new subscription

**- I want to be able to do:** 
Have a date(time)-range-picker to select start/end date using our new date picker (thanks to #6664). 
See example here: https://flatpickr.js.org/examples/#range-calendar

## Acceptance Criteria & Tests
_Scenario 1 As a simple producer_
We need to make sure selecting date ranges ends up with correct results on all the following pages:
 - `/admin/reports` on each reports filters
 - `/admin/orders?q[s]=completed_at+desc` in start / end date filters
 - `/admin/orders/bulk_management` in start / end date filters
 - `/admin/subscriptions/` when creating or editing a new subscription

_Scenario 2 As a multi-producer hub_
Repeat same tests as scenario 1

_Scenario 3 As a super admin_
Repeat same tests as scenario 2

## Previous discussions
See https://github.com/openfoodfoundation/openfoodnetwork/issues/6664#issuecomment-760964353

**Comment by RachL** [comment]
@jibees is this one suppose to be still open?

**Comment by jibees** [comment]
Currently, to select date range we use two inputs: one for the start date, the second one for the end date of the range.
Flatpickr allows us to use one widget to get date range: https://flatpickr.js.org/examples/#range-calendar

This issue proposes to use the Flatpickr feature and have only one input for date range.

**Comment by RachL** [comment]
@jibees ah yes now I remember! Do you think this could be a good-first-issue?

**Comment by jibees** [comment]
I think it could!

**Comment by KombiCode** [comment]
Hello. I did the one with the Close button before and now I start working on this one 😅

**Comment by KombiCode** [comment]
Hello. Just a quick update on this.
I was busy with several other things last week, so just managed to work a bit on it and below is an overview of how the range date picker would like in Orders : 

<img width="688" alt="Capture d’écran 2021-11-15 à 09 58 22" src="https://user-images.githubusercontent.com/54935392/141752431-b88d7478-6104-4d64-9ca3-d206e8bb60e1.png">

Hope to have more time this week to focus on this !

**Comment by KombiCode** [comment]
Hello. Another quick update :
I've almost finished it for orders and bulk orders management
I'm currently looking to subscriptions (which is less obvious)
Then I'll look to reports

**Comment by KombiCode** [comment]
Hi there. I didn't find time those days to work on it.
I'm very busy those weeks and will come back to that when possible, sorry for the delay.
Let me know if this is a problem...

**Comment by RachL** [comment]
Hello @KombiCode Just checking in: are you still planning to find some time in the coming weeks? Thanks :)

**Comment by KombiCode** [comment]
Hello @RachL. I hope to find few hours between Christmas and New Year's Day to continue on this, and also hope to spent few days early weeks of January. Maybe I'll need some technical tips on Angular to achieve the issue as I'm not an Angular specialist 😅. And in case it turns that I cannot find time, I'll let you know.

**Comment by RachL** [comment]
@sigmundpetersen yeah it's a bit of a mess, but I notice it's hard for new contributors to do PR closing issues from another repo. So I leave all good first issues here. I've added the papercut label :+1:

**Comment by muthumcr77** [comment]
Hello. I'm new to OFN. Can I work on this?

**Comment by drummer83** [comment]
Hi @muthumcr77, welcome! 🎉
Great to have you here!

It seems that @jibees has been working on this already (https://github.com/openfoodfoundation/openfoodnetwork/pull/9526).

Maybe it's better to pick something else?

In csse of any questions feel free to drop us a line on our [Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-1f9wxglo5-aj6s5pTnDxxBTD9~KVU9Pw)!

**Comment by muthumcr77** [comment]
Hi @drummer83,
Sure. Happy to know someone is working on it. I will look into other interesting issues.

Thank you for the reply!
