### ISSUE TITLE
follow-up specs on "Fix customer balance n+1" #6366

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6731]
### What we should change and why (this is tech debt)

This epic gathers two missing test cases on the specs, which were covered manually during testing of #6366:

- adding new payments: adding new payments on the payments section of the order
- partial refunds on paid orders (balance = 0): adding/removing some items, or a line item -> the order turns to the "balance due" / "credit owed", respectively. 

### Context

@sauloperez suggested to add theses specs here:
https://github.com/openfoodfoundation/openfoodnetwork/pull/6366#issuecomment-759336421

**Comment by Matt-Yorkley** [comment]
We could theoretically add automated regression tests for N+1s in key areas of the app with this EvilMartians gem: https://evilmartians.com/chronicles/squash-n-plus-one-queries-early-with-n-plus-one-control-test-matchers-for-ruby-and-rails

**Comment by sauloperez** [comment]
I haven't checked but in the past, existing solutions seemed to address partially or cause false negatives. It's indeed something that would align with our metrics-driven approach to performance. I'd be happy to dig deeper.

**Comment by filipefurtad0** [comment]
Nice! Indeed this one is quite old, and can be closed.

Thanks so much for that suggestion @sigmundpetersen, that's a great idea! Opened an issue [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/12088) :pray:  

Note to self: I see I need to keep better track of the epics I've opened... :see_no_evil:
