### ISSUE TITLE
un-checking "Enable mail delivery" not disabling email delivery

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6738]
## Description

Noticed while testing #6537: un-checking "Enable mail delivery" is currently not disabling email delivery.

## Expected Behavior

Un-checking "Enable mail delivery" should disable email delivery.

## Actual Behaviour

Un-checking "Enable mail delivery" is not disabling email delivery. Ticking it should re-enable mail delivery.

## Steps to Reproduce

1. Log in as superadmin.
2. Go to email settings.
3. Check/un-check the "Enable mail delivery" checkbox. Click "Update".
4. Trigger some emails: see how emails are working still.

## Workaround

-

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.4.5
* Browser name and version: Firefox 84
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by Matt-Yorkley** [comment]
I think we've updated this now and it works lightly differently. Anyway, disabling email delivery isn't a feature we need to support.
