### ISSUE TITLE
Customers not showing in customer list

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#6743]
## Description
When a customer places an order in a shop,  they should be placed into the shop's customer list.  This happens for guests as well as registered customers.  We have at least one shop where this is not happening.   It warrants investigation -  in case it is a more extensive problem.

At present -  I only know of one shop with this problem -  its the shop we use to sell OFN-Canada SAAS subscriptions.  It means that we can't easily monitor customers and their balances using the customer list.  At this point - I'm not aware of other situations where this bug is occuring.

## Expected Behavior
Customer places an order (as either a guest or a registered user).  Their email, name, address appear in the shop's customer list,  along with their account balance.

## Actual Behaviour
Some customers who placed orders in this shop appear in the customer list.  Others do not.  I have been unable to find any pattern to this.

Shop is public, allows guest checkout,   and placed orders cannot be changed/cancelled
Shop is open on OFN-CAN -  called OFN Services  - enterprise ID  1628

Look at the orders  -   3 customers  placed orders but are missing on the customer list page:  My test order is from  'tschumilas+placingfirstorder@gmail.com (guest) R888152421 ,  and customers placing  R033475684  and R415521461 are not on the customer list.  

These orders appear in reports,  and the customers appear in the enterprise's customer report.

Just to test this again -  I just placed 2 more orders in this shop.  A second order  with the same tschumilas+placing firstorder@gmail guest login above ( R727437383)  And an using a differnt registered user email -  tschumilas@rogers.com (order R410222152).  Both are in the orders list and in reports.   Neither customer shows in the customer list.

## Steps to Reproduce
Place an order in the above shop. https://openfoodnetwork.ca/ofn-services/shop#/shop
See the order on the  order list. https://openfoodnetwork.ca/admin/orders?q%5Bs%5D=completed_at+desc
See the customer does not appear in the shop customer list https://openfoodnetwork.ca/admin/customers

1.
2.
3.
4.

## Workaround
Customer list is available in reports.

## Severity
This is an s3 -  but it would be good to try to figure out what the problem is -  is it affecting others users and we don't know about it?

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by filipefurtad0** [comment]
This looks closely related to #6038.

**Comment by lin-d-hop** [comment]
CLosing this one as it seems its an edge case and old edge cases are so hard to track down.
