### ISSUE TITLE
Increase capacity of our CI service

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#6752]
### What we should change and why (this is tech debt)

Not only our CI service is very old, rather limited in terms of features, and soon discontinued (it was already outlined in https://github.com/openfoodfoundation/openfoodnetwork/issues/4435) but we've also been experiencing serious resource contention issues lately. According to Semaphore itself

> developers have spent over 103 hours waiting for CI resources during the week of January 4, 2021.

I think the combination of Dependabots PRs and the need to retry jobs N times due to the test suite's flakiness are the root cause of this.

We initially thought it's worth spending money on this (we're still running on Rob's free account) but given that we've got a free GH account trying out Github Actions might solve it for free (I've personally adopted it successfully for other projects).

Alternatively, we could investigate migrating to Semaphore CI v2 (we have an account already) and pay if needed.

### Context

This was briefly discussed in the last delivery train meeting, and there was a shared agreement that this has become a problem.

### Impact and timeline

Having an up-to-date CI service should reduce the time it takes to get PRs to test ready, and enable new potential automation.

**Comment by sauloperez** [comment]
I'm noticing an increasing amount of `Net::ReadTimeout` errors in the build, such as https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-6774/builds/2. This slows builds even more and the retries increase the queue even more.

**Comment by sauloperez** [comment]
We need to undo https://github.com/openfoodfoundation/openfoodnetwork/issues/6840 as soon as we get to a stable build elsewhere other than Semaphore.

**Comment by sauloperez** [comment]
Insights so far after the initial configuration done in #6902 

* We managed to get all the different kinds of tests working without surprises. Capybara and JS tests run successfully.
*

**Comment by Matt-Yorkley** [comment]
We can run them both, right? So we could trigger these new Github CI builds alongside the current Semaphore builds (temporarily) with no problems, and then remove the Semaphore builds at a later date.

We've got nothing to lose, lets try it :+1:

**Comment by sauloperez** [comment]
yep, we're totally aligned!

**Comment by mkllnk** [comment]
I've been using Semaphore 2 lately and while it works much better than Semaphore Classic, it can be quite expensive. So if we get all this stuff for free with Github Actions, let's go for it. We can still use Semaphore for deployments while we are working on a better solution.

**Comment by RachL** [comment]
@andrewpbrett As per our delivery-train decision, I'm assigning you here as well so you can help Pau on this one :)

**Comment by andrewpbrett** [comment]
Re: https://github.com/openfoodfoundation/openfoodnetwork/pull/6902#issuecomment-795267879 - I just double checked the math (and added in the engines specs, which report their counts separately) and I got 4486 examples, 25 pending on both Github and Semaphore. I think we can confidently say we're running all specs on both.

Since we want to keep Semaphore going for the time being in order to do deploys, I propose that we strip the config down to just run, say, the javascript and model specs in a single job. Then we'll have up to four concurrent builds going and should never be waiting on Semaphore since Github will take longer to complete. 

@openfoodfoundation/core-devs: If you're good with that proposal, add a 👍 to this comment. If everyone is good with it, we can go ahead and reconfigure Semaphore (and I think close this issue).

**Comment by andrewpbrett** [comment]
One thing we could also do is rebalance the jobs; the admin-feature-folders (~6min) one could get shifted to another one and the admin-features (~20min) split in two, for example.

**Comment by sauloperez** [comment]
> Or maybe set up knapsack?

I would personally wait after rebalancing jobs manually as you suggest and see if they get out of balance. If so, we might need to consider Knapsack Pro so we don't add another manual operation to remind ourselves of. But it may not happen that often and we can avoid that extra piece.

**Comment by mkllnk** [comment]
> I propose that we strip the config down to just run, say, the javascript and model specs in a single job.

I think that we shouldn't run any specs twice. We could still run Javascript in Semaphore and not in Github and we can remove all other specs from Semahpore. Let's not use resources unnecessarily.

**Comment by andrewpbrett** [comment]
I'm going to close this. I just updated the Semaphore config to only run javascript tests and created https://github.com/openfoodfoundation/openfoodnetwork/pull/7178 and https://github.com/openfoodfoundation/openfoodnetwork/pull/7179 which I think should be the last bits of cleanup here. I think we can say that our CI is much improved and can pause for now and revisit if it needs more attention.
