### ISSUE TITLE
Incorrect link to the order, on the cancellation Email sent to the shop 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6767]
## Description

PR #6720 introduced a notification email to the shop, when a customer cancels an orders.

However, the link on the email leads to a non-existing page.

## Expected Behavior

The link on the email should redirect the user to
`https://staging.coopcircuits.fr/admin/orders/<order_id>/edit`

## Actual Behaviour

The link on the email redirects the user to
`https://staging.coopcircuits.fr/admin/orders/<order_id>` -> which displays an error 404, to the user

## Steps to Reproduce

1. See the testing steps on #6720

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/a01dfb19-3b43-4ed9-b90e-63605a6e0d7a)

## Workaround

Look for cancelled orders or manually add `/edit` on the address bar.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: only after PR #6720 is merged or in production
* Browser name and version: Firefox 84
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by cillian** [comment]
A [fix](https://github.com/openfoodfoundation/openfoodnetwork/pull/6720/commits/0cfd7de8a8a62f6c4f2ce1197ac9ecde17ac570e) has been added to the #6720 PR now.

**Comment by filipefurtad0** [comment]
Closing here :+1:
