### ISSUE TITLE
Impossible to deleter order cycle with no  order attached even with admin rights

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#677]
I created an order cycle and I wanted to delete it just after, no order is attached. Impossible, even with admin rights. The strange thing is that then I duplicated it, and I had the option to delete the new one.
If I look at the discussion here: http://community.openfoodnetwork.org/t/clean-up-order-cycle-index-for-readability-and-faster-loading/96/2 it is supposed to be possible.

![order-cycle](https://cloud.githubusercontent.com/assets/8135376/10002448/6cf546b8-60a7-11e5-80e6-efe0620f5240.jpg)

**Comment by myriamboure** [comment]
Even more strange, among all the order cycles, I can delete 2 order cycles... I'm with admin right, but I didn't create those two order cycle.
![order-cycle2](https://cloud.githubusercontent.com/assets/8135376/10002538/f8294b12-60a7-11e5-808d-85f38e3d9a0d.jpg)

**Comment by edem228** [comment]
Hey everybody, this problem was already solved?

**Comment by myriamboure** [comment]
I don't manage to reproduce it, so I'll close the issue. I guess that was a mistake/misunderstanding from my side.
