### ISSUE TITLE
After updating stock in product admin, page is stuck on 'saving' even after the changes have been captured.

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#6777]
## Description

Producer updates stock via Product Admin page 
https://openfoodnetwork.org.uk/admin/products
After making changes, click 'Save'

If '15 per page' is selected then page remains stuck on 'Saving' 
![save15](https://user-images.githubusercontent.com/45104035/106383739-80753380-63bf-11eb-8335-4a705e3e6db1.gif)

Refresh the page and come back, changes have been captured *no loss in functionality*

If '50 per page' is selected then page moves from 'Saving' back to 'Saved' when changes have been captured.
![save50](https://user-images.githubusercontent.com/45104035/106383779-a995c400-63bf-11eb-8cd9-1678833fa324.gif)

Impact on user: confusing.

## Expected Behavior

1. make changes to stock on this page https://openfoodnetwork.org.uk/admin/products
2. click 'Save'
3. when changes have been captured screen displays 'Saved'

## Actual Behaviour

1. make changes to stock on this page https://openfoodnetwork.org.uk/admin/products
2. click 'Save'
3. when changes have been captured screen continues to show 'Saving'

## Steps to Reproduce

1. make changes to stock on this page https://openfoodnetwork.org.uk/admin/products
2. click 'Save'
3. when changes have been captured screen displays 'Saved'

## Severity

bug S4

Annoying and confusing to users only.
Might be an easy one to fix though?

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by andrewpbrett** [comment]
Closed by #6821
