### ISSUE TITLE
More admin UI improvements

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6785]

**Comment by filipefurtad0** [comment]
Hey @RachL @jibees ,
I've recently created issue #6833 while testing the release, should I assign you to it JB? I think it might be related to the recent widening of the UI so I've added it to this epic. Should we keep it here and keep the epic open, or close the epic and move the issue to all the things?

**Comment by jibees** [comment]
I don't know if you should keep this issue under this epic, but i assigned this issue to me.
