### ISSUE TITLE
white space on "Display as" row (on products/new)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6798]
## Description

A white space on "Display as" row (on products/new) was spotted when testing #6788.

## Steps to Reproduce

1. visit /admin/products/new

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/903f4088-8dca-4732-8144-e7db58647687)

Also seen on narrower windows:
![image](https://user-images.githubusercontent.com/49817236/106592833-e7bdef80-6547-11eb-9aa8-8f80c427a715.png)

and Mobile:
![Peek 2021-02-02 11-09](https://user-images.githubusercontent.com/49817236/106592285-3b7c0900-6547-11eb-89fc-df55f8046397.gif)

## Severity

s5

## Your Environment

* Version used: v3.4.6
* Browser name and version: Across browsers and devices

**Comment by RachL** [comment]
The thing is I'm not sure what to put in this white space. If the work on unit prices goes into the admin as well this space will be used.
Do we have an idea how to do it? ping @jibees

**Comment by jibees** [comment]
I'm sorry, I though I was clear when creating the PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6788#issue-565280820

Actually, there's a space after "Display as" to let the space available for "Unit Name" field as you can see here:
<img width="442" alt="106480833-1ab2a580-64ac-11eb-9120-9a37445b1b2e" src="https://user-images.githubusercontent.com/296452/106665982-46668600-65a7-11eb-97c9-fdf3c61b4e47.png">

However It should be possible to hide this space when the field is not present (can be usefull on small screen).

**Comment by filipefurtad0** [comment]
Thank you for stressing this @jibees .

While testing it, it felt like a regression to me, especially in mobile.

Also, this concerns potentially mandatory fields - realize I should have been more explicit about this, on my "description" in this issue, sorry for that.

> However It should be possible to hide this space when the field is not present (can be useful on small screen).

I totally agree with the solution you propose, if you find this feasible.

But if it is temporary and we are fine with this, we can as well choose to close this issue. What do you think @RachL @jibees ?

**Comment by RachL** [comment]
I'm a bit concern we are starting to consider mobile in the back end. If so there is a lot to take into account and I feel this space is not the main priority? But that's really only my opinion. Given you have some time @jibees I let you decide what you think is best.

Also - but this will need another issue. What stroke my eye was that the image placeholder is not centered anymore:

![image](https://user-images.githubusercontent.com/6525576/106736023-39807b80-6615-11eb-9d21-70a55e0863a4.png)

FYI, how the page looked before:

![image](https://user-images.githubusercontent.com/6525576/106736097-4f8e3c00-6615-11eb-99fe-5809765c3a7b.png)

**Comment by jibees** [comment]
> I'm a bit concerned we are starting to consider mobile in the back office. If so there is a lot to take into account and I feel this space is not the main priority? But that's really only my opinion. 

I totally agree, but let's start there, no? It should not take that long.
We need a global reflexion on how we handle mobile/small screen devices cases. I think we should be able to have such a things : https://tailwindcomponents.com/component/form-grid

**Comment by jibees** [comment]
@RachL @filipefurtad0 Sorry, I was totally confused: I thought that these two fields (`Display As` and `Unit Names`) could exist at the same time, next to each other. In fact, they are never displayed at the same time.... So sorry. 😊
