### ISSUE TITLE
Adjust report loading for super-admin so loads no info to start

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#680]
On Aus production we now have a problem that some reports are trying to load so much info that they're timing out. This is because the default when you click into each report is to load up info from the start of the month (or similar). As super-admin this can be a lot of info

Long-term the whole reports infrastructure needs rethink, but short-term fix would be:
- for super-admin only
- default reports load NO info, requiring filters to be set before it tries to load data

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/optimisations-suggestions/1176
