### ISSUE TITLE
Activate new customer balance for all FR users

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6804]
A bit crazy but at least we will have data :)

**Comment by RachL** [comment]
Yes I'm winning worse issue awrd here, but I'm still unclear on how we test this. Maybe I could pair with you @filipefurtad0 next time you test it?

**Comment by filipefurtad0** [comment]
Sure @RachL  :+1:

**Comment by sauloperez** [comment]
https://github.com/openfoodfoundation/ofn-install/pull/697#issuecomment-772665756 is relevant for this issue.
