### ISSUE TITLE
Release v3.5.7 Sobrassada

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#6818]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Draft new release]
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2151
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by filipefurtad0** [comment]
Hey @sauloperez ,

I've had issues deploying the release draft in staging-FR and-AU, opened an issue here #6828.  Does this raise concerns about deploying to production?

Deployment worked fine for staging-UK, so I'll proceed with release testing.

**Comment by filipefurtad0** [comment]
This is good to go :tada
https://docs.google.com/document/d/1EzayqGj31mfeFTtD4XiI_-Q3ld9p22XjUbgiIkNj864/edit#

Only issue #6828 needs attention :+1:

**Comment by filipefurtad0** [comment]
I just noticed this warning on the bulk order management page, and on staging-UK (after testing the release):

![image](https://user-images.githubusercontent.com/49817236/107240480-dc743380-6a21-11eb-9e93-49be583e61ad.png)

This _was_ a corrupt item, at some point, but it now looks like this: 

```
id   | sku | weight | height | width | depth | deleted_at | is_master | product_id | cost_price | position | cost_currency | unit_value |  unit_description   |  display_name   |  display_as   | import_date 
--------+-----+--------+--------+-------+-------+------------+-----------+------------+------------+----------+---------------+------------+---------------------+-----------------+---------------+-------------
235431 |     |   0.00 |        |       |       |            | f         |     214247 |            |        4 | GBP           |          0 | #unit_description_5 | #display_name_5 | #display_as_5 | 

```

So, actually, `unit_value` is not empty... I was a bit puzzled to see that warning, thought I should mention it.

The funny display on the box with the totals is related to this issue #6833.

**Comment by sauloperez** [comment]
The data migration failed in almost all instances. It got executed in AU, CA, BE, FR and ES but it only succeeded in ES. I had to cancel the deployment at this point as it was seriously affecting the system while migrating UK's instance. I'm listing the issues for each instance below:

* AU: [Data integrity issue](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1612879953047200) related to units. Needs to be somehow handled in the migration. 
* BE: [Deadlock](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1612879430045800). Hopefully deploying again at night will solve it.
* CA: [Data integrity issue](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1612879675046000) involving option values. Needs to be somehow handled in the migration.
* FR: [Deadlock](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1612880744047400). Same as BE.

We will need to address the issues related to the migration, and perhaps use plain SQL statements, skipping callbacks and then also split the deploy by continents and deploy while their users are sleeping so we don't hit any deadlocks. Could you @andrewpbrett and/or @Matt-Yorkley take a look at the migration? I'm off tomorrow morning.

**Comment by sauloperez** [comment]
For the record, I created the branch [release/v3.5.7](https://github.com/openfoodfoundation/openfoodnetwork/tree/release/v3.5.7) to include the fixes onto the initially drafted release. We should cherry-pick onto it whatever we merge to master and want to include in the release.

**Comment by sauloperez** [comment]
@andrewpbrett I had a discussion and think the best path forward is to take the migration that we're trying to fix in https://github.com/openfoodfoundation/openfoodnetwork/pull/6842 out of the release so all the other changes get deployed before drafting the next one.

Then, we'll have the necessary time to solve those migration issues properly and without any rush.

**Comment by sauloperez** [comment]
:tada: @andrewpbrett successfully managed to deploy https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v3.5.8 :clap:
