### ISSUE TITLE
Group map only showing "+1" map pointer

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6829]
## Description

Group maps are not displaying pointers when there is only 1 hub per address anymore. As a result, a lot of maps are empty.

## Steps to Reproduce

Empty group maps: https://www.coopcircuits.fr/groups/fleuve-de-liens#/map or https://openfoodnetwork.org.uk/groups/monlocalfood#/map

Map with only "+1" : https://openfoodnetwork.org.uk/groups/biodynamic-association-licensees#/map or https://openfoodnetwork.ca/groups/orillia-fairgrounds-farmers-market#/map

## Workaround
None ? The main map can be used though

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v3.5.6
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by Matt-Yorkley** [comment]
I have a feeling this could be an image asset path issue, like the markers are theoretically there, but the url to the image is not correct...

**Comment by andrewpbrett** [comment]
It seems like that commit **should** fix the issue... but I'm not seeing it work on staging. For example, I expected https://staging.openfoodnetwork.org.uk/groups/new-group-22#/map to no longer have 404 errors in the dev tools console, but it still isn't finding the assets. 

The assets are present, we're just asking for the non-fingerprinted version. E.g. https://staging.openfoodnetwork.org.uk/assets/map_005-hub-0459406eef74347f506ca49e97ccba42.svg works. But we're requesting 
https://staging.openfoodnetwork.org.uk/assets/map_005-hub.svg

**Comment by filipefurtad0** [comment]
I've noticed this issue again while testing something else. It seems we are still getting a 404 in production.
The +1 icon is missing from `/map` page - seen in production too - file `map_009-cluster.svg` not found (error 404 in the console):

![image](https://user-images.githubusercontent.com/49817236/109681940-de8b6700-7b75-11eb-817f-53b1163870bc.png)

Should we re-open this issue?

**Comment by RachL** [comment]
@filipefurtad0 I think this is a different issue? In this one we _only_ had +1 point visible, no the others. Also this issue was only on group maps, not the main /map page. But maybe I've missunderstood, in that case yes let's reopen.

**Comment by andrewpbrett** [comment]
🤦 I see what we did. Yes, technically a separate issue, but I'm fine to reopen this one. Will be a quick fix either way.

**Comment by filipefurtad0** [comment]
It seemed related to the PR #6885 which brought me back here, but yeah... Either way is good :+1:
