### ISSUE TITLE
set default no. enterprises ^ 1?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#683]

**Comment by elf-pavlik** [comment]
@kirstenalarsen could you please add a paragraph with little more explanation to description?

**Comment by kirstenalarsen** [comment]
This was a note to reconsider this down the track . . there are two cases to consider

1. Enterprise user: if a user signs up for the first time, and creates their first enterprise, they only have permission to create one. The admin / instance manager then needs to manually update that user to allow them to create more e.g. if they become a hub and want to start creating users. Automating this when someone changes their enterprise type to 'hub' would be a possibility, but at this stage in Australia we still quite like just keeping a bit of an eye on who's who - particularly as a check against both spam profile creation and people getting confused / lost and creating multiple enterprises for the same one because they're not sure what they're doing. So for this case I'd still be inclined to say leave it for now. @sstead may have a view on this as she actually handles all this for us now . . Sally would you prefer to have some case where a user is automatically allowed more enterprises?

2. 'Super-admin' user . . not sure if there is another interconnected issue somewhere, but I think when a user is made an 'admin' (either at instance provisioning or by clicking the little flag in the user) they might still only default to permission for one user.
- first 'super-admin' user: @pmackay @mkllnk @RohanM do you know if this got fixed in provisioning somewhere so that the first super-admin is set to lots of users? or it has to be done manually when setting up for the first time?
- any new super-admin user: I don't think this has been done, and could be a good task . . so anytime a user is turned onto 'admin' their no. of allowed enterprises is set to 10,000 or infinite or something . .

**Comment by elf-pavlik** [comment]
Thank you @kirstenalarsen, I think this issue needs more discussion and we will not work on it during next days in Berlin.
I suggest having social aspect discussed on community forum and to keep this github issue focused on technical requirements of how to implement the decided functionality.

**Comment by sstead** [comment]
Update: We are keen to remove the 'request permission to create >1 enterprise' measure. Can we change the setting so all users can create ?30 enterprises by default? This number is flexible... 

Points 2, 3 and 4 above could either be done or postponed and done separately.

**Comment by sstead** [comment]
Can anyone from the UK tackle this?

**Comment by myriamboure** [comment]
That's great @sstead , I vote for :-) I have a kind of regular hub in France who has already like 15 producers and 10 hubs (he handles 10 buying groups), so 30 might be a little low, threshold, why not 50? Then I would suggest to add a not on the "entreprise page" telling that "You can set up up to 50 entreprise (we set it that way to avoid spam profile creation) so if they want to create more they can write to xx@xxx" OR even better, when the limit is reached and the user can't create more entreprise, if he clicks on "new entreprise" a pop up could say "you have reached the limit of 50 entreprise set up by default to prevent spam profile creation, write to blabalbla to increase your threshold!"

**Comment by NickWeir63** [comment]
@lin-d-hop is it feasible to put this on the UK list?

**Comment by myriamboure** [comment]
So let's go for:
- set up limit to 50 by default
- when the limit is reached and the user can't create more entreprise, if he clicks on "new entreprise", he can't proceed and a pop up display and say "You have reached the limit of 50 enterprises set up by default to prevent spam profile creation, write to [default instance email] to increase your threshold!"

If any objection please raise your voice quickly !

**Comment by kirstenalarsen** [comment]
hmmmm, just a caution. This was originally done like this to prevent spam.
Given that we still don't have an easy way to get rid of enterprises that
people create, and excess enterprises clog up both the database and the
enterprises screen (to the point of extreme pain for superadmin), I would
retain caution about allowing anyone who comes along and is playing around
and not sure what they're doing to create as many enterprises as they want.
I know it's annoying to have to increase them manually, perhaps just make
it 5 or something before asking super-admin to do it? Not sure best solution

**Comment by myriamboure** [comment]
Hum... the thing is that today it make people come on OFN and leave as some think it's just not working... so why not putting a lower number, if there is the pop-up explaining about the entreprise limit... I woudl say ok we can start with 5 as when people play and modelize their case they usually don't need more, and I guess if we need to increase that it's just one figure to change somewhere in the code then ;-) So let's go for 5 !

**Comment by myriamboure** [comment]
So update for @ltrls after Kirsten's comment: for the "producer hub" and "distributor hub" package type (=those who are meant to manage multiple enterprises):

- set up limit to 50 by default
- when the limit is reached and the user can't create more entreprise, if he clicks on "new entreprise", he can't proceed and a pop up display and say "You have reached the limit of 50 enterprises set up by default to prevent spam profile creation, write to [default instance email] to increase your threshold!"

**Comment by kirstenalarsen** [comment]
5, not 50? :)

**Comment by myriamboure** [comment]
Oups, sorry, was too quick, thanks @kirstenalarsen, made the change, sorry @ltrls for the confusion, it's 5 not 50 the limit we want for now :)

**Comment by enricostano** [comment]
cc/ @sauloperez @sseerrggii
