### ISSUE TITLE
[Reports] Enterprise Fees w Tax By Order

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6845]
## Description

As a hub manager I want to be able to view report that includes a breakdown of fees including tax information by order.

This report will extend on #6844 and hence will not need additional UI navigation.

A mock of the report data in CSV form is available [here](https://docs.google.com/spreadsheets/d/1VmcaV2GFVgw-4fysnJn9QZeGbZqPOqfXJJ-GOVVbsTI/edit#gid=877250263).

- _Enterprise_: The hub for which the correlating order was placed
- _Order Cycle_: Identifier for the order cycle in which the order was placed
- _Order Number_: The OFN order identifier eg R##########
- _Name_: Enterprise fee name. Note that for this report to be maximally useful we are including the 'Produce' within this report.
This is not technically an enterprise fee. It is essentially costs that do not map to fees on the order.
- _Type_: The fee type eg Admin, Packing. Note the 'Produce' fee can have type 'Line Items'
- _Owner_: The enterprise that allocated this fee to the produce
- _Tax Category_: Self explanatory. Note that some fees 'inherit' their tax category. Also the 'Produce' will have a mixed category.
- _Tax Rate_: Self explanatory. Will not be applicable for 'inherit' and 'produce' categories.
- _Total (tax excl):_ Total cost without tax
- _Total (tax)_: Total amount of tax applied
- _Total (tax incl)_: Total including tax (eg sum of last two rows)
- _First Name_: First name of the shopper
- _Last Name_: Last name of the shopper
- _Customer Code_: Self explanatory
- _Email_: From the order

The report will be sorted by order.
Note that after each Order a row of totals will be displayed.

~~The filters for this report will be the same at #6844. The only addition required for this report will be to enable the user to select between 'By Producer' and 'By Order'~~

- ~~_By Producer/By Order_ (Dropdown): Allows user to view the report sorted by Producer or by Order~~

## Acceptance Criteria & Tests

1. All fields described above are present and data matches the description
2. Report can be downloaded as a CSV
3. Report can be accessed via the UI
4. Report can be filtered on all fields mentioned above
5. Totals row show correctly summed total amounts
6. In the UI figures should be rounded to 2 decimal places. In the CSV figures should be rounded to 6 decimal places.
7. All fields are translatable

**Comment by abdellani** [comment]
@lin-d-hop 

I want to confirm something related to filters.

>Producer (Auto-fill text) Filter to a specific producer for fee calculations
Order Cycle (Auto-fill text) Reporting by OC
Fee Name (Auto-fill text) Filter to only include specific fees eg for a specific delivery run
Fee Owner (Auto-fill text) Filter to select the Enterprise that should be collecting the fees (reconciliation)
Customer Email (Auto-fill text) Report can then be used for wholesale customers tax calculations

What does filtering by `Producer` mean?

1. listing the orders that have at least one line item made by the selected Producer
2. or do we have to remove the cost of the line items made by the other producers before rendering the report?

**Comment by lin-d-hop** [comment]
The original intention was for option 2, in line with other reports. 
However thinking this through now, if we filter the report with just line items from producers then what happens to order level fees? Including them doesn't make sense. Leaving them out gives us the same results as the 'Enterprise fees w tax by Producer' report.

So I suggest we should leave off the filter by 'Producer' on the 'by Order' report.

**Comment by kirstenalarsen** [comment]
@RachL should this be assigned to @dacook ?

**Comment by abdellani** [comment]
I already have a [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/10323) that already implements some of the work that needs to be done. It needs a rebase on [this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/10304).
 
I don't know if @dacook wants to use it or start a new PR.

**Comment by dacook** [comment]
> So I suggest we should leave off the filter by 'Producer'

I've updated the description to match this ^
