### ISSUE TITLE
[Reports] Allow user to show/hide totals with a checkbox toggle

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6846]
## Description

To increase the utility of this report we wish to enable the user to show and hide the Totals rows (as displayed in the CSV mock)

The user will have an additional checkbox filter:

- _Display Total Rows_ (Checkbox) Include total rows in display/CSV

When the box is checked, total row will be included.
When the box is not check the CSV download and the UI report will not have totals rows

This needs to be applied to both the By Producer and By Order pivots of this report.

## Acceptance Criteria & Tests

1. The Display Total Rows checkbox is included
2. When it is ticked the totals rows are display in CSV download and on UI
3. When it is not ticked the totals rows are not displayed in CSV download and on UI
4. All fields are translatable

**Comment by RachL** [comment]
@lin-d-hop do we still need this issue now that the checkbox will be standard on all reports?

**Comment by lin-d-hop** [comment]
Agree @RachL. This is now the default :)
