### ISSUE TITLE
Tax Totals with Rates by Producer Report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6848]
## Description

As a hub manager I want to be able to view report that includes a breakdown of what is paid to producers by tax rate.

A mock of the report data in CSV form is available [here](https://docs.google.com/spreadsheets/d/1VmcaV2GFVgw-4fysnJn9QZeGbZqPOqfXJJ-GOVVbsTI/edit#gid=0).

- _Enterprise_: The hub for which the correlating order was placed
- _Producer_: The producer that supplied the produce
- _Producer Tax Status_: Is the producer tax registered or not
- _Order cycle_: Identifier for the order cycle in which the order was placed
- _Tax Category_: Self explanatory.
- _Tax Rate_: Self explanatory.
- _Total (tax excl)_: Total of orders without tax
- _Total (tax):_ Total tax applied in orders
- _Total (tax incl)_: Total including tax (eg sum of last two rows)

Note that after each Producer a row of totals will be displayed.

The report will need filters to ensure that relevant data can be accessed. Also summarised [here](https://docs.google.com/spreadsheets/d/1VmcaV2GFVgw-4fysnJn9QZeGbZqPOqfXJJ-GOVVbsTI/edit#gid=731457444):

- _Date Range_ (Datepicker): Allows weekly/monthly/annual reporting
- _Distributor_ (Auto-fill text) Allows multi-enterprise hubs granularity
- _Producer_ (Auto-fill text) Filter to a specific producer for fee calculations
- _Order Cycle_ (Auto-fill text) Reporting by OC
- _Tax Rate_ (Auto-fill text) Simple totals for tax reporting
- _Customer Email_ (Auto-fill text) Report can then be used for wholesale customers tax calculations

The report should be accessible via the UI via Reports -> Sales Tax Reports -> Tax Totals with Rates
https://community.openfoodnetwork.org/uploads/default/original/2X/7/78a043e39d6619ca3307d2bec50e934f53971bfb.png

## Acceptance Criteria & Tests

1. All fields described above are present and data matches the description
2. Report can be downloaded as a CSV
3. Report can be accessed via the UI
4. Report can be filtered on all fields mentioned above
5. Totals row show correctly summed total amounts
6. In the UI figures should be rounded to 2 decimal places. In the CSV figures should be rounded to 6 decimal places.
7. All fields are translatable
[EDIT] 
8. Works with added tax and included tax systems (ie CA/US and EU/AU)
9. Correct data returned on complex order cycle configurations including multiple suppliers, multiple distributors, multiple order cycles, multiple enterprises per report render.
10. All data returned via API

**Comment by kirstenalarsen** [comment]
Can we please repeat any identifying and context information on the Totals rows when they are included, and that info makes sense in an 'aggregate' - so that when the user filters to use only the Totals rows they have the info about Enterprise, Producer etc easily to hand

**Comment by lin-d-hop** [comment]
After chatting with @kirstenalarsen on Slack my understanding is the above comment refers to outdated screenshots on discourse rather than the issues as specified here.

**Comment by Matt-Yorkley** [comment]
I've got a question...

Taxes can be applied to:
1. Line Items (each associated with a producer) 
2. Shipments
3. Enterprise Fees on Orders
4. Enterprise Fees on Line Items

I'm assuming we want to include **1** here and not include **4**, but I just thought I'd check.

**Comment by Matt-Yorkley** [comment]
But conversely; the **Tax Totals by Order** report will be quite different in that it'll include all 4 sets of taxes for each order.

**Comment by lin-d-hop** [comment]
Hey Matt, yes that is correct to my understanding too. Tis a good clarification. we might need to look closer at this in the enterprise fees report. Off the top of my head we'll be covering cases in that report for enterprise fees/tax per producer.

**Comment by abdellani** [comment]
@lin-d-hop  @RachL 

I had an instructive call with @filipefurtad0  about the taxes, and we clotured with the following questions:

Calculating the taxes for an order is composed of three steps:

1. calculate line items taxes
2. calculate shipments taxes
3. calculate enterprise fees taxes

https://github.com/openfoodfoundation/openfoodnetwork/blob/c96bba8094405a86a4eb9aeea0450fcd353e22d8/app/models/spree/order.rb#L313-L321

If the order's distributor doesn't have the GST enabled, the taxes calculation process will return 0 taxes.
https://github.com/openfoodfoundation/openfoodnetwork/blob/c96bba8094405a86a4eb9aeea0450fcd353e22d8/app/models/spree/tax_rate.rb#L31-L38

#### First question:

![image](https://user-images.githubusercontent.com/16113997/209564297-b6cdb492-aa8b-4a07-9ff9-e70190e441c0.png)

In the template, we are showing the `Producer Tax Status`. Do we use this information in the calculation of the final price of the products? if this parameter is not used anywhere in the tax calculation process, maybe we can remove it from the report.
Instead, when I read the code, I found that we're checking the `Distributor Tax Status` before calculating the taxes. 
Maybe adding the `Enterprise Tax Status` to the report will be relevant? 

#### Second question:
An order has :
- multiple line items and each line item can have multiple tax rates.
- shipment tax rates
- enterprise tax rates

I don't see how can we represent all the data in this table.
 
For example:

Suppose that we're in the context of added taxes (opposite of included taxes), we have one order in an order cycle. This order has one line item only.
The initial price is 100$ and the line item matches two tax rates: `state` and `country`. For example 2.5% for both (as in a country like India).

The final price is supposed to be 105%

If we list the Tax Categories and Tax Rates, we'll have
| Tax Category | Tax rate | Total (tax excl) | Tax  | Total (tax incl) |
|--------------|----------|------------------|------|------------------|
|country |       2.5% |             100 | 2.50 |             102.5 |
|state |       2.5% |             100 | 2.50 |             102.5 |

We need also to include the shipment taxes and the enterprise fees taxes.

So, how can  I fill this data in the suggested table?

**Comment by lin-d-hop** [comment]
Thanks for these questions @abdellani 

First question (for completeness): Please do include this. You are right the calculations aren't made from this field but it is helpful in accounting to know the VAT status of suppliers

Second question: Let me look into this. To be honest I think this was the puzzle that broke @Matt-Yorkley ;) Meaning it just might not be possible. Though the spec was originally approved by devs.

**Comment by lin-d-hop** [comment]
So the intention with this report is that if we have:
Product - 100
Enterprise fees - 10
Shipping fees - 5
All with state and country tax rate of 2.5%

We show:


Tax Category | Tax rate | Total (tax excl) | Tax | Total (tax incl)
-- | -- | -- | -- | --
country | 2.5% | 115 | 2.50 | 117.875
state | 2.5% | 115 | 2.50 | 117.875
. | **Total** | 115 | 5% | 120.75

The goal here is to summarise the whole order separating tax rates so that we can see how much of each type of tax is paid on each order.

My understanding is that the difficulty is in separating out the enterprise and shipping taxes as per each tax rate as this is calculated on the line item consecutively and can be either percentage or flat rate. 

It would be good to ensure that we have a shared understanding as a first step. Then we can start to adjust the spec based on what is possible and what is not. Does the above table make sense to you @abdellani? Do you think it is possible?

**Comment by abdellani** [comment]
@lin-d-hop 

I tried to implement this scenario in my local environment.
I started by creating two categories: Country and State.
![image](https://user-images.githubusercontent.com/16113997/209923069-ea9a52a1-c0c1-4d05-8b2f-a22fc1a79242.png)

When I tried to create the product, shipping method, and enterprise fees, I discovered that it's not possible to attach more than one tax category.

To fix that, I created a new tax category and called it "Australia Taxes", then I created two tax rates "Country" and "State".
![image](https://user-images.githubusercontent.com/16113997/209923427-6e092f49-8ac7-444c-9de9-37e910826a8d.png)

Question 1: Maybe we can add a new column for the `Tax rate name`?

The invoice (taxes = 5.5%  (2.5%+3%)
![image](https://user-images.githubusercontent.com/16113997/209931875-f5178431-4d46-4892-8087-da5c6123cd40.png)


### For the first report (by supplier)
I'm thinking about the definitions:

>Total (tax excl): Total of orders without tax
>Total (tax): Total tax applied in orders
>Total (tax incl): Total including tax (eg sum of last two rows)

Question 2: what if one order can have line items coming from different suppliers?

### For the second report (by order)
I think this will be easy since we have `order.all_adjustments.eligible.tax`

**Comment by lin-d-hop** [comment]
Hi @abdellani 

Question 1: Great, yes let's add another column for `Tax Rate Name`. I've added this to the mock spreadsheet.

Question 2: Yes orders will often have produce from more than one supplier. So this is tricky. We need to group all the orders that match the search filters and calculate the tax on these line items. In this supplier report we group by supplier, not order, as per the mock spreadsheet. Will that be possible?

**Comment by abdellani** [comment]
@lin-d-hop 
I implemented a draft of the "by producer" report. I'm getting the same results as in the example : 

![image](https://user-images.githubusercontent.com/16113997/210089585-758b4b45-cbb9-467a-93ba-ce94ddd2fcfb.png)

I'll test it with more complex scenarios. In the meantime, I'll ask for a review.

is it Ok if I add different subreports "Sales Tax Totals by producer" and "Sales Tax Totals by order" instead of  one report "Sales Tax Totals" ?
![image](https://user-images.githubusercontent.com/16113997/210090062-9a6de309-84e3-4c48-b975-421f9ffccdf3.png)

**Comment by lin-d-hop** [comment]
Hi @abdellani 
Great! Sounds like this is moving forward. The testing on this will be pretty complex so I'd be expecting it to go back and forth a couple times.

I think you're UI suggestion 'Sales Tax Totals by Producer' is good. This issue was written before the recent reports refactoring and the original spec was out of date. Sorry about that :)
