### ISSUE TITLE
Tax Totals with Rates by Order Report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6849]
## Description

As a hub manager I want to be able to view report that includes a breakdown of what is paid per order for each tax rate.

A mock of the report data in CSV form is available [here](https://docs.google.com/spreadsheets/d/1VmcaV2GFVgw-4fysnJn9QZeGbZqPOqfXJJ-GOVVbsTI/edit#gid=877250263).

- _Enterprise_: The hub for which the correlating order was placed
- _Order cycle_: Identifier for the order cycle in which the order was placed
- _Tax Category_: Self explanatory.
- _Tax Rate_: Self explanatory.
- _Total (tax excl)_: Total of orders without tax
- _Total (tax)_: Total tax applied in orders
- _Total (tax incl)_: Total including tax (eg sum of last two rows)
- _First Name_: First name of the shopper
- _Last Name_: Last name of the shopper
- _Customer Code_: Self explanatory
- _Email_: From the order

Note that after each Order a row of totals will be displayed.

The filters for this report will be the same as #6848. The only addition required for this report will be to enable the user to select between 'By Producer' and 'By Order'

- _By Producer/By Order_ (Dropdown): Allows user to view the report sorted by Producer or by Order

## Acceptance Criteria & Tests

1. All fields described above are present and data matches the description
2. Report can be downloaded as a CSV
3. Report can be accessed via the UI
4. Report can be filtered on all fields mentioned above
5. Totals row show correctly summed total amounts
6. In the UI figures should be rounded to 2 decimal places. In the CSV figures should be rounded to 6 decimal places.
7. All fields are translatable

**Comment by kirstenalarsen** [comment]
Can we please repeat any identifying and context information on the Totals rows when they are included, and that info makes sense in an 'aggregate' - so that when the user filters to use only the Totals rows they have the info about Enterprise, OrderID etc easily to hand
