### ISSUE TITLE
Allow user to show/hide totals with a checkbox toggle

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6850]
## Description

To increase the utility of this report we wish to enable the user to show and hide the Totals rows (as displayed in the CSV mock)

The user will have an additional checkbox filter:

- _Display Total Rows_ (Checkbox) Include total rows in display/CSV

When the box is checked, total row will be included.
When the box is not check the CSV download and the UI report will not have totals rows

This needs to be applied to both the By Producer and By Order pivots of this report.

Issue #6846 will be very similar to this.

## Acceptance Criteria & Tests

1. The Display Total Rows checkbox is included
2. When it is ticked the totals rows are display in CSV download and on UI
3. When it is not ticked the totals rows are not displayed in CSV download and on UI
4. Fields are translatable

**Comment by abdellani** [comment]
Hi @lin-d-hop 


Does "Display Total Rows" refer to "Summary Rows"?

In the report code, I see that if the selected format is CSV or JSON, the summary rows flag will be unchecked. 
https://github.com/openfoodfoundation/openfoodnetwork/blob/ee70645d04370b5c58363c9c878b5240603e4c3e/lib/reporting/report_renderer.rb#L24-L28

https://github.com/openfoodfoundation/openfoodnetwork/blob/ee70645d04370b5c58363c9c878b5240603e4c3e/lib/reporting/report_renderer.rb#L13-L15

I noticed the same thing in the UI
![image](https://user-images.githubusercontent.com/16113997/211977032-e0cfd2b3-c244-40e5-aab6-89154e9cfcff.png)

Do you want to change that behavior?

**Comment by lin-d-hop** [comment]
Hi @abdellani 
Correct, the 'total rows' are now called the 'summary rows'.
Let's stick with behaviour consistent to the other reports and disable the 'summary rows' in the CSV and JSON formats.

Out of interest, do you think it would be difficult to change this behaviour so that you can choose to show summary rows on CSV and JSON formats? This fell out of scope in the last reports changes and we had the impression it was a tricky to include the totals rows, particularly for the JSON. Don't spend more than an hour thinking about this question :)

**Comment by abdellani** [comment]
@lin-d-hop 

To answer your question, I updated the report to authorize summary rows on CSV.
I tested the two reports: `Sales Tax Totals By Order` && `Order Cycle Supplier Totals`, and I didn't notice any problems.
## Sales Tax Totals By Order
![image](https://user-images.githubusercontent.com/16113997/211983334-5fa0d51f-9021-4b5d-b0fb-36b035296d49.png)

![image](https://user-images.githubusercontent.com/16113997/211983388-85a123d3-0291-4644-bdcc-41ea3a81577f.png)

## Order Cycle Supplier Totals

![image](https://user-images.githubusercontent.com/16113997/211983586-416a66a5-7ad5-4383-8433-9a3215e8f2ce.png)

![image](https://user-images.githubusercontent.com/16113997/211983625-212f2112-8add-4334-8bc1-1ebfd1870efe.png)

**Comment by lin-d-hop** [comment]
Cool, any idea about the JSON? Given there's still 30mins left in that hour ;)

**Comment by abdellani** [comment]
@lin-d-hop 

This is the result: https://gist.github.com/abdellani/4ae748bd891ae99e81fa2f509c65e8cc

I think we have a small problem, the name of the attributes in the summary sub-document.
```json
        {
            "producer": "",
            "product": "",
            "variant": "TOTAL",
            "quantity": 6,
            "total_units": "6.0",
            "curr_cost_per_unit": "",
            "total_cost": "420.0"
        }
```

I notice another problem. 
I used the following query to request the documents
http://localhost:3000/api/v0/reports/orders_and_fulfillment?token=9ddde4af9a4f457d86e1c6fbd61d9880277c3ceadf67d69f&report_subtype=order_cycle_supplier_totals&q[order_cycle_id][]="5"&display_summary_row=true

I remove `q[order_cycle_id][]="5"` to fetch all the document
I get the following error
```json
{
    "error": "Please supply Ransack search params in the request"
}
```
If I replace it with `q[random][]`, it works. 
`q[][]` doesn't solve the problem.

**Comment by lin-d-hop** [comment]
Thanks @abdellani! From a dev perspective, how hard would it be for us to create a search param like 'include totals' which if true returns a new sub document appended to the end with different attributes? This needs some thought and design, but in theory would this be difficult? Though our hour is up :)

It's a known thing that you need to supply some search params for the API RQ, and I think a good buffer to try stop an inexperienced API dev from crashing our servers with a request for too much data :)

**Comment by abdellani** [comment]
@lin-d-hop 

We already have that search param: `display_summary_row=true`

One possible way to do it is by updating the `extract_rows`. We can check the targeted format before building the rows. 
https://github.com/openfoodfoundation/openfoodnetwork/blob/ee70645d04370b5c58363c9c878b5240603e4c3e/lib/reporting/report_rows_builder.rb#L47-L65

**Comment by dacook** [comment]
Hi @abdellani , sorry I didn't realise you had already started on this.  

It sounds like we don't have any reason for `raw_render?` to disallow summary rows for any format. 
Based on your comments, it sounds like we can already allow summary rows on CSV, and with my [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/10466), we can also enable for JSON (although it's certainly not pretty!)

So @lin-d-hop after my PR, should we proceed with allowing summary rows and headers on all formats? 
We can remove this distinction between "Formatted data" and "raw data": 
![Screen Shot 2023-02-23 at 12 36 18 pm](https://user-images.githubusercontent.com/4188088/220802761-0f7849e7-1e1f-45a2-8561-ce4f2cb7a857.png)
For backwards-compatibility, we should probably continue to make summary rows off by default for CSV.

**Comment by abdellani** [comment]
@dacook 
I don't know if this is helpful:
* After this [comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/9990#issuecomment-1340175806), I remember that I removed the summary row from a  CSV file used on the specs. 
* the UI disabled automatically the summary row checkbox when CSV format is selected.

**Comment by RachL** [comment]
> It should be deselected by default but allowed if selected.

Yes it's covered by https://github.com/openfoodfoundation/openfoodnetwork/issues/9546

> I think the maintenance cost of CSV is quite low for us

Perhaps on the tech side, but we shouldn't forget testing. @filipefurtad0 what do you think?

**Comment by filipefurtad0** [comment]
> I think the maintenance cost of CSV is quite low for us

> Perhaps on the tech side, but we shouldn't forget testing

Good points. It seems to me that CSV is easy to test/maintain - we do it already in our suite (like for the product import feature).

I would not know how to test XLSX files for content and we have issues testing PDFs as well, so I'd say these are more challenging to maintain.

**Comment by RachL** [comment]
FYI product import allows xslx 👍

**Comment by filipefurtad0** [comment]
> FYI product import allows xslx +1

Yes, but I don't think we test it :see_no_evil:

**Comment by lin-d-hop** [comment]
I do agree that if it isn't onerous to include the summary option in the CSV version we should do it. it will remove confusion. Given that we now allow this on API version, CSV is the only one left.

The original issue here is soooo outdated.... from before the new reports framework. I can create a new issue for this actual task and close this one.
