### ISSUE TITLE
flatpickr date-time-picker: Usablity issues for users on [mobile + Firefox] 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6859]
## Description

After implementing the new flatpickr date-time-pickers, it was noticed, while testing PR #6691 that these changes introduce a regression for Firefox users, on mobile devices: The user can click on the desired date and time, but cannot close the calendar, which takes up the whole screen.

## Expected Behavior

Selecting the desired dates inserts this info in the desired fields; After this, the calendar closes. (previously, the "Done" button was used for this purpose.)

## Actual Behaviour

The used cannot update the date-time fields.

## Steps to Reproduce

1. Choose an Android device on Browserstack.
2. Choose the browser Firefox. 
3. Login as admin, and Order Cycles page `/admin/order_cycles`
4. Try to open or close an order cycle, by changing the Open/Close dates.

Or:

3. Visit https://flatpickr.js.org/examples/ 
4. Click DateTime

## Animated Gif/Screenshot

**Firefox, on Android 10 Samsung Galaxy S20**:
![image](https://user-images.githubusercontent.com/49817236/107443215-52ff5700-6b30-11eb-9570-05e4a6f8c729.gif)

The same device, visiting the page https://flatpickr.js.org/examples/ and clicking 

![image](https://user-images.githubusercontent.com/49817236/107443442-c1441980-6b30-11eb-9191-dd70f95855d1.png)

## Workaround

Rotate the phone 90 degrees.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.5.7
* Browser name and version: relevant for Android devices in Firefox
* Operating System and version (desktop or mobile): Mobile

**Comment by RachL** [comment]
@filipefurtad0 with @jibees 's feedback here https://github.com/openfoodfoundation/openfoodnetwork/pull/6691#issuecomment-777004308 I think we can lower the severity. Also I think we should open this issue on their repo (as well), what do you think? I've been browsing their firefox issues but now I'm not 100% sure they do have exactly this one.

**Comment by filipefurtad0** [comment]
Opening an issue on their repo is a good idea @RachL :+1:

**Comment by filipefurtad0** [comment]
And yes, I guess downgrading is ok, we're assuming not many users are affected. 

But I'm wondering @RachL @jibees if we have numbers to demonstrate this? I remember discussing 25% of admin visits coming from smartphones, at some point. Does this scale, to other instances? What is the share of Firefox users on mobile, in OFN?

**Comment by RachL** [comment]
@filipefurtad0 this number applies only to FR. Other instances are under 15%. On this share, firefox is not the most used browser. Chrome comes first. Again in FR Firefox seems quite used, but on other instance Firefox is far from being the top browser used. So yes this is not a really severe issue for us.

**Comment by filipefurtad0** [comment]
Cool, thanks for clarifying Rachel :+1:

**Comment by jibees** [comment]
I (re)tested with Samsung S20/Firefox, and (now?) there is a scroll bar that you could use to see the action buttons: 
<img width="506" alt="Capture d’écran 2021-07-27 à 13 59 26" src="https://user-images.githubusercontent.com/296452/127149984-b15b9559-f0b4-4536-b199-0d554d74c884.png">

Is this issue still available then?

**Comment by filipefurtad0** [comment]
> Is this issue still available then?

I've missed this comment JB - I've found the scroll bar now  :see_no_evil: 
Closing.
