### ISSUE TITLE
Backoffice SCA-payments marked as uncaptured after completed authentication

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6867]
## Description

A similar issue to #6755 , but concerning orders placed in the backoffice.

## Expected Behavior

After the authentication step is successfully completed and the customer sees the order confirmation, the admin should see the order marked as "complete" in the backoffice, on /orders 

## Actual Behaviour

After the authentication step is successfully completed and the customer sees the order confirmation, the admin still needs to take action to capture the payment and change the order state to "complete" 

## Steps to Reproduce

1. As an admin: Place an order in the backoffice and create a Stripe SCA payment with valid a 3D-auth card, which always requires auth., like -3184 
2. As the customer: Expect the email to arrive on the customer's email account
3. As the customer: Complete the authentication step. This should lead to the order confirmation screen.

As an admin
3. Go to orders, and check the payment state for that order -> see it's "pending"
4. Capture the order by clicking the "pencil" icon, i.e. editing the order -> this captures the payment and changes the order state to "complete". **Only** after this step do the order confirmation emails arrive. 

## Animated Gif/Screenshot

An incomplete payment, **before the authentication step** is completed from the customer's side:
**Stripe Dashboard**
![image](https://user-images.githubusercontent.com/49817236/107651988-01fa7a80-6c78-11eb-8a87-ad4ace964eaa.png)

**Orders Page and Order State**

![image](https://user-images.githubusercontent.com/49817236/107652509-906efc00-6c78-11eb-920d-a11ac287eff9.png)

![image](https://user-images.githubusercontent.com/49817236/107652350-64ec1180-6c78-11eb-8abf-07e1a1142158.png)

**After the authentication step** is completed:

The payment remains uncaptured on Stripe:

![image](https://user-images.githubusercontent.com/49817236/107652759-d330d400-6c78-11eb-9774-22f6d381ce6e.png)

In the BO, the order is not listed under "complete orders". To make it complete, the payment needs to be captured by:

- clicking the pencil to edit the order (see video below). Clicking "capture" seems to capture the payment, but it does not bring the order to a "complete" state.

![capturing_the_order](https://user-images.githubusercontent.com/49817236/107653407-80a3e780-6c79-11eb-827b-33b523677936.gif)

## Workaround

Capturing it manually.

## Severity

I'd say less serious than #6755, maybe:
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.5.8
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by filipefurtad0** [comment]
This issue is blocking #6808 , the customers transactions tab only shows orders in the state "complete", which is a condition for the link to appear for the customer to take action, and provide authentication, as [seen in this comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/6808#discussion_r573862645):

![image](https://user-images.githubusercontent.com/49817236/107771782-32ebb580-6d33-11eb-8209-e89f5ceea54c.png)

**Comment by filipefurtad0** [comment]
Please note that issue is worsened by PR #6713, i.e., the steps to reproduce described on this issue will not work: The order cannot reach a "complete" state, when placed in the backoffice and paid via Stripe SCA.

**Comment by andrewpbrett** [comment]
@filipefurtad0 Thanks for catching this. I've pushed some additional commits to #6808 so it should now be unblocked, and it should also close this issue, pending your thorough testing :)

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett , I see you've opened #6909 which is the missing bit on this issue, after the recent merged PRs on SCA; I think we're safe on closing this issue.
