### ISSUE TITLE
configure new relic and server down notifications (wormly?) for uk

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#688]
@lin-d-hop @pmackay @NickWeir63 - just popping in some cards so you can see progress, what has been knocked off this week

**Comment by mkllnk** [comment]
Done. @lin-d-hop and @stveep have access.

**Comment by pmackay** [comment]
Just to understand, what is the access for?

**Comment by mkllnk** [comment]
NewRelic and Wormly.

NewRelic has nice performance graphs and handy to identify problems on the server.

Wormly is just checking that your server is still responding and sends text messages to a phone if the server can't be reached.

Would you like to be on the list as well?

**Comment by pmackay** [comment]
Yes please if it doesnt cost anything.

**Comment by mkllnk** [comment]
*Wormly*: Rohan pays for his account and we use it as well. I don't think that we pay for contacts. But if they send more than 40 text messages a month, they will charge him $0.18 per text.

Your email  and Lynne's email are on there now. Would you like to have a mobile phone notified as well?

*NewRelic*: We are on a free plan. The restriction is that we can see data only for the last 24h. But I guess that that is okay for now. You have been in there already.

**Comment by pmackay** [comment]
No need for phone notification for now :)
