### ISSUE TITLE
Remove the powered by google logo on both main map and the group maps

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6882]
## Description

**- As a:** simple web surfer
**- On page:** /maps and /groups
**- I want to be able to do:** Not see google's branding anymore see https://github.com/openfoodfoundation/product-pipe/issues/39#issuecomment-778175396 for details

## Acceptance Criteria & Tests

1. The map should display all pointer correctly except known bug #6829
2. Registering and editing an address as an enterprise works as in current master, expect without the Google Logo

**Comment by mkllnk** [comment]
The logo is identified by the image it links to: https://maps.gstatic.com/mapfiles/api-3/images/google_white5.png. Hiding it should be fairly easy but it's really just a short term workaround. I can probably do that today.

**Comment by mkllnk** [comment]
Oh, hang on, I was looking at the Google logo at the bottom left of the map. Some of the complaints are about the "powered by Google" in the search results. That's content coming straight from Google. We would need to remove that search completely.

**Comment by mkllnk** [comment]
I found that it's much easier to revert to Google tiles which is properly compliant with Google licensing.

**Comment by RachL** [comment]
> Some of the complaints are about the "powered by Google" in the search results. 

@mkllnk now I understand why removing the logo could be an option for Google! Nice catch :+1: It's great that it was easy to revert!!
