### ISSUE TITLE
Bulk Order Management page: missing one translation

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#6892]
## Description
One translation is missing in bulk order management page: the title of the box, appearing when you click on one item.
<img width="189" alt="Capture d’écran 2021-02-16 à 10 01 14" src="https://user-images.githubusercontent.com/296452/108040690-e9a2ab00-703d-11eb-87b7-059c24db01cd.png">

## Expected Behavior
The word `ALL` must be translated into your current langage used by your platform.

## Actual Behaviour
The word `ALL` isn't translated.

## Steps to Reproduce

1. Login as Admin and visit bulk order management tab: `/admin/orders/bulk_management`
2. Click on any line item to display the mentioned box, with totals
3. Click on "Shared Resources?" (or something similar in your language) checkbox
4. The word `ALL` in the title should be translated

#### How to reproduce
![2021-02-16 10 01 44](https://user-images.githubusercontent.com/296452/108040785-07701000-703e-11eb-8361-c3078eceb4ce.gif)

#### In English: without consequence
<img width="612" alt="Capture d’écran 2021-02-16 à 09 54 51" src="https://user-images.githubusercontent.com/296452/108039961-09859f00-703d-11eb-8bf2-b05faeef5edc.png">

#### In Catalan: should be translated
<img width="615" alt="Capture d’écran 2021-02-16 à 09 57 43" src="https://user-images.githubusercontent.com/296452/108040298-6d0fcc80-703d-11eb-86cb-963f825f1830.png">

## Workaround
No workaround.

## Severity
bug-s5: we can live with it, only a few users impacted

As "ALL" is a very known english word, I think it's not a problem for most of users.

## Possible Fix
Add translated key into Transifex.

## Context
Spotted via #6865

**Comment by efgalvao** [comment]
Hello. I would like to fix this one.

**Comment by RachL** [comment]
hello @efgalvao no it's not fixed you can go ahead :) Welcome!! If you have any questions don't hesitate to join our #dev channel on [Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A).
