### ISSUE TITLE
Use new customer balance calculation in bulk coop report

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#6896]
## Description

**- As an:** enterprise user 
**- On page:** order_management/reports/bulk_coop
**- I want to be able to do:** get the right "Amount owing" and "Amount paid" using the Bulk Coop Customer Payments report type.

## Acceptance Criteria & Tests

We want to display those two amounts being consistent with what we show under /account in the frontoffice as well as with the /admin/customers page.

**Comment by RachL** [comment]
@sauloperez what's the difference with this issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/6856 ?

**Comment by sauloperez** [comment]
different reports
