### ISSUE TITLE
New date picker does not prefill correct end date in reports

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6917]
## Description

Some reports have their date prefill with the last month range.

Since the introduction of the new date picker the date range is fixed at 20.01.2021 to 20.01.2021

List of reports impacted are all under:

`/admin/reports/orders_and_fulfillment`

## Steps to Reproduce

1. Log in as admin
2. Go to `/admin/reports/orders_and_fulfillment`
3. See the prefilled dates

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/d4ef774e-4734-481e-ba3e-6f5514ceb6eb)

## Workaround

Removes the dates

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v3.5.9
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment]
@jibees how is your pile of work doing? :) If you have lots of room before your holidays, I think this is a little regression from the introduction of the date picker but I can be wrong.

**Comment by jibees** [comment]
Yes, will do my best today. 
As far as I know it's a bug that concern maybe only French (in any case, the bug is don't reproduce in english)

**Comment by eugenichafer** [comment]
In Katuma it shows always a period between today and next number day+1 of next month

<img width="488" alt="Captura de Pantalla 2021-02-25 a les 22 31 21" src="https://user-images.githubusercontent.com/64070973/109222254-f780ca80-77b9-11eb-9c84-baa79e302e3a.png">

**Comment by RachL** [comment]
@eugenichafer yes this is the correct behavior, it was like this before the bug.
