### ISSUE TITLE
Xero - Adjustments not carrying into the Xero report

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#692]
The screenshot below shows that a shipping adjustment was added, but a new adjustment was not. It also seems that GST is not charged on adjustments (can't control from enterprise settings)? Is there a way to make it include GST?

![image](https://cloud.githubusercontent.com/assets/10843056/10534836/a370818c-7428-11e5-8f71-06dc3ca96b5f.png)

**Comment by kirstenalarsen** [comment]
Create ability to assign tax to the adjustment - yes / no / select tax? and put appropriate tax code into xero report line items

**Comment by sstead** [comment]
Testing - ability to assign tax rates to new/existing adjustments. Do these adjustments and the correct tax rates carry into Xero report?

Yay- when you go to an order's adjustments. You can see if the existing ones carry tax (this might be on an enterprise fee that was applied in the shop). You can also create a new adjustment (like a late fee) and when you create it, you can select a tax rate to apply to it. You can also edit an adjustment and edit whether it's got tax applied or not.

A few issues:
![image](https://cloud.githubusercontent.com/assets/10843056/11082337/764f94c2-8878-11e5-9e24-1a3b2f014714.png)

![image](https://cloud.githubusercontent.com/assets/10843056/11082540/48420aa4-887a-11e5-8c9b-c80766e314d4.png)

**Comment by kirstenalarsen** [comment]
@sstead @RohanM so can we now close this? If there is still an issue with shipping, can create separate issue?

**Comment by sstead** [comment]
closed - https://github.com/openfoodfoundation/openfoodnetwork/issues/730
