### ISSUE TITLE
Release v3.5.10 Cucumber

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#6920]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Draft new release]
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2211
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/

**Comment by RachL** [comment]
This release is ready to go! Thanks team :tada: https://docs.google.com/document/d/1u5O0vup4jaeKR9vnV8VT9pOck0tZZ-ipqdYTvtoun2U/edit#heading=h.anfihdtue49m
