### ISSUE TITLE
When editing an order, I can't add line item and adjust at same time

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#693]
When logged in as a regular user... (doesn't happen if SuperAdmin)...
So if you're editing an order, and adjust the QTY of a product already in the order, and then try to add a new product (that isn't already in order), when you click the +ADD button, the new product is added to the order, but the QTY of existing product reverts to original. 

To avoid this happening you have to save the QTY change that you made, and then add the new item.

Food Connect raised this.

**Comment by daniellemoorhead** [comment]
@sstead can you check whether this has been fixed please. If fixed, close the issue. If not fixed change the milestone to Australian Backlog.

**Comment by RachL** [comment]
The UI has changed since this issue. Yes you are loosing you changes if you don't save the new quantity, but it's a bit more clear now with a new saving button. I'm closing.
