### ISSUE TITLE
staging-UK: payments with Stripe-SCA - page not found after authentication step

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6931]
## Description

Checking out using Stripe SCA leads to a "page not found", after the authentication step, on staging-UK.

This seems only related to staging-UK. After staging master - https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2204 - in staging-AU, I could not reproduce the issue.

**Broken link**:

`
https://demo.openfoodnetwork.org/checkout?payment_intent=pi_1INb0GKuuB1fWySnlcjek3UU&payment_intent_client_secret=pi_1INb0GKuuB1fWySnlcjek3UU_secret_7r254T92ftvzB97Y5C0eeEbbp`

**Console**:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/239d3b80-6679-4c94-b51a-787dee6d9cfd)

![stripe_sca_broken_in_staging_uk.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/6a0d8ffb-1951-42e4-b8dc-f7b18ec07086)

## Steps to reproduce

1. As a customer, visit a hub, which has stripe-SCA set up
2. Insert some items and proceed to check-out
3. Insert card `4000002760003184` or any card which requires authentication
4. Try to authenticate, and finish the purchase

**Comment by filipefurtad0** [comment]
This seems to be the case, with staging Katuma as well:
![image](https://user-images.githubusercontent.com/49817236/108819228-7dcac000-75b2-11eb-9724-738e0dbe09b5.png)

But working on staging-FR, and AU. I'm using the same Stripe account to connect to all staging servers.

**Comment by filipefurtad0** [comment]
Ok, this is not a Sysadmin issue, maybe even expected behavior, I don't know - I'm moving this to All the things - thought of S3, but maybe it is not.

So, on orders/servers/(situations?) in which for some reason are not going through with a 3D-auth. card., payments with non-3D-auth. card (like 424242...) card triggers this error:

https://app.bugsnag.com/katuma/katuma/errors/602cbf57d9fdda00188e2bbe?event_id=6034bfbd006ca08d237b0000&i=sk&m=nw

![image](https://user-images.githubusercontent.com/49817236/108820673-72789400-75b4-11eb-86d8-73393841f39a.png)

Attempting once again, with the 424242... card then works, but we can see the several attempts on the transaction fee:

![image](https://user-images.githubusercontent.com/49817236/108820888-b9ff2000-75b4-11eb-9a5b-2334bec842e1.png)
 
A tentative explanation here is that Stripe charges a fee, for 3D-auth. transactions. This would explain everything, except:
- the fact that 3D payments are not going through in some cases (servers)
- that the hubs transaction fees pile up on the shopfront as well - although this seems to happen only in this scenario (1) attempting payment with a 3D-auth card, and, after failing, pay the order with a non-3D-auth card.

**Comment by Matt-Yorkley** [comment]
It looks like the `Spree::Config['site_url']` value has been reset to the default somehow (`demo.openfoodnetwork.org`). That's what's breaking the redirects. I imagine if you click a link in an email (like reset password) it will also be broken...

**Comment by filipefurtad0** [comment]
Yes, I just confirmed that now (for password reset). Wondering how we lost that config... After a deployment? :thinking:

**Comment by Matt-Yorkley** [comment]
I've just reset it via superadmin, we can keep an eye on it...

**Comment by filipefurtad0** [comment]
Ok, it's back now - after restarting unicorn, changes took effect :+1:

**Comment by filipefurtad0** [comment]
I think the issue can be closed now, but I'm thinking if we could somehow automate post-deployment checks. In /spec/features/admin/configuration/general_settings_spec.rb we have this like:

`expect(find("#site_url").value).to eq("demo.openfoodnetwork.org")`

Which is of course not catching changes in this field after deployment, on other environments...

We also had this issue in the past #5932 (which probably can be closed as well).

This issue/comment also seems related:
https://github.com/openfoodfoundation/openfoodnetwork/issues/6529#issuecomment-745691551

How could we improve automatic post-deployment checks?
