### ISSUE TITLE
[Adjustments] Updated Amounts from a Tax Rate not considered when updating an order

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6935]
## Description

Observed while testing #6678.

A superadmin changes a Tax Rate from 10% to, say, 15%. After this change, a hub/admin wishes to edit and update previously placed orders, to reflect this change. Editing the order and clicking "Update and recalculate fees" does not change the Amount set on the respective Tax Rate. It only is changed after line items are removed or added to the order.

This can be seen at the DB level:
https://github.com/openfoodfoundation/openfoodnetwork/pull/6678#issuecomment-773890915

## Expected Behavior

Clicking "Update and recalculate fees" does not change the amount set on the respective Tax Rate. It only is changed after line items are removed or added to the order.

## Actual Behaviour

Clicking "Update and recalculate fees" does not change the amount set on the respective Tax Rate, as discussed here (ping @Matt-Yorkley ):
https://github.com/openfoodfoundation/openfoodnetwork/pull/6678#issuecomment-773623933

## Steps to Reproduce

0. As superadmin, set the Amount of a given Tax Rate to be 10%
1. As an admin, set up that tax on a given product, and place them in the shopfront
2. As s customer, place an order - 10% should be charged as tax
3. As superadmin, edit that Tax Rate, and change its Amount to 20%.
4. As the admin, visit the newly placed order, and "click update and recalculate fees" - Verify that the outdated 10% tax is charged.
5. The workaround: add or remove a line item - this should get the new tax rate, recalculating it for the whole order.

## Animated Gif/Screenshot

![Peek 2021-02-22 13-14.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/54edb7d2-32fd-4118-830c-7f0b90f24e70)

## Workaround

Point 5, as described above:
![Peek 2021-02-22 13-38.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/d071ab74-9d09-48f4-8269-6039ec2ee42a)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.4.8
* Browser name and version: Firefox 84
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by efgalvao** [comment]
Hi. Can I try to fix this one ?

**Comment by filipefurtad0** [comment]
Hi @efgalvao ,

I think taxes and adjustments is quite a tricky topic and undergoing lots of changes, lately.
Maybe best to tackle a "good first issue" (label)? Thank you for your interest!

**Comment by Matt-Yorkley** [comment]
If a customer placed an order 6 months ago and the tax rate was 10%, and today the government announces that the rate is officially changing to 15%, and I update that tax rate to 15% in superadmin... the order that was placed 6 months ago should still be using the rate that was applied _at the time the order was placed_, and not the new rate I've just applied 5 minutes ago, right?

This is genuinely a feature and not a bug :laughing:
