### ISSUE TITLE
[release test automation] Payment methods

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6939]
### What we should change and why (this is tech debt)

We need to verify if these test cases are sufficient to cover this feature and skip the manual testing of this during release preparation. The relevant spec is:

- `spec/features/admin/payment_method_spec.rb `

With test cases (edited output from running the spec with `-fd` options)
- As a Super Admin, I want to be able to set a distributor on each payment method
 - creating a payment method
    - using stripe connect
      - communicates the status of the stripe connection to the user  
    - assigning a distributor to the payment method
    - checking a single distributor is checked by default
    - checking more than a distributor displays no default choice
 - updating a payment method
 - as an enterprise user
    - I can get to the new enterprise page
    - creates payment methods
    - shows me only payment methods I have access to
    - does not show duplicates of payment methods
    - shows me only payment methods for the enterprise I select (PENDING: No reason given)

All test cases currently passing except the last one -> `(PENDING: No reason given)` -> this needs fixing, I guess.

This looks like the same failure observed on #6693.

### Context

This came up in the context of release test automation. Also, one should assess whether any changes are required, considering the Stripe transition Connect -> SCA.

### Impact and timeline

Makes our build more resilient to changes/upgrades and removes the need to test manually. 

Removing manual release testing from our weekly tasks and making the automated test suite more resilient.

**Comment by filipefurtad0** [comment]
The "Calculator" section is not covered by this feature spec, as shown by the regression #7027.

We might need to add feature tests here (reason for reopening), if we find that controller tests are insufficient.

**Comment by sauloperez** [comment]
any extra tests covering the regression need to come included in the PR fixing the regression, though. Agree is worth keeping this open to assess the situation once that gets addressed.
