### ISSUE TITLE
BOM- search filter misbehaving. potentially looking at product description too.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#694]
Food Connect suspects that the search filter is not always responding when you type into it. I haven't been able to recreate this. But we think perhaps they are just getting too many products returned in their searches...

This may be because the searcher is looking at the product description as well?
Or it may be not filtering correctly. 
See example below...  I checked and the Mince Lamb didn't have any product description. So why is it coming up under a search for AL?

![image](https://cloud.githubusercontent.com/assets/10843056/10535238/c63f7052-742c-11e5-98f6-079d51f57c4a.png)

**Comment by RachL** [comment]
I've not been able to reproduce this. I specifically tested to add the search item in a description, but the item didn't came up, so it is not looking at description.

As no one reported anything recently on this, I'm closing this issue and we will reopen if necessary.
