### ISSUE TITLE
Monthly job for updating Global Key Stats | Script for 2 missing metrics

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#6948]
### Description

And automated job for monthly updating the key stats would help for the global fundraising work as well as to generally have accurate numbers for every month available whenever needed.

**When?**
1st week of every Month, to get data for the full previous month

**Which Metrics?**
- Sales (in local currency)
- Number of orders

Optional, if possible:
- Number of Customers (i.e. Number of shoppers that placed an order in that month)
- Number of Active Producers/Hubs (i.e. Number of enterprises that had >=1 sale)
-> These numbers will help to measure additional to the the pure business metrics the value that OFN brings in connecting producers and consumers

**Where to?**
Suggestions welcome :)

Best case, in a separate Tab in the Global Key Stats Google Sheet.
Simplest way, an automated e-mail with the CSV to jana@openfoodnetwork.com zap into analytics channel also works.

In case that helps, here are the SQL queries that we use for pulling those stats from Metabase

**Nr. of Customers, for Feb 2021**

```
SELECT count(distinct "Customers"."email") AS "count"
FROM "public"."spree_orders" INNER JOIN "public"."customers" "Customers" ON "public"."spree_orders"."customer_id" = "Customers"."id"
WHERE ("public"."spree_orders"."completed_at" IS NOT NULL
   AND ("public"."spree_orders"."completed_at" >= timestamp with time zone '2021-02-01 00:00:00.000Z' AND "public"."spree_orders"."completed_at" < timestamp with time zone '2021-03-01 00:00:00.000Z'))
```

**Nr. of Active Enterprises**

```
SELECT count(distinct "public"."enterprises"."id") AS "count"
FROM "public"."enterprises" INNER JOIN "public"."spree_orders" "Spree Orders" ON "public"."enterprises"."id" = "Spree Orders"."distributor_id"
WHERE ("Spree Orders"."state" = 'complete'
   AND ("public"."enterprises"."sells" <> 'unspecified'
    OR "public"."enterprises"."sells" IS NULL) AND ("public"."enterprises"."sells" <> 'none' OR "public"."enterprises"."sells" IS NULL) AND "Spree Orders"."completed_at" BETWEEN timestamp with time zone '2021-02-01 00:00:00.000Z' AND timestamp with time zone '2021-02-28 00:00:00.000Z')
```

**Comment by jaycmb** [comment]
Frrom conversation with @mkllnk we have 2 options:
- create an API endpoint (once created, accessing shouldn't need any coding skills as far as I understood)
- create a separate app to do this, similar to the scripts Maikel did before but this time code gets published

For the API version Lynne had concerns, as this cannot be an official endpoint.
Since Maikel & me have not been part of these conversations, maybe @lin-d-hop could briefly clarify.

Non-technically speaking: what would be the "simplest" solution to schedule a script to pull those numbers and dump into a spreadsheet (or send the output as a csv via mail?)

**Comment by RachL** [comment]
@jaycmb 

> once created, accessing shouldn't need any coding skills as far as I understood

It would however require you to become super admin of all instances. Otherwise it would mean that the endpoint is open for anyone. I'm not sure we want that?

**Comment by mkllnk** [comment]
> It would however require you to become super admin of all instances. Otherwise it would mean that the endpoint is open for anyone. I'm not sure we want that?

I don't know either. It would be great to have that information public. Maybe we should survey all instance managers. I don't see any harm in this.

If some people don't want it public, we could protect the API endpoint optionally, set on a per-instance basis. Either via super-admin or with a separate key to access those stats.

@lin-d-hop Why does this endpoint not fit in the current API roadmap?

**Comment by jaycmb** [comment]
As decided in last night´s product curation meeting: an automated job at this point seems to be more complex than just running the script for the 4 Key Stats "manually" 1/month.

@mkllnk proposed the following definitions for

- **Number of customers:** Count user accounts which placed an order that month. It doesn't matter if they bought from multiple shops or from one.
- **Number of active enterprises**: Every order is a sale for the distributor and all producers of the products in that order. And we count all enterprises that have at least one sale that

**Comment by mkllnk** [comment]
I wrote SQL statements to gather those metrics: https://gist.github.com/mkllnk/d101e9d441834716f8c967dbf7adc31f

I ran it for all production servers and copied the results into the spreadsheet.

**Comment by andrewpbrett** [comment]
Where should we put this issue on the ZenHub board? Is the idea to run the task each month? Maybe a Slack reminder to the dev channel would work best.

**Comment by mkllnk** [comment]
Good idea with the Slack reminder. I moved it to review hoping that Jana might comment on it but she replied on Slack. I think she approves of the current script and we can close the issue.
