### ISSUE TITLE
Toggling unit prices for unlogged users (in 'development' or 'staging' environemts)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6953]
## Description

Currently, it is necessary to log-in to enable unit prices (or any feature). This does not appear to match the criteria set on `config/initializers/feature_toggles.rb`

```
OpenFoodNetwork::FeatureToggle.enable(:unit_price) do
  ['development', 'staging'].include?(ENV['RAILS_ENV'])
end
```

From which one would expect that the feature is toggled only by meeting the requirement of running the app in 'development' or 'staging'.

## Expected Behavior

Users do not have to log in to see unit prices in the shop front, in 'development' or 'staging' environments

## Actual Behaviour

Currently users need to log in see unit prices in the shop front, both on 'development' or 'staging' environments.

## Steps to Reproduce

In 'development' or 'staging' environments:

1. As a non-logged in user: Visit a shopfront and see the missing unit prices 
2. Log in, and re-fresh the page -> unit prices should appear.

**Comment by jibees** [comment]
This will be possible with Flipper: #7259
