### ISSUE TITLE
Problems placing a shopper order on UK staging

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#696]
@mkllnk thank you very much for the update to UK staging - it is looking great apart form two issues so far - 
1) after selecting cart items when I submit an order on the stroudco shopfront  (before I get to delivery /payment options) I get a message in a temporary blue banner (which disappears after a few seconds) saying "the hub you selected is temporarily closed for order, please try later"
2) the Stroudco logo doesnt appear on the shopfroint - there is an empty box where it should be and when I scroll down the list of products the empty box stays on the screen and  i cannot edit the quantity of any prodcuts that are under the box.

**Comment by kirstenalarsen** [comment]
Check you have s valid payment method

**Comment by mkllnk** [comment]
Point 2) is just a missing logo for the website itself. Unfortunately, the placeholder is invisible but takes up a lot more space and covers other parts of the website (shopfront).

Point 1) probably needs some testing. Is it reproducible? Is the same happening on the AUS website?

**Comment by NickWeir63** [comment]
Bit more testing on point 1)......
The problem is only happening on UK staging - not on UK production and not on Aus staging 2 - I have just successfully put orders through on both of those.

I have checked that I have a valid payment method - and this order cycle was copied across from production by @mkllnk so surely the payment method was copied over with it?

Yes it seems reproducible - I have just done it again and created this screenshot
![temporarily closed](https://cloud.githubusercontent.com/assets/10517702/10559533/834a078a-74ea-11e5-89b2-8f557d435c56.JPG)

**Comment by kirstenalarsen** [comment]
I cannot check it on uk staging, but strongly suspect your payment method
is noactive. Go into the payment method and check. This looks like the
thing we deliberately put in to enable people to have 'sample' shopfronts
that people cqnnot actually order through

**Comment by mkllnk** [comment]
That's a good hint. Payment methods are bound to an environment, staging or production. I copied the production database to the staging server. So all payment methods that were active at the production site, are not active on the staging site and vice versa.

**Comment by NickWeir63** [comment]
Good team work - although the payment methods were active they were set up for production not staging so when I set up a new one on staging it resolved that problem - thank you both!

Next problem is that I am not getting confirmation emails (neither to the shopper or the hub) and when I do a password reset that doesn't come through by email either.  This is the problem that you fixed on "confirmation emails not coming through to hub or shopper from UK production #648" - please can you do it again?!

Also - going back to point 2 - 2 can I upload an image for the website itself (I have superadmin access but couldn't find anywhere to upload an image)?  and will this solve the problem?  

thanks for your help on all this

**Comment by mkllnk** [comment]
Email: There were two things not right: the mailing method was set up for production. I changed it to staging. And the process handling sending the emails (delayed job) wasn't set up either. I hope it works now.

Images: Not sure. The design changes were done while I was away. I need to ask the team on Wednesday to find that out. Maybe @kirstenalarsen knows it?

**Comment by NickWeir63** [comment]
Yes - great thanks the emails are working fine now.
Shouldn't you be asleep??!!!

**Comment by mkllnk** [comment]
Hi Nick,

the logo and background image can be [customised by admin users](http://community.openfoodnetwork.org/t/configuration-content/307).

Any other issues that came up?

Just tell us when you are ready for a production upgrade.

**Comment by NickWeir63** [comment]
Hi Maikel
Thanks - i tried uploading logos as png, tiff, jpeg and various different sizes but each time I clicked update the screen went back to 'no file chosen' - see screenshot.
I guess the logo file needs to be in a particular format - please can you advise?
As soon as we get this sorted out and the logo doesn't block the shopping screen we would love to get this on production
thanks
Nick
![uploading logos](https://cloud.githubusercontent.com/assets/10517702/10633901/e3fc2380-77e5-11e5-9ead-12e63d560660.jpg)

**Comment by mkllnk** [comment]
Ok, I can reproduce that. The page doesn't tell you which images have been uploaded already. But, if you reload the homepage, you will see that the images have been uploaded. Can you confirm that?

We use a logo that is 640px × 130px. I guess the ratio is important so that is doesn't overlap the content.

**Comment by NickWeir63** [comment]
Great! Yes I can confirm that the new logo is in place and no longer blocks the shopping page!  Thank you @mkllnk .  I am happy for us to go ahead and deploy to UK production - but please bear in mind that we have been doing a lot of work massaging data on production (adding photos and manually changing unit/value data that was not migrated from the legacy Stroudco system) so please DO NOT overwrite the current data on production!
Thanks again for all your work on this
N
