### ISSUE TITLE
Stripe webhooks are failing for be-prod

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#6992]
## Description

Stripe notified us that they can't deliver webhooks to our Belgian server.

## Expected Behavior

Stripe webhooks are delivered which can be viewed in the Stripe dashboard.

## Actual Behaviour

Webhooks fail with a 404 response.

## Steps to Reproduce

1. Log into the Stripe dashboard of the Belgian instance.
2. Go to the affected account: https://dashboard.stripe.com/acct_1Hx6ktF90sHuhCtT/events
3. You see some events marked with a symbol, next to "Your account information was updated."
4. Clicking on the symbol gives you more details. Stripe receives a 404 code.

## Animated Gif/Screenshot

> Objet : Stripe webhook delivery issues for https://openfoodnetwork.be
> 
> Hi there, 
> 
> We're contacting you because we've had some trouble sending requests to a webhook endpoint associated with your OFN BE account in live mode. Webhooks are used to notify your server about events that happen in your Stripe account, such as a payout completing or an invoice being created. The failing webhook endpoint is https://openfoodnetwork.be/stripe/callbacks.
> 
>  You or someone on your team has added that endpoint in your Stripe webhook settings, which you can view and edit here: https://dashboard.stripe.com/account/webhooks.
> 
>  Please note that in most cases a failing webhook does not impact your payments or payouts. However, if you use subscriptions we rely on your webhook endpoint to notify you of new invoices. These invoices may be delayed for up to three days if your webhook is unable to successfully receive them. If you use Checkout, you may be handling the `checkout.session.completed` event as part of your purchase fulfillment process as described here: https://stripe.com/docs/payments/checkout/fulfillment#webhooks. If you do, failure to handle these events may interfere with purchase fulfillment.
> 
>  We've attempted to notify the endpoint 17 times since February 18, 2021 at 01:45PM. If this endpoint is important to your application, please try and fix the issue. If you do not need the webhook endpoint you can delete it from your Stripe webhook settings. We will stop sending notifications to your webhook by February 27, 2021 around 01:45PM.
> 
>  Here is the summary of errors we have received when sending you webhooks:
>  * 17 requests returned a HTTP 404, you should verify the endpoint URL in your Stripe webhook settings.
>  
>   You need to return anything between a HTTP 200 to 299 for the webhook to be considered successfully delivered.
>  For more details on the errors, you can find your events page here: https://dashboard.stripe.com/acct_1Hx6ktF90sHuhCtT/events.
> 
>  You can also always review the history of webhooks and failed request logs right from your dashboard: https://dashboard.stripe.com/acct_1Hx6ktF90sHuhCtT/events.
> 
>  For more in depth information about how to use webhooks, we recommend taking a look at our documentation: https://stripe.com/docs/webhooks.

Here is an example of account information that couldn't be updated:
![Screenshot from 2021-03-04 17-04-31](https://user-images.githubusercontent.com/3524483/109918959-f85eb280-7d0b-11eb-94cd-241eb6d62019.png)

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
**bug-s3: a feature is broken but there is a workaround**
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

It looks like account updates are not synchronised. So if an enterprise uploads a logo in the Stripe dashboard, that gets sent to OFN but OFN doesn't know what to do with that. This doesn't affect OFN's functionality but these false alarms are dangerous because a Stripe admin may disregard a notification in the future if something is seriously broken.

I will rate it as S3 because something is broken and the workaround is to ignore the false alarms.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

If my theory is right, we could handle this event here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/5985344166cfc014fc9d5e7fe8fc01dafb4f2bc4/app/controllers/stripe/callbacks_controller.rb#L9-L16

**Comment by RachL** [comment]
@mkllnk you should have received an invite to BE's stripe account on your OFN AU email.

**Comment by mkllnk** [comment]
Okay, I don't think that this is critical. Enterprise account information gets updated from time to time and Stripe sends the event to OFN. At some point in January that call started failing. It's possible that a stripe gem update changed this behaviour. Updates are released frequently (1-2 times per month). It looks like we are not handling this event. My theory is that this case was ignored in an old stripe version but now triggers an error.

@RachL I didn't test my theory and I think it would be good to prioritise this work, finding out what changed, just not as s1. What do you think?

**Comment by RachL** [comment]
@mkllnk interesting! Yes let's keep an eye on it and lower the severity for now 👍  Thanks :)

**Comment by Matt-Yorkley** [comment]
That controller is pretty ancient and I don't think we've ever really looked at maintaining it. I didn't even know it existed until recently. We haven't really been actively using it in the app.

There's been some discussion before about using those Webhooks a bit more for things like getting extra payment status change event data but it hasn't been looked at as far as I know.

**Comment by RachL** [comment]
I'm closing this one as we haven't had the issue since. We can reopen if needed.
