### ISSUE TITLE
Product image upload on uk-staging

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7002]
## Description

**Uptdate**: seems related to staging-UK AWS-S3 settings.

Uploading of product images is broken on:
- /admin/products
- /admin/products/new
- /admin/products/<product>/images

Uploading enterprise images on:

- /admin/enterprises/food-on-rails5-hub/edit#/images

Triggers bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6098ec994ba1cf000842270a?event_id=6098ec99007a87ece7990000&i=sk&m=nw

## Expected Behavior

Image upload should work; these should be displayed in the shopfront on the respective products.

## Actual Behaviour

Image upload for products is not working.

## Steps to Reproduce

1. Visit /admin/products/new
2. Try to upload a pic
3. See error 404 on the console

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/db6e80e7-6383-4855-8518-023cfb892804)

## Workaround

-

## Your Environment

* Version used: rails 5.0 upgrade branch
* Browser name and version: Firefox 86 
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by filipefurtad0** [comment]
Staging #6832 in staging-ES revealed that image upload was working fine; this seems related to the UK staging server. Moving to Sysadmin column.

**Comment by drummer83** [comment]
Logo and promo image upload are also not working on UK staging server. Probably related?
Is it working on the "real" (productive) servers? I don't know how to test without creating new users...

**Comment by RachL** [comment]
This is fixed now :muscle:
