### ISSUE TITLE
Payment / Shipment State info missing from admin orders page 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7003]
## Description

After a cash order was placed, Payment / Shipment State info was appearing as missing from the on the admin orders page `/admin/orders?q[s]=completed_at+desc` and on the order edit page. It only appears after the payment was captured.

## Expected Behavior

Payment / Shipment State info should be displayed for complete orders, even if the payment was not captured / pending.

## Actual Behaviour

Payment / Shipment State info is not being displayed, if the payment is not captured or pending.

## Steps to Reproduce

1. Customer: Place a cash order
2. Admin: check that order on  `/admin/orders?q[s]=completed_at+desc` 
3. See the missing info  on payment and shipping state.
4. Capture the payment -> see that the info is now correctly displayed. 

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/b1a1e387-c656-4514-bebe-be944b429f18)

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/25b15b1d-2f1b-4bb6-b338-94fc1c60aaa5)

After capturing the order:
![image](https://user-images.githubusercontent.com/49817236/109845620-42309580-7c45-11eb-87db-daf7a311c200.png)

## Workaround

- 

## Your Environment

* Version used: rails upgrade branch
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by RachL** [comment]
FYI editing the order makes also the states appear correctly.
