### ISSUE TITLE
Missing translation '(includes tax)' on cart page

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#7006]
## Description
The translation key for '(includes tax)' on the cart page is missing.

## Steps to Reproduce
1. Set language to non-English
2. Put item into your cart
3. Go to https://openfoodnetwork.de/cart 

## Animated Gif/Screenshot
![grafik](https://user-images.githubusercontent.com/1790176/109897597-3ff52800-7c93-11eb-8005-f45d755781fb.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
- Version used: v3.5.11
- Browser name and version: Firefox 86
- Operating System and version (desktop or mobile): Desktop Windows 10

**Comment by drummer83** [comment]
I leave you to confirm that this is a s3.

**Comment by sigmundpetersen** [comment]
Yes, missing translations are s3. We also have an epic where we collect all translation bugs.

**Comment by RachL** [comment]
They also are good first issues and need to be added to the welcome new dev board :+1:

**Comment by drummer83** [comment]
Isn't this frontend, @RachL?

**Comment by RachL** [comment]
@drummer83 it's frontoffice, but a backend issue :)

**Comment by stavares843** [comment]
I can reproduce the issue, but going to the strings file all seems correct

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/de_DE.yml#L1477

Any thoughts?

**Comment by drummer83** [comment]
Yeah, there are two occurences. The one which is in the string file is used here:
\openfoodnetwork\app\views\spree\orders\_summary.html.haml
The one which is not translated is used in this file here:
\openfoodnetwork\app\views\spree\orders\_form.html.haml

Unfortunately I cannot open the cart in my test environment (don't know why) so I cannot fix and test it myself.

**Comment by guidoDutra** [comment]
Hello! I'd like to take this issue as my first PR, I talked to Lynne Davis and have been told to comment here to get it assigned to me

**Comment by sigmundpetersen** [comment]
Hey @guidoDutra thanks! I assigned you and moved the issue to 'In Dev' on the Zenhub board.

**Comment by guidoDutra** [comment]
thanks @sigmundpetersen!

**Comment by drummer83** [comment]
Hey @guidoDutra,
sorry,isthis a duplicate which has just been solved?  #7057

**Comment by andrewpbrett** [comment]
Hi @guidoDutra, sorry about that - @drummer83 is correct, this was just fixed. Let me know if you want any guidance on finding another good first issue to work on.

**Comment by guidoDutra** [comment]
No problem @AndrewCleve , I'll pick up another issue later. If you have any recommendation let me know, otherwise I'll choose by myself
