### ISSUE TITLE
ActionView::Template::Error in enterprises#shop

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#701]
## Exception in OpenFoodNetwork

**ActionView::Template::Error** in **enterprises#shop**
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/56301f2f15766f1ee385215c?event_id=56301f2fd144fee232aa52f4)

## Stacktrace

    app/views/shopping_shared/_details.html.haml:5 - _7aaa381981ae5c451e022c3a15aee24d
    app/views/enterprises/shop.html.haml:25 - _6da9ac30b60f975608204f144b66bed3

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/56301f2f15766f1ee385215c?event_id=56301f2fd144fee232aa52f4)

**Comment by mkllnk** [comment]
This is a rare error, but it shows that we use slow and brittle code in our view.
```ruby
        - if current_distributor.logo.exists?
          %img.left{src: current_distributor.logo.url(:thumb)}
```

Paperclip's `exists?` will query the Amazon S3 server to see if the image is actually there. That is load we don't want to have on the server and it failed when Amazon had a problem with their SSL certificate. We should just check if the logo attribute was set:
```ruby
        - if current_distributor.logo?
          %img.left{src: current_distributor.logo.url(:thumb)}
```

It's probably worth doing a `git grep 'exists?'` to find more of these calls.

Depending on the location of the Amazon servers, we could save a few hundreds milliseconds during page load.

**Comment by Em-AK** [comment]
Can this issue be marked as closed ?
It seems to be done https://github.com/openfoodfoundation/openfoodnetwork/commit/d5c4da3bf0ba903fc942a127b7cceeecae803b1d
:clapper:

**Comment by mkllnk** [comment]
Yes. Thanks for the reminder. We just merged that last week.
