### ISSUE TITLE
Max quantity values are not displayed after page reload

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#702]
I go to place an order and set the max quantity on an item, and then place my order - this works. I can go to the reports and see the max quantity for my item(s).

However, when I set the max quantity in the shopfront, and then I reload the shopfront, my max quantity is lost. I expect to see a number, but instead I see a blank quantity input field. So somehow the max quantity is not being loaded from the server and displayed.

**Comment by RohanM** [comment]
Duplicate of #669

**Comment by kirstenalarsen** [comment]
closing as is duplicate
