### ISSUE TITLE
[Rails 5.0] broken payments report

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7021]
## Description

In `https://staging.openfoodnetwork.org.uk/admin/reports/payments` generating a report which is not empty triggers error 500:

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/604222773a55e80018135689?event_id=604222770072f76beaf10000&i=sk&m=nw

## Possible Fix

maybe #7013 will fix this as well?

**Comment by Matt-Yorkley** [comment]
This could be linked to the other two issues, which left the order in the wrong state in regards to payment and shipment states. I think it might be fixed by the same PR I made yesterday...

**Comment by Matt-Yorkley** [comment]
Is there any change if you adjust the date range to only cover older orders (before Rails 5 was staged)?

**Comment by filipefurtad0** [comment]
Yup, it works for other hubs, for orthers placed before Rails 5.0 was staged :+1:  

![image](https://user-images.githubusercontent.com/49817236/110120600-277d2e80-7db5-11eb-8220-deccbc1b6947.png)

Cool, so probably it will be fixed then as well - I'll check this again when testing #7013 :+1:

**Comment by andrewpbrett** [comment]
Closing; See https://github.com/openfoodfoundation/openfoodnetwork/pull/7032#issuecomment-795257163
