### ISSUE TITLE
hangs when opening order cycle on UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#703]
I am sorry to bother you with this but this is a bit critical because Lynne and I are having a detailed technical assessment phone call on monday with the funder we are applying to and it would be great if UK production was working well....
I added in all the Stroudco products to the current order cycle in UK production.  Now the shopfront takes a long time (I stopped counting at 5 minutes) to load and I when I go in as admin, I cannot open the order cycle - it hangs like this:
![hangs on opening order cycle](https://cloud.githubusercontent.com/assets/10517702/10859199/4b4a4d7c-7f53-11e5-98e1-360fcdee3b47.png)

**Comment by NickWeir63** [comment]
As a temporary fix for Monday I just tried replicating an old order cycle, but when I open the order cycle to edit the collection date I get the same hanging problem.

So I tried just editing the dates on an old order cycle and the current one (without opening either of them) but the shopper screen still hangs.

**Comment by NickWeir63** [comment]
This is not the slow loading issue we have had before.....I left the shopper screen opening and 8 hours later it was still showing this:
![hung shopper screen](https://cloud.githubusercontent.com/assets/10517702/10865795/1fe08350-8010-11e5-8223-4048ab1361eb.png)

**Comment by kirstenalarsen** [comment]
can you check if you have any enterprises included in the Order cycle that have not had their emails confirmed? That is an annoying thing that would cause this problem!

**Comment by kirstenalarsen** [comment]
also @mklink has just answered my text and is going to have a look for you. .

**Comment by mkllnk** [comment]
Ok, you can test it again. It seems to be a performance problem. Each page request had a timeout of 30 seconds. The products load in 35 seconds. I set the timeout to 60 seconds now. On the Australian server we set it to 120 seconds.

I also looked into the admin panel. The payment method *Cash or cheque on Delivery/Collection* is bound to the staging environment. It is not active on the production server. That does not block the page load. But it is probably something you would like to fix. There are also some duplicate enterprises you most likely want to delete. That might speed up a bit as well.

**Comment by NickWeir63** [comment]
Great- thank you both very much.  I am very sorry to have interrupted your weekends.  But at least we now have something to show the funders tomorrow!

I have replaced the dodgy payment method 
It was still taking 5 minutes to load the shopping page so I went to de-duplicate the enterprises.  I couldnt see any duplicates so created an excel spreadsheet to list all the enterprises in the '7 Nov' order cycle and then sorted them alphabetically.  the number in column B was the original order they were in in the order cycle - there don't seem to be any duplicates...
![image](https://cloud.githubusercontent.com/assets/10517702/10868162/85505014-807c-11e5-8abf-431124de65e9.png)
@mkllnk please can you tell me which enterprises you think are duplicated and I will delete them

For the time being I have made the '7 Nov' order cycle inactive and created a new one called '7th November' which has fewer enterprises and loads quickly on the shopper screen.  So this is not urgent.

thanks again very much for your help

**Comment by mkllnk** [comment]
@NickWeir63 Sorry, I didn't mean in the order cycle.

If you go to enterprises as admin, you see some duplicates:
* Dean Forest Food Hub
* Dean Forest Food Hub-1
* Stroudco Food Hub-1
* Hodmedods
* Hodmedods-1
* Hodmedods-2
* Howard Stollar
* Howard Stollar-1
* Stroudco Food Hub
* Trehill Farm
* Trehill Farm-1

**Comment by NickWeir63** [comment]
Big thanks to @mkllnk for all your help with this. The conversation with the funder went very well and he had obviously been having a good look at the Storudco shopfront and playing with orders.  Phew!!
He liked OFN a lot! 

I have now added all the Stroudco producers in and the shopfront loads within 2 minutes.
I will sort out the duplicates above by putting the word 'DELETE' in front of the redundant ones (Kirstens suggestion when I spoke to her on Monday).

Thanks all very much -
Nick

**Comment by kirstenalarsen** [comment]
Yay!! come on funder :)
