### ISSUE TITLE
Is OFN working on iPads?

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#704]
We've had a customer letting us know that they couldn't put their order through on an iPad.... Nov 4th.

"I was using your website last night for the first time placing an order with Bondi Food Collective. I was unable to process my order through the checkout using my ipad. I processed it on my work PC this morning with no problem so I'm guessing the website is not set up correctly to process orders using an ipad. Is this something you are able to fix? "

**Comment by kirstenalarsen** [comment]
Hi sally - can you check with them re. what browser and version they were using? Suspect will be safari and hopefully older version (which we’re aware of) but if is different browser and/or later version it may be a new problem

**Comment by sstead** [comment]
"It's an iPad Air 2. When I got to the checkout it wouldn't allow me to put any text in the text boxes for name etc, it also wouldn't allow me to login to my account."

**Comment by sstead** [comment]
Safari - current version.

**Comment by elf-pavlik** [comment]
possibly relevant: #538

**Comment by pmackay** [comment]
@daniellemoorhead given recent discussion on #1013, could this be checked/closed as well?
