### ISSUE TITLE
upgrade to Ruby 2

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#705]

**Comment by flov** [comment]
what's the issue? I just upgraded seemlessly.

**Comment by pmackay** [comment]
When testing this out locally am noticing that this warning is appearing:

`Digest::Digest is deprecated; use Digest`

@oeoeaio do you know what the cause is?

**Comment by oeoeaio** [comment]
Hi @pmackay,

Not sure off the top of my head, but it is on my radar as I have been seeing it too.

**Comment by elf-pavlik** [comment]
everyone here in Berlin uses 2.1.5 as specified in
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/.ruby-version

can you please clarify what exactly it takes to close this issue?

**Comment by daniellemoorhead** [comment]
Actually happened in v1.3
