### ISSUE TITLE
Upgrade rspec-rails to 4.1

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#7050]
### What we should change and why (this is tech debt)
Broken build from dependabot when trying to upgrade.

### Context

https://github.com/openfoodfoundation/openfoodnetwork/pull/7038
#7061

**Comment by sigmundpetersen** [comment]
The build for 4.1.2 looks much healthier #7067 
They also released a 5.0.0 which is dropping support for Rails <5.2, so I'm guessing that broke the build and they reverted those changes into that 4.1.2

We can update the title of this issue to upgrade to 5.0 or just close it and let dependabot try the update after we get to 5.2
