### ISSUE TITLE
Intermittent Test Failures

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#706]
Out test suite fails randomly on certain tests on Travis and our own CI server. They are probably timing issues in the feature specs. We should review these specs and make them stable. One example failure:

```
    As a payment administrator
    I want to capture multiple payments quickly from the one page
 can add a product to an existing order
     Failure/Error: page.should have_selector 'td', text: @product.name
     Capybara::ExpectationNotMet:
       expected to find css "td" with text "Product #288 - 2541" but there were no matches. Also found "Product #289 - 4821 (1g, S)", "$10.00", "", "$10.00", "", "Subtotal:", "$10.00", "", "TOTAL ORDER:", "$10.00", "", which matched the selector but not all filters.
     # ./spec/features/admin/orders_spec.rb:60:in `block (2 levels) in <top (required)>'
```

**Comment by marito59** [comment]
Hi Maikel, I ran into the same issue on a pull request (#707). How did yu bypass the issue (sorry, I am not familiar with Travis)

**Comment by mkllnk** [comment]
If you click on the failed build link, you see five sub-builds in Travis. The first one failed. If you click on that one, you have a little rebuild icon on the right. Or at least I see that button. I clicked on that button and ten minutes later the build should be passed. You probably can't see the failed build any more when you read this. But that's how I would deal with this until we got that solved. You don't need to rebuild the whole thing, only the failed sub-build.

**Comment by marito59** [comment]
Thanks Maikel. Unfortunately it still faills for the same reason. AND I don't have the rebuild button available.

Could it be related to the fact that it builds with Ruby 1.9.3 while apparently master shifter to 2.1.5 ? Apparently Travis push fails because of that.

**Comment by mkllnk** [comment]
We had the same intermittent test failure with Ruby 1.9.3 as well. It's not the version. But it could be a timing issue. Ruby 2 is much faster.

**Comment by mkllnk** [comment]
Closing in favour of https://github.com/openfoodfoundation/openfoodnetwork/issues/2233.
