### ISSUE TITLE
Release v3.6-beta Chioggia Beets

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#7073]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Draft new release] https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-9e565b8903fe04fb40b4
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: ~~https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2283~~ https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2292
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by andrewpbrett** [comment]
Thanks @RachL!

**Comment by Matt-Yorkley** [comment]
Note: we'll need to include #7099 in the release...

**Comment by Matt-Yorkley** [comment]
Redrafted to include #7112, and a couple of minor things like spec changes in between.

**Comment by filipefurtad0** [comment]
Job nr. 3 seems to have aborted with:

```
[BUG] Segmentation fault at 0xfffffffffffffffa
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
```
What do you think @Matt-Yorkley?

**Comment by filipefurtad0** [comment]
Alright, this would be good to go :+1: 

There is discussion for additional patches [here](https://openfoodnetwork.slack.com/archives/CAVTM01QB/p1615834540087900?thread_ts=1615833044.084400&cid=CAVTM01QB).
