### ISSUE TITLE
[Rails 5.2] Deprecation on query arguments

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7089]
This shows up thousands of times and is probably slowing the build a lot:

```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "\"spree_variants\".position ASC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from set_position at /home/runner/openfoodnetwork/app/models/spree/variant.rb:237)
```

Should be a simple fix.

**Comment by luisramos0** [comment]
There are several places of origins:
spec/factories/product_factory.rb:36
app/models/spree/variant.rb:237
app/models/spree/product.rb:55

I am struggling to find the specs that generate these warnings.

**Comment by luisramos0** [comment]
ok, found one spec/features/consumer/shopping/orders_spec.rb:

**Comment by luisramos0** [comment]
yeah, looks like this is all we need for all of them: https://github.com/openfoodfoundation/openfoodnetwork/pull/7098/files
lots of them because it's on product.variants.
