### ISSUE TITLE
[Rails 5.2] Rspec controller syntax deprecations (~100 broken specs)

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7090]
Lots of errors like this in the build:

```
Admin::MatomoSettingsController#update changes Matomo settings
       Failure/Error: post :update, params
       
       ArgumentError:
         unknown keyword: preferences
       # ./spec/controllers/admin/matomo_settings_controller_spec.rb:23:in `block (4 levels) in <top (required)>'
       # ./spec/controllers/admin/matomo_settings_controller_spec.rb:22:in `block (3 levels) in <top (required)>'
```

Rspec syntax has changed in relation to how params and other attributes are passed to get/put/post/delete calls in controller tests.

Reference: https://brandoncaples.com/blog/rails-5-rspec-parameters/

**Comment by luisramos0** [comment]
This is not breaking locally for me...

**Comment by luisramos0** [comment]
ok, got it.

there are 116 errors like "unknown keyword".
the params just need to be sent inside an hash called params, that's it.
This was one is just boring editing of the specs to add the params keyword.

**Comment by luisramos0** [comment]
ok, I started with a couple of them in https://github.com/openfoodfoundation/openfoodnetwork/pull/7097

**Comment by luisramos0** [comment]
I wont be able to come back to this soon.

**Comment by luisramos0** [comment]
this was helpful: https://github.com/rspec/rspec-rails/issues/1650#issuecomment-502403414

**Comment by luisramos0** [comment]
I think #7241 fixes all of these errors.
