### ISSUE TITLE
embedded_shopfronts_spec.rb test fails

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#7129]
#### Description
Test fails
```
1) Using embedded shopfront functionality using iframes redirects to embedded hub on logout when embedded
     Failure/Error: page.has_no_selector? 'div.login-modal', visible: true
     
     Selenium::WebDriver::Error::UnexpectedAlertOpenError:
       unexpected alert open: {Alert text : }
         (Session info: chrome=89.0.4389.82)
     # 0   chromedriver                        0x000000010e88db59 chromedriver + 2595673
     # 1   chromedriver                        0x000000010ef41b33 chromedriver + 9624371
     # 2   chromedriver                        0x000000010e63d773 chromedriver + 169843
     # 3   chromedriver                        0x000000010e69906b chromedriver + 544875
     # 4   chromedriver                        0x000000010e6899f3 chromedriver + 481779
     # 5   chromedriver                        0x000000010e663cd6 chromedriver + 326870
     # 6   chromedriver                        0x000000010e664ba7 chromedriver + 330663
     # 7   chromedriver                        0x000000010e85bb09 chromedriver + 2390793
     # 8   chromedriver                        0x000000010e868bcc chromedriver + 2444236
     # 9   chromedriver                        0x000000010e8686ee chromedriver + 2442990
     # 10  chromedriver                        0x000000010e842832 chromedriver + 2287666
     # 11  chromedriver                        0x000000010e86963f chromedriver + 2446911
     # 12  chromedriver                        0x000000010e851299 chromedriver + 2347673
     # 13  chromedriver                        0x000000010e8808b9 chromedriver + 2541753
     # 14  chromedriver                        0x000000010e893008 chromedriver + 2617352
     # 15  libsystem_pthread.dylib             0x00007fff20573950 _pthread_start + 224
     # 16  libsystem_pthread.dylib             0x00007fff2056f47b thread_start + 15
     # ./spec/features/consumer/shopping/embedded_shopfronts_spec.rb:119:in `login_with_modal'
     # ./spec/features/consumer/shopping/embedded_shopfronts_spec.rb:97:in `block (4 levels) in <top (required)>'
     # ./spec/support/embedded_pages_helper.rb:7:in `block in on_embedded_page'
     # ./spec/support/embedded_pages_helper.rb:6:in `on_embedded_page'
     # ./spec/features/consumer/shopping/embedded_shopfronts_spec.rb:94:in `block (3 levels) in <top (required)>'

Finished in 30.87 seconds (files took 13.2 seconds to load)
3 examples, 1 failure
```
probably due to a native chrome popup that appears:
![Capture d’écran 2021-03-16 à 10.23.50.png](https://images.zenhubusercontent.com/5ff4980976fe25c17e594ba3/d2512070-ce0d-4411-aadf-8f6b6c5f49d9)

#### Expected Behavior
Test should pass.

#### Actual Behaviour
Test fails.

#### Steps to Reproduce
Run test `bundle exec rspec spec/features/consumer/shopping/embedded_shopfronts_spec.rb`

#### Severity
Tech.

**Comment by jibees** [comment]
_**Note:**_ Every time I _quit_ a shop (like `http://localhost:3000/freddy-s-farm-shop/shop`), I have a popup that ask me to confirm
###### Chrome
<img width="411" alt="Capture d’écran 2021-03-16 à 10 38 59" src="https://user-images.githubusercontent.com/296452/111288105-2c0ed600-8644-11eb-8cd6-480335caab0d.png">
###### Firefox
<img width="635" alt="Capture d’écran 2021-03-16 à 10 40 12" src="https://user-images.githubusercontent.com/296452/111288128-30d38a00-8644-11eb-8b0b-eb3bdd940081.png">

**Comment by jibees** [comment]
Seems to be the line that show the popup:
https://github.com/openfoodfoundation/openfoodnetwork/blob/674f0f87a31397c99cb12bcb2bee7eda1240ea76/app/assets/javascripts/darkswarm/services/cart.js.coffee#L96

**Comment by jibees** [comment]
Continue exploring : this popup appears too often since `v3.5.11` (commit f1fca874a129618239eb78352d26307defc562a3)

**Comment by jibees** [comment]
Test on CI seems to fail since 162ae4f : https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2291

**Comment by jibees** [comment]
@openfoodfoundation/core-devs If anyone can handle this? 🙏

**Comment by Matt-Yorkley** [comment]
I had a look yesterday. I noted a few things: 
- it fails locally pretty consistently, not just in CI
- if I add some `sleep(5)` calls between each step in the spec, it reliably passes
- the unexpected alert can otherwise appear in a fairly indeterminate way (after different lines in the code)
- I think if you try to navigate away from the page while Angular is still busy, that's what causes the alert
- it's a tricky one

**Comment by Matt-Yorkley** [comment]
We could just set this spec to pending for now, it's not very high value and we have a lot going on at the moment.

**Comment by sauloperez** [comment]
> I think if you try to navigate away from the page while Angular is still busy, that's what causes the alert

Yes, I think what should be done. Wait for Angular to finish before checking anything.

> We could just set this spec to pending for now, it's not very high value and we have a lot going on at the moment.

As always with embedded shopfronts... it's the ugly duckling of our features...

**Comment by lin-d-hop** [comment]
Embedded shopfronts were deprecated long ago.

Should I explore the product side of removing the code?

**Comment by sauloperez** [comment]
> Should I explore the product side of removing the code?

YES PLEASE

**Comment by lin-d-hop** [comment]
Embedded groups functionality is not deprecated.

So any removing of embedded shopfront code will need to still ensure embedded groups is functional.

Can anyone share any thoughts on whether this is do-able or difficult? I would HATE to inadvertently create a bunch of issues around embedded groups while doing this work.

**Comment by sauloperez** [comment]
then it sounds the best we can do is @Matt-Yorkley suggested and temporarily skip that flaky spec.
