### ISSUE TITLE
Compute unit price in Inventory

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#7139]
### Description
**- As an:** enterprise user
**- On page:** /admin/inventory
**- I want to be able to do:** See the price of a single unit when viewing my inventory products.

As we've done for the shopfront, the aim of this issue is to display right values of unit prices in the back-office, since the frontend part has been done with #6496.

### Reference

- If enterprise user (=shop/hub) is using inventory to create a different price,  display unit price from product inventory (because the inventory unit  price overwrites the product list unit price )

_And_

- if the enterprise user is a reseller (buy and sell a product with a markup) the unit price of the product should adjust to the new price including the markup

See #6449

**Comment by jaycmb** [comment]
Put on hold, as discussed in Delivery Circle.
Waiting until after product Uplift -

    or not as inventory is to be phased out
