### ISSUE TITLE
en-GB translation strings missing

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#715]
Mentioned first in #713.

**Comment by NickWeir63** [comment]
Do we need to ask for Aus help on this or will they pick up on the bug label?

**Comment by pmackay** [comment]
@NickWeir63 have created a PR - if Aus can merge to master I can push to staging.

**Comment by oeoeaio** [comment]
Pinging @mkllnk

**Comment by mkllnk** [comment]
@pmackay I'm working on automated commits of the Transifex translations to a separate branch in our repository. But I noticed that Transifex uses `en_GB` instead of `en-GB`. Do you have any concern changing the name of the locale to `en_GB`?

**Comment by pmackay** [comment]
Would changing the file to `en_GB` fix the problem of the strings not being picked up in JS? Isnt Transifex just about creating the translations?

**Comment by pmackay** [comment]
My last comment was before I read https://github.com/openfoodfoundation/openfoodnetwork/pull/716#issuecomment-159748883. So I dont have a problem changing the file to `en_GB` if it doesnt affect anything else. Would that mean the `application.yml` files need changing to use that as the locale?

**Comment by NickWeir63** [comment]
@pmackay 
 is it OK for us to close this now?
thanks for all your work on this
