### ISSUE TITLE
Fatal errors in OrderCycleManagement report

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7154]
## Error in OpenFoodNetwork UK

**ActiveRecord::StatementInvalid** in **spree/admin/reports#order_cycle_management**
PG::AmbiguousColumn: ERROR:  column reference "state" is ambiguous
LINE 1: SELECT DISTINCT spree_orders.*, CASE WHEN state IN ('cancele...
                                                  ^
: SELECT DISTINCT spree_orders.*, CASE WHEN state IN ('canceled', 'returned') THEN payment_total
     WHEN state IS NOT NULL THEN payment_total - total
ELSE 0 END
 AS balance_value, spree_orders.* FROM "spree_orders" INNER JOIN "spree_payments" ON "spree_payments"."order_id" = "spree_orders"."id" INNER JOIN "spree_payment_methods" ON "spree_payment_methods"."id" = "spree_payments"."payment_method_id" AND "spree_payment_methods"."deleted_at" IS NULL LEFT OUTER JOIN spree_line_items ON (spree_line_items.order_id = spree_orders.id) LEFT OUTER JOIN spree_variants ON (spree_variants.id = spree_line_items.variant_id) LEFT OUTER JOIN spree_products ON (spree_products.id = spree_variants.product_id) WHERE "spree_orders"."state" IN ('complete', 'canceled', 'resumed', 'awaiting_return', 'returned') AND ("...

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/605342dac8953d0007bca274?event_id=605343150074ee6b113c0000&i=gh&m=ci)

## Stacktrace

    lib/open_food_network/order_cycle_management_report.rb:83 - table_items
    app/controllers/spree/admin/reports_controller.rb:63 - order_cycle_management

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/605342dac8953d0007bca274?event_id=605343150074ee6b113c0000&i=gh&m=ci)

*Created by Admin OFF via Bugsnag*

**Comment by sauloperez** [comment]
closed by #7177
