### ISSUE TITLE
Editing cancelled orders introduces discrepancies on customer balance and stock management

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7164]
## Description

As admin, editing cancelled orders has been observed to introduce discrepancies in:

- customer balance - #7165 
- stock management - #7166 

These result from performing operations such as changing:

- the line items - changing quantity and introducing/removing variants
- shipping methods (with fees)
- adjustments (adding/removing)
- capturing payments 

## Expected Behavior

The functionality to `edit` and view the order (namely to refund payments) should be kept, but:
If the status of the order is `cancelled` introducing changes affecting order total and stock of line items, should not be possible. To do this, the order must be resumed (i.e., not cancelled).

## Actual Behaviour

Even though the status of the order is `cancelled`, editing and introducing changes affecting order total and stock of line items is currently possible, without having to `resume` the order.

## Steps to Reproduce

As admin
1. Cancel an existing order (needs to be non-shipped)
2. Edit the order
3. Change line items quantity; make adjustments; capture payments
4. Notice discrepancies on customer balance and stock.

## Workaround

-

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v3.6.8
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by filipefurtad0** [comment]
I've organized this on an epic to reflect that:
- If we address the Expected Behavior on this epic, both underlying issues are closed;
- If we don't or if the current and Actual Behavior is a requirement which should be kept, then the underlying issues can be dealt with separately.

This needs @openfoodfoundation/train-drivers-product-owners feedback. Please see [also discussion](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1616146474003400).

**Comment by andrewpbrett** [comment]
Both issues are closed, I'll close the epic 🎉
