### ISSUE TITLE
i18n of spree customizations

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/openfoodnetwork#717]
Instructions from @mkllnk 

> You will need angularjs knowledge to internationalise
> Javascript templates. Here is a little guideline:
> 1. Identify all Rails template files that can contain text:
>    `find app/views/admin/ -name '*.haml'`
> 2. Go through all of them and look for text. Replace the text by a call
>    of the translate function alias `t`. There are heaps of examples in
>    commit 85c99102dd65f1a4785bbaa3f971d7c3e771553e. The `t` function is
>    called with a key. That key has to be put into en.yml with the replaced
>    text.
> 3. Include the I18n object and the translation code in the Javascript
>    admin module. Currently it's only in the darkswarm module:
>    - app/assets/javascripts/darkswarm/i18n.js.erb
>    - app/assets/javascripts/darkswarm/i18n.translate.js.coffee
>    - app/assets/javascripts/darkswarm/filters/translate.js.coffee
> 4. Identify all Javascript templates that contain text:
>    `find app/assets/javascripts/admin/ -name '*.coffee'`
> 5. Go through all of them and replace text. Depending of the context,
>    you can use the angular filter called `t` or the global function called
>    `t`. There are examples of using the `t` function in commit
>    ae9654111226ca69513331c08c274db7dc8d4b84. But that commit contains some
>    bad examples of the filter call. That was improved in commit
>    5f8004385749fae28249a61c25a8feac8d14cfde.
> 
> A final note on naming the translation keys (left side in en.yml). I
> have used a simple flat structure for keys. For example, a key is named
> `email_not_found`. But it is possible to group keys that belong
> together. Maybe you want to experiment with that and find a better
> structure. For example, you could group all the admin translations by
> naming them `admin.enterprises` instead of just `enterprises`. You
> definitely want to read the i18n Rails guide first:
> http://guides.rubyonrails.org/i18n.html

**Comment by mkllnk** [comment]
Another little addition: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Angular-and-OFN#i18n---using-translation-features

Feel free to ask questions here.

**Comment by mkllnk** [comment]
There was a question about the files in `app/assets/javascripts/templates/admin/`. You can use the Ruby `t` function or the Angular `t` filter in these files. The difference is when the translation is done.

If you use the Ruby `t` function, the translations are done during pre-compilation of assets on the server (in staging and production environment only). This is more efficient. But changing the language requires re-compiling assets.

If you use the Angular `t` filter, the translations are done in the browser. This provides the flexibility to let the user choose the language later. I think it would be better to go this way.

**Comment by wvengen** [comment]
[i18n-js](https://github.com/fnando/i18n-js) could be useful here

**Comment by elf-pavlik** [comment]
from https://github.com/openfoodfoundation/openfoodnetwork/commit/7a4f0e214cc10094775bd6a98742d01adcbe70e6#commitcomment-14949747

> I would suggest pulling the translation filters out into a separate angular module (maybe 'i18n' or 'ofn.i18n'?), which can then be specified as a dependency for the darkswarm (front end) module and for each admin module that requires it (probably most of them).

> This is the same pattern we use to include particular angularjs libraries that we use (eg. pasvaz.bindonce, ng-resource, textAngular, etc.)

> You could alternatively create a translations filter within each individual admin module, with only the translations required for that module, but that feels harder to maintain and not very DRY...

**Comment by mkllnk** [comment]
@oeoeaio's comment on a separate module for the translation stuff would be a good way to go with our current code. i18n-js module that @wvengen posted could be a replacement for our custom code. You can try it if you have time. But we might need to adjust the already internationalised views.

**Comment by elf-pavlik** [comment]
I just noticed validation message in model which has some non translated string: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/enterprise_role.rb#L6
We should also search more of them!

Also some mailers 
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/producer_mailer/order_cycle_report.text.haml

**Comment by elf-pavlik** [comment]
> If you use the Angular t filter, the translations are done in the browser. This provides the flexibility to let the user choose the language later. I think it would be better to go this way.

We had chat with @nanoharsha on slack that they may need to allow switching languages on the same instance for their India deployment. Maybe we can close this issue and start new one to discuss how this would work?

**Comment by myriamboure** [comment]
@elf-pavlik @nanoharsha see the first comments on that here: http://community.openfoodnetwork.org/t/internationalisation-project-notes/312/104?u=myriamboure

**Comment by RachL** [comment]
I think this issue can be closed now. @mkllnk @myriamboure do you agree?

**Comment by mkllnk** [comment]
Yes, we have a few untranslated strings but we open separate issues for those.
