### ISSUE TITLE
Payment & Shipping Method Filters for Order Cycle Management Reports not working

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7176]
## Description

View https://openfoodnetwork.org.uk/admin/reports/order_cycle_management

Entering a filter into either the Payment Method or Shipping Method fields and try to down load a report results in the Slug error message.

Both the Payment Method and Delivery reports can be accessed if no filters are applied for Payment/Shipping Method.

## Expected Behavior

Data for Delivery and Payment Method reports can be filtered by customer Payment & Shipping Method.

## Actual Behaviour

Data for Delivery and Payment Method reports can not be filtered by customer Payment and Shipping Method.

## Steps to Reproduce

1. Visit https://openfoodnetwork.org.uk/admin/reports/order_cycle_management
2. Select a hub
3. Enter a filter into the 'payment method' field
4. Select 'Payment Method report'
5. Click 'Search'
6. Observe the Slug Screen
7. Repeat with a filter in the 'Shipping Method' field.
8. Observe the slug screen
9. repeat both steps choosing the 'Delivery Report'
10. Observe the slug screen

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by filipefurtad0** [comment]
The bugsnag errors seem to point to issue #7154 - the steps to reproduce are useful to check, when fixing this :+1:

**Comment by RachL** [comment]
This is fixed by #9032 @filipefurtad0 that's why I'm putting this in test ready. We can close when the PR is merged.
