### ISSUE TITLE
Shipping fees should update after I make an adjustments to an order (in order, or in BOM)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#718]
Currently, shipping fees do not update after an order is adjusted in either single order edit, or BOM. This applies to shipping fees that are not a set fee, but calculate based on the order total (such as a % fee).

**Comment by RachL** [comment]
I didn't manage to reproduce this (aside from other opened bugs as https://github.com/openfoodfoundation/openfoodnetwork/issues/3661). Maybe at the time of the issue the button updating fees did not existed? So I'm closing this.
