### ISSUE TITLE
[Rails 5.2] Order Workflow Problem?

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#7188]
Rails 5.2 build error:

```
 115) Spree::Admin::Orders::CustomerDetailsController#update adding customer details via newly created admin order when adding details of a registered user redirects to shipments on success
       Failure/Error: save!
       
       ActiveRecord::RecordInvalid:
         Validation failed: Count on hand must be greater than or equal to 0
       # ./app/models/spree/stock_item.rb:27:in `block in adjust_count_on_hand'
       # ./app/models/spree/stock_item.rb:23:in `adjust_count_on_hand'
       # ./app/models/spree/stock_movement.rb:22:in `update_stock_item_quantity'
       # ./app/models/concerns/variant_stock.rb:117:in `move'
       # ./lib/open_food_network/scope_variant_to_hub.rb:52:in `move'
       # ./app/models/spree/stock_location.rb:47:in `move'
       # ./app/models/spree/stock_location.rb:43:in `unstock'
       # ./app/models/spree/shipment.rb:290:in `manifest_unstock'
       # ./app/models/spree/shipment.rb:193:in `block in finalize!'
       # ./app/models/spree/shipment.rb:193:in `each'
       # ./app/models/spree/shipment.rb:193:in `finalize!'
       # ./app/models/spree/order.rb:402:in `block in finalize!'
       # ./app/models/spree/order.rb:400:in `finalize!'
       # ./app/services/order_workflow.rb:33:in `advance_order'
       # ./app/services/order_workflow.rb:9:in `complete'
       # ./app/controllers/spree/admin/orders/customer_details_controller.rb:26:in `update'
       # ./spec/support/controller_requests_helper.rb:49:in `process_action_with_route'
       # ./spec/support/controller_requests_helper.rb:27:in `spree_post'
       # ./spec/controllers/spree/admin/orders/customer_details_controller_spec.rb:55:in `block (5 levels) in <top (required)>'


```

### Possible fix
It looks like a problem in the order workflow:
 def advance_order(options)
In the step payment,
break unless order.next
order.next returns true but the order is still in the payment state.
The error in the spec is related to stock because the stock keeps getting reduced but I think the problem is in the workflow logic.

**Comment by Matt-Yorkley** [comment]
Looks like there's quite a few issues with locking, which happens a lot in the checkout workflow.

I did a bit of debugging on these errors:
```
CartController basic behaviour tells cart_service to overwrite
      Failure/Error:
            order.with_lock do
              EnterpriseFee.clear_all_adjustments order
        
              create_line_item_fees!
              create_order_fees!
        
              order.updater.update_totals
              order.updater.persist_totals
            end
      
      RuntimeError:
        Locking a record with unpersisted changes is not supported. Use `save` to persist the changes, or `reload` to discard them explicitly.
```
I checked `order.changed?` and `order.changes` at that point, which shows: `"last_ip_address"=>[nil, "0.0.0.0"]`.

When we load the current order in lots of places, we use this helper method, and it's both loading the order and then changing the `last_ip_address` without persisting it:

https://github.com/openfoodfoundation/openfoodnetwork/blob/3ed8dbe3b33e6c90fed95652aef4b7bef67c0464/lib/spree/core/controller_helpers/order.rb#L55

So when we come to lock it any point (which we do in lots of places) it now _doesn't want to be locked_ with those unpersisted changes present.

**Comment by Matt-Yorkley** [comment]
Okay, this order workflow thing is bananas. It can be seen quite well in `spec/services/order_workflow_spec.rb`.

When transitioning through _most_ order states, everything is fine. When transitioning specifically from `payment` to `complete`, the transition happens, the after_transition hook gets called (`after_transition to: :complete, do: :finalize!` in `Order::Checkout`), but at the point that `finalize!` is called, `order.state` is still `"payment"`. :thinking:

It doesn't change to complete even though the transition has happened, or at least the value doesn't get persisted on the order object..? I looked through various Spree issues and commit notes in various versions, and they don't seem to have encountered this specific problem.

Looking through the remaining spec failures, I think a large number of them are caused by this issue. I spent a fair bit of time playing with this one, but didn't manage to crack it.

**Comment by luisramos0** [comment]
wow, I tired removing all extra things from the workflow, including the finalize method of the order. no luck.

Spec spec/services/order_workflow_spec.rb:43 is the spec to look at this.

The workflow doesnt work when its moving from payment to complete. the callback after_transition is called with payment, not complete.
I tried to find a diff from master while debugging like in find_transition and go_to_tate method.  no luck.

I ended my effort by upgrading state_machines-activerecord: https://github.com/openfoodfoundation/openfoodnetwork/pull/7264
still no luck :man_shrugging:

**Comment by luisramos0** [comment]
I think we need to debug state_machine next method itself...

**Comment by Matt-Yorkley** [comment]
Yeah it's pretty crazy. I had a quick look at `StateMachine#next` with byebug, but didn't get anywhere. I wonder if there might be a method naming conflict somewhere, like if a core Rails class now has a `#complete` method..?

Explicitly setting `order.state` to "complete" in the after_transition hook seems to fix it, but obviously that's a crazy solution...

**Comment by luisramos0** [comment]
do you mean on "after_transition do |order|" in checkout? I tried to force complete there and it was not working. I mean, this is not working:
order.state = order.state

**Comment by Matt-Yorkley** [comment]
Hmmm.... `#finalized?` and `#completed?` are both methods that are provided by `ActiveRecord`. I  wonder if there's a clash there?

**Comment by luisramos0** [comment]
Thats a good hint. We can try to rename the order state complete to
something else.

**Comment by andrewpbrett** [comment]
> #finalized? and #completed? are both methods that are now provided by ActiveRecord

Could you explain how you found this @Matt-Yorkley? If I do `order.completed?` on this branch it's calling the method we define here: https://github.com/openfoodfoundation/openfoodnetwork/blob/2ee15838d9fdddb51468c1b5d7d6efe39dcf8d9a/app/models/spree/order.rb#L187

and if I call `order.rolledback?` I get an undefined method error.

**Comment by Matt-Yorkley** [comment]
Ah, it looks like they're only available on the object's transactions via `order.transaction.rolledback?`. False alarm.

**Comment by andrewpbrett** [comment]
I was definitely not looking forward to changing the name of that state if that was in fact the problem 😆
