### ISSUE TITLE
Learning and documenting buildkite deployment to UK servers

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#719]
At today's skype we talked about the best way for @stveep to deploy his work on stock levels to UK staging.  We talked about whether all UK developers should be able to deploy or if we want one person to co-ordinate it.  We also talked about how important it is to document the deployment process on discourse so that other people can follow it in future.  We agreed:
1) that I would ask @pmackay if he would be able to talk this through and if so
2) that we would arrange a skype for @pmackay , @stveep, @mkllnk and possibly @lin-d-hop to talk through the questions above
3) that @kirstenalarsen would talk to @mkllnk and ask him to confirm whether the documentation should go onto a current discourse link or if we should start a new one

Thanks all

**Comment by pmackay** [comment]
Happy to have a chat. Might be useful if @mkllnk could clarify who can access Buildkite? (cannot remember the license issues). 

Suggest deployment process notes go here https://github.com/openfoodfoundation/ofn_deployment/wiki/Deployment-with-Buildkite. I've added a description of how to use the UK projects.

**Comment by mkllnk** [comment]
We pay $7.50 USD per user per month for using Buildkite. Lynne and Paul, you both have accounts. Should we give Steve one as well?

If you choose to have one co-ordinator, you would need only one account which saves a bit of money.

I can add some notes to the [deployment project](https://github.com/openfoodfoundation/ofn_deployment/wiki/Deployment-with-Buildkite) how it works.

**Comment by mkllnk** [comment]
Hey, just saw that @pmackay documented the UK projects on Buildkite already. Do you need any more details on how it works?

Would you like a chat with me about the deployment? We could have a Skype chat next week. But you can also post any questions here or email me.

**Comment by stveep** [comment]
Paul and I discussed this and we think it's probably not worth me having my own account - at least in theory it's all automated and won't require much manual action. I think I'm clear now on what to do so closing this.
