### ISSUE TITLE
Implement and use feature toggles with flipper

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#7193]
#### Goal
The aim of this issue is to install flipper UI inside the app and use it for Unit Prices feature.

#### Context
As discussed here: #6998, we think it's now time to have a simple UI to manage feature toggle as needed behavior seems to become more and more complex. 
Flipper (https://github.com/jnunemaker/flipper) seems to be the perfect tool to start with.

Sources:
 - https://docs.google.com/document/d/1P3j2i9T1NVx2dguzTofrOmLzMG4eIR3KcN5RVdDcLcY/edit
 - https://docs.google.com/document/d/1ekLdGbvUeW_m0tprOK_19t1LxyK0WxsCn1xlcyojJGY/edit

**Comment by sauloperez** [comment]
This should enable us to close #6870 as well, one way or another.

**Comment by jibees** [comment]
@sauloperez 
Should we restrict the flipper UI with a basic authentification like this:
```ruby
 Rack::Auth::Basic
```
view: https://github.com/jnunemaker/flipper/blob/master/docs/ui/README.md#basic-authentication-via-rack
?
Or `user.admin` is enough? I guess so, but I need to confirm.
Thanks. 🙏

**Comment by sauloperez** [comment]
I would stick to user.admin which will grant access only to superadmins. That's already the case for the Delayed Job web UI
https://github.com/openfoodfoundation/openfoodnetwork/blob/0c182c4606c6ff22f28a8eaff797a13e4d1a9169/config/routes/admin.rb#L4-L5

**Comment by jibees** [comment]
And that's where _Flipper_ is mounted.

https://github.com/openfoodfoundation/openfoodnetwork/blob/0c182c4606c6ff22f28a8eaff797a13e4d1a9169/config/routes/admin.rb#L4-L6

**Comment by sauloperez** [comment]
sure, I just wanted to show that's the approach we follow already :ok_hand:
