### ISSUE TITLE
Reorganise order 'invoice' 'print' resend' action buttons for clarity

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#720]
Enterprise users can generate printable invoices from inside an order. They have three options from within an order:
- (when not in edit mode) - can 'print' which will create pdf in new tab
- (when in edit mode) - can 'resend' email in template to customer; can 'invoice' which sends email with printable invoice as attachment

This is confusing - which button is where and why

Can we have an 'action dropdown' that appears both when you are in edit or non-edit mode that enables (my suggested naming)
- print to pdf
- email pdf attachment
- email order details

**Comment by sstead** [comment]
@oeoeaio 
Yes, the dropdown works.
Only thing, you want both bottons?
![image](https://cloud.githubusercontent.com/assets/10843056/11830452/70a8676e-a3f9-11e5-9098-8a8a2ca84caf.png)
