### ISSUE TITLE
ExampleException in home#example

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#7201]
## Test error in Example.com

**ExampleException** in **home#example**
Something really bad happened

[View on Bugsnag](http://app.bugsnag.com/errors/example/events/example?i=gh&m=te)

## Stacktrace

    app/controllers/home_controller.rb:123 - example
    app/controllers/other_controller.rb:12 - broken
    lib/important/magic.rb:4 - load_something

[View full stacktrace](http://app.bugsnag.com/errors/example/events/example?i=gh&m=te)

*Created by OFN Canada via Bugsnag*

**Comment by sigmundpetersen** [comment]
Closing, same reason as in https://github.com/openfoodfoundation/openfoodnetwork/issues/11071#issuecomment-2125948713
