### ISSUE TITLE
Build Action Field Component (Styleguide 1.0 | Product List)

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#7203]
**- As a enterprise user**

**- On page:** Product List Page https://openfoodnetwork.org.uk/admin/products 

**- I want to be able to do:** 
I want to edit, delete and clone **individual** products.
I want to delete **multiple** products at once using a global action field.

**Action Field**
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/27fb4e55-704b-4306-a940-f174913cb52d)

**Global Actions Dropdown**
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/f5a260de-22c3-4e5a-991b-2c5181b82e6a)

**Individual Actions Dropdown**
For Product
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/94c06883-38d0-4684-b6b7-465d8397cdce)
For Variant
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/ac104277-0435-4bd3-941e-59a46653e31a)

## Acceptance Criteria & Tests

**Behaviour**

- If user clicks on the action field, the dropdown expands 
- If user clicks anywhere outside the action field or the dropdown, the dropdown closes without any option executed
- If user selects _'edit'_, the product edit page opens https://openfoodnetwork.org.uk/admin/products/avocado-38/edit
- If user selects _'clone',_ the a copy of the product is created below (named COPY OF [Product Name])
- If user selects _'delete_', an alert pops up 'Are you sure you want to delete this?'. If user clicks _'cancel',_ pop closes and product gets not deleted. If user click _'delete'_, pop closes and product gets deleted.

1.
2. 
3. 
4.

**Designs are here:**
https://www.figma.com/file/kBvKYXnaNU0thSnKJUoyup/Product-List-UI-uplift?node-id=10%3A1351

**Comment by jaycmb** [comment]
In the designs I couldn´t find an indication for this field in use.
@kirstenalarsen please doublecheck if the AC describe the intended behaviour correctly. 
@Erioldoesdesign I believe we miss a design for the alert, if a user is about to delete a (list of) product(s).

**Comment by Erioldoesdesign** [comment]
> In the designs I couldn´t find an indication for this field in use.
> @kirstenalarsen please doublecheck if the AC describe the intended behaviour correctly.
> @Erioldoesdesign I believe we miss a design for the alert, if a user is about to delete a (list of) product(s).

It was in a weird place in the file (the last page) I added it into the 'Producer - edit fields' page in figma and looks like this:

<img width="630" alt="Screenshot 2021-03-24 at 17 04 59" src="https://user-images.githubusercontent.com/11681324/112352979-2b6ce400-8cc3-11eb-86bf-0812a6b85a39.png">

**Comment by kirstenalarsen** [comment]
I think that is right - should probably have a product/s  and it/them for the plural product delete?
