### ISSUE TITLE
Adjustments to Lettuceshare report

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#722]
Change columns in lettuceshare report.
- Remove values in Unit Price column (not needed) and make data currently going to Totals column show in Unit Price Column... leaving Totals column blank. [For lettuceshare users, the 'QTY' column and the 'Totals' column are blank, and that program puts sums in place to complete the math.]
- make it so that variants don’t appear if they are set to 0 in inventory (including in override inventory) (or ‘hide’)

**Comment by sstead** [comment]
Problem: The Lettuceshare report is looking at the 'on hand/on demand' status of the product, not the variant. Further, there is a value in the system which I can't see that is also impacting on this. For instance I can have two products set to 'on demand' but one will show in the report, another will not. I think it has something to do with historical on hand values assigned to the product. A new product - that's always been 'on demand' will never show in report.

Which products should be visible?- If the E2E permission exist between hub and producer to 'manage products', 'add to order cycle' and 'VO'.... you won't necessarily see products in the Lettuce Share reports. you will only see them once that producers has been added to an order cycle. A new producer's products won't show (if owned by someone else, and only linked by E2Es)

**Comment by sstead** [comment]
It appears that the Lettuce share report looks at the Price and On hand value of the producer's product, not the variant override

**Comment by sstead** [comment]
These notes are for future reference more than anything:
![image](https://cloud.githubusercontent.com/assets/10843056/11828442/e3fbb9d4-a3e8-11e5-8ca5-74179aa6fa49.png)
![image](https://cloud.githubusercontent.com/assets/10843056/11828445/e6fd9c4c-a3e8-11e5-80a8-a8a672965e12.png)
![image](https://cloud.githubusercontent.com/assets/10843056/11828448/f042abe4-a3e8-11e5-878e-50644fe2aa79.png)

**Comment by kirstenalarsen** [comment]
@mkllnk my bad - hadn't updated the issue description following discussion with lisa about sku. Lettuceshare reads in in a very specific way so adding extra columns breaks everything :) @oeoeaio reverting so that no sku in this report
