### ISSUE TITLE
UI regression: font formatting regressions

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7220]
## Description

Several pages in the BO are displaying an incorrect font.

## Expected Behavior

Fonts should be consistent throughout the app.

## Actual Behaviour

In some pages a serif font is being displayed (see pics below).

## Steps to Reproduce

The search was not exhaustive but visiting the pages below as admin will reveal some. A more thorough search can be performed, if needed.

## Animated Gif/Screenshot

**Orders page**
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/ebefdaa4-3e6d-4842-be9a-709518bf3162)

**Editing an order**
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/3c27b7fd-43a4-4be6-9d11-778ce8ce1803)

**Editing an order -> Return authorizations tab**
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/36f3840c-0010-47eb-8349-88ca61c26097)

**Subscriptions**
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e88ea82e-b0ab-4457-8be1-3ec6e4b8b57e)

**Bulk order Management**
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/775b9b08-ebb1-4cc1-88ba-b1019e02b83f)

## Workaround

Does not interfere with functionality.

## Severity

s3

## Your Environment

* Version used: v3.6.... current master.
* Browser name and version: latest Firefox and Chrome
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

I'm pretty sure this was introduced between these builds:

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2367 (regression not observed)

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2374  (regression observed)

**Comment by filipefurtad0** [comment]
Not related to Unit Prices either; after disabling the feature this is still observed, for example:

![image](https://user-images.githubusercontent.com/49817236/112622082-6e919900-8e22-11eb-8a08-03e0507ce964.png)

**Comment by jibees** [comment]
Not exactly related to unit price feature (enabled or not) but certainly due to css modifications i've made.
I'll investigate.

**Comment by jibees** [comment]
I've already created this #7214: I close it, since yours is better documented.
