### ISSUE TITLE
Line items missing from previously placed orders

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7225]
## Description

Found while testing #6956, but not necessarily related. Possible s2 regression, needs clarification before next release.

Some previously placed orders are not displaying the line items; the order total is correct. See pic below.

## Expected Behavior

Customers should be able to view the line items on previously placed orders correctly.

## Actual Behaviour

Customers are not able to view the line items on previously placed orders correctly, in some cases - this needs investigation to track down which cases.

## Steps to Reproduce

1. As a customer, visit /account#/orders
2. Pick an order, and click "View"
3. In some cases (which ones??) line items are completely gone

## Animated Gif/Screenshot

Comparison between admin view of an order and customer view of the same order (order is from staging-ES):

![image](https://user-images.githubusercontent.com/49817236/112527192-af45cf80-8d9a-11eb-8115-297aa15a9134.png)

## Workaround

-

## Severity

Looks like an s2 regression.

## Your Environment

* Version used: observed on https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2374
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

Needs investigation.

**Comment by Matt-Yorkley** [comment]
It looks like this is broken when the unit price feature toggle is on, and fixed when it's off.

**Comment by jibees** [comment]
I should take a look then.

**Comment by filipefurtad0** [comment]
I think this is not related to unit prices. I reproduced the issue as follows:

- I disabled the unit price feature in staging-UK (commented this out):

![image](https://user-images.githubusercontent.com/49817236/112618652-4142ec00-8e1e-11eb-9e02-dd08bacde153.png)

And removed the users from the beta-testers, so that in the shopfront the unit price is not showing:

![image](https://user-images.githubusercontent.com/49817236/112618849-7c451f80-8e1e-11eb-96ae-1a4c7973dfb3.png)

And restarted unicorn.service.

Then:
1) Customer: placed an order in the shopfront
2) Admin: deleted the items from `/products` (I think the items need to be deleted - I'll check and update this line)
3) Admin: closing the OC from which these line items were purchased
4) Customer: visit `/account#/orders` and see the missing items in the order

![Peek 2021-03-26 10-25](https://user-images.githubusercontent.com/49817236/112619208-f2e21d00-8e1e-11eb-99c7-a62e55eb3b51.gif)

**Comment by andrewpbrett** [comment]
I was able to reproduce this by deleting a product that was on an existing order. I confirmed that the product does not appear on the customer's view of the order, but does appear on the admin view of the order (this is due to our old friend, the fact that the admin view is using the order's shipment manifest, which may be out of sync with the order's line items). 

I checked out v3.5.10 and it happens on that version as well. So it looks like this is unrelated to anything we've changed recently, unless it's now happening for other cases besides the product being deleted. 

@filipefurtad0 were you able to find any other scenarios where this bug appears?

**Comment by Matt-Yorkley** [comment]
> I checked out v3.5.10 and it happens on that version as well. So it looks like this is unrelated to anything we've changed recently

That's super weird. I can toggle the unit prices feature on and off in `es-staging` and it makes the line items appear and dissapear in order `R738338024`. Are there two overlapping bugs here..?

> I was able to reproduce this by deleting a product that was on an existing order. I confirmed that the product does not appear on the customer's view of the order, but does appear on the admin view of the order

So I think we're talking about these lines in this view:
https://github.com/openfoodfoundation/openfoodnetwork/blob/19c2c9c1c5d80f6293561c81ea7568522578571e/app/views/spree/orders/_form.html.haml#L19-L21

And it looks like it's accessing variants via line items. I guess in this case the variants are soft-deleted and not picked up... they should be found via this bit of code (although admittedly it looks a bit shady):

https://github.com/openfoodfoundation/openfoodnetwork/blob/19c2c9c1c5d80f6293561c81ea7568522578571e/app/models/spree/line_item.rb#L162-L167

**Comment by andrewpbrett** [comment]
I think this line is actually the culprit: https://github.com/openfoodfoundation/openfoodnetwork/blob/19c2c9c1c5d80f6293561c81ea7568522578571e/app/views/spree/orders/_summary.html.haml#L14

We call `sorted_by_name_and_unit_value` which scopes to non-deleted products.

**Comment by Matt-Yorkley** [comment]
Cool, a unit test for soft-deletion on that scope would be a good place to start then. It looks like it's only used in two places, and they probably both want to included deleted products :+1:
