### ISSUE TITLE
Order confirmation email subject lines 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#723]
- Email subject line when sent to customer - somehow more personalised to Food hub they ordered from - e.g. "thanks for ordering at XX on the Open Food Network" ???

**Comment by sineadfenton** [comment]
Hey,

We had a request for this come up again not so long ago. Think it would be really useful for users, as well as adding an element of personalisation which I think both user/seller will benefit from.

Cheers,

Sinead

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Order Confirmation Emails](https://trello.com/c/GbyrU43C/15-order-confirmation-emails)

**Comment by lin-d-hop** [comment]
While this is needed, it is a feature and needs to be specced properly and pumped through the feature pipe. Closing.
