### ISSUE TITLE
Editing an OC removes products

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7234]
## Description

Enterprise ID: 201467

Clone OC-> creates a copy with all the products in the original
Example OCs: 207822, 207807

Edit the cloned OC -> all bar 4 products are removed.
Visit the incoming products page and see that there are '0/0' products selected for the supplying enterprises.
Look at a supplier-> they have products listed and their enterprise settings is down as 'Producer'
Enterprise permissions remain in place.

**Cloned OC contains 'Doro's Flowers' which has no products listed.  It shouldn't be possible for this to have been added to the incoming section of the OC** 

Create a new OC and add in producers one by one and then edit to see when/if all products removed.
Added all supplying enterprises which were in the original OC (apart from Doro's flowers which I can't add as it has no products) to new OC.
Save and back to list
Edit OC
Products remain

## Expected Behavior

Clone an order cycle and the edit.  Products remain in the order cycle.
Enterprises with no products listed are not present in the incoming section of an OC.

## Actual Behaviour

Clone an order cycle which contains an enterprise with no products listed.
Edit this OC
All products are removed from the OC

## Steps to Reproduce

1. Clone OC 207719
2. Edit the new OC
3. observe Doro's flowers listed in incoming section
4. Observe all products removed from the OC

## Severity

S2: work around is to recreate (v time consuming) the OC

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
Notes; there are several new cloned OCs this week:

- "April 3rd 2021" (ID: **207822**)
- "April 3rd 2021" (ID: **207807**)
- "April 3rdv3 2021" (ID: **207823**)

They all seem to have been cloned from the previous week's OC ("March 27th 2001", ID: **207719**), and the issue is that all the incoming exchanges in that OC list no products. The OC from the week prior ("March 20th 2001", ID: **207659**) seems to be fine, all the incoming exchanges are intact.

**Comment by Matt-Yorkley** [comment]
Cloning OCs in general seems to be working. It looks like a data problem with that specific order cycle. Not sure of the cause yet.

**Comment by Matt-Yorkley** [comment]
It looks like deadlocks occasionally occur when cloning OCs, and specifically on cloning the associated exchanges and calling `touch` on the enterprise.

**Comment by David-OFN-CA** [comment]
Just chipping in to say that we just tried to replicate this issue in Canada, and didn't run into any problems -- we cloned and edited an OC and it worked fine
