### ISSUE TITLE
BOM: select multiple OCs into filter

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#724]
can’t select multiple OC’s into filter for Bulk Order Management - would have to use date search functions to cover all our days….??

**Comment by kirstenalarsen** [comment]
hold for now - FC checking . . if date range is ok, then no need for this . .

**Comment by myriamboure** [comment]
closing for now, if the need reappears let's open an icebox item, but if no user express that need let's just forget about it. #gitcull2018
