### ISSUE TITLE
[Rails 5.2] acts_as_list

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7258]
### What we should change and why (this is tech debt)

We have various classes that use the **acts_as_list** gem, and they currently have some kind of weird issue. This applies to various things like unit value names, product properties, etc. The objects representing those items are not being created or saved for some reason?

Bumping the gem requires Ruby 2.4.7+, but I tried this and bumped both Ruby and the gem, and it made no difference.

Example error:
```
36) Spree::Product variant units when the product already has a variant unit set (and all required option types exist) removes the old option type and assigns the new one
      Failure/Error: expect(p.option_types).to eq([ot_volume])
      
        expected: [#<Spree::OptionType id: 1046, name: "unit_volume", presentation: "Volume", created_at: "2021-03-27 19:13:51", updated_at: "2021-03-27 19:13:51", position: 670>]
             got: #<ActiveRecord::Associations::CollectionProxy []>
      
        (compared using ==)
      
        Diff:
        @@ -1 +1 @@
        -[#<Spree::OptionType id: 1046, name: "unit_volume", presentation: "Volume", created_at: "2021-03-27 19:13:51", updated_at: "2021-03-27 19:13:51", position: 670>]
        +[]
        
      # ./spec/models/spree/product_spec.rb:769:in `block (4 levels) in <module:Spree>'
```

**Comment by luisramos0** [comment]
I had a quick look, I am not sure this is related to acts_as_list...

Looking at spec/models/spree/product_spec.rb:769 and comparing master with rails.5.2 branch:

I think there's a problem in product.rb:444
variant_unit_changed?

when the product is created, this variant_unit_changed? is true in master and false in rails 5.2 and so the option type does not get updated.

I think the other similar error is related to taxons and that will be similar problem with primary_taxon_id_changed?

here is the explanation: https://jetrockets.pro/blog/rails-5-2-changes-in-callbacks

This fixes the problem https://github.com/openfoodfoundation/openfoodnetwork/pull/7347
We may need to look at the other usages of _changed? in our codebase :warning:
