### ISSUE TITLE
Orders index page, order cycle filter not offering all valid options

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#726]
When user is manager of hub, is seeing correct orders in orders index page, but order cycle filter is not giving correct options - think maybe is only offering OCs that user is coordinator of? needs to be those also participating in?

**Comment by daniellemoorhead** [comment]
@kirstenalarsen would it be worth adding more detail in this if a newbie is going to work on it?

**Comment by kirstenalarsen** [comment]
yes, but I have no idea if this is still an issue or not - seems like it would have had more screaming by now . . @sstead ?

**Comment by myriamboure** [comment]
This has been covered by https://github.com/openfoodfoundation/openfoodnetwork/issues/1889 which is now merged (not yet released). If you see this issue again feel free to reopen.
