### ISSUE TITLE
Editing Adjustments on cancelled orders changes order total -> leads to issue #7165

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7279]
## Description

This is a follow-up of issue #7228, which deals with canceled orders and changed the UI do disable the possibility to:
- change line item quantities
- adding/removing a line item
- changing shipping methods

However, it is still possible to access and make changes on the Adjustments tab(adding/deleting/editing) which has an effect on the order total, and may lead to the related issue #7165.

## Expected Behavior

Adjustments should not be editable on cancelled orders.

## Actual Behaviour

It's possible to edit Adjustments, which can lead to issue #7165.

## Steps to Reproduce

As admin, 
1. Cancel an order
2. Edit ajustments
3. See the changes on the order total.

## Animated Gif/Screenshot

-
## Workaround

-
## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.6.0
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by andrewpbrett** [comment]
Closing via https://github.com/openfoodfoundation/openfoodnetwork/pull/7265
