### ISSUE TITLE
Strange mistake in report with unexisting product

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#728]
In our order cycle we propose a "ung presset ost" (a cheese) of 200g.

In the product list of the producer it appears correctly, in the front end also, in the email confirmation also, in the bulk order management also... but in the detail of the order and the report it doesn't appear correctly, some very strange thing is happening.

Here is Magali's confirmation email:
![ofn_etrange_fromage3](https://cloud.githubusercontent.com/assets/8135376/11664076/e88748e2-9ddf-11e5-8323-f8cf18424d71.png)
It's well written 200g.

But when we export in csv the report, and in the order in the back office, here is what we had: one of the lines was showing another variant we never created, and which is not in the product list... the same cheese but with written "(400g)"
![ofn_etrange_fromage](https://cloud.githubusercontent.com/assets/8135376/11659263/a775c756-9dc7-11e5-9fbd-4d8f9f9b0e2b.png)

When investigating, we did an export by customer and found out the problem was on Magali... 

Olivier (with whom we run the buying group) has unfortunately deleted the "wrong strange 400g item" and replaced it by the only existing 200g item to Magali's order without taking other screen shots :-o

But he told me there were another problem with a mysterious variant we had not created, for the kale cabbage, we had only created a 500g  variant and Olivier told me in some other orders there were a mysterious 250g variant, which is not in the product list... He also changed them to the correct one.

Any idea? Has it happened to someone else?

**Comment by myriamboure** [comment]
Can it be connected to that issue @kirstenalarsen? https://github.com/openfoodfoundation/openfoodnetwork/issues/697

**Comment by kirstenalarsen** [comment]
Rob picked this up previously and is fixed in later commit, which I think Rohan has deployed for you by now.

**Comment by myriamboure** [comment]
Ok, sorry if it was already reported and fixed :-) I think we did the exports before Rohan depoyed the new version, so hopefully that won't happen again. I close the issue then.
