### ISSUE TITLE
Missing translation for Edit Shipping Method of an Existing Order

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7285]
## Description

Edit Order to change the shipping method.

There is a 'Yes/No' toggle to pass on the associated change in shipping method fee (if appropriate).

Text above this toggle is 'Associated Adjustment Closed'

No associated translation for this line of text.

![shippingmethod edit translation](https://user-images.githubusercontent.com/45104035/113011634-e38e0700-9171-11eb-989a-91ea5143fca1.jpg)

## Expected Behavior

There is a string 'Associated Adjustment Closed' in Transifex 

## Actual Behaviour

There is no string 'Associated Adjustment Closed' in Transifex 

## Steps to Reproduce

1.
2.
3.
4.

## Severity

S3
Good first issue
Papercut

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
This is now working 🎉
