### ISSUE TITLE
Add case studies to ofn.org.au in hub sign up page.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#729]
I have approved case studies for Baw Baw and Farm Food Store. Written for Bondi too, but Shann hasn't had a look at it yet (might soon, check with me).

Want these to be either put into .au as a new page. Or I can put them into .org and just need the hyperlink in .au to be updated. 

Any wisdom as to where they should be located?
- I figure they are useful on the global site, maybe under Platform > Food Hubs, but maybe global site should not be cluttered?

To save a developer having to do this again in future, could a place be held for the insertion of more case studies? Ideally we'll have 4 producer case studies and 4 hub case studies and maybe a group case study or two.

[Baw Baw Food Hub.docx](https://github.com/openfoodfoundation/openfoodnetwork/files/56289/Baw.Baw.Food.Hub.docx)
[Farm Foodstore Case Study SS (with KM edits).docx](https://github.com/openfoodfoundation/openfoodnetwork/files/56290/Farm.Foodstore.Case.Study.SS.with.KM.edits.docx)

**Comment by sstead** [comment]
Update: Case studies can be found here - https://openfoodnetwork.org/user-guide/case-studies/ We just need the hyperlinks updated at .org.au

**Comment by RachL** [comment]
These cases are now available here : https://openfoodnetwork.org/au/learn/ So I'm guessing this is either done or will be dealt with in the wordpress approach for the global & local "about" websites. So I'm closing this, but feel free to reopen if I misunderstood something.
