### ISSUE TITLE
Date Picker Error in Order Cycle Creation

### ISSUE THREAD

**Issue by kabhotz** [openfoodfoundation/openfoodnetwork#7292]
## Description
During the creation of a new Order Cycle the date picker seems use a bad locale date for Italian instance, using "a" instead of a correct year format.

![image](https://user-images.githubusercontent.com/8977332/113130777-bc404400-921c-11eb-94ba-cdf114743776.png)

This issue seem related to this #6170!

## Expected Behavior
The picker should use the locale date format for every instance.

## Actual Behaviour
All the order cycle opened with the new release don't work fine and show an error on missing delivery and payment mode also if this information are already setup.

## Steps to Reproduce

1. Go to https://stg.openfoodnetwork.it/
2. Login as producer
3. Create a new cycle order

## Severity
bug-s2

## Your Environment
Tested on v3.6.2 on https://stg.openfoodnetwork.it

**Comment by RachL** [comment]
@kabhotz I think this bit is again linked to translation. Have you checked the it translation for these strings? ping @jibees if you have another idea

**Comment by kabhotz** [comment]
@RachL it is strange because I have translated the field when we have solved the past issue #6170, I will try to check again on Transifex.

Now Irene wrote me that a new order cycle work fine and could be possibile that the error is about delivery and payment options.

In any case the date picker show a wrong date and have to be fixed.

**Comment by Matt-Yorkley** [comment]
> we have solved the past issue #6170

The translations for datepickers have changed again since then :grimacing:

**Comment by kabhotz** [comment]
I have tried to find the field by key in Transifex but without any result..! :(
Any suggestion to find the bad translation?

**Comment by RachL** [comment]
@kabhotz can you try these:

```
date_picker:
      flatpickr_date_format: "Y-m-d"
      flatpickr_datetime_format: "Y-m-d H:i"
      today: "Today"
      now: "Now"
```

**Comment by kabhotz** [comment]
Thanks @RachL, I have found it but what is the correct way to translate it?

Thanks in advance!

**Comment by kabhotz** [comment]
Usually the date format in Italy is dd-mm-yy

**Comment by sigmundpetersen** [comment]
https://www.transifex.com/open-food-foundation/open-food-network/translate/#it/enyml/314958800

I wonder if this actually shouldn't be translated and stay as `Y-m-d`?

**Comment by kabhotz** [comment]
Thanks for the suggestion @sigmundpetersen, now the two keys:

flatpickr_date_format
flatpickr_datetime_format

Use the "Y-m-d" format.

**Comment by RachL** [comment]
Yes these shouldn't be translated. I'm going to close this. Please reopen if there is any issue 💪
