### ISSUE TITLE
subscription orders: NoMethodError: undefined method `to_d' for #<OrderBalance:0x00000000074123f8>

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7293]
## Description

Observed both with feature toggle on and off:

Orders placed via subs are returning errors. Placing/confirming the sub is successful, but payments seem not to go through. Verified for stripe SCA (card x-3184) and Cash payment methods.

Bugsnag:
(1) After manually forcing the confirmation job in the console:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60644cbf579e980007f63e7e?event_id=60644cbf0075ef0a8c680000&i=sk&m=nw

(2) Attempting to manually capture StripeSCA payments (a consequence of the previous error)
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6059d808db1b8d0007c7528f?event_id=606450a80076106ce9ab0000&i=sk&m=nw

## Expected Behavior

Valid payments via subscription should be successful.

## Actual Behaviour

Valid payments via subscription are not successful. Order is in a pending state and can be captured manually. 

## Steps to Reproduce

1. Placing a subscription with SCA or Cash -> triggers error (1)
2. Attempt to manually capture the payment on /orders page -> triggers error (2)

## Animated Gif/Screenshot

-
## Workaround

-
## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: current master (after v3.6.2)
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by Matt-Yorkley** [comment]
Ok, so this relates to: 

https://github.com/openfoodfoundation/openfoodnetwork/blob/76def3a74feb71995b8102da1e07522c57ae1ba3/engines/order_management/app/services/order_management/subscriptions/payment_setup.rb#L14

Previously `@order.outstanding_balance` returned a number, but now it's an object that doesn't behave like a number (it doesn't respond to `#to_d`, which gets called on it by `Spree::LocalizedNumber`):

https://github.com/openfoodfoundation/openfoodnetwork/blob/0f5af2d9f1916d35484da764a500c370cd2269b7/app/models/spree/payment.rb#L8

https://github.com/openfoodfoundation/openfoodnetwork/blob/932adb533ccd1f87bd6340cc7739628349d8552e/lib/spree/localized_number.rb#L52

:boom: `NoMethodError: undefined method `to_d' for #<OrderBalance:0x00000000074123f8>`

**Comment by sauloperez** [comment]
Sorry I missed this balance usage although it was listed 🙈
