### ISSUE TITLE
Release v3.6.3  Chicha Morada

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#7304]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Release draft](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-77fbc882a91cc1e105e3)
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2429
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [ ] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by RachL** [comment]
@sauloperez this is ready to go :) 

https://docs.google.com/document/d/1GJIg414CNmru1wwRpHXCi8sSMUbeYzhPCvfKVBbCd1g/edit#

**Comment by Matt-Yorkley** [comment]
Devops note: I've just provisioned all production servers to install **Ruby 2.5.8**, so they're ready for deploying this release :ok_hand:
