### ISSUE TITLE
Desktop Chrome/Safari/Edge browsers display number input arrows when adding items (shopfront)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7306]
## Description

On Desktop, and for Windows 10/Ubuntu/Catalina OSs, the browsers Chrome/Safari/Edge browsers seem to display number input arrows, when adding items to the cart (`/shopfront`). This seems not to affect Firefox at all. It also seems not to affect mobile devices, on any browser.

## Expected Behavior

Display number input arrows should not be displayed - we have the +/- buttons for that :+1: 

## Actual Behaviour

Display number input arrows should not be displayed, between the +/- buttons.

## Steps to Reproduce

1. Visit any shop
2. Add/remove items
3. Notice the display number input arrows

## Animated Gif/Screenshot

On Desktop:

**- Chrome**
![Peek 2021-04-02 10-46](https://user-images.githubusercontent.com/49817236/113407892-2f28f680-93a6-11eb-816d-cc01dbe88d09.gif)

**- Firefox (not visible - OK)**
![Peek 2021-04-02 10-48_FF](https://user-images.githubusercontent.com/49817236/113407896-2fc18d00-93a6-11eb-8800-9e2b9e0bb9fb.gif)

**- Safari**
![Peek 2021-04-02 10-50_safari](https://user-images.githubusercontent.com/49817236/113407898-305a2380-93a6-11eb-835e-78abf2cbdad3.gif)

## Workaround

Not interferring with function; just not good-looking.

## Severity

I guess an bug-s4, but pretty widespread and affecting shopfront...

## Your Environment

* Version used: verified in v3.6.2 (probably pre-existing)

**Comment by gucci-ninja** [comment]
Hey I can work on this one, if that's cool

**Comment by filipefurtad0** [comment]
Hey @gucci-ninja, welcome! :tada: 

Sure, I've assigned you to the issue.
Feel free to drop us a line if you have any questions.
