### ISSUE TITLE
Payment Failed with no trace in Stripe

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7323]
## Description

Payment for order R286128647 (generated by a subscription) should have been collected at 12:00 05/04/21
Payment for order R825166787 (generated by a subscription) should have been collected at 14:30 05/04/21

Emails sent to the customers to state that the payments were unsuccessful.

No trace of the orders or failed payment attempt in Stripe account.

Payment status of the orders remains 'checkout'.

Unlike issue #6547 no record of failed payment attempts in bugsnag.

## Expected Behavior

Subscription order is paid for by a customer's authorised card.
Payment request is made to Stripe when the order cycle closes.
If payment is denied by Stripe there is a record or this in the user's Stripe account.
Error is captured by bugsnag
Error message sent to customer and user informs both about the cause of the payment failure.

## Actual Behaviour

Subscription order is paid for by a customer's authorised card.
Payment request is made to Stripe when the order cycle closes.
no record of payment request in user's Stripe account
No Error captured by bugsnag
Incomplete error message sent to customer and user informs both about the cause of the payment failure.

## Steps to Reproduce

Unable
1.
2.
3.
4.

## Severity

S2
onboarding a LARGE subscriptions user on UK platform (170 subscriptions potentially).
User needs confidence that payment attempts will go through.
Customer unable to pay for order

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
Both of those payments threw a simple error in Bugsnag: `Credit Card has expired`.

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/606aee5f82042300073b9609?event_id=606aee5f00770cd6053d0000&i=sk&m=nw

**Comment by lbwright22** [comment]
@Matt-Yorkley why was there no record in Stripe?  Is it possible to improve error messaging to the customer?

**Comment by Matt-Yorkley** [comment]
So the customer received an email telling them the payment was unsuccessful, but it didn't give them any more detail?

Sounds like it wouldn't be too hard to improve that and include the message.

**Comment by lbwright22** [comment]
All it said was ;
The payment for your subscription with C... failed because of a problem with your credit card. C... has been notified of this failed payment. You can view details of this order at any time.....

The enterprise didn't get any details either and so would be unable to inform the customer what was wrong (ie they simply had to update their expired card)

It would be super amazing if the error could be stated.

**Comment by lin-d-hop** [comment]
@lbwright22 Let's start to collect the current flows in a document.
Then we can identify some simple solutions that help a lot from a user perspective.
This will help us to make very clear issues for developers. And since this is about payments on orders we can see what can be squeezed through as an s2 :-)

**Comment by lbwright22** [comment]
@lin-d-hop here is the document of current workflow: https://docs.google.com/document/d/1p0988VQx1eTDy1kfNYyz18zHWmlI3P3TWlNAsV5eBVQ/edit?usp=sharing

includes proposed improvements

**Comment by lin-d-hop** [comment]
Removing S2 label pending work with @jaycmb and @filipefurtad0 on subs order states.

**Comment by lin-d-hop** [comment]
Closing as the most important parts of this issue are captured in wishlist.
