### ISSUE TITLE
[Rails 5.2] Carefully upgrade wicked_pdf and wkhtmltopdf-binary

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7324]
### What we should change and why (this is tech debt)

I think we might be getting close to the point where our multiple Ubuntu versions becomes problematic, specifically in relation to the `wicked_pdf` gem and the related `wkhtmltopdf-binary` gem. For a bit of background: different versions of the gems have compatibility with different OS versions, so for example some versions work with Ubuntu 14-18, some work with 16-20, etc. Incidentally, this is the reason most of us can't run PDF specs in dev.

We were previously held back at versions that support Ubuntu 14+, because Semaphore ran on 14. I think we will need to bump those gems for Rails 5.2, but when we remove the version pin it will be easy to accidentally upgrade to a version that breaks on Ubuntu 16, and we won't currently see it in CI, which currently runs with an Ubuntu 18 image.

Maybe we should switch Github CI to use Ubuntu 16?

Either way, we'll need to be careful when upgrading those gems, and make sure it works with Ubuntu 16.

We can do this in master :+1:

**Comment by luisramos0** [comment]
Ubuntu 16 is about to change from "extended support" to "extended security support", this probably means it will only get security updates from now on. https://en.wikipedia.org/wiki/Ubuntu_version_history#Version_timeline

**Comment by Matt-Yorkley** [comment]
I made a PR to bump `wkhtmltopdf-binary` in master, but I think we'll also need to try bumping `wicked_pdf` in the 5.2 branch. It won't let me bump it any higher in master, but I think it uses `#alias_method_chain` internally (which will not work in 5.2).
