### ISSUE TITLE
REST API documentation

### ISSUE THREAD

**Issue by wvengen** [openfoodfoundation/openfoodnetwork#734]
Hi, as part of the [EU hackathon](http://community.openfoodnetwork.org/t/project-ideas-for-eu-hackathon/406) I'm looking into the REST API. There seems to be [a partial API](https://github.com/openfoodfoundation/openfoodnetwork/blob/a96cdd5ee77411e4204f7427740b97d22c37f59c/config/routes.rb#L122) already, and I would like to add documentation for this.

Any preferred way to document the REST API?
* **[swagger](http://swagger.io)**
* **plain markdown** - a bit of a hassle, but workable ([hints](https://bocoup.com/weblog/documenting-your-api))
* **[fork api.spreecommerce.com](https://github.com/spree/api.spreecommerce.com/tree/master/content/v1)**
* **[apipie-rails](https://github.com/Apipie/apipie-rails)**
* **[apiblueprint](https://apiblueprint.org/)**
* ...

**Comment by darshand** [comment]
swagger is the best option for documenting REST API.



Regards,
Dharshan B D
ONZE Technologies Pvt. Ltd

**Comment by wvengen** [comment]
related #280 and [wiki:Integration & API](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Integration-&-API)

**Comment by wvengen** [comment]
It seems that Spree [uses markdown for api.spreecommerce.com](https://github.com/spree/api.spreecommerce.com/tree/master/content/v1). We could fork it and add OFN-specific endpoints. Prone to getting out-of-date, though.

**Comment by wvengen** [comment]
For simplicity I've started with a wiki page [API documentation](https://github.com/openfoodfoundation/openfoodnetwork/wiki/API-documentation).

**Comment by wvengen** [comment]
Now that there is a first place for API docs, this can be closed. Feel free to re-open if you think we need more structured API documentation (like swagger).
