### ISSUE TITLE
Shop Products not loading

### ISSUE THREAD

**Issue by Renatacumming** [openfoodfoundation/openfoodnetwork#7348]
## Description
The entire shopfront is not loading
Shopfront: https://openfoodnetwork.org.au/westies-dry-goods-buying-group/shop#/shop

Please note this order cycle is for registered customers only, if you are not registered you get a message to that effect, if you are you get the spinning wheel. Customers noticed this issue last week, we have only just been notified overnight

## Expected Behavior
All products which are in stock should load on shop front

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by andrewpbrett** [comment]
I fixed this for the time being by setting the product's `variant_unit_scale` to `nil`; the PR should fix it more permanently.
