### ISSUE TITLE
Release v3.6.5 Ravishing Radishes

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#7358]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Draft new release]
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2467
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

The release looks good to go. Found a regression but not a blocker, I think:

- #7398 (regression)
- #7399 (pre-existing)

Testing notes here:
https://docs.google.com/document/d/1MhXtgiOQ-6xvP73d68llrA-jZPdEL4R_yDhYis0nU54/edit#
