### ISSUE TITLE
Update developer documentation wiki page

### ISSUE THREAD

**Issue by wvengen** [openfoodfoundation/openfoodnetwork#737]
During a talk with @elf-pavlik @selmo-ofn @myriamboure I learned some things that would be useful to put in developer documentation, probably on [wiki:Developer Manual](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Developer-Manual).

- [x] OFN forums are used for discussing new features (and much more)
- [x] Github issues are used for bugs and features from the backlog that will be implemented
- [x] Trello is not being used anymore
- [x] Zenhub is being used
- [x] I would suggest to add a like from CONTRIBUTING.md to the developer manual wiki page.
- [x] Add Travis badge

It would be useful to update the wikipage with this information and add specific links.
This would help new developers get into the project easier

**Comment by kirstenalarsen** [comment]
agree! we had whiteboard session a couple of weeks ago around communicating all this better and just waiting on the person who said they’d write it all up and communicate it. If hasn’t happened before then I’ll try to get to it on friday :)

**Comment by wvengen** [comment]
Great to hear :+1: Would have added it but felt just a bit unsure about how things were organised.

**Comment by pmackay** [comment]
@wvengen have done a bunch of things on this - see https://github.com/openfoodfoundation/openfoodnetwork/wiki. Feedback welcome. More to do on wiki for general gardening. Also updated README, etc.

**Comment by myriamboure** [comment]
Ping @marito59 and @blancnic, would be great if you can give feedback on the documentation.

**Comment by pmackay** [comment]
Closing but please add comments if you have more suggestions.
