### ISSUE TITLE
few more i18n tasks 

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/openfoodnetwork#738]
I just noticed validation message in model which has some non translated string: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/enterprise_role.rb#L6
We should also search more of them!

`grep -r 'message:' app/models`

---

Also some mailers 
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/producer_mailer/order_cycle_report.text.haml

Example of translated mailer https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/enterprise_mailer/welcome.html.haml

Check
- https://github.com/openfoodfoundation/openfoodnetwork/tree/master/app/views/spree/order_mailer
- https://github.com/openfoodfoundation/openfoodnetwork/tree/master/app/views/spree/user_mailer

not on transifex

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/spree/user_mailer/signup_confirmation.en-GB.text.erb

https://github.com/openfoodfoundation/openfoodnetwork/commit/543368169f5aa09b6646aa5440b44f2ce6c96629#commitcomment-14981280

---

https://github.com/glebm/i18n-tasks

`$ i18n-tasks missing`

**Comment by mkllnk** [comment]
Reviewing and merging pull requests, I find conflicting keys quite often. Sometimes their are duplicate entries and sometimes people forget to delete old keys. The i18n-tasks gem suggested by Pavlik could be really helpful. Let's implement that.

**Comment by daniellemoorhead** [comment]
Hey @mkllnk are those new transifex PRs you created today linked to this issue?

**Comment by mkllnk** [comment]
The one merging the `transifex` branch is a monthly task for every release. We would like to automate that. But for now I'm doing it manually. In a dev chat long ago, we said that pull requests are a good way to make that step visible and remember it.

This issue is suggesting a new tool to clean up our translations and ensure that we don't mess things up with code typos. It would be a core commons contribution to work on this. Making i18n pull requests easier and faster for everyone.

**Comment by daniellemoorhead** [comment]
Hey @kirstenalarsen reckon we could spend some CC funds on doing this work? ☝️

**Comment by kirstenalarsen** [comment]
please post to the discourse discussion if you want to nominate for spending OFN cc funds - https://community.openfoodnetwork.org/t/determining-use-of-ofn-cc-funds/987

Thanks :)

**Comment by kirstenalarsen** [comment]
now placed in [CC Tech Oversight](https://github.com/openfoodfoundation/openfoodnetwork/projects/17) project
@mkllnk estimate 4 hours

**Comment by myriamboure** [comment]
@mkllnk @sauloperez @enricostano given what you discussed with Maikel and what Maikel started to implement, do we still need to do that ? Should we keep it in the current pipe or create an icebox ?

**Comment by sauloperez** [comment]
I agree with @mkllnk that it's worth using https://github.com/glebm/i18n-tasks. I'd create an icebox item.

**Comment by daniellemoorhead** [comment]
Can this be closed now @myriamboure @sauloperez, is there an icebox item for it?

**Comment by myriamboure** [comment]
Done https://community.openfoodnetwork.org/t/ensure-correct-translations-are-maintained-and-comprehensive/1303. I'm wondering though as this was already prioritized if we shouldn't finish it... but anyway, I'm closing it for now, it is in the spreadsheet so I guess we won't forget it.
