### ISSUE TITLE
Non-weight variants: Creating/editing with 'weight' field blank -> snail (error 500)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7398]
## Description

While **creating** or **editing** variants which are not variant unit scale is not `weight` type:
- if the form under `/admin/products/<product_name>/variants/<variant_id>/edit` is submitted with the `weight` field left blank
then the user gets the snail.

## Expected Behavior

Submitting the variant form with 'weight' field left blank should not trigger the snail.

## Actual Behaviour

It currently does.

## Steps to Reproduce

1. Create a or edit a variant for a **non-weight** product (ex., L or Items)
2. Fill in the form in `/admin/products/<product_name>/variants/<variant_id>/edit` but deleted the pre-filled value on the field `weight`
3. Click 'Update' -> Snail

## Animated Gif/Screenshot

![Peek 2021-04-12 10-35.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/bbdf7700-dc7a-44ae-aa72-8fad49d1532c)

## Workaround

Don't delete the prefilled value. If you do, type in something. A string is also fine.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: introduced in v.3.6.5
* Browser name and version: Firefox 87
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by Matt-Yorkley** [comment]
Is this definitely new in v3.6.5 or was it already in v3.6.4? I can't see any PRs in this week's release that look like they could have changed this... :thinking:

**Comment by filipefurtad0** [comment]
Humm, weird. I checked on production-FR and the `weight` had no pre-defined value:

![image](https://user-images.githubusercontent.com/49817236/114413189-a9772900-9ba5-11eb-94c1-59366ac7da00.png)

Hence, could not trigger this on production...

**Comment by filipefurtad0** [comment]
On staging-AU, after staging the release PR for v.3.6.5:

![image](https://user-images.githubusercontent.com/49817236/114415194-5dc57f00-9ba7-11eb-86a9-715e19f9f772.png)

On staging-ES - last PR staged was **build #2 of pull-request-7363**  so maybe it was introduced in the meantime?

![image](https://user-images.githubusercontent.com/49817236/114415249-6ddd5e80-9ba7-11eb-9bc6-5464b5f43092.png)

On staging-UK - last staged PR was **build #5 of pull-request-7207**:

![image](https://user-images.githubusercontent.com/49817236/114415591-bbf26200-9ba7-11eb-80a8-93474eb962ae.png)

I'll stage the v.3.5.6 in staging-UK and check if we get the non-null constraint as well :+1:

**Comment by filipefurtad0** [comment]
Tricky. Not happening in staging-UK after staging the release draft. Also, looking at devops channel, we see this error has occurred before (twice) in production, it's not a regression. Seems it affected Katuma before. And it's possible to reproduce now as well.... Below the pic and Bugsnag katuma-production:

![image](https://user-images.githubusercontent.com/49817236/114419458-5bfdba80-9bab-11eb-8cfc-d304726b37d9.png)

So, it looks as if it might be related to some server settings? Anyway, it is not a regression. Thanks for checking Matt.

**Comment by Matt-Yorkley** [comment]
Thanks @filipefurtad0! It looks like there could be some kind of issue there, but if it's not a release blocker then there's no rush to fix it before deploying :ok_hand:
