### ISSUE TITLE
Incorrect Payment Status Email sent to customer on completion of Subscription order

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7401]
## Description

OC 207805 closed noon 12/04/21
Email (number 16 of[ this Wiki list](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Emails)) were sent to customers of orders R665015285 and R521874556 stating that there had been a problem with their card payment and for the customer to contact the hub manager.

Email 18 of [this Wiki List](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Emails) also states that payment failed for the above two orders.

Order status for these transactions on the platform shows that payment was successful. 
Checking the payment status in Stripe for the two orders shows that payment was successfully taken.

This is confusing for the customer.

## Expected Behavior

Only subscription customers for whom payments are not processed successfully through Stripe when an order cycle closes are sent email 16 from [this Wiki List](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Emails).

## Actual Behaviour

Subscription customers for whom payments were processed successfully through Stripe when an order cycle closes were sent email 16 from [this Wiki List](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Emails) by mistake.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by andrewpbrett** [comment]
This is the relevant Bugsnag:

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6074287e3d6d1b00075f8417?event_id=6074287e0077584d71340000&i=sk&m=nw

It was actually a problem with the email going out, not anything to do with the payment failing it looks like. In that method, however, we rescue any error that happens with a clause that sends that email (# 16) 

I'm not sure what might have caused the Net::Timeout error, however, but my best guess is that the email provider was unreachable for a couple minutes. I believe the UK is on SendGrid, correct? @Matt-Yorkley might have some other ideas here.

**Comment by Matt-Yorkley** [comment]
Yeah we use SendGrid and it's usually pretty good. I'd also assume it was a temporary network issue around sending the email.

:man_shrugging:

**Comment by andrewpbrett** [comment]
Cool, thanks Matt. In that case I'd say we should downgrade and basically hit the snooze button until it pops up again; it seems rare enough that it's probably not worth the time and added codebase complexity to write a lot of extra logic around it. What do you think @lbwright22?

**Comment by lbwright22** [comment]
@Matt-Yorkley  and @andrewpbrett thanks for looking into this. I have tried to create an order in the back office for the same enterprise and order cycle to see if it is working now and it isn't.

The business need to create back office orders on closed order cycles and so this is a real problem for them and their business model.

**Comment by Matt-Yorkley** [comment]
> create back office orders on closed order cycles

That's a lot more specific and could be a useful clue :+1:

**Comment by lbwright22** [comment]
but also on Open order cycles if possible (any back office order - open or closed OC) not working at the moment for this enterprise

**Comment by andrewpbrett** [comment]
@lbwright22 did you mean to comment on this issue? https://github.com/openfoodfoundation/openfoodnetwork/issues/7337

**Comment by lbwright22** [comment]
Ahhh- mixed up. Sorry @andrewpbrett and @Matt-Yorkley

**Comment by lbwright22** [comment]
Yes. fine to snooze this
