### ISSUE TITLE
Split Checkout

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#7406]
### Description 

**EDIT/ UPDATE Apr 13th (to summarize outcomes of inception)**

The Checkout will be split into 3 steps/pages

1. Your details
2. Payment Method
3. Order Details

This will address
- the perfomance issues (prices calculated only after shipping details entered)
- the incorrectly displayed prices (final prices calculated after shipping details entered, but before user places the order)
- addresses the legal requirements (providing a order summary page before user confirms the order)
- and improves the user experience :)

**Designs** are here: https://www.figma.com/file/mwC9b6iUJxP29G4COnfkbC/Checkout-Overhaul?node-id=0%3A1

**Original Issue Description** 
++++++++++++++++++++++++++++++++++++++++++++

Initiated by the work on adjustments and the way how tax calculations influence the final price, we would like to explore splitting the checkout in 2 pages alongside improving the overall UX and legal compliance of the checkout process.

**- 1. Legal Compliance:**  Currently OFN is not compliant to the "Double-Click-Rule":  EU law requires a checkout process to have an order summary page where

> For the order to be validly concluded, you must have been able, before confirming it :
> 
> - check the details and the total price
> - and correct any errors.
> 
> 

> Your consent is given by a double click (2 mouse clicks) :
> -  the 1st click enables you to validate your order,
> - the 2nd click allows you to definitively confirm your order after having checked it and, if necessary, corrected it.

> In the absence of a double click or information on the obligation to pay, the sale is considered invalid.

Further details and acceptance criteria will follow below in comment

**2. Correct Tax Calculations**

Tax rates can be dependent on the address that the order will be delivered to, so in some instances this means that the rates will be different depending on the customer's location (eg. different rates in different states)
In this case, **the final prices on the order can only be sensibly calculated after the order explicitly has an address already saved on it**, 

**3. Performance**
Currently all fees and taxes are re-calculated any time a line item is added or removed (or quantity is changed), even whilst the order is in cart state
-> This is not needed until a user gets to the checkout, 

> as any of these tax calculations and adjustments will be removed and re-calculated after the order's address is formalised. Eg: until the address is fixed, any tax-related adjustments are provisional . 
> Same applies to **order-level fees** that don't affect line item prices. 

> There's no reason to create them before checkout, but we re-create them every time the cart is touched.

**4. UX**
As discussed earlier, the checkout process could do a general UX uplift. 

Getting rid of Next Buttons / Jumping Sections
https://app.zenhub.com/workspaces/product--inception-pipe-5f82e534db531f000f8c09ff/issues/openfoodfoundation/inception-pipe/30 
https://app.zenhub.com/workspaces/product--inception-pipe-5f82e534db531f000f8c09ff/issues/openfoodfoundation/inception-pipe/21

From a UX perspective, splitting checkout should be considered, as there are also advantages for keeping a single-page-checkout since it´s easier and more convenient for the user to have all steps on one page. Splitting in to 2 steps might increase cart abandonment.

User Testing of the Checkout flow currently in play here: https://app.zenhub.com/workspaces/product--inception-pipe-5f82e534db531f000f8c09ff/issues/openfoodfoundation/product-pipe/21 will provide additional insights.

**Comment by Erioldoesdesign** [comment]
Final design file: https://www.figma.com/file/uhgmuHCznpkoYnaM8AZESt/Splitting-the-checkout-for-dev?node-id=0%3A1

Discourse post updated: https://community.openfoodnetwork.org/t/splitting-the-checkout/2173/9

**Comment by Erioldoesdesign** [comment]
Asked Matt for some time this week to chat through the dev bits

**Comment by drummer83** [comment]
Just wanted to point out that it was agreend NOT to change the address input fields of the checkout processs compared to what we have now (see this [Slack conversation](https://openfoodnetwork.slack.com/archives/C01FMHLRJAJ/p1616415079007700)). This should be explicitly mentioned to developers because the Figma file still contains changes.

Discourse post still seems to be private. Should it be public because community feedback was requested?

@Erioldoesdesign @jaycmb

**Comment by jaycmb** [comment]
Thanks for the reminder @drummer83 - that´s true, we agreed to keep the current implementation.
That must have gone under the radar, slack threads are not the best place for documenting decisions ;)

**Comment by Erioldoesdesign** [comment]
I can change the designs but I *strongly advise* that the first improvement ticket for this work after live is to remove 'Address cont.' in favour of street etc. because of the user-testing evidence.

**Comment by jaycmb** [comment]
Agree that 'Address cont.' is not intuitive and that users can be confused of where to put in the house number.
We are mixing up 2 things here though:

1. order of input fields
2. ambiguous input field description

1) Ideal case would be to have the precise description of the input fields ('house number' , 'street') but with the order of fields localized for the instance. But that´s certainly overkill for now
2) This could be addressed now already if we want, by renaming the 2 lines to something like:
- Address (Street + House Number)
- Additional address info (optional)

But also good to just keep it like it is, and validate text with users.

**Comment by Erioldoesdesign** [comment]
Figma file changed and updated

**Comment by RachL** [comment]
#10636 will definitely close this, but as it's the last issue I'm closing here to have a clearer dev ready column. We can reopen if needed.
