### ISSUE TITLE
Checkout 1st step - Allow user to enter their details

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#7408]
## Description

**- As a:** user
**- On page:** new URL: /checkout/enter-your-details
**- I want to be able to do:** 
- enter my personal details
- enter my billing address
- save my billing address for future orders (optional)
- enter my delivery address (if different from billing address)
- save my delivery address (optional)
- choose a delivery option
- provide additional information about the order or the delivery to the shop (optional)
- see how many steps I have to complete and where I am (progress bar)

- confirm the details I entered and move to next step
- go back to edit my basket 

## Acceptance Criteria & Tests

1. User can enter their details
2. User can choose a delivery option
3. If only one delivery option is provided, this should be preselected
4. Depending on the selected delivery option, the respective information that is provided in Admin is displayed to the user
5. If the user confirms (**checkmark selected**) that billing address is same as delivery address, the delivery address input block vanishes and the billing address is used for delivery address.
6. If the user does not confirm (**checkmark not selected**) that billing address is same as delivery address, an additional delivery address input block is provided for the user to enter their delivery details
7. If user missed to enter some of the (mandatory) information and clicks on 'Next - Payment Method' , an error message is displayed -> **see new design for error handling**
9. User cannot 'jump' to one of the next step by clicking on 2nd or 3rd step on the progress bar, if mandatory information is missing. 
8. If user clicks on _'Next-Payment method'_ information is saved (delivery address is used for calculating final costs incl. shipping + taxes) and user gets to the 2nd Step - Payment method

**TO CLARIFY:**  
-> information should be saved when going back and forth between steps!

All designs are here: https://www.figma.com/file/mwC9b6iUJxP29G4COnfkbC/Checkout-Overhaul?node-id=0%3A1

**Overview 'Your Details Page**
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/4588b9e3-6a56-42a0-8cf8-1522ae9e7ede)

Error-Handling
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/71fb27b0-88ef-46b1-8df6-da66b0a4b0d0)!

**Comment by RachL** [comment]
@jaycmb we have had a few requests from users asking that if there is only one shipping method, the shipping method should be automatically selected. Do you think it's a test we can include here or should this be a separate papercut?

**Comment by Erioldoesdesign** [comment]
@RachL I think that's a reasonably stretch of this and worth testing. Less clicks is good for users :)

**Comment by jaycmb** [comment]
Agree, we can add this.

**Comment by jaycmb** [comment]
**Rough estimation**

Dev: 16- 20 hours / 2 -2.5 days
**Backend** 4 hours / 0.5 Day
**Frontend** 12 hours / 1.5 Day
**Testing** 3 hours / 0.25-0.5 Day

**T-Shirt Size**
Dev: 
Backend: S
Frontend: M
Testing: M

**Comment by jibees** [comment]
After a lot of back and forth (that probably spend 3/4 days) new estimation (for the frontend part) are around 5 days for Step1 + Step2 (That includes: adding StimulusJS, learning StimulusJS, understanding what should be removed from previous AngularJS controllers and added thanks to StimulusJS and finally building the form)

**Comment by RachL** [comment]
I'm closing this one. We can use the tests described here when testing everything, but it does not need for this issue to be kept opened.
