### ISSUE TITLE
Checkout Product Analytics: change URL to enable tracking of checkout flow 

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#7409]
## Description

**- As a:** product manager
**- On page:** all pages
**- I want to be able to do:**track the sign in/registration flow (authentication) because if users struggling to sign in, they are more likely to abandon their basket.
The URL is /checkout before the login and after so at the moment you can't tell where users are dropping off between those two steps. 
This will happen in all pages as currently the login dialog is not being tracked as a pageview in Matomo.

To be able to track the authentication as part of the checkout flow and differentiate between guest users & registered users, we need a separate URL /login 
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/423bd384-3785-46e2-ac88-89be07c89a50)

## Acceptance Criteria & Tests

The user flows for registered users vs. guest users should be as follows

**Registered Users, not logged in**
1. /cart
2./checkout
3. /login/
4. /checkout/enter-your-details
5. /checkout/payment-method
6. /checkout/order-summary

**Logged-in user**
1. /cart
2. /checkout/enter-your-details
3. /checkout/payment-method
4. /checkout/order-summary

**Guest**
1. /cart
2. /checkout
3. /checkout/enter-your-details
4. /checkout/payment-method

/checkout
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/6bb3b24c-8a19-467a-9134-5e3c301e311f)
/checkout/#login
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/2364dba4-885f-4872-922d-656e4a32fda7)
/checkout
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/b86f8962-77a8-48cb-a2e7-924947cf56cd)

**Guest Checkout**

/checkout
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/7ef73321-cc76-40f3-b36f-4a484d3dbe06)
/checkout
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/005b5735-fd65-4c20-b46e-c680d9c75855)

**Comment by monarab** [comment]
hi Jana
My understanding is that for logged in users, they wouldn't see the checkout step but would go straight into into /your-details? Is that right?
Thanks,
Monica

**Comment by jaycmb** [comment]
Yes, that´s right! I´ll edit

**Comment by jaycmb** [comment]
If URLs are changed away from what has been specified above (or on the respective issue of the steps), then please make sure to document in the issues and ping me. 
Because otherwise we set up the funnels in the wrong way.
Ping @jibees and @Matt-Yorkley

**Comment by jibees** [comment]
I'll change the document in order to match the reality. I'll close the issue then. 
Here the document: https://docs.google.com/spreadsheets/d/1kVIoIBiYdBhgml1BbV2AEU0JnYTNphlhp6Y9nXHGEog/edit#gid=780308511

**Comment by jaycmb** [comment]
Currently the flow is defined like this:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/39744592/135095732-1d83b682-13a6-4156-94b7-47a7f5c1e447.png">

I couldn´t find the updates in the document, or is 

> I'll change the document in order to match the reality. I'll close the issue then.

meant yet to come :)?

Also, do you have in mind that we want to separate /checkout from /login?

**Comment by jibees** [comment]
I'v double checked the URLs, and added it to the document : 

Split checkout URLs |  
-- | --
Your details | `/checkout/details`
Payment method | `/checkout/payment`
Order summary | `/checkout/summary`

You can use it to make some modification in the current flow definition: for example, replace "path contains `payment-method`" by "path contains `checkout/payment`" (NB: without the first `/`)

**Comment by jibees** [comment]
Re 
> Also, do you have in mind that we want to separate /checkout from /login?

Not sure to understand what does this means, and implication on URL tracking.

**Comment by jibees** [comment]
For the modal opening, I think the right way to track this, is to push an event via javascript

https://matomo.org/docs/event-tracking/#how-to-set-up-matomo-event-tracking-with-javascript
https://developer.matomo.org/guides/tracking-javascript-guide#manually-trigger-events

**Comment by jibees** [comment]
@jaycmb I implemented a code that push an event each time signup is submitted.

**Event Category** : Signup
**Event Action** : Submit signup
**Event Name** : the current url
**Event Value** : N/A

**Comment by jaycmb** [comment]
So this will only track the signup then, not a login for registered users, right?

Can we still track the funnel separate between logged in and not logged in users, as it is described in the AC, if we use an event and not a different URL (/login)?

<img width="498" alt="image" src="https://user-images.githubusercontent.com/39744592/136187504-ef07029c-d64d-40ac-a07f-78d1c4d6e996.png">
