### ISSUE TITLE
at /register unable to select state

### ISSUE THREAD

**Issue by monicafrancia** [openfoodfoundation/openfoodnetwork#741]
When registering you can't select a state and hence can't proceed in creating a profile.

![image](https://cloud.githubusercontent.com/assets/16314150/11829758/0db24a86-a3f3-11e5-89f9-3e148a2f907f.png)

**Comment by sstead** [comment]
This is pretty strange, and we can't figure out what's causing it. If anyone would like to take a look that would be great!
From what we can tell it's only happening on Windows computers. In Chrome.

**Comment by myriamboure** [comment]
this is working fine at the moment so closing.
