### ISSUE TITLE
Checkout 2nd step - Allow user to choose their payment method

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#7410]
## Description

**- As a:** shopper
**- On page:** checkout/payment-method
**- I want to be able to do:** select my payment method, depending on the payment options provided by the shop

When the user choses payment options Credit Card or Paypal the respective default text should be displayed to the user
- **Paypal**
_Pay with Paypal. You will be redirected to your PayPal account after you reviewed and confirmed your order in the next step "Order Summary"._
- **Credit Card**
_Pay with your debit or credit card. You will be redirected to Stripe to enter your card details after you reviewed and confirmed your order in the next step "Order Summary._

These default texts should also be visible to Admins in Backoffice > Payment methods.

## Acceptance Criteria & Tests

1. User can select between all payment options provided by the shop
2. When the user has selected a payment option, the additional information (if) provided by the Admin is displayed to the user
UPDATE
3. For all payment options, in this step the **user will only select their payment option**. Details will be entered only after order is placed in 3rd step.
4. For payment options **Credit card** and **Paypal**, the default text should be displayed to the user (if not overwritten by Admin)
5. When the user wants to go back to the previous step, they can do so in 3 ways: by 
- click on 'Back to Your Details' Button 
- click on the 1st step in the progress bar 'Your Details' (entire progress bar section is entire click hit area)
- click on the browser back button
  When the user goes back to the previous step, the information entered / selected in the current step should be saved

All designs are here:
https://www.figma.com/file/mwC9b6iUJxP29G4COnfkbC/Checkout-Overhaul?node-id=0%3A1

**Example: Payment with Credit Cart selected.**
![Checkout - Payment card entered](https://user-images.githubusercontent.com/39744592/132505441-910ca762-cf03-417b-a938-404587bee36c.png)

**Comment by jaycmb** [comment]
Where does the verification of the payment method happen, when credit card or PayPal is selected?
Between this step and the  order summary page?
Or only after the user has seen the order summary page and completes the order?

**Comment by Erioldoesdesign** [comment]
@jaycmb After paypal is selected, there's a Paypal modal that opens and asks you to login and verify. Until verified the 'Next - order summary- button would need to give an error saying that paypal has yet to be verified.
There would be no change in the behaviour on current OFN.

**Comment by jaycmb** [comment]
The discussion around [when the user enters their payment details](https://app.zenhub.com/workspaces/product--inception-pipe-5f82e534db531f000f8c09ff/issues/openfoodfoundation/inception-pipe/73) was concluded to go for

Option A

- 2nd Step "Payment Method" is purely for the user to select their payment option and see related fees but not enter any details
- 3rd step Order Summary: both for Credit Card and Paypal users are asked to enter their information only when placing the order in the final step and then getting forwarded to the respective payment provide

(see issue description for for details)

 @Matt-Yorkley confirmed that also in this case the user will be able to select from previously saved cards **after** they placed the order and are redirected to Stripe in 3rd Step.

Like this the process for the user gets unified: for all payment methods they select their preferred payment method but only enter their details when redirected to payment providers after they reviewed the order in the final step.

**Comment by jaycmb** [comment]
**Rough Estimation**

**Dev**
Frontend:
Backend: 8 hours / 1 -1.5 days

**Testing**
1-2 hours / 0.25 days


_This is for the case, that payment details will be entered in the 3rd step_!

**Comment by jaycmb** [comment]
Could it be that we are going to face problems due to the time lag between, as user saving items in cart, payment method added and payment being authorised happens ins 3 distinct steps?

Doublechecking because of the multiple bugs we recently faced around payment and order states

> This is due to the order we do things in:
> 
>    ` Order#process_payments!` gets called in the `before_transition to: :complete hook`
>     `Order#finalize! `gets called in the `after_transition to: :complete hook`, and this is where a) stock is reduced and the b) order is marked as completed

[#7692 ](https://app.zenhub.com/workspaces/dev-pipe-54b840c6a249c8781446d4b2/issues/openfoodfoundation/openfoodnetwork/7692)

Not sure if this also applies to front office orders?

Ping @Matt-Yorkley @filipefurtad0 @andrewpbrett

**Comment by andrewpbrett** [comment]
I think the changes we're making (which will likely be merged before this epic) will actually be really useful to enable the new split checkout, since we now assume there could be a long lag between each step and are programming defensively to account for that.

**Comment by RachL** [comment]
I'm closing this one. We can use the tests described here when testing everything, but it does not need for this issue to be kept opened.
