### ISSUE TITLE
duplication of 'line item'  and 'order item'  adjustments

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#7418]
## Description
On the order editing page,  I am seeing 'order item adjustments' mirrored as 'line item adjustments'  and then mirrored again on the adjustments page.   Adjustments like enterprise fees for example,  have previously only appeared once on the order edit page,  and they have never appeared on the adjustments page.   Several users have emailed our support to say that their orders are double calculating admin fees in the shops.  This is not the case - from what I can see,  only one of these adjustments is calculating -  but I'm guessing that they shouldn't be showing in 3 places. 

## Expected Behavior
I'm not sure  -  what is the difference between a 'line item' and an 'order item' adjustment,  and where should each be showing?

## Actual Behaviour
As above -  'line item'  and 'order item' adjustments are appearing,  but not active,  in multiple places.   Which of these should the user edit?

## Steps to Reproduce
Set an enterprise fee to calculate on each item in a shop
Place an order
See the edit order page
Go to the adjustment tab and see the list there

## Animated Gif/Screenshot
![line item versus order item adjustments](https://user-images.githubusercontent.com/13171778/114720636-2f11ea80-9d06-11eb-9f9b-49e59b5d2e69.png)
![admin fees on adjustments page](https://user-images.githubusercontent.com/13171778/114720663-3507cb80-9d06-11eb-9b87-49c108496677.png)

## Workaround
No workaround that I can see

## Severity
I'd say an s1 given the confusion its causing users trying to edit orders -   but if its an s2 and we can't fix soon - perhaps we can put an explanation in the user guide and tell users which adjustments to edit and which to ignore?

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by filipefurtad0** [comment]
Thanks for reporting this @tschumilas,

This seems reproducible in staging, and I can confirm that the order total is unaffected; it seems only to affect the displayed info.

@Matt-Yorkley , I was having a second look at this (also in the context of #7329) and just realized that the UI is missing tax info, which the appears correctly under the adjustments tab:

![image](https://user-images.githubusercontent.com/49817236/114723359-8332c400-9d32-11eb-8500-8f3514a13158.png)

For comparison, the same order as seen from the customer:

![image](https://user-images.githubusercontent.com/49817236/114723458-93e33a00-9d32-11eb-8ad6-5c0fe2cd4d68.png)

**Comment by Matt-Yorkley** [comment]
I've split this into two parts and made a separate PR for each one :+1:

**Comment by tschumilas** [comment]
I'm sorry - I've lost track of where and when to provide feedback on these.  Will there be a drop down of all countries or will the country pre-populate in each instance?   And  once country is selected or pre-populated will the list of provinces/states pre-populate based on what is configured for the instance?   (And fully assuming that 'county' is translatable -  we'd make it 'province' for example) Sorry if these things are assumed -  I'm just making sure.
