### ISSUE TITLE
The LettuceShare report not showing new products until they have been in an OC

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#743]
The LettuceShare report is not showing new products that are added to a supplying producer until it has been in the outgoing section of an OC run by the hub.
This is the case even when full E2Es are in place and the product has an on hand value >0 or on demand.

**Comment by lin-d-hop** [comment]
Closing as this issue is not well specced and the report is used by just one user. If this problem is significant enough for this user please reopen.

#gitcull21
