### ISSUE TITLE
Checkout 3rd step - Provide order summary page to the user

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#7434]
## Description

**- As a:** shopper
**- On page:** /checkout/order-summary 
**- I want to be able to do:** 

- check my details
- edit my details if needed
- check my selected payment method
- change my payment method if needed
- check my cart ('Order total')
- edit my cart ('Order total')  if needed
- check and agree to the 'Terms and conditions'
- go back to the previous steps if anything needs to be changed
- complete my order if everything is as I wanted

Designs are here:
https://www.figma.com/file/mwC9b6iUJxP29G4COnfkbC/Checkout-Overhaul?node-id=0%3A1

## Acceptance Criteria & Tests

1. When the user clicks on 'Edit your details', they get back to the 1st step 'Your Details' where they can see and edit their details
2. When the user clicks on 'Edit Payment Method', they get back to the 2nd step where they can see their selected payment method and change details if needed
3. When the user clicks on 'Edit Basket', they get back to the /cart page where they can see and edit their cart

![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/cd2c60ec-81a6-4f2d-a36c-048c0971d21a)

4. When the user wants to go back to the previous step, they can do so in 3 ways: by

- click on 'Back to Payment Method' Button
- click on the progress bar 1st step 'Your Details' or 2nd step 'Payment Method' (entire progress bar sections are click hit areas)
- click on the browser back button
 
5. When the user goes back to any of the previous steps for editing purposes, their progress stays saved so that the user can go back to the order summary after doing changes without starting from scratch

6. Depending on the instance,
- tax is displayed in a field ('Tax included') **below the order total for instances with tax included**, aggregating all taxes for products, fees & shipping already accounted for in the total price
- tax is displayed in a field ('Tax') **above the order total for instances with tax added**, aggregating all taxes that are added on products, fees & shipping to calculate the total price

7. For card or Paypal payments the user gets redirected to the respective Payment provider (depending on payment method selected) when they click on _"Complete Order"_ button.

8. 
8a. If user does not have a previously saved card, they will enter their details after placing order in step 3 -> so it should only show selected Payment Method (Design A)

8b. If user wants to pay with previously saved card, they will select in step 2 -> so it should show their details here on order summary (Design B)

**(A) Version for Instances with tax included and no card saved**
![Checkout - Order summary v3, no saved card - UK includes tax](https://user-images.githubusercontent.com/39744592/131340433-31654f71-21ed-4f1b-8fcf-d931a09e22b8.png)

**(B) Version for Instances with tax added and previously saved card**
![Checkout - Order summary v3, previously saved card - USA   CA separate tax](https://user-images.githubusercontent.com/39744592/131340824-6acf2c92-15b4-4089-bb73-c0d45a150dc4.png)

**Comment by jaycmb** [comment]
Rough Estimation

**Dev**
Frontend
Backend: 8 hours / 1 -1.5 days
-> including the spike 

**Testing**
3-4 hours / 0.5 day

**T-Shirt Size**
Frontend
Backend: M

**Testing**
M


Spike is needed to check if with the payment details entered after 3rd step, we can still save and display previously saved credit cards to the user in the 2nd step.

**Comment by jaycmb** [comment]
Note: Designs are NOT FINAL.
-> It´s one column as the previous steps but we need to wait for result from spike to decide if credit card details are displayed in this step or only selected payment method

**Comment by andrewpbrett** [comment]
> Spike is needed to check if with the payment details entered after 3rd step, we can still save and display previously saved credit cards to the user in the 2nd step.

Based on Stripe's docs, I believe this is possible. I'd also like to update my estimate to 12 hours/2 days :)

**Comment by jaycmb** [comment]
> I'd also like to update my estimate to 12 hours/2 days :) 

Done!

> Based on Stripe's docs, I believe this is possible.

Okay. Would this involve any UI changes in the 2nd step (where user can select previously saved cards) or just the way how to access the info would be slightly different than in the current process?

**Comment by andrewpbrett** [comment]
> Would this involve any UI changes in the 2nd step

The UI for the second step can look like it does in the Figma files, yes. There will be some changes to how we save the card behind the scenes, but nothing that will affect the UI really.

**Comment by jaycmb** [comment]
Okay, so the designs for this 3rd step would then look slightly different depending on if the user choose to use a previously saved card or not.

Added also to the AC in the issue description.

8a. If user does not have a previously saved card, they will enter their details after placing order in step 3 -> so it should only show selected payment method
(Screenshot 1) 
![image (15).png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/5f44819a-20bf-463e-8abb-8f7e069245c8)

8b. If user wants to pay with previously saved card, they will select in step 2 -> so it should show the details in step 3
(Screenshot 2)

![image (16).png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/18b9ddbd-96c9-4a9d-99c8-b76da460849d)

![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/86228f0c-0b58-49ec-bafd-3c8fb7093fd9)
**Version for Instances with tax included**
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/91d957ef-7b24-4b11-a3c7-7eedb7d8a1c![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/97b0234d-605c-497e-9188-aecca3130826)c)

**Comment by andrewpbrett** [comment]
That sounds right, thanks @jaycmb 👍

**Comment by Matt-Yorkley** [comment]
Technical note: we'll want to recreate our Angular `StripeElements` service and the directive that uses it. It looks a bit like this in StimulusJS: https://gist.github.com/Matt-Yorkley/6b9cd71e7c9a4c3839bd615f8a1e5720

**Comment by andrewpbrett** [comment]
@jaycmb in the Figma file, we have the Stripe modal for entering the card details (there's also the old form, on the summary page, but I believe we discussed that that was a mistake). 

Stripe has updated their [Stripe Checkout product](https://stripe.com/docs/payments/checkout) so that it's no longer a modal but rather a page hosted by Stripe. I just want to confirm that this is what we want to do; I did a quick test locally to see what it would look like:

<img width="1530" alt="Screen Shot 2021-08-28 at 2 08 28 PM" src="https://user-images.githubusercontent.com/35588/131231757-a6e62834-ab70-4875-b416-6558ead16dce.png">

We can customize the line items that show up and prefill the email address field as well. After filling out the payment information, the customer would be redirected back to OFN and see the confirmation screen. 

Let me know if that looks good to you.

**Comment by jaycmb** [comment]
>  (there's also the old form, on the summary page, but I believe we discussed that that was a mistake).

Yes, the designs have never been updated according to the outcomes of the spike that confirmed the new payment flow, I believe that was just after Eriol had left. I m going to adjust the files so we have the final version.

Yes, that looks good to me. 

3 questions

We might need to indicate, that the user is redirected to Stripe and after the payment will get back to OFN (now that it is a page and not a modal could be confusing otherwise).
Is there a template in the Stripe checkout product for this "transition"?

<img width="170" alt="image" src="https://user-images.githubusercontent.com/39744592/131306941-58ad08a2-17b4-4aa4-95c3-420430da3a30.png">
Would this be _Pay OFN_ or _Pay respective shop_, i.e. can be customized to respective food hub?

<img width="324" alt="image" src="https://user-images.githubusercontent.com/39744592/131306905-b53a659f-659b-4a64-b6b8-01c2e85f651e.png">

If the user confirms this, then their credit card details will be saved so that the user can next time choose already in the 2nd checkout step, right?

**Comment by andrewpbrett** [comment]
> Is there a template provided in the Stripe checkout product for this "transition"?

There's a demo app of sorts here: https://checkout.stripe.dev - it's pretty much what we have, a checkout page that then takes you to Stripe after clicking the Checkout button. We could potentially change the text of that button based on whether they'll be redirected or not. E.g. it could say "Complete Order" if you're paying with Cash later, vs. "Pay on Stripe" if you're about to be redirected.

> Would this be _Pay OFN_ or _Pay respective shop_, i.e. can be customized to respective food hub?

This can be customized to the respective shop 👍 

> If the user confirms this, then their credit card details will be saved so that the user can next time choose already in the 2nd checkout step, right?

Yes, if they choose to save their card we should get the token for that card back and allow the customer to use the saved card the next time they checkout.

**Comment by jaycmb** [comment]
> We could potentially change the text of that button based on whether they'll be redirected or not. E.g. it could say "Complete Order" if you're paying with Cash later, vs. "Pay on Stripe" if you're about to be redirected.

It´s better to stick with the "Complete order" (or place order), because this is the legal agreement of the user to enter the  contract.
I thought there might be a page loading in between before the user is redirected.
But we can add a line for card (or Paypal) payments above the CTA.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/39744592/132507818-0ffeaba3-1bd7-44b0-aa01-b3b93de123a4.png">

**Comment by Matt-Yorkley** [comment]
> Stripe Checkout product 

Wouldn't we just be adding an extra checkout page that shows the summary and details and address in that case?

**Comment by andrewpbrett** [comment]
There is a bit of redundancy here - we're showing the summary page with all the details, and then if they're paying with a new credit card, we're sending them to a Stripe checkout page where they'll see mostly of the same thing again, but with the credit card form. 

I think it has to look like this though, because of the requirement that the summary page can't have the payment form embedded on it - right @jaycmb?

**Comment by RachL** [comment]
I'm closing this one. We can use the tests described here when testing everything, but it does not need for this issue to be kept opened.
