### ISSUE TITLE
[Flaky] spec/features/admin/tag_rules_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#7444]
### What we should change and why (this is tech debt)

```
rspec ./spec/features/admin/tag_rules_spec.rb:16 # Tag Rules creating allows creation of rules of each type
```

### Context

https://github.com/mkllnk/openfoodnetwork/runs/2387841668?check_suite_focus=true

**Comment by mkllnk** [comment]
Closing in favour of #7667.

**Comment by jibees** [comment]
> Closing in favour of https://github.com/openfoodfoundation/openfoodnetwork/issues/7667.

Closing then. ;)
