### ISSUE TITLE
Customer subscription marked as not generated and no confirmation email sent to customer but order is placed.

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7449]
## Description

Enterprise ID 200270
Order Cycle ID 207778

Email sent to hub manager states that there was an error in placing order R182515644 

![suberror](https://user-images.githubusercontent.com/45104035/115539897-6dbf1c00-a295-11eb-8d28-494fa265a15e.jpg)

Order shows on the OFN platform as having been generated at 6:03 21/04/21

No order confirmation sent to customer.

Both customer and hub manager have misleading information as a result.

## Expected Behavior

Orders generated by subscriptions send an order confirmation email to the customer.
Hub manager only notified of errors to orders not placed.

## Actual Behaviour

Customer not sent an order confirmation email when their subscription order was generated.
Hub manager incorrectly informed of an error (false positive)

## Steps to Reproduce

1.
2.
3.
4.

## Severity

bug S2
User wishes to process between 170 - 200 subs a week and needs confidence in the system

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
Relevant Bugsnag: https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/607fb23b65df940007535d72?event_id=607fb23b0077bd8cb8bb0000&i=sk&m=nw

**Comment by Matt-Yorkley** [comment]
It's a `Net::OpenTimeout` error, which indicates it's the same thing that caused this recent issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/7401

It indicates that the server temporarily failed to connect to the email provider (in this case it's Sendgrid), so the email couldn't be sent.

Rummaging through the logs with:
```
grep -A80 -B80 "Net::OpenTimeout" /home/openfoodnetwork/apps/openfoodnetwork/current/log/production.log
```
I notice a couple of things: at this exact point in time we were essentially blasting a large volume of emails to Sengrid _all at once_. All of the others went though okay (before and after).

I'm wondering if that's a factor? Sending too many emails at once? Maybe they have some kind of rate limiting, or maybe the volume of attempts per second was just too high (on either end)?

**Comment by Matt-Yorkley** [comment]
Once we merge the 5.2 branch, we'll have a bunch of hot new options for handling exceptions with email sending in `ActionMailer`, which includes things like automatic retry on `Net::OpenTimeout` errors. Introduced some time between Rails 5.1 and 5.2, [it looks a bit like this.](https://github.com/rails/rails/pull/25991/commits/8b5c04e423cbfd90a15ed6fbab3f111803bc6544)

**Comment by sauloperez** [comment]
> which includes things like automatic retry on Net::OpenTimeout

but isn't DJ already doing this by default?

**Comment by Matt-Yorkley** [comment]
> but isn't DJ already doing this by default?

It didn't seem like it the other day :man_shrugging:

**Comment by sauloperez** [comment]
Aiaiaiai 🙈 🙈 this needs to be checked

**Comment by Erioldoesdesign** [comment]
Discussed in delivery circle - repopen if upgrade doesn't fix.

**Comment by sauloperez** [comment]
Alternatively, enqueuing the delivery of the summary emails would be slightly slower (we don't care much about it because the whole process happens async anyway) but they'd be retried by DJ in case of networks errors.
