### ISSUE TITLE
Deleting line items from shipped orders is possible through Bulk Order Management page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7457]
## Description

Shipping an order removes the icons to edit the line item quantity (and shipping method details) from the UI, to prevent orders from being edited after shipping :+1: 

However, it is still possible to remove a line item through using bulk order management feature :-1: 

Attempting to change the stock for that line item triggers:
https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60816e5b006e7d0007864736?event_id=60816e5b0077c2ac330c0000&i=sk&m=nw

Through the "Actions" menu one can remove the line item. Doing so introduces changes on the balance of the order. While this change is correctly reflected under admin/customers (admin view) and account#/transactions (customer view) one should notice that:

- if a (shipped) order is left with no line items, it will not appear on the `order_management/reports/bulk_coop` reports, which will lead to a misleading sum of customer balances.

## Expected Behavior

Line items from shipped orders should not be visible on the bulk order management page (right?)

## Actual Behaviour

Line items are appearing on the BOM page, which makes it quite tempting to edit:
- edit quantity -> bugsnag
- delete through the Actions menu -> customer balance discrepancies

## Steps to Reproduce

1. Create an order with **one line item**, add a payment and ship it. Take notice of the order number.
2. Notice that you can find this order on the on bulk order management reports (customer payments); check the balance for that customer (both on admin and customer side)
4. Now, look for the order on `admin/orders/bulk_management`
5. Try to edit the line item amount -> triggers bugsnag
5. Select (tick the checkbox) that line item and click the Actions menu -> Click "Delete Selected"
6. Notice that:
- customer balance changed (both on admin and customer side)
- the order does not appear on bulk order management reports
- you can visit the edit order page, but it displays a shipped order with no line items :-1: 

## Animated Gif/Screenshot

A shipped order. The UI does not allow to make changes here :+1

![image](https://user-images.githubusercontent.com/49817236/115713875-691a6680-a36e-11eb-8f3c-87f7cdd885e4.png)

Trying to edit the line item amount:

![image](https://user-images.githubusercontent.com/49817236/115715703-51dc7880-a370-11eb-811a-2b2fb5c00afe.png)

The same order, after following the steps to reproduce:

![image](https://user-images.githubusercontent.com/49817236/115716559-33c34800-a371-11eb-9e5e-61b27b9eac19.png)

## Workaround

Don't delete line items from shipped orders. However, nothing really tells you they are shipped, on the BOM page.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.5.7
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

I think making line items from shipped orders not visible through Bulk Order Management list would solve this.

**Comment by Matt-Yorkley** [comment]
Hey @openfoodfoundation/train-drivers-product-owners just for a bit of clarity on what we're actually trying to do here: 

Do we want to hide all line items for **shipped** orders from the BOM page? As they shouldn't be edited, and they can't be edited elsewhere. Would that be a shocking change for BOM fans?

Or do we want to show those items but not allow them to be changed? That seems like it would be complicated and we'd have to show errors whenever someone tried to edit them, which is weird.

**Comment by RachL** [comment]
@Matt-Yorkley I would go for the least complicated one at this stage (not displaying shipped orders). But maybe we can introduce a sentence on the BOM page saying that the list they are seeing is a list of orders that are completed but not shipped? To avoid having people searching for shipped orders and not understanding the problem. If needed, I can work on a quick mock-up to make it more clear if everyone is aligned with the idea.
