### ISSUE TITLE
i18ize the FlipperUI banner

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#7463]
<img width="604" alt="Capture d’écran 2021-04-19 à 14 46 03" src="https://user-images.githubusercontent.com/296452/115239293-d768ea00-a11e-11eb-879c-3b92c6fa6ffb.png">

> Any chance we can add a translation key for this?

_Originally posted by @Matt-Yorkley in https://github.com/openfoodfoundation/openfoodnetwork/pull/7437#discussion_r618561714_

Check if FlipperUI could also be translated.

**Comment by jibees** [comment]
At the end, I'm wonder if this has any sense:
 - FlipperUI cannot be translated (at this time)
 - Access to this UI is restricted to instance manager (who do the translation, so they already know how to translate this banner)
 - The wiki page we link is in english
 
 What do you think @Matt-Yorkley ?

**Comment by sauloperez** [comment]
> Access to this UI is restricted to instance manager 

and even more, we don't ask them to be responsible for toggles. The core team will deal with and make decisions about them. That made me doubt of the value of I18n here.

**Comment by jibees** [comment]
I'm wonder if @Matt-Yorkley or @openfoodfoundation/train-drivers-product-owners have any thoughts on this. 
If not, I'll close the issue.

**Comment by jibees** [comment]
2 days ago, I close the issue.
