### ISSUE TITLE
Add shipping category test coverage

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7470]
### What we should change and why (this is tech debt)

There are no feature specs for shipping categories superadmin settings. The relevant page is:
`/admin/shipping_categories` (superadmin)

Existing controller spec (delete missing):
`/spec/controllers/spree/admin/shipping_categories_controller_spec.rb`

Additional info:
https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ofn-platform-configuration/shipping-categories

### Context

Looking for dead spots on test coverage.

### Impact and timeline

Part of our road towards continuous delivery.

**Comment by shen-sat** [comment]
Hey @filipefurtad0, [as mentioned on Slack](https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1621452405023500) I'd like to pick this ticket up :)

I will write the missing delete action controller spec 👍 

Regarding the feature spec, would the following user flow make sense?

- user logs in as super admin
- user visits /admin/shipping_categories
- user clicks "New Shipping Category"
- user creates a new shipping category
- user is redirected back to /admin/shipping_categories and sees new shipping category name

**Comment by filipefurtad0** [comment]
Hey @shen-sat , awesome - thanks for picking this up :muscle: 

Yes, that `create` flow makes perfect sense to me - sounds good!

**Comment by filipefurtad0** [comment]
Closing, as this is now covered by #7686 and #7909 - thanks @shen-sat :muscle:
