### ISSUE TITLE
Shipping Tax Duplicated

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7474]
## Description

Shipping tax is displaying twice on invoices, customer order confirmation emails and on order adjustments: both UK and EU zone rates are being applied to UK sales.

![taxadjustments](https://user-images.githubusercontent.com/45104035/115867366-edceb880-a432-11eb-8bb5-5f88b1693ce3.jpg)
![taxemail](https://user-images.githubusercontent.com/45104035/115867389-f4f5c680-a432-11eb-97cf-a5148f90703a.jpg)

## Expected Behavior

Tax on shipping is displayed for one Zone (UK) only .

## Actual Behaviour

Tax on shipping is displayed for two zones (UK and EU)

## Steps to Reproduce

1.
2.
3.
4.

## Severity

S2

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
Fixed :+1: Details in Slack.
