### ISSUE TITLE
Error 500 when performing actions on orders

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7492]
## Description

Triggering certain actions on the Actions Menu cause error 500. These include the following actions on orders:
- cancelling
- shipping
- re-sending order confirmation
- resuming

Also:
- returning items

Triggers the same error. Bugsnag:

https://app.bugsnag.com/yaycode/openfoodnetwork/errors/6086e256e633fa0007d59dcc?event_id=6086e2560078079b7c160000&i=sk&m=nw

After seeing the snail, the triggered action actually has the expected outcome - just the UI displays the error.

If a customer cancels the order it also triggers an error. In this case, the order does not change state:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6087dafd643c530007e32686?event_id=6087dafd00781cc1ed410000&i=sk&m=nw

I'm adding the customer case here as well, as it seems related. Both seem to point to `app/controllers/spree/orders_controller.rb`.

## Expected Behavior

Order actions (the above mentioned) should not trigger errors.

## Actual Behaviour

Order actions (the above mentioned) should trigger visible errors in the UI and Bugsnag.

## Steps to Reproduce

1. Log in as admin and edit an order
2. Try any of the following actions: cancelling, shipping, re-sending order confirmation, resuming
3. See the error but notice the intended action did take place (for example, the order state changed as expected)
4. Log in as a customer
5. On a hub which allows chances to orders: cancel the order

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/116221693-c125e400-a745-11eb-964a-6cca60ff5e4c.png)

## Omitting further sections 
Since this is a 5.2 regression, I would think it's ok to omit other sections from bug reports, such as severity, workarounds, version... right? I'd add them only if relevant to the bug at hand.

**Comment by Matt-Yorkley** [comment]
Thanks!

So the error is:
```
NoMethodErrorspree/admin/orders#resend
undefined method `back_url' for #<Spree::Admin::OrdersController:0x000000000b6a0558>
```
which is caused by the use of `redirect_to :back`: 
https://github.com/openfoodfoundation/openfoodnetwork/blob/0194e39bd2c742f87addfe8367fb9e7fdaa00946/app/controllers/spree/admin/orders_controller.rb#L71

which has apparently changed in 5.2... should be a really simple fix :ok_hand:

**Comment by filipefurtad0** [comment]
PR #7522 fixes it :tada: 
Closing.
