### ISSUE TITLE
[Release Blocker] Payment and shipping state displayed as NONE in the UI (after cash payment) -> causing Payment reports to break 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7494]
## Description

It all looks quite similar to the previous issues #7021 and it's root cause #7003.

When placing backoffice orders, adding an uncaptured cash payment leaves the order with Payment and shipping state displaying as NONE, which then breaks the payments report on`Itemized Totals` and `Payment totals`.

## Expected Behavior

Orders should have the correct Payment and shipping states; relevant reports should render.

## Actual Behaviour

Orders with uncaptured cash payments display Payment and shipping state displayed as NONE in the UI and break the payments report.

## Steps to Reproduce

Log in as admin:
1. Create an order in the backoffice
2. On payment details: add a cash payment (don't capture it)
3. After clicking Update, notice the Payment and shipping state of the order changing to NONE
4. Visit `/admin/reports/payments` and select one of the report types `Itemized Totals` or `Payment totals`
5. Generating the report should trigger the snail

## Animated Gif/Screenshot

After an un-captured cash payment (backoffice order):
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/53f186d9-a9f1-446f-b32d-3bb14060e527)

After reaching this state, `/admin/reports/payments` and selecting: `Itemized Totals` and `Payment totals`:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e89c5dff-2005-4300-a25b-ac06465ad272)

## Workaround

Capturing the payment? One would need to be aware of this...

## Severity

s2 - Blocking the release, as discussed [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/7433#issuecomment-827490538).

## Your Environment

* Version used: v3.6.8 
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by Matt-Yorkley** [comment]
Just to clarify; it's only backoffice orders that are affected?

**Comment by filipefurtad0** [comment]
Yes, placing cash orders through the shopfront displays the order states as before, even before capturing the payment. I found no scenario in which this is affecting shopfront orders...

**Comment by RachL** [comment]
> Capturing the payment? One would need to be aware of this...

I think I've captured "like a machine" during my release test, sorry team :(
