### ISSUE TITLE
Shipment fee (adjustment) not persistant when creating BO orders

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7502]
## Description

When creating an order in the backoffice, after adding customer details, the admin can change the value of the Shipment fee, in the Adjustments tab, by editing this entry, in the Adjustments table. After doing this, it can:
- proceed to Order Details and click Update and Recalculate fees
- proceed to Payments

In any of these cases, the edited value returns to zero, after a payment is added to the order (this changes the order state). This means, that the initial payment considered the value, but after adding it, the order total has changed.

## Expected Behavior

Edits made on the Shipping fee should be persistent, till the order is concluded.

## Actual Behaviour

Edits made on the Shipping fee are not persistent: they get wiped out, once a payment is introduced.

## Steps to Reproduce

1. Create a new order in the BO
2. Add line items
3. Add customer details
4. Click the Adjustments tab
5. Edit the amount from the "Shipment" fee: change it from zero to, say, 10.
6. Click Continue.
7. Go to payments, and add any payment
8. Notice the changing order total: the edited amount for shipment is back to zero.

## Animated Gif/Screenshot

![Peek 2021-04-28 12-09.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/dc8e0970-c87f-4ec1-9115-122223a0cefb)

## Workaround

Adding the shipment after the payment was taken.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.6.9
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu

**Comment by Matt-Yorkley** [comment]
Yeah, we need to make some improvements to the way we show things in that adjustments tab. The shipping fee is re-calculated based on the shipping method when the order is saved. I don't think this is new in v3.6.9.

**Comment by filipefurtad0** [comment]
After [this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/7805#issuecomment-880759459) it is not possible to edit shipping fees manually/arbitrarily. Closing.
