### ISSUE TITLE
Inconsistent rounding on some units

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7504]
## Description

Closely related to https://github.com/openfoodfoundation/wishlist/issues/6

There's some issues with rounding issues with units like L, inserting a value respective to a given unit appears in the "Display as" field as a decimal, with plenty of significant digits. (see pic/video below). This can easily appear in the shopfront.

A known combination is `Volume (L)`, with value `0.7`; others have been observed.

## Expected Behavior

Inserting 0.7 should appear as 700 mL.

## Actual Behaviour

Inserting 0.7 L appears as 699.99999999.... mL

## Steps to Reproduce

1. Create or edit a Volume (L) product.
2. Type 0.7 on the "Value" field.
3. See the "Display as" field.

## Animated Gif/Screenshot

![Peek 2021-04-21 21-38](https://user-images.githubusercontent.com/49817236/115617902-e2bc4100-a2e9-11eb-9e5f-64b4a848cea7.gif)

This value gets actually gets stored and is even displayed in the shopfront:

![image](https://user-images.githubusercontent.com/49817236/115618864-25cae400-a2eb-11eb-9210-cd13d1b53afb.png)

**Update**
This issue also appears on the inventory (https://github.com/openfoodfoundation/wishlist/issues/6) and Order Cycles page:
![image](https://user-images.githubusercontent.com/49817236/134367112-1ddaf9a5-78ea-4b2e-98e8-169745e66385.png)

## Workaround

You can edit the display as field and type any value, overriding the placeholder value.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: first spotted [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/7334#issuecomment-824348956), maybe v3.6.3?
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by jibees** [comment]
Ahah, ❤️  `javascript`: 

<img width="203" alt="Capture d’écran 2021-09-14 à 10 07 13" src="https://user-images.githubusercontent.com/296452/133220182-345c4ec8-774f-4059-b458-6abc44a3a94e.png">

**Comment by lauriewayne** [comment]
Possibly related: we are seeing a similar display problem show up when the "Display as" field is empty (i.e. default/auto generated). 

**In back end:**
![Screenshot 2021-11-07 9 21 27 AM](https://user-images.githubusercontent.com/37803238/140656978-c2ed699a-ae69-4e46-850f-2a0cad6de6fc.png)

**In shop:**
![image001](https://user-images.githubusercontent.com/37803238/140656945-7b49a8e4-abf1-4564-bb70-21de12cb14a1.jpg)

**When the "Display as" field is manually updated to "12 ounces" in the variant edit, the display looks better:**
![Screenshot 2021-11-07 10 24 52 AM](https://user-images.githubusercontent.com/37803238/140657103-917a8d68-0afc-455c-b78a-9abc17832f4b.png)

**But the back end still shows 11.999999999999998 even after manually changing it to 12:**
![Screenshot 2021-11-07 10 07 32 AM](https://user-images.githubusercontent.com/37803238/140657045-175254ba-2f3b-492a-b506-4f18da07298c.png)

**Comment by lauriewayne** [comment]
Looks like an imperial measures only issue. Moving this comment to #7072.

**Comment by drummer83** [comment]
Oh no, this one is back! :cry: 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/c880c75f-f285-4642-9c9e-d867f6bcb9ef)

Reopening!

**Comment by filipefurtad0** [comment]
Closing from merging PR #12950.
