### ISSUE TITLE
Order states inconsistency between subscription- and backoffice-placed orders

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7510]
## Description

Placing a orders with cards requiring 3D-auth from a) placing a subscription and b) backoffice order will lead to different order states.

It does not look right that orders should differ in state, when the exact same amount, items and payment methods are used; both are awaiting authentication from the shopper. See pic below.

## Expected Behavior

Order states should be consistent, regardless of the "path" taken to reach the point where authentication is required.

## Actual Behaviour

Order states differ, depending on the order "path": backoffice orders are in a "payment" state, whereas subscription orders are in a "complete" state.

## Steps to Reproduce

1. Place two identical orders: one via subscription and another through the backoffice; 
2. Check the order states on `/orders`

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/91d3a3b4-f9b6-48f5-ba11-e71b4a6c5a93)

## Severity

?

## Your Environment

* Version used: v3.6.9
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by filipefurtad0** [comment]
Together with @lin-d-hop we had a chat around this in the context of the [Order States work](https://docs.google.com/document/d/1seE9n8NQoJS-Gow9jk6Br5IXeC3uwpEhG0wYu_omhSs/edit). One way to address this could be to introduce a new order state to reflect the payment awaiting authorization from the customer, something like "Agreed?" or so.

**Comment by Matt-Yorkley** [comment]
I think what we're missing is a new _payment_ state for `requires_authorization`, which is the "new" element we've introduced into the checkout/payment flow, right? We previously didn't have payments that require authorization, and when they're in that state they don't fit neatly into our existing payment states (they're a grey are between the payment being `pending` and `paid`).
