### ISSUE TITLE
Items are displayed with plural option

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#7517]
## Description

Items are displayed with plural options, but it does not make sense for unit prices.

## Steps to Reproduce
1. Go to FR prod
2. Look at shops like https://coopcircuits.fr/les-jardins-ty-bio/shop
3. See item prices

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/e709c614-c59f-4c72-bb12-fba11245cd81)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v.3.6.9
* Browser name and version: All
* Operating System and version (desktop or mobile): Both

**Comment by jibees** [comment]
As far as I understand, this string is entered by user with `(s)`
<img width="1088" alt="Capture d’écran 2021-05-06 à 10 21 54" src="https://user-images.githubusercontent.com/296452/117265885-fcff2e80-ae54-11eb-8723-eeae28b82417.png">
<img width="267" alt="Capture d’écran 2021-05-06 à 10 22 01" src="https://user-images.githubusercontent.com/296452/117265896-fffa1f00-ae54-11eb-9c9f-2c72f85b774c.png">

And then we use it _as it_ to display unit price information. 

I'm wondering if there is any solution in that particular case... Maybe tell the user to not pluralize a unit name?

**Comment by RachL** [comment]
ah ok for some reason I thought we were using the display name!

My bad :)

Closing then. Thanks @jibees
