### ISSUE TITLE
Drop-down in the registration process do not work with the mouse on Chrome

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#752]
In the hub/producer/group registration process: https://www.openfoodnetwork.no/register 
When we select a country clicking on the country list with the mouse, on Chrome 47.0.2526.73 m and 47.0.2526.80 m (we tried with two computers with different versions), it doesn't work. With the arrows on the keyboard that works. And that works on Firefox.

![registrationbug](https://cloud.githubusercontent.com/assets/8135376/11919366/fcde8ace-a750-11e5-89ac-9e5806fb4e2b.png)

**Comment by blancnic** [comment]
It worked for me on Chrome 47.0.2526.106 m
Anyone else?

**Comment by myriamboure** [comment]
@blancnic it seems it works again, we tried and now it works as you say... So I close the issue :-)
