### ISSUE TITLE
Semaphore deployments fail on staging-FR

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7533]
## Description

Deployment jobs are failing on staging-FR. It seems to relate to a config/DNS issue between Semaphore and the server staging.

See for example:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/fr-staging/deploys/505

**Comment by Matt-Yorkley** [comment]
So... Semaphore is trying to deploy to `staging.openfoodfrance.org` instead of `staging.coopcircuits.fr`. But it should just be using the ofn-install inventory directly, and that doesn't use `staging.openfoodfrance.org` any more... :thinking:

**Comment by Matt-Yorkley** [comment]
Fixed :ok_hand:
