### ISSUE TITLE
Endless spinner when uploading logo and promo images

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7534]
## Description

When creating an enterprise, the user has the possibility do add a logo and promo images. These appear not to work: an endless spinner is displayed instead.

## Expected Behavior

The spinner should only be displayed till the image is fully uploaded.

## Actual Behaviour

The spinner does not disappear.

## Steps to Reproduce

1. Log in; click Register here on the homepage.
2. Fill in the details necessary to get to the step in which you are allowed to upload logo and promo images.
3. Select a file and click Upload.
4. See the spinner spinning.

## Animated Gif/Screenshot

![Peek 2021-05-03 10-51.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/786222a5-fad9-4fe8-ad61-68bb347385bb)

## Workaround

The images seem to actually be uploaded. So the workaround is to just move along to the next registration step.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.6.10
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by drummer83** [comment]
Hi @filipefurtad0, 
this one I can confirm for the German instance. 
I don't agree to the severity of s4 though. 
- It definitely does prevent users from using the paltform. If the registration process doesn't seem to work, many users might just leave the site. --> should be s3
- There is a workaround (just continue) but new users trying to register are not aware of that workaround and we cannot inform them about it - so it's basically not present. --> should be s2
- If you consider the registration process as critical (not sure, but probably is) ... --> even s1

Can you please consider upgrading this issue to higher severity? Maybe discuss it with Delivery Circle?
I really see this as very important to fix quickly. Thanks!

**Comment by jibees** [comment]
Got a js error: 
```js
VM5620:1 Uncaught SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at fromJson (all.js:28511)
    at defaultHttpResponseTransform (all.js:37583)
    at all.js:76688
    at forEach (all.js:27512)
    at FileUploader._transformResponse (all.js:76687)
    at XMLHttpRequest.xhr.onload (all.js:76774)
```

Because could not parse the response: 
```
"/images/enterprises/logos/9/medium/Capture_d%E2%80%99e%CC%81cran_2021-05-04_a%CC%80_13.27.33.png?1620808850"
```

Sent by:
https://github.com/openfoodfoundation/openfoodnetwork/blob/e60a513c88cd054145174cfda42b4be6ddcede8f/app/controllers/api/v0/enterprises_controller.rb#L47
