### ISSUE TITLE
Order Cycle Management Report not fetching "Hub Code" info

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7537]
## Description

On `admin/reports/order_cycle_management`, the Delivery report features a `Hub Code` column, which is not being populated, when rendering reports.

## Expected Behavior

 
(**edited**) `Hub Code` column should fetch the respective 'Customer Code', i.e., the hubs code for the customer

## Actual Behaviour

`Hub Code` column remains empty.

## Steps to Reproduce

1. Log in as admin and go to `admin/reports/order_cycle_management`
2. Select "Delivery Report"
3. Click "Search"
4. See the results for that hub: notice the Hub Code column remains empty 

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/7d5cddec-f52f-4b96-b777-01235b9e7d82)

## Workaround

Use the Name of the hub instead.
I'm not entirely sure of the use cases for this info.

## Severity

S3

## Your Environment

* Version used: v3.6.10
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu 20-04

**Comment by lin-d-hop** [comment]
In other reports 'Hub Code' is actually referring 'Customer Code' 

Sounds confusing, but It is the Hubs code for the customer. The name is unclear and should be updated.

For consistency this should certainly not refer to HubID but CustomerCode here.

**Comment by filipefurtad0** [comment]
I had a second thought on this, I think there's no bug here:

If one sets the customer code under `/customers`:

![image](https://user-images.githubusercontent.com/49817236/123429970-7eef1680-d5bf-11eb-9658-899010ee0f7f.png)


then it **does** appear on the report:

![image](https://user-images.githubusercontent.com/49817236/123430626-50be0680-d5c0-11eb-92a7-db3af7932bc8.png)

I find the designation `Hub Code` misleading, but I think this is something which can be decided each instance, by changing the respective key `report_header_hub_code`.

So I think we can safely close this issue :+1: Again, thanks for your input @lin-d-hop .

**Comment by lin-d-hop** [comment]
Nice one @filipefurtad0 
Sorry I didn't clock it earlier.... the field name is damn confusing :woozy_face:
