### ISSUE TITLE
Can't set inventory stock using the import tool

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7538]
## Description

On the inventory import template there is the option to include stock info, for a given product. It is therefore expected that stock info is updated by uploading a valid file, provided that the hub has permissions to do so, on that item. AFAIK, this includes:
- making sure the `Inherit?` field in not checked
- making sure that `On demand?` is set to `No`
- in case of a hub managing a producers stock: permission to manage stock should be granted by the producer

Even with these pre-conditions in place, it does not seem possible to set inventory stock, through the inventory import too. The error "Count_on_hand must be blank because using producer stock settings".

## Expected Behavior

Having the correct settings in place, stock info (on_hanb) is updated by uploading a valid file.

## Actual Behaviour

Despite having the correct settings in place and the file being valid, the stock info (on_hand) cannot be updated via inventory import. The error "Count_on_hand must be blank because using producer stock settings" is displayed.

## Steps to Reproduce

1. Add a product to the inventory and, on the inventory page, set:
2. `Inherit?` field as not checked
3. `On demand?` to `No`
4. Create a valid Inventory upload file; choose a stock (on_hand) which differs from the current value
5. Try to upload the file
6. See the error "Count_on_hand must be blank because using producer stock settings"

## Animated Gif/Screenshot

Below: inventory page tab (left), import tool tab (right)
![image](https://user-images.githubusercontent.com/49817236/116887919-c2ae4b00-ac22-11eb-911e-47af5c3d0622.png)

Used CSV file:

![image](https://user-images.githubusercontent.com/49817236/116888552-84fdf200-ac23-11eb-90ad-5f6b3960a767.png)

```
producer,distributor,name,display_name,variant_unit_name,sku,units,unit_type,price,on_hand,on_demand
Noname Hub,Noname Hub,Bread,Bread,,,2,kg,2,22,

```

## Workaround

Make the desired changes manually, on `admin/inventory`

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.6.10
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by tschumilas** [comment]
Permission needs to be given for 'add to inventory'  not just managing products or adding to order cycle (just checking that is the case for you @filipefurtad0 ).  And -  I'm surprised that inherit has to be unchecked?   I thought inherit was irrelevant (in terms of inventory import).  And in your import file for the above -  'on demand' should be set 0.

**Comment by filipefurtad0** [comment]
That's it @tschumilas - thank you for feedback. It worked by setting the `on_demand` to zero (below stock is set from 33 to 22):
![image](https://user-images.githubusercontent.com/49817236/117114761-28feaf00-ad84-11eb-9517-b58595bb2054.png)

Many thanks! :pray: Closing.
