### ISSUE TITLE
Switch caching backend from Memcached to Redis

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7541]
#### Description

We need to make a couple of changes to our caching backend in order to use StimulusReflex. 

#### Why?

Whilst the _basic_ caching features used by the regular Rails cache are essentially the same in Memcached and Redis, Redis provides some higher-level functionality for interacting with Ruby objects in the cache, and StimulusReflex uses some of those advanced features directly.

Also I think traditional session handling doesn't play nicely with Websockets, but this option does :ok_hand:
 
#### Requirements

It should be pretty simple, but the plan looks like this (and should be done one step at a time):

1. Install and configure Redis (ofn-install)
2. Switch the cache store from Memcached to Redis (main repo)
3. Switch the session store from ActiveRecord to Redis (main repo)

Parts 1 and 2 should be implemented and tester together. Part 3 can be done afterwards.

**Comment by Matt-Yorkley** [comment]
**Estimates:** 

I had a quick play with parts 1 and 2 at the weekend, I can drop a couple of PRs in about 20 minutes.

Part 3 might need a bit more finesse, I'd estimate 1-2 hours of dev time and a bit of sysadmin/devops discussion around deployment.

**Comment by RachL** [comment]
@Matt-Yorkley the main thing left here is ActiveRecord right?

**Comment by Matt-Yorkley** [comment]
We can probably just close this for now (since most of it is done) and wait and see if we need to switch the session storage from ActiveRecord.
