### ISSUE TITLE
Stripe payment rejected for shoppers bank card: no reason given

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7577]
## Description

Shopper wishes to pay for their OFN order using a VISA card associated with a specific bank.  Using a card from this bank (not sure which bank) repeatedly throws up the error messages:
 'Error your card was declined' 
and
'There was a problem setting up your card in our payment gateway...'

See screen shot:
<img width="937" alt="Screenshot 2021-05-06 212045" src="https://user-images.githubusercontent.com/45104035/117447193-17103e00-af35-11eb-9231-30399015526b.png">

They can use a card from this bank to pay at other websites online.
Their card for this bank has recently been replaced and the same issue occurs with the new version.  (Could the error be linked to the bank?)

user id 209621
enterprise shop id 201342

In the end they always pay using a card from a different bank but are extremely unhappy (I assume they might get cash back or similar for using a specific bank card).

I can not find trace of the error messages on bugsnag or in Stripe in order to advise the next course of action.

Order IDs (orders completed with a different bank card, unsuccessful attempts using the bank card which is rejected would have been made shortly before each successful one):
R850725848 06/05/21 21:26
R845851501 22/04/21
R461078732 07/04/21
R363377132 25/03/21 

## Expected Behavior

Card payment rejected generates an error to inform the shopper of steps they can take to ensure the next attempted payment is successful.

## Actual Behaviour

Card payment rejected with ambiguous error message

## Steps to Reproduce

1.
2.
3.
4.

## Severity

Not sure. Seems like just one customer, but potentially could be lots.
bug level S2 ?

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by andrewpbrett** [comment]
This is what I found in the Stripe logs:

<img width="551" alt="Screen Shot 2021-05-07 at 8 59 42 AM" src="https://user-images.githubusercontent.com/35588/117477206-92acc380-af12-11eb-9888-4a01c1522235.png">

There's three attempts all with this error message right before the successful one yesterday, so I'm pretty sure that's the customer in question. (I can send you the last four of the card number @lbwright22 if you want to double check with them). 

To find the error, I switch to viewing the dashboard as that Enterprise in Stripe, and then went to Developer > Logs.

This sounds similar to some other issues that have come up in the past, but I don't know if there's anything we can do about it, other than to follow up with the customer and/or Stripe and facilitate those two parties getting to the bottom of why Stripe is declining the card. The error message is reporting everything we know, unfortunately. 

I'm going to mark this down to an S3, but I think we could probably close it entirely if you agree @lbwright22.

**Comment by lin-d-hop** [comment]
Agree this can be closed. This is a general error message and there just isnt much more we can offer to the shopper :-(
