### ISSUE TITLE
New producer sign ups on UK production get an 'untrusted website cert' notice from UK staging

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#758]
we signed up a new producer and they received this email
-------- Forwarded Message -------- 
Subject: 	Please confirm your email for Ecolibrium
Date: 	Sun, 27 Dec 2015 21:45:07 +0000
From: 	hello@openfoodnetwork.org.uk

Reply-To: 	please-change-me@config-initializers-devise.com

To: 	ecolibriumnow@riseup.net

Open Food Network UK 

 
	Hi, Greg Dance! 
A profile for Ecolibrium has been successfully created! To activate your Profile we need to confirm this email address. 
 
Please click the link below to confirm your email and to continue setting up your profile. 
Confirm this email address » 
 
After confirming your email you can access your administration account for this enterprise. See the User Guide to find out more about Open Food Network UK's features and to start using your profile or online store. 
 
Cheers, 
Open Food Network UK Team 
 
Connect with Us: 
Facebook Twitter LinkedIn 

 
Email us: 
hello@openfoodnetwork.org 

 
	Terms of service | Open Food Network UK 

When he clicked on the link he got this message (NB the link shows that it is coming from our staging server)
![producer sign up](https://cloud.githubusercontent.com/assets/10517702/12050717/17424cdc-aef1-11e5-8c5d-4eae040a55d8.jpg)

Do we need to redirect these sign ups to production instead of staging?

thanks
Nick

**Comment by kirstenalarsen** [comment]
need to fix your ssl cert probably - I suspect paul would be best person to do this

**Comment by NickWeir63** [comment]
hi @pmackay 
is this something you can help with?
thanks
Nick

**Comment by pmackay** [comment]
Had a quick look, I need to work out what generates the confirmation URL and why it would point at staging. Will take longer to dig into this. Unsure why "untrusted" issue is happening as I renewed the staging certs at end of Nov.

**Comment by stveep** [comment]
We noted this in the reply-to field the Skype today, which looks like it should be changed!

```
Reply-To: please-change-me@config-initializers-devise.com
```

**Comment by NickWeir63** [comment]
Now new producer signups on UK production are getting grumpy cat at the end of their sign up.  However the sign up seems to work and they then receive this email (which (as a separate issue) needs the email address in the body of the text changing from hello@openfoodnework.org to hello@openfoodnetwork.org.uk)........
![screenshot 2016-01-25 10 56 22](https://cloud.githubusercontent.com/assets/10517702/12549078/afc30ad0-c352-11e5-85fb-9681fcbcd2fc.png)

but when I ckick on the acticvation link in the email I get this screen.....
![screenshot 2016-01-25 10 55 46](https://cloud.githubusercontent.com/assets/10517702/12549104/d9ae00d4-c352-11e5-8cf2-917804883e1c.png)

.....which then changes to this screen
![screenshot 2016-01-25 10 55 28](https://cloud.githubusercontent.com/assets/10517702/12549120/ec05b2cc-c352-11e5-8108-f57257281b21.png)

**Comment by pmackay** [comment]
@lin-d-hop assigned this to you, but also just noticed i did some stuff in #569 which never got merged.

**Comment by lin-d-hop** [comment]
I think all things raised in this issue have been fixed with #793 and the recent deployments.

Awaiting merge on #793 then will test on staging.

**Comment by lin-d-hop** [comment]
Everything in here is either resolved or being merged with #793.
Closing.
