### ISSUE TITLE
Grumpy cat prevents superadmin deletion of enterprise from UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#759]
When we log in as superadmin and try to delete Hania Cheeses from UK production ..................
![screen shot 2015-12-30 at 12 29 59 3](https://cloud.githubusercontent.com/assets/10517702/12051151/13b1fc92-aef7-11e5-9f84-3dc24dfe60c4.png)

.................we get the grumpy  cat (with a red background!)
THis is not urgent but we thought it might be a clue to something more important 
![screenshot 2015-12-30 13 12 43](https://cloud.githubusercontent.com/assets/10517702/12051154/22ebfadc-aef7-11e5-8ee5-3e38db811edb.png)

**Comment by kirstenalarsen** [comment]
known issues, you can’t delete enterprises, non-urgent - https://github.com/openfoodfoundation/openfoodnetwork/issues/359 <https://github.com/openfoodfoundation/openfoodnetwork/issues/359>

**Comment by NickWeir63** [comment]
OK thanks
