### ISSUE TITLE
grumpy cat when loading image to product on UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#760]
When adding image - see screenshot we get grumpy cat when we click update.  We have tried logging in as superadmin and get same error
![screenshot 2015-12-31 10 52 49](https://cloud.githubusercontent.com/assets/10517702/12063799/e6942742-afac-11e5-940f-f47f5b7c97dd.png)

**Comment by NickWeir63** [comment]
I have just tried uploading images to the same product on the staging server and it uploads fine.  So I think this means that whatever is causing this problem is either;
a) a code difference between the versions on UK production and UK staging or
b) something to do with the images settings on production (could they be set to staging???)

@pmackay please could you try deploying the new version to Production and see if that solves this image loading problem?

**Comment by pmackay** [comment]
Currently staging has @stveep's branch for inventory. Can that be merged into master first? We shouldnt be pushing feature branches to production, only master.

**Comment by NickWeir63** [comment]
OK thanks @pmackay 
I am happy for Steve's inventory branch to be merged into master as long as we are OK with ignoring the non-replicable error that i logged in issue 404 (link pasted below).  What do you reckon?
If we are OK to merge Steve's branch into master is that something we can do or do we need to ask for Aus help?
thanks
Nick
Issue 404 https://github.com/openfoodfoundation/openfoodnetwork/issues/404

**Comment by pmackay** [comment]
@stveep can you confirm what the inventory branch status is? Can it be or is it merged to master?

**Comment by stveep** [comment]
It could go into master as is, but it will eventually be merged via @oeoeaio's ng-vo-inventory-reset branch; we can look at merging this branch (uk/default-inventory) separately if the need for this becomes urgent. Go ahead and deploy something else to staging if you want.

**Comment by pmackay** [comment]
Its not about changing staging, its about moving this to production, but I really dont want to push anything other than master to production. So is it best to wait? Any idea of timing re the `ng-vo-inventory-reset` branch?

**Comment by daniellemoorhead** [comment]
@oeoeaio is back in tomorrow (Wednesday Aus time) so he'll be able to answer that question very soon!

**Comment by oeoeaio** [comment]
Sorry @pmackay @stveep,

I was planning on getting `ng-vo-inventory-reset` into master before Christmas but didn't quite get there. Hoping to be able to get it through today or tomorrow.

**Comment by NickWeir63** [comment]
Lynne mentioned that Paul was rolling back to a previous version on Production last night so I just tried again to upload an image but got grumpy cat again.

**Comment by lin-d-hop** [comment]
No production deploy has been done given the funding meeting this morning. I've been having issues for a while with images on production, along with other issues. Hence the requested deploy to a named release version.
We can look into images after the deploy and better document.

**Comment by pmackay** [comment]
@NickWeir63 I deployed v1.4 to prod today. Was able to upload an image ok. Please could you do more testing with the appropriate images? :)

**Comment by NickWeir63** [comment]
great thanks @pmackay - yes image loading works fine now and i put in a test order that all seemed good too.  Thank you
