### ISSUE TITLE
Unit price: when decimal separator is a comma, could not compute unit price 

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#7602]
## Description
As an admin, if I want to edit variant (eg. `http://localhost:3000/admin/products/produit-1/variants/52/edit`), and if I use the comma as the decimal separator, unit price could not be computed (field is empty): 
<img width="380" alt="Capture d’écran 2021-05-10 à 17 28 27" src="https://user-images.githubusercontent.com/296452/117684284-230a3300-b1b5-11eb-911b-d79613df2b60.png">

This is due to the magic of js:
```js
!isNaN("1.0")
true
!isNaN("1,0")
false
```

See line: https://github.com/openfoodfoundation/openfoodnetwork/blob/17a0063b40f2fb2ecd60cfaaec790cd9e209d6d1/app/assets/javascripts/admin/products/services/unit_prices.js.coffee#L4

## Expected Behavior
As a shop manager using comma as decimal separator, I want to see unit price when I edit a variant.

## Actual Behaviour
As a shop manager using comma as decimal separator, I could not see unit price when I edit a variant.

## Steps to Reproduce
1. Create a product with price `1` (url: `http://localhost:3000/admin/products/new`)
2. Display the list of products and click on the button to edit the associated variant of this new product
3. See that the price is `1,00` and therefor no unit price is displayed

## Severity

bug-s2: a non-critical feature is broken, no workaround

**Comment by RachL** [comment]
Does it also not appear on the shopfront or only on this page? If only on this page, maybe this can be downgraded to s3.

**Comment by jibees** [comment]
There's a lot of inconsistencies here...
We've got a global settings that is set by instance managers which is `currency_decimal_mark`:
<img width="266" alt="Capture d’écran 2021-05-10 à 22 07 11" src="https://user-images.githubusercontent.com/296452/117719214-6aa4b500-b1dd-11eb-99b7-4a05bb310425.png">

But, in angular part, we often use the default client decimal separator which could be different. And here comes the pain.

**Comment by jaycmb** [comment]
The majority of European countries but UK uses the decimal comma as separator, so this is not such a rare case to happen.
