### ISSUE TITLE
Possible wrong entry name for translation in Order Datail page

### ISSUE THREAD

**Issue by marito59** [openfoodfoundation/openfoodnetwork#761]
In file `app/views/spree/shared/_order_details.html.haml`, there are 2 strings for a label under the entry name `order_produce` that seems to be totals. Can you confirm that the entry name is right ?

Shouldn't we have 2 differents entries:
* order_subtotal for line 126 (first line with Produit in screen below)
* order_total for line 143 (second line with Produit in screen below)

![order_detail](https://cloud.githubusercontent.com/assets/11704159/12127263/7a1a3ff4-b3f6-11e5-96b6-c20628461fb4.png)

**Comment by daniellemoorhead** [comment]
@RohanM, @mkllnk, @oeoeaio?

**Comment by mkllnk** [comment]
You are right, that's a mistake. The second one should be `order_total_price`. I will fix that one. Thank you!

**Comment by daniellemoorhead** [comment]
@mkllnk was this completed as part of v1.4? If yes, can you please close this issue. If no then can you please let me know which milestone it should be moved to.
