### ISSUE TITLE
NoMethodError in spree/admin/line_items#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#762]
## Exception in OpenFoodNetwork

**NoMethodError** in **spree/admin/line_items#update**
undefined method &#x60;destroy&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=568c72382401836537b55400)
## Stacktrace

```
app/controllers/spree/admin/line_items_controller_decorator.rb:48 - block in apply_enterprise_fees_with_lock
app/controllers/spree/admin/line_items_controller_decorator.rb:47 - apply_enterprise_fees_with_lock
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=568c72382401836537b55400)

**Comment by mkllnk** [comment]
It looks like `destroy` is called twice on a line item from time to time. We should investigate how that happens and make that method fail safe.

**Comment by daniellemoorhead** [comment]
Happened twice since Dec 31, impacts on orders in admin.

**Comment by mkllnk** [comment]
I was not able to reproduce this error within an hour. This error can happen when you edit an order and you reduce the quantity of a line item to 0. The actual error occurs within the spree module. So we can't tell which line of code is producing this error. The effect for the enterprise user is probably that the change of quantity doesn't take effect. That can lead to a bigger order than intended.

The next step should be improving the error reporting on that page.

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **spree/admin/line_items#update**
undefined method &#x60;destroy&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5695da1862be12cb72c520c5)

## Stacktrace

    app/controllers/spree/admin/line_items_controller_decorator.rb:48 - block in apply_enterprise_fees_with_lock
    app/controllers/spree/admin/line_items_controller_decorator.rb:47 - apply_enterprise_fees_with_lock

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5695da1862be12cb72c520c5)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **spree/admin/line_items#update**
undefined method &#x60;destroy&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5695dc7e1b9bea175e585bf3)

## Stacktrace

    app/controllers/spree/admin/line_items_controller_decorator.rb:48 - block in apply_enterprise_fees_with_lock
    app/controllers/spree/admin/line_items_controller_decorator.rb:47 - apply_enterprise_fees_with_lock

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5695dc7e1b9bea175e585bf3)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **spree/admin/line_items#update**
undefined method &#x60;destroy&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=569d66a424cdf221522dbd7d)

## Stacktrace

    app/controllers/spree/admin/line_items_controller_decorator.rb:48 - block in apply_enterprise_fees_with_lock
    app/controllers/spree/admin/line_items_controller_decorator.rb:47 - apply_enterprise_fees_with_lock

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=569d66a424cdf221522dbd7d)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **spree/admin/line_items#update**
undefined method &#x60;destroy&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=569f2fbe090d887e4d5896c1)

## Stacktrace

    app/controllers/spree/admin/line_items_controller_decorator.rb:48 - block in apply_enterprise_fees_with_lock
    app/controllers/spree/admin/line_items_controller_decorator.rb:47 - apply_enterprise_fees_with_lock

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=569f2fbe090d887e4d5896c1)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=56c2a74d54ebfdd243d3d343)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=56d50118a42e3f765a5da2b5)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=56d77ed00772dedd57003ec9)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=56f9ee11259734d96053d4da)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=56fb3f8168297a196726018d)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=570333d67fe201b770b7d97f)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=570c130979fb7bb87be9a4ae)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57145f4f7ea6283d5689bc8a)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=571ee043836738821f6040a0)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=572953ae6054231b734b59ab)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57412c2f5478e2996fe3a4bc)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57425ae336466cd26eb4a8c6)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5746ba9f53ba10366d3f390e)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5769e2136587147668612d0a)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=576d94567af4521620ef7011)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=577c5d7883dddc6e0ec5e04a)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57841041c36820b9572ee241)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=578d6d8e8f26251764bde0a8)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5796a1f1550e0fd961af920c)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=579b48c8a456fffa509ac50c)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57b23c7d717a8210007a0568)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57b859a3c373151000cb4f23)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57c62c16364b7e1100e65fb8)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57d7186d98e126120099f5a7)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57e1c6ff6a67f81100b3adf6)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57f2d6c4eba4ad1100e0e012)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=57fbf9814b7cad1100bbaa94)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5805a3b2897ad8110017e666)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58147780013b8b1100f19158)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58317884fb65af1100969941)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=583bbefb7f8b771100322477)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5848950292e9121000a45ff1)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=585a1ab21fe398100015c8b5)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=587d95f588dd911200f6c626)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=5882de2f4af195110083eb79)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=589a4104f15b4711007c3490)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58a24df640bd691200b40d1b)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58b7ff52f66bb4110080a2d4)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58c92788d6c0431100d90b8f)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58cc45207e8eb3160071247c)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58e1e7f91c8c0117003a0744)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58e94882c9339b001856e9a6)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58ef810f64db7300192e8164&i=gh&m=ra)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **spree/admin/line_items#update**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5684967607141bdbdac2f568?event_id=58fd80b1011e2d00190cd4b9&i=gh&m=ra)
