### ISSUE TITLE
Remove obsolete/redundant lines in `setup/script`

### ISSUE THREAD

**Issue by shen-sat** [openfoodfoundation/openfoodnetwork#7624]
### What we should change and why (this is tech debt)
Myself and another new developer recently joined the project. We came across a few redundant/obsolete lines in the `script/setup` file.

Removing redundancies and doing a general cleanup of `script/setup` will help new developers by:
a) removing unneccessary setup commands from blocking setup
b) aid diagnosis when one of the setup commands fail

### Context
https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1620397593134200
Linked issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/7613

### Impact and timeline
Shouldn't take longer than 3 days. Impact: better onboarding experience for new developers ✨

**Comment by mkllnk** [comment]
I think that this was solved with the associated issue.
