### ISSUE TITLE
NoMethodError in admin/order_cycles#index

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#763]
## Exception in OpenFoodNetwork

**NoMethodError** in **admin/order_cycles#index**
undefined method &#x60;has_spree_role?&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=568b39c230bafcb00b851427)
## Stacktrace

```
app/models/order_cycle.rb:50 - block in &lt;class:OrderCycle&gt;
app/controllers/admin/order_cycles_controller.rb:104 - collection
app/controllers/admin/order_cycles_controller.rb:126 - load_data_for_index
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=568b39c230bafcb00b851427)

**Comment by mkllnk** [comment]
It looks like the user is not always set correctly when managing order cycles.

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **admin/order_cycles#index**
undefined method &#x60;has_spree_role?&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=5699fb0ed1b0614f42736823)

## Stacktrace

    app/models/order_cycle.rb:50 - block in &lt;class:OrderCycle&gt;
    app/controllers/admin/order_cycles_controller.rb:104 - collection
    app/controllers/admin/order_cycles_controller.rb:126 - load_data_for_index

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=5699fb0ed1b0614f42736823)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **admin/order_cycles#index**
undefined method &#x60;has_spree_role?&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=56a0252fccc2722b35df4037)

## Stacktrace

    app/models/order_cycle.rb:50 - block in &lt;class:OrderCycle&gt;
    app/controllers/admin/order_cycles_controller.rb:104 - collection
    app/controllers/admin/order_cycles_controller.rb:126 - load_data_for_index

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=56a0252fccc2722b35df4037)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **admin/order_cycles#index**
undefined method &#x60;has_spree_role?&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=56ad468f89d421400aef0f1b)

## Stacktrace

    app/models/order_cycle.rb:50 - block in &lt;class:OrderCycle&gt;
    app/controllers/admin/order_cycles_controller.rb:104 - collection
    app/controllers/admin/order_cycles_controller.rb:126 - load_data_for_index

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=56ad468f89d421400aef0f1b)

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **admin/order_cycles#index**
undefined method &#x60;has_spree_role?&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=56b4589c84c6c8673a08e659)

## Stacktrace

    app/models/order_cycle.rb:50 - block in &lt;class:OrderCycle&gt;
    app/controllers/admin/order_cycles_controller.rb:104 - collection
    app/controllers/admin/order_cycles_controller.rb:126 - load_data_for_index

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=56b4589c84c6c8673a08e659)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **admin/order_cycles#index**](https://bugsnag.com/yaycode/openfoodnetwork/errors/566d38c715766f1ee3536aae?event_id=56d2584cd6e3385625e4f04d)

**Comment by RachL** [comment]
@mkllnk how about this one? Is this error still happening?

I'm sorry for all those questions. Please take your time to review them, it's not at all urgent ;)

**Comment by mkllnk** [comment]
This has not happened lately. Thank you for going through all these old issues. It's good to clear them up.

**Comment by RachL** [comment]
As last time was 3 years ago, I'm closing it and we will reopen it if this happens again. But I'm afraid it's too old and we won't come back here.
