### ISSUE TITLE
Set up Tag Manager for France to enable tracking of new checkout flow

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#7635]
## Description

1.
2. 
3. 
4.

**Comment by RachL** [comment]
The tag manager is set up, but it does not pick up events. I'm not sure where to look to debug this. 

Maybe the container that was set up for France contains errors?

**Comment by jaycmb** [comment]
Yeah I noticed that as well.
Who inserted the container in the code and when?

**Comment by RachL** [comment]
> Who inserted the container in the code and when?

I inserted the container in the code following: https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ofn-platform-configuration/matomo

But I did not created the container. I thought Steeve might have done it? Or maybe Monica? 🤷

**Comment by jibees** [comment]
Did some changes on FR instance, and seems to be functional now:

<img width="582" alt="Capture d’écran 2021-09-20 à 10 48 13" src="https://user-images.githubusercontent.com/296452/133977182-51557458-46a7-440f-b86c-25b84461d0e9.png">
