### ISSUE TITLE
Product creation crashes with wrong image

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#764]
## Description

**Paperclip::Errors::NotIdentifiedByImageMagickError** in **spree/admin/images#create**
Paperclip::Errors::NotIdentifiedByImageMagickError

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54b04f4499b2cdc8b867a1f8?event_id=568a55383644892447eda417)
## Stacktrace

```
gems/paperclip-3.5.4/lib/paperclip/geometry_detector_factory.rb:10 - make
gems/paperclip-3.5.4/lib/paperclip/geometry.rb:26 - from_file
bundler/gems/spree-afcc23e489eb/core/app/models/spree/image.rb:36 - find_dimensions
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54b04f4499b2cdc8b867a1f8?event_id=568a55383644892447eda417)

## Expected Behavior

The product image is either processed successfully (all images supported) or a helpful error message is given.

## Actual Behavior

The snail page appears and the user doesn't know why.

## Steps to Reproduce

1. Log in as enterprise user.
2. Go to products.
3. Create a product.
4. Fill in the details and upload an image that is not recognised. (Sorry, we don't have a test image yet.)
5. Submit the form.

## Animated Gif/Screenshot

Not recorded yet.

## Context

Australian users trying to create products.

## Severity

S3: The "create product" feature is broken in some cases. The workaround is to use a different image file.

## Your Environment

* Version used: 5c8a638320f06874065b0e87c237ba7853adc1f7

## Possible Fix

There are several ideas:

1. Investigate if we can support more image formats.
2. Show an error message telling that the image is no good.
3. Separate the image upload from the product creation form so that it's obvious that this step fails.

**Comment by mkllnk** [comment]
Errors while creating/uploading images are not handled and cause a grumpy cat. This one happens when someone uploads an image in an unknown format.

**Comment by mkllnk** [comment]
We just had a user in Australia report this again. They tried to create a new product and got stuck, because they just see an error page and don't know that it's the image. I will update the description with our issue template.

**Comment by sauloperez** [comment]
I don't see any exception handling neither in the `ImagesController` nor in the `Spree::Image` model. Not even in Spree 2.0, so I'm afraid will need to add it on our end...

**Comment by luisramos0** [comment]
I managed to upload a png.
I managed to upload a tif but the image doesnt show in the product list.
I managed to replicate the issue with a openEXR image (whatever that is, it was available as export format on my basic mac image editor), this is the error page I see:
<img width="1219" alt="Screenshot 2019-06-12 at 14 41 28" src="https://user-images.githubusercontent.com/1640378/59356192-481f6e00-8d20-11e9-9dd8-a93d29e6d700.png">

So, the problem isn't as bad as a snail page, the user sees
Paperclip::Errors::NotIdentifiedBy**Image**MagickError
There's a little indication that the image is the problem.

the same problem happens when uploading this file in the new product page, in the new image page and in the edit image page.

We need to show a user friendly error in all 3 cases.

**Comment by luisramos0** [comment]
in the create product page the endpoint with 500 is:
http://0.0.0.0:3000/admin/products
on the new image page the endpoint is: http://0.0.0.0:3000/admin/products/test/images
on the edit image page the endpoint is: http://0.0.0.0:3000/admin/products/test/images/1

**Comment by mkllnk** [comment]
@luisramos0 
>  the problem isn't as bad as a snail page, the user sees
Paperclip::Errors::NotIdentifiedByImageMagickError
There's a little indication that the image is the problem.

That was in dev environment, right? Server errors are not shown in production and replaced by a snail page.

**Comment by luisramos0** [comment]
ah, good point. thanks Maikel!
