### ISSUE TITLE
NoMethodError in spree/admin/shipments#edit

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#765]
## Exception in OpenFoodNetwork

**NoMethodError** in **spree/admin/shipments#edit**
undefined method &#x60;special_instructions=&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/561645df15766f1ee335f773?event_id=568486ff32828d214afd31e9)
## Stacktrace

```
bundler/gems/spree-afcc23e489eb/core/app/controllers/spree/admin/shipments_controller.rb:32 - edit
gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4 - send_action
gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167 - process_action
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/561645df15766f1ee335f773?event_id=568486ff32828d214afd31e9)

**Comment by mkllnk** [comment]
When trying to update a shipment, the shipment object is missing. Maybe it got deleted before?

**Comment by mkllnk** [comment]
## Resolved error re-occurred in OpenFoodNetwork

**NoMethodError** in **spree/admin/shipments#edit**
undefined method &#x60;special_instructions=&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/561645df15766f1ee335f773?event_id=56a085007edcc6f5540990bd)

## Stacktrace

    bundler/gems/spree-afcc23e489eb/core/app/controllers/spree/admin/shipments_controller.rb:32 - edit
    gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4 - send_action
    gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167 - process_action

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/561645df15766f1ee335f773?event_id=56a085007edcc6f5540990bd)

**Comment by RachL** [comment]
@mkllnk is this safe to close as well?

**Comment by mkllnk** [comment]
Hasn't happened recently.
