### ISSUE TITLE
ActionView::Template::Error in spree/orders#show

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#766]
## Exception in OpenFoodNetwork

**ActionView::Template::Error** in **spree/orders#show**
undefined method &#x60;firstname&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/568090a307141bdbdab33876?event_id=568090b311b2ec7d51b409ce)
## Stacktrace

```
app/views/spree/shared/_order_details.html.haml:36 - _a0d87274ab1701ef97fa1064fd1c8893
app/views/spree/orders/show.html.haml:28 - _f7a41ec218b1eb64ede3ef70a11acdbb
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/568090a307141bdbdab33876?event_id=568090b311b2ec7d51b409ce)

**Comment by mkllnk** [comment]
The shipping address of an order is either not required or can get lost. A missing address causes an error.

**Comment by RachL** [comment]
@mkllnk did this had any new occurence since 2016?

**Comment by mkllnk** [comment]
No.
