### ISSUE TITLE
Error 422 (user facing) if stock is reduced before providing authorization

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7665]
## Description

Follow-up from PR #7649.

After an order is created in the backoffice and a Stripe-SCA payment is added, an email is sent to the customer to provide payment authorization. If stock is reduced during this time, when the customer provides authentication:

- an error 422 will be displayed (customer)
- no changes on the payment (admin; this can easily be seen as "the customer still has not provided auth.)
- the payment is successful and captured (Stripe Dashboard)

## Expected Behavior

Proposal:
Stock limitations should restrict payment creation (as imposed by #7649), but not payment capture: stock should be "reserved" for the order once a Stripe-SCA payment is created - I believe this is the case with confirmed subscription orders, which await payment authorization.

Also related: We could consider to order state should be "complete" ([as subs orders are](https://camo.githubusercontent.com/547899ad6f1f9dab41ebae752f5ae9236824a1fd7e03ab54e77399857c6a8c4c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564373631623034396464653635303030316561663332662f39316433613362342d663962362d343866352d626131312d653731623461366335613933)) while a new payment is awaiting authorization. A new payment state may be necessary to introduce here:

See discussion on this issue and comment https://github.com/openfoodfoundation/openfoodnetwork/issues/7510#issuecomment-841873665.

Ping @Matt-Yorkley @lin-d-hop @jaycmb @RachL 

## Actual Behaviour

If stock limitations occur within the time window from the moment the admin creates the payment till the time the customer provides authentication, the payment will be captured (on stripe), but an error is displayed to the customer; the order is left "not paid".

## Steps to Reproduce

As an admin:
1. Create a backoffice order with some items in the cart
2. Add a Stripe SCA payment method, card x-3184.
3. Reduce the stock for that item to zero.

As a customer:
4. Use the link received per email to authorize the payment -> see the cat.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/118865515-ecc96380-b8d8-11eb-87f1-f0b981ef8a83.png)

## Workaround

None.

## Severity

The time between payment creation and customer authorization can be long... which leaves plenty of time to stock reduction (I'm thinking what happens if an OC closes in the meantime?)
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v3.7.1
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

Related to #5784.

**Comment by Matt-Yorkley** [comment]
Ok, that's a non-trivial problem! This is partly due to the issues around the fact that backoffice order processing tries to do things the same as the checkout, but they're very different!

Anyway, what we ultimately need to do here is _complete_ the order (and reduce the stock) at the point the order is placed by the admin user, and leave the payment as "balance due". And we'll probably want to sort out the payment states issue around payments that are awaiting authorization: https://github.com/openfoodfoundation/openfoodnetwork/issues/7510#issuecomment-841873665
