### ISSUE TITLE
Can't delete order cycle/hub even without any order on it

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#768]
I tried to delete test hubs/order cycles we had created on the Norwegian instance:
- the hub Testblabla (no orders, order cycle, P2P relationship, products attached so we should be able to delete them)
- the order cycle "meat test" (no order attached so we should be able to delete them)
  But in both case, we have "uncompleted orders" with a "cart status" meaning we have been on the shopfront I guess, so it has created an order with the status "cart".
  And so we can't delete them.
  ![testblablacart](https://cloud.githubusercontent.com/assets/8135376/12138919/de1df52a-b45c-11e5-869e-c9bc998d3098.png)
  (we have to unclick "only show complete orders" to see them)

And I can't either delete those "cart status orders", so I'm stuck and can't clean anything... I have cancelled them but have no option to delete...
![order-cancelled](https://cloud.githubusercontent.com/assets/8135376/12139017/9308744c-b45d-11e5-934c-31a26102a338.png)

(see discussion here for reference: http://community.openfoodnetwork.org/t/clean-up-order-cycle-index-for-readability-and-faster-loading/96)

**Comment by nanoharsha** [comment]
Has there been any progress made against this ?
We are testing the same in the Indian instance and are also stuck at the same issue mentioned by @myriamboure as above !!

**Comment by myriamboure** [comment]
@nanoharsha from what I understood if you are bothered by those useless order cycle / hubs you have to delete them directly in the database... we are just leaving with them, they don't really bother us, they are closed and we use the search tools to filter what we search all the time, so we thought it was not a priority...

**Comment by nanoharsha** [comment]
@myriamboure  agree. Started ignoring and working on other important testing.

**Comment by nanoharsha** [comment]
@myriamboure , I have seen that in the current staging environment staging2.openfood.com.au, this error is no more. We tried to delete an order cycle and it surpisingly happened. 
I believe we did at a week back, and it didnt happen, but not completely sure.
I rechecked the release notes and didnt find any mention of any fix.
Can you verify from your end also, and if it is the same, we can notify the rest of the development team.

Cheers

**Comment by nanoharsha** [comment]
I dont have access to deleting enterprises, as I am not super admin, hence cat validate that.

**Comment by myriamboure** [comment]
@nanoharsha I just tested again and no change, when I have a product in the basket, it still creates a "cart" status order and I don't see the dustbin to delete the OC anymore... so no change for me.

**Comment by myriamboure** [comment]
The question is: should the hub manager be able to delete a OC if there are orders with a status "cart"? Or if there are orders completed but deleted?
For me it should be possible, as it means it's mainly used for tests, in real life if a hub open an OC there will be orders so they won't be able to delete it, and it's ok if they delete and OC before there have been any order, no?

**Comment by myriamboure** [comment]
@sauloperez I understand that today you can delete a OC if order = none, so yes it is what is happening but what I say is that it should be possible to delete an OC if order = cart as well. But I guess we can include this in the more general deletions epic that is still under discussion, as we need anyway to enable a soft delete of OC even if orders has been made (for example if it was test orders and the hub want to clean up the tests he made). So agree, we can close as covered in  https://github.com/openfoodfoundation/openfoodnetwork/issues/1874

**Comment by sauloperez** [comment]
Yes, I also thought about the soft delete here but the problem with the `cart` state is that it can imply two things: the system created an empty cart for the user to place an order next time or the user started an order but didn't finish it yet. We need to be aware of that.

**Comment by myriamboure** [comment]
Sure, we should add some process for that, I added a question on #1874 "if the OC had "cart" status orders attached and is deleted, when the user connects again on the OFN, should he see a message like "the order cycle you were shopping in has closed, please select another one to keep shopping" ?"
