### ISSUE TITLE
Missing email translation payment state

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#7681]
## Description

When customer receive email with order confirmation, such email has untranslated key from 'payment_states' - "Checkout", that already translated.
I think the code that generates this piece of email is somewhere around `apps/openfoodnetwork/current/app/views/spree/shared/_payments_list.html.haml`

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/119271838-02f25f00-bc0c-11eb-9bad-0419e8bf4552.png)

## Severity

bug-s5

## Your Environment

* Version used: 3.6.10
* Browser name and version: FF 78.10
* Operating System and version (desktop or mobile): Desktop opensuse

**Comment by vishaldeepak** [comment]
Hey, I'd like to give this a shot if no one has already started work on this

**Comment by lin-d-hop** [comment]
Hi @vishaldeepak
That would be great! Feel free to ask any questions on [Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A) if you'd like some help.
Thanks very much!
Lynne
