### ISSUE TITLE
Emails down on staging servers

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7684]
Emails are down on staging servers. This might be a side effect from having staged PR #7673 before on -UK, -AU, -FR - pinging @Matt-Yorkley .

Tested emails:
- order confirmation
- order cancellation
- shipping
- invoice re-send

Test emails are working (sent as superadmin).

In staging-Katuma emails are down as well but due to #6673.

**Comment by Matt-Yorkley** [comment]
I think this will now be fixed by #7673.
