### ISSUE TITLE
ActiveRecord::RecordInvalid in enterprises#shop

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#769]
## Exception in OpenFoodNetwork

**ActiveRecord::RecordInvalid** in **enterprises#shop**
Validation failed: Distributor or order cycle cannot supply the products in your cart

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/55bd8ad0ea1b57dee7bc88bd?event_id=568d09b631d74100405187a9)
## Stacktrace

```
app/controllers/enterprises_controller.rb:43 - reset_order
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/55bd8ad0ea1b57dee7bc88bd?event_id=568d09b631d74100405187a9)

**Comment by mkllnk** [comment]
From time to time a cart reset fails.

**Comment by oeoeaio** [comment]
Need to have a nice way of notifying customers when variants in their cart become unavailable, regardless of whether this is caused by someone else buying the last one, or whether it is caused by the enterprise user removing the item from the OC.

**Comment by daniellemoorhead** [comment]
@oeoeaio should we add this notification as a GH issue and look at adding it to the backlog for a future sprint?

**Comment by mkllnk** [comment]
Yes, this should go into a sprint.

**Comment by RachL** [comment]
@mkllnk For this one, we have a now a notification if the user attempt to checkout something in his cart that has become unavailable. Was this the case here?

![image](https://user-images.githubusercontent.com/6525576/54674446-bb885980-4afc-11e9-9bb6-3e2ba8b6cbd0.png)

**Comment by mkllnk** [comment]
I don't know. Let's close it.
