### ISSUE TITLE
Improve ease of setup

### ISSUE THREAD

**Issue by psychoslave** [openfoodfoundation/openfoodnetwork#7691]
## What is the problem we are solving 

After #7613 is closed, most crucial parts for setting up a developer instance more easily will be done. However there are still some minor concerns that might benefit love and attention to make the setup process even more closer to a breeze.

## Success factors = expected outcome 

- Less manual steps involved to deploy a new instance
- Less hindrances for new instance managers
- Happier people, and a better world :smile: 

## Useful information for inception

- [ ] ./script/setup might come with an option to switch between `developer` and `production` instance, if that helps with lowering the number of subsequent manual configurations
- [ ] possibly, if needed, include a "wizard", that guide the user with questions, preferably with given limited choices provided
- [ ] automatize as much as possible the adaptation of config/application.yml
  - [ ] `SECRET_TOKEN` comes with a scriptable receipt in the configuration file itself
  - [ ]  `TIMEZONE`, can be obtain from system calls, might require to cross data with [ActiveSupport::TimeZone](https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html) to get the proper name from `MAPPING`
  - [ ] `DEFAULT_COUNTRY_CODE` and `LOCALE`  can use current user related system environment variables
  - [ ] `AVAILABLE_LOCALES` might be trickier, browsers might have relevant preferences to back on
  - [ ] `CHECKOUT_ZONE`, might require to cross data between  system environment variables and [Spree zones](https://guides.spreecommerce.org/user/shipments/zones.html). Currently it seems that OFN comes with `Australia`, `EU_VAT`, and `North America` out of the box.
  - [ ] `GOOGLE_MAPS_API_KEY`

## Link to the "Product Development - Backlog" item in Discourse

Development environment setup

**Comment by mkllnk** [comment]
Thanks again for putting so much thought into this. A few things have changed since you wrote this issue and we are on a trajectory of simplifying the setup with Docker. So I'll close this issue for now but feel free to contribute pull requests with improvements as you see fit.
