### ISSUE TITLE
Text change on order confirmation emails

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#772]
Please can we 
1) make these changes (see screenshot) to the text on the order confirmation emails and 
2) replace the OFN Aus logo with the OFN UK logo
thanks
Nick
![order confirmation email](https://cloud.githubusercontent.com/assets/10517702/12176759/e3c40f14-b560-11e5-90c8-2f3c4b17f9e4.png)

**Comment by lin-d-hop** [comment]
Changes made and currently deployed to UK staging.
PR #793

**Comment by lin-d-hop** [comment]
This has been merged. Just waiting on a UK production deployment.

**Comment by lin-d-hop** [comment]
With last weeks deploys these changes are now on UK staging and production.

Closing.
