### ISSUE TITLE
Product paid for at checkout absent from order

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7725]
## Description

Hub manager has no recollection of removing the 3 white bread rolls from Order ID R231310772 and is confused to find the order present with payment status of credit owing £1.50 02/06/21.
Is it possible to trace when the white bread rolls were removed from the order?  They were paid for at checkout. Hub needs to be confident on how and when the order was edited in order to make refunds.

## Expected Behavior

Customer places order and pays at checkout for all items in the basket. 
Order confirmation email states all products in the order. 
![helstonorder](https://user-images.githubusercontent.com/45104035/120518060-0edadf80-c3c9-11eb-839e-9694c382c4d1.png)

These items appear listed under Edit order -> 'order details'
Enterprise settings do not permit customer to change order while order cycle open.
Hub manager does not change order
One week later, all products which were in the original order are still present.

## Actual Behaviour

Customer places order and pays at checkout for all items in the basket. 
Order confirmation email states all products in the order. 
These items appear listed under Edit order -> 'order details'
Enterprise settings do not permit customer to change order while order cycle open.
Hub manager does not change order
One week later, the White Bread rolls which were in the original order are no longer present.  The order displays as Credit Owing = £1.50

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
Closing as we don't have enough background to go on.
Let's reopen if we see again.
