### ISSUE TITLE
Order invoices failing to print/download

### ISSUE THREAD

**Issue by chezaorchard** [openfoodfoundation/openfoodnetwork#7726]
## Description
Enterprise ID: 1965

When looking at an existing order R463442651 in the backoffice, and trying to print an invoice for that order by navigating Edit > Actions > Print Invoice, I am taken to the print view (https://openfoodnetwork.org.au/admin/orders/R463442651/print), but served an error 'Failed - Network Error' when clicking > Download.

<img width="1252" alt="failed network error" src="https://user-images.githubusercontent.com/68367600/120589388-1ad3a980-c47c-11eb-8470-89a43472a8f3.png">

Don't seem to be able to print any customer invoices - logged in as superadmin or various enterprises - have tried from numerous computers to check its not device specific - all returning the same error.

## Expected Behavior
When clicking Download, PDF of order invoice should be available

## Actual Behaviour
Enter order number in back office orders page > search
Click Edit
From the Edit screen click > Actions > Print Invoice
From the Print screen click > Download
File drops into download bar in chrome navigation, bottom of scrreen - but is a blank document with name 'Failed - Network Error'

## Steps to Reproduce

1. Replicated logged in as Enterprise (not superadmin) - same as above
2. Replicated logged in as SuperAdmin for different Enterprise and random customer orders - same as above
3. Replicated logged in as different enterprise (not superadmin) and random customer orders - same as above

## Workaround
Can take a screenshot of the orders > edit page and send to customer if needed but this is not a workable solution for customers who need to send multiple invoices, for example those who are managing all wholesale order payments by invoices

## Severity
S3

bug-s3: a feature is broken but there is a workaround

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment
Chrome on desktop Mac

**Comment by lin-d-hop** [comment]
This seems to be a known Chrome issue rather than an OFN issue.

Workarounds:
- Use incognito mode in Chrome.
- Use a different browser

**Comment by RachL** [comment]
If I understand clearly, we cannot do anything about it? I'm closing, we can reopen if it is not the case.
