### ISSUE TITLE
Unable to scroll cart pop-over when the list of products is longer than the screen height.

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#775]
There was no design solution put in place for when the list of products displayed is longer than the max. height of the cart pop-over. The user can still proceed to checkout, or view their cart via the top buttons in the pop-over, however there is currently no scroll bar or elegant way of dealing with a pop-over that is longer than the available screen height.

See Discourse discussion on this here: http://community.openfoodnetwork.org/t/unable-to-scroll-down-the-cart-to-checkout-when-products-10-15/457/4

![aafadb03537e39f91cfe257f946d3b07cb990047_1_690x362](https://cloud.githubusercontent.com/assets/10949052/12187777/f16c3f90-b602-11e5-935b-ea723b12d68d.png)

**Comment by sstead** [comment]
This is now in Aus Production.
