### ISSUE TITLE
CI failing due to Codecov problems

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7750]
Build are failing incredibly frequently due to the Codecov report upload not working. This started a couple of days ago. Looks like it might be an issue on the Codecov side.

Seen here (amongst other places): https://github.com/openfoodfoundation/openfoodnetwork/issues/7749

**Comment by andrewpbrett** [comment]
This looks like it's working again, should we close and reopen if it comes up again?

**Comment by Matt-Yorkley** [comment]
Ah ok, it looks like they've finally fixed it :+1:
