### ISSUE TITLE
Can't place orders using Stripe 3D cards (shopfront and backoffice)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7753]
## Description

Checking out through the shopfront with [3D-auth cards](https://stripe.com/docs/testing#regulatory-cards) like:

- 4000000000003220
- 4000002760003184

display the error:

`
There was a problem with your payment information: Received unexpected 3DS authentication response. Use the execute_threed option to initiate a proper 3DS flow. 
`

Placing BO orders with 3D cards leads to an invalid payment.

First observed on staging-FR as reported by @Matt-Yorkley; reproduced on other servers, namely staging-AU: staging master [build #2649](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/345) led to this bug.

## Expected Behavior

Checkout should be possible with 3D-auth. cards.

## Actual Behaviour

Checking out with 3D-auth. cards is not possible.

## Steps to Reproduce

Shofront
1. Attempt to place an order through the shopfront, selecting Stripe SCA as a payment method
2. Add a 3D-secure card
3. See the error

Backoffice
1. Attempt to place an order through the backoffice, selecting Stripe SCA as a payment method
2. Add the card details
3. See the payment marked as "Failed"

## Animated Gif/Screenshot

**Shopfront**

![Peek 2021-06-07 16-14.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/bd8cadee-a8af-4fc2-a52f-9b5e67e69caa)

**Backoffice**

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/a238c98a-8857-4ff9-9a37-f1df80011de8)

## Workaround

Using a different payment method. 

## Severity

Blocker for the release v3.8.0 - it is not in production.
Not observed after deploying v3.7.3.

## Your Environment

* Version used: observed on master branch [build #2649](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/345)

## Possible Fix

@Matt-Yorkley investigated further: Reverting a recent PR (#7752) didn't fix it... Rails 6.0 upgrade could be related to this - although this scenario was tested before merging with master...

**Comment by Matt-Yorkley** [comment]
Okay... this is nasty. I can replicate it in `v3.8.0` but not in `v3.7.3`.

The issue is related to this [ActiveMerchant decorator] being out of sync with the version provided by the gem. I think various things have changed in relation to class-loading in Rails 6.0, and AFAICT something has changed in the way this decorator is being loaded and overwriting (or not overwriting) the original.

**Comment by Matt-Yorkley** [comment]
Background: https://github.com/openfoodfoundation/openfoodnetwork/pull/7286#issuecomment-813065641

Super relevant background when we tried to remove the decorator: https://github.com/openfoodfoundation/openfoodnetwork/pull/7286#issuecomment-815751831

The errors in that last comment are exactly the errors we see now :point_up:

**Comment by andrewpbrett** [comment]
I also noticed that as part of Rails 6.0 we bumped the Stripe gem, and we originally had some breaking changes in the build in order to do it. https://github.com/openfoodfoundation/openfoodnetwork/pull/7668

I won't be able to really dig in to this for several hours. I think you're right though, @Matt-Yorkley, that the decorator is probably not being applied so if we can figure out why that should solve this.

**Comment by Matt-Yorkley** [comment]
The error is being thrown by a method in that same file, and it's one we don't have in our decorator...

**Comment by luisramos0** [comment]
I am sorry to see this, with this decorator we need to verify  if the original file changes everytime we update Stripe.
Any ideas to improve this? We could just copy a specific version of the file to ofn, as we had before but I think it's better (although a bit painful with problems like this) to keep following stripe gem updates,

**Comment by luisramos0** [comment]
I wonder if there is a way to write an automated test that replicates this bug.

**Comment by Matt-Yorkley** [comment]
The troublesome bit of code was here: https://github.com/activemerchant/active_merchant/blob/a9c588f90c4c1d59f7b0f5e1dc40b9ca12cb7fbf/lib/active_merchant/billing/gateways/stripe_payment_intents.rb#L384-L392

These lines are quite new, but not _that_ new. It looks like they've been present for a least 2 releases, but this error only started in this release (with Rails 6.0).

It looks like setting that `execute_threed` option enables 3DS handling. I don't fully understand why the issue has only surfaced now though.

**Comment by luisramos0** [comment]
I just realized PR #7286 is not merged...  maybe we should try to get it in?

**Comment by Matt-Yorkley** [comment]
Ah! Yeah we can rebase it and test it again :+1:
