### ISSUE TITLE
Introduce Webpacker

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7774]
This is required for StimulusReflex and possibly other parts of Product Uplift. It's also how all modern Rails apps handle assets...

It's a pretty serious change to the asset pipeline! It also requires some changes in the dev environment.

We could bring it in slowly and keep current assets as they are and introduce new assets in Webpacker, or we could go all in and move all of our Javascript and CSS into Webpacker all at once...

**Comment by jibees** [comment]
>We could bring it in slowly and keep current assets as they are and introduce new assets in Webpacker, or we could go all in and move all of our Javascript and CSS into Webpacker all at once...

What does your experience with OFN tells you? Do you have any idea at this time?

**Comment by Matt-Yorkley** [comment]
Maybe it makes sense to do it all at once and test it all together?

**Comment by jibees** [comment]
It is an elegant and ambitious idea ;) I like it!

**Comment by Matt-Yorkley** [comment]
I've started working on this, but it's going to be pretty crazy due to the outdated assets we're loading from gems. They don't all play nicely with Webpacker...

**Comment by RachL** [comment]
@Matt-Yorkley hello, do we still need this issue?

**Comment by Matt-Yorkley** [comment]
We've introduced it but we haven't quite finished migrating things. I guess the remaining bits are not a big priority though and we don't really need this issue now :ok_hand:
