### ISSUE TITLE
Change default Redis port for Sidekiq

### ISSUE THREAD

**Issue by shveikus** [openfoodfoundation/openfoodnetwork#7787]
### What we should change and why (this is tech debt)
Change default Redis port from 6381 to 6379 for Sidekiq.

There will be no need to find out what service has to be running on port 6381 and has failed the setup script for newcomers.

### Context
One more tiny improvement for #7691

**Comment by Matt-Yorkley** [comment]
Hi @shveikus :wave: this issue should be resolved by PR https://github.com/openfoodfoundation/openfoodnetwork/issues/7745, hopefully we'll merge it soon.
