### ISSUE TITLE
ActionView::Template::Error in ActionMailer::DeliveryJob@mailers

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#7789]
## Error in OpenFoodNetwork UK

**ActionView::Template::Error** in **ActionMailer::DeliveryJob@mailers**
undefined method `firstname' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60c1f241eecfd70007d4e8df?event_id=60c8bd46007ceb1220000000&i=gh&m=ci)

## Stacktrace

    app/views/spree/order_mailer/confirm_email_for_shop.html.haml:21 - _app_views_spree_order_mailer_confirm_email_for_shop_html_haml__2331135668978603145_49753200
    app/mailers/spree/order_mailer.rb:46 - block in confirm_email_for_shop
    app/mailers/spree/order_mailer.rb:44 - confirm_email_for_shop

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60c1f241eecfd70007d4e8df?event_id=60c8bd46007ceb1220000000&i=gh&m=ci)

*Created by Admin OFF via Bugsnag*

**Comment by andrewpbrett** [comment]
This is probably an S1/S2? Any email that encounters this won't be delivered.

**Comment by Matt-Yorkley** [comment]
This is tracked in https://github.com/openfoodfoundation/openfoodnetwork/issues/7723

The emails do get delivered :+1:

**Comment by andrewpbrett** [comment]
Ahhh okay. Thanks. I'll close this as a dupe.

**Comment by Matt-Yorkley** [comment]
It's pretty freaky, it would be good to investigate and fix it...
