### ISSUE TITLE
ActionView::Template::Error in ActionMailer::DeliveryJob@mailers

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#7798]
## Error in OpenFoodNetwork

**ActionView::Template::Error** in **ActionMailer::DeliveryJob@mailers**
undefined method `firstname' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60c23003cf1a6b00074744ce?event_id=60ca9f1b007ee2f463410000&i=gh&m=ci)

## Stacktrace

    app/views/spree/order_mailer/confirm_email_for_shop.html.haml:21 - _app_views_spree_order_mailer_confirm_email_for_shop_html_haml___209002452646850361_47004543315460
    app/mailers/spree/order_mailer.rb:46 - block in confirm_email_for_shop
    app/mailers/spree/order_mailer.rb:44 - confirm_email_for_shop

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60c23003cf1a6b00074744ce?event_id=60ca9f1b007ee2f463410000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by Matt-Yorkley** [comment]
This is already tracked in #7723

**Comment by mkllnk** [comment]
This issue has been unlinked from an error in Bugsnag
[**ActionView::Template::Error** in **ActionMailer::DeliveryJob@mailers**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60c23003cf1a6b00074744ce?event_id=60caf36a007ef0bd93d30000&i=gh&m=ul)
