### ISSUE TITLE
Snail on Enterprise Fee Report 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#7799]
## Description
When trying to run the Enterprise Fee Report in Australia we get a snail.

I have managed to successfully run it for one very small user, but for any login with multiple enterprises (including super-admin) it seems to fail. See below - we think is something to do with incomplete clean-up of Pin Payments

## Expected Behavior
We should be able to run the Enterprise Fee Report

## Actual Behaviour
SNAIL

## Steps to Reproduce
* Log in as superadmin in Aus
* Try to run Enterprise Fee Report

## Workaround
Managed to do what was needed for this customer through other reports (in this case Order Cycle Supplier Totals) 

## Severity
S3 

## Possible Fix
We think this might be something to do with an Enterprise / Fee that is associated with the now removed Pin Payments method. See message from Bugsnag 
https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60c18fcb9974e50008199131?event_id=60c18fcb007d033870870000&i=sk&m=nw

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/41f33d68-1148-485e-a575-c783cc7a1483)

**Comment by kirstenalarsen** [comment]
@mkllnk did you have any other thoughts on this?

**Comment by mkllnk** [comment]
Ah, yes, I saw that and raised it with Ronella. We still have Pin payment gateway records in the database but the related code has been removed. So I see two possible resolutions:

* Bring back a minimal implementation of the Pin payment gateway. Not great in terms of code maintenance.
* Transition the current records to a generic payment gateway, like cash. Dev needs to check how easy but that would be the right way forward, I think. Maybe we would even invent a new payment method `RetiredPaymentGateway`.

**Comment by luisramos0** [comment]
Hi, I just saw this now.
This was supposed to be done already, migrate to Check. This was done for payment methods:
https://github.com/luisramos0/openfoodnetwork/blob/34ce3c0db1d50caf91337cc6c416c1fd68b2e6e1/db/migrate/20210203215049_rename_pin_payment_methods_to_check.rb
I believe this migration needs to be done for enterprise fees (or adjustments?) as well.

And yes, this needs to be taken in consideration when doing #7872 :+1:

**Comment by filipefurtad0** [comment]
Noting here that we might need a migration for the recently removed MIGS payment method as well: the enterprise fee report is broken for hubs which used it, too.
