### ISSUE TITLE
Release v3.8.3 Käsekrainer

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#7811]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] https://github.com/openfoodfoundation/openfoodnetwork/releases/
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2698
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by lin-d-hop** [comment]
I'm surprised this is not a whole dot point release with the big adjustments changes...

Nice work team. All looking good and besides the big changes there are some excellent little fixes in here!

https://docs.google.com/document/d/1gUbFtWQrs4lhbJvBRhbUc3t3dZfl3yNngH_ZD06vd7c/edit#heading=h.yealfrq6sw9f

**Comment by RachL** [comment]
First batch of deployment has happened :tada: Is there anything preventing us to publish the release?

**Comment by sauloperez** [comment]
It was published, I assume, by @andrewpbrett :point_right: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v3.8.3

**Comment by RachL** [comment]
@sauloperez aaaah thanks! I missed the message on slack then. I guess we can close it. We are not tracking deployments with this issue.
