### ISSUE TITLE
Restarting unicorn is failing on deployments

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7833]
## Description

Staging of the Rails 6.1 PR is failing with the message:

```
RUNNING HANDLER [restart unicorn] **********************************************
fatal: [staging.openfoodnetwork.org.uk]: FAILED! => {"changed": false, "msg": "Unable to restart service unicorn_openfoodnetwork: Job for unicorn_openfoodnetwork.service failed because the control process exited with error code. See \"systemctl status unicorn_openfoodnetwork.service\" and \"journalctl -xe\" for details.\n"}
Thursday 24 June 2021  16:10:12 +0000 (0:00:05.514)       0:02:45.505 ********* 

```

as found on the logs:
staging-UK - https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/uk-staging/deploys/766
staging-AU - https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/360

**Comment by andrewpbrett** [comment]
Looks like this:

> 3.2 Force SSL
> The force_ssl method on controllers has been deprecated and will be removed in Rails 6.1. You are encouraged to enable config.force_ssl to enforce HTTPS connections throughout your application. If you need to exempt certain endpoints from redirection, you can use config.ssl_options to configure that behavior.

https://guides.rubyonrails.org/upgrading_ruby_on_rails.html

We already do `config.force_ssl = true` in production.rb, so it seems like the file lib/spree/core/controller_helpers/ssl.rb may no longer be necessary.

**Comment by andrewpbrett** [comment]
This is fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/7608/commits/334b9b520ab374ceee86671eb581fe64e9917fd6
