### ISSUE TITLE
NoMethodError in spree/orders#update

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#7844]
## Error in Open Food Network Belgium

**NoMethodError** in **spree/orders#update**
undefined method `order' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/60d86535d4e14e00078d39e6?event_id=60d86535007f758147ca0000&i=gh&m=ci)

## Stacktrace

    app/models/spree/tax_rate.rb:105 - compute_amount
    app/models/spree/adjustment.rb:106 - update_adjustment!
    engines/order_management/app/services/order_management/order/updater.rb:132 - update_all_adjustments
    engines/order_management/app/services/order_management/order/updater.rb:22 - update
    app/models/spree/order.rb:218 - update_order!
    app/models/spree/order_contents.rb:126 - update_order
    app/models/spree/order_contents.rb:50 - update_cart
    app/controllers/spree/orders_controller.rb:71 - update

[View full stacktrace](https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/60d86535d4e14e00078d39e6?event_id=60d86535007f758147ca0000&i=gh&m=ci)

*Created by OFN Belgium via Bugsnag*

**Comment by andrewpbrett** [comment]
Looks like it's related to the adjustments changes, we're passing in a nil item for some reason. Should be quick to guard against the nil but might need 👀 from @Matt-Yorkley to make sure there's not a deeper cause.

**Comment by Matt-Yorkley** [comment]
I'll take a look now :+1:

**Comment by Matt-Yorkley** [comment]
Alright this one looks pretty weird. There's only one instance of this happening, but the details of the request are a bit strange. It seems like it was a PATCH request sending form data to the cart controller (and sent form data), but the headers indicate it originated from inside of the microsoft outlook email client..? `"X-Requested-With": "com.microsoft.office.outlook"`. Not sure what to make of that.

Also this Bugsnag corresponds to a deadlock that occurred at the exact same time (`Jun 27th, 11:47:01 UTC`), and it looks like there were two simultaneous requests sent to update the same cart object at the same time. I'm thinking a weird double-click type event on the client side is the most likely cause? If the user continued to click things afterwards I think their cart would have been updated okay, so I'm not sure there's much to do here.

I know we're on high alert for any related issues during the adjustments rollout, but I think this one is a genuine freak occurrence and is more related to general issues around handling of double-clicks (which still cause us problems, specifically deadlocks).

**Comment by andrewpbrett** [comment]
Thanks for checking that out @Matt-Yorkley - I don't know if you saw this but there's another bugsnag at the same time that reports a deadlock: https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/60d86539137419000723da6b?event_id=60d86539007f6dca95df0000&i=sk&m=nw

So I think it's safe to say this is unrelated to the adjustments rollout. Should we keep it open to help with tracking down double-click issues? Or is that captured somewhere else?

**Comment by lin-d-hop** [comment]
Seems to be the cause of[ this bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60e9a0720589900007ea067f?filters[event.unhandled]=true&filters[event.since]=30d&filters[app.release_stage]=production&filters[search]=lilyrussell1961%40icloud.com) which blocked a checkout with paypal.

Bumping to S2.

**Comment by Matt-Yorkley** [comment]
Alright I'm trying to piece together what the whole session looked like for that recent Bugsnag:
- various users were shopping at the same hub at the same time
- there were potentially multiple (presumably handled) out-of-stock errors for that user even _before_ the checkout: when the user was trying to add items to the cart some of them were going out of stock at the exact same time
- the end result is that there were issues at the checkout and some of the objects associated with the order seem to be in a slightly weird/unexpected state

It's possible the probem that ultimately caused the checkout error here actually happened _before_ the checkout as opposed to during. It's definitely related to error-handling under high stock volatility.

**Comment by lin-d-hop** [comment]
Yes that much I've already told the user.

Of course out of stock issues will always be a thing. So the priority is simple handling error messaging and state transitions. When shoppers just see an error saying 'NO' the fear that that creates in the shopper reverberates through like half a dozen people before becoming a GH issue. 

If there is any way to help the experience be something the shopper understand then lots of people will win... for example:
- Shopper sees error message that they can understand telling them the item that sold out
- The cart still existis and now has the subset of available items in it
- Shopper is free to retry checkout or even continue shopping to replace the missing item

To add perspective, so far on one failed checkout we see that the shopper, two people from the hub, two people from UK support, three people from global have all spent time understanding it :-)

**Comment by Matt-Yorkley** [comment]
Aha... alright I think I've figured it out and there's an edge case here at the point where we're hurriedly deleting a line item from the cart because it's just gone out of stock. I think if there's enterprise fees on the line item and taxes on those fees, the way we ditch that out-of-stock line item doesn't actually clear things up in the way it should and there's a leftover reference to the deleted line item. 

I'll take a crack at some specs and a fix :ok_hand:
