### ISSUE TITLE
Remove Stripe Connect

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#7872]
### What we should change and why (this is tech debt)

Now that we have moved to Stripe SCA we wish to remove Stripe Connect from the codebase to simplify and clean up our code.

All Stripe Connect code is be removed
No existing payment methods should reference this old payment method.
Any reports that reference this old payment method (Enterprise Fees report?) will now reference StripeSCA

### Context

All Stripe Support teams have handled the roll out of Stripe SCA so we can boldly make code changes and migrations here.

Another payment method was removed recently so this might be useful background:
#6231
and this resulting (and still unsolved) error is a mistake we should not repeat:
#7799

### Impact and timeline

While all users have been moved from Stripe Connect it is still possible for users to have chosen this payment method and be using it. Therefore we need to ensure we do a migration of any Stripe Connect payment methods to Stripe SCA.

**Comment by luisramos0** [comment]
I have created a draft for this: #7978 
The removal of code must be nearly done.
Quite a few specs moved from stripe connect factory to strips sca factory, I think this will need some adaptation fo the specs but worth while so we keep all the tests but no reference to stripe connect.
We then need to write a migration for the payment method and the enterprise fees/adjustments (as per #7799).
And that must be it. . 

I am not sure when/if I'll have time to get back to this.

**Comment by lin-d-hop** [comment]
Thanks @luisramos0 

If there are any additional notes that might be useful to help @apricot12 (our sparky new junior dev) pick this up that would be super helpful. In any case thanks so much for yet another invaluable volunteer contribution!

**Comment by luisramos0** [comment]
Hi @lin-d-hop :wave:
The specific next steps are:
- fix the build in #7978 
- add a migration like this to migrate stripeconnect to stripesca
- fix #7799 with a migration of enterprisefees and/or adjustments and then add a similar one for this migration.
That should be it.

**Comment by apricot12** [comment]
Looks like I know what I'll have to look into next 😂. Thanks @luisramos0
