### ISSUE TITLE
Deployments failing when running a rake task

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#7877]
## Description

We are seeing deployments fail when they require a rake task to be run, e.g. `remove_transient_data`. The message is

```
rake aborted!
ArgumentError: Missing `secret_key_base` for 'staging' environment, set this string with `bin/rails credentials:edit`
```
## Expected Behavior

Successful deploy

## Actual Behaviour

Failed deploy

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
Ah we need to provision all staging servers. I'll do it now.

**Comment by Matt-Yorkley** [comment]
Done. I'll do a quick deployment check but it should be working now :ok_hand:

**Comment by Matt-Yorkley** [comment]
Fixed

**Comment by andrewpbrett** [comment]
Nice! Was there a change in ofn-install that I missed?

**Comment by andrewpbrett** [comment]
I didn't think that the dot-env changes were necessary, since we were trying to deploy a version that was earlier in the history, before that was merged...

**Comment by Matt-Yorkley** [comment]
I think when Sempaphore deploys PRs it deploys a them merged with master.

As a side note I'm pretty happy with that error :sweat_smile: it indicates deployments will fail early in the case where the secret key base is missing in the configs, which is an incredibly valuable failsafe.

**Comment by andrewpbrett** [comment]
> I think when Sempaphore deploys PRs it deploys them merged with master?

Yeah that would explain something @filipefurtad0 and I were scratching our heads about earlier this week as well with the webpack PR. We were deploying PR's that had been created a long time ago and not rebased, but they were picking up the bad commit that had only just been merged. 

> As a side note I'm actually pretty happy with that error

Yeah that's a nice check, that it will fail loudly if it's missing. 

Will we ned to move to using Rails.credentials at some point? I did a brief trip down that road and it looks like it'd be a bit complex... right now each instance has its own secret key base, which would be difficult to do with the new setup.

**Comment by Matt-Yorkley** [comment]
It's doable, but probably not a high priority. We could open an issue to track it :+1:
