### ISSUE TITLE
Upgrade Webpack to v5 and webpacker to v6

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#7878]
### What we should change and why (this is tech debt)

Our webpack config is not valid for webpack >= 5 it seems.

### Context

https://github.com/openfoodfoundation/openfoodnetwork/issues/7860

**Comment by jibees** [comment]
Rail webpacker 5 is only available for webpack 4.X.X

From webpacker : 
> NOTE: The master branch now hosts the code for v6.x.x. Please refer to 5-x-stable branch for 5.x documentation.

So, to upgrade webpack to v5.X.X, we also must upgrade gem webpacker to > 6.X.X

**Comment by jibees** [comment]
@Matt-Yorkley 
I can do the upgrade, if you're agree (and if you think it feasible and seems legit to do it right now).

**Comment by Matt-Yorkley** [comment]
I don't think going to Webpacker 6 is a good idea right now. It's still essentially in beta and I've heard strong recommendations from various people saying to stick at Webpacker 5.4 for now and avoid using 6.x in production...
