### ISSUE TITLE
Product appearing twice in the "Incoming" section of order-cycles

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7885]
## Description

Products are appearing twice, in the "Incoming" section, when setting an Order Cycle. Variant overrides have been pointed as a possible cause, but it does not seem to be the decisive pattern - below an example is posted where this is not the case.

As of writing, this seems not to be reflected throughout the app: if "doubles" are selected they appear only once in the "Outgoing" section of the OC, and hence, appear only once in the Shopfront.

Updated: See steps to reproduce.

## Expected Behavior

Products and respective variants should appear only once in the Incoming section of Order Cycles.

## Actual Behaviour

Some products and respective variants appear twice in the Incoming section of Order Cycles. The loaded variant count is incorrectly displayed.

## Steps to Reproduce

~~Not sure. Our best clue is so far the example below: a product with `three` variants displays two doubles, i.e., appearing `three` times... No Inventory overides.~~

See [comment below](https://github.com/openfoodfoundation/openfoodnetwork/issues/7885#issuecomment-874686694).

1. Create a product with `n` variants, with `n` > 1
2. Add it to the inventory
3. Add it to an OC
4. Under "Advanced Settings" choose the option "Coordinators inventory only"
5. See this product appears `n` times in the incoming section of the OC -> notice the loaded variant count is also incorrect (xx / yy Variants Loaded)
6. Under "Advanced Settings" choose the option "All available products" -> this should go back to normal.

## Animated Gif/Screenshot

Product list and Incoming section:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/75b8fd87-ad56-41ab-b822-d014d9e55559)

The "doubles" behave as one:
![Peek 2021-07-06 12-07.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/b3549f0e-f058-4b63-a4c8-b1d63eaa3524)

**Inventory**
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/f3992da9-3f93-4480-985b-b39960b9232b)

## Workaround

Confusing to the user, but no workaround needed as nothing seems to break.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.8.3
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by filipefurtad0** [comment]
Ok, I think it's about the OC setting display "Coordinators inventory only":

![Peek 2021-07-06 12-35](https://user-images.githubusercontent.com/49817236/124593663-ce063880-de56-11eb-83a5-f3ef28e80611.gif)

For a product with `n` variants, it adds `n` entries to the incoming section, when the product is added to the inventory and "Coordinators inventory only" option is selected.

**Comment by chezaorchard** [comment]
Australia are seeing duplicate variants where hub accounts are creating order cycles and selecting the advanced setting 'coordinators inventory only'. Tested using Chrome & Safari

Found duplicates in order cycles for Enterprise ID 2894, 3303, 259, 3539, 119

I also checked 119 historic order cycles from super admin; and can see duplicate variants in all order cycles for August. Was timing out when I tried to view earlier than that so was unable to check if it is applied to all historic OCs - short video of that here https://www.loom.com/share/bf94173e7aa14f088ceb0a20521ad903

![Xnip2021-09-07_15-53-06](https://user-images.githubusercontent.com/68367600/132299062-ea0591ce-b889-40f6-8446-c95c61befb1a.jpg)
![Xnip2021-09-07_15-52-20](https://user-images.githubusercontent.com/68367600/132299087-65264eb9-9dc9-4813-ba26-015252b9e351.jpg)
