### ISSUE TITLE
Error in report: product name showing wrong variant name

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#789]
I have a sausage, with two variants: full sausage, or half sausage:
![speke1](https://cloud.githubusercontent.com/assets/8135376/12536055/f4c42d4a-c298-11e5-8aec-1e2de3f50e1e.png)

In my order cycle, two persons have ordered the variant 1/2 sausage
![speke2](https://cloud.githubusercontent.com/assets/8135376/12536069/73e23be4-c299-11e5-9b19-1bb740aab13d.png)

When I do the exports (total by supplier) to order to the producer, here is what happens:
![speke3](https://cloud.githubusercontent.com/assets/8135376/12536082/ed1f9056-c299-11e5-8ae3-3625344a5420.png)

As you see, the price and number of orders are good, but the name of the variant is wrong, it says it's full sausages that have been ordered, I don't know why, it takes the name of the other variant, in total contradiction!
I tried to add in the name of the variant a more precise indication:
![speke4](https://cloud.githubusercontent.com/assets/8135376/12536110/e67e421e-c29a-11e5-8b14-40d6b0eddca6.png)
But the report still indicates the wrong name as a side:
![speke5](https://cloud.githubusercontent.com/assets/8135376/12536118/0faac2ac-c29b-11e5-829f-aecfbe1878d2.png)

That is really strange... Do you have an idea where that might come from?
I checked in all the products set up, nothing solved this problem...

**Comment by RachL** [comment]
@myriamboure I did not manage to reproduce this. So I'm closing it. Feel free to reopened it with all the steps if you remember how to reproduce it!
