### ISSUE TITLE
Line taxes listed on order confirmation and invoices

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#7890]
## Description

Since the adjustments work and latest release,  taxes are being listed individually on order confirmations and on invoices.  It is happening on both invoice templates.  It is happening for instances where tax is included and where tax is excluded from prices. 

## Expected Behavior

The order confirmation and the invoice should show totals of taxes (by tax category?)  and not each individual tax amount associated with an item.

## Actual Behaviour

Each individual tax amount  -  for each tax category -  is showing on the invoice and the order confirmation,   making for lengthy invoices.   For example:  a customer buys 50 taxable items -  the invoice shows 50 lines of tax amoungs.    In instances where two different tax categories are applicable (this would be in BC, Canada for example,  and I think many of the US states) the invoice would show two lines of tax for every item ordered. 

Example below.

## Steps to Reproduce

1.Place an order for more than one taxable item
2.See the invoice and the order confirmation
3. Swtich invoice templates -  and see its the same.
4.

## Workaround

No woraround

## Your Environment

We've tested in Chrome,  and in Firefox
[invoice-R150736087.pdf july 7.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/6777535/invoice-R150736087.pdf.july.7.pdf)

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by filipefurtad0** [comment]
These amounts correspond to tax amounts from enterprise fees, for each individual item, but not for the item itself. For example, this order has no taxes associated with the products (only with the fees):

![image](https://user-images.githubusercontent.com/49817236/124778959-4a714800-df39-11eb-84c7-127e0f7631d0.png)

So, to observe this issue an enterprise fee needs to be created, set-up with a given a tax category, and added to the OC. A customer then needs to checkout using a billing/shipping address within the respective zone.

**Comment by filipefurtad0** [comment]
We should note that we've had this issue #5591 opened because the tax values from enterprise fees per line items were omitted from invoices. I think we can close it now.
