### ISSUE TITLE
Incorrect display of shopping tax on invoices and in order confirmations

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#7894]
## Description
On invoices (first screenshot) the shipping tax (0,13 €) is listed above the line, but it is already included in the shipping fee (2,00 €). So the total amount doesn't match all the numbers above the line. This is really confusing for customers and financial controlling. 
Same applies to the order confirmation in emails and the browser (second screenshot) as well as to order cancellation emails. 

## Expected Behavior
The shipping tax line should not be displayed seperately above the line, because the tax is already included in the shipping fee. 

## Actual Behaviour
There is a separate shipping tax line displayed above the line.

## Steps to Reproduce
1. Place an order which includes a shipping fee and a shipping tax
2. Look at the order confirmation screen and order confirmation email
3. Look at the invoice
4. Cancel the order
5. Look at the order cancelllation email

## Animated Gif/Screenshot
![grafik](https://user-images.githubusercontent.com/1790176/124871350-3c1c3e00-dfc4-11eb-861b-641c6be55f67.png)
![grafik(1)](https://user-images.githubusercontent.com/1790176/124871369-41798880-dfc4-11eb-8fdb-de00de7828b5.png)

## Workaround
not available

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v3.8.3
* Browser name and version: Firefox 89.0.2
* Operating System and version (desktop or mobile): Desktop Windows 8

## Possible Fix
The easiest solution would be to remove the separate shipping tax line.

**Comment by andrewpbrett** [comment]
Thanks @drummer83 - so if I understand it correctly, shipping fee is meant to be tax-inclusive, and so the 0.13 euros should show up as part of the 6.75 euro "tax included" line?

**Comment by drummer83** [comment]
Yes, @andrewpbrett, that's correct! And it actually **is already included** in the 6.75 €. So the **numbers must not change** - simply the line with the 0.13 € should be removed.
I hope I am doing the math right here, but pretty sure. ;-)

**Comment by Matt-Yorkley** [comment]
It wouldn't necessarily be tax-inclusive though, mainly for US or Canada...

**Comment by andrewpbrett** [comment]
So could we have that line show up conditionally based on whether the adjustment's `included_tax` is 0?

**Comment by Matt-Yorkley** [comment]
Hmmm I'm thinking we should just exclude tax adjustments completely from that itemised list. There's already a set of tax totals _underneath_ that list.

**Comment by andrewpbrett** [comment]
I updated #7892 and I believe it should now fix this issue as well.

**Comment by RachL** [comment]
Hello!

Could the solution here be actually a change of design instead of removing information?

We could choose to present shipping fees like we display products: the price without taxes, and the tax included number?

**Comment by drummer83** [comment]
@RachL: Just wondering where we are displaying products the way you are describing. On invoices and order confirmation we currently don't (see screenshots above) - at least in the "tax included" variant.
