### ISSUE TITLE
Orders placed as guest customer cannot be viewed after sign-up

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7905]
## Description

After a first (and following) successful orders placed as a `guest`, a customer which signs-up (and logs in) cannot view these orders on `/account#/orders`. It also cannot check the balance on that shop, under `/account#/transactions#`.

These are visible for the admin as usual.

## Expected Behavior

After signing up, a customer should be able to view orders placed before sign up (as a guest customer). Also, the customer should be able to see its balance, for that shop.

## Actual Behaviour

After signing up, a customer is not able to view orders placed before sign up (as a guest customer). Customer balance is not visible either.

## Steps to Reproduce

0. As a Hub/Shop, set it your shop to allow guest checkout. (admin/enterprises/<shop_permaling>/edit#/shop_preferences)
1. As a guest customer, place one or more orders (using the same email address) in a Hub
2. Sign up and log in to the account
3. Go to `/account#/orders` -> no orders appear
4. Notice that `/account#/transactions#` the hub from which the orders were placed appears, but no transactions are visible

## Animated Gif/Screenshot

![Peek 2021-07-09 10-43](https://user-images.githubusercontent.com/49817236/125062090-ef109880-e0a5-11eb-83a5-78180beaeb49.gif)

## Workaround

None for the customer. An idea would be to use the order number to view the order, but it leads to an authorization error (see video).

## Severity

I'm not sure. From process an S2, but maybe not occurring that often, so maybe S3.

## Your Environment

* Version used: ~~v3.8.3~~ at least since v3.8.4.
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by RachL** [comment]
Are we sure this was working before?

**Comment by filipefurtad0** [comment]
Before v3.8.3? I'm not sure. Maybe it is introduced more recently...

After [we reached this conclusion](https://github.com/openfoodfoundation/openfoodnetwork/issues/7877#issuecomment-873114241) I'm a bit unsure about using semaphore to investigate which version bugs are introduced...

This was tested in staging-UK and -AU, which have different PRs which were staged using semaphore, which seems to always merge to current master. Maybe we could place a dummy order in production?

**Comment by filipefurtad0** [comment]
It's definitively in v3.8.4:
![image](https://user-images.githubusercontent.com/49817236/125066083-82e46380-e0aa-11eb-990a-1139ca87c4f5.png)
