### ISSUE TITLE
Data back up

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#791]
@lynne and I would like users to be able to back up their enterprise data and then restore to earlier versions.  Is this already possible?

**Comment by daniellemoorhead** [comment]
@NickWeir63 @lin-d-hop how do you see this happening? Is it a wikipedia-style view previous versions and restore, or is it more like an iPhone backup where you save a version on your computer/in the cloud for emergency use?

**Comment by pmackay** [comment]
@NickWeir63 can you give any more detail about what data needs to be included?

**Comment by NickWeir63** [comment]
We haven't really thought this through fully yet and it is very low priority but would probably include order cycle history, product details, shopper records, users, enterprise details........

Also not sure how it would work technically - wikipedia style or cloud or what.....

Sorry - not very helpful!

**Comment by lin-d-hop** [comment]
Closing as not specified and not even high enough priority to move to wishlist!
#gitcull2017
