### ISSUE TITLE
Customer unable to pay for order with payment status of "Authorisation Required" 

### ISSUE THREAD

**Issue by RonellaG** [openfoodfoundation/openfoodnetwork#7910]
## Description
An enterprise (New Farm Life, ID 2026) have a number of orders placed using the Stripe payment option that have not completed and have a new payment status called "Authorisation Required" (see screenshot) and the shoppers do not have a way to authorise and therefore complete the payment.

The enterprise has not been transitioned to Stripe SCA yet. 

## Expected Behavior
When an order has a payment status of "Authorisation required" access is provided to the shopper to authorise and complete the payment via the order confirmation and their customer account.

## Actual Behaviour
For order number R432775542.
<img width="1229" alt="Screen Shot 2021-07-12 at 4 18 44 pm" src="https://user-images.githubusercontent.com/68315791/125242453-0f538800-e330-11eb-90b9-72d79542a0ba.png">

We checked the order confirmation email that was sent and it included 2 line items in the payment summary, one for a failed payment followed by one with "Authorisation Required" but there are no links that enable the shopper to authorise the payment. 
<img width="912" alt="Screen Shot 2021-07-12 at 4 04 01 pm" src="https://user-images.githubusercontent.com/68315791/125242498-209c9480-e330-11eb-86e9-abb41c82fddd.png">

We checked their connected Stripe account and the reason for the first payment attempt failed was because it was blocked by the rule - cvc_check: = 'fail'

According to Stripe, all the other orders with a payment status of "Authorisation required" were placed successfully on the first payment attempt.

The payment appears in the customer's bank statement that she shared with us. According to Stripe the failed payment may temporarily appear as pending on the customer's statement before being removed which explains why there are two line items. So we do not think the failed payment is part of this issue.
![Image from iOS (2)](https://user-images.githubusercontent.com/68315791/125247501-5cd2f380-e336-11eb-8a8b-1149febf75a6.jpg)

Over the phone, the customer:

1. logged into her customer account 
2. navigated to transactions
3. She could see a line item for the current order showing authorisation required with button ‘authorise’
4. Clicked authorise button
5. Went to snail ‘page not found’ error
![Image from iOS (4)](https://user-images.githubusercontent.com/68315791/125248024-ee426580-e336-11eb-86e8-d502796da8a3.jpg)
![Image from iOS (3)](https://user-images.githubusercontent.com/68315791/125248037-f26e8300-e336-11eb-815d-eb3f866785b8.jpg)

## Steps to Reproduce
I do not know how to reproduce an order with a payment status of "authorisation required"  because we do not know what determines this status but assume it is required by the bank.

## Workaround
There is a button in the Payment section of the order for "Resend authorisation email" but we could not test it because we could not see any emails in the Orders inbox with those keywords and didn't know what the shopper would be sent and confirm where they would be taken to. 
<img width="1256" alt="Screen Shot 2021-07-12 at 5 36 18 pm" src="https://user-images.githubusercontent.com/68315791/125248760-cf909e80-e337-11eb-85b5-0df93258e864.png">

**Comment by lin-d-hop** [comment]
We are no longer fixing bugs on Stripe Connect. 
I was under the impression all AU enterprises have transitioned to Stripe SCA as we are removing Stripe Connect from the code base in the coming weeks. I would suggest getting this enterprise onto Stripe SCA and then exploring is the problem remains.

**Comment by lin-d-hop** [comment]
@RonellaG Can this be closed?
