### ISSUE TITLE
Error when adding certain product to cart

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#7919]
## Description

One of the Australian shops reported that an error message was displayed whenever you added something to the cart. You could still check out.

## Expected Behavior

The checkout should not raise a random error and enterprise fees should always be associated to an enterprise.

## Actual Behaviour

Enterprise fees can be without enterprise and then the shopfront raises an error.

### Create an enterprise fee without enterprise

1. Select the blank option for an enterprise when editing fees: https://github.com/openfoodfoundation/openfoodnetwork/issues/7919#issuecomment-879787426

### Trigger error

1. Visit affected shop.
2. Add product to cart.
3. Observe server error.

## Workaround

As a dev, delete all enterprise fees which are not associated to any enterprise:

```rb
EnterpriseFee.where(enterprise_id: nil).map(&:delete)
```

## Severity

Labelling as S3 because the checkout is still possible.

## Possible fix

* Remove the blank option for the enterprise on editing fees.
* Validate that every enterprise fee has an enterprise.

## Error in OpenFoodNetwork

**NoMethodError** in **cart#populate**
undefined method `name' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60ebb1106ea573000844d302?event_id=60ed320b007f90fba6ce0000&i=gh&m=ci)

## Stacktrace

    lib/open_food_network/enterprise_fee_applicator.rb:34 - base_adjustment_label
    lib/open_food_network/enterprise_fee_applicator.rb:25 - line_item_adjustment_label
    lib/open_food_network/enterprise_fee_applicator.rb:6 - create_line_item_adjustment
    lib/open_food_network/enterprise_fee_calculator.rb:47 - block in create_line_item_adjustments_for
    lib/open_food_network/enterprise_fee_calculator.rb:46 - each
    lib/open_food_network/enterprise_fee_calculator.rb:46 - create_line_item_adjustments_for
    app/services/order_fees_handler.rb:31 - block in create_line_item_fees!
    app/services/order_fees_handler.rb:29 - create_line_item_fees!
    app/services/order_fees_handler.rb:20 - block in recreate_all_fees!
    app/services/order_fees_handler.rb:17 - recreate_all_fees!
    app/models/spree/order.rb:71 - recreate_all_fees!
    app/controllers/cart_controller.rb:12 - populate

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60ebb1106ea573000844d302?event_id=60ed320b007f90fba6ce0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by mkllnk** [comment]
I don't know which enterprise fee here failed but Australian production has exactly one enterprise fee without an enterprise:
```rb
EnterpriseFee.where(enterprise_id: nil).count
=> 1

EnterpriseFee.where(enterprise_id: nil)
=> #<ActiveRecord::Relation [#<EnterpriseFee id: 682, enterprise_id: nil, fee_type: "packing", name: "Sourcing and packing ", created_at: "2021-07-01 22:32:57.325784000 +1000", updated_at: "2021-07-12 12:56:44.304366000 +1000", tax_category_id: 2, inherits_tax_category: false, deleted_at: nil>]>

```

That fee was last updated yesterday and five minutes later this error appeared for the first time. That might be a coincidence.

**Comment by mkllnk** [comment]
@filipefurtad0 Do you know how to create an enterprise fee and then unassign it from all enterprises?

**Comment by mkllnk** [comment]
I deleted the orphaned enterprise fee and the shop seems to work now.

**Comment by filipefurtad0** [comment]
Thanks for raising this @mkllnk ,

After investigating I think I've found the way to reproduce it. Basically, there is an blank option, when defining enterprise fees:

![Peek 2021-07-14 11-32](https://user-images.githubusercontent.com/49817236/125608272-d257e156-280d-4844-8ec8-f346351582b8.gif)

This changes the respective enteprise fee from:
```

 id  | enterprise_id | fee_type |  name   |         created_at         |         updated_at         | tax_category_id | inherits_tax_category | deleted_at 
-----+---------------+----------+---------+----------------------------+----------------------------+-----------------+-----------------------+------------
 294 |          1785 | packing  | packing | 2021-07-07 14:23:34.062112 | 2021-07-14 10:34:17.183157 |               1 | f                     | 
(1 row)

``` 
 
to
```

 id  | enterprise_id | fee_type |  name   |         created_at         |         updated_at         | tax_category_id | inherits_tax_category | deleted_at 
-----+---------------+----------+---------+----------------------------+----------------------------+-----------------+-----------------------+------------
 294 |               | packing  | packing | 2021-07-07 14:23:34.062112 | 2021-07-14 10:34:17.183157 |               1 | f                     | 
(1 row)


```

If this is associated with an OC then the cart cannot be populated:

![Peek 2021-07-14 11-27](https://user-images.githubusercontent.com/49817236/125608552-7f2911f2-ef92-4c25-98c0-a28ba5f48085.gif)

This triggers:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60eeba5718138a0007f32d9c?event_id=60eeba57007f94b2fa070000&i=sk&m=nw

There is no workaround for the user, as the fee does not appear in the OC outgoing section, after `enterprise_id` is removed:

![image](https://user-images.githubusercontent.com/49817236/125608798-663e75cd-c245-42b4-9fbb-97d245d0c858.png)

Not sure we should not raise this back to S2, as this easily breaks the shopfront. Thoughts?

**Comment by Matt-Yorkley** [comment]
That whole enterprise fees UI desperately needs various improvements, but... maybe for now we could just add a validation on `EnterpriseFee` that ensures an `enterprise_id` is present when saving. It's super simple and TBH I'm surprised it doesn't have it already.
