### ISSUE TITLE
NoMethodError in spree/admin/reports#order_cycle_management

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#792]
## Exception in OpenFoodNetwork

**NoMethodError** in **spree/admin/reports#order_cycle_management**
undefined method `amount' for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/56aadb8207141bdbda637b05?event_id=56aadb8285e028de60190b2f)

## Stacktrace

    lib/open_food_network/order_cycle_management_report.rb:69 - delivery_row
    lib/open_food_network/order_cycle_management_report.rb:31 - block in table_items
    lib/open_food_network/order_cycle_management_report.rb:31 - table_items
    app/controllers/spree/admin/reports_controller_decorator.rb:97 - order_cycle_management

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/56aadb8207141bdbda637b05?event_id=56aadb8285e028de60190b2f)

**Comment by lin-d-hop** [comment]
Fixed now.
