### ISSUE TITLE
Payment attempts on orders with stock restrictions appear as authorized and "uncaptured" on Stripe

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7922]
## Description

Related to #7692.
Follow-up issue from #7779 - This PR introduces a warning to the user about an unsuccessful payment when stock is reduced, when the payment awaits for SCA authentication; it also removes doubling of transaction fees, on every payment attempt.

However, for that scenario, he payment still goes through as authorized and authenticated, appearing as "uncaptured" on Stripe.

Both payments appear on Stripe, (1) and (2):

- The first payment attempt (1) above appears in Stripe as an authorized, but `Uncaptured` payment;
- The second and successful payment attempt appears in Stripe as a `Succeeded`  payment;

![image](https://user-images.githubusercontent.com/49817236/125448269-a94f919e-5fc4-42c9-9e08-e35fa245c8a4.png)

## Expected Behavior

Payment attempts on orders with stock restrictions should be voided, when stock restrictions occur.

## Actual Behaviour

Payment attempts on orders with stock restrictions appear as authorized and "uncaptured" on Stripe

## Steps to Reproduce

As a customer:
1. Add stock to cart
2. Checkout with Stripe SCA
3. Wait till the "Authorization screen" is displayed on the UI

As admin:
4. Set available stock to zero, for that item

As a customer
5. Click `Complete Authentication` (customer)
6. Check the Stripe Dashboard for that account - see the payment is appearing as uncaptured

## Animated Gif/Screenshot

Steps to reproduce:
![Peek 2021-07-13 12-52](https://user-images.githubusercontent.com/49817236/125448887-a546f81f-1e86-44fd-9814-fc16af146f76.gif)

Payment, on Stripe Dashboard:
![image](https://user-images.githubusercontent.com/49817236/125452195-e46a153c-7e90-4b5f-ab7b-b1d9366584b8.png)

## Workaround

Cancelling the payment on Stripe:
![image](https://user-images.githubusercontent.com/49817236/125452349-d8a3ebaf-4f69-4ad6-98d3-8cf5c1ccab21.png)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.8.4
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by RachL** [comment]
@filipefurtad0 when the payment in uncaptured on Stripe it has still left the shopper's bank account right? I'm wondering if this severity is not higher, but I'm highly confused by Stripe capture feature. I'm not sure what it is used for....

**Comment by filipefurtad0** [comment]
Yeah, I'm wondering too...

An uncaptured payment still has not left the shoppers account, but the amount is reserved, and as such, not available to be used by the shopper for other purchases.

On https://stripe.com/docs/payments/capture-later:

>Place a hold on a card to reserve funds now but only capture them after your business completes the service. For example, a hotel may authorize a payment in full prior to a guest’s arrival, then move the money when the guest checks out. 

So... this means that in order to make the amount "useful" again on the customers account, the manager would have to manually void the payment. But this probably is not a useful workaround if we have several such payments...

Upgrading to S2, thanks for your feedback :+1:
