### ISSUE TITLE
Add tooltip for 'schedule' and 'order cycle' on the OC admin page

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#7924]
"In the Order Cycle admin page there is an Add Schedule button - clicking this opens a modal"... This button didn't appear on the page until Subscriptions was enabled in Enterprise > Manage. I only knew this was an issue due to Nick's comment.

As a User I am not familiar with the terminology - but ‘schedule’ and ‘order cycle’ were not easily understood. Consider adding a tooltip for the labels?

![subscriptions1](https://user-images.githubusercontent.com/1451633/74142446-35d03980-4bf9-11ea-8aee-08d9453dc7e7.jpg)

_Issue spotted by Yuko_

**Comment by andrewpbrett** [comment]
Closed via https://github.com/openfoodfoundation/openfoodnetwork/pull/7923
