### ISSUE TITLE
Replace "feature specs" for "system tests" 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7929]
### What we should change and why (this is tech debt)

**Project steps**
~~- Create OFN's first "system test" under a new directory (/spec/system, I guess), with a simple browser-based test that passes.~~ - done
~~- Add the Ferrum-Cuprite driver to the stack. Configure all tests of the "system test" type to run on Ferrum-Cuprite instead of Selenium (but leave the old feature spec setup as it is, with Selenium).~~ - done
- slowly transition towards Ferrum-Cuprite, replacing old feature specs (Selenium) 

**Guidelines**

https://ofn-user-guide.gitbook.io/ofn-testing-handbook/automated-testing-handbook/system-specs

**Background**
https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing#modern-system-tests-with-cuprite
https://guides.rubyonrails.org/testing.html#system-testing

### Context

This came up here:
https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1626093858077600?thread_ts=1626075838.077100&cid=C02TZ6X00

### Impact and timeline

This impacts all feature specs, build performance and its reliability.

**Comment by filipefurtad0** [comment]
Should we now create a branch and migrate all `spec/feature` -> `spec/system`?

**Comment by RachL** [comment]
@filipefurtad0 I see all issues have been completed here. Can this epic be closed?

**Comment by filipefurtad0** [comment]
We can close the epic I think :+1:
Thank you for noticing this.

There are however two pending issues:
- #8434
- and some final clean-up will surely be needed as well (after removing/migrating that last file  `spec/features/admin/invoice_print_spec.rb`) - no issue for this yet
