### ISSUE TITLE
Alternative invoice: Tax rate not displayed for shipping fee

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7934]
## Description

Relates to #7892; closely related to #7932 and #7933.

The alternative invoice does not display the tax rate for a shipping fee, on the `Tax rate` column.

## Expected Behavior

The alternative invoice displays the tax rate an applied shipping fee, on the `Tax rate` column.

## Actual Behaviour

Currently, no information is displayed on this space (see pic below).
 
## Steps to Reproduce

Same 6 steps as in issue #7932.

7. As super admin, select the option "Use the alternative invoice model" under `/admin/invoice_settings/edit`
8. As admin, visit the order and click Print invoice -> notice the blank space on the `Shipping / Tax rate` table entry

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/125651759-63edefb7-d321-4ec7-99dc-e843f089fbc4.png)

## Workaround

Calculate these values manually.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.5.8
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by jibees** [comment]
@filipefurtad0 
I'd like to dive into this one, trying to reproduce, but not sure to understand why the design of the invoice is not the same: 
<img width="753" alt="Capture d’écran 2022-02-04 à 15 59 42" src="https://user-images.githubusercontent.com/296452/152551237-e45fcc57-22ca-4439-b80a-97463142e882.png">
Do you use the "Print invoice" button here?
<img width="342" alt="Capture d’écran 2022-02-04 à 16 00 46" src="https://user-images.githubusercontent.com/296452/152551327-430d878e-536b-47ec-a4b9-9a2fe489b0eb.png">

**Comment by drummer83** [comment]
@jibees Have you tried step 7 in "How to reproduce" above? The two different designs are an instance setting.
Hope I gotten your question right...

**Comment by jibees** [comment]
@drummer83 Yep, I've tested, and indeed I can see some differences :
<img width="748" alt="Capture d’écran 2022-02-04 à 16 23 10" src="https://user-images.githubusercontent.com/296452/152555068-301ea261-d9a5-45c1-8e79-ab22549d1542.png">
VS. 
<img width="743" alt="Capture d’écran 2022-02-04 à 16 23 25" src="https://user-images.githubusercontent.com/296452/152555077-5cd7ec4f-79a8-45ba-a313-594f578d14f1.png">

But none of these invoices have the same design with the beautiful table header. Wondering if i'm missing something or if I'm facing a bug.

**Comment by jibees** [comment]
Yeap, seems like an issue around CSS loading with `wicked_pdf_stylesheet_pack_tag`. Worth debuging.
