### ISSUE TITLE
Tax display changes (follow-up from PR #7892)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7936]
This Epic groups some bugs and requests around the the displaying of tax info.

**Comment by drummer83** [comment]
I don't seem to understand this epic thing... Where do I see the bugs which are grouped here?

**Comment by filipefurtad0** [comment]
Hey @drummer83 ,

Epics are a [feature from Zenhub](https://help.zenhub.com/support/solutions/articles/43000010341), so you'll need to have the Zenhub plugin working on your browser and log in to Zenhub (using your Github credentials), so this feature is active. This should make the sub-issues on an epic visible :+1: 

You can also use the Zenhub website https://app.zenhub.com/ to access the board, and then search/click the epic.
