### ISSUE TITLE
When filling in my profile, if I go back to a previous stage of the process, images are lost

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#794]
When I register a hub or producer, in the process I upload a logo, and a banner. If I forgot something and go back to the previous tabs to check, then the images are lost.
Here is what I see after having clicked on "previous", the images are lost (or seem to be lost at least, which is confusion):
![signup](https://cloud.githubusercontent.com/assets/8135376/12694251/656e8058-c727-11e5-89a0-0452608925c9.png)

**Comment by myriamboure** [comment]
Ping @blancnic, minor fix I guess, maybe the images are stored but it just doesn't appear on the screen when you clic on previous...

**Comment by myriamboure** [comment]
Ok, I confirme the image is stored in the profile, but the user has the impression that it was not loaded (the image should appear on the screen and stay there if I click on "previous"

**Comment by blancnic** [comment]
I confirm the problem, I'm going to take a look at it...

**Comment by myriamboure** [comment]
Closing as not so vital and never had user feedback on it, will address that later when we'll have treated all the important things. Iceboxed https://community.openfoodnetwork.org/t/hubs-and-producers-can-easily-create-their-enterprise-on-ofn/1248
