### ISSUE TITLE
Paypal credentials in plain text: security issue

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#798]
After having filled in the Paypal info (Paypal express payment gateway), the payment method works fine. BUT when I go into the Payment Method details i see that all info is there in plain text, API login, password and signature...!

1) Front-end: these values should probably be hidden with copy paste disabled? As when you register your credit card details on a website, when you come and check later, most digits are hidden.

2) Back-end: if they are displayed in plain text, are they also stored in plain text? Hopefully they are encrypted... 

(see image here: http://community.openfoodnetwork.org/t/paypal-credentials-in-plain-text/493)

Estimate = 3 hours

**Comment by daniellemoorhead** [comment]
@mkllnk the Norway team are happy for us to go ahead and do this work as part of V1.6

**Comment by mkllnk** [comment]
I worked on this today and these input fields are very deep within the Spree software. Hiding the password and the signature would need a lot more time. But I have a version that hides the password. For anything more advanced, I would vote for upgrading Spree. Sally can test this version next Wednesday.

**Comment by daniellemoorhead** [comment]
@sigmundpetersen please see @mkllnk's comment above. Is hiding the password an acceptable fix at this stage?

**Comment by sigmundpetersen** [comment]
It's Olivier who knows the details. He is not on github but maybe you could describe and ask him here http://community.openfoodnetwork.org/t/paypal-credentials-in-plain-text/493?

**Comment by daniellemoorhead** [comment]
Ohhh, of course it was! Sorry @sigmundpetersen :)

**Comment by sigmundpetersen** [comment]
No need to be sorry :)

**Comment by mkllnk** [comment]
@sstead Most Payment Methods on staging2 don't have any credentials set. Here are the exceptions:

- https://staging2.openfood.com.au/admin/payment_methods/47/edit
- https://staging2.openfood.com.au/admin/payment_methods/51/edit
- https://staging2.openfood.com.au/admin/payment_methods/5/edit
- https://staging2.openfood.com.au/admin/payment_methods/45/edit

They all have a password set. Make sure that it's not displayed in the new staged version. Then do some changes and create new ones. Tell me which ones you changed and if you set new passwords or not. I can then check in the database if the passwords are still set correctly.

If you have the chance to do a test payment, that would be great. But don't think that there would be an issue.

**Comment by mkllnk** [comment]
Merged to production. The things that are not ideal:

- Password fields are just empty instead of showing dots/stars.
- Signature is still visible.

Both need more time to solve. We need to implement our own view of payment methods or upgrade Spree. So I close this for now.
