### ISSUE TITLE
[Staging-servers] Semaphore deployments are not branch/commit-specific

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7986]
## Description

It was[ recently noticed](https://github.com/openfoodfoundation/openfoodnetwork/issues/7877#issuecomment-873119788) that deployments on staging servers using Semaphore were not specific regarding to:

- the branch -> the target branch appears to be staged "together" (merged?) with master
- the commit -> the most recent version of a branch is being deployed

This introduces uncertainties when testing, both individual PR's and release testing.

## Expected Behavior

We should be able to specify deployments in regards to the `branch` and a given `commit`.

## Actual Behaviour

Deployment made using Semaphore stages the most recent version of a given branch together with the changes on current master branch.

## Steps to Reproduce

See https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1627379299208200.

1. Check the latest master, looking for a file changed by a recent merge. Take notice of those changes.
2. Look for a branch, preferably a long living one, which has not been recently rebased (thus not including the recent changes in master). Take notice of the changes it introduces.
3. Look for a staging server, which has yet another branch staged in it.
4. Stage the branch selected in step 2.
5. Login via ssh to the staging server and check for:
a) the changes noted in step 1.
b) the changes noted in step 2.
6. See how the server displays the changes both in a) and b) -> it is expected to only have changes from b) 

## Workaround

Manual deployments (using ansiable?) seem like the only option to be specific about commit/branch, when staging in staging servers.

## Severity

Relevant for testing but for development as well?

## Possible Fix

Could this be fixed by changing/improving the current Semaphore scripts?

**Comment by Matt-Yorkley** [comment]
I think I can tweak the deployment settings to use the commit reference instead of the branch. I'll try it now...

**Comment by Matt-Yorkley** [comment]
I've made some adjustments that should get the outcome we want:
> When deploying to staging via Semaphore, specific versions of master (including drafted releases) will use the exact commit, but pull requests will use the latest version of the branch merged with master.

**Comment by jibees** [comment]
> pull requests will use the latest version of the branch merged with master. [...] we'll also include recent changes when testing PRs that haven't been rebased recently.

Brilliant!
