### ISSUE TITLE
Make phone number field not mandatory on Checkout 1st step

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#8008]
## Description

As mentioned [here](https://community.openfoodnetwork.org/t/checkout-customization-adapt-fields-required-to-the-hub-model-and-customer-type/1163) and discussed in Slack, the phone number field on the 1st step of the checkout should not be mandatory.

This should be done as part of https://github.com/openfoodfoundation/openfoodnetwork/issues/7408 

**- As a:** user
**- On page:** /checkout/enter-your-details

## Acceptance Criteria & Tests

1. User does not enter their phone number
2. User clicks on "Next"
3. User is forwareded to next step (payment details), no error message for missing phone number

**Comment by andrewpbrett** [comment]
closed via https://github.com/openfoodfoundation/openfoodnetwork/pull/8076
