### ISSUE TITLE
Fix authorisation of non-permitted VOs

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#801]
@oeoeaio to work with @sstead to fix this.

**Comment by sstead** [comment]
Description of how permissions currently operate here - http://community.openfoodnetwork.org/t/upgrade-variant-override-to-inventory-management-interface/398/4

**Comment by daniellemoorhead** [comment]
@oeoeaio as per your update at standup today, you'll be looking into this to see whether it needs to/can be fixed for v1.5.

**Comment by sstead** [comment]
Testing permission for VO now...
- The permission issue relating to ownership is still happening. I can create VOs for any producer owned by the same user who owns the Shop.
E.g....
![image](https://cloud.githubusercontent.com/assets/10843056/13343903/41e5bbc2-dca5-11e5-87c5-c71826a207a7.png)
similarly ...
![image](https://cloud.githubusercontent.com/assets/10843056/13343905/481ab786-dca5-11e5-9381-259e2c484a47.png)
But on the bright side...for enterprises owned by different users, I'm only about to create inventory if the producer has granted me P-VO. Granting P-OC is enough for them to appear in my inventory dropdown, but I can't actually see their products and do over-rides... 2 screenshots below... 
![image](https://cloud.githubusercontent.com/assets/10843056/13343945/93000648-dca5-11e5-828d-62f16e0b2cfa.png)
...And...
![image](https://cloud.githubusercontent.com/assets/10843056/13343955/9ff13066-dca5-11e5-8327-25994e991887.png)
Further good news... when logged in as sallystead2@gmail.com and when I go to Inventory, I can only select shops I own. This is good. However, I'm not sure what should happen in this scenario. I set up a buying group that distributes for one of my hubs, and they gave me P-VO, should I be able to create inventory for them? See screenshot below...
![image](https://cloud.githubusercontent.com/assets/10843056/13344025/4eb24b8a-dca6-11e5-8db0-56c3c5db4b0e.png)

**Comment by sstead** [comment]
Automatic update of shopfront when you change inventory settings is working :)

![image](https://cloud.githubusercontent.com/assets/10843056/13344998/7b5f9c56-dcaf-11e5-9377-49963800e3ee.png)

**Comment by sstead** [comment]
Cool, so @oeoeaio other than the permission thing when you own two enterprises but don't have correct P-VO, and the buying group scenario, I'm happy with everything else :)

**Comment by oeoeaio** [comment]
Thanks Sally! First issue you raised is the only unexpected behaviour - due to a stuff up by me. Will fix by Wed morning.

**Comment by oeoeaio** [comment]
Ok, so: final things to check

1. User can only override variants of producers who have explicitly granted P-VO  management/ownership and P-OC should have no effect
2. Inventory page automatically selects a hub when it is the only option
3. 'Override Variant Details' permission renamed to 'Add Products To Inventory'
4. Variant override permissions should be applied as soon as they are added or removed, and we shouldn't get any authentication errors from the server when we try to save changes to other variants on the inventory page
5. Updated text for "inventory only" product selection setting for enterprises is ok?
6. 'Variant Overrides' index page has been renamed to 'Inventory'
7. When a variant is in an exchange, but not inventory, and the enterprise setting changes to "inventory only" the product immediately disappears from both the order cycle and the shop (without updating the order cycle)

**Comment by sstead** [comment]
1) Yep!! The only thing is if I filter by hub in Inventory page, I can still see non P-VO producers in the producer dropdown. Do we want to make it so you can't try to see them? The important thing though is that you can't see the products.
2) Yep!
3) Yep!
4) Yep! If products are in an order cycle with P-VOs and overrides in place, when I remove P-VO, they revert to master price/qty. I can also no longer see the products in my Inventory. If I reinstate P-VO, the go back to old Inventory settings. The system seems to remember old over-rides. 
5) Yep!
6) Yep!
7) Yep! changing the inventory settings will immediately remove any new products from the outgoing section of OC, and shopfront. And vice versa.
