### ISSUE TITLE
"Amount" on Delivery Report does not account for order edits

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8019]
## Description

After an order is placed, the `Amount` displayed in the Delivery Report does not reflect subsequent order edits (ex. by adding or removing items)

## Expected Behavior

The "Amount" column on the Delivery Report should reflect changes on the order total, from editing an order.

## Actual Behaviour

The "Amount" column on the Delivery Report does not reflect changes on the order total: it displays the initial order total.

## Steps to Reproduce

1. Place an order.
2. Visit `/admin/reports/order_cycle_management`and find the line corresponding to the customer and order
3. Edit the placed order, ex. remove some line items; issue a refund (pic below).
4. Compare the order total found on `/admin/orders/<order_nr>/edit`with the `Amount` one found on the Delivery report: the latter still displays the initial order total (before the order edit).

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/128693466-5a891cbf-c3c5-48ef-813a-4317a968cd6f.png)

## Workaround

None;
Proposing S3 as I'm not really sure on the impact on this one.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used:  v3.8.8
* Browser name and version: Firefox 90
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by lin-d-hop** [comment]
I actually think this should be an S2.

A workaround of 'look at a different report for the same information' shouldn't be a workaroud. How is a user supposed to know which report is correct?

This has caused a bit of confusion in the UK that I was struggling to track down... only just spotted this issue. Nice catch @filipefurtad0

**Comment by lin-d-hop** [comment]
@apricot12 This might be one you can look at? Getting your head into reports would be really great at the start of the reports project :-)

**Comment by apricot12** [comment]
> @apricot12 This might be one you can look at? Getting your head into reports would be really great at the start of the reports project :-)

Since this is an S2, I'll prioritize this and start on Monday 👍
