### ISSUE TITLE
Full profile modal about section copy display improvement

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#806]
Add "more" and "less" links for the copy part of the about section - remove the scroll bar.

**Comment by mkllnk** [comment]
Because of the timebox on this issue, we decided to just remove the scroll bar. But we don't have more/less buttons.

**Comment by sstead** [comment]
![image](https://cloud.githubusercontent.com/assets/10843056/13621785/36b68bb2-e5ee-11e5-9d61-131c6663d39c.png)


@mkllnk  Hey my interpretation was that the left scroll bar would be gone...? Is that what this issue is about?

**Comment by mkllnk** [comment]
Yes, the scroll bar should be gone. I assume that this screen shot is from current staging and it didn't work?
