### ISSUE TITLE
Inherited product properties impacting filtering after removal

### ISSUE THREAD

**Issue by adele-ofn** [openfoodfoundation/openfoodnetwork#8075]
## Description
For enterprises who want to use the same "properties" tag(s) on most of their products, they may use the "inherit properties" checkbox to carry these properties across from one product to their entire range. For example, a baker who sells mostly gluten-free bread may wish to use this feature to tag all of their products with the "gluten-free" property. 

However, if they begin stocking a product which does not carry the same properties as the rest of their range (for example, a product which is not gluten-free), they will need to untick the "inherit properties" checkbox for that product, so it not not inherit this tag. This action successfully removes the tag from that product, but it still shows up in the listing when a customer filters by the tag it previously carried (e.g. it would still appear when filtering for "gluten-free", even though it no longer carries this tag).

This issue was raised by an enterprise in the Australian instance (Fork it Farm, enterprise no: 2183), but had been previously identified by global instance managers (though not yet logged as a bug).

## Expected Behavior
Enterprises expect that when the "inherit properties" checkbox is unticked for a product, the inherited properties are removed from that product - it is no longer tagged with that property, and it does not appear if a customer filters by that property.

## Actual Behaviour
When the "inherit properties" checkbox is unticked for a product, the inherited tag is removed, but the product still appears when a customer filters by that property in the shopfront.

## Steps to Reproduce
1. Log into enterprise in OFN backoffice.
2. Open shopfront link in a separate tab.
3. Click into "Properties" tab for the enterprise.
4. Create a property and add a description.
5. Click into "Products" tab, and open a product.
6. Click "product properties" tab.
7. Untick "inherit properties from enterprise" checkbox and click "update".
8. Delete the property for this product.
9. Open the shopfront tab and scroll to find product - it should no longer have this property tag.
10. Filter by property tag, it will still appear in the listing (despite no longer having the tag).

Have reproduced in superadmin and demo account, same issue arises for both.

## Animated Gif/Screenshot

<img width="1440" alt="1" src="https://user-images.githubusercontent.com/89006237/130004307-37121c0e-1ad3-458c-ac20-2eb6c87c336b.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/89006237/130004314-52a8f492-04c2-46be-90d7-f5c59bdb2ad1.png">
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/89006237/130004321-bc75334c-860e-4f2e-a5dd-757d04297260.png">
<img width="1436" alt="4" src="https://user-images.githubusercontent.com/89006237/130004330-98e1f7a4-6b2f-4d1f-bfe7-1d648dfc898d.png">
<img width="1440" alt="5" src="https://user-images.githubusercontent.com/89006237/130004335-e6867027-e91c-4ba1-ae78-a465cd900220.png">

## Workaround
There is no workaround for this issue. It may not appear critical, as it does not impact the shopper's ability to purchase from a shopfront, however it is at odds with Open Food Network values regarding transparency. Shoppers should be able to access accurate information about the products their purchasing from OFN, as intended by the enterprise owner. This bug has the potential to mislead customers.

## Severity
bug-s3

## Your Environment
* Browser name and version: Chrome Version 92.0.4515.131 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): macOS Sierra Version 10.12.6

**Comment by karlafalk** [comment]
Also see [wishlist issue #111 ](https://github.com/openfoodfoundation/wishlist/issues/111#issue-967496073)
