### ISSUE TITLE
Sidekiq error on bulk printing: Errno::ENOENTBulkInvoiceJob@default

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8080]
## Description

~~Plenty of occurrences on the this error on the last day only, but so far only on UK-prod - checked bugsnag for FR, DE, US, AU:~~

Issue reported for FR-prod:

https://app.bugsnag.com/open-food-france/coopcircuits/errors/64802e66f3387700081f3ad9?event_id=64805b0700be10ebf2020000&i=sk&m=fq

One print attempt triggers several errors in Bugsnag.

## Expected Behavior

~~There have been user reports on this, so I guess the b~~
Bulk-pdf printing is not working for users.

## Actual Behaviour

Users should be able to bulk-print pdfs.

## Steps to Reproduce

~~Could not reproduce it in staging.~~

1. On the orders page, select a some orders
2. On the Actions dropdown, select Print invoices
3. Notice the print-job never finishes.
4. Notice the multiple Bugsnag errors.

## Workaround

Printing individual invoices, on the edit order pages, works as before.

Or as dev, after deploy run:
```
ansible all-prod -u openfoodnetwork -a 'mkdir -p ~/apps/openfoodnetwork/current/tmp/invoices'
```

## Severity

S2 at least for further investigations and to prevent it affects other instances.

## Your Environment

* Version used: ~~v4.0.1~~ v4.3.11
* Browser name and version: Firefox 113
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

Possibly related to the latest rollback?

**Comment by cillian** [comment]
IE had multiple occurences of this issue too between 19:36 yesterday and 03:44 this morning. But bulk invoice printing seems to working again right now.

**Comment by lin-d-hop** [comment]
It seems that this was caused by the reverting and redeploying of the last release.
Users are reporting this is fixed.
I'm going to close. Reopen if this continues to be a problem for anyone.

**Comment by sigmundpetersen** [comment]
The last release had a bump of sidekiq and sidekiq-scheduler, so could be related.
I guess the fastest attempt would be to revert those PR's and test bulk printing?

**Comment by filipefurtad0** [comment]
Before reverting, I was trying to capture the bug on a spec. We have a test for bulk printing here, but it would not catch this regression:

https://github.com/openfoodfoundation/openfoodnetwork/blob/1c9a09d88dc5379f698ee3df746447b5dca7cffc/spec/system/admin/orders_spec.rb#L529-L542

I've found [this advice](https://sloboda-studio.com/blog/testing-sidekiq-jobs/) for having sidekiq in inline! mode for tests, which should run the jobs immediately instead of enqueuing them.

In any case, the modal never disappears and we have a 422 in the console. So, I was not able to have a pending spec for the bug. Instead, I'll make a branch reverting #10898 and #10782, stage and check if it fixes the issue.

**Comment by Matt-Yorkley** [comment]
> Sidekiq::Testing.inline!

Interesting... that might help with some of the flaky specs we have on the background reports PR. I'm wondering if we should apply it to the whole test suite or maybe just enable it on individual tests that need it? It looks like it can take a block, like:

```ruby
describe "printing invoices" do
  page.find("span.icon-reorder", text: "ACTIONS").click 
  
  Sidekiq::Testing.inline! do
    page.find("span", text: "Print Invoices").click
    # etc...
  end
end
```
