### ISSUE TITLE
start the shop front with a list of categories (taxons)

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#809]
Oliver (the Stroudco manager) suggests that we start the shop front with a list of categories (taxons). And then show them one at a time.

**Comment by pmackay** [comment]
How do you imagine showing them one at a time would work?

**Comment by lin-d-hop** [comment]
I'm not so sure about this @NickWeir63 
Was the motivation speeding up load time?
Taxons are displayed across the top of the product page once the page loads, so users can just select (once load time improves).

I think this would be a negative feature for producers that just sold one category (ie a small cheese producer). Users would have to click on the Cheese button to get to their shop, and erroneous step for this shop.

Can we discuss this once the product load speed is not a factor?

**Comment by NickWeir63** [comment]
Yes I have put a note in [713 ](https://github.com/openfoodfoundation/openfoodnetwork/issues/713)to tell Rohan not to include this idea in the load speed work he is doing.  It is something that Oliver (the Stroudco manager) wants to see but he is happy to wait and discuss it at a later date.

**Comment by lin-d-hop** [comment]
#gitull2017
This refers to features desired in a rewrite of the shopfront. Needs further specification.
