### ISSUE TITLE
Replace default alert by a custom modal when removing last item from an order 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8098]
## Description

Follow-up from issue #8040.
The default modal has some design and usability issues - it can, for example, be muted, see discussion and testing notes on the issue.

## Expected Behavior

When removing last item from an order a custom modal should be displayed, instead of the default warning. 

## Actual Behaviour

When removing last item from an order the default warning is displayed.

## Steps to Reproduce

As an admin:
1. Edit an order
2. Attempt to remove the last item
3. See the default alert
4. Mute the default alert
5. Click around and notice how the UI appears to be broken - clicking the trash bin does not remove the last item

## Animated Gif/Screenshot

![Peek 2021-08-24 11-23.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/cb2680d6-8db7-4b82-baab-77eb2222d49b)

## Workaround

It is usable, but not very visible and able to be muted.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.0.2
* Browser name and version: Firefox 90
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by meronokbay** [comment]
:eyes: can I pick up this issue?

**Comment by jibees** [comment]
> 👀 can I pick up this issue?

Sure! Please, feel free to pick it up! Thanks.
