### ISSUE TITLE
Payment taken in Paypal but order in state = Payment

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8109]
## Description

UK order R702316474

Payment was taken via Paypal for this order.
Many of the items were out of stock
The order is in State = Payment
However the order has a 'completed_at' time registered.

Having State = Payment (meaning not 'complete') and having a 'completed at' time seems to have caused discrepencies. There is a difference between the presence of this order in reports and the presence of this order in the 'Notify Producers' email which has caused confusion.

I suspect this is related to #7692 and potentially ofn-install issue #643

## Expected Behavior

Payment taken in paypal
Order state = complete
'Completed-at' datetime filled
Consistency between Notify Producers email and Reporting

## Actual Behaviour

Payment taken in paypal
Order state = Payment
'Completed-at' datetime filled
Lack of consistency between Notify Producers email and Reporting

## Steps to Reproduce

Not sure.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: UK Prod
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by andrewpbrett** [comment]
@lin-d-hop Also I'll be away starting tomorrow evening through Thursday (Sept 2); if we get more info during that time we'll need someone else to pick it up.

**Comment by lin-d-hop** [comment]
@andrewpbrett 
Please ignore the reporting issue here for now. Let's focus on the fact that a paypal payment was taken and yet the order was not received in OFN.

Sounds like #7692.
Given this is happening in Paypal and not Stripe is an indication that redirects might be at fault as per ofn-install issue #643 

I will update the description to focus on the problem that we actually need to focus on here.

**Comment by Matt-Yorkley** [comment]
I think there's a good chance both of these issues will be fixed by #8090

**Comment by andrewpbrett** [comment]
So if we're pretty sure this is related to redirects, and fixed by #8090, shall we close it and reopen if it happens again after 4.0.2 is deployed?

**Comment by filipefurtad0** [comment]
Currently - before deploying #8090 into production -  we have 3 orders in UK and 4 in FR which have are in `state` = 'payment' but have a `completed_at` value:

`SELECT * FROM spree_orders WHERE state = 'payment' AND completed_at IS NOT NULL;`

```
   id    |   number   | item_total | total |  state  | adjustment_total | user_id |         created_at         |         updated_at         |        completed_at        | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |          email          | special_instructions | distributor_id | currency | last_ip_address | order_cycle_id | customer_id | created_by_id | included_tax_total | additional_tax_total 
---------+------------+------------+-------+---------+------------------+---------+----------------------------+----------------------------+----------------------------+-----------------+-----------------+---------------+----------------+---------------+-------------------------+----------------------+----------------+----------+-----------------+----------------+-------------+---------------+--------------------+----------------------
 2044346 | R702316474 |      60.70 | 73.97 | payment |            13.27 |  204882 | 2021-08-20 19:47:21.606872 | 2021-08-27 12:42:33.856424 | 2021-08-20 20:04:46.840806 |          813344 |          813346 |         83.20 | pending        | credit_owed   | <email_removed>   |                      |            160 | GBP      | 109.152.243.8   |         209222 |       18035 |        204882 |               1.49 |                 0.00
  417047 | R413520401 |      48.08 | 48.08 | payment |             0.00 |         | 2018-09-10 07:50:45.918177 | 2018-09-10 08:06:53.650028 | 2018-09-10 08:06:50.858318 |          328543 |          328544 |         48.08 | pending        | paid          | <email_removed>   |                      |         200205 | GBP      | 127.0.0.1       |         202198 |        4200 |               |               0.00 |                 0.00
 1236945 | R388325464 |       2.96 |  3.85 | payment |             0.89 |  204882 | 2020-08-22 18:58:10.794166 | 2020-08-24 14:09:45.634018 | 2020-08-22 19:00:26.710048 |          564269 |          564270 |          3.85 | pending        | paid          | <email_removed>   |                      |            160 | GBP      | 127.0.0.1       |         205636 |       18035 |        204882 |               0.00 |                 0.00
(3 rows)
```

in FR:

```
   id    |   number   | item_total | total |  state  | adjustment_total | user_id |         created_at         |         updated_at         |        completed_at        | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |           email            |     special_instructions      | distributor_id | currency | last_ip_address | order_cycle_id | customer_id | created_by_id | included_tax_total | additional_tax_total 
---------+------------+------------+-------+---------+------------------+---------+----------------------------+----------------------------+----------------------------+-----------------+-----------------+---------------+----------------+---------------+----------------------------+-------------------------------+----------------+----------+-----------------+----------------+-------------+---------------+--------------------+----------------------
 1433076 | R302442332 |      69.45 | 70.56 | payment |             1.11 |    5852 | 2020-09-04 17:03:55.285782 | 2020-09-24 12:41:28.767646 | 2020-09-04 19:26:31.396606 |          453142 |          453143 |         70.56 | pending        | paid          | <email_removed>  |                |            922 | EUR      | 91.168.149.97   |           5107 |        7338 |          5852 |               3.61 |                 0.00
 1518412 | R472553603 |      49.97 | 55.97 | payment |             6.00 |   10842 | 2020-10-04 08:21:30.171172 | 2020-10-05 07:52:02.232298 | 2020-10-04 08:33:49.970303 |          524400 |          524401 |          0.00 | pending        | failed        | <email_removed>  |                |            922 | EUR      | 90.112.155.225  |           5453 |       12312 |         10842 |               3.63 |                 0.00
 1886417 | R584254364 |      31.80 | 37.80 | payment |             6.00 |   17501 | 2021-03-07 12:29:35.170359 | 2021-03-17 12:36:37.953426 | 2021-03-07 12:41:10.90518  |          700433 |          700434 |          0.00 | pending        | failed        | <email_removed>  | <removed>      |            922 | EUR      | 193.33.56.162   |           6875 |       19224 |         17501 |               3.88 |                 0.00
 1831944 | R210757342 |      28.56 | 34.56 | payment |             6.00 |   17501 | 2021-02-08 07:32:45.712288 | 2021-03-17 12:42:08.495596 | 2021-03-15 06:31:45.155671 |          700433 |          700434 |          0.00 | pending        | failed        | <email_removed>  | <removed>      |            922 | EUR      | 193.33.56.162   |           6956 |       19224 |         17501 |               3.70 |                 0.00
(4 rows)
```

So maybe we can close the issue and check these queries again some time soon?

It would be to receive a notification once an order with `state = 'payment' AND completed_at IS NOT NULL` is created. Could we maybe [use Metabase for this](https://www.metabase.com/docs/latest/users-guide/15-alerts.html)? Probably not syncing often enough though.

**Comment by filipefurtad0** [comment]
It is interesting to note that not all of these are Paypal payments. In FR, for orders with ids `1886417` and `1831944` payment method `376` was used which is `Spree::Gateway::StripeSCA` .

**Comment by RachL** [comment]
Yes I think we only have 1 paypal user 🙈

**Comment by andrewpbrett** [comment]
> It is interesting to note that not all of these are Paypal payments

@filipefurtad0 that seems consistent to me; #8090 is fixing an issue where someone is logged in on the "wrong" domain, and then redirected to a different one after completing payment. That can happen with Stripe or PayPal.

**Comment by andrewpbrett** [comment]
@filipefurtad0 thanks for running those queries, useful to have that before and after deploying. I agree we should close this now that #8090 is deployed and re-run those queries in a week or so to see if there are any orders in that state.

**Comment by filipefurtad0** [comment]
I'm not sure whats the best way to be notified automatically when these corrupt orders pop in, something to discuss. But in the meantime I've set a reminder in #testing to check these queries in a week's time.

**Comment by filipefurtad0** [comment]
I've just logged in to the prod DBs in UK and FR ran the queries and got the exact same [results as above](https://github.com/openfoodfoundation/openfoodnetwork/issues/8109#issuecomment-914175645) :+1:
