### ISSUE TITLE
Error when notifying producers

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#811]
In the order cycle, I click on "notify producers".
The emails are sent to the different producers, BUT the cancelled orders are included in the emails sent automatically.

Example:
For the producer "Norganic", 11 items has been ordered, and one order with 2 items has been cancelled.

In the report, it is correct, I have 11.
![norganic1](https://cloud.githubusercontent.com/assets/8135376/12854591/ddaf690c-cc3a-11e5-889b-8c42667f4f75.png)

But in the email received by Norganic, I see 13
![norganic2](https://cloud.githubusercontent.com/assets/8135376/12854643/1bc237ce-cc3b-11e5-83d8-792b9a37d7e2.png)

The email should not include the itmes from the canceled orders.

**Comment by myriamboure** [comment]
@daniellemoorhead should we put a "core" label on that one?

**Comment by myriamboure** [comment]
Is it the same issue as https://github.com/openfoodfoundation/openfoodnetwork/issues/1009
@sigmundpetersen have you reproduced the error in Norway again? Or can we close?

**Comment by sigmundpetersen** [comment]
Seems like the same issue yes. Should be fixed though, ref http://community.openfoodnetwork.org/t/what-s-new-v-1-8-1-160618/612. So think we can close, @daniellemoorhead ?

**Comment by lin-d-hop** [comment]
Closing #gitcull
