### ISSUE TITLE
Should production log level be set to :warn?

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#812]
Am noticing UK production log is pretty large, is that necessary? 

Thoughts @RohanM @oeoeaio @mkllnk ?

**Comment by mkllnk** [comment]
I never look into the log file. And when we did to solve more difficult problems, we had to increase the log level to find the problem. So I think the default could be error.

But is that maybe a symptom of issues in the code that there are so many warnings?

**Comment by pmackay** [comment]
I think the default currently is `info` which produces a lot of output about rendering, not very useful.

**Comment by daniellemoorhead** [comment]
@pmackay what do you suggest it should be instead?

**Comment by pmackay** [comment]
Set it to warning or error level so the output is less.

**Comment by mkllnk** [comment]
Let's set it to warning then and see how that goes.

**Comment by daniellemoorhead** [comment]
Great, thanks @mkllnk. Can you close this issue once you're done?

**Comment by mkllnk** [comment]
Ok, @pmackay would you like to do a pull request? It will be tiny, I know.

**Comment by daniellemoorhead** [comment]
@pmackay you ok to close this issue now that the PR has been merged?
