### ISSUE TITLE
[master] Can't login to a user account (not in production)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8126]
## Description

In current master `build aaf45afbfe14d4ec10752b2049b5fc3da901be80` it is not possible to login to the user account. This happens for all accounts, so it might relate to sessions and https://github.com/openfoodfoundation/openfoodnetwork/issues/8090

## Expected Behavior

Users should be able to login.

## Actual Behaviour

Not possible to login, currently.

## Steps to Reproduce

1. Try logging in with valid credentials -> user remains on the home page

## Animated Gif/Screenshot

![Peek 2021-09-01 12-51.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/a9d4d7cb-60e8-4b29-b415-e2c4241406e3)

## Workaround

-

## Severity

Would be an S1 but not in production.

## Your Environment

* Version used: `build aaf45afbfe14d4ec10752b2049b5fc3da901be80`
* Browser name and version: Tested on Firefox and Chrome
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

Reverting #8090 or improving it.

**Comment by Matt-Yorkley** [comment]
@filipefurtad0 I just had a go and I can log in and out without problems. Any more details?

**Comment by filipefurtad0** [comment]
I can't login right now to staging-UK on desktop nor mobile... but this seems to happen only after staging this `build aaf45afbfe14d4ec10752b2049b5fc3da901be80`... or any PR (which we now know gets deployed merged with master).

**Comment by Matt-Yorkley** [comment]
Aha! Yeah, I see it now.

Should be fixed by: https://github.com/openfoodfoundation/openfoodnetwork/pull/8127
