### ISSUE TITLE
[AU-staging] Can't run the app

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8133]
## Description

There are issues running the app correctly under staging-AU, after staging recent master/PRs. This seems specific to this server, which some warnings on the console not seen on other servers.

## Expected Behavior

The app should run.

## Actual Behaviour

App does not run properly.

## Steps to Reproduce

1. Start a fresh session (no previous cookies) and visit staging.openfoodnetwork.org.au

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/131997188-1a704145-f9e0-4534-82b8-06ca7e6643b1.png)

## Your Environment

* Version used: v4.0.1
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

I have not used this server for quite a while. Maybe it just needs provisioning with some latest changes? Not sure.

**Comment by Matt-Yorkley** [comment]
I restarted the server and it's working now. Not a good sign though. The deployment log looks pretty weird, it says yarn took 15 minutes to install packages?! It should normally take ~10 seconds...

**Comment by filipefurtad0** [comment]
Yeah, the how deployment took way over half an hour... weird.

**Comment by Matt-Yorkley** [comment]
I miss-counted; yarn took _25 minutes_!

**Comment by filipefurtad0** [comment]
But thanks for restarting the server! :+1: It's up now and already providing answers regarding some tests on removing Stripe. This server goes way back so there are plenty of "legacy" orders which is good to test this transition...

I'll stage PR #8064 on it, and see how it works. (See you in 45 mins :-D)

**Comment by jibees** [comment]
> I miss-counted; yarn took _25 minutes_!

😮 😮 😮

**Comment by filipefurtad0** [comment]
Yep, something is fishy here, deploying PR #8064 failed:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/378

**Comment by Matt-Yorkley** [comment]
I just ran `yarn install` locally with master, and it took 14 seconds. I'm not sure why it would be any different in staging... I'll have to investigate.

**Comment by Matt-Yorkley** [comment]
Seems like it's only AU Staging that's on the fritz.

**Comment by filipefurtad0** [comment]
Closing, as discussed [here](https://github.com/openfoodfoundation/ofn-install/pull/780#issuecomment-927994160) :+1:
