### ISSUE TITLE
Payment taken if authorized after order cycle closes

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#8142]
## Description

If a customer authorizes a payment after an order cycle closes, the payment is processed on Stripe but not marked as paid in OFN

## Expected Behavior

The payment should be refunded and the order canceled

## Actual Behaviour

The payment is taken and the order remains in the `payment` state

## Steps to Reproduce

See also https://github.com/openfoodfoundation/openfoodnetwork/issues/7692#issuecomment-902857548

1. Place an order using a card that always requires SCA authorization
2. While on the SCA authorization page, in another window, close the order cycle
3. Authorize payment
4. Get redirected to OFN and then the shop page, get notified that the order cycle has closed

## Animated Gif/Screenshot

See https://github.com/openfoodfoundation/openfoodnetwork/issues/7692#issuecomment-902857548
## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by andrewpbrett** [comment]
This does have to do with payments, which would normally be an S2+, however, I don't think there's any reason to think that this has ever happened in production. @filipefurtad0 noticed that it was possible while testing another PR. Given that, I'm marking it an S3. Others feel free to weigh in/escalate though.

**Comment by filipefurtad0** [comment]
Thanks for opening this issue @andrewpbrett :+1: 

An additional note: payments are marked as `authorized` but not captured - so they are not really taken.

As of now, I have no evidence that the payment is captured after a week; At least in testing, these seem to be cancelled automatically - such `authorized` payments from previous tests got cancelled automatically (pic below taken from this [comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/8089#issuecomment-911938648)):

![image](https://user-images.githubusercontent.com/49817236/132201512-c26f5420-0fa5-4172-8b2c-7bc5b52fbbf3.png)

**Comment by andrewpbrett** [comment]
> I have no evidence that the payment is captured after a week

I agree, I think that was lost in translation. The Stripe docs indicate that any payment that's not captured after a week will be canceled.

**Comment by filipefurtad0** [comment]
The steps to reproduce now trigger the warning introduced here:
https://github.com/openfoodfoundation/openfoodnetwork/issues/6755

But the payment seems not to be created at all, and as such does not appear on Stripe dashboard as `uncaptured`, which is good :+1: 

I'd close this issue as the #7692 (comment) seems not to create a bug anymore.
