### ISSUE TITLE
Payment taken in Stripe but not marked complete in OFN

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#8143]
## Description

This was originally grouped with #7692; this issue is intended to be the placeholder for the third scenario in [this comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/7692#issuecomment-913027500).

## Expected Behavior

Payments that are completed in Stripe should be marked as complete in OFN

## Actual Behaviour

Payments are not marked complete

## Steps to Reproduce

TBD

First place to investigate are these payments, which are still in the `requires_authorization` state:
```
[["2021-05-16", 374727], ["2021-05-25", 377352], ["2021-05-26", 377522], ["2021-07-30", 393002], ["2021-07-31", 393154], ["2021-07-31", 393157], ["2021-08-02", 393404], ["2021-08-05", 394307], ["2021-08-07", 394667], ["2021-08-08", 394957], ["2021-08-09", 395301], ["2021-08-09", 395306], ["2021-08-19", 397252], ["2021-08-23", 397055], ["2021-08-25", 398568], ["2021-09-02", 400105]]
```
1.
2.
3.
4.

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by andrewpbrett** [comment]
```
394012 - load_order, 8/3
394307 - load_order, 8/5
393002 - require_distributor_chosen, 8/5
394667 - require_distributor_chosen, 8/7
394957 - require_distributor_chosen, 8/8 
395301 - require_distributor_chosen, 8/9
395306 - load_order, 8/9
397252 - require_distributor_chosen, 8/18
398568 - load_order 8/25
400105 - require_distributor_chosen, 9/2
```

Here's a lookup for what method redirected each of these payment ID's and the date that it happened. 

Two things to note: 

It does seem like this is happening the majority of the time when we try to return from SCA auth, i.e. there are a few other log entries where I see the redirect going to the order page (thus completing the payment) but most of the time it gets caught before that. 

There are only two instances in this list that happened since August 18. This seems inconsistent with @lin-d-hop reporting that this is currently happening multiple times per week in the UK. That would seem to indicate that there's some other pattern/scenario we need to be looking for, but we don't have enough information currently to narrow down what to look for.

**Comment by RachL** [comment]
@andrewpbrett a hub in FR reported 2 orders with the problem this week:

R563033613 and R221258050

the hub manager forgot to go check stripe to see if there was a payment problem, so she first manually created cash payment in OFN.

Then this morning she noticed the payment were not captured and capture them manually.

Here are the stripe screenshot, we can see the shopper has really confirmed the payment right away in both cases:


![image](https://user-images.githubusercontent.com/6525576/132484571-62377e50-be98-4ea5-b979-30c09a8d3156.png)

![image](https://user-images.githubusercontent.com/6525576/132484638-eb8180f5-15a9-4bf8-90ed-0dbd1a15edd0.png)

**Comment by andrewpbrett** [comment]
Thanks @RachL. For both of those orders, I see in the logs the line `require_distributor_chosen`, so these are hopefully the last couple payments where this happened before #8090 was deployed.

**Comment by lin-d-hop** [comment]
The multiple issues reported in the recent weeks were tracked down to actually have different causes that weren't our fault.

Perhaps this has been resolved now? :crossed_fingers:

**Comment by andrewpbrett** [comment]
Thanks for the update @lin-d-hop - I think this issue was intended as a placeholder for those payment issues. So now that we're saying we've tracked them down, and #8090 is merged, I think this is good to be closed and then if a new issue comes up, we can track it separately. 🎉

**Comment by filipefurtad0** [comment]
There is a sum of edge cases which consistently leads to this scenario:

![image](https://user-images.githubusercontent.com/49817236/133240358-f7143796-3e4d-40d2-b554-2de0b2006236.png)

It is closely related to https://github.com/openfoodfoundation/openfoodnetwork/issues/8185 and to https://github.com/openfoodfoundation/openfoodnetwork/issues/8142

i) If one changes the order by editing the cart on a parallel tab (#8185) and then tries to place the order on the initial tab (#8142) -> this will generate an uncaptured payment
ii) If one then returns to the second tab (which was used to edit the cart) and proceed to checkout -> it generates a user facing error and a captured payment on Stripe

![Peek 2021-09-14 11-15](https://user-images.githubusercontent.com/49817236/133240661-36797ca5-6545-4f22-a706-b56c70cbd7da.gif)

The order looks like this on the admin side:

![image](https://user-images.githubusercontent.com/49817236/133241717-042486df-79a4-437e-80d9-1f08b6fc3053.png)

I'm not sure how relevant this scenario is to production. I think it might depend on the time the authentication step takes. If users get impatient they might start clicking around, attempting to checkout. What do you think?

**Comment by RachL** [comment]
Team, I'm sorry I'm reopening this because CA reported a case which sounds like this issue. See conversation on slack: https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1631824275068900

@andrewpbrett do you have enough info to take a look?

**Comment by andrewpbrett** [comment]
Thanks @RachL. This should be its own issue, if I'm understanding that slack message correctly; in CA's case, the payments are marked as complete, but the order remains in the payment state. What we were seeing here was the payment not marked as complete.

**Comment by andrewpbrett** [comment]
Created #8224 and will fill in details
