### ISSUE TITLE
Update UK staging to 14.04 with latest deploy process

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#815]
- [x] Resolve issues with suburbs config
- [ ] Verify all aspects of installation work ok with ofn_deployment.
- [x] Check full installation works ok on 14.04.
- [ ] Migrate staging DNS to new server.

**Comment by lin-d-hop** [comment]
I would also like to explore separating the DB to a different server on production. This would help us to maintain data continuity through _this_ process and allow us to have a safer way to do major upgrades in the future without downtime to the users, as we could upgrade on different server, test, and switchover without risking data loss. @RohanM @mkllnk @oeoeaio would you share any quick thoughts on this?

**Comment by mkllnk** [comment]
I think that is a common good practice. Some of the CI scripts may need to be customised for that. They save and restore data on the staging server and these commands may assume a local, passwordless connection to the database (on the staging server).

But I'm not sure how you can have less downtime with a separate database server. And if you want to test a new release first, you still need a copy of the database, because migrations will change it. And while you are testing the copy, people may do updates (e.g. new orders) on the old database.

**Comment by lin-d-hop** [comment]
Thanks @mkllnk 
It would be more for system updates rather than code releases. It may be an overkill but this issue inspired the thinking... I don't like the idea of downtime while we update ubuntu if things go wrong in the process.

**Comment by pmackay** [comment]
@lin-d-hop I'm not quite understanding your thinking. Its more flexible but wouldnt it also imply two servers that need updating, when updates are needed?

**Comment by lin-d-hop** [comment]
My thinking is we update one server then point DNS to that one. If this switch takes any time at all, when users could be directed to either site, then we get inconsistent data. If the DB is on another server then we lose nothing in the process. Then we just ditch the other server until we need to do more system work.
It means that we can start to explore system updates more flexibly. I'm considering this for if we grow and we need to run multiple servers or more advanced DB infrastucture. My thinking is that taking this step early will make it easier to upgrade our systems in the future and result in less potential downtime once we have more users.
One big worry for me is downtime once we launch, and the impact this will have on the food businesses that are relying on this service.
Maybe it's an overkill... what do you think @pmackay?

**Comment by myriamboure** [comment]
@lin-d-hop can we close this one? seems like old one...

**Comment by sigmundpetersen** [comment]
I guess this is obsolete @Matt-Yorkley . At least move to `ofn-install` if discussion on server topology is to be kept open

**Comment by Matt-Yorkley** [comment]
Yep, this issue is old and obsolete. Closed!
