### ISSUE TITLE
ArgumentError in checkout#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#816]
## Exception in OpenFoodNetwork

**ArgumentError** in **checkout#update**
Missing required parameter: login

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/56b692b907141bdbda9c81db?event_id=56b694cb6f0bf91260cec5bd)
## Stacktrace

```
app/controllers/checkout_controller.rb:91 - advance_order_state
app/controllers/checkout_controller.rb:28 - update
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/56b692b907141bdbda9c81db?event_id=56b694cb6f0bf91260cec5bd)

**Comment by RachL** [comment]
@mkllnk did this issue happened again?
