### ISSUE TITLE
Sorting orders by "Total" not working correctly - response code 304 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8161]
## Description

Clicking the column header "Total" in the `/orders` page is not sorting the orders according to order total. An error 304 is seen in the console.

## Expected Behavior

Clicking the column header "Total" in the `/orders` page should sort orders according to order total. Request should return 200 response.

## Actual Behaviour

Clicking the column header "Total" in the `/orders` page is not sorting orders according to order total and is returning a 304 response.

## Steps to Reproduce

As an admin:
1. Visit `/admin/orders` page and open the browser console
2. Click "Total" several times (this should switch the error position up and down)
3. Notice how the ordering remains unchanged
4. Notice the response code 304 for the requests
5. Notice the "If-None-Match" response
6. De-select the "Show only complete orders option" and repeat -> the outcome should be the same

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/132679460-09111744-6e68-42e9-b99a-053fb35efd23.png)

## Workaround

Search for orders with a given total manually.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.1.0
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

I _think_ this was has worked at some point... Added the ```regression``` label.

**Comment by achauve** [comment]
Starting working on it
