### ISSUE TITLE
Release v4.1.1 Cassoulet

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#8162]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Draft new release]
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2913
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by filipefurtad0** [comment]
The release is good to go :tada: 

https://docs.google.com/document/d/1bB6E2XuHlpPRqC9Z1H5biaHWBwfP3XKDubmBgTU_uRs/edit#

Found an issue related to orders in which items go out of stock, for now [reported here](https://github.com/openfoodfoundation/openfoodnetwork/pull/8148#issuecomment-918009003), but opening an issue.
