### ISSUE TITLE
Migrated StripeConnect payment methods have empty "Account Owner"

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8169]
## Description

Follow-up from  #8064.
When killing stripe Connect, we were left with one missing bit, after the migration:  **Account owner** is left empty, which breaks payments, namely in Subscriptions.

## Expected Behavior

No StripeSCA payment methods should have `Account owner` empty

## Actual Behaviour

Some StripeSCA payment methods have `Account owner` left empty

## Steps to Reproduce

Find the payment methods which have no `Account owner` attributed -> I guess this should be possible through the console

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/132483213-0d2f489a-080b-407e-8a39-4e82772d2027.png)

## Severity

Breaks subscriptions and potentially shopfront in backoffice payments.

**Comment by lin-d-hop** [comment]
@filipefurtad0 Will this break existing subscriptions? I'm not clear on the impact and hence unsure if this should be an s2.

**Comment by apricot12** [comment]
> @filipefurtad0 Will this break existing subscriptions? I'm not clear on the impact and hence unsure if this should be an s2.

@lin-d-hop This can break existing subscriptions if there was any instance left still using StripeConnect for subscriptions. The workaround here will probably be to re-do the steps to add Stripe to your account.

**Comment by lin-d-hop** [comment]
That doesnt sound like a valid workaround.

If we deploy  #8064 before this is fixed then any instances that havent migrated to Stripe SCA will deploy the release and have Stripe break in BO and subs. That basically renders all of the work done in this PR completely pointless.

Luckily most instances have already transferred all stripe accounts to SCA.

**Comment by filipefurtad0** [comment]
I should have made more explicit in the issue that this is currently only in `master`, as v4.1.1 will not include Stripe connect removal. As such, I  totally agree it is a good idea to address this before release v4.1.2.

> so this will only be of impact if the hub hasn't already switched to SCA
Yes, that's it but again, best fixed before deploy.

**Comment by lin-d-hop** [comment]
Why merge and create a separate issue when the problem means the original work did not actually solve the original issue? Then create an S3 that actually is a blocker for the whole piece of work? Rather than just saying 'actually you didn't fix the issue'.
Guys, I'm sorry, your logic has totally broken me. 

But so long as you have it under control :shrug:

**Comment by filipefurtad0** [comment]
Yes, this one was not obvious... It seems that the branch in #8064 was causing conflicts, since it was a long lived branch - it was worked on an tested a few times.

So, to avoid the need to constantly resolve conflicts and since it was not on the upcoming release (so it would not break production) it seemed like the best to do, in this case: merge and address before next release.

I should have made this decision making process more clear on this issue @lin-d-hop @sigmundpetersen , sorry it caused confusion.

**Comment by lin-d-hop** [comment]
Hi @apricot12 and @filipefurtad0 
Reading this issue I'm not clear on what the next steps are here? Sorry if I'm being dim.

**Comment by filipefurtad0** [comment]
Hey @lin-d-hop ,
The latest tests had revealed some regressions [(see these and following testing notes)](https://github.com/openfoodfoundation/openfoodnetwork/pull/8255#issuecomment-936560856), so I think the approach will be to split this on into two PRs, as suggested [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/8255#issuecomment-966018074).
