### ISSUE TITLE
Tax Totals Report Available over API

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8187]
## Description

As an API user I would like to access the data on tax reports via the API. This will be the first of our reports available over the API.

API RQs need to allow the same search criteria as the reports search fields.
API RSs need to return the same data as the report when searching.

The goal is that this work leverages work already done by Matt. If there are specific params or fields that are much more complex to deliver over the API than in the UI let's ignore them for now and treat their addition as issues. 

The intention is that this is an XS or max S piece of work. Any bigger and we'll need to rethink.

## Acceptance Criteria & Tests

1. API can be queried via the API with the same set of criteria as the UI
2.  API responses return the same results and aligned format as the UI
3. The endpoint is available on the v0 namespace
4. The endpoint is documented in the v0 Swagger
5. We have example RQ/RS pairs available in the Swagger docs

**Comment by abdellani** [comment]
Hi @lin-d-hop 

Can you please share more details?
I don't see how v1 will be different from what we already have on v0.

**Comment by lin-d-hop** [comment]
@abdellani When this issue was created we didn't have the reports framework we currently do that enabled reports on the API automatically.
This issue can be ignored.
