### ISSUE TITLE
Enterprise Fee w Tax Report available over the API

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8188]
## Description

As an API user I would like to access the data on enterprise fee reports via the API. This will be the first of our reports available over the API.

API RQs need to allow the same search criteria as the reports search fields.
API RSs need to return the same data as the report when searching.

The goal is that this work leverages work already done by Matt. If there are specific params or fields that are much more complex to deliver over the API than in the UI let's ignore them for now and treat their addition as issues. 

The intention is that this is an XS or max S piece of work. Any bigger and we'll need to rethink.

## Acceptance Criteria & Tests

1. API can be queried via the API with the same set of criteria as the UI
2.  API responses return the same results and aligned format as the UI
3. The endpoint is available on the v1 namespace
4. The endpoint is documented in the v1 Swagger
5. We have example RQ/RS pairs available in the Swagger docs

**Comment by abdellani** [comment]
@lin-d-hop 

I think this can closed as we did we the tax report https://github.com/openfoodfoundation/openfoodnetwork/issues/8187
