### ISSUE TITLE
'contact us' button for shoppers to message the administrator

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#819]
This request is copied from old issue 318

Stroudco would like to have a 'contact us' button so that shoppers can send a message or email to the administrator?

**Comment by lin-d-hop** [comment]
Hi @NickWeir63 
At the top of the StroudCo shopfront there is a Contact tab that has all of the possible contacts for StroudCo. 
Will this suffice for this functionality?

In all honesty I think the current implementation is the best option. We aren't going to implement a messaging system like in the StroudCo software as this style of system is outdated, prone to error and not as good as trusty old email.

**Comment by NickWeir63** [comment]
yes sorry - closing this now
