### ISSUE TITLE
grumpy cat if PaylPal not set up

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#820]
I get grumpy cat if i try to pay for a Stroudco order with paypal.  However paypal works fine from the Ferment Bristol shop.  
this is probably happening because all the Paypal details are blank in the stroudco payment method.  We will get the stroudco Paypal details set up but I think it would be good if we could have an error message saying something like "there is a problem with the Paypal settings - please contact your food hub administrator using the contact button on the shopfront"

**Comment by pmackay** [comment]
Surely if the hub is not configured with Paypal info, it shouldnt be offered at all as a payment option?

**Comment by NickWeir63** [comment]
yes i just thought that if the Paypal options are wrong it would be better to get an error message than a grumpy cat?

**Comment by lin-d-hop** [comment]
Paypal error messages are quite clear now. We still have UX issues but this bug doesn't describe them.
