### ISSUE TITLE
Creation of 2 variants with same name & quantity allowed, which causes problems in the reports

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#822]
A hub manage in France has uploaded products with this parameters:
![error](https://cloud.githubusercontent.com/assets/8135376/12918342/f59b73ce-cf3e-11e5-8b0b-542bc2b94280.png)

It's not relly obvious how to fill in the different field for setting up products... so he tried to fill in the fields so that it looks right on the platform.
But as you see, the name and quantity of each variant is the same, only the "display as" field has been changed so that it looks good.

The problem is that then, in the report, we dont see the different variants, they are all summed up in just one line (which is a problem as it was two different variants in fact).

I guess the problem is that the field "display as" is not a "database field" but just how we want the product to appear.
And I guess as the two variants had the same name and quantity, they are just aggregated in the reports... am I right?

Quick fix: shouldn't there be a warning box if you create 2 variants with same name and quantity, saying it's not possible? The system should refuse if you put another variant with the same infos, or at least open a warning and say that the orders for the products will aggregate all variants?
Does this represent a lot of work?

Ping @blancnic and @marito59

**Comment by myriamboure** [comment]
Ok, we had the issue again on a real case with a hub who was proposing two types of papaya and using the "display as" field to tell the differences to the customer:
![screenshot from 2017-03-29 11-47-19](https://cloud.githubusercontent.com/assets/8135376/24448786/7eb56670-1475-11e7-876a-3230d17a1254.png)

I guess the issue is linked to the fact that the user uses the "display as" field to differentiate the two variants, but as they have the same name and quantity, the system consider them as being the same.

The workaround of course is to set up a different name, I'm going to do that with that user, but it would be great to have an error control if you have two variants with a "display as" field which is different, there should be a pop-on saying "the variant has same name and quantity as another variant, please choose another name or change the quantity"

**Comment by myriamboure** [comment]
@ltrls @Em-AK is it a big job or quick fix in your opinion? I can ask the user if he is ready to pay for it, but I need an estimation of the cost... would you be able to say or should we ask the Aus tech lead?

**Comment by Matt-Yorkley** [comment]
Would an easier option be to show the "display as" field in the reports and show each variant?

**Comment by myriamboure** [comment]
Would be another possibility @Matt-Yorkley but I guess "forcing" to use another variant name might make searches easier afterward, in reports, and all, no? Else it means adding the "display as" column everywhere, and also for the CSV import work considering also the "display as" field to see if same variant or not... It seems easier to me to force using different variant names, but I'm not on the tech side ;-)

**Comment by Matt-Yorkley** [comment]
@myriamboure I can see that it might make things easier, but I'm not sure it would be technically feasible to make variant display names unique at the moment.

**Comment by myriamboure** [comment]
I add "important" as we had our biggest user in France who had an issue with this and it caused some serious trouble for one OC... I think we should solve that sooner rather than later!

**Comment by RachL** [comment]
We haven't had occurrences of this again and I suspect Network will change a lot product creation. I'm closing.
