### ISSUE TITLE
Remove "Ask" checkbox throughout the app

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8223]
## Description

Related to #925 and to https://community.openfoodnetwork.org/t/ask-checkbox/995.

Some pages like:
- bulk order management page - `admin/orders/bulk_management`
- customers page `admin/customers`
(- any other?)

display an "Ask" checkbox, whose function seems to confuse customers. 

Checking it and saving changes does not retain this choice - reloading the page removes the check; Also, it's functionality seems broken.

To summarize: we should remove it from the UI.

## Expected Behavior

- The "Ask" checkbox is not displayed in any of the pages. These include BOM and the customers page.  (anywhere else we could be missing?)
- The user always needs to confirm the deletion of items from these pages (current behavior)

## Actual Behaviour

The "Ask" checkbox is displayed on BOM and customers page; its function is broken.

## Steps to Reproduce

1. Visit BOM and/or the customers page.
2. Check or uncheck the box - click Update - and try to notice any difference in behavior when deleting items from these pages.
3. Reload the page -> notice how your changes on did not take effect.

## Animated Gif/Screenshot

![Peek 2021-09-23 16-06](https://user-images.githubusercontent.com/49817236/134533618-5c5eecc1-6ec4-4efe-a9f5-42b50d289274.gif)
![Peek 2021-09-23 15-59](https://user-images.githubusercontent.com/49817236/134533623-60eae31f-b981-4857-9f62-fcf73c7c01f2.gif)

## Workaround

Just ignore it and live with the constant confirmations

## Severity

bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: v4.1.2
* Browser name and version: Firefox 92
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by sinansonmez** [comment]
Dear @filipefurtad0 and @RachL, I can search the codebase and can remove the ask checkbox. Could you please assign this to me?
