### ISSUE TITLE
Listing Orders UX Improvement: Payment state of cancelled cash/EFFs order

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#8229]
## Description

Customer opts to pay for an order by cash/EFFs payment method. 
This order is then cancelled- either by the food enterprise or the customer- prior to payment being captured.
Listing Orders table shows the payment state of the order as 'amber= balance due' (see image below) and 'capture payment' icon appears to the right of the order.
If order is canceled then no money is due. Payment state should read 'None' and 'capture payment' icon should not be present.

## Expected Behavior

If order is canceled then no money is due. Payment state should read 'None' and 'capture payment' icon should not be present.

## Actual Behaviour

An order (paid for by cash or EFFs) is cancelled- either by the food enterprise or the customer- prior to payment being captured.
Listing Orders table shows the payment state of the order as 'amber= balance due' (see image below) and 'capture payment' icon appears to the right of the order.

## Steps to Reproduce

1. place dummy order and opt to pay by cash or other non-integrated payment method
2. cancel order
3. view Listing Orders table
4.

## Animated Gif/Screenshot

![cancelled_cashorder](https://user-images.githubusercontent.com/45104035/79746249-91a5f580-8301-11ea-85fa-09809d87ff2b.jpg)

## Severity

bug -s5
Paper cut 
## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by anansilva** [comment]
Hi, can I be assigned to this one? Thanks!

**Comment by anansilva** [comment]
Actually, had a look at it and seems like [PR 8863](https://github.com/openfoodfoundation/openfoodnetwork/pull/8863) solved this issue. Can someone confirm?

**Comment by RachL** [comment]
Hi @anansilva thanks for digging out that PR! I think that it partially solves the issue only.

Indeed in the list of order, the payment is shown as cancelled:


![Image](https://user-images.githubusercontent.com/6525576/216335314-1f0679b8-3a9e-47f9-ba91-7354d489cd41.png)


However the admin is still able to capture the payment: the button should disappear.

Also if you go and edit the order, the payment status remains "balance due" with the ability to capture the payment. Both should be changed. 



![Image](https://user-images.githubusercontent.com/6525576/216335647-3dad9e9b-08ad-4756-a347-164f817a1e76.png)


Are you happy to work on improving these two aspects?

**Comment by RachL** [comment]
Also the shipping status can't be "pending" anymore, but we can open a new issue for that :+1:

**Comment by anansilva** [comment]
Got it, thanks for the details @RachL, happy to take this one!
