### ISSUE TITLE
Inform users they need to unblock 3rd party browser cookies in Firefox to make /map work

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#8230]
## Description
Currently if user has disabled 3rd party cookies, for example in Firefox:
![image](https://user-images.githubusercontent.com/1640378/79241744-5fad1300-7e6b-11ea-8afb-568dbcd4210a.png)

When the user goes to /map the map wont show correctly
![image](https://user-images.githubusercontent.com/1640378/79242699-8c155f00-7e6c-11ea-8e2e-a14d2b0694d3.png)

And bugsnagJS errors will be created like:
https://app.bugsnag.com/yaycode/open-food-network-js-katuma/errors/5e8c6364df4e9c0017b280c6?filters[event.since][0]=30d&filters[error.status][0]=open
![image](https://user-images.githubusercontent.com/1640378/79242437-3fca1f00-7e6c-11ea-94a0-313eec621213.png)

But the user is not informed about this error in any way. So for the user, the OFN map is broken.

We could make a very simple change in OFN to detect this problem and show an error message to the user indicating they should enable third-party cookies if they want to see the OFN map.

All occurrences of this error in bugsnagJS (121 in France) are on Firefox, so this is a Firefox specific issue. The map works correctly in chrome even if 3rd party cookies are disabled.

## Acceptance Criteria & Tests
Users who have disabled 3rd party cookies are warned when they visit /map that they can enable 3rd party cookies to see the map.

**Comment by MichaelDimmitt** [comment]
What website currently does this?
Just shoot to emulate that behavior. cc @murjax

**Comment by murjax** [comment]
The TypeError mentioned above is from the search bar and is a downstream effect of the map not rendering. It's reproducible in local development by turning off the network and loading the map page.

Although users would unlikely reach this error in staging or prod via network failure, it does identify an area we can respond and tell the user 3rd party cookie settings may need to be checked. Opening a PR shortly with a potential solution for further discussion.
