### ISSUE TITLE
Payment State of Subscription Order canceled Before Stripe payment taken

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#8232]
## Description

System automatically generates a subscription order for a customer who will pay by Stripe.  Hub settings allow orders to be cancelled or changed while an order cycle is open.  Payment for subscription order is thus not taken from customer account straight away.
Order is cancelled by either customer or hub before order cycle closes.
Payment state of order remains as 'amber= balance due'.
No payment is required as no goods purchased.

## Expected Behavior

Customer or hub cancels a subscription order (paid for by Stripe) while an order cycle is open and before payment has been automatically taken from customer's account.
No payment is due for the order.
Payment state of order should read 'void' rather than balance due.

## Actual Behaviour

System automatically generates a subscription order for a customer who will pay by Stripe.  Hub settings allow orders to be cancelled or changed while an order cycle is open.  Payment for subscription order is thus not taken from customer account straight away.
Order is cancelled by either customer or hub before order cycle closes.
Payment state of order remains as 'amber= balance due'.

Similar to issue #8229 but in this case the capture payment icon is not visible.

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![cancelled_suborder](https://user-images.githubusercontent.com/45104035/79747118-0c234500-8303-11ea-8994-95753133c42a.jpg)

## Severity

S5
Potential paper cut

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by georgethoppil** [comment]
I can take a look at this

**Comment by georgethoppil** [comment]
@andrewpbrett @lbwright22 I was able to reproduce this issue locally. In terms of the payment state of the order, are we looking to add an additional state of 'none'? I don't believe this is available for us at the moment. The states that I see are: 

```
        payment_states:
          balance_due: "balance due"
          completed: "completed"
          checkout: "checkout"
          credit_owed: "credit owed"
          failed: "failed"
          paid: "paid"
          pending: "pending"
          requires_authorization: "authorization required"
          processing: "processing"
          void: "void"
          invalid: "invalid" 
```
