### ISSUE TITLE
Angular translations do not fallback to en?

### ISSUE THREAD

**Issue by stveep** [openfoodfoundation/openfoodnetwork#827]
I put some translated strings using the Angular t filter like so:

```{haml}
        %th.order1{"bo-text" => "'transaction' | t"}
        %th.order2{"bo-text" => "'transaction_date' | t"}
        %th.order3{"bo-text" => "'payment_state' | t"}
        %th.order4{"bo-text" => "'shipping_state' | t"}
        %th.order5.text-right{"bo-text" => "'value' | t"}
```
en.yml contains all the translations and these work fine in the default locale. When locale is en-GB (as it presumably is on uk staging), some of these don't fall back to en as they should.

en.yml:
```{yaml} 
...
  balance: "Balance"
  transaction: "Transaction"
  transaction_date: "Date" #Transaction is only in key to avoid conflict with :date
  payment_state: "Payment status"
  shipping_state: "Shipping status"
  value: "Value"
...
```
![stagingi18n](https://cloud.githubusercontent.com/assets/1314715/13128134/910e2a3a-d5cb-11e5-9a5d-b76cd344d666.png)

(Minor point: payment state is not actually translated correctly (state not status), assume this key is also defined somewhere in Spree?)

The same thing happens when I set en-GB as the locale in my local environment. If I do the translation in rails, with (e.g.) the syntax below, it translates correctly. Do we need to set up a fallback for translations in Angular? I don't really understand how the translation is configured in Angular. I could just do it in Rails but was under the impression that the preference is to translate in Angular rather than in Rails to allow for possible dynamic change of languages?

```{haml}
        %th.order2{"bo-text" => "'transaction_date' | t"}
        %th.order3
          = t :transaction_date
```
`=> transaction_date Date`

**Comment by daniellemoorhead** [comment]
@elf-pavlik, @blancnic, @pmackay, @mkllnk - able to help @stveep out with this? It's impacting on #616 and we'd like to get it out in this week's release if possible :)

**Comment by mkllnk** [comment]
We don't have a locale fallback in javascript yet. That is something we still need to code. If you can do it in ruby, that's great. Dynamic changing of languages should be easy with ruby translations.

But in general, we need to keep en-GB up-to-date, at least for strings that are translated in javascript.

**Comment by stveep** [comment]
OK thanks!
