### ISSUE TITLE
ActiveRecord::StatementInvalid in spree/orders#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#829]
## Error in OpenFoodNetwork

**ActiveRecord::StatementInvalid** in **spree/orders#update**
PG::Error: ERROR:  deadlock detected
DETAIL:  Process 19431 waits for ShareLock on transaction 77916022; blocked by process 19426.
Process 19426 waits for ShareLock on transaction 77916020; blocked by process 19431.
HINT:  See server log for query details.
: DELETE FROM "spree_option_values_line_items" WHERE "spree_option_values_line_items"."line_item_id" = 618994 AND "spree_option_values_line_items"."option_value_id" IN (1342)

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f78cc947e6d27c286869f3?event_id=56c506b3247fb7dc6237ee1f)
## Stacktrace

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/54f78cc947e6d27c286869f3?event_id=56c506b3247fb7dc6237ee1f)

**Comment by RachL** [comment]
@mkllnk I have the feeling we could close this one and reopen if we have a more recent occurence. What do you think?
