### ISSUE TITLE
Impossible to complete some orders paid through Stripe

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#8296]
## Description

Two shops 2210 and 2120 can't validate orders when payments has been failed

For exemple, the R713605770 order has two payment, one successful payment and one failed payment

<img width="622" alt="Capture d’écran 2021-10-06 à 16 10 03" src="https://user-images.githubusercontent.com/67476305/136332996-0f8463d9-328f-4b1f-abfe-52883235aa9e.png">

(we do not understand why there were two payments while the first one has been successfull)

The hub, from OFN, can't delete the second payment from order menu. So can't complete the order.

<img width="752" alt="Capture d’écran 2021-10-07 à 08 53 00" src="https://user-images.githubusercontent.com/67476305/136334126-d9d792eb-afa0-4fdf-925d-6590a3abc019.png">

There is few payment with failed payment (maybe a clue) with differents behavior which prevents us from validating orders : 

- R361886228 

<img width="1361" alt="Capture d’écran 2021-10-07 à 09 07 48" src="https://user-images.githubusercontent.com/67476305/136336784-6bc8d375-f0c4-484a-850d-ff42aa82c9fe.png">

Failed payment seems to be canceled but the order can not be completed

- R101116778

Impossible to access to "payments" bouton 

- R372070856

<img width="1404" alt="Capture d’écran 2021-10-07 à 09 06 42" src="https://user-images.githubusercontent.com/67476305/136337056-9bdb2cd8-f7b2-419c-a89b-dd453a8f56b7.png">

Impossible to complete order while payment is ok (no failed payment in this case)

## Steps to Reproduce

1. Orders menu 
2. Edit order
3. Payment
4. Select the cross for the failed payment

## Workaround
I can't find one, does someone have an idea to allow user to complete clients orders ? 

## Severity
A shop is blocked

**Comment by Cecilia-Hn** [comment]
Here is the summary
<img width="692" alt="Capture d’écran 2021-10-07 à 12 53 24" src="https://user-images.githubusercontent.com/67476305/136370878-e11f33b0-681a-4fea-a4e1-17754f6bed02.png">

**Comment by Cecilia-Hn** [comment]
Hi,
Thanks @filipefurtad0 

I've checked the shipping methods for both hubs (2120 and 2210), the display is "both checkout and back office"

We've got new cases


<img width="227" alt="Capture d’écran 2021-10-12 à 10 37 02" src="https://user-images.githubusercontent.com/67476305/136922021-1ed37606-6830-4dcf-9bf1-3baa30ba5f2d.png">

And for exemple, for the R460556583, Stripe seems to refuse the first payment that have been successfull and some payment are tiggered even the day after

![stripe(1)](https://user-images.githubusercontent.com/67476305/136922213-fa24a9ca-d158-4ad7-a108-49c2aa65198d.jpg)


The user struggle with his hub payments, have we got a clue for a workaround or a reason why this is happening ? 
Thanks a lot

**Comment by filipefurtad0** [comment]
> I've checked the shipping methods for both hubs (2120 and 2210), the display is "both checkout and back office"

Great, thanks for that info @Cecilia-Hn  - that rules out #8219.

So, I think the reason all these orders have a shipping address in Malaga is because that specific hub / distributor / shop :
- has its address in Malaga / Spain
- has only one shipping method set: it is a `pick-up shipping method`, so this explains why all orders have this `shipping-address`
(pickup methods automatically set up the hub's address as shipping address)

Looking at the address set for distributor `2210` -> https://coopcircuits.fr/fruits-bio-andalousie-direct-29-morlaix/shop#/contact

```
   id   | firstname | lastname |   address1    | address2 | city  | zipcode | phone  | state_name | alternative_phone | state_id | country_id |         created_at         |         updated_at         | company |  latitude  | longitude  
--------+-----------+----------+---------------+----------+-------+---------+--------+------------+-------------------+----------+------------+----------------------------+----------------------------+---------+------------+------------
 877135 | unused    | unused   | Rue du Dossen | Penzé    | Taulé | 29670   | unused |            |                   |      458 |        175 | 2021-10-09 10:10:49.085141 | 2021-10-09 10:10:49.085141 |         | 48.5994807 | -3.9342043
(1 row)
```

We can see that it has:
`| state_id | country_id | `respectively `|      458 |        175 | ` ->  which is Spain / Malaga

Could this be a mix up in setting the address?

![image](https://user-images.githubusercontent.com/49817236/136947515-1851e65c-004c-4b8a-9b6f-194e7cb19453.png)

So maybe the workaround would be to select the correct country and state in the enterprise settings (29670 Taulé, France)?

**Comment by Cecilia-Hn** [comment]
Hi @filipefurtad0 and @RachL 
We've got 2 new cases for hub 2468 

These two following payments are captured in Stripe but in red statu in OFN

R862447072
<img width="1369" alt="Capture d’écran 2021-11-03 à 13 42 32" src="https://user-images.githubusercontent.com/67476305/140062380-4aff03f3-357b-4a85-aa61-39841b600459.png">
<img width="1096" alt="Capture d’écran 2021-11-03 à 13 42 44" src="https://user-images.githubusercontent.com/67476305/140062387-c07fea47-628e-4cfe-bc55-f8d925517333.png"

Same behavior for R157315143 but for this one the user could change the OFN statu

**Comment by Matt-Yorkley** [comment]
I'll start writing some specs around this, and see what I can find. Did you manage to replicate it in Staging @filipefurtad0 ?

- Hub's shipping address is outside of the instance's default zone
- Customer is in a different zone
- Hub only has pickup shipping methods

Is that it?
