### ISSUE TITLE
 Community Forum for OFN (Discourse)

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#831]
More detail in http://community.openfoodnetwork.org/t/community-forum-for-ofn/450

**Comment by sstead** [comment]
Seems all good. I just tested that users were logged in correctly, and were given admin permission if SuperAdmin in OFN. That was working. If the user's email is not verified, they don't get loged into discourse. And if I'm a not an enterprise user, I see the Notices link, but am not logged in. Making comments is working in discourse once logged in. And the OFN checkout is working.
