### ISSUE TITLE
Verify emails of users, not enterprises

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#833]
Currently, only enterprise emails are validated with a confirmation email. This can lead to enterprise owners with invalid email addresses in the system.

It would be much clearer to verify email addresses on user level as discussed:
- http://community.openfoodnetwork.org/t/confirmation-emails-registration-flow/237
- http://community.openfoodnetwork.org/t/community-forum-for-ofn/450/18

**Comment by daniellemoorhead** [comment]
@lin-d-hop and @stveep maybe this is something worthy of Levent's attention. It's a pretty important thing to have but it's never got to the top of the list of priorities. Designing out how it would work for new users and then for existing unverified users, and then implementing it, shouldn't be too much of a stretch....maybe?

PS. Didn't like Levent to this because not sure of his userID :)

**Comment by NickWeir63** [comment]
Adding Levent https://github.com/lebreeze

**Comment by NickWeir63** [comment]
@levent

**Comment by myriamboure** [comment]
> Currently, only enterprise emails are validated with a confirmation email. This can lead to enterprise owners with invalid email addresses in the system.
@mkllnk I don't think this is true anymore as the owner email can only be chosen among the verified email list. And you cannot add a manager if the email has not been verified. I suggest we close this issue, I'm referencing all the issues in a broader spec document on the user verifications / workflow.

**Comment by daniellemoorhead** [comment]
@sstead are you able to respond to @myriamboure's comment above, is this the case?

**Comment by sstead** [comment]
Yes, I agree with Myriam, enterprise owners must be validated. Shoppers are not validated yet.

**Comment by mkllnk** [comment]
@myriamboure It has been a long time. I can't remember what the loophole was and if that has changed. But we still want to verify the email addresses of customers, right? Maybe we should change the motivation for this change, but we still want to do this.

**Comment by daniellemoorhead** [comment]
Closing this issue as it has been superseded by epic #946 and all accompanying issues within it. Yay!
