### ISSUE TITLE
On staging2 when I load the backend in small screen I lose icons

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#835]
![image](https://cloud.githubusercontent.com/assets/10843056/13275844/7b8d564e-db0d-11e5-928b-ad4116ad7318.png)

When i make the screen larger this doesn't happen. Not happening in production currently, but might get pushed.

**Comment by myriamboure** [comment]
@sstead is this still an issue? And does this issue need to be solved given that it only concerns a staging server?

**Comment by daniellemoorhead** [comment]
Closing this issue for now, backend not optimised for small screen. Solution: use a bigger screen 😈
