### ISSUE TITLE
Option to not ask for the addresses of customers 

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#837]
From: Francis Priestland [mailto:fp26@st-andrews.ac.uk] 
Sent: 24 February 2016 16:35
To: nick@openfoodnetwork.org.uk
Subject: No Herefordshire

Is there a way to not ask for the addresses of our customers since we are using PayPal for payment anyway?

**Comment by myriamboure** [comment]
@NickWeir63 can we close for this one ? https://github.com/openfoodfoundation/openfoodnetwork/issues/928 We had already started to work on it so probably better to keep the issue where details are provided. I let you close it if you agree.

**Comment by lin-d-hop** [comment]
Closing as duplicate
#gitcull2017
