### ISSUE TITLE
Map search bar on mobile goes off screen in portrait aspect

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#840]
![map-searchbar-bug](https://cloud.githubusercontent.com/assets/10949052/13340058/6e780948-dc81-11e5-8718-672b0cae5911.png)

The search bar goes off screen on landscape mobile aspect. Can we maybe move those 'Map' and 'satellite' buttons to the bottom left of the screen so that they don't take up space, and then have the search bar width shrink to fit the screen width?

Estimate = timeboxed to 1 hour only.

**Comment by myriamboure** [comment]
This seems to be solved, retested on Iphone (pretty small screen, the 6E)
![img_8637](https://user-images.githubusercontent.com/8135376/36926426-11ec82fe-1e78-11e8-9650-de0fbca2a043.PNG)
If any other problem on other devices maybe please reopen.
