### ISSUE TITLE
Map marker key on the OFN map page

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#841]
It's not obvious on the map what each of the map markers mean. There are tractors and pointers and white and green and red markers, but it's not obvious to the user what these colours and icons symbolise without a key.

The key should sit under the location search bar and be expando-collapso (so that all you see initially is "Map Key" and when you click/touch on that it expands to show the list of the different types of markers (though @mkllnk, I'll leave it to you to determine the final solution).

This is important given that we are going to be directing users to this page from the call to action button on the homepage, so more people will be directly accessing it at a point where they don't know a whole lot about the OFN. Given them context of what is on the map will help them to determine what is relevant to them, and then help convert them to becoming customers of OFN shops. This is only the first of many steps in improving the experience for customers, but it's a good start.

Estimate = 1 day.

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/discovery/1177
