### ISSUE TITLE
Main nav bar improvements

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#842]
![mock up - main nav](https://cloud.githubusercontent.com/assets/10949052/13341434/d21c7f6e-dc8c-11e5-893e-a3b0137f02c9.png)

**1. Remove 'About' from the top level navigation on desktop view.**
It's common practice on websites for the link to about and the team to be in the footer rather than as prominent as the other menu items. Given the lack of space we have in the bar on the desktop view it makes sense to move this to a lower level position, ie. just the footer.

But, we need to make sure that the link to about shows in the mobile menu. Can we keep it in the hamburger menu for small screen, but remove it for desktop?

**2. Add menu icons to desktop top level navigation**
See mock up above. These icons show in the small screen hamburger menu, and are so useful for the user when it comes to understanding what the icons we use actually mean. This way, when they see a tractor they'll always connect that to being a representation for a producer, etc etc.

**3. Add a call to action somewhere in the global navigation element for enterprises to register**
Link should read something like "Get on the OFN". We need to figure out how to do this with the constraint of all the other things that display in that global nav bar: logo, main menu links, shopping cart, shop name, settings icon, and now the new "notices" link.

**Comment by daniellemoorhead** [comment]
@serenityhill @mkllnk @sstead let's chat about this at the sprint planning session to figure out final scope for the work. I've added all the possibilities here, we just need to determine exactly what we'll do.

**Comment by mkllnk** [comment]
> we need to make sure that the link to about shows in the mobile menu. Can we keep it in the hamburger menu for small screen, but remove it for desktop?

Yes, no problem. The two menus are in two separate files and don't depend on each other.

**Comment by lin-d-hop** [comment]
@daniellemoorhead Can this be closed and moved to wishlist?

**Comment by daniellemoorhead** [comment]
It can just be closed. So long ago :-)

An overhaul of the entire UI will incorporate this.
