### ISSUE TITLE
Investigate Github for deployments

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8422]
### What we should change and why (this is tech debt)

We should investigate replacing Semaphore with Github for deployments.

Some documentation:
https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions

### Context

This came [up here](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1635337061013100?thread_ts=1635332407.012200&cid=C02TZ6X00), but I believe it has been discussed previously.

### Impact and timeline

This would remove dependency from Semaphore.

~~Not a priority action, i.e., **not included in Horizon 1**~~
Edit: we've been having several issues with deployment with semaphore, worth prioritizing!

**Comment by filipefurtad0** [comment]
Found a good ref here, I think the approach could be similar for GH:
https://github.com/openfoodfoundation/ofn-install/pull/299

**Comment by filipefurtad0** [comment]
I've unassigned myself for now, hope to be able to progress on it at a later state. Moving back to the tech-debt prioritized column.

**Comment by filipefurtad0** [comment]
We have been experiencing some issues with Semaphore, today again:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/8836ef24-5962-4a55-992b-62258ec7049e)

The workaround is deploying manually to the staging server, like so:
- on the main repo, pull the branch to be tested
- pull the latest master from ofn-secrets
- pull the latest master from ofn-install; on ofn install, run (example):
`ansible-playbook playbooks/deploy.yml --limit uk-staging -e "github_key=jibees:10561-allow-user-to-create-custom-tab-in-shop-navigation" 
`

**Comment by dacook** [comment]
We now have a deadline:

> :warning: **Semaphore Classic will be deprecated on September 30th.**
> We encourage you to migrate your projects to [Semaphore 2](https://semaphoreci.com/login). If you wish to retain your current pricing plan or require technical assistance, please send us a message at [support@semaphoreci.com](mailto:support@semaphoreci.com).
> Learn more about the Classic shutdown [here](https://semaphoreci.com/blog/semaphore-classic-deprecation).

**Comment by filipefurtad0** [comment]
Hum, seems some branches were deployed already:
https://github.com/openfoodfoundation/openfoodnetwork/deployments/activity_log

So I guess we have a good idea how this could work...

I was thinking of:
- creating an ssh key pair
- adding it to our repo secrets
- then create a workflow to run an Ansible script

I'm not sure all this is necessary, seeing that we have a [OFN-deployments Bot](https://github.com/ofn-deployments) :robot:  
Any comments on the best way to proceed?

**Comment by Matt-Yorkley** [comment]
Alright, I'm taking a little look at this. The options for triggering a workflow are a bit weird, but I think one of them we could go for is label events. I'll have to look at how permissions work actually to see how we can limit that, but basically you can set it up so that adding a `uk-staging` label to a PR will trigger the deployment to uk staging.

**Comment by RachL** [comment]
@filipefurtad0 do we still need this issue? and especially in dev ready?

**Comment by filipefurtad0** [comment]
Ah, no, we don't - @Matt-Yorkley has implemented this already. Closing :+1:
