### ISSUE TITLE
EU cookie compliance

### ISSUE THREAD

**Issue by stveep** [openfoodfoundation/openfoodnetwork#843]
I think instances of OFN in the EU (which includes the UK at least for a few more months...) will need some kind of irritating popup for the first site visit to opt in to cookie storage, like every other EU website does:

https://en.wikipedia.org/wiki/Directive_on_Privacy_and_Electronic_Communications#Cookies

This could replace or add in to the "Start here" drop-down banner? (by the way, personally I don't like this drop-down as it loads last and moves all the rest of the site content, leading to clicking in the wrong place)

Maybe related to or could be combined with work in https://github.com/openfoodfoundation/openfoodnetwork/issues/842 @daniellemoorhead

**Comment by daniellemoorhead** [comment]
Hiya @stveep, this isn't something that is needed in Australia, but we'd be happy to include it in the backlog of work that we do for the uk. 

Let's chat about it tonight at the skype session with @NickWeir63, @lin-d-hop, @pmackay.

**Comment by pmackay** [comment]
I'd favour a banner at the bottom of the page? Less obtrusive?

Worth checking https://github.com/infinum/cookies_eu.

**Comment by OliverUK** [comment]
I remember looking at this a couple of years ago and in the UK at least, being typically light touch, the relevant authority made it clear that there would be no punishment of any sort if a website did not have this. I imagine if they directly instructed you and you ignored them, it may be different. But until then...

**Comment by pmackay** [comment]
@stveep @lin-d-hop reckon we could just leave it and add it if asked? ;)

**Comment by stveep** [comment]
Fine by me, guess it's Lynne that goes to jail ;)

**Comment by pmackay** [comment]
I assume there would be a warning before she gets clapped in irons ;-)

**Comment by lin-d-hop** [comment]
In my opinion if the enforcing organisation have taken the notice off their website we have nowt to worry about. 
@myriamboure what are your thoughts?
I'll put this is UKBacklog for now... who knows, we might not even have to worry about EU directives in a few months time... not that I would advocate for that :-)

**Comment by myriamboure** [comment]
For my information, why do we have cookies for in the OFN? What are we tracing?

@blancnic any idea on the legal point? I found this for France (https://www.cnil.fr/fr/site-web-cookies-et-autres-traceurs) but I don't think that is really appied... it sounds soooooo heavy! I don't think we should consider that as a priority given that we don't use any data for advertisment, or we don't trace anything for commercial purpose... I would vote to wait until we are ask to change something/get a warning... Agree Nicolas?

**Comment by myriamboure** [comment]
To add on, here is an example of what we could do to tell people that there are cookies, so use the top banner for that seems pretty smart @lin-d-hop :-)
![cookies](https://cloud.githubusercontent.com/assets/8135376/14188146/e288c2a8-f786-11e5-94ea-00a9cf23b4fa.png)

**Comment by myriamboure** [comment]
I think this is getting pretty critical. Just talk to a very activist open source lawyer and told be we shouldn't play too much on this one. We also need that for sure in GDPR. Icebox item is here https://community.openfoodnetwork.org/t/users-know-clearly-which-cookies-are-used-and-can-refuse-them/1252 I suggest we prioritize for next quarter.

**Comment by enricostano** [comment]
Keep in mind that the tricky part here is that diffent instances may be using different external services.

**Comment by daniellemoorhead** [comment]
And also keep in mind that it's not a requirement globally, so we may need to think about being able to turn this function on/off as a super admin.

**Comment by myriamboure** [comment]
Closing this one as being addressed in the epic https://github.com/openfoodfoundation/openfoodnetwork/issues/2242
