### ISSUE TITLE
Use openstreetmap instead of google map.

### ISSUE THREAD

**Issue by sciunto** [openfoodfoundation/openfoodnetwork#844]
Hi,

First, I'd like to say that your project is awesome. Congrats for the hard work.

I think it makes sense for this project to use openstreetmap (OSM) instead of googlemap. OSM shares similar principles as OFN: users are also producers of content, it's made by locals and shared with everybody. :)

Thanks!

**Comment by myriamboure** [comment]
Hi @sciunto !
Thank you for your message :-)
A discussion has been open already on the topic here: http://community.openfoodnetwork.org/t/open-street-map-vs-google-maps/492

We are aware that it would be more consistent, we just need someone who can dedicate time to work on it, and I'm not sure when that will be possible as there are soooo many important things to fix/develop... But this is in the wishlist :-)

Cheers!

**Comment by daniellemoorhead** [comment]
Hey @bingxie perhaps a good learning opportunity for you is to change the tile server we use with Google maps to be the OSM tile server and then we can see what it looks like. You can read more about this here: http://community.openfoodnetwork.org/t/open-street-map-vs-google-maps/492/4

**Comment by daniellemoorhead** [comment]
@bingxie go ahead and change the tile server and then close this issue :)
