### ISSUE TITLE
Cart deleted without warning when choosing different hub on producer's page

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8441]
## Description

The following behaviour was observed and discussed in this [slack conversation](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1611105113010100):
**Scenario 1**
- Put items into your cart
- On the map, select a different hub
- Click on the hub below "change shop to ..."
- A warning pops up that you will lose your items in your cart

This is considered to be a feature.

**Scenario 2**
- Put items into your cart
- On the map, select a producer, that sells at a different hub
- Click on the hub below "shop for ... products at"
- No warning will show, but your cart will be deleted.

This is condisered to be a bug.

## Expected Behavior
Before deleting the cart in scenario 2 a warning should be displayed (as in other cases).

## Actual Behaviour
The cart is deleted without warning.

## Steps to Reproduce
See description of scenario 2 above.

## Animated Gif/Screenshot
This is the warning which should be displayed, but is not.
![grafik](https://user-images.githubusercontent.com/1790176/139735640-5e0e6b1b-1b6e-4602-b458-c35fb54dbbcb.png)

## Workaround
Don't use the above workflow of scenario 2.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v4.1.5
* Browser name and version: Firefox 93.0
* Operating System and version (desktop or mobile): Windows 10, Desktop

## Possible Fix
Include the warning.

**Comment by seballot** [comment]
Hi ! could you please assign it to me please?

**Comment by drummer83** [comment]
Thanks again! :-)
