### ISSUE TITLE
Flash error and flash notice are on top of each other when displayed at the same time

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8442]
## Description
If flash notice (e.g.: "The hub xyz is listed in an active order cycle, but does not have valid shipping and payment methods.") is active in super admin and a flash error (e.g.: "Please select a file first" when creating a Terms of Service file) is activated at the same time, both messages are shown on top of each other and the one in the background (flash error in this case) can't be read.

## Expected Behavior
If there is more than one flash error/notice to be displayed, then display them all, in separate lines.

## Actual Behaviour
If there is more than one flash error/notice to be displayed, they are displayed on top of each other.

## Steps to Reproduce
1. Make sure have a flash notice active in super admin. Do so by opening an order cycle without having shipment and/or payment methods set up for the hub.
2. Go to admin/terms_of_service_files
3. Click "Create terms of service files" WITHOUT selecting a file

## Animated Gif/Screenshot
![grafik](https://user-images.githubusercontent.com/1790176/139811548-6c5bd85b-ef38-4d89-9526-506b2d0eba2f.png)
![grafik](https://user-images.githubusercontent.com/1790176/139810523-64e5561b-84de-4dba-9b61-e3f1f54f98b1.png)

## Workaround
None.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v4.1.5
* Browser name and version: Firefox 93.0
* Operating System and version (desktop or mobile): Windows 10, Desktop

**Comment by seballot** [comment]
Hi ! could you please assign it to me please?

**Comment by drummer83** [comment]
Of course, @seballot!
Thank you very much for your time!
