### ISSUE TITLE
Missing translation on admin/configuration/TermsOfService

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8445]
## Description
On page admin/terms_of_service_files the strings "Attachment" and "Create Terms of Service file" cannot be translated.

## Expected Behavior
All strings can be translated.

## Actual Behaviour
The mentioned strings cannot be translated.

## Steps to Reproduce
1. Select a language other than English
2. Go to page admin - configuration - Terms of Service
3. Look at the strings
4. Search for the strings in Transifex - you won't find them

## Animated Gif/Screenshot
![grafik](https://user-images.githubusercontent.com/1790176/139847996-5c03e6d5-0f9a-4f49-8771-49cda9b1c3d7.png)

## Workaround
Learn English.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.5
* Browser name and version: Firefox 93.0
* Operating System and version (desktop or mobile): Windows 10, Desktop

**Comment by kayleewon** [comment]
Can I take this?

**Comment by jibees** [comment]
@kayleewon : sure, thanks! 🙏
