### ISSUE TITLE
Uber dropdown text to "Interested in getting on the Open Food Network? Register here >"

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#845]
Estimate = 1 hour.

**Comment by daniellemoorhead** [comment]
The uber drop down may be impacted by the solution for #843 as it's likely this kind of drop down will be needed for the cookie acceptance message.

**Comment by mkllnk** [comment]
This is only a text change, right?

So remembering of closing the dropdown is another task?

**Comment by mkllnk** [comment]
The text change is at the top dropdown and in the footer.
