### ISSUE TITLE
Missing translation: "or" between buttons

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8457]
## Description
On several pages there is "or" displayed between two buttons. The text cannot be translated in Transifex. So it should be added to Transifex or it could be removed completely, because it is not very common to have "or" between two buttons.

## Expected Behavior
The text "or" should be translated or removed.

## Actual Behaviour
The text "or" is present on some pages and can't be translated.

## Steps to Reproduce
1. Log in
2. Choose a language other than English
3. Go to /admin/order_cycles
4. Klick 'new schedule' ('neuer Zeitplan' in German)
5. In the opening modal you will see "or" between the two buttons

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/1790176/140500081-84894a59-b7d6-4c09-902f-9850d8c947de.png)

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.6
* Browser name and version: Chrome 95.0.4638.69 (Offizieller Build) (64-Bit)
* Operating System and version (desktop or mobile): Windows 10, Desktop

## Possible Fix
1. Make the string "or" translatable.
2. Remove (all appearances of) the string "or".
Decision by Product/Delivery circle required which way to go.

**Comment by RachL** [comment]
@drummer83 Thanks Konrad for all those missing translation issues! 

May I ask why you added the feedback label?

**Comment by drummer83** [comment]
@RachL Because it needs a decision if "or" should be translated or removed.
Sorry, if this is not the correct label.

**Comment by RachL** [comment]
@drummer83 best for these cases is to ping @openfoodfoundation/train-drivers-product-owners because we don't have a process to review feedback label in "all the things" :+1:  I don't have a strong opinion on this one. Maybe removing the text is a good idea.

**Comment by Dmoment** [comment]
@RachL Can I work on this issue?

**Comment by lin-d-hop** [comment]
Go for it @Dmoment :-)
To clarify the spec - let's remove the untranslated 'or' text.
Thank you!!
