### ISSUE TITLE
Missing translation: table headers in product import validation table

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8458]
## Description
During product import one of the last steps is to display two tables with all the products which were found in the csv-file and all the products which will be created. The headers of those tables are not translated.

## Expected Behavior
The table headers should be translated.

## Actual Behaviour
The table headers are not translated.

## Steps to Reproduce
0. Prepare a csv-file for product import
1. Select a language other than English
2. Log in
3. Go to /admin/product_import (products - import)
4. Choose the csv-file you have prepared and klick 'upload'
5. Follow the instructions until you end up at the validation screen

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/1790176/140503865-9c708e8a-790e-4f58-82c6-c56f8fe17908.png)

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.6
* Browser name and version: Chrome 95.0.4638.69 (Offizieller Build) (64-Bit)
* Operating System and version (desktop or mobile): Windows 10, Desktop

**Comment by tsara27** [comment]
Hello @drummer83,

I have some free time. Can I work on this issue?

**Comment by sigmundpetersen** [comment]
Hey @tsara27 yes please go ahead 🎉

**Comment by RachL** [comment]
hello @tsara27 I hope this messge finds you well. Just checking in: are you still working on this issue?

**Comment by tsara27** [comment]
Hello @RachL,

Yes, I am still working on it. I was dragged into something else. Thank you for reminding.
