### ISSUE TITLE
Rounding error in tax calculation on products + fees

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#847]
For a product that costs $6.00, with a fee of 20% applied, with an included tax rate of 10% applied to both, we are currently calculating included tax as follows:

Product tax = $6(1 - 1/1.1) = 0.55
Fee tax =  $1.2(1 - 1/1.1) = 0.11
Total tax = 0.66

This is a rounding error caused by individual tax components being rounded to two decimal places before being added together.

Total tax should be: $7.2(1 - 1/1.1) = 0.65

**Comment by RohanM** [comment]
I've started investigating a potential solution to this (2:30 hrs so far). However, it looks like it'll need a fair bit more time to implement, so I'm holding off until we have confirmation on how this needs to work.

**Comment by daniellemoorhead** [comment]
@RohanM as per Discourse discussion, this can now be pushed through to testing (if anything was changed) and then to prod. Ta!

**Comment by RohanM** [comment]
After discussion, we've decided that no change is needed:
http://community.openfoodnetwork.org/t/tax-calculation-issue/547/6
