### ISSUE TITLE
Producers are able to see all orders (not just their own) when running 'Pack by Supplier' report

### ISSUE THREAD

**Issue by adele-ofn** [openfoodfoundation/openfoodnetwork#8473]
## Description
A producer contacted the Australian instance about an issue with the report they use each week to pack their orders - 'Pack by Supplier'. They filter by producer and order cycle to view and pack their own orders, but the 'Pack by Supplier' report is now displaying orders for all producers within that order cycle (not just their own). Because they have 'customer names in reports' enabled, they can also see other producers' customer names.

The bug has been successfully replicated for other suppliers and hubs. 

The producer uses this report every week, and the issue has only just arisen this week (they contacted the Australian instance at 5pm 10/11/21 AEST).

## Expected Behavior
Running the 'Pack by Supplier' report and filtering by supplier and order cycle should produce a report which lists all the orders within that order cycle for that producer only.

## Actual Behaviour
Running the 'Pack by Supplier' report and filtering by supplier and order cycle produces a report which lists all the orders for all producers within that order cycle.

## Steps to Reproduce
To reproduce this bug you'll need to act as a supplier who is selling through a hub which has multiple suppliers. You may do this by adding a non-superadmin login as a manager on the supplier's account.

1. Log in using the non-superadmin login
2. Open the reports tab
3. Click 'Pack by Supplier'
4. Select the producer and an order cycle
5. Click search

## Animated Gif/Screenshot
![Screen Shot 2021-11-11 at 11 26 42 am](https://user-images.githubusercontent.com/89006237/141216377-2808ea3b-e726-4640-b59e-cee810382513.png)
![Screen Shot 2021-11-11 at 11 27 21 am](https://user-images.githubusercontent.com/89006237/141216379-1dc07187-4bb7-4f4c-9c78-92ef2848679b.png)

## Workaround
To create a report which lists only that producer's sales, they would need to download the 'Pack by Supplier' report and filter it by producer in excel. There is no workaround available on the platform.

## Severity
**bug-s2: a non-critical feature is broken, no workaround**

Graded as an s2, as suggested by Lynne Davis in global instance managers slack channel.

We are concerned about the implications of this bug on privacy of producer and customer details on the platform. For example, two producers both selling through the same hub will be able to view each other's sales (and customer details, if "customer names in reports is enabled").

## Your Environment
* Version used: v4.1.7
* Browser name and version: Chrome 95.0.4638.69
* Operating System and version (desktop or mobile): MacOS Big Sur 11.5.2 

## Possible Fix
Given that this issue has only started occurring in the last week, we suspect it is a result of the [most recent release](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v4.1.7).

**Comment by filipefurtad0** [comment]
Probably introduced [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/8145).

**Comment by tschumilas** [comment]
I've re-opened - because I don't think this is fixed ---  unless I misunderstand the issue.

If I am a hub -  and I want to run a packing list and filter for a specific producer -   I see the sales of all suppliers.  There is no possibility for me to filter.  Below is a screenshot -  as the hub, I tried to filter for only one supplier - Garden Party Flower Farm -  and all the suppliers in the order cycle show.  (Only happens with the packing reports -  other reports filter by supplier as expected)

And the same thing happens if I am logged in as one of the suppliers ---  I see the packing report results for all suppliers,  not just my own.

![Reports-OFN-Administration](https://user-images.githubusercontent.com/13171778/143491894-e168ad4a-59cb-4d82-b35a-78a55ccc1c8b.png)

**Comment by filipefurtad0** [comment]
Thanks again for reporting @tschumilas . I'll close this issue and open a new to reflect your finding.
