### ISSUE TITLE
 Missing translation: card decline error messages

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8489]
## Description

There are several error messages - related to respective card error codes - which are not translated. These appear as a red banner after a payment attempt.

A full list is found here:
https://stripe.com/docs/declines/codes

The full list should be implemented.

~~I'm not sure on the scope of this issue: Are these errors all implemented on OFN?~~

~~I think the most relevant could be these (below) but pinging pinging @openfoodfoundation/train-drivers-product-owners in case others are required.~~

## Expected Behavior

Stripe error messages should be translated.

## Actual Behaviour

Stripe error messages are not translated.

## Steps to Reproduce

1. Add some items to the cart
2. Proceed to checkout
3. Choose a Stripe payment method and 
4. Add [different cards](https://stripe.com/docs/testing#regulatory-cards), to trigger different error messages.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/141811946-ec3181d7-c7c0-4eec-bcad-c39fb7451648.png)

![image](https://user-images.githubusercontent.com/49817236/141811502-c0085cb4-ed60-40ca-84c0-8ffd94a99415.png)

## Severity

S3

## Your Environment

* Version used: v4.1.7
* Browser name and version: all
* Operating System and version (desktop or mobile): all

**Comment by RachL** [comment]
@filipefurtad0 I think we need to consider all these messages. I don't think the case of an error message mentioning PIN can happen. But maybe there are cases we don't know / typical to some banks etc. If stripe provides translation for them, let's use them?

**Comment by filipefurtad0** [comment]
Thanks for feedback: Agree :+1: 
Updated the issue.
