### ISSUE TITLE
Snail when deleting a saved card

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8494]
## Description

Reported in production:

If a Stripe card is deleted on Stripe, it is then impossible to remove it from the "Saved Cards" list, on `/account#/cards`: clicking `Delete` triggers a snail.

## Expected Behavior

Users should always be able to remove cards from their Saved Cards list.

## Actual Behaviour

If a card was previously deleted in Stripe it is not possible to delete it from Saved Cards list, through the UI.

## Steps to Reproduce

Not 100% sure, but it should be something like:

As a customer:
1. Add a card under `/account#/cards`
2. Add some items to a cart and checkout with that card

As a Stripe admin:
3. Visit `https://dashboard.stripe.com/test/customers/` and toggle Test Mode.
4. Find the customer and click on it, the URL should be something like `/test/customers/cus_KDcRs8CarySIOy`
5. Find the section **Payment methods** and delete the card added in point 1.

As a customer:
6. Click Delete, for that respective card -> see the snail

## Workaround

Delete the card in the DB.

## Severity

bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: v4.1.7
* Browser name and version: all 
* Operating System and version (desktop or mobile): all

**Comment by filipefurtad0** [comment]
In staging, this seems not to blow up at all...

How was the card deleted @lin-d-hop ? Was it on Payment methods, as described above? 
![image](https://user-images.githubusercontent.com/49817236/142196187-e83e2a31-119d-43ed-ac0f-f0b75704d41e.png)

As a workaround, we've agreed to remove them directly from the DB. We can do this by logging in to the server and running the following in the psql shell:`

```
DELETE FROM spree_credit_cards WHERE id = <id>;
```

I've tested this in staging and seemed to work fine, especially considering that this concerns cards which are not set as default:
`is_default: f`

**Comment by filipefurtad0** [comment]
Ok, deleted:
![image](https://user-images.githubusercontent.com/49817236/142203413-b3a287f1-37f3-4c04-a5b0-25d0b6074a74.png)

I think we can close this after we've verified the cards are gone, with no side effects ping @lin-d-hop.

**Comment by lin-d-hop** [comment]
Thanks @filipefurtad0 
It was deleted on Stripe, though not sure exactly how...
All good and closing :-)
