### ISSUE TITLE
Editing unit names is not correctly applied on shopfront

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8495]
## Description

If you edit a unit name on a product sold by item, the shopfront does not display the unit name correctly everywhere. 

## Expected Behavior

Unit name is coherent

## Actual Behaviour

Only unit names on unit price is correctly edited.

## Steps to Reproduce

1. Change the unit name of a product already sold by item
2. See how the change is applied on the shopfront

## Animated Gif/Screenshot

An example in staging: 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/8043c1de-b781-4324-b1a1-786c74fc1823)

In production (the user first save the product and made a mistake, now impossible to change it): 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/9b6e476f-8e92-4fc4-9359-44f0a261b4ed)

## Workaround

I can't see one, hence s2.

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v.4.1.7
* Browser name and version: Firefox and chrome
* Operating System and version (desktop or mobile): Both

**Comment by filipefurtad0** [comment]
It seems editing the item, like for example changing the stock brings coherence between the variant unit name and the unit price:

![Peek 2021-12-06 17-10](https://user-images.githubusercontent.com/49817236/144890900-67455dd4-244e-46d5-a6af-f3717c4ca4dc.gif)

This is recorded in staging-UK after staging v4.1.7, build f89263f0604788c17c5a36fac48b5e0ec070298a

**Comment by filipefurtad0** [comment]
#8500 has been reverted [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/8585), so the issue is back - reopening:

![image](https://user-images.githubusercontent.com/49817236/145046823-acbf8df7-645d-490b-9364-5c2487e24ac5.png)

**Comment by apricot12** [comment]
@filipefurtad0 Alright. I'm currently trying to fix this through the views.
