### ISSUE TITLE
Address High Severity and Critical Security dependabot issues

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8502]
### What we should change and why (this is tech debt)

Dependabot is raising several High Severity and one Critical Security issues:
https://github.com/openfoodfoundation/openfoodnetwork/security/dependabot

### Context

This came up [here](https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1637097892042300).

**Comment by Matt-Yorkley** [comment]
Those are mostly just dependencies that are used by Storybook, which doesn't get loaded in staging or production.

**Comment by Matt-Yorkley** [comment]
Also, if you read through the details of some of these CVE's, they're things like "if a malicious user manages to pass in some data in really obscure way, a _slightly inefficient_ Regex that's somewhere in the code could slow down the server, which might theoretically lead to a Denial Of Service situation"... which honestly is not very scary! They're also referring to packages which for example are used briefly at compile time but don't actually take any user input in our case.

**Comment by RachL** [comment]
Closing this one as we will act on those separately as they come.
