### ISSUE TITLE
Duplicated text in the "https://www.openfoodnetwork.org/software-platform/" 

### ISSUE THREAD

**Issue by SarvarKh** [openfoodfoundation/openfoodnetwork#8505]
## Description

**Find out how we can help**'s text on _openfoodnetwork.org/software-platform_ is duplicated. 

## Expected Behavior
One of duplicated **Find out how we can help**'s text shall not appear on the page.

## Actual Behaviour
**Find out how we can help**'s text on _openfoodnetwork.org/software-platform_ is duplicated. 

## Steps to Reproduce
Take a look at this [URL link.](https://www.openfoodnetwork.org/software-platform/#:~:text=we%20can%20help.-,Find%20out%20how%20we%20can%20help,Get%20in%20touch%20and%20find%20out%20how%20we%20can%20help.,-Learn%20more)

## Animated Gif/Screenshot

| Actual | Expected |
| --- | --- |
| <img width="1435" alt="Screen Shot 2021-11-20 at 14 47 36" src="https://user-images.githubusercontent.com/60043698/142721889-53f6d1e4-6f6f-4cb2-9f10-d07018eddba2.png"> | <img width="1421" alt="Screen Shot 2021-11-20 at 14 48 58" src="https://user-images.githubusercontent.com/60043698/142721926-73fe7aea-92a2-49a8-84d8-157822c2ccce.png"> |
## Workaround

N/A

## Severity
[bug-s5: we can live with it, only a few users impacted](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity#severity-5-)

## Your Environment

* Version used: v.4.1.7
* Browser name and version: Chrome 96 on macOS (Big Sur)
* Operating System and version (desktop or mobile): OSX, Desktop

## Possible Fix

It is quite simple to remove the duplicated text. But this minor issue belongs to [OFN's global website](https://www.openfoodnetwork.org/software-platform/#:~:text=we%20can%20help.-,Find%20out%20how%20we%20can%20help,Get%20in%20touch%20and%20find%20out%20how%20we%20can%20help.,-Learn%20more).

**Comment by lin-d-hop** [comment]
Hi @SarvarKh 
Thanks for reporting this. In this Github repo we only add issues for the Rails app. Changes to this site (which is a WP site) can be requested in slack. Of course, you weren't to know this :-)

Closing and will post in slack. 
Thanks!
