### ISSUE TITLE
Put line breaks between the listed products in shipment email

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8506]
## What is the need / problem?

The shipment confirmation email is ugly. This issue stands as a partial answer to the feature request https://github.com/openfoodfoundation/wishlist/issues/71

We just want the list of products to be listed one after the other, with line breaks, instead of what we have today:

![image](https://user-images.githubusercontent.com/6525576/132664672-c38542f7-e0f3-4670-8478-7115b8bf79cc.png)

## Which type of users does this problem affect (and how many, if known)?
Shoppers_
Hub Managers (MCFEs)_
Producers_

## Is Papercut or feature candidate?

Confirmed papercut in September 8th 2021 meeting.

**Comment by lauriewayne** [comment]
Thank you for making our world a bit more orderly and beautiful!!!
