### ISSUE TITLE
Log-in with "Remember me" function not working

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8516]
## Description

Follow-up from #8492.

While logging in, the user has the option to check the "Remember me" option, which should store a specific cookie, and facilitate following logging in. This function is currently broken.

## Expected Behavior

Checking the "Remember me" checkbox should remember user details (by storing a cookie) and facilitate logging in.

For reference, the cookie banner displays:

`cookie_remember_me_desc: "Used if the user has requested the website to remember him. This cookie is automatically deleted after 12 days. If as a user you want that cookie to be deleted, you only need to logout. If you don’t want that cookie to be installed on your computer you shouldn’t check the “remember me” checkbox when logging in."`

## Actual Behaviour

Checking the "Remember me" checkbox does not remember user details for following log in attempts. The cookie seems to be stored but is deleted after logout.

## Steps to Reproduce

1. Visit `/#/login`
2. Be sure to accept the cookie-consent warning
3. Open the console - find the cookies section. 
4. Add your log in details, and check the "Remember me" checkbox
5. Click Log in -> notice that a `remember_spree_user_token` / `cookie` appearing 
6. Log out -> notice that this is removed
7. Try to log back in -> notice that the checkbox is unchecked, and that you have to introduce your details from scratch

## Animated Gif/Screenshot

![Peek 2021-11-25 11-54](https://user-images.githubusercontent.com/49817236/143437497-75fac9ce-0736-4254-9ee3-78cb0c6d9606.gif)

## Workaround

Adding your details each time you log in.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v.4.1.8
* Browser name and version: tested on Firefox/Chrome
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by seballot** [comment]
Hi ! could you please assign it to me?

**Comment by drummer83** [comment]
Looking forward to your contributions! :-)

**Comment by seballot** [comment]
@filipefurtad0 I think what you describe is the expected behaviour and not a bug :)

If you click "log out", then that is expected that the cookie gets deleted
If you don't click logout and open the page the next day, you will still be loggued in. Tested on local machine and on coopcircuits.fr. Remmeber me function works like that, everywhere

Please close the ticket if you agree :)

**Comment by filipefurtad0** [comment]
Hi @seballot, welcome!

Indeed, I was not too sure on how this feature should work. Thank you for clarifying :pray: 
Closing.
