### ISSUE TITLE
Automatically email producers

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#8529]
## Description

As a Hub I want to have automatic notifications to my producers at the end of every order cycle.

I want to enable this in 'Edit Order Cycle' -> General Settings.
This should be a checkbox with the text 'Automatically notify producers with their orders via emails when order cycles close.'

## Acceptance Criteria & Tests

1. The email that is sent should be the same as the 'Notify Producers' email
2. The email should be sent to the Producers and CC the Hubs
3. The email should be sent at the time that the Order Cycle closes
4. The text in the Order Cycle page should be translated.

_______________________________________________________________________________________

## Original Post

Another request from UK hubs; an option to make the notifications emails at the end of an order cycle send automatically when the order cycle closes, so that producers will receive them by the next morning after close.

Could be something like a checkbox in the order cycle.

Also, there isn't anything that shows whether or not the emails have been sent for an order cycle, which may cause issues if there are multiple people doing hub admin, so a Sent/Not Sent flag would be useful.

**Comment by seballot** [comment]
Nice! Please assign me to this one

**Comment by Matt-Yorkley** [comment]
I've been thinking about this issue over the last couple of days, i'm not sure it's a papercut though...

**Comment by lin-d-hop** [comment]
The papercuts team decided it was. The process is not perfect but I think once the group decides we continue with that decision.

You would be good in papercuts team @Matt-Yorkley ;)

**Comment by RachL** [comment]
Hi @seballot are you working on this one? Otherwise we can assign it to someone else in the team :)

**Comment by seballot** [comment]
Hi @RachL, I will do this one this week

**Comment by Matt-Yorkley** [comment]
Dev note: I had a quick play with what the job part might look like [here](https://github.com/openfoodfoundation/openfoodnetwork/compare/master...Matt-Yorkley:oc-closing) if someone else is picking it up :ok_hand:
