### ISSUE TITLE
Subscriptions payments failing in OFN, but successful in Stripe

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8534]
## Description

Within the UK subscriptions we have a growing list of shoppers for which the payments stop working in OFN, while the payment can still be taken in Stripe. 

I am not sure what the cause is, but the symptoms are:
1. A shopper's card works fine in Stripe and OFN for some time, with automatic payments taken.

2. Suddenly the payments stop being taken in OFN with no error showing. I also can't find a relevant error in Bugsnag. The payments can still be taken in Stripe. 
- The order is showing as payment status 'Balance Due (amount)' in OFN. 
- The payment status does not show as 'Failed' as it would when there is an error.

3. The payments continue to fail in OFN going forward, but can still be taken in Stripe

The result is that there is a growing list of payments that must be taken in Stripe manually. This list continues to grow.

The solution here, if at all possible, should be to enable these payments to automatically start being taken in OFN again without any action from the shopper. If that is not possible then I will not be asking shoppers to take any actions until we are confident we have resolved the underlying issue.

Example orders UK Production:
- R150268612
- R303610726
- R058286187
- R134070484

## Expected Behavior

If a payment can be taken in Stripe for a subscription it should be taken automatically in OFN

## Actual Behaviour

Some payments that can be taken manually in Stripe for a subscription are not being taken automatically in OFN. There is no error or evidence that the payment was tried.

## Steps to Reproduce

1. So far I have not found a way to reliably reproduce this issue.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: UK Production

**Comment by sigmundpetersen** [comment]
Hey @lin-d-hop is this the same as #7785 or is it different?
Lots of history there that could be helpful if they're the same

**Comment by lin-d-hop** [comment]
Thanks @sigmundpetersen for linking them. I think they are the same issue though I opened a new one as my understanding is that subs have changed a fair bit in this time and the solution offered in the previous issue a) did not uncover the underlying problem and b) asked shoppers to reenter their card details. 

I was aiming for a fresh perspective but let's see ;-)

**Comment by lin-d-hop** [comment]
Closing as we need a bigger spike around this work.
