### ISSUE TITLE
Supplier filter broken on Packing reports

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8539]
## Description

Follow-up from #8473, see:
https://github.com/openfoodfoundation/openfoodnetwork/issues/8473#issuecomment-979431767

As a hub, it is currently not possible to filter packing reports for a specific supplier.

## Expected Behavior

Supplier filter should work for packing reports.

## Actual Behaviour

Supplier filter should work for packing reports.

## Steps to Reproduce

As an OC coordinator:
1. Generate packing reports for an OC which has more than one supplier
2. Try to use the supplier filter: add a supplier in the "Producers" field
3. Hit "Search"
4. Notice you get the same results as before

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/144021690-14f30d8a-78dc-4c93-be3f-f53ea30fe894.png)

See also:
https://user-images.githubusercontent.com/13171778/143491894-e168ad4a-59cb-4d82-b35a-78a55ccc1c8b.png

## Workaround

- Searching for the desired Supplier with the browser search function
- When downloading the file: use the spreadsheet search function

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.1.8
* Browser name and version: All
* Operating System and version (desktop or mobile): All

**Comment by Matt-Yorkley** [comment]
Ah, I'm already working on this one @jibees

**Comment by lin-d-hop** [comment]
Sorry guys, this needs to be upgraded to s2.
Let's make sure it goes into the next release please :pray:

**Comment by jibees** [comment]
@lin-d-hop 

just moved to `Test Ready` ;)
