### ISSUE TITLE
BOM addition calculator at the top doesn’t currently read from / add up quantities of ‘items’

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8540]
## What is the need / problem?

Currently if a product has item as unit, the calculator at the top of the page is not working. Example on staging FR:

![image](https://user-images.githubusercontent.com/6525576/132230739-47527595-6b6a-47e2-b706-b5fbe6e70c68.png)

## Which type of users does this problem affect (and how many, if known)?

_- Hub Managers (MCFEs)_
_- Producers_
_- Instance Managers_

## Connected wishlist and discovery discussions* [list precedent discussions]

https://community.openfoodnetwork.org/t/bulk-order-management-wishlist/305/2?u=rachel

## Is Papercut or feature candidate?

Good questions

**Comment by sigmundpetersen** [comment]
Is this the same as #664?
If this never has been a feature and thus not a bug, maybe we can close that other issue.

**Comment by RachL** [comment]
yes! thank you @sigmundpetersen ❤️
