### ISSUE TITLE
Super admin navigation showing for regular enterprises

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8546]
## Description
The super admin navigation is showing for regular enterprises if they want to create new payment or shipping options directly through the admin/enterprises page. When selecting one of the links in the navigation, the page "unauthorized" opens. 

Background:
Issue #7937 reported that the super admin navigation was missing on some super admin pages. It was first addressed in #7967 and seemed to be fixed by #8395.

## Expected Behavior
The super admin navigation should only show for super admins.

## Actual Behaviour
The super admin navigation is displayed for regular enterprises if they want to create new payment or shipping methods directly through the admin/enterprises page by clicking 'create new'.
The pages `admin/shipping_methods/new` and `admin/payment_methods/new` seem to be affected (maybe more).

## Steps to Reproduce

1. As a regular user create an enterprise without payment and shipping methods.
2. Go to admin/enterprises.
3. Open the 'status' field with the red warning sign.
4. Click 'Create new' for shipping or payment method.
5. Observe that the super admin navigation is displayed on the right of the screen

## Animated Gif/Screenshot
Click 'create new' to access the broken pages:
![grafik](https://user-images.githubusercontent.com/1790176/144263480-7b8306fd-d96b-4b0c-b404-1e222f250fa2.png)

On this page the navigation on the right should not be displayed:
![grafik](https://user-images.githubusercontent.com/1790176/144275372-dc7ccd72-108d-4454-997e-531c9a31b425.png)

## Workaround
None.

## Severity
bug-s2: a non-critical feature is broken, no workaround
Users reported that they tried to create shipping and payment methods through the links in the super admin navigation - which fails due to the unauthorized page.

## Your Environment
* Version used: v4.1.8
* Browser name and version: Firefox 94.0 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS, Desktop

**Comment by drummer83** [comment]
@sinansonmez Would you be willing to have a further look at this? Your first improvement was great already!

**Comment by sinansonmez** [comment]
Hey @drummer83 Unfortunately i will not be able to work on this. I am pretty busy nowadays.

**Comment by lin-d-hop** [comment]
Unless this is an easy fix I suggest we need to revert the previous change.
This situation is far worse than the original fix for which just a few super-admin pages were impacted.

Since this issue will now take dev time from the core team for an issue that was originally prioritised I would suggest that we need to take the fastest route to resolution.

**Comment by sinansonmez** [comment]
Sorry, I didn't realize that this issue is due to my #8395 PR. I feel responsible now 🥲 I will spare some time and try to fix it asap

**Comment by sinansonmez** [comment]
As promised, I managed to spare some time and created PR to fix the issue. Right now I am checking if user is super admin and only in that case I am showing the navigation
