### ISSUE TITLE
Payment Method Report record false payment information

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#8547]
**Description**

Payment Method Report seems to record payment information selected by the customer during the order rather than the payment method finally used. 

Exemple : 

3 orders have been placed between the 1st novembre and the 2nd december 

<img width="1348" alt="Capture d’écran 2021-12-01 à 18 31 44" src="https://user-images.githubusercontent.com/67476305/144287853-755ae578-2ae2-42ef-88c6-2a8c91c147ec.png">

All were ordered with "A la livraison" payment method

<img width="1369" alt="Capture d’écran 2021-12-01 à 18 58 25" src="https://user-images.githubusercontent.com/67476305/144288104-39d35b4b-1eab-4518-a311-7b9b6a35769b.png">

If during the withdrawl, the payment method is modified by the customer and then modified in OFN by the user, the Payment Method Report still displays the method registered during the customer order.

For exemple, if we change the R644581413 order payment method for "Sur le marché" 

<img width="1053" alt="Capture d’écran 2021-12-01 à 18 33 51" src="https://user-images.githubusercontent.com/67476305/144288656-11d9a782-c9f3-4f94-b735-f16f11612ac1.png">
## Expected Behavior

The Payment Method Reports still displays "A la livraison"

<img width="182" alt="Capture d’écran 2021-12-01 à 19 04 04" src="https://user-images.githubusercontent.com/67476305/144288848-e9e506fb-38b1-4d9c-872a-93f39bbe443e.png">

**Workaround**

The user can find the correct information from Order Menu >  Edit button > Payments.
But I won't say it's an easy to use workaround in case there is "a lot" of orders. 

Maybe this issue can be linked to [8548](https://github.com/openfoodfoundation/openfoodnetwork/issues/8548)

**Comment by Cecilia-Hn** [comment]
@RachL 
I'm wondering if this case it's an S2 as there is no real workaround avec we've got three users complaining about the fact that they need to manage this information with a spreadsheet and a lot of time. What do you think ? 
Thanks a lot !

**Comment by RachL** [comment]
@Cecilia-Hn do you know why the hub edit this info? How many user reacted to this? I'm a bit afraid this is a long lasting bug that we didn't take car off because nobody edits delivery info usually. 

Do the users who edit this info do it often and if yes why? Maybe we can found a workaround for them.

**Comment by Cecilia-Hn** [comment]
Yes I don't know if it's a big need. All I know is that we've got 2 users who wants to edit it each week for accounting and to check the cash amount for each payment method at the end of each distributions day.

**Comment by RachL** [comment]
@Cecilia-Hn here if I understand correctly the problem exist _only_ when the hub edits the delivery method. So I have no doubt that having the delivery method is important, what I doubt is that it often happens that hubs are editing it. If they are editing it twice a year, I think it is dangerous to raise this as s2. Best is to select it as our next s3.
We can have a call on Monday, I'm not sure what I write is clear to understand :D

**Comment by jibees** [comment]
@RachL 
> here if I understand correctly the problem exist only when the hub edits the delivery method.

You mean, payment method right?

**Comment by RachL** [comment]
@jibees yeah all good! Sorry I got fooled by "a la livraison" 😁
