### ISSUE TITLE
order cycles wiped from UK staging 

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#855]
When we deployed v1.5 to UK staging all the order cycles disappeared.
I have recreated a test cycle but think we should check how this happened so it doesn't happen again.

**Comment by NickWeir63** [comment]
when we put v1.5 onto production this issue didnt happen

**Comment by NickWeir63** [comment]
Mikael told us:
"I just deployed to production which is saving the staging database to a file, but not changing it. Or did that happen when you staged version 1.5? The normal CI scripts are resetting the staging database to the point of the last production deployment. If you had another test branch in staging before, that data got lost. We do that, because some branches do migrations which have to be reverted before staging another branch that doesn't include these migrations."

I just wanted to check that this resolves this issue?

**Comment by lin-d-hop** [comment]
yes, it does.
however we do need to chat about this wrt how we use our staging server. If customers are testing the platform on staging we risk losing their data. Lots of options here. I'll have a think and propose a strategy...

**Comment by lin-d-hop** [comment]
So there are two factors in this:
1) Ensuring that we have the data we need for UK testing of new functionality
2) Ensuring that we have a platform that new users can use to test OFN without their test data disappearing often.

In Aus I believe they have two staging servers for this reason. Staging2 is for feature testing and staging 1 is for user testing.

I think it's fine for us to let users know that data on the staging server may be lost. And for us to just hold this awareness and ask for staging to be on the same branch as production if we want to make big changes to baseline data.

It would be good, however, for us to have a set of enterprises on staging that we can direct users to (with log ins) to allow them to feel out the software without having to input all of the data themselves only to have it lost if they happen to do it while we are testing a different branch. This will need to be done while staging is on the same branch as production.

@NickWeir63 
Key things to note in light of this understanding:
1) Let new users know that staging data might be lost at any time
2) Don't create large amounts of staging data while on a branch as this will be lost next deploy.
