### ISSUE TITLE
Split name column in customers table

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#8577]
### What we should change and why (this is tech debt)

The customers table in the database holds `name` as a single column with first and last names combined in a single string. We **really** need this to be two `first_name` and `last_name` fields (for lots of reasons; API, reports, etc).

We'll need a migration to not only change the columns but also split the existing data and reassign it.

Also related to the example endpoints in #8326, they shouldn't go live until we've made these changes and adjusted the new serializer. 

### Context

Discussion around Customers API endpoint. We should even think about starting it without doing this first.

We might need to adapt some other bits of code as well that use customers, and maybe even the customers report?

### Impact and timeline

ASAP please :sweat_smile:

**Comment by RaggedStaff** [comment]
Hey,

This sounds like an easy db fix... split the column. i'd suggest leaving the original & using a trigger to update it, that way you can not worry about migrating all the legacy code that reads it. We could do more complex things with table renames & views (potentially materialised) but the trigger update seems simplest.

A few things other things we'll need to consider:

1. What about customers with more than 2 names?
Options are first_name, middle_names, surname fields or forenames, surname. Depends how precise you need to be. 

2. And the ones with only 1 name... general best practice to put that in surname.

**Comment by RaggedStaff** [comment]
Hey,

This sounds like an easy db fix... split the column. i'd suggest leaving the original & using a trigger to update it, that way you can not worry about migrating all the legacy code that reads it. We could do more complex things with table renames & views (potentially materialised) but the trigger update seems simplest.

A few things other things we'll need to consider:

1. What about customers with more than 2 names?
Options are first_name, middle_names, surname fields or forenames, surname. Depends how precise you need to be. 

2. And the ones with only 1 name... general best practice to put that in surname.

**Comment by Matt-Yorkley** [comment]
> Options are first_name, middle_names, surname fields or forenames, surname.

I don't think we use middle names anywhere in the codebase.

> We could do more complex things with table renames & views (potentially materialised) but the trigger update seems simplest.

I'd prefer it if we can avoid using triggers or materialized views here, and just do a one-off migration which updates both the data and the app code. 

I think these names were populated from two fields in the first place (`first_name` and `last_name`), then combined into one column. It's probably worth having a look through some production data first though to see how things look. We have strings like `James Le Blanc`, which we can just split on the first space, but I wonder if there are other cases that would need a bit more finesse...

**Comment by RaggedStaff** [comment]
>  It's probably worth having a look through some production data first though to see how things look. 

Ok. Easy check... can someone run this against a prod dataset (preferably not on a live server 😉, name is unindexed so could be a costly query)?
```
SELECT
LEN(name)-LEN(REPLACE(name,' ', '')) AS space_cnt
, count(*) as count
FROM customers
GROUP BY 1
;
```

There's typically a trim function implicit in Len() that should sort out any extraneous whitespace at the beginning or end. Won't capture tabs or newlines, hoping they wouldn't make it in in the first place.

> We have strings like James Le Blanc, which we can just split on the first space, but I wonder if there are other cases that would warrant a bit more finesse

Probably, its always the edge cases that are tricky. We might get away with it if we don't drop any data - as you say, split on 1st space. Let's see how big an issue it is, maybe the data's very clean! 😎

**Comment by Matt-Yorkley** [comment]
Alright, with a sample of around 30,000 we have:

- ~10,200 records (~34%) with no name at all (blank). That's easy, we can just leave both new fields blank.
- ~19,000 records (~63%) with a single space. Easy, we can split on the space.
- ~800 records (~2.6%) which have 0, 2, 3, 4, or 5 spaces. Looking through some samples, they're not simple to split.

There's a lifeline here though; the customer `name` fields for the most part match the (combined) `first_name` and `last_name` of the customer's current `bill_address`, and those names are split across the two fields as the user originally intended. So potentially we can just pull the correctly-split versions out of the `bill_address` in most cases.

Not all customer records have a `bill_address`... but the ones that don't generally also have a blank `name`, which is fine.

I think we can work with this. These customer name fields are generally used internally for browsing/searching records, and we'll be showing the first name and last name alongside each other anyway. They can also be changed by the users if needed.

**Comment by RachL** [comment]
hello @RaggedStaff ! We are looking to move this forward I see you commented here, are you already working on this issue?

**Comment by lin-d-hop** [comment]
This work isn't a priority for @RaggedStaff to my understanding. Is there a reason you started on this Garethe?

**Comment by RachL** [comment]
We were talking about this issue with @jibees and discovered that @achauve might have seen part of the code while working on the Active Storage migration. Moreover, maybe the migration will make this work easier if I understood correctly.

Anyway @achauve it looks you might like a quick issue to ship to production. Would you be interested to work on it? I won't be there during delivery circle tomorrow but I will share a post on slack suggesting this as a topic if there is room :)

Otherwise @jibees will pick it up I guess. It's a funded feature :+1:

**Comment by achauve** [comment]
@RachL Not sure about the link between attachments and customer names, but my knowledge of the backend and migrations is getting better yes (at least I hope ;-) ).
I think it would be great to switch if there are urgent bugs, but I'm not sure about going on another feature at the same time.

**Comment by jibees** [comment]
The point here is that you seem to have done a great job/overview on the backend, and especially around migration. Then, we thought that you might be the man for the job.

**Comment by RaggedStaff** [comment]
Hey, sorry for the delayed response... baby arrived. No, I just saw this & offered a bit of expertise with cust data. Not worked on it further, happy for others to pick it up.
