### ISSUE TITLE
Assess and remove the "suburbs" table (if unused) 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8578]
### What we should change and why (this is tech debt)

Suburbs table seems empty in FR and CA production but not empty in AU production; This could be legacy data though. We should assess whether this table is still needed and remove it, if this is not the case.

### Context

This came up in the reports standardization work.

### Impact and timeline

Simplifying data model.

**Comment by mkllnk** [comment]
I had a quick search in the code and the model has been removed seven years ago (c4fb4a8510a0b9f1082866d13bdced277717c11f). The table can be deleted.
