### ISSUE TITLE
Error 500 when deleting saved cards

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8581]
## Description

Reproducible in staging and some occurrences logged in UK-production:

- after adding a new card under and associating it with a shop, attempting to delete it triggers an error 500, visible to the user.

Bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/611f8a26ecba010008dd5cb1?filters[search]=spree%2Fcredit_cards%23destroy&filters[user.id]=207722&pivot_tab=event

Possibly relates to https://github.com/openfoodfoundation/openfoodnetwork/issues/8579

## Expected Behavior

Deleting a saved card should not trigger an error 500. 

## Actual Behaviour

At times, deleting a user card triggers error 500. The card card gets deleted nevertheless.

## Steps to Reproduce

As a customer:
1. visit /account#cards
2. create a new SCA card
3. associate it with a shop
4. see the SCA pop-up: grant authentication
5. try to deleted the card
6. :bumm:

## Animated Gif/Screenshot

![Peek 2021-12-06 20-10](https://user-images.githubusercontent.com/49817236/144915366-d0912804-8357-43f1-9d64-ab57aff0d79b.gif)

## Workaround

None needed, the card seems to get deleted.

## Severity

bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: v4.1.8
* Browser name and version: all 
* Operating System and version (desktop or mobile): all

**Comment by lin-d-hop** [comment]
This happens when there is an error in Stripe. It seems Stripe errors in deleting saved cards is not handled well in OFN.
I experienced it directly when I removed a card in Stripe BEFORE removing it in OFN.
