### ISSUE TITLE
Provide an API to create and update a CatalogItem object

### ISSUE THREAD

**Issue by pacodelaluna** [openfoodfoundation/openfoodnetwork#8595]
## What is the problem we are solving 
Right now we are able to list the `CatalogItem` objects, we want know to be able to create or update them.
The main issue will be about how to map properly this `CatalogItem` object with OFN related object (`Spree::Product` and `Spree::Variant`).
On API side, it will be standard POST and PUT actions on the `catalog_items` controller.

## Success factors = expected outcome 
We can create and update a CatalogItem object on DFC API. Auto-tests are defined and covering all cases, sucesses or failures.

**Comment by RaggedStaff** [comment]
Looking at this. 

Shall we continue to use the oidc branch? If so, might fork to my repo (don't have rights across Andy's repo) unless you have another preference? 

We should probably `rebase` before we start. I can do that when I pull it across, unless you want to do that before you push up to FR-Staging?

**Comment by lin-d-hop** [comment]
This issue is not well specified. Closing.
