### ISSUE TITLE
Support new DFC JSON-LD format

### ISSUE THREAD

**Issue by pacodelaluna** [openfoodfoundation/openfoodnetwork#8596]
## What is the problem we are solving 
We are currently supporting the v1.5 format (https://datafoodconsortium.gitbook.io/dfc-standard-documentation/appendixes/practical-examples/version-1-5).
We should move to v1.6 support (https://datafoodconsortium.gitbook.io/dfc-standard-documentation/appendixes/practical-examples/version-1.6) in order to support flat graph structure.

## Success factors = expected outcome 
The output is the DFC API should be in a JSON-LD format matching the DFC ontolgies.

**Comment by RachL** [comment]
New issue here: https://github.com/openfoodfoundation/openfoodnetwork/issues/9170
