### ISSUE TITLE
Deployments fail with "storybook unmet peer dependency" errors

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8604]
## Description

Deployments are broken on master after merging:
https://github.com/openfoodfoundation/openfoodnetwork/issues/8575

The error message points out to unmet dependencies, see:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/uk-staging/deploys/990

Deploying commit 65e52916790ab71091a5dc4ab2ee1974e89fc149 (before merging the above PR) worked fine.

This was tested across staging servers.

**Comment by jibees** [comment]
The solution could probably be to merge https://github.com/openfoodfoundation/openfoodnetwork/pull/8603, https://github.com/openfoodfoundation/openfoodnetwork/pull/8602 and https://github.com/openfoodfoundation/openfoodnetwork/pull/8601 at the _same time_ (ie each one after the other) as those three projects (`@storybook/serverBump`, `@storybook/addon-docs` and `@storybook/addon-controls` should have the same version to work together)

**Comment by Matt-Yorkley** [comment]
Those 3 PRs have been merged now. We should be able to deploy master and PRs again, but we might want to redraft the release to include those recent merges?

**Comment by filipefurtad0** [comment]
I'll have a go at this, and try this out.
Thanks @Matt-Yorkley :pray:

**Comment by sigmundpetersen** [comment]
Looks to me like those "unmet peer dependency" are just warnings.

Found some errors further down:
- "stdout": "RAILS_ENV=staging environment is not defined in config/webpacker.yml"
- "EntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'babel-loader' in '/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2021-12-10-134327'"

Could these be any clues?

**Comment by mkllnk** [comment]
One problem with merging all the storybook dependencies is that after each merge, there's a conflict and we need to wait for Dependabot to rebase. That takes a while. And we usually can't wait for reviews either because by the time two reviews are in, there's a new version released. Our process doesn't work with the continuous delivery of storybook.
