### ISSUE TITLE
Cancelling orders display an error to the customer

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8620]
## Description

For shops which allow changes to orders, if the customer cancels an order a banner will be displayed stating that the cancelling of the order was not successful - when in fact it was.

## Expected Behavior

An error message should not be displayed, if the order was successfully cancelled.

## Actual Behaviour

An error message is displayed, despite successful cancelling of the order.

## Steps to Reproduce

As a customer:
1. Place an order in a shop which allows order changes, till the OC is open
2. Visit `/account#/orders`
3. Cancel an order, by accepting the warnings*** -> see the banner

*** actually, two confirmations-boxes appear, when only one should appear - a separate issue

## Animated Gif/Screenshot

![Peek 2021-12-14 19-11](https://user-images.githubusercontent.com/49817236/146068271-182711d7-b4e5-4773-abdd-af5b66774f87.gif)

## Workaround

None needed.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.1.11
* Browser name and version: Firefox 95
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by SarvarKh** [comment]
I am working on this...

**Comment by SarvarKh** [comment]
Hello @filipefurtad0

**Comment by SarvarKh** [comment]
Hello @filipefurtad0 
I have tried to reproduce the issue by following these steps (animation is given below), but an error message is not popping up.

1. Created enterprise as Shop (SuperFlexibleShop) allowing to change/cancel the order while OC is open.
2. Placed the product in the Shop
3. Ordered the product by logging in from another account, and then canceled the order.
4. No error message, only alert is displayed for confirmation...

Could you advise if I missed something or the issue has been resolved already?
![Untitled](https://user-images.githubusercontent.com/60043698/147926366-eb4b50d5-13c7-4f24-8c34-aedf1a2fcc83.gif)

**Comment by filipefurtad0** [comment]
Hey @SarvarKh ,

Thank you so much for jumping on this issue and the detailed video :pray: 

I'm still observing this issue on staging servers:
![image](https://user-images.githubusercontent.com/49817236/147941772-35a2cc31-c07a-4b50-a676-4a63d1c62bb9.png)

I'll need to investigate more, there should be something on these orders which triggers this warning... My first hint was payment methods, but this was observed both for orders paid with cash and stripe. Not sure what could it be...

I'll drop a line if I find out something else on this regard, it looks tricky. If you feel blocked at some point please do feel free to drop this one and pick up another issue.

Thanks again!

**Comment by SarvarKh** [comment]
@filipefurtad0 thank you for your feedback.
I'd carry on to work on this if you could advise after your investigation.

Because I tried to reproduce it again without success - no error flash message. Is it possible that this issue relates to the OFN UK or France, not the OFN Australia? because I noticed in both gifs that they seemed to belong to the UK and France shopfront ordering/cancellation pages.

Thank you once again🙏

**Comment by RachL** [comment]
hello @SarvarKh ! I'm just checking in: are you still working on this issue? Do you need any help?

**Comment by SarvarKh** [comment]
Hi @RachL I couldn't reproduce this issue, it seems that it requires more time. Could you unassign me? so that others can also check this issue. I will also have a look over the weekends. Thanks

**Comment by drummer83** [comment]
Maybe worth mentioning that I also cannot reproduce this one and #8704 anymore (which is also seen in the video above).
Something has changed here... but the only merged PR I could find which is somewhere near around this topic would be #8661.

I asked for Filipe's opinion over in the other issue. We might be able close them both?

**Comment by filipefurtad0** [comment]
Thanks @drummer83,
Can't reproduce it anymore :tada: 

![Peek 2022-01-26 10-23](https://user-images.githubusercontent.com/49817236/151146241-9e5bec91-e658-4f17-826a-309752deaddd.gif)

Closing.

**Comment by drummer83** [comment]
Well, we do have the regression, that after cancelling the order, the page remains empty (can be seen in both your videos). Before the list of orders was displayed automatically. Should I create a new issue for that, @filipefurtad0? 
@SarvarKh Maybe you would like to have a look at that instead?

**Comment by filipefurtad0** [comment]
Thanks @drummer83 ,
Yeah, I noticed that but was not sure it was a regression. If you are sure about that than feel free to open that issue.
