### ISSUE TITLE
[Split Checkout] Clicking the `Next - Order Summary` button has no effect

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8625]
## Description

Follow-up from #8503; concerns checkout split (feature toggle on).

After selecting a payment method and adding the necessary data, clicking the `Next - Order Summary` button has no effect. This seems to work only when adding new credit card details on a stripe SCA payment, but is broken for all other payment methods.

## Expected Behavior

Clicking the `Next - Order Summary` button should redirect the user to the Order Summary page.

## Actual Behaviour

If cash, paypal, Stripe SCA (with a saved card) are selected as payment methods, then clicking the `Next - Order Summary` button takes no effect.

## Steps to Reproduce

1. On checkout, select any payment method (Exception is Stripe SCA while adding new card details)
2. Click `Next - Order Summary` button -> notice nothing happens.

## Animated Gif/Screenshot

![Peek 2021-12-15 17-06](https://user-images.githubusercontent.com/49817236/146231924-26203c5b-e156-41d8-875f-a248c0635c98.gif)

**Comment by jibees** [comment]
The `app/webpacker/controllers/stripe_controller.js` handle the submit of the form (`form.addEventListener("submit", event => {})`), and stop the propagation of the event. with an error:

```js
{
    "type": "validation_error",
    "code": "incomplete_number",
    "message": "Votre numéro de carte est incomplet."
}
```

if the payment method is not stripe, we should not enter in this method, if the payment method is stripe no error should happen I guess.

(cc @Matt-Yorkley )
