### ISSUE TITLE
Missing translation: "Are you sure?" when deleting a product

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8629]
## Description
When deleting a product on /admin/products there is a warning "Are you sure?" displayed. This message cannot be translated.

## Expected Behavior
The message should be translated (as when deleting shipping methods).

## Actual Behaviour
The message is not translated.

## Steps to Reproduce
1. Go to admin/products
2. Delete a product using the recycle bin icon
3. Observe the message

## Animated Gif/Screenshot
![Are you sure](https://user-images.githubusercontent.com/1790176/146287424-1be9a0a5-84f2-4c68-9eda-d5747d7ad96c.png)

## Workaround
Learn English.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.10
* Browser name and version: Firefox 95.0
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS Desktop

## Possible Fix

**Comment by SuprajaRamesh** [comment]
Can this be picked up or is anyone already working on it?

**Comment by drummer83** [comment]
Hi @SuprajaRamesh,
Thanks for offering your support on this one. 👍🏻
I am not aware of anyone else working on it, so please go ahead. I will see if I can assign it to you!
If there are any questions, please feel free to ask any time!
