### ISSUE TITLE
[Split checkout] Make the bottom buttons sticky

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8630]
## Description
**- As a:** shopper
**- On page:** last checkout page step
**- I want to be able to do:** always see the bottom checkout button, no matter the device used

## Acceptance Criteria & Tests

Tests have to be performed both on mobile & desktop

_Scenario 1 as a guest checkout_

1. Add product to the cart
2. Proceed to checkout
3. When reaching the last step, no matter where I scroll on the page I see the checkout button at the bottom, overlapping the page content

_Scenario 2 as a loggedin user_

repeat scenario 1 but this time with a known shopper

**Comment by RachL** [comment]
@jibees here is a proposal to first try the stickiness ( :D ) only on last step where it is the most problematic.

I'm afraid to make the other step too heavy if we add some sticky option, but let me know if it makes things more complex from a tech pov.

**Comment by jibees** [comment]
> I'm afraid to make the other step too heavy if we add some sticky option

Agree.

Will do only on the last step then.
