### ISSUE TITLE
Add test coverage on payments_controller

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#8633]
### What we should change and why (this is tech debt)

This controller has no tests or documentation: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/payments_controller.rb

It took me a while to figure out that it's actually the controller which handles links in Stripe authorization emails (for subs). I thought it might be dead code at first!

### Context

Working on payments for split checkout.

**Comment by kellyzhangg** [comment]
Is this still a relevant issue? Was going through some open testing-related issues and wanted to take a stab at one, thanks!

**Comment by filipefurtad0** [comment]
Ah! Well spotted @kellyzhangg, I've lost it from sign .
Sure, I've assigned you to the issue. Please let us know if you have any questions!

**Comment by kellyzhangg** [comment]
Just submitted a PR - let me know if anything looks off with the test! Thank you 👍
