### ISSUE TITLE
Stripe payment not taken if authentication step occurs after OC closure

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8635]
## Description

If an order cycle closes:
- after an order was placed
- before a Stripe SCA payment was authorized

Authorizing the payment fails, although this is the expected.

This potentially affects all order types, frontoffice and backoffice are confirmed; affects subscriptions as well -> Verified when following the authentication link provided per email, while logged out.

**Bugsnag** as monitoring was introduced here #8484 :muscle: 
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61afbd9471f8ef000745ab84?filters[event.since]=30d&filters[error.status]=open&event_id=61bb44e1008aa54f6cc50000

## Expected Behavior

Stripe SCA payments should be successfully authenticated, provided the order was placed before the OC closes.

## Actual Behaviour

Stripe SCA payment authentication is failing, if the authentication step occurs after OC closure.

## Steps to Reproduce

1. Admin: On a **newly created OC**, place a BO order with a Stripe SCA payment -> the authorization link should be sent to the customer
2. Admin: Close the OC
3. Customer: use the authentication link
4. Customer: See the message indicating OC closure.
5. Admin: Check the state of the payment and the Stripe Dashboard - > see no payment is there

## Animated Gif/Screenshot

Backoffice

![image](https://user-images.githubusercontent.com/49817236/146387238-d7c1d391-d9d6-46a0-935b-adeaa7fc491a.png)

**Shopfront**
![Peek 2021-12-16 13-53](https://user-images.githubusercontent.com/49817236/146387160-221ef8f4-33c7-41d7-8fc7-1e14b74eabb2.gif)

## Workaround

Manually adding payments to each order may be unfeasible.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.1.11
* Browser name and version: all
* Operating System and version (desktop or mobile): all

**Comment by Matt-Yorkley** [comment]
Cool. There's 3 places where we might need to authorize a Stripe payment; checkout, backoffice, and subscriptions. 

I think in the first case (checkout) it's okay. The payment should theoretically get authorized straight away as part of the checkout process, but if it's left too long and the OC closes, the order doesn't get placed :ok_hand: 

In the other two cases this is more of a problem, as it's _normal_ that the order can be completed first and then require user authorization on a payment later (potentially after the OC has closed).

So part of what we need to do here is separate Stripe processing from the `CheckoutController`. I'll submit a PR for it soon, then we can reassess :+1:

**Comment by filipefurtad0** [comment]
I could not reproduce this bug/bugsnag warning on subscription order payment - updated the description.

**Comment by filipefurtad0** [comment]
Humm... I just observed this now while testing a subscription related PR:

```
RuntimeError payments#redirect_to_authorize
Notice: order cycle closed during checkout completion
```

This seems to be occurring in production as well:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61afbd9471f8ef000745ab84?filters[event.since]=30d&filters[error.status]=open&event_id=61c1bcaf008aa5d0a44d0000

Specifically, this occurred by following the payment authorization link provided by email, **while logged-out** from the respective account. Logging in displayed the banner pointing out the closed OC. Retrying the link leads to a successful payment.

**Comment by Matt-Yorkley** [comment]
Thanks for investigating :pray:

There's definitely a few funky issues around sessions/links and authorizing payments. Pulling the Stripe logic out into it's own controller is the only real way to begin addressing these kinds of issues. In progress :ok_hand:
