### ISSUE TITLE
Inventory display in Firefox

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#865]
When I visit `/admin/inventory` with Firefox and select a hub, the table is displayed in the wrong place.

Screenshot: https://files.zenhub.io/56e251912c70ecd345e1a27c

![https://files.zenhub.io/56e251912c70ecd345e1a27c](https://files.zenhub.io/56e251912c70ecd345e1a27c)

Chrome displays the page as expected.

**Comment by myriamboure** [comment]
I can't reproduce, it seems the issue is fixed
![capture du 2018-07-13 11-58-28](https://user-images.githubusercontent.com/8135376/42685749-21c11238-8694-11e8-9b5c-06cbd0bc2f2a.png)
