### ISSUE TITLE
Alert modals appear with no color fill on the order cycles page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8665]
## Description

Alert modals appear with no color fill on the order cycles page, `/admin/order_cycles`. Likely introduced [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/7784).

## Expected Behavior

Modal should appear like this:
![image](https://user-images.githubusercontent.com/49817236/148048307-5bc8cefd-8d3d-4524-ad6f-743458937c06.png)

## Actual Behaviour

Appears like this:
![image](https://user-images.githubusercontent.com/49817236/148048829-f228b9c6-b8b8-441c-bdfe-1cf9a80602b7.png)

## Steps to Reproduce

1. Set up a subscription (associated with a schedule, associated to an OC)
2. Edit the dates on the respective OC
3. See the modal appears with no color fill.

## Animated Gif/Screenshot

Compere expected vs actual behavior.

## Your Environment

* Version used: currently on master, not on production, not on the current release
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile):

**Comment by filipefurtad0** [comment]
This seems to be affecting the schedules menu as well:

![Peek 2022-01-04 18-21](https://user-images.githubusercontent.com/49817236/148105669-057c5569-75e0-4cdc-84e6-f18a3f2ffa37.gif)

**Comment by Matt-Yorkley** [comment]
Should be fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/8659

**Comment by jibees** [comment]
I tested with #8659 and yes, should be fixed.
