### ISSUE TITLE
Checking out as a guest

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8668]
## Description

On the new split-checkout feature,  guest users are not prompted to either login or checking out as guest (if allowed by the shop) and are always able to checkout.

## Expected Behavior

When visiting a shop as a guest:
- If a shop **does not** allow guest checkout, the customer is redirected to this screen

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/ad0b824e-1018-4ffd-a703-008b1e3b6010)

- If a shop **does** allow guest checkout, the customer is redirected to this screen

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/fb3b6438-2193-45fe-a0b8-4767d07b04d5)

## Actual Behaviour

Guest users are not prompted to either login or checking out as guest (if allowed by the shop) and are always able to checkout.

## Steps to Reproduce

As a guest customer:
1. Visit a shop which allows guest-checkout
2. Add items to the cart and proceed to checkout (you should be on `/checkout` page)

3. On a different session, log in as the admin and change the setting to require customer log-in. This is set in `/admin/enterprises/<enterprise_name>/edit#!/shop_preferences`.

Go back to your customer session and:
4. Visit the same shop, now not allowing guest-checkout
5. Add items to the cart and proceed to checkout (`/checkout` page) 

6. Notice how in both cases the user is able to proceed to the first step of the split checkout `1 - Your details`

**Comment by filipefurtad0** [comment]
Maybe [the change in this spec](https://github.com/openfoodfoundation/openfoodnetwork/pull/8673) can be used as acceptance criteria for closing this issue?

**Comment by jibees** [comment]
I totally missed this feature. 
I'll work on it.
