### ISSUE TITLE
CSP: remove inline scripts

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#8699]
### What we should change and why (this is tech debt)

We need to get to a place where we can remove the `unsafe_inline` directive from our CSP configuration in `config/initializers/content_security_policy.rb`. In order to do that we need to remove/replace all inline scripts in the codebase (otherwise the app will be broken).

One of the simplest ways to look for inline scripts is to search the codebase for the `:javascript` tag. These all need to go! Most of the results of searching for `%script` also need to go. Here's an example:
https://github.com/openfoodfoundation/openfoodnetwork/blob/3480c5d931c235edd6d23380cdaa79265514b9e8/app/views/admin/order_cycles/_order_cycle_top_buttons.html.haml#L1-L16

A lot of our inline scripts are random bits of legacy jQuery like this one :point_up: . We can generally replace those with StimulusJS controllers.

Some of our inline scripts are basically just simple vanilla Javascript. These could just be moved out of views and into regular JS files and included into the rest of our precompiled JS.

Some of our inline scripts are closely tied to our use of Angular, and are a bit trickier to remove/replace/disentangle. Take this monstrosity for example:

https://github.com/openfoodfoundation/openfoodnetwork/blob/3480c5d931c235edd6d23380cdaa79265514b9e8/app/views/spree/admin/products/new.html.haml#L112-L118

You might be looking at this and thinking: "WTF is this even doing? Why is it here in this view file? Does it even need to exist?". Perfectly reasonable questions which I currently can't answer :man_shrugging: TLDR; this needs to be removed, but removing it without breaking anything might require some other code changes. In the wider scheme of things we want to remove Angular completely, but that might take some time.

### Context

This came up as part of #8648

### Impact and timeline

When this is finished we should be able to remove the `unsafe_inline` directive from our CSP config and still have a green build.

**Comment by jibees** [comment]
I don't know exactly how we can handle this easily and seamlessly, but worth doing it.
Should tackle them one by one, by creating a PR for each case (referencing this issue, but not closing it)?

**Comment by Matt-Yorkley** [comment]
> tackle them one by one, by creating a PR for each case

Yeah. I mostly put this here are a general notice / reminder. I don't think we'll get this done all at once or even in the short term.

**Comment by filipefurtad0** [comment]
Hey everyone,
It seems all PRs mentioning this issue are now merged, closing :+1:
