### ISSUE TITLE
Text change on 'listing orders' screen

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#870]
On the ‘listing orders’ screen (see screenshot) the headings ‘payment county’ and ‘shipping county’ should read ‘payment state’ and ‘shipping state’.  
![listing orders](https://cloud.githubusercontent.com/assets/10517702/13955625/4705ea2c-f03d-11e5-83b0-dee8ba5f2909.png)

**Comment by lin-d-hop** [comment]
Due to the fact that we only have 1 translation for the word 'State'. This will obviously be an issue for all languages apart from Australian English :-)

**Comment by lin-d-hop** [comment]
Ok so this was actually from the Spree I18N project.

I've submitted a PR here:
https://github.com/spree-contrib/spree_i18n/pull/668

Will close once that PR has been merged and the changes will flow through to us.

**Comment by stveep** [comment]
In the mean time, this can be overridden locally in `config/locales/en-GB.yml` so we don't need to wait for the spree_i18n PR:

https://github.com/stveep/openfoodnetwork/commit/27fdfb60af61ca2fdd1ed7484df028502b894b69

Should I set up a PR for this into master, or do we maintain our en-GB file somewhere else @pmackay?

**Comment by lin-d-hop** [comment]
Nice one @stveep Thanks for helping out on that.

This will go into master as all is maintained in the main code base.

**Comment by lin-d-hop** [comment]
Hope you don't mind me assigning to you @stveep to get a PR in for your solution :-)

**Comment by lin-d-hop** [comment]
Hi @daniellemoorhead @mkllnk Could this be merged to master for the next release please? thanks :-)

**Comment by mkllnk** [comment]
Should be easy. It's a small change. @daniellemoorhead I'm happy to take this on. Estimate 1 hour.

**Comment by daniellemoorhead** [comment]
Go for it @mkllnk

**Comment by mkllnk** [comment]
@lin-d-hop Merged. :-)

**Comment by lin-d-hop** [comment]
See this on UK production now (side effect of updating translation file for v1.6.0).
Closing.
