### ISSUE TITLE
[Flaky] spec/system/admin/order_print_ticket_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8702]
### What we should change and why (this is tech debt)

   1) 
    As an administrator
    I want to print a ticket for an order
 as an enterprise manager viewing the edit page can print an order's ticket
     Failure/Error: print_data = page.evaluate_script('printData');
     
     Ferrum::JavaScriptError:
       ReferenceError: printData is not defined
           at <anonymous>:1:15
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_print_a_ticket_for_an_order_as_an_enterprise_manager_viewing_the_edit_page_can_print_an_order_s_ticket_367.png

     
     # ./spec/system/admin/order_print_ticket_spec.rb:49:in `block (6 levels) in <top (required)>'
     # ./spec/system/admin/order_print_ticket_spec.rb:48:in `block (5 levels) in <top (required)>'
     # ./spec/system/admin/order_print_ticket_spec.rb:47:in `block (4 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:38:in `block (2 levels) in <top (required)>'

### Context

Came up here:
https://github.com/openfoodfoundation/openfoodnetwork/runs/4774852822?check_suite_focus=true

### Impact and timeline

Reliable build.

**Comment by mkllnk** [comment]
I ran this spec locally and 3 out of 10 runs failed.
