### ISSUE TITLE
Notify Producers Email not sending on first button click

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8707]
## Description

This morning a hub reported that when they clicked the Notify Producers email the emails didn't send.It appears the button had been pressed because it now was labelled 'Re-notify Producers'

After reading through the PR and testing on this it appears that with the automation of this button a first click was not tested but a second click was tested. I pressed 'Resend Notification Emails' and the emails sent correctly.

Obviously users should not have to press this button a second time for it to work. 

## Expected Behavior

Notify Producers button works every time it is pressed.

## Actual Behaviour

Notify Producers button appears to not work on the first press.

## Steps to Reproduce

1. After an order cycle closes, and when the Notify Producers button has not been automated, press the Notify Producers button
2. Emails dont send
3. Press again
4. Emails send

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

Marking as S1 as this is how producers are sent their orders and the UX suggests that everything has worked. If a hub manager doesnt notice then the whole order cycles produce will not be delivered to the hub.

## Your Environment

* Version used: 4.1.12
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Probably introduced in the last release in 4.1.12 with #8598

**Comment by filipefurtad0** [comment]
Hi @lin-d-hop,

I can't reproduce the issue. Tested as follows:

As an:
- Admin: opened an OC, with products and stock from a Supplier
- Customer: visited the shop and placed orders

- Admin:
  i) with the OC still open -> clicked Notify Producers once -> Both emails arrive as expected *
  ii) after the OC closes, and before the automatic notification -> clicked Notify Producers once -> Both emails arrive as expected *

* Two emails are expected in the case above, one for the OC coordinator and one for the Supplier.

So far I could not find a scenario in which the notification Email does not arrive to my mailbox, after clicking the Notify Producers.

Any thoughts on this? Or scenario you feel might be relevant to test?

**Comment by filipefurtad0** [comment]
Also relevant, would be a test case, in which:
- the Admin
iii) after the OC closes, and **after** the automatic notification -> clicked **Re-Notify** Producers once

![Peek 2022-01-12 09-57](https://user-images.githubusercontent.com/49817236/149120111-9fcc1431-da3d-40ec-a986-29682c8625e2.gif)

However, there is a bug in the UX indeed, which is misleading indeed. It related to with **how** the OC is created:
- if an order cycle is created from an OC (i.e. **cloned**) in which the automatic notification ran (i.e. the button displays **Re-Notify**), then the cloned OC will display the same button.

Below we clone "OC9 - to be cloned". Notice how the new OC (cloned from OC9) already displays the green tick and is labelled "Re-notify":

![Peek 2022-01-12 10-12](https://user-images.githubusercontent.com/49817236/149121220-8a035832-cfe1-4d72-9c5f-0813f70b9916.gif)

At this stage, not orders were placed on this OC, so clicking **Re-Notify** will not trigger any email. So I think this could be the issue?

**Comment by Matt-Yorkley** [comment]
Okay, I agree with your assessment; I think the notify producers button _does_ send the emails when clicked, and the issue was more about confusion around the UI where the button was showing that the emails had been sent when actually they hadn't.

**Comment by lin-d-hop** [comment]
The user denies this is the case, however a 'misclick' would have created this behaviour.

This user is prone to errors so I am happy to follow your assessment.
