### ISSUE TITLE
Cloned OCs retain UX /"Re-send Notify" button

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8713]
## Description

This issue might be a double from #8707 - not sure, hence opening this one:

If an order cycle is created from an OC (i.e. cloned) in which the automatic notification ran (i.e. the button displays Re-Notify), then the cloned OC will display the same button.

At this stage, no orders were placed on this OC, so clicking Re-Notify will not trigger any email. This does not happen if an OC is created from scratch-

## Expected Behavior

For clones from OCs in which the automatic producer notification was triggered:

- Cloned OCs display "Notify Producers" button and no green tick.

## Actual Behaviour

For clones from OCs in which the automatic producer notification was triggered:

- Cloned OCs display "Re-Notify Producers" button and the green tick.

## Steps to Reproduce

1. Create an OC.
2. Run the steps to get the "Re-Notify Producers" + green thick, described in #8598
3. Clone that OC
4. Visit `/admin/order_cycles/<oc_number>/edit` and notice the UX on the button

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/758af586-9c61-4d0e-adcd-720fa6c9404f)

## Workaround

Ignore it. The button works, but is misleading. It won't trigger any emails for a freshly cloned OC as it has no orders associated with it.

## Severity

Maybe a good idea to fix asap?
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 4.1.12
* Browser name and version: Firefox 95
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by Matt-Yorkley** [comment]
Closed via #8712
