### ISSUE TITLE
[SplitCheckout] selected shipping method is not shown in the UI (and/or saved)

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#8716]
## Description
It seems that the split checkout do not save the shipping method (at least in certain condition, and from an UX point of view)

## Expected Behavior
Actually save the shipping method choose by the customer and show the selected shipping method in the UI. 

## Actual Behaviour
The shipping method is not saved/seen in the form

## Steps to Reproduce

1. Add product to cart, and proceed to checkout
2. Choose a shipping method and go to next step (payment)
3. Go back to first step (details): no shipping method is selected

<img width="623" alt="Capture d’écran 2022-01-13 à 11 02 41" src="https://user-images.githubusercontent.com/296452/149308912-8e4df3dd-358e-4365-a66c-06062506b342.png">

## Severity
Still not available (under a feature toggle)

**Comment by jibees** [comment]
I wrote a system spec, trying to reproduce the issue, but although it seems to be very easy to reproduce on my machine, can't reproduce it on system spec. I should have a particular option...

**Comment by Matt-Yorkley** [comment]
I'm sure this was working before... :thinking:

**Comment by jibees** [comment]
yes, I can confirm that probably in _most of _ cases it should work. But I can tell you that on my setup, only the last shipping method (the one that is without any fees), wants to be selected: 
<img width="534" alt="Capture d’écran 2022-01-14 à 11 59 42" src="https://user-images.githubusercontent.com/296452/149504877-34c26cb4-bddb-4bd4-bb0c-e46924dc5a75.png">

**Comment by Matt-Yorkley** [comment]
I can't currently replicate this on master :thinking:

Do you have some more details about your exact setup with the shipping methods?

**Comment by jibees** [comment]
I don't know exactly what is relevant, here's the screenshots:

##### The one that *can't* be selected
<img width="730" alt="Capture d’écran 2022-01-14 à 12 04 51" src="https://user-images.githubusercontent.com/296452/149505596-13176c5a-383d-45a7-967d-36845aa9159e.png">

##### The one that *can* be selected
<img width="737" alt="Capture d’écran 2022-01-14 à 12 05 00" src="https://user-images.githubusercontent.com/296452/149505605-e122b32d-8c2e-4d5d-b4b1-741f0977d265.png">

**Comment by jibees** [comment]
I think I will close this issue, since I could not reproduce the issue: I've created a new cart, then proceed to new checkout, but could not reproduce it. Maybe a temporary bug on the old cart I had?

_For the record, the test I've created:_ 

```diff
diff --git a/spec/system/consumer/split_checkout_spec.rb b/spec/system/consumer/split_checkout_spec.rb
index 252fc97c74..a6ef9fd44a 100644
--- a/spec/system/consumer/split_checkout_spec.rb
+++ b/spec/system/consumer/split_checkout_spec.rb
@@ -158,6 +158,24 @@ describe "As a consumer, I want to checkout my order", js: true do
           click_button "Next - Payment method"
           expect(page).to have_current_path("/checkout/payment")
         end
+
+        describe "submit the form and then go back to details step", :debug do
+          before do
+            click_button "Next - Payment method"
+            click_on "Back to Your details"
+          end
+
+          it "should display the selected shipping method" do
+            expect(page).to have_checked_field("shipping_method_#{free_shipping.id}")
+          end
+
+          it "should allow the user to change the selected shipping method" do
+            choose shipping_with_fee.name
+            click_button "Next - Payment method"
+            click_on "Back to Your details"
+            expect(page).to have_checked_field("shipping_method_#{shipping_with_fee.id}")
+          end
+        end
       end
 
       describe "selecting a delivery shipping method and submiting the form" do
```
