### ISSUE TITLE
[Split Checkout] Logging in during guest checkout redirects to homepage 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8719]
## Description

As a registered user, but during guest-checkout:
when a distributor authorizes checking out as guest, the user is prompted to log-in or checkout as guest. In this situation the user can login which should trigger a redirect to the Details page, ideally with some previously filled in details. 

## Expected Behavior

Logging in during guest checkout redirects the user to the Details section.

## Actual Behaviour

Logging in during guest checkout redirects the user to the homepage.

## Steps to Reproduce

1. Set up a distributor which authorizes checking out as guest
2. Visit this shop as a (previously registered) guest, adding some items to the cart
3. Proceed to checkout
4. Choose to login
5. Notice you get redirected to the homepage

## Animated Gif/Screenshot

![Peek 2022-01-12 20-06_](https://user-images.githubusercontent.com/49817236/149215303-60de14e0-2b77-4412-81ab-243254c0d7f5.gif)

**Comment by Matt-Yorkley** [comment]
I've got a PR for this but it's blocked by #8679 and #8733...
