### ISSUE TITLE
Embed shopfront in external website

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#872]
Audacious Veg want to embed their OFN shopfront within their website (rather than linking to it as a separate screen). They asked if there was some HTML code that they could copy into their Wordpress site that would show the OFN shopfront within their website.

**Comment by lin-d-hop** [comment]
As stated in user guide this has long been seen as low priority...

**Comment by lin-d-hop** [comment]
Moving this into the UK pipeline.
@RohanM has done some work in enabling the groups functionality to be embedded commenting:
"I did some work on embedding groups, but didn't start on shopfront embedding. However, the groups embedding wasn't too complex and seemed to produce reasonable results pretty quickly."

Work so far in the thrive-groups-embed branch, which includes a demo of a couple of group pages.

Would be great to flesh out an estimate and specification here:
https://community.openfoodnetwork.org/t/embeddable-shopfronts-whitelabelling/757

**Comment by pmackay** [comment]
@NickWeir63 can you indicate how much demand there is for this feature? Of all the groups interested in OFN, how many might want it?

**Comment by lin-d-hop** [comment]
This has been discussed regularly in management meetings and is currently second highest future dev priority.

**Comment by lin-d-hop** [comment]
Closing as something is happening regarding germans and @kirstenalarsen...
