### ISSUE TITLE
No confirmation email when adding Golden Apple Press to UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#874]
All the other producers we have added have recived the confirmation email but despite several attempts at resending it this one srill has not come through as an email  - see screenshot.  
![screenshot 2016-03-29 12 54 03](https://cloud.githubusercontent.com/assets/10517702/14107093/bad5158e-f5ad-11e5-9dce-c57f3e54632e.png)

**Comment by lin-d-hop** [comment]
I couldn't see any obvious reason why this email was failing. As the producer had no details or products associated and this problem hadn't been seen on other producers it didn't seem an effective use of my time to look into it too deeply. I simply deleted and recreated the enterprise.
If it happens again I'll look deeper. Hope that's ok. Closing for now.

**Comment by NickWeir63** [comment]
yes that is great thanks Lynne - sorry i didn't think of trying that
