### ISSUE TITLE
"Interested in collaboration" lower banner still redirecting to openfoodnetwork.org

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#876]
The top bar redirect to the right page (https://www.openfoodnetwork.no/register) but the same bar at the bottom of the page redirect to openfoodnetwork.org > should redirect to the same /register page.
Tested on both the French and Norwegian instances.
Ping @blancnic if that's something you can work on for next release :-) Small thing but I received feedback from the first users on that, so if it's easy, let's get this clean.

**Comment by mkllnk** [comment]
Oh, I solved that with #845.
