### ISSUE TITLE
[current master] Darkswarm stylesheet is not being loaded correctly

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8760]
## Description

On current [master](https://github.com/openfoodfoundation/openfoodnetwork/commit/e1849e5fb6cfa5a374f94f9267e87b9eea3e4f3a), it seems darkswarm stylesheet is not being loaded correctly. 

## Expected Behavior

Pages should render as before.

## Actual Behaviour

Pages are not rendering correctly.

## Steps to Reproduce

1. Stage [master](https://github.com/openfoodfoundation/openfoodnetwork/commit/e1849e5fb6cfa5a374f94f9267e87b9eea3e4f3a)
2. Visit the homepage.

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/b4ca8c85-8e67-4560-a2de-485714adad4a)

## Your Environment

* Version used: after commit 1cbb0d8bbd8ee5d18405cf15c2e0992e336436e8
* Browser name and version: all
* Operating System and version (desktop or mobile): all

**Comment by Matt-Yorkley** [comment]
Hmmm... it's only on UK. `master` looks fine on French Staging for example.

**Comment by Matt-Yorkley** [comment]
Seems like it's fixed now..? Something weird happened with Puma, but I can't tell what exactly.

**Comment by filipefurtad0** [comment]
Yes, all seems good now :shrug: 
Closing :+1:
