### ISSUE TITLE
[Split Checkout] Terms and Conditions

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#8765]
Showing the links to terms and conditions files and accepting them (for the instance and the hub) in the summary step of the split checkout needs some more work and improvements in the test coverage.

There's quite a lot of different combinations of scenarios, [outlined here](https://github.com/openfoodfoundation/openfoodnetwork/pull/8653#issuecomment-1016423660) by @filipefurtad0

**Comment by RachL** [comment]
@Matt-Yorkley just to be sure, this issue is about improving test coverage, correct?

**Comment by Matt-Yorkley** [comment]
Nope, there's a couple of things that are not working correctly. It's described here: https://github.com/openfoodfoundation/openfoodnetwork/pull/8653#issuecomment-1016423660

**Comment by RachL** [comment]
@Matt-Yorkley at delivery circle meeting, the team was saying that you might be in the best position to finish this one. Are you happy to take this one on?

**Comment by Matt-Yorkley** [comment]
Sure :+1:
