### ISSUE TITLE
[Spike] Finding a WYSIWYG editor for our text fields

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8768]
## Description

See https://github.com/openfoodfoundation/wishlist/issues/63 but also https://community.openfoodnetwork.org/t/using-hyperlinks-in-product-descriptions/1546

The aim of this issue is to benchmark which existing text editor could be used in order to:

- Easily add/change text display (bold, italic, size, bullet points..)
- add/edit hyperlinks
- Embed code (e.g. a video or a newsletter subscription box)
- Supports Markdown?

The gem that would be used needs to be well maintained;

## Acceptance Criteria & Tests

This spike is a papercut. the spike is considered complete when:

- a list of potential tools have been found (like https://trix-editor.org/)
- for each tools a benchmark of the above criteria are analyzed
- the spike is able to conclude on the best possible approach to solve the need
- an estimation of the time needed is done (especially if it can be done as a papercut / good first issue)

**Comment by apricot12** [comment]
I've written up something [here](https://docs.google.com/document/d/1EPg8EP6dCK9NGDIvADQIcLM9GRErz8Jsgdu1j-JccHI/edit?usp=sharing). I'm not sure if it's good so please do comment with anything I could add to improve it,

**Comment by jibees** [comment]
I'd be happy if we choose trix-editor.

**Comment by mkllnk** [comment]
Yes, Trix looks great. Development isn't super active but it looks quite mature.

**Comment by RachL** [comment]
closing in favor of https://github.com/openfoodfoundation/wishlist/issues/63 for the next steps.
