### ISSUE TITLE
[Split Checkout] Random behavior when activating split checkout for one user only

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8769]
## Description

Not sure if related to split checkout or feature toggling/flipper:
Some weird behavior is being observed if the split checkout feature is being activated for specific actors only.

## Expected Behavior

The rendered checkout page should be reproducible.

## Actual Behaviour

The rendered checkout page _sometimes_ displays the old checkout, _sometimes_ the split checkout.

## Steps to Reproduce

1. Activate the feature using the syntax `Spree::User;<id>`
2. Keep it `enabled for 0% of actors`
3. Log in into the account of the user
4. Add some items to the cart and visit `/checkout`
5. Refresh the page several times

6. Repeat for a `guest` user.

I think it would make sense that `enabled for 100% of actors` should be used instead, so, a way to test this is also to:
7. Repeat the procedures above with the setting `enabled for 100% of actors`

## Animated Gif/Screenshot

![Peek 2022-01-20 15-06.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/16c55a5f-07df-4cec-b844-146e8fc89342)

## Workaround

None needed for now - eventually relevant for rolling out this feature.

## Your Environment

* Version used: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/3265
* Browser name and version: Firefox, Chromium
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by Matt-Yorkley** [comment]
Possibly fixed here: https://github.com/openfoodfoundation/openfoodnetwork/pull/8758/commits/27001a5c5556db40731379e895558a77d70cdfd5

**Comment by jibees** [comment]
Seems to be a cache issue.
**Initial conditions** 
 - _User_1_ is connected and have access to split checkout via the interface `Spree::User;1`, as seen on screenshot below.
 - _Guest_ is not connected, and therefore have no access to the Split checkout.

**How to reproduce**
 - With _User_1_, prepare a cart and proceed to checkout. See that `/checkout/details` is the split checkout. OK
 - With _Guest_, prepare a cart and proceed to checkout. See that `/checkout/details` is the split checkout. NOK.
 - Put a `byebug` into `SplitCheckoutConstraint#matches`, and refresh `/checkout/details` with _Guest_. See that `/checkout/details` is _not_ the split checkout. OK, but WTF.
 - Remove the `debug` keyword, renew the operation. Confirm that _Guest_ only see the old checkout. (seems to be) OK.
 - Refresh the `/checkout/details` for _User_1_. See that he see the split checkout. (finally?) OK
 - And then, refresh the `/checkout/details` for _Guest_. See that he see the split checkout. NOK, WTF. 

Cache issue?


_Screenshot_1_
<img width="606" alt="Capture d’écran 2022-02-11 à 09 42 31" src="https://user-images.githubusercontent.com/296452/153561097-3afc51fc-f2bf-48a9-9a8c-d3969b66f730.png">

**Comment by jibees** [comment]
Debug

With _User_1_: 
```
request.env['warden'].user #<Spree::User:0x00007f954d7cabe8>
@spree_current_user #<Spree::User:0x00007f95675f94f8>
```
and then with _Guest_: 
```
request.env['warden'].user 
@spree_current_user #<Spree::User:0x00007f95675f94f8>
```

The previous (ie. the _User_1_) is stored in the `@spree_current_user` variable...

**Comment by Matt-Yorkley** [comment]
Nice debugging! I think the issue is that memoizing the value here is a bad idea. We can try it like this:
```diff
def matches?(request)
--   Flipper.enabled? :split_checkout, current_user(request)
++   Flipper.enabled? :split_checkout, request.env['warden'].user
end
--
-- def current_user(request)
--   @spree_current_user ||= request.env['warden'].user
-- end
```

**Comment by jibees** [comment]
Yep, that's exactly what i'm going to commit ;) Thanks! 🙏
