### ISSUE TITLE
Shop scrolls to shops list automatically

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#877]
There is a feature on the shops page that is annoying me. If you are logged in, the shops page scrolls to the beginning of the shop list automatically. The idea is that customers don't need to see the banner with the explanation text, they go straight to the shops. But if you scroll further down and reload the page, the same feature takes you up to the beginning of the list again. You loose the position within the page which is annoying me.

Maybe the scroll feature could check if the user has scrolled down already? Otherwise I would vote for getting rid of that feature. But that's a detail that can lead to a long discussions about how the shops list should look like.

**Comment by lin-d-hop** [comment]
Not well described

#gitcull2021
