### ISSUE TITLE
Uploading a product import file with empty unit type fails without any clue on the UI

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8773]
## Description

Uploading a file and forgetting to fill unit_type and variant_unit_name leads to a fail after just 2 sec but the user does not know it.

## Expected Behavior

Show an error on the UI (same model than other product import error)

## Actual Behaviour

User see this:

![image](https://user-images.githubusercontent.com/6525576/150553329-b2a651a0-aad7-4127-a907-508fb79d6914.png)

console (no network errors)

![image](https://user-images.githubusercontent.com/6525576/150553403-f757a550-64f2-4665-ae75-54d49da5cb5c.png)

## Steps to Reproduce

1. Create a file in order to **update** an existing product and leave both unit_type and variant unit_name empty
2. :boom:

## Workaround

Fill on of the 2 fields

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.1.13
* Browser name and version: All
* Operating System and version (desktop or mobile): desktop

**Comment by SarvarKh** [comment]
Hi @RachL,
I left the animation below showing the steps I followed to reproduce this issue unsuccessfully.

I didn't fill `unit_type` and filled `variant_unit_name`.
I also tried doing the opposite by filling `unit_type` with `weight (kg)` and leaving `variant_unit_name` empty, but got an validation error as incorrect `unit_type` input.

Could you advise how I can reproduce this issue a bit more? thanks

![upload-file_2](https://user-images.githubusercontent.com/60043698/150687196-9e8fcc4d-2fba-418e-9bf7-b4b1891ce894.gif)

**Comment by RachL** [comment]
hello @SarvarKh have you tried leaving _both_ fields empty?

**Comment by SarvarKh** [comment]
I hadn't tried it, and the issue occurred when both fields were empty. The display just stuck and didn't show any flash notice about the occurred error. Thanks.

![test_2](https://user-images.githubusercontent.com/60043698/150780869-8eae10dc-4128-4928-82be-969ad93a4103.gif)

**Comment by SarvarKh** [comment]
Ok, QC Work)
This issue didn't not occur:
1. When both `unit_type` and `variant_unit_name` are empty;
2. When `unit_type` is empty;
3. When `variant_unit_name` is empty;
![test_3](https://user-images.githubusercontent.com/60043698/150841059-3db8ffd6-9609-47d6-8a37-7e8ef6a0534a.gif)

**Comment by SarvarKh** [comment]
The issue only appears when a product is uploaded by importing successfully, and the same product (with the same name) is re-uploaded with `unit_type` and `variant_unit_name` empty fields🤔

![test_4](https://user-images.githubusercontent.com/60043698/150841624-a03a07c1-caed-4f10-a325-1af912c30498.gif)

**Comment by RachL** [comment]
Nice findings @SarvarKh !

**Comment by SarvarKh** [comment]
It is more like a front-end issue related to the async calling in `import_form_contoller.js.coffee` where I would appreciate someone's help)

In terms of model validations, adding this code into `product_field_errors` [method](https://github.com/SarvarKh/openfoodnetwork/blob/a9d4233af9ad751ca02f8204d0e14662a9a318ec/app/models/product_import/entry_validator.rb#L364) should have validated and returned an error (`cannot be updated on existing products via product import`) because the Rails.logger is returning as expected on the rails s terminal: 
<img width="1115" alt="Screen Shot 2022-01-27 at 00 10 48" src="https://user-images.githubusercontent.com/60043698/151230487-9046c8f2-8879-45de-960c-1d618a256de0.png">


```
      if entry.name == existing_product.name
        # Rails.logger.debug "....................Debuging..................... #{entry.name}, #{existing_product.name}"
        mark_as_invalid(entry, attribute: "name",
                              error: I18n.t('admin.product_import.model.not_updatable'))
      end
```

**Comment by mkllnk** [comment]
Okay, so it looks like we are sending the error to the browser but we are not displaying it. Are you familiar with AngularJS?

I would check:

- Is the error sent to the browser? Check network console and look at the JSON data.
- Is the attributes listed in the view? https://github.com/openfoodfoundation/openfoodnetwork/blob/75395f6f297c5acaae2218b84eb1e2c55d34fd29/app/views/admin/product_import/_entries_table.html.haml#L13-L14
- Is the error present when the view asks for it? https://github.com/openfoodfoundation/openfoodnetwork/blob/75395f6f297c5acaae2218b84eb1e2c55d34fd29/app/assets/javascripts/admin/product_import/controllers/import_feedback.js.coffee#L9-L10

I'm not 100% sure about my references in the last two dot points. That was only a very quick code search but it looks like errors are handled there.

**Comment by SarvarKh** [comment]
I didn't use Angular JS (only React&Redux with JS itself).

Not much progress, but just FYI:
Concerning the 1st point: it is returning an error to the network console, but not what is expected.

![Screen Shot 2022-01-29 at 11 39 10 (2)](https://user-images.githubusercontent.com/60043698/151650822-f50536f6-1e1b-4582-9ffd-def41792d2ad.png)

**Comment by SarvarKh** [comment]
Sorry if I am irritating with my questions) thought this gif file might be useful.

![test_5](https://user-images.githubusercontent.com/60043698/151672486-c3895100-543d-4cd0-b7f9-f9bea60cc15b.gif)

**Comment by mkllnk** [comment]
I'm wondering if this is the underlying issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/6096

**Comment by SarvarKh** [comment]
> I'm wondering if this is the underlying issue: #6096

Async call in `.catch` is returning undefined <= product_import controller is rendering whole HTML error response, instead of JSON. So, I believe it does relate to the #6096 

There is an alternative [solution](https://github.com/openfoodfoundation/openfoodnetwork/pull/8876), but not ideal.
