### ISSUE TITLE
Strange strings in Transifex

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#878]
I just translated in French the new strings in Transifex, I didn't translate some that looked strange in English... some had a ^ before, and others looked more like "entrance key" than strings to translate... can someone tell me if it's normal and I can go ahead? @blancnic ? @mkllnk ?
Thanks :-)

![image](https://cloud.githubusercontent.com/assets/8135376/14261085/61186cba-faaf-11e5-87a8-824dfaa6d5fc.png)

**Comment by myriamboure** [comment]
Ping @sigmundpetersen for info

**Comment by mkllnk** [comment]
Thank you. Some of these translations are really wrong. @elf-pavlik Can you fix these? There are some function calls in the translated strings. And some contain `&amp;`, but the key doesn't end with `_html` to mark HTML content.

@myriamboure The entries starting with `^` are correct. They are displayed under the thing they are referring to. The `^` character is like an arrow to the top.

**Comment by myriamboure** [comment]
Ping @blancnic maybe you will know how to solve the wrong translations issues while Pavlik is on his Vipassana course ;-) I translated the ^ ones.

**Comment by blancnic** [comment]
Ok what's the point? Do you need I check If translations with html encodind are using in _html file or not?

**Comment by mkllnk** [comment]
@blancnic Yes. Rails escapes all characters by default. If we need to use HTML within a translation, then the key needs to end in `_html`. It also looks like some Javascript function calls were substituted by translation strings. Would be good if you can revert that.

**Comment by elf-pavlik** [comment]
back online! @blancnic did you make some progress on this issue or should i take a look at it during next days?

**Comment by blancnic** [comment]
add_and_manage_products: "Add &amp; manage products"
add_and_manage_order_cycles: "Add &amp; manage order cycles"
-> /app/views/spree/admin/overview/single_enterprise_dashboard.html.haml
@elf-pavlik :We can add _html in key or revert &amp; as you want

**Comment by mkllnk** [comment]
I would prefer using `&` instead of `&amp;`. You don't need the suffix _html and the code is safer for translators that don't know HTML.

**Comment by elf-pavlik** [comment]
@mkllnk it looks like you added the 'accounts administration distributor' string in https://github.com/openfoodfoundation/openfoodnetwork/commit/fa8c3d65dc812a0ff4ccfda1631b2cdb867654f6#diff-2762c9737fdd8da2f25c74623499b30cR10 without adding translation to it. Later Julien added it to en.yml in https://github.com/openfoodfoundation/openfoodnetwork/commit/8fa293f561c602552b8dd6a6984e7d60900925e5#diff-37c9b835927e3c363588f172de9bb6faR725

I will create PR for all the rest once all the tests I run now on Travis pass...

**Comment by elf-pavlik** [comment]
this commit has all the changes: https://github.com/elf-pavlik/openfoodnetwork/commit/f15e9480854cfc6ad0d9f7833576e57aeec6c4df

all tests pass: https://travis-ci.org/elf-pavlik/openfoodnetwork/builds/123176291

do you want PR or you can just pick it from the branch on my fork?

**Comment by mkllnk** [comment]
We merged these changes, but they will not appear in Transifex until the next release in two weeks.
