### ISSUE TITLE
[API] Finalise Customer Endpoint

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8788]
## Description

FR, UK and AU instances need to be able to create, find and update Customers via the API.

### Request Params
Nothing additional to the standard rq queries

### Response Attributes
Id - integer
Enterprise_id - integer
First_name - string
Last_name - string
Code - string
Email - string
Allow_charges - binary (NO CREATE OR UPDATE - force users to use the UI. False on create)
Tags - array of strings
Billing_address - address object. I believe we can use something already existing here but check in with product if needed.
Shipping_address - address object. I believe we can use something already existing here but check in with product if needed.
Terms_and_conditions_accepted_at - datetime (NO CREATE OR UPDATE - force users to use the UI. False on create.)

NOTE This field will not be added in the first iteration of this endpoint as there are significant performance considerations
Customer_balance - double (ON SHOW ONLY) (NO CREATE OR UPDATE)

### Scoping
This endpoint will be accessible to Enterprises only - authentication is granted to any enterprises the user owns or manages.
This endpoint will not have a scope for shoppers/non-enterprise users.
This endpoint will list all customers connected to enterprises that are owned or managed by the authenticated user

### Acceptance Criteria

1. Developer to provide a full list of RQ params that can be used. 
2. Create: Tester to confirm that customers created via the endpoint are correct, including all fields. Any fields that should not be creatable via API should be handled correctly.
3. Read: Tester to ensure RQ params filter correctly and Rs attributes are correct
4. Update: Tester to ensure that all fields update correctly. Any fields that should not be creatable via API should not change.
5. Delete: Tester to ensure deletes are handled correctly. Deletes should be singular via ID. No bulk deleting.
6. Tester to confirm scope. An enterprise user should see all and only of the customers related to enterprises they own or manage. No CRUD actions should be possible for customers relating enterprises they do not manage.
7. Product to confirm documentation is correct and sufficient. Improve if necessary.
8. Feature exists behind a feature toggle

**Comment by mkllnk** [comment]
Just keeping track of my work in progress:

### Attributes:

- [x] Id - integer
- [x] Enterprise_id - integer
- [x] First_name - string
- [x] Last_name - string
- [x] Code - string
- [x] Email - string
- [x] Allow_charges - binary (NO CREATE OR UPDATE - force users to use the UI. False on create)
- [ ] Tags - array of strings
- [ ] Billing_address - address object. I believe we can use something already existing here but check in with product if needed.
- [ ] Shipping_address - address object. I believe we can use something already existing here but check in with product if needed.
- [x] Terms_and_conditions_accepted_at - datetime (NO CREATE OR UPDATE - force users to use the UI. False on create.)

Other:

- [ ] Feature toggle

**Comment by mkllnk** [comment]
> Billing_address - address object. I believe we can use something already existing here but check in with product if needed.
> Shipping_address - address object. I believe we can use something already existing here but check in with product if needed.

Every customer record has a link to a billing address and a shipping address. The easiest would be to just have the address ids in the response but I think that you want the whole object.

If we include the whole object on every request, it doesn't scale that well, especially when listing customers. But I think that JSON:API's approach to this is to include a link to the address by default and include the whole object if requested, for example with `/api/v1/customers/1?include=billing_address`.

Does that sound right?

This could take me another day or two.
