### ISSUE TITLE
Entreprise confirmation links is badly transformed in Firefox and prevent to validate the entreprise.

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#879]
We have some issues in France with the validation emails, we have quite a lot of feedback from people who get "security issues" messages when clicking on the link to validate an enterprise.
The confirmation email contains a link with http, but Firefox convert the link in https, so the SSL certificate (Let's encrypt) is not valid.
This issue doesn't happen on Google Chrome or IE apparently.
Gilles doesn't know how to solve this issue... any idea? Maybe @pmackay I think you have some experience with Let's encrypt?

**Comment by pmackay** [comment]
@mkllnk have you used Let's Encrypt recently? Can you help?

**Comment by myriamboure** [comment]
I know @gnollet did something on it, do you think the issue is solved? What did you do exactly?

**Comment by gnollet** [comment]
Hi, 
We used Let's Encrypt and the certificate is OK.
The confirmation email contains some links and we use Sendgrid to send email. Sendgrid has a function to track links on emails and this function use redirect links to do tracking. I disabled this function on Sendgrid, then I think the issue is solved.

**Comment by myriamboure** [comment]
Ok so I close the issue :-)

**Comment by mkllnk** [comment]
I have a little bit of experience with letsencrypt. Most browsers accept the certificates. There is normally no problem with Firefox either. One big exception is Windows XP. But there is nothing you can do about that.

But it seems that the problem where the redirect links of Sendgrid. I don't think that letsencrypt has a role in this.
