### ISSUE TITLE
Display "only X left" in shopfront when there are less than or 3 units of stock left

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8790]
## Description

Related wishlist: https://github.com/openfoodfoundation/wishlist/issues/146

**- As a:** enterprise user
**- On page:** shopfront only => **cart page remains the same**
**- I want to be able to do:** Activate the ability for the shopper to see that 3 product variant are left or less.

The number 3 will be for now hardcoded: no possibility to change it. We can create a superadmin feature to change this number in a later papercut.

To activate the feature, an enterprise user needs to go to their shop preferences and see a new radio button called `SEE PRODUCT STOCK`

What's this? text : `Allows the shopper to see when there is limited availability on products in your shopfront. Shoppers will see a message when there are 3 units or fewer remaining.`.

Mockup: https://design.penpot.app/#/view/41afef30-7d1f-11ec-9ea7-96385a0e391f?page-id=e586bdc1-acd0-11eb-bb49-81aaa3a367f9&index=0&share-id=64c46680-7d3e-11ec-a93c-e5d362d27ee9

By default the radio button should be on "Disabled".

We should take the opportunity of this issue to fix the alignment of the guest orders radio buttons:
![image](https://user-images.githubusercontent.com/6525576/150841728-7e863f6e-a971-4536-9e3c-84b172097698.png)

## Acceptance Criteria & Tests

*Scenario 1 : the feature is activated by shopfront manager*

1. Log in as enterprise with shopfront
2. Check the feature is disabled by default
3. Check the alignment issue we currently have with the radio button is fixed
4. Activate the feature
5. Check that on demand variant aren't showing any message (current behavior isn't changed for on demand variants)
6. Check that all variant with on_hand value being 3 or less are showing this message to either a guest shopper or a loggedin one: 

![image](https://user-images.githubusercontent.com/6525576/150839896-0040b31c-db12-40d6-ab7c-e33d8db5905f.png)

We use the same font size and position as the "in cart" message, **the only difference is the color which should be #E54E47**.

7. One the shopper starts to add items to the cart, the message disappear and the "in cart message" is displayed. The "+" sign get disabled once the shopper's reached the stock limit (same current behavior)

*Scenario 2 : the feature stays disabled*

1. Log in as enterprise with shopfront
2. Check the feature is disabled by default
3. Check the alignment issue we currently have with the radio button is fixed
4. Check that on demand variant aren't showing any message (current behavior isn't changed for on demand variants)
5. Check that no messages appear on the shopfront for variants with 3 on_hand value or less (current behavior isn't changed)

**Comment by filipefurtad0** [comment]
Hey @RachL , question on this one: should this also apply to products which can be ordered in bulk?

**Comment by RachL** [comment]
@filipefurtad0 haha 🙈 I must confess I don't know how on_hand values are handled on bulk products.... did you try it? I will have a go but in any case I guess it would be another papercut. I'm not sure how to handle it in terms of design yet.

**Comment by filipefurtad0** [comment]
I've tried it when testing #8841 - it does not change the behavior on bulk items, so usual stock restrictions apply.
