### ISSUE TITLE
Remove backup name column from customers table

### ISSUE THREAD

**Issue by pacodelaluna** [openfoodfoundation/openfoodnetwork#8835]
### What we should change and why (this is tech debt)
We ~~renamed the `name` column as `backup_name`~~ kept the `name` column on `customers` table in case of data issue during the migration.

Now that the migration has completed successfully, we can remove the old column from the database.

### Context
Related to https://github.com/openfoodfoundation/openfoodnetwork/pull/8763.

### Impact and timeline
This is cleaning the `customers` table by removing unused data.

**Comment by nicogaldamez** [comment]
Hey there! 

If this is still pending, I'd be happy to help with this simple task. Once I understand the codebase better, I'm open to tackling more difficult issues.

**Comment by RachL** [comment]
ping @openfoodfoundation/developers ☝️

**Comment by mkllnk** [comment]
Yes, this is still an issue. Please provide two separate pull requests for this. The first one ignores the column in the model. You can then make sure all tests pass. After we deployed that one, we can merge a pull request that removes the column in a migration. That would be awesome, thank you!

**Comment by nicogaldamez** [comment]
I'm having a failing test (`spec/migrations/split_customer_names_spec`) that relates to the migration from name to `first_name` + `last_name`. If we're planning to remove the column that migration doesn't make sense. I'm not sure how you're used to proceed in these cases. Should I delete that file?

I’m having a failing test (`spec/migrations/split_customer_names_spec`) that relates to the migration from name to `first_name` + `last_name`. If we’re planning to remove the `name` column, that migration doesn’t make sense. I’m not sure how you usually handle these situations. Should I delete the test file?

Thanks

**Comment by dacook** [comment]
Yes, that sounds like a good idea 👍
