### ISSUE TITLE
Customer account debited twice 

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#8843]
## Description
R186663316 is a complete order on 876 shop on the 4th january 2022 (FR Prod) 
<img width="1386" alt="Capture d’écran 2022-02-07 à 15 36 09" src="https://user-images.githubusercontent.com/67476305/152808558-bc5ae9b5-95f2-4d3e-b61d-35ab9d718803.png">

Then, the customer account has been debited twice 

- Spree order ID : R186663316-YMP3B4MF
- Spree ordre ID : R760023678-5USVLBSV

The hub reimbursed manually one of the debits to the customer, from the Stripe application, on the 7th february

<img width="489" alt="Capture d’écran 2022-02-07 à 11 51 07" src="https://user-images.githubusercontent.com/67476305/152774420-82531106-22ab-478a-86f6-ce68fefb96d1.png">

Seems to be related to [8608](https://github.com/openfoodfoundation/openfoodnetwork/issues/8608) and [8618](https://github.com/openfoodfoundation/openfoodnetwork/issues/8618)
Note that these three cases are related to the same HUB manager

**Comment by lin-d-hop** [comment]
Always worth noting the server, since the person who works on this might not know where you are @Cecilia-Hn ;)
FR Prod
