### ISSUE TITLE
Order contains no line items - only adjustments

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8844]
## Description

Order R420586454 on UK Production appears to be an empty order with no line items.
However the order does contain the correct adjustments and order total for what the customer ordered.

According to the user the correct items appeared in reports as the order was correctly packed and delivered.

However the order itself appears to require that a refund of the full amount is required, despite the total still displaying correctly. This is messing up the balance and accounting processes for the hub.

Probably related to being completed with Paypal.

## Expected Behavior

Line items should appear. 
Order should not have a 'credit owing'

## Actual Behaviour

Order appears to have a 'credit owing' of the full order amount
No line items are appearing on the order

## Steps to Reproduce

1. Unknown. Seems to be impacting only this order
2.
3.
4.

## Animated Gif/Screenshot

![Screenshot from 2022-02-07 13-44-42](https://user-images.githubusercontent.com/8669848/152799850-8c386b9f-a43a-4cde-8884-3dfb7111a8f3.png)

## Severity

bug-s2: a non-critical feature is broken, no workaround
I am applying S2 in the hope we can:
a) Restore this order to a sensible state
b) Gain information on what happened

Unless there is a critical issue uncovered it is not important to fix the root cause of this issue as an S2 - we can downgrade for that.

## Your Environment

* Version used: UK Prod
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
@filipefurtad0 did you read the issue? Its not a stripe sca issue ;)

**Comment by filipefurtad0** [comment]
Sorry, my mix-up.
I'm not sure if somehow related but items were not appearing on the order [when out of stock](https://github.com/openfoodfoundatio/openfoodnetwork/issues/8178). Wonder if this OC closed on the 31st... Anyway, this has been [recently fixed](https://github.com/openfoodfoundation/openfoodnetwork/pull/8438) but the order was created/updated/completed just before this was deployed into production ([which was on the 01.02.2022](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1643723779170949)):

```
   id   | amount | order_id |         created_at         |         updated_at         | source_id |         source_type          | payment_method_id |   state   | response_code | avs_response | identifier | cvv_response_code | cvv_response_message |        captured_at         
--------+--------+----------+----------------------------+----------------------------+-----------+------------------------------+-------------------+-----------+---------------+--------------+------------+-------------------+----------------------+----------------------------
 429902 |  42.02 |  2308784 | 2022-01-31 09:03:19.636198 | 2022-01-31 09:03:23.096696 |    210594 | Spree::PaypalExpressCheckout |                 7 | completed |               |              | CMYCRHRE   |                   |                      | 2022-01-31 09:03:23.105361
(1 row)
```

**Comment by lin-d-hop** [comment]
Nice thoughts @filipefurtad0 
The OC was open until the 2nd at 9:30am
All 13 line items were in stock and delivered to the customer.

**Comment by lin-d-hop** [comment]
Note you can see all the line items in the origianl issue... just they are adjustments, rather than line items

**Comment by lin-d-hop** [comment]
Ok, I just made this order even worse. I added a line item so I could try adding a shipping method back in to see if that would fix things.

However it didn't. And now the Apple juice I added can't be removed from the order because it is the 'last item' on the order.
![Screenshot from 2022-02-09 13-33-25](https://user-images.githubusercontent.com/8669848/153211823-7a7493bc-97ff-4215-8580-47b62532373c.png)

Ah what a mess :facepalm:

**Comment by filipefurtad0** [comment]
Maybe a heads-up on this issue @lin-d-hop : These orders potentially break `/admin/reports/orders_and_distributors` reports... probably because they have `shipment state = none`...

**Comment by filipefurtad0** [comment]
The order does have a shipment:
```
   id   | tracking |    number    | cost | shipped_at | order_id | address_id |         created_at         |        updated_at        |  state  | stock_location_id | included_tax_total | additional_tax_total | adjustment_total 
--------+----------+--------------+------+------------+----------+------------+----------------------------+--------------------------+---------+-------------------+--------------------+----------------------+------------------
 417125 |          | H10087645525 | 0.00 |            |  2308784 |            | 2022-02-09 13:32:07.596705 | 2022-02-09 13:32:32.9324 | pending |                 1 |               0.00 |                 0.00 |             0.00
(1 row)
```
```

   id    |   number   | item_total | total |  state   | adjustment_total | user_id |         created_at         |         updated_at         |        completed_at        | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |             email             | special_instructions | distributor_id | currency | last_ip_address | order_cycle_id | customer_id | created_by_id | included_tax_total | additional_tax_total 
---------+------------+------------+-------+----------+------------------+---------+----------------------------+----------------------------+----------------------------+-----------------+-----------------+---------------+----------------+---------------+-------------------------------+----------------------+----------------+----------+-----------------+----------------+-------------+---------------+--------------------+----------------------
 2308784 | R420586454 |      38.08 | 45.22 | complete |             7.14 |  201478 | 2022-01-24 11:30:26.738293 | 2022-02-09 13:32:32.941567 | 2022-01-31 09:03:23.129574 |          888541 |          888542 |         42.02 | pending        | balance_due   |     <hiddenhidden>            |                      |            160 | GBP      | 86.129.43.189   |         210637 |        5353 |        201478 |               0.00 |                 0.00
(1 row)

```
So it seems the order now has a shipment, and it is `pending`. But this makes sense, because the only exiting payment (42.02) does not cover the order total (45.22)... so, `balance_due` state.

This seems to have changed, since you've reported @lin-d-hop. How does it look now in the UI? Can you add additional payments? Does clicking Update and Recalculate fees change something?

**Comment by lin-d-hop** [comment]
@filipefurtad0 
The order is missing its line items. All of them. I feel like this discussion has gone on a huge tangent from the fundamental problem here.

I'm closing this issue. Its been sitting here for so long and the user has worked around in their accounts that this order is just a broken mess.
