### ISSUE TITLE
[Stripe SCA] Critical issues on Payments

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8846]
This issue gathers critical payment issues related to Stripe SCA.

Note to support teams on OFN:
The [change on EU legislation](https://stripe.com/en-pt/connect/eu-guide) has triggered recent changes on how Stripe SCA is implemented. We have been experiencing some issues on this regard, which we aim to fix on a weekly basis.

We're deploying [another fix](https://github.com/openfoodfoundation/openfoodnetwork/pull/8807) which hopefully prevents some of these issues from reocurring (today, 8.2.2022).

**Comment by RachL** [comment]
this is an epic, but no issues related. So closing.

**Comment by filipefurtad0** [comment]
I've spotted a recent issue on Stripe SCA payments on the backoffice recently, and it seems we had another one here - maybe good to group them. Should we re-open this or create a new epic?
