### ISSUE TITLE
Tagging visualisation

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#886]

**Comment by mkllnk** [comment]
On the customers page /admin/customers you can select a hub and get a list of customers. Each customer has an input field for tags.

1. Tags with associated rules should have a different markup.
2. While typing, rule-tags should pop up as suggestions.
3. The suggested rule tags should show how many rules apply / which rules apply.

Nice to have:

* Hovering over a tag should display a little note saying if rules apply and if yes how many or even what kind of rules.
*  The heading "Tags" should link to the hub's tags tab. This needs a tab navigation on the hub edit page.

**Comment by sstead** [comment]
Testing notes April 29. 
1 and 2 are working. 
3 is working, but we're only shown how many rules apply, not which rules apply
Nice to have 1 is working, again, just showing how many rules apply.

**Comment by daniellemoorhead** [comment]
What was done:
1. Tags with associated rules should have a different markup.
2. While typing, rule-tags should pop up as suggestions.
3. The suggested rule tags should show how many rules apply.
4. Hovering over a tag should display a little note saying if rules apply.
