### ISSUE TITLE
Uploading product image fails

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#8877]
## Description

One Australian user could not upload a product image. This was observed in Bugsnag and the details are not known yet.

## Expected Behavior

Uploading an image always works.

## Actual Behaviour

Uploading failed for one user. More may be affected.

## Steps to Reproduce

1. ???
2.
3.
4.

## Severity

Unknown.

## Your Environment

* Version used: v4.1.18
* Browser name and version:
* Operating System and version (desktop or mobile):

## Error in OpenFoodNetwork Aus

**ArgumentError** in **spree/admin/images#create**
wrong number of arguments (given 3, expected 1..2)

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/620747d48a11c300088f60b4?event_id=6207492e00903d3f01f60000&i=gh&m=ci)

## Stacktrace

    app/controllers/spree/admin/images_controller.rb:28 - create
    lib/session_cookie_upgrader.rb:19 - call

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/620747d48a11c300088f60b4?event_id=6207492e00903d3f01f60000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by jibees** [comment]
Related to #8851 ?

**Comment by mkllnk** [comment]
We asked the user what happened. They said that they switched their computer off and on again and then everything worked. :smile:

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**ArgumentError** in **admin/enterprises#update**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/620f1217395d4b000841cb56?event_id=621706d50091564dae450000&i=gh&m=li)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ArgumentError** in **admin/enterprises#update**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/620f1217395d4b000841cb56?event_id=626ab9dd0093ed7f0d0c0000&i=gh&m=ra)
