### ISSUE TITLE
Remove bogus payment method

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#8886]
### What we should change and why (this is tech debt)
This payment method is never used, and is unsupported (part of the Spree code). Remove it. 

### Context
This came up in split checkout

### Impact and timeline
This work should start after Split Checkout is in production and is running (without toggling) and at the same time when cleaning all the _old-checkout_ code.

**Comment by mkllnk** [comment]
A lot of specs depend on this method. We need to replace those with Stripe or Paypal tests. That work would be much easier after adding VCR:
- #7767

**Comment by macanudo527** [comment]
I'll look into how feasible this is now.
