### ISSUE TITLE
Login messages not displayed for unconfirmed users

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8888]
## Description

_Updated_

Logging in to an unconfirmed account does not display any message on the login modal (for some browsers). I think this is the related message `unconfirmed: "You have to confirm your account before continuing." `.

## Expected Behavior

The modal messages for unconfirmed users should appear.

## Actual Behaviour

The modal messages are not appearing for different browsers.

## Steps to Reproduce

1. Create a user account but don't confirm it (through the received email).
2. Try to log in (the password needs to be correct)
3. See that no modal is being shown.

## Animated Gif/Screenshot

Some console errors are seen on Ubuntu 20.04 Chrome 98:
![image](https://user-images.githubusercontent.com/49817236/153905970-83ad9a8a-552d-41c3-8a8c-3f1d5d219acc.png)

## Workaround

It can be confusing for the user if no message appears at all.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v14.1.17
* Browser name and version: different versions of Chrome/Firefox
* Operating System and version (desktop or mobile): so far observed only on Ubuntu, probably affecting others

## Possible Fix

Maybe related to https://github.com/openfoodfoundation/openfoodnetwork/pull/8808?

**Comment by Matt-Yorkley** [comment]
My only guess is that there's some kind of weird HTTP caching going on. Could you try in a private browsing window or try deleting history/cached data and see if it goes away? I can't replicate on Ubuntu with Fireox or Chrome.

**Comment by Matt-Yorkley** [comment]
Otherwise; that image indicates there are multiple errors. Could you scroll up and show me the first ones in the list?

**Comment by filipefurtad0** [comment]
Seems to be a caching issue indeed, running on the private window works:

![Peek 2022-02-14 17-39](https://user-images.githubusercontent.com/49817236/153917397-bdcf9979-a59f-42e6-9c64-4fe968fdcb54.gif)


The two errors shown before appear each time Login is clicked:

![Peek 2022-02-14 17-38](https://user-images.githubusercontent.com/49817236/153917377-1f4db8b3-33ed-4201-92a7-f139c3995133.gif)

**Comment by Matt-Yorkley** [comment]
Aha! I can replicate it with an unconfirmed email but not with a wrong password. Okay...

**Comment by filipefurtad0** [comment]
Ahh. Yes indeed, I see that now as well - the pass needs to be correct - updating the issue :+1:
