### ISSUE TITLE
Be able to make an enterprise invisible on other enterprises profiles

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#8896]
## Description

As a hub or producer I want to be able to be invisible. Currently I can hide from the map and /shops page, but even when hidden I am still linked to from the profiles of other hubs have enterprise relationships with. In the cases in which a shop is hidden to provide additional price points etc this is problematic.

## Acceptance Criteria & Tests

On the Enterprise Settings -> Shop Preferences page we want to change the option that currently looks like this:
![Screenshot from 2022-02-16 13-27-57](https://user-images.githubusercontent.com/8669848/154274517-4b0a2453-7f41-4d18-a001-b3c69902ee38.png)

To have 3 options:
1. Public
2. Hide on map, search and listings
3. Hide all references

The Tooltip should now read:
Shops can be 1. publicly visible, appearing on the OFN map and listings; 2. Hidden on maps and listings but referenced by other shops and linked in their profile or 3. Completely hidden. Note that the shop will still be accessible open shopfronts with a direct link.

1. 'Public' shopfronts should be visible on the /shops page, /map
2. When 'Hide on map, search and listings' is chosen enterprises should not appear on the map or /shops page. If the appropriate enterprise settings are set up the enterprise can still be referenced from the 
3. When 'Hide all references' is selected the enterprise should not appear on the map or shops page, and should not be referenced from the profiles of enterprises they have enterprise permissions with
4. An open OC should still be able to be accessed via a direct link.
5. Modifications to Groups functionality are beyond the scope of this PR.

**Comment by georgethoppil** [comment]
@jaycmb @RachL Just want to confirm something with regards to point 3 where it mentions
> should not be referenced from the profiles of enterprises they have enterprise permissions with

I take it that this is mentioning the storefront profiles of the enterprise and we would like to hide any mention of these shops that are invisible ex. in the Producers tab. Is this correct? Are there any other areas where we would like to hide the invisible shops?

**Comment by RachL** [comment]
@georgethoppil yes producer tab only for now.

These hubs also appear on group pages, but as the issue description says, this is out of scope for now :+1:
