### ISSUE TITLE
No error message to warn customer they don't have a default card set when they authorise payments for a subscription

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#8897]
## Description

Customer has a credit/debit card registered with their OFN account but none are set to 'default'.
They check the 'allow charges' box, log out and log back into find the box has become unchecked.
Hub can not set up a subscription for the customer.

## Expected Behavior

Customer ticks the 'allow charges?' box to set up their subscription.
The 'default' card toggle is not set.
A warning pops up that their request to save won't go through until they set their default card

=> don't allow the "allow charges" checkbox to be selected if no default card is set.

## Actual Behaviour

Customer ticks the 'allow charges?' box to set up their subscription.
The 'default' card toggle is not set.
The customer thinks they have completed their subscription set up, logs out.
Customer finds out later their subscription can't be processed.

## Steps to Reproduce

1. Log in as a customer with a subscription
2. Save your credit card and allow charges, but don't set the card to default
3. See the subscription is not going through

## Severity
bug-s4: it's annoying, but you can use it

papercut

**Comment by RachL** [comment]
@jibees can you select by default when there is only one? (that should be 90% of the cases). Then for the people who forgot to delete or actually have several cards, what about what Louise said in the expected behavior? Like you can't allow charges if no default card is selected?

**Comment by jibees** [comment]
@RachL 
Thanks for the answer. I think that: 
 - Mark as the default card if only one card,
 - do not allow to click on checkbox "Allow Charges to Default Card?" until no card is marked as default

should be enough.

**Comment by lin-d-hop** [comment]
Small correction:
- Mark as the default card if only one card :heavy_check_mark: 
- do not allow to click on checkbox "Allow Charges to Default Card?" **IF** no card is marked as default

**Comment by jibees** [comment]
The question is: should I delete angularjs of this page (widely used)?
if yes, this should be no more a papercut
if no, this should be a papercut

**Comment by RachL** [comment]
I think you've answered you own question? :) Let's keep it papercut :+1:
