### ISSUE TITLE
Admin Fee display in shopfront: displaying fee name instead of the type

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8899]
## Description
**- As a:** (enterprise user, super admin, user...) Shopper
**- On page:** (provide url of the page you want to modify. If not provide where will be created the new url and the name we want to give it) Shopfront
**- I want to be able to:** (specify the desired behavior) ee the name of enterprise fees specified by enterpise

Enterprise fees have 'types' associated with them:  - admin, sales, transport, packing, fundraising
This is a Spree legacy and doesn't have a reflection on taxes or functionality. It simply creates a point of confusion for users.

This issue is part of a 3part epic to remove these fee types.

Part 1. Removing them from the shopfront.
Currently the fee type is displayed in the shopfront within the 'pie chart' feature
![Screenshot from 2022-02-16 14-10-16](https://user-images.githubusercontent.com/8669848/154281942-c1414810-97bd-4aa3-86e7-06151e9d2f16.png)

Instead of the **fee types** these should have the **fee names** that have been entered here:
![Screenshot from 2022-02-16 14-15-49](https://user-images.githubusercontent.com/8669848/154282944-408feee0-5df5-45b3-a1c6-c4f618236501.png)

So from the image above the Pie Chart should now say '100% special' instead of 'Fundraising Fee' as it would say now.

## Acceptance Criteria & Tests

1. All types of fees should now display in the pie chart with the Fee Name instead.
2. Front end developer should take into consideration how the Fee Name length will render on different devices. If the name is too long it should be truncated with a ... to ensure it renders well. Any max should be noted in the issue fro additional testing.
3. 
4.

**Comment by SarvarKh** [comment]
Pie chart reflects price break_down with `fee_types` instead of `fee_names` through [price_breakdown.html.haml](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/templates/price_breakdown.html.haml).

So far, I couldn't find where `variant` variable in the above file is defined.
It must be quite simple, but I am new to Angular - I used React & Redux for the front-end.
FYI: I just bought a [course](https://www.udemy.com/course/the-complete-guide-to-angular-2/) to familiarize myself with Angular.js

Would appreciate your help🙏

**Comment by SarvarKh** [comment]
Ok, `variant` variable doesn't comprise fee names.
So, need to define and then display them.

<img width="1440" alt="Screen Shot 2022-02-23 at 09 21 29" src="https://user-images.githubusercontent.com/60043698/155261552-a82ada64-4df4-4679-b8ba-bfa941e1845d.png">

**Comment by RachL** [comment]
hello @apricot12 are you still working on this one?

**Comment by apricot12** [comment]
> hello @apricot12 are you still working on this one? 

Yes I start on this one today 🙂. Sorry I take a long time to get to the things I assigned.
