### ISSUE TITLE
Admin Fee display on invoice: displaying fee name instead of the type

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8904]
## Description
**- As a:** (enterprise user, super admin, user...) shopper
**- On page:** (provide url of the page you want to modify. If not provide where will be created the new url and the name we want to give it) invoice
**- I want to be able to:** (specify the desired behavior) see the name of the fee as it appeared in the shopfront

Enterprise fees have 'types' associated with them:  - admin, sales, transport, packing, fundraising
This is a Spree legacy and doesn't have a reflection on taxes or functionality. It simply creates a point of confusion for users.

This issue is part of a 3part epic to remove these fee types.

Part 1. Removing them from the invoice.
Currently the fee type is displayed on invoices
![Screenshot from 2022-02-16 14-27-12](https://user-images.githubusercontent.com/8669848/154285169-c624558e-19f5-4c01-ba9f-fdd852bfbf69.png)

Instead of the **fee types** these should have the **fee names** that have been entered here:
![Screenshot from 2022-02-16 14-15-49](https://user-images.githubusercontent.com/8669848/154282944-408feee0-5df5-45b3-a1c6-c4f618236501.png)

So from the image above the invoice should now say '100% special' instead of 'Fundraising Fee' as it would say now. 

Blocked by #8899 

## Acceptance Criteria & Tests

1. All types of fees should now display on invoices with the Fee Name instead.
2. 
3. 
4.

**Comment by lin-d-hop** [comment]
As per a chat in delivery train, can we spend an hour or so just documenting what the different fee types and groupings are?
It would be good to be able to document in the user guide how different types of fees are grouped and summarised on invoices. 

From there we might find that there are good tweaks we can make for transparency while not losing any clever grouping that has been done in the past to simplify invoices :)

**Comment by RachL** [comment]
The main target here is to remove fee types. Can we do this with keeping the grouping or is it too complex?

**Comment by lin-d-hop** [comment]
Now I've forgotten why we can't just put the Fee Name in the summary rows. Most enterprises do not have a lot of fees and we'll only be showing the fees that are not percentage based. To me it makes sense that we just use the Fee Name for all flat fees and then go ahead and remove the fee types.

Or maybe I am forgetting some detail...

**Comment by RachL** [comment]
@lin-d-hop we can. I was afraid this grouping was made on purpose because enterprises didn't want the list of fees. But let's do it then!

**Comment by lin-d-hop** [comment]
Maybe it was.... but I think it is now just opaque and unhelpful to group in this way, particularly as so many people use fees for discounts.

**Comment by jibees** [comment]
Not sure to understand, i'll try to sum up:

 When displaying order on page `/orders/R_ORDER_ID`, fees should be displayed as they are displayed in the admin section (ie. `/admin/orders/R_ORDER_ID/edit`), as then both displays are equivalent:
<img width="1041" alt="Capture d’écran 2022-07-22 à 16 18 22" src="https://user-images.githubusercontent.com/296452/180458796-a806a437-6c2d-4484-98ea-8ea56141967e.png">
<img width="539" alt="Capture d’écran 2022-07-22 à 16 19 21" src="https://user-images.githubusercontent.com/296452/180458983-2759840d-fa4d-46b2-abcb-04350a4b5e41.png">

And then, the displayed name should be the one that is set in the `/admin/enterprise_fees?enterprise_id=ENTERPRISE_ID` table:

<img width="1094" alt="Capture d’écran 2022-07-22 à 16 24 10" src="https://user-images.githubusercontent.com/296452/180460301-d10fa999-a86e-410e-b429-40006eda2bfd.png">

An finally, this should looks like:
<img width="655" alt="Capture d’écran 2022-07-22 à 16 41 14" src="https://user-images.githubusercontent.com/296452/180463516-5ca0b761-25bf-40ca-9be8-f79920365fa7.png">

Right?
