### ISSUE TITLE
Convert checkout alerts to flashes 

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#8905]
## Description
A user was stuck at checkout and reported she couldn't continue shopping or checkout,  and her screen was frozen.   I sent a series of screenshots to her showing the checkout error messages and 'update' button that appear when an item in the customer's cart goes out of stock.  She insisted she did not see these messages.   After back and forth we realized  her popup blocker was blocking these messages  - she couldn't see the messages and was stuck at checkout going nowhere.

We need to convert these alerts to flashes so that a popup blocker won't block them. 

## Step to reproduce the pop-up window

1.Set a stock level at a product at 2
2. Go to the store add 1 in the cart
3. Go to the cart and try to increase quantity to 3 (or whatever above 2)
4. See the pop-up message : this is the one we need to convert in flashes.

**Comment by Laurel16** [comment]
Hello! 

Is this issue still relevant? I tried to reproduce it with a pop up blocker without success. 
When I reduce the stock available of an item in my cart, I have an error message in a flash notice and text under the input. 

<img width="1389" alt="Capture d’écran 2022-11-14 à 14 33 36" src="https://user-images.githubusercontent.com/16537140/201729385-18afc526-f846-479e-a33f-5c606f9b3e7b.png">

Thank you verry much!

**Comment by tschumilas** [comment]
Its been a long time since I created this issue -  and I have not heard of it happening again.   I suggest we close it -  unless anyone else is still getting reports about this?

**Comment by Laurel16** [comment]
Thanks @tschumilas for your answer. 
Hello @RachL maybe this issue can be on file ?

**Comment by RachL** [comment]
@Laurel16 @tschumilas it took me a while to figure it out, but yes unfortunately the issue is still relevant.

Actually the way to reproduce the popup is by trying to _add_ quantities on the cart page and going _above_ the stock limitation : 

![image](https://user-images.githubusercontent.com/6525576/202268900-543d4cce-661d-487e-ad69-af64565287e1.png)

I will update the issue.

**Comment by RachL** [comment]
So in terms of design, I think we can follow the same design you have in your screenshot @Laurel16 but with the content of the popup currently - if it's doable of course.

**Comment by Laurel16** [comment]
Thank you very much @RachL for cheeking. I think the culprit is an angular alert. I'll try to figure out.
