### ISSUE TITLE
Remove Fee Types from the Platform

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8907]
## What is the problem we are solving 

Enterprise fees have 'types' associated with them: - admin, sales, transport, packing, fundraising
This is a Spree legacy and doesn't have a reflection on taxes or functionality. It simply creates a point of confusion for users.

## Success factors = expected outcome 

No more reference to Fee Types in shop, invoices or backoffice. 
Migration to remove from DB

**Comment by SarvarKh** [comment]
Let me check this one

**Comment by lin-d-hop** [comment]
@SarvarKh Sure thing. Just start with the first papercut, rather than the whole epic ;)
#8899
