### ISSUE TITLE
Add 'Balance' to Customer endpoint

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8909]
## Description

As reports offer a calculated balance at the specific moment the report was run, we want a way to calculate Balances at a scheduled time. This will enable hubs to reconcile based on dates which is currently impossible.

Customers have balances that are calculated by the app and displayed on the Customer screen.  It is also availabe in reports. To take balance at a scheduled time requires copying and pasting from the screen at a specific time or running a report at a specific time. 

This Balance information is currently not available on the API though other Customer information is.

## Acceptance criteria

Adding Customer Balance to /show and hiding behind a display_customer_balance param in /index

Customer_balance - double (ON SHOW ONLY) (NO CREATE OR UPDATE)

1. An enterprise user should see all and only of the customers related to enterprises they own or manage. No CRUD actions should be possible for customers relating enterprises they do not manage.

2. Create: Confirm that customers created via the endpoint are correct, including all fields. Any fields that should not be creatable via API should be handled correctly.
3. Read: Ensure RQ params filter correctly and Rs attributes are correct
4. Update: Ensure that all fields update correctly. Any fields that should not be creatable via API should not change.
5. Delete: Ensure deletes are handled correctly. Deletes should be singular via ID. No bulk deleting.

**Comment by RachL** [comment]
Performance issue has been addressed in customer endpoint spec.
