### ISSUE TITLE
Re-named taxons show in product lists but original names show in shopfront

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#8910]
## Description
I recently needed to add new taxons as super-admin in configuration.  On OFN-CAN we had a number of garbaged taxons named 'z'.  These were the result of early mistakes I made in configuration when I didn't know you can't delete taxons.

So I needed new taxons  and I renamed the 'z' to 'Seedlings - Vegetables'  for example.  I did this with 6 z taxons.  I've done this before and its worked.  And I'm slowly getting rid of my 'z' taxons this way.

I remaned these 6 taxons,  and used them with a product import of a large product list.  No errors on import.  The categories look correct in the product list.

But in the shop,  the categories from renamed taxons do not show as filters.  Instead the original taxon name shows in the shop.  They filter correctly - its just the new name doesn't show in the shop.

So product list category is:  Seedlings (Vegetables)  and category in the shop for this product is 'z' (the underlying taxon)

If I add new taxons,  they work fine.
Problem is with the renamed taxons.

 

## Expected Behavior
Taxons that are renamed   and are attached to products as categories,   should show in shop filters

## Actual Behaviour
Renamed  taxons are not showing as shop filters. 

## Steps to Reproduce
1. Rename an existing taxon,  and attach it to a product.   
2. Create an OC with the product
3. See that the  new (over-written) name shows in the product list dropdown.  But the  original name shows in the shop. 

See detailed step in this comment: openfoodfoundation/openfoodnetwork#8910

## Workaround
No workaround to fix this  -  issue is that the renamed taxons show i the product list.  Users are selecting them.  But then multiple 'z' s are showing in the shop.  I cannot delete.  I can only create new taxons.
 

## Severity
I think an s3 or s4 -  but its making OFN Can shops look pretty bad with all these 'z's showing up.

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by georgethoppil** [comment]
@filipefurtad0 and I quickly tested this out and it seems like we are able to edit the main taxonomy and changing the name. This is reflected to the storefront now. There is a separate issue that Filipe found where re-naming by clicking the rename function on the main taxonomy has no effect whatsoever. However, that seems like a different issue we are trying to solve here and should be separated out to a different ticket if it hasn't been done so

cc @tschumilas @lin-d-hop 

![Peek 2022-03-22 16-09](https://user-images.githubusercontent.com/45666083/159574678-64e483a4-d90d-48a9-a473-e6db2e33620a.gif)

**Comment by filipefurtad0** [comment]
Thanks @georgethoppil ,
I've opened #9031 on the broken "Rename" function.

I think we can close here :+1:
