### ISSUE TITLE
[Subscriptions] Color of "No Upcoming Order Cycle" warning should be red

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#8911]
The color of the "No Upcoming Order Cycle" warning when adding a variant without open or upcoming OC to a subscription should be red.

## Description

This is a warning that should be more obvious to the user.

@RachL discovered this when testing openfoodfoundation/openfoodnetwork#2733.

This used to work, so I suspect (not sure) that this is the offending commit, but I don't know why yet: https://github.com/openfoodfoundation/openfoodnetwork/pull/2733/commits/5992bba97b80afa7264763c5ba5a92d647ed2c4f

## Expected Behavior

The warning should be red.

## Actual Behavior

The warning is in regular text color.

## Steps to Reproduce

1. Create a subscription for the customer.
2. Add a variant that is not in any open or upcoming OC. The following warning should be red: "There are no open or upcoming order cycles for this product."
3. Save the subscription.
4. Edit the subscription. In the review page, the following warning should be red: "No Upcoming Order Cycle"

## Context

@RachL discovered this when testing openfoodfoundation/openfoodnetwork#2733.

## Severity

bug-s5: we can live with it, only a few users impacted

**Comment by bschuer** [comment]
Hello! My partner and I are in a student group working on open source projects and would like to help out with this issue. Do you have any advice/tips?

**Comment by jibees** [comment]
@bschuer and welcome here ;) 
What sort of advice do you need: is the description of the issue not enough?

Did you install the application on your computer ?
there's a wiki https://github.com/openfoodfoundation/openfoodnetwork/wiki that can answer question ... Did you join our slack https://www.openfoodnetwork.org/slack-invite ?

**Comment by kubczakn** [comment]
Has this issue already been fixed? I went through the steps to reproduce the issue and it looks like the behavior is already what is intended with the warning being in red:  

![image](https://user-images.githubusercontent.com/55517183/161337543-a807216c-4ad5-48cc-8315-41e27c35738e.png)

**Comment by drummer83** [comment]
Thanks @kubczakn, I accidentally found this issue and you are right! I can confirm that this one is solved already.

![image](https://user-images.githubusercontent.com/1790176/194718643-195da3bb-35a9-4dc0-be00-f68b257510ac.png)

![image](https://user-images.githubusercontent.com/1790176/194718648-923e62e6-8229-4176-a1df-1f8f9bba1eff.png)

Closing.
