### ISSUE TITLE
Adjust Backoffice Order Flow

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#8912]
## Description
**- As an:** enterprise user
**- On page:** create backoffice order
**- I want to be able to:** do this in a more straightforward way

We want to change the flow of the backoffice order creation process.
 Currently it goes:
1. Order Details
2. Customer Details
3. Payments
4. Adjustments
The problem with this is that it demands the user switches back and forth between 1 and 2 a few times to fill in all the details.

We want to change to:
1. Customer Details
2. Order Details
3. Payments
4. Adjustments
So when 'New Order' is pressed in the backoffice the user should be taken to the 'Customer Details' screen first.

An order in state cart should be created at step 1.

It was noted that potential issues may arise if elements in 'Customer Details' step depend on 'Order Details' step. This should be solvable in half a day.

This change applies to the User Flow and also to the submenu. Please change the submenu accordingly.

## Acceptance Criteria & Tests

1. Test stopping at every point and that the order does not go into a corrupted state. State transitions should be well handled.
2. Test orders are created properly
3. This will probably benefit from some thorough testing of this flow with the distinct intention of trying to break it!
4.  Product need to update the Order States miro board to reflect these changes
5. Product need to ensure hte User Guide is updated to reflect these changes

**Comment by tschumilas** [comment]
OK.  Thanks.
