### ISSUE TITLE
Remove "Checkout only" option on payment methods

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8915]
## Description

Came up in [#8871](https://github.com/openfoodfoundation/openfoodnetwork/pull/8871), but valid for both legacy and split checkout.

The `checkout only` option is available only for payment methods but seems not to be working correctly ~~for split checkout~~. We should remove it from the dropdown, when editing a payment method:

`/admin/payment_methods/<id>/edit`

## Expected Behavior

The `checkout only` option should not appear on the dropdown when editing payment methods.

## Actual Behaviour

The `checkout only` option appears on the dropdown when editing payment methods; setting it as the only payment method closes the shop ~~on split-checkout~~.

## Steps to Reproduce

1. Set a shop to open with one payment method only
2. Set it as checkout only
3. Verify the shop is closed

## Animated Gif/Screenshot

![Peek 2022-02-17 10-30](https://user-images.githubusercontent.com/49817236/154468830-4b80b6fd-681a-4adf-90e2-70d3e9c437b0.gif)

## Workaround

Set the payment method as `Both checkout and backoffice`

## Severity

bug-s3

## Your Environment

* Version used: v4.1.19
* Browser name and version: Firefox 96
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by jibees** [comment]
I guess this one should be renamed to `Remove "Checkout only" option on payment methods`, as it's not strongly related to splitcheckout and will actually remove this option in both split / legacy checkout, right?

**Comment by filipefurtad0** [comment]
> it's not strongly related to splitcheckout

Good point :+1: 
Renamed and updated the issue. Thanks!

**Comment by Matt-Yorkley** [comment]
Hmmm... I thought this feature was being used? :thinking:

**Comment by RachL** [comment]
@Matt-Yorkley "backoffice only" yes, "back+ front" yes, but not "checkout only". But we can double check by checking in prod DB if we have users who have selected this?

**Comment by RachL** [comment]
@filipefurtad0 can we know the hub id?

**Comment by filipefurtad0** [comment]
The hub (it seems to be only one) using SCA as "checkout only" is:

```
openfoodnetwork=> SELECT distributor_id FROM distributors_payment_methods WHERE payment_method_id IN (select id FROM spree_payment_methods WHERE display_on = 'front_end' AND type = 'Spree::Gateway::StripeSCA');
 distributor_id 
----------------
           2412
(1 row)

```

The others are:

```
openfoodnetwork=> SELECT distributor_id FROM distributors_payment_methods WHERE payment_method_id IN (select id FROM spree_payment_methods WHERE display_on = 'front_end' AND type != 'Spree::Gateway::StripeSCA');
 distributor_id 
----------------
           1453
           1072
           1063
           2412
           3192
(5 rows)
```

**Comment by RachL** [comment]
@filipefurtad0 thank you ❤️ I've switched them all :)

**Comment by RachL** [comment]
@apricot12 yes. I think we need to run a little migration as part of the removal? Switching all existing "checkout only" to "backoffice and checkout" ?

**Comment by apricot12** [comment]
Is it migration to both back office AND checkout or only to one of these in the DB? @RachL

**Comment by RachL** [comment]
@apricot12 yes both! Switching to backoffice only would make payment method disappear from the shopfront. That would be annoying 😅

**Comment by apricot12** [comment]
Sounds good. Will take a crack at it.
