### ISSUE TITLE
Link from Order Confirmation to enterprises' own website

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8917]
## Description

Enterprise users want their customers to feel like they are shopping with them, even when they are using OFN. This is one of the reasons we tried to do embedded shopfronts, but we aren’t able to continue supporting that particular feature.

To have a more end-to-end customer journey when customers are being sent from enterprises’ own websites to the OFN shop, we could try to make it more likely that they go back to the website at the completion of their order.

**- As a:** shopper
**- On page:** `/orders/RXXXXX`
**- I want to be able to do:** See a button to visit the shop's website (when the hub manager has put one in enterprise settings)

![image](https://user-images.githubusercontent.com/6525576/154537971-dd487b1a-2eb7-4b0f-8dd2-1b1442aa7acb.png)

## Acceptance Criteria & Tests

*Scenario 1 - As a loggedin shopper*

1. As a hub manager set up a website in the contact page of your enterprise settings
2. Login as a shopper and order something
3. See the button on the order confirmation page, next to "back to store"
4. As a hub manager, remove the website
5. Login as a shopper again and order something
6. See the button is not appearing any longer

*Scenario 2 - As a guest shopper*

Repeat scenario 1 with a guest shopper

## Connected wishlist and discovery discussions* [list precedent discussions]

Created from: https://community.openfoodnetwork.org/t/link-from-order-confirmation-to-enterprises-own-website/

**Comment by RachL** [comment]
hello @apricot12 are you still working on this one?

**Comment by apricot12** [comment]
@RachL Yep, just started on it today 🙏
