### ISSUE TITLE
Welsh / cy.yml locale throwing errors in staging

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8919]
## Description

Not yet in production, but used to be working correctly in staging. Not sure this is related to server settings / provisioning...

## Expected Behavior

The app should work in Welsh.

## Actual Behaviour

The app is breaking when selecting the Welsh language.

## Steps to Reproduce

1. visit https://staging.openfoodnetwork.org.uk/
2. Look for welsh in the dropdown -> notice you have an unusual link in it
3. Select it though
4. Try to browse around... 

## Animated Gif/Screenshot

![Peek 2022-02-21 12-52](https://user-images.githubusercontent.com/49817236/154959749-e1b92965-a8fa-4eac-8d53-10d60ab0f9f7.gif)

## Workaround

-

## Severity

Not yet in production, but used to work.

## Your Environment

* Version used: v4.1.19

**Comment by sigmundpetersen** [comment]
Yes you can see this in the code as well https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/cy.yml#L2

**Comment by sigmundpetersen** [comment]
I can put it back to what it was, 'Saesneg'. But afaik this translates to 'English'?
It should rather be 'Gymraeg' -> 'Welsh', no?

**Comment by sigmundpetersen** [comment]
I don't think this is what breaks the page though.
That's rather due to the lines 'menu_x_url' being translated, which they shouldn't be.
(From https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/cy.yml#L1456)

**Comment by sigmundpetersen** [comment]
I put them back to untranslates values in Transifex.
They should be updated on next pull from Transifex.

**Comment by filipefurtad0** [comment]
Thanks for investigating and fixing @sigmundpetersen .
I'll close here, and check back at a later stage :+1:
