### ISSUE TITLE
As a user with an OFN account, I want to be able to login with my LesCommuns account

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8922]
Merging https://github.com/openfoodfoundation/openfoodnetwork/issues/5220 and https://github.com/openfoodfoundation/openfoodnetwork/issues/5221

## Description
**- As a:** enterprise who has an account on both OFN and les communs account
**- On page:** `/#/login`
**- I want to be able to do:** I want to be able to login with lescommuns. **User creation is out of scope here.**

A small demo on how it is working on another platform: https://www.loom.com/share/1a61cd8972fa4e3eb1566da4b2fc679c

## Acceptance Criteria & Tests

As tester we want to be able to see the following if the feature toggle in #8195 is turned on:

1. When visiting `/#/login` on a staging server where you would have created an account with the email testdfc@protonmail.com (FR staging is set up) I should see: 

![image](https://user-images.githubusercontent.com/6525576/155184402-630b8579-5fd0-4fe1-a611-f467b2834cca.png)

**Except the text should not be red it should be grey to not attract user attention too much.** OFN grey is `#555555`

2. When clicking on the link, I should be redirected to this page (URL looks like https://login.lescommuns.org/auth/realms/data-food-consortium/protocol/openid-connect/auth?scope=openid+profile+email&response_type=code&redirect_uri=https%3A%2F%2Fsecure.socleo.org%2Fauth%2Fauthorize%2Flescommuns&code_challenge_method=S256&prompt=consent&client_id=socleo&code_challenge=6-D8UCbxW8--C279y6SrFilIJJZzItGEwU6sIi0Omd8 )

![image](https://user-images.githubusercontent.com/6525576/155183715-39838e4b-e500-4987-b930-05ae3412078a.png)

3. When login in with test DFC user (credentials in bitwarden) I should be redirected back to OFN home page, but logged in this time (as I would if I had used OFN to login).
4. If there is another staging server that has this same account, when visiting that staging server on the same browser I should be logged in automatically.

**Comment by RachL** [comment]
@Matt-Yorkley I don't know if François or Andy already change the color of the link. Last I heard was in this comment: https://github.com/openfoodfoundation/openfoodnetwork/pull/7880#issuecomment-881756570

@filipefurtad0 let me know if the issue is clear enough. We can have a quick call about it and I will be of course helping on testing as well, but it could be cool for you to be aware of that work.

**Comment by Matt-Yorkley** [comment]
@RachL 

> I don't know if François or Andy already change the color of the link

Last I checked the button had been removed from the login modal completely and moved to a page in the admin area.

**Comment by Matt-Yorkley** [comment]
> 4. If there is another staging server that has this same account, when visiting that staging server on the same browser I should be logged in automatically.

I don't think it'll work like that. They would have to log in again on the other staging server and potentially re-authenticate via LesCommuns. Sessions and session cookies are not shared across different domains.

**Comment by RachL** [comment]
@Matt-Yorkley 

> Last I checked the button had been removed from the login modal completely and moved to a page in the admin area.

🤔  But how am I supposed to login if I'm already loggedin as admin? That's a bit weird no?

> If there is another staging server that has this same account, when visiting that staging server on the same browser I should be logged in automatically.

Ok. Today I can do it with the other platforms in DFC: when I do it on one, on the same browser I'm loggedin on the others, so I thought it would be the same with OFN. I will remove this part then.

**Comment by Matt-Yorkley** [comment]
Let's step back a bit and try some re-inception here. So there are several different operations that need to work correctly for a proper OAuth implementation and we need to look at each of them and think about how they will be implemented. Each bit is like a mini-feature and each bit needs some UI and some backend work. They look like this:

1. Creating a **new OFN user** account based on an external identity
This is effectively a user sign-up, but based on the authentication from the external provider. It needs to go into the signup flow.

2. Linking an **existing OFN user** account to an external identity
I imagine this is what a lot of users will want primarily, and it's completely different to the first option. It needs to be shown to the user only _after_ they've logged in to their account (and not in the login modal).

3. **Logging in** to an OFN user account which has _already_ been linked to an external identity
This requires that the user has used either option 1 or option 2. It doesn't make a lot of sense unless both of the previous two options have been implemented. It needs to go in the login flow.

**Comment by RachL** [comment]
@Matt-Yorkley step 1 is out of scope here, there is no funding for that.
The funding is only on login IF the account exist already on _both_ sides: OFN _and_ the external provider.

Can you describe what do you want to show to the user in step 2?
