### ISSUE TITLE
[BUU] As an enterprise user, I should be able to access action buttons and add new variant

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8931]
## Description
**- As a:** enterprise user
**- On page:** `admin/product`
**- I want to be able to do:** see per product buttons edit, clone and delete and per variant dropdowns edit and delete. Also the new variant button can be used to add variant.

**Individual Actions Dropdown**
For Product
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/94c06883-38d0-4684-b6b7-465d8397cdce)
For Variant
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/ac104277-0435-4bd3-941e-59a46653e31a)

<img width="630" alt="Screenshot 2021-03-24 at 17 04 59" src="https://user-images.githubusercontent.com/11681324/112352979-2b6ce400-8cc3-11eb-86bf-0812a6b85a39.png">

These designs are here: https://www.figma.com/file/kBvKYXnaNU0thSnKJUoyup/Product-List-UI-uplift?node-id=10%3A1351 

## Acceptance Criteria & Tests

*Scenario 1 as enterprise user*

1. Turn on toggle feature
2. Log in as enterprise user
3.  Go to `admin/products` :

- If click on the action field, the dropdown expands 
- If click anywhere outside the action field or the dropdown, the dropdown closes without any option executed
- If _'edit'_, the product edit page opens `admin/products/XXXX/edit`
- If _'clone',_ the a copy of the product is created below (named COPY OF [Product Name]) also it would be cool if it fixes this issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/660 
- If _'delete_', an alert pops up 'Are you sure you want to delete this?'. If user clicks _'cancel',_ pop closes and product gets not deleted. If user click _'delete'_, pop closes and product gets deleted.
- **check that you cannot delete the last variant of a product, only the product**

- Adding new variant works with this button:

![image](https://user-images.githubusercontent.com/6525576/156615560-49028c3c-c57d-4a64-b126-6a5e592de714.png)

*Scenario 2 as super admin*

Repeat scenario 1 with super admin.

**Comment by mariocarabotta** [comment]
archiving as overwritten by other issues
