### ISSUE TITLE
[BUU] As an enterprise user, I should be able to do edit actions on admin/products page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8933]
## Description
**- As a:** enterprise user
**- On page:** `admin/products`
**- I want to be able to do:** edit a product´s `unit type`, `number`, `tax category`, `inherit properties`, `category`, `SKU`, `producer`, `price` and a `variant´s number` and `display as` field

This will be done using Autosave behavior.

TODO: design on the top left for example a little spinner that ends with the text "All changes saved"

## Acceptance Criteria & Tests

*Scenario 1 as enterprise user*
1. Turn on feature toggle
2. Log in as enterprise admin
3. Edit the listed fields and see if it applies correctly on the page but also the shopfront.
Some comments:

**Unit field + variant unit name + on hand** 
- when the user clicks on the Unit field it should show a tick list with the different unit types (pre-defined options in the system) to change to, **in case of _Items_ a text field is displayed below**
- when the user clicks on the **variant´s unit field,** the field becomes editable field where the user can change the 500 to another value
- 5000g should be automatically correcting to display 5kg, as the system currently does, we wouldn't intend to lose this functionality
- the onhand field opens to an editable field with the option to turn on 'on demand'. users can change the stock levels e.g. 'On hand' or make the product on demand which is the new version of the existing 'unlimted'.
Design wise:
1. Typeable fields are grey labels and grey outlines until they are ‘clicked’ in to type/edit
and then the outline of the field becomes blue.
2. Unit type is editable in the parent only, in the variant´s unit dropdown it´s greyed out![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/97f8cf5f-f88e-40dd-a3c7-e3f10b935a61)
3. When user clicks somewhere outside of the dropdown area, drowdown closed and edits are saved.

how mandatory fields should look like: ![Screenshot 2021-03-30 at 16.28.33.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/e6d16980-5a05-418b-acc7-450477904169)

**On Hand**
On hand is new and on click, brings up this visual:
![Screenshot 2021-03-31 at 10.03.08.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/02f12565-f304-4158-9ee4-9d00ad50c6f9)

Where users can change the stock levels e.g. 'On hand' or make the product on demand which is the new version of the existing 'unlimted'. 

**Tax Category**

Simple drop down tick list:

![Screenshot 2021-03-31 at 10.28.11.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/10c063db-fb0a-4441-87f6-832675ddcf57)

**Inherit Property**

Simple on/off switch:
![Screenshot 2021-03-31 at 10.23.57.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/f6d19f0b-cb8c-4276-8bb9-3b266ac1ac92)!

**Display as + price + sku + category + producer**

They should be editable when column is activated. Category has a similar dropdown as in the filter.

*Scenario 1 as super admin*

Repeat scenario 1 with super admin credentials.

**Comment by RachL** [comment]
@jibees I know you said we need probably 1 issue per field, but I needed to gather info to start with.

I stumbled upon more questions. I see here https://www.figma.com/file/kBvKYXnaNU0thSnKJUoyup/Product-List-UI-uplift?node-id=0%3A1

![image](https://user-images.githubusercontent.com/6525576/155577316-a77f8b2e-cdc1-4ce7-9548-7128586d9cdd.png)

We see the dropdown carret for 1 quiche and if I understood correctly it should open a zone that explains to me this is editable. But I can't find the designs for it. Do you?

If not we need design for this + the autosave if we are going for it. Do you want to do them? Otherwise I can have a go.

**Comment by mariocarabotta** [comment]
archiving as overwritten by other issues
