### ISSUE TITLE
Rubocop: app/controllers/split_checkout_controller.rb has too many lines

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#8942]
### What we should change and why (this is tech debt)
Rubocop warning about the length of the class `split_checkout_contoller.rb`

### Context
This came up in PR https://github.com/openfoodfoundation/openfoodnetwork/pull/8893#issuecomment-1048313464

**Comment by macanudo527** [comment]
@jibees  I'd like to give this a try.

**Comment by macanudo527** [comment]
I think we can isolate all the methods that handle errors into a service. It seems like all of these are related:
```
render_error
order_error_messages
no_ship_address_needed?
remove_ship_address_errors
reorder_errors
bill_address_error_order
flash_error_when_no_shipping_method_available
```

And then maybe we can extract the voucher processing? That should come close to 100 lines.

Or there was talk of splitting this into two controllers. Is that the better solution here?
