### ISSUE TITLE
Unable to save enterprise name change depending on cursor position

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#8943]
## Description

When making changes to the enterprise name field from the primary details screen, the 'update' button remains greyed out even after text is changed, unless the cursor is clicked outside of the 'name' field. This means that users are unable to save their changes with the update button until they have first clicked outside of the name field.

## Expected Behavior

Users should be able to click the 'update' button after making changes to the name field.

## Actual Behaviour

Users are only able to click 'update' following changes to the name field when the cursor is first clicked outside of the name field.

## Steps to Reproduce

1. Go to enterprise settings and make a change to the name field on the primary details tab
2. Attempt to save the changes by clicking the 'update' button, without clicking elsewhere on the page first
3. Changes are not saved as the update button cannot be clicked
4. Click elsewhere on the screen, or enter another tab and perform a click action, which will turn the update button red and clickable, allowing information to be saved.

## Animated Gif/Screenshot

![Name change bug](https://user-images.githubusercontent.com/100226210/156003405-7cbf7bc0-8fae-48a7-994a-4788ec3282a5.gif)

## Workaround

Clicking outside of the name field allows the update button to be clicked and changes to be saved.

## Severity

bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: OFN UK on prod
* Browser name and version: Chrome Version 98.0.4758.80 (Official Build) (arm64)
* Operating System and version (desktop or mobile): Mac OSX Big Sur 11.6.2 desktop

**Comment by drummer83** [comment]
I think this is covered in #1719, isn't it?

**Comment by dacook** [comment]
Yes, that looks like the exact same problem. That issue was closed as there's an easy workaround.

However low the priority, I think it's still relevant though so would suggest we keep this open. 

From a technical point of view, I think this is developed in Angular. In the long term, we'd like to replace that, but it could be a long time away. Until then I think this simple fix would be valuable.
