### ISSUE TITLE
[Split Checkout] Stripe production testing / roll-out strategy

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8948]
### Description

Related to #7767.
Related to #8924.

We need to consider Stripe and perhaps Paypal testing in our rollout strategy as these are, at the moment, difficult to cover with automated tests.

While in principle manual testing can cover some scenarios with test cards this will need careful testing in a production environment.

### Context

This came up on delivery circle meeting 01.03.2022.

### Impact and timeline

Rollout of Split Checkout.

**Comment by RachL** [comment]
As this is a prod-test, at this stage I'm confident with the use of the feature toggle to gradually increase to test this in production. I will keep this thread up-to-date as soon as we start opening the new checkout to new users again: https://community.openfoodnetwork.org/t/new-checkout-feature-split-checkout-rollout/2546 to follow. Closing here
