### ISSUE TITLE
Customers: select a hub, then another

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#895]
When you go to /admin/customers and select a hub that doesn't have any customers, you can click on another hub, but nothing happens. At first, I thought that no hub has any customers, but you need to reload the page before you can select another hub.

**Comment by daniellemoorhead** [comment]
Hey @mkllnk is this the same as #588?

**Comment by mkllnk** [comment]
Yes. Sorry, I didn't see that one. I close this as a duplicate.
