### ISSUE TITLE
[Split Checkout] Payments with non-3D cards need to be manually captured in the BO

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8952]
## Description

Payments with non-3D cards need to be manually captured in the BO.
~~Despite manually capturing them they still appear as not-captured on the Stripe Dashboard.~~

## Expected Behavior

- Payments with non-3D cards should be automatically captured (provided the card is valid), both on the UI and on Stripe.
- The button to manually capture credit card payments is displayed (when editing the order)

## Actual Behaviour

- Payments with non-3D cards are not automatically captured (provided the card is valid) in the UI, and remain uncaptured on Stripe
- The button to manually capture credit card payments is displayed (when editing the order)

## Steps to Reproduce

1. Place an order with Stripe using a simple non-3D card, like the 4242424242... 
2. Notice the payment is not taken (seen on order confirmation and order edit)

## Animated Gif/Screenshot

![Peek 2022-03-02 16-18.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/cf77f08d-8151-49de-9734-d376907fa9ca)

**Comment by jibees** [comment]
I'm not sure to manage to handle this one. 
I guess @Matt-Yorkley could be the man for sure.

**Comment by BethanOFN** [comment]
I've currently taken UK testers off split checkout due to this issue - any rough timescale for a resolution?

**Comment by RachL** [comment]
@mkllnk do you have some room to look at it? George has already a pile of bug on his plate 😅 

thanks @BethanOFN for the feedback! I will let you know as soon as it is fixed.

**Comment by filipefurtad0** [comment]
Updated the description:

> Despite manually capturing them they still appear as not-captured on the Stripe Dashboard.

I've checked this in the context of https://github.com/openfoodfoundation/openfoodnetwork/pull/10014 and in master: Manually capturing the payment on the backoffice marked the payment as captured on the Stripe Dashboard :+1:

**Comment by abdellani** [comment]
Hi @filipefurtad0 

I was unable to reproduce the issue locally.
Can you please check if I missed anything?
I integrated Stripe, and connected the producer.

This is how I create the payment method
![image](https://user-images.githubusercontent.com/16113997/205048207-ded52005-1ad6-4d1b-ab77-59a8fefd5871.png)

I order a product and selected `Stripe ASC` as a payment method 

![image](https://user-images.githubusercontent.com/16113997/205048737-e92a91bb-c4b0-4f0b-b958-c92bb0a5f788.png)

Order confirmed
![image](https://user-images.githubusercontent.com/16113997/205049003-ffe216cd-b769-449f-9e8e-bbede762fcaf.png)


![image](https://user-images.githubusercontent.com/16113997/205049196-57bfcef2-c4d0-43cd-8380-c1debf4916d4.png)

**Comment by drummer83** [comment]
@abdellani On legacy checkout (your screenshot) this is working. You need to enable split checkout to reproduce the issue.

**Comment by drummer83** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Feature-toggles

You need to log in as super admin an open /admin/feature_toggles.

@abdellani

**Comment by abdellani** [comment]
After comparing the legacy checkout with the split checkout. I noticed that the `payment_intent` was created but processed in the split checkout.

![image](https://user-images.githubusercontent.com/16113997/205300569-516f59b8-6343-4293-aa90-7ac0249648e5.png)

In the legacy checkout controller, the submit request trigger a loop that keeps the order moving from one state to another unit it reaches the final state `complete`.
If I'm not wrong, The sequence of states is: 
`cart` -> `payment` -> `confirmation` -> `complete`

Note: there are other order states, but it looks like they are not used in this context. For example: `canceled` or `returned`.
When the order reaches the state `payment`, we run the method to [process the payment](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/checkout_controller.rb#L96) 
```ruby
  def checkout_workflow(shipping_method_id)
    while @order.state != "complete"
      if @order.state == "payment"
        update_payment_total
        return if redirect_to_payment_gateway

        return action_failed if @order.errors.any?
        return action_failed unless @order.process_payments!  # <<<<<<<<
      end

      next if OrderWorkflow.new(@order).next({ "shipping_method_id" => shipping_method_id })

      return action_failed
    end

    update_response
  end
```

In the split checkout, we don't need to use the same loop as every state is represented by a different view. The user controls the order transition from one state to another.

In the new context, we can't process the payment when the order is in the `payment` state. We need to wait for the user to confirm the order. In the PR, I suggest updating the `confirm_order` in [the controller](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/split_checkout_controller.rb#L67). 

```ruby
  def confirm_order
    return unless summary_step? && @order.confirmation?
    return unless validate_summary! && @order.errors.empty?

    @order.customer.touch :terms_and_conditions_accepted_at

    return true if redirect_to_payment_gateway

    @order.process_payments!
    @order.confirm!
    order_completion_reset @order
  end

```
I thought about adding `process_payments` before transitioning to `complete` in the state machine, but I was not sure if this will not create other issues.
