### ISSUE TITLE
Metabase has not synched since 17 Feb 2022

### ISSUE THREAD

**Issue by RonellaG** [openfoodfoundation/openfoodnetwork#8961]
## Description
The Australian team use Metabase to provide customer support.

## Expected Behavior
We should be able to see up-to-date data so that we can investigate customer enquiries

## Actual Behaviour
Metabase has not synched since 17 Feb 2022

## Steps to Reproduce
<img width="1273" alt="Screen Shot 2022-03-07 at 6 15 07 pm" src="https://user-images.githubusercontent.com/68315791/156985698-057956c8-48f2-45f7-a6ed-fc9e39a52e10.png">

## Severity
Kirsten has said that this can be an S1

## Your Environment

* Browser name and version: Chrome Version 98.0.4758.109 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): MacBook Pro MAC OS Catalina Version 10.15.17

**Comment by Matt-Yorkley** [comment]
Done :ok_hand:
