### ISSUE TITLE
"g" products display BOM management tab in "oz" 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8965]
## Description

Reported [here](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1646633613539759).

Products which are set to be in `g` are displaying `oz` in bulk order management. 

## Expected Behavior

`g` products should display the respective unit in BOM.

## Actual Behaviour

`g` products display BOM management tab in `oz`.

## Steps to Reproduce

1. Create a `g` product;
2. Set up a bulk unit size for that product
3. Add it to an OC and place an order with it. 
4. Visit the BOM page
5. See the BOM tab displays the units in `oz`

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/d2e53075-5671-4791-865a-bfb49da65166)

## Workaround

None.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.1.20
* Browser name and version: Firefox 95
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Context
https://github.com/openfoodfoundation/openfoodnetwork/pull/8565

**Comment by jibees** [comment]
We need to find a _better_ way to reproduce the issue. I've tested on my local environment, and I could not reproduce. 
I've tested with `Garlic` product:

###### In the product lists:
<img width="1161" alt="Capture d’écran 2022-03-08 à 11 11 28" src="https://user-images.githubusercontent.com/296452/157215561-8a8f8133-8b26-4d0f-8538-022955454b87.png">

###### Its options:
<img width="376" alt="Capture d’écran 2022-03-08 à 11 11 44" src="https://user-images.githubusercontent.com/296452/157215577-6936c290-eb42-4b95-baad-76ab8c9d7e54.png">

###### As a result, in the BOM interface:
<img width="1435" alt="Capture d’écran 2022-03-08 à 11 11 34" src="https://user-images.githubusercontent.com/296452/157215571-9ca67bfb-87fb-4a18-bad2-c1e1ea222d42.png">

**Comment by jibees** [comment]
Actually, this is due to that `200` configuration: 
<img width="909" alt="Capture d’écran 2022-03-08 à 12 05 26" src="https://user-images.githubusercontent.com/296452/157226427-f3810f68-98e4-477f-b913-542773bfd320.png">

We retrieve the unit thanks to this. And the bug seems to be here for a long time.
