### ISSUE TITLE
Group Products by Supplier on Invoice: Part 2 - Create Enterprise User Switch

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#8969]
All Devs, Product and Testing please use Clockify project [185](https://github.com/openfoodfoundation/wishlist/issues/185) Group products by supplier

## Description
* As an enterprise user
* on page: Enterprise Settings / Business Details
* I want to be able to switch my invoice layout so that the items on it are sorted by Producer then Product i.e.

#8968 created an option in the code for items on invoices to be printed in the following order (Producer, Product) 
Apples- Murrnong
Figs- Murrnong
Cherry Tomatoes- Ross Tomatoes
Truss Tomatoes- Ross Tomatoes

This issue is about reorganising the Enterprise Settings / Business Details tab and adding the switch so that the Enterprise Owner or Manager can choose their preferred invoice order. This is shown below and can be summarised as:
* Create new sub-heading called Invoice Settings
* Put display logo in invoices checkbox and 'add customised text' into this section
* Add a new item called 'Item Display Order' with a switch to move to alphabetical by Producer then Product
* Move 'Business Address' below 'Invoice Settings'

![image](https://user-images.githubusercontent.com/2911176/157188313-228b3c59-4b70-46d4-97b5-d472e8a4e64b.png)

You can mess with the mock-up [here](https://docs.google.com/presentation/d/1jgiqASf6VT8WjJOb40vMU6pvJgRgSORK-DZCJes3Zps/edit#slide=id.p)

See further discussions [here](https://github.com/openfoodfoundation/wishlist/issues/185)

## Acceptance Criteria & Tests

1. Login as enterprise user with existing orders
2. Edit an Order that has multiple Producers and multiple Products from those Producers
3. Select Actions, Print Invoice. Note the order of the items (should be alphabetical by Product Name). Stay in the same order
4. In another tab, go to Enterprise Settings, Business Details. Switch 'Item Display Order' to 'Alphabetical by Producer, then Product'. Hit Save
5. Back in the order, print the invoice again. The order of the items on the invoice should have changed.
6. Testing should probably include both invoice templates
7. Also check the Bulk Invoice print from the Orders page

**Comment by lin-d-hop** [comment]
Small note - the UI element of the switch used in the above mock is not used in other places in Enterprise Settings. Can we use a UI element that is consistent with this area of the app? eg radio buttons :pray:

**Comment by kirstenalarsen** [comment]
This was a suggestion by @Rachel Arnould ***@***.***>
to introduce a switch like this. I'm open to it being done either way.
@jibees any thoughts?

**Comment by jibees** [comment]
I'd be happy to use such a new component, but my main concern is that this kind of component is rather used in interface when clicking on it change immediately the state of the app. Here, we wait for submitting the form. I'd vote for a radio button then.

_Source:_ https://www.nngroup.com/articles/toggle-switch-guidelines/#:~:text=Toggle%20switches%20are%20best%20used,or%20toggles%20%E2%80%94%20can%20be%20tough.

**Comment by RachL** [comment]
I was mentionning this type of switch as we start to have a huge set of radio button, and they are pretty small. I find them more and more hard to use. But maybe a topic for the future, not this issue :-)

**Comment by lin-d-hop** [comment]
It would be cool to make an epic to replace all the radios to a better component for sure! I just hate to add more complexity to our confusing UI
