### ISSUE TITLE
Translations on UK account page

### ISSUE THREAD

**Issue by stveep** [openfoodfoundation/openfoodnetwork#897]
I just checked the account page as deployed on UK production and it is not finding translations for the payment and shipping states. They should be in the spree i18n translations so I think it could be an issue with configuration?

@pmackay @lin-d-hop 

![transl](https://cloud.githubusercontent.com/assets/1314715/14402987/90cd0024-fe3d-11e5-9d67-dd96b55fdf89.png)

**Comment by lin-d-hop** [comment]
Seems they were missing from the en-GB.yml file. I just added them in and you can see in UK production now. Though I haven't tested anything except Balance Due and Pending (shipment state)...

@stveep would you check you agree? And if so close? 

Thanks :-)
