### ISSUE TITLE
Linking Order Cycles to Shipping & Payment Methods

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8971]
## What is the need / problem?

One of the core structures within the Open Food Network is the Order Cycle. Order Cycles have a lot of flexibility – you can set different order cycles to have different products or be visible to different customers. However there is currently a significant flaw with Order Cycles. They all must enable every payment method and every shipping method that the Enterprise offers.

This is problematic as there are many cases in which some order cycles would benefit from having only some payment of shipping methods available. For example if you wish to offer national delivery on less perishable products, then you might want the ‘national courier’ delivery option for an order cycle with only perishables and a ‘local delivery’ option on an order cycle with all products. Or if you have a physical premises then you might want to offer cash payment only for orders to be collected from the physical shop. More potential use cases are listed in the next section.

## Which type of users does this problem affect (and how many, if known)?

_- Shoppers_
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]

https://www.openfoodnetwork.org/fundedfeatures1/

## Connected wishlist and discovery discussions* [list precedent discussions]

https://community.openfoodnetwork.org/t/tagging-shipping-methods-and-payment-methods-to-ordercycles/921/32

## Is Papercut or feature candidate?

Feature candidate!

**Comment by mkllnk** [comment]
Trying a little estimate here. It's a bit bigger though and bigger means more uncertainty:

- 2 days: Database changes for associating shipping methods and payment methods to order cycle. Implementation is not straight forward. We could associate methods with order cycles directly but that would mean that a shared payment method between two enterprises can only be toggled for both enterprises at the same time. This is rare but probably unexpected. The other possibility is to associate to the outgoing exchanges of an order cycle. An exchange is the connection between an order cycle and an enterprise. The downside is that the data model would allow to also filter on the incoming level of order cycles which doesn't make sense. Suppliers don't have payment methods... but we can ignore that.
- 2 days: UI changes. Looks simple but it's probably all handled with AngularJS. Converting to Stimulus would take extra time.
- 4 days: Model and controller updates. This *should* be simple but it's adding to complex code already. There may be regressions around validation and caching. I don't expect the first PR to pass manual testing.
- x days: Unknown. The above is a best case scenario of known work when done by a senior developer. It may take longer depending on circumstances.

**Comment by lin-d-hop** [comment]
Ok this is a process point.

In future I think we need to have 2 devs estimating before fundraising as the difference between Andys estimate and Maikels estimate is 100%. Funded features wont be feaible with the kind of underestimate made on this one.

Thanks for estimating this @mkllnk. Did you know @cillian is working on it?

**Comment by mkllnk** [comment]
Where is Andy's estimate?

**Comment by lin-d-hop** [comment]
In the original meeting on the first round of funded features we filtered all potential funded features that would take more than 4 senior dev days.
