### ISSUE TITLE
Adding fees to specific Payment Methods

### ISSUE THREAD

**Issue by Rocksj** [openfoodfoundation/openfoodnetwork#898]
Is there a way to automatically add on the paypal charges to a customer's payment. We want the 4% paypal charge to be borne by the customer not the Food Hub

**Comment by lin-d-hop** [comment]
I'll spec a little more on discourse for input from the world

**Comment by lin-d-hop** [comment]
Discussion here: http://community.openfoodnetwork.org/t/fees-on-payment-methods/552

**Comment by lin-d-hop** [comment]
Over to @mkllnk after hangout this morning.

**Comment by mkllnk** [comment]
Here is the roadmap:

- [ ] Extend Spree::PaymentMethod with calculated_adjustments. (3h)
- [ ] Add new inputs to the payment method edit form in the admin interface. (4h)
- [ ] Add the fee to the order during checkout. (4h)
- [ ] Display that fee to the customer during checkout. (5h)
- [ ] Display that fee to in confirmation emails. (3h)

**Comment by sstead** [comment]
Testing Notes:
It seems the presence of a payment method with a fee attached is causing some checkout issues, depending on the fee calculator that's applied...
- Flat Percent - get 'server went down' grumpy cat when i try to checkout
- Flat Rate (per order) - Works correctly.
- Flexible Rate - get 'server went down' grumpy cat when i try to checkout
- Flat Rate (per item) - The payment fee looks right, but in the 'your order summary it's not updated. And if you try to place order, it says submitting order, but it doesn't go through and you remain on th checkout page. See below.
![image](https://cloud.githubusercontent.com/assets/10843056/15530579/a572c6d8-2298-11e6-9bb6-82c2be7d959c.png)
- Price Sack - Am able to checkout with correct fees, but the summary on checkout page is not correct, see below.
![image](https://cloud.githubusercontent.com/assets/10843056/15530682/3b0ed952-2299-11e6-925c-f231fbe95b03.png)

**Comment by sstead** [comment]
Testing notes
- All fee calculators are now working. 
- The fee is showing in the correct places in checkout and order confirmation.
- If the fee is a % fee, it doesn't calculate including shipping or enterprise fees.
- If the fee is a % fee it will calculate based on the price of the produce, regardless of whether this price includes GST or if it's a GST free item. 
- No tax seems to be included in the payment method fee.
- If I create an order, and select the payment method with a fee, this fee is applied to the order. 
- But if I edit an order, changing the total $, the fee doesn't recalculate.
