### ISSUE TITLE
[staging-FR] Images broken: error 301

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8983]
## Description

Images are broken on staging-FR.
~~Possibly related to #8414 and [Slack thread](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1635232358001600).~~

## Expected Behavior

Images should work on staging-FR.

## Actual Behaviour

Images are broken on staging-FR.

## Steps to Reproduce

1. Anything related to images, for example:
2. Displaying previously uploaded images 
3. Uploading images

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/4758fcf4-7535-42a0-bc74-8d37dfa25867)

## Severity

~~Release blocker?~~
Does not seem to be the case: staging master in staging-AU did not break images :+1: 

## Your Environment

* Version used: current master 6474055380ace63095e1a06e7db8f54db1040e14

**Comment by filipefurtad0** [comment]
Seems only related to staging-FR; all good in staging-AU after staging master :+1: 
Updating the issue.

**Comment by sigmundpetersen** [comment]
Also reported in #6290? 
Maybe it's been broken for a while

**Comment by filipefurtad0** [comment]
Hey @sigmundpetersen - thanks!
While in #6290 an error 422 was reported, on this issue we see an error 301, when trying to upload images -> this seems to be the current behavior now, so I'll close #6290 :+1:

**Comment by mkllnk** [comment]
I just had a look at the error message and I think it's just a missing config option. The bucket seems to be in Europe which is not the default region. We need to specify `S3_REGION`. Let's fix this up after Active Storage.

**Comment by RachL** [comment]
> The bucket seems to be in Europe which is not the default region.

yes we have changed this in https://github.com/openfoodfoundation/ofn-secrets/pull/55 - . As we want to be compliant and store all our data in Europe. But I thought we did it only for our database, as it is always tough to migrate images. I don't know if it's easier now with Active Storage, but FR (and any EU instance) really needs to have everything in Europe and not in the US anymore.

**Comment by mkllnk** [comment]
Okay, another check:

* fr-prod is using storage in Europe.
* fr-staging is using the bucket `ccs-ofn-staging` which is in US East (N. Virginia) us-east-1.
* The staging bucket is in the default region and therefore doesn't need a config parameter for this.
* Staging is correctly configured and works correctly with Active Storage.

I can close this issue. :smile:
