### ISSUE TITLE
Make checkbox for "Send a cancellation email to the customer" checked by default

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8985]
## Description
To solve #8477 all functionality was implemented in #8766. The checkbox for "Send a cancellation email to the customer" should be checked by default when cancelling an order by deleting the last item (See [this comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/8477#issuecomment-936550669) in https://github.com/openfoodfoundation/openfoodnetwork/issues/8477). Currently the checkbox is unchecked by default.

## Expected Behavior
The checkbox should be checked by default.

## Actual Behaviour
The checkbox is unchecked by default.

## Steps to Reproduce
1. Log in and go to /admin/orders
2. Edit an order and delete all items

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/1790176/157776735-0c73be8e-f0ea-4d55-bea2-9a3f550ea88f.png)

## Workaround
None.

## Your Environment

* Version used: staged [af8500e](https://github.com/openfoodfoundation/openfoodnetwork/commit/af8500e98c61d635697c3898763d37240705e0a4)
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by drummer83** [comment]
@openfoodfoundation/train-drivers-product-owners 

Hi team, just wanted to raise that #8766 is currently part of the next release but it is not fully according to specification. Please see this issue above and comment if 
- A) we move forward and implement this with the following release
- B) we redraft a release without #8766 

I personally would go for A because the impact on users is really small. Also discussed this with @filipefurtad0.
What do you think?

**Comment by RachL** [comment]
yes moving forward :+1:

**Comment by drummer83** [comment]
Hmm, I can't confirm. 
It makes me feel bad, but I have to say that I probably missed to test the regular cancellations you are mentioning.

**Comment by filipefurtad0** [comment]
Hey @drummer83 ,
No worries :+1: 

> Hmm, I can't confirm.

Ahh, ok, so you are receiving regular cancellation emails? In that case, all good.
I'm just wondering whether this is a confirmed to add to this bug report, and assure it is considered on the fix on PR #8991 :+1: 

> It makes me feel bad, but I have to say that I probably missed to test the regular cancellations you are mentioning.

Please, no worries at all - it's part of the testing business :heart:

**Comment by drummer83** [comment]
@filipefurtad0 I can now confirm that no confirmation emails are sent for "regular" cancellations. Sorry for not being clear about this earlier.
@jibees I will create a separate issue for that.

**Comment by drummer83** [comment]
@filipefurtad0 I can now confirm that no confirmation emails are sent for "regular" cancellations. 
@jibees I have created #9043 to cover this.
