### ISSUE TITLE
BOM: datepicker not working correctly when used together with OC selector (error 304)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8998]
## Description

On the bulk order management page if both filters (datepicker + OC selector) are used together then the selected date is not kept.

## Expected Behavior

Filters should work independently and together with other filters, on the BOM page.

## Actual Behaviour

Datepicker not working correctly when used together with OC selector. An error 304 is seen in the console (maybe related)

## Steps to Reproduce

1. As a hub manager
2. Visit the BOM page
3. Set a given date on the datepicker
4. Select an order cycle
5. Notice the date on the datepicker changes

## Animated Gif/Screenshot

![Peek 2022-03-15 15-21](https://user-images.githubusercontent.com/49817236/158415510-1c0947de-ce98-4818-9cfb-6dac0684e751.gif)

## Workaround

Using only one filter

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.1.20
* Browser name and version: Firefox, 97.0.2
* Operating System and version (desktop or mobile): Windows 10 and Ubuntu 20.04

**Comment by filipefurtad0** [comment]
#9526 is now merged, removing the unblocked label. The issue still occurs:

[Screencast from 17-10-2022 15:23:16.webm](https://user-images.githubusercontent.com/49817236/196202833-7501c76c-356d-4373-b36a-35b767d7657e.webm)

**Comment by jibees** [comment]
When selecting the date range to only one day, it triggers a strange bug. 
Ie. when selecting the 12 december 2022
<img width="368" alt="Capture d’écran 2022-12-12 à 14 47 10" src="https://user-images.githubusercontent.com/296452/207061268-ca7c9926-7220-47cd-afd8-a7f56af7464f.png">

the date range is
```
q[completed_at_gteq]: 2022-09-06T00:00:00+02:00
q[completed_at_lt]:  2023-09-02T00:00:00+02:00
```

We probably. should have a look at this.

**Comment by jibees** [comment]
Ok, so I discovered a feature ;) 
When selecting an order_cycle, we're supposed to update the date range picker with the start and end date of the order_cycle. 
That's why the params send to the server are not reflecting the the date range picker values.

**Comment by jibees** [comment]
On BOM page, changing date range on order cycle selection is a _feature_ (which wasn't ok since we upgrade to a date _range_ picker (https://github.com/openfoodfoundation/openfoodnetwork/pull/9526) ; I've made a [fix](https://github.com/openfoodfoundation/openfoodnetwork/pull/10144) for that): date range picker values are updated to the order cycle dates. 
So, if I understand correctly, #8998 is not a bug. 

What do you think?

**Comment by filipefurtad0** [comment]
I've staged master, to check for the current behavior.

If there is **no order cycle selected**:
- selecting one day only, from the calendar seems to work correctly

![image](https://user-images.githubusercontent.com/49817236/207313111-40f24e8e-b483-4579-9deb-350dd81c04d5.png)

- selecting a range works as well
![image](https://user-images.githubusercontent.com/49817236/207313405-690b3483-8cb7-416b-ac83-bb312872d7f7.png)

> When selecting the date range to only one day, it triggers a strange bug.
> Ie. when selecting the 12 december 2022

So, I could not reproduce this finding.

From the following comment, I suppose that this happened because an OC was selected as well, with the dates:

```
q[completed_at_gteq]: 2022-09-06T00:00:00+02:00
q[completed_at_lt]:  2023-09-02T00:00:00+02:00
```

Was this the case @jibees?

**Comment by filipefurtad0** [comment]
It makes sense indeed - and that's a great catch @jibees - to restrict the datepicker dates, to the dates of the OC - no point in searching for orders outside the order cycle (at least, in theory, because the open/closing times could be edited after the orders were placed; is it good UX to override that first selection? Currently the flow 1) datepicker - 2) OC selector - 3) datepicker again).

However, the main issue why I find it to be a bug is that one cannot restrict dates within the OC. So for example, an OC is open for the whole month in December 22:

![image](https://user-images.githubusercontent.com/49817236/207315941-2eb94cac-3e44-4af2-b28e-3ba6ddf43a34.png)

This is the full list of orders, for that OC:

![image](https://user-images.githubusercontent.com/49817236/207316296-842480f9-7c19-49d0-977b-e9340e5e510f.png)

After selecting the OC, on the OC selector, all orders are displayed by default. I think this would be OK (a feature!) but only if:

- after OC selection, the datepicker reflects the opening/closing times of the OC
- changing the dates in datepicker and keeping the OC shows results according to the reflected change

I cannot verify any of these to be happening, so I'd still think this issue is bug: basically, the opening/closing dates of the OC overlap any selection from the datepicker:

![Uploading image.png…]()
