### ISSUE TITLE
[Split Checkout] Tags not taking effect on shipping methods

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8999]
## Description

Tags not taking effect on shipping methods

## Expected Behavior

Tags should take effect on shipping methods

## Actual Behaviour

Tags not taking effect on shipping methods

## Steps to Reproduce

1. Set a tag `hide_sm` as default rule to hide shipping methods
2. Add the tag to a given shipping method
3. Visit the checkout and notice the shipping method still appears

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e72cf63b-7846-4500-9683-e8541b36c6e5)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
outch. I didn't notice about that. Thanks @filipefurtad0 for your deep testing / review ...

**Comment by filipefurtad0** [comment]
Thanks @jibees for your patience and work on this :pray: 

Some notes on this:
- I'm working on [this draft PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/9000) to cover for this scenario (shipping methods)
- It will include coverage on tags + payment methods, which I'm confident it is working :+1:

**Comment by jibees** [comment]
> It will include coverage on tags + payment methods, which I'm confident it is working
Ok !
