### ISSUE TITLE
Log-in with Facebook, Twitter, google etc

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#9]
Install existing supported spree extension? Is a dev release for 1.3 
http://spreecommerce.com/extensions/118-spree-social

**Comment by kirstenalarsen** [comment]
note: we are looking at integrating a discourse instance within ofn instance as communications / discussion forum for users (see . would like single login e.g. login to ofn = login to integrated discourse. Discourse already has this functionality . . just in case is relevant. See http://community.openfoodnetwork.org/t/integrate-discourse-into-ofn-instance-as-communications-platform/426

**Comment by ludivinecp** [comment]
I'm working on this issue

**Comment by bingxie** [comment]
This project https://github.com/spree-contrib/spree_social/ can be reference. It's depends on spree master branch.

**Comment by elf-pavlik** [comment]
Since i18n shouldn't need much more attention, I can take a look now at PR #750

**Comment by daniellemoorhead** [comment]
Closing this as it's been around forever and it hasn't been a priority nor will it be for a while.
#githubcull2018

**Comment by diegoamc** [comment]
Hi,

I'm currently working on an Open Food Network fork and login with social networks (Facebook and Google) is a desired feature. Is there any interest that we make this a contribution to the upstream repository?

**Comment by lin-d-hop** [comment]
Hi @diegoamc 
Thanks for this offer.
OFN is licensed under the GNU Affero General Public License, which is designed specifically to ensure that, in such cases, the modified source code becomes available to the community.
Therefore we ask you do make your fork open source such that it can be shared with the wider community. In that case it would be easy to see if the contribution would be a good fit to merge upstream.
Thanks again! Looking forward to seeing what you've been up to in your fork.

**Comment by diegoamc** [comment]
The fork is open source (:

We are only getting started but we plan to make as many contributions as we can.

We'll go ahead with the implementation of login with social networks and when we have something to show we'll share it here
