### ISSUE TITLE
Can't delete an enterprise relationship on UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#900]
I tried to delete this enterprise relationship but when i clicked the trash symbol and confirmed yes i was sure, nothing happened
![screenshot 2016-04-12 16 11 53](https://cloud.githubusercontent.com/assets/10517702/14465090/8c3a7b5c-00c9-11e6-99d5-12174b21e520.png)

**Comment by lin-d-hop** [comment]
Working after latest deploy.
Closing.
