### ISSUE TITLE
Missing translation: "Shipping method" when editing shipping method

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9017]
## Description
When editing a shipping method, the confirmation message at the top of the screen is not fully translated. It starts with untranslated "Product xy".

## Expected Behavior
"Shipping method" in the confirmation message should be translated.

## Actual Behaviour
"Shipping method" in the confirmation message is not translated.

## Steps to Reproduce
1. Choose a language other than English.
2. Log in.
3. Go to /admin/shipping_methods/
4. Klick the 'edit' icon of a shipping method
5. Make a change and click 'Speichern' ('update' in German)
6. Observe the confirmation message at the top of the screen

## Animated Gif/Screenshot
![grafik](https://user-images.githubusercontent.com/1790176/159193496-a549fa14-3624-46bd-8bd2-8a87bbbca7c9.png)

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.21
* Browser name and version: 98.0.1 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTE, Desktop

**Comment by jibees** [comment]
As this one is labeled as `good first issue`, let me post the link to our wiki page regarding the i18n : https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

**Comment by drummer83** [comment]
Hi @hmurali01,
you just post a comment here - as you just did. I will assign it to you!
Looking forward to your contributions! :partying_face:

**Comment by hmurali01** [comment]
Thank you so much! I look forward to helping!
