### ISSUE TITLE
Missing translation: Confirmation message when editing order cycle

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9018]
## Description
When editing an order cycle, the confirmation message at the bottom of the screen is not translated. 

## Expected Behavior
"Order cycles have been updated" in the confirmation message should be translated.

## Actual Behaviour
"Order cycles have been updated" in the confirmation message is not translated.

## Steps to Reproduce
1. Choose a language other than English.
2. Log in.
3. Go to /admin/order_cycles
4. Change the open or close time of an order cycle
5. Click 'Änderungen speichern' ('update' in German)
6. Observe the confirmation message at the bottom of the screen

## Animated Gif/Screenshot
![grafik](https://user-images.githubusercontent.com/1790176/159193984-486b3fb0-5e48-405c-bee0-1ad160f0bf43.png)

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.21
* Browser name and version: 98.0.1 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTE, Desktop

**Comment by jibees** [comment]
As this one is labeled as `good first issue`, let me post the link to our wiki page regarding the i18n : https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

**Comment by MrFuku** [comment]
Hi! @jibees 
Can I do this?

**Comment by jibees** [comment]
@MrFuku for sure!
