### ISSUE TITLE
[Split-checkout] Default-address checkbox displayed on guest checkout

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9022]
## Description

The default-address checkbox is displayed on guest checkout; according to previous specs this is not the expected behavior, see:
https://github.com/openfoodfoundation/openfoodnetwork/blob/532d566308fbb173bff0652c190f42bc4403f157/spec/system/consumer/shopping/checkout_spec.rb#L353

## Expected Behavior

Default-address checkbox should not be displayed on guest checkout.

## Actual Behaviour

Default-address checkbox is displayed on guest checkout.

## Steps to Reproduce

1. As a consumer
2. I want to checkout my order as a guest user
3. on the 'details' step
4. does not show the save as default bill address checkbox

See [this spec/example](https://github.com/openfoodfoundation/openfoodnetwork/blob/532d566308fbb173bff0652c190f42bc4403f157/spec/system/consumer/shopping/checkout_spec.rb#L352)

And/or this [commit](https://github.com/openfoodfoundation/openfoodnetwork/pull/9021/commits/d24940e2ccebcdfc5877697ff4cbd0dcdbeff167).

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/159483707-7ee421e3-f667-46a0-a4d6-67f32ae9ab9c.png)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by drummer83** [comment]
Hi @filipefurtad0,
to avoid misunderstandings during implementation and testing: Shouldn't the other checkbox on that screenshot be highlighted? "Save as default billing address" instead of "Shipping address same as billing address"? Or am I getting it wrong?

**Comment by filipefurtad0** [comment]
> "Save as default billing address" instead of "Shipping address same as billing address"?

Yes, indeed - edited :+1:
