### ISSUE TITLE
Setup script is broken, invalid transition of states

### ISSUE THREAD

**Issue by apricot12** [openfoodfoundation/openfoodnetwork#9024]
### What we should change and why (this is tech debt)
When trying to run the setup script using `script/setup`, I run into the following error : 
```
[ofn:sample_data] - complete order - shipped
rake aborted!
StateMachines::InvalidTransition: Cannot transition state via :ship from :pending (Reason(s): State cannot transition via "ship")
/Users/srbaker/Projects/openfoodnetwork/lib/tasks/sample_data/order_factory.rb:36:in `create_samples'
/Users/srbaker/Projects/openfoodnetwork/lib/tasks/sample_data.rake:56:in `block (2 levels) in <main>'
/Users/srbaker/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
/Users/srbaker/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
Tasks: TOP => ofn:sample_data
(See full trace by running task with --trace)
```

We should probably get on this ASAP as this could turn away a lot of potential volunteer contributors before they even start.

### Impact and timeline
- Impacts first time setup for new/volunteer devs.

**Comment by pacodelaluna** [comment]
I was bumping into this issue. It seems that the payment amount is not set up during the order workflow related to the Rake task. Then it is generating a `balance_due` payment_state blocking the shipment process.
