### ISSUE TITLE
Homepage footer logo is poor quality & low resolution

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#9026]
## Description

The footer on the OFN uk platform displays a low res OFN logo. 

## Expected Behavior

There should be a high quality image of our logo

## Actual Behaviour

The image is pixellated

## Steps to Reproduce

1. Go to OFN UK homepage 
2. Scroll to the bottom
3. See poor quality logo displayed
4.

## Animated Gif/Screenshot

<img width="308" alt="Screenshot 2022-03-22 at 10 53 41" src="https://user-images.githubusercontent.com/100226210/159466151-1fc49248-64ab-4b31-a7e6-a22c7b0c13fa.png">

## Severity
bug-s5
Visible on homepage to all users and gives a poor impression

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Replace image with higher res version

**Comment by lin-d-hop** [comment]
@BethanOFN I think you might be able to fix this.
Have a look in Super Admin -> Configuartion -> Content. You should be able to change this logo to a higher res one.

Did you check if this is also a problem on other instances? It is often the case that if something exists on UK prod that is related to UK specific content. A good thing to check before opening a general issue. If it is a UK specific thing we should have the power to fix that in the UK team

**Comment by BethanOFN** [comment]
Issue resolved:
<img width="407" alt="Screenshot 2022-03-22 at 14 22 45" src="https://user-images.githubusercontent.com/100226210/159503941-3c3d9c18-c00f-4d93-b3b6-178e04521f8c.png">
