### ISSUE TITLE
Remove radio button asking for closed associated adjustments

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9027]
## Description
**- As a:** enterprise user
**- On page:** `/admin/orders/XXXXX/edit` (order edit page)
**- I want to be able to do:** 
When changing the shipping method, I don't want to see the radio buttons on associated adjustments.

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/cfa93727-60d6-4bcd-9db4-34ea0e45ec33)

According to this thread: https://github.com/openfoodfoundation/openfoodnetwork/pull/7520#issuecomment-840718616 it's a leftover from Spree we can now remove

## Acceptance Criteria & Tests

1. Log in as enterprise user
2. Go to an edit order page
3. Edit the shipping method
4. See the radio buttons do not appear anymore

**Comment by RachL** [comment]
@openfoodfoundation/core-devs can this be a good-first-issue?

**Comment by jibees** [comment]
> @openfoodfoundation/core-devs can this be a good-first-issue?

Sure!

**Comment by Liberatys** [comment]
@RachL I this up for grabs? :D

**Comment by RachL** [comment]
@Liberatys yes go for it! Don't hesitate to join our Slack or ping here if you feel stuck :)
