### ISSUE TITLE
User guide signposting for "Pricing irregular, indivisible meat items"

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#903]
Hi Sally.  
The user guide is great  -thanks for all your work on it.  
Just one small issue: When I click on 'Pricing irregular, indivisible meat items' (see below) it takes me to the description of adding variants
![screenshot 2016-04-13 14 38 16](https://cloud.githubusercontent.com/assets/10517702/14495052/bb0d03ac-0185-11e6-9757-baf15468b5c6.png)

**Comment by sstead** [comment]
Thanks Nick, user guide feedback is super helpful to me, keep it coming! I've fixed that link. If you spot smaller bits and pieces feel free to list them here - http://community.openfoodnetwork.org/t/user-guide-testing-feedback/217
