### ISSUE TITLE
"Rename" function broken (taxonomies)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9031]
## Description

There are different ways one can rename taxonomies. By visiting `/admin/taxonomies/<taxon_id>/edit`, one can:
i) edit the Name field
ii) right click on the taxon; select Edit
iii) right click on the taxon; select Rename

This issue is about option iii): it currently takes no effect whatsoever.

## Expected Behavior

Editing a taxon name by right clicking on the taxon and selecting Rename should change its name.

## Actual Behaviour

Right clicking on the taxon and selecting Rename takes no effect.

## Steps to Reproduce

As superadmin:
1. Visit `/admin/taxonomies/<taxon_id>/edit`
2. Right click on the taxon
3. Select Rename and change the name
4. Click Update, or on the "Back to Taxonomies list"
5. Check whether the change took effect -> see that it didn't

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/159664736-83f54cf7-7543-4156-946f-b0266ca0f6c5.png)

## Workaround

You can still change the taxonomy name by using steps i) and ii) (see Description section, above)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.1.22
* Browser name and version: Firefox 96
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

Maybe related to:
https://github.com/openfoodfoundation/openfoodnetwork/pull/8678

**Comment by lin-d-hop** [comment]
@tschumilas do you want to select this as your S3 given the last one was closed?

**Comment by jibees** [comment]
@brittneyhoneycutt Done, and thanks!

**Comment by brittneyhoneycutt** [comment]
Hi! For some reason, I can't get delete to work using the same menu (trying to locate the bug with rename). I keep getting the error that base_url.close is not a function. Has anyone had any experience with this issue?

**Comment by jibees** [comment]
@brittneyhoneycutt 

I can reproduce the bug: the rename action has no effect, and throws a javascript error seen in the console:
![2022-04-13 10 23 54](https://user-images.githubusercontent.com/296452/163133278-732674ce-4e88-4e94-a653-48b2901774ba.gif)

Not sure to understand the bug you're facing of... Would you like to add some screenshot/screencast?
Thanks! 🙏

**Comment by brittneyhoneycutt** [comment]
Thank you so much for your help! I am glad the issue does not just pertain to my local copy. Going forward, I will investigate the clone() method and try to seek a solution.

**Comment by jibees** [comment]
As I've been reading the code behind, I guess there are at least two issues :
 - One is due to this `clone()` method which should be easy to resolve. Then, rename, move and delete will be functionnal.
 - The other one is triggered when you try to rename the first taxon, on the top of the list, which is the parent. When you rename it with a righ-click (1),  and then you save, the form is submitted with the input type text (2) value as the old name. So the old name is kept.
<img width="768" alt="Capture d’écran 2022-04-14 à 09 38 31" src="https://user-images.githubusercontent.com/296452/163337588-31261020-aa9f-434a-8b25-9ccf754a4081.png">
