### ISSUE TITLE
$ not £ on backend screens of UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#904]
at some point we need to replace $ with £
this doesnt affect the shopfront so not urgent
![screenshot 2016-04-13 15 04 27](https://cloud.githubusercontent.com/assets/10517702/14496161/330af964-018a-11e6-9adf-10575ba9750d.png)

**Comment by OliverUK** [comment]
Here is what it looks like on UK production:
![screen shot 2016-12-09 at 15 07 48](https://cloud.githubusercontent.com/assets/17590921/21053452/5ce1fcca-be21-11e6-8ea3-706044f1b613.png)

And here is what it looks like on UK staging:
![screen shot 2016-12-09 at 15 07 19](https://cloud.githubusercontent.com/assets/17590921/21053464/6ae90f7a-be21-11e6-837c-5d2259013551.png)

Bulk Order Management is the only place that I'm aware of where this was incorrect. @NickWeir63  are you aware of any other places?
