### ISSUE TITLE
Property filters on shopfronts not functioning

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#9046]
## Description

User clicks to apply any of the properties filters to items (e.g. certified organic, nut free, vegan etc) and no filtering occurs. Raised by customer of one specific hub and I've replicated across multiple hubs. 

## Expected Behaviour

Clicking a property filter on a shop should filter the items displayed to those tagged with the property (e.g. clicking certified organic should show only items with the certified organic property). 

## Actual Behaviour

Clicking a property filter does not trigger any filtering. Applying a category filter first functions as expected, but clicking a category filter _after_ clicking a property filter also fails to filter any products. 

## Steps to Reproduce

1. Go to any shopfront with properties e.g. Tamar Valley Food Hub
2. Click a property filter (e.g. certified organic, gluten free)
3. Observe lack of filtering of item lists
4. Now apply a category filter (e.g. herbs & spices)
5. Observe lack of category filtering

## Animated Gif/Screenshot

![Kapture 2022-03-29 at 09 36 09](https://user-images.githubusercontent.com/100226210/160573584-f8892329-055f-46a1-b2b3-fcd2bbc113db.gif)

## Workaround

No workaround

## Your Environment

* Version used: UK prod
* Browser name and version: Version 99.0.4844.51 (Official Build) (arm64)
* Operating System and version (desktop or mobile): Mac OS Big Sur 11.6.2

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Not sure why but distributor 1785 can't handle any properties search:

`curl 'https://staging.openfoodnetwork.org.uk/api/v0/order_cycles/3581/products.json?distributor=1785&page=1&per_page=10&q%5Bname_or_meta_keywords_or_variants_display_as_or_variants_display_name_or_supplier_name_cont%5D=&q%5Bwith_properties%5D%5B%5D=1'`


This somehow triggers a bad query (the 422 error):
`{"exception":"PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list\nLINE 12: ...id\" = $6) GROUP BY \"spree_products\".\"id\" ORDER BY spree_prod...\n                                                              ^\n"}`

Indeed, this does not seem to relate to enterprise relationships. I've revoked them all for this enterprise, and set them at the product level instead: this triggered the same error...

**Comment by filipefurtad0** [comment]
Ok, this seems to have been introduced by the `Display ordering in shopfront` feature,  possibly [in this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/7712).

This is set under `/admin/enterprises/<distributor_name>/edit#!/shop_preferences`

![image](https://user-images.githubusercontent.com/49817236/162783429-f55cedf8-951b-4ac1-9024-37074b135f23.png)

Ping @jibees @BethanOFN.
