### ISSUE TITLE
Form fields get erased on error in new product page

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#9047]
## Description
**- As a:** enterprise user and super admin
**- On page:** `/admin/products/new`
**- I want to be able to do:**  When creating a new product, I get an error message but the data I typed in the form gets erased as well. We must keep that data so the user doesn't need to type in from scratch.

## Acceptance Criteria & Tests

1. Log in as enterprise user
2. Go to  `/admin/products/new`
3. Create a new product and fill all mandatory field except one
4. Submit
5. See the error message about the mandatory field, and see that all the selection / data you previously typed are still there

**Comment by RachL** [comment]
Closing as handled in #9067
