### ISSUE TITLE
[Split Checkout] Error 422 on step '1 - Your details' - Update highlighted fields

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9056]
## Description
While trying to check out with split checkout active on staging AU I have observed an Error 422 in the console, going along with the flash message: 'Saving failed, please update the highlighted fields.' It gets triggered when clicking 'Next - Payment method' but there is no highlighted field...
I have tried editing all visible fields and changing their content without success - I wasn't able to proceed to step '2 - payment method'.
This is not always seen, the steps to reproduce are currently unknown.

## Expected Behavior
There shouldn't be an Error 422.
There shouldn't be a flash error asking to update highlighted fields when there are no highlighted fields..

## Actual Behaviour
Error 422 is seen in the console and the flash error is displayed without any highlighted field.

## Steps to Reproduce
1. Deploy v4.1.23 to staging AU ([latest commit](https://github.com/openfoodfoundation/openfoodnetwork/commit/913a4560d1c8bb254ae13b2d8d788f3566762033))
2. Toggle split checkout ON
3. As hub manager verify that cancellation of orders is enabled (I used 'Konrad Testhub' - happy to provide login data)
4. As hub manager have an order cycle open
5. As customer log in
6. Shop at Konrad Testhub
7. Go to checkout
8. Enter you data
9. See the errors

## Animated Gif/Screenshot
![grafik](https://user-images.githubusercontent.com/1790176/161044876-d055ac2a-0dc2-4c94-ad4d-7ef438ef4c1f.png)

## Workaround
No workaround.

## Severity

Not sure, since it is not yet in production.

## Your Environment

* Version used: 4.1.23 on staging AU
* Browser name and version: Firefox 98.0.2 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTE Desktop

**Comment by jibees** [comment]
Can't reproduce this one on my local setup. 
Sure that every fields was filled?

If you could reproduce it on the staging server, please could you:
 - Provide a screenshot that actually shows the whole screen?
 - Copy as CURL the request that actually respond a 422 and paste it:
<img width="535" alt="Capture d’écran 2022-04-01 à 14 59 38" src="https://user-images.githubusercontent.com/296452/161268457-f2aaf646-bafa-4f31-98ab-bcded3e27a42.png">
 - Copy the whole response of that request and paste it:

<img width="1057" alt="Capture d’écran 2022-04-01 à 15 00 53" src="https://user-images.githubusercontent.com/296452/161268669-b1a8e02d-74bb-4a07-9da9-b3b87605a8b9.png">


Thanks! 🙏

**Comment by drummer83** [comment]
First of all I could not reproduce the error on Chromium - not sure if this has any impact.

Yes, I am sure I filled all fields. Here is a screen video:
https://user-images.githubusercontent.com/1790176/161566340-01e485fc-7614-4da1-92d3-f2656b853af9.mp4

This is the console (after seeing the error twice):
![image](https://user-images.githubusercontent.com/1790176/161566547-50806b5b-27d3-4745-8da8-da3f353b5e3d.png)

This is the cURL of the 422-POST entry (sorry for the formatting - can I improve this?):
`curl 'https://staging.openfoodnetwork.org.au/checkout/details' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0' -H 'Accept: application/vnd.cable-ready.json, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://staging.openfoodnetwork.org.au/checkout/details' -H 'x-requested-with: XmlHttpRequest' -H 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' -H 'X-CSRF-TOKEN: xcesYaSKhW25hP7Uktd1-gVTIIeS0Aiz4Ndd_XcS9jQFpmZhCXipwQ9m4Fa5MM3CIAndz9WOJZhKnKXRCjen3A' -H 'Origin: https://staging.openfoodnetwork.org.au' -H 'Connection: keep-alive' -H 'Cookie: __stripe_mid=fbbd75f4-e133-4786-a813-4133a8e3b6ed12aed7; __stripe_sid=6a1d43b3-10a5-4389-8d34-a1320ce7489b596b97; cookies_consent=cookies_consent; _pk_id.3.cd81=d95c96ab2c62318c.1649079678.; _pk_ses.3.cd81=1; _pk_id.3.32b3=dff740dd72244594.1649079678.; _pk_ses.3.32b3=1; XSRF-TOKEN=JgLL3p-3ALjkx9kJaKEgbzdW5oh8j6_AB-TjOgMTqjTmYwHeMkUsFFIlx4tDRphXEgwbwDvRguutrxsWfjb73A; _ofn_session_id=5abbb0a843d16084b840a6d747ef30ba' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'TE: trailers' --data-raw '_method=put&authenticity_token=tw6T0AAFAzq_ie80Dk3Lb8rVgRBDfTzgD6pDgWrT0OTMoG_orIADdRK3qjXXUuEsJE4W5ljYOxVJagATboZmOg&order%5Bbill_address_attributes%5D%5Bfirstname%5D=Jane&order%5Bbill_address_attributes%5D%5Blastname%5D=Doe&order%5Bemail%5D=kunde%40konradsachse.de&order%5Bbill_address_attributes%5D%5Bphone%5D=123&order%5Bbill_address_attributes%5D%5Baddress1%5D=17+rue+de+la+chevre&order%5Bbill_address_attributes%5D%5Baddress2%5D=&order%5Bbill_address_attributes%5D%5Bcity%5D=Metz&order%5Bbill_address_attributes%5D%5Bzipcode%5D=57000&order%5Bbill_address_attributes%5D%5Bcountry_id%5D=12&order%5Bbill_address_attributes%5D%5Bstate_id%5D=1061493586&order%5Bsave_bill_address%5D=0&shipping_method_id=720&order%5Bship_address_attributes%5D%5Baddress1%5D=&order%5Bship_address_attributes%5D%5Baddress2%5D=&order%5Bship_address_attributes%5D%5Bcity%5D=&order%5Bship_address_attributes%5D%5Bzipcode%5D=&order%5Bship_address_attributes%5D%5Bcountry_id%5D=12&order%5Bship_address_attributes%5D%5Bstate_id%5D=1061493586&order%5Bsave_ship_address%5D=0&order%5Bspecial_instructions%5D=&commit=Next+-+Payment+method'`

**Comment by filipefurtad0** [comment]
I've tried checking out on that shop with another user and experienced no issues. No answers, but some thoughts below.

I've looked on that order in the DB:

```
   id   |   number   | item_total | total | state | adjustment_total | user_id |         created_at         |         updated_at         | completed_at | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |         email         | special_instructions | distributor_id | order_cycle_id | currency | last_ip_address | customer_id | created_by_id | included_tax_total | additional_tax_total 
--------+------------+------------+-------+-------+------------------+---------+----------------------------+----------------------------+--------------+-----------------+-----------------+---------------+----------------+---------------+-----------------------+----------------------+----------------+----------------+----------+-----------------+-------------+---------------+--------------------+----------------------
 532581 | R632827840 |       2.00 |  2.00 | cart  |             0.00 |    7991 | 2022-03-31 11:36:44.757064 | 2022-04-04 14:55:52.005795 |              |                 |                 |          0.00 |                |               | kunde@............... |                      |           2507 |           3797 | AUD      | 185.209.105.111 |        7068 |          7991 |               0.00 |                 0.00
(1 row)
```

and to that user / customer:

```
  id  |                                                        encrypted_password                                                        |    password_salt     |         email         | remember_token | persistence_token | reset_password_token | perishable_token | sign_in_count | failed_attempts | last_request_at |     current_sign_in_at     |      last_sign_in_at       | current_sign_in_ip | last_sign_in_ip |         login         | ship_address_id | bill_address_id |         created_at         |         updated_at         | authentication_token | unlock_token | locked_at | remember_created_at |                  spree_api_key                   | reset_password_sent_at | api_key | enterprise_limit | locale |  confirmation_token  |        confirmed_at        |    confirmation_sent_at    | unconfirmed_email 
------+----------------------------------------------------------------------------------------------------------------------------------+----------------------+-----------------------+----------------+-------------------+----------------------+------------------+---------------+-----------------+-----------------+----------------------------+----------------------------+--------------------+-----------------+-----------------------+-----------------+-----------------+----------------------------+----------------------------+----------------------+--------------+-----------+---------------------+--------------------------------------------------+------------------------+---------+------------------+--------+----------------------+----------------------------+----------------------------+-------------------
 7991 | 930bd85e2d5ed06a2c2e9803c26f9cda8df0e2e8c907336d919bb880d7b1b00ea8e30fec14b1aa69d9a06c5db7d9c8029ca1e78d27470464d91c126419301c9c | pei8zw9LhHrP4kF-uTyv | kunde@konradsachse.de |                |                   |                      |                  |            12 |               0 |                 | 2022-04-04 14:51:34.164462 | 2022-04-04 14:02:26.620709 | 185.209.105.111    | 185.209.105.111 | kunde@konradsachse.de |                 |                 | 2022-03-29 21:29:28.782754 | 2022-04-04 14:51:34.165074 |                      |              |           |                     | ee34c5a04212a2d7cd5c5e306678ef5cff090e7bb0eb86a3 |                        |         |                5 | en_AU  | RuKFc3U8uEeRygYMyrxM | 2022-03-29 21:29:43.014177 | 2022-03-29 21:29:28.782981 | 
(1 row)
```

What's strange here is billing and shipping address are empty, although this user has placed orders before. The order is stuck on the cart state, also no shipping or billing address.

Since we're dealing with a pick-up delivery method the hub's address should become the ship address for that order. Don't know why this is happening. My only clue would be that `ß` symbol, that somewhere the DB is not handling this correctly. Here's the hubs address, it displays incorrectly in SQL but so far correctly in the UI:

```
   id   | firstname | lastname |   address1    | address2 |   city    | zipcode | phone | state_name | alternative_phone |  state_id  | country_id |         created_at         |         updated_at         | company |  latitude   |  longitude  
--------+-----------+----------+---------------+----------+-----------+---------+-------+------------+-------------------+------------+------------+----------------------------+----------------------------+---------+-------------+-------------
 347053 | Jane      | Doe      | Teststra<C3><9F>e 1 |          | Testungen | 12345   | 123   |            |                   | 1061493592 |         12 | 2022-03-29 21:32:03.357746 | 2022-03-29 21:32:03.357746 | unused  | -36.9847807 | 143.3906074
(1 row)
```

**Comment by jibees** [comment]
Ok, I couldn't reproduce this issue at all... 
Maybe fixed with related PRs... 
Feel free to re-open it if needed!

**Comment by drummer83** [comment]
I have this on staging UK now as well...
Here is what I did:
- register a new user (kunde2@konradsachse.de)
- confirm the email address
- log in
- shop at Konrad Testhub
- Click on cart
- Click on checkout
- Fill in all the fields
- Click on 'Next - Payment method'
- See the error

The thing is I repeated the steps above for kunde3 (without 'ß') and kunde4 (with 'ß') and it worked for them. So no big news on the root cause, but it is still there.

**Comment by audez** [comment]
ok guys this completes and kinda confirm my previous comment.
I was doing some tests on a shop that only had a "pickup" method, and I was able to checkout several times without trouble. Then at some point, I was unable to checkout and was stuck at step 1 with the 422 error (obviously all fields were filled in). 
I decided to create a "delivery" method, and I tested to checkout with that, and it worked fine. 
I then chose the "pickup" method again, and checking out was now ok again. 

As you can see in the screenshots, two fields were missing from the 422 request:
order[bill_address_attributes][id]
order[ship_address_attributes][id]

##KO request
![Screen Shot 2022-10-14 at 11 41 52](https://user-images.githubusercontent.com/28386648/195817401-097bb78e-3877-4196-83de-d36307c25cca.png)

##OK request
![Screen Shot 2022-10-14 at 11 42 02](https://user-images.githubusercontent.com/28386648/195817945-6e40913a-8c38-4d7c-a63f-eff128ed7059.png)

As @filipefurtad0 said in a previous comment that "Since we're dealing with a pick-up delivery method the hub's address should become the ship address for that order.", I guess that these fields are required to make the request work. And for a weird reason they're sometimes not sent..But if you trigger a delivery request, then you can make the pickup request work again.
Hope this can help in some way!

**Comment by filipefurtad0** [comment]
This seems related:

![image](https://user-images.githubusercontent.com/49817236/210354010-41a7ccc4-77c6-4144-8883-8432ae2cec83.png)

It might be the same issue (422), as the error is only triggered when clicking `Next - Order Summary`. There is a default/saved card for this user, and the card is valid, so it does not look Stripe related.

There is an additional message, which is visible before attempting to proceed to the `/summary` page.
`Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://js.stripe.com’) does not match the recipient window’s origin (‘https://staging.openfoodnetwork.org.uk’).`

Clicking a second time proceeds to the `/summary` page with no issues.

**Comment by RachL** [comment]
So we know how to reproduce? I've tried with a saved card but couldn't... is there something else to set up?

**Comment by filipefurtad0** [comment]
I was able to reproduce it on master for different cards/customer/hubs/browsers. It seems to be introduced by the recent design changes, at least I could not reproduce it before https://github.com/openfoodfoundation/openfoodnetwork/pull/10154. Opening a separate issue as the present one exists before these changes.

**Comment by mkllnk** [comment]
I couldn't reproduce this either. But I opened a pull request to improve the error message. So hopefully will know more if this happens again. Until then we can close this, I think.
