### ISSUE TITLE
How to translate emails contents / titles... do we have to go into the code?

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#906]
In the French instance, automatic emails are partially / sometimes not accurately translated, both in title and content (see image bellow)
How can we easily translate that and change the content?
Do we have to go into the base somewhere, or could we imagine to do it in the configuration panel (by super-admin)
It's very obscure for me for the moment, and I think @blancnic and  @gnollet have not yet found how to do (if I understood well ;-))
Any clue?
![image](https://cloud.githubusercontent.com/assets/8135376/14510156/4457c350-01d0-11e6-9b15-5163bbdab0b2.png)

**Comment by blancnic** [comment]
I'm going to investigate

**Comment by blancnic** [comment]
For the translation of the title, we have to change it in 3 files :+1: 
**app/mailers/enterprise_mailer.rb**:    mail(subject: "Please confirm your email for #{@enterprise.name}",
spec/mailers/enterprise_mailer_spec.rb:      expect(mail.subject).to eq "Please confirm your email for #{enterprise.name}"
spec/mailers/enterprise_mailer_spec.rb:      expect(mail.subject).to eq "Please confirm your email for #{enterprise.name}"

**Comment by blancnic** [comment]
We can change by that : 
mail(subject: = t "spree_admin_single_enterprise_alert_mail_confirmation" #{@enterprise.name}",
What do you thing ? 
We will have "Please confirm **the **email address for" instead of "Please confirm **your** email address for"

**Comment by mkllnk** [comment]
Good.

But I just found something even better: http://guides.rubyonrails.org/i18n.html#translations-for-action-mailer-e-mail-subjects

```ruby
mail(subject: default_i18n_subject(enterprise: @enterprise.name)),
```

The locale needs this entry then:
```yml
en:
  enterprise_mailer:
    confirmation_instructions:
      subject: "Please confirm the email address for %{enterprise}"
```

Try that and see if it works.

**Comment by blancnic** [comment]
Nice. I will try it

**Comment by blancnic** [comment]
@mkllnk I tried to test it on my dev env but impossible to send email. I tried with delayed-jobs but it didn't work :(

**Comment by mkllnk** [comment]
Have you tried deactivating delayed job in `config/initializers/delayed_job.rb`?

**Comment by blancnic** [comment]
Sorry but I don't know how to do that. I launched manually delayed_job but I don't think it works well....

**Comment by mkllnk** [comment]
I just looked at this again. The spec you changed covers this change already. So if `spec/mailers/enterprise_mailer_spec.rb` passes, everything should be alright.

**Comment by blancnic** [comment]
I have an error in final tests:
 ArgumentError:
  wrong number of arguments (1 for 0)
     # ./app/mailers/enterprise_mailer.rb:16:in `confirmation_instructions'

**Comment by mkllnk** [comment]
Have a look at https://github.com/mkllnk/openfoodnetwork/commit/f3fb158e014cbc6d4ebaf96707e95617a7f7dc6e.

There were three things I fixed:

- The translations in the locale had the wrong indentation. It was under `devise`.
- I updated the spec with the new text.
- I had to use the I18n.translate function `t`, because the `default_i18n_subject` function in our version of rails doesn't support variables in translations yet: http://apidock.com/rails/v3.2.13/ActionMailer/Base/default_i18n_subject. The newest version does.

You can pull my changes with:

    git fetch git@github.com:mkllnk/openfoodnetwork
    git merge f3fb158e014cbc6d4ebaf96707e95617a7f7dc6e

Would you like to translate the subject of the welcome email in the same way? If that works, you can open a pull request and I'm happy to get these changes in.

**Comment by blancnic** [comment]
Many thanks for your help. 
git fetch git@github.com:mkllnk/openfoodnetwork->failed
I will take a look to the other translation and contact Myriam to know what she wanted to change more.

**Comment by blancnic** [comment]
@myriamboure : ok for the title, can you explain more what do you want to modify in the text of the mail? Thanks

**Comment by mkllnk** [comment]
@blancnic You can't merge if the fetch didn't work. Try `git fetch https://github.com/mkllnk/openfoodnetwork.git` first, then merge.

**Comment by blancnic** [comment]
@mkllnk :PR #937
