### ISSUE TITLE
Customer Accounts should capture Users/customer who place orders as guests

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#907]
If a registered user/customer checks out as a guest their order doesn't show in their Customer Account, even though they used their email. 

Rob says Customer Accounts is using a method called 'user#orders_by_distributor'
Which is not picking up customer orders, only User orders

As part of fixing this we should also ideally prompt a person who does checkout as guest, and tries to use a known User email, to login. This is a security thing, to disable people from placing orders for users without their knowledge.

**Comment by stveep** [comment]
This is a method that I added when updating the account page (is this what you mean by Customer Account?). I didn't appreciate that Customer was different to User in this respect. I can probably change it to show orders with the users email as well, though i agree that forcing the login is the best way.

**Comment by OliverUK** [comment]
It does make sense that login should be required if a known email is used.

**Comment by RachL** [comment]
This was prevented/resolved  in #1159. Closing
