### ISSUE TITLE
Welsh website translation incorrectly showing English phrasing

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#9082]
## Description

When viewing the OFN UK website in Welsh, the text displayed on a shopfront with an open order cycle contains English words when stating the time until the cycle closes. The Welsh (cy) transifex file gives the correct translation so the issue must be in the code. In transifex the key is 'key:distance_in_words' for the variable.

## Expected Behavior

All code for the Welsh website version should reference the Welsh (cy) transifex file.

## Actual Behaviour

Some text is incorrectly shown in English.

## Steps to Reproduce

1. Go to OFN UK and select 'Gymraeg' via the globe icon at top right
2. Navigate to a shop with an open order cycle
3. In the box at top right where it states when the order cycle closes, part of the text is in Welsh and the variable time text is incorrectly displayed in English

<img width="625" alt="Screenshot 2022-04-11 at 10 41 35" src="https://user-images.githubusercontent.com/100226210/162808037-510678f7-3a8b-49fe-8bd0-f53765ec377e.png">

## Severity
Assigning this as **bug-s4** - this reflects poorly on our support of Welsh language at a time we are launching Welsh food hubs.

**Comment by lin-d-hop** [comment]
Hrm, this french shopfront currently has this showing correctly.
https://coopcircuits.fr/la-cagette-aixoise/shop#/home

So not a translation key problem....

**Comment by RachL** [comment]
@lin-d-hop @BethanOFN I think @jibees did a fix for this in https://github.com/openfoodfoundation/openfoodnetwork/pull/7156

Example of a key in transifex: `datetime.distance_in_words.x_days`

**Comment by RachL** [comment]
@BethanOFN do you know if this is still a problem?

**Comment by BethanOFN** [comment]
Notice this has resolved so closing
