### ISSUE TITLE
[Split Checkout] Previous order information missing in cart

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9085]
## Description
When placing a second order while the order cycle is still open, a note is displayed, telling you to check the cart for already ordered items:
![image](https://user-images.githubusercontent.com/1790176/163053704-10bbc72c-7591-4574-ab5f-86bc8e6166a9.png)
For split checkout this is not true, because in the cart only the items of the current order (which has not yet checked out) are shown. The information about the previous order(s) is missing.

## Expected Behavior
Just like in legacy checkout, the previously ordered items should be displayed in the cart.

## Actual Behaviour
Only the items of the current order are displayed in the cart.

## Steps to Reproduce
1. Make sure you are shopping in an order cycle which allows changing and cancelling orders
2. Place the first order
3. Go back to shop (click 'Shopping @ Shop_xy')
4. Begin second order
5. Before finishing checkout observe note: You have an order for this order cycle already. Check the cart to see the items you ordered before. 
6. Click on 'cart' in the note. It redirects to /cart#/bought-products
7. Observe that for
- Legacy checkout: Cart is displayed incl. the previous items
- Split checkout: Cart is only showing the new items

## Animated Gif/Screenshot
Compare split checkout on the left and legacy checkout on the right:
![Peek 2022-04-12 22-48](https://user-images.githubusercontent.com/1790176/163054668-8fc27174-dc41-4e38-8df4-d48d7e3445e8.gif)

## Workaround

No workaround.

## Severity

Not sure because split checkout is still in development.

## Your Environment

* Version used: 
* - for split checkout: [762b6fa](https://github.com/openfoodfoundation/openfoodnetwork/commit/762b6fad65cd4411d67a8ca70fac43e9549d16a9)
* - for legacy checkout: [20142ca](https://github.com/openfoodfoundation/openfoodnetwork/commit/20142ca632955e56502da669f5ce2616f80f8e3f)
* Browser name and version: Firefox 99.0
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by jibees** [comment]
@RachL yes, for sure!
