### ISSUE TITLE
$NaN in subscriptions back office

### ISSUE THREAD

**Issue by RonellaG** [openfoodfoundation/openfoodnetwork#9100]
## Description

The admin for enterprise ID#3651 created a new order cycle with 2 products that were appearing as $NaN in the subscriptions back office.

Customer support confirmed that subscription orders had been correctly placed and processed by the system. However, it is a confusing back office experience and wastes enterprises time to check that orders are placed and processed correctly, especially when the workaround of creating a new order cycle does not alleviate the problem.

## Expected Behavior

@RachL mentioned in [this thread](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1615379974016200?thread_ts=1615373982.015700&cid=CG7NJ966B) that the "$NaN" sometimes appears in the subscription back office when there is no upcoming order cycle that includes the relevant products. This is a display issue but does not impact order placement or processing. The workaround she suggested was that if you open an order cycle that contains the product or set it to open in the future, then the $NaN goes away. 

## Actual Behaviour

However, when one of our hub admin's created a new order cycle to fix this, the $NaN did not go away. For all subscriptions where variants were added at the same time, all price estimates are displayed in the subscription back office as well as in Metabase. For the 2 specific subscriptions where 2 product variants were added to each subscription at a date after the subscription was created, the price estimate is not displayed in Metabase and appears as $NaN in the back office even after an order cycle is opened. Refer screenshots.

## Steps to Reproduce
Order cycle name "CYCLE 10: 15 April 22 (Week 15)" (OC ID #12116)

Product info
Product name: Full cream milk, 2 litre
Product ID: #15982
Variant ID: #40925
Supplier Name: Saint David Dairy
Supplier ID: # 826
Created at: August 28, 2020, 12:18 AM (UK time)
Update at: October 22, 2020, 6:40 PM (UK time)
Inventory override by Merri Food Hub
Supplier info: Price $5, On hand = 0, On demand = No
MFH: Price $5, On hand = On demand, On demand = Yes

Subscription info
Subscription ID: 405

![image](https://user-images.githubusercontent.com/68315791/163512965-328c5987-1670-486f-b870-2b7e286bf136.png)

Red flag! There is nothing in the Price estimate field in Metabase for Variant ID: #40925!
![image](https://user-images.githubusercontent.com/68315791/163513016-a8c84832-7fe7-4a7a-b22c-d0ae06f3061f.png)

Product info
Product name: Campo
Product ID: #23970
Variant ID: #62890
Supplier Name: Back Alley Bakes
Supplier ID: # 3709
Last updated the same time it was created
No inventory overrides

Subscription info
Subscription ID: 396

![image](https://user-images.githubusercontent.com/68315791/163513065-360e8078-2742-4b75-ab10-9f9f84d75b47.png)

Red flag! As with the other subscription, there is nothing in the Price estimate field in Metabase for Variant ID: #62890!
![image](https://user-images.githubusercontent.com/68315791/163513094-3499b792-5a70-47cb-b773-c65d4f6b36a8.png)

## Workaround

The workaround does not work in this scenario.

## Severity
S2

## Your Environment

* Browser name and version: Google Chrome Version 100.0.4896.88 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): MacBook Pro MacOS Catalina Version 10.15.7 (19H1824)

**Comment by filipefurtad0** [comment]
Thanks @RonellaG and @georgethoppil for the heads up on this one.

I've reproduced this as well, in staging. Indeed the NaN does not dissapper (at least not in all cases!):

If we take a subscription associated (via schedule) to a closed OC:
- it will initially display that no upcoming OCs for that particular variant are upcoming.
- adding other variants from that closed OC
=> will display the NaN error, and mess up the sum estimate (seen while when editing the subscription)

![Peek 2022-05-02 15-48](https://user-images.githubusercontent.com/49817236/166255790-cdb7af7c-aa51-4964-a8d1-f6de2e0cd191.gif)

If we then change the order cycle dates, and:
- set it to a future time
- and edit the subscription
=> we can see that the NaN error is still there

![Peek 2022-05-02 15-50](https://user-images.githubusercontent.com/49817236/166255798-9ccb064c-f642-4614-9021-be53bdad1bf0.gif)

I think these will be the steps to take, when testing the PR.
