### ISSUE TITLE
[API] Products Endpoint

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#9105]
## What is the need / problem?
FR, UK and AU need to be able to create, find and update Products/Variants via the API.
This work will be challenging as we wish to create a robust endpoint that is Network 2.0 ready.

## Which type of users does this problem affect (and how many, if known)?
e.g. - Shoppers - Hub Managers (MCFEs) - Producers - Instance Managers - Other (Please specify)
Hub Managers

## High Level Specification
Step 1. Spike refactoring of Products/Variants #9069 
Step 2. Check and quick fixes on existing Product/Variant endpoint to enable update stock / price in short term 
Step 3: Implement . .

## Connected wishlist and discovery discussions
Standard Acceptance Criteria around documentation and controller actions as described here.

## Tracking
As this is a funded feature all time spent on this issue should be tracked in Clockify under '#9105 REST API - Products' project

**Comment by RachL** [comment]
Closing here as the work is now mapped by other epics
