### ISSUE TITLE
Check and scope functionality of /products and /products/variants

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#9106]
## Description
We have some existing API endpoints that deal with products and variants. It is not clear how functional these are or whether the documentation in Swagger is correct for what they currently do.  

We have a long-term process underway to review the product/variant data model in preparation for Network 2.0, and wish to create a public supported Product endpoint that is Network 2.0 ready. In the meantime, we have some use cases that might well be readily served with some minor fixes to the existing endpoints. This will enable us to support users to use these, while also communicating clearly that they are going to evolve and users will need to update / change when that happens.

The use cases we would like to support are:
* Create a product / variant
* Read a product / variant
* Update price and stock on a variant 
* no other updates, no deletes
* no handling of inventory overrides (as these will be retired)

This issue is to investigate the current endpoints and confirm whether / how they could support the above uses. If not, what would it take to fix them so that they can?  

## Acceptance Criteria & Tests
* Investigation of current endpoint functionality
* Develop list of issues around what would need to be done to enable above use case
* Update swagger docs if necessary to ensure accurate representation of what is possible with current endpoints

**Comment by mkllnk** [comment]
The Bulk Edit Products page uses an API v0 controller under the hood. That means that we can do everything that the page can including updating stock levels and prices.

**Comment by mkllnk** [comment]
Request:
```json
{
   "products":[
      {
         "id":16666,
         "variants_attributes":[
            {
               "id":42302,
               "on_demand":false
            }
         ]
      }
   ],
   "filters":{
      "q[name_cont]":"",
      "q[supplier_id_eq]":"",
      "q[primary_taxon_id_eq]":"",
      "q[s]":"name asc",
      "import_date":""
   },
   "page":1,
   "per_page":15
}
```

Response:

```json
{
   "products":[
      {
         "id":16666,
         "name":"$25 'Reject' Fruit Box",
         "sku":"",
         "variant_unit":"items",
         "variant_unit_scale":null,
         "variant_unit_name":"box",
         "inherits_properties":true,
         "on_hand":0,
         "price":"50.0",
         "available_on":"2020-04-13 17:26:11",
         "permalink_live":"fruit-box-1",
         "tax_category_id":1,
         "import_date":null,
         "image_url":"https://ofn-staging.s3.us-east-1.amazonaws.com/public/images/spree/products/6839/product/fruitbox.png?1603384510",
         "thumb_url":"https://ofn-staging.s3.us-east-1.amazonaws.com/public/images/spree/products/6839/mini/fruitbox.png?1603384510",
         "producer_id":2451,
         "category_id":98,
         "variants":[
            {
               "id":42302,
               "name":"$25 'Reject' Fruit Box - 1 box",
               "producer_name":"Atlas Community Food Hub",
               "image":"https://ofn-staging.s3.us-east-1.amazonaws.com/public/images/spree/products/6839/mini/fruitbox.png",
               "sku":"",
               "import_date":null,
               "options_text":"1 box",
               "unit_value":1.0,
               "unit_description":"",
               "unit_to_display":"1 box",
               "display_as":null,
               "display_name":null,
               "name_to_display":"$25 'Reject' Fruit Box",
               "variant_overrides_count":1,
               "price":"25.0",
               "on_demand":false,
               "on_hand":0,
               "in_stock":false,
               "stock_location_id":1,
               "stock_location_name":"default"
            }
         ],
         "master":{
            "id":42301,
            "name":"$25 'Reject' Fruit Box - 1 box",
            "producer_name":"Atlas Community Food Hub",
            "image":"https://ofn-staging.s3.us-east-1.amazonaws.com/public/images/spree/products/6839/mini/fruitbox.png",
            "sku":"",
            "import_date":null,
            "options_text":"1 box",
            "unit_value":1.0,
            "unit_description":"",
            "unit_to_display":"1 box",
            "display_as":null,
            "display_name":null,
            "name_to_display":"$25 'Reject' Fruit Box",
            "variant_overrides_count":0,
            "price":"50.0",
            "on_demand":false,
            "on_hand":0,
            "in_stock":false,
            "stock_location_id":1,
            "stock_location_name":"default"
         }
      },
   ],
   "pagination":{
      "results":13850,
      "pages":924,
      "page":1,
      "per_page":15
   }
}
```

**Comment by abdellani** [comment]
What's Network 2.0?  I tried to google it but I only found irrelevant results.

Are we supposed to write request specs here?

**Comment by RachL** [comment]
@abdellani it's code name for a future new feature in OFN. You can find a presentation here: https://community.openfoodnetwork.org/t/network-phase-1/1906

**Comment by RachL** [comment]
@kirstenalarsen @mkllnk now that the porduct refactor is being worked on, is this issue still up-to-date / needed?

**Comment by RachL** [comment]
As per delivery circle today: this is not needed anymore, closing!
