### ISSUE TITLE
Accounts & Billing distributor is visible in front end for users that own enterprises.

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#912]
Probably not a big deal, but something to fix at some stage.

![screen shot 2016-04-17 at 6 36 34 pm](https://cloud.githubusercontent.com/assets/2067859/14585955/8081e57e-04cb-11e6-9cc9-2662fee05dd9.png)

**Comment by stveep** [comment]
Can you explain what this is? I'm not sure how you would identify it as a special case not to be shown - is it always present and named the same? It doesn't seem to be in my sample data dump or shown on UK staging.

**Comment by oeoeaio** [comment]
Hi @stveep,

The Accounts distributor is identified by the id specified in the Spree::Config.accounts_distributor_id variable. The #account_invoice? method defined on Spree::Order in the order decorator gives an example of how to use this variable to identify an order as one that should not be treated as a regular order.

**Comment by stveep** [comment]
OK I've added to this PR along with the other improvements to this page:

https://github.com/openfoodfoundation/openfoodnetwork/pull/908
