### ISSUE TITLE
Inconsistent default visibility setting, for newly created enterprises

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9123]
## Description

Follow-up from #9087.
See Slack [thread](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1650640081691859) .

After this PR and for newly created enterprises:
- The default value in the DB for the `Enterprises` table, column `visible` is `t`
- However, after #9087 valid values are `hidden`, `only_through_links` and `public`
- This leads to having newly created enterprises invisible till one of the radio buttons is selected (and a valid value is attributed to `visible`)
- EDIT, added from #10038: Enterprises are invisible both in the enterprise list AND on the map, after creation

## Expected Behavior

For newly created enterprises:
- The default value in the DB for the `Enterprises` table, column `visible` should be ~~`public`.~~ Edit: ~~`hidden`~~ `only_through_links`.
(Updated following [discussion on Slack](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1651255901800579?thread_ts=1650640081.691859&cid=C02TZ6X00)).
- The UI should have the "Not Visible" radio-button selected

## Actual Behaviour

For newly created enterprises:
- The default value in the DB for the `Enterprises` table, column `visible` is `t`.
- The UI has no radio-button selected
- After creation, enterprises are invisible both in the enterprise list AND on the map

## Steps to Reproduce

1. Create an enterprise; note the id
2. Check the entry on the DB for that enterprise
3. Notice the default value in the DB for the `Enterprises` table, column `visible` is `t`.
4. Notice no radio button is selected on the enterprise "Primary details" page

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/164758957-6eaf79fa-f53a-4efd-bae9-a8bc06bb63c9.png)

## Severity

This seems harmless, but it's worth investigating as discussed on the [slack thread](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1650645939262759?thread_ts=1650640081.691859&cid=C02TZ6X00) .

## Your Environment

* Version used: v4.1.27
* Browser name and version: Firefox 99
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by jibees** [comment]
Hi @filipefurtad0 
I've open a PR for this one, but seems like things have changed since the issue opening date ... Would you confirm my thoughts/comments before going to Code Review ?

 - Default value was `public`. I've change to `hidden` ...
 - which is linked to _Hide all references_ in the UI (because _Hidden_ in the UI <-> `only_through_links`)

Wdyt?
