### ISSUE TITLE
List available feature toggles in the UI

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9125]
### What we should change and why (this is tech debt)

When you want to activate a new feature, you have to know it's key like `api_v1`. It would be nice if we added these to Flipper when booting the application so that you see an overview of all current feature in the feature toggle UI.

With that list of currently active feature, we can also remove old features from the database to keep it clean. That has the advantage that we can re-use feature names. This may happen accidentally, for example if someone uses `api_next` as key and two years later there's a new API and we use it again, forgetting that it has been used already. If we then had pre-existing toggles in the database, we may get random behaviour. So cleaning those up avoids that.

### Context

Non-devs want to activate feature toggles like the API and have to ask devs about the name.

**Comment by RachL** [comment]
Just for the record, keys can already be found in the UI here: `/admin/feature-toggle/features` if I'm not mistaken. At least this is how I do it.

**Comment by jibees** [comment]
You don't see available features under `/admin/feature-toggle/features` : you only see either _previously activated features_ and _currently activated features_.
To see all available features (and past features), for now, is the wiki page: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Feature-toggle-with-Flipper which must be edited for sure (and this is the _pain_ point).
Having such an interface that @mkllnk suggested will be an improvement in term of clarification for sure.

**Comment by mkllnk** [comment]
The docs enable us to add descriptions to each feature: https://www.flippercloud.io/docs/ui

It doesn't list them automatically but we could do that in the banner at the top at least. Otherwise we could go through the list of feature and add them to the database if they are not there yet.
