### ISSUE TITLE
Conditionally send cancellation email to customer when cancelling the whole order

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9128]
## Description

Since implementation of openfoodfoundation/openfoodnetwork#8766 users can choose if a cancellation email should be sent when an order is being cancelled. However this only applies when the order is cancelled because the last line item is deleted (on order edit page or BOM).

**- As a:** enterprise user
**- On page:** `admin/orders/Rxyz/edit`
**- I want to be able to do:** clicking the 'cancel' button OR by selecting 'cancel order' from the actions drop down should display the modal asking if the user is sure + if they want to send the email. Email checkbox is ticked on by default.

![image](https://user-images.githubusercontent.com/6525576/165101876-b7e5ff41-b85e-4f59-938f-8e8e550c2c10.png)

The design for this modal can be found when deleting the last item of an order.

## Acceptance Criteria & Tests

1. Log is an enterprise user
2. Cancel an order with the button
3. See the modal
4. Test the the checkbox is ticked by default and than unchecking it works

Repeat with the action dropdown and in superadmin.

**Comment by sigmundpetersen** [comment]
Yes you can 🙂 
I have assigned you and moved to In Dev

**Comment by mgrigoriev8109** [comment]
Finally got started, and had a quick question. Hope folks don't mind me asking questions as I begin contributing more and am getting used to the codebase. First off, I created a failing system test which successfully clicks on the action dropdown's Cancel Order and expects a modal to be there (one is not)

Now that I have some understanding of the code involved and before I pursue implementation any further, I wanted to ask if the best course of action is to completely remove the current action dropdown Cancel Order button's underlying logic and replace it with reusing the blue Cancel button's logic? 

**Context:**
Comparing the current "Cancel button" with the "Cancel Order from action dropdown", both are located in `app/views/spree/admin/orders/edit.html.haml` under `event_links` and `order_links` respectively.
```ruby
- content_for :page_actions do
  - if can?(:fire, @order)
      %li= event_links
    = render partial: 'spree/admin/shared/order_links'
 ```
 
 As for the two different buttons:
 
_action dropdown Cancel Order button_
The Cancel Order is currently `cancel_order_link`, can be found at the same location:
```ruby
      def cancel_order_link
        { name: t(:cancel_order),
          url: spree.fire_admin_order_path(@order.number, e: 'cancel'),
          icon: 'icon-trash',
          confirm: t(:are_you_sure) }
      end
```

 _blue Cancel button_
 The Cancel button is `cancel_event_link` which can be found in `app/helpers/spree/admin/order_helpers.rb`:
 ```ruby
       def cancel_event_link
        event_label = I18n.t("cancel", scope: "actions")
        button_link_to(event_label,
                       fire_admin_order_url(@order, e: "cancel"),
                       method: :put, icon: "icon-cancel", form_id: "cancel_order_form")
      end
```
This button has two associated functions in `app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb` which I'd like to reuse to avoid duplication in the codebase. The first of these is the event listener, which listens for the form to be submitted (the blue Cancel button to be clicked)
```javascript
initCancelOrder = function() {
    $('#cancel_order_form').submit(function(e){
        ofnCancelOrderAlert((confirm, sendEmailCancellation, restock_items) => {
            if (confirm) {
                var redirectTo = new URL(Spree.routes.cancel_order.toString());
                redirectTo.searchParams.append("send_cancellation_email", sendEmailCancellation);
                redirectTo.searchParams.append("restock_items", restock_items);
                window.location.href = redirectTo.toString();
            }
        });
        e.preventDefault();
        return false;
    });
}
```
and the second, which I won't copy paste, is `ofnCancelOrderAlert` which actually generates the modal.

**Comment by drummer83** [comment]
Hi @mgrigoriev8109, 
great seeing you picking this up! :muscle: 
I will let the devs comment on your questions. As the author of this issue I am just wondering if I was clear about the fact, that we do already have the modal which should be displayed. You can see it when deleting the last item of an order. So you might want to reuse that as well. 
And for your information: I believe in the meantime we have implemented a second checkbox on that modal asking if the products should be put back into stock after cancellation.

**Comment by mgrigoriev8109** [comment]
Thanks @drummer83 ! I was planning on re-using the second function I mentioned, `ofnCancelOrderAlert` as it is the one I believe displays the modal, and it does contain the checkbox for restocking items:
```javascript
ofnCancelOrderAlert = function(callback, i18nKey) {
  if (i18nKey == undefined) {
    i18nKey = "js.admin.orders.cancel_the_order_html";
  }
  $('#custom-confirm .message').html(
    ` ${t(i18nKey)}
      <div class="form">
        <input type="checkbox" name="send_cancellation_email" value="1" id="send_cancellation_email" checked="true" />
        <label for="send_cancellation_email">${t("js.admin.orders.cancel_the_order_send_cancelation_email")}</label><br />
        <input type="checkbox" name="restock_items"  id="restock_items" checked="checked"/>
        <label for="restock_items">${t("js.admin.orders.restock_items")}</label>
      </div>`);
  $('#custom-confirm button.confirm').unbind( "click" ).click(() => {
    $('#custom-confirm').hide();
    callback(true, $('#send_cancellation_email').is(':checked'), $('#restock_items').is(':checked'));
  });
  $('#custom-confirm button.cancel').click(() => {
    $('#custom-confirm').hide();
    callback(false)
  });
  $('#custom-confirm').show();
}
```

And, as you mention it's called in both `initCancelOrder` inside the event listener which waits for the form to be submitted, and also inside of `app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee` when the last item of an order is deleted.

**Comment by drummer83** [comment]
Hey @openfoodfoundation/core-devs,
could you have a quick look at this and confirm if Mikhail is on the right track here https://github.com/openfoodfoundation/openfoodnetwork/issues/9128#issuecomment-1145047438?
@mgrigoriev8109: Just comment if no feedback is needed anymore!

**Comment by mkllnk** [comment]
Sounds great. There's a chance that it won't be that easy but I can't tell without working on the issue myself. So try it out and let us know if you hit a road block.

**Comment by mkllnk** [comment]
AngularJS has a concept called *directives* which can apply to certain elements, classes or attribute names. This one applies to the class:

https://github.com/openfoodfoundation/openfoodnetwork/blob/3e3fc4a5a2359f772d18034901154a38dd96a15e/app/assets/javascripts/admin/dropdown/directives/links_dropdown.js.coffee#L1-L5

(Github tip: You can go to a file, mark some lines and then select "copy permalink". Pasting that in a comment means that we got the link to look up the file and Github includes the lines nicely formatted, too.)

I'm not familiar with `angular.bootstrap` either. I could imagine that this code is sometime loaded into an existing page and this initialisation needs to happen but I'm not actually sure it's needed.

**Comment by mgrigoriev8109** [comment]
Apologies for getting started on this and pulling out, but something else has come up in life and I have to step away from this issue. I hope the context I've provided makes it simple for someone else to pick this up and work on it, and will definitely be picking up more OFN issues in the future.

**Comment by muthumcr77** [comment]
Hi there!
I'm new to the OFN. Mind if I take on this issue?

**Comment by drummer83** [comment]
Sure @muthumcr77, this is a great one!

There is very valuable information in the comments above. Make sure to check that out and to include the "restock checkbox" on the modal.

If there are any questions regarding specification, just let us know here! 😉

**Comment by muthumcr77** [comment]
Thanks @drummer83 . Will get started on it.

**Comment by muthumcr77** [comment]
Hey there.
Apologies for getting started on this so late. I've read and understood the progress so far. I've also made myself familiar with Angular directives as mentioned by @mkllnk. Currently, I am working with 

https://github.com/openfoodfoundation/openfoodnetwork/blob/3e3fc4a5a2359f772d18034901154a38dd96a15e/app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb

Let me quickly try a few things and I'll definitely give you a solid update.

**Comment by muthumcr77** [comment]
Hello. 
I understand that cancel_event_link uses a form_id as jquery selector and upon 'onclick' event calls ofnCancelOrderAlert(); to display the required modal here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/3e3fc4a5a2359f772d18034901154a38dd96a15e/app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb

`
ofnCancelOrderAlert = function(callback, i18nKey) {
  if (i18nKey == undefined) {
    i18nKey = "js.admin.orders.cancel_the_order_html";
  }
  $('#custom-confirm .message').html(
    ` ${t(i18nKey)}
      <div class="form">
        <input type="checkbox" name="send_cancellation_email" value="1" id="send_cancellation_email" checked="true" />
        <label for="send_cancellation_email">${t("js.admin.orders.cancel_the_order_send_cancelation_email")}</label><br />
        <input type="checkbox" name="restock_items"  id="restock_items" checked="checked"/>
        <label for="restock_items">${t("js.admin.orders.restock_items")}</label>
      </div>`);
  $('#custom-confirm button.confirm').unbind( "click" ).click(() => {
    $('#custom-confirm').hide();
    callback(true, $('#send_cancellation_email').is(':checked'), $('#restock_items').is(':checked'));
  });
  $('#custom-confirm button.cancel').click(() => {
    $('#custom-confirm').hide();
    callback(false)
  });
  $('#custom-confirm').show();
}
`

I noticed that cancel_order_link(the cancel order button in actions dropdown menu) calls for :fire action with event: cancel, params: :id.
`
def fire
        event = params[:e]
        @order.send_cancellation_email = params[:send_cancellation_email] != "false"
        @order.restock_items = params.fetch(:restock_items, "true") == "true"

        if @order.public_send(event.to_s)
          flash[:success] = Spree.t(:order_updated)
        else
          flash[:error] = Spree.t(:cannot_perform_operation)
        end
      rescue Spree::Core::GatewayError => e
        flash[:error] = e.message.to_s
      ensure
        redirect_back fallback_location: spree.admin_dashboard_path
      end
`
How would you like me to proceed with implementing the modal? 
 - Upon clicking, call ofnCancelOrderAlert modal and redirect to :fire action with the suitable params 
(or) am I going about this the wrong way and would you like me to look elsewhere? 

Kindly assist me with this.

**Comment by mkllnk** [comment]
I think that you are on the right way. I'm not sure what you mean by "redirect" here. You can use the same logic as is used at the moment when cancelling the last order.

**Comment by RachL** [comment]
hello @muthumcr77 I hope this message finds you well. As it's been a while we don't have news here, I'm unassigning you so someone else can pick this up. If you want to come back to it, don't hesitate to comment here :)

**Comment by basilawwad** [comment]
Hi,

I would like to work on this issue, I have done a few tests and it seems that the cancel button is already showing the modal when clicked. The implementation is needed for selecting 'cancel order' from the actions drop-down only unless I am missing another cancel button :)

**Comment by sigmundpetersen** [comment]
Yes, sure @basilawwad ! Thanks a lot 🎉 
Don't hesitate to shout if you have any questions 👍

**Comment by basilawwad** [comment]
Hi,

Since the cancel button already shows the modal when clicked. I thought the best way to do this would be to call the same function ofnCancelOrderAlert when the cancel link is clicked from the dropdown.

https://github.com/openfoodfoundation/openfoodnetwork/blob/9ef07cb110129dd9e5c64696c6eb495bf0bcb6b8/app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb#L230-L251

I can see that some tests are added to check when the last item is deleted I was wondering if I should a spec to see if the modal appears when the Cancel Link is clicked as well?
