### ISSUE TITLE
[Reports] Open PDF in new tab

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9144]
This issue can only be worked on once https://github.com/openfoodfoundation/openfoodnetwork/pull/9032 is merged.

## Description
**- As a:** enterprise & super admin
**- On page:** ALL subpages of `admin/reports`
**- I want to be able to do:** When export in PDF, I want the PDF to open in a new tab instead of the same page I select all my filters. Currently it means the current page is lost.

## Acceptance Criteria & Tests

1. Log in as enterprise user
2. Go to `admin/reports`
3. Check all reports: if you download them as PDF, the PDF should open in a new tab

Repeat as super admin

**Comment by KosyAbone** [comment]
Please i/d love to work on this issue. Thank you

**Comment by RachL** [comment]
hello @KosyAbone and welcom here! You will need to wait until https://github.com/openfoodfoundation/openfoodnetwork/pull/9032 gets merged first, but otherwise yes feel free to work on it. Have you seen our [Welcome New devs board](https://github.com/orgs/openfoodfoundation/projects/2) in the meantime?

**Comment by RachL** [comment]
@KosyAbone FYI this issue is now unblocked if you still fancy working on it :)

**Comment by sigmundpetersen** [comment]
This now has a suggested fix in the connected PR.
@KosyAbone if you want to have a look at other potential issues, please visit the New Devs board as mentioned above. Thanks! 🤗
