### ISSUE TITLE
No bulk delete possible on BOM when orders have multiple items

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#9148]
## Description
It is not possible to select and bulk delete items from orders on the BOM page,  when there are multiple items on the order.  It IS possible to select and bulk delete items IF these are the only/last items in an order.   It IS possible to delete items singularly.

## Actual Behaviour
Should be able to filter, select and bulk delete items.

## Steps to Reproduce

1.create an order with multiple items
2.select multiple items on the BOM page
3.go to actions -  delete.  
4.

## Workaround
Work around is to delete items one by one but for a large hub with 1000 items in their shop and on orders,  this is very time consuming.

## Severity
S2?  

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version: Chrome - latest
* Operating System and version (desktop or mobile): Windows -  desktop

**Comment by filipefurtad0** [comment]
Hey @tschumilas , thanks for opening the issue!

I could not quite reproduce it just yet. For an order with two line items (seen on the left screen) and others with a single line item, I've tried to bulk delete one item from an order which contains two items, and the last item from another order (right screen):

![Peek 2022-05-02 12-43](https://user-images.githubusercontent.com/49817236/166228849-737f4cb6-4d79-457c-8ea0-fa81020f54c0.gif)

Any advice on how to reproduce it?

**Comment by tschumilas** [comment]
just retested:
one 'simple' store (producer sells own)
3 different customers placed orders
BOM -  just filtered by date
I selected products from 2 different customers
go to 'actions' - delete.   Nothing happens.

Will try to make a recording shortly

**Comment by tschumilas** [comment]
![testing bom bulk actions](https://user-images.githubusercontent.com/13171778/167013467-3a71a845-55a5-417f-9bf9-498a3ceddff0.gif)

**Comment by tschumilas** [comment]
OK - so above recording -   first shows I am able to see  the orders in the orders listing.  Then,  I go to BOM and show that I CAN delete an item from an order on BOM.   Then I try to delete 2 items from the same order on BOM using the 'actioins' - 'delete' .  Nothing happens.    I also show the same effect trying to select and delete items from different orders.

Its not shown on this recording -   but  IF an item is the last item on an order -  it WILL delete using the  select - actions - delete process.

**Comment by tschumilas** [comment]
Trying to think about anything else different with this enterprise -  but nothing --   just a producer selling own,  public shop,

**Comment by RachL** [comment]
@tschumilas I think I might have a lead of what happens here : when you do bulk actions on this page, a pop-in opens and ask you for some confirmation. My guess is that you have something on your browser that blocks that pop-in (like an adblocker or something). That would explain why we can't reproduce on our side. Can you try a different browser or maybe in incognito mode?

**Comment by tschumilas** [comment]
Its happened for a couple of users though -  plus for me.  But good thought and yes I'll check in incognito,  and i'll ask the hubs reporting it to do the same.

**Comment by tschumilas** [comment]
2 different users (I'm one of them) have tried this using an incongito window,  and using both chrome and firefox browsers.  
It is not possible to bulk delete items from orders  IF there is more than 1 item in the orders.

Note -  if there is only 1 item in one of the orders,   then the pop up is seen asking about returning to stock and sending a cancellation notice.  This pop up is  prompted when trying to delete the last item on an order. (whether the user is deleting on a single order,  or using bulk delete)

So the problem occurs when using bulk delete (ie across several orders)  and there are multiple items in these orders.  (SO none of the orders will end up being cancelled).   And I think this problem started when we were working on this process for cancelling orders when the last item was removed.

**Comment by RachL** [comment]
@tschumilas thanks for testing Theresa.... then I'm stucked. It works well on my end... I even tested on a combo of order with 5+ items and 1 item only... not sure what can be causing this :thinking:

**Comment by tschumilas** [comment]
I'm going to test more scenerios to day also.  Could it be something else in the supplier or hub settings I wonder.  The thing is -  this used to work fine.....  So its definately something we touched...

**Comment by tschumilas** [comment]
just clarify for me please @RachL - when you just tested this -   when using BOM to remove items from different orders -  and when those orders have more than 1 item in them -   are you seeing the popup?  (because I'm not seeing the popup in any of my testing in this scenerio)  Howver I DO see the popup if I'm removing the last item from one of those orders.

**Comment by tschumilas** [comment]
So just to confirm steps to reproduce this..... (and hopefully someone can)
create an oc with 2 different orders
each of those orders must have at least 2 line items
go to bom
select one line item from each order
go to 'actions'  -  delete
do you see the popup to confirm delete?  

I do not see this popup and i have tried with super admin,  multiple enterprises,  multiple logins.  The inventory settings are all default.  No products are in inventory.

Note that I DO see the popup to confirm deletion if there is only 1 remaining item in at least one of the orders.  This only happens if the number of line items in the orders is greater than 1.

**Comment by tschumilas** [comment]
Others on our support team,  and the hub that reported this,  have re-tested this.   Note that to replicate this bug - there need to be items remaining in the orders selected so that no order is cancelled.    If  - in the process of bulk deleting items -  an order is cancelled (that is,  the last item in an order is selected for deletion, leaving the order empty) -  then the popup confirming deletion AND order cancellation appears.   But,  if you try to delete items from orders,  without cancelling an order (so all orders would have items remaining after the deletion),   then there is no confirmation popup,  and no action occurs.
In the testing above -  @filipefurtad0 and @RachL  -  it looks to us like some of the items you deleted were the only item in an order,  resulting in order cancellation.  And that is why you saw the popup.      There is no popup  if an order is not cancelled in this bulk item deletion process.
So again,  steps to reproduce:
Create 2 orders,  and EACH order has more than 1 item:
Order A -  item 1, item 2
Order B - item 3, item 4
Try to bulk delete item 1 and item 3 -   see no confirmation popup, no error,  and no action
Now try to delete item 1, item, 3 and item 4 (so that would mean cancelling order B)   and see that the popup appears to confirm deletion AND cancellation.

I hope we can confirm and replicate so we can move on this one.  Two large hubs are now asking for this feature to be back.  Today,  for example the problem is:   hub has 80 orders with organic milk.   Supplier is not able to delivery any organic milk.  Hub cannot bulk delete organic milk from all orders,  and has to delete the item individually from each order one at a time.

**Comment by RachL** [comment]
ah thank you @tschumilas :heart: ! I think I've reproduce it as well today, weirdly last week I couldn't...perhaps due to the other bugs we had also on BOM.  @jibees do you have room to take a look? It might have been introduce by the confirmation modal?
