### ISSUE TITLE
Migrate invoice_print_spec.rb into a system spec

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9152]
### What we should change and why (this is tech debt)

We should remove the last standing feature spec, using selenium into a system spec, using cuprite. This is `invoice_print_spec.rb`

### Context

In the context of migrating all feature into system specs.
A previous attempt can be found in #8434.

### Impact and timeline

Being able to reliably test pdfs as system specs or otherwise would improve reliability.

**Comment by sigmundpetersen** [comment]
Can we close this @filipefurtad0 ?

**Comment by filipefurtad0** [comment]
Thank you @sigmundpetersen I lost track of this issue - let's close :ok_hand: 

Adding this for future notice: This was addressed by converting it explicitly into a rack test, for ref. see: #9576/#9577
