### ISSUE TITLE
[Split checkout] Taxes are not re-calculated if customer changes state

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9153]
## Description

Tested using staging UK with CA data: the legacy checkout updates tax calculation on shipping method, but not split checkout.

## Expected Behavior
Taxes are re-calcultated if a customer change their address

## Actual Behaviour
Taxes are no re-calcultated, customer checksout with the wrong tax.

## Steps to Reproduce

1. Go to https://staging.openfoodnetwork.org.uk/red-berries-hub/shop#/shop
2. Checkout the red berries with Nunavut state for customer + shipping method with tax
3. See the amount
4. Checkout again, but this time select Ontario as a state for the shopper. Same shipping method

## Animated Gif/Screenshot

Legacy checkout:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/dc088aee-ef82-4b10-8b02-7dfa60ea2255)

Split checkout:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/f1990c67-ac3a-482b-a3b7-22c6f76ae481)

## Workaround

None. Currently if customers change their state, they won't be paying the correct tax (or even no tax at all)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v.4.2.8
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Both

## Possible Fix

Recalculate taxes when reaching the summary page? If not possible we need at least to keep the current behavior: the correct amount is charged and shown on order confirmation

**Comment by filipefurtad0** [comment]
I _think_ I've seen taxes correctly charged on split-checkout before... (I can't find a pic demonstrating this). 

As discussed today on delivery train, we might be looking at a regression introduced by https://github.com/openfoodfoundation/openfoodnetwork/pull/8822

**Comment by filipefurtad0** [comment]
I think split-checkout is not calculating taxes, regardless of customers changing state. The orders below, from legacy checkout (left); from split checkout (right):

![Peek 2022-05-05 15-55](https://user-images.githubusercontent.com/49817236/167190539-5fa39894-9afc-4bae-acb2-a05c48410ed0.gif)

Only after clicking update and recalculate fees in the BO the orders match.

**Comment by jibees** [comment]
I'll deep dive into this one 🤿. Not sure I'll succeed, but let's have a try ;)

**Comment by mkllnk** [comment]
Just with a very quick look at these line:
https://github.com/openfoodfoundation/openfoodnetwork/blob/44965ff2352e04a824e6036ada383b1fb2decbc8/app/controllers/split_checkout_controller.rb#L79-L81

It looks like the updater is setting the new values but in my 30 second read I didn't see them saved. Do we need to call `save`?
