### ISSUE TITLE
Delete customers

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#916]
This is a follow-up of #850. We can't delete customers that ordered something already. In order to change this, we could do this:
- Remove attribute customer_id from order model.
- Create association from order to customer by a method like this:

``` ruby
def customer
  if @user
    @user.customer_of(@enterprise)
  else
    Customer.find_by_enterprise_and_email(@enterprise, @email)
  end
end
```

@oeoeaio Do you think that is a good first step and we can solve the user assignment after that?

**Comment by oeoeaio** [comment]
Hm, my preference would be to just solve everything all at once. What do you think the benefit of doing it in stages is?

**Comment by mkllnk** [comment]
Sometimes things explode. It is easier to solve one problem at a time. Keeps the system stable. And if I don't get the second bit done, the first one is already an improvement. I wouldn't do it if there would be a lot of extra work. But it looks to me, that I would just add four lines that get removed later.

```diff
def customer
-  if @user
    @user.customer_of(@enterprise)
-  else
-    Customer.find_by_enterprise_and_email(@enterprise, @email)
-  end
end
```

I can still put it in one pull request. I split it up into two issues, because there are two functional things to solve: delete customers and associate customers with new users. And there was already the issue about validating user emails instead of enterprise emails. That is separate as well.

**Comment by myriamboure** [comment]
Captured in the icebox on deletion, will be rechecked when we decide to focus on it.
https://community.openfoodnetwork.org/t/users-and-admins-can-delete-accounts-entreprises-customers-order-cycles-groups/1149
#gitcull2018
