### ISSUE TITLE
Metabase has not synched since 26 April 2022

### ISSUE THREAD

**Issue by RonellaG** [openfoodfoundation/openfoodnetwork#9161]
## Description
The Australian team use Metabase to provide customer support.

## Expected Behavior
We should be able to see up-to-date data so that we can investigate customer enquiries

## Actual Behaviour
Metabase has not synched since 26 April 2022

## Steps to Reproduce
<img width="1216" alt="Screen Shot 2022-05-09 at 4 23 17 pm" src="https://user-images.githubusercontent.com/68315791/167352722-10ee6497-3213-43d6-960d-8aa97f84248a.png">

## Severity
S2

## Your Environment
Browser name and version: Chrome Version 100.0.4896.127 (Official Build) (x86_64)
Operating System and version (desktop or mobile): MacBook Pro MAC OS Catalina Version 10.15.17

**Comment by mkllnk** [comment]
Documenting actions so far:

Giving @jibees access after his PR got merged:
```
ansible-playbook playbooks/provision.yml -t ssh_keys
```

I had to fix a conditional first and committed that to master.

Setup my local inventory:
```
ansible-playbook playbooks/fetch_inventory.yml
```

Looking at the playbooks, reset_stream sounds useful. Let's see what it does:
```
ansible-playbook playbooks/reset_stream.yml -e "ofn_client=au-prod"
...
TASK [libre_ops.open_jdk : install openjdk] ***********************************************************************************************************************************************************************
fatal: [openfoodnetwork.org.au]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: "}

PLAY RECAP ********************************************************************************************************************************************************************************************************
data.openfoodnetwork.org.uk : ok=13   changed=7    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
openfoodnetwork.org.au     : ok=7    changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

:disappointed: 

I did notice that the `confluent-control-center` process is pretty busy. I'm wondering if that's normal or because something is hanging there. Let's try to restart it manually:

```
systemctl restart confluent-control-center.service
```

Initially busy but now less so. Maybe that fixed something.

**Comment by mkllnk** [comment]
I've done a direct connection setup for Australia and we'll see how well that works before I do that for other countries, too.

**Comment by mkllnk** [comment]
I provisioned all managed instances and changed the database connections on the existing databases in Metabase. If another instance wants Metabase, we can simply add the account details now. Passwords are in ofn-secrets.
