### ISSUE TITLE
Let users generate their API key

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9166]
## What is the problem we are solving 

Only admin users can generate and see API keys at the moment. So if anyone wants to use the API they need to ask an instance manager for an API key first. This is additional work. Plenty of community contributors are also asking regularly how they get an API key and we need to let them know.

## Success factors = expected outcome 

1. In Admin/Users (a super admin screen only) we need a 'View API checkbox'. This box will enable and disable the 'Developer Settings' tab in /Account
![image](https://user-images.githubusercontent.com/8669848/172190265-3df1cc46-1bb2-49bd-b964-503981619250.png)

2. In /Account there is a new tab next to Account Settings called Developer Settings that will display the API key and allow a user to regenerate their API key.
![Screenshot from 2022-06-06 16-17-14](https://user-images.githubusercontent.com/8669848/172190754-de93e5db-6e78-41d5-b6a2-330c2cc61092.png)

## Acceptance Criteria

1. The new functionality described above
2. If a super admin unclicks the 'View API Checkbox' the user is no longer able to see the developer screen in /Account
3. If a super admin unclicks the 'View API Checkbox' the user's API key doesn't change.
4. If a super admin click regenerate key then the API key does change.
5. Text fields are translatable

**Comment by mgrigoriev8109** [comment]
Could I work on this issue?

**Comment by drummer83** [comment]
Sure! 😊
I have assigned it to you!

**Comment by lin-d-hop** [comment]
@mgrigoriev8109 The spec here is not very clear. Do you understand what Maikel means by 'users account page'?

**Comment by RachL** [comment]
I would like to add that for now, in FR, we are not ready to support users doing so. So it would be really nice if instance managers can choose in their configuration panel whether or not users are able to do this?

**Comment by mgrigoriev8109** [comment]
Thank you @lin-d-hop , I would appreciate the help greatly!

My assumptions:
    - Application programming interface keys, or API keys, are used to authenticate either a user or an app. Currently there is a button in the Admin Interface while editing a User which allows the Admin to generate a key for the user, clear the key, and regenerate the key. The specific path for this button is `http://localhost:3000/admin/users/user_id/edit` You can see these these buttons below:

    -The implementation goal for this issue is to create similar functionality, but for the User themselves on the User profile’s account page. The path for this implementation will be `http://localhost:3000/account#api_key` , and the page on which this implementation will go can be seen below:

Proposed Implementation:
- I organised this section into how I would create tests, the model, the view, the controller, and the routes.

- Tests:
- Since I saw that features should be test-driven, I would start by creating a test which I would aim to take from failing to passing in the course of implementation. I saw that there’s currently no model tests, but there are controller tests for the Admin’s version of this feature over in `spec/controllers/spree/admin/users_controller_spec.rb`. I would start by creating two similar tests over in `spec/controllers/spree/users_controller_spec.rb`, which would look something like:
```ruby
describe "api_keys" do
    routes { Openfoodnetwork::Application.routes }
    let!(:user) { create(:user) }

    it "allows user to update an API key" do
        expect(user).to receive(:generate_spree_api_key!).and_return(true)
        spree_put :generate_api_key, id: user.id
        expect(response).to redirect_to(spree.account_path(test_user))
    end
    it "allows user to clear an API key" do
        expect(user).to receive(:clear_spree_api_key!).and_return(true)
        spree_put :clear_api_key, id: user.id
        expect(response).to redirect_to(spree.account_path(test_user))
    end
end
```

- Model:
    - I shouldn’t need to add anything to the current User model, as the following two model methods are available to all users: 
```ruby
def generate_spree_api_key!
    self.spree_api_key = SecureRandom.hex(24)
    save!
end

def clear_spree_api_key!
    self.spree_api_key = nil
    save!
end```


- View
    - So since I’d love some feedback on this, but since I’m creating it in the User account page, my thinking was that I would create another tab - so the way you see Orders, Transactions, and Settings in the above picture, there would be a fourth identical tab which says API Key. I’d do this by taking the following code located in `app/views/spree/users/show.html.haml` 
```ruby
.darkswarm
    .row.pad-top
        .small-12.columns.pad-top
            %h2
            = accurate_title
            %span.account-summary{"data-hook" => "account_summary"}
            = @user.email
            = render 'orders'
            = render 'cards'
            = render 'transactions'
            = render 'settings'
        .row.tabset-ctrl#account-tabs{ style: 'margin-bottom: 100px', navigate: 'true', selected: 'orders', prefix: 'account' }
        .small.12.medium-3.columns.tab{ name: "orders" }
            %a=t('.tabs.orders')
            - if Spree::Config.stripe_connect_enabled && Stripe.publishable_key
        .small.12.medium-3.columns.tab{ name: "cards" }
            %a=t('.tabs.cards')
        .small.12.medium-3.columns.tab{ name: "transactions" }
            %a=t('.tabs.transactions')
        .small.12.medium-3.columns.tab{ name: "settings" }
            %a=t('.tabs.settings')
        .small-12.columns.tab-view
            = render partial: "shared/footer"
```

and adding a fifth render of `= render 'api_keys'`, along with the following right after the transaction and settings tabs, on line 33 of that file:
```ruby
    .small.12.medium-3.columns.tab{ name: "api_key" }
    %a=t('.tabs.api_key')
```

- Then, I would create the api_key partial by creating `app/views/spree/users/_api_key.html.haml`, which would borrow heavily from `app/views/spree/admin/users/_api_fields.html.haml`and look like:
```ruby
%script{ type: "text/ng-template", id: "account/orders.html" }
    %fieldset.omega.six.columns
        %h3= t('.api_key')

        if @user.spree_api_key.present?
            .field
                = label_tag t('spree.api.key')
                = ":"
                = @user.spree_api_key
            .filter-actions.actions
                = form_tag spree.clear_api_key_user_path(@user), method: :put do
                = button t('spree.api.clear_key'), 'icon-trash'
                = form_tag spree.generate_api_key_user_path(@user), method: :put do
                = button t('spree.api.regenerate_key'), 'icon-refresh'

        else
            .no-objects-found= t('spree.api.no_key')
            .filter-actions.actions
                = form_tag spree.generate_api_key_user_path(@user), method: :put do
                = button t('spree.api.generate_key'), :class => 'button primary’
```

- I haven’t looked at the styles yet, but my goal in design would be to have the color scheme similar to the current Account Settings form. As seen below, I was considering making the words API Access to be plain and black, and the buttons to be orange with white font. :
- picture



- Controller
    - Going off of the two methods located in `app/controllers/spree/admin/users_controller.rb`, My plan was to navigate to `app/controllers/spree/users_controller.rb` and create something similar, along the lines of:
```ruby
def generate_api_key
    if @user.generate_spree_api_key!
    flash[:success] = t('spree.api.key_generated')
    end

    redirect_to spree.account_path(@user)
end

def clear_api_key
    if @user.clear_spree_api_key!
    flash[:success] = t('spree.api.key_cleared')
    end

    redirect_to spree.account_path(@user)
end
```

- Routes:
    - Not too sure about this one - to be honest I’ve never interacted with routes as complex or large in scope as this project. I was going to try take the same routes the admin currently uses, and add them onto the tail end of the  `devise_scope :spree_user` routes within `config/routes/spree.rb` , which would end up looking something like:
```ruby
devise_scope :spree_user do
    post '/login' => 'user_sessions#create', :as => :create_new_session
    get '/logout' => 'user_sessions#destroy', :as => :logout
    get '/password/recover' => 'user_passwords#new', :as => :recover_password
    post '/password/recover' => 'user_passwords#create', :as => :reset_password
    get '/password/change' => 'user_passwords#edit', :as => :edit_password
    put '/password/change' => 'user_passwords#update', :as => :update_password
    put :generate_api_key
    put :clear_api_key
end
```

Phew, that was a lot. Sorry for dumping so much on here - but I figured the more thorough I was the better. Apologies if there are lots of mistakes - this is all off the top of my head, and I haven't actually put any of it into code, or commited/tested/debugged any of this yet. I just wanted to get my main ideas down to see if I was on the right direction. 

As for what @RachL mentioned, I'd love to include that in the feature - though I haven't begun to do much thinking as to how it would be implemented yet. Am I correct in the assumption that Instance Managers are Enterprise Owner users?

**Comment by mkllnk** [comment]
This is amazing and enables me to give you early feedback. You are totally on the right track with testing and where to put the code. One change I would like to suggest though is to create a new ApiKeysController with `resource :api_key` routes for only create and destroy. The reason being that our controllers are often growing bigger than is easy to read and that it plays nicely with Rails conventions. It will also be easier to extend if we support multiple keys one day.

**Comment by mkllnk** [comment]
Oh, and use a feature toggle with Flipper so that instances can decide to enable it or not.

**Comment by RachL** [comment]
@lin-d-hop @mkllnk are we sure we want to put this in the account settings section? That means than any shopper would be able to see this. It does extend the scope, but I would prefer that we put this under a new tab in enterprise settings. It does not make sense for me to show this to non-admin users.

**Comment by mkllnk** [comment]
Good point but it's not associated to an enterprise either. Should there be something at the bottom of the dashboard or another menu item?

**Comment by RachL** [comment]
The ideal would be a profile / preferences page on admin side, but maybe too much work.  Currently there is an "account" entry that leads to the user account on the shopfront side. What about creating a new page under that link? 

Otherwise: can we show the generate API in the suer account _only_ if the user has admin access?

**Comment by mkllnk** [comment]
Oh yes, there's a lot to think about. But can we find a first step for a good-first-issue to solve here and now?

I could imagine to create this new developer tab in the account section and show it only if an API key is already present. This means an instance manager granted access. It can also be removed and then the user can't use the API any more. We could also always show that tab in development environment to ease entry for newcomers. And it would be good to have some documentation about this so that people know to ask for an API key.

**Comment by lin-d-hop** [comment]
API Keys seem to have been automatically created for many users. You don't have to click Generate Key.

I think we need a super admin toggle as part of the minimum viable, personally.

**Comment by lin-d-hop** [comment]
@mgrigoriev8109 I know you're working on other things now, but if you are still interested in this one I've updated the spec in the main issue description :)

**Comment by Philwi** [comment]
Hey, I would like to tackle this one. Could you assign me, please? :)

**Comment by drummer83** [comment]
Sure, @Philwi! I have assigned it to you.
Make sure you read the comments above and check out the preparations mgrigoriev8109 has already provided.

Looking forward to your contribution and don't hesitate to ask here or in our Slack in case you get stuck! 😊
