### ISSUE TITLE
[API] Customer endpoint improvements

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9167]
## What is the problem we are solving 

After publishing the customer endpoint behind a feature toggle we got some suggestions for improvements. I selected a few which would be good to do now before publishing the endpoint as stable.

## Success factors = expected outcome 

Region and country codes are useful IDs to compare across databases:

- Replace `region` string with an object: `region: { code: "VIC", name: "Victoria" }`
- Replace `country` with an object: `country: { code: "AU", name: "Australia" }`

Please note:

- The country code should be the two-letter version.
- The update action should also be changed to this new format. We best rely on the code to find the record but we can search for the name as well if the code is not present.

**Comment by lin-d-hop** [comment]
Please track your hours on this in clockify under the Customer Endpoint funded feature.
Thanks!
