### ISSUE TITLE
[Split Checkout] Should a shipment be created on the `/summary` step?

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9168]
## Description

This issue is meant as a placeholder to double-check if the current behavior is correct. So not bug per se, rather a code/feature logic/design question:

Do we need to create shipments on the /summary step?

On legacy checkout: a shipment is created once the used clicks "Place order now".
On Split Checkout: a shipment is created once the user visits the `/summary` step, and before clicking "Complete order".

Why is this important?

If a shipment is created on `/summary` but the user goes back to `/details` shipping info may be changed. This means that the `shipment` entity needs to be updated or destroyed accordingly. This can influence the calculation of taxes, for example.

I've found no controller specs documenting this behavior.

## Actual Behaviour

On legacy checkout: a shipment is created once the used clicks "Place order now".
On Split Checkout: a shipment is created once the user visits the `/summary` step, and before clicking "Complete order".

## Steps to Reproduce

On legacy checkout:
1. Visit the /checkout page
2. Check the DB looking for shipments associated with that order -> see there is **none**.

On split-checkout:
1. Visit the `/payment` page
2. Check the DB looking for shipments associated with that order -> see there is **none**.
3. Proceed to `/summary`
4. Check the DB looking for shipments associated with that order -> see there is **one**.

## Animated Gif/Screenshot

Legacy Checkout (using the order id for that cart order):
![image](https://user-images.githubusercontent.com/49817236/167611516-17c6e1e5-5d2e-4bb6-b62e-d350bcd8f897.png)

Split-Checkout (using the order id for that cart order):
![image](https://user-images.githubusercontent.com/49817236/167611611-7eba1b70-374c-4ebc-b15a-96e7f746dd2a.png)

## Related

Clicking the empty cart destroys shipments associated with the order. If the shipment is missing the `/summary` page will not render, see #9131.

**Comment by RachL** [comment]
@filipefurtad0 now that recalculation of taxes are fixed. Do we still need this issue?

**Comment by filipefurtad0** [comment]
Hey @RachL, 
We don't need it. The issue was rather here to spring discussion on why the split checkout was designed to create a shipment object in the DB before the order is completed. But it's not really a bug so we can close it.
