### ISSUE TITLE
Associate new users with their previous orders

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#917]
This is a follow-up of #850 and #916.

If a user orders as a guest and decides later to sign up, the user cannot see their old guest orders. Additionally, there are two customer records with the same enterprise and email address. One is associated to the guest orders and the other one to the user.

In order to solve this, we need to validate email addresses during signup, #833.
And it would be good to create guest user records that don't allow to login, but they are the reference to associate orders and customers.

@oeoeaio Does this sound right?

**Comment by RachL** [comment]
It was agreed here: https://github.com/openfoodfoundation/openfoodnetwork/issues/1592#issuecomment-392276084 that this was not the way to go. So I'm closing this.
