### ISSUE TITLE
[Split checkout] Rename "delivery address" in "shipping info"

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9172]
## Description
**- As a:** shopper
**- On page:** `/checkout/details`
**- I want to be able to do:** see the text "Shipping info" (same as legacy checkout) rather than "delivery address"

Context : it has been reported by several users. They get confused by the term "address". We can fix it in translation, but it's good  to give the right incentive to translators.

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/43a66756-7995-451b-9b43-95b81678330a)

## Acceptance Criteria & Tests

1. Checkout on a shop
2. See "Shipping info" instead of "delivery address"

**Comment by jibees** [comment]
Since the i18n key has already been translated for almost all languages, should I re-create another key, or simply changing the original key is enough?

**Comment by RachL** [comment]
@jibees can we re-use the i18n key from legacy checkout?
