### ISSUE TITLE
As an admin, I can add a note on an order

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9178]
## Description

**- As a:** enterprise user
**- On page:** `/admin/orders/RXXXX/edit`
**- I want to be able to do:** Add a note on an order. Be able to edit it and delete it as well.

The idea is to keep the same UX we have for tracking number and put it below:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/25e8db73-d7e0-4881-8905-93af93b96e23)

By default, the placeholder should indicate "No note added yet".

## Acceptance Criteria & Tests

1.  Log in as enterprise
2.  Go to an edit order's page
3.  Try to add a note : check the display works
4. Check editing works
5. Check deleting works

Check the behavior on different states: completed, cancelled, resumed...

Repeat tests with super admin.

**Comment by RachL** [comment]
@jibees do you think we need to limit the number of characters?

**Comment by jibees** [comment]
For sure, it should be limited. 
Don't know how many...

**Comment by jibees** [comment]
Quick question: should the input be a text input or a textarea? Ie. should the note contains more than 1 line?

**Comment by RachL** [comment]
@jibees let's start with a text input, but it'd be nice if we could show the user when they are reaching the max. number of characters allowed, so they can fix before saving?

**Comment by jibees** [comment]
yes, It'd be nice, I agree !

What about 280 car max?

**Comment by RachL** [comment]
let's go :+1:
