### ISSUE TITLE
Show notes written by admins on invoices

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9179]
## Description
**- As a:** enterprise user
**- On page:** On an invoice (PDF)
**- I want to be able to do:** See the note that I have added thanks to 
https://github.com/openfoodfoundation/openfoodnetwork/issues/9178

The note should appear at the end of the rest of the invoice content, with the same UX than the payment description for example : 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/e830f548-2c92-4abc-898f-162631c0c3b2)

Title + note below. The Title should be "Additional information".

## Acceptance Criteria & Tests

1. Log in as an enterprise user
2.  Add a note on an order
3.  Check it appears when you generate the invoice
4. Delete the note + check orders without notes : notion should appear on invoices

Repeat with super admin

:warning: be sure to apply it on BOTH invoices template.

**Comment by apricot12** [comment]
@RachL Is there any kind of design cues available about how you'd want this to look like? 

Should it be at the way bottom in bold text, should it be centered, etc..?

**Comment by lin-d-hop** [comment]
The design cue is in the issue:
![Screenshot from 2022-08-10 16-55-18](https://user-images.githubusercontent.com/8669848/183955380-5424fa0c-7ea2-460c-be40-06baf8d72ba1.png)

**Comment by apricot12** [comment]
![image](https://user-images.githubusercontent.com/65319144/183959073-c5f66d4e-7494-453e-91aa-325ac97a5d8c.png)
So this is exactly what we want, yes? I think it's done.

**Comment by RachL** [comment]
Perfect :+1: Welcome back @apricot12 :tada: !!!

This one will make @tschumilas very happy :)
