### ISSUE TITLE
[Reports] Ability for the admin to save their rendering options per reports

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9189]
## Description
**- As a:** enterprise user or super admin
**- On page:** each sub pages of `admin/reports`
**- I want to be able to do:** Be able to save the last 'rendering options' I have used

Rendering Options include:
- Report Type
- Display (Header/Summary rows)
- Columns to Show (see [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9191))
- Report Generation type

The same rendering options exist on each report, however some of the options available change on a report by report basis.

## Acceptance Criteria

- When I set the rendering options on a report, my last used rendering options are saved next time I visit this report.
- For each report, each of the rendering options is saved such that when I click away from the report, or log out and log back in, the rendering options I used last time are shown.
- If I set rendering options on one report, and set rendering options on a second report, then both are saved independently from each other.
- Rendering options are saved per user (ie not per enterprise)
- Functionality works on all reports, including super admin reports
- Settings are saved on click. There is no save button. Saving is automatic.
- Functionality is covered by automated tests (see comments, it was agreed that testing each rendering option rather than each report is acceptable)

## Testing notes

1. Log in as enterprise user
2.  Go to `admin/reports`
3. Select a report and add rendering options
4.Press 'go' to launch the display of the report
5. Go to another page and come back : see the rendering you have selected are still in place.
6. Saving does not work if you did not press 'Go' on the report.

**Comment by RachL** [comment]
@jibees one more question came up when I was writing the acceptance criteria : there are some rendering options which are similar across reports like "summary row". When I save "summary row" for one report does it save it on ALL reports? For now, I think from the product side we would prefer to have it _per_ reports.

**Comment by jibees** [comment]
I'd say _per report_ too...

**Comment by abdellani** [comment]
Hi

As the rendering options will persist after the logout, I was thinking about adding a new model to store the rendering options.
What do you think?
```ruby
ReportRenderingOptions
  report_type: string
  report_subtype: string
  user: reference
  options: text #serialized hash
```

**Comment by jibees** [comment]
Yes, I think this should do the job. We want a tuple with `Report-Subreport`/`User`/`Rendering options`. I think it's good then.

**Comment by abdellani** [comment]
I noticed that when I access the report page for the first time after clicking a link from the reports list, the backend generates the report even if nothing is rendered. This will run unnecessary queries to the database, no?

This is question is maybe not related directly to the feature we want to develop here.

**Comment by jibees** [comment]
> the backend generates the report even if nothing is rendered. This will run unnecessary queries to the database, no?

Yes, for sure. This is something we need to facing on. But not related to this issue here. 
If you have any solution, ... feel free to open a new pull request!

**Comment by dacook** [comment]
> I noticed that when I access the report page for the first time after clicking a link from the reports list, the backend generates the report even if nothing is rendered.

Hi @abdellani, just wondering if you confirmed this bug or not? If so, could you please raise it?

**Comment by abdellani** [comment]
Hi @dacook 

The data fetched from the database is not used. I wouldn't consider it as a problem if the queries don't impact the production server performance.

**Comment by dacook** [comment]
From what I can see, the report class is automatically instantiated, but it's not immediately clear to me how it works.
It sounds like you're saying it runs the report (query the database) based on the default form parameters. That doesn't sound good, but if it's not a problem, then I won't look into it further :)

**Comment by abdellani** [comment]
@dacook 
> it runs the report (query the database) based on the default form parameters.

Yes, you're right. 

>That doesn't sound good, but if it's not a problem, then I won't look into it further

I can't say if it's a problem or not.

**Comment by RachL** [comment]
>  That doesn't sound good, but if it's not a problem, then I won't look into it further

It's a problem but it's out of the scope of this PR. If it improves performance we can take a look into it in the next performance issues.
