### ISSUE TITLE
Displaying product properties

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#919]
Stroudco added the "certified organic" property to Ruskin Mill marmalade and although we can now filter by "certified organic" and get the right result, the product itself isn't marked as organic, which we understand should be via a label inside the pop-up window.

Also a couple of other points about properties:
1) is it possible to remove the "minimum order" property as I understand this doesnt work yet?
2) please can we add another property called "certified biodynamic"
3) please can we add another property called "produced within 15 miles of Stroud".  I guess this property would need to be editable by the administrator so they can change the location?

Thanks

**Comment by lin-d-hop** [comment]
New properties can be created in super-admin under Products -> Properties.

Properties are global variables per instance so "produced within 15 miles of Stroud" doesn't make much sense but "produced within 15 miles" might...?

**Comment by NickWeir63** [comment]
Great - I will create those and delete "minimum order"
thanks
Nick
