### ISSUE TITLE
Problem in customer communiation process with shipping emails

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#922]
Connected to the issue #906 

When clicking on "ship" on the order listing page,
![shipment](https://cloud.githubusercontent.com/assets/8135376/14763604/ae9f9c3e-099a-11e6-94eb-dc3da7d681c3.png)

there is an automatic email sent to the customer.
![mail](https://cloud.githubusercontent.com/assets/8135376/14763610/d1fe149e-099a-11e6-86fb-a0439e7c7390.png)

1- First, the email is not translated (and even in English it's a the "thank you for your business" sounds a bit strange to me ;-))
2- But the most important is: when someone come and pick up the products, and the hub manager click on "ship" to tell that the product has been shipped (or in that case, taken), it's a bit stranger for the customer to receive a message via email saying that his order has been shipped (he knows, he was there to take it ;-)) Is it possible to choose when you clic on "ship" if you want to send a notification email or not?

**Comment by blancnic** [comment]
I propose to deactivate the notification email or maybe check to test the shipping mode.

**Comment by myriamboure** [comment]
I don't understand @blancnic ... desactivate the notification is not a solution as some hubs need their customer to know that the order has been shipped (for home delivery shipping methods). What do you mean by "check to test the shipping mode?" My solution would be to have a pop-up when you click on "ship" and in the pop up, one question: "do you want to sent a notification message to the buyer?" two buttons "send" and "don't send"...

**Comment by lin-d-hop** [comment]
This needs more spec to be useful. It is not going to be actioned from this issue. #gitcull
