### ISSUE TITLE
Cannot search using OpenStreetMap

### ISSUE THREAD

**Issue by diegoamc** [openfoodfoundation/openfoodnetwork#9225]
## Description

When in the map page with open street map configured, I cannot type anything on the search input.

## Expected Behavior

When using open street map, I would like to search locations successfully

## Actual Behaviour

I cannot type any value on the search input of the map when using open street map

## Steps to Reproduce

1. Configure the system to use open street map by going to the admin panel -> configurations -> content
2. Access the map page
3. Try to type something

## Animated Gif/Screenshot

I don't actually think this will be useful because nothing happens neither in the screen nor in the console

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: master branch
* Browser name and version: Firefox 100.0.2 and Chromium 101.0.4951.64
* Operating System and version (desktop or mobile): Ubuntu 21.10

**Comment by RachL** [comment]
Hello @diegoamc ! Yes open street map work is not finished yet! Most of the work to be done is capture over here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5542

We have no one working on this for now, so if you are interested drop us a line! I'm closing here to avoid duplicate.
