### ISSUE TITLE
Can't delete enterprise relationship

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#923]
When I click delete and then confirm 'yes I am sure' nothing happens 
However if I log in as superadmin the delete is successful
![screenshot 2016-04-25 13 17 16](https://cloud.githubusercontent.com/assets/10517702/14783872/72ef3d60-0aea-11e6-8789-991565d3ac29.png)

**Comment by OliverUK** [comment]
I can delete relationships that I created but I can't delete those that must have been created when Stroudco data was imported from the current system.

**Comment by NickWeir63** [comment]
OK I will delete all the old redundant ones in superadmin.
this glitch must be something to do with how the data was imported so i will close this issue
