### ISSUE TITLE
Ugly line break around shipping category radio buttons (delivery/pick up)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9231]
## Description

Even though there should be enough room in the row, the text 'delivery' is not displayed next to the radio button but below.

## Expected Behavior

Text should be nicely placed next to the radio button.

## Actual Behaviour

Text is shown below the radio button.

## Steps to Reproduce

1. Visit page /admin/shipping_methods/new or 
/admin/shipping_methods/[number]/edit

## Animated Gif/Screenshot

![grafik](https://user-images.githubusercontent.com/1790176/170689913-915dc8b8-f373-48f5-9df8-8291820b21d3.png)

## Workaround

No workaround.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.1.33
* Browser name and version: Firefox 100
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by saunmanoj888** [comment]
hii @drummer83 
Can I pick this issue?

**Comment by drummer83** [comment]
Sure, please go ahead, @saunmanoj888! 😊
