### ISSUE TITLE
Grumpy cat when deleting enterprise

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#924]
Earthshare sent me this email:
**Also, you can delete the shop Suzanne2 , that was a test shop we created to see if we could get the emails to work. **
I went in as superadmin and checked that it was his enterprise but got this message when I tried to delete it so I just changed the owner, manager and notification emails to get them off his account
![screenshot 2016-04-25 17 14 56](https://cloud.githubusercontent.com/assets/10517702/14790752/9a6f7434-0b0a-11e6-97d4-da169a00d715.png)

**Comment by lin-d-hop** [comment]
Currently we can't delete enterprises with relationships. Try removing the products and enterprise relationships associated with that enterprise and then see if super admin delete works.

**Comment by NickWeir63** [comment]
Thanks Lynne
