### ISSUE TITLE
Json dependency of aws sdk gem is too old

### ISSUE THREAD

**Issue by diegoamc** [openfoodfoundation/openfoodnetwork#9256]
## Description

`aws-sdk` is on version 1.67.0 on OFN. It requires `json ~> 1.4`. In the Gemfile OFN has `json` listed. When installing the project from scratch and following the getting started document, the OFN local instance ends up with json `2.6.1`.

When we run `bundle install`, it logs this message:

```bash
Your lockfile doesn't include a valid resolution.
You can fix this by regenerating your lockfile or trying to manually editing the bad locked gems to a version that satisfies all dependencies.
The unmet dependencies are:
* json (~> 1.4), depended upon aws-sdk-v1-1.67.0, unsatisfied by json-2.6.1
```

So, whenever we run `bundle install` (when trying to install a new gem, for example), we have the error:

```bash
Bundler could not find compatible versions for gem "json":
  In snapshot (Gemfile.lock):
    json (= 2.6.1)

  In Gemfile:
    json

    aws-sdk (= 1.67.0) was resolved to 1.67.0, which depends on
      aws-sdk-v1 (= 1.67.0) was resolved to 1.67.0, which depends on
        json (~> 1.4)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
``` 

## Expected Behavior

I would like to install new gems in the project

## Actual Behaviour

I cannot install any new gem

## Steps to Reproduce

1. Add a new gem in the Gemfile, say `phonelib` (in the context of #9249, for example )
2. Run `bundle install`

## Animated Gif/Screenshot

![Screenshot from 2022-06-02 11-53-35](https://user-images.githubusercontent.com/1068750/171657972-3cf88893-51f5-4729-bcc9-2e0132724f0d.png)

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: master branch
* Browser name and version: -
* Operating System and version (desktop or mobile): Ubuntu 21.10

## Possible Fix

Update `aws-sdk` gem.

**Comment by sigmundpetersen** [comment]
Hey @diegoamc yes we are aware of this issue.
First thing needed is to switch from Paperclip to Active Storage, this has just been done through this isse https://github.com/openfoodfoundation/openfoodnetwork/issues/6347

I'm not 100% of the exact next steps after that, but this unblocks path forward at least.
