### ISSUE TITLE
Summary row (total line) in reports has a different date format

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9257]
## Description

When activating the summary row in reports, the date of this row doesn't have seconds.

Example : 

- line item date is 2022-05-30 17:55:50
- summary row date is : 2022-05-30 17:55

This block user from sorting the spreadsheet they download by date.

## Expected Behavior

Summary row has the same date format than the line item

## Steps to Reproduce

1. Go to admin/reports : especially order total by customers but I need to check all reports with date column
2. Download with summary row in spreadsheet
3. Sort by date
4. :boom:

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/46ca6639-7a15-4f71-900b-238de306bb5b)

## Workaround

I have manually re-ordered the spreadsheet to get the hub ready for packing. It tool me an 1h and I can do mistake. I can do it once or twice but would hope this is an easy fix?

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.1.33
* Browser name and version: All
* Operating System and version (desktop or mobile): Both

**Comment by RachL** [comment]
Full context : this is breaking my Excel script that is looking for total lines and assign a number to a customer (according to several rules like type of shipping method and order date, [example here](https://community.openfoodnetwork.org/t/hub-can-easily-generate-accurate-packing-slips/1392/51?u=rachel)).

I didn't see it earlier because I wrote this script 2 years ago now and forgot to add in the process "sort the spreadsheet by date because you didn't find how to sort within the script".

![ ](https://media.giphy.com/media/jUwpNzg9IcyrK/giphy.gif)

**Comment by jibees** [comment]
Reading the code, if i'm not mistaken, seems that for:
 - _Sales Tax_, _Tax Types_ report
 - all _Users and enterprises_ reports
the date aren't formatted with seconds. 

But it's not in summary row, it's for classic rows.
