### ISSUE TITLE
Some report sub-types not listed in reports description

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9261]
## Description

Most of the reports have different types, e.g. for Payment Reports there are types 'Payment by Types', 'Payment Totals' and 'Itemised Payment Totals'. For most reports these types are listed in the 'description' column of the reports main page, e.g. 'Tax Types' and 'Tax Rates' for Sales Tax reports.
For some reports the available types are not listed in the description:
- Bulk Co-Op
  - Bulk Co-op Supplier Report
  - Bulk Co-op Allocation
  - Bulk Co-op Packing Sheets
  - Bulk Co-op Customer Payments
- Payment Reports
  - Payments By Type
  - Itemised Payment Totals
  - Payment Totals
- Xero Invoices
  - Summary
  - Detailed

## Expected Behavior

For consistency reasons all sub-types of reports should be displayed on the reports main page in column 'description'.

## Actual Behaviour

For Bulk Co-Op, Payment and Xero reports the types are currently not listed on the reports main page in column 'description'.

## Steps to Reproduce

1. Go to /admin/reports
2.
3.
4.

## Animated Gif/Screenshot

![grafik](https://user-images.githubusercontent.com/1790176/171847490-e5f2913f-7b4f-4d81-b745-5d06ead92d4d.png)

## Workaround

Select the type in the rendering options before creating the report.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.1.34
* Browser name and version: Firefox 100
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by jibees** [comment]
This will be handled by #9191 and commit f0584495f7466b78e0ab29969c9360c0af82f92f

**Comment by drummer83** [comment]
This has not been implemented, sorry.

**Comment by RachL** [comment]
@drummer83 it is it's just behind a feature toggle that will be removed once https://github.com/openfoodfoundation/openfoodnetwork/issues/9625 is done. so I think we can close?

**Comment by drummer83** [comment]
Oops, I wasn't aware of that.
Re-closing. 😉
