### ISSUE TITLE
Add landmark field to addresses

### ISSUE THREAD

**Issue by arthurtui** [openfoodfoundation/openfoodnetwork#9275]
## Description
**- As a:** enterprise user
**- On page:** Details step of registration form (/register)
**- I want to be able to do:** Add a landmark to my address

In rural areas in Brazil (and I believe other parts of the world suffer from the same issue), addresses can be very broad, and often additional details for addresses are offered in the form of landmarks to help orientating people searching for that address.

## Acceptance Criteria & Tests

1. See a "Landmark" optional field in the address when registering an enterprise
2. Fill that field with a value
3. See the value displayed in the other pages that also display an enterprise's address

**Comment by mkllnk** [comment]
@arthurtui Can you include the landmark in the address line 2? Have you done any research how this is handled by other platforms? We would like to be interoperable and addresses will be exposed in a standard format on the API. Is there a standard for a landmark field?

@openfoodfoundation/train-drivers-product-owners Does this align with our goals?

**Comment by RachL** [comment]
I have the same question than @mkllnk : can't address line 2 be used for landmark?
