### ISSUE TITLE
Server error on order confirmation page and order admin edit page when one product image is broken

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9279]
## Expected Behavior

Orders should always be editable as admin and the confirmation should always show to the user.

## Actual Behaviour

Pages can fail if they try to load a broken image.

## Steps to Reproduce

Requires dev knowledge.

1. Log into the Rails console or database.
2. Find a product image.
3. `image.attachment.blob.update(content_type: "application/octet-stream")`
4. Load an order containing the product of that image.

## Workaround

Re-upload offending images that don't display correctly in the shop or the product list.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.2.0-beta
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Use `Spree::Image#url` here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/08cc6ab1693f50867533c2787371e754c3217a85/app/views/spree/shared/_variant_thumbnail.html.haml#L6

```diff
diff --git a/app/views/spree/shared/_variant_thumbnail.html.haml b/app/views/spree/shared/_variant_thumbnail.html.haml
index d92e205a0..94246ea6a 100644
--- a/app/views/spree/shared/_variant_thumbnail.html.haml
+++ b/app/views/spree/shared/_variant_thumbnail.html.haml
@@ -3,4 +3,4 @@
 - else
   - # A Rails bug makes it necessary to call `main_app.url_for` here.
   - # https://github.com/rails/rails/issues/31325
-  = image_tag(main_app.url_for(variant.product.images.first.variant(:mini)))
+  = image_tag(variant.product.images.first.url(:mini))
```
## Error in OpenFoodNetwork Aus

**ActionView::Template::Error** in **spree/orders#show**
ActiveStorage::InvariableError

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62a12321bb3da700089c72e8?event_id=62a1909f00950bbe60aa0000&i=gh&m=ci)

## Stacktrace

    app/models/spree/image.rb:18 - variant
    app/views/spree/shared/_variant_thumbnail.html.haml:6 - _app_views_spree_shared__variant_thumbnail_html_haml___2298067171885791212_947300
    app/views/spree/orders/_summary.html.haml:19 - block in _app_views_spree_orders__summary_html_haml___88892310205784297_947280
    app/views/spree/orders/_summary.html.haml:14 - _app_views_spree_orders__summary_html_haml___88892310205784297_947280
    app/views/spree/shared/_order_details.html.haml:48 - block in _app_views_spree_shared__order_details_html_haml___2036512373848117335_947240
    app/views/spree/shared/_order_details.html.haml:44 - _app_views_spree_shared__order_details_html_haml___2036512373848117335_947240
    app/views/spree/orders/show.html.haml:28 - _app_views_spree_orders_show_html_haml__2063344321963506564_940840
    lib/session_cookie_upgrader.rb:19 - call

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62a12321bb3da700089c72e8?event_id=62a1909f00950bbe60aa0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by jibees** [comment]
I've tested your patch, but I got a `Nil location provided. Can't build URI.` 
Will debug.

**Comment by jibees** [comment]
Maybe should be handled at the same time than https://github.com/openfoodfoundation/openfoodnetwork/issues/9281 ?

**Comment by mkllnk** [comment]
Waiting for deploy.

Comment added in Bugsnag by Maikel
[**ActionView::Template::Error** in **spree/orders#show**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62a12321bb3da700089c72e8?event_id=62a2dd87009513a0a50b0000&i=gh&m=cm)

**Comment by mkllnk** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionView::Template::Error** in **spree/admin/images#index**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62a12321bb3da700089c72e8?event_id=62b3e56b0094ff771e2b0000&i=gh&m=eu)
