### ISSUE TITLE
Make customer address and phone non compulsory info at checkout

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#928]
As a hub manager, I want to be able to choose if the address and phone number fields are compulsory or not at checkout.

And when I select a "delivery" type shipping method, the system should open an address field pre-filled in if I already have filled in an address above, and here it should be compulsory field of course (=delivery). The invoice address can be different from the delivery address, so in any case we need to have another address field for the delivery method, even if the hub manager choose to keep the address compulsory field on the first part.

(original discussion here: http://community.openfoodnetwork.org/t/make-customer-address-and-phone-non-compulsory-info-at-checkout/554/3)

**Comment by myriamboure** [comment]
Ok, we had another discussion with our core beta testeur and this is a priority point. @blancnic do you think it's possible for you to work on that? See the discussion on Discourse.

**Comment by myriamboure** [comment]
Complement to the demand: the hub wants the clients to be able to order easily from a mobile without  having to log in, and entering the min info possible.

**Comment by daniellemoorhead** [comment]
Hi @myriamboure I can't see this being a big piece of work (feel free to correct me on this @oeoeaio or @enricostano or @Matt-Yorkley or @pacodelaluna or anyone else reading this), so I wonder whether Panier Ruse would be willing to contribute to its development?

**Comment by myriamboure** [comment]
To add in the scope : give the possibility for the hub manager to disallow comment on the checkout page (request from a user in France)

**Comment by myriamboure** [comment]
To add in the scope : give the possibility for the hub manager to disallow comment on the checkout page (request from a user in France)

**Comment by myriamboure** [comment]
@daniellemoorhead I wrote a quick spec so that @ltrls can start working on it, can you tell me if that wounds find to you ? It's  super quick, half a page ;-) https://docs.google.com/document/d/1dsimTJdu6XZ4-l16zxbDegSfMyNTxofBjplzA_lSmLw/edit?usp=sharing

**Comment by myriamboure** [comment]
I asked  Panier Rusé if they can chip in a bit, else we will try to cover that from the OFFrance budget as it seems to be pretty low cost / quick thing.

**Comment by daniellemoorhead** [comment]
@myriamboure I don't have a problem but I don't have the same understanding of the system as @sstead and @oeoeaio and @kirstenalarsen so perhaps they could have a look at this and understand if there is any impact?

**Comment by myriamboure** [comment]
Including https://github.com/openfoodfoundation/openfoodnetwork/issues/1197 in the scope

**Comment by daniellemoorhead** [comment]
Just adding a link to the ongoing scope conversation happening here: https://community.openfoodnetwork.org/t/make-customer-address-and-phone-non-compulsory-info-at-checkout/554/18

**Comment by myriamboure** [comment]
@sstead or @kirstenalarsen or @oeoeaio can we go for that ? https://docs.google.com/document/d/1dsimTJdu6XZ4-l16zxbDegSfMyNTxofBjplzA_lSmLw/edit?usp=sharing
I would like one other view than mine before @ltrls starts developping... so that there is no issue when merging!

**Comment by myriamboure** [comment]
Panier Rusé has agreed to contribute 200€ for that issue. Open Food France will put also 200€.
We are a bit blocked here, would be great to have another view... but I guess that all what we put in the document is customizable by the hub and doesn't change default so I don't think we take too much risk in moving forward @ltrls do you agree ?

**Comment by kirstenalarsen** [comment]
i have put some comments :)

**Comment by myriamboure** [comment]
Thanks @kirstenalarsen I took your comments into account. Launching now dev with @ltrls :-)

**Comment by myriamboure** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/checkout-customization-adapt-fields-required-to-the-hub-model-and-customer-type/1163
