### ISSUE TITLE
Invoice printing failing when logo image added

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/openfoodnetwork#9281]
## Description

After the move from Paperclip to Active Storage, Bulk Invoice printing is failing when invoices have logo images on them

Bugsnag error: (I don't have access to extended info)

Unhandled error
ActionView::Template::Error: The asset "" is not present in the asset pipeline.
Location
app/views/spree/admin/orders/invoice2.html.haml:11 - _app_views_spree_admin_orders_invoice__html_haml__44451502337717208_11240980

## Expected Behavior

Invoice printing should work with logo images on the invoice

## Actual Behaviour

Invoice printing failing when logo image added to invoice

## Steps to Reproduce
 - Print an invoice that use alternative model for an order of an enterprise that has a logo, and `DISPLAY LOGO IN INVOICES` 
 - You should have an invoice with a logo

## Workaround

Remove logo image

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
`no implicit conversion of ActiveStorage::VariantWithRecord into String`
on `/app/views/spree/admin/orders/invoice2.html.haml:11`
