### ISSUE TITLE
LoadError in db2fog:backup

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9287]
## Error in OpenFoodNetwork Aus

**LoadError** in **db2fog:backup**
cannot load such file -- mime/types

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62a057ce8ce5ce0008478111?event_id=62a2521600950e04c0570000&i=gh&m=ci)

## Stacktrace

    gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33 - require

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62a057ce8ce5ce0008478111?event_id=62a2521600950e04c0570000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by RachL** [comment]
@mkllnk just checking in on this one: is this still something to keep in dev ready?

**Comment by mkllnk** [comment]
Yes, I should at least check that we are still uploading backups...

**Comment by mkllnk** [comment]
This error didn't happen again and we are still uploading backups. I guess it's all fine.
