### ISSUE TITLE
 Enterprise admin page broken with V1.6 (translations issue)

### ISSUE THREAD

**Issue by blancnic** [openfoodfoundation/openfoodnetwork#929]
When  you click on an enterprise, you have a problem and nothing displays in the center of the screen.

![pasted image at 2016_04_27 09_14 pm](https://cloud.githubusercontent.com/assets/16450598/14886775/d7d721e2-0d52-11e6-84b4-91bf78c383e6.png)

In Firebug, I found this error:
NetworkError: 409 Conflict - https://staging.openfoodfrance.fr/enterprises/check_permalink?permalink=XXXX

**Comment by daniellemoorhead** [comment]
This issue has also been raised by @sigmundpetersen on Discourse - http://community.openfoodnetwork.org/t/whats-new-v1-6/527/2

And in slack #deployment channel. 

@RohanM and @oeoeaio and @mkllnk I think this is something we're going to need to fix before we can deploy the next release. Can we get onto this as a priority?

**Comment by daniellemoorhead** [comment]
This problem will already be fixed as part of release 1.7. Yay!

Therefore, closing this issue.
