### ISSUE TITLE
Backoffice orders: Set text color of 'choose customer' dropdown to white

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9296]
## Description

During testing of [#9212 ](https://github.com/openfoodfoundation/openfoodnetwork/pull/9212) it was observed that the text color of the dropdown menu to choose a customer has changed to dark grey, but it should be white (as before). This can be seen on page /admin/orders/[order_number]/customer while creating a backoffice order.

## Expected Behavior

The text should be white.

## Actual Behaviour

The text is dark grey.

## Steps to Reproduce

1. As an enterprise user: Create a backoffice order (click 'new order' on page /admin/orders).
2. Select a distributor and order cycle and click 'next'.
3. Select a product variant, add it to the order and click 'update and recalculate fees'.
4. Observe the color of the text 'Choose a customer' on the dropdown menu.

## Animated Gif/Screenshot

![grafik](https://user-images.githubusercontent.com/1790176/173158204-b3d7ed07-dd06-4f01-8353-1cbf9883616f.png)

## Workaround

No workaround.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [8fec5f1464b43ff72275db3880bbee9b880c8345](https://github.com/openfoodfoundation/openfoodnetwork/pull/9212/commits/8fec5f1464b43ff72275db3880bbee9b880c8345)
* Browser name and version: Firefox 100
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by leopengilley** [comment]
@drummer83 Hey Konrad, can I have a go please?

**Comment by drummer83** [comment]
Hi @leopengilley, welcome! Great to have you here!
I will assign it to you!
Have fun and get in touch if you need support! 😊
