### ISSUE TITLE
Product creation: Minor improvements of errors and mandatory information

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9298]
## Description

Note: This issue can be split into several even smaller issues to be solved. Every tiny pull request is welcome!

During testing of #9177 several minor inconsistencies have been found [see comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/9177#issuecomment-1132692337).  Here they are:
- Add "unit value" in the content of the red box at the top of the page if it was left blank during product creation. Currently this is only displayed if a 'unit size' had been selected in the first place.
![grafik](https://user-images.githubusercontent.com/1790176/173162647-b7828eec-65a2-4391-badb-a640f904696c.png)
- Add red highlighting and little text 'can't be blank' under the fields
  - unit size
  - unit value
  - product category
  ![grafik](https://user-images.githubusercontent.com/1790176/173162729-2001cb91-7a37-43e7-a50a-fa594ba25180.png)
- remove red star on Tax category (default value is preselected)
![grafik](https://user-images.githubusercontent.com/1790176/173162830-3ef07a0e-8ef3-4486-9c5a-5b008207936c.png)
- remove red star on Supplier (first supplier is preselected)
![grafik](https://user-images.githubusercontent.com/1790176/173162808-c53acb02-e39d-4a2a-b210-60e994c7e340.png)
- remove the option to select a blank 'unit size' in the dropdown (in 'product category' dropdown it is not possible to select 'blank')
![Peek 2022-06-11 01-46](https://user-images.githubusercontent.com/1790176/173163441-7f406f8c-5200-44a6-88c3-3ae90eb5fbd2.gif)

## Expected Behavior

See above.

## Actual Behaviour

See above.

## Steps to Reproduce

1. Start to create a new product on page /admin/products/new.
2. Leave fields with mandatory information blank (e.g. the product category).
3. Click 'Create'.
4. Observe the error messages and red highlighting.

## Animated Gif/Screenshot

![Peek 2022-06-11 01-40](https://user-images.githubusercontent.com/1790176/173163080-3c46b1b9-da67-4e54-9abe-68268bf8f933.gif)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by drummer83** [comment]
Hi @uzorjchibuzor, and welcome!
Yes, of course, I will assign it to you!
Don't hesitate to ask questions here or in our Slack in case you get stuck!

Looking forward to your contributions! 🥳

**Comment by abdellani** [comment]
let me handle this :)

**Comment by sigmundpetersen** [comment]
Sure thanks @abdellani , go ahead 🎉 
Don't hesitate to ask any questions here if you are stuck 👍

**Comment by sigmundpetersen** [comment]
Please also have a look at the previous PR attempt by another contributor here #9317

**Comment by abdellani** [comment]
From the product model, `unit_value` is only validated when the variant unit (unit size) is selected. 
```ruby
    validates :unit_value, presence: { if: ->(p) { %w(weight volume).include? p.variant_unit } }
```
So, if we submit an empty form. I belive we should not see an error related to that field.
Is that correct?

**Comment by drummer83** [comment]
@abdellani There is some complexity around this because for 'unit value = item' the 'unit size' is not mandatory anymore. Unit size is set to '1' unless you type something else.
To be honest, I don't really understand why it is that way.
To answer your question: Yes, that's my understanding as well. 👍🏻
