### ISSUE TITLE
Admin, Bulk Edit Product: can't clone a product

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#9309]
## Description
_Context: Trying to reproduce https://github.com/openfoodfoundation/openfoodnetwork/issues/660_

As an admin, from the Bulk Edit Product interface, it is impossible to clone a product. Clicking on the icon on the right of each row triggers an error, that seems to be related to ActiveStorage:
```
The product image was not recognised. Please upload an image in PNG or JPG format.
```
As I've the exception in french (although my interface is in EN...), I also copy/paste the FR message:
```
La validation a échoué : Images attachment a un contenu invalide, Images base L'image du produit n'a pas été reconnue. Veuillez importer une image au format PNG ou JPG.
```

## Expected Behavior
As an admin, in the Bulk Edit Interface, I can clone a product without a request error.

## Actual Behaviour
As an admin, in the Bulk Edit Interface, it is impossible to clone a product.

## Steps to Reproduce

1. As an admin, go to `/admin/products`
2. Click on the clone icon
3. Nothing happens, no clone at all, ajax request error.
```
Request URL: http://localhost:3000/api/v0/products/8/clone
Request method: POST
Status code: 422 Unprocessable Entity

{"exception":"La validation a échoué : Images attachment a un contenu invalide, Images base L'image du produit n'a pas été reconnue. Veuillez importer une image au format PNG ou JPG."}
```

## Workaround
?

## Severity
Don't know the severity.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by sigmundpetersen** [comment]
As #660 is an S3, I would say this also is S3

**Comment by jibees** [comment]
The stack trace:

```
app/models/spree/image.rb:30:in `no_attachment_errors'
lib/spree/core/product_duplicator.rb:18:in `duplicate'
app/models/spree/product.rb:282:in `duplicate'
app/controllers/api/v0/products_controller.rb:91:in `clone'
```

**Comment by RachL** [comment]
@jibees FYI I can't reproduce either. Are you still experiencing this?

@abdellani it might be tough, but if you are interesting in looking into [#660](https://github.com/openfoodfoundation/openfoodnetwork/issues/660), a lot of users are annoying by this oooold bug!

this comment can be helpfull: https://github.com/openfoodfoundation/openfoodnetwork/issues/660#issuecomment-137298238

**Comment by abdellani** [comment]
Ok @RachL , please assign it to me : )

**Comment by jibees** [comment]
It's maybe an edge case, not so relevant...

Actually, some images failed and those products I cannot clone them.

<img width="1039" alt="Capture d’écran 2022-10-18 à 10 40 10" src="https://user-images.githubusercontent.com/296452/196381024-7691be87-6ca6-4f1c-8369-49ccfb28557e.png">

<img width="806" alt="Capture d’écran 2022-10-18 à 10 39 43" src="https://user-images.githubusercontent.com/296452/196380913-8c3c4fa6-8272-452c-a0a8-39a1b76bff9c.png">


Probably something related to my local setup during development....
Closing then
