### ISSUE TITLE
Set up Bug Herd for a local instance

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#931]
1. Configure BugHerd API key for any instance who wants to use it, rather than current set up where all local instances use the Australian bug herd account.
2. Document how to set it up on discourse in the Super Admin section.

**Comment by elf-pavlik** [comment]
Any chance to also consider #740 so various instances can choose to use open source trackers like [Sentry](https://getsentry.com/welcome/) or [Errbit](http://errbit.github.io/errbit/). I guess I should just work on PR if I would like it to happen...

**Comment by daniellemoorhead** [comment]
@lin-d-hop FYI :)

**Comment by RohanM** [comment]
A branch with this feature (`bugherd-config`) is pushed ready for testing.

With #740, @elf-pavlik that sounds like a great idea, and the possible approaches that @mkllnk posted on that issue look good to me. A PR would be great :)
