### ISSUE TITLE
Total by suppliers report is not merging product quantity when selecting multiple shops

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9310]
## Description

We need to revert https://github.com/openfoodfoundation/openfoodnetwork/pull/9268 for Total by suppliers

On staging the report gives: 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/3e7d1050-a329-4881-b381-0b872ceb5144)

Lines with the same product should be merged has this report does not have a distributor column.

## Steps to Reproduce

1. Go to admin/reports and select "orders & fulfillment reports'
2. In the hub filter select 2 hubs which work with the same producer
3. Observe that the report does not merge lines.

## Animated Gif/Screenshot

See above

## Workaround

I'm not sure

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v.4.2
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Both

**Comment by filipefurtad0** [comment]
Ok, I see. This is the regression, right?

Before #9268:
![image](https://user-images.githubusercontent.com/49817236/173819330-167d8246-b8c3-4007-825e-26cf970736b2.png)

After #9268:
![image](https://user-images.githubusercontent.com/49817236/173819413-f450d064-a795-4b74-9963-0849c32f113e.png)

But is the solution to revert #9268 (closed an S1) or rather fix this S2?

**Comment by RachL** [comment]
@filipefurtad0 yes I think this is it.

Is it worth to check all sub reports to check if we have not another regression? Looking at what they are supposed to show (and my old files) it does not seem so, but I wonder :/
