### ISSUE TITLE
Remove code generating receipts

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9311]
### What we should change and why (this is tech debt)

Receipts were a feature develop by FR for FR needs back in 2017. After that, France (the country) issued some legal framework around receipts and this feature became obsolete.

OFN therefore introduced a switch in `admin/invoice_settings/edit` which allowed instance managers to turn this feature on/off to help FR transitioning to other solutions.

The last user using this in FR has finally stoped, so FR has finally deactivated receipts from their instance. :tada:

### Acceptance criteria

1. Check that all instances managed by global already has the feature deactivated
2. :fire: :

Any side effects?

**Comment by anansilva** [comment]
@RachL I'd like to take this one but I have some questions about the scope of it. 

From what I gathered, we have two places where we can print/send invoices, and these should be removed:

- Orders page
![Captura de ecrã 2023-02-09, às 16 41 49](https://user-images.githubusercontent.com/27692541/217881315-eab870ca-3846-44bb-83a0-3323a51e6a26.png)

- Order page 
![Captura de ecrã 2023-02-09, às 16 42 40](https://user-images.githubusercontent.com/27692541/217881398-40c325a0-edbf-46fa-86e2-c969cb8df8b3.png)

But these are tied to 'Invoice Settings' under the Configurations page:

![Captura de ecrã 2023-02-09, às 16 48 28](https://user-images.githubusercontent.com/27692541/217882196-a34e0660-63a3-4ce1-89dc-d949ce5a0c91.png)

**Is it safe to remove this whole 'Invoice Settings' module or does this impact any other invoicing features that I might not be aware of?**

I got a bit confused because after this issue was created (Jun 15, 2022), [a PR was merged adding code to this feature ](https://github.com/openfoodfoundation/openfoodnetwork/pull/9348). So I just want to make sure I'm not removing features I shouldn't.

Let me know if there are any other areas I should be aware of, regarding invoice creation. 

Thanks!

**Comment by filipefurtad0** [comment]
I've had a quick brainstorm with @anansilva, I must say I was also a bit confused and could not really answer the questions above.

My best guess is that the goal here is to remove the code activated by this checkbox? (and the checkbox itself)

![image](https://user-images.githubusercontent.com/49817236/217891996-dff706f1-e4fc-4a04-8374-6e92fbee82b4.png)

@RachL , can you confirm?

**Comment by RachL** [comment]
@filipefurtad0 @anansilva ah sorry I think I understand where the confusion came from. The issue is pointing to the wrong PR. I haven't found the correct PR, so I just removed the mention for now.

So yes confirming what Filipe said:
currently if the checkbox is activated there is only one place where you can see receipts/tickets (not invoices - [this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/9348) is impacting invoices not receipts) is under the order edit page action button:

![image](https://user-images.githubusercontent.com/6525576/217898458-26d003cf-a68a-4e7f-b845-0b1b20581df6.png)

It's the 2 options "Print ticket" and "select printer for tickets".

Both currently display an error message "Error: Unable to establish connection with QZ".

This feature is not supported anymore and no one is using it so yes to close this issue we must remove the code that is activated by this "show options for printing receipts using thermal printers..." checkbox and remove the checkbox itself.

QZ integration was added here I think: https://github.com/openfoodfoundation/openfoodnetwork/pull/1459

**Comment by anansilva** [comment]
Perfect, got it now! Thank you both, will open a PR soon.

**Comment by mkllnk** [comment]
> Check that all instances managed by global already has the feature deactivated

That's only something a core-developer with access to all instances can do. So I just ran this within ofn-install:
```
sql='select key,value from spree_preferences where key like $$%enable_receipt_printing%$$;'
ansible all-prod -u openfoodnetwork -a "psql -h localhost openfoodnetwork ofn_user -c '$sql'"

openfoodnetwork.org.au | CHANGED | rc=0 >>
                        key                        |   value   
---------------------------------------------------+-----------
 /spree/app_configuration/enable_receipt_printing? | --- false+
                                                   | 
(1 row)
openfoodnetwork.org.nz | CHANGED | rc=0 >>
                        key                        |  value   
---------------------------------------------------+----------
 /spree/app_configuration/enable_receipt_printing? | --- true+
                                                   | 
(1 row)
openfoodnetwork.ca | CHANGED | rc=0 >>
                        key                        |   value   
---------------------------------------------------+-----------
 /spree/app_configuration/enable_receipt_printing? | --- false+
                                                   | 
(1 row)
app.katuma.org | CHANGED | rc=0 >>
                        key                        | value 
---------------------------------------------------+-------
 /spree/app_configuration/enable_receipt_printing? | f
(1 row)
coopcircuits.fr | CHANGED | rc=0 >>
                        key                        |   value   
---------------------------------------------------+-----------
 /spree/app_configuration/enable_receipt_printing? | --- false+
                                                   | 
(1 row)
openfoodnetwork.de | CHANGED | rc=0 >>
                        key                        |   value   
---------------------------------------------------+-----------
 /spree/app_configuration/enable_receipt_printing? | --- false+
                                                   | ...      +
                                                   | 
(1 row)
openfoodnetwork.hu | CHANGED | rc=0 >>
                        key                        |  value   
---------------------------------------------------+----------
 /spree/app_configuration/enable_receipt_printing? | --- true+
                                                   | ...     +
                                                   | 
(1 row)
openfoodnetwork.org.uk | CHANGED | rc=0 >>
                        key                        |   value   
---------------------------------------------------+-----------
 /spree/app_configuration/enable_receipt_printing? | --- false+
                                                   | 
(1 row)
openfoodnetwork.net | CHANGED | rc=0 >>
 key | value 
-----+-------
(0 rows)
openfoodnetwork.be | CHANGED | rc=0 >>
                        key                        |  value   
---------------------------------------------------+----------
 /spree/app_configuration/enable_receipt_printing? | --- true+
                                                   | ...     +
                                                   | 
(1 row)
openfoodnetwork.ie | CHANGED | rc=0 >>
 key | value 
-----+-------
(0 rows)
```

So unfortunately, we have a few instances which have this activated:

- openfoodnetwork.be
- openfoodnetwork.hu
- openfoodnetwork.org.nz

@RachL Do we need to check in with these instances? You also said that it's broken. So nobody would expect this to be present, right?

**Comment by jibees** [comment]
Just a quick note, not fully related to this thread: @mkllnk thanks for pointing me a way to run a sql query on all managed servers ;)
