### ISSUE TITLE
Allow super admin to activate if "company number" is mandatory or not

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9315]
## Description
**- As a:** super admin
**- On page:** `/admin/invoice_settings/edit`
**- I want to be able to do:** I want to be able to activate or deactivate the fact that "company number" is required to print invoices.

Mockup: 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/aadaf9e9-7cd4-4373-bff9-266b25f4ff8b)

Context : https://github.com/openfoodfoundation/wishlist/issues/217

## Acceptance Criteria & Tests

1. Login as superadmin
2.  Go to `/admin/invoice_settings/edit`
3.  See that the checkbox is checked by default
4. Try to print invoices for company with empty number. You should have this message popin up : 
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/867928c7-c663-46f6-8f95-9e23639a594e)
5. Go back to  `/admin/invoice_settings/edit`
6. Tick the checkbox off
7. You should be able to print invoices for those enterprises.

**Comment by jibees** [comment]
I guess it's also available for "Send invoice" action?
<img width="214" alt="Capture d’écran 2022-06-23 à 11 11 11" src="https://user-images.githubusercontent.com/296452/175262953-3a37e171-3af8-4cab-bef8-1751a74128e7.png">

**Comment by RachL** [comment]
@jibees yes good catch

**Comment by RachL** [comment]
@jibees the checkbox should make ABN mandatory or not, same as bulk invoice printing or invoice printing.

Why do you mention phone number? It's currently mandatory as well?

**Comment by filipefurtad0** [comment]
> you could not send invoice if an ABN is not present for the order's distributor, but you could print it

This PR also made me wonder... Should we keep allowing for PDF printing _without_ ABN?

**Comment by RachL** [comment]
@filipefurtad0 I'm afraid using checkbox and ticked and ABN can be missinterpreted, so to put it in other words:

- In FR it is mandatory to have an ABN to issue an invoice
- In CA or UK it is not

So if the checkbox is ticked, you cannot print a PDF _without_ an ABN (FR case).
