### ISSUE TITLE
Super admin: Don't prefill password on user page

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9337]
## Description

If the browser has a users login data stored and the super admin want to make changes on the /admin/users/[ID] page, there is an error, because the password is prefilled but the password confirmation is empty.

## Expected Behavior

The password field is there only to provide a new password. If other changes are made on that page, the password field should simply be empty.

## Actual Behaviour

The password field is prefilled with stored login data, which lead to an error.

## Steps to Reproduce

1. As a user log in and save the login data in your browser.
2. As a super admin go to the /admin/users/[ID] page of that user.
3. See that the password field is filled while the password confirmation is empty.

## Animated Gif/Screenshot

![Peek 2022-06-21 18-53](https://user-images.githubusercontent.com/1790176/174855507-70e317bf-5b9b-4a48-a1cc-9d85e3a5121c.gif)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [606a56a64de9fd3f6145e45a3d1865e817fcb4de](https://github.com/openfoodfoundation/openfoodnetwork/pull/9154/commits/606a56a64de9fd3f6145e45a3d1865e817fcb4de)
* Browser name and version: 101.0.1 (64-Bit)
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by saunmanoj888** [comment]
hii @drummer83 
Can this issue be assigned to me? If the fix is not required urgently. I can work to fix the issue this weekend.

**Comment by drummer83** [comment]
Cool @saunmanoj888,

I have assigned it to you!
It is not super urgent! 👍🏻
