### ISSUE TITLE
Deactivated user: Redirect to homepage with flash error when trying to access /admin

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9338]
## Description

When a deactivated user tries to access an admin page, he/she is redirected to the homepage with the login modal open. Trying to log in there redirects to the homepage without login modal - which feels like the user has successfully logged in, but he/she actually hasn't. He/she can access shops but the checkout flow is broken: Clicking checkout in the cart always takes the user back to the shop with empty cart.
![Peek 2022-06-21 19-20](https://user-images.githubusercontent.com/1790176/174860316-d8e32459-1ef5-43a7-b84d-a7daa1cf85dd.gif)

## Expected Behavior

When a deactivated user is trying to access an admin page, he/she should be redirected to the homepage with the flash error message as shown below.
![grafik](https://user-images.githubusercontent.com/1790176/174860835-a6320138-7dcd-407e-9446-252298bb84be.png)

## Actual Behaviour

The user is redirected to the homepage with login modal but login doesn't work and checkout flow is broken.

## Steps to Reproduce

1. As super admin deactivate a user.
2. As deactivated user try to access /admin --> login modal appears
3. Try to login --> homepage opens
4. Try to checkout --> not working

## Animated Gif/Screenshot

See above.

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: staged [606a56a64de9fd3f6145e45a3d1865e817fcb4de](https://github.com/openfoodfoundation/openfoodnetwork/pull/9154/commits/606a56a64de9fd3f6145e45a3d1865e817fcb4de)
* Browser name and version: 101.0.1 (64-Bit)
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

## Possible Fix

See #9154 for implementation of the deactivation of a user.

**Comment by vsmay98** [comment]
Hi @drummer83 
Can I work on this issue?

**Comment by RachL** [comment]
Hello @vsmay98 yes it's cleaner if we do it for any page rather than just the admin :+1: You can go ahead :)

**Comment by drummer83** [comment]
Thanks for your PR, @vsmay98! It is now in code review by our developers. This may take a few days or so and will probably not happen during the weekend. There seems to be a conflict with another PR #9341. We will get back to you if we need to.
In the meantime feel free to pick another issue and let us know!

Have fun! And thanks again! :smiley:
