### ISSUE TITLE
Google Analytics number is hardcoded

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#938]
Looking at `https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/shared/_analytics.html.haml`, it seems to have a single GA `UA` code in it. Should this be changed to insert some Spree code that supports their trackers mechanism? Or make the `UA` number a variable?

@RohanM @mkllnk @oeoeaio please comment :)

cc @lin-d-hop

**Comment by oeoeaio** [comment]
I don't have much experience with GA but I think that is a sensible idea...

**Comment by mkllnk** [comment]
I think GA should be optional. There are good reasons not to use it:

- Not everybody wants to give their user data to Google.
- It can slow down the website.
- There are alternatives.

How does Spree's tracking system work?

**Comment by pmackay** [comment]
See https://spreecommerce.com/blog/ecommerce-tracking-in-spree. Need to do this to get it to work:

> If the Javascript is not present, be sure you are still including the spree/shared/google_analytics partial in your application layout.

Then it would be optional because its configurable via Spree admin. However it seems like it only works for commerce checkouts, not all pages. If so, how important is tracking all pages? How often do you use the tracking you currently have? Would it be ok to just remove the current hardwired tracking code? 

@mkllnk have you used any alternatives before?

**Comment by mkllnk** [comment]
No, I haven't used any alternatives.

I personally would be happy to remove the Google Analytics code. But I think some people would like to keep it.

@daniellemoorhead:

- Are we using Google Analytics?
- Who is interested in it?
- Do we have capacity to analyse the data?
- Do we have capacity to act on the insights?

**Comment by daniellemoorhead** [comment]
@mkllnk it's not an option to remove the analytics code. Definitely not.

- We do use Google Analytics, @sstead reports on stuff each month for the OFN au board.
- Not sure what you mean by who is interested in it...?
- See first point
- We're not using it for product development (is that what you mean?), but we will need insights if we get funding to redo the front end experience.

The bigger question is how can we set this up so that every local instance can have it's own version running? Was this considered when it was added in the first place? @RohanM or @oeoeaio or @serenityhill can you shed any light on this?

**Comment by pmackay** [comment]
@daniellemoorhead could you please add a bit more detail about what info from the analytics you use? Is it important to have stats for all the pages accessed?

Am asking because Spree has some capacity for GA built in, which is configurable, but it may only work when shop checkouts are made. How much of a problem would that be?

**Comment by daniellemoorhead** [comment]
Can't tell you off the top of my head @pmackay and I'm full time elsewhere at the moment. As I said, it's @sstead who's using the stats in her reporting so she could shed some light. Or give you access to the dashboard / send you an exported report. 

Have to say, my initial reaction is dread as I don't like the idea of not having access to all the data when/if we need it. It's a foreign concept to me not to have it there on hand. Happy to sit down and have a longer conversation about this, but just tracking shop checkouts IMO isn't enough.

**Comment by pmackay** [comment]
@oeoeaio @mkllnk see #988 for a quick fix to this. Would you like it tested on a staging server before merging, to verify it is gathering stats? @lin-d-hop could we put on UK staging? And what chance is there to get into v1.7.1?

**Comment by lin-d-hop** [comment]
@pmackay Def feel free to put onto UK staging and have a play!

**Comment by sstead** [comment]
The board asked us for basic analytics, at the moment we just report # of users, length of stay, # of sessions. From speaking to Dani, it seems the main concern is that we'd like to have GA in place in case we want to gather this data, or additional data in the future. @pmackay @daniellemoorhead Here is the link to our dashboard configuration https://analytics.google.com/analytics/web/template?uid=sGZtQnDDSB-8MefiMUgWiw (it won't contain our traffic data). And here is a report from our current dashboard - 
[Analytics All Web Site Data OFN AU - General Knowledge 20160410-20160510.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/258554/Analytics.All.Web.Site.Data.OFN.AU.-.General.Knowledge.20160410-20160510.pdf) . Let me know if you need to login to our GA dashboard Paul.

**Comment by daniellemoorhead** [comment]
Heya @sstead - @pmackay has asked for GA access so would be great to set him up with access. I'll send you via slack his email address. Ta!

**Comment by sstead** [comment]
Paul let me know if you require login, the above might be enough.

**Comment by pmackay** [comment]
@lin-d-hop this is on UK staging now, I can configure a staging specific GA code and see the page views in realtime. So it definitely does basic logging as well as commerce.

Could #991 be merged?

**Comment by mkllnk** [comment]
:+1: from me.
