### ISSUE TITLE
Format ALL money amounts in report spreadsheets and on screen as numbers

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9384]
## Description

Follow up of #9229.

According to [testing notes of #9229](https://github.com/openfoodfoundation/openfoodnetwork/pull/9229#issuecomment-1161768607) we still have some money amounts in the report spreadsheets and on screen formatted as 'text' or 'text with currency'. These formats can't be used for calculations and should be converted to numbers as in all other reports.

Affected reports are:
- Bulk coop Supplier report
- Enterprise fees
- Pack by customer
- Pack by supplier
- Pack by product

![grafik](https://user-images.githubusercontent.com/1790176/177188839-beed8441-cc2f-413e-8404-77c6384670c2.png)

## Expected Behavior

All money amount in report spreadsheets and on screen should be displayed as numbers.

## Actual Behaviour

Some money amounts are displayed as 'text' or 'text with currency'.

## Steps to Reproduce

1. Make sure you have some orders.
2. Go to admin/reports.
3. Generate the report of interest on screen or as a spreadsheet.

## Animated Gif/Screenshot

![grafik](https://user-images.githubusercontent.com/1790176/177190210-bd34e81d-e9cf-455a-923b-e277434bb0bf.png)

## Workaround

None.

## Severity
bug-s3

## Your Environment

* Version used: staged [ae8f14a6719e5c4a2f994eb10a51eed6e126ae0f](https://github.com/openfoodfoundation/openfoodnetwork/pull/9229/commits/ae8f14a6719e5c4a2f994eb10a51eed6e126ae0f) 
* Browser name and version: Firefox 101.0.1 (64-Bit)
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by drummer83** [comment]
@jibees This issue is mainly about xlsx and on screen. Did you include them in your PR as well?

**Comment by jibees** [comment]
> @jibees This issue is mainly about xlsx and on screen. Did you include them in your PR as well?

sure!
