### ISSUE TITLE
Notes on orders: Immediately edit or delete the note (and tracking information)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9397]
## Description

Follow up of #9368 
Some improvements of usability and to make sure the implementation is according to specification ([see mockup here](https://github.com/openfoodfoundation/openfoodnetwork/issues/9178#issue-1234182060)).

## Expected Behavior

- As soon as clicking the 'edit' icon, the cursor should be placed at the end of the note to start typing without an extra click.
- Add the 'delete' icon to immediately delete the note without having to edit and delete the text. When hovering over the delete icon, use the red styling and the crossed out text styling as on line items.
- Both should be implemented for the tracking information at the same time.

## Actual Behaviour

- After clicking the 'edit' icon you have to click inside the text field first to start typing.
- There is no direct 'delete' icon.
- Same for tracking information.

## Steps to Reproduce

1. Go to /admin/orders/[order-number]/edit.
2. Try to edit or delete the note.

## Animated Gif/Screenshot

![grafik](https://user-images.githubusercontent.com/1790176/177958435-af1167e6-60a8-4bc6-9134-509b95499986.png)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [89809aed5fdcd953d13b9108290c942a5182ceb4](https://github.com/openfoodfoundation/openfoodnetwork/pull/9368/commits/89809aed5fdcd953d13b9108290c942a5182ceb4)
* Browser name and version: Firefox 102.0 (64-Bit)
* Operating System and version (desktop or mobile): Desktop Windows 10

**Comment by binarygit** [comment]
hello! Could you please assign this to me?

**Comment by drummer83** [comment]
I would love to, but I still can't. Not sure why. We will fix that on Monday. 👍🏻

**Comment by sigmundpetersen** [comment]
Hey @drummer83 I think it's a bug in Zenhub so it only works if opening the issue in its own tab 👍
