### ISSUE TITLE
Downtimes caused by orders and fulfillment report

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9398]
## Description

UK and FR have been having downtimes since the reports overhaul. Last time reported was a few weeks ago, see [here](https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1656517709091749?thread_ts=1656508480.737279&cid=C01T75H6G0Z).

## Expected Behavior

All sub-reports from orders and fulfillment should have the name of the last order cycle pre-selected, on `Order Cycle` field (see Possible fix section). This should contribute to preventing server down.

This is how each report should look like, when accessing the respective URL:

Order Cycle Supplier Totals - `admin/reports/orders_and_fulfillment/order_cycle_supplier_totals`

![ksnip_20220708-181441](https://user-images.githubusercontent.com/49817236/178039722-3b95f6f2-8610-4c9f-87fe-07136d356f41.png)

Order Cycle Supplier Totals by Distributor - `admin/reports/orders_and_fulfillment/order_cycle_supplier_totals_by_distributor`

![image](https://user-images.githubusercontent.com/49817236/178038480-5bc97193-33a8-4f91-b67a-e331e0ff105c.png)

Order Cycle Distributor Totals by Supplier - `admin/reports/orders_and_fulfillment/order_cycle_distributor_totals_by_supplier`

![image](https://user-images.githubusercontent.com/49817236/178038675-84a56c8d-8935-4ca2-8e3d-ff45666e2247.png)

Order Cycle Customer Totals - `admin/reports/orders_and_fulfillment/order_cycle_customer_totals`

![image](https://user-images.githubusercontent.com/49817236/178038958-4c986203-f6a6-4fac-9500-a7b103b2377b.png)

## Actual Behaviour

Downtimes caused caused by orders and fulfillment report.

## Steps to Reproduce

Plenty of users simultaneously calling orders and fulfillment report... I guess this could be reproduced with a load test, on a staging server.

## Animated Gif/Screenshot

How it looked like on Datadog:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/7c0cde59-7774-4c64-a390-4813f9c9c536)

## Workaround

None other then watiting till the server recovers

## Severity

When occurring, this is an S1. AFAIK last occurrence was on June 29th.

## Your Environment

* Version used: last observed on v4.2.3

## Possible Fix

Not a fix, but a possible way to prevent this in the long run could be long term solutions could be [pagination](https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1656692336515579?thread_ts=1656688554.114709&cid=C01T75H6G0Z).

A more short term quick-win was proposed [here](https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1656928215293369?thread_ts=1656688554.114709&cid=C01T75H6G0Z) and consists of adding the last order cycle as a pre-selected option. This is the preferred option for now and hence the good first issue and papercut labels - to be confirmed.

**Comment by binarygit** [comment]
Hey :wave: @filipefurtad0 I'd like to help out with this. However, I can't find the file that's actually responsible for the search bar. I know that the page like: `http://localhost:3000/admin/reports/orders_and_fulfillment/order_cycle_supplier_totals` is rendered by `app/views/admin/reports/filters/_orders_and_fulfillment.html.haml` But it's a simple rails view and I think the search bar functionality comes from an angular (plugin, maybe) but can't find the file. Can you help me out please? :smile:

**Comment by filipefurtad0** [comment]
Hi @binarygit ,

Welcome. Thanks for your interest on this issue. I'm afraid I won't be able to provide any more insight than @jibees already has on with the reply above. I'll assign you to the issue for now, but if it turns out to be too challenging feel free to move on to another one.

Thank you :pray:

**Comment by binarygit** [comment]
Hey @jibees. Sorry, I think I was unclear on what I am not finding. The line of code you mention does render the component but it's a simple rails `select` helper and doesn't have the features that this component has, namely the input element that enables type and search (which is why I called it a search bar :smile: )

![search-bar](https://user-images.githubusercontent.com/87677429/178230210-29ac25b4-6852-4321-895a-4c6e6574f692.png)

Removing the `select2` class from the above code yields the normal rails `select` component rendered by the `select helper`

![rem-select1](https://user-images.githubusercontent.com/87677429/178230873-49d63b48-15f9-4294-8149-d0b51599ee45.png)

but that's just a CSS class and all that functionality must come from JS (which is why I suspect it's maybe a angular plugin or something). If I could look at the code that's actually enables the selection and shows the selected elements inside the bar...I could perhaps modify it to do what we want it to do.

**Comment by jibees** [comment]
Ok, now I understood what you mean! 
We used to use the npm package `select2` (https://www.npmjs.com/package/select2) and gem `select2-rails` (https://github.com/argerim/select2-rails) to render such component. 
But now, we decide to transition to `tom-select` (https://tom-select.js.org/) that is bases on stimulujs. you can find example in our code by searching `tom-select`, for example: 

https://github.com/openfoodfoundation/openfoodnetwork/blob/3b6b2ea9368f5a42312009b97d4adddbb03f3b9d/app/views/spree/admin/orders/customer_details/_address_form.html.haml#L36-L37

The controller is: `app/webpacker/controllers/tom_select_controller.js`

So, if you want to modify this, please use the `tom-select` wrapper/component! Thanks!

**Comment by binarygit** [comment]
gothca! Thank You!

**Comment by binarygit** [comment]
Hey! sorry, I only had time to work on this today which is why it took a bit of time to complete. Please check the PR and let me know if there's anything!

**Comment by RachL** [comment]
Just to be sure here: we adding the last order cycle but we are not removing dates, is that correct?

**Comment by binarygit** [comment]
yup @RachL just adding the last order cycle but not removing the dates.

**Comment by filipefurtad0** [comment]
Not the best solution as discussed [here](https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1661847250148009?thread_ts=1661847081.332509&cid=C01T75H6G0Z), closing.
