### ISSUE TITLE
Finalize usability optimizations of notes and tracking information

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9409]
## Description

Follow up of #9399 

Some open issues were found during implementation and testing of #9399. These are summarized in this issue.
Please note that each issue can be solved independently of the others.

## Expected Behavior

1. Use the same red highlighting and crossed out text styling when hovering over the 'delete' icon as on product items.
2. When creating a new back office order (on page admin/orders/new) do not display the 'notes' field until a first item has been added to the order (hide it just like tracking information)
![image](https://user-images.githubusercontent.com/1790176/179021708-5e41556a-adbb-4283-9e22-07d3774473f4.png)
3. Display 'delete' icon only when note or tracking information is present.
![image](https://user-images.githubusercontent.com/1790176/178840804-65701417-c377-476a-ad07-2dc18d80b99c.png)
4. Add a confirmation dialog: Are you sure? when deleting a note or tracking information. Use the same styling as when deleting a product from the order.
![image](https://user-images.githubusercontent.com/1790176/178841123-d84e76a6-f574-470c-81bf-eeb08cd033f0.png)
5. Do not show the 'Tracking information:' row without any further information in the shipping email when there was tracking information provided which got deleted later.
![image](https://user-images.githubusercontent.com/1790176/178840598-dc8e5cb5-2dd3-4987-b67b-6d4cc2f665c3.png)

## Actual Behaviour

1. There is not red highlighting or crossed our text styling when hovering over the 'delete' icon.
2. Note is always visible, but table looks broken (see screenshot above)
3. Delete icon is always present.
4. There is no confirmation dialog.
5. If there was a tracking information added, which then has been deleted, in the shipping email there will be the 'Tracking information:' row without any further information

## Steps to Reproduce

1. Go to admin/orders
2. Click the 'edit' icon next to an order
3. Check the behaviour of notes and tracking information.

## Animated Gif/Screenshot

See above.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [6ad0749ce8fbc31fda4adedd4d571d0d5fa8e733](https://github.com/openfoodfoundation/openfoodnetwork/commit/6ad0749ce8fbc31fda4adedd4d571d0d5fa8e733)
* Browser name and version: Firefox 102.0 (64-bit)
* Operating System and version (desktop or mobile): Desktop Windows 10

**Comment by binarygit** [comment]
Hey @drummer83 :wave: I want to take a crack at this, could you assign it to me?

**Comment by drummer83** [comment]
Here you go! 💪
