### ISSUE TITLE
Check if image resizing converts PNG to JPG where required 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#941]
i.e. Large banners

**Comment by pmackay** [comment]
Should an image format conversion actually happen? Why not get users to upload correct image?

**Comment by Matt-Yorkley** [comment]
Users won't always have the software or the know-how to convert image formats.

**Comment by mkllnk** [comment]
This was done by Paperclip but is currently not done by Active Storage. It's possible but nobody has asked for this lately. Let's keep users in control for now and optimise later if we have capacity to work on this.
