### ISSUE TITLE
Resend confirmation email in bulk (from the admin orders page)

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9420]
## Description
**- As a:** enterprise user and super admin
**- On page:** `admin/orders`
**- I want to be able to do:** select several orders and send them per email (same action that is available under the edit button today, but this time in bulk)

![image](https://user-images.githubusercontent.com/6525576/179571871-9ba2b2fc-40ed-4cfb-808f-9545ebee1dca.png)

Use this design for the confirmation modal : https://github.com/openfoodfoundation/wishlist/issues/44#issuecomment-917722084

Keep same order in dropdown than in order edit page.

## Acceptance Criteria & Tests

1. Log as enterprise user
2.  Go to `admin/orders`
3. Select one or several orders
4. Click on resend confirmation in the dropdown
5. See the confirmation modal
6. If you select yes on the confirmation check the emails are correctly sent and are the same you would receive if you've had used the actions dropdown in the edit order page.
7. Check if cancelling on the modal works

Repeat with super admin

**Comment by jibees** [comment]
I've started to work on it, but I think I've a question.
On my local setup, I've two orders:
 - R481177037, CANCELLED	
 - R853342257, COMPLETE

If I go on the complete one page: `admin/orders/R853342257/edit`, I can resend the confirmation email
<img width="334" alt="Capture d’écran 2022-10-17 à 15 12 04" src="https://user-images.githubusercontent.com/296452/196185933-7b629de5-6cbd-484d-a448-91d2d307b3c7.png">

But, if I go to the other one page `/admin/orders/R481177037/edit`, I can't do nothing (the UI is not really fine here and seems broken) :
<img width="246" alt="Capture d’écran 2022-10-17 à 15 12 41" src="https://user-images.githubusercontent.com/296452/196186060-86bca5b9-42d9-4754-9707-0c42a4b7381e.png">

I I go to the index page, and select only the order which is cancelled, it appears that I can either do cancel or print the cancelled invoice:
<img width="608" alt="Capture d’écran 2022-10-17 à 15 14 21" src="https://user-images.githubusercontent.com/296452/196186403-f47db9de-1c4b-442e-934c-547948d0a7b3.png">

Which is pretty weird at some point. 

So, I'll assume that we will have the same behavior for the "Resend confirmation email" action.

**Comment by RachL** [comment]
@jibees yes we are well aware of the problem. We spoke together about it in papercut meeting when analyzing the solution here : https://github.com/openfoodfoundation/wishlist/issues/261 but it took too much time to discuss it during papercut meeting. For now, let's keep same behavior, but it would be good to find other solutions for 261 soon.
