### ISSUE TITLE
Cancel orders in bulk (from the admin orders page)

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9422]
## Description
**- As a:** enterprise user and super admin
**- On page:** `admin/orders`
**- I want to be able to do:** select several orders and cancel them (same action that is available under the edit button today, but this time in bulk)

![image](https://user-images.githubusercontent.com/6525576/179774364-ae97210a-911a-4499-8fb1-4a805aa27757.png)

Use the same design for the confirmation modal we have when cancel orders today (with the option to untick sending the email to the customer)

Keep same order in dropdown than in order edit page.

## Acceptance Criteria & Tests

1. Log as enterprise user
2.  Go to `admin/orders`
3. Select one or several orders
4. Click on cancel in the dropdown
5. See the confirmation modal with the option to not to send email to customer
6. If you select yes on the confirmation check the emails are correctly sent and are the same you would receive if you've had used the actions dropdown in the edit order page.
7. Check if cancelling on the modal works

Repeat with super admin

**Comment by binarygit** [comment]
Hello, I would like to take this on, could you assign it to me please?

**Comment by sigmundpetersen** [comment]
Yes, thank you @binarygit , go ahead 🙂

**Comment by drummer83** [comment]
Hey @RachL and @binarygit,
I guess the action should read 'Cancel orders' and not 'Cancel invoices' (see screenshot above), right?
Just to clarify and get the label right from the beginning...

**Comment by RachL** [comment]
@drummer83 @binarygit ah yes copy paste problem!

**Comment by binarygit** [comment]
Hello, I've been looking at how this feature could be implemented but I can't seem to find where the `order.cancel` method is defined. I want to see how it's been written so that I know what happens. This is the code that fires the `cancel` method on an order:

```ruby
app/controllers/spree/admin/orders.rb

      def fire
        event = params[:e]
        @order.send_cancellation_email = params[:send_cancellation_email] != "false"
        @order.restock_items = params.fetch(:restock_items, "true") == "true"

        # event is cancel here so the following line is basically
        # @order.cancel
        if @order.public_send(event.to_s)
          flash[:success] = Spree.t(:order_updated)
        else
          flash[:error] = Spree.t(:cannot_perform_operation)
        end
      rescue Spree::Core::GatewayError => e
        flash[:error] = e.message.to_s
      ensure
        redirect_back fallback_location: spree.admin_dashboard_path
      end
```

I checked the orders model. I found an `allow_cancel?` method but there's no `cancel`

**Comment by jibees** [comment]
Event/State for ActiveRecord model in our codebase is handled by `state_machines-activerecord`. For order, this is tested through the file `spec/models/spree/order/state_machine_spec.rb`
You probably also want to check `app/services/customer_order_cancellation.rb` and the associated PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/6720
