### ISSUE TITLE
Shipping and Payment methods: add a new translation key for green menu "calculator"

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9423]
### What we should change and why (this is tech debt)

The section to set up fees for shipping or payment methods is currently called 'Calculator'. New users may not understand what is calculated here. The proper name for this section would be 'Fees' and within this section you select the calculator you want to use for that fee.
Currently both (section name and calculator name) are using the same string. That's why it is not possible to solve this in Transifex alone.
![grafik](https://user-images.githubusercontent.com/1790176/170703520-2bd17d5f-2e81-4561-a1d1-dd87efb739e3.png)

## Additional context
The code for this can be found in this file: 
/app/views/spree/admin/shared/_calculator_fields.html.haml

It is used on the following pages:
/admin/shipping_methods/new
/admin/shipping_methods/[NUMBER]/edit
/admin/payment_methods/new
/admin/payment_methods/[NUMBER]/edit

**Comment by saunmanoj888** [comment]
hii @drummer83 
Can I work on this issue?

**Comment by drummer83** [comment]
Here you go! 💪🏻

**Comment by saunmanoj888** [comment]
hii @drummer83
 Going through the title and description of this issue, I just want to confirm that we just need a translation for the section name `Calculator`. We don't want to change `Calculator` to `Fees`. Am I right here?

**Comment by drummer83** [comment]
Hi @saunmanoj888,
it's great that you are asking! 👍🏻
Yes, we only want the section header to be changed to fees (added the green circle).
![Screenshot_20220724-175049_Firefox.jpg](https://user-images.githubusercontent.com/1790176/180655564-b988259d-a9d9-4fb6-8b0b-22b66fdac615.jpg)
Looking forward to this contribution! 🤗
