### ISSUE TITLE
Calculator: Provide a calculator 'none'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9424]
## Description
**- As a:** enterprise user or super admin
**- On page:** `/admin/shipping_methods/new` `/admin/shipping_methods/XXX/edit` and  `/admin/payment/new` `/admin/payment/XXX/edit` 
**- I want to be able to do:** set the calculator to "none" or "empty" by default.

## Acceptance Criteria & Tests

1. Log in as enterprise user
2.  Go to `/admin/shipping_methods/new` `/admin/shipping_methods/XXX/edit` and  `/admin/payment/new` `/admin/payment/XXX/edit` 
3. See that when creating the dropdown of the calculator is set to "none" by default, and that you can change it to "none" when editing.
4. When using "none" the calculator has no value

**Comment by apricot12** [comment]
I'm gonna give this a go :)

**Comment by RachL** [comment]
Hello @apricot12 ! I hope this message finds you well :) Are you still working on this one? Don't hesitate to ask if you need guidance.

**Comment by apricot12** [comment]
> Hello @apricot12 ! I hope this message finds you well :) Are you still working on this one? Don't hesitate to ask if you need guidance.

Hi @RachL, I'm doing well and thanks for asking! I'm still gonna work on this, it just happened that there were some state holidays and festivals right after I assigned this to myself so I just never had an opportunity to get started 😭

**Comment by RachL** [comment]
No worries, hope you had a nice time :+1:

**Comment by RachL** [comment]
@apricot12 Hello. I will unassigned you for now as it looks like you don't have much time. Feel free to pick this one up again once you have more space! I hope everything is ok for you.
