### ISSUE TITLE
[Admin dashboard] Make the shop URL clickable 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9427]
## Description
On the admin dashboard, in "[Enterprises](https://coopcircuits.fr/admin/enterprises)" > "Primary details", the url pointing to the shop is not clickable.

## Expected Behavior
The URL should direct to the shopfront by a simple click. The URL should be underlined (and of a different color ?) to outline that it is an actual link. 

## Actual Behaviour
The URL is a text that can't be clicked.

## Steps to Reproduce
1. Connect as a user with at least one shop, go to the "Enterprises" tab (https://coopcircuits.fr/admin/enterprises)
2. Click on the shop url in the "Primary details" tab

## Animated Gif/Screenshot
![Screen Shot 2022-07-19 at 20 03 11](https://user-images.githubusercontent.com/28386648/179818678-581e38b3-3f60-4150-969e-7637e6b0c6c9.png)

## Workaround
Copy/paste the shop url.

## Severity
bug-s4: it's annoying, but you can use it, but it is quite annoying for the users while the issue #5997 is not resolved.

**Comment by Philwi** [comment]
Hey, I would like to start with this ticket. Could you assign me?  :)

I have one question: should the click on the link open a new tab or on the same tab?

**Comment by RachL** [comment]
Yes, create a new tab is the way to go 👍 1:
