### ISSUE TITLE
[Admin dashboard] Missing translations when printing invoice

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9441]
## Description
Some strings are displayed in French, they should be translated to English. 

## Steps to Reproduce
1. In the Admin dashboard, go to Orders page. 
2. Select an order, click "Actions" button, "Print invoices"

## Animated Gif/Screenshot
![Screen Shot 2022-07-22 at 14 14 31](https://user-images.githubusercontent.com/28386648/180437973-21888ce5-8067-4dce-afc1-2caac315f188.png)
-------
![Screen Shot 2022-07-22 at 14 14 07](https://user-images.githubusercontent.com/28386648/180437980-233f40bd-a9ee-4f08-8c35-25085f1a9221.png)

## Severity
bug-s4: it's annoying, but you can use it

**Comment by RachL** [comment]
FYI I've checked transifex and the keys are correctly translated. So the bug is somewhere else :+1:

**Comment by RachL** [comment]
This is fixed now 💪
