### ISSUE TITLE
Convert notes/tracking workflow into Stimulus

### ISSUE THREAD

**Issue by binarygit** [openfoodfoundation/openfoodnetwork#9443]
### What we should change and why (this is tech debt)

As OFN is transitioning to use StimulusJs in the frontend, replace the Jquery code that handles the creation, editing, deletion, and the hover effects on notes/tracking info in orders. 

The Jquery code lives in: `/app/assets/javascripts/admin/spree/base.js` (handles the hover effect when hovering over edit/delete btns), `/app/assets/javascripts/admin/spree/orders/shipments.js.erb` and `/app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb` contains the code for editing/deleting etc.  

### Context

This PR is a follow up to this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/9399

**Comment by RachL** [comment]
hello @binarygit I'm just checking in on this one: is this issue still needed? I see connected PR are either merged or closed.

**Comment by binarygit** [comment]
Yup this should be closed!
