### ISSUE TITLE
[Shopfront] Link to hub with "hide all references" setup is still displayed in producers profiles

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9468]
## Description
Even if a hub selects the "hide all references" settings to make its shopfront completely invisible, the reference is still displayed in its producers profiles.

This impacts hubs that want their shops to remain private, for example hubs that have a pro and public shop, because they don't want customers to see that they apply different prices to their products. 

## Expected Behavior
Reference to the shop must be hidden everywhere (see issue #8896).

## Actual Behaviour
Reference is invisible in Producers tab but remains displayed in the producers profiles (popup of producers details), that can be accessed through:
- the [supplier shop page > Producers tab ](https://coopcircuits.fr/nouvelle/shop#/producers)> click on the supplier shop link > a popup will open, displaying the reference below "SHOP FOR XXX PRODUCTS AT:"
- another hub provided by the supplier > Producers tab > click on the supplier shop link > a popup will open, displaying the reference below "SHOP FOR XXX PRODUCTS AT:"

## Steps to Reproduce
1. Connect as admin or superadmin to a hub 
2. In admin dashboard > Enterprises settings, set "Visible in search?" to "Hide all references"
3. Go to one of the hub producer's shopfront (alternatively, go to another hub provided by the supplier)
4. Click on the "Producers" tab to display the producers list. 
5. Click on the supplier's link, this opens a popup with producers' details
6. You can see a link to the hub (below the label "SHOP FOR XXX PRODUCTS AT:")

## Animated Gif/Screenshot
This is a hub set up to "Hide all references" :
![Screen Shot 2022-07-27 at 14 50 06](https://user-images.githubusercontent.com/28386648/181251653-706ae9a7-20bb-418c-b38d-90a9c48c6358.png)

Connecting to another hub that shares the same supplier, the reference can be found in the "Producers" tab, by clicking on the supplier's link:
![Screen Shot 2022-07-27 at 14 50 46](https://user-images.githubusercontent.com/28386648/181251662-20c7b572-1a28-496e-8741-2c8b537e4f33.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Possible Fix
In the [shop page](https://coopcircuits.fr/testaude/shop#/producers), in Producers list, in the view that opens when clicking on a producer, hide references to shops that chose the "Hide all references" setting.

**Comment by RachL** [comment]
Bite me. I forgot the producer profiles in https://github.com/openfoodfoundation/openfoodnetwork/issues/8896

Good news: we have user who actually visit producer profiles!

**Comment by leopengilley** [comment]
Hey, can I please give this one a go?

**Comment by drummer83** [comment]
Sure @leopengilley! Thanks for working on this!
Looking forward to this contribution! 🤗

**Comment by RachL** [comment]
hey @leopengilley as we don't have news from you I'm unassigning you. Feel free to come back any time if you wish to work again on this!

**Comment by vjain98** [comment]
Hey @RachL 
Can I work on this issue?

**Comment by vsmay98** [comment]
Hi @RachL 
Can I work on this issue?

**Comment by jibees** [comment]
Hi @vsmay98 👋 

Sure, will assign to you. Please feel free to comment here if you're stuck!
