### ISSUE TITLE
Weird decimals when using 12 or 24 as weight in imperial metric system

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9493]
## Description

When adding 12 or 24 as product weight in an imperial system, ends up with a huge number of unnecessary decimals.

## Expected Behavior
Keep just 12 and 24 - no decimals

## Actual Behaviour

![image](https://user-images.githubusercontent.com/6525576/181781290-ac3e3a26-2252-43f0-bdc3-a9696e0bea7a.png)

![image](https://user-images.githubusercontent.com/6525576/181781422-eb3e61ff-109a-4a75-b9e1-c548c70df114.png)

## Steps to Reproduce

1. create or edit a product with weight in oz
2. Enter 12
3. Save
4. :boom: 

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/181781363-cfbef26d-6a4c-4a98-a9d6-0352a91b1dbc.png)

## Workaround

Forcing our own decimals like 12.001? Still pretty weird for shoppers

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v.4.2.7
* Browser name and version: All
* Operating System and version (desktop or mobile): Both

**Comment by jibees** [comment]
Did I already told that I hate when javascript is doing math?

```js
28.35*12
340.20000000000005
```

![6ok6hs](https://user-images.githubusercontent.com/296452/182147388-d66f6f9c-0a72-45e0-8167-09cfda57c8a7.jpg)

**Comment by jibees** [comment]
Ok, WTF

![6ok79l](https://user-images.githubusercontent.com/296452/182148675-e031b354-d09c-4d69-91c2-a643b169c51c.jpg)
