### ISSUE TITLE
Apply save bar to more admin pages

### ISSUE THREAD

**Issue by bingxie** [openfoodfoundation/openfoodnetwork#950]
Apply save bar to more admin pages:

1. create order cycle
2. bulk edit products
3. edit enterprise

**Comment by sstead** [comment]
@oeoeaio can you just check whether or not this is an issue in your eyes.... ![image](https://cloud.githubusercontent.com/assets/10843056/15695582/f0820474-27eb-11e6-95fc-e246c1c1cfec.png)

![image](https://cloud.githubusercontent.com/assets/10843056/15695650/a3b47126-27ec-11e6-9318-119d836e3779.png)

![image](https://cloud.githubusercontent.com/assets/10843056/15695693/2df112a4-27ed-11e6-839f-25cf44f43528.png)

Those are the only three things I picked up on, all else seemed to be working well! Thanks Bing!

**Comment by oeoeaio** [comment]
@bingxie do you think you could have a look at the second issue Sally found. I will I fix the first and third issues.

If you can't find and easy way to do it, don't worry about it. It isn't a big deal.

**Comment by bingxie** [comment]
@oeoeaio I knew the second issue, for this form part of them are not ng-model, so we use the form onchange event to watch the dirty status. But this event is not triggered by the change on the text input until user click another place of the page. So I can not find an easy way to fix it. 
Thanks for fixing the other two issues.

**Comment by bingxie** [comment]
@sstead I just deployed this PR to staging2, if you have time could you please check the issue 1 & 3.

**Comment by sstead** [comment]
Hi @bingxie issues 1 and 3 are fixed :) thanks!

**Comment by daniellemoorhead** [comment]
Hey there @bingxie, where are we at in fixing issue 2?

**Comment by bingxie** [comment]
@daniellemoorhead  I reckon we won't fix it for now.

**Comment by bingxie** [comment]
@daniellemoorhead From my perspective, I can not find a easy way to fix the issue2. If we want to fix this issue, maybe we need to re-implement the form.
