### ISSUE TITLE
Selection of shipping method at shopfront

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#951]

**Comment by myriamboure** [comment]
Can you explain @sstead ? I'm wondering if that won't be a bit messy, and I think that most of the e-commerce website ask that at checkout, so customers are used to it... why do you want this?

**Comment by sstead** [comment]
Hi Myriam, This was an idea from a designer who was with us some time ago. The logic was that currently customers aren't fully aware of what they're getting themselves into until the last page of checkout (regarding shipping and payment methods). Because hubs have non-traditional shipping methods (such as farmgate pickup, and dropoffs at schools) it is important to make the options clear to the customer before they shop, so they aren't surprised later on.

**Comment by lin-d-hop** [comment]
This is relevant, but also not clearly described. Needs inception and prioritisation to be useful. #gitcull
