### ISSUE TITLE
Enterprise description field text formatting

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#953]
Hitting enter makes new paragraph, not just new line. Leads to huge gaps in profiles text... (THIS HAS BEEN FIXED)

![image](https://cloud.githubusercontent.com/assets/10843056/15004145/baa028dc-11f6-11e6-980d-a016781efb25.png)

Headings are all the same: (THIS IS OUTSTANDING)
![image](https://cloud.githubusercontent.com/assets/10843056/20127220/a3ff090c-a690-11e6-9791-de7e01947487.png)

**Comment by myriamboure** [comment]
Another issue here is that the url link doesn't open a new tab, it opens the link in the OFN page so the customer quit the shopfront, which is not what we want.
Desired behavior : url link in entreprise description should open a new tab.

**Comment by myriamboure** [comment]
I put important not as it's so important but so that Claire can pick it up when she gets added to the team. And we had a user who was a bit annoyed by the link thing, so if it's easy and can help Claire jumping into Angular, car be a great start :-)

**Comment by myriamboure** [comment]
@clairezed for you to have a look and see :-)

**Comment by frank-west-iii** [comment]
@myriamboure, the formatting is fixed, but I see that there is another issue here in the comments regarding links opening in new windows in the description.

There are two possible fixes to this problem. One is a global fix for any link generated in a WYSIWYG editor like this one. This will affect product descriptions, shopfront messages, and shopfront closed messages. Those are the ones that I can see in the code currently.

The other is just to apply this fix to the about us description.

Which would you prefer?

**Comment by frank-west-iii** [comment]
@myriamboure, just wondering if the link problem should be spun into a new issue. It is related to an external library and we have to build some custom functionality into it: 

https://github.com/textAngular/textAngular/wiki/Customising-The-Toolbar

**Comment by frank-west-iii** [comment]
Some additional context to the issue:
https://github.com/textAngular/textAngular/issues/224

**Comment by myriamboure** [comment]
Thanks a lot @frank-west-iii ! Yep you are right the comment should be another issue, I'll open it right now and you can assign yourself to it if you want to work on it :-)
