### ISSUE TITLE
Overhaul backend of OFN

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#955]
- Convert top horizontal menu to side menu
- Keep existing categories? With pop out sub-categories
- Put settings at bottom
- Responsiveness

**Comment by myriamboure** [comment]
@sstead arent you afraid that two side menu might be a bit hard to read with the entreprise menu being already vertical? Maybe it's just not visual yet to me ;-)

**Comment by sstead** [comment]
Hi Myriam, this is Rob's idea which he's scoped out on discourse, here's the link - 
http://community.openfoodnetwork.org/t/backend-admin-layout-overhaul/229

**Comment by myriamboure** [comment]
Ok great, looks cool :-)

**Comment by lin-d-hop** [comment]
Two thumbs up from me... like this -> :+1: :+1:

**Comment by lin-d-hop** [comment]
This is a huge feature. This issue serves noone :-)
