### ISSUE TITLE
Removing customer tag fails to save when using search bar for said tag

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#9553]
## Description

We created an integration for an enterprise that allowed new customers to create an account with a specific tag entitling them to a discount. The discount was only intended for first orders, so the tag needed to be removed from customers who had since placed an order. The enterprise had a large customer list so in order to find the required customers, we searched the relevant tag 'CGJUNE22'. This returned the required customers.
However, when clicking the 'x' next to the tag, the customer disappears from the list. The user assumes the tag has been removed successfully and no 'save changes' button is shown. When returning to the customer list though (i.e. by refreshing via loading another enterprise's customer list), the tags persist. This is confusing and frustrating for users.

## Expected Behavior

Searching a customer tag, then deleting that tag via the filtered customer list, should not remove the customer from the list and should allow the user to 'save changes'.

## Actual Behaviour

Searching a customer tag, then deleting that tag removes the customer from the list and does not save the tag change. The customer is still tagged with the tag the user tried to delete.

## Steps to Reproduce

1. Go to customer list of an enterprise with tags (e.g. Deeside Food Hub)
2. Search for the tag (e.g. 'cgjune22')
3. From filtered list of customers, remove the tag from a customer
4. Observe customer disappear from filtered list
5. Change enterprise to a different one/leave page and return to force refresh of customer list
6.  Search the tag again (e.g. 'cgjune22')
7.  Observe that the customer you removed the tag from is still there with the tag present.

## Animated Gif/Screenshot

![Kapture 2022-08-10 at 12 26 49](https://user-images.githubusercontent.com/100226210/183891618-e85a4a94-f662-43c3-99ca-6db83bd94407.gif)

## Workaround

Not searching the tag, instead searching the customer name, or using the browser 'find in page' tool (e.g. CTRL + F/ Command + F) allows tags to be removed and saved. 

## Severity
bug-s4

## Your Environment

* Version used: UK Prod
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by BethanOFN** [comment]
Bumping to S3 as now having problems with users with 1500+ customers for whom the workaround is verrrrryyyyy slow (loading entire customer list and using 'find in page')

**Comment by jibees** [comment]
_Dev note_: the tricky part here is the contradiction between submitting the form for all changed elements and those elements that aren't no more displayed since we removed the tag.
