### ISSUE TITLE
[Admin] Missing translation in error messages 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9559]
## Description
In Products > New Product (/admin/products/new), there is an error message when you forget to fill in a field. Translations are missing for the following field names:
- name
- unit value
- price

I couldn't find the missing translations in Transifex.

## Steps to Reproduce
1. In Products, click "New product"
2. Don't fill in the field and clik "Create"

## Animated Gif/Screenshot
![Screen Shot 2022-08-11 at 22 18 42](https://user-images.githubusercontent.com/28386648/184236515-3030907f-ad36-446e-bcc6-9f2b530ffbcf.png)
![Screen Shot 2022-08-11 at 22 18 13](https://user-images.githubusercontent.com/28386648/184236522-e0d1a488-b59a-4efc-af17-87aed2eed46a.png)

## Severity
bug-s4: it's annoying, but you can use it

**Comment by TimotheDavid** [comment]
I ll do it its my mother language :)

**Comment by audez** [comment]
@TimotheDavid sorry I just edited the issue to add more missing translations in error messages in the Enterprises settings, but I see now that you began to work on it 🤭 should I roll back and create another issue?

**Comment by saunmanoj888** [comment]
hii @audez 
Can you please assign me this issue?
Thanks

**Comment by Laurel16** [comment]
Hi, I am already on it here (
https://github.com/openfoodfoundation/openfoodnetwork/pull/9737),  but feel
free to make suggestions for improvement :)

Le ven. 14 oct. 2022 à 20:50, Manoj Saun ***@***.***> a
écrit :
