### ISSUE TITLE
Instance options to configure business model

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#956]
Some work has been done towards this...
- https://github.com/openfoodfoundation/openfoodnetwork/issues/526
- https://github.com/openfoodfoundation/openfoodnetwork/pull/911

Still seemingly outstanding:
- enterprise package text is still hard coded- make editable
- deactivate/register

**Comment by lin-d-hop** [comment]
Multiple iterations have shown that this is better done outside of OFN as business models change so quickly.
#gitcull
