### ISSUE TITLE
[Admin][Orders page] Add a dedicated email for pickup orders when switching shipment state to "Shipped"

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9561]
## Context
Some hub managers that use the "Pick up" shipping method want to be able to differentiate an order that is ready from an order that has been distributed. For this, they use the "Ship" button (road icon) in the [Orders page](https://coopcircuits.fr/admin/orders), which switches the Shipment state from "Ready" to "Shipped". But clicking on this button automatically send the customer an email, and this email is designed only for delivery orders. It indicates that the order has been shipped. It creates confusion because in the case of pickup orders, customers have already received their order. Furthermore, the email doesn't include information about the order completion date or order number, and can be received way after the pickup date. Hub managers and customers are thus worried to receive an order confirmation without having placed an order.

![2022-07-26 18 29 54](https://user-images.githubusercontent.com/28386648/181060759-1084d46b-3c4c-4cfe-88da-4b0bb84ee2b5.gif)

## Description
**- As a:** enterprise user or super admin
**- On page:** `/admin/orders`
**- I want to be able to do:** When shipping an order, if the shipping method category of the order is "pick up" then I should receive a different email content than when the shipping method category is "delivery".

![Screen Shot 2022-07-26 at 13 38 35](https://user-images.githubusercontent.com/28386648/181060926-567765e5-d178-431f-949d-77abd118f2cd.png)

FYI this is the shipped email version: 

![image](https://user-images.githubusercontent.com/6525576/184311982-2c5df42b-2585-4ba9-8268-8816d1733ea6.png)

New title should become (release farm is the name of the hub): 

![image](https://user-images.githubusercontent.com/6525576/184312504-8cbf7171-74a3-4f14-8311-5acd47126136.png)

Email body default (but can be changed by instance managers in translation):

Dear customer,

Your order from release farm has been picked-up.

**Order summary**
Melonn 1000 sachets
Thank you for your business

## Acceptance Criteria & Tests

1. Log in as enterprise
2. Ship an order with pick up shipping category, check the email content is correct
3. Ship an order with delivery category, check the email content is correct
4. Repeat on different payment method (cash & credti card)
5. Repeat with super admin

**Comment by audez** [comment]
@RachL I've reworded the content of the email in transifex too, so we don't have more requests while the problem is resolved :)

**Comment by binarygit** [comment]
Looks like there are no real `pickup` or `delivery` categories. We're using those radio inputs to just toggle the `require_ship_address` to `true` or `false`. And I checked my `ShippingCategory` model but there's only this in there.

I think that there's no real `pickup` or `delivery` shipping categories. Like 
```ruby
shipping_method.category 
=> 'pickup'
```


There are models like `ShippingCategory` and `ShippingMethodCategory` but they aren't straight forward as they sound. It seems like a `ShippingMethod` has_many :shipping_method_categories and then

![category](https://user-images.githubusercontent.com/87677429/190884403-a7b29c54-28fe-4d00-aa24-e1dabf243ea7.png)
The code for this is: 

```haml
  .row
    .alpha.four.columns
      -# The 'Category' label here is just a logical descriptor for the data we are trying to collect for 'requires_ship_address'
      -# and does not relate to shipping categories in any way.
      = f.label :require_ship_address, t(:category)
    .three.columns
      = f.radio_button :require_ship_address, true
      &nbsp;
      = f.label :delivery, t(:delivery)
    .omega.six.columns
      = f.radio_button :require_ship_address, false
      &nbsp;
      = f.label :pick_up, t(:pick_up)
```

Looks like there's no real `pickup` or `delivery` category. We're just using those radio buttons to toggle the `require_ship_address` attribute to `true` or `false`. 
And I'm having a hard time understanding what the `ShippingMethodCategory` or the `ShippingCategory` models are doing. As I see it, the `ShippingMethodCategory` 
![shippingMethod](https://user-images.githubusercontent.com/87677429/190885552-e4a69eb8-c3d2-4438-ba86-984b71b0ab88.png)

**Comment by binarygit** [comment]
the

**Comment by jibees** [comment]
@binarygit 
If I understood correctly, I think those two lines will helps you a lot: 

https://github.com/openfoodfoundation/openfoodnetwork/blob/887f886110a90b294ee5e0acb98cb65b1c2f4bd8/app/models/spree/shipping_method.rb#L98-L99

**Comment by binarygit** [comment]
That clears everything up. Thanks! :smile:

**Comment by drummer83** [comment]
#9682 was created to solve this issue. Looking at it in detail I understand that #9682 is great to have, but it's not really solving the original need. If this is true, @audez or @tschumilas, I would propose to open a wishlist item to either
- have an option to disable the email notification OR
- not set shipment state to 'ready' automatically as soon as the order is complete and paid, but instead do this manually OR
- add an additional shipment state (e.g. 'packed') which is activated manually and is located between 'ready' and 'shipped' OR
- you may have better ideas...

**Comment by audez** [comment]
Yes i agree @drummer83 i don't think it's really solving the need neither, and clients are still confused even with 9682 and the new mail.. 😿

I like both options 1 & 2 - and the fact to manually choose the shipment state is a request we've had from users. Option 3 i'm not sure because for pickups generally when the order is "ready" that means it's "packed", and i'm afraid they still would go to the last step "shipped" when it's delivered, so it will send the mail anyway.

So actually I'd like to create several wishlists:
- Have a different wording for shipment status "Shipped" if it's a pickup order --> for ex "Delivered" instead of "Shipped"
- Have an option to disable the email notification for pickup orders when shipment state is "Delivered"
- Adding order number and date in the mails sent to clients after pickup or delivery 
- Uncorrelate the shipment and payment status to allow users to manually set the shipment state 
- And this one is a request from user: Add a shipment status between "pending" and "ready", because they would like to differentiate between an order that they've considered and need to prepare from an order they didn't check yet. So there would be 4 status: "pending", "to prepare", "ready", "shipped"/"delivered"

What do y'all think?

**Comment by audez** [comment]
- Have a different wording for shipment status "Shipped" if it's a pickup order --> for ex "Delivered" instead of "Shipped"
this is already the topic of  #287, i added a comment
