### ISSUE TITLE
[Admin] [Products] Changing unit value won't work for numbers with a comma separator

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9569]
## Description
In the admin dashboard, in "Products" tab, if you update a variant unit value using a comma separator for decimals (for ex "2,5"), it won't work. Whereas it works well when editing the unit value from the product's details.

## Expected Behavior
You should be able to update the variant unit value from the product's list (admin/products). It is already possible in the products details edition (admin/products/carottes-88/edit).

## Actual Behaviour
When you click "Save" after having changed the unit value of the variant, it's the old unit value that will appear.

## Steps to Reproduce
1. Go to Products tab 
2. On a variant line, type a number with comma separator in the "unit" field
3. Click "Save changes"

## Animated Gif/Screenshot
![virgule2](https://user-images.githubusercontent.com/28386648/184648290-d7e76730-bd72-41f8-8ceb-6bccf19c87df.gif)

## Workaround
Click the "edit" icon on the product and change the unit value in the "variants" tab. 

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by saunmanoj888** [comment]
hii @sigmundpetersen 
Can I work on this issue?

**Comment by sigmundpetersen** [comment]
Yeah sure @saunmanoj888 go ahead 👍 
Thanks!

**Comment by saunmanoj888** [comment]
Update:
Still figuring out the issue, looks like something is wrong with the implementation in the JS. Need to fix changes in the file `app/assets/javascripts/admin/bulk_product_update.js.coffee`
 I will update here once I resolve the issue.
