### ISSUE TITLE
Misplaced "Developer Settings" on /account# page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9579]
## Description

Follow-up from #9414.

#9414 introduced the possibility for customers to generate their own API key in a "Developer Settings" which now appears in customers `/account#` page. 

This tab appears misplaced, even if not limited by the screen width.

## Expected Behavior

This tab appears next "Account Settings", if not limited by the screen width.

## Actual Behaviour

This tab appears below the "Orders" tab, even if not limited by the screen width.

## Steps to Reproduce

1. As a superadmin, toggle the Checkbox: "Show API key generation view", under `/users/<user_id>/edit`
2. As a customer, visit the `/account#/` section
3. Notice the misplaced "Developer Settings" tab

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/185239782-b10b31a6-1902-4461-ba10-b0e4ebb3311b.png)

## Workaround

None needed, all works - just not the best UI

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: introduced in #9414
* Browser name and version: Firefox 103
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by saunmanoj888** [comment]
hii @filipefurtad0 
Can I work on this issue?

**Comment by sigmundpetersen** [comment]
Sure go ahead 👍 I'll assign you.
Thanks
