### ISSUE TITLE
[Stripe/active_merchant] Checkout error prevents order completion 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9580]
## Description

Probably introduced by #9507 and/or #9456.

Since the last release we're getting errors on _some_ instances:
`lib/active_merchant/billing/gateways/stripe_payment_intents_decorator.rb:60`

**UK**
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/62fb43b59ffd5b0008478b23?filters[event.since]=all&filters[search][]=undefined&filters[search][]=method&filters[search][]=%60first%27&filters[search][]=for&filters[search][]=nil%3ANilClass

**AU**
https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62fc74ff173ec3000888a0ec?filters[event.since]=30d&filters[app.release_stage]=production

**US**
https://app.bugsnag.com/yaycode/openfoodnetwork-usa/errors/62fbeb745f03710008c2983d?filters[event.since]=30d&filters[error.status]=open

This is preventing checkout for some customers. The "Checkout failed" flash message is displayed.

## Expected Behavior

Checkout succeeds and the credit card is saved in the profile.

## Actual Behaviour

Error at checkout prevents completing the order.

## Steps to Reproduce

Saving a new card during checkout:

* Log in as user.
* Add items to cart.
* Check out with Stripe and tick "Remember this card?".
* Submit with "Place order now".

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/185578505-29a03500-e966-491d-b636-4697a2920231.png)

## Workaround

- Untick  "Remember this card?" or
- use another payment method other than Stripe.

## Your Environment

* Version used: v4.2.9
* Browser name and version: -
* Operating System and version (desktop or mobile): -

## Possible Fix

~~To be checked: The fact that it is so far not observed in FR _could_ indicate that the bug affects only cards not requiring SCA?~~

**Comment by mkllnk** [comment]
>  The fact that it is so far not observed in FR could indicate that the bug affects only cards not requiring SCA?

No, it confirms that the release introduced the bug because I didn't deploy to FR.

**Comment by mkllnk** [comment]
This issue has been linked to an error in Bugsnag
[**NoMethodError** in **checkout#update**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62fc74ff173ec3000888a0ec?event_id=6302d24b00965f22db780000&i=gh&m=li)

**Comment by mkllnk** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**NoMethodError** in **checkout#update**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62fc74ff173ec3000888a0ec?event_id=63031584009641a76b4e0000&i=gh&m=fx)

**Comment by mkllnk** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v4.2.10

Comment added in Bugsnag by Maikel
[**NoMethodError** in **checkout#update**](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/62fc74ff173ec3000888a0ec?event_id=63031584009641a76b4e0000&i=gh&m=cm)

**Comment by filipefurtad0** [comment]
Looking at logs to see what actually blows up:

```
I, [2022-09-06 15:24:12#27524]  INFO -- : source=rack-timeout id=556ac606-e827-4723-b789-ad9bbef9ace0 wait=5ms timeout=120000ms state=ready
I, [2022-09-06 15:24:12#27524]  INFO -- : Started PUT "/checkout.json" for 148.69.190.53 at 2022-09-06 15:24:12 +0000
I, [2022-09-06 15:24:12#27524]  INFO -- : Processing by CheckoutController#update as JSON
I, [2022-09-06 15:24:12#27524]  INFO -- :   Parameters: {"order"=>{"default_bill_address"=>false, "default_ship_address"=>false, "email"=>"filipefurtado+treec@gmail.com", "shipping_method_id"=>902, "payments_attributes"=>[{"payment_method_id"=>"751", "source_attributes"=>{"gateway_payment_profile_id"=>"pm_1Lf3dHFBE7f7kItLsqD3Cukb", "cc_type"=>"visa", "last_digits"=>"3184", "month"=>2, "year"=>2034, "first_name"=>"Frank", "last_name"=>"Four Fingers", "save_requested_by_customer"=>true}}], "bill_address_attributes"=>{"zipcode"=>"987654", "city"=>"city", "state_name"=>"MB", "state_id"=>57, "phone"=>"987651", "firstname"=>"Frank", "lastname"=>"Four Fingers", "address1"=>"rua da gloria, 28", "address2"=>"", "country_id"=>204, "country_name"=>"Canada"}, "ship_address_attributes"=>{"zipcode"=>"987654", "city"=>"city", "state_name"=>"MB", "state_id"=>57, "phone"=>"987651", "firstname"=>"Frank", "lastname"=>"Four Fingers", "address1"=>"rua da gloria, 28", "address2"=>"", "country_id"=>204, "country_name"=>"Canada"}, "terms_and_conditions_accepted"=>true}, "checkout"=>{"order"=>{"default_bill_address"=>false, "default_ship_address"=>false, "email"=>"filipefurtado+treec@gmail.com", "shipping_method_id"=>902, "payments_attributes"=>[{"payment_method_id"=>"751", "source_attributes"=>{"gateway_payment_profile_id"=>"pm_1Lf3dHFBE7f7kItLsqD3Cukb", "cc_type"=>"visa", "last_digits"=>"3184", "month"=>2, "year"=>2034, "first_name"=>"Frank", "last_name"=>"Four Fingers", "save_requested_by_customer"=>true}}], "bill_address_attributes"=>{"zipcode"=>"987654", "city"=>"city", "state_name"=>"MB", "state_id"=>57, "phone"=>"987651", "firstname"=>"Frank", "lastname"=>"Four Fingers", "address1"=>"rua da gloria, 28", "address2"=>"", "country_id"=>204, "country_name"=>"Canada"}, "ship_address_attributes"=>{"zipcode"=>"987654", "city"=>"city", "state_name"=>"MB", "state_id"=>57, "phone"=>"987651", "firstname"=>"Frank", "lastname"=>"Four Fingers", "address1"=>"rua da gloria, 28", "address2"=>"", "country_id"=>204, "country_name"=>"Canada"}, "terms_and_conditions_accepted"=>true}}}
W, [2022-09-06 15:24:13#27524]  WARN -- [Bugsnag]: Adding metadata/severity using a hash is no longer supported, please use block syntax instead
I, [2022-09-06 15:24:13#27524]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of NoMethodError
I, [2022-09-06 15:24:13#27524]  INFO -- : Completed 400 Bad Request in 1051ms (Views: 0.2ms | ActiveRecord: 115.9ms | Allocations: 137973)
I, [2022-09-06 15:24:13#27524]  INFO -- : source=rack-timeout id=556ac606-e827-4723-b789-ad9bbef9ace0 wait=5ms timeout=120000ms service=1087ms state=completed
```
