### ISSUE TITLE
(silent?) Checkout error 404 when order cycle closes during checkout

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9583]
## Description

If the OC closes during checkout the user will see an generic error (see Animated Gif/Screenshot section).

I believe we're not getting notified from these errors, as 404s don't trigger the Bugsnag notification flow.

We do get a warning though, each time the OC closes on checkout:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61f91350e0348e00089f160f?filters[event.since]=30d&filters[error.status]=open

## Expected Behavior

If the OC closes during checkout, then:
The customer should be redirected to the (closed) shopfront and the appropriate message should be displayed:

![image](https://user-images.githubusercontent.com/49817236/185592867-43b57f87-ecd4-44b4-8bae-0b9a170b0c89.png)

## Actual Behaviour

If the OC closes during checkout, then:
The customer is not getting redirected to the shopfront page but rather seeing generic flash messages.

## Steps to Reproduce

As a customer
1. Visit the shopfront, add some items to the cart and proceed to checkout

As admin
2. Close the order cycle

As the customer
3. Click Checkout
4. See the generic error

## Animated Gif/Screenshot

**Cash**
![image](https://user-images.githubusercontent.com/49817236/185592204-0e1fc4a0-98a4-4da2-a1c2-bd24ae1d54b9.png)

**Stripe**
![image](https://user-images.githubusercontent.com/49817236/185593656-bfa47e5a-f410-4f86-9931-4389edcc238e.png)

## Workaround

Navigate back to the cart and or shopfront page.

## Severity

~~I think this would be an S3; surely a regression.~~
Upgrading to S2 - likely to impact customer support. Feel free to downgrade if disagreed.

## Your Environment

* Version used: observed on v4.2.9 and before (checked for v4.2.8). 
* Browser name and version: Firefox 103
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by RachL** [comment]
So this is a message that is not precise enough. I'm downgrading as s3 as we have a very small team currently...

**Comment by sigmundpetersen** [comment]
Is this the same as #8898 ? Can we consolidate the info and keep only one?
@filipefurtad0

**Comment by filipefurtad0** [comment]
Thank you @sigmundpetersen for the heads up - it seems it has been here for a while - removed the regression label, and closed #8898.

Perhaps a clarification is needed on the expected behavior. Looking at [this related discussion](https://github.com/openfoodfoundation/openfoodnetwork/issues/5369#issuecomment-624045267), I'd think that the expected behavior is:
- if shop has no order cycles open -> redirect to homepage
- if shop has 1 order cycle open -> redirect /shop; automatically select that order cycle
- if shop has 2 order cycles open -> redirect /shop; do not select an order cycle
- in all the above cases, display the correct error message (from `en.yml` -> `order_cycle_closed`)
- 404 should not occur

Does this sound right @RachL ?
