### ISSUE TITLE
[Admin][Permissions] Granting permission to a shop displays it in "Producers" list as if it was a supplier 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9589]
## Description
When Shop A grants permission to Shop B to sell its product, these two things happen:
👍- Shop A will appear in Shop B shopfront page, in the Producers list -> this is OK 
👎- Shop B will appear in Shop A shopfront page, in the Producers list -> this is not OK , as Shop B is a **distributor** for Shop A, and not a **supplier**. 

This has been raised by a shop manager who didn't understand why many producers that were not supplying him products appeared in his shop.

## Expected Behavior
A shop should appear in a shop's "Producers" list only if it supplies this shop, which means only if it has granted the permission to this shop to sell its products.

## Actual Behaviour
When granting a permission from Shop A to Shop B, Shop B appears in Shop A producers list (boutique-1/shop#/producers).
(It only applies when Shop B is a producer).

## Steps to Reproduce
1. Connect to a producer's shop (shop A)
2. Grant permission "add to order cycle" from this producer to another **producer** shop or hub or profile (shop B)
3. Go to shop A url and click on the "Producers" tab (boutique-1/shop#/producers)
4. See that shop B appears 

## Animated Gif/Screenshot
![Screen Shot 2022-08-22 at 20 58 36](https://user-images.githubusercontent.com/28386648/186001487-3e5a0b1c-3a11-479a-a73d-f75dcb6dab8b.png)
![Screen Shot 2022-08-22 at 21 02 33](https://user-images.githubusercontent.com/28386648/186001500-74f2e6d0-4155-47cd-9d1b-63126181b566.png)
![Screen Shot 2022-08-22 at 21 08 11](https://user-images.githubusercontent.com/28386648/186001506-f7f62afb-9286-4ae1-b67a-29236052f966.png)

## Workaround
Remove permission from Shop A to Shop B (but then Shop B won't be able to sell products from Shop A).

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by ashwini-seshadri** [comment]
Hi, I would like to work on this issue!

**Comment by sigmundpetersen** [comment]
Yes, go ahead @ashwini-seshadri 🙂 Thank you 🙏

**Comment by ashwini-seshadri** [comment]
Hi, just an fyi, I am still working on this issue!

**Comment by drummer83** [comment]
Don't hesitate to reach out if you get stuck!
@ashwini-seshadri

**Comment by ashwini-seshadri** [comment]
Hi, @drummer83 Thank you, I was a bit sick, but hopefully, I will be able to finish it and submit a PR soon!
Thank you!

**Comment by ashwini-seshadri** [comment]
Hi, I have a question, what are all the permissions that need to be enabled for a producer to be a producer on an organisation.
Eg: "to add to order cycle". "to manage products" etc

**Comment by ashwini-seshadri** [comment]
I'm going to change the query  to this to help me remove children in the enterprise relationship
from this :
```ruby
scope :relatives_of_one_union_others, lambda { |one, others|
    where("
      enterprises.id IN
        (SELECT child_id FROM enterprise_relationships WHERE enterprise_relationships.parent_id=?)
      OR enterprises.id IN
        (SELECT parent_id FROM enterprise_relationships WHERE enterprise_relationships.child_id=?)
      OR enterprises.id IN
        (?)
    ", one, one, others)
  }
```
to this:
```ruby
scope :relatives_of_one_union_others, lambda { |one, _|
    where("enterprises.id IN (SELECT parent_id FROM enterprise_relationships WHERE enterprise_relationships.child_id=?)", one)
  }
```

This seems to fix the issue. I will write tests and create a PR.

**Comment by sigmundpetersen** [comment]
If you haven't already, you can read more about permissions [here ](https://guide.openfoodnetwork.org/basic-features/enterprise-profile/enterprise-to-enterprise-permissions-e2es#enterprise-permissions) 👍

**Comment by ashwini-seshadri** [comment]
@sigmundpetersen Thanks!
What about the sql query? Do you think it is ok top solve this with the above mentioned approach?

**Comment by jibees** [comment]
hey @ashwini-seshadri 👋 

I think the approach is to create a PR with specs, and then pass the CI specs, and code review. It'll be cleaner for everyone.

Thanks! 🙏

**Comment by ashwini-seshadri** [comment]
Hi @jibees 
Thank you for your response. It helped me in finding another approach to solve this issue. I have created a PR, but it is failing two tests that I don't understand very well. Can you advise me on how to handle it?

**Comment by jibees** [comment]
@ashwini-seshadri 
I can see that PR #9768 is in code review, so i will review it and comment there
