### ISSUE TITLE
Minimum order spend

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#959]
## What is the problem we are solving
To be efficient, shops often need their orders to be of a minimum value at least. Orders received below this value may actually lose the shop money, or reduce their margin. 
Currently there's no way for shops to set a 'minimum spend' in their shop. In the absence of such functionality shops either need to absorb the inefficiency of low value orders, or have an awkward conversation with a customer - which is not great for customer relationships

## Success factors = expected outcome 
Shops can avoid receiving orders that are below their minimum threshold. Customers are aware of this requirement and aren't surprised.

## Metric
- Can shops automatically prevent orders below a given minimum value? 

## Link to the "Product Development - Backlog" item in Discourse
https://community.openfoodnetwork.org/t/shops-can-require-a-minimum-spend-before-customers-can-checkout/1350

## First feature candidate to be implemented
This needs further discussion. One suggestion here:
- Shops can set an optional 'minimum spend' value in their settings. This minimum spend requirement is communicated clearly to customers in the shopfront. If the customer tries to checkout with a cart below this value they're reminded of the minimum value requirement and redirected to the shopfront.

**Comment by sineadfenton** [comment]
Just to add, we've had two further requests from the UK for this

**Comment by enricostano** [comment]
Related to this https://groups.google.com/forum/?hl=en#!topic/spree-user/xyzwVK-6zgo

But we need to look for more recent info about it, maybe asking again in the Spree community.

**Comment by daniellemoorhead** [comment]
>Would it be worth opening this up for discussion on the International discourse platform to gage interest and bring it back here?

I think that's a great idea @sineadfenton - have a go at talking through how you would see it working, then others can join in the conversation.

**Comment by sigmundpetersen** [comment]
Quote @daniellemoorhead: "I moved this back to "all the things" because we don't put epics into the zenhub delivery pipe. They're tracked on the feature backlog here: https://github.com/openfoodfoundation/openfoodnetwork/projects/19" 😄

**Comment by myriamboure** [comment]
Sorry @sigmundpetersen but I don't think this epic should be in feature backlog as there is it is not ready to put in the pipe, for that we need it to be properly incepted and a story map needs to be there, so with actionable issues attached to it. So until then I would leave it in all the things. Also, we did prioritize but a year ago, so maybe things will be reshuffled a bit with new voting process... let's see.

**Comment by berteh** [comment]
as discussed with Kirsten and Theresa I think the existing "price sack" commission mechanism already provides a viable solution to this need: https://community.openfoodnetwork.org/t/shops-can-require-a-minimum-spend-before-customers-can-checkout/1350/5

**Comment by lin-d-hop** [comment]
I'm closing this epic as we are now almost all solving this with the price sack calculator
