### ISSUE TITLE
FR Prod instance down

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9596]
## Description
Website completely down.
Then Getting the snail when trying to access any reports at https://coopcircuits.fr/admin/reports

**Comment by audez** [comment]
this is OK now. The bug lasted 1h-2h, was reported at 9:55 this morning
- snail on reports  
- importing orders to the integrated cash software (Pastèque) failed
- Every page was very slow to load (It was already slow yesterday)

It looks like it might be linked to our previous memory issue..

**Comment by audez** [comment]
ongoing work:
https://github.com/openfoodfoundation/openfoodnetwork/issues/9398
https://github.com/openfoodfoundation/openfoodnetwork/pull/9413

**Comment by RachL** [comment]
@audez the snail did not occur only on reports, right, on all pages? 

As on kuma we can see it's a server timeout:

![image](https://user-images.githubusercontent.com/6525576/186886072-8f0cc166-e809-4a32-ab2b-d44d16af8035.png)

Note we had the same downtime yesterday.

Datadog confirms the first spike occured at 9:49 with some request already starting at 9:39 : 

![image](https://user-images.githubusercontent.com/6525576/186885340-c174eb37-e37e-49e0-b24a-201297fa3c6d.png)

I haven't had time yet to see which request started the chain reaction. Perhaps if someone who has ssh access can access the logs, that would be quicker.

I'll be back on Monday, but if we need to put more metal to it in the meantime, our credit card is stored in our host account. You can reach me on telegram or signal if there is a 2FA problem.

**Comment by audez** [comment]
thanks! for me the snail occured only when trying to access a report. I tested around 11:30.  I was able to access orders (but it was veeery slow) and all pages were slow. Yesterday everything was slow too. I think I loaded some reports around 12:30 and got no snail though

**Comment by audez** [comment]
down again around 15:15

**Comment by RachL** [comment]
@audez did you loggedin as super admin or enterprise user?

**Comment by audez** [comment]
in a window as super admin and in another enterprise user

**Comment by mkllnk** [comment]
> in a window as super admin and in another enterprise user

If it's in the same browser then you are logged in with the same account.

**Comment by audez** [comment]
@mkllnk yea thanks :P it was same browser but one private window and one normal so I could test both

**Comment by mkllnk** [comment]
Probably best to plan downtime between 2am and 7am French time. That should cover my workday very well.

**Comment by RachL** [comment]
Closing for now. Let's see if we need to reopen after https://github.com/openfoodfoundation/ofn-install/issues/825
