### ISSUE TITLE
Customer accounts - able to add credit, and update details

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#960]
Desired changes:

As a customer, I can pay credit into my accounts to cover future orders. Needs a separate accounts for each hub. 

As a customer I can update my details (name, address, etc)

**Comment by lin-d-hop** [comment]
This is being explored in Discourse:
https://community.openfoodnetwork.org/t/enable-customers-to-pay-partially-or-fully-with-their-credits/1211
