### ISSUE TITLE
[Admin][Order cycle] Same enterprise appear several times in the fees dropdown list

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9603]
## Description
When choosing to apply fees in steps 3 and 4 of a hub's order cycle, the same enterprise can appear several time in the dropdown list.

## Expected behavior
One enterprise should appear only one time.

## Steps to Reproduce
1. Connect to an account that has a producer-hub enterprise (with at least one available product so it can be added as a supplier): for ex Enterprise 3949 and 4001
2. Create or edit an order cycle
3. At step 2, choose the hub as the supplier, then click "Add fee"
4. See that the hub appears several times

## Animated Gif/Screenshot
![Screen Shot 2022-08-29 at 19 26 54](https://user-images.githubusercontent.com/28386648/187261975-b51c1076-4166-43b8-96a6-8366de02e9b4.png)

![Screen Shot 2022-09-19 at 11 32 43](https://user-images.githubusercontent.com/28386648/190989478-42a98839-41e7-4d5d-9765-5de861122e18.png)

## Workaround
Choose whether of the proposed options.

## Severity
bug-s4: it's annoying, but you can use it
0

**Comment by saunmanoj888** [comment]
hii @audez @sigmundpetersen 
Can I work on this issue?
Thanks

**Comment by sigmundpetersen** [comment]
Yes sure, go ahead @saunmanoj888 !
Thank you 🙏

**Comment by maniSHarma7575** [comment]
Hi @sigmundpetersen  can I take up this issue if no one else is working on it? 😊

cc: @saunmanoj888

**Comment by sigmundpetersen** [comment]
I have assigned you @maniSHarma7575 , thank you 🎉

**Comment by maniSHarma7575** [comment]
@sigmundpetersen Added PR: #9752
