### ISSUE TITLE
Expand enterprise types (e.g. wholesaler, maker, buying group?)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#961]

**Comment by myriamboure** [comment]
Yes, would be great :-) And allow the relevant ones to create products (ex: basket of vegetables) Then the notion of "hub" should be clarify (ex: if you use the online shop, you are a hub, a distribution point)

**Comment by lin-d-hop** [comment]
Needs more detail to be useful. #gitcull
