### ISSUE TITLE
[Checkout] Fix spacing between texts in shipping and payment info

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9612]
## Description
On checkout page, when shipping info or payment info is on two lines, there is a spacing issue, making it difficult to read.

## Expected Behavior
There should be a space between two different shipping or payment methods.
There should be no space  between two lines of the same shipping or payment methods.

## Steps to Reproduce
1. Connect to a shop which has payment or shipping methods info on at least two lines

## Animated Gif/Screenshot
![Screen Shot 2022-08-31 at 14 28 16](https://user-images.githubusercontent.com/28386648/187679162-c5b1d96e-7057-4f2c-af00-b575ccea2c4d.png)
![Screen Shot 2022-08-31 at 14 28 21](https://user-images.githubusercontent.com/28386648/187679154-83b8c7b3-7ee5-4c25-bd12-2a3d15f0aa77.png)

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

**Comment by RachL** [comment]
@audez FYI the current checkout page is not maintained anymore. The new checkout page (currently in beta testing) has fixed this problem. Let me know if you want me to activate the page a user of yours.

Closing here.
