### ISSUE TITLE
Enterprises/Primary details: Delay when changing the 'sells' option to display the permalink settings

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9637]
## Description

Follow up of #9594.
There is a delay of > 1 second when changing the 'sells' option until the display is updated to show the permalink settings.

## Expected Behavior

Permalink settings should be shown immediately after selecting 'sells == own' or 'sells == any'.

## Actual Behaviour

There is a delay of > 1 second until the display is updated.

## Steps to Reproduce

1. Go to /admin/enterprises/'name'/edit
2. Change the 'sells' option beetween 'own' and 'none'
3. Observe the display and how quickly the permalink settings are shown

## Animated Gif/Screenshot

Left before #9594, right after #9594:
![Peek 2022-09-06 00-15](https://user-images.githubusercontent.com/1790176/188518727-608e3ff1-2a0e-480c-8492-e4322836e6d0.gif)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [02e3184](https://github.com/openfoodfoundation/openfoodnetwork/pull/9594/commits/02e3184945f2e04a0108feeba09989ade47f9db6)
* Browser name and version: Firefox 104
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by binarygit** [comment]
Is this in production?

**Comment by RachL** [comment]
Perhaps here the quick fix is to introduce a spinner.

**Comment by drummer83** [comment]
I observed this on staging servers.

**Comment by binarygit** [comment]
I like the idea of having a spinner there (for now). Will send a PR for it, should I have the spinner right next to the `Any` label? It just shows up until the DOM updates then goes away.
![spinner](https://user-images.githubusercontent.com/87677429/190997544-c0ebf08c-54df-43a8-83db-c54c3cd38c9e.png)

Meanwhile I can look into what's causing the delay. How do I go to the staging server?

**Comment by drummer83** [comment]
@filipefurtad0 wrote a great post about this: https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1662455775158809?thread_ts=1662048305.835949&cid=C02TZ6X00

**Comment by RachL** [comment]
I think we should only refer to our wiki and if our wiki sucks, improve our wiki :D Here is the wiki : https://github.com/openfoodfoundation/openfoodnetwork/wiki/Testing-process
