### ISSUE TITLE
Build failing in master

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#9643]
### What we should change and why (this is tech debt)
Seems like the build failed ~since merging https://github.com/openfoodfoundation/openfoodnetwork/pull/9631~

https://github.com/openfoodfoundation/openfoodnetwork/runs/8240457288

```
spec/system/consumer/shops_spec.rb:28

Failure/Error: expect(page).to have_content "Sorry, no results found for xyzzy"
       expected to find text "Sorry, no results found for xyzzy" in "SHOPS MAP PRODUCERS GROUPS ABOUT Inglés Login Cart 0 Close Your cart is empty Shopping, transformed. Food grows in cycles, farmers harvest in cycles, and we order food in cycles. If you find an order cycle closed, check back soon. Shop in your local area Filter by Did you mean? xyzzy... Enterprise 452 Herndon Vic Orders open Show closed shops Show all on the map Interested in getting on the Open Food Network? Register here Secure and trusted. Open Food Network uses SSL encryption (2048 bit RSA) everywhere to keep your shopping and payment information private. Our servers do not store your credit card details and payments are processed by PCI-compliant services. Keep in touch Email us Newsletter sign-up News Calendar Navigate Shops Map Producers Groups About Join us Create a listing, shop or group directory on the Open Food Network. Tell me more! Read our Terms of service | Find us on GitHub Open Food Network is a free and open source software platform. Our content is licensed with CC BY-SA 3.0 and our code with AGPL 3. We take good care of your data. See our cookies policy". (However, it was found 2 times including non-visible text.)
```

### Context
This came up in PR #9536

### Impact and timeline
Build failed.

**Comment by jibees** [comment]
This also fails for 95839f88f2, ie. `4.2.11`

**Comment by jibees** [comment]
Seems super strange, this spec should not have been green... 
We use the wording `Did you mean?` 
<img width="497" alt="Capture d’écran 2022-09-08 à 09 46 13" src="https://user-images.githubusercontent.com/296452/189065275-3d5262c9-5ec7-4c66-9c58-bd0ffc77f27a.png">
and not `Sorry, no results found for` which is used when searching products inside a shop.

**Comment by jibees** [comment]
I'm wondering if this spec was not running in CI, and then, for some reasons, has started to run. 
Because when I see the spec files, or the view file, I don't spot any changes recently.

Then, i'll correct the spec, until someone has a better idea.

**Comment by jibees** [comment]
Or maybe this is some modification around `nameMatchesFiltered`, ... because I don't see any reason on why we show here a list of hubs:  
![failures_r_spec_example_groups_shops_searches_by_url_993](https://user-images.githubusercontent.com/296452/189074851-dd2ab66a-3501-461a-bc21-f7509a4efdd0.png)

instead of the wording `Sorry, no results found for xyzzy. Try another search?`

**Comment by sigmundpetersen** [comment]
We have #5467 which represents the bug that search results appear when they shouldn't. No clue if this is why the spec is failing or why it started failing now.

But maybe a good time to fix that bug 😄

**Comment by jibees** [comment]
I can spot a difference between search for `query` via the input and entering the enter key (which returns some results) and visit URL via `/shops#/?query=query` which did not return any result.

![2022-09-08 10 41 49](https://user-images.githubusercontent.com/296452/189077350-415de133-e7e8-4630-b65e-8c5d8f0c933c.gif)


The spec used the visit one, and should _work_ ... as it should not return any result.

**Comment by jibees** [comment]
Found the difference between the two cases ('Case1: when loading the page via URL', 'Case2: when searching via enter key'). 
 - `Case1`: `enterprise.distance` has `undefined` value, and `undefined / 1000 <= 50` is false, then enterprise is hidden
 - `Case2`: `enterprise.distance` has `null` value, and `null / 1000 <= 500` is true, then enterprise is shown

**Comment by filipefurtad0** [comment]
Awesome :muscle:
Should we set this example as pending, till this fix is through the pipe?

**Comment by jibees** [comment]
Did not found anything relevant, I'll then make a pause on this one.
I don't think it blocks the release, since I've tested (locally) this for `4.2.11` and `4.2.10` and it fails.
