### ISSUE TITLE
[Reports] Packing by customer: WEIGHT is always 0.0

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9646]
## Description

Follow up #9575.
The weight column is always showing 0.0 as values even if weight is > 0.

## Expected Behavior

The weight column should show the actual weight.

## Actual Behaviour

The weight column is always showing 0.0 as values even if weight is > 0.

## Steps to Reproduce

1. Visit variants edit page of any variant and fill in the WEIGHT field.
2. Go to an order cycle and place an order with the variant you edited.
3. Generate packing report by customer for that order cycle and hub.
4. See that the weight column is always 0.0.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/1790176/189202828-24a23101-668c-4851-8262-84657cc67319.png)

## Workaround

None.

## Severity
(?) bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: staged [6e161bb](https://github.com/openfoodfoundation/openfoodnetwork/commit/6e161bb749b0a394da6ea6dfc7bd766558ef29c9)
* Browser name and version: Firefox 104
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

**Comment by RachL** [comment]
closing as this is currently handled in #9487
