### ISSUE TITLE
[Subscriptions] Searching a shop doesn't work when creating a new subscription

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9648]
## Description

When setting up a new subscription the list of shop open and shows a search input but you can't type anything in there. You have to scroll through the list of shops to find the one you need.

## Expected Behavior

Typing letters in the search input field should show the relevant results only.

## Actual Behaviour

Typing into the search input field is not possible.

## Steps to Reproduce

1. Go to /admin/subscriptions
2. Click 'New Subscription'
3. A modal opens
4. Try to search for a shop in the list

## Animated Gif/Screenshot

![Peek 2022-09-08 15-08](https://user-images.githubusercontent.com/1790176/189215498-90fc4e40-8404-44f3-bce7-9386b0794bef.gif)

## Workaround

Find and select the shop without using the search.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [abbb61b](https://github.com/openfoodfoundation/openfoodnetwork/commit/abbb61b943abb0c22012bdcb147f898d1b0b5bf2)
* Browser name and version: Firefox 104
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

**Comment by RachL** [comment]
Hello @ashwini-seshadri and welcome :) Feel free to start and ping us [on slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A) (dev channel) if you are stuck :) 

PS : subscription code can be a little overwhelming at first. thinking about it maybe it's not soo much a good first issue. So don't feel bad to pick up another one if you loose too much time on it. thanks!

**Comment by ashwini-seshadri** [comment]
Hello @RachL 
Thank you for the kind words! :)
Can you please point me at the files/modules that might be useful to look at when understanding this issue.

**Comment by RachL** [comment]
@ashwini-seshadri perhaps a first step is the user guide? Here you have a detailed info on what the feature does: https://guide.openfoodnetwork.org/basic-features/subscriptions/subscriptions-creating-and-managing-orders

**Comment by ashwini-seshadri** [comment]
@RachL Thanks for the hint! It was very helpful. I was able to reproduce the issue. I am going to explore the fix for it.

**Comment by ashwini-seshadri** [comment]
Hi, I seem to have found an issue with `.ofn-select2` [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/templates/admin/new_subscription_dialog.html.haml#L8). I see the focus on the input field dropping in and out rapidly.
I tried to look for issues on select2, describing the above and was unable to find anything useful.
Can you also please help me with looking for potential leads that could solve the issue.
Thank you!

**Comment by sigmundpetersen** [comment]
@jibees would this be related to the switch to `tom-select` ?

**Comment by jibees** [comment]
Our vision/goal is to replace each occurence of `ofn-select2` by `tom-select` via the Stimulus controller `app/webpacker/controllers/tom_select_controller.js` (for example, see that commit : abbb61b943abb0c22012bdcb147f898d1b0b5bf2)

The one you point is handled via the old `ofn-select2`, thus I'd propose you to replace it to a select input handled via `tom-select`, and see how it goes. Maybe will solve your issue?

**Comment by ashwini-seshadri** [comment]
@jibees Thank you very much for your suggestion. I will try this out and let you know how it goes!
Hopefully, this will solve the issue. 🤞🏾

**Comment by ashwini-seshadri** [comment]
I explored around and I am planning to stop using `select2` and start using `tom-select` in [this](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/templates/admin/new_subscription_dialog.html.haml) file.
I discovered that it is a file that gets compiled (I think) along with the rest of the JS files. 

I think the way to solve this issue is to ditch the compiled haml file/move it inside rails views and attach a stimulus controller to it.

WDYT about this approach?

**Comment by jibees** [comment]
Hi @ashwini-seshadri 

I'm not sure to understand what is the issue you're facing? 
I can see that this file is added via: 
```
template = $compile($templateCache.get('admin/new_subscription_dialog.html'))(scope)
```
Is that point that failed? 

I'm not sure what's the solution is (since I don't know the problem), but adding this file into a rails view and attach to a stimulus controller seems definitely to be a good way to go!

Regarding stimulus and modal, we already have some (like `app/webpacker/controllers/help_modal_controller.js`) but maybe it's time to have a generic one.

**Comment by ashwini-seshadri** [comment]
Hi @jibees! Your inputs were really helpful. I have opened a pull request for the issue.

**Comment by filipefurtad0** [comment]
Hey @ashwini-seshadri ,
Welcome :wave: 

Thanks for picking this up, I've verified the issue prior to staging and checked that your PR fixes it after staging it:

[Screencast from 30-09-2022 13:29:30.webm](https://user-images.githubusercontent.com/49817236/193270291-803d3943-3fbc-4f5b-aa33-5e803b05b934.webm)

Many thanks! Merging.
