### ISSUE TITLE
Cookie notice impeding navigation of OFN UK mobile site

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#9658]
## Description

This issue has been raised by a number of customers, all accessing the OFN UK website using a mobile phone. When going to openfoodnetwork.org.uk for the first time on a mobile device, the cookie notice completely covers the screen and makes using the website impossible. Comments from user "Just for your information on my handset which is an huawei p20 with android 10. It is almost impossible to be able to see the site and get past the cookies policy due to it dropping off the bottom of the screen and scrolling being unavailable".

## Expected Behavior

Users accessing OFN from a mobile device should be able to click 'accept cookies' on the cookie notice to access the site. 

## Actual Behaviour

The cookie notice fills the user's mobile screen with the 'accept cookies' button out of view. The page is not scrollable, thus the button can't be clicked to remove the notice to allow users access to the site.

## Steps to Reproduce

1. From a mobile device in a hidden browser session (to force cookie notice to show), go to openfoodnetwork.org.uk
2. Observe cookie notice filling screen and unable to see 'accept cookies' button
3. Observe inability to therefore access site
4.

## Animated Gif/Screenshot

![Screenshot_20220910_084648_com android chrome](https://user-images.githubusercontent.com/100226210/189622364-7761936e-18d5-479c-9409-7dae4388a7ed.jpg)

## Workaround

Use desktop version - however this is not practical for users who may not have a desktop

## Severity
bug-s3 - this is an important issue that is preventing new customers from accessing OFN and probably therefore losing us custom.

## Your Environment

* Version used: UK prod
* Browser name and version: Android, untested on iPhone
* Operating System and version (desktop or mobile): Mobile

**Comment by RachL** [comment]
@BethanOFN FYI FR disabled the cookie banner following https://github.com/openfoodfoundation/wishlist/issues/1#issuecomment-1007265482 Have a look perhaps it's a good option as well?

**Comment by drummer83** [comment]
@BethanOFN Sometimes rotating the screen helps. Has someone tried that? ;-)

**Comment by BethanOFN** [comment]
> @BethanOFN FYI FR disabled the cookie banner following [openfoodfoundation/wishlist#1 (comment)](https://github.com/openfoodfoundation/wishlist/issues/1#issuecomment-1007265482) Have a look perhaps it's a good option as well?

Thanks @RachL - so we can remove the cookies banner altogether when following the steps outlined in the linked guide, this is great news. However, I am not a super user for the UK matomo account, only an admin. Who would be able to change my role?

**Comment by RachL** [comment]
@BethanOFN I've done it, however we are all on a shared instance. That means your are now super user for all OFN instances. So be careful when you change something ;)

**Comment by BethanOFN** [comment]
@RachL amazing thank you 👍 I will try not to get too drunk on the power 😆

**Comment by RachL** [comment]
I see UK has also removed the cookie banner, so I'm closing this one. We can always reopen if we work on shopfront responsiveness one day.
