### ISSUE TITLE
Group links from enterprise with badge

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#966]

**Comment by kirstenalarsen** [comment]
not sure what this is - @sstead could you put a bit more description?

**Comment by sstead** [comment]
This was one of the many cards which had accumulated in a pile in the office, which I put on Github. I didn't write the card so excuse vagueness, but I think this is a request for a 'badge' or link to be placed on an enterpris' profile for each group they're a member of. Clicking on this link would take the visitor to that group's page. I.e. a 'Flavour Crusader' badge would be on the profile, linking to FC group page.

**Comment by lin-d-hop** [comment]
Needs detail to be useful
