### ISSUE TITLE
[Bulk Order Management] Incorrect sorting by date: months sorted alphabetically instead of chronologically

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9661]
## Description

When sorting the orders on bulk order management page by 'completed at' date, the months are sorted alphabetically and not chronologically as you would expect. 

## Expected Behavior

Sorting ascending by date you would expect: July --> August --> September

## Actual Behaviour

It is sorted alphabetically: August --> July --> September

## Steps to Reproduce

1. Go to /admin/orders/bulk_management
2. Select date range covering three or more months
3. Sort by date (click on 'completed at' in the table header)
4. Observe the sorting

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/1790176/189726425-6020c076-75ff-4ed1-997f-cf68967fe442.png)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [5a4b38e](https://github.com/openfoodfoundation/openfoodnetwork/commit/5a4b38ec55ad0a56fd00f49fbf4899c91912fa72) (master)
* Browser name and version: Firefox 104.0 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

**Comment by AdamPRankin** [comment]
looks like a good first issue for me to tackle, will look into it

**Comment by drummer83** [comment]
Welcome @AdamPRankin! Great to have you here! 

Let us know if you get stuck! 

Looking forward to your contributions! 😊

**Comment by AdamPRankin** [comment]
initial thought is that it looks like it is comparing the datestring and not a date object.  Maybe create a custom comparator and use that to compare date objects would be the most elegant way to go? Still finding my way around the codebase and yet to find the sorting code.

**Comment by RachL** [comment]
Hello @AdamPRankin ! I hope this message fins you well. Just checking in: are you still working on this issue?

**Comment by toshitapandey** [comment]
@RachL - If no one is working on this, can I pick this up?

**Comment by RachL** [comment]
@toshitapandey apologies for the late answer. If you are still interested yes go ahead, I've assigned it to you!

**Comment by cyrillefr** [comment]
Hello @RachL , @drummer83 .
Since no one is assigned, may I work on that issue ?

**Comment by RachL** [comment]
hi @cyrillefr there is some chnages going on in BOM atm so perhaps best to wait for these changes to be merge before we fix this. I will indicate the dependency issue :+1:

**Comment by cyrillefr** [comment]
No problemo @RachL , I have the fix on my local machine. I will save it for later.

**Comment by drummer83** [comment]
Is this one still blocked? #10123 has been merged.

**Comment by RachL** [comment]
No we are good to go :+1:

**Comment by cyrillefr** [comment]
Hello @RachL & @drummer83,

May I work on this issue ? I made a patch 3 months ago, I hope it is still valid.
I am working on #9499 by now, but I can definitely check if my solution is ok within 2 days.

**Comment by RachL** [comment]
HI @cyrillefr yes go ahead 💪 thank you so much :)
