### ISSUE TITLE
Random product ordering in report Order Cycle Supplier Totals by Distributor 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9678]
## Description

For a given distributor, the results in report Order Cycle Supplier Totals by distributor are displayed in a random order. Refreshing the page changes the product ordering.

This was spotted with the `spec/system/admin/reports/orders_and_fulfillment_spec.rb`  

## Expected Behavior

Ordering should be consistent: products should be displayed alphabetically - within each distributor. 

## Actual Behaviour

Ordering is random.

## Steps to Reproduce

1. For a hub with more than one ordered product, visit admin/reports/orders_and_fulfillment
2. Run the  Order Cycle Supplier Totals by Distributor 
3. Take notice of the ordering of the products (for a given distributor)
4. Refresh the page a couple of times
5. Notice the ordering changes

Rspec related examples:
(these will be set to pending)

rspec ./spec/system/admin/reports/orders_and_fulfillment_spec.rb:304 # Orders And Fulfillment reports Order Cycle Supplier for three different orders Totals by Distributor with the header row option not selected aggregates results per variant
rspec ./spec/system/admin/reports/orders_and_fulfillment_spec.rb:438 # Orders And Fulfillment reports Order Cycle Distributor Totals by Supplier for an OC supplied by two suppliers with the header row option not selected aggregates results per variant, per supplier

## Animated Gif/Screenshot

[Screencast from 16-09-2022 15:05:09.webm](https://user-images.githubusercontent.com/49817236/190659853-7343ac72-edb3-48cf-973a-8a01ea202197.webm)

## Workaround

Use the search function in the browser.

## Severity

Not sure on the real impact.
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.2.12
* Browser name and version: Firefox 104
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by mariodz95** [comment]
I have only one item in the list, can you provide me steps to add it another one?

**Comment by drummer83** [comment]
Hi @mariodz95,
Are you working on your local setup? You should be able to login as super admin user and see all the orders and enterprises. Try to adjust the date range. There should be more orders in the past. If there are not you can create orders by registering a customer and shopping or by creating a backoffice order.

**Comment by mariodz95** [comment]
Yes, I'am working on local setup, ok I will try to figure out. (manel.super.admin@example.org, and password is?)

**Comment by drummer83** [comment]
email: ***@***.***: ofn123https://github.com/openfoodfoundation/openfoodnetwork/blob/master/GETTING_STARTED.md
-------- Ursprüngliche Nachricht --------Von: Mario Džoić ***@***.***> Datum: 16.09.22  21:17  (GMT+01:00) An: openfoodfoundation/openfoodnetwork ***@***.***> Cc: Konrad ***@***.***>, Comment ***@***.***> Betreff: Re: [openfoodfoundation/openfoodnetwork] Random product ordering in report Order Cycle Supplier Totals by Distributor  (Issue #9678) 
Yes, I'am working on local setup, ok I will try to figure out. ***@***.***, and password is?)

**Comment by abdellani** [comment]
I want to work on this, Please assign it to me.
It's a good opportunity to explore the code used to generate the report : )

**Comment by sigmundpetersen** [comment]
Nice, thank you @abdellani 🎉 
I'll assign you and move the issue to the 'In Dev' column 👍

**Comment by abdellani** [comment]
Hi 
There is one test failing among  `(spec/system/admin/[a-o0-9]*)` in the pipeline.
When I run the tests locally, I got 0 failures.
![image](https://user-images.githubusercontent.com/16113997/196376627-8c342a05-63d7-4005-8eff-1eb234cdce1c.png)

**Comment by filipefurtad0** [comment]
Hi @abdellani :wave: 
Thanks for signalling that - this issue is [being addressed elsewhere](https://github.com/openfoodfoundation/openfoodnetwork/issues/9757), so you're safe to ignore it for now.
Please carry on with your PR :+1:

**Comment by abdellani** [comment]
thank you @filipefurtad0 
I'm done with PR
