### ISSUE TITLE
Weird decimals when using 1234.5 or 1234.6 as weight in imperial metric system

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9679]
## Description

Similar to #9493
When adding 1234.5 or 1234.6 as product weight in an imperial (oz) system, ends up with a huge number of unnecessary decimals on page /admin/products.

## Expected Behavior

Just keep 1234.5 or 1234.6 - no additional decimals.

## Actual Behaviour

![image](https://user-images.githubusercontent.com/1790176/190681290-e1d71e7e-5243-4f8c-89b2-f50148efd491.png)

## Steps to Reproduce

1. Create or edit a product with weight in oz
2. Enter 1234.5 or 1234.6
3. Save
4. :boom: 

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: staged [498d003](https://github.com/openfoodfoundation/openfoodnetwork/commit/498d0036841b726b380eb1483218299725383231)
* Browser name and version: Firefox 104.0
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

## Possible Fix

See #9497?

**Comment by Minami-jp** [comment]
Hello. I am sure, I can fix the problem.
Please let me know when possible to discuss with me.

**Comment by jibees** [comment]
Hi @Minami-jp 👋  
and welcome. 

I've assigned to your the issue. 
Please, feel free to comment here if you're stuck on something.

**Comment by RachL** [comment]
hello @Minami-jp as you are already assigned to #9661 I've unassigned you here so someone else can have a look as well :) don't hesitate to comment if you already had started something.

**Comment by saunmanoj888** [comment]
hii @jibees @RachL 
Can I work on this issue?
Thanks

**Comment by drummer83** [comment]
Sure, @saunmanoj888!
I have assigned it to you! 👍🏻
