### ISSUE TITLE
[BO] Can't find customers as superadmin 

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9684]
## Description

As superadmin, it's currently not possible to find customers by using the search box in /admin/orders/<order_nr>/customer. This works fine as the hub manager.

See #9683

## Steps to Reproduce

1. Login as super admin
2. Visit /orders
3. Click "New order"
4. Select an enterprise and order cycle
5. On the Customer Details tab try do find any customer by typing in the name or email -> no results
6. Logout and login as an entrerprise owner with customers
7. Repeat from 2. -> see that the query yields results

Alternatively run the spec #9683 on your local system.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/191023136-c7734d6a-ffdc-4eb2-9cc7-139f0681a502.png)

## Workaround

?

## Severity

As per https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1663530146433049
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: verified in v4.2.12
* Browser name and version: Firefox 104
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by jibees** [comment]
I can't reproduce it in my local environnement.

**Comment by jibees** [comment]
Found!

```diff

diff --git a/app/controllers/spree/admin/search_controller.rb b/app/controllers/spree/admin/search_controller.rb
index 1ddb023b3a..df96618fc0 100644
--- a/app/controllers/spree/admin/search_controller.rb
+++ b/app/controllers/spree/admin/search_controller.rb
@@ -19,7 +19,12 @@ module Spree
 
       def customers
         @customers = []
-        if spree_current_user.enterprises.pluck(:id).include? search_params[:distributor_id].to_i
+        enterprise_ids = if spree_current_user.admin?
+                           Enterprise.pluck(:id)
+                         else
+                           spree_current_user.enterprises.pluck(:id)
+                         end
+        if enterprise_ids.include? search_params[:distributor_id].to_i
           @customers = Customer.
             ransack(m: 'or', email_start: search_params[:q], first_name_start: search_params[:q],
                     last_name_start: search_params[:q]).
diff --git a/spec/system/admin/order_spec.rb b/spec/system/admin/order_spec.rb
index ab23c34346..76bdffa60a 100644
--- a/spec/system/admin/order_spec.rb
+++ b/spec/system/admin/order_spec.rb
@@ -755,7 +755,6 @@ describe '
       end
       
       it "finds a customer by name" do
-        pending("issue #9684")
         serching_for_customers
       end
     end
```
