### ISSUE TITLE
Different admin interface for a producer who didn't connect for few years

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9700]
## Description
There was a bug on shop #1080, who displayed a weird version (old version?) of the website with different wordings and some missing features. The producer created this shop in 2018/2019 and didn't access the admin page since then. 
It could be good to check if this bug applies to other producers who didn't log in for a long time.

## Expected Behavior
The admin website must be the latest version.

## Actual Behaviour
The user logged in (from 2 different computers), and had access to a strange version of the admin interface, that might be an old version. 
For instance, translations were not the same than the classic admin interface:
- main menu: "Des produits" instead of "Produits", "Ordres" instead of "Commandes", "Clients" instead of "Acheteurs"
- enterprise category: "centre de producteurs" instead of "boutique multi-producteurs"..

I first thought it could be a translation issue, so I asked the user to go to www.coopcircuits.fr and check the language. It was fine so he went back to the admin page... and surprisingly, it was now displaying the good interface. 
So I wasn't able to see much more than the sent screenshot, but the producer said that some functionalities were missing (for instance no "Columns" button in the product list).

## Steps to Reproduce
Connect with a user account that hasn't logged for a long time?

## Animated Gif/Screenshot
![IMG_20220923_140000(1)](https://user-images.githubusercontent.com/28386648/191959611-60bd7eff-c910-49ef-a73c-03b86ca1254f.jpg)

## Workaround
Go to the main site and go back to the admin. 

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by RachL** [comment]
@audez I think this is a classic cache problem? I don't think we can do anything about it. When this occur we can ask the user to do a Ctrl+F5 to empty his cache properly.

> like the "Mode d'emploi" button, are not there anymore.

We still have the user guide on this page: 

![image](https://user-images.githubusercontent.com/6525576/191962409-315025e8-f5e0-4c3e-89d8-0c96cdd0e95c.png)

**Comment by audez** [comment]
Oh ok yes i edited the issue for the button, thanks :) 
For the cache, I think I didn't give proper explanation: the producer created his account few years ago. Now the producer loged in again, and had this weird interface. Then the hub manager connected with the producer account on his own computer, and had the same old interface. So it can't be linked to the browser cache, can it?

**Comment by audez** [comment]
same as #9803 
it's not a browser version or cache problem. The thing is:

    You open coopcircuits.fr and chose "EN" language
    Then you ask Chrome to "translate in French" (when the popup opens or with a right click - translate)
    And you end up with a poorly translated interface... which is exactly the screenshots the 2 producers sent...

**Comment by RachL** [comment]
ha nice catch @audez !
