### ISSUE TITLE
Shopfront: product description should have a pointer cursor when it's clickable

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#9703]
## Description
Product description can be clickable to open a modal, and read the whole production description:

<img width="951" alt="Capture d’écran 2022-09-26 à 10 14 43" src="https://user-images.githubusercontent.com/296452/192227669-d2ce8a52-6d5b-4fe7-b0a4-d44d6eae4920.png">

<img width="1041" alt="Capture d’écran 2022-09-26 à 10 14 48" src="https://user-images.githubusercontent.com/296452/192227146-f5852227-3f9b-43fa-8b96-78b8092584f1.png">

## Expected Behavior
Cursor should be pointer on product description when it's clickable.

## Actual Behaviour
Cursor is text on product description when it's clickable.

## Steps to Reproduce

1. As a customer, go to a shopfront
2. See that product description is clickable
3. Cursor should be the pointer one

## Severity
bug-s4: it's annoying, but you can use it

**Comment by viniciusueharaweb** [comment]
Hey, can I take this one?

**Comment by jibees** [comment]
Hi @viniciusueharaweb 👋 
and welcome! 

Sure, I'll assign you. Please feel free to comment if you're stuck on something!

**Comment by RachL** [comment]
Hello @viniciusueharaweb I hope this message finds you well. Just checking in: are you still working on this issue?

**Comment by viniciusueharaweb** [comment]
> Hello @viniciusueharaweb I hope this message finds you well. Just checking in: are you still working on this issue?

Yup! Had a busy schedule past week, hope I can handle this issue next days!
