### ISSUE TITLE
The search for eaters- how to improve it

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#971]
Need to explore and examine ways to improve

**Comment by pmackay** [comment]
@sstead could you add a bit more detail to this please?

**Comment by sstead** [comment]
Hey @pmackay this was one of many cards that had accumulated at OFN Melbourne, which I entered into github. I think it's a general prompt to do some UX improvements for shoppers who arrive at OFN. How could we improve the landing page, maps, directories, search/filter tools etc. You can close it if you think it's redundant/covered elsewhere/not specific enough.

**Comment by lin-d-hop** [comment]
This has been raised by Yuko in her UX inspections. UK are marking this as an important one. My understanding is Yuko and @daniellemoorhead are going to wrestle them all into manageable github issues once theyve been designed. Which is _Very Awesome_!

**Comment by pmackay** [comment]
Sounds like this is an epic then!

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/discovery/1177
