### ISSUE TITLE
[Split Checkout] Incorrect backgroundcolor in order summary table

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9722]
## Description

The alternating colors of the table displaying the products on the order summary page are not properly implemented.

## Expected Behavior

The background color of the complete row should be identical.

## Actual Behaviour

The background color of the product name is always grey, even in the white rows.

## Steps to Reproduce

1. Activate split checkout (as super admin)
2. As a customer put at least 3 different products in your cart
3. Proceed to the order summary page
4. Look at the background colors of the table

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/1790176/193086900-ef2b3405-4d27-4c28-b3dd-fcce0c1d6ddb.png)

## Workaround

None.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [ebe4a3d](https://github.com/openfoodfoundation/openfoodnetwork/commit/ebe4a3d6ab3ba6cf52efaebb30f95b422638cd2b)
* Browser name and version: Firefox 104
* Operating System and version (desktop or mobile): Desktop Windows 10 Enterprise

**Comment by Yh010** [comment]
I would like to work on this issue. Could u pls assign this issue?

**Comment by jibees** [comment]
Hi @Yh010 
And welcome here! Yep, sure, i'll assign it to you ;)

**Comment by snehalsenapati23** [comment]
Hello @jibees i want to work on this issue . Could you assign it to me?

**Comment by jibees** [comment]
Hi @snehalsenapati23 👋 
And welcome here !

This one is already assigned to @Yh010 ;) 
Could you please find another issue, marked as `good first issue` if you want?

**Comment by RachL** [comment]
hello @Yh010 I hope this message finds you well. Just checking in: are you still working on this issue?

**Comment by Yh010** [comment]
hey! 
actually, I was occupied with my college's mid-semester exams, and on-campus internship rounds..will be starting to work on this issue this Monday...

**Comment by RachL** [comment]
Hello @Yh010 I'm unassigning you for now, but feel free to comment back here if you are still planning to work on this. Hope everything is well for you!

**Comment by RachL** [comment]
this is fixed in #10254 :+1:
