### ISSUE TITLE
Unused Paperclip columns still present

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9726]
### What we should change and why (this is tech debt)

We replaced Paperclip with Active Storage but we kept the old Paperclip columns in the database tables for the transition. This transition is well over now and new devs get confused about inconsistent data. They look at the old Paperclip columns and wonder why they don't match up with uploaded files.

Removing the columns should also reduce the database size and make result sets smaller.

:warning: *This issue should be solved in two pull requests:*

1. Add the column to `ignored_columns` on each model. Otherwise we would encounter server errors during deployment because Rails would still try to access these columns when we just deleted them. This has to be deployed before the next pull request is merged.
2. Create database migrations to remove the columns. After they have been ignored, it's safe to delete the columns. The `ignored_columns` config should be removed as well now.

### Context

- #9126
- #9119

**Comment by AthiraKadampatta** [comment]
Hello @mkllnk I would like to work on this one. Could you please assign it to me?

**Comment by mkllnk** [comment]
Done. All yours.
