### ISSUE TITLE
Does Groups homepage need to exist?

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#973]

**Comment by pmackay** [comment]
@sstead could you add a bit more context to this please?

**Comment by sstead** [comment]
This question was raised in Aus by @daniellemoorhead (Dani feel free to chime in). At the time 'Groups' was one of our primary menu items at the homepage (this is no longer the case, we have 'connect' and 'learn' instead). The groups page itself only listed 3-4 groups, so seemed like a waste of real estate. From a user's perspective we also asked whether browsing by group is a common way to navigate, and whether it may just be confusing. I think in Aus the potential for group pages is highest IF the group pages could be embedded in external websites (regional tourism sites etc). If this is made possible, the group directory may not be needed. Essentially it's just a questions of what the intention of the Groups homepage is, and how effective it is. If it's not performing a useful function, perhaps it should be removed.

Regarding the directory thread, personally I think yes, if the map were to have greater functionality as a directory, and you could filter by group, the groups directory may become even more redundant?

**Comment by myriamboure** [comment]
I agree with what @sstead says, groups make sense if can be embedded in the website of a municipality for a local food system visualization for example So even with a more powerful directory, I think this need to have the possibility to embed a group will remain. For example even if I can filter on "The Food Assembly" on the general map, maybe the Food Assembly would like to embed a white labeled group into their website with only the Food Assembly hubs.
But in all cases, no need for a top homepage, groups ca be a bottom/less visible link for the moment. And group embed will soon come as a priority I guess as soon as someone can pay to develop the embed feature :-)
