### ISSUE TITLE
Deleted variants can't be deleted from orders (error 404)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9734]
## Description

If an enterprise user deletes a variant which has been ordered by customers before, this item cannot be deleted from the customers orders (error 404). 

## Expected Behavior

The line item should be removed from the order.
The question is, what should happen, if the user selects to 'restock' the item to the existing stock? A warning that the variant doesn't exist anymore?

## Actual Behaviour

There is an error 404 in the browser.

## Steps to Reproduce

1. As customer: Place an order.
2. As shop manager: Delete the variant or the product from your product list (or variant list).
3. As shop manager: Try to delete this variant on the orders/Rxxxxxxxx/edit page
4. Observe the 404

## Animated Gif/Screenshot

`curl "https://staging.openfoodnetwork.org.uk/api/v0/orders/R846253275/shipments/H82234103731/remove.json" -X PUT -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0" -H "Accept: */*" -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate, br" -H "Referer: https://staging.openfoodnetwork.org.uk/admin/orders/R846253275/edit" -H "X-CSRF-Token: NoQBvV5T5WtLv428HvLI1pHNJJe8dP6RHZDa3vGDEoFnTt3sXPdUO7R1-jUFM7TO8XdhlDbZ3M7b4DbIuKBwIg" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "X-Requested-With: XMLHttpRequest" -H "Origin: https://staging.openfoodnetwork.org.uk" -H "Connection: keep-alive" -H "Cookie: _ofn_session_id=c9fa4dffb7daed7af5fcebed3e8a7638; XSRF-TOKEN=GoWvxF221U6GLXITGSdbg37Vfy2mXjRN-LXvsLPLvyJLT3OVXxJkHnnnBZoC5iebHm86LizzFhI-xQOm-ujdgQ; __stripe_mid=ed46b5b4-ba65-46c7-9acf-aff89c8d39b3d1da30; cookies_consent=cookies_consent" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: same-origin" -H "TE: trailers" --data-raw "variant_id=62435&restock_item=true&quantity=3"`

```
{
	"PUT": {
		"scheme": "https",
		"host": "staging.openfoodnetwork.org.uk",
		"filename": "/api/v0/orders/R846253275/shipments/H82234103731/remove.json",
		"remote": {
			"Address": "10.4.68.1:8080"
		}
	}
}
{
	"Status": "404Not Found",
	"Version": "HTTP/2",
	"Transferred": "879 B (65 B size)",
	"Referrer Policy": "strict-origin-when-cross-origin",
	"Request Priority": "Highest"
}
{
	"Response Headers (820 B)": {
		"headers": [
			{
				"name": "cache-control",
				"value": "no-cache"
			},
			{
				"name": "content-encoding",
				"value": "br"
			},
			{
				"name": "content-security-policy",
				"value": "default-src 'self' https:; font-src 'self' https: data: fonts.gstatic.com; img-src 'self' https: data: *.s3.amazonaws.com; object-src 'none'; frame-ancestors 'none'; script-src 'self' https: 'unsafe-inline' 'unsafe-eval' *.stripe.com openfoodnetwork.innocraft.cloud maps.googleapis.com maps.gstatic.com d2wy8f7a9ursnm.cloudfront.net; style-src 'self' https: 'unsafe-inline' fonts.googleapis.com cdnjs.cloudflare.com"
			},
			{
				"name": "content-type",
				"value": "application/json"
			},
			{
				"name": "date",
				"value": "Tue, 04 Oct 2022 16:37:00 GMT"
			},
			{
				"name": "server",
				"value": "nginx"
			},
			{
				"name": "strict-transport-security",
				"value": "max-age=63072000; includeSubDomains"
			},
			{
				"name": "x-content-type-options",
				"value": "nosniff"
			},
			{
				"name": "X-Firefox-Spdy",
				"value": "h2"
			},
			{
				"name": "x-request-id",
				"value": "680c8de2-3045-4600-892f-f3d95d35e393"
			},
			{
				"name": "x-runtime",
				"value": "0.046630"
			},
			{
				"name": "x-xss-protection",
				"value": "1; mode=block"
			}
		]
	}
}
{
	"Request Headers (982 B)": {
		"headers": [
			{
				"name": "Accept",
				"value": "*/*"
			},
			{
				"name": "Accept-Encoding",
				"value": "gzip, deflate, br"
			},
			{
				"name": "Accept-Language",
				"value": "en-US,en;q=0.5"
			},
			{
				"name": "Connection",
				"value": "keep-alive"
			},
			{
				"name": "Content-Length",
				"value": "45"
			},
			{
				"name": "Content-Type",
				"value": "application/x-www-form-urlencoded; charset=UTF-8"
			},
			{
				"name": "Cookie",
				"value": "_ofn_session_id=c9fa4dffb7daed7af5fcebed3e8a7638; XSRF-TOKEN=GoWvxF221U6GLXITGSdbg37Vfy2mXjRN-LXvsLPLvyJLT3OVXxJkHnnnBZoC5iebHm86LizzFhI-xQOm-ujdgQ; __stripe_mid=ed46b5b4-ba65-46c7-9acf-aff89c8d39b3d1da30; cookies_consent=cookies_consent"
			},
			{
				"name": "Host",
				"value": "staging.openfoodnetwork.org.uk"
			},
			{
				"name": "Origin",
				"value": "https://staging.openfoodnetwork.org.uk"
			},
			{
				"name": "Referer",
				"value": "https://staging.openfoodnetwork.org.uk/admin/orders/R846253275/edit"
			},
			{
				"name": "Sec-Fetch-Dest",
				"value": "empty"
			},
			{
				"name": "Sec-Fetch-Mode",
				"value": "cors"
			},
			{
				"name": "Sec-Fetch-Site",
				"value": "same-origin"
			},
			{
				"name": "TE",
				"value": "trailers"
			},
			{
				"name": "User-Agent",
				"value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0"
			},
			{
				"name": "X-CSRF-Token",
				"value": "NoQBvV5T5WtLv428HvLI1pHNJJe8dP6RHZDa3vGDEoFnTt3sXPdUO7R1-jUFM7TO8XdhlDbZ3M7b4DbIuKBwIg"
			},
			{
				"name": "X-Requested-With",
				"value": "XMLHttpRequest"
			}
		]
	}
}

Request:
{
	"variant_id": "62435",
	"restock_item": "true",
	"quantity": "3"
}

Response:
{
	"error": "The resource you were looking for could not be found."
}
```
## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
I think this is a duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/4203 ?

**Comment by drummer83** [comment]
Yes, it is! Damn it - I couldn't find that one.
Closing.

Duplicate of #4203.
