### ISSUE TITLE
Bulk Edit Products - group buy, on demand properties

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#976]
- Primary taxon
- image
- description
- properties
- on demand
- group buy

Current:
![image](https://cloud.githubusercontent.com/assets/10843056/15006941/f3f879ba-1217-11e6-997c-15f242fb79ce.png)

**Comment by myriamboure** [comment]
@sstead can you explain what you are talking about ? I don't understand. Else just close please if not relevant anymore.
