### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#977]
1) Set up google analytics events and goals

2) Implement google tag manager

3) Define analytics plan

4) Set up a trial Google analytics dashboard for a shop

**Comment by pmackay** [comment]
Relates to #938 (should be fixed first?).

**Comment by RachL** [comment]
As we are not planning on expanding GA in the short term, I'm closing this. We can of course move this discussion to discourse if needed.
