### ISSUE TITLE
Admin, Enterprise Settings, Business Details Panel, Business Address : First country of the available ones is selected

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#9777]
## Description
Regarding several hub in `fr-prod`, it appears that all of them have Afghanistan selected as their country on page, although it seems very unlikely.

`/admin/enterprises/[HUB_PERMALINK]/edit#!#business_details_panel` :

<img width="855" alt="Capture d’écran 2022-10-13 à 12 22 51" src="https://user-images.githubusercontent.com/296452/195572990-6aebec1e-6306-492d-abd1-01ae0bfa84b3.png">

\+ it seems that when we change country selector value, the state selector options do not change at all. 

*Important drawback*: when saving anything is this page (ie. `/admin/enterprises/[HUB_PERMALINK]`), I guess that the country will be effectively changed to Afghanistan (instead of France in case of `fr-prod`)

## Expected Behavior
Right country is selected. Ie. should be France in most of case.

## Actual Behaviour
Although France is the country saved in DB, it appears that Afghanistan is selected since it's the first one on the list.

## Steps to Reproduce

1. As an admin, go to `/admin/enterprises/[HUB_PERMALINK]/edit#!#business_details_panel`
2. Change country to a country that is not the first in the list
3. See that state options did changed
4. Select a state that is not the first on the list
5. Save
6. And then refresh the page, and see that country/state are well saved and are selected in the components.

## Workaround
I don't see any workaround. Each time will save anything on the page, first country of the selector will be saved.

## Severity

bug-s2: a non-critical feature is broken, no workaround

**Comment by drummer83** [comment]
Great catch @jibees, another issue around this country selector was identified here: https://github.com/openfoodfoundation/openfoodnetwork/pull/7973#issuecomment-937727738.
It was agreed to tackle that at a later stage, but now that you are working on that anyway, it might be the right time to fix it. Maybe it was covered by your solution already? Or by @binarygit's work?

**Comment by jibees** [comment]
Oh, nice spotted @drummer83 ! I think I can correct it easily ;)

**Comment by mkllnk** [comment]
I think this bug was introduce with 0cfe842bd6f664489074db9975db63db9cf38d45 in [v4.2.13](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v4.2.13). So it's already deployed and doesn't block the release.
