### ISSUE TITLE
Can't save inventory

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#978]
Whenever I try to save any changes in inventory, it says "I couldn't get authorisation to save those changes, so they remain unsaved."
![screenshot 2016-05-04 18 51 05](https://cloud.githubusercontent.com/assets/10517702/15023731/a2fdbd10-1229-11e6-9c32-da8e3085ab8d.png)

**Comment by OliverUK** [comment]
Thanks for looking at this @lin-d-hop ! We are trying to get ready to open for orders and this is preventing us from setting reset levels (or removing existing overrides).

**Comment by lin-d-hop** [comment]
My guess this is also a permissions issue. @NickWeir63 can you check that the enterprise has the permission 'add to inventory' in the enterprise relationships? Thanks!

**Comment by NickWeir63** [comment]
Hi @lin-d-hop 
I checked the enterprise relationships and they all look good
![screenshot 2016-05-06 08 28 20](https://cloud.githubusercontent.com/assets/10517702/15066981/2784bac0-1365-11e6-8cec-4c5d2b1d2c41.png)

then i tried to set a stock default but when i clicked save I got this again

![screenshot 2016-05-06 08 32 05](https://cloud.githubusercontent.com/assets/10517702/15067003/42c98cc0-1365-11e6-9de0-fce16e5fffd9.png)

**Comment by OliverUK** [comment]
Besides we are trying to save our own inventory!

**Comment by NickWeir63** [comment]
@lin-d-hop this is now the only issue that is preventing @OliverUK going ahead with the Stroudco switchover.  No pressure(!!) but is there anything else that we could try to sort this authorisation thing?......... I just logged in as superadmin and tried making a change to inventory (see screenshot) and it saved successfully.
I wonder if this problem that Oliver and I are having with authorisation is something that changed when we upgraded to v1.6 because up until then we had no problem saving inventory changes?
![screenshot 2016-05-07 08 06 51](https://cloud.githubusercontent.com/assets/10517702/15090760/229b9d28-142b-11e6-8868-019a0084bfac.png)

**Comment by NickWeir63** [comment]
In superadmin I have now changed Stroud Community Agriculture (one of the producers who needs to be able to reset their stock levels every week) to be able to sell their own produce (changed from 'none' to 'own') and i then set up one of my other email addresses to be manager of Stroud Community Agriculture.  When I log in with this address I can save changes to inventory (see 1st screenshot) but when I log in with my usual email I get the "no authorisation" message (2nd screenshot)
![screenshot 2016-05-07 08 17 59]
![screenshot 2016-05-07 08 20 45](https://cloud.githubusercontent.com/assets/10517702/15090829/6e152740-142d-11e6-8c1b-344e1ba286bc.png)
(https://cloud.githubusercontent.com/assets/10517702/15090828/642ff836-142d-11e6-9426-5bd232772bbc.png)

**Comment by OliverUK** [comment]
Thanks for investigating further @NickWeir63 .

**Comment by NickWeir63** [comment]
@lin-d-hop I have just spoken to Oliver and he is happy to go with this work around and do the Stroudco switchover this weekend so we can fix this authorisation issue later so I am taking the important label off now.  thanks

**Comment by lin-d-hop** [comment]
@OliverUK @NickWeir63 
My understanding of the Inventory Page is that it is intended as a way for SHOPFRONTs to manage their stock as separate from Producers.

A producer can manage their stock levels from the Product page directly. This is the master stock levels, when done at the producer level. You can do this in the variants tab when editing a product.

The point of the inventory is in case any hub or hub/producer needs to override the Master stock level or a producer, say if the producer will only delivery 6 at a time, or something like that.

So, no producers without shopfronts should NEED to have access to an inventory, as they only have a master product list and no override.

Can you both confirm if this makes sense and feels appropriate to the current inventory issues you've been facing? If not apologies for misunderstanding and we can chat in more detail.

**Comment by OliverUK** [comment]
Hi Lynne,

It DOES make sense in terms of what inventory is meant for. But what we are saying above is that we aren't able to save even our own inventory page, even though we have a shopfront. 

When we tried to give producers access to the reset stock level functionality we gave them shopfronts to allow them to see the inventory page. 
So there are two separate issues:

- The error message that prevents us from saving any inventory page changes

- The reset stock level functionality is in the wrong place and should be moved to the products screen

**Comment by lin-d-hop** [comment]
Hi @OliverUK 
Thanks, no it is much clearer.
I will take a look at the auth error.

Regarding the reset stock being in the wrong place... reset stock is an attribute on an order cycle. A products properties propagate to every hub they supply, however the reset stock variable is designed to be specific to a hub. This will become a separate issue on improvements to stock reset... I'll be in touch to spec more.

**Comment by lin-d-hop** [comment]
@NickWeir63 @OliverUK 
I think I've solved this. The issue seemed to be caused by some corrupt data in the Variant Override table. There were two entries in the Variant Override table that Stroudco did not have permission to manage stopping future updates from completing.
I don't know how this happened. When did this issue start occurring? If since the beginning of time it might have been related to the original data import in some way.
Hopefully the Inventory will save correctly now. Please test and close if you are happy.

**Comment by OliverUK** [comment]
@lin-d-hop 
Lynne, yes, I can now save the inventory again, thanks you! 
I reckon it started with the implementation of 1.7 but may be wrong.
