### ISSUE TITLE
[Product import] Wrong error message when shipping category doesn't match predefined shipping categories

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9781]
## Description
When importing a .csv with products with shipping categories:
- that contains a mispelling in the name: for instance "Default " (with one extra space)
- or that doesn't match one of the predefined categories (see the list below)
![Screen Shot 2022-10-13 at 15 27 18](https://user-images.githubusercontent.com/28386648/195610883-c40d42ba-cba2-4a6e-958f-7f6602260384.png)

The error displayed to the user is: "-  Shipping_category can't be blank ", whereas the category isn't blank.

This is misleading for the user, and they contact us asking why they have this error whereas the shipping category is filled in.

## Expected Behavior
The error should be: "Shipping_category doesn't match allowed categories. See the correct categories to choose from on the product import page, or check that there's no mispelling."
Or something like that?

## Steps to Reproduce
1. Connect to a shop
2. Import a file with wrong shipping category, for instance :
[Bug-shipping-error.csv](https://github.com/openfoodfoundation/openfoodnetwork/files/9777177/Bug-shipping-error.csv)

## Animated Gif/Screenshot
![Screen Shot 2022-10-13 at 15 23 12](https://user-images.githubusercontent.com/28386648/195611486-c82f4016-82d4-4232-8086-73482012b44c.png)

## Severity
bug-s4: it's annoying, but you can use it

**Comment by RachL** [comment]
@viniciusueharaweb yes sure :) just beware that product import code can be messy. So don't hesitate to jump or another one after or ask for help :)

**Comment by audez** [comment]
😍
