### ISSUE TITLE
[Bulk order management] "Group Buy Unit Size" displays zero when too small

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9789]
## Description
If the value entered by the user in the "group buy" option is too small, in the "Bulk order management page" the "group buy unit size" displays "0" instead of the value corresponding to that was set up by the user.

## Expected behavior
The "Group buy unit size" that is displayed in the "Bulk order management page" (admin/orders/bulk_management#) should match the "group buy" unit size that the user sets in the product "group buy" option.

Knowing that the value entered by the customer in the "group buy" option follows [this rule](https://guide.openfoodnetwork.org/basic-features/products-1/group-buy-for-bulk-ordering#adjusting-orders-to-make-complete-batches):
```
The units for the Bulk Unit Size quantity depend on the units selected for retailing the product to customers.  
If the product is sold by:
Weight: units are in g (so if collective total must equal 5 kg then enter '5000' in this field)
Volume: units are in litres (so if collective total must be 10 l then enter '10' in this field)
Items: eg. selling bunches of flowers but must purchase 100 bunches in total then enter '100' in this field
```

## Steps to Reproduce
1. Create products with units: kg and T.
2. For these products, set "group buy" option to yes, and set a bulk unit value to 0.1 for instance
3. Pass an order with those products
4. Go to the "Bulk order management page" (admin/orders/bulk_management#) and click on each product
5. See that Group Buy Unit Size = 0

(you can also use shop 2732 on https://staging.coopcircuits.fr and check VRAC 1 - amandes: 1kg)

## Animated Gif/Screenshot
![Screen Shot 2022-10-14 at 14 05 26](https://user-images.githubusercontent.com/28386648/195843269-fad591a8-e672-4632-a79d-15bfda4b4fb8.png)

## Severity
bug-s5

**Comment by RachL** [comment]
@audez I think this is expected behavior? If I follow the quote, instead of 1 kg we should use 1000 g. this way the quantity is never small?

**Comment by audez** [comment]
mmm nope. I mean the user is not _supposed to_ put small values, but if they put a small value:
- if we allow them to do it, then the value they entered must be displayed in the "Group buy unit size". 
I think it's just a bug in this field that doesn't display values less than 0.001. Because we see that the value has still been recorded in database, as the calculations of "current" and "max fulfilled units" are done
- if we don't allow small values, then we must tell them that they can't, and it shouldn't be possible to save small value and we should display a clear error message

**Comment by RachL** [comment]
yes I understand, but it looks as something that was scoped this way. Let's use https://github.com/openfoodfoundation/wishlist/issues/300 to move forward! Thanks :green_heart:
