### ISSUE TITLE
Giving suppliers permission to reset default stock levels

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#979]
We are trying to set up some of our producers to be able to change their stock reset levels. We couldn't get any inventory page to display when logged in as the supplier. I wonder if it's because they have to have a shop front? 
Is there any way round setting them up with a shopfront?

**Comment by OliverUK** [comment]
I'm not sure I see the sense in only allowing those with a shop front to set this type of stock level. Maybe it's something that can be moved to the products page?

**Comment by lin-d-hop** [comment]
@NickWeir63 @OliverUK 
Producers can change their stock levels, but only as On Hand and On Demand levels. Reseting stock levels can currently only be done through an inventory which isn't available to users without a shopfront.

I can see the need to producers wanting to be able to change their stock levels in the Stroudco order cycle. The solution sounds like it might be that producers need a list of the hubs they are supplying with the ability to change stock levels and prices to each hub themselves. Currently the hubs can do this on the producers stock for their inventory but I believe it can't be controlled the other way around.

I'll look into a little more. I can see this is a nice feature but potentially not an urgent one at the moment? It would be required for big producers such as Essential.

**Comment by OliverUK** [comment]
@NickWeir63 @lin-d-hop 
Nick, ok to close this?
We know now that producers can't reset stock in the Stroudco inventory and that they can only set stock in "products", which doesn't have the reset function.

**Comment by lin-d-hop** [comment]
The question is is this useful functionality?
I can see that it would be useful for a producer to be able to set the level of stock available for different producers OCs but feel that it would be quite a large amount of work for quite a small gain.

If we are happy to roll with not having it then close.
If it is a future desired enhancement then change the title and description to more closely describe the functionality required and move to backlog/icebox.

**Comment by NickWeir63** [comment]
Looking to the future I can imagine that Stroudco producers might be selling through multiple hubs/shopfronts so it would be useful to have this functionality.  But I also take Lynne's point about the cost of development time to make this happen.  
I think we rename it and move it to icebox for when OFN has loads of money and hoards of developers looking for something to do!!!!
What do you reckon @OliverUK

**Comment by OliverUK** [comment]
OK, icebox it then.

**Comment by myriamboure** [comment]
Iceboxed here https://community.openfoodnetwork.org/t/enable-product-chain-tracking-hubs-variants-creation/1152 (connected to network product chain and permission + OC overhaul) #gitcull2018
