### ISSUE TITLE
Updates to UK About page

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#980]
- [x] Upload images to AWS server
- [x] Add html to case studies to display pics
- [x] General pretty-ing up

**Comment by lin-d-hop** [comment]
About to link to Au page, Au contacts to specificy UK contact.
Newsletter to UK mailchimp.
News still to global for now.
Twitter -> UK
Facebook, waiting.

Check links from User Guide

**Comment by lin-d-hop** [comment]
Mags, will you take a look at this and suggest changes. Look through the About and Producer/Hub sign up pages and suggest improvements? Also looks for any confusing links. We've chatted about it in the past and would be good to sanity check it ive missed anything.

**Comment by MagsHall** [comment]
Looks good, one minor point - I would just clarify under Monthly Service Fees on the Producer / Hub sign up pages, that the monthly fees are 2% of turnover **on OFN**. Is it clearer to word it as 2% of all sales? 

Also, is it worth sticking in a paragraph on the About page about the subsidised funding from Esme? Would be another way of getting the word out there about it.

**Comment by lin-d-hop** [comment]
@MagsHall just testing your notifications are working

**Comment by MagsHall** [comment]
Yes! But I seem to be getting notifications about pretty much everything on Github, and I have to admit I don't read them all. Will go and edit my settings so I'm only getting notifications about mentions.

**Comment by sigmundpetersen** [comment]
Close @lin-d-hop @Matt-Yorkley ?

**Comment by RachL** [comment]
@lin-d-hop I'm closing this issue as it is looking done. Feel free to reopen if necessary.
