### ISSUE TITLE
Wrong admin interface for a producer 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9803]
## Description
In prod, shop 3902 has a different and wrong interface, with wrong translations, with products that don't have the name she set and other weird things..
She is on Google Chrome, we tried to empty her cache and reload, but it remains the same.

It's the same bug than the one I reported in #9700 , and her shop has been created by the same person (the owner of shop 890). He then set her as main owner.

Her shop was created around July/August, so it's very unlikely that it's an old interface..

## Expected Behavior
The admin interface should be the updated one.

## Actual Behaviour
The admin interface is very weird: 
- wrong translations of menu tabs and interface texts
- products are displayed with different names than the ones she set: for instance "spaghettis de courge" instead of "courges spaghettis"
- some units are displaying different names than the one that she set (for example "bouteilles" instead of "bottes")
- some stocks are in letters ("dix") instead of numbers ("10")

The producer is very unhappy because it's not a good look to have weird names on the shop (she said that it appeared on the shopfront).

She also had an issue with products that aren't in stock but appeared in her shop, but I think it was linked to the inventory, as I set inventory to "use producer stocks settings" seems to solve this problem.

## Steps to Reproduce
I don't know how to reproduce, because when I connect to her shop as a manager, I see the good interface. I guess the best would be to connect with her account (and also see shop 1080 account -  #9700 )

## What she sees
![image001](https://user-images.githubusercontent.com/28386648/196188726-69247f4f-df83-4adc-a838-8f1cebda2ea1.png)

## What she must see
<img width="1300" alt="Capture d’écran 2022-10-17 à 15 28 52" src="https://user-images.githubusercontent.com/28386648/196189762-e052ba00-4c58-4642-ae38-1d1496d300e3.png">

## What she sees
![image001(1)](https://user-images.githubusercontent.com/28386648/196188824-4b8d293a-2e50-4220-9814-840166a136fa.png)

## What she must see
<img width="1280" alt="Capture d’écran 2022-10-17 à 15 27 58" src="https://user-images.githubusercontent.com/28386648/196189530-0b0ca9cc-a035-4157-a469-c04ef3167380.png">

## What she sees
![image001(3)](https://user-images.githubusercontent.com/28386648/196189107-6fa49d57-ddc6-4b37-9615-4ac25701603a.png)

![image001(2)](https://user-images.githubusercontent.com/28386648/196189018-48587642-fbdb-458f-bd1f-0bf155ed9b55.png)

## Workaround
She was working and didn't have much time, so I didn't ask her to try with another browser. But maybe this would work

## Severity
s3?

**Comment by RachL** [comment]
@audez as we can't reproduce it's very unlikely we will have a fix for it :( If you happen to have her online again, the version of her google chrome could be interesting. 

This being said, I doubt that we will have the time / budget to issue a special fix for an old version of google chrome. So asking her to try a new browser could be the best short term option. It could also be that there is some extension coming into play. Trying with incognito mode could be a nice test as well, but I understand she won't have time for this.

**Comment by RachL** [comment]
@audez as super admin you can change her password. But you need to tell her the new one.

**Comment by audez** [comment]
ok thank you, i'll see with her if it's ok for her

**Comment by audez** [comment]
ok mystery resolved: it's not a browser version or cache problem. The thing is:
- You open coopcircuits.fr and chose "EN" language
- Then you ask Chrome to "translate in French" (when the popup opens or with a right click - translate)
- And you end up with a poorly translated interface... which is exactly the screenshots the 2 producers sent...
