### ISSUE TITLE
[Flaky] spec/system/admin/order_cycles/simple_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9805]
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage simple order cycles
 modify the minute of a order cycle with the keyboard, check that the modifications are taken into account
     Failure/Error: expect(page).to have_content "You have unsaved changes"
       expected to find text "You have unsaved changes" in "Logged in as : margaretta@priceweber.info Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUP
S USERS Admin Order Cycles NEW SCHEDULE NEW ORDER CYCLE QUICK SEARCH INVOLVING Any Enterprise SCHEDULE Any Schedule COLUMNS NAME SCHEDULES OPEN CLOSE COORDINATOR PRODUCTS None Enterprise 1 0 variants"
     
     [Screenshot Image]: /home/maikel/code/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_simple_order_cycles_modify_the_minute_of_a_order_cycle_with
_the_keyboard__check_that_the_modifications_are_taken_into_account_378.png

     
     # ./spec/system/admin/order_cycles/simple_spec.rb:712:in `block (2 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'
     # -e:1:in `<main>'

Finished in 16.7 seconds (files took 1.59 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/system/admin/order_cycles/simple_spec.rb:704 # 
```

Locally, I got a pass rate of 97%. So difficult to reproduce but it's definitely happening on CI from time to time.

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3265236711/jobs/5367132845

**Comment by sigmundpetersen** [comment]
I'm sorry but this failed again on the merge build https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3344082795/jobs/5538023567

**Comment by filipefurtad0** [comment]
Hahah - I spoke too early https://github.com/openfoodfoundation/openfoodnetwork/pull/9897#issuecomment-1294782679
:sweat_smile:

**Comment by filipefurtad0** [comment]
The bar is never really visible, when running on headless mode. Not even maximizing the screen. So I wonder if we should run such cases in larger screen size, by changing the config `window_size: [1200, 800]` on `cuprite_setup.rb`. I'll give it a try.

**Comment by sigmundpetersen** [comment]
Still failing https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3357761424/jobs/5563838680
