### ISSUE TITLE
[Matomo] Goals/funnels broken after removing general tracking code

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9818]
## Description

Goals/funnels broken after removing general tracking code.

## Expected Behavior

Goals and funnels should work as before, after the removal of the general tracking code.

## Actual Behaviour

Goals/funnels broken after removing general tracking code.

## Steps to Reproduce

Prod or staging test
1. Set up a goal
2. Assure it is triggered -> currently failing
3. Change those settings to contain funnels
4. Check the Funnels section and try to get out meaningful readings -> currently failing (no goals, hence no funnels!)

## Animated Gif/Screenshot

-

## Workaround

-

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: since v4.2.15
* Browser name and version: all
* Operating System and version (desktop or mobile): all

## Possible Fix

Setting goals using Tags

**Comment by filipefurtad0** [comment]
An S2 according to our processes, but maybe best to keep this one out of the In Dev column as I doubt it will require any changes in our code base - it should be a configuration issue. I've assigned myself.

**Comment by RachL** [comment]
@filipefurtad0 I don't know if usefull, or overkill, but perhaps we need a repo for analytics issues?

**Comment by filipefurtad0** [comment]
Hum, not sure we need a new repo :shrug:

Between a new Analytics column on our main repo or a shiny new one: which one do you think it would make more sense?

Having a new repo for Analytics that could allow to combine it the occasional need to make specific metabase/DB queries. So, for example, when anyone needs a query we could open issues in this repo, and have the SQL queries addressing it.

Thoughts?

**Comment by filipefurtad0** [comment]
Ok, as far as I could gather from my last interaction with customer support (transcribing):


> In the standard tracking code there is this particular entry (below) in the code to push  the page view
>
>_paq.push(['trackPageView']);
>
>Looking at your Tag Manager you do have some triggers for button click and order confirmation, what you need is a tag that triggers on any page view to duplicate the action above. You do have a similar trigger configured already (below screenshot) but it will only fire on the 'check out' page, so if you can create a trigger for 'page view' with no "optional" triggers it should push all page views.

Ok, so, having:

1. created a general trigger (optional part left empty):

![image](https://user-images.githubusercontent.com/49817236/196766722-51416d2b-bb40-4e3e-bed9-29d0e2660093.png)

2. And creating an tag for this trigger:

![image](https://user-images.githubusercontent.com/49817236/196768377-a2944509-1a1c-4a86-a39e-ecbdc903b21d.png)

Appending the preview code snippet on the URL and reloading the page seems to trigger the page view:

![image](https://user-images.githubusercontent.com/49817236/196768062-3f2523b2-340b-420f-84a1-599dc04f9618.png)

To do:
Still left to test is whether this correctly triggers the respective goals.

**Comment by filipefurtad0** [comment]
Alright - goals and funnels are back (on staging) :tada: 


**Goals**

![image](https://user-images.githubusercontent.com/49817236/197174899-f851ddda-aa70-4606-ac01-bb4c7b002eb8.png)

**Funnels**

![image](https://user-images.githubusercontent.com/49817236/197174733-0ff5471c-166f-4fed-9f9a-3e394e9f6eb8.png)


So, as a **summary**, we need:
- a trigger and respective tag for general page visits
- a trigger and respective tag for each goal
- (each goal has of course to have it's own funnel settings in place, as before)

Ping @BethanOFN - this should fix it. Once you've tried it in UK-production could you please drop me a line, if it worked out? I'll close the issue then. Please reach out if there is anything unclear - thank you!

**Comment by BethanOFN** [comment]
@filipefurtad0 I just need to check tomorrow once stats update to ensure that each goal is working correctly - I've got all of them working bar one so far, will update once finished thank you 👍

**Comment by BethanOFN** [comment]
@filipefurtad0 Bingo all working, thank you!

**Comment by filipefurtad0** [comment]
Very happy to hear!
Thank you so much for your feedback @BethanOFN :pray:

**Comment by filipefurtad0** [comment]
This seems not to be working yet for FR-prod. Re-opening.

**Comment by filipefurtad0** [comment]
Hum, so this does work in FR prod, but only for browsers explicitly allowing tracking - below Chrome, with the Tag set in debug mode:

![image](https://user-images.githubusercontent.com/49817236/199533075-4c828a66-ae8f-471a-a697-e73340524609.png)

**Comment by filipefurtad0** [comment]
I believe this is happening because FR-prod requires tracking consent, but has cookies disabled on the respective variable named `Matomo Configuration (OFN FR)`, - below, left:

![image](https://user-images.githubusercontent.com/49817236/199536109-db7243cb-9c9c-4646-8321-ee6aa2f607aa.png)

**Comment by RachL** [comment]
Hmmmm the guidelines I've followed in https://github.com/openfoodfoundation/wishlist/issues/1 don't mention this, but I guess it makes sense!
Good catch:)

**Comment by filipefurtad0** [comment]
We need to pin that post somewhere :-) https://github.com/openfoodfoundation/wishlist/issues/1 - I was looking for it before but could not find it.

Anyway, I think we're back on track:
![image](https://user-images.githubusercontent.com/49817236/199713191-b8e9b240-864b-4f29-a182-ed67b2f22656.png)

Closing.
