### ISSUE TITLE
Remove report_inverse_columns_logic feature toggle and fix some small display issues

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9821]
Following up https://github.com/openfoodfoundation/openfoodnetwork/pull/9706

## Description
**- As a:** admin or super admin
**- On page:** `/admin/reports`
**- I want to be able to see:** 

1. Remove "reports for bulk co-op orders" description and "reports for payments" description

2. Remove links from the left hand-side: this means that Orders and distributors and enterprise fee summary should be made on the right hand side (just repeat the text for now)

![image](https://user-images.githubusercontent.com/6525576/196654755-f68f5901-5f04-4947-9054-75f3cc67e587.png)

3. Add headers to reports pages using header style we have on other pages like: 

![image](https://user-images.githubusercontent.com/6525576/196655098-b1d58d89-1651-4867-8f0f-7729c37c326f.png)

4. Remove the feature toggle

## Acceptance Criteria & Tests

1. Login as admin
2.  See new column logic (old one does not exist anymore 🔥 )
3. See that all links are available on right hand side
4. See headers

**Comment by RachL** [comment]
@jibees is it ok to finish the work in one PR? Or should stuff like headers be handles separately?

**Comment by drummer83** [comment]
We have separated issues in wishlist already: #292, #293, #294. But #293 has slightly different specifications than this one here.

**Comment by RachL** [comment]
@drummer83 yes i know :) i'm trying to get the shortest road to remove the toggle :)

**Comment by jibees** [comment]
>  is it ok to finish the work in one PR?

All those 4 points are ok in the same PR.
