### ISSUE TITLE
[CI] Redis::CannotConnectError

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9825]
### What we should change and why (this is tech debt)

At times, our CI is failing spec runs with:

```
Failure/Error: raise CannotConnectError, "Error connecting to Redis on #{location} (#{error.class})"
     
     Redis::CannotConnectError:
       Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3280121563/jobs/5400516312

### Impact and timeline

A consistent build.

**Comment by mkllnk** [comment]
I'm wondering if we need to start Redis on CI. Two solutions:

* https://stackoverflow.com/a/67631989/3377535
* https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers

Not sure which one is quicker but avoiding the additional container sounds more performant.
