### ISSUE TITLE
Cache related bug - Product changes not saving

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#983]
I've heard from 2 users that product changes are not carrying through to the shopfront. Seems the system is drawing on old information.This was occurring for Theresa in Canada, I could see the bug (confirming it was not user error). Caching in Canadian SuperAdmin had this in the DIFF column - https://gist.github.com/sstead/b7a44bbb915aa589db27f12ac81d08fc

![image](https://cloud.githubusercontent.com/assets/10843056/15065350/1fcacaee-13a2-11e6-9ac4-f404262b1340.png)

@mkllnk please chat with Rohan about what needs to be done on the Canada server to fix this up.

**Comment by pmackay** [comment]
@sstead @mkllnk can you say what OFN version the Canada instance is running? Just to compare with UK related stuff.

**Comment by sstead** [comment]
1.6
________________________________

**Comment by OliverUK** [comment]
In the UK we reckon there is a delay but changes do come through eventually.

**Comment by NickWeir63** [comment]
Sometimes after I have made changes to products it seems to help to log out, close the window and then re-open it before checking the changes have been made in the shopfront.  But maybe as Oliver says this is just about the time delay.

**Comment by myriamboure** [comment]
Have we hear of any problem since May 2016? OK I will close that issue for now as it doesn't seem it has happened again, we will reopen if it does.
