### ISSUE TITLE
[Admin][Users] Snail (error 404) when generating/clearing API key after changing the option 'Show API key view for user'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9833]
## Description

While testing #9828 an error 404 (page not found) was observed when clicking the buttons 'generate key', 'clear key' or 'regenerate key' under certain conditions. This only happens after changing the checkbox setting 'Show API key view for user' or after clicking the 'Update' button, because the URL changes from `/admin/USER_ID/edit` to `/admin/USER_ID` (without `/edit`). As long as the latter URL is present, the action of the button will be carried out, but after that an error 404 will be displayed.

## Expected Behavior

No matter if the checkbox 'Show API key view for user' had just been changed or not or if the 'update' button was used, the buttons 'generate key', 'clear key' and 'regenerate key' should always work properly wihtout an error 404.

## Actual Behaviour

If the checkbox 'Show API key view for user' had just been changed or the 'update' button was used, the buttons 'generate key', 'clear key' and 'regenerate key' lead to an error 404.

## Steps to Reproduce

1. As super admin go to /admin/users/USER_ID/edit (for any user)
2. Toggle the 'Show API key view for user' checkbox or click the 'update' button
3. Observe that the URL now doesn't have the /edit anymore
4. Klick one of the API key buttons 'generate key', 'clear key' or 'regenerate key'
5. :boom: 

## Animated Gif/Screenshot

![Peek 2022-10-20 16-47](https://user-images.githubusercontent.com/1790176/196982000-3875708e-1fc3-4e06-874c-a346b0216d0b.gif)

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: staged [fc79612](https://github.com/openfoodfoundation/openfoodnetwork/commit/fc79612f26f2def50a4db6546ca9059f39fde37c)
* Browser name and version: Firefox 105
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS Desktop

## Possible Fix

Option 1: Make sure that the URL is always including /edit
Option 2: Make sure that the buttons work as well if the URL is without /edit

**Comment by dacook** [comment]
I was looking at this to triage if it was easy or hard.. and I fixed it instead 😄
