### ISSUE TITLE
Product creation: Further improvements of errors and mandatory information

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9834]
## What is the need / problem?
This is a follow-up of #9776.

Each of the following issues can be solved individually. There may be easy ones and hard ones. :wink: 

During product creation (page `/admin/products/new`) there are still some things that could be improved.
- [ ] If 'item' is selected as unit size and a value is entered in 'unit name', these values are not kept if product creation fails due to some other missing information (e.g. product name). This was missed in issue [#9067](https://github.com/openfoodfoundation/openfoodnetwork/issues/9067) and its pull request [#9177](https://github.com/openfoodfoundation/openfoodnetwork/pull/9177). Look at those for inspiration.
![Peek 2022-10-20 11-22](https://user-images.githubusercontent.com/1790176/196910132-da5dc014-14a2-4f2c-8a1a-7f9b67714e2f.gif)

- [ ] Add red highlighting of the input field's title (compare to field 'product name') for 'unit size' and 'product category'.
![image](https://user-images.githubusercontent.com/1790176/196911651-8b3edcd1-2192-4996-b46a-7a76c32cfa1c.png)

- [ ] Add red highlighting of the input field box and its title (compare to field 'producer name') for ''value' and 'unit name' (when 'item' is selected as 'unit size').
![image](https://user-images.githubusercontent.com/1790176/196911800-66a762d4-f780-436c-ba73-bc48cd7e69e6.png)

- [ ] Add a placeholder for 'supplier' instead of selecting the first option and make the field mandatory again (red star and highlighting if not selected): "Please choose a supplier" (or similar). See https://github.com/openfoodfoundation/openfoodnetwork/pull/9177#issuecomment-1158647656 for the discussion.
![image](https://user-images.githubusercontent.com/1790176/196990673-1f2aabf8-c6de-416d-8015-430556682cec.png)

- [ ] Improve the 'tax category' dropdown, see https://github.com/openfoodfoundation/openfoodnetwork/pull/9177#issuecomment-1158664475. Details are to be agreed upon before implementation!

- [ ] Make price mandatory and evaluate input: don't set it to 0.0 if invalid input but show error message instead. There might be a reason and a previous discussion about this (see https://github.com/openfoodfoundation/openfoodnetwork/pull/9177#issuecomment-1132635366).

- [ ] Keep the uploaded image, if product creation fails, see [#9297](https://github.com/openfoodfoundation/openfoodnetwork/issues/9297).

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Producers
- Instance Managers

**Comment by ijdershem** [comment]
@drummer83 Is this an issue I could jump on?

**Comment by drummer83** [comment]
Sure, @ijdershem!
You can tackle these step by step. No need to solve everything at once! 👍🏻

**Comment by RachL** [comment]
Hello @ijdershem Just checking in: are you still working or planning to work on this? Don't hesitate to ask for help if you are stuck :)

**Comment by RachL** [comment]
Ah sorry I just saw your comment on https://github.com/openfoodfoundation/openfoodnetwork/issues/9870#issuecomment-1312910845

**Comment by ijdershem** [comment]
> Ah sorry I just saw your comment on [#9870 (comment)](https://github.com/openfoodfoundation/openfoodnetwork/issues/9870#issuecomment-1312910845)

I am working on it! I think I’ve got the first part figured but I’m visiting family for the next two weeks so wont be able to work on the other sections.

Happy to open a PR for the first part of this issue though if you wanted this to be moved along!

**Comment by ijdershem** [comment]
@RachL Sorry for the delay on this one but I plan to work on it in the next few days. I do have the first objective completed if you want to have that merged in sooner rather than later!

**Comment by ijdershem** [comment]
@RachL Regarding this comment https://github.com/openfoodfoundation/openfoodnetwork/pull/9177#issuecomment-1158664475: 

It looks like we already have a 'None' option for 'Tax Category' which appears to be a valid selection i.e no tax category. 

Is there a proposed solution for the "Improve 'tax category' dropdown task on this issue? I saw there was some discussion about requiring 'tax category' when the selected 'supplier' is subject to taxes but it sounds like we aren't at the point where we would be able to hit that best case scenario yet. Is that still true?

**Comment by RachL** [comment]
Hi @ijdershem yes still true/ there isn't a well written solution yet: I suggest you move forward without this item, it will be a great improvement already :+1:

I suppose also it might be hard to do the last one: 

- Keep the uploaded image, if product creation fails, see https://github.com/openfoodfoundation/openfoodnetwork/issues/9297

I think this deserves an entire new issue.

**Comment by ijdershem** [comment]
> Hi @ijdershem yes still true/ there isn't a well written solution yet: I suggest you move forward without this item, it will be a great improvement already 👍
> 
> I suppose also it might be hard to do the last one:
> 
> * Keep the uploaded image, if product creation fails, see [Create product: Keep the uploaded image when product creation fails due to missing information #9297](https://github.com/openfoodfoundation/openfoodnetwork/issues/9297)
> 
> I think this deserves an entire new issue.

@RachL Sounds good! Thanks for the follow up. Regarding https://github.com/openfoodfoundation/openfoodnetwork/issues/9297 Would you be able to assign this to me and I can take a look?

**Comment by RachL** [comment]
It looks like this can be closed now as there are issues for the remaining bits. In the future, it might be best to create issues for each small bit, it is a bit hard to trace all links to various PR :sweat_smile:

**Comment by RachL** [comment]
sorry last PR not merged actually.

**Comment by ijdershem** [comment]
Whoop whoop! Thanks for all the QA and code review on this one 🙂
