### ISSUE TITLE
Shipping methods fees: improve validation of input

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9836]
## Description

These are little leftovers from #9756.

On pages `/admin/shipping_methods/new` and `/admin/shipping_methods/_ID_/edit` there is still room for improvement.

- For fee calculator 'Flexible rate' the 'max items' value is not validated as other fields, but it is set to '0' for invalid input while for 'Price sack' the amount values are validated as other fields and the error message is displayed for invalid input. Flexible rate should do the same.
- After clicking 'update' or 'create' invalid input field(s) should be highlighted (red border of input field) and all other updated information should be kept (including description, tags, display, ...). Currently changes are lost and have to be entered again.

## Expected Behavior

- All input data should be validated.
- There should be an error message when invalid data is submitted.
- Invalid data should be highlighted.
- Updated information should be kept when submission of the form fails.

## Actual Behaviour

- Not all input data is validated.
- There is no error message when invalid data is submitted in the field 'max items' of the 'Flexible rate' calculator.
- Invalid data is not highlighted.
- Updated information is lost when submission of the form fails.

## Steps to Reproduce

Changing a shipping methods fee with 'Flexible rate':
1. As enterprise user or super admin user go to `/admin/shipping_methods/_ID_/edit`
2. Select the 'Flexible rate' calculator and click 'update'
3. Update some fields (e.g. description) - do not click update yet
4. Type invalid information into the 'max unit' field (e.g. the text 'invalid')
5. Click 'update'
6. See that the invalid value is set to 0

Changing any shipping method:
1. As enterprise user or super admin user go to `/admin/shipping_methods/_ID_/edit`
2. Select any calculator and click 'update'
3. Update some fields (e.g. description) - do not click update yet
4. Type invalid information into any calculator field (e.g. the text 'invalid' in the 'amount' field)
5. Click 'update'
6. See that the updated information is lost
7. See that is no highlighting of the invalid input

Repeat for setting up new shipping methods.

## Animated Gif/Screenshot

![Peek 2022-10-20 12-10](https://user-images.githubusercontent.com/1790176/197003231-bbc5b203-d550-4d70-86ed-4e5c2f626fd2.gif)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
Hi @ashwini-seshadri 👋 
Sure, I'll assign to you ;)

**Comment by ashwini-seshadri** [comment]
Hi, just an FYI, I was a bit caught up with some uncertain personal things, I have started to work on this today and hopefully, will be able to create a PR soon! 🙏🏾

**Comment by RachL** [comment]
No worries @ashwini-seshadri ! thanks for the update :)

**Comment by sigmundpetersen** [comment]
Hi there @ashwini-seshadri how are you 👋 
Will you be able to continue on this or should we unassign for now?

**Comment by ashwini-seshadri** [comment]
Hello @sigmundpetersen 
Sorry I couldn't post the updates. I am doing this. I will submit the PR by the end of the day!
Thanks! 🙏🏾

**Comment by sigmundpetersen** [comment]
Thank you @ashwini-seshadri 👏

**Comment by RachL** [comment]
Hello @ashwini-seshadri sorry to ping you again, but we just want to be sure: are you still working on this?

**Comment by ashwini-seshadri** [comment]
Hi @RachL Sorry I didn't get back, I got caught up with some unforeseen situation and had to travel without my system.
Yes I have worked on it, I will submit it! 🙏🏾

**Comment by RachL** [comment]
No worries :) Glad you are ok!

**Comment by mkllnk** [comment]
@ashwini-seshadri Any update on this?

**Comment by sumedhavs** [comment]
Hi, I would like to work on this issue!

**Comment by mkllnk** [comment]
Okay, I assigned you. Have a look at similar work:

* https://github.com/openfoodfoundation/openfoodnetwork/pull/10329

**Comment by dacook** [comment]
I just tested and I think this is now covered by the above PR.

1.  **Validating fee calculator numeric fields:** this was resolved by using native html numeric inputs. This prevents the user from entering invalid values in the first place.
2. **Remembering shipping method changed values when calculator is invalid**: I think this is no longer relevant, because the calculator can't be invalid.

That change hasn't been confirmed by testing or merged yet though.

I did discover a problem:
1. Edit shipping method `/admin/shipping_methods/*/edit`
2. Remove name or description - don't click update yet
3. Change calculator by selecting a different item in the list
4. Click update
5. 💥 `ActiveModel::UnknownAttributeError`

So I think we should pause this until the above  PR has been confirm, then re-evaluate. There might be relevant bits to copy, which `@thejwuscript` may be able to advise about.

**Comment by thejwuscript** [comment]
@dacook I think the problem you had is resolved? I followed the steps and couldn't reproduce it.

**Comment by dacook** [comment]
Oh, that's good news!
So now that https://github.com/openfoodfoundation/openfoodnetwork/pull/10329 is merged, I think this is ready to work on. 

@sumedhavs I'm wondering if you are, or planning to work on this?

**Comment by jibees** [comment]
Hi @sumedhavs 
I unassigned you, but feel free to ask if you want to work on it!

**Comment by drummer83** [comment]
Hi @dacook,
Thanks for following up!
Yes, I can confirm that the original issues described here as well as the one you found are solved in our current master (https://github.com/openfoodfoundation/openfoodnetwork/commit/c1587b689aae7ba50970ceb2d4be57ced3e012bf).
Closing this one. :+1:
