### ISSUE TITLE
On checkout page, Checkbox Label is clickable but not active.

### ISSUE THREAD

**Issue by Jaxom99** [openfoodfoundation/openfoodnetwork#9845]
Hello,
I report here for lack of other channel, but I think it's a bug report for the french instance CoopCircuits.

## Description

On the checkout page, with my order filled, the last step to confirm order is "accept CGU". This step is a simple checkbox with a sentence as label : "accept the [link-to-CGU](CGU)".
The mouse cursor changes when you hover the label, so it looks like you can click on it.

## Expected Behavior
When I click the label the associated checkbox should be checked.

## Actual Behaviour
When I click the label, nothing happens.
I have to click on the (quite small) checkbox itself so as to check it and proceed to the "confirm order" button.

## Steps to Reproduce

1. Place an order on any shop, such as https://coopcircuits.fr/connexion-paysanne1/
2. See the checkout page : https://coopcircuits.fr/checkout

## Severity
I would go with : 

- bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: Not known
* Browser name and version: Firefox 105.0.3 and previous
* Operating System and version (desktop or mobile): Desktop Linux Debian 11.

## Possible Fix
Minor change to HTML code in the page :)

**Comment by ijdershem** [comment]
@RachL Happy to take a look at this one in the next few days!

**Comment by sigmundpetersen** [comment]
Great, thank you @ijdershem 🎉 
And welcome to OFN!

**Comment by Jaxom99** [comment]
Thank you for this quick fix @ijdershem :wink:
