### ISSUE TITLE
When shopfront displays multiple property filters please replace '&' with 'OR'

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#985]
On the screenshot below I can see products that are produced within 15 miles and I can see products that are certified biodynamic.  However most of these products do not fit BOTH these properties.  It would be great if the message top left could be changed from
Showing: Certified Biodynamic & Produced within 15 miles
to
Showing: Certified Biodynamic **OR** Produced within 15 miles
Ideally with the '**OR**' in bold, capitals, underlined, whatever to emphasise it
Thanks
![screenshot 2016-05-07 15 33 06](https://cloud.githubusercontent.com/assets/10517702/15092701/b009705c-1469-11e6-9f43-0d2fb25ce74c.png)

**Comment by lin-d-hop** [comment]
This is going to take more thought and discussion. Both AND and OR functionality are useful and I suspect users in other places would not want the sudden change.
@myriamboure @oeoeaio @sstead Any thoughts?

**Comment by sstead** [comment]
We're not worried about users getting confused by changes to the text. You're right Nick, OR is a more accurate description of what the filter is doing. Note that the & between the Taxons should also be changed to OR... for this scenario... 
![image](https://cloud.githubusercontent.com/assets/10843056/15170184/0515c5b2-1787-11e6-8b44-9ae96d7b0c57.png)

**Comment by yorkfrog** [comment]
Hi, Is anyone currently working on this issue?  I would like to pick it up as a first issue.  Colin

**Comment by sauloperez** [comment]
Nope. Go for it @yorkfrog

**Comment by myriamboure** [comment]
Sorry just had a look at it as @yorkfrog was going to work on it, I'm wondering @NickWeir63 and @sstead I understand about replacing "&" by "or" for the properties, but intuitively the user will see displayed the "fruits" AND the "nuts" on the page (also no product can be in two categories) that are either with the first or second property, so I propose to leave "&" for product categories filter and only change the first one. If you disagree please shout.
@yorkfrog keep in mind that this "OR" that you introduce needs to be translatable through transifex so that non-english instances can translate to their language ;-)

**Comment by sauloperez** [comment]
I might feel a bit overwhelming @yorkfrog but https://github.com/openfoodfoundation/openfoodnetwork/wiki/i18n might help you a bit on what @myriamboure mentioned.

**Comment by NickWeir63** [comment]
Yes I agree with @myriamboure 's amendment  - thanks all

**Comment by yorkfrog** [comment]
Great, thanks @myriamboure for the clarification.  @sauloperez, I was looking at the i18n stuff for one of the other bugs I was considering (may be next) so should be fine, but will checkout that page and shout if I need help.  
Checked in en.yml and there is already a translation for 'or' (en:or).  Is it ok to use that, or do you do single translation per use on screen in case things get changed later?

**Comment by sauloperez** [comment]
> do you do single translation per use on screen in case things get changed later?

yes, we do that. We favor the added changeability over the duplication.

**Comment by yorkfrog** [comment]
@NickWeir63, @myriamboure - are you happy with this format?
![image](https://user-images.githubusercontent.com/31819562/37920859-f244eddc-311f-11e8-83ca-095ed1d181c7.png)
The 'OR' is an i18n entry that can be translated.

**Comment by myriamboure** [comment]
@NickWeir63 are you happy? It looks good to me, thanks @yorkfrog :-)

**Comment by NickWeir63** [comment]
Yes I am very happy with this @yorkfrog - thank you very much

**Comment by yorkfrog** [comment]
Submitted change on PR [#2204](https://github.com/openfoodfoundation/openfoodnetwork/pull/2204)

**Comment by kirstenalarsen** [comment]
is this closed @mkllnk @myriamboure ?

**Comment by sigmundpetersen** [comment]
No @kirstenalarsen, follow the connected PR to see state. There are changes requested from the reviewers.

**Comment by tywestlie** [comment]
Hi there! Mind if I take a crack at this issue?

**Comment by yorkfrog** [comment]
Hi @tywestlie, I'm happy for you to go for it.  I solved the problem (see PR #2204) but will need to be rebased.  As I remember, the outstanding work to was to add some tests around that code.  Good luck. Colin

**Comment by daniellemoorhead** [comment]
Welcome @tywestlie! It would be most awesome if you could finish up the last little bit of what was missing from @yorkfrog's PR and we can get it merged. That would be a win-win-win 😄
