### ISSUE TITLE
[Admin][Enterprise Fees] Improve validation of input

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9860]
## Description

These are little leftovers from #9791 and exactly the same as #9836 for shipping methods. Maybe the code can be referenced instead of copying it?

On page `/admin/enterprise_fees` there is still room for improvement.

- For fee calculator 'Flexible rate' the 'max items' value is not validated as other fields, but it is set to '0' for invalid input while for 'Price sack' the amount values are validated as other fields and the error message is displayed for invalid input. Flexible rate should do the same.
- After clicking 'update' or 'create' invalid input field(s) should be highlighted (red border of input field) and all other updated information should be kept (including changes on other existing enterprise fees). Currently changes are lost and have to be entered again.

## Expected Behavior

- All input data should be validated.
- There should be an error message when invalid data is submitted.
- Invalid data should be highlighted.
- Updated information should be kept when submission of the form fails.

## Actual Behaviour

- Not all input data is validated.
- There is no error message when invalid data is submitted in the field 'max items' of the 'Flexible rate' calculator.
- Invalid data is not highlighted.
- Updated information is lost when submission of the form fails.

## Steps to Reproduce

Creating or changing an enterprise fee with 'Flexible rate':
1. As enterprise user or super admin user go to `/admin/enterprise_fees`
2. Select fee type, enter a name and select a tax category
3. Select the 'Flexible rate' calculator and click 'update'
4. Type invalid information into the 'max unit' field (e.g. the text 'invalid')
5. Click 'update'
6. See that the invalid value is set to 0

Creating or changing any shipping method:
1. As enterprise user or super admin user go to `/admin/enterprise fees`
2. Fill in required field, select any calculator and click 'update'
3. Update some fields (e.g. description) - do not click update yet
4. Type invalid information into any calculator field (e.g. the text 'invalid' in the 'amount' field)
5. Click 'update'
6. See that the updated information is lost
8. See that is no highlighting of the invalid input

## Animated Gif/Screenshot

![Peek 2022-10-24 22-02](https://user-images.githubusercontent.com/1790176/197618016-1adad831-8f1a-4e96-9cdf-d66381381e86.gif)

![Peek 2022-10-24 22-01](https://user-images.githubusercontent.com/1790176/197617813-cfcb4eac-bc78-433c-a7ad-e41c57358618.gif)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by brolinr** [comment]
Can I work on this one

**Comment by brolinr** [comment]
I resolved the issue. Here is the pull request [https://github.com/openfoodfoundation/openfoodnetwork/pull/9960](url)

**Comment by HillaryOkello** [comment]
Can I work on the changes in the PR for this?

**Comment by drummer83** [comment]
Hi @HillaryOkello and welcome!

Sure, I will assign you to the issue and the prepared PR.

Thanks for your contribution!

**Comment by drummer83** [comment]
I can't assign you to the PR but please go ahead.

**Comment by HillaryOkello** [comment]
Hi @drummer83 I tried to reproduce the issue but it seems to be fixed. We cannot type invalid information into any calculator field because of the number format of the field. Could there be something else that is needed that I haven't understood, please?

**Comment by drummer83** [comment]
Hi @HillaryOkello,
Thanks for getting in touch. I have tried to reproduce the issue as well and it seems that it has been fixed in the meantime already. Great catch!!
Sorry for the confusion! If you like you are very welcome to pick a different issue.
I will close this one here.
Thanks again!
