### ISSUE TITLE
Payment methods fees: improve validation of input

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9861]
## Description

These are little leftovers from #8204, very similar to #9836.

On pages `/admin/payment_methods/new` and `/admin/payment_methods/_ID_/edit` there is still room for improvement.

- After clicking 'update' or 'create' invalid input field(s) should be highlighted (red border of input field) and all other updated information should be kept (including description, tags, display, ...). Currently changes are lost and have to be entered again.

## Expected Behavior

- Invalid data should be highlighted.
- Updated information should be kept when submission of the form fails.

## Actual Behaviour

- Invalid data is not highlighted.
- Updated information is lost when submission of the form fails.

## Steps to Reproduce

Changing any payment method:
1. As enterprise user or super admin user go to `/admin/payment_methods/_ID_/edit`
2. Select any calculator and click 'update'
3. Update some fields (e.g. description) - do not click update yet
4. Type invalid information into any calculator field (e.g. the text 'invalid' in the 'amount' field)
5. Click 'update'
6. See that the updated information is lost
7. See that is no highlighting of the invalid input

Repeat for setting up new payment methods.

## Animated Gif/Screenshot

This is showing shipping methods instead of payment methods:
![Peek 2022-10-20 12-10](https://user-images.githubusercontent.com/1790176/197003231-bbc5b203-d550-4d70-86ed-4e5c2f626fd2.gif)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
Hi @Lz-01 
And welcome on board! 🤗 
I'll assign this to you ;)

**Comment by RachL** [comment]
Hello @Lz-01 Just checking : are you still working or planning to work on this issue? Don't hesitate if you need help!

**Comment by thejwuscript** [comment]
I'd like to work on this issue.

**Comment by sigmundpetersen** [comment]
Yes, thank you @thejwuscript 👍 I've assigned you.
Don't hesitate to ask if you have any questions!

**Comment by thejwuscript** [comment]
I'm looking for some clarification:

1. Upon form submission with invalid inputs and valid inputs, would you like valid data to be saved to the database at first? Or would you like "all-or-nothing" approach, where all data must be valid before saving anything to the database?
2. How should the error message be displayed? Originally it was a Flash message that disappears in a few seconds, but I am considering to have a red box near the top of the page like the one in the screenshot:
![error message](https://user-images.githubusercontent.com/88938117/208956907-5be18f15-00a5-4efc-b871-331f9dc00f84.png)
3. For invalid fields, should it be populated and displayed with the previously valid input or the invalid input?
4. I am planning to write system specs in ``` ./spec/system/admin/payment_method_spec.rb ``` . Is it the right file?

Thanks in advance.

**Comment by RachL** [comment]
Hi @thejwuscript 

Here are some answers: 

2. Great idea with the red box! Let's do that.

3. Keep the invalid input

For 1 and 4 I can't answer as I'm not a dev, but perhaps one of our @openfoodfoundation/core-devs can :-)

**Comment by jibees** [comment]
Hi 👋 

1. We clearly are in a "all-in-one" solution currently. Let's continue for now ;)
2. Yes, should be the right file!

Thanks!
