### ISSUE TITLE
Corrupt image files are accepted and raise errors later

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#9863]
## Description

A user can upload files which are named like example.jpg but are not valid images. A [new version of active_storage_validations](https://github.com/openfoodfoundation/openfoodnetwork/pull/9849) can now check this, too.

## Expected Behavior

Uploading a non-image file as image should display an error straight away.

## Actual Behaviour

The upload succeeds but the image can't be displayed

## Steps to Reproduce

1. Create a text file.
2. Change the filename ending to `.jpg`.
3. Upload the .jpg file as product image.
4. Visit the shopfront to see the product image.

## Workaround

Upload a valid image.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Add `processable_image: true` to all image validations as described in https://github.com/igorkasyanchuk/active_storage_validations/pull/168/files.

**Comment by zafar-hussain** [comment]
hi @mkllnk,

Please assign this issue to me,

cheers

**Comment by zafar-hussain** [comment]
hi @sigmundpetersen,

Thanks for assigning this issue to me.

Please, if you can have a look at my PR and advice.

If all is well,  can you please add "hacktoberfest-accepted label"

cheers

**Comment by sigmundpetersen** [comment]
Hi @zafar-hussain 
The PR will be reviewed by one of our devs 👍 

Since the issue has the hacktoberfest label and the repo has the hacktoberfest tag, I think the PR will be counted towards hacktoberfest once approved and merged.
Maybe @RachL has some further insights into this process.

BR

**Comment by RachL** [comment]
Yes that's it :+1:

**Comment by saunmanoj888** [comment]
hii @sigmundpetersen 
The PR for this issue was closed. Can I work on this and try to fix the specs and create the PR again?

**Comment by sigmundpetersen** [comment]
Yes, of course @saunmanoj888 💪 
Thanks a lot!

**Comment by sigmundpetersen** [comment]
Hey @RachL why was this moved?

**Comment by RachL** [comment]
@sigmundpetersen ah sorry I've only checked the PR and didn't understood why we had a closed PR in dev

**Comment by saunmanoj888** [comment]
thanks will continue to work this weekend and raise the PR
