### ISSUE TITLE
[Product import] Incorrect error message when different variant unit names

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9870]
## Description
When importing a .csv with products with 2 variants, and putting 2 different variant_unit_name, the error message is incorrect and misleading.

## Expected Behavior
The error should be "Variants units of the same product must be the same. Please correct the variant_unit_name field."

## Actual Behaviour
The error is: " -  Variant_unit_name cannot be updated on existing products via product import "
Whereas it can be the first time you import the products and they don't exist yet.

## Steps to Reproduce
In Product Import page (admin/product_import), import a csv file with two variants having different variant_unit_name
Example file:
[mollusquus.csv](https://github.com/openfoodfoundation/openfoodnetwork/files/9946820/mollusquus.csv)

## Animated Gif/Screenshot
![Screen Shot 2022-10-25 at 14 01 19](https://user-images.githubusercontent.com/28386648/197768423-591f7017-0736-41e7-806a-eab406d5d3e5.png)

## Severity
bug-s4: it's annoying, but you can use it

**Comment by audez** [comment]
it's not that actually

**Comment by audez** [comment]
Yes it's just to link them as they're similar, so the person doing one can do the other if they want to

**Comment by ijdershem** [comment]
@audez Happy to take a look at this one if it's open!

**Comment by sigmundpetersen** [comment]
Sure @ijdershem go ahead! Thanks 🎉

**Comment by ijdershem** [comment]
> Sure @ijdershem go ahead! Thanks 🎉

@sigmundpetersen I'm hung up working on https://github.com/openfoodfoundation/openfoodnetwork/issues/9834 currently so if it would make sense to unassign this from me in case anyone else wants to swoop in feel free! Happy to keep it assigned as I hope to get to it once I'm unstuck on #9834

**Comment by sigmundpetersen** [comment]
Yes, don't worry 🙂 We can leave them both assigned to you, and you work on them at your pace.
There are a lot of open issues to choose from, so we don't need this one available to others right now 👍 

Thanks for the update!

**Comment by ijdershem** [comment]
@audez @RachL It looks like we have a pretty locked format for displaying errors in the following format
`{attribute_name} {error_message}`
e.g.
`Variant_unit_name cannot be updated on existing products via product import` 

Where `attribute_name` is `Variant_unit_name` and `error_message` is `cannot be updated on existing products via product import`

We could refactor the way these error messages are displayed but it may be more work than it's worth. That said, would you be open to this format? 

`Variant_unit_name must be the same for products with the same name.`

This would allow us to maintain our current structure for generating and displaying error messages and would provide some additional clarity by explicitly identifying the fact that `variant_unit_name` must match products with the same name (as opposed to 'the same product' in the suggested error message: "Variants units of the same product must be the same. Please correct the variant_unit_name field.").

**Comment by RachL** [comment]
HI @ijdershem this looks good to solve the issue indeed let's not dive into a huge refactor now :+1:
