### ISSUE TITLE
[retry-spec] Flaky specs tagged with the "retry" option

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9871]
### What we should change and why (this is tech debt)

An epic grouping flaky specs tagged with the "retry" option.

### Context

This came up [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9831#pullrequestreview-1154699889).

### Impact and timeline

No more flaky specs.

**Comment by sigmundpetersen** [comment]
Can we close this @filipefurtad0 ?
I'm not sure I understand it completely, is the purpose to have issues with the specs containing the retry option?

**Comment by filipefurtad0** [comment]
Yes that was it @sigmundpetersen , but I think it is perhaps an overkill to track these in individual issues. So I'd agree to close this epic. As of now, we have retry on three spec files:

[~/openfoodnetwork/spec/system/admin/bulk_order_management_spec.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/a0050693943f971189e5d8666085e6f2c6ad4647/spec/system/admin/bulk_order_management_spec.rb#L649):

- in several lines/examples.

[~/openfoodnetwork/spec/system/admin/shipping_methods_spec.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/a0050693943f971189e5d8666085e6f2c6ad4647/spec/system/admin/shipping_methods_spec.rb#L115):

- in line 115:     it "creating a shipping method", retry: 3 do


[~/openfoodnetwork/spec/system/admin/order_cycles/complex_creating_specific_time_spec.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/a0050693943f971189e5d8666085e6f2c6ad4647/spec/system/admin/order_cycles/complex_creating_specific_time_spec.rb#L52):

- in line 52:   xit "creating an order cycle with full interface", retry: 3 do

Still, maybe good to keep track of this. Perhaps a regular issue would do as well (to be added to the Automated tests column)?
