### ISSUE TITLE
Order cycle creation: Needless warning and lost data when leaving and saving

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9874]
## Description

During complex order cycle creation there are warnings when leaving the page without saving the data. However this isn't applied on all steps and sometimes the warning is shown even when no data was changed. Also the 'save' buttons should only be active when data was changed and needs to be saved.

- Leaving step 3 of complex order cycle asks to confirm to leave the page even when no data was changed.
- Leaving step 4 of complex order cycle DOESN’T ask to confirm to leave the page even when data was changed (the change is lost without notice).
- The buttons ‘save’ and ‘save and back to list’ should only be active when data was changed.

## Expected Behavior

- Leaving any step of order cycle creation should NOT warn the user if NO data has been changed.
- Leaving any step of order cycle creation SHOULD warn the user IF data has been changed.
- The buttons ‘save’ and ‘save and back to list’ should only be active if data was changed.

## Actual Behaviour

- Leaving step 3 of complex order cycle asks to confirm to leave the page even when no data was changed.
- Leaving step 4 of complex order cycle DOESN’T ask to confirm to leave the page even when data was changed (the change is lost without notice).
- The buttons ‘save’ and ‘save and back to list’ are always active on step 3 and 4.

## Steps to Reproduce

1. Create an order cycle for a hub (sells = any)
2. Proceed through all steps and save
3. Edit the order cycle
4. Proceed to step 3, don't change anything and the click on step 1, 2 or 4 --> the warning will be shown
5. Proceed to step 4, change data and then click on step 1, 2 or 3 or any other page --> there will be no warning, data will be lost
6. Observe the buttons 'save' and 'save and back to list' while editing an order cycle

## Animated Gif/Screenshot

![Peek 2022-10-25 15-45](https://user-images.githubusercontent.com/1790176/197790533-74075e45-f7c4-41b7-bde0-183bbd10af15.gif)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by krishnasingh001** [comment]
Hello @drummer83  I would like to work on this one. Could you please assign it to me?

**Comment by drummer83** [comment]
Sure, @krishnasingh001! And welcome!
I will assign it to you!

**Comment by drummer83** [comment]
Sure, @krishnasingh001! And welcome!
I will assign it to you!

**Comment by RachL** [comment]
@drummer83 is this issue still happening?

**Comment by drummer83** [comment]
@RachL Yes, it is.

**Comment by rioug** [comment]
> The  buttons ‘save’ and ‘save and back to list’ should only be active when data was changed.

This is a bit confusing when creating a new order cycle as you end up with no way of saving the new order cycle on the last step. Technically speaking it is already saved, but the user most likely doesn't know/realise that. I kept the existing behaviour.
