### ISSUE TITLE
[Admin][Reports] Columns names not translated in packing and Xero reports

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9944]
## Description
Since the new column selection feature ( #9830), columns names are not translated in admin language for **packing reports** and **Xero reports**. 

## Expected Behavior
Column names should be displayed in the admin language.

## Actual Behaviour
Column names are not translated.
For instance, when you are on the French dashboard, if you open the packing report, you will see the column names in English. This has been noticed by a French customer who says it's hard to make the selection because they're not bilingual.

For packing reports only, the translated columns names appear after generating the report.

## Steps to Reproduce
1. Connect to the French instance, choose FR language
2. Open Packing reports (admin/reports/packing) or Xero reports (admin/reports/xero_invoices/summary)
3. Click on the dropdown "Columns". Names appear in EN
4. Generate the report. Names now appear in FR for packing reports

### Packing report 
![Screen Shot 2022-11-07 at 11 06 46](https://user-images.githubusercontent.com/28386648/200283445-46f230dc-f0f5-4e14-96ed-ad48a9061a3c.png)

### Packing report after generating a report
![Screen Shot 2022-11-07 at 10 59 21](https://user-images.githubusercontent.com/28386648/200283518-46b89569-0fe2-434c-93b3-bc8ec55afd40.png)

### Xero report
![Screen Shot 2022-11-07 at 10 55 59](https://user-images.githubusercontent.com/28386648/200283575-4ee97d26-8b7d-4606-86f5-ce9406f6dc47.png)

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by jibees** [comment]
@audez, do you confirm that for `/admin/reports/xero_invoices/summary` columns are not translated neither for the widget component:
<img width="516" alt="Capture d’écran 2022-11-07 à 11 44 45" src="https://user-images.githubusercontent.com/296452/200291536-eea173cc-bc70-4750-9036-231520f8e58f.png">

nor for the report itself:
<img width="1486" alt="Capture d’écran 2022-11-07 à 11 44 38" src="https://user-images.githubusercontent.com/296452/200291594-6bec8fc2-1465-4386-81bc-c9338449db96.png">


For the report `/admin/reports/packing`, columns aren't translated for `json`, `xlsx` and `csv` format, which is _normal_ (avoid breaking changes, see commit: https://github.com/jibees/openfoodnetwork/commit/b7991e5ae853f2bdc8fcfb5c7537f8260caa0003) ; but should be translated when requesting the page itself, in the small columns selection component. Will open a PR for that.

**Comment by jibees** [comment]
For the Xero columns, I can see a comment that specify that: 
```
 # These are NOT to be translated, they need to be in this exact format to work with Xero
```

I'm not sure this was translated before I made the changes in https://github.com/openfoodfoundation/openfoodnetwork/pull/9830 ;)

**Comment by audez** [comment]
@jibees for Packing report: for the report itself, they are well translated when generating on screen, so the issue is only in the widget. 
Indeed in the csv they aren't translated, as it was before.
![Screen Shot 2022-11-07 at 12 31 58](https://user-images.githubusercontent.com/28386648/200300413-3a0f23c4-a70f-4ce3-ad30-3c45ec369193.png)

OK for the Xero 👍
