### ISSUE TITLE
Invite user to manage enterprise profile

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#996]
This is part of http://community.openfoodnetwork.org/t/useability-of-e2e-link-management/102

**Comment by myriamboure** [comment]
Closing as this is covered in icebox https://community.openfoodnetwork.org/t/hubs-can-easily-navigate-back-office-and-manage-their-shopfront/1246 and I think even more in email confirm https://github.com/openfoodfoundation/openfoodnetwork/pull/2138
