### ISSUE TITLE
Get Producer and Product tax status in Order Cycle Supplier Totals Report

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#9962]
## Description

**- As a:** Enterprise (Hub)
**- On page:** Reports: Order Cycle Supplier Totals
**- I want to be able to:** easily identify the correct tax that needs to be reported in payments to Producers. 

In the OC Supplier Totals report I want to know if the Producer is registered for tax, and if the product is taxable. This information is contained in the Producer profile (in Aus 'Charges GST - Yes or No' in Enterprise Settings) and the Tax Category connected with the Product. 

## Acceptance Criteria & Tests
1. Add two new columns to the Order Cycle Supplier Totals reports For each line item we wish to display. These will be translatable fields: 'GST/VAT Registered' and 'Product Tax Category'.
2. Columns to be added to the end of each row.
3. 'GST/VAT Registered' will display true if the producer has 'Charges GST/VAT' enabled.
4. 'Product Tax Category' will display the tax category of the product. Consistent to other areas of the UI if no tax category is preset, 'None' is rendered.
5. For testing we wish to test each permutation (at least 4, though you  might want to test for multiple tax categories too).
6. These columns to be hidden by default in UI. API will return all data 'columns'.
7. All fields translatable
8. Unit test to cover this functionality.

**Comment by lin-d-hop** [comment]
@abdellani Apologies but there was a missing acceptance criteria from this issue.

We also need to have these columns Hidden by Default.
Let me know if you'd like me to explain that more - I hope it's clear in the code that some columns are displayed by default and some are hidden.

Thanks for your patience with this late addition of acceptance criteria :pray:

**Comment by abdellani** [comment]
@lin-d-hop 
No worries :)
I think I already know how to do that.

**Comment by kirstenalarsen** [comment]
When columns are hidden by default are they still included in API response?
Or is there a parameter needed to include them? Just checking so we can put
this into immediate use! Thanks!

**Comment by lin-d-hop** [comment]
Good question. API should return everything. This is something for acceptance criteria.

**Comment by abdellani** [comment]
@lin-d-hop 
Hitting the `Go` button will trigger a POST request with a payload that lists the `fields_to_show`.
The response will be an HTML document that includes exclusively the selected columns.
How will it be possible to return everything?

![image](https://user-images.githubusercontent.com/16113997/202631123-fbf3de48-8c56-47d7-8db4-6d12cf75f3ff.png)

**Comment by lin-d-hop** [comment]
Hi @abdellani 
The API is exposed without hitting the Go button. You should just be able to call reports endpoints at any time and all of this should be automatic without you needing to implement.

Take a look at the API handbook reports page and see if you can test it for this report:
https://app.gitbook.com/o/-L9rgjXCVdbnhSow2XnR/s/Nv32980j4B1B2UoS6UMi/~/changes/Qu0Lc9n9XDQRAavUHT1F/ofn-api-v0-unsupported/reports

**Comment by abdellani** [comment]
@lin-d-hop 
I understand now.  All the columns are generated regardless of the list of columns to hide, We are hiding the columns in the view.

I don't have access to the link you shared.

**Comment by sigmundpetersen** [comment]
I think this is the same location https://ofn-user-guide.gitbook.io/ofn-api-handbook/ofn-api-v0-unsupported/reports
