### ISSUE TITLE
Gallery view for shop front

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#997]
A lot of people would like a shopfront with tiles instead of the list. It would be awesome to support templates for the shopfront. That way people could have their individual shopfronts.

**Comment by pmackay** [comment]
Is the choice just likely to be grid vs tiles? Or other layouts might be considered?

Are there any other aspects to shopfronts that have been raised before? Featured products at the top, things like that?

**Comment by mkllnk** [comment]
I only know that people asked for a gallery view. This issue is not in any schedule at the moment. It has been in our offline backlog for a long time. We try to make everything transparent online.

**Comment by myriamboure** [comment]
Yes, would be great to offer 2 or 3 options for hub manager on how the shopfront will look like, and especially at least:
- one photo based approach, GoodEggs style
- one where the picture is not so central, like the current one, for hubs who are not very keen on adding nice picture for every product
...
Shopify or similar webstore tools propose different shopfronts.

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/shopfront-display/676
