### ISSUE TITLE
[Flaky] rspec ./spec/system/admin/order_spec.rb

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9971]
### What we should change and why (this is tech debt)

Failed examples:

rspec ./spec/system/admin/order_spec.rb:220 # 
    As an administrator
    I want to create and edit orders
 can't add more items than are available
rspec ./spec/system/admin/order_spec.rb:150 # 
    As an administrator
    I want to create and edit orders
 deleting item of an order when there a more than one items in the order show a modal 'Are you sure?' that the user confirm and then the item is deleted

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3437005286/jobs/5731212105

**Comment by filipefurtad0** [comment]
When addressing this one we need to remove question marks from example descriptions - like `'Are you sure?'` - this prevents artifacts from being saved on Github Actions.

**Comment by filipefurtad0** [comment]
Failing examples:

`rspec ./spec/system/admin/order_spec.rb:150`

`rspec ./spec/system/admin/order_spec.rb:220`

`rspec ./spec/system/admin/order_spec.rb:334`

**Comment by drummer83** [comment]
Another occurrence of `rspec ./spec/system/admin/order_spec.rb:334` here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6448547177/job/17505927953

**Comment by drummer83** [comment]
And one more here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6468131388/job/17559534479
Has anything changed around this?

**Comment by drummer83** [comment]
And again: https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6487151301/job/17616831093

**Comment by mkllnk** [comment]
Here's another one:

```
Failures:

  1) 
    As an administrator
    I want to create and edit orders
 can't add more items than are available
     Failure/Error: click_button("OK")
     
     Capybara::Cuprite::ObsoleteNode:
       The element you are trying to interact with is either not part of the DOM, or is not currently visible on the page (perhaps display: none is set). It is possible the element has been replaced by another element and you meant to interact with the new element. If so you need to do a new find in order to get a reference to the new element.
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_create_and_edit_orders_can_t_add_more_items_than_are_available_581.png

     
     # ./spec/system/admin/order_spec.rb:353:in `block (2 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Ferrum::NodeNotFoundError:
     #   No node with given id found
     #   ./spec/system/admin/order_spec.rb:353:in `block (2 levels) in <main>'


Finished in 4 minutes 12.7 seconds
65 examples, 1 failure

Failed examples:

rspec ./spec/system/admin/order_spec.rb:334 # 
```
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/6713387720/job/18244861316

**Comment by mkllnk** [comment]
Since this has been coming up a lot lately, I looked into the spec fails and finally found out what's happening:

* https://github.com/openfoodfoundation/openfoodnetwork/commit/b70d3c3824abee3f01f12fbb585f78bc4a567062

I don't know yet what the solution is though. We probably have to fix the Javascript that's still dispatching the click event.
