### ISSUE TITLE
Customer names and addresses leaking between checkout sessions

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9991]
## Description

Seems to affect legacy checkout only.

Since last release, customer names and addresses leaking between checkout sessions: a customer checkouts and finds other names and details.

This leads to orders placed with incorrect names and addresses.

## Expected Behavior

Customers should not find other customers details on the checkout screen.

## Actual Behaviour

Customers are find other customers details on the checkout screen.

## Steps to Reproduce

There are some details which are not yet clear, but this worked:

On a given session/browser
1. Login as a customer, add some items and visit the checkout screen
2. Select save as default billing address. Complete checkout.

On another session/browser
3. Create a new user.
4. Login as the new user and visit the shop on step 1.
5. Proceed to checkout -> see the customer details from step 2. are pre-filled on the checkout

## Your Environment

* Version used: v4.2.21
* Browser name and version: 
* Operating System and version (desktop or mobile):

**Comment by sigmundpetersen** [comment]
I guess this needs to be taken into account if adding caching again.
What's the best process? 
Remove bug label and update the description with reference to #9926?
Move to Dev Ready or All the things?
